### ISSUE TITLE
KafkaConsumer loosing group on broker restart

### ISSUE THREAD

**Issue by DEvil0000** [edenhill/librdkafka#1006]
Description
===========
2 Kafka Brokers.
Topics with 2 partitions replication factor 2.
Some KafkaConsumers.

When I restart a broker half to all KafkaConsumers loose their group and are not recovering correct.
Before the restart "/opt/kafka/bin/kafka-run-class.sh kafka.admin.ConsumerGroupCommand --bootstrap-server localhost:9092 --list --new-consumer" shows groups, after the restart it does not show most to all.

How to reproduce
================
Restart a broker which is actually used. (Maybe a leader change of some sort is causing this)

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
master (c73d2bbaf6a4c15ea9d196ae1f9d79e448e119e6)
 - [x] Apache Kafka version: 
0.9.0.1
 - [x] librdkafka client configuration:
nothing special:
socket.keepalive.enable=true
session.timeout.ms=6000
partition.assignment.strategy=roundrobin
enable.auto.commit=true
auto.commit.interval.ms=100
group.id=<whatever>
event_cb
rebalance_cb
 - [x] Operating system:
ubuntu 14.04
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Consumers stop working, wont consume, after a leader change?

**Comment by DEvil0000** [comment]
Sorry for my unprecise description there:
They are still consuming but the broker is not aware of their consumer group anymore.
Its like the consumer group (and its handling) died but the consumers (kafkaConsumers) are still reading.

**Comment by vin-d** [comment]
I see this one too and I think it could be the same issue I notified here :
https://github.com/edenhill/librdkafka/issues/947

@DEvil0000 can you check if you have the same issue with a "cluster" of just one Kafka server.
- If you shut it down, is a rebalance revoke triggered to the consumer ?
- if you restart it right after, does the consumer gets a rebalance assign callback ?

The detail is (if with both see the same issue) that the KafkaConsumer can still consume(=read the partition) as it doesn't need to be part of the consumer group to read messages. But if it tries to commit offsets, the server discards the commit and there is no callback at all to the consumer.

**Comment by DEvil0000** [comment]
Guess it is at least related.

**Comment by vin-d** [comment]
Note that I have also tested c571043 and cannot see the issue happenning with it.
The CGRP heartbeat from the KafkaConsumer is present as soon as my kafka server restarts.
Then the Kafka server doesn't drop the KafkaConsumer from its group members 30sec after restart.

**Comment by DEvil0000** [comment]
So we can be sure it is the same issue for both tickets right?
Just to mention: c571043a18f656c47f725223ffce3a65eeee261a had other issues with group handling fixed shortly before 39ba864f9d649e3888ec0c9ae4ef3fd73bae5ddb - so I guess this fix causes this bug.
I think the ticket was #844 (@vin-d seams like we have the same issues)
Additionally I can imagine this issue is also related to #939
It is all about group handling and such

**Comment by DEvil0000** [comment]
@edenhill is there any progress on this issue? do you need more information from us?

**Comment by edenhill** [comment]
Sorry, I haven't had time to look into this yet, it is on my list.

**Comment by coberty** [comment]
I'm having a similar issue after switching from 0.9.2 to 0.9.3. I have one broker on localhost.
It's easy to reproduce - just restart broker while application is running and waiting for messages.
After restart there are no more group heartbeats.

**Comment by vin-d** [comment]
fixed (tested with https://github.com/edenhill/librdkafka/commit/f343ce874c0ee4e182a20026001ae70029c19daf )

**Comment by DEvil0000** [comment]
confirm fixed

**Comment by edenhill** [comment]
Thanks to both of you!
