### ISSUE TITLE
configuring kerberos in librdkafka using gnu library

### ISSUE THREAD

**Issue by kanchanagarwal3** [edenhill/librdkafka#1007]
unable to connect to kerberos enable broker(kafka consumer) using librdkafka producer
WITH_SASL=y
Libsasl2 installed..
set sasl.mechanism=GSSAPI
sasl.kerberos.service.name=kafka
sasl.kerberos.kinit.command=/usr/bin/kinit

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [x] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Your kerberos configuration is incomplete, see this:
https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka

**Comment by kanchanagarwal3** [comment]
sasl.mechanisms         GSSAPI
       sasl.kerberos.service.name      kafka
      sasl.kerberos.keytab    /usr/app/shipper/cgnkafka.keytab
      sasl.kerberos.kinit.cmd         /usr/bin/kinit
       sasl.kerberos.principal cgnkafka@HADOOPACC.HOST.MOBISTAR.BE       sasl.kerberos.min.time.before.relogin   86400000

This is my kerberos ocnfiguration..but you know i amnot getting related to SASL authentication..it just gives
%3|1484653877.541|FAIL|rdkafka#producer-1| Hdfs600.host.mobistar.be:9092/bootstrap: Receive failed: Disconnected
%3|1484653877.541|ERROR|rdkafka#producer-1| Hdfs600.host.mobistar.be:9092/bootstrap: Receive failed: Disconnected
%3|1484653878.072|FAIL|rdkafka#producer-1| Hdfs600.host.mobistar.be:9092/bootstrap: Receive failed: Disconnected

**Comment by kanchanagarwal3** [comment]
do i need to make some changes in rdkafka_broker.c to enable logs for sasl..or i need to set any parameter..i have just set WITH_SASL and reconfigured the librdkafka

**Comment by edenhill** [comment]
You can enable SASL debugging by setting the  debug config property to 'security'.

Also make sure that your bootstrap brokers actually point to the SASL_PLAINTEXT listener on the broker.

**Comment by kanchanagarwal3** [comment]
where can i debug config property...I am reeally new to this..Pls dnt mind...I am using GNU library

**Comment by edenhill** [comment]
I'm not really sure what you mean by GNU library.

You set the debug property just as you set the other configuration properties (e.g., sasl.mechanisms), which seems to be `debug security` in your program.

**Comment by kanchanagarwal3** [comment]
ok..by GNU i mean I am using GCC compiler at my end ..librdkafka is a c library of apache kafka

**Comment by kanchanagarwal3** [comment]
![image](https://cloud.githubusercontent.com/assets/25172356/22019792/f3ba5bba-dcda-11e6-8fa1-9a3ca5fe9315.png)
debug is already set to security by default..but still i dnt find any SASL authentication logs so that i can debug

**Comment by kanchanagarwal3** [comment]
Also make sure that your bootstrap brokers actually point to the SASL_PLAINTEXT listener on the broker...what do you mean by this line??pls explain

**Comment by edenhill** [comment]
No debug is not set by default, you need to set it.


When you configure your brokers you specify different listeners for PLAINTEXT, SASL_PLAINTEXT, SSL, etc.
You need to connect your client to the correct listener port, so make sure that the bootstrap server you provide to the client configration match the SASL_PLAINTEXT listener in your broker config

**Comment by kanchanagarwal3** [comment]
rd_kafka_conf_set(kafka_conf,"debug","security",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"security.protocol","sasl_plaintext",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.kerberos.principal","cgnkafka@HADOOPACC.HOST.MOBISTAR.BE",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.mechanisms","GSSAPI",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.service_name","kafka",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.kerberos.kinit.cmd","/usr/bin/kinit",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.kerberos.keytab","/usr/app/shipper/cgnkafka.keytab",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.kerberos.min.time.before.relogin",86400000,errstr,sizeof(errstr));
..ok look i have set like ds debug as wll..but stilll no change

**Comment by kanchanagarwal3** [comment]
where can i find the listener port for SASL_PLAINTEXT..id it rdkafka_conf.c file..and how can i set it?

**Comment by edenhill** [comment]
You do not have to alter the librdkafka source code to configure it, you use the configuration interface for that.

The listener port is configured on the **broker**, check the broker configuration.

Also, I dont see you adding any bootstrap brokers to your config (bootstrap.servers).

**Comment by kanchanagarwal3** [comment]
rd_kafka_conf_set(kafka_conf,"debug","security",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"bootstrap.servers","SASL_PLAINTEXT://Hdfs600.host.mobistar.be:9092",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"security.protocol","sasl_plaintext",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.kerberos.principal","cgnkafka@HADOOPACC.HOST.MOBISTAR.BE",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.mechanisms","GSSAPI",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.service_name","kafka",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.kerberos.kinit.cmd","/usr/bin/kinit",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.kerberos.keytab","/usr/app/shipper/cgnkafka.keytab",errstr,sizeof(errstr));
rd_kafka_conf_set(kafka_conf,"sasl.kerberos.min.time.before.relogin",86400000,errstr,sizeof(errstr));
..ok see this is th enew one with bootstrapserver ..

**Comment by kanchanagarwal3** [comment]
but there is no change inoutput..and most surprisingly..if i write anythng wrong then also no error...i thnk it isnt compilng

**Comment by kanchanagarwal3** [comment]
%3|1484656651.326|FAIL|rdkafka#producer-1| Hdfs600.host.mobistar.be:9092/bootstrap: Receive failed: Disconnected
%3|1484656651.326|ERROR|rdkafka#producer-1| Hdfs600.host.mobistar.be:9092/bootstrap: Receive failed: Disconnected
%3|1484656651.856|FAIL|rdkafka#producer-1| Hdfs600.host.mobistar.be:9092/bootstrap: Receive failed: Disconnected
..got this error...

**Comment by edenhill** [comment]
Please paste your broker config

**Comment by kanchanagarwal3** [comment]
KafkaBrokers            plaintext://Hdfs600.host.mobistar.be:9092
KafkaTopic              cgn.int.ship
# KafkaConfigOption     compression.codec       snappy

**Comment by edenhill** [comment]
The broker's configuration (server.properties file)

**Comment by kanchanagarwal3** [comment]
i dnt have that file..it isin apache kafka

**Comment by edenhill** [comment]
As your Kafka administrator exactly what port you should connect to for SASL_PLAINTEXT

**Comment by kanchanagarwal3** [comment]
I am using Unix environment

**Comment by kanchanagarwal3** [comment]
It is 9092 port

**Comment by edenhill** [comment]
Okay, then check your broker logs why it is disconnecting/rejecting your client.

**Comment by kanchanagarwal3** [comment]
where can i check broker logs?

**Comment by edenhill** [comment]
Ask your Kafka infrastructure engineers to check the logs.

**Comment by kanchanagarwal3** [comment]
Ok thenks...do i need to modify rdkafka_sasl.c or any other file which come in librdkafka library to configure kerberos

**Comment by edenhill** [comment]
No, use the configuration interface. See previous comments and the wiki link

**Comment by kanchanagarwal3** [comment]
hi,i saw the brokers logs butthere is no update in  th elogs..actually it is not able to connect to broker itself...i am getting this error
%3|1484731234.789|FAIL|rdkafka#producer-1| hdfs500.host.mobistar.be:9092/bootstr                                                                                        ap: Receive failed: Disconnected
pls suggest

**Comment by edenhill** [comment]
"Disconnected" means the client managed to connect but that the broker disconnected the client.
The reason is typically printed in broker logs.
Which broker logs did you check?

**Comment by kanchanagarwal3** [comment]
I check the broker logs on the server side (receiving end) where i am tryng to conenct

**Comment by edenhill** [comment]
What are the broker log file names you checked?

**Comment by kanchanagarwal3** [comment]
sever.log

**Comment by kanchanagarwal3** [comment]
sorry..server.log

**Comment by edenhill** [comment]
Can you paste the `listeners=..` line from your server.properties?

**Comment by kanchanagarwal3** [comment]
listeners=PLAINTEXT://:9093,SASL_PLAINTEXT://:9092

**Comment by kanchanagarwal3** [comment]
hi,thenks,,now i am getting errors..
but camn you help me reslve this
%7|1484733051.523|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: Initializing SASL client: service name kafka, hostname hdfs500.host.mobistar.be, mechanisms GSSAPI
%7|1484733051.523|SASLREFRESH|rdkafka#producer-1| Refreshing SASL keys with command: /usr/bin/kinit -S "kafka/hdfs500.host.mobistar.be" -k -t "/usr/app/shipper/cgnkafka.keytab" cgnkafka@HADOOPACC.HOST.MOBISTAR.BE
%7|1484733051.538|SASLREFRESH|rdkafka#producer-1| SASL key refreshed
%7|1484733051.538|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: Available SASL mechanisms: EXTERNAL
%2|1484733051.538|LIBSASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: No worthy mechs found
%3|1484733051.538|FAIL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start): SASL(-4): no mechanism available: No worthy mechs found

**Comment by edenhill** [comment]
Your libsasl/cyrus installation seems to be missing kerberos modules, try installing  cyrus-sasl-devel package too

**Comment by kanchanagarwal3** [comment]
i have already cyrus..but when i check its mech support list
i dnt see GSSAPI mechanism

**Comment by kanchanagarwal3** [comment]
libsasl has alsobeen installed...i m passing the path to sasl thhrough SASL_PATH variable

**Comment by kanchanagarwal3** [comment]
and you know i just check now whether kerberos tickt is created or not...by using klist command..i cans ee a ticket is creeated

**Comment by kanchanagarwal3** [comment]
%2|1484733735.450|LIBSASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: No worthy mechs found....i think i cannot fing GSAAPI mechlist in libsasl

**Comment by edenhill** [comment]
try installing cyrus-sasl-gssapi

**Comment by kanchanagarwal3** [comment]
ok

**Comment by kanchanagarwal3** [comment]
Is there any package in libsasl that supports GSSAPI mechanism..because u know i have used libsasl evrywhere

**Comment by edenhill** [comment]
I was hoping cyrus-sasl-gssapi would provide that. Did it work?

**Comment by kanchanagarwal3** [comment]
ok then..i am installing..gv me sometime

**Comment by kanchanagarwal3** [comment]
%3|1484738807.161|ERROR|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start): SASL(-4): no mechanism available: No worthy mechs found..no change

**Comment by kanchanagarwal3** [comment]
i havbe installed and provided path to it via SASL_PATH...is there no way to support GSSAPI through libsasl library??

**Comment by edenhill** [comment]
Is it still only listing EXTERNAL as mechanism?

**Comment by edenhill** [comment]
Look for this line:
`..|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: Available SASL mechanisms: <WHAT DOES THIS SAY?>`

**Comment by kanchanagarwal3** [comment]
%7|1484738807.161|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: Available SASL mechanisms: EXTERNAL
%2|1484738807.161|LIBSASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: No worthy mechs found

**Comment by edenhill** [comment]
Setting up your system libraries to support Kerberos/GSSAPI is outside the scope  of librdkafka open source support. Please consult your system documentation or contact your system vendor support.

When you have GSSAPI listed as a SASL mechanism you should get the client to authenticate, if not please reopen this issue.

**Comment by kanchanagarwal3** [comment]
but in the CONFIGURATION.md file...sasl.mechanism is GSSAPI ..then how can we say it is not suopported

**Comment by edenhill** [comment]
That means librdkafka was built to support GSSAPI authentication using a SASL library (cyrus libsasl2), but GSSAPI must be implemented and supported by libsasl2.

**Comment by kanchanagarwal3** [comment]
Hi,I am using librdkafka of github..

**Comment by edenhill** [comment]
librdkafka does not implement SASL GSSAPI authentication, it uses the cyrus-sasl (libsasl2) library for that.

libsasl2 is just a generic SASL framework, it depends on sub-libraries to implement the actual authentication mechanisms (such as GSSAPI).
Therefore you will need to make sure the proper sub libraries for libsasl2 is installed so that GSSAPI authentication is made available.
Since library installation is platform/OS dependent that is outside the scope of librdkafka to instruct how to properly install these libraries.
So please consult your operating system documentation or support to get help how to make your cyrus-sasl/libsasl2 installation support GSSAPI.
When you have that properly installed then the librdkafka client should report "GSSAPI" in the list of supported mechanisms and you should be able to authenticate with Kerberos.

**Comment by kanchanagarwal3** [comment]
yes you are rigth after i instaaled cyraus-sasl-gssapi ...
i can see in sasl2-shared-mechlist
Library supports: ANONYMOUS,LOGIN,PLAIN,EXTERNAL,GSSAPI,GSS-SPNEGO

**Comment by kanchanagarwal3** [comment]
but even though i am getting same error..becuase actually librdkafka is searching GSSAPI is libsasl2 library..

**Comment by edenhill** [comment]
Please paste logs from librdkafka again after this fix

**Comment by kanchanagarwal3** [comment]
%2|1484742330.329|LIBSASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: No worthy mechs found
%3|1484742330.329|FAIL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start): SASL(-4): no mechanism available: No worthy mechs found
%3|1484742330.329|ERROR|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start): SASL(-4): no mechanism available: No worthy mechs found
%3|1484742330.329|ERROR|rdkafka#producer-1| 1/1 brokers are down
%7|1484742331.346|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: Initializing SASL client: service name kafka, hostname hdfs500.host.mobistar.be, mechanisms GSSAPI

**Comment by edenhill** [comment]
There should be a line like this above that:
..|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: Available SASL mechanisms: <WHAT DOES THIS SAY?>

**Comment by kanchanagarwal3** [comment]
yes rght..there is
%7|1484742331.359|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: Available SASL mechanisms: EXTERNAL
%2|1484742331.359|LIBSASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9093/bootstrap: No worthy mechs found

**Comment by kanchanagarwal3** [comment]
It says external

**Comment by kanchanagarwal3** [comment]
if u see 
-rwxr-x--- 1 shipper shipper   36904 Jan 18 12:20 libgssapiv2.so.3.0.0
lrwxrwxrwx 1 shipper shipper      20 Jan 18 12:21 libgssapiv2.so.3.0.0.1 -> libgssapiv2.so.3.0.0
-rwxr-x--- 1 shipper shipper  134344 Jan 13 14:00 libgssrpc.so
lrwxrwxrwx 1 shipper shipper      12 Jan 16 06:01 libgssrpc.so.1 -> libgssrpc.so

**Comment by kanchanagarwal3** [comment]
i hve installed this ..and giving thepath of this directory in SASL_PATH variable

**Comment by edenhill** [comment]
I'm sorry, I dont know how to solve that.

**Comment by rajatkusumwal** [comment]
@edenhill I have a similar issue I have some limitations to my env. So cannot do a apt get install libsasl2-modules-gssapi-mit.

Though i have separately got the .deb package and installed it in a non root location.

Is it possible to tell librdkafka to use  SASL_PATH variable in that case.

Or does it looks for the libsasl2 deps in the root lib folder.

My kafka broker only supports GSSAPI.

Where as my client supports all the other mechanism apart from GSSAPI.

**Comment by edenhill** [comment]
The linker will look for libsasl2...so in the standard library locations as configured with /etc/ld.so.conf*, typically: /lib, /usr/lib, /usr/local/lib.
You can temporarily tell it to look in additional paths by setting the LD_LIBRARY_PATH environment variable to a library directory path, e.g.:
`LD_LIBRARY_PATH=/root/my/libs ./my-program`

**Comment by rajatkusumwal** [comment]
@edenhill 
LD_LIBRARY_PATH=/root/my/libs ./my-program
Does this only hold true when am doing a make install from librdkafka source code?

Cause i'm installing librdkafka-dev using a deb package
https://packages.debian.org/sid/librdkafka-dev

Which I further use to build my confluent kafka python pip module.

So is it that the dependency is already linked and librdkafka looks for the libsasl2 binaries from a specific path to which it was linked while being build, rather than using "LD_LIBRARY_PATH"?

**Comment by edenhill** [comment]
No, LD_LIBRARY_PATH is a program runtime thing, not build time.

If you need to tell librdkafka's build system where to find libraries you should use LDFLAGS, like so:
`LDFLAGS=-L/root/my/libs CPPFLAGS=-I/root/includefiles ./configure`.

But on debian you typically only need to do:
`sudo apt-get install libsasl2-dev libssl-dev`

and then
`./configure`  in librdkafka

**Comment by rajatkusumwal** [comment]
@edenhill 
Does merely setting up these env variables will not be sufficient.
LDFLAGS=-L/root/my/libs CPPFLAGS=-I/root/includefiles
Why do I have to do a ./configure after that?
So I need to make install it again?
Librdkafka binaries are already present in my system using https://packages.debian.org/sid/librdkafka-dev.

**Comment by edenhill** [comment]
Oh, sorry, I misinterpreted your issue. 
You want your application to find the gssapi modules? It seems SASL_PATH is the way to go but I haven't tried this myself. This is more of an issue for cyrus-sasl than librdkafka

**Comment by rajatkusumwal** [comment]
@edenhill Thanks for the quick response. 👍

**Comment by edenhill** [comment]
I think the package is called cyrus-sasl-gssapi on CentOS:
https://centos.pkgs.org/7/centos-x86_64/cyrus-sasl-gssapi-2.1.26-23.el7.x86_64.rpm.html

**Comment by faladu** [comment]
Thank you that fixed it ! 
Any chance you could update the article in github about kerberos and librdkafka to include that for centos?

**Comment by edenhill** [comment]
Done

**Comment by write2jaydeep** [comment]
@edenhill I have a similar problem. I have some limitations to my env. So cannot do a apt get install libsasl2-modules-gssapi-mit.
I have compiled Krb5 and Cyrus-sals on my system. I build librdkafka with this configure command:
`./configure --prefix=install --bindir=/Stratusoft/ARI_Techsupport/work_dir/Kerberos/src/clients/kinit --libdir=/Stratusoft/ARI_Techsupport/work_dir/cyrus/cyrus-sasl-2.1.27/install/lib --libdir=/Stratusoft/ARI_Techsupport/work_dir/cyrus/cyrus-sasl-2.1.27/install/lib/sasl2`

now I run my application. it works perfectly on the system where I build things. when I deployed to another system, and it is still looking for GSSAPI module on build location(/Stratusoft/ARI_Techsupport/work_dir/cyrus/cyrus-sasl-2.1.27/install/lib/sasl2). even I set LD_LIBRARY_PATH with dir name where I copied all *.so (shared libs), but it doesn't work.

can you please guide me, what I am doing wrong here? 

Thanks!
JD

**Comment by edenhill** [comment]
@write2jaydeep librdkafka itself does not attempt to load any cyrus-sasl modules, librdkafka simply links to libsasl2 (see `ldd librdkafka.so` to see where it looks).
The sasl modules/plugins are loaded by libsasl2, and I'm guessing it is using a combination of the system default linker paths (ld.so.conf) and a build-time configuration property where to look, but that is outside the scope of librdkafka.

**Comment by write2jaydeep** [comment]
@edenhill Thanks! I appreciate your help.
