### ISSUE TITLE
Committing before consumption results in NULL msg pointer for the consumed msg

### ISSUE THREAD

**Issue by archanapujar** [edenhill/librdkafka#1011]
Description
===========
If I commit an offset to the topic partition before consuming from it, the consumed message is NULL

How to reproduce
================
- Produce 5 messages to a topic with 10 partitions
- Assign topic partition to the consumer 
- Commit offset 0 to all the topic partitions
- Call rd_kafka_consume_poll() the recived msg pointer is NULL.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.2
 - [ ] Apache Kafka version:  kafka_2.11-0.10.0.1
 - [ ] librdkafka client configuration:
 - [ ] Operating system: centos
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Since you start the consumer after messages have been produced and the default starting offset is latest/largest/last/end offset, this makes sense.
The commit doesn't come into play until the next time you run the client.
