### ISSUE TITLE
sasl authentication failure error using librdkafka library

### ISSUE THREAD

**Issue by kanchanagarwal3** [edenhill/librdkafka#1015]
%3|1484896879.875|FAIL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)
%3|1484896879.875|ERROR|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)
%3|1484896879.875|ERROR|rdkafka#producer-1| 1/1 brokers are down
%7|1484896880.892|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Initializing SASL client: service name kafka, hostname hdfs500.host.mobistar.be, mechanisms GSSAPI
%7|1484896880.892|SASLREFRESH|rdkafka#producer-1| Refreshing SASL keys with command: /usr/bin/kinit -S "kafka/hdfs500.host.mobistar.be" -k -t "
" cgnkafka@HADOOPACC.HOST.MOBISTAR.BE
kinit: Key table file '

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Searching for that error message gives:
```
Matching credential not found

Cause:
The matching credential for your request was not found. Your request requires credentials that are unavailable in the credentials cache.

Solution:
Destroy your tickets with kdestroy, and create new tickets with kinit.
```

http://docs.oracle.com/cd/E19253-01/816-4557/trouble-6/index.html

**Comment by kanchanagarwal3** [comment]
Hi,Thanks for you reply...%7|1484901459.042|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Send SASL frame to broker (662 bytes)
%7|1484901459.052|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Received SASL frame from broker (108 bytes)
%7|1484901459.064|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Send SASL frame to broker (0 bytes)
%7|1484901459.074|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Received SASL frame from broker (32 bytes)
%7|1484901459.075|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Send SASL frame to broker (32 bytes)
%7|1484901459.075|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Authenticated as cgnkafka@HADOOPACC.HOST.MOBISTAR.BE using GSSAPI (gssapiv2)
%3|1484901460.282|FAIL|rdkafka#producer-1| sasl_plaintext://hdfs602.host.mobistar.be:9092/272: Failed to initialize SASL authentication: SASL handshake failed (start): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)
%3|1484901460.282|ERROR|rdkafka#producer-1| sasl_plaintext://hdfs602.host.mobistar.be:9092/272: Failed to initialize SASL authentication: SASL handshake failed (start): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)
%2|1484901460.283|LIBSASL|rdkafka#producer-1| sasl_plaintext://hdfs600.host.mobistar.be:9092/271: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)

**Comment by kanchanagarwal3** [comment]
if you see for frst broker hdfs500 it is working..but we have three brokers..it is not working for other two brokers..hdfs602,hdfs600

**Comment by kanchanagarwal3** [comment]
and its oobvious because
 Refreshing SASL keys with command: /usr/bin/kinit -S "**kafka/hdfs500.host.mobistar.be**" -k -t "/usr/app/shipper/cgnkafka.keytab" cgnkafka@HADOOPACC.HOST.MOBISTAR.BE....how can i ask to switch brokers in kinit while refreshing

**Comment by edenhill** [comment]
Can you provide your client configuration?

**Comment by kanchanagarwal3** [comment]
KafkaBrokers            sasl_plaintext://hdfs500.host.mobistar.be:9092
KafkaTopic              cgn.int.ship
# KafkaConfigOption     compression.codec       snappy
KafkaConfigOption       debug   security
KafkaConfigOption       metadata.broker.list    sasl_plaintext://hdfs500.host.mobistar.be:9092,sasl_plaintext://hdfs602.host.mobistar.be:9092
KafkaConfigOption       api.version.request     true
KafkaConfigOption       security.protocol       sasl_plaintext
KafkaConfigOption       bootstrap.servers       sasl_plaintext://hdfs500.host.mobistar.be:9092
KafkaConfigOption       batch.num.messages      100
KafkaConfigOption       queue.buffer.max.ms     100
KafkaConfigOption       sasl.mechanisms         GSSAPI
KafkaConfigOption       sasl.kerberos.service.name      kafka
KafkaConfigOption       sasl.kerberos.keytab    /usr/app/shipper/cgnkafka.keytab
KafkaConfigOption       sasl.kerberos.kinit.cmd         /usr/bin/kinit
KafkaConfigOption       sasl.kerberos.principal cgnkafka@HADOOPACC.HOST.MOBISTAR.BE
KafkaConfigOption       sasl.kerberos.min.time.before.relogin   86400000
~

**Comment by edenhill** [comment]
what librdkafka version is this?

**Comment by kanchanagarwal3** [comment]
0.9.1

**Comment by kanchanagarwal3** [comment]
and kafka server where we are connecting is 0.9

**Comment by edenhill** [comment]
`KafkaConfigOption sasl.kerberos.kinit.cmd /usr/bin/kinit`
That line seems incomplete, it should feature a number of %.. tokens as described here:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by kanchanagarwal3** [comment]
you are right..

but in the CONFIGURATION.md present in my librdkafka folder..i can see

sasl.kerberos.kinit.cmd                  |  *  |                 |         kinit | Kerberos kinit command path. <br>*Type: string*

**Comment by kanchanagarwal3** [comment]
so i wrote like this..should i change?

**Comment by edenhill** [comment]
librdkafka 0.9.1 CONFIGURATION.md does not look like that::
https://github.com/edenhill/librdkafka/blob/0.9.1/CONFIGURATION.md

Are you sure you are on 0.9.1?

**Comment by kanchanagarwal3** [comment]
Name: librdkafka
Description: The Apache Kafka C/C++ library
Version: 0.9.1
Cflags: -I${includedir}
Libs: -L${libdir} -lrdkafka
Libs.private: -lpthread -lz -lcrypto -lssl -lcrypto -lsasl2 -lrt
~

**Comment by kanchanagarwal3** [comment]
I can see this in rdkafka.pc inside pkgconfig folder

**Comment by edenhill** [comment]
What does `rpm -qi librdkafka` say?

**Comment by kanchanagarwal3** [comment]
package librdkafka is not installed..

but even if it is 0.9..it should connect because kafka server is 0.9

**Comment by edenhill** [comment]
librdkafka supports all broker versions.

How did you install librdkafka?
Can you call rd_kafka_version_str() from your program and show me the output?

**Comment by kanchanagarwal3** [comment]
ok

**Comment by kanchanagarwal3** [comment]
Hi Its not returning any value..i am trying to fx it but if i look at rdkafka.h file ,..
i can see
#define RD_KAFKA_VERSION  0x00090100

**Comment by edenhill** [comment]
`printf("v: %s\n", rd_kafka_verison_str());`

How did you install librdkafka?

**Comment by kanchanagarwal3** [comment]
BROKER VRSION is 0.9.1-pre0

**Comment by kanchanagarwal3** [comment]
got this output

**Comment by edenhill** [comment]
I dont know where you found that version.
Please remove librdkafka and install 0.9.2 from here:
http://docs.confluent.io/3.1.1/installation.html#installation-yum

**Comment by kanchanagarwal3** [comment]
but the server we are connecting is 0.9..and reinstalling means evrythng will be removed...Is there no way to fix this error of SASL authentciation in this version..??why is this occuring basically?

**Comment by edenhill** [comment]
You only need to remove librdkafka, nothing else.

**Comment by edenhill** [comment]
After removing librdkafka you re-install it (and only librdkafka and librdkafka-devel packages) from the above Yum repo

**Comment by kanchanagarwal3** [comment]
Yes I will do that ..but before doing that i need to answer what was the problem in this version that caused this issue??

**Comment by edenhill** [comment]
Hard to say 0.9.1-pre0 is not a released version so it could be any point in time during development over a 6 month period.

The take-away is: Only use proper releases

**Comment by kanchanagarwal3** [comment]
Ok..i take yours words..one more doubt i have

**Comment by kanchanagarwal3** [comment]
I can see in the error....
sasl_plaintext://hdfs600.host.mobistar.be:9092/271: Initializing SASL client: service name kafka, hostname hdfs600.host.mobistar.be, mechanisms GSSAPI
%7|1484907264.127|SASLREFRESH|rdkafka#producer-1| Refreshing SASL keys with command: /usr/bin/kinit -S "kafka/hdfs500.host.mobistar.be" -k -t "/usr/app/shipper/cgnkafka.keytab" cgnkafka@HADOOPACC.HOST.MOBISTAR.BE

**Comment by kanchanagarwal3** [comment]
is it normal that you make a kinit for service  kafka/hdfs500, while you want a service ticket for hdfs600 & 602 ?

**Comment by edenhill** [comment]
Please upgrade librdkafka to 0.9.2, it is possible that this has been fixed. Thank you.

**Comment by kanchan1234** [comment]
hi,i tried uninstalling librdkafka 0.9.1 but since it is a compiled code..i am unable to unistall it ..

**Comment by kanchan1234** [comment]
the library was compiled

**Comment by edenhill** [comment]
Find the librdkafka libraries (librdkafka.so* or librdkafka.dylib*), probably somewhere in /usr/lib or /usr/local/lib and remove them.
Then compile and install a newer version of librdkafka.

**Comment by edenhill** [comment]
And try upgrading to librdkafka 0.9.3., it is the latest release

**Comment by kanchan1234** [comment]
ok thenk u..but i hv already created request for 0.9.2..so now again its a long procedure to request for 0.9.3..i think kerberos issue can be solved wit 0.9.2 also

**Comment by edenhill** [comment]
0.9.2 should be fine, yes.

**Comment by kanchan1234** [comment]
Hi,

I can see this output after the team installed librdkafka-0.9.2

I dnt see any script file to compile librdkafka..

Is it ,they forgot to install librdkafka-devel packages ..

Please confirm



[cid:image001.png@01D2806F.6C21DF10]


Thanks and regards,

Kanchan

**Comment by edenhill** [comment]
Your image was not attached, try dragging it to the github issue comment field in your web browser

**Comment by kanchan1234** [comment]
[root@blackcat tmp]$rpm -ql librdkafka-0.9.2
/usr/lib64/librdkafka++.so.1
/usr/lib64/librdkafka.so.1
/usr/share/licenses/librdkafka-0.9.2
/usr/share/licenses/librdkafka-0.9.2/LICENSE
/usr/share/licenses/librdkafka-0.9.2/LICENSE.pycrc
/usr/share/licenses/librdkafka-0.9.2/LICENSE.queue
/usr/share/licenses/librdkafka-0.9.2/LICENSE.regexp
/usr/share/licenses/librdkafka-0.9.2/LICENSE.snappy
/usr/share/licenses/librdkafka-0.9.2/LICENSE.tinycthread
/usr/share/licenses/librdkafka-0.9.2/LICENSE.wingetopt
/usr/share/licenses/librdkafka-0.9.2/LICENSE.xxhash

**Comment by edenhill** [comment]
Yeah, that's the runtime package. To build your application you also need the librdkafka-devel package

**Comment by kanchan1234** [comment]
after asking to install it...they installed version 0.9.3 ..i can see this
pls tell me why i m not getting devconf.sh file

how can i compile it?
[root@blackcat librdkafka-devel-0.9.3]$ls -ltr
total 64
-rw-r--r-- 1 root root  5932 Jan 23 15:04 README.md
-rw-r--r-- 1 root root 19722 Jan 23 15:04 INTRODUCTION.md
-rw-r--r-- 1 root root  7542 Jan 23 15:04 CONTRIBUTING.md
-rw-r--r-- 1 root root 23997 Jan 23 16:17 CONFIGURATION.md
drwxr-xr-x 2 root root  4096 Feb  6 11:08 examples

**Comment by edenhill** [comment]
dev-conf.sh is for building librdkafka itself, you dont need that as you already have preinstalled librdkafka and librdkafka-devel packages.

**Comment by kanchan1234** [comment]
ok got it..

**Comment by kanchan1234** [comment]
Now as per CONFIGURATION property
I have added this in the kafka config for kinit
but still getting error...
KafkaConfigOption       sasl.kerberos.kinit.cmd         kinit -S kafka -k -t /usr/app/shipper/cgnkafka.keytab cgnkafka@HADOOPACC.HOST.MOBISTAR.BE

**Comment by kanchan1234** [comment]
but i can see tickets are genearted..that means kinit is wroking

**Comment by kanchan1234** [comment]
%3|1486378815.366|ERROR|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)
%7|1486378816.383|AUTH|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Auth in state CONNECT (handshake not supported)
%7|1486378816.383|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Initializing SASL client: service name kafka, hostname hdfs500.host.mobistar.be, mechanisms GSSAPI
%7|1486378816.383|SASLREFRESH|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Refreshing SASL keys with command: kinit -S kafka -k -t /usr/app/shipper/cgnkafka.keytab cgnkafka@HADOOPACC.HOST.MOBISTAR.BE

**Comment by kanchan1234** [comment]
I think brokers are down..I have asked team to check that

**Comment by edenhill** [comment]
`(Matching credential not found)`
That looks like an authentication error.

**Comment by kanchanagarwal3** [comment]
i have tried kdestory ..but still getting same error

**Comment by edenhill** [comment]
As mentioned previously, enable debugging in jaas and check the broker logs/stderr

**Comment by kanchan1234** [comment]
ok..jaas file from broker side ?

**Comment by kanchan1234** [comment]
one more thing..the broker is 0.9 version ..so is there any issue of compatibility ?

**Comment by edenhill** [comment]
broker side jaas file, yes.
0.9 should be fine.

**Comment by kanchan1234** [comment]
i have seen  broker side jaas conf file..

only confusion is with principal name..
in jaas file-it is ->principal="kafka/hdfs600.host.mobistar.be@HADOOPACC.HOST.MOBISTAR.BE";
from our side in config file ,
KafkaConfigOption       sasl.kerberos.principal cgnkafka@HADOOPACC.HOST.MOBISTAR.BE

moreover in kinit command 
i wrote kinit -S kafka -k -t /usr/app/shipper/cgnkafka.keytab cgnkafka@HADOOPACC.HOST.MOBISTAR.BE

there is no broker.name field?

is this the reason for auth error?

**Comment by edenhill** [comment]
The broker's JAAS KafkaServer principal service (up to the first slash) should match the sasl.kerberos.service.name of the client. In your case it is "kafka", which is default, good.

The sasl.kerberos.principal is the client's servicename/host@realm.
This principal must be added to the broker's keytab as instructed here:
https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka#3-create-client-principal-and-keytab-on-kerberos-server

**Comment by kanchan1234** [comment]
ok thenks ..I have noticed one thing.as suggested 
if i had host name in sasl.kerberos.principal ->kafka/hdfs600.host.mobistar.be@HADOOPACC.HOST.MOBISTAR.BE
i get no kerberos credential available error
but if i use cgnkafka@HADOOPACC.HOST.MOBISTAR.BE ->i see matchning vredentails error but ticket gets genearted in this case.I verified using klist

that means we have to add our principal in keytab using the link suggested by you.

It is taking only default principal i.e cgnkafka

Please confirm.

**Comment by edenhill** [comment]
I believe the hostname is required, yes.

Please follow that "Using SASL with librdkafka" guide and any other guides (Confluent's) it links to.

**Comment by kanchan1234** [comment]
Hi,now i am gettinf this,it is connecting to hdfs500 since it is present n kinit command explicaitly but not with other two brokers..
you told this problem is resolved in librdkafka 0.9.3
please suggest how to resolve this,

tart (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)
%7|1486463880.752|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Send SASL frame to broker (662 bytes)
%7|1486463880.762|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Received SASL frame from broker (108 bytes)
%7|1486463880.774|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Send SASL frame to broker (0 bytes)
%7|1486463880.784|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Received SASL frame from broker (32 bytes)
%7|1486463880.784|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Send SASL frame to broker (32 bytes)
%7|1486463880.784|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Authenticated as cgnkafka@HADOOPACC.HOST.MOBISTAR.BE using GSSAPI (gssapiv2)
%7|1486463880.841|AUTH|rdkafka#producer-1| sasl_plaintext://hdfs602.host.mobistar.be:9092/272: Auth in state CONNECT (handshake not supported)
%7|1486463880.841|SASL|rdkafka#producer-1| sasl_plaintext://hdfs602.host.mobistar.be:9092/272: Initializing SASL client: service name kafka, hostname hdfs602.host.mobistar.be, mechanisms GSSAPI
%7|1486463880.841|SASLREFRESH|rdkafka#producer-1| sasl_plaintext://hdfs602.host.mobistar.be:9092/272: Refreshing SASL keys with command: /usr/bin/kinit -S kafka/hdfs500.host.mobistar.be -k -t /usr/app/shipper/cgnkafka.keytab cgnkafka@HADOOPACC.HOST.MOBISTAR.BE

**Comment by edenhill** [comment]
Can you paste the complete log line that says "Matching credential not found"?

It looks like you manage to auth  with broker hdfs500:
`%7|1486463880.784|SASL|rdkafka#producer-1| sasl_plaintext://hdfs500.host.mobistar.be:9092/bootstrap: Authenticated as cgnkafka@HADOOPACC.HOST.MOBISTAR.BE using GSSAPI (gssapiv2)`

**Comment by kanchan1234** [comment]
%3|1486464603.955|FAIL|rdkafka#producer-1| sasl_plaintext://hdfs602.host.mobistar.be:9092/272: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)

**Comment by kanchan1234** [comment]
i undertand it is due to the sasl.kerberos.kinit -> /usr/bin/kinit -S kafka/hdfs500.host.mobistar.be -k -t /usr/app/shipper/cgnkafka.keytab cgnkafka@HADOOPACC.HOST.MOBISTAR.BE

It is not giving access to other two brokers

**Comment by kanchan1234** [comment]
look,this the erro now
after a change in kinuit command as /usr/bin/kinit -S kafka/hdfs600.host.mobistar.be -k -t /usr/app/shipper/cgnkafka.keytab cgnkafka@HADOOPACC.HOST.MOBISATR.BE
%7|1486465130.210|SASL|rdkafka#producer-1| sasl_plaintext://hdfs600.host.mobistar.be:9092/bootstrap: Send SASL frame to broker (662 bytes)
%7|1486465130.221|SASL|rdkafka#producer-1| sasl_plaintext://hdfs600.host.mobistar.be:9092/bootstrap: Received SASL frame from broker (108 bytes)
%7|1486465130.232|SASL|rdkafka#producer-1| sasl_plaintext://hdfs600.host.mobistar.be:9092/bootstrap: Send SASL frame to broker (0 bytes)
%7|1486465130.242|SASL|rdkafka#producer-1| sasl_plaintext://hdfs600.host.mobistar.be:9092/bootstrap: Received SASL frame from broker (32 bytes)
%7|1486465130.242|SASL|rdkafka#producer-1| sasl_plaintext://hdfs600.host.mobistar.be:9092/bootstrap: Send SASL frame to broker (32 bytes)
%7|1486465130.242|SASL|rdkafka#producer-1| sasl_plaintext://hdfs600.host.mobistar.be:9092/bootstrap: Authenticated as cgnkafka@HADOOPACC.HOST.MOBISTAR.BE using GSSAPI (gssapiv2)

**Comment by kanchan1234** [comment]
is there any way to assingn all three in avariable and then append in kinit command 
will it work?

**Comment by edenhill** [comment]
Can you paste your librdkafka client configuration?

**Comment by kanchan1234** [comment]
KafkaBrokers            sasl_plaintext://hdfs500.host.mobistar.be:9092,sasl_plaintext://hdfs600.host.mobistar.be:9092
KafkaTopic              cgn.int.ship
# KafkaConfigOption     compression.codec       snappy
KafkaConfigOption       debug   security
KafkaConfigOption       metadata.broker.list    sasl_plaintext://hdfs600.host.mobistar.be:9092,sasl_plaintext://hdfs602.host.mobistar.be:9092
KafkaConfigOption       api.version.request     false
KafkaConfigOption       security.protocol       sasl_plaintext
KafkaConfigOption       bootstrap.servers       sasl_plaintext://hdfs600.host.mobistar.be:9092
KafkaConfigOption       batch.num.messages      100
KafkaConfigOption       queue.buffer.max.ms     100
KafkaConfigOption       sasl.mechanisms         GSSAPI
KafkaConfigOption       sasl.kerberos.service.name      kafka
KafkaConfigOption       sasl.kerberos.keytab    /usr/app/shipper/cgnkafka.keytab
KafkaConfigOption       sasl.kerberos.kinit.cmd         /usr/bin/kinit -S kafka/hdfs600.host.mobistar.be -k -t /usr/app/shipper/cgnkafka.keytab cgnkafka@HADOOPACC.HOST.MOBISTAR.BE
KafkaConfigOption       sasl.kerberos.principal cgnakfka@HADOOPACC.HOST.MOBISTAR.BE
KafkaConfigOption       sasl.kerberos.min.time.before.relogin   86400000
~

**Comment by edenhill** [comment]
This isn't so strange since you have hardcoded the broker name in sasl.kerberos.kinit.cmd:
`KafkaConfigOption sasl.kerberos.kinit.cmd /usr/bin/kinit -S kafka/hdfs600.host.mobistar.be -k -t /usr/app/shipper/cgnkafka.keytab cgnkafka@HADOOPACC.HOST.MOBISTAR.BE`

That command is ran for each broker.

Is there any reason why you did not leave it at the default value?
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by kanchan1234** [comment]
what is the default value for brokers.name

**Comment by edenhill** [comment]
the name that you provide as bootstrap broker, and the names that brokers advertise themselves as.

**Comment by kanchan1234** [comment]
if i use only /usr/bin/kinit -S kafka-k -t /usr/app/shipper/cgnkafka.keytab cgnkafka@HADOOPACC.HOST.MOBISTAR.BE..then i am getting auth error

**Comment by edenhill** [comment]
Please see the documentation for `sasl.kerberos.kinit.cmd` and `sasl.kerberos.keytab` here:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

Especially observe the default values for these settings, those values will be used if you do not specify them and they should be sufficient to get your client to authenticate.

**Comment by kanchan1234** [comment]
hey thenks,thenks a lot..finally reoslved

**Comment by edenhill** [comment]
Glad to hear that.
