### ISSUE TITLE
KIP-32 - Add timestamps to Kafka message

### ISSUE THREAD

**Issue by thijsc** [edenhill/librdkafka#1016]
It would be really nice if `librdkafka` would support setting a timestamp on a message. Any plans for this?

https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message

**Comment by edenhill** [comment]
It does, but you need to enable the new protocol features by setting `api.version.request=true` on the client.
This will make the producer set the current wallclock time (UTC) for messages produced.
If you want to specify your own timestamps you need to use the new rd_kafka_producev() API

**Comment by thijsc** [comment]
Oh that's nice to hear :-). Is there also a way to get the timestamp from a message?

For other people who might look for this: This tests contains an example: https://github.com/edenhill/librdkafka/blob/15d3e7ea8589fcf0a81f5631e9d74f88630fa7bf/tests/0052-msg_timestamps.c#L79

**Comment by edenhill** [comment]
Yes, use the rd_kafka_message_timestamp() API to extract the timestamp type and timestamp of received messages. Do note that the consumer will also need `api.version.request=true`.
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L887

**Comment by thijsc** [comment]
Thanks for the information!
