### ISSUE TITLE
kafkaConsumer consumer group rebalance fail after the restart of one of the consumer

### ISSUE THREAD

**Issue by morningxidan** [edenhill/librdkafka#1019]
Description
===========

My setup:
2 Kafka Brokers.
Topics with 3 partitions , replication factor 2
high-level consumer

At first, I start 3 consumer, belong to the same consumer group. It rebalance correct.Each consumer was owning one partition.

Then I killed consumer3 , rebalance :
consumer1 - partition1
consumer2 - partition2, partition3

It worked well until I restart consumer3. At this time, rebalance_cb revoke did not being triggered. The situation is as follows:
consumer1 - partition1
consumer2 - partition2, partition3

consumer3 - partition1, partition2, partition3 

I test for dozens of times, this situation happens just twice, and I can't reproduce it any more.

How to reproduce
================

I have not found a way to reproduce this situation. It only happens sometimes after the restarts of one of the consumer in the group.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
        master
 - [x] Apache Kafka version: 
        0.9.0.1
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue
 - [x] enable.auto.commit
         true

**Comment by edenhill** [comment]
Whoops, I completely missed this issue.

Are you still seeing this with latest master / 0.9.4?
Do you have any more info (e.g., debug=cgrp output?)
