### ISSUE TITLE
Cluster events

### ISSUE THREAD

**Issue by liud** [edenhill/librdkafka#102]
My kafka8.0 cluster has 2 brokers.
192.168.12.130:9092
192.168.12.130:9093

When I called rd_kafka_brokers_add("192.168.12.130:9092,192.168.12.130:9093"), the application run well, and all messages were sent to 9092. Then I killed 192.168.12.130:9092,  the application doesn't send message to port 9093, and all message sending were failed, is this intended?

Btw, is that possible to get all the message from broker, including messages available and not available. If yes, can please advise how to config? Thanks!

**Comment by edenhill** [comment]
See #137
