### ISSUE TITLE
Where does librdkafka exactly log 

### ISSUE THREAD

**Issue by kparadkar** [edenhill/librdkafka#1020]
Q1. Where does librdkafka log? Even though i have log_level set to DEBUG i dont see anything on stdout /stderr. 
Q2. Am i missing any config?
Q3. Is there any provision to give your own log file path to librdkafka?

**Comment by edenhill** [comment]
A1. log_level is 6 by default (anything but debug) but is automatically raised to 7 (debug) when debugging is enabled. So it serves the reverse purpose: to filter out higher-leveled logs. There is really very little use for it.
A2. librdkafka does not really log anything unless there are errors. Logs are logged through the log_cb which defaults to a stderr writer, there is also a builtin syslog writer you can configure with set_log_cb(). If you want to get librdkafka to log stuff even though there are no errors you can enable debugging by setting the `debug` config property to e.g. `topic,broker`.
A3. If you want to log to a file you need to implement your own log_cb, which is simple enough to do, just implement the log_cb interface and pass your function reference to set_log_cb.
