### ISSUE TITLE
main thread of KafkaConsumer being blocked (deadlock?) by librdkafka

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#1022]
Description
===========
My test is the following  (it is done basically to find a workaround to recover from #947 )
1) loop on consume() with a subscribed KafkaConsumer
2) perdiodically (each 15s) trigger a commit (always from the consumer thread).
before I do the commit I check a few things and begin to do a consumer->assignment() call
this assignement() call blocks for ever.

I've put some trace in librdkafka and seen that assignement() call stack goes like that
rd_kafka_assignment
>rd_kafka_assignment
>>rd_kafka_op_req2
>>>rd_kafka_op_req
>>>>rd_kafka_op_req0
>>>>>rd_kafka_q_pop
>>>>>>rd_kafka_q_pop_serve
in which rko == 0 at the if(rko)
and timeout_ms == INT_MAX  [from the call stack (RD_POLL_INFINITE)]
>>>>>>>cnd_timedwait_ms(&rkq->rkq_cond, &rkq->rkq_lock, timeout_ms)
is the one blocking.

How to reproduce
================
to reproduce the blocking assignement() call I do the following but I'm not sure if any of these action have an influence into triggering the issue : 
1) I start my program,
2) I let at least one asynchronous commit be done() (note that I have offset_commit_cb registered)
3) I stop my only kafka server (**./kafka_server_stop.sh ../config/server.properties**)
4) I wait 90 seconds (not sure of the impact from this)
5) I start my kafka server (**./kafka-server-start.sh ../config/server.properties**)
note that usually 30s after starting the server I won't be able to commit and my commit_cb will get ERR_UNKNOWN_MEMBER_ID (my program don't update heartbeat since step 3 but that bug # 947)

6) the program calls  consumer->assignment() (that is done inside the the 30s window, the consumer is still considered a group member by Kafka ).
7) **the assignment() call doesn't return.**

Checklist
=========
Please provide the following information:

 - [89ed67f ] librdkafka version (release number or git tag):
 - [kafka_2.11-0.10.1.0 ] Apache Kafka version: 
 - [ c++] librdkafka client configuration:
 - [Ubuntu 16.04 ] Operating system:
 - [ ] Using the legacy Consumer
 - [x ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by vin-d** [comment]
Note that before using 89ed67f I was on
7f12b7f and the call wasn't blocking.

**Comment by edenhill** [comment]
I haven't forgotten about this issue

**Comment by edenhill** [comment]
Reproduced in regression tests.

**Comment by vin-d** [comment]
fixed (tested with https://github.com/edenhill/librdkafka/commit/f343ce874c0ee4e182a20026001ae70029c19daf )

**Comment by edenhill** [comment]
Thanks @vin-d
