### ISSUE TITLE
What does group_session_timeout_ms do?

### ISSUE THREAD

**Issue by johnrgregg3** [edenhill/librdkafka#1023]
Description
===========
The Confluent python client exposes a config parameter, session.timeout.ms, which maps to group_session_timeout_ms in the underlying librdkafka library. I looked through the code a bit, but I could not be sure I understand what I'm actually configuring if I change this parameter. Does "group" mean consumer group? In this case, the parameter has no effect for a producer, but I kind of think that is not what it means. The documentation only says "Client group session and failure detection timeout." What handshake or connection is being timed by this parameter? What sort of failure would cause us to exceed this timeout, and what would happen if we did?

How to reproduce
================

See above - just a question

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by vryabinin** [comment]
This property maps directly to Kafka **session.timeout.ms**:

_The amount of time a consumer can be out of contact with the brokers while still considered alive, defaults to 3 seconds. If a consumer goes for more than session.timeout.ms without sending a heartbeat to the group coordinator, it is considered dead and the group coordinator will trigger a rebalance of the consumer group to allocate partitions from the dead consumer to the other consumers in the group_

[https://www.safaribooksonline.com/library/view/kafka-the-definitive/9781491936153/ch04.html](url)

**Comment by johnrgregg3** [comment]
Thanks!
