### ISSUE TITLE
Producer and DeliveryReportCb::dr_cb(Message)  - lost message issue.

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#1028]
Description
===========
I use libRdKafka to produce small string messages from a list of strings to a Kafka topic.

in my `` DeliveryReportCb::dr_cb(Message &message) ``
I do the following check :
``` 
if (message.err() != RdKafka::ERR_NO_ERROR) {
  produce(&message); // here I reattempt to re-produce the message since it has failed before.
} else {
  log_to_file(message);
}

```
having my source data on hand I have find out (after consuming to the topic where messages are produced) that I a missing a few number of messages over a long period of time.

But I compare my source data with my logged file, I can actually see the missing messages in the file.

Could libRdKafka's dr_cb function reply ERR_NO_ERROR even if the message was not produced to Kafka ?
Would that be possible with a specific configuration(/mis-configuration) of kafka for example ? 

Note that everything is running on the same LAN under the same datacenter and there are no network/ system / Kafka errors reported at the time when these missing message have been "miss - produced"

How to reproduce
================
I tried to reproduce without success
The proportion of missing messages is very small (something like less than 50 over 1 million) over a duration of 10 days.

Checklist
=========
Please provide the following information:

 - [7f12b7f ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [Ubuntu 16.04 ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Are you checking the return value of produce() and properly handling those errors?

What is your topic-level configuration, especially "acks"?

Do you have any broker outages, ISR or leader changes?

**Comment by edenhill** [comment]
What client are you using to verify the messages?
Are you sure there are no missed messages on the consumer side? (check sequenciality of offsets)

**Comment by vin-d** [comment]
**return value of produce() :** 
good point !!! as I'm not checking this.
But does a produce() call triggers a dr_cb() call _EVERY time_ (even if different return code is different from ERR_NO_ERROR) ? 

**Clients :** 
A colleague reported me this by using a python client,
and I've tried with kafka-console-producer.sh so for me it's not a consumer issue.

**outage / ISR / leader change :** 
nothing specific at the first glance.
maybe a Kafka server/cluster/topic configuration issue but I'm not totally familiar with that so I need a bit of time to check this information.

**Comment by edenhill** [comment]
The delivery report callback is only called for messages accepted by produce(), thus if produce() fails the message was not accepted and no delivery report will be called.

What is your producer config for request.required.acks/acks?

**Comment by edenhill** [comment]
Default client configuration, not broker.
See https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

acks defaults to 1 (only leader guarantees write, not replicas)

**Comment by vin-d** [comment]
ok thank you, I first understood the broker was providing these default values.
I guess it's related to that and unattended cluster/broker events because I have just had access to the server log and see some messages like in one of the windows where messages were missing

```
[2017-01-28 14:48:22,285] INFO [SessionExpirationListener on 0], ZK expired; shut down all controller components and try to re-elect (kafka.controller.KafkaController$SessionExpirationListener)
[2017-01-28 14:48:22,287] DEBUG [Controller 0]: Controller resigning, broker id 0 (kafka.controller.KafkaController)
[2017-01-28 14:48:22,287] DEBUG [Controller 0]: De-registering IsrChangeNotificationListener (kafka.controller.KafkaController)
[2017-01-28 14:48:22,287] INFO [Partition state machine on Controller 0]: Stopped partition state machine (kafka.controller.PartitionStateMachine)
[2017-01-28 14:48:22,287] INFO [Replica state machine on controller 0]: Stopped replica state machine (kafka.controller.ReplicaStateMachine)
[2017-01-28 14:48:22,287] INFO [Controller 0]: Broker 0 resigned as the controller (kafka.controller.KafkaController)
```
and the zookeeper logs also refers to some timeout at the same time.
So I really don't thing it's in anyway related to librdkafka, but to the Kafka context/infrastructure.

Thank you for the support and advices over this.

**Comment by edenhill** [comment]
Good luck!
