### ISSUE TITLE
Configuration location

### ISSUE THREAD

**Issue by ktalebian** [edenhill/librdkafka#1029]
This may be a simple question, but where is the configuration file located?

**Comment by edenhill** [comment]
librdkafka is configured through string-based key=value properties using a C/C++ configuration API (rd_kafka_conf_set, Conf::set), it is up to an application using librdkafka to expose this interface through a file, command-line arguments or hard-coded, whatever fits the application.

For the actual configuration properties see https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

Here's an example how to create a configuration file interface allowing both librdkafka properties as well as application-specific properties
https://github.com/wikimedia/varnishkafka/blob/master/config.c

or:
https://github.com/edenhill/librdkafka/blob/master/tests/test.c#L408

**Comment by ktalebian** [comment]
Thanks, makes sense.
