### ISSUE TITLE
Consumer fetched message payload is of unexpected format

### ISSUE THREAD

**Issue by ktalebian** [edenhill/librdkafka#1030]
I'm using [php-rdkafka]() and I'm not sure if the following behavior is specific to that application or more generic to this library.

Basically, I'm using Java for kafka producer. This record is of the form

```
{
   "id": "XXX",
   "user_id": "YYY",
   "date_created": "2017...",
   "paylaod_type": "userevent",
   "payload": {
       // Custom payload
    }
}
```

The message payload that I receive from the consumer is of the format:

```
D{ID}D{USER_ID}({DATE_CREATED}){PAYLOAD_TYPE}{PAYLOAD}
```

For example:

```
DLDEzVjF25ZW8paoxFP0z2Ik4WffW3dqOX3GJtns3sifHK8piBWCym6WeTMtVDTJK(2017-01-31T00:36:20Zuserevent�{THE_PAYLAOD_FIELD}
```

Is [this](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_feature.h#L38)? I changed it to `0x0` because that is what we use, but if I do that, then I can never consume my stream.

**Comment by edenhill** [comment]
librdkafka does not provide a De/Serialization interface, that is up to the user of librdkafka to layer around the produce() and consume() calls.
E..g, you serialize your object prior to calling produce() and deserialize whatever comes out of consume().

Are you using Confluent's Schema-Registry? I dont know of any schema-registry-supporting Avro serdesers for PHP

**Comment by ktalebian** [comment]
I updated my question. I dug into our own services and noticed that we use `0x0` for the magicbyte. I updated [this](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_feature.h#L38) line to `0x0` and recompiled the library, but now I don't even get any result when I run the consumer.

I'm using [PHP RDKafka](https://github.com/arnaud-lb/php-rdkafka), and I'm running their high level consumer example.

**Comment by edenhill** [comment]
That define you changed is an internal bitfield of librdkafka, it has no bearing on the message format.
Dont change it, it will break stuff and will not fix your problem.

As explained above librdkafka wont do any de/serialization, it will simply forward whatever opaque binary payload between producers and consumers. You implement de/serialization on top librdkafka's interfaces (or php-rdkafka in this case).
