### ISSUE TITLE
Installing new version of librdkafka library

### ISSUE THREAD

**Issue by kanchan1234** [edenhill/librdkafka#1031]
I have librdkafka 0.9.1 -pre 0 version installed in my dev server.

Due to issues regarding kerberos authentication and since it is not a proper release ,it is suggested to install librdkafka 0.9.2 

Please suggest is there risk of losing some function call in new version which can halt the present work.
Is it suggested to create clone server before adapting this change..or i can insatll new version directly  by just taking backup of codes??

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka is API and ABI safe, you can safely upgrade to a new version without breaking existing functionality, bindings or interfaces.

**Comment by edenhill** [comment]
librdkafka 0.9.3 was just released, I suggest you upgrade to that verison.

**Comment by kanchan1234** [comment]
ok..thenks for such a quick response..
