### ISSUE TITLE
Support for setting "consume_cb" breaks set() backwards compatibility

### ISSUE THREAD

**Issue by vdeters** [edenhill/librdkafka#1033]
Description
===========
A C++ client built against librdkafka without this support but running against a newer librdkafka with this support fails when setting "event_cb".

How to reproduce
================
Run a C++ client on linux and call set("event_cb", ..., ...) on a global config object. The call fails because it enters this:
  virtual Conf::ConfResult set (const std::string &name,
                                DeliveryReportCb *dr_cb,
                                std::string &errstr) = 0;

instead of this:
  virtual Conf::ConfResult set (const std::string &name,
                                EventCb *event_cb,
                                std::string &errstr) = 0;

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That sounds very strange, why would the linker select the wrong set() variant?
This is from `nm librdkafka++.dylib` on osx:
```
0000000000001330 t __ZN7RdKafka8ConfImpl3setERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPNS_7EventCbERS7_
00000000000014f0 t 
0000000000001270 t __ZN7RdKafka8ConfImpl3setERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPNS_9ConsumeCbERS7_
```

**Comment by vdeters** [comment]
Is it a linker issue? We built our client against an older librdkafka
(without the consume_cb change). At run time, if we dynamically load the
same librdkafka all is well. But if we dynamically load a newer librdkafka
with the consume_cb change we hit this issue.

**Comment by edenhill** [comment]
Your program should have a linker dependency on the set(..., EventCb*) symbol,
you can check this with nm on your binary.

**Comment by vdeters** [comment]
nm libesp_kafka_cpi-4.2.0.so | grep RdKafka
00000000000187c0 T
_ZN19dfESPkafkaConnector14processMetaMsgEPN7RdKafka7MessageE
000000000001b200 T _ZN19dfESPkafkaConnector8event_cbERN7RdKafka5EventE
                 U _ZN7RdKafka13KafkaConsumer6createEPNS_4ConfERSs
                 U _ZN7RdKafka14TopicPartition6createERKSsi
                 U _ZN7RdKafka4Conf6createENS0_8ConfTypeE
                 U _ZN7RdKafka5Topic6createEPNS_6HandleERKSsPNS_4ConfERSs
000000000001e250 W _ZN7RdKafka7EventCbD0Ev
000000000001db20 W _ZN7RdKafka7EventCbD1Ev
000000000001db20 W _ZN7RdKafka7EventCbD2Ev
                 U _ZN7RdKafka7err2strENS_9ErrorCodeE
                 U _ZN7RdKafka8Producer6createEPNS_4ConfERSs
000000000001ff40 W
_ZNSt6vectorIPN7RdKafka14TopicPartitionESaIS2_EE13_M_insert_auxEN9__gnu_cxx17__normal_iteratorIPS2_S4_EERKS2_
000000000022a9c0 V _ZTIN7RdKafka7EventCbE
0000000000027210 V _ZTSN7RdKafka7EventCbE
000000000022abe0 V _ZTVN7RdKafka7EventCbE
000000000001b1f0 T
_ZThn392_N19dfESPkafkaConnector8event_cbERN7RdKafka5EventE
Andy Tracy: (9:54 AM)
This is easier to read:
00000000000187c0 T dfESPkafkaConnector::processMetaMsg(RdKafka::Message*)
000000000001b200 T dfESPkafkaConnector::event_cb(RdKafka::Event&)
                 U RdKafka::KafkaConsumer::create(RdKafka::Conf*,
std::string&)
                 U RdKafka::TopicPartition::create(std::string const&, int)
                 U RdKafka::Conf::create(RdKafka::Conf::ConfType)
                 U RdKafka::Topic::create(RdKafka::Handle*, std::string
const&, RdKafka::Conf*, std::string&)
000000000001e250 W RdKafka::EventCb::~EventCb()
000000000001db20 W RdKafka::EventCb::~EventCb()
000000000001db20 W RdKafka::EventCb::~EventCb()
                 U RdKafka::err2str(RdKafka::ErrorCode)
                 U RdKafka::Producer::create(RdKafka::Conf*, std::string&)
000000000001ff40 W std::vector<RdKafka::TopicPartition*,
std::allocator<RdKafka::TopicPartition*>
>::_M_insert_aux(__gnu_cxx::__normal_iterator<RdKafka::TopicPartition**,
std::vector<RdKafka::TopicPartition*,
std::allocator<RdKafka::TopicPartition*> > >, RdKafka::TopicPartition*
const&)
000000000022a9c0 V typeinfo for RdKafka::EventCb
0000000000027210 V typeinfo name for RdKafka::EventCb
000000000022abe0 V vtable for RdKafka::EventCb
000000000001b1f0 T non-virtual thunk to
dfESPkafkaConnector::event_cb(RdKafka::Event&)

**Comment by vin-d** [comment]
I think I had that problem too a few weeks ago.
That's because of a pull request I did to have an upgraded setter/getter inteface to the C++ Conf object.

If I understood the problem clearly, this changed the interface/symboles (.h file) of the shared object. So if you execute a program that was compiled using the older .h, it seems like the program will call the wrong RdKafka::Conf methods .

I've fixed that by recompiling (on a computer that have the new librdkafka interface) the software which had the issue.
sudo ldconfig may also be needed.

**Comment by vdeters** [comment]
Ok that makes sense, but if a recompile against an updated .h is required,
that breaks upward compatibility for an existing program right? If so,
shouldn't that be a major version change for librdkafka? Thanks,
Vince

**Comment by edenhill** [comment]
Did you change toolchain between the old librdkafka and new compilation by any chance?

**Comment by vdeters** [comment]
No, the old and new librdkafka versions are built with the same toolchain,
but it may be different than the one used to build the client program that
links against librdkafka. I can find out, if that would be helpful to know.

**Comment by edenhill** [comment]
That would be helpful, thanks.

I think this is an issue with C++ symbol mangling.

**Comment by vdeters** [comment]
We're building librdkafka with (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4).

We built our client (which is itself a shared object) with g++ 4.4.7.

**Comment by vdeters** [comment]
Another data point. We tested our current client which is built with g++ 4.9.4 and –std=c++11 against the "old" and "new" librdkafka and saw the same issue.

**Comment by edenhill** [comment]
Looking at the following link I can't find an obvious reason this would happen, unless you are sub-classing the Conf class?

https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B

**Comment by vin-d** [comment]
on my side I've tried to reproduced the problem as I thought it was.
I did git checkout  d547b81e39c874d1f24d7aef102fada20f80ac65
which is a version before the pull request I was talking about
then
```
./configure
make
sudo make install
sudo ldconfig
```
cleaned my project and recompiled, then installed back my current used version of librdkafka (7f12b7f).
Result I don't see the problem as I thought I would.
So I would tend to say that the cause told in my initial message was wrong.
It could have been a toolchain update in my case, I just don't know with automatic system updates.

**Comment by edenhill** [comment]
huhm, okay, so it works now?
Old application, new librdkafka?

**Comment by vin-d** [comment]
in my case yes.
The program on which I saw this was a small program to tryout librdkafka, so it wasn't under active development when I saw this issue. That's why I would say that updated toolchain (or anything near that) could be a good guess at the problem source... but I'm not an expert on this subject :-x

**Comment by edenhill** [comment]
Good!
One down, one to go. @vdeters

**Comment by vdeters** [comment]
Good to know. In any case we probably need to fix our librdkafka to a tagged version before we do any more testing. What do you recommend? Looks like we're currently using something pulled from master based on 0.9.1.

**Comment by edenhill** [comment]
v0.9.3 is the latest and greatest, v0.9.2 is also good

**Comment by vdeters** [comment]
Looking back at the change that introduced consume_cb:
https://github.com/edenhill/librdkafka/commit/c09efc160949cd3a1c0c8480ff22f6f7943c09e1

...and looking at the link you posted it seems this would explain it, no?

https://community.kde.org/Policies/Binary_Compatibility_Examples#Change_the_order_of_the_declaration_of_virtual_functions

**Comment by edenhill** [comment]
@vdeters You are right, my mistake.

I'd like to fix the ordering but that'll break 0.9.2 users. Don't know what's best.

**Comment by edenhill** [comment]
Suggestion on which way to go?
 * fix ordering, this will allow <=0.9.1 -> 0.9.4 upgrades without recompile
 * dont fix ordering, this will allow >=0.9.2 -> 0.9.4 upgrades

**Comment by vin-d** [comment]
I would suggest fix ordering for minimal impact of users:
As the other case (c09efc1)  was  done in Nov 14 (about 3 month window only) and given the fact that usually people tend to stay with the stable library they have first installed.

There must be more people that have  version <=0.9.1 installed.

**Comment by edenhill** [comment]
Good point. Would you like to file a PR?

**Comment by vin-d** [comment]
Yes, sure.

So, have I correctly understood that it's just [at](https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp_int.h#L221)
```c++
class ConfImpl : public Conf {
 public:
  ConfImpl()
      :consume_cb_(NULL),
      dr_cb_(NULL),
      event_cb_(NULL),
      socket_cb_(NULL),
      open_cb_(NULL),
      partitioner_cb_(NULL),
      partitioner_kp_cb_(NULL),
      rebalance_cb_(NULL),
      offset_commit_cb_(NULL),
      rk_conf_(NULL),
      rkt_conf_(NULL){}
  ~ConfImpl () {
    if (rk_conf_)
      rd_kafka_conf_destroy(rk_conf_);
    else if (rkt_conf_)
      rd_kafka_topic_conf_destroy(rkt_conf_);
  }
```
has to change back to 
```c++
class ConfImpl : public Conf {
 public:
  ConfImpl()
      :dr_cb_(NULL),
      consume_cb_(NULL),
      event_cb_(NULL),
      socket_cb_(NULL),
      open_cb_(NULL),
      partitioner_cb_(NULL),
      partitioner_kp_cb_(NULL),
      rebalance_cb_(NULL),
      offset_commit_cb_(NULL),
      rk_conf_(NULL),
      rkt_conf_(NULL){}
  ~ConfImpl () {
    if (rk_conf_)
      rd_kafka_conf_destroy(rk_conf_);
    else if (rkt_conf_)
      rd_kafka_topic_conf_destroy(rkt_conf_);
  }
```

?

**Comment by edenhill** [comment]
I was under the impression it was the public Conf class's ordering of virtual methods that bugged it.
E.g., need to move the Set(... consumer_cb) to the end of the class

**Comment by vin-d** [comment]
I''ll do before  and after tests to make sure it's fixed.

**Comment by vin-d** [comment]
Yes you were right, that was the problem.

**Comment by edenhill** [comment]
Dup of #1075
