### ISSUE TITLE
Kafka Producer issue

### ISSUE THREAD

**Issue by nikhil-dhiman** [edenhill/librdkafka#1034]
Description
===========

$this->producer = new \RdKafka\Producer($conf);

            $topic = $this->producer->newTopic($topic);
            //504- Gateway timeout in the next line if no children are fetched
            $topic->produce(RD_KAFKA_PARTITION_UA, 0, $data);

We have around 30 partition, but somehow librdkafka is acting biased and sending major chunk messages to few partition  only

Partition	LogSize	Consumer Offset	Lag	Consumer Instance Owner
0	1147	-1	1148	
1	**27442**	-1	27443	
2	**33518**	-1	33519	
3	701	-1	702	
4	**63286**	-1	63287	
5	**19863**	-1	19864	
6	919	-1	920	
7	1107	-1	1108	
8	1436	-1	1437	
9	1796	-1	1797	
10	5858	-1	5859	
11	7363	-1	7364	
12	1174	-1	1175	
13	1225	-1	1226	
14	2407	-1	2408	
15	624	-1	625	
16	7197	-1	7198	
17	**18503**	-1	18504	
18	5423	-1	5424	
19	930	-1	931	
20	3816	-1	3817	
21	4573	-1	4574	
22	2996	-1	2997	
23	758	-1	759	
24	5367	-1	5368	
25	1054	-1	1055	
26	5605	-1	5606	
27	2445	-1	2446	
28	661	-1	662	
29	5921	-1	5922

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x ] librdkafka version (release number or git tag):Latest
 - [x] Apache Kafka version: 0.9.01
 - [x] librdkafka client configuration: Will update soon
 - [ ] Operating system: 
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by nikhil-dhiman** [comment]
Kafka server properties


auto.create.topics.enable=true
auto.leader.rebalance.enable=true
background.threads=10
broker.id=1
broker.id.generation.enable=true
compression.type=producer
connections.max.idle.ms=600000
controlled.shutdown.enable=true
controlled.shutdown.max.retries=3
controlled.shutdown.retry.backoff.ms=5000
controller.socket.timeout.ms=30000
default.replication.factor=1
delete.topic.enable=false
fetch.purgatory.purge.interval.requests=1000
group.max.session.timeout.ms=30000
group.min.session.timeout.ms=6000
host.name=127.0.0.1
inter.broker.protocol.version=0.8.2.2
leader.imbalance.check.interval.seconds=300
leader.imbalance.per.broker.percentage=10
listeners=PLAINTEXT://127.0.0.1:9092
log.cleaner.backoff.ms=15000
log.cleaner.dedupe.buffer.size=134217728
log.cleaner.delete.retention.ms=86400000
log.cleaner.enable=true
log.cleaner.io.buffer.load.factor=0.9
log.cleaner.io.buffer.size=524288
log.cleaner.io.max.bytes.per.second=1.7976931348623157E308
log.cleaner.min.cleanable.ratio=0.5
log.cleaner.threads=1
log.cleanup.policy=delete
log.dir=/tmp/kafka-logs
log.flush.interval.messages=9223372036854775807
log.flush.offset.checkpoint.interval.ms=60000
log.flush.scheduler.interval.ms=9223372036854775807
log.index.interval.bytes=4096
log.index.size.max.bytes=10485760
log.preallocate=false
log.retention.bytes=-1
log.retention.check.interval.ms=300000
log.retention.hours=168
log.roll.hours=168
log.roll.jitter.hours=0
log.segment.bytes=1073741824
log.segment.delete.delay.ms=60000
max.connections.per.ip=2147483647
message.max.bytes=1000012
metrics.num.samples=2
metrics.sample.window.ms=30000
min.insync.replicas=1
num.io.threads=8
num.network.threads=3
num.partition=3
num.partitions=1
num.recovery.threads.per.data.dir=1
num.replica.fetchers=1
offset.metadata.max.bytes=4096
offsets.commit.required.acks=-1
offsets.commit.timeout.ms=5000
offsets.load.buffer.size=5242880
offsets.retention.check.interval.ms=600000
offsets.retention.minutes=1440
offsets.topic.compression.codec=0
offsets.topic.num.partitions=50
offsets.topic.replication.factor=3
offsets.topic.segment.bytes=104857600
port=9092
principal.builder.class=org.apache.kafka.common.security.auth.DefaultPrincipalBuilder
producer.purgatory.purge.interval.requests=1000
queued.max.requests=500
quota.consumer.default=9223372036854775807
quota.producer.default=9223372036854775807
quota.window.num=11
quota.window.size.seconds=1
replica.fetch.backoff.ms=1000
replica.fetch.max.bytes=1048576
replica.fetch.min.bytes=1
replica.fetch.wait.max.ms=500
replica.high.watermark.checkpoint.interval.ms=5000
replica.lag.time.max.ms=10000
replica.socket.receive.buffer.bytes=65536
replica.socket.timeout.ms=30000
request.timeout.ms=30000
reserved.broker.max.id=1000
sasl.kerberos.kinit.cmd=/usr/bin/kinit
sasl.kerberos.min.time.before.relogin=60000
sasl.kerberos.principal.to.local.rules=DEFAULT
sasl.kerberos.ticket.renew.jitter=0.05
sasl.kerberos.ticket.renew.window.factor=0.8
security.inter.broker.protocol=PLAINTEXT
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
socket.send.buffer.bytes=102400
ssl.client.auth=none
ssl.enabled.protocols=TLSv1.2,TLSv1.1,TLSv1
ssl.keymanager.algorithm=SunX509
ssl.keystore.type=JKS
ssl.protocol=TLS
ssl.trustmanager.algorithm=PKIX
ssl.truststore.type=JKS
unclean.leader.election.enable=true
zookeeper.connect=Z1,Z2,Z3
zookeeper.session.timeout.ms=6000
zookeeper.set.acl=false
zookeeper.sync.time.ms=2000

**Comment by edenhill** [comment]
which librdkafka version or exact git sha1 are you using?

**Comment by nikhil-dhiman** [comment]
I don't remember the version, since i use this repo to compile[Somewhere in mid December 2016, i cloned your repo.]

**Comment by edenhill** [comment]
It would be interesting to extract some librdkafka stats for the partition queues but it seems like the stats_cb is not implemented in php-rdkafka.

Can you file a feature request on that project for stats support, or implement it yourself (easy enough, stats_cb will be called form rd_kafka_poll() and provides you with a JSON document as a string)?
