### ISSUE TITLE
Why consumer poll causes so large bandwidth usage even it is in idle? Bug or normal?

### ISSUE THREAD

**Issue by jupiterh** [edenhill/librdkafka#1037]
Description
===========
Hi edenhill,

My small devices to send / receive messages via 3G / LTE connected in 7 / 24 connection, the following bandwidth usages (all overheads) were measured in consumer poll without transmit / receive any real user messages in the device (in idle state), 

Tx: 21 kb / s
Rx: 28 kb / s

It uses ssl, both debug and EventCallback were disabled. It consumes bandwidth about total 6 KB/s, or 500 MB / day or 15 GB / month, that is way too high especially that are pure overheads, I haven't transmitted and received any real messages. Is it a bug or normal behaviour?

I think that overheads just comes from the library, I've tried many different things, but could not reduce the overhead bandwidth consumption. Are there any way I can reduce the bandwidth consumption through compilation or configuration?

Please help, it is simply unsustainable on such high overheads.

Thank you.

Kind regards.

How to reproduce
================

You can run rdkafka_example.cpp for consumer "-C" and watch bandwidth usage from iftop

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.1-1
 - [ ] Apache Kafka version: 2.11-0.10.1.0 
 - [ ] librdkafka client configuration:
 - [ ] Operating system: Debian
 - [ ] Using the legacy Consumer rdkafka_example.cpp
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There are two things happening:
 * librdkafka attempts to pre-fetch messages so that at least `queued.min.messages` are available in local queues for immediate consumtion by the application. This setting is limited by `queued.max.messages.kbytes` which by default is 1GB. This is clearly undesirable options in your scenario so I suggest you lower those two to reasonable values.
 * Kafka uses a long-polling approach to fetch new messages, so even when there are no new messages on the given partition(s) there will be Fetch requests at least the frequency of `fetch.wait.max.ms` - this value defaults to 100ms. You should increase this value to suit your needs. The only drawback of a higher fetch wait is that other requests, such as OffsetCommit and Metadata requests are stalled behind a waiting Fetch request. So I suggest you keep Fetch wait well below 10 seconds.

Let me know if this helps

**Comment by jupiterh** [comment]
Thanks Edenhill, will do it tomorrow morning and will let you know the result.

**Comment by jupiterh** [comment]
Hi Edenhill, 

That works well for consumer after changing "queued.min.messages" to 1, 100000, 100000, "max.messages.kbytes" to 1, 1000000, 1000000 and fetch.wait.max.ms to 0, 300*1000, 9000. 

But the producer still received large overheads every time I transmitted the message, the received overhead size is much larger than the message size,  are there any configuration variables I can change to reduce the producer receiving overhead?

Thank you very much and appreciate your kind help.

**Comment by edenhill** [comment]
An idle producer should be mostly idle (except for the intervalled metadata refreshes).
You could try debug=protocol to see what is going on.

**Comment by jupiterh** [comment]
Yes, idle producer did not receive any overhead, only when a produce sent data, it immediately received large size metadata. I'll check the debug=protocol tomorrow morning. Thank you.

**Comment by jupiterh** [comment]
Hi Edenhill,

Here are the debug for protocol running on producer, sending every message received 93% overhead, are there any configuration variables can be adjusted to reduce the overhead? Thank you.

LOG-7-APIVERSION: ssl://research33:9093/bootstrap: Using (configuration fallback) 0.9.0 protocol features
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature MsgVer1: Produce (2..2) NOT supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature MsgVer1: Fetch (2..2) NOT supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap: Using (configuration fallback) 0.9.0 protocol features
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature MsgVer1: Produce (2..2) NOT supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature MsgVer1: Fetch (2..2) NOT supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap: Disabling feature MsgVer1
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature ApiVersion: ApiVersion (0..0) NOT supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap: Disabling feature ApiVersion
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature BrokerGroupCoordinator: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap: Enabling feature BrokerGroupCoordinator
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature BrokerBalancedConsumer: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature BrokerBalancedConsumer: OffsetCommit (1..2) supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature BrokerBalancedConsumer: OffsetFetch (1..1) supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature BrokerBalancedConsumer: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature BrokerBalancedConsumer: SyncGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature BrokerBalancedConsumer: Heartbeat (0..0) supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature BrokerBalancedConsumer: LeaveGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap: Enabling feature BrokerBalancedConsumer
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature ThrottleTime: Produce (1..2) supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature ThrottleTime: Fetch (1..2) supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap: Enabling feature ThrottleTime
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature Sasl: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap: Enabling feature Sasl
LOG-7-APIVERSION: ssl://research31:9093/bootstrap:  Feature SaslHandshake: SaslHandshake (0..0) NOT supported by broker
LOG-7-APIVERSION: ssl://research31:9093/bootstrap: Disabling feature SaslHandshake
LOG-7-APIVERSION: ssl://research33:9093/bootstrap: Disabling feature MsgVer1
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature ApiVersion: ApiVersion (0..0) NOT supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap: Disabling feature ApiVersion
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature BrokerGroupCoordinator: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap: Enabling feature BrokerGroupCoordinator
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature BrokerBalancedConsumer: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature BrokerBalancedConsumer: OffsetCommit (1..2) supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature BrokerBalancedConsumer: OffsetFetch (1..1) supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature BrokerBalancedConsumer: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature BrokerBalancedConsumer: SyncGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature BrokerBalancedConsumer: Heartbeat (0..0) supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature BrokerBalancedConsumer: LeaveGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap: Enabling feature BrokerBalancedConsumer
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature ThrottleTime: Produce (1..2) supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature ThrottleTime: Fetch (1..2) supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap: Enabling feature ThrottleTime
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature Sasl: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap: Enabling feature Sasl
LOG-7-APIVERSION: ssl://research33:9093/bootstrap:  Feature SaslHandshake: SaslHandshake (0..0) NOT supported by broker
LOG-7-APIVERSION: ssl://research33:9093/bootstrap: Disabling feature SaslHandshake
LOG-7-APIVERSION: ssl://research32:9093/bootstrap: Using (configuration fallback) 0.9.0 protocol features
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature MsgVer1: Produce (2..2) NOT supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature MsgVer1: Fetch (2..2) NOT supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap: Disabling feature MsgVer1
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature ApiVersion: ApiVersion (0..0) NOT supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap: Disabling feature ApiVersion
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature BrokerGroupCoordinator: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap: Enabling feature BrokerGroupCoordinator
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature BrokerBalancedConsumer: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature BrokerBalancedConsumer: OffsetCommit (1..2) supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature BrokerBalancedConsumer: OffsetFetch (1..1) supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature BrokerBalancedConsumer: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature BrokerBalancedConsumer: SyncGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature BrokerBalancedConsumer: Heartbeat (0..0) supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature BrokerBalancedConsumer: LeaveGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap: Enabling feature BrokerBalancedConsumer
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature ThrottleTime: Produce (1..2) supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature ThrottleTime: Fetch (1..2) supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap: Enabling feature ThrottleTime
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature Sasl: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap: Enabling feature Sasl
LOG-7-APIVERSION: ssl://research32:9093/bootstrap:  Feature SaslHandshake: SaslHandshake (0..0) NOT supported by broker
LOG-7-APIVERSION: ssl://research32:9093/bootstrap: Disabling feature SaslHandshake
LOG-7-SEND: ssl://research31:9093/bootstrap: Sent MetadataRequest (v0, 37 bytes @ 0, CorrId 1)
LOG-7-SEND: ssl://research33:9093/bootstrap: Sent MetadataRequest (v0, 37 bytes @ 0, CorrId 1)
LOG-7-SEND: ssl://research32:9093/bootstrap: Sent MetadataRequest (v0, 37 bytes @ 0, CorrId 1)
LOG-7-RECV: ssl://research31:9093/bootstrap: Received MetadataResponse (v0, 5468 bytes, CorrId 1, rtt 54.04ms)
LOG-7-RECV: ssl://research33:9093/bootstrap: Received MetadataResponse (v0, 5468 bytes, CorrId 1, rtt 52.82ms)
LOG-7-RECV: ssl://research32:9093/bootstrap: Received MetadataResponse (v0, 5468 bytes, CorrId 1, rtt 51.68ms)
LOG-7-SEND: ssl://research31:9093/1: Sent MetadataRequest (v0, 37 bytes @ 0, CorrId 2)
LOG-7-SEND: ssl://research33:9093/3: Sent MetadataRequest (v0, 37 bytes @ 0, CorrId 2)
LOG-7-SEND: ssl://research32:9093/2: Sent MetadataRequest (v0, 37 bytes @ 0, CorrId 2)
LOG-7-RECV: ssl://research31:9093/1: Received MetadataResponse (v0, 5468 bytes, CorrId 2, rtt 40.89ms)
LOG-7-RECV: ssl://research32:9093/2: Received MetadataResponse (v0, 5468 bytes, CorrId 2, rtt 42.28ms)
LOG-7-RECV: ssl://research33:9093/3: Received MetadataResponse (v0, 5468 bytes, CorrId 2, rtt 43.83ms)

**Comment by edenhill** [comment]
There are no timestamps so its hard to know what the timespan here is.
The currently released versions of librdkafka is a bit chatty when it comes to MetadataRequests, it will send them often and to many brokers, but that's fixed on master.

But looking at the above log there are 6 requests of 37 bytes each, each resulting in a response of 5468 bytes. So all in all 222 out and 32kb in.

**Comment by jupiterh** [comment]
So the next release from the master will fix it, when are you going to release the fixed on master and which version will it be? I'll test it as soon as you release it.

Thanks Edenhill.

**Comment by edenhill** [comment]
Looking to release 0.9.4 within a months time.
You are free to try out master beforehand, it would be interesting to know if it fixes your issue

**Comment by jupiterh** [comment]
Will try it, thank you very much.
