### ISSUE TITLE
problem running tests

### ISSUE THREAD

**Issue by jmarca** [edenhill/librdkafka#1040]
Description
===========

When running tests, I get an error.  I manually built/installed kafka_2.11-0.10.1.0 on slackware 14.2 (current), and am new to Kafka so there might be issues there.

How to reproduce
================

Running this package's tests, I did 

```
kafka[master]$ cd tests
tests[master]$ ./broker_version_tests.py   --debug
#### Version 0.8.1.1, suite standard: STARTING
ZookeeperApp-1: Creating ZookeeperApp instance
KafkaBrokerApp-2: Creating KafkaBrokerApp instance
KafkaBrokerApp-2: Listeners: PLAINTEXT://localhost:33764
KafkaBrokerApp-2: Advertised Listeners: PLAINTEXT://localhost:33764
KafkaBrokerApp-3: Creating KafkaBrokerApp instance
KafkaBrokerApp-3: Listeners: PLAINTEXT://localhost:46444
KafkaBrokerApp-3: Advertised Listeners: PLAINTEXT://localhost:46444
KafkaBrokerApp-4: Creating KafkaBrokerApp instance
KafkaBrokerApp-4: Listeners: PLAINTEXT://localhost:48336
KafkaBrokerApp-4: Advertised Listeners: PLAINTEXT://localhost:48336
LibrdkafkaTestApp-5: Creating LibrdkafkaTestApp instance
Traceback (most recent call last):
  File "./broker_version_tests.py", line 185, in <module>
    interact=args.interact, debug=args.debug)
  File "./broker_version_tests.py", line 40, in test_it
    rdkafka = LibrdkafkaTestApp(cluster, version, _rdkconf, tests=tests)
  File "/home/james/repos/librdkafka/tests/LibrdkafkaTestApp.py", line 25, in __init__
    self.appid = UuidAllocator(self.cluster).next(self, trunc=8)
TypeError: next() got multiple values for argument 'trunc'
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): dde5ecf0a02db2f938312812cae52c234d560c1b
 - [x] Apache Kafka version: 2.11-0.10.1.0
 - [x] librdkafka client configuration: NA
 - [x] Operating system: Linux; slackware 14.2 -current
 - [x] Using the legacy Consumer no
 - [x] Using the high-level KafkaConsumer no
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka see above
 - [x] Provide broker log excerpts NA
 - [x] Critical issue test does not run

I assume others can run tests, so I must be doing something wrong.

Python version is Python 3.4.3
pip list shows trivup (0.1)

Update: forgot to set the checkboxes.  Also, note that the above command does not have "trunk" , but the same thing happens with trunk, except a different version number, as in:

```
 ./broker_version_tests.py trunk --debug
#### Version trunk, suite standard: STARTING
ZookeeperApp-1: Creating ZookeeperApp instance
KafkaBrokerApp-2: Creating KafkaBrokerApp instance
KafkaBrokerApp-2: Listeners: PLAINTEXT://localhost:54998
KafkaBrokerApp-3: Creating KafkaBrokerApp instance
KafkaBrokerApp-3: Listeners: PLAINTEXT://localhost:49200
KafkaBrokerApp-4: Creating KafkaBrokerApp instance
KafkaBrokerApp-4: Listeners: PLAINTEXT://localhost:37165
LibrdkafkaTestApp-5: Creating LibrdkafkaTestApp instance
Traceback (most recent call last):
  File "./broker_version_tests.py", line 185, in <module>
    interact=args.interact, debug=args.debug)
  File "./broker_version_tests.py", line 40, in test_it
    rdkafka = LibrdkafkaTestApp(cluster, version, _rdkconf, tests=tests)
  File "/home/james/repos/librdkafka/tests/LibrdkafkaTestApp.py", line 25, in __init__
    self.appid = UuidAllocator(self.cluster).next(self, trunc=8)
TypeError: next() got multiple values for argument 'trunc'
```

Also, no difference running as root or as regular user.

**Comment by edenhill** [comment]
You'll need a newer version of trivup, but I haven't pushed it to PyPi yet.
You could clone https://github.com/edenhill/trivup and `python setup.py install` it your virtualenv.

**Comment by edenhill** [comment]
If you specify a Kafka release version (rather than the default trunk) it will automatically download prebuilt binaries to run, so you dont need Gradle, JDK, etc.

**Comment by jmarca** [comment]
I tried with the github version of trivup too, but got essentially the same error.  I also have gradle SDK, etc ready to go, so I don't think that is the issue.  

After removing the "standard" version of trivup, I installed the github version of trivup as follows:

```
 sudo pip install .
Processing /home/james/repos/trivup
Installing collected packages: trivup
  Running setup.py install for trivup ... done
Successfully installed trivup-0.1
```

Made sure python is python 3.4, not 2.7 (the default on slackware)

Getting the same exact error:

```
 ./broker_version_tests.py  --debug --kafka-src /home/james/Downloads/kafka/kafka_2.11-0.10.1.0 --brokers 4 trunk
#### Version trunk, suite standard: STARTING
ZookeeperApp-1: Creating ZookeeperApp instance
KafkaBrokerApp-2: Creating KafkaBrokerApp instance
KafkaBrokerApp-2: Listeners: PLAINTEXT://localhost:35150
KafkaBrokerApp-2: Advertised Listeners: PLAINTEXT://localhost:35150
KafkaBrokerApp-3: Creating KafkaBrokerApp instance
KafkaBrokerApp-3: Listeners: PLAINTEXT://localhost:42529
KafkaBrokerApp-3: Advertised Listeners: PLAINTEXT://localhost:42529
KafkaBrokerApp-4: Creating KafkaBrokerApp instance
KafkaBrokerApp-4: Listeners: PLAINTEXT://localhost:47533
KafkaBrokerApp-4: Advertised Listeners: PLAINTEXT://localhost:47533
KafkaBrokerApp-5: Creating KafkaBrokerApp instance
KafkaBrokerApp-5: Listeners: PLAINTEXT://localhost:50575
KafkaBrokerApp-5: Advertised Listeners: PLAINTEXT://localhost:50575
LibrdkafkaTestApp-6: Creating LibrdkafkaTestApp instance
Traceback (most recent call last):
  File "./broker_version_tests.py", line 185, in <module>
    interact=args.interact, debug=args.debug)
  File "./broker_version_tests.py", line 40, in test_it
    rdkafka = LibrdkafkaTestApp(cluster, version, _rdkconf, tests=tests)
  File "/home/james/repos/librdkafka/tests/LibrdkafkaTestApp.py", line 25, in __init__
    self.appid = UuidAllocator(self.cluster).next(self, trunc=8)
TypeError: next() got multiple values for argument 'trunc'
```

**Comment by edenhill** [comment]
I saw the same problem until I updated to latest master, I didnt use pip to install it though but `python setup.py install` into a virtualenv, dont know if your environment is picking up the wrong version for some reason?

**Comment by jmarca** [comment]
Okay. My python setup on my laptop is a shambles right now, mix of 2.7 and 3.x.  I'll reopen if/when I get a chance to test this on my other Linux box that has a better python tool chain.

**Comment by edenhill** [comment]
Okay, good luck :)
