### ISSUE TITLE
How to set the appropriate value of timeout_ms parameter when call to rd_kafka_consumer_poll function?

### ISSUE THREAD

**Issue by DavidLiuXh** [edenhill/librdkafka#1042]
Description
===========
How to set the appropriate value of timeout_ms parameter when call to rd_kafka_consumer_poll function?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I'm not sure I understand, can you elaborate?

**Comment by DavidLiuXh** [comment]
Sorry~
How to set the appropriate value of timeout_ms parameter whdn call to rd_kafka_consumer_poll function?

**Comment by edenhill** [comment]
The consumer_poll() timeout_ms argument states the maximum time this call will block waiting for a new message.
It only affects your program, not librdkafka, so you should use a value that is reasonable for your consume loop.
E.g., if you need to do other stuff every 2s, set it to 2000. If this loops only consumes you can set it to -1 (for infinite).

**Comment by DavidLiuXh** [comment]
Thanks for @edenhill
