### ISSUE TITLE
Feature: Add default offset commit callback 

### ISSUE THREAD

**Issue by rnpridgeon** [edenhill/librdkafka#1043]
Description
===========
It would be helpful if librdkafka provided a default callback handler much like that of the java client which could at the very least log offset commit failures. This will aid in troubleshooting unexpected behavior that wen't unnoticed in the absence of registering an offset callback. 

As an example the java api provides the following:

https://github.com/confluentinc/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L654-L660 

While I understand it may not be desirable to halt consumption because of this it would be nice to at least have some logging indicating and issue when committing offsets. 

How to reproduce
================
Set offsets.topic.replication.factor = # brokers + 1; even works with + 2 and +3 ! 
Set auto.offset.reset = earliest 

Consume your heart away without registering a CB, restart the broker

The consumer will fall back to earliest, as you would expect. 

The java client on the other hand will throw an exception upon failing to commit its offsets. Handling commit failures as the default behavior seems like the right move to me. If a client choses to ignore these failures they should have to do so manually to avoid confusion

**Comment by edenhill** [comment]
This is what it'll look like:
`%4|1489005286.401|COMMITFAIL|0049_consume_conn_close#consumer-2| [thrd:main]: Offset commit (unassign) failed for 4/4 partition(s): Broker: Unknown member: rdkafkatest_rnd78b280ca7b7be770_0049_consume_conn_close[0]@4997(Broker: Unknown member), rdkafkatest_rnd78b280ca7b7be770_0049_consume_conn_close[1]@4996(Broker: Unknown member), rdkafkatest_rnd78b280ca7b7be770_0049_consume_conn_close[2]@5003(Broker: Unknown member), rdkafkatest_rnd78b280ca7b7be770_0049_consume_conn_close[3]@5004(Broker: Unknown member)`

**Comment by rnpridgeon** [comment]
Works for me! Thanks
