### ISSUE TITLE
Partitions keep getting revoked

### ISSUE THREAD

**Issue by manvendratomar** [edenhill/librdkafka#1044]
Description
===========
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [16]: stored offset -1001, committed offset 6905
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [16]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [17]: stored offset -1001, committed offset 6254
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [17]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [18]: stored offset -1001, committed offset 7174
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [18]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [19]: stored offset -1001, committed offset 6913
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [19]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [20]: stored offset -1001, committed offset 6557
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [20]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [21]: stored offset -1001, committed offset 7195
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [21]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [22]: stored offset -1001, committed offset 6906
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-1 [22]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [16]: stored offset -1001, committed offset 6492
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [16]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [17]: stored offset -1001, committed offset 7180
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [17]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [18]: stored offset -1001, committed offset 6913
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [18]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [19]: stored offset -1001, committed offset 6246
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [19]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [20]: stored offset -1001, committed offset 7191
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [20]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [21]: stored offset -1001, committed offset 6938
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [21]: setting offset INVALID for commit
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [22]: stored offset -1001, committed offset 6541
%7|1486641294.688|OFFSET|rdkafka#consumer-1| Topic cls-image-tier3-input-2 [22]: setting offset INVALID for commit
%7|1486641294.688|COMMIT|rdkafka#consumer-1| OffsetCommit internal error: Local: No offset stored
%7|1486641294.688|COMMIT|rdkafka#consumer-1| OffsetCommit for 14 partition(s): cgrp auto commit timer: returned: Local: No offset stored
%7|1486641294.688|UNASSIGN|rdkafka#consumer-1| Unassign not done yet (0 wait_unassign, 14 assigned, 0 wait commit): OffsetCommit done (__NO_OFFSET)

**Partitions keep getting revoked**

Acutal offsets for queues:
brands          cls-image-tier3-input-1        0   7179            8286            1107            none
brands          cls-image-tier3-input-1        1   6985            8286            1301            none
brands          cls-image-tier3-input-1        2   6735            7105            370             none
brands          cls-image-tier3-input-1        3   7167            8283            1116            none
brands          cls-image-tier3-input-1        4   6948            8282            1334            none
brands          cls-image-tier3-input-1        5   6662            7112            450             none
brands          cls-image-tier3-input-1        6   7139            8280            1141            none
brands          cls-image-tier3-input-1        7   6953            8279            1326            none
brands          cls-image-tier3-input-1        8   6528            7102            574             none
brands          cls-image-tier3-input-1        9   7138            8277            1139            none
brands          cls-image-tier3-input-1        10  6961            8275            1314            none
brands          cls-image-tier3-input-1        11  6258            7107            849             none
brands          cls-image-tier3-input-1        12  7115            8276            1161            none
brands          cls-image-tier3-input-1        13  6946            8273            1327            none
brands          cls-image-tier3-input-1        14  6712            7096            384             none
brands          cls-image-tier3-input-1        15  7139            8275            1136            none
brands          cls-image-tier3-input-1        16  6905            8274            1369            none
brands          cls-image-tier3-input-1        17  6254            7105            851             none
brands          cls-image-tier3-input-1        18  7174            8272            1098            none
brands          cls-image-tier3-input-1        19  6913            8274            1361            none
brands          cls-image-tier3-input-1        20  6557            7095            538             none
brands          cls-image-tier3-input-1        21  7195            8273            1078            none
brands          cls-image-tier3-input-1        22  6906            8273            1367            none
brands          cls-image-tier3-input-1        23  6247            7105            858             none
brands          cls-image-tier3-input-1        24  7219            8272            1053            none
brands          cls-image-tier3-input-1        25  6928            8269            1341            none
brands          cls-image-tier3-input-1        26  6527            7094            567             none
brands          cls-image-tier3-input-1        27  7194            8269            1075            none
brands          cls-image-tier3-input-1        28  6921            8268            1347            none
brands          cls-image-tier3-input-1        29  6250            7100            850             none

How to reproduce
================
Intiailized consumer topics with following config
'default.topic.config': {'auto.offset.reset': 'smallest'}
Not sure how can you reproduce this i hope debug logs may help

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.2
 - [x] Apache Kafka version: 0.10.0.1
 - [x] librdkafka client configuration: using confluent kafka python api with {'session.timeout.ms': 60000, 'default.topic.config': {'auto.offset.reset': 'latest'},'api.version.request': 'true'}
 - [x] Operating system: centos
 - [x] Using the legacy Consumer: No
 - [x] Using the high-level KafkaConsumer: Yes
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue: Yes

**Comment by edenhill** [comment]
The debug logs mostly show some internal offset store/commit logic.

The only indication of rebalancing is the last line:
> %7|1486641294.688|UNASSIGN|rdkafka#consumer-1| Unassign not done yet (0 wait_unassign, 14 assigned, 0 wait commit): OffsetCommit done (__NO_OFFSET)

where it waits for the current assignment (14 partitions) to be unassigned from broker threads.

To find out why that isn't happening you'll need to enable debug=cgrp,topic,broker
