### ISSUE TITLE
default value for message.max.bytes @0.8.6 and Broker: Message size too large

### ISSUE THREAD

**Issue by rathdeep** [edenhill/librdkafka#1045]
Description
===========
Noticed default value of  "message.max.bytes" is  4000000 in librdkafka version 0.8.6 whereas  fetch.message.max.bytes   default  is  1048576.
It should be 1000000 which is set correctly now in HEAD. 

Actually I was debugging  [Broker: Message size too large] error. As I have reduced message.max.bytes, I am likely to hit it more.
Facing this issue not every time,  very rarely, difficult to reproduce.
Size of messages is same in every run. Enabling debug gives size of message around 40 bytes
.....produce messageset with 172 messages (6556 bytes)]. 

I even tried delay of 5 secs producing 30K messages at a time, so size should never go beyond ~1.2MB (message.max.bytes is 4 MB).

Found https://issues.apache.org/jira/browse/KAFKA-1718. But [Broker: Message size too large] is error on librdkafka side, it's not even reaching Kafka.

Any pointers to dig this further ?

Thanks.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.8.6
 - [ ] Apache Kafka version:  0.8.2
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you please librdkafka master or 0.9.3?
It will auto adjust fetch size to allow larger batches and there are also fixes on the producer side

**Comment by rathdeep** [comment]
Does this need Kafka broker upgrade too or any change in client application(or just upgrade the library).

**Comment by edenhill** [comment]
Upgrade is sufficient, you dont need to recompile your application
