### ISSUE TITLE
Update Alpine packages to v0.9.4

### ISSUE THREAD

**Issue by mcandre** [edenhill/librdkafka#1047]
Please help the Alpine maintainers update their librdkafka, so that Alpine users can benefit from newer Kafka stuff.

**Comment by albundy83** [comment]
Hello,
not sure to understand what do you need ?

**Comment by edenhill** [comment]
Packaging librdkafka for various distributions is not part of the librdkafka project, it is either performed by 3rd party contributors or distribution packaging teams.

If there's neither of those then pull-requests that adds packaging spec files to packaging/XYZ, etc, are welcome, to help out other users until official packages are available from the *distribution*
