### ISSUE TITLE
Publish artifacts with GitHub Releases

### ISSUE THREAD

**Issue by mcandre** [edenhill/librdkafka#1049]
Could we start offering source and/or binary tarballs with GitHub releases, so that developers have a clear, fixed URL for downloading librdkafka, and so users can easily browse through available artifacts?

Example:

https://github.com/mcandre/go-ios7crypt/releases

**Comment by edenhill** [comment]
Source tarballs are available by default on github:
https://github.com/edenhill/librdkafka/archive/v0.9.3.tar.gz

For binary packages; this is messy, while building per platform and arch is possible (although a bit of work), it does not solve the problem of dependencies (zlib, lz4, openssl, sasl) and dependency versions, so I'm afraid would just cause more problems for users and maintainers.

librdkafka packages are already available (and usually pushed in reasonable time following a release) for the most popular platforms:
 * Debian and Ubuntu  (official packages and Confluent's)
 * RPM-based systems  (Confluent's and 3rd parties (remi))
 * Homebrew for OSX
 * NuGet for Windows (and others) [SOON]
