### ISSUE TITLE
Connection refused error in a multi-node environment

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#1051]
Description
===========
I am running the mdtest (an MPI metadata creation) benchmark on a multi-node setup - each node has a producer writing to a broker - one broker is shared across all nodes. This is just the beginning of benchmark tests - we are beginning with one broker. For every mdtest operation - file create/delete operation the producer sends one message to Kafka.

The producer caches its connection in rd_kafka_t once at the beginning of the test. During the test, several times, I get a:

RDKAFKA-3-FAIL: client01.X.Y.Z.com:9092/0: Connect to ipv4#<broker_address>:9092 failed: Connection refused
RDKAFKA-3-ERROR: client01.X.Y.Z.com:9092/0: Connect to ipv4#<broker_address>:9092 failed: Connection refused

Under what conditions would a connection be refused by Kafka?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Connection refused means one of two things:
 * the kafka broker is not listening on that specific address, port or address family (ipv4/ipv6)
 * a firewall/iptables/etc.. rule is prohibiting access
