### ISSUE TITLE
Can i use this lib to connect the kafka brokers through zookeeper?

### ISSUE THREAD

**Issue by KomaBeyond** [edenhill/librdkafka#1052]
As what i said in the title. Please tell me, thanks ~

**Comment by edenhill** [comment]
Sorry no, clients should no longer (since Kafka 0.9) talk directly to zookeeper.

**Comment by bingo** [comment]
But how could HA applies to Kafka broker cluster without zookeeper awareness? Or you're saying we just missed zookeeper HA capabilities after 0.9?

**Comment by edenhill** [comment]
ZK is still used by the brokers, but it is abstracted from use from the clients.
The clients connects to one or more brokers in the cluster to fetch the full broker list.

**Comment by bingo** [comment]
If we hardcoded bootstrap.servers list in code, what happens if all brokers in this list doesn't respond at the moment we connect? It's an extreme condition, just curious about it.

**Comment by edenhill** [comment]
The library will emit an _ALL_BROKERS_DOWN error event on the error callback when it detects that none of the provided brokers are reachable.
But it will continue to try to connect to all of its known brokers in the background, for ever.
