### ISSUE TITLE
What is the "ciritcal errors"? 

### ISSUE THREAD

**Issue by KomaBeyond** [edenhill/librdkafka#1055]
I use the php-rdkafka php extension in my application and it allows to set an Error Callback method to catch the "ciritcal errors" from librdkafka. So what is the "ciritcal errors"? Please help me, thanks~

**Comment by edenhill** [comment]
There currently isnt a definitive list of emitted errors, but generally errors are handled gracefully by the library and it tries to recover automatically.
I suggest you register an error callback and start experimenting to get a feel for what to expect.

**Comment by KomaBeyond** [comment]
Ok, i will be try. Thank u.

**Comment by KomaBeyond** [comment]
I do the test, and the error callback could catch most of the errors and report an error number, but not include this:
```html
%3|1487052297.838|FAIL|rdkafka#producer-1| [thrd:bumblebee:9092/0]: bumblebee:9092/0: Connect to ipv4#127.0.1.1:9092 failed: Connection refused
```

**Comment by edenhill** [comment]
librdkafka will both log those broker failures as well as trigger an error callback.
Maybe it shouldn't do that.

**Comment by edenhill** [comment]
The next version of the API could have a richer error type that indicates if an error is critical or not.

**Comment by remizyaka** [comment]
Now for Connection refused errors we don't have log messages if callback is present, but callback also is not called. Any way I can catch connection refused errors?
