### ISSUE TITLE
memory used increase on producer process while BrokerInstances not reachable/listening

### ISSUE THREAD

**Issue by tsplibrdkakfa** [edenhill/librdkafka#1057]
Description
===========
Hi, We are testing producer functionality using below command. In our setup we have multiple Kafka instances running on multiple nodes. If these kafka instances are not reachable or listening state, We see producer process memory keeps on increasing. This is not desirable outcome when producer does not have control on Kafka Instance state. If producer kept in same state for long, It goes out of allowed memory in small time.   

valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --show-leak-kinds=all   /dump/gau/092/rdkafka_performance  -P -t PM_ARR_CSCF-01 -b 10.200.212.136:9092,10.200.212.136:9093,10.200.212.136:9094,10.200.212.136:9095,10.200.212.137:9092,10.200.212.137:9093,10.200.212.137:9094,10.200.212.137:9095   -m "7" -c 2  

How to reproduce
================
Run above command and keep all the broker instances down/unreachable. Measure the memory used by Producer process, Continuous increase in resident(RSS) memory is seen using pmap command.

root@abcd> while true; do pmap -x 28313 | tail -n 1 ; sleep 1; done
total kB          249244   64032   60332
total kB          249244   64032   60332
total kB          249260   64048   60348
total kB          249260   64048   60348
total kB          249260   64048   60348
total kB          249260   64048   60348
total kB          249276   64064   60364
total kB          249276   64064   60364
total kB          249276   64064   60364
total kB          249276   64064   60364
total kB          249292   64108   60408

When run with Valgrind Below summary could be seen. If run without cleanup(rd_kafka_topic_destroy, rd_kafka_destroy) functions, It shows some memory is accumulated by the library, which is freed only at the end at cleanup time. For daemon producer process it is not desirable.

==========run with clean up functions==========
==15741== 
==15741== LEAK SUMMARY:
==15741==    definitely lost: 0 bytes in 0 blocks
==15741==    indirectly lost: 0 bytes in 0 blocks
==15741==      possibly lost: 0 bytes in 0 blocks
==15741==    still reachable: 108,587 bytes in 3,267 blocks
==15741==         suppressed: 0 bytes in 0 blocks
==15741== 
==15741== For counts of detected and suppressed errors, rerun with: -v
==15741== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 1 from 1)

==========run without clean up functions==========
==28313== LEAK SUMMARY:
==28313==    definitely lost: 0 bytes in 0 blocks
==28313==    indirectly lost: 0 bytes in 0 blocks
==28313==      possibly lost: 6,080 bytes in 10 blocks
==28313==    still reachable: 154,828 bytes in 3,364 blocks
==28313==         suppressed: 0 bytes in 0 blocks
==28313== 
==28313== For counts of detected and suppressed errors, rerun with: -v
==28313== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 1 from 1)

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):0.9.2
 - [ ] Apache Kafka version: 
 - [x] librdkafka client configuration:default configuration in librdkafka-0.9.2/examples/rdkafka_performance.c
 - [x] Operating system: Linux 
 - [x] Using the legacy Consumer:NA
 - [x] Using the high-level KafkaConsumer:NA
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by tsplibrdkakfa** [comment]
Hi, Attaching the output of the below command run with and without clean up funcitons.

valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --show-leak-kinds=all /dump/gau/092/rdkafka_performance -P -t PM_ARR_CSCF-01 -b 10.200.212.136:9092,10.200.212.136:9093,10.200.212.136:9094,10.200.212.136:9095,10.200.212.137:9092,10.200.212.137:9093,10.200.212.137:9094,10.200.212.137:9095 -m "7" -c 2

[val2_withCleanUpFunctions.txt](https://github.com/edenhill/librdkafka/files/773221/val2_withCleanUpFunctions.txt)
[val3_withoutCleanUPFunctions.txt](https://github.com/edenhill/librdkafka/files/773222/val3_withoutCleanUPFunctions.txt)

**Comment by edenhill** [comment]
When brokers are not available messages will start queueing up internally in librdkafka until either the brokers become available again or the messages time out. The default timeout is 5 minutes.
The application must also call poll() at regular intervals so that delivery report callbacks, stats, etc, are served.

Do you think this explains what you are seeing?

**Comment by tsplibrdkakfa** [comment]
Hi Edenhill, 
Thanks for the reply. What I observe is different. In my test, I send only single byte ("7") - two times (-c 2 ), So total of 2 Bytes. Still I observe the memory increase in 10s of KBs every few seconds. This continues until time out happens, that is 5 minutes. I have attached full output of the command run with this issue. This observation is for the example producer process (rdkafka_performance).  But in my application which runs as daemon continues for ever and brokers never come up. So the memory keeps increasing  until  I "kill -9" it manually. 

One observation from my side is that brokers are not in good shape, out of multiple broker instances few are blocked, few are hanging somewhere, few are not even listening on given port also. Can broker/s state impact the behavior of producer process ? 

Thanks

**Comment by edenhill** [comment]
Interesting, I can't think of anything obvious expect some shortlived requests queuing up, but they should not increase in memory indefinately.
I'll have a closer look at your valgrind reports (much appreciated!!) tomorrow

**Comment by edenhill** [comment]
I can't reproduce this (latest master).
The memory usage increases with the number of messages queued but then flats out when no new messages are produced and the VSZ and RSS are constant until the messages time out.

Also, there is no indication of any leaks in the Unclean valgrind output, it simply shows the allocation that are typical for a running processes.

**Comment by tsplibrdkakfa** [comment]
Thanks Edenhill, I had tested it for both 0.8.2 and 0.8.3 librdkafka. I will test with master and check if I see the behavior.
