### ISSUE TITLE
Messages not received when auto.offset.reset is set to be largest

### ISSUE THREAD

**Issue by suiyuzeng** [edenhill/librdkafka#1059]
Description
===========
Messages are not received when the partition is not consumed for the first time. The auto.offset.reset is set to be largest.

How to reproduce
================
1.create a group;
2.start a producer, and send messages to a fixed partition, such as partition 0;
3.start a consumer
4.close consumer
5.start another producer, and send 10 messages to another partition, such as partition 1;
6.close the second producer and restart the consumer
7.the 10 messages the second producer sent are not received

My understanding is that the 10 messages can be received when the consumer start for the second times. And java client can receive the 10 message, when the auto.offset.reset is set to be largest.
In the function rd_kafka_commit_message, the offset is not committed when the err is not 0. Offset will not be committed, when the err is RD_KAFKA_RESP_ERR__PARTITION_EOF. If the offset should be committed when the err is RD_KAFKA_RESP_ERR__PARTITION_EOF?

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):0.9.2
 - [x] Apache Kafka version: 0.9.0
 - [ ] librdkafka client configuration:
 - [ ] Operating system:linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka will not commit offsets if it reaches the end of the partition without seeing any messages, which is the case if you dont have any previously committed offsets and set auto.offset.reset=largest (default). It will hit EOF and do nothing.
