### ISSUE TITLE
RdKafka - Enable Log Compaction when creating a new topic

### ISSUE THREAD

**Issue by ofirzaibert** [edenhill/librdkafka#1060]
Hey, 

is it possible to enable log compaction when creating a new topic via rdKafka in C#?

On my computer I'm able to alter the topic using this command:
bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic my-topic
--config cleanup.policy=compact

Is there a similar way for me to change the topic's configuration using rdKafka.Config?

**Comment by treziac** [comment]
You can't create topics in kafka clients for the moment, you must do it on broker-side (KIP-4 is working on changing it)
You create topics with rdkafka only because you set auto create in your broker

**Comment by ofirzaibert** [comment]
Oh OK, I understand.

Thanks for the quick reply.
