### ISSUE TITLE
librdkafka consume group is missing after some time【question】

### ISSUE THREAD

**Issue by xjj210130** [edenhill/librdkafka#1061]
Description
===========
hi all:
i use librdkafka to consumer message, and use keep-alive.. First i use only one thread to consume message.
The code like the foloowing:

```
class Consumer
{
public:
void init();
void fun();
private:
RdKafka::KafkaConsumer* m_pConsumer;

};

void Consumer::init()
{
m_pGlobalConf->set("group.id", "test", errstr)
m_pGlobalConf->set("enable.auto.commit", "true", errstr);
m_pGlobalConf->set("heartbeat.interval.ms", "1000", errstr);
m_pConsumer= RdKafka::KafkaConsumer::create(m_pGlobalConf, errstr);
}

void Consumer::fun()
{
while(bFlag)
{
if(NULL != m_pConsumer)
{
RdKafka::Message *msg = m_pConsumer->consume(1000);
}

}
```

Now, i user the follow cmd:
./kafka-consumer-groups.sh --new-consumer --bootstrap-server xx:9092 --list default

it can show the group : test

but after one day, the group :test is missing.

librdkafka version is 0x00090301
Is some one know why? thanks .

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [. ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by vin-d** [comment]
Hi,
I have seen a few issues lately related to consumer group management : #947 / #1006 / #1022 

I would suggest you monitor theses issue and retry your scenario once they are fixed. It could be because of the same bug.

in the meantime, what I've done is  to make my consumer resubscribe if it receives a ERR_UNKNOWN_MEMBER_ID error from an offset commit callback. But this is not ideal as the side effect could be reprocessing of some messages already.

**Comment by edenhill** [comment]
I think these issues should be fixed on master, can you try upgrading?

**Comment by vin-d** [comment]
yes the three tickets I was refering to are  fixed. (tested with https://github.com/edenhill/librdkafka/commit/f343ce874c0ee4e182a20026001ae70029c19daf )
so, I guess this one too.

**Comment by edenhill** [comment]
@xjj210130 Can you try latest master?

**Comment by xjj210130** [comment]
@edenhill , @vin-d Thanks . I will do it,and update the question. now , i use the librdkafka version is 0x00090301, and it's master branch.

**Comment by edenhill** [comment]
Could it be that you had no new messages for longer than the __consumer_offsets retention policy?
See `offsets.retention.minutes` here: http://kafka.apache.org/documentation.html#brokerconfigs

Default value is 24 hours which seems inline with your previously stated time frame.
