### ISSUE TITLE
Is there has a config-item for auto create the topic?

### ISSUE THREAD

**Issue by KomaBeyond** [edenhill/librdkafka#1062]
I want to config my kafka when the topic doesn't exists it can be create it automatic. I search in the CONFIGRATION file, but not found.

**Comment by treziac** [comment]
You can't manage topic creation in kafka clients for the moment, you must do it on broker-side (KIP-4 is working on changing it)
Specifically, you need to set auto.create.topics.enable to true (default) on your broker configuration
