### ISSUE TITLE
automate the kafka producer process using UNIX shellscript

### ISSUE THREAD

**Issue by kanchan1234** [edenhill/librdkafka#1063]
#!/bin/bash
export LD_LIBRARY_PATH=/usr/app/shipper/local/lib1/
echo $LD_LIBRARY_PATH
echo $PWD
nohup ./shipper -f=shipper-kafka1.conf  >output.txt &
cd /usr/app/shipper/src/cgnshipper/cgn_stub/
echo $PWD
cmd1="./stub_cgn -n=100 -a=127.0.0.1 -p=2340"
$cmd1
p=shipper-kafka1
pkill -f $p
echo killed "$p"
...shipper-kafka is th ekafka producer and cgn_stub prodces the events..the target is to frst start kafka producer..It will listen to Cgn_stub ..cgn_stub will feed the data into it...I tried this code it is working but Cgn_stub doesn't gets connected to shipper-kafka..msg read is ) by kafk a producer

**Comment by edenhill** [comment]
There is no information related to librdkafka to go on here.

**Comment by kanchan1234** [comment]
the environment variable LD_LIBRARY_PATH points the locations of librdkafka

**Comment by edenhill** [comment]
Sorry, but there are no technical detaisl to go on here.
I will be happy to reopen if any information is provided showing that librdkafka is the problem you can not run your shell script.
