### ISSUE TITLE
Messages "stuck" in queue for 5 minutes after metadata timing out, and then they are dropped

### ISSUE THREAD

**Issue by UrielGuy** [edenhill/librdkafka#1064]
Description
===========

My scenario is as follows:
I'm trying to send network traffic in the form of pcapng frames over 4 kafka topics (for headers, TCP, UDP and others). The phenomenon I'm seeing is as follows: 
* I'm seeing alot of metadata information timeout messages
* Once in a while after a metadata timeout some of the messages get stuck in the local queue
* after 5 minutes I receive a Message times out error. 
* Important to note: During those 5 minutes newer packets are sent successfully to the broker

I have tried to change topic.metadata.refresh.interval.ms to -1 (otherwise set to 60000), but then I'm getting the timeouts every second or so, and drops are much worst. 

In the attached log I've enabled debug for broker and topic. 
You  can see many timeouts, an example for when the problem is happening can be seen with the timeout at 00:16:19, after which there are 9 messages stuck in the udp_queue until 00:21:19 when they time out, or between 00:58:32 to 01:03:32. there are some more examples in this file. 
I'm also attaching the log from the initialization of the producers. 
[strike_capture_init.txt](https://github.com/edenhill/librdkafka/files/781053/strike_capture_init.txt)
[strike_capture_problem_logs.txt](https://github.com/edenhill/librdkafka/files/781054/strike_capture_problem_logs.txt)

I really appreciate your help and all of the hard work you've put into this library!

How to reproduce
================

It happens pretty much constantly on my end, I just send the amount of data on the log and see it happening. My brokers are in a 3 machine cluster that's only doing this topic for now, so it's supposed to be enough

Kafka Broker files: 
=========

[controller.log.2017-02-16-00.txt](https://github.com/edenhill/librdkafka/files/781097/controller.log.2017-02-16-00.txt)
[controller.log..txt2017-02-16-01.txt](https://github.com/edenhill/librdkafka/files/781099/controller.log.txt2017-02-16-01.txt)
[server.properties.txt](https://github.com/edenhill/librdkafka/files/781110/server.properties.txt)
[controller_master_leader.txt](https://github.com/edenhill/librdkafka/files/781111/controller_master_leader.txt)

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 65c8bc48da311b0667ba9147ff07025b95c817dd
 - [x] Apache Kafka version: 0.10.1.0
 - [x] librdkafka client configuration:
    * Producer config: 
        
name | value
------ | -----
debug | broker,topic
metadata.broker.list | st-nj01-kafka01:9092
socket.keepalive.enable | true
topic.metadata.refresh.interval.ms | 60000
message.max.bytes | 1050625
compression.codec | lz4
queue.buffering.max.ms | 1
socket.blocking.max.ms | 5
queue.buffering.max.messages | 1000000
socket.send.buffer.bytes | 100000000
api.version.request | true

    * Topic config:

name | value
------ | -----
produce.offset.report | true

 - [x] Operating system: Linux, Fedora Core 20
 - [x] Using the legacy Consumer: No
 - [x] Using the high-level KafkaConsumer: No
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: Attached.
 - [x] Provide broker log excerpts
 - [ ] Critical issue

**Comment by UrielGuy** [comment]
Just to be clear - I don't really care about metadata, but missing messages is sort of catastrophic for my scenario

**Comment by edenhill** [comment]
Thanks for a good issue report.

It sounds like you are not actually loosing messages, just that some messages time out (so you can take appropriate actions, but the messages are not lost). Right?

I dont see much librdkafka debugging in the provided log files, did you forget to attach it?

**Comment by UrielGuy** [comment]
Thanks for the speedy reply!
The times out messages are actually dropped and I'm never receiving them. 
I have the librdkafka logs along with my own in these files: 

https://github.com/edenhill/librdkafka/files/781053/strike_capture_init.txt
https://github.com/edenhill/librdkafka/files/781054/strike_capture_problem_logs.txt

If there are more logs I can provide I'm more than happy to generate them. 

Glad to write a good report, I know how frustrating a one line issue can be :smile: 

Thanks again for your help!

**Comment by edenhill** [comment]
But you are receiving delivery report handlers for the timed out messages, right? This means that they are passed back to your application so you can handle this case (retry, write to permanent storage, drop - whatever the app policy is). So the messages are not dropped.

The strike_capture_problem_logs.txt only contains your app output, not any librdkafka debugging, so it is hard to know what's going on.

Can you reproduce this with debug=broker,queue,msg ?

**Comment by UrielGuy** [comment]
I am, but by that point if I resend these messages they are out of order, which is important to me. 
I will regenerate with debug=broker,queue,msg and post tomorrow, as during the day there's a lot more traffic and it's harder to find isolated cases of this problem manifesting.  (will look what I'm getting now and see). 
I've accidentally attached the wrong log for the problem, from before I turned on broker and topic logs. Here is the one with the librdkafka logs. the times I specified in the original message (quoted below) are also correct for this file and not the last one. Sorry about that.

> You can see many timeouts, an example for when the problem is happening can be seen with the timeout at 00:16:19, after which there are 9 messages stuck in the udp_queue until 00:21:19 when they time out, or between 00:58:32 to 01:03:32. there are some more examples in this file.

[strike_capture_problem_logs_correct.txt](https://github.com/edenhill/librdkafka/files/781321/strike_capture_problem_logs_correct.txt)

Thanks again for your time and help!

**Comment by edenhill** [comment]
Thanks, that log is better :)

So it seems this happens when librdkafka's topic metadata information times out, the reason for timeout is that no new metadata has been seen for that topic in the allotted time frame (180s).
This in turn could be caused by:
 * librdkafka not sending metadata requests often enough
 * brokers responding too slowly to metadata requests
 * librdkafka not querying the desired topics (bug)

With this new information I would like you to set  `debug=topic,metadata`

How many topics do you have in your cluster?

**Comment by UrielGuy** [comment]
Will do. Right now we have ~ 20 topics, and only 4 (mine)active, as we are still in development.

**Comment by UrielGuy** [comment]
Here are logs from a few minutes now with debug-topic,metadata
[metadata_logs.txt](https://github.com/edenhill/librdkafka/files/781430/metadata_logs.txt)

**Comment by edenhill** [comment]
Thanks, that's very good.
Could you enable log.thread.name=true as well?

Much appreciated

**Comment by UrielGuy** [comment]
Attached. Thanks again for all of your help! It's really appreciated. 

[metadata_topic_thread_log.txt](https://github.com/edenhill/librdkafka/files/781491/metadata_topic_thread_log.txt)

**Comment by edenhill** [comment]
Thanks alot.

This is the problem:
`LOG-7-METADATA: ..: Skipping metadata refresh of 1 topic(s): connected: already being requested`

It is suppressing metadata updates for the topics because it thinks it is already being requested.
I'd like to reproduce this locally, will give it a shot but not sure what's special about your setup

**Comment by UrielGuy** [comment]
Let me know if there's anything I can do to help. Again, I appreciate your help! 
The first message has all of my configs, but if there's anything missing I'd be more than happy to provide it.

**Comment by edenhill** [comment]
How easy is this for you reproduce?
Im thinking it would be useful if I could get a repro with debug=all

**Comment by UrielGuy** [comment]
It reproduces constantly. Will run now,

**Comment by edenhill** [comment]
Wait, I misread your initial post's version, you are on a mid-january master commit.
I strongly urge you to update to latest master before reproducing (even without debug=all) to see if this has been fixed.

There are a couple of metadata fixes in there since then.

**Comment by UrielGuy** [comment]
Oh! that's good news. I will try it tomorrow, In the meanwhile, I'm posting the debug=all log here.

**Comment by UrielGuy** [comment]
Having recompiled everything with master I'm getting the following errors trying to run:
unable to set event_cb: Invalid value type
unable to set dr_cb: Invalid value type

Has anything changed around that area? Google didn't quickly get any results..

**Comment by edenhill** [comment]
You need to recompile your application, class members were moved by mistake so the ABI safety is broken.

**Comment by UrielGuy** [comment]
From 10-15 minutes of running today after updating to master seems to have done the trick. 
Thank you so much for your time and help! Happy to see an easy solution to the problem. 
If the issue happens again (overnight?) I will revisit this.

**Comment by edenhill** [comment]
Glad to hear that!
