### ISSUE TITLE
Debugging context

### ISSUE THREAD

**Issue by keshriavi** [edenhill/librdkafka#1065]
Description
===========

I am trying to execute rdkafkaexample program with debugging option. I am giving "-d producer" but  showing error " Debug configuration failed: Invalid value for configuration property "debug": producer".
why? 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [x] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
producer is not a valid debug context, see [CONFIGURATION.md](CONFIGURATION.md) for the full list, search for debug

**Comment by edenhill** [comment]
For the producer, try `-d topic,broker`
