### ISSUE TITLE
producer deadlock  on librdkafka 0.9.1?

### ISSUE THREAD

**Issue by xiangqiao123** [edenhill/librdkafka#1068]
Description
===========
producer deadlock  on librdkafka 0.9.1

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.9.1 ] librdkafka version (release number or git tag):
 - [ 0.9] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Do you have any additional information that could help in tracking down this problem?

**Comment by xiangqiao123** [comment]
hi edenhill ,thank you for replay this question.

it is like thisi issue,https://github.com/edenhill/librdkafka/issues/1036

librdkafka 0.9.1 also has this question?

**Comment by edenhill** [comment]
did you try latest master?

**Comment by xiangqiao123** [comment]
on librdkafka 0.9.1, i can not reproduce this question every time，but  when the producer‘s concurrency level is very high it wil emit this issue some times.

**Comment by edenhill** [comment]
Can you try upgrading to librdkafka master or 0.9.3?

**Comment by edenhill** [comment]
Upgrade to 0.9.4 which is the latest release
