### ISSUE TITLE
win32: producer latency

### ISSUE THREAD

**Issue by mineralres** [edenhill/librdkafka#1069]
Description
===========
Here is my config
```javascript
Global_conf{
builtin.features : gzip,snappy,ssl,sasl,regex,lz4
client.id : rdkafka
metadata.broker.list : 192.168.1.9:9092
message.max.bytes : 1000000
message.copy.max.bytes : 65535
receive.message.max.bytes : 100000000
max.in.flight.requests.per.connection : 1000000
metadata.request.timeout.ms : 60000
topic.metadata.refresh.interval.ms : 300000
metadata.max.age.ms : -1
topic.metadata.refresh.fast.interval.ms : 250
topic.metadata.refresh.fast.cnt : 10
topic.metadata.refresh.sparse : true
socket.timeout.ms : 60000
socket.blocking.max.ms : 1
socket.send.buffer.bytes : 0
socket.receive.buffer.bytes : 0
socket.keepalive.enable : false
socket.nagle.disable : false
socket.max.fails : 3
broker.address.ttl : 1000
broker.address.family : any
reconnect.backoff.jitter.ms : 500
statistics.interval.ms : 0
enabled_events : 0
log_cb : 507D4050
log_level : 6
log.queue : false
log.thread.name : true
log.connection.close : true
socket_cb : 507E3AA0
open_cb : 507EF470
internal.termination.signal : 0
api.version.request : false
api.version.fallback.ms : 1200000
broker.version.fallback : 0.9.0
security.protocol : plaintext
sasl.mechanisms : GSSAPI
sasl.kerberos.service.name : kafka
sasl.kerberos.principal : kafkaclient
partition.assignment.strategy : range,roundrobin
session.timeout.ms : 30000
heartbeat.interval.ms : 1000
group.protocol.type : consumer
coordinator.query.interval.ms : 600000
enable.auto.commit : true
auto.commit.interval.ms : 5000
enable.auto.offset.store : true
queued.min.messages : 100000
queued.max.messages.kbytes : 1000000
fetch.wait.max.ms : 100
fetch.message.max.bytes : 1048576
fetch.min.bytes : 1
fetch.error.backoff.ms : 500
offset.store.method : broker
enable.partition.eof : true
queue.buffering.max.messages : 100000
queue.buffering.max.kbytes : 4000000
queue.buffering.max.ms : 1
message.send.max.retries : 2
retry.backoff.ms : 100
compression.codec : none
batch.num.messages : 10000
delivery.report.only.error : false
}
Topic_conf{
request.required.acks : 1
request.timeout.ms : 5000
message.timeout.ms : 300000
produce.offset.report : false
compression.codec : inherit
auto.commit.enable : true
auto.commit.interval.ms : 60000
auto.offset.reset : largest
offset.store.path : .
offset.store.sync.interval.ms : -1
offset.store.method : broker
consume.callback.max.messages : 0
}
```

and my produce code below
```c++

conf_->set("queue.buffering.max.ms", "1", err);
conf_->set("socket.blocking.max.ms", "1", err);

inline int sync_produce(const std::string& msg)
{
	int ret = -5555;
	RdKafka::ErrorCode resp = producer_->produce(topic_, RdKafka::Topic::PARTITION_UA, RdKafka::Producer::RK_MSG_COPY,
		const_cast<char *>(msg.c_str()), msg.size(), NULL, &ret);
	if (resp != RdKafka::ERR_NO_ERROR){
		GO_LOG_SEV(error) << "% Produce failed: " << RdKafka::err2str(resp) << std::endl;
		ret = -1;
	}
	else {
		while (ret == -5555){
			producer_->poll(1000);
		}
	}
	return ret;
}
void DRCB::dr_cb(RdKafka::Message &message)
{
	int* err = (int*)message.msg_opaque();
	*err = message.err();
}
```

in my test i got  50-60 ms latency,  how can set to send message as soon as posible in sync mode,
can i get latency < 1ms  ?

my kafka (version: 0.10.1.1) runs on centos 7
producer compile and runs on window 7

reference:
https://github.com/edenhill/librdkafka/wiki/Sync-producer

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): master:latest
 - [x] Apache Kafka version: 0.10.1.1
 - [ ] librdkafka client configuration:
 - [ ] Operating system: windows 7
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
If you enable debug=protocol you will see per-request RTT (round-trip time) latency printouts, look for the ProduceRequests to see how much time is actually spent on the network and broker.
You can also enable statistics.interval.ms and set a stats callback to check for average rtt and internal latency, see [Statistics](https://github.com/edenhill/librdkafka/wiki/Statistics)

**Comment by mineralres** [comment]
@edenhill  When i set debug=protocol enabled, i get the RTT ~= 30ms,  my question is:
1  when i produce message, i spend about  60ms/msg , about 2 * RTT,  should it be equal to RTT?
2  when i ping  192.168.1.9( the broker server ip),  i got ~0.6 ms ,  it's much different from kafka RTT(~30ms),  is there any options have a great impact ?

**Comment by edenhill** [comment]
If you get 30ms rtt  for ProduceRequests and your network latency is 0.6, then that means the broker is spending ~28ms handling the message, unless it is a Windows TCP issue (not necessarily in Windows but the way librdkafka interacts with the TCP stack).

Can you try the same type of measurement from a non-Windows client and see if you get the same RTTs?
E.g.: `echo hi | kafkacat -b brokers.. -t mytopic -P -X queue.buffering.max.ms=1 -d protocol`

**Comment by edenhill** [comment]
Possibly related issue with latency of 30ms: https://github.com/confluentinc/confluent-kafka-dotnet/issues/89

**Comment by edenhill** [comment]
@mineralres Can you try setting socket.nagle.disable=true in your client? We saw a 50% drop in latency in the other issue when doing that
