### ISSUE TITLE
What is "assert: rktp->rktp_assigned"

### ISSUE THREAD

**Issue by muumu** [edenhill/librdkafka#1070]
Description
===========
I have got the following message from the consumer I am using.
```
*** rdkafka_cgrp.c:1589:rd_kafka_cgrp_op_serve: assert: rktp->rktp_assigned ***
```
https://github.com/edenhill/librdkafka/blob/26448824be13f184555e653a967caad9328ca2be/src/rdkafka_cgrp.c#L1589
What is the problem of this failure?

How to reproduce
================
I do not know but it happens every several dozens of minutes.

Checklist
=========
 - [ x ] librdkafka version (release number or git tag): 0.9.2rc
 - [ x ] Apache Kafka version: 0.10.1.1
 - [ ] librdkafka client configuration:
 - [ x ] Operating system: CentOS 6
 - [ ] Using the legacy Consumer
 - [ x ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This indicates a bug in the state machinery which I believe has been fixed since then.
Can you try latest master?

**Comment by muumu** [comment]
I have updated librdkafka to latest master and confirmed that the error has disappeared.
I understand that it was the bug you said.
Thank you!
