### ISSUE TITLE
Failed assert in: rd_kafka_cgrp_metadata_update_check

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#1071]
Hi Magnus,

Have you seen assert:
**rd_kafka_assert(NULL, thrd_is_current(rkcg->rkcg_rk->rk_thread));**
in: 
**rd_kafka_cgrp_metadata_update_check**
, fail before?

Got that in two consumers at the same time. Using version 0.9.2.

Both consumers were running for 8 hours getting 7 messages every 5 seconds. Unfortunately i do not have more log output at this time.

**Comment by edenhill** [comment]
I think I stumbled on this as well, there were some cases where metadata parsing would not take place on the correct thread.
It has been fixed on master (soon 0.9.4) with the new metadata redesign.

**Comment by MaximGurschi** [comment]
Thanks Magnus, nice to see this expected to be out soon!
