### ISSUE TITLE
Producer and "brokers are down" error

### ISSUE THREAD

**Issue by Nnamdi** [edenhill/librdkafka#1072]
Description
===========
Kafka Version: 0.10.1.1
librdkafka: 0.9.3

I have a producer that connects to a cluster of 3 brokers, and very infrequently sends a single message.  After a period of time, it production fails with the error:

```
6/6 brokers are down
```

I am using the default idle timeout in the broker, which looks to be 10mins, the same frequency librdkafka sends metadata requests, looking at its logging:

```
12:23:52.145 [20612] SEND: host1:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 1)
12:23:52.145 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 1)
12:23:52.145 [20611] SEND: host2:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 1)
12:23:52.165 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 1)
12:23:52.165 [20616] SEND: host1:21000/1003: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 1)
12:23:52.165 [20617] SEND: host2:21000/1002: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 1)
12:28:52.135 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 2)
12:33:52.152 [20616] SEND: host1:21000/1003: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 2)
12:33:52.179 [20617] SEND: host2:21000/1002: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 2)
12:33:52.253 [20616] SEND: host1:21000/1003: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 3)
12:33:52.266 [20612] SEND: host1:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 2)
12:33:52.299 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 2)
12:33:52.480 [20617] SEND: host2:21000/1002: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 3)
12:33:52.551 [20611] SEND: host2:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 2)
12:38:52.165 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 3)
12:43:52.159 [20611] SEND: host2:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 3)
12:43:52.338 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 4)
12:43:52.369 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 4)
12:43:52.379 [20616] SEND: host1:21000/1003: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 4)
12:43:52.433 [20612] SEND: host1:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 3)
12:43:52.739 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 5)
12:43:52.780 [20617] SEND: host2:21000/1002: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 4)
12:48:52.190 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 6)
12:53:52.251 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 7)
12:53:52.308 [20611] SEND: host2:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 4)
12:53:52.308 [20611] SEND: host2:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 5)
12:53:52.428 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 5)
12:53:52.509 [20616] SEND: host1:21000/1003: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 5)
12:53:52.607 [20617] SEND: host2:21000/1002: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 5)
12:53:52.666 [20612] SEND: host1:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 4)
12:58:52.159 [20617] SEND: host2:21000/1002: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 6)
13:03:52.127 [20617] SEND: host2:21000/1002: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 7)
13:03:52.350 [20616] SEND: host1:21000/1003: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 7)
13:03:52.374 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 6)
13:03:52.381 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 8)
13:03:52.433 [20611] SEND: host2:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 6)
13:03:52.835 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 7)
13:03:52.883 [20612] SEND: host1:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 5)
13:08:52.198 [20611] SEND: host2:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 7)
13:13:52.202 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 9)
13:13:52.202 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 10) 
13:13:52.247 [20617] SEND: host2:21000/1002: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 8)
13:13:52.459 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 8)
13:13:52.491 [20616] SEND: host1:21000/1003: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 8)
13:13:52.952 [20611] SEND: host2:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 8)
13:13:53.024 [20612] SEND: host1:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 6)
13:18:52.230 [20612] SEND: host1:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 7)
13:23:52.210 [20612] SEND: host1:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 8)
13:23:52.309 [20616] SEND: host1:21000/1003: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 10) 
13:23:52.340 [20612] SEND: host1:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 9)
13:23:52.377 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 11) 
13:23:52.413 [20617] SEND: host2:21000/1002: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 9)
13:23:52.678 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 12) 
13:23:52.798 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 9)
13:23:53.215 [20617] SEND: host2:21000/1002: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 10) 
13:23:53.296 [20611] SEND: host2:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 9)
13:28:52.135 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 13) 
13:33:52.134 [20617] SEND: host2:21000/1002: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 11) 
13:33:52.362 [20611] SEND: host2:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 10) 
13:33:52.400 [20615] SEND: host3:21000/1001: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 14) 
13:33:52.428 [20616] SEND: host1:21000/1003: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 11) 
13:33:52.461 [20612] SEND: host1:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 10) 
13:33:52.921 [20612] SEND: host1:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 11) 
13:33:53.006 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 10) 
13:38:52.213 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 11)
```

I understand that those threads sending metadata requests could be disconnected by the broker, however, as you can see from the log extract above, there is a thread sending a MetadataRequest every 5 minutes, which is less than the idle timeout (and in the full log extract, I do not see it having to re-establish the connection for the message on 5min boundaries).  Could you please clarify:

1.  Why does the all brokers down error occur when at least 1 thread is sending requests within half the timeout limit?
2.  Why does it indicate 6 connections are down, when it is connected to 3 brokers?
3.  Is there anything that could be done to have it reconnect when we produce?

It is suggested in #915 that the idle timeout should be set higher, but some users might only send a handfull of messages a day, of be left running overnight without producing, so I would like to avoid setting the timeout to days if possible.

How to reproduce
================

1. Create a producer.
2. Sleep for 20 minutes.
3. Produce a message.
4. Return to step {2)

The problem will eventually occur.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Re 3 vs 6 brokers:
Since there is no way to map an existing connection to a broker id the client can only use the broker name+port and id from received metadata information to know what broker it is actually connecting to.
This means that it can't map a bootstrap broker to a proper broker, unless the bootstrap broker hostname and port is configured exactly as that returned from metadata.
Since you changed the hostnames in the output I can't be sure, but my guess is that they are not identical.
So you end up with 2x the brokers: one bootstrap and one proper for each broker.

Since the metadata refresh interval is exactly the same as the idle interval it is likely that the broker idle connection reaper will kick in at the same time the client sends a new Metadata request, thus probably disconnecting the client just before it receives the request.

This would explain why all of your brokers are disconnected simultaneously, if it wasn't for this guy:
> `12:28:52.135 [20613] SEND: host3:21000/bootstrap: Sent MetadataRequest (v0, 42 bytes @ 0, CorrId 2)`

Its interval is offset by 5 minutes to the other broker threads and thus should not be disconnected at the same time as others (it'll be disconnected every 10 minutes for the same reason as stated above though).

So yes, this does seem weird and I don't have a good answer.
I'll try reproduce it, in the meantime as a workaround set the topic.metadata.refresh.interval.ms lower than 10 minutes (like 9:30 or so).

The next version of librdkafka (0.9.4, master) has had its metadata engine rewritten and it will send much fewer metadata requests (not one per broker per interval, for instance).
So when you upgrade the lowered metadata refresh interval will not really help.

You should probably configure `log.connection.close=false` and increase `reconnect.backoff.jitter.ms` to get some time dispersions between broker connections, but that wont rid the possibility of an initial ALL_BROKERS_DOWN being emitted.

**Comment by Nnamdi** [comment]
Thanks for the clarification.

The 6 broker thing makes sense now, I pass a connection string like `host1:1234,host2:1234,host3:1234`, but the rdkafka logging shows metadata coming from `host1.fully.qualified.name/1234`, etc.

For point (3), after some more testing, I see that the message is delivered, so it must be successfully reconnecting to the brokers.  I was only calling `poll` on the producer immediately after a produce, so I guess its possible that the all brokers down event is raised before I attempt to send the message, but I was only pulling it off the event queue after, e.g.

1. Brokers idle disconnect, all brokers down event added to queue.
2. Message is produced, and we are reconnected to the brokers.
3. `poll` the producer event_cb queue, where we see the all brokers down event.

I will try using a lower `topic.metadata.refresh.interval.ms`.  But as the ALL_BROKERS_DOWN could occur (if the brokers config was changed for example), does that mean that in this context, the error should be ignored, as the only way to distinguish between real broker failures and the idle disconnects is if producing a message fails?

**Comment by edenhill** [comment]
produce() is not directly affected on the availability of leader broker, if no leader is available it will queue the message for up to message.timeout.ms.

Also, ALL_BROKERS_DOWN doesn't really mean anything to librdkafka, it is just a friendly indication to the application that **currently** there are no brokers to communicate with. But librdkafka will continue to try to reconnect indefinately, and it will attempt to re-send messages until message.timeout.ms or message.max.retries are exceeded.


You should typically try to call poll() at regular intervals, to get events, delivery reports, statistics, etc, even if you are not actively producing. This is a recommendation but not strictly required.

**Comment by Nnamdi** [comment]
That clears things up nicely - thanks for the help!
