### ISSUE TITLE
connection errors to brokers

### ISSUE THREAD

**Issue by lathakris** [edenhill/librdkafka#1073]
Hi,

Description
===========

Is there a generic error i can handle if I have brokers which go down and change IP address ? We have a scaling/shrinking scenario based on load and the brokers IP may change. I can always get the list of alive brokers at any given point in time. I would like to connect to this updated list when I receive that error ? I do consume and produce in separate threads in my application. I am using librdkafka-0.8 version. Basically I need to know when to reconnect. 

Thank you so much for your help.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You could register an error_cb and look for __TRANSPORT errors, they indicate that the connection could not be made or was torn down.
In this case you can add new brokers through rd_kafka_brokers_add(), but old ones can't be removed.

**Comment by lathakris** [comment]
Thank you so much for your prompt response. Does rd_kafka_brokers_add() check for duplicate brokers ?

**Comment by edenhill** [comment]
Yes, it will ignore previously configured or add():ed brokers that exactly match the name and port.

**Comment by lathakris** [comment]
Thank you.
