### ISSUE TITLE
Memory leak when kafka server is down

### ISSUE THREAD

**Issue by xiaocairush** [edenhill/librdkafka#1074]
Description
===========
Let's free [rd_kafka_msg_t *rkm](https://github.com/edenhill/librdkafka/blob/68de70e93597af9274ac0619be1715abc336cea9/src/rdkafka_msg.c#L211)  pointer as it will cause memoryleak when kafka server is down.

How to reproduce
================
Produce message when kafka server is down.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.2
 - [x] Apache Kafka version: 0.10.1.0
 - [ ] librdkafka client configuration: no specified
 - [ ] Operating system: windows
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by xiaocairush** [comment]
I found the **rd_kafka_msg_new** methoud will return in [line 230](https://github.com/edenhill/librdkafka/blob/68de70e93597af9274ac0619be1715abc336cea9/src/rdkafka_msg.c#L230) without free  **rd_kafka_msg_t *rkm pointer** when I debug.

**Comment by xiaocairush** [comment]
The follwing code has generated memory leak
```
RdKafka::ErrorCode lErrorCode = mProducerPtr->produce(lpTopic, 0/*use this as default for now*/,
				RdKafka::Producer::RK_MSG_COPY,
				/* Payload and length */
				const_cast<char *>(irValue.ToString().c_str()), irValue.GetStringLength(),
				/* Optional key string*/
				NULL,
				/* Message opaque, provided in
				* delivery report callback as
				* msg_opaque. */
				NULL
				);
```

**Comment by edenhill** [comment]
If produce() returns NO_ERROR it means the message was enqueued for delivery, if the broker is down the message will linger in internal queues until a leader broker comes up again or the message times out (message.timeout.ms).
Use DeliveryReportCb and poll() to get notification when messages are finally delivered or fails permanently.

**Comment by xiaocairush** [comment]
Thanks @edenhill for answering my stupid question, which method should I call to release the memory of message queue ? 
Some code like [this](https://github.com/edenhill/librdkafka/blob/8d96733529f6d9a788d1620760a4bf529cb00057/examples/rdkafka_example.cpp#L519)?

```
delete topic;
delete producer;
```

**Comment by edenhill** [comment]
Yes, that should be sufficient.

**Comment by xiaocairush** [comment]
Hi @edenhill ,

The issue can be reproduced just little change to rdkafka_example.cpp.

If I change the code from [Line 513](https://github.com/edenhill/librdkafka/blob/8d96733529f6d9a788d1620760a4bf529cb00057/examples/rdkafka_example.cpp#L513) 
```
   while (run && producer->outq_len() > 0) {
      std::cerr << "Waiting for " << producer->outq_len() << std::endl;
      producer->poll(1000);
    }
```

Just change to :
 
```
producer->poll(1000);
```

Then run the example's producer mode. The memory leak will be detect by [Deleaker ](http://www.deleaker.com/) in windows.

**Comment by edenhill** [comment]
When you move poll() out of that loop you are no longer guaranteed to wait for all messages to be delivered, you'll just wait for one or more messages, but not wait for longer than 1 s (which coincides with the default buffering interval queue.buffering.max.ms).
So there will still be messages enqueued inside librdkafka, either for transmission to broker, retries or for delivery report callbacks.

You need to call poll() until the outq_len() reaches 0  (or just call flush() that abstracts this) to make sure all messages are accounted for before terminating.

**Comment by xiaocairush** [comment]
Thanks @edenhill ,
  Is it possible to enhance kafka library by adding feature like shutdown hook to delete them? I think the feature will make librdkafka more robust although it's responsibily of application to close kafka correctly.

Because the [main thread](https://github.com/edenhill/librdkafka/blob/8d96733529f6d9a788d1620760a4bf529cb00057/src/rdkafka.c#L1001) may be killed by code like exit() and that will cause memory leak.  
In my case, the kafka main thread is started from another thread which my application main thread has started. Then my application main thread returned 0 and exit() in C:\VS14\VC\crt\src\vcruntime\exe_common.inl (Line 260) killed librdkafka main thread. That has caused my memory leak.

**Comment by edenhill** [comment]
It would be possible to clean up kafka client instances in atexit(), but since it might be a blocking operation (waiting for messages to be produced) I suspect this would only cause much more problems than it solves.

It is very hard to generalize on these things since all applications are different, it is thus the application's responsibility to properly close and clean up Kafka client instances.
