### ISSUE TITLE
Termination sequence hangs when all the brokers are killed and re-started again.

### ISSUE THREAD

**Issue by V-Anand** [edenhill/librdkafka#1078]
Description
===========
When all the brokers go down and come back, a synchronous producer in the middle of sending its message set hangs on "proper termination sequence" as listed in the wiki:
 /* 1) Make sure all outstanding requests are transmitted and handled. */
     while (rd_kafka_outq_len(rk) > 0)
         rd_kafka_poll(rk, 50);

The stack trace for the hanging thread is given below.

#0  0x00007f24047d064b in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f23a637b840 in cnd_timedwait_ms (cnd=cnd@entry=0x1543d3f8, mtx=mtx@entry=0x1543d3d0, timeout_ms=timeout_ms@entry=1000) at tinycthread.c:501
#2  0x00007f23a63543e2 in rd_kafka_q_serve (rkq=0x1543d3d0, timeout_ms=1000, max_cnt=0, cb_type=1, callback=0x7f23a63317a0 <rd_kafka_poll_cb>, opaque=0x0) at rdkafka_queue.c:401

How to reproduce
================
Implement a synchronous producer as given in the librdkafka wiki. 
Send a batch of messages one by one through the synchronous producer.
Kill all the brokers.
Allow the sending of batch of messages to error out in the middle.
Bring back all the brokers
Terminate the synchronous producer as given in the "proper termination sequence" given in the wiki.
Observe the outq_len > 0 and hence the infinite looping of the above termination sequence.

Checklist
=========
Please provide the following information:

 - [ v0.9.3] librdkafka version (release number or git tag):
 - [2.11_0.10.1.1 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I believe a fixed an issue like this where the leader was not always re-detected.
Can you try the same with latest master?

**Comment by V-Anand** [comment]
I tried a few times with the latest master and I am unable to reproduce this issue. Thanks.

**Comment by edenhill** [comment]
Great news, thanks!
