### ISSUE TITLE
Connection Directly to Zookeeper.Hosts

### ISSUE THREAD

**Issue by whoschcekingin** [edenhill/librdkafka#1079]
Description
===========
Not an issue but needed help. Pretty new to librdkafka but I was able to use it in our application and while connecting to the Kafka Brokers without issues. But there is a server on my side which doesn't expose the broker ports. Coming from Python and PyKafka in those we were able to connect to the Kafka cluster by providing Zookeeper address and ports. 

ex : client = KafkaClient(zookeeper_hosts="<Zookeeper Hosts>")

I was following the rdkafka_example.cpp provided but couldn't figure out a way to do the same using librdkafka also - Connecting to Zookeeper Hosts directly.

Kafka Version : 0.8
librdrdkafka version : v0.9.3
Operating System: Linux

How to reproduce
================
None.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
 - [x] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [x] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Connecting via ZooKeeper is a legacy from older versions of Kafka and is actually an indirect route, ZK is used to look up the broker hostnames which are then connected to.
Nowadays you connect directly to one of the brokers and bootstrap the full broker list from there, so ZK should no longer be used from clients and I wouldn't be surprised if ZK is either removed or at least shielded off from clients in future Kafka versions.
