### ISSUE TITLE
Local: Communication failure with broker

### ISSUE THREAD

**Issue by zdftju** [edenhill/librdkafka#1080]
Local: Communication failure with broker
Local: Communication failure with broker
Local: Communication failure with broker
Local: Communication failure with broker
Local: Communication failure with broker

Apache Kafka version: 0.8.2
librdkafka client configuration:
"metadata.broker.list":"node1:9090,node1:9091,node1:9092"
"broker.version.fallback":"0.8.2"
 using the cpp API

**Comment by edenhill** [comment]
What API is returning that error code?
Is there anything in the broker logs?

**Comment by zdftju** [comment]
I first use the cpp dynamic libraries compiled  by VS2013  , it works well , but while  use the same api with the dynamic libraries compiled  by VS2010  , the error happened. However , it just return the error code after consuming the last message , it still can consume message regularly.

**Comment by edenhill** [comment]
What exact librdkafka API are you using that returns that error code?
