### ISSUE TITLE
[Question] Producer, how to set a hash partition not a specified one?

### ISSUE THREAD

**Issue by leslieyuan** [edenhill/librdkafka#1082]
Description
===========
I see the api, all **RdKafka::Producer** produce() function has a `partition_num` argument.
And i also see a topic can set a partitioner_cb,  is that mean when i set it to a topic, then i produce to the topic, it will ignore the partition number i set? I wonder if i am right.

Thx.

**Comment by edenhill** [comment]
If you specify PARTITION_UA (unassigned) as partition to the produce() call then librdkafka will use the configured partitioner to decide which partition the message should be sent to, typically using the message key.
The default partitioner is using consistent random partitioning as described in rdkafka.h, search for consistent_random

**Comment by leslieyuan** [comment]
Thanks for reply !
Now i know:

1.  Set `PARTITION_UA` , which partitioner to send to will decided by the key.   
2.  Set a real partition number, producer just use it.

**Comment by edenhill** [comment]
Yup!

Den 1 mar 2017 10:25 skrev "leslieyuan" <notifications@github.com>:
