### ISSUE TITLE
the result may be  MB/s , not Mb/s

### ISSUE THREAD

**Issue by jingshiwenlibi** [edenhill/librdkafka#1084]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
???
Can you give some context?

**Comment by jingshiwenlibi** [comment]
I think b means bit and B means byte.So in the log ,I think B is accurate.

**Comment by edenhill** [comment]
which log from which program are you referring to?
