### ISSUE TITLE
cannot specify ip´s via bootstrap.servers (confluent_kafka/python)

### ISSUE THREAD

**Issue by schlitzered** [edenhill/librdkafka#1085]
Description
===========
i am trying to connect to a kafka server using its ip address, but it seems that it is always trying to connect to 127.0.0.1/localhost

How to reproduce
================
```
some_data_source = ['blarg1', 'blarg2', 'blarg3']
p = confluent_kafka.Producer({'bootstrap.servers': '192.168.33.14,mybroker,mybroker2'})
for data in some_data_source:
    p.produce('mytopic', data.encode('utf-8'))
p.flush()
```

output:
```
%3|1488488915.919|FAIL|rdkafka#producer-1| localhost:9092/0: Connect to ipv4#127.0.0.1:9092 failed: Connection refused
%3|1488488915.919|ERROR|rdkafka#producer-1| localhost:9092/0: Connect to ipv4#127.0.0.1:9092 failed: Connection refused
%3|1488488916.755|FAIL|rdkafka#producer-1| mybroker2:9092/bootstrap: Failed to resolve 'mybroker2:9092': Name or service not known
%3|1488488916.755|ERROR|rdkafka#producer-1| mybroker2:9092/bootstrap: Failed to resolve 'mybroker2:9092': Name or service not known
%3|1488488916.755|FAIL|rdkafka#producer-1| mybroker:9092/bootstrap: Failed to resolve 'mybroker:9092': Name or service not known
%3|1488488916.755|ERROR|rdkafka#producer-1| mybroker:9092/bootstrap: Failed to resolve 'mybroker:9092': Name or service not known
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.1-1
 - [x] Apache Kafka version: 0.10.1.1
 - [x] librdkafka client configuration:{'bootstrap.servers': '192.168.33.14,mybroker,mybroker2'}
 - [x] Operating system: ubuntu 16.10
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Your broker (with broker id 0) is advertising itself as localhost.
Look at the advertised.listeners broker configuration property.
