### ISSUE TITLE
checking for libsasl failed

### ISSUE THREAD

**Issue by wolvever** [edenhill/librdkafka#1090]
Description
===========
When doing `./configure, get the following response even if sasl-lib is installed: 

```
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... failed (disable)
checking for libsasl (by pkg-config)... failed
checking for libsasl (by compile)... failed (disable)
```

It seems librdkafka is looking for sasl lib files end with 'so.2', but installed files are end with 'so.3'

Environment
```
cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)

uname -r
3.10.0-514.6.1.el7.x86_64
```

How to reproduce
================
```
yum install -y epel-release
yum install -y openssl-devel zlib zlib-devel lz4 lz4-devel cyrus-sasl-lib
wget https://github.com/edenhill/librdkafka/archive/v0.9.4.tar.gz
tar zxf v0.9.4.tar.gz && cd librdkafka-0.9.4
./configure
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.4
 - [x] Apache Kafka version: not related
 - [x] librdkafka client configuration: not related
 - [x] Operating system: CentOS 7
 - [x] Using the legacy Consumer: not related
 - [x] Using the high-level KafkaConsumer: not related
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I think you need to install the -devel package of cyrus-sasl-lib/libsasl-devel

**Comment by wolvever** [comment]
It works, thank you :)

**Comment by edenhill** [comment]
Great!
