### ISSUE TITLE
Out-of-order with retries>0 is possible despite max.inflight=1

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#1092]
The ordering guarantee that is assumed when max.inflight=1 is currently broken:

The retry buffers may be placed after other message buffers, which breaks the strict ordering guarantee.

The fix involves implementing a time-based transmit queue that supports per-buffer retry.backoff.ms.

There are also some corner cases where the partition leader changes during the retry time.

This fix should start with designing test cases.

**NOTE**: This only affects ordering on retries (due to intermittent failures). Ordering will be maintained (regardless of max.inflight) when there are no errors.

**Comment by grantr** [comment]
How does the recent release of Kafka 0.11 with [KIP-98](https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging) affect this issue? Will librdkafka support idempotent producer mode?

**Comment by edenhill** [comment]
@grantr librdkafka implements the new EOS message format of KIP-98, but not the EOS functionality itself (transactions).
It is on the roadmap.

**Comment by edenhill** [comment]
EOS support is tracked in #1308

**Comment by edenhill** [comment]
This is now fixed on master
