### ISSUE TITLE
Callback problem

### ISSUE THREAD

**Issue by keshriavi** [edenhill/librdkafka#1100]
Description
===========

is it compulsory to poll for 1000 msec for outq_len. As i am trying to do performance test of my program but it poll for 1000msec each time. How can i remove this poll? i am configuring broker ana topic as default configuration.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [x] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Can you show me your producer loop code?

**Comment by keshriavi** [comment]
while (producer->outq_len() > 0) {
            cerr << "Waiting for " << producer->outq_len() << endl;
            producer->poll(1000);
        }

**Comment by edenhill** [comment]
That loop will wait for all outstanding messages to be produced or failed (you can use flush() which does the same thing).

It is not clear to me what you are trying to achieve or what your actual question is?

**Comment by keshriavi** [comment]
so it is necessary to use this loop.. as i am removing this loop then no messages are published?

**Comment by edenhill** [comment]
the produce() method is asynchronous, it will only enqueue the message on an internal queue for later transmission to the broker.
So to make sure all enqueued messages are actually produced to the broker you will need to wait for the outq_len to reach zero, or simply use flush() that abstracts this for you.

**Comment by keshriavi** [comment]
is there any way so that we don't need to wait?

**Comment by edenhill** [comment]
If you want to be sure the messages are delivered you need to wait.
You can cut down on the wait time by minimizing queue.buffering.max.ms
