### ISSUE TITLE
why consumer offset change to -1001? thank you

### ISSUE THREAD

**Issue by salmanchan** [edenhill/librdkafka#1102]
Description
===========
i hava a program to monitor consumer offset，and output log
look ，topic "M_USAGE" long times have no message,  consumer commited offset from 27196925 change to -1001 suddenly

> [2017-03-08 09:41:32][0][TRKafka.cpp:645][GetWaterLineOffset]: Topic "M_USAGE" partition 0 offset 27196925
> [2017-03-08 09:51:33][0][TRKafka.cpp:645][GetWaterLineOffset]: Topic "M_USAGE" partition 0 offset 27196925
> [2017-03-08 09:51:35][0][TRKafka.cpp:645][GetWaterLineOffset]: Topic "M_USAGE" partition 0 offset **27196925**
> [2017-03-08 10:01:36][0][TRKafka.cpp:645][GetWaterLineOffset]: Topic "M_USAGE" partition 0 offset **-1001**
> [2017-03-08 10:01:38][0][TRKafka.cpp:645][GetWaterLineOffset]: Topic "M_USAGE" partition 0 offset -1001

then,  i send some message to the topic, the offset seems to be restored, or restored from largest offset

> [2017-03-08 11:09:20][0][TRKafka.cpp:645][GetWaterLineOffset]: Topic "M_USAGE" partition 0 offset -1001
> [2017-03-08 11:09:23][0][TRKafka.cpp:645][GetWaterLineOffset]: Topic "M_USAGE" partition 0 offset 27198925
> [2017-03-08 11:09:26][0][TRKafka.cpp:645][GetWaterLineOffset]: Topic "M_USAGE" partition 0 offset 27198925

 may be  the reason is  kafka server clear log files in this time period?

> kafka1#[/data/data03/app/kafka/kafka_2.11-0.9.0.1/logs] cat server.log.2017-03-08-10
> [2017-03-08 10:00:08,842] INFO [Group Metadata Manager on Broker 1]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
> [2017-03-08 10:10:08,842] INFO [Group Metadata Manager on Broker 1]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
> [2017-03-08 10:15:53,745] INFO Rolled new log segment for '__consumer_offsets-31' in 1 ms. (kafka.log.Log)
> [2017-03-08 10:20:08,842] INFO [Group Metadata Manager on Broker 1]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
> [2017-03-08 10:30:08,842] INFO [Group Metadata Manager on Broker 1]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
> [2017-03-08 10:40:08,843] INFO [Group Metadata Manager on Broker 1]: Removed 1 expired offsets in 1 milliseconds. (kafka.coordinator.GroupMetadataManager)
> [2017-03-08 10:50:08,842] INFO [Group Metadata Manager on Broker 1]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.2
 - [x] Apache Kafka version: 0.9.0.1
 - [x] librdkafka client configuration: enable.auto.commit=true
 - [x] Operating system:Linux
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
>  Apache Kafka version: 3.5.1

I'm not sure what version that is?  Kafka is currentl on 0.10.2.0

> [2017-03-08 10:01:38][0][TRKafka.cpp:645][GetWaterLineOffset]: Topic "M_USAGE" partition 0 offset -1001

What is this log based on, what API are you getting the information from?

**Comment by salmanchan** [comment]
I'm sorry.  Apache Kafka version is 0.9.0

I use the following code to get offset, and loop the code to monitor the offset
Usually, it works correctly and gets corrent offset, but sometimes the offset is changed to -1001

```
    err = rd_kafka_committed(m_pKfk, m_pKfkTopicList, 5000);
    if (err) {
        __DEBUG_LOG1_(0, "%% Failed to fetch offsets: %s\n",
            rd_kafka_err2str(err));
        iRet = RET_ERR;
        lLow = -1;
        lHigh = -1;
        return iRet;
    }

    for (int i = 0; i < m_pKfkTopicList->cnt; i++) {
        rd_kafka_topic_partition_t *p = &m_pKfkTopicList->elems[i];
        if (p->err) {
            __DEBUG_LOG1_(0, "error %s", rd_kafka_err2str(p->err));
        } else {
            __DEBUG_LOG3_(0, "Topic \"%s\" partition %d offset %ld",
                p->topic, p->partition, p->offset);
            if (p->partition == iPartition) {
                lCur = p->offset;
                if (lCur == -1001) {
                    lCur = -1;
                }
                break;
            }
        }
    }
```

**Comment by edenhill** [comment]
Thank you.

It seems the __consumer_offsets topic was rolled over due to retention policy, thus loosing the committed offsets.
Search for `offsets.retention.minutes` here http://kafka.apache.org/documentation.html

**Comment by salmanchan** [comment]
Thanks you!
