### ISSUE TITLE
Default Configuration

### ISSUE THREAD

**Issue by keshriavi** [edenhill/librdkafka#1103]
Description
===========

How can i know the default configuration details of topic? As i am trying to set "request.required.acks" to 0 but how can i be sure?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
[CONFIGURATION.md](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) lists the default values.

You can also use conf_dump() to dump all config values, or conf_get() to retrieve a single one.

**Comment by keshriavi** [comment]
thanks
