### ISSUE TITLE
Issue with avro data serialisation using librdkafka library

### ISSUE THREAD

**Issue by kanchanagarwal3** [edenhill/librdkafka#1107]
Unable to produce avro data using librdkafka library to apache kafka consumer console...getting empty strings on consmer consule..is it because of schemaID set to 0001 in hex code. Though in cosumer side..thy are expcted to delete the schemaID..is 0 in hex code acts as null terminator for kafka producer???

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka is completely payload agnostic, it will pass the data exactly as-is, byte-for-byte.

If you are treating the payload as a C string (null terminated) then a 0x00 value would cut that string short.
Make sure to use the binary string handling, such as memcpy, rather than strcpy.
