### ISSUE TITLE
Confirm that all msgs are sent to kafka consumed

### ISSUE THREAD

**Issue by kanchanagarwal3** [edenhill/librdkafka#1108]
How can i confirm all the avro encoded msgs are sent to kafka consumer in asynchronous system using librdkafka producer

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Use the delivery report callback mechanism (rd_kafka_conf_set_dr_msg_cb()) to get per-message delivery results.

**Comment by kanchanagarwal3** [comment]
hi,thenks for the reply...if i use rd_kafka_poll is it not correct?

**Comment by kanchanagarwal3** [comment]
Actually the issue ,If i am sending 100 events from kafka producer,the team at kafka consumer side is receiving less events
please suggest

**Comment by edenhill** [comment]
delivery report callbacks are triggered by calling poll() or flush()

**Comment by kanchanagarwal3** [comment]
so,i am already using rd_kafka_poll() but still we can see there is some loss of data..
Infact at producer side ,we have kept a counter whichh increments as soon as it pass the if condition for kafka_procude,we cans ee all msgs are sent but still at consumer side (who are apache kafka) confirmed that there is loss of data..
Please suggest
