### ISSUE TITLE
assert fails on topics with many partitions

### ISSUE THREAD

**Issue by tadasv** [edenhill/librdkafka#111]
I have a topic with 512 partitions. I was trying to test the example consumer code and it keeps failing at rdkafka_broker.c:190

assert(rkbuf->rkbuf_iovcnt <= IOV_MAX);

On my linux machine IOV_MAX is set to 1024 but rkbuf_iovcnt gets as high as 1027 when calling rd_kafka_broker_fetch_toppars.

I was able to go around this problem by recompiling librdkafka with -DNDEBUG or -DIOV_MAX=2048. However, this does not sound like the right solution.

**Comment by edenhill** [comment]
Fixed on oct15 branch by the round-robin fetcher
