### ISSUE TITLE
See error message when using SSL

### ISSUE THREAD

**Issue by saheemg** [edenhill/librdkafka#1111]
Description
===========
My event callback is receiving an error event and when I use RdKafka::err2str on the  event.err() value, I get the following string (I scrubbed the hostname)

Local: Broker transport failure: ssl://--------:9093/bootstrap: Receive failed: No error

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ x] librdkafka version (release number or git tag): 0.94
 - [x ] Apache Kafka version: 0.10.0.1
 - [ ] librdkafka client configuration:
 - [x ] Operating system:  3.10.0-327.10.1.el7.x86_64
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This means the remote peer (the broker) closed the connection (the error message is fixed on master).

Check the broker logs for hints, possibly enabling JAAS debugging.
