### ISSUE TITLE
Configuration.md does not contain examples

### ISSUE THREAD

**Issue by petriceko** [edenhill/librdkafka#1113]
Hi,
please add examples to Configuration.md. Specifically format of configuration "metadata.broker.list" is not clear.

**Comment by edenhill** [comment]
Will provide some more information for that property.

The format is a CSV (comma-separated value) list of host or host:port

**Comment by petriceko** [comment]
Great, thanks for explanation. I think, it could be very usable to add this explanation to Configuration.md for mentioned property and maybe also for all others.

**Comment by edenhill** [comment]
That makes sense.
We're looking into writing a series of blog posts on common usage of librdkafka (and librdkafka-based clients) to provide some proper examples.
