### ISSUE TITLE
question: which debug flags to determine why a consumer is missing messages

### ISSUE THREAD

**Issue by bjustin-ibm** [edenhill/librdkafka#1114]
Eventually I'll fill out a proper bug report, but the short of it is that I have just confirmed that my confluent-kafka-python consumer is missing messages that are definitely being properly produced (as shown by using a different client to subscribed to the same topic).

For now, what debug settings would be best to help determine what might be going on?

Thanks!

**Comment by edenhill** [comment]
That doesn't sound good.

From an implementation view point it shouldn't miss messages during normal operations, but during a rebalance a lot of stuff is going on so I suggest enabling debug=cgrp,topic  (and also ,fetch if you have enough disk space for logs..) to track how the offset-to-fetch progresses through rebalances and other events.

**Comment by bjustin-ibm** [comment]
Thanks a bunch! 

I'm not yet convinced (yet) there is a bug in librdkafka. In my scenario the consumer that is missing messages is newly created and subscribed to the topic (seconds before the message is produced), while the second consumer that catches the message is long-running. Best case scenario is that there is a timing issue whereby the "latest" offset is set after the message is produced.

Either way, I'll let you know what I find out 😉

**Comment by bjustin-ibm** [comment]
@edenhill I believe my timing theory is correct, but I would like your help to verify:

```
%7|1489521449.882|OFFSET|rdkafka#consumer-34| [thrd:main]: test [0]: offset reset (at offset INVALID) to END: no previously committed offset available: Local: No offset stored
%7|1489521449.882|OFFREQ|rdkafka#consumer-34| [thrd:main]: sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.net:9093/4: Partition test [0]: querying for logical offset END (opv 2)
%7|1489521449.882|OFFSET|rdkafka#consumer-34| [thrd:main]: sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.net:9093/4: OffsetRequest (v0, opv 0) for 1 topic(s) and 1 partition(s)
%7|1489521449.882|PARTSTATE|rdkafka#consumer-34| [thrd:main]: Partition test [0] changed fetch state offset-query -> offset-wait
%7|1489521449.882|CGRPOP|rdkafka#consumer-34| [thrd:main]: Group "binaryKeyTrigger-1489521441725" received op PARTITION_JOIN in state up (join state started, v5) for test [0]
%7|1489521449.882|PARTADD|rdkafka#consumer-34| [thrd:main]: Group "binaryKeyTrigger-1489521441725": add test [0]
%7|1489521449.963|OFFSET|rdkafka#consumer-34| [thrd:main]: sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.net:9093/4: Offset reply for topic test [0] (v2 vs v2)
%7|1489521449.963|OFFSET|rdkafka#consumer-34| [thrd:main]: Offset END request for test [0] returned offset 1203 (1203)
%7|1489521449.963|PARTSTATE|rdkafka#consumer-34| [thrd:main]: Partition test [0] changed fetch state offset-wait -> active
%7|1489521450.963|FETCHDEC|rdkafka#consumer-34| [thrd:sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.]: Topic test [0]: fetch decide: updating to version 2 (was 0) at offset 1203 (was 0)
%7|1489521450.963|FETCH|rdkafka#consumer-34| [thrd:sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.net:9093/4: Topic test [0] in state active at offset 1203 (0/100000 msgs, 0/1000000 kb queued, opv 2) is fetchable:
%7|1489521450.963|FETCHADD|rdkafka#consumer-34| [thrd:sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.net:9093/4: Added test [0] to fetch list (1 entries, opv 2)
%7|1489521450.964|FETCH|rdkafka#consumer-34| [thrd:sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.net:9093/4: Fetch topic test [0] at offset 1203 (v2)
%7|1489521450.964|FETCH|rdkafka#consumer-34| [thrd:sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.net:9093/4: Fetch 1/1/1 toppar(s)
%7|1489521451.651|FETCH|rdkafka#consumer-34| [thrd:sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.net:9093/4: Fetch topic test [0] at offset 1203 (v2)
```

To my eyeballs, this is the exact moment when the consumer first figures out that the "latest" offset is actually `1203` and that it will only be aware of messages with offset `1203` and later (this topic only has one partition). Is that correct?

If so, then this occurs after the message was produced. But what concerns me is that the latest offset isn't determined until well after the consumer successfully polls (using confluent-kafka-python's `Consumer.poll()`). I was making the assumption that `poll()` would only successfully complete after the latest offset was determined and therefore, the consumer was completely ready to consumer any new messages. Is that assumption incorrect?

**Comment by edenhill** [comment]
When starting a new consumer it might take some time for it to get its new assignment - the rebalancing time - which is up to session.timeout.ms depending on the current state of the group.

You will need to call poll() at regular intervals to receive and apply your new assignment following the (initial) rebalance. Consumtion will only start when rebalancing + assignment is complete, and even if you dont specify an on_assign callback you still need to call poll() for this to be taken care of.

**Comment by bjustin-ibm** [comment]
Awesome! Thanks for getting back to me.
