### ISSUE TITLE
Memory leak in rdkafka_example.c

### ISSUE THREAD

**Issue by mcandre** [edenhill/librdkafka#1115]
Minor, but https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.c never frees the conf object with `rd_kafka_conf_destroy()`.

This might not be important for a one-off process that quickly ends, but longer term applications will definitely want to seal those leaks, and the example code should guide how to correctly do this.

**Comment by edenhill** [comment]
In the common case where rd_kafka_new() succeeds it takes ownership of the conf object and frees it internally (as a questionable convenience to the caller).

Regarding the error cases in the example code: See comments on the PR.

I do appreciate you looking into this!
