### ISSUE TITLE
rdkafkacpp_int.h:450]: (error) Mismatching allocation and deallocation: tmpValue

### ISSUE THREAD

**Issue by dcb314** [edenhill/librdkafka#1118]
Description
===========

$ fgrep tmpValue ../BUILD/librdkafka-0.9.4/src-cpp/rdkafkacpp_int.h
      char *tmpValue = NULL;
	  tmpValue = new char[size];
				       tmpValue, &size)) != RD_KAFKA_CONF_OK)
	  tmpValue = new char[size];
					     tmpValue, &size)) != RD_KAFKA_CONF_OK)
      if (tmpValue != NULL) {
	  value.assign(tmpValue);
	  delete tmpValue;
$ 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks for reporting this, will fix.
