### ISSUE TITLE
unable to set config property in librdkafka

### ISSUE THREAD

**Issue by kanchanagarwal3** [edenhill/librdkafka#1120]
unable to set queue.buffering.max.ms property in librdkafka

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You need to provide more information:
 * what value are you trying to set?
 * what error do you get back?
 * code snippet

**Comment by kanchanagarwal3** [comment]
code snippet & value
KafkaConfigOption       queue.buffer.max.ms     1000
Error
Could not set kafka config queue.buffer.max.ms to 1000

**Comment by edenhill** [comment]
The config property name is incorrect. See here: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by kanchanagarwal3** [comment]
yea thanks you were right now it has been set.
Could you plesae tell me if i want to send continuous data of say 10k/s to Kafka Producer which proeprty i need to set.
actually it is taking just 250 data...I want to increase the count of messages it is processing.
Though i tried with batch.num.messages even but no help
