### ISSUE TITLE
Question: which message does a replacement consumer pick up from?

### ISSUE THREAD

**Issue by alamaison** [edenhill/librdkafka#1122]
In the Wiki it says

> `auto.commit.enable` - If true (default), periodically commit offset of the last message handed to the application. This commited offset will be used when the process restarts to pick up where it left off.

My question is, if a consumer fails partway through processing the message and the message offset has already been committed, does the replacement consumer get given the same message that the previous one was part-way though processing?  Or does it get the next one and, therefore, miss part of the processing for the previous message?

I'm using librdkafka via Python, if it's relevant.

**Comment by edenhill** [comment]
With auto.commit.enable=true the offset is stored for future auto commit just PRIOR to handing the message to the application.
This means that if your processing time is long and the consumer eventually crashes, it is possible for that message's offset to have been committed, and the next consumer will start off with the next message following this one - in other words, that message is lost from a processing perspective.

The alternative is to disable auto commits and manually commit asynchronously after processing messages (preferably no more often than once per second since offset commits can be somewhat slow). This way, if the consumer crashes while processing a message, the next consumer will pick up the same message. Depending on how often you commit this may also mean that the message will be processed multiple times.

**Comment by alamaison** [comment]
Thanks.  That's really helpful.

It might be worth updating [the docs](http://docs.confluent.io/3.0.0/clients/consumer.html#synchronous-commits) because they say:

>  Using auto-commit gives you “at least once” delivery: Kafka guarantees that no messages will be missed, but duplicates are possible. 

Which suggests that auto-commit is safe for at-least-once behaviour.  With your explanation in mind, it's now obvious that it guarantees at-least-once delivery, as it says.  But it might be good to call out explicitly that the commit doesn't wait for you processing to succeed and that measures should be taken to handle that yourself if necessary.

**Comment by edenhill** [comment]
Thanks for your input @alamaison , will forward this on

**Comment by alamaison** [comment]
Sorry to revisit this but I'm still struggling to work out how to get at least once message processing.  

If I call commit on a consumer it is documented as committing 'the current partition assignment'.  Does that really mean what is sounds like: that is will commit offsets for messages that haven't been returned by poll yet?  I've trawled the source to find a definitive answer but come up empty.

I can see that auto_commit uses the returned message's offset (+1 why?), and that the same offset is tracked as the last offset returned for that topic:
https://github.com/edenhill/librdkafka/blob/2bd2ff97a58b1b3fd3895d1151c3d057538f8e3a/src/rdkafka_op.c#L594

But when it comes to committing explicitly, that offset doesn't seem to be used: https://github.com/edenhill/librdkafka/blob/1c044abc59063fab56001d016b44d54374a67b2a/src/rdkafka_cgrp.c#L1916

Of course, I could use the explicit offsets parameter but then I have to track the offset for every partition of every topic myself in the consumer loop rather than just maintaining a counter.  Or I have to commit every message which hurts performance.

Am I missing something?  Processing each message at least once must surely be the default that most people expect from Kafka (and is the case for the Java client), but I seem to be jumping through hoops to make it happen.

**Comment by edenhill** [comment]
Committing the current partition assignment means committing the last locally stored offset for each partition in the current assignment.
The locally stored offset for a partition is the offset of the last message handed to the application + 1, and this offset is stored just prior to handing the message to the application.
This means that if your application crashes while processing a message, and auto commit has been unfortunate to run inbetween the time the message offset was stored prior to handing you the message and the time your application crashes, then on restart the consumer will start with the next message.
The way around that is to set `enable.auto.offset.store=false` and perform an explicit store (using rd_kafka_offset_store()) **after**  processing your message. You can think of store as a light-weight in-memory commit, it stores the offset to commit, and works both with auto and manual commits (as long as you dont specify en explicit offset to commit).

Re +1: we commit the offset to start consuming at if we're interrupted, which is not the last message, but the next message, thus last message +1.

**Comment by alamaison** [comment]
Thanks for your quick response. 

So just to confirm what I understood:

If `auto.commit.enable` is off, the normal commit behaviour (NULL offsets) does what I was hoping. It commits the offset+1 of the last message in each toppar that was returned by a call to poll. As long as I call commit after processing the message, each message will be processed to completion at least once.

Additionally, if I wanted a way to get at least once processing that also worked with auto-commit on or i didn't want the 'burden' of scheduling commits using the `message_count %`-method, i could use enable.auto.offset.store=false and call offset_store after every message (how does this ever get committed if auto-commit is off?). But i don't have to, i can just disable auto-commit and use regular calls to commit?

If that all is the case, i really recommend adding the first two sentences of your answer to the docs for commit.

**Comment by edenhill** [comment]
You are absolutely right in your assumptions.

Re offset_store without auto commit: it wont get automatically committed, but calling commit(NULL) will commit it.
