### ISSUE TITLE
continuous data flow to rdkafka producer

### ISSUE THREAD

**Issue by kanchanagarwal3** [edenhill/librdkafka#1124]
Can i send contnuous data to rdkafka say 10k/sec ..I my case it is processing only max 288 data.
tried to set message.timeout.ms property but its not set ..
How can i set it and will it solve the problem ?

Code snippet
KafKaConfigOption    message.timeout.ms     300000

 librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please fill out the questions in the issue template.
Also provide a code snippet to show you are producing messages

**Comment by kanchanagarwal3** [comment]
lines where we are actually writing data to kafka_producer:
if( rd_kafka_produce(
		kafka_topic,
		partition,
		RD_KAFKA_MSG_F_COPY,
		msg.msg, 
		strlen(msg.msg),
		NULL,
		0,
		NULL
		) != 0 ) {
			printf( "Could not send message to kafka\n" );
			}

**Comment by kanchanagarwal3** [comment]
Librdkakfa 0.9.3 in RHOS.

**Comment by edenhill** [comment]
have you registered a dr_msg_cb? How often are you calling rd_kafka_poll() to serve the dr_msg_cb?

**Comment by kanchanagarwal3** [comment]
i am calling rd_kafka_poll() at regular interval
if( rd_kafka_produce(
		kafka_topic,
		partition,
		RD_KAFKA_MSG_F_COPY,
		msg.msg,
		strlen( msg.msg ),
		NULL,
		0,
		NULL
		) != 0 ) {
		printf( "Could not send message to kafka\n" );
		}
		else {
		cnt_processed_msg++;
        		rd_kafka_poll( kafka_conn, 10 );
		}
		cnt_received_msg++;
		}
	}
    // Wait for all messages to be delivered
    while( rd_kafka_outq_len( kafka_conn ) > 0 ) {
        rd_kafka_poll( kafka_conn, 10 );
    }

**Comment by kanchanagarwal3** [comment]
but i haven;t registered dr_msg_cb() because i dnt know th eprocedure to register it rather i have set debug=msg in config file

**Comment by edenhill** [comment]
When produce() fails you it is typically because the buffer in full, in this case you should call rd_kafka_poll() with a higher timeout and then retry the produce call.

When produce() succeeds you should call poll with a timeout of 0, otherwise you might stall for 10ms (10000 msgs/s > 1000/10ms) for each message (worst case).

**Comment by kanchanagarwal3** [comment]
Hi thanks,

I decreased the poll time to 0.01 but still i dnt see full 10k events to be processes though the number had increased to 970..

**Comment by kanchanagarwal3** [comment]
i tried pushing 10k events..it process 7700 events..why it is random selection of count..why it isnot considering all data??
do i need to set queue.buffering.max.ms property ??

**Comment by edenhill** [comment]
You dont need to change any configs, you need to call rd_kafka_poll(rk, 0) after a succesfull produce.
