### ISSUE TITLE
rd_kafka_message_destroy always necessary?

### ISSUE THREAD

**Issue by davidbirdsong** [edenhill/librdkafka#1126]
Description
===========

Quick question: as a producer, I'm not the creator of a `rd_kafka_message_t`. Am I still expected to call  `rd_kafka_message_destroy` inside of a `rd_kafka_conf_set_dr_msg_cb`?

If it's pertinent to my question: my message flag is set to `0`, my code owns the payload and free's it in `rd_kafka_conf_set_dr_msg_cb`.

...the reason for my question is to help me start narrowing down a steady memory leak.

How to reproduce
================
Clarification only.

Checklist
=========
Please provide the following information:

 - [v0.9.4 ] librdkafka version (release number or git tag):
 - [confluent-oss ] Apache Kafka version: 
 - [] librdkafka client configuration:
 - [ ubuntu 14.04] Operating system:
 - [no ] Using the legacy Consumer
 - [no ] Using the high-level KafkaConsumer
 - [ none] Provide logs (with `debug=..` as necessary) from librdkafka
 - [none ] Provide broker log excerpts
 - [ no] Critical issue

**Comment by edenhill** [comment]
An application must not call message_destroy() on the message given to the dr_msg_cb(), it will be destroyed automatically when the callback returns.

But unless you specify _F_COPY or _F_FREE you will need to free the message payload (if you allocated it).

**Comment by davidbirdsong** [comment]
Thank you. This answers my question.
