### ISSUE TITLE
Can librdkafka support mutiple rd_kafka_t handles in different threads?

### ISSUE THREAD

**Issue by CasperLiu** [edenhill/librdkafka#1127]
Description
===========
Nice to meet you, Magnus!

We are using librdkafka (git Tag 0.9.4) for our development. We use librdkafka client to send messages to a Kafka Cluster which has three Kafka brokers. 
We would like to have a high throughput to Kafka brokers for the network between our product process and Kafka clusters may be not good sometimes.  We have two designs, please give your comments for the two designs.

The first design is that our single process (which will use librdkafka to send messages) will have a number of worker threads, each worker thread will create a rd_kafka_t handle, a rd_kafka_conf_t object, dedicated for this thread and non-shared with other threads, and send messages to Kafka Cluster. Delivery report CB will be used for each thread to report the message delivery status.
PS: all the worker threads can send messages to the same topic list in Kafka Cluster.
Our questions are:  
Will librdkafka support mutilple rd_kafka_t handles in multiple threads of a single process? 
In this case: how would Socket connections be set up(for example, we have two handles: Handle1 in Worker Thread 1, Handle2 in Worker Thread 2, and there will be three Brokers. Then there will be six TCP connections of Handle1-Broker1, Handle1-Broker2, Handle1-Broker3, and  Handle2-Broker1, Handle2-Broker2, Handle2-Broker3, right? Or there will be only three connections whatever the handle number?)
Will this design increase the throughput actually?
Is there any potentional problem for this kind of design? 

The second design is that we will have only one rd_kafka_t handle,  only one rd_kafka_conf_t object - in short, this is the typical use case as in rdkafka_example.c(demo in librdkafka source code). For this design, do you have any suggestions to get a better throughput? 
PS: I already read below nice guide for decrease latency.
https://github.com/edenhill/librdkafka/wiki/How-to-decrease-message-latency

Thanks a lot in advance!

How to reproduce
================
This is a consulation.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
git tag: 0.9.4
 - [ ] Apache Kafka version: 
kafka_2.11-0.10.1.1,
 - [ ] librdkafka client configuration:
default producer configuration
 - [ ] Operating system:
CentOS 7
 - [ ] Using the legacy Consumer
Only producer functionality is used.
 - [ ] Using the high-level KafkaConsumer
Only producer functionality is used.
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
No logs so far.
 - [ ] Provide broker log excerpts
No.
 - [ ] Critical issue
Yes.

**Comment by edenhill** [comment]
Hi,

can you specify what kind of throughput numbers (messages / second and average message size) you are expecting?

I would start off with a single rd_kafka_t instance, which can be used from any number of application threads, There is already one internal thread per broker so I don't think there is much to gain from running multiple rd_kafka_t instances in the same process, unless their configuration needs to differ.

Each rd_kafka_t instance will have one thread and one socker per broker in the cluster.

**Comment by edenhill** [comment]
That's 600KB/s which is microscopical, you should be fine :)

**Comment by CasperLiu** [comment]
Magnus,

Thanks for your nice confirmation! :)

One question about topic existence check.
In our use case (we use librdkafka in a producer process to send msg to Kafka cluster), topic(s) should be existent before we start up our producer process. This means we don't want to use librdkafka to create a topic on Kafka cluster.
**Is there any API or a serial of APIs to check if a topic with a certain topic name already exists in Kafka cluster?**
Format is like: rd_kafka_topic_existence_check(const char * topic_name);
 
PS: I have checked below online manual, but didn't find it.
I just found rd_kafka_topic_new, rd_kafka_topic_destroy, rd_kafka_topic_name.
http://docs.confluent.io/2.0.0/clients/librdkafka/index.html

Thanks a lot!

Regards
Casper

**Comment by CasperLiu** [comment]
PS: we have decided to use a single librdkafka handle per your suggestion. :)

**Comment by edenhill** [comment]
If auto.create.topics.enable is set to true on the broker then any (metadata) request for a non-existent topic will create it.

The only way around that is to requesting all topics from the cluster, you can achieve this by calling ?
`rd_kafka_metadata(rk, 1/*all_topics*/, NULL, &metadata, 10*1000);` and then scanning through the provided metadata looking for a matching topic.
