### ISSUE TITLE
some messages are lost while shipping large amount of data in one batch to rdkafka in RHOS

### ISSUE THREAD

**Issue by kanchanagarwal3** [edenhill/librdkafka#1128]
Code snippet:
```
// Deliver message
if( rd_kafka_produce(
				kafka_topic,
				partition,
				RD_KAFKA_MSG_F_COPY,
				msg.msg,
				strlen( msg.msg ),
				NULL,
				0,
				NULL
			) != 0 ) {
				printf( "Could not send message to kafka\n" );
			}
			else {
				cnt_processed_msg++;
        		rd_kafka_poll( kafka_conn, 0 );
			}
			cnt_received_msg++;
		}
	}
    // Wait for all messages to be delivered
    while( rd_kafka_outq_len( kafka_conn ) > 0 ) {
        rd_kafka_poll( kafka_conn, 0 );
    }
```
Say,if 10k events are sent,it receives only 8k or above but not all

It think it loses connection
Please suggest

**Comment by edenhill** [comment]
outq_len() should never reach 0 until all messages have either been sent or failed.

**Comment by kanchanagarwal3** [comment]
sory ..i didnt get your answer

**Comment by edenhill** [comment]
I dont see any problems with your code.

**Comment by edenhill** [comment]
Do note though that messages may fail delivery, to know when this happens you need to register a delivery report callback, see rd_kafka_conf_set_dr_msg_cb().
It will be called exactly once per message to propagate the per-message success or error.
It is called from poll()

**Comment by kanchanagarwal3** [comment]
ok...can u send a useful link where i can see how to set rd_kafka_conf_set_dr_msg_cb().
Can i set it in Config file ?

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_simple_producer.c
