### ISSUE TITLE
How to create different number of partitions for different topics in librdkafka?

### ISSUE THREAD

**Issue by xiaocairush** [edenhill/librdkafka#1129]
Description
===========
For example: create 2 partitions for topic A and create 3 partitions for topic B.
From the [stackoverflow](http://stackoverflow.com/questions/16946778/how-can-we-create-a-topic-in-kafka-from-the-ide-using-api) we can find it's possible to implement the above idea by zkclient:
```
AdminUtils.createTopic(zkUtils, topic, partitions, replication, topicConfig);
```
I have referred to rdkafka_zookeeper_example.c but cannot success to compile it for now. So I tried with rdkafka_example but seems my idea cannot work. 
So I wonder is it possible to implement my idea by librdkafka?

How to reproduce
================
1.  set ```auto.create.topics.enable=true``` and ```num.partitions=1``` for kafka server
2.  run caommand ```./rdkafka_example -P -t test -p 5 -b 127.0.0.1:9092``` and send some message
3. got error message: **Failed to produce to topic test partition 5: Local: Unknown partition**

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is not currently possible, the topic auto creation is a blunt "feature" that uses the broker's default topic configuration to create a requested topic, the client can only set the name of the topic, nothing else.

With KIP-4 support you will be able to create a topic programmaticaly from the client, this is tracked in issue #986
