### ISSUE TITLE
0.9.2 : producer : rd_kafka_outq_len keeps on increasing with 1msg per second when kafka broker is down

### ISSUE THREAD

**Issue by mazharshaikh86** [edenhill/librdkafka#1130]
Description
===========
0.9.2 : producer: rd_kafka_outq_len keeps on increasing with 1msg per second when kafka broker is down

How to reproduce
================
1. stop kafka broker
2. set producer "message.timeout.ms"  to 0(disabled)
3. start producer
4.  Don't produce and msg
5. Keep checking "rd_kafka_outq_len()"

Observation:
================
rd_kafka_outq_len : returns ever increment value

How can i solve this issue ?

Checklist
=========
Please provide the following information:

 - [0.9.2] librdkafka version (release number or git tag):
 - [ kafka_2.11-0.9.0.1] Apache Kafka version: 
 - [message.timeout.ms=0] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Are you calling rd_kafka_poll()?

**Comment by mazharshaikh86** [comment]
KafkaProducerDebugLogger : [rdkafka#producer-1] [7] [CONNECT] [b1.kafka.com:9092/bootstrap: broker in state DOWN connecting]
KafkaProducerDebugLogger : [rdkafka#producer-1] [7] [CONNECT] [b1.kafka.com:9092/bootstrap: Connecting to ipv4#1.1.1.1:9092 (plaintext) with socket 56]
KafkaProducerDebugLogger : [rdkafka#producer-1] [7] [STATE] [b1.kafka.com:9092/bootstrap: Broker changed state DOWN -> CONNECT]
KafkaProducerDebugLogger : [rdkafka#producer-1] [7] [BROADCAST] [Broadcasting state change]
KafkaProducerDebugLogger : [rdkafka#producer-1] [7] [BROKERFAIL] [b1.kafka.com:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection refused)]
KafkaProducerDebugLogger : [rdkafka#producer-1] [3] [FAIL] [b1.kafka.com:9092/bootstrap: Connect to ipv4#1.1.1.1:9092 failed: Connection refused]
KafkaProducerDebugLogger : [rdkafka#producer-1] [7] [STATE] [b1.kafka.com:9092/bootstrap: Broker changed state CONNECT -> DOWN]
KafkaProducerDebugLogger : [rdkafka#producer-1] [7] [BROADCAST] [Broadcasting state change]
KafkaProducerDebugLogger : [rdkafka#producer-1] [7] [BUFQ] [b1.kafka.com:9092/bootstrap: Purging bufq with 0 buffers]
KafkaProducerDebugLogger : [rdkafka#producer-1] [7] [BUFQ] [b1.kafka.com:9092/bootstrap: Updating 0 buffers on connection reset]

**Comment by mazharshaikh86** [comment]
Yes.. I'm calling poll 

rd_kafka_poll(m_rdKafka, 0);

**Comment by edenhill** [comment]
Okay, good.

It could be metadata requests being enqueued.

The metadata code was rewritten for v0.9.4 so I suggest upgrading to v0.9.4 to see if the problem persists

**Comment by mazharshaikh86** [comment]
Thank you Magnus.

I'll upgrade to 0.9.4 as suggested.

Thank you.
