### ISSUE TITLE
unable to understand how callback function works in librdkafka

### ISSUE THREAD

**Issue by kanchanagarwal3** [edenhill/librdkafka#1131]
question:
1.i am not getting any delivery while producing less number of events not even errro msg
2.getting the delivery report while sending large number of events in a single batch
% Message delivered (34 bytes, Partition 1)
% Message delivered (34 bytes, Partition 0)
% Message delivered (35 bytes, Partition 0)
% Message delivered (35 bytes, Partition 0)
......
but again how to take a count of the total message actually deivered is it i need add a counter in callback function 

% Message delivered (34 bytes, Partition 1) is this single line depicts transfer of one message   ?

Code snippet

static void dr_msg_cb (rd_kafka_t *rk,const rd_kafka_message_t *rkmessage, void *opaque) {
        if (rkmessage->err)
                fprintf(stderr, "%% Message delivery failed: %s\n",rd_kafka_err2str(rkmessage->err));
        else
               fprintf(stderr,"%% Message delivered (%zd bytes, " "Partition %"PRId32")\n",
                        rkmessage->len, rkmessage->partition);
        /* The rkmessage is destroyed automatically by librdkafka */
}
// Create kafka handle
    kafka_conf  = rd_kafka_conf_new();
    if( kafka_conf == NULL ) {
        printf( "Could not create kafka configuration\n" );
        return 1;
    }
              
rd_kafka_conf_set_dr_msg_cb(kafka_conf, dr_msg_cb);
    kafka_conn = rd_kafka_new( RD_KAFKA_PRODUCER, kafka_conf, errstr, sizeof(errstr) );

**Comment by edenhill** [comment]
> 1.i am not getting any delivery while producing less number of events not even errro msg
> 2.getting the delivery report while sending large number of events in a single batch

I'm not sure what that means.
What is less number and large number?

**Comment by kanchanagarwal3** [comment]
i mean is i send say just 100 events ..i dnt get any acknowledgement neuther any error is thrown

but again in the next try if i increase the count to say 1k then i get something like this
% Message delivered (34 bytes, Partition 1)
 % Message delivered (34 bytes, Partition 0)
 % Message delivered (35 bytes, Partition 0)
 % Message delivered (35 bytes, Partition 0)
don't know exactly how many times it dsiplays and what it indicates??
Is it like for 1k events i should get 1k time delivery report ??

**Comment by edenhill** [comment]
Yes, you should.

Are you using the simple producer example I linked to?

**Comment by edenhill** [comment]
Either use my rdkafka_simple_producer.c unchanged and reproduce this issue, or provide the full source code of your own program.

**Comment by kanchanagarwal3** [comment]
yes i used the link u provided last day
here is my complete code
[rdkafkaproducer.txt](https://github.com/edenhill/librdkafka/files/857300/rdkafkaproducer.txt)

**Comment by edenhill** [comment]
Does it work with my unchanged example?

Den 21 mar 2017 08:05 skrev "kanchanagarwal3" <notifications@github.com>:

**Comment by kanchanagarwal3** [comment]
I haven't embedded the complete example code in my process because i will incorpoarte many more things it to to see the ouput.
Id it possible to figure out the issue in the code i attached..
Is there a check needed in Consumer  side??

**Comment by edenhill** [comment]
No, I want you to reproduce with the simple producer example with no
changes.
If it works that means there is something wrong with your interaction with
librdkafka and you will need to troubleshoot and compare by your own means.


Den 21 mar 2017 08:55 skrev "kanchanagarwal3" <notifications@github.com>:

**Comment by kanchanagarwal3** [comment]
I understand that if  poll for 1ms [rd_kafka_poll( kafka_conn, 1 )]..
I can see that  I am getting delivery report [Message delivered (34 bytes, Partition 1)] 70 times.
on the other hand,the total data passed to Kafka producer is 100
Could you help in analysing the data loss actually its a major issue and i need to fix it asap

**Comment by kanchanagarwal3** [comment]
It may also happen that at consumer side they are commiting before all the messages arrive.
but again i have a question that why i am not getting any error message for the 30 lost data

**Comment by edenhill** [comment]
Can you reproduce the message loss with the simple producer example (unchanged)?

**Comment by kanchanagarwal3** [comment]
i haven't tried yet with the simple producer example one.

I am trying to fx within my producer code

**Comment by edenhill** [comment]
Start with my working example, then try to find differences between that implementation and yours to find the root of the problem.

**Comment by kanchanagarwal3** [comment]
Hi,
I found three things in your code which was absent in mine:
1. retry option for failed messages - > but in my case it is not going to fail itself..if i take a counter in   produce loop it shows complt 1000 events [though i have added this in mine too]
2. if produce success then u poll for 0 sec i.e allowing continuous non-blocking flow..[i added this in mine]
3.u have used rd_kafka_flush to flush out all the remaining messages and it will wait for 10 secs
i added this..
for once when there was a delay from my side in killing th eprocess..
i got a error that broker has failed

but again aftr doing al this..again if i  count the number of delivery report is printed is < 1000k (approx 800)



2.

**Comment by edenhill** [comment]
try setting message.timeout.ms to a value lower than your flush setting, e.g., 8000ms, and see if you get delivery reports for all messages.

**Comment by kanchanagarwal3** [comment]
unable to set this propery in config file
I tried to set like this in the code..no change i can see in the output but there was no compiler error
rd_kafka_conf_set(kafka_conf,"message.timeout.ms","600",errstr,sizeof(errstr));

**Comment by edenhill** [comment]
It is a topic level property:
```
rd_kafka_topic_conf_t *tconf = rd_kafka_topic_conf_new();
rd_kafka_topic_conf_set(tconf, "message.timeout.ms", "6000", NULL, 0);

rd_kafka_topic_t *rkt = rd_kafka_topic_new("yourtopic", tconf);
```

**Comment by kanchanagarwal3** [comment]
thenks..i made the changes
but this time i got 345 times delivery report (expected 1k times)
in addition I have also set 
KafkaConfigOption       queue.buffering.max.ms  100
and gain no error message
but if i take the count of message for success produce it is 1k
i dnt know then why it is not giving delivery report for 1k

**Comment by edenhill** [comment]
what is your rd_kafka_flush() timeout?

**Comment by kanchanagarwal3** [comment]
rd_kafka_flush(kafka_conn, 10000 /* wait for max 10 seconds */);

**Comment by edenhill** [comment]
Try calling rd_kafka_outq_len() and print the return value, after flush() returns, to see the number of messages still in queues.

**Comment by kanchanagarwal3** [comment]
rd_kafka_topic_conf_set(kafka_topic_conf, "message.timeout.ms", "6000", NULL, 0);
kafka_topic = rd_kafka_topic_new(kafka_conn, p_config->p_topic, kafka_topic_conf );

**Comment by kanchanagarwal3** [comment]
ok

**Comment by kanchanagarwal3** [comment]
fprintf(stderr, "%% Flushing final messages..\n");
        rd_kafka_flush(kafka_conn, 10000 /* wait for max 10 seconds */);
printf("\nNUMBER OF MESSAGES IN QUEUE %d",rd_kafka_outq_len(kafka_conn));

**Comment by kanchanagarwal3** [comment]
no output..not even printf() is working

**Comment by kanchanagarwal3** [comment]
hi,
i just got a confirmation from consumer side that they received 1k events after fixing at their side last night..
we are doing a couple of test more..i will confirm you after  that if it is resolved or not

**Comment by kanchanagarwal3** [comment]
this issue has been fixed..issue was with flume configuration
