### ISSUE TITLE
a phenomenon like "loop consuming"

### ISSUE THREAD

**Issue by lording** [edenhill/librdkafka#1132]
Description
===========
Hi, edenhill
I encountered a phenomenon like "loop consuming" while using rdkafka_consumer_example_cpp produced by rdkafka_consumer_example.cpp.
I add two configuration :
```
  conf->set("fetch.wait.max.ms", "30000", errstr); //30000 or larger , but less than 300000
  tconf->set("auto.offser.reset", "smallest", errstr);
```
after line 390. other configurations are default.

when i consume a topic named "topic_test",which has two partition with 200 msgs in toal.
I run command: ./rdkafka_consumer_example_cpp -g group_test_1 -b xxx.xxx.xxx.xxx:9092 topic_test
After the final msg is consumed, the client 
will block in about 30 seconds and consumes from the first msg in offset 0.
I think there are abnormal situation:
1.client can consume with the same groupid (group_test_1) for many times and consume from the very beginning at offset 0.
2.loop consume from the very beginning at offset 0 after consumed to the last offset in about 30 seconds.

Do I use the client incorrectly? please help me, thanks very much.

How to reproduce
================
broker side :
create a topic name "topic_test", with two partitions.

client side :
produce a certain certain number of msgs, such as 10 msgs, using rdkafka_example_cpp with default configurations.
command is :` ./rdkafka_example_cpp -P -t topic_test -b xxx.xxx.xxx.xxx:9092`

consume msgs :
I run command: `./rdkafka_consumer_example_cpp -g group_test_1 -b xxx.xxx.xxx.xxx:9092 topic_test`

Checklist
=========
Please provide the following information:

 - [0.9.3] librdkafka version (release number or git tag):
 - [0.10.1.0] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [redhat 6u3 X64] Operating system:
 - [ ] Using the legacy Consumer
 - [yes] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka uses the same connection for fetching messages and group control (heartbeats, etc).
If you specify a fetch.wait.max.ms that is close to, or above, the session timeout, then you risk the client falling out of the group due to missing heartbeats if there is an outstanding Fetch request that waits for new messages.

I suggest setting the fetch.wait.max.ms much lower (not more than 1s)

**Comment by lording** [comment]
ok, got it. thank you very much.
