### ISSUE TITLE
How to set "request.required.acks"?

### ISSUE THREAD

**Issue by fieldsplum** [edenhill/librdkafka#1133]
Description
===========

According to comment in Issue #1123 as below

> You are calling
> `rk_res = rd_kafka_topic_conf_set(topic_conf, "request.required.acks", "1", errstr, sizeof(errstr));`
> after rd_kafka_topic_new(), but that function takes ownership (and destroys) topic_conf, so you are practically writing to freed memory.
> 
> Move that topic_conf_set line above the topic_new() call.

If I need to call rd_kafka_topic_conf_set before rd_kafka_topic_conf_new, then I use this new topic_conf, it means "request.required.acks" isn't set to topic_conf.
How should set "request.required.acks" parameter?

By the way, in the circumstance of setting "request.required.acks", rd_kafka_topic_conf_set will call rd_kafka_anyconf_set_prop0,
```
	case _RK_C_BOOL:
	case _RK_C_INT:
	case _RK_C_S2I:
	case _RK_C_S2F:
	{
		int *val = _RK_PTR(int *, conf, prop->offset);

		if (prop->type == _RK_C_S2F) {
			switch (set_mode)
			{
			case _PROP_SET_REPLACE:
				*val = ival;
				break;
			case _PROP_SET_ADD:
				*val |= ival;
				break;
			case _PROP_SET_DEL:
				*val &= ~ival;
				break;
			}
		} else {
			/* Single assignment */
			*val = ival;

		}
		return RD_KAFKA_CONF_OK;
	}
```
I didn't find the place where to destroy topic_conf.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Do this:
 1. First create topic_conf_t object using `rd_kafka_topic_conf_t *tconf = rd_kafka_topic_conf_new();`
 2. Set your configuration property using `rd_kafka_topic_conf_set(tconf, "acks", "all", errstr, sizeof(errstr))` (plus error checking)
 3. Use the configuration object with the new topic object: `rd_kafka_topic_t *rkt = rd_kafka_topic_new("mytopic", tconf);`
 4. The `tconf` object is automatically freed by topic_new.

**Comment by fieldsplum** [comment]
Got it.
Thank you!
