### ISSUE TITLE
Unable to see group ids on the broker when assign is used

### ISSUE THREAD

**Issue by yagnasrinath** [edenhill/librdkafka#1136]
Description
===========
Unable to see the consumer group ids on the broker when assign is used for owning partitions.
Our usecase is using the new consumer to store topic offsets only. All consumers will consume from all partitions of the topic. I am attaching the code below to reproduce the issue. I am not sure if I am using it in an expected way. Please help.

How to reproduce
================
```
#include <ctype.h>
#include <signal.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <syslog.h>
#include <time.h>
#include <sys/time.h>
#include "rdkafka.h"  /* for Kafka driver */

int main (int argc, char **argv) {
	char *brokers = "10.0.0.114:9092";
	rd_kafka_conf_t *conf;
	rd_kafka_topic_conf_t *topic_conf;
	rd_kafka_resp_err_t err;
	char errstr[512];
	/* Kafka configuration */
	conf = rd_kafka_conf_new();
	/* Topic configuration */
	topic_conf = rd_kafka_topic_conf_new();
	if (rd_kafka_conf_set(conf, "group.id",
				"testsri", errstr,
				sizeof(errstr)) != RD_KAFKA_CONF_OK) {
		exit(1);
	}
	/* Disable connection close errors */
	if (rd_kafka_conf_set(conf, "log.connection.close", "false", errstr,
				sizeof(errstr)) != RD_KAFKA_CONF_OK) {
		exit(1);
	}
	/* Consumer groups always use broker based offset storage */
	if (rd_kafka_topic_conf_set(topic_conf, "offset.store.method",
				"broker", errstr,
				sizeof(errstr)) != RD_KAFKA_CONF_OK) {
		exit(1);
	}
	/* Fallback to earliest offset if there are no offsets */
	if (rd_kafka_topic_conf_set(topic_conf, "auto.offset.reset",
				"earliest", errstr,
				sizeof(errstr)) != RD_KAFKA_CONF_OK) {
		exit(1);
	}
	//rd_kafka_conf_set_default_topic_conf(conf, topic_conf);
	rd_kafka_t *rk;
	/* Create Kafka handle */
	if (!(rk = rd_kafka_new(RD_KAFKA_CONSUMER, conf, errstr,
					sizeof(errstr)))) {
		exit(1);
	}
	/* Add brokers */
	if (rd_kafka_brokers_add(rk, brokers) == 0) {
		exit(1);
	}
	/* Redirect rd_kafka_poll() to consumer_poll() */
	rd_kafka_poll_set_consumer(rk);
	rd_kafka_topic_t* topic =
		rd_kafka_topic_new(rk, "device_segment", topic_conf);
	const struct rd_kafka_metadata *metadata;
	/* Fetch metadata */
	err = rd_kafka_metadata(rk, 0, topic, &metadata, 5000);
	if (err != RD_KAFKA_RESP_ERR_NO_ERROR) {
		exit(1);
	}
	rd_kafka_topic_partition_list_t *topic_parts = rd_kafka_topic_partition_list_new(
			metadata->topics[0].partition_cnt);
	int32_t i;
	for (i = 0; i < metadata->topics[0].partition_cnt; ++i) {
		rd_kafka_topic_partition_list_add(topic_parts,
				"device_segment", i);
	}
	if ((err = rd_kafka_assign(rk, topic_parts))) {
		exit(1);
	}
	rd_kafka_metadata_destroy(metadata);
	rd_kafka_message_t * message;
	while(1) {
		message = rd_kafka_consumer_poll(rk, 1000);
		printf("%ld\n",message->offset);
		sleep(1);
	}
}
```

command used to test:
1. bin/kafka-consumer-groups.sh --zookeeper 10.0.0.x:2181 --list
2. bin/kafka-consumer-groups.sh --new-consumer --list --bootstrap-server 10.0.0.x:9092

Either commands dint yield the expected group name.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.1
 - [ ] Apache Kafka version: 0.9.1
 - [ ] librdkafka client configuration: 
 - [ ] Operating system: ubuntu 1404
 - [ ] Using the legacy Consumer no
 - [ ] Using the high-level KafkaConsumer yes
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue yes

**Comment by edenhill** [comment]
The consumer only joins the consumer group when subscribe() is used.
With assign() it sets its own assignment and starts consuming without any correlation with other consumers in the same group, which means that group remains unknown to the broker.


Note: Make sure to call rd_kafka_message_destroy(message);  here:
```
	while(1) {
		message = rd_kafka_consumer_poll(rk, 1000);
		printf("%ld\n",message->offset);
		sleep(1);
```

**Comment by yagnasrinath** [comment]
Thanks @edenhill but, how do I obtain the functionality of storing offsets in the broker or file?

**Comment by yagnasrinath** [comment]
@edenhill is it possible to get such a functionality in any other way? if not this.

**Comment by yagnasrinath** [comment]
Achieved the same with subscribe and one consumer group per consumer
