### ISSUE TITLE
KafkaConsumer is not calling ConsumeCb when it's registered.

### ISSUE THREAD

**Issue by kenxxu67** [edenhill/librdkafka#1137]
Description
===========
Running "rdkafka_consumer_example_cpp,exe -g 2345 -f ccb rtest" without any modification to rdkafka_consumer_example.cpp. No message is printed to the screen. Breakpoint set in consume_cb was not hit when message was consumed.

How to reproduce
================
1. Complile and run "rdkafka_consumer_example_cpp,exe -g 2345 -f ccb rtest"
2. Run "rdkafka_example.exe -P -t rtest -p 0" to produce some messges
3. rdkafka_consumer_example_cpp is not printing any messages produced.

Running "rdkafka_consumer_example_cpp,exe -g 2345 rtest" works fine. In fact the message seems still received as the result of consume call.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by kenxxu67** [comment]
I guess my question is more like what would be the best way to use this high level consumer. Is polling calling consume better than using the callbacks? Also, it looks like callback pass back an extra parameter opaque. I doubt this this is the opaque passed in when the producer calling produce. So where does this opaque come from then? and why consume doesn't return this opaque. Any comments?

**Comment by edenhill** [comment]
The consume callback is probably somewhat faster than the consume()/poll() approach, but for most use-cases that speed increase is irrelevant (the message processing time is what is slow).

The opaque pointer is the handle (rd_kafka_t) opaque as set by rd_kafka_conf_set_opaque()

**Comment by kenxxu67** [comment]
I noticed the cpp files in src-cpp is using "std::string" in the code, instead of "using namespace std" then "string". Is there any benefit doing this way?
The reason I ask is we are using our specialized STL, with a namespace different from std. We don't want to bring in two copies of STL into our application because of using librdkafka. Using std:: all over the place in the code may bring risk for us to consume your future fixes. Otherwise we can just switch a few headers and change the using namespace.
If you don't mind either way, I can make the change and generate a pull request for this.

**Comment by edenhill** [comment]
Re std::, I think it is safer and more clear (and elaborate) with the prefix in place:
http://stackoverflow.com/a/1453605/1821055

**Comment by lyk1905** [comment]
i have the same problem with KafkaConsumer.
when i register my ConsumerCb in conf , it not been called.
so i am asking you what should be considered in this situation,
such as configuration...

**Comment by edenhill** [comment]
@lyk1905 The ConsumeCb is not currently supported by KafkaConsumer (and there is little reason to use it anyway, see previous comments)

**Comment by ronalabraham** [comment]
Could you please tell me why the "consume callback is probably somewhat faster than the consume()/poll() approach"?

**Comment by edenhill** [comment]
The consume callback avoids some API overhead, but except for the most extreme cases it shouldn't matter.
