### ISSUE TITLE
consuming speed limited question

### ISSUE THREAD

**Issue by lording** [edenhill/librdkafka#1138]
Description
===========
Hi, edenhill
I have some doubts about consuming speed. 
I have five machines, Network bandwidth is 1000Mb/s.
On machine A, consumer_1 fetches topic_1 with only one thread, groupid is group_consumer_1.
On machine B, consumer_2 fetches topic_2 with only one thread, groupid is group_consumer_2.
Machine C、D、F combine a kafka cluster.Each topic (topic_1/topic_2)has 1 million msgs already.
Each msg is about 80KB.

When I start running consumer_1 on machine A only, it can receive data with about 118MB/s, almost full speed of bandwidth.
When I start running consumer_2 on machine B only, it can also receive data with about 118MB/s.
But when I run consumer_1 and consumer_2 both, they can only receive data with about 60MB/s for each.
consumer_1 and consumer_2 use different groupids consuming different topics one different machines.
they should pull data separately with full speed of bandwith.
why? Is there anything wrong? please help me, thanks.

How to reproduce
================
Firstly, produce about 1 million msgs to topic_1 and topic_2, each topic has three partitions with replication factor 1.
Secondly, only start consumer_1 or consumer_2 with default configurations.
Thirdly, start consumer_1 and consumer_2 both with default configurations.
Fourthly, stop one of consumer_1 or consumer_2, consumer left can pull data with higher speed, back to full speed.

Checklist
=========
Please provide the following information:

 - [0.9.3] librdkafka version (release number or git tag):
 - [0.10.1.0] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [redhat 6u3 X64] Operating system:
 - [ ] Using the legacy Consumer
 - [yes] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It seems like you are maxing out the network:
120MB/s is roughly 1 gigabit, which is your network speed. With one consumer you reach this speed, with two consumers you get half that speed per consumer, which equals the same throughput in total.

**Comment by lording** [comment]
ok, thank you for your advice, edenhill.
