### ISSUE TITLE
Add a rd_kafka_metadata where only_rkt is char*

### ISSUE THREAD

**Issue by treziac** [edenhill/librdkafka#1139]
Querying metadata on a single topic can only be done with a rd_kafka_topic_t, but only the char* is use, it would be nice to add

```
rd_kafka_metadata (rd_kafka_t *rk, int all_topics,
                   char *only_rkt,
                   const struct rd_kafka_metadata **metadatap,
                   int timeout_ms) 
```

overload

Especially when wrapping the library like in confluent-kafka-dotnet, it would avoid to deal with internal librdkafka structures.

**Comment by edenhill** [comment]
I anticipated this would come :)

My plan is to add a new metadata API that takes a list of topic_partition_t (or a list of strings).

**Comment by edenhill** [comment]
dup #1158
