### ISSUE TITLE
Idempotent producer

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#114]
Implementation of only-once guarantee on the producer side

https://cwiki.apache.org/confluence/display/KAFKA/Idempotent+Producer

**Comment by edenhill** [comment]
This will be implemented through EOS

**Comment by grantr** [comment]
@edenhill What is the EOS you're referring to?

**Comment by edenhill** [comment]
EOS is Exactly Once Semantics, more info here:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging
