### ISSUE TITLE
unable to feed large amount of data to kafka producer

### ISSUE THREAD

**Issue by kanchanagarwal3** [edenhill/librdkafka#1140]
code snippet:
 // Deliver message
retry:
                        if( rd_kafka_produce(
                                kafka_topic,
                                partition,
                                RD_KAFKA_MSG_F_COPY,
                                msg.msg,
                                strlen(msg.msg),
                                NULL,
                                0,
                                NULL
                        ) == -1 ) {
                                printf( "Could not send message to kafka\n" );

fprintf(stderr,
                                "%% Failed to produce to topic %s: %s\n",
                                rd_kafka_topic_name(kafka_topic),
                                rd_kafka_err2str(rd_kafka_last_error()));

                        /* Poll to handle delivery reports */
                        if (rd_kafka_last_error() ==
                            RD_KAFKA_RESP_ERR__QUEUE_FULL) {
                                /* If the internal queue is full, wait for
                                 * messages to be delivered and then retry.
                                 * The internal queue represents both
                                 * messages to be sent and messages that have
                                 * been sent or failed, awaiting their
                                 * delivery report callback to be called.
                                 *
                                 * The internal queue is limited by the
                                 * configuration property
                                 * queue.buffering.max.messages */

rd_kafka_poll(kafka_conn, 10/*block for max 1000ms*/);
                                goto retry;
cnt_processed_msg++;

                        rd_kafka_poll( kafka_conn, 0 );

                        }
// Wait for all messages to be delivered
    while( rd_kafka_outq_len( kafka_conn ) > 0 ) {

     rd_kafka_poll( kafka_conn, 1 );
 }
kafka config file:
KafkaBrokers            plaintext://Hdfs500.host.mobistar.be:9093,plaintext://Hdfs600.host.mobistar.be:9093,plaintext://Hdfs602.host.mobistar.be:9093
KafkaTopic              cgn.int.ship

Librdkafka version 0.9.3

**Comment by edenhill** [comment]
When you open an issue there is a template that you need to fill in, it is there to help you provide the appropriate information for us to help you.

Ignoring that template and not providing proper information means your issue can't be handled and it will be ignored or closed.

**Comment by kanchanagarwal3** [comment]
Issue description:

Unable to feed large amount of continuous data  to Kafka_Producer inBatch Process.

If i send say 10k events to Kafka_Producer..it fetches only 7k(approx)

No timeout property added 
Moreover rd_kafka_poll() is also set to 0
