### ISSUE TITLE
Not able to produce big message(2M Bytes long) 

### ISSUE THREAD

**Issue by tsplibrdkakfa** [edenhill/librdkafka#1141]
Description
===========
Hi Edenhill,

I am trying to produce string message with length of 2MBytes. Default Configuration of "message.max.bytes" supports less (1000000). So I change that property to 2000000 and then try to produce the message with 2MBytes length. rd_kafka_produce returns success but the Delivery CallBack never gets called. On server side I have changed needed parameters for handling 2MB message. 

Important thing I notice is that the functionality works with librdkafka 0.9.2. with librdkafka 0.9.2 the consumer is able to receive message with 2Mbytes length.  When I change the library to 0.9.3,  it does not work. 0.9.4 also does not work. 

Thanks.

How to reproduce
================
To set the property "message.max.bytes" to 2000000 and then try to produce message of length 2000000.

Checklist
=========
Please provide the following information:

 - [] librdkafka version (release number or git tag):0.9.3 and 0.9.4
 - [ ] Apache Kafka version: kafka_2.11-0.9.0.0
 - [ ] librdkafka client configuration: As mentioned in description of problem
 - [ ] Operating system: Linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by tsplibrdkakfa** [comment]
Hi Edenhill, Can you please check this issue. Please let me know if any configuration related thing changed from 0.9.2 to 0.9.3 of librdkafka version that we have to take care in our client process.
Thanks.

**Comment by edenhill** [comment]
Can you try increasing message.max.bytes by 10% to account for message overhead?

Also make sure fetch.message.max.bytes is sufficiently large on the consumer.

**Comment by tsplibrdkakfa** [comment]
Thanks for the hint Edenhill. After accounting the overhead for the message, I am able to push 2MB message. 
I think the configuration parameter information should be updated to help the users of librdkafka.
