### ISSUE TITLE
Multile threads shared one producer or consumer

### ISSUE THREAD

**Issue by zdftju** [edenhill/librdkafka#1144]
Hi, edenhill:
          Is the cpp client thread safe? I means multiple threads share one producer or cunsumer, and the producer or consumer binds multiple topics. First,I create an extern value producer or consumer, then I use the producer in multiple threads  like this: producer.produce(topicName,partition), consumer.consume(topicName,partition), every thread binds a single topic.

**Comment by edenhill** [comment]
Yes, the client is thread-safe.

**Comment by zdftju** [comment]
thanks！
