### ISSUE TITLE
Consumer stops listening after disconnected message

### ISSUE THREAD

**Issue by asharma339** [edenhill/librdkafka#1145]
Description
===========
Related to issue https://github.com/edenhill/librdkafka/issues/437, when no messages are being published, I see errors messages like following on consumer:

`%3|1490728407.501|FAIL|mytask.tsk#consumer-1| [thrd:dob2-bach-r1n09.com:6667/bootstrap]: dob2-bach-r1n09..com:6667/544460917: Receive failed: Disconnected
`

From issue#437, it looked like it is just a logging issue, but I notice that listening stops working on consumer after I see above messages.

Please advise.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by asharma339** [comment]
Not an issue. My app code had bug.

**Comment by nkristianto** [comment]
hi, sorry
could u please tell me what happened with this case?
i face the same issue, and still not solved
