### ISSUE TITLE
rdns=false a nogo?

### ISSUE THREAD

**Issue by automaticgiant** [edenhill/librdkafka#1146]
Description
===========
can't achieve `rdns=false` functionality.
idk if it's a heimdal bug (i'm on osx), but i tried providing a krb5.conf (with `rdns=false`) and specifying location in `KRB5_CONFIG` but it wants to handshake with a re-resolved fqdn instead of the cname that the spn is for.
might not be your problem, but i saw in the docs that you say that broker arg must match spn, and didn't know if that was a choice made in development of this library.
this isn't necessarily true of the jvm client, though idk for sure if it is a matter of client dns resolution (jvm or librdkafka) or if it is more the responsibility of the underlying krb/gssapi.
so more info would be great, or suggestion/assessment of a fix (mine or yours) would be awesome.

How to reproduce
================
```
brew install kafkacat
KRB5_CONFIG=./krb5.conf kafkacat -v -d security -t test -b asdp0103.cloud:9092 -X security.protocol=sasl_ssl -X sasl.kerberos.kinit.cmd='kinit -t keytab' -C -X ssl.ca.location=dev_ca.pem
```

Checklist
=========
Please provide the following information:

 - [?] librdkafka version (release number or git tag): kafkacat librdkafka 0.9.4
 - [x] Apache Kafka version: confluent 3
 - [x] librdkafka client configuration: default, aside from specified in command
 - [x] Operating system: osx sierra
 - [x] Using the legacy Consumer no
 - [x] Using the high-level KafkaConsumer yes
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue - would have to replace with jvm client or change spns

```
%7|1490734297.585|SSLVERIFY|rdkafka#consumer-1| [thrd:sasl_ssl://asdp0103.cloud:9092/bootstrap]: sasl_ssl://asdp0103.cloud:9092/bootstrap: Broker SSL certificate verified
%7|1490734297.585|AUTH|rdkafka#consumer-1| [thrd:sasl_ssl://asdp0103.cloud:9092/bootstrap]: sasl_ssl://asdp0103.cloud:9092/bootstrap: Auth in state CONNECT (handshake not supported)
%7|1490734297.585|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://asdp0103.cloud:9092/bootstrap]: sasl_ssl://asdp0103.cloud:9092/bootstrap: Initializing SASL client: service name kafka, hostname asdp0103.cloud, mechanisms GSSAPI
%7|1490734297.585|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://asdp0103.cloud:9092/bootstrap]: sasl_ssl://asdp0103.cloud:9092/bootstrap: Refreshing SASL keys with command: kinit -t keytab
Encryption type arcfour-hmac-md5(23) used for authentication is weak and will be deprecated
%7|1490734297.652|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://asdp0103.cloud:9092/bootstrap]: sasl_ssl://asdp0103.cloud:9092/bootstrap: SASL key refreshed
%7|1490734297.653|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://asdp0103.cloud:9092/bootstrap]: sasl_ssl://asdp0103.cloud:9092/bootstrap: My supported SASL mechanisms: SRP GSSAPI GSSAPI DIGEST-MD5 WEBDAV-DIGEST EXTERNAL SMB-NTLMv2 DHX APOP CRAM-MD5 NTLM MS-CHAPv2 PLAIN-CLIENTTOKEN ATOKEN PLAIN OAUTHBEARER LOGIN XOAUTH2 ANONYMOUS
%2|1490734297.735|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://asdp0103.cloud:9092/bootstrap]: sasl_ssl://asdp0103.cloud:9092/bootstrap: GSSAPI Error:  Miscellaneous failure (see text (Server (kafka/ip-204-92-65.dqa@DQA) unknown)
%3|1490734297.735|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://asdp0103.cloud:9092/bootstrap]: sasl_ssl://asdp0103.cloud:9092/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (Server (kafka/ip-204-92-65.dqa@DQA) unknown)
% Fatal error at consumer_run:584:
% ERROR: Failed to query metadata for topic test: Local: Broker transport failure
```

**Comment by edenhill** [comment]
> but i saw in the docs that you say that broker arg must match spn, and didn't know if that was a choice made in development of this library.

Since a client will most likely connect to multiple brokers this seems like the only plausible option, using one ticker per broker and using that broker's configured or advertised name.

Otherwise you would need to configure an SPN manually for each broker and have some way of mapping the configured/advertised broker to this SPN, which seems error prone and a lot of work.

However, you are free to specify any command line you like for the sasl.kerberos.kinit.cmd which allows you to use an alternate broker name, but this is a global property that will be called for each broker.

**Comment by edenhill** [comment]
I can't tell you why rdns=false isn't working, I have no idea.

**Comment by automaticgiant** [comment]
wait, why would the kinit change the spn the client is expecting from the broker?

**Comment by edenhill** [comment]
librdkafka allows you to configure the kinit command to your liking, see `sasl.kerberos.kinit.cmd` in [CONFIGURATION.md](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)
