### ISSUE TITLE
replication factor: 3 larger than available brokers: 0

### ISSUE THREAD

**Issue by CasperLiu** [edenhill/librdkafka#1148]
Description
===========
Hi Magnus,
 
We happened to run into a “rainy day” case, which triggered us to think into similar scenario and wanted to consult you real kafka expert.

The real story:
In Kafka borker configuration we set 3 replicas

config/server.properties
\#   Replication
auto.create.topics.enable=true
default.replication.factor=3 

But we only brought up one broker instance and created a topic manually via

bin/kafka-topics.sh --create  --zookeeper zookeeper.tas01.local -replication-factor 1 --partitions 2 --topic test

here we chose “--replication-factor 1” so it could create the topic “test” successfully.

Then we brought up our producer based on your “libkfk_rd” and started sending message with topic “test”.
It went well in first 5 minutes, and then we got “unknow topic” error message by calling right after 5 minutes.

Did tcpdump and checked server.log at Kafka Broker side, we found it complained 

[2017-03-31 02:14:44,847] ERROR [KafkaApi-6] error when handling request Name: TopicMetadataRequest; Version: 0; CorrelationId: 1; ClientId: rdkafka; Topics: test (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 0
        at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:77)
        at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:236)
        at kafka.server.KafkaApis$$anonfun$20.apply(KafkaApis.scala:572)
        at kafka.server.KafkaApis$$anonfun$20.apply(KafkaApis.scala:555)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.Set$Set2.foreach(Set.scala:111)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)

We know this was upon “Metadata Request” sent from your libkfk_rd, but the check was done at server side as from tcpdump trace we did not see  the request included “replica” number but only topic name.

That made sense given we set “default.replication.factor = 3” but only brought up one broker instance. (we understood the 5 minutes good interval from your doc )

What we thought further was:
\1)     We set “default.replication.factor =3” and we do bring up 3 broker instances – then all should work perfectly 
\2)     Suppose after a while, one or two of the broker instances go away that leaves only one broker instance in service
\3)     Therefore it again builds up a “default.replication.factor = 3” but one broker instance scenario
Will then it run into the same problem as in the real story we ran into ?

Much appreciate your insight, thanks

How to reproduce
================
Please see above details.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
v0.9.4
 - [ ] Apache Kafka version: 
2.11-0.9.0.1
 - [ ] librdkafka client configuration:
Only producer functionality is used.
 - [ ] Operating system:
Linux 4.4.22-1.el7.elrepo.x86_64 #1 SMP Sat Sep 24 10:20:58 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
 - [ ] Using the legacy Consumer
Not use the consumer API. 
 - [ ] Using the high-level KafkaConsumer
Not use the consumer API. 
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
No log so far.
 - [ ] Provide broker log excerpts
No log so far.
 - [ ] Critical issue
Yes. A critical issue.

**Comment by edenhill** [comment]
I think what happened here was that the broker was restarted, or somehow lost the 'test' topic that you created with replication factor 1, and then librdkafka sent a metadata request for topic 'test' that the broker then auto-created with the default replication factor of 3, which fails since not enough brokers were available.
