### ISSUE TITLE
rd_kafka_producev default value

### ISSUE THREAD

**Issue by treziac** [edenhill/librdkafka#1153]
When using rd_kafka_producev, is there any differences between providing no rd_kafka_vtype_t for timestamp and sending 0?

Also, not providing partition send data to the 0 partition, I was expecting it to send as RD_KAFKA_PARTITION_UA. Is it expected behavior / documented somewhere?

**Comment by edenhill** [comment]
The zero timestamp (which is also the default) makes librdkafka insert the current time.

The partition being 0 is a bug, will fix. Thanks!

**Comment by treziac** [comment]
So we can rely on sending a 0 timestamp / -1 partition with no problem?

**Comment by edenhill** [comment]
Yep!

**Comment by treziac** [comment]
Solved on 0.9.5
