### ISSUE TITLE
Specify topic config with rd_kafka_producev and topic name

### ISSUE THREAD

**Issue by treziac** [edenhill/librdkafka#1155]
Is there any plan in adding a `RD_KAFKA_VTYPE_TOPICCONF //(const char *, rd_kafka_topic_conf_t *) `for rd_kafka_producev when wanting to use a specific conf, or should we use the `RD_KAFKA_VTYPE_RKT `for this use case?

**Comment by edenhill** [comment]
That requirement hasn't come up before, what's the use-case?

**Comment by treziac** [comment]
https://github.com/confluentinc/confluent-kafka-dotnet/issues/139
In confluent-kafka-dotnet, I'm looking at how to introduce custom partitioner/other custom topic conf in specific topics (in Rdkafka, we could directly create topic with the config so this was not a problem)

As producev can create topic when given a new topic name, I though it could be passed there too. But perhaps it's better to create the topic before with custom configs, and then produce to it.

**Comment by edenhill** [comment]
The topic object is only created once in librdkafka, any sub-sequent calls to rd_kafka_topic_new() will just increase a refcount and ignore the passed topic_conf.
With this in mind it is a bad fit to allow providing topic_conf to producev() since it would only be used the first time.

**Comment by treziac** [comment]
Ok with this, thanks
