### ISSUE TITLE
Setting receive.message.max.bytes  (Protocol parse failure)

### ISSUE THREAD

**Issue by winbatch** [edenhill/librdkafka#116]
1400039259.017 RDKAFKA-4-PROTOERR: rdkafka#consumer-0: d146537-025.masked.com:5757/1052189117: Protocol parse failure at rd_kafka_messageset_handle:2637
1400039259.017 RDKAFKA-4-PROTOERR: rdkafka#consumer-0: d146537-025.masked.com:5757/1052189117: expected 18 bytes > 4 remaining bytes

**Comment by weekendyogi** [comment]
I am hitting this issue.

On all brokers
max.request.size=1000000
fetch.message.max.bytes=1000000

message.max.bytes=1000000
replica.fetch.max.bytes=1000000



On consumer
receive.message.max.bytes=1000000000
fetch.message.max.bytes=1000000
message.max.bytes=1000000 

1527700852.798 RDKAFKA-7-BROKERFAIL: rdkafka#consumer-1: [thrd:ssl://knode1.scaletest.mgmt:8082/bootstrap]: ssl://knode1.scaletest.mgmt:8082/bootstrap: failed: err: Local: Bad message format: (errno: Success)
1527700852.798 RDKAFKA-3-FAIL: rdkafka#consumer-1: [thrd:ssl://knode1.scaletest.mgmt:8082/bootstrap]: ssl://knode1.scaletest.mgmt:8082/bootstrap: Receive failed: Invalid message size 1213486156 (0..1000000000): increase receive.message.max.bytes
1527700852.799 RDKAFKA-3-ERROR: rdkafka#consumer-1: [thrd:ssl://knode1.scaletest.mgmt:8082/bootstrap]: ssl://knode1.scaletest.mgmt:8082/bootstrap: Receive failed: Invalid message size 1213486156 (0..1000000000): increase receive.message.max.bytes

**Comment by edenhill** [comment]
@weekendyogi what librdkafka version?

**Comment by weekendyogi** [comment]
I took the latest from git hub.

I also tried 0.9.4
