### ISSUE TITLE
Using the "low latency" fd-queue wakeups in the legacy simple consumer

### ISSUE THREAD

**Issue by samanpa** [edenhill/librdkafka#1161]
Description
===========
When one attempts to produce a message the `rd_kafka_toppar_enq_msg` method is called which  immediately _wakes up_ the network communication thread (by writing to a pipe). When using the simple consumer there is no similar sequence. As such to get _low latency_ one has to still depend on **socket.blocking.max.ms** which is supposed to be deprecated.

Any chance that we can get low latency fd-queue wakeups in the legacy simple consumer?

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.4
 - [x] Using the legacy Consumer: Yes.

**Comment by edenhill** [comment]
Is there a reason you can't use the high-level consumer? (with assign())

**Comment by samanpa** [comment]
Using the high level consume will still not solve the _problem_ with **socket.blocking.max.ms** . Even though that setting is supposed to be deprecated it still has an effect on both the high level and simple consumer but not on producers.

**Comment by edenhill** [comment]
I understand.

Is there are a reason you can't decrease socket.blocking.max.ms?
Out of curiosity, what is your target latency?
