### ISSUE TITLE
Question: Correlate kafka messages & wait for specific message

### ISSUE THREAD

**Issue by PhilipSchmid** [edenhill/librdkafka#1162]
Hi there,

Im currently working on a small project, where I would like to develop an Apache HTTPD module which communicates with Apache Kafka to a backend. The goal is to extract some information about each incoming request to a Kafka topic (e.g. request URL, timestamp etc..). 
When a request arrives on some special URLs, I would like to rate this request on the backend system (within about 100-250 milliseconds). This means I would like to hold back the request on the Apache HTTPD and listen on a topic with a Kafka consumer for the correlated response (rating).

Regarding this use case described above, I would like ask you guys some questions:

1. Is it possible to use something like a correlation ID in a message which is send from the Apache HTTPD to the backend? This correlation ID would be needed to correlate the afterwards incoming Kafka message response against all waiting requests on the Apache HTTPD in order to see to which one it belongs. As described in the [Producer API](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md) there is a `key` field but I'm not sure if this one could also be used for this purpose. I guess an alternative would be to set a random correlation ID in the sent message itself. When a response arrives, this manual set correlation ID would be extracted (via Callback?).

2. The other question is, is it possible to use some kind of `rd_kafka_consume*()` function which listens for all incoming messages but only terminates and consumes the related message (the rating response) when a specific correlation ID matches?

Any hint and/or help is welcome!

Thank you.

Regards,
Philip

**Comment by vamshi2055** [comment]
Whats the solution for this issue?
