### ISSUE TITLE
Question: Getting offset for a specific consumer

### ISSUE THREAD

**Issue by asharma339** [edenhill/librdkafka#1163]
Description
===========
Looks like rd_kafka_query_watermark_offsets() returns the highest offset committed for a topic+partition irrespective of which consumer/consumergroup committed that offset. Is there a way to find highest committed offset for your  consumer or consumer group if you are doing auto commits on brokers?

I know in consume call back, we do get offsets, but when you are starting first time, you may need to find out the latest committed offset. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
rd_kafka_query_watermark_offsets() returns the partition's lowest and highest message offset, regardless of consumer position, i.e., the oldest and newest messages' offset in the partition.

You should use rd_kafka_committed() to get the committed offset for a consumer group, make sure to configure "group.id" to match the group you are querying about.

**Comment by asharma339** [comment]
Thanks.

**Comment by tzachshabtay** [comment]
Hi @edenhill question on `rd_kafka_committed`, to get the offsets for all partitions using this function it seems I need to assign all partitions to my created group, is this non-intrusive? i.e I don't want my admin application to temporarily hijack the partitions from the real consumers for that consumer group that consume the messages.

**Comment by edenhill** [comment]
If you only want to read the committed offsets and not actually start consuming the partitions you shouldn't assign(), but rather call rd_kafka_metadata() to get the partition count of the topic and then create a topic_partition_list_t list of all partitions, then pass that to committed().
