### ISSUE TITLE
Consumer re-join group takes a long time

### ISSUE THREAD

**Issue by dw09** [edenhill/librdkafka#1165]
Description
===========
The consumer leaves the consumer group with successful `rd_kafka_consumer_close()` and `rd_kafka_destroy()` and the process terminates.
The restarted consumer, with the same `group.id`, takes about 60s until it rebalances to receive messages again.  Session timeout is set to 40s.
This happens even if it is the only consumer.

Kafka warns:
WARN Attempting to send response via channel for which there is no open connection, connection id 2 (kafka.network.Processor)

Is this maybe even expected behaviour?
I used much lower session timeouts so far, but I would have expected the rebalance to be faster after the consumer left the group cleanly.
If this is not expected, I will fetch more log output.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 440fe36  (from today)
 - [x] Apache Kafka version: 0.10.2.0
 - [ ] librdkafka client configuration:
 - [x] Operating system: Linux
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you reproduce this with 'debug=cgrp' and provide the logs?

**Comment by andrey-sra** [comment]
I am seeing the same WARN message every 2 seconds on the broker side with 0.10.2.0 and older `librdkafka` (https://github.com/edenhill/librdkafka/commit/9db322b525685daad40d5c779d68fb0c37225769)

**Comment by psmod2** [comment]
@dw09 Did you manage to resolve this - if so how?
