### ISSUE TITLE
some configures in kafka cannot be found in https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

### ISSUE THREAD

**Issue by Mxiaoyu** [edenhill/librdkafka#1167]
Description
===========
There are some configures in kafka cannot be found in the configures of librdkafka.
For example, the **request.timeout.ms** of consumer,  Or is the setting: socket.timeout.ms?
what configure corresponds to the **buffer_memory**?

How to reproduce
================

My versions:

Please provide the following information:
librdkafka v0.9.4 release
Apache kafka 2.11

**Comment by edenhill** [comment]
Yes, request.timeout.ms corresponds to socket.timeout.ms.

Buffer memory is controlled through queue.buffering.max.kbytes for the producer and queued.max.messages.kbytes for the consumer.

**Comment by Mxiaoyu** [comment]
Understand! Thanks for answering so quickly!
