### ISSUE TITLE
manually store offset in high-level consumer 

### ISSUE THREAD

**Issue by Mxiaoyu** [edenhill/librdkafka#1168]
Description
===========
hello, edenhill. I use the high-level API of consumer: **RdKafka::KafkaConsumer**, Then I want to set the enable.auto.commit=false, and manually stored it. But, I only find the API **offset_store (int32_t partition, int64_t offset)** which is limited to the simple RdKafka::Consumer. 
Is there an API doing this or I have to use the low-level API?

my librdkafka is release v0.9.4

**Comment by jleducq** [comment]
This feature should be included in the next librdkafka release (v0.9.5):
https://github.com/edenhill/librdkafka/issues/826

**Comment by Mxiaoyu** [comment]
Thanks for answering. Is there any alternative solution for the time being?

**Comment by jleducq** [comment]
I don't know any alternatives, but my guess is that 0.9.5 should be released very soon. There is already 2 RC: https://github.com/edenhill/librdkafka/releases

**Comment by Mxiaoyu** [comment]
Understand~Thanks

**Comment by Mxiaoyu** [comment]
Hi， edenhill， I find that V0.9.5 has been released. But I didn't find the feature of manually storing offset in high-level consumer. Will the feature be released in next version or the feature has been added in V 0.9.5?

**Comment by edenhill** [comment]
I'm sorry but offset_store() in C++ didn't make the 0.9.5 maintenance release, it will be shipped with the next feature release which is about 1.5 months out.

**Comment by edenhill** [comment]
The workaround for now is to use the C interface:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2243

Something like:
```
 // Save this somewhere to reuse it for each offset_store() call.
 // You an cache the topic in the RebalanceCb on ASSIGN and destroy
 // it on REVOKE
 rd_kafka_topic_t *rkt = rd_kafka_topic_new("my_topic", NULL);
  
...
  rd_kafka_offset_store(rkt, my_partition, my_offset);

...

// Make sure to free the rkt when you are done with it
rd_kafka_topic_destroy(rkt);
```

**Comment by Mxiaoyu** [comment]
No problem. Thanks for that.

**Comment by edenhill** [comment]
fixed on master

**Comment by Mxiaoyu** [comment]
@edenhill  I see the issue has been closed. Does that mean that the feature has been fixed in master or will be added in the next feature? But I cannot find the commit of this in the master.

**Comment by edenhill** [comment]
The method is called KafkaConsumer::offsets_store() and was added in commit 715c49bfbf9f3fe41934989cf92408966949954e
