### ISSUE TITLE
producer returns Queue full

### ISSUE THREAD

**Issue by ghost** [edenhill/librdkafka#117]
If I set
 queue.buffering.max.messages=10 
and
 queue.buffering.max.ms=60000

the producer returns "Queue full" after sending 10 messages . It seems that the producer doesn't send the messages to kafka. I should suppose that when the queue is full ( or maybe 3/4 full) the messages are send to kafka even if queue.buffering.max.ms is not expired. 
Maybe it is better to define a max and min value.
When the size of queue is more than buffering.min then producer tries to send the data to kafka

**Comment by mikesparr** [comment]
@edenhill I got through the consumer issues and noticed the topic message count was greater than the Elasticsearch index count. In grep'ing logs I found these errors and error count almost matches the missing record count.

I notice you recommend some setting above and it's not clear exactly where to apply the settings for librdkafka using the `confluent-python-kafka` client library. When I try some of these in the `conf` Dictionary the app won't run. I appreciate an example python client config to adjust the settings to prevent `Queue full` issues we're seeing:

~~~
conf = {'bootstrap.servers': ','.join(map(str, self.config.get('hosts'))),
                'client.id': socket.gethostname(),
                'default.topic.config': {'acks': 'all'}
            }
~~~

Errors in logs:
![screen shot 2016-07-06 at 12 48 20 pm](https://cloud.githubusercontent.com/assets/5553105/16630515/fcac7ec6-4377-11e6-9a77-1fcf9e6f42bf.png)

**Comment by mikesparr** [comment]
If I edit the `confluent-kafka-python` conf object to the following increasing the millis for buffering and max messages but decreasing the batch size, is that recommended way to make sure I have plenty of buffer to avoid this?

~~~
            conf = {
                'bootstrap.servers': ','.join(map(str, self.config.get('hosts'))),
                'queue.buffering.max.messages': 500000,
                'queue.buffering.max.ms': 60000,
                'batch.num.messages': 100,
                'log.connection.close': False,
                'client.id': socket.gethostname(),
                'default.topic.config': {'acks': 'all'}
            }
~~~

**Comment by mikesparr** [comment]
With revised settings above, 0 errors in logs for diff/transform apps now! 

![screen shot 2016-07-06 at 3 08 04 pm](https://cloud.githubusercontent.com/assets/5553105/16634559/8ff48de6-438b-11e6-901c-168653e95cac.png)

**Comment by edenhill** [comment]
I'm guessing this is related to the confluent-kafka-python issue (not calling poll() frequently enough)
