### ISSUE TITLE
fd leak

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#1170]
Description
===========
having a kafka client in charge of forwarding messages from one cluster to another, this daemon program runs since several weeks.

We have seen an issue of connections to kafka cluster nodes that couldn't be made because there was too many open fd.
After analyzing lsof it seems that there was 3.5 million fd of type pipe open. half in read and half in write.

Since I don't use pipes myself I suspect this would be from librdkafka. Anyone already got that issue ? 

Thanks in advance for your thoughts.
Vincent.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ release 0.9.4] librdkafka version (release number or git tag):
 - [ producing to 10.0.0 and consuming from 10.1.0] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ubuntu 16.04] Operating system:
 - [ ] Using the legacy Consumer
 - [ producer and high level consumer] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka v0.9.4 added support for fd-based queue wakeups to minimize latency, and those are coincidently pipes, so I guess we have the culprit.

But there should only be two fds per queue, and I dont think you have 1.5M queues..?

Can you describe your use? Are you creating and destroying producer/consumers?

**Comment by vin-d** [comment]
Thanks,
I don't have the code in front of me but for what remember I only destroy Producer(KafkaConsumer) if I get an error back from them.

I do the same way you would do with a tcp socket or any connect-based communication medium .
I understood after working more with librdkafka that this was maybe not the best way to use it (as I think) it's doing that "connection reset" for you. anyway normally this shouldn't happen often as it's done on error.
I'll give a deeper look to it tomorrow.

**Comment by edenhill** [comment]
Oh, okay, yeah you shouldnt typically close librdkafka when you get an error, librdkafka will recover automatically.

But still, the fd leak is a bug.
It would be interesting to see how you are using the library and how you are shutting it down, so that I can reproduce this case.

**Comment by vin-d** [comment]
Here's a bit of statistics if it can give directions : 
(the program consumes from a cluster of 3 nodes and produces to a cluster of 5 nodes)
```
~$ less lsof.txt | wc -l
4919988
```
then specifics of these by grep on my program PID 26633:
Number of open fd for my program :
```
~$ less lsof26633.txt | wc -l
4897903
```
the number of threads of the program (awk on TID):
```
~$ less lsof26633.txt | awk '{ print $3  }' | uniq | wc -l 
4612
```
the number of open fd for a thread (here 27243 but I tested with a lot of random numbers)
```
~$ less lsof26633.txt  | grep 27243 | wc -l
1062
```
so 4612*1062 = 4897944 fd.

For one of these thread the partitioning of these 1062 open fd are
```
~$ less lsof26633.txt | grep 27300 | grep pipe | wc -l
748
```
```
~$ less lsof26633.txt | grep 27300 | grep IPv4 | wc -l
270
```
regular files : nothing abnormal here (mostly shared objects)
```
~$ less lsof26633.txt | grep 27300 | grep REG | wc -l
38
```
there are also so sock type fd open but less (not sure what this is exactly)
```
~$ less lsof26633.txt | grep sock | wc -l
40700
```
threads have either 0,7, or 14 sock fd but i'm not sure if this is related to librdkafka or not.

I can pass you lsof26633.txt privately if you want.

**Comment by edenhill** [comment]
nitpick:
> `~$ less lsof26633.txt | awk '{ print $3  }' | uniq | wc -l `

you need to sort before piping to uniq

**Comment by edenhill** [comment]
Thanks for the lsof stats, I would need to know how you are using the library though.

**Comment by edenhill** [comment]
Also see this:
https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence

**Comment by vin-d** [comment]
On my producer code, I created a RdKafka::Producer only once, so at least the leak is not caused by repeated Producer creation.

**Comment by edenhill** [comment]
Qs:
 * Do you know if it is the producer or consumer that is leaking, or both?
 * How many brokers do you have in your cluster?
 * Did you add or remove any brokers?
 * the thread count is very high, librdkafka will create a maximum of 1+(2*N) threads per instance where N is the number of brokers in the cluster. More threads than this indicates that there are multiple instances, or new brokers are added to the cluster (en masse).

**Comment by vin-d** [comment]
Answers : 
- I don't know (but as told in my previous msf on the producer side I only create it once.)
- the program consumes from a cluster of 3 nodes and produces to a cluster of 5 nodes
- no, the number of brokers is stable for both clusters.
- I'll guess I'll try to track the number of threads through time and link it to external events, tcp connection lost, KafkaConsumer deletion/creation ,etc...

I do a KafkaConsumer deletion/creation if I received unexpected error from an offset commit response (for example if I receive unknown member id response ) so it can trigger a revoke+assign rebalance to every body in the group.

And to answer you previous message about proper termination sequence : there is here something I assume I don't do well because my last Rdkafka instruction before exiting is 
```
RdKafka::wait_destroyed(2000);
```
it never returns 0, and other client of the consumer group have to wait 30s after rebalance revoke to get a new rebalance assign. And I assume that this is linked to the cluster waiting for a (timeout-ed) response from my exiting client .

but this is less of a problem because as a daemon program running in a service, it's in theory never ended.

**Comment by edenhill** [comment]
You dont need to call wait_destroyed() anymore (since destroy() is blocking), and with multiple instances wait_destroyed() will not return..

Regarding destroying the KafkaConsumer for each error: wouldnt it be enough to just unsubscribe()  and then subscribe() again when you get the revocation?

**Comment by edenhill** [comment]
Can you paste your code for terminating the KafkaConsumer?

**Comment by vin-d** [comment]
> Regarding destroying the KafkaConsumer for each error: wouldnt it be enough to just unsubscribe() and then subscribe() again when you get the revocation?

Yes that would be sufficient, but I haven't understood at the time I wrote this code that the library would manage to reconnect by itself upon connection error. I'll change that !

Also after reading https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence I see that I delete my KafkaConsumer before the RdKafka::Message are deleted in the case where a commit offset returns an error.
That's Because when I get messages from my consume loop I just pass it to a processing thread, which will pass it to a RdKafka::Producer ... and the message will finally be deleted in the Producer's RdKafka::DeliveryReportCb::dr_cb
.

Here's my code for terminating the KafkaConsumer (so it is ran once just at program shutdown)
```
ForwardingTask::~ForwardingTask()
{
    if(consumer != nullptr){
	std::vector<RdKafka::TopicPartition*> vTP;
        consumer->assignment(vTP);
        consumer->pause(vTP);
        consumer->unsubscribe(); //this triggers a rebalance-revoke
        purge(vTP); // I delete the TopicPartition referenced by the pointers
	
	consumer->consume(100);
	delete(consumer);
    }
    delete(conf); 
    delete(tconf);  
}
```

**Comment by edenhill** [comment]
Ah, yes:
> All objects except for the handle (C: rd_kafka_t, C++: Consumer,KafkaConsumer,Producer), such as topic objects, messages, topic_partition_t, TopicPartition, events, etc, MUST be destroyed/deleted prior to destroying or closing the handle.

So it seems that not deleting the messages causes this memory and fd leak.

**Comment by vin-d** [comment]
Thanks,
I'll just do the unsubscribe / resubscribe 
(and not the delete myKafkaConsumer / myKafkaConsumer = RdKafka::KafkaConsumer::create(conf, errstr);)
if  want to reset my processing because of errors.
