### ISSUE TITLE
Fetching metadata for a specific topic provides invalid amount of partitions

### ISSUE THREAD

**Issue by mfontanini** [edenhill/librdkafka#1172]
Description
===========
When calling `rd_kafka_metadata` using a specific topic as the argument (and using `all_topics` set to 1), I'm noticing the partition count for the topic is wrong. This only started happening today when I updated from 0.9.3 to 0.9.4. I also tried `HEAD` and it has the same issue.

Note that if I fetch the metadata for all topics (without using the specific one), this returns the right amount of partitions. I'm currently using this code:

```c++
Configuration config = {
    { "metadata.broker.list", brokers },
    { "group.id", "something" },
};
Consumer consumer(config);
Topic topicObject = consumer.get_topic(topic);
TopicMetadata topicMetadata = consumer.get_metadata(topicObject);
cout << topic << ": " << topicMetadata.get_partitions().size() << endl;
```

It uses cppkafka as a wrapper but it should be easily translatable to plain librdkafka code.

See the logs using debug: "all" [here](https://gist.github.com/mfontanini/2e1c6c02368aee89c96e2799a7111f67). This was a test I ran where the topic I requested metadata for was "broken_topic". The actual amount of partitions is 20 but librdkafka returned 100.

How to reproduce
================
Just use the code above, it fails 100% of the times for me.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.4
 - [x] Apache Kafka version: 0.10.1.0
 - [x] librdkafka client configuration: provided above
 - [x] Operating system: GNU/Linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
all_topics and specifying a specific topic are mutually exclusive.

Having said that it seems like the partition count behaviour is a bug in librdkafka.

**Comment by edenhill** [comment]
I can't reproduce this.

**Comment by mfontanini** [comment]
I'll re try this today at work as we have a big cluster in there but I can guarantee this was happening 100% of the times.

**Comment by mfontanini** [comment]
Seems like I can actually not reproduce it anymore. Maybe the broker was in some broken state? I don't know...

**Comment by edenhill** [comment]
What we've seen historically is that different brokers may return different partition counts when in a transient state, and since the client can't really control which broker to query for metadata this might have been the case.
