### ISSUE TITLE
CONFIGURATION.md modification by Makefile

### ISSUE THREAD

**Issue by mfontanini** [edenhill/librdkafka#1176]
Description
===========
Every time you run `make`, CONFIGURATION.md is regenerated. This makes it annoying to have to checkout tags/pull from the repo. I'm using librdkafka as a git submodule in a bunch of projects and every time I need to update the ref I need to run `git reset --hard` and only then I can actually pull. This is especially bad as I have it as a submodule of a submodule so I always need to end up going into the rdkafka directory and cleaning things up before updating refs.

I get it that it's useful to generate the configuration file automatically but IMO this should either:

* Be outside of the `all` target so users of the library don't generate it every time, as in reality you'd check it out straight on github, so there's no point in doing so.
* Or instead make sure the file is always up to date, so running `make` doesn't change it. This is less ideal as I imagine PR's could miss updating this.

How to reproduce
================
Run `./configure && make` on the current HEAD and you'll see CONFIGURATION.md marked as dirty.

**Comment by edenhill** [comment]
The modification is because your builtin features are less than the full set, which affect the generated properties, typically because you are missing a library dependency (such as cyrus-sasl/libsasl2 or lz4).

If the automatic generation was removed, or made explicit, it would inevitably lead to the checked in CONFIGURATION.md being outdated and not match the latest code. I have a hard time remembering to commit the file on change as it is.

You probably already have specific targets to build the submodule so maybe you can add one that resets just CONFIGURATION.md explicitly?

**Comment by mfontanini** [comment]
As much as I don't agree with the `all` target modifying the git index no matter the environment, I guess I can build whatever specific rdkafka target is built in.

**Comment by julien-lecomte** [comment]
@mfontanini I also don't like the md file being re-generated, so I issued a `git update-index --assume-unchanged` command on the file to ignore changes to it.

**Comment by jason-matthew** [comment]
Updating CONFIGURATION.md does have its perks.  Conveying supported properties ended up being a big help to troubleshoot error messages like 'No such configuration property: xxx'.

**Comment by rolandyoung** [comment]
@julien-lecomte It may be better to use `--skip-worktree`: see https://stackoverflow.com/a/13631525, but many thanks for pointing out this useful workaround

**Comment by edenhill** [comment]
@jason-matthew This gave me an idea; maybe we shouldn't `#ifdef`-out configuration properties, but simply mark them as not being included in the build, this way we can provide more useful error messages to the user. E.g. `No such configuration property: ssl.ca.location: this build lacks SSL support`
