### ISSUE TITLE
Kafka consumer: Broker: No more messages

### ISSUE THREAD

**Issue by PhilipSchmid** [edenhill/librdkafka#1177]
Description
===========
Hi there.

I'm trying to integrate a high-level Kafka consumer into my Apache HTTPD module. The Kafka producer part works already. Unfortunately I can't consume any messages, because the rkmessage payload only contains "Broker: No more messages". I already have checked [examples/rdkafka_consumer_example.c](https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_consumer_example.c) but I'm still not able to find the error in my code/configuration/setup. It would be awesome if someone of you guys could provide some input.

How to reproduce
================
In my `kafka_connect_consumer()`function, I create a new kafka consumer handle (`RD_KAFKA_CONSUMER`) if it's not already created by a previous call using `rd_kafka_new(RD_KAFKA_CONSUMER, *conf, errstr, sizeof(errstr))` with the following configuration (set by `rd_kafka_conf_new()`):

```C
apr_hash_set(conf->kafka.conf_consumer.global, "queue.buffering.max.ms", APR_HASH_KEY_STRING, (const void *)"0");
apr_hash_set(conf->kafka.conf_consumer.global, "debug", APR_HASH_KEY_STRING, (const void *)"cgrp,topic,fetch");
apr_hash_set(conf->kafka.conf_consumer.global, "offset.store.method", APR_HASH_KEY_STRING, (const void *)"broker");
```

After the kafka consumer handle creation, this code follows:
```C
    /* Set default topic config for pattern-matched topics. */
    if (conf != NULL && topic_conf != NULL) {
        rd_kafka_conf_set_default_topic_conf(conf, topic_conf);
    }

    /* Callback called on partition assignment changes */
    /*if (conf != NULL) {
        rd_kafka_conf_set_rebalance_cb(conf, kafka_consumer_rebalance);
    }*/

    /* Add our topic to the topics list */
    rd_kafka_topic_partition_list_add(kafka->topics, topic, 0);

    err = rd_kafka_subscribe(kafka->rk_consumer, kafka->topics);
    if (err) {
        ap_log_error(PC_LOG_CRIT, NULL, "Subscribe failed: [%s]", rd_kafka_err2str(err));
        exit(1);
    }

    ap_log_error(PC_LOG_INFO, NULL, "===== Starting consuming messages from %s =====", topic);

    rd_kafka_message_t *rkmessage;
    rkmessage = rd_kafka_consumer_poll(kafka->rk_consumer, 10000);
    if (rkmessage) {

        if (rkmessage->payload) {
          ap_log_error(PC_LOG_INFO, NULL, "CONSUMED MESSAGE [%s]", rkmessage->payload);
        } else {
          ap_log_error(PC_LOG_INFO, NULL, "CONSUMED MESSAGE is empty");
        }
        //ap_log_error(PC_LOG_INFO, NULL, "CONSUMED MESSAGE [%s] with key [%s]", rkmessage->payload, rkmessage->key);
    } else {
      if (rkmessage->err) {
        ap_log_error(PC_LOG_CRIT, NULL, "Response message not received. Error: %i", rkmessage->err);
      } else {
        ap_log_error(PC_LOG_CRIT, NULL, "Response message not received. No error log provided.");
      }
    }
    rd_kafka_message_destroy(rkmessage);
    ap_log_error(PC_LOG_INFO, NULL, "===== Stopping consuming messages from %s =====", topic);
```

As you can see, I use a timeout of 10 sec to  block and wait for new messages (`rd_kafka_consumer_poll(kafka->rk_consumer, 10000);`). During this timeintervall, I create a new message the manual way:

```bash
echo "123,This is a test message" | kafka-console-producer.sh \
    --broker-list localhost:9092 \
    --topic kafkalogger-analyse-result \
    --property parse.key=true \
    --property key.separator=,
```
Unfortunately this newly created new message isn't consumed by my kafka high-level consumer. 

Here is the debug log output: [https://gist.github.com/PhilipSchmid/4300560def195f474b97359362bc556e](https://gist.github.com/PhilipSchmid/4300560def195f474b97359362bc556e)

Question for my understanding: The API of `rd_kafka_consumer_poll()` says "Will block for at most \p timeout_ms milliseconds". In which case will it exactly block? Also if no new message is available (as I currently use it in my code above)? If not, looping over `rd_kafka_consumer_poll()` will be required until the message is available, right?

Thanks!

Regards,
Philip

Checklist
=========
Please provide the following information:

 - [X] librdkafka version (release number or git tag): 0.9.3-1
 - [X] Apache Kafka version: https://hub.docker.com/r/spotify/kafka/
 - [ ] librdkafka client configuration:
 - [X] Operating system: 4.9.0-kali3-amd64
 - [X] Using the legacy Consumer: NO
 - [X] Using the high-level KafkaConsumer: YES
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by PhilipSchmid** [comment]
I was able to fix it. Thanks anyway.

```C
    ap_log_error(PC_LOG_INFO, NULL, "===== Starting consuming messages from %s =====", topic);
    while (msgcount != -1) {
        rd_kafka_message_t *rkmessage;
        rkmessage = rd_kafka_consumer_poll(kafka->rk_consumer, 10);
        if (rkmessage) {
            if (rkmessage->err) {
                /* We have reached the topic/partition end. Continue to wait for the response.. */
                if (rkmessage->err == RD_KAFKA_RESP_ERR__PARTITION_EOF) {
                    rd_kafka_message_destroy(rkmessage);
                    continue;
                }
            }
            ap_log_error(PC_LOG_INFO, NULL, "CONSUMED MESSAGE [%s] with key [%s]", rkmessage->payload, rkmessage->key);
            msgcount = -1;
            rd_kafka_message_destroy(rkmessage);
        }
    }
    ap_log_error(PC_LOG_INFO, NULL, "===== Stopping consuming messages from %s =====", topic);
```

Regards,
Philip

**Comment by rarchana2001asu** [comment]
@PhilipSchmid so the fix is polling for new messages from producer and exiting when a message is read? If I want the consumer to read from the beginning of the partition then what configuration is needed?

**Comment by edenhill** [comment]
@rarchana2001asu If you always want to start from the oldest available message you can call assign with the .offset field set to RD_KAFKA_OFFSET_BEGINNING
