### ISSUE TITLE
Connection refused when try to connect to the broker from librdkafka producer

### ISSUE THREAD

**Issue by syedtoah** [edenhill/librdkafka#1182]
Hello Edenhill,

I am facing a rather weird issue, I have set the IP:9092 as the listeners on the broker, have started the broker in Stand alone mode. Now when I run the producer I see that there is one connection established and the other one is bailing out with connection refused.

Below are the details:
Broker is running on a VM and the producer on another.
I have stopped the iptable rules, so no firewall.
I can do telnet IP 9092 and it is fine.

On Producer:
netstat -anop | grep 9092
tcp        0      0 12.0.0.22:45725         12.0.0.23:9092          ESTABLISHED 11642/kafkaclient off (0.00/0/0)

On a service restart on the broker, I see this on the producer:

[root@BENU TEMP/MEG-1] opt# 1492519874.304 RDKAFKA-3-FAIL: rdkafka#producer-2: 12.0.0.23:9092/0: Receive failed: Disconnected
1492519874.414 RDKAFKA-3-FAIL: rdkafka#producer-2: 12.0.0.23:9092/0: Connect to ipv4#12.0.0.23:9092 failed: Connection refused
1492519875.431 RDKAFKA-3-FAIL: rdkafka#producer-2: 12.0.0.23:9092/0: Connect to ipv4#12.0.0.23:9092 failed: Connection refused
1492519876.445 RDKAFKA-3-FAIL: rdkafka#producer-2: 12.0.0.23:9092/0: Connect to ipv4#12.0.0.23:9092 failed: Connection refused
1492519877.464 RDKAFKA-3-FAIL: rdkafka#producer-2: 12.0.0.23:9092/0: Connect to ipv4#12.0.0.23:9092 failed: Connection refused
1492519878.475 RDKAFKA-3-FAIL: rdkafka#producer-2: 12.0.0.23:9092/0: Connect to ipv4#12.0.0.23:9092 failed: Connection refused
1492519879.491 RDKAFKA-3-FAIL: rdkafka#producer-2: 12.0.0.23:9092/0: Connect to ipv4#12.0.0.23:9092 failed: Connection refused
1492519880.504 RDKAFKA-3-FAIL: rdkafka#producer-2: 12.0.0.23:9092/0: Connect to ipv4#12.0.0.23:9092 failed: Connection refused

On the broker:
tcp6       0      0 12.0.0.23:9092          :::*                    LISTEN      5962/java            off (0.00/0/0)
tcp6       0      0 12.0.0.23:9092          12.0.0.23:34666         ESTABLISHED 5962/java            keepalive (7070.29/0/0)
tcp6       0      0 12.0.0.23:34661         12.0.0.23:9092          ESTABLISHED 5962/java            keepalive (7070.29/0/0)
tcp6       0      0 12.0.0.23:9092          12.0.0.23:34661         ESTABLISHED 5962/java            keepalive (7070.29/0/0)
tcp6       0      0 12.0.0.23:9092          12.0.0.22:45725         ESTABLISHED 5962/java            keepalive (7070.29/0/0)

librdkafka version: 0.9.2
Kafka version: kafka_2.11-0.10.1.1
OS: CentOS Linux release 7.2.1511 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.2.1511 (Core) 
CentOS Linux release 7.2.1511 (Core)

**Comment by edenhill** [comment]
I'm not sure why your client can't connect: 
it looks like it first manages to connect and then Disconnects, followed by connection refused, which would indicate that the broker might have died?

Are you running the telnet test from the same host? If not there could be some firewall rules in place

**Comment by syedtoah** [comment]
The disconnect is because I did the broker service restart, which will allow the producer to try reconnect.
Yes I did the telnet form the same client where the producer is.
I have dropped all the firewall rules.
Why does the client request two connections with the broker? Is there any thing else needed to further debug this?

**Comment by edenhill** [comment]
librdkafka will first connect to all configured bootstrap brokers and query the brokers for the full broker list from the cluster itself.
It will then also connect to that full broker list from the cluster.
If a configured bootstrap broker exactly matches (name and port) a broker reported in cluster metadata then it will use that same connection, otherwise create a new connection.

You can use `debug=broker` to get more debugging on this matter, but librdkafka only does simple TCP connections, so generally speaking these type of problems boil down to either:
 * the broker's advertised hostname and port (advertised.listener) are wrong or can't be reached
 * there are network problems or firewall rules

**Comment by syedtoah** [comment]
Thank you for explaining, for now out of no where it has started working. I am guessing some issue with the TCP connection and the firewall. Did nothing really with regard to this. I will close this for now and re-open to debug further if I see again. 

Again Thanks for helping.

**Comment by write2jaydeep** [comment]
Hi,  @syedtoah I am having the similar problem. If I specify hostname in /etc/hots. it just works perfect.
but here I don't have root permission to access the shared virtual machine.(openVOS) 
Is there any other way to work around?

**Comment by edenhill** [comment]
librdkafka relies solely on the local libc resolver (which typically uses DNS and /etc/hosts) to resolve hostnames.
