### ISSUE TITLE
0.8.6 : Core generated during metadata query 

### ISSUE THREAD

**Issue by mazharshaikh86** [edenhill/librdkafka#1184]
Description
===========
Core generated during metadata query 

#0 0x00007fb97a6670d5 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1 0x00007fb97a66a83b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2 0x00007fb97a03046a in rd_kafka_crash (file=<optimized out>, line=<optimized out>, function=<optimized out>, rk=0x7fb8e0308700, reason=<optimized out>) at rdkafka.c:1902
#3 0x00007fb97a03fb48 in rd_kafka_topic_destroy0 (rkt=0x7fb8e02f3900) at rdkafka_topic.c:410
#4 rd_kafka_topic_destroy0 (rkt=0x7fb8e02f3900) at rdkafka_topic.c:405
#5 0x00007fb97a03fb9e in rd_kafka_toppar_destroy0 (rktp=0x7fb94c1d7100) at rdkafka_topic.c:89
#6 0x00007fb97a038b5f in rd_kafka_broker_fail (rkb=0x7fb8ddae1200, err=RD_KAFKA_RESP_ERR__DESTROY, fmt=0x0) at rdkafka_broker.c:445
#7 0x00007fb97a03a204 in rd_kafka_broker_thread_main (arg=<optimized out>) at rdkafka_broker.c:4169
#8 0x00007fb98a99de9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9 0x00007fb97a72438d in clone () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x0000000000000000 in ?? ()

How to reproduce
================
Not able to reproduce.

Attaching the metadata query code (Executed once every 5 min for broker health check).

[metadata.txt](https://github.com/edenhill/librdkafka/files/934757/metadata.txt)

Checklist
=========
Please provide the following information:

 - [0x00080600] librdkafka version (release number or git tag):
 - [kafka_2.11-0.9.0.1 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka 0.8.6 is over 2 years and 1600 commits old, this issue has most likely been fixed since then.

You can check the release notes for the releases since v0.8.6 [here](https://github.com/edenhill/librdkafka/releases), or just upgrade to v0.9.5 right away :)
