### ISSUE TITLE
Compilation issue when SASL not enabled

### ISSUE THREAD

**Issue by ValerioSevilla** [edenhill/librdkafka#1185]
- [ ] librdkafka version (release number or git tag): v0.9.4 and v0.9.5
 - [ ] Operating system: Linux (Heroku)

Description
===========
I've got some compilation errors when deploying [node-rdkafka](https://github.com/Blizzard/node-rdkafka) into Heroku, and it seems they are due to a combination of issues in both node-rdkafka and librdkafka. This is:

node-rdkafka is using librdkafka v0.9.4. In that version (as well as in v0.9.5), there is this code within rdkafka_conf.h:

```c
struct rd_kafka_conf_s {

	...

#if WITH_SASL
	struct {
		char *principal;
		char *mechanisms;
		char *service_name;
		char *kinit_cmd;
		char *keytab;
		int   relogin_min_time;
		char *username;
		char *password;
	} sasl;
#endif

	...

}
```

There is a `rd_kafka_conf_s` contained in `rd_kafka_s`, as we can see in rdkafka_int.h:

```c
struct rd_kafka_s {

        ...

        rd_kafka_conf_t  rk_conf;

        ...
}
```

... and, in rdkafka_sasl.c, there are multiple references to that structure that try to access the inner `sasl` structure. For example:

```c
int rd_kafka_sasl_conf_validate (rd_kafka_t *rk,
				 char *errstr, size_t errstr_size) {

	if (strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI"))
		return 0;

	...
}
```

The problem is, this code is not protected with the `WITH_SASL` preprocessor label, which means that when compiling the library without defining `WITH_SASL`, errors like this one arise:

> if (!strcmp(rk->rk_conf.sasl.mechanisms, "GSSAPI")) {
> ^
> ../deps/librdkafka/src/rdkafka_sasl.c:157:32: error: ‘rd_kafka_conf_t’ has no member named ‘sasl’

Apparently this issue is fixed in the latest version in master branch, but it has not been tagged, so I don't know which version is it supposed to be.

I have found this preprocessor definition in win32_config.h (v0.9.4):

```c
#define WITH_SASL 1
```

I guess this means in Windows it is enabled by default. At this point I am not sure how can this be enabled in Unix systems. According to [node-rdkafka documentation](https://github.com/Blizzard/node-rdkafka#sasl-support), it is enabled by default, but for some reason it is being disabled when compiling from Heroku. Can anyone please help sort this out?

I'm opening an issue for node-rdkafka as well.

**Comment by ValerioSevilla** [comment]
Issue on node-rdkafka: https://github.com/Blizzard/node-rdkafka/issues/157

**Comment by edenhill** [comment]
There is currently no way to fix this retrospectively for the existing releases, so I suggest installing the SASL dependency as a workaround (cyrus-sasl-devel on rpm and libsasl2-dev on deb).

**Comment by ValerioSevilla** [comment]
@edenhill I see your point: during configuration, the `WITH_SASL` flag is set if the library is found. Now, in Heroku they have libsasl2-2 installed (you can check it [here](https://devcenter.heroku.com/articles/stack-packages)). I have found [the script in librdkafka that checks for the availability of libsasl2 or libsasl](https://github.com/edenhill/librdkafka/blob/master/configure.librdkafka#L71). If the available library is libsasl2-2, it doesn't work.

I will try to find a way of using libsasl2 or libsasl in Heroku, but it would actually be better if librdkafka considered the availability of libsasl2-2 as well.

**Comment by edenhill** [comment]
I'm not sure I understand what the problem with libsasl2-2 is, librdkafka works fine with it:
```
ubuntu:~/src/librdkafka$ ldd src/librdkafka.so
	linux-vdso.so.1 =>  (0x00007ffeae3f5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f69f963f000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f69f9425000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f69f8fe0000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f69f8dc8000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f69f8b5f000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f69f8943000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f69f873b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f69f8372000)
	/lib64/ld-linux-x86-64.so.2 (0x00005580ff698000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f69f816d000)
ubuntu:~/src/librdkafka$ dpkg -S /usr/lib/x86_64-linux-gnu/libsasl2.so.2
libsasl2-2:amd64: /usr/lib/x86_64-linux-gnu/libsasl2.so.2
ubuntu:~/src/librdkafka$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
