### ISSUE TITLE
Add support to libsasl2-2

### ISSUE THREAD

**Issue by ValerioSevilla** [edenhill/librdkafka#1189]
Related to [Compilation issue when SASL not enabled](https://github.com/edenhill/librdkafka/issues/1185#issuecomment-296621571).

When the library is configured, it checks for the availability of some libraries. Among them, [it checks whether or not libsasl(2)(-dev) is available](https://github.com/edenhill/librdkafka/blob/master/configure.librdkafka#L71), and if none of them is available, SASL is disabled in compilation time.

[Heroku currently includes libsasl2-2 in their machines](https://devcenter.heroku.com/articles/stack-packages), which means it is not directly possible to enable SASL in librdkafka on Heroku. As @edenhill [suggested](https://github.com/edenhill/librdkafka/issues/1185#issuecomment-295361032), an option would consist of trying to install libsasl2-dev (Heroku use Ubuntu machines). I achieved this by using [heroku-buildpack-apt](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt) to install libsasl2-dev before the compilation of node-rdkafka when deploying the application, but then another issue arises: a linker error.

`SOLINK_MODULE(target) Release/obj.target/node-librdkafka.node
/usr/bin/ld: /tmp/build_eeb44c8ffb7664e68ad622ff97e5082a/.apt/usr/lib/x86_64-linux-gnu/libsasl2.a(client.o): relocation R_X86_64_PC32 against symbol 'sasl_client_add_plugin' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/node-librdkafka.node] Error 1`

Apparently, libsasl2-dev comes from [APT](https://wiki.debian.org/Apt) without [PIC](https://en.wikipedia.org/wiki/Position-independent_code).

Ultimately, all of this means it is impossible, or at least extremely complicated, to use this library within Heroku _at least with SASL_, which in turn affects the [node-rdkafka](https://github.com/Blizzard/node-rdkafka) library. That's why I think it is really important to update the library configuration to consider libsasl2-2 as well.

Thanks.

**Comment by edenhill** [comment]
I believe this might be an issue with how node-rdkafka builds librdkafka, perhaps linking libsasl2 statically which probably won't work since SASL modules are dlopen():ed and thus needs to call into libsasl2 again, requiring it to be linked dynamically for symbols to be visible.
