### ISSUE TITLE
Intermittent weird offsets with rdkafka 0.9.4 and 0.10.2 broker in 0.9.0 message mode

### ISSUE THREAD

**Issue by rthalley** [edenhill/librdkafka#1192]
Description
===========

I'm testing producing from rdkafka 0.9.4 while upgrading a broker to 0.10.2, so I have the broker in 0.9.0 message format mode.

Usually if I produce say 23 messages in a few blocks, I get what you'd expect, i.e. offsets 0 .. 22 on the broker, and the broker reports that the next offset is 23.

Sometimes I see unexpected gaps in the offset numbers.  This sequence is made up, but is like what I've seen:

0, 2, 3, 4, 5, 6, 7, 8, 16, 17, 18, 19, 20, 21, 22, 44, 45, 46, 47, 48, 49, 50, 51

but the broker will still report next offset is 23.

This causes offset storage chaos on (ungrouped) consumers because they store offsets locally and the values they get do not correspond to reality.

The offset jumps tend to correspond to gaps in transmissions, as the process doing the producing is making a burst of data every 5 seconds.

I never see this issue with rdkafka 0.9.2, nor do I see it with 0.9.4 writes to a 0.10.2 broker in 0.10.2 mode.

I'm reporting this even though I don't have a good recipe to reproduce it.  I'm not sure if this is an rdkafka issue (e.g. offsets ok on broker, but weird when printed by rdkafka) or a broker issue.

How to reproduce
================

I have yet to discover a solid replication recipe.  I will keep trying though!

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.4
 - [ ] Apache Kafka version:  0.10.2
 - [ ] librdkafka client configuration: typically snappy is on, though I've seen it with it off
 - [ ] Operating system: macOS Sierra.
 - [ ] Using the legacy Consumer  yes
 - [ ] Using the high-level KafkaConsumer  no
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka  I would if I could reproduce
 - [ ] Provide broker log excerpts  likewise
 - [ ] Critical issue   no, but it's worrisome!

**Comment by rthalley** [comment]
also, whatever is wrong is persistent, as restarting the broker or updating it to 0.10.2 message format do not fix the bad offsets when they happen

**Comment by edenhill** [comment]
Do you get the same behaviour with api.version.request=true?

**Comment by rthalley** [comment]
We always have that on.

**Comment by edenhill** [comment]
Okay.

And where do you see the weird offsets?
Producer's delivery reports?
On consumers when they consume? (what clients?)

**Comment by rthalley** [comment]
I see the weird offsets from the rdkafka (legacy) consumer.  I haven't been able to test with other consumers yet.

**Comment by rthalley** [comment]
I have more insight into this problem, though I don't know what's wrong yet.  I still see the problem with 0.9.5.

I have a topic full of large messages.  Typically 2 to 3 messages fix into a 1 meg-ish snappy compressed message set.  In this example, the starting offset is 0, and the "next offset" as reported by kafka is 27029.  The broker is 0.10.2, but in 0.9.0 message mode as part of a rolling upgrade test.

If I consume this data with an old rdkafka, 0.9.0, I get the right answers; here are examples of the fetches rdkafka requests from the broker, cut down and sanitized from full debug logging:

Fetch topic big-data [0] at offset 0
Fetch topic big-data [0] at offset 3
Fetch topic big-data [0] at offset 5
Fetch topic big-data [0] at offset 7
Fetch topic big-data [0] at offset 10
Fetch topic big-data [0] at offset 12
Fetch topic big-data [0] at offset 14
Fetch topic big-data [0] at offset 16
Fetch topic big-data [0] at offset 18
Fetch topic big-data [0] at offset 21
Fetch topic big-data [0] at offset 23
Fetch topic big-data [0] at offset 25
Fetch topic big-data [0] at offset 27
Fetch topic big-data [0] at offset 29
Fetch topic big-data [0] at offset 31
Fetch topic big-data [0] at offset 33
Fetch topic big-data [0] at offset 36
Fetch topic big-data [0] at offset 38
Fetch topic big-data [0] at offset 41
Fetch topic big-data [0] at offset 44
Fetch topic big-data [0] at offset 47
Fetch topic big-data [0] at offset 49
Fetch topic big-data [0] at offset 51
Fetch topic big-data [0] at offset 53
Fetch topic big-data [0] at offset 56
...

Now lets look at the exact same trace from 0.9.4 or 0.9.5.


Fetch topic big-data [0] at offset 0 (v2)
Fetch topic big-data [0] at offset 5 (v2)
Fetch topic big-data [0] at offset 13 (v2)
Fetch topic big-data [0] at offset 29 (v2)
Fetch topic big-data [0] at offset 61 (v2)
Fetch topic big-data [0] at offset 127 (v2)
Fetch topic big-data [0] at offset 259 (v2)
Fetch topic big-data [0] at offset 523 (v2)
Fetch topic big-data [0] at offset 1049 (v2)
Fetch topic big-data [0] at offset 2101 (v2)
Fetch topic big-data [0] at offset 4205 (v2)
Fetch topic big-data [0] at offset 8413 (v2)
Fetch topic big-data [0] at offset 16829 (v2)
Fetch topic big-data [0] at offset 33661 (v2)
Fetch topic big-data [0] at offset -1001 (v2)
Fetch topic big-data [0] at offset -1001 (v2)
Fetch topic big-data [0] at offset -1001 (v2)
Fetch topic big-data [0] at offset -1001 (v2)
Fetch topic big-data [0] at offset -1001 (v2)
Fetch topic big-data [0] at offset -1001 (v2)
Fetch topic big-data [0] at offset -1001 (v2)
Fetch topic big-data [0] at offset -1001 (v2)
Fetch topic big-data [0] at offset -1001 (v2)
Fetch topic big-data [0] at offset -1001 (v2)

Note how it more than doubles the last offset it fetched from each time; basically it's 2x + delta where delta is small like 3 or 4 typically.  It rapidly goes off the end of the topic, and once it does that (at 33661 ) the broker complains and then rdkafka is stuck fetching from the "invalid offset" and gets

Topic big-data [0] MessageSet size 0, error "Broker: Offset out of range", MaxOffset -1, Ver 2/2

errors each time.

My instinct is that rdkafka is applying some rule that would be appropriate for the 0.10.2 protocol but not the 0.9.0 protocol, or something, but I haven't dug into the code yet.  About to do so.  I have full traces that I can sanitize and/or send to you if needed.

**Comment by rthalley** [comment]
Putting the broker into 0.10.2 message mode results in the problem going away.

**Comment by rthalley** [comment]
I suspect this is related to "relative offsets" in compressed messages, as that seems to be the big difference in handling, but I have no idea whether the root cause is in rdkafka or the broker yet.

**Comment by rthalley** [comment]
Yes, it is relative offsets related.

The Kafka protocol specification says "Fetch Response v2 might either contain message format v0 or message format v1" but the code only considers the API version and not the actual message format.  So when the broker returns a v0 format message it erroneously applies relative offsets.

This patch fixed the problem, specifically the second of the two diffs.  With this change it works like 0.9.0.

```
diff -u -r old/src/rdkafka_broker.c new/src/rdkafka_broker.c
--- old/src/rdkafka_broker.c	2017-04-28 14:10:31.000000000 -0700
+++ new/src/rdkafka_broker.c	2017-04-28 14:08:32.000000000 -0700
@@ -3619,7 +3619,8 @@
 			 *       the messageset, and it also means
 			 *       we cant perform this offset check here
 			 *       in that case. */
-			relative_offsets = ApiVersion == 2;
+			relative_offsets = (ApiVersion == 2 &&
+                                            hdr.MagicByte == 1);
 
                         if (!relative_offsets &&
 			    hdr.Offset < rktp->rktp_offsets.fetch_offset)
@@ -3815,7 +3816,8 @@
 		if (outbuf) {
 			rd_kafka_q_t relq; /* Temporary queue for use with
 					    * relative offsets. */
-			int relative_offsets = ApiVersion == 2;
+			int relative_offsets = (ApiVersion == 2 &&
+                                                hdr.MagicByte == 1);
                         rd_kafka_timestamp_type_t use_tstype =
                                 RD_KAFKA_TIMESTAMP_NOT_AVAILABLE;
                         int64_t use_timestamp = 0;
```

**Comment by edenhill** [comment]
Sweet stuff!

**Comment by edenhill** [comment]
Thanks for this!
