### ISSUE TITLE
RD_KAFKA_RESP_ERR_NOT_COORDINATOR_FOR_GROUP on commit

### ISSUE THREAD

**Issue by mfontanini** [edenhill/librdkafka#1195]
Description
===========
When a broker goes down and then comes back up, synchronous commits fail with `RD_KAFKA_RESP_ERR_NOT_COORDINATOR_FOR_GROUP`. This can be easily reproduced 100% of the times by (on a single broker setup but I've seen it happen on a multi broker one as well):

* Subscribing to a topic
* Starting a producer on the same topic
* Taking the broker down
* Produce a couple of messages (this will block until the broker is back up)
* Start the broker
* The consumer gets a message, tries to commit it synchronously and the commit fails with that error

Now, this might not be a bug but I don't recall seeing this before v0.9.4. In any case, if this is not a bug then I guess the consumer should perform an exponential backoff when trying to commit messages? Or is there a better approach at fixing this?

If you need some logs I can reproduce this later today and paste them here.

How to reproduce
================
See above

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.9.4
 - [x] Apache Kafka version: 0.10.1.0
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Debug logs with debug=cgrp,protocol,broker  would be very handy, thanks!

**Comment by mfontanini** [comment]
Here are logs for debug: "all": https://gist.github.com/mfontanini/1eac3ecf303d8246dc25298680f159b2

**Comment by edenhill** [comment]
Thanks!

So the odd part is the client querying for coordinator, getting a proper response (coordinator is broker 0), then shortly after sending an offset commit to the coordinator which responds with "Not coordinator for group":

(fluff removed)
```
%7|1493479529.677|RECV|rdkafka#consumer-1| [thrd:kafka-vm:9092/bootstrap]: kafka-vm:9092/0: Received GroupCoordinatorResponse (v0, 20 bytes, CorrId 56, rtt 2.74ms)
%7|1493479529.677|CGRPCOORD|rdkafka#consumer-1| [thrd:main]: kafka-vm:9092/0: Group "some_consumer" coordinator is kafka-vm:9092 id 0

...500ms later..

%7|1493479530.182|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "some_consumer" received op OFFSET_COMMIT (v0) in state up (join state started, v4 vs 0)
OffsetCommitRequest (v1, 122 bytes @ 0, CorrId 59)
%7|1493479530.333|RECV|rdkafka#consumer-1| [thrd:kafka-vm:9092/bootstrap]: kafka-vm:9092/0: Received OffsetCommitResponse (v1, 20 bytes, CorrId 59, rtt 150.89ms)
%7|1493479530.333|COMMIT|rdkafka#consumer-1| [thrd:main]: kafka-vm:9092/0: OffsetCommit for 1 partition(s): manual: returned: Broker: Not coordinator for group
```

One possibility is that the broker 0 is elected coordinator and then for some reason some other broker is elected instead.
Is there anything in the broker logs that can be correlated with the above?

**Comment by mfontanini** [comment]
So I should also clarify that this is a test setup I created on a vm with a single broker so anything related to multiple brokers could be discarded.

The only thing I see in `server.log` is the following when I produce the messages (this happens even without taking the broker down).

```
[2017-05-02 19:51:15,072] ERROR [KafkaApi-0] error when handling request null (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:77)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:236)
	at kafka.server.KafkaApis$$anonfun$20.apply(KafkaApis.scala:565)
	at kafka.server.KafkaApis$$anonfun$20.apply(KafkaApis.scala:555)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:555)
	at kafka.server.KafkaApis.handleGroupCoordinatorRequest(KafkaApis.scala:702)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:78)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
```

This is interesting, as I don't see any topic with replication factor > 1:

```shell
matias@kafka-vm:~/kafka_2.11-0.9.0.1$ ./bin/kafka-topics.sh --list --zookeeper localhost:2181
__consumer_offsets
cppkafka_test1
cppkafka_test2
example
test
matias@kafka-vm:~/kafka_2.11-0.9.0.1$ ./bin/kafka-topics.sh  --zookeeper localhost:2181 --describe --topic  cppkafka_test1
Topic:cppkafka_test1	PartitionCount:3	ReplicationFactor:1	Configs:
matias@kafka-vm:~/kafka_2.11-0.9.0.1$ ./bin/kafka-topics.sh  --zookeeper localhost:2181 --describe --topic  cppkafka_test2
Topic:cppkafka_test2	PartitionCount:3	ReplicationFactor:1	Configs:
matias@kafka-vm:~/kafka_2.11-0.9.0.1$ ./bin/kafka-topics.sh  --zookeeper localhost:2181 --describe --topic  example
Topic:example	PartitionCount:3	ReplicationFactor:1	Configs:
matias@kafka-vm:~/kafka_2.11-0.9.0.1$ ./bin/kafka-topics.sh  --zookeeper localhost:2181 --describe --topic  __consumer_offsets
Topic:__consumer_offsets	PartitionCount:50	ReplicationFactor:1	Configs:segment.bytes=104857600,cleanup.policy=compact,compression.type=uncompressed
matias@kafka-vm:~/kafka_2.11-0.9.0.1$ ./bin/kafka-topics.sh  --zookeeper localhost:2181 --describe --topic  test
Topic:test	PartitionCount:1	ReplicationFactor:1	Configs:
```

Anything else you need me to try? This can be reproduced really easily. I'm using this to produce the message:

```c++
#include <cppkafka/utils/buffered_producer.h>
#include <iostream>

using namespace cppkafka;
using namespace std;

int main() {
    Configuration config = {
        { "metadata.broker.list", "kafka-vm:9092" }
    };
    BufferedProducer<string> producer(config);
    for (string payload : { "1", "2", "3" }) {
        producer.add_message(MessageBuilder("test").partition(0).payload(payload));
    }
    
    cout << "Kill kafka and press enter\n";
    cin.get();
    producer.flush();
}
```

On the consumer side, I'm using the [consumer example](https://github.com/mfontanini/cppkafka/blob/master/examples/kafka_consumer.cpp) in cppkafka.

**Comment by edenhill** [comment]
This sounds like a broker problem to me, my theory:
When you are restarting the broker (possibly with previously created topics removed?) it fails to create the __consumer_offsets topic because the default replication count of 3 can't be satisfied.
This then leaves the broker in a somewhat weird state where it thinks it is the group coordinator, but fails to perform group coordinator tasks because of under-replicated topic.

**Comment by mfontanini** [comment]
It's weird because I never saw this before v0.9.4 (which of course doesn't mean it didn't happen). I'll try this later today with other versions and report back.

**Comment by edenhill** [comment]
What version were you on before v0.9.4? There's been a bunch of fixes with regards to commit handling, coordinator lookups, etc.

**Comment by mfontanini** [comment]
I used v0.9.0, v0.9.1, v0.9.3 and finally v0.9.4. I was actually hit by a bug on commit handling a bunch of times on v0.9.3 and now I've never hit that again after updating.

**Comment by edenhill** [comment]
If you search the 0.9.4 release notes for "commit" or "cgrp" you'll find a bunch of fixes for stuff like this:
https://github.com/edenhill/librdkafka/releases/tag/v0.9.4

**Comment by mfontanini** [comment]
Yeah, that's the reason why I updated. So you're saying maybe this had always happened but rdkafka only started handling it properly on v0.9.4? That would make sense.

**Comment by mfontanini** [comment]
Closing this as it's not really an issue, I was mostly curious as to why this happened only on v0.9.4 and the explanation makes sense.
