### ISSUE TITLE
Use librdkafka on AIX (6.1) issue: No buffer space available

### ISSUE THREAD

**Issue by izhlidan** [edenhill/librdkafka#1196]
Description
===========

Librdkafka Runtime error on AIX 6.1

    OS:   AIX 6.1
    Processor:   Power 5
    GCC:   4.85 (installed by  RPM )

I build librdkafka using gcc-4.8.1 (no error):
./configure --disable-sasl --mbits=aix64 --enable-devel --disable-optimization
make

The librdkafka configurations are as follows:
batch.num.messages = "10";
queue.buffering.max.messages = "10000";
log_level = "7";

Call produce function in a loop:
while (1) {
     res = rd_kafka_produce(
         rkt_topic,
         RD_KAFKA_PARTITION_UA, RD_KAFKA_MSG_F_COPY,
         buffer, size, NULL, 0, NULL
     );
     if (res != 0) {
         ...
     }
}
    Then I run my test program it prints out error messages:
 ...
[thrd:192.168.0.139:9092/bootstrap]: 192.168.0.139:9092/0: Receive failed: No buffer space available
[thrd:192.168.0.139:9092/bootstrap]: 192.168.0.139:9092/0: Receive failed: No buffer space available

     Such error messages are randomly popped out
     Has anyone encountered such issue before? 

Here is my c code:
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/syslog.h>
#include "rdkafka.h"

void callback_logger(const rd_kafka_t* rk, int level, const char* fac, const char* buf) {
    //if (level >= LOG_WARNING) {                                                                                                                                                                                   
        printf("logger: %s\n", buf);
    //}
}

void callback_deliver(rd_kafka_t *rk, void* buf, size_t len, rd_kafka_resp_err_t err, void* opaque, void* msg) {
    if (err) {
        printf("error: %s\n", rd_kafka_err2str(err));
        printf("now-size: %d\n", rd_kafka_outq_len(rk));
    }   
}

void set_kfkcfg(rd_kafka_conf_t* cfg, const char* name, const char* value) {
    char error[512] = { 0 };
    rd_kafka_conf_res_t res;

    res = rd_kafka_conf_set(cfg, name, value, error, sizeof(error));
    if (res != RD_KAFKA_CONF_OK) {
        printf("error-cfg '%s(%s)': %s\n", name, value, error);
    }   
}

#define BROKERS  "192.168.0.139"
#define TOPIC    "test"
#define TEST_MSG "test-"
//#define MAX_MSGS 1000

int main(int argc, char** argv) {
    rd_kafka_conf_t* rk_cfg;
    rd_kafka_t*      rk_kfk;
    rd_kafka_topic_conf_t* rkt_cfg;
    rd_kafka_topic_t*      rkt_topic;

    char error[512] = { 0 };
    char buffer[1024] = { 0 };
    int cc = 0;
    size_t size;
    int ret = 0;

    rk_cfg = rd_kafka_conf_new();
    set_kfkcfg(rk_cfg, "batch.num.messages",           "10");
    set_kfkcfg(rk_cfg, "queue.buffering.max.messages", "1000");
    set_kfkcfg(rk_cfg, "log_level",                    "7");

    rd_kafka_conf_set_log_cb(rk_cfg, callback_logger);
    rd_kafka_conf_set_dr_cb(rk_cfg, callback_deliver);

    rk_kfk = rd_kafka_new(RD_KAFKA_PRODUCER, rk_cfg, error, sizeof(error));
    if (!rk_kfk) {
        printf("error-new: %s\n", error);
        rd_kafka_conf_destroy(rk_cfg);
        return 1;
    }
    rd_kafka_set_log_level(rk_kfk, LOG_DEBUG);

    if (rd_kafka_brokers_add(rk_kfk, BROKERS) == 0) {
        printf("failed to add broker: %s\n", BROKERS);
        return 1;
    }

    rkt_cfg = rd_kafka_topic_conf_new();
    rkt_topic = rd_kafka_topic_new(rk_kfk, TOPIC, rkt_cfg);
    if (!rkt_topic) {
        printf("failed to new topic: %s\n", TOPIC);
        return 1;
    }

    for (cc = 0; ; cc++) {
        size = sprintf(buffer, "%s%d", TEST_MSG, cc);
        while (1) {
            ret = rd_kafka_produce(rkt_topic, RD_KAFKA_PARTITION_UA, RD_KAFKA_MSG_F_COPY, buffer, size, NULL, 0, NULL);
            if (ret != 0) {
                printf("error-produce: %d, %s, %d, %s\n",
                    cc,
                    rd_kafka_err2str(rd_kafka_last_error()),
                    rd_kafka_outq_len(rk_kfk), buffer
                );
                rd_kafka_poll(rk_kfk, 20);
                usleep(200);
                continue;
            }

            //rd_kafka_poll(rk_kfk, 10);
            usleep(20);
            break;
        }

        //usleep(200);
    }

    rd_kafka_poll(rk_kfk, -1);
    printf("version = %s\n", rd_kafka_version_str());
    return 0;
} 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I don't have access to an AIX box so you'll need to debug this yourself.

But that error message is most likely ENOBUFS coming from recvmsg
https://www.ibm.com/support/knowledgecenter/ssw_aix_61/com.ibm.aix.commtrf2/recvmsg.htm

It could be the number of iovecs (iov_len) or size of the iovecs buffers,
or maybe a you need to adjust the receive.buffer size in librdkafka


Den 29 apr. 2017 9:45 fm skrev "izhlidan" <notifications@github.com>:

**Comment by izhlidan** [comment]
Yes, it is ENOBUFS coming from recvmsg.
I have adjust the AIX's receive buffer size to 262088 and call getsockopt() to get the attribute in librdkafka like this:
	optlen = sizeof(buf_size);
	if (getsockopt(rktrans->rktrans_s, SOL_SOCKET, SO_RCVBUF, &buf_size, &optlen) != 0) { 
	    printf("Failed to get recev buffer size: %s\n", strerror(errno));
	} else {
	    printf("buffer size %d\n", buf_size);
	}
I got the result:  buffer size 262088
But error msg "No buffer space available" is still printed out.

Another confusion:
Why do not rdkafka reconnect the kafka brokers after the error occurred?

**Comment by izhlidan** [comment]
Do you mind we give you access to the AIX server and ask you to help us debug this issue?

Your help is much appreciated.

**Comment by izhlidan** [comment]
We had new findings. The function rd_kafka_buf_new() (defined in rdkafka_broker.c) returns a NULL pointer.

    The call stack is:
    malloc()
    rd_malloc()
    rd_kafka_buf_new()
    rd_kafka_broker_produce_toppar()
    rd_kafka_toppar_producer_serve() 
if rd_kafka_conf_set(rk_cfg, "batch.num.messages", "10000", NULL, 0); is called.

However, we did not figure out the root cause.

**Comment by edenhill** [comment]
Do you have any memory constraints in place for the process? (e.g., ulimit)

librdkafka relies on malloc() being optimistic and always succeeding (which is true for most modern operating systems), I dont know if this is the case for AIX.

Can you check how large of a buffer it tried to allocate?
Does it help to decrease batch.num.messages?
