### ISSUE TITLE
Unable to set opaque pointer for consumer callback in c++ code 

### ISSUE THREAD

**Issue by logsplitter11** [edenhill/librdkafka#1197]
Description
===========
Trying to set opaque pointer for c++ callback on consumer.  test code is based on the sample `rdkafka_consumer_example.cpp` code

In the doc it appears I need to use something like this

`rd_kafka_conf_set_opaque(conf, this)`

this seems to be in the c interface.

But I seem to be unable to find the right function from any where in the c++ code base.

As a side question, does the consumer call back run async, ie will it start a process for each message as they are received?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [v0.9.5.x ] librdkafka version (release number or git tag):
 - [ Latest] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ Linux] Operating system:
 - [ No] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The C++ does not expose the opaque pointer, you should instead instantiate a sub-class of the callback class in question and pass it to Conf::set()

Here's an example DeliveryReportCb:
https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.cpp#L127
