### ISSUE TITLE
Per-message timeouts

### ISSUE THREAD

**Issue by CasperLiu** [edenhill/librdkafka#1198]
Description
===========
Hi librdkafka owners, 

I know we can use below statements to set a topic's property before producing messages to a certain topic.

        char errstr[512];
        *topic_conf = rd_kafka_topic_conf_new();
        if(rd_kafka_topic_conf_set(*topic_conf, "message.timeout.ms", timeValue, errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK)
        {
               // print error message
        }

After the librdkafka in producer mode has started sending messages to certain topics, how can I dynamically update a topic property, such as "message.timeout.ms"?
In short, can librdkafka support updating a topic's property dynamically after producing has started? 

Thanks a lot!

How to reproduce
================

This is a consulation.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
v0.9.4
 - [ ] Apache Kafka version: 
Latest version of Kafka.
 - [ ] librdkafka client configuration:
Producer mode
 - [ ] Operating system:
Redhat
 - [ ] Using the legacy Consumer
Only producer mode is used.
 - [ ] Using the high-level KafkaConsumer
Only producer mode is used.
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue
This is a critial issue.

**Comment by edenhill** [comment]
Configuration is immutable after use

Den 3 maj 2017 14:06 skrev "CasperLiu" <notifications@github.com>:

**Comment by qiuyuzhe** [comment]
Thanks for your reply!
That means topic configuration cannt be modified aftet producing has been started.

Is there any workaround to update topic property after producing started, such as destroy all topics, but keep rk left, then create all the topics with the new topic property? If above workarond is possible, is there any risk?
Thanks a lot!

**Comment by qiuyuzhe** [comment]
Thanks for your reply!
That means topic configuration cannt be modified aftet producing has been started.

Is there any workaround to update topic property after producing started, such as destroy all topics, but keep rk left, then create all the topics with the new topic property? If above workarond is possible, is there any risk?
Thanks a lot!

**Comment by edenhill** [comment]
That is not possible.

Can you explain your use case?

Den 3 maj 2017 15:33 skrev "qiuyuzhe" <notifications@github.com>:

**Comment by qiuyuzhe** [comment]
Hi,
In our case, we need to update certain timer properties of topics per runtime value change by user(for eample, user set a value on a GUI, then the value is passed into a process using librdkafka ).

Details:  librdkafka only works in producer mode, before producing messages to brokers, we set a value for message.timeout.ms property of all the available topics.
Then we start sending to brokers.
If user wants to change above timer, he can set a new value, and our process(who calls librdkafka) will need to update the librdkafka timer without restart our process.

So what is the correct step to call APIs to implement the need? Thanks a lot!

**Comment by edenhill** [comment]
I see.
That use-case is currently not supported.
Instead of making the configuration mutable, which is a big change, it might be better to add a produce-option to specify the timeout per-message.
This way you can pass whatever message timeout the GUI has set for each produce call.

Would that work?

**Comment by qiuyuzhe** [comment]
This is a good direction! We would investigate this solution.
Could you please tell us what is the proper API list to add a produce-option to specify the timeout per-message? Or do you have any demo source code for reference on librdkafka github?

Thanks a lot!

**Comment by qiuyuzhe** [comment]
HI owners,

Is there any API list to add a produce-option to specify the timeout per-message?
Thanks a lot!
