### ISSUE TITLE
_GNU_SOURCE compile macro should be added in rdkafka_int.h

### ISSUE THREAD

**Issue by fieldsplum** [edenhill/librdkafka#1200]
Description
===========
Hi edenhill,
In rdkafka_int.h, 
```c
#ifndef _MSC_VER
#define _GNU_SOURCE  /* for strndup() */
#include <syslog.h>
#else
typedef int mode_t;
#endif
```
I think the code above should be changed to 
```c
#ifndef _MSC_VER
#ifndef _GNU_SOURCE
#define _GNU_SOURCE  /* for strndup() */
#endif
#include <syslog.h>
#else
typedef int mode_t;
#endif
```

If some projects have already used "_GNU_SOURCE", and they want to use Kafka, include "rdkafka_int.h", there will be some compile problem.

What's your opinion?

How to reproduce
================
Nothing

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):  0.9.5
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [X] Operating system: Linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is usually only a problem if defines are redefined with a different value.
From what I understand _GNU_SOURCE shouldn't be defined to a value, just defined.
Is your code setting _GNU_SOURCE to a specific value? If so, what? And why? :)

> Macro: _GNU_SOURCE
> If you define this macro, everything is included: ISO C89, ISO C99, POSIX.1, POSIX.2, BSD, SVID, X/Open, LFS, and GNU extensions. In the cases where POSIX.1 conflicts with BSD, the POSIX definitions take precedence.

https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html

**Comment by fieldsplum** [comment]
I didn't define _GNU_SOURCE with a value. Some  guy used "-D_GNU_SOURCE" in Makefile. I will modify it.

But I still think _GNU_SOURCE compile macro should be used in rdkafka_int.h as rd.h. Because somebody may write code like:
```c
#include "rd.h"
#include "rdkafka_int.h"
```

**Comment by edenhill** [comment]
I'm not sure why you would want to specify -D_GNU_SOURCE when compiling a foreign project, it is bound to break stuff. The project itself defines what compile feature  flags it needs to set.

**Comment by fieldsplum** [comment]
You're right. It's a historical reason. 
The modification I want in rakafka_int.h is not a bad idea. :)

**Comment by edenhill** [comment]
Might not be a bad idea, generally speaking, but it is not needed :)
(feel free to file a PR if you want to fix it)
