### ISSUE TITLE
 rdkafka_queue.c:432:rd_kafka_q_serve: assert: !*"op not handled" ***

### ISSUE THREAD

**Issue by rakytan** [edenhill/librdkafka#1203]
Description
===========
*** rdkafka_queue.c:432:rd_kafka_q_serve: assert: !*"op not handled" ***
rd_kafka_t 0x116d2c0: rdkafka#consumer-2
 producer.msg_cnt 0 (0 bytes)
 rk_rep reply queue: 0 ops
 brokers:
 rd_kafka_broker_t 0x116e180: :0/internal NodeId -1 in state UP (for 25.855s)
  refcnt 2
  outbuf_cnt: 0 waitresp_cnt: 0
  0 messages sent, 0 bytes, 0 errors, 0 timeouts
  0 messages received, 0 bytes, 0 errors
  0 messageset transmissions were retried
  0 toppars:
 rd_kafka_broker_t 0x116eac0: 10.95.20.160:9092/0 NodeId 0 in state UP (for 25.854s)
  refcnt 5
  outbuf_cnt: 0 waitresp_cnt: 1
  9 messages sent, 667 bytes, 0 errors, 0 timeouts
  8 messages received, 2630 bytes, 0 errors
  0 messageset transmissions were retried
  1 toppars:
   test [0] leader 10.95.20.160:9092/0
    refcnt 30
    msgq:      0 messages
    xmit_msgq: 0 messages
    total:     0 messages, 0 bytes
 cgrp:
  test-consumer-group in state up, flags 0x10
   coord_id 0, managing broker 10.95.20.160:9092/0
  toppars:
   test [0] in state active
 topics:
  test with 1 partitions, state exists, refcnt 3
   test [-1] leader none
    refcnt 1
    msgq:      0 messages
    xmit_msgq: 0 messages
    total:     0 messages, 0 bytes
   desired partitions:

Metadata cache with 4 entries:
  __consumer_offsets (inserted 25854ms ago, expires in 874145ms, 50 partition(s), valid)
  my-replicated-topic2 (inserted 25854ms ago, expires in 874145ms, 1 partition(s), valid)
  my-replicated-topic (inserted 25854ms ago, expires in 874145ms, 1 partition(s), valid)
  test (inserted 2ms ago, expires in 899997ms, 1 partition(s), valid)
Aborted

How to reproduce
================

when producer closed，this issue is happend

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 
 - [x] Apache Kafka version: kafka_2.11-0.9.0.1
 - [x] librdkafka client configuration:laster verseion
 - [x] Operating system: linux
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rakytan** [comment]
@edenhill

**Comment by rakytan** [comment]
。。

**Comment by edenhill** [comment]
What was the problem?
