### ISSUE TITLE
librdkafka 32 bit library giving few errors while linking

### ISSUE THREAD

**Issue by guruprasadkk** [edenhill/librdkafka#1204]
Hi Edenhill,

    I have built librdkafka 0.9.5 and I tried to link it with my application. I got the below error

**/usr/bin/ld: skipping incompatible ../../../lib/linux_mysql/librdkafka++.so when searching for -lrdkafka++**

Then I came to know that my application is built for 32 bit so it is not recognizing this librdkafka library.
My first question, is there any way I can make it work?

I did not get any solution, so I built librdkafka for 32 bit by changing few makefiles by adding the option -m32. I am successfully able to build the .so's. But when I try to link it with my application It is throwing me following linker errors. 

I have written simple producer consumer just to cross check these errors there also I got the same errors I am not facing any linker errors with the 64 bit librdkafka libraries and producer consumer communication is happening properly. But my existing application is on 32 bit so I cannot use 64 bit librdkafka library.

Can you please help me in resolving these errors.

Following is the error.
**/usr/bin/ld: warning: libstdc++.so.6, needed by /home/gkk/kafkatest//librdkafka++.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcrypto.so.10, needed by /home/gkk/kafkatest/m32libs//librdkafka.so.1, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libssl.so.10, needed by /home/gkk/kafkatest/m32libs//librdkafka.so.1, not found (try using -rpath or -rpath-link)
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_connect'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `operator new[](unsigned int)@GLIBCXX_3.4'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_M_destroy(std::allocator<char> const&)@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `CRYPTO_set_locking_callback'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `operator delete(void*)@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_ctrl'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_load_error_strings'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `X509_STORE_set_flags'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_CTX_use_certificate_chain_file'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_get_peer_certificate'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::_List_node_base::hook(std::_List_node_base*)@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_free'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `vtable for __cxxabiv1::__class_type_info@CXXABI_1.3'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `__cxa_end_catch@CXXABI_1.3'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `__cxa_rethrow@CXXABI_1.3'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*, unsigned int)@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_CTX_set_default_passwd_cb_userdata'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_empty_rep_storage@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_CTX_new'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_get_verify_result'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_read'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_set_fd'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `X509_verify_cert_error_string'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::ios_base::Init::Init()@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `CRYPTO_num_locks'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_CTX_load_verify_locations'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `__gxx_personality_v0@CXXABI_1.3'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::ios_base::Init::~Init()@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSLv23_client_method'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `operator delete[](void*)@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_CTX_use_PrivateKey_file'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_library_init'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_CTX_set_default_passwd_cb'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `CRYPTO_set_id_callback'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_do_handshake'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_CTX_set_cipher_list'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_new'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_write'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_CTX_get_cert_store'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `__dynamic_cast@CXXABI_1.3'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `X509_free'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)@GLIBCXX_3.4'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `vtable for __cxxabiv1::__si_class_type_info@CXXABI_1.3'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `ERR_error_string_n'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::__throw_length_error(char const*)@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_shutdown'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `__cxa_begin_catch@CXXABI_1.3'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `vtable for __cxxabiv1::__vmi_class_type_info@CXXABI_1.3'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `__cxa_pure_virtual@CXXABI_1.3'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned int, std::allocator<char> const&)@GLIBCXX_3.4'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `operator new(unsigned int)@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_CTX_ctrl'
/home/gkk/kafkatest//librdkafka++.so: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)@GLIBCXX_3.4'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_get_error'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `SSL_CTX_free'
/home/gkk/kafkatest/m32libs//librdkafka.so.1: undefined reference to `ERR_get_error_line_data'**

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):  librdkafka-0.9.5
 - [ ] Apache Kafka version: kafka_2.10-0.10.2.1
 - [ ] librdkafka client configuration: 
 - [ ] Operating system: Oracle linux 64 bit

Regards,
Guru.

**Comment by edenhill** [comment]
You'll need 32 bit libraries for librdkafka's dependencies as well, such as openssl.  (these are usually called libssl-dev:i386 or similar on Debian-based distros)

**Comment by guruprasadkk** [comment]
Thank you very much for your quick reply. 
Can you also please tell me how to get these so's??

**Comment by edenhill** [comment]
Install the 32-bit versions of OpenSSL and zlib.
Your Linux vendor should have such packages available for you.

**Comment by guruprasadkk** [comment]
Thank you very much. I will try and let you know the results.
