### ISSUE TITLE
consumer remains down always 

### ISSUE THREAD

**Issue by chetandev** [edenhill/librdkafka#1205]
Description
===========
When kafka servers are shut down , consumer throws a Broker Transport failure error  , But when kafka servers are up again consumer still remain in stopped state 

How to make consumer work again without restarting it manually ?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
 - [x] Apache Kafka version: 
 - [x] librdkafka client configuration:
 - [x] Operating system:
 - [x] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please fill out the checklist form.
