### ISSUE TITLE
xmit_msgq leak at shutdown

### ISSUE THREAD

**Issue by rthalley** [edenhill/librdkafka#1207]
Description
===========

If I produce in a situation where there is only one broker which is down, and then destroy my topic and then the producer, then all messages on the local message xmit queue leak.

Not leaking and having delivery callbacks run with an error (DESTROY?) would be better.

How to reproduce
================

As described above.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.4
 - [ ] Apache Kafka version: 0.10.2.0
 - [ ] librdkafka client configuration: N/A
 - [ ] Operating system: macOS
 - [ ] Using the legacy Consumer  NO
 - [ ] Using the high-level KafkaConsumer  NO
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue NO

**Comment by edenhill** [comment]
There is currently no way to forcibly expire messages in local queues, so this is behaviour is according to design.

There's a feature request here:
https://github.com/edenhill/librdkafka/issues/990#issuecomment-271535748

For now I suggest that you decrease message.timeout.ms and call flush() to wait for message expiry..

**Comment by edenhill** [comment]
dup of #990
