### ISSUE TITLE
topic creation

### ISSUE THREAD

**Issue by lathakris** [edenhill/librdkafka#1209]
Description
===========
Is it possible to create a topic when auto create is disabled. I want to do this before subscribing. I tried using 'rd_kafka_topic_new' (new topic handle) but does not help. 

Thank you.

How to reproduce
================
try subscribing to a topic when topic is not created and autocreate is disabled.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Currently no, but this issue tracks that feature request:
https://github.com/edenhill/librdkafka/issues/986

**Comment by lathakris** [comment]
Thank you so much for your quick response.
