### ISSUE TITLE
group ID

### ISSUE THREAD

**Issue by lathakris** [edenhill/librdkafka#1210]
Description
===========
If I do not specify a group ID, what will the library use as group ID ? I have multiple instances of the client and I want each one to get all the messages. So will the group ID be unique ?
I assume I can set the group ID with the configuration API ? Thanks.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There is no default group.id, for your use-case you'll need to generate a unique consumer id (e.g, a uuid) for each consumer.

**Comment by lathakris** [comment]
ok thank you, I will generate and set it with 'group.id' conf param for the consumer.

**Comment by lathakris** [comment]
I tried generating a unique group ID and assigning it with 
(rd_kafka_conf_set(confCons, "group.id", gid, errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK)
I do this to the consumer handle. (subscribe to topics later). 
But then I do not see the groups listed with the 
'kafka-consumer-groups.sh' command on the kafka server ? How can I make sure that the groups are created. there was no error either.

I have been using without assigning a groups ID all these days and it was working fine, all my clients used to get the same message, not sure how it worked. thanks. started seeing some missed messages and hence debugging. 

Thank you.

**Comment by edenhill** [comment]
Are you committing offsets?

**Comment by lathakris** [comment]
No I am not commiting offsets.

**Comment by lathakris** [comment]
Also, I set the 'offset.store.path' configuration. It stores the offsets in the file specified. It takes this into account though I have not specified 'offset.store.method' as a separate configuration.

**Comment by edenhill** [comment]
I believe that `kafka-consumer-groups.sh --list ..` will show your consumer group (as long as the consumer is joined), but `.. --describe` will not unless the consumer commits offsets to the broker.

**Comment by lathakris** [comment]
yes. i tried the --list command. I will check my code again to make sure I did it right. 

Also, since auto commit is true, the offsets are committed automatically right ? 
Does the 'offset.store.path' configuration assume the offset.store.method is 'file' ? (I have set only the first one)

**Comment by edenhill** [comment]
offset.store.path is ignored unless you also set offset.store.method=file

**Comment by lathakris** [comment]
ok (it creates local files in the specified path in my case and stores the offset, i will fix it to set the method as well.) 

I wrote a little test program, I set the 'group.id' in the kafka conf, I set the 'offset.store.method' to broker in the topic conf and run the consumer. I then use the list command, still does not display my group. I tried the 'describe' as well since the offsets are committed to broker, it says group does not exist.

./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --list 

Thanks you so much for your help and prompt response.

**Comment by lathakris** [comment]
I am using 0.8 librdkafka version, could that be an issue ?

**Comment by edenhill** [comment]
Yes, librdkafka 0.8 does not support consumer groups.
Upgrade to 0.9.5

**Comment by lathakris** [comment]
Thank you, I will upgrade. Is there is a server version dependency/compatability ? We are running kafka server - 0.10.2.0.

**Comment by edenhill** [comment]
Broker 0.9 or later, so you're fine

Den 16 maj 2017 9:04 em skrev "Latha Krishnamurthi" <
notifications@github.com>:

Thank you, I will upgrade. Is there is a server version
dependency/compatability ? We are running kafka server - 0.10.2.0.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/edenhill/librdkafka/issues/1210#issuecomment-301882919>,
or mute the thread

**Comment by lathakris** [comment]
I have upgraded to 0.9.5 and setting a unique consumer group using "group.id" and also set the "offset.store.method" to broker using the 'rd_kafka_conf_set' configuration APIs for the consumer.
The consumer is receiving the messages without any problems.
Now I am using the 'kafka-consumer-groups.sh '
1. --list does not display the consumer group
2. --describe with the group ID, displays the group but does not have the complete information. The 'read' and 'write' pointers are incrementing though.

Please see the output below (run 2 times to see the read/write pointers move after consumption). Am I missing something ? Thank you.
=======>>>>>>
root@kafka-latha-master-um:/opt/kafka/bin# ./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --group cc-17-2 --describe
Note: This will only show information about consumers that use the Java consumer API (non-ZooKeeper-based consumers).

Consumer group 'cc-17-2' has no active members.

TOPIC                          PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG        CONSUMER-ID                                       HOST                           CLIENT-ID
v1.chassis.2.init.config       0          70              70              0          -                                                 -                              -

=======>>>>>>
root@kafka-latha-master-um:/opt/kafka/bin# ./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --group cc-17-2 --describe
Note: This will only show information about consumers that use the Java consumer API (non-ZooKeeper-based consumers).

Consumer group 'cc-17-2' has no active members.

TOPIC                          PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG        CONSUMER-ID                                       HOST                           CLIENT-ID
v1.chassis.2.init.config       0          72              72              0          -                                                 -                              -

**Comment by edenhill** [comment]
And you are running kafka-consumer-groups.sh while the client is running?

**Comment by lathakris** [comment]
yes.

**Comment by jiayunwei** [comment]
I met the problem too,the consumer is receiving the messages without any problems.Now I am using the 'kafka-consumer-groups.sh ' display no active members;

**Comment by june6868** [comment]
Same problem too. when setting "offset.store.method" to broker, --list command shows the comsumer group,but setting "offset.store.method" to file, it not.

**Comment by edenhill** [comment]
offset.store.method=file uses local files for offset commits, which means no offsets will be committed to the brokers, and thus not be visible by consumer-groups.sh
