### ISSUE TITLE
Random crash on IBM AIX system

### ISSUE THREAD

**Issue by asharma339** [edenhill/librdkafka#1211]
Description
===========
I'm running a test which publishes and subscribes to a Kafka topic. On running this test 5-7 times on IBM, it crashes once. Same test works always on Solaris and Linux. I have crash stack:

![pic1](https://cloud.githubusercontent.com/assets/22985349/26010962/0e5400ec-371d-11e7-9dc5-97e9ffece06d.PNG)

Crash happens due to following assertion failure:
`rdkafka_op.c:308:rd_kafka_op_destroy: assert: !*"rd_kafka_op_cnt < 0" `

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.4
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system: AIX ibm
 - [ ] Using the legacy Consumer: Yes
 - [ ] Using the high-level KafkaConsumer: No
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Forgive my ignorance, but what exactly is "IBM" in this context? IBM z/OS?

**Comment by asharma339** [comment]
uname running on system
$ uname -a
AIX ibm1 1 7 00F85A984C00 powerpc 00F85A984C00 AIX

**Comment by edenhill** [comment]
Thank you.

AIX is currently not a supported platform, meaning that we're very happy if you use librdkafka on AIX but you can't expect us to be able to sort out these types of issues easily, instead you'll need to rely on your own powers or the community to help out.
Search the librdkafka issues for AIX and see if you can contact any of the previous AIX users and share your experiences.

**Comment by asharma339** [comment]
OK Thanks..I know that AIX is not supported platform. I filed here, just to gain any insight or any feedback, which may be obvious and I may be overlooking. There is one more crash on AIX which happens when client cannot reach Kafka. I think these reports will serve just some potential user if we find any fix or workaround, which we can put here.

**Comment by edenhill** [comment]
Is this reproducible with the example tools?

**Comment by asharma339** [comment]
I will test and let you know. I will also file second report for other stack which I mentioned earlier.
