### ISSUE TITLE
Any possibility if few of the Kafka Produced Messages get lost and does not gets consumed...

### ISSUE THREAD

**Issue by abhit011** [edenhill/librdkafka#1213]
Set up Description...

The entire setup is on Windows.

My Kafka Cluster has 6 brokers, 4 on one machine and 2 on other machine.
It has two Kafka Topics with partition size 50 each, and replication factor of 3.

My partition logic selection: like for each message (its unique ID % 50) , and then calling Kafka producer API to route a specific message to a particular topic partition .
**RdKafka::ErrorCode resp = m_kafkaProducer->produce(m_kafkaTopic,(unique ID % 50),RdKafka::Producer::RK_MSG_COPY /* Copy payload */,ptr,size,&partationKey,NULL);**
I am using various process to produce messages to Kafka to these 2 topics.
On an average there are around 48 threads in each process that's calling

m_kafkaProducer->produce(m_kafkaTopic,partition,RdKafka::Producer::RK_MSG_COPY / Copy payload /,ptr,size,&partationKey,NULL);

My Kafka Producer configuration

if (m_ex_event_cb == NULL)
return -1;
m_KafkaConf->set("event_cb", m_ex_event_cb, errstr);		
t_KafkaConf->set("produce.offset.report", "true", errstr);
t_KafkaConf->set("request.required.acks", "1", errstr);

And I have just one KafkaConsumer, which is going to consume all the kafka messages. Currently I have restricted that to just 8 threads. I mean 8 threads in my kafka consumer are using to consumer messages and then doing the actions.
Kafka Consumer setting

t_KafkaConf->set("auto.offset.reset", "latest", errstr);
t_KafkaConf->set("enable.auto.commit", "true", errstr);
t_KafkaConf->set("auto.commit.interval.ms", "1000", errstr);
m_KafkaConf->set("rebalance_cb", m_ex_rebalance_cb, errstr);	
m_KafkaConf->set("metadata.broker.list", m_brokersAddress, errstr);

I am using 0.9.2 librdkafka for Producer and Consumer.

Each produced message is of 96 bytes each.

Any possibility if few of the Kafka Produce Messages gets dropped and never gets consumed by kafka consumer... If yes how to debug those and what I need to do to catch those ? 

And my server.properties is

broker.id=0
port:9093
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
offsets.retention.minutes=360
num.partitions=1
num.recovery.threads.per.data.dir=1
log.retention.minutes=360
log.segment.bytes=52428800
log.retention.check.interval.ms=300000
log.cleaner.enable=true
log.cleanup.policy=delete
log.cleaner.min.cleanable.ratio=0.5
log.cleaner.backoff.ms=15000
log.segment.delete.delay.ms=6000
auto.create.topics.enable=false

Abhi

**Comment by edenhill** [comment]
Two things:
 * register a delivery report callback, you'll get one call per message produced telling you if the message was successfully produced or not.
 * with acks=1 you risk the loss of messages if replicas are unavailable and the leader broker goes down  before flushing messages to disk. You might want to consider acks=all

Apart from that there should be no case where messages are lost.

**Comment by abhit011** [comment]
Yes I have subscribed for dr_cb in my kafka producer.. What would be the ideal failure case , looks like
```
void dr_cb(RdKafka::Message &message) {
			
			if (!message.key())
				kafka_logger2->kafkaCb() << "Bytes : " << message.len();
			
			if (message.key()){
				kafka_logger2->kafkaCb() << "[Key: " << *(message.key()) 
										 << "] Bytes:"
										 << message.len()
										 << ",Offset: " << message.offset()
										 << ",Topic: "  << message.topic_name()
										 << ",Result: " << message.errstr();
			}
		}

```
Usually for Success case the message.errstr() returns "Success", what comes in case of failure ?

ack=all might delay my consuming process ?

**Comment by edenhill** [comment]
You should check `message.err()` for errors, if it returns anything but ERR_NO_ERROR it means the message failed to produce.
`message.errstr()` must not be used on the producer, only on the consumer (yes, this needs to be documented)

`ack=all` will not delay consumtion (since consumers are only consuming fully produced messages)

**Comment by edenhill** [comment]
You should use the delivery report callback to find out if a message was delivered or not.

**Comment by abhit011** [comment]
The idea is in case for failures which is 

```
if(message.err() != ERR_NO_ERROR){
kafka::KafkaMsgObject *object = (kafka::KafkaMsgObject *)message.payload();

}
```
Few Questions..
1. Who will take care of freeing the object memory ? or when it will get freed ?
2. Should i call the same produce API again if it fails. 
3. I am thinking of actually in some other layer other than Kafka, may be some cachelayer where i will dump such messages.

**Comment by edenhill** [comment]
You specify with the msgflags how you wanted the payload memory handled, see here:
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1858

librdkafka will automatically retry temporary produce errors, so when you get a failure in your delivery report callback it is pretty certain that it is a semi-permanent error.

See here for more info:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-reliability

**Comment by abhit011** [comment]
Lets say at any time, there are 100 produce() messages gets called, and now I call close program.... Do I literally need to wait for all those 100 already produced messages to successfully delivered to Kafka to make sure that all data transferred. Does there exist any API ?

abhi

**Comment by edenhill** [comment]
Yes, there's currently no API to purge messages from queue.
You  can adjust the maximum queueing time by `message.timeout.ms` though

**Comment by abhit011** [comment]
Can it be taken in your backlog ?

**Comment by edenhill** [comment]
Yes, here is the issue to track: https://github.com/edenhill/librdkafka/issues/990

**Comment by abhit011** [comment]
@edenhill  Has it been completed ?

Abhi

**Comment by edenhill** [comment]
Sorry no, just closed this duplicate
