### ISSUE TITLE
How to do a custom SASL authentication

### ISSUE THREAD

**Issue by cpuchakayaka** [edenhill/librdkafka#1214]
Description
===========
We have a use case of polyglot Kafka clients connecting to our Kafka infrastructure. We are not sure we want go with Kerberos route. We can use SASL/PLAIN but want to see if can do something better. One of the ideas we have is to use OAUTH, either using SASL with OAUTH (https://tools.ietf.org/html/rfc7628) or passing OAUTH tokens thru SASL/PLAIN mechanism or do GSSAPI with OAUTH (https://tools.ietf.org/html/draft-mills-kitten-sasl-oauth-04) . If we decide to pass OAUTH tokens using SASL/PLAIN, we can easily do this in the java clients.  Wondering how hard would it be introduce something like that here (as the confluent python and go are dependent on it), where a client sends oauth token as the password in the SASL/PLAIN mechanism. There are some outstanding questions regarding how would the client refresh the oauth token or would the initial authentication of the oauth token is enough in the SASL/PLAIN mechanism.

@edenhill would like to understand the complexity of implementing something like this from your perspective to do either a custom SASL mechanism or pass oauth tokens as part of SASL/PLAIN.

Will it be possible to call a callback for password/token?

**Comment by edenhill** [comment]
It sounds like you want a callback to provide the SASL PLAIN (or SCRAM) username/password which would be fairly easy to implement (with some threading caveats that needs detailed attention).

However, the Kafka protocol currently does not support re-authentication on the same connection, all authentication takes place at the initial phase of a connection.

**Comment by cpuchakayaka** [comment]
Wondering how that would look like for the bindings that use librdkafka, like python and go which use this?, Not to familiar with python or go.  We don't want fork out from librdkafka or official confluent libraries, if we decide to do a PR for this will you accept it?

**Comment by edenhill** [comment]
I'm happy to review a design overview and we can discuss it from there.
It would be preferable if the interface somewhat mimiced the Java client's, while staying true to C.
