### ISSUE TITLE
How to use rd_kafka_queue_poll_callback

### ISSUE THREAD

**Issue by kparadkar** [edenhill/librdkafka#1215]
@edenhill 
Event interface description in rdkafka.h says- The event API provides an alternative pollable non-callback interface to librdkafka's message and event queues

Description of rd_kafka_queue_poll_callback() api says-
Poll a queue for events served through callbacks

Shouldnt queue only contain the events which doesnt have a callback? in that case how does the api even work? How/when should it be used?

Could you please explain this api ?

**Comment by edenhill** [comment]
Queue ops may be served by the application either through callbacks (e.g., rd_kafka_queue_poll_callback()) or by returning the ops as events (rd_kafka_queue_poll()).

It is up to you to decide which interface suits you better.
E.g., in some language bindings (such as Go) it is problematic to have C callbacks, so the event API was added to alleviate that.

**Comment by edenhill** [comment]
See this test for an example use:
https://github.com/edenhill/librdkafka/blob/master/tests/0039-event.c

or the Confluent Go client:
https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/event.go#L119

**Comment by kparadkar** [comment]
@edenhill What determines if its a queue op or an event op? 

I see following EVENT ops - 
RD_KAFKA_EVENT_DR, RD_KAFKA_EVENT_FETCH, RD_KAFKA_EVENT_ERROR, RD_KAFKA_EVENT_ERROR, RD_KAFKA_EVENT_REBALANCE, RD_KAFKA_EVENT_OFFSET_COMMIT,
RD_KAFKA_EVENT_LOG

Are their corresponding OPs called as Queue ops? RD_KAFKA_OP_DR etc..

**Comment by edenhill** [comment]
The internal ops are all the same, depending on how you serve the queue they will be dispatched as callbacks or returned as events.

This is the full ops list (most of them are internal):
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_op.h#L68

Which map to events here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_event.h#L35

and callbacks here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L2450

**Comment by kparadkar** [comment]
Thanks @edenhill! 
So if I am using C language application I could continue using callback mechanism using rd_kafka_consumer_poll or rd_kafka_poll and would not have any use for event APIs is that statement right?

**Comment by edenhill** [comment]
Correct

**Comment by kparadkar** [comment]
@edenhill what is the problem with C callbacks in go language? Could you point me to the bug if any?

**Comment by kparadkar** [comment]
@edenhill The reason I ask this is, why is there a need of separate api, couldn't it be achieved by 'not configuring' the callback at all? what am I missing here?

**Comment by edenhill** [comment]
Sorry for dropping the ball on this, is this still a concern?

**Comment by kparadkar** [comment]
I understand and am able to use rd_kafka_queue_poll in my test code to get events, but if events interface was introduced to provide alternative pollable non-callback interface, then what purpose  rd_kafka_queue_poll_callback serves? I can use rd_kafka_queue_poll_callback in my test but I am having trouble understanding why I should use it when I can simply call rd_kafka_poll/ consumer_poll ?

**Comment by edenhill** [comment]
queue_poll..() is to be used when the main queue (rd_kafka_poll() or consumer queue (rd_kafka_consumer_poll()) is redirect to a custom queue.
