### ISSUE TITLE
What is the use of Event APIs 

### ISSUE THREAD

**Issue by kparadkar** [edenhill/librdkafka#1216]
@edenhill 
I have not quiet understood the use of event interface vs callback ?

I do understand that events give you provision to 'not' have a callback and poll for event using rd_kafka_queue_poll. But isn't this similar to the regular 'poll for callback' mechanism? to get rebalance/ message/consumer message you eventually poll. Am i missing something here?

Could you please clarify the scenario when application would want to use event apis ?

**Comment by edenhill** [comment]
See #1215
