### ISSUE TITLE
message seems consume unnormal

### ISSUE THREAD

**Issue by lyk1905** [edenhill/librdkafka#1217]
Description
===========
i have two brokers, and i create a topic with 2 partitions , 1 republication
then i wrote my consumer, i tried both of Consumer and KafkaConsumer， group id is 0.
firstly, i start my consumer as a resident process, 
then i produce a message into kafka, but it is consumed twice.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
0.9.5x
 - [x] Apache Kafka version: 
0.10.2.0
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [x] Using the legacy Consumer
yes
 - [x] Using the high-level KafkaConsumer
yes
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
When you say it is consumed twice, can you elaborate?
Twice during the same run of the consumer?
are the duplicate messages having the same topic, partition and offset?

**Comment by edenhill** [comment]
Please also fill in the checklist above.

**Comment by lyk1905** [comment]
okay. i will show you the key part of consumer.
 int64_t start_offset = RdKafka::Topic::OFFSET_BEGINNING;
RdKafka::ErrorCode resp = consumer_->start(topic_, 1, start_offset);
 while(run_){
       consumer_->consume_callback(topic_, 1, timeout, &consumer_cb, &use_ccb);
 }

when it run as a resident process,  i produce one message into kafka, 
and i can see the callback method has been called twice during this time.
message is produced by 
bin/kafka-console-producer.sh --broker-list 10.241.107.161:9093,10.241.107.161:9094 --topic my-test-topic
after type some words, i type enter
then i can see the callback method has been called twice during this time.

**Comment by lyk1905** [comment]
and i have tried another way,
i used KafkaConsumer::consume(),
it dosen't work...
my kafka version is 0.10.2.0
librdkafka version is 0.9.5x
 conf_ = boost::shared_ptr<RdKafka::Conf>(RdKafka::Conf::Conf::create(RdKafka::Conf::CONF_GLOBAL));
    tconf_ = boost::shared_ptr<RdKafka::Conf>(RdKafka::Conf::Conf::create(RdKafka::Conf::CONF_TOPIC));

    tconf_->set("partitioner_cb", new TopicHashPartitionCb, err_str);
    tconf_->set("enable.auto.commit", "true", err_str);
    
    conf_->set("rebalance_cb", new mbox::KafkaRebalanceCb, err_str);
    conf_->set("group.id", "1", err_str);


    RdKafka::Conf::ConfResult rc_res = RdKafka::Conf::CONF_UNKNOWN;


    conf_->set("metadata.broker.list", brokers, err_str);
    conf_->set("partition.assignment.strategy", "roundrobin", err_str);

    conf_->set("consume_cb", new mbox::SimpleConsumerCb, err_str);
    conf_->set("event_cb", new mbox::KafkaEventCb, err_str);
    conf_->set("default_topic_conf", tconf_.get(), err_str);

**Comment by lyk1905** [comment]
(1). "AAAAAAAAAAAAAAA")B
 (2). P)B

when i consume a message,  i print the payload. each time callback called twice, and print (1) and (2),
(1) is what i send into kafka, and (2) i don't know what it is, and it is different each time.

**Comment by edenhill** [comment]
Sorry for dropping the ball on this one, please let me know if this is still an issue.
Closing for now.
