### ISSUE TITLE
Will KafkaConsumer:Subscribe method cause disturbance to topics that is not changed?

### ISSUE THREAD

**Issue by kenxxu67** [edenhill/librdkafka#1224]
Description
===========
Will KafkaConsumer:Subscribe method cause disturbance to topics that is not changed? since the partition reassignment will happen for the unsubcription and then resubscription for unchanged topics. Then this reassignment will also affect the consumers in the same group.

How to reproduce
================
From doc,

"Any previous subscription will be unassigned and unsubscribed first.

The subscription set denotes the desired topics to consume and this set is provided to the partition assignor (one of the elected group members) for all clients which then uses the configured partition.assignment.strategy to assign the subscription sets's topics's partitions to the consumers, depending on their subscription.

The result of such an assignment is a rebalancing which is either handled automatically in librdkafka or can be overriden by the application by providing a RdKafka::RebalanceCb.

The rebalancing passes the assigned partition set to RdKafka::KafkaConsumer::assign() to update what partitions are actually being fetched by the KafkaConsumer."

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
Rebalance here is group rebalancing (coordinator over consumer), not partition rebalancing on topic (over broker)
ie consumers which share the same groupId may receive data from different partition after subscribe / unsubscribe of a member of this group. This does not modify the state of the topic on brokers in any way

**Comment by kenxxu67** [comment]
Consumer group rebalancing is costly for us because the consumers will have to rebuild cache from database for the data through the newly assigned partitions. And then this work is reversed because the consumer resubscribed after unsubscribe if we are still interested in the topic. This partition rebalancing is disruptive to our consumer's normal operation and we are trying to avoid it. 

It seems not that complicated to figure out the subscription delta and only unsubscribe the topic no longer interested and subscribe to the topic that is newly added.

**Comment by edenhill** [comment]
Yes, but that is not how the Kafka group subscription model currently works so there isn't much that can be done on the client side, member assignments are atomic, not incremental.

I suggest you discuss this on the kafka-users mailing list.
