### ISSUE TITLE
When i use subscribe() to subscribe a topic that are not existing in kafka cluster, it will create the topic in kafka cluster.

### ISSUE THREAD

**Issue by meiliumeiliu** [edenhill/librdkafka#1226]
Description
===========
When i use subscribe() to subscribe a topic that are not existing in kafka cluster, it will create the topic in kafka cluster.

Could it return false when the topic doesn't exist in kafka cluster? how to configure.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ 0.10.1.0] Apache Kafka version: 
 - [ 0.9.5] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You can work around this by specifying your topic(s) as regexes, that is, to prefix them with "^".
E.g., you subscribe to your topic "analytics_501" using the string "^analytics_501$"

**Comment by edenhill** [comment]
Using regex subscription will request all topics in the cluster, while using non-regex subscription will request only the specific topics which will create them on the broker if auto.create.topics is enabled.

**Comment by meiliumeiliu** [comment]
test
