### ISSUE TITLE
Way to know librdkafka threads

### ISSUE THREAD

**Issue by aasselin-en** [edenhill/librdkafka#1227]
Description
===========
To my knowledge there is no way to know which threads are created by librdkafka.

I am in situation where a thread creates a librdkafka handle (through rd_kafka_new), this thread as some affinity already set, and Linux gives this affinity to all the threads that librdkafka creates.

I need a way to catch these creations, nicely to set correct affinities, a callback on create/destroy or a list would do.

Can I propose a patch adding this callback ?

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.4

**Comment by edenhill** [comment]
Sounds reasonable.

Do you need the create callback to be called before thread creation, or from within the newly created thread?
Same thing for destroy: after thread has been joined, or just prior to thread exit?

**Comment by aasselin-en** [comment]
I think that it would be better within the thread, I'll need the thread id to the set the affinity.
So just after creation near the start of the thread and just before destruction seems the more appropriate.

**Comment by edenhill** [comment]
We could add interceptors for that: on_thread_start() and on_thread_exit()

**Comment by aasselin-en** [comment]
yes, near the start and end of rd_kafka_thread_main. I suppose that we should provide the "rk" to these on_thread_??? functions, and call the callback from there, using a specific callback and the opaque.
I believe that a single on_thread_operation_cb with some parameter telling if we are about creation (say RD_KAFKA_THREAD_CREATION=0) or destruction (RD_KAFKA_THREAD_DESTRUCTION=1) would do the job.

**Comment by edenhill** [comment]
There are also broker threads being created, not sure if there is a need to distinguish between them, but they are much more CPU and memory heavy than the mostly idle main thread.

I'd rather see specific start/exit callbacks instead of new enums, from previous experience with API design I find it simpler to maintain a number of extra callbacks than a new enum type, as strange as it may sound :) The more combinations (e.g., callback + enum, vs multiple callbacks), the harder it is to maintain.

**Comment by aasselin-en** [comment]
ah, OK indeed, more callbacks is more liberty, each can have its own prototype if needed.
I see that there is rd_kafka_thread_name, it could interesting to provide it during these calls.
so on_thread_start_cb/on_thread_exit_cb, with internal rd_kafka_on_thread_ZZZ functions to support them, and rd_kafka_conf_set_on_thread_ZZZ_cb

I'd see their prototype as: void (*cb) (const rd_kafka_t *rk, const char *thread_name)

**Comment by f18m** [comment]
Hi,
I was going to file a ticket for this same reason: in my case I'm using librdkafka inside an app having several threads and I'm mostly interested in providing a name to Kafka threads, to be able to distinguish them in "top -H" or "gdb showthreads" commands...

So what you discussed in the last day would be a great solution for me. Regarding the API: I usually provide in my libraries the possibility for the user to specify a thread name prefix (like "kafka"); then my code adds a thread-specific identifier (e.g., "br/0" to identify first broker thread ... "br/N" to identify N-th broker thread or "reaper/0" to identify first reaper thread, etc).

**Comment by aasselin-en** [comment]
to be more coherent, i am about to call them "thread_start_cb/thread_exit_cb" as there are no "on_" prefix usually. I forgot the opaque, so the prototype is more like:
void (*cb) (const rd_kafka_t *rk, const char *thread_name, void *opaque)

**Comment by aasselin-en** [comment]
@edenhill: what would the correct place to declare and implement the interceptors ?

**Comment by edenhill** [comment]
All interceptors have the on_ prefix, see here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L3321

The benefit of using interceptors rather than a single callback is that it allows multiple callbacks to added for the same event, which is important with the use of plugins since there can be multiple plugins loaded simultaneously and librdkafka can make no assumption on what they are trying to achieve, or how.


Interceptor links:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_conf.h#L145
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_interceptor.c

**Comment by aasselin-en** [comment]
ouch, I wanted to base my code on the release that we use here (0.9.4) and everything changed, I believe that I won't be able to convince the project to use a non-released version :(

**Comment by edenhill** [comment]
librdkafka only has a single release track, there is no backporting of features to older release trains,
so it doesn't make sense to add a new feature to 0.9.4.

The master branch, with interceptors, will be released end of june.  This new feature will not make that release due to Code freeze, but it can make the next.

**Comment by aasselin-en** [comment]
I understand. I cannot wait until end of june for the current matter, so i'll do a patch here, and we'll change user code when the interceptor version is released. That's not bad it will let me more time to propose the patch.

**Comment by aasselin-en** [comment]
I understand. I cannot wait until end of june for the current matter, so i'll do a patch here, and we'll change user code when the interceptor version is released. That's not bad it will let me more time to propose the patch.

**Comment by aasselin-en** [comment]
I have coded a first draft version here. I wonder if the callback/interceptor approach can work for the thread_exit. If for some reason some rdkafka thread would stop after the user object, we'd go surely for a crash :(

**Comment by edenhill** [comment]
All threads created by librdkafka will be terminated and joined from rd_kafka_destroy(), so this should be safe.

**Comment by citrusmoose** [comment]
I also need the ability to set the affinity of threads.  I see that the ticket is closed, but I don't see any interceptors for threads?  Is there some other method that will allow me to do this?

**Comment by edenhill** [comment]
What is your use-case for setting thread affinity?

**Comment by citrusmoose** [comment]
In a system where application/thread core placement is critical.  I believe `pthread_create` can be intercepted, but that's hacky and something I'd rather not do.

**Comment by edenhill** [comment]
Okay, I think the proper way to do this is add the two new interceptors mentioned above, for thread creation and thread exit.
But since the demand is minimal it is unlikely that we'll get this on the backlog, so if you're up for it I suggest you take a stab at making a PR

**Comment by zhanghaowx** [comment]
In the latest version (v1.2.0-RC3) we now have interceptors on thread start, which is great! However, is there a way to get the internal thread from rd_kafka_t so that I can call pthread_setaffinity_np?

**Comment by edenhill** [comment]
@zhanghaowx There is not, you should use the thread_start interceptor for that.

**Comment by zhanghaowx** [comment]
@edenhill Thanks! I just realized I don't need rk to get the thread id. I should use whatever the current thread id is. After that I got everything running perfectly. Now I can change the affinity of all internal threads. I have to say the example of `0100-thread_interceptors.cpp` is really useful and saves so much time. Cheers!
