### ISSUE TITLE
How to re-consume log based on time instead of offset?

### ISSUE THREAD

**Issue by hangcun** [edenhill/librdkafka#1229]
I want to re-consume logs with message timestamp, could it be done in a consumer?

**Comment by edenhill** [comment]
Yes, you can look up the offset for a given timestamp using get_offsets_for_times() and then pass that list of partitions+offsets to assign() to start consuming at the given offset.

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1862

**Comment by edenhill** [comment]
Here's a bsearch implementation using timestamps:
https://github.com/edenhill/librdkafka/blob/master/tests/0059-bsearch.cpp#L178

**Comment by hangcun** [comment]
Do you mean rd_kafka_offsets_for_times()? I think it will help. But there is no get_offsets_for_times(),  did miss?

**Comment by edenhill** [comment]
Sorry, I meant rd_kafka_offsets_for_times()

**Comment by hangcun** [comment]
Thanks. I'm going to try.
