### ISSUE TITLE
Multiple OpenSSL initializations conflict with each other

### ISSUE THREAD

**Issue by alanbutt** [edenhill/librdkafka#1230]
Description
===========
When used OpenSSL is initialized by librdkafka.   This initialization conflicts with other libraries that also use and initialize OpenSSL.   OpenSSL is initialized by added algorithms, loading error strings, creating and setting locking objects and callbacks, etc.   OpenSSL is initialized with similar structures for other libraries.   In our case, the objects and callbacks were not compatible leading to crashes and handle leaks. 

To solve the problem I modified rd_kafka_transport.c to "skip" the OpenSSL initialization and cleanup.  This means the invoking program is responsible for initializing OpenSSL "before" librdkafka makes any use of OpenSSL.   I performed similar adjustments for the other libraries as well.

OpenSSL initialization is found in rdkafka_transport.c.   I added to my copy of the code the following:

#if WITH_SSL
static int rd_kafka_ssl_skip_initialize;	// set to !0 to skip OpenSSL initialization
void rd_kafka_set_ssl_skip_intialize(int b) {
	rd_kafka_ssl_skip_initialize = b;
}
#endif

And in rd_kafka_transport_ssl_term() and rd_kafka_transport_ssl_init()
if (rd_kafka_ssl_skip_initialize)
	return;
before the the actual initialization and cleanup.   

I do not propose that the above changes are added to the code, but it would be very nice if there were a "standard" option that would leave the OpenSSL initialization up to the calling program.

How to reproduce
================

Create an application that uses librdkafka using openssl and also includes and uses another library that uses openssl.  In our cause the application was a producer.   The application was performing direct cryptographic operations using OpenSSL and was also using libcurl.    All three uses of OpenSSL provided slightly different locking objects and callback mechanism.   When pumping data through all of these mechanism weird crashes and handle leaks will be observed.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
        Master, 0.9.5, 0.9.3
 - [x] Apache Kafka version: 
        10.1
 - [ ] librdkafka client configuration:
 - [x] Operating system: Windows, Linux
 - [x] Using the legacy Consumer
       No
 - [x] Using the high-level KafkaConsumer
      No
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue
     Crashes are always critical.

**Comment by edenhill** [comment]
Urgh, yes, this is a big problem with OpenSSL, it doesn't make it easy for multiple libraries to use it simultaneously.

We could perhaps add a configuration setting that allows an application to suppress librdkafka's SSL initialization.

**Comment by edenhill** [comment]
OpenSSL 1.1.0 fixes this.
