### ISSUE TITLE
DNS queries from kafka client library

### ISSUE THREAD

**Issue by lathakris** [edenhill/librdkafka#1232]
Description
===========
I have provided an IP address as the broker address in the client configuration. Is it still possible for the client library to do a DNS query for 'kafka' domain ? We are seeing a lot of  DNS queries go through our network for 'kafka' domain. Does this happen only when the broker is not reachable in which case it needs to figure out the alternate kafka servers ? Or does it happen in the normal operation also ?

Thanks.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka uses the standard libc resolver and will attempt to resolve the broker address on each connect attempt but no more often than `broker.address.ttl` which defaults to 1s.

**Comment by lathakris** [comment]
but would it try to resolve even if I have provided the IP address to connect (not domain name) ? I thought if we provide the IP address it can use it directly without resolving.

**Comment by edenhill** [comment]
It will not try to resolve an ip address but use it directly.
Do note though that the broker may return a hostname in its Metadata response (based on advertised.listener) to the client

**Comment by lathakris** [comment]
oh ok I guess this is what is happening because though I give the IP address we see the DNS resolution happening.

**Comment by edenhill** [comment]
Yeah, you can see what the broker returns by calling metadata(), or `kafkacat -b <broker> -L` (or `rdkafka_example -b <broker> -L`)

**Comment by lathakris** [comment]
ok let me check this. Thank you so much! Appreciate your response.

**Comment by lathakris** [comment]
Yes the broker is returning hostname and hence the issue is happening. Great! Thanks once again.
