### ISSUE TITLE
How to balance the load among partitions?

### ISSUE THREAD

**Issue by smartcat2010** [edenhill/librdkafka#1237]
I start dozens of consumer on dozens of machines, each machine has 1 consumer running. The total partition is about hundreds. Some consumer reads faster than others, so it reads newer data than other, which cause  error in my application logic. 
In another word, I hope to keep all consumers read in same speed and all partitions are consumed about same amount of messages at the same time. Is there any way to make the fastest consumer "steal" messages from partition of slow consumers'?

**Comment by treziac** [comment]
No - order in kafka is only by partition, not by topic. If you want to synchronize your consumers, you will have to implement it yourself, or review your application logic. Even with one single consumer, you wouldn't be able to receive the message in orders from a topic with multiple partitions.

If your question was "I have one consumer which has too much lag on its assigned partitions, so I want to reduce the number of partitions on this one and rebalance on other consumers" - the answer would also be no - you would need a partition.assignment.strategy different from range or roundrobin, and they don't exist for now (though I think it's possible to create a custom one in kafka for the broker, I didn't look too much at it)
