### ISSUE TITLE
Message logs are deleted unexpectedly when using rd_kafka_producev()

### ISSUE THREAD

**Issue by hangcun** [edenhill/librdkafka#1238]
Description
===========
 When i use (RdKafka::Producer)
```
  virtual ErrorCode produce (const std::string topic_name, int32_t partition,
                             int msgflags,
                             void *payload, size_t len,
                             const void *key, size_t key_len,
                             int64_t timestamp,
                             void *msg_opaque) = 0;
```
to produce message with customized timestamp, something confused happened.

When i set parameter **timestamp** with **time(NULL)** or other customized one, messages are produced indeed and stored in broker log path. However, these logs are deleted in a short time (less than 10 min) by broker, whose configuration are default whose log.retention.hours is 168.

But when i set parameter **timestamp** with **0** which  i think is equal to **time(NULL)**, these message logs will never be deleted.

Did i misunderstand the api? 

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.5
 - [ ] Apache Kafka version: 2.11-0.10.1.0
 - [ ] librdkafka client configuration: "acks=all", "api.version.request=true"
 - [ ] Operating system: Linux version 2.6.32_1-17-0-0
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
Are you using compaction?
0.10.1.0 has a bug related to this : https://issues.apache.org/jira/browse/KAFKA-4497
Corrected in later versions
This is a broker related error, if you are not in the above case, look at your broker logs for more informations

**Comment by mfontanini** [comment]
Time will return a timestamp in seconds, while rdkafka timestamps are in
milliseconds. Try multiplying the time returned by the function by 1000 and
see if the issue persists. You are basically setting a very old timestamp
on all your messages which will likely trigger a cleanup before it actually
should occur

**Comment by treziac** [comment]
Forgot about 0.10.1.0 change

> Potential breaking changes in 0.10.1.0
> 
> The log retention time is no longer based on last modified time of the log segments. Instead it will be based on the largest timestamp of the messages in a log segment.
> The log rolling time is no longer depending on log segment create time. Instead it is now based on the timestamp in the messages. More specifically. if the timestamp of the first message in the segment is T, the log will be rolled out when a new message has a timestamp greater than or equal to T + log.roll.ms

So yes, that's it. Maybe it should be added in kafka doc in an other place than breaking change

**Comment by hangcun** [comment]
@mfontanini thx, it is the cause.
