### ISSUE TITLE
consumer group does not work with legacy APIs

### ISSUE THREAD

**Issue by royliu-santiago** [edenhill/librdkafka#1239]
Description
===========
I want to use rd_kafka_subscribe with consumer legacy APIs；but it does not work.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.5
 - [x] Apache Kafka version: 0.10.0
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
Legacy consumer does not provide group support
https://github.com/edenhill/librdkafka/wiki/FAQ#what-is-a-simple-consumer
