### ISSUE TITLE
Producer does not reconnect to broker

### ISSUE THREAD

**Issue by stathisgotsis** [edenhill/librdkafka#1241]
Description
===========

I have a producer with the same code as in: rdkafka_example.cpp. The only difference is that when RdKafka::ERR__ALL_BROKERS_DOWN event is raised, I continue with the program execution, instead of exiting. What I notice is that the producer does not reconnect across broker restarts. Specifically, if some messages are queued up while broker is down, these and subsequent messages are never sent to the broker.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.8
 - [ ] Apache Kafka version: kafka_2.10-0.8.2.2
 - [ ] librdkafka client configuration:
 - [ ] Operating system: Linux Ubuntu-12 3.2.0-32-generic
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
What is the exact librdkafka version?
Do you see this problem with the latest librdkafka release (v0.9.5)?

**Comment by stathisgotsis** [comment]
librdkafka is latest of branch 0.8.
I need to work with broker 0.8, so I suppose I cannot use v0.9.5?

**Comment by edenhill** [comment]
librdkafka is backwards compatible with older brokers (broker version 0.8 and later), you should use the latest released librdkafka version.

See this:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility
