### ISSUE TITLE
Seeing no data when subscribing to topic set where some topics may not exist in broker

### ISSUE THREAD

**Issue by saheemg** [edenhill/librdkafka#1242]
Description
===========
We are not seeing ANY data when passing a vector of topics to https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1423 where one of the topics did not exist, but all other topics are active. 

How to reproduce
================
Add a topic that does not exist to the vector passed to https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1423.

Checklist
=========
Please provide the following information:

 - [x ] librdkafka version (release number or git tag): 0.9.4
 - [x] Apache Kafka version:  0.10.2.1
 - [ ] librdkafka client configuration:
 - [x] Operating system: rhel7
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That link points to subscription(), I'm guessing you mean subscribe(), right?

**Comment by saheemg** [comment]
Woops... that is correct.  I meant subscribe()

**Comment by saheemg** [comment]
ping..

**Comment by edenhill** [comment]
Do you have auto topic create disabled in the broker?
