### ISSUE TITLE
rd_kafka_produce problems

### ISSUE THREAD

**Issue by duanyr** [edenhill/librdkafka#1243]
@edenhill 
hi:

my librdkafka version is 0.9.5-pre0
Apache kafka version is 0.10.2.0

my question is:

i have altered my topic's partition num(such as from 2 to 3).when calling rd_kafka_produce with the new partition, function returned error_code:RD_KAFKA_RESP_ERR__UNKNOWN_PARTITION;

but wait for several minutes,when calling rd_kafka_produce again with the new partition,the function can execute correctly;

so how shoud i judge the new partition can produce or consume?

thanks!

**Comment by edenhill** [comment]
The producer will pick up the new partition count on the next periodic metadata refresh, you can control this interval with the `topic.metadata.refresh.interval.ms` property.
