### ISSUE TITLE
librdkafka consumer questions with group.id

### ISSUE THREAD

**Issue by duanyr** [edenhill/librdkafka#1246]
@edenhill 
hi:
First of all thank you very much for your last answer!

my librdkafka version is 0.9.5-pre0
Apache kafka version is 0.10.2.0

my question is:

when calling rd_kafka_consume_start with offset param RD_KAFKA_OFFSET_STORED, the ErrMsg indicates that it requires a group.id; so i set group.id configuration with rd_kafka_conf_set; but i don't know what's this configuration meaning in here.

my some configuration:
offset.store.method is broker
enable.auto.commit is true

I've always thought that goup.id is for consumer group using(such as for consumer rebalance)  and it should be high-level api configuration (i think rd_kafka_consume_start  api  is low-level,because i need specify topic and partition when consuming or producing);

I don't know if i understand correctly above,so really looking forward to your answer.

thanks!

**Comment by edenhill** [comment]
Broker-based Offset commits are effectively a tuple of  (group.id, topic, partition, offset)

**Comment by edenhill** [comment]
Topics and partitions dont belong to a  specific consumer or a specific consumer group, any number of different implementations and applications can consume the same partitions simultaneously and there is no shared state between them.
To share the commit state the group.id is used, allowing multiple applications and instances to use the same stored offset.
