### ISSUE TITLE
Producing duplicated data after increasing partition numbers

### ISSUE THREAD

**Issue by chrislee87** [edenhill/librdkafka#1247]
Description
===========

How to reproduce
================
Dynamicly increasing the topics' partition number, then producer(based on C version librdkafka) writes duplicated data into kafka.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 
 - [ ] Apache Kafka version:  0.10
 - [ ] librdkafka client configuration: 0.9.1
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please provide details on how to reproduce this and how you are producing the messages and verifying their duplicity.
