### ISSUE TITLE
No c++ interface for connect_cb?

### ISSUE THREAD

**Issue by szmcdull** [edenhill/librdkafka#1249]
Description
===========
No c++ interface for connect_cb?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.9.5] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Correct, the C++ API lags somewhat behind and some of the less used interfaces are only added on demand/contribution.

I'm curious, what is your use-case for connect_cb?

**Comment by szmcdull** [comment]
I need to report server alerts to zabbix monitoring server. I also need to clear the alert after the server goes back to normal. I guess I can use connect_cb to know when the server gets online.

**Comment by edenhill** [comment]
That makes sense, scheduling this for the release after the next one, we're at code freeze so it won't make the next release.

**Comment by szmcdull** [comment]
Thank you very much.

**Comment by szmcdull** [comment]
I found out that I need to implement connect inside connect_cb. But the socket parameter is non-blocking. How can I know the connect call is to be successful or failed?

**Comment by edenhill** [comment]
You are right that it expects a non-blocking connect.
What is it that you are trying to do?

Den 6 jul 2017 10:42 skrev "szmcdull" <notifications@github.com>:

**Comment by szmcdull** [comment]
I want to know if the connection successes or fails.

**Comment by szmcdull** [comment]
I need to report the connection alert when the connection fails. And clear the alert when the connection resumes.

**Comment by edenhill** [comment]
You can use the error_cb for connection filuren, but there is currently no
callback to monitor succesful connections.

What is it that you are trying to achieve at a higher level?

Den 6 jul 2017 11:35 skrev "szmcdull" <notifications@github.com>:
