### ISSUE TITLE
Topic delete callback

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#1250]
Description
===========
Is there a callback that is generated when a topic gets deleted on the broker? That ways the producer using librdkafka can use to cleanup topic related objects and do the needful.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system: Linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Currently no, there are some plans to provide a topic event notification API that allows the application to monitor a partition for creation, leader changes, partition count updates, and deletions.

**Comment by edenhill** [comment]
As a workaround you can periodically poll the topic's metadata with rd_kafka_metadata()

**Comment by blandings** [comment]
Thank you. How might we help increase priority of enhancements such as these?

**Comment by edenhill** [comment]
The prioritization goes something like:
 * Severity 
 * Confluent backlog / Confluent customer demand
 * High-quality community PRs
 * Community backlog / Community demand (issue popularity)
