### ISSUE TITLE
Confluent.kafka - security.protocol is not recognised

### ISSUE THREAD

**Issue by kavyashivakumar** [edenhill/librdkafka#1251]
Description
===========
hi

i'm using confluent.net wrapper to try and produce messages to kafka using sasl_plaintext.. the error i get is " "No such configuration property: security.protocol"

i did see readme.doc for latest librdkafka. it says missing "  - SASL support (no official Cyrus libsasl2 DLLs available)"

my questions are:

is there no way i can to sasl authentication using .net?
i did see https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_conf.c and had some code for sasl. if i rebuild latest librdkafka, will i not be able to use it?

please help. as I'm quite stuck with this problem. 

How to reproduce
================
if you run this code, (a basic one)

`
               
              string topicName = "KAFKA_MM_RESULT_L0";
            System.Diagnostics.Process.Start("cmd.exe", @"C:\Program Files (x86)\Java\jdk1.8.0_131\bin\kinit -k -t C:\Kafka\SRVCSSTFRTB01_APPIAGLOBAL.keytab SRVCSSTFRTB01@IAGLOBAL.LLOYDSTSB.COM");
            var config = new Dictionary<string, object> { { "bootstrap.servers", "s1" },
                { "sasl.kerberos.service.name", "kafka/something@somethingDomain.COM" },{"security.protocol","PLAINTEXTSASL"} };

            using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
            {
                Console.WriteLine($"{producer.Name} producing on {topicName}. q to exit.");

                string text = @"this is from .net ";

                while ((text = Console.ReadLine()) != "q")
                {
                    var deliveryReport = producer.ProduceAsync(topicName, null, text);
                    deliveryReport.ContinueWith(task =>
                    {
                        Console.WriteLine($"Partition: {task.Result.Partition}, Offset: {task.Result.Offset}");
                    });
                }

                // Tasks are not waited on synchronously (ContinueWith is not synchronous),
                // so it's possible they may still in progress here.
                producer.Flush();
            }
`

Checklist
=========
Please provide the following information:

 - [ latest version of confluent.kafka.net] librdkafka version (release number or git tag):
 - [ no explicit changes] librdkafka client configuration:
 - [windows 7 ] Operating system:
  - [ Not quite sure how to do this in kafka-net.] Provide logs (with `debug=..` as necessary) from librdkafka =
 - [ yes] Critical issue

**Comment by kavyashivakumar** [comment]
just when i posted, i tried with {"security.protocol","sasl_plaintext"} and it worked. But your thoughts would still be helpful on my first qn. thank you. as I'm still unable to "produce" messages to Kafka. not sure if i'm missing any attribute

**Comment by kavyashivakumar** [comment]
i tried with {"security.protocol","sasl_plaintext"} and it worked.

**Comment by edenhill** [comment]
SASL PLAIN and SCRAM support has been added to librdkafka master and will be available in the next release.

**Comment by kavyashivakumar** [comment]
@edenhill thank you Eden. is there any pre release version i can test with?
