### ISSUE TITLE
When DNS is not available, RdKafka does not correctly connects with the broker

### ISSUE THREAD

**Issue by f18m** [edenhill/librdkafka#1252]
Description
===========
I have found  the following problem:  I'm setting the property "metadata.broker.list" to a single IPv4 address, which obviously points to my Kafka broker. The broker server has the hostname "fmontorsi-eventstorage-instance-4gfxkwsddczv", but the DNS in the LAN where I'm working is not able to resolve that name.

I discovered that, although the "metadata.broker.list" contains directly the IP address of the broker, something in RdKafka is failing with the following syslog message:

Jun  5 10:50:24 fmontorsi-statemachine-instance-opyh44dvilvx hmstatemachine[16921]: INFO [17000] [thrd:fmontorsi-eventstorage-instance-4gfxkwsddczv:9092/0]: fmontorsi-eventstorage-instance-4gfxkwsddczv:9092/0: **Failed to resolve 'fmontorsi-eventstorage-instance-4gfxkwsddcz
v:9092': Name or service not known**

and then rd_kafka_produce() calls I do are returned as successful but no data is stored on the Kafka broker (I see the directory of logs /tmp/kafka-logs contains files that do not grow in time).
 
The workaround was to explicitly provide name resolution for the Kafka broker on the machine where I create the PRODUCER and CONSUMER sockets (by adding to /etc/hosts a line with the Kafka broker IP and hostname).

How to reproduce
================
- install Kafka broker on a machine with an hostname that is not registered in any DNS
- try from another machine to create a PRODUCER socket that uses that Kafka broker
- Metadata acquisition will work, message producing will not

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.5
 - [x] Apache Kafka version: kafka_2.12-0.10.2.1
 - [ ] librdkafka client configuration:
 - [x] Operating system: Centos7
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The metadata.broker.list/bootstrap.servers bootstrap brokers are only used to connect to the cluster and request the full list of brokers - this list is created by the brokers and is based on the broker's advertised hostnames (advertised.listener config).
The client then connects to each of the proper broker addresses.

If the client can't resolve or connect to the advertised broker addresses it will not be able to neither consume or produce.

**Comment by OleksandrKvl** [comment]
Hi @edenhill, we had a similar issue but I don't quite understand your previous answer.
I was not involved directly but here are the details I know: we had a machine with bad configuration in a way that its host name `name_a` was different from the DNS name `name_b`. Kafka was configured using correct IP address of that machine. However, we got an error that `name_a` cannot be resolved. It looks like rdkafka unconditionally converted IP to host name which it then tried to resolve and failed. Is it really the correct approach in case when IP address is used?

**Comment by rolandyoung** [comment]
Your interpretation of the problem is not correct. The "metadata.broker.list" property is used to find one of the brokers in the cluster. That broker then tells rdkafka its own address and the address of all the other brokers. From this point onwards, these are the addresses that rdkafka will use. 
If the broker is confused about its own address and/or publishes an address that cannot be resolved correctly, rdkafka will be unable to  communicate with that broker. (See this article https://www.confluent.io/en-gb/blog/kafka-listeners-explained/)

**Comment by OleksandrKvl** [comment]
@rolandyoung Oh, I see now, Kafka connected to it using IP address but then got wrong host name because it's configuration was broken. Thank you!
