### ISSUE TITLE
Log Location for librdkafka

### ISSUE THREAD

**Issue by kavyashivakumar** [edenhill/librdkafka#1253]
Description
===========
Pardon my ignorance but i'm still learning. 

I'm trying to connect to Kafka using confluent Kafka-net and am unable to connect to producer. I want to understand why so enabled logging by adding 
`{"log_level",7 }{"debug",all }`

but where is the log stored? I do not have access to unix box where kafka service is running. can you please help? 

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ no changes] librdkafka client configuration:
 - [windows ] Operating system:
 - [ na] Using the legacy Consumer
 - [na ] Using the high-level KafkaConsumer
 - [ where do i get this from?] Provide logs (with `debug=..` as necessary) from librdkafka

**Comment by kavyashivakumar** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ i did find this link but I'm just trying to understand if it will be logged at client side(windows) or at server side(Linux). how can i see logs at the client side?

**Comment by treziac** [comment]
At client side. You have to configure yourself how logs are handled. If you write them to a file, you will find them in a file

**Comment by kavyashivakumar** [comment]
thank you @treziac  took a while but eventually figured. just the way you've mentioned. You're already familiar with the issue i've raised in another thread. took a while but had managed to get some log.
thank you again

**Comment by kavyashivakumar** [comment]
resolved
