### ISSUE TITLE
Sometime  the Rebalance_cb  don't be triggered

### ISSUE THREAD

**Issue by ChildePig** [edenhill/librdkafka#1257]
Description
===========
i put up a brokers colony in linux system. then use the high API  KafkaConsumer  poll messages. 
then i found that the rebalance_cb do not be triggered. so  i check the broker debug info.

print  a string  "address  is already registered ."

but my cosumer client have not any error info.

the below's info is my consumer client config code:
	kfk_config.use_group = true;
	kfk_config.use_consume_cb = false;
	kfk_config.use_event_cb = true;
	kfk_config.use_rebalance_cb = true;
	kfk_config.use_offset_commit_cb = false;
	kfk_config.auto_commit_offset = false;

below is topic config info:
        request.required.acks = 1
        request.timeout.ms = 5000
        message.timeout.ms = 300000
        produce.offset.report = false
        compression.codec = inherit
        auto.commit.enable = false
        auto.commit.interval.ms = 60000
        auto.offset.reset = largest
        consume.callback.max.messages = 0

more i can provide:
   this bug that the title described come from some project scene .
   After the examination, the discovery that the bug will be appear in the condition like that when the broker's ip address in the brokers cluster is already in use.
   the debug string "ip address  is already in use" print when i query the topic list.
   after changed  the ip address of that broker, the consumer client can work in correcttly, as well as the rebalace_cb will be triggered .

All of the above case only occured when use high level KafkaConsumer class.   

And the low API  Consumer  can work correctly in above condition.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ master branch ] librdkafka version (release number or git tag):
 - [ 2.10-0.10.0.0 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ centos 6.5 ] Operating system:
 - [ no ] Using the legacy Consumer
 - [ yes ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Not enough information to go on.
Please fill out the checklist.

**Comment by ChildePig** [comment]
add some description

**Comment by edenhill** [comment]
If the broker can't bind to its address it will not function correctly, this is not a problem on the client side.
