### ISSUE TITLE
Why would you want to set "log.queue" true?

### ISSUE THREAD

**Issue by ronalabraham** [edenhill/librdkafka#1258]
(I'm referring to [this](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md).)

The only reason I can think of is so that you can choose exactly which thread handles the log events. So then you can consume (e.g. print) logs whenever it's appropriate from a thread-safety perspective. Is there another reason?

**Comment by treziac** [comment]
In some language bindings, you might not want to use callbacks also for various reason.
See https://github.com/edenhill/librdkafka/issues/355 for original reasons.
Being thread safe seems to be the main reason, but you could find more: if you send data to a distant location, you would be able to send them in bulk more easily, etc.

**Comment by ronalabraham** [comment]
Thanks for the history lesson! :+1:
