### ISSUE TITLE
Why does enabling any "debug" context explicitly set a "log_level" of LOG_DEBUG?

### ISSUE THREAD

**Issue by ronalabraham** [edenhill/librdkafka#1260]
Maybe this is a silly question, but I'm referring to a specific line of [code](https://github.com/edenhill/librdkafka/blob/v0.9.5/src/rdkafka.c#L1286). This seems to imply all logs from every debugging context are at the DEBUG level.

I'm asking because I was surprised that I was receiving DEBUG level logs despite explicitly specifying "log_level" = LOG_INFO; it turned out it was because I was enabling at least one "debug" context.

**Comment by edenhill** [comment]
This is just legacy, and decision way back in the days.
It would be perfectly fine to enable debugging and not increase the log level, would require some minor modification to the log functions.

Are you seeing an actual problem with the current behaviour?

**Comment by ronalabraham** [comment]
Thanks for your answer. The only problem is this surprising behavior: when I create a Producer object (C++ API) configured with "debug" = "all" and "log_level" = LOG_INFO, I get DEBUG level logs. There isn't a way to change the "log_level" after the Producer is created, right?

**Comment by edenhill** [comment]
Correct, but why would you enable debugging and then not want to see it by
lowering the log level?

Den 9 juni 2017 17:06 skrev "ronalabraham" <notifications@github.com>:

**Comment by ronalabraham** [comment]
OK, so that's why this was a silly question. :) It sounds like you're saying that all logs produced by any debugging context (all, generic, broker, etc) are at DEBUG level, and there are none at INFO, NOTICE, WARNING, etc.

**Comment by edenhill** [comment]
@ronalabraham Exactly!
