### ISSUE TITLE
Help!Why the producer cannot send messages

### ISSUE THREAD

**Issue by CoderOverflow** [edenhill/librdkafka#1261]
Description
===========
Hi,
I follow the examples to create a new console Win32 project in vs2015.
I found my code doesn't work unless I added getline() function at the end of the program.

The produce() method returns success, but the command window of kafka-console-consumer cannot
have any response.

How to solve this problem?
Anyone knows?

--2017/6/11 Add--
I found why it doesn't work.
It seems too fast to delete the producer object 
causing the producer cannot send messages to broker.

When I add sleep 1000 between produce method and delete producer object, 
producer can send message correctly.

So, the question is How to send message immediately.
How can I make sure those message have been send totally before I destroy the producer object?

How to fix this problem, actually I don't like to add some sleep() in my source code.

---------------------

How to reproduce
================
```
// kafka_test_win32_nomfc.cpp
//

#include "stdafx.h"
#include <iostream>
#include "librdkafka/rdkafkacpp.h"


int static producer_1()
{
	std::string brokers = "127.0.0.1";
	std::string errstr;
	std::string topic_str = "linli";
	std::string mode;
	std::string debug;
	int32_t partition = RdKafka::Topic::PARTITION_UA;
	int64_t start_offset = RdKafka::Topic::OFFSET_BEGINNING;
	bool do_conf_dump = false;
	int opt;
	// MyHashPartitionerCb hash_partitioner;
	int use_ccb = 0;

	/*
	* Create configuration objects
	*/
	RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
	RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

	conf->set("metadata.broker.list", brokers, errstr);

	RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);
	if (!producer) {
		std::cerr << "Failed to create producer: " << errstr << std::endl;
		exit(1);
	}

	std::cout << "% Created producer " << producer->name() << std::endl;

	/*
	* Create topic handle.
	*/
	RdKafka::Topic *topic = NULL;
	if (!topic_str.empty()) {
		topic = RdKafka::Topic::create(producer, topic_str, tconf, errstr);
		if (!topic) {
			std::cerr << "Failed to create topic: " << errstr << std::endl;
			exit(1);
		}
	}

	RdKafka::ErrorCode resp = producer->produce(topic, partition,
		RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
		const_cast<char *>("hello worlf"), 11,
		NULL, NULL);

	delete topic;
	delete producer;
	return 0;
}


int static producer_2()
{
	std::string brokers = "127.0.0.1";
	std::string errstr;
	std::string topic_str = "linli";
	std::string mode;
	std::string debug;
	int32_t partition = RdKafka::Topic::PARTITION_UA;
	int64_t start_offset = RdKafka::Topic::OFFSET_BEGINNING;
	bool do_conf_dump = false;
	int opt;
	// MyHashPartitionerCb hash_partitioner;
	int use_ccb = 0;

	RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
	RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

	conf->set("metadata.broker.list", brokers, errstr);

	RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);
	if (!producer) {
		std::cerr << "Failed to create producer: " << errstr << std::endl;
		exit(1);
	}

	std::cout << "% Created producer " << producer->name() << std::endl;

	RdKafka::ErrorCode resp = producer->produce(topic_str, partition,
		RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
		(void *)"hi", 2,
		NULL, 0, 0, NULL);

	std::string errs(RdKafka::err2str(resp));
	std::cout << errs << std::endl;
	//producer->poll(0);


	delete producer;
	
	return 0;
}


int main()
{
    producer_2();
    return 0;
}

```

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):591104
 - [ ] Apache Kafka version: kafka_2.10-0.9.0.1
 - [ ] librdkafka client configuration:
 - [ ] Operating system:win10
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
produce() is asynchronous, the message will be sent later from a background thread.
To make sure all messages are sent you need to call flush() prior to terminating your producer application.

**Comment by CoderOverflow** [comment]
Calling flush() doesn't work, maybe this is a bug.  
In the delete procedure, you mean, produce will check some flags before it destroys itself.
I simply use the above-mentioned code to test behaviors of producer. Insert the line of produce->flush(0) between produce() method and delete method(). 
Now I am prepare to update my test project into a multi-thread application in order to test and find the better way to use the producer.

**Comment by edenhill** [comment]
Why are you calling flush() with a timeout of 0? You are not giving it any time to actually produce the messages in the background.
Increase the timeout to the allowed time to produce, e.g., 10s or 2 minutes.

**Comment by CoderOverflow** [comment]
I cannot give it so much time in an instant data transport system.
so, it seems there is no way to send a message immediately...

**Comment by CoderOverflow** [comment]
I see ^_^
one more question. if I use producer object in a long life way, can I modify the conf dynamically, 
Or If I want to change the config, the producer object must be recreated to load the new configuration and the origin one should be delete?

**Comment by edenhill** [comment]
Giving it 0 time units logically gives it no time to produce, so it is clear that will not work.
You'll need to decide what your maximum latency is and adjust the flush() period accordingly.
Also have a look at this wiki post:
https://github.com/edenhill/librdkafka/wiki/How-to-decrease-message-latency

Configuration is immutable.

**Comment by CoderOverflow** [comment]
and I find another interesting phenomenon, went I create producer at the main thread and use detach(), message cannot be send. 
When I move the producer into thread, message can be send correctly.
both are call the flush function.
so, it seems I have to use the join() method to run the thread;

**Comment by edenhill** [comment]
librdkafka is thread-safe (unless otherwise noted in the API docs), if you find a case where this is not the case please file a separate issue and provide a fully reproducible code snippet.

Thanks

**Comment by CoderOverflow** [comment]
thank you for your information about 
[(https://github.com/edenhill/librdkafka/wiki/How-to-decrease-message-latency )]
I tried setting the configuration to an immediate transmission
conf->set("queue.buffering.max.ms", "0", errstr);
conf->set("socket.blocking.max.ms", "0", errstr);

but still have no effect, unless I call the flush(5000);

Is this correct that I have to set these three things.

**Comment by edenhill** [comment]
Try setting those values to "1" instead of "0", also enable "protocol" debug to see the rtt (latency) of the ProduceRequests.

**Comment by CoderOverflow** [comment]
![2017-06-14_193110](https://user-images.githubusercontent.com/29338660/27130412-cafad934-5138-11e7-81b7-2c5d69492f52.png)

I've used the test 0055 to learn the usage in terms of latency.  The picture is about the result of the test.
Thanks a lot.

**Comment by Krishnaraj02** [comment]
#include <iostream>
#include <string>
#include <librdkafka/rdkafkacpp.h>

int main() {
    std::string brokers = "localhost:9092";
    std::string topic = "secondtopic";
    std::string errstr;

    RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
    RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);
    conf->set("bootstrap.servers", brokers, errstr);

    RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);
    delete conf;

    std::cout << "Created producer " << producer->name() << std::endl;

    RdKafka::Topic *rd_topic = NULL;
    if (!topic.empty()) {
		rd_topic = RdKafka::Topic::create(producer, topic, tconf, errstr);
		if (!rd_topic) {
			std::cerr << "Failed to create topic: " << errstr << std::endl;
			exit(1);
		}
	}
        std::string message;
        std::cout << "Enter the Message or type 'exit': ";
        std::getline(std::cin, message);

        RdKafka::ErrorCode resp = producer->produce(rd_topic, RdKafka::Topic::PARTITION_UA, RdKafka::Producer::RK_MSG_COPY,
                                           const_cast<char *>(message.c_str()), message.size(), NULL, NULL);

        if (resp != RdKafka::ErrorCode::ERR_NO_ERROR) {
            std::cerr << "Failed to produce message: " << RdKafka::err2str(resp) << std::endl;
        } else {
        std::cout << "Message produced: " << message << std::endl;
        }
    delete rd_topic;
    delete producer;

    return 0;
}
-------while run the code it shows Failed to produce message anyone can clear this issue
