### ISSUE TITLE
some data loss in kafka producer when sending large events

### ISSUE THREAD

**Issue by kanchan1234** [edenhill/librdkafka#1262]
Description
Librdkafka version(0.9.3) in RHOS
Hi, whenever i send large data say (>5k) ,kafka producer accepts vei less event(say just 2k)..

here is the configuration setting,i have done:
KafkaConfigOption       batch.num.messages      60000
KafkaConfigOption       queue.buffering.max.ms  5
KafkaConfigOption      queue.buffering.max.messages    10000000

Producer code:
```
 if( rd_kafka_produce(
                                kafka_topic,
                                partition,
                                RD_KAFKA_MSG_F_COPY,
                                msg.msg,
                                strlen(msg.msg),
                                NULL,
                                0,
                                NULL
                        ) == -1 ) {
                                printf( "Could not send message to kafka\n" );
rd_kafka_poll(kafka_conn, 1/*block for max 1000ms*/);
                                goto retry;
                        }
cnt_processed_msg++;

                        rd_kafka_poll( kafka_conn, 0 );

                        }
```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by kanchan1234** [comment]
hello,can i get any suggestion?

**Comment by edenhill** [comment]
`rd_kafka_poll(kafka_conn, 1/*block for max 1000ms*/);`

You are just sleeping for 1ms there, not 1000 ms.

What is the error code you get from produce? (use rd_kafka_last_error() or rd_kafka_errno2err())

**Comment by kanchan1234** [comment]
Ok thenks for the comment.
This is how i modified my code for rd_kafka_produce
retry:
if( rd_kafka_produce(
                                kafka_topic,
                                partition,
                                RD_KAFKA_MSG_F_COPY,
                                msg.msg,
                                strlen(msg.msg),
                                NULL,
                                0,
                                NULL
                        ) != 0 ) {
                        printf( "Could not send message to kafka\n" );
  if (rd_kafka_last_error()) {
printtf("%s",rd_kafka_err2str(rd_kafka_last_error())) ;
rd_kafka_poll(kafka_conn, 1000/*block for max 1000ms*/);
                                goto retry;
                        }
        }
Results:
Input-10000000 
Output- 5254404
No error i saw in the screen
I changed the kafka Config as:
KafkaConfigOption queue.buffering.max.messages 1000000
KafkaConfigOption       batch.num.messages      50000
KafkaConfigOption       queue.buffering.max.ms  100

**Comment by edenhill** [comment]
Are you calling flush() before exiting your application to make sure all queued messages are sent?
You should also check rd_kafka_outq_len() after calling flush(timeout) to see if there are any remaining messages in queue that did not flush.

**Comment by kanchan1234** [comment]
yes i am using it
 while( rd_kafka_outq_len( kafka_conn ) > 0 ) {
        rd_kafka_poll( kafka_conn, 1 );
    }
fprintf(stderr, "%% Flushing final messages..\n");
       rd_kafka_flush(kafka_conn, 10 /* wait for max 10 seconds */);

**Comment by edenhill** [comment]
There is no need to call flush() after that outq_len+poll loop, they are essentially the same thing.

(nit: flush() takes milliseconds, not seconds).

Have you registered a delivery report callback, and if so, are you counting the number of successfully produced messages, as well as messages that failed to produce (`err` is set)?

**Comment by kanchan1234** [comment]
Ok,i wl remove the flush()
yes i have set report callback but for such large number of events we can't check individually also our aim is to prevent loss  
how can i set err??

**Comment by edenhill** [comment]
The delivery report is called once per message. See API docs for details.


Den 16 juni 2017 13:41 skrev "kanchan1234" <notifications@github.com>:

Ok,i wl remove the flush()
yes i have set report callback but for such large number of events we can't
check individually also our aim is to prevent loss
how can i set err??

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/edenhill/librdkafka/issues/1262#issuecomment-309004640>,
or mute the thread

**Comment by kanchan1234** [comment]
yes delivery report works for each message..i have set it and i can see there is a loss of data from kafka producer...but what can be the reason i don't know.
is there any config property i need to customise to allow large data to be consumed or i need to make some change in consumer side

**Comment by kanchan1234** [comment]
moreover the loss amount is not same ..it varies evry other moment i run the commnd..are the datas are getting buffered..if so how to resolve..is there a way to send 1llakh data in just one shot with no delay

**Comment by kanchan1234** [comment]
ok..i tried to set " request.required.acks   -1"  in config file using
KafKaConfigOption  request.required.acks   -1
but i am unable to set it.I think it can prevent data loss

**Comment by kanchan1234** [comment]
i understand it is topic property so i have tried to set it like this:
kafka_topic_conf = rd_kafka_topic_conf_new();
rd_kafka_topic_conf_set(kafka_topic_conf,"request.required.acks","-1",errstr,sizeof(errstr));
when i run doin this
i get an error 
% Message delivery failed: Broker: Not enough in-sync replicas
but all the messages are sent,the consumer side confirms that they get all messages so how i can rely onit for the scenario where we face data loss
