### ISSUE TITLE
How to deal with the connection timeout

### ISSUE THREAD

**Issue by CoderOverflow** [edenhill/librdkafka#1266]
Description
===========
![20170617000827](https://user-images.githubusercontent.com/29338660/27234927-67f0e2ec-52f1-11e7-960e-62b12ac3261b.png)

I've read https://github.com/edenhill/librdkafka/issues/437 

I'm trying to write an ProducerPool to manage the long life object of several producers.
I have a question about how to deal with the connection timeout.

should I get the produce's return value when it fail to do and then release the current producer and 
create a new one again?
or Should I adjust the value of connections.max.idle.ms and create a thread to refresh the connection?

Which way do you recommend to use.

Thanks.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You don't need to handle connection closes, librdkafka will reconnect automatically.
If you want to silence the idle connection reaper you can set log.connection.close=false in the client.

**Comment by CoderOverflow** [comment]
I tested producer to send a message after sleep(1000*60*11), however
the broker cannot receive the massage.
What should I do?

**Comment by edenhill** [comment]
start with enabling debug to see what is going on: `debug=broker,topic,metadata`

**Comment by CoderOverflow** [comment]
Thank you very much.
 :)

**Comment by CoderOverflow** [comment]
Hi @edenhill 
how to catch the time_out error?

Now i write some codes in the dr_cb's callback function to save messages.
I seems that the dr_cb's callback doesn't be invoked when time_out occurs.
I want to save my messages to disk when this happens.

**Comment by edenhill** [comment]
The delivery report will be called when the message times out, but the delivery report callbacks needs to be triggered by the application, either through calling poll() or flush().

**Comment by naveen-ilink** [comment]
I am facing the same connection down issues on my producer client library (v0.9.5)
log.connecition.close: false property is not working as expected. Should i need to upgrade to latest version of Confluent library (v0.11.0)
