### ISSUE TITLE
About producer object's destruction

### ISSUE THREAD

**Issue by CoderOverflow** [edenhill/librdkafka#1267]
Description
===========
What should I do to properly release the long-life busy producer object when I terminate my application.
Should I have to check the value of 
1. err = p->flush(5000);  (0059-bsearch.cpp)
2. p->outq_len() > 0;  (0057-invalid_topic.cpp)
or something else.
and then wait a period of time, after that call delete procuder again?
or can I pick out the message which is unsuccessfully sent out at the moment, and then release the producer.

I am still not sure that whether the message is totally send in the producer when i destroy it.

Thanks.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
When you terminate your application you should call flush() with the maximum timeout allowed to produce any messages in queue.
After flush() returns you can check outq_len() to see if there are any remaining messages in queue and then handle that separately to your liking.

flush() will trigger delivery reports.

**Comment by CoderOverflow** [comment]
Can I get the remaining payload from producer object?

**Comment by edenhill** [comment]
There's currently no API for purging the internal queue and triggering delivery report callbacks.

Dup of #990

**Comment by CoderOverflow** [comment]
Thank your for you information.
Now in my application there are many work threads which share some long life producers together.

When I close my application to reload some settings, the next thing maybe happen.
1. force to call flush->(5000)  before  delete produce[i]. and if p->outq_len() equits 0(According your advice) this is OK. 
2. what if after the action of calling flush() and still returns some error ,and if p->outq_len() bigger than 0 , How can I handle this situation 
and get messages back because I want to save this messages on disk for being resend next time, when the application starts.

It‘s really a problem If there is no API for getting the residue messages at producer side. 
I hope that in the future it could automatically create a persist files to save the reminding when application is down ,or provide API to let user get the messages in out queue .



Thanks

**Comment by edenhill** [comment]
The messages will remain in queue until they are produced, failed permanently due to broker error, or times out due to `message.timeout.ms` (5 minutes default).
Since you only have control of the latter I suggest you decrease `message.timeout.ms` to a reasonable value and make sure to call flush() with the same value (plus a second or so for processing time).
This way you should be guaranteed that outq_len() will always be 0 when flush() returns

**Comment by CoderOverflow** [comment]
:) Yeah, I know what you mean. I am just worried about that situation the worst one even if it's hardly to happen. sometimes user may restart their server, so an API for developers to do some persistence is also a good choice, isn’t it.

Anyway, I will try setting this device to a big value; Thank a lot.
