### ISSUE TITLE
librdkafka produces event with -1 for create time

### ISSUE THREAD

**Issue by javierholguera** [edenhill/librdkafka#1268]
Description
===========
Using librdkafka through C# confluent-dotnet wrapper produces very rarely events with -1 for create time. In a topic with 25K events, only 1 has -1. All of them are produced with the same code and the same version for all components.

We produce in confluent-dotnet like this:

```c#
            return this.innerProducer
                .ProduceAsync(this.topic, key, message, targetPartition)
                .ContinueWith(t => ToPublishResult(t.Result));
```

Which means that we let confluent-dotnet manage timestamps. I've checked the code that pushes this all the way to librdkafka, which seems to do this:

```c
rkm->rkm_timestamp = rd_uclock()/1000;
```

Not sure how -1 could end up in the broker.

How to reproduce
================
1. Load testing our system
2. Lots of events get successfully into the topic (including the one with -1 for create time).
3. Eventually, a KStreams consumer complains about an event with -1 for create time.
4. Reading the topic using kafkacat, 1 out of 25K events has -1 for create time.

Example of kafkacat dump:
```
Topic my-topic[3], offset: 7568, Timestamp: 1497712176074 (Saturday, June 17, 2017 3:09:36.074 PM)
Topic my-topic[3], offset: 7569, Timestamp: 1497712215686 (Saturday, June 17, 2017 3:10:15.686 PM)
Topic my-topic[3], offset: 7570, Timestamp: 1497712219920 (Saturday, June 17, 2017 3:10:19.920 PM)
Topic my-topic[3], offset: 7571, Timestamp: -1 
Topic my-topic[3], offset: 7572, Timestamp: 1497712294655 (Saturday, June 17, 2017 3:11:34.655 PM)
Topic my-topic[3], offset: 7573, Timestamp: 1497712369771 (Saturday, June 17, 2017 3:12:49.771 PM)
Topic my-topic[3], offset: 7574, Timestamp: 1497712381483 (Saturday, June 17, 2017 3:13:01.483 PM)
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.5.
 - [x] Apache Kafka version: 10.x.y
 - [x] librdkafka client configuration: api.version.request = true
 - [ ] Operating system: Windows
 - [ ] Using the legacy Consumer:
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue: Yes

**Comment by treziac** [comment]
Do you have a single process producing? If not, are you sure you don't have a producer which doesn't have the api.version.request = true configuration?
Couldn't reproduce myself (win10 on confluent 0.9.5 by prducing 600Kmsg/s with kafka 10.2.1)

**Comment by javierholguera** [comment]
Sorry, I should have answered and close this ticket.

After discussing it with Confluent support, the problem was the following:

1. Our brokers were going through a very unstable phase, including lots of rebalances, etc.
2. As a result of that, when librdkafka would try to connect, the attempt would fail.
3. When that happened, it would use whatever value was configured in `broker.version.fallback`, which 0.9.0 being the current default.
4. Then it would try to produce, without sending any value for create time.

The solution proposed was to set `broker.version.fallback` to "0.10.0" to guarantee that it wouldn't fall back to a version of the protocol that doesn't support the features that we require.

So far, it was worked like a charm.
