### ISSUE TITLE
High level consumer receives TIMED_OUT if EOF

### ISSUE THREAD

**Issue by vadimiron** [edenhill/librdkafka#1269]
Description
===========
I'm using high level consumer - with php binding (php-rdkafka) 
Often, when there are no new messages in the topic (EOF), my consumers raise TIMED_OUT (Local: Timed out) error. I'm using timeout=1000 ms for consuming.
If some new messages are produced, then they can be consumed by consumers without a problem. But after that (if no new messages) I receive again TIMED_OUT.

If the broker is down I also receive the same error -> so it is impossible to differ between EOF and some connection issues.
But I would like to know, when there are some connection issues and when there are just no new messages in the topic.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.5
 - [x] Apache Kafka version: 0.10.2.1
 - [x] librdkafka client configuration:
offset.store.method = broker
enable.auto.commit = false
api.version.request = true
socket.keepalive.enable = true
 - [x] Operating system: Ubuntu 14.04
 - [x] Using the legacy Consumer - no
 - [x] Using the high-level KafkaConsumer - yes
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
If there are no new messages before the poll timeout is reached you will get a TIMED_OUT error back, which is expected since the timeout passed.

Connection issues are abstracted by librdkafka and it will reconnect and resume operations as soon as the broker is available again.

**Comment by vadimiron** [comment]
Thank you - I can confirm, that it is working as described, so I will wrap the timeout error, so it is not thrown in my library as exception .... but still for monitoring it would be nice, if I could differ between timeout=no new messages    and timeout=network issues/broker is not reachable.
But may be I could do something with logging or closesocket_cb

**Comment by edenhill** [comment]
I suggest using a logging callback and an error callback for that purpose.
