### ISSUE TITLE
What is the minimum windows version requirement for the librdkafka?

### ISSUE THREAD

**Issue by kshenkshen** [edenhill/librdkafka#1270]
hello,
I cannot  run the Producer client program with librdkafka in windows server 2003 because of some windows functions like InitializeSRWLock are not be supported.

So i want to know the minimum windows version requirement of librdkafka.

I can only sure that not less than windows server 2008 according to function InitializeSRWLock'requirement .

My English is terrible，thanks for reading.

**Comment by edenhill** [comment]
@mhowlett

**Comment by treziac** [comment]
@edenhill for info this is not not related with C# client (but we should provide the minimum required version there here too)
https://github.com/edenhill/librdkafka/blob/b7f57f9863367feff64b743b651f4f51f0934581/src/tinycthread.h#L492
This should not use InitializeSRWLock if we want it to work below Vista and WindowsServer 2008
