### ISSUE TITLE
Bumping the refcount of a topic in C: expose rd_kafka_topic_keep

### ISSUE THREAD

**Issue by Quuxplusone** [edenhill/librdkafka#1274]
Description
===========

I see `rd_kafka_topic_new(rk, name, config)` for converting a string topic name into a `rd_kafka_topic_t*`.
I see `rd_kafka_topic_destroy(rkt)` for decrementing the refcount of that topic.
What's missing is a way to *increment* the refcount of the topic without jumping through extremely burdensome hoops — e.g. `rd_kafka_topic_new((rd_kafka_t*)rd_kafka_topic_opaque(rkt), rd_kafka_topic_name(rkt), NULL)`, assuming that you're willing to waste the opaque pointer on a back-reference to the original `rd_kafka_t` that owns this topic — or `rd_kafka_topic_keep_app(rd_kafka_topic_a2i(rkt))` if you're willing to use internal headers.

What I'd like to see is a way to write a C++ binding that directly manages topics according to shared_ptr semantics:

    struct Topic {
        explicit Topic(rd_kafka_topic_t *rkt) : p_(rkt) {}
        Topic(Topic&& rhs) : p_(rhs.p_) { rhs.p_ = nullptr; }
        Topic(const Topic& rhs) : p_(rhs.p_) { if (p_) rd_kafka_topic_copy(p_); }
        ~Topic() { if (p_) rd_kafka_topic_destroy(p_); }
    };

This would work great for C++ code, if only the C API would expose `rd_kafka_topic_copy` for use by C++ code. I believe it could be implemented as a one-line function that calls `rd_kafka_topic_keep_app(rd_kafka_topic_a2i(rkt))`.

I'm happy to make a patch if it would help.

Checklist
=========

This applies to librdkafka top-of-tree, e223a193cbc089714110e42ca9051f3f1ebc0695.
Nothing else in the checklist matters since this is just a source-level issue.

**Comment by edenhill** [comment]
Isn't it sufficient with wrapping the Topic object in your own shared_ptr:ed topic class object?

**Comment by Quuxplusone** [comment]
@edenhill: Yes, I could use `std::shared_ptr<Topic>`, but then I would be using two layers of thread-safe reference-counting and two layers of heap allocation — and, most perniciously IMHO, two layers of `*`s in the C++ syntax for using the thing — when I could be using just one layer of each.

If `rd_kafka_topic_t` weren't refcounted at all, it would be a different story. But given that it *is* refcounted, and the C API already exposes the "decrement the refcount" function, it's weird that the C API doesn't equally expose the "increment the refcount" function.
