### ISSUE TITLE
FD based consuming in C++

### ISSUE THREAD

**Issue by Nnamdi** [edenhill/librdkafka#1276]
Are there any plans to expose `rd_kafka_queue_io_event_enable` functionality in the C++ API?

Thanks.

**Comment by edenhill** [comment]
The long-term goal is the provide corresponding C++ APIs for everything that is available in the C API as long as it is non-deprecated and found useful by people.

**Comment by edenhill** [comment]
Now supported:
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1436
