### ISSUE TITLE
Marking the coordinator 2147483537 dead

### ISSUE THREAD

**Issue by vihunk** [edenhill/librdkafka#1279]
Description
===========
print the log(loop) in one second:Marking the coordinator 2147483537 dead;
in my case: 
I configurated as manually commit offset and assign topic partitions as same, when reboot the kafka, the consumer print the log looply in one second, and cann't read the data any more. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka does not emit that log line.
