### ISSUE TITLE
High level consumer and autocommit=false

### ISSUE THREAD

**Issue by vadimiron** [edenhill/librdkafka#1280]
Description
===========
If the high level consumer is used and autocommit is switched off (enable.auto.commit=false), then high level consumer of librdkafka returns the next message even if the previous one was not commited.
It is a strange behavior, because I would await, that if I do not commit some message, I will receive always the same message on consume, but not the next one.
So: If I do not commit some message, I receive the next ones (from same partition). And if I commit these next ones, I will never get the first one again.

How to reproduce
================
Write 2 messages into a topic, that have only 1 partition.
Consume first time - do not commit - first message is received.
Consume second time - second message is received, but not the first one.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.5 (used over php binding)
 - [x] Apache Kafka version: 0.10.2.1
 - [x] librdkafka client configuration:
'offset.store.method' = 'broker'
'enable.auto.commit' = 'false'
'api.version.request' = true
'socket.keepalive.enable' = true
'socket.blocking.max.ms' = 1
'fetch.wait.max.ms' = 10
 - [x] Operating system: Ubuntu 14.04
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
If you never commit offsets for a given groupid, you will by default start at end of topic ("auto.offset.reset" is "largest" by default)

When you commit an offset, you commit the next offset to read, not the current one. So if you just consumed message at offset n, you should commit offset n+1 (this is done automatically in [rd_kafka_commit_message](https://github.com/edenhill/librdkafka/blob/6a735dd3b86a93b78f61855a7691439e89864368/src/rdkafka_offset.c#L442))

I didn't well understand what you meant, if this does not solve your problem, can you provide example with offset number and where you produce.consumer/commit?

**Comment by vadimiron** [comment]
Example:
There is a producer - it writes 2 messages into the topic (just 1 partition) - no consumer is listening yet.

After some time a consumer (high level) comes and consumes the first message. There is some exception and this consumer doesn't commit this message (enable.auto.commit=false). After that this consumer consumes again and receives the next message (the second one), but not the first one.
Why?  The first message was not commited - so offset is the old one.
If the consumer is restarted (new process), then he gets the first message - but only, if the second message was not commited.

I think, if enable.auto.commit=false, then the consumer should not get the second message till the first one is commited

**Comment by treziac** [comment]
What is your "some exception"?
Commit is only for getting assignments at startup. Once you have an assignment (except if there is a rebalance where you get new assignment), commit will not change the way you read data - sequentially.
Commit will only be used when you restart a consumer (what you see in your case)

Under the hood, librdkafka retry automatically to recover from failure and fail only for non temporary error.
If you think your first error is anormal, please provide logs by setting debug to cgrp,topic,fetch for now

**Comment by vadimiron** [comment]
This error is just some error in my application.
Pseudo code:

consumer = new Consumer(conf);

message = consumer.consume(); // first message
result = processMessage(message); // my application logic - false if some error occured
if(result) {
    consumer.commit(message);
}

message = consumer.consume(); //here I get the second message, even though I did not commit the first one


So it was not logical for me, that I get the next message (with higher offset), if I did not commit the previous one

**Comment by vadimiron** [comment]
I think I understand, that current offset is read only once at the start or rebalancing, so I will build a wrapper, that does, what I want

**Comment by treziac** [comment]
Yes, just rework your processMessage function so that you retry when it fail (or handle it correctly)

Note that if you have high throughput, it's discouraged to commit on each message - commit is not as light as reading data and will make broker spend too much time on updating offset everytime. Commit every 100ms or every 10msg for example. If you don't have high throughput or your broker can handle this, you can keep it like this
