### ISSUE TITLE
How to know the payload has been committed to the broker.

### ISSUE THREAD

**Issue by CoderOverflow** [edenhill/librdkafka#1282]
Description
===========
I tried using request.required.acks = 1 to retrieve some feedback from broker, but I am not 
familiar with it.
How can I check the require acks and how to create some failure of broker?
When a message is committed,  will the callback function RdKafka::EventCb be called？
Does RdKafka::DeliveryReportCb get the result regardless of the information in broker side?

When I use request.required.acks, is that means I have to use the API with topic configuration like

        RdKafka::Topic *topic = NULL;
	if (!topic_str.empty()) {
		topic = RdKafka::Topic::create(producer, topic_str, tconf, errstr);
		if (!topic) {
			std::cerr << "Failed to create topic: " << errstr << std::endl;
			exit(1);
		}
	}

	RdKafka::ErrorCode resp = producer->produce(topic, partition,
		RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
		const_cast<char *>("hello worlf"), 11,
		NULL, NULL);

rather than the one without topic settings
       
        RdKafka::ErrorCode resp = producer->produce(topic_str, partition,
		RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
		(void *)"xf0-1-2", 7,
		NULL, 0, 0, NULL);

THX

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
Didn't see your edit
The one with topic_str will automatically create the topic if you had not create it before, using the default topic configuration (you can define values for default topic)
Creating the topic allow you to define a custom topic conf if needed, where you can set a custom ack

Give a try to the samples, it will help you to start with the library ;)

**Comment by CoderOverflow** [comment]
I have tried DeliveryReportCb, and define callback function as examples shows.
I feel that DeliveryReportCb is only producer side information, is it right.
Or when the DeliveryReportCb is called represents the broker has receive the message successfully?

I constantly receive the info form DeliveryReportCb when request.required.acks is -1, is this normal?

class ExampleDeliveryReportCb : public RdKafka::DeliveryReportCb {
public:
	void dr_cb(RdKafka::Message &message) {
		std::cout << "Message delivery for (" << message.len() << " bytes): " <<
			message.errstr() << std::endl;
		if (message.key())
			std::cout << "Key: " << *(message.key()) << ";" << std::endl;
	}
};

class ExampleEventCb : public RdKafka::EventCb {
public:
	void event_cb(RdKafka::Event &event) {
		switch (event.type())
		{
		case RdKafka::Event::EVENT_ERROR:
			std::cerr << "ERROR (" << RdKafka::err2str(event.err()) << "): " <<
				event.str() << std::endl;
			if (event.err() == RdKafka::ERR__ALL_BROKERS_DOWN)
		//		run = false;
			break;

		case RdKafka::Event::EVENT_STATS:
			std::cerr << "\"STATS\": " << event.str() << std::endl;
			break;

		case RdKafka::Event::EVENT_LOG:
			fprintf(stderr, "LOG-%i-%s: %s\n",
				event.severity(), event.fac().c_str(), event.str().c_str());
			break;

		default:
			std::cerr << "EVENT " << event.type() <<
				" (" << RdKafka::err2str(event.err()) << "): " <<
				event.str() << std::endl;
			break;
		}
	}
};


int static producer_2()
{
	std::string brokers = "127.0.0.1";
	std::string errstr;
	std::string topic_str = "linli";
	std::string mode;
	std::string debug;
	int32_t partition = RdKafka::Topic::PARTITION_UA;
	int64_t start_offset = RdKafka::Topic::OFFSET_BEGINNING;
	bool do_conf_dump = false;
	int opt;
	// MyHashPartitionerCb hash_partitioner;
	int use_ccb = 0;

	RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
	RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

	
	conf->set("metadata.broker.list", brokers, errstr);
	conf->set("log.connection.close", "false", errstr);
	conf->set("queue.buffering.max.ms", "0", errstr);
	conf->set("socket.blocking.max.ms", "1", errstr);
	tconf->set("request.required.acks", "-1", errstr);
	ExampleDeliveryReportCb ex_dr_cb;

	/* Set delivery report callback */
	conf->set("dr_cb", &ex_dr_cb, errstr);

	ExampleEventCb ex_event_cb;
	conf->set("event_cb", &ex_event_cb, errstr);

	RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);
	if (!producer) {
		std::cerr << "Failed to create producer: " << errstr << std::endl;
		exit(1);
	}

	std::cout << "% Created producer " << producer->name() << std::endl;

	//RdKafka::ErrorCode resp = producer->produce(topic_str, partition,
	//	RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
	//	(void *)"xf0-1-2", 7,
	//	NULL, 0, 0, NULL);

	RdKafka::Topic *topic = NULL;
	if (!topic_str.empty()) {
		topic = RdKafka::Topic::create(producer, topic_str, tconf, errstr);
		if (!topic) {
			std::cerr << "Failed to create topic: " << errstr << std::endl;
			exit(1);
		}
	}

	RdKafka::ErrorCode resp = producer->produce(topic, partition,
		RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
		const_cast<char *>("hello worlf"), 11,
		NULL, NULL);

	






	producer->flush(5000);
//	_sleep(3000);
//	delete topic;
	delete producer;

	return 0;
	//_sleep(10);
}

int main()
{
	producer_2();
	system("PAUSE");
        return 0;
}

**Comment by treziac** [comment]
DeliveryCb is producer and broker side
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L403

Produce will return immediately only for immediate error (it will generally return without error)
Delivery callback (dc) will be called for all messages sent via produce. You have to inspect message->err(), it will be non 0 if broker did not properly receive message

With ack=-1, your dc will be called once all insync brokers received messages, or if brokers did not acked it (not enough in sync replica, network error or whatever, possibly timeout after message.timeout.ms, by default 5min)

**Comment by CoderOverflow** [comment]
I see. :)   when ack=-1, it doesn't mean to switch off the dc. The default value of ack is 1?
So I should set ack = all for sync replica to make sure every message received successfully.
could you told me some simple way to create a failure of broker which I can confirm in the dc easily?

**Comment by treziac** [comment]
acks=-1 and acks=all is the same, default is 1 (see CONFIGURATION.md for possible values, default values and explanation)

The simplest to test, you can set your broker message.max.bytes to a small value (for example 10 bytes). When you produce any data, you will receive a "Broker : Message size too large" exception (as 12 bytes is the minimum for header&co)

**Comment by CoderOverflow** [comment]
Thank you very much. I'll try it.:+1:

**Comment by CoderOverflow** [comment]
I set the message.max.bytes=1000 in the server side.
When I send a payload which length is 999 bytes, Broker : Message size is too large error happens.
Why?

**Comment by treziac** [comment]
message.max.bytes is whole message size with metadata, not only payload (you send the key, the payload length, the key length, etc). I think it was 12bytes, but this may have change (and may change in the future)

**Comment by CoderOverflow** [comment]
That's OK
How to know which payload is in error when the broker is return error? 
I tried getting message.payload(). It returns an address.
How to use message.payload() function?

**Comment by edenhill** [comment]
payload() returns the pointer to the payload (which may your original pointer you passed to produce() or a copy, depending on msgflags,  message size, etc).

You should typically use the msg_opaque as per-message reference to be able to map a delivery report callback's message back to your own object.

https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1356

**Comment by CoderOverflow** [comment]
Hi, @edenhill 

Is the usage like the following code?
I pass the whole payload massage to msg_opaque when produce method is called.

```
class ExampleDeliveryReportCb : public RdKafka::DeliveryReportCb {
public:
	void dr_cb(RdKafka::Message &message) {
		
		std::cout << "Message delivery for [" << "]\n(" << message.len() << " bytes): " <<
			message.errstr() << std::endl;
		if (message.key())
			std::cout << "Key: " << *(message.key()) << ";" << std::endl;
		if (message.err())
		{
			char *p = (char *)message.msg_opaque();
			std::cout << "Error: " << p << "\n" << message.err() << ";" << std::endl;
		}
	}
};
```

 
```
RdKafka::ErrorCode resp = producer->produce(topic_str, partition,
		RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
		(void *)"111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
					", 999,
		NULL, 0, 0, "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
				1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\
					");
```

**Comment by edenhill** [comment]
Passing the payload in msg_opaque seems uneccesary since the payload is already in `payload()`, you should typically use something that allows you to reference whatever original object you attempted to produce and now got a delivery report for.
If you have no need to track the original object you need to use msg_opaque.

**Comment by CoderOverflow** [comment]
I have problem with my program I don't know what to do :( 
I add
        ExampleDeliveryReportCb ex_dr_cb;
	conf->set("dr_cb", &ex_dr_cb, errstr);
to my source code. When I run it, the error “ Access violation writing location 0xCCCCCCCC.” has happend.



## ProducerPool.h
```
#include <vector>
#include <iostream>
#include <thread>
#include <map>
#include <random>
#include "librdkafka/rdkafkacpp.h"
namespace std
{
#define  PRODUCERPOOL_MAX_NUM 64
	class ExampleDeliveryReportCb : public RdKafka::DeliveryReportCb {
	public:
		void dr_cb(RdKafka::Message &message) {
			std::cout << "Message delivery for (" << message.len() << " bytes): " <<
				message.errstr() << std::endl;
			if (message.key())
				std::cout << "Key: " << *(message.key()) << ";" << std::endl;
		/*	if (message.err())
			{
				char *p = (char *)message.msg_opaque();
				std::cout << "Error: " << p << "\n" << message.err() << ";" << std::endl;

			}*/
		}
	};
	class ExampleEventCb : public RdKafka::EventCb {
	public:
		void event_cb(RdKafka::Event &event) {
			switch (event.type())
			{
			case RdKafka::Event::EVENT_ERROR:
				std::cerr << "ERROR (" << RdKafka::err2str(event.err()) << "): " <<
					event.str() << std::endl;
				/*if (event.err() == RdKafka::ERR__ALL_BROKERS_DOWN)
					run = false;*/
				break;

			case RdKafka::Event::EVENT_STATS:
				std::cerr << "\"STATS\": " << event.str() << std::endl;
				break;

			case RdKafka::Event::EVENT_LOG:
				fprintf(stderr, "LOG-%i-%s: %s\n",
					event.severity(), event.fac().c_str(), event.str().c_str());
				break;

			default:
				std::cerr << "EVENT " << event.type() <<
					" (" << RdKafka::err2str(event.err()) << "): " <<
					event.str() << std::endl;
				break;
			}
		}
	};

	class ProducerPool
	{
		
		std::vector<RdKafka::Producer*> _producerPool;
		
		int _count = 0;
		map<string, string> _mapConf;
		std::vector<std::string> _confList;
	public:
		inline ProducerPool(void) {};
		inline ProducerPool(unsigned short size) { 
			_count = size;
			createPool(size);
		}
		inline ~ProducerPool()
		{

			for (size_t i = 0; i < _count; i++) {
				if (_producerPool[i] != nullptr) {
					delete _producerPool[i];
				}
			}

			//RdKafka::wait_destroyed(5000);
		}

	public:
		void loadConf(map<string, string> mapConf)
		{
			_mapConf = move(mapConf);
			//return m_mapConf;
		}
	public:
		RdKafka::Producer* initializeProducer()
		{
			std::string errstr;
			std::string brokers = "127.0.0.1";
		//	std::string errstr;
			std::string topic_str = "linli";
			std::string mode;
			std::string debug;

			int32_t partition = RdKafka::Topic::PARTITION_UA;
			int64_t start_offset = RdKafka::Topic::OFFSET_BEGINNING;
			bool do_conf_dump = false;
			int opt;
			// MyHashPartitionerCb hash_partitioner;
			int use_ccb = 0;

			RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
			//RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

			conf->set("metadata.broker.list", brokers, errstr);
			conf->set("log.connection.close", "false", errstr);
			conf->set("queue.buffering.max.ms", "0", errstr);
			conf->set("socket.blocking.max.ms", "1", errstr);


			//map<string, string>::iterator iter;
			//for (iter = _mapConf.begin(); iter != _mapConf.end(); iter++)
			//{
			//	conf->set(iter->first, iter->second, errstr);
			//}
			ExampleDeliveryReportCb ex_dr_cb;

			///* Set delivery report callback */
			conf->set("dr_cb", &ex_dr_cb, errstr);

			//ExampleEventCb ex_event_cb;
			//conf->set("event_cb", &ex_event_cb, errstr);


			RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);

			return producer;
		}
		RdKafka::Producer* getProducer() {
			std::random_device rd;
			std::mt19937 gen(rd());
			std::uniform_int_distribution <> dis(0, _count - 1);
			
			return _producerPool[dis(gen)];

		}

		void createPool(unsigned short size) {
			if (_producerPool.size() > 0) return;

			_count = size;
			std::vector<RdKafka::Producer*> producerList(_count);
			for (size_t i = 0; i < _count; i++) {
				producerList[i] = initializeProducer();
			}
			_producerPool = std::move(producerList);

		}
	};
}
```
## MyProducePoolTest.cpp
```
#include "stdafx.h"
#include <iostream>
#include "ProducerPool.h"
#include "librdkafka/rdkafkacpp.h"
std::ProducerPool myProducer;
int main()
{
	try {

		//myProducer.loadConf(map1);
		myProducer.createPool(1);
		std::string ppp("111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111");

		std::thread t1(producer_4, myProducer.getProducer(), ppp);
		t1.join();
		

		system("PAUSE");
		return 0;
	}

	catch (std::exception& e)
	{
		std::cout << "some unhappy happened...  " << std::this_thread::get_id() << e.what() << std::endl;
	}
}

```

**Comment by treziac** [comment]
You should not create a pool of producer/consumer/ Use a single instance, it will be more efficient (only reason to use a pool would be if you have multiple cluster). Well, if this is only for test, then no problem

There is no flush in the last code you provided, there is one in your error.

Also, you can't cast from string to char*, this is what you seem to do in your delivery callback.

Alos, you can look at wiki, samples and headers for proper api usage :)

**Comment by CoderOverflow** [comment]
Hi @treziac 
Sorry, I forgot it. I've updated it.

I am not sure that one producer can support how many worker thread in my program.
So I wrote this pool to test it. the pool size also can be set by 1 a single instance.

the program runs well if I remove the line of conf->set("dr_cb", &ex_dr_cb, errstr);. 

I have commented out the char* part, I think I can use message.payload() to save it to the disk when error occurs. But how to get the message.payload()'s form void* to a text content? Should I use memcpy?

**Comment by treziac** [comment]
Look at verifiableClient example:

https://github.com/edenhill/librdkafka/blob/master/examples/kafkatest_verifiable_client.cpp#L259
https://github.com/edenhill/librdkafka/blob/master/examples/kafkatest_verifiable_client.cpp#L818

this is without opaque (from byte array, you can directly recopver the string)

msg_opaque is to use when you want the callback to reference some other object you can't retrieve directly from payload - this is not your case. You also did not provide msg_opque in your simple (it's the last parameter from produce passed as a pointer. This is documented here: https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1996

I would advise you to read the introduction to confluent clients there:
http://docs.confluent.io/current/clients/consumer.html#c-c-client-librdkafka
http://docs.confluent.io/current/clients/producer.html
You can also find doxygen doc for librdkafkac++ here : 
http://docs.confluent.io/current/clients/librdkafka/index.html

**Comment by CoderOverflow** [comment]
Thank you for your information. It's very helpful.
I will simplify my program and create a new ticket for Access violation when using DR_cb

**Comment by CoderOverflow** [comment]
Hi @edenhill 
Does the msg_opaque parameter be copied inside automatically?
Should I allocate memory for it? and release it in the callback function?

**Comment by edenhill** [comment]
It is just a pointer, it is your responsibility to ensure whatever memory
or object the pointer points to is valid in both the produce() call as well
as the delivery report.

Den 5 jul 2017 17:01 skrev "CoderOverflow" <notifications@github.com>:

**Comment by CoderOverflow** [comment]
I see
