### ISSUE TITLE
delivery report callback do not return acknowledgement for every message

### ISSUE THREAD

**Issue by kanchan1234** [edenhill/librdkafka#1283]
Description
===========
I am using librdkakfa 0.9.3 in RHOS
Red Hat Enterprise Linux Server release 7.1 (Maipo)
i have set dr_msg_cb to get delivery report for each message
here is the function def:
```
static void dr_msg_cb (rd_kafka_t *rk,const rd_kafka_message_t *rkmessage, void opaque) {
if (rkmessage->err)
fprintf(stderr, "%% Message delivery failed: %s\n",rd_kafka_err2str(rkmessage->err));
else
fprintf(stderr,"%% Message delivered (%zd bytes, " "Partition %"PRId32")\n",
rkmessage->len, rkmessage->partition);
/ The rkmessage is destroyed automatically by librdkafka */
}
```
function call:
```
kafka_conf = rd_kafka_conf_new();
rd_kafka_conf_set_dr_msg_cb(kafka_conf, dr_msg_cb);
```
i observe that when i push 1k events to kafka producer
I get '% Message delivered (32 bytes, Partition 6) " for 217 times..
How can i understand the number of messages actually received by consumer
snippet code:
```
if( rd_kafka_produce(
                                kafka_topic, partition,RD_KAFKA_MSG_F_COPY, msg.msg,strlen(msg.msg),NULL,0,
                                NULL ) == -1 ) {
                                printf( "Could not send message to kafka\n" );
                                rd_kafka_poll(kafka_conn, 5/*block for max 1000ms*/);
                                                        }
                     else {
cnt_processed_msg++;
 rd_kafka_poll( kafka_conn, 0 );
     }
```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You only seem to call poll() after produce(), but if you produce() 1000 messages and then just wait for delivery you'll need to call poll() (or flush()) to serve delivery report callbacks.

**Comment by kanchan1234** [comment]
ok thenks for the reply...you mean to say i need to call poll() after producing every 1000 messages.??
if( rd_kafka_produce(
                                kafka_topic, partition,RD_KAFKA_MSG_F_COPY, msg.msg,strlen(msg.msg),NULL,0,
                                NULL ) == -1 ) {
                                printf( "Could not send message to kafka\n" );
                                rd_kafka_poll(kafka_conn, 5/*block for max 1000ms*/);
                                                        }
                     else {
cnt_processed_msg++;
 rd_kafka_poll( kafka_conn, 0 );
     }
// Wait for all messages to be delivered
    while( rd_kafka_outq_len( kafka_conn ) > 0 ) {
     rd_kafka_poll( kafka_conn, 1 );
 }

**Comment by edenhill** [comment]
Yes

**Comment by kanchan1234** [comment]
ok..i have this line
else {
cnt_processed_msg++;
if(( cnt_processed_msg%1000) == 0 ){
rd_kafka_poll(kafka_conn,1);
}
rd_kafka_poll( kafka_conn, 0 );
  }
but i see "% Message delivered (35 bytes, Partition 10)" appears 543 times but at consumer side i see that all 1000 messages has received
due to this inconsistency,i cannot figure out the in case of failure even that is the scenario where i push 5k events and only 4.5k gets delivered.

I tried to remove this inconsistency by setting 'request.required.acks = -1
but i got error Message delivery failed: Broker: Not enough in-sync replicas"

**Comment by edenhill** [comment]
We've been over this before, to re-iterate:
 * produce() is asynchronous, it will just enqueue the message for transmission (which happens later)
 * poll() needs to be called at regular intervals to serve delivery reports
 * even after you've stopped calling produce() you need to call poll() to make sure any outstanding message callbacks are triggered. Either call poll() until outq_len() returns 0, or just call flush(-1) which does the same thing.
 * If you specify acks=all (or -1 which is same thing) then your partition needs to be fully replicated: that is, if the topic was created with a replication factor of 3, then you must have 3 replica brokers available for produce to work.

**Comment by kanchan1234** [comment]
yes...u already gave me suggestions earllier...but actually after doing everythng still i cannot sync the data with the kafka producer.I could not figure out the reason behind this abnormal behaviour because the loss percent is also not constant

**Comment by edenhill** [comment]
Start off by fixing your cluster so that each topic is properly replicated.
Then look at client behaviour.
Compare example program behaviour to your own, if the example programs (e.g. rdkafka_example) works but yours doesn't then you know where to start looking.

**Comment by kanchan1234** [comment]
ok...so basically i need to set  min.insync.replicas as 3 because there are three brokers in cluster
I wl compare my code with example code

**Comment by treziac** [comment]
I would set min.insync.replicas at 2 in this case - if one broker is down, you don't want to stop all operation (and one broker will be down sometime, for example for rolling upgrade)
