### ISSUE TITLE
send error after changing brokers

### ISSUE THREAD

**Issue by HeChuanXUPT** [edenhill/librdkafka#1285]
Description
===========
after move one broker to a new kafka cluster, rdkafka client will send data to both clusters, and get many errors

* ERROR: Broker hostname updated ( keep about 10m )
* send multi-partition topic failed, errno 3, errinfo: No such process ( all the time )
* send some topics to both clusters, I expect client should not send data to kafka2

How to reproduce
================
0. two kafka clusters running, kafka1 and kafka2
1. start rdkafka client with a hostname which belong to cluster kafka1
2. keep producing data(different topics) to kafka1. kafka1 can receive the data
3. move one ip(broker) from kafka1 to kafka2
4. keep producing data

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.2
 - [x] Apache Kafka version: 0.10.2
 - [x] librdkafka client configuration: 
  broker.version.fallback=0.8.2
  statistics.interval.ms=60000
 - [x] Operating system: linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by HeChuanXUPT** [comment]
got it, thanks!
will you support this case, remove brokers that are not fit the origin configured cluster?

**Comment by edenhill** [comment]
Sorry, but there are currently no plans to support such a use-case, but the client could error out if it sees different clusterIds from different brokers (requiring broker >=0.10.2)
