### ISSUE TITLE
How to dump send queue messages to file, when flush timeout

### ISSUE THREAD

**Issue by nmred** [edenhill/librdkafka#1294]
Description
===========

C++ producer API, when kill process I call flush() API, if flush timeout only return ERR_TIME_OUT, how to get send queue message?

How to reproduce
================

I use invalid  kafka broker address create producer instance , then send message, call flush(), flush() return timeout

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.5-RC2
 - [ ] Apache Kafka version: 0.9
 - [ ] librdkafka client configuration:
 - [ ] Operating system:centos6.5
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

20170630 15:50:22.635048 140612087228896 INFO  Topic config:consume.callback.max.messages=0 - Producer.cpp:244
20170630 15:50:22.635481 140612087228896 INFO  Created producer rdkafka#producer-1 - Producer.cpp:250
20170630 15:50:22.635567 140611984287488 INFO  Start productor - Producer.cpp:118
20170630 15:50:23.635783 140611984287488 INFO  Send message - kafkap.cpp:26
20170630 15:50:23.635867 140611984287488 INFO  Start create topic object `test` - Producer.cpp:148
20170630 15:50:23.635880 140611984287488 INFO  0xFDC3B0 - Producer.cpp:150
20170630 15:50:23.635893 140611984287488 INFO  test - Producer.cpp:151
20170630 15:50:23.635901 140611984287488 INFO  0xFDD760 - Producer.cpp:152
20170630 15:50:23.636011 140611984287488 ERROR ERROR (Local: Broker transport failure): 10.13.4.161:9192/bootstrap: Connect to ipv4#10.13.4.161:9192 failed: Connection refused - Producer.cpp:31
20170630 15:50:23.636024 140611984287488 ERROR ERROR (Local: All broker connections are down): 1/1 brokers are down - Producer.cpp:31
20170630 15:50:24.636121 140611984287488 INFO  Send message - kafkap.cpp:26
^C20170630 15:50:26.146064 140612087228896 ERROR dedede 2 - kafkap.cpp:43
20170630 15:50:26.206660 140612087228896 ERROR Event loop stoped. - EventLoop.cpp:57
20170630 15:50:26.206740 140612087228896 ERROR Stopping productor. - Producer.cpp:108
20170630 15:50:27.206820 140612087228896 ERROR Stopping productor. - Producer.cpp:108
20170630 15:50:28.206995 140612087228896 ERROR Stopping productor. - Producer.cpp:108
20170630 15:50:29.207132 140612087228896 ERROR Stopping productor. - Producer.cpp:108
20170630 15:50:29.235881 140611984287488 ERROR Flush message timeout, message size:2 - Producer.cpp:189
20170630 15:50:30.207289 140612087228896 INFO  Stop kafka productor success - Producer.cpp:111

**Comment by treziac** [comment]
There is currently no API to purge librdkafka queue - you would have to wait for the message to timeout

Issue to add a purge API is tracked here:
https://github.com/edenhill/librdkafka/issues/990

**Comment by nmred** [comment]
@treziac  thank you
