### ISSUE TITLE
How to enable omkafka module on CentOS 5 32 bit ?

### ISSUE THREAD

**Issue by wess1984** [edenhill/librdkafka#1295]
Description
===========
I want to enable omkafka module in Rsyslog on centos 5 32 bit. I am currently using Rsyslog 8.16.0 version, and when I run, under rsyslog folder, this command "./configure --enable-omkafka". I get error "could not find rdkafka library". But I can't find a librdkafka library for 32 bit arch!

How to reproduce
================
cd rsyslog-8.16.0
./configure --enable-omkafka
configure: error: could not find rdkafka library

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.8.6
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [x] Operating system: CentOS 5 32-bit
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Try librdkafka version 0.9.5 or later.


Den 30 jun 2017 13:43 skrev "Oussama BEN BACCAR" <notifications@github.com>:

**Comment by edenhill** [comment]
This is really an omkafka problem:
Try removing -Werror on omkafka build, I dont know how but you could file an issue on that project instead.

**Comment by wangycc** [comment]
+ 1

**Comment by bruce87en** [comment]
Please see commit https://github.com/bruce87en/rsyslog/commit/87c8f478ebd0111c9c8d521020acffa42a4508c9
