### ISSUE TITLE
Enhancement: Add value check after dynamic_cast

### ISSUE THREAD

**Issue by prehistoric-penguin** [edenhill/librdkafka#1297]
Description
===========
It's better to add return value check after dynamic_cast, to prevent misusing. If the cast fails, the code will lead to a crash.
The code snippet is from [KafkaConsumerImpl.cpp](https://github.com/edenhill/librdkafka/blob/master/src-cpp/KafkaConsumerImpl.cpp#L39)
```cpp
  char errbuf[512];
  RdKafka::ConfImpl *confimpl = dynamic_cast<RdKafka::ConfImpl *>(conf);
  RdKafka::KafkaConsumerImpl *rkc = new RdKafka::KafkaConsumerImpl();
  rd_kafka_conf_t *rk_conf = NULL;
```

**Comment by edenhill** [comment]
If the dynamic_cast fails the function was passed the wrong type of argument, which is a bug in the caller, we don't need graceful handling for such cases.
