### ISSUE TITLE
SASL support

### ISSUE THREAD

**Issue by foreign** [edenhill/librdkafka#1300]
Hello,

I want to use kafka with kerberos.
Operating system is Red Hat.

On server side kerberos is installed.
Are installation of these packages enough on client before librdkafka compilation?

cyrus-sasl-devel.i686 : Files needed for developing applications with Cyrus SASL 
cyrus-sasl-devel.x86_64 : Files needed for developing applications with Cyrus SASL

**Comment by edenhill** [comment]
If those packages also provide the SASL mechanisms, then yeah, that should be sufficient.

Do note that from the next librdkafka version v0.11.0 (or current master), the SASL PLAIN and SASL SCRAM mechanisms are built-in and does not rely on cyrus-sasl (which provides GSSAPI/Kerberos).

**Comment by foreign** [comment]
I installed v0.11.0-RC2 but output for libsasl is failed.
I think if v0.11.0 is installed then cyrus-sasl installation is not necessary.
Am i right?

checking for libssl (by pkg-config)... failed
checking for libssl (by compile)... failed (disable)
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... failed (disable)
checking for libsasl (by pkg-config)... failed
checking for libsasl (by compile)... failed (disable)

**Comment by edenhill** [comment]
you will need libsasl2 for GSSAPI/Kerberos
