### ISSUE TITLE
Completely disabling auto commit

### ISSUE THREAD

**Issue by invector** [edenhill/librdkafka#1301]
Description
===========
I want to use consumer group with 2 librdkafka-based daemons that consume one topic. Want to commit offsets manually in each daemon once an hour. If one daemon is killed, for example, its partitions offsets must not be commited (another daemon must read this partitions from latest commited offset if I properly understand consumer groups logic). So here are questions I have:
* If i disable auto commit by setting "enable.auto.commit" option to "false", are offsets commited on call to consumer's close()? It's not desirable for me. If yes, can I avoid it somehow? I want complete control over commiting.
* I want to use commitSync() to commit once an hour. But I don't understand if it commits offsets stored in offsets storage and updated with auto.commit.interval.ms. And what happens if I set this interval to 0 and use commitSync()?

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
0.9.2
 - [x] Apache Kafka version: 
0.10.1.0
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
No offsets will be automatically committed (in the background or from close()) when enable.auto.commit=false.

commitSync() without params will commit the "stored offset", which is a lousy name for the offset of the last message passed to the application.
(see also `enable.auto.offset.store` and `rd_kafka_offset_store()` for manually controlling what offsets are "stored" for future commits).

Manual commits (e.g, commitSync()) does not use the auto.commit.interval.ms property in any way,
auto.commit.interval.ms is only used if enable.auto.commit=true.

**Comment by edenhill** [comment]
You should also upgrade to librdkafka v0.9.5 (or 0.11.0 in a week or two). v0.9.2 had some consumer bugs that have been fixed.

**Comment by ctrochalakis** [comment]
So, by using the following settings with a high level consumer:

```
enable.auto.commit=true
enable.auto.offset.store=false
auto.commit.interval.ms=10000
```

And by manually calling `rd_kafka_offset_store()` one  can control the exact offsets that will get auto-committed by kafka every 10s (and during `rd_kafka_consumer_close()`). Is that correct?

**Comment by edenhill** [comment]
@ctrochalakis Yep, that's the idea.

**Comment by edenhill** [comment]
You may also register an `offset_commit_cb` to get the commit results for each OffsetCommitRequest.
