### ISSUE TITLE
queue.buffering.max.kbytes default wrong?

### ISSUE THREAD

**Issue by trapexit** [edenhill/librdkafka#1304]
Description
===========
The default is 4,000,000 but according to the docs and [code ](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_conf.c#L646)the max value is 2,097,151 (INT_MAX / 1024).

And shouldn't the [overflow calculation compare](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L1397) against INT_MAX?

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): master

**Comment by edenhill** [comment]
Re 1: Yeah, that looks like a bug.
Re 2: The multiplicated value is stored in a size_t, thus the SIZE_MAX check.

**Comment by trapexit** [comment]
SIZE_MAX on 64bit systems will be equal to unsigned long long. That comparison won't function if it did overflow. And since the max value is actually INT_MAX shouldn't that not be the comparison? Looking at the standard you actually might want to explicitly use 2^31-1 since INT_MAX is only guaranteed to be ≥+32,767 and LONG_MAX can be equal to SIZE_MAX on 64bit.

Given that value doesn't seem to be set outside the config api and therefore bounded it in practice might not ever happen.
