### ISSUE TITLE
inconsistency between queued.max.messages.kbytes and queue.buffering.max.kbytes

### ISSUE THREAD

**Issue by trapexit** [edenhill/librdkafka#1305]
Description
===========
[queue.buffering.max.kbytes](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_conf.c#L643): kbytes = kibibytes (2^10)
[queued.max.messages.kbytes](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_conf.c#L571): kbytes = kilobytes (10^3)

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): master

**Comment by edenhill** [comment]
queue.buffering.max.kbytes is the producer queue, while queued.max.messages.kbytes is the consumer queue, and thus have different purposes.
But the maximum value should probably be synched, at least in favour of the producer.

**Comment by trapexit** [comment]
I understand they are used for different things but both are of unit 'kbytes' but they aren't actually the same unit. If both are set to the same value they end up being different in practice. If I want 1 megabyte each (2^20-1) I'll have to set the former to 1024 (1024 * 1024 = 1048576) and the latter 1049 (1049 * 1000 = 1049000).
