### ISSUE TITLE
Empty messages instead of TIMED_OUT in 0.11.0-RC2

### ISSUE THREAD

**Issue by rthalley** [edenhill/librdkafka#1306]
Description
===========

I have a toppar with no messages ever written to it.  Before RdKafka 0.11.0-RC2, the behavior was
for the C++ legacy consumer to return RdKafka::ERR__TIMED_OUT when the timeout had expired and no messages been read.

With 0.11.0-RC2, it instead returns RdKafka::ERR_NO_ERROR, and gives me a message with offset 0, key length 0, and size 0.  This makes my code unhappy as it's not getting a properly formed message.

How to reproduce
================

As described above.  Just make an empty toppar and try to consume it with RdKafka::Consumer.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.0-RC2
 - [x] Apache Kafka version: 0.10.2.0 and 0.11.0
 - [x] librdkafka client configuration: not relevant
 - [x] Operating system: macOS
 - [x] Using the legacy Consumer yes
 - [ ] Using the high-level KafkaConsumer no
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka  upon request :)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thank you, will investigate.

**Comment by rthalley** [comment]
I should clarify that when I say "before" I mean with 0.9.4 and earlier.  I haven't tried 0.9.5 or 0.11.0-RC1.

**Comment by edenhill** [comment]
@rthalley Can you verify the fix on master?
Thanks

**Comment by rthalley** [comment]
Fix confirmed, thanks!

**Comment by edenhill** [comment]
Sweet, thank you!
