### ISSUE TITLE
Pausing consumption resets offsets

### ISSUE THREAD

**Issue by mfontanini** [edenhill/librdkafka#1307]
Description
===========
I have some application which pauses and resumes consumption on one topic so as to throttle each partition individually. This works fine but I'm coming across some pretty bad issue where:

* The consumer offset lags are 0 when the consumer comes up
* I start consumption, get EOF on all partitions (no messages at all as there's no lag).
* I pause consumption on all partitions. This is done on purpose to fill some local queues for each partition.
* Then I resume consumption on all partitions. At this point, all my local queues are filled and I can actually start processing messages.

Normally this works fine, but when I start and get EOF on all partitions, at the point where I resume consumption, instead of consuming from the next offset, the `auto.offset.reset` policy, which I set to smallest, kicks in and I'm not consuming the entire topic from scratch, which is undesirable to say the least.

How to reproduce
================

I can reproduce this 100% of the times doing the following:

* Create a topic which has some messages.
* Consume all of them using consumer group id X and commit their offsets.
* Stop your consumer app
* Start a new consumer (using the same group id X) using `auto.offset.reset == smallest` and subscribe to the topic.
* Wait until partitions are assigned.
* Once they're assigned, pause consumption on all of them (e.g. `consumer.pause_partitions(consumer.get_assignment())`).
* Resume consumption on all of them (e.g. `consumer.resume_partitions(consumer.get_assignment())`).

Expected behavior: nothing happens as there are no messages to be consumed
Actual behavior: all of the messages are consumed again.

See the relevant log lines [here](https://gist.github.com/mfontanini/90ff98a79ab272a5fa7887a8c747fd9c).

So, without knowing much about the internals of librdkafka, it seems like since the library doesn't know any offset (because it got EOF initially), it somehow discards what the `OffsetFetchResponse` said and thinks it has an INVALID offset, which makes it end up going back to the beginning as the policy indicates.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.4
 - [x] Apache Kafka version: 0.10.1.0
 - [x] librdkafka client configuration: `enable.auto.commit=false, auto.offset.reset=smallest`
 - [x] Operating system: GNU/Linux (Ubuntu Xenial 64 bits)
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka provided in the "how to reproduce" section
 - [ ] Provide broker log excerpts
 - [ ] Critical issue: as much as you'll likely think this is some corner case, this affects me very badly as I rely on this behavior. Also, I already had to patch the code a bit since I've had issues with librdkafka ignoring some pause/resume operations if I don't poll in between, but that's another story.

**Comment by mfontanini** [comment]
Any update on this? I implemented another application that pauses consumption and hit this issue again, I'm surprised nobody has hit it before as it happens every single time and it only requires pausing consumption after hitting EOF.

**Comment by edenhill** [comment]
Will look into this soon.

**Comment by mfontanini** [comment]
I can confirm this is still happening on v0.11.1-RC1. The following code reproduces the issue 100% of the times. You just need a topic with one partition (see names used in `main`). When calling `consume_pause_resume` you end up consuming the entire topic, which shouldn't happen.

Also I noticed that in v0.11.1 (or somewhere in between that and v0.9.5), the next call to poll after calling pause/resume_partitions actually spits out a message whereas before this would always cause a timeout (or at least you always got a null message pointer). Did this behavior change? I thought doing a poll in those cases would basically force rdkafka to process the pause/resume event or something of the sorts.

```c++
#include <iostream>
#include <cassert>
#include <cppkafka/consumer.h>
#include <cppkafka/utils/buffered_producer.h>
#include <cppkafka/utils/consumer_dispatcher.h>

using namespace cppkafka;
using namespace std;

void produce(const string& broker, const string& topic) {
    Configuration config = {
        { "metadata.broker.list", broker }
    };
    const string payload = "hehe";
    BufferedProducer<string> producer{config};
    producer.produce(MessageBuilder(topic).payload(payload));
    producer.flush();
}

void consume(const string& broker, const string& group_id, const string& topic) {
    Configuration config = {
        { "metadata.broker.list", broker },
        { "group.id", group_id },
    };
    config.set_default_topic_configuration({ { "auto.offset.reset", "smallest" } });

    Consumer consumer{config};
    consumer.subscribe({ topic });

    ConsumerDispatcher dispatcher{consumer};
    dispatcher.run(
        [&](Message msg) {
            cout << "Received message: " << msg.get_payload() << endl;
            consumer.commit(msg);
        },
        [&](ConsumerDispatcher::EndOfFile, const TopicPartition& topic_partition) {
            dispatcher.stop();
        }
    );
}

void check_message(Message msg) {
    if (msg) {
        if (msg.get_error()) {
            if (msg.is_eof()) {
                cout << "Received EOF for partition " << msg.get_partition() << endl;
            }
            else {
                cout << "Received error: " << msg.get_error() << endl;
            }
        }
        else {
            cout << "Received message: " << msg.get_payload() << endl;
        }
    }
}

void consume_pause_resume(const string& broker, const string& group_id, const string& topic) {
    Configuration config = {
        { "metadata.broker.list", broker },
        { "group.id", group_id },
    };
    config.set_default_topic_configuration({ { "auto.offset.reset", "smallest" } });

    Consumer consumer{config};
    consumer.subscribe({ topic });

    cout << "Waiting for assignment\n";
    while (consumer.get_assignment().empty()) {
        check_message(consumer.poll());
    }

    cout << "Pausing\n";
    consumer.pause_partitions(consumer.get_assignment());
    check_message(consumer.poll());

    cout << "Resuming\n";
    consumer.resume_partitions(consumer.get_assignment());
    check_message(consumer.poll());

    cout << "Consuming\n";
    ConsumerDispatcher dispatcher{consumer};
    dispatcher.run(
        [&](Message msg) {
            cout << "Received message: " << msg.get_payload() << endl;
            consumer.commit(msg);
        },
        [&](ConsumerDispatcher::EndOfFile, const TopicPartition& topic_partition) {
            dispatcher.stop();
        }
    );
}
 
int main() {
    const string broker = "kafka-vm";
    const string topic = "test";
    const string group_id = "bug";

    cout << "Producing messages\n";
    produce(broker, topic);

    cout << "Consuming and committing\n";
    consume(broker, group_id, topic);

    cout << "Consuming\n";
    consume_pause_resume(broker, group_id, topic);
}
```

**Comment by mfontanini** [comment]
I think I know what the issue is here. In `rd_kafka_toppar_pause_resume`, when saving the offset of the last consumed message (`rktp->rktp_next_offset = rktp->rktp_app_offset`), the offset is invalid, because we actually never got a message (just EOFs). The value of `rktp_next_offset` before that assignment is actually correct. So it seems like there should be some special case to handle when no messages where consumed but the offset is known?

I can submit a PR but I'd like some guidance on what has to be changed as I don't know how the code works internally.
