### ISSUE TITLE
API to set custom memory allocator in librdkafka

### ISSUE THREAD

**Issue by roopabayar** [edenhill/librdkafka#1310]
Description
===========
I could not locate an API that could be used to set custom memory alloc/free function in librdkafka.
How do we achieve it?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
4da1061ad1d993f446e54356b9dbc82f4ef52583
 - [ x] Apache Kafka version: 
0.10.2
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
Linux/Ubuntu
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you explain how you are planning to use this?

Do you want to use separate allocator instances for each rd_kafka_t instance?

Do you want the allocator to be used for configuration settings as well (rd_kafka_conf_t ..)?

**Comment by roopabayar** [comment]
If i could register my malloc and free function with the library, i will
have better visibility to the memory used. This would work for any of the
objects.

For ex: I am calling the rd_kafka_produce function for which i am passing
the buffer pointer and asking library to free it by setting flags
RD_KAFKA_MSG_F_FREE. My memory allocator is accounting the allocations, but
is not able to account for the free as the free is done using RD_FREE
(free).


Thanks
Roopa

**Comment by eugpermar** [comment]
Hi, @roopabayar ! I have a similar use case (many messages in the same memory chunk buffer, with reference counter). I use the delivery report callback to reduce reference counter & free.

You could add bytes to your counter just after the successfully produce(), and subtract it in delivery report callback. What you can't account this way is librdkafka internal allocations, but they should be insignificant against a lot of messages memory.
