### ISSUE TITLE
using the 'kafka-consumer-groups.sh" display  has no active members

### ISSUE THREAD

**Issue by jiayunwei** [edenhill/librdkafka#1312]
Description
===========
I set a unique consumer group using "group.id" and also set the "offset.store.method" to broker using the high configuration APIs for the consumer. The consumer is receiving the messages without any problems. Yesterday I am using the 'kafka-consumer-groups.sh ' normally, but today display  has no active members;
How to reproduce

Checklist
=========
Please provide the following information:

 - [] librdkafka version (release number or git tag):0x00090200
 - [ ] Apache Kafka version: 0.10.2.1
 - [ ] librdkafka client configuration:
builtin.features = gzip,snappy,ssl,regex
client.id = rdkafka
metadata.broker.list = 
message.max.bytes = 1000000
message.copy.max.bytes = 65535
receive.message.max.bytes = 100000000
max.in.flight.requests.per.connection = 1000000
metadata.request.timeout.ms = 60000
topic.metadata.refresh.interval.ms = 300000
topic.metadata.refresh.fast.cnt = 10
topic.metadata.refresh.fast.interval.ms = 250
topic.metadata.refresh.sparse = true
socket.timeout.ms = 10000
socket.blocking.max.ms = 100
socket.send.buffer.bytes = 0
socket.receive.buffer.bytes = 0
socket.keepalive.enable = false
socket.max.fails = 3
broker.address.ttl = 1000
broker.address.family = any
reconnect.backoff.jitter.ms = 500
statistics.interval.ms = 0
enabled_events = 0
log_cb = 0x434d50
log_level = 6
log.thread.name = true
log.connection.close = true
socket_cb = 0x442d20
open_cb = 0x4551f0
opaque = 0x8b8b68
default_topic_conf = 0x8b8af0
internal.termination.signal = 0
api.version.request = false
api.version.fallback.ms = 1200000
broker.version.fallback = 0.9.0
security.protocol = plaintext
group.id = test
partition.assignment.strategy = range,roundrobin
session.timeout.ms = 30000
heartbeat.interval.ms = 1000
group.protocol.type = consumer
coordinator.query.interval.ms = 600000
enable.auto.commit = false
auto.commit.interval.ms = 5000
enable.auto.offset.store = true
queued.min.messages = 100000
queued.max.messages.kbytes = 1000000
fetch.wait.max.ms = 500
fetch.message.max.bytes = 1048576
fetch.min.bytes = 4096
fetch.error.backoff.ms = 500
offset.store.method = broker
enable.partition.eof = true
queue.buffering.max.messages = 100000
queue.buffering.max.kbytes = 4000000
queue.buffering.max.ms = 1000
message.send.max.retries = 2
retry.backoff.ms = 100
compression.codec = none
batch.num.messages = 10000
delivery.report.only.error = false
request.required.acks = 1
request.timeout.ms = 5000
message.timeout.ms = 300000
produce.offset.report = false
compression.codec = inherit
auto.commit.enable = true
auto.commit.interval.ms = 60000
auto.offset.reset = smallest
offset.store.path = .
offset.store.sync.interval.ms = -1
offset.store.method = broker
consume.callback.max.messages = 0
 - [ ] Operating system:linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer yes
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It is possible that the committed offsets have expired (offset topic's retention time) and no new messages have been seen or committed by the consumer since then.
