### ISSUE TITLE
librdkafka cause kafka ERROR Processor got uncaught exception. (kafka.network.Processor) java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by wangzhicheng2013** [edenhill/librdkafka#1316]
Description
===========
I use librdkakfa and write the codes in rdkafka_simple_producer.c
8 //      while (run && fgets(buf, sizeof(buf), stdin)) {
169         int loop = 0;
170         while (run) {
171                 if(loop++ > 1000) break;
172                 strcpy(buf, "abc123ZTE");
173                 size_t len = strlen(buf);
174 
175                 if (buf[len-1] == '\n') /* Remove newline */
176                         buf[--len] = '\0';
177 
178                 if (len == 0) {
179                         /* Empty line: only serve delivery reports */
180                         rd_kafka_poll(rk, 0/*non-blocking */);
181                         continue;
182                 }

How to reproduce
================
run the rdkafka_simple_producer
the kafka will show:
[2017-07-11 02:13:29,911] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
[2017-07-11 02:19:41,287] INFO [Group Metadata Manager on Broker 93]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):0.11
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by wangzhicheng2013** [comment]
please help with the issue

**Comment by edenhill** [comment]
What is your broker version?
What is your exact librdkafka version? (0.11 is not a released version)

The broker typically logs a backtrace for each exception, can you check your broker logs to see if that "got uncaught exception" log message is followed by an exception backtrace?

**Comment by wangzhicheng2013** [comment]
1.kafka_2.11-0.9.0.0
2.librdkafka 0.11.0.x
3. kafka server.log
[2017-07-11 09:27:32,589] ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException

**Comment by edenhill** [comment]
Can you paste 10 lines above and below that ArrayIndexOutOfBoundsException log line from the broker log? (include that line too)

**Comment by wangzhicheng2013** [comment]
I am sorry when I start debug mode and watch the server.log only 
Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException
shows

**Comment by wangzhicheng2013** [comment]
Dear edenhill:
I have two different code slice
there are all from rdkafka_simple_producer.c in the examples of librdkafka
one:
.......

        while (run && fgets(buf, sizeof(buf), stdin)) {
                size_t len = strlen(buf);

                if (buf[len-1] == '\n') /* Remove newline */
                        buf[--len] = '\0';

                if (len == 0) {
                        /* Empty line: only serve delivery reports */
                        rd_kafka_poll(rk, 0/*non-blocking */);
                        continue;
                }

                /*
                 * Send/Produce message.
                 * This is an asynchronous call, on success it will only
                 * enqueue the message on the internal producer queue.
                 * The actual delivery attempts to the broker are handled
                 * by background threads.
                 * The previously registered delivery report callback
                 * (dr_msg_cb) is used to signal back to the application
                 * when the message has been delivered (or failed).
                 */
        retry:
                if (rd_kafka_produce(
.............
the code uses fgets from stdin and when I run it,
it will show:
XXX
enqueue ....
delivery ...
when I input a line, the callback function will be called at once.
The second code silce:
int loop = 0;
while (run) {
   if(++loop > 10) break;
   strcpy(buf, "abc123");
   size_t len = strlen(buf);
.......
I used the strcpy, I run it in the server, and the callback functions will be called at last, in the back of "Flushing final messages"
But I run it in the PaaS as a micro service, the callback function will never show except I add sleep in the while state.
I think that the callback function leads to the mission of messages

**Comment by wangzhicheng2013** [comment]
I set  if (rd_kafka_conf_set(conf, "queue.buffering.max.ms", "0"
but it takes no effect

**Comment by wangzhicheng2013** [comment]
rd_kafka_flush will create a thread, but in PaaS it does not take effect timeout comes

**Comment by wangzhicheng2013** [comment]
/*
 * librdkafka - Apache Kafka C library
 *
 * Copyright (c) 2017, Magnus Edenhill
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * Simple Apache Kafka producer
 * using the Kafka driver from librdkafka
 * (https://github.com/edenhill/librdkafka)
 */

#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>

/* Typical include path would be <librdkafka/rdkafka.h>, but this program
 * is builtin from within the librdkafka source tree and thus differs. */
#include "rdkafka.h"
char buf[512];          /* Message value temporary buffer */
size_t len;
rd_kafka_t *rk;         /* Producer instance handle */
rd_kafka_topic_t *rkt;  /* Topic object */
rd_kafka_conf_t *conf;  /* Temporary configuration object */
/**
 * @brief Message delivery report callback.
 *
 * This callback is called exactly once per message, indicating if
 * the message was succesfully delivered
 * (rkmessage->err == RD_KAFKA_RESP_ERR_NO_ERROR) or permanently
 * failed delivery (rkmessage->err != RD_KAFKA_RESP_ERR_NO_ERROR).
 *
 * The callback is triggered from rd_kafka_poll() and executes on
 * the application's thread.
 */
static void dr_msg_cb (rd_kafka_t *rk,
                       const rd_kafka_message_t *rkmessage, void *opaque) {
        if (rkmessage->err)
                fprintf(stderr, "%% Message delivery failed: %s\n",
                        rd_kafka_err2str(rkmessage->err));
        else
                fprintf(stderr,
                        "%% Message delivered (%zd bytes, "
                        "partition %"PRId32")\n",
                        rkmessage->len, rkmessage->partition);

        /* The rkmessage is destroyed automatically by librdkafka */
}

int main (int argc, char **argv) {
        char errstr[512];       /* librdkafka API error reporting buffer */
        const char *brokers;    /* Argument: broker list */
        const char *topic;      /* Argument: topic to produce to */
		brokers = "127.0.0.1:9092";
//		brokers = "172.168.103.93:4531";
		topic = "test";
        /*
         * Create Kafka client configuration place-holder
         */
        conf = rd_kafka_conf_new();

        /* Set bootstrap broker(s) as a comma-separated list of
         * host or host:port (default port 9092).
         * librdkafka will use the bootstrap brokers to acquire the full
         * set of brokers from the cluster. */
        if (rd_kafka_conf_set(conf, "bootstrap.servers", brokers,
                              errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK) {
                fprintf(stderr, "%s\n", errstr);
                return 1;
        }
		if (rd_kafka_conf_set(conf, "queue.buffering.max.ms", "0",
								errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK) 
		{
				fprintf(stderr, "%s\n", errstr);
				return 1;
		}
        /* Set the delivery report callback.
         * This callback will be called once per message to inform
         * the application if delivery succeeded or failed.
         * See dr_msg_cb() above. */
        rd_kafka_conf_set_dr_msg_cb(conf, dr_msg_cb);

        /*
         * Create producer instance.
         *
         * NOTE: rd_kafka_new() takes ownership of the conf object
         *       and the application must not reference it again after
         *       this call.
         */
        rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf, errstr, sizeof(errstr));
        if (!rk) {
                fprintf(stderr,
                        "%% Failed to create new producer: %s\n", errstr);
                return 1;
        }
        /* Create topic object that will be reused for each message
         * produced.
         *
         * Both the producer instance (rd_kafka_t) and topic objects (topic_t)
         * are long-lived objects that should be reused as much as possible.
         */
        rkt = rd_kafka_topic_new(rk, topic, NULL);
        if (!rkt) {
                fprintf(stderr, "%% Failed to create topic object: %s\n",
                        rd_kafka_err2str(rd_kafka_last_error()));
                rd_kafka_destroy(rk);
                return 1;
        }
		FILE *fp = fopen("./1.txt", "r");
		if(!fp) goto next;
		while(fgets(buf, sizeof buf, fp))
		{
		len = strlen(buf);
		if (buf[len - 1] == '\n') buf[--len] = '\0';
        if (len > 0 && rd_kafka_produce(rkt, RD_KAFKA_PARTITION_UA, RD_KAFKA_MSG_F_COPY, buf, len, NULL, 0, NULL) == -1) 
		{
				fprintf(stderr, "%% Failed to produce to topic %s: %s\n", rd_kafka_topic_name(rkt), rd_kafka_err2str(rd_kafka_last_error()));
				if (rd_kafka_last_error() == RD_KAFKA_RESP_ERR__QUEUE_FULL) 
				{
						printf("ll");
				//		rd_kafka_poll(rk, 1000);
                }
        }
		else if(len > 0) 
		{
				fprintf(stderr, "%% Enqueued message (%zd bytes) for topic %s\n", len, rd_kafka_topic_name(rkt));
                rd_kafka_poll(rk, 0);
		}
		}
next:
		fclose(fp);
        fprintf(stderr, "%% Flushing final messages..\n");
//      rd_kafka_flush(rk, 10 * 1000 /* wait for max 10 seconds */);
        rd_kafka_flush(rk, 1 /* wait for max 10 seconds */);
        /* Destroy topic object */
        rd_kafka_topic_destroy(rkt);
        /* Destroy the producer instance */
        rd_kafka_destroy(rk);

        return 0;
}
-bash-4.2# ./rdkafka_simple_producer 
% Enqueued message (3 bytes) for topic test
% Flushing final messages..
pay attention no delivery message

**Comment by wangzhicheng2013** [comment]
It seems a bug

**Comment by edenhill** [comment]
`rd_kafka_flush(rk, 1 /* wait for max 10 seconds */);`

You are only waiting 1 millisecond for messages to be fully delivered and acknowledged, try using the original 10 seconds instead (10 * 1000).

Also, your produce if-condition will print "Enqueued message .." for empty lines when no message was actually enqueued.
