### ISSUE TITLE
How to make sure the dr_cb be invoked everytime?

### ISSUE THREAD

**Issue by CoderOverflow** [edenhill/librdkafka#1317]
Description
===========
I tested the dr_cb. 
I found the dr_cb will be missed to call sometimes when the timeout occurs.
I set an inaccessible address to test the timeout case.

"metadata.broker.list":"192.168.3.234:9092,
"log.connection.close":"false",
"queue.buffering.max.ms":"0",
"socket.blocking.max.ms":"1",
"message.timeout.ms":"3000"

after each produce() 
err = producer->flush(3000);  is called.

I tested the 10 messages. the log file recorded only 9 messages
2017-7-11 17:43:51  [10928]count1 1 count2 1 cound3 1 
2017-7-11 17:43:52  [callback]data
2017-7-11 17:43:55  [5040]count1 1 count2 1 cound3 1 
2017-7-11 17:43:56  [callback]data
2017-7-11 17:43:59  [16728]count1 1 count2 1 cound3 1 
2017-7-11 17:44:0  [callback]data	
2017-7-11 17:44:3  [16480]count1 1 count2 1 cound3 1 
2017-7-11 17:44:4  [callback]data
2017-7-11 17:44:7  [168]count1 1 count2 1 cound3 1 
2017-7-11 17:44:8  [callback]data	
2017-7-11 17:44:11  [16772]count1 1 count2 1 cound3 1 
2017-7-11 17:44:12  [callback]data	
2017-7-11 17:44:15  [17828]count1 1 count2 1 cound3 1 
2017-7-11 17:44:16  [callback]data
2017-7-11 17:44:19  [16304]count1 1 count2 1 cound3 1 
2017-7-11 17:44:20  [callback]data
2017-7-11 17:44:23  [2252]count1 1 count2 1 cound3 1 
2017-7-11 17:44:24  [callback]data
**2017-7-11 17:44:27  [2092]count1 1 count2 1 cound3 1** 

**It seems the last one is not correct.**

This log shows that the last task is running at work-thread[2092] and have called the produce method.
but the callback function is not invoked due to some reason.
the producer is a long-running object.
the current setting is that one thread calls produce() method only one time.
The parent thread will wait until sub work-thread done. (1 parent 1 sub thread very 4second) After each message,
both will exit.

This is the work thread source code
```
unsigned __stdcall ResendProcKafka(void * pData)
{
	CString strOut;
	CString strObj;
	CStringList *pStr = (CStringList *)pData;
	if (pStr == NULL || pStr->GetCount() <= 0)
		return 50;

	unsigned threadID = GetCurrentThreadId();
	short nStdCount = 0;

	int cou1 = 0;
	int cou2 = 0;
	int cou3 = 0;
	CString strPath = _T("");
	try {

		int length = pStr->GetSize();
		for (size_t i = 0; i < length; i++)
		{
			cou1++;
				RdKafka::Producer* producer;
				RdKafka::ErrorCode err;

				std::string payload;
				USES_CONVERSION;
				CString strOut;
				CString strOjbFullPath;
				strOjbFullPath = pStr->GetAt(pStr->FindIndex(i));

				CString strPayload;
				CStdioFile file(strOjbFullPath, CFile::modeRead); 
				file.ReadString(strPayload);
				file.Close(); 

				payload = W2A(strPayload.GetBuffer(strPayload.GetLength()));
				// kafka 
				if (g_bKafkaFlag == TRUE)
				{
					BOOL bErr = FALSE;

					producer = g_myProducer.getProducer();
					if (producer)
					{
						USES_CONVERSION;
						path1 = W2A(strFilePathMove);
						path2 = W2A(strOjbFullPath);
					
						payload += '|';
						payload += path1;
						payload += '|';
						payload += path2;
						payload += '|';
						payload += '1';
						cou2++;

						err = producer->produce(g_myProducer.TopicName,
							g_myProducer.Partition,
							RdKafka::Producer::RK_MSG_COPY,
							(void *)payload.c_str(),
							payload.size(),
							NULL,
							0,
							0,
							NULL);

						if (err == RdKafka::ErrorCode::ERR_NO_ERROR)
						{
							cou3++;
							err = producer->flush(g_myProducer.MessageTimeoutMax);
						}
						else
						{
							bErr = TRUE;
						}
					}
					else
					{
						bErr = TRUE;
					}
					
					if (bErr == TRUE)
					{
						
					}
				}
		}
	}
	catch (CException* e)
	{
		TCHAR szError[1024];
		e->GetErrorMessage(szError, 1024);
		CString strErr;
		strErr.Format(_T("Exception Happened %s "), szError);
		g_LogFile.Write(strErr);
		
		return 51;
	}

	CString de;
	de.Format(_T("[%d]count1 %d count2 %d cound3 %d [%s\n"), threadID, cou1, cou2, cou3, strPath);
	g_LogFile.Write(de);

	return 52;
}


```

How to reproduce
================

```
class ExampleDeliveryReportCb : public RdKafka::DeliveryReportCb {
public:
	void dr_cb(RdKafka::Message &message) {
		if (message.len() > 0) { 
			USES_CONVERSION;
			int32_t nResend = -1;
			CString strMsg;
			CString strErr(A2W(RdKafka::err2str(message.err()).c_str()));
			std::string strpl = std::string(static_cast<const char*>(message.payload()), message.len());
			std::vector<std::string> elems;
			boost::split(elems, strpl, boost::is_any_of("|"));
			
			CString strPayload = elems[0].size() > 0 ? A2W(elems[0].c_str()) : _T("");
			CString strPathTo = elems[1].size() > 0 ? A2W(elems[1].c_str()) : _T("");
			CString strPathFrom = elems[2].size() > 0 ? A2W(elems[2].c_str()) : _T("");
			nResend = elems[3].size() > 0 ? atoi(elems[3].c_str()) : -1;

			_tprintf(_T("[callback]")+strPayload + _T("\n"));

			if (message.err()) {

				// from resend procedure
				if (nResend == 1) {

					// resend
					_tprintf(_T("[Kafka]Move from [" + strPathFrom + "\n]to [") + strPathTo + _T("]\n"));
						...
				}
				//from normal procedure
				else	{
					// resend
					if (g_bResendCreateFileFlagKafka)	{
						....
					}
				}
			}
			else {
				if (nResend == 1) {
					_tprintf(_T("[Kafka]Success Resend:%s"), strPayload);
				}
				else	{
					_tprintf(_T("[Kafka]Success Send:%s"), strPayload);
				}
			}
		}
	}
};
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):591104
 - [x] Apache Kafka version: kafka_2.10-0.9.0.1
 - [x] librdkafka client configuration:{"metadata.broker.list":"192.168.2.100:9092","log.connection.close":"false","queue.buffering.max.ms":"0","socket.blocking.max.ms":"1","message.timeout.ms":"3000"}
 - [x] Operating system:windows10
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please fill out the checklist and provide samples of your produce() and delivery report code.

**Comment by edenhill** [comment]
Yes, you should allow for some extra time in flush().
