### ISSUE TITLE
Empty messages in consumer

### ISSUE THREAD

**Issue by sandeepReddyG** [edenhill/librdkafka#1318]
Description
===========
When executing sample consumer ,I am continuosly getting Read message at offset 0 with new commits after Mar 17 2017. Where as previously it used to give message when producer writes some message to topic.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Dup of #1306
