### ISSUE TITLE
Librdkafka version 0.9.5 on ubuntu

### ISSUE THREAD

**Issue by arpanshah29** [edenhill/librdkafka#1320]
Description
===========

librdkafka-dev only has 0.8.3 on the mirrors to readily apt-get install. Running into setup issues with confluent-kafka-python as a result

How to reproduce
================

attempt to install librdkafka and latest version of confluent-kafka-python on an ubuntu:trusty box or container

**Comment by edenhill** [comment]
librdkafka Debian packaging is maintained by Debian's Kafka team, and Ubuntu pulls in those packages at their own discretion. The librdkafka team is not involved in this process.

https://packages.ubuntu.com/source/artful/librdkafka

**Comment by ctrochalakis** [comment]
Debian & Ubuntu packages per release:

Debian: https://packages.debian.org/search?keywords=librdkafka&searchon=sourcenames&suite=all&section=all
Ubuntu: https://packages.ubuntu.com/search?keywords=librdkafka&searchon=sourcenames&suite=all&section=all
