### ISSUE TITLE
Creating partition along with creating topic

### ISSUE THREAD

**Issue by guruprasadkk** [edenhill/librdkafka#1321]
Hi Edenhill,

    Currently in librdkafka there is no way to specify no of partitions we need when we create the topic. It will take the value from num.partitions from server.properties to determine how many partitions it needs to create. But in java client we can specify that how many partitions we need while creating the topic. Do you have any plans of introducing this feature in librdkafka?

Regards,
Guru,

**Comment by treziac** [comment]
Hi

This feature is tracked in #986
