### ISSUE TITLE
High level consumer - big # of threads and consume call back not working

### ISSUE THREAD

**Issue by l-rossetti** [edenhill/librdkafka#1327]
Description
===========
I'm studying librdkafka to understand how the system can scale.
My setup is:
- single machine
- 2 brokers
- topic with 2 partition and replication-factor = 1

I run the rdkafka_consumer_example.cpp in order to compute the throughput I can achieve using the high level consumer. 
I'm executing the following command:
`rdkafka_consumer_example_cpp -g d test2 -b :9092,:9093 -f ccb`

 - 1st problem: 
I see 7 threads running:
![rdkafka_consumer_threads](https://user-images.githubusercontent.com/4290628/28223696-b883a0e6-68cc-11e7-9388-34cd91febdad.png)

I read in [issue #293](https://github.com/edenhill/librdkafka/issues/293)  that with 3 brokers it should spawn 7 threads (main+metadata.broker.list+metadata update), but I have 7 with 2 brokers. Why?

 - 2nd problem:
Since I read that using the consume_callback the performance are better, I enabled it through `-f ccb`  option. The thing is that the callback is never called. Following the function calls from the consume(), I found that in function `rd_kafka_consume0` of file `rdkafka.c` there is a call `rd_kafka_poll_cb(rk, rkq, rko, **RD_KAFKA_Q_CB_RETURN**, NULL);` . This last makes the called function returning from the if condition, and it never sets the consume callback; if I change the condition inside I'm able to execute the callback:
```

case RD_KAFKA_OP_FETCH:
                if (!rk->rk_conf.consume_cb ||
             //       cb_type == RD_KAFKA_Q_CB_RETURN || **condition commented**
                    cb_type == RD_KAFKA_Q_CB_FORCE_RETURN)
                        return RD_KAFKA_OP_RES_PASS; /* Dont handle here */
                else {
                        struct consume_ctx ctx = {
                                .consume_cb = rk->rk_conf.consume_cb,
                                .opaque = rk->rk_conf.opaque };

                        return rd_kafka_consume_cb(rk, rkq, rko, cb_type, &ctx);  **// return the callback**
```

 - 3rd problem:
I don't understand how the threads are working on the partitions. Once I made the callback working, I tried printing the thread ID inside the callback. The result is that for every message consumed, the PID is always the same (the main thread), but I was expecting to see two different with respect to the main one.  Am I missing something?

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.0 RC3
 - [x] Apache Kafka version: 0.11.0.0
 - [ ] librdkafka client configuration:
 - [ ] Operating system: 
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-internal-threads
