### ISSUE TITLE
[Need Sponsoring] Native Windows port

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#133]
A port of librdkafka to run on native Windows, built through Visual Studio, no reliance on cygwin et.al.

This sub-project needs sponsoring.

**Comment by edenhill** [comment]
There is now a native win32 port in testing in the win32 branch.

**Comment by michema** [comment]
Hi, Magnus:

Is the windows platform supported now? If so, when will the windows support be pushed to the branch for people use?

Thanks,

Michelle

**Comment by edenhill** [comment]
Hi,
the Win32 platform support is under development but is ready for testing.
I'd be happy to get more people trying it out, it is in the `win32` branch.
