### ISSUE TITLE
subscribing to only one partition from a topic

### ISSUE THREAD

**Issue by silviucpp** [edenhill/librdkafka#1330]
Description
===========

I'm trying to subscribe to only one partition of a topic using:

```c
rd_kafka_topic_partition_list_t *topics = rd_kafka_topic_partition_list_new(1);
rd_kafka_topic_partition_list_add(topics, "benchmark", 0);
if ((err = rd_kafka_subscribe(rk, topics)))
{
     fprintf(stderr, "%% Failed to start consuming topics: %s\n", rd_kafka_err2str(err));
     exit(1);
}
rd_kafka_topic_partition_list_destroy(topics);
```
But seems rebalance callback is called with all partitions and also I get messages from all parititons.

I'm missing something ?

Silviu

**Comment by edenhill** [comment]
You subscribe() to one or more topics and the distributed balanced consumer group functionality will assign a subset(0..N) of those partitions to your consumer based on the assignment strategy.

If you want to consume a specific set of partitions without the automatic rebalancing you shall use the assign() API.
