### ISSUE TITLE
Why does not librdkafka producer work when buffer queue full 

### ISSUE THREAD

**Issue by zijiaozeng** [edenhill/librdkafka#1331]
Description
===========
        Recently, I took stress test on librdkafka async api,  when the producer returns "Queue full", the producer does not send the messages to kafka any more, why?    the network traffic diagram of test mechine as below,  the blue line represents the rate of outflow , green areas represent rate of inflow
![image](https://user-images.githubusercontent.com/15360334/28315350-96d6de00-6bf0-11e7-87a8-5bc0ca685c3a.png)
        Could anyone help me?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.5
 - [x] Apache Kafka version:  0.9.0.0
 - [x] librdkafka client configuration:
              queue.buffering.max.messages    500000
              message.send.max.retries     3
              retry.backoff.ms    500
              queued.min.messages    1000000
              request.required.acks   1
 - [x] Operating system:
              center os
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by zijiaozeng** [comment]
I found the problem, when the buffer queue is full, I didn't execute poll(0),  produce interface only put message in queue， not the truth send

**Comment by edenhill** [comment]
That's right, produce() is asynchronous and if you've registered a delivery report callback you need to call poll() to serve it.

**Comment by zijiaozeng** [comment]
The in-flight message are those that have been sent to the broker but we still havent received an ack for.  Is it possible to never get the ack, causes messages to always exist in queues?

**Comment by edenhill** [comment]
The message will fail regardless after `message.timeout.ms` and trigger your delivery report callback with the ERR__MSG_TIMED_OUT error code.
