### ISSUE TITLE
What does "JoinGroup failed: Local: Message timed out" mean on the consumer?

### ISSUE THREAD

**Issue by johnrgregg3** [edenhill/librdkafka#1333]
Description
===========

I see this in my logs:

[2017-07-19 20:29:38,280] [21704] [kafka_analytics_consumer.py:793] [ERROR] Received message from broker 23.79.234.63:9092, but got error. code -192, name _MSG_TIMED_OUT, str JoinGroup failed: Local: Message timed out

I have seen MSG_TIMED_OUT on a producer, but I don't know what it means on a consumer. When this happens, within 2-4 seconds I see my on_assignment routine get called. Does this mean that this consumer failed to join its consumer group? This comes quite a while after the initial subscribe().

I am running confluent_kafka.libversion ('0.9.5', 591359) and confluent_kafka.version ('0.9.2', 590080), which is actually 0.9.4.

It seems like this comes out of the blue. I don't think any brokers or consumers came up or down at that time.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You are right that `MSG_TIMED_OUT` is mainly used for the producer, but it will also be emitted when any protocol request times out waiting for response from the broker.
In this the JoinGroupRequest went unanswered for `session.timeout.ms + 3000ms`.

This is most likely an issue with your cluster. If you've decreased session.timeout.ms you might want to increase it.

**Comment by johnrgregg3** [comment]
Under what circumstances do I issue a JoinGroup request? At the time I (the consumer) see this, I don't think I've done anything like a subscribe() for a while. I'm just idle, hanging out, then I see this. Is it something like my periodic stats triggering this?
