### ISSUE TITLE
Run-Time Check Failure #4 - Stack area around _alloca memory reserved by this function is corrupted

### ISSUE THREAD

**Issue by jhy871167495** [edenhill/librdkafka#1334]
Description
===========
On windows 7 and Windows 10 , rdkafka_consumer_example_cpp.exe pop up an exception message box
<img width="960" alt="2017-07-20" src="https://user-images.githubusercontent.com/3050754/28415803-e6a05116-6d83-11e7-853b-80642ca9707d.png">
<img width="960" alt="2017-07-20" src="https://user-images.githubusercontent.com/3050754/28415824-fadfcc6a-6d83-11e7-981b-aaeffa84f389.png">

How to reproduce
================
 - [ ] librdkafka version (release number or git tag):  0.10 and 0.11.0
 - [ ] Apache Kafka version: kafka_2.12-0.10.2.1
 - [ ] librdkafka client configuration: default
 - [ ] Operating system: Windows 7 x86  and Windows 10 x64
 - [ ] Using the legacy Consumer
run or debug rdkafka_consumer_example_cpp.exe

**Comment by edenhill** [comment]
What command line arguments are you passing to rdkafka_consumer_example_cpp?

**Comment by TaoOfFoo** [comment]
command line args: 
-g g1 -b localhost:9092 rdkafka
and
-g g1 -b localhost:9092 -z none -v rdkafka

**Comment by tschmidt76** [comment]
Was there any resolution to this issue? I am getting the exact same error using this example when returning from rd_kafka_anyconf_copy on windows 10.

cmdline args = -P -t sometpoic -b 127.0.0.1

>	rdkafkacpp_producer.exe!rd_kafka_anyconf_copy(int scope, void * dst, const void * src, unsigned __int64 filter_cnt, const char * * filter) Line 1540	C
 	rdkafkacpp_producer.exe!rd_kafka_conf_dup(const rd_kafka_conf_s * conf) Line 1550	C
 	rdkafkacpp_producer.exe!RdKafka::Producer::create(RdKafka::Conf * conf, std::basic_string<char,std::char_traits<char>,std::allocator<char> > & errstr) Line 68	C++
 	rdkafkacpp_producer.exe!main(int argc, char * * argv) Line 466	C++
 	rdkafkacpp_producer.exe!invoke_main() Line 65	C++

**Comment by edenhill** [comment]
@tschmidt76 Thank's for the analysis, seems reasonable.

**Comment by edenhill** [comment]
This should fix it, can you try it out?

Thanks

**Comment by TaoOfFoo** [comment]
nice. Works fine for me. 
Thanks
