### ISSUE TITLE
consumer is not working after rebalance in case you forward queues

### ISSUE THREAD

**Issue by silviucpp** [edenhill/librdkafka#1335]
Hello,

I'm not sure what I'm going wrong but after a rebalance some of consumers (even if they have partitions assigned) are no longer receiving messages. 

I also created a small app for replicating the problem.. I'm not sure what I'm doing wrong so any advice is welcome. If I restart the consumer messages are consumed.. so most probably something is wrong in the way I forward the queues.. 

Program to replicate is here:

https://www.dropbox.com/s/bexg1k32euq90tb/consumer_test.cc?dl=1

Silviu

**Comment by edenhill** [comment]
Forwarding queues from the high-level consumer is not officially supported yet, and while it should mostly work issues like this are important to show-case that this is a feature that needs proper vetting to sort out the corner-cases.

**Comment by edenhill** [comment]
For now, make sure to unforward the queues in your rebalance callback on REVOKE before calling the empty assign()

**Comment by silviucpp** [comment]
hmm how you unforward a queue ?

**Comment by edenhill** [comment]
Pass NULL for the forward-to queue:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2007

**Comment by silviucpp** [comment]
Hmm not sure if it's clear..

When I want to forward I do:

rd_kafka_queue_t* partition_queue = rd_kafka_queue_get_partition(rk, topic.c_str(), partition);
ASSERT(partition_queue);
rd_kafka_queue_forward(partition_queue, NULL);

And for that partition I consume messages from partition_queue pointer.. then to unforward I have to call again `rd_kafka_queue_forward(partition_queue, NULL);` ?

**Comment by edenhill** [comment]
Oh, right, sorry. To restore the original queue setup of the high-level consumer (where each partition is forwarded to the common consumer queue) you forward the partition queue to the consumer queue (queue_get_consumer())

**Comment by silviucpp** [comment]
Hello @edenhill ,

I changed the revoke part as you suggested : 

```c
for(auto it = queues.begin(); it < queues.end(); ++it)
{
      rd_kafka_queue_forward(*it, rd_kafka_queue_get_consumer(rk));
      rd_kafka_queue_destroy(*it);
}
```
But still the issue persist..

**Comment by silviucpp** [comment]
Hmm seems if you unforward the queue you don't have to call rd_kafka_queue_destroy(*it); any longer... removing this it's fixing the problem

**Comment by silviucpp** [comment]
OK so seems now the problem it's fixed with unforwarding queues, rebalancing working nice. 

But I still have a potential issue. I did a small app that consumes 30 messages then exits and tries to close properly the session. 

https://www.dropbox.com/s/bexg1k32euq90tb/consumer_test.cc?dl=1

Behavior it's odd.. when cleanup it's done I see the callback for rebalancing being called by `rd_kafka_consumer_close` and everything seems ok.

But if I try to start the process again after closed then the next rebalancing takes place after `session.timeout` which makes me believe that kafka didn't saw that shutdown for the previous client as being a clean one.. 

What do you think ?

Silviu

**Comment by silviucpp** [comment]
Hello @edenhill any idea on the last comment I sent you ?

**Comment by edenhill** [comment]
Please reopen if this is still an issue.

**Comment by silviucpp** [comment]
@edenhill this was fixed in librdkafka or calling rd_kafka_queue_forward(*it, rd_kafka_queue_get_consumer(rk)); is still needed ?

**Comment by edenhill** [comment]
It hasn't been explicitly fixed, but might have been resolved by other fixes.
The issue was closed due to inactivity.

**Comment by silviucpp** [comment]
Hello,

Thanks for the feedback.  I'll keep using `rd_kafka_queue_forward(*it, rd_kafka_queue_get_consumer(rk));`

Silviu
