### ISSUE TITLE
Producer continuously sends Metadata Requests for non-existing topic though Broker responds with UnknownTopic (3)

### ISSUE THREAD

**Issue by kfdx87** [edenhill/librdkafka#1336]
Description
===========
**Producer** instance is spamming **Broker** with **Metadata** requests for non-existing topic if **Topic** object has been created with a wrong (non-existing) name and given **Prodcuer** instance. Although **Broker** responds with **UnknownTopic (3)** error Producer continues to send these useless **Metadata** requests.

How to reproduce
================
1. Use **librdkafkacpp**.
2. Start network traffic capture with Wireshark.
3. Create global config. object, set mandatory config. properties.
4. Create **Producer** instance.
5. Create **Topic** instance using a wrong topic name (which doesn't exist on a Kafka cluster).
6. Inspect Wireshark capture: there is **Metadata** request / **Metadata** response (error code **UnknownTopic (3)**) exchnage in a loop.

Why does **Producer** can't handle **UnknownTopic (3)** and stop sending **Metadata** requests for a given topic? Is there any workaround / config. rules ?

![metadata req resp loop](https://user-images.githubusercontent.com/30352818/28476056-4355f7e8-6e57-11e7-9888-9ee9f81eaa3b.png)
[metadata.req.resp.loop.log.txt](https://github.com/edenhill/librdkafka/files/1166353/metadata.req.resp.loop.log.txt)

Checklist
=========
Please provide the following information:

 - [X] librdkafka version (release number or git tag): v0.9.5
 - [X] Apache Kafka version: 0.10
 - [ ] librdkafka client configuration: almost default 
 - [X] Operating system: Windows 8.1
 - [X] Using the legacy Consumer: no
 - [X] Using the high-level KafkaConsumer: no
 - [X] Provide logs (with `debug=..` as necessary) from librdkafka: attached, please refer to the **metadata.req.resp.loop.log** file.
 - [ ] Provide broker log excerpts
 - [X] Critical issue: maybe it's not critical, but it doesn't seem minor one.

**Comment by kfdx87** [comment]
Updated description for a pretty mardown look.

**Comment by edenhill** [comment]
librdkafka attempts to automatically recover from errors, in this case by keeping to monitoring the given topic for availability.
I do agree that there should be some backoff mechanism to avoid querying once per second, but from an operational perspective this isn't really an issue: the 1 req/s request rate is miniscule.

**Comment by kfdx87** [comment]
@edenhill, thanks for you response. By the way I found that library doesn't stop sending **Metadata** requests even after appropriate "bad" **Topic** objects are destroyed and new "good" **Topic** instance with correct name is created. Only workaround I found is to destroy all "bad" **Topic** objetcs, create a "good" **Topic** object and re-create a **Producer** instance.

**Comment by edenhill** [comment]
Topic objects are currently never really destroyed internally even when the application destroys all its references, only when the producer or consumer instance is destroyed will it be destroyed.
