### ISSUE TITLE
some questions about librdkafka consumer

### ISSUE THREAD

**Issue by duanyr** [edenhill/librdkafka#1339]
@edenhill 

First of all,thank you very much for last answer!

my librdkafka version is 0.9.5-pre0
Apache kafka version is 0.10.2.0

my question is:

1:how to get specified topic and partition offset info(eg:latest offset and consuming offset)  using librdkafka api?

2:Is there any problem if all my consumer instances using same group.id?

Really looking forward to your reply!

**Comment by merlin82** [comment]
1、use kafka-consumer-groups.sh command
2、no problem

**Comment by edenhill** [comment]
librdkafka based clients will use the new consumer API (not zookeeper) to commit offsets, you thus need to call kafka-consumer-groups.sh with --new-consumer.

The legacy tools or options that use zookeeper will not work.
