### ISSUE TITLE
a question about rdkafka_consumer_example.cpp

### ISSUE THREAD

**Issue by merlin82** [edenhill/librdkafka#1340]
Description
===========
in "msg_consume function", other error will stop program.
 if I don't set "run = false;", Does the program work properly when error is fix (like broker restart)?

void msg_consume(RdKafka::Message* message, void* opaque) {
  switch (message->err()) {
    default:
      /* Errors */
      std::cerr << "Consume failed: " << message->errstr() << std::endl;
      run = false;
  }
}

Checklist
=========
Please provide the following information:
librdkafka version 0.95
Apache Kafka version 0.10.2
Using the legacy Consumer

**Comment by edenhill** [comment]
Yes, librdkafka will relentlessly try to recover from all errors.
