### ISSUE TITLE
Segmentation fault when "produce" function called

### ISSUE THREAD

**Issue by hoseiney** [edenhill/librdkafka#1341]
Description
===========
We have a Ubuntu server and want to use librdkafka  with c++.
In this server we don't have internet access  so we should install all required packages offline
and seems all packages for Ubuntu  (librdkafka1 , librdkafka-dev with all dependencies) installed successfully.
In another server with internet access we have installed all packages online and create a producer and it works fine. But the same code in offline server returns error "Segmentation fault (core dumped)" 
when the "produce" method called. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):librdkafka-dev: 0.8.3 and librdkafka1: 0.9.1
 - [x] Apache Kafka version: 0.10
 - [ ] librdkafka client configuration:
 - [x] Operating system:Ubuntu 14.04
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
You are building with librdkafka 0.8.3 but using the 0.9.1 runtime library, this is fine for the C API, but the C++ API is not ABI-safe (it is API-safe though), so you need to recompile your program for the librdkafka version you want to use.

You should strive to use the latest librdkafka version, which is 0.11.0.
The release before that is 0.9.5.
