### ISSUE TITLE
lds-gen doesn't find python on FreeBSD

### ISSUE THREAD

**Issue by mutability** [edenhill/librdkafka#1342]
FreeBSD 10.3-RELEASE-p17, librdkafka v0.9.5
(Also seen on FreeBSD 11.0-RELEASE-p11)

Build fails with:

```
Generating linker script librdkafka.lds from rdkafka.h
env: python: No such file or directory
gmake[1]: *** [Makefile:71: librdkafka.lds] Error 127
```

FreeBSD has /usr/local/bin/python2 in PATH, but no "python" in PATH.
Build works after changing the shebang line of lds-gen.py to python2

**Comment by edenhill** [comment]
Calling `python2` seems to be safe on OSX and Ubuntu, will need to check other platforms as well.
