### ISSUE TITLE
Installing on HP Nonstop oss

### ISSUE THREAD

**Issue by siva2553326** [edenhill/librdkafka#1343]
Description
===========
I'm trying to install the library in HP Nonstop oss, where it supports only the C89 and C99.  I made some changes to the makefile and the object compiled did not used the native compiler, hope its because of the source used.

Please let me know how to port this library for Hp nonstop oss

How to reproduce
================
installing on Hp nonstop oss

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ X] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [] Critical issue

**Comment by poojaud123** [comment]
I am facing similar issues while porting librdkafka on HP Nonstop OSS(NONSTOP_KERNEL J06).
c89 version: T8164H01_01MAY2017_c89_28MAr2017_OSS_SPR_ACN

Had you been able to port this?
