### ISSUE TITLE
Memory leak 0.11.0.0

### ISSUE THREAD

**Issue by Qwedir** [edenhill/librdkafka#1344]
Description
===========
RAM Memory leak after start consume and wait few seconds. (10gb in ~10seconds)
php-rdkafka: 2.0.1
librdkafka version (runtime)	0.11.0-RC1
librdkafka version (build)	0.11.0.0

How to reproduce
================
Here a simple php code:
```
<?php
require(__DIR__ . '/vendor/autoload.php');
$rk = new RdKafka\Consumer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers('127.0.0.1');

$topic = $rk->newTopic('test', new RdKafka\TopicConf());
$topic->consumeStart(0, 0);

sleep(10000);
```

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.11.0-RC1
 - [ ] Apache Kafka version: 0.11.0.0 also try 0.10.2.0
 - [ ] librdkafka client configuration: default
 - [ ] Operating system: Ubuntu 16.04
 - [ ] Using the legacy Consumer: true
 - [ ] Using the high-level KafkaConsumer: false
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka:
 - [ ] Provide broker log excerpts
 - [ ] Critical issue: true

**Comment by edenhill** [comment]
I modified rdkafka_example.c to sleep after calling consume_start() and I can't reproduce this, the memory initially increases until the internal fetch message queue is full and then stays the same for the duration of the execution.

How are you measuring memory? VSS or Residential?
Do you get the same behaviour if putting the sleep() before the consumeStart() call?
Try running it with valgrind.

**Comment by Qwedir** [comment]
see in htop because php does not show memory usage (memory_get_usage(true))

**Comment by Qwedir** [comment]
I see in htop because php function memory_get_usage(true) does not show memory leak.
Also I detected that this happens when the PHP script processes something. In my case, it was a long write in cassandra. I try use sleep 1 second and reproduce this bug.
Downgrade to librdkafka 0.9.5 helped
