### ISSUE TITLE
Unnecessary TCP connection is kept between Producer and Kafka cluster

### ISSUE THREAD

**Issue by kfdx87** [edenhill/librdkafka#1345]
Description
===========
**librdkafka** library maintains the redundant TCP connection with one of the Kafka brokers (with the broker which was configured as a bootstrap server).

How to reproduce
================
1. Use C++ binding of **librdkafka** library.
2. Prepare Apache Kafka cluster with 3 brokers: X, Y and Z.
3. Create **Conf** object (of global type), set the broker X as a bootstrap server via **metadata.broker.list** config. property.
4. Create **Producer** object using that **Conf** object.
5. Create some **Topic** objects just in case (not sure that it's necessary, but it is a very usual step).
6. Monitor network connections between the test host and XYZ-cluster. There are 4 TCP connections between the test host and XYZ-cluster: 2 with X broker, 1 with Y broker and 1 with Z broker.
7. NOTE: **librdkafka** automatically recovers these 4 TCP connections, i.e. if any of them is killed via appropriate test tools, then it will be re-established.

Is it really needed to keep 2 TCP connections with broker X?

Checklist
=========
Please provide the following information:

 - [X] librdkafka version (release number or git tag): v0.9.5
 - [X] Apache Kafka version: 0.10.1
 - [ ] librdkafka client configuration:
 - [X] Operating system: Windows 8.1
 - [X] Using the legacy Consumer: no
 - [X] Using the high-level KafkaConsumer: no
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka: no, it's reproduced in 100% cases.
 - [ ] Provide broker log excerpts: no
 - [X] Critical issue: not critical

**Comment by edenhill** [comment]
To avoid redundant connections, make sure that the bootstrap.server hostnames and ports exactly match the broker's advertised.listeners.
See here: https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-broker-tcp-connections

**Comment by kfdx87** [comment]
Wow, perfect, it helps! @edenhill, thank you!
