### ISSUE TITLE
Metadata request failed when consumer receive topic from broker using SSL

### ISSUE THREAD

**Issue by duxinyuhi** [edenhill/librdkafka#1347]
Description
===========
producer can send topic,but consumer cannot receive topic from broker
Following is the error info of consumer:
% Subscribing to 1 topics
1501226250.726 RDKAFKA-4-METADATA: rdkafka#consumer-1: [thrd:main]: ssl://135.1.236.92:9093/bootstrap: Metadata request failed: Local: Timed out (61987ms)

How to reproduce
================
I do the steps as "Using SSL with librdkafka".
set broker's properties
# SSL
ssl.protocol = TLS
ssl.enabled.protocols=TLSv1.2,TLSv1.1,TLSv1
ssl.keystore.type = JKS
ssl.keystore.location = /home/cloud-user/kafka/ssl-dir/broker_sandbox-msg-1_server.keystore.jks
ssl.keystore.password = abcdefgh
ssl.key.password = abcdefgh
ssl.truststore.type = JKS
ssl.truststore.location = /home/cloud-user/kafka/ssl-dir/broker_sandbox-msg-1_server.truststore.jks
ssl.truststore.password = abcdefgh
# To require authentication of clients use "require", else "none" or "request"
ssl.client.auth = none
security.inter.broker.protocol=SSL
ssl.endpoint.identification.algorithm=HTTPS

set producer's properties 
./rdkafka_example -P -t hello -b 135.1.236.92:9093  -X security.protocol=ssl -X metadata.broker.list=135.1.236.92:9093 -X ssl.ca.location=/home/cloud-user/librdkafka/ca-cert -X ssl.certificate.location=/home/cloud-user/librdkafka/ssl-dir/1111/client_sandbox-msg-5_client.pem -X ssl.key.location=/home/cloud-user/librdkafka/ssl-dir/1111/client_sandbox-msg-5_client.key -X ssl.key.password=abcdefgh

producer:
% Type stuff and hit enter to send
1234567
% Sent 7 bytes to topic hello partition -1
2345678
...

consumer:
./rdkafka_consumer_example -b 135.1.236.92:9093 -X metadata.broker.list=135.1.236.92:9093 -X security.protocol=ssl -X ssl.ca.location=/home/cloud-user/librdkafka/ssl-dir/ca-cert -X ssl.certificate.location=/home/cloud-user/librdkafka/ssl-dir/client_sandbox-msg-6_client.pem -X ssl.key.location=/home/cloud-user/librdkafka/ssl-dir/client_sandbox-msg-6_client.key -X ssl.key.password=abcdefgh hello

% Subscribing to 1 topics
1501226250.726 RDKAFKA-4-METADATA: rdkafka#consumer-1: [thrd:main]: ssl://135.1.236.92:9093/bootstrap: Metadata request failed: Local: Timed out (61987ms)

Checklist
=========
Please provide the following information:

 - [√ ] librdkafka version (0.11.0-RC1-27-g1f7417):
 - [√ ] Apache Kafka version: 0.10.1.0
 - [ ] librdkafka client configuration:
 - [ √] Operating system:Red Hat Enterprise Linux Server release 7.3 (Maipo)
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by treziac** [comment]
Can you provide logs by setting "debug" configuration to "security"?

Are you using consumer and producer on same machine? If not, can you try to do it, using the same certificate for producer and consumer?

Also if not already done, upgrade to the 0.11 release rather than RC1

**Comment by duxinyuhi** [comment]
@treziac 
Many thanks!

Consumer and producer are on two machines and I use the same certificate for producer and consumer.

On consumer, I use /rdkafka_example  instead of ./rdkafka_consumer_example and set partition to 0, then SSL connection is successful on version RC1.
