### ISSUE TITLE
how catch the exception of rd_kafka_produce()

### ISSUE THREAD

**Issue by tinux2015** [edenhill/librdkafka#1348]
Description
===========
My kafkaServer is down,but when I call rd_kafka_produce() to produce message,the result of rd_kafka_produce() is success.How can I to catch the exception ?

the error infometion of librdkafka is like this:
%3|1501319304.414|ERROR|rdkafka#producer-1| [thrd:hostname9092/bootstrap]: hostname::9092/bootstrap: Connect to ipv4#hostname::9092 failed: **Connection refused**
%3|1501319304.414|ERROR|rdkafka#producer-1| [thrd:hostname:9092/bootstrap]: 1/1 **brokers are down**

but i can't catch it!!!

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):librdkafka-master
 - [ ] Apache Kafka version:  0.10.0.0
 - [ ] librdkafka client configuration:default
 - [ ] Operating system:SUSE Linux Enterprise Server 11 
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Register a deliveryReport callback (dr_msg_cb) and call poll() to serve it.

Messages will time out in the internal queue if they haven't been delivered in `message.timeout.ms` (def 5 min)

**Comment by tinux2015** [comment]
Thank U very much,let me try

**Comment by tinux2015** [comment]
It's not work...

I added a callback function : rd_kafka_conf_set_dr_msg_cb(MyKafkaConf, msgWritedCallback);
and I set timeout "500" :
("message.timeout.ms", "500");

Then I called rd_kafka_poll() after call rd_kafka_produce(),but nothing happened....

**Comment by rolandyoung** [comment]
Did at least 500ms elapse between your call to rd_kafka_produce() and your call to rd_kafka_poll() ? If you call _poll() straight away, it will have nothing to report.
Have a look at rdkafka_simple_producer.c (but notice that that program relies on the user to keep hitting 'enter' to pick up the delivery reports; in a real application you would poll from a repeating timer event.)

**Comment by rolandyoung** [comment]
I think this might be an FAQ: "Why does rd_kafka_produce() always succeed, even if theres is a problem connecting to the Kafka brokers?"
Answer: "Because librdkafka has put your message on its outbound queue and will will try to recover from the error for ``message.timeout.ms`` before reporting failure. Delivery failures are reported asynchronously; meanwhile your program can be notified (also asynchronously) about connection issues if it registers an error callback."

**Comment by tinux2015** [comment]
I added error cb function by rd_kafka_conf_set_error_cb(), it worked..
thans a lot @edenhill @rolandyoung 
best wishes

**Comment by edenhill** [comment]
@rolandyoung Added to FAQ, thank you!
