### ISSUE TITLE
[Question] producer - default partitioner

### ISSUE THREAD

**Issue by trigee** [edenhill/librdkafka#1349]
I would like to ask regarding the default partitioning for c++ producer. (not setting "partitioner_cb")

Testing shows that messages with the same key are alwyas sent to the same partition.

I understand from the documents that the default partitioner is random, which doesn't seem to be the case.

Can you please describe how partitioning behaves when no custom partitioner is provided via the "partitioner_cb" option?

**Comment by treziac** [comment]
Default partitioner is consistent random, not random
Kafka paradigm is that data with same keys should end up in same partition. Default partitioner computess CRC-32 of key % partitionCount to choose partition
