### ISSUE TITLE
rd_kafka_consume() 

### ISSUE THREAD

**Issue by tinux2015** [edenhill/librdkafka#1350]
Description
===========
It's a question:

When I produce rdkafka_example like this:
rdkafka_example -b localhost:9092 -C -o beginning -t A_TEST -p 0

It begin from offset[40], not offset[0],WHY?
Logger :
**optarg is [0][0]...
get_wmarks is [0].....
partition is [0], start_offset[-2].....% Message (offset 40, 131 bytes):
Message Payload hexdump (131 bytes):**

Thank you.

**Comment by treziac** [comment]
Your first message is at offset 40. Messages get deleted after a certain amount of time by the broker.

**Comment by tinux2015** [comment]
OH,yep,thanks a lot
