### ISSUE TITLE
librdkafa.so does not show dynamic linked libraries path

### ISSUE THREAD

**Issue by gmdun** [edenhill/librdkafka#1352]
Description
===========
i've build librdkafa successfully but while doing ldd librdkafka++.so it does not path for SASL, zlib and ssl shared library path
ldd librdkafka++.so
        linux-vdso.so.1 =>  (0x00007fff1d5ff000)
        librdkafka.so.1 => not found
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007ffb0fa40000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ffb0f82a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ffb0f496000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ffb0f211000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003bfb400000)

echo $LD_LIBRARY_PATH
/sv/app/oracle/product/12.1.0.2/lib

How to reproduce
================
here how i built and install kafka server using makefile
PKG_CONFIG_PATH=/home/work/zlib/product/zlib-1.2.8/lib/pkgconfig:/home/work/openssl-1.0.2j/lib/pkgconfig:/home/work/sasl/product/cyrus-sasl-2.1.26/lib/pkgconfig; export PKG_CONFIG_PATH; \
 LDFLAGS=-L/home/work/zlib/product/zlib-1.2.8/lib/ -L/home/work/openssl-1.0.2j/lib -L/home/work/sasl/product/cyrus-sasl-2.1.26/lib; export LDFLAGS; \
 cd $@ && ./configure --prefix=/home/work/librdkafa-master && make
make install

here is the output
-rwxr-xr-x 1 sv_app sv_app 8271328 Aug  1 16:22 librdkafka.a
-rwxr-xr-x 1 sv_app sv_app 4279613 Aug  1 16:22 librdkafka.so.1
lrwxrwxrwx 1 sv_app sv_app      15 Aug  1 16:22 librdkafka.so -> librdkafka.so.1
-rwxr-xr-x 1 sv_app sv_app 2306256 Aug  1 16:22 librdkafka++.a
-rwxr-xr-x 1 sv_app sv_app  899705 Aug  1 16:22 librdkafka++.so.1
drwxr-xr-x 2 sv_app sv_app    4096 Aug  1 16:22 pkgconfig
lrwxrwxrwx 1 sv_app sv_app      17 Aug  1 16:22 librdkafka++.so -> librdkafka++.so.1

but doing ldd shows sasl,ssl,zlib library shared library not found
dd librdkafka++.so
        linux-vdso.so.1 =>  (0x00007fffe39ff000)
        librdkafka.so.1 => /sv/app/10.00/librdkafka-master/rel/lib/librdkafka.so.1 (0x00007f008b956000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f008b640000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f008b42a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f008b096000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f008ae78000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f008ac62000)
        libcrypto.so.1.0.0 => not found
        libssl.so.1.0.0 => not found
        libsasl2.so.3 => /sv/app/10.00/sasl/product/cyrus-sasl-2.1.26/lib/libsasl2.so.3 (0x00007f008aa45000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f008a83d000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f008a638000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003bfb400000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f008a3b4000)

but if export the LD_LIBRARY_PATH i was able to the shared libraries path
export LD_LIBRARY_PATH=/home/work/openssl/product/openssl-1.0.2j/lib
export LD_LIBRARY_PATH=/home/work/sasl/product/cyrus-sasl-2.1.26/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/sv/app/librdkafka-master/rel/lib:$LD_LIBRARY_PATH  
ldd librdkafka++.so
        linux-vdso.so.1 =>  (0x00007fff8ebff000)
        librdkafka.so.1 => /home/work/librdkafka-master/rel/lib/librdkafka.so.1 (0x00007f255a3c8000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f255a0b2000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f2559e9c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2559b08000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f25598ea000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f25596d4000)
        libcrypto.so.1.0.0 => /home/work/openssl/product/openssl-1.0.2j/lib/libcrypto.so.1.0.0 (0x00007f255929e000)
        libssl.so.1.0.0 => /home/work/openssl/product/openssl-1.0.2j/lib/libssl.so.1.0.0 (0x00007f255902e000)
        libsasl2.so.3 => //home/work/sasl/product/cyrus-sasl-2.1.26/lib/libsasl2.so.3 (0x00007f2558e12000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f2558c0a000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f2558a05000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003bfb400000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f2558781000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f2558566000)

can some please tell without setting LD_LIBARAY_PATH, how can i achieve this

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system: 
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by tinux2015** [comment]
Copy libcrypto.so.1.0.0 and libssl.so.1.0.0 to the dir of librdkafka++.so,and achieve them together

**Comment by gmdun** [comment]
did you mean copy ibcrypto.so.1.0.0 and libssl.so.1.0.0 into librdkafka++.so dir. i did copy these two so files into same directory where librdkafa is present but still the same issue persist.
$ ls -lrt
total 18200
-rwxr-xr-x 1  kafadev kafadev 899705 Aug  2 20:57 librdkafka++.so.1
-rwxr-xr-x 1 kafadev kafadev 4211715 Aug  2 20:57 librdkafka.so.1
-rwxr-xr-x 1 kafadev kafadev 2306288 Aug  2 20:57 librdkafka++.a
-rwxr-xr-x 1 kafadev kafadev 8105854 Aug  2 20:57 librdkafka.a
lrwxrwxrwx 1 kafadev kafadev      15 Aug  2 20:57 librdkafka.so -> librdkafka.so.1
drwxr-xr-x 2 kafadev kafadev    4096 Aug  2 20:57 pkgconfig
lrwxrwxrwx 1 kafadev kafadev      17 Aug  2 20:57 librdkafka++.so -> librdkafka++.so.1
-r-xr-xr-x 1 kafadev kafadev 2585540 Aug  3 04:15 libcrypto.so.1.0.0
-r-xr-xr-x 1 kafadev kafadev  508363 Aug  3 04:15 libssl.so.1.0.0

ldd librdkafka.so.1
        linux-vdso.so.1 =>  (0x00007ffcdfb27000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc7c5aad000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fc7c5896000)
        libcrypto.so.1.0.0 => not found
        libssl.so.1.0.0 => not found
        librt.so.1 => /lib64/librt.so.1 (0x00007fc7c568d000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fc7c5489000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fc7c50f5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc7c5f8c000)

**Comment by edenhill** [comment]
In your first example `ldd` can't find librdkafka.so (because it is not in the standard search paths, the current directory is not searched), so it can't show the secondary librdkafka dependencies.
In your second example it does find librdkafka.so so it also shows librdkafka's dependencies.
