### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by silviucpp** [edenhill/librdkafka#1353]
Hello,

While working on https://github.com/silviucpp/erlkaf (which by the way in case you want you can add it to the bindings section as time it's completed from a functionality point of view) I found useful the following feature:

In case the connection between broker and driver dies and the internal queue get full erlkaf have a configuration to choose what to do with the new produce requests:

1. Block the calling process until librdkafka queue has enough space again (broker is up and messages start delivered again)
2. Drop new messages 
3. (default) Save the messages locally on a disk queue and once we have connection back with the broker we will send them to kafka

Everithing works fine but I need in order to make it reliable in case the  producer is stopped and I'm calling `rd_kafka_flush` to be able to get after this call returns all messages that are still in internal queue and were not sent to the broker because the method timed out 

Silviu

**Comment by edenhill** [comment]
(Please submit a PR for including your client in the README 👍 )

There is currently no API to forcefully drain the producer message queues, but there's enough demand for such an API now that we'll add it to the backlog.

Please see (and comment on) the API suggestion in issue #990
