### ISSUE TITLE
queue.buffering.max.kbytes default value is greater than maximum

### ISSUE THREAD

**Issue by mhowlett** [edenhill/librdkafka#1354]
Description
===========

the `queue.buffering.max.kbytes` default value is greater than the maximum range value (and very large). Is this intended?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by Tapppi** [comment]
@edenhill both `queue.buffering.max.kbytes` and `queued.max.messages.kbytes`have very hight defaults. Are the defaults in bytes even though the settings are in kbytes? That's what I'm thinking since queue.buffering.max.kbytes default is larger than max allowed..

**Comment by edenhill** [comment]
Dup #1304

**Comment by chebee7i** [comment]
In the standard Kafka documentation (https://kafka.apache.org/documentation/), librdkafka's `queue.buffering.max.kbytes` seems to correspond to the `batch.size` config parameter, only `batch.size` is in bytes not kibibytes.  The defaults seem to differ drastically, with librdkafka setting the default to: 2^{20} kibibytes = 2^{30} bytes = 1 GiB, while Kafka's documentation puts the default at 2^{14} bytes = 0.015625 MiB.  Even if I've misinterpreted the units in the Kafka documentation by a factor of 1024, the difference in defaults still seems large.

Can you comment on the motivation behind the difference? In https://www.confluent.io/wp-content/uploads/Optimizing-Your-Apache-Kafka-Deployment-1.pdf, their throughout settings suggest bumping `batch.size` up to 200000 ~ 2 Mib, which still pales in comparision to librdkafka's default.

**Comment by edenhill** [comment]
librdkafka's produce() API is truly asynchronous (the Java counterpart has edge-cases where it will block) and is usable right after client creation, before connections have been fully set up. 1 gigabyte of queue size corresponds to 5-10s of data at a high throughput rate, which seems like a reasonable time to allow for setting up connections to brokers and authenticating.

**Comment by chebee7i** [comment]
Thanks!
