### ISSUE TITLE
Librdkafka consumes (or produces) empty payloads and keys as null

### ISSUE THREAD

**Issue by webmakersteve** [edenhill/librdkafka#1357]
Description
===========
When producing a payload that is an empty string, it is read as NULL instead of as empty. In previous versions of librdkafka these elements were produced as non null. When tested on librdkafka 0.9.4 the following test passes.

How to reproduce
================
https://gist.github.com/webmakersteve/d541eff10ca0cd7d1ef311945d74109a

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11
 - [x] Apache Kafka version: 0.10.2
 - [ ] librdkafka client configuration:
 - [x] Operating system: Mac OS and Ubuntu
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That does sound like a regression, will look into it.
Thanks

**Comment by edenhill** [comment]
This was fixed in https://github.com/edenhill/librdkafka/commit/d15b541e972d8b433bbf85a216f106d5d9418211

Can you please verify the fix works for you?
