### ISSUE TITLE
Consuming message from unassigned partition after rebalance

### ISSUE THREAD

**Issue by mfontanini** [edenhill/librdkafka#1359]
Description
===========
I've come across this issue at least twice already. Basically after a rebalance occurs, I end up receiving a message from the previous assignment. I've already patched 2 applications to bypass this but I wondered if it's a known issue as it doesn't seem right.

How to reproduce
================
Not any specific code and I can't reproduce it consistently, I'm just completely sure it happens as I've seen it more than once on completely unrelated applications. Just consume, trigger a rebalance and see if you get data from an unassigned partition. Both applications subscribe to a single topic and use pausing/resuming on their assigned partitions, so maybe that somehow triggers this behavior?

I can't really provide logs as this only happens sporadically and I don't happen to have logging enabled at all times.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.9.4 but I've also seen it on older versions
 - [x] Apache Kafka version: 0.10.1.0
 - [x] librdkafka client configuration: nothing special, both `auto.reset.offset=latest/smallest` trigger it
 - [x] Operating system: GNU/Linux
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Do you have a rebalance callback registered?
If so: are you seeing messages from the previous assignment's partitions after you've called assign() from the rebalance callback?

Is this reproducible on librdkafka v0.11.0?
