### ISSUE TITLE
Static librdkafka compiled with Homebrew on OS X 10.11 depends on missing symbols.

### ISSUE THREAD

**Issue by Jose123456** [edenhill/librdkafka#1360]
Description
===========
Unfortunately Apple has decided to break backwards compatibility with their latest SDK releases. Setting SDKROOT like Homebrew insists on doing leads to the generation of static libraries which depend on symbols that don't exist in OS X 10.11. A librdkafka compiled with Homebrew contains a reference to _clock_gettime:
```
nm /usr/local/lib/librdkafka.a  | grep gettime
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _clock_gettime
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
                 U _gettimeofday
```
Trying to link statically with that archive fails like this:
```
Undefined symbols for architecture x86_64:
  "_clock_gettime", referenced from:
      _mtx_timedlock in librdkafka.a(tinycthread.o)
      __tthread_timespec_get in librdkafka.a(tinycthread.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
The offending code is here: https://github.com/edenhill/librdkafka/blob/0.11.0.x/src/tinycthread.c#L937. The very same code compiled outside of Homebrew does not contain the offending reference. This is on OSX 10.11.6 with Xcode 8.2.1.

The ridiculous amount of bureaucracy Apple expects you to implement is documented (badly) here: https://github.com/Homebrew/brew/issues/1550

Personally I'd reuse the code you already have [here](https://github.com/edenhill/librdkafka/blob/0.11.0.x/src/rdtime.h#L70) and sidestep the whole stinking mess.

I'd be happy to prepare a pull request implementing the latter approach if you like.

How to reproduce
================
`brew install librdkafka`

Try to build a binary that statically links to `/usr/local/lib/librdkafka.a`. I used: https://github.com/edenhill/librdkafka/blob/0.11.0.x/examples/rdkafka_consumer_example.c

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.0.x
 - [x] Apache Kafka version: Any
 - [x] librdkafka client configuration: Any
 - [x] Operating system: Mac OS X 10.11.6
 - [] Using the legacy Consumer: N/A
 - [] Using the high-level KafkaConsumer: N/A
 - [] Provide logs (with `debug=..` as necessary) from librdkafka: No binary = no logs
 - [] Provide broker log excerpts: No binary = no logs
 - [] Critical issue

**Comment by edenhill** [comment]
Thanks for a great report.

I agree that falling back on gettimeofday(), as rd_clock() does, seems like a reasonable and safe workaround and we'd be happy to accept such a PR!

**Comment by michelazzo** [comment]
Some chance this issue get patched anytime soon?

**Comment by Jose123456** [comment]
Unfortunately I no longer have an El Capitan system to test on. I'll grind this out if you want to test it for me.

**Comment by michelazzo** [comment]
Sure thing, my OS's version is still El Capitan.

**Comment by edenhill** [comment]
This does not seem to be a problem for people anymore, closing issue.
