### ISSUE TITLE
Produce failed: Local: Unknown topic

### ISSUE THREAD

**Issue by coberty** [edenhill/librdkafka#1362]
Hi
what could be the reason for this error? I noticed it in my logs but I cannot reproduce it.
A few times it was returned by a produce() call and a few times produce() was a success and it was reported by DeliveryCallback. 
Why is it not consistent? How should I deal with this error? Retry sending the message?

Thanks,
cob

**Comment by OTNewburn** [comment]
I am also having this problem. My producer will produce messages to a topic for hours and then for a few minutes throw "Produce failed: Local: Unknown topic" and then start working again. No other part of my code is touching the topic structure.

**Comment by edenhill** [comment]
UNKNOWN_TOPIC means the client thinks the topic (no longer) exists in the cluster, which should only be caused if the topic is indeed deleted, or if one of the brokers report that it does not know about the topic - which would indicate a problem on the brokers.
Check broker logs for any exception or log messages around the time you see this problem.

**Comment by combrinckd** [comment]
Just in case someone else also comes up with this issue, I have found a similar message on my side.
What I have found after a while was that one of my topics had a space in the name. Only after fixing the name removing white spaces, the problem went away..

Might be something to check.. 
:)
