### ISSUE TITLE
Weird behavior on big batch.num.messages

### ISSUE THREAD

**Issue by treziac** [edenhill/librdkafka#1363]
Description
===========

**librdkafka**: 0.9.4 to 0.11.0
**kafka**: 0.10.2.1 and 0.11.0
**os**: windows 10

When `batch.num.messages` is big, librdkafka will use huge amount of RAM (>30Go, app get shut down) , despite the fact the batch size is never reached (capped by message.max.bytes, only 1 message per batch)

Spotted when testing https://github.com/confluentinc/confluent-kafka-dotnet/issues/50#issuecomment-320227889

How to reproduce
================

Use following conf:

                {"message.max.bytes" , 10240}
                {"batch.num.messages", 10000}

Then produce data of 8192 size.

`debug: msg` show that 
`7|2017-08-07 16:40:25.843|test-client#producer-1|PRODUCE| ***: No more space in current MessageSet (1 message(s), 8319 bytes`
Which is normal, and there are no other related logs with debug=all . 
But `batch.num.messages` has unexpected behaviour

When set to 1, the program takes up to 2GB
With 1000, up to 5GB (with same time of execution)
10_000, up to 30GB
100_000, my process simply crash

**Comment by edenhill** [comment]
Do you think this could be related to the behaviour described here:
https://github.com/edenhill/librdkafka/wiki/FAQ#explain-the-consumers-memory-usage-to-me
(TLDR: not destroying consumed message objects will cause new messages to be fetched without freeing memory from the previous fetch)

**Comment by treziac** [comment]
It might. I think it's allocating a buffer from batch.num.message * some size for every message received, but does not check if it's bigger than message.max.bytes.
Increasing message.maxbytes will decrease memory, as I won't allocate a buffer for every message (many messages will fit the same buffer)
May do some debugging when I have time (which may not be before some days :/ )

What seems wrong is too allocate >30GB - would be fine to know what the max limit is
