### ISSUE TITLE
Question : what happens if with pending callbacks if RdKafka::Producer is deleted

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#1365]
Description
===========
Hi, I just want to make sure I don't do anything forbidden that would mess with the library : 
I have a **RdKafka::Producer myProducer** that has at least dr_cb callback registered.

let's say many messages are produced, and we haven't yet received the delivery report (let's say low bandwith,etc high latency,etc...) and I decide to do a **delete myProducer;** and create a new one, reconfigure it,etc...

How is librdKafka going to handle that ?

- Is librdKafka going to stop retrying to send the yet undelivered message from myProducer if it has the chance to ?
- If librdkafka knows the message has been delivered but myProducer is already deleted, what will happen ?
  - does the RdKafka::Producer destructor safely de-register the registered callback ?
or will it still try to call the method of the registered RdKafka::DeliveryReportCb::dr_cb method
( registered by using conf->set("dr_cb", myDeliveryReportCb Object, errstr))

because I am looking to see if it's safe to do as follows : 
```cpp
delete myProducer;
delete myDeliveryReportCb;
// and then continue with the creation of a new myProducer and myDeliveryReportCb instances.
```
So I wouldn't want that a call would be made to myDeliveryReportCb::dr_cb after it has been deleted.

Checklist
=========
Please provide the following information:

 - [ 0.9.4] librdkafka version (release number or git tag):
 - [10.0.1 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [Ubuntu 16.04 ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There is no co-operation or data-sharing between different RdKafka::Handle instances, once the Producer has been deleted the delivery report instance will not be used any more.

**Comment by vin-d** [comment]
Perfect, thank you.
