### ISSUE TITLE
appveyor artifacts

### ISSUE THREAD

**Issue by eaba** [edenhill/librdkafka#1366]
Description
===========
Help me https://ci.appveyor.com/project/edenhill/librdkafka/build/job/4h79hg7qbmde8lqf/artifacts downloadable in a zip file please.
cant get it to build on my machine

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You should typically reference the librdkafka.redist package from NuGet: https://www.nuget.org/packages/librdkafka.redist

**Comment by eaba** [comment]
Thanks!
