### ISSUE TITLE
kafa client can't get data from the server

### ISSUE THREAD

**Issue by huangjunyi1** [edenhill/librdkafka#1383]
Description
===========
When I restart the client : 
%5|1503105134.515|TOPICBRK|rdkafka#consumer-0| Topic Alarm [0] migrated to unknown broker 1: requesting metadata update

And then the error is: 
%3|1503104662.792|ERROR|rdkafka#consumer-0| 208.208.180.162:9092/3: Receive failed: Disconnected
%3|1503105262.836|FAIL|rdkafka#consumer-0| 208.208.180.162:9092/3: Receive failed: Disconnected
%3|1503105262.836|ERROR|rdkafka#consumer-0| 208.208.180.162:9092/3: Receive failed: Disconnected
%3|1503105262.990|FAIL|rdkafka#consumer-0| 208.208.180.151:9092/1: Receive failed: Disconnected
%3|1503105262.990|ERROR|rdkafka#consumer-0| 208.208.180.151:9092/1: Receive failed: Disconnected

How to reproduce
================

Checklist
=========
Please provide the following information:
 librdkafka version 0.8.1
 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka v0.8.1 is almost 4 years old and is way past its support Windows.
Upgrade to the latest librdkafka version (v0.11.0) and see if you can reproduce the problem.
