### ISSUE TITLE
kafka produce fails - open connections

### ISSUE THREAD

**Issue by lathakris** [edenhill/librdkafka#1388]
Description
===========
When the kafka produce fails on a client, is any clean up required on the client program ? We see that the connections are left open on the server side and are not being cleaned up. Seems like when a produce fails, new connections are opened up and old ones also linger around. 
Please let me know if there is anything missing to be done on the client side.

I am using librdkafka - 0.9.5 on linux.

Thanks.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.9.5 ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [linux ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka will keep connected to all brokers in the cluster at all times, and then use the appropriate connection to produce messages.
In case a connection is closed librdkafka will reconnect.
Failed produce attempts are retried (if retriable error) until they fail, which you can monitor with the delivery report callback.
https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-broker-tcp-connections
