### ISSUE TITLE
A problem about Local:Queue full and how can I delete message from queue

### ISSUE THREAD

**Issue by q1f3** [edenhill/librdkafka#1393]
Hi,I have a problem about "Local:Queue full".
I set " rd_kafka_conf_set(conf,"queue.buffering.max.messages","10000",errstr,sizeof(errstr));".
And I do a test that printf message number, when message number is bigger than queue.buffering.max.messages,it will print  "Local:Queue full".
How can I delete message from queue.
9991
9992
9993
9994
9995
9996
9997
9998
9999
10000
10001
% Failed to produce to topic snort_packet: Local: Queue full
10001
% Failed to produce to topic snort_packet: Local: Queue full
10001
% Failed to produce to topic snort_packet: Local: Queue full
10001
% Failed to produce to topic snort_packet: Local: Queue full
How to reproduce

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):the latest
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by zhaowq32** [comment]
I think you can set "queue.buffering.max.messages" much bigger.

**Comment by q1f3** [comment]
@zhaowq32 Thanks for your reply! I have set biggest value for "queue.buffering.max.messages",and problem also can't be solved.

**Comment by zhaowq32** [comment]
Has the message been sent successfully?

**Comment by q1f3** [comment]
@zhaowq32 message can't be sent when "Local:Queue full" happened.

**Comment by zhaowq32** [comment]
I mean if the message can be sent successfully before the error occurs

**Comment by edenhill** [comment]
Can you provide some code?

**Comment by edenhill** [comment]
If you've registered a delivery report callback (dr_msg_cb) you must call rd_kafka_poll() continually to serve the reports.

**Comment by q1f3** [comment]
@edenhill Thanks for your reply.I have called rd_kafka_poll(),and it will be occur "Local: Queue full"  about 4 hours later.
 `if(rd_kafka_produce(rkt,RD_KAFKA_PARTITION_UA,RD_KAFKA_MSG_F_FREE,buf,len,NULL,0,NULL) == -1)
        {
            fprintf(stderr,"%% Failed to produce to topic %s: %s\n",rd_kafka_topic_name(rkt),rd_kafka_err2str(rd_kafka_last_error()));
            rd_kafka_poll(rk,1000);
        }
`

**Comment by q1f3** [comment]
@edenhill I have commented out the code.I don't know what will be happened,if I comment out the code.
`while (unlikely(rk->rk_curr_msgs.cnt + cnt >
                        rk->rk_curr_msgs.max_cnt ||
                        (unsigned long long)(rk->rk_curr_msgs.size + size) >
                        (unsigned long long)rk->rk_curr_msgs.max_size)) {
                if (!block) {
                        //mtx_unlock(&rk->rk_curr_msgs.lock);
                        //return RD_KAFKA_RESP_ERR__QUEUE_FULL;
                }
                cnd_wait(&rk->rk_curr_msgs.cnd, &rk->rk_curr_msgs.lock);
        }`

**Comment by zhaowq32** [comment]
I think you could add some code like below after rd_kafka_produce.
```
while(rd_kafka_outq_len(rk) > 0)
{
    rd_kafka_poll(rk, 1000);
}
```

**Comment by q1f3** [comment]
@zhaowq32 OK,thank you,I should have a try.And I want to know if the message can be deleted from queue after the message has been delivered to kafka server.

**Comment by zhaowq32** [comment]
I think the message would be deleted from queue automaticly after it delivered to kafka server.

**Comment by q1f3** [comment]
@zhaowq32 I add the code {while(rd_kafka_outq_len(rk) > 0) ...} that you suggested after rd_kafka_produce,it calls rd_kafka_msg_destroy to delete message.And I get the other error "free():  invalid pointer: 0x0000000000ed29".The error may be caused by rd_kafka_poll(rk, 1000).

**Comment by zhaowq32** [comment]
Did you call rd_kafka_msg_destroy after rd_kafka_produce?If your produce msgflags is 'RD_KAFKA_MSG_F_FREE',then you shouldn't call rd_kafka_msg_destroy.

**Comment by q1f3** [comment]
@zhaowq32 Thank you very much,everything is good.

**Comment by duoluowangzi** [comment]
I have encountered the same problem. I resend the msg when callback is fail, and after a few days the error will occur. I dont known  why msg stay in the queue for so many.

**Comment by zhaowq32** [comment]
@duoluowangzi Local queue will storage the message that not delivered to kafka server until the message timeout(message.timeout.ms).When the network has fluctuated or there are other errors, there will be a lot of messages stacked in the queue, resulting in the queue full.

**Comment by baiwfg2** [comment]
@edenhill If I haven't registered any callback, do I still need to call `poll` ?

**Comment by edenhill** [comment]
@baiwfg2 Nope, without callbacks there will be nothing enqueued to poll()
