### ISSUE TITLE
[Question] Any "ThreadPool" limitations? Stuck at 3 GBit/s

### ISSUE THREAD

**Issue by 0blu** [edenhill/librdkafka#1396]
Description
===========
I created a simple c++ program that creates a consumer and a topic, and then producing a lot of data.

When I run one instance of the program it's transferring about 3 GBit/s but if I run two instances its going to transfer data at the speed of roughly 6GBit/s.
So I tried to create multiple producers in the same Instance but I still just had about 3Gbit/s.

That make me wonder if there is a static ThreadPool with a max about of Threads?

I figured out that there is a "rd_kafka_broker_thread_main" which get called 6 times but i can't find a way to increase the number of threads.
Edit: Ok, "rd_kafka_broker_thread_main" will be called 1+n where n is the number of connections.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.5
 - [ ] Apache Kafka version: 0.11.0.0
 - [ ] librdkafka client configuration: "message.max.bytes: 536870912, request.required.acks: 1"
 - [ ] Operating system: CentOS 7.3
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The level of parallelism in librdkafka is per broker, one thread is created per broker (rather than topic or partition).

Use `top -H` or similar to see what threads are maxing out, it might not necessarily be the broker threads but your main thread. Also make sure your partitions are evenly spread out of your available brokers to promote parallelism.

**Comment by 0blu** [comment]
Ok, I managed to outsource the main thread into 4 smaller threads and doubled the kafka broker count.
Now I get about 10Gbit/s

**Comment by edenhill** [comment]
@0blu That's an impressive number :)

Can you share some information on your setup?
Number of brokers, hardware/instance types, network speed, number of clients?
(or are you planning a blog?! :) )

**Comment by 0blu** [comment]
So my goal is to send _a lot of big files_ from A to _N_ clients **reliable** and to verify if Kafka is the right technology to use for this task.

Therefor I got a software which is wring files into a ramdisk and my Kafka Producer is listing with an INotfiy on this ramdisk folder, so if a new files is being "IN_CLOSE_WRITE" I get notified.

When I get Notified I will write the filename into a queue and one of my worker threads will then receive this entry.

The worker is reading the file in small chunks(2Mib) and actually making a Kafka produce.
(along with some Metadata to find the file)
The last Metadata produce() also includes the filepath as msg_opaque which the  _dr_cb_ checks and finally delete the file from the ramdisk.

Since I only writing files into Kafka this is my current test setup:

```
                                +-------+
                                | Kafka1|
                                +-------+
                                   II
                                  10GE
                                   II
     +-----------+               +------+
     |  Server A |  === 40GE === |Switch|
     +-----------+               +------+
                                   II
                                  10GE
                                   II
                                +-------+
                                | Kafka2|
                                +-------+
``` 

The load is well balance each 10GE connections gets about 5Gbit/s of the 10Gbit/s load.
_Server A_ is running my producer program and _Kafka1_&_Kafka2_ are running 5 instances of Kafka( = 10 total instances).
Each Kafka instance has access to a ramdisk for the log and -Xmx16G dedicated ram guaranteed.
The default topic partition count is 20.

I think I have to further improve my program to reach 20Gbit/s in order to max out the network speed.
If i run multiple instances at the same time I get ~15Gbit/s so this should be my new goal for now.

@edenhill 
So to remention my question `[...]verify if Kafka is the right technology to use for this task`:
Maybe there is another piece of technology out there to handle my use case? (Which I might don't know yet)
Do you have any other Tip?

**Comment by edenhill** [comment]
This is not my area of expertise, but the typical recommendation for use-cases involving large files is to store the actual file content in another system (S3, HDFS, ..) and use Kafka for metadata signaling.

Are you memory mapping the files that you produce in chunks? If so, and by not setting the MSG_F_COPY flag, you should get zero-copy behaviour.

**Comment by 0blu** [comment]
Thanks, I will take a look into these technologies.

I am currently not using the zero-copy behavior( also have to take a look into this).

``` c++
std::ifstream file_stream;
file_stream.open(path);

while([...]) {
    file_stream.read(p_chunk_buffer, MAX_CHUNK_SIZE);
    if (read_len == 0)
        break;
    producer->produce(topic_name,
                      RdKafka::Topic::PARTITION_UA,
                      RdKafka::Producer::RK_MSG_COPY,
                      p_chunk_buffer,
                      read_len,
                      [...]);
}
file_stream.close();

```

**Comment by edenhill** [comment]
ooh, you should see a performance boost when switching to zero copy then.
