### ISSUE TITLE
Which Boost library packages needed for avro c++

### ISSUE THREAD

**Issue by gmdun** [edenhill/librdkafka#1398]
Description
===========
I have installed all the packages of boost 1.64 in linux. but I want to install only those packages which needed for avro cpp. here are the boost libraries  list.
./b2 --show-libraries
  - atomic
  - chrono
  - container
  - context
  - coroutine
  - coroutine2
  - date_time
  - exception
  - fiber
  - filesystem
  - graph
  - graph_parallel
  - iostreams
  - locale
  - log
  - math
  - metaparse
  - mpi
  - program_options
  - python
  - random
  - regex
  - serialization
  - signals
  - system
  - test
  - thread
  - timer
  - type_erasure
  - wave

where as avro says it needs following packages.(avro package is avro-cpp-1.8.2) libboost-dev libboost-filesystem-dev libboost-system-dev libboost-program-options-dev.

I not sure here what libraries  libboost-dev package contain in boost? Which library from boost I have to install for this package.
How to reproduce
================
i' m doing manual installation of boost library and avro. 
Since I don’t have root permission 
so I’m following below instructions to install boost and avro.
 ./bootstrap.sh --prefix=/home/work/boost ./b2 install --prefix=/home/work/boost --without-python 
 Currently I’m not able to figure out which libraries is required for avro cpp so I’m installing all boost library. 
 Avro installation BOOST_ROOT=/home/work/boost; 
 export BOOST_ROOT; export DESTDIR==/home/work/avro; 
 ./build.sh install 
 can some please answer since boost contains so many shared libraries i don't want to keep unnecessary libraries.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I think you filed this issue on the wrong project, librdkafka does not make use of neither avro nor boost.
