### ISSUE TITLE
Cannot consume when using key in produce()

### ISSUE THREAD

**Issue by markjans** [edenhill/librdkafka#1400]
Description
===========
I have an application in C++ that consumes events from the topic "unsorted", _adds a key_ and sends the _same_ event back to Kafka in another topic called "sorted".
The problem is that my Java consumers cannot consume events in "sorted". Some consumers even crash.
If the key is replaced with nullptr, then they can consume. So, the problem seems to be related to the key.

I also have tried with an Java application doing the same thing as the C++ application, and then it works fine.

Code for producing events:
```
void produceMessage(uint32_t key, RdKafka::Message& message)
{
  std::string keyStr = std::to_string(key);

  RdKafka::ErrorCode resp = producer->produce(targetTopic,
                                              RdKafka::Topic::PARTITION_UA,   // Unassigned partition
                                              RdKafka::Producer::RK_MSG_COPY, // Copy payload
                                              message.payload(),              // Serialized bytes
                                              message.len(),                  // Number of bytes
//                                              nullptr,
                                              &keyStr,
//                                              keyStr.c_str(), keyStr.size(),
                                              nullptr);

  if (resp != RdKafka::ERR_NO_ERROR)
  {
    TRACE_INFO(STR("Produce failed: %s", RdKafka::err2str(resp).c_str()));
  }
  else
  {
    TRACE_INFO(STR("Produced message (%d bytes)", message.len()));
  }

  producer->poll(0);
}
```

The delivery report callback indicates no error:
INFO:DeliveryReportCallback::dr_cb: Message delivery for (24 bytes): Success
INFO:DeliveryReportCallback::dr_cb: Key: 50

One of the Java consumers that always crash when key in the C++ application is used:
```
public class SortVerify extends ShutdownableThread {
  private final KafkaConsumer<Integer, ObsEvent> consumer;
  private final String topic;
  private final int pollPeriod;
  private final Map<Integer, HashMap<Integer,Integer>> partions;

  public SortVerify(String topic, String bootstrapServers) {
    super("SortVerify", false);
    Properties propsConsumer = new Properties();
    propsConsumer.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
    propsConsumer.put(ConsumerConfig.GROUP_ID_CONFIG, "SortVerify");
    propsConsumer.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "true");
    propsConsumer.put(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, "1000");
    propsConsumer.put(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, "30000");
    propsConsumer.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest"); // earliest|latest|none
    consumer = new KafkaConsumer<>(propsConsumer, new IntegerDeserializer(), new EventDeserializer());

    this.topic = topic;
    pollPeriod = 1000;

    partions = new HashMap<>();
  }

  @Override
  public void doWork() {
    consumer.subscribe(Collections.singletonList(topic));
    ConsumerRecords<Integer, ObsEvent> records = consumer.poll(pollPeriod);

    System.out.println("partitions: " + records.partitions().size());

    for (ConsumerRecord<Integer, ObsEvent> record : records) {
      System.out.println("record key: " + record.key());
      //  doing something...
      }
  }

  @Override
  public String name() {
    return null;
  }

  @Override
  public boolean isInterruptible() {
    return false;
  }
}
```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): librdkafka-0.11.0
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [x] Operating system: Red Hat server 6.4
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I'm guessing the problem is that you are producing the key as a string (not null-terminated string of characters, e.g, "5" "0"), but the Java producer expects an integer key (which is assumed to be at least 4 bytes long).

**Comment by markjans** [comment]
Doesn't keyStr.c_str() contain a null-terminator?
I have tried:
```
std::string keyStr = std::to_string(key);
RdKafka::ErrorCode resp = producer->produce(
                                               ...
                                              keyStr.c_str(), keyStr.size(),
                                              nullptr);
```
with same result.

**Comment by edenhill** [comment]
size() does not include the null-terminator.
But that's besides the point, the Java code expects an integer, not a string.
Convert the key before producing to whatever representation the IntegerDeserializer expects (I'm guessing 32-bit big endian, but you'll need to check).

**Comment by markjans** [comment]
Yes, if I send the key as integer instead of string, then it works.
Thanks for the help!

**Comment by edenhill** [comment]
👍
