### ISSUE TITLE
Performance regression when upgrading from librdkafka 0.9.5 -> 0.11.0

### ISSUE THREAD

**Issue by patricklauer** [edenhill/librdkafka#1401]
Description
===========
We are using a custom protocol converter, which can be found at https://github.com/adjust/schaufel

With librdkafka 0.9.5 we can write fast (4 threads deliver ~400k messages/sec, schaufel at 400% CPU, kafka pretty much idle) into both kafka-0.10 and kafka-0.11 brokers.

After upgrade to 0.11.0 writing is slower (~250k messages/sec) and CPU usage is massively higher for schaufel (>800%) and kafka (>400%).

How to reproduce
================
Install schaufel, use it with dummy input and kafka output:
`./schaufel -c 4 -p 4 -i dummy -o kafka -B kafka-server -T banana -l logfile`
This writes diagnostic messages to `logfile`, and writes dummy messages to the kafka broker on `kafka-server`, topic `banana`. By default lz4 compression is used for kafka.

sample log output looks like this:
```
Wed Aug 30 13:00:53 2017 producer are up
Wed Aug 30 13:00:57 2017 added / s: 0 delivered / s: 0
Wed Aug 30 13:01:02 2017 added / s: 370020 delivered / s: 350020
Wed Aug 30 13:01:07 2017 added / s: 409952 delivered / s: 409956
Wed Aug 30 13:01:12 2017 added / s: 406541 delivered / s: 406539
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.0
 - [x] Apache Kafka version: 0.11.0
 - [x] librdkafka client configuration: See `schaufel` source code
 - [x] Operating system: Gentoo Linux / amd64 / glibc
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you try setting `linger.ms` to 100 or 1000?

**Comment by patricklauer** [comment]
Setting `linger.ms` to 1000 reduces kafka broker CPU usage by about 20%, schaufel CPU usage by a similar amount, but is still massively higher than with librdkafka-0.9.5.

**Comment by edenhill** [comment]
Can you provide the full producer config?

**Comment by champtar** [comment]
Hi @patricklauer @edenhill 
Updating to 0.11 I also had a big performance drop, in my case setting ```queue.buffering.max.ms``` to 100 ms instead of the new 0 default fixed it

**Comment by edenhill** [comment]
*note: `linger.ms` is an alias for `queue.buffering.max.ms`*

**Comment by patricklauer** [comment]
See https://github.com/adjust/schaufel/blob/master/src/kafka.c#L122

The config is all 'defaults', except for the following config values we add:
```
enable.auto.commit = true
auto.commit.interval.ms = 10
auto.offset.reset = 10
```
On the kafka side, it's the same config we used with 0.10, with `log.message.format.version=0.11.0` and `inter.broker.protocol.version=0.11.0`

**Comment by edenhill** [comment]
Oh, I was under the impression this was using the producer.
If you run a consumer feeding into a producer, please try to separate the two to see which one is slower (or both)

**Comment by patricklauer** [comment]
Yes, this is the producer showing elevated CPU usage - but the consumer also seems to have similar performance issues. Also, the kafka broker is showing elevated CPU usage, but only with librdkafka-0.11.

So either the new log format in 0.11 is problematic, or some default in librdkafka changed in a way that increases overhead a lot. I haven't noticed anything in the release notes of both kafka and librdkafka that explains this increase, and I'm out of ideas which configuration options to change to get it back to something near the previous resource usage.

**Comment by edenhill** [comment]
the 0.11.0 message format is far more effective for large batches, but has bigger overhead for small batches.
Increasing `linger.ms` (producer property, not consumer!) increases the chances of larger, more effective, batches.

Can you reproduce this with `linger.ms=1000` and `debug=msg,protocol` and provide a 100 line log excerpt containing ProduceRequests and "Produce MessageSet with .."?

**Comment by patricklauer** [comment]
Oh, I see I patched the config in the wrong place. 
Trying with `linger.ms` for the producer set to a reasonably large value (e.g. >100) pretty much returns us to the previous behaviour with low CPU usage and high throughput.

So this fixes our problem, maybe you want to explicitly add a warning to the config to prevent repeat bug reports like this one :)
