### ISSUE TITLE
Question: connection state

### ISSUE THREAD

**Issue by trapexit** [edenhill/librdkafka#1403]
Is there a way to determine (in a synchronous fashion) the current state of a session?

The problem I'm facing is that some calls (rd_kafka_metadata, rd_kafka_query_watermark_offsets, etc.) take timeouts but don't seem to short circuit on certain errors. If I set the broker to a hostname which exists but port which is not bound so the OS returns "connections refused" the call will still wait the full timeout. Or if the hostname is bogus. Or AUTHN fails (it seems to just keep trying over and over till the timeout).

Is there any internal state that I can query so as to avoid these timeouts?

**Comment by edenhill** [comment]
When connecting to a Kafka broker v0.10 or later you can use `rd_kafka_clusterid()` which will return non-NULL when it has managed to connect to at least one broker.
You can use this with a small timeout allowing for the initial connection setup.

**Comment by trapexit** [comment]
Any possibility of adding something to help with these situations? A "fail fast" config option or a call to see the internal state?

**Comment by edenhill** [comment]
This is tracked in feature request https://github.com/edenhill/librdkafka/issues/418
