### ISSUE TITLE
poll cause core dump

### ISSUE THREAD

**Issue by ChampionL** [edenhill/librdkafka#1405]
Description
===========

i create a thread , the start_routine code show below
```
void* deal_kafka_cb_thread(void * arg){

 RdKafka::Producer * producer = (RdKafka::Producer *)arg;

 while(true){

   while (producer->outq_len() > 0) {

      std::cerr << "Waiting for " << producer->outq_len() << std::endl;

          producer->poll(-1);

         }

    }
 }

```
it cause a core dump,it's stack is 
Coredump at:

`
[dr_msg_cb_trampoline] deps/kafka_src/src-cpp/ProducerImpl.cpp:47 [0x1ef7ae]
Backtrace:
   <== [dr_msg_cb_trampoline] deps/kafka_src/src-cpp/ProducerImpl.cpp:47 [0x1ef7ae]

    <== [rd_kafka_poll_cb]  deps/kafka_src/src/rdkafka.c:2592 [0x1f9498]

     <== [rd_kafka_q_serve]  deps/kafka_src/src/rdkafka_queue.c:467 [0x21af26]

      <== [produceMsgToKafka(std::string, std::string)]
` what's the problem?

**Comment by edenhill** [comment]
Try running your program with valgrind, it assists in finding these sort of issues.
My guess would be that your DeliveryReport instance is allocated on the stack rather than the heap and then goes out of scope.

**Comment by qcloudsms** [comment]
thanks,the DeliveryReportCb Instalce is allocated in stack,i alloacated it in heap and it's ok now
