### ISSUE TITLE
Fix  instantiate more topics error

### ISSUE THREAD

**Issue by cuiluguang** [edenhill/librdkafka#1408]
Description
===========
rdkafka_topic.c:258  Fix  instantiate  more topics error  in the function rd_kafka_topic_new0()
SOURCE:
	if (!conf) {
                if (rk->rk_conf.topic_conf)
                        conf = rd_kafka_topic_conf_dup(rk->rk_conf.topic_conf);
                else
                        conf = rd_kafka_topic_conf_new();
        }
	rkt->rkt_conf = *conf;
	rd_free(conf);
FIX method:
	if (!conf) {
                if (rk->rk_conf.topic_conf)
                        conf = rd_kafka_topic_conf_dup(rk->rk_conf.topic_conf);
                else
                        conf = rd_kafka_topic_conf_new();
				//fix bug-tg
				rkt->rkt_conf = *conf;
				rd_free(conf);
        }
	rkt->rkt_conf = *conf;
	//rd_free(conf);

How to reproduce
================
rdkafka_zookeeper_example.c
producer mode   instantiate more topics 
 rkt = rd_kafka_topic_new(rk, "test1", topic_conf);
 rkt1 = rd_kafka_topic_new(rk, "test2", topic_conf);

Checklist
=========
Please provide the following information:

 - [ *] librdkafka version (release number or git tag):master
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [* ] Critical issue

**Comment by edenhill** [comment]
The topic_conf object may not be reused, as stated in the documentation:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1733

The application should call topic_conf_dup() if it needs to reuse an existing config object for multiple new() calls.
