### ISSUE TITLE
Build librdkafka for 32 bit environment 

### ISSUE THREAD

**Issue by Tushar1983** [edenhill/librdkafka#1413]
Hi Edenhill,

I am trying to build the librdkafka library for c/c++ for 32 bit environment on a 64 bit linux.
It would be very helpful if you could guide me to appropriate wiki or steps.

I have checked out the code from Master.

I am trying to develop a producer to publish to one of our Kafka Cluster where,
All communication is over SSL.
All clients must use SASL/SCRAM to authenticate with Kafa

For this I am following "https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka".

I have the keystore with its password.
Now, I have exported the caroot.pem certificate from client keystore.

It would be very helpful if you could guide me on following points.
1. How to build the library for 32 bit environment/application.
2. What all config properties I need to set. The Kafka environment is configured and is being used by Java based producers. Following are the configs provided to us.
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-256
ssl.truststore.location=/path_to/kafka.client.truststore.jks
ssl.truststore.password=Welcome1

Code snippet:
```
void KafkaProducer::request() {
    std::string response = "success";
    std::string topic_str = "batchindexer_topic";
    std::string errstr;
    ExampleDeliveryReportCb ex_dr_cb;
    Json::FastWriter writer;

    try
    {
    	RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);

    	if (conf->set("metadata.broker.list", "bzn00acf.****.com:9092", errstr)!= RdKafka::Conf::CONF_OK) {
    	      printf("metadata.broker.list : %s\n", errstr.c_str());
    	}

    	if (conf->set("security.protocol", "SASL_SSL", errstr)!= RdKafka::Conf::CONF_OK) {
    		printf("security.protocol : %s\n", errstr.c_str());
    	}

    	if (conf->set("sasl.mechanisms", "SCRAM-SHA-256", errstr)!= RdKafka::Conf::CONF_OK) {
    		printf("sasl.mechanism : %s\n", errstr.c_str());
    	}

    	if (conf->set("ssl.certificate.location", "/home/tussinha/RNowServers/BatchIndexer/KafkaKeystore/caroot.pem", errstr)!= RdKafka::Conf::CONF_OK) {
    		printf("ssl.certificate.location : %s\n", errstr.c_str());
    	}

    	if (conf->set("sasl.username", "admin", errstr)!= RdKafka::Conf::CONF_OK) {
    		printf("sasl.username : %s\n", errstr.c_str());
    	}

    	if (conf->set("sasl.password", "Welcome1", errstr)!= RdKafka::Conf::CONF_OK) {
    		printf("sasl.password : %s\n", errstr.c_str());
    	}

    	if (conf->set("queue.buffering.max.ms", "0", errstr)!= RdKafka::Conf::CONF_OK) {
    		printf("queue.buffering.max.ms : %s\n", errstr.c_str());
    	}

    	if (conf->set("dr_cb", &ex_dr_cb, errstr)!= RdKafka::Conf::CONF_OK) {
    		printf("dr_cb : %s\n", errstr.c_str());
    	}

    	RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);
    	RdKafka::Topic *topic = RdKafka::Topic::create(producer, topic_str, NULL, errstr);

    	Json::Value jsonData(Json::objectValue);
    	jsonData["id"] = "1";
    	jsonData["firstName"] = "Test";
    	jsonData["lastName"] = "Contact1";
    	jsonData["postalCode"] = "123456";

        std::string data = writer.write(jsonData);

        producer->produce(topic, RdKafka::Topic::PARTITION_UA, RdKafka::Producer::RK_MSG_COPY, const_cast<char *>(data.c_str()), data.size(), NULL, NULL);
        producer->poll(0);
    }
    catch (std::exception& e)
    {
    	printf("Exception :: %s", e.what());
        throw e;
    }
    Json::Value responseData(Json::objectValue);
    responseData["message"] = response;
    std::string resp = writer.write(responseData);
    printf("Response:: %s",resp.c_str());
}
```

**Comment by edenhill** [comment]
1. librdkafka should build just fine for 32-bit systems, just download the source, type `./configure --prefix=/usr && make && sudo make install`. Make sure the development dependencies, such as the OpenSSL development packages (e.g., libssl-dev) are installed prior to running configure, and check the configure output that it includes libssl.

2. You seem to be missing the client certificate and key, follow the steps outlined in https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

**Comment by Tushar1983** [comment]
I think, I need to elaborate a bit more..
The kafka environment setup has a two way SSL handshake configuration.
I have three *.jks files available, server.trustore.jks, client.trustore.jks and server.keystore.jks.
Now, I have extracted the .perm files from all three of them.

How to configure my producer configs?

**Comment by edenhill** [comment]
There's plenty of existing documentation on this subject.

Please see
http://docs.confluent.io/current/kafka/ssl.html#
https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka
https://www.openssl.org/docs/

along with google searches for any concerns that pop up you should be able to translate your Java configuration to a pure OpenSSL (librdkafka) config.

**Comment by Tushar1983** [comment]
I might have mentioned in incorrectly.
What I am trying to achieve here is build a 32bit librdkafka library on a 64 bit Linux machine.
The target application where I will be using the library is a 32 bit app. Whereas I only have a 64 bit linux environment.

**Comment by edenhill** [comment]
Try with `./configure --mbits=32` followed by the other make steps.
If that doesn't work, see this guide for how to employ a cross-compilation toolchain:
https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Hosts-and-Cross_002dCompilation.html

**Comment by bhattmayur26** [comment]
Hi Edenhill,

I am trying to build 32 bit version of librdkafka on 64 bit CentOS 7. I have installed all dependencies (32-Bit). When is try to build, I am getting below build errors. Can you please help

crc32c.c: In function ‘crc32c’:
crc32c.c:283:13: error: ‘asm’ operand has impossible constraints
             __asm__("crc32q\t" "(%3), %0\n\t"
             ^
crc32c.c:303:13: error: ‘asm’ operand has impossible constraints
             __asm__("crc32q\t" "(%3), %0\n\t"
             ^
crc32c.c: In function ‘crc32c_global_init’:
crc32c.c:349:9: error: PIC register clobbered by ‘%ebx’ in ‘asm’
         __asm__("cpuid" \
         ^
crc32c.c:380:9: note: in expansion of macro ‘SSE42’
         SSE42(sse42);
         ^
make[1]: *** [crc32c.o] Error 1

**Comment by timothy** [comment]
Hi @edenhill,
I am trying to compile a 32-bit version on a 64-bit ubuntu box and getting the below errors. 

I am using the below to install the lib:
```
./configure --mbits=32
make
sudo make install
```

Below is the error I receive: 
```
crc32c.c:362:1: warning: unsupported size for integer register
 }
 ^
crc32c.c:362:1: warning: unsupported size for integer register
crc32c.c:362:1: warning: unsupported size for integer register
crc32c.c:362:1: warning: unsupported size for integer register
crc32c.c:362:1: warning: unsupported size for integer register
crc32c.c:362:1: warning: unsupported size for integer register
crc32c.c:362:1: warning: unsupported size for integer register
crc32c.c:362:1: warning: unsupported size for integer register
crc32c.c:362:1: warning: unsupported size for integer register
crc32c.c: Assembler messages:
crc32c.c:277: Error: unsupported instruction `crc32'
crc32c.c:278: Error: unsupported instruction `crc32'
crc32c.c:279: Error: unsupported instruction `crc32'
crc32c.c:297: Error: unsupported instruction `crc32'
crc32c.c:298: Error: unsupported instruction `crc32'
crc32c.c:299: Error: unsupported instruction `crc32'
crc32c.c:314: Error: unsupported instruction `crc32'
../mklove/Makefile.base:84: recipe for target 'crc32c.o' failed
make[1]: *** [crc32c.o] Error 1
```

**Comment by edenhill** [comment]
@timothy Can you provide the output from ./configure ?  My guess is that it uses the hardware-assisted crc32 instructions, which you can disable by doing something like:
` true || mkl_compile_check ....` here: https://github.com/edenhill/librdkafka/blob/master/configure.self#L151
And then run `./configure --clean` foillowed by your original configure command.
