### ISSUE TITLE
Consumer receives ERR__PARTITION_EOF even though there are mesaages

### ISSUE THREAD

**Issue by hrjaco** [edenhill/librdkafka#1414]
Description
===========

I am using C++ client. I have a kafka consumer, which periodically I seek back to a previous offset(by using offsetsForTimes() + seek()). I have 2 topics. Every 5 mins, I will do the above seek for each topic sequentially. 

The issue I saw is sometimes after finishing these 2 seeks(), consume() will return  ERR__PARTITION_EOF even though there are enough messages.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): v0.11.0
 - [ ] Apache Kafka version: 0.10.1.1
 - [ ] librdkafka client configuration:
conf->set("metadata.broker.list", broker_list_, err);
conf->set("api.version.request", "true", err);
conf->set("enable.auto.offset.store", "false", err);
conf->set("group.id", , err);
 - [ ] Operating system: ubuntu 12.04
 - [ ] Using the legacy Consumer No
 - [ ] Using the high-level KafkaConsumer Yes
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please reproduce with `debug=fetch,topic,protocol` and mark the log where this occurs.

**Comment by hrjaco** [comment]
Will do. One QQ, when I consume from 2 topics(each with 1 partition), will I get `ERR__PARTITION_EOF` if either topic reaches the end, or will I get EOF when both reaches end?

**Comment by edenhill** [comment]
PARTITION_EOF is emitted per partition each time the fetcher reaches the end of the partition.

So if you are consuming 4 partitions and eventually catch up to the end, you will get 4 PARTITION_EOF (see the topic and partition members of message_t to see which partition reached EOF).
When new messages are produced and the consumer consumes them and then reaches the new end offset it will once again report EOF.
If you are not interested in EOF you can disable them through a client configuration property, see CONFIGURATION.md

**Comment by kostov** [comment]
```
while( ! this->isCanceled() ) {
	uptr<RdKafka::Message const> const kafkaMessage( kafkaConsumer->consume( 1000 ) );
	switch( kafkaMessage->err() )
	{
		case RdKafka::ERR_NO_ERROR:
		< process the message >
		break;
			
		case RdKafka::ERR__PARTITION_EOF:
		// QUESTION 1: if it happens, is it will happen again and again infinitely?
		// QUESTION 2: if yes, weed we doing some speep here?
		break;
	
		case RdKafka::ERR__TIMED_OUT:
		break;
	
		default:
		< error handling >
		this->cancel();
	}
}
```

**Comment by edenhill** [comment]
PARTITION_EOF will be raised each time the fetcher hits the last offset in the partition, but only once per such offset.

You don't need to sleep as long as you have a timeout on the consume() call.

The fetcher continues to operate in the background and will fetch new messages automatically when they are produced.

**Comment by kostov** [comment]
Thank you :)
