### ISSUE TITLE
Inconsistent enable.auto.commit for Java and C++ clients

### ISSUE THREAD

**Issue by coberty** [edenhill/librdkafka#1415]
Hello
I have noticed some inconsistency between those two clients.

librdkafka: 0.9.5.

Both clients settings:
   enable.auto.commit=true
   auto.commit.interval.ms=10

For Java client offset retention starts counting off as soon as the client is stopped.
For C++ client it starts just after last commit.
So for the Java client offsets are retained while the client is running. For the C++ client it looks like they are retained while it is running but after restart of the client it appears that they have been lost.

How to reproduce
Set the following props for the broker:
   offsets.retention.check.interval.ms=10000 # =10s
   offsets.retention.minutes=1
run the clients and check the broker logs for "Removed X expired offsets in Y milliseconds."

cob

**Comment by edenhill** [comment]
It might be that the Java client is re-committing the same offset on each commit interval, which the librdkafka client does not. See #1372

**Comment by coberty** [comment]
I guess this is the case.
Thanks for the explanation.

**Comment by edenhill** [comment]
If you feel this behaviour is wrong, please provide some insight/use-case in issue #1372.
Thanks

**Comment by coberty** [comment]
I am not sure if it is wrong. I would rather say - unexpected.

We have such case:
Our C++ client had not received any messages for 2 days. And after it was restarted it started to read everything from the very beginning what is something that we want to avoid.

It wouldn't have happened with Java client since it retains offsets while is running with auto commit.

Thanks,
cob
