### ISSUE TITLE
Add isolation.level=read_committed support

### ISSUE THREAD

**Issue by kiranrj** [edenhill/librdkafka#1418]
Any milestone planned to support Kafka transactional APIs and commit-aware consumers in RdKafka?

Thanks in advance !

**Comment by edenhill** [comment]
Tracked in #1308. I dont have a time frame for you though.
Exposing read_uncommitted=false as a property would be trivial to implement in the meantime, if it would help.

**Comment by kiranrj** [comment]
Our primary use case was to have a transaction aware consumer. Exposing this as a consumer configuration would thus really help.

Thanks a lot !
