### ISSUE TITLE
whether librdkafka api supports kafka-streaming or ksql features?

### ISSUE THREAD

**Issue by duanyr** [edenhill/librdkafka#1419]
hello:

Recently, kafka community talks more about kafka-streaming and ksql, so whether librdkafka api supports these features?(i have not found related api on my using version)

And if not support at the moment, when thess features will be supported estimately?

Looking forward to your answer!
@edenhill

**Comment by edenhill** [comment]
The Kafka Streams API is not implemented by librdkafka, and while it is on the backlog there is no set time for when it will be implemented.

KSQL will not be implemented in librdkafka, the existing Java implementation is sufficient.

librdkafka-based clients are interoperable with both Kafka Streams and KSQL though.

**Comment by duanyr** [comment]
OK,thank you very much for your answer.

**Comment by edenhill** [comment]
Dup #1248
