### ISSUE TITLE
about key store file

### ISSUE THREAD

**Issue by a7618317a** [edenhill/librdkafka#1420]
Description
===========
When I use the Key store file,add property "ssl.keystore.location、ssl.keystore.password、ssl.key.password、ssl.truststore.location、ssl.truststore.password" in the config, It throw error:"can not find the property ssl.keystore.location....." ,how can i use librdkafka with key store file,thank you !

How to reproduce
================

add property "ssl.keystore.location、ssl.keystore.password、ssl.key.password、ssl.truststore.location、ssl.truststore.password" in the config

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by a7618317a** [comment]
thank you

**Comment by edenhill** [comment]
Those are Java client configuration properties which make use of Java's JAAS framework and Java-specific trust/keystores.
librdkafka (and its sibling clients) makes use of OpenSSL, see this guide how to set it up:
https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka
