### ISSUE TITLE
Howto disable version fallback?

### ISSUE THREAD

**Issue by champtar** [edenhill/librdkafka#1422]
Description
===========
Some feature just like ```security.protocol = sasl_plaintext with sasl.mechanisms = PLAIN``` just don't work when librdkafka fallback after a timedout ApiVersionRequest
Is setting ```api.version.fallback.ms=0``` enough to disable version fallback?

Checklist
=========
Please provide the following information:

 - [X] librdkafka version (release number or git tag): a212ea2
 - [X] Apache Kafka version: 0.11.0.1
 - [X] librdkafka client configuration:
security.protocol = sasl_plaintext
sasl.mechanisms = PLAIN
api.version.request = true
api.version.fallback.ms = 0

 - [X] Operating system:
CentOS 7.4

 - [ ] Using the legacy Consumer
 - [X] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Yes, or simply setting broker.version.fallback=  to your actual broker version (or any version >= "0.10.0" since that will enable ApiVersionRequests)

**Comment by champtar** [comment]
Hi @edenhill 
I didn't try setting ```broker.version.fallback``` to my broker version because documentation says ```Valid values are: 0.9.0, 0.8.2, 0.8.1, 0.8.0``` which is a bit misleading :)
