### ISSUE TITLE
rd_kafka_ApiKey2str() fails for key value 6

### ISSUE THREAD

**Issue by rthalley** [edenhill/librdkafka#1423]
Description
===========

When configured with "debug" set to "all", we see crashes in rd_kafka_handle_ApiVersion() when it calls
		rd_rkb_dbg(rkb, FEATURE, "APIVERSION",
			   "  ApiKey %s (%hd) Versions %hd..%hd",
			   rd_kafka_ApiKey2str(api->ApiKey),
			   api->ApiKey, api->MinVer, api->MaxVer);
 
The problem is that api->ApiKey is 6 but this ApiKey (UpdateMetadata) is not in the table in rdkafka_proto.h.  The way this table is constructed is kind of dangerous, as any key that is less than the max but happens not to be in the table will cause a crash instead of running the "I don't know this ApiKey code".

These issues are still present on the master branch as far as I can tell from looking at the code.

How to reproduce
================

Connect to 0.10.0 broker with rdkafka configured with debug = all.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.11.0
 - [ ] Apache Kafka version: 0.10.0
 - [ ] librdkafka client configuration: debug = all
 - [ ] Operating system: N/A (happened to be solaris in our case)
 - [ ] Using the legacy Consumer  no
 - [ ] Using the high-level KafkaConsumer   no
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka  cores if you attempt it :)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue  no

**Comment by edenhill** [comment]
If I remember correctly from about 10 years ago with my last SunOS stint, I believe the SunOS libc printf doesn't support NULL values for %s.

I'll make a fix.
