### ISSUE TITLE
Add Java-compatible murmur2 partitioner

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#1424]
Also make partitioners configurable by standard text property, e.g.:
`rd_kafka_conf_set(conf, "partitioner", "murmur2", ..);`

And to make that work with custom/pluggable partitioners, also add:
`rd_kafka_conf_add_partitioner(conf, "partitioner_name", partitioner_cb);`

**Comment by barrotsteindev** [comment]
I've started working on this

**Comment by barrotsteindev** [comment]
I'm having trouble getting this to compile on Windows. Can provide a link to my fork if necessary. It'd be lovely if someone with more experience using Windows could help
