### ISSUE TITLE
Nuget package - librdkafka does not support debug mode

### ISSUE THREAD

**Issue by dreamskeee** [edenhill/librdkafka#1425]
I'm using librdkafka with Nuget.  (Visual studio 2017)
My application works well in release mode, but crashes in debug mode.
I think this happens because there is no debug library in the Nuget package. (There is not really)
It would be nice to deploy it with a debug library.

Thanks a lot.

**Comment by edenhill** [comment]
Not enough demand.

**Comment by nfp0** [comment]
> Not enough demand.

@edenhill I understand there might not be demand for a debug library, but is it normal for librdkafka to crash in debug mode though?
