### ISSUE TITLE
api.version.request=false

### ISSUE THREAD

**Issue by dinmil** [edenhill/librdkafka#1427]
I'm having problem with Windows consumer client using version 0.11.0 and connecting to Linux Kafka server 0.11.0.
When server is on one network subnet mask (e.g. IP=10.16.14.1) and client is on the same network mask (e.g. IP=10.16.14.22) then consumer application consume messages very fast, but when I move client to some other network address not in (e.g. IP=172.16.20.25) then application fetch messaged about 10 times slowly.
Note, network upload and download is correct and it should takes messages quickly. Messages, are big (average is about 5 MB).

Now, I played with consumer settings trying to get best performance, and nothing helped. At the end I put api.version.request=false and suddenly everything works smoothly.

Can, somebody explain whats happening.
I tried also
api.version.request=true and 
broker.version.fallback=0.9.0.0 and 
it was OK, but server is 0.11.0

Note if you set api.version.request=false
broker.version.fallback=0.9.0
it is not OK.

The other question is why CONNECT time is so long (about 10 seconds). It is because negotiation about broker version is in progress, or what...?

**Comment by edenhill** [comment]
You are probably encountering #1384 which is fixed on master.

**Comment by edenhill** [comment]
The connect stall of 10s should only be seen with api.version.request=true (default) and broker versions 0.9.x, due to a broker bug. You should not see it with any other broker version.

More info:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="local-packages" value="../foo/bin/Debug" />
  </packageSources>
</configuration>
