### ISSUE TITLE
How I Can Install librdkafka on Windows?

### ISSUE THREAD

**Issue by dutraleonardo** [edenhill/librdkafka#1428]
Description
===========
Hi, I'm using windows 10 64bits and I need to install librdkafka, but I don't know how to do that? lol

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Reference the librdkafka.redist package from NuGet

**Comment by miguel-angel-monjas** [comment]
Dear friends, I'm trying to install the confluent-kafka Python module in Windows (Windows 7 in fact) and, unfortunately, I'm not able to find any usable documentation to do it. The information provided in the [NuGet site](https://www.nuget.org/packages/librdkafka.redist/) is far from being informative when you don't have any experience in Visual Studio (I just want to publish/consume from a Python script in Kafka). Are you planning to offer any guidance on how to install the confluent-kafka Python package in Windows? Thanks

**Comment by edenhill** [comment]
We don't currently support confluent-kafka-python on Windows, so you would need to sort this out yourself and with the help of the community.

There is some information in this issue on what needs to be done, but it is not straight forward:
https://github.com/confluentinc/confluent-kafka-python/issues/132

**Comment by miguel-angel-monjas** [comment]
OK, then. Thank you for sharing the information...

**Comment by edenhill** [comment]
@anvithap123 We now have experimental windows wheels on PyPi, should be as simple as: `pip install confluent_kafka`.

If that doesn't work, please provide output from `pip`.

**Comment by AndrewMarchuk** [comment]
Hi, I have some problem with librdkafka. I have installed it with nuget, but when I had tried to build my project, I got an errors:

Error	LNK2019	unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::err2str(enum RdKafka::ErrorCode)" (__imp_?err2str@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ErrorCode@1@@Z) referenced in function "int __cdecl producer_2(void)" (?producer_2@@YAHXZ)	TestLibrdkafkaProducerC++	D:\Projects\TestLibrdkafkaProducerC++\TestLibrdkafkaProducerC++\TestLibrdkafkaProducerC++.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Conf * __cdecl RdKafka::Conf::create(enum RdKafka::Conf::ConfType)" (__imp_?create@Conf@RdKafka@@SAPAV12@W4ConfType@12@@Z) referenced in function "int __cdecl producer_2(void)" (?producer_2@@YAHXZ)	TestLibrdkafkaProducerC++	D:\Projects\TestLibrdkafkaProducerC++\TestLibrdkafkaProducerC++\TestLibrdkafkaProducerC++.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Producer * __cdecl RdKafka::Producer::create(class RdKafka::Conf *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (__imp_?create@Producer@RdKafka@@SAPAV12@PAVConf@2@AAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "int __cdecl producer_2(void)" (?producer_2@@YAHXZ)	TestLibrdkafkaProducerC++	D:\Projects\TestLibrdkafkaProducerC++\TestLibrdkafkaProducerC++\TestLibrdkafkaProducerC++.obj	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: static int const RdKafka::Topic::PARTITION_UA" (__imp_?PARTITION_UA@Topic@RdKafka@@2HB)	TestLibrdkafkaProducerC++	D:\Projects\TestLibrdkafkaProducerC++\TestLibrdkafkaProducerC++\TestLibrdkafkaProducerC++.obj	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: static __int64 const RdKafka::Topic::OFFSET_BEGINNING" (__imp_?OFFSET_BEGINNING@Topic@RdKafka@@2_JB)	TestLibrdkafkaProducerC++	D:\Projects\TestLibrdkafkaProducerC++\TestLibrdkafkaProducerC++\TestLibrdkafkaProducerC++.obj	1	
Error	LNK1120	5 unresolved externals	TestLibrdkafkaProducerC++	D:\Projects\TestLibrdkafkaProducerC++\Debug\TestLibrdkafkaProducerC++.exe	1	

Maybe you can say me, what I did wrong?

**Comment by edenhill** [comment]
@AndrewMarchuk That typically means you are linking the library statically or dynamically and haven't set LIBRDKAFKA_STATICLIB accordingly

**Comment by TSheahan** [comment]
> We now have experimental windows wheels on PyPi

successful install. this just rocked my world, thanks :)
