### ISSUE TITLE
C++ api for fetching the metadata

### ISSUE THREAD

**Issue by ghost** [edenhill/librdkafka#143]
Hello,

In C there exists an API for fetching the metadata (rd_kafka_metadata), but there is no C++ api for that.

**Comment by edenhill** [comment]
Any progress on this @eugpermar ?

**Comment by eugpermar** [comment]
Only left the C++ configuration parser of the regression test. I can try to do next week if you need it.

Sorry for the long news gap :) you got a usable API on https://github.com/eugpermar/librdkafka/commits/WIP-CPP-metadata.

**Comment by edenhill** [comment]
Any news on this, @eugpermar ? :)

**Comment by edenhill** [comment]
Fixed on master
