### ISSUE TITLE
rd_kafka_metadata() ignores if rd_kafka_MetadataRequest() fails

### ISSUE THREAD

**Issue by rthalley** [edenhill/librdkafka#1430]
Description
===========

While doing code review to try to find refcount leaks somehow associated with metadata requests as part of failures like in Issue #1326, I noticed that rd_kafka_metadata() calls rd_kafka_MetadataRequest() which can fail if a full request is already ongoing (if I read the code correctly, but it doesn't look at the the error code.  I think this means that instead of joining the ongoing request and using its result, it will instead sleep for the whole timeout period and then return TIMED_OUT.  That seems suboptimal.  I realize that "joining" the ongoing request might be hard, but maybe it could return the error immediately?

Not critical at all, but I thought I should open an issue so it could be considered.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):0.11.0, master
 - [ ] Apache Kafka version: 0.10.0
 - [ ] librdkafka client configuration: N/A
 - [ ] Operating system: N/A
 - [ ] Using the legacy Consumer  No
 - [ ] Using the high-level KafkaConsumer No
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka  N/A
 - [ ] Provide broker log excerpts  N/A
 - [ ] Critical issue  No

**Comment by edenhill** [comment]
Good find, thank you!

I believe the easiest fix is to allow the app metadata request to pass through regardless of outstanding requests, which is in line with pre 0.9.4 behaviour.
