### ISSUE TITLE
Cannot consume data when using RdKafka::Consumer::poll in specific thread

### ISSUE THREAD

**Issue by tanglianggithub** [edenhill/librdkafka#1434]
Description
Want consumed data to be sent from consume thread to other thread. But it cannot be sent for looping infinitely in consume thread.

want to change the code from
```
while (1) {
        consumer->consume_callback(topic, partition, 1000, &ex_consume_cb, &use_ccb);
        consumer->poll(0);
}
```
to
```
void KConsumer::Poll()
{
    while (1) {                      
        consumer_->poll(0);                                                             
    }
}   

void KConsumer::StartConsume()                                                         
{   
    int64_t start_offset = RdKafka::Topic::OFFSET_BEGINNING;                            
    RdKafka::ErrorCode resp = consumer_->start(topic_, partition_, start_offset);       
    if (resp != RdKafka::ERR_NO_ERROR) {                                                
      LOG(ERROR) << "Failed to RdKafka::Consumer::start() : " << RdKafka::err2str(resp);
      return;                                                                           
    }
    consumer_->consume_callback(topic_, partition_, 1000, ccb_, (void *)1);             
    poll_thread_.reset(new boost::thread(&KConsumer::Poll, this));                      
}   
```
but it didn't work.

=========
 - [ ] librdkafka version : 0.11
 - [ ] Operating system: centos
 - [ ] Using the legacy Consumer

**Comment by edenhill** [comment]
Unless you have a specific reason for using the legacy Consumer I suggest moving to the KafkaConsumer which combines poll() and consume() into just consume().
It does not however support callbacks, but refactoring your code to call your consume callback code directly after calling consume() should be trivial.

**Comment by tanglianggithub** [comment]
still confused. 
I am running the program asynchronously. cannot loop infinitely. That is to say, start consumer first, once got messages, send messages to the queue, at the same time notify post-processed program through the pipe.
For while loop, other thread programs cannot be run.

examples/rdkafka_consumer_example.cpp can solve this problem?
while (1) {
    RdKafka::Message *msg = consumer->consume(1000);
    if (!use_ccb) {
      msg_consume(msg, NULL);
    }
    delete msg;
  }

**Comment by edenhill** [comment]
Then you want to use the old legacy Consumer, yes, and create a thread from which you call `consume()`.

If you are not registering any global-level callbacks, such as EventCb, etc, you don't need to call poll()

**Comment by tanglianggithub** [comment]
If KafkaConsumer supports consuming by partition, I will try it.

can I run https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.cpp#L568 outside the while loop?  so it will run just one time.

run https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.cpp#L575 in some thread.

I tried like above, but I cannot get data consumed. Must put https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.cpp#L568  into the while loop?






consumer->poll(0);

**Comment by tanglianggithub** [comment]
another question:
If I want to pause the consuming.
must run pause function(https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1015) in other thread.
for while loop is running poll(for legacy consumer) or KafkaConsumer.consume().

not found example about pause and resume(https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1027).
