### ISSUE TITLE
Consuming using auto.offset.reset=latest doesn't emit EOF for partition 

### ISSUE THREAD

**Issue by mfontanini** [edenhill/librdkafka#1435]
Description
===========
This happened a couple of times but I can't get any logs. I basically ended up using auto.offset.reset=latest to bypass #1307 but now it seems like once in a while I hit a case where I'm loading messages right after subscribing to a topic where there are messages in already and I never get an EOF for one partition. I may add that I'm pausing consumption on every partition when I reach EOF. My consumption looks like:

```
consumer.subscribe()
while (not reached eof/filled an internal queue on all partitions) {
     msg = consumer.poll()
     if (msg.eof()) {
        consumer.pause(msg.partition)
     }
     else {
         // store message in some queue
         if (some condition) {
              consumer.pause(msg.partition)
         }
     }
}
```

And that is pretty much it. In this case I managed to attach a debugger and I can see that for one of the 10 partitions that were assigned I never reached EOF nor did I get any messages so I'm basically looping forever just waiting for that one partition to give me something. 

I think this is related to auto.offset.reset=latest because I have other consumers using the same code but using offset reset smallest which have never seen the bug and have been running for months now.  

How to reproduce
================
Consume and wait for an EOF that never comes, possibly using auto offset reset latest policy. 

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.5. Note that I'd like to use the latest version but I've been tracking the issues and noticed there's a couple of things I wouldn't want to be affected by so I'd rather wait for the next release before doing so.
 - [x] Apache Kafka version: 0.10.1.0
 - [x] librdkafka client configuration: `enable.auto.commit=false, auto.offset.reset=latest`
 - [x] Operating system: GNU/Linux x64
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue: not sure if this qualifies as critical, but the fact that I can consume and not get a single message from a partition, not even one that I'm supposed to get (the EOF one) seems undesirable and in this case completely stalls my consumption. Now I need to apply some sort of timeout so that if I'm looping for more than X seconds and I don't get any message, I just kill my application.

**Comment by edenhill** [comment]
Is there any difference between the working and non-working partitions in regards to message rate, broker leader, etc?

Can you reproduce this with `debug=topic,fetch,queue,msg,broker` and point out what partition is misbehaving?

**Comment by mfontanini** [comment]
There was only one message on one of the partitions (not the one that got stalled), the rest were empty. I did get EOF on all of them, even the one that had one message, but not on the one that got stalled.

It's really not simple for me to reproduce this, it just happens randomly and rdkafka logging is really verbose so I can't really run the application itself with logging enabled. I'll see if I can reproduce this somehow in an ad-hoc test but I don't know how long that'll take.

**Comment by mfontanini** [comment]
Okay, I reproduced this: https://gist.github.com/mfontanini/89f87fbd5eec9fa75d5715865288e422

I was assigned partitions [ 14...19 ], then started loading, and only got an EOF on partitions 14, 15 and 16. I didn't pop a valid message nor EOF notification for any of the rest of them. Is there anything else I can do to help fix this? If you can point me into some direction, I can look into it. Both this and #1307 are affecting me pretty badly. Also it seems like I can reproduce this one every time now.

**Comment by mfontanini** [comment]
I think I know what triggers this. You can find a line for parttions 17, 18 and 19 (the stalled ones) that look like this:

```

%7|1507312239.366|RESUME|matias-laptop#consumer-1| [thrd:main]: Not resuming stopped my_topic [17]: at offset 0 (state offset-wait, v3)
```

Right after I start consumption I call `resume_partitions` using all assigned ones because I may have been paused previously. I changed to logic so it only does this if it's actually paused and this seems to not trigger the issue.

It seems like the whole pausing/resuming logic in rdkafka is pretty fragile. This is probably the third issue I've found regarding this. At some point I had cases where if I paused/resumed a partition without any poll in between, the partition wouldn't pause either. All of this can be "bypassed" by not using rdkafka in particular ways but I'd expect it to handle this properly as I'm not really abusing the API.
