### ISSUE TITLE
Error  "No such file or directory" on AIX 5.3

### ISSUE THREAD

**Issue by greatt1n** [edenhill/librdkafka#1436]
Hi, recently we  try using  rdkafka on AIX 5.3  and  we succeed in compiling rdkafka 0.9.5. when we run rdkafka_example the error occurred.

related error messages are

> % Type stuff and hit enter to send
1506585436.469 RDKAFKA-3-FAIL: rdkafka#producer-1: [thrd:132.151.51.34:9091/bootstrap]: 132.151.51.34:9091/bootstrap: Failed to connect to broker at :9091: No such file or directory
1506585436.469 RDKAFKA-3-FAIL: rdkafka#producer-1: [thrd:132.151.51.34:9091/bootstrap]: 132.151.51.32:9091/bootstrap: Failed to connect to broker at :9091:9091: No such file or directory
1506585436.469 RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:132.151.51.34:9091/bootstrap]: 132.151.51.34:9091/bootstrap: Failed to connect to broker at :9091: No such file or directory
1506585436.469 RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:132.151.51.34:9091/bootstrap]: 132.151.51.32:9091/bootstrap: Failed to connect to broker at :9091:9091: No such file or directory
1506585436.469 RDKAFKA-3-FAIL: rdkafka#producer-1: [thrd:132.151.51.34:9091/bootstrap]: 132.151.51.33:9091/bootstrap: Failed to connect to broker at 132.151.51.34:9091: No such file or directory
1506585436.470 RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:132.151.51.34:9091/bootstrap]: 132.151.51.33:9091/bootstrap: Failed to connect to broker at 132.151.51.34:9091: No such file or directory
1506585436.470 RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:132.151.51.34:9091/bootstrap]: 3/3 brokers are down

What do you suggest?

**Comment by edenhill** [comment]
AIX is not an officially supported platform (because we don't have access to any AIX systems, and the demand isn't great), so you'll need to sort this out yourself or with help from other AIXians, making AIX a community supported platform.

We're happy to accept a PR if you fix this issue.
