### ISSUE TITLE
SSL spending more time then needed in RAND_add()

### ISSUE THREAD

**Issue by alanbutt** [edenhill/librdkafka#1439]
Description
===========
This is a performance suggestion.   This is a very minor issue

While performance sampling, we noticed that a fair amount of hits were in the OpenSSL method RAND_add()--which can be invoked from RAND_get_bytes().  The current OpenSSL setup is using the default implementation of RAND_add().   However, a much more efficient method exists beginning with OpenSSL 1.0.1 using the rdrand engine.   See: https://wiki.openssl.org/index.php/Random_Numbers Hardware section for details.

Attached is a patch that can be used to load the engine if its available.   The patch modifies the ssl initialization/termination methods to load the engine if available. 

Enjoy!
 
How to reproduce
================
NA

Checklist
=========
Please provide the following information:

 - [ x] librdkafka version (release number or git tag): master and previous
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [x] Operating system: windows/linux/mac os X
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

[rdkafka_transport.c.patch.txt](https://github.com/edenhill/librdkafka/files/1354141/rdkafka_transport.c.patch.txt)

**Comment by edenhill** [comment]
Thanks for the patch! Will look into this soon.

**Comment by edenhill** [comment]
In light of recent Intel security vulnerabilities I will choose not to implement this in librdkafka.
An application may still do so itself by calling the code in the provided patch prior to calling rd_kafka_new()

https://en.wikipedia.org/wiki/RdRand#Reception

Do appreciate the effort though!
