### ISSUE TITLE
NuGet: include ARM build

### ISSUE THREAD

**Issue by MaitreDede** [edenhill/librdkafka#1441]
Hi,
Is it possible to produce `arm` binaries, and distribute it inside the [nuget package](https://www.nuget.org/packages/librdkafka.redist/) ?
Since dotnet core 2.0 runs fine on Raspberry Pi, I would like to run some kafka stuff on it...
The nuget taget may be `linux-arm`.

**Comment by edenhill** [comment]
For linux platforms it is generally required to install librdkafka (and its dependencies) through the native package manager.
Providing a prebuilt generic librdkafka library for Linux has proven troublesome due to direct and indirect dependencies.

**Comment by MaitreDede** [comment]
Ok :) I will follow your advice. Thanks
