### ISSUE TITLE
One broker out of 3 down, producers not able to send message

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#1444]
[standAloneProducer.C.txt](https://github.com/edenhill/librdkafka/files/1384067/standAloneProducer.C.txt)
[writeup_for_librdkafka.pdf](https://github.com/edenhill/librdkafka/files/1384070/writeup_for_librdkafka.pdf)

Description
===========
I have 3 brokers: b1, b2, b3
I have many producers. To configure every producer, I use 

rd_kafka_brokers_add(...., "b1:9092, b2:9092, b3:9092");

When one of these brokers dies, some producers are not able to send messages to the cluster until that broker comes back up again.

What is the expected behavior in such a scenario? I thought as long as the cluster was up, producers would be able to send messages.

How to reproduce
================
See the attached files on how to reproduce the scenarios.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 10
 - [ ] librdkafka client configuration: file attached
 - [ ] Operating system: Redhat
 - [ ] Using the legacy Consumer - no
 - [ ] Using the high-level KafkaConsumer  - yes
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka - in the attached file
 - [ ] Provide broker log excerpts - in the attached file
 - [ ] Critical issue - as defined

**Comment by edenhill** [comment]
librdkafka will automatically detect partition leader changes and switch to the new leader broker.
So I'm suspecting you don't have a replica broker for your topic.

Start troubleshooting with `kafka-topics.sh --zookeeper <ZK> --describe --topic <yourtopic>` to see replication factor, replicas, isrs, etc.

**Comment by blandings** [comment]
We have 3 brokers, one topic, replication factor 3, and 3 partitions, in sync replicas is 1.

librdkafka is configured to retry sending messages 3 times. 

When a broker goes down, the producer is unable to send messages for a short duration.

1. Would setting the number of in-sync replicas = 3 make leader election quicker in the case of failure?
2. Can we fiddle with the timeout which triggers leader election?

The goal is to not lose messages like this.

Thank you.

**Comment by edenhill** [comment]
How come you only have one replica in sync?
Make sure you set `acks=all` on the producer

**Comment by blandings** [comment]
acks = all on producer already. I thought this would already take care of keeping all replicas in sync.

We will try today setting the  broker topic with in-sync replicas = 3

**Comment by blandings** [comment]
Here is the output of the topic describe command:


/opt/kafka/kafka_2.11-0.10.1.1/bin/kafka-topics.sh --describe --zookeeper <zk1:2181, zk2:2181, zk3:2181> --topic 157_6372129557625143312_24_a
Topic:157_6372129557625143312_24_a	PartitionCount:3	ReplicationFactor:3	Configs:min.insync.replicas=3	Topic: 157_6372129557625143312_24_a	Partition: 0	Leader: 1000004	Replicas: 1000004,1000003,1000002	Isr: 1000003,1000002,1000004	Topic: 157_6372129557625143312_24_a	Partition: 1	Leader: 1000002	Replicas: 1000002,1000004,1000003	Isr: 1000002,1000003,1000004	Topic: 157_6372129557625143312_24_a	Partition: 2	Leader: 1000003	Replicas: 1000003,1000002,1000004	Isr: 1000003,1000002,1000004
--

**Comment by edenhill** [comment]
That looks good, all partition replicas are in sync.

Please edit the top comment and fill out the checklist.

**Comment by blandings** [comment]
done. Please see attached files.

**Comment by blandings** [comment]
We switched to version 11, added the dr_msg_cb, the error_cb, and we poll after every produce. 

We don't see message loss any more. Thank you for your help.
