### ISSUE TITLE
qustion about pause/resume consume?

### ISSUE THREAD

**Issue by tanglianggithub** [edenhill/librdkafka#1447]
Can I use pause/resume function as follows? 

```
class ExampleConsumeCb : public RdKafka::ConsumeCb {
public:
  void consume_cb (RdKafka::Message &msg, void *opaque) {
    RdKafka::Consumer::pause();
    sleep(2);
    RdKafka::Consumer::resume();
  }
};
```

**Comment by edenhill** [comment]
Yes, that should work, but may I ask why?
The library will handle back-pressure automatically, if you are not processing messages the librdkafka will eventually (thresholds set by configuration properties `queued.max.messages.kbytes` and `queued.min.messages`) stop fetching new messages until more are needed.

The only reason to pause() is if you want to call poll() or consume() and only serve non-message events for a while.

**Comment by tanglianggithub** [comment]
my ExampleConsumeCb is as follows:
```
class ExampleConsumeCb : public RdKafka::ConsumeCb {
public:
  void consume_cb (RdKafka::Message &msg, void *opaque) {
       std::string msg(static_cast<const char *>(message.payload()), static_cast<int>(message.len()));
       `queue_`.push(msg);
  }
};
```
put received messages from ExampleConsumeCb into a `queue_`.
another thread will pull from `queue_` and process the data and processing speed is slower than received speed.
so don't think `queued.max.messages.kbytes` and `queued.min.messages` will work for consumed messages are only put `queue_` .
If putting post-processing programming into the ExampleConsumeCb may work. But cannot for some reason.

**Comment by edenhill** [comment]
pause and resume does make sense in your setup, but I would suggest minising queued.min.messages anyway since when you pause() all messages pre-fetched into the queue will be purged.

**Comment by tanglianggithub** [comment]
Can I just put sleep function as follows? Thus,  all messages pre-fetched into the queue cannot be purged.
Does it have a bad effect on heartbeat?
```
class ExampleConsumeCb : public RdKafka::ConsumeCb {
public:
  void consume_cb (RdKafka::Message &msg, void *opaque) {
    ...
    if(downstream_state_ == "slow")
           sleep(2);
    ...
  }
};
```

**Comment by edenhill** [comment]
Heartbeats and pre-fetching is handled by a background thread, so you should be fine with sleeping.
