### ISSUE TITLE
Trying to install librdkafka on a RHEL VM that does not have internet connectivity

### ISSUE THREAD

**Issue by sdggithub02** [edenhill/librdkafka#1448]
Hello Eden:
I am trying to use the confluent-python API on a RHEL VM that is not connected to the internet, I have downloaded your latest version of the librdkafka (Oct 5 release) from GIT, and copied to the VM, but ran into issues installing the library. Can you please let me know how to proceed ?

Description
===========
1. On Mac, git clone https://github.com/edenhill/librdkafka.git
2. scp-ed the code to the RHEL 7 VM to /tmp
3. cd /tmp
4. As root, ./configure --prefix /usr
    Here is the output:
    using cache file config.cache
checking for OS or distribution... ok (RedHatEnterpriseServer)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok (cached)
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok (cached)
checking executable ld... ok (cached)
checking executable nm... ok (cached)
checking executable objdump... ok (cached)
checking executable strip... ok (cached)
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok (cached)
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok (cached)
checking for __atomic_64 (by compile)... ok (cached)
checking for socket (by compile)... ok (cached)
parsing version '0x000b00ff'... ok (0.11.0)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok (cached)
checking for zlib (by pkg-config)... failed
checking for zlib (by compile)... ok (cached)
checking for libcrypto (by pkg-config)... failed
checking for libcrypto (by compile)... ok (cached)
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... ok (cached)
checking for libssl (by pkg-config)... failed
checking for libssl (by compile)... failed (disable)
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... ok (cached)
checking for crc32chw (by compile)... ok (cached)
checking for regex (by compile)... ok (cached)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for strndup (by compile)... ok (cached)
checking for strerror_r (by compile)... ok (cached)
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok (cached)
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           y
  ENABLE_SSL               y
  ENABLE_SASL              y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               RedHatEnterpriseServer
  SOLIB_EXT                .so
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.11.0
  MKL_APP_VERSION          0.11.0
  LIBS                     -lpthread -lz -lcrypto -llz4 -lsasl2 -lrt -ldl
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr
  bindir                   /usr/bin
  sbindir                  /usr/sbin
  libexecdir               /usr/libexec
  datadir                  /usr/share
  sysconfdir               /usr/etc
  sharedstatedir           /usr/com
  localstatedir            /usr/var
  libdir                   /usr/lib
  includedir               /usr/include
  infodir                  /usr/info
  mandir                   /usr/man

5. As root, make
    Here is the output
    gcc -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -DLIBRDKAFKA_GIT_VERSION="\"\""  -c rdkafka.c -o rdkafka.o
In file included from rdkafka_buf.h:31:0,
                 from rdkafka_int.h:91,
                 from rdkafka.c:38:
rdcrc32.h:30:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
make[1]: *** [rdkafka.o] Error 1
make[1]: Leaving directory `/tmp/librdkafka/src'
make: *** [libs] Error 2

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ dated Oct 5 commit c44f40be96556ab8145f0f5bcaa500d16d4e0fc4] librdkafka version (release number or git tag):
 - [ 0.11] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It looks like the build tree was not clean before you copied it, resulting in reusing the configure settings.

Try running `./configure --clean` on the Linux host before running `./configure` and `make`

**Comment by sdggithub02** [comment]
Thanks Magnus, followed your advice and this took me a step further, however got a Warning

./configure --clean
./configure --prefix /usr
- make (ran this as root)

  make[1]: Entering directory `/opt/Kafka-Scripts/librdkafka/src'
	gcc -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -DLIBRDKAFKA_GIT_VERSION="\"\""  -c rdkafka.c -o rdkafka.o
	In file included from rd.h:68:0,
	                 from rdkafka_int.h:44,
	                 from rdkafka.c:38:
	rdkafka.c: In function ‘rd_kafka_version_str’:
	rdkafka.c:2960:56: warning: offset outside bounds of constant string [enabled by default]
	                                  LIBRDKAFKA_GIT_VERSION+1 :
	                                                        ^
	rdposix.h:84:36: note: in definition of macro ‘rd_snprintf’
	 #define rd_snprintf(...)  snprintf(__VA_ARGS__)

**Comment by sdggithub02** [comment]
Anyway continued with make install (as root) and got the following output, does the output suggest that I installed librdkafka successfully ?

make install
  [root@lpdosput50090 librdkafka]# make install
	make[1]: Entering directory `/opt/Kafka-Scripts/librdkafka/src'
	Install librdkafka to /usr
	install -d $DESTDIR/usr/include/librdkafka ; \
	install -d $DESTDIR/usr/lib ; \
	install rdkafka.h $DESTDIR/usr/include/librdkafka ; \
	install librdkafka.a $DESTDIR/usr/lib ; \
	install librdkafka.so.1 $DESTDIR/usr/lib ; \
	[ -f "rdkafka.pc" ] && ( \
		install -d $DESTDIR/usr/lib/pkgconfig ; \
		install -m 0644 rdkafka.pc $DESTDIR/usr/lib/pkgconfig \
	) ; \
	(cd $DESTDIR/usr/lib && ln -sf librdkafka.so.1 librdkafka.so)
	make[1]: Leaving directory `/opt/Kafka-Scripts/librdkafka/src'
	make[1]: Entering directory `/opt/Kafka-Scripts/librdkafka/src-cpp'
	Install librdkafka++ to /usr
	install -d $DESTDIR/usr/include/librdkafka ; \
	install -d $DESTDIR/usr/lib ; \
	install rdkafkacpp.h $DESTDIR/usr/include/librdkafka ; \
	install librdkafka++.a $DESTDIR/usr/lib ; \
	install librdkafka++.so.1 $DESTDIR/usr/lib ; \
	[ -f "rdkafka++.pc" ] && ( \
		install -d $DESTDIR/usr/lib/pkgconfig ; \
		install -m 0644 rdkafka++.pc $DESTDIR/usr/lib/pkgconfig \
	) ; \
	(cd $DESTDIR/usr/lib && ln -sf librdkafka++.so.1 librdkafka++.so)
	make[1]: Leaving directory `/opt/Kafka-Scripts/librdkafka/src-cpp'


Here is the output of /usr/lib directory
[root@lpdosput50090 ~]# ls -l /usr/lib/librd*
-rwxr-xr-x 1 root root 12202966 Oct  9 09:42 /usr/lib/librdkafka.a
-rwxr-xr-x 1 root root  2461650 Oct  9 09:42 /usr/lib/librdkafka++.a
lrwxrwxrwx 1 root root       15 Oct  9 09:42 /usr/lib/librdkafka.so -> librdkafka.so.1
lrwxrwxrwx 1 root root       17 Oct  9 09:42 /usr/lib/librdkafka++.so -> librdkafka++.so.1
-rwxr-xr-x 1 root root  4959408 Oct  9 09:42 /usr/lib/librdkafka.so.1
-rwxr-xr-x 1 root root   956424 Oct  9 09:42 /usr/lib/librdkafka++.so.1

**Comment by edenhill** [comment]
Looks ok

**Comment by sdggithub02** [comment]
Hi Magnus:
As you confirmed, librdkafka is now installed successfully, but do you know why this warning appeared and how to clear it ?

./configure --clean
./configure --prefix /usr

make (ran this as root)

make[1]: Entering directory `/opt/Kafka-Scripts/librdkafka/src'
gcc -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -DLIBRDKAFKA_GIT_VERSION="""" -c rdkafka.c -o rdkafka.o
In file included from rd.h:68:0,
from rdkafka_int.h:44,
from rdkafka.c:38:
rdkafka.c: In function ‘rd_kafka_version_str’:
rdkafka.c:2960:56: warning: offset outside bounds of constant string [enabled by default]
LIBRDKAFKA_GIT_VERSION+1 :
^
rdposix.h:84:36: note: in definition of macro ‘rd_snprintf’
#define rd_snprintf(...) snprintf(VA_ARGS)

**Comment by edenhill** [comment]
The empty LIRDKAFKA_GIT_VERSION is probably becausing you are copying the directory.
Try removing the .git folder before running ./configure ..
