### ISSUE TITLE
Kafka cluster Partitions are not same after topics copied in target cluster 

### ISSUE THREAD

**Issue by Sarahshee** [edenhill/librdkafka#1449]
Description
===========

the source kafka cluster 1 topic contains 60 partitions and the other one have 100, when i trying to copying the topics to the destination cluster topics has been created and all looks good except the number of partitions, the number of partitions count does not show 60, are 100, how would get this fixed ?

Kafka cluster Partitions are not same to the target clusters as per source after topics copied in target cluster , how do we get fixed ?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please edit your original comment and fill out the issue template.

Also: what do you mean by "copying topics"? How are you doing that?

Hint: Use `kafka-topics.sh ... --describe ..` to see what the cluster thinks of your topics.

**Comment by Sarahshee** [comment]
Hi , sorry for the late reply, I will be doing the kafka mirror maker command to copying the topics from source cluster to target cluster ,

ex:-source cluster topic name :- abcd and it contains 40 partitions 
in target the data is coying the same size but partitions are not creating the same no 40 and it shows only one instead of 40. kafka has no ability to produce the same whatever in source to target ?

**Comment by edenhill** [comment]
This sounds more of an issue with mirror maker, librdkafka can only produce to partitions that actually exist.
