### ISSUE TITLE
Increase partitions of the topic,the last data in queue of the topic will be repeated

### ISSUE THREAD

**Issue by Wingoom** [edenhill/librdkafka#1454]
Description
===========
librdkafka version 0.9.0

when my producer client is running, if I increase partitions of the topic,  the last data in queue of the topic will be repeated.

Then restart my producer client,the last data return to normal.  
It is so strange!

the code:
RdKafka::ErrorCode resp = producer->produce(topic, partition,
                          RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
                          const_cast<char *>(tmp_sBuf), sBufLen,
                          NULL, NULL);
I am sure the number of messages for producing is no change always.

How to reproduce
================
running the producer API program，then  increase partitions of the topic

**Comment by edenhill** [comment]
I believe this has been fixed.
Please upgrade to librdkafka 0.11.0/master and try to reproduce.

**Comment by Wingoom** [comment]
thanks!
