### ISSUE TITLE
No broker, but rd_kafka_produce returns 0

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#1456]
Description
===========
rd_kafka_produce returns a 0 even when there is no broker running at the hostname:port combination I use when setting up rd_kafka_conf and rd_kafka_topic_conf.

What is the expected behavior?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 10
 - [ ] librdkafka client configuration: ack=all, default batching, max retries 3, queue.buffering.max.ms 1
 - [ ] Operating system: Redhat
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by girone** [comment]
Although this is confusing, I think this is intended. You need to install a handler to make the internal events of librdkafka visible.

How I solved this in C++ (I guess you can derive the C way from that): 
1. Implement the pure virtual EventCb 
```
class EventHandler : public RdKafka::EventCb
{
 public:
    EventHandler() { }

    void event_cb(RdKafka::Event& event) override {
        if (event.type() == RdKafka::Event::EVENT_LOG)
	{
		std::cout << "Kafka log message: " << event.str() << std::endl;
                // there is also event.severity() which can be used
	}
	else if (event.type() == RdKafka::Event::EVENT_ERROR)
	{
		std::cerr << "Kafka error: " << RdKafka::err2str(event.err()) << std::endl;
	}
        // ...
};
```
2. Configure librdkafka to use it
```
EventHandler myhandler;
config->set("event_cb", &myhandler, &errstr);  // NOTE in the C++ interface, you can install just one 
if (not errstr.empty()) {
    std::cerr << errstr << std::endl;
}
// Start producer with the config ...
```

Note that according to [CONFIGURATION.md](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md#global-configuration-properties) you can set separate callbacks for error, log, stats and throttling. However, in the C++ version only one common callback object can be set with `"event_cb"`, which needs to distinguish the type internally. Will have a separate issue for this. 

@edenhill it would be nice to have a more thorough example for this in the [INTRODUCTION.md](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#threads-and-callbacks).

**Comment by blandings** [comment]
Thank you. I agree that there needs to be thorough example.

With the distributed architecture, asynchronous delivery, and all these different callbacks, I pretty much have no idea whether my messages got to the broker or not. 

Since performance is key, I need to use batching  and asynchronous delivery. However, what I really want is for librdkafka to provide a callback for a failed batch - so that I could then persist that batch on high performance storage or some such and provide some reliability guarantees without having to subscribe to the performance hogging synchronous delivery mechanism.

I also cannot keep per event statistics today because no callback is available for per batch. Only per event which is too expensive.

**Comment by edenhill** [comment]
That's what the DeliveryReportCb is for, it will be called exactly once per message (triggered by your application calling `..->poll()` at regular intervals) to inform you whether the message was successfully delivered, or if there was an error.

The `message.timeout.ms` configuration property decides how long librdkafka will attempt to deliver the message, which alleviates the application from having to think about and handle disconnect, leader changes, etc.

**Comment by edenhill** [comment]
See the INTRODUCTION for more info:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-reliability

**Comment by blandings** [comment]
I understand that.

However, do you have any gauge/test on how that might affect performance? 

Also, what do you mean by 'regular intervals'? After every produce?

Let's say, I 'poll' after 100 messages. Will the callbacks enqueue for all 100 messages?

Thanks for all your clarifications.

**Comment by tinux2015** [comment]
you can try this after call rd_kafka_produce()
     while( 0 ==rd_kafka_poll())  { }

**Comment by edenhill** [comment]
@blandings That is up to you and your produce pattern, but there are usually two ways to do it:
 1. run rd_kafka_poll(rk, 1000); from its own thread in a loop
 2. call rd_kafka_poll(rk, 0);  after each produce(). This is a non-blocking call that will serve previously produced messages. Before terminating, call rd_kafka_flush() to make sure the last produced messages are delivered.

More elaborate pseudo code example for 2:
```
rk = rd_kafka_new(..PRODUCER..);

while (run) {
retry:
     r = rd_kafka_produce(...);
     if (r != -1) {
         rd_kafka_poll(rk, 0);
         continue;
      }

      // Handle error:
       if (rd_kafka_last_error() == _QUEUE_FULL) {
            rd_kafka_poll(rk, 1000); // wait for deliveries before retrying
            goto retry;
        } else {
           // handle other errors..
        }
}

rd_kafka_flush(rk, 5000);

rd_kafka_destroy(rk)
```


I would not recommend @tinux2015 suggestion since that effectively makes the produce synchronous and very slow.

**Comment by blandings** [comment]
@edenhill : Thank you very much! This makes a lot of sense.
