### ISSUE TITLE
Configuration for log_cb, error_cb, etc. does not work in C++ interface

### ISSUE THREAD

**Issue by girone** [edenhill/librdkafka#1457]
Description
===========

As I understood it, the configuration options for C and C++ should be the same. However, using `set("log_cb", ...)` as [documented here](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) does not work in the C++ interface. The code ends up in [this line](https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp_int.h#L265) and produces the error message `Invalid value type, expected RdKafka::EventCb`. Which is not helpful, because the value type is actually correct.

The workaround is to use `set("event_cb", ...)` instead and use one callback object, which internally distinguishes the event type as described in #1456. 

Is there any reason why the C++ interface does not allow to set different callbacks? I think there should be at least a hint in the documentation.

Solution alternatives:
* In `ConfImpl` and `HandleImpl` distinguish all four event types and pass on individual callbacks to the underlying code.
* Update the error message when trying to set, e.g. "log_cb" instead of "event_cb" and update the documentation how to handle internal log messages/errors from the C++ interface.

How to reproduce
================

Run a program which tries to set e.g. "log_cb", "error_cb", ... using the C++ interface.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.0
 - [x] Apache Kafka version: No cluster required to reproduce the problem.
 - [x] librdkafka client configuration: See above.
 - [x] Operating system: Linux.
 - [ ] Using the legacy Consumer 
 - [x] Using the high-level KafkaConsumer 
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts: Not needed
 - [ ] Critical issue

**Comment by edenhill** [comment]
The log_cb, error_cb, ..etc properties are not supposed to be set through the string-based set():er but with specific APIs.
Now, for C++ those callbacks are abstracted into a common EventCb class that you should use instead.
