### ISSUE TITLE
Are there any topic_conf callbacks?

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#1459]
Description
===========
There are error_cb, stats_cb, etc - but they all apply to kafka_conf.

Are there any callbacks that apply to a kafka_topic_conf? What if I wanted to pass a kafka_topic_conf object as opaque to one of these callbacks?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system: Redhat
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The topic object is provided in callbacks (directly or indirectly) where it makes sense.
You can set a per-topic opaque value using `rd_kafka_topic_conf_set_opaque()` which you can later extract from a `rd_kafka_topic_t` object using `rd_kafka_topic_opaquie()`.

**Comment by blandings** [comment]
Understood. Thanks.
