### ISSUE TITLE
Retries on leadership change

### ISSUE THREAD

**Issue by ottomata** [edenhill/librdkafka#146]
This is just a question, not really an issue.

Let's say there are queued messages waiting for ACKs from a particular broker.  That broker dies, and then a few seconds later the producer is notified of a leadership metadata change.  When the messages are retried, will they be sent the new leaders?

**Comment by mmanoj** [comment]
@edenhill 

This is same I was discussing with you in thread -issues/186 , as per my observation it's not happen when I kill the leader broker. Please advice.
