### ISSUE TITLE
Which is the latest stable release for librdkafka?

### ISSUE THREAD

**Issue by kparadkar** [edenhill/librdkafka#1461]
What is the difference in librdkafka 0.9.5 and 0.11.x api implementation? 
We are curretnly using 0.9.1 apis with kafka 0.9 and plan to move to kafka 0.10/11 soon (TBD), which release should librdkafka be upgraded to?

**Comment by edenhill** [comment]
0.11.0 is the latest stable release of librdkafka and is fully backwards compatible with older broker versions.
Do note however that we'll be releasing a 0.11.1 maintenance release within a couple of days, so you might want to wait for that one.

Also make sure to look at the release notes for each release.
