### ISSUE TITLE
additional modes of Apache Kafka version 0.11

### ISSUE THREAD

**Issue by tinux2015** [edenhill/librdkafka#1462]
Description
===========
Apache Kafka version 0.11 has some additional modes:
**the KafkaProducer supports two additional modes: the idempotent producer and the transactional producer. The idempotent producer strengthens Kafka's delivery semantics from at least once to exactly once delivery**

Which verson of librdkafka is support this?

Best wishes!

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ 0.11.1] librdkafka version (release number or git tag):
 - [0.11.1 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Neither of those features are yet implemented in librdkafka.
We're aiming for the Q1 release.

**Comment by tinux2015** [comment]
thanks a lot

**Comment by tinux2015** [comment]
thanks a lot

**Comment by rnpridgeon** [comment]
@arcoviilan,  checkout #1308

**Comment by arcoviilan** [comment]
@rnpridgeon, thanks! I didn't see this issue somehow ... so exciting news and thanks for your work!
