### ISSUE TITLE
odd interaction of socket.blocking.max.ms and queue.buffering.max.ms

### ISSUE THREAD

**Issue by tbsaunde** [edenhill/librdkafka#1464]
When queue.buffering.max.ms is 1 I see significantly lower worst case latency with socket.blocking.max.ms=2 compared to socket.blocking.max.ms=1, on the order of 50ms for the former and 110ms for the latter.  I suspect this is because of the logic that decides if a wakeup fd is used at rdkafka_broker.c:3398 or so.

**Comment by edenhill** [comment]
socket.blocking.max.ms has been removed
