### ISSUE TITLE
RD_KAFKA_MSG_F_FREE and msg_dr_cb in case of failure

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#1466]
Description
===========
There are cases when rd_kafka_produce returns 0 even when the producer is unable to send a message to the broker/s.

In such cases, if msg_dr_cb is registered, then it is invoked and the failed message is returned in rd_kafka_message_t->payload.

However, if RD_KAFKA_MSG_F_FREE was set, then is the payload memory the caller's responsibility?

This is a clarification question. I know from the documentation that:

"*    If the function (rd_kafka_produce) returns -1 and RD_KAFKA_MSG_F_FREE was specified, then
 *    the memory associated with the payload is still the caller's
 *    responsibility."

However, my question is **not** about when rd_kafka_produce returns -1, but **when it returns a 0 and the message could not be sent.**

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
When produce() accepts a message (returns 0) the msgflags directive is in effect, so for the case of MSG_F_FREE it means librdkafka will free the payload when the message is eventually destroyed (after dr_msg_cb() is called)

**Comment by blandings** [comment]
Thank you!
