### ISSUE TITLE
"Broker: Request timed out" on commit

### ISSUE THREAD

**Issue by greatt1n** [edenhill/librdkafka#1470]
Hello,we used high-level consumer api and seted "auto.commit.enable=false", sometimes synchronous commits  failed  with "Broker: Request timed out". The property "socket.timeout.ms" is 60000 ,we thought if the spent time exceeded  this value ,however it took about 30 seconds from fetch messages to commit offset.
So we don't know how to correctly deal this error.
1、sleep several milliseconds and  re-commit the offsets?
2、or increase any other "timeout properties"?

**Comment by edenhill** [comment]
synchronous commit() uses the session.timeout.ms, not socket.timeout.ms.

**Comment by greatt1n** [comment]
Okay，but session.timeout.ms is much longer ,now session.timeout.ms=120000，we checked the broker server logs at that time and found nothing.

**Comment by greatt1n** [comment]
I checked the broker's logs,found that the controller reconneted all the brokers that time ,infos like this:

> java.io.IOException: Connection to 2 was disconnected before the response was read
>         at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1$$anonfun$apply$1.apply(NetworkClientBlockingOps.scala:87)
>         at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1$$anonfun$apply$1.apply(NetworkClientBlockingOps.scala:84)
>         at scala.Option.foreach(Option.scala:257)
>         at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1.apply(NetworkClientBlockingOps.scala:84)
>         at kafka.utils.NetworkClientBlockingOps$$anonfun$blockingSendAndReceive$extension$1.apply(NetworkClientBlockingOps.scala:80)
>         at kafka.utils.NetworkClientBlockingOps$.recursivePoll$2(NetworkClientBlockingOps.scala:137)
>         at kafka.utils.NetworkClientBlockingOps$.kafka$utils$NetworkClientBlockingOps$$pollContinuously$extension(NetworkClientBlockingOps.scala:143)
>         at kafka.utils.NetworkClientBlockingOps$.blockingSendAndReceive$extension(NetworkClientBlockingOps.scala:80)
>         at kafka.controller.RequestSendThread.liftedTree1$1(ControllerChannelManager.scala:190)
>         at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:181)
>         at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)

**Comment by edenhill** [comment]
The OffsetCommitRequest should be retried up to `retries`(default 2) times with a `retry.backoff.ms` backoff (default 100 ms).
It is likely that the brokers did not manage to reconnect within that time period (~2*100ms) which causes the commit to fail permanently.
Suggestion is to either increase retries and and backoff, which goes for all request types, or retry the sync offset commit manually after a short delay in your application when you see this error.

**Comment by greatt1n** [comment]
Thanks very much. I will do as you suggested.

**Comment by thijsc** [comment]
We also ran into this issue. We have `session.timeout.ms` set to 60000 and `retry.backoff.ms` and `retries` set to the default. We measured how long the commit timeout took and it fails after 5-6 seconds. That should be about 180 seconds with these settings right?

**Comment by thijsc** [comment]
Just did an experiment with setting `session.timeout.ms` to 60000 and then the commit fails after 5 seconds. It looks like these configuration options do work together in a different way than described here?

**Comment by edenhill** [comment]
@thijsc Which librdkafka version?

**Comment by thijsc** [comment]
0.11.3

**Comment by edenhill** [comment]
Thanks.

The timeout originally reported ("Broker: Request timed out")  is a broker-side timeout which corresponds to the **broker** property `offsets.commit.timeout.ms` that defaults to 5000ms.

Search for `offsets.commit.timeout.ms` here:
http://kafka.apache.org/documentation.html#brokerconfigs

**Comment by thijsc** [comment]
Thanks for the info. Will this be retried if `retries` is configured?

**Comment by edenhill** [comment]
Yes it will be immediately retried on <=0.11.3, for the upcoming version it will be retried after `retry.backoff.ms`

**Comment by thijsc** [comment]
Interesting, we don't see that happening. We have `retries` set to 5 now but the total timeout is still only five seconds.

**Comment by thijsc** [comment]
To clarify: I'm measuring the total time the commit function takes in our own code. So I know for sure how long the commit call takes.

**Comment by edenhill** [comment]
It might be related to a bug where the request timeout was not reset on retry, so it would immediately time out on retry.

The `retry_fixes` branch should have a fix for this, could you give it a shot?

**Comment by thijsc** [comment]
I will try that branch. It will take a few days to know if this fixed it, we only see the timeouts a few times a day.

**Comment by edenhill** [comment]
Thanks!
