### ISSUE TITLE
in-sync replicas and failures

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#1471]
Description
===========
If I have 3 partitions per topic, 3 replicas on 3 brokers and in-sync replica is set to 3, if one broker goes down, that that mean rd_kafka_produce (acks = all) will block?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
produce() is async (unless you specify MSG_F_BLOCK, but that requires a separate poll thread and is most likely not what you want) and will not block.
Messages are immediately enqueued on the internal queue for later transmission to the leader broker, when it becomes available.
When local queue is full produce() will reject the message and fail.

**Comment by blandings** [comment]
Thank you!
As a follow up - is there any API or a plan to provide API to drain failed message queue in bulk?

**Comment by edenhill** [comment]
Failed messages will already be ready for your dr callback when you call poll.

But there is currently no API to drain messages that have not yet failed (message.timeout.ms or retries not yet reached), that feature request is tracked in #990

**Comment by blandings** [comment]
Thank you!
