### ISSUE TITLE
offset_store_method : file not work

### ISSUE THREAD

**Issue by qdore** [edenhill/librdkafka#1474]
Description
===========
Use offset.store.method : file not work
Use gdb attach process:  rd_kafka_offset_store_init hasn't been run since the program start

How to reproduce
================

./rdkafka_consumer_example_cpp -g deviceConsumerGroup -b 192.168.72.10:9092,192.168.72.20:9092,192.168.72.25:9092,192.168.72.26:9092,192.168.72.27:9092 -e -X auto.offset.reset=earliest -X enable.auto.commit=true -X offset.store.method=file -X offset.store.sync.interval.ms=10 -X offset.store.path=/home/xlq/gitlab/device -v log-old

**Comment by edenhill** [comment]
You need to use "topic.offset.store.method" with that tool since it is a topic-level property.
