### ISSUE TITLE
rd_kafka_subscribe how to start from RD_KAFKA_OFFSET_STORED ?

### ISSUE THREAD

**Issue by qdore** [edenhill/librdkafka#1475]
Description
===========
While use rd_kafka_subscribe to recieve message, how to make sure every partition start from RD_KAFKA_OFFSET_STORED instead of RD_KAFKA_OFFSET_INVALID ?
If start from RD_KAFKA_OFFSET_INVALID, store to broker or file is not working.

**Comment by edenhill** [comment]
Calling assign() with OFFSET_INVALID actually means "Use stored offset", so it should do what you want.

**Comment by qdore** [comment]
@edenhill  Actually I want to use file to store offset, calling assign() with OFFSET_INVALID will not run rd_kafka_offset_store_init

![image](https://user-images.githubusercontent.com/6831829/31814441-404d0016-b54f-11e7-8af1-7e386d27fb88.png)

**Comment by edenhill** [comment]
The high-level consumer (subscribe() or assign()) only supports broker-based offset storage.
The file-based offset storage can only be used with the legacy consumer (consume_start()).

You can work around this by disable auto commit and manually writing the offsets to a file, and reading them when starting to consume.
