### ISSUE TITLE
librdkafka producer write msg into only one partition when nine partitions available

### ISSUE THREAD

**Issue by Lionel-Coding-Lee** [edenhill/librdkafka#1477]
Description
===========
We use librdkafka to write msgs to about 30 topics, on 3 kafka brokers, almost 3 partitions per topic except 2 heavy-load topics with 9 paritions.
But we find that some topics only have one partition being written in for several days.
And this problem disappeared after recreate these topics and restart producer program.

How to reproduce
================
No clear idea to reproduce

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
0.9.0.99
 - [x] Apache Kafka version: 
0.9.0
 - [x] librdkafka client configuration:
only [bootstrap servers] configured
 - [x] Operating system:
linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
No logs
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
* Are you specifying a message key when producing?
 * What partitioner did you use?
 * Did the affected topic have available broker leaders for all its partitions?
