### ISSUE TITLE
Memory leak when producev() fails

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#1478]
Description
===========
The s_rkt rkt shared reference is not destroyed when msg_new() in producev() fails, typically due to QUEUE_FULL.

The lost reference potentially triggers hang-on-termination.

This was originally reported by @fede1024 

How to reproduce
================
Set low queue.buffering.max.messages or construct a too large message and call producev() until it fails.

**Comment by fede1024** [comment]
I can confirm that after the fix I don't see the memory leak in valgrind anymore (see output [before](http://paste.ubuntu.com/25777470/) and [after](http://paste.ubuntu.com/25784334/) the fix).
