### ISSUE TITLE
Basic producer monitoring 

### ISSUE THREAD

**Issue by willastronomer** [edenhill/librdkafka#1484]
Description
===========
Sorry to open an issue for this but I couldn't find a better way to reach out. I'm having some issues finding documentation on how to gather  what would be the basic performance/health stats in the java producer. I'm attempting to pull response rate, request rate, bytes out and average request latency. Is the expectation that librdkafka gives back the per partition/broker stats and the user aggregates them as they see fit and monitor that?

**Comment by edenhill** [comment]
You typically register a stats_cb/stats event callback and forward the emitted json to a stats collector.
The JSON format is documented here:
https://github.com/edenhill/librdkafka/wiki/Statistics

**Comment by willastronomer** [comment]
I've registered the stats but I'm not sure what the typical way to get a wholistic view of the producer performance as the stats are returned per broker and per topic / partition.

**Comment by willastronomer** [comment]
Closing the issue as i had missed all the possible debug configurations in https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md. Thanks for the quick reply
