### ISSUE TITLE
how set config:producer.type

### ISSUE THREAD

**Issue by tinux2015** [edenhill/librdkafka#1485]
Description
===========
when I set config[producer.type] by rd_kafka_conf_set() or (), both return error:
**error[No such configuration property: "producer.type"]**
why? how set config:producer.type?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.10  ] librdkafka version (release number or git tag):
 - [0.10 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That is not a librdkafka configuration property:
librdkafka does not yet implement the idempotent producer. Tracked here #1308
