### ISSUE TITLE
how to set offset when using consumer like rdkafka_consumer_example.c

### ISSUE THREAD

**Issue by tinux2015** [edenhill/librdkafka#1486]
Description
===========
My program of consumer needs to call rd_kafka_subscribe(),but I want to set offset for each partation by myself, so may I set the offset? and how?
Looking forward to your reply.
BEST WISHES!

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.10 ] librdkafka version (release number or git tag):
 - [0.10 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Register a rebalance_cb and on ASSIGNED_PARTITIONS you update the partition list with your desired offsets before calling assign().
Make sure to read the docs for rebalance_cb on your responsibilies.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/Manually-setting-the-consumer-start-offset
