### ISSUE TITLE
Messages lost when a broker is down

### ISSUE THREAD

**Issue by greatt1n** [edenhill/librdkafka#1487]
Hello,edenhill,I found when I kill -9 a broker ,the broker will lose some messages.
My scenario is the following:

- Kafka cluster with 3 brokes.
- Topic sample1 with 3 partions & 3 replicas .
- Start a producer application  which producing 1000000 messages on topic sample1.
- Kill -9 one of the brokers.
- After the producer  application produced messages done ,I found  additional offsets < 1000000.
- I tryed 3 times,the lost messages maybe 3000 or 4000.

My produce code like this
```
while (run) {
retry:
     if (rd_kafka_produce(...) != -1) {
         rd_kafka_poll(rk, 0);
         continue;
      }
      if (rd_kafka_last_error() == RD_KAFKA_RESP_ERR__QUEUE_FULL) {
            rd_kafka_poll(rk, 1000); // wait for deliveries before retrying
            goto retry;
       } 
}
```
My broker version is 0.11.0.0 and  configurations are:
> min.insync.replicas=2

My librdkafka version is 0.11.1 RC1 and configurations are:

> socket.keepalive.enable=true
> log.connection.close=false
> queue.buffering.max.messages=10000
> queue.buffering.max.kbytes=400000
> request.required.acks=all
> message.send.max.retries=3
> retry.backoff.ms=10000

**Comment by edenhill** [comment]
Are you checking the error code for each message in the delivery report to make sure you only count the successfully produced messages?
Make sure to disable unclean leader election on the broker.

**Comment by greatt1n** [comment]
Thanks for your reply.I seted "unclean.leader.election.enable=false" on the broker and added delivery report callback in my application. Messages lost again and the errmsg is "Local: Message timed out". The property "message.timeout.ms" is defalut value 300000. increase this value ?

**Comment by edenhill** [comment]
message.timeout.ms tells librdkafka for how long it may try to deliver a message, set it high enough to allow brokers to come back up again after a failure.
