### ISSUE TITLE
wrong offset when using auto_offset_reset= smallest

### ISSUE THREAD

**Issue by silviucpp** [edenhill/librdkafka#1488]
Description
===========

Hello,

I have a very strange issue with consuming messages. I'm using kafka manager to monitor the lag on the topics and even if sometimes shows me that my group has 0 lag when I start the consumer starts consuming from an older topic.

This bug is radom, for example I produce some messages then I consume all of them using my consumer, I restart the consumer several times and nothing there to consume which works as expected and next day when I start consumer again it finds 2-3 messages or more.

All the time kafka manager doesn't show any lag (which is true).

Beside the default settings I'm using:

client config: debug="all", api.version.request="true",
topic config = "auto_offset_reset"= "smallest"

I'm also attaching the logs . In this particular case kafka manager shows:

<img width="1156" alt="consumed_topic_view" src="https://user-images.githubusercontent.com/4814731/32048117-fe069b5c-ba50-11e7-826d-f419d39b7ed2.png">

But librdkafka on the following partitions start consuming from old offsets:

handle_message topic: <<"events3">> partition: 6 offset: 12
handle_message topic: <<"events3">> partition: 9 offset: 5
handle_message topic: <<"events3">> partition: 11 offset: 3

Logs are here:

[log.txt](https://github.com/edenhill/librdkafka/files/1417924/log.txt)

Any idea where problem can be ?

Checklist
=========
 - [x] librdkafka version (release number or git tag): v0.11.1
 - [x] Apache Kafka version: 0.10.1.0

**Comment by silviucpp** [comment]
Hello @edenhill do you have any clue about this problem ? I tried also last master and it's the same, once I go in the next day when consumer starts it's always processing few messages above.

In this case what kafka manager shows is the proper offset value. 

Silviu

**Comment by silviucpp** [comment]
Seems problem replicates when I change the ip of the consumer

**Comment by edenhill** [comment]
`[ 2017-10-26 13:11:53.626] debug nonode@nohost <0.102.0>@erlkaf_logger:log_message:38 => rdkafka#consumer-2 OFFSETFETCH [thrd:main]: jabber-beanstalkd01.woow.office:9092/0: OffsetFetchResponse: events3 [11] offset -1`

This indicates that there were no committed offsets for events3, partition 11, with the same group.id.
This could either be because you changed the group.id, or the offset commit topic's retention policy has deleted the committed offsets.

**Comment by silviucpp** [comment]
hmm @edenhill the group It's never changed.. the one with offset commit topic's retention policy is what I need to check.. what I don't understand is why kafka manager shows something (always the real situation) and librdkafka something else time to time.. 

It is possible that they read offsets from zookeeper and librdkafka from kafka itself ?

**Comment by edenhill** [comment]
Possibly, I don't have any experience with kafka manager.
librdkafka will only do broker-based offset commits.
Zookeeper-based offset commits are something of the past (prior to kafka 0.9)

**Comment by silviucpp** [comment]
but do you have any idea on how I can lookup in kafka itself for the offset committed ?

**Comment by edenhill** [comment]
```
$ examples/rdkafka_consumer_example -b $BROKERS -g mygrp -O test:0 test:1 test:2 test:3
Topic "test" partition 0 offset 147499
Topic "test" partition 1 offset 93562
Topic "test" partition 2 offset 112745
Topic "test" partition 3 offset 147194
```

**Comment by edenhill** [comment]
Programmatically:
 * set the same `group.id`
 * populate the list of topic+partitions in a topic_partition_list_t
 * call `committed()`

**Comment by silviucpp** [comment]
Thanks for the info I will debug more to see what's the problem. do you have any idea what settings in kafka broker might influence the offset commit policy ?

What I changed is :

delete.topic.enable = true
replica.fetch.max.bytes=15000000
message.max.bytes=15000000
log.flush.interval.messages=10000
log.flush.interval.ms=3000

**Comment by edenhill** [comment]
`offsets.retention.minutes` et.al

**Comment by silviucpp** [comment]
:) exactly 24 hours as default.. this might be the problem as time it's a development machine and I'm opening once 1-2 days and continue development :)

I will investigate in few days and see. 

Thanks a lot

Silviu

**Comment by edenhill** [comment]
:+1:

I'm closing this issue for now, reopen if retention wasn't the problem
