### ISSUE TITLE
rd_kafka_consumer_poll() never returns if consumer has subscribed to an invalid topic

### ISSUE THREAD

**Issue by f18m** [edenhill/librdkafka#1490]
Description
===========
In my simple application I create a rdkafka consumer and then I use rd_kafka_topic_partition_list_add_range() to add topics+partitions.
I noticed that in case by mistake an invalid topic name is added to the list (together with other valid topics) and subscribed via rd_kafka_subscribe(), then the consumer object will be unable to receive messages: rd_kafka_consumer_poll() will never return even if on the valid topics new messages are generated.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.1
 - [x] Apache Kafka version: 0.10.2.1
 - [ ] librdkafka client configuration:
 - [x] Operating system: centos 7
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Do you have an example of an invalid topic name?
Enable consumer group debugging with debug=cgrp to see why you are not receiving a subscription

**Comment by f18m** [comment]
In my application I create topics with names like "typeXXX" where XXX is in range [100-200].
If I try to subscribe to topic "type201" I see this problem: it's ok that the topic is invalid: it has never been created on the broker! Also I have "auto.create.topics.enable=false" on the broker...

**Comment by edenhill** [comment]
oh, that is a valid topic, but it doesn't exist. An invalid topic would be one with invalid characters in it.
Please try debug.
