### ISSUE TITLE
Why  do this comparison "match_elem == cmp" ?

### ISSUE THREAD

**Issue by DavidLiuXh** [edenhill/librdkafka#1493]
https://github.com/edenhill/librdkafka/blob/0c2ed0a2289f926780d228698b30a71968292503/src/rdlist.c#L144

Why  do this comparison "match_elem == cmp" ?

**Comment by edenhill** [comment]
It is an optimization, if the object pointers are the same there is no need to call the comparator since it is the same object.

**Comment by rolandyoung** [comment]
But should the expression not be `match_elem == elem` ? As it is, the code appears to be comparing the pointer to one of the objects with the pointer to the comparator function.

**Comment by edenhill** [comment]
Ha, yes, you are both right, sorry! Reading too fast.
