### ISSUE TITLE
dr_msg_cb() called with same msgOpaque for Producer

### ISSUE THREAD

**Issue by ssc3** [edenhill/librdkafka#1495]
Description
===========
In rdkafka_simple_producer.c, dr_msg_cb() is called once for every message that is given to rd_kafka_produce(). When we give an int msgOpaque to rd_kafka_produce(), it should be available in dr_msg_callback() with each message's msgOpaque.

However, when multiple messages are queued without calling rd_kafka_poll() and then later, rd_kafka_poll() is called, it prints only the last msgOpaque value.

How to reproduce
================
I just modified rdkafka_simple_producer.c to the following:

****************
Callback
****************

        static void dr_msg_cb (rd_kafka_t *rk,
                       const rd_kafka_message_t *rkmessage, void *opaque) {
        **uint64_t lMsgKey = *((uint64_t*) (rkmessage->_private));**
        fprintf(stderr, "CB MsgKey=%ld\n", lMsgKey);

        /* The rkmessage is destroyed automatically by librdkafka */
}

*****************
Producer
*****************
    long msgKey = 0;

        while (run && fgets(buf, sizeof(buf), stdin)) {
                size_t len = strlen(buf);

                if (buf[len-1] == '\n') /* Remove newline */
                        buf[--len] = '\0';

                if (len == 0) {
                        /* Empty line: only serve delivery reports */
                        rd_kafka_poll(rk, 0/*non-blocking */);
                        continue;
                }

                **msgKey++;
                void* msgOpaque = (void*) &msgKey;**

               
        retry:
                if (rd_kafka_produce(
                            rkt,
                            RD_KAFKA_PARTITION_UA,
                            RD_KAFKA_MSG_F_COPY,
                            buf, len,
                            NULL, 0,
                            **msgOpaque**) == -1) {
                        /**
                         * Failed to *enqueue* message for producing.
                         */
*********************************************************
Output:
********************************************************
./rdkafka_simple_producer2 10.23.232.250 TopicObserver
% Type some text and hit enter to produce message
% Or just hit enter to only serve delivery reports
% Press Ctrl-C or Ctrl-D to exit
safsdf
% Enqueued message (6 bytes) for topic TopicObserver
fgdfg
% Enqueued message (5 bytes) for topic TopicObserver

CB MsgKey=2
CB MsgKey=2
sdfs
% Enqueued message (4 bytes) for topic TopicObserver
sdf
% Enqueued message (3 bytes) for topic TopicObserver
gggg
% Enqueued message (4 bytes) for topic TopicObserver
ssss
% Enqueued message (4 bytes) for topic TopicObserver
ewrwe
% Enqueued message (5 bytes) for topic TopicObserver
sdgsg
% Enqueued message (5 bytes) for topic TopicObserver

**CB MsgKey=8
CB MsgKey=8
CB MsgKey=8
CB MsgKey=8
CB MsgKey=8
CB MsgKey=8**     <--------------- Why is it always printing CB MsgKey as 8?

***********************************************************************

Checklist
=========
Please provide the following information:

 - [X] librdkafka version (release number or git tag): 0.11.0
 - [ ] Apache Kafka version: 
 - [X] librdkafka client configuration: Same as rdkafka_simple_producer
 - [X] Operating system: Centos 6.3
 - [ ] Using the legacy Consumer
 - [X] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You are passing a pointer to the same integer variable for all your messages, so the pointer points to the same variable, meaning they will have the same value.

**Comment by ssc3** [comment]
I see. I simply assumed we're making some copies of msgOpaque inside rd_kafka_produce()

This solves my problem. Thanks Magnus!
