### ISSUE TITLE
Is dr_msg_cb called exactly once for each successfully produced message?

### ISSUE THREAD

**Issue by shiftysymbol** [edenhill/librdkafka#1500]
Question
===========

As a producer I call `rd_kafka_conf_set_dr_msg_cb(...)` to register my callback. After a successful call to `rd_kafka_produce(...)` I start polling, awaiting the callback function to be called.

Provided that I don't close the producer, is it guaranteed that the callback function will be (eventually) called exactly once for each successful `rd_kafka_produce()`? Is there a scenario when the callback isn't called at all or it's called multiple times?

The reason I'm asking is that I'm using `msg_opaque` as a pointer to my data which I need to free up at some point. I'd like to make sure I do deallocate the memory. Also I'd like to make sure I don't try to deallocate it twice.

Checklist
=========
Please provide the following information:

 - [0.11.1] librdkafka version (release number or git tag):
 - [N/A] Apache Kafka version: 
 - [N/A] librdkafka client configuration:
 - [Linux x86_64] Operating system:
 - [no] Using the legacy Consumer
 - [no] Using the high-level KafkaConsumer
 - [N/A] Provide logs (with `debug=..` as necessary) from librdkafka
 - [N/A] Provide broker log excerpts
 - [N/A] Critical issue

**Comment by edenhill** [comment]
Yes, the dr callback will be called exactly once for per message.

**Comment by shiftysymbol** [comment]
Excellent, thanks for the confirmation!
