### ISSUE TITLE
Documentation/max value for queue.buffering.max.kbytes

### ISSUE THREAD

**Issue by jayalane** [edenhill/librdkafka#1503]
Description
===========
States default is 4000000

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_conf.c#L685

	{ _RK_GLOBAL|_RK_PRODUCER, "queue.buffering.max.kbytes", _RK_C_INT,
	  _RK(queue_buffering_max_kbytes),
	  "Maximum total message size sum allowed on the producer queue. "
	  "This property has higher priority than queue.buffering.max.messages.",
	  1, INT_MAX/1024, 4000000 },

However with a few compilers I tried (all quite old), INT_MAX is 2 ** 31, and hence the max is  2097151 (lower than the default).  

How to reproduce
================

I'm happy to fix, but not sure what you'd prefer for the max.  Maybe max(4000000, INT_MAX/1024)?Personally, I'm in a use case where I was thinking of experimenting with 40000000 but maybe that's excessive.  

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
5df87157fa8b51e4e8cfc0bfb964d6e79c1a65b6
 - [ ] Apache Kafka version: 
Not relevant.  
 - [ ] librdkafka client configuration:
Trying to set queue.buffering.max.kbytes
 - [ ] Operating system:
Linux (old RHEL).   
- [ ] Using the legacy Consumer
N/A 
- [ ] Using the high-level KafkaConsumer
N/A
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
It's a config time issue. 
 - [ ] Provide broker log excerpts
It's a config time issue.  
 - [ ] Critical issue
No.

**Comment by edenhill** [comment]
Dup #1304
