### ISSUE TITLE
Documentation for RK_MSG_FREE in C++ layer is incorrect

### ISSUE THREAD

**Issue by neromir** [edenhill/librdkafka#1506]
This line specifies that if the return value is -1, then freeing the memory associated with the call is the caller's responsibility. This is not actually correct; it appears that if any error code is returned (not just -1), then freeing the memory is the caller's responsibility.

From looking at the code, it looks like the C-side returns -1 (so this would be correct for the C API), but the C++ wrapper then translates it into one of a number of other error codes, any of which it seems, indicates that the memory still needs to be freed by the caller. It seems like ERR_NO_ERROR is the only one that indicates the memory doesn't need to be freed by the caller.

https://github.com/edenhill/librdkafka/blob/9bd283ef760c471f9276cd9251afbfce4e7f57aa/src-cpp/rdkafkacpp.h#L1986

**Comment by edenhill** [comment]
Good catch, you are absolutely right!
