### ISSUE TITLE
rd_kafka_list_groups() returns 0 even if it's not done when using ssl.

### ISSUE THREAD

**Issue by skarlsson** [edenhill/librdkafka#1508]
Description
===========
rd_kafka_list_groups() returns 0 even if it's not done when using ssl.

If you create a consumer or producer kafka using ssl and soon after trying to get group list - this succeds but returns an empty list. If not using ssl this works.

The pseudo code below provokes and fixes the error by retrying.

The problem is trhat 

How to reproduce
================
```
    char errstr[128];
    rd_kafka_resp_err_t err = RD_KAFKA_RESP_ERR_NO_ERROR;
    const struct rd_kafka_group_list *grplist = nullptr;
    int retries = timeout.count();
    /* FIXME: Wait for broker to come up. This should really be abstracted by librdkafka. */
    do {

      if (err) {
        DLOG(ERROR) << "retrying group list in 1s, ec: " << rd_kafka_err2str(err);
        std::this_thread::sleep_for(1s);
      } else if (grplist) {
        // the previous call must have succeded bu returned an empty list -
        // bug in rdkafka when using ssl - we cannot separate this from a non existent group - we must retry...
        rd_kafka_group_list_destroy(grplist);
        LOG(INFO) << "got empty group list - retrying in 1s";
        std::this_thread::sleep_for(1s);
      }
      {
        err = rd_kafka_list_groups(rk_, consumer_group.c_str(), &grplist, 5000);
      }

      DLOG_IF(INFO, err!=0) << "rd_kafka_list_groups: " << consumer_group.c_str() << ", res: " << err;
      DLOG_IF(INFO, err==0) << "rd_kafka_list_groups: " << consumer_group.c_str() << ", res: OK" << " grplist->group_cnt: "
                            << grplist->group_cnt;
    } while ((err == RD_KAFKA_RESP_ERR__TRANSPORT ||
              err == RD_KAFKA_RESP_ERR_GROUP_LOAD_IN_PROGRESS) || (err == 0 && grplist && grplist->group_cnt == 0) &&  retries-- > 0);
```

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
v0.11.1

**Comment by edenhill** [comment]
What this does in the background is query all brokers for their list of groups.

Question is: what if we haven't got a successful response from each broker by the time the timeout expires?
 1. return with error 0 and a partial grouplist?
 2. return with an error code and a partial grouplist?
 3. return with an error code and no grouplist?

I would not recommend nr 3 since this will make this API useless if any of the brokers are down, not responding in time, etc.
My vote is probably for 2 since there is no way to signal that the grouplist is indeed partial otherwise.

**Comment by skarlsson** [comment]
is not RD_KAFKA_RESP_ERR_GROUP_LOAD_IN_PROGRESS is all about (3) ?

It seems to me that it's broken when using ssl but works in plaintext. (it might just be a timing issue that makes plaintext work)

Otherwise from that a PARTIAL_GROUPLIST  error code would be ok. (2) (But still - same behaviour with or without ssl...)

I'd consider (1) a bug.

**Comment by edenhill** [comment]
Thanks, I'll make it return ERR__PARTIAL in this case.

**Comment by edenhill** [comment]
Side-note: I see the termination hang now too :+1:
