### ISSUE TITLE
Committing offsets while rebalancing crashes librdkafka

### ISSUE THREAD

**Issue by AlexeyRaga** [edenhill/librdkafka#1512]
Description
===========

`librdkafka` version: `v0.11.1`
OS: `Mac OS Sierra`

I am running a consumer and am trying to commit offsets after every message that I receive.
First several responses that I get from `rd_kafka_consumer_poll` are timeouts, probably because the consumer group has not yet finished rebalancing.
Yet, when call `rd_kafka_commit` I predictably get `NO_OFFSETS`, but then if I do `rd_kafka_consumer_poll` again the whole application crash:

```
Running consumer example...
Just KafkaLogInfo
%7|1510197060.388|MEMBERID|rdkafka#consumer-2| [thrd:app]: Group "consumer_example_group": updating member id "(not-set)" -> ""
%7|1510197060.388|BRKMAIN|rdkafka#consumer-2| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1510197060.388|WAKEUPFD|rdkafka#consumer-2| [thrd:app]: localhost:9092/bootstrap: Enabled low-latency partition queue wake-ups
%7|1510197060.388|BRKREASSIGN|rdkafka#consumer-2| [thrd:main]: Group "consumer_example_group" management reassigned from broker (none) to :0/internal
%7|1510197060.388|STATE|rdkafka#consumer-2| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1510197060.388|WAKEUPFD|rdkafka#consumer-2| [thrd:app]: localhost:9092/bootstrap: Enabled low-latency ops queue wake-ups
%7|1510197060.388|CGRPSTATE|rdkafka#consumer-2| [thrd:main]: Group "consumer_example_group" changed state init -> wait-broker (v1, join-state init)
%7|1510197060.388|BROADCAST|rdkafka#consumer-2| [thrd::0/internal]: Broadcasting state change
%7|1510197060.388|BROADCAST|rdkafka#consumer-2| [thrd:main]: Broadcasting state change
%7|1510197060.388|BRKASSIGN|rdkafka#consumer-2| [thrd:main]: Group "consumer_example_group" management assigned to broker :0/internal
%7|1510197060.388|BROKER|rdkafka#consumer-2| [thrd:app]: localhost:9092/bootstrap: Added new broker with NodeId -1
Polling for message
	Message: Left (KafkaResponseError RdKafkaRespErrTimedOut)
Committing offsets
	Offsets: KafkaResponseError RdKafkaRespErrNoOffset
Polling for message
Process exited with ExitFailure (-11): kafka-client-example
```

In this case I don't redirect events to the consumer loop and everytime I poll for messages I am actually explicitly poll for events too (with the timeout=0).

Note that if I don't call `rd_kafka_commit` everything works fine. Or if I call `rd_kafka_commit` anytime after I actually receive a message, then it works fine as well.

**Comment by edenhill** [comment]
Can you get a core file and fire up gdb, then do `bt full` ?

**Comment by AlexeyRaga** [comment]
Oh, I've just found a cause of this issue: I have a commit offsets callback, and when no offsets committed I would expect it to return me an empty `rd_kafka_topic_partition_list_t`, but it instead gives me `null`!
Perhaps I was thinking too Haskell and have forgotten that `null` exists in this universe :)
