### ISSUE TITLE
Looking for Mirrormaker automation script  is anyone help how to write a code and etc ..?

### ISSUE THREAD

**Issue by Sarahshee** [edenhill/librdkafka#1514]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by Sarahshee** [comment]
Hello, thinking to automate the the Kafka MirrorMaker from source to multiple DC's (ex:- Using with consumer/producer on Kafka cluster), Could you help me out how to automate such a think in Kafka cluster fetch the topics to Destination from Source? your help much appreciated. thanks!

**Comment by edenhill** [comment]
I don't see how this is related to librdkafka.
