### ISSUE TITLE
Is enable.idempotent=true supported?

### ISSUE THREAD

**Issue by jsa4000** [edenhill/librdkafka#1517]
Description
===========
Hello, i'm using librdkafka and I want to use newer option from kafka 0.11 for exactly once semantics.
I haven't found any information regarding this topic. Could you provide me its current state and if there is a way to use it withn this library?
 Thanks in advance

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): latest
 - [x] Apache Kafka version: v0.11
 - [x] librdkafka client configuration: enable.idempotent=true
 - [x] Operating system: windows 
 - [x] Using the legacy Consumer no
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue no

**Comment by rolandyoung** [comment]
You might want to add your vote to this issue: EOS support #1308

**Comment by jsa4000** [comment]
> You might want to add your vote to this issue: EOS support #1308

Thanks you so much and sorry for the inconveniences. The search I used it didnt't show me any results at all... By the way, I have already voted. 

Best regards
