### ISSUE TITLE
(broker based) Consumer groups 

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#152]
Support for broker based consumer groups which will be available in Apache Kafka 0.9, maybe earlier.
This removes the need for ZooKeeper on high level consumers.

**Comment by bailxaccount** [comment]
What time can be expected to support this function？

**Comment by edenhill** [comment]
The broker support for this will be available in Apache Kafka 0.9, I'm not sure what the release date for that is. Probably post summer 2015.
As soon as broker support is released librdkafka will be updated to support it.

**Comment by fsaintjacques** [comment]
Any news on this feature, this is really a key missing point.

**Comment by edenhill** [comment]
@fsaintjacques Since this relies on broker functionality that will first be available in 0.9 (~Q4) it will be released at the same time.

**Comment by edenhill** [comment]
Fixed on master

**Comment by barock19** [comment]
Is it possibleto specify the offset for `rd_kafka_subscribe` ?
