### ISSUE TITLE
Potential performance anomaly when application does other work in between producing data

### ISSUE THREAD

**Issue by akhi3030** [edenhill/librdkafka#1520]
Description
===========
I have an application scenario where a single thread is responsible for producing data over Kafka.  It sits in a loop waiting for new work.  When 1 unit of work arrives, it causes the application to produce 1 new Kafka value and then go back to polling.  What I notice is that this scenario has significantly poorer performance (lower throughput) than what the benchmarks report.  It seemed like I am spending a lot of time in rd_kafka_produce().

After some investigation, I was able to improve the performance by batching up work.  So the thread will first accumulate N units (2048 in my case) of work and then produce 2048 values.  In this scenario, I started getting good performance again.

I wonder if this performance anomaly is known and if it is, then the above is the recommended way to work around the issue.

How to reproduce
================
To help demonstrate the problem, I wrote a simple benchmark.  The code is available at: https://github.com/akhi3030/librdkafka/commit/155d6da0f18d321b7a61ba5afb3fa2169da68faa.  The benchmark is designed to sleep for a variable amount of time in between trying to produce Kafka values.  It measures the amount of time rd_kafka_produce() takes and then prints out the average.  

When I run it with no sleeping in between:
$ ./rdkafka_perf_issue 0
diff=0.483700us eagain=0
diff=0.463200us eagain=0
diff=0.510500us eagain=0
diff=0.497000us eagain=0
diff=0.443500us eagain=0
diff=0.460900us eagain=0
diff=0.444800us eagain=0
diff=0.411100us eagain=0
diff=0.437700us eagain=0

When I run it with sleep for 1ms in between:
$ ./rdkafka_perf_issue 1000
diff=3.808800us eagain=0
diff=3.627300us eagain=0
diff=3.448900us eagain=0
diff=3.534500us eagain=0
diff=3.673500us eagain=0
diff=3.542900us eagain=0
diff=3.797100us eagain=0
diff=3.477600us eagain=0
diff=3.692100us eagain=0
diff=3.609100us eagain=0

I can see a measurable performance difference when I sleep for even a slight amount of time.  Sleeping for 1ms just helps easily demonstrate the problem.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
$ git describe --tag
v0.0.63-RC1-23-gba6d5e4

 - [x] Apache Kafka version: 2.11-0.11.0.1
 - [ ] librdkafka client configuration: None
 - [x] Operating system: Linux
 - [ ] Using the legacy Consumer: No
 - [ ] Using the high-level KafkaConsumer: No
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka: None
 - [ ] Provide broker log excerpts: None
 - [ ] Critical issue: No

**Comment by edenhill** [comment]
Try setting `linger.ms` to `10`(ms) or above and see if you get improved performance.

**Comment by akhi3030** [comment]
It seems like when I am not sleeping, increasing linger time helps and when I am sleeping, it seems to hurt (or not help much).

I updated the test app to take linger and sleep as parameters (https://github.com/akhi3030/librdkafka/commit/8b36e17e2bc0be2f85587c57db440f480c35d554).  Here is what I see:

$ ./rdkafka_perf_issue 
Usage: ./rdkafka_perf_issue usleep-time linger-time

**No sleeping**

$ ./rdkafka_perf_issue 0 0
diff=0.643700us eagain=0
diff=0.507100us eagain=0
diff=0.525400us eagain=0
diff=0.726400us eagain=0
diff=0.496700us eagain=0
diff=0.532200us eagain=0
diff=0.535600us eagain=0
diff=0.522600us eagain=0
diff=0.534300us eagain=0
diff=0.544400us eagain=0

$ ./rdkafka_perf_issue 0 10
diff=0.286700us eagain=0
diff=0.054200us eagain=0
diff=0.050100us eagain=0
diff=0.067600us eagain=0
diff=0.050000us eagain=0
diff=0.050600us eagain=0
diff=0.051000us eagain=0
diff=0.043600us eagain=0
diff=0.087400us eagain=0
diff=0.064500us eagain=0

$ ./rdkafka_perf_issue 0 100
diff=0.161300us eagain=0
diff=0.037600us eagain=0
diff=0.061800us eagain=0
diff=0.052300us eagain=0
diff=0.049300us eagain=0
diff=0.035700us eagain=0
diff=0.049100us eagain=0
diff=0.048300us eagain=0
diff=0.039800us eagain=0
diff=0.040300us eagain=0

**Sleeping for some time**
$ ./rdkafka_perf_issue 100 0
diff=2.018700us eagain=0
diff=0.847000us eagain=0
diff=0.856900us eagain=0
diff=0.915500us eagain=0
diff=0.995700us eagain=0
diff=0.927700us eagain=0
diff=1.071200us eagain=0
diff=0.766200us eagain=0
diff=1.154800us eagain=0
diff=0.956100us eagain=0

$ ./rdkafka_perf_issue 100 10
diff=1.281800us eagain=0
diff=1.286100us eagain=0
diff=1.268500us eagain=0
diff=1.191100us eagain=0
diff=1.233900us eagain=0
diff=1.042300us eagain=0
diff=1.194100us eagain=0
diff=1.204900us eagain=0
diff=1.145100us eagain=0
diff=1.189900us eagain=0

$ ./rdkafka_perf_issue 100 100
diff=1.336200us eagain=0
diff=2.072800us eagain=0
diff=1.765300us eagain=0
diff=1.468500us eagain=0
diff=1.375300us eagain=0
diff=1.376100us eagain=0
diff=1.978300us eagain=0
diff=1.371500us eagain=0
diff=1.596000us eagain=0
diff=1.407300us eagain=0

**Comment by edenhill** [comment]
Latency and throughput should be improved on master now, or provide settings to improve it.
