### ISSUE TITLE
Does autocommit work with rd_kafka_queue_get_partition

### ISSUE THREAD

**Issue by kparadkar** [edenhill/librdkafka#1522]
I have few qns on usage of rd_kafka_queue_get_partition which were not clear from the test code.
1) Say I have topic with 10 partitions. If I get p_queue
    p_queue= rd_kafka_queue_get_partition(rk, topic, p0);
    rkmsg = rd_kafka_consume_queue(p_queue, 100);
 (Note that I am not forwarding queue with rd_kafka_queue_fwd(p_queue, NULL);

In this case will message from p0 also be available on regular rd_kafka_consumer_poll ?
2) If answer to 1 is 'yes' then when exactly offset get auto committed? on rd_kafka_consume_queue or rd_kafka_consumer_poll call?
3) Can I use rd_kafka_queue_get_partition method on topics with rd_kafka_assign and rd_kafka_subscribe call?

**Comment by edenhill** [comment]
1. If you don't alter the forwarding of the partition queue it will still be forwarded to the consumer queue and you will not see any messages consuming directly from the partition queue, only the consumer queue.
 2. Whenever a message is passed to the application, through any of the APIs (consume, consume_queue, consumer_poll, etc), that message's offset is stored internally for the upcoming auto (or manual) commit.
 3. Yes, queue_get..() works regardless of how partitions are being assigned.
