### ISSUE TITLE
How to commit synchronously

### ISSUE THREAD

**Issue by JoshMarler** [edenhill/librdkafka#1526]
Description
===========
Could someone confirm for me how to correctly commit offsets in a synchronous manner ?

It's a little difficult for me to show source code as I'm working on an in house C++ wrapper around the C api at my job. 

Essentially I have `enable.auto.commit == false` in my configuration and am attempting to manually commit the offset of each message I consume via `rd_kafka_consumer_poll()`.

So something along the lines of:
    `message = rd_kafka_consumer_poll(rk, 1000);
     if (message)
    {
        consume(message);
        rd_kafka_commit_message(rk, mesage, 0);
    }
`
I am able to consume a message but logging shows that every call to `rd_kafka_commit` is failing with "No offset stored". Do I need to explicitly call `rd_kafka_offset_store` or similar to make this approach work ?

I can access some logs if necessary but would like to double check my approach first. 

Many Thanks

Checklist
=========
Please provide the following information:

 - [0.11.1 ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ Ubuntu ] Operating system:
 - [ ] Using the legacy Consumer
 - [ X ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by JoshMarler** [comment]
Apologies. I had a mistake in my code. Please ignore this.

**Comment by madhukant** [comment]
That's good man.. but could you please share the code or sample code for how we can store the offset and use to manually commit the offset?

**Comment by edenhill** [comment]
@madhukant I don't have a readily available example, but in short what you do is:
 * set up a consumer with `enable.auto.offset.store=false` (but leave `enable.auto.commit=true`)
 * consume message as usual, when done processing the message you call `offsets_store()` on the message's TopicPartition (with its offset set), this will store the offset for the next automatic background commit.
 * consume the next message, goto 20
