### ISSUE TITLE
Reset partition metrics on unassign

### ISSUE THREAD

**Issue by andreycha** [edenhill/librdkafka#1528]
Hi,

I have a question regarding statistics values. Here is an excerpt (the fields are just user-friendly names for partition stats fields, e.g. `hi_offset` -> `HighestOffset`):

> Partition: 5, QueryOffset: 0, NextOffset: 15358709, AppOffset: 15358709, StoredOffset: 15358709, CommittedOffset: 15358707, EofOffset: -1001, LowestOffset: 0, HighestOffset: 15499892, Lag: 141183

> Partition: 6, QueryOffset: -1, NextOffset: -1001, AppOffset: -1001, StoredOffset: -1001, CommittedOffset: -1001, EofOffset: -1001, LowestOffset: -1001, HighestOffset: 14838222, Lag: -1

It's all clear with the partition 5: consuming is ongoing and there is some lag. But what do values for partition 6 mean? `HighestOffset` is set, that means messages exist, but does empty `AppOffset` mean that consuming from this partition has never started (and nothing has been committed)? If so, doesn't it mean that lag should be equal to highest offset? My application is the only consumer within specified group id, so all partitions are assigned to it.

Thank you.

**Comment by edenhill** [comment]
> but does empty AppOffset mean that consuming from this partition has never started

Correct, AppOffset is the offset of the latest message provided to the application.
You should probably check that fetch_state is `active` before using the lag metrics.

**Comment by andreycha** [comment]
I see, thank you. I actually use driver for .NET so I additionally check current assignment.

One more question though... Suppose that I have a topic with 8 partitions. I start a consumer, he receives valid statistics for all 8 partitions. Then I start second consumer within the same consumer group, 4 partitions are revoked from first consumer, but he continues to receive statistics for revoked partitions with 'frozen' values (as of rebalancing). I find this a bit strange. Maybe it'd make more sense to sent default values (as in example above)?

**Comment by edenhill** [comment]
All partitions are cached for a desired topic, even if they are not being consumed, so yes, the old stats will linger.
That's why you should check that the fetch state is "active" before using the the metrics for a given partition, but maybe that is tricky to do from your monitoring/graphing thing?

**Comment by andreycha** [comment]
No, that's absolutely fine, I'm able to check fetch state. Those frozen values just seem to me to be somewhere in between providing default values and always actual values. But anyway thanks for clarification!
