### ISSUE TITLE
VS2015 Compile failed

### ISSUE THREAD

**Issue by xjxia** [edenhill/librdkafka#1532]
Description
===========
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2005	___iob_func 已经在 crc32c.obj 中定义	librdkafka	D:\librdkafka\win32\rdaddr.obj	1	
错误	LNK2005	___iob_func 已经在 crc32c.obj 中定义	librdkafka	D:\librdkafka\win32\rdbuf.obj	1	
错误	LNK2005	___iob_func 已经在 crc32c.obj 中定义	librdkafka	D:\librdkafka\win32\rdcrc32.obj	1	
错误	LNK2005	___iob_func 已经在 crc32c.obj 中定义	librdkafka	D:\librdkafka\win32\rdgz.obj	1	
错误	LNK2005	___iob_func 已经在 crc32c.obj 中定义	librdkafka	D:\librdkafka\win32\rdkafka.obj	1	
错误	LNK2005	___iob_func 已经在 crc32c.obj 中定义	librdkafka	D:\librdkafka\win32\rdkafka_assignor.obj	1	
错误	LNK2005	___iob_func 已经在 crc32c.obj 中定义	librdkafka	D:\librdkafka\win32\rdkafka_broker.obj	1	
错误	LNK2005	___iob_func 已经在 crc32c.obj 中定义	librdkafka	D:\librdkafka\win32\rdkafka_cgrp.obj	1	

How to reproduce
================
vs2015 compile ，win7 OS
openssl version:Win32OpenSSL-1_0_2m

I think the reason is that VS2015 had changed the defined in corecrt_wstdio.h
_ACRTIMP_ALT FILE* __cdecl __acrt_iob_func(unsigned);  
  
#define stdin  (__acrt_iob_func(0))  
#define stdout (__acrt_iob_func(1))  
#define stderr (__acrt_iob_func(2)) 

I try to resolve this
1. with latest win32Openssl， not work
2. VS compile openssl with source code， compile failed（to solve the compilation problem wasting a lot of time，and may not work too, so i gave up）
3. disable openssl in Head file macro， not work(another error through)
4. with 2017 NuGet， not work( lost libeay32)

At present，I only want to use the producer function，and I have no time to resolve this problem
,any way to resolve this fast
（Linux works ok）

**Comment by edenhill** [comment]
Please next time translate the error message to english.

I think this is an issue with OpenSSL being compiled with msvcr120 and newer visual studios using msvcr140 (or later), this makes it impossible to statically link OpenSSL.
Solution is to remove the `\static\ suffix from the OpenSSL `<LibraryPath>`s in `win32/librdkafka.vcxproj`

**Comment by xjxia** [comment]
It looks like not work

iob func already defined in crc32c.obj
