### ISSUE TITLE
How to get partition_num

### ISSUE THREAD

**Issue by xjxia** [edenhill/librdkafka#1539]
I cann't use `rkt->rkt_partition_cnt` in my code, which compile failed with dereferencing pointer to incomplete type
Because rd_kafka_topic_t（rd_kafka_itopic_s） is defined in rdkafka_topic.h， my code only include rdkafka.h

I found after call `rkt=rd_kafka_topic_new(........)`, rkt object had filled the rkt_partition_cnt from server. So at present， I just add a new function to get rkt_partition_cntand and rebuild librdkafka

I need do this，because I want to write kafka topic random。Although call rd_kafka_produce with RD_KAFKA_PARTITION_UA support this，but its inefficient for get a parition per call（Probably？）
My application data had Primary Key(from mysql table), I can use primary key % rkt_partition_cnt to assigne a fixed partition write efficient. 
Is there any other better way? 
Thinks

**Comment by edenhill** [comment]
Implement your own partitioner_cb, the partition_cnt will be provided to you in the callback.

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1535

Here's an (real) example partitioner:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_msg.c#L516

**Comment by xjxia** [comment]
thank you very much.
