### ISSUE TITLE
After creating an instance of producer (rd_kafka_new), kafka.common.KafkaException: Wrong request type 18

### ISSUE THREAD

**Issue by wheretogetusername** [edenhill/librdkafka#1541]
Description
===========
When I use rd_kafka_new() with librdkafka to produce a producer instance, the Kafka server ends up reporting errors : kafka.common.KafkaException: Wrong request type 18

How to reproduce
================
void main()
{
        rd_kafka_t *rk;
	rd_kafka_topic_t *rkt;
	rd_kafka_conf_t *conf;
	char errstr[512];
	char buf[512];
	const char *brokers;
	const char *topic;

	brokers = "192.168.200.128:9092";
	topic = "test";

	conf = rd_kafka_conf_new();

	if (rd_kafka_conf_set(conf, "metadata.broker.list", brokers, errstr,
		sizeof(errstr)) != RD_KAFKA_CONF_OK){
		fprintf(stderr, "%s\n", errstr);
		return 1;
	}

	rd_kafka_conf_set_dr_msg_cb(conf, dr_msg_cb);

	if (rd_kafka_conf_set(conf, "log.connection.close", "false", errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK) {
		fprintf(stderr, "%% Failed to create new producer:%s\n", errstr);
		return 1;
	}
	
	rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf, errstr, sizeof(errstr));
	if (!rk){
		fprintf(stderr, "%% Failed to create new producer:%s\n", errstr);
		return 1;
	}

	rkt = rd_kafka_topic_new(rk, topic, NULL);
	if (!rkt){
		fprintf(stderr, "%% Failed to create topic object: %s\n",
			rd_kafka_err2str(rd_kafka_last_error()));
		rd_kafka_destroy(rk);
		return 1;
	}
}

Checklist
=========
apache kafka:
        version : kafka_2.11-0.8.2.2
        os : centos-7
librdkafka :
        version : 2017.11.17
        os : windows_x64

**Comment by wheretogetusername** [comment]
What can I do to solve this error?

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by wheretogetusername** [comment]
get it! thanks for the confirmation!
