### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by MrPoudel** [edenhill/librdkafka#1543]
Hello everybody,

Where is the config.h file ?
I'm getting following error while trying to compile rdkafka_example.c file:

make all 
'Building file: ../src/Kafka_inC.c'
'Invoking: Cross GCC Compiler'
arm-linux-gnueabihf-gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/Kafka_inC.d" -MT"src/Kafka_inC.o" -o "src/Kafka_inC.o" "../src/Kafka_inC.c"
'Finished building: ../src/Kafka_inC.c'
' '
'Building file: ../src/crc32c.c'
'Invoking: Cross GCC Compiler'
arm-linux-gnueabihf-gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/crc32c.d" -MT"src/crc32c.o" -o "src/crc32c.o" "../src/crc32c.c"
In file included from ../src/crc32c.c:48:0:
../src/rd.h:59:43: fatal error: ../config.h: No such file or directory
 #include "../config.h" /* mklove output */
                                           ^
compilation terminated.
make: *** [src/crc32c.o] Error 1

**Comment by edenhill** [comment]
Follow the build instructions in the README:

    ./configure
    make
    sudo make install

then link your program to the shared or static library.
