### ISSUE TITLE
rd_kafka_consume_start with unavailable offset

### ISSUE THREAD

**Issue by rapimo** [edenhill/librdkafka#1544]
Description
===========

When I want to fetch messages with `rd_kafka_consume_start` giving an offset that is (due to retention) no longer available. 
a later call with `rd_kafka_consume_batch` gives 
`message->err == RD_KAFKA_RESP_ERR__PARTITION_EOF`

I would expect that messages would automatically be consumed at the next available offset in this case.

Is that expected behaviour or is there another way to to achieve this?

**Comment by edenhill** [comment]
See the auto.offset.reset configuration policy

**Comment by rapimo** [comment]
this seems not to have any effect I don't use any offset and just want to manage the offsets myself am I missing something here?

**Comment by edenhill** [comment]
You can show me your consumer setup code, including the conf_set stuff?

**Comment by rapimo** [comment]
sure 
https://github.com/adjust/kafka_fdw/blob/master/src/connection.c#L27

but even when I hardcode the offset to `RD_KAFKA_OFFSET_BEGINNING`
here 
https://github.com/adjust/kafka_fdw/blob/master/src/kafka_fdw.c#L932

I don't get any messages.

**Comment by edenhill** [comment]
I don't see you setting `auto.offset.reset` on the topic config object in connection.c (but maybe you tried?).
Set the `debug` property to `topic,fetch` to see why the fetcher is starting where it is starting.

**Comment by rapimo** [comment]
it's here line 38 on branch offset_reset
```
    if (rd_kafka_topic_conf_set(topic_conf, "auto.offset.reset", "beginning", errstr, KAFKA_MAX_ERR_MSG) !=
        RD_KAFKA_CONF_OK)
        ereport(
          ERROR,
          (errcode(ERRCODE_FDW_ERROR),
           errmsg_internal("kafka_fdw: could not set configuration option auto.offset.reset %s", k_options.topic)));
```

I'll try to debug tomorrow

**Comment by rapimo** [comment]
Ok I made a  simplified self contained test here:

https://github.com/rapimo/kafka_debug
