### ISSUE TITLE
Consumer stops receiving messages when brokers go down

### ISSUE THREAD

**Issue by asharma339** [edenhill/librdkafka#1546]
Description
===========
We use librdkafka 0.9.5.1 in production and have been experiencing issue of consumer stops receiving messages when brokers go down, although new messages are being published successfully . We have 3 node Kafka cluster with replication factor of 3.
I thought I would try with latest release.  I still see issue though it is slightly better.

How to reproduce
================
I built my task using librdkafka version 0.11.1 on Linux . 
Here is my test setup:

- Publish every one second to a partition
- Listen to that partition

Brokers were brought up and down in following manner:

Broker-1 Down
Broker-1 Up
.....Wait for 2-3 mins or until I see messages being received......

Broker-2 Down
Broker-2 Up
.....Wait for 2-3 mins or until I see messages being received......

Broker-3 Down
Broker-3 Up
.....Wait for 2-3 mins or until I see messages being received......

Repeat above sequence 3 times. That means bringing brokers up/down 9 times.

Results:
1. Most often I see connection refused(-195) error on killing a broker. On receiving that error, it recovers in approximately 2-3 seconds. Recover here means start receiving messages.
2. Two times, all brokers down(-187) error came. Recovery in one case was 25-30 seconds but in other case it was 4-5 mins.
3. When bringing a broker UP, sometimes, it would stop receiving messages and would recover in around 2-3 mins. It happened twice.
4. Producer never has any issue during whole period and does not report any error.
3. During whole experiment, I never had to restart my task to recover. 4-5 mins was the worst case which happened only once.

Hence with latest library, we always appear to recover, which is definitely good, but we need to tune some configuration to control that 4-5 mins recovery time. Any suggestions?

I have only following params set for the consumer: 
group.id
client.id
session.timeout.ms 6000
log.connection.close false
fetch.wait.max.ms 5
fetch.error.backoff.ms 5

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.11.1
 - [ ] Apache Kafka version:  kafka_2.11-1.0.0
 - [ ] librdkafka client configuration:
 - [ ] Operating system: Linux
 - [ ] Using the legacy Consumer yes
 - [ ] Using the high-level KafkaConsumer  no
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue  yes

**Comment by edenhill** [comment]
To find out what is stalling the consumer to resume operations I suggest enabling `debug=cgrp,fetch`, it should give you an idea what is going on, or isnt.

**Comment by asharma339** [comment]
When -187 error came and consumer stopped receiving messages, I do see ONLY following in log with above debug options on consumer:

ERROR: Consumer error: 3/3 brokers are down Errorcode: -187
ERROR: Consumer error: 100.43.12.200:9092/2: Connect to ipv4#100.43.12.200:9092 failed: Connection refused Errorcode: -195
Resetting*********************************************************************
%7|1511540601.799|MEMBERID|mrplnydmrsmr02_bcpc#consumer-5| [thrd:app]: Group "mrplnydmrsmr02_bcpc": updating member id "(not-set)" -> ""
49

**Comment by asharma339** [comment]
I notice that if I ignore -187 error as I do -195, I started receiving messages around 1.5 mins. But that still begs 2 questions:
1. Why lag of 1.5 mins?
2. How would you distinguish false alarm of -187(all brokers down) with the real -187 when whole cluster goes down.

**Comment by edenhill** [comment]
You should typically ignore all errors.
Also consider using rd_kafka_err2str(errcode) to get meaningful error strings.

Did you find any clues in the debug log I asked you to gather?

**Comment by asharma339** [comment]
I didn't find any clues in the debug log. But after I cleaned, restarted and started ignoring -187(all broker down error), I noticed that recovery is between 4-5 seconds. So only pending issue is how to distinguish false -187 from real scenario of all broker down.

**Comment by edenhill** [comment]
There was a bug with regards to false positive triggering of ALL_BROKERS_DOWN which has been fixed in 0.11.3
https://github.com/edenhill/librdkafka/issues/1101
