### ISSUE TITLE
why get this error while running producer on my system

### ISSUE THREAD

**Issue by ayyappaswamy019** [edenhill/librdkafka#1548]
Description

% Type stuff and hit enter to send
1511418210.136 RDKAFKA-3-FAIL: rdkafka#producer-1: [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused
1511418210.136 RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused
1511418210.137 RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:localhost:9092/bootstrap]: 1/1 brokers are down

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The broker is not listening on that address or port.

**Comment by ayyappaswamy019** [comment]
what can i do.....

**Comment by edenhill** [comment]
Follow the Kafka quick start:
http://kafka.apache.org/documentation/#quickstart

Getting the broker environment set up is outside the scope of librdkafka open source support.

**Comment by ayyappaswamy019** [comment]
thanq so much i got it....
