### ISSUE TITLE
librdkafka producer main thread send messages to background threads issue when brokers  down 

### ISSUE THREAD

**Issue by lzc123456** [edenhill/librdkafka#1549]
Description
===========
Hi, I have a question, thank for you time.

currently, I study librdkafka example of rdkafka_example.c, in example, Producer main thread send messages to  background threads with internal producer queue, and one producer queue means one broker partition(e.g. I have six partitions, means have six producer queues).
the partitions of broker already exist(means producer queue already exist) even if  the broker is down, so producer main thread still can send messages to the producer queue with broker down's, but background threads cannot send the messages to kafka cluster(cannot get messages from producer queue when broker is down), finally, the messages cannot send to kafka cluster.

so, this is an issue? if not ,how can I do that, thank you again.

How to reproduce
================
step 1, start producer without assign partition option.
step 2, start consumer
step 3, producer input messages and send to kafka cluster, and consumer can received all messages successful.
step 4, take out the network cable for one of broker in kafka cluster, and now the broker goes down,  then input messages again and again, consumer sometimes cannot received messages, some message feeling lost.
step 5, connect up the network cable for the broker down's, consumer can received the previous messages when broker recover up.

Checklist
=========
Please provide the following information:

 - [librdkafka-0.11.1] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [centos] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I'm not really sure what you are asking, if the broker is down the message can't be delivered but will remain in the internal queue for up to `message.timeout.ms` - if a leader broker comes back within that time a new produce attempt will be performed automatically.

`queue.buffering.max.messages` limits the maximum number of messages to queue.
To control the batch size you would need to use `batch.num.messages`.

**Comment by lzc123456** [comment]
thank you for your reply timely.

I've found out the reason and fixed it based you reminder, it's my kafka cluster replicas value incorrect cased.

thank you so much.

**Comment by AlexeyRaga** [comment]
@edenhill just out of interest, you say that

>  if the broker is down the message can't be delivered but will remain in the internal queue for up to `message.timeout.ms` - if a leader broker comes back within that time a new produce attempt will be performed automatically

What happens if the broker stays down longer than `message.timeout.ms`? I assume that messages do not just disappear from the queue silently?

**Comment by edenhill** [comment]
When messages time out it will trigger delivery reports for them with error code set to _MSG_TIMED_OUT.

**Comment by AlexeyRaga** [comment]
And what happens if I don't subscribe do delivery reports? Will the job fail or will the message be dropped?

**Comment by edenhill** [comment]
Then messages will be dropped.
Not sure what a "job" is

**Comment by AlexeyRaga** [comment]
Sorry, I refer to an executable program as a "job" here.

**Comment by edenhill** [comment]
Okay, the delivery report is the mechanism used to notify the application of message transmission success/failure.
There are very few applications where it is warranted to not using a delivery report since there willbe  no indication whatsoever of success or failure, fire and forget.
