### ISSUE TITLE
rdkafka_consumer_example receives many ERR__TIMED_OUT messages until "real" messages arrive

### ISSUE THREAD

**Issue by cantappa** [edenhill/librdkafka#1552]
Description
===========
I have the following problem: When I start the rdkafka_consumer_example with the only option being
"-b localhost:9092" and a topic which contains some (~10 messages) new messages about every second call (yes, this does not happen everytime) the consumer always receives messages with ERR__TIMED_OUT error after the call of consume(1000) for a time period of about 10-20 seconds.
If this situation is not happening, I receive the messages immediately.
I appended the output I get when providing the option "-d all".
What am I'm doing wrong? I need the consumer to immediately receive the new messages.

How to reproduce
================
Call ./rdkafka_consumer_example -b <broker> topic where topic should be an existent topic that contains several new messages (one suffices).

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.1
 - [x] Apache Kafka version: kafka_2.11-0.11.0.1
 - [x] librdkafka client configuration: default
 - [x] Operating system: Ubuntu 17.10
 - [x] Using the legacy Consumer: no
 - [x] Using the high-level KafkaConsumer: yes
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

[kafka.log](https://github.com/edenhill/librdkafka/files/1499887/kafka.log)

**Comment by edenhill** [comment]
That's the rebalancing timeout you are seeing, which is bound by `session.timeout.ms`.

> 1511456163.959 RDKAFKA-7-RECV: rdkafka#consumer-1: [thrd:devpc:9092/0]: devpc:9092/0: Received JoinGroupResponse (v0, 179 bytes, CorrId 3, rtt 14580.79ms)

^ it takes 14s to join the group (see rtt)

**Comment by edenhill** [comment]
`-X session.timeout.ms=6000` will speed up this process, but make sure to use the same session.timeout.ms on all consumers of the group

**Comment by vaspas** [comment]
We have the same behaviour in the C# client. 
Our test does with steps:
- create consumer
- subscribe
- calling consume message until first one will received
- commit
- unsubscribe
- dispose consumer

In the first attempt message are received about 5 sec after creating consumer. In the second attempt only after 20-30sec. 
But it is looked strange because dispose is called in the first attempt.

**Comment by cantappa** [comment]
Thank you for your answer! This was a solution to my problem :-).
