### ISSUE TITLE
Receive failed: SSL syscall error number: 5: Success

### ISSUE THREAD

**Issue by peodor** [edenhill/librdkafka#1554]
Description
===========
When enabled SSL I got each minute, OnError event (Confluent C# client): Receive failed: SSL syscall error number: 5: Success

(and then immediate after through debug/security logging: Broker SSL certificate verified)

Any clue what causing and how to interpret the OnError message (Number 5? And the text "Success"?)?

It seems as receiving and publish messages works.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.11.1
 - [ ] Apache Kafka version: 0.10.2
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer YES
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please fill out the checklist
