### ISSUE TITLE
fatal error: 'openssl/ssl.h' file not found when I do make command

### ISSUE THREAD

**Issue by pontiyaraja** [edenhill/librdkafka#1556]
Description
===========
Getting below error when I do make command

`gcc -MD -MP -gstrict-dwarf -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -DLIBRDKAFKA_GIT_VERSION="\"v0.11.1-66-g8754f1\""  -c rdkafka.c -o rdkafka.o
In file included from rdkafka.c:38:
./rdkafka_int.h:53:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make[1]: *** [rdkafka.o] Error 1
make: *** [libs] Error 2`

How to reproduce
================

1. git clone https://github.com/edenhill/librdkafka.git (master branch)
2. ./configure
3. make

you can get the error

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.1
 - [x] Apache Kafka version:  0.10.2
 - [ ] librdkafka client configuration: 
 - [ ] Operating system: MAC OS
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka: Yes
 - [ ] Provide broker log excerpts
 - [ ] Critical issue: yes

**Comment by edenhill** [comment]
Try installing openssl from homebrew

Den 27 nov. 2017 09:42 skrev "Pandiyaraja Ramamoorthy" <
notifications@github.com>:

**Comment by pontiyaraja** [comment]
Thank you @edenhill its working fine now
