### ISSUE TITLE
Build error with  Microsoft Visual Studio 2013

### ISSUE THREAD

**Issue by MrPoudel** [edenhill/librdkafka#1557]
Description
===========
I'm using Microsoft Visual Studio 2013 on windows 10 machine to compile the librdkafka library. I already installed zlib from NuGet. In addition, I  installed the OpenSSL-win32 and provided the path correctly.
for include:C:\OpenSSL-Win32\include
for linker: C:\OpenSSL-Win32\lib

I'm getting following errors while compiling with MSVS 2013.

Error 16 error LNK1104: File "librdkafkacpp.lib" can not be opened. C: \ Users \ Poudel \ Desktop \ librdkafka-master \ librdkafka-master \ win32 \ rdkafka_example \ LINK rdkafka_example
Error 15 error LNK1104: File "librdkafka.lib" can not be opened. C: \ Users \ Poudel \ Desktop \ librdkafka-master \ librdkafka-master \ win32 \ librdkafkacpp \ LINK librdkafkacpp
Error 9 error C2275: 'u32': Invalid use of this type as expression c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1358 1 librdkafka
Error 1 error C2275: 'size_t': Invalid use of this type as expression c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1205 1 librdkafka
Error 10 error C2146: Syntax error: Missing ';' before identifier 'to_add' c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1358 1 librdkafka
Error 2 error C2146: Syntax error: Missing ';' before identifier 'n' c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1205 1 librdkafka
Error 6 error C2143: Syntax error: ';' is missing before 'const' c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1209 1 librdkafka
Error 11 error C2065: 'to_add': undeclared identifier c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1358 1 librdkafka
Error 12 error C2065: 'to_add': undeclared identifier c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1359 1 librdkafka
Error 13 error C2065: 'to_add': undeclared identifier c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1360 1 librdkafka
Error 14 error C2065: 'to_add': undeclared identifier c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1361 1 librdkafka
Error 3 error C2065: 'n': undeclared identifier c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1205 1 librdkafka
Error 4 error C2065: 'n': undeclared identifier c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1206 1 librdkafka
Error 5 error C2065: 'n': undeclared identifier c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1207 1 librdkafka
Error 7 error C2065: 'c': undeclared identifier c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1211 1 librdkafka
Error 8 error C2065: 'c': undeclared identifier c: \ users \ poudel \ desktop \ librdkafka-master \ librdkafka-master \ src \ snappy.c 1212 1 librdkafka

How can I solve this problem? Any help would be appreciated. Thanks! @edenhill

**Comment by edenhill** [comment]
VS 2013 is not supported, I suggest one of:
 * upgrade to VS 2015 or 17
 * use the librdkafka.redist binary NuGet package of librdkafka
 * fix the compilation errors

**Comment by MrPoudel** [comment]
@edenhill Thanks a lot for your prompt response. I will definitely try with MSVS 2017. But, README.win32 file contains the info "Native win32 build instructions using **Microsoft Visual Studio 2013** (MSVC)". This is little bit misleading, I suggest you to upgrade it to MSVC 2015 or 2017. 
In addition, I have two questions. I'm sorry the questions are little bit deviated from the core librdkafka issues. Anyway, I would be happy if you could provide me some hints.

1. I already tried a lot to integrate the Kafka producer on my existing Eclipse project on windows, but there was no luck. I could not succeed. It it possible to compile the librdkafka on Eclipse on Windows platform?
2.  Why don't you provide single-file distribution like librdkafka.h/.c header and source file, so that it would be quite simple to integrate on any projects?

**Comment by edenhill** [comment]
1. I've never used Eclipse so can't help you there.
 2. That's the first time in 4 years that minification has come up, so I can't say the demand is huge  :)
