### ISSUE TITLE
is there a switch to stop the broker bootstrap(only connect the brokers i config)?

### ISSUE THREAD

**Issue by apeipo** [edenhill/librdkafka#1561]
Description
===========
Our kafka cluster has about 200 brokers, but my service only need connect three brokers to produce.
When i config the three brokers as set `metadata.broker.list` ,  the client will connect all of the 200 brokers(rdkafka query each one for Metadata information which contains the full list of brokers). this cause two problems:
 1. A single client will start 200 threads, as i start 10 produce client, my service has 2000 threads.
 2. the event_cb report `RdKafka::Event::EVENT_ERROR` about every 5 minutes, the event message is " xxx.com Receive failed: Disconnected"(the xxx.com is not in the 3 brokers that i config ). i doubt this is because i didn't use them for a long time.

so i want to know is there a switch to set the client **only** connect the brokers  list that i config? or some other way to solved the two problems above(especially the first).

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.1
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Unfortunately not, there is an issue to track a sparse connections feature but it has not yet been implemented: #825

We reduced the number of Metadata requests about a year ago, so I suggest upgrading to librdkafka 0.11.1 to reap the benefits of that, at least.
