### ISSUE TITLE
How to detect the availability of kafka brokers?

### ISSUE THREAD

**Issue by lxyscls** [edenhill/librdkafka#1563]
Description
===========

I have a producer, and will switch to some other sources when the kafka brokers are unavaliable. So what is the right thing to detect the availability of kafka brokers? use rd_kafka_metadata(...), or to check the errocode of produce?

Appreciate your reply.

How to reproduce
================

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [ ] librdkafka version (release number or git tag): irrelevant
 - [ ] Apache Kafka version: irrelevant
 - [ ] librdkafka client configuration: irrelevant
 - [ ] Operating system: irrelevant
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I suggest a combination of the _ALL_BROKERS_DOWN error code (register an error_cb) to get notified when all connections are down, and then using metadata() periodically to find out when the cluster is available again.

re #418
