### ISSUE TITLE
Spikes in RTT of a consumer

### ISSUE THREAD

**Issue by mohoch1** [edenhill/librdkafka#1565]
Hi.

Description
===========
We were experiencing spikes of latency in our data, and for the investigation we started logging the RTT latency of the fetch requests.

While the  RTT was usually around 16ms, every once in a while we see a spike in the latency, reaching 200-300ms.
These spikes occur about 4-6 times a minute,

Example logs:
Received FetchResponse (v2, 222 bytes, CorrId 346718, rtt 218.00ms)
Received FetchResponse (v2, 1151 bytes, CorrId 351973, rtt204.00ms)
Received FetchResponse (v2, 132 bytes, CorrId 343598, rtt 219.00ms)
Received FetchResponse (v2, 3035 bytes, CorrId 357882, rtt203.00ms)
Received FetchResponse (v2, 330 bytes, CorrId 363216, rtt 219.00ms)
Received FetchResponse (v2, 150 bytes, CorrId 354929, rtt 218.00ms)
Received FetchResponse (v2, 186 bytes, CorrId 368655, rtt 110.00ms)
Received FetchResponse (v2, 565 bytes, CorrId 369064, rtt 203.00ms)
Received HeartbeatResponse (v0, 2 bytes, CorrId 369065, rtt 109.00ms)
Received FetchResponse (v2, 276 bytes, CorrId 373925, rtt 219.00ms)
Received FetchResponse (v2, 78 bytes, CorrId 364894, rtt 219.00ms)
Received FetchResponse (v2, 240 bytes, CorrId 379077, rtt 219.00ms)

How to reproduce
================
1. Create a consumer to a specific topic
2. Doesn't matter if you write anything to this topic - it happens anyway
3. Set the `debug` config to `protocol`
4. Track the `FetchResponse` log messages, and the `rtt` value in them

**Client configuration:**
{"socket.blocking.max.ms":100,
"socket.nagle.disable":true,
"fetch.wait.max.ms":5,
"fetch.min.bytes":100,
"fetch.error.backoff.ms":50,
"deug":"protocol"}

We changed this config over and over, but the problem stayed the same.

Is there anything I'm missing? any configuration?

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): ` v0.11.1`
 - [x] Apache Kafka version: `0.10.0`
 - [x] librdkafka client configuration: `e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..`
 - [x] Operating system: `Brokers - Centos 5 (x64). Client - Windows 7`
 - [x] Provide logs 
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Does the latency drop proportionally if you reduce socket.blocking.max.ms?
