### ISSUE TITLE
Several consumptions of all messages in a topic in a row cause assertion failure in rd_kafka_cgrp_op_serve

### ISSUE THREAD

**Issue by cantappa** [edenhill/librdkafka#1567]
Description
===========
I'm having the following problem with consumers.
In my project I create a consumer with the configuration as provided below.
I have a method `ConsumeAll` which causes the consumer (high level KafkaConsumer) to consume all messages from my topic (about 7000 messages). The consumption is via the consume function of the KafkaConsumer.

When I run the ConsumeAll once or twice everything works as expected. (I receive all messages and can access the stored messages afterwards.)
But when I run it a third time (directly in a row) I get the output attached to this post. (I only attached the log output after the start of the last call of ConsumeAll.)

The log tells me that an assertion in function rd_kafka_cgrp_op_serve of rdkafka_cgrp.c failed.
The code snippet of this assertion (or the surrounding case block) is:

case RD_KAFKA_OP_FETCH_STOP|RD_KAFKA_OP_REPLY:
                /* Reply from toppar FETCH_STOP */
                rd_kafka_assert(rkcg->rkcg_rk,
                                rkcg->rkcg_wait_unassign_cnt > 0);
                rkcg->rkcg_wait_unassign_cnt--;
                rd_kafka_assert(rkcg->rkcg_rk, rktp->rktp_assigned); // this assertion failed

Unfortunately, I cannot really interpret what's happening there and what the problem war or what I am doing wrong. Could anybody help me out here?

How to reproduce
================
See description.

Checklist
=========

 - [x] librdkafka version (release number or git tag): `0.11.1`
 - [x] Apache Kafka version: ` 0.11.0.1`
 - [x] librdkafka client configuration: 
`auto.offset.reset = 'earliest'
group.id = 0
metadata.broker.list = 5 brokers in local network
session.timeout.ms = 6000
debug=all
security.protocol=sasl_ssl
ssl.ca.location=/etc/ssl/certs
sasl.mechanisms=PLAIN
sasl.username=<myuser>
sasl.password=<mypassword>
api.version.request=true
`
 - [x] Operating system: `Ubuntu 17.10 (x64)`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: see attached file
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

[kafka.txt](https://github.com/edenhill/librdkafka/files/1514573/kafka.txt)

**Comment by edenhill** [comment]
Can you show me your code?

**Comment by cantappa** [comment]
Unfortunately, I can't cause it's not my private project.
But my consumer works as the consumer in the rdkafka_consumer_example.cpp.

**Comment by edenhill** [comment]
Okay, then can you outline what your ConsumeAll() function does and if you are doing any other steps inbetween calls to ConsumeAll()?

**Comment by cantappa** [comment]
I took your rdkafka_consumer_example.cpp and adapted it to have a similar behavior as my consumer. 
With that I could reproduce the behavior. In the third run of the for loop the program crashes with an output as in my first post.

[rdkafka_consumer_example.txt](https://github.com/edenhill/librdkafka/files/1517869/rdkafka_consumer_example.txt)

**Comment by edenhill** [comment]
When you use subscribe() you must only call assign() from within a rebalance_cb/EVENT_REBALANCE, but here you are first calling subscribe() to directly after call assign() which does not make much sense.
Remove the subscribe() call.

**Comment by cantappa** [comment]
Ok, but when I do so, only the first consumer receives all messages, the following ones don't receive any message. Even though I set auto.offset.reset='earliest'. Why is that?

**Comment by edenhill** [comment]
Probably because you are using the same group.id for the consumers, so the will start off where the previous instance left off and committed its final offsets.

**Comment by cantappa** [comment]
Yes, that makes sense. But can I somehow avoid this without using different consumer groups? I tried to always reset the offset to 0 using the instructions you gave here [1]. But the problem there is that the rebalance_cb function is only called after the first consumer finished. And therefore the remaining consumers do not start at offset 0.

[1] https://github.com/edenhill/librdkafka/wiki/Manually-setting-the-consumer-start-offset

**Comment by edenhill** [comment]
The rebalance callback will be called once for each consumer and rebalance.
You could set enable.auto.commit=false.

**Comment by cantappa** [comment]
The problem I still have in this context is that I am not able to let the same consumer receive all messages (from beginning) of a topic twice or more in a row.
I did set enable.auto.commit=false, and I set the offset of the partitions in rebalance_cb to 0, I assigned new topic handles to the consumer before its new ConsumeAllMessages call while setting the offset to 0 and assigning these handles to the consumer. But it always ends in only the first call of ConsumeAllMessages actually receiving messages. What am I doing wrong? Or ain't one consumer supposed to consume all messages of a topic several times?

**Comment by edenhill** [comment]
Offset 0 is not necessarily the oldest message, if topic retention is at play the oldest message may very well be a moving target >= 0.
If you specify offset 0 and it doesn't exist then auto.offset.reset will kick.
To really use the oldest offset use the RD_KAFKA_OFFSET_BEGINNING constant.
