### ISSUE TITLE
creation of kakfa consumer doesnt throw an error even the broker mentioned doesn't exist

### ISSUE THREAD

**Issue by vikneshwaran1994** [edenhill/librdkafka#1568]
Description
===========
Hello edenhill, I am a student, I started using librdkafka and I am completely new to this. I just created a kafka consumer, when I was using a broker which exists, the consumer is working properly. 
But the problem is even if I am giving some random broker name, consumer is being created.

The details of the configuration that I used is given below.
 RdKafka::Conf *conf=RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
 
I set the broker as well as the group.  
conf->set("metadata.broker.list", "randomname", errstr) ; 
conf->set("group.id", "test", errstr);
RdKafka::KafkaConsumer * consumer_1= RdKafka::KafkaConsumer::create(conf,errstr); 
if(!consumer_1)
{
   return false;
} 
return true;

this code is written in a function and it always returns true, even if I am giving some random broker name.

But it is writing the following error message to the console when I give some broker that doesn't exist.

%3|1512070500.731|FAIL|rdkafka#consumer-1| [thrd:randomname:9092/bootstrap]: randomname:9092/bootstrap: Failed to resolve 'randomname:9092': Name or service not known                                                                         
%3|1512070500.731|ERROR|rdkafka#consumer-1| [thrd:randomname:9092/bootstrap]: randomname:9092/bootstrap: Failed to resolve 'randomname:9092': Name or service not known                                                                         
%3|1512070500.731|ERROR|rdkafka#consumer-1| [thrd:randomname:9092/bootstrap]: 1/1 brokers are down                                                              
%3|1512070500.732|FAIL|rdkafka#consumer-2| [thrd:randomname:9092/bootstrap]: randomname:9092/bootstrap: Failed to resolve 'randomname:9092': Name or service not known                                                                         
%3|1512070500.732|ERROR|rdkafka#consumer-2| [thrd:randomname:9092/bootstrap]: randomname:9092/bootstrap: Failed to resolve 'randomname:9092': Name or service not known      

And when I am giving ("") an empty string as broker name, it not throwing any errors to the console.

what it assumes when we give an empty string, and how it is creating a consumer even when I am giving some invalid broker name. I am completely new to kafka, trying to learn it. can someone help.

And I am using the latest library. I just download it from your repository yesterday.

Thank you,
Vicky.

**Comment by edenhill** [comment]
It is not considered an error to:
 * provide no bootstrap.brokers
 * provide an empty list of bootstrap.brokers

For some use cases the brokers are not known at client creation but added later through rd_kafka_brokers_add() API.
