### ISSUE TITLE
Crashed when using msg_opaque

### ISSUE THREAD

**Issue by CoderOverflow** [edenhill/librdkafka#1570]
Description
===========

![image](https://user-images.githubusercontent.com/29338660/33424154-e16bb7be-d5f5-11e7-9295-11a750668dd4.png)

[https://github.com/edenhill/librdkafka/issues/1302](url)

The bug seems still there.. it likes a ghost in my program.
After running for a while, for example 10000 times, the parameter of opaque will be lost in some case.

no matter I used the stack-allocated or heap-allocated msg_opaque to pruduce(), It crashed.
I also check the pmsg_opaque point before calling pruduce() to prevent the null point.

Can you check this issue again?

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag):  v0.11.1
 - [x] Operating system: window10 64

**Comment by edenhill** [comment]
Please share your code that calls produce()

**Comment by CoderOverflow** [comment]
`if (producer)
								{
									USES_CONVERSION;
									path1 = W2A(strFilePath);
									CB_KAFKA_TYPE * pmsg_opaque = new CB_KAFKA_TYPE;
									memset(pmsg_opaque->szPathFrom, '\0', 251);
									memset(pmsg_opaque->szPathTo, '\0', 251);
									pmsg_opaque->nFlag = 0;
									strncpy(pmsg_opaque->szPathTo, path1.c_str(), strnlen_s(path1.c_str(), 251));
                                  
									if (pmsg_opaque == nullptr)
									{
										...
										
									}
									else
									{
									err = producer->produce(g_myProducer.TopicName,
										RdKafka::Topic::PARTITION_UA,
										RdKafka::Producer::RK_MSG_COPY,
										(void *)payload.c_str(),
										payload.size(),
										NULL,
										0,
										0,
										(void *)&pmsg_opaque);
									

									err = producer->flush(g_myProducer.MessageTimeoutMax);
									
									}
								}
								else
								{
									...
								}`

the above code is at work-thread of socket. when socket receives the data, it will be transferred to kafka cluster by calling produce() after some extra process.

**Comment by edenhill** [comment]
You are passing a pointer pointer (CB_KAFKA_TYPE **) to the stack variable (CB_KAFKA_TYPE *) that holds a pointer.

Use `(void *)pmsg_opaque` instead.
