### ISSUE TITLE
Does Kafka support topic level group.id?

### ISSUE THREAD

**Issue by lxyscls** [edenhill/librdkafka#1573]
Description
===========

My consumers want to share the data of one topic, so they use the same group.id. And the meanwhile, they also want to read every single messages of another topic, so they use unique group.id.

Does Kafka support topic level group.id? 

If it doesn't, can I use two consumers with two confs in one thread? Is it thread safe?

How to reproduce
================

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [ ] librdkafka version (release number or git tag): `master`
 - [ ] Apache Kafka version: `0.11.0.1`
 - [ ] librdkafka client configuration: irrelevant
 - [ ] Operating system: irrelevant
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You can use multiple consumers, they don't share any state, so it will be safe.

But, nothing is really stopping you from assigning an extra set of topic+partitions in your rebalance_cb on ASSIGNED_PARTITIONS: in other words, append your shared topic+partitions to the assigned partitions.

**Comment by lxyscls** [comment]
@edenhill Do you mean that i can add all partitions to the topic, which every single message needs to be consumed by every consumer? This solution is very ellegant, if it does work well.

**Comment by edenhill** [comment]
Yes, just make sure that you don't commit to partitions that weren't assigned to your consumer.

**Comment by lxyscls** [comment]
Can i use "enable.auto.commit" under this situation? @edenhill

**Comment by edenhill** [comment]
Basically no, since that would cause multiple consumers to commit for the same partition.
But there is a trick you might be able to use:
 * disable `enable.auto.offset.store`
 * store offsets manually for each received message using `rd_kafka_offset_store()` for the partitions that only your consumer is using, i.e., the partitions that were passed to you on ASSIGN_PARTITIONS in the rebalance_cb.

**Comment by lxyscls** [comment]
@edenhill emmm... If every consumer maintains their topic+partitions' offsets on their own, who will commit the offset? When one consumer restarts from crashed, it will start consume from the "end". But this "end" is far before than other consumers. Am i right? I don't want to store those offsets in somewhere else.

 I am not very familiar, and thank for your patience.

**Comment by edenhill** [comment]
There can (reliably and obviously) only be one consumer per group.id that commits offsets for a topic+partition, otherwise multiple consumers would just overwrite eachother's offsets.

If you want multiple consumers to consume a topic at their own discretion and managing their own offsets then you need to put them into separate consumer groups.

**Comment by lxyscls** [comment]
@edenhill So the simple solution is as below?

- add all the consumers into one consumer group, who can share the message.

- add all the other consumers into separate consumer groups, who need every single message of the topic

- poll those consumers in one thread, there is noneed for sync.

**Comment by edenhill** [comment]
Seems reasonable, yes. Make sure to disable auto commits for the first group (shared).

**Comment by lxyscls** [comment]
@edenhill Thank you very much. I have one more question about the consumer's timeout precision. I give 1ms, so it can return in 1ms **in time** if there is no data? Or I can give RD_POLL_NOWAIT, it can return immediately with no data. As you know, if there are two consumers, one's wait time has impact on the other one's throughput.
```
while (run) {
    RdKafka::Message *msg = consumer->consume(1);
    if (!use_ccb) {
      msg_consume(msg, NULL);
    }
    delete msg;
  }
```

**Comment by edenhill** [comment]
Yes, that's upper bound timeout if no messages were available.
