### ISSUE TITLE
Is there a way to enable Consumer API(KafkaConsumer Interface) to start w/ a specified offset on a given topic

### ISSUE THREAD

**Issue by leezhenghui** [edenhill/librdkafka#1574]
Description
===========
This  question is regarding `KafkaConsumer Interface` (NOT the `Simple Consumer Legacy API`).  We are working on a Instant Message system refactoring work, as one of requirement, we want to replace our current kafka driver to librdkafka. We need a feature for starting a consumer instance with a specified offset for a given topic, I can see this ever being supported by the `Simple Consumer Legacy API`, but not get a luck in `KafkaConsumer Interface`, Do I miss anything here, or any suggestion on the solution is appreciated. 

How to reproduce
================
A question indeed, see description above please.
 
**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x ] librdkafka version (release number or git tag): `e.g., v0.11.x`
 - [ ] Apache Kafka version: `e.g., 0.10.2.3`
 - [ ] librdkafka client configuration: `e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..`
 - [ ] Operating system: `e.g., Centos 5 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ArenPeace** [comment]
try to set "auto.offset.reset"

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#how-do-i-manually-set-the-start-offset-to-consume
