### ISSUE TITLE
How to compile a static library correctly

### ISSUE THREAD

**Issue by wheretogetusername** [edenhill/librdkafka#1577]
Description
===========
Fisrt I downloaded librdkafka, then ./configure --prefix=/usr/local/librdkafka , make , make install.
 ps : configure info : 
using cache file config.cache
checking for OS or distribution... ok (Linux)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok (cached)
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok (cached)
checking executable ld... ok (cached)
checking executable nm... ok (cached)
checking executable objdump... ok (cached)
checking executable strip... ok (cached)
checking for pkgconfig (by command)... ok (cached)
checking for install (by command)... ok (cached)
checking for PIC (by compile)... ok (cached)
checking for GNU-compatible linker options... ok (cached)
checking for GNU linker-script ld flag... ok (cached)
checking for __atomic_32 (by compile)... ok (cached)
checking for __atomic_64 (by compile)... ok (cached)
checking for socket (by compile)... ok (cached)
parsing version '0x000b01ff'... ok (0.11.1)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok (cached)
checking for zlib (by pkg-config)... ok
checking for zlib (by compile)... ok (cached)
checking for libcrypto (by pkg-config)... ok
checking for libcrypto (by compile)... ok (cached)
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for libssl (by pkg-config)... ok
checking for libssl (by compile)... ok (cached)
checking for libsasl2 (by pkg-config)... ok
checking for libsasl2 (by compile)... ok (cached)
checking for crc32chw (by compile)... ok (cached)
checking for regex (by compile)... ok (cached)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok (cached)
checking for strndup (by compile)... ok (cached)
checking for strerror_r (by compile)... ok (cached)
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok (cached)
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok (cached)
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           y
  ENABLE_SSL               y
  ENABLE_SASL              y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               Linux
  SOLIB_EXT                .so
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.11.1
  MKL_APP_VERSION          0.11.1
  LIBS                     -lpthread -lz   -lcrypto   -lssl -lcrypto   -lsasl2   -lrt -ldl
  CFLAGS                          
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
Generated config.cache

After installing , i get librdkafa.a and rdkafka.h from /usr/local/librdkafka/lib and /usr/local/librdkafka/include

Then I wrote makefile to generate programs.The g++ sentence roughly is "g++ -I$(IncludeDir) -o $@ -Wl,--start-group $(ObjFile) -L$(LibDir) -lrdkafka -lssl -lcrypto -ldl -lsasl2 -lz -lrt -lpthread -Wl,--end-group " .  ( ps : Librdkafa、Libssl and Libcrypto are all static libraries )
when linking, it reports link error "librdkafka.a(rdkafka_transport.o): undefined reference to symbol 'SSL_library_init@@libssl.so.10'".

Do I compile the correct static library ? or Am I right to use static library ?

How to reproduce
================

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [ v0.11.0] librdkafka version (release number or git tag): `e.g., v0.10.5`
 - [ ] Apache Kafka version: `e.g., 0.10.2.3`
 - [ ] librdkafka client configuration: `e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..`
 - [Cnetos7(x64) ] Operating system: `e.g., Centos 5 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Are you building librdkafka and your application on the same machine?

**Comment by wheretogetusername** [comment]
Of course, on the same machine. The prefix of configuration summary should be "prefix /usr/local/librdkafka".
In order for my program to be compiled into a static library without relying on the version of the dynamic library, I replaced the (Libssl.so、Libcrypto.so) with (libssl.a、libcrypto.a) when the link was linked. But it reports error "librdkafka.a(rdkafka_transport.o): undefined reference to symbol 'SSL_library_init@@libssl.so.10'". Why does the mistake seem to have to rely on libssl.so ?

**Comment by wheretogetusername** [comment]
@edenhill
