### ISSUE TITLE
System.DllNotFoundException: Failed to load the librdkafka native library

### ISSUE THREAD

**Issue by merlin-king** [edenhill/librdkafka#1578]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

System.DllNotFoundException: Failed to load the librdkafka native library

Description
===========
An error occurred using the Dotnet core Web API
Errors are as follows

Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL9RN5T1D654", Request id "0HL9RN5T1D654:00000001": An unhandled exception was thrown by the application.
System.DllNotFoundException: Failed to load the librdkafka native library.
   at Confluent.Kafka.Impl.LibRdKafka.Initialize(String userSpecifiedPath)
   at Confluent.Kafka.Producer..ctor(IEnumerable`1 config, Boolean manualPoll, Boolean disableDeliveryReports)
   at Confluent.Kafka.Producer`2..ctor(IEnumerable`1 config, ISerializer`1 keySerializer, ISerializer`1 valueSerializer, Boolean manualPoll, Boolean disableDeliveryReports)

How to reproduce
================
Use Asp.net Core WebApi  on Centos7

**Comment by rolandyoung** [comment]
From this line
> Confluent.Kafka.Impl.LibRdKafka.Initialize(String userSpecifiedPath)
it appears that the Confluent Kafka .Net framework is trying to load librdkafka.dll from "userSpecifiedPath" instead of from an actual location in your filesystem.

You need to check the instructions for building apps using that framework. This is not a problem with librdkafka itself.

**Comment by edenhill** [comment]
This is a .NET client issue.
Might be related to this:
https://github.com/confluentinc/confluent-kafka-dotnet/issues/390

**Comment by ratri-git** [comment]
https://github.com/confluentinc/confluent-kafka-dotnet/issues/778#issuecomment-560225446
