### ISSUE TITLE
Authentication Failure, need a reason code, rather than reason string

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#1581]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ - done.

Description
===========
For the producer, when authentication fails, the error_cb is called with err = RD_KAFKA_RESP_ERR__AUTHENTICATION and a reason in the form of a string with the description in it is returned.

For example:

producerErrorCb (rk=0x7f8ae0026560, err=RD_KAFKA_RESP_ERR__AUTHENTICATION, 
    reason=0x7f89ec002d20 "sasl_plaintext://vm.xyz.com:9092/bootstrap: SASL authentication failure: Disconnected: check client PLAIN credentials and broker logs", opaque=0x7f8ae0007528)

Authentication also fails when one out of three of the brokers is down. We have tested this.

Depending on the reason for authentication failure, we would like to be able to recover from it gracefully. For example:

1. If the authentication failed because of one or all brokers being down, then the producer needs to keep trying for a certain period of time and then give up.
2. If authentication failed because the username/password is invalid, then the producer needs to refresh its username/password
3.... any other reason?

The problem is that today, the reason is returned to the error callback in the form of a string, not a code. So, we need to parse the error string (which may not be error free) and also not durable.

Is there any plan for providing a reason code, and not a reason string?

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): RDKAFKA_VERSION_STR "0.11.1"
 - [ ] Apache Kafka version: kafka-1.0.0
 - [ ] librdkafka client configuration: `queue.buffering.max.ms = 50 ms, ack = all, security.protocol = SASL_PLAINTEXT, sasl.mechanisms = PLAIN, `
 - [ ] Operating system: Red Hat Enterprise Linux Server release 7.2 (Maipo)
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka - can provide if requried
 - [ ] Provide broker log excerpts - possibly not required
 - [ ] Critical issue - N

**Comment by edenhill** [comment]
> Authentication also fails when one out of three of the brokers is down. We have tested this.

Are you really getting ERR__AUTHENTICATION when a broker is down? You should be seeing ERR__TRANSPORT then

**Comment by edenhill** [comment]
As for the case where all brokers reject your credentials you could use the _ALL_BROKERS_DOWN event.

As for invalid username/password, there is no such granularity in the broker's error code, for security reasons, so there is not much the client can do.
