### ISSUE TITLE
delete topic cause consumer stuck

### ISSUE THREAD

**Issue by qdore** [edenhill/librdkafka#1582]
Description
===========
set enable.auto.offset.store=false but leave enable.auto.commit=true - the offset store() locally "stores" the offset to commit

 when I delete the topic and reproduce message to this topic, the consumer stuck

PS: v0.11.0

**Comment by edenhill** [comment]
What is your `auto.offset.reset` configuration?
Are new messages being produced to the new topic for the consumer to consume?
