### ISSUE TITLE
librdkafka.redist.targets in the v0.11.3 nuget package has invalid path

### ISSUE THREAD

**Issue by noahdav** [edenhill/librdkafka#1583]
Description
===========
When building on MSBuild we use the librdkafka.redist.targets in our project files.  However the librdkafka.lib is being referenced as $(MSBuildThisFileDirectory)..\..\runtimes\win7-x64\native\librdkafka.lib but the path should be $(MSBuildThisFileDirectory)..\..\build\native\lib\win7\x64\win7-x64-Release\v120\librdkafka.lib

How to reproduce
================
Try to include the v0.11.3 nuget package and include the librdkafka.redist.targets file to link against librdkafka.lib.  The path is not valid and will not be able to link using this targets file.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (v0.11.3):
 - [ ] Apache Kafka version: `e.g., 0.10.2.3`
 - [ ] librdkafka client configuration: `e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..`
 - [ ] Operating system: `e.g., Centos 5 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Ouch, that's a regression introduced when trying to get librdkafka.redist to work properly across .NET frameworks and platforms. We'll look into it, thanks.
