### ISSUE TITLE
Does librdkafka support offsetForTimes in group comsumer?

### ISSUE THREAD

**Issue by hangcun** [edenhill/librdkafka#1586]
Description
===========
I want to start a consumer group with specified timestamp(**T**) and then the consumer group will consume msg with CreateTime after **T**, could librdkafka do this and how?

**Comment by edenhill** [comment]
Yes, register a rebalance callback and look up the absolute offset of a timestamp with offsets_for_times(), update the assigned partitions list, and then call assign().

https://github.com/edenhill/librdkafka/wiki/Manually-setting-the-consumer-start-offset
