### ISSUE TITLE
RddKafka queue full error!

### ISSUE THREAD

**Issue by soheil08** [edenhill/librdkafka#1588]
I use `CppKafka` that used `RddKafka` for producing messages to Kafka. I wrote a code that gets data through `UDP` port and produces it to Kafka cluster. It read a pre-specified index of messages for knowing which topic it should be sent and create it with 24 partitions if not exist. Using getting data from one and two sensors each sending 100 sample per second, totally 7KB for every second, I successfully can produce data on topics. But trying to get data from 3 sensors the code run without any error but data is not storing in Kafka. It creates proper topics in Kafka but when I want to consume data Kafka errors:
` WARN [console-consumer-40979_kafka1-1512724369032-b455                         5058-leader-finder-thread], Failed to add leader for partitions [7792,9],[7792,2                         3],[7792,17],[7792,11],[7792,1],[7792,15],[7792,18],[7792,20],[7792,2],[7792,7],                         [7792,8],[7792,21],[7792,12],[7792,13],[7792,14],[7792,3],[7792,6],[7792,4],[779                         2,10],[7792,22],[7792,0],[7792,5],[7792,19],[7792,16]; will retry (kafka.consume                         r.ConsumerFetcherManager$LeaderFinderThread)
kafka.common.NotLeaderForPartitionException`

and once after a while producing data, it errors `queue full`!
checking the Kafka logs it includes:
` Completed load of log 7798-2 with log end offset 0 (kafka.log.Log)
[2017-12-07 12:23:22,468] INFO Created log for partition [7798,2] in /var/log/kafka with properties {compression.type -> producer, message.format.version -> 0.10.0-IV1$
[2017-12-07 12:23:22,468] INFO Partition [7798,2] on broker 1: No checkpointed highwatermark is found for partition [7798,2] (kafka.cluster.Partition)
[2017-12-07 12:23:22,485] INFO Completed load of log 7798-23 with log end offset 0 (kafka.log.Log)`

I use the default `RddKafka` producer settings and my cluster includes 3 nodes. 

 - [ ] librdkafka version : `latest`
 - [ ] Apache Kafka version: ` 0.10.0.0`
 - [ ] librdkafka client configuration: `default`
 - [ ] Operating system: `ubuntu server 16.04`

**Comment by edenhill** [comment]
Sounds like there are no leaders for the given partitions.
Use a metadata listing tool (such as `rdkafka_example -b BROKERS -L` or `kafkacat -b .. -L` or 'kafka-topics --describe ..`) to see what is going on

**Comment by soheil08** [comment]
Thanks for replying!

Issuing command: `kafka-topics.sh --describe --zookeeper zookeeper1:2181 --describe --topic 7792`

it results in 
` PartitionCount:24       ReplicationFactor:2     Configs: `
        Topic: 7792     Partition: 0    Leader: 3       Replicas: 3,1   Isr: 3,1
        Topic: 7792     Partition: 1    Leader: 1       Replicas: 1,2   Isr: 1,2
        Topic: 7792     Partition: 2    Leader: 2       Replicas: 2,3   Isr: 2
        Topic: 7792     Partition: 3    Leader: 3       Replicas: 3,2   Isr: 3,2
        Topic: 7792     Partition: 4    Leader: 1       Replicas: 1,3   Isr: 1
        Topic: 7792     Partition: 5    Leader: 2       Replicas: 2,1   Isr: 2,1
        Topic: 7792     Partition: 6    Leader: 3       Replicas: 3,1   Isr: 3,1
        Topic: 7792     Partition: 7    Leader: 1       Replicas: 1,2   Isr: 1,2
        Topic: 7792     Partition: 8    Leader: 2       Replicas: 2,3   Isr: 2
        Topic: 7792     Partition: 9    Leader: 3       Replicas: 3,2   Isr: 3,2
        Topic: 7792     Partition: 10   Leader: 1       Replicas: 1,3   Isr: 1
        Topic: 7792     Partition: 11   Leader: 2       Replicas: 2,1   Isr: 2,1
        Topic: 7792     Partition: 12   Leader: 3       Replicas: 3,1   Isr: 3,1
        Topic: 7792     Partition: 13   Leader: 1       Replicas: 1,2   Isr: 1,2
        Topic: 7792     Partition: 14   Leader: 2       Replicas: 2,3   Isr: 2
        Topic: 7792     Partition: 15   Leader: 3       Replicas: 3,2   Isr: 3,2
        Topic: 7792     Partition: 16   Leader: 1       Replicas: 1,3   Isr: 1
        Topic: 7792     Partition: 17   Leader: 2       Replicas: 2,1   Isr: 2,1
        Topic: 7792     Partition: 18   Leader: 3       Replicas: 3,1   Isr: 3,1
        Topic: 7792     Partition: 19   Leader: 1       Replicas: 1,2   Isr: 1,2
        Topic: 7792     Partition: 20   Leader: 2       Replicas: 2,3   Isr: 2
        Topic: 7792     Partition: 21   Leader: 3       Replicas: 3,2   Isr: 3,2
        Topic: 7792     Partition: 22   Leader: 1       Replicas: 1,3   Isr: 1
        Topic: 7792     Partition: 23   Leader: 2       Replicas: 2,1   Isr: 2,1



and issuing command: `kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list kafka1:9092 --topic 7792 --time -1`

It results in 
7792:23:0
7792:8:0
7792:17:0
7792:11:74553
7792:20:0
7792:2:0
7792:5:0
7792:14:0
7792:13:0
7792:4:0
7792:22:0
7792:16:0
7792:7:0
7792:1:0
7792:10:0
7792:19:0
7792:9:
7792:18:
7792:21:
7792:12:
7792:3:
7792:15:
7792:6:
7792:0:

**Comment by edenhill** [comment]
Run the producer with the `debug` config property set to `metadata,topic,msg` and look for error indication

**Comment by soheil08** [comment]
I run the producer using command `./connector -b kafka1:9092,kafka2:9092,kafka3:9092`

How can I run it in debug mode?

**Comment by edenhill** [comment]
You will need to check CppKafka's API docs to see how to set the `debug` configuration property.

**Comment by soheil08** [comment]
After deleting all zookeeper and Kafka data(logs) and restarting it works correctly. Running on debug mode as you said, it logs:

`%7|1512808095.283|MSGSET|rdkafka#producer-1| [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: 7792 [8]: MessageSet with 1 message(s) delivered
%7|1512808095.283|MSGSET|rdkafka#producer-1| [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: 7794 [8]: MessageSet with 1 message(s) delivered
%7|1512808095.288|PRODUCE|rdkafka#producer-1| [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: 7798 [8]: Produce MessageSet with 1 message(s) (104 bytes, ApiVersion 2, MsgVersion 1)
%7|1512808095.289|MSGSET|rdkafka#producer-1| [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: 7798 [8]: MessageSet with 1 message(s) delivered
`

and it seems all things are correct! Can you justify why it works after cleaning and restarting?
What this part of logs means? `%7|1512808095.288`
I guess `288` is offset number but what means `%7` and `1512808095`?

**Comment by edenhill** [comment]
If things works after resetting your cluster it means there was a problem with the cluster, not the client.

The default  log format is %loglevel (7=debug,see syslog) following by an epoch timestamp with two digit precision
