### ISSUE TITLE
How can I set serializer in rddKafka

### ISSUE THREAD

**Issue by soheil08** [edenhill/librdkafka#1589]
Hi, I searched the `CONFIGURATION.md` file for finding serializer setting but I found nothing! What serializer RddKafka use? 
In addition, some other configurations like `buffer.memory` are not found!

 - [ ] librdkafka version (release number or git tag): `latest`
 - [ ] Apache Kafka version: `0.10.0.0`

**Comment by edenhill** [comment]
Serializers are not supported in librdkafka, simply because they don't add any value in C.
I suggest wrapping the produce and consume calls with your own serializer/deserializers.

**Comment by soheil08** [comment]
So in what format data are written in Kafka brokers? Are they serialized?

**Comment by edenhill** [comment]
Kafka does not care about the format, that is up to your application to decide.
