### ISSUE TITLE
RD_KAFKA_PARTITION_UA_BATCH

### ISSUE THREAD

**Issue by eugpermar** [edenhill/librdkafka#159]
Produce in batch to a random partition is currently expensive, because we have to call the random partitioner for each message in.

We could assign the whole batch to a random partition. This way, we don't have to call so many times the random partitioner, and we keep have randomness in some way.

In classic produce(), I think that this should mean the same as RD_KAFKA_PARTITION_UA. Just for protection.

**Comment by edenhill** [comment]
The partitioner is a per-message thing (since it typically operates on the message key).
Can't you just assign the parittion prior to produce_batch() instead?
