### ISSUE TITLE
What happened if a message not was delivered successfully?

### ISSUE THREAD

**Issue by soheil08** [edenhill/librdkafka#1590]
Description
===========
As `RdKafka` sent messages assynchrinouly, by default what happens if a message was not delivered?
Is it retry again according to `retries` config and if all retries were unsuccessful what happened?

 - [x] librdkafka version (release number or git tag): `latest`
 - [x] Apache Kafka version: `e.g., 0.10.0.0`
 - [x] librdkafka client configuration: `e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..`
 - [x] Operating system: `Ubuntu-server 16.04)`

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-reliability

**Comment by steuke-fm** [comment]
Hi Magnus @edenhill ,

sorry for re-opening this issue, but can you elaborate on what "Produce errors signaled by the broker" refers to and/or give some more details which errors are retried and which will fail immediately? E.g. we were expecting that librdkafka would retry when the number of ISR are below the min.isr-setting, but in fact it fails immediately. (We are using the confluent .NET library).

Best,
Stefan

**Comment by edenhill** [comment]
There are currently some problems around the producer retry logic, but we've fixed and formalized how this is all handled on the `retry_fixes` branch (which will be merged to master and included in the next release when proper testing and verification has been performed).
One part of this work was to document how different errors are handled, which you can see here:
https://github.com/edenhill/librdkafka/blob/retry_fixes/INTRODUCTION.md#producer-message-delivery-failure

Insufficient ISRs is one of the errors that was previously incorrectly handled but now is retried.
