### ISSUE TITLE
huge memory cost when create producer

### ISSUE THREAD

**Issue by apeipo** [edenhill/librdkafka#1591]
Description
===========
for some reasons, i need to create producers more than one in my program, but i got a strange problem.
on a few machines, when i  init 10 producers(use the method below), it cost about **3G memorys**. but on some other machine, it only cost about **70M**. 
is anyone has a similar problem?

hear are some informations:
1. the os, kernel version are the same, both CentOS 6.7 & kernel2.6, 
2. i compile my test program and librdkafka(0.11.3) in gcc4.9.4 ,  the glibc one these machines are the same,  ulimit -a show the same too.
3. the test program  compile options `-std=c++11  -Wl,-E -lz -lpthread -ldl -lm -lrt -lcrypto -lssl -lsasl2 -g -O0`
4. our kafka cluster has about 200 brokers(i use 3 of them actually, but as the doc say, rdkafka will connect all of them)
5. i use valgrind to start my program, but it doesn't seems to be helpful, hear is the summary on different machine. 

```
//the machine that cost 3G memory
==00:00:00:11.740 16753== HEAP SUMMARY:
==00:00:00:11.740 16753==     in use at exit: 2,830,694 bytes in 23,634 blocks
==00:00:00:11.740 16753==   total heap usage: 39,024 allocs, 15,390 frees, 9,649,893 bytes allocated
==00:00:01:52.020 16753== LEAK SUMMARY:
==00:00:01:52.020 16753==    definitely lost: 681,690 bytes in 7,777 blocks
==00:00:01:52.020 16753==    indirectly lost: 66,159 bytes in 2,603 blocks
==00:00:01:52.020 16753==      possibly lost: 108,681 bytes in 332 blocks
==00:00:01:52.020 16753==    still reachable: 1,974,164 bytes in 12,922 blocks
==00:00:01:52.020 16753==         suppressed: 0 bytes in 0 blocks
ERROR SUMMARY: 12 errors from 12 contexts (suppressed: 29 from 9)
```

```
//the machine that cost normal
==00:00:00:11.396 19459== HEAP SUMMARY:
==00:00:00:11.396 19459==     in use at exit: 2,493,793 bytes in 20,211 blocks
==00:00:00:11.396 19459==   total heap usage: 33,249 allocs, 13,039 frees, 8,004,400 bytes allocated

==00:00:01:29.648 19459== LEAK SUMMARY:
==00:00:01:29.648 19459==    definitely lost: 531,827 bytes in 6,068 blocks
==00:00:01:29.648 19459==    indirectly lost: 51,934 bytes in 2,034 blocks
==00:00:01:29.648 19459==      possibly lost: 108,480 bytes in 330 blocks
==00:00:01:29.648 19459==    still reachable: 1,801,552 bytes in 11,779 blocks
==00:00:01:29.648 19459==         suppressed: 0 bytes in 0 blocks
ERROR SUMMARY: 13 errors from 13 contexts (suppressed: 0 from 0)
```

How to reproduce
================
the method i use to init producers:

```
int init_kafka(int produce_num, std::string topic_str, std::string brokers) {
    RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
    RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);
    string errstr;
    conf->set("event_cb", &event_cb, errstr);
    conf->set("metadata.broker.list", brokers, errstr);
    conf->set("dr_cb", &dr_cb, errstr);
    conf->set("batch.num.messages",     std::to_string(1000), errstr);
    conf->set("queue.buffering.max.ms", std::to_string(5),    errstr);
    //conf->set("queue.buffering.max.messages", std::to_string(m_queue_max_len), errstr);

    for(int i = 0; i < produce_num; i++){
        RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);
        if (!producer) {
            std::cerr <<"create producer, i:" << i  << "|fail:" << errstr.c_str() << std::endl;
            return 0;
        }
        std::cerr << "Created producer:" << producer->name().c_str() << std::endl;
        RdKafka::Topic *topic = RdKafka::Topic::create(producer, topic_str,
                                                       tconf, errstr);
        if (!topic) {
            std::cerr <<  "Failed to create topic:" << errstr.c_str() << std::endl ;
            return 0;
        }
       //do some store things 
    }
}
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.3`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: ` "batch.num.messages":1000
   "queue.buffering.max.ms":5`
 - [x] Operating system: `CentOS 6.7  2.6.32-573.18.1.el6.toa.x86_64`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by apeipo** [comment]
ok, i will try  valgrind again and post the report later.
by the way,  how can i `Make sure you close and terminate the producers properly`, i just kill -9 of my program  or just sleep a while and quit.   does librdkafka cache some file?
 @edenhill

**Comment by edenhill** [comment]
Looks like you are not shutting down the client properly, see docs here:
https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence

**Comment by apeipo** [comment]
thanks for reply.
😢😢 may be i didn't shut down properly before.  but what i can do to solved the problem now?  the point is that, whenever i run my program with 10 producers, it cost near 3G memories at run time but on some other machine it only cost 70M.

**Comment by edenhill** [comment]
What is the difference the different invocations?
Are the producers that allocate memory handling more messages, or bigger messages?
Do they have worse connectivity to the broker?

You can enable the stats callback to get some internal metrics for librdkafka and compare these between the huge memory instances and the normal ones.

Also, can you show us your code that calls produce() and the corresponding delivery report?

Thanks

**Comment by apeipo** [comment]
my test program just create producer and  **it doesn't produce any message**, the huge memory is alloc just after the producer thread created done. so i think may be nothing to with the message i produce?

the config i use to create producer is the same (the code is in the issue content above).  
for now i guess it  may  be cause by some system call or system env variable used in the producer create logic..

i will try the  stats callback and  check some system config to see what i can find.
Thanks

**Comment by edenhill** [comment]
I recommend that you reuse the same Producer instance, there is really not much value in creating more instances and it will just consume system memory resources.

Since it will create one thread per broker, using the system's default thread stack size, it might be that the default thread stack size differs between the machine that takes 70M and the one that takes 3G
