### ISSUE TITLE
GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found

### ISSUE THREAD

**Issue by kchandan** [edenhill/librdkafka#1593]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Not able to connect,publish messages using confluent kafka APIs which uses librdkafka. 

How to reproduce
================
Installed 
librdkafka-devel-0.11.1-1.el7.x86_64
librdkafka-0.11.1-1.el7.x86_64

Python Pip:
confluent_kafka

Python Code:
```

        avroProducer = AvroProducer({
         'schema.registry.url': 'http://kafka-server:8081','sasl.kerberos.principal': 'sa_kafka@EXAMPLE',
         'sasl.kerberos.keytab': '/tmp/kafka.keytab',
         'sasl.kerberos.service.name': 'kafka',
         'security.protocol': 'SASL_PLAINTEXT',
         'sasl.kerberos.kinit.cmd':'kinit -kt /tmp/kafka.keytab kafka@EXAMPLE'
         ,'bootstrap.servers':'kafka-servers:9096'},
         default_value_schema=value_schema,default_key_schema=None)
```
When I run my code with above code, I get following error
```
%3|1513198484.333|FAIL|rdkafka#consumer-2| [thrd:kafka-server:9096/bootstrap]: kafka-server:9096/bootstrap: Receive failed: Disconnected
%3|1513198484.333|ERROR|rdkafka#consumer-2| [thrd:kafka-server:9096/bootstrap]: kafka-server:9096/bootstrap: Receive failed: Disconnected
%3|1513198484.333|ERROR|rdkafka#consumer-2| [thrd:kafka-server:9096/bootstrap]: 1/1 brokers are down
kinit: Cannot find KDC for realm "EXAMPLE" while getting initial credentials
%3|1513198484.356|SASLREFRESH|rdkafka#producer-1| [thrd:sasl_plaintext://kafka-server:9096/bootstrap]: sasl_plaintext://kafka-server:9096/bootstrap: SASL key r
efresh failed: kinit -kt /tmp/kafka.keytab kafka@EXAMPLE: exited with code 1
%2|1513198484.363|LIBSASL|rdkafka#producer-1| [thrd:sasl_plaintext://kafka-server:9096/bootstrap]: sasl_plaintext://kafka-server:9096/bootstrap: GSSAPI Error:
Unspecified GSS failure.  Minor code may provide more information (Matching credential not found (filename: /tmp/krb5cc_1000))
%3|1513198484.363|FAIL|rdkafka#producer-1| [thrd:sasl_plaintext://kafka-server:9096/bootstrap]: sasl_plaintext://kafka-server:9096/bootstrap: Failed to initial
ize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching
 credential not found (filename: /tmp/krb5cc_1000))
```

However, when I copy paste the same kinit command, it works. Also, I tried to play with configuration options mentioned in other issues on this project. Also tried different kinit command [with/without service option], all works from command prompt but somehow from the lib it throws error.

kinit -S "kafka/kafka-server" -k -t "/tmp/kafka.keytab" sa_kafka@EXAMPLE

Did a test run using kafkacat, it works pretty well. Looks like some configuration issue.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `librdkafka-0.11.1-1.el7.x86_64`
 - [X ] Apache Kafka version: `0.10.1`
 - [X ] librdkafka client configuration: ` avroProducer = AvroProducer({
         'schema.registry.url': 'http://kafka-server:8081','sasl.kerberos.principal': 'sa_kafka@EXAMPLE',
         'sasl.kerberos.keytab': '/tmp/kafka.keytab',
         'sasl.kerberos.service.name': 'kafka',
         'security.protocol': 'SASL_PLAINTEXT',
         'sasl.kerberos.kinit.cmd':'kinit -kt /tmp/kafka.keytab sa_kafka@EXAMPLE'
         ,'bootstrap.servers':'kafka-servers:9096'},
         default_value_schema=value_schema,default_key_schema=None)`
 - [X ] Operating system: `CentOS Linux release 7.4.1708 (Core)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
So you are saying the same config worked from kafkacat but not the Python client?
That is weird, there should be no differences given they are using the same librdkafka library, unless there are some environment variables affecting GSSAPI/ktinit which are not set in one of those invocations.

**Comment by edenhill** [comment]
Any update on this?
