### ISSUE TITLE
Whether this rd_kafka_anyconf_get0  function will not return the correct value if dest = NULL ?

### ISSUE THREAD

**Issue by DavidLiuXh** [edenhill/librdkafka#1594]
https://github.com/edenhill/librdkafka/blob/35f28e241240c12c213041b76910e008dbee12ab/src/rdkafka_conf.c#L1895

Whether this rd_kafka_anyconf_get0  function will not return the correct value if dest = NULL ?

**Comment by edenhill** [comment]
since flags2str() has already written the string to dest this code sets dest to NULL to avoid overwriting it down at line 1924
