### ISSUE TITLE
stuck in uninit

### ISSUE THREAD

**Issue by mr-wing** [edenhill/librdkafka#1596]
Description
Loopped init->produce->uninit using rdkafka, the process maybe stuck in uninit, the reason is as follows:

when uninit is called, rdmain (rd_kafka_thread_main) will remove the leader of partition by calling rd_kafka_toppar_broker_leave_for_remove. This function will send a task to the leader, But it prior choice nextleader in partition struct. When the broker receive and process this task, the broker(nextleader) is not the leader in partition struct. So removing process is break, the broker_refcnt do not minus one. Rdmain and main is waiting for the stop of the broker.

In rd_kafka_toppar_broker_leave_for_remove
```
       if (rktp->rktp_next_leader)
                 dest_rkb = rktp->rktp_next_leader;
         else if (rktp->rktp_leader)
                 dest_rkb = rktp->rktp_leader;
         else {
                 rd_kafka_dbg(rktp->rktp_rkt->rkt_rk, TOPIC, "TOPPARDEL",
                              "%.*s [%"PRId32"] %p not handled by any broker: "
                              "not sending LEAVE for remove",
                              RD_KAFKAP_STR_PR(rktp->rktp_rkt->rkt_topic),
                              rktp->rktp_partition, rktp);
                 return;
         }
```

In rd_kafka_broker_op_serve

```
             if (unlikely(rktp->rktp_leader != rkb)) {
                        rd_rkb_dbg(rkb, BROKER | RD_KAFKA_DBG_TOPIC, "TOPBRK",
                                   "Topic %s [%"PRId32"]: "
                                   "ignoring PARTITION_LEAVE: "
                                   "broker is not leader (%s)",
                                   rktp->rktp_rkt->rkt_topic->str,
                                   rktp->rktp_partition,
                                   rktp->rktp_leader ?
                                   rd_kafka_broker_name(rktp->rktp_leader) :
                                   "none");
                        rd_kafka_toppar_unlock(rktp);
                        break;
                }    
```

Why the leader is not the nextleader in partition struct, the reason is as follows:
When the process is starting rdmain will parse the metadata and update broker info and topic info. Both of two processes is async .Updating topic info, rdmain will join the broker in partition leader by calling rd_kafka_toppar_broker_migrate. When updating broker is not over, rdmain will join internalbroker in partition leader. After updating broker success, therd_kafka_toppar_broker_migrate is called again. When the two join(therd_kafka_toppar_broker_migrate) is overlap together(nextleader is not null), therd_kafka_toppar_broker_migrate will make nextleader equal new leader, decrease refcnt in internalbroker and increase refcnt in new leader without any lock. In this time the nextleader is not leader in partition struct.

In rd_kafka_toppar_broker_migrate

```
        int had_next_leader = rktp->rktp_next_leader ? 1 : 0;  

        /* Update next leader */
        if (new_rkb)
                rd_kafka_broker_keep(new_rkb);
        if (rktp->rktp_next_leader)
                rd_kafka_broker_destroy(rktp->rktp_next_leader);
        rktp->rktp_next_leader = new_rkb;

        /* If next_leader is set it means there is already an async
         * migration op going on and we should not send a new one
         * but simply change the next_leader (which we did above). */
        if (had_next_leader)
                return; 
```

When it happened, the thread of internalbroker is not running in rd_kafka_broker_thread_main yet. What's worse is that the uninit is called. So the thread of internalbroker is over without in process loop. One can imagine the leader and nextleader never equal.

There are three question need to be resolved
1. Whether the judgment that nextleader and rkb is equal in rd_kafka_broker_op_serve can be removed?
2. Whether the process of judgment nextleader is null and change nextleader in rd_kafka_toppar_broker_migrate will lock?
3. After updating broker, join new leader is not running on rdmain, but remove leader is running on rdmian. Are there any conflicts between these two processes?

**Comment by mr-wing** [comment]
This modification can increase the probability of problem recurrence
In rd_kafka_broker_thread_main
```
static int rd_kafka_broker_thread_main (void *arg) {
        rd_kafka_broker_t *rkb = arg; 
        rd_kafka_t *rk = rkb->rkb_rk;
if (rkb->rkb_source == RD_KAFKA_INTERNAL) {
        sleep(5);
}
```

**Comment by edenhill** [comment]
Wow, that is an impressive analysis of the problem!

**Comment by edenhill** [comment]
This should now be fixed on master, can you try to verify the fix on your end?

**Comment by mr-wing** [comment]
ok  thanks for your fix
