### ISSUE TITLE
What's the relationship among background thread, broker, consumer, producer, and topic?

### ISSUE THREAD

**Issue by lxyscls** [edenhill/librdkafka#1598]
Description
===========
My application plays as consumer and producer both, and there are half of a hundred topics.
I need to confine the total number of threads, because system resource is limited.
So I am curious about the relationship among background thread, broker, consumer, producer and topic.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-internal-threads
