### ISSUE TITLE
Way to reduce threads used by librdkafka?

### ISSUE THREAD

**Issue by hrjaco** [edenhill/librdkafka#1600]
My process has 4 Kafka consumer instances(they are to the same topic, but they might be consuming different offsets). Our kafka cluster has 17 kafka brokers. I notice that there are 126 background kafka threads...

So it looks like for each kafka consumer instance, we have 2 * N threads(where N is the number of kafka brokers). Is this correct? Is there way to reduce this? Is there way to share kafka background threads to the same the brokers? (right now I have 8 background thread per kafka broker, and 8 sockets)

**Comment by edenhill** [comment]
Best case you should be able to reduce the number of threads to 1+NUM_BROKERS:
https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-internal-threads

**Comment by hrjaco** [comment]
Thanks for the link! Is it possible to close the bootstrap broker connections afterwards?

It does not mention about sharing connections among multiple RdKafka::KafkaConsumer instances(to the same brokers). Is this possible?

**Comment by edenhill** [comment]
If you specify the bootstrap server names identical to how they are reported from the cluster (e.g., `kafkacat -b brokers.. -L`) then it will reuse the bootstrap connection/threads for the real brokers.

It is not possible to share sockets or threads between client instances.

**Comment by masenov9607** [comment]
> Best case you should be able to reduce the number of threads to 1+NUM_BROKERS: https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-internal-threads

In the implementation of **rd_kafka_new**
it is created additional internal broker thread which is not connected to any broker and serves for handling
ops which are not related to the brokers thread. So there are 2 + NUM_BROKERS not 1 + NUM_BROKERS . 

```
      rd_kafka_broker_add(rk, RD_KAFKA_INTERNAL, RD_KAFKA_PROTO_PLAINTEXT,
                                "", 0, RD_KAFKA_NODEID_UA);
```

is it possible that amount to be reduced to 1 + NUM_BROKERS?
