### ISSUE TITLE
Cannot link when built with cmake and no sasl

### ISSUE THREAD

**Issue by krojew** [edenhill/librdkafka#1601]
Description
===========
When trying to build using cmake with -DWITH_SASL=OFF, the build succeeds but linking to the resulting lib fails:

librdkafka.so: undefined reference to `rd_kafka_sasl_scram_provider'

How to reproduce
================
Build with cmake:

cmake -DWITH_SASL=OFF -DBUILD_SHARED_LIBS=ON -DRDKAFKA_BUILD_TESTS=OFF -DRDKAFKA_BUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Release .
make -j8

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.3`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `Ubuntu 17.10`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I don't think our CMakefiles support specifying WITH_.. options on the command line like that.
PRs are welcome though.

**Comment by krojew** [comment]
Can you elaborate? CMakeLists.txt contains `option(WITH_SASL "With SASL" ${with_sasl_default})`, so -DWITH_SASL=OFF is the normal way to set such option.

**Comment by edenhill** [comment]
The CMake stuff is community contributed and not officially supported, I'm not well versed in that space.
I'm suspecting there's an error with the logic around WITH_SASL (and its siblings).
The reference is the mklove logic in `configure.librdkafka`, i.e., what to turn on/off when.

**Comment by krojew** [comment]
Ah, ok. It might be a good idea to make a note somewhere that cmake support is experimental at the moment.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/blob/master/packaging/cmake/README.md

But it is not in an obvious location, will fix.
