### ISSUE TITLE
Cross compile issue with misuse preprocessor

### ISSUE THREAD

**Issue by polarG** [edenhill/librdkafka#1603]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>
Location:
rdatomic.h

Problems:
In the file 'config.h', the macro 'HAVE_ATOMICS_64' and 'HAVE_ATOMICS_64' are always defined. 
So 'defined(HAVE_ATOMICS_64)' and 'defined(HAVE_ATOMICS_32)' always return true. 

Solution: replace 'defined(HAVE_ATOMICS_xx)' with 'HAVE_ATOMICS_xx' in this file.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>
Cross compile the lib with '#define HAVE_ATOMICS_64 0' and  '#define HAVE_ATOMICS_32 0' in the 'config.h'.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<cc0d7af39b09be5ff1188ba83176f68d52589666>`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This was fixed in https://github.com/edenhill/librdkafka/pull/1592
