### ISSUE TITLE
Consumer stops consuming if commit occurs during broker rebalancing

### ISSUE THREAD

**Issue by krishanfrog** [edenhill/librdkafka#1605]
Description
===========
When the brokers are getting rebalanced, the consumer process throws an `Broker: Not coordinator for group` error and gets stuck and stops consuming.

How to reproduce
================
1. Setup a cluster of 2 brokers (Replication factor is 2).
2. Keep 1 broker up and 2nd broker down
3. Publish messages to a partition whose preferred leader is the 2nd broker which is down. (request.required.acks is 1)
4. Start a consumer. ("session.timeout.ms": 15000, "enable.auto.commit": false}. I am using synchronous commits 
5. Bring the 2nd broker up
6. Once rebalance is done, I immediately get an error `Broker: Not coordinator for group` and the consumer process gets stuck and doesn't get any further messages although requests are going to the broker

Broker logs during the error -

ERROR [ReplicaFetcherThread-0-3]: Error for partition [<topic>,<partition>] to broker 3:org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition. (kafka.server.ReplicaFetcherThread)

Checklist
=========

 - librdkafka version - 0.11.1
 - Apache Kafka version: 0.11.0.0
 - librdkafka client configuration:  "session.timeout.ms": 15000, "partition.assignment.strategy": "range", "enable.auto.commit": false, "auto.offset.reset": "earliest"
 - Operating system: Ubuntu 14.04

It looks like the message is read from broker 1 and committed to broker 1 but the read happens before rebalance and commit occurs after rebalance and hence the issue.

**Comment by krishanfrog** [comment]
The issue doesn't happen if I use asynchronous commits. I guess its expected if we use synchronous commits because other network calls will not go through until the commit is successful. But this way synchronous commits will not be usable due to this issue

**Comment by edenhill** [comment]
Can you reproduce this with the `debug` config property set to `cgrp,topic` and provide the log output?

**Comment by ChenyuanHu** [comment]
I encountered the same problem when I submitted asynchronously and fixed it. I'll post log and patch later.

**Comment by ChenyuanHu** [comment]
My Consumer config：
    {"security.protocol",   "SASL_PLAINTEXT"},
    {"sasl.mechanisms",     "PLAIN"},
    {"offset.store.method", "broker"},
    {"enable.auto.commit",  "false"},
    {"sasl.username", "........"},
    {"sasl.password",  "......."},
    {"group.id",  "......."},

And I call rd_kafka_commit asynchronously after message was handled。

I have 6 consumer, all use High-level API.
When I restart a consumer, there is a certain probability that I will not receive the message. Start again. He'll get a pile of messages.  I think some partion was assigned to it, but it didn't consume.

I got a log of normal and unusual situations to compare.

Normal log:
FETCHSTART [thrd:main]: Group ".........": starting fetchers for 3 assigned partition(s) in join-state assigned (usable_offsets=no, v15, line 2302)

unusual situations Log:
2018-01-02 17:07:44|(7) FETCHSTART [thrd:main]: Group ".........": not starting fetchers for 3 assigned partition(s) in join-state assigned (usable_offsets=no, v6, line 2302): waiting for 1 commit(s)
2018-01-02 17:07:44|(7) COMMIT [thrd:main]: sasl_plaintext://100.107.6.151:9092/1: OffsetCommit for 3 partition(s): manual: returned: Success

In an unusual case, after receiving the commit, he did not fetchstart again.

I looked at the key function and its modification history.  
`static void
rd_kafka_cgrp_partitions_fetch_start0 (rd_kafka_cgrp_t *rkcg,
				       rd_kafka_topic_partition_list_t
				       *assignment, int usable_offsets,
				       int line) {
        int i;

	/* If waiting for offsets to commit we need that to finish first
	 * before starting fetchers (which might fetch those stored offsets).*/
	if (rkcg->rkcg_wait_commit_cnt > 0) {
		rd_kafka_dbg(rkcg->rkcg_rk, CGRP, "FETCHSTART",
			     "Group \"%s\": not starting fetchers "
			     "for %d assigned partition(s) in join-state %s "
			     "(usable_offsets=%s, v%"PRId32", line %d): "
			     "waiting for %d commit(s)",
			     rkcg->rkcg_group_id->str, assignment->cnt,
			     rd_kafka_cgrp_join_state_names[rkcg->
							    rkcg_join_state],
			     usable_offsets ? "yes":"no",
			     rkcg->rkcg_version, line,
			     rkcg->rkcg_wait_commit_cnt);
		return;
	}`

Add at function rd_kafka_cgrp_op_handle_OffsetCommit 
`
 +	if (rkcg->rkcg_wait_commit_cnt == 0 &&
 +	    rkcg->rkcg_assignment &&
 +	    RD_KAFKA_CGRP_CAN_FETCH_START(rkcg))
 +		rd_kafka_cgrp_partitions_fetch_start(rkcg,
 +						     rkcg->rkcg_assignment, 0);`
this Code add on this commit，
https://github.com/edenhill/librdkafka/commit/474718752832ed1deca1b861c3ded39ee9e8aeda#diff-cc76569a59209937294362cbe190303e

but delete on this
https://github.com/edenhill/librdkafka/commit/f56d10c148f72238833cf01d16da5c38097a63c9#diff-cc76569a59209937294362cbe190303e

I think the author did not take rebalance into account, but only destory. So the fetchstart was not reexecuted at err=0 time.

I patch it.
`                /* FALLTHRU and error out */
        }

	rd_kafka_assert(NULL, rkcg->rkcg_wait_commit_cnt > 0);
	rkcg->rkcg_wait_commit_cnt--;

+    if (err == RD_KAFKA_RESP_ERR_NO_ERROR) {
+        rd_kafka_dbg(rk, CGRP, "COMMIT", "All commited, call fetch_start.");
+        if (rkcg->rkcg_wait_commit_cnt == 0 &&
+            rkcg->rkcg_assignment &&
+            RD_KAFKA_CGRP_CAN_FETCH_START(rkcg))
+                rd_kafka_cgrp_partitions_fetch_start(rkcg,
+                                                     rkcg->rkcg_assignment, 0);
+    }

	if (err == RD_KAFKA_RESP_ERR__DESTROY ||
            (err == RD_KAFKA_RESP_ERR__NO_OFFSET &&
             rko_orig->rko_u.offset_commit.silent_empty)) {
		rd_kafka_op_destroy(rko_orig);
                rd_kafka_cgrp_check_unassign_done(
                        rkcg,`

I tested the traffic online. The problem has been fixed.

**Comment by yijia2413** [comment]
@ChenyuanHu 's update works perfectly on our system, :100:
