### ISSUE TITLE
how legacy consumer to see consume state

### ISSUE THREAD

**Issue by tanglianggithub** [edenhill/librdkafka#1607]
I want to see how much data has been consumed and how much data not been consumed for legacy consumer.

I set group.id according to this wiki: according to this wiki : https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management

config:

#kafka Global config
builtin.features = gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins
client.id = rdkafka
metadata.broker.list = 1.23.16.137:9092
message.max.bytes = 1000000
message.copy.max.bytes = 65535
receive.message.max.bytes = 100000000
max.in.flight.requests.per.connection = 1000000
metadata.request.timeout.ms = 60000
topic.metadata.refresh.interval.ms = 300000
metadata.max.age.ms = -1
topic.metadata.refresh.fast.interval.ms = 250
topic.metadata.refresh.fast.cnt = 10
topic.metadata.refresh.sparse = true
debug = 
socket.timeout.ms = 60000
socket.blocking.max.ms = 1000
socket.send.buffer.bytes = 0
socket.receive.buffer.bytes = 0
socket.keepalive.enable = false
socket.nagle.disable = false
socket.max.fails = 3
broker.address.ttl = 1000
broker.address.family = any
reconnect.backoff.jitter.ms = 500
statistics.interval.ms = 0
enabled_events = 0
log_cb = 0x7fee1c83ce50
log_level = 6
log.queue = false
log.thread.name = true
log.connection.close = true
socket_cb = 0x7fee1c848860
open_cb = 0x7fee1c85b3a0
internal.termination.signal = 0
api.version.request = true
api.version.request.timeout.ms = 10000
api.version.fallback.ms = 1200000
broker.version.fallback = 0.9.0
security.protocol = plaintext
sasl.mechanisms = GSSAPI
sasl.kerberos.service.name = kafka
sasl.kerberos.principal = kafkaclient
sasl.kerberos.kinit.cmd = kinit -S "%{sasl.kerberos.service.name}/%{broker.name}" -k -t "%{sasl.kerberos.keytab}" %{sasl.kerberos.principal}
sasl.kerberos.min.time.before.relogin = 60000
`group.id = sh.group0`
partition.assignment.strategy = range,roundrobin
session.timeout.ms = 30000
heartbeat.interval.ms = 1000
group.protocol.type = consumer
coordinator.query.interval.ms = 600000
```
enable.auto.commit = true
auto.commit.interval.ms = 5000
enable.auto.offset.store = true
```
queued.min.messages = 100000
queued.max.messages.kbytes = 1000000
fetch.wait.max.ms = 100
fetch.message.max.bytes = 1048576
fetch.min.bytes = 1
fetch.error.backoff.ms = 500
offset.store.method = broker
enable.partition.eof = true
check.crcs = false
queue.buffering.max.messages = 100000
queue.buffering.max.kbytes = 4000000
queue.buffering.max.ms = 0
message.send.max.retries = 2
retry.backoff.ms = 100
compression.codec = none
batch.num.messages = 10000
delivery.report.only.error = false

#kafka Topic config
request.required.acks = 1
request.timeout.ms = 5000
message.timeout.ms = 300000
produce.offset.report = false
compression.codec = inherit
auto.commit.enable = true
auto.commit.interval.ms = 60000
auto.offset.reset = largest
offset.store.path = .
offset.store.sync.interval.ms = -1
`offset.store.method = broker`
consume.callback.max.messages = 0

 - [ ] librdkafka version: `0.11.0.1`
 - [ ] Operating system: `Centos 6,2`
 - [ ] Using the legacy Consumer
 - [ ]  broker version: 0.9

**Comment by edenhill** [comment]
You can registera stats_cb and look for consumer_lag on each consumed partition:
https://github.com/edenhill/librdkafka/wiki/Statistics

**Comment by tanglianggithub** [comment]
I am using librdkafka c++ interface and I didn't found stats_cb in librdkafka/src-cpp/ interface.
https://github.com/edenhill/librdkafka/blob/51a65ab4e8c1f7cf8d5987a53272001cc241ea97/src-cpp/rdkafkacpp.h#L809

only c interface has stats_cb.

Can I use mix c++ interface with c interface at the same time?
