### ISSUE TITLE
_MSG_TIMED_OUT with error code -192 in error_cb normal?

### ISSUE THREAD

**Issue by Hai-Lin** [edenhill/librdkafka#1611]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We have a 3 bare metal machines for our staging cluster running 0.10.2.1. And there is another cluster with 0.9 Kafka running in a different data center. We see the 192 error happened much more often on a 0.10.2.1 cluster than an old 0.9 cluster with identical client configuration. We are using the confluent python library with 0.11 and fallback to 0.9 and 0.10 brokers. Our major concern is the timeout error from time to time(for example about 1 per minute), can we safely ignore it since it's not even related to the sending a message? If we want to monitor producer health, should we force on other message like delivery fail call back? Any action we can take to improve this?

We can provide more server side configuration detail if it help.

How to reproduce
================
There is not much way we can reproduce, I think it might be a network related issue.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11`
 - [x] Apache Kafka version: `0.10.2.1`
 - [x] librdkafka client configuration: `KAFKA_CONFIG.update({
    "bootstrap.servers": ",".join([
        "broker1:port",
        "broker2:port",
        "broker3:port",
    ]),
    "schema.registry.url": "http://schema-registry-{{internal domain name}}",
    "broker.version.fallback": "0.10.2.1",
})`
 - [x] Operating system: `Ubuntu(docker for client, bare metal for Kafka cluster)`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka `MSG_TIMED_OUT with error code -192`
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Which exact librdkafka version are you on?

Try increasing linger.ms to something like 50-100ms and see if it helps.

**Comment by QinMing** [comment]
I work with @Hai-Lin .
The `librdkafka` that we are using is as follows. The one we said earlier was wrong.
```sh
$ apt list | grep librdkafka

librdkafka++1/stable,now 0.9.2~1confluent3.1.2-1 amd64 [installed,automatic]
librdkafka-dev/stable,now 0.9.2~1confluent3.1.2-1 amd64 [installed]
librdkafka1/stable,now 0.9.2~1confluent3.1.2-1 amd64 [installed,automatic]
librdkafka1-dbg/stable 0.9.2~1confluent3.1.2-1 amd64
```

**Comment by edenhill** [comment]
Ouch, that's pretty old. I suggest you upgrade to librdkafka 0.11.3

**Comment by Hai-Lin** [comment]
Our broker is still using 0.9 message format since a lot our client are still using 0.9. Will be any compatibility issue if we upgrade to 0.11.3 with brokers running on 0.10 and 0.9 message format?  Do you think the version related to the timeout?

**Comment by edenhill** [comment]
When upgrading you need to set `api.version.request=false` and `broker.version.fallback=0.9.0.0` on your client. More info here: https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

For producers you probably want to set `linger.ms` to a value between 50-100ms to promote performance (thru batching).


There's been a great number of fixes and modifications since 0.9.2, so it is likely that this problem has been fixed.

**Comment by Hai-Lin** [comment]
In the wiki, I saw 
```
Broker version >= 0.10.0.0 (or trunk)
api.version.request=true
```
is this true for 0.10 broker with 0.9 message format? Or we should follow the 0.9 broker setting. I think 0.10 broker supports the api version request even with 0.9 message format. 

Also more important for us is we are trying to deploy a version to production, should we block by the time out error? Or we can deploy to production since it's not related to message delivery and fix it in a later time?

**Comment by edenhill** [comment]
api.version.request=true is required for enabling new features, if you set it to false while connecting to a >=0.10 broker your client can only use 0.9 features.

As for the timed out error, I'm not yet sure what exactly is timing out. Are you seeing the error in error_cb or on_delivery?

**Comment by Hai-Lin** [comment]
In error_cb. I am trying to figure out what's the timeout, we are not really familiar with C++ code. Any way we can tell where the timed out happen in the log? We only see a simple time out with 192 code.

**Comment by edenhill** [comment]
If you get a TIMED_OUT/MSG_TIMED_OUT in the error_cb it means a protocol request timed out, which is typically due to networking issues.

Generally speaking the errors seen in error_cb should be seen as informational rather than fatal since librdkafka will try its best to recover from most types of errors.

**Comment by edenhill** [comment]
If you get timeout errors in on_delivery it means messages could not be delivered in time, which is more of a problem.

**Comment by Hai-Lin** [comment]
That's very helpful, any configuration on producer/broker side are related to the timed out in error_cb? Any tuning you recommend for us?  This is a small cluster(compare to other one we are running on production) with smaller throughput. 

We do 
io.thread=32
num.network.threads=48
and a lot of timeout as default as 0.10 default

**Comment by edenhill** [comment]
I suggest to set `debug=protocol,broker` in the producer to try to figure out which requests are failing.

**Comment by Hai-Lin** [comment]
This very helpful, we have some action items now. Much appreciated.

**Comment by edenhill** [comment]
Reopen if you see this again
