### ISSUE TITLE
Partition assignment guarantees?

### ISSUE THREAD

**Issue by HenningRoigaard** [edenhill/librdkafka#1622]
I have a couple of questions related to partition assignment in consumer groups.

When a group rebalances, one of the members are elected as leader. It is the responsibility of the leader to assign partitions to all members, across all subscribed topics. This is done using an assignment strategy, selected by the leader itself. We use Confluent's Apache Kafka .NET client, but I expect that the actual assignment is implemented in librdkafka. 

If that is the case, what guarantees, if any, does the default assignment strategy give? I cannot seem to find any documentation on the subject, not even in the native Java client.

Through testing using the Confluent Kafka .Net client, I have found to following property to hold for assignment: If a consumer groups has multiple members, and they subscribe to multiple topics with the _same_ number of partitions, then each consumer will be assigned the exact same partitions from each topic. E.g. if members M1 and M2 consume from topics T1 and T2 with 5 partitions each, and M1 is assigned partitions {0,2,4} from T1, then it will also be assigned the exactly same set of partitions {0,2,4} from T2.

Is this specific behavior guaranteed?

Finally, is it possible in librdKafka to inject a custom assignment strategy?

Checklist
=========
- [x] librdkafka version (release number or git tag): 0.11.3 via Confluent.Kafka 0.11.3
- [x] Apache Kafka version: 0.11.0.0
- [ ] librdkafka client configuration: 
- [x] Operating system: Windows 10 x64
- [ ] Provide logs (with `debug=..` as necessary) from librdkafka
- [ ] Provide broker log excerpts
- [ ] Critical issue

**Comment by edenhill** [comment]
The best source of information in this case is the source itself:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_roundrobin_assignor.c#L33
and
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_range_assignor.c#L36

**Comment by HenningRoigaard** [comment]
Thank you. I am not very proficient in reading C, but I found sufficient answer.

To summarize my new understanding:
* Librdkafka comes with 2 predefined assignment strategies: ‘range’ and ‘roundrobin’
* The guarantees are expressed via the algorithm in the documentation of the strategies. ‘range’ seems to guarantee the specific behavior I mentioned, while ‘roundrobin’ does not.
* Strategies available for a leader to choose from are the intersection of all allowed strategies for the consumers in the group. These are configured using the key “partition.assignment.strategy”, and defaults to both predefined strategies.

I am still unsure whether it is possible to inject custom assignment strategies, but at this point, it is mostly a point of curiosity, so I will leave it at that.

As another point of curiosity, I cannot really get a fix on how a strategy is selected by the leader if multiple strategies are allowed. By testing, I see that ‘range’ is chosen when using the default “partition.assignment.strategy” configuration. I guess it really does not matter and not something that should be relied on anyways.

**Comment by edenhill** [comment]
:+1:

The code is prepared for custom partitioners, but there is currently no API exposed to provide one. This is something we'll add on demand.

The selected strategy is the first one (left-to-right) supported by all members in the group.
