### ISSUE TITLE
Consumer fetchq empty but some partitions lagging

### ISSUE THREAD

**Issue by shanson7** [edenhill/librdkafka#1623]
Description
===========
Noticed after upgrading from 0.9.5 to 0.11.1:

While consuming from multiple partitions of a topic, I noticed that 2 partitions continually fall further and further behind, while the logic threads are almost completely idle.

In the stats I see that most partitions have 0 lag, and the fetchq_cnt is 0, but 2 partitions seem to just fall further and further behind. They are processing messages, just more slowly than the other partitions. It never seems to reach EOF either.

How to reproduce
================
Start consuming from several partitions. This naturally occurs.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.1`
 - [x] Apache Kafka version: `0.10.2.1`
 - [x] librdkafka client configuration: defaults except for  `queued.min.messages=15000,`
 - [x] Operating system: `RHEL 7.2`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
>  They are processing messages, just more slowly than the other partitions.

By this, do you mean that processing each individual message is slower for these partitions, or that the partitions are just consumed slower)?

**Comment by shanson7** [comment]
Sorry, that was pretty ambiguous. I meant that messages are consumed more slowly, but not by much. Perhaps two comparative stats outputs would helps.

In the attached file, partition 210 and 211 are the 2 slow ones (there are about 25 partitions total, split across 4 topics for this consumer). I also included the stats for 212 to show what the rest of the topics look like. You'll notice that both 210 and 211 have lag, but have consumed fewer msgs than 212, which is all caught up. This topic is produced to without hash (unassigned partition), so they should all get about the same msgs/s. 

For reference, we have 28 threads calling `consume` (C++ API) simultaneously. We seem to be spending roughly 90% of our time in `consume` (processor threads pretty much idle), yet not getting these msgs. For comparison, with 0.9.5 the bottleneck was almost always in our message processing, not the consuming (librdkafka was usually able to keep the fetchq full when we lagged).
 
[slow_consume.txt](https://github.com/edenhill/librdkafka/files/1606883/slow_consume.txt)

**Comment by edenhill** [comment]
Possibly related to this:
https://github.com/edenhill/librdkafka/issues/1395#issuecomment-355547750

That is, OffsetCommits to the group coordinator broker may potentially slow down the partitions being consumed from that same broker.

**Comment by shanson7** [comment]
In this case, partition 210 has `"leader": 5` and 211 has `"leader": 10` and both are lagging. 

These are the only 2 partitions that have those leaders in this consumer instance. Since you pointed out the `rtt` avg, brokers 5 && 10 are much *lower* than the other brokers and the counts are lower as well. I'm attaching a breakdown and the entire stats file.

[broker_rtt.txt](https://github.com/edenhill/librdkafka/files/1607039/broker_rtt.txt)
[all_stats.txt](https://github.com/edenhill/librdkafka/files/1607040/all_stats.txt)

**Comment by shanson7** [comment]
Maybe a silly question, but is it ok that the 0.11.1 consumers are in a mixed consumer group with 0.9.5 consumers?

**Comment by shanson7** [comment]
TBH, I can only seem to make this happen when the 0.11.1 consumer joins my consumer group in progress.  

If I start up a 0.11.1 consumer in a new consumer group, it's fine. If I start up a new consumer group with a 0.9.5 consumer and add an 0.11.1 consumer, it's also fine. Idk if there is something special about the consumer group I'm trying to add them to, but's it is very strange.

I can consistently reproduce the result with this one particular pre-existing consumer group.

**Comment by edenhill** [comment]
So:
 * 0.9.5 + 0.9.5 = ok
 * 0.9.5 + 0.11.1 = ok
 * 0.11.1 + 0.11.1 = lag

?

What about 0.11.1 + 0.9.5 (i.e., add a 0.9.5 to a 0.11.1 group)?

**Comment by edenhill** [comment]
Silly question:
 is it possible that your per-message data is significantly different for the partitions handled by leader 5 and 10? E.g., much larger, or smaller, message sizes?

**Comment by shanson7** [comment]
The messages in this topic range from ~2-400 KB, but they should be randomly distributed across the partitions.

**Comment by shanson7** [comment]
>So:
0.9.5 + 0.9.5 = ok
0.9.5 + 0.11.1 = ok
0.11.1 + 0.11.1 = lag
?

Unfortunately, it's not that easy. If I create a new consumer group with just 0.9.5 consumers, then replace one with a 0.11.1 consumer, it doesn't seem to replicate the issue. The only time I can consistently replicate this is by adding an 0.11.1 consumer to a particular consumer group (that has be around for a very long time). 

Can you recommend some debug settings for rdkafka logging that might spit out some decent info?

**Comment by edenhill** [comment]
Most of the consumer fetch debugging is unfortunately quite chatty (by nature) so not really suitable for long-running processes.

But what we're after here is `debug=cgrp,topic,fetch`

**Comment by shanson7** [comment]
I see messages like `08JAN2018_15:04:19.865492 188768:140577265923840 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = BACKOFF event = [thrd:tel-pub-prr-r01-n05.bloomberg.com:9092/5]: tel-pub-prr-r01-n05.bloomberg.com:9092/5: logs [15]: Fetch backoff for 500ms: Local: Bad message format`

I'll run with debug on and version 0.9.5 to see if we get these there as well.

**Comment by edenhill** [comment]
Interesting, if you add `protocol` to the list of debug contexts you should see the reason why the message was considered bad

**Comment by shanson7** [comment]
```
08JAN2018_16:08:09.610865 37859:140497574164224 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = PROTOERR event = [thrd:tel-pub-prr-r02-
n03.bloomberg.com:9092/8]: tel-pub-prr-r02-n03.bloomberg.com:9092/8: Protocol parse failure at 979511/1048612 (rd_kafka_msgset_reader_msg_v0_1:464) (incorrect broker.ve
rsion.fallback?)

08JAN2018_16:08:09.610878 37859:140497574164224 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = PROTOERR event = [thrd:tel-pub-prr-r02-
n03.bloomberg.com:9092/8]: tel-pub-prr-r02-n03.bloomberg.com:9092/8: expected 215053 bytes > 69101 remaining bytes
```

So, I'll admit I'm a little under-informed on the protocol differences. I see this:

```
08JAN2018_16:13:57.655926 41107:139629076391680 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = SEND event = [thrd:tel-pub-prr-r01-n04:9092/bootstrap]: tel-pub-prr-r01-n04:9092/bootstrap: Sent ApiVersionRequest (v0, 25 bytes @ 0, CorrId 1)
08JAN2018_16:13:57.656342 41107:139629076391680 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = RECV event = [thrd:tel-pub-prr-r01-n04:9092/bootstrap]: tel-pub-prr-r01-n04:9092/bootstrap: Received ApiVersionResponse (v0, 132 bytes, CorrId 1, rtt 0.35ms)
08JAN2018_16:13:57.663601 41107:139625553192704 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = CONNECTED event = [thrd:tel-pub-prr-r01-n04.bloomberg.com:9092/4]: tel-pub-prr-r01-n04.bloomberg.com:9092/4: Connected (#1)
08JAN2018_16:13:57.663634 41107:139625553192704 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = FEATURE event = [thrd:tel-pub-prr-r01-n04.bloomberg.com:9092/4]: tel-pub-prr-r01-n04.bloomberg.com:9092/4: Updated enabled protocol features +ApiVersion to ApiVersion
```

**Comment by shanson7** [comment]
We do not explicitly set a broker version fallback

**Comment by shanson7** [comment]
It seems like maybe messages are getting truncated to 1048612 bytes?

**Comment by edenhill** [comment]
This is expected, as an optimization on the broker it may send partial messages (using sendfile()), and the client is supposed to handle it gracefully, which librdkafka should be doing so it should not fall into the fetch.backoff trap.

Can you give me a somewhat larger log snippet that also includes the "Fetch backoff" ?

**Comment by shanson7** [comment]
Short one and attached the first 10k lines of output for one of the runs.
[0.11.1_proto_debug.clean.short.txt](https://github.com/edenhill/librdkafka/files/1612301/0.11.1_proto_debug.clean.short.txt)


```
8JAN2018_16:14:00.457698 41107:139625528014592 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = CONSUME event = [thrd:tel-pub-prr-r01-n
01.bloomberg.com:9092/1]: tel-pub-prr-r01-n01.bloomberg.com:9092/1: Enqueue 23 message(s) (23 ops) on logs [168] fetch queue (qlen 23, v2, last_offset 1624804154)

08JAN2018_16:14:00.458076 41107:139625528014592 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = CONSUME event = [thrd:tel-pub-prr-r01-n
01.bloomberg.com:9092/1]: tel-pub-prr-r01-n01.bloomberg.com:9092/1: Enqueue 12 message(s) (12 ops) on logs [168] fetch queue (qlen 12, v2, last_offset 1624804166)

08JAN2018_16:14:00.458105 41107:139625528014592 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = PROTOERR event = [thrd:tel-pub-prr-r01-
n01.bloomberg.com:9092/1]: tel-pub-prr-r01-n01.bloomberg.com:9092/1: Protocol parse failure at 925108/1048612 (rd_kafka_msgset_reader_msg_v0_1:464) (incorrect broker.ve
rsion.fallback?)

08JAN2018_16:14:00.458126 41107:139625528014592 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = PROTOERR event = [thrd:tel-pub-prr-r01-
n01.bloomberg.com:9092/1]: tel-pub-prr-r01-n01.bloomberg.com:9092/1: expected 455153 bytes > 123504 remaining bytes

08JAN2018_16:14:00.458146 41107:139625528014592 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = CONSUME event = [thrd:tel-pub-prr-r01-n
01.bloomberg.com:9092/1]: tel-pub-prr-r01-n01.bloomberg.com:9092/1: Enqueue 0 message(s) (130 ops) on logs [168] fetch queue (qlen 130, v2, last_offset 1624804166)

08JAN2018_16:14:00.458163 41107:139625528014592 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = BACKOFF event = [thrd:tel-pub-prr-r01-n01.bloomberg.com:9092/1]: tel-pub-prr-r01-n01.bloomberg.com:9092/1: logs [168]: Fetch backoff for 500ms: Local: Bad message format

08JAN2018_16:14:00.458359 41107:139625528014592 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = FETCH event = [thrd:tel-pub-prr-r01-n01.bloomberg.com:9092/1]: tel-pub-prr-r01-n01.bloomberg.com:9092/1: Topic logs [168] in state active at offset 1624804037 (117/15000 msgs, 1507/1000000 kb queued, opv 2) is not fetchable: fetch backed off

08JAN2018_16:14:00.458390 41107:139625528014592 DEBUG ipbkafka_consumer.cpp:185 IPBKAFKA.CONSUMER KAFKA LOG:  severity = 7 fac = FETCHADD event = [thrd:tel-pub-prr-r01-n01.bloomberg.com:9092/1]: tel-pub-prr-r01-n01.bloomberg.com:9092/1: Removed logs [168] from fetch list (0 entries, opv 2)
```

**Comment by edenhill** [comment]
Thank you very much!

 I guess your message size is not close to 1MB?

**Comment by shanson7** [comment]
No, all messages >1MB get blocked at the produce level, but that is definitely larger than we expect these messages to be.

**Comment by edenhill** [comment]
Could ~455153 bytes be an actual message?

**Comment by shanson7** [comment]
Yeah, that's about on the upper end of what we expect.

**Comment by edenhill** [comment]
Okay, thanks, I think I know what's wrong, I'll make a fix that you can try out soon

**Comment by shanson7** [comment]
Oh, fantastic!

**Comment by edenhill** [comment]
Is this a compressed topic? If so: what compression?

**Comment by shanson7** [comment]
It uses snappy

**Comment by edenhill** [comment]
Would it be easy for you to test a fix branch?

**Comment by shanson7** [comment]
Not trivial, but I am eager to try.

**Comment by edenhill** [comment]
Although I managed to reproduce this behaviour locally it would be very valuable to see if the fix works out in the open.

Please give the `fix_1623` branch a spin when you get the chance.

Thanks

**Comment by shanson7** [comment]
I was able to build against that patch and I no longer see the "Bad message format" messages and I don't see any lagging. 

What was the issue?

**Comment by edenhill** [comment]
Whoop, that's great news, thanks!

The message reader error checking code would trigger a backoff if a parsing/underflow error was seen and the counter of read messages was 0 - e.g., it could not parse at least one message from the received response - which indicates a real error.

The problem was that it could indeed parse about 130 messages before the response buffer ran out, but since those messages were compressed they were not counted correctly and the backoff code would kick in and stall consumption for 500ms.
This was a one-line fix.

Very happy with your help on this issue, thanks alot!

We're aiming for a new maintenance release mid february, in the meantime you can reduce `fetch.error.backoff.ms` as a workaround.

The fix will land in master later today.

**Comment by shanson7** [comment]
Awesome! Thanks for such quick responses and debug help!
