### ISSUE TITLE
how set offset after rebalance_callback()

### ISSUE THREAD

**Issue by tinux2015** [edenhill/librdkafka#1624]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
It's a question, HELP!!
When I reset the offset after rebalance_cb() like the example:
 createKafka() {
   rd_kafka_topic_partition_list_t *partitions;
   partitions = rd_kafka_topic_partition_list_new(1);
   rd_kafka_topic_partition_list_add(partitions, "mytopic", RD_KAFKA_PARTITION_UA);
   rd_kafka_subscribe(rk, partitions);
 }

 rebalance_cb(...., rd_kafka_topic_partition_list_t *partitions, ...) {
   // store partitions in my_partition
 }

  my_func() {
    rd_kafka_topic_partition_list_add(partitions, "mytopic", my_partition)->offset = 1234;
    rd_kafka_assign(rk, partitions);
 }

But some error happened:
* rdkafka_cgrp.c:2727:rd_kafka_cgrp_op_serve: assert: rktp->rktp_assigned *

Looking forward to you reply,thank u very much!
best wishes.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<0.11>`
 - [x] Apache Kafka version: `< 0.10>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<suse>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Your code is incomplete: how is my_func() called?

**Comment by tinux2015** [comment]
like this:
      while (1) {
            rd_kafka_message_t *rkmessage = rd_kafka_consumer_poll();
            my_func();
            // do something
       }

**Comment by edenhill** [comment]
re-read documentation on rebalance_cb, the application must call assign() from within the callback:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1340

**Comment by tinux2015** [comment]
OK，I will try again ，thank u

**Comment by tinux2015** [comment]
This problem is solved
It's my fault,I called assign() many time in the whileLoop
when I modified to call once assign(),it's worked.
Thank u for your reply
