### ISSUE TITLE
No support for Kafka 1.0.0

### ISSUE THREAD

**Issue by angelpp2018** [edenhill/librdkafka#1627]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>
Does the latest librdkafka support Kafka 1.0.0 ? It seems no, we can't find this kind of information in release notes.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#is-librdkafka-compatible-with-my-broker-version

**Comment by angelpp2018** [comment]
Thanks, so librdkafka has already supported Kafka 1.0.0, right ? If Yes, I will close this issue.

**Comment by edenhill** [comment]
It depends on what you mean, librdkafka is compatible with broker 1.0.0, but it might not support all features of Kafka 1.0.0 - Idempotent and EOS in particular are not supported.

Is there a specific feature you are looking for?

**Comment by angelpp2018** [comment]
We are going to upgrade our Kafka server version to 1.0.0 to mitigate Jackthon Databind security vunerability, but we are not sure whether the latest librdkafka lib has supports Kafka 1.0.0. We are using 0.9.2 version librdkafka. Can we upgrade librdkafka lib  the lastest version to keep compatible with Kafka 1.0.0. ?

**Comment by edenhill** [comment]
Brokers are backwards compatible with old clients (>=0.8) and librdkafka is backwards compatible with older brokers (>=0.8), so both combinations are fine and yes you can (and should) upgrade to the latest release of librdkafka (0.11.3) regardless of your broker version.

Make sure to read the broker version compatibility wiki page lined above.

**Comment by angelpp2018** [comment]
Thanks for all your answers, I think we can close this issue now.
