### ISSUE TITLE
How to Throw an Error When Wrong SASL Authentication Info Given

### ISSUE THREAD

**Issue by jihwan-chun** [edenhill/librdkafka#1633]
Description
===========
I'm using SASL_PLAINTEXT for my authentication to Kafka brokers. It works well, but in case I make a mistake for a authentication info(username/password) I just want to throw an error when authenticaion fails.

It seems that current librdkafka does not throw any error when client fails to connect to broker because of wrong username/password. How can I make it?

Checklist
=========
 - [x] librdkafka version (release number or git tag): 0.11.3
 - [x] Apache Kafka version: 1.0.0
 - [x] librdkafka client configuration:
```
var config = new Dictionary<string, object>
                    {
                        {"bootstrap.servers", string.Join(",", kafkaBrokerList)},
                        {"client.id", Dns.GetHostName()},
                        {
                            "default.topic.config",
                            new Dictionary<string, object>
                            {
                                {"acks", "all"}
                            }
                        },
                        {"security.protocol", "SASL_SSL"},
                        {"sasl.mechanisms", "PLAIN"},
                        {"ssl.ca.location", sslCALocation},
                        {"ssl.certificate.location", sslCertificateLocation},
                        {"ssl.key.location", sslKeyLocation},
                        {"sasl.username", saslUsername},
                        {"sasl.password", saslPassword}
                    };
```
 - [x] Operating system: Windows Server 2016 Base
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: Question issue, no logs yet
 - [x] Provide broker log excerpts
 - [?] Critical issue

**Comment by edenhill** [comment]
You should receive an ERR__AUTHENTICATION error code in your onError handler

**Comment by jihwan-chun** [comment]
Added an handler at producer and it smoothly worked. Leaving the snippet for whom have a same question with me -

(I'm using [confluent-kafka-dotnet](https://github.com/confluentinc/confluent-kafka-dotnet) for client library using librdkafka)
```csharp
producer = new Producer<Null, string>( ... );
producer.OnError += (_, error) =>
{
    /* ... some another error handling code ... */
    if (error.Code == ErrorCode.Local_Authentication)
    {
        /* ... Throw error, leave log or do whatever you want ... */
    }
};
```

Thank you so much for the help!
