### ISSUE TITLE
how can i set a broker bind  a network-card  in a PC with four network-card, please?

### ISSUE THREAD

**Issue by ChildePig** [edenhill/librdkafka#1634]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
 I'm tryying to build a cluster in one machine that have four network-card, and i want set one broker bind one of four network-card,  then it can run in right.

but when i produce data to this cluster,  i found that only one network-card in IO, others is null.

would you like to give me  some advice?   thank you very very much !!

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ x] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ centos7.0 ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [x ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x ] Provide broker log excerpts
 - [ x] Critical issue

**Comment by edenhill** [comment]
This is currently not supported in librdkafka itself, but a quick google turned up this:
https://unix.stackexchange.com/a/210992

**Comment by ChildePig** [comment]
ok, thank you very much
