### ISSUE TITLE
rd_kafka_offsets_for_times reports RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE constantly

### ISSUE THREAD

**Issue by kparadkar** [edenhill/librdkafka#1641]
I have a single node kafka cluster where I am using rd_kafka_offsets_for_times API (0.11.3 RELEASE). I have produced to two topics topic1 and topic2 with timestamp and I am calling rd_kafka_offsets_for_times(consumer, 10000/*timeout_ms*/).

However every call errors out with RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE.

Command: bin/kafka-topics.sh --describe --topic topic1 --zookeeper localhost:2181
Output: 
        Topic:topic1	PartitionCount:5	ReplicationFactor:1	Configs:
	Topic: topic1	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
	Topic: topic1	Partition: 1	Leader: 0	Replicas: 0	Isr: 0
	Topic: topic1	Partition: 2	Leader: 0	Replicas: 0	Isr: 0
	Topic: topic1	Partition: 3	Leader: 0	Replicas: 0	Isr: 0
	Topic: topic1	Partition: 4	Leader: 0	Replicas: 0	Isr: 0

Command: bin/kafka-topics.sh --describe --topic topic2 --zookeeper localhost:2181
Output:
        Topic:topic2	PartitionCount:5	ReplicationFactor:1	Configs:
	Topic: topic2	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
	Topic: topic2	Partition: 1	Leader: 0	Replicas: 0	Isr: 0
	Topic: topic2	Partition: 2	Leader: 0	Replicas: 0	Isr: 0
	Topic: topic2	Partition: 3	Leader: 0	Replicas: 0	Isr: 0
	Topic: topic2	Partition: 4	Leader: 0	Replicas: 0	Isr: 0

I debugged little bit and found that rd_kafka_metadata_cache_topic_partition_get call never finds topic partition in its cache and query_topics after rd_kafka_topic_partition_list_get_leaders always contains all 10 topic partitions (topic1+topic2) and eventually drops out of while loop. 

API flow -
rd_kafka_producev(producer) .. with timestamp
rd_kafka_offsets_for_times (consumer, timeout)

I have also tried test with rd_kafka_producev, rd_kafka_subscribe(consumer, tp_list) , rd_kafka_offsets_for_times but that doesnt work either.

Please help. Am I missing something here?

**Comment by edenhill** [comment]
kafka-topics.sh queries zookeeper while librdkafka queries the brokers directly, can you get the metadata for those topics using `examples/rdkafka_example -b <broker> -L -t topic1` and topic2 and provide the output here?

**Comment by kparadkar** [comment]
examples# ./rdkafka_example -b localhost:9092 -L -t topic1
Metadata for topic1 (from broker -1: localhost:9092/bootstrap):
 1 brokers:
  broker 0 at mfs56.qa.lab:9092
 1 topics:
  topic "topic1" with 0 partitions: Broker: Leader not available (try again)
root@mfs56:/home/builds/private-librdkafka-kp/examples# ./rdkafka_example -b localhost:9092 -L -t topic2
Metadata for topic2 (from broker -1: localhost:9092/bootstrap):
 1 brokers:
  broker 0 at mfs56.qa.lab:9092
 1 topics:
  topic "topic2" with 0 partitions: Broker: Leader not available (try again)


I have modified following server.properties - 
delete.topic.enable=true
num.partitions=5
auto.create.topics.enable = true

**Comment by kparadkar** [comment]
Ok I had to add following in server.properties -
port = 9092
advertised.host.name = localhost


Now I see all leaders correctly
./rdkafka_example -b localhost:9092 -L -t topic2
Metadata for topic2 (from broker 0: localhost:9092/0):
 1 brokers:
  broker 0 at localhost:9092
 1 topics:
  topic "topic2" with 5 partitions:
    partition 2, leader 0, replicas: 0, isrs: 0
    partition 4, leader 0, replicas: 0, isrs: 0
    partition 1, leader 0, replicas: 0, isrs: 0
    partition 3, leader 0, replicas: 0, isrs: 0
    partition 0, leader 0, replicas: 0, isrs: 0

**Comment by kparadkar** [comment]
Reopened the issue since I still get RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE  error

**Comment by edenhill** [comment]
Okay, can you reproduce with `-d protocol,metadata,topic`  and provide the output?

**Comment by kparadkar** [comment]
./rdkafka_example -b localhost:9092 -L -t topic1 -d protocol,metadata,topic 2> out.txt
Metadata for topic1 (from broker -1: localhost:9092/bootstrap):
 1 brokers:
  broker 0 at localhost:9092
 1 topics:
  topic "topic1" with 5 partitions:
    partition 2, leader 0, replicas: 0, isrs: 0
    partition 4, leader 0, replicas: 0, isrs: 0
    partition 1, leader 0, replicas: 0, isrs: 0
    partition 3, leader 0, replicas: 0, isrs: 0
    partition 0, leader 0, replicas: 0, isrs: 0

[out.txt](https://github.com/edenhill/librdkafka/files/1643940/out.txt)

**Comment by edenhill** [comment]
Oh sorry, I was a bit unclear, my bad.
Can you reproduce the issue with your tool with debug=protocol,metadata,topic enabled, making sure your call to offsets_for_times() is clearly printed in the output?

As a workaround you can also try calling rd_kafka_metadata(rk, rkt..); prior to offsets_for_times()

**Comment by kparadkar** [comment]
%7|1516311300.791|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516311301.291|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516311302.393|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516311304.094|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516311306.396|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516311309.297|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516311310.795|DESTROY|rdkafka#consumer-2| [thrd:app]: Terminating instance
%7|1516311310.795|DESTROY|rdkafka#consumer-2| [thrd:main]: Destroy internal
%7|1516311310.795|DESTROY|rdkafka#consumer-2| [thrd:main]: Removing all topics
%7|1516311310.896|BROKERFAIL|rdkafka#consumer-2| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
~

**Comment by edenhill** [comment]
can you include the full log, and point out where you call offsets_for_times so I can correlate the logs?

**Comment by kparadkar** [comment]
This is the complete log. With some debug message with test code. 
 BEFORE OffsetsForTimes: tp count: 10
topic: topic1 partition:0	offset: 1005
topic: topic2 partition:0	offset: 2005
topic: topic1 partition:1	offset: 1005
topic: topic2 partition:1	offset: 2005
topic: topic1 partition:2	offset: 1005
topic: topic2 partition:2	offset: 2005
topic: topic1 partition:3	offset: 1005
topic: topic2 partition:3	offset: 2005
topic: topic1 partition:4	offset: 1005
%7|1516313875.373|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516313875.873|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516313876.981|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516313878.682|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516313880.983|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516313883.885|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
topic: topic2 partition:4	offset: 2005
 AFTER OffsetsForTimes: error: 5, tp count: 10 --> After offsetsForTimes API
topic: topic1 partition:0	offset: 1005 error:0
topic: topic2 partition:0	offset: 2005 error:0
topic: topic1 partition:1	offset: 1005 error:0
topic: topic2 partition:1	offset: 2005 error:0
topic: topic1 partition:2	offset: 1005 error:0
topic: topic2 partition:2	offset: 2005 error:0
topic: topic1 partition:3	offset: 1005 error:0
topic: topic2 partition:3	offset: 2005 error:0
topic: topic1 partition:4	offset: 1005 error:0
%7|1516313885.375|DESTROY|rdkafka#consumer-2| [thrd:app]: Terminating instance
%7|1516313885.375|DESTROY|rdkafka#consumer-2| [thrd:main]: Destroy internal
%7|1516313885.375|DESTROY|rdkafka#consumer-2| [thrd:main]: Removing all topics
%7|1516313885.477|BROKERFAIL|rdkafka#consumer-2| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
topic: topic2 partition:4	offset: 2005 error:0

**Comment by edenhill** [comment]
That's the complete log? Okay, please reproduce with `debug=protocol,metadata,topic,broker`, need more info. thanks

**Comment by kparadkar** [comment]
It didn't give lot more information

 
BEFORE OffsetsForTimes: tp count: 10
topic: topic1 partition:0	offset: 1005
topic: topic2 partition:0	offset: 2005
topic: topic1 partition:1	offset: 1005
topic: topic2 partition:1	offset: 2005
topic: topic1 partition:2	offset: 1005
topic: topic2 partition:2	offset: 2005
topic: topic1 partition:3	offset: 1005
topic: topic2 partition:3	offset: 2005
topic: topic1 partition:4	offset: 1005
%7|1516317273.457|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516317273.457|BRKMAIN|rdkafka#consumer-2| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1516317273.457|STATE|rdkafka#consumer-2| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1516317273.959|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516317275.059|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516317276.761|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516317279.061|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
%7|1516317281.962|METADATA|rdkafka#consumer-2| [thrd:app]: Skipping metadata refresh of 2 topic(s): no usable brokers
topic: topic2 partition:4	offset: 2005
 AFTER OffsetsForTimes: error: 5, tp count: 10
topic: topic1 partition:0	offset: 1005 error:0
topic: topic2 partition:0	offset: 2005 error:0
topic: topic1 partition:1	offset: 1005 error:0
topic: topic2 partition:1	offset: 2005 error:0
topic: topic1 partition:2	offset: 1005 error:0
topic: topic2 partition:2	offset: 2005 error:0
topic: topic1 partition:3	offset: 1005 error:0
topic: topic2 partition:3	offset: 2005 error:0
topic: topic1 partition:4	offset: 1005 error:0
%7|1516317283.458|DESTROY|rdkafka#consumer-2| [thrd:app]: Terminating instance
%7|1516317283.458|DESTROY|rdkafka#consumer-2| [thrd:main]: Destroy internal
%7|1516317283.458|DESTROY|rdkafka#consumer-2| [thrd:main]: Removing all topics
%7|1516317283.458|TERM|rdkafka#consumer-2| [thrd::0/internal]: :0/internal: Received TERMINATE op in state UP: 1 refcnts, 0 toppar(s), 0 fetch toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1516317283.558|TERMINATE|rdkafka#consumer-2| [thrd::0/internal]: :0/internal: Handle is terminating: failed 0 request(s) in retry+outbuf
%7|1516317283.558|BROKERFAIL|rdkafka#consumer-2| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1516317283.558|STATE|rdkafka#consumer-2| [thrd::0/internal]: :0/internal: Broker changed state UP -> DOWN
topic: topic2 partition:4	offset: 2005 error:0

**Comment by kparadkar** [comment]
Ok My bad. In my test code broker's were not added for consumer (were added only for producer) hence I was hitting the error. Everything works now. Thanks!
