### ISSUE TITLE
Commit messages on Producer

### ISSUE THREAD

**Issue by karthikeyanajendran1984** [edenhill/librdkafka#1643]
Hi ,

I have developed the Consumer in C language using librdkafka and performing manual commit based on time and counts on messages what ever first reaches.

Currently I am working on Producer side and i would like to know whether the commit is really required for producer. I have referred the CONFIGURATION.md related to commit properties like auto.commit.enable, auto.commit.interval.ms which is only for consumer not for producer.

Also I am not seen any commit call in librdkafka example code.

Please let me know whether we really required a commit from producer side or we can just use the Delivery report callback (dr_cb or dr_msg_cb) to verify through reports.
Also please let me know whether this is same for produce a message in batch request mode(produce multiple message at one call).

Thanks in advance.

Regards,
Karthik

**Comment by edenhill** [comment]
commit() is a consumer method, not to be used on the producer.

**Comment by karthikeyanajendran1984** [comment]
Thanks @edenhill . You meant rd_kafka_commit () is a consumer method ?
If Yes, Can you please let me know in this case how we can verify from producer side that the message has been published successfully to kafka Server.

**Comment by edenhill** [comment]
Register a delivery report:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-reliability
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1312

**Comment by karthikeyanajendran1984** [comment]
@edenhill, Thank you very much for your time.
