### ISSUE TITLE
[Question] Should messages be committed when partitions are revoked?

### ISSUE THREAD

**Issue by andreycha** [edenhill/librdkafka#1647]
Hi,

We have a consumer with disabled autocommit, and we commit messages every N seconds. We are also subscribed to rebalancing callback and have some logic when partitions are assigned and revoked. The question is: do we need to commit messages when partitions are revoked or this is done automatically on rebalancing?

Thank you.

Checklist
=========

 - [x] librdkafka version (release number or git tag): `0.11.2`
 - [x] Apache Kafka version: `1.0`
 - [x] librdkafka client configuration: `enable.auto.commit = false`
 - [x] Operating system: `Win7 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Final offsets will be committed on rebalance (revoke) only if auto commit is enabled.

**Comment by andreycha** [comment]
I see, thank you!
