### ISSUE TITLE
librdkafka.redist nuget package is running into Run-Time Check Failure on windows

### ISSUE THREAD

**Issue by noahdav** [edenhill/librdkafka#1648]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
In the 0.11.3 librdkafka.redist nuget package I am running into the bug described here https://github.com/edenhill/librdkafka/issues/1334.  However if I checkout and build v0.11.3 it is working correctly.  Since I do not have the symbols in the nuget package it is hard for me to see what is actually happening.

Since our build environment is required to use the nuget package I am not able to use the build from source as a final fix.  Is it possible to update the official nuget package?  If not can you let me know when it will be updated?

How to reproduce
================
using the nuget package for librdkafka.redist set a config value.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.3`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
We're looking to release new versions of the clients mid-late February, there'll be a release candidate or two in a couple of weeks hopefully.

**Comment by noahdav** [comment]
Sounds good.  I can hopefully wait until then.  Thanks for letting me know.
