### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by a285577011** [edenhill/librdkafka#1649]
Description
===========
Installing librdkafka and go get -u github.com/confluentinc/confluent-kafka-go/kafka
wrong:
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /lib/../lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /lib/../lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/../lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/../lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/local/lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/local/lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: cannot find -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /lib/../lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /lib/../lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/../lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/../lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/local/lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/local/lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/librdkafka.so when searching for -lrdkafka
/usr/bin/ld: skipping incompatible /usr/lib/librdkafka.a when searching for -lrdkafka
/usr/bin/ld: cannot find -lrdkafka

Checklist
=========
centos7

**Comment by edenhill** [comment]
How did you install librdkafka and what version?

**Comment by a285577011** [comment]
@edenhill There is a problem with my golang version
