### ISSUE TITLE
rdkafka_sasl_cyrus.c:39:23: fatal error: sasl/sasl.h: No such file or directory

### ISSUE THREAD

**Issue by Al-Dailami** [edenhill/librdkafka#1650]
Description
===========
I want to cross-compile librdkafka for mipsel-openwrt-linux architecture using lede SDK toolchain mipsel-openwrt-linux-gcc and i gote the following error:

I'm Using Ubuntu 16.04LTS and  librdkafka-0.9.5

here is the last part of the debug log:

r/include -I/documents/source/staging_dir/target-mipsel_24kc_musl-1.1.16/usr/include -c rdkafka_sasl_cyrus.c -o rdkafka_sasl_cyrus.o
rdkafka_sasl_cyrus.c:39:23: fatal error: sasl/sasl.h: No such file or directory
compilation terminated.
../mklove/Makefile.base:77: recipe for target 'rdkafka_sasl_cyrus.o' failed
make[5]: *** [rdkafka_sasl_cyrus.o] Error 1
make[5]: Leaving directory '/documents/source/build_dir/target-mipsel_24kc_musl-1.1.16/librdkafka-0.9.5/src'
Makefile:20: recipe for target 'libs' failed
make[4]: *** [libs] Error 2
make[4]: Leaving directory '/documents/source/build_dir/target-mipsel_24kc_musl-1.1.16/librdkafka-0.9.5'
Makefile:63: recipe for target '/documents/source/build_dir/target-mipsel_24kc_musl-1.1.16/librdkafka-0.9.5/.built' failed
make[3]: *** [/documents/source/build_dir/target-mipsel_24kc_musl-1.1.16/librdkafka-0.9.5/.built] Error 2
make[3]: Leaving directory '/documents/source/feeds/librdkafka/librdkafka'
package/Makefile:105: recipe for target 'package/feeds/librdkafka/librdkafka/compile' failed
make[2]: *** [package/feeds/librdkafka/librdkafka/compile] Error 2
make[2]: Leaving directory '/documents/source'
package/Makefile:101: recipe for target '/documents/source/staging_dir/target-mipsel_24kc_musl-1.1.16/stamp/.package_compile' failed
make[1]: *** [/documents/source/staging_dir/target-mipsel_24kc_musl-1.1.16/stamp/.package_compile] Error 2
make[1]: Leaving directory '/documents/source'
/documents/source/include/toplevel.mk:205: recipe for target 'world' failed
make: *** [world] Error 2

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): librdkafka-0.9.5
 - [x] Apache Kafka version:  0.10.2.3
 - [ ] librdkafka client configuration: message.timeout.ms=123, auto.reset.offset=earliest, 
 - [x] Operating system: ubuntu 16.04LTS (x64)
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Cross compilation is a can of worms and very hard to generally support, but it is possible.
Important part is that the same params are passed to the configure and build steps.
You do this by setting up CC, CXX, CFLAGS, CXXFLAGS, CPPFLAGS, LDFLAGS, LIBS and other environment variables in your call to ./configure and making sure the proper features are detected, troubleshoot by looking at config.log

**Comment by Al-Dailami** [comment]
Thanks a lot for your reply...

I'm using the same steps as the following page:
https://github.com/ifding/openwrt-packages

**Comment by Al-Dailami** [comment]
Hi, can you please help. 
I still could not compile the library.

I'm now using toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16 

the configure command is : 
./configure --host=mips-*-* --target=mipsel-linux --prefix=/documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16 --cc=\${prefix}/bin/mipsel-openwrt-linux-musl-gcc 

The error message:
/documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16 --cc=\${prefix}/bin/mipsel-openwrt-linux-musl-gcc --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --disable-silent-rules --libdir=\${prefix}/lib/ --libexecdir=\${prefix}/lib --disable-maintainer-mode --disable-dependency-tracking
using cache file config.cache
checking for OS or distribution... ok (Ubuntu)
checking for C compiler from CC env... ok (cached)
checking for C++ compiler from CXX env... ok (cached)
checking executable ld... ok (cached)
checking executable nm... ok (cached)
checking executable objdump... ok (cached)
checking executable strip... ok (cached)
checking for pkgconfig (by command)... ok (cached)
checking for install (by command)... ok (cached)
checking for PIC (by compile)... ok (cached)
checking for GNU-compatible linker options... ok (cached)
checking for GNU linker-script ld flag... ok (cached)
checking for __atomic_32 (by compile)... ok (cached)
checking for __atomic_64 (by compile)... ok (cached)
checking for socket (by compile)... ok (cached)
parsing version '0x000b00ff'... ok (0.11.0)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok (cached)
checking for zlib (by pkg-config)... failed
checking for zlib (by compile)... ok (cached)
checking for libcrypto (by pkg-config)... failed
checking for libcrypto (by compile)... ok (cached)
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for libssl (by pkg-config)... failed
checking for libssl (by compile)... ok (cached)
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... ok (cached)
checking for crc32chw (by compile)... ok (cached)
checking for regex (by compile)... ok (cached)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok (cached)
checking for strndup (by compile)... ok (cached)
checking for strerror_r (by compile)... ok (cached)
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok (cached)
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok (cached)
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           y
  ENABLE_SSL               y
  ENABLE_SASL              y
  HOST                     mips-*-*
  TARGET                   mipsel-linux
  includedir               /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/include
  mandir                   /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/share/man
  infodir                  /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/share/info
  DISABL_SILENT_RULES      y
  libdir                   /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/lib/
  libexecdir               /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/lib
  MKL_MAINT_MODE           n
  DISABL_DEP_TRACK         y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  LDFLAGS                  -L/documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/lib/
  CPPFLAGS                 -I/documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/include -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  MKL_DISTRO               Ubuntu
  SOLIB_EXT                .so
  CC                       ${prefix}/bin/mipsel-openwrt-linux-musl-gcc
  CXX                      
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.11.0
  MKL_APP_VERSION          0.11.0
  LIBS                     -lpthread -lz -lcrypto -lssl -lsasl2 -lrt -ldl
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16
  bindir                   /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/bin
  sbindir                  /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/sbin
  datadir                  /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/share
  sysconfdir               /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/etc
  sharedstatedir           /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/com
  localstatedir            /documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/var
Generated config.cache

Now type 'make' to build
----------------------------------------------------------------------------

Then after  the make command i have the following error message:
make[1]: Entering directory '/documents/librdkafka/src'
/documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/bin/mipsel-openwrt-linux-musl-gcc -MD -MP -I/documents/toolchain-mipsel_24kc_gcc-5.4.0_musl-1.1.16/include -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align  -c rdkafka.c -o rdkafka.o
In file included from rd.h:68:0,
                 from rdkafka_int.h:44,
                 from rdkafka.c:38:
rdposix.h: In function 'rd_strerror':
rdposix.h:98:16: warning: return makes pointer from integer without a cast [-Wint-conversion]
         return strerror_r(err, ret, sizeof(ret));
                ^
In file included from rdkafka.c:38:0:
rdkafka_int.h: At top level:
rdkafka_int.h:53:25: fatal error: openssl/ssl.h: No such file or directory
compilation terminated.
../mklove/Makefile.base:77: recipe for target 'rdkafka.o' failed
make[1]: *** [rdkafka.o] Error 1
make[1]: Leaving directory '/documents/librdkafka/src'
Makefile:20: recipe for target 'libs' failed
make: *** [libs] Error 2

Can you please help me fixing this problem
