### ISSUE TITLE
RdKafka::wait_destroyed must be called or not?

### ISSUE THREAD

**Issue by ZhiqiangCui** [edenhill/librdkafka#1652]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
RdKafka::wait_destroyed is required or not.

How to reproduce
================
I do not find a clear description, when RdKafka version > 0.9, RdKafka::wait_destroyed must be called or not. If we do not call this function, what will happen. :)
Thanks a lot.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (0.11.0): 
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You do not need to call wait_destroyed(), it no longer serves a purpose.
https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence
