### ISSUE TITLE
Several seconds latency when start consuming

### ISSUE THREAD

**Issue by Maverick04** [edenhill/librdkafka#1655]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I met a problem with librdkafka & rdkafka when using PHP to connect a broker. The problem is that，when start consuming, the first message is received immediately, however, the callback is really delayed, usually several seconds. I use strace to capture the system call of the main thread.  see the following:

16659 17:16:54.180723 <... gettimeofday resumed> {1517217414, 180624}, NULL) = 0 <0.000102>
**16659 17:16:54.180860 futex(0x26f6eac, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 3, {1517217423, 835624000}, ffffffff <unfinished ...>** 
**16659 17:17:03.835769 <... futex resumed> ) = -1 ETIMEDOUT (Connection timed out) <9.654893>**
16659 17:17:03.835826 futex(0x26f6e80, FUTEX_WAKE_PRIVATE, 1) = 0 <0.000029>
16659 17:17:03.836682 gettimeofday({1517217423, 836703}, NULL) = 0 <0.000011>
16659 17:17:03.836829 clock_gettime(CLOCK_MONOTONIC, {2179049, 590654187}) = 0 <0.000011>
16659 17:17:03.836884 clock_gettime(CLOCK_MONOTONIC, {2179049, 590715754}) = 0 <0.000017>
16659 17:17:03.836963 clock_gettime(CLOCK_MONOTONIC, {2179049, 590788746}) = 0 <0.000010>
16659 17:17:03.837007 gettimeofday({1517217423, 837021}, NULL) = 0 <0.000010>
**16659 17:17:03.837046 futex(0x26f6eac, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 5, {1517217433, 836021000}, ffffffff <unfinished ...>** 
**16659 17:17:05.640083 <... futex resumed> ) = 0 <1.803021>**

the master thread is waiting a signal before doing the callback until one child thread who receives message active the master thread. 

16674 17:17:05.639676 mprotect(0x7f05b8040000, 4096, PROT_READ|PROT_WRITE) = 0 <0.000013>
16674 17:17:05.639749 mprotect(0x7f05b8041000, 4096, PROT_READ|PROT_WRITE) = 0 <0.000017>
16674 17:17:05.639862 mprotect(0x7f05b8042000, 4096, PROT_READ|PROT_WRITE) = 0 <0.000013>
16674 17:17:05.639932 mprotect(0x7f05b8043000, 4096, PROT_READ|PROT_WRITE) = 0 <0.000016>
**16674 17:17:05.640020 futex(0x26f6eac, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x26f6ea8, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1 <0.000023>**
16674 17:17:05.640123 recvmsg(30,  <unfinished ...> 
16674 17:17:05.640223 <... recvmsg resumed> 0x7f05cabfc2f0, MSG_DONTWAIT) = -1 EAGAIN (Resource temporarily unavailable) <0.000086>

This leads a several seconds latency when restarting the consumer. Does anyone have ideas on this issue? Thanks!!

How to reproduce
1,set up a kafka cluster
2,send some messages
3,start a client and consume the message

librdkafka version: 0.92
rdkafka version:1.0.0
Language: PHP 5.5.38
OS: Linux lianjia 2.6.32-642.1.1.el6.x86_64
I changed the version of librdkafka&rdkafka to the latest, but it occurs all the way. 

Thanks Guys~~

**Comment by edenhill** [comment]
> The problem is that，when start consuming, the first message is received immediately, however, the callback is really delayed, usually several seconds. 

What callback is that?

**Comment by Maverick04** [comment]
The callback is really simple, just print the message and exit. 
    
public function uuuAction()
    {   
        $kafka_config = Context::getService('config')->kafka->newhindex->toarray();
        $kafka  = new Kafka($kafka_config);
        sleep(30);
        $kafka->consumeMsg([$this, 'handleMsg'], 'ttt', KafkaConst::TOPIC_CUSTOMER_REGISTER_UPDATE);
    }   
    public function handleMsg($msg)
    {   
        print_r(date('Y-m-d H:i:s'));
        $msg = json_decode($msg, true);
        print_r($msg);
        exit;
    }

**Comment by edenhill** [comment]
I think you'll need to file this issue on the php kafka project.

**Comment by Maverick04** [comment]
OK, Takk~
