### ISSUE TITLE
producer Sometimes slow

### ISSUE THREAD

**Issue by a285577011** [edenhill/librdkafka#1656]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
producer Sometimes slow 
Nearly 1 second
 I find it Time is spent on Received ProduceResponse 

How to reproduce
%7|1517291355.887|TOPPAR|rdkafka#producer-1| [thrd:211.149.162.241:9092/bootstrap]: 211.149.162.241:9092/0: Gula-ApiTest [6] 0+0 msgs
%7|1517291355.887|TOPPAR|rdkafka#producer-1| [thrd:211.149.162.241:9092/bootstrap]: 211.149.162.241:9092/0: Gula-ApiTest [0] 0+0 msgs
%7|1517291355.946|RECV|rdkafka#producer-1| [thrd:211.149.162.241:9092/bootstrap]: 211.149.162.241:9092/0: Received ProduceResponse (v3, 48 bytes, CorrId 3, rtt 59.29ms)
%7|1517291355.946|MSGSET|rdkafka#producer-1| [thrd:211.149.162.241:9092/bootstrap]: 211.149.162.241:9092/0: Gula-ApiTest [1]: MessageSet with 1 message(s) delivered

Checklist

$conf = new \RdKafka\Conf();
$conf->set('debug', 'all');
$conf->set('api.version.request', 'true'); // api请求版本
$producer = new RdKafka\Producer($conf);
$producer->setLogLevel(LOG_DEBUG);
$producer->addBrokers("211.149.162.241:9092");
$topicConf = new \RdKafka\TopicConf();
// 开启提交失败重复提交
$topic = $producer->newTopic("Gula-ApiTest",$topicConf);
$topic->produce(RD_KAFKA_PARTITION_UA, 0, "Messag");

**Comment by edenhill** [comment]
Checklist not filled out.
