### ISSUE TITLE
producer Sometimes slow

### ISSUE THREAD

**Issue by a285577011** [edenhill/librdkafka#1657]
Description
producer Sometimes slow
Nearly 1 second
I find it Time is spent on Received ProduceResponse

%7|1517292470.035|RECV|rdkafka#producer-1| [thrd:xxx:9092/bootstrap]: xxx:9092/0: Received ProduceResponse (v3, 48 bytes, CorrId 3, rtt 44.91ms)
rtt 44.91ms

**Comment by edenhill** [comment]
When you create an issue there is an issue template that we ask you to fill out.
Without the information requested we will not be able to help you.

Please open a new issue where you instead of removing the issue template you fill it out completely.
