### ISSUE TITLE
Build a long connection

### ISSUE THREAD

**Issue by Frank-AFN** [edenhill/librdkafka#1658]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Currently, I have a large amount data, it's about 200k /pps . I have to build a long connection and send them to kafka. So how to use it ?

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version : `0.11.0.x`
 - [x] Apache Kafka version: `0.8.2.3`
 - [ ] librdkafka client configuration: `"queue.buffering.max.messages", "10000000"`
 - [x] Operating system: `Centos 7 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is a standard use-case, just create a standard producer and produce your messages.

**Comment by Frank-AFN** [comment]
@edenhill Thanks for quick reply. I will try it.

**Comment by edenhill** [comment]
Make sure to upgrade to librdkafka 0.11.3, 0.11.0 had some problems.
You will most likely want to set `linger.ms` to `100` for optimal performance (fixed in next version)
