### ISSUE TITLE
 Protocol read buffer underflow

### ISSUE THREAD

**Issue by Frank-AFN** [edenhill/librdkafka#1660]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I got warning just like fowlling.
%3|1517371075.308|PROTOUFLOW|rdkafka#producer-1| [thrd:xx.xxx.xx.xx():9092/bootstrap]: xx.xx.xxx.xx:9092/5: Protocol read buffer underflow at 44/44 (rd_kafka_handle_Produce_parse:1751): expected 4 bytes > 0 remaining bytes (incorrect broker.version.fallback?)

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.1.x`
 - [ ] Apache Kafka version: `0.8.2`
 - [ ] librdkafka client configuration: `"queue.buffering.max.messages", "10000000"`
 - [ ] Operating system: `centos 7`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by Frank-AFN** [comment]
I set the property
	rd_kafka_conf_set(conf, "api.version.request", "false", errstr, sizeof(errstr));
But doesn't work.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility#broker-versions-08xy

**Comment by Frank-AFN** [comment]
Thanks, It works!!
