### ISSUE TITLE
Failed to produce to topic: xxxxx: Local: Queue full Failed

### ISSUE THREAD

**Issue by Frank-AFN** [edenhill/librdkafka#1661]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I meet the problem `Failed to produce to topic: xxxxx: Local: Queue full Failed` 
I have already set property queue.buffering.max.messages", "10000000"
But still useless.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.1.x`
 - [ ] Apache Kafka version: `0.8.2`
 - [ ] librdkafka client configuration: `queue.buffering.max.messages", "10000000`
 - [ ] Operating system: `centos 7`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Do you have a delivery report callback? If so, are you calling poll() at regular intervals?

**Comment by Frank-AFN** [comment]
retry:
	if (rd_kafka_produce(
			/* Topic object */
			rkt,
			/* Use builtin partitioner to select partition*/
			RD_KAFKA_PARTITION_UA,
			/* Make a copy of the payload. */
			RD_KAFKA_MSG_F_COPY,
			/* Message payload (value) and length */
			buf, len,
			/* optional key and its length */
			NULL, 0,
			/* Message opaque, provided in
			 * delivery report callback as
			 * msg_opaque. */
			NULL) == -1) {
		/**
		  * Failed to *enqueue* message for producing.
		  */
		cout << "Failed to produce to topic: " << rd_kafka_topic_name(rkt) << ": "
			 << rd_kafka_err2str(rd_kafka_last_error()) << endl;

		/* Poll to handle delivery reports */
		if (rd_kafka_last_error() == RD_KAFKA_RESP_ERR__QUEUE_FULL) {
			rd_kafka_poll(rk, 1000);
			goto retry;
		} else {
			cout << "Enqueue message " << len << " " << rd_kafka_topic_name(rkt) << endl;
		}
		rd_kafka_poll(rk, 0/*non-blocking*/);
	}

**Comment by Frank-AFN** [comment]
retry:
	if (rd_kafka_produce(
			/* Topic object */
			rkt,
			/* Use builtin partitioner to select partition*/
			RD_KAFKA_PARTITION_UA,
			/* Make a copy of the payload. */
			RD_KAFKA_MSG_F_COPY,
			/* Message payload (value) and length */
			buf, len,
			/* optional key and its length */
			NULL, 0,
			/* Message opaque, provided in
			 * delivery report callback as
			 * msg_opaque. */
			NULL) == -1) {
		/**
		  * Failed to *enqueue* message for producing.
		  */
		cout << "Failed to produce to topic: " << rd_kafka_topic_name(rkt) << ": "
			 << rd_kafka_err2str(rd_kafka_last_error()) << endl;

		/* Poll to handle delivery reports */
		if (rd_kafka_last_error() == RD_KAFKA_RESP_ERR__QUEUE_FULL) {
			rd_kafka_poll(rk, 1000);
			goto retry;
		} else {
			cout << "Enqueue message " << len << " " << rd_kafka_topic_name(rkt) << endl;
		}
		rd_kafka_poll(rk, 0/*non-blocking*/);
	}

**Comment by Frank-AFN** [comment]
I set this props. It works now thanks for your quick reply! 
	rd_kafka_conf_set(conf, "queue.buffering.max.kbytes", "1000000", errstr, sizeof(errstr));
