### ISSUE TITLE
What name means?

### ISSUE THREAD

**Issue by cystbear** [edenhill/librdkafka#1662]
Description
===========

Hi guys, what `RD` really means in lib`rd`kafka name?

**Comment by rolandyoung** [comment]
If you look at [Magnus's Github page](https://github.com/edenhill), you will see that he is the author of librd, a Rapid Development C utility library. 

So it apprears that librdkafka is a Kafka API build using the librd toolkit. It seems to be a pretty good advertisement for that toolkit.

**Comment by cystbear** [comment]
oh, thanks @rolandyoung !

**Comment by edenhill** [comment]
@rolandyoung is correct that librdkafka stems from librd.
librd itself was my toolbox that I brought along when doing C-based contracting gigs, it served its purpose well but it hasn't been maintained for years, there are still some gems in there though.

The 'rd' in librd stands for rapid (or rabid) development, but in librdkafka it may also be pronounced as 'libertykafka' as in 'free from JVM' (@jkreps' intepretation)
