### ISSUE TITLE
ERROR|rdkafka#producer-1|  request(s) timed out: disconnect (average rtt 

### ISSUE THREAD

**Issue by ranjitkumar2k10** [edenhill/librdkafka#1663]
Description
===========
I have c++ process which acts as producer for 1 topic and consumer for some other topic .

I have 1 kafka broker and  i increased the kafka partitions to 3 still i am facing this problem .

**some time c++ librdkafka producer is giving errors like this.**
%3|1517317005.596|FAIL|rdkafka#producer-1| [thrd:192.168.122.189:9092/1]: 192.168.122.189:9092/1: 783 request(s) timed out: disconnect (average rtt 17153.227ms)
%3|1517317005.596|ERROR|rdkafka#producer-1| [thrd:192.168.122.189:9092/1]: 192.168.122.189:9092/1: 783 request(s) timed out: disconnect (average rtt 17153.227ms)
%3|1517317007.532|FAIL|rdkafka#producer-1| [thrd:192.168.122.189:9092/1]: 192.168.122.189:9092/1: 1834 request(s) timed out: disconnect (average rtt 17137.621ms)
%3|1517317007.532|ERROR|rdkafka#producer-1| [thrd:192.168.122.189:9092/1]: 192.168.122.189:9092/1: 1834 request(s) timed out: disconnect (average rtt 17137.621ms)
%3|1517317010.564|FAIL|rdkafka#producer-1| [thrd:192.168.122.189:9092/1]: 192.168.122.189:9092/1: 15 request(s) timed out: disconnect (average rtt 17119.293ms)
%3|1517317010.565|ERROR|rdkafka#producer-1| [thrd:192.168.122.189:9092/1]: 192.168.122.189:9092/1: 15 request(s) timed out: disconnect (average rtt 17119.293ms)

How to reproduce
================
1. create test c++ program with kafka topic with sending 200 bytes of data and send 1000 messages/sec after some time this message will come.

NOTE: i have not created any test problem, i have already in build code which is doing the same.

Checklist
=========
librdkafka version v0.11.0
Apache Kafka version: v2.11-0.11.0.2

**Comment by edenhill** [comment]
You are getting some really bad rtt to the broker which could be caused poor batching on the producer:
Try setting `linger.ms=100` on the producer config and see if it helps
