### ISSUE TITLE
how to use librdkafka.dll on windows os?

### ISSUE THREAD

**Issue by leisuredev** [edenhill/librdkafka#1669]
how to use librdkafka.dll on windows os? please help me

**Comment by edenhill** [comment]
Reference the librdkafka.redist NuGet package from your VS project and it should sort itself out.

**Comment by leisuredev** [comment]
my project is php, i download php-rdkafka in this link http://pecl.php.net/package/rdkafka/3.0.5/windows
this download link include librdkafka.dll and php-rdkafka.dll
https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka.installation.windows.html
this installation guid just tell me how to use php-rdkafa.dll but no librdkafka.dll

**Comment by edenhill** [comment]
"sasl.mechanisms" was added over 2 years ago to librdkafka v0.9.0.
Are you attempting to set it on the Topic level config object?

**Comment by leisuredev** [comment]
it's the same error when i set "sasl.mechanisms" on the TopicConf


Fatal error: Uncaught RdKafka\Exception: No such configuration property: "sasl.mechanisms" in G:\development\Apache24\htdocs\kafka-consumer.php:13 Stack trace: #0 G:\development\Apache24\htdocs\kafka-consumer.php(13): RdKafka\TopicConf->set('sasl.mechanisms', 'PLAIN') #1 {main} thrown in G:\development\Apache24\htdocs\kafka-consumer.php on line 13

<?php
$setting = require __DIR__ . '/setting.php';
$conf = new RdKafka\Conf();


$conf->set('group.id', $setting['consumer_id']);

$conf->set('metadata.broker.list', $setting['bootstrap_servers']);

$topicConf = new RdKafka\TopicConf();

$topicConf->set('auto.offset.reset', 'smallest');
$topicConf->set('sasl.mechanisms', 'PLAIN');
$topicConf->set('api.version.request', 'true');
$topicConf->set('sasl.username', $setting['sasl_plain_username']);
$topicConf->set('sasl.password', $setting['sasl_plain_password']);
$topicConf->set('security.protocol', 'SASL_SSL');
$topicConf->set('ssl.ca.location', __DIR__ . '/ca-cert');

**Comment by edenhill** [comment]
It should be set on the global config object.
What librdkafka version is this?
