### ISSUE TITLE
How to consume an imbalanced topic ?

### ISSUE THREAD

**Issue by AkiChen** [edenhill/librdkafka#1670]
Description
===========
Hi, I’m using the C++ interface of librdkafka(RD_KAFKA_VERSION 0x000b00ff) and here is the background.

I have an imbalanced topic X to consume.
The producers of topic X use an imbalanced hash function to decide the output partition of each input message,
which leads to the biggest partition could have as much as 24 times of the messages in the least one.

In the phase of consuming this topic, I use two instances of RdKafka::KafkaConsumer ( on two separated machine) to consume  this topic.

One instance works fine with an acceptable lag of messages. While the other one, who is on duty of the biggest partition, might lag greatly on the largest partition, meanwhile, other smaller partitions are consumed well with little lag.

Sometimes, when the throughput of the biggest part increase rapidly, the lag of msgs keeps growing up fast, while the KafkaConsumer doesn’t read any messages.

The temporary solution is simple. I start another consumer only for the largest partition, and the lag is gone.

Finally, here is my question:
Do I need to apply consumer for each partition of an imbalanced topic ? Or, there might be some more elegant solutions ?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [ ] librdkafka version : `<v0.11.0>` 
 - [ ] Apache Kafka version: `<v0.10.1.0>`
 - [ ] librdkafka client configuration: `<api_version_request=true, queued_min_messages=100>`
 - [ ] Operating system: `<Centos 6>`

**Comment by edenhill** [comment]
This was an issue in librdkafka 0.11.0,it has since been fixed. Please upgrade to 0.11.3

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/issues/1384
