### ISSUE TITLE
Large value for fetch.wait.max.ms causes HeartbeatRequest message timeouts

### ISSUE THREAD

**Issue by DuncanSands** [edenhill/librdkafka#1671]
Description
===========

If you set fetch.wait.max.ms to a large value, then HeartbeatRequest messages timeout if there is no data arriving in the topic.

How to reproduce
================

./rdkafka_consumer_example -b some_broker some_topic -X fetch.wait.max.ms=300000 -q -d all 2>&1 | grep HeartbeatRequest

Run this for a topic with no data (so Fetch requests timeout).  Here's some example output:

1517822620.118 RDKAFKA-7-SEND: rdkafka#consumer-1: [thrd:kafka2:9092/2]: kafka2:9092/2: Sent HeartbeatRequest (v0, 97 bytes @ 0, CorrId 5)
1517822621.596 RDKAFKA-7-SEND: rdkafka#consumer-1: [thrd:kafka2:9092/2]: kafka2:9092/2: Sent HeartbeatRequest (v0, 97 bytes @ 0, CorrId 93)
1517822651.600 RDKAFKA-7-RETRY: rdkafka#consumer-1: [thrd:kafka2:9092/2]: kafka2:9092/2: Retrying HeartbeatRequest (v0, 97 bytes, retry 1/2)
1517822651.600 RDKAFKA-7-RETRY: rdkafka#consumer-1: [thrd:kafka2:9092/2]: kafka2:9092/2: Retrying HeartbeatRequest (v0, 97 bytes, retry 2/2)
1517822651.806 RDKAFKA-7-SEND: rdkafka#consumer-1: [thrd:kafka2:9092/2]: kafka2:9092/2: Sent HeartbeatRequest (v0, 97 bytes @ 0, CorrId 95)
1517822651.843 RDKAFKA-7-REQERR: rdkafka#consumer-1: [thrd:main]: kafka2:9092/2: HeartbeatRequest failed: Broker: Unknown member: explicit actions 0x0
1517822719.255 RDKAFKA-7-SEND: rdkafka#consumer-1: [thrd:kafka2:9092/2]: kafka2:9092/2: Sent HeartbeatRequest (v0, 97 bytes @ 0, CorrId 107)
1517822720.616 RDKAFKA-7-SEND: rdkafka#consumer-1: [thrd:kafka2:9092/2]: kafka2:9092/2: Sent HeartbeatRequest (v0, 97 bytes @ 0, CorrId 195)

In my case the broker is part of a three node cluster (kafka1, kafka2, kafka3) and I passed "-b kafka1".

The timeout occurs after 30 seconds, so maybe coming from session.timeout.ms?

Checklist
=========

 - [x] librdkafka version: 0.11.3
 - [x] Apache Kafka version: 1.0.0
 - [x] librdkafka client configuration: fetch.wait.max.ms=300000
 - [x] Operating system: Ubuntu 17.10 (x86)
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka

**Comment by edenhill** [comment]
librdkafka maintains one connection per broker, if the group coordinator and partition leader of a consumed partitions is the same broker then the FetchRequests will block HeartbeatRequests and OffsetCommitRequests.
To avoid Fetches blocking for too long, configure fetch.wait.max.ms to a low value (or keep the default).

**Comment by DuncanSands** [comment]
If I would to use a large value of fetch.wait.max.ms, is it enough to increase session.timeout.ms, or does fetch.wait.max.ms interact with some other timeouts?

By the way, I originally started playing with large values of fetch.wait.max.ms as I was seeing vast numbers of fetch requests when having many topics with many partitions (eg 40,000 fetches/sec) and I thought it might help.  But this issue, seen with 0.9.5, seems to have gone away with 0.11.3, so my fetch.wait.max.ms question is now only theoretical.

**Comment by edenhill** [comment]
fetch.wait.max.ms will block the connection for that long, worst case, which will block OffsetCommits and Heartbeats if the broker is the group coordinator.

**Comment by edenhill** [comment]
How many partitions are you consuming from a single consumer?

**Comment by DuncanSands** [comment]
One consumer consuming from about 2000 toppars worst case (which is what I was testing).  In practice I don't expect more than 200 toppars.  At the time I observed the vast number of fetch requests I was using fetch.wait.max.ms=100.  I was assuming that fetch requests were per toppar.  If you compute 2000 * (10 fetches per second) you get 20000/second; since there were two consumers doing the same thing, this would explain the 40000 fetches/second shown by the broker metrics.  However with 0.11.3 I don't see fetches per top-par, I see a small number of fetches per connection.  Did something change in how librdkafka works?

I've been playing with a fetch.wait.max.ms value of 1 minute (not the extreme value of 300000 I used in this ticket).  An offset commit delay of 1 minute is of no consequence in my use case.  If I want to go this route I guess I should increase heartbeat.interval.ms also to 1 minute, and increase session.timeout.ms to something like 3 minutes.

**Comment by edenhill** [comment]
Fetch requests are per broker, it will fetch all consumed partitions that have that broker as a leader through a single request. This has been the behaviour for a long time so I'm not sure why you're seeing a difference, could be some related issue that has been fixed.

Your logic regarding timeouts is correct, but I would be cautious using such long timeouts unless you really need to. While there is nothing wrong with it theoretically, in practice the majority of users and use-case use default values or slightly above. There are also really no tests for fetch.wait.max.ms that large, which could lead to you hitting various unforeseen corner case issues.

**Comment by DuncanSands** [comment]
Thanks for your advice (and all your hard work on librdkafka!): I'm going to put fetch.wait.max.ms back to the default given that it seems to work fine with 0.11.3.
