### ISSUE TITLE
"Error: Local: Authentication failure" with node-rdkafka

### ISSUE THREAD

**Issue by atulkumar-it** [edenhill/librdkafka#1673]
I ma using node-rdkafka 2.0.0 version. 
My application is trying to make connection with IBM MessageHub, Below are the config.
'security.protocol' : 'sasl_ssl',
	'ssl.ca.location' :  '/etc/ssl/certs',
	'sasl.mechanisms' : 'PLAIN',
	'api.version.request' : true,
	'compression.codec' : 'gzip',
	'retry.backoff.ms' : 1000,
	'message.send.max.retries' : 5,
	'socket.keepalive.enable' : true,
        'delivery.report.only.error' : false,
	'socket.timeout.ms' : 30000,
	'dr_msg_cb' : true,
	'dr_cb' : true,
	'log.connection.close': false

Kafka.librdkafkaVersion: 0.9.5 |  
Kafka.features: gzip,snappy,ssl,sasl,regex,lz4 | 

But I am getting below error:
{"message":"authentication failure","stack":"Error: Local: Authentication failure","origin":"local","code":-1,"errno":-1}

**Comment by atulkumar-it** [comment]
Once the application goes in disconnect mode, it never able to reconnect. Is there any way to recover the connection after its idle time passed?

**Comment by RaajBadra** [comment]
Have you figured out the issue ? I'm also facing the same issue now. Unable to connect to the IBM message hub.

**Comment by atulkumar-it** [comment]
It works for me.
I have used below configs:
        'client.id' : 'koneiot-dvcfeed-processor',
	'metadata.broker.list' : <<kafka_brokers_sasl>>,
	'security.protocol' : 'sasl_ssl',
	'ssl.ca.location' : '/etc/ssl/certs,'
	'sasl.mechanisms' : 'PLAIN',
	'sasl.username' : <<username>>,
	'sasl.password' : <<password>>,
	'api.version.request' : true,
	'compression.codec' : 'gzip',
	'retry.backoff.ms' : 1000,
	'message.send.max.retries' : 5,
	'socket.keepalive.enable' : true,
	'queue.buffering.max.messages' : 1000,
	'queue.buffering.max.ms' : 10,
	'batch.num.messages' : 1,
	'delivery.report.only.error' : false,
	'socket.timeout.ms' : 30000,
	'dr_msg_cb' : true,
	'dr_cb' : true,
	'log.connection.close': false
