### ISSUE TITLE
kafka_producev failing with dynamic topics

### ISSUE THREAD

**Issue by lathakris** [edenhill/librdkafka#1676]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
kafka produce is failing with "2018-02-07 22:35:54,532 shieldx user.notice cc: [INFO] <  cc>: % MESSAGE DELIVERY FAILED, error = Broker: Unknown topic or partition"

kafka version - 0.9.5

I am seeing an issue where the kafka produce is returning the error- "Broker: Unknown topic or partition".  I think this is happening with rd_kafka_producev() and mostly with dynamic topics which are created on the fly. In one scenario, I had 8 producers all producing on the same dynamic topic and 2 of them failed. The time lines indicate that these 2 sent out the produce message within 60 ms. of the consumer subscribing to the topic. The others sent out after about 100+ms and they succeeded. Do you think this is meta refresh issue ? I have not changed the meta refresh interval. Is there a way to fetch the meta on demand when I produce on the dynamic topics ? Are the messages sent too soon and hence failing ? (I get the dynamic topic name on another message and then produce on that topic.)

Also, I had changed the retries to 1000 times, with the default backoff as 100 ms (1000*100 = 100 seconds).  But then I see that the delivery call back comes back within 3 seconds with the above error. Does it mean that the retry logic did not work ? thought retries would help in this case.

Thank you so much for your response. 

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Could you try reproducing this on librdkafka master?

The retry handling is flaky in 0.9.5 and has been revised and revamped on master, a new release is scheduled for end of february.

**Comment by lathakris** [comment]
Oh ok thank you. I assume the latest 0.11.3 does not have this fix either. (since we need something in our release branch was wondering)

Also, if I use this retry fix, do you think it will address my issue though the meta refresh time is set to 5 minutes ? Thank you very much.

**Comment by lathakris** [comment]
I am running the tests with the master library, will update soon.

Also, is it that when produce fails, the meta is refreshed automatically (the config guide says will fetch on error and connect. Thank you,)

**Comment by edenhill** [comment]
Metadata is updated depending on the error, e.g., a ProduceRequest that fails with NotLeaderForPartition will trigger a Metadata request to figure out the new leader.

**Comment by lathakris** [comment]
I don't have any test results yet.

Then on this particular error which I am seeing the meta may not be refreshed, do you think I should reduce the refresh interval to handle these dynamic topics.  How are these kind of topics propagated to the clients ? Sorry for my ignorance on meta data refresh, I was trying to read but could not find much info. Thank you.  (We have a single instance in the cluster.)

**Comment by edenhill** [comment]
Hard to tell, we would need a reproduce log with `debug=msg,topic,metadata,protocol,broker` to know what is really going on.

**Comment by lathakris** [comment]
ok thank you I will try to reproduce the issue.. The only we saw when the issue happened was ==> 
Broker: Unknown topic or partition"

**Comment by lathakris** [comment]
any idea when the next release will happen ? did not see it so far in the private builds. Thank you.

**Comment by edenhill** [comment]
Within two weeks

**Comment by lathakris** [comment]
ok thank you.

**Comment by xfm18901105** [comment]
i have the same problems, the producer gets unknown partions error.

**Comment by edenhill** [comment]
@xfm18901105 could you try reproducing this on latest master or v0.11.4-RC1B?

**Comment by xfm18901105** [comment]
I have not tried the  0.11.4, 
but the problem is annoying, may I restart a producer to produce when I receive the unknown topic and partition error
The error appear interval about 3 days, so I’ve no way to get the debug infos.

**Comment by lathakris** [comment]
any updates on the release ?

**Comment by edenhill** [comment]
final RC going out today, hopefully release tomorrow

**Comment by lathakris** [comment]
ok thank you.

**Comment by lathakris** [comment]
should I use - v0.11.4-RC2 ?

**Comment by lathakris** [comment]
great saw the official release for - v0.11.4.

will upgrade to that and try in the official release... thank you.

**Comment by lathakris** [comment]
I have ungraded the system with this version. I am still running into this error. Not sure if the retry is working fine. I tried a couple of alternatives. 

1. Created a new producer handle and a conf handle. I changed the meta refresh time for this handle to 300 ms. Then tried producing on this handle on the dynamic topic. This also fails once in a while.

2. I fetch the meta just before producing on this dynamic topic (producing using kafka_producev) and it fails sometimes. I dumped the topics in the fetched meta, I do not see this dynamic topic. 

I then introduced a delay of 1 second and then fetched the meta (saw the dynamic topic in the topic list) and then did the produce. This seems to pass.

Not very convinced with this 1 second approach, any idea whats going on ? Thank you very much for your inputs.

**Comment by lathakris** [comment]
I would like to mention that auto create is disabled on the broker.

**Comment by edenhill** [comment]
@lathakris Can you write up a timeline? Something like:
 * timestamp: producer starts
 * timestamp: topic A is created (by admin tool)
 * timestamp: producev(topic_A) - returns what?
 * timestamp: delivery report - returns what?
 ...

**Comment by lathakris** [comment]
Thank you.

1. The producer starts pretty early.
2. The time difference between the time topic is created and producev produces on the topic is about 60ms,
3. producev returns success
4. delivery report returns "Broker: Unknown topic or partition"'

**Comment by edenhill** [comment]
I think this is a timing issue for newly created topics being partially reported by broker metadata, there is a fix in v0.11.5 for this case: 530498119969766099074829aab9fe83efdc991d

Could you try to reproduce with v0.11.5?

**Comment by lathakris** [comment]
ok sure I am using v0.11.4,  will upgrade to v0.11.5 and check it out and update. thank you.

(Now anyways I am fetching the metadata explicitly using the API call before producing on the topic, I am going to use this approach.)

**Comment by lathakris** [comment]
Can we use librdkafka client 0.11.5 with kafka server 2.0 ? Is this supported ? Thanks.

**Comment by edenhill** [comment]
Yes, see https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility
