### ISSUE TITLE
different producers for different topics 

### ISSUE THREAD

**Issue by ranjitkumar2k10** [edenhill/librdkafka#1677]
Description
===========
Hi,

I want to use 2 diffrent producer objects for 2 diffrent topics as one topic i want to use linger.ms=100 and other topic i dont want to use this paramter.

As it is a global configuration i can't set to only one topic.

Is it possible to create 2 producer instances and can use for 2 topics  in same executable ?

Checklist
=========
librdkafka version - latest master branch

**Comment by edenhill** [comment]
Yes, that's not a problem. Just make sure not to share objects between the two instances
