### ISSUE TITLE
unresolved ___iob_func for Visual Studio 2015

### ISSUE THREAD

**Issue by borneq** [edenhill/librdkafka#1678]
I have download librdkafka-0.11.3.zip and open win32/librdkafka.sln.
I have installed Win32OpenSSL-1_0_2n.exe in c:\OpenSSL-Win32.
Next, I try build librdkafka project. I have add legacy_stdio_definitions.lib and conditional _NO_CRT_STDIO_INLINE but this not helps.
I got errors:
Error	LNK2001	unresolved external symbol ___iob_func	librdkafka	D:\kod\kafka\librdkafka\win32\libeay32MT.lib(cryptlib.obj)	1

**Comment by edenhill** [comment]
That error usually means you are trying to link openssl statically with a mismatching msvcr version (120 vs 140).
OpenSSL was compiled for v120, but VS 2015 uses v140.
The workaround is to link OpenSSL dynamically by changing win32/librdkafka.vcxproj as so:
```
-    <LibraryPath>$(VC_LibraryPath_x64);$(WindowsSDK_LibraryPath_x64);C:\OpenSSL-Win64\lib\VC\static</LibraryPath>
+    <LibraryPath>$(VC_LibraryPath_x64);$(WindowsSDK_LibraryPath_x64);C:\OpenSSL-Win64\lib\VC</LibraryPath>^M
```
