### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by dinmil** [edenhill/librdkafka#1679]
I have problem with 2 different instances of my application, both are using same kafka topic (one partition, compact topic). Messages are large and compressed. Uncompressed message is about 500K in size. But compressed is about 50K. 
Consumer configuration is like that:

[sportfeedxml]
broker=sbkafka1.superbet.ro,sbkafka2.superbet.ro,sbkafka3.superbet.ro
topic=sportfeedxml_2

[sportfeedxml_conf]
group.id=sboffer_live_production001 (for stage is sboffer_live_stage001)
socket.keepalive.enable=true
socket.blocking.max.ms=1
socket.nagle.disable=true
queued.min.messages=5
queued.max.messages.kbytes=2097151
fetch.wait.max.ms=100
fetch.min.bytes=1
fetch.error.backoff.ms=1
message.max.bytes=100000000
enable.auto.commit=true
auto.commit.interval.ms=500
enable.auto.offset.store=true
auto.offset.reset=latest
receive.message.max.bytes=1000000000
api.version.request=true

One computer is on network with ping latency less then 1ms, the other one is less then 3 ms. Both computers are Win Server 2012 R2 with 16 GB RAM and 8 Cores. 

One computer is for production (less then 1ms) and the other one is stage (less then 3ms).
Application is the same and just read the messages as fast as it can with one reader. I think the network limit  is not the problem, CPU (20 % is used) and memory is not the problem. Production of messages is about 10 msg per second.

librdkafa is 11.3 from nuget win 64.

So, the problem is latency of messages which is not the same, and in production is worst then on stage (normally :-)) I measure the same message production time and receiving time and I get different and not even close values. Some messages are late up to 15 seconds, while the same message is late up to 3 seconds on stage environment.

We use Grafana and Prometheus to monitor latency and graph really show different behavior.
On example you can see that lag of messages (blue is production) is different then magenta (stage), and I can confirm that because I save timestamp in database and I can compare numbers.
Stage graph is more like flat line, while production graph is like steps and those steps goes into minus area of graph ???

So, the question is what can you see from configuration that can be cause of that problem (if you can see). Maybe some TCP params must be set in windows registry?

![example](https://user-images.githubusercontent.com/16936991/36067292-6b330d7e-0eba-11e8-9444-607f071dacf5.png)

**Comment by dinmil** [comment]
Funny thing happen. I switched consumer group names. Now production is stage and stage is production. And the lag behavior is now opposite. Production has no lag and stage has lag.
Can somebody explain what happens?

**Comment by edenhill** [comment]
How are you measuring latency?

**Comment by dinmil** [comment]
With ping command.
I found the problem. It seems that we have only 1 partition for topic (not 32 as it for default). If you have 2 consumers that read 1 partition then performance is dropping rapidly. Now we switched to only 1 reader and everything is OK. 
It seem that first connected consumer gets more attention from kafka server, and others only when first is finished and there is a time.

**Comment by edenhill** [comment]
I mean, how do you measure latency of the consumer?

**Comment by dinmil** [comment]
I'm sorry, I do not measure latency of messages on kafka level.
I measure on message content level.
Producer produce message (xml) and write timestamp.
One consumer receive message and write timestamp - I calculate difference.
Second consumer receive the same message and write timestamp - I calculate difference.

All 3 servers are time synchronized (difference can be maybe 10 or 20 ms)

First server receive message with 2 second difference and the other one is late up to 15 seconds for the same message. We receive lot of messages and we can calculate average latency. The difference is more then 500 ms.

**Comment by edenhill** [comment]
Try to break the latency down to understand where it adds up, start on the producer by calling rd_kafka_message_latency() from the delivery report callback to measure the time spent producing the message

**Comment by edenhill** [comment]
If you have more consumers (in the same group) than partitions there will be consumers without an assignment, this should not lead to performance problems.
Same with multiple consumers in different groups; the only performance impact should be the extra consumers.
But it sounds like the problem here is actually message sizes, how large are your messages?

It is generally advisable to keep messages under a meg, and if you need to propagate larger messages (such as files) you should put them in other storage and only send a link/ref through Kafka.

**Comment by dinmil** [comment]
We have one topic with one partition. There are 10 producers into this topic. There are two cosumers. Message is xml of 500KB. Message is compressed and it is about 20KB in size.

**Comment by dinmil** [comment]
Message is compressed by setting property on producer size. I do not know which size is counted. Compressed or uncompressed. If uncompressed then we have sometime message larger then 1 MB

**Comment by dinmil** [comment]
Yesterday we had an strange issue with kafka offset. It seems that after rebalancing conumers lost proper offset. Note that kafka topic is compacted. Here is the grafana lag picture. It seems that producers produced 800 000 messages in one second so consumer try to fetch them all all went out of memory. Wery strange situation because producers are producing not more then 10 messages per second, so counsumer lag is always on zero.
![img_24022018_220919_0](https://user-images.githubusercontent.com/16936991/36640062-d029b0de-1a18-11e8-952a-4ca1e112c0ca.png)

**Comment by dinmil** [comment]
Note that this consumer lag happen at the same time for some node.js application conusmers for different topics and they are not using librdkafka to fetch messages (they use kafka-node.npm) library.
