### ISSUE TITLE
TLS authentication without message encryption

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#1683]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
This is a question/clarification request: Is it possible to have TLS authentication but *not* encrypt the messages/data?

I have read the Kafka documentation, but I cannot be sure.

How to reproduce
================

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.3`
 - [x] Apache Kafka version: `1.0`
 - [x ] librdkafka client configuration: `security.protocol=ssl, ssl.ca.location, ssl.certificate.location, ssl.key.location, ssl.key.password`
 - [ ] Operating system: RedHat
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Yes, you should be able to pick a cipher that is supported both by your local openssl (which librdkafka uses) and the Kafka broker's JVM:
https://www.openssl.org/docs/man1.0.2/apps/ciphers.html
https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html
