### ISSUE TITLE
Local messages not timing out on Ubuntu

### ISSUE THREAD

**Issue by vmandke** [edenhill/librdkafka#1685]
Delivery callback is called on Mac OS, where as not in Ubuntu. Local messages timeout on MAC OS, where as they are not timing out on Ubuntu. Is this a known issue ?

` 

    def get_producer_client(self):
        # Complete configuration list https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md # noqa
        # Tune the Kafka producer to send out the message
        # as-soon-as it receive one
        return Producer({
            'client.id': 'leonardo',
            'bootstrap.servers': get_config('kafka', 'bootstrap.servers'),
            'batch.num.messages': 1,
            'queue.buffering.max.ms': 50,
            'topic.metadata.refresh.interval.ms': -1,
            'retries': int(get_config('kafka', 'retries')),
            'default.topic.config': {
                'acks': 'all',
                'message.timeout.ms': 600},
            'retry.backoff.ms': 1000,
            'max.in.flight.requests.per.connection': 1,
            'request.required.acks': 'all',]
            'produce.offset.report': False,
            'error_cb': self.on_generic_error})

    def delivery_callback(self, err, msg):
        if err:
            log('info', 'Message: {} to Kafka failed with {}'.format(msg, err))
            # Raise error to inform the worker
            raise KafkaException(err)
        else:
            log('info', 'Message sent to Kafka')

    def sync_produce(self, message):
        self.client.produce(self.topic,
                            bytes(json.dumps(message), 'utf-8'),
                            callback=self.delivery_callback)
        log('info', 'Message Produced on Kafka')
        # Block till the message ack is received
        log('info', 'Blocked on Kafka message ack')
        self.client.poll(timeout=1)
        self.client.flush(timeout=500)
`
MAC Setup:
/usr/local/Cellar/librdkafka/0.11.3 (14 files, 1.9MB) *
confluent-kafka==0.11.0

Ubuntu:
0.9.5~1confluent3.2.2-2
confluent-kafka==0.11.0

**Comment by edenhill** [comment]
The difference is most likely due to a much older librdkafka version on ubuntu: 0.9.5 vs 0.11.3 on osx.
Upgrade librdkafka on Ubuntu and you should be fine.

**Comment by vin18** [comment]
@edenhill the was the only available candidate on Ubuntu

https://packages.debian.org/source/jessie/librdkafka
apt-get install can only find till 0.8.3 
Ubuntu precise

**Comment by edenhill** [comment]
https://launchpad.net/ubuntu/+source/plank/0.11.3-2

Or build it yourself from source

**Comment by vin18** [comment]
built the 0.11.3 from source on Ubuntu. Still the local_message_timeout is not thrown.  Specifically the delivery_callback is not called.

**Comment by vin18** [comment]
Is there a way to explicitly check if there are messages on the local_message_queue (via confluent-kafka ) ?

**Comment by edenhill** [comment]
You can do `len(Producer)` to get the count of queued messages (and ops).

I suggest you reproduce this with `debug=topic,msg,broker,protocol` to see what is going on under the hood.

**Comment by eeepmb** [comment]
Any news on this? I'm facing a similar problem

**Comment by edenhill** [comment]
Most likely fixed on master:
https://github.com/edenhill/librdkafka/commit/4680d62c6a00e413bd361bf8a9f868c3bd4fd9ba

Next release due in about 3 weeks.

**Comment by eeepmb** [comment]
Wonderful! And thanks for the fast response too
