### ISSUE TITLE
Big latency of the first message produced

### ISSUE THREAD

**Issue by loskutov** [edenhill/librdkafka#1686]
Description
===========
Whenever I use the Producer API, the first produced message takes roughly `socket.blocking.max.ms` ms to call the corresponding callback. However, b84a437eb940c5f9e786e204b7256c6f436184ce marked this option as deprecated (and x10ed its default value), so I wonder if there's a way to decrease the latency in some other way.

How to reproduce
================
Produce a message once with the Producer C API (`rd_kafka_new()`, `rd_kafka_conf_set_dr_msg_cb()`, and `rd_kafka_produce()`, polling with frequent intervals and 0 timeout). With the default config, it takes about 1 second to get the `dr_msg_cb` called; the next messages, however, are served much faster.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.3`
 - [x] Apache Kafka version: `0.9.0.0`
 - [x] librdkafka client configuration: `api.version.request=false`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
what OS are you on?

**Comment by loskutov** [comment]
I'm on Linux

**Comment by edenhill** [comment]
Can you reproduce with `debug=all` and provide the logs?

**Comment by loskutov** [comment]
After the message is enqueued (I create a topic and then produce a message at once), I get the following output:
```
%7|1518632772.960|TOPBRK|rdkafka#producer-1| [thrd:ignat-Latitude-5480:9092/0]: ignat-Latitude-5480:9092/0: Topic mytopic [0]: joining broker (rktp 0x5634b555b7d0)
%7|1518632772.960|BROADCAST|rdkafka#producer-1| [thrd:ignat-Latitude-5480:9092/0]: Broadcasting state change
%7|1518632773.960|TOPPAR|rdkafka#producer-1| [thrd:ignat-Latitude-5480:9092/0]: ignat-Latitude-5480:9092/0: mytopic [0] 1+0 msgs
%7|1518632773.960|PRODUCE|rdkafka#producer-1| [thrd:ignat-Latitude-5480:9092/0]: ignat-Latitude-5480:9092/0: mytopic [0]: Produce MessageSet with 1 message(s) (33 bytes, ApiVersion 1, MsgVersion 0)
%7|1518632773.960|TOPPAR|rdkafka#producer-1| [thrd:ignat-Latitude-5480:9092/0]: ignat-Latitude-5480:9092/0: mytopic [0] 0+0 msgs
%7|1518632773.960|SEND|rdkafka#producer-1| [thrd:ignat-Latitude-5480:9092/0]: ignat-Latitude-5480:9092/0: Sent ProduceRequest (v1, 85 bytes @ 0, CorrId 2)
%7|1518632773.960|TOPPAR|rdkafka#producer-1| [thrd:ignat-Latitude-5480:9092/0]: ignat-Latitude-5480:9092/0: mytopic [0] 0+0 msgs
%7|1518632773.962|RECV|rdkafka#producer-1| [thrd:ignat-Latitude-5480:9092/0]: ignat-Latitude-5480:9092/0: Received ProduceResponse (v1, 35 bytes, CorrId 2, rtt 1.66ms)
%7|1518632773.962|MSGSET|rdkafka#producer-1| [thrd:ignat-Latitude-5480:9092/0]: ignat-Latitude-5480:9092/0: mytopic [0]: MessageSet with 1 message(s) delivered
%7|1518632773.962|TOPPAR|rdkafka#producer-1| [thrd:ignat-Latitude-5480:9092/0]: ignat-Latitude-5480:9092/0: mytopic [0] 0+0 msgs
```
After that, message is delivered.

I tried to write a minimal example, but it looks like I only encounter it inside my application (in the example, output is the same except there is no 1s gap) and I can't find out what causes the difference. Is there something particular that could cause this behavior?

**Comment by edenhill** [comment]
Can you provide some more logs, in particular all the logs leading up to that snippet?

**Comment by loskutov** [comment]
https://hastebin.com/ilusimofaw.rb

**Comment by edenhill** [comment]
Great, thanks!

```
%7|1518634762.114|METADATA|rdkafka#producer-1| [thrd:main]: ignat-Latitude-5480:9092/0: Caching full metadata with 1 broker(s) and 4 topic(s): connected
%7|1518634775.819|TOPIC|rdkafka#producer-1| [thrd:app]: New local topic: mytopic
```

This 13s pause is due to something in your application, right?

**Comment by loskutov** [comment]
Yes

**Comment by edenhill** [comment]
Workaround for now is setting `socket.blocking.max.ms=10`

**Comment by alexandrfox** [comment]
FTR we are also observing the same behaviour using 0.11.6 librdkafka version, the only workaround that helps is to set `socket.blocking.max.ms` to lesser value, even though documentation now states that this flag is unused (I do see in the code however that it was still used in this release).

**Comment by edenhill** [comment]
Can you give master or the latest v1.0.0-RC.. release a shot?
The scheduler has been improved and socket.blocking.max.ms is no longer used.
If you are looking at CONFIGURATION.md form the master branch it will match the next release, not a previous one (e.g., v0.11.6), you will need to change tag in github to look at the correct version, e.g:
https://github.com/edenhill/librdkafka/blob/v0.11.6/CONFIGURATION.md

**Comment by alexandrfox** [comment]
@edenhill appreciate your quick reply. Just tried out to recompile 1.0.0 RC3 and it seems that the issue is gone (ran a re-instantiated producer 1000 times without seeing 1s+ delivery report latencies), looking forward for release!

**Comment by edenhill** [comment]
That's great news!
We're looking to release within about 2-3 weeks
