### ISSUE TITLE
sasl_ssl plain password length

### ISSUE THREAD

**Issue by stefanhipfel** [edenhill/librdkafka#1691]
Description
===========
I am currently trying to connect to our brokers via sasl_ssl plain. Our password however has more than 255 chars. I saw in the [code](https://github.com/edenhill/librdkafka/blob/7972ec9906fbb545369769fa4a317f99ae442f26/src/rdkafka_sasl_plain.c#L88), that passwords are cut after a length of 255, so the client fails to connect. What are the reasons for this and can this be changed or made configurable?

The sasl plain [standard](https://tools.ietf.org/html/rfc4616) mentions: MUST accept up to 255 octets. But could it not also accept more than that, especially when the server you are trying to connect to, would allow it?

Maybe the library could throw an error, when one tries to use a password > 255 chars? It took us some time to figure out the problem we had with sasl_ssl.

Thanks in advance

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.1`
 - [x] Apache Kafka version: `0.11`
 - [x] librdkafka client configuration: 
`
    'debug': 'security',
    'security.protocol' : 'SASL_SSL',
    'ssl.ca.location': 'path/to/ca,
    'sasl.username': serviceCredentials.username,
    'sasl.password': 'password_with_more_than_255_chars',
    'sasl.mechanisms': 'PLAIN',
    'metadata.broker.list': cluster['brokers.auth_ssl'],
    "socket.timeout.ms": 15000,
    'socket.keepalive.enable': true
`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
And I have trouble remembering a 10 character password :|

I read those instructions as max 255, but you're right that it looks to be the lower limit.

I'll make a fix

**Comment by stefanhipfel** [comment]
Hi,

wow that was fast! Thanks a lot for your great support!! :)

**Comment by edenhill** [comment]
It'd be great if you could verify the fix in PR #1692 (saslcidlen branch)

**Comment by stefanhipfel** [comment]
I just did and it works (using the node-rdkafka lib on top). Thanks a lot!!

**Comment by stefanhipfel** [comment]
Hi,

when will this fix be available in the next release?

Thanks!!

**Comment by edenhill** [comment]
Release within 2 weeks
