### ISSUE TITLE
Messages loss when using compression snappy/gzip

### ISSUE THREAD

**Issue by koushikchitta** [edenhill/librdkafka#1695]
Description
===========
I see few messages lost when using snappy/gzip compression . Happens inconsistently , but seen majority of the time.
Is there something(or any other config) I'm missing ?

I see no errors logged at consumer end. or in the brokers

Please provide the following information:

 - [x] librdkafka version :  0.11
 - [ ] Apache Kafka version: 0.10.2
 - [ ] librdkafka client configuration:  
Producer config
    linger.ms:100
    batch.size:50000
    socket.send.buffer.bytes:50000000
    socket.receive.buffer.bytes:50000000
    compression.codec:gzip

Consumer config
    fetch.min.bytes:25000000
    socket.send.buffer.bytes:50000000
    socket.receive.buffer.bytes:50000000

 - [ ] Operating system:  Windows server 2016

**Comment by edenhill** [comment]
Do you have a delivery report callback registered?
That callback will be called once per message, either with success (err==0) or an error (err!=0).
The callback is triggered by calling rd_kafka_poll() at regular intervals.

If the partition exists but is unavailable messages will stay on the producer queue until the partition becomes available (leader comes up) or the message times out (message.timeout.ms).

**Comment by koushikchitta** [comment]
I'm using .net library and I've registered for callback. I see the message loss only with compression is enabled.
I'm sending 120 mil (6 producers) & no. of received messages doesn't match at consumer end (4 consumers) . I've tried with acks=all as well. I see ~3-4% loss of messages. None of the partitions were down during the test.

**Comment by edenhill** [comment]
Are you getting successful delivery reports for all produced messages before terminating the producers?

**Comment by koushikchitta** [comment]
I increment the message counter at each producer end only if the delivery report doesn't has any error.

**Comment by edenhill** [comment]
Can you show your produce and delivery report code just to verify?
Thanks

**Comment by koushikchitta** [comment]
try
                    {
                        int keyCount = 0;
                        while (keyCount < 250000  && currentMessageCount < messageCount)
                        {
                            var deliveryReport = producer.ProduceAsync(topics[0], keyCount, payload);
                            keyCount++;

                            deliveryReport.ContinueWith(task =>
                            {
                                if (task.Result.Error.HasError)
                                {
                                    logger.Info(task.Result.Error);
                                }
                                else
                                {
                                    currentMessageCount++;
                                }
                            }, ct);
                        }
                    }
                    catch (Exception exception)
                    {
                        logger.Error(exception);
                    }
                    finally
                    {
                        producer.Flush(TimeSpan.FromMilliseconds(100));
                    }

**Comment by edenhill** [comment]
And you are checking `currentMessageCount` after Flush() to get the number of actually produced messages? (as opposed to KeyCount or messageCount)

**Comment by koushikchitta** [comment]
yes I check  currentMessageCount .

**Comment by koushikchitta** [comment]
I'm using the .NET consumer. let me try reproducing this on 1 partition and verify the offsets.
Thanks for the suggestion.

**Comment by koushikchitta** [comment]
I see a producer offset difference doesn't match with no. of messages produced.
offset difference > no. of messages.

At consumer end, after consuming few messages. I see following error

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Confluent.Kafka.Impl.LibRdKafka.NativeMethods.rd_kafka_destroy(IntPtr rk)
   at Confluent.Kafka.Impl.LibRdKafka.destroy(IntPtr rk)
   at Confluent.Kafka.Impl.SafeKafkaHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()


I'll retest this to confirm that I can consistently reproduce above scenario

**Comment by edenhill** [comment]
The consumer crash looks like another issue.
If it is reproducible, open a new issue with `"debug":"all"` set and provide the last 100 lines of log.

**Comment by edenhill** [comment]
Regarding the producer issue:
 * Are you producing messages to a compacted topic?
 * Can you make a reproducible test case?

**Comment by koushikchitta** [comment]
Not writing to a compact topic. Following is the configuration used.

Topic config:
Topic:gzip_test2        PartitionCount:1        ReplicationFactor:3     Configs:compression.type=gzip
        Topic: gzip_test2       Partition: 0    Leader: 9       Replicas: 9,0,1 Isr: 9,0,1

Broker config:
log.cleaner.enable=true
log.cleaner.threads=8
log.cleaner.io.max.bytes.per.second=10000
message.max.bytes=10000000
log.index.interval.bytes=4096
log.index.size.max.bytes=10485760
log.roll.hours=168
log.flush.interval.messages=20000
log.flush.interval.ms=4000
log.flush.scheduler.interval.ms=2000
log.retention.hours=24
log.segment.bytes=1036870912
log.retention.check.interval.ms=120000
log.cleanup.interval.mins=2
log.cleanup.policy=delete


Will generate a reproducible test case.

**Comment by koushikchitta** [comment]
Opened a [new issue](https://github.com/edenhill/librdkafka/issues/1703) with a reproducible test
