### ISSUE TITLE
could not determine kind of name for

### ISSUE THREAD

**Issue by fcuencaML** [edenhill/librdkafka#1697]
Hi there, i have this problem
# github.com/confluentinc/confluent-kafka-go/kafka
./generated_errors.go:106:36: could not determine kind of name for C.RD_KAFKA_RESP_ERR__NOENT
./generated_errors.go:104:39: could not determine kind of name for C.RD_KAFKA_RESP_ERR__READ_ONLY
./generated_errors.go:108:40: could not determine kind of name for C.RD_KAFKA_RESP_ERR__UNDERFLOW
I updated librdkafka to 0.11.3. 
I dont know what's the problem :(

**Comment by edenhill** [comment]
Answered on Golang issue
