### ISSUE TITLE
Performance Regression 0.11.3

### ISSUE THREAD

**Issue by rthalley** [edenhill/librdkafka#1699]
Description
===========
After an update, some of our users reported a ~10x performance slowdown between 0.11.0 and 0.11.3 with the high level consumer when consuming from a consumer group.  Reverting the code back to 0.11.0 restored performance.

How to reproduce
================
I don't have an easy replication recipe.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.3
 - [x] Apache Kafka version: 0.10.2.0
 - [x] librdkafka client configuration: N/A
 - [x] Operating system: Centos 6
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: N/A
 - [x] Provide broker log excerpts: N/A
 - [x] Critical issue   yes, we had to roll back to 0.11.0.

**Comment by edenhill** [comment]
We usually hear the opposite report (because of errors in Fetch handling in 0.11.0).

If you could run `examples/rdkafka_performance -b <brokers> -G <unique-group> <topic1> <topic2>..` on a typical typic and compare the results between 0.11.0, 0.11.3 and master that would be great and give us something to go on.

**Comment by edenhill** [comment]
any updates?

**Comment by rthalley** [comment]
Sorry for the delay!  Here are some results


0.11.0

Note that msgs/s and MB/s were steadily increasing until the end of the test.

% 100000 messages (9576208911 bytes) consumed in 57717ms: 1732 msgs/s (165.91 MB/s)
% Average application fetch latency: 718us


0.11.3

Note that msgs/s and MB/s hit a low wall very early and stayed there
the whole time.

% 100000 messages (9608854012 bytes) consumed in 226995ms: 440 msgs/s (42.33 MB/s)
% Average application fetch latency: 2490us


master

Started pretty fast, got to around 2k msgs/s and 192 MB/s quickly and stayed
there.

% 100000 messages (9563984779 bytes) consumed in 49654ms: 2013 msgs/s (192.61 MB/s)
% Average application fetch latency: 717us

**Comment by edenhill** [comment]
Thank you!

Okay, that's good news, it seems to be fixed (again) on master.
v0.11.4 is due next week.

**Comment by edenhill** [comment]
The Producer performance was improved in v0.11.4 by optimizing the way message queues, backpressure and batching are handled.

The Consumer had a performance related bug that was fixed in 70d3d9fa80842e0808f952d966b20fc010c659f2
