### ISSUE TITLE
Missing documentation for `metadata_cache_cnt` statistics

### ISSUE THREAD

**Issue by ankon** [edenhill/librdkafka#1701]
https://github.com/edenhill/librdkafka/blob/e62a0d83d1ac4ffc1aa5fd8d736c67020882f0e7/src/rdkafka.c#L1003

**Comment by edenhill** [comment]
Thanks for pointing that out, that value is the number of topics in the metadata cache. It has little significance to the user but might come in handy for librdkafka devs when troubleshooting issues.

**Comment by edenhill** [comment]
Wiki updated

**Comment by ankon** [comment]
Thanks a lot! I'm currently building [a library that translates all statistics from rdkafka for prometheus](https://github.com/Collaborne/node-rdkafka-prometheus), and this one triggered warnings that the library didn't know what it was.

**Comment by edenhill** [comment]
Nice! Make sure to tell the node-rdkafka people when it is ready
