### ISSUE TITLE
Local: Message timed out

### ISSUE THREAD

**Issue by cumafo** [edenhill/librdkafka#1702]
Hej Magnus,
We are experiencing an issue almost identical to https://github.com/edenhill/librdkafka/issues/474.
Could it be a regression?

librdkafka v0.11.3-CI1
confluent-kafka-2.11  1.0.0-1
ubuntu 14.04/16.04
client configuration: default

Thanks

Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [x] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Please fill out the issue checklist and provide repro steps and logs.

**Comment by cumafo** [comment]
There is not distinct way to reproduce. We have about 30 lxc containers running on 3 servers. The problem occurs at reboot of on any container, maybe once by 10.

Logging all that comes from RdKafka::EventCb and RdKafka::DeliveryReportCb according to your example and all there are is from delivery report like: 
...
18-02-21T23:24:46 topic gelf 319 bytes: Local: Message timed out
..
Kafka server logs shows nothing.

Since there is an existing description of the problem (#474) I was just wondering if it's a regression.

**Comment by edenhill** [comment]
I don't believe there is a regression to #474.

It would be great if you could reproduce on latest librdkafka master with `debug=msg,topic,protocol,broker`.
We're looking to publish a release candidate tomorrow

**Comment by cumafo** [comment]
Working on it, already building from source. However, it is production system, so I'm a bit restricted..
