### ISSUE TITLE
Interpreting message key as C-String

### ISSUE THREAD

**Issue by billygout** [edenhill/librdkafka#1705]
In my application the producer sends in messages with the message key containing non-NUL-terminated text. In my consumer, I would like to operate on the message key, treating it as a C-String, and I'm trying to determine whether it is safe to treat the key buffer as NUL-terminated, or rather I need to copy the buffer into a new buffer and NUL-terminate it myself. With my limited testing, I have found empirically that the byte following the last byte in the message key (has been `malloc()`'d and) is `'\0'`, which makes me want to say this is a safe assumption but so far I've been unable to verify this is the case by looking at the librdkafka code. In other words, in the below snippet, if we get past the `if (msg->key() != NULL)`, then the inner expression is true. 

```
RdKafka::Message *msg = consumer->consume(1000);
if (msg->key() != NULL) 
    msg->key()->c_str()[msg->key_len()] == '\0' // <---- This expression is true
```

Can you please confirm or deny whether the code guarantees this? 

Thank you!

**Comment by edenhill** [comment]
`msg->key` is a `std::string` who's `c_str()` is guaranteed to be a nul-terminated string, so your assumption is true and safe.
