### ISSUE TITLE
offset.store.method=broker

### ISSUE THREAD

**Issue by dinmil** [edenhill/librdkafka#1706]
Description
Topic configuration for windows: offset.store.method=file does not work

How to reproduce
I want to save offset in local file , but I can not manage to do it
My configuration for topic.
offset.store.method=file
offset.store.path=g:\offset\
offset.store.sync.interval.ms=0

I tried g:\offset, g:\offset\, g:\\offset, g:\\offset\\
/offset, /offset/, g://offset, g://offset//

offset directory exists on proper place.
I tried with exact filename of offset file, but archived nothing

Kafka is 0.11
librdkafka is 0.11.3 from nuget web site

Any ideas?
It seems that it always save the offset on broker

**Comment by edenhill** [comment]
Are you setting `offset.store.method` on a topic config object, or on a global config object?
In the latter case, make sure it is not overwritten by a call to set_default_topic_conf().
If you are using confluent-kafka-dotnet I believe there was a recent bug that causes topic config properties set on the global object to be discarded.

**Comment by dinmil** [comment]
I 'm setting enable.auto.offset.store=true on global config object and
offset.store.method=file for specific topic. 
No error is returned when I do this settings in code.
I use librdkafka dll which is translated by myself into freepascal dll calls. Nothing special is done there since pascal calls are compatible with c calls.
There is project on github for freepascal https://github.com/dinmil/KafkaGate

**Comment by edenhill** [comment]
Topic properties can be set on the global config object only if they are not overwritten by a sub-sequent call to set_default_topic_conf or if topic_new() is called with a non-NULL config object.

**Comment by dinmil** [comment]
Sorry.
Only property enable.auto.offset.store=true is set on global config object.

Properties: 
offset.store.method=file 
offset.store.path=g:\offset\
offset.store.sync.interval.ms=-1
are set in topic configuration.

Maybe I should move enable.auto.offset.store=true into topic configuration also.

**Comment by edenhill** [comment]
Yes, you should, but in this specific case it doesn't matter because that value defaults to true
