### ISSUE TITLE
produce failed,and ip:port is changed to localhost:9092

### ISSUE THREAD

**Issue by tinux2015** [edenhill/librdkafka#1714]
**When I produce some msg to kafkaServer[255.10.10.10:9092], it's failed, and ip:port change to localhost:9092. And log as follow:**

1520235887.597 RDKAFKA-7-BRKMAIN: rdkafka#producer-1: [thrd::0/internal]: :0/internal: Enter main broker thread
1520235888.825 RDKAFKA-7-BROKER: rdkafka#producer-1: [thrd:app]: 255.10.10.10:9092/bootstrap: Added new broker with NodeId -1
1520235888.825 RDKAFKA-7-STATE: rdkafka#producer-1: [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
1520235888.826 RDKAFKA-7-BRKMAIN: rdkafka#producer-1: [thrd:255.10.10.10:9092/bootstrap]: 255.10.10.10:9092/bootstrap: Enter main broker thread
1520235888.826 RDKAFKA-7-TOPIC: rdkafka#producer-1: [thrd:app]: New local topic: KAFKA_TEST_01
1520235888.828 RDKAFKA-7-CONNECT: rdkafka#producer-1: [thrd:255.10.10.10:9092/bootstrap]: 255.10.10.10:9092/bootstrap: broker in state INIT connecting
1520235888.828 RDKAFKA-7-TOPPARNEW: rdkafka#producer-1: [thrd:app]: NEW KAFKA_TEST_01 [-1] 00520C78 (at rd_kafka_topic_new0:284)
[2018-03-05 15:44:48] : Begin write:partition[-1], partitionKey[13588888888][11]..
[2018-03-05 15:44:48] : Enqueued message (12 bytes) for topic KAFKA_TEST_01..
1520235888.836 RDKAFKA-7-CONNECT: rdkafka#producer-1: [thrd:255.10.10.10:9092/bootstrap]: 255.10.10.10:9092/bootstrap: Connecting to ipv4#255.10.10.10:9092 (plaintext) with socket 388
1520235888.837 RDKAFKA-7-STATE: rdkafka#producer-1: [thrd:255.10.10.10:9092/bootstrap]: 255.10.10.10:9092/bootstrap: Broker changed state INIT -> CONNECT
[2018-03-05 15:44:50] : Result of rd_kafka_poll:0...
1520235890.732 RDKAFKA-7-CONNECT: rdkafka#producer-1: [thrd:255.10.10.10:9092/bootstrap]: 255.10.10.10:9092/bootstrap: Connected to ipv4#255.10.10.10:9092
1520235890.732 RDKAFKA-7-NOINFO: rdkafka#producer-1: [thrd:main]: Topic KAFKA_TEST_01 partition count is zero: should refresh metadata
1520235890.732 RDKAFKA-7-CONNECTED: rdkafka#producer-1: [thrd:255.10.10.10:9092/bootstrap]: 255.10.10.10:9092/bootstrap: Connected (#1)
1520235890.734 RDKAFKA-7-FEATURE: rdkafka#producer-1: [thrd:255.10.10.10:9092/bootstrap]: 255.10.10.10:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
1520235890.734 RDKAFKA-7-STATE: rdkafka#producer-1: [thrd:255.10.10.10:9092/bootstrap]: 255.10.10.10:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
[2018-03-05 15:44:53] : Result of rd_kafka_poll:0...
1520235893.447 RDKAFKA-7-FEATURE: rdkafka#producer-1: [thrd:255.10.10.10:9092/bootstrap]: 255.10.10.10:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,Th
rottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4
1520235893.447 RDKAFKA-7-NOINFO: rdkafka#producer-1: [thrd:main]: Topic KAFKA_TEST_01 partition count is zero: should refresh metadata
1520235893.448 RDKAFKA-7-STATE: rdkafka#producer-1: [thrd:255.10.10.10:9092/bootstrap]: 255.10.10.10:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
[2018-03-05 15:44:53] : Result of rd_kafka_poll:0...
[2018-03-05 15:44:53] : Result of rd_kafka_poll:0...
[2018-03-05 15:44:53] : Result of rd_kafka_poll:0...
1520235895.318 RDKAFKA-7-BROKER: rdkafka#producer-1: [thrd:main]: localhost:9092/0: Added new broker with NodeId 0
[2018-03-05 15:44:55] : Result of rd_kafka_poll:0...
1520235895.318 RDKAFKA-7-STATE: rdkafka#producer-1: [thrd:main]: Topic KAFKA_TEST_01 changed state unknown -> exists
1520235895.320 RDKAFKA-7-PARTCNT: rdkafka#producer-1: [thrd:main]: Topic KAFKA_TEST_01 partition count changed from 0 to 5
1520235895.321 RDKAFKA-7-TOPPARNEW: rdkafka#producer-1: [thrd:main]: NEW KAFKA_TEST_01 [0] 0052AEE8 (at rd_kafka_topic_partition_cnt_update:511)
1520235895.322 RDKAFKA-7-TOPPARNEW: rdkafka#producer-1: [thrd:main]: NEW KAFKA_TEST_01 [1] 0052B520 (at rd_kafka_topic_partition_cnt_update:511)
1520235895.318 RDKAFKA-7-BRKMAIN: rdkafka#producer-1: [thrd:localhost:9092/0]: localhost:9092/0: Enter main broker thread
1520235895.324 RDKAFKA-7-TOPPARNEW: rdkafka#producer-1: [thrd:main]: NEW KAFKA_TEST_01 [2] 0052BB90 (at rd_kafka_topic_partition_cnt_update:511)
1520235895.325 RDKAFKA-7-CONNECT: rdkafka#producer-1: [thrd:localhost:9092/0]: localhost:9092/0: broker in state INIT connecting
1520235895.328 RDKAFKA-7-TOPPARNEW: rdkafka#producer-1: [thrd:main]: NEW KAFKA_TEST_01 [3] 0052C200 (at rd_kafka_topic_partition_cnt_update:511)
[2018-03-05 15:44:55] : Result of rd_kafka_poll:0...
1520235895.333 RDKAFKA-7-TOPPARNEW: rdkafka#producer-1: [thrd:main]: NEW KAFKA_TEST_01 [4] 0052CDA0 (at rd_kafka_topic_partition_cnt_update:511)
1520235895.335 RDKAFKA-7-METADATA: rdkafka#producer-1: [thrd:main]:   Topic KAFKA_TEST_01 partition 2 Leader 0
1520235895.336 RDKAFKA-7-BRKDELGT: rdkafka#producer-1: [thrd:main]: KAFKA_TEST_01 [2]: delegate to broker localhost:9092/0 (rktp 0052BB90, term 0, ref 2, remove 0)
1520235895.337 RDKAFKA-7-BRKDELGT: rdkafka#producer-1: [thrd:main]: KAFKA_TEST_01 [2]: broker localhost:9092/0 is now leader for partition with 0 messages (0 bytes) queued
1520235895.339 RDKAFKA-7-BRKMIGR: rdkafka#producer-1: [thrd:main]: Migrating topic KAFKA_TEST_01 [2] 0052BB90 from (none) to localhost:9092/0 (sending PARTITION_JOIN to localhost:9092/0)
1520235895.343 RDKAFKA-7-METADATA: rdkafka#producer-1: [thrd:main]:   Topic KAFKA_TEST_01 partition 4 Leader 0
[2018-03-05 15:44:55] : Result of rd_kafka_poll:0...
[2018-03-05 15:44:56] : Result of rd_kafka_poll:0...
**1520235896.345 RDKAFKA-7-BROKERFAIL: rdkafka#producer-1: [thrd:localhost:9092/0]: localhost:9092/0: failed: err: Local: Broker transport failure: (errno: Unknown error)
1520235896.351 RDKAFKA-7-STATE: rdkafka#producer-1: [thrd:localhost:9092/0]: localhost:9092/0: Broker changed state CONNECT -> DOWN
[2018-03-05 15:44:56] : MErrInfo: Local: Broker transport failure
1520235896.355 RDKAFKA-7-TOPBRK: rdkafka#producer-1: [thrd:localhost:9092/0]: localhost:9092/0: Topic KAFKA_TEST_01 [3]: joining broker (rktp 0052C200)**
[2018-03-05 15:44:56] : Unknown exception..

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

my kafkaServer is in linux,IP:PORT is 255.10.10.10:9092 , and my produceClient is in win7.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [0.11.x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [0.10.0.0 ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Your broker advertises itself as localhost.
See advertised.listeners, etc, in kafka broker configs.

**Comment by tinux2015** [comment]
yeah, it's worked ,thanks a lot
