### ISSUE TITLE
Non uniform wakeups and Transaction Bytes across Brokers and consumer lag build up

### ISSUE THREAD

**Issue by krishanfrog** [edenhill/librdkafka#1717]
Description
===========
I see that wakeups and transaction bytes are much higher (20x - 40x) in one broker than the rest of the brokers despite load on each broker being uniform and consumer lag rises abruptly over time

How to reproduce
================
1. Setup a cluster of 3 brokers (Replication factor is 3) and 200 partitions. Production rate is 100 messages per sec and each message size is ~4kb. The configuration in all 3 brokers is identical
2. I started 8 consumer processes. Each consumer gets equal share of partition assignment and is balanced across brokers
3. The wake up and transaction bytes broker stats are significantly different immediately.
3. After half an hour wakeups in broker 0 are 500k and for other 2 brokers are 25k. Transaction bytes in broker 0 are 25 million and 0.5 million in other 2 brokers. At this stage the consumption is working fine for all partitions with no lag.
4. After some random time (~6-8 hours) consumer lag starts building up randomly across partitions. It goes upto 20k for some partitions. upto 5k for some. upto 1k for some. All such partitions are only those which have their leaders assigned to broker 1 or broker 2. During this time the consumption is happening for some of these partitions from time to time. All partitions in broker 0 are perfectly fine and being consumed with no lag. The only error I see in logs are
```
[thrd:host:9092/bootstrap]: host:9092/1: Protocol parse failure at 228719/383381 (rd_kafka_msgset_reader_v2:802) (incorrect broker.version.fallback?)
[thrd:host:9092/bootstrap]: host:9092/1: topic [10] MessageSet at offset 211483 payload size 204822 > 154662 remaining bytes
[thrd:host:9092/bootstrap]: host:9092/1: Enqueue 12 message(s) (12 ops) on topic [10] fetch queue (qlen 12, v10, last_offset 211482)
```

After some more random time (~2-4 hours) the lag in these partitions starts clearing up and eventually goes to 0.

Don't know if the behaviours of wakeups/ transaction bytes and consumer lag are related but they seem to be.

Don't see any significant log in the broker during this time frame

Checklist
=========

- librdkafka version - 0.11.3
 - Apache Kafka version: 0.11.0.0
 - librdkafka client configuration: 
```
{ "metadata.broker.list": "broker-0:9092,broker-1:9092,broker-2:9092", 
"partition.assignment.strategy": "range", "enable.auto.commit": false, 
"fetch.message.max.bytes": 512000, "receive.message.max.bytes": 20480000, 
"max.in.flight.requests.per.connection": 1, "queued.min.messages": 1, 
"queued.max.messages.kbytes": 512000, "fetch.error.backoff.ms": 100, 
"enable.partition.eof": false, "socket.keepalive.enable": true,
 "debug": "metadata,cgrp,topic,fetch,queue,broker,protocol", 
"api.version.request": true, "broker.version.fallback": "0.11.0.0", 
"log.connection.close": false, "statistics.interval.ms": 60000 }
```
 - Operating system: Ubuntu 14.04

**Comment by edenhill** [comment]
Could you try to reproduce this on librdkafka master?

**Comment by krishanfrog** [comment]
Is this something that has been fixed in master? If so can you point me to the commit which fixed the issue. I will try reproducing after applying the patch

Asking because I am having some trouble updating to master. I am actually using node-rdkafka and updating only librdkafka breaks some dependencies there. Trying to debug it but its going to take some time.

**Comment by edenhill** [comment]
Is the broker with increased wakeups the group coordinator? That broker connection will have more traffic (heartbeats, commits, etc).

As for relevant fixes in 0.11.4, perhaps this: https://github.com/edenhill/librdkafka/issues/1623#issuecomment-356211569

**Comment by krishanfrog** [comment]
Yes it is the group coordinator. If this behaviour is expected then its fine.

Will try to reproduce it on master but the fix for #1623 looks like related to compression. I am not using any compression. Also the lag in my consumer keeps building up and the consumer doesn't consume any message until a significant time (~2-4 hours) unlike #1623 where consumption is slow but is happening.

Let me know if I am wrong in the above statements.

**Comment by edenhill** [comment]
This should be considered a bug, the solution is to use a dedicated connection to the coordinator so that commits, et.al, don't block consumption and vice versa.

As for consumer stalls, you'll need to set debug=cgrp,topic,fetch and reproduce the issue, providing the last 10000 lines of output from the log or so. Yes, it will be noisy.

**Comment by edenhill** [comment]
Also make sure to reproduce on v0.11.4
