### ISSUE TITLE
Question on specifying port with ipv6 address for broker

### ISSUE THREAD

**Issue by alpesh-arrcus** [edenhill/librdkafka#1722]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
Using librdkafka ver 0.11 for C on Linux (debian jessie)

I am trying to connect to a Kafka broker that is listening on a IPv6 address. The Address is 3333:10:9:101::204 and its listening on the default 9092 port.

In the producer code, the broker ip is constructed by concatenating the IP:port as described in documentation

What I see is connection failures with the message below

===========
[2018/03/13 21:55:46]**ERR**Kafka-log: 3, fac=FAIL, rk=rdkafka#producer-1, [thrd:3333:10:9:101::204:9092:9092/bootstrap]: 3333:10:9:101::204:9092:9092/bootstrap: Connect to ipv6#[3333:10:9:101::204:9092]:9092 failed: No route to host
[2018/03/13 21:55:46]**ERR** Kafka-log: 3, fac=ERROR, rk=rdkafka#producer-1, [thrd:3333:10:9:101::204:9092:9092/bootstrap]: 3333:10:9:101::204:9092:9092/bootstrap: Connect to ipv6#[3333:10:9:101::204:9092]:9092 failed: No route to host
2018/03/13 21:55:46]**ERR**Kafka-log: 3, fac=ERROR, rk=rdkafka#producer-1, [thrd:3333:10:9:101::204:9092:9092/bootstrap]: 1/1 brokers are down###########################################################

**The port 9092 seems to be getting appended twice resulting in an incorrect ip.**

If I change the producer code to pass in just the IPv6 address without specifying port, everything works fine, ie, connection completes and messages are delivered successfully.

In the server.properties file of Kafka server, the listeners and advertised.listeners are configured as follows
listeners=PLAINTEXT://3333:10:9:101::204:9092
advertised.listeners=PLAINTEXT://3333:10:9:101::204:9092

So my question is
Is this a bug in librdkafka related to parsing IPv6 address?
OR
Is there a different way to specify the port for IPv6 addresses for the "bootstrap.servers" parameter? Maybe there is a different separator between ipv6 address and port?

I could not find anything in FAQ or google. But this seems like basic issue so I suspect the latter 

For IPv4 addresses, using ip:port format works correctly.

How to reproduce
================
Pls see above

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: Pls see above
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Since IPv6 uses `:` as a separator within the address it can't be used like in IPv4 to directly append a port, instead you'll need to wrap the IPv6 address in brackets and then append `:port`, like so:
`[3333:10:9:101::204]:9092`.

https://tools.ietf.org/html/rfc5952#section-6

If the broker parses `3333:10:9:101::204:9092` as address `3333:10:9:101::204` plus port `9092` then that's a bug in the broker that needs to be fixed (open a [JIRA](jira.apache.org))

**Comment by alpesh-arrcus** [comment]
Thank you Magnus !!
Using the [IP]:port works both IPv4 and IPv6 addresses. 

Maybe FAQ or documentation can be updated to clarify this?
