### ISSUE TITLE
Not received delivery report for failure scenario while calling rd_kafka_produce_batch

### ISSUE THREAD

**Issue by karthikeyanajendran1984** [edenhill/librdkafka#1723]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We have implemented a batch message publishing in synchronous way (i.e waiting for delivery report for all the messages.) We are fine with Success scenario by publishing 10K messages in one batch call and got delivery report for all messages in a second. But for the failure scenario like Unknown Topic or Partition, We are not receiving the delivery report and in our code we are checking delivery report count should be received for all messages by having one static counter say MessageDeliveryCount and the same we check in loop. But for the failure scenario, it went to infinite loop because of not receiving delivery report. 

1) I have one solution to achieve Unknown topic and partition by fetching the metadata information before publish call and find the same. Please confirm if this is fine and achievable ?
2) I would like to know what are the other failure scenario i can verify to receive the delivery report ? (Currently delivery report not received both Unknown Topic and Partition )
3) Am i able to receive delivery report for other failure scenarios from librdkafka ?
4) The return value of batch produce gives the number of messages successfully published, In this case I am assuming the partial message publish happens only for  -184 Local: Queue full scenario and not of any other scenario ? Please confirm

How to reproduce
================
As mentioned we have implemented a synchronous batching to receive acknowledgement for each call, we set the below configurations as per previous issue #1651 i raised before.
1) request.required.acks = 1
2) max.in.flight = 1 (wait for a Delivery Report before producing again)
3) message.send.max.retries = 100000 (let librdkafka handle all the retry logic)
4) queue.buffering.max.ms =0 
5) batch.num.messages = 500 ( as this is not valid and no meaning )
6) message.timeout.ms = 2000
Start our application trekafka(i. e produce API) by registering delivery report and produce batch messages contains 100 messages at one call
Give the correct topic name but gave the wrong partition number which is not available in Kafka server
Wait for the delivery report and the delivery report has not received.

NOTE : For a success scenario 10K at one call, delivery report has been received for all the messages published.
--

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version : librdkafka-0.11.0
 - [x] Apache Kafka version: `kafka_2.11-0.11.0.0`
 - [x] librdkafka client configuration: `request.required.acks = 1, max.in.flight = 1, message.send.max.retries = 100000,  queue.buffering.max.ms =0, batch.num.messages = 500, message.timeout.ms = 2000)
 - [x] Operating system: `Linux 2.6.39-200.24.1.el6uek.x86_64`
 - [x] Provide logs - not have librdkafka logs, If required i can give.
 - [ ] Provide broker - 
 - [x] Critical issue - Not major, but still require for failure scenario to get the delivery report.

**Comment by edenhill** [comment]
I think this is related to buggy producer retry handling in previous versions of librdkafka.

Can you try to reproduce this on latest master or v0.11.4-RC1B ?

**Comment by karthikeyanajendran1984** [comment]
Thanks for the quick reply. I will test the same in v0.11.4-RC1B and let you know.

**Comment by karthikeyanajendran1984** [comment]
Can u please provide me the link to download that particular version.

**Comment by karthikeyanajendran1984** [comment]
Got it. Thanks.

**Comment by karthikeyanajendran1984** [comment]
In the mean time, Can u please confirm the below 

The return value of batch produce gives the number of messages successfully published, In this case I am assuming the partial message publish happens only for -184 Local: Queue full scenario and not of any other scenario ? Please confirm

**Comment by edenhill** [comment]
produce_batch() returns the number of messages accepted and that you will eventually get a delivery report for.
If the return value is less than the number you pass to produce_batch() you need to go through your messages array and check the error code of each message, if it is non-zero the message was not accepted and there will be no delivery report for that message.

**Comment by karthikeyanajendran1984** [comment]
I tried testing the scenario in later master branch and the issue is not reproduced.
It worked as expected as we receive the Unknown Topic or Partition on rkmessage structure which is fine.
But our organization download the maintenance release (standard) version when we started work for kafka development. As i see now the current maintenance release v0.11.3 (https://github.com/edenhill/librdkafka/releases) is not working as expected and the issue has been reproduced and still there with v0.11.3. 
Is it possible know when is the next maintenance release to avail this fix ?

Also can you please confirm the following 
1) If we are not taking the master branch as of now, the respective Unknown partition and topic can fixed through other way by availing metadata information before publish. But is there any other failure scenario this issue  can occur ? 
2) it is recommended to take the latest version to use ?
3) I would like to know what are the other failure scenario i can verify to receive the delivery report ?

**Comment by edenhill** [comment]
We'll release librdkafka v0.11.4 early next week.

You should typically consider all delivery report errors as fatal, given that you've configured librdkafka with the appropriate message.timeout.ms and message.send.max.retries.

**Comment by edenhill** [comment]
That does sound like a regression, I will check it out. Thanks!

**Comment by karthikeyanajendran1984** [comment]
OK. It would be great if you can make sure this fix also to be part of coming maintenance release.

**Comment by edenhill** [comment]
I can't reproduce this behaviour:
I've modified the produce_batch tests (tests/0011...c) to fail the last 10% of messages due to QUEUE_FULL, but the return value from batch() is correct (90%).

Could you provide a small reproducible test case / example application?

**Comment by karthikeyanajendran1984** [comment]
Sorry, Please ignore this issue. Its issue with our code and testing.
