### ISSUE TITLE
clarify about timeout_ms in KafkaConsumer.consume() 

### ISSUE THREAD

**Issue by XiaoyaoFan** [edenhill/librdkafka#1724]
Description
===========
Hi,

The definition of the function is virtual Message *consume (int timeout_ms) = 0;
And it's the explanation of timeout_ms: timeout_ms is maximum amount of time to wait for a message to be received.

Question 1:  The timeout_ms is about the max wait time to retrieve a message from librdkafka's local message queue, not the time to retrieve from broker, right? The time from broker is depended on configs like "fetch.wait.max.ms", "fetch.message.max.bytes" etc.
Question 2:  Can we wait infinitely until there is message on queue? If yes, what value should set to timeout_ms?

Thanks in advance for your answer!

**Comment by edenhill** [comment]
Q1. Yes, you are correct, this is the timeout for the internal fetchq. Messages are being fetched from the broker in a background thread and added to this queue regardless of consume timeout.
Q2. Yes, you can pass timeout_ms=-1 to wait indefinitely.

**Comment by XiaoyaoFan** [comment]
Thanks very much, and I'm clear with now.

**Comment by XiaoyaoFan** [comment]
@edenhill Hi, I have 2 more questions on consume() when set timeout_ms=-1, thanks in advance for your response.

Q3: If there is no more message(eg. end of partition), how to terminate the infinite wait for consumer()?

Q4: In the function description:  "An application should make sure to call consume() at regular intervals, even if no messages are expected, to serve any queued callbacks waiting to be called". If there is no more message, will the potential callbacks are also blocked due to infinite wait on consume() (because we can't call it in regular intervals)?

**Comment by edenhill** [comment]
Q3. Not currently possible. https://github.com/edenhill/librdkafka/issues/614
   Workaround: don't use infinite timeouts.

Q4. The callbacks will be served by consume(), regardless of timeout.

**Comment by XiaoyaoFan** [comment]
Thanks for your prompt reply.

For Q4, if consume() is keeping waiting infinitely, then we can't promise it'd be called at regular intervals, will it impact the callbacks? If no impact, can I say as long as I call consume() at least once, the callbacks will be served properly?

And I'm also curious about how librdkafka serve the callbacks, like how it receives an event(or a message which represents an event) from broker, and where are these callbacks queued?
