### ISSUE TITLE
how to make rd_kafka_produce quick compare with writing local file ?

### ISSUE THREAD

**Issue by Johnny-Three** [edenhill/librdkafka#1725]
I use the newest version of 11.04
my conf is : 
    rd_kafka_conf_set(conf, "queue.buffering.max.ms", "1", NULL, 0); 
    rd_kafka_conf_set(conf, "socket.blocking.max.ms", "1", NULL, 0);
    rd_kafka_conf_set(conf, "batch.num.messages", "100", NULL, 0);
    rd_kafka_conf_set(conf, "request.required.acks", "1", NULL, 0);
    rd_kafka_conf_set(conf, "compression.codec", "lz4", NULL, 0);

and when frequently call code below it will cost some time : 
if (rd_kafka_produce(rkt, partition, RD_KAFKA_MSG_F_COPY, (char *) message, len, NULL, 0, NULL) == -1) {
            fprintf(stderr, "%% Failed to produce to topic %s partition %i: %s\n", rd_kafka_topic_name(rkt), partition,
                    rd_kafka_err2str(rd_kafka_last_error()));
        }
seems the api rd_kafka_produce is not a real asynchronous way ? 
cause I found when compare with write the message into local file , seems no time saving .
can show me the right way  to call rd_kafka_produce cost less time ?
thanks in advance!

**Comment by edenhill** [comment]
Need more info:
 * how long does each call take?
 * does the time vary?
 * what's your typical message size?
 * what hardware/instance type is this running on?
 * what's the CPU usage with and without the producer running?

**Comment by Johnny-Three** [comment]
Sorry to answer late . 
After some tests , I change the config like this : 
rd_kafka_conf_set(conf, "queue.buffering.max.ms", "0", NULL, 0);
rd_kafka_conf_set(conf, "queue.buffering.max.messages", "1000000", NULL, 0);
rd_kafka_conf_set(conf, "delivery.report.only.error", "true", NULL, 0);
rd_kafka_conf_set(conf, "socket.blocking.max.ms", "1", NULL, 0);
rd_kafka_conf_set(conf, "batch.num.messages", "100", NULL, 0);
 rd_kafka_conf_set(conf, "request.required.acks", "1", NULL, 0);
 rd_kafka_conf_set(conf, "compression.codec", "lz4", NULL, 0);

And program seems work well .

But still something unclear when using rd_kafka_produce api .
I make parameter "queue.buffering.max.messages" much smaller , for example 1000 . 
And then turn down  the kafka server . 
librdkafka client says : 192.168.180.104:9091/1: Connect to ipv4#192.168.180.104:9091 failed: Connection refused . 
But then I push high volume messages by using  rd_kafka_produce .
code like this:
if (rd_kafka_produce(rkt, partition, RD_KAFKA_MSG_F_COPY, (char *) serialized_string, strlen(serialized_string), NULL, 0, NULL) ==
            -1) {
            fprintf(stderr, "%% Failed to produce to topic %s partition %i: %s\n", rd_kafka_topic_name(rkt), partition,
                    rd_kafka_err2str(rd_kafka_last_error()));
        }
no error prints . 
That confused me . 
Does the librdkafka abandon the input messages automatically when the internal queue is full ? 
Actually I need this feature but do not know how to make it happen (automatically abandon messages when the internal queue is full )
Thanks in advance !

**Comment by Johnny-Three** [comment]
and I try to set a poll function for it .
But I got Error  Failed to produce to topic XX-HTTP-KEYWORD-LOG1 partition -1: Err--655589048?
when I set queue size to 1000 and then make high volume messages . 
Found no messages consumes . 
Need Help .
