### ISSUE TITLE
rd_kafka_consumer_poll is not calling registered consumer_cb function

### ISSUE THREAD

**Issue by devjin22** [edenhill/librdkafka#1726]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I upgraded librdkafka library from v0.9.1 to v0.11.3. After the upgrade, I am observing that my existing implementation of periodically calling rd_kafka_consumer_poll API, which would internally call consumer_cb, is broken.

Now I need to rely on message returned from rd_kafka_consumer_poll and call the callback function explicitly. This has slowed down by consumer, as previously single call to rd_kafka_consumer_poll would result into multiple callback function execution.

How to reproduce
================

1. Write a new consumer by registering consumer_cb function using rd_kafka_conf_set_consume_cb. 
2. Run a periodic timer, which on expiry would call rd_kafka_consumer_poll API.
3. consumer_cb won't get called.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.3
 - [ ] Apache Kafka version: 1.0.0
 - [ ] librdkafka client configuration: rd_kafka_conf_set_consume_cb, and consumer group.id
 - [ ] Operating system: Ubuntu
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
As a workaround could you try?:
```
// after consumer_set_poll() get the consumer queue
rd_kafka_queue_t *queue = rd_kafka_queue_get_consumer(rk);


// ... and then in your consumer loop instead of consumer_poll() use:
rd_kafka_queue_poll_callback(queue, your_timeout);
```

**Comment by devjin22** [comment]
I gave it a try. Consumer_cb is getting called but with a side effect. Side effect is error callback is getting called with "Broker: No more messages".

**Comment by edenhill** [comment]
You can silence PARTITION_EOF by setting `enable.partition.eof=false`

**Comment by devjin22** [comment]
Ok. it is now working properly.
