### ISSUE TITLE
High Fetch latency for some partitions

### ISSUE THREAD

**Issue by krishanfrog** [edenhill/librdkafka#1729]
Description
===========

I see high fetch latency in 2 partitions out of 200. Production rate is same across partitions. In 198 partitions the consumption latency is the same (~ 1 sec). In 2 partitions the consumption latency is skewed (between 1 - 30 secs)

After enabling debug logs on the consumer I see that "CONSUME" log occurs nearly every second for every partition.

But in these 2 partitions the "CONSUME" log gets stuck for some time (~30 secs) before the next log for that partition (the "FETCH" message) which could be the holdup. This holdup does not occur every-time but randomly (approximately every minute - So it fetches messages every second except when the hold up happens)

Broker and Topic Configuration -
1. 4 brokers. Each broker is a leader of 50 partitions and replication factor is 3. Leader assignment for brokers is range (0-49 : Leader Broker 1, 50 - 99: Leader Broker 2, 100 - 149: Leader Broker 3, 150 - 199: Leader Broker 4)
2. Broker 4 is leader of consumer offsets and Broker 2 is the replica for the same
3. Only Partition Numbers 50 and 99 are showing the skew

Have attached the logs between "CONSUME" and "FETCH" logs. The time between them is 30 secs in this case.

Checklist
=========

 - librdkafka version - master (c319b4e987d0bc4fe4f01cf91419d90b62061655)
 - Apache Kafka version: 1.0.1
 - librdkafka client configuration: 
 - Debug Logs - [Logs-17thMarch-partitionLag.zip](https://github.com/edenhill/librdkafka/files/1821792/Logs-17thMarch-partitionLag.zip)

```
{"partition.assignment.strategy": "range", "enable.auto.commit": false, 
"fetch.message.max.bytes": 512000, "receive.message.max.bytes": 20480000, 
"max.in.flight.requests.per.connection": 1, "queued.min.messages": 1, 
"queued.max.messages.kbytes": 512000, "fetch.error.backoff.ms": 100, 
"enable.partition.eof": false, "socket.keepalive.enable": true,
 "debug": "metadata,cgrp,topic,fetch,queue,broker,protocol", 
"api.version.request": true, "broker.version.fallback": "0.11.0.0", 
}
```
 - Operating system: Ubuntu 14.04

**Comment by krishanfrog** [comment]
On digging deeper found the issue.

One client connection was assigned to partitions 99,100,101. Broker 2 is leader of 99 and broker 3 is leader of 100 and 101

Similar behavior for other case. One client connection was assigned to 48,49,50. Broker 1 is leader of 48 and 49 and broker 2 is leader of partition 50.

If I change the leaders of the partitions such that clients always consume partitions from same broker, the latency is consistent. 

So the consumption latency changes drastically if consuming from different brokers. 

Is this an expected flow @edenhill? Is this fixable? Because this limits the flexibility on partition assignment.

**Comment by edenhill** [comment]
What happens if you set `fetch.error.backoff.ms` to 0?

Also, your config is pretty aggressive in minimizing the number of messages queued, ruining the case for prefetching messages (which evens the flow and increases throughput).
I generally advise using queue config default values unless there is a clear use-case not to, they are designed to cover most use-cases and also make it easier to reason about anomalies.

**Comment by krishanfrog** [comment]
If I set queued.min.messages to 100 the latency improves drastically to 200 ms. Also there is no variation in latency across partitions. 

I had actually expected latency to be higher by increasing this value but looks like this config fixes the issue.
