### ISSUE TITLE
kafka partition can not larger than 1000?

### ISSUE THREAD

**Issue by hitljs** [edenhill/librdkafka#173]
Hi, when i set kafka server's partition larger than 1000, using librdkafka will not send any message to kafka/

**Comment by edenhill** [comment]
Is your problem solved?

**Comment by hitljs** [comment]
Yes，in 0.8.5 version you provide a larger number, but still hard code .

**Comment by edenhill** [comment]
The current max is 10000 partitions per topic (and max 10000 topics).

Is this number sufficient for you now and in the foreseeble future?
(Having more than 1000 partitions is usually not recommended in Kafka)

**Comment by hitljs** [comment]
it fits me well, and my kafka-server partition would not larger than 10000

**Comment by edenhill** [comment]
Perfect, thakns
