### ISSUE TITLE
Can't build with gcc

### ISSUE THREAD

**Issue by ilanoh** [edenhill/librdkafka#1730]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hello,
I receive issue type :  undefined reference to `LZ4F_getErrorName'
I think it may be linked to librairies.

Here is what I call

-L ../utils -lutils -L ../network -lnetwork -Wl,-Bstatic -lev -ljansson -lmpdec -lrdkafka -lrdkafka++ -lz -lssl -lcrypto -lhiredis -Wl,-Bdynamic -lm -lpthread -ldl -lcurl

If anyone can advise ?

Thank you

The entire error look like this :

` //usr/local/lib/librdkafka.a(rdkafka_lz4.o): In function `rd_kafka_lz4_decompress':
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:184: undefined reference to `LZ4F_createDecompressionContext'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:185: undefined reference to `LZ4F_isError'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:203: undefined reference to `LZ4F_getFrameInfo'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:204: undefined reference to `LZ4F_isError'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:303: undefined reference to `LZ4F_freeDecompressionContext'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:304: undefined reference to `LZ4F_isError'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:244: undefined reference to `LZ4F_decompress'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:246: undefined reference to `LZ4F_isError'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:186: undefined reference to `LZ4F_getErrorName'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:303: undefined reference to `LZ4F_freeDecompressionContext'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:304: undefined reference to `LZ4F_isError'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:305: undefined reference to `LZ4F_getErrorName'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:205: undefined reference to `LZ4F_getErrorName'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:247: undefined reference to `LZ4F_getErrorName'
//usr/local/lib/librdkafka.a(rdkafka_lz4.o): In function `rd_kafka_lz4_compress':
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:346: undefined reference to `LZ4F_compressBound'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:347: undefined reference to `LZ4F_isError'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:364: undefined reference to `LZ4F_createCompressionContext'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:365: undefined reference to `LZ4F_isError'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:366: undefined reference to `LZ4F_getErrorName'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:372: undefined reference to `LZ4F_compressBegin'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:373: undefined reference to `LZ4F_isError'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:386: undefined reference to `LZ4F_compressUpdate'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:388: undefined reference to `LZ4F_isError'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:389: undefined reference to `LZ4F_getErrorName'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:348: undefined reference to `LZ4F_getErrorName'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:429: undefined reference to `LZ4F_freeCompressionContext'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:405: undefined reference to `LZ4F_compressEnd'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:406: undefined reference to `LZ4F_isError'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:429: undefined reference to `LZ4F_freeCompressionContext'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:374: undefined reference to `LZ4F_getErrorName'
/home/ilan/librdkafka-master/src/rdkafka_lz4.c:407: undefined reference to `LZ4F_getErrorName' 
`

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Add `-llz4` to your linker command, or use librdkafka's pkg-config files.

**Comment by ilanoh** [comment]
I have libredkafka's pkg config installed.. weird, anyway thanks a lot -llz4 resolved the undefined reference LZ4, I still have some errors.

//usr/local/lib/librdkafka.a(rdkafka_sasl_cyrus.o): In function `rd_kafka_sasl_cyrus_close':
/home/ilan/librdkafka-master/src/rdkafka_sasl_cyrus.c:409: undefined reference to `sasl_dispose'

 Things like that, I don't really know whatsup now

**Comment by edenhill** [comment]
pkg-config really solves all this by providing you with compile (`--cflags`) and linker flags (`--libs`).

Something like:
`gcc .. -o yourprogram $(pkg-config --libs rdkafka)`

**Comment by ilanoh** [comment]
Cool, but how do you install pkg-config, I thought I installed everything by installing librdkafka

**Comment by edenhill** [comment]
pkg-config is a standard development tool that usually comes in the `pkg-config` package (ubuntu).

**Comment by ilanoh** [comment]
Ok sorry for my noobness, I'm confused on what I should do to have it work then

**Comment by aishwarydhare** [comment]
what solved the issue for me was changing the order from -lz -llz4 -lrdkafka in makefile to -lrdkafka -lz -llz4

also make sure you have installed lz4 dependencies beforehand, such as sudo apt-get install liblz4-1 liblz4-dev -y

**Comment by PSChrisHinshaw** [comment]
I am seeing similar errors, and tracked it down to the `./src/lz4*.c` files are not compiled into `*.o` files, even when `./configure --enable-lz4`.  I had to comment out lines 18 and 21 of `./src/Makefile` to get the object files to be created.

You can run `nm -aACS librdkafka.so | grep LZ4F_` to see if the functions are defined or not.
