### ISSUE TITLE
v0.11.4-RC2 nuget request

### ISSUE THREAD

**Issue by gccmbr** [edenhill/librdkafka#1736]
@edenhill  This is a big release!  If helpful I can test out over the next few weeks given a windows nuget build.  Thank you for v0.11.4-RC2 !  If this requires any effort, I will use v0.11.4-RC1 and provide feedback with that instead.

**Comment by edenhill** [comment]
@gccmbr Thank you for offering your help, very much appreciated!

We're looking to release the final v0.11.4 early next week, if you are able to give it a spin before that it'd be great.

Thanks
