### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [edenhill/librdkafka#1737]
I would like to point out that identifiers like “[`_RDKAFKA_H_`](https://github.com/edenhill/librdkafka/blob/6c722e5d411882283e5687b3e214075804e782ae/src/rdkafka.h#L44 "Update candidate")” and “[`_RDKAFKACPP_H_`](https://github.com/edenhill/librdkafka/blob/6c722e5d411882283e5687b3e214075804e782ae/src-cpp/rdkafkacpp.h#L29 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by edenhill** [comment]
I'm curious to know if this is a problem in practice?
It is an aesthetic change so a PR to rename the defines is welcomed if it solves a problem.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by edenhill** [comment]
That is theoretical in this case, no system will define _RDKAFKA* defines, the namespace is too unique.

Unless there is a real case where this breaks I'm going to close this issue.

Thanks
