### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [edenhill/librdkafka#1738]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [rd_kafka_destroy_internal](https://github.com/edenhill/librdkafka/blob/dbde254bf7671d5b106ebc70de25ee92cd5fe6a7/src/rdkafka.c#L753)
- rd_strdup ⇒ [rd_kafka_plugin_new](https://github.com/edenhill/librdkafka/blob/6a735dd3b86a93b78f61855a7691439e89864368/src/rdkafka_plugin.c#L53)

**Comment by edenhill** [comment]
This is a conscious choice:
There is no need to check return value of the heap memory allocator (for standard sized allocations).
If the process runs out of virtual memory there are much bigger problems, and it will likely run out of physical memory first.
If we did check there would be an explosion in the number of error paths and it is highly unlikely that we would be able to rewind the stack calls safely without incurring another allocation on the way (such as in a log or error event).

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by edenhill** [comment]
See previous explanation.
