### ISSUE TITLE
Support for config SSL TrustManager , KeyManager algorithm

### ISSUE THREAD

**Issue by koushikchitta** [edenhill/librdkafka#1741]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Is the support for SSL TrustManager , KeyManager algorithm configurations are in project backlog items ? 

```
ssl.keymanager.algorithm
ssl.trustmanager.algorithm
```

**Comment by edenhill** [comment]
Those are Java entities from what I understand, so I don't see a way to add support for them.

Fortunately the Kafka project is moving towards using standard PKCS stores, which are compatible with OpenSSL.

**Comment by koushikchitta** [comment]
Right. got it.
