### ISSUE TITLE
Huge performance hit when writing to more than 1 partition

### ISSUE THREAD

**Issue by DuncanSands** [edenhill/librdkafka#1744]
Description
===========

If I write data to just one partition of a multi-partition topic then the throughput is good.  In the example below it takes about 10 seconds to write all data.  However if I spread the data over multiple partitions then performance drops through the floor: about 4 minutes if I write to two partitions.  If I run multiple instances of the same program in parallel, each writing the data to just one partition (each instance using a different partition), then performance is excellent.  So the poor performance only seems to happen when one program is writing to multiple partitions

How to reproduce
================

(1) Create a topic with multiple partitions:
$ kafka-topics.sh --zookeeper localhost:2181 --create --replication-factor 1 --partitions 4 --topic test4p

(2) Write a big CSV file to a single partition:
$ time cat big.csv | kafkacat -P -b localhost -t test4p -p 0

real	0m9.371s
user	0m11.975s
sys	0m1.771s

This performance is fine.

(3) Write a big CSV file to multiple partitions:
$ time cat big.csv | kafkacat -P -b localhost -t test4p -p -1

real	10m1.572s
user	2m22.054s
sys	1m54.141s

This performance is poor.  The kafkacat CPU usage is much lower than in the single partition test.  For a topic with two partitions it takes about 4 minutes.

(4) To show that Kafka can happily handle writing to multiple partitions in parallel:
$ time (for F in 0 1 2 3 ; do cat big.csv | kafkacat -P -b localhost -t test4p -p $F & done; wait)

real	0m11.971s
user	0m52.126s
sys	0m3.996s

In spite of writing 4 times as much data, this only takes slightly longer than the single partition test.

Checklist
=========

 - [x] librdkafka version: 0.11.3
 - [x] kafkacat version: 1.3.1
 - [x] Apache Kafka version: 1.0.0 (scala 2.11)
 - [x] librdkafka client configuration: whatever kafkacat uses
 - [x] Operating system: Ubuntu 17.10, x86-64

**Comment by edenhill** [comment]
Try setting `-X linger.ms=100` or install librdkafka v0.11.4

**Comment by DuncanSands** [comment]
Using -X linger.ms=100 is effective, but using librdkafka v0.11.4 (without -X linger.ms) is not: it still shows the issue.

**Comment by DuncanSands** [comment]
PS: -X linger.ms=100 is effective in the sense that the test takes only 12 seconds with it.  But that's still slower than the 9 seconds it takes with only a single partition.  Shouldn't it be faster with more partitions?  Writing four times as much data using parallel programs, see (4), also takes 12 seconds, which suggests that using 4 partitions from a single program should be four times faster than it is, i.e. take about 3 seconds.

**Comment by edenhill** [comment]
How are the 4 partitions distributed among the brokers? and how many brokers?

What's the typical message size?

**Comment by DuncanSands** [comment]
I made a mistake about 0.11.4: kafkacat is dynamically linked and it was picking up an earlier version of the librdkafka library.  Forcing it to use 0.11.4 (without -Xlinger.ms) gives:

Topic with 1 partition:
        produce to partition 0: 8s
        random partitioner: 18s (!)
Topic with 2 partitions:
        produce to partition 0: 10s
        random partitioner: 21s
Topic with 4 partitions:
        produce to partition 0: 9s
        random partitioner: 27s
So this is much much better, but not great.

Compare for example with producing in parallel, as in (4):
Topic with 1 partitions, 1 parallel processes each producing one copy of the file: 9s = 9s per copy
Topic with 2 partitions, 2 parallel processes each producing one copy of the file: 11s = 5.5s per copy
Topic with 4 partitions, 4 parallel processes each producing one copy of the file: 15s = 3.75s per copy
Here each processes produces to one partition: first process to partition 0, second process to partition 1 etc

Given these numbers, I'd expect one process spreading data over 4 partitions to take about 3.75s, like 4 parallel processes producing 1/4 of the data each does, but it actually takes 27s (see above).

There is one broker running on my laptop (4 cores); the kafkacat instances are running on the same machine.  It is Kafka out of the box (default configuration).  The file "big.csv" is a CSV file with 14421950 lines.  The maximum line length (= maximum message length) is 162 characters, however most lines are less than 32 characters long.

**Comment by edenhill** [comment]
That is very helpful, thank you.

If the partitions are handled by the same broker, and thus the same internal librdkafka per-broker thread, there will be no gain in producing to multiple partitions.  Rather the opposite since there will be more partitions for the producer arbiter to enumerate.

The cost of the random partitioner is in part because it requires slightly more locking, but there may also be a startup cost involved:
Before the connection to the cluster is up and the actual number of partitions for a topic is known any specifically requested partitions, such as when you specify a fixed partition for producing, will be instantiated and messages for that partition is enqueued directly on that partition instance.
But when using a partitioner all those messages that are produced prior to connection setup will go to an internal UA/unassigned/-1 partition, and when the partition count is later learnt all the messages in the UA queue is scanned and the partitioner is run for each one.
What this means in practice is that there will be twice as many locks and enqueues for those initial messages, which depending on ingestion rate is typically close to `queue.buffering.max.messages`.
When doing performance measurements with continous message rates this is usually seen as a low throughput rate during the first second or so of the run.

I don't think this fully explains the difference, and I'm not sure I can - performance measurements are hard and they are always dependent on the platform, hardware, setup, other processes, loads etc.

**Comment by DuncanSands** [comment]
Thanks for the explanation.  I did some benchmarking against a cluster of three brokers (on three different machines) using one process and increasing the number of partitions.  There's a speedup when going from 1 to 2 partitions and again when going from 2 to 3 partitions.  From 3 to 4 (and onwards) it gets a little worse, but is more or less stable.  This seems logical as with 3 partitions you have 3 connections, one to each broker, each with one thread handling it.  With fewer partitions there is less parallelism and with more partitions you are just cycling around the existing connections.

In this case too I could increase throughput substantially (a factor of 5) by running multiple processes in parallel.  I guess I could get the same effect within a single process by creating multiple instances of the topic and spreading messages over the instances.

Anyway, -Xlinger.ms or 0.11.4 solve the original issue, so I'm closing the ticket.  Thanks for your help!

**Comment by edenhill** [comment]
> In this case too I could increase throughput substantially (a factor of 5) by running multiple processes in parallel.

Can you provide thruput numbers for one process consuming 4 partitions, vs multiple processes (how many?) consuming how many partitions each?

**Comment by DuncanSands** [comment]
I was only talking about producing, not consuming.  The following is on my laptop (single broker, kafkacat also running on my laptop; SSD drive), writing to a topic with 4 partitions.  Each process is doing: "cat big.csv | kafkacat -P -b localhost -t test4p -p -1-Xlinger.ms=100 ".

Num process | Throughput (MB/sec)
1                      37
2                      64
3                      88
4                     104
