### ISSUE TITLE
We would like some suggestions improving our low latency configuration settings

### ISSUE THREAD

**Issue by mindcrash** [edenhill/librdkafka#1746]
Hi Magnus,

We are currently in the process of rebuilding a monolithic application towards a microservices based cloud platform. To move our data around we are currently experimenting with Kafka using the latest Confluent Platform Docker images. To build consumers and producers we are currently using .NET Core 2.0 using the official .NET library from Confluent (and thus librdkafka)

For some of our functional uses cases latency matters a lot. Under Windows we noticed a RTT delay of up to a second at first which was not acceptable. When running under Linux (using librdkafka 0.9.5 compiled on the test machine) we noticed round trip times dropped to around 100 msecs, which is a big step in the right direction, especially considering the fact we would like to run our platform on Linux anyway. But we would like to shave off quite a bit of that number (towards 2).

With some help from the documentation our configuration settings currently look like this:

```
queue.buffering.max.ms: 1
fetch.error.backoff.ms: 1
socket.blocking.max.ms: 1
socket.nagle.disable: true
batch.num.messages: 1
debug: protocol
```

The data volume involved is extremely small (just a couple of messages within a 5 minute window).

Any suggestions would be very welcome.

**Comment by edenhill** [comment]
librdkafka v0.11.4 has a number of latency-related fixes, so first thing you should do is upgrade.

There are some limitations on Windows that requires you to configure socket.blocking.max.ms manually, but it should not be required on Linux.
https://github.com/edenhill/librdkafka/wiki/How-to-decrease-message-latency

**Comment by mindcrash** [comment]
Oh right, just noticed our local package repo was slightly out of date.  😬 

Anyhow, we updated to 0.11.3, but the results have become slightly worse.

We are now waiting for 0.11.4 to become available in Gentoo and recheck again.
