### ISSUE TITLE
Consumer group ID not shown in 'kafka-consumer-groups.sh'  when consumer uses batch queue

### ISSUE THREAD

**Issue by yvonq** [edenhill/librdkafka#1752]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have a consumer that uses a Consumer queue to consume records from an offset. A group.id is assigned using the rd_kafka_conf_set() call. 
The issue is that the group is not shown with the 'kafka-consumer-groups.sh' command. 

The consumer uses the following API calls: 
for queue init: 
queue = rd_kafka_queue_new()
 rd_kafka_consume_start_queue(topic_conf, 0, offset, queue);

to consume from queue: 
rd_kafka_consume_batch_queue(queue, 100, messages, count)

the consumer works ok: records are read sucessfully from the topic/partition. 

This has been tested with the latest release (v0.11.4). log with debug = 'all' attached. 

How to reproduce
================
create a sample consumer that reads records from batch queue.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag):v0.11.4
 - [ ] Apache Kafka version: kafka_2.12-1.0.0
 - [ ] librdkafka client configuration: offset.store.method
='broker', enable.auto.commit='false'
 - [ ] Operating system: 4.9.62-21.56.amzn1.x86_64
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

[group-id-issue.zip](https://github.com/edenhill/librdkafka/files/1873261/group-id-issue.zip)

**Comment by edenhill** [comment]
The rd_kafka_consume_start_*() APIs are part of the low-level legacy consumer which does not partake in a consumer group but consumes the given partitions directly.

To join a consumer group use rd_kafka_subscribe().

**Comment by yvonq** [comment]
Thanks for the switch response. 
I did not realize this was the case. 

I'll make the changes to my consumer code then to use rd_kafka_subscribe(). 

Yvon

**Comment by yvonq** [comment]
Hi, 

Actually, I was using the rd_kafka_consume_start_*() APIs as I wanted to start reading from a given offset:
...
rd_kafka_consume_start_queue(topic_conf, 0, offset, queue);

how do I do that with the rd_kafka_subscribe() API? I cannot find a way to specify an offset.

Thanks
Yvon

**Comment by rolandyoung** [comment]
The documentation for `rd_kafka_conf_set_rebalance_cb` says that your callback can update the partitions assigned to your consumer with the offsets you require. It does not say whether you can use the magic values `RD_KAFKA_OFFSET_END`, `RD_KAFKA_OFFSET_BEGINNING` etc, but I think Magnus has said that you can in one of his comments on a another issue.
