### ISSUE TITLE
pausing then resuming partitions doesn't always work

### ISSUE THREAD

**Issue by calummitchell** [edenhill/librdkafka#1753]
Description
===========
Resuming paused partitions only seems to work when operating on all assigned partitions. Pausing then resuming individual partitions when a consumer also has unpaused partitions assigned doesn't generate an error, but the consumer never receives any messages from the resumed partition.

How to reproduce
================
Code to reproduce this issue and debug "all" logs (my-rdkafka-example/logs) from these repro steps are attached here [my-rdkafka-example.zip](https://github.com/edenhill/librdkafka/files/1948741/my-rdkafka-example.zip).

In this example topic "topic" has two partitions: 0 1.

1. Run producer to generate messages to consume.

**producer localhost:9092 topic 1000 -1 0 > producer 2>&1**

794753488 6420 snd: topic[0:1] 0
794753495 6420 snd: topic[1:1] 1
794753500 6420 snd: topic[0:2] 2
794753506 6420 snd: topic[1:2] 3
794753509 6420 snd: topic[0:3] 4
794753514 6420 snd: topic[1:3] 5
\<snipped\>
794756351 6420 snd: topic[0:498] 994
794756354 6420 snd: topic[1:498] 995
794756358 6420 snd: topic[0:499] 996
794756361 6420 snd: topic[1:499] 997
794756364 6420 snd: topic[0:500] 998
794756367 6420 snd: topic[1:500] 999

2. Run consumer1 to consume messages from all partitions.

**consumer localhost:9092 topic 1000 -1 1000 1 > consumer1 2>&1**

794759242 14500 consume: 1000
794761351 14500 reb: [] => [0 1]
794761351 14500 pas: 0
794761351 14500 pas: 1
794763243 14500 res: 0
794763244 14500 res: 1
794763288 14500 rcv: topic[0:0] 0
794764288 14500 rcv: topic[0:1] 2
794765289 14500 rcv: topic[0:2] 4
794766290 14500 rcv: topic[1:0] 1
794767290 14500 rcv: topic[1:1] 3
794768291 14500 rcv: topic[1:2] 5
794769292 14500 rcv: topic[1:3] 7
794770292 14500 rcv: topic[1:4] 9
794771293 14500 rcv: topic[1:5] 11
794772293 14500 rcv: topic[0:3] 6
794773294 14500 rcv: topic[0:4] 8
794774295 14500 rcv: topic[0:5] 10
794775313 14500 reb: [0 1] => [1]     // consumer0 started
794775325 14500 rcv: topic[1:6] 13
794776325 14500 rcv: topic[1:7] 15
794777326 14500 rcv: topic[1:8] 17
794778326 14500 rcv: topic[1:9] 19
794779326 14500 rcv: topic[1:10] 21
794780327 14500 rcv: topic[1:11] 23
794781328 14500 rcv: topic[1:12] 25
794782328 14500 rcv: topic[1:13] 27
794783329 14500 rcv: topic[1:14] 29
794784330 14500 rcv: topic[1:15] 31
794785330 14500 rcv: topic[1:16] 33
794786331 14500 rcv: topic[1:17] 35
794787331 14500 rcv: topic[1:18] 37
794788332 14500 rcv: topic[1:19] 39
794789333 14500 rcv: topic[1:20] 41
794790333 14500 rcv: topic[1:21] 43
794791334 14500 rcv: topic[1:22] 45
794792353 14500 reb: [1] => [0 1]     // consumer0 stopped
794792353 14500 pas: 0
794792359 14500 rcv: topic[1:23] 47
794793359 14500 res: 0
794793359 14500 rcv: topic[1:24] 49
794794360 14500 rcv: topic[1:25] 51
794795360 14500 rcv: topic[1:26] 53
794796361 14500 rcv: topic[1:27] 55
794797362 14500 rcv: topic[1:28] 57
794798362 14500 rcv: topic[1:29] 59
794799363 14500 rcv: topic[1:30] 61
794800364 14500 rcv: topic[1:31] 63
794801364 14500 rcv: topic[1:32] 65
794802364 14500 rcv: topic[1:33] 67
794803365 14500 rcv: topic[1:34] 69
794804365 14500 rcv: topic[1:35] 71
794805366 14500 rcv: topic[1:36] 73
794806366 14500 rcv: topic[1:37] 75
794807366 14500 rcv: topic[1:38] 77
794808367 14500 rcv: topic[1:39] 79
794809367 14500 rcv: topic[1:40] 81
794810368 14500 rcv: topic[1:41] 83
794811368 14500 rcv: topic[1:42] 85
794812368 14500 rcv: topic[1:43] 87
794813369 14500 shutdown begin
794813486 14500 shutdown end

3. Run consumer0 to consume messages from all partitions.

**consumer localhost:9092 topic 1000 -1 1000 0 > consumer0 2>&1**

794775140 21084 consume: 1000
794775314 21084 reb: [] => [0]
794775315 21084 pas: 0
794777144 21084 res: 0
794777146 21084 rcv: topic[0:6] 12
794778146 21084 rcv: topic[0:7] 14
794779147 21084 rcv: topic[0:8] 16
794780148 21084 rcv: topic[0:9] 18
794781148 21084 rcv: topic[0:10] 20
794782149 21084 rcv: topic[0:11] 22
794783150 21084 rcv: topic[0:12] 24
794784151 21084 rcv: topic[0:13] 26
794785151 21084 rcv: topic[0:14] 28
794786152 21084 rcv: topic[0:15] 30
794787153 21084 rcv: topic[0:16] 32
794788153 21084 rcv: topic[0:17] 34
794789153 21084 rcv: topic[0:18] 36
794790154 21084 rcv: topic[0:19] 38
794791154 21084 rcv: topic[0:20] 40
794792155 21084 shutdown begin
794792263 21084 shutdown end

consumer1 initially consumes messages from both partitions (after pausing them immediately after a rebalance then resuming them a second later). When consumer0 is started, it's assigned partition0 and starts consuming messages from partition0 (after pausing then resuming). consumer1 continues to consume messages from partition1. When consumer0 is shutdown, consumer1 is reassigned partition0, but after pausing and resuming partition0, consumer1 continues to only consume messages from partition1.

If during the reassignment of partition0 to consumer1, consumer1 paused then resumed both partitions 0 and 1, it would successfully consume messages from both partitions.

If instead of two consumers, I had three and consumer0 and consumer1 took away partitions 0 and 1 from consumer2. Shutting down consumer0 and consumer1 at roughly the same time would reassigned partitions 0 and 1 to consumer2. consumer2 would pause and resume both of them and successfully consume messages from both.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.9.5-rc.10`
 - [x] Apache Kafka version: `kafka_2.12-1.0.0`
 - [x] librdkafka client configuration: `socket.blocking.max.ms=1, fetch.wait.max.ms=0, fetch.error.backoff.ms=10, max.partition.fetch.bytes=256, session.timeout.ms=6000, enable.auto.commit=false, group.id=group, partition.assignment.strategy=range, auto.offset.reset=smallest`
 - [x] Operating system: `Windows 10: producer/consumer, Alpine Linux v3.4: kafka `
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please upgrade to librdkafka v0.11.4 and try to reproduce

**Comment by calummitchell** [comment]
Apologies, this isn't a bug. In my test after consumer 1 resumes partition 0, he initially only receives messages from partition 1. However this is just temporary, after a while he'll begin receiving messages from both partitions.
