### ISSUE TITLE
How to know when we reach all topic partitions' eof with group consumer?

### ISSUE THREAD

**Issue by hangcun** [edenhill/librdkafka#1757]
I use a compacted topic for state storage. And then I use `KafkaConsumer` with subscription mode to consume state messages from the compacted topic, how do I know the time that I reach all partitions' eof, which means I finish recovering the state?

**Comment by edenhill** [comment]
You will need to track this per partition yourself.
Register a RebalanceCb (alternatively call assignment()) to keep track of which partitions are currently assigned to you, then keep track of EOF or if new messages are seen on a partition.

**Comment by hangcun** [comment]
Ok, thanks!
