### ISSUE TITLE
Add package checksums to releases

### ISSUE THREAD

**Issue by koenrh** [edenhill/librdkafka#1759]
It is considered a good (security) practice to always verify the integrity of downloaded files. It would help if the releases page would have the checksums (e.g. SHA-256) listed along the download links for the packages.

Could you start adding the checksums to the [releases](https://github.com/edenhill/librdkafka/releases)?

See, for a basic example, Kubernetes releases: https://github.com/kubernetes/kubernetes/releases.

I'm happy to update the [RELEASE](https://github.com/edenhill/librdkafka/blob/master/packaging/RELEASE.md) document with instructions.

**Comment by thijsc** [comment]
Any thoughts on this @edenhill? This would be a very good security measure for language integrations.

**Comment by edenhill** [comment]
I agree that checksums are indeed useful for download pages, but I'm not sure how useful they are for github releases: if someone can change the tag the links point to, they can probably change the release page as well, right?

**Comment by thijsc** [comment]
That's true. There is still a benefit though. If I as a Ruby gem maintainer bump the librdkafka version I can take the hash it was at that time. I then verify the hash and add it to the code for the Ruby integration. At that time I know that if the release was not initially compromised there is a stable situation.

If at any time after this somebody changes the release or the CDN Is compromised the gem install will fail and we will be aware of what happened.

**Comment by edenhill** [comment]
Okay, sounds good.

@koenrh Please go ahead with a PR to update the RELEASE instructions, and preferably a script in packaging/tools that automates the download+checksum steps based on a tag and emits what should be copy-pasted onto the release page.

**Comment by thijsc** [comment]
@koenrh did you get a chance to do this? 1.0 is coming up, so good occasion to get started with this.

**Comment by thijsc** [comment]
I noticed that the 1.0 release didn't include a checksum, is this part of the release process now?

**Comment by thijsc** [comment]
Any thoughts on this?

**Comment by edenhill** [comment]
Can you verify that the script in `packaging/tools/gh-release-checksums.py` generates correct checksums?

**Comment by breunigs** [comment]
It does:
```
stefan@nb-sbreunig-debian ~/github/librdkafka $ wget -q https://github.com/edenhill/librdkafka/archive/v1.1.0.tar.gz
stefan@nb-sbreunig-debian ~/github/librdkafka $ wget -q https://github.com/edenhill/librdkafka/archive/v1.1.0.zip
stefan@nb-sbreunig-debian ~/github/librdkafka $ sha256sum v1.1.0.tar.gz v1.1.0.zip
123b47404c16bcde194b4bd1221c21fdce832ad12912bd8074f88f64b2b86f2b  v1.1.0.tar.gz
70279676ed863c984f9e088db124ac84a080e644c38d4d239f9ebd3e3c405e84  v1.1.0.zip
stefan@nb-sbreunig-debian ~/github/librdkafka $ packaging/tools/gh-release-checksums.py v1.1.0
## Checksums
Release asset checksums:
 * v1.1.0.zip SHA256 `70279676ed863c984f9e088db124ac84a080e644c38d4d239f9ebd3e3c405e84`
 * v1.1.0.tar.gz SHA256 `123b47404c16bcde194b4bd1221c21fdce832ad12912bd8074f88f64b2b86f2b`
```

**Comment by edenhill** [comment]
Done, thanks!

**Comment by thijsc** [comment]
I noticed there were no checksums published for https://github.com/edenhill/librdkafka/releases/tag/v1.5.2, was that intentional?

**Comment by edenhill** [comment]
Whoops, fixed. Thanks @thijsc
