### ISSUE TITLE
cpu is 100% 

### ISSUE THREAD

**Issue by sterryxue** [edenhill/librdkafka#1762]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
when i found the cpu of my process is 100%, i use "top -H -p pid" command at my server
 8788 root      20   0 1333484  21872  12980 R 99.3  0.6  14134:31 moniter_agent  
i user "pstack pid" command
Thread 12 (Thread 0x7f095effd700 (LWP 8788)):
#0  0x00007f0985d0bc02 in pthread_mutex_lock () from /lib64/libpthread.so.0
#1  0x00000000006ae6a9 in mtx_lock (mtx=<optimized out>) at tinycthread.c:136
#2  0x00000000006616c8 in rd_refcnt_get (R=<optimized out>) at rd.h:305
#3  rd_kafka_broker_thread_main (arg=0x2092f48) at rdkafka_broker.c:3070
#4  0x00000000006ae627 in _thrd_wrapper_function (aArg=<optimized out>) at tinycthread.c:624
#5  0x00007f0985d09dc5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f098437676d in clone () from /lib64/libc.so.6

How to reproduce
================
Dual current problem at release v_0.11.4

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version v_0.11.4

**Comment by edenhill** [comment]
Instead of removing the checklist, please fill it out instead.

**Comment by edenhill** [comment]
dup of #1858
