### ISSUE TITLE
Setup ACL user over kafka Client

### ISSUE THREAD

**Issue by lday00** [edenhill/librdkafka#1763]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I try to setup ACL over Kafka client and server.

How to reproduce
================
 I use librdkafka (c/c++) as the client and add following in server.properties.

authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
super.users=User:Producer;User:Consumer;User:ANONYMOUS

Currently, I can get ANONYMOUS user working by using kafka-acls.sh.
/opt/kafka_2.11-1.0.0/bin/kafka-acls.sh --authorizer-properties zookeeper.connect=localhost:2181 --add --allow-principal User:ANONYMOUS --allow-host 10.1.xx.xx --producer --topic MY.TOPIC.NAME
/opt/kafka_2.11-1.0.0/bin/kafka-acls.sh --authorizer-properties zookeeper.connect=localhost:2181 --add --allow-principal User:ANONYMOUS --allow-host 10.1.xx.xx -operation Write --topic MY.TOPIC.NAME

This means client send username ANONYMOUS to server. How can I change the username from client side?

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.1
 - [x] Apache Kafka version: 2.11-1.0.0
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: Red Hat Enterprise Linux Server release 6.9 (Santiago)
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You need to set up the client for authorization using security.protocol and sasl.mechanisms.
See these links for more info;
https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka (Kerberos auth)
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md  (config properties, search for sasl)

**Comment by lday00** [comment]
Thanks for the help. I will look over them.

**Comment by edenhill** [comment]
Coming
