### ISSUE TITLE
`gen-ssl-certs.sh` generates DSA certs which Kafka does not cope with well

### ISSUE THREAD

**Issue by jcaesar** [edenhill/librdkafka#1765]
The `gen-ssl-certs.sh` script generates DSA certificates on my system (CentOS), which will cause the broker to run into trouble, which in turn generates weird errors on the client side:
`ssl://blubbs:9093/bootstrap: SSL handshake failed: ../ssl/record/ssl3_record.c:252: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:`

This can be easily fixed by adding `-keyalg RSA` to all `keytool -genkey` invocations.

I'm sorry for not following the standard issue format with this; I just want to ask: do you want a pull request for this?

**Comment by edenhill** [comment]
A PR would be very welcome!
