### ISSUE TITLE
rebalance_cb is getting old partition offsets when assigned to a partition revoked earlier 

### ISSUE THREAD

**Issue by ludobrands** [edenhill/librdkafka#1767]
Description
===========
Our consumer is configured with topic config 'offset.store.method','broker'  and 'enable.auto.commit','false'. Data is handled and stored to a database in batch mode and we want to commit in kafka after the data is committed in the database. Since we are having a lot of fluctuation in activity over the day, the number of consumers spawned are managed by a tool that monitors the offsets in kafka. So there is a lot of re-balancing going on. The problem we encountered occurs when consumer A handles for example partition 10 which gets revoked at offset N, then partition 10 gets assigned to consumer B, revoked at offset M end then assigned back to consumer A. The rebalance_cb for consumer A gets in the partitions parameter an offset for partition 10 still at N. Our code is pretty much similar to https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_consumer_example.c and the result is that we consume again messages that were already consumed by consumer B. 

Tested with 'enable.auto.commit','true' and the behavior was as expected and consumer A started where consumer B left off. 

Debugged with 'all' debug log and noticed the following difference:
 'enable.auto.commit','false' consumer A after rebalance
`%7|1523440895.765|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "PG1" changed join state wait-assign-rebalance_cb -> assigned (v11, state up)
%7|1523440895.765|BARRIER|rdkafka#consumer-1| [thrd:main]: Group "PG1": rd_kafka_cgrp_partitions_fetch_start0:1599: new version barrier v12
%7|1523440895.765|FETCHSTART|rdkafka#consumer-1| [thrd:main]: Group "PG1": starting fetchers for 4 assigned partition(s) in join-state assigned (usable_offsets=no, v12, line 2281)
%7|1523440895.765|FETCHSTART|rdkafka#consumer-1| [thrd:main]: List with 4 partition(s):
%7|1523440895.765|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [0] offset 258169
%7|1523440895.765|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [1] offset 74914
%7|1523440895.765|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [2] offset 73399
%7|1523440895.765|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [3] offset 71859
%7|1523440895.765|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "PG1" changed join state assigned -> started (v12, state up)
`
Those offsets are the last ones the consumer A committed. Not what the broker reports as committed. 

 'enable.auto.commit','false' consumer A  after rebalance
`%7|1523442368.319|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "PG1" changed join state wait-sync -> assigned (v10, state up)
%7|1523442368.319|BARRIER|rdkafka#consumer-1| [thrd:main]: Group "PG1": rd_kafka_cgrp_partitions_fetch_start0:1599: new version barrier v11
%7|1523442368.319|FETCHSTART|rdkafka#consumer-1| [thrd:main]: Group "PG1": starting fetchers for 4 assigned partition(s) in join-state assigned (usable_offsets=no, v11, line 2281)
%7|1523442368.319|FETCHSTART|rdkafka#consumer-1| [thrd:main]: List with 4 partition(s):
%7|1523442368.319|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [0] offset INVALID
%7|1523442368.319|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [1] offset INVALID
%7|1523442368.319|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [2] offset INVALID
%7|1523442368.319|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [3] offset INVALID
%7|1523442368.319|OFFSET|rdkafka#consumer-1| [thrd:main]: Fetch 4 offsets with v11
%7|1523442368.319|OFFSET|rdkafka#consumer-1| [thrd:main]: Fetch 4 offsets with v11
%7|1523442368.319|OFFSET|rdkafka#consumer-1| [thrd:main]: 192.168.2.238:9092/0: OffsetFetchRequest(v1) for 4/4 partition(s)
%7|1523442368.319|SEND|rdkafka#consumer-1| [thrd:192.168.2.238:9092/bootstrap]: 192.168.2.238:9092/0: Sent OffsetFetchRequest (v1, 54 bytes @ 0, CorrId 1146)
%7|1523442368.320|RECV|rdkafka#consumer-1| [thrd:192.168.2.238:9092/bootstrap]: 192.168.2.238:9092/0: Received OffsetFetchResponse (v1, 76 bytes, CorrId 1146, rtt 0.61ms)
%7|1523442368.320|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]: List with 4 partition(s):
%7|1523442368.320|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]:  pg [0] offset INVALID
%7|1523442368.320|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]:  pg [1] offset INVALID
%7|1523442368.320|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]:  pg [2] offset INVALID
%7|1523442368.320|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]:  pg [3] offset INVALID
%7|1523442368.320|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic pg [0]: setting default offset INVALID
%7|1523442368.320|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic pg [1]: setting default offset INVALID
%7|1523442368.320|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic pg [2]: setting default offset INVALID
%7|1523442368.320|OFFSET|rdkafka#consumer-1| [thrd:main]: Topic pg [3]: setting default offset INVALID
%7|1523442368.320|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]: 192.168.2.238:9092/0: OffsetFetchResponse: pg [0] offset 264753
%7|1523442368.320|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]: 192.168.2.238:9092/0: OffsetFetchResponse: pg [1] offset 76563
%7|1523442368.320|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]: 192.168.2.238:9092/0: OffsetFetchResponse: pg [2] offset 76527
%7|1523442368.320|OFFSETFETCH|rdkafka#consumer-1| [thrd:main]: 192.168.2.238:9092/0: OffsetFetchResponse: pg [3] offset 76517
%7|1523442368.320|OFFFETCH|rdkafka#consumer-1| [thrd:main]: 192.168.2.238:9092/0: OffsetFetch for 4/4 partition(s) returned Success
%7|1523442368.320|BARRIER|rdkafka#consumer-1| [thrd:main]: Group "PG1": rd_kafka_cgrp_partitions_fetch_start0:1599: new version barrier v12
%7|1523442368.320|FETCHSTART|rdkafka#consumer-1| [thrd:main]: Group "PG1": starting fetchers for 4 assigned partition(s) in join-state assigned (usable_offsets=yes, v12, line 1528)
%7|1523442368.320|FETCHSTART|rdkafka#consumer-1| [thrd:main]: List with 4 partition(s):
%7|1523442368.320|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [0] offset 264753
%7|1523442368.320|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [1] offset 76563
%7|1523442368.320|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [2] offset 76527
%7|1523442368.320|FETCHSTART|rdkafka#consumer-1| [thrd:main]:  pg [3] offset 76517
%7|1523442368.320|CGRPJOINSTATE|rdkafka#consumer-1| [thrd:main]: Group "PG1" changed join state assigned -> started (v12, state up)`

Both start with usable_offsets=no but in auto commit mode, partitions is reset to all RD_KAFKA_OFFSET_INVALID while in manual commit, partitions contains old data.  https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_cgrp.c#L1659 results in no offsets being requested from broker. 
Fixed the problem by manually setting all offsets to RD_KAFKA_OFFSET_INVALID in the RD_KAFKA_RESP_ERR__ASSIGN_PARTITIONS case in rebalance_cb().

So the main problem is that librdkafka holds on to old partition offsets that are clearly not valid since the consumer got all partitions revoked. The example consumer and documentation don't mention this and suggest that partitions only has to be updated if the user uses his own offset store. Here the broker is used to store the offsets and handled by librdkakfa.

How to reproduce
================
My test setup: kafka with 4 partitions, producer posting an event every 300 msec. Consumer configured to debug log all and to commit to kafka every 5 secs. Start consumer A, survey log. When a few commits have been made, start consumer B. When both consumers are rebalanced, wait for a few commits and stop consumer B. Note last committed offsets for B. Look at consumer A, wait until rebalanced and start consuming again and note the start offsets for the partitions handled previously by B. All events handle by B are fetched again by A. 

Checklist
=========

 - [x] librdkafka version (release number or git tag): `v0.11.4`
 - [x] Apache Kafka version: `0.10.1.1-0`
 - [x] librdkafka client configuration: `topic.offset.store.method=broker, topic.enable.auto.commit=false, topic.auto.offset.reset=earliest `
 - [x] Operating system: `debian stretch and ubuntu 16.04`
 - [x] Critical issue

**Comment by edenhill** [comment]
Thanks for a great report!

It indeed looks like assign() is called with valid (but outdated) offsets, are you absolutely sure you are not populating the assigned partitions with offsets before calling assign()?
If you are not then it seems like a bug in librdkafka

**Comment by ludobrands** [comment]
We wrote a thin binding in freepascal for librdkafka. Here is the relevant code for the rebalance.cb before the fix:

```
procedure TKConsumer.RebalanceCb(ark: prd_kafka_t; err: rd_kafka_resp_err_t;
  partitions: prd_kafka_topic_partition_list_t);
begin
  globalklogger(LOG_INFO,'%% Consumer group rebalanced: ');
  case (err) of
  RD_KAFKA_RESP_ERR__ASSIGN_PARTITIONS:
     begin
     globalklogger(LOG_INFO,'assigned:'+GetPartitionList(partitions));
     rd_kafka_assign(ark, partitions);
     inc(Fwait_eof,partitions^.cnt);
     end;
...
end;
```
```
function TKConsumer.GetPartitionList(
  partitions: prd_kafka_topic_partition_list_t): string;
var
 i : integer;
begin
  result:='';
  rd_kafka_position(Frk,partitions);
  for I:=0 to partitions^.cnt-1 do
    result+=format('%s[%d] offset %d ;',[partitions^.elems[i].topic,
                  partitions^.elems[i].partition,
                  partitions^.elems[i].offset]);
end;
```

As you can see, it is an almost literal translation of https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_consumer_example.c. We do store the offsets as savepoints in our database backends but that is only used to implement an exactly once system that skips database updates when the offset is already handled and committed to the database. It is in no way used to direct the kafka consumer.

**Comment by edenhill** [comment]
Oh, I see what's wrong.
You are passing the assignment from the rebalance callback to `rd_kafka_position()` which updates the list with the last consumed offset (+1) for each of the partitions. This information is, for better or worse, prevailing between rebalances and that is why when consumer A gets assigned a partition it used to consume at an earlier rebalance will happily update the partition list with that old offset.

The workaround is to make a copy of the assignment list before passing it to rd_kafka_position() so the original list's offsets are not updated.

**Comment by ludobrands** [comment]
That explains indeed our problem. Thanks a lot for spotting this. 

May I suggest to add a small warning to the documentation of rd_kafka_position()? Something along the lines of:
`The offset field of each requested partition will be set to the offset of the last consumed message + 1, or RD_KAFKA_OFFSET_INVALID in case there was no previous message. NOTE: in this context the last consumed message is the offset consumed by the current librdkafka instance and, in case of rebalancing, not necessarily the last message consumed from the kafka queue. `
