### ISSUE TITLE
Transplant librdkafka producer into IBM ZOS, compile error

### ISSUE THREAD

**Issue by atear77** [edenhill/librdkafka#1768]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

hi:
   we want to transplant the librdkafka producer into IBM ZOS host, but we met errors while compile, can you provide some service to help us for this ? Thank you

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Since there are no readily available CI build services available for ZOS we can't support it, and it is up to the community to contribute a working port.

**Comment by trudeaun** [comment]
@atear77 Hello! Do you have access to z/OS currently? If you are an IBM partner or ISV, IBM has a z/OS Validation program that you might be able to take advantage of, if an issue is getting access. 

For the Node.js, OMR, OpenJ9 and AdoptOpenJDK projects, some external z/OS systems from Marist's private z/OS cloud were acquired to add to the respective communities CI.  i.e. there are regular PR jobs running on z/OS for each OMR PR: https://ci.eclipse.org/omr/job/PullRequest-zos_390-64/ 

For Jenkins, there were few workarounds for ASCII/EBCDIC handling with the Jenkins slave.jar as well as compatibility with Rocket tools like git - let me know if you're interested in hearing more about that.
