### ISSUE TITLE
rd_kafka_topic_conf_set_partitioner_cb does not work

### ISSUE THREAD

**Issue by hitljs** [edenhill/librdkafka#177]
HI， when I set rd_kafka_topic_conf_set_partitioner_cb(topic_conf, partitioner_cb);
and define 
````
static int32_t partitioner_cb(const rd_kafka_topic_t *rkt,
                           const void *keydata,
                           size_t keylen,
                           int32_t partition_cnt,
                           void *rkt_opaque,
                           void *msg_opaque) {

    int32_t *key = ((int32_t *)keydata);
    TEST_SAY("call partitioner_cb");
    return *key % partition_cnt;
}
````
when i run the test THE TEST_SAY function will not work. or i think it is the rd_kafka_topic_conf_set_partitioner_cb function error, can you give me an example ,thanks

**Comment by mazharshaikh86** [comment]
I'm facing the same problem. "rd_kafka_topic_conf_set_partitioner_cb()" is not working.

rd_kafka_produce(rkt, 
                        RD_KAFKA_PARTITION_UA,
                        RD_KAFKA_MSG_F_COPY,                        
                        buf, len,   // Payload and length                        
                        kbuf, klen,   //Optional key and its length                       
                        NULL)

Can anyone help ?

**Comment by mazharshaikh86** [comment]
got it.  need to set partitioner before creating a topic.

//Set Topic Partitioner
    rd_kafka_topic_conf_set_partitioner_cb (topic_conf,&partitioner);
    
    /* Create topic */
    rkt = rd_kafka_topic_new(rk, topic, topic_conf);
