### ISSUE TITLE
rdkafka*-static.pc files are installed even if librdkafka was not built with static linking support

### ISSUE THREAD

**Issue by fcami** [edenhill/librdkafka#1772]
Description
===========
librdkafka installs /usr/lib64/pkgconfig/rdkafka++-static.pc and /usr/lib64/pkgconfig/rdkafka-static.pc even if --enable-static was not provided to configure.

Checklist
=========

 - [x] librdkafka version (release number or git tag): v0.11.4.tar.gz 
 - [x] Operating system: Fedora 27
 - [ ] Critical issue - no, but as it breaks downstream packaging it'd be nice to see it fixed.

**Comment by edenhill** [comment]
I think this is fine, the application can link librdkafka statically but its dependencies (e.g, openssl) dynamically.

--enable-static only controls how librdkafka itself links its dependency libraries, and this currently only has affect for liblz4 which can be linked statically with librdkafka.

**Comment by fcami** [comment]
OK, understood. I'll close this issue, thanks for the explanation!

**Comment by k1ng87** [comment]
don't mean to open this up again but how do you statically link the librdkafka dependencies like openssl?

**Comment by tamama** [comment]
+1

Can we have complete static linking to all these dependencies?
`LIBS                     -llz4  -lm -lcurl  -L/usr/lib -lzstd  -lsasl2  -lssl  -lcrypto  -lz  -ldl -lpthread -lrt -lpthread -lrt`

^ The above is not okay, because this would force all downstream to use one particular version of these system libraries. This is too strict for production where almost every component uses a specific version of whatever dependency due to legacy. 

Is there a way of overriding this to use custom-built third-party libraries?

We just can't use system libraries for practical reasons.

**Comment by edenhill** [comment]
We can link everything but libsasl2 statically, haven't found a good way to accomplish that for libsasl2/cyrus-sasl unfortunately.

If you don't need Kerberos/GSSAPI, and thus not libsasl2, you can create a completely self-contained librdkafka (that only depends on system libraries) with:
`./configure --install-deps --source-deps-only --disable-gssapi --enable-static`

And then link to librdkafka-static.a.

**Comment by tamama** [comment]
Unfortunately, SASL (though not via Kerberos) is needed for our case here.

Here is my onfigure snippet:
```
        ./configure \
            --enable-static \
            --enable-sasl \
            --enable-gssapi \
            --enable-curl \
            --enable-ssl \
            --enable-zlib \
            --enable-zstd \
            --enable-lz4-ext \
            --enable-syslog \
            --prefix=$PWD/.dist \
            ;
``` 

Well, tbh - the best strategy I see forward would be to compile this on some (docker) container with the runtime libraries attached.

Using system dependencies on host would be too tricky (ie. any software upgrade on host could break/corrupt these dependencies - which means that there must be 1 headcount to maintain this effort - which is ... oops ... quite difficult.

**Comment by edenhill** [comment]
If you build it statically (as previously instructed) but with --enable-gssapi it will depend on a specific soname version of libsasl2, but these are ABI safe for upgrade within the same soname version, so updating that package should not have adverse affects.
I.e., on Ubuntu 20.04 libsasl2 has soname 2, package name is thus libsasl2-2.

**Comment by tamama** [comment]
Noted with thanks.

For the bigger audience, these are the runtime that would work. 

```
target_link_libraries(vendor-kafka-rdkafka
    INTERFACE
        ${RdKafka-LIBRARIES}
        /usr/lib64/libdl.so
        /usr/lib64/libcurl.so
        /usr/lib64/libcrypto.so
        /usr/lib64/libssl.so
        /usr/lib64/libsasl2.so
        /usr/lib64/libzstd.so
)

```

**Comment by tamama** [comment]
@edenhill

One more question I would like to ask you.

I have indeed built my custom OpenSSL package.
Is there a configure option to include the openssl diretcory

(I saw you wrote on CMakke:   -D OPENSSL_ROOT_DIR=xxx  )

Thanks!

**Comment by edenhill** [comment]
Use `PKG_CONFIG_PATH=../path/to/where/openssl.pc ./configure  ..`

**Comment by tamama** [comment]
> Use `PKG_CONFIG_PATH=../path/to/where/openssl.pc ./configure ..`

Magic!
