### ISSUE TITLE
Equivalent "adminClient.deleteRecordsBefore" from librdkafka

### ISSUE THREAD

**Issue by lday00** [edenhill/librdkafka#1773]
Description
===========
I can delete kafka records using kafka-delete-records.sh.

Example:
kafka-delete-records.sh --bootstrap-server my.broker.name:9092 --offset-json-file ./offset_file.json
where offset_file.json:
{"partitions": [{"topic": “TOPIC.RECEIVE.01", "partition": 0, "offset": 90}], "version":1 }

This is implemented in DeleteRecordsCommand.scala. Is there any equivalent for C++ (librdkafka) implemented or easy way to write my own in C++?

How to reproduce
================
N/A

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.1`
 - [x] Apache Kafka version: `2.11-1.0.0`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `Red Hat Enterprise Linux Server release 6.9 (Santiago)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
DeleteRecords was added in 1.6.0
