### ISSUE TITLE
Need some clarification about queued.max.messages.kbytes and prefetcher

### ISSUE THREAD

**Issue by vryabinin** [edenhill/librdkafka#1775]
Description
===========
My consumer (custom Node.js binding around librdkafka) is configured with `queued.max.messages.kbytes=150000 fetch.message.max.bytes=150000 queued.min.messages=1000`. The consumer fetches a topic with ~ 493000 messages, each message ~ 1200 bytes (~ 640MB total). The consumer process is experiencing a huge memory consumption, about 700MB RSS. 

I do not call `rd_kafka_message_destroy` at all (I do this for test purposes intentionally. Under a heavy load on my application, its processing speed can't keep up with the librdkafka fetching rate so each message destruction will be delayed).

I expect the internal prefetcher to stop once it hits the `queued.max.messages.kbytes` threshold, but this never happens - it never stops. So there's really no backpressure.

How can I configure librdkafka to stop fetching when config thresholds are hit?

How to reproduce
================
The consumer has been reduced to this test loop:
```
while (run) {
    rd_kafka_consumer_poll(rk, -1);
}
```
`rd_kafka_message_destroy` never gets called. librdkafka eventually fetches all 640MB of messages even with no processing on the application's side.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.4>`
 - [x] Apache Kafka version: `<2.11-0.11>`
 - [x] librdkafka client configuration: `<session.timeout.ms=6000 socket.blocking.max.ms=10 fetch.wait.max.ms=10 fetch.error.backoff.ms=100 queued.max.messages.kbytes=150000 fetch.message.max.bytes=150000 queued.min.messages=1000 enable.auto.commit=false socket.keepalive.enable=true enable.auto.offset.store=false offset.store.method=none topic.enable.auto.commit=false topic.auto.offset.reset=smallest>`
 - [x] Operating system: `<Centos 7 (x64) 4.15.9-1.el7.elrepo.x86_64>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
When a consume message is passed to your application it is no longer considered part of the queue, which means its space is now free for more messages to be added.
