### ISSUE TITLE
Error in Producing and consuming messages with confluent-kafka 0.11.4

### ISSUE THREAD

**Issue by rajilion** [edenhill/librdkafka#1776]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
i am using librdkafka with confluent-kafka python to produce and consume messages. 
So far i have used confluent-kafka version 0.11.0 and there were no issues in producing and consuming but when i upgraded the package i got the below erroe

cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to create producer: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN SASL_SCRAM"}

i have tried with the lastet release of librdkafka (11.4) and also with master too. 

i have all the required packages installed

yum install cyrus-sasl
yum install cyrus-sasl-devel
yum install cyrus-sasl-lib
yum install cyrus-sasl-gssapi
yum install openssl-devel
yum install openssl

using Red Hat Enterprise Linux Server release 7.3 

How to reproduce
================

producer = Producer({
            'bootstrap.servers': self.bootstrap_servers,
            'security.protocol': 'SASL_SSL',
            'sasl.mechanisms': 'GSSAPI',
            'sasl.kerberos.service.name': 'kafka',
            'sasl.kerberos.principal': myprincipal,
            'sasl.kerberos.keytab': mykeytab,
            'ssl.ca.location': cert_file
        })

consumer = Consumer({
            'bootstrap.servers': bootstrap_servers,
            'group.id': 'kafka',
            'security.protocol': 'SASL_SSL',
            'sasl.mechanisms': 'GSSAPI',
            'sasl.kerberos.service.name': 'kafka',
            'sasl.kerberos.principal': myprincipal,
            'sasl.kerberos.keytab': mykeytab,
            'ssl.ca.location': cert_file,
            'default.topic.config': {
                'auto.offset.reset': 'smallest'
            }
        })

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.4`
 - [x ] Apache Kafka version: `CDH Kafka 3.0.0-1.3.0.0.p0.40`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ x] Operating system: `RHEL 7`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by drazenzubovic** [comment]
Has this been introduced with/from 0.11 ?

**Comment by edenhill** [comment]
Binary wheels were introduced in v0.11.4

**Comment by drazenzubovic** [comment]
Thx for the quick reply, but there might be some further clarification needed. 
On macOS we use librdkafka alongside with confluent-kafka without "side effects". The current version is 0.11 for both. 
Deploy on mac:
```
brew install librdkafka
pip install confluent-kafka
```
While trying the code on RHEL we are hitting above mentioned error. Both versions are also 0.11
Deploy on RHEL:
```
yum install librdkafka  -> from the latest confluent repository 4.1.1
pip install confluent-kafka
```
So the question is, why does RHEL version behave differently and what exactly is needed to make rdlibkafka + confluent-kafka under RHEL work? 
Does this also affect Kafka 0.10 ?

**Comment by edenhill** [comment]
As stated in the README you need to install the librdkafka-devel packages on RHEL, and the source install of confluent-kafka:
```
# remove the binary wheel python client first, repeat until it says no longer installed
pip uninstall -y confluent-kafka

yum install librdkafka-devel python-devel
pip install --no-binary :all: confluent-kafka
```

**Comment by drazenzubovic** [comment]
Thanks again, but this does not answer the question completely. 
Yes I can confirm the README cookbook works and creates confluent-kafka which can handle SASL/GSSAPI. But for that it requires gcc on the host! Needles to mention gcc is no-go from the ITSec perspective on productive enterprise systems. 
So again, why is librdkafka for Linux treated differently? How long is this workaround expected to be in place? Who/what is the right place to shed some more light on this?

**Comment by edenhill** [comment]
The problem with GSSAPI support is that it requires libsasl2 and the libsasl2 kerberor plugins, we encountered some problems with packaging these in a Linux distro-agnostic way so we chose not to include them until we could find a viable solution (which is on our roadmap).
On OSX these libraries are installed by default as part of the OS

**Comment by Sudheer312** [comment]
> As stated in the README you need to install the librdkafka-devel packages on RHEL, and the source install of confluent-kafka:
> 
> ```
> # remove the binary wheel python client first, repeat until it says no longer installed
> pip uninstall -y confluent-kafka
> 
> yum install librdkafka-devel python-devel
> pip install --no-binary :all: confluent-kafka
> ```

 ERROR: Complete output from command /opt/rails-seo-admin/env/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-z7znvu24/confluent-kafka/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6h0c4jx1/install-record.txt --single-version-externally-managed --compile --install-headers /opt/rails-seo-admin/env/include/site/python3.6/confluent-kafka:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/confluent_kafka
    copying confluent_kafka/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka
    creating build/lib.linux-x86_64-3.6/confluent_kafka/admin
    copying confluent_kafka/admin/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/admin
    creating build/lib.linux-x86_64-3.6/confluent_kafka/avro
    copying confluent_kafka/avro/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
    copying confluent_kafka/avro/cached_schema_registry_client.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
    copying confluent_kafka/avro/error.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
    copying confluent_kafka/avro/load.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro
    creating build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_client.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_consumer.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
    copying confluent_kafka/kafkatest/verifiable_producer.py -> build/lib.linux-x86_64-3.6/confluent_kafka/kafkatest
    creating build/lib.linux-x86_64-3.6/confluent_kafka/avro/serializer
    copying confluent_kafka/avro/serializer/__init__.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro/serializer
    copying confluent_kafka/avro/serializer/message_serializer.py -> build/lib.linux-x86_64-3.6/confluent_kafka/avro/serializer
    running build_ext
    building 'confluent_kafka.cimpl' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/confluent_kafka
    creating build/temp.linux-x86_64-3.6/confluent_kafka/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -c confluent_kafka/src/confluent_kafka.c -o build/temp.linux-x86_64-3.6/confluent_kafka/src/confluent_kafka.o
    In file included from confluent_kafka/src/confluent_kafka.c:17:0:
    confluent_kafka/src/confluent_kafka.h:55:2: error: #error "confluent-kafka-python requires librdkafka v1.0.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
     #error "confluent-kafka-python requires librdkafka v1.0.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
      ^
    confluent_kafka/src/confluent_kafka.c: In function ‘error_cb’:
    confluent_kafka/src/confluent_kafka.c:1226:20: error: ‘RD_KAFKA_RESP_ERR__FATAL’ undeclared (first use in this function)
             if (err == RD_KAFKA_RESP_ERR__FATAL) {
                        ^
    confluent_kafka/src/confluent_kafka.c:1226:20: note: each undeclared identifier is reported only once for each function it appears in
    confluent_kafka/src/confluent_kafka.c:1228:17: warning: implicit declaration of function ‘rd_kafka_fatal_error’ [-Wimplicit-function-declaration]
                     err = rd_kafka_fatal_error(rk, errstr, sizeof(errstr));
                     ^
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/opt/rails-seo-admin/env/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-z7znvu24/confluent-kafka/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6h0c4jx1/install-record.txt --single-version-externally-managed --compile --install-headers /opt/rails-seo-admin/env/include/site/python3.6/confluent-kafka" failed with error code 1 in /tmp/pip-install-z7znvu24/confluent-kafka/

**Comment by edenhill** [comment]
```
#error "confluent-kafka-python requires librdkafka v1.0.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
```

Install librdkafka-devel from the latest Confluent Platform rpm packages:
http://docs.confluent.io/current/installation.html

**Comment by Sudheer312** [comment]
> ```
> #error "confluent-kafka-python requires librdkafka v1.0.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
> ```
> 
> Install librdkafka-devel from the latest Confluent Platform rpm packages:
> http://docs.confluent.io/current/installation.html

@edenhill  We are using centos 7 machine 
https://github.com/confluentinc/confluent-kafka-python/issues/438 : this says we need devel version above 0.11.6
but only available till 0.11.5 in https://pkgs.org/download/librdkafka

Where can we find 0.11.6 devel for cenros 7 or is there any other fix

**Comment by edenhill** [comment]
http://docs.confluent.io/current/installation.html

**Comment by moisesrc13** [comment]
@edenhill 
I'm also testing in RHEL 7.7, using python 3.7 with the following configuration
import certifi
...
'bootstrap.servers': MY-BROKER,
'security.protocol': 'SASL_SSL',
'message.timeout.ms':'80000',                       
'ssl.ca.location': certifi.where(),
'sasl.mechanisms': 'PLAIN',                            
'sasl.username' : 'USER',
'sasl.password':'PASSWORD'

I have tried with different timeout values but always get the error
**Message delivery failed: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}**

I also tried with protocol `SASL_PLAINTEXT`. I noticed when using  `'debug': 'all'` that always get the same version of `librdkafka` regardless I have or not installed `librdkafka-devel`, which btw the version I got installed is 
```
librdkafka-devel-1.1.0_confluent5.3.1-1.el7.x86_64
librdkafka1-1.1.0_confluent5.3.1-1.el7.x86_64
```
 This is the librdkafka version I always see in the log
```
7|1573669393.372|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v1.2.0 (0x10200ff) rdkafka#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, GCC GXX PKGCONFIG INSTALL GNULD LDS LIBDL PLUGINS ZLIB SSL ZSTD HDRHISTOGRAM SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0xffff)
```

Is there a way to tell python from where to take `librdkafka`? i.e. to use the one I installed with brew at `/home/linuxbrew/.linuxbrew/opt/librdkafka/lib`

**Comment by moisesrc13** [comment]
I was able to fix my connection problem as follows
1. install brew
this will be installed under /home/linuxbrew/.linuxbrew/. At the end of the installation you will find final instructions to set brew in your PATH
2. install python3 using brew
$ brew install python3
3. Install librdkafka using brew
$ brew install librdkafka
the library is installed at /home/linuxbrew/.linuxbrew/opt/librdkafka/lib
4. Install openssl using brew
$ brew install openssl
5. Install python3
$ brew install python3
6. clone repo https://github.com/confluentinc/confluent-kafka-python.git
7. Build confluent-kafka using the openssl and librdkafka you installed with brew
$ cd confluent-kafka-python
$ export C_INCLUDE_PATH=/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include
$ export LIBRARY_PATH=/home/linuxbrew/.linuxbrew/opt/librdkafka/lib
$ C_INCLUDE_PATH=/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include LIBRARY_PATH=/home/linuxbrew/.linuxbrew/opt/librdkafka/lib python3.7 setup.py build
8. Install confluent-kafka
$ C_INCLUDE_PATH=/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include LIBRARY_PATH=/home/linuxbrew/.linuxbrew/opt/librdkafka/lib python3.7 setup.py install
