### ISSUE TITLE
Question : Link error LNK2019 in C++ with Visual Studio 2015 

### ISSUE THREAD

**Issue by coucoual** [edenhill/librdkafka#1777]
Description
===========
Hello all,

I hava an issue to link my code .... Build is OK, but not link .... 

I tried to use Nuget package, but it's the same .... 

I added rdkafkacpp.h and rdkafka.h in my PublicInterface folder 

I have this error :

NGEventCb.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::err2str(enum RdKafka::ErrorCode)" (__imp_?err2str@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ErrorCode@1@@Z) referenced in function "public: static unsigned char __cdecl NGEventCb::event_cb(class RdKafka::Event &)" (?event_cb@NGEventCb@@SAEAEAVEvent@RdKafka@@@Z)

How to reproduce
================
My .h
#ifndef NGEventCb_H
#define NGEventCb_H

#include "NGKafka.h"

#include "NGKafkaServices.h"

// System
#include "CATUnicodeString.h"
#include "CATBoolean.h"

#include "rdkafkacpp.h"

using namespace RdKafka;

//-----------------------------------------------------------------------

class ExportedByNGKafkaServices NGEventCb
{

public:
	static CATBoolean event_cb(Event &event);

	//-----------------------------------------------------------------------
};
#endif

My .cpp

#include "NGEventCb.h"

// NGSystem
#include "NGTrace.h"

CATBoolean NGEventCb::event_cb(Event &event) 
{
	NGDefineFunctionTrace(NGEventCb, hr);

	print_time();

	CATBoolean Run;

	switch (event.type())
	{
	case Event::EVENT_ERROR:
		std::cerr << "ERROR (" << err2str(event.err()) << "): " <<
			event.str() << std::endl;
		if (event.err() == ERR__ALL_BROKERS_DOWN)
			Run = false;
		break;

	case Event::EVENT_STATS:
		std::cerr << "\"STATS\": " << event.str() << std::endl;
		break;

	case Event::EVENT_LOG:
		fprintf(stderr, "LOG-%i-%s: %s\n",
			event.severity(), event.fac().c_str(), event.str().c_str());
		break;

	case Event::EVENT_THROTTLE:
		std::cerr << "THROTTLED: " << event.throttle_time() << "ms by " <<
			event.broker_name() << " id " << (int)event.broker_id() << std::endl;
		break;

	default:
		std::cerr << "EVENT " << event.type() <<
			" (" << err2str(event.err()) << "): " <<
			event.str() << std::endl;
		break;
	}

	return Run;
}

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.4
 - [x] Apache Kafka version: `1.1.0
 - [x] librdkafka client configuration: `N/A
 - [x] Operating system: `Windows 7
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mbmathews** [comment]
I am seeing a similar problem this error along with LNK2001 happens after a successful compile.  It is happening with other library functions too.   No insight yet, examined the lib and find the entries, but they are not an exact match given the C++ name mangling.  I am running Visual C++ 2017 Community Edition Version 15.6.1

error LNK2001: unresolved external symbol "__declspec(dllimport) public: static __int64 const RdKafka::Topic::OFFSET_END" (__imp_?OFFSET_END@Topic@RdKafka@@2_JB)

error LNK2001: unresolved external symbol "__declspec(dllimport) public: static __int64 const RdKafka::Topic::OFFSET_END" (__imp_?OFFSET_END@Topic@RdKafka@@2_JB)

error LNK2019: unresolved external symbol "__declspec(dllimport) int __cdecl RdKafka::wait_destroyed(int)" (__imp_?wait_destroyed@RdKafka@@YAHH@Z) referenced in function "public: virtual __cdecl HKSender::~HKSender(void)" (??1HKSender@@UEAA@XZ)

**Comment by mbmathews** [comment]
Found the issue I was having.  In my cmake project code, I was forced to add the define in my cmake:

target_compile_definitions(tpf.usvc.kafka PRIVATE LIBRDKAFKACPP_EXPORTS=0) 

for windows builds.

This seems to be a bug.  The rdkafka++ library should have all apis exported by default it should not be necessary to do this in an outside project.  I note that the same trick was used to get the c++ example to build and link.

Hope that helps.

**Comment by raulbocanegra** [comment]
Hi! You are right @mbmathews I remember adding that compile definition for the test to link. But forgot to add it as a INTERFACE target compile definition for rdkafka++.
From what I remember in shared builds on Windows if you don't define the macro LIBRDKAFKACPP_EXPORTS=0 then RD_EXPORT is not set to the correct value, but I'm not sure why because the export macros seems correct on rdkafkacpp.h.
Give me some time to try to add that macro as an INTERFACE compile definition and check if that works (I'm sure it will) adn them do a PR to avoid any user to add that macro explicitly as you did.

**Comment by raulbocanegra** [comment]
PR done #1800

**Comment by mbmathews** [comment]
Thanks.  I’ll give it a try.

Best,

Mike Mathews
mike@themathews.net<mailto:mike@themathews.net>
(m) 425-765-1237

On May 9, 2018, at 5:44 AM, Raul Bocanegra Algarra <notifications@github.com<mailto:notifications@github.com>> wrote:


PR done #1800<https://github.com/edenhill/librdkafka/pull/1800>

**Comment by edenhill** [comment]
@mbmathews  Any luck?

**Comment by ppngiap** [comment]
I resolve this issue on Windows by forcing the rdkafka++ to be a DLL instead of a static lib.  -- Tom

set(
    sources
    ConfImpl.cpp
    ConsumerImpl.cpp
    HandleImpl.cpp
    KafkaConsumerImpl.cpp
    MessageImpl.cpp
    MetadataImpl.cpp
    ProducerImpl.cpp
    QueueImpl.cpp
    RdKafka.cpp
    TopicImpl.cpp
    TopicPartitionImpl.cpp
)

add_library(rdkafka++ **SHARED** ${sources})

**Comment by raulbocanegra** [comment]
Hi @ppngiap, to be honest, I thought that rdkafka++ had RDKAFKA_BUILD_MODE added on its add_library as the target rdkafka does. This should be an improvement for the rdkafka++. I am wondering if using the same variable (RDKAFKA_BUILD_MODE) for both targets or creating a different one for rdkafka++. Probably @edenhill could help us with that.
