### ISSUE TITLE
How to handle fast open/closing of consumer with manual partition event handling

### ISSUE THREAD

**Issue by JeanMertz** [edenhill/librdkafka#1778]
**edit** I just realised I created this issue in the librdkafka repository, instead of the confluent-kafka-go repository (which is the client I'm using), I don't think there's anything specific to the Go library in this report, but if you disagree, I can re-open the issue there.

Description
===========

I've got a situation where I have a consumer that opens and closes really quickly. I do manual partition management. The following situation can occur:

- consumer starts
- partition assignment event received
- consumer closes
- partition assignment handling fails with `Local: Broker handle destroyed`

The reason this happens is because the partition assignment call is made after kafka.Close() has already been called.

Fixing this sounds easy, I should make sure that I only call close _after_ the handling of any events currently being processed are done. However, after doing this, I'm now in a different situation:

- consumer starts
- partition assignment event received
- partition assignment handled
- event handler closed, no more Kafka events accepted
- kafka close called, but it never releases

Looking into the logs, I can now see that the broker never closes, because it expects the client to handle `rebalance_cb`, and the log keeps returning `waiting for rebalance_cb`.

So I'm stuck in a no-win situation: if I close the kafka consumer before closing the event listening logic, it's possible that any still-in-flight response to Kafka will return an error, because the consumer was closed, but if I first handle any events, close the listener, and then close the kafka consumer, it will remain stuck forever, waiting for the rebalance event to be handled before closing the consumer.

Any thoughts on what the right solution is here?

Checklist
=========

Please provide the following information:

 - [x] librdkafka version `v0.11.4`
 - [x] Apache Kafka version: `v1.1`
 - [x] Operating system: `macOS`

**Comment by JeanMertz** [comment]
One solution I could think of, is:

- after closing the general event listener
- open a new event listener that only handles the unassign event
- now close the kafka consumer
- handle the unassign event
- close unassign event listener

That's doable, but I wonder if I'm perhaps misunderstanding the correct flow, requiring me to work around a problem that's better solved some other way.

**Comment by edenhill** [comment]
Corresponding Go issue: https://github.com/confluentinc/confluent-kafka-go/issues/65

The tricky part here is that Close() will trigger a rebalance/revoke, and that revoke is something the application *may* want to handle (for offset commits, etc), so we can't just handle it automatically from Close(). But at the same time the application has likely stopped polling the .Events channel at this point.

One alternative would be to pass an optional rebalance-callback to Close().
Another would be to have the application explicitly say: I'm no longer polling the Event channel, handle rebalances for me. For apps that want to handle the rebalance themselve they would simply keep polling the Event channel in parallel until it closes.

Not sure what's best.

**Comment by agis** [comment]
@edenhill Is that the case for the Poll-based consumer as well? Do we have to call `Unassign()` after we call `Close()` even though we don't pass a custom rebalance callback?

**Comment by edenhill** [comment]
@agis the poll based consumer should be fine since the rebalance callbacks will be triggered directly from Close() rather than emitted on a channel.
https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/event.go#L192

**Comment by agis** [comment]
True, they will be emitted by `Close()`, but what if we don't call `Poll()` after we call `Close()`?

This is what happens in our case and `Close()` blocks indefinitely.

**Comment by edenhill** [comment]
You shouldn't call Poll() after Close(), the consumer should be considered inoperable after Close().
Can you share your (relevant bits) of code?

**Comment by agis** [comment]
Sorry, I now understood what you meant by `Close()`. So it's expected that `Close()` will trigger the rebalance callback (we haven't provided any) itself. Fair enough, we'll try to provide a reproducible script and report back.
