### ISSUE TITLE
Decompression (codec 0x1) of message at 0 of 470 bytes failed: Local: Not implemented

### ISSUE THREAD

**Issue by lnashier** [edenhill/librdkafka#1779]
While consuming messages from a topic that has compressed (gzip) messages. Following error is encountered:
`Decompression (codec 0x1) of message at 0 of 470 bytes failed: Local: Not implemented`

 - [x] librdkafka version (release number or git tag): `v0.11.4` `13befa7053c43593fd6f2effdffbd83c3ea52eb7`
 - [x] Apache Kafka version: `0.10.2.1`
 - [x] librdkafka client configuration: `message.timeout.ms=100`, `auto.offset.reset = latest`
 - [x] Operating system: `GNU/Linux x86_64`

@edenhill

**Comment by lnashier** [comment]
Producer can use compression.codec = gzip

```
compression.codec                        |  P  | none, gzip, snappy, lz4 |          none | compression codec to use for compressing message sets. This is the default value for all topics, may be overriden by the topic configuration property `compression.codec`.  <br>*Type: enum value*
```

however,

**Comment by lnashier** [comment]
I tried 
$ sudo yum install zlib-devel
$ ./configure --reconfigure
grep WITH_ZLIB config.h # should say WITH_ZLIB 1
$ make
$ sudo make install

**Comment by fenghaojun** [comment]
@lnashier The error occurred to me too, can you tell me how you solve the problem?
