### ISSUE TITLE
hi，edenhill，when using the non-block method,how can i make suer all message send success?

### ISSUE THREAD

**Issue by hitljs** [edenhill/librdkafka#178]
In your kafka_performance.c I found that you use the msgs_count and the msgs_dr_ok to judge if all messages send to kafka success,when sending 2 msgs, i found that the dr_cb will call three times. is that ok.

**Comment by edenhill** [comment]
That sounds very strange.
Is this reproducible with rdkafka_performance? If so, what is your exact command line?

**Comment by hitljs** [comment]
sorry,i can't reproducible that, is it right using the e msgs_count and the msgs_dr_ok to judge if all messages send to kafka success? when i send 89 messages , the success number is 84 and no error find .

**Comment by edenhill** [comment]
The delivery report callback (dr_cb or dr_msg_cb) will be called once for each message that is accepted by `rd_kafka_produce()` (i.e., produce() does not return an error code).
Each such callback will provide an error code which is either NO_ERROR if the message was delivered or a specific error code for delivery failures.

You should be able to use this information to count the number of messages sent, failed, etc.

E.g.:
````
   if ((err = rd_kafka_produce(...)) != RD_KAFKA_RESP_ERR_NO_ERROR) {
        produce_failure_cnt++;
   } else {
        messages_in_transit++;
   }

...........
void my_delivery_cb (...err..) {

     if (err) { 
        messages_failed_delivery++;
    } else {
         messages_delivered++;
     }
    messages_in_transit--;
}
````
