### ISSUE TITLE
Make fails with undeclared __ATOMIC_SEQ_CST

### ISSUE THREAD

**Issue by nkrode** [edenhill/librdkafka#1782]
Hi - Make seems to fail for me with error: ‘__ATOMIC_SEQ_CST’ undeclared. Maybe my gcc version is too old, is this expected? Logs from configure and make attached below along with OS version.

**Configure**

./configure
using cache file config.cache
checking for OS or distribution... ok (Linux)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok (cached)
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok (cached)
checking executable ld... ok (cached)
checking executable nm... ok (cached)
checking executable objdump... ok (cached)
checking executable strip... ok (cached)
checking for pkgconfig (by command)... ok (cached)
checking for install (by command)... ok (cached)
checking for PIC (by compile)... ok (cached)
checking for GNU-compatible linker options... ok (cached)
checking for GNU linker-script ld flag... ok (cached)
checking for __atomic_32 (by compile)... ok (cached)
checking for __atomic_64 (by compile)... ok (cached)
checking for socket (by compile)... ok (cached)
parsing version '0x000b04ff'... ok (0.11.4)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok (cached)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok (cached)
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok (cached)
checking for zlib (by pkg-config)... ok
checking for zlib (by compile)... ok (cached)
checking for libcrypto (by pkg-config)... ok
checking for libcrypto (by compile)... ok (cached)
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for libssl (by pkg-config)... ok
checking for libssl (by compile)... ok (cached)
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... ok (cached)
checking for crc32chw (by compile)... ok (cached)
checking for regex (by compile)... ok (cached)
checking for strndup (by compile)... ok (cached)
checking for strerror_r (by compile)... ok (cached)
checking for pthread_setname_gnu (by compile)... ok (cached)
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok (cached)
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           y
  ENABLE_SSL               y
  ENABLE_SASL              y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               Linux
  SOLIB_EXT                .so
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.11.4
  MKL_APP_VERSION          0.11.4
  LIBS                     -lsasl2 -lssl -lcrypto   -lcrypto   -lz   -ldl -lpthread -lrt
  CFLAGS                        
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
Generated config.cache

Now type 'make' to build

**Make**
gcc -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -DLIBRDKAFKA_GIT_VERSION="\"\""  -c rdkafka.c -o rdkafka.o
In file included from rdposix.h:119,
                 from rd.h:68,
                 from rdkafka_int.h:44,
                 from rdkafka.c:38:
rdatomic.h: In function ‘rd_atomic32_add’:
rdatomic.h:69: warning: implicit declaration of function ‘__atomic_add_fetch’
rdatomic.h:69: error: ‘__ATOMIC_SEQ_CST’ undeclared (first use in this function)
rdatomic.h:69: error: (Each undeclared identifier is reported only once
rdatomic.h:69: error: for each function it appears in.)
rdatomic.h: In function ‘rd_atomic32_sub’:
rdatomic.h:86: warning: implicit declaration of function ‘__atomic_sub_fetch’
rdatomic.h:86: error: ‘__ATOMIC_SEQ_CST’ undeclared (first use in this function)
rdatomic.h: In function ‘rd_atomic32_get’:
rdatomic.h:100: warning: implicit declaration of function ‘__atomic_fetch_add’
rdatomic.h:100: error: ‘__ATOMIC_SEQ_CST’ undeclared (first use in this function)
rdatomic.h: In function ‘rd_atomic64_add’:
rdatomic.h:140: error: ‘__ATOMIC_SEQ_CST’ undeclared (first use in this function)
rdatomic.h: In function ‘rd_atomic64_sub’:
rdatomic.h:157: error: ‘__ATOMIC_SEQ_CST’ undeclared (first use in this function)
rdatomic.h: In function ‘rd_atomic64_get’:
rdatomic.h:171: error: ‘__ATOMIC_SEQ_CST’ undeclared (first use in this function)
make[1]: *** [rdkafka.o] Error 1
make[1]: Leaving directory `/home/nkrode/redis/deps/librdkafka/src'
make: *** [libs] Error 2

Checklist
=========
 - [x] librdkafka version (release number or git tag): `13befa7053c43593fd6f2effdffbd83c3ea52eb7`

 - [X ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`

Linux version 2.6.32-573.12.1.el6.x86_64 (mockbuild@x86-ol6-builder-05) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Tue Dec 15 06:42:08 PST 2015

**Comment by nkrode** [comment]
I had mixed up compiles between OS, this works with a clean install

**Comment by amitrch** [comment]
Hello nkrode,

I am getting in to the same problem. How did you resolve this. I couldn't quite understand your statement "mixed up compiles between OS" ??

Thanks,
Amit
