### ISSUE TITLE
SASL credentials via jaas file?

### ISSUE THREAD

**Issue by nkrode** [edenhill/librdkafka#1783]
Is there a way to configure properties for sasl.username and sasl.password by providing a path to jaas config file?

KafkaClient {
	com.kafka.security.PlainLoginModule required
	username="foo"
	password="bar";
}

**Comment by edenhill** [comment]
No, you will need to translate the jaas config (a java thing) to librdkafka configuration properties, namely:
```
sasl.mechanisms=plain
sasl.username=foo
sasl.password=bar
```

**Comment by nkrode** [comment]
👍
