### ISSUE TITLE
Get last committed offsets when a partition revocation occurs (enhancement)

### ISSUE THREAD

**Issue by accelerated** [edenhill/librdkafka#1785]
Description
===========
Currently, when the rebalance callback is called upon a partition revoke, the current partition list passed in the callback does _not_ contain a valid offset. It would be nice to have the `latest committed offset` so that the consumer can persist it if needed. The last offset should be available in the library when building the partition list. 

How to reproduce
================
Register a rebalance callback and check for `error == ERR__REVOKE_PARTITIONS`. Then verify that the offset is missing.

**Comment by edenhill** [comment]
You can call position() (last offsets of messages passed to application) or committed() (last committed offsets).

Depending on what you want to do, commit final offsets, or persist committed offsets out of band, one of those might be of interest.

**Comment by accelerated** [comment]
Will `comitted` block the callback thread/polling thread until the broker responds?

**Comment by edenhill** [comment]
Yep, it is a blocking operation waiting for the broker response.

**Comment by accelerated** [comment]
Ok thanks.
