### ISSUE TITLE
Broker ops are delayed up to 1000ms when not fetching

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#1787]
When a broker thread does not have any partitions to fetch it is highly likely that it will block on IO wait for up to 1000ms (regardless of `socket.blocking.max.ms`), if an op (such as OP_COMMIT) is enqueued on the
broker ops queue at this time it will not be served until an IO event is triggered (unlikely) or timeout occurs.

This is not a problem on platforms where we support io-based wakeups of queues, such as Linux and OSX, but we don't have those facilities on Windows and that's why people are seeing slow sync commits in .NET, as in this issue:
https://github.com/confluentinc/confluent-kafka-dotnet/issues/433

The long term fix is to rewrite the io/queue dispatcher, the short term fix is to check if there are any outstanding IOs we're waiting for, and if not, do the blocking wait on the queue instead of the IO.

**Comment by ricardoecosta** [comment]
How far up in the priority list is this @edenhill? Just to manage expectations from our side.

**Comment by edenhill** [comment]
I have a rudimentary patch ready that seems to work but needs more vetting. We'll try to get it in the upcoming release (end of june)

**Comment by ricardoecosta** [comment]
Awesome, thank you.

**Comment by edenhill** [comment]
Fixed on master by tcp-based io wake up

**Comment by GarrettDavis** [comment]
@edenhill In which release can we expect this fix? Was the tcp-based io wake up in 0.11.5, or will we need to wait for 1.0?

**Comment by edenhill** [comment]
tcp-based io wake up on Windows will be in the next maintenance release, v0.11.6, which is scheduled in about 2w. We'll roll the first RC soon.

**Comment by AlexzundeR** [comment]
@edenhill,  was this fix included in v0.11.6 release?

**Comment by edenhill** [comment]
@AlexzundeR Yes, it was. 
https://github.com/edenhill/librdkafka/releases/tag/v0.11.6 
#1930

**Comment by edenhill** [comment]
^ @mhowlett
