### ISSUE TITLE
GCC Compile error: undefined behaviour in case label expressions

### ISSUE THREAD

**Issue by arvidn** [edenhill/librdkafka#1789]
Description
===========

There are a few places in librdkafka where the (constant) expression for a case label invokes undefined behaviour. When building with GCC and `-fsanitize=undefined` this yields a compile error (but it does not when building without the undefined sanitizer).

The GCC behaviour is a bit unintuitive but is explained in this [ticket](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66880).

How to reproduce
================
Compile librdkafka with GCC 5, 6 or 7 with `-fsanitize=undefined`. Here's an example:

```
gcc-6 -Isrc -Igenerated/dummy -g -fno-omit-frame-pointer -fsanitize=undefined -fsanitize-undefined-trap-on-error -o objs/rdkafka.c.o -c src/rdkafka.c
```

With head of master, the error message is:

```
src/rdkafka.c: In function 'rd_kafka_poll_cb':
src/rdkafka.c:2629:9: error: case label does not reduce to an integer constant
         case RD_KAFKA_OP_OFFSET_COMMIT | RD_KAFKA_OP_REPLY:
         ^~~~
```

The same issue also exist in `src/rdkafka_cgrp.c` and `src/rdkafka_partition.c`

The problem is that the define `RD_KAFKA_OP_REPLY` is computed as `1 << 31`. The `1` integer literal has the type `signed int` and the shift operation causes an overflow of that type, which is undefined behaviour. As far as I can tell, this problem is fixed by changing the define like this:

`#define RD_KAFKA_OP_REPLY     (((unsigned int)1) << 31)  /* Reply op. */`

It also doesn't look quite right to interpret `rko->rko_type` as a signed type, since it has this bitmask behaviour, along with all the other variables and enums that combine with `RD_KAFKA_OP_REPLY`. But this is just from a brief skimming of the code.

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `13befa7053c43593fd6f2effdffbd83c3ea52eb7`
 - [ ] Apache Kafka version: Not applicable
 - [ ] librdkafka client configuration: Not applicable
 - [x] Operating system: Ubuntu and Darwin. But since this happens in the GCC Front-end, any system GCC supports would be affected.
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Hej Arvid!

Thank you, fixed on master.
