### ISSUE TITLE
Documentation: Add anchors for table of contents in INTRODUCTION.md

### ISSUE THREAD

**Issue by Enether** [edenhill/librdkafka#1791]
Hey, I introduced myself to the project and opened `INTRODUCTION.md`. 
There I saw a table of contents and saw that it corresponded to the paragraphs in the file but did not have links to them.

Are you okay with adding such links, so that a person can click on any of the titles and go to that part of the document? I'll open a PR if you give me the green light.

**Comment by edenhill** [comment]
Hey Stanislav :)

That sounds great, please file a PR! (As long as the html tags don't make the doc too ugly to view in plain text mode.)
