### ISSUE TITLE
Could not dynamic link rdkafka++

### ISSUE THREAD

**Issue by haosdent** [edenhill/librdkafka#180]
```
//usr/local/lib/librdkafka++.so: undefined reference to `rd_kafka_conf_set_socket_cb'//usr/local/lib/librdkafka++.so: undefined reference to `rd_kafka_opaque'
//usr/local/lib/librdkafka++.so: undefined reference to `rd_kafka_conf_set_open_cb'
//usr/local/lib/librdkafka++.so: undefined reference to `rd_kafka_conf_set_dr_msg_cb'
collect2: error: ld returned 1 exit status
```

My compile Command:
```
g++ -g -O2 -fPIC -Wall -Werror -Wfloat-equal -Wpointer-arith -Wno-non-virtual-dtor -I../src-cpp rdkafka_example.cpp -o rdkafka_example_cpp  -lrdkafka++ -lpthread
-lz -lrt -lstdc++ -lrdkafka
```

When I use 
```
g++ -g -O2 -fPIC -Wall -Werror -Wfloat-equal -Wpointer-arith -Wno-non-virtual-dtor -I../src-cpp rdkafka_example.cpp -o rdkafka_example_cpp  /usr/local/lib/librdkafka++.so /usr/local/lib/librdkafka.so -lpthread -lz -lrt -lstdc++
```
It is ok.

**Comment by edenhill** [comment]
Could you provide information about your system, gcc/clang version, and the full build output?
Thanks.

**Comment by edenhill** [comment]
I think the root of your problem is that you dont link your application with both `-lrdkafka++ -lrdkafka`, try that and it should work.

**Comment by haosdent** [comment]
you could check my command, i have link them. If i don't link rdkafka, it would produce more errors.

**Comment by edenhill** [comment]
Can you provide the full output of trying to link your application to rdkafka? You can hide secret parts.

**Comment by haosdent** [comment]
infact, it is all output of link error when i use lrdkafka++ -lrdkafka. If I only use lrdkafka++, it would produce more reference error.

**Comment by edenhill** [comment]
Okay, I will need some more info:
 * the exact command line used for linking your application?
 * what OS and version is this?

Thanks

**Comment by haosdent** [comment]
My command which produce error:

```
g++ -g -O2 -fPIC -Wall -Werror -Wfloat-equal -Wpointer-arith -Wno-non-virtual-dtor -I../src-cpp rdkafka_example.cpp -o rdkafka_example_cpp  -lrdkafka++ -lpthread
-lz -lrt -lstdc++ -lrdkafka
```

The command which is ok:

```
g++ -g -O2 -fPIC -Wall -Werror -Wfloat-equal -Wpointer-arith -Wno-non-virtual-dtor -I../src-cpp rdkafka_example.cpp -o rdkafka_example_cpp  /usr/local/lib/librdkafka++.so /usr/local/lib/librdkafka.so -lpthread -lz -lrt -lstdc++
```

It mean when I use dynamic link `-l` rdkafka and rdkafka++, it would return 

```
//usr/local/lib/librdkafka++.so: undefined reference to `rd_kafka_conf_set_socket_cb'
//usr/local/lib/librdkafka++.so: undefined reference to `rd_kafka_opaque'
//usr/local/lib/librdkafka++.so: undefined reference to `rd_kafka_conf_set_open_cb'
//usr/local/lib/librdkafka++.so: undefined reference to `rd_kafka_conf_set_dr_msg_cb'
collect2: error: ld returned 1 exit status
```

And when I don't use `-l`, use path instead of `-l`, the build is pass.

My system version:

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
```

gcc version:
```
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
```

g++ version:
```
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
```

ld version:

```
GNU ld (GNU Binutils for Ubuntu) 2.24
Copyright 2013 Free Software Foundation, Inc.
```

**Comment by edenhill** [comment]
Try placing `-lrdkafka` right after the C++ library (before the system libraries), linking order usually matters.

E.g.:
`g++ -g -O2 -fPIC -Wall -Werror -Wfloat-equal -Wpointer-arith -Wno-non-virtual-dtor -I../src-cpp rdkafka_example.cpp -o rdkafka_example_cpp  -lrdkafka++  -lrdkafka -lpthread
-lz -lrt -lstdc++`

**Comment by haosdent** [comment]
Yes, I try it. But the result is same.

**Comment by edenhill** [comment]
Did you ever get this sorted?
Have not seen any other reports on this

**Comment by bigdata2** [comment]
I am trying to build opencontrail and I am also seeing link errors with librdkafka++. 

The build command and the errors that I am getting are copied below. Note that the number of link errors are a lot, I have only copied a few of them here.

scons: `build/debug/vnsw/agent/contrail/contrail-vrouter-agent' is up to date.
g++ -o build/debug/analytics/vizd -Wl,--whole-archive -lbase -lcpuinfo -lprocess_info -lnodeinfo -l:librdkafka++.a -l:librdkafka.a -Wl,--no-whole-archive -g build/debug/analytics/collector_uve_types.o build/debug/analytics/collector_uve_constants.o build/debug/analytics/collector_uve_html.o build/debug/analytics/analytics_types.o build/debug/analytics/analytics_constants.o build/debug/analytics/analytics_html.o build/debug/analytics/redis_types.o build/debug/analytics/redis_constants.o build/debug/analytics/redis_html.o build/debug/analytics/uflow_types.o build/debug/analytics/uflow_constants.o build/debug/analytics/uflow_html.o build/debug/analytics/sflow_types.o build/debug/analytics/sflow_constants.o build/debug/analytics/sflow_html.o build/debug/analytics/viz_types.o build/debug/analytics/viz_constants.o build/debug/analytics/viz_html.o build/debug/analytics/viz_collector.o build/debug/analytics/ruleeng.o build/debug/analytics/collector.o build/debug/analytics/vizd_table_desc.o build/debug/analytics/viz_message.o build/debug/analytics/generator.o build/debug/analytics/redis_connection.o build/debug/analytics/redis_processor_vizd.o build/debug/analytics/options.o build/debug/analytics/stat_walker.o build/debug/analytics/protobuf_collector.o build/debug/analytics/protobuf_server.o build/debug/analytics/sflow.o build/debug/analytics/sflow_generator.o build/debug/analytics/sflow_collector.o build/debug/analytics/usrdef_counters.o build/debug/analytics/sflow_parser.o build/debug/analytics/ipfix_collector.o build/debug/analytics/protobuf_schema.pb.o build/debug/analytics/main.o build/debug/analytics/buildinfo.o build/debug/analytics/db_handler.o build/debug/analytics/OpServerProxy.o build/debug/analytics/syslog_collector.o build/debug/analytics/parser_util.o -Lbuild/lib -Lbuild/debug/sandesh -Lcontroller/src/sandesh -Lbuild/debug/analytics/ruleparser -Lcontroller/src/analytics/ruleparser -Lbuild/debug/discovery/client -Lcontroller/src/discovery/client -Lbuild/debug/http/client -Lcontroller/src/http/client -Lbuild/debug/xml -Lcontroller/src/xml -Lbuild/debug/database -Lcontroller/src/database -Lbuild/debug/base -Lcontroller/src/base -Lbuild/debug/io -Lcontroller/src/io -Lbuild/debug/net -Lcontroller/src/net -lcassandra_cql -lcassandra -lgendb -lboost_regex -lssl -lcrypto -lsasl2 -lcpuinfo -lds -lio -lsandesh -lhttpc -lhttp -lvncapi -lhttp_parser -lcurl -lruleparser -lxml -lprocess_info -lnodeinfo -lbase -lio -lz -lnet -lipfix -lmisc -lsandeshvns -lpugixml -lhiredis -lprotobuf -lzookeeper_client -lzookeeper_mt -lboost_filesystem -lboost_program_options -lboost_system -llog4cplus -lpthread -ltbb -lboost_python -lpython2.7 -lrt
//usr/local/lib/librdkafka++.a(ConfImpl.o): In function `RdKafka::ConfImpl::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const':
librdkafka/src-cpp/rdkafkacpp_int.h:428: undefined reference to `rd_kafka_conf_get'
librdkafka/src-cpp/rdkafkacpp_int.h:433: undefined reference to `rd_kafka_conf_get'
librdkafka/src-cpp/rdkafkacpp_int.h:438: undefined reference to `rd_kafka_topic_conf_get'
librdkafka/src-cpp/rdkafkacpp_int.h:443: undefined reference to `rd_kafka_topic_conf_get'
//usr/local/lib/librdkafka++.a(ConfImpl.o): In function `RdKafka::ConfImpl::set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RdKafka::Conf const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
librdkafka/src-cpp/rdkafkacpp_int.h:307: undefined reference to `rd_kafka_conf_set_default_topic_conf'
//usr/local/lib/librdkafka++.a(HandleImpl.o): In function `RdKafka::consume_cb_trampoline(rd_kafka_message_s*, void*)':
librdkafka/src-cpp/HandleImpl.cpp:37: undefined reference to `rd_kafka_topic_opaque'
//usr/local/lib/librdkafka++.a(HandleImpl.o): In function `RdKafka::HandleImpl::set_common_config(RdKafka::ConfImpl*)':
librdkafka/src-cpp/HandleImpl.cpp:210: undefined reference to `rd_kafka_conf_set_throttle_cb'
librdkafka/src-cpp/HandleImpl.cpp:231: undefined reference to `rd_kafka_conf_set_rebalance_cb'
librdkafka/src-cpp/HandleImpl.cpp:237: undefined reference to
