### ISSUE TITLE
Got different compiled static libraries on different Linux Kernel version

### ISSUE THREAD

**Issue by hiberabyss** [edenhill/librdkafka#1804]
Description
===========

The compiled kafka static library is different for containers based on same image while running on different operation systems.

The compiled `librdkafka.a` on macOS lacked symbols like `RdKafka::err2str`, while `librdkafka.a` compiled on Linux container had these symbols `RdKafka::err2str`:

``` shell
# Container on macOS did not have that symbol
[root@e1e6c4cd266f kafka]# strings librdkafka.a | grep 'RdKafka::err2str'

# Container on linux
root@PEKdev242:3rd/kafka # strings librdkafka.a | grep 'RdKafka::err2str'
RdKafka::err2str
```

Following is the kernel info of container run on macOS:

```
[root@e1e6c4cd266f /]# uname  -a
Linux e1e6c4cd266f 4.9.49-moby #1 SMP Fri Dec 8 13:40:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Following is the kernel info of container run on Linux:

```
root@PEKdev242:3rd/kafka # uname -a
Linux PEKdev242.dev.fwmrm.net 3.10.0-493.el7.x86_64 #1 SMP Tue Aug 16 11:45:26 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information (Only related with compiling, remove useless checklist):

 - [x] librdkafka version (release number or git tag): `0.9.2`
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is most likely due to different C++ name mangling on different toolchains.
Try `objdump -t src-cpp/librdkafka++.a | c++filt`

**Comment by edenhill** [comment]
your librdkafka version is really outdated, btw.
