### ISSUE TITLE
Consumer does not read topic under windows

### ISSUE THREAD

**Issue by gitadani** [edenhill/librdkafka#1819]
Description
===========

I am trying to consume a topic with the example programs, but it receives no messages: 

rdkafka_consumer_example_cpp.exe -g 400 -b 10.1.10.81:9092 -v logging.trading.warning
rdkafka_example.exe -d all -C -b 10.1.10.81:9092 -t logging.trading.warning -p 0

However, the linux version compiled from the same source of the library works fine.

According to the network capture the windows version does not send GroupCoordinator-Request message, which may be part of the problem.
Do you have an idea what the root cause could be?

Thank you,
Regards,
Attila

Checklist
=========

 - [x] librdkafka version (release number or git tag): v0.11.4
 - [x] Apache Kafka version: 1.1.0
 - [x] Operating system: Windows x64
 - [x] Provide logs (with `debug=all` as necessary) from librdkafka
 
[debug_cpp.txt](https://github.com/edenhill/librdkafka/files/2035111/debug_cpp.txt)
[debug_c.txt](https://github.com/edenhill/librdkafka/files/2035147/debug_c.txt)

**Comment by edenhill** [comment]
Interesting, I'm trying to figure how the fetch backoff can get so high.

**Comment by gitadani** [comment]
I built it myself on windows (visual studio 2015)

2018-05-24 17:35 GMT+02:00 Magnus Edenhill <notifications@github.com>:

**Comment by gitadani** [comment]
I tried and it works fine, both the consumer example program and my test
application!
So, it must my build! However, I just used librdkafka.sln from the win32
folder...
Anyway, the redist package is just perfect for me, so I will use that.
Thanks a lot.
Should I close this case?

2018-05-24 19:25 GMT+02:00 Magnus Edenhill <notifications@github.com>:

**Comment by edenhill** [comment]
Happy to hear that!
