### ISSUE TITLE
Consumergroup lag statistics 

### ISSUE THREAD

**Issue by koushikchitta** [edenhill/librdkafka#1822]
Description
===========
Is there a way to get **specific consumer group** lag statistics ? Currently the consumer lag statistics gives data even if the message was consumed by any consumer group member.

How to reproduce
================
N/P

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.3`
 - [x] Apache Kafka version: `0.10.2.0`

**Comment by edenhill** [comment]
librdkafka will only reports stats about its own client instances, which uses at most one consumer group.
Stats defined here:
https://github.com/edenhill/librdkafka/wiki/Statistics

**Comment by dodomouse** [comment]
in sample of https://github.com/edenhill/librdkafka/wiki/Consumer-lag-monitoring, I see consumer_lag(238952) can be calculated by hi_offset(342283286) - next_offset(342044334), but in https://github.com/edenhill/librdkafka/wiki/Statistics, you said that consumer_lag=hi_offset - app_offset, I don't know the difference between next_offset and app_offset, could you give more information?

**Comment by edenhill** [comment]
next_offset is the next offset to fetch from the broker, fetched messages go into the pre-fetch queue.
app_offset is the last offset consumed by the application.
If you want to  know consumer lag you should use app_offset, not next_offset.

**Comment by dodomouse** [comment]
Hello edenhill,
I use sample-rdkafka_performance to try to get json message which generated by rd_kafka_conf_set_stats_cb(), I find that if I set groupid, then it won't print hi_offset/consumer_lag and etc..., if I remove -G option, then it comes out. I feel puzzled, I just want to monitor consumer lag and the length of the whole message queue for one topic and one group, could you give some samples or more detailed information?

**Comment by edenhill** [comment]
The consumer lag is only calculated when partitions have been assigned and are fetched.
When you use the high-level balanced consumer (-G) it will take some time for the group to rebalance before you get an assignment, and even then you might not get assigned all, or any, partitions of the topics you subscribed to (depending on the number of other members in the group).

**Comment by dodomouse** [comment]
Thanks a lot :+1:
