### ISSUE TITLE
rdkafka producer Memory Leak

### ISSUE THREAD

**Issue by syedtoah** [edenhill/librdkafka#1824]
Description
===========
rdkafka producer leaks memory over time and does not get freed. I have seen the memory being consumed to be about 5 to 9 GB and keeps going up.
The problem is when I am sending messages I dont see the issue, but when the system is idle I see the system increases the memory but 16384 (buff value below) and does not get freed. 

Am I missing some function call that will free the memory right after use? Other wise why is the memory increasing while the system is almost idle not transferring any messages.

Any pointers will be helpful, thanks.

Code

`
            if (rd_kafka_conf_set(conf, "statistics.interval.ms",
                "1000",
                errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK)
            {
                fprintf(stderr, "%% %s\n", errstr);
                exit(1);
            }

            rd_kafka_conf_set_log_cb (conf, wamgrKafkaClientLogger);
            //rd_kafka_conf_set_error_cb (conf, wamgrKafkaClientErrCb);
            rd_kafka_conf_set_error_cb (conf, kafkaClientErrorHandling);

            rd_kafka_conf_set_dr_msg_cb (conf, wamgrKafkaClientDRCb);

            if (rd_kafka_conf_set(conf, "queue.buffering.max.messages",
                "600000",
                errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK)
            {
                fprintf(stderr, "%% %s\n", errstr);
                exit(1);
            }
            if (rd_kafka_conf_set(conf, "queue.buffering.max.ms",
                "5",
                errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK)
            {
                fprintf(stderr, "%% %s\n", errstr);
                exit(1);
            }

            if (rd_kafka_conf_set(conf, "socket.timeout.ms",
                KAFKA_BROKER_SOCKET_TIMEOUT_MS,
                errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK)
            {
                fprintf(stderr, "%% %s\n", errstr);
                exit(1);
            }
            
            if (rd_kafka_conf_set(conf, "socket.max.fails",
                KAFKA_BROKER_MAX_FAILS,
                errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK)
            {
                fprintf(stderr, "%% %s\n", errstr);
                exit(1);
            }

            if (rd_kafka_conf_set(conf, "socket.send.buffer.bytes",
                KAFKA_BROKER_SOCKET_SEND_BUFFER_SIZE,
                errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK)
            {
                fprintf(stderr, "%% %s\n", errstr);
                exit(1);
            }

            if (rd_kafka_conf_set(conf, "debug",
                "topic,broker,queue,msg",
                errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK)
            {
                fprintf(stderr, "%% %s\n", errstr);
                exit(1);
            }

            /* Create Kafka handle */
            /* Note: Please dont use conf after this function call, as it is getting free inside */
            if (!(rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf, errstr, sizeof(errstr))))
            {
                fprintf(stderr, "%% Failed to create new producer: %s\n", errstr);

                exit(1);
            }
            unsigned char buf[16384];
            rd_kafka_produce(rkt, partition, RD_KAFKA_MSG_F_COPY, buf, len, "str", strlen("str"), 0);

            if(rd_kafka_outq_len(rk) > 0)
            {
            }

        rd_kafka_poll(rk, 0);
`

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<0.9.2>`
 - [ ] Apache Kafka version: `<>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<Centos (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
v0.9.2 is really old, please reproduce on the latest release v0.11.4.

Your code is incomplete.

**Comment by syedtoah** [comment]
This is the send function from which I had given an excerpt earlier,
The buf size is 16K and the length may vary depending on the msg size

This API is called when ever the message is ready to be sent, which happens very often.

`    void kafkaClientSend(wamgrKafkaClientMsg * entry, char * buf, size_t len, BOOL isvCPE_Events_Message)
    {
       rd_kafka_topic_t *rkt;

        char *mac = 0; //[MAC_ADDR_COMPRESSED_STRLEN] = {0};

    if(isvCPE_Events_Message)
    {
        rkt = rkt_vCPE_Events;
        mac = entry->cpe_MacAddr;
        //memcpy (mac, entry->cpe_MacAddr, MAC_ADDR_COMPRESSED_STRLEN);
    }
    else
    {
        rkt = rkt_vCPE_MessageStream;
        if (entry->messageType == WAMgrKafkaClient_MSG_DEVICE_DHCP_STREAM)
        {
            //memcpy (mac, entry->u.xPC_Device_DHCP_Stream_Msg.deviceMacAddr, MAC_ADDR_COMPRESSED_STRLEN);
            mac = entry->u.xPC_Device_DHCP_Stream_Msg.deviceMacAddr;
        }
    }

    if (rkt != 0)
    {
        statsDone = False;
        size_t macLen = 0;

        if (mac != 0)
            macLen = MAC_ADDR_COMPRESSED_STRLEN;
        if (rd_kafka_produce(rkt, partition, RD_KAFKA_MSG_F_COPY, buf, len, mac, macLen, 0) == -1)
        {
            //fprintf(stderr, "%% Failed to produce to topic %s " "partition %i: %s\n", 
             rd_kafka_topic_name(rkt), partition, rd_kafka_err2str(rd_kafka_errno2err(errno)));

            /* Poll to handle delivery reports */

            kafkaClientStatsIncDebugCount(kafkaClientDbgMsgNotSent);
            if (errno == ENOBUFS)
            {
                kafkaClientStatsIncDebugCount(kafkaClientDbgMsgBufferSizeOverFlow);
            }
            else if (errno == ESRCH)
            {
                kafkaClientStatsIncDebugCount(kafkaClientDbgMsgUnknownPartition);
            }
            else if (errno == ENOENT)
            {
                kafkaClientStatsIncDebugCount(kafkaClientDbgMsgUnknownTopic);
            }
            else if (errno == EMSGSIZE)
            {
                kafkaClientStatsIncDebugCount(kafkaClientDbgMsgMessageSizeLargerThanConfigured);
            }
        }
        else
        {
            // Increment sent message count
            kafkaClientStatsIncDebugCount(kafkaClientDbgMsgSent);

            if(isvCPE_Events_Message)
                kafkaClientStatsIncDebugCount(kafkaClientDbgEventMsgSent);
            else
                kafkaClientStatsIncDebugCount(kafkaClientDbgStreamMsgSent);

            if(rd_kafka_outq_len(rk) > 0)
            {
                //rd_kafka_poll(rk, 0);
            }
        }

        rd_kafka_poll(rk, 0);

    }
    }

`

**Comment by edenhill** [comment]
Looks fine to me.

Please do this:
 1. Upgrade to librdkafka v0.11.4
 2. Reproduce with valgrind
 3. Make sure to call rd_kafka_poll()  at regular intervals, even if no new messages are produced, to serve the delivery report callbacks for already produced messages - if you've registered a delivery report callback.

**Comment by akin-pan** [comment]
@edenhill @syedtoah I try to solve rdkafka producer leaks memory issue for a long time.thanks for your reply,when I call rd_kafka_poll() at a timer callback,I fixed the issue too.I think we can give some notice in the example files.
