### ISSUE TITLE
how does librdkafka work with avro like java,does it support? 

### ISSUE THREAD

**Issue by miaojianxin** [edenhill/librdkafka#1827]
now, i want to write a program : a producer send msg  processed by avro ,i read this type of program like java,  if i include the avro c libraray, and  before send the msg , i process the msg using avro, and then send it through librdkafka , does it right? thank you

**Comment by edenhill** [comment]
Confluent's [libserdes](https://github.com/confluentinc/libserdes) provides a schema-registry client for C and C++ which is suitable to use with librdkafka.

See the examples here:
https://github.com/confluentinc/libserdes/tree/master/examples
