### ISSUE TITLE
Update documentation (auto commit issue)

### ISSUE THREAD

**Issue by nick-zh** [edenhill/librdkafka#1829]
Heya

Maybe i am mistaken, but i think https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management#configuration-properties
sould be updated. 

If i read this, i am under the assumption, that if i set enable.auto.commit to false, i always have to manually commit my messages. But it seems enable.auto.offset.store has also set to be false for this, unless i am misunderstanding something

Cheers,
Nick

**Comment by rnpridgeon** [comment]
Hey Nick, 

Your understanding is correct, by setting `enable.auto.commit=false` you are preventing librdkafka from committing your offsets to the broker automatically. librdkafka will however continue committing offsets as the application receives them to the local store as long as `enable.auto.offset.store=true`(default). It is still up to the application to commit these messages back to Kafka but you still lack total control over offset tracking. 

In my experience what most people want to do is set `enable.auto.commit=true` with `enable.auto.offset.store=false`. This allows the consumer to control when an offset is considered committed by calling `store_offsets()` while maintaining the convenience of `enable.auto.commit.

**Comment by nick-zh** [comment]
@rnpridgeon one more thing for my understanding, so when i stop a client and restart it, if there is a local offset, it will use this instead of the one stored on the broker?
also i was a bit hasty, so having ```enable.auto.offset.store=false``` and ```enable.auto.commit=true``` will give me full control? but wont ```enable.auto.commit=true``` just commit messages from time to time that i consume or am i mistaking something? (i am using the php-rdkafka)

**Comment by edenhill** [comment]
The local offset store is not an offset commit, but an in-memory store of the next offset to commit.

enable.auto.commit will commit the last stored offset for each partition (if it has changed from the last commit) at regular intervals, at rebalance, and at consumer shutdown,.
With `enable.auto.offset.store=false` the auto commit still runs, but you control what offsets it commits by explicitly calling store_offsets().

I'm not sure that php-rdkafka exposes the store_offsets() API

**Comment by nick-zh** [comment]
@edenhill thx a lot, this clears up a lot. As far as i can see php-rdkafka has a function ```offsetStore``` for a topic which calls ```rd_kafka_offset_store``` (https://github.com/arnaud-lb/php-rdkafka/blob/master/topic.c#L328) i am uncertain if this now stores directly to the broker or to the local offset store.

**Comment by nick-zh** [comment]
@edenhill @rnpridgeon i have updated the page (https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management#configuration-properties) please review if that is ok.
For me it is a bit confusing though, shouldnt the section for ```enable.auto.commit```
> If false, the application will manually have to call rd_kafka_offset_store() to store an offset (optional)
say that you manually need to call commit? Since ```rd_kafka_offset_store``` since this is used for the local offset store?

**Comment by edenhill** [comment]
Thanks for your update, I clarified some more on that page. Please reload and see if it is clearer now

**Comment by nick-zh** [comment]
@edenhill yes thanks a lot for the help, for me this makes it a lot clearer now :+1:
