### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by zpzkit** [edenhill/librdkafka#183]
I have memory leaks  with the  rdkafka, but i dont know  where it is.
I only use produce.
can you tell me where can be memory leaks.
thank you very much.
This problem for a year .

**Comment by edenhill** [comment]
What flags are you using when calling `rd_kafka_produce()`?

Have you run your application with valgrind to locate the memory leaks?

**Comment by zpzkit** [comment]
/*initialize*/
int kafka_init_all(inform_kafka_hdl_t *writer)
{
	if(kafka_init_conf(writer) != 0){
		return -1;
	}
	/*init write*/
	if(inform_init_write(writer) != 0){
		return -2;
	}

	return 0;
}

/*initialize  configuration*/
int kafka_init_conf(inform_kafka_hdl_t *kafka_hdl)
{
    int ret;
	/*conf create*/
	ret = inform_conf_create(kafka_hdl);
    if(ret != 0){
        return ERROR_CREATE_CONF;
    }

	/*set error callback*/
    rd_kafka_conf_set_error_cb(kafka_hdl->conf, err_cb);
    rd_kafka_conf_set_dr_cb(kafka_hdl->conf, msg_delivered);
    /* Producer config */
    rd_kafka_conf_set(kafka_hdl->conf,
    				  "queue.buffering.max.messages", "500000",errstr, sizeof(errstr));
    rd_kafka_conf_set(kafka_hdl->conf,
					  "message.send.max.retries", "1", errstr, sizeof(errstr));
    rd_kafka_conf_set(kafka_hdl->conf,
					  "retry.backoff.ms", "50", errstr, sizeof(errstr));

    if (rd_kafka_conf_set(kafka_hdl->conf, "compression.codec",
						  kafka_hdl->compression_type,errstr, sizeof(errstr))
						  != RD_KAFKA_CONF_OK)
	{
        fprintf(stderr, "%% %s\n", errstr);
        return ERROR_SET_KAFKA_CONF;
    }

    if (rd_kafka_topic_conf_set(kafka_hdl->topic_conf,
                    "request.required.acks", kafka_hdl->send_mode,errstr, sizeof(errstr))
                    != RD_KAFKA_CONF_OK)
    {
        fprintf(stderr, "%% %s\n", errstr);
        return ERROR_SET_TOPIC_CONF;
    }
	return 0;
}


/*create configuration handle*/
int inform_conf_create(inform_kafka_hdl_t *kafka_hdl)
{
    if(kafka_hdl == NULL) {
        assert(0);
        fprintf(stderr, "%% kafka_hdl is NULL fail!!!\n");
    }

    if((kafka_hdl->conf = rd_kafka_conf_new()) == NULL) {
        fprintf(stderr, "%% Create kafka conf fail!!!\n");
        return ERROR_CREATE_KAFKA_CONF;
    }

    if((kafka_hdl->topic_conf = rd_kafka_topic_conf_new()) == NULL) {
        fprintf(stderr, "%% Create kafka topic conf fail!!!\n");
        return ERROR_CREATE_KAFKA_TOPIC_CONF;
    }
	return 0;
}

/*create handle*/
int inform_init_write(inform_kafka_hdl_t *kafka_hdl)
{
    /* Create Kafka handle */
    if(kafka_hdl->rk == NULL) {
        if (!(kafka_hdl->rk = rd_kafka_new(RD_KAFKA_PRODUCER, kafka_hdl->conf,
                        errstr, sizeof(errstr)))) {
            fprintf(stderr,
                "%% Failed to create Kafka producer: %s\n",
                errstr);
            return ERROR_KAFKA_NEW;
        }
    }
	/*Add brokers*/
	int ret;
	if((ret = rd_kafka_brokers_add(kafka_hdl->rk, kafka_hdl->brokers)) == 0){
        fprintf(stderr, "%% No valid brokers specified %s\n", kafka_hdl->brokers);
		return ERROR_KAFKA_BROKERS_ADD;
	}
	/*create topic*/
    if((kafka_hdl->rkt = rd_kafka_topic_new(kafka_hdl->rk,kafka_hdl->topic_id, kafka_hdl->topic_conf)) == NULL) {
        fprintf(stderr,
            "%% Failed to create Kafka producer: %s\n",
            errstr);
        return ERROR_KAFKA_TOPIC_NEW;
    }
    fprintf(stdout,"Create the producter Success\n");
	return 0;
}


int inform_produce(int partition, inform_kafka_hdl_t *sender,
						 char *send_buf,int send_len)
{
	int ret = 0;
    if(sender->rkt == NULL || sender->rk == NULL){
        return PRODUCE_ERROR_BAD_HEAD;
    }
    if (rd_kafka_produce(sender->rkt, partition,
                RD_KAFKA_MSG_F_COPY, send_buf, send_len,
                NULL, 0, NULL) != 0) {
		if(errno == ENOBUFS){
			ret = PRODUCE_ERROR_ENOBUFS;
		}else if(errno == EMSGSIZE){
			ret = PRODUCE_ERROR_EMSGSIZE;
		}else if(errno == ESRCH){
			ret = PRODUCE_ERROR_ESRCH;
		}else if(errno == ENOENT){
			ret = PRODUCE_ERROR_ENOENT;
		}
        /* Poll to handle delivery reports */
        rd_kafka_poll(sender->rk, 10);
		return ret;
    }

    /* Must poll to handle delivery reports */
    rd_kafka_poll(sender->rk, 0);

    return ret;
}


this is  my code.
I have used valgrind,but it's speed is so slow.
I cant use it .

**Comment by zpzkit** [comment]
I have found out the error.
I use have a problem.
But still want to thank you for your help.
thank you.

**Comment by edenhill** [comment]
Thats great news!
