### ISSUE TITLE
Query on queue.enqueue.timeout.ms in latest Kafka version support.

### ISSUE THREAD

**Issue by karthikeyanajendran1984** [edenhill/librdkafka#1830]
hi @edenhill or anyone.. please let me know the "queue.enqueue.timeout.ms" is supported in the latest kafka version and librdkafka version. i cannot able to see this parameter in latest apache Kafka version documentation and librdkafka CONFIGURATION.md file.

If supported, is it required to be used in Kafka producer.properties file or need to be producer client side application through librdkafka property settings. ??

**Comment by edenhill** [comment]
I believe that's a property from the old Scala producer, it is not supported by the new Java producer or librdkafka.

Both the Java and librdkafka's produce() APIs are asynchronous, they will not block, so that configuration property does not apply.

**Comment by karthikeyanajendran1984** [comment]
Thanks @edenhill .  As you have mentioned produce API (single or batch API) call will not block while enqueue message in to producer queue, So it is application responsibility to have a blocking loop which can does re-pushing messages received as queue full error ?

**Comment by edenhill** [comment]
Yes, or use RD_KAFKA_MSG_F_BLOCK, but you will need a separate thread doing poll in that scenario
