### ISSUE TITLE
Superfluous semicolon in rdkafkacpp.h

### ISSUE THREAD

**Issue by martukas** [edenhill/librdkafka#1831]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Superfluous semicolon causes warnings on recent compilers:
```
/somewhere/include/librdkafka/rdkafkacpp.h:78:2: warning: extra ‘;’ [-Wpedantic]
 };
  ^
```

How to reproduce
================
Build on recent compiler with -Wpedantic
I was building on:
g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.4
 - [x] Apache Kafka version: irrelevant
 - [x] librdkafka client configuration: irrelevant
 - [x] Operating system: Ubuntu 18.04
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: see above, irrelevant
 - [x] Provide broker log excerpts: irrelevant
 - [x] Critical issue: if someone happens to be building with -Werror, perhaps yes

**Comment by edenhill** [comment]
Thank you, will fix!
