### ISSUE TITLE
Disabling ALL error logs on the console

### ISSUE THREAD

**Issue by skandhas1** [edenhill/librdkafka#1832]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Need to suppress all the console logs from librdkafka. For example, below logs,

%3|1527807323.707|FAIL|rdkafka#producer-1| [thrd:1.1.2.1:9092/bootstrap]: 1.1.2.1:9092/bootstrap: Connect to ipv4#1.1.2.1:9092 failed: Connection refused
% ERROR CALLBACK: rdkafka#producer-1: Local: Broker transport failure: 1.1.2.1:9092/bootstrap: Connect to ipv4#1.1.2.1:9092 failed: Connection refused
% ERROR CALLBACK: rdkafka#producer-1: Local: All broker connections are down: 1/1 brokers are down

I tried setting log_level config to 0 and 7. Both didn't help. Am i missing any other config other than log_level for disabling logs?

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The `log_level` property seems to work for me. Make sure you are not specifying any `debug` config properties since that will override log_level and set it to 7.

```
$ examples/rdkafka_example -b xyz -C -t test -p 0 -X log_level=0
<..silence..>

$ examples/rdkafka_example -b xyz -C -t test -p 0
1527837287.021 RDKAFKA-3-FAIL: rdkafka#consumer-1: [thrd:xyz:9092/bootstrap]: xyz:9092/bootstrap: Failed to resolve 'xyz:9092': nodename nor servname provided, or not known
```
