### ISSUE TITLE
Confused about topic.blacklist setting

### ISSUE THREAD

**Issue by cvuillemez** [edenhill/librdkafka#1834]
Description
===========

This setting is described as 

> Topic blacklist, a comma-separated list of regular expressions for matching topic names that should be ignored in broker metadata information as if the topics did not exist. 

When we use a consumer group, is the setting applied to all consumers within the same group ?
It 's seems not, so I need to explain why I ask this question:

Suppose you have:
* a consumer group "mygroup" with a consumer C1 and consumer C2
* C1 subscribes to "topicA, topicB, topicC" 
* C2 subscribes to "^topic.*" and has a `topic.blacklist = "topicC"`

Everything works fine, C1 consume 3 topics and C2 consumer only 2.

But when I restarted a consumer (C1), I don't know why, the `topic.blacklist` was suddently applied to each consumer, so the topicC has no more consumers...

I can't reproduce it easily... can it be a bug, or is it a bad use of this setting ?

Checklist
=========

 - [x] librdkafka version : `0.11.3`
 - [x] Apache Kafka version: `1.0.1`
 - [x] Operating system: `Ubuntu 16.04.3 LTS`

**Comment by edenhill** [comment]
topic.blacklist only affects the local client, but if the local client is elected group leader then it is responsible for assigning topics and partitions to the members in the group, with a blacklist in place that client will not see topiC and will thus not assign it to any member, regardless if they have blacklist configured or not.

**Comment by cvuillemez** [comment]
So clear now.. :)
Is there a doc or code who shows which setting is local or group-wide ?

**Comment by edenhill** [comment]
Pretty much all client configuration properties only have local effect, but they may have secondary effects like this one.
