### ISSUE TITLE
KakfaError - Message at offset might be too large

### ISSUE THREAD

**Issue by pascals-ager** [edenhill/librdkafka#1835]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>
KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Message at offset 5077 might be too large to fetch, try increasing receive.message.max.bytes"}

How to reproduce
================
Simply running the consumer. As the number of messages published increases, I see this error. It does not occur when the number of messages are low.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `librdkafka v0.11.4  h5623a8b_0`

 - [x] Apache Kafka version: `11-1.0.1`(wrong)---->>  `1.0.0`

 - [x] librdkafka client configuration: `receive.message.max.bytes': 1000000000, fetch.max.bytes': 52428800, max.partition.fetch.bytes': 52428800(also tried 1MB) ,fetch.message.max.bytes': 52428800 (also tried 1MB), auto.offset.reset: earliest` (Also tried without any config but auto.offset.reset:earliest)
 - [x] Operating system: `Ubuntu 16.04.4 LTS`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
How many partitions are you consuming?

This error may be seen when max.partition.fetch.bytes * numPartitionsConsumed > receive.message.max.bytes

**Comment by pascals-ager** [comment]
I am using 3 partitions. I did set receive.message.max.bytes=1GB to take no
chances..

The issue persists..

**Comment by pascals-ager** [comment]
I was incorrect with my Kafka broker version. I am using v 1.0.0.

And the error seems to be occurring when the message is empty: _b''_
Is there a specific way I can handle empty messages?

**Comment by pascals-ager** [comment]
I am seeing this behavior consistently. I do not understand why the consumer is consistently reaching the end of a partition and throwing an error. Shouldn't the msg be 'None' instead?

if I simply ignore both the errors, it looks like the processing works correclty (i.e no records are dropped. Throughtput however is another question)


```
KafkaError{code=MSG_SIZE_TOO_LARGE,val=10,str="Message at offset 3861 might be too large to fetch, try increasing receive.message.max.bytes"} at topic - consume-count, partition - 0, offset - 3861
b''

KafkaError{code=_PARTITION_EOF,val=-191,str="Broker: No more messages"} at topic - consume-count, partition - 0, offset - 3862
```

**Comment by edenhill** [comment]
When consuming messages in Python make sure that you check the returned message for None equality, and not true/false.

I.e.:
```
   msg = c.poll()
   if msg is None:
       continue
    elif msg.error() is not None:
        # handle error..
    else
        handle(msg.value())
```
