### ISSUE TITLE
ERROR - % Produce failed: Local: Queue full 

### ISSUE THREAD

**Issue by pdhanya** [edenhill/librdkafka#1840]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
When I am sending messages as producer after sometime I am getting the following error

ERROR - % Produce failed: Local: Queue full

I am sending 40000 messages/sec & each message is 313 bytes. The topic has 3 partitions

Code Snippet:
=============
Code snippet:
```
int KafkaQueue::initPerfLogProducer()
{
        int32_t partition = RdKafka::Topic::PARTITION_UA;

        RdKafka::Conf *perflog_conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
        RdKafka::Conf *perflog_tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);
        boost::property_tree::ptree pt;
        boost::property_tree::read_ini("./config/config.ini",pt);
        std::string brokers= pt.get<std::string>("bootstrapserver");
        std::string produce_buffer = pt.get<std::string>("ProduceBuffering");
        std::string produce_batch = pt.get<std::string>("ProduceBatch");
        std::string produce_threshold = pt.get<std::string>("ProduceThreshold");
        std::string produce_lingerms = pt.get<std::string>("ProduceLingerValue");
        std::string produce_bufmax = pt.get<std::string>("ProducebufMax");

        perflog_conf->set("event_cb", &perflog_kafka_event_cb, errstr);
        perflog_conf->set("dr_cb",&perflog_kafkadel_cb, errstr);
        /* TBD - should be from KafkaConfig. */
        perflog_conf->set("metadata.broker.list", brokers, errstr);
        perflog_conf->set("linger.ms", produce_lingerms,errstr);
        perflog_conf->set("queue.buffering.max.messages", produce_bufmax, errstr);
        perflog_conf->set("queue.buffering.max.ms", produce_buffer, errstr);
        perflog_conf->set("batch.num.messages", produce_batch, errstr);
        perflog_conf->set("queue.buffering.backpressure.threshold", produce_threshold, errstr);
        //conf->set("debug","broker,topic,producer,all",errstr);
        LOG_INFO << "Produce Threshold is: " << produce_threshold;


        perflog_producer_ = RdKafka::Producer::create(perflog_conf, errstr);
        if (!perflog_producer_)
        {
                LOG_ERROR << "Failed to create producer: " << errstr;
                return 1;
        }
        LOG_INFO << "% Created producer " << perflog_producer_->name();

        topicPerfLog_ = RdKafka::Topic::create(perflog_producer_, "GS_PERF_LOG_MSG", perflog_tconf, errstr);
        if (!topicPerfLog_)
        {
                LOG_ERROR << "Failed to create topic Logging Message: " << errstr;
                return 1;
        }
}



int KafkaQueue::produceOnGSPerfLogData(const char* buf, int len)
{
        int32_t partition = RdKafka::Topic::PARTITION_UA;
        int64_t start_offset = RdKafka::Topic::OFFSET_BEGINNING;

        RdKafka::ErrorCode resp = perflog_producer_->produce(topicPerfLog_, partition,
                        RdKafka::Producer::RK_MSG_COPY ,
                        const_cast<char *>((char*) buf), len,
                        NULL, NULL);

        if (resp != RdKafka::ERR_NO_ERROR)
                LOG_ERROR << "% Produce failed: " << RdKafka::err2str(resp);
        else
///             LOG_INFO << " successfully sent :" ;
        return 1;
}
```

Apache Kafka version : kafka_2.11-1.0.1
librdkafka version:  Taken from the trunk in January
Operating System : Debian GNU/Linux 8

Configuration:
===============

queue.buffering.max.messages=0
batch.num.messages=10000
queue.buffering.backpressure.threshold=2
linger.ms=100
queue.buffering.max.messages=2000000
queue.buffering.max.ms=0

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You need to call poll() at regular intervals to serve delivery reports of failed or succeeded messages.
