### ISSUE TITLE
Does consumer consume partitions equally?

### ISSUE THREAD

**Issue by mmustala** [edenhill/librdkafka#1841]
If a consumer has two partitions to consume and first partition has 1 message and the second one has 1000 messages, are the partitions supposed to be consumed equally? With equal I mean that it consumes one message from each partition in turns.

What I'm seeing with my consumers is that even though both partitions have many messages, occasionally the consumer is consuming messages only from one partition. Then after a while it may swap to the second partition, or start consuming both of the partitions more or less equally.

Does it matter when the messages are produced into the partition? Is it automatically trying to keep the lag as low as possible?

I would need my partitions to be consumed equally.

**Comment by mmustala** [comment]
I tried to dig this from the source but cannot understand how it works. Anybody know how the consumed partition is selected? Is it done by the consumer or Kafka server?

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#how-are-partitions-fetched

**Comment by edenhill** [comment]
Yup, sounds reasonable

**Comment by edenhill** [comment]
You can use `debug=fetch` to see what partitions are being fetched when, or why not.
As for the queue limiting properties, these actually apply to the final message queue; when using the new consumer (assign() or subscribe()) messages from all partitions are forwarded to the same queue (which you serve thru rd_kafka_consumer_poll()).
This means that `queued.min.messages` and `queued.max.message.kbytes` applies globally, not per partition.

**Comment by mmustala** [comment]
Ok. In https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md it says for `queued.max.messages.kbytes` that "Maximum number of kilobytes per topic+partition in the local consumer queue.". This topic+partition made me to think it is per partition.

So, if high level consumer always fetches for all of its assigned partitions and the partitions are in round robin order in the fetch request, doesn't it mean that broker always tries to fill the fetch request from the same partition first?

**Comment by chengcheng-pei** [comment]
> The round-robiner should fetch partitions as follows:
> 
> 1. partition order 1,2,3,4
> 2. partition order 2,3,4,1
> 3. partition order 3,4,1,2
> 4. partition order 4,1,2,3
> 5. partition order 1,2,3,4
> 
> Code:
> https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L3345

if topic A (partition 0, partition 1) and topic B (partition 0, partition 1, partition 2) assigned to consumer, it will fetch from A0, A1, B0, B1, B2 in roundrobin way?

**Comment by edenhill** [comment]
Yes
https://github.com/edenhill/librdkafka/wiki/FAQ#how-are-partitions-fetched
