### ISSUE TITLE
How to make the same consumer group id subscribe in different topics starting from different offsets.

### ISSUE THREAD

**Issue by FranciscoGualdi** [edenhill/librdkafka#1842]
Description
===========
Hello. I need re-use a group-id and reset the off-set of the topic. I tried to use assign for this topic, setting offset to -2 but all topics in this same group-id have theirs offset reset too.

I tried use rd_kafka_topic_partition_list_set_offset but without sucess.

Is it possible to change an offset of a specific topic in a dynamic rd_kafka_topic_partition_list_t?

1. using only subscribe (not work)
`    

    rd_kafka_topic_partition_list_t *topics_; // is a global var

    int32_t partition = 0; // in this case we only have one partition

    rd_kafka_topic_partition_list_add( topics_, "newTOPIC", partition );

    if (fromFirstOffset)  // if is need start reading from the first offset
    {
        if (rd_kafka_resp_err_t err = rd_kafka_topic_partition_list_set_offset (topics_, topicName.c_str(), partition, 0)) // this reset not work
        {
            return false;
        }
    }
    if (rd_kafka_resp_err_t err = rd_kafka_subscribe(rk_, topics_))
    {
        return false;
    }
`

2. using subscribe (for the smallest offset) and assign (when a need reset the offset) (in the assign case all topics in this group-id have their offset reset) 

`
    
   rd_kafka_topic_partition_list_t *topics_; // is a global var

    int32_t partition = 0; // in this case we only have one partition

    rd_kafka_topic_partition_list_add( topics_, "newTOPIC", partition );

    if (fromFirstOffset)
    {
        newpartition->offset = -2; // ( -2 for beginning and -1 for end)
        // we are using assign because that override the committed offset of the consumer id group
        if (rd_kafka_resp_err_t err = rd_kafka_assign(rk_, topics_)) // all topics in this group-id have their offset reset
        {
            return false;
        }
    }
    else
    {
        if (rd_kafka_resp_err_t err = rd_kafka_subscribe(rk_, topics_))
        {
            return false;
        }
    }`

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v0.11.3>`
 - [ ] Apache Kafka version: `<kafka_2.12-1.0.0>`
 - [ ] librdkafka client configuration: `<v0.11.3>`
 - [ ] Operating system: `<Linux Red Hat>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
subscribe() only looks at the topic name, partitions and offsets will be ignored, and you shall not pass a list with duplicate topic names in it.
If you want to set the starting offset while using subscribe() you can register a rebalance_cb, which will be called when the consumer gets a new assignment, and update that assignment's partition list with new starting offsets and then calling assign(), pretty much what you do today in your assign() example.

**Comment by FranciscoGualdi** [comment]
In fact, I only have one partition, so I believe I don't need the rebalance behavior.
Is there a way to use assign instead of subscriber, and set an offset for a specific topic on the rd_kafka_topic_partition_list_t?

**Comment by edenhill** [comment]
subscribe() is used to create/join a consumer group consisting of multiple consumers which will get assigned a subset of the partitions for the topics being subscribed.
If you only have one consumer you don't need to use subscribe() but can use assign() directly.

Your assign example should be fine (but use RD_KAFKA_OFFSET_BEGINNING instead of -2).

**Comment by FranciscoGualdi** [comment]
Hey Edenhill. I have one consumer group and several topics, in runtime I want add a new topic to rrd_kafka_topic_partition_list_t and set the offset of this topic to the beginning. 
I tested using assign but when I add a new topic in the list and set the offset = RD_KAFKA_OFFSET_BEGINNING all the topics on the list have the offset reset too. What I'm expecting is only that topic added had the offset reset. I will activate some log to get more info.

**Comment by edenhill** [comment]
This is behaving according to design, assign() will replace the current assignment.
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2906

**Comment by FranciscoGualdi** [comment]
Hello Edenhill.

Thanks for your return. Indeed your suggestion works. We can reset the offset of that specific topic without resetting the others topics in the same group id.

Now, I'm struggling with the commit of the offset I just reset.
With my configs (auto.commit = true and auto.store = true) if I try reset two topics in sequence, this means, call your sample code twice (one for each topic). I'm losing the first reset. As I understand, this happens because I'm resetting the store offset and not commit that to the broker, when I reset the second topic I'm losing the reset of the previous. I tried changing my config's to manual store and manual commit. but I not succeeded.  Do you have any tip for this?

**Comment by edenhill** [comment]
Note that assign() is atomic, not incremental. It will replace the current assignment,
so make sure that you include the proper offset of both your partitions.
In the case where you are adding a new partition to the assignment you can use position() to get the current application position of the existing partition, something like:
```
   current = position();
   ..topic_partition_list_add(current, newtopic, newpart)->offset = new_part_start_offset;
    assign(current);
```

**Comment by cumafo** [comment]
Hej Magnus.
Is it possible to use RD_KAFKA_OFFSET_STORED in the rebalance_cb - assign scenario above?
/C

**Comment by edenhill** [comment]
Yes, that's the same as RD_KAFKA_OFFSET_INVALID in the case of assign(), which is also the default behaviour:
attempt to fetch committed offsets,
else fall back to auto.offset.reset
