### ISSUE TITLE
How to build librdkafka use vs2015 without openssl

### ISSUE THREAD

**Issue by prehistoric-penguin** [edenhill/librdkafka#1843]
Description
===========
I was using librdkafka 0.9.2 before, it's OK to build without openssl. Now I am trying to upgrade to 0.11.4, but get compiling error.  Even with the `#define WITH_SSL 0` config in file `win32_config.h`.

Then I get the error message:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error (active)		#error directive: "WITH_SSL (OpenSSL) is required for SASL SCRAM"	librdkafka	z:\librdkafka-0.11.4\src\rdkafka_sasl_scram.c	46	

How to reproduce
================
* Edit win32_config.h, change the line to `#define WITH_SSL 0` 
* Build project librdkafka with config: X64 - Debug

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v-0.11.4`
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration: 
 - [x] Operating system: `Windows server 2008 R2`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You'll probably want to remove openssl from librdkafka.sln / librdkafka.vcxproj, etc

**Comment by prehistoric-penguin** [comment]
I tried to make the fix, please review
https://github.com/edenhill/librdkafka/pull/1844

**Comment by kuskmen** [comment]
What about Visual Studio 2017 guys? I am interested in looking some code because I want to join .NET client, but first I guess I need to familiarize with the client .NET client is wrapper around.

**Comment by prehistoric-penguin** [comment]
@kuskmen Sorry, I only have experience with VS2015.

**Comment by edenhill** [comment]
You should be able to use the librdkafka.redist package that comes prebuilt and includes openssl.

**Comment by tgredfish** [comment]
I am trying to use VS2017 to build a program that includes the Kafka libraries and the ProtocolBuffer libraries.  The goal is to build ProtocolBuffer objects and add them to a Kafka topic that will be consumed by a host process.  The recommendation by the google website is to compile & link ProtocolBuffer as a static library.  I have done that and I was able to link that into my program.  When I try to compile and link the Kafka library as a static library, I get many link errors when I include the OpenSSL libraries I downloaded (the static builds).

When I installed the librdkafka.redist package you referenced above without the protocol buffer libraries, I was able to get the kafka calls to work properly.  But, when I included the Protocol Buffer libraries, I get many link error with that library.

I tried the target solution to both v140 and v141 with basically the same problems.  Do you have any recommendations on how to get both of these packages to compile and link into the same program?  Thanks ahead of time for your response.
