### ISSUE TITLE
Error len is 0 when rd_kafka_message_t contains an error

### ISSUE THREAD

**Issue by accelerated** [edenhill/librdkafka#1851]
librdkafka version: commit 57c000a293abada459115aa7f6052ef6d9253eff from 18/06/2018

Based on the documentation of `rd_kafka_message_t` structure: 
```
	void   *payload;           /**< Producer: original message payload.
				    * Consumer: Depends on the value of \c err :
				    * - \c err==0: Message payload.
				    * - \c err!=0: Error string */
	size_t  len;               /**< Depends on the value of \c err :
				    * - \c err==0: Message payload length
				    * - \c err!=0: Error string length */
```
When receiving an EOF message, the error and payload are properly set to `RD_KAFKA_RESP_ERR__PARTITION_EOF` and `"Broker: No more messages"` repectively but `len` field is 0, which is incorrect. Note that other error messages may have this issue as well.

**Comment by edenhill** [comment]
Fixed on master, thanks!
