### ISSUE TITLE
kafka client crash in rd_kafka_q_pop_serve

### ISSUE THREAD

**Issue by aelanthi** [edenhill/librdkafka#1853]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
kafka client crashes in rd_kafka_q_pop_serve

How to reproduce
================

1. Not able to predict/ consistenly reproduce the crash. I have seen this multiple times now. Doesn't seem to be related to number of messages sent/received on kafka.
2. Default configuration plus additional settings as mentioned under checklist.
3. Single kafka consumer and multiple producers run on different linux pthreads
4. Messages are produced using rd_kafka_producev() for topics created at runtime  and rd_kafka_produce() for topics known beforehand
5. Messages are consumed using rd_kafka_consumer_poll()

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.4`
 - [x ] Apache Kafka version: `0.10.1.0`
 - [x ] librdkafka client configuration: `metadata.broker.list='broker_address',,group.id='gid',offset.store.method='broker'`
 - [x] Operating system: `Ubuntu 14.04.3 LTS`
 - [x
[librdkafka_stack_trace.txt](https://github.com/edenhill/librdkafka/files/2117089/librdkafka_stack_trace.txt)
] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
in gdb, can you do?:
`fr 2`
followed by
`p *rkq`

and provide the output here? thanks

**Comment by aelanthi** [comment]
I ran into a different stack(protocol parse failure) trace two times. I tried to get more information when it happened again and have the gdb session alive. Let me know if you want more data from the session.

[kafka_crash2_again_more_info.txt](https://github.com/edenhill/librdkafka/files/2121255/kafka_crash2_again_more_info.txt)
[kafka-crash2.txt](https://github.com/edenhill/librdkafka/files/2121256/kafka-crash2.txt)

**Comment by aelanthi** [comment]
I got more information on the original crash today, please see attached 
[librdkafka_stack_trace_2.txt](https://github.com/edenhill/librdkafka/files/2143200/librdkafka_stack_trace_2.txt)

**Comment by edenhill** [comment]
Thanks for the backtraces!
The queue looks fine in stack_trace_2, with refcnt of 3, but still it crashes.
Would it be possible for you to reproduce this while running valgrind or having compiled librdkafka with `-fsanitize=address`  (see dev-conf.sh)
