### ISSUE TITLE
how to use librdkafka to monitor the length of topic queue?

### ISSUE THREAD

**Issue by dodomouse** [edenhill/librdkafka#1856]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hello, I want to use librdkafka to get the length of one topic queue for one group, like using kafka-consumer-groups.sh --describe to get CURRENT-OFFSET/LOG-END-OFFSET/LAG. I don't how to implement it, could you show me some samples or tell me how to do?

Thanks a lot.

**Comment by edenhill** [comment]
If you want to do this for just one group you could do something like this:
 * Create a new consumer with group.id set to the group you want to monitor

Every 10s or whatever rate you want to monitor the consumer lag, do:
 * Call query_watermark_offsets() to get the low and high offsets of the given partitions
 * Call committed(wmark_partitions) to retrieve the last committed offset position for the group.
 * Calculate the difference between the committed offsets to the high watermark.
