### ISSUE TITLE
Consumers receive _ALL_BROKERS_DOWN error at an alarming rate

### ISSUE THREAD

**Issue by avoskresensky** [edenhill/librdkafka#1857]
Description
===========
We have a Kubernetes cluster of 6 nodes running a Kafka cluster of 5 nodes.
Zookeeper ensemble has 3 nodes and is run on separate machines.

Among the pods that we run in our Kubernetes cluster, there are around 600 containers that run Kafka consumers.
Each of them -- a single Python process that uses confluent-kafka python wrapper to consume one or more topics (usually one).

According to the logs we get around 100-150 occurrences of _ALL_BROKERS_DOWN error each hour across the entire cluster,
which suggests that each of those 600 consumers get that error at least once in 4 hours.

We've noticed in the past that this error makes some of our consumers get frozen, so we're catching it in error_cb and fail fast as soon as we see it.
Kubernetes makes sure our consumers are automatically restarted, but at least one restart every 4 hours sounds a bit much and we'd like to figure out what can be done to remedy the problem.

librdkafka version: v0.11.4
Apache Kafka version: 1.1.0

There are 522 Kafka topics with 20 partitions and the replication factor of 1.

Consumer settings:
    'enable.auto.commit': ..., (we have both ways in our scripts -- both fail the same)
    'group.id': ...,
    'default.topic.config': {
        'auto.offset.reset': 'smallest'
    },
    'session.timeout.ms': 30000,  # this was added recently -- no visible change
    'socket.timeout.ms': 60000,   # this was added recently -- no visible change

Kafka settings (other than defaults):
    'KAFKA_NUM_PARTITIONS': '20',
    'KAFKA_DEFAULT_REPLICATION_FACTOR': '1',
    'KAFKA_LOG_RETENTION_HOURS': str(RETENTION_HOURS),
    'KAFKA_LOG_ROLL_HOURS': str(RETENTION_HOURS),
    'KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS': '300000',
    'KAFKA_OFFSETS_RETENTION_MINUTES': str(6 * 60),
    'KAFKA_OFFSETS_RETENTION_CHECK_INTERVAL_MS': '300000',
    'KAFKA_LOG_CLEANUP_POLICY': 'delete',
    'KAFKA_LOG_CLEANER_ENABLE': 'true',
    'KAFKA_DELETE_TOPIC_ENABLE': 'true'

There is nothing incriminating in the broker logs.
The consumer log taken with "debug": "protocol,broker" is attached.
It tool that particular process less than a minute to go belly up.

**Comment by avoskresensky** [comment]
Consumer logs:
https://www.dropbox.com/s/dvo7pw60q00w2zp/broker-down-logs.txt?dl=0

**Comment by edenhill** [comment]
This looks like a problem with the network, all 5 brokers disconnect pretty much at the same time, which triggers the ALL_BROKERS_DOWN event:

```
%7|1529635225.517|STATE|rdkafka#consumer-1| [thrd:35.227.39.21:30014/5]: 35.227.39.21:30014/5: Broker changed state UP -> DOWN
%7|1529635225.517|STATE|rdkafka#consumer-1| [thrd:35.227.39.21:30010/bootstrap]: 35.227.39.21:30010/1: Broker changed state UP -> DOWN
%7|1529635225.518|STATE|rdkafka#consumer-1| [thrd:35.227.39.21:30012/3]: 35.227.39.21:30012/3: Broker changed state UP -> DOWN
%7|1529635225.518|STATE|rdkafka#consumer-1| [thrd:35.227.39.21:30013/4]: 35.227.39.21:30013/4: Broker changed state UP -> DOWN
%7|1529635225.522|STATE|rdkafka#consumer-1| [thrd:35.227.39.21:30011/bootstrap]: 35.227.39.21:30011/2: Broker changed state UP -> DOWN
```

**Comment by avoskresensky** [comment]
Should I be seeing something regarding this in the broker logs? Or is this happening on the client side?

**Comment by edenhill** [comment]
I don't believe it is client side, but rather broker or network. I'd check the broker logs.

**Comment by edenhill** [comment]
It could be the broker's idle connection reaper kicking in;
https://github.com/edenhill/librdkafka/wiki/FAQ#why-am-i-seeing-receive-failed-disconnected

You can set `log.connection.close=false` to silence these logs. there are also some improvements in the upcoming v0.11.5 release where it will automatically silence idle disconnects regardless of `log.connection.close`.
