### ISSUE TITLE
Callback-based IO event notifier

### ISSUE THREAD

**Issue by fede1024** [edenhill/librdkafka#1859]
I'm working on improving the way librdkafka interacts with the rust futures for [rust-rdkafka](https://github.com/fede1024/rust-rdkafka). The main challenge is to notify the event loop whenever there are new events to be processed. I believe issue #749 asked for basically the same feature, but the solution provided there uses file-descriptor, while in the rust case (and I suppose in other cases as well) it would be more efficient to just have a callback that is triggered whenever a queue goes from 0 to a non-0 number of events.

I made a small change to the library [here](https://github.com/fede1024/librdkafka/commit/87898c5ca8137c370809ecb26f0e12507eb47946) and I've successfully tested this approach from the rust library, but before opening a PR (with proper tests and documentation), I'd like to know if there is any downside to this approach, if there is any reason why this woud be a bad idea, etc.

Thanks! :)

**Comment by edenhill** [comment]
Thanks for the background, the use-case makes sense and should be catered for by librdkafka.

Your change looks good, go ahead with creating a PR, I left some comments on your initial commits.
