### ISSUE TITLE
Question on rd_kafka_q_serve_rkmessages

### ISSUE THREAD

**Issue by elbaro** [edenhill/librdkafka#1863]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

`rd_kafka_q_serve_rkmessages` has a parameter `timeout_ms`.
Is `timeout_ms` applied for batch or for a single message?

From the code, it looks like the timeout is applied for each message:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_queue.c#L537-L551

If then, the request for batch_size=100, timeout_ms=1000 may timeout after 100*1000ms = 100 seconds.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): bd74dc31ba6edf431749b4ad5a00aa4fc78882fc

**Comment by rnpridgeon** [comment]
relates to https://github.com/confluentinc/confluent-kafka-python/issues/407

**Comment by edenhill** [comment]
You are correct, this seems to be a bug. It should use the remaining timeout.

**Comment by manugarri** [comment]
hey @edenhill , is there any update on when we could expect a bugfix? If not we can really use batch consume reliably, right?

**Comment by edenhill** [comment]
The fix PR will soon be submitted.
We've also got a couple of other fixes that warrants a maintenance release, so we'll probably create an RC next week.

**Comment by manugarri** [comment]
Awesome, thanks so much @edenhill ! We really want to use librdkafka since well. is the fastest library (and the one with the "official" confluent support). Very much looking forward to it Sir.
