### ISSUE TITLE
Frequent request time outs and partition reassignments

### ISSUE THREAD

**Issue by tkrajca** [edenhill/librdkafka#1865]
Description
===========
Hi, I have been trying to work out this issue for quite a while but arrived at a dead end. I am not sure if it's a librdkafka issue or some sort of issue with my configuration.

I've got 3 kafka brokers, 3 confluent kafka python producers and 2 confluent kafka python consumers (each consumer receives about 100000 messages every 8 minutes). The 2 consumers emit the following error message a few times every hour (not at the same time, I couldn't see any patterns there):

`2018-06-28 00:14:48,016 ERROR testme2 __main__ PID: 9559  FAIL [aauvmadmsa001.example.com61#consumer-1] [thrd:auhwbeshd011.example.com:6667/1006]: auhwbeshd011.example.com:6667/1006: 1 request(s) timed out: disconnect`
`2018-06-28 00:14:48,017 ERROR testme2 __main__ PID: 9559  ERROR [aauvmadmsa001.example.com61#consumer-1] [thrd:auhwbeshd011.example.com:6667/1006]: auhwbeshd011.example.com:6667/1006: 1 request(s) timed out: disconnect
`
Now this wouldn't worry me too much except it sometimes seems to correlate to a group partition assignment re-balance. So consumer A gets this error, consumer B thinks consumer A left the group so reassigns all partitions from A to itself, then a few minutes later consumer A appears again and they reassign partitions again. I could live with the timeouts but I can't have the consumers taking over each other's partitions a few times every hour.

I ran tcpdump to troubleshoot the time outs and verified that after a consumer have successfully been talking to a broker for quite a while, it sends a request and doesn't receive any response for 60s (I verified that the broker receives the request but sends no response back for those 60s). The consumer tears down the connection after those 60s.

I am not entirely sure if the time outs have anything to do with the reassignment but I suspect they might.

The CPU load per core on any of the 3 brokers averages around 0.15, never rising over 0.4. A regular GC on kafka brokers takes a few 100ms with full GCs taking a few seconds at most.

Any pointers would be greatly appreciated.

This is a simple python consumer that I run two instances of (the 2 log files are at https://github.com/RepositPower/dump):

```python
import logging
import random
import socket

from confluent_kafka import Consumer

kafka_logger = logging.getLogger(__name__)
logger = logging.getLogger(__name__)

logging.basicConfig(level=logging.DEBUG, format="%(asctime)s %(levelname)s %(module)s %(name)s PID: %(process)d  %(message)s")

consumer_config = {
    "bootstrap.servers": "kafka.example.com:6668",
    "group.id": "tomas123",
    "client.id": socket.gethostname() + str(random.randint(0, 256)),
    'log.connection.close': False,
    "enable.partition.eof": False,
    "partition.assignment.strategy": "range", "api.version.request": False,
    "broker.version.fallback": "0.9.0.2.3",
    "debug": "consumer,cgrp,topic,fetch,protocol"
}

consumer = Consumer(consumer_config, logger=kafka_logger)    # , on_commit=on_commit)
topics = [
    "tsdb.operational.australia.nem.ec.meter.real_power", 
]

def on_assign(_, partitions):
    """on_assign"""
    logger.warn("Re-Assignment: {0}".format(partitions))

consumer.subscribe(topics, on_assign=on_assign)

logger.debug("running")
i = 0
while True:
    msg = consumer.poll()
    if msg is not None:
        if not msg.error():
            i += 1
        else:
            logger.error("Error for {0}: {1}".format(
                (msg.topic(), msg.key()), msg.error())
            )    
    if i % 100000 == 0:
        logger.debug(i)
```

confluent-kafka-python version: confluent-kafka==0.11.5rc4

Checklist
=========

 - [x] librdkafka version (release number or git tag):
```
>>> confluent_kafka.libversion()
('0.11.5-PRE5-7-g57c000', 722176)
```
 - [x] Apache Kafka version: `0.9.0.2.3`
 - [x] librdkafka client configuration:    
  ` "bootstrap.servers": "kafka.example.com:6668",
    "group.id": "tomas123",
    "client.id": socket.gethostname() + str(random.randint(0, 256)),
    'log.connection.close': False,
    "enable.partition.eof": False,
    "partition.assignment.strategy": "range", "api.version.request": False,
    "broker.version.fallback": "0.9.0.2.3",
    "debug": "consumer,cgrp,topic,fetch,protocol"`

 - [x] Operating system: `CentOS 7 (x64)`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
> I ran tcpdump to troubleshoot the time outs and verified that after a consumer have successfully been talking to a broker for quite a while, it sends a request and doesn't receive any response for 60s (I verified that the broker receives the request but sends no response back for those 60s). The consumer tears down the connection after those 60s.

That is odd indeed. Do you have throttling enabled on the broker? (Since you're running a development version of the clients you can add a throttle_cb to your python clients to see if they begin getting throttled - it will not report throttling for the request that fails though).

Looking at the logs the last FetchResponse from broker 1004 is received with minimal latency at 00:43:00, then there is nothing for 30s until the HeartbeatRequest times out and closes the connection.
When the connection comes up again it happily sends and receives requests with normal latency.

**Comment by tkrajca** [comment]
Thanks @edenhill , yep, it is really odd, the responses seem to arrive in around 100ms or under until there suddenly is no response. It looks like the broker actually doesn't send any response but I have no idea why. I couldn't find anything in the broker logs that could explain it.

I don't know if I've got throttling enabled on the broker, I use pretty much the default config from (Hortonworks) ambari.

```
[root@auhwbeshd010 0]# cat server.properties
# Generated by Apache Ambari. Thu Jun 21 02:14:51 2018

auto.create.topics.enable=true
auto.leader.rebalance.enable=true
compression.type=producer
controlled.shutdown.enable=true
controlled.shutdown.max.retries=3
controlled.shutdown.retry.backoff.ms=5000
controller.message.queue.size=10
controller.socket.timeout.ms=30000
default.replication.factor=2
delete.topic.enable=false
external.kafka.metrics.exclude.prefix=kafka.network.RequestMetrics,kafka.server.DelayedOperationPurgatory,kafka.server.BrokerTopicMetrics.BytesRejectedPerSec
external.kafka.metrics.include.prefix=kafka.network.RequestMetrics.ResponseQueueTimeMs.request.OffsetCommit.98percentile,kafka.network.RequestMetrics.ResponseQueueTimeMs.reques
t.Offsets.95percentile,kafka.network.RequestMetrics.ResponseSendTimeMs.request.Fetch.95percentile,kafka.network.RequestMetrics.RequestsPerSec.request
fetch.purgatory.purge.interval.requests=10000
group.max.session.timeout.ms=60000
kafka.ganglia.metrics.group=kafka
kafka.ganglia.metrics.host=localhost
kafka.ganglia.metrics.port=8671
kafka.ganglia.metrics.reporter.enabled=true
kafka.metrics.reporters=org.apache.hadoop.metrics2.sink.kafka.KafkaTimelineMetricsReporter
kafka.timeline.metrics.host=aauvmadmwo001.repositpower.net
kafka.timeline.metrics.maxRowCacheSize=10000
kafka.timeline.metrics.port=6188
kafka.timeline.metrics.protocol=http
kafka.timeline.metrics.reporter.enabled=true
kafka.timeline.metrics.reporter.sendInterval=5900
kafka.timeline.metrics.truststore.password=xxxx
kafka.timeline.metrics.truststore.path=/etc/security/clientKeys/all.jks
kafka.timeline.metrics.truststore.type=jks
leader.imbalance.check.interval.seconds=300
leader.imbalance.per.broker.percentage=10
listeners=PLAINTEXT://auhwbeshd010.repositpower.net:6667
log.cleanup.interval.mins=10
log.dirs=/grid/1/kafka-logs
log.index.interval.bytes=4096
log.index.size.max.bytes=10485760
log.retention.bytes=-1 
log.retention.hours=72 
log.roll.hours=24
log.segment.bytes=1073741824
message.max.bytes=1000000
min.insync.replicas=1  
num.io.threads=8
num.network.threads=3  
num.partitions=20
num.recovery.threads.per.data.dir=1
num.replica.fetchers=1 
offset.metadata.max.bytes=4096
offsets.commit.required.acks=-1
offsets.commit.timeout.ms=5000
offsets.load.buffer.size=5242880
offsets.retention.check.interval.ms=600000
offsets.retention.minutes=86400000
offsets.topic.compression.codec=0
offsets.topic.num.partitions=50
offsets.topic.replication.factor=2
offsets.topic.segment.bytes=104857600
port=6667
producer.purgatory.purge.interval.requests=10000
queued.max.requests=500
replica.fetch.max.bytes=1048576
replica.fetch.min.bytes=1
replica.fetch.wait.max.ms=500
replica.high.watermark.checkpoint.interval.ms=5000
replica.lag.max.messages=4000
replica.lag.time.max.ms=10000
replica.socket.receive.buffer.bytes=65536
replica.socket.timeout.ms=30000
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
socket.send.buffer.bytes=102400
zookeeper.connect=auhwbeshd007.repositpower.net:2181,auhwbeshd006.repositpower.net:2181,auvmbes001.repositpower.net:2181,auvmbes004.repositpower.net:2181,auhwbeshd005.repositpower.net:2181
zookeeper.connection.timeout.ms=25000
zookeeper.session.timeout.ms=30000
zookeeper.sync.time.ms=2000
```
I added the throttle_cb into the consumer config but haven't seen any throttle events so far.

```python
def throttle_cb(throttle_event):
    logger.warn("Throttle: {0}".format(throttle_event))

consumer_config = {
...
    "throttle_cb": throttle_cb
}
...
```

**Comment by tkrajca** [comment]
Hmm, I upgraded kafka brokers to 0.10.0, looks like that might have fixed it :)
