### ISSUE TITLE
Potential null reference in rd_kafka_metadata_refresh_topics and rd_kafka_metadata_refresh_all?

### ISSUE THREAD

**Issue by ankon** [edenhill/librdkafka#1866]
Found while reading through the code, looking for something else: In both `rd_kafka_metadata_refresh_topics` and `rd_kafka_metadata_refresh_all` the code can dereference `rkb` when `rk` is null, but then has another check _afterwards_ that seems to imply that `rkb` could also be null.

https://github.com/edenhill/librdkafka/blob/bd74dc31ba6edf431749b4ad5a00aa4fc78882fc/src/rdkafka_metadata.c#L774-L779
https://github.com/edenhill/librdkafka/blob/bd74dc31ba6edf431749b4ad5a00aa4fc78882fc/src/rdkafka_metadata.c#L908-L911

I've tried to find callers for `rd_kafka_metadata_refresh_all`, and it seems that it is never called with a null `rk`, but I do not know the code well enough to see whether this actually the case, or whether this is a null reference in certain cases.

**Comment by edenhill** [comment]
The idea is that these two functions may be called with valid rk and rkb, or one of rk and rkb, but never neither rk or rkb.
In practice it only seems to be called with just rk though.

**Comment by edenhill** [comment]
Thanks for the code review!
