### ISSUE TITLE
how can I link the statically compiled code to the nginx

### ISSUE THREAD

**Issue by Jianye** [edenhill/librdkafka#1868]
Description
===========
[work@xx.xxx.xx sbin]$ ./nginx -V
./nginx: error while loading shared libraries: librdkafka.so.1: cannot open shared object file: No such file or directory

How to reproduce
================
Install librdkafka
./configure  --prefix=../bulid --enable-static && make && make install

install nginx
 ./configure  --prefix=../bulid/ --add-module=../ngx_kafka_module-master --with-cc-opt="-I ../bulid/include" --with-ld-opt="-L ../bulid/lib"&& make && make install

setup nginx
add "LD_LIBRARY_PATH=$path/lib" to start script

but, how can I link the statically compiled code to the nginx?

**Comment by edenhill** [comment]
use `pkg-config --libs rdkafka-static`
