### ISSUE TITLE
C++ interface does not implement getting the 'key' of a message

### ISSUE THREAD

**Issue by kodekarl** [edenhill/librdkafka#187]
Line 122 in src-cpp/rdkafkacpp_int.h:
```
 const std::string *key () const { return NULL; /* FIXME */ }
```
So when consuming via the C++ interface, we are not able to get the key of the message.
I'll propose a fix via a pull request in a short while.

**Comment by edenhill** [comment]
Thanks!

**Comment by edenhill** [comment]
Thanks for the fix, much appreciated!
