### ISSUE TITLE
Change kafka broker ip in rdkafka 

### ISSUE THREAD

**Issue by matesio** [edenhill/librdkafka#1875]
Hi, 
i am using librdkafka on centos 7, to puch bro logs to kafka topic, but when i execute bro script it gives me error.
```
%3|1531144133.473|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused
%3|1531144133.473|ERROR|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused

```
As i am on hortonworks and kafka uses 6667 port, so i need to change both port and remote ip,

Please do let me know how  i can change ip address and port in rdkafka.

**Comment by rolandyoung** [comment]
Check the documentation for the bro script you are using. It must have away to set up configuration parameters for the Kafka producer that it runs.

It might accept command line parameters, parse environment variables or read a configuration file. The parameter you want to set is `metadata.broker.list`, or its alias `bootstrap.servers`.

However, this a question for the Bro project, not this one.

**Comment by matesio** [comment]
i have set up metadata.broker.list to my kafka address, but it always picks localhost:9092 (librdkafka-1) .

**Comment by matesio** [comment]
Redefining rdkakfa info in bro script worked for me. Thank you.
