### ISSUE TITLE
Increased number of timeouts when message.timeout.ms = 0

### ISSUE THREAD

**Issue by coldeasy** [edenhill/librdkafka#1876]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
When I set `message.timeout.ms` to `0` (infinite) I notice frequent producer timeouts with logs like
```
2018-07-10 13:12:56,475 REQTMOUT [cl1@1/cl1#producer-1] [thrd:<ip>:9092/102]: <ip>:9092/102: Timed out 4+0+0 requests
2018-07-10 13:12:56,475 BROKERFAIL [cl1@1/cl1#producer-1] [thrd:<ip>:9092/102]: <ip>:9092/102: failed: err: Local: Timed out: (errno: Connection timed out)
2018-07-10 13:12:56,475 FAIL [cl1@1/cl1#producer-1] [thrd:<ip>:9092/102]: <ip>:9092/102: 4 request(s) timed out: disconnect (average rtt 36.261ms)
```

By contrast if I set the `message.timeout.ms` to `60000` (the same as a the `socket.timeout.ms`) I don't see any timeouts whatsoever.

How to reproduce
================
Set `message.timeout.ms=0` and run a producer. I can send debug logs for `msg,protocol,broker` if you need it.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.10.4`
 - [x] Apache Kafka version: `0.10.2`
 - [x] librdkafka client configuration: `message.timeout.ms=0, statistics.interval.ms=1000, message.send.max.retries=10, queue.buffering.max.ms=50, queue.buffering.max.messages=10000, queue.buffering.max.kbytes=10240, max.in.flight.requests.per.connection=200, batch.num.messages=1000`
 - [x] Operating system: `Centos 6 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Interesting, will need to reproduce.

**Comment by shirkevich** [comment]
For those facing it, more details it this ticket:
https://github.com/edenhill/librdkafka/issues/2015

**Comment by edenhill** [comment]
Dup of #2015
