### ISSUE TITLE
When restarting a kafka cluster, rd_kafka fails to retrieve timestamps for messages after reconnecting.

### ISSUE THREAD

**Issue by LavaSpider** [edenhill/librdkafka#1877]
Description
===========
While doing tests with restarting a kafka cluster while a rd_kafka consumer was connected we found that the consumer will no longer receive messages with valid timestamps once the connection has been restored.

How to reproduce
================
1. When the kafka cluster goes down, rd_kafka immediately attempts to reconnect.
2. rd_kafka_broker_connect attempts connection with a new non-blocking socket.
3. rd_kafka_transport_poll polls the connection for writeability using WSAPoll and a timeout of 1000ms which returns POLLWRNORM.
a. Mesaured time shows that actual time spent in initial WSAPoll to be 0ms.
4. rd_kafka_transport_get_socket_error checks the connection for errors using GetSocketOpt SO_ERROR, which succeeds with *errp set to 0.
5. rd_kafka thinks the connection succeeded: rd_kafka_transport_connect_done is called from rd_kafka_transport_poll.
6. rkb_features indicates that RD_KAFKA_FEATURE_APIVERSION is available and a version request is issued from within rd_kafka_broker_connect_done.
7. Version request fails because socket is not actually connected.
8. In rd_kafka_broker_fail, RD_KAFKA_FEATURE_APIVERSION failure while in state RD_KAFKA_BROKER_STATE_APIVERSION_QUERY is assumed to indicate that the broker cannot handle version requests.
9. rkb_features is set to no longer handle RD_KAFKA_FEATURE_APIVERSION.
10. start kafka broker and allow rd_kafka consumer to reconnect.
11. Messages fetched from broker no longer contain timestamps because rd_kafka thinks that the broker is a version which does not support them.

Regarding step 3:
https://docs.microsoft.com/en-us/windows/desktop/api/winsock2/nf-winsock2-wsapoll
"Pending connect requests are indicated in the returned revents member of WSAPOLLFD structure by POLLWRNORM."
So POLLWRNORM being returned is expected.

Regarding step 4:
This is the cause of the issue and seems to be timing related. Sometimes error is set to 0 and other times it is the expected WSAECONNREFUSED(10061)
It would be interesting to see what happens when a router which drops icmp messages sits between the rd_kafka client and the broker. I would expect 0 to be set from GetSocketOpt SO_ERROR until the connection attempt times out.

Workaround
=========
Setting broker.version.fallback to a broker version which supports RD_KAFKA_FEATURE_APIVERSION such as 0.10.0 is a work around for this issue.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.4`
 - [x] Apache Kafka version: `1.0.0 via docker image wurstmeister/kafka:1.0.0`
 - [x] librdkafka client configuration: `enable.auto.commit=false, enable.auto.offset.store=false, enable.partition.eof=false, fetch.error.backoff.ms=0, produce.offset.report=true, session.timeout.ms=10000, socket.keepalive.enable=true`
 - [x] Operating system: `Windows 10 Enterprise 64-bit (10.0, Build 16299)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Great report!

librdkafka has some heuristics to detect the broker/protocol version, including workarounds for a bug in Kafka broker 0.9.
When the initial ApiVersionRequest times out the client will revert to its broker.version.fallback setting for api.version.fallback.ms.
However, if you know your broker version is at least 0.10.0.0 you can set `broker.version.fallback=0.10.0.0` (as you've noted!) and `api.version.fallback.ms=0`.

https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility
