### ISSUE TITLE
`app_offset` significantly lower than `committed_offset` and stuck

### ISSUE THREAD

**Issue by shanson7** [edenhill/librdkafka#1878]
Description
===========
Occasionally our consumers seem to get "stuck" and report a consistent lag. The stats look something like:

```
"topic": {
                "metadata_age": 6851,
                "partitions": {
                    "9": {
                        "app_offset": 674919,
                        "commited_offset": 713406,
                        "committed_offset": 713406,
                        "consumer_lag": 38487,
                        "desired": true,
                        "eof_offset": 713406,
                        "fetch_state": "active",
                        "fetchq_cnt": 0,
                        "fetchq_size": 0,
                        "hi_offset": 713406,
                        "leader": 5,
                        "lo_offset": 713406,
                        "msgq_bytes": 0,
                        "msgq_cnt": 0,
                        "msgs": 2,
                        "next_offset": 713406,
                        "partition": 9,
                        "query_offset": 0,
                        "rx_ver_drops": 0,
                        "stored_offset": 674919,
                        "txbytes": 0,
                        "txmsgs": 0,
                        "unknown": false,
                        "xmit_msgq_bytes": 0,
                        "xmit_msgq_cnt": 0
                    }
                },
                "topic": "topic"
            }
```

Producing a single message to the stuck partition seems to kickstart it and everything is fine (but not all toppars get frequent data, so it can report lag for hours).

Unfortunately, I don't know how to reproduce this, although it does seem to coincide with rebalances and I see things like:

`[2018-07-11 17:22:48,586] INFO [GroupCoordinator 6]: Member rdkafka-XXX in group topic_consumer has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)`

In kafka at the same time. 

How to reproduce
================

Unfortunately, I don't know how to reproduce this, although it does seem to coincide with rebalances and I see things like:

`[2018-07-11 17:22:48,586] INFO [GroupCoordinator 6]: Member rdkafka-XXX in group topic_consumer has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)`

in kafka at the same time. 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.4`
 - [x] Apache Kafka version: `1.1.0`
 - [x] librdkafka client configuration: `statistics.interval.ms=10000, log.connection.close=true, compression.codec=snappy`
 - [x] Operating system: `rhel7.3`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by shanson7** [comment]
Some open questions:
1. Why would `app_offset` ever be less than `committed_offset`?
1. When this happens, are messages from `app_offset` - `committed_offset` reprocessed?
1. Is there a way for me to get a callback when partition offsets are initially set? It seems to be asynchronous and I'm not sure how to do this aside from polling for a while (which can get me incorrect offsets as some messages might get processed).

**Comment by shanson7** [comment]
Is there any way to get the info such as:
`severity = 7 fac = FETCHSTART event = [thrd:main]:  metrics [0] offset 37388236`

In a structured callback rather than a log? The issue I'm having is that in my consumers, I'd like to log the assignments (with positions) on startup, shutdown, and post rebalance. That way, I can better track the coming and going of partitions. But mostly, I just want to log the *changes* partitions added, removed and (in the case of a bug) unexpected differences in the offsets.

**Comment by edenhill** [comment]
Hey Sean,

the `app_offset` is only updated when your application consumes a message,
and `consumer_lag` is calculated by `hi_offset - app_offset`.
Is it possible that this particular consumer was assigned this partition a while ago and consumed up to 674919, then the group rebalanced and the partition was reassigned to another consumer which picked up from the committed 674919 offset and processed messages up to 713406, followed by a commit.
The partition was the reassigned back to the first consumer which fetches the committed offset (713406) and also the partition high-watermark offset (the same 713406), thus resulting in no messages actually being fetched and thus no messages being available for the application to consume - leaving the `app_offset` untouched at its pre-historic position.

I'd say this is correct for the `app_offset`, but obviously not for `consumer_lag`.
Maybe the logic should be more like this:
```
   consumer_lag = hi_offset - MAX(app_offset, committed_offset)
```
?


--
As for fetchstart callback: there is no such thing available. You can use position() to get the information though.

**Comment by mhowlett** [comment]
i'd say it's more correct for `app_offset` to be invalidated when the partition moves away from the consumer. and yes, makes sense to me for the `consumer_lag` calculation use `committed_offset` (assuming that is known and valid) in the case `app_offset` is invalid.

**Comment by edenhill** [comment]
So unassign should reset app_offset to INVALID_OFFSET.

**Comment by shanson7** [comment]
I think you are likely right that this is the issue. For now, I can adjust my lag detection logic to handle this properly.

As far as using `positions()`, the issue I was having is that without calling `consume()` the offsets never get assigned. So I have to consume, but they changed the offsets.

**Comment by edenhill** [comment]
Fixed on master.

Re position(); there's been some discussion whether we should provide an API that returns the starting offset of an assignment, using the same logic as what is done internally when assign() is called:
 - look up committed offsets,
 - if that fails, check auto.offset.reset and look up those logical offsets.

**Comment by shanson7** [comment]
Is the intended usage to call `assignments()` then pass the result into `positions()`? 
Are these pointers then supposed to be `free`d / `delete`d?  
Is there a risk that using these API calls can muck with the actual consumer offsets?

**Comment by edenhill** [comment]
Yeah, pass the results of assignment() to position() to get the offset + 1 of the last message consumed by the application, then free the returned vec (from assignment) with TopicPartition::destroy().

> .. risk ..
No, these are read-only operations.
