### ISSUE TITLE
How to use in Windows by using Visual Studio 

### ISSUE THREAD

**Issue by umutozturk95** [edenhill/librdkafka#1879]
Hi,
Do you have a chance to explain step by step how to compile this api in VS for C++?
I got a lot of errors while compling this api and did not find enough resources . Do you have resources to provide?

All the best,

**Comment by edenhill** [comment]
You should typically import and use the librdkafka.redist NuGet package in your application project.

If you want to build librdkafka yourself, simply open up the win32/librdkafka.sln file in Visual Studio and build (you will need to install [Win32 OpenSSL](https://slproweb.com/products/Win32OpenSSL.html) first in C:\
