### ISSUE TITLE
Question on metadata

### ISSUE THREAD

**Issue by lathakris** [edenhill/librdkafka#1880]
Hi,

I had a question on metadata fetch., when the metadata is refreshed periodically, I assume it is available and gets used by the corresponding kafka handle. (the topics fetched in the metadata are available for that kafka instance).

Does the same thing happen when I refresh the metadata using ' rd_kafka_metadata' api ? I assume I will have to destroy the fetched metadata ?  (does the fetched metadata get associated with the kafka handle so that the new topics discovered in the metadata are available to the producer ?) Mainly used for topics created dynamically.

Thanks.

Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Question on metadata

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.4`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There is an internal metadata cache in librdkafka and it gets updated both by internally triggered metadata refreshes as well as application triggered metadata() calls.

**Comment by edenhill** [comment]
And yes, you must destroy the returned metadata data, the cache uses its own copy.

**Comment by lathakris** [comment]
ok thank you very much for the clarification.
