### ISSUE TITLE
"compression.type" fails to set with rd_kafka_conf_set and rd_kafka_topic_conf_set

### ISSUE THREAD

**Issue by drorgu** [edenhill/librdkafka#1885]
Hi, 
When setting Producer global parameter "compression.type" with rd_kafka_conf_set I get the following error:
No such configuration property: "compression.type"
According to https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md "compression.type" is an alias of "compression.codec".  "compression.codec" does not fail to set  rd_kafka_conf_set so the alias does not seem to work (bug maybe?).
This parameter is also a topic level parameter and when setting "compression.type" as a topic parameter with rd_kafka_topic_conf_set it also fails with the same error, but again "compression.codec" works fine.
Is this a known issue? should I only use "compression.codec"?
Thanks,
Dror

**Comment by edenhill** [comment]
You're most likely using an older librdkafka version that did not have the alias.
Use compression.codec, or upgrade.

**Comment by drorgu** [comment]
(I am using version 11.3 on CentOS 6.6 machine). I am only using producer (no consumer).

**Comment by drorgu** [comment]
OK, you're right, it was added in 11.4

Thanks,
Dror
