### ISSUE TITLE
rd_kafka_conf_get and rd_kafka_topic_conf_get fail with RD_KAFKA_CONF_UNKNOWN (-2) on many of the parameters in CONFIGURATION.md

### ISSUE THREAD

**Issue by drorgu** [edenhill/librdkafka#1886]
Hi, 

(I am using version 11.3 on CentOS 6.6 machine). I am only using producer (no consumer).

rd_kafka_conf_get and rd_kafka_topic_conf_get fail with RD_KAFKA_CONF_UNKNOWN (-2) on many of the parameters in CONFIGURATION.md (in https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md).

Here's what I get when trying to print all producer global parameters and Topic parameters as listed in CONFIGURATION.md (the global parameters are followed by topic parameters): 

*** For Global Configuration:

builtin.features = gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins
client.id = rdkafka
metadata.broker.list = localhost:9092
bootstrap.servers = localhost:9092
message.max.bytes = 1000000
message.copy.max.bytes = 65535
receive.message.max.bytes = 100000000
max.in.flight.requests.per.connection = 1000000
max.in.flight = 1000000
metadata.request.timeout.ms = 60000
topic.metadata.refresh.interval.ms = 300000
metadata.max.age.ms = -1
topic.metadata.refresh.fast.interval.ms = 250
topic.metadata.refresh.fast.cnt = 10
topic.metadata.refresh.sparse = true
failed to get value of conf key 'topic.blacklist' (-2)
debug =
socket.timeout.ms = 60000
socket.blocking.max.ms = 1000
socket.send.buffer.bytes = 0
socket.receive.buffer.bytes = 0
socket.keepalive.enable = false
socket.nagle.disable = false
socket.max.fails = 3
broker.address.ttl = 1000
broker.address.family = any
reconnect.backoff.jitter.ms = 500
statistics.interval.ms = 0
enabled_events = 0
error_cb = 0x7f0d255c3090
failed to get value of conf key 'throttle_cb' (-2)
failed to get value of conf key 'stats_cb' (-2)
log_cb = 0x7f0d2458db90
log_level = 6
log.queue = false
log.thread.name = true
log.connection.close = true
failed to get value of conf key 'background_event_cb' (-2)
socket_cb = 0x7f0d245a1280
failed to get value of conf key 'connect_cb' (-2)
failed to get value of conf key 'closesocket_cb' (-2)
open_cb = 0x7f0d245b1ae0
failed to get value of conf key 'opaque' (-2)
failed to get value of conf key 'default_topic_conf' (-2)
internal.termination.signal = 0
api.version.request = true
api.version.request.timeout.ms = 10000
api.version.fallback.ms = 1200000
broker.version.fallback = 0.9.0
security.protocol = plaintext
failed to get value of conf key 'ssl.cipher.suites' (-2)
failed to get value of conf key 'ssl.curves.list' (-2)
failed to get value of conf key 'ssl.sigalgs.list' (-2)
failed to get value of conf key 'ssl.key.location' (-2)
failed to get value of conf key 'ssl.key.password' (-2)
failed to get value of conf key 'ssl.certificate.location' (-2)
failed to get value of conf key 'ssl.ca.location' (-2)
failed to get value of conf key 'ssl.crl.location' (-2)
failed to get value of conf key 'ssl.keystore.location' (-2)
failed to get value of conf key 'ssl.keystore.password' (-2)
sasl.mechanisms = GSSAPI
failed to get value of conf key 'sasl.mechanism' (-2)
sasl.kerberos.service.name = kafka
sasl.kerberos.principal = kafkaclient
sasl.kerberos.kinit.cmd = kinit -S "%{sasl.kerberos.service.name}/%{broker.name}" -k -t "%{sasl.kerberos.keytab}" %{sasl.kerberos.principal}
failed to get value of conf key 'sasl.kerberos.keytab' (-2)
sasl.kerberos.min.time.before.relogin = 60000
failed to get value of conf key 'sasl.username' (-2)
failed to get value of conf key 'sasl.password' (-2)
failed to get value of conf key 'plugin.library.paths' (-2)
failed to get value of conf key 'interceptors' (-2)
failed to get value of conf key 'group.id' (-2)
partition.assignment.strategy = range,roundrobin
session.timeout.ms = 30000
heartbeat.interval.ms = 1000
group.protocol.type = consumer
coordinator.query.interval.ms = 600000
enable.auto.commit = true
auto.commit.interval.ms = 5000
enable.auto.offset.store = true
queued.min.messages = 100000
queued.max.messages.kbytes = 1048576
fetch.wait.max.ms = 100
fetch.message.max.bytes = 1048576
max.partition.fetch.bytes = 1048576
failed to get value of conf key 'fetch.max.bytes' (-2)
fetch.min.bytes = 1
fetch.error.backoff.ms = 500
offset.store.method = broker
failed to get value of conf key 'consume_cb' (-2)
failed to get value of conf key 'rebalance_cb' (-2)
failed to get value of conf key 'offset_commit_cb' (-2)
enable.partition.eof = true
check.crcs = false
queue.buffering.max.messages = 100000
queue.buffering.max.kbytes = 1048576
queue.buffering.max.ms = 200
linger.ms = 200
message.send.max.retries = 2
retries = 2
retry.backoff.ms = 100
failed to get value of conf key 'queue.buffering.backpressure.threshold' (-2)
compression.codec = none
failed to get value of conf key 'compression.type' (-2)
batch.num.messages = 50
delivery.report.only.error = false
failed to get value of conf key 'dr_cb' (-2)
dr_msg_cb = 0x7f0d255c30c0

*** For Topic Configuration:

request.required.acks = -1
acks = -1
request.timeout.ms = 5000
message.timeout.ms = 6000
failed to get value of conf key 'queuing.strategy' (-2)
produce.offset.report = true
failed to get value of conf key 'partitioner' (-2)
failed to get value of conf key 'partitioner_cb' (-2)
failed to get value of conf key 'msg_order_cmp' (-2)
failed to get value of conf key 'opaque' (-2)
compression.codec = inherit
failed to get value of conf key 'compression.type' (-2)
failed to get value of conf key 'compression.level' (-2)
auto.commit.enable = true
enable.auto.commit = true
auto.commit.interval.ms = 60000
auto.offset.reset = largest
offset.store.path = .
offset.store.sync.interval.ms = -1
offset.store.method = broker
consume.callback.max.messages = 0

Thanks,
Dror

**Comment by edenhill** [comment]
String configuration properties, such as sasl.username, will return UNKNOWN if they are not set (NULL).
The callback/pointer based properties (e.g., partitioner_cb) behave the same way.
This is a bug.

I can't reproduce the non-string failures you see though, such as fetch.max.bytes.

**Comment by drorgu** [comment]
OK, we will install 11.4 and try to reproduce the non-string failures. 
I should mention though (if it makes a difference) that we did not set fetch.max.bytes (so the value is the default one).
Thanks,
Dror
