### ISSUE TITLE
Can producer immediately perceive the broker disconnected?

### ISSUE THREAD

**Issue by tuhangdi** [edenhill/librdkafka#1888]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>

We want to cache messages when the broker connection is not available， so i want to know if producer can immediately perceive the broker disconnected， or is there any other way?

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<0.9.2>`
 - [ ] Apache Kafka version: `<0.10.2.1>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<SUSE Linux Enterprise Server 11 SP3  (x86_64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The library already queues messages internally for up to `message.timeout.ms` waiting for the leader broker(s) to become available, so there is no reason for your application to do the same.

You can register an error_cb and check for ERR__TRANSPORT to see when brokers go down, but there is no corresponding log when they come back up again.

Also, 0.9.2 is really old, upgrade to v0.11.4

**Comment by tuhangdi** [comment]
so if all brokers go down and wait timeout，can i save messages or other data to the local

**Comment by edenhill** [comment]
You will get a delivery report callback when the messages times out, at which time you can store them in a local disk cache.

**Comment by aarjan** [comment]
@edenhill  
i can't get error message when creating a producer if the broker is not connected / down !

**Comment by edenhill** [comment]
@aarjan That is intended, otherwise it would not be possible to start the client when a broker or network is down.

**Comment by edenhill** [comment]
If all brokers are down you will get the ALL_BROKERS_DOWN error raised.

**Comment by aarjan** [comment]
@edenhill I am using the https://github.com/confluentinc/confluent-kafka-go client, so basically this error message should be sent to the error channel in that client right?

**Comment by edenhill** [comment]
Yes, it will be an Error event with code ErrAllBrokersDown on the Events channel.

**Comment by aarjan** [comment]
But, i just get the Delivery failed error message after the timeout!

**Comment by edenhill** [comment]
Make sure you use the latest version of confluent-kafka-go and librdkafka (both v0.11.6), there was an issue with earlier versions not raising errors properly.

**Comment by aarjan** [comment]
I am sorry, i just went with the default docs in the repo, and i didn't checked for other errors.
Thank you very much for your prompt response!
