### ISSUE TITLE
Strange  behavior reading 2 topics with one consumer question

### ISSUE THREAD

**Issue by rapIsKal** [edenhill/librdkafka#1891]
Description
===========
Hi, I'm expecting some interesting behavior when consumer client trying to read from 2 topics in Kafka when Kafka queue is quite full.
I see from monitoring that messages are read in batches - batch from topic 1, then batch from topic 2.
Is this a correct behavior? And what may cause that?

How to reproduce
================
1. Fill Kafka server with messages of topic 1 and topic 2. Load is constant on both
2. connect python client confluent-kafka to consumer

Checklist
=========

 - [x] confluent-kafka version v0.11.5rc0 
 - [x] Apache Kafka version: 1.0
 - [x] librdkafka client configuration:
                "auto.commit.interval.ms": 1000, 
                "bootstrap.servers": <server_pool>
                "debug": "all", 
                "default.topic.config": {
                    "auto.offset.reset": "smallest"
                }, 
                "enable.auto.commit": false, 
                "enable.auto.offset.store": true, 
                "group.id": "mygroup", 
                "session.timeout.ms": 6000
 - [x] Operating system: Red Hat 7.5
 - [ ] Provide logs 
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#how-are-partitions-fetched

**Comment by rapIsKal** [comment]
Sorry, I don't exactly get it. I see that it's about reading partitions. Does it mean that in that case client firstly serves all the partitions in topic1 and then partitions in topic2? I don't really understand that from the FAQ

**Comment by edenhill** [comment]
Messages are fetched in batches from the broker, each batch containing 1 or more messages for a single partition.
When these batches are returned to the consumer the consumer enqueues these messages in the order they were received which is first messages for partition 1, then partition 2, etc.
