### ISSUE TITLE
Mapr Streams | "No such configuration property: "streams.producer.default.stream"" 

### ISSUE THREAD

**Issue by vivekgopinathlal** [edenhill/librdkafka#1893]
Description
===========
Trying to work with mapr streams. As directed 
 in https://maprdocs.mapr.com/home/MapR_Streams/MapRStreamsPythonExample.html

Error:

> cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "streams.producer.default.stream""}

How to reproduce
================
```
>>> from confluent_kafka import Producer
>>> p = Producer({'streams.producer.default.stream': '/apps/iot-stream'})

```

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `librdkafka-0.11.5`
 - [x] Apache Kafka version: `0.9.0`
 - [x] Operating system: `Centos 6.5 (x64)`
 - [x] Pyspark version `version 2.1.0-mapr-mep-3.x-1803`
 - [x] Mapr version `5.2.2.44680.GA`

**Comment by rolandyoung** [comment]
That property is supported only by the MapR fork of librdkafka. Please note this step from the web page you refer to above:

> Verify that you have completed the steps to configure the MapR-ES C client or complete the steps now. See Configuring the MapR-ES C Client.

See also [https://maprdocs.mapr.com/home/MapR_Streams/MapRStreamsCApplications.html](https://maprdocs.mapr.com/home/MapR_Streams/MapRStreamsCApplications.html)
and [Configuration Properties for MapR-ES C Client](https://maprdocs.mapr.com/home/MapR_Streams/StreamsConfigurationC.html#reference_q2k_wpq_fz)
