### ISSUE TITLE
err: Local: Message timed out: (errno: Connection timed out)

### ISSUE THREAD

**Issue by DavidLiuXh** [edenhill/librdkafka#1894]
Description
===========
1. Run producer;
2. After running for a while, send a message failed: failed: err: Local: Message timed out: (errno: Connection timed out);
3. Kafka broker is ok.
4. I tried to change the configuration, still have problems.
    message.send.max.retries=5                                                                                                                                                                                              retry.backoff.ms=1000

How to reproduce
================

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version: 0.9.4 591103
 - [x] Apache Kafka version: 0.9.0.1
 - [ ] librdkafka client configuration: message.send.max.retries=5 retry.backoff.ms=1000
 - [ ] Operating system:  Centos 6.2 
 - [ ] Provide logs: debug=broker,topic,queue,msg,protocol
[rdkafka_log.tar.gz](https://github.com/edenhill/librdkafka/files/2222696/rdkafka_log.tar.gz)

 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by DavidLiuXh** [comment]
@edenhill 
1. The api.version.request default value is false in the librdkafka 0.9.4
2. I fixed this problem "Due to a bug in broker version 0.9.0.0 & 0.9.0.1 the broker will not close the connection when receiving the API version request" and close connection by broker.

I don't understand why this timeout problem still occurs.

**Comment by edenhill** [comment]
Please share your config

**Comment by DavidLiuXh** [comment]
@edenhill 

debug=broker,topic,queue,msg,protocol
message.send.max.retries=5                                                                                                                                                                                         retry.backoff.ms=1000                                                                                                                                                                                              socket.timeout.ms=120000

**Comment by edenhill** [comment]
Please upgrade and try to reproduce on v0.11.5

**Comment by DavidLiuXh** [comment]
@edenhill  I upgrade rdkafka to 0.11.5 and reproduced.

1. my config:
api.version.request=false                                                                                                                                                                                          
broker.version.fallback=0.9.0.1                                                                                                                                                                                    
debug=broker,topic,queue,msg,protocol      
message.send.max.retries=5                                                                                                                                                                                         
retry.backoff.ms=1000                                                                                                                                                                                              
socket.timeout.ms=120000
 
2. log                                                                                                                                                                       
[rdkafka.tar.gz](https://github.com/edenhill/librdkafka/files/2269795/rdkafka.tar.gz)

**Comment by edenhill** [comment]
The broker stops responding to ProduceRequests after the last one here:
```
Wed Aug  8 09:18:32 2018
 | RD_KAFKA_LOG | level: 7 | fac: RECV | msg: [thrd:10.208.49.157:9092/9]: 10.208.49.157:9092/9: Received ProduceResponse (v1, 37 bytes, CorrId 39974, rtt 1.50ms)
```

and doesn't start again until after the connection is reset.

There is nothing in the logs indicating why this might be, so I suggest looking in the broker logs. around that time for clues.

Also look at `netstat -anp | grep 10.208.49.157:9092` when this happens to see if the send or receive queues of the socket are building up.
If the send queue is increasing it means the broker is not reading any more messages,
if the receive queue is increasing it means the client is not reading any more.

**Comment by DavidLiuXh** [comment]
@edenhill It is a full gc problem on the broker side

**Comment by DavidLiuXh** [comment]
@edenhill 

     We released a kafkabridge(kafka client sdk) based on librdkafka.
     github: https://github.com/Qihoo360/kafkabridge

      Librdkafka is a very good kafka client. Thank you very much~

**Comment by edenhill** [comment]
@DavidLiuXh That looks interesting! Feel free to add it here:
https://github.com/edenhill/librdkafka/wiki/Powered-by-librdkafka
