### ISSUE TITLE
0.11.5 won't compile with libressl 2.7.4 (latest)

### ISSUE THREAD

**Issue by secretmike** [edenhill/librdkafka#1896]
Description
===========
`librdkafka` 0.11.5 doesn't compile using the latest `libressl` (2.7.4). 

The commit adding support for the `ssl.sigalgs.list` config option (https://github.com/edenhill/librdkafka/commit/3cc0ab6070d7cda1e5f05d7160ff855945561e4f) checks the version of openssl (`#if OPENSSL_VERSION_NUMBER >= 0x1000200fL`) to determine if the `SSL_CTX_set1_sigalgs_list()` function is available.

Libressl (for some reason) defines the `OPENSSL_VERSION_NUMBER` as `0x20000000L`, but it doesn't (yet) support these newer APIs.

AlpineLinux builds packages using Libressl, which means the latest `librdkafka` doesn't compile on AlpineLinux. (See my attempt here: https://github.com/alpinelinux/aports/pull/4841 )

How to reproduce
================
See linked alpinelinux PR above. This Dockerfile will also reproduce (it succeeds if you change `0.11.5` to `0.11.4`):
```Dockerfile
FROM alpine:3.8

RUN apk add --no-cache build-base bash python2 libressl-dev zlib-dev

RUN mkdir -p /test
WORKDIR /test

ADD https://github.com/edenhill/librdkafka/archive/v0.11.5.tar.gz /test/

RUN tar xzf v0.11.5.tar.gz
WORKDIR /test/librdkafka-0.11.5

RUN ./configure --prefix=/usr
RUN make
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.5`
 - [x] Apache Kafka version: `N/A`
 - [x] librdkafka client configuration: `N/A`
 - [x] Operating system: `Alpine Linux 3.8 & edge`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by secretmike** [comment]
This diff from nginx suggests a possible workaround:

https://forum.nginx.org/read.php?29,265780,265780#msg-265780

```
+#if (defined LIBRESSL_VERSION_NUMBER && OPENSSL_VERSION_NUMBER == 0x20000000L)
+#undef OPENSSL_VERSION_NUMBER
+#define OPENSSL_VERSION_NUMBER 0x1000107fL
+#endif
```

**Comment by yongtang** [comment]
I encountered a similar issue with boringssl.

**Comment by secretmike** [comment]
@rnpridgeon I gave a try with `openssl-dev` as you suggested and it does successfully build. However, alpinelinux made an overall shift to libressl a couple years ago (http://lists.alpinelinux.org/alpine-devel/5463.html), so it wouldn't be possible to link to `librdkafka` from other alpinelinux packages if it used openssl.

Possibly another option would be to provide a configure flag to explicitly disable the new functionality?

I'm happy to submit a patch, but I'd be grateful to know which solution would be preferred.

Thanks!

**Comment by rnpridgeon** [comment]
@secretmike I agree in the long term its best to offer some way to disable this feature to increase portability. Please do go ahead and submit a PR when you are ready. We will need @edenhill to make the final call on such a change but I will be more than happy to do a preliminary review until he is able to get to it.

**Comment by secretmike** [comment]
@rnpridgeon I put up https://github.com/edenhill/librdkafka/pull/1901 as a possible solution. I confirmed this fixes the build with LibreSSL (sigalgs and curves options are disabled) and works correctly with later openssl (sigalgs and curves options enabled).

**Comment by edenhill** [comment]
I think in this particular case we're better of with the `#if ..` checks rather than configure checks, even though the latter are generally "more correct", they will not be used on Windows where build config is set manually in win32_config.h

**Comment by secretmike** [comment]
Ok, makes sense. I'll modify the PR shortly.

**Comment by secretmike** [comment]
@edenhill Updated PR (https://github.com/edenhill/librdkafka/pull/1901) using define tests instead of configure. Thanks!
