### ISSUE TITLE
How to disable -lpthread option?

### ISSUE THREAD

**Issue by ChiftKey** [edenhill/librdkafka#1897]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>

Hi~

How to disable `-lpthread` Option on `configure` file??

I've been trying to compile for Android Device by NDK

I passed command like this

```
./configure \
--prefix=/home/steve/arm/ \
--cc=/home/steve/arm/bin/arm-linux-androideabi-gcc \
--cxx=/home/steve/arm/bin/arm-linux-androideabi-g++ \
--arch=arm
```
then

I found some error while configuring
```
checking for OS or distribution... ok (Ubuntu)
checking for C compiler from CC env... ok
checking for C++ compiler from CXX env... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... failed
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x000b05ff'... ok (0.11.5)
checking for librt (by compile)... failed
checking for libpthread (by compile)... failed (fail)
checking for libdl (by compile)... ok
checking for zlib (by compile)... ok
checking for libcrypto (by compile)... failed (disable)
checking for libm (by compile)... ok
checking for liblz4 (by compile)... failed (disable)
checking for rapidjson (by compile)... failed (disable)
checking for libssl (by compile)... failed (disable)
checking for libsasl2 (by compile)... failed (disable)
checking for libsasl (by compile)... failed (disable)
checking for crc32chw (by compile)... failed (disable)
checking for regex (by compile)... ok
checking for strndup (by compile)... ok
checking for strerror_r (by compile)... ok
checking for pthread_setname_gnu (by compile)... failed (disable)
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok



###########################################################
###                  Configure failed                   ###
###########################################################
### Accumulated failures:                               ###
###########################################################
 libpthread ()
    module: librdkafka
    action: fail
    reason:
compile check failed:
CC: CC
flags: -lpthread
/home/steve/arm/bin/arm-linux-androideabi-gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpvF1NP4.c -o _mkltmpvF1NP4.c.o   -lpthread:
/home/steve/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lpthread
collect2: error: ld returned 1 exit status
source: #include <pthread.h>
```

as far as i know, pthread libary is included in bionic (android C Library)
so, I want to disable that option.

Thanks.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Try changing `"-lpthread"` to `""` on line 45 in configure.librdkafka:
https://github.com/edenhill/librdkafka/blob/master/configure.librdkafka#L45

**Comment by ChiftKey** [comment]
Thanks It works for me ^^
