### ISSUE TITLE
rdkafka_performance: Option to dump the actual producer configuration

### ISSUE THREAD

**Issue by ankon** [edenhill/librdkafka#1900]
Description
===========

I'm right now tracking down some latency issues in our application, which I believe are caused by us doing something horribly stupid such as setting a flag to the wrong value. I could verify with `rdkafka_performance` against our Kafka cluster that neither Kafka nor librdkafka could be the main cause, because using the performance tool showed that these parts are certainly able to provide loads of throughput with awesome latency :)

What I would like to have is a way in the `rdkafka_performance` tool to dump the actual configuration used, so I can compare things.

I hacked it in manually now:
```diff
diff --git a/examples/rdkafka_performance.c b/examples/rdkafka_performance.c
index e45406b..0083207 100644
--- a/examples/rdkafka_performance.c
+++ b/examples/rdkafka_performance.c
@@ -1245,6 +1245,17 @@ int main (int argc, char **argv) {
                         stats_fp = stdout;
         }
 
+	if (verbosity > 1) {
+                /* Dump the configuration */
+                size_t count;
+                size_t i;
+                const char **dump = rd_kafka_conf_dump(conf, &count);
+                for (i = 0; i < count; i += 2) {
+                        fprintf(stderr, "%% %s=%s\n", dump[i], dump[i+1]);
+                }
+                rd_kafka_conf_dump_free(dump, count);
+        }
+
 	if (msgcnt != -1)
 		forever = 0;
 
```

Is this something you'd consider accepting, i.e. shall I create a PR for it?

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 44242a4
 - [x] Apache Kafka version: 1.1.0
 - [x] Operating system: Linux x86_64

**Comment by mhowlett** [comment]
The performance tool allows you to specify configuration parameters from a file via the -X flag. Can you not just set up your testing process to use that? I would say adding the ability to dump the config has marginal benefit and is best left out. @edenhill may want to comment further.

**Comment by ankon** [comment]
I can _set_ the options just fine. In my case the problem is that the performance tool manages to get great performance, while my client doesn't. Being able to see what the tool configured helps me to figure out where I am potentially off or could be looking at interesting options I'm missing.

**Comment by edenhill** [comment]
You could copy the following block of code from rdkafka_example.c to rdkafka_performance.c to have it dump its configuration just prior to creating the client instance:
https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.c#L504
