### ISSUE TITLE
About the metrics of Statistics

### ISSUE THREAD

**Issue by lyz0907** [edenhill/librdkafka#1903]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi,

The broker level "tx", total number of requests sent. What's specific meaning of "total" ? Which represents the sum of all requests for a client_id ? Which is a non-decreasing value ? 

For example, statistics.interval.ms equals 60000, when a client_id sent 2 requests to a broker in first minute, and sent 5 requests to the same broker in second minute, so the broker "tx"  values were 2, 7 ? Do I understand correctlly ?

Thanks!

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.11.1 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
@lyz0907, yes your assessment sounds correct to me. Do note however that the aggregate metrics may not always represent the sum of their parts as mentioned in the statistics page.

>  The metrics returned may not be completely consistent between brokers, toppars and totals, due to the internal asynchronous nature of librdkafka. E.g., the top level tx total may be less than the sum of the broker tx values which it represents.

https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

**Comment by mhowlett** [comment]
yep, the broker level `tx` metric is a counter (never decreases).

**Comment by lyz0907** [comment]
@rnpridgeon, thank you for the clarification !

**Comment by lyz0907** [comment]
@mhowlett , thanks for your answer !
