### ISSUE TITLE
static linking with v0.11.5 problem: undefined symbol: sqrt

### ISSUE THREAD

**Issue by alorbach** [edenhill/librdkafka#1904]
Description
===========
We are building librdkafka from source on Ubuntu 16 (Xenial) to build kafka modules in rsyslog. We statically link the library into our own modules to avoid using old outdated librdkafka versions from the system OS. 

Until 0.11.4 this went well, we tried to update our sources from 0.11.4 to 0.11.5 and suddenly our modules fail to load with the following error: 

could not load module '/usr/lib/rsyslog/imkafka.so', dlopen: /usr/lib/rsyslog/imkafka.so: undefined symbol: sqrt  

sqrt is a math function and only used in "rdhdrhistogram.c". We tried adding -lm into CFLAGS when building librdkafka: 
CFLAGS=-lm

But it didn't fix the problem. 

As rdhdrhistogram.c appears to be added recently, some dependencies seem not to be set correctly.

**Comment by rnpridgeon** [comment]
Thanks for reporting this @alorbach. I think I'll need to dig around in mklove a bit to figure out why you are seeing this but I'll report back once I have a better understanding as to why this is happening.

**Comment by alorbach** [comment]
If you would enable the configure to enable/disable the precompiled variable "WITH_HDRHISTOGRAM", this would help during meantime to build librdkafka statically. We can just disable the new feature then.

**Comment by alorbach** [comment]
Not yet as we had to find a solution during meantime and next time we can test this solution will be when new packages for rsyslog will be created.

**Comment by alorbach** [comment]
pkg-config approach does not work for us. 
We still use our ENABLE_HDR_HIST patch from above.
