### ISSUE TITLE
Look up the offsets for the given partitions by timestamp.

### ISSUE THREAD

**Issue by congchp** [edenhill/librdkafka#1907]
Hi all.

Description
===========
Can we look up the offsets for the given partitions by **timestamp** in librdkafka? Or consume from some timestamp?

like this in java kafka client:

java.util.Map<TopicPartition,OffsetAndTimestamp> offsetsForTimes(java.util.Map<TopicPartition,java.lang.Long> timestampsToSearch)

**Comment by rnpridgeon** [comment]
Sure can 

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2291-L2318

**Comment by congchp** [comment]
Thanks.
C has this function. Does C++ have this function?
