### ISSUE TITLE
 Can we know who published each message

### ISSUE THREAD

**Issue by XinyaoShen** [edenhill/librdkafka#1908]
Description
===========
Hi @edenhill,

I'm wondering can consumer knows who published each message into Kafka Topic? Is the publisher information stored into Message itself or any other way that we could retrieve such information?

If such publisher information doesn't exist in each message, we might plan to add it into message header, which I found has been supported in C api.

I'm wondering is there any api to retrieve current userid after finishing authentication? We could use such api to add the publisher information to header.

Thanks very much!

**Comment by ossberyl** [comment]
Hi @edenhill We're also looking into similar question, if such publisher information doesn't exist in each message, we might plan to add it into message header, which I found has been supported in C api.

I'm wondering is there any api to retrieve current userid after finishing authentication? We could use such api to add the publisher information to header.

Thanks very much!

**Comment by rnpridgeon** [comment]
Your best bet would be to embed the client id into a message header as you have suggested. There is no API to retrieve the current users userid however you should have all the information available to you in your client's configuration. If your client is configured to use the SASL GSSAPI mechanism your userid will be configured with `sasl.kerberos.service.name`. If you are using SCRAM or PLAIN SASL mechanisms however you will want to check `sasl.username`. 

If you are relying on TLS mutual auth the userid is the complete DN from the certificate you have stored at `ssl.certificate.location`

**Comment by XiaoyaoFan** [comment]
@rnpridgeon Thanks for the detailed reply!

We plan to add both the userid and client id into message header to indicate both the user's and application's information. 

Another question would be, is there any tool in Kafka to retrieve the exact host:port(might be a list of host:port if multiple client applications are sharing same client id) by giving a client id? 

I know that might not be appropriate to ask the Kafka server operational question here, but it would be great if you have some ideas on that, thanks in advance!
