### ISSUE TITLE
consume from some timestamp

### ISSUE THREAD

**Issue by congchp** [edenhill/librdkafka#1910]
Hi all.
Description

Can we consume from some given timestamp in C++ librdkafka?

**Comment by mhowlett** [comment]
@congchp - the `rd_kafka_offsets_for_times` function is what you're looking for:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2292

**Comment by congchp** [comment]
Thanks. @mhowlett 
But how can we input timestamp? use offsets as timestamp?

rd_kafka_offsets_for_times (rd_kafka_t *rk,
                            rd_kafka_topic_partition_list_t *offsets,
                            int timeout_ms);

**Comment by congchp** [comment]
Thanks very much for your  answer.  @mhowlett :)

**Comment by congchp** [comment]
Hi @mhowlett 
I used offsetsForTimes (std::vector<TopicPartition*> &offsets, int timeout_ms) to get offset.
Sometimes it can get offset successfully. But it returns ERROR('Local: Timed out') for many times?

and after getting offset successfully,  I use assign (const std::vector<TopicPartition*> &partitions), want to consume from the offset, but sometimes it didnt consume from the offset.

**Comment by edenhill** [comment]
Use `debug=fetch` to see what partitions it is trying to consume

**Comment by congchp** [comment]
just one topic. and one partition. @edenhill

**Comment by edenhill** [comment]
`debug=fetch` will tell you why it is not fetching.
