### ISSUE TITLE
Broker list string limit

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#1915]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
This is a request for clarification.

We have several configurations where there may be 20+ brokers. It is necessary for us to provide the entire list of brokers to librdkafka? We could start with 5, for instance. 

I have checked the rd_kafka data structures and they *do* get updated when brokers come and go. I don't have to do anything explicit to keep librdkafka's broker list current.

1. How many brokers addresses does librdkafka need at the minimum?
2. Let's say we started with brokers a, b, c. Then d, e and f came along. rdkafka updates its data structures. However, if a, b and c went down, will our connections to Kafka via librdkafka fail?

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.3`
 - [ ] Apache Kafka version: `1.0.0>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<Redhat 7.2>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mhowlett** [comment]
the client only needs to be able to connect to one broker on startup. specifying more than one is just for redundancy (on startup). If you start with brokers a,b,c, then d,e,f come along and a,b,c fail, the client will not fail. However, if you restarted the client, it wouldn't be able to connect to the cluster in that scenario (of course) because none of the configured bootstrap.servers are available.

**Comment by blandings** [comment]
Thank you!
