### ISSUE TITLE
mklove/modules/configure.base: line 1485: source: configure.librdkafka: file not found

### ISSUE THREAD

**Issue by jaltone** [edenhill/librdkafka#1919]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
./configure --prefix=/apps/local
mklove/modules/configure.base: line 1485: source: configure.librdkafka: file not found

How to reproduce
================
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.9 (Santiago)

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (librdkafka-0.11.5): v0.11.5
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: Red Hat Enterprise Linux Server release 6.9 (Santiago)
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Is this from a completely untouched librdkafka source directory?
How did you retrieve the source code?e

**Comment by jaltone** [comment]
I clicked on Download ZIP last week.

**Comment by edenhill** [comment]
That is very weird, can you show all your steps from unzip to ./configure failing in one long cutnpaste?

**Comment by jaltone** [comment]
I began to suspect that there is something in my .bashrc that is causing this problem. So I renamed my .bashrc and ran the configure command again. And this time the problem went away. I haven't determined what the root cause is, but I'll probably do this much later. Apologies for wasting your time.
