### ISSUE TITLE
Seek with high-level consumer

### ISSUE THREAD

**Issue by gadde-cern** [edenhill/librdkafka#1925]
Description
===========
Hi!

Thank you for all your work on librdkafka. It is very useful to us.

I am writing a piece of software that uses kafka only for streaming records without committing anything and I am not subscribing to topics but just self assigning topics.
I am using the high level consumer through cppkafka.
I can still access the underlying rdkafka objects to add missing features.

I would like to know if I can use rd_kafka_seek with the high-level consumer.
I can see it is tagged as simple consumer API but I could retrieve the rd_kafka_topic_t through rd_kafka_topic_new that caches the existing objects.

Could this work?
Would this be significantly faster than re assigning the same topics with different offsets?

How to reproduce
================
N/A

Checklist
=========

 - [x] librdkafka version (release number or git tag): `<v0.11.4>`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Yes, you may use seek() as you suggest, the only thing you need to know is that seek() is only allowed when the partition has been assigned (assign()). So use assign() for the initial offset, and seek() to update the position while consuming.
Also note that the pre-fetched message queue will be purged when you seek(), so if you do it often you might want to decrease its size to optimize bandwidth usage (queued.min.messages and queued.max.message.kbytes).

Callign assign() will stop all fetchers, purge all queues, and then start fetching the new partition set, so it is much more costly than just seek().

**Comment by gadde-cern** [comment]
Great. I will give it a try then.
Thank you.

**Comment by gadde-cern** [comment]
I did implement it. It works great and fast.

I hit a problem though. The seek version blocks for almost 3 minutes when it shuts down ) in rd_kafka_destroy. The "reassigns every time" version does not have this delay on destroy. I am destroying all my messages ( and also polling the consumer to exhaustion) before destruction.
Do you have any clue of a side effect of using seek with the high level consumer as I am doing that could explain this behavior?
( by the way, I also happen to use rd_kafka_queue_io_event_enable, just in case it is relevant)

in the log, I  can see:
%7|1533750125.517|TOPBRK|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Topic prototype_US_2019-06-21 [0]: leaving broker (0 messages in xmitq, next leader (none), rktp 0x7f148c035440)
%7|1533750125.517|TOPBRK|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Topic prototype_US_2019-06-21 [0]: no next leader, failing 0 message(s) in partition queue
%7|1533750125.517|TERM|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Received TERMINATE op in state UP: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1533750125.517|BROKERFAIL|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
%7|1533750125.518|FAIL|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Client is terminating
%7|1533750125.518|STATE|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Broker changed state UP -> DOWN
%7|1533750125.618|TERMINATE|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Handle is terminating in state DOWN: 1 refcnts (0x7f148c000be0), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1533750125.618|BROKERFAIL|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
%7|1533750125.618|MEMBERID|rdkafka#consumer-2| [thrd:app]: Group "dummy": updating member id "" -> "(not-set)"
which seems that the local broker was destroyed earlier than expected and timed out in the destruction process.

I give more log in attachment.

Many thanks for your inputs.

[kafka-logs.txt](https://github.com/edenhill/librdkafka/files/2271334/kafka-logs.txt)

**Comment by edenhill** [comment]
Thank you for the log, would it be possible to get the entire log?
I'm particularily interested in what happens to broker thread `thrd:opamux0790.:9092/0` before the current log.

**Comment by edenhill** [comment]
Moving to #1928
