### ISSUE TITLE
Consumer not receiving messages or EOF after upgrading from v0.11.4 to v0.11.5

### ISSUE THREAD

**Issue by qed-** [edenhill/librdkafka#1926]
Consumer does not receive any messages or partition EOF after upgrading from v0.11.4 to v0.11.5 (via Confluent .Net client of same version). It works again after downgrading back to 0.11.4.

Tested on two clusters, both of broker version 1.1.1, the problem only occurs on one cluster. Given that fetch backoff messages are seen the difference is probably that the second one is more loaded.

THE.TOPIC is compressed (snappy) and is created but does not yet contain any messages. Auto commit is enabled and Store() (not Commit()) is called by the application.

Three logs are attached:

[0115_Cluster2.txt](https://github.com/edenhill/librdkafka/files/2269878/0115_Cluster2.txt)
shows the problem occurring with client v0.11.5

[0115_Cluster1.txt](https://github.com/edenhill/librdkafka/files/2269879/0115_Cluster1.txt)
 shows the problem not occurring with client v0.11.5 on another cluster

[0114_Cluster2.txt](https://github.com/edenhill/librdkafka/files/2269880/0114_Cluster2.txt)
client v0.11.4 working properly 

- [x] librdkafka version 0.11.5
 - [x ] Apache Kafka version: 1.1.1
 - [x] librdkafka client configuration: client.id=TheClientId
 group.id=TheGroupId
 bootstrap.servers=xxx:9092
 socket.keepalive.enable=True
 socket.nagle.disable=True
 socket.blocking.max.ms=1
 fetch.wait.max.ms=10
 fetch.min.bytes=1000000
 log.connection.close=False
 enable.auto.commit=True
 enable.auto.offset.store=False
 log_level=7
 debug=all
 - [x] Operating system:  Windows 8
 - [x ] Provide logs 
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Cluster2 does not have the topic:
```
thrd:main]: host2:9092/0: ===== Received metadata: connected =====
[thrd:main]: host2:9092/0: ClusterId: Cw_guIReTs2mtscKRWsnew, ControllerId: 0
[thrd:main]: host2:9092/0: 1 brokers, 0 topics
[thrd:main]: host2:9092/0:   Broker #0/1: host2:9092 NodeId 0
[thrd:main]: Group "TheGroupId": no topics in metadata matched subscription
```

The NewVersion_Cluster1.txt log  (v0.11.5?) ends with a "Reached initial EOF", while ..OldVersion does not. Is it possible that these two logs were switched seeing how you say that v0.11.5 did not report EOF?

**Comment by edenhill** [comment]
The log files seem to be missing the initial log lines, can you provide new ones for the two v0.11.5 consumers with all the logs from the absolute beginning of execution?
Thanks

**Comment by qed-** [comment]
[0115_Cluster1_example2.txt](https://github.com/edenhill/librdkafka/files/2270045/0115_Cluster1_example2.txt)
Here is a new example for cluster 1. It doesn't seem to contain any additional messages. I have modified them to anonymise hostnames/IP addresses/topic/group names but have not removed any lines.

If required I can get another one for cluster 2 but it will take a bit longer, unfortunately cluster1=dev, cluster2=prod.

**Comment by edenhill** [comment]
The log (with debug=all) should start with something like:
```
1533727903.921 RDKAFKA-7-MEMBERID: rdkafka#consumer-1: [thrd:app]: Group "x1": updating member id "(not-set)" -> ""
1533727903.921 RDKAFKA-7-INIT: rdkafka#consumer-1: [thrd:app]: librdkafka v0.11.5-5-gfcffe6-dirty (0xb05ff) rdkafka#consumer-1 initialized (debug 0xffff)
1533727903.921 RDKAFKA-7-WAKEUPFD: rdkafka#consumer-1: [thrd:app]: localhost:41647/bootstrap: Enabled low-latency partition queue wake-ups
1533727903.921 RDKAFKA-7-WAKEUPFD: rdkafka#consumer-1: [thrd:app]: localhost:41647/bootstrap: Enabled low-latency ops queue wake-ups
1533727903.921 RDKAFKA-7-BRKMAIN: rdkafka#consumer-1: [thrd::0/internal]: :0/internal: Enter main broker thread
1533727903.921 RDKAFKA-7-STATE: rdkafka#consumer-1: [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
1533727903.921 RDKAFKA-7-BROADCAST: rdkafka#consumer-1: [thrd::0/internal]: Broadcasting state change
...
```
so there's a bunch of stuff still missing from that log

**Comment by qed-** [comment]
There are messages written to stdout after creating the consumer but before the OnLog handler is assigned. There doesn't seem to be a way around this in the C# client.

Here's what's missing from the cluster1 example:

7|2018-08-08 12:40:11.882|TheClientId#consumer-1|MEMBERID| [thrd:app]: Group "TheGroupId": updating member id "(not-set)" -> ""
7|2018-08-08 12:40:11.891|TheClientId#consumer-1|BROKER| [thrd:app]: host1:9092/bootstrap: Added new broker with NodeId -1
7|2018-08-08 12:40:11.891|TheClientId#consumer-1|BRKREASSIGN| [thrd:main]: Group "TheGroupId" management reassigned from broker (none) to :0/internal
7|2018-08-08 12:40:11.895|TheClientId#consumer-1|CGRPSTATE| [thrd:main]: Group "TheGroupId" changed state init -> wait-broker (v1, join-state init)
7|2018-08-08 12:40:11.895|TheClientId#consumer-1|BRKMAIN| [thrd::0/internal]: :0/internal: Enter main broker thread
7|2018-08-08 12:40:11.895|TheClientId#consumer-1|INIT| [thrd:app]: librdkafka v0.11.5 (0xb05ff) TheClientId#consumer-1 initialized (debug 0xffff)
7|2018-08-08 12:40:11.897|TheClientId#consumer-1|STATE| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
7|2018-08-08 12:40:11.897|TheClientId#consumer-1|BROADCAST| [thrd:main]: Broadcasting state change
7|2018-08-08 12:40:11.899|TheClientId#consumer-1|BRKMAIN| [thrd:host1:9092/bootstrap]: host1:9092/bootstrap: Enter main broker thread
7|2018-08-08 12:40:11.899|TheClientId#consumer-1|BROADCAST| [thrd::0/internal]: Broadcasting state change
7|2018-08-08 12:40:11.900|TheClientId#consumer-1|BRKASSIGN| [thrd:main]: Group "TheGroupId" management assigned to broker :0/internal
7|2018-08-08 12:40:11.900|TheClientId#consumer-1|CONNECT| [thrd:host1:9092/bootstrap]: host1:9092/bootstrap: broker in state INIT connecting

**Comment by edenhill** [comment]
cc @mhowlett re log delegate.

**Comment by edenhill** [comment]
The latest log ends at:
```
thrd:main]: Group "TheGroup": delegating assign of 1 partition(s) to application rebalance callback on queue rd_kafka_cgrp_new: new assignment
[thrd:main]: Group "TheGroup" changed join state wait-sync -> wait-assign-rebalance_cb (v1, state up)

[thrd:main]: host1:9092/0: Heartbeat for group "TheGroup" generation id 3
..
```

Which indicates that librdkafka has emitted an OnPartitionsAssigned event to the application and now waiting for the application to call Assign() to synchronize state and start consuming.
Are you doing that?
Is this perhaps related to "Exiting polling task" further up in the log?

**Comment by edenhill** [comment]
It looks like the OnPartitionsAssigned/Revoked never makes it to your application, or your application doesn't call Assign() or Unassign(). 
Can you show your code for your OnPartitionsRevoked delegate?

Is there any chance the "Exiting poll task" is related?

**Comment by qed-** [comment]
I agree the Assigned/Revoked events are never making it to the application. The OnPartitionsRevoked handler is as follows:

_consumer.OnPartitionsRevoked += (sender, topicPartitions) =>
{
   _log.LogInformation("Revoked partitions: {0}", string.Join(",", topicPartitions));
   _consumer.Unassign();
 };

This log message is not seen in either case (which makes sense as this is when the app is starting up and subscribing for the first time).

The only difference between the two examples was upgrading the client from 0.11.4 to 0.11.5.  

The "exiting polling task" log message is not a factor - this is triggered when shutting down the app. It had run for a few minutes at this point, the working version has a partition assigned well within this time.

This is no longer reproducible in either cluster. I also don't see any Fetch backoff messages written to the log. I have not made any code changes. For completeness in case it is seen again this is the log using client 0.11.5 with the previously not working cluster:

[cluster2_working.txt](https://github.com/edenhill/librdkafka/files/2283430/cluster2_working.txt)

**Comment by edenhill** [comment]
Reopen this bug if it happens again.
