### ISSUE TITLE
consumer_close() stalls for a long time

### ISSUE THREAD

**Issue by gadde-cern** [edenhill/librdkafka#1928]
This ticket follows-up on #1925 as it was closed and I cannot reopen it.

I did implement it. It works great and fast.

I hit a problem though. The seek version blocks for almost 3 minutes when it shuts down ) in rd_kafka_destroy. The "reassigns every time" version does not have this delay on destroy. I am destroying all my messages ( and also polling the consumer to exhaustion) before destruction.
Do you have any clue of a side effect of using seek with the high level consumer as I am doing that could explain this behavior?
( by the way, I also happen to use rd_kafka_queue_io_event_enable, just in case it is relevant)

in the log, I can see:
%7|1533750125.517|TOPBRK|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Topic prototype_US_2019-06-21 [0]: leaving broker (0 messages in xmitq, next leader (none), rktp 0x7f148c035440)
%7|1533750125.517|TOPBRK|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Topic prototype_US_2019-06-21 [0]: no next leader, failing 0 message(s) in partition queue
%7|1533750125.517|TERM|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Received TERMINATE op in state UP: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1533750125.517|BROKERFAIL|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
%7|1533750125.518|FAIL|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Client is terminating
%7|1533750125.518|STATE|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Broker changed state UP -> DOWN
%7|1533750125.618|TERMINATE|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: Handle is terminating in state DOWN: 1 refcnts (0x7f148c000be0), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1533750125.618|BROKERFAIL|rdkafka#consumer-2| [thrd:opamux0790.:9092/0]: opamux0790.:9092/0: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
%7|1533750125.618|MEMBERID|rdkafka#consumer-2| [thrd:app]: Group "dummy": updating member id "" -> "(not-set)"
which seems that the local broker was destroyed earlier than expected and timed out in the destruction process.

I give more log in attachment.

Many thanks for your inputs.
[kafka-logs.txt](https://github.com/edenhill/librdkafka/files/2271371/kafka-logs.txt)

**Comment by edenhill** [comment]
Thank you for the log, would it be possible to get the entire log?
I'm particularily interested in what happens to broker thread thrd:opamux0790.:9092/0 before the current log.

**Comment by gadde-cern** [comment]
Here are two cases.

The hang-up time is longer in the second case.
I don't know if it sometimes deadlocks as I interrupt it when it is too long.

[rdkafka_case_1.log](https://github.com/edenhill/librdkafka/files/2286022/rdkafka_case_1.log)
[rdkafka_case_2.log](https://github.com/edenhill/librdkafka/files/2286023/rdkafka_case_2.log)

**Comment by edenhill** [comment]
Can you provide your client configuration?

**Comment by gadde-cern** [comment]
Sorry.

Here are 3 new files.
- A new log file (a consumer was not in debug verbosity in the previous files).
- Their corresponding configurations

A bit of Background on what the application is doing.
The applications is consuming (self assigned) {TopicsName}._MtxOfs
These topics contain offsets in the corresponding {TopicsName}. 
{TopicsName}._MtxOfs are read by two consumers successively. One to catch up in the beginning (consumer 5). The other to keep tracking (consumer 6).
Consumer 2 is fed with these offsets to seek into  {TopicsName} and get the corresponding records.

[rdkafka_case_3.log](https://github.com/edenhill/librdkafka/files/2286378/rdkafka_case_3.log)
[DataPickerConfig_consumer2.txt](https://github.com/edenhill/librdkafka/files/2286379/DataPickerConfig_consumer2.txt)
[OffsetTrackerConfig_consumer5and6.txt](https://github.com/edenhill/librdkafka/files/2286380/OffsetTrackerConfig_consumer5and6.txt)

**Comment by edenhill** [comment]
Thank you for the logs, unfortunately there is nothing there to indicate why one of the broker handler threads is blocking for that long.
Would it be possible for you to acquire a core file from the process while it is in the stalled state?
Alternatives include:
 * run the process in gdb, and hit ctrl-c when it hangs
 * run `gcore ..` on the process when it hangs
 * run `kill -6 <pid>` when it hangs (make sure that the shell was configured with `ulimit -u unlimited` before starting the app)

Then, with `gdb <app> <corefile>`, in gdb type: `thread apply all bt` and provide me the output.

**Comment by edenhill** [comment]
At what point in that log did you grab the gdb stack traces?

**Comment by gadde-cern** [comment]
During the long timeout at the end of the program while destroying the kafka consumer. It should coincide with somewhere between the two log lines:
%7|1534855287.363|FETCHADD|rdkafka#consumer-1| [thrd:opamux0790:9092/0]: opamux0790:9092/0: Removed prototype_P_Us_2019-06-21._MtxOfs [0] from fetch list (0 entries, opv 5)
%7|1534855436.245|TOPBRK|rdkafka#consumer-2| [thrd:opamux0790:9092/0]: opamux0790:9092/0: Topic prototype_C_Eu_2018-08-08 [0]: leaving broker (0 messages in xmitq, next leader (none), rktp 0x7f0854001f40)

**Comment by edenhill** [comment]
Thank you. Can you show me your termination code, I'm trying to understand what happens here?

**Comment by gadde-cern** [comment]
Hi. Sorry for my late reply.
I extracted the termination procedure (I use cppkafka, plus native librdkafka). 
Here is what it does:

cancel()
{
  rd_kafka_queue_io_event_enable(pRdKafkaQueue, -1, "1", 1);
  rd_kafka_assign(get_handle(), nullptr);
  destroy_pending_messages(); (run poll until exhaustion);
}
close()
{
  rd_kafka_consumer_close(get_handle());
}
terminate()
{
  cancel(), possibly twice (just realized this now but it does not look that bad)
  close()
}

I attach some tracing of rd_kafka functions through gdb. 
The long timeout happens just before the first occurrence of '17:42:04' in the file.
[rdkafkatrace.txt](https://github.com/edenhill/librdkafka/files/2318521/rdkafkatrace.txt)

**Comment by gadde-cern** [comment]
I will try to do this when I have some time. I am not sure how to though. I might intercept a pthread call in gdb.

**Comment by edenhill** [comment]
If it is easily reproducible you could monitor the output and hit ctrl-c in gdb when you think it has stalled

**Comment by gadde-cern** [comment]
I already did that and I sent the stack trace or am I misunderstanding ?
For my pthread comment, I meant for how close in time are the thread wake up and exit that you mentioned 3 posts ago.
