### ISSUE TITLE
Brokers leak because of refcount mismatch

### ISSUE THREAD

**Issue by thelamb** [edenhill/librdkafka#193]
To reproduce:

`valgrind --leak-check=full ./rdkafka_example -b first-server,second-server -t your-topic -P`

(Wait about 30 seconds before quitting)

Output:
```
==29251== 1,460 (1,424 direct, 36 indirect) bytes in 1 blocks are definitely lost in loss record 10 of 10
==29251==    at 0x4C29DB4: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29251==    by 0x40AA1A: rd_kafka_broker_add (rdkafka_broker.c:4112)
==29251==    by 0x415E9B: rd_kafka_brokers_add (rdkafka_broker.c:4291)
==29251==    by 0x402C8D: main (rdkafka_example.c:500)
```

There are 2 causes that I could identify:
### rd_kafka_brokers_add 
  `rd_kafka_brokers_add` calls `rd_kafka_broker_find`, which increments the broker's refcount if found. `rd_kafka_brokers_add` does not call `rd_kafka_broker_destroy` on the return value of `rd_kafka_broker_find`

Note:
`rd_kafka_broker_find` does not have a comment that the caller should call `rd_kafka_broker_destroy` on the return like `rd_kafka_broker_find_by_nodeid` has.

### rd_kafka_metadata_refresh_cb
`rd_kafka_metadata_refresh_cb` calls `rd_kafka_broker_any`, which increments the broker's recount if found. `rd_kafka_metadata_refresh_cb` does not call `rd_kafka_broker_destroy` on the return value.

 
I have a proposed fix ready and will submit a pull request

**Comment by edenhill** [comment]
Now this is what a bug report is supposed to look like! Great work!
