### ISSUE TITLE
How to specified the number of thread connected  brokers

### ISSUE THREAD

**Issue by Johnny-Three** [edenhill/librdkafka#1933]
Hi edenhill .
Can I reduce the number of thread connected  brokers ?
I notice the threads number is (1 + number of brokers).
Here I just want to use maybe 10 brokers or less .
Any way to do it ?
ps:
I read the source code but found the broker_add connection seems only add the configured brokers' ip.
which I want to do is find the whole ip list of the brokers and make some of them connected .
But I did not find a way to make it happen .
Could you give some suggestions on it ?
Thanks in advance .

**Comment by edenhill** [comment]
That is not possible today, we're looking to fix this during 2019.

**Comment by Johnny-Three** [comment]
understand . Thanks ！
