### ISSUE TITLE
SASL IO loop does not detect disconnects on Windows

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#1937]
As described in https://github.com/confluentinc/confluent-kafka-dotnet/issues/285#issuecomment-412307219

**Comment by stefanseufert** [comment]
I've seen that your fix went into 0.11.6-RC3. I tested this version today (using the pre release nuget packages for both rdkafka and the .net client). Sadly I've got to report that the issue still remains.

I'd be happy to help with fixing this issue but currently I'm not able to build the solution. I alwyas get linker errors, saying that external symbols such as _ictest and _sscanf, __iob_func cannot be resolved. The source seems to be (partially?) in openssl, but I am using the version mentioned in the readme. Any directions regarding this issue?

**Comment by edenhill** [comment]
@stefanseufert That happens when trying to link OpenSSL (with an older msvc toolchain, 120) statically on a newer Visual Studio (toolchain 140).
The fix is to change the occurences of `c:\OpenSSL...\libs\vc\static\` in win32/librdkafka.vcxproj by removing the `static\` suffix.

**Comment by stefanseufert** [comment]
@edenhill Thank you, changing the directory made my build work (the interceptor test project still fails, but I simply excluded this for now).

I'll try to pinpoint the issue (most probably this afternoon) and will keep you posted.

**Comment by stefanseufert** [comment]
The cause was even simpler than assumed in my original analysis. The poll result was not checked for the disconnect flag (POLLHUP) while in AUTH state. The pull request above adds a check for this case in the same way the situation is handled for the UP state.

**Comment by WolfspiritM** [comment]
I'm also waiting for a fix to this!
The RC didn't seem to fix it so I hope this can be integrated into the final 0.11.6.
It doesn't seem to be a big change.

Thanks @stefanseufert

**Comment by OMSKremer** [comment]
Yeah, please integrate it in v0.11.6 and do not wait for version 1.0.0, it's a really nasty problem!

Thx @stefanseufert
