### ISSUE TITLE
Error: Invalid value "ssl" for configuration property "security.protocol"

### ISSUE THREAD

**Issue by AnandRKmr** [edenhill/librdkafka#1938]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have been trying to use SSL (Nodejs Project on Mac) on my localhost Kafka Server and localhost clients(producer & consumers). However, I keep getting the error Error: Invalid value "ssl" for configuration property "security.protocol"

Error: Invalid value "ssl" for configuration property "security.protocol"
    at Producer.Client (/Users/ark/nodeproj/kafka/node_modules/node-rdkafka/lib/client.js:54:18)
    at new Producer (/Users/ark/nodeproj/kafka/node_modules/node-rdkafka/lib/producer.js:75:10)
    at Object.<anonymous> (/Users/ark/nodeproj/kafka/localhost-producer.js:77:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)

Here is the list of features and versions(0.11.5) printed by the application:
[ 'gzip',
  'snappy',
  'sasl',
  'regex',
  'lz4',
  'sasl_gssapi',
  'sasl_plain',
  'plugins' ]
As you can see SSL is missing. Can you please provide help with this?
I have tried the following things:
Brew install openssl; reconfigure librdkafka; and make; 
I have tried configure with setting CPPFLAGS=-I/usr/local/Cellar/openssl/1.0.2o_2/include/openssl LDFLAGS=-L/usr/local/Cellar/openssl/1.0.2o_2/lib ./configure
 In make logs I can see the following:
checking for libssl (by compile)... ok (cached)
checking for libsasl2 (by compile)... ok (cached)

I am wondering what is causing the issue.. can anyone please provide some inputs?

Thank you

How to reproduce
================
Use SSL setting	'security.protocol':'ssl' in the client var producer = new Kafka.Producer constructor

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.5`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `  'client.id': 'kafka',
  'metadata.broker.list': 'localhost:9093',
	'security.protocol':'ssl',
	'ssl.ca.location':'...path... to... ca-cert',
	'ssl.certificate.location':'...path.. to.... cert-client-signed',
	'ssl.key.location':'...path to ...ca-key',
	'ssl.key.password':'Andz1003a',
  'compression.codec': 'gzip',
  'retry.backoff.ms': 200,
  'message.send.max.retries': 10,
  'socket.keepalive.enable': true,
  'queue.buffering.max.messages': 100000,
  'queue.buffering.max.ms': 1000,
  'batch.num.messages': 1000000,
  'dr_cb': true`
 - [ ] Operating system: `Mac OS 10.13.6`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka will detect and build with openssl 1.0.2 or 1.1.0 if available on the system, so I suspect there's something in the node-rdkafka client's build step that is the problem.
Please open the issue on that project instead.

Also note that librdkafka is available as a brew package with all dependencies satisfied.
