### ISSUE TITLE
How to limit the interval and number of times the producer reconnects  to a broker when the broker disconnects.

### ISSUE THREAD

**Issue by tuhangdi** [edenhill/librdkafka#1940]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>

hi eden,  I set recnnocet.backoff.jitter.ms , and it is useful. I also try to set topic.metadata.refresh.interval.ms, my expected effect is that when the producer refreshes the metadata, it will no longer connect to the disconnected broker, but the fact is that the producer will still connect, which puts a lot of pressure on the firewall of my kafka server. 

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.0`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `socket.keepalive.enable=true, topic.metadata.refresh.interval.ms=60000, reconnect.backoff.jitter.ms=6000`
 - [x] Operating system: `SUSE Linux Enterprise Server 11 SP3 (x86_64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka will currently not forget about brokers it has seen, but instead try to reconnect to them indefinitely.
We have plans to make the connections more sparse and be able to forget brokers as they are removed from the cluster, but this is for later this year the earliest.

**Comment by edenhill** [comment]
dup #356
