### ISSUE TITLE
Client keeps trying to reconnect to a broker which is not available and never stop.

### ISSUE THREAD

**Issue by AAJCN** [edenhill/librdkafka#1943]
Description
===========
<your issue description goes here>
Client keeps trying to reconnect to a broker which is not available and never stop.

How to reproduce
================
When I shutdown a broker, client will know it from metadata and send message to another broker. At the same time，client will send SYN  package by reconnect.backoff.jitter.ms . Can I limit its attempts to reconnect?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag):    v0.11.0
 - [x] librdkafka client configuration: 
 topic.metadata.refresh.interval.ms 60 000
 reconnect.backoff.jitter.ms  60 000

**Comment by edenhill** [comment]
Dup of #1940
