### ISSUE TITLE
Should rd_kafka_flush always call poll?

### ISSUE THREAD

**Issue by coldeasy** [edenhill/librdkafka#1950]
Description
===========
`rd_kafka_flush` does not call `rd_kafka_poll` if the timeout given is zero. I feel like it should always call it once since if someone is trying to use this in a non-blocking way, repeatedly calling `rd_kafka_flush` with a zero timeout will not give the desired results. We can easily work around this by calling `rd_kafka_poll` repeatedly and checking the queue length afterwards however I think making `rd_kafka_flush` call `rd_kafka_poll` at least once would yield a nicer API to work with.

How to reproduce
================
Produce some messages
Repeatedly call `rd_kafka_flush`
Notice that the queue length does not decrease.

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.10.5`
 - [x ] Apache Kafka version: `0.10.2`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x ] Operating system: `Centos 6 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That makes sense, will fix :+1:

**Comment by coldeasy** [comment]
👍 Thanks!

**Comment by edenhill** [comment]
Could you try out the fix (on the fetcholdrktp branch)?

**Comment by coldeasy** [comment]
I've tested it with the python client and it works well. Thanks for the quick turnaround.

**Before**
```python
>>> producer = confluent_kafka.Producer({'bootstrap.servers': '{}:{}'.format(kafka_host, kafka_port)})
>>> producer.produce('topic', 'data')
>>> producer.produce('topic', 'data')
>>> len(producer)
3
>>> producer.flush(0)
3L
>>> len(producer)
3
```
**After**

```python
>>> producer = confluent_kafka.Producer({'bootstrap.servers': '{}:{}'.format(kafka_host, kafka_port)})
>>> producer.produce('topic', 'data')
>>> producer.produce('topic', 'data')
>>> len(producer)
4
>>> producer.flush(0)
0
>>> len(producer)
0
```

**Comment by edenhill** [comment]
Thank you!
