### ISSUE TITLE
offsetsForTimes returns ERROR('Local: Timed out')

### ISSUE THREAD

**Issue by congchp** [edenhill/librdkafka#1956]
Description
===========
Hi

I use offsetsForTimes to get offset with a constand timestamp.
Sometimes it return SUCCESS.
But sometiimes it returns ERROR('Local: Timed out'). If call the function by loop, finally it will return SUCCESS.
How can I get the reason of this Error?

```
        std::vector<RdKafka::TopicPartition*> offsets;
        auto ptr =  (std::unique_ptr<RdKafka::TopicPartition>)RdKafka::TopicPartition::create("test", 0, 1533199279903); // 1533199279903 is timestampt of offset 67
        offsets.push_back(ptr);
        RdKafka::ErrorCode err = RdKafka::ERR_NO_ERROR;
        do {
                err = m_consumer->offsetsForTimes(offsets, 20000);
                if (err)
                    dpp::appLog(dpp::LogLevel::Error, "Failed offsetsForTimes %s", RdKafka::err2str(err).c_str());
        }
        while(err);
```
Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v0.11.3-RC1>`
 - [x] Apache Kafka version: `<2.11-1.0.0>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `<REPLACE with e.g., Centos7 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Trying to reproduce this on v0.11.5 / master, to no avail.
Could you try upgrading and see if you can reproduce?
If so, also provide all output with `"debug": "broker,protocol,metadata,topic"` enabled

**Comment by congchp** [comment]
If we update librdkafka to v0.11.5, should we update Apache kafka server?

**Comment by edenhill** [comment]
No, the client and broker versions are not coupled

Den fre 17 aug. 2018 10:57congchp <notifications@github.com> skrev:
