### ISSUE TITLE
 【Consumer】look up offsets for the given partitions by timestamp

### ISSUE THREAD

**Issue by congchp** [edenhill/librdkafka#1957]
Description
===========

Look up offset for the given partitions by timestamp. Then assign this offset.
What will happen if there is no kafka message after the timestamp we input?
Seems offset() will be -1. If we assign this offset, is there any problem?
Can my consumer work?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v0.11.3-RC1>`
 - [x] Apache Kafka version: `<2.11-1.0.0>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `<REPLACE with e.g., Centos 7 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
If you pass a timestamp that is higher than any message timestamp in the partition you get -1 (which is the value of the logical END offet) back, if you pass a timestamp is lower than any message timestamp in the partition you get the lowest offset of the partition back.

You can pass both these offsets directly to assign()
