### ISSUE TITLE
cannt get current offset

### ISSUE THREAD

**Issue by congchp** [edenhill/librdkafka#1964]
Hi

Description
===========
I use consumer->position(offsets) to get current offset. Is it OK?
CURRENT-OFFSET 99
LOG-END-OFFSET 100
But offset I got is -1001.
Why?

```
        /*subscibed topic test before*/
	RdKafka::TopicPartition* ptr = RdKafka::TopicPartition::create("test", 0);
	offsets.push_back(ptr);
        m_consumer->position(offsets); // return ERR_NO_ERROR
	int64_t offset = ptr->offset();
	appLog(LogLevel::Info, "topic test current offset: %ld", offset); //offset is -1001

```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v0.11.5>`
 - [x] Apache Kafka version: `<kafka_2.11-1.0.0>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `<REPLACE with e.g., Centos 7 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by congchp** [comment]
CURRENT-OFFSET is the last message offset the application has consume, right?
in my case, position() should return 99+1.
But why return -1001?

**Comment by edenhill** [comment]
The position() is only valid for the current fetching "session", that is, if you change your assignment (assign() or subscribe()) the position() will no longer be valid.

committed() returns the committed position, while position() returns where the application is currently consuming.

**Comment by congchp** [comment]
Thanks so much, @edenhill 
apache kafka client command line can get current offset for a consumer.
I thought we should be able to do that.

**Comment by edenhill** [comment]
that's the committed offset, which you retrieve with committed()

**Comment by congchp** [comment]
I use the command line below. I think it didnt commit().
bin/kafka-consumer-groups.sh --bootstrap-server localhost:9092 --group test --describe

**Comment by edenhill** [comment]
`committed()`, not `commit()`

**Comment by congchp** [comment]
hmm. Where is the commited() function?
