### ISSUE TITLE
async send error

### ISSUE THREAD

**Issue by hitljs** [edenhill/librdkafka#197]
Hello， when i using the async_produce send messages to different kafka (one online , the other offline), when testing send message to offline succ,while sending to online none of the dr_cb will be called until kafka returns the timeout

**Comment by edenhill** [comment]
Can you reproduce this with debugging enabled? (`debug=broker,metadata,topic,msg`)

**Comment by hitljs** [comment]
yes， Failed to resolve '**********************': Name or service not known
it reported this error ，when using the sync it seems ok

**Comment by hitljs** [comment]
the server has 12 compters with 1024 partition,if there ars limits for socket threads?

**Comment by edenhill** [comment]
So if I understand you correctly you have two cases:
 * offline kafka cluster: messages are sent "succesfully"
 * online kafka cluster: messages are not sent successfully

How do you determine success? Are you using dr_cb in both cases? What is the `err` value in the dr_cb for both cases?

**Comment by edenhill** [comment]
Ping?
