### ISSUE TITLE
Does consumer rebalance clear consumer's message queue?

### ISSUE THREAD

**Issue by vchekan** [edenhill/librdkafka#1977]
Description
===========
While troubleshooting rebalance storm problem, I've noticed that my consumer (F# confluent-kafka-dotnet) does not receives reblance event and keeps processing messages long after I've triggered consumer rebalance. Experiment showed that trimming `queued.min.messages` fixed the problem and rebalance happens smoothly now.
This leads me to suspicion that librdkafka consumer does not discard internal message buffer upon receiving request for rebalance. Is this assumption correct? If yes, would it be considered undesirable behavior and subject to fix?

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.5`
 - [x] Apache Kafka version: `2.0.0-1`
 - [x] librdkafka client configuration: `  |> Config.bootstrapServers broker
  |> Config.Consumer.sessionTimeout 60000
  |> Config.Consumer.fetchMaxBytes 60000
  |> Config.Consumer.commitIntervalMs (30*1000)
  |> Config.Consumer.groupId group
  |> Config.clientId "marvel"
  |> Config.Consumer.heartbeatInterval (10*1000)
  |> Config.config "queued.min.messages" (box 3000)
  //|> Config.config "queued.max.messages.kbytes"
  |> Config.Consumer.Topic.autoOffsetReset Config.Consumer.Topic.Beginning
  |> Config.debug [Config.DebugFlags.Cgrp]
`
 - [x] Operating system: `windows10`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The consumer queue is purged when assign()/unassign() is called, which is done at rebalance.

**Comment by vchekan** [comment]
@edenhill  I have more nuanced impression.
In order for unassign/assign to be called, rebalance event needs to reach the client. And in order to do that, client needs to exhaust message queue and only when all messages from the queue are consumed, rebalance event will be fed to the client.

**Comment by vchekan** [comment]
Ahh, discovered a loop in my code which consumes with 0 zero timeout in a loop. This way it will suck all messages from librdkafka buffer and will create impression that queued.min.messages influence behavior.
Closing this.

**Comment by mensfeld** [comment]
> The consumer queue is purged when assign()/unassign() is called, which is done at rebalance.

Does it happen also when `rebalance_cb` is set manually?
