### ISSUE TITLE
MSG_COPY from   rdkafkacpp.h

### ISSUE THREAD

**Issue by wyh2015BIT** [edenhill/librdkafka#198]
some error:
   include/librdkafka/rdkafkacpp.h:517:20: error: expected unqualified-id before numeric constant
   static const int MSG_COPY = 0x2;

reason for "gcc-4.8.2.bpkg-r2/include/bits/msq.h:# define MSG_COPY      040000  /* copy (not remove) all queue messages */"
changing " MSG_COPY" into "xx_MSG_COPY" is ok

**Comment by edenhill** [comment]
Urgh, will need to rename them.
Out of curiousity, can you provide your list of system includes prior to rdkafkacpp.h inclusion

**Comment by edenhill** [comment]
Please update your code to use  RK_MSG_COPY and RK_MSG_FREE instead.
