### ISSUE TITLE
rd_clock() wraps on Windows after 7+ days

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#1980]
Depending on the host-dependent PerformanceCounter frequency, the calculation
in rd_clock() may wrap after 7 days of uptime.
Since rd_clock() is assumed to be a monotonic clock this wrap will lead to timers, timeouts, etc, stop working.

Original .NET issue: https://github.com/confluentinc/confluent-kafka-dotnet/issues/603

Introduced in v0.11.5

**Comment by queil** [comment]
@edenhill thanks for the fix. Is there any ETA for a librdkafka.redist release?

**Comment by edenhill** [comment]
We'll start the release cycle with an RC later this week, with a final release late next the earliest.

**Comment by mhowlett** [comment]
related: https://www.i-programmer.info/news/149-security/8548-reboot-your-dreamliner-every-248-days-to-avoid-integer-overflow.html

**Comment by shatilov-diman** [comment]
I've just found the issue.
May be below fix little more clean (I didn't check it):

return (now.QuadPart / freq.QuadPart) * 1000000 + ((now.QuadPart % freq.QuadPart) * 1000000) / freq.QuadPart;

**move from #998

**Comment by edenhill** [comment]
Is there a problem with the existing fix?

**Comment by shatilov-diman** [comment]
I believe* existing fix solves the issue, but I just don't like convert int to double and back, because it's slower and not so accurate as integer.

*I need a time to make internal release to recheck it.

**Comment by edenhill** [comment]
see https://github.com/confluentinc/confluent-kafka-dotnet/issues/603#issuecomment-417487187

**Comment by shatilov-diman** [comment]
> see [confluentinc/confluent-kafka-dotnet#603 (comment)](https://github.com/confluentinc/confluent-kafka-dotnet/issues/603#issuecomment-417487187)

Hmmm, existing fix two times faster of mine. Thank you for this.
