### ISSUE TITLE
Messages stuck in producer queue after topic metadata timed out

### ISSUE THREAD

**Issue by Oxymoron79** [edenhill/librdkafka#1985]
Description
===========
After a long(-ish) network loss of at least 15 minutes, I found that the Kafka Message producer fails
to transmit the messages that were produced after 15 minutes into the network loss when connectivity
was recovered.

The message buffer of the Producer had plenty of space available, the message timeout was
disabled by the configuration and the produce() call returned ERR_NO_ERROR for all produced
messages.

To investigate message losses, I wrote a Producer that produces one message per second
containing the message number. After the first 10 messages were succesfully transmitted
and aknowledged I interrupted the network connection for at least 15 minutes, producing
up to message 1000. When the connection is then re-established, the delivery report
callback function is called only up to message 899 and then continues with message 1000.
The messages 900 - 999 are permanently lost.

The debug=all output of librdkafa logged the following right between message 899 and 900:
```
DBG500: KafkaEventCb::event_cb: LOG: [thrd:main]: Topic rsc-test metadata information timed out (900215ms old)
DBG500: KafkaEventCb::event_cb: LOG: [thrd:main]: Topic rsc-test changed state exists -> unknown
```
It seems to me that after this point all messages are silently dropped, since
the produce() calls for the messages 900-999 all returned ERR_NO_ERROR.

Also: Even with the metadata refresh disabled (`topic.metadata.refresh.interval.ms=-1`)
the metadata information times out with the same debug message as above.

How to reproduce
================
1. Start Producer that is constantly producing messages
2. Disconnect Producer from network for at least 15 minutes
3. Re-connect the producer to the network
4. Check the message delivery reports

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.5`
 - [x] Apache Kafka version: `1.0.1`
 - [x] librdkafka client configuration:
```
topic.metadata.refresh.interval.ms=-1,
max.in.flight.requests.per.connection=1,
message.send.max.retries=1,
message.timeout.ms=0,
queue.buffering.max.messages=100000,
queue.buffering.max.kbytes=1024,
queue.buffering.max.ms=60000,
batch.num.messages=10,
socket.keepalive.enable=true,
statistics.interval.ms=10000
```
 - [x] Operating system: `Ubuntu 16.04 (x64)`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I believe this is the same issue as #1913, which is fixed on master.
Can you try reproducing on latest master? (I tried but could not)

**Comment by Oxymoron79** [comment]
I could reproduce the issue on master (commit 231f59cf84c796ce1dfe0ee1d3ec99f0ec056e72) with the same behavior as described in the issue.

Also, setting `topic.metadata.refresh.interval.ms` to 10000 leads to the topic metadata to timeout after 30 seconds and messages produced after that timeout are dropped.

Here is the log from my test, where messages 40 to 55 were dropped: 
[dev-2018-09-06T15:03:51.log.gz](https://github.com/edenhill/librdkafka/files/2357187/dev-2018-09-06T15.03.51.log.gz)

This is the application I used to reproduce the issue, perhaps it helps: 
[StreamTest.cpp.gz](https://github.com/edenhill/librdkafka/files/2357215/StreamTest.cpp.gz)

**Comment by edenhill** [comment]
There's a fix on the `unkretry` branch, can you help us verify the fix?

**Comment by edenhill** [comment]
Awesome, thanks!

**Comment by Oxymoron79** [comment]
So far I haven't found further issues.

Just one thing, that might not even be related to this issue: One Metadata request seems to get stuck in a retry loop, even after the connection has been re-established. The following messages keep showing up in the logs (repeating multiple times):
```
KafkaEventCb::event_cb: LOG: [thrd:ci.kiconnect.io:9092/bootstrap]: ci.kiconnect.io:9092/bootstrap: Retrying MetadataRequest (v2, 35 bytes, retry 0/1, prev CorrId 0) in 100ms
KafkaEventCb::event_cb: LOG: [thrd:main]: ci.kiconnect.io:9092/bootstrap: MetadataRequest failed: Local: Timed out in queue: actions Retry
```
It is always a MetadataRequest retry referring to `prev CorrId 0`.
