### ISSUE TITLE
SSL configuration enforces use of CA, even for Kafka servers that use self-signed certificates

### ISSUE THREAD

**Issue by fabdslv** [edenhill/librdkafka#1989]
Description
===========
When using librdkafka through node-rdkafka, it seems like we have no other choice than specifying the CA through 'ssl.ca.location' parameter. The problem is that, for Kafka servers/services that use a self-signed certificate, the CA might not be available or downloadable. In Node.JS TLS implementation for example, we can pass the self-signed certificate as CA, stated from this doc : https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options. It seems like it is not the case for librdkafka.

Of course, it works when using `ca-cert` generated file (the CA) instead of `cert-signed` (the self-signed certificate).

Checklist
=========

 - [x] librdkafka version (release number or git tag): `v0.11.4`
 - [x] Apache Kafka version: `2.0.0`
 - [x] librdkafka client configuration: `{"socket.timeout.ms":10000, "retries":10, "dr_msg_cb":true, "debug":"security,broker", "security.protocol":"SSL", "metadata.broker.list":"localhost:9093", "ssl.ca.location":"/dev/tools/kafka_2.12-2.0.0/cert-signed"}`
 - [x] Operating system: `MacOS 10.13.5`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
nit: v2.3.4 is not a librdkafka version number.

**Comment by fabdslv** [comment]
@edenhill you're right, I updated the version number, thanks for noticing.

**Comment by fabdslv** [comment]
@rnpridgeon sorry for not being clear enough, I'll try to be clearer this time.

From Kafka documentation (https://kafka.apache.org/documentation.html#security_ssl_signing), there is the `ca-cert` file which is the certificate of the CA vs `cert-signed` file which is the signed certificate of the Kafka server. When you use a Java client, the only thing you need to do is add the `cert-signed` file (which you can retrieve from broker URL) to your client truststore, and then use this truststore to connect (then you don't need the `ca-cert` file).

It seems like for other clients, when using 'ssl.ca.location' parameter, you can't use the signed certificate of the Kafka server (the `cert-signed` file) as it doesn't connect, but you must use the certificate of the CA (`ca-cert` file) which is not public if it is self-generated.

**Comment by MaximKojine** [comment]
![image](https://user-images.githubusercontent.com/38443875/80156780-9b399280-8579-11ea-94ef-d54a253296e7.png)

**Comment by SinghNO** [comment]
Is there any way for 2-way SSL handshake where we can use self signed certs for consumers using confluent-kafka-python with librdkafka ? Is that supported or any workaround exist to serve this use case ?

**Comment by edenhill** [comment]
@SinghNO Yes it is supported and basically what is being outlined here: 
https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

**Comment by SinghNO** [comment]
@edenhill Thanks for the quick response. Just a follow question, can we provide client's self signed certificate in place of ssl.ca.location or it's an optional parameter ?

**Comment by edenhill** [comment]
`ssl.ca.location` is used by the client to verify the broker's certificate.
`ssl.certificate.location` is the client's public key,
while `ssl.key.location` is the client's private key.

If you are using self-signed, or locally signed (your own CA), certificates you will need to set up all three of the above config settings on the client, as well as add the certificate that was used to sign the client's certificate to the brokers truststore.
