### ISSUE TITLE
Failed to initialize SASL authentication: SASL handshake

### ISSUE THREAD

**Issue by alihossein** [edenhill/librdkafka#1990]
I have a simple code to connect to `Kafka` via `Kerberos`.

‍`index.php` :
 
    <?php

    require 'vendor/autoload.php';

    use Enqueue\RdKafka\RdKafkaConnectionFactory;
    $i = 0;
    while (true) {

    // connect to Kafka broker at example.com:1000 plus custom options
    $connectionFactory = new RdKafkaConnectionFactory([ 
        'global' => [
                'bootstrap.servers' =>'kafka1.dataak.dev:9096,kafka2.dataak.dev:9096, 
     kafka3.dataak.dev:9096',
		'sasl.kerberos.keytab' => 'twitter_crawler.user.keytab',
		'sasl.kerberos.service.name'=> 'kafka',
        'security.protocol' => 'SASL_PLAINTEXT',
		'sasl.kerberos.principal'=> 'twitter_crawler@KAFKA.SECURE',
		'sasl.mechanisms'=> 'GSSAPI',
    ],
    'topic' => [
        'auto.offset.reset' => 'beginning',
    ],
    ]);

    $psrContext = $connectionFactory->createContext();

    $message = $psrContext->createMessage($i);

    $fooTopic = $psrContext->createTopic('test');

    $psrContext->createProducer()->send($fooTopic, $message);
    echo $i . " success push \n";
    $i++;
    }

The code works well but sometimes, in the middle of the run, I encounter this message:

    0%2|1536492505.195|LIBSASL|rdkafka#producer-11| 
    [thrd:sasl_plaintext://kafka2.dataak.dev:9096/bootstrap]: 
    sasl_plaintext://kafka2.dataak.dev:9096/bootstrap: GSSAPI Error: 
    Unspecified GSS failure.  Minor code may provide more information 
    (Matching credential not found)
    %3|1536492505.195|FAIL|rdkafka#producer-11| 
    [thrd:sasl_plaintext://kafka2.dataak.dev:9096/bootstrap]: 
    sasl_plaintext://kafka2.dataak.dev:9096/bootstrap: Failed to 
    initialize SASL authentication: SASL handshake failed (start (-1)): 
    SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  
    Minor code may provide more information (Matching credential not found)
    %3|1536492505.195|ERROR|rdkafka#producer-11| [thrd:sasl_plaintext://kafka2.dataak.dev:9096/bootstrap]: sasl_plaintext://kafka2.dataak.dev:9096/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)
    11%2|1536492506.480|LIBSASL|rdkafka#producer-12| [thrd:sasl_plaintext://kafka3.dataak.dev:9096/bootstrap]: sasl_plaintext://kafka3.dataak.dev:9096/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)
    %3|1536492506.480|FAIL|rdkafka#producer-12| [thrd:sasl_plaintext://kafka3.dataak.dev:9096/bootstrap]: sasl_plaintext://kafka3.dataak.dev:9096/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)
    %3|1536492506.480|ERROR|rdkafka#producer-12| [thrd:sasl_plaintext://kafka3.dataak.dev:9096/bootstrap]: sasl_plaintext://kafka3.dataak.dev:9096/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found)

[![enter image description here][1]][1]
This problem will be more when I run this ‍‍`php index.php` several times simultaneously.

Is this a natural problem?
Is there a way to solve it?

  [1]: https://i.stack.imgur.com/0wSe0.png

**Comment by rnpridgeon** [comment]
"Matching credential not found" means we were unable to obtain credentials for `sasl.kerberos.principal`. Since we are using the same credentials with each iteration I suspect this may have something to do with the fact we are creating a new librdkafka handle per iteration. 

I'm not a libsasl2 expert but I suspect there is some underlying contention issue preventing us from reading the credential cache which is not being surfaced.

If you share the producer instance across iterations do you see the same behavior?

**Comment by alihossein** [comment]
@rnpridgeon 
> If you share the producer instance across iterations do you see the same behavior?

I did not understand this line
please explain more

**Comment by rnpridgeon** [comment]
Disclaimer: I do know absolutely 0 php so I could be interpreting this wrong

It looks like you are instantiating a new producer per loop iteration: 

while (true) {
...
$psrContext->createProducer()->send($fooTopic, $message);
echo $i . " success push \n";
$i++;
}

What I'm proposing is creating a single producer instance which is shared across all loop iterations. 

$producer = $psrContext->createProducer()
while (true) {
...
$producer->send($fooTopic, $message);
echo $i . " success push \n";
$i++;
}

It's likely that the rapid instantiation of producer instances is thrashing the credentials cache in some way which causes the intermittent `Matching credential not found` error. Although I initially said this is the client principal its possible librdkafka has lost the service granting ticket as part of this supposed credential cache thrashing.

**Comment by HamoonDBA** [comment]
@rnpridgeon I think it's not normal behaviour of librdkafka because imagine we have a topic which have 6 partitions. So you generate a keytab to access to this topic. So if you want to running consumer group on specific machine (you run 6 proccess to access to each parition) you will get those error because they are running at the same time and they want to use keytab separately.
And about your latest solution, I think it Will lead to complication code because you have to manage all of process to use the same kafka connection!

**Comment by HamoonDBA** [comment]
@edenhill I saw [this issue](https://github.com/edenhill/librdkafka/issues/635) I think it's related to our problem, but I didn't understand how can I fix my problem.
