### ISSUE TITLE
Why use non-const Conf when create Producer/Consumer

### ISSUE THREAD

**Issue by XiaoyaoFan** [edenhill/librdkafka#1991]
Hi @edenhill ,

I'm wondering why does C++ API uses non-const Conf when create Producer and Consumer? Will Conf be changed inside create()?
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1846

Thank you!

**Comment by edenhill** [comment]
This is just a lapse in the API design, the configuration object will not be changed in the C++ API.
