### ISSUE TITLE
sticky assignor partition strategy

### ISSUE THREAD

**Issue by decoursin** [edenhill/librdkafka#1992]
Feature request: Add Sticky assignor strategy implementation to partition.assignment.strategy

**Comment by chris-zen** [comment]
For further context, [KIP-429](https://cwiki.apache.org/confluence/display/KAFKA/KIP-429%3A+Kafka+Consumer+Incremental+Rebalance+Protocol) is worth to read.

**Comment by damoon** [comment]
The configuration reads to me like it already is implemented.


Property | C/P | Range | Default | Importance | Description
-- | -- | -- | -- | -- | --
partition.assignment.strategy | C |   | range,roundrobin | medium | The name of one or more partition assignment strategies. The elected group leader will use a strategy supported by all members of the group to assign partitions to group members. If there is more than one eligible strategy, preference is determined by the order of this list (strategies earlier in the list have higher priority). Cooperative and non-cooperative (eager) strategies must not be mixed. Available strategies: range, roundrobin, cooperative-sticky.Type: string

Setting "partition.assignment.strategy" to "ooperative-sticky" triggers the error "Unsupported partition.assignment.strategy: cooperative-sticky".
Am i doing something wrong?

**Comment by drewtech** [comment]
Would like to be able to see if sticky works better than roundrobin but getting this same error as @damoon when setting ```'partition.assignment.strategy': 'cooperative-sticky',``` in my consumer.

**Comment by mhowlett** [comment]
sticky assignor is implemented in v1.6.0, what version are you using?

note: it's only provided in librdkafka for the incremental rebalancing case - i.e. you should update partition assignments with `incremental_assign` and `incremental_unassign`. overall, this is a big improvement over the old eager rebalancing strategies.
