### ISSUE TITLE
Memory peak during slow consume

### ISSUE THREAD

**Issue by nick-zh** [edenhill/librdkafka#1994]
Hey @edenhill

I don't think this is an issue, but i am a bit fuzzy why this happens.
So i have a consumer (php with rdkafka) that just subscribes (no consumption),
i see that my memory increases until around 2GB (each message is around 10 - 20kb),
then it suddenly drops.
My assumption is, that my local queue is getting filled (with the default 100k msg) and at some point
all the in memory messages get somehow persisted locally to the queue (hence the memory drop).
I am a bit worried, if i would start consuming very slowly, could it be possible that my memory
consumption just keeps increasing?
Thanks in advance for the help.

Cheers,
Nick

**Comment by edenhill** [comment]
The consumer memory usage is explained here: https://github.com/edenhill/librdkafka/wiki/FAQ#explain-the-consumers-memory-usage-to-me

Which explains the initial memory usage (~20KB * 100k = 2GB).
It does not, however, explain the sudden drop. If your application isn't calling consumer_poll/consume() the fetched messages will remain in the queue until a rebalance happens (in which case the internal fetchq is purged).

**Comment by nick-zh** [comment]
Thanks a lot for the quick feedback, i am just doing a consumeQueueStart but not a queue->consume...
