### ISSUE TITLE
Can not install librdkafka.dll on Windows 10, not using Visual studio

### ISSUE THREAD

**Issue by kyo00710** [edenhill/librdkafka#1996]
I download lib for php-rdkafka on windows 10. 
Then I add librdkafka.dll to System32 folder, and run : regsvr32 librdkafka.dll
But I got the error message failed to load. I don't know how to resolve it. 

Put the php_rdkafka.dll to ext/ folder of php, it will  display the error entry point popup, and display the message : 

PHP Warning:  PHP Startup: Unable to load dynamic library 'php_rdkafka.dll' (tried: ext\php_rdkafka.dll (The specified procedure could not be found.), ext\php_php_rdkafka.dll.dll (The specified module could not be found.)) in Unknown on line 0. 

So, how can resolve  this problem on windows 10?

**Comment by edenhill** [comment]
You probably need to copy all library files from the NuGet package's native folder to system32 or the application folder.

NuGet package is here:
https://www.nuget.org/packages/librdkafka.redist/0.11.6-RC2

**Comment by kyo00710** [comment]
I added all files in this folder librdkafka.redist.0.11.6-rc2\runtimes\win-x64\native into system32 folder.
Then run command regsvr32 librdkafka.dll.
Unfortunately, it tells that the lib was loaded, but the DllRegisterServer was not found.

I searched the way to fix, and found Regasm. When running command 
RegAsm.exe D:\librdkafka.redist.0.11.6-rc2\runtimes\win-x64\native\librdkafka.dll

It told me that: 

RegAsm : error RA0000 : Failed to load 'D:\librdkafka.redist.0.11.6-rc2\runtimes\win-x64\native\librdkafka.dll' because it is not a valid .NET assembly

Still not added librdkafka.dll on windows 10.

**Comment by edenhill** [comment]
I believe it is failing to load its dependencies.
Try running dependencyWalker on librdkafka.dll to see what is missing:
http://www.dependencywalker.com/

**Comment by kyo00710** [comment]
I upload all errors when opening librdkafka.dll in Dependency Walker. 

![librdkafka_miss_end](https://user-images.githubusercontent.com/5699285/45409999-e5b71580-b69a-11e8-8675-0386caa5ce78.png)
![librdkafka_miss1](https://user-images.githubusercontent.com/5699285/45410000-e64fac00-b69a-11e8-8ca1-2dd3bd6670cb.png)
![librdkafka_miss2](https://user-images.githubusercontent.com/5699285/45410001-e64fac00-b69a-11e8-9124-51d00a919c2b.png)
![librdkafka_miss3](https://user-images.githubusercontent.com/5699285/45410002-e64fac00-b69a-11e8-9ef0-1ce933c5e31b.png)
![librdkafka_miss4](https://user-images.githubusercontent.com/5699285/45410004-e6e84280-b69a-11e8-8beb-de19ca1618e1.png)
![librdkafka_miss5](https://user-images.githubusercontent.com/5699285/45410005-e6e84280-b69a-11e8-828f-90964bedb343.png)
![librdkafka_miss6](https://user-images.githubusercontent.com/5699285/45410006-e6e84280-b69a-11e8-865b-befeb2065660.png)
![librdkafka_miss7](https://user-images.githubusercontent.com/5699285/45410007-e780d900-b69a-11e8-8302-4ebdde87c405.png)

**Comment by edenhill** [comment]
@mhowlett Any ideas?

**Comment by kyo00710** [comment]
What problem with this file? Can you fix it?

**Comment by edenhill** [comment]
Can you provide a list of all the files you copied from the nuget package?

I'm also not sure you should copy these to system32, they should probably go in the application's .exe directory instead.

**Comment by kyo00710** [comment]
I copied all these files to System 32, then run regsrv32 librdkafka.dll command for registering lib kafka to windows

![Uploading native.png…]()

**Comment by edenhill** [comment]
Try putting them in the application directory instead

**Comment by kyo00710** [comment]
I tried, but it still display error: Miss Entry point. And the result is php-rdkafka.dll cannot be started

**Comment by kyo00710** [comment]
Hi, Anything new?

**Comment by mhowlett** [comment]
Regsvr32 is used to register OLE controls. librdkafka isn't an OLE control and doesn't have a `DllRegisterServer` entry point, so the error you see is what you would expect if you try to use regsvr32.

RegAsm.exe is used to register .NET Assemblies. librdkafka isn't a .NET assembly (it's a native .dll), so the error you see here is also what you'd expect if you try to use regasm.exe.

echoing what @edenhill said, it seems to be a dependency problem, or php-rdkafka unable to find librdkafka. i'm not familiar with php-rdkafka and would need to install / experiment to comment further.
