### ISSUE TITLE
rdkafka_zookeeper_example.c   if  error

### ISSUE THREAD

**Issue by cuiluguang** [edenhill/librdkafka#2002]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ
rdkafka_zookeeper_example.c:  line 543
  if (rd_kafka_conf_set(conf, "metadata.broker.list",
                              brokers, errstr, sizeof(errstr) !=
                              RD_KAFKA_CONF_OK)) {
                fprintf(stderr, "%% Failed to set brokers: %s\n", errstr);
                exit(1);
        }

Description
===========
<your issue description goes here>
Right bracket position error.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
> Right bracket position error.

Which bracket?
Please use three ticks to format your code.

**Comment by edenhill** [comment]
Oh, I see, good spotting!

**Comment by edenhill** [comment]
Fixed on master
