### ISSUE TITLE
Repeatedly create many TCP connections

### ISSUE THREAD

**Issue by sliyy** [edenhill/librdkafka#2003]
When I create every client instance, the corresponding broker list is actually the same. Do you need to call the rd_kafka_brokers_add method every time, which creates a lot of TCP connections?

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-broker-tcp-connections

**Comment by sliyy** [comment]
Can multiple client instances share a brokers connection instead of creating a connection to brokers for each client instance?

**Comment by edenhill** [comment]
No.

Try using a single instance as much as possible

Den fre 14 sep. 2018 14:03sliyy <notifications@github.com> skrev:
