### ISSUE TITLE
Building 0.11.5 on windows fails

### ISSUE THREAD

**Issue by ManfredLange** [edenhill/librdkafka#2005]
Description
===========
Building commit 993090c fails on Windows

How to reproduce
================
1. Check out https://github.com/edenhill/librdkafka.git, 
1. switch to label `v0.11.5` (= latest released version). 
1. Open terminal window, e.g. PowerShell
1. execute `build.bat` at the root of this respository
1. Result: several unresolved external symbols:

> libeay32MT.lib(cryptlib.obj) : error LNK2019: unresolved external symbol ___iob_func referenced in function _OPENSSL_stderr [C:\projects\tests\librdkaf
ka\win32\librdkafka.vcxproj]
> libeay32MT.lib(ui_openssl.obj) : error LNK2001: unresolved external symbol ___iob_func [C:\projects\tests\librdkafka\win32\librdkafka.vcxproj]
ssleay32MT.lib(t1_enc.obj) : error LNK2001: unresolved external symbol ___iob_func [C:\projects\tests\librdkafka\win32\librdkafka.vcxproj]
> libeay32MT.lib(txt_db.obj) : error LNK2001: unresolved external symbol ___iob_func [C:\projects\tests\librdkafka\win32\librdkafka.vcxproj]

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.5`
 - [ ] Apache Kafka version: `n/a`
 - [ ] librdkafka client configuration: `n/a`
 - [x] Operating system: `Windows 10 Pro, 64 bit, version 10.0.17134 Build 17134`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka: n/a
 - [ ] Provide broker log excerpts: n/a
 - [ ] Critical issue: n/a

Environment:
- msbuild engine 14.0.25420.1
- nuget 4.6.2.5055
- OpenSSL version 1.0.2p (April 2018), 32 bit, installed at `C:\OpenSSL-Win32` (default install directory)

Note that I want to build librdkafka as it shows the same issues when trying to execute `npm install node-rdkafka@2.3.4`. Please don't get hung up on the npm install bit at this stage. Once I resolved the build issue with just librdkafka and without the npm package stuff in the picture, I think it will help to resolve the npm install issues as well. My hunch is, that perhaps its a question of either placing OpenSSL in the right place or picking the correct version or perhaps an additional environment setting required to set up directories that contain the OpenSSL libraries.

Any suggestion for how to further diagnose/resolve this would be very much appreciated. Also, I'm happy to provide more details or run additional experiments to diagnose the problem. Thank you!

**Comment by edenhill** [comment]
OpenSSL is built with msvcr 120, while modern toolchains are typically on 140.
This only seems to be a problem with linking OpenSSL statically (.lib), so try linking it dynamically instead by removing the "static" suffix from these lines:
```
win32/librdkafka.vcxproj:16:    <LibraryPath>$(VC_LibraryPath_x86);$(WindowsSDK_LibraryPath_x86);C:\OpenSSL-Win32\lib\VC\static</LibraryPath>
win32/librdkafka.vcxproj:20:    <LibraryPath>$(VC_LibraryPath_x64);$(WindowsSDK_LibraryPath_x64);C:\OpenSSL-Win64\lib\VC\static</LibraryPath>
```

**Comment by ManfredLange** [comment]
I tried this and it does change the result. It is now able to link `librdkafka.lib` successfully (ie building librdkafka.vcxproj build successfully) and then continues to compile `librdkafkacpp.vcxproj` which fails in the compile step. The compile error is in file `rdkafka_consumer_example.cpp`, line 48. It cannot find the include file `atltime.h`.

Do you happen to have suggestions for how to resolve this?

**Comment by ManfredLange** [comment]
Alright, I have been able to successfully compile this on Windows 10 by changing the path environment variable to point to the Visual Studio / VC++ 2010 version of the toolset (version 12.0). Trying to use a later version such as Visual Studio 2013 or toolset version 14.0 would require changes in this repository as far as I understand it.

Here are steps to compile tag `v0.11.5` of this repo that worked in my Windows 10 environment:
1. Open a terminal, e.g. PowerShell
2. Execute `msbuild` and check the version is prints out. If the version is something like 12.0.x you should be fine. Go to step 4. **Important:** If the version is not something like `12.0.x.y` (with x and y being numbers), it is highly unlikely that it will build.
3. If it cannot find the command "msbuild" add the path to the appropriate folder to your environment variable named "Path". In my case the correct path was `C:\Program Files (x86)\MSBuild\12.0\Bin`. Go back to step 2.
4. Install OpenSSL version 1.0.2 from [here](https://slproweb.com/products/Win32OpenSSL.html). Pick the version that says "[Win32_OpenSSL_v1.0.2p.exe](https://slproweb.com/download/Win32OpenSSL-1_0_2p.exe)". When installing accept all defaults.
5. In your terminal window execute `nuget` and check the version number. Versions 4.6.1, 4.7.x or later should be fine. If that is the case go to step 7
6. Install nuget, then add the path the location of "nuget.exe" to your "Path" environment variable. Go to step 5.
7. You should now be ready to build. In your terminal window navigate to the root of the checked-out source code of this repository
8. Execute `./build.bat`

Note that with these steps I was able to build (compile and link) this repo successfully and without modifications. I used tag `v0.11.5` from this repository.

**Comment by edenhill** [comment]
Thanks for providing the solution!
