### ISSUE TITLE
Producer flush never completes leading to non delivery of messages.

### ISSUE THREAD

**Issue by Sigmundsdottir** [edenhill/librdkafka#2006]
Description
===========

Calling producer flush never completes and leads to message timeout.

Points to note .

1. Application Calls poll at regular interval of times. Poll is called after every 5 or 10 seconds and flush is called after every 60-90 seconds.
2. 6 out of 10 times, when application calls the flush with timeout of 1 second, ERR__TIMED_OUT is being returned( normal and expected ), hence application retries infinitely until all the messages have been delivered to broker and dr_cb is called for all messages.
3. My logic requires to flush all the messages after regular interval of times, hence application retries flush until outq_len() function returns 0 or ERR_NO_ERROR is returned. 
4. But sometimes it happens that producer flush never completes even after 5 minutes( default message.timeout.ms ) and dr_cb is called with message timeout error code.
5. Application code cannot move forward until flush has been completed.
6. Do note that it does not happen every time the application calls flush but only on average of 60% of the time.
7. Repeating the same test over and over again, I have noticed that - 
    a.) It happens when the frequency of message is around 10K to 50K every 10 millisecond.
    b.) It does not happen when I increase the frequency along with time to 100K every 1 second.
    c.) Continuous message stream at very short time intervals was the common observation during the tests. 

Additional info -

1. Application is composed of 13 Consumers and 13 Producers. 
2. Each pair of consumer-producer runs in single thread.
3. Thread consumes messages with the help of consumer and apply some logic and produce output using producer.
4. For each message there can be more than 1 outputs.
5. Thread stops consuming after particular message count and calls the poll of the producer on regular intervals. After some time thread calls the flush and that is where it gets stuck because flush never completes.
6. Each consumer is consuming from it's own single topic with only single partition. Producer is producing messages to its own separate topic with single partition.
7. There is only 1 Apache kafka broker is running.
8. Complete setups runs on same machine i.e the application is running where Kafka broker is running. 
9. We have tried replicating the issue on other local machines as well as on cloud -DigitalOcean and AWS, it was easily replicated on both.

How to reproduce
================

Unfortunately, it does not happen every time I run the tests. But it does happen majority of the time.

We bombard the application with 10k to 50K messages every 10 milliseconds and the flush fails 60% of the time.

But when we increase the time to say 1 second along with number of messages to 100K, flush completes successfully. 

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.4`
 - [x] Apache Kafka version: `2.11-1.1.0`
 - [x] librdkafka client configuration: 
`metadata.broker.list=127.0.0.1:9092
message.max.bytes=10000
message.copy.max.bytes=65535
receive.message.max.bytes=100000000
max.in.flight.requests.per.connection=1000000
metadata.request.timeout.ms=60000
topic.metadata.refresh.interval.ms=300000
metadata.max.age.ms=300000
topic.metadata.refresh.fast.interval.ms=250
topic.metadata.refresh.sparse=true
debug=msg
socket.timeout.ms=300000
socket.blocking.max.ms=5000
socket.send.buffer.bytes=100000000
socket.receive.buffer.bytes=100000000
socket.keepalive.enable=false
socket.nagle.disable=false
socket.max.fails=1
broker.address.ttl=1000
broker.address.family=any
reconnect.backoff.jitter.ms=500
statistics.interval.ms=0
enabled_events=0
log.queue=false
log.thread.name=true
log.connection.close=true
internal.termination.signal=0
api.version.request=true
api.version.request.timeout.ms=10000
api.version.fallback.ms=1200000
broker.version.fallback=0.9.0
security.protocol=plaintext
partition.assignment.strategy=roundrobin
session.timeout.ms=30000
heartbeat.interval.ms=1000
group.protocol.type=consumer
coordinator.query.interval.ms=600000

auto.commit.interval.ms=5000
enable.auto.offset.store=true
queued.min.messages=100000
queued.max.messages.kbytes=1048576
fetch.wait.max.ms=100
fetch.message.max.bytes=1048576
fetch.max.bytes=52428800
fetch.min.bytes=1
fetch.error.backoff.ms=500
offset.store.method=broker
enable.partition.eof=true
check.crcs=false

queue.buffering.max.messages=1000000
queue.buffering.max.kbytes=1048576
queue.buffering.max.ms=100
message.send.max.retries=2
retry.backoff.ms=200
queue.buffering.backpressure.threshold=1
compression.codec=none
batch.num.messages=10000
delivery.report.only.error=false

auto.commit.interval.ms=5000
auto.offset.reset=largest
offset.store.path=.
offset.store.sync.interval.ms=-1
offset.store.method=broker
consume.callback.max.messages=0

request.timeout.ms=10000
message.timeout.ms=300000
queuing.strategy=fifo
produce.offset.report=true
partitioner=consistent_random
compression.codec=inherit`

 - [x] Operating system: 'CentOS Linux release 7.5.1804 with Linux kernel 3.10.0-862.11.6.el7.x86_64`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
'%7|1536938034.895|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: No more space in current MessageSet (90 message(s), 9969 bytes)
%7|1536938034.895|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: Produce MessageSet with 90 message(s) (9897 bytes, ApiVersion 3,     MsgVersion 2) 
%7|1536938034.895|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: No more space in current MessageSet (90 message(s), 9969 bytes)
%7|1536938034.895|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: No more space in current MessageSet (90 message(s), 9969 bytes)
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: Produce MessageSet with 90 message(s) (9897 bytes, ApiVersion 3,     MsgVersion 2) 
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: No more space in current MessageSet (90 message(s), 9969 bytes)
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: Produce MessageSet with 90 message(s) (9897 bytes, ApiVersion 3,     MsgVersion 2) 
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: No more space in current MessageSet (90 message(s), 9969 bytes)
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: Produce MessageSet with 90 message(s) (9897 bytes, ApiVersion 3,     MsgVersion 2) 
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: No more space in current MessageSet (90 message(s), 9969 bytes)
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: Produce MessageSet with 90 message(s) (9897 bytes, ApiVersion 3,     MsgVersion 2) 
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: No more space in current MessageSet (90 message(s), 9969 bytes)
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: Produce MessageSet with 90 message(s) (9897 bytes, ApiVersion 3,     MsgVersion 2) 
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: No more space in current MessageSet (90 message(s), 9969 bytes)
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: Produce MessageSet with 90 message(s) (9897 bytes, ApiVersion 3,     MsgVersion 2) 
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: No more space in current MessageSet (90 message(s), 9969 bytes)
%7|1536938034.913|PRODUCE|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: Produce MessageSet with 90 message(s) (9897 bytes, ApiVersion 3,     MsgVersion 2) 
%7|1536938034.929|MSGSET|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: MessageSet with 90 message(s) delivered
%7|1536938034.929|MSGSET|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: MessageSet with 90 message(s) delivered
%7|1536938034.930|MSGSET|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: MessageSet with 90 message(s) delivered
%7|1536938034.930|MSGSET|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: MessageSet with 90 message(s) delivered
%7|1536938034.930|MSGSET|xnr-producer#producer-11| [thrd:127.0.0.1:9092/bootstrap]: 127.0.0.1:9092/0: xnr-OUTGOING [0]: MessageSet with 90 message(s) delivered'

 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Great report!

Can you try reproducing this on master or v0.11.6-RC2, there's been fixes to messages  getting stuck in queues since 0.11.4

**Comment by Sigmundsdottir** [comment]
Thank you for replying. 

I will test again with v0.11.6-RC2 and update the thread.

**Comment by iranjeet-bittmax** [comment]
I have tested the scenario on two branches. Following are the observations : 

Branch - 0.11.5 ( Stable release ) ( Problem Solved )
a.) Issue magically disappear and producer flushing is running flawlessly. All messages are getting flushed and none of the message was returned back to dr_cb with timeout error code. This solves my problem.

Branch- Master (  Commit number - b677b4517 )  ( Problem Solved ) 
a. ) This branch also contains the fix and producer flush is working perfectly fine.
b. ) However, I faced a linking issue with my application when I jumped to this branch. 
      i.) Issue : Undefined reference to "rd_kafka_controllerid".
     ii.) I had a look at the code and solved this by linking both C++ and C .so with my application.


Question : 

As Stable release 0.11.5 solves my problem, can I migrate to newer version? My application is running in production and I am not sure if master or release candidate would be a good decision?

Can you please advice?

This ticked can be closed. 

Your help to the community is highly appreciated.

**Comment by Sigmundsdottir** [comment]
I have tested the scenario on two branches. Following are the observations :

Branch - 0.11.5 ( Stable release ) ( Problem Solved )
a.) Issue magically disappear and producer flushing is running flawlessly. All messages are getting flushed and none of the message was returned back to dr_cb with timeout error code. This solves my problem.

Branch- Master ( Commit number - b677b45 ) ( Problem Solved )
a. ) This branch also contains the fix and producer flush is working perfectly fine.
b. ) However, I faced a linking issue with my application when I jumped to this branch.
i.) Issue : Undefined reference to "rd_kafka_controllerid".
ii.) I had a look at the code and solved this by linking both C++ and C .so with my application.

Question :

As Stable release 0.11.5 solves my problem, can I migrate to newer version? My application is running in production and I am not sure if master or release candidate would be a good decision?

Can you please advice?

This ticked can be closed.

Your help to the community is highly appreciated.
