### ISSUE TITLE
CentOS 7 compilation issues

### ISSUE THREAD

**Issue by LesterS4t1qbit** [edenhill/librdkafka#2008]
Description
===========
Librdkafka compiles and installs on CentOS 7, but the SO file errors on undefined references to OpenSSL functions when trying to link against librdkafka.so

```
[edd7e346942b] root@/usr/lib/: gcc librdkafka.so
/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
librdkafka.so: undefined reference to `OpenSSL_version_num'
librdkafka.so: undefined reference to `OPENSSL_sk_pop_free'
librdkafka.so: undefined reference to `OPENSSL_init_ssl'
librdkafka.so: undefined reference to `OpenSSL_version'
librdkafka.so: undefined reference to `OPENSSL_init_crypto'
librdkafka.so: undefined reference to `TLS_client_method'
librdkafka.so: undefined reference to `SSL_CTX_set_options'
collect2: error: ld returned 1 exit status

[edd7e346942b] root@/usr/lib/: ldd librdkafka.so
        linux-vdso.so.1 =>  (0x00007ffd6db8b000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007fc52f655000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007fc52f1f4000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fc52eef2000)
        libz.so.1 => /usr/local/lib/libz.so.1 (0x00007fc52ecd4000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fc52ead0000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc52e8b4000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fc52e6ac000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fc52e2df000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc52fbc3000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fc52e092000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fc52ddaa000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fc52dba6000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fc52d973000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fc52d765000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fc52d561000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fc52d348000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fc52d121000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fc52cebf000)
```

How to reproduce
================
This was reproduced on top of a CentOS 7 docker image with tag `centos:7.3.1611` with gcc 5.3.1 through devtoolset-4
1. Check out the github repo @ b677b451700a3548e37298fa070016b5126b71c8
2. Install dependencies as listed under the wiki for CentOS 6
    cyrus-sasl-lib-2.1.23-15.el6_6.2.x86_64
    openssl-1.0.1e-57.el6.x86_64
3. Run ./configure and then make in the repo
4. Make will pass the librdkafka++ integrity checks, but fail on running
```
make -C examples
make[1]: Entering directory `/root/librdkafka/examples'
gcc -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align  -I../src rdkafka_example.c -o rdkafka_example  \
        ../src/librdkafka.a -lssl -lcrypto   -lm -lcrypto   -lz   -ldl -lpthread -lrt
../src/librdkafka.a(rdkafka_transport.o): In function `rd_kafka_transport_ssl_init':
/root/librdkafka/src/rdkafka_transport.c:503: undefined reference to `OPENSSL_init_ssl'
/root/librdkafka/src/rdkafka_transport.c:504: undefined reference to `OPENSSL_init_ssl'
../src/librdkafka.a(rdkafka_transport.o): In function `rd_kafka_transport_ssl_ctx_init':
/root/librdkafka/src/rdkafka_transport.c:848: undefined reference to `TLS_client_method'
/root/librdkafka/src/rdkafka_transport.c:857: undefined reference to `SSL_CTX_set_options'
../src/librdkafka.a(rdkafka_transport.o): In function `sk_X509_pop_free':
/usr/local/include/openssl/x509.h:97: undefined reference to `OPENSSL_sk_pop_free'
../src/librdkafka.a(rdkafka_transport.o): In function `rd_kafka_transport_ssl_ctx_init':
/root/librdkafka/src/rdkafka_transport.c:835: undefined reference to `OpenSSL_version_num'
/root/librdkafka/src/rdkafka_transport.c:835: undefined reference to `OpenSSL_version'
../src/librdkafka.a(rdkafka_transport.o): In function `sk_X509_pop_free':
/usr/local/include/openssl/x509.h:97: undefined reference to `OPENSSL_sk_pop_free'
../src/librdkafka.a(rdkafka_transport.o): In function `rd_kafka_transport_ssl_init':
/root/librdkafka/src/rdkafka_transport.c:505: undefined reference to `OPENSSL_init_crypto'
collect2: error: ld returned 1 exit status
make[1]: *** [rdkafka_example] Error 1
make[1]: Leaving directory `/root/librdkafka/examples'
make: *** [examples] Error 2
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `b677b451700a3548e37298fa070016b5126b71c8`
 - [x] Apache Kafka version: `2.0.0`
 - [x] librdkafka client configuration: `didn't get far enough to set one up`
 - [x] Operating system: `CENTOS 7 (docker image centos:7.3.1611)`
 - [X] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts `don't get far enough to have any`
 - [x] Critical issue

**Comment by edenhill** [comment]
librdkafka requires OpenSSL >= 1.0.2.
1.0.1 is out of support and should not be used.

**Comment by LesterS4t1qbit** [comment]
Oh, alright. Thanks.

**Comment by daihanhle** [comment]
Hi,
I have same error with openssl version 1.1.1

../src/librdkafka.a(rdkafka_ssl.o): In function rd_kafka_ssl_set_certs': /home/daihanh/kafkaLib/librdkafka-1.9.3-RC2/src/rdkafka_ssl.c:1325: undefined reference to X509_OBJECT_get0_X509'
../src/librdkafka.a(rdkafka_ssl.o): In function sk_X509_NAME_push': /usr/local/include/openssl/x509.h:77: undefined reference to OPENSSL_sk_push'
../src/librdkafka.a(rdkafka_ssl.o): In function sk_X509_OBJECT_num': /usr/local/include/openssl/x509_vfy.h:58: undefined reference to OPENSSL_sk_num'
../src/librdkafka.a(rdkafka_ssl.o): In function sk_X509_NAME_free': /usr/local/include/openssl/x509.h:77: undefined reference to OPENSSL_sk_free'
/usr/local/include/openssl/x509.h:77: undefined reference to OPENSSL_sk_free' ../src/librdkafka.a(rdkafka_ssl.o): In function sk_X509_pop_free':
/usr/local/include/openssl/x509.h:99: undefined reference to OPENSSL_sk_pop_free' ../src/librdkafka.a(rdkafka_ssl.o): In function rd_kafka_ssl_ctx_init':
/home/daihanh/kafkaLib/librdkafka-1.9.3-RC2/src/rdkafka_ssl.c:1522: undefined reference to TLS_client_method' /home/daihanh/kafkaLib/librdkafka-1.9.3-RC2/src/rdkafka_ssl.c:1533: undefined reference to SSL_CTX_set_options'
/home/daihanh/kafkaLib/librdkafka-1.9.3-RC2/src/rdkafka_ssl.c:1497: undefined reference to OpenSSL_version_num' /home/daihanh/kafkaLib/librdkafka-1.9.3-RC2/src/rdkafka_ssl.c:1497: undefined reference to OpenSSL_version'
collect2: error: ld returned 1 exit status
make[1]: *** [rdkafka_example] Error 1
make[1]: Leaving directory `/home/daihanh/kafkaLib/librdkafka-1.9.3-RC2/examples'
make: *** [examples] Error 2
[localhost]$ openssl version
OpenSSL 1.1.1k 25 Mar 2021
[localhost]$
