### ISSUE TITLE
Add auto.commit.interval.messages

### ISSUE THREAD

**Issue by DEvil0000** [edenhill/librdkafka#201]
i am using offset saved in files.

1) there is a auto commit config value based on ms "auto.commit.interval.ms" but i would like a have a second parameter to control auto commit on a message level.
something like auto commit after 5 messages or commit on every message.

2) there is a second ms based offset config value "offset.store.sync.interval.ms" is there a need to have two config values describing the same thing? or what is the difference? if there is a difference i might also want to control this additionally on a per message level.

edit:
ms = 0 should be immediate
= -1 could be never

**Comment by edenhill** [comment]
1) `auto.commit.interval.ms` is just used internally - see 2) below, it doesn't control at what message-granularity offsets are stored.
   Message offsets are stored at this granularity:
 -  the non batch consumers (`rd_kafka_consume[_queue](), rd_kafka_consume_callback..()`):   offset is stored for the message returned/passed.
 - the batch consumers: offset of the last message in the batch is stored.

2) the phrasing is a bit messed up (partly because these config settings were copied from the Scala clients):
  - `..._offset_store()` "saves" the last offset in **memory**
  - property `auto.commit.interval.ms` controls how often the last stored offset in **memory** is written to storage (file, broker).
  - property `offset.store.sync.interval.ms` controls how often file-based storages call fsync() to force that the last disk write was actually written to disk (not just disk cache).

**Comment by DEvil0000** [comment]
thanks this makes the purpose of the values more clear to me.
but i think you did not get my concern or i don't get the intention and meaning - i will try it again with some examples and i will tell you how i understand it.

i understood:
1) if the consumer consumes a message (or a bunch of messages) the new offset is stored in memory.
2) there are two ways to save the offset from memory to more permament place (file/broker)
 2.1) `..._offset_store()` manually saved by function call
 2.2) `auto.commit.interval.ms` auto saved based on ms timer timeout
3) `offset.store.sync.interval.ms` is pretty clear now

i think:
1) if you store the offset only in memory you may process information twice or may hang on a message.
example:
something unexpected happens (e.g. segfault) and your process restarts. your last offset was not saved to a persistant place because it is only in memory. you may end up
a) consuming the same x messages again you have processed before (process it twice)
b) you fail again on the same message and will never come over it (loop process it)
2) 1a) may be fine for me (depends on kafka usage and app goal) and 1b) might me my own impl. issue.. but i would like to control auto commits on a message level or better on both levels. to be more precise i would like to commit the offset after each consumed message.
2.1) yes i can use this to do the thing like i want but getting auto commit more usefull might help others..
2.2) 
using a small auto commit value (in ms) is dangerous because my RTT in the network path might be longer than this and might varry.
using a large auto commit value may leed to the loose of the correct offset position on machine/process failure.
my solution for this would be a `auto.commit.interval.messages` to get better control over auto saving. like "save after every message", "save after 5 messages" and so on...
of course you need both values (ms & count) just consider different settings for the config values and different message traffic on the topic.
3) i should not need to care about this. that is os & fs impl detail. maybe on shutdown - right?

but i think the most common usecase would be: save the offset to a more permanent place after every received/consumed message.

do you understand my usecase and why i think there is a need for this now?
do i get something wrong? have i missed something?

**Comment by edenhill** [comment]
Thanks for clarifying, it is perfectly clear now, and your suggestion with `auto.commit.interval.messages` is good. I'll have it work in conjunction with `auto.commit.interval.ms`: it will commit the last stored offset for whichever threshold comes first, the `.ms` or `.messages`.

**Comment by edenhill** [comment]
Is there still demand for this?

**Comment by DEvil0000** [comment]
I would still like to have this but it is not very important to me anymore.
This would help to build a "process exactly once" consumer if you can additionally configure if offset commit should be blocking or not. You should also be able to disable one of both completely.

**Comment by edenhill** [comment]
Exactly Once Semantics is currently discussed in [KIP-98](https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging)

I will close this issue since an application side workaround is easy to do.

I
