### ISSUE TITLE
Problems in compiling rdkafka_example.cpp

### ISSUE THREAD

**Issue by marcoippolito** [edenhill/librdkafka#2011]
[librdkafkaInstallConfig.txt](https://github.com/edenhill/librdkafka/files/2393979/librdkafkaInstallConfig.txt)
Hi,

in my Ubuntu 18.04

    marco@PC:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 18.04.1 LTS
    Release:        18.04
    Codename:       bionic

after git-cloning the latest librdkafka : 
   librdkafka version: according to the make phase output: v0.11.6-RC2-6-gb677b4
   apache-kafka release: 2.0.0 release

    marco@PC:~$ git clone https://github.com/edenhill/librdkafka.git
    Cloning into 'librdkafka'...
    remote: Counting objects: 16577, done.
    remote: Compressing objects: 100% (5/5), done.
    remote: Total 16577 (delta 1), reused 1 (delta 0), pack-reused 16572
    Receiving objects: 100% (16577/16577), 10.14 MiB | 7.46 MiB/s, done.
    Resolving deltas: 100% (12558/12558), done.

    marco@PC:~$ cd librdkafka/
    marco@PC:~/librdkafka$
    marco@PC:~/librdkafka$ ./configure
  

    Configuration summary:
    prefix                   /usr/local
    ARCH                     x86_64
    CPU                      generic
    GEN_PKG_CONFIG           y
    ENABLE_DEVEL             n
    ENABLE_VALGRIND          n
    ENABLE_REFCNT_DEBUG      n
    ENABLE_SHAREDPTR_DEBUG   n
    ENABLE_LZ4_EXT           y
    ENABLE_SSL               y
    ENABLE_SASL              y
    MKL_APP_NAME             librdkafka
    MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
    MKL_DISTRO               Ubuntu
    SOLIB_EXT                .so
    CC                       gcc
    CXX                      g++
    LD                       ld
    NM                       nm
    OBJDUMP                  objdump
    STRIP                    strip
    CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
    PKG_CONFIG               pkg-config
    INSTALL                  install
    LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
    LDFLAG_LINKERSCRIPT      -Wl,--version-script=
    RDKAFKA_VERSION_STR      0.11.6
    MKL_APP_VERSION          0.11.6
    LIBS                     -lsasl2 -lssl -llz4 -lm -lcrypto -lz -ldl -lpthread -lrt
    CFLAGS
    CXXFLAGS                 -Wno-non-virtual-dtor
    SYMDUMPER                $(NM) -D
    exec_prefix              /usr/local
    bindir                   /usr/local/bin
    sbindir                  /usr/local/sbin
    libexecdir               /usr/local/libexec
    datadir                  /usr/local/share
    sysconfdir               /usr/local/etc
    sharedstatedir           /usr/local/com
    localstatedir            /usr/local/var
    libdir                   /usr/local/lib
    includedir               /usr/local/include
    infodir                  /usr/local/info
    mandir                   /usr/local/man

    /home/marco/librdkafka/make

    Updating
    Checking  integrity
    CONFIGURATION.md               OK
    examples/rdkafka_example       OK
    examples/rdkafka_performance   OK
    examples/rdkafka_example_cpp   OK
    Checking librdkafka integrity
    librdkafka.so.1                OK
    librdkafka.a                   OK
    Symbol visibility              OK
    Checking librdkafka++ integrity
    librdkafka++.so.1              OK
    librdkafka++.a                 OK

After the installation phase:

    marco@PC:~/librdkafka$ sudo make install
    [sudo] password for marco:
    make[1]: Entering directory '/home/marco/librdkafka/src'
    Install librdkafka to /usr/local
    install -d $DESTDIR/usr/local/include/librdkafka ; \
    install -d $DESTDIR/usr/local/lib ; \
    install rdkafka.h $DESTDIR/usr/local/include/librdkafka ; \
    install librdkafka.a $DESTDIR/usr/local/lib ; \
    install librdkafka.so.1 $DESTDIR/usr/local/lib ; \
    [ -f "rdkafka.pc" ] && ( \
            install -d $DESTDIR/usr/local/lib/pkgconfig ; \
            install -m 0644 rdkafka.pc $DESTDIR/usr/local/lib/pkgconfig \
     ) ; \
    [ -f "rdkafka-static.pc" ] && ( \
            install -d $DESTDIR/usr/local/lib/pkgconfig ; \
            install -m 0644 rdkafka-static.pc $DESTDIR/usr/local/lib/pkgconfig \
    ) ; \
    (cd $DESTDIR/usr/local/lib && ln -sf librdkafka.so.1 librdkafka.so)
    make[1]: Leaving directory '/home/marco/librdkafka/src'
    make[1]: Entering directory '/home/marco/librdkafka/src-cpp'
    Install librdkafka++ to /usr/local
    install -d $DESTDIR/usr/local/include/librdkafka ; \
    install -d $DESTDIR/usr/local/lib ; \
    install rdkafkacpp.h $DESTDIR/usr/local/include/librdkafka ; \
    install librdkafka++.a $DESTDIR/usr/local/lib ; \
    install librdkafka++.so.1 $DESTDIR/usr/local/lib ; \
    [ -f "rdkafka++.pc" ] && ( \
            install -d $DESTDIR/usr/local/lib/pkgconfig ; \
            install -m 0644 rdkafka++.pc $DESTDIR/usr/local/lib/pkgconfig \
     ) ; \
    [ -f "rdkafka++-static.pc" ] && ( \
            install -d $DESTDIR/usr/local/lib/pkgconfig ; \
            install -m 0644 rdkafka++-static.pc $DESTDIR/usr/local/lib/pkgconfig \
    ) ; \
    (cd $DESTDIR/usr/local/lib && ln -sf librdkafka++.so.1 librdkafka++.so)
    make[1]: Leaving directory '/home/marco/librdkafka/src-cpp'

  I attached a txt file containing the output of all three building phases.

    marco@PC:/usr/local/include/librdkafka$ ls -lah
    total 264K
    drwxr-xr-x 2 root root 4.0K Sep 18 19:02 .
    drwxr-xr-x 4 root root 4.0K Sep 18 19:02 ..
    -rwxr-xr-x 1 root root  73K Sep 18 19:02 rdkafkacpp.h
    -rwxr-xr-x 1 root root 178K Sep 18 19:02 rdkafka.h

    marco@PC:/usr/local/lib$ ls -lah
    total 95M
    drwxr-xr-x  5 root root  4.0K Sep 18 19:02 .
    drwxr-xr-x 13 root root  4.0K Sep  5 08:29 ..
    lrwxrwxrwx  1 root root    21 May  7 12:10 libcaf_core.so -> libcaf_core.so.0.15.7
    -rw-r--r--  1 root root   38M Jul 26 16:08 libcaf_core.so.0.15.7
    lrwxrwxrwx  1 root root    19 May  7 12:10 libcaf_io.so -> libcaf_io.so.0.15.7
    -rw-r--r--  1 root root   34M Jul 26 16:08 libcaf_io.so.0.15.7
    -rwxr-xr-x  1 root root   13M Sep 18 19:02 librdkafka.a
    -rwxr-xr-x  1 root root  3.7M Sep 18 19:02 librdkafka++.a
    lrwxrwxrwx  1 root root    15 Sep 18 19:02 librdkafka.so -> librdkafka.so.1
    lrwxrwxrwx  1 root root    17 Sep 18 19:02 librdkafka++.so -> librdkafka++.so.1
    -rwxr-xr-x  1 root root  6.2M Sep 18 19:02 librdkafka.so.1
    -rwxr-xr-x  1 root root  1.4M Sep 18 19:02 librdkafka++.so.1
    drwxr-xr-x  2 root root  4.0K Sep 18 19:02 pkgconfig
    drwxrwsr-x  4 root staff 4.0K Aug 31 10:17 python2.7
    drwxrwsr-x  3 root staff 4.0K Aug 31 10:11 python3.6
    marco@PC:/usr/local/lib$

In my .bashrc file I included these two lines:

    export PATH=/usr/local/include/librdkafka:$PATH
    export PATH=/usr/local/lib:$PATH

When compiling : 

    marco@PC:~/librdkafka/examples$ gcc -v
    gcc version 8.0.1 20180414 (experimental) [trunk revision 259383] (Ubuntu 8-20180414-1ubuntu2)

     marco@PC:~/librdkafka/examples$ g++ -std=c++17 rdkafka_example.cpp -ordkafka_example   
    -lrdkafka -lz -lpthread -lrt
    rdkafka_example.cpp:54:10: fatal error: rdkafkacpp.h: No such file or directory
     #include "rdkafkacpp.h"
              ^~~~~~~~~~~~~~
    compilation terminated.

And when I compile specifying the paths of the include files and of the library:

    marco@PC:~/librdkafka/examples$ g++ -std=c++17 rdkafka_example.cpp -ordkafka_example -I 
    /usr/local/include/librdkafka -L /usr/local/lib -lrdkafka -lz -lpthread -lrt

    /tmp/ccS41ooP.o: In function `metadata_print(std::__cxx11::basic_string<char, std::char_traits<char>, 
    std::allocator<char> > const&, RdKafka::Metadata const*)':
    rdkafka_example.cpp:(.text+0x46b): undefined reference to `RdKafka::err2str[abi:cxx11]  
    (RdKafka::ErrorCode)'
    rdkafka_example.cpp:(.text+0x855): undefined reference to `RdKafka::err2str[abi:cxx11]  
    (RdKafka::ErrorCode)'
    /tmp/ccS41ooP.o: In function `main':
    rdkafka_example.cpp:(.text+0xcd7): undefined reference to `RdKafka::Topic::PARTITION_UA'
    rdkafka_example.cpp:(.text+0xce4): undefined reference to `RdKafka::Topic::OFFSET_BEGINNING'
    rdkafka_example.cpp:(.text+0xd14): undefined reference to   
    `RdKafka::Conf::create(RdKafka::Conf::ConfType)'
    rdkafka_example.cpp:(.text+0xd25): undefined reference to  
    `RdKafka::Conf::create(RdKafka::Conf::ConfType)'
    rdkafka_example.cpp:(.text+0x1016): undefined reference to `RdKafka::Topic::OFFSET_END'
    rdkafka_example.cpp:(.text+0x1043): undefined reference to `RdKafka::Topic::OFFSET_BEGINNING'
    rdkafka_example.cpp:(.text+0x1070): undefined reference to `RdKafka::Topic::OFFSET_STORED'
    rdkafka_example.cpp:(.text+0x15dd): undefined reference to `RdKafka::get_debug_contexts[abi:cxx11]()'
    rdkafka_example.cpp:(.text+0x1603): undefined reference to `RdKafka::version()'
    rdkafka_example.cpp:(.text+0x1612): undefined reference to `RdKafka::version_str[abi:cxx11]()'
    rdkafka_example.cpp:(.text+0x1afe): undefined reference to `RdKafka::Producer::create(RdKafka::Conf*,   
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
    rdkafka_example.cpp:(.text+0x1c41): undefined reference to `RdKafka::Topic::create(RdKafka::Handle*,  
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RdKafka::Conf*,  
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
    rdkafka_example.cpp:(.text+0x1def): undefined reference to `RdKafka::err2str[abi:cxx11]  
    (RdKafka::ErrorCode)'
    rdkafka_example.cpp:(.text+0x20e3): undefined reference to   
    `RdKafka::Consumer::create(RdKafka::Conf*, std::__cxx11::basic_string<char, std::char_traits<char>,  
    std::allocator<char> >&)'
    rdkafka_example.cpp:(.text+0x2226): undefined reference to `RdKafka::Topic::create(RdKafka::Handle*, s  
    td::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RdKafka::Conf*,  
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
    rdkafka_example.cpp:(.text+0x22e7): undefined reference to `RdKafka::err2str[abi:cxx11]   
    (RdKafka::ErrorCode)'
    rdkafka_example.cpp:(.text+0x2550): undefined reference to `RdKafka::Producer::create(RdKafka::Conf*, 
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
    rdkafka_example.cpp:(.text+0x26b8): undefined reference to `RdKafka::Topic::create(RdKafka::Handle*, 
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RdKafka::Conf*, 
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
    rdkafka_example.cpp:(.text+0x27c7): undefined reference to `RdKafka::err2str[abi:cxx11]
    (RdKafka::ErrorCode)'
    rdkafka_example.cpp:(.text+0x2858): undefined reference to `RdKafka::wait_destroyed(int)'
    /tmp/ccS41ooP.o: In function `ExampleEventCb::event_cb(RdKafka::Event&)':
    rdkafka_example.cpp
     undefined reference to `RdKafka::err2str[abi:cxx11](RdKafka::ErrorCode)' 
    rdkafka_example.cpp:  
    collect2: error: ld returned 1 exit status

How to solve the problem?
Looking forward to your kind hints and help.
Marco

**Comment by edenhill** [comment]
>  marco@PC:~/librdkafka/examples$ g++ -std=c++17 rdkafka_example.cpp -ordkafka_example   
-lrdkafka -lz -lpthread -lrt

Why are you not using the makefile in examples?
`make -C examples` will build the examples for

**Comment by marcoippolito** [comment]
With make -X examples all examples are indeed built.

But how to compile a simple plain file?

    marco@PC:~/librdkafka/examples$ cat plain.cpp
    #include "rdkafkacpp.h"

    int main() {
      return 0;
    }

    marco@PC:~/librdkafka/examples$ g++ -std=c++17 plain.cpp -oplain -lrdkafka -lz -lpthread -lrt
    plain.cpp:1:10: fatal error: rdkafkacpp.h: No such file or directory
     #include "rdkafkacpp.h"
              ^~~~~~~~~~~~~~
    compilation terminated.

**Comment by edenhill** [comment]
After `sudo make install` the proper include path is:
`#include <librdkafka/rdkafkacpp.h>`

And then you build your application with info from pkg-config, e.g.:
`g++ $(pkg-config --cflags rdkafka++) .. yourapp.cpp -o yourapp $(pkg-config --libs rdkafka++)`

**Comment by marcoippolito** [comment]
marco@PC:~/librdkafka/examples$ g++ -std=c++17 $(pkg-config --cflags rdkafka++) plain.cpp -o 
    plain $(pkg-config --libs rdkafka++)
    marco@PC:~/librdkafka/examples$ ./plain

I have to deepen pkg-config because I actually do not know much about it. Bye the way, thanks a lot for your kind help.
Marco

**Comment by pradeepp2019** [comment]
@edenhill - I am getting the below error when I try to compile rdkafka_consumer_example.cpp but I am able to compile rdkafka_consumer_example.c file successfully. Can you please help me here? Note that I am trying to compile the files outside the librdkafka directory.

[root@vm7 seastarApps]# g++ rdkafka_consumer_example.cpp -o rdkafka_consumer_example `pkg-config --cflags --libs --static rdkafka++`
/tmp/ccBb6qV6.o: In function `main':
rdkafka_consumer_example.cpp:(.text+0xe74): undefined reference to `RdKafka::get_debug_contexts[abi:cxx11]()'
rdkafka_consumer_example.cpp:(.text+0xe9c): undefined reference to `RdKafka::version_str[abi:cxx11]()'
rdkafka_consumer_example.cpp:(.text+0x12f1): undefined reference to `RdKafka::KafkaConsumer::create(RdKafka::Conf*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
rdkafka_consumer_example.cpp:(.text+0x1463): undefined reference to `RdKafka::err2str[abi:cxx11](RdKafka::ErrorCode)'
/tmp/ccBb6qV6.o: In function `ExampleEventCb::event_cb(RdKafka::Event&)':
rdkafka_consumer_example.cpp:(.text._ZN14ExampleEventCb8event_cbERN7RdKafka5EventE[_ZN14ExampleEventCb8event_cbERN7RdKafka5EventE]+0xe1): undefined reference to `RdKafka::err2str[abi:cxx11](RdKafka::ErrorCode)'
rdkafka_consumer_example.cpp:(.text._ZN14ExampleEventCb8event_cbERN7RdKafka5EventE[_ZN14ExampleEventCb8event_cbERN7RdKafka5EventE]+0x3f2): undefined reference to `RdKafka::err2str[abi:cxx11](RdKafka::ErrorCode)'
/tmp/ccBb6qV6.o: In function `ExampleRebalanceCb::rebalance_cb(RdKafka::KafkaConsumer*, RdKafka::ErrorCode, std::vector<RdKafka::TopicPartition*, std::allocator<RdKafka::TopicPartition*> >&)':
rdkafka_consumer_example.cpp:(.text._ZN18ExampleRebalanceCb12rebalance_cbEPN7RdKafka13KafkaConsumerENS0_9ErrorCodeERSt6vectorIPNS0_14TopicPartitionESaIS6_EE[_ZN18ExampleRebalanceCb12rebalance_cbEPN7RdKafka13KafkaConsumerENS0_9ErrorCodeERSt6vectorIPNS0_14TopicPartitionESaIS6_EE]+0x37): undefined reference to `RdKafka::err2str[abi:cxx11](RdKafka::ErrorCode)'
collect2: error: ld returned 1 exit status

**Comment by pradeepp2019** [comment]
I still get the same problem with the above option. But, I am able to fix the problem with the below explicit linking of src and src-cpp of librdkafka.

g++ rdkafka_consumer_example.cpp -o rdkafka_consumer_example -lrdkafka++ -lrdkafka -L/home/pradeep/code/librdkafka/src-cpp -L/home/pradeep/code/librdkafka/src
