### ISSUE TITLE
64bit Redhat6.5 Compile librdkafka-master ERROR

### ISSUE THREAD

**Issue by mictnic** [edenhill/librdkafka#2013]
Redhat6.5 x64 system
When I configure with ./configure --mbits=32, then I type make to complie。 it reports error:
crc32c.c: In function ‘crc32c’:
crc32c.c:283: error: can't find a register in class ‘GENERAL_REGS’ while reloading ‘asm’
crc32c.c:303: error: can't find a register in class ‘GENERAL_REGS’ while reloading ‘asm’
crc32c.c:267: error: ‘asm’ operand has impossible constraints
crc32c.c:283: error: ‘asm’ operand has impossible constraints
crc32c.c:303: error: ‘asm’ operand has impossible constraints
crc32c.c: In function ‘crc32c_global_init’:
crc32c.c:380: error: PIC register ‘%ebx’ clobbered in ‘asm’
make[1]: *** [crc32c.o] Error 1
make[1]: Leaving directory `/usr/local/librdkafka-master/src'
make: *** [libs] Error 2

**Comment by edenhill** [comment]
Looks like an outdated toolchain.
