### ISSUE TITLE
unable to compile source code on openVOS(POSIX environment supported)

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#2014]
Description
===========
Hey guys,
     I am a newbie with this Kafka stuff. I import this source code and compiled on linux (Ubantu) and it works pretty well.

    I don't know this is right place to ask about other platform related stuff here. now I would like to compile the same on openVOS stratus mainframe which has POSIX support.
I tried but it prompts the following errors. Please help if possible. Thanks!

**bash-4.2$ ./configure --**prefix=/%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install
checking for OS or distribution... ok (VOS)
checking for C compiler from CC env... ok
checking for C++ compiler from CXX env... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... failed
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... failed
checking for __atomic_32_lib (by compile)... failed
checking for __sync_32 (by compile)... failed (disable)
checking for __atomic_64 (by compile)... failed
checking for __atomic_64_lib (by compile)... failed
checking for __sync_64 (by compile)... failed (disable)
checking for socket (by compile)... ok
parsing version '0x000b06ff'... ok (0.11.6)
checking for librt (by compile)... failed
checking for c11threads (by compile)... failed (disable)
checking for libpthread (by compile)... ok
checking for libdl (by compile)... ok
checking for zlib (by compile)... ok
checking for libcrypto (by compile)... ok
checking for libm (by compile)... ok
checking for liblz4 (by compile)... failed (disable)
checking for rapidjson (by compile)... failed (disable)
checking for libssl (by compile)... ok
checking for libsasl2 (by compile)... failed (disable)
checking for libsasl (by compile)... failed (disable)
checking for crc32chw (by compile)... failed (disable)
checking for regex (by compile)... ok
checking for strndup (by compile)... failed (disable)
checking for strerror_r (by compile)... failed (disable)
checking for pthread_setname_gnu (by compile)... failed (disable)
checking for nm (by env NM)... ok (cached)
checking for python (by command)... failed (disable)
disabling linker-script since python is not available
Generated Makefile.config
Generated config.h

**Configuration summary:**
  prefix                   /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install
  ARCH                     i786
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           y
  ENABLE_SSL               y
  ENABLE_SASL              y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               VOS
  SOLIB_EXT                .so
  CC                       gcc.pm
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.11.6
  MKL_APP_VERSION          0.11.6
  LIBS                     -lssl -lm -lcrypto -lz -ldl -lpthread
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install
  bindir                   /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install/bin
  sbindir                  /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install/sbin
  libexecdir               /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install/libexec
  datadir                  /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install/share
  sysconfdir               /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install/etc
  sharedstatedir           /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install/com
  localstatedir            /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install/var
  libdir                   /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install/lib
  includedir               /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install/include
  infodir                  /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install/info
  mandir                   /%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/install/man
Generated config.cache

Now type 'make' to build

**bash-4.2$ make**
make[1]: Entering directory `/%mkt2#m2_d06/Stratusoft/ARI_TechSupport/ENC_TEST/work_dir/librdkafka-master/src'
gcc.pm -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align  -c rdkafka.c -o rdkafka.o
In file included from tinycthread.h:497,
                 from rd.h:51,
                 from rdkafka_int.h:44,
                 from rdkafka.c:38:
tinycthread_extra.h:105: error: syntax error before "rwlock_t"
tinycthread_extra.h:105: warning: type defaults to `int' in declaration of `rwlock_t'
tinycthread_extra.h:105: warning: data definition has no type or storage class
tinycthread_extra.h:107: error: syntax error before '*' token
tinycthread_extra.h:108: error: syntax error before '*' token
tinycthread_extra.h:109: error: syntax error before '*' token
tinycthread_extra.h:110: error: syntax error before '*' token
tinycthread_extra.h:111: error: syntax error before '*' token
tinycthread_extra.h:112: error: syntax error before '*' token
In file included from rd.h:68,
                 from rdkafka_int.h:44,
                 from rdkafka.c:38:
rdposix.h: In function `rd_usleep':
rdposix.h:136: error: variable `req' has initializer but incomplete type

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): master branch
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [x] Operating system: openVOS (stratus mainframe)

**Comment by write2jaydeep** [comment]
@edenhill Thank you! I have figured out the problem and find out go ahead. I need to modify all the stuff and need define all missing stuff manually

**Comment by write2jaydeep** [comment]
Hi @edenhill 
I have compiled the source and created objs. during dynamic library building getting below errors.  I am not sure if you guys can throw some lights on it. I come to know that our platform openVOS doesn't support TLS(thread local storage). do this errors related to TLS?

**bind: Warning for object module
     %mkt2#m2_d01>librdkafka>src>obj>rdkafk
     a. 15 22

bind: Internal error for ELF symbol ret.2.**

**Comment by write2jaydeep** [comment]
@edenhill  Thanks! got the way out by defining this...
#if defined(__VOS__)
#define RD_TLS
#else
#define RD_TLS      __thread

#endif

**Comment by edenhill** [comment]
librdkafka requires TLS, so that patch will not work, it will break due to thread concurrent access.

**Comment by write2jaydeep** [comment]
@edenhill agree with you. I read docs related to openVOS and it provides scope of static variables per thread(task), it is not a global one. so I think I can ignore by defining the above rule.
Thank you!
