### ISSUE TITLE
How to get number of consumers in a group?

### ISSUE THREAD

**Issue by fredespo** [edenhill/librdkafka#2016]
Sorry if I am posting this in the wrong place, but I am wondering if it is possible to get the number of consumers in a given consumer group (using the C++ interface)?

**Comment by rnpridgeon** [comment]
You may want to have a look at the following:

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L3379-L3468

**Comment by fredespo** [comment]
Right, so how do I query the broker for that info? Do I have to go through the C interface with something like this? :

```
const struct rd_kafka_group_list *grplist = nullptr;
std::string group_name = "consumerGroup1";
rd_kafka_t *rk;
rd_kafka_conf_t *rkconf;
rkconf = rd_kafka_conf_new();
char rkerrstr[512];
rk = rd_kafka_new(RD_KAFKA_CONSUMER, rkconf, rkerrstr, sizeof(rkerrstr));
rd_kafka_list_groups(rk, group_name, &grplist, 5000);
```

**Comment by edenhill** [comment]
@fredespo Yep, that's the way, and then enumerate through the `grplist->groups[..]->members[..]` array.
