### ISSUE TITLE
KAFKA flush queue timeout error

### ISSUE THREAD

**Issue by TigersOP** [edenhill/librdkafka#2018]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We have a Async producer with a call back function. Some times we receive a error from KAFKA broker 
but we are able to see the actual error code we receive. Can you tellus how we can capture the error from rd_kafka_flush function and handle the error

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Register a delivery report callback, dr_msg_cb, which will give you the error status for each produce()d message. 
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1374
