### ISSUE TITLE
Consumer Seg Faults, partitions

### ISSUE THREAD

**Issue by drgardner43** [edenhill/librdkafka#2024]
Description
===========

I am having some interesting problems and hope someone has had a similar previous experience to help out. Thank you all for your time!

I am attempting to create a robust consumer class that will always start at offset 0 for a set of topics. To do this, I started with the KafkaConsumer.cpp example very closely. I have a rebalance_cb, event_cb, and setup a conf that I thought would use them. I also setup broker metadata & group ID in the conf object.

Then I create a consumer object, and subscribe to the topics list, and attempt to consume 10 times.

If this is a brand new topic, I am able to consume twice before segfault.
If this is an existing topic, I segfault during the fist consume.
If I restart execution right after failure, it will consume all 10 times, but give no data back (What I would expect, since I have no data on topic).

the backtrace is as such:
```

#0  0x00000000009579f0 in ?? ()
#1  0x00007ffff7bcdbb9 in RdKafka::rebalance_cb_trampoline (rk=<optimized out>, err=RD_KAFKA_RESP_ERR__ASSIGN_PARTITIONS, c_partitions=<optimized out>, opaque=0x9580a8)
    at HandleImpl.cpp:176
#2  0x00007ffff78da8ac in rd_kafka_poll_cb (rk=rk@entry=0x9588e0, rkq=rkq@entry=0x959940, rko=rko@entry=0x7fffdc001250, cb_type=cb_type@entry=RD_KAFKA_Q_CB_RETURN, 
    opaque=opaque@entry=0x0) at rdkafka.c:2811
#3  0x00007ffff78db186 in rd_kafka_consume0 (rk=0x9588e0, rkq=0x959940, timeout_ms=<optimized out>) at rdkafka.c:2210
#4  0x00007ffff7bd004a in RdKafka::KafkaConsumerImpl::consume (this=<optimized out>, timeout_ms=<optimized out>) at KafkaConsumerImpl.cpp:112

```

after some digging, I found the offset 0 article (very helpful). and added it into my callback. I had the same issue. So I added it to my main, and got a separate stack trace:

```
#0  0x00000000009579f0 in ?? ()
#1  0x00007ffff7bcdbb9 in RdKafka::rebalance_cb_trampoline (rk=<optimized out>, err=RD_KAFKA_RESP_ERR__REVOKE_PARTITIONS, c_partitions=<optimized out>, opaque=0x9580a8)
    at HandleImpl.cpp:176
#2  0x00007ffff78da8ac in rd_kafka_poll_cb (rk=rk@entry=0x9588e0, rkq=rkq@entry=0x959940, rko=rko@entry=0x7fffe40019b0, cb_type=cb_type@entry=RD_KAFKA_Q_CB_RETURN, 
    opaque=opaque@entry=0x0) at rdkafka.c:2811
#3  0x00007ffff78db186 in rd_kafka_consume0 (rk=0x9588e0, rkq=0x959940, timeout_ms=<optimized out>) at rdkafka.c:2210
#4  0x00007ffff7bd004a in RdKafka::KafkaConsumerImpl::consume (this=<optimized out>, timeout_ms=<optimized out>) at KafkaConsumerImpl.cpp:112
```
my questions are:

1. It looks like my rebalance_cb isn't being called, any ideas why?
2. Am I not shutting down correctly?
3. Is subscribing to an empty topic (and awaiting data) even a supported use case?

Any info you could give would be awesome. Thanks!

Checklist
=========

- librdkafka - 0.11.5
- OS -> RHEL 7.5

**Comment by edenhill** [comment]
It looks like your RebalanceCb class goes out of scope (e.g., stack-allocated), make sure it stays valid for the entire duration of the Producer.

**Comment by drgardner43** [comment]
Thank you for the fast response!

**Comment by yjxyy** [comment]
How to solve this problem, Thanks

**Comment by edenhill** [comment]
@yjxyy Make sure your RebalanceCb instance does not go out of scope, either by allocating it on the heap, keeping it as a global variable, or by making sure a stack-allocated instance does not go out of scope.
