### ISSUE TITLE
Offset not properly stored between consumer runs

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#203]
See test case here:

https://bitbucket.org/yungchin/python-librdkafka/commits/b9e6f4c7ea6b26de5821e299fb58ec023d459bdb#Ltests.pyT113

**Comment by yungchin** [comment]
Thanks for this!
Just to add - the newly stored offset does eventually make it to disk. That is, if I run the test a second time, I get back the offset I stored on the earlier run. It just seems that loading the RD_KAFKA_OFFSET_STORED might ignore the one that's still on its way to disk?

**Comment by edenhill** [comment]
Dup #227
