### ISSUE TITLE
problem with set queue.buffering.max.messages 

### ISSUE THREAD

**Issue by D-fazeli** [edenhill/librdkafka#2031]
I want send `8G` `CSV` file from rsyslog to Kafka. my bandwidth is `limit`. I need to limit rsyslog for send.
when i set `queue.buffering.max.messages=15000` I have `3Mbps` load on interface rsyslog server(output), and when set `queue.buffering.max.messages=20000` the volume sent is strangely increased.
with this config, `70Mbps` load on interface, While expected to be added to the amount Load twice, but the load is multiplied. Is this parameter more influential than other parameters?
Where do I make mistakes?

my config file is : 
```
Module (load="imfile")
Module (load="omkafka")

Input(type="imfile" File="/opt/*.csv" tag="send_csv_file" ruleset="send_csv_file")

template(name="tpl1" type="string" string="%msg%")

ruleset(name="send_csv_file"){
        action(type="omkafka" broker=["192.168.163.37:9092","192.168.163.38:9092","192.168.163.39:9092"]  topic="test24" template="tpl1" failedMsgFile="/var/log/failedMsg-kafka.msg" partitions.number="12" confParam=["queue.buffering.max.messages=20000"] )
}
```
thanks.

**Comment by edenhill** [comment]
You should leave the queue settings at the defaults.

To optimize performance in your case I suggest increasing the chances of batches by setting `linger.ms` to something like `100`. The longer the batch linger, the larger the batches, the higher the throughput.
you will need to find the sweet spot for your use-case.
