### ISSUE TITLE
any way to disable IPV6 related stuff during processor stage 

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#2034]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We have openVOS platform which is almost Linux like. it doesn't have headers files related to IPV6. I would like to disable IPV6 in librdkafka. is there any way?

Thanks!

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): master
 
 - [ ] Operating system: openVOS
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Do you mean during build or runtime?
You can disable ipv6 connections at runtime by setting broker.address.family=v4.
It is not possible to build without IPV6 support at this point.

**Comment by write2jaydeep** [comment]
@edenhill Thank you for quick response. I need during the build as We do not have supported header files.
I will try to put preprocessor directive my own. Thanks again.
