### ISSUE TITLE
Producer - Local: Message timed out - while performing load testing.

### ISSUE THREAD

**Issue by dganesan23** [edenhill/librdkafka#2035]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
we have a single producer instance publishing messages to 3 topics and we have delivery report callback.
While performing load testing, we are seeing "Local:Message Timed Out" error .

We are using latest stable version 0.11.5 in our .net project.
Kafka server is 2.0.0 and we have 8 partition for each topics.
messages to topics are grouped by our key.

Thanks in advance

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.5 (stable)
 - [X ] Apache Kafka version: `<2.0.0`
 - [X ] librdkafka client configuration: 
     "bootstrap.servers" - 3 servers,
 "request.timeout.ms" 10000,
 "message.timeout.ms" 300000,
"security.protocol" SASL_SSL,
"ssl.ca.location" C:\cert,
"sasl.mechanisms" PLAIN,
"sasl.username" test,
"sasl.password" afhjdsfhasdf,
"max.in.flight.requests.per.connection" 5,
"retries" 1 or 3 (tried both),
"acks" 1/all (tried both),
"retry.backoff.ms" 1000,
"linger.ms" 100,
 - [ X] Operating system: `window iis 16gb memory`
 - [ X] Provide logs (with `debug=..` as necessary) from librdkafka 'debug - all'
 - [X ] Provide broker log excerpts
seeing message Local:Message Timeout
 - [X ] Critical issue

**Comment by dganesan23** [comment]
We changed to default value for equest.timeout.ms, retry.backoff.ms, max.in.flight parameters. but we are still seeing Local:Message Timeout.

Our load rate is around 7000 message for an hour and each message size is approximately 300mb. 
We also checked the bootstrap server and cluster logs  and everything looked fine.

When we enabled kafka log, we saw messages like FACILITY:BROKERFAIL, FACITLITY:LEADERDOWN.

Having single producer instance can be a problem?
Does the number of consumers have an impact?

**Comment by edenhill** [comment]
300 megabyte per **message**?

**Comment by dganesan23** [comment]
yes

**Comment by dganesan23** [comment]
Sorry .. 300kb per message

**Comment by edenhill** [comment]
Please provide the log messages, not just the facility

**Comment by dganesan23** [comment]
[thrd:sasl_ssl:///bootstrap]: sasl_ssl:/: failed: err: Local: Timed out: (errno: Unknown error), level:7, Name: rdkafka#producer-1, Facility:BROKERFAIL
[thrd:sasl_ssl://9093/bootstrap]: sasl_ssl://: Request metadata for 3 topic(s): broker down, level:7, Name: rdkafka#producer-1, Facility:METADATA
[thrd:sasl_ssl://9093/bootstrap]: sasl_ssl://:9093/1001: Timed out 0+2+0 requests, level:7, Name: rdkafka#producer-1, Facility:REQTMOUT
On Producer Logging for the message : [thrd:sasl_ssl://9093/bootstrap]: sasl_ssl://9093/1002: dev.sac.loan.webhooks [7]: MessageSet with 14 message(s) encountered error: Local: Timed out (actions Retry), level:7, Name: rdkafka#producer-1, Facility:MSGSET
[thrd:main]: Topic xxx.deferred [6]: leader is down: re-query, level:7, Name: rdkafka#producer-1, Facility:QRYLEADER
 [thrd:sasl_ssl://9093/bootstrap]: sasl_ssl:// Updating 4 buffers on connection reset, level:7, Name: rdkafka#producer-1, Facility:BUFQ
[thrd:sasl_ssl://9093/bootstrap]: sasl_ssl://:9093 :topic: xxxx [1] 76 message(s) in xmit queue (76 added from partition queue), level:7, Name: rdkafka#producer-1, Facility:TOPPAR

**Comment by edenhill** [comment]
This is most likely #1980, timers start wrapping after around 7+ days on Windows.
If restarting the machine helps then this is definitely the case.
A new release (v0.11.6) is scheduled for next week

**Comment by dganesan23** [comment]
it is just not happening after 7 days. there is no pattern on when its happening. 
Is there a way to reproduce?

**Comment by edenhill** [comment]
There seems to be networking, congestion, auth, or broker issues. Check the broker logs and load.

**Comment by dganesan23** [comment]
No messages in the broker log. 
Callback error message has IsLocal :true and IsBroker :false
No auth issue because  Local: Message timeout is inconsitent.
When we start the load testing, first 500 to 1000 message are fine . it starts timing out after 1000 msg (approx)

How can we detect if it is network congestion?

We are not able to replicate the issue from our local. We tried to send 10 times more load from our local app.

here are our config
  { "bootstrap.servers", "x:9093,xxx:9093,xxxx"  },
                        { "request.timeout.ms", "5000"},
                        { "message.timeout.ms", "120000"},
                        { "security.protocol", "SASL_SSL" },
                        { "ssl.ca.location", "C:\\cert\\ca-cert" },
                        { "sasl.mechanisms", "PLAIN"},
                        { "sasl.username", "test23234" },
                        { "sasl.password", "password123" },
                        {"max.in.flight.requests.per.connection", "1000000"},
                        {"retries", "3"},
                        {"acks", "all"},
                        {"retry.backoff.ms", "100"},
                        {"linger.ms", "100"}

**Comment by edenhill** [comment]
You might actually be hitting #1980 . Could you try v0.11.6?

**Comment by dganesan23** [comment]
we tried updating version to 0.11.6 but still getting thousands of timeout message in async mode. 
Synchronouse mode its working fine.

**Comment by edenhill** [comment]
Please reproduce with `debug=protocol,broker,msg,queue` and provide the logs.
