### ISSUE TITLE
Send a single ProduceRequest for all partitions led by the same broker

### ISSUE THREAD

**Issue by poolik** [edenhill/librdkafka#2036]
Description
===========
I've noticed that when producing multiple messages to many different partitions which are all led by the same broker then `librdkafka` creates a `ProduceRequest` for each of these partitions instead of batching them together. This seems like a significant potential performance problem, in case one has say 100 partitions, but only pushing small nr of messages per partition.

The Kafka protocol docs seem to indicate that this kind of across partition batching is possible [(link)](https://kafka.apache.org/protocol):
> A clever client can make use of this and support an "asynchronous" mode in which it batches together messages sent individually and sends them in larger clumps. We go even further with this and allow the batching across multiple topics and partitions, so a produce request may contain data to append to many partitions and a fetch request may pull data from many partitions all at once.

After briefly reading the code of the Java client then it does seem to do this across partition batching for produce requests to the same broker.

I tried to find an issue or some documentation discussing why `librdkafka` isn't doing this batching. For us this would be a significant performance boost as we produce to ~30 different partitions led by the same broker in one go, but only 1-3 small messages to each partitions. At the moment this results in ~30 small `ProduceRequests`, but could be done with 1 large one.

How to reproduce
================
1) Create a cluster with at least 2 brokers and a topic with at least 5 partitions
2) Produce to 2 partitions led by the same broker in parallel with some small linger.ms value
3) Notice librdkafka sends 2 separate `ProduceRequest`-s for these partitions, even though they go to the same broker and could be batched.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.5`
 - [x] Apache Kafka version: `1.0.1`
 - [x] librdkafka client configuration: `debug: 'all', linger.ms: 10`
 - [x] Operating system: `macOS 10.13.6`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You are right, librdkafka currently only sends one partition per ProduceRequest.
This will be fixed later this year.

**Comment by poolik** [comment]
@edenhill thanks for the quick confirmation, looking forward to the fix then. Unfortunately I'm not fluent in C enough to help contributing it myself. I also assume that the fix won't be trivial due to some needed locking changes to achieve this.

Thanks again. Will you update this issue once the batching is done?

**Comment by edenhill** [comment]
Will do.

Do note that batching is performed on a per-partition level, so if you produce multiple messages to a single partition within linger.ms they will be batched.

**Comment by edenhill** [comment]
Dup of #1700
