### ISSUE TITLE
Build error 32Bit on 64Bit Centos 7 machine

### ISSUE THREAD

**Issue by bhattmayur26** [edenhill/librdkafka#2043]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi Edenhill,

I am trying to build 32 bit version of librdkafka on 64 bit CentOS 7. I have installed all dependencies zlib-dev, libssl-dev and libsasl2-dev  (32-Bit versions). When I try to build, I am getting below build errors. Can you please help.

crc32c.c: In function ‘crc32c’:
crc32c.c:283:13: error: ‘asm’ operand has impossible constraints
             __asm__("crc32q\t" "(%3), %0\n\t"
             ^
crc32c.c:303:13: error: ‘asm’ operand has impossible constraints
             __asm__("crc32q\t" "(%3), %0\n\t"
             ^
crc32c.c: In function ‘crc32c_global_init’:
crc32c.c:349:9: error: PIC register clobbered by ‘%ebx’ in ‘asm’
         __asm__("cpuid" \
         ^
crc32c.c:380:9: note: in expansion of macro ‘SSE42’
         SSE42(sse42);
         ^
make[1]: *** [crc32c.o] Error 1

How to reproduce
================

1. Install glibc 32-bit
    sudo yum install -y glibc-devel.i686

2. Install dependencies
   
   sudo yum install -y cyrus-sasl-devel.i686

   sudo yum install -y openssl-devel.i686

3.  Download librdkafka package librdkafka-0.11.x

4. Install using below steps
    
    ./configure --mbits=32
    make

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `< v0.11.x>` 
 - [ ] Apache Kafka version: `<0.10.2.3>`
 - [ ] librdkafka client configuration: `<>`
 - [x] Operating system: `<Centos 7 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Provide the output from ./configure and config.log

**Comment by bhattmayur26** [comment]
Thanks for the reply. Here is output from ./configure

$ ./configure --mbits=32
using cache file config.cache
checking for OS or distribution... ok (CentOS)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok (cached)
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok (cached)
checking for mbits compiler flag (-m32)... ok (cached)
checking executable ld... ok (cached)
checking executable nm... ok (cached)
checking executable objdump... ok (cached)
checking executable strip... ok (cached)
checking for pkgconfig (by command)... ok (cached)
checking for install (by command)... ok (cached)
checking for PIC (by compile)... ok (cached)
checking for GNU-compatible linker options... ok (cached)
checking for GNU linker-script ld flag... ok (cached)
checking for __atomic_32 (by compile)... ok (cached)
checking for __atomic_64 (by compile)... ok (cached)
checking for socket (by compile)... ok (cached)
parsing version '0x000b03ff'... ok (0.11.3)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok (cached)
checking for zlib (by pkg-config)... ok
checking for zlib (by compile)... ok (cached)
checking for libcrypto (by pkg-config)... ok
checking for libcrypto (by compile)... ok (cached)
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for libssl (by pkg-config)... ok
checking for libssl (by compile)... ok (cached)
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... ok (cached)
checking for crc32chw (by compile)... ok (cached)
checking for regex (by compile)... ok (cached)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok (cached)
checking for strndup (by compile)... ok (cached)
checking for strerror_r (by compile)... ok (cached)
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok (cached)
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok (cached)
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           y
  ENABLE_SSL               y
  ENABLE_SASL              y
  MBITS                    32
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               CentOS
  SOLIB_EXT                .so
  CC                       gcc
  CXX                      g++
  CPPFLAGS                 -m32 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  LDFLAGS                  -m32
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.11.3
  MKL_APP_VERSION          0.11.3
  LIBS                     -lpthread -lz   -lcrypto   -lssl -lcrypto   -lsasl2 -lrt -ldl
  CFLAGS                        
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
Generated config.cache

Now type 'make' to build
$ 





Here is config.log file

# configure exec: ./configure --mbits=32
# On Wed Oct 10 15:13:33 EDT 2018
DBG: ccenv: WITH_CC:  --version failed: mklove/modules/configure.base: line 1184: --version: command not found
DBG: Check ccenv (WITH_CC, action cont (originally cont)) failed: command ' --version' failed:
mklove/modules/configure.base: line 1184: --version: command not found
DBG: cxxenv: WITH_CXX:  --version failed: mklove/modules/configure.base: line 1184: --version: command not found
DBG: Check cxxenv (WITH_CXX, action cont (originally cont)) failed: command ' --version' failed:
mklove/modules/configure.base: line 1184: --version: command not found
DBG: pkg-config check libpthread (): pkg-config --short-errors --cflags libpthread
DBG: 'pkg-config --short-errors --cflags libpthread' failed: No package 'libpthread' found
DBG: Check libpthread_PKGCONFIG (, action cont (originally cont)) failed: 'pkg-config --short-errors --cflags libpthread' failed:
No package 'libpthread' found
DBG: pkg-config check zlib (): pkg-config --short-errors --cflags zlib
DBG: pkg-config check libcrypto (): pkg-config --short-errors --cflags libcrypto
DBG: pkg-config check liblz4 (): pkg-config --short-errors --cflags liblz4
DBG: 'pkg-config --short-errors --cflags liblz4' failed: No package 'liblz4' found
DBG: Check liblz4_PKGCONFIG (, action cont (originally cont)) failed: 'pkg-config --short-errors --cflags liblz4' failed:
No package 'liblz4' found
DBG: Compile check liblz4 (WITH_LZ4_EXT): gcc  -m32 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpx5lNGI.c -o _mkltmpx5lNGI.c.o  -m32 -llz4
DBG: compile check for liblz4 (WITH_LZ4_EXT) failed: gcc  -m32 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpx5lNGI.c -o _mkltmpx5lNGI.c.o  -m32 -llz4: _mkltmpx5lNGI.c:1:22: fatal error: lz4frame.h: No such file or directory
 #include <lz4frame.h>
                      ^
compilation terminated.
DBG: Check liblz4 (WITH_LZ4_EXT, action disable (originally disable)) failed: compile check failed:
CC: CC
flags: -llz4
gcc  -m32 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpx5lNGI.c -o _mkltmpx5lNGI.c.o  -m32 -llz4:
_mkltmpx5lNGI.c:1:22: fatal error: lz4frame.h: No such file or directory
 #include <lz4frame.h>
                      ^
compilation terminated.
source: #include <lz4frame.h>
DBG: pkg-config check libssl (): pkg-config --short-errors --cflags libssl
DBG: pkg-config check libsasl2 (): pkg-config --short-errors --cflags libsasl2
DBG: 'pkg-config --short-errors --cflags libsasl2' failed: No package 'libsasl2' found
DBG: Check libsasl2_PKGCONFIG (, action cont (originally cont)) failed: 'pkg-config --short-errors --cflags libsasl2' failed:
No package 'libsasl2' found
DBG: pkg-config check librt (): pkg-config --short-errors --cflags librt
DBG: 'pkg-config --short-errors --cflags librt' failed: No package 'librt' found
DBG: Check librt_PKGCONFIG (, action cont (originally cont)) failed: 'pkg-config --short-errors --cflags librt' failed:
No package 'librt' found
DBG: pkg-config check libdl (): pkg-config --short-errors --cflags libdl
DBG: 'pkg-config --short-errors --cflags libdl' failed: No package 'libdl' found
DBG: Check libdl_PKGCONFIG (, action cont (originally cont)) failed: 'pkg-config --short-errors --cflags libdl' failed:
No package 'libdl' found

**Comment by edenhill** [comment]
That run was using cached values, please do this and provide the output, config.log and config.h:
```
./configure --clean
./configure
cat config.log
cat config.h
```

**Comment by bhattmayur26** [comment]
[user@localhost librdkafka-0.11.x]$ ./configure --clean
Removing Makefile.config
Removing config.h
Removing config.cache
Removing config.log


[user@localhost librdkafka-0.11.x]$ ./configure
checking for OS or distribution... ok (CentOS)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x000b03ff'... ok (0.11.3)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for zlib (by compile)... ok (cached)
checking for libcrypto (by pkg-config)... ok
checking for libcrypto (by compile)... ok (cached)
checking for liblz4 (by pkg-config)... ok
checking for liblz4 (by compile)... ok (cached)
checking for libssl (by pkg-config)... ok
checking for libssl (by compile)... ok (cached)
checking for libsasl2 (by pkg-config)... ok
checking for libsasl2 (by compile)... ok (cached)
checking for crc32chw (by compile)... ok
checking for regex (by compile)... ok
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for strndup (by compile)... ok
checking for strerror_r (by compile)... ok
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           y
  ENABLE_SSL               y
  ENABLE_SASL              y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               CentOS
  SOLIB_EXT                .so
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.11.3
  MKL_APP_VERSION          0.11.3
  LIBS                     -lpthread -lz   -lcrypto   -llz4   -lssl -lcrypto   -lsasl2   -lrt -ldl
  CFLAGS                            
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
Generated config.cache

Now type 'make' to build


[user@localhost librdkafka-0.11.x]$ cat config.log
# configure exec: ./configure 
# On Thu Oct 11 12:00:38 EDT 2018
DBG: ccenv: WITH_CC:  --version failed: mklove/modules/configure.base: line 1184: --version: command not found
DBG: Check ccenv (WITH_CC, action cont (originally cont)) failed: command ' --version' failed:
mklove/modules/configure.base: line 1184: --version: command not found
DBG: cxxenv: WITH_CXX:  --version failed: mklove/modules/configure.base: line 1184: --version: command not found
DBG: Check cxxenv (WITH_CXX, action cont (originally cont)) failed: command ' --version' failed:
mklove/modules/configure.base: line 1184: --version: command not found
DBG: Compile check PIC (HAVE_PIC): gcc  -g -O2 -Wall -Werror _mkltmpPLXGo2.c -o _mkltmpPLXGo2.c.o   -fPIC
DBG: Compile check gnulib (WITH_GNULD): gcc  -g -O2 -fPIC -Wall -Werror _mkltmp8tMwEa.c -o _mkltmp8tMwEa.c.o   -shared -Wl,-soname,mkltest.0
DBG: Compile check ldsflagvs (): gcc  -g -O2 -fPIC -Wall -Werror _mkltmpjAboG2.c -o _mkltmpjAboG2.c.o   -shared -Wl,--version-script=_mkltmpdfZZo9
DBG: Compile check __atomic_32 (HAVE_ATOMICS_32): gcc  -g -O2 -fPIC -Wall -Werror _mkltmpZWdG0H.c -o _mkltmpZWdG0H.c.o   
DBG: Compile check __atomic_64 (HAVE_ATOMICS_64): gcc  -g -O2 -fPIC -Wall -Werror _mkltmpXmq0Un.c -o _mkltmpXmq0Un.c.o   
DBG: Compile check socket (): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpPY0Hsa.c -o _mkltmpPY0Hsa.c.o   
DBG: pkg-config check libpthread (): pkg-config --short-errors --cflags libpthread
DBG: 'pkg-config --short-errors --cflags libpthread' failed: No package 'libpthread' found
DBG: Check libpthread_PKGCONFIG (, action cont (originally cont)) failed: 'pkg-config --short-errors --cflags libpthread' failed:
No package 'libpthread' found
DBG: Compile check libpthread (): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmp48F3u5.c -o _mkltmp48F3u5.c.o   -lpthread
DBG: pkg-config check zlib (): pkg-config --short-errors --cflags zlib
DBG: pkg-config check libcrypto (): pkg-config --short-errors --cflags libcrypto
DBG: pkg-config check liblz4 (): pkg-config --short-errors --cflags liblz4
DBG: pkg-config check libssl (): pkg-config --short-errors --cflags libssl
DBG: pkg-config check libsasl2 (): pkg-config --short-errors --cflags libsasl2
DBG: Compile check crc32chw (WITH_CRC32C_HW): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpoHxroS.c -o _mkltmpoHxroS.c.o   
DBG: Compile check regex (HAVE_REGEX): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpftXmQ7.c -o _mkltmpftXmQ7.c.o   
DBG: pkg-config check librt (): pkg-config --short-errors --cflags librt
DBG: 'pkg-config --short-errors --cflags librt' failed: No package 'librt' found
DBG: Check librt_PKGCONFIG (, action cont (originally cont)) failed: 'pkg-config --short-errors --cflags librt' failed:
No package 'librt' found
DBG: Compile check librt (): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpEJpAXL.c -o _mkltmpEJpAXL.c.o   -lrt
DBG: Compile check strndup (HAVE_STRNDUP): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpSrmEZG.c -o _mkltmpSrmEZG.c.o   
DBG: Compile check strerror_r (HAVE_STRERROR_R): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpl8OGAz.c -o _mkltmpl8OGAz.c.o   
DBG: pkg-config check libdl (): pkg-config --short-errors --cflags libdl
DBG: 'pkg-config --short-errors --cflags libdl' failed: No package 'libdl' found
DBG: Check libdl_PKGCONFIG (, action cont (originally cont)) failed: 'pkg-config --short-errors --cflags libdl' failed:
No package 'libdl' found
DBG: Compile check libdl (WITH_LIBDL): gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpHzrZ3y.c -o _mkltmpHzrZ3y.c.o   -ldl


[user@localhost librdkafka-0.11.x]$ cat config.h
// Automatically generated by ./configure 
#pragma once
#define ARCH "x86_64"
#define CPU "generic"
#define WITHOUT_OPTIMIZATION 0
#define ENABLE_DEVEL 0
#define ENABLE_VALGRIND 0
#define ENABLE_REFCNT_DEBUG 0
#define ENABLE_SHAREDPTR_DEBUG 0
#define ENABLE_LZ4_EXT 1
#define ENABLE_SSL 1
#define ENABLE_SASL 1
#define MKL_APP_NAME "librdkafka"
#define MKL_APP_DESC_ONELINE "The Apache Kafka C/C++ library"
// distro
#define SOLIB_EXT ".so"
// gcc
#define WITH_GCC 1
// gxx
#define WITH_GXX 1
// pkgconfig
#define WITH_PKGCONFIG 1
// install
#define WITH_INSTALL 1
// PIC
#define HAVE_PIC 1
// gnulib
#define WITH_GNULD 1
// __atomic_32
#define HAVE_ATOMICS_32 1
// __atomic_32
#define HAVE_ATOMICS_32_ATOMIC 1
// atomic_32
#define ATOMIC_OP32(OP1,OP2,PTR,VAL) __atomic_ ## OP1 ## _ ## OP2(PTR, VAL, __ATOMIC_SEQ_CST)
// __atomic_64
#define HAVE_ATOMICS_64 1
// __atomic_64
#define HAVE_ATOMICS_64_ATOMIC 1
// atomic_64
#define ATOMIC_OP64(OP1,OP2,PTR,VAL) __atomic_ ## OP1 ## _ ## OP2(PTR, VAL, __ATOMIC_SEQ_CST)
// atomic_64
#define ATOMIC_OP(OP1,OP2,PTR,VAL) __atomic_ ## OP1 ## _ ## OP2(PTR, VAL, __ATOMIC_SEQ_CST)
// parseversion
#define RDKAFKA_VERSION_STR "0.11.3"
// parseversion
#define MKL_APP_VERSION "0.11.3"
// zlib
#define WITH_ZLIB 1
// liblz4
#define WITH_LZ4_EXT 1
// WITH_SNAPPY
#define WITH_SNAPPY 1
// WITH_SOCKEM
#define WITH_SOCKEM 1
// libssl
#define WITH_SSL 1
// libsasl2
#define WITH_SASL_CYRUS 1
// WITH_SASL_SCRAM
#define WITH_SASL_SCRAM 1
// crc32chw
#define WITH_CRC32C_HW 1
// regex
#define HAVE_REGEX 1
// strndup
#define HAVE_STRNDUP 1
// strerror_r
#define HAVE_STRERROR_R 1
// libdl
#define WITH_LIBDL 1
// WITH_PLUGINS
#define WITH_PLUGINS 1
// python
#define HAVE_PYTHON 1
[user@localhost librdkafka-0.11.x]$

**Comment by edenhill** [comment]
Wait, you are on v0.11.3? Can you try librdkafka v0.11.5 or preferably master branch?

**Comment by bhattmayur26** [comment]
Closing this as we no longer have the requirement to use 32-bit version
