### ISSUE TITLE
How to fetch last published message from unassigned partition

### ISSUE THREAD

**Issue by nilsocket** [edenhill/librdkafka#2045]
I produce messages to kafka, there is high probability, my program crashes frequently. So I want to fetch the last published message and continue my work from their.
The problem I was facing is I was publishing my messages to `RD_KAFKA_PARTITION_UA`.

So how can I fetch the last message with minimal code.

 - [x] librdkafka version (release number or git tag): `0.11.5`
 - [x] Apache Kafka version: `2.11-2.0.0`
 - [x] Operating system: `ubuntu 16.04`

**Comment by edenhill** [comment]
The unassigned/any partition is used when producing to have the partitioner select a partition.
With the consumer you must either know the partition to consume, or consume all of them.
You can use RD_KAFKA_OFFSET_TAIL(1) as the starting offset for each partition you pass to assign() to start consuming at the last message.

**Comment by nilsocket** [comment]
Thank you.
