### ISSUE TITLE
What offset do resumed consumers start reading from?

### ISSUE THREAD

**Issue by ronalabraham** [edenhill/librdkafka#2052]
In https://github.com/edenhill/librdkafka/issues/1849#issue-332908938, @accelerated asked:

> 4\. If I keep polling while the consumer is paused, I assume the local queue will still deliver buffered messages, but librdkafka will no longer fetch batches from the broker, correct?

@edenhill responded with:

> 4\. No, it will not give you any new messages when polling, in fact it will purge the queue of fetched messages, and stop the fetcher.

Can you please explain what happens when you later resume? Is there some consumer-side bookkeeping to guarantee that you resume reading from the next message in the partition that has yet to be delivered to the application? My guess is yes, but just wanted to confirm.

**Comment by edenhill** [comment]
Yes, when pausing the consumer saves the current application offset as the next_offset.
When resuming, the fetcher starts at next_offset.
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_partition.c#L1729

**Comment by ronalabraham** [comment]
Thanks!
