### ISSUE TITLE
Kafka client connected to Kafka cluster, but not join in any "consumer group"

### ISSUE THREAD

**Issue by wbb1975** [edenhill/librdkafka#2055]
Description
===========
Currently we are using librdkafka-0.9.5 as our Kafka client library. Our code is C++, and our deployment is Oracle Linux Server release 7.1. When the application starts, it will build connection against our Kafka Cluster, and join in the "feeder.$HOSTNAME" consume group to consume three topics(each topic all has just 1 partition). The issue is that sometimes our client library has create connection to the Kafka cluster, but didn't join into our expected consumer group. Please see the following screenshot for mode details:

1. Our machine c410gqczpin12 has built TCP connection with Kafka cluster:
c410gqczpin12:/data# netstat -anp | grep 9092
tcp        0      0 10.249.*.*:50480    10.249.166.*:9092      ESTABLISHED 4490/java
tcp        0      0 10.249.*.*:36466    10.249.166.*:9092      ESTABLISHED 4490/java
tcp        0      0 10.249.*.*:56372    10.249.166.*:9092      ESTABLISHED 4490/java
tcp        0      0 10.249.*.*:37008    10.249.134.*:9092      ESTABLISHED 5503/ingestfeeder
tcp        0      0 10.249.*.*:36198    10.249.134.*:9092      ESTABLISHED 4490/java
tcp        0      0 10.249.*.*:32808    10.249.134.*:9092      ESTABLISHED 5503/ingestfeeder
tcp        0      0 10.249.*.*:38838    10.249.146.*:9092      ESTABLISHED 5503/ingestfeeder
tcp        0      0 10.249.*.*:49742    10.249.146.*:9092      ESTABLISHED 5503/ingestfeeder
tcp        0      0 10.249.*.*:34710    10.249.146.*:9092      ESTABLISHED 5503/ingestfeeder
tcp        0      0 10.249.*.*:36794    10.249.134.*:9092      ESTABLISHED 5503/ingestfeeder

2. But our client c410gqczpin12 didn’t join consumer group in kafka cluster
In kafka cluster, we have found other 15 servers have joining the consumer group, not no kafka consumer group like "feeder.c410gqczpin12" found.

3. Check the counter, found that this thread block at:
Message *kafkaMsg = m_Consumer->consume(m_KafkaPollTimeout);
++m_StatPollCount;
So there is no any message fetched out.

Could you help check why my code didn't join into "consumer group" successfully? And why no any error reported when not join in the "consumer group"?

How to reproduce
================
I am very sorry this is not always reproduced--but I have observed this case two times in last three months. But I can attach related code as below:

m_KafkaClientFile = fopen(m_KakfkaEventCBFilename.c_str(), "w");
Conf::ConfResult result = Conf::CONF_OK;
string errorStr;
m_KafkaConf = Conf::create(Conf::CONF_GLOBAL);
result = m_KafkaConf->set(Constants::KAFKA_BOOTSTRAP_SERVERS, m_KafkaBootstrapServers, errorStr);
result = m_KafkaConf->set(Constants::KAFKA_GROUP_ID, m_KafkaGroupID, errorStr);
result = m_KafkaConf->set(Constants::KAFKA_EVENT_CB, this, errorStr);
result = m_KafkaConf->set(Constants::KAFKA_FETCH_MESSGE_MAX_BYTES, m_KafkaFetchMaxMessageSize, errorStr);
 m_Consumer = KafkaConsumer::create(m_KafkaConf, errorStr);
 if (m_Consumer == nullptr)
 {
        // log error
         return false;
 }
// https://stackoverflow.com/questions/42496443/why-consumer-hangs-while-consuming-messages-from-kafka-on-dc-os-using-client-api
 // ErrorCode resp = m_Consumer->subscribe(kafkaTopics);
ErrorCode resp = m_Consumer->assign(partitions);
 if (ERR_NO_ERROR != resp)
{
   // log error
  return false;
}
while (true)
{
                // consume may block forever https://stackoverflow.com/questions/37682296/kafka-consumers-poll-method-gets-blocked
                // https://stackoverflow.com/questions/38597037/kafka-consumer-poll-and-reconnection
                Message *kafkaMsg = m_Consumer->consume(m_KafkaPollTimeout);
                ++m_StatPollCount;
}

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.9.5`
 - [x] Apache Kafka version: `1.00`
 - [x] librdkafka client configuration:     
bootstrap.servers="hostname:9092" 
enable.auto.commit="true"
subscribetopics="***" 
fetch.message.max.bytes="10485760"
kafkaeventcbfile="logs/kafkaclient.log"
 - [x] Operating system: Oracle Linux Server release 7.1
 - [x] Provide logs: no librdkafka logs generated.
 - [x] Provide broker log excerpts: Sorry this is our production env and I have no way to get it.
 - [x] Critical issue

**Comment by wbb1975** [comment]
Previous I have found similar issue--at that time I was using subscribe to join the "consumer group like m_Consumer->subscribe(kafkaTopics);. After some investigation I changed it into m_Consumer->assign(partitions); but it seems this issue is not fixed completely. So my questions are:
1. If it failed in joining the consumer group, why no any function return code indicated this?
2. Why consume block and never return?

Appreciate your guys help. If your guys need further stuff, please ping me. Thanks!

**Comment by edenhill** [comment]
Please try to reproduce this on the latest released version, v0.11.5, or master.
You can enable debugging for the consumer by setting the `debug` configuration property to `consumer` or `cgrp` (more detailed)

**Comment by wbb1975** [comment]
Hi Edenhill,

    I am sorry this issue is not 100% reproducible, we just found 2 cases in last three months. So expect you can help give some check from code respective.
    I will check the history of change after v0.95.0 until v0.11.5 to check there is any fixes related with this issue and whether it's worth to upgrade our client version to it.

Thanks and Regards!
Bingbing
