### ISSUE TITLE
KIP-140: Add support for ACLs in Admin API

### ISSUE THREAD

**Issue by mlongob** [edenhill/librdkafka#2058]
Protocol:
* `DescribeAcls` - https://kafka.apache.org/protocol#The_Messages_DescribeAcls
* `CreateAcls` - https://kafka.apache.org/protocol#The_Messages_CreateAcls
* `DeleteAcls` - https://kafka.apache.org/protocol#The_Messages_DeleteAcls

Proposed in: https://cwiki.apache.org/confluence/display/KAFKA/KIP-140%3A+Add+administrative+RPCs+for+adding%2C+deleting%2C+and+listing+ACLs

**Comment by Smithx10** [comment]
@mlongob  By chance, have you found a way around this?

**Comment by emasab** [comment]
implemented in https://github.com/edenhill/librdkafka/pull/2676
