### ISSUE TITLE
kafka produce issue on multiple send

### ISSUE THREAD

**Issue by raven1978** [edenhill/librdkafka#206]
Hi

I developed a simple program to do multiple calls to lib function  rd_kafka_produce (i.e. 10 function calls) to send a simple message to kafka.
The problem is that during comunication with kafka node some message are gonna be lose .

For example if I send 10 messages, only 9 will be consume kafka side, but the return value of rd_kafka_produce is always =0 (success), for all 10 calls.
Furthermore, I've only 9 callback function call on my msg_delivered cb.

This means that only 9 message of 10 were delivered to kafka module.

Why I received ten 0 code from rd_kafka_produce function ?

I don't know if there is some issue on my side, or connection problem or something else...

Here you can find the most relevant pieces of my code:
````
static void msg_delivered (rd_kafka_t *rk,
                           const rd_kafka_message_t *rkmessage, void *opaque) {
	printf("SENT: %s\n",  (const char *)rkmessage->payload);
}

static void err_cb (rd_kafka_t *rk, int err, const char *reason, void *opaque) {
	printf("ERROR!\n");
}


int main (int argc, char **argv)
{
	int i;
	int x = 0;
	int jjj=5;

	//********** KAFKA
	rd_kafka_conf_t *conf;
	rd_kafka_topic_conf_t *topic_conf;

	static rd_kafka_t *rk;
	rd_kafka_topic_t *rkt;

	char errstr[512];

	unsigned long counter=0;

	int partition = RD_KAFKA_PARTITION_UA;

	struct timespec slptm;
	slptm.tv_sec = 0;
	slptm.tv_nsec = usleep * 1000000;      //1000 ns = 1 us

	quiet = !isatty(0);

	int ret = initLog("init/kafka_runtime.ini", "common");

	ini_parse("init/kafka_runtime.ini", applicationInihandler, NULL);

	// KAFKA CONF
	conf = rd_kafka_conf_new();



	/* Producer config */
	rd_kafka_conf_set(conf, "queue.buffering.max.messages", "600000", NULL, 0);
	rd_kafka_conf_set(conf, "message.send.max.retries", "3", NULL, 0);
	rd_kafka_conf_set(conf, "retry.backoff.ms", "1000", NULL, 0);
	rd_kafka_conf_set(conf, "socket.keepalive.enable", "true", NULL, 0);
	rd_kafka_conf_set(conf, "request.required.acks", "0", NULL, 0);
	rd_kafka_conf_set(conf, "queue.buffering.max.ms", "1000", NULL, 0);
	rd_kafka_conf_set(conf, "batch.num.messages", "0", NULL, 0);


	topic_conf = rd_kafka_topic_conf_new();



		/*
		 * Producer
		 */
		char buf[2048];
		int sendcnt = 0;
		int messageCounter=10;

		rd_kafka_conf_set_error_cb(conf, err_cb);

		rd_kafka_conf_set_dr_msg_cb(conf, msg_delivered);

		/* Create Kafka handle */
		if (!(rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf, errstr, sizeof(errstr)))) {
			fprintf(stderr, "%% Failed to create new producer: %s\n", errstr);
			exit(1);
		}

		/* Set logger */
		rd_kafka_set_logger(rk, logger);
		rd_kafka_set_log_level(rk, 1);

		/* Add brokers */
		if (rd_kafka_brokers_add(rk, brokers) == 0) {
			fprintf(stderr, "%% No valid brokers specified\n");
			exit(1);
		}

		/* Create topic */
		rkt = rd_kafka_topic_new(rk, topic, topic_conf);


		while (messageCounter>0) {

			sprintf(buf, "MESSAGE (%d)", messageCounter);

				size_t len = strlen(buf);
				if (buf[len - 1] == '\n')
					buf[--len] = '\0';

				/* Send/Produce message. */

				int prod_result=rd_kafka_produce(rkt, partition, RD_KAFKA_MSG_F_COPY,
						/* Payload and length */
						buf, len,
						/* Optional key and its length */
						NULL, 0,
						/* Message opaque, provided in
						 * delivery report callback as
						 * msg_opaque. */
						NULL);

				printf("Produce return code: %d\n", prod_result);

				if (prod_result == -1) {
					printf("Error on rd_kafka_produce function call\n");

					/* Poll to handle delivery reports */
					rd_kafka_poll(rk, 0);
					run=0;
					continue;
				}

			    printf("%% ***** (%lu) Sent %s to topic %s *****\n", counter, buf, topic);

				sendcnt++;
				counter++;
				/* Poll to handle delivery reports */
				rd_kafka_poll(rk, 0);


			messageCounter--;

		}


		/* Poll to handle delivery reports */
		rd_kafka_poll(rk, 0);



		int outq=1;

		while (outq > 0) {

			outq = rd_kafka_outq_len(rk);

			printf("%% %i messages in outq\n", outq);

			printf("\n Queue is NOT empty... still waiting!\n\n");

			msSleep(5000);

			rd_kafka_poll(rk, 0);

		}

		printf("Done!");
}
````
------------------------------------------------------------------------------------------------------

here is the output of my script:
````
Produce return code: 0
% ***** (0) Sent MESSAGE (10) to topic bucksense_test *****
Produce return code: 0
% ***** (1) Sent MESSAGE (9) to topic bucksense_test *****
Produce return code: 0
% ***** (2) Sent MESSAGE (8) to topic bucksense_test *****
Produce return code: 0
% ***** (3) Sent MESSAGE (7) to topic bucksense_test *****
Produce return code: 0
% ***** (4) Sent MESSAGE (6) to topic bucksense_test *****
Produce return code: 0
% ***** (5) Sent MESSAGE (5) to topic bucksense_test *****
Produce return code: 0
% ***** (6) Sent MESSAGE (4) to topic bucksense_test *****
Produce return code: 0
% ***** (7) Sent MESSAGE (3) to topic bucksense_test *****
Produce return code: 0
% ***** (8) Sent MESSAGE (2) to topic bucksense_test *****
Produce return code: 0
% ***** (9) Sent MESSAGE (1) to topic bucksense_test *****

% 10 messages in outq

 Queue is NOT empty... still waiting!

SENT: MESSAGE (9)
SENT: MESSAGE (5)
SENT: MESSAGE (4)
SENT: MESSAGE (3)
SENT: MESSAGE (10)
SENT: MESSAGE (7)
SENT: MESSAGE (6)
SENT: MESSAGE (2)
SENT: MESSAGE (1)
% 1 messages in outq

 Queue is NOT empty... still waiting!

% 1 messages in outq

 Queue is NOT empty... still waiting!

% 1 messages in outq

 Queue is NOT empty... still waiting!

% 1 messages in outq

 Queue is NOT empty... still waiting!

% 1 messages in outq

 Queue is NOT empty... still waiting!
 
```` 
 ... and so on...
 
 ------------------------------------------------------------------------------------------------------
 
 here is consumer side output:
 ````
 MESSAGE (9)
MESSAGE (5)
MESSAGE (4)
MESSAGE (3)
MESSAGE (10)
MESSAGE (7)
MESSAGE (6)
MESSAGE (2)
MESSAGE (1)
````
------------------------------------------------------------------------------------------------------

As you can see, message number 8 is missing.

After I was doing many tentatives, I have seen that is ALWAYS the message number 8 the only one it misses. How is it possible?

I would be really grateful if you help me

Thanks

Fabrizio

**Comment by edenhill** [comment]
Hi,
thanks for the detailed bug report!

* How many partitions do you have for your topic?
* Do all partitions have a leader broker?
* Have you run this with debugging enabled? (property `debug=topic.msg`)
* You could try adding a call to `rd_kafka_dump()` in your outq loop, it will describe the state of the various internal queues and let us know where the 8th message is residing.
* If you set `partition` to 0 or other available partition, are all messages sent?



**Minor detail**
The kafka message is not null-terminated so this printout is unsafe:
````
static void msg_delivered (rd_kafka_t *rk,
                           const rd_kafka_message_t *rkmessage, void *opaque) {
    printf("SENT: %s\n",  (const char *)rkmessage->payload);
}
````

Change it to this to make it safe:
````
    printf("SENT: %.*s\n",  (int)rkmessage->len, (const char *)rkmessage->payload);
````

**Comment by raven1978** [comment]
Hi,

thanks for the response.

in fact it seems that partions number on kafka broker is 3, but the second partition has no leader.

Forcing producer to first partition, it seemed to work fine and every message has been consumed.

Thanks also for the advice about print unsafe.

Fabrizio

**Comment by raven1978** [comment]
sorry, another little question.

is there a  function used to set an error callback that manage the payload message (i.e. rd_kafka_conf_set_error_msg_cb)?
So I can implement a retry feature. Or retry mechanism is always implicit?

I saw and I used **rd_kafka_conf_set(conf, "message.send.max.retries", "3", NULL, 0);** and **rd_kafka_conf_set(conf, "retry.backoff.ms", "1000", NULL, 0);** function calls, but i wonder if there is a way to manage each retry out of library.

Thanks again

**Comment by edenhill** [comment]
Per-message delivery errors are reported by the delivery report callback (`dr_cb` or `dr_msg_cb`) when the `err` argument is non-zero.

You should typically let librdkafka perform the retries internally (which it does by default) because it has a clearer picture of what went wrong and will only retry on non-permanent errors.
A permanent error is the topic or partition not existing.
Having said that you can still re-produce your message as you see fit in you get an error for it in the delivery report callback.
