### ISSUE TITLE
detecting connection failures in producer

### ISSUE THREAD

**Issue by benp20** [edenhill/librdkafka#2062]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi,
I'd like to know the recommended procedure for detecting connection failures while setting  up a producer.

Looking at the simple producer example, I see these two main function calls

       if (rd_kafka_conf_set(conf, "bootstrap.servers", brokers,
                              errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK) {
                fprintf(stderr, "%s\n", errstr);
                return 1;
        }

        rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf, errstr, sizeof(errstr));
        if (!rk) {
                fprintf(stderr,
                        "%% Failed to create new producer: %s\n", errstr);
                return 1;
        }

I notice that even if the addresses of my brokers are incorrect, these calls succeed and so I am unable to tell that the connection actually failed (I do see log entries indicating connection failures). I am wondering what is the right technique to  detect these failures while setting up the producer.

One option I considered is to use an error callback.
But in that case, I would imagine that I do not  get a  callback in case of  successful connection, and so I do not  know how  long to wait for  an error to determine if the connection did indeed succeed.

Also, I do see failures reported during send  eventually, but I'd like  to catch this before.

librdkafka version (release number or git tag): v11
Operating system: ubuntu 16.04

Thanks,
Ben

How to reproduce
================
Run simply producer passing an incorrect broker address. 
No error is reported while creating the rdkafka object or topic.

 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v11
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: default
 - [ ] Operating system: ubuntu 16.04
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Connections are performed asynchronously in the background.
You will get an ERR__RESOLVE error event (error_cb, or error event, or log message) if resolution fails, or ERR__TRANSPORT if the connection fails.

**Comment by benp20** [comment]
Thanks.
Is there a way to get a callback in case the connection succeeded. Without that, the application is not sure for how long to wait for an error message by way of callback.

Also, I notice that resolution errors are taking 20+ seconds to show up by way of callback from the time  the rd_kafka_new method is called, even though I keep calling rd_kafka_poll. Any idea why it might be taking that long? Is there a configuration parameter I can tweak to make this short (like a few hundred milliseconds as is the case with a regular socket connect)?

**Comment by edenhill** [comment]
There is currently no signaling of connection status, and the application really shouldn't care.

When producing messages you give constraints to the producer:
 * how long it will try to delivery your message (`message.timeout.ms`)
 * and how many retries it may attempt (`retries`).

When either of those two are exceeded the message will fail and you will get the delivery report callback  (from poll()).
Of course, if the message is delivered successfully before that you will get a successful delivery report sooner.

There is an ERR_ALL_BROKERS_DOWN event that allows you to detect when the client can't connect to any broker.

**Comment by edenhill** [comment]
Is it possible that resolving the broker address takes 20s?

**Comment by prashankmehta** [comment]
I am facing a similar issue. For instance, when I try to connect Production broker from Dev box, it takes around 60 sec to receive an error ERR_ALL_BROKERS_DOWN and ERR__TRANSPORT on event_cb.  During this period, the application thinks it is connected and keeps producing data. These messages will never reach Kafka. The telnet connection failure is quicker.
Most of the global config constraints/properties are set to default for my Producer. 

**The ideal thing should be an option to make a synchronous call to check broker status.**

**Comment by edenhill** [comment]
Problem is there is no such thing as "broker status" in a Kafka cluster.
A consumer will need to speak to a group coordinator, and the leaders for the partitions it wants to consume.
A producer will need to speak to the leaders for the partitions it wants to produce to.

Will the consumer be operational if it can read 2/3 partitions?
Will the producer be operational if it can write to 2/3 partitions?

Is slowness to connect a fatal error? What's the definition of slow?
How much time should be allowed to try a connection before moving on?
The delay of ALL_BROKERS_DOWN is the connection failure/timeout time (which will vary depending on reason) * the number of brokers. More aggressive timeouts might mean we fail a connection attempt that would have been successful if we would have just waited a bit longer.

What if there is a temporary outage, should all clients fail?

The answers to all these questions are: it depends - on your infrastructure, data contracts, etc.

If you want to conceive your own logic you could register a stats_cb and parse the JSON to get per-broker states, see https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md 

But my recommendation is not to think of this problem as a connectivity or broker problem, but rather a data problem:
 * Consumer: if less than P% of the expected data rate has been received in the last X minutes, something is wrong.
 * Producer: if more than P% of messages failed producing during the last X minutes, something is wrong.

**Comment by prashankmehta** [comment]
The delayed timeout was due to the firewall on my system. 
Thank you Edenhill for your time and response.
