### ISSUE TITLE
possible memory leaks using ssl transport

### ISSUE THREAD

**Issue by jcalcote** [edenhill/librdkafka#2064]
Hi Magnus, 

My company has been using kafka for some time now, and we have a few components written in C and C++ so we've been using librdkakfa. We've had a pretty good handle on memory usage and pooling within librdkafka (thanks to your valgrind exception list). 

Recently we added some sensitive data to our kafka topics and switched to using tls-encrypted transports. Suddenly, we're seeing a large bump in apparent leaks in ssl libraries where the calls were arrived at through librdkafka call stacks.

Are you aware of any memory leak issues in librdkafka that are specific to using SSL/TLS transport?

If you say there may be issues, I'll start digging into valgrind logs and posting more data on this issue.

Thanks in advance,
John

**Comment by edenhill** [comment]
Hey,

we don't know of any such issues.
Which OpenSSL version are you on?

valgrind will definitely help, or compile with --fsanitize=address
