### ISSUE TITLE
Be informed on partition changes (producer).

### ISSUE THREAD

**Issue by nilsocket** [edenhill/librdkafka#2069]
1. Any possibility of being informed, in-case any partition changes for a topic. (using producer API)

2. In consumer API, rebalance callback is  not being called, I don't need the messages from consumer, but I want to be informed of any changes to partition.

3. Metadata has many other fields which were unnecessary for me, querying metadata before producing message would be too costly.

4. I need to read the last message from a single partitioned topic, when my program starts. Is it better to use `assign()` or `consume()`. (I read the message last message and close the consumer).

Thank you.

**Comment by edenhill** [comment]
## 1
There is currently no topic change monitoring interface, you have two options:
 * periodically call rd_kafka_metadata() and compare to the previous result
 * register a statistics callback, set statistics.interval.ms, and compare the topic/partition information. https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

## 2
If your rebalance callback is not being called but you are able to consume messages (some time) after subscribe() then there's something wrong with your rebalance callback setup. Look at the examples/.
If your rebalance callback is not beign called and you are not seeing any messages then your consumer probably fails to join the group or fails to get an assignment. Troubleshoot by setting `debug` to `cgrp` or `consumer`.

## 3
You definitely don't want to query metadata for each message produced, that would be very slow.
What exactly is it that you are trying to do?

## 4
You can set the start offset (by setting `topic_partition_t.offset = RD_KAFKA_OFFSET_TAIL(1)`) for each partition in the assignment in the rebalance callback. You should probably set enable.auto.commits=false if you don't want to resume from committed offsets.

**Comment by nilsocket** [comment]
My application have high chances of crashing, and I shouldn't resend messages to Kafka stream.

So I create a consumer and read last message and close the consumer. (this is done only on start-up)

Based upon the last message I resume my work.

Another requirement if no.of partitions in a topic to which I produce is increased, then I need to shutdown my application.
