### ISSUE TITLE
Get Assigned Partitions when using subscribe

### ISSUE THREAD

**Issue by vvadan** [edenhill/librdkafka#2070]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

I have multiple consumers subscribing to a single topic (with multiple partitions).
Once the subscribe is successful, I want to check the assigned partitions to that consumer.
I see that there is an assignment() call, but that can be only used in conjunction with assign() call.

How can I get the assigned partitions of a consumer, when subscribed to a topic using subscribe() ?
FYI, Iam using high level consumer with C++.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.5`
 - [ ] Apache Kafka version: `2.0.0`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `RHEL 7.4`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
assignment() will return the current assignment, but since subscribe() is asynchronous (it initiates the group join, but the join and rebalance is taking place in the background) you will not have an assignment directly after calling subscribe().
What you can is register a rebalance callback which will give you assigned partitions when the rebalance happens, just make sure to call assign() and unassign() according to the rebalance callback documentation.
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L689

**Comment by vvadan** [comment]
Thanks @edenhill, I am using the callback for the rebalance already and doing the steps as documented.
But was wondering if there is any function call right after the subscribe, so that I can have the partition information. Thanks anyway.

**Comment by pratikthakkar24** [comment]
Hey @vvadan did you get the solution for your query ?

**Comment by pratikthakkar24** [comment]
Hello @edenhill ,
I have registered the callback for rebalance (_**rebalance_cb**_), but my callback is getting called (triggered) only after producing the first message from the producer. My rebalance callback is not getting called (triggered) upon calling subscribe() with the set of topics.
Even if my consumer waits for a lot of time after successfully calling subscribe() with the set of topics, the rebalance callback gets called only after producing the first message from producer.
Is this the way how rebalance callback of kafka works (it gets called only after producing some messages on the topic)?
