### ISSUE TITLE
Fencing across Consumer::stop()

### ISSUE THREAD

**Issue by tudor** [edenhill/librdkafka#2073]
Description
===========

I am having a somewhat unusual use case, and I'm wondering what would be the best way to use librdkafka for my purposes. I will describe my use case, our current implementation, the problems we have with it, what I've tried, and the (small) features that I would like to see in librdkafka to help me.

I have C++ server processes that act as a Kafka consumers for a relatively large number (roughly 250) of toppars each. The mapping from toppar to server process is external and explicit; I don't need consumer groups or automatic rebalancing. Also, Kafka is (essentially) used as a transaction log for a database, so I don't need to commit offsets to Kafka -- they're written into my own stable storage.

It is also possible (albeit unlikely) that the server process needs to subscribe more than once to the same toppar, with different running offsets.

The current implementation multiplexes to a small set of (old-style) `Consumer` objects. There is usually only one `Consumer` object, unless we need to subscribe more than once to the same toppar, in which case we create more than one. (The maximum number of `Consumer` objects is equal to the maximum number of subscriptions to the same toppar, which is usually 1 or 2 in a process, so this works out.)

Toppar assignments do change dynamically, so I prefer the old-style `Consumer` rather than `KafkaConsumer` interface, as it's easy to add / drop one single toppar from the assignment list; `KafkaConsumer` would force me to provide the full assignment list on each change, with correct offsets, and I assume that would cause unnecessary work (and unnecessary broker traffic).

We do, however, have one dedicated thread consuming for each subscription, and 250 threads is quite a lot in this use case, so I'd like to move to a design where we consume from a small (and configurable) number of threads.

I would like to forward all subscriptions to a librdkafka `Queue`, with those consumer threads blocked on the same `Queue`'s `consume()` method.

That works, except that I don't really know how to stop consuming on one toppar.

Let's say I call `Consumer::stop` for a toppar. There are likely some messages for that toppar that have already been enqueued in the `Queue`; I would like to either wait until those messages are processed, or somehow ensure that they won't be processed, but I currently have no way of knowing how many messages there are.

I can ignore messages from toppars that I'm not currently subscribed to, but I could want the same `Consumer` to resubscribe to the same toppar (at a different offset), and now the `Queue` may contain message from different "generations" of subscriptions to the same toppar, and things get weird.

Here are a few options, in order of preference:

1. Add a "cookie" (generation count, random identifier, etc) to all messages consumed from one toppar. The call to `Consumer::start` could give me a way to add some (opaque) cookie; the cookie would then be returned in every consumed `Message`. The consumer threads could then ignore the cookies that I don't recognize. The C API's `rkt_opaque` in in the `rd_kafka_topic_t` object would be perfect for this purpose, but, unfortunately, the C++ API hijacks it for its own purpose (storing a pointer to the `TopicImpl` wrapper object).

2. `Consumer::stop()` could return the offset of the last message from that toppar (atomically with stopping the fetch for that toppar). Then, after calling `Consumer::stop()`, I could wait until all messages up to that offset have been processed.

3. `Queue` could give me the number of messages currently in the queue. (This information is already in the C API, but not in the C++ API). I can then wait until that number of messages have been processed before declaring my stop operation complete. This is overly conservative (it waits until more work is done than strictly necessary), requires some overly coarse locking and/or very careful ordering of atomic reads, especially in the presence of multiple consumer threads, but I believe it would be workable.

4. I could wrap the C API directly instead of the C++ API, in which case I could use `rkt_opaque`, implementing solution 1, and be done with it.

I would love to hear your thoughts and suggestions.

Thank you!

cc: @igorcanadi

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.6`
 - [x] Apache Kafka version: `2.0.0`
 - [x] librdkafka client configuration: N/A
 - [x] Operating system: `Ubuntu 18.04`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: N/A
 - [x] Provide broker log excerpts: N/A
 - [ ] Critical issue

**Comment by edenhill** [comment]
> Let's say I call Consumer::stop for a toppar. There are likely some messages for that toppar that have already been enqueued in the Queue; I would like to either wait until those messages are processed, or somehow ensure that they won't be processed, but I currently have no way of knowing how many messages there are.

Did you try this because this should work as it is?
Whenever a partition is started, seeked, stopped, paused, an internal version is bumped on the partition. This invalidates all queued messages for that partition with an older version, which are filtered out lazily as you call poll/consume/whatever.
So what you describe should work out of the box, and if not there's a bug that we need to fix.
The use of C or C++ API should not matter, this is all in the librdkafka internals.

If you run your application with `debug=topic` you should see messages like:
`FETCH: .. Start fetch for sometopic [3] in state ... (v4)` where `v4` is the new the partition version/generation/epoch.
And for stop:
`FETCH: .. Stopping fetch for .. in state .. (v4)`.

**Comment by tudor** [comment]
> Whenever a partition is started, seeked, stopped, paused, an internal version is bumped on the partition. This invalidates all queued messages for that partition with an older version, which are filtered out lazily as you call poll/consume/whatever.

That's great. Thank you!

Do I have to reuse the same `rd_kafka_topic_t` object when resubscribing, though? (Instead of a newly created one with the same name). From my (cursory) reading of the code, it seems that, if I use a different `rd_kafka_topic_t` object, the version number would reset to 1. (Then, my question becomes "how do I know when it's safe to delete the `Topic` objects"?)

**Comment by edenhill** [comment]
No, you can destroy the existing rd_kafka_topic_t object and re-recreate it with rd_kafka_topic_new() when you need it the next time. The object will be the same, it is internally refcounted and currently never goes to zero (regardless of no more app references) until the client terminates (but do acquire your own reference to it thru _new()!).

**Comment by tudor** [comment]
Ah, neat. This seems to meet my needs perfectly. Thank you!
