### ISSUE TITLE
producer Local:Queue full

### ISSUE THREAD

**Issue by zhuxiufenghust** [edenhill/librdkafka#2074]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
producer write topic with many Local:Queue full logs like below
kafka_producer.go:236|public_msg_failed|error=Local: Queue full
partition_id is calculated by key_hash mannually.

How to reproduce
================
in company internal circumstance

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0725ba43bef93568bb89402e2117c07375fcd2fa`
 - [x] Apache Kafka version: `0.8`
 - [x] librdkafka client configuration: ``
	bufferSize := 100000
	bufferTime := 50
	producer.raw, err = kafka.NewProducer(&kafka.ConfigMap{
		"queue.buffering.max.messages": bufferSize,
		"queue.buffering.max.ms":       bufferTime,
		"compression.codec":            "gzip",
		"message.max.bytes":            81943040,
		"metadata.broker.list":         brokers,
		"go.delivery.reports":          false,
		"default.topic.config": kafka.ConfigMap{
			"produce.offset.report": false,
		},
		"log_level":7,
		"debug":"msg,topic,protocol,broker",
	})
 - [x] Operating system: `ubuntu 16.04`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
%7|1540527118.414|TOPPAR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 21 message(s) queued but broker not up
%7|1540527118.414|TOPPAR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 11932 message(s) queued but broker not up
%7|1540527118.414|TOPPAR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 4270 message(s) queued but broker not up
%7|1540527118.414|TOPPAR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 878 message(s) queued but broker not up
%7|1540527118.414|TOPPAR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 4752 message(s) queued but broker not up
%7|1540527118.414|TOPPAR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 1881 message(s) queued but broker not up
%7|1540527118.414|TOPPAR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 907 message(s) queued but broker not up
%7|1540527118.414|TOPPAR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 2277 message(s) queued but broker not up
%7|1540527118.414|TOPPAR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 79 message(s) queued but broker not up
%7|1540527118.414|TOPPAR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 1065 message(s) queued but broker not up

%3|1540528201.180|ERROR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 7 request(s) timed out: disconnect (after 43924ms in state UP)
%3|1540528204.881|ERROR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 1 request(s) timed out: disconnect (after 3666ms in state UP)
%3|1540528249.375|ERROR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 7 request(s) timed out: disconnect (after 44490ms in state UP)
%3|1540528301.295|ERROR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 14 request(s) timed out: disconnect (after 51888ms in state UP)
%3|1540528329.626|ERROR|rdkafka#producer-1| [thrd:10.65.235.32:9092/bootstrap]: 10.65.235.32:9092/32: 10 request(s) timed out: disconnect (after 28296ms in state UP)
 - [] Provide broker log excerpts
 - [] Critical issue

**Comment by edenhill** [comment]
Looks like a connectivity or broker problem, the broker is not up or the client is being disconnected.

**Comment by zhuxiufenghust** [comment]
yes, broker is alive but not healthy, one  partition is too big to slow down the broker's performance.
