### ISSUE TITLE
Memory consumption on slow consumer

### ISSUE THREAD

**Issue by amircodota** [edenhill/librdkafka#2076]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I'm using node-rdkafka, and have encountered an issue where memory just blows up in seconds, even if I set queued.min.messages to a low number (say, 10 or even 1).
After investigation, I believe the issue is in librdkafka and not in the nodejs wrapper.

My use case is that I have a topic that already has a large number of pretty large messages, and now I have a consumer that consumes them. The topic has many partitions.
The consumer processes messages in parallel, so it would read a batch of messages (say 10), process them in parallel and then consume the next batch.
Each message might take a little while to process (say, 1 second), so this is a pretty slow consumer.

I've done some tests, using librdkafka. I've filled a topic with 10000 messages of 1 MB each, compressed.
1. If a consumer reads a message, waits 1 second, and consumes the next in a loop, memory blows up (in seconds, you should see the process memory goes up to gigs of RAM).
2. If we set the queued.min.messages to 10, memory is stable again.
3. If a consumer reads 10 messages, waits 1 second, and then consumes another 10 in a loop, memory blows up even if we set queued.min.messages to 10.

How to reproduce
================
Create a topic named "mem-issue-test" with 100 partitions.

```
bin/kafka-topics.sh --create --zookeeper localhost:2181 --partitions 100 --replication-factor 1 --topic mem-issue-test
```

Fill the topic with 10000 messages, of size 1000000 bytes, compressed with gzip.

Run the following consumer. You should see the process memory go up very quickly

```c++
#include <iostream>
#include <string>
#include <cstdlib>
#include <cstdio>
#include <csignal>
#include <cstring>
#include <unistd.h>
#include "rdkafkacpp.h"

static long msg_cnt = 0;
static bool run = true;

void msg_consume(RdKafka::Message* message, void* opaque) {
  std::cout << "Received Message" << message->errstr() << std::endl;
  switch (message->err()) {
    case RdKafka::ERR__TIMED_OUT:
      std::cout << "Timed out" << std::endl;
      break;

    case RdKafka::ERR_NO_ERROR:
      /* Real message */
      msg_cnt++;
	  printf("Got message of length %d\n",
           static_cast<int>(message->len()));
	  sleep(1);
      break;

    default:
      /* Errors */
      std::cerr << "Consume failed: " << message->errstr() << std::endl;
      run = false;
  }
}

int main() {
  std::string brokers = "localhost";
  std::string errstr;
  RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
  RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

  if (conf->set("group.id", "amir_gid5", errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }
  
  if (conf->set("metadata.broker.list", brokers, errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }

  if (conf->set("queued.min.messages", "10", errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }

  if (tconf->set("auto.offset.reset", "earliest", errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }

  if (conf->set("default_topic_conf", tconf, errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }

  delete tconf;

  RdKafka::KafkaConsumer *consumer = RdKafka::KafkaConsumer::create(conf, errstr);
  if (!consumer) {
    std::cerr << "Failed to create consumer: " << errstr << std::endl;
    exit(1);
  }

  delete conf;

  std::cout << "% Created consumer " << consumer->name() << std::endl;

  std::vector<std::string> topics;
  topics.push_back("mem-issue-test");

  RdKafka::ErrorCode err = consumer->subscribe(topics);
  if (err) {
    std::cerr << "Failed to subscribe to topics: "
              << RdKafka::err2str(err) << std::endl;
    exit(1);
  }

  while (run) {
    RdKafka::Message *msg = NULL;
    for (int i = 0; i < 10; i++) {
      if (msg) delete msg;
       msg = consumer->consume(1000);      
    }

    msg_consume(msg, NULL);

    delete msg;
  }

  return(0);
}
```

A few notes:
1. I used both a local kafka, version 0.10.1, and a remote kafka version 2.0, and it reproduced on both.
2. If you change the loop inside `while(run)` to only loop once, memory seems stable. If I comment out setting queued.min.messages to 10, memory blows up even when consuming one message at a time.

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): Reproduced on both 0.11.5, 0.11.6 and master, which is currently 0725ba43bef93568bb89402e2117c07375fcd2fa
 - [x] Apache Kafka version: Tested on both 0.10.1 and 2.0, reproduced on both
 - [ ] librdkafka client configuration: see my consumer code
 - [x] Operating system: Ubuntu 18.04
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

Will really appreciate your advice on this.
It is a critical issue for us, and prevents us from going live with our kafka pipeline.

Regards
Amir

**Comment by edenhill** [comment]
This is probably of interest:
https://github.com/edenhill/librdkafka/wiki/FAQ#explain-the-consumers-memory-usage-to-me

**Comment by edenhill** [comment]
Okay, so what I think is happening here is:
 1. the compression ratio is good
 2. thanks to the good compression, a FetchRequest to the broker will return multiple messages and for multiple partitions
 3. say you have 3 brokers handling your topic, that is ~30 partitions per broker. A fetch request may thus return messages for up to 30 partitions, each one of 1 MB uncompressed.
 4. as soon as the fetch response is received, the compressed messages are uncompressed and put on the internal fetchq for the application to consume. The queue limit is immediately exceeded and the fetcher stops.
 5. when the application has consumed some messages the watermark goes below the queued.min.messages threshold and the fetcher starts again
 6. another 30 partitions are fetched... goto 2

Did you try setting queued.max.message.kbytes to avoid more messages being fetched?

**Comment by amircodota** [comment]
Hi, edenhill

Really appreciate you taking the time to respond and troubleshoot with me.

I've set queued.max.messages.kbytes to 12000 (meaning ~12MB of RAM if I understand correctly).

Did not make a difference.

Is this limit global or per partition? What about queued.min.messages - is it per partition?

Not sure I understand why this would change anything. I mean, the fetcher would only ever fetch when there are 10 messages or less in the queue, which amounts in my case to 10MB of RAM. Why would memory keep growing, regardless of queued.max.messages.kbytes?

Thanks
Amir

**Comment by amircodota** [comment]
Here's something that might help explain.
I do not fully understand what's going on, but maybe it will help you :-)

I created another topic, with exactly the same messages but without the compression.

At first when I run it, I get

%3|1540713078.983|FAIL|rdkafka#consumer-1| [thrd:amir-XPS-13-9360:9092/0]: amir-XPS-13-9360:9092/0: Receive failed: Invalid response size 104859433 (0..100000000): increase receive.message.max.bytes (after 2001ms in state UP)

Then I upped receive.message.max.bytes (to 110000000).
And then it runs correctly with memory stable at around 110MB of RAM.

So it seems you were right about compression being the cause of this.
Is it possible that I am getting 100MB of compressed data - when decompressed gets to be Gigs of RAM?
If that's the case, how would you fix it? Please take into account that while in the test all messages are 1MB, in reality the size and compression rate can vary greatly, and in extreme cases, a single message can be a few MB of compressed data.

Thanks a lot
Amir

**Comment by edenhill** [comment]
You can limit the amount of data requested from the broker with:
 * `fetch.max.bytes` - cap for all requested partitions in the FetchRequest
 * `fetch.message.max.bytes` - cap for each partition in FetchRequest

Do note that this corresponds to compressed data, and these values will be automatically adjusted upwards until one complete batch of messages can be retrieved.

**Comment by amircodota** [comment]
Tried reducing both these configs, but it does not seem to have any effect.

Enabled debugging - maybe this will help?

[out.txt](https://github.com/edenhill/librdkafka/files/2523142/out.txt)

**Comment by amircodota** [comment]
I've played with several. Here's the smallest I've tried

fetch.max.bytes = 1000000
fetch.message.max.bytes = 100000

**Comment by edenhill** [comment]
Any progress on this from your side?

**Comment by amircodota** [comment]
Yes, I managed to get it to work.

The key parameters that worked for me were - 
queued.min.messages = 10 (a much lower number than the default)
fetch.message.max.bytes = 10000 (a much lower number than the default)

rdkafka will increase fetch.message.max.bytes if its not enough, but since my relatively big messages compressed very well, it is usually enough keeping the memory stable.

Thanks for your assistance, and sorry I did not report this sooner.

**Comment by yanqi321** [comment]
Did you solved the problem by setting limit of memory ?
```
fetch.max.bytes = 1000000
fetch.message.max.bytes = 100000
```
it met the same problem ,Could yout help me?

**Comment by amircodota** [comment]
It has been a while, but if I remember correctly, what made the difference was setting 
queued.min.messages 
to a small number.
Otherwise rdkafka keeps fetching more and more messages to fill its internal buffer

**Comment by yanqi321** [comment]
Thank you so much, @amircodota , I set the config as you told:
```
'queued.min.messages': 10,
'queued.max.messages.kbytes': Math.floor(800 * 1024)
```
it Solve the problem that has plagued me for several days.
Mybe the default value of 'queued.min.messages' is 100000 that made the config fetch.message.max.bytes not work?
