### ISSUE TITLE
Same partitions assigned to multiple consumers of same consumer group on first rebalance

### ISSUE THREAD

**Issue by Sigmundsdottir** [edenhill/librdkafka#2079]
A topic is created with 5 partitions.
A consumer is started which subscribes on the topic and receives rebalance_cb with 5 partitions from 0 to 4.
In rebalance_cb, consumer assigns the newly received partitions to itself using librdkafka's assign() method and starts to restores it's state for the newly assigned partitions that is a time consuming process, and may takes upto minutes.
NOTE: While the consumer is trying to restore it's state it cannot consume new messages as it will lead to discrepancy in the system's state.

If during this time another consumer is started with same kafka settings, it is observed that the second consumer as well receives the assign rebalance_cb of all the 5 partitions( 0 to 4 ).

Now, both consumers have same partitions assigned to them and they are restoring there states for all the partitions. However, it was expected if some partitions are assigned to one of the consumer, they should not get assigned to another instance before they are revoked.

How to reproduce
================
Step 1: Start consumer 1, it is observed that 0 to 4 partitions are assigned.
             Consumer 1 assigns the partitions to itself by making a call to assign() method provided 
             by librdkafka and, starts to process some time consuming task inside the rebalance_cb.

Step 2: Start consumer 2, it is observed that 0 to 4 partitions are assigned to the consumer 2 as well.
             At this moment consumer 2, starts to follow the same process as of consumer 1. 
             This leads to discrepancy in our business logic, as it is not expected that same partition with 
            same consumer group will be assigned over multiple consumers.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.6`
 - [x] Apache Kafka version: `2.11-1.1.0`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `CentOS Linux release 7.5.1804 (Core)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
I would guess the group rebalances while the first consumer is ramping up, a rebalance_cb is triggered but since the application is busy ramping up it probably isn't calling poll() to see it, as the session.timeout.ms expires the consumer is deemed dead by the group coordinator and the partitions are assigned to other members of the group.

[KIP-62](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread), which is scheduled for v1.0.0 (in about a months time), might help with this situation.

**Comment by Sigmundsdottir** [comment]
Thanks for the quick response.

As an alternative solution for now, we are using pause and resume functionality of consumer rather than increasing session.timeout.ms as it might lead to system being unavailable for long duration in case of any network issues.

Detailed Steps:
Step 1: Start consuming messages using consume method.
Step 2: In rebalance_cb assign, use the pause method to stop processing any new messages from the assigned partitions that are not in sync to consumer.
Step 3: Keep consuming messages using consume() method.
Step 4: After consumer poll timeout has reached of consume() method, check if the system has synced in respect to any of the assigned partitions(will always complete before session timeout).
Step 5: If yes, use resume() method to resume processing from the synced partition.
             If no, move to step 3.

As tested, we are able to achieve the desired functionality needed. Is it safe to use this logic in production or is there any other better alternative that can be taken at this stage?

**Comment by edenhill** [comment]
I don't see how the group synchronization is performed with your suggested solution.
Strongly suggest you look into KIP-62 / max.poll.interval.ms, that is being released with librdkafka v1.0.0 (try it on master branch)

**Comment by Sigmundsdottir** [comment]
Thank you @edenhill  for your time. 
I will test it on v1.0.0. and revert back on this thread.
For the time being, Closing the issue.
