### ISSUE TITLE
When did request.required.acks change??

### ISSUE THREAD

**Issue by winbatch** [edenhill/librdkafka#208]
This used to represent the number of brokers to wait on.  I used to set it to 2.  Now it won't let me?

Configuration property "request.required.acks" value 2 is outside allowed range -1..1

How do I indicate as I used to (in 0.8.4) that I want two brokers to come back to me?  I consider this to be an API breaking change.  My use case is that there may be 3 ISR's but I want to make sure that 2 brokers got it.

**Comment by winbatch** [comment]
Looks like it was done here?
https://github.com/edenhill/librdkafka/commit/11e9d2a1ffde769f10588aa8a8cda49ee7a990f1

**Comment by edenhill** [comment]
See [KAFKA-5555](https://issues.apache.org/jira/browse/KAFKA-1555?focusedCommentId=14147394&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14147394) for the reasoning behind this.

**Comment by winbatch** [comment]
Is this for a particular broker version or applies to all .8?  If we are
still on .8.0 can I still use latest librdkafka and use the new
flags/logic?   If u was setting required.acks to 2 what do you recommend I
set now?

**Comment by edenhill** [comment]
Broker 0.8.2 added `min.insync.replicas` property that should be used in conjunction with the producer's `request.required.acks=-1`.

I can revert the narrowed config limits in librdkafka so that you can still use request.required.acks > 1 on older brokers.

**Comment by winbatch** [comment]
Thanks. If I keep the  2 and the broker gets upgraded later, will
everything break?

**Comment by edenhill** [comment]
I think the broker will allow values > 1 for 0.8.2 but fail the ProduceRequest in 0.8.3.
Make a note of changing to `min.insync.replicas=..` on the broker and setting `request.required.acks=-1` when upgrading.

**Comment by winbatch** [comment]
Thanks for the info.  This is going to be quite a challenge as we will want
to keep the same code base (this is deployed across hundreds/thousands of
machines) and I would imagine we won't be upgrading all clusters at the
same time.  Not your problem/fault of course.

**Comment by winbatch** [comment]
Is there any way in librdkafka it can let me know the broker version so I
can choose the right logic dynamically?

**Comment by edenhill** [comment]
Unfortunately not, I'd like to have that information as well but there is no such request :/
