### ISSUE TITLE
cppkafka::HandleException' what(): Local: Timed out Aborted (core dumped) rdkafka issue?

### ISSUE THREAD

**Issue by marcoippolito** [edenhill/librdkafka#2087]
Hi,
as described here: [https://github.com/mfontanini/cppkafka/issues/131](url)

this simple snippet outputs a core dumped exception:

    `#include <cppkafka/cppkafka.h>

    using namespace std;
    using namespace cppkafka;

    int main() {
      // Create the config
      Configuration config = {
        { "metadata.broker.list", "127.0.0.1:9092" }
      };
      // Create the producer
      Producer producer(config);
      // Produce a message!
      string message = "hey there!";
      producer.produce(MessageBuilder("my_topic").partition(0).payload(message));
      producer.flush();
      return 0;
    }
    `
According to Matias, the creator of cppkafka, the problem is likely to reside within rdkafka library.
So I kindly ask you to coordinate with him, in order to solve this problem, and may be, to set a a schedule for the advancement of both your important libraries.

Looking forward to your kind help.
Marco

**Comment by edenhill** [comment]
set `"debug": "msg,broker,topic"` to see what is going on

**Comment by marcoippolito** [comment]
Where to set the configuration for the debugging?
I tried few "options", but didn't find the proper syntax / way:

    #include <cppkafka/cppkafka.h>

    using namespace std;
    using namespace cppkafka;

    int main() {
      // Create the config
      //Configuration config = {
        //{ "metadata.broker.list", "127.0.0.1:9092"},
        //{ "msg", "broker", "topic"}
      //};

      //DebugConfiguration debug_configuration = {
        //{"msg","broker","topic"}
      //};
      //Configuration config = {
        //{ "metadata.broker.list", "127.0.0.1:9092", "msg", "broker", "topic"}
      //};
      //Configuratioon config = {
        //{ "metadata.broker.list", "127.0.0.1:9092", "debug"}
      //};

      Configuration config = {
        { "metadata.broker.list", "127.0.0.1:9092"}
      };

      // Create the producer
      Producer producer(config);
      // Produce a message!
      string message = "hey there!";
      producer.produce(MessageBuilder("my_topic").partition(0).payload(message));
      producer.flush();
      return 0;
    }

**Comment by mfontanini** [comment]
Okay this is not the most descriptive way of explaining what is going on. What seems to happen is sometimes you create a producer handle, produce a couple of messages and when you call flush on it, that returns connection timed out. I've seen this happening even when connecting to a broker in localhost. My theory is the connection is asynchronous and it takes longer for the connection to be established than for the messages to be produced.

**Comment by marcoippolito** [comment]
With this code:

    `#include <cppkafka/cppkafka.h>

    using namespace std;
    using namespace cppkafka;
    int main() {
      // Create the config
      Configuration config = {{ "metadata.broker.list", "127.0.0.1:9092"} , {"debug","all"}};
      // Create the producer
      Producer producer(config);
      // Produce a message!
      string message = "hey there!";
      producer.produce(MessageBuilder("my_topic").partition(0).payload(message));
      producer.flush();
      return 0;
    }
    `

The output when compiling is:
    `g++ -std=c++17 -lrdkafka -lpthread -lz -lstdc++ plain.cpp -lboost_program_options -lcppkafka 
    -oplain

    ./plain
    %7|1541520149.274|WAKEUPFD|rdkafka#producer-1| [thrd:app]: 127.0.0.1:9092/bootstrap: Enabled 
    low-latency ops queue wake-ups
    %7|1541520149.274|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker 
    thread
    %7|1541520149.275|BROKER|rdkafka#producer-1| [thrd:app]: 127.0.0.1:9092/bootstrap: Added new 
    broker with NodeId -1
    %7|1541520149.275|CONNECT|rdkafka#producer-1| [thrd:app]: 127.0.0.1:9092/bootstrap: Selected for   
    cluster connection: bootstrap servers added (broker has 0 connection attempt(s)
    %7|1541520149.275|BRKMAIN|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:   
    127.0.0.1:9092/bootstrap: Enter main broker thread
     %7|1541520149.275|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v1.0.0-RC2 (0x1000002)   
    rdkafka#producer-1 initialized (builtin.features 0xffff, debug 0xffff)
    %7|1541520149.275|CONNECT|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:    
    127.0.0.1:9092/bootstrap: Received CONNECT op
    %7|1541520149.275|STATE|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:    
    127.0.0.1:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
    %7|1541520149.275|BROADCAST|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]: Broadcasting 
    state change
    %7|1541520149.275|CONNECT|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:    
    127.0.0.1:9092/bootstrap: broker in state TRY_CONNECT connecting
    %7|1541520149.275|STATE|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:    
    127.0.0.1:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
    %7|1541520149.275|BROADCAST|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]: Broadcasting 
    state change
    %7|1541520149.275|TOPIC|rdkafka#producer-1| [thrd:app]: New local topic: my_topic
    %7|1541520149.275|CONNECT|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:    
    127.0.0.1:9092/bootstrap: Connecting to ipv4#127.0.0.1:9092 (plaintext) with socket 7
    %7|1541520149.275|BROKERFAIL|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:   
    127.0.0.1:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection refused)
     %3|1541520149.275|FAIL|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:    
    127.0.0.1:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state   
    CONNECT)
    %3|1541520149.275|ERROR|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:       
    127.0.0.1:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state 
    CONNECT)
    %7|1541520149.275|STATE|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:   
    127.0.0.1:9092/bootstrap: Broker changed state CONNECT -> DOWN
    %3|1541520149.275|ERROR|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]: 1/1 brokers are down
    %7|1541520149.275|BROADCAST|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]: Broadcasting 
    state change
    %7|1541520149.275|BUFQ|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:    
    127.0.0.1:9092/bootstrap: Purging bufq with 0 buffers
    %7|1541520149.275|BUFQ|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:   
    127.0.0.1:9092/bootstrap: Purging bufq with 0 buffers
    %7|1541520149.275|BUFQ|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:    
    127.0.0.1:9092/bootstrap: Updating 0 buffers on connection reset
    %7|1541520149.275|TOPPARNEW|rdkafka#producer-1| [thrd:app]: NEW my_topic [-1] 0x556a5fd46cc0  
    (at rd_kafka_topic_new0:393)
    %7|1541520150.275|NOINFO|rdkafka#producer-1| [thrd:main]: Topic my_topic metadata information  
    unknown
    %7|1541520150.275|NOINFO|rdkafka#producer-1| [thrd:main]: Topic my_topic partition count is zero: 
    should refresh metadata
    %7|1541520150.275|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in 
    progress: refresh unavailable topics
    %7|1541520150.275|CONNECT|rdkafka#producer-1| [thrd:main]: Not selecting any broker for cluster 
    connection: still suppressed for 49ms: refresh unavailable topics
    %7|1541520150.275|METADATA|rdkafka#producer-1| [thrd:main]: Skipping metadata refresh of 1    
    topic(s): no usable brokers
    %7|1541520150.275|CONNECT|rdkafka#producer-1| [thrd:main]: Not selecting any broker for cluster 
    connection: still suppressed for 49ms: no cluster connection
    %7|1541520150.275|STATE|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]:    
    127.0.0.1:9092/bootstrap: Broker changed state DOWN -> INIT
    %7|1541520150.275|BROADCAST|rdkafka#producer-1| [thrd:127.0.0.1:9092/bootstrap]: Broadcasting 
    state change
    terminate called after throwing an instance of 'cppkafka::HandleException'
      what():  Local: Timed out
    Aborted (core dumped)
    `

**Comment by edenhill** [comment]
@mfontanini That does sound like a plausible explanation.

Since the default timeout is 1s I strongly suggest calling flush() with a more sensible timeout, such as 30s, to allow for slow connections.

**Comment by elftech** [comment]
> @mfontanini That does sound like a plausible explanation.
> 
> Since the default timeout is 1s I strongly suggest calling flush() with a more sensible timeout, such as 30s, to allow for slow connections.

How to set it longer?

**Comment by kitattyor** [comment]
> 
> 
> > @mfontanini That does sound like a plausible explanation.
> > Since the default timeout is 1s I strongly suggest calling flush() with a more sensible timeout, such as 30s, to allow for slow connections.
> 
> How to set it longer?

I know it's been a while, but putting this here in case anyone stumbles upon this thread.

```
using namespace std::chrono_literals;
producer.flush(10000ms); // 10s
```
