### ISSUE TITLE
librdkafka does not compile on MacOS Mojave

### ISSUE THREAD

**Issue by alexandrugris** [edenhill/librdkafka#2089]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Library does not compile on MacOS Mojave which leads to downstream errors like node-rdkafka does not compile on MacOS Mojave.

How to reproduce
================
Run configure and make on MacOS Mojave

Solution
======

Adding -lcrypto to LIBS fixes the problem, all tests succeed afterwards

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thank you, reproduced it.

It is weird that libcrypto is not automatically picked up from libssl, need to dig deeper.
