### ISSUE TITLE
librdkafka Can Support Windows Platform?

### ISSUE THREAD

**Issue by xiaojuntong** [edenhill/librdkafka#209]
Dear edenhill:
   I need use librdkafka at windows platform and send the videos to Kafka, The librdkafka Can Support Windows Platform ? How to use the code,can you make a exp ?

**Comment by edenhill** [comment]
Hi Xia,

librdkafka currently requires Cygwin on Windows, but a native Win32 port is in the roadmap.

**Comment by DEvil0000** [comment]
see #133
