### ISSUE TITLE
Question on graceful shutdown

### ISSUE THREAD

**Issue by razor-1** [edenhill/librdkafka#2091]
Hi, thanks for this great library!

I have read over https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence but am still not sure how to perform a graceful shutdown of a consumer in an application where at-least-once message processing is a requirement and autocommit is enabled.

What I basically want to do is stop any further background consumption into the fetchq, and drain the fetchq up to the point of the last committed offset.  You can't `poll()` a closed consumer, and from what I have read about `pause()` it invalidates the fetchq.

So what is the proper sequence to shut down in such a way that all the committed messages are processed by the application?  Or is this not possible with autocommit?

Thanks again

**Comment by edenhill** [comment]
I don't think you should worry about the messages in the fetchq, they are not committed.
Only when a message is passed to the application is its offset stored (store_offsets()) for a future auto-commit.

**Comment by razor-1** [comment]
Got it, thank you for clarifying.
