### ISSUE TITLE
broker_version_tests.py - TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by lerookie** [edenhill/librdkafka#2094]
https://github.com/edenhill/librdkafka/blob/95a56e160a3da2018e694dbd74d315163afe90b9/tests/broker_version_tests.py#L218

I believe the file should be opened with `'wb'` instead of `'w'` as bytes are written to the file on L223.

https://github.com/edenhill/librdkafka/blob/95a56e160a3da2018e694dbd74d315163afe90b9/tests/broker_version_tests.py#L223

**Comment by edenhill** [comment]
Good find!
Would you be willing to submit a PR?
