### ISSUE TITLE
Consuming same message twice

### ISSUE THREAD

**Issue by amircodota** [edenhill/librdkafka#2096]
Description
===========
I have a situation where I am consuming the same message twice. This happens during the same process run and with the same consumer object.

I'm doing manual commits. I'm processing messages asynchronously, and I want to commit only messages that have completed processing.
Per https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management, I've set 'enable.auto.offset.store' to false, and I am manually calling commit.
For each partition, I manage a list of offsets in flight, and I am only committing when I've completed all offsets up to a certain offset.

So my question is: Is it possible that when enable.auto.offset.store is false, the next fetch request will fetch from the last commit and not from where we actually last consumed? 

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.5
 - [x ] Apache Kafka version: 2.0.0
 - [x] librdkafka client configuration: 'auto.offset.reset': 'earliest', 'enable.auto.offset.store': false
 - [x] Operating system: Ubuntu 18 & 16
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You will need to call offsets_store() (after processing) to let the client know you've processed a message, otherwise the internal fetcher might rewind itself upon leader failover, consumer rebalance, etc.

**Comment by amircodota** [comment]
Yes, that's what I saw - that it reset itself after a rebalance.

I'm current calling commitAsync on the c++ api. What should I be doing instead?

**Comment by edenhill** [comment]
You need to call store_offsets() for each message you've processed.
You can then choose to continue calling commitAsync(), or re-enable auto commits to have the consumer automatically commit the stored offsets for you (at the configured auto.commit.interval.ms and on rebalance, close(), etc)

**Comment by amircodota** [comment]
Changed it. 

Thanks a lot!
