### ISSUE TITLE
Typo in description for `enable.idempotence`

### ISSUE THREAD

**Issue by rnpridgeon** [edenhill/librdkafka#2098]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
`max.inflight.requests.per.connection` should read `max.in.flight.requests.per.connection` as reported in confluent-kafka-python. 

https://github.com/confluentinc/confluent-kafka-python/issues/481

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag):  master
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Fixed
