### ISSUE TITLE
Failed to produce to topic 'test' partition xx: Local: Queue full

### ISSUE THREAD

**Issue by secsubs** [edenhill/librdkafka#210]
I am using librdkafka via another open source project called rsyslog:
https://github.com/rsyslog/rsyslog/blob/master/plugins/omkafka/omkafka.c

When the producer tries to post a high amount of data to the topic "test", I start seeing these errors in the rsyslog log:
Failed to produce to topic 'test' partition xx: Local: Queue full

I checked rsyslog code and see that this error actually comes from librdkafka code. Wondering what config parameters or metrics or dial/knobs I need to look at on the producer or kafka side to troubleshoot this problem?

I have 18 kafka nodes, each node has five disks (2 CPU, 12 cores, 64GB RAM), and the topic "test" has 30 partitions. About 40-50k messages are written from the producer to the "test" topic.

Thanks.

**Comment by secsubs** [comment]
For the time being, I think I resolved the issue by bumping up these params on the kafka broker config:
num.network.threads=48
socket.request.max.bytes=104857600
socket.receive.buffer.bytes=10485760
socket.send.buffer.bytes=10485760
queued.max.requests=1000

I will need to monitor the producer logs when the output EPS is higher to see if there is enough headroom on the broker side for transient spikes.

**Comment by edenhill** [comment]
Happy to hear you solved the problem by improving the broker performance, good work.

If you want to increase librdkafka's internal producer message queue size you can set the `queue.buffering.max.messages` configuration property, it defaults to 100000 messages.
Something like `.. confParam=["queue.buffering.max.messages=2000000", ...]`

**Comment by secsubs** [comment]
Thanks. Yes, I tweaked the local buffers as well. I think I have hit some
kind of limit of how much an individual producer can send to a kafka
cluster. Might just have to add more producers.

**Comment by iphone4plus** [comment]
Unfortunately,follow the config above did not solve my same problem.Any other suggestions?

**Comment by edenhill** [comment]
librdkafka's internal producer message queue of messages waiting to be sent to the broker will typically only get full on the following occassions:
 * the Kafka cluster is down
 * there is no leader broker available for the given topic+partition(s)
 * the incoming produce rate is higher than what the network or broker can handle
 * the application does not call `rd_kafka_poll()` frequently enough to empty the delivery report queue.

Start troubleshooting based on that and see what you can find.

**Comment by edenhill** [comment]
Increase the producer queue size (`queue.buffering.max.messages` and `queue.buffering.max.kbytes`), or backpressure the data source to give you messages at a lower rate, if possible.

https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by edenhill** [comment]
librdkafka does not throw exceptions. Instead check the return value of produce() for ERR__QUEUE_FULL.

**Comment by hulaxiaodai** [comment]
get it, thank you very much
