### ISSUE TITLE
Log callback would be more useful with opaque pointer in the signature

### ISSUE THREAD

**Issue by mexicowilly** [edenhill/librdkafka#2100]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
The log callback might want to include an `opaque` pointer. Currently, the signature of the log callback, set using `rd_kafka_conf_set_log_cb` is: ```void kafka_log(const rd_kafka_t*, int, const char*, const char*)```
I would suggest that a signature of ```void kafka_log(const rd_kafka_t*, int, const char*, const char*, void*)```
Would be more useful, where the `void*` is the opaque pointer. My code has a logger that should be used to funnel all rdkafka log messages into it. As the signature is now, I must create a global logger object, and I think it would be preferable to allow the log callback to accept a pointer that has the data I need to reference.

Checklist
=========

 - [x] librdkafka: version 0.11.5
 - [x] Apache Kafka version: n/a
 - [x] librdkafka client configuration: `rd_kafka_conf_set_log_cb(conf, kafka_log);` with kafka log signature as `static void kafka_log(const rd_kafka_t* rk, int level, const char* fac, const char* buf)`.
 - [x] Operating system: `FreeBSD freebsd 11.2-RELEASE-p4`
 - [ ] No logs
 - [ ] No broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Yes, you are right, but the callback signature can't be changed without breaking the API guarantees that we provide.

You can use `rd_kafka_opaque(rk)` to acquire the opaque for the rd_kafka_t instance.
