### ISSUE TITLE
Include `msvcp120.dll` within NuGet package

### ISSUE THREAD

**Issue by iradul** [edenhill/librdkafka#2103]
Description
===========
[librdkafka.redist NuGet package](https://www.nuget.org/packages/librdkafka.redist/) Windows runtime (`runtimes/win-*/native/`) includes `msvcr120.dll` but not `msvcp120.dll`. Would it be possible to include this dependency as well?

Runtimes are not working unless *Visual C++ Redistributable Packages for Visual Studio 2013* is installed and the only reason is `msvcp120.dll`.

Ref: https://github.com/Blizzard/node-rdkafka/pull/493

Checklist
=========

 - [x] librdkafka version (release number or git tag): any version on [NuGet](https://www.nuget.org/packages/librdkafka.redist/)
 - [x] Operating system: `Windows`

**Comment by iradul** [comment]
@edenhill any idea ?

**Comment by edenhill** [comment]
Sorry for the long delay.

I will look into this.
