### ISSUE TITLE
Broker socket connection Status

### ISSUE THREAD

**Issue by syedtoah** [edenhill/librdkafka#211]
Hello All,

I am relatively new to the library and I have requirement where in I am supposed to show the Broker connection status via the application and I dont think there is any such API to support the same.
I see the inner structure rd_kafka_broker_t has a rkb_state which will reflect the status of the connection.
Is there any other API/way I can extract the same information without having to modify the lib code?

Thanks

**Comment by edenhill** [comment]
Per-broker state information is available in the statistics output.
Do this:
 * Set `statistics.interval.ms` to a value of your liking (e.g 500ms)
 * Register a stats callback with `rd_kafka_conf_set_stats_cb()`
 * Regularly call `rd_kafka_poll()` to trigger the stats callback.
 * Parse the statistics JSON document that is passed to your callback.

Example stats output:
````
{
  "name": "rdkafka#producer-0",
  "type": "producer",
 ....
 "brokers": {
    "localhost:9092\/bootstrap": {
      "name": "localhost:9092\/bootstrap",
      "nodeid": -1,
      "state": "UP",
      "stateage": 4501978,
....
    },
    "bib.local:9093\/3": {
      "name": "bib.local:9093\/3",
      "nodeid": 3,
      "state": "UP",
      "stateage": 4495774,
....    },
    "bib.local:9092\/2": {
      "name": "bib.local:9092\/2",
      "nodeid": 2,
      "state": "UP",
      "stateage": 4495718,
 ...   },
  ....
}
````

**Comment by syedtoah** [comment]
Thanks Edenhill

**Comment by syedtoah** [comment]
I am sorry to have re-opened this issue. The answer has served the purpose for me but setting the timeout in the call back and parsing the json every timeout seconds is pretty CPU intensive. I wanted to check if I will be able to control this information at all? Coz whenever I call the poll function I get a back to back callbacks for time passed no of times timeout. This is pretty annoying.

**Comment by edenhill** [comment]
What you can do is either adjust your stats interval, or make sure you only parse it once per poll call, something like this:

````
static int stats_parsed = 0;
static void my_sats_cb (..) {
   if (stats_parsed++)
      return; // already parsed

   parse_the_stats...;
}


... somewhere else ...

     while (run) {
         stats_parsed = 0;
         rd_kafka_poll(rk, my_timeout);
    }
````
