### ISSUE TITLE
visual studio 2017compile error

### ISSUE THREAD

**Issue by wjx0912** [edenhill/librdkafka#2112]
1>------ Rebuild All started: Project: librdkafka, Configuration: Debug Win32 ------
1>D:\sdk\vs2017\librdkafka-0.11.6\win32\librdkafka.vcxproj(250,5): error : This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\zlib.v141.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\zlib.v141.windesktop.msvcstl.dyn.rt-dyn.targets.
1>Done building project "librdkafka.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

please fix it, thanks

**Comment by edenhill** [comment]
Did you follow the instructions in the error message?

**Comment by wjx0912** [comment]
@edenhill  
hi, the nuget already download zlib, The error still exists.

**Comment by edenhill** [comment]
How are you performing the NuGet restore, through Visual studio solutions menu or command line?

**Comment by wjx0912** [comment]
@edenhill 
hi, thanks for your reply.  i use the Visual studio solutions menu, can you release a vs2017 .sln file?

**Comment by ElasticCoder** [comment]
The issue is that librdkafka.vcxproj has elements such as:

```
<Import Project="packages\zlib.$(PlatformToolset).windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\zlib.$(PlatformToolset).windesktop.msvcstl.dyn.rt-dyn.targets" Condition="Exists('packages\zlib.$(PlatformToolset).windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\zlib.$(PlatformToolset).windesktop.msvcstl.dyn.rt-dyn.targets')" />
```
whereas $(PlatformToolset) resolves to v141 and the Nuget packages that are restored in packages.config are v140.
I hacked out the librdkafka.vcxproj and changed zlib.$(PlatformToolset) to zlib.v140

**Comment by wjx0912** [comment]
@ElasticCoder 
thanks, i have compile success, please close the issue.

**Comment by wjx0912** [comment]
@GavynG  Please refer to this article: https://github.com/wjx0912/CppBaseUtils/blob/master/document/librdkafka.md

**Comment by bhowmickatish** [comment]
while using VS2017 with default toolset as v141 , modify the toolset of libkafka.vcxproj to v140 ( VS 2015) , it shud build

**Comment by tangyiyong** [comment]
I just copy the folder 'zlib.v140.windesktop.....' in '.\win32\packages', and rename to 'zlib.v141.windesktop.....', then rename all the 'v140' to 'v141' in the new folder's sub path and files. rebuild it, passed
