### ISSUE TITLE
[Question] - rd_kafka_queue_forward APIDOC

### ISSUE THREAD

**Issue by stephan-hof** [edenhill/librdkafka#2113]
Hi,

I'm currently looking at using the Queue interface for internal routing. The following setence in the API DOC confuses me: https://github.com/edenhill/librdkafka/blob/849c066b559950b02e37a69256f0cb7b04381d0e/src/rdkafka.h#L2471

Looking at the implementation I can see that only the refcount to the `dst` queue is increased. What I don't see is that the refcount for the `src` queue gets increased. 
This behavior is also the one I would have expect thus making sense to me.

So I'm wondering why the APIDOC says that the refcount for both queues gets increased.

Speaking in code. I'm wondering if the following function (not the real code, but to illustrate the question), causes memory leak or not if called multiple times.

```c++
void consume(RdKafka:KafkaConsume* consumer) {
    auto q = RdKafka::Queue::create(consumer.get());

    auto q1 = consumer->get_partition_queue(...);
    auto q2 = consumer->get_partition_queue(...);

    q1.forward(q);
    q2.forward(q);

    while (not should_stop) {
         auto msg = q->consume(1000);
         heavy_processing(msg);
         delete msg;
    }
    /* Do I have to call pause() here ? */
   q1.forward(nullptr);
   q2.forward(nullptr);
   delete q;
   delete q1;
   delete q2;
}
```
I know there is this high level consumer, but in my usage case I must have specific control which thread takes care of which partition.

**Comment by edenhill** [comment]
The documentation is incorrect, the source queue will not have its reference increased.
Thanks for pointing this out, will fix the docs!

Your code looks fine. You don't need to call pause().
