### ISSUE TITLE
Producer memory issue

### ISSUE THREAD

**Issue by styphnate** [edenhill/librdkafka#2114]
Description
===========
We have set the queue.buffering.max.kbytes to 524288 on the producer. We then proceed to produce messages faster than we can send them resulting in the queue buffer filling up. We do this to stress-test the system. What we've seen is that when reaching the max size of the queue buffer no more messages are being added, but the memory consumption of the producer keeps growing. If we just continue to send endlessly the producer will keep allocating memory until all RAM is allocated (8gig). But even when there is less than 524288 kbytes in the queue buffer the producer still consumes a lot more memory than what is inside the queue buffer. Where does this memory go?

We are very restricted on memory and need to keep track of how much memory is being used.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<0.11.06>`
 - [ x] Apache Kafka version: `<0.10.2.1>` 
 - [ x] librdkafka client configuration: `<batch.num.messages = 1, queue.buffering.max.messages = 10000000, linger.ms = 1, max.in.flight.requests.per.connection = 10, queue.buffering.max.kbytes = 524288>`
 - [ x] Operating system: `<RHEL6>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
When produce() fails, are you freeing the payload yourself? Librdkafka will not do this for you when produce() returns an error.

Also, try running the application with valgrind to catch memory leaks.

**Comment by edenhill** [comment]
side note: Small batches, such as forced by batch.num.messages=1, will lead to large per-message overhead.

**Comment by styphnate** [comment]
Furthermore we've ran it through valgrind, but as we cant fill the buffer this way we have no way of testing this scenario. When we do smaller tests valgrind shows no leaks.

**Comment by edenhill** [comment]
Can you paste your code calling produce*() ?

**Comment by styphnate** [comment]
void MyImpl::produce(const uint32_t& payloadLength, const unsigned char* payload) {
  // Delay to let the CPU empty the buffer
  std::this_thread::sleep_for(std::chrono::microseconds(20));
  RdKafka::ErrorCode resp = producer->produce(topic,
                                              RdKafka::Topic::PARTITION_UA,            // Unassigned partition
                                              RdKafka::Producer::RK_MSG_FREE, 
                                              const_cast<unsigned char*>(payload), // Serialized bytes
                                              payloadLength,                       // Number of bytes
                                              nullptr,
                                              nullptr);
  if (resp != RdKafka::ERR_NO_ERROR) {
    free(const_cast<unsigned char*>(payload));
    producer->poll(1000);
  }
  else {
    producer->poll(0);
  }
}

**Comment by styphnate** [comment]
`void MyImpl::produce(const uint32_t& payloadLength, const unsigned char* payload) {
  // Delay to let the CPU empty the buffer
  std::this_thread::sleep_for(std::chrono::microseconds(20));
  RdKafka::ErrorCode resp = producer->produce(topic,
                                              RdKafka::Topic::PARTITION_UA,            // Unassigned partition
                                              RdKafka::Producer::RK_MSG_FREE, 
                                              const_cast<unsigned char*>(payload), // Serialized bytes
                                              payloadLength,                       // Number of bytes
                                              nullptr,
                                              nullptr);
  if (resp != RdKafka::ERR_NO_ERROR) {
    free(const_cast<unsigned char*>(payload));
    producer->poll(1000);
  }
  else {
    producer->poll(0);
  }
}
`

**Comment by styphnate** [comment]
`
void MyImpl::produce(const uint32_t& payloadLength, const unsigned char* payload) {
  // Delay to let the CPU empty the buffer
  std::this_thread::sleep_for(std::chrono::microseconds(20));
  RdKafka::ErrorCode resp = producer->produce(topic,
                                              RdKafka::Topic::PARTITION_UA,            // Unassigned partition
                                              RdKafka::Producer::RK_MSG_FREE, 
                                              const_cast<unsigned char*>(payload), // Serialized bytes
                                              payloadLength,                       // Number of bytes
                                              nullptr,
                                              nullptr);
  if (resp != RdKafka::ERR_NO_ERROR) {
    free(const_cast<unsigned char*>(payload));
    producer->poll(1000);
  }
  else {
    producer->poll(0);
  }
}
`

**Comment by edenhill** [comment]
That looks fine.

If valgrind is not an optional, can you try compiling both librdkafka and your application with ASAN?

**Comment by styphnate** [comment]
We just did a valgrind test again and saw that 178kb were lost when we sent 20000 messages with 16175bytes each. This is the statistic difference between 5 seconds where we also print the consumed memory at the bottom:
"rtt": 
	"min":1252
	"max":301730
	"avg":5426
	"sum":48494738
msg_cnt":33191
msg_max":10000000
msg_size":536864425
msg_size_max":536870912

Memory used (kb): 2196884


"rtt": 
	"min":1141
	"max":308923
	"avg":4427
	"sum":42048397
msg_cnt":33191
msg_max":10000000
msg_size":536864425
msg_size_max":536870912

Memory used (kb): 2307112

As you can see the memory used has increased with 100MB. Unfortunately we are unable to run the ASAN test you requested.

**Comment by edenhill** [comment]
valgrind should tell you where the memory was leaked, did it?

**Comment by styphnate** [comment]
It says that the memory is still reachable, not where it was leaked. But the amount of "leaked" memory is so small that it doesn't even compare to the memory-difference of 100MB we saw between the statistics interval of 5 seconds. For each interval we continue to consume additional 100MB of memory.

**Comment by edenhill** [comment]
`valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes .. `

**Comment by styphnate** [comment]
But, we just need to know what consumes memory in the librdkafka when we produce payloads. Since we have capped out our buffer and memory is still being consumed there must be some different buffer that is also being filled? How can we calculate how much memory a specific message size with a specific batch-size would consume, ergo how big the overhead will be?

What we've been noticing that when we send payload to an offline broker and accumulates payloads in the buffer this way, we stop consuming memory when the buffer is full.

**Comment by edenhill** [comment]
The overhead depends on configuration and architecture.
But I'd say roughly around 200 bytes per message.

The memory should not increase constantly when the queue becomes full (other than for serializing messages into protocol requests, compression, etc).
If that happens it typically means there is a leak in the application, not librdkafka, since librdkafka test suites run with a memory profiler.

**Comment by styphnate** [comment]
Thank you, we will try to find our leakage, but the strange thing is that we run our code similar to:
while(true) {
  produceFunction(payload, length);
}
and in the produceFunction() is the code I supplied you with earlier. Seems strange that a memory leak can present itself in these lines.

**Comment by styphnate** [comment]
Hi again, we changed to librdkafka version 1.0.0 from 0.11.06 and we don't see the memory leak anymore. Is there something that you changed to the 1.0.0 version that would fix this issue?
, Thanks.

**Comment by edenhill** [comment]
Not off the top of my head, no.

**Comment by styphnate** [comment]
https://github.com/edenhill/librdkafka/commit/4c359c41b6bda8cc0b39fb2d62613b74b3be65ab maybe this commit? Unsure if a full buffer would cause fatal errors.

**Comment by edenhill** [comment]
Fatal errors are only emitted by the idempotent producer, and at most once per client instance, and they were added in v1.0.0, so that is not the thing.

**Comment by styphnate** [comment]
We just reverted down to librdkafka version 0-11-06 without changing anything else in our code. After doing this we saw that we are still leaking memory when the buffer is full. We don't leak any memory at all at librdkafka version 1-0-0. There must be something you have done in 1-0-0 that solves this issue. If you figure out what, we would really like to know what it was.

**Comment by styphnate** [comment]
We reverted even further down to 0.11.05 and saw the memory leak there as well.

**Comment by edenhill** [comment]
There are no memory leak fixes from what I can tell, but there are two issues that were fixed since v0.11.6 that could cause messages to get stuck in queues in the producer, which was not a memory leak in itself but the messages would never succeed or fail delivery - this was triggered by broker failure and broken retry logic.
