### ISSUE TITLE
Support for 32-bit platforms without 64-bit atomics/libatomic

### ISSUE THREAD

**Issue by AICN1986** [edenhill/librdkafka#212]
Hi,edenhill,
     I use arm-linux-gcc compile librdkafka,when I run configure,it tell me "checking for __sync_64 (by compile)... failed (fail)".So I want to know may I disable this option or how can I solve this problem? I hope you can help me. Thank you!
     Rgds.

**Comment by edenhill** [comment]
librdkafka currently requires 64-bit atomics, and Im guessing you are compiling this for a 32-bit CPU, right?
Not all 32-bit architectures have 64-bit atomic support, so check if your toolchain has support for it.

**Comment by AICN1986** [comment]
Yes,I compiling this for a 32-bit CPU,and my toolchain can't support for 64-bit atomic support,I try to compiling linux-atomic-64bit.c and add it to the project,but it also tell me undefined reference to `__sync_add_and_fetch_8' .Thank you for your reply!

**Comment by edenhill** [comment]
See if libatomic can help you out
Den 6 mar 2015 09:28 skrev "AICN1986" <notifications@github.com>:
>
> Yes,I compiling this for a 32-bit CPU,and my toolchain can't support for
64-bit atomic support,I try to compiling linux-atomic-64bit.c and add it to
the project,but it also tell me undefined reference to
`__sync_add_and_fetch_8' .Thank you for your reply!

**Comment by AICN1986** [comment]
Could you tell me where can I get libatomic source code, if you konw. thanks.

**Comment by edenhill** [comment]
Iirc it is part of gcc
Den 6 mar 2015 09:41 skrev "AICN1986" <notifications@github.com>:

**Comment by edenhill** [comment]
Let me know if this is a show stopper for you and we'll work something out

**Comment by AICN1986** [comment]
I try to compiling lirc by arm-linux-4.5.1,but it can't build."configure: error: no 8-bit type".So I just must update my toolchain.Could you tell me how can I disable  64-bit atomic support.I really don't want to be upgraded toolchain.

**Comment by edenhill** [comment]
What ARM SOC are you trying to build for?

**Comment by AICN1986** [comment]
I try to build bit32 system on arm,and put client of kafka on this arm system.

**Comment by edenhill** [comment]
Do you know what arm system it is? (SoC name or CPU name)

**Comment by AICN1986** [comment]
arm1176jzf-s

**Comment by AICN1986** [comment]
cpu name is "arm1176jzf-s".Thank you very much for the help.

**Comment by edenhill** [comment]
Okay, it's a 32-bit CPU you will need a toolchain that provides libatomic (software atomics).
But I'll have a quick glance through librdkafka source and see if I can lessen the requirement on 64-bit atomics

**Comment by AICN1986** [comment]
Thanks.I just try to build libatomic.

**Comment by AICN1986** [comment]
But how can I build libatomic,could you like give me more information?

**Comment by edenhill** [comment]
libatomic should be built automatically when building your gcc toolchain if gcc version >= 4.8.
For older gcc it seems you can use this instead:
https://gcc.gnu.org/wiki/Atomic/GCCMM?action=AttachFile&do=view&target=libatomic.c

From this page:
https://gcc.gnu.org/wiki/Atomic/GCCMM

**Comment by AICN1986** [comment]
Hi,edenhill,
     I had compile successful.Fllower your advice for libatomic.c,it can't use.At last,I use linux-atomic.c and linux-atomic-64bit.c from gcc 4.9.2 and put them into project,it can compile successful. Thank you for your help.

**Comment by AICN1986** [comment]
By the way,I don't know why I make them to lib it can't work.

**Comment by edenhill** [comment]
To clarify, did you manage to build librdkafka with libatomic.c stuff?

**Comment by AICN1986** [comment]
Yes,I try build librdkafka with libatomic.c it can't work, it since my toolchain not support __int_128_t,and not support other define.

**Comment by edenhill** [comment]
Okay, I'll see if I can make librdkafka work for you.

**Comment by edenhill** [comment]
The work to provide 64-bit atomics on unsupported platforms is in progress.

**Comment by AICN1986** [comment]
Thank you!

**Comment by edenhill** [comment]
@AICN1986 Is this still relevant for you?

**Comment by AICN1986** [comment]
No, I think you can close it. It no need change code. Thanks.

**Comment by edenhill** [comment]
Okay, great.
It is much easier to fix this now after some modifications.
