### ISSUE TITLE
is RdKafka::Message.status() still used? 

### ISSUE THREAD

**Issue by rerpha** [edenhill/librdkafka#2122]
https://github.com/edenhill/librdkafka/blob/d7d58e5407852d17485cf8a82841523eb2b8f6d1/examples/rdkafka_example.cpp#L131

in the example file a delivery report callback is created. I can't seem to use message.status() in my code, is there an updated way to implement the above switch case?

**Comment by edenhill** [comment]
message.status() is currently only available on master branch (and v1.0.0 release candidates),
so you will need to build librdkafka from source to get this functionality.
It is scheduled for the v1.0.0 release in a couple of weeks.

**Comment by rerpha** [comment]
@edenhill I'll leave this closed, but for now how should i implement a delivery callback? Is there another way to see if a message has been delivered? thanks. currently switching from the C API to C++

**Comment by edenhill** [comment]
You should check message.error() for if the message was delivered or not, status() is mostly for people concerned with exactly once.
