### ISSUE TITLE
Is there support for the SASL meachanism OAUTHBEARER?

### ISSUE THREAD

**Issue by karlmartens** [edenhill/librdkafka#2123]
Description
===========

I did not find any reference in the documentation to supporting the SASL mechanism OAUTHBEARER. Is it supported? if not are there plans to support it in the future and if so what kind of timeline is it planned for.

Thanks.

**Comment by rondagostino** [comment]
See PR https://github.com/edenhill/librdkafka/pull/2189

**Comment by edenhill** [comment]
Available on master
