### ISSUE TITLE
Mismatch timestamp units between C++ Producer and C implementation

### ISSUE THREAD

**Issue by LighthouseJ** [edenhill/librdkafka#2125]
**NOTE:** This is purely an inline documentation issue.

Description
===========
The inline documentation for RdKafka::Producer::produce() that accepts a creation timestamp defines the unit of time for timestamps as microseconds, but the underlying units of time for a timestamp by librdkafka C implementation uses milliseconds.

Relevant line mentioning microseconds:
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L2500

Used as milliseconds here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L955
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_msg.h#L90

How to reproduce
================
N/A

Checklist
=========

 - [x] librdkafka version (release number or git tag): Various, since commit hash: b864890288b3384ff457f14edbfa8791983dd05f
 - [x] Apache Kafka version: N/A
 - [x] librdkafka client configuration: N/A
 - [x] Operating system: N/A
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You're absolutely right, that should be fixed!
