### ISSUE TITLE
Producer Seg Faults after socket.timeout.ms

### ISSUE THREAD

**Issue by tgaldes** [edenhill/librdkafka#2126]
Description
I am testing out kafka by sending a lot of messages to a broker on my localhost. Once socket.timeout.ms has passed, my program will segfault, usually in a call to producer->poll

I've run my program several times changing only the configured socket timeout, and the time it takes for the program to segfault varies accordingly.

I'm not sure if I'm just using the option incorrectly or if it's a bug, but after running the program I can consume messages that were sent before the segfault, so some are getting sent despite the run time of the program indicating that there is some network request sent at the beginning of the program that always times out.

Backtrace of fault:
Core was generated by `./producer -t 51380 -b localhost:9093'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000001b3421d8 in ?? ()
[Current thread is 1 (Thread 0x7f6a1d36a080 (LWP 22567))]
(gdb) bt
#0  0x000000001b3421d8 in ?? ()
#1  0x00007f6a1a16f10f in RdKafka::error_cb_trampoline(rd_kafka_s*, int, char const*, void*) () from /usr/lib64/librdkafka++.so.1
#2  0x00007f6a19e873ac in rd_kafka_poll_cb () from /usr/lib64/librdkafka.so.1
#3  0x00007f6a19eb3e93 in rd_kafka_q_serve () from /usr/lib64/librdkafka.so.1
#4  0x000000000044806a in main (argc=5, argv=0x7ffcabece0b8) at producer.cpp:184

When the socket timeout is small enough, my program will segfault wherever it's currently executing. Typically it happens in a call to poll() since the majority of the execution time in my program is calling that function.
=28413== Jump to the invalid address stated on the next line
==28413==    at 0x322437F8: ???
==28413==    by 0xFFFF46FFFFFFFFFF: ???
==28413==    by 0x3FE: ???
==28413==    by 0x8D9FAD7FF: ???
==28413==    by 0x35B9FF47FF: ???
==28413==  Address 0x322437f8 is 360 bytes inside a block of size 656 alloc'd
==28413==    at 0x4C2A243: operator new(unsigned long) (vg_replace_malloc.c:334)
==28413==    by 0x6955451: allocate (new_allocator.h:104)
==28413==    by 0x6955451: allocate (alloc_traits.h:416)
==28413==    by 0x6955451: __allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<RootBar<....> >, (__gnu_cxx::_Lock_policy)2u> > > (allocated_ptr.h:103)
.......
This stack originates from a call I'm making that doesn't involve rdkafka.
Then:
=28413==    by 0x447C33: main (producer.cpp:128)
==28413== 
vex amd64->IR: unhandled instruction bytes: 0xF4 0x7C 0x8F 0x1C 0x67 0x15 0x0 0x60 0x5E 0x1C
vex amd64->IR:   REX=0 REX.W=0 REX.R=0 REX.X=0 REX.B=0
vex amd64->IR:   VEX=0 VEX.L=0 VEX.nVVVV=0x0 ESC=NONE
vex amd64->IR:   PFX.66=0 PFX.F2=0 PFX.F3=0
==28413== Invalid read of size 1
==28413==    at 0x3224384B: ???
==28413==    by 0xFFFF46FFFFFFFFFF: ???
==28413==    by 0x3FE: ???
==28413==    by 0x8D9FAD7FF: ???
==28413==    by 0x35B9FF47FF: ???
==28413==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==28413== 
==28413== 
==28413== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==28413==  Access not within mapped region at address 0x0
==28413==    at 0x3224384B: ???
==28413==    by 0xFFFF46FFFFFFFFFF: ???
==28413==    by 0x3FE: ???
==28413==    by 0x8D9FAD7FF: ???
==28413==    by 0x35B9FF47FF: ???
==28413==  If you believe this happened as a result of a stack
==28413==  overflow in your program's main thread (unlikely but
==28413==  possible), you can try to increase the size of the
==28413==  main thread stack using the --main-stacksize= flag.
==28413==  The main thread stack size used in this run was 8388608.
==28413== Invalid free() / delete / delete[] / realloc()
==28413==    at 0x4C2AD1D: free (vg_replace_malloc.c:530)
==28413==    by 0x942926B: __libc_freeres (in /usr/lib64/libc-2.17.so)
==28413==    by 0x4A24749: _vgnU_freeres (vg_preloaded.c:77)
==28413==    by 0x7C5210E: RdKafka::error_cb_trampoline(rd_kafka_s*, int, char const*, void*) (in /usr/lib64/librdkafka++.so.1)
==28413==    by 0x7E7B3AB: ??? (in /usr/lib64/librdkafka.so.1)
==28413==    by 0x7EA7E92: ??? (in /usr/lib64/librdkafka.so.1)
==28413==    ........... more frames
==28413==  Address 0x967f3c0 is 0 bytes inside data symbol "noai6ai_cached"

The valgrind output looks similar when the socket timeout is long enough that the program is in a call to poll() when the timeout expires.

Checklist
=========
 - [x] 0.11.5 and 0.9.3
 - [ ] Apache Kafka version: confluent kafka 2.11
# Global config
builtin.features = gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins
client.id = rdkafka
metadata.broker.list = 10.4.30.52:9093
message.max.bytes = 1000000
message.copy.max.bytes = 65535
receive.message.max.bytes = 100000000
max.in.flight.requests.per.connection = 1000000
metadata.request.timeout.ms = 60000
topic.metadata.refresh.interval.ms = 300000
metadata.max.age.ms = -1
topic.metadata.refresh.fast.interval.ms = 250
topic.metadata.refresh.fast.cnt = 10
topic.metadata.refresh.sparse = true
debug = 
socket.timeout.ms = 60000 (switching this guy around accordingly)
socket.blocking.max.ms = 1000
socket.send.buffer.bytes = 0
socket.receive.buffer.bytes = 0
socket.keepalive.enable = false
socket.nagle.disable = false
socket.max.fails = 1
broker.address.ttl = 1000
broker.address.family = any
reconnect.backoff.jitter.ms = 500
statistics.interval.ms = 0
enabled_events = 0
log_cb = 0x7e71200
log_level = 6
log.queue = false
log.thread.name = true
log.connection.close = true
socket_cb = 0x7e875b0
open_cb = 0x7e9a3d0
internal.termination.signal = 0
api.version.request = true
api.version.request.timeout.ms = 10000
api.version.fallback.ms = 1200000
broker.version.fallback = 0.9.0
security.protocol = plaintext
sasl.mechanisms = GSSAPI
sasl.kerberos.service.name = kafka
sasl.kerberos.principal = kafkaclient
sasl.kerberos.kinit.cmd = kinit -S "%{sasl.kerberos.service.name}/%{broker.name}" -k -t "%{sasl.kerberos.keytab}" %{sasl.kerberos.principal}
sasl.kerberos.min.time.before.relogin = 60000
partition.assignment.strategy = range,roundrobin
session.timeout.ms = 30000
heartbeat.interval.ms = 1000
group.protocol.type = consumer
coordinator.query.interval.ms = 600000
enable.auto.commit = true
auto.commit.interval.ms = 5000
enable.auto.offset.store = true
queued.min.messages = 100000
queued.max.messages.kbytes = 1048576
fetch.wait.max.ms = 100
fetch.message.max.bytes = 1048576
fetch.max.bytes = 52428800
fetch.min.bytes = 1
fetch.error.backoff.ms = 500
offset.store.method = broker
enable.partition.eof = true
check.crcs = false
queue.buffering.max.messages = 10000000
queue.buffering.max.kbytes = 1048576
queue.buffering.max.ms = 0
message.send.max.retries = 2
retry.backoff.ms = 100
queue.buffering.backpressure.threshold = 1
compression.codec = none
batch.num.messages = 10000
delivery.report.only.error = false

# Topic config
request.required.acks = 1
request.timeout.ms = 5000
message.timeout.ms = 300000
queuing.strategy = fifo
produce.offset.report = false
partitioner = consistent_random
compression.codec = inherit
compression.level = -1
auto.commit.enable = true
auto.commit.interval.ms = 60000
auto.offset.reset = largest
offset.store.path = .
offset.store.sync.interval.ms = -1
offset.store.method = broker
consume.callback.max.messages = 0

 - [ ] CentOS Linux release 7.5.1804 (Core)

**Comment by edenhill** [comment]
My guess would be that your Error/Event callback class was allocated on the stack and has now gone out of scope.

**Comment by tgaldes** [comment]
That was exactly it *facepalms*
I had read your advice on a couple other issue threads, but never realized that my event cb was allocated on the stack even though the delivery and error were not.
Thanks for the help!
