### ISSUE TITLE
Unable to load the librdkafka

### ISSUE THREAD

**Issue by no1melman** [edenhill/librdkafka#2131]
Description
===========

I've been trying to use the Confluent.Kafka library and am having troubles loading the librdkafka. Here is the [issue](https://github.com/confluentinc/confluent-kafka-dotnet/issues/688).

Basically, the issue is it can't load the librdkafka library.

How to reproduce
================

Clone the Confluent.Kafka solution, go into examples/consumer, modify the Consumer.csproj, remove any reference to net45 and net462. run `dotnet build`, `dotnet run -- consumer <BROKER_IP><PORT> <TOPICNAME>`, it'll throw the error.

The error is:

```
Unable to load shared library 'librdkafka' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibrdkafka, 1): image not found
```

I'm not sure how that reproduction will be of any help because it is .NET Core specific. However, if you apply the DYLD_PRINT_LIBRARIES and [others](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/LoggingDynamicLoaderEvents.html) it gives the below output:

```
dyld: loaded: /Users/melman/.nuget/packages/librdkafka.redist/1.0.0-pre1/runtimes/osx-x64/native/librdkafka.dylib
dyld: loaded: /usr/lib/libsasl2.2.dylib
dyld: unloaded: /Users/melman/.nuget/packages/librdkafka.redist/1.0.0-pre1/runtimes/osx-x64/native/librdkafka.dylib
dyld: lazy bind: libcoreclr.dylib:0x105B5E750 = libc++abi.dylib:___cxa_allocate_exception, *0x105B5E750 = 0x7FFF6043FAD2
dyld: lazy bind: libcoreclr.dylib:0x105B5E7A0 = libc++abi.dylib:___cxa_throw, *0x105B5E7A0 = 0x7FFF6043FB48
dyld: lazy bind: libcoreclr.dylib:0x105B5E738 = libunwind.dylib:__Unwind_Resume, *0x105B5E738 = 0x7FFF62F3BE82
dyld: lazy bind: libcoreclr.dylib:0x105B5E760 = libc++abi.dylib:___cxa_begin_catch, *0x105B5E760 = 0x7FFF6044050F
dyld: lazy bind: libcoreclr.dylib:0x105B5E770 = libc++abi.dylib:___cxa_end_catch, *0x105B5E770 = 0x7FFF60440583
dyld: lazy bind: libcoreclr.dylib:0x105B5E868 = libsystem_c.dylib:_bsearch, *0x105B5E868 = 0x7FFF62DC00A4
dyld: lazy bind: libcoreclr.dylib:0x105B5E850 = libsystem_c.dylib:_atoi, *0x105B5E850 = 0x7FFF62DBFFD2
dyld: lazy bind: libcoreclr.dylib:0x105B5E798 = libc++abi.dylib:___cxa_rethrow, *0x105B5E798 = 0x7FFF6044080B
dyld: lazy bind: libcoreclr.dylib:0x105B5EA88 = libsystem_c.dylib:_iswspace, *0x105B5EA88 = 0x7FFF62D6D134
dyld: lazy bind: System.Native.dylib:0x1066D8378 = libsystem_kernel.dylib:_stat$INODE64, *0x1066D8378 = 0x7FFF62E51884
dyld: lazy bind: System.Native.dylib:0x1066D83A8 = libsystem_c.dylib:_sysconf, *0x1066D83A8 = 0x7FFF62D90118
```

I will just point out that I have looked to see if the dylib exists there and it does.

I just want to confirm that this is nothing to do with librdkafka stuff.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): (redist) `1.0.0-pre1`
 - [ ] Apache Kafka version: N/A
 - [ ] librdkafka client configuration: N/A
 - [x] Operating system: `OSX Mojave 10.14.1`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts N/A
 - [x] Critical issue

**Comment by edenhill** [comment]
` dlopen(liblibrdkafka, 1): image not found`

seems like the dotnet client is prepending one too many "lib".

Please use the dotnet issue, this is not related to librdkafka itself.

**Comment by no1melman** [comment]
why would the DYLD output loading the correct url?

**Comment by no1melman** [comment]
So the issue I had is that I needed to install openssl - I haven't found this in the FAQ, why is this needed on the mac?

**Comment by nick-melton** [comment]
I had the same issue on mac, the solution was to copy it from my brew folder to the one, that was mentioned in the error. In my case I just ran: `cp /opt/homebrew/lib/librdkafka.dylib /opt/homebrew/opt/openssl@3/lib/librdkafka.dylib`
