### ISSUE TITLE
crash at "handle->event_cb_->event_cb(event)"

### ISSUE THREAD

**Issue by hapablanha** [edenhill/librdkafka#2133]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Crash at the line in **bold**

librdkafka-0.11.6\src-cpp\HandleImpl.cpp

void RdKafka::log_cb_trampoline (const rd_kafka_t *rk, int level,
                                 const char *fac, const char *buf) {
  if (!rk) {
    rd_kafka_log_print(rk, level, fac, buf);
    return;
  }

  void *opaque = rd_kafka_opaque(rk);
  RdKafka::HandleImpl *handle = static_cast<RdKafka::HandleImpl *>(opaque);

  if (!handle->event_cb_) {
    rd_kafka_log_print(rk, level, fac, buf);
    return;
  }

  RdKafka::EventImpl event(RdKafka::Event::EVENT_LOG,
                           RdKafka::ERR_NO_ERROR,
                           static_cast<RdKafka::Event::Severity>(level),
                           fac, buf);

  **handle->event_cb_->event_cb(event);**
}

How to reproduce
================
disconnect the network for 10 min then reconnect

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version v0.11.6
 - [x] Apache Kafka version: v2.0.0
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: Windows 10
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
[Test.zip](https://github.com/edenhill/librdkafka/files/2652828/Test.zip)
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by hapablanha** [comment]
When we were testing using rdkafka_example, we notice "ERROR connection closed". I wonder whether crash will be seen if it is handled gracefully.
BTW, in our revised code we always set use_ccb to 0.

**Comment by hapablanha** [comment]
one more question, as the messages are pre-fetched, is consume_callback() preferred than consume() from the point of performance (CPU and memory usage) view?

**Comment by edenhill** [comment]
consume_callback() will theoretically be slightly faster than consume(), but not enough to warrant its use in any real-world use-cases.
