### ISSUE TITLE
Issue with consuming topic on Confluent Kafka instance

### ISSUE THREAD

**Issue by jonasvekeman** [edenhill/librdkafka#2134]
Hi

We've setup an Kafka server in the Confluent Cloud. I'm trying to consume a topic using cppkafka (v0.2.0) and librdkafka (tested v0.11.6 and v1.0.0_rc4) but I get an error on APIVERSION_QUERY.

Sample code:

```cpp
Configuration config{
	{ "bootstrap.servers", "pkc-l915e.europe-west1.gcp.confluent.cloud:9092" },
	{ "api.version.request", true },
	{ "broker.version.fallback", "0.10.0.0" },
	{ "api.version.fallback.ms", 0 },
	{ "sasl.mechanisms", "PLAIN" },
	{ "sasl.username", "..." },
	{ "sasl.password", "..." },
	{ "enable.auto.commit", false },
	{ "group.id", "testclient" },
	{ "debug", "broker,topic,msg" }
};
Consumer consumer{ config };

consumer.subscribe({ "topic" });
auto message = consumer.poll();
if (!message)
{
   // code gets till here.
}
```

Error log:

%7|1544111102.799|BROKER|rdkafka#consumer-1| [thrd:app]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Added new broker with NodeId -1
%7|1544111102.799|BRKMAIN|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1544111102.799|CONNECT|rdkafka#consumer-1| [thrd:app]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Selected for cluster connection: bootstrap servers added (broker has 0 connection attempt(s))
%7|1544111102.799|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v1.0.0-pre2 (0x1000002) rdkafka#consumer-1 initialized (builtin.features 0xffff, debug 0x46)
%7|1544111102.799|BRKMAIN|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Enter main broker thread
%7|1544111102.799|CONNECT|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Received CONNECT op
%7|1544111102.799|STATE|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1544111102.799|CONNECT|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1544111102.799|STATE|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1544111102.800|CONNECT|rdkafka#consumer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: coordinator query
%7|1544111102.800|CONNECT|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: Received CONNECT op
%7|1544111102.800|STATE|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> TRY_CONNECT
%7|1544111102.800|STATE|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: Broker changed state TRY_CONNECT -> UP
%7|1544111102.852|CONNECT|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Connecting to ipv4#35.195.121.90:9092 (plaintext) with socket 7
%7|1544111102.894|CONNECT|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Connected to ipv4#35.195.121.90:9092
%7|1544111102.894|CONNECTED|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Connected (#1)
%7|1544111102.894|FEATURE|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1544111102.894|STATE|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1544111102.948|BROKERFAIL|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
%7|1544111102.949|FEATURE|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Updated enabled protocol features -ApiVersion to 
%7|1544111102.949|STATE|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Broker changed state APIVERSION_QUERY -> DOWN
%7|1544111102.949|BROKERFAIL|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: failed: err: Local: Not implemented: (errno: Connection reset by peer)
%7|1544111102.949|FAIL|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: ApiVersionRequest failed: Local: Broker transport failure: probably due to old broker version (after 0ms in state DOWN)
%7|1544111103.800|CONNECT|rdkafka#consumer-1| [thrd:main]: Cluster connection already in progress: coordinator query
%7|1544111103.800|CONNECT|rdkafka#consumer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection
DBG [2018-Dec-06 16:45:03.800998] [00007f44675be700] No new messages [boost::optional<SshMediatorKafkaConsumeData> sshmediator::server::SshMediatorKafka::consume():/home/t1t/Documents/git/cpp-ssh-mediator/src/ssh-mediator/server/SshMediatorKafka.cpp:306]
%7|1544111103.801|DESTROY|rdkafka#consumer-1| [thrd:app]: Terminating instance (destroy flags none (0x0))
%7|1544111103.801|DESTROY|rdkafka#consumer-1| [thrd:main]: Destroy internal
%7|1544111103.801|DESTROY|rdkafka#consumer-1| [thrd:main]: Removing all topics
%7|1544111103.801|DESTROY|rdkafka#consumer-1| [thrd:main]: Sending TERMINATE to pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap
%7|1544111103.801|TERM|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: Received TERMINATE op in state UP: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1544111103.801|BROKERFAIL|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1544111103.801|FAIL|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: Client is terminating (after 1001ms in state UP)
%7|1544111103.801|STATE|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: Broker changed state UP -> DOWN
%7|1544111103.801|TERMINATE|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: Handle is terminating in state DOWN: 1 refcnts (0x7f4460006aa0), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1544111103.801|BROKERFAIL|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1544111103.801|TERM|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1544111103.801|BROKERFAIL|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Connection reset by peer)
%7|1544111103.801|FAIL|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Client is terminating (after 852ms in state DOWN)
%7|1544111103.801|TERMINATE|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: Handle is terminating in state DOWN: 1 refcnts (0x7f4460007730), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1544111103.801|BROKERFAIL|rdkafka#consumer-1| [thrd:pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap]: pkc-l915e.europe-west1.gcp.confluent.cloud:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Connection reset by peer)

**Comment by rolandyoung** [comment]
You need to fill in the issue template. For instance, you should state what Apache Kafka version you are connecting to and what client platform you are using.

**Comment by edenhill** [comment]
You need to configure `security.protocol=SASL_SSL`, right now it is trying to connect with neither SSL nor SASL authentication, which is rejected by the broker.

**Comment by jonasvekeman** [comment]
Thanks for the feedback. 

I guess if I configure SASL_SSL, I need to provide a client certificate as well as stated in the Confluent Cloud Client config for librdkafka (ssl.ca.location=/usr/local/etc/openssl/cert.pem). I'm a bit confused by this certificate, is this one from the server (I didn't setup the server myself) or one I can create myself?

**Comment by edenhill** [comment]
confluent cloud does not require a client certificate.
ssl.ca.location is the (root) cert to let the client validate the broker certificate.
These are typically provided by the distro on Linux, but might require `ca-certificates` deb package to be installed, or openssl (through homebrew) on OSX.
Try without specifying ssl.ca.location, if you get an SSL failure, specify it.
The file is typically called cacert.pem and can also be downloaded from e.g. https://curl.haxx.se/docs/caextract.html
