### ISSUE TITLE
Which thread runs RdKafka::RebalanceCb::rebalance_cb()?

### ISSUE THREAD

**Issue by ronalabraham** [edenhill/librdkafka#2135]
I'm using the high-level C++ Kafka consumer with a custom rebalance callback class, and I only have a single thread that calls [`RdKafka::KafkaConsumer::consume()`](https://github.com/edenhill/librdkafka/blob/0.11.1.x/src-cpp/rdkafkacpp.h#L1544). Is it guaranteed that [`RdKafka::RebalanceCb::rebalance_cb()`](https://github.com/edenhill/librdkafka/blob/0.11.1.x/src-cpp/rdkafkacpp.h#L665) always runs on the same thread that calls `consume()`?  I assume that this is the case based on the documentation, but I don't think it's explicitly stated anywhere.

**Comment by edenhill** [comment]
rebalance_cb(), along with all other callbacks (unless otherwise noted, such as for log_cb), will be triggered by calling consume(), poll(), flush(), i.e., the application thread calling those methods.
