### ISSUE TITLE
kafka consumer not receipting mesages or  RD_KAFKA_RESP_ERR__PARTITION_EOF when one node is down in kafka cluster

### ISSUE THREAD

**Issue by dcdsc** [edenhill/librdkafka#2136]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I am having 3 node kafka cluster with default replication factor=2 and num.partitions=2. When I brought one kafka node down I am seeing messages getting missed by kafka consumer. Below are my initial observations.

I am running kafka consumer to consume one message which is sent by producer once consumer is started.
1) In some cases I am seeing kafka consumer after never getting "RD_KAFKA_RESP_ERR__PARTITION_EOF" in..->err on rd_kafka_consumer_poll(). In this case it also never gets the message sent by producer.

2) In very few tries kafka consumer receives "RD_KAFKA_RESP_ERR__PARTITION_EOF" in..->err on rd_kafka_consumer_poll(). In this case it gets the message sent by producer

How to reproduce
================
1) bring down one kafka node in 3 node cluster.
2) start kafka consumer with broker list as all 3 nodes of cluster
3) start kafka producer and send one message with broker list as all 3 nodes of cluster
4) Kafka consumer will not receive either message or EOF.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.5
 - [x] Apache Kafka version: kafka_2.11-1.1.0
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: RHEL 7.4
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Are you using subscribe() or assign() in the consumer?
If subscribe(): do you get an assignment?

Are the assigned partitions on-line, i.e., have an active leader? (`kafka-topics.sh --describe ...` or `kafkacat -b .. -L -t topic`

**Comment by dcdsc** [comment]
I am using assign and all assign partitions has active leader. I am seeing this issue very frequently i.e. 9 out of 10 times.

$ ./kafka-topics.sh --describe --zookeeper :2181 --topic Dharmendra_director.OPERATION_CONTEXT
Topic:Dharmendra_director.OPERATION_CONTEXT	PartitionCount:2	ReplicationFactor:2	Configs:
	Topic: Dharmendra_director.OPERATION_CONTEXT	Partition: 0	Leader: 147	Replicas: 147,103	Isr: 147
	Topic: Dharmendra_director.OPERATION_CONTEXT	Partition: 1	Leader: 145	Replicas: 103,145	Isr: 145

**Comment by edenhill** [comment]
Run the consumer with `debug` config property set to `consumer,fetch` to see what is going on

**Comment by dcdsc** [comment]
My application is running multiple instances of kafka consumer at a time using same configuration template. If I am changing debug=consumer,fetch, its throwing lots of logs for all consumers in my application.
it won't be easy to trace the faulty kafka consumer which is missing the message/EOF.

Is there any other way so I can give you some debug logs?

**Comment by edenhill** [comment]
The standard log function includes the client instance name, e.g. "consumer-2", you should be able to grep on that to separate logs from different instances.

**Comment by dcdsc** [comment]
Find attached logs with debug=consumer,fetch
[rdkafka_consumer13.log](https://github.com/edenhill/librdkafka/files/2662739/rdkafka_consumer13.log)

**Comment by edenhill** [comment]
according to that log your application should've received at least two messages.

**Comment by dcdsc** [comment]
yes but I am not seeing any message. 
Did you find if it received EOF anytime? as normally  when we start any any consumer first it will go to EOF. then it will recieve message if any sent after consumer startup.

**Comment by edenhill** [comment]
You should've received a PARTITION_EOF after each message since the produce rate is lower than the poll rate.

Do note that in the next version of librdkafka (v1.0.0) Partition EOFs are disabled by default and you'll need to set enable.partition.eof=true to have them emitted.

**Comment by dcdsc** [comment]
whenever message is not received its not getting EOF as well. As I mentioned in description above whenever its receiving the EOF , I am getting message as well.

Let me know if you want any other information.

**Comment by edenhill** [comment]
Since we can see in the logs that the messages are enqueued for the application I would guess this is an application issue.
You'll need to share relevant parts of your consumer code to proceed

**Comment by dcdsc** [comment]
ok let me figure how to share reproducer with you.

**Comment by dcdsc** [comment]
Please find few more consumer logs. yesterday what i shared with you was probably the message received case.

This log taken when consumer received the messages
[rdkafka-consumer-17_message_received.log](https://github.com/edenhill/librdkafka/files/2666359/rdkafka-consumer-17_message_received.log)

This log taken when consumer didn't received any messages.
[rdkafka-consumer-11_message_missed.log](https://github.com/edenhill/librdkafka/files/2666360/rdkafka-consumer-11_message_missed.log)
 
Please have a look at these logs and see if it helps. In meantime I will be working on reproduce this with some sample code.

**Comment by edenhill** [comment]
The second log shows that the client can't connect to one of the brokers.
Can it connect to any broker? (set `debug=cgrp,broker,fetch`)
Is there an active leader broker for the partitions you wish to consume?
Are you using subscribe() or assign()?

**Comment by dcdsc** [comment]
I have three brokers: kafkanode145,kafkanode147,kafkanode103 (out of which kafkanode103 is down)

my kafka consumer intended to consume from partition 1 of the topic. which has an active leader kafkanode145, shown as below:

./kafka-topics.sh --describe --zookeeper :2181 --topic MCC.OPERATION_CONTEXT
Topic:MCC.OPERATION_CONTEXT	PartitionCount:2	ReplicationFactor:2	Configs:
	Topic: MCC.OPERATION_CONTEXT	Partition: 0	Leader: 147	Replicas: 147,103	Isr: 147
	Topic: MCC.OPERATION_CONTEXT	Partition: 1	Leader: 145	Replicas: 103,145	Isr: 145

I am using assign.

Please find below the logs with requested debug.

[rdkafka-consumer-23-test_failed.log](https://github.com/edenhill/librdkafka/files/2666822/rdkafka-consumer-23-test_failed.log)

**Comment by edenhill** [comment]
With broker 103 out of play your __consumer_offsets is under-replicated which prevents a group coordinator to be elected:
`11/12 14:32:36.160541[22859][458774] Trace Level: 7 Reason: CGRPCOORD Kafka Handle Name: rdkafka#consumer-23 Log: [thrd:main]: kafkanode145:9092/145: Group "kafkanode147.25590.65536" GroupCoordinator response error: Broker: Group coordinator not available`

**Comment by dcdsc** [comment]
Do you want to say what --describe is showing kafkanode145 as leader for partition 1 is not correct?

Is there any way to recover from it? Any configurations or settings to avoid this scenario?

**Comment by edenhill** [comment]
You need to restore the down broker, or change the __consumer_offsets replication factor to 2

**Comment by dcdsc** [comment]
you mean below server properties ?

############################# Internal Topic Settings  #############################
# The replication factor for the group metadata internal topics "__consumer_offsets" and "__transaction_state"
# For anything other than development testing, a value greater than 1 is recommended for to ensure availability such as 3.
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1

is __transaction_state topic also play any role . is it better to have that also to 2?

**Comment by edenhill** [comment]
If this is a development cluster you can reduce the __consumer_offsets replication factor.
If it is a prod cluster you need to get the down broker back in business.

**Comment by dcdsc** [comment]
After changing topic replicator of __consumer_offsets to 2 , its working fine consistently.
