### ISSUE TITLE
how to get the number of partitions in a topic in program

### ISSUE THREAD

**Issue by Yrp** [edenhill/librdkafka#214]
hi, edenhill
how to get the number of partitions in a topic in program? i use c++ api

**Comment by Yrp** [comment]
hi, edenhill
how to get the number of partitions in a topic in program? i use c++ api

**Comment by edenhill** [comment]
The Metadata API is currently not implemented, but in progress according to issue #143 
In the meantime I suggest you use the C API to fetch metadata and retrieve the partition count:
`rd_kafka_metadata()`

**Comment by Yrp** [comment]
well
3ks

**Comment by edenhill** [comment]
Duplicate #143
