### ISSUE TITLE
Failed to get message timestamp from rd_kafka_message_timestamp() in producer message delivered callback

### ISSUE THREAD

**Issue by KseniyaYakil** [edenhill/librdkafka#2144]
Description
===========

rd_kafka_message_timestamp() returns incorrect ts and ts type when called in msg delivered callback in producer.
ts 1544534459024 (Tuesday May 8 05:43:44 UTC 50914), ts type 8 (unknown)

As far as I know rd_kafka_message_timestamp() is supposed to be added in master branch of librdkafka recently.

How to reproduce
================

1. configure librdkafka: ./configure --disable-ssl --enable-static
2. set correct broker list and topic name in test program (https://gist.github.com/KseniyaYakil/9bde5e139d95ddf07f2ef59e4eac6590)
3. build test program: gcc kafka_producer_msg_ts.c /usr/local/lib/librdkafka.a -ldl -lz -lpthread -lrt -lm -o msg_ts
4. run: ./msg_ts

Checklist
=========
 - [x] librdkafka version (release number or git tag): master branch, last commit 2f189501cbbd
 - [x] Apache Kafka version: kafka 0.11.0.0
 - [x] librdkafka client configuration: debug=all, produce.offset.report=true
 - [x] Operating system: Linux 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - [x] Provide logs https://gist.github.com/KseniyaYakil/9bde5e139d95ddf07f2ef59e4eac6590
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
`	printf("\n\nmsg delivered cb: %s: offset %lu, ts %"PRId64", type %u\n",`

The offset format should be `..offset %"PRId64"..`

**Comment by edenhill** [comment]
```

static void kafka_destroy(rk_ctx_t *ctx) {
	if (ctx->rk != NULL) {
		rd_kafka_destroy(ctx->rk);
	}

	if (ctx->topic != NULL) {
		rd_kafka_topic_destroy(ctx->topic);
	}

	*ctx = (rk_ctx_t){};
};
```

You need to destroy the topic object before the rd_kafka_t object. I.e., the reverse creation order.
More info here:
https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence

**Comment by KseniyaYakil** [comment]
Magnus, printf format (that only has read access to variable) and destroy order (that happens in the end of the program, after calling rd_kafka_message_timestamp()) don't explain why the type of rd_kafka_timestamp_type_t *tstype is incorrect. (anyway thank you for high lining this)

I reported issue about incorrect tstype and ts after calling rd_kafka_message_timestamp() function in msg deliver cb in producer. This doesn't work on master branch.. and we really need to know correct kafka timestamp in producer's deliver cb.

Please, have a look again

**Comment by edenhill** [comment]
Can't reproduce this with librdkafka master and AK 0.11.0.0:
`msg delivered cb: rdkafka#producer-1: offset 3, ts 1545073670902, type 1`
