### ISSUE TITLE
Producer memory allocation

### ISSUE THREAD

**Issue by styphnate** [edenhill/librdkafka#2147]
Description
===========
How do librdkafkas producer allocate memory? We have seen that we keep allocating memory over time for the producer application up until it has allocated the whole buffer size even though the buffer is not even close to being full, is these observations accurate? Is there any way to let librdkafka free this memory so other applications can use this memory while the buffer is not full?

How to reproduce
================
Produce messages over a long time while printing the consumed memory from the application, see that the memory increases over time.

Checklist
=========
 - [x] librdkafka version (release number or git tag): `<librdkafka 1.0.0 RC2>`
 - [x] Apache Kafka version: `<0.10.2.1>`
 - [x] librdkafka client configuration: `<message.send.max.retries = 5, max.in.flight.requests.per.connection = 5, queue.buffering.max.ms = 200, queue.buffering.max.kbytes = 716, message.max.bytes = 4096000, batch.num.messages = 1000, queue.buffering.max.messages = 734003>`
 - [x] Operating system: `<RHEL6>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The allocations performed by the producer are roughly 200 bytes overhead per message (if you pass MSG_F_COPY the payload will also be allocated). Then there's some temporary larger allocations when batches/requests are being sent.

Make sure to call rd_kafka_poll() to serve delivery reports and automatically free resources for delivered messages.

**Comment by styphnate** [comment]
Poll(0) is being called after every produce. What I can see is that even though I always have roughly 300 messages in my queue the memory consumption of the application increases up to a point where my theory is that the whole buffer has been allocated. If I decrease the size of the buffer to the size I wrote in this post I will only consume more memory for a short while before I stop at a fixed amount.

**Comment by edenhill** [comment]
Suggest running your application with a memory leak detector, such as
valgrind

Den ons 12 dec. 2018 13:57 skrev styphnate <notifications@github.com>:

**Comment by styphnate** [comment]
Valgrind shows no leaks.

**Comment by edenhill** [comment]
Okay, then enable librdkafka statistics and see if there are any internal gauge metrics that don't go down even if you stop producing.

**Comment by shubhangiam** [comment]
how to enable statistics in librdkafka

**Comment by shubhangiam** [comment]
RAM seems to be increasing due to lag on consumer side may be.... but it never goes down

**Comment by edenhill** [comment]
RSS or VIRT?
Are there messages in the consumer queues?

**Comment by shubhangiam** [comment]
RSS keeps on increasing..... yes there are lots of msgs in consumer queue .. have used kafka-console-producer.sh to send 1500 packets per second with the help of tshark.... on the consumer side , after polling one by one , copying it in message queue and then destroying msg.... but if somehow things get delayed or increases packets per second, RSS keeps on increasing and never gets decreased .

**Comment by shubhangiam** [comment]
from few posts, memory will keep on increasing as internal buffers are getting allocated for those may msgs ...but even after consuming it, memory doesnot decrease on the consumer side.

**Comment by shubhangiam** [comment]
from few posts, I understand that memory will keep on increasing as internal buffers are getting allocated for those may msgs ...but even after consuming it, memory does not decrease on the consumer side .

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#explain-the-consumers-memory-usage-to-me

**Comment by shubhangiam** [comment]
I have refered this article ...but still at some point , it skips thru these values and add more memory in the fetch .... any idea how frequently  rd_kafka_toppar_fetch_decide function gets called ..

**Comment by shubhangiam** [comment]
@edenhill I tried to configure those parameter mentioned in the article. But my concern is somewhere after some time, message is getting consummed within period of max 10 sec , still why memory never decreases. after consuming the messages, allocated buffer should be deleted right ...... pls let me know if my understanding is correct or not ....
