### ISSUE TITLE
about thread safe

### ISSUE THREAD

**Issue by Yrp** [edenhill/librdkafka#215]
hi, edenhill
  RdKafka::Producer::create(), RdKafka::Topic::create(), RdKafka::Producer::produce().The three function is thread safe? 
10 thread in my program use them.
thank u!

**Comment by Yrp** [comment]
if not , how to do? thank u again.

**Comment by edenhill** [comment]
The librdkafka is completely thread safe (unless otherwise noted).
The three functions you mention are thread safe.

**Comment by Yrp** [comment]
in my demo, sending every message will call both RdKafka::Topic::create() and RdKafka::Topic::create(), then call producer->produce() and producer->outq_len().
Whether resources not released maybe?

**Comment by edenhill** [comment]
Producer, Consumer and Topic handles should be long lived.
I.e., you should typically create them when your application starts and keep using them for the duration of your program, and finally when shutting down your app you wait for outq_len() to become 0 and then destroy the handles.

**Comment by Yrp** [comment]
yes, you are right.i will do it as you say.

**Comment by Yrp** [comment]
Thank you very much ,i have solved it.

**Comment by edenhill** [comment]
Great!
