### ISSUE TITLE
cannot find -lcrypto on sles11 build

### ISSUE THREAD

**Issue by senthilkumar87** [edenhill/librdkafka#2151]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<getting issue "cannot find -lcrypto">

please find below error 

dl.o rdkafka_plugin.o -o librdkafka.so.1 -lm -lcrypto -ldl -lz   -L/usr/local/lib -lz   -ldl -lpthread -lrt
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib64/gcc/x86_64-suse-linux/4.3/../../../libcrypto.so when searching for -lcrypto
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib64/gcc/x86_64-suse-linux/4.3/../../../libcrypto.a when searching for -lcrypto
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib64/libcrypto.so when searching for -lcrypto
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib64/libcrypto.a when searching for -lcrypto
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: cannot find -lcrypto
collect2: ld returned 1 exit status
make[1]: *** [librdkafka.so.1] Error 1
make[1]: Leaving directory `/root/c/src'
make: *** [libs] Error 2

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v1.0.0-RC4-5>`
 - [X] Apache Kafka version: `NA`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `SLES11`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please provide the output from `./configure`

**Comment by senthilkumar87** [comment]
@4e9ebfbee5aa:/root/c # ./configure --mbits=32 --prefix=/root/c/librdkafka32
checking for OS or distribution... ok (Linux)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking for mbits compiler flag (-m32)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... failed
checking for __atomic_32_lib (by compile)... failed
checking for __sync_32 (by compile)... failed (disable)
checking for __atomic_64 (by compile)... failed
checking for __atomic_64_lib (by compile)... failed
checking for __sync_64 (by compile)... failed (disable)
checking for socket (by compile)... ok
parsing version '0x01000002'... ok (1.0.0)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for c11threads (by pkg-config)... failed
checking for c11threads (by compile)... failed (disable)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for zlib (by compile)... ok (cached)
checking for libcrypto (by pkg-config)... ok
checking for libcrypto (by compile)... ok (cached)
checking for libzstd (by pkg-config)... failed
checking for libzstd (by compile)... failed (disable)
checking for libm (by pkg-config)... failed
checking for libm (by compile)... ok
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for rapidjson (by compile)... failed (disable)
checking for libssl (by pkg-config)... ok
checking for libssl (by compile)... ok (cached)
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... failed (disable)
checking for libsasl (by pkg-config)... failed
checking for libsasl (by compile)... failed (disable)
checking for crc32chw (by compile)... failed (disable)
checking for regex (by compile)... ok
checking for strndup (by compile)... ok
checking for strerror_r (by compile)... ok
checking for pthread_setname_gnu (by compile)... failed (disable)
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /root/c/librdkafka32
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_LZ4_EXT           y
  ENABLE_SSL               y
  ENABLE_SASL              y
  MBITS                    32
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               Linux
  SOLIB_EXT                .so
  CC                       gcc
  CXX                      g++
  CPPFLAGS                 -m32 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  LDFLAGS                  -m32
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      1.0.0
  MKL_APP_VERSION          1.0.0
  LIBS                     -lssl -lcrypto -ldl -lz   -lm -lcrypto -ldl -lz   -L/usr/local/lib -lz   -ldl -lpthread -lrt
  CFLAGS                   -I/usr/local/include
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /root/c/librdkafka32
  bindir                   /root/c/librdkafka32/bin
  sbindir                  /root/c/librdkafka32/sbin
  libexecdir               /root/c/librdkafka32/libexec
  datadir                  /root/c/librdkafka32/share
  sysconfdir               /root/c/librdkafka32/etc
  sharedstatedir           /root/c/librdkafka32/com
  localstatedir            /root/c/librdkafka32/var
  libdir                   /root/c/librdkafka32/lib
  includedir               /root/c/librdkafka32/include
  infodir                  /root/c/librdkafka32/info
  mandir                   /root/c/librdkafka32/man
Generated config.cache

Now type 'make' to build

is it mandatory to have libsssl.?

**Comment by edenhill** [comment]
This seems to be a problem with --mbits=32: it is trying to link the x64 version of libcrypto.
Will look into this, but make sure you have the 32-bit version of libcrypto installed.

**Comment by edenhill** [comment]
Out of curiosity, why are you building for 32 bit?

**Comment by senthilkumar87** [comment]
all the other dependent libraries are 32 bits.

**Comment by senthilkumar87** [comment]
issue resolved it seems after installing libcrypto and libssl library
