### ISSUE TITLE
Question regarding throttling

### ISSUE THREAD

**Issue by accelerated** [edenhill/librdkafka#2153]
This is referring to the rdkafka version 0.11.6
Kafka broker version 1.1.1

What is the recommended behavior for producers and consumers when they get throttled?
**Producer**: 
Pausing a producer via `rd_kafka_pause_partitions` from publishing to those partitions seems to make sense as rdkafka stops sending batches out. This also enables the application to continue producing messages which simply get enqueued in the rdkafka partition queues. Or is it better to _not_ pause, and simply produce less?

**Consumer**:
From what I understood, when pausing a consumer with `rd_kafka_pause_partitions`, the fetcher stops and the batched messages which have been locally fetched are purged. However pausing the consumer may not be the best approach because when the consumer is resumed (after throttle period expires), the fetcher will re-fetch a new batch, which puts pressure on the broker, causing it potentially to throttle the consumer again, which will pause/resume then throttle again, etc...getting stuck in a bad cycle. If instead of pausing the consumer, the application polls at longer intervals, this can have an impact on events and heartbeats as they are now serviced slower. So what exactly is recommended in such a case?

Also the throttle callback documentation says:
 > Callbacks are triggered whenever a non-zero throttle time is returned by the broker, or when the throttle time drops back to zero.

Does this mean that _rdkafka_ keeps track of the throttled amount and when the period reaches 0, it calls the `throttle_cb` with 0? Or is the 0 throttle issued by the broker? I have noticed that the 0 throttle does not always get called. Initially I was relying on this for resuming the producers and consumers but there were many occasions when that 0 throttle never came. Any possible explanations for this?

**Comment by edenhill** [comment]
Before broker version 2.0 throttling was always performed by the broker, it would delay processing the request, and the client would wait for the response.

The throttle callback simply forwards the time the broker spent throttling the request.
Throttle of 0 is only emitted when the previous throttle value was > 0.

With >= 2.0, and KIP-219, the client can now enforce the throttling by slowing its rate down as instructed by the broker. This is however not yet implemented by librdkafka (planned for early next year).

As for the application; you generally don't need to do anything with the client itself, the client is already being paced by the broker.
But you might want to backpressure the data source, if possible.
If the data source supports it you could either do it when you get a throttling callback, but perhaps preferably when the local producer queue gets full (ERR__QUEUE_FULL), which is a more generic way to handle backpressure, regardless if the broker is throttling or not. Adjust the producer queue size accordingly.

**Comment by accelerated** [comment]
Thanks for the clarification @edenhill! So with broker version > 2.0 will the planned rdkafka changes include a new set of APIs or will it be a different handling of the throttle callback?

> Throttle of 0 is only emitted when the previous throttle value was > 0. 

Just to be clear, this does not happen all the time so there may be a bug in the throttle handling logic. I can't reproduce it always, but based on logs put inside the throttle callback, the 0 throttle is not generated every time.

**Comment by edenhill** [comment]
I don't think support for KIP-219 warrants any API changes, the only difference is that the client can do the rate-limiting itself (the broker will still do it if the client does not), which helps avoiding timeouts for sub-sequent requests. Though in practice, it will probably require a low max.in.flight to work well.

Here's the zero-edge, otherwise-level, -triggered throttle triggering code:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_op.c#L593

**Comment by accelerated** [comment]
Yes, seems like the logic in `rd_kafka_op_throttle_time` is good and I also checked everywhere it's called and it just seems like it's passing along what it gets from the broker, so that means the broker has not sent a 0 throttle back. Could that be case?

**Comment by edenhill** [comment]
So you are saying you receive throttle_cb with throttle time of >0 ms, but sometimes you don't get a 0? Do you get other >0 values after this, or do they also stop?

**Comment by edenhill** [comment]
Using debug=protocol might be a good way to troubleshoot this further by looking at the rtt's of each response, anything above the typical roundtrip would indicate throttling

**Comment by accelerated** [comment]
> So you are saying you receive throttle_cb with throttle time of >0 ms, but sometimes you don't get a 0? Do you get other >0 values after this, or do they also stop?

Correct. The times where I could actually get throttled, the throttle time increases and then stops. In a few cases I got throttled a few times, got a 0, throttled a few more times, then nothing. I will use the debug=protocol flag and I'll see. Will circle back if I have more relevant information. Thanks a lot for the assistance!!
