### ISSUE TITLE
Retrying MetadataRequest (v2, 33 bytes, retry 0/2, prev CorrId 0) in 100ms

### ISSUE THREAD

**Issue by smartdu** [edenhill/librdkafka#2156]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

MetadataRequest Always trying again

log:
[REQTMOUT] [thrd:kafka-hs.default.svc.cluster.local:9093/bootstrap]: kafka-hs.default.svc.cluster.local:9093/bootstrap: Timed out 0 in-flight, 1 retry-queued, 0 out-queue, 0 partially-sent requests
[REQERR] [thrd:main]: kafka-hs.default.svc.cluster.local:9093/bootstrap: MetadataRequest failed: Local: Timed out in queue: actions Retry
[RETRY] [thrd:kafka-hs.default.svc.cluster.local:9093/bootstrap]: kafka-hs.default.svc.cluster.local:9093/bootstrap: Retrying MetadataRequest (v2, 33 bytes, retry 0/2, prev CorrId 0) in 100ms
[REQTMOUT] [thrd:kafka-hs.default.svc.cluster.local:9093/bootstrap]: kafka-hs.default.svc.cluster.local:9093/bootstrap: Timed out 0 in-flight, 1 retry-queued, 0 out-queue, 0 partially-sent requests
[REQERR] [thrd:main]: kafka-hs.default.svc.cluster.local:9093/bootstrap: MetadataRequest failed: Local: Timed out in queue: actions Retry

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.6`
 - [ ] Apache Kafka version: `kafka_2.12-2.0.0`
 - [ ] librdkafka client configuration: `session.timeout.ms=30000,batch.num.messages=5,debug=all,message.timeout.ms=10000`
 - [ ] Operating system: `Centos 7 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That looks like a connectivity or auth issue.
