### ISSUE TITLE
RdKafka::Consumer::create function can not get network disconnect

### ISSUE THREAD

**Issue by AlwaysOnline666** [edenhill/librdkafka#2158]
if i use RdKafka::KafkaConsumer to create consumer and use consumer->start(topic, partition, start_offset);
when i network disconnect，kafka cant find network is disconnect，but if i use RdKafka::KafkaConsumer::create and  RdKafka::Message *msg = consumer->consume(1000); when i network disconnect i can find it。 so i want ask: if i use the first function i can find EVENT_ERROR。
i know the first function is old version， so the old version is not this function
thanks。

**Comment by AlwaysOnline666** [comment]
Description
===========
<your issue description goes here>


How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>


**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.


Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<0.11.4>`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The client is asynchronous, it will connect to brokers from background threads.
So the constructor/factory/init function will not fail if the brokers are not available, this would prevent consumers from being started when brokers are down, which wouldn't be very practical.

Register an event handler and check for EVENT_ERROR.

Generally speaking you do not need to take any action on these errors, they are informational. The client will automatically try to recover from all errors.

**Comment by AlwaysOnline666** [comment]
yes I know。i Register event handler and check for EVENT_ERROR. it is  my fault。 my mean is when i use RdKafka::Consumer and register an event handler and check for EVENT_ERROR， but can’t catch EVENT_ERROR when I use RdKafka::KafkaConsumer::create  I can catch.I want confirm this result because of  RdKafka::Consumer is old version  so it‘s not this function。
And just now i find a problem when i disconnect Ethernet network kafka can catch EVENT_ERROR but if
disconnect wlan kafka event handler cant catch error 
I kown The client will automatically try to recover from all errors. but I want to try print log when kafka discoonect so I need your help 
very thanks。

**Comment by AlwaysOnline666** [comment]
yes I know。i Register event handler and check for EVENT_ERROR. it is  my fault。 my mean is when i use RdKafka::Consumer and register an event handler and check for EVENT_ERROR， but can’t catch EVENT_ERROR when I use RdKafka::KafkaConsumer::create  I can catch.I want confirm this result because of  RdKafka::Consumer is old version  so it‘s not this function。
And just now i find a problem when i disconnect Ethernet network kafka can catch EVENT_ERROR but if
disconnect wlan kafka event handler cant catch error 
I kown The client will automatically try to recover from all errors. but I want to try print log when kafka discoonect so I need your help 
very thanks。

**Comment by edenhill** [comment]
`..start()` will not trigger callbacks, You will need to call consume() or poll() for (error) callbacks to be triggered

**Comment by edenhill** [comment]
Maybe it just takes longer for the network stack to detect errors on the wifi interface.
This is outside the scope of librdkafka.
