### ISSUE TITLE
DNS resolution at bootstrap retried only once

### ISSUE THREAD

**Issue by dgregoire** [edenhill/librdkafka#2159]
Description
===========
Kafka DNS resolution retried once and then never again at bootstrap, no errors are returned by `NewConsumer()` or `Subscribe()`.

kube-dns can go down at any time for any amount of time and trigger this.

librdkafka 0.11.4-r1 / go 1.11.2

How to reproduce
================
Setup brokers with an inexistant DNS record.

```
%3|1545116782.982|FAIL|rdkafka#consumer-1| [thrd:kafka-bootstrap.backbone:9092/bootstrap]: kafka-bootstrap.backbone:9092/bootstrap: Failed to resolve 'kafka-bootstrap.backbone:9092': Try again
%3|1545116782.982|ERROR|rdkafka#consumer-1| [thrd:kafka-bootstrap.backbone:9092/bootstrap]: kafka-bootstrap.backbone:9092/bootstrap: Failed to resolve 'kafka-bootstrap.backbone:9092': Try again
%3|1545116782.982|ERROR|rdkafka#consumer-1| [thrd:kafka-bootstrap.backbone:9092/bootstrap]: 1/1 brokers are down
```

Checklist
=========

 - [x] librdkafka version (release number or git tag): `0.11.4-r1`
 - [x] Apache Kafka version: `1.0.1`
 - [x] librdkafka client configuration:
```
              <"bootstrap.servers":  kafka-bootstrap.backbone:909),
		"group.id":                "some-group-id",
		"go.events.channel.size":   50,
		"auto.offset.reset":        "earliest",
		"enable.auto.commit":       false,
		"go.events.channel.enable": true,
```
 - [x] Operating system: `Container-Optimized OS from Google `
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
It will re-resolve the address on each re-connect attempt, but it will not log equal sub-sequent errors.
