### ISSUE TITLE
Difficulty linking librdkafka/librdkafka++ with g++

### ISSUE THREAD

**Issue by FoxbatHeavyIndustries** [edenhill/librdkafka#216]
I'm attempting to use librdkafka with an existing body of C++ code. During the link phase g++ seems unable to resolve any of the librdkafka symbols.

My test code:
````
#include <stdio.h>
#include <librdkafka/rdkafka.h>
int main(int , char **) {
  int kvers = rd_kafka_version();
  fprintf(stdout, "Librdkafka vers: %d\n", kvers);
    return 0;
}
````

Compile output:
````
g++ -c -pipe -g -Wall -W -DHAVE_NAMESPACE_STD -DHAVE_CXX_STRING_HEADER -DDLLIMPORT= -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -o main.o main.cpp
g++  -o kafkatest main.o     -lrdkafka++ -L/usr/local/lib -lrdkafka -L/usr/local/lib -lpthread -lz -lrt 
main.o: In function `main':
main.cpp:6: undefined reference to `rd_kafka_version()'
collect2: error: ld returned 1 exit status
````

I have tried reversing the order the two libraries are fed to the linker to no avail. 
I can link librdkafka with gcc, if main.cpp is copied to main.c:
````
gcc -c -pipe -g -Wall -W -DHAVE_NAMESPACE_STD -DHAVE_CXX_STRING_HEADER -DDLLIMPORT= -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -o main.o main.c
g++  -o kafkatest main.o     -lrdkafka++ -L/usr/local/lib -lrdkafka -L/usr/local/lib -lpthread -lz -lrt
````

./kafkatest
Librdkafka vers: 525568

This also works:
  gcc -o kafkatest main.o     -lrdkafka++ -L/usr/local/lib -lrdkafka -L/usr/local/lib -lpthread -lz -lrt
./kafkatest
Librdkafka vers: 525568

I am using the current master branch of librdkafka with 
gcc --version
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-7)
The system is Fedora core 20.

Please advise.
Thank you
           ^

**Comment by edenhill** [comment]
If you want to include the C-headers (rdkafka.h) in your C++ program you need to declare them as extern "C", as so:
````
#include <stdio.h>
extern "C" {
#include <librdkafka/rdkafka.h>
}

int main(int , char **) {
  int kvers = rd_kafka_version();
  fprintf(stdout, "Librdkafka vers: %d\n", kvers);
    return 0;
}
````

**Comment by edenhill** [comment]
Typically you should be fine with just the C++ headers (rdkafkacpp.h) and use the C++ API, but if you are after the missing pieces (metadata retrieval) you will need to use rdkafka.h too for now.

**Comment by kodekarl** [comment]
Someone (well: I) might argue that the C header should handle that extern'ing on its own? Want a pull request for that? ;-)

**Comment by edenhill** [comment]
@kodekarl You are probably right!

**Comment by FoxbatHeavyIndustries** [comment]
Thanks, that dealt with it.

I most likely will be using meta data. Beyond that how complete/stable is the C++ interface. The documentation seems to imply that it is not as mature as the C interface.

**Comment by edenhill** [comment]
The C interface is guaranteed to be both API and ABI stable,
while the C++  interface has not reached that step yet it is unlikely to change.
