### ISSUE TITLE
Solaris 10 i386, gcc 3.4.3, librdkafka 0.11.6

### ISSUE THREAD

**Issue by roblos** [edenhill/librdkafka#2165]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
librdkafka.a compiled on Solaris 10 but the lib used in a homemade C program but ld gives error:

Undefined                       first referenced
 symbol                             in file
__clzdi2                            /home/s/lib/4.7000/librdkafka.a(lz4hc.o)
__ctzdi2                            /home/s/lib/4.7000/librdkafka.a(lz4hc.o)
ld: fatal: symbol referencing errors. No output written to /home/s/syp//leosread
**** BLD_ERR **** (status=2, : /home/s/syp//leosread)
-- (ERROR) /home/s/syp//leosread: bad executable, deleting!
gmake: *** [/home/s/syp//leosread] Error 2

What do I miss ?

How to reproduce
================
lidrdkafka 0.11.6 compiled as folows on Solaris 10:

>isainfo -v
64-bit amd64 applications
        avx xsave pclmulqdq aes sse4.2 sse4.1 ssse3 popcnt tscp cx16 sse3 sse2
        sse fxsr mmx cmov amd_sysc cx8 tsc fpu
32-bit i386 applications
        avx xsave pclmulqdq aes sse4.2 sse4.1 ssse3 popcnt tscp cx16 sse3 sse2
        sse fxsr mmx cmov sep cx8 tsc fpu

> gcc --version
gcc (GCC) 3.4.3 (csl-sol210-3_4-branch+sol_rpath)
Copyright (C) 2004 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

> gmake --version
GNU Make 3.82
Built for i386-pc-solaris2.10
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

actions done:

- change configure.librdkafka, add with "if [[ $MKL_DISTRO == "SunOS" ]]; then"
        mkl_mkvar_append CFLAGS CFLAGS "-Dsun"
        mkl_mkvar_append CFLAGS CFLAGS "-D__sun"
        mkl_mkvar_append CFLAGS CFLAGS "-D_XPG6"
- rd_kafka_features2str function changed in src/rdkafka_feature.c -=> code commented because of gcc internal error. Code changed into: return "nvt";
		
./configure --clean
./configure --prefix /etsi/work/gli/kafka/librdkafka-master --exec-prefix=/etsi/work/gli/kafka/librdkafka-master/local --includedir=/usr/include --cc=/opt/SUNWspro/bin/cc --cxx=/opt/SUNWspro/bin/CC --mbits=64 --enable-static --disable-ssl

gmake

lib src/librdkafka.a is created !

cp src/librdkafka.a /home/SpecLib

--> build homemade C program:

VMAIOT#spsy|leosread> bld
-- bld    (DIR=/home/spsy/roblos/kafka/leosread)
-- cd /home/s/bld/leosread/check
-- /usr/sfw/bin/gmake -ref /home/s/bld/leosread/check/Makefile all
--
-- CC -H 2>$dep '-DL_ENDIAN=1' '-DLP64' '-D_64BIT_' '-DSOLARIS_2_0=1' '-DOS_SOLARIS=51000' '-DSPEC_SUBSYSTEM_TREE=1' '-DSOL_SPECTRUM=1' '-DOSVERSION=51000' '-DSUBS_CAMA=1' '-DSUBS_DMS=3' '-DSUBS_ICCP=1' '-DSUBS_IFS=1' '-DSUBS_PROJECT=1' '-DSUBS_RELEASE=470' '-DSUBS_SDB=1' '-DSUBS_TC=1' '-DSUBS_TOPOL=2' '-DSUBS_UI=1' '-D_POSIX_C_SOURCE=200112L' '-D_XOPEN_SOURCE' '-D__EXTENSIONS__' '-I/home/spsy/roblos/kafka/leosread' '-I/home/spsy/roblos/kafka/librdkafka-0.11.6/src' '-I/home/s/src' '-I/home/s/src/code' '-I/home/s/src/include' '-I/home/s/cmp/I' '-errtags' '-g' '-xport64=implicit' '-erroff=signextwarn' '-m64' '-c' /home/spsy/roblos/kafka/leosread/leosread.cxx
"/home/spsy/roblos/kafka/librdkafka-0.11.6/src/rdkafka.h", line 476: Warning, identexpected: Identifier expected instead of "}".
"/home/spsy/roblos/kafka/librdkafka-0.11.6/src/rdkafka.h", line 573: Warning, attrskipunsup: attribute deprecated is unsupported and will be skipped..
"/home/spsy/roblos/kafka/librdkafka-0.11.6/src/rdkafka.h", line 589: Warning, attrskipunsup: attribute deprecated is unsupported and will be skipped..
"/home/spsy/roblos/kafka/librdkafka-0.11.6/src/rdkafka.h", line 812: Warning, identexpected: Identifier expected instead of "}".
"/home/spsy/roblos/kafka/librdkafka-0.11.6/src/rdkafka.h", line 1105: Warning, attrskipunsup: attribute unused is unsupported and will be skipped..
"/home/spsy/roblos/kafka/librdkafka-0.11.6/src/rdkafka.h", line 3545: Warning, attrskipunsup: attribute deprecated is unsupported and will be skipped..
"/home/spsy/roblos/kafka/librdkafka-0.11.6/src/rdkafka.h", line 5106: Warning, identexpected: Identifier expected instead of "}".
"/home/spsy/roblos/kafka/librdkafka-0.11.6/src/rdkafka.h", line 5195: Warning, identexpected: Identifier expected instead of "}".
8 Warning(s) detected.
-- (Info) Dependency for leosread.cxx updated
--
-- (Info) Linking with libraries in /home/s/lib/4.7000.
-- CC -L/home/s/lib/4.7000 -i '-m64' leosread.o -R/home/SpecLib -lrdkafka -lz -lpthread -lrt -lsasl -lSPEC -lDBA -lBASE -lrt -lsocket -lnsl -lkstat -lkvm -lelf -lCstd -o /home/s/syp//leosread
Undefined                       first referenced
 symbol                             in file
__clzdi2                            /home/s/lib/4.7000/librdkafka.a(lz4hc.o)
__ctzdi2                            /home/s/lib/4.7000/librdkafka.a(lz4hc.o)
ld: fatal: symbol referencing errors. No output written to /home/s/syp//leosread
**** BLD_ERR **** (status=2, : /home/s/syp//leosread)
-- (ERROR) /home/s/syp//leosread: bad executable, deleting!
gmake: *** [/home/s/syp//leosread] Error 2

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You mention that this is on i386, but your program is built for 64-bit.
Is librdkafka built with -m64 as well?
Also make sure you use the same linker for both librdkafka and your program.

**Comment by roblos** [comment]
In the meantime this was resolved. Thanks.
