### ISSUE TITLE
higher cpu  usage,v1.0.0-RC5(gcc 4.6.4,O2,tcmalloc) 

### ISSUE THREAD

**Issue by XLPE** [edenhill/librdkafka#2167]
V0.11.4 has always been suspected of having a memory leak，I switched the librdkafka from 0.11.4 to v1.0.0-RC5, V1.0.0-RC5 memory usage is lower,but  cpu load  doubled.

V0.11.4
the result of perf top
-------------------------------------------------------------------
 10.12%  libpthread-2.23.so    [.] __lll_lock_elision
   7.06%  MetricExchangeServer  [.] rd_kafka_snappy_uncompress_iov
   5.33%  libc-2.23.so          [.] __memcmp_sse4_1
   5.20%  libpthread-2.23.so    [.] __lll_unlock_elision
   5.11%  libstdc++.so.6.0.21   [.] std::string::compare
   3.77%  MetricExchangeServer  [.] rd_kafka_snappy_compress_iov
   3.64%  libc-2.23.so          [.] __memcpy_avx_unaligned
   3.64%  libc-2.23.so          [.] memchr
   3.29%  libstdc++.so.6.0.21   [.] std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string
   2.75%  MetricExchangeServer  [.] MetricCallBack::metricStat
   2.35%  MetricExchangeServer  [.] rd_slice_read
   2.18%  MetricExchangeServer  [.] operator new[]
   1.87%  MetricExchangeServer  [.] rd_slice_reader0
   1.82%  libpthread-2.23.so    [.] __pthread_rwlock_rdlock
   1.64%  libstdc++.so.6.0.21   [.] std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string
   1.47%  MetricExchangeServer  [.] tc_deletearray_nothrow
   1.24%  [kernel]              [k] __lock_text_start
   1.24%  libpthread-2.23.so    [.] __pthread_rwlock_wrlock
   1.11%  [vdso]                [.] 0x000000000000097e
   1.11%  libpthread-2.23.so    [.] pthread_mutex_lock
   1.07%  MetricExchangeServer  [.] rd_varint_dec_slice

v1.0.0-RC5
the result of perf top
---------------------------------------------------------------------------------
 11.40%  libpthread-2.23.so    [.] __lll_lock_elision
   7.65%  [kernel]              [k] __lock_text_start
   4.19%  MetricExchangeServer  [.] decompress_all_tags
   3.61%  libpthread-2.23.so    [.] __lll_unlock_elision
   3.10%  MetricExchangeServer  [.] rd_slice_reader0
   2.97%  libc-2.23.so          [.] __memcmp_sse4_1
   2.78%  MetricExchangeServer  [.] unaligned_copy64
   2.67%  MetricExchangeServer  [.] compress_fragment
   2.48%  libpthread-2.23.so    [.] __pthread_rwlock_wrlock
   2.40%  libstdc++.so.6.0.21   [.] std::string::compare
   2.20%  libc-2.23.so          [.] __memcpy_avx_unaligned
   1.98%  MetricExchangeServer  [.] rd_slice_abs_offset
   1.96%  libc-2.23.so          [.] memchr
   1.94%  libpthread-2.23.so    [.] pthread_mutex_lock
   1.80%  MetricExchangeServer  [.] writer_append_from_self
   1.77%  [kernel]              [k] finish_task_switch
   1.77%  libstdc++.so.6.0.21   [.] std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string
   1.65%  MetricExchangeServer  [.] rd_slice_read
   1.43%  MetricExchangeServer  [.] MetricCallBack::metricStat
   1.35%  MetricExchangeServer  [.] rd_kafkap_str_cmp_str
   1.24%  MetricExchangeServer  [.] rd_kafka_toppar_producer_serve
   1.07%  libpthread-2.23.so    [.] __pthread_rwlock_rdlock
   1.05%  MetricExchangeServer  [.] operator new[]
   1.03%  MetricExchangeServer  [.] tc_deletearray_nothrow
   0.91%  MetricExchangeServer  [.] find_match_length
   0.89%  MetricExchangeServer  [.] incremental_copy_fast_path
   0.77%  MetricExchangeServer  [.] writer_try_fast_append
   0.72%  libstdc++.so.6.0.21   [.] std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string
   0.69%  MetricExchangeServer  [.] hash_bytes
   0.67%  [vdso]                [.] 0x000000000000097e
   0.66%  [kernel]              [k] ipt_do_table
   0.60%  MetricExchangeServer  [.] tc_calloc
   0.59%  MetricExchangeServer  [.] rd_kafka_msgset_reader_msg_v2
   0.56%  libstdc++.so.6.0.21   [.] std::string::find_first_of
   0.53%  MetricExchangeServer  [.] rd_varint_dec_slice

**Comment by edenhill** [comment]
Could you try to v0.11.6, or preferably v1.0.0-RC5? (https://www.nuget.org/packages/librdkafka.redist/1.0.0-RC5)
