### ISSUE TITLE
What is the meaning of "rd" in rd_kafka?

### ISSUE THREAD

**Issue by tamama** [edenhill/librdkafka#2168]
Hi there,

May I ask for the meaning of "rd" in rd_kafka?
I can't find anything in the FAQ...

Kind regards,
Tamama

**Comment by edenhill** [comment]
librdkafka originally stems from [librd](https://github.com/edenhill/librd), which was my contractor toolbox.
The 'rd' stands for 'rapid development'.

In hindsight librdkafka should have been named simply libkafka.

**Comment by tamama** [comment]
Thanks, now that makes sense.
