### ISSUE TITLE
Thread concurrence for 1 external broker producer/consumer

### ISSUE THREAD

**Issue by nachopol** [edenhill/librdkafka#2170]
Hi @edenhill. I'm trying to port librdkafka to OpenVOS (I read other threads and I know this OS is not supported). Anyway, I could compile it and successfully test two instances of the example rdkafka_example program as a producer and a consumer respectively using an external broker in a win Kafka installation.

According what I've understood in the FAQs, having in mind the following architecture each instance should have 2 threads (the main and the per-broker ones):
- Kafka broker in an external server
- Producer or Consumer separate instances conected to one sole broker

In this architecture, will it work a #define RD_TLS  https://github.com/edenhill/librdkafka/issues/2014#issuecomment-426740874
or is it going to break at any point?

Thanks in advance

**Comment by write2jaydeep** [comment]
Hey @nachopol 
it works perfectly fine. if you know that openVOS has separate scope per threads for static variables. This directive works well for me. 

Thanks
JD

**Comment by write2jaydeep** [comment]
hi @nachopol  
if you could help me I would like you to perform a few tests to observer RTT time.
Can you please enable 'protocol' debug and produce some messages using simple_producer.c. Please put statistics here. (RTT). so far minimum I am able to achieve RTT is 30ms. 
I have put the question [here](https://github.com/edenhill/librdkafka/issues/1553#issuecomment-450083900)
I appreciate your help!
We can keep in touch on write2jaydeep@gmail.com

Thanks
JD

**Comment by nachopol** [comment]
Hi @write2jaydeep, thanks for answering. 
I haven't found anything about the scope behaviour you talk about in stratadoc website (do you have the exact reference?).
Anyway, as far as I understand, there are still two non-static RD_TLS variable declaration:
`rd_kafka_resp_err_t RD_TLS rd_kafka_last_error_code;` in **rdkafka.c**
`int RD_TLS rd_kafka_yield_thread = 0;` in **rdkafka_queue.c**

**Comment by edenhill** [comment]
@nachopol Defining RD_TLS to nothing will not work, any code that is marked with RD_TLS needs its thread-local-storage, or must be rewritten in a way that does not use TLS (which most likely involves changes to the internal or public API).
