### ISSUE TITLE
New release 1.0.0 ?

### ISSUE THREAD

**Issue by MartinX3** [edenhill/librdkafka#2172]
Needed for this issue
https://github.com/edenhill/kafkacat/issues/145

Is there any ETA?

**Comment by billygout** [comment]
+1

**Comment by edenhill** [comment]
Both issues that are stalling the v1.0.0 release, #2163 and #2164 are fixed in #2188 and are currently being verified in integration and soak tests.
We're looking to make a new RC early next week.

**Comment by edenhill** [comment]
v1.0.0-RC6 is now available and ready for testing, please try it out and report your findings.

**Comment by billygout** [comment]
Thank you. Has this gone through your "soak testing"?

**Comment by edenhill** [comment]
Hey @billygout, the soak test for this version will run for two weeks , effectively started two days ago. 
There's also an older version that's been running since early December.

**Comment by billygout** [comment]
Thanks.

**Comment by scottsappen** [comment]
Nice. So probably 1.0.0 release sometime this month 'eh?

**Comment by edenhill** [comment]
Yes, that's the plan. Soak tests have been running fine for a week.
Need to sort out static builds of librdkafka for the Python and NuGet packages, which does not affect the code or stability itself.

**Comment by matthewbyrne** [comment]
Any update?

**Comment by edenhill** [comment]
Build and packaging issues are now fixed, final (hopefully) RC going out this week.

**Comment by MartinX3** [comment]
@edenhill And now? :P
