### ISSUE TITLE
What's the concrete behaviour of "enable.auto.commit"?

### ISSUE THREAD

**Issue by lxyscls** [edenhill/librdkafka#2179]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Time A, my application has been received a message. And at the meantime, the "auto.commit" has been reached. Does it mean that the background thread will commit the offset of message,  or it will only commit the offsets about "auto.commit.interval.ms" ago?
If my application crashed after commit but before handle the message, there will be risk to "lose" the message. Am I right?

Thank you very much, and sorry for my poor english.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.6
 - [x] Apache Kafka version: 0.10.2.1
 - [ ] librdkafka client configuration: N/A
 - [ ] Operating system: N/A
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#offset-management
