### ISSUE TITLE
C++ API, std::string-less interface for keys?

### ISSUE THREAD

**Issue by rthalley** [edenhill/librdkafka#218]
I am using keyed messages, and for my purposes, I'd much prefer the same interface as is used for payloads, i.e. pointer + length, rather than the std::string *.  The std::string requires me to contort my code a bit and do extra copies.  I'm fine with keeping the std::string interface available, but if I could have accessors and a variant of produce(), I'd be happy.  If you agree this is OK, I can probably make a patch.

**Comment by edenhill** [comment]
I had a hard time deciding if the key interface should be payload,len or std::string but finally decided on std::string since strings are most likely always simple strings, and we all know what assumptions mean.

So I'd be happy to accept a pullreq for an additional binary ptr,len key interface.

**Comment by DEvil0000** [comment]
this is the same right?
#220
merged with:
fca0cf58097b137fd5eed3ff3f9fe21aa6e44112

**Comment by edenhill** [comment]
Yep, thanks.
