### ISSUE TITLE
Immediate and proper termination

### ISSUE THREAD

**Issue by mohansella** [edenhill/librdkafka#2180]
Hi edenhill, thanks for this cool library!

I have a doubt regarding the proper termination of librdkafka. I am using librkafka for a producer. I just need to store the messages of in-memory queue which are not sent to the broker during shutdown. I can see it can be easily handled with the callback registration (`rd_kafka_conf_set_dr_msg_cb`). In the wiki, it shows to do like `while (rd_kafka_outq_len(rk) > 0) rd_kafka_poll(rk, 50)` . This works fine as expected when broker available during shutdown but blocks until the timeout expire which is very long (i guess default linger.ms=15min). after analyzing that, i dont want to poll until the queue is empty even if broker is available(bcs there may be network delay).

But my question is, how to handle the situation when the broker is completely shutdown but to stop librkafka without delay and store the in-memory queue (the actual messages).

I tried to find the solution for this but cant. so, raising the question here.
If it is possible, please provide me some details in the right direction. if not , some workarounds can be helpful. note: my usecase is performance and fast shutdown without message loss.

**Comment by edenhill** [comment]
`rd_kafka_purge()` is what you need!
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L3452

**Comment by mohansella** [comment]
I don't understand. Even in the latest `1.0.0.-rc5`, I cannot find that method in `<release_zip>/src/rdkafka.h` but available in the master branch.

**Comment by edenhill** [comment]
I can see it in https://github.com/edenhill/librdkafka/archive/v1.0.0-RC5.zip

**Comment by mohansella** [comment]
sorry, my bad. it is available in the latest RC. thanks man.
