### ISSUE TITLE
Is offset_commit_cb called by the poll API or other background thread?

### ISSUE THREAD

**Issue by lxyscls** [edenhill/librdkafka#2182]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#threads-and-callbacks

I want to sync some informations in the offset_commit_cb. And those informations are collected in the same thread with the poll API.
So, if the offset_commit_cb is called by the poll API, there is no need to add lock.
But I can't find enough information about the situation from the INTRODUCTION.md.

Thank you very much!

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.6
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
All callbacks are triggered by *poll() unless otherwise noted (like log_cb that is triggered on internal librdkafka threads).

**Comment by lxyscls** [comment]
@edenhill
