### ISSUE TITLE
Broker Availability with list_group

### ISSUE THREAD

**Issue by zachCoder17** [edenhill/librdkafka#2184]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I am working with Kafka on the premise that we should check the availability of the Kafka broker before any messages are sent out into the network.  I have been told that using the list_groups() method would work to check the availability of the broker because it essentially pulls some metadata from the broker or times out if the broker is unavailable.  After doing some more research into this, the list_groups() method seems to never timeout if say the broker is down or the wrong broker address is given.  I have even tested this out on your test code because I was unsure if my code was setup correctly. 

How to reproduce
================
In your tests folder in 0019-list_groups.c, by commenting out the call to test_produce_msgs(…) call in the main method creates a situation where given a bad broker ip address or given a broker down event, list_groups() never times out.  From my observation this is because the test_produce_msgs() call eventually calls code that will call the poll method, which serves up any error.  What does seem to time out is the surrounding code that runs in the main thread.  
My question would be is this an error or is there some justification as to why the list_groups() method call never seems to time out.  Also, is this a fair assessment as to how to determine if the Kafka broker is up and running before sending any messages to the broker?  Lastly, would you have any other recommendations on checking the health of the broker?

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.5`
 - [ ] Apache Kafka version: `2.11-2.0.0`
 - [ ] librdkafka client configuration: `Ubuntu 16.04 LTS`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I'll look into the list_groups() hang, but I suggest you use rd_kafka_metadata() to query the cluster for liveness.

Generally, an application won't need to check if the cluster is available, but instead configure constraints for max delivery time by setting the `message.timeout.ms` configuration property for the maximum allowed time to produce a message. This abstracts all possible error cases and instead dictates what the maximum delivery time is based on the data itself, rather than relying on arbitrary cluster metadata.

**Comment by zachCoder17** [comment]
Okay, thanks.  I was able to get rd_kafka_metadata() to work.  I will need to think about if we should use  the message timeout, but its good to know that we can do it either way. And thanks, I would really like to know why the list_groups() doesn't time out.
