### ISSUE TITLE
Do consumers in different groups share the same topic:partition:offset?

### ISSUE THREAD

**Issue by lxyscls** [edenhill/librdkafka#2186]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have one producer which has produced 6 messages, they are "1hello", "2hello", ..., "6hello".
I set up one conusmer in "group1" to consume all the message.
But when I set up two other consumers in "group2" and "group3", they can't consume from the beginning, when I set "auto.offset.reset=beginning".
Is it make sense? I think consumers in different groups don't share the same topic:partition:offset.

How to reproduce
================
[root@node5 examples]# ./rdkafka_consumer_example -g group1 -b 172.21.1.18:9092 OFFSET_TEST:0 -O 
Topic "OFFSET_TEST" partition 0 offset 6
% Consumer closed
[root@node5 examples]# ./rdkafka_consumer_example -g group2 -b 172.21.1.18:9092 OFFSET_TEST:0 -O 
Topic "OFFSET_TEST" partition 0 offset -1001
% Consumer closed
[root@node5 examples]# ./rdkafka_consumer_example -g group3 -b 172.21.1.18:9092 OFFSET_TEST:0 -O 
Topic "OFFSET_TEST" partition 0 offset -1001
% Consumer closed
[root@node5 examples]# ./rdkafka_consumer_example -g group3 -b 172.21.1.18:9092 OFFSET_TEST:0 -X auto.offset.reset=beginning
% Assigning 1 partitions
% Consumer reached end of OFFSET_TEST [0] message queue at offset 6
^C% Consumer closed
[root@node5 examples]# ./rdkafka_consumer_example -g group1 -b 172.21.1.18:9092 OFFSET_TEST:0 -X auto.offset.reset=beginning 
% Assigning 1 partitions
% Consumer reached end of OFFSET_TEST [0] message queue at offset 6

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.6
 - [x] Apache Kafka version: 0.10.2.1
 - [x] librdkafka client configuration: auto.offset.reset=beginning`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is an issue with rdkafka_consumer_example, you need to specify topic properties with a "topic." prefix, as so: `... -X topic.auto.offset.reset=beginning`

**Comment by edenhill** [comment]
You need to specify -X before the list of topics

**Comment by lxyscls** [comment]
> 
> 
> I believe you need to specify -X before the list of topics

> [root@node5 examples]# ./rdkafka_consumer_example -g group3 -b 172.21.1.18:9092 -X topic.auto.offset.reset=beginning -O OFFSET_TEST:0
Topic "OFFSET_TEST" partition 0 offset -1001
% Consumer closed
[root@node5 examples]# ./rdkafka_consumer_example -g group3 -b 172.21.1.18:9092 -X topic.auto.offset.reset=beginning OFFSET_TEST:0   
% Assigning 1 partitions
% Consumer reached end of OFFSET_TEST [0] message queue at offset 6
^C% Consumer closed

The same situation. Thank you for your patient.

I have turned the "debug" on, the output is as below.

> [root@node5 examples]# ./rdkafka_consumer_example -X topic.auto.offset.reset=beginning -g group3 -b 172.21.1.18:9092 OFFSET_TEST:0 -X debug=consumer,cgrp,topic,fetch
1547545684.056 RDKAFKA-7-MEMBERID: rdkafka#consumer-1: [thrd:app]: Group "group3": updating member id "(not-set)" -> ""
1547545684.057 RDKAFKA-7-BRKREASSIGN: rdkafka#consumer-1: [thrd:main]: Group "group3" management reassigned from broker (none) to :0/internal
1547545684.057 RDKAFKA-7-INIT: rdkafka#consumer-1: [thrd:app]: librdkafka v0.11.6 (0xb06ff) rdkafka#consumer-1 initialized (builtin.features 0xffff, debug 0x2504)
1547545684.057 RDKAFKA-7-CGRPSTATE: rdkafka#consumer-1: [thrd:main]: Group "group3" changed state init -> wait-broker (v1, join-state init)
1547545684.057 RDKAFKA-7-BRKASSIGN: rdkafka#consumer-1: [thrd:main]: Group "group3" management assigned to broker :0/internal
% Assigning 1 partitions
1547545684.057 RDKAFKA-7-CGRPOP: rdkafka#consumer-1: [thrd:main]: Group "group3" received op ASSIGN (v0) in state wait-broker (join state init, v1 vs 0)
1547545684.057 RDKAFKA-7-ASSIGN: rdkafka#consumer-1: [thrd:main]: Group "group3": new assignment of 1 partition(s) in join state init
1547545684.057 RDKAFKA-7-TOPIC: rdkafka#consumer-1: [thrd:main]: New local topic: OFFSET_TEST
1547545684.057 RDKAFKA-7-TOPPARNEW: rdkafka#consumer-1: [thrd:main]: NEW OFFSET_TEST [-1] 0x7f2680000d00 (at rd_kafka_topic_new0:362)
1547545684.057 RDKAFKA-7-TOPPARNEW: rdkafka#consumer-1: [thrd:main]: NEW OFFSET_TEST [0] 0x7f26800011b0 (at rd_kafka_toppar_desired_add:594)
1547545684.057 RDKAFKA-7-DESIRED: rdkafka#consumer-1: [thrd:main]: OFFSET_TEST [0]: adding to DESIRED list
1547545684.057 RDKAFKA-7-DESP: rdkafka#consumer-1: [thrd:main]: Adding desired topic OFFSET_TEST [0]
1547545684.057 RDKAFKA-7-BARRIER: rdkafka#consumer-1: [thrd:main]: Group "group3": rd_kafka_cgrp_assign:2301: new version barrier v2
1547545684.057 RDKAFKA-7-ASSIGN: rdkafka#consumer-1: [thrd:main]: Group "group3": assigning 1 partition(s) in join state init
1547545684.057 RDKAFKA-7-CGRPJOINSTATE: rdkafka#consumer-1: [thrd:main]: Group "group3" changed join state init -> assigned (v2, state wait-broker)
1547545684.057 RDKAFKA-7-BARRIER: rdkafka#consumer-1: [thrd:main]: Group "group3": rd_kafka_cgrp_partitions_fetch_start0:1641: new version barrier v3
1547545684.057 RDKAFKA-7-FETCHSTART: rdkafka#consumer-1: [thrd:main]: Group "group3": starting fetchers for 1 assigned partition(s) in join-state assigned (usable_offsets=no, v3, line 2346)
1547545684.057 RDKAFKA-7-FETCHSTART: rdkafka#consumer-1: [thrd:main]: List with 1 partition(s):
1547545684.057 RDKAFKA-7-FETCHSTART: rdkafka#consumer-1: [thrd:main]:  OFFSET_TEST [0] offset INVALID
1547545684.057 RDKAFKA-7-OFFSETFETCH: rdkafka#consumer-1: [thrd:main]: List with 1 partition(s):
1547545684.057 RDKAFKA-7-OFFSETFETCH: rdkafka#consumer-1: [thrd:main]:  OFFSET_TEST [0] offset INVALID
1547545684.057 RDKAFKA-7-OFFSET: rdkafka#consumer-1: [thrd:main]: Offset fetch error: Local: Waiting for coordinator
1547545684.057 RDKAFKA-7-CGRPQUERY: rdkafka#consumer-1: [thrd:main]: Group "group3": no broker available for coordinator query: intervaled in state wait-broker
1547545684.058 RDKAFKA-7-STATE: rdkafka#consumer-1: [thrd:main]: Topic OFFSET_TEST changed state unknown -> exists
1547545684.058 RDKAFKA-7-PARTCNT: rdkafka#consumer-1: [thrd:main]: Topic OFFSET_TEST partition count changed from 0 to 1
1547545684.058 RDKAFKA-7-METADATA: rdkafka#consumer-1: [thrd:main]:   Topic OFFSET_TEST partition 0 Leader 2
1547545684.059 RDKAFKA-7-BRKDELGT: rdkafka#consumer-1: [thrd:main]: OFFSET_TEST [0]: delegate to broker 172.21.1.19:9092/2 (rktp 0x7f26800011b0, term 0, ref 3, remove 0)
1547545684.059 RDKAFKA-7-BRKDELGT: rdkafka#consumer-1: [thrd:main]: OFFSET_TEST [0]: broker 172.21.1.19:9092/2 is now leader for partition with 0 messages (0 bytes) queued
1547545684.059 RDKAFKA-7-BRKMIGR: rdkafka#consumer-1: [thrd:main]: Migrating topic OFFSET_TEST [0] 0x7f26800011b0 from (none) to 172.21.1.19:9092/2 (sending PARTITION_JOIN to 172.21.1.19:9092/2)
1547545684.059 RDKAFKA-7-METADATA: rdkafka#consumer-1: [thrd:main]: 172.21.1.18:9092/bootstrap: 1/1 requested topic(s) seen in metadata
1547545684.059 RDKAFKA-7-TOPBRK: rdkafka#consumer-1: [thrd:172.21.1.19:9092/2]: 172.21.1.19:9092/2: Topic OFFSET_TEST [0]: joining broker (rktp 0x7f26800011b0)
1547545684.059 RDKAFKA-7-BRKREASSIGN: rdkafka#consumer-1: [thrd:main]: Group "group3" management reassigned from broker :0/internal to 172.21.1.18:9092/bootstrap
1547545684.059 RDKAFKA-7-BRKUNASSIGN: rdkafka#consumer-1: [thrd:main]: Group "group3" management unassigned from broker handle :0/internal
1547545684.059 RDKAFKA-7-BRKASSIGN: rdkafka#consumer-1: [thrd:main]: Group "group3" management assigned to broker 172.21.1.18:9092/bootstrap
1547545684.059 RDKAFKA-7-CGRPQUERY: rdkafka#consumer-1: [thrd:main]: 172.21.1.18:9092/bootstrap: Group "group3": querying for coordinator: intervaled in state wait-broker
1547545684.059 RDKAFKA-7-LEADER: rdkafka#consumer-1: [thrd:172.21.1.18:9092/bootstrap]: 172.21.1.18:9092/1: Mapped 0 partition(s) to broker
1547545684.059 RDKAFKA-7-CGRPCOORD: rdkafka#consumer-1: [thrd:main]: 172.21.1.18:9092/1: Group "group3" coordinator is 172.21.1.20:9092 id 3
1547545684.059 RDKAFKA-7-CGRPCOORD: rdkafka#consumer-1: [thrd:main]: Group "group3" changing coordinator -1 -> 3
1547545684.060 RDKAFKA-7-BRKREASSIGN: rdkafka#consumer-1: [thrd:main]: Group "group3" management reassigned from broker 172.21.1.18:9092/1 to 172.21.1.20:9092/3
1547545684.060 RDKAFKA-7-BRKUNASSIGN: rdkafka#consumer-1: [thrd:main]: Group "group3" management unassigned from broker handle 172.21.1.18:9092/1
1547545684.060 RDKAFKA-7-BRKASSIGN: rdkafka#consumer-1: [thrd:main]: Group "group3" management assigned to broker 172.21.1.20:9092/3
1547545684.060 RDKAFKA-7-CGRPSTATE: rdkafka#consumer-1: [thrd:main]: Group "group3" changed state wait-broker -> wait-broker-transport (v3, join-state assigned)
1547545684.060 RDKAFKA-7-CGRPQUERY: rdkafka#consumer-1: [thrd:main]: 172.21.1.18:9092/1: Group "group3": querying for coordinator: intervaled in state wait-broker-transport
1547545684.060 RDKAFKA-7-CGRPCOORD: rdkafka#consumer-1: [thrd:main]: 172.21.1.18:9092/1: Group "group3" coordinator is 172.21.1.20:9092 id 3
1547545685.055 RDKAFKA-7-CGRPSTATE: rdkafka#consumer-1: [thrd:main]: Group "group3" changed state wait-broker-transport -> up (v3, join-state assigned)
1547545685.055 RDKAFKA-7-BARRIER: rdkafka#consumer-1: [thrd:main]: Group "group3": rd_kafka_cgrp_partitions_fetch_start0:1641: new version barrier v4
1547545685.055 RDKAFKA-7-FETCHSTART: rdkafka#consumer-1: [thrd:main]: Group "group3": starting fetchers for 1 assigned partition(s) in join-state assigned (usable_offsets=no, v4, line 3056)
1547545685.055 RDKAFKA-7-FETCHSTART: rdkafka#consumer-1: [thrd:main]: List with 1 partition(s):
1547545685.055 RDKAFKA-7-FETCHSTART: rdkafka#consumer-1: [thrd:main]:  OFFSET_TEST [0] offset INVALID
1547545685.055 RDKAFKA-7-OFFSET: rdkafka#consumer-1: [thrd:main]: 172.21.1.20:9092/3: OffsetFetchRequest(v1) for 1/1 partition(s)
1547545685.055 RDKAFKA-7-OFFSET: rdkafka#consumer-1: [thrd:main]: 172.21.1.20:9092/3: Fetch committed offsets for 1/1 partition(s)
1547545685.056 RDKAFKA-7-OFFSETFETCH: rdkafka#consumer-1: [thrd:main]: List with 1 partition(s):
1547545685.056 RDKAFKA-7-OFFSETFETCH: rdkafka#consumer-1: [thrd:main]:  OFFSET_TEST [0] offset INVALID
1547545685.056 RDKAFKA-7-OFFSET: rdkafka#consumer-1: [thrd:main]: Topic OFFSET_TEST [0]: setting default offset INVALID
1547545685.056 RDKAFKA-7-OFFSETFETCH: rdkafka#consumer-1: [thrd:main]: 172.21.1.20:9092/3: OffsetFetchResponse: OFFSET_TEST [0] offset -1
1547545685.056 RDKAFKA-7-OFFFETCH: rdkafka#consumer-1: [thrd:main]: 172.21.1.20:9092/3: OffsetFetch for 1/1 partition(s) returned Success
1547545685.056 RDKAFKA-7-BARRIER: rdkafka#consumer-1: [thrd:main]: Group "group3": rd_kafka_cgrp_partitions_fetch_start0:1641: new version barrier v5
1547545685.056 RDKAFKA-7-FETCHSTART: rdkafka#consumer-1: [thrd:main]: Group "group3": starting fetchers for 1 assigned partition(s) in join-state assigned (usable_offsets=yes, v5, line 1573)
1547545685.056 RDKAFKA-7-FETCHSTART: rdkafka#consumer-1: [thrd:main]: List with 1 partition(s):
1547545685.056 RDKAFKA-7-FETCHSTART: rdkafka#consumer-1: [thrd:main]:  OFFSET_TEST [0] offset INVALID
1547545685.056 RDKAFKA-7-CGRPJOINSTATE: rdkafka#consumer-1: [thrd:main]: Group "group3" changed join state assigned -> started (v5, state up)
1547545685.056 RDKAFKA-7-BARRIER: rdkafka#consumer-1: [thrd:main]: OFFSET_TEST [0]: rd_kafka_toppar_op_fetch_start:2193: new version barrier v2
1547545685.056 RDKAFKA-7-CONSUMER: rdkafka#consumer-1: [thrd:main]: Start consuming OFFSET_TEST [0] at offset INVALID (v2)
1547545685.056 RDKAFKA-7-OP: rdkafka#consumer-1: [thrd:main]: OFFSET_TEST [0] received op FETCH_START (v2) in fetch-state none (opv1)
1547545685.056 RDKAFKA-7-FETCH: rdkafka#consumer-1: [thrd:main]: Start fetch for OFFSET_TEST [0] in state none at offset INVALID (v2)
1547545685.056 RDKAFKA-7-PARTSTATE: rdkafka#consumer-1: [thrd:main]: Partition OFFSET_TEST [0] changed fetch state none -> offset-query
1547545685.056 RDKAFKA-7-OFFSET: rdkafka#consumer-1: [thrd:main]: OFFSET_TEST [0]: offset reset (at offset INVALID) to BEGINNING: no previously committed offset available: Local: No offset stored
1547545685.056 RDKAFKA-7-OFFREQ: rdkafka#consumer-1: [thrd:main]: 172.21.1.19:9092/2: Partition OFFSET_TEST [0]: querying for logical offset BEGINNING (opv 2)
1547545685.056 RDKAFKA-7-OFFSET: rdkafka#consumer-1: [thrd:main]: 172.21.1.19:9092/2: OffsetRequest (v0, opv 0) for 1 topic(s) and 1 partition(s)
1547545685.056 RDKAFKA-7-PARTSTATE: rdkafka#consumer-1: [thrd:main]: Partition OFFSET_TEST [0] changed fetch state offset-query -> offset-wait
1547545685.056 RDKAFKA-7-CGRPOP: rdkafka#consumer-1: [thrd:main]: Group "group3" received op PARTITION_JOIN in state up (join state started, v5) for OFFSET_TEST [0]
1547545685.056 RDKAFKA-7-PARTADD: rdkafka#consumer-1: [thrd:main]: Group "group3": add OFFSET_TEST [0]
1547545685.057 RDKAFKA-7-OFFSET: rdkafka#consumer-1: [thrd:main]: 172.21.1.19:9092/2: Offset reply for topic OFFSET_TEST [0] (v2 vs v2)
1547545685.057 RDKAFKA-7-OFFSET: rdkafka#consumer-1: [thrd:main]: Offset BEGINNING request for OFFSET_TEST [0] returned offset 6 (6)
1547545685.057 RDKAFKA-7-PARTSTATE: rdkafka#consumer-1: [thrd:main]: Partition OFFSET_TEST [0] changed fetch state offset-wait -> active
1547545685.057 RDKAFKA-7-FETCH: rdkafka#consumer-1: [thrd:main]: Partition OFFSET_TEST [0] start fetching at offset 6
1547545685.057 RDKAFKA-7-FETCHDEC: rdkafka#consumer-1: [thrd:172.21.1.19:9092/2]: Topic OFFSET_TEST [0]: fetch decide: updating to version 2 (was 0) at offset 6 (was 0)
1547545685.057 RDKAFKA-7-FETCH: rdkafka#consumer-1: [thrd:172.21.1.19:9092/2]: 172.21.1.19:9092/2: Topic OFFSET_TEST [0] in state active at offset 6 (0/100000 msgs, 0/1048576 kb queued, opv 2) is fetchable: 
1547545685.057 RDKAFKA-7-FETCHADD: rdkafka#consumer-1: [thrd:172.21.1.19:9092/2]: 172.21.1.19:9092/2: Added OFFSET_TEST [0] to fetch list (1 entries, opv 2)
1547545685.057 RDKAFKA-7-FETCH: rdkafka#consumer-1: [thrd:172.21.1.19:9092/2]: 172.21.1.19:9092/2: Fetch topic OFFSET_TEST [0] at offset 6 (v2)

**Comment by edenhill** [comment]
`1547545685.057 RDKAFKA-7-OFFSET: rdkafka#consumer-1: [thrd:main]: Offset BEGINNING request for OFFSET_TEST [0] returned offset 6 (6)`

Your partition begins at offset 6, older messages have probably been removed due to offset retention policy or compaction.

**Comment by lxyscls** [comment]
@edenhill 
I think this is the root cause. My retention time is 1 hour. Thank you very much. You are the best!
