### ISSUE TITLE
Broker state in statistics update very slowly when brokers are down.

### ISSUE THREAD

**Issue by GavynG** [edenhill/librdkafka#2191]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Broker state in statistics update very slowly when brokers are down.
My App register statistic callback and set stat interval to 5000ms,then the App call rd_kafka_poll() in every few seconds.
I have three brokers,and when I unplug those network cable which connect to brokers, the broker state value which statistic callback function got is still be "UP" for many cycle, it always takes about 5 mins to change the state value to "DOWN".But it's alway instantly change the state to "UP" when I replug those network cable in.
I've try set topic.metadata.refresh.interval.ms to 30000,instead default 300000 and set socket.keepalive.enable to true,but does't help.
How can I get the brokers `down` state more quickly?
Another strange thing is that it seems like the rdkafka doesn't acctually enable socket keepalive,according to the packets captured by tcpdump.
Thanks in advance!

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.0.0-pre2 (git commit:5422b75) and v0.11.6`
 - [x] Apache Kafka version: `kafka_2.11-2.1.0`
 - [x] librdkafka client configuration: `socket.keepalive.enable=true,topic.metadata.refresh.interval.ms=30000,statistics.interval.ms=5000`
 - [x] Operating system: `client:Windows 10 x64\Redhat 6.5 x64, broker : Centos 7 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by GavynG** [comment]
> 
> 
> If there are no protocol requests being sent on a TCP connection the loss of connectivity will not be detected.
> One workaround is to enable socket keepalives (socket.keepalive.enable), but typically requires tuning of the kernel keepalive interval as well, see:
> http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html
> http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
> 
> The topic metadata refresh will pick a random UP connection, so it may take some time for it disconnect all connections.

Thanks for your instruction. I add some test code in "rdkafka_transport.c" to set those three keepalive parameters, tcp_keepalive_time is 4000ms,intvl is 2000ms,probes is 3(no such option available in Windows),and with "topic.metadata.refresh.interval.ms" set to 30000ms. 
I test two scenarios on two platfroms (windows 10 x64,RHEL 6.5 x64):
 1.produce one message per 2500ms 
 2.don't produce any message
I get faster link status change in statistics on Windows than Linux while I unplug the cable.On windows it takes about 10~15 seconds,but on Linux it takes about one minute. 
Is it possilbe that rdkakfa detect link down more faster on Linux? at least as fast as on Windows.

keepalive setting code:
`int rd_kafka_set_keepalive_param(int fd)
{
	if (fd <= 0)
		return -1;
	int ret = 0;
	
#ifdef _MSC_VER
	struct tcp_keepalive alive;
	DWORD dwBytesRet = 0;
	//Set the keepalive values 
	alive.onoff = TRUE;
	alive.keepalivetime = 4000; //ms
	alive.keepaliveinterval = 2000;

	if (WSAIoctl(fd, SIO_KEEPALIVE_VALS, &alive, sizeof(alive),
		NULL, 0, &dwBytesRet, NULL, NULL) == SOCKET_ERROR)
	{
		return -1;
	}
#else
	//int keepalive_enable = 1;
	int keepalive_idle = 4;
	int keepalive_intvl = 2;
	int keepalive_cnt = 3;

	ret = setsockopt(fd, SOL_TCP, TCP_KEEPIDLE, (char *)&keepalive_idle, sizeof(keepalive_idle));
	if (ret < 0)
	{
		return -1;
	}

	ret = setsockopt(fd, SOL_TCP, TCP_KEEPINTVL, (char *)&keepalive_intvl, sizeof(keepalive_intvl));
	if (ret < 0)
	{
		return -1;
	}

	ret = setsockopt(fd, SOL_TCP, TCP_KEEPCNT, (char *)&keepalive_cnt, sizeof(keepalive_cnt));
	if (ret < 0)
	{
		return -1;
	}
#endif
	return 0;
}`

**Comment by edenhill** [comment]
I don't know more than you on this topic, you will need to play with the Linux setsockopts and /sys or /proc settings.
