### ISSUE TITLE
Documented valid values for producer acks configuration should be updated

### ISSUE THREAD

**Issue by hartfordfive** [edenhill/librdkafka#2193]
## Description
As per [Kafka documentation](http://kafka.apache.org/documentation/#producerconfigs), the valid values for the producer acks/request.required.acks config parameter only include `-1`, `0`, `1` and `all` since [v0.8.3](https://cwiki.apache.org/confluence/display/KAFKA/KIP-1+-+Remove+support+of+request.required.acks).  Consequently, the [producer client documentation](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md#topic-configuration-properties) should be updated to reflect this.

**Comment by edenhill** [comment]
This might be a breaking change for existing applicaitons so we'll put in a deprecation warning to eventually have it changed for v2.0
