### ISSUE TITLE
Using librdkafka with select() or poll()

### ISSUE THREAD

**Issue by singularsyntax** [edenhill/librdkafka#2194]
Is there any means of exposing the socket descriptors librdkafka uses for network I/O so that it can be integrated into an application event loop handling multiple I/O channels, e.g. using select()/poll() ?

**Comment by edenhill** [comment]
No, there is no such need since all IO is handled by background threads.

**Comment by singularsyntax** [comment]
I guess I should be more clear - I'm not talking about doing low-level read() on the network sockets, but rather, a multiplexed select()/poll() compatible (i.e. file-descriptor based) notification mechanism for available messages/events.

Upon further investigation, it looks like this might be what I'm looking for:

    RD_EXPORT
    void rd_kafka_queue_io_event_enable (rd_kafka_queue_t *rkqu, int fd, const void *payload, size_t size);

When this file descriptor is read-indicated, I can then call `rd_kafka_consumer_poll` with a timeout of 0 and process available messages and events.

**Comment by edenhill** [comment]
Yes, that's exactly the use case for io_event!
