### ISSUE TITLE
How to remove lzstd ?

### ISSUE THREAD

**Issue by sangli00** [edenhill/librdkafka#2196]
./configure

```
LIBS                     -lssl -lcrypto   -lm  -lzstd -lcrypto   -lz   -ldl -lpthread -lrt
```

How to remove? 

OS:CentOS6.5
GCC:6.2

Why cannot link lib?
```
undefined symbol: ZSTD_compressBound
```

**Comment by edenhill** [comment]
What version of libzstd do you have installed?

**Comment by sangli00** [comment]
@edenhill  yum install ,but I cannot ```nm``` libzstd.so.1

**Comment by edenhill** [comment]
Run `rpm -q libzstd-devel`

**Comment by sangli00** [comment]
I modify  ```configure.librdkafka```,delete line 90 & 91 ,is OK.
maybe libzstd library is error ,cannot link or bad symbol.
