### ISSUE TITLE
node-rdkakfa: Local: Broker transport failure

### ISSUE THREAD

**Issue by ignasiduran** [edenhill/librdkafka#2199]
Description
===========
I have 4 consumers with node-rdkafka for 4 partitions of one topic and 3 brokers. Consumers and Kafka cluster runs on K8S. 

Sometimes, I get "Local: Broker transport failure error". When consumers no process messages for large period of time, I get the same error every x minutes:

2019-01-23T12:26:10.304Z
{ Error: Local: Broker transport failure
  origin: 'local',
  message: 'broker transport failure',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Broker transport failure' }
2019-01-23T12:41:10.273Z
{ Error: Local: Broker transport failure
  origin: 'local',
  message: 'broker transport failure',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Broker transport failure' }
2019-01-23T13:06:10.325Z
{ Error: Local: Broker transport failure
  origin: 'local',
  message: 'broker transport failure',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Broker transport failure' }
2019-01-23T13:16:10.397Z
{ Error: Local: Broker transport failure
  origin: 'local',
  message: 'broker transport failure',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Broker transport failure' }
2019-01-23T13:26:10.417Z
{ Error: Local: Broker transport failure
  origin: 'local',
  message: 'broker transport failure',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Broker transport failure' }
2019-01-23T13:36:10.265Z
{ Error: Local: Broker transport failure
  origin: 'local',
  message: 'broker transport failure',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Broker transport failure' }
2019-01-23T14:01:10.408Z
{ Error: Local: Broker transport failure
  origin: 'local',
  message: 'broker transport failure',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Broker transport failure' }

The connection on Kafka nodes show the status TIME_WAIT when previous error appears. I understand that broker's idle connection closes the connection due to inactivity and reconnect. 

On Kafka log show the following property:

connections.max.idle.ms = 600000

If I set  "log.connection.close" to true, I do not show the previous errors. 

Why my errors "Local: Broker transport failure" not appear every 10 minutes? Any idea about this period errors?

How to reproduce
================
const Kafka = require('node-rdkafka');

console.log(Kafka.librdkafkaVersion);
console.log(Kafka.features);

  console.info('Creating Kafka consumer');

  var stream = Kafka.KafkaConsumer.createReadStream({
    'metadata.broker.list': 'kafka-kafka-0.kafka-kafka-headless:9092,kafka-kafka-1.kafka-kafka-headless:9092',
    'group.id': 'test',
    'socket.keepalive.enable': true,
    'enable.auto.commit': true,
    'auto.offset.reset': 'latest',
    'log.connection.close': false,
  }, {}, {
    topics: 'test',
    waitInterval: 0,
    objectMode: false
  });

  stream.on('data', function(message) {
   console.log('Got message');
   console.log(message.value);
   console.log(new Date().toISOString());
   })

  });

  stream.consumer.on('ready', function(err) {
    console.log('Kafka readStream consumer ready\',', err);
    console.log(new Date().toISOString());
  })

  stream.on('error', function() {
    process.exit(1);
  });

  stream
    .pipe(process.stdout);

  stream.on('error', function(err) {
    console.log(err);
    process.exit(1);
  });

  stream.consumer.on('event.log', function(err) {
    console.log(new Date().toISOString());
    console.log(err);
  })

  stream.consumer.on('event.error', function(err) {
    console.log(new Date().toISOString());
    console.log(err);
  })

  process.on('SIGINT', function() {
      console.log("Caught interrupt signal");
      console.log(new Date().toISOString());
      stream.consumer.disconnect();
  });

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.5
 - [x] Apache Kafka version: 2.11-1
 - [x] librdkafka client configuration: 'socket.keepalive.enable': true, 'enable.auto.commit': true, 'auto.offset.reset': 'latest', 'log.connection.close': false
 - [x] Operating system: Debian
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Random connections will be used for metadata refresh requests, which is probably the reason why you are not seeing perfect 10-minute disconnects.
The upcoming v1.0.0 release of librdkafka will use sparse connections and only connect to the brokers it needs to talk to, not all brokers, so this will not be a problem then.

**Comment by lxyscls** [comment]
@edenhill

**Comment by lxyscls** [comment]
@edenhill I meet the same problem, so which v1.0.0 RC release is better? Thank you.

**Comment by edenhill** [comment]
Please try the latest RC: v1.0.0-RC7
