### ISSUE TITLE
Is there good way to know the error which causes delivery failed has been fixed?

### ISSUE THREAD

**Issue by ossberyl** [edenhill/librdkafka#2201]
Hello,

Suppose we are reading from a data stream(which someone else is continuously append data to) and write the data to Kafka. If we get error in delivery callback especially when the error isn't related with this specific message such as ERR_CORRUPT_MESSAGE, ERR_MSG_SIZE_TOO_LARGE but related with the unhealthy state of Broker, we want to stop reading and restart until the error is fixed.

I know there could be various reason for the error from the user manual, do we have a full list of errors which would appear in the delivery callback(not intermediate errors which librdkafka would retry for user automatically)? 

And is there a good way to know when such error is fixed, maybe via which "Status change" in event_cb? If there is a good mapping between the error which appear in delivery callback and the "Status change", that would be very helpful.

We won't continue reading and pushing message into librdkafka's local queue to avoid make it full and either block there or drop the message, so knowing when the error is fixed is important to us.

Thanks!

**Comment by edenhill** [comment]
Any broker error, that is, single underscore ERR_SOMETHING error, or non-negative value, typically means the error was permanent (from the producer's perspective) and that the error was triggered by the broker.

There is no practical way for the producer to know that such an error has been mitigated by broker configuration change, or similar.

**Comment by ossberyl** [comment]
Thank you for the prompt reply!

I have another question for the setting of "retries", do we have an option for infinite retry? Thus we could keep the unsent message in librdkafka's local queue until it can be sent.

**Comment by edenhill** [comment]
Just set retries to its max value, possibly also adjusting retry.backoff.ms to your liking, and message.timeout.ms. This effectively makes it "infinite"
