### ISSUE TITLE
Fail faster if broker is down

### ISSUE THREAD

**Issue by Tezd** [edenhill/librdkafka#2202]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I try to produce to single broker, which is unavailable. With setting message.timeout.ms to 100 ms  expectations were that execution time will be be around 100 ms plus time it takes to destroy kafka resources. Due to https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L1708 (master) or https://github.com/edenhill/librdkafka/blob/v0.11.6/src/rdkafka.c#L1399 (v0.11.6) shutdown time will be in steps of 1 second(ex. message.timeout.ms 1500ms will result in shutdown of 2 sec). Important part I do want to trigger dr_cb on failed messages. Question is there any way of speeding up failure in this kind of situations or maybe make window for **tmr_topic_scan** configurable?

How to reproduce
================

1. Bring up environment using [Dockerfile](https://github.com/edenhill/librdkafka/files/2792425/Dockerfile.txt)
2. Build librdkafka inside of the container: `./configure && make && make install`
3. Add following [producer.c](https://github.com/edenhill/librdkafka/files/2792400/producer.txt) to /app:` docker cp producer.c <container_name>:/app`
4. Build producer inside of the container: `gcc -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I/usr/local/include -I./src producer.c -o producer_poc src/librdkafka.a -L/lib -lsasl2 -lssl -L/usr/local/lib -llz4 -lm -lcrypto -L/lib -lz -ldl -lpthread -lrt`
5. Run: `docker exec -it <container_name> time /app/producer_poc`
6. Verify that it took ~1s to complete

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.6`
 - [x] Apache Kafka version: `1.0.0` (not used)
 - [x] librdkafka client configuration: `config: debug=all, topic_config: message.timeout.ms=100`
 - [x] Operating system: `alpine:2.8`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka [producer.log](https://github.com/edenhill/librdkafka/files/2792417/producer.log)
 - [ ] Provide broker log excerpts (not used)
 - [ ] Critical issue

**Comment by edenhill** [comment]
There currently isn't, the scanning will be on 1s intervals.

Why do you need such a low message timeout, what is it you are trying to achieve?

In practice, a local or remote system (swapping, core contention, etc), or network, hickup is very likely to last longer than 100ms, especially when adding the TCP slow down on resend.
Even a connection attempt with SSL may take a long time on a loaded broker.

So I would question the practical use of a lower timeout scan than 1s.

**Comment by Tezd** [comment]
I took 100 ms as an example. Event if I will have 1500 ms(as stated in description) as message.timeout.ms it will take ~2s to shutdown (since topic scan is in 1s cycles) adding additional 500 ms to shutdown routine.

**Comment by edenhill** [comment]
I guess we could adjust the timeout scan interval to be min(message.timeout.ms, 1000), at the expense of increased CPU usage when message.timeout.ms is low.
But I still fail to see the real use of this, can you elaborate on your use-case and what you mean by shutting down?

**Comment by Tezd** [comment]
For long running applications this makes little to no sense. My use-case is php-rdkafka + php-fpm. We usually have response time ~180-200 ms so if it'll become ~1s we can run into fpm pool being busy.  I meant shutting down in context of short lived php process. In php-rdkafka it tries to flush all queued messages (if not flushed previously) on destruction of process. Sorry I should have been more precise with the title.

**Comment by edenhill** [comment]
I understand.
It will be quite costly to set up a new Kafka client instance for each web server request though, the client needs to connect to multiple brokers, spawn threads, and issue requests. I wouldn't recommending all that for each web request if it can be avoided.

Having said that, try decreasing the previously mentioned 1s timer, and also this value https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L75 on master branch, see if it cuts down on the wait time.

On the other hand, you will only see these timeouts if the cluster is down/not reachable, which is an error case, right?

**Comment by Tezd** [comment]
Took again 100 ms message timeout as reference and librdkafka branch which tested against is master (7ed30b3ed6a9e964afcd427836fa6c7687614773)

rd_kafka_max_block_ms | topic_scan_interval | produce ms 
---|---|---
1000 | 1000000 | 0m1.015s
100 | 1000000 | 0m1.020s
1000 | 100000 | 0m0.207s
100 | 100000 | 0m0.219s

Yes it is error case, but we can re-queue not delivered items after recovery.

**Comment by edenhill** [comment]
Good test!
Are the 200ms range results sufficient for your needs?

**Comment by Tezd** [comment]
Yes they are)

**Comment by edenhill** [comment]
Good :+1:

We'll look into this issue after the v1.0.0 release and see if we can adjust the scan interval to cater to message.timeout.ms without adverse affects.

Thank you for your exploratory efforts!

**Comment by Tezd** [comment]
Thank you for your time and swift responses

**Comment by accelerated** [comment]
Hi @edenhill, I'm currently running client v1.3.0 and I noticed that `message.timeout.ms` doesn't take effect at all. I'm also simulating a broker down/unavailable, set the `message.timeout.ms=10000` and it still times out after 5 mins which is the default. Aside from this, I see the error callback getting invoked almost immediately which is a good sign.

**Comment by edenhill** [comment]
Huhm, ok, can you verify that the message timeout property is in fact in use by configuring non existent bootstrap servers?

**Comment by accelerated** [comment]
Confirmed:
```
    options.push_back({"metadata.broker.list", "bad:1111"});
    options.push_back({"retries",0});
    options.push_back({"api.version.request",true});
    options.push_back({"message.timeout.ms", 10000});
```

**Comment by edenhill** [comment]
And the messages don't time out after 10s with this config?
Are you calling poll()?

**Comment by accelerated** [comment]
Yes I am since I'm getting the error callback almost immediately. I'm also getting the delivery report after 5min. So I know that the polling works.

**Comment by edenhill** [comment]
Are you producing to a specific partition or any/partitioner?

**Comment by edenhill** [comment]
Tried reproducing this on master, works as expected:
```
$ time (echo hi | examples/rdkafka_example -b bad:1111 -P -t test -X topic.message.timeout.ms=10000)
% Type stuff and hit enter to send
% Sent 2 bytes to topic test partition -1
1581517484.898 RDKAFKA-3-FAIL: rdkafka#producer-1: [thrd:bad:1111/bootstrap]: bad:1111/bootstrap: Failed to resolve 'bad:1111': nodename nor servname provided, or not known (after 32ms in state CONNECT)
1581517484.898 RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:bad:1111/bootstrap]: bad:1111/bootstrap: Failed to resolve 'bad:1111': nodename nor servname provided, or not known (after 32ms in state CONNECT)
1581517484.898 RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:bad:1111/bootstrap]: 1/1 brokers are down
% Message delivery failed: Local: Message timed out

real	0m10.511s
user	0m0.014s
sys	0m0.039s
```

(ignore the topic. prefix on the property, rdkafka_example separates global and topic config)

**Comment by accelerated** [comment]
If it makes any difference, I'm calling `flush` on the producer with a timeout of 0, every 100ms.

**Comment by accelerated** [comment]
Ok found it. So this is a typical case of _my bad_ vs options not being validated. I was passing in the option to the producer options instead of topic options. Now I put it in the topic options and it works fine. Remember a while ago I gave you a PR for validating producer vs consumer vs topic options...wish we had that right now. :) 

Sorry for the confusion anyway and thanks for the speedy check!!

**Comment by edenhill** [comment]
You can pass it in the global options, which automatically applies it per topic unless you specify a default topic config or topic-specific config.

**Comment by accelerated** [comment]
Good to know. Actually i was not specifying any topic options, only producer ones. Might want to check and see why it's not taking effect in that case.

**Comment by edenhill** [comment]
Did you call rd_kafka_conf_set_default_topic_config()?

**Comment by accelerated** [comment]
Yup
