### ISSUE TITLE
What happens in Kafka after new consumer connects?

### ISSUE THREAD

**Issue by abyss7** [edenhill/librdkafka#2205]
I have the following issue: after I create consumer and subscribe it (with `cppkafka::Consumer::subscribe()`) there is some lag before the consumer can poll messages. Especially with a timeout polling it looks like consumer gets zero messages. Then after sometime on server-side I can see something like this in logs:

    kafka_1 | [2019-01-25 16:08:42,279] INFO [GroupCoordinator 1001]: Preparing to rebalance group group1 in state PreparingRebalance with old generation 442 (__consumer_offsets-40) (reason: Adding new member … (kafka.coordinator.group.GroupCoordinator)
    kafka_1 | [2019-01-25 16:08:42,281] INFO [GroupCoordinator 1001]: Stabilized group group1 generation 443 (__consumer_offsets-40) (kafka.coordinator.group.GroupCoordinator)
    kafka_1 | [2019-01-25 16:08:42,284] INFO [GroupCoordinator 1001]: Assignment received from leader for group group1 for generation 443 (kafka.coordinator.group.GroupCoordinator)

And consumer begins to receive messages. I assumed that this event may be caught with an assignment callback, but it doesn't work - the callback is never called.

What is actually going on on both sides (consumer, server) after connection, and how can I catch the event of consumer readiness?

The real problem is that I try to create consumers on-the-fly and consume all pending messages. After the topic is depleted consumer waits some time and then gets destroyed. So, with a timeout too low, the consumer simply doesn't have enough time to "really connect" and gets destroyed before getting any messages.

**Comment by abyss7** [comment]
I investigated a little bit more and found #400, with a similar problem. So my current workaround looks almost the same:
1. pause consumer,
2. set rebalance callback to set the flag,
3. subscribe and wait until consumer "joins" the group.

All this steps for me locally take 2 seconds (!) - that's a huge for a single server, single consumer and everything single too.

Is there a way to improve this timing?

**Comment by edenhill** [comment]
Consumer group rebalances typically take somewhere between 0 and `session.timeout.ms`, the initial rebalance for a new/empty group takes `group.initial.rebalance.delay.ms` (broker side property).

**Comment by prakharpratap1** [comment]
@edenhill Hi, We are not seeing the reason for rebalances in version 2.0.1 whereas we could see the reason for rebalance in version 2.1.0 like Adding new member, removing member heartbeat expiration etc., which could help in debugging the issue. Can we enable kafka rebalance logs to show the reason in kafka broker version 2.0.1? 

Logs in Kafka **2.0.1**:
[2019-03-18 17:42:51,829] INFO [GroupCoordinator 3]: Preparing to rebalance group consumer-group1 with old generation 0 (__consumer_offsets-15) (kafka
.coordinator.group.GroupCoordinator)
[2019-03-18 17:42:57,837] INFO [GroupCoordinator 3]: Stabilized group consumer-group1 generation 1 (__consumer_offsets-9) (kafka.coordinator.g
roup.GroupCoordinator)

Logs in Kafka **2.1.0**:
[2019-03-06 13:36:06,400] INFO [GroupCoordinator 0]: Preparing to rebalance group consumer-group1 in state PreparingRebalance with old generation 26 (__consumer_offsets-9) (**reason: Adding new member** MY_TOPIC_ONE-0-85209770-11c7-4ce5-856c-d3e51c2c4b2e) (kafka.coordinator.group.GroupCoordinator)

**Comment by edenhill** [comment]
Might be related to KAFKA-7909:
https://github.com/apache/kafka/commit/4cb8f56b45f3bfb596fb00ef2cc88938fc66f364
