### ISSUE TITLE
rdkafka-static.pc missing in Debian package 0.11.6

### ISSUE THREAD

**Issue by sevagh** [edenhill/librdkafka#2212]
Description
===========
I'm trying to build https://github.com/confluentinc/confluent-kafka-go statically, which gives me this error:
```
# pkg-config --cflags  -- rdkafka-static
Package rdkafka-static was not found in the pkg-config search path.
Perhaps you should add the directory containing `rdkafka-static.pc'
to the PKG_CONFIG_PATH environment variable
No package 'rdkafka-static' found
pkg-config: exit status 1
```
I have the confluentinc Debian repo added in the Debian Jessie Docker container:

```
RUN wget -qO - https://packages.confluent.io/deb/5.1/archive.key | apt-key add -

RUN add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.1 stable main"

RUN apt-get update && apt-get install -y librdkafka-dev librdkafka1
```

The container doesn't have `rdkafka-static.pc`:

```
root@d077dab5586c:/media-replicator# find / -name '*rdkafka*.pc'
/usr/lib/x86_64-linux-gnu/pkgconfig/rdkafka++.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/rdkafka.pc
```
My laptop (Fedora 29 with the confluentinc repo) does:

```
 $ sudo dnf list installed | grep librdkafka
librdkafka-devel.x86_64                           0.11.6_confluent5.1.0-1.el7         @Confluent.dist
librdkafka1.x86_64                                0.11.6_confluent5.1.0-1.el7 
$ sudo find /usr/ -name 'rdkafka*.pc'
/usr/local/lib/pkgconfig/rdkafka++.pc
/usr/local/lib/pkgconfig/rdkafka++-static.pc
/usr/local/lib/pkgconfig/rdkafka-static.pc
/usr/local/lib/pkgconfig/rdkafka.pc
/usr/lib64/pkgconfig/rdkafka++.pc
/usr/lib64/pkgconfig/rdkafka++-static.pc
/usr/lib64/pkgconfig/rdkafka-static.pc
/usr/lib64/pkgconfig/rdkafka.pc
/usr/lib/pkgconfig/rdkafka++.pc
/usr/lib/pkgconfig/rdkafka++-static.pc
/usr/lib/pkgconfig/rdkafka-static.pc
/usr/lib/pkgconfig/rdkafka.pc
```

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.6`
 - [x] Operating system: `Debian Jessie`

**Comment by edenhill** [comment]
This needs to be sorted out by the Debian maintainers.
Ping @paravoid @vincentbernat
