### ISSUE TITLE
UNKNOWN_MEMBER_ID exception when commiting

### ISSUE THREAD

**Issue by steruel** [edenhill/librdkafka#2213]
Description
===========

Hi Edenhill, 
this is my issue....
I have a consumer that is getting sometimes the UNKNOWN_MEMBER_ID exception when trying to commit (no autocommit is enabled).

I think this exception is raised when this message process spent more than 300 secs, but that is not the case (it spent about 120-150 sec)

I am not sure but it seems for any reason librdkafka has a batch of messages and this long time could be related with process all of this messages.

I mean, for example the batch has 4 messages and each spends 2 mins...The sum will be 8 mins, and the last commit (all of them really) fails.

In other java client i had the same problem but I could to solve it setting "max.poll.records" to 1 and "max.interval.ms" to 700000 ms.
I can't set these properties in librdkafka.

My question is : can I simulate this behavior setting 'fetch.message.max.bytes' and 'queued.max.messages.kbytes' ? My idea is batch will have only one message.

Is there any other way to avoid this problem?

Thanks

Checklist
=========

 - [x] librdkafka version 0.11.6
 - [X] Apache Kafka version:0.11
 - [ ] librdkafka client configuration: 
 - [ ] Operating system: ubuntu
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
What is your session.timeout.ms?

For long running processing you will need max.poll.interval.ms (KIP-62) support that is coming in the v1.0.0 release.

**Comment by steruel** [comment]
Thanks, 
session.timeout.ms is the default one.

Could help us to modify it?
do you know when could bbe available V1.0.0?

Thank you very much

**Comment by edenhill** [comment]
We'll hopefully create a new release candidate today which you can try out, where you will want to set max.poll.interval.ms to your maximum possible processing time + some extra padding.

**Comment by steruel** [comment]
Thanks for your support

**Comment by edenhill** [comment]
v1.0.0-RC6 is now tagged, please give it a try and report your findings.
Thanks
