### ISSUE TITLE
Hasan

### ISSUE THREAD

**Issue by HassanAYt** [edenhill/librdkafka#2217]
Description
===========
In the file rdkafka-consumer-example.cpp I get a run error on the lines
*val = '\0';
val++;
in main() function.
I compile and run in debug mode under Win32.
Also If you can kindly provide a sample of the arguments syntax to run the rdkafka-consumer-example.exe? I did not find the syntax to compose these arguments for this executable anywhere.

How to reproduce
================
compile rdkafka-consumer-example project and run in debug mode under Win32.
using visual studio community 15

operating system Windows10

Checklist
=========

apache kafka version is kafka_2.11-2.1.0
 rdkafkalib I am using the master
with Latest commit a869fa1  on Dec 1, 2018

**Comment by Hasssona123** [comment]
thanks. but please still the first question is unanswered:
In rdkafka-consumer-example.cpp 
Line: 283    *val = '\0';
the rdkafka-consumer-example.exe gives a run time error?

**Comment by edenhill** [comment]
What exact command arguments are you using to provoke that crash?

**Comment by Hasssona123** [comment]
the command argument is:
rdkafka_consumer_example.exe  -X mytopic -b mybroker -g mygroup 
and the crash happens after press Ctrl C in the console

**Comment by edenhill** [comment]
That's not a valid command line, I'm not sure why it crashes for you but it is properly handled as an error for me.
I provided the proper command line without -X in a previous comment.

**Comment by Hasssona123** [comment]
ok-Thanks a lot for your prompt response and help.
