### ISSUE TITLE
C11 thread check is not working with glibc 2.28

### ISSUE THREAD

**Issue by Oxymoron79** [edenhill/librdkafka#2220]
Description
===========
Glibc version 2.28 added support for C11 threads (see the release notes: https://www.sourceware.org/ml/libc-alpha/2018-08/msg00003.html).

But the check for C11 threads in configure.librdkafka (https://github.com/edenhill/librdkafka/blob/master/configure.librdkafka#L46) does not seem to
detect the C11 threads support on systems using glibc >= 2.28, because the link option
`-lpthread` is not used for the check.

I suspect that this leads to similar problems as https://github.com/edenhill/librdkafka/issues/1998.

How to reproduce
================
On a system with glibc >= 2.28 (e.g. Arch Linux):
```
./configure
cat config.h | grep WITH_C11THREADS
```
`WITH_C11THREADS` is not defined in `config.h`, which leads to tinycthread being compiled without C11 thread support.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.1`
 - [x] Operating system: `Arch Linux (x86_64)`
 - [x] Critical issue

**Comment by edenhill** [comment]
Interesting, do you know of a docker image with glibc 2.28?

**Comment by Oxymoron79** [comment]
Ubuntu 18.10 (Cosmic) seems to be shipping glibc 2.28: https://packages.ubuntu.com/cosmic/libc6
The `cosmic` tag of the ubuntu docker image should therefore include it: https://hub.docker.com/_/ubuntu

**Comment by Oxymoron79** [comment]
@edenhill Were you able to reproduce the issue?

**Comment by grafitto** [comment]
I am also experiencing the same error.

**Comment by edenhill** [comment]
This will be fixed in the upcoming v1.0.0 release.
