### ISSUE TITLE
make fails on OSX

### ISSUE THREAD

**Issue by freddyfly** [edenhill/librdkafka#2223]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
_make_ fails on OSX with the following error:

`/Library/Developer/CommandLineTools/usr/bin/make -C examples
gcc -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -I/usr/local/Cellar/openssl/1.0.2q/include -I/usr/local/Cellar/lz4/1.8.3/include -I/usr/local/Cellar/openssl/1.0.2q/include -I../src rdkafka_example.c -o rdkafka_example  \
		../src/librdkafka.a -lsasl2 -L/usr/local/Cellar/openssl/1.0.2q/lib -lssl -L/usr/local/Cellar/lz4/1.8.3/lib -llz4 -lm -L/usr/local/Cellar/openssl/1.0.2q/lib -lcrypto -lz -ldl -lpthread
ld: warning: ignoring file ../src/librdkafka.a, file was built for archive which is not the architecture being linked (x86_64): ../src/librdkafka.a
Undefined symbols for architecture x86_64:
  "_rd_kafka_brokers_add", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_conf_dump", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_conf_dump_free", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_conf_get", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_conf_new", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_conf_properties_show", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_conf_set", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_conf_set_dr_msg_cb", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_conf_set_log_cb", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_consume", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_consume_start", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_consume_stop", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_controllerid", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_destroy", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_dump", referenced from:
      _main in rdkafka_example-06464e.o
      _sig_usr1 in rdkafka_example-06464e.o
  "_rd_kafka_err2str", referenced from:
      _main in rdkafka_example-06464e.o
      _msg_delivered in rdkafka_example-06464e.o
  "_rd_kafka_header_add", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_header_get_all", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_headers_copy", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_headers_destroy", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_headers_new", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_last_error", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_message_destroy", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_message_headers", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_message_timestamp", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_metadata", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_metadata_destroy", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_name", referenced from:
      _logger in rdkafka_example-06464e.o
  "_rd_kafka_new", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_outq_len", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_poll", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_produce", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_producev", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_query_watermark_offsets", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_seek", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_topic_conf_destroy", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_topic_conf_dump", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_topic_conf_get", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_topic_conf_new", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_topic_conf_set", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_topic_destroy", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_topic_name", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_topic_new", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_version", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_version_str", referenced from:
      _main in rdkafka_example-06464e.o
  "_rd_kafka_wait_destroyed", referenced from:
      _main in rdkafka_example-06464e.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [rdkafka_example] Error 1
make: *** [examples] Error 2
`

Maybe I'm missing something obvious here, but I do not know what?

Output from ./configure: [configure.txt](https://github.com/edenhill/librdkafka/files/2857856/configure.txt)

How to reproduce
================
./configure
make

on OSX

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v1.0.0-test1, installed via brew, and release v0.11.6
 - [ x] Apache Kafka version: 2.1.0
 - [x] librdkafka client configuration: N/A
 - [x] Operating system: MacOS Mojave 10.14.3
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts - N/A
 - [ ] Critical issue

**Comment by edenhill** [comment]
> ../src/librdkafka.a, file was built for archive which is not the architecture being linked

Do you get this even after a `make clean ; make` ?

**Comment by axopadyani** [comment]
I'm having the same issue here. I want to install version `0.11.6` on my MacOS, but I get this error when executing `make`:
```
Undefined symbols for architecture x86_64:
  "_CRYPTO_cleanup_all_ex_data", referenced from:
      _rd_kafka_transport_ssl_term in rdkafka_transport.o
  "_CRYPTO_num_locks", referenced from:
      _rd_kafka_transport_ssl_init in rdkafka_transport.o
  "_CRYPTO_set_id_callback", referenced from:
      _rd_kafka_transport_ssl_term in rdkafka_transport.o
      _rd_kafka_transport_ssl_init in rdkafka_transport.o
  "_CRYPTO_set_locking_callback", referenced from:
      _rd_kafka_transport_ssl_term in rdkafka_transport.o
      _rd_kafka_transport_ssl_init in rdkafka_transport.o
  "_ERR_clear_error", referenced from:
      _rd_kafka_transport_send in rdkafka_transport.o
      _rd_kafka_transport_recv in rdkafka_transport.o
      _rd_kafka_transport_io_serve in rdkafka_transport.o
  "_ERR_error_string_n", referenced from:
      _rd_kafka_ssl_error in rdkafka_transport.o
  "_ERR_get_error_line_data", referenced from:
      _rd_kafka_ssl_error in rdkafka_transport.o
  "_ERR_peek_error", referenced from:
      _rd_kafka_transport_ssl_io_update in rdkafka_transport.o
  "_ERR_remove_thread_state", referenced from:
      _rd_kafka_broker_thread_main in rdkafka_broker.o
  "_EVP_DecodeBlock", referenced from:
      _rd_kafka_sasl_scram_fsm in rdkafka_sasl_scram.o
  "_EVP_EncodeBlock", referenced from:
      _rd_kafka_sasl_scram_build_client_final_message in rdkafka_sasl_scram.o
  "_EVP_PKEY_free", referenced from:
      _rd_kafka_transport_ssl_ctx_init in rdkafka_transport.o
  "_EVP_PKEY_new", referenced from:
      _rd_kafka_transport_ssl_ctx_init in rdkafka_transport.o
  "_EVP_sha1", referenced from:
      _rd_kafka_sasl_scram_conf_validate in rdkafka_sasl_scram.o
  "_EVP_sha256", referenced from:
      _rd_kafka_sasl_scram_conf_validate in rdkafka_sasl_scram.o
  "_EVP_sha512", referenced from:
      _rd_kafka_sasl_scram_conf_validate in rdkafka_sasl_scram.o
  "_HMAC", referenced from:
      _rd_kafka_sasl_scram_Hi in rdkafka_sasl_scram.o
      _rd_kafka_sasl_scram_HMAC in rdkafka_sasl_scram.o
  "_OPENSSL_add_all_algorithms_noconf", referenced from:
      _rd_kafka_transport_ssl_init in rdkafka_transport.o
  "_PKCS12_free", referenced from:
      _rd_kafka_transport_ssl_ctx_init in rdkafka_transport.o
  "_PKCS12_parse", referenced from:
      _rd_kafka_transport_ssl_ctx_init in rdkafka_transport.o
  "_SHA1", referenced from:
      _rd_kafka_sasl_scram_conf_validate in rdkafka_sasl_scram.o
  "_SHA256", referenced from:
      _rd_kafka_sasl_scram_conf_validate in rdkafka_sasl_scram.o
  "_SHA512", referenced from:
      _rd_kafka_sasl_scram_conf_validate in rdkafka_sasl_scram.o
  "_X509_STORE_set_flags", referenced from:
      _rd_kafka_transport_ssl_ctx_init in rdkafka_transport.o
  "_X509_free", referenced from:
      _rd_kafka_transport_ssl_ctx_init in rdkafka_transport.o
      _rd_kafka_transport_io_serve in rdkafka_transport.o
  "_X509_new", referenced from:
      _rd_kafka_transport_ssl_ctx_init in rdkafka_transport.o
  "_X509_verify_cert_error_string", referenced from:
      _rd_kafka_transport_io_serve in rdkafka_transport.o
  "_d2i_PKCS12_fp", referenced from:
      _rd_kafka_transport_ssl_ctx_init in rdkafka_transport.o
  "_sk_pop_free", referenced from:
      _rd_kafka_transport_ssl_ctx_init in rdkafka_transport.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [librdkafka.1.dylib] Error 1
make: *** [libs] Error 2
```

Can you help me with this issue?

**Comment by edenhill** [comment]
Upgrade to librdkafka v1.1.0, then do: `./configure --clean ; ./configure ; make clean ; make`

**Comment by axopadyani** [comment]
So i can't install `v0.11.6` on MacOS then?

**Comment by edenhill** [comment]
You can, but you should install the latest version (more features, fixes, and actually supported)
