### ISSUE TITLE
Message stuck in producer queue when broker is down

### ISSUE THREAD

**Issue by roopabayar** [edenhill/librdkafka#2226]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Message stuck in producer queue when broker is down

I see this issue was seen earlier also. Please let me know if it was fixed? 

I have pulled the code from master (v1.0.0-RC7). If the broker is not up when we send messages, there is no callback invoked. As soon as i start the broker, the callback is received.

In my implementation, message free is done in the application. If there is a failure to send message or if there is message timeout, i send the message to secondary kafka cluster. So getting response (success or failure) is a must.  

How to reproduce
================
1) Kill the broker
2) Send messages from the producer client.
3) No response received at all till the broker is brought up. Buffers are stuck.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 

v1.0.0-RC7
GIT hash 51ae5f5fd8b742e56f47a8bb0136344868818285
Branch Master

 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
kafka_2.10-0.10.2.0

 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
Ubuntu

 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
What is your message.timeout.ms setting? And do you wait that long (+ couple of seconds of grace time)?

It works as expected for me:
```
 echo 1 | time examples/rdkafka_example -b localhost -P -t test -X topic.message.timeout.ms=123
% Type stuff and hit enter to send
% Sent 1 bytes to topic test partition -1
1550242158.103 RDKAFKA-3-FAIL: rdkafka#producer-1: [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 1ms in state CONNECT)
1550242158.103 RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv6#[::1]:9092 failed: Connection refused (after 1ms in state CONNECT)
1550242158.103 RDKAFKA-3-ERROR: rdkafka#producer-1: [thrd:localhost:9092/bootstrap]: 1/1 brokers are down
% Message delivery failed: Local: Message timed out
        1.03 real         0.01 user         0.01 sys
```

**Comment by roopabayar** [comment]
message.timeout.ms is set to 60000 ( 60 seconds).

Even after 5 mins, there is no response. As soon as I bring back the broker up, the message fail errors are received.

**Comment by edenhill** [comment]
Can you share relevant sections of your code?

**Comment by roopabayar** [comment]
HI Magnus

There were couple of issues. One was with a very old version of librdkakfa and other was in my implementation.
After I upgraded and fixed the issue in my code, the message stuck issue is no longer seen.

Thanks a lot
Regards
Roopa

**Comment by edenhill** [comment]
Thanks
