### ISSUE TITLE
Whether librdkafka supports concurrent access to kerberos authentication

### ISSUE THREAD

**Issue by linuxkangkang** [edenhill/librdkafka#2227]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Hello Sir:

I use librdkafka with kerberos authentication in a thread 
But when kinit cmd in rd_kafka_sasl_cyrus_kinit_refresh function only have a small lock 

        mtx_lock(&rd_kafka_sasl_cyrus_kinit_lock);
        r = system(cmd);
        mtx_unlock(&rd_kafka_sasl_cyrus_kinit_lock);

I wonder if multithreaded librdkafka is secure when using kerberos authentication?
Thanks.

**Comment by edenhill** [comment]
That locking makes sure there is only one simultaneous call to kinit, to avoid messing up the cache.

There should be no problems using multithreading no.

**Comment by linuxkangkang** [comment]
Thank you, Sir 
I think my question is the same as ISSUE #635.
My final solution is to use a global lock outside of the librdkafka library.Ensure the serialization of the kerberos authentication process.
