### ISSUE TITLE
does librdkafka supports MEMORY cache type with kerberos?

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#2228]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

does librdkafka supports MEMORY cache type for kerberos authentication? (please check below configuration)

krb5.conf
========
` dns_lookup_realm = false
   default_realm = REALM.COM
   **default_ccache_name = MEMORY:**
   rdns = false
   kdc_timesync = 1
   ccache_type = 4
   forwardable = true
   proxiable = true
   preauth = false
   udp_preference_limit = 1'

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.0.0`
 - [x ] Apache Kafka version: `1.1.1`
 - [x ] librdkafka client configuration: ` 
   * builtin.features=sasl_gssapi
  security.protocol=sasl_plaintext
  sasl.mechanisms=GSSAPI
  sasl.kerberos.service.name=kafkaclient
  sasl.kerberos.principal=kafkaclient/mydomain.com@REALM.COM
  sasl.kerberos.keytab=mydomain.keytab
`

 - [x] Operating system: ` Ubuntu 16.04.5 LTS`

debug log
========

1550227364.367 RDKAFKA-7-AUTH: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: Auth in state APIVERSION_QUERY (handshake supported)
1550227364.367 RDKAFKA-7-STATE: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: Broker changed state APIVERSION_QUERY -> AUTH_HANDSHAKE
1550227364.367 RDKAFKA-7-BROADCAST: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: Broadcasting state change
1550227364.367 RDKAFKA-7-SEND: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: Sent SaslHandshakeRequest (v0, 29 bytes @ 0, CorrId 2)
1550227364.369 RDKAFKA-7-RECV: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: Received SaslHandshakeResponse (v0, 14 bytes, CorrId 2, rtt 1.16ms)
1550227364.369 RDKAFKA-7-SASLMECHS: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: Broker supported SASL mechanisms: GSSAPI
1550227364.369 RDKAFKA-7-AUTH: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: Auth in state AUTH_HANDSHAKE (handshake supported)
1550227364.369 RDKAFKA-7-STATE: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: Broker changed state AUTH_HANDSHAKE -> AUTH
1550227364.369 RDKAFKA-7-BROADCAST: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: Broadcasting state change
1550227364.369 RDKAFKA-7-SASL: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: Initializing SASL client: service name kafkaclient, hostname mydomain.com, mechanisms GSSAPI, provider Cyrus
1550227364.369 RDKAFKA-7-SASLREFRESH: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: Refreshing SASL keys with command: kinit -S "kafkaclient/mydomain.com" -k -t "/home/jaydeep/kafka_2.11-1.1.1/config/mydomain.keytab" kafkaclient/mydomain.com@REALM.COM
1550227364.462 RDKAFKA-7-SASLREFRESH: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: SASL key refreshed
1550227364.462 RDKAFKA-7-SASL: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: My supported SASL mechanisms: GS2-IAKERB GS2-KRB5 SCRAM-SHA-1 GSSAPI GSS-SPNEGO DIGEST-MD5 EXTERNAL NTLM CRAM-MD5 LOGIN PLAIN ANONYMOUS
1550227364.464 RDKAFKA-2-LIBSASL: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (No Kerberos credentials available)
1550227364.464 RDKAFKA-7-BROKERFAIL: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: failed: err: Local: Authentication failure: (errno: Invalid argument)
1550227364.464 RDKAFKA-3-FAIL: rdkafka#producer-1: [thrd:sasl_plaintext://mydomain.com:9997/bootstrap]: sasl_plaintext://mydomain.com:9997/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (No Kerberos credentials available) (after 95ms in state AUTH)

**Comment by rnpridgeon** [comment]
I believe what you are looking for is `ccache_type` not `default_ccache_name`. The property `default_ccache_name` refers to the location of the credential cache as opposed to the medium in which it is stored. 

ccache_types:
https://web.mit.edu/kerberos/krb5-1.12/doc/basic/ccache_def.html#ccache-types

ccache_name:
https://web.mit.edu/kerberos/krb5-1.12/doc/basic/ccache_def.html#default-ccache-name

**Comment by write2jaydeep** [comment]
@rnpridgeon Thank you for your reply. 
have you ever tried MEMORY type configuration in krb5.conf?
it really doesn't work with librdkafka. let me know the config parms if it works for you.

I had some problem with FILE type cache, but now I resolved the problem! so you may figure out the problem with MEMORY cache type.

**Comment by rnpridgeon** [comment]
No I have not although I would imagine the credential cache implementation is abstracted away from librdkafka itself. @edenhill can correct me if I'm wrong on that though. 

I imagine this would be handled by the kerberos client library which librdkafka links to. Meaning that if you can successfully `kinit` with these properties in krb5.conf it should work for librdkafka as well. If you can't kinit outside of librdkafka though something else is wrong.

**Comment by write2jaydeep** [comment]
@rnpridgeon I will try to figure it out and report you with trace log if it is really something need to do with librdkafka. Thank you!

**Comment by rnpridgeon** [comment]
Thanks @write2jaydeep!

**Comment by zmstone** [comment]
Worth trying: `export KRB5CCNAME="MEMORY:my_application_name"`
Disclaimer: I have not tested it with librdkafka. This is the workaround I used in another project.
cyrus lib does not seem to work with non-default ccname, or I failed to figure out how to make it work with non-default ccname.
