### ISSUE TITLE
zlib crc32 bug causes server to reject message

### ISSUE THREAD

**Issue by rthalley** [edenhill/librdkafka#223]
If you produce with a key but specify NULL and 0 length for the payload (i.e. sending a "deletion tombstone" for keyed log compaction) then the message will be rejected by the server due to a bad CRC.  The message is sent with CRC 0 which is wrong.  This is because the zlib crc32() function erroneously returns 0 as the CRC instead of the initial CRC if NULL is passed in as the pointer.  It does the right thing for 0 length but some other value pointer, e.g. unsigned char junk; x = crc32(original, &junk, 0) works.

This isn't librdkafka's fault, of course, but it might be good if it worked around it.  I will submit a bug report for zlib too.

**Comment by rthalley** [comment]
Hmm, on second reading it looks like zlib is meant to work this way as it's the way to initialize an incremental CRC computation.  Still, might be nice to work around it.

**Comment by edenhill** [comment]
Yeah, I too stumbled on this issue yesterday, fix is on the way. Thanks!

**Comment by edenhill** [comment]
Huhm, are you still seeing this on master?
This should've been fixed in 7305785492caa9b3f16be5c63fe6c9afb3d039d2

**Comment by rthalley** [comment]
It is fixed on master.
