### ISSUE TITLE
Configuration Property : 'socket.blocking.max.ms' of librdkafka

### ISSUE THREAD

**Issue by rohitajmera** [edenhill/librdkafka#2233]
Description
@edenhill  and @mhowlett  please comment
is the property : "socket.blocking.max.ms" deprecated
I have a sync producer which performs very fast when this property is set to a minimal value(as needed by me)

I am using librdkafka version 0.11.6
OS : windows
Confluent Kafka : 0.11.6
Producer config : 
new Dictionary<string, object>()
                {
                    { "bootstrap.servers",  serverString},
                    { "client.id", "producer name" },
                    //{ "batch.num.messages" ,"1" },
                    { "socket.blocking.max.ms", "1" },
                    //{ "queue.buffering.max.ms", "0" }, // for immediate transmission, the above 2 properties decrease message latency.
                    { "default.topic.config", new Dictionary<string, object>
                        {
                            { "acks", "all" }
                        }
                    }
                }

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [x] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
In the upcoming v1.0.0 release, socket.blocking.max.ms is no longer needed or used, you will get low latency by default.
