### ISSUE TITLE
confluent python kafka client crash

### ISSUE THREAD

**Issue by aelanthi** [edenhill/librdkafka#2234]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Kafka python client crashed and produced core file. The core file produced by python points to librdkafka.so library

How to reproduce
================
No specific steps to reproduce, just happened once so far

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.5`
 - [x] Apache Kafka version: `kafka_2.11-2.0.0`
 - [x] librdkafka client configuration: `'client.id' : 'client_name', 'group.id': 'client_name','session.timeout.ms' : 6000`
 - [x] Operating system: `ubuntu 14.04`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue
[python_confluent_kafka_gdb_trace.txt](https://github.com/edenhill/librdkafka/files/2886237/python_confluent_kafka_gdb_trace.txt)

**Comment by edenhill** [comment]
I believe this issue has been fixed on librdkafka master, we'll have a v1.0.0 release shortly.
