### ISSUE TITLE
Could you build an release dll or lib file, and put it into Release part?

### ISSUE THREAD

**Issue by yazi1297** [edenhill/librdkafka#2236]
As you know, it''s difficult to prepare the build environment, I think most of people want a file that published officially. 
So, could you help us to build a release version librdkafka file that support windows xp, windows vista or higher, and put it into release part in this git project. 
Thank you.

**Comment by edenhill** [comment]
We suggest you use the NuGet packages at https://www.nuget.org/packages/librdkafka.redist/, which come with all required dependencies.
The nupkg is a zip file you can open and copy the library files for your platform and arch from the runtimes/ directory.
