### ISSUE TITLE
seek reset to OFFSET_END for invalid offset and returns no error

### ISSUE THREAD

**Issue by fesun** [edenhill/librdkafka#2238]
I am trying to use the seek API to move the offset forward and backward, however when I provide one invalid offset(say smaller than low or larger than high), the API returns ERR_NO_ERROR instead of reporting invalid offset, and librdkafka resets the offset to OFFSET_END no matter what's the offset before calling seek. If this is by design, is it better to comment in the doc?

I read the source code and found https://github.com/edenhill/librdkafka/blob/d306f5f7ef2aea04cdb9e7146796efd4a28d49f1/src/rdkafka_partition.c#L2274 always returns RD_KAFKA_RESP_ERR_NO_ERROR. If librdkafka never returns error for seek, is it better to set to OFFSET_BEGINNING if the provided offset is smaller than low and to OFFSET_END if it's larger than high? For example when we recover from crash, we'd like to read from the last offset, maybe that offset is smaller than current low due to expiration, we want to read from beginning in order to lose as little data as possible. If last offset is 12 and current low is 10, we may first query partition offset watermark, and then choose 12, but offset 12 may become invalid when we call seek.

**Comment by edenhill** [comment]
seek() is asynchronous, it simply sets the next offset to fetch, an invalid offset will be detected later when the offset is being fetched.
When this happens the auto.offset.reset policy will kick in, if you want to be notified you should set this option to `error` to have a consumer error raised (a message with the `.err` field set to, in this case, ERR_OFFSET_OUT_OF_RANGE).

In your case it sounds like you should simply set auto.offset.reset=earliest to have it use the earliest available offset if your seek():ed to offset is invalid.

**Comment by fesun** [comment]
Thanks for your excellent reply.
