### ISSUE TITLE
KafkaConsumer not consume due to no partition assigned when the lib updated from V0.8.X to V1.0

### ISSUE THREAD

**Issue by boatfish** [edenhill/librdkafka#2241]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
the code of client is not changed and the rebalance callback is not triggered(no assigin or revoke)
the debug log is here：

%7|1551326621.644|ASSIGN|rdkafka#consumer-5| [thrd:main]: Group "test_finalconsumer": new assignment of 0 partition(s) in join state assigned
%7|1551326621.644|BARRIER|rdkafka#consumer-5| [thrd:main]: Group "test_finalconsumer": rd_kafka_cgrp_assign:2354: new version barrier v113
%7|1551326621.644|ASSIGN|rdkafka#consumer-5| [thrd:main]: Group "test_finalconsumer": assigning 0 partition(s) in join state assigned
%7|1551326621.644|CGRPOP|rdkafka#consumer-8| [thrd:main]: Group "test_finalconsumer" received op ASSIGN (v0) in state query-coord (join state assigned, v76 vs 0)
%7|1551326621.645|ASSIGN|rdkafka#consumer-8| [thrd:main]: Group "test_finalconsumer": new assignment of 0 partition(s) in join state assigned
%7|1551326621.645|CGRPOP|rdkafka#consumer-5| [thrd:main]: Group "test_finalconsumer" received op ASSIGN (v0) in state query-coord (join state assigned, v113 vs 0)
%7|1551326621.645|ASSIGN|rdkafka#consumer-5| [thrd:main]: Group "test_finalconsumer": new assignment of 0 partition(s) in join state assigned
%7|1551326621.645|BARRIER|rdkafka#consumer-5| [thrd:main]: Group "test_finalconsumer": rd_kafka_cgrp_assign:2354: new version barrier v114
%7|1551326621.645|ASSIGN|rdkafka#consumer-5| [thrd:main]: Group "test_finalconsumer": assigning 0 partition(s) in join state assigned
%7|1551326621.644|CGRPOP|rdkafka#consumer-2| [thrd:main]: Group "test_finalconsumer" received op ASSIGN (v0) in state query-coord (join state assigned, v111 vs 0)
%7|1551326621.645|ASSIGN|rdkafka#consumer-2| [thrd:main]: Group "test_finalconsumer": new assignment of 0 partition(s) in join state assigned
%7|1551326621.645|BARRIER|rdkafka#consumer-2| [thrd:main]: Group "test_finalconsumer": rd_kafka_cgrp_assign:2354: new version barrier v112
%7|1551326621.645|ASSIGN|rdkafka#consumer-2| [thrd:main]: Group "test_finalconsumer": assigning 0 partition(s) in join state assigned
%7|1551326621.644|BARRIER|rdkafka#consumer-6| [thrd:main]: Group "test_finalconsumer": rd_kafka_cgrp_assign:2354: new version barrier v98
%7|1551326621.645|ASSIGN|rdkafka#consumer-6| [thrd:main]: Group "test_finalconsumer": assigning 0 partition(s) in join state assigned
%7|1551326621.645|CGRPOP|rdkafka#consumer-2| [thrd:main]: Group "test_finalconsumer" received op ASSIGN (v0) in state query-coord (join state assigned, v112 vs 0)
%7|1551326621.645|ASSIGN|rdkafka#consumer-2| [thrd:main]: Group "test_finalconsumer": new assignment of 0 partition(s) in join state assigned
%7|1551326621.645|BARRIER|rdkafka#consumer-2| [thrd:main]: Group "test_finalconsumer": rd_kafka_cgrp_assign:2354: new version barrier v113
%7|1551326621.645|CGRPOP|rdkafka#consumer-6| [thrd:main]: Group "test_finalconsumer" received op ASSIGN (v0) in state query-coord (join state assigned, v98 vs 0)
%7|1551326621.645|ASSIGN|rdkafka#consumer-6| [thrd:main]: Group "test_finalconsumer": new assignment of 0 partition(s) in join state assigned
%7|1551326621.645|BARRIER|rdkafka#consumer-6| [thrd:main]: Group "test_finalconsumer": rd_kafka_cgrp_assign:2354: new version barrier v99
%7|1551326621.645|ASSIGN|rdkafka#consumer-6| [thrd:main]: Group "test_finalconsumer": assigning 0 partition(s) in join state assigned
%7|1551326621.644|CGRPOP|rdkafka#consumer-4| [thrd:main]: Group "test_finalconsumer" received op ASSIGN (v0) in state query-coord (join state assigned, v122 vs 0)
%7|1551326621.645|ASSIGN|rdkafka#consumer-4| [thrd:main]: Group "test_finalconsumer": new assignment of 0 partition(s) in join state assigned
%7|1551326621.645|BARRIER|rdkafka#consumer-4| [thrd:main]: Group "test_finalconsumer": rd_kafka_cgrp_assign:2354: new version barrier v123
%7|1551326621.645|ASSIGN|rdkafka#consumer-4| [thrd:main]: Group "test_finalconsumer": assigning 0 partition(s) in join state assigned
%7|1551326621.644|BARRIER|rdkafka#consumer-1| [thrd:main]: Group "test_finalconsumer": rd_kafka_cgrp_assign:2354: new version barrier v155
%7|1551326621.645|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "test_finalconsumer": assigning 0 partition(s) in join state assigned
%7|1551326621.645|CGRPOP|rdkafka#consumer-4| [thrd:main]: Group "test_finalconsumer" received op ASSIGN (v0) in state query-coord (join state assigned, v123 vs 0)
%7|1551326621.645|ASSIGN|rdkafka#consumer-4| [thrd:main]: Group "test_finalconsumer": new assignment of 0 partition(s) in join state assigned
%7|1551326621.645|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "test_finalconsumer" received op ASSIGN (v0) in state query-coord (join state assigned, v155 vs 0)
%7|1551326621.645|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "test_finalconsumer": new assignment of 0 partition(s) in join state assigned
%7|1551326621.645|BARRIER|rdkafka#consumer-1| [thrd:main]: Group "test_finalconsumer": rd_kafka_cgrp_assign:2354: new version barrier v156
%7|1551326621.645|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "test_finalconsumer": assigning 0 partition(s) in join state assigned
%7|1551326621.644|CGRPOP|rdkafka#consumer-3| [thrd:main]: Group "test_finalconsumer" received op ASSIGN (v0) in state query-coord (join state assigned, v130 vs 0)
%7|1551326621.645|ASSIGN|rdkafka#consumer-3| [thrd:main]: Group "test_finalconsumer": new assignment of 0 partition(s) in join state assigned
%7|1551326621.645|BARRIER|rdkafka#consumer-3| [thrd:main]: Group "test_finalconsumer": rd_kafka_cgrp_assign:2354: new version barrier v131

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It looks like one of two things:
 * you have more consumers than partitions in your consumer group ,thus leaving some consumers without an assignment.
 * you are subscribing to non-existent topics

Set `debug=cgrp` to get more detailed information what is going on.
