### ISSUE TITLE
Is there some missing error codes?

### ISSUE THREAD

**Issue by masahiro-kondo-quick** [edenhill/librdkafka#2245]
Description
===========
This is a question.
When I compared rdkafka.h in librdkafka and clients\src\main\java\org\apache\kafka\common\protocol\Errors.java in Apache Kafka to handle Kafka errors, it seems some difference is appears in broker error code.
Rdkafka converts some error codes? Or is there some missing codes?
If you give me some advice, I'm so happy .

In librdkafka (`rdkafka.h`)
```
        /** Topic deletion is disabled */
        RD_KAFKA_RESP_ERR_TOPIC_DELETION_DISABLED = 73,
        /** Unsupported compression type */
        RD_KAFKA_RESP_ERR_UNSUPPORTED_COMPRESSION_TYPE = 74,
```

In Apache Kafka (`clients\src\main\java\org\apache\kafka\common\protocol\Errors.java`)
```
    TOPIC_DELETION_DISABLED(73, "Topic deletion is disabled.",
            TopicDeletionDisabledException::new),
    FENCED_LEADER_EPOCH(74, "The leader epoch in the request is older than the epoch on the broker",
            FencedLeaderEpochException::new),
    UNKNOWN_LEADER_EPOCH(75, "The leader epoch in the request is newer than the epoch on the broker",
            UnknownLeaderEpochException::new),
    UNSUPPORTED_COMPRESSION_TYPE(76, "The requesting client does not support the compression type of given partition.",
            UnsupportedCompressionTypeException::new);
```

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v0.11.5`
 - [X] Apache Kafka version: `2.1.0`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This happens when support for a new Kafka feature is added to librdkafka before the Apache Kafka release has been finalized, and a new PR is merged which changes the order of the error codes.

We'll fix this in the next version of librdkafka.

Thanks for pointing it out.
