### ISSUE TITLE
I'm having trouble with the consumer side

### ISSUE THREAD

**Issue by ChildePig** [edenhill/librdkafka#2246]
Description
===========
I've been testing on consumption and found that the use of low-level consumer(RdKafka::Consumer) spending is far higher than that of using high-level consumer(RdKafka::KafkaConsumer) , the same cluster, the data of the same size of 200 bytes, the same test environment, use low-level consumer(RdKafka::Consumer) consumption can reach 100000 per second, but with the senior consumers(RdKafka::KafkaConsumer) only reach thousands per second.

all test use by the demo rdkafka_excample.exe  and  rdkafka_consumer_example.exe.

I hope to get some help or advice,please.

Please provide the following information:

 - [0.11.3] librdkafka version (release number or git tag)
 - [0.10.0] Apache Kafka version
 - [default]  librdkafka client configuration
 - [win10] Operating system

**Comment by edenhill** [comment]
Can you try to reproduce this behaviour with v1.0.0, and if so also provide relevant parts of your code?

**Comment by ChildePig** [comment]
> Can you try to reproduce this behaviour with v1.0.0, and if so also provide relevant parts of your code?

ok，with v1.0.0 , msg.size=200bytes, 
 Consumer :  100000/sec    KafkaConsumer:  28000/sec.  

that's enough for me.

i tested other things, when use std::thread to consume()  ,can't simply use std::this_thread::sleep_for,  the sleep_for can take up to 20ms, even when used nanoseconds.
but if you use  std::this_thread::yield, it  in turn causes CPU preemption problems.

So I'm going to use consume_batch and with sleep_for now to control consumption, like this:

`	auto begin_time = clock();
	while (!bexit)
	{
		while (true)
		{
			++num;
			if( (num%10000 == 0 && num!=0) || ((time_span % 10 == 0) && (time_span > 0)))
			{
				break;
			}			
			RdKafka::Message *msg = consumer->consume(1000);
                        msg_consume(msg, NULL);
                        delete msg;
		}		
		auto this_time = clock();
		time_span = this_time - begin_time;
		int count = time_span/1000;

		if ((time_span % 1000 == 0) && (time_span >= 1000))
		{
			std::lock_guard<std::mutex> lk(mut);
			cout<<count <<"tread:"<<std::this_thread::get_id()<<",speed:"<< num / count <<" n/sec." << endl;
		}

		std::this_thread::sleep_for(std::chrono::milliseconds(1));
		//std::this_thread::yield();
	}`
