### ISSUE TITLE
Weird assignment timing issue

### ISSUE THREAD

**Issue by bencyoung** [edenhill/librdkafka#2249]
Description
===========
I have a weird issue with some integration tests I've written for our Kafka support. We're using the .NET Confluent.Kafka package, but I think the issue we're having is lower level than this, and possibly timing based.

We have a sequence of tests that all start off by sending a message on a 1 partition Test topic to get the latest offset. The tests then proceed to send and consume messages from this offset and generally it works well. 

One test fails consistently, but only after one or more other tests have been run. When run standalone it works fine. If I add "debug": "consumer" it still fails, but if I have "debug":"fetch" it passes. Any other debug options cause it to pass. Debugging and pausing at random points and then continuing often causes it to pass too.

The test simply does this:
Prelude: Produce a message and record the offset + 1
1. Create a producer and a simple message. 
2. Wait for the acknowledgement
3. Destroy the producer
4. Start a consumer with a manual rebalancing callback
5. In the rebalance callback and return (partition, offset+1 from above) 
6. Wait for the callback to be invoked
7. Use the explicit Poll to read the message from the queue. 

With debug:consumer (which fails) the log looks something like:
```
My log: Next offset: 42871
[thrd:main]: Group "61ad6423-5cfc-4080-b5fe-873b6ddc0316": subscribe to new subscription of 1 topics (join state init)
My log: Subscribing to 'Test' as 'Test#consumer-8'
[thrd:main]: Group "61ad6423-5cfc-4080-b5fe-873b6ddc0316": postponing join until up-to-date metadata is available
[thrd:main]: Group "61ad6423-5cfc-4080-b5fe-873b6ddc0316": subscription updated from metadata change: rejoining group
[thrd:main]: 10.244.224.111:9092/1: Joining group "61ad6423-5cfc-4080-b5fe-873b6ddc0316" with 1 subscribed topic(s)
[thrd:main]: Group "61ad6423-5cfc-4080-b5fe-873b6ddc0316": "range" assignor run for 1 member(s)
Assigning partition '0' at offset '42871'
[thrd:main]: Group "61ad6423-5cfc-4080-b5fe-873b6ddc0316": new assignment of 1 partition(s) in join state wait-assign-rebalance_cb
[thrd:main]: Partition Test [0] start fetching at offset 42871
...
Nothing else
```

if I set debug:fetch it always passes, but looks like:

```
My log: Next offset: 42876
[thrd:main]: Group "437ccdb8-9072-47cd-8bf8-4c48dacb8f84": subscribe to new subscription of 1 topics (join state init)
My log: Subscribing to 'Test' as 'Test#consumer-8'
[thrd:main]: Group "437ccdb8-9072-47cd-8bf8-4c48dacb8f84": postponing join until up-to-date metadata is available
[thrd:main]: Group "437ccdb8-9072-47cd-8bf8-4c48dacb8f84": subscription updated from metadata change: rejoining group
[thrd:main]: 10.244.224.111:9092/1: Joining group "437ccdb8-9072-47cd-8bf8-4c48dacb8f84" with 1 subscribed topic(s)
[thrd:main]: Group "437ccdb8-9072-47cd-8bf8-4c48dacb8f84": "range" assignor run for 1 member(s)
Assigning partition '0' at offset '42876'
[thrd:main]: Group "437ccdb8-9072-47cd-8bf8-4c48dacb8f84": new assignment of 1 partition(s) in join state wait-assign-rebalance_cb
[thrd:main]: Partition Test [0] start fetching at offset 42876
[thrd:10.244.224.111:9092/bootstrap]: 10.244.224.111:9092/1: Topic Test [0] in state active at offset 42876 (0/100000 msgs, 0/1048576 kb queued, opv 2) is fetchable: 
[thrd:10.244.224.111:9092/bootstrap]: 10.244.224.111:9092/1: Fetch topic Test [0] at offset 42876 (v2)
[thrd:10.244.224.111:9092/bootstrap]: 10.244.224.111:9092/1: Fetch 1/1/1 toppar(s)
[thrd:10.244.224.111:9092/bootstrap]: 10.244.224.111:9092/1: Enqueue 1 message(s) (39 bytes, 1 ops) on Test [0] fetch queue (qlen 1, v2, last_offset 42876, 0 ctrl msgs)
[thrd:10.244.224.111:9092/bootstrap]: 10.244.224.111:9092/1: Fetch topic Test [0] at offset 42877 (v2)
[thrd:10.244.224.111:9092/bootstrap]: 10.244.224.111:9092/1: Fetch 1/1/1 toppar(s)
[thrd:main]: Group "437ccdb8-9072-47cd-8bf8-4c48dacb8f84": new assignment of 0 partition(s) in join state started
[thrd:main]: Group "437ccdb8-9072-47cd-8bf8-4c48dacb8f84": unassigning 1 partition(s) (v5)
```

I'm at a bit of a loss how to proceed. It doesn't appear to be affecting our production stuff but it would be nice to understand, or at least mitigate!

Checklist
=========

Please provide the following information:

 - [x] librdkafka version 0.11.6

**Comment by bencyoung** [comment]
Note I can see the message appear via the console-consumer

**Comment by edenhill** [comment]
I've seen similar issues when using `acks=1` (default) on the producer, if consumption is done close to produce succeeding the high watermark might not have increased and the consumer will not see the message until the ISRs have fetched the newly produced message and their high watermarks have propagated back to the master.
So before troubleshooting this further I suggest setting `acks=all` on the producer.

**Comment by bencyoung** [comment]
Thanks for the quick response. Will give that a try and let you know

**Comment by bencyoung** [comment]
Ok, I've resolved the issue and as was likely there was a bug on my side! In the unit tests we have a wait loop that waits for the partitions to be assigned so that we know it's safe to continue. To get the assignment callback invoked we call Poll intermittently .

What I didn't realise was that in the version of the client I'm using, if you call Poll and don't have a message delivery callback registered it throws any messages received into the void. So I think we were getting assignment and a message in the same call to Poll and discarding the later. Changing logging etc moved when the messages was delivered.

Now we capture any messages and put them in a local queue to be delivered first. Will be more careful calling Poll in the future!
