### ISSUE TITLE
The problem of "broker" offset store method

### ISSUE THREAD

**Issue by bbgasj** [edenhill/librdkafka#225]
Hi，I found two problem in the "broker" method:
1、if consumer was not registerd ZK，you will get RD_KAFKA_RESP_ERR_UNKNOWN_TOPIC_OR_PART
and retry default times.
2、if topic was not find or offset was out of range，it will hanging. That's because when you do not find the right offset , it will try to reset this, but in the rd_kafka_toppar_offset_request()，when rkt_conf.offset_store_method == RD_KAFKA_OFFSET_METHOD_BROKER, it will try to get offset from broker, and fail....and retry...and try to get offset from broker...and fail.....and retry....

Solution:
1、I set a flag to diff common offset request and reset offset request to solve the second problem.
2、I add rd_kafka_toppar_offset_commit(rktp, 0) when get RD_KAFKA_RESP_ERR_UNKNOWN_TOPIC_OR_PART in the rd_kafka_toppar_offset_reply(), this made offset was out of range, so it try to reset.

**Comment by edenhill** [comment]
Thank you, I will look into this.

**Comment by alfred-landrum** [comment]
@bbgasj seeing this as well... would you be able to post a PR with your changes?

**Comment by bbgasj** [comment]
@alfred-landrum I'm now working for ZooKeeper Balance base on 0.85 (there are also some bugs founded when I do this); it will be finish this weekend; and it need to be tested for some days; And it also needs some times to update to 0.86, So I think I will uploads my codes this month. For this two problems;the first one, I just found codes change on 0.86 but the problem also exists, so it takes some times to fix this again;for the second problem; you can just add "rd_kafka_toppar_offset_commit(rktp, 0);" after # 3648 line in rdkafka_broker.c(0.86); this method was async, so just wait or change this to sync(all broker requests in a queue ).

**Comment by edenhill** [comment]
Fixed on master
