### ISSUE TITLE
Issue in seek operation, offset moved to beginning at times.

### ISSUE THREAD

**Issue by Gordon-The-Turtle** [edenhill/librdkafka#2256]
Description
===========

I am using a single consumer which is listening from a topic with a single partition.
Most of the time seek works fine and I am able to listen from the required offset but at other times, my application starts listening from the first message that was produced on the topic.
Seek was performed with a timeout of 3000 ms.

Following log is observed in event callback and detailed logs are provided below.
[rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Topic MY-TOPIC-INCOMING [0] in state offset-wait at offset 9 (0/100000 msgs, 0/1048576 kb queued, opv  3) **is not fetchable: not in active fetch state**

Error code returned by seek() is ERR_NO_ERROR;

Setup consists of :
2 zookeeper
3 kafka broker

How to reproduce
================
Note: Unfortunately, it does not happen every time.
Step 1: Create a topic with a single partition and produce some messages(in my case 9).
Step 2: Read all the messages using a consumer.
Step 3: Restart the consumer and perform a seek operation to read only new messages in rebalance callback.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<0.11.6>`
 - [x] Apache Kafka version: `<2.11-2.0.1>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `<CentOS Linux release 7.5.1804 (Core)>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka

  [INFO]  [MY-APPLICATION] : Trying to seek MY-TOPIC at offset : 9 with timeout of 3000.
  [MY-APPLICATION] : [thrd:app]: MY-TOPIC-INCOMING [0]: rd_kafka_toppar_op_seek:2247: new version barrier v3
  **[MY-APPLICATION] : [thrd:app]: Seek MY-TOPIC-INCOMING [0] to offset 9 (v3)**
  [rdk:main] : [thrd:main]: MY-TOPIC-INCOMING [0] received op SEEK (v3) in fetch-state offset-wait (opv2)
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Received OffsetResponse (v0, 44 bytes, CorrId 3, rtt 0.39ms)
  **[rdk:main] : [thrd:main]: Seek MY-TOPIC-INCOMING [0] to offset 9 in state offset-wait (v3)**
  [rdk:main] : [thrd:main]: Partition MY-TOPIC-INCOMING [0] changed fetch state offset-wait -> active
  [rdk:main] : [thrd:main]: Partition MY-TOPIC-INCOMING [0] start fetching at offset 9
  [rdk:main] : [thrd:main]: kafka3:9092/3: Wake-up
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: Topic MY-TOPIC-INCOMING [0]: fetch decide: updating to version 3 (was 0) at offset 9 (was 0)
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Topic MY-TOPIC-INCOMING [0] in state active at offset 9 (0/100000 msgs, 0/1048576 kb queued, opv 3) is fetchable: 
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Added MY-TOPIC-INCOMING [0] to fetch list (1 entries, opv 3) 
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Fetch topic MY-TOPIC-INCOMING [0] at offset 9 (v3)
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Fetch 1/1/1 toppar(s) 
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Sent FetchRequest (v4, 89 bytes @ 0, CorrId 4)
  [rdk:main] : [thrd:main]: kafka3:9092/3: Offset reply for topic MY-TOPIC-INCOMING [0] (v2 vs v3)
  [rdk:main] : [thrd:main]: kafka3:9092/3: Offset reply error for topic MY-TOPIC-INCOMING [0] (v2): Local: Outdated 
  [rdk:main] : [thrd:main]: MY-TOPIC-INCOMING [0]: outdated offset response: (re)starting offset query timer for offset BEGINNING
  [rdk:main] : [thrd:main]: Partition MY-TOPIC-INCOMING [0] changed fetch state active -> offset-query 
  [rdk:main] : [thrd:main]: Topic MY-TOPIC-INCOMING [0]: timed offset query for BEGINNING in state offset-query
  [rdk:main] : [thrd:main]: kafka3:9092/3: Partition MY-TOPIC-INCOMING [0]: querying for logical offset BEGINNING (opv 3)
  [rdk:main] : [thrd:main]: kafka3:9092/3: OffsetRequest (v0, opv 0) for 1 topic(s) and 1 partition(s)
  [rdk:main] : [thrd:main]: Partition MY-TOPIC-INCOMING [0] changed fetch state offset-query -> offset-wait
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Topic MY-TOPIC-INCOMING [0] in state offset-wait at offset 9 (0/100000 msgs, 0/1048576 kb queued, opv 3) is not fetchable: not in active fetch state
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Removed MY-TOPIC-INCOMING [0] from fetch list (0 entries, opv 3) 
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Sent OffsetRequest (v0, 76 bytes @ 0, CorrId 5)
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Received FetchResponse (v4, 60 bytes, CorrId 4, rtt 1001.06ms)
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Topic MY-TOPIC-INCOMING [0] MessageSet size 0, error "Success", MaxOffset 9, Ver 3/3
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Received OffsetResponse (v0, 44 bytes, CorrId 5, rtt 501.05ms)
  [rdk:main] : [thrd:main]: kafka3:9092/3: Offset reply for topic MY-TOPIC-INCOMING [0] (v3 vs v3)
  [rdk:main] : [thrd:main]: **Offset BEGINNING request for MY-TOPIC-INCOMING [0] returned offset 0 (0)**
  [rdk:main] : [thrd:main]: Partition MY-TOPIC-INCOMING [0] changed fetch state offset-wait -> active
  [rdk:main] : [thrd:main]: Partition MY-TOPIC-INCOMING [0] start fetching at offset 0
  [rdk:main] : [thrd:main]: kafka3:9092/3: Wake-up
  [rdk:main] : [thrd:main]: kafka2:9092/2: Heartbeat for group "my-topic-consumer-group" generation id 33
  **[rdk:broker3] : [thrd:kafka3:9092/bootstrap]: Topic MY-TOPIC-INCOMING [0]: fetch decide: updating to version 3 (was 3) at offset 0 (was 9)**
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Topic MY-TOPIC-INCOMING [0] in state active at offset 0 (0/100000 msgs, 0/1048576 kb queued, opv 3) is fetchable: 
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Added MY-TOPIC-INCOMING [0] to fetch list (1 entries, opv 3) 
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Fetch topic MY-TOPIC-INCOMING [0] at offset 0 (v3)
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Fetch 1/1/1 toppar(s) 
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Sent FetchRequest (v4, 89 bytes @ 0, CorrId 6)
  [rdk:broker2] : [thrd:kafka2:9092/bootstrap]: kafka2:9092/2: Sent HeartbeatRequest (v0, 113 bytes @ 0, CorrId 9)
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Received FetchResponse (v4, 1365 bytes, CorrId 6, rtt 0.44ms)
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Topic MY-TOPIC-INCOMING [0] MessageSet size 1305, error "Success", MaxOffset 9, Ver 3/3
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Enqueue 9 message(s) (675 bytes, 9 ops) on MY-TOPIC-INCOMING [0] fetch queue (qlen 9, v3, last_offset 8, 0 ctrl msgs) 
  **[rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Fetch topic MY-TOPIC-INCOMING [0] at offset 9 (v3)**

**[INFO]  [MY-APPLICATION] [:650]: New Message consumed from kafka.(Incorrect message received with offset 0, it has already been processed before.)**
  [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Fetch 1/1/1 toppar(s)
] [18_Mar_2019.08:25:36] [rdk:broker3] : [thrd:kafka3:9092/bootstrap]: kafka3:9092/3: Sent FetchRequest (v4, 89 bytes @ 0, CorrId 638)

 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by Gordon-The-Turtle** [comment]
Any update for the same?

**Comment by edenhill** [comment]
Thank you for a great issue report!

This is a timing issue in librdkafka, even though it is actively fetching from the seeked-to offset, it reverts to the original logical offset lookup and starts consuming at the auto.offset.reset policy:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_partition.c#L1322

Workaround:
if possible, try to use assign() to set the initial offset rather than sync.
Otherwise, have your application code check if the received offset is expected,  else perform another seek.

**Comment by Gordon-The-Turtle** [comment]
@edenhill Thanks for the response and suggesting possible workarounds.
Btw, till when can I expect the same to be fixed?

Thanks for your contribution to the community.

**Comment by Gordon-The-Turtle** [comment]
@edenhill Needed to clarify some of my doubts.
While researching over the possible solutions, I came across this issue : [https://github.com/edenhill/librdkafka/issues/1964](issue).
Even if i use the above mentioned approach(assign/ multiple seek), until I consume position function will always return -1001.
So how can i make sure the seek or assign function has successfully reached the required offset before consuming?

Your help will be highly appreciated.

**Comment by edenhill** [comment]
You know what offset you seek to, so after seeking you could ignore any messages that does not match the seeked-to-offset, until the seeked-to-offset is seen in a message and then you accept any offset.
There are some implications with auto.offset.reset here where the seeked-to-offset does not exist, but you could use auto.offset.reset=error to get an error when this happens.

**Comment by Gordon-The-Turtle** [comment]
Thanks for the quick response, ignoring the unrequired messages work fine. I am using this approach for now until the issue is resolved.
Thanks for your time.
