### ISSUE TITLE
Need to clarify 'opaq' in all API functions

### ISSUE THREAD

**Issue by asashnov** [edenhill/librdkafka#2258]
There are a lot of 'opaq' function arguments in src/rdkafka.h meaning different things.

To avoid any confusion, it is suggested to rename those arguments, never leaving just 'opaq'. It always should be rkt_opaque,  msg_opaque or other kind of opaque.

Otherwise, it leads to confusions.

For example:

https://github.com/edenhill/librdkafka/blob/v1.0.0-RC8/src/rdkafka.h#L858

```C
RD_EXPORT void
rd_kafka_topic_partition_list_sort (rd_kafka_topic_partition_list_t *rktparlist,
                                    int (*cmp) (const void *a, const void *b,
                                                void *opaque),
void *opaque);
```

should be changed to (if my guess is right, plese DOUBLE check it):

```C
RD_EXPORT void
rd_kafka_topic_partition_list_sort (rd_kafka_topic_partition_list_t *rktparlist,
                                    int (*cmp) (const void *a, const void *b,
                                                void *msg_opaque),
void *rkt_opaque);
```

https://github.com/edenhill/librdkafka/blob/v1.0.0-RC8/src/rdkafka.h#L1467

```C
RD_EXPORT void
rd_kafka_conf_set_background_event_cb (rd_kafka_conf_t *conf,
                                       void (*event_cb) (rd_kafka_t *rk,
                                                         rd_kafka_event_t *rkev,
void *opaque));
```

probably should be:

```C
RD_EXPORT void
rd_kafka_conf_set_background_event_cb (rd_kafka_conf_t *conf,
                                       void (*event_cb) (rd_kafka_t *rk,
                                                         rd_kafka_event_t *rkev,
void *rkt_opaque));
```

and so on, **especially in call back prototypes**.

This change can be local- just rename variable even in only function prototypes, limited to rdkafka.h file. But will be helpful to any novice developer, and will eliminate hours of debugging.

**Comment by edenhill** [comment]
This is a great idea! Will fix!

**Comment by edenhill** [comment]
Fixed on master
