### ISSUE TITLE
When will a heartbeat request be sent?

### ISSUE THREAD

**Issue by x-Zyte** [edenhill/librdkafka#2263]
Hey guys,
I wonder that If fetching block sending a heartbeat request, when will a heartbeat request be sent? Because fetch continuously according to its interval.

If I would like to set the "fetch.wait.max.ms" to 60000, then what is a suitable value of "heartbeat.interval.ms" and "session.timeout.ms"? The "heartbeat.interval.ms" should less than or more than or equal to the "fetch.wait.max.ms".?

**Comment by edenhill** [comment]
In librdkafka < v1.0.0 Hearbeats are possibly sent on the same connection as FetchRequests, which may cause Heartbeats to be blocked behind a Fetch request (which is only a problem if fetch.wait.max.ms is increased).
In librdkafka v1.0.0 a dedicated connection to the group coordinator is used for consumer joins, heartbeats, etc.
