### ISSUE TITLE
How to limit fetch size to avoid CPU cost

### ISSUE THREAD

**Issue by yfliuyanyan** [edenhill/librdkafka#2265]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>
I use librdkakfa as consumer side. Each time the number of messages are increased immediately, the CPU cost is highly. I feel bad that it is out of my control.

How to avoid this? What I think is to limit the consumer size for each batch. But I don't know which config is effective. Any config recommend?

My confParams info in rsyslog conf as follows:

confParam=[
                "topic.metadata.refresh.sparse=true",
                "fetch.message.max.bytes=1000000",
                "receive.message.max.bytes=10000000",
                "fetch.wait.max.ms=100",
                "socket.keepalive.enable=true",
                "socket.receive.buffer.bytes=2000000",
                "socket.send.buffer.bytes=2000000",
                "queued.max.messages.kbytes=25000"
        ]

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [x] Apache Kafka version: 0.10.1.1
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by yfliuyanyan** [comment]
any help?

**Comment by edenhill** [comment]
Please specify which librdkafka version you are on.

Is it the broker host or client host CPU that is running hot?
And what increase in CPU usage are you seeing?

I suggest leaving the config at its default values, they're usually good.
