### ISSUE TITLE
How Can I get connected success message at procedure

### ISSUE THREAD

**Issue by TheRoadToSuccess** [edenhill/librdkafka#2271]
I just use librdkafka at my project.
No, i need to do fail over work, which i need to know connect status to brokers.
I can get all brokers down message by  rd_kafka_conf_set_error_cb callback function,
but i can't get the connected success message, please give me some advice. thanks

all brokers down message:
% ERROR CALLBACK: rdkafka#producer-1: Local: Broker transport failure: localhost:9092/0: Disconnected (after 76057ms in state UP)
% ERROR CALLBACK: rdkafka#producer-1: Local: All broker connections are down: 2/2 brokers are down
% ERROR CALLBACK: rdkafka#producer-1: Local: Broker transport failure: 127.0.0.1:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)
% ERROR CALLBACK: rdkafka#producer-1: Local: Broker transport failure: localhost:9092/0: Connect to ipv6#[::1]:9092 failed: Connection refused (after 0ms in state CONNECT)

 
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You can check the client stats by adding a stats_cb and setting statistics.interval.ms, and check for broker states (UP). See https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

**Comment by TheRoadToSuccess** [comment]
thanks give me this advice,
but, i also has another question, i want to update kafka conf dynamic.
i don't want to check the state by state_cb, i just to check this status after all brokers down.
so, what need i to do.

**Comment by edenhill** [comment]
The kafka client configuration can't be updated after client instantiation, but you can add additional brokers calling rd_kafka_brokers_add().

**Comment by TheRoadToSuccess** [comment]
in my opinion，if I want to check the brokers state by state_cb every one minutes，which will cost some cpu time. so I just want to update conf dynamicly.
