### ISSUE TITLE
Difficulty cleaning up opaque pointer provided to rd_kafka_topic_conf_set_opaque

### ISSUE THREAD

**Issue by vaci** [edenhill/librdkafka#2272]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Difficulty cleaning up application's opaque pointer to topic callbacks.

I would like to use the rd_kafka_topic_conf_set_opaque call to provide topic-level client data in callbacks.

However, because topics are reference counted, and there is no way of indicating that a topic is not longer in use, it is difficult to find a way to release the memory allocated to hold the client data.

This is a particular problem when re-creating a topic that has been deleted using rd_kafka_topic_destroy. A call to rd_kafka_topic_new is likely to return the previous instance, still held by a reference count, and still bound to an existing client data opaque pointer. If that client data had also been deleted, the pointer is now invalid.

I can see no obvious was of determining when topic-level client data can be deleted, except when the entire  rd_kafka_t context has been destroyed. There is no interception point where the topic lifetime can be tracked.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.10.5
 - [X] Apache Kafka version: 2.0
 - [ ] librdkafka client configuration: Any
 - [X] Operating system:  Red Hat Enterprise Linux Server release 7.4
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka: NA
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Currently a topic_t object isn't freed until rd_kafka_destroy() is called, so even though the application has called rd_kafka_topic_destroy() symetrically, the next call to rd_kafka_topic_new() for the same topic name will return the old topic object, and its configuration can't be changed, including opaque pointer.

So I suggest you treat the topic object lifetime the same as the rd_kafka_t client instance.

**Comment by vaci** [comment]
I  understand, thank you for the response!
