### ISSUE TITLE
Unrecovered Broker State 

### ISSUE THREAD

**Issue by abhit011** [edenhill/librdkafka#2273]
There has been very bizarre Kafka Brokers getting down all of sudden, And I am really now able to figure out whats wrong thats happening.. 
I am running Kafka 7 broker nodes and 3 zk instances.... From the last 1 month this is the third incident where out of 7, 5 broker were literally not responding at the same time .. Please help me in understanding few things ... There are 4 topics with partition size of 50 each ... I am also attaching the controller.log file. 

1. On my Consumer App  Screen Shot . 
![image](https://user-images.githubusercontent.com/10906885/55642521-561bb480-57ee-11e9-9d1e-3ee62c1df225.png)

2. There are times on Producer side I get `AxKafkaResponse ULTRACRIC Bytes:245,Offset: -1001,Topic: LOC,Result: Local: Message timed out` and there are times I get `AxKafkaResponse ULTRACRIC Bytes:236,Offset: 26034016,Topic: LOC,Result: Broker: Request timed out`. 

Abhi
:wq 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<>`
 - [x] Apache Kafka version: `<0.10.2.0>`
 - [x] Operating system: `<Windows Server>`
  -[x] Provide broker log excerpts
 - [x ] Critical issue

[controller.zip](https://github.com/edenhill/librdkafka/files/3048871/controller.zip)

**Comment by abhit011** [comment]
I know when time out occurs, after reattempts when it fails to get delivered to leader broker, the internal message queue returns these messages. But what's Result: Broker: Request timed out

**Comment by edenhill** [comment]
Please provide librdkafka version and configuration.

The commit failures can typically be ignored, they will be retried as soon as a new group coordinator broker is available.

The Produce request errors, "Broker: Request timed out", indicates that the broker couldn't finish handling the produce request in time, typically because of replicas falling too far behind.

I believe both of these problems are in your cluster, and not your client.

**Comment by abhit011** [comment]
Yeah its not the librd client issue, i was just worried about Broker Request Time out ... There are times when my server CPU crosses 100% for few seconds <As there are other processes too running on the same server> it leads to lot of brokers falling into offline partitions state ...

**Comment by abhit011** [comment]
Also is this broker error or connection error 
![image](https://user-images.githubusercontent.com/10906885/55980016-20c10c00-5cb1-11e9-8e9e-f8953364554e.png)

**Comment by abhit011** [comment]
This was coming in broker log, only for this topic "LOC" it was coming , rest of the topics were fine . Hence not able to understood what went wrong for this topic 
![image](https://user-images.githubusercontent.com/10906885/55980444-1ce1b980-5cb2-11e9-83b8-8a8ae65d14ba.png)

**Comment by edenhill** [comment]
Operational broker issues are outside the scope of librdkafka community support.
