### ISSUE TITLE
Consumer group not able to recover due to group-coordinator not being available

### ISSUE THREAD

**Issue by luisteran1** [edenhill/librdkafka#2275]
I had a broker node go unresponsive in a 3 node kafka cluster. I have 3 replicas (1 on each node) and 6 partitions. When 

the node when unresponsive, my consumers were not able to retrieve any messages from the remaining two brokers due to the group coordinator not being available. When I started the sample consumer with another groupID, then the consumer worked fine. If there are 2/3 nodes/brokers left with 1 replica each, shouldn't a new group leader be picked?

[consumer_err.txt](https://github.com/edenhill/librdkafka/files/3056219/consumer_err.txt)

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following [information:]
 - [x] librdkafka version (release number or git tag): `0x000b06ff`
 - [x] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `-d all`
 - [ ] Operating system: ``
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka

**Comment by edenhill** [comment]
Consumer groups maps, after hashing, to a __consumer_offsets topic partition. My guess is that the loss of one of your brokers made the partition for the original group under-replicated and thus unavailable.
