### ISSUE TITLE
Questions regarding Conf

### ISSUE THREAD

**Issue by cumafo** [edenhill/librdkafka#2276]
Hi Magnus. 

Is it possible to use the same global conf for both a consumer and producer (in same process)? That is, consumer options are applied to the consumer and vice versa?

Having a common option for several topics, would it be enough to set it in the global conf? Or must all options be explicitly set on each topic?
Tried with 'message.timeout.ms' which is accepted in the global conf but seems to have no effect there.

Thx
C

libbrdkafka version v1.0

**Comment by edenhill** [comment]
Yes, librdkafka will currently ignore consumer properties on the producer and vice versa.
Future versions might add warnings for this, and eventually reject them, but we'll provide some means of disabling these checks then.

We do recommend setting the default topic configuration on the global rd_kafka_conf_t object, and not use set_default_topic_config().
