### ISSUE TITLE
Not able to block consumer when there is no message in the partition

### ISSUE THREAD

**Issue by ganeshnikam18** [edenhill/librdkafka#228]
I am using CPP interface from the library. I want to block my consumer if there are no message in the partition. There is configuration option: "consumer.timeout.ms"(defaults to  -1) to block the consumer. But in the library interface, I did not find the way to set it. Some queries here:

1. with current version of the library, is it possible to set this option ?
2. If not, then is there a way to configure this option and block the consumer ?
3. I did set this option in the Kafka server's config file, but still I see non blocking consumer. is this correct behaviour ?
4. Its default value is -1 (blocks indefinitely if no new message is available for consumption.). Then even if I don't set this option, my consumer should block. is this understanding correct ?

**Comment by edenhill** [comment]
librdkafka does not have the `consumer.timeout.ms` consumer configuration property, it does things
a bit differently.
When you call consume() on your Consumer handle you also pass a timeout which is the maximum amont of time it will wait/block for new messages, I think this is what you are after.
See here:
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L478
