### ISSUE TITLE
unknown broker error 

### ISSUE THREAD

**Issue by yyweii** [edenhill/librdkafka#2280]
Description
===========
KafkaConsumer reports unknown broker error after running several hours. What can i do with this error? 

Checklist
=========

 - [x] librdkafka version (release number or git tag): `0.11.6`
 - [x] Apache Kafka version: `0.9.0.1`

**Comment by edenhill** [comment]
Please provide the exact error / log message and fill out the checklist completely.

**Comment by yyweii** [comment]
> Please provide the exact error / log message and fill out the checklist completely.

The problem has been solved. I forgot to add  broker.version.fallback config. Thank you anyway!
