### ISSUE TITLE
What does "ERR_UNSUPPORTED_FOR_MESSAGE_FORMAT" mean?

### ISSUE THREAD

**Issue by XiaoyaoFan** [edenhill/librdkafka#2281]
Hi librdkafka,

I'm reading the https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#producer-message-delivery-failure, it mentions "ERR_UNSUPPORTED_FOR_MESSAGE_FORMAT" as one of "Typical permanent broker errors", would you mind helping to explain what does it mean? Is it related with any single message or mis-configuration?

Thanks in advance!

**Comment by edenhill** [comment]
According to the broker code this error will be returned if a transactional batch has messages with old message format, which will likely never happen unless the client is buggy.
Since librdkafka is not doing transactions yet this error will not be raised.

**Comment by XiaoyaoFan** [comment]
Thanks for the explanation!
