### ISSUE TITLE
Question: rkmessage of dr_msg_cb gets freeup by librdkafka

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#2282]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Hey @edenhill I am a little bit confused here.

**The rkmessage is destroyed automatically by librdkafka**

in my application, I have defined a structure pointer and have allocated dynamic memory into it. I am using this structure pointer to pass as **msg_opaque**. so do I need to release (free up) memory rkmessage->_private in dr_msg_cb()??

Thanks 
Jaydeep

**Comment by edenhill** [comment]
The msg_opaque that you pass to produce() will be passed backed to the  application as `rkmessage->_private` in the delivery report callback, at which point your application resumes ownership of that pointer and you can free it or do whatever you like.
