### ISSUE TITLE
delivery gets message timeout instead of broker down message

### ISSUE THREAD

**Issue by faladu** [edenhill/librdkafka#2286]
Description
===========
When no brokers are available the delivery callback doesn't come back after the delivery failed 2 times but waits till the message times out to come back with a message timeout error (after roughly 5mins).

================
Reproduction is probably the easiest if you use the following c code sample:

```
#include <rdkafka.h>
#include <string.h>
char delivered = 0;

static void dr_msg_cb(rd_kafka_t *rk,
    const rd_kafka_message_t *rkmessage, void *opaque) {

    if (rkmessage->err)
        fprintf(stderr, "%% Message delivery failed: %s\n",
        rd_kafka_err2str(rkmessage->err));
    else
        fprintf(stderr,
        "%% Message delivered (%zd bytes, "
        "partition %"PRId32")\n",
        rkmessage->len, rkmessage->partition);

    delivered = 1;    
    /* The rkmessage is destroyed automatically by librdkafka */
}

static void onError(rd_kafka_t *rk, int err, const char *reason, void *opaque){

    printf("Kafka Error: %s , Kafka Reason: %s \n", rd_kafka_err2str(err), reason);
}

int main(int argc, char *argv[])
{

    rd_kafka_t          *rk;
    rd_kafka_conf_t     *conf;
    rd_kafka_topic_t    *topic;

    char error[1024];
    char *message = "dummymessage";

    conf = rd_kafka_conf_new();

    rd_kafka_conf_set_error_cb(conf, onError);
    rd_kafka_conf_set_dr_msg_cb(conf, dr_msg_cb);

    rd_kafka_conf_set(conf, "security.protocol", "PLAINTEXT", error, sizeof(error));

    rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf, error, sizeof(error));
    rd_kafka_brokers_add(rk, "192.168.1.1:1"); //non existent dummy broker 

    topic = rd_kafka_topic_new(rk, "test", NULL);
    if(rd_kafka_produce(topic, RD_KAFKA_PARTITION_UA, 0, message, strlen(message), NULL, 0, NULL) == -1){
        printf("Error producing topic");
    }

    while (!delivered){
        rd_kafka_poll(rk, 1000);
    }

    return 0;
}
```

this results in the following output:

Kafka Error: Local: Broker transport failure , Kafka Reason: 192.168.1.1:1/bootstrap: Connect to ipv4#192.168.1.1:1 failed: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat... (after 21002ms in state CONNECT)
Kafka Error: Local: All broker connections are down , Kafka Reason: 1/1 brokers are down
% Message delivery failed: Local: Message timed out

I would have expected the delivery to also return with an error about the brokers being down. And ideally directly after all delivery tries failed.

Got the master checkout from today and compiled it to make sure the issue is with the current version.

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v1.0.0
 - [x] Apache Kafka version: none - error occurs when no brokers are available so no kafka is needed.
 - [x] librdkafka client configuration: see code above
 - [x] Operating system: windows 7 64 bit.

If anything else is needed I'll happily provide it.
Best regards
Max

**Comment by rolandyoung** [comment]
This is intended behaviour - it is covered by [this FAQ](https://github.com/edenhill/librdkafka/wiki/FAQ#why-does-rd_kafka_produce-always-seem-to-succeed-even-if-there-is-a-problem-connecting-to-the-kafka-brokers)

The library assumes that it may be possible to establish a connection (you might add another broker,  a network problem might ge resolved, etc, etc) until the message timeout (default 300 sec) expires.

**Comment by faladu** [comment]
Intresting thanks for the link 
What is max retries then for?
What error would it stop on after x retries instead of waiting for the message timeout?

**Comment by write2jaydeep** [comment]
I have experienced a similar problem.
even though I have set **message.timeout.ms** to 3000ms (3 sec) and retries to 0, it still waits for 5 min.
I am using simple_producer from examples.

**Comment by rolandyoung** [comment]
Sorry - missed the part about max retries. But I wonder whether that parameter only applies once a connection exists to an actual broker. I am surprised that any attempts to send the message are being made at all before a broker connection has been established.

**Comment by edenhill** [comment]
@rolandyoung See the manual for how retries are handled:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#producer-message-delivery-failure

**Comment by faladu** [comment]
Is there a way for me to know if the message timed out due to connectivity issues or because of some other problem where it did not get to max retries before the timeout?

**Comment by edenhill** [comment]
As stated in the documentation, any permanents errors will fail the message immediately and propagate the permanent error code unchanged, so you will not see ERR__MSG_TIMED_OUT for such errors.

**Comment by faladu** [comment]
Mh maybe I missed something but my understanding is once the message has been in the queue for the 5 min it times out.

I was just curious that if there are other retriable errors that can take longer than 5 minutes and would then have the message quit with the message timeout but are not from connection problems.

If not then i can tell the users of my application that this error message always indicates a connection problem

**Comment by edenhill** [comment]
ERR__MSG_TIMED_OUT is an aggregate error code covering all the possible temporary errors that will cause the message to retried, and eventually succeed, fail or time out.

While we could propagate one of the message errors instead of ERR__MSG_TIMED_OUT it is not clear which one to propagate; there could be multiple different error codes in the message.timeout.ms timespan: first there's a disconnect (ERR__TRANSPORT), followed by a connect error (ERR__TRANSPORT again), then the broker might be back up with bad config causing auth error (ERR__AUTH), then the broker config is fixed but the network barfs so the produceRequests time out with ERR_REQUEST_TIMED_OUT.  Which error should be represented as *the* message error?

All of the above errors, which are really client-level errors rather than message-level, are propagated separately through the client-level error_cb.

**Comment by faladu** [comment]
Knowing they all trigger the error cb is enough for me.
Then i just track what came through there and hand out the last 2 or 3 with the error.

I just wasn't sure that this is how it works.
Is there any document to read up on the retriable errors in detail?

And i guess they issue is solved. 
Thank you for all the info.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#producer-message-delivery-failure

**Comment by faladu** [comment]
I somehow missed the line about all other errors being permanent errors reading it the first time.

Thank you
