### ISSUE TITLE
the performance of producer for librdkafka v1.0.0 is decreased

### ISSUE THREAD

**Issue by boatfish** [edenhill/librdkafka#2288]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
the performance of syn producer was decreased when the latest librdkafka used， So I compared the performance of the two versions(v0.11.5 and v1.0.0 ). I run the rdkafka_performance in examples and here is the results.

PS: the kafka cluster and topic is same, msgsize is 512bytes
      the process run on the same machine

**v0.11.5**
% 10850900 messages produced (5555660800 bytes), 10693530 delivered (offset 0, 0 failed) in 13001ms: 822470 msgs/s and 421.10 MB/s, 0 produce failures, 157371 in queue, no compression
% 11699080 messages produced (5989928960 bytes), 11556310 delivered (offset 0, 0 failed) in 14001ms: 825349 msgs/s and 422.58 MB/s, 0 produce failures, 142770 in queue, no compression
% 12537690 messages produced (6419297280 bytes), 12417914 delivered (offset 0, 0 failed) in 15001ms: 827763 msgs/s and 423.82 MB/s, 0 produce failures, 119776 in queue, no compression
% 13359129 messages produced (6839874048 bytes), 13269362 delivered (offset 0, 0 failed) in 16001ms: 829243 msgs/s and 424.57 MB/s, 0 produce failures, 89767 in queue, no compression
% 14181083 messages produced (7260714496 bytes), 14027374 delivered (offset 0, 0 failed) in 17001ms: 825054 msgs/s and 422.43 MB/s, 0 produce failures, 153709 in queue, no compression
% 15004481 messages produced (7682294272 bytes), 14865138 delivered (offset 0, 0 failed) in 18002ms: 825747 msgs/s and 422.78 MB/s, 0 produce failures, 139348 in queue, no compression
% 15825609 messages produced (8102711808 bytes), 15748160 delivered (offset 0, 0 failed) in 19002ms: 828751 msgs/s and 424.32 MB/s, 0 produce failures, 77463 in queue, no compression
% 16655663 messages produced (8527699456 bytes), 16610549 delivered (offset 0, 0 failed) in 20002ms: 830433 msgs/s and 425.18 MB/s, 0 produce failures, 45115 in queue, no compression
% 17521743 messages produced (8971132416 bytes), 17451460 delivered (offset 0, 0 failed) in 21002ms: 830932 msgs/s and 425.44 MB/s, 0 produce failures, 70283 in queue, no compression
% 18428225 messages produced (9435251200 bytes), 18317681 delivered (offset 0, 0 failed) in 22002ms: 832536 msgs/s and 426.26 MB/s, 0 produce failures, 110544 in queue, no compression
% 19281609 messages produced (9872183808 bytes), 19102564 delivered (offset 0, 0 failed) in 23002ms: 830464 msgs/s and 425.20 MB/s, 0 produce failures, 179045 in queue, no compression
% 20066439 messages produced (10274016768 bytes), 20005586 delivered (offset 0, 0 failed) in 24002ms: 833487 msgs/s and 426.75 MB/s, 0 produce failures, 60853 in queue, no compression
% 20868354 messages produced (10684597248 bytes), 20814166 delivered (offset 0, 0 failed) in 25002ms: 832491 msgs/s and 426.24 MB/s, 0 produce failures, 54188 in queue, no compression
% 21732516 messages produced (11127048192 bytes), 21589016 delivered (offset 0, 0 failed) in 26002ms: 830274 msgs/s and 425.10 MB/s, 0 produce failures, 143500 in queue, no compression
% 22534808 messages produced (11537821696 bytes), 22479028 delivered (offset 0, 0 failed) in 27002ms: 832486 msgs/s and 426.23 MB/s, 0 produce failures, 55780 in queue, no compression
% 23401316 messages produced (11981473792 bytes), 23339894 delivered (offset 0, 0 failed) in 28002ms: 833500 msgs/s and 426.75 MB/s, 0 produce failures, 61422 in queue, no compression
% 24273812 messages produced (12428191744 bytes), 24179706 delivered (offset 0, 0 failed) in 29002ms: 833717 msgs/s and 426.86 MB/s, 0 produce failures, 94106 in queue, no compression
% 25101053 messages produced (12851739136 bytes), 25043883 delivered (offset 0, 0 failed) in 30002ms: 834733 msgs/s and 427.38 MB/s, 0 produce failures, 57170 in queue, no compression
% 25939917 messages produced (13281237504 bytes), 25875077 delivered (offset 0, 0 failed) in 31002ms: 834619 msgs/s and 427.32 MB/s, 0 produce failures, 64840 in queue, no compression
% 26839212 messages produced (13741676544 bytes), 26733880 delivered (offset 0, 0 failed) in 32002ms: 835374 msgs/s and 427.71 MB/s, 0 produce failures, 105332 in queue, no compression
% 27739285 messages produced (14202513920 bytes), 27597119 delivered (offset 0, 0 failed) in 33002ms: 836219 msgs/s and 428.14 MB/s, 0 produce failures, 142166 in queue, no compression
% 28548999 messages produced (14617087488 bytes), 28447336 delivered (offset 0, 0 failed) in 34002ms: 836630 msgs/s and 428.35 MB/s, 0 produce failures, 101663 in queue, no compression
% 29445361 messages produced (15076024832 bytes), 29210576 delivered (offset 0, 0 failed) in 35002ms: 834520 msgs/s and 427.27 MB/s, 0 produce failures, 234788 in queue, no compression
% 30208411 messages produced (15466706432 bytes), 30124440 delivered (offset 0, 0 failed) in 36003ms: 836713 msgs/s and 428.40 MB/s, 0 produce failures, 83972 in queue, no compression
^C% 30958782 messages produced (15850896384 bytes), 30958782 delivered (offset 0, 0 failed) in 36964ms: 837517 msgs/s and 428.81 MB/s, 0 produce failures, 0 in queue, no compression

**v1.0.0**
% 2304779 messages produced (1180046848 bytes), 1804782 delivered (offset 55686597, 0 failed) in 19024ms: 94865 msgs/s and 48.57 MB/s, 6874 produce failures, 499997 in queue, no compression
% 2305817 messages produced (1180578304 bytes), 1805818 delivered (offset 56051639, 0 failed) in 20025ms: 90174 msgs/s and 46.17 MB/s, 7377 produce failures, 499999 in queue, no compression
% 2411429 messages produced (1234651648 bytes), 1911430 delivered (offset 56021103, 0 failed) in 21027ms: 90902 msgs/s and 46.54 MB/s, 7737 produce failures, 499999 in queue, no compression
% 2511441 messages produced (1285857792 bytes), 2011442 delivered (offset 56030530, 0 failed) in 22031ms: 91298 msgs/s and 46.74 MB/s, 8078 produce failures, 499999 in queue, no compression
% 2602254 messages produced (1332354048 bytes), 2104166 delivered (offset 55826581, 0 failed) in 23033ms: 91351 msgs/s and 46.77 MB/s, 8417 produce failures, 498088 in queue, no compression
% 2702277 messages produced (1383565824 bytes), 2202277 delivered (offset 56032566, 0 failed) in 24035ms: 91626 msgs/s and 46.91 MB/s, 8758 produce failures, 500000 in queue, no compression
% 2904142 messages produced (1486920704 bytes), 2405487 delivered (offset 55844434, 0 failed) in 25038ms: 96072 msgs/s and 49.19 MB/s, 9019 produce failures, 498655 in queue, no compression
% 3081709 messages produced (1577835008 bytes), 2583621 delivered (offset 56077349, 0 failed) in 26042ms: 99206 msgs/s and 50.79 MB/s, 9267 produce failures, 498089 in queue, no compression
% 3268686 messages produced (1673567232 bytes), 2769213 delivered (offset 55664694, 0 failed) in 27042ms: 102400 msgs/s and 52.43 MB/s, 9546 produce failures, 499473 in queue, no compression

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
How many partitions does the topic have?

Can you try running the v1.0.0 benchmarks with `-X linger.ms=50` ?

**Comment by boatfish** [comment]
> How many partitions does the topic have?
 **22 partitions**
> Can you try running the v1.0.0 benchmarks with `-X linger.ms=50` ?
   I run the v1.0.0 benchmarks with the config `-X linger.ms=50` ( ./rdkafka_performance -P -b XXXX:9092 -t TEST -s 512 -X linger.ms=50) 

% 794918 messages produced (406998016 bytes), 296833 delivered (offset 62300036, 0 failed) in 1000ms: 296746 msgs/s and 151.93 MB/s, 63 produce failures, 498085 in queue, no compression
% 1122366 messages produced (574651392 bytes), 624279 delivered (offset 62592603, 0 failed) in 2002ms: 311800 msgs/s and 159.64 MB/s, 200 produce failures, 498087 in queue, no compression
% 1425023 messages produced (729611776 bytes), 926583 delivered (offset 62246168, 0 failed) in 3002ms: 308637 msgs/s and 158.02 MB/s, 338 produce failures, 498440 in queue, no compression
% 1738405 messages produced (890063360 bytes), 1240319 delivered (offset 62129820, 0 failed) in 4005ms: 309671 msgs/s and 158.55 MB/s, 478 produce failures, 498086 in queue, no compression
% 2048306 messages produced (1048732672 bytes), 1550219 delivered (offset 62241147, 0 failed) in 5013ms: 309231 msgs/s and 158.33 MB/s, 619 produce failures, 498087 in queue, no compression
% 2367774 messages produced (1212300288 bytes), 1867774 delivered (offset 62430695, 0 failed) in 6015ms: 310481 msgs/s and 158.97 MB/s, 753 produce failures, 500000 in queue, no compression
% 2702538 messages produced (1383699456 bytes), 2204451 delivered (offset 62169992, 0 failed) in 7015ms: 314204 msgs/s and 160.87 MB/s, 891 produce failures, 498088 in queue, no compression
% 3035402 messages produced (1554125824 bytes), 2535402 delivered (offset 62322688, 0 failed) in 8020ms: 316130 msgs/s and 161.86 MB/s, 1035 produce failures, 500000 in queue, no compression
% 3364034 messages produced (1722385408 bytes), 2865947 delivered (offset 62191035, 0 failed) in 9023ms: 317626 msgs/s and 162.62 MB/s, 1182 produce failures, 498088 in queue, no compression
% 3642544 messages produced (1864982528 bytes), 3144457 delivered (offset 62299428, 0 failed) in 10025ms: 313660 msgs/s and 160.59 MB/s, 1326 produce failures, 498088 in queue, no compression

**Comment by boatfish** [comment]
I find the reason that the default value of “request.required.acks” is "-1", but why it is not included in the config dump with default value?

**Comment by edenhill** [comment]
What do you mean it is not included? `rdkafka_performance -X list | grep acks` and `rdkafka_example -X dump` both report `-1` as the default and set value.

**Comment by boatfish** [comment]
I use rd_kafka_conf_dump dump the config and make a comparison between the two versions，but I can't find the “request.required.acks”.

**Comment by edenhill** [comment]
That setting is on the (default) topic config object, you can extract a copy by calling rd_kafka_default_topic_config_dup() that you can then pass to topic_conf_dump()

**Comment by boatfish** [comment]
I see, it's my fault. and is it ok if I set “request.required.acks” in global config instead of topic config?

**Comment by edenhill** [comment]
Yes, as long as you don't overwrite the default topic config (by setting rd_kafka_conf_set_default_topic_conf()) you can specify any topic-configuration on the global rd_kafka_conf_t object.

**Comment by boatfish** [comment]
ok, thanks very much
