### ISSUE TITLE
How to set retention?

### ISSUE THREAD

**Issue by martin-jenny** [edenhill/librdkafka#2289]
How to set the retention for a topic with librdkafka?
```
log.retention.ms=xxx
log.retention.minutes=xxx
log.retention.hours=xxx
log.retention.bytes=xxx
```

**Comment by edenhill** [comment]
Use the Admin API's AlterConfigs():
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L5643

**Comment by neha2007** [comment]
@edenhill Could you please share an example code where we can set the retention period while creating topic using rd_kafka_CreateTopics API. Or if we can set the retention period after the topic is created.

**Comment by edenhill** [comment]
This is part of the test-suite, so overly complex, but I think you can sift out the relevant parts:
https://github.com/edenhill/librdkafka/blob/master/tests/0081-admin.c#L112

**Comment by neha2007** [comment]
@edenhill 
Using Admin API's AlterConfigs(), can we configure Topic configuration parameter - "message.format.version" from librdkafka client?

Please share example code if yes. Thanks in advance.

**Comment by edenhill** [comment]
Same way you would configure other topic properties, see my previous comment.
