### ISSUE TITLE
send a msg to a broker successfully, but the kafka server is closed.

### ISSUE THREAD

**Issue by Yrp** [edenhill/librdkafka#229]
hi, edenhill 
my program sends a msg to a broker successfully, but the kafka server is closed on the broker.
code:
```c++
   boost::shared_ptr<RdKafka::Conf> conf(RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL));
   conf->set("metadata.broker.list", "", errstr);
   producer = boost::shared_ptr<RdKafka::Producer>(RdKafka::Producer::create(conf.get(), errstr));
   RdKafka::ErrorCode resp = m_eventProducer->produce(
        m_eventTopic.get(), 
        RdKafka::Topic::PARTITION_UA,
        RdKafka::Producer::RK_MSG_COPY,
        const_cast<char *>(_data.data()),
        _data.size(),
        NULL, 
        NULL);
```
produce handle is executed, the value of the resp is RdKafka::ERR_NO_ERROR. But **metadata.broker.list** is empty.

What is the reason？

Thanks.

**Comment by Yrp** [comment]
You are a good man. Thanks for your help. I know what you say. 
Thanks again.

**Comment by Yrp** [comment]
I just want to know how to get the error when kafka broker is bad.

**Comment by edenhill** [comment]
Register a delivery report callback (dr_cb) and call poll every now and then and you will receive delivery status per message

**Comment by Yrp** [comment]
I konw , Thanks.
