### ISSUE TITLE
Combining Kafka libraries and Protocol Buffer libraries into one program.  Need help?

### ISSUE THREAD

**Issue by tgredfish** [edenhill/librdkafka#2290]
I am trying to use VS2017 to build a program that includes the Kafka libraries and the ProtocolBuffer libraries. The goal is to build ProtocolBuffer objects and add them to a Kafka topic that will be consumed by a host process. The recommendation by the google website is to compile & link ProtocolBuffer as a static library. I have done that and I was able to link that into my program. When I try to compile and link the Kafka library as a static library, I get many link errors when I include the OpenSSL libraries I downloaded (the static builds).
When I installed the librdkafka.redist package you referenced above without the protocol buffer libraries, I was able to get the kafka calls to work properly. But, when I included the Protocol Buffer libraries, I get many link error with that library.
I tried the target solution to both v140 and v141 with basically the same problems. Do you have any recommendations on how to get both of these packages to compile and link into the same program? Thanks ahead of time for your response.

**Comment by edenhill** [comment]
Did you get linking errors for librdkafka or protobuf symbols?

**Comment by tgredfish** [comment]
Is there an easy way to compile the librdkafka without any dependencies on the OpenSSL package?

I took your advice and in one of the projects I have been trying to get this resolved, I installed the nuget package for librdkafka.  When I did that and tried to relink with the protocol buffer static libraries I get protocol buffer errors like:
FSRiteTrxDlg.obj : error LNK2001: unresolved external symbol "struct google::protobuf::internal::SCCInfo<0> protobuf_google_2fprotobuf_2ftimestamp_2eproto::scc_info_Timestamp" (?scc_info_Timestamp@protobuf_google_2fprotobuf_2ftimestamp_2eproto@@3U?$SCCInfo@$0A@@internal@protobuf@google@@A)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "public: __thiscall google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (??0LogMessage@internal@protobuf@google@@QAE@W4LogLevel@23@PBDH@Z) referenced in function "public: void __thiscall google::protobuf::internal::RepeatedPtrFieldBase::Clear<class google::protobuf::RepeatedPtrField<class ImageCategoryPB>::TypeHandler>(void)" (??$Clear@VTypeHandler@?$RepeatedPtrField@VImageCategoryPB@@@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@QAEXXZ)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "public: __thiscall google::protobuf::internal::LogMessage::~LogMessage(void)" (??1LogMessage@internal@protobuf@google@@QAE@XZ) referenced in function "public: void __thiscall google::protobuf::internal::RepeatedPtrFieldBase::Clear<class google::protobuf::RepeatedPtrField<class ImageCategoryPB>::TypeHandler>(void)" (??$Clear@VTypeHandler@?$RepeatedPtrField@VImageCategoryPB@@@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@QAEXXZ)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "public: class google::protobuf::internal::LogMessage & __thiscall google::protobuf::internal::LogMessage::operator<<(char const *)" (??6LogMessage@internal@protobuf@google@@QAEAAV0123@PBD@Z) referenced in function "public: void __thiscall google::protobuf::internal::RepeatedPtrFieldBase::Clear<class google::protobuf::RepeatedPtrField<class ImageCategoryPB>::TypeHandler>(void)" (??$Clear@VTypeHandler@?$RepeatedPtrField@VImageCategoryPB@@@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@QAEXXZ)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "public: void __thiscall google::protobuf::internal::LogFinisher::operator=(class google::protobuf::internal::LogMessage &)" (??4LogFinisher@internal@protobuf@google@@QAEXAAVLogMessage@123@@Z) referenced in function "public: void __thiscall google::protobuf::internal::RepeatedPtrFieldBase::Clear<class google::protobuf::RepeatedPtrField<class ImageCategoryPB>::TypeHandler>(void)" (??$Clear@VTypeHandler@?$RepeatedPtrField@VImageCategoryPB@@@protobuf@google@@@RepeatedPtrFieldBase@internal@protobuf@google@@QAEXXZ)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "void __cdecl google::protobuf::internal::VerifyVersion(int,int,char const *)" (?VerifyVersion@internal@protobuf@google@@YAXHHPBD@Z) referenced in function "void __cdecl protobuf_ProtocolBufferTransitEvent_2eproto::InitDefaultsLaneMessagePB(void)" (?InitDefaultsLaneMessagePB@protobuf_ProtocolBufferTransitEvent_2eproto@@YAXXZ)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "void __cdecl google::protobuf::internal::OnShutdownRun(void (__cdecl*)(void const *),void const *)" (?OnShutdownRun@internal@protobuf@google@@YAXP6AXPBX@Z0@Z) referenced in function "void __cdecl google::protobuf::internal::OnShutdownDestroyMessage(void const *)" (?OnShutdownDestroyMessage@internal@protobuf@google@@YAXPBX@Z)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "public: struct std::pair<int,int> __thiscall google::protobuf::io::CodedInputStream::IncrementRecursionDepthAndPushLimit(int)" (?IncrementRecursionDepthAndPushLimit@CodedInputStream@io@protobuf@google@@QAE?AU?$pair@HH@std@@H@Z) referenced in function "public: static bool __cdecl google::protobuf::internal::WireFormatLite::ReadMessage<class AddressPB>(class google::protobuf::io::CodedInputStream *,class AddressPB *)" (??$ReadMessage@VAddressPB@@@WireFormatLite@internal@protobuf@google@@SA_NPAVCodedInputStream@io@23@PAVAddressPB@@@Z)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "public: bool __thiscall google::protobuf::io::CodedInputStream::DecrementRecursionDepthAndPopLimit(int)" (?DecrementRecursionDepthAndPopLimit@CodedInputStream@io@protobuf@google@@QAE_NH@Z) referenced in function "public: static bool __cdecl google::protobuf::internal::WireFormatLite::ReadMessage<class AddressPB>(class google::protobuf::io::CodedInputStream *,class AddressPB *)" (??$ReadMessage@VAddressPB@@@WireFormatLite@internal@protobuf@google@@SA_NPAVCodedInputStream@io@23@PAVAddressPB@@@Z)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "private: __int64 __thiscall google::protobuf::io::CodedInputStream::ReadVarint32Fallback(unsigned int)" (?ReadVarint32Fallback@CodedInputStream@io@protobuf@google@@AAE_JI@Z) referenced in function "public: bool __thiscall google::protobuf::io::CodedInputStream::ReadVarint32(unsigned int *)" (?ReadVarint32@CodedInputStream@io@protobuf@google@@QAE_NPAI@Z)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "private: int __thiscall google::protobuf::io::CodedInputStream::ReadVarintSizeAsIntFallback(void)" (?ReadVarintSizeAsIntFallback@CodedInputStream@io@protobuf@google@@AAEHXZ) referenced in function "public: bool __thiscall google::protobuf::io::CodedInputStream::ReadVarintSizeAsInt(int *)" (?ReadVarintSizeAsInt@CodedInputStream@io@protobuf@google@@QAE_NPAH@Z)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "private: unsigned int __thiscall google::protobuf::io::CodedInputStream::ReadTagFallback(unsigned int)" (?ReadTagFallback@CodedInputStream@io@protobuf@google@@AAEII@Z) referenced in function "public: struct std::pair<unsigned int,bool> __thiscall google::protobuf::io::CodedInputStream::ReadTagWithCutoffNoLastTag(unsigned int)" (?ReadTagWithCutoffNoLastTag@CodedInputStream@io@protobuf@google@@QAE?AU?$pair@I_N@std@@I@Z)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "public: static unsigned char * __cdecl google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char *)" (?WriteStringWithSizeToArray@CodedOutputStream@io@protobuf@google@@SAPAEABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAE@Z) referenced in function "public: static unsigned char * __cdecl google::protobuf::internal::WireFormatLite::WriteStringToArray(int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char *)" (?WriteStringToArray@WireFormatLite@internal@protobuf@google@@SAPAEHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAE@Z)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "public: void * __thiscall google::protobuf::internal::ArenaImpl::AllocateAligned(unsigned int)" (?AllocateAligned@ArenaImpl@internal@protobuf@google@@QAEPAXI@Z) referenced in function "private: void * __thiscall google::protobuf::Arena::AllocateInternal<struct google::protobuf::internal::InternalMetadataWithArenaBase<class google::protobuf::UnknownFieldSet,class google::protobuf::internal::InternalMetadataWithArena>::Container>(bool)" (??$AllocateInternal@UContainer@?$InternalMetadataWithArenaBase@VUnknownFieldSet@protobuf@google@@VInternalMetadataWithArena@internal@23@@internal@protobuf@google@@@Arena@protobuf@google@@AAEPAX_N@Z)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "public: void * __thiscall google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned int,void (__cdecl*)(void *))" (?AllocateAlignedAndAddCleanup@ArenaImpl@internal@protobuf@google@@QAEPAXIP6AXPAX@Z@Z) referenced in function "private: void * __thiscall google::protobuf::Arena::AllocateInternal<struct google::protobuf::internal::InternalMetadataWithArenaBase<class google::protobuf::UnknownFieldSet,class google::protobuf::internal::InternalMetadataWithArena>::Container>(bool)" (??$AllocateInternal@UContainer@?$InternalMetadataWithArenaBase@VUnknownFieldSet@protobuf@google@@VInternalMetadataWithArena@internal@23@@internal@protobuf@google@@@Arena@protobuf@google@@AAEPAX_N@Z)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "public: void __thiscall google::protobuf::internal::ArenaImpl::AddCleanup(void *,void (__cdecl*)(void *))" (?AddCleanup@ArenaImpl@internal@protobuf@google@@QAEXPAXP6AX0@Z@Z) referenced in function "private: void __thiscall google::protobuf::Arena::OwnInternal<class google::protobuf::Message>(class google::protobuf::Message *,struct std::integral_constant<bool,1>)" (??$OwnInternal@VMessage@protobuf@google@@@Arena@protobuf@google@@AAEXPAVMessage@12@U?$integral_constant@_N$00@std@@@Z)
1>FSRiteTrxDlg.obj : error LNK2019: unresolved external symbol "private: void __thiscall google::protobuf::Arena::OnArenaAllocation(class type_info const *,unsigned int)const " (?OnArenaAllocation@Arena@protobuf@google@@ABEXPBVtype_info@@I@Z) referenced in function "private: void __thiscall google::protobuf::Arena::AllocHook(class type_info const *,unsigned int)const " (?AllocHook@Arena@protobuf@google@@ABEXPBVtype_info@@I@Z)
1>FSRiteTrxDlg.obj : error LNK2001: unresolved external symbol "public: virtual class google::protobuf::MessageLite * __thiscall google::protobuf::MessageLite::New(class google::protobuf::Arena *)const " (?New@MessageLite@protobuf@google@@UBEPAV123@PAVArena@23@@Z)
1>FSRiteTrxDlg.obj : error LNK2001: unresolved external symbol "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall google::protobuf::MessageLite::InitializationErrorString(void)const " (?InitializationErrorString@MessageLite@protobuf@google@@UBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
1>FSRiteTrxDlg.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall google::protobuf::MessageLite::SerializeWithCachedSizes(class google::protobuf::io::CodedOutputStream *)const " (?SerializeWithCachedSizes@MessageLite@protobuf@google@@UBEXPAVCodedOutputStream@io@23@@Z)
1>FSRiteTrxDlg.obj : error LNK2001: unresolved external symbol "public: virtual unsigned char * __thiscall google::protobuf::MessageLite::SerializeWithCachedSizesToArray(unsigned char *)const " (?SerializeWithCachedSizesToArray@MessageLite@protobuf@google@@UBEPAEPAE@Z)
1>FSRiteTrxDlg.obj : error LNK2001: unresolved external symbol "public: virtual unsigned char * __thiscall google::protobuf::MessageLite::InternalSerializeWithCachedSizesToArray(bool,unsigned char *)const " (?InternalSerializeWithCachedSizesToArray@MessageLite@protobuf@google@@UBEPAE_NPAE@Z)


When I start with the project that has protocol buffer linked and add the librdkafka static libraries with the openssl static libraries I get the following messages:
1>librdkafka.lib(rdkafka_conf.obj) : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/SAFESEH' specification
1>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
1>librdkafka.lib(rdkafka_assignor.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_request.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_msgset_writer.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_broker.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdbuf.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_msg.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_buf.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_msgset_writer.obj) : error LNK2019: unresolved external symbol _deflate referenced in function _rd_kafka_msgset_writer_compress_gzip
1>librdkafka.lib(rdkafka_msgset_writer.obj) : error LNK2019: unresolved external symbol _deflateEnd referenced in function _rd_kafka_msgset_writer_compress_gzip
1>librdkafka.lib(rdkafka_msgset_writer.obj) : error LNK2019: unresolved external symbol _deflateBound referenced in function _rd_kafka_msgset_writer_compress_gzip
1>librdkafka.lib(rdkafka_msgset_writer.obj) : error LNK2019: unresolved external symbol _deflateInit2_ referenced in function _rd_kafka_msgset_writer_compress_gzip
1>librdkafka.lib(rdgz.obj) : error LNK2019: unresolved external symbol _inflate referenced in function _rd_gz_decompress
1>librdkafka.lib(rdgz.obj) : error LNK2019: unresolved external symbol _inflateEnd referenced in function _rd_gz_decompress
1>librdkafka.lib(rdgz.obj) : error LNK2019: unresolved external symbol _inflateGetHeader referenced in function _rd_gz_decompress
1>librdkafka.lib(rdgz.obj) : error LNK2019: unresolved external symbol _inflateInit2_ referenced in function _rd_gz_decompress
1>libcrypto32MTd.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __vsnwprintf referenced in function _OPENSSL_showfatal
1>libcrypto32MTd.lib(eng_openssl.obj) : error LNK2019: unresolved external symbol ___iob_func referenced in function _openssl_load_privkey
1>libcrypto32MTd.lib(e_capi.obj) : error LNK2001: unresolved external symbol ___iob_func
1>libcrypto32MTd.lib(ui_openssl.obj) : error LNK2001: unresolved external symbol ___iob_func
1>libcrypto32MTd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertOpenStore@20 referenced in function _capi_open_store
1>libcrypto32MTd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertCloseStore@8 referenced in function _capi_find_key
1>libcrypto32MTd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertEnumCertificatesInStore@8 referenced in function _capi_find_cert
1>libcrypto32MTd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertFindCertificateInStore@24 referenced in function _capi_find_cert
1>libcrypto32MTd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertDuplicateCertificateContext@4 referenced in function _capi_load_ssl_client_cert
1>libcrypto32MTd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertFreeCertificateContext@4 referenced in function _capi_find_key
1>libcrypto32MTd.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertGetCertificateContextProperty@16 referenced in function _capi_cert_get_fname
1>libcrypto32MTd.lib(v3_utl.obj) : error LNK2019: unresolved external symbol _sscanf referenced in function _ipv4_from_asc

**Comment by tgredfish** [comment]
I know there are a lot of variable things and moving parts I am asking and I am just trying to simplify things for a basic set of functionality...

**Comment by edenhill** [comment]
Are you using the librdkafka.redist nuget package, or building librdkafka yourself?
In the latter case you can make librdkafka link OpenSSL dynamically by changing the OpenSSL lib paths in `win32/librdkafka.vcxproj` from `C:\OpenSSL-Win64\lib\VC\static` to `C:\OpenSSL-Win64\lib\VC`.

**Comment by tgredfish** [comment]
I did build librdkafka myself as a static library.  I did install the nuget package in the project.  Stupid question but is there a way to undo that or better just to build a new project.

**Comment by tgredfish** [comment]
Also, I have VS2008, VS2013 and VS2017.   Which one is the easier one to use for trying to do this.  I didn't even try on 2013.  I thought 2008 encountered problems with some of the C11 things.

**Comment by edenhill** [comment]
I'd use 2013 or 2017, personally use 2015 myself.

Suggest you don't try to link statically since that may have issues with differing runtimes (v120, v140) between librdkafka, OpenSSL and libprotobuf.

**Comment by tgredfish** [comment]
to try dynamic linking of OpenSSL are there any other setting when compiling the librdkafka library which I have to build as static library.

**Comment by arena** [comment]
Please use markdown when you paste code with local variables to avoid @
mentioning github users.

**Comment by tgredfish** [comment]
First time posting, so I will try to figure out where markdown is before I paste more code.  Sorry.

**Comment by tgredfish** [comment]
I have attempted to  make librdkafka link OpenSSL dynamically by changing the OpenSSL lib paths in win32/librdkafka.vcxproj from C:\OpenSSL-Win64\lib\VC\static to C:\OpenSSL-Win64\lib\VC.  Is there a define I need to define to get the OpenSSL to link dynamically by using the right headers.  It still seems to behave the same way.  I must be missing a step.

**Comment by tgredfish** [comment]
I get the following messages when I do as you said above and include the C:\OpenSSL-Win32\lib\VC as an additional library directory and include libcrypto32MTd.lib and libssl32MTd.lib in the Additional Dependencies after librdkafka.lib


1>librdkafka.lib(rdkafka_conf.obj) : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/SAFESEH' specification
1>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
1>librdkafka.lib(rdkafka_assignor.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_request.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_msgset_writer.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_broker.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdbuf.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_msg.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_buf.obj) : error LNK2001: unresolved external symbol _crc32
1>librdkafka.lib(rdkafka_msgset_writer.obj) : error LNK2019: unresolved external symbol _deflate referenced in function _rd_kafka_msgset_writer_compress_gzip
1>librdkafka.lib(rdkafka_msgset_writer.obj) : error LNK2019: unresolved external symbol _deflateEnd referenced in function _rd_kafka_msgset_writer_compress_gzip
1>librdkafka.lib(rdkafka_msgset_writer.obj) : error LNK2019: unresolved external symbol _deflateBound referenced in function _rd_kafka_msgset_writer_compress_gzip
1>librdkafka.lib(rdkafka_msgset_writer.obj) : error LNK2019: unresolved external symbol _deflateInit2_ referenced in function _rd_kafka_msgset_writer_compress_gzip
1>librdkafka.lib(rdgz.obj) : error LNK2019: unresolved external symbol _inflate referenced in function _rd_gz_decompress
1>librdkafka.lib(rdgz.obj) : error LNK2019: unresolved external symbol _inflateEnd referenced in function _rd_gz_decompress
1>librdkafka.lib(rdgz.obj) : error LNK2019: unresolved external symbol _inflateGetHeader referenced in function _rd_gz_decompress
1>librdkafka.lib(rdgz.obj) : error LNK2019: unresolved external symbol _inflateInit2_ referenced in function _rd_gz_decompress
1>.\Debug/FSRiteTrx.exe : fatal error LNK1120: 9 unresolved externals

**Comment by edenhill** [comment]
Looks like you are not linking with zlib

**Comment by tgredfish** [comment]
Thank you.  I used nuget to install the zlib-msvc-x86 for VS2017 and that seem to link successfully.
