### ISSUE TITLE
"Receive failed: connection reset by peer" in producer

### ISSUE THREAD

**Issue by terrywh** [edenhill/librdkafka#2291]
Description
===========
Error messages freqently appear:
```
%3|1555892678.223|ERROR|rdkafka#producer-1| [thrd:yyy.yyy.yyy.yyy:19092/bootstrap]: yyy.yyy.yyy.yyy:19092/1: Receive failed: Connection reset by peer (after 600003ms in state UP)
%3|1555903768.283|ERROR|rdkafka#producer-1| [thrd:xxx.xxx.xxx.xxx:19092/bootstrap]: xxx.xxx.xxx.xxx:19092/3: Receive failed: Connection reset by peer (after 1045590ms in state UP)

```
How to reproduce
================
I'm not sure, seems to happen randomly.

Checklist
=========
librdkafka version: lastest( v1.0.0)
Apache Kafka version: kafka_2.12-0.11.0.2
librdkafka client configuration: 
```
bootstrap.servers: xxx.xxx.xxx.xxx:19092,yyy.yyy.yyy.yyy:19092,zzz.zzz.zzz.zzz:19092
log.connection.close: false
```

**Comment by edenhill** [comment]
That looks like the broker's idle connection reaper kicking in, see https://github.com/edenhill/librdkafka/wiki/FAQ#why-am-i-seeing-receive-failed-disconnected

**Comment by terrywh** [comment]
i was told setting "log.connection.close: false" will prevent that kind of info from showing up ?

**Comment by edenhill** [comment]
What OS is this on?

**Comment by terrywh** [comment]
CentOS v7.6

**Comment by edenhill** [comment]
Seems like we might get a ECONNRESET error back from recvmsg(), rather than 0, on connection close.
Will make sure it is handled like a normal disconnect.

**Comment by edenhill** [comment]
I don't think we need to differentiate between a clean socket close and a forced one (ECONNRESET).
