### ISSUE TITLE
Question: does producer retries a message to same partition?

### ISSUE THREAD

**Issue by my3** [edenhill/librdkafka#2295]
When msg delivery failed and lib retries, does the library try to send the msg to the same partition during all those attempts or does it try a different partition?

**Comment by my3** [comment]
max.in.flight.requests.per.connection=1
linger.ms=30
message.send.max.retries=5
retry.backoff.ms=10
retries=5
delivery.timeout.ms=10000
compression.type=snappy

Others should be default. For ex: enable.idempotence=false

**Comment by edenhill** [comment]
Messages are only partitioned once, they will not change partitions.
So, future retries will be on the same partition.
