### ISSUE TITLE
Question about connections on windows

### ISSUE THREAD

**Issue by MoJI4yH** [edenhill/librdkafka#2297]
Description
===========
It seems an incorrect shutdown of the socket on windows.

How to reproduce
================
Run 10 consumers for topic with 10 partitions.
As Result (connections on win10)
![kafka_connections_windows](https://user-images.githubusercontent.com/5322898/56723429-9ddc8e80-6751-11e9-8a7a-57a99f5fa5aa.png)

we have 20 connections to broker and thats OK, but also **50 connections with Bound State** and 60 Established connections on localhost

I try run the same code on MacOX
As Result (connections on macox)
<img width="857" alt="kafka_connections_macox" src="https://user-images.githubusercontent.com/5322898/56723471-b0ef5e80-6751-11e9-9175-577d18de7e9c.png">
we have 20 connections to broker and thats OK, and also 2 Established connections on localhost and thats OK too.

So the question is: "Is it possible that these **50 bound state** sockets were closed incorrectly?" 

=========

Please provide the following information:
 - [x] librdkafka version: `1.0.0, 0.11.6`
 - [x] Apache Kafka version: ` 2.1.1, 1.1.0`
 - [x] librdkafka client configuration: set bootstrap.servers and groupid, other by default`
 - [x] Operating system: win10 (x64), windows server 2016 (x64)

**Comment by edenhill** [comment]
On Windows, librdkafka uses internal TCP connections on 127.0.0.1 to trigger its background broker threads. Those are probably the ones you are seeing.
