### ISSUE TITLE
auto-poll

### ISSUE THREAD

**Issue by DEvil0000** [edenhill/librdkafka#230]
I realised dr_cb is not called after delivery (what i was expecting).
It is called some time later on the next bulk delivery action. This might be pretty late and you might "miss" a dr_cb for the last bulk message produce.

Test Example:
- produce 3 messages (A) (will get written to rdkafka internal queue)
- rdkafka will now transmit them in bulk to kafka broker
- wait some seconds (I used 10)
- start new consumer (offset start at end of topic)
- wait some seconds (I used 10)
- check: consumer was not consuming something because offset is at the end of topic (ok)
- produce 3 messages (B) (will get written to rdkafka internal queue)
- BUG/TAKE A LOOK HERE: now I receive the acc/callback for the 3 first messages (A)
- rdkafka will now transmit them in bulk to kafka broker
- check: consumer received 3 messages (B) (ok)
- wait some seconds (I used 10)
- 'trigger' shutdown
- STRANGE/TAKE A LOOK HERE: now I receive the acc/callback for the 3 last messages (B)

I consider this a bug: I get the dr_cb only when producing the next message (set). Not when they are produced with success.
And because of this and as kind of a bad fix I get the last messages acc callback on shutdown.

update:
Do I need/miss a poll call?
After produce i call poll(0)
should the rdkafka library hide this and call it from time to time?

**Comment by edenhill** [comment]
You need to poll continually.
If you do something like:
````
   produce();
   poll(0);
````
then there aren't many cycles between the produce and poll and it is highly unlikely (impossible, almost) that the message has been sent to the broker and the broker has sent an ack back, causing the dr_cb to be enqueued.
In such an approach any previous message's dr_cbs will be triggered by that poll, but no the latest one.
Depending on the application this might be okay (e.-g., the application expects a steady stream of messages to produce), for other applications that needs to know the delivery status as soon as possible I suggest creating a separate thread that only does something like:
````
 while (run)
   rd_kafka_poll(rk, 1000);
````

**Comment by DEvil0000** [comment]
thanks.
why is the lib not abstracting the poll mecanism away from the user?
you could do polls in the lib and configure them with the config - right?

**Comment by edenhill** [comment]
The main reason is thread safety, providing an auto-poll from an internal rdkafka thread would
trick application developers into thinking they do not need to think about thread safety and this
would lead to buggy applications with hard to troubleshoot errors.

Forcing developers to make elaborate decisions on their threading model alleviates this problem.

Having said that I do agree it would be convenient for an auto-poll option, but it will need to
be marked with large warning signs.

**Comment by rathdeep** [comment]
One question regarding delivery reports. If i publish Messages 1, 2,3,4,5 in this order. Is it guaranteed that delivery reports will also have same order.

**Comment by trink** [comment]
Instead of auto poll why not just invoke the callbacks directly as expected (+1 for thread safety doc warnings)?  Something like this (only implemented for delivery reports here) https://github.com/edenhill/librdkafka/compare/master...trink:dr_no_poll?expand=1
