### ISSUE TITLE
how to use RdKafka::Queue

### ISSUE THREAD

**Issue by smartdu** [edenhill/librdkafka#2302]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I use Queue, the code is as follows, the message is not consumed

```
#include <stdio.h>
#include <string>
#include <vector>
#include "rdkafka.h"
#include "rdkafkacpp.h"
using namespace RdKafka;

class A
: public RebalanceCb
, public OffsetCommitCb
, public EventCb
{
public:
        void rebalance_cb(RdKafka::KafkaConsumer *consumer, RdKafka::ErrorCode err, std::vector<TopicPartition*>&partitions)
        {
        }

        void offset_commit_cb(RdKafka::ErrorCode err, std::vector<TopicPartition*>&offsets)
        {

        }

        void event_cb(Event &event)
        {

        }
};

KafkaConsumer* create_consumer(const char *topic)
{
        Conf::ConfResult result;
        std::string errstr;

        std::string topic_ = topic;
        int offset_flag_ = Topic::OFFSET_END;
        std::string brokers_ = "kafka-hs.default.svc.cluster.local:9093";
        std::string consumer_group_ = "test";

        A *a = new A;

        RdKafka::Conf *global_consumer_conf_ = Conf::create(Conf::CONF_GLOBAL);
        result = global_consumer_conf_->set("bootstrap.servers", brokers_, errstr);
        result = global_consumer_conf_->set("group.id", consumer_group_, errstr);
        result = global_consumer_conf_->set("rebalance_cb", (RebalanceCb*)a, errstr);
        result = global_consumer_conf_->set("offset_commit_cb", (OffsetCommitCb*)a, errstr);
        result = global_consumer_conf_->set("event_cb", (EventCb*)a, errstr);
        result = global_consumer_conf_->set("fetch.wait.max.ms", "10", errstr);
        result = global_consumer_conf_->set("session.timeout.ms", "30000", errstr);
        result = global_consumer_conf_->set("fetch.error.backoff.ms", "100", errstr);
        result = global_consumer_conf_->set("debug", "generic,broker,metadata,security,interceptor,plugin,admin,fetch", errstr);
        //result = global_consumer_conf_->set("statistics.interval.ms", "30000", errstr);

        RdKafka::Conf *consumer_conf_ = Conf::create(Conf::CONF_TOPIC);
        result = global_consumer_conf_->set("default_topic_conf", consumer_conf_, errstr);

        KafkaConsumer *kc_ = KafkaConsumer::create(global_consumer_conf_, errstr);

        TopicPartition *tp_ = TopicPartition::create(topic_.c_str(), 0, offset_flag_);
        std::vector<TopicPartition*> tps;
        tps.push_back(tp_);
        kc_->assign(tps);

        return kc_;
}

int main()
{
        KafkaConsumer *kc1_ = create_consumer("VMS-SP");
        KafkaConsumer *kc2_ = create_consumer("VMS");

        Queue *q1_ = Queue::create(kc1_);
        Queue *q2_ = Queue::create(kc2_);

        q1_->forward(q2_);
        while (true)
        {
                q1_->poll(10);
                Message *msg = q1_->consume(10);
                if (msg != NULL && msg->err() == RD_KAFKA_RESP_ERR_NO_ERROR && msg->len() > 0)
                {
                        printf("%.*s\n", msg->len(), (const char*)msg->payload());
                }
                else
                {
                        delete msg;
                }

        }


        while (true)
        {
                Message *msg = kc1_->consume(10);
                if (msg != NULL && msg->err() == RD_KAFKA_RESP_ERR_NO_ERROR && msg->len() > 0)
                {
                        printf("%.*s\n", msg->len(), (const char*)msg->payload());
                }
                else
                {
                        delete msg;
                }

                msg = kc2_->consume(10);
                if (msg != NULL && msg->err() == RD_KAFKA_RESP_ERR_NO_ERROR && msg->len() > 0)
                {
                        printf("%.*s\n", msg->len(), (const char*)msg->payload());
                }
                else
                {
                        delete msg;
                }
        }
}
```

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.0.0`
 - [ ] Apache Kafka version: `kafka_2.11-1.1.0`
 - [ ] librdkafka client configuration: `fetch.wait.max.ms=10;session.timeout.ms=30000;fetch.error.backoff.ms=100;debug=generic,broker,metadata,security,interceptor,plugin,admin,fetch`
 - [ ] Operating system: `CentOS-x64 7`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by smartdu** [comment]
`
#include <stdio.h>
#include <string>
#include <vector>
#include "rdkafka.h"
#include "rdkafkacpp.h"
using namespace RdKafka;

class A
: public RebalanceCb
, public OffsetCommitCb
, public EventCb
{
public:
        void rebalance_cb(RdKafka::KafkaConsumer *consumer, RdKafka::ErrorCode err, std::vector<TopicPartition*>&partitions)
        {
        }

        void offset_commit_cb(RdKafka::ErrorCode err, std::vector<TopicPartition*>&offsets)
        {

        }

        void event_cb(Event &event)
        {

        }
};

KafkaConsumer* create_consumer(const char *topic)
{
        Conf::ConfResult result;
        std::string errstr;

        std::string topic_ = topic;
        int offset_flag_ = Topic::OFFSET_END;
        std::string brokers_ = "kafka-hs.default.svc.cluster.local:9093";
        std::string consumer_group_ = "test";

        A *a = new A;

        RdKafka::Conf *global_consumer_conf_ = Conf::create(Conf::CONF_GLOBAL);
        result = global_consumer_conf_->set("bootstrap.servers", brokers_, errstr);
        result = global_consumer_conf_->set("group.id", consumer_group_, errstr);
        result = global_consumer_conf_->set("rebalance_cb", (RebalanceCb*)a, errstr);
        result = global_consumer_conf_->set("offset_commit_cb", (OffsetCommitCb*)a, errstr);
        result = global_consumer_conf_->set("event_cb", (EventCb*)a, errstr);
        result = global_consumer_conf_->set("fetch.wait.max.ms", "10", errstr);
        result = global_consumer_conf_->set("session.timeout.ms", "30000", errstr);
        result = global_consumer_conf_->set("fetch.error.backoff.ms", "100", errstr);
        result = global_consumer_conf_->set("debug", "generic,broker,metadata,security,interceptor,plugin,admin,fetch", errstr);
        //result = global_consumer_conf_->set("statistics.interval.ms", "30000", errstr);

        RdKafka::Conf *consumer_conf_ = Conf::create(Conf::CONF_TOPIC);
        result = global_consumer_conf_->set("default_topic_conf", consumer_conf_, errstr);

        KafkaConsumer *kc_ = KafkaConsumer::create(global_consumer_conf_, errstr);

        TopicPartition *tp_ = TopicPartition::create(topic_.c_str(), 0, offset_flag_);
        std::vector<TopicPartition*> tps;
        tps.push_back(tp_);
        kc_->assign(tps);

        return kc_;
}

int main()
{
        KafkaConsumer *kc1_ = create_consumer("VMS-SP");
        KafkaConsumer *kc2_ = create_consumer("VMS");

        Queue *q1_ = Queue::create(kc1_);
        Queue *q2_ = Queue::create(kc2_);

        q1_->forward(q2_);
        while (true)
        {
                q1_->poll(10);
                Message *msg = q1_->consume(10);
                if (msg != NULL && msg->err() == RD_KAFKA_RESP_ERR_NO_ERROR && msg->len() > 0)
                {
                        printf("%.*s\n", msg->len(), (const char*)msg->payload());
                }
                else
                {
                        delete msg;
                }

        }


        while (true)
        {
                Message *msg = kc1_->consume(10);
                if (msg != NULL && msg->err() == RD_KAFKA_RESP_ERR_NO_ERROR && msg->len() > 0)
                {
                        printf("%.*s\n", msg->len(), (const char*)msg->payload());
                }
                else
                {
                        delete msg;
                }

                msg = kc2_->consume(10);
                if (msg != NULL && msg->err() == RD_KAFKA_RESP_ERR_NO_ERROR && msg->len() > 0)
                {
                        printf("%.*s\n", msg->len(), (const char*)msg->payload());
                }
                else
                {
                        delete msg;
                }
        }
}
`

**Comment by edenhill** [comment]
You're registering a rebalance_cb but you don't call assign() from it, see the docs here:
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L732

**Comment by smartdu** [comment]
Can't assign method use Queue?

**Comment by edenhill** [comment]
Oh sorry, didnt see your assign() call, it works.

I see that you are creating two consumers to read two topics, unless the consumers need different config I suggest you use a single consumer and pass the two topics in the single assign() call instead, since it will be more effective for a single consumer to fetch multiple topics than the other way around.


The reason you are not seeing any messages is that you are creating a queue but it is not associated with anything, the fetched messages will still go on the consumer queue.

The queue interface in C++ does not currently expose the consumer queue, so it can't be forwarded,  but you can redirect specific partition queues to your own queues by getting the partition queue with `get_partition_queue()` and then forwarding that queue to your queue with `part_queue->forward(your_queue)`.

Do note that any callbacks you have registered will still go on the main consumer queue, so you will still need to call consume() to serve those events.

**Comment by smartdu** [comment]
Thank you very much for your answer. @edenhill
