### ISSUE TITLE
Question about config options on AdminClient

### ISSUE THREAD

**Issue by gavinmcnair** [edenhill/librdkafka#2303]
I noticed that you have implemented the ability to create topics using the AdminClient API.

In order to auto provision topics i need to be able to set the config options

   * cleanup.policy=compact
   * min.insync.replicas
   * etc

The examples I can find don't seem to do this. Can it currently be done via the AdminClient API?

**Comment by edenhill** [comment]
Use rd_kafka_NewTopic_set_config() to set topic configuration properties on the new topic.

https://github.com/edenhill/librdkafka/blob/master/tests/0081-admin.c#L104

**Comment by gavinmcnair** [comment]
Thanks for the information.
