### ISSUE TITLE
Question: auto.commit.enable (legacy)

### ISSUE THREAD

**Issue by nick-zh** [edenhill/librdkafka#2304]
Just to be sure, does the deprecation of this config for the legacy consumer (topic) mean, that i always have to explicitly store my offsets, there is no auto mechanism anymore?
Thanks in advance for answering.

Cheers,
Nick

**Comment by edenhill** [comment]
auto.commit.enable is no longer in use. You should use enable.auto.commit.
But both of these options have the default of true, so auto commits have and are still enabled by default.

**Comment by nick-zh** [comment]
Many thanks!
