### ISSUE TITLE
Implement C application Kerberos on Solaris 10 

### ISSUE THREAD

**Issue by roblos** [edenhill/librdkafka#2308]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have already a producer and consumer working on Solaris 10. Both C applications.
The next step is to use Kerberos. How to implement this ? Is there some example code ?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): librdkafka-0.11.6
 - [ ] Operating system: `Solaris 10, 64 bit`

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka
