### ISSUE TITLE
Question/Improvement: connected/connection lost event callback (c++)

### ISSUE THREAD

**Issue by DEvil0000** [edenhill/librdkafka#231]
I am trying to use event_cb and a check for ERR__ALL_BROKERS_DOWN to detect connection lost.
Is there something similar to get informed when I get a broker connection or a broker returns?

Background:
When I lose connection/cat not produce to the broker anymore I want to stop producing to the internal rdkafka produce queue and I want to stop some consumers.

Possible improvements:
* configuration value for stop producer/consumer on kafka down.
* a callback for connection fine/connection lost

**Comment by edenhill** [comment]
What you probably want is a per topic&partition operative state, issue #137 touches on this,
but it is not yet implemented.

**Comment by DEvil0000** [comment]
yes, this is what i want.
But with an additional config value "stop producer/consumer on down". This way produce should fail when the thing is down and the internal produce queue will not grow anymore.

**Comment by edenhill** [comment]
Are you sure you want that? That means that any small hick-up in broker connectivity will prevent you from producing messages, putting the burden on your application to perform retries, etc.
Instead let librdkafka handle that for you and give it a time frame for how long it may try to deliver a message (message.timeout.ms).

**Comment by DEvil0000** [comment]
I am not sure about my attempt. Take a look:
* Loosing messages would be a problem. But better loosing one instead of some more.
* I can not guarantee bugfree/crashfree code. (who can?)
* Holding messages in RAM may lead to 'out of memory' pretty fast. -> crash -> data loss
* rdkafkas internal queue is not persistent.
This is why I was thinking about persisting messages local until produce worked.
Option A:
Save all messages before produce and delete them on successful produce.
- super save but much I/O
Option B:
Save all messages on failed produce and dr_cb returning error.
- just a small part of messages may get lost and SSD is only used on broker down.

Do i miss something?

**Comment by edenhill** [comment]
If you are worried about application crashes I think Option A is the best, and that should be fairly simple.
There are plans to provide persistance in librdkafka, issue #31.

**Comment by edenhill** [comment]
See #137
