### ISSUE TITLE
KafkaConsumer cannot consume equally

### ISSUE THREAD

**Issue by eelyaj** [edenhill/librdkafka#2312]
I got a topic which has 60 partitions, in my consumer application, I calculate message number for each partition and print result every 30 second.
I found some partitions always consume more messages than others. the result is like this:
p_x means partition x, the number is messages received in 30 seconds

p_0: 73543
p_1: 61643
p_2: 157930
p_3: 67383
p_4: 55653
p_5: 151808
p_6: 67073
p_7: 55436
p_8: 151326
p_9: 68022
p_10: 55690
p_11: 151194
p_12: 67546
p_13: 55547
p_14: 151795
p_15: 67326
p_16: 55554
p_17: 151823
p_18: 67205
p_19: 55337
p_20: 151395
p_21: 67759
p_22: 55491
p_23: 151030
p_24: 67457
p_25: 55640
p_26: 151879
p_27: 67193
p_28: 55487
p_29: 151872
p_30: 67088
p_31: 55497
p_32: 151555
p_33: 67814
p_34: 55581
p_35: 151060
p_36: 67678
p_37: 55999
p_38: 152062
p_39: 67349
p_40: 56280
p_41: 152045
p_42: 67391
p_43: 55643
p_44: 145294
p_45: 67797
p_46: 55331
p_47: 142939
p_48: 67776
p_49: 55659
p_50: 145778
p_51: 67416
p_52: 55614
p_53: 145831
p_54: 67215
p_55: 55567
p_56: 145648
p_57: 67853
p_58: 55668
p_59: 145177

consume parameters:
            "group.id": "mbb_ufdr_prs",
            "auto.offset.reset": "earliest",
            "enable.auto.commit": "false",
            "enable.auto.offset.store": "false"

librdkafka version 0.11.6
Kafka 1.0.0
3 brokers

**Comment by edenhill** [comment]
Can you please give this a try on the latest version, v1.0.0?

**Comment by eelyaj** [comment]
v1.0.0 version has the same issue.
I changed the partition number from 60 to 55, still the same question.
It seems partition  2 / 5 / 8 / 11 / 14 /.... always consume more.

test 1:
p_0: 127982
p_1: 127757
p_2: 205646
p_3: 121658
p_4: 117273
p_5: 191522
p_6: 120639
p_7: 119948
p_8: 195201
p_9: 123356
p_10: 117125
p_11: 196597
p_12: 122082
p_13: 122496
p_14: 197175
p_15: 119077
p_16: 119301
p_17: 197678
p_18: 121989
p_19: 121404
p_20: 200537
p_21: 118299
p_22: 118274
p_23: 195674
p_24: 119708
p_25: 118874
p_26: 193034
p_27: 117558
p_28: 119411
p_29: 196355
p_30: 119707
p_31: 120791
p_32: 191438
p_33: 120886
p_34: 121343
p_35: 199285
p_36: 121241
p_37: 119162
p_38: 190110
p_39: 116884
p_40: 121278
p_41: 192499
p_42: 121776
p_43: 118011
p_44: 192951
p_45: 118757
p_46: 120374
p_47: 196173
p_48: 116314
p_49: 116186
p_50: 194508
p_51: 119639
p_52: 119751
p_53: 198259
p_54: 116506

test2:
p_0: 121423
p_1: 114644
p_2: 191006
p_3: 122718
p_4: 112853
p_5: 189918
p_6: 122512
p_7: 114983
p_8: 186569
p_9: 125005
p_10: 112382
p_11: 189034
p_12: 122983
p_13: 116537
p_14: 189337
p_15: 119635
p_16: 112885
p_17: 190816
p_18: 122987
p_19: 112338
p_20: 191230
p_21: 118640
p_22: 113327
p_23: 192812
p_24: 123882
p_25: 114108
p_26: 187051
p_27: 120240
p_28: 114872
p_29: 191723
p_30: 120568
p_31: 116037
p_32: 185638
p_33: 121141
p_34: 114106
p_35: 190782
p_36: 121731
p_37: 112195
p_38: 189612
p_39: 122376
p_40: 114379
p_41: 185666
p_42: 124252
p_43: 111818
p_44: 188449
p_45: 121194
p_46: 114890
p_47: 189153
p_48: 119069
p_49: 112168
p_50: 190484
p_51: 121951
p_52: 112380
p_53: 191459
p_54: 118764


partition  for each broker
Broker 1
(0,1,4,5,6,7,10,11,12,13,16,17,18,19,22,23,24,25,28,29,30,31,34,35,36,37,40,41,42,43,46,47,48,49,52,53,54)
Broker 2
(0,2,3,4,6,8,9,10,12,14,15,16,18,20,21,22,24,26,27,28,30,32,33,34,36,38,39,40,42,44,45,46,48,50,51,52,54)
Broker 3
(1,2,3,5,7,8,9,11,13,14,15,17,19,20,21,23,25,26,27,29,31,32,33,35,37,38,39,41,43,44,45,47,49,50,51,53)

**Comment by edenhill** [comment]
Are you reading old messages from these partitions, or are you reading new, constantly produced, messages?

**Comment by edenhill** [comment]
Also, are you changing the assignment, seeking, pausing, or otherwise altering the current state of the consumer during these tests?

**Comment by eelyaj** [comment]
The client reading old messages. First I produce messages for some minutes, then I stop the producer and run this consumer client. So the consumer is reading as more message as it can, the cpu rate is around 600% (8 vcpu).

**Comment by eelyaj** [comment]
I didn't change anything, The code is like this:

while (run)
    {

        currenttime = time(0);
        if (lasttime + 30 <= currenttime)
        {
            lasttime = currenttime;
            for (int i = 0; i <= 60; ++i)
            {
                if (count[i] > 0)
                {
                    LOG(INFO) << "p_" << i << ": " << count[i];
                    count[i] = 0;
                }
            }

            LOG(INFO) << "=======================================";
        }

        msg = consumer->consume(1000);
        switch (msg->err())
        {
        case RdKafka::ERR_NO_ERROR:
            addMetric(KAFKA_CONSUMER_METRIC_PROCESS_MESSAGE_NUMBER);
            count[msg->partition()]++;
            processor->process(msg, consumer);
            break;
        case RdKafka::ERR__TIMED_OUT:
            addMetric(KAFKA_CONSUMER_METRIC_TIMED_OUT_NUMBER);
            processor->process(msg, consumer);
            usleep(1000);
            break;
        case RdKafka::ERR__PARTITION_EOF:
            addMetric(KAFKA_CONSUMER_METRIC_PARTITION_EOF_NUMBER);
            processor->process(msg, consumer);
            usleep(1000);
            break;

**Comment by champtar** [comment]
Maybe same bug as https://github.com/edenhill/librdkafka/issues/1395

**Comment by eelyaj** [comment]
> Maybe same bug as #1395

Yes, it seems the same issue. It still happens in latest version.
Any workaround?

**Comment by eelyaj** [comment]
interesting..  I found that partitions which consume more message are from the same broker.

180:9092/3: Fetch topic mbb_ufdr [17] at offset 118974974 (v2)
180:9092/3: Fetch topic mbb_ufdr [20] at offset 120407639 (v2)
180:9092/3: Fetch topic mbb_ufdr [23] at offset 118020892 (v2)
180:9092/3: Fetch topic mbb_ufdr [26] at offset 115531604 (v2)
180:9092/3: Fetch topic mbb_ufdr [29] at offset 117985549 (v2)
180:9092/3: Fetch topic mbb_ufdr [32] at offset 114212297 (v2)
180:9092/3: Fetch topic mbb_ufdr [35] at offset 117890820 (v2)
180:9092/3: Fetch topic mbb_ufdr [38] at offset 116514447 (v2)
180:9092/3: Fetch topic mbb_ufdr [41] at offset 116018029 (v2)
180:9092/3: Fetch topic mbb_ufdr [44] at offset 116527307 (v2)
180:9092/3: Fetch topic mbb_ufdr [47] at offset 117448644 (v2)
180:9092/3: Fetch topic mbb_ufdr [50] at offset 117353783 (v2)
180:9092/3: Fetch topic mbb_ufdr [53] at offset 118660688 (v2)
180:9092/3: Fetch topic mbb_ufdr [2] at offset 117900550 (v2) 
180:9092/3: Fetch topic mbb_ufdr [5] at offset 116594436 (v2) 
180:9092/3: Fetch topic mbb_ufdr [8] at offset 116056919 (v2) 
180:9092/3: Fetch topic mbb_ufdr [11] at offset 118172728 (v2)
180:9092/3: Fetch topic mbb_ufdr [14] at offset 119209116 (v2)
180:9092/3: Fetch 18/18/18 toppar(s)

**Comment by edenhill** [comment]
Maybe that broker's connectivity is faster, or has less load?
Or are fewer partitions fetched from that broker opposed to other brokers?

**Comment by eelyaj** [comment]
It sounds reasonable that a faster connectivity cause a faster consuming.
But it is very difficult to implement a time-based calculating application under such network circumstances.

Can I use both RdKafka::KafkaConsumer and RdKafka::Consumer.
That means, I use the KafkaConsumer to re-balance partitions in the same group id, and use Consumer to fetch certain number of message in each partition.

**Comment by edenhill** [comment]
That sounds complex and error-prone.

Here's an alternative:
Each fetched partition has its own queue of fetched messages, when this queue size reaches `queued.min.messages` or `queued.max.messages.kbytes` the fetcher will stop fetching that partition until the queue drops below those thresholds.
When using the KafkaConsumer the partition queues are forwarded to a single queue that, so that you can read message from all partitions by calling consume() in a single place.
With the queues forwarded the queue thresholds are no longer checked per partition, but for the common queue, which means that all partitions stop fetching when the common queue size thresholds are exceeded.

To solve your problem you can remove the forwarding of the partition queues so that each partition queue is checked individually against the size thresholds, this will generate a more balanced partition queue load since each partition will be fetched up to the same threshold, instead of a few partitions taking up much of that space.

So, for each assigned partition, use get_partition_queue() to get the partition's queue, then call forward(NULL) on that queue to disable forwarding.
Then poll each queue separately.
Do note that you still need to call consume() to serve rebalance events, but it will not return any messages now.

Also make sure to adjust `queued.min.messages` and `queued.max.messages.kbytes` to limit the number of messages and bytes, since these are now applied per partition rather than globally.

**Comment by eelyaj** [comment]
Thanks very much. Now I get all partitions in rebalance_cb callback function, and get the queue of each partition, call forward(NULL).
In the main thread, I call each queue->consume() to get message, and also I need to call consumer->consume() to trigger rebalance_cb. Is that right?
A little bit confuse, when should I call queue->poll()?

**Comment by edenhill** [comment]
That's right.
You don't need to call queue->poll(), queue->consume() is sufficient.
They are just two interfaces over the same internal queue, consume() returns messages and triggers callbacks, while poll() only triggers callbacks.

**Comment by eelyaj** [comment]
OK, Is there any side effect? In this separately queue mode, can I still use consumer->commitSync() to commit offset of each partition. And after re-balance, could each partition gets its last-committed-offset automatically?

**Comment by edenhill** [comment]
That functionality should work as usual, yes.

**Comment by champtar** [comment]
@edenhill In my bug I had 3 identical vms on the same host, and still not consuming at the same speed
Would it make sense to have an option to use separate queue to have better fairness (but without changing each app)(feature request) ?

**Comment by edenhill** [comment]
Yes, the long term plan is to optionally enforce the queue limits per partition, but this will not happen in the short term since it is somewhat of a niche problem.

**Comment by eelyaj** [comment]
Finally... I made it. 
@edenhill Thank you so much.

I use while(1) to consume each queue. I found that if I set timeout larger than 0, it will slow down when some partition reach to the end . some like this: 

            msg = q->consume(0);

            switch (msg->err())
            {
            case RdKafka::ERR_NO_ERROR:



p_0: 110280
p_1: 110167
p_2: 110167
p_3: 110167
p_4: 110167
p_5: 110167
p_6: 110167
p_7: 110167
p_8: 110167
p_9: 110167
p_10: 110167
p_11: 110167
p_12: 110167
p_13: 110167
p_14: 110167
p_15: 110167
p_16: 110167
p_17: 110167
p_18: 110167
p_19: 110167
p_20: 110167
p_21: 110167
p_22: 110167
p_23: 110167
p_24: 110167
p_25: 110167
p_26: 110167
p_27: 110167
p_28: 110167
p_29: 110167
p_30: 110167
p_31: 110167
p_32: 110167
p_33: 110167
p_34: 110167
p_35: 110167
p_36: 110167
p_37: 110167
p_38: 110167
p_39: 110167
p_40: 110167
p_41: 110167
p_42: 110167
p_43: 110167
p_44: 110167
p_45: 110167
p_46: 110054
p_47: 110167
p_48: 110167
p_49: 110167
p_50: 110167
p_51: 110167
p_52: 110167
p_53: 110167
p_54: 110167
