### ISSUE TITLE
KafkaConsumer can't consume messages sometimes

### ISSUE THREAD

**Issue by boatfish** [edenhill/librdkafka#2315]
when serveral kafka consumer based on librdkafka v1.0.0 working with others which based on librdkafka v0.11.5, some time(maybe serveral days later) the kafka consumer with v1.0.0 can‘t consume any message when a partition assigned to it even though there are lots of messages in the partition, and the consumer also can't query watermark offsets  of the partition.   

the kafka consumer is based on the high level api (Rdkafka::KafkaConsumer)
return code of consume is timeout
return code of query_watermark_offsets is also timeout
the timeout time is 1000 ms

the consumers based on v0.11.5 worked well. are there some critical changes in v1.0.0? 

Config:
[global]
max.poll.interval.ms: 86400000
enable.auto.commit: false
offset.store.sync.interval.ms: 0
enable.partition.eof: false
[topic]
auto.offset.reset: earliest

**Comment by edenhill** [comment]
Is your consumer consuming partition(s) from a single broker?
Did that broker connection go down for any reason?
If so, you're probably seeing #2266

**Comment by boatfish** [comment]
there are 3 brokers and no abnormal logs was observed on the brokers. this occurs when rebalance happend and can't recover for longtime(at least serveral hours) utill we roll back the process.

**Comment by edenhill** [comment]
How often are your consumers calling consumer_poll()?
The group will not rebalance until all consumers have called poll, or max.poll.interval.ms has expired.

**Comment by boatfish** [comment]
I call consume functition of Rdkafka::KafkaConsumer  in a loop, and the time interval between two calls is at most 35 seconds.

**Comment by edenhill** [comment]
Okay, can you please reproduce this with `debug=broker,cgrp` and provide us with the logs?

**Comment by boatfish** [comment]
okay，I'll try

**Comment by edenhill** [comment]
Were you able to reproduce this with debug enabled?

**Comment by boatfish** [comment]
This case has not yet recurred
