### ISSUE TITLE
No Hostname Validation Option - ssl.endpoint.identification.algorithm missing

### ISSUE THREAD

**Issue by wesnerm** [edenhill/librdkafka#2319]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
While the ssl.endpoint.identification.algorithm setting is available for Java Kafka clients, it isn't provided for in the library. 

What this setting does it after validating that the broker's certificate is issue directly or indirectly by a trustworthy CA, it looks for a further match between the hostname of the server and the CN (common name) or SAN (alternate name) contained in the issued certificate.

This prevents men-in-the-middle attack.

There doesn't appear to be other mechanisms to validate the hostname.
Or is there? 

Please inform
1) whether there is an alternative?
2) whether the functionality exists?
3) whether the feature will arrive in some future version?

How to reproduce
================
Using latest version of Confluent Kafka .NET v1.0 which I believe uses latest librdkafka.

It's not possible to Set("ssl.endpoint.identification.algorithm", true) on a ProducerConfig object to enable hostname validation. The producer from the Confluent .NET library passes the data to librdkafka.

It results in an InvalidOperationException when calling ProduceAsync. In the exception, librdkafka reports that ssl.endpoint.identification.algorithm setting does not exist.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.  v1.0.0.0
 - [x] Apache Kafka version.  v2.2.0 (latest)
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<librdkafka.redist 1.0.0>`
 - [x] Apache Kafka version: `2.2.0`
 - [x] librdkafka client configuration: `<
security.protocol=ssl
>`
 - [x] Client configuration. .Net Core  
 - [x] Operating system.  Windows/Ubuntu
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Should be fairly easy to add, given that OpenSSL's built-in functionality works as expected:
https://wiki.openssl.org/index.php/Hostname_validation

**Comment by edenhill** [comment]
This is your lucky day, I was knee-deep in SSL refactoring so I added `ssl.endpoint.identification.algorithm` in PR #2309.
It would be great if you could verify this feature on your end (build the `sslcertcb` branch).

**Comment by wesnerm** [comment]
Sorry, for the lack of response. I haven't had to opportunity to test it.

Since I get my packages from NuGet, I need to figure out the interaction between package management, wrapper libraries (Confluent.NET) and private versions of packages from pull requests.

The PR does address other features that I have been interested in such as in-memory keys and the use of Windows roots.

When I verify this works or doesn't work, I will send a message to both this issue and the PR. 

Most likely, I will only able to get to this after the PR is merged.

Thanks for your work.

**Comment by edenhill** [comment]
@wesnerm Makes sense. We'll try to push a release-candidate to NuGet within a week.
