### ISSUE TITLE
Add static membership support in librd consumer client

### ISSUE THREAD

**Issue by abbccdda** [edenhill/librdkafka#2320]
Original proposal was here: 
https://issues.apache.org/jira/browse/KAFKA-8230

Once the effort in https://issues.apache.org/jira/browse/KAFKA-7018 is done, one of the low hanging fruit is to add this support for other language Kafka consumers, such as c consumer in librdKafka.

In fact, we need to upgrade the join group protocol to latest for non-java clients first in order to add on this feature.

**Comment by edenhill** [comment]
Will be available in v1.4.0
