### ISSUE TITLE
SASL Kerberos solaris 10

### ISSUE THREAD

**Issue by roblos** [edenhill/librdkafka#2321]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have made a consumer in C which works fine with a plain connection to Kafka.
Now I am trying to use Kerberos but I am getting the following error: **Auth in state CONNECT (handshake not supported)**
Below there is further details of the logging. 
What do I miss or doing wrong ?
link options: -lrdkafka -lz -lpthread -lrt -lsasl

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): librdkafka-0.11.6
 - [ ] librdkafka client configuration: 

rd_kafka_conf_set(conf, "debug","security", NULL, 0);
rd_kafka_conf_set(conf, "security.protocol","SASL_PLAINTEXT", NULL, 0);
rd_kafka_conf_set(conf, "sasl.mechanisms","GSSAPI", NULL, 0);
rd_kafka_conf_set(conf, "sasl.kerberos.service.name","kafka", NULL, 0);
rd_kafka_conf_set(conf, "sasl.kerberos.keytab","/etc/krb5/user.keytab", NULL, 0);
rd_kafka_conf_set(conf, "sasl.kerberos.principal","user@ALLIANDER.LOCAL", NULL, 0);

rd_kafka_brokers_add(rk, "test.alliander.local:9094")

 - [ ] Operating system: `Solaris 10`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
VMAIO#spsy|leoswrite> %7|1557501171.444|SASL|rdkafka#consumer-1| [thrd:app]: Selected provider Cyrus for SASL mechanism GSSAPI
%7|1557501171.444|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v0.11.6 (0xb06ff) rdkafka#consumer-1 initialized (builtin.features 0xffff, debug 0x200)
%7|1557501172.451|AUTH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Auth in state CONNECT (handshake not supported)
%7|1557501172.451|SASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Initializing SASL client: service name kafka, hostname test.alliander.local, mechanisms GSSAPI, provider Cyrus
%7|1557501172.451|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_plaintext://ltest.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Refreshing SASL keys with command: kinit -S "kafka/test.alliander.local" -k -t "/etc/krb5/user.keytab" suser@ALLIANDER.LOCAL
%7|1557501172.478|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: SASL key refreshed
%7|1557501172.478|SASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: My supported SASL mechanisms: CRAM-MD5 GSSAPI DIGEST-MD5 PLAIN EXTERNAL
%0|1557501172.478|LIBSASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Unable to find a callback: 16385
%2|1557501172.484|LIBSASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185)
%3|1557501172.484|FAIL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185) (after 32ms in state AUTH)
%3|1557501172.484|ERROR|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185) (after 32ms in state AUTH)
%3|1557501172.484|ERROR|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: 1/1 brokers are down
%7|1557501173.485|AUTH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Auth in state CONNECT (handshake not supported)
%

 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It seems this log message might be relevant:

`%0|1557501172.478|LIBSASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Unable to find a callback: 16385`

callback 16385 == 0x4001 = SASL_CB_USER = "Get the name of the user acting for."

There's an old comment in the [librdkafka source](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_sasl_cyrus.c#L442) that says that specifying this callback breaks GSSAPI.
You might want to try changing that code so the callback is defined with GSSAPI too, and then set `sasl.username` to something, what I dont know? It shouldn't be needed with Kerberos.


Follow up problem:
`%2|1557501172.484|LIBSASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: GSSAPI Error: Unspecified GSS failure. Minor code may provide more information (Unknown code 185)`

**Comment by roblos** [comment]
Ok, but sasl.mechanism is set to “GGSAPI” and not “PLAIN”.
Do you mean explicitly setting state->callbacks because of GSSAPI ?



[cid:image001.jpg@01D50766.0DF02C00]

Van: Magnus Edenhill <notifications@github.com>
Verzonden: vrijdag 10 mei 2019 18:30
Aan: edenhill/librdkafka <librdkafka@noreply.github.com>
CC: Los, Robert <robert.los@alliander.com>; Author <author@noreply.github.com>
Onderwerp: Re: [edenhill/librdkafka] SASL Kerberos solaris 10 (#2321)


It seems this log message might be relevant:

%0|1557501172.478|LIBSASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Unable to find a callback: 16385

callback 16385 == 0x4001 = SASL_CB_USER = "Get the name of the user acting for."

There's an old comment in the librdkafka source<https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_sasl_cyrus.c#L442> that says that specifying this callback breaks GSSAPI.
You might want to try changing that code so the callback is defined with GSSAPI too, and then set sasl.username to something, what I dont know? It shouldn't be needed with Kerberos.

Follow up problem:
%2|1557501172.484|LIBSASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: GSSAPI Error: Unspecified GSS failure. Minor code may provide more information (Unknown code 185)

**Comment by edenhill** [comment]
Just remove the if statement

Den fre 10 maj 2019 19:25Robert Los <notifications@github.com> skrev:

**Comment by roblos** [comment]
- I changed the code into:
        /* SASL_CB_USER is needed for PLAIN but breaks GSSAPI */
        if (1 /*!strcmp(rk->rk_conf.sasl.mechanisms, "PLAIN")*/) { /* also GSSAPI */
- recompiled lib
- added: rd_kafka_conf_set(conf, "sasl.username","someuser", NULL, 0);
- but still errors, any other hints or tips ?

%7|1557581403.059|SASL|rdkafka#consumer-1| [thrd:app]: Selected provider Cyrus for SASL mechanism GSSAPI
%7|1557581403.060|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v0.11.6 (0xb06ff) rdkafka#consumer-1 initialized (builtin.features 0xffff, debug 0x200)
%7|1557581404.069|AUTH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Auth in state CONNECT (handshake not supported)
%7|1557581404.069|SASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Initializing SASL client: service name kafka, hostname test.alliander.local, mechanisms GSSAPI, provider Cyrus
%7|1557581404.069|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Refreshing SASL keys with command: kinit -S "kafka/test.alliander.local" -k -t "/etc/krb5/user.keytab" user@ALLIANDER.LOCAL
%7|1557581404.130|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: SASL key refreshed
%7|1557581404.130|SASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: My supported SASL mechanisms: CRAM-MD5 GSSAPI DIGEST-MD5 PLAIN EXTERNAL
%7|1557581404.130|LIBSASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: CB_GETSIMPLE: id 0x4001: returning someuser
%2|1557581404.144|LIBSASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185)
%3|1557581404.144|FAIL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185) (after 75ms in state AUTH)
%3|1557581404.144|ERROR|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185) (after 75ms in state AUTH)
%3|1557581404.144|ERROR|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: 1/1 brokers are down
%7|1557581405.190|AUTH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Auth in state CONNECT (handshake not supported)
%7|1557581405.190|SASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Initializing SASL client: service name kafka, hostname test.alliander.local, mechanisms GSSAPI, provider Cyrus
%7|1557581405.190|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Refreshing SASL keys with command: kinit -S "kafka/test.alliander.local" -k -t "/etc/krb5/user.keytab" user@ALLIANDER.LOCAL
en%7|1557581405.419|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: SASL key refreshed
%7|1557581405.419|SASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: My supported SASL mechanisms: CRAM-MD5 GSSAPI DIGEST-MD5 PLAIN EXTERNAL
%7|1557581405.419|LIBSASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: CB_GETSIMPLE: id 0x4001: returning someuser
%2|1557581405.423|LIBSASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185)
%3|1557581405.423|FAIL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185) (after 233ms in state AUTH)
%3|1557581405.423|ERROR|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185) (after 233ms in state AUTH)

**Comment by roblos** [comment]
It looks like, I am little bit further. I changed the hostname order (kdc host and broker host 'test') in /etc/hosts. So the hostnames I use are the first mentioned after the ip address. My consumer is running on an environment where no DNS is allowed.

/etc/krb5/krb.conf looks like:

**[libdefaults]
        rdns = false
        dns_lookup = no
        dns_lookup_realm = no
        default_realm = ALLIANDER.LOCAL

[kdcdefaults]
        kdc_ports = 88,750

[realms]
        ALLIANDER.LOCAL = {
                kdc = kdc.alliander.local
                admin_server = kdc.alliander.local
                default_domain = ALLIANDER.LOCAL
        }

[domain_realm]
        .alliander.local = ALLIANDER.LOCAL
        alliander.local = ALLIANDER.LOCAL**

Can you please advice/judge the following log what the status is ? 


%7|1557584699.635|SASL|rdkafka#consumer-1| [thrd:app]: Selected provider Cyrus for SASL mechanism GSSAPI
%7|1557584699.635|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v0.11.6 (0xb06ff) rdkafka#consumer-1 initialized (builtin.features 0xffff, debug 0x200)
%7|1557584700.642|AUTH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Auth in state CONNECT (handshake not supported)
%7|1557584700.642|SASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Initializing SASL client: service name kafka, hostname test.alliander.local, mechanisms GSSAPI, provider Cyrus
%7|1557584700.643|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Refreshing SASL keys with command: kinit -S "kafka/test.alliander.local" -k -t "/etc/krb5/user.keytab" user@ALLIANDER.LOCAL
%7|1557584700.668|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: SASL key refreshed
%7|1557584700.668|SASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: My supported SASL mechanisms: CRAM-MD5 GSSAPI DIGEST-MD5 PLAIN EXTERNAL
%7|1557584700.668|LIBSASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: CB_GETSIMPLE: id 0x4001: returning user
%7|1557584700.674|SASL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: Send SASL frame to broker (2120 bytes)
%3|1557584700.676|FAIL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: SASL authentication failure: Invalid frame size 352518912 (after 33ms in state AUTH)
%3|1557584700.676|ERROR|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: SASL authentication failure: Invalid frame size 352518912 (after 33ms in state AUTH)
%3|1557584700.676|ERROR|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: 1/1 brokers are down

**Comment by edenhill** [comment]
```%3|1557584700.676|FAIL|rdkafka#consumer-1| [thrd:sasl_plaintext://test.alliander.local:9094/bootstrap]: sasl_plaintext://test.alliander.local:9094/bootstrap: SASL authentication failure: Invalid frame size 352518912 (after 33ms in state AUTH)```

This looks like a protocol mismatch, are you sure you are connecting to the brokers SASL_PLAINTEXT listener?

**Comment by roblos** [comment]
I had to set SASL_SSL. The result is now:
Looks like the other side is down ?

VMAIO#spsy|leoswrite> %3|1557733908.741|FAIL|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 499ms in state UP)
%3|1557733908.741|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 499ms in state UP)
%3|1557733908.741|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: 1/1 brokers are down
i%3|1557733909.241|FAIL|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 498ms in state UP)
%3|1557733909.241|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 498ms in state UP)
%3|1557733909.241|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: 1/1 brokers are down
gni%3|1557733909.741|FAIL|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 498ms in state UP)
%3|1557733909.741|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 498ms in state UP)
%3|1557733909.741|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: 1/1 brokers are down
te %3|1557733910.240|FAIL|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 498ms in state UP)
%3|1557733910.241|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 498ms in state UP)
%3|1557733910.241|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: 1/1 brokers are down
pr%3|1557733910.741|FAIL|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 499ms in state UP)
%3|1557733910.741|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 499ms in state UP)
%3|1557733910.741|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: 1/1 brokers are down
j%3|1557733911.241|FAIL|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 497ms in state UP)
%3|1557733911.241|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 497ms in state UP)
%3|1557733911.241|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: 1/1 brokers are down
471%4|1557733911.740|REQTMOUT|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Timed out 0 in-flight, 1 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1557733911.741|FAIL|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 499ms in state UP)
%3|1557733911.741|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: la0040.alliander.local:9094/bootstrap: Disconnected (after 499ms in state UP)
%3|1557733911.741|ERROR|rdkafka#consumer-1| [thrd:la0040.alliander.local:9094/bootstrap]: 1/1 brokers are down

**Comment by roblos** [comment]
Or does /bootstrap cause connection issues ?

**Comment by roblos** [comment]
update. I compiled the lib with option --disable-ssl which is not handy I think when I want to use SASL_SSL ! ;-)
- So I recompiled the lib without this option and my program also linked with -lssl and -lcrypto. 
- I used an company crt which is also known by the broker(s) and make a truststore on the client.
  keytool -import -file <company.crt> -keypass <pasw> -keystore keystore.jks -storepass <pasw>
- then the following settings to the program:
rd_kafka_conf_set(conf, "debug","security", NULL, 0);
rd_kafka_conf_set(conf, "security.protocol","SASL_SSL", NULL, 0);
rd_kafka_conf_set(conf, "sasl.mechanisms","GSSAPI", NULL, 0);
rd_kafka_conf_set(conf, "sasl.kerberos.service.name","kafka", NULL, 0);
rd_kafka_conf_set(conf, "sasl.kerberos.keytab","/etc/krb5/user.keytab", NULL, 0);
rd_kafka_conf_set(conf, "sasl.kerberos.principal","user@ALLIANDER.LOCAL", NULL, 0);
rd_kafka_conf_set(conf, "ssl.truststore.location","/etc/krb5/keystore.jks", NULL, 0);
rd_kafka_conf_set(conf, "ssl.truststore.password","<pasw>", NULL, 0);
rd_kafka_brokers_add(rk, "test.alliander.local:9094");

Which results in the following situation. Path and permissions of /etc/krb5/keystore.jks looks fine.
Any ideas ? 
If it works eventually I will sent you a bottle of wine or beer !!!! 

 
%7|1557760146.916|SASL|rdkafka#consumer-1| [thrd:app]: Selected provider Cyrus for SASL mechanism GSSAPI
%7|1557760146.916|OPENSSL|rdkafka#consumer-1| [thrd:app]: librdkafka built with OpenSSL version 0x100020ff
%7|1557760146.917|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v0.11.6 (0xb06ff) rdkafka#consumer-1 initialized (builtin.features 0xffff, debug 0x200)
%3|1557760146.939|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://test.alliander.local:9094/bootstrap]: sasl_ssl://test.alliander.local:9094/bootstrap: Failed to verify broker certificate: unable to get local issuer certificate (after 20ms in state CONNECT)
%3|1557760146.939|ERROR|rdkafka#consumer-1| [thrd:sasl_ssl://test.alliander.local:9094/bootstrap]: sasl_ssl://test.alliander.local:9094/bootstrap: Failed to verify broker certificate: unable to get local issuer certificate (after 20ms in state CONNECT)
%3|1557760146.939|ERROR|rdkafka#consumer-1| [thrd:sasl_ssl://test.alliander.local:9094/bootstrap]: 3/3 brokers are down

**Comment by roblos** [comment]
Update. The certificate issue looks resolved, but I still have the problem with the unknown GSS failure.

%7|1557827911.196|SASL|rdkafka#consumer-1| [thrd:app]: Selected provider Cyrus for SASL mechanism GSSAPI
%7|1557827911.196|OPENSSL|rdkafka#consumer-1| [thrd:app]: librdkafka built with OpenSSL version 0x100020ff
%7|1557827911.196|SSL|rdkafka#consumer-1| [thrd:app]: Loading CA certificate(s) from file /etc/krb5/AllianderRootCA.crt
%7|1557827911.197|SSL|rdkafka#consumer-1| [thrd:app]: Loading certificate from file /etc/krb5/AllianderIssuerCA.crt
%7|1557827911.198|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v0.11.6 (0xb06ff) rdkafka#consumer-1 initialized (builtin.features 0xffff, debug 0x200)
%7|1557827911.219|SSLVERIFY|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: Broker SSL certificate verified
%7|1557827911.220|AUTH|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: Auth in state APIVERSION_QUERY (handshake supported)
%7|1557827911.221|SASLMECHS|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: Broker supported SASL mechanisms: GSSAPI
%7|1557827911.221|AUTH|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: Auth in state AUTH_HANDSHAKE (handshake supported)
%7|1557827911.221|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: Initializing SASL client: service name kafka, hostname test.ALLIANDER.LOCAL, mechanisms GSSAPI, provider Cyrus
%7|1557827911.221|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: Refreshing SASL keys with command: kinit -S "kafka/test.ALLIANDER.LOCAL" -k -t "/etc/krb5/test.keytab" test@ALLIANDER.LOCAL
%7|1557827911.251|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: SASL key refreshed
%7|1557827911.251|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: My supported SASL mechanisms: CRAM-MD5 GSSAPI DIGEST-MD5 PLAIN EXTERNAL
%7|1557827911.251|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: CB_GETSIMPLE: id 0x4001: returning kafka
%2|1557827911.257|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185)
%3|1557827911.257|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185) (after 36ms in state AUTH)
%3|1557827911.257|ERROR|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Unknown code 185) (after 36ms in state AUTH)
%3|1557827911.257|ERROR|rdkafka#consumer-1| [thrd:sasl_ssl://test.ALLIANDER.LOCAL:9094/bootstrap]: 1/1 brokers are down

**Comment by edenhill** [comment]
`Unknown error 185` might be `KRB5_NO_TKT_IN_RLM` - "Cannot find ticket for requested realm", according to this site: https://www.netmeister.org/blog/krb5-error-codes-table.html

Can you try the `singlekinit` branch, https://github.com/edenhill/librdkafka/tree/singlekinit, it has some fixes around how kinit is called which I think might be relevant to this situation.

**Comment by roblos** [comment]
Ok, or do I need to use V1.0.0 of the lib ? I am now using V.0.11.6.

**Comment by edenhill** [comment]
There is a singlekinit-v0.11.6 branch too, if you wish to remain on v0.11.6 for testing.
Otherwise I suggest using the singlekinit branch based on v1.0.0/master since it has a lot of other fixes.

**Comment by roblos** [comment]
Any tips/hints how to compile V1.0.0 on solaris 10 ?

The compiling of V.0.11.6 succeeded with the following actions but for V1.0.0. some configs has been changed,:
1) adding the following 3 items with SunOS part in configure.librdkafka: 
        mkl_mkvar_append CFLAGS CFLAGS "-Dsun"
        mkl_mkvar_append CFLAGS CFLAGS "-D__sun"
        mkl_mkvar_append CFLAGS CFLAGS "-D_XPG6"

**Comment by edenhill** [comment]
I don't have access to a sun machine, so I can't really help out, but we'd be happy to accept a PR if you sort it out.

**Comment by roblos** [comment]
Ok, I will keep on trying. In the meantime it looked like I resolved the GSSAPI error. I had to put fqdn at first after the ip address in /etc/hosts. So I can still use V.0.11.6 but it feels better to use V1.0.0. 
I close this issue.
