### ISSUE TITLE
Invalid value "zstd" for configuration property "compression.codec"

### ISSUE THREAD

**Issue by senthilec566** [edenhill/librdkafka#2322]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Im using LibRdKafka V1.0.0 (https://github.com/edenhill/librdkafka/tree/v1.0.0) and it started failing with Invalid value "zstd" for configuration property "compression.codec" if i change compression from snappy to zstd.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.0.0`
 - [x] Apache Kafka version: `2.2.0`
 - [x] librdkafka client configuration: `log.connection.close=true,compression.type=zstd`
 - [x] Operating system: `Ubuntu`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You built librdkafka without zstd, check config.log why
