### ISSUE TITLE
failed to initialize confluent-kafka-producer errno: Success)

### ISSUE THREAD

**Issue by jsikarin** [edenhill/librdkafka#2325]
So I am trying to initialize a confluent-kafka-producer and send the message "this is a test" into a topic called events. I am using ssl with a CA and have debugging set to "all". The logs for my producer can be found in the pastebin below:

https://pastebin.com/MUxBGyyz

To protect the hostnames of my brokers I have replaced both broker's hostnames with bababooey

Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I don't see anything wrong in the logs, your messages are produced:
`%7|1557804000.043|MSGSET|rdkafka#producer-1| [thrd:ssl://bababooey:9092/2]: ssl://bababooey:9092/2: events [12]: MessageSet with 1 message(s) delivered`

**Comment by qburst-nanditha** [comment]
@edenhill We have issue with kafka producer initialisation. 
Traceback (most recent call last):
  File "/usr/src/app/pubsub/kafkaproducer.py", line 86, in send_messages
    producer.init_transactions(30)
cimpl.KafkaException: KafkaError{code=_TIMED_OUT,val=-185,str="Failed to initialize Producer ID: Local: Timed out"}"

Could you please help

**Comment by qburst-nanditha** [comment]
@edenhill Kafka timeout issue happens frequently and now we got above exception
