### ISSUE TITLE
librdkafka v1.0 compiling Solaris 10

### ISSUE THREAD

**Issue by roblos** [edenhill/librdkafka#2327]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
How can lib V1.0 being compiled at Solaris 10 ?

With V0.11.6 the following procedure worked:
1) Change configure.librdkafka and add for $MKL_DISTRO == "SunOS"
         mkl_mkvar_append CFLAGS CFLAGS "-Dsun"
        mkl_mkvar_append CFLAGS CFLAGS "-D__sun"
        mkl_mkvar_append CFLAGS CFLAGS "-D_XPG6"
2) ./configure --clean
3)./configure --prefix /etsi/work/gli/kafka/librdkafka-master --exec-prefix=/etsi/work/gli/kafka/librdkafka-master/local --includedir=/usr/include --cc=/opt/SUNWspro/bin/cc --cxx=/opt/SUNWspro/bin/CC --mbits=64 --enable-static
4) gmake

 - [x] librdkafka version (release number or git tag): `V1.0.0`
 - [ ] Operating system: `Solaris 10`

**Comment by edenhill** [comment]
If you sort this out, please document what you had to do, or submit a PR with your changes
