### ISSUE TITLE
compile failed, about openssl version 

### ISSUE THREAD

**Issue by songhtdo** [edenhill/librdkafka#2328]
Thank you very much for your work.
Librdkafka compilation failed while I was compiling it.
![image](https://user-images.githubusercontent.com/22132121/57758364-1d92c300-772a-11e9-871a-04ad1d744c22.png)

librdkafka version: 
RD_KAFKA_VERSION  0x010000ff

openssl version:
openssl-1.0.2k
Openssl-devel has been installed.

**Comment by edenhill** [comment]
Are you using a release tarball of librdkafka or a git checkout? If the latter, what sha?
