### ISSUE TITLE
HighLevelProducer default key/message serialization broken.

### ISSUE THREAD

**Issue by norla** [edenhill/librdkafka#2329]
Description
===========
HighLevelProducer default key/message serialization broken.

If you don't set message/key serializers nothing is sent and no errors are emitted.
I think it is because the default serializers are not fed through the "createSerializer" function which alters the behaviour of the "apply" function (it originally takes two arguments).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply

https://github.com/Blizzard/node-rdkafka/blob/50f99ab46c4a475678b94af07c2ea02e1ba353ff/lib/producer/high-level-producer.js#L257

How to reproduce
================

```
const Kafka = require("node-rdkafka");
const producer = new Kafka.HighLevelProducer({
  "metadata.broker.list": "localhost:9200"
});
producer.connect();
producer.on("ready", () => {
  producer.produce("some-topic", null, Buffer.from("Hello"), "some-key", Date.now(), (err, res) => {
    console.log("Message sent", err, res);
  });
});
```

**Comment by edenhill** [comment]
librdkafka does not have serializers, sounds like you should file this issue on the node-rdkafka project.

**Comment by norla** [comment]
My bad, sorry :)
