### ISSUE TITLE
rkmessage partition not set in dr_msg_cb

### ISSUE THREAD

**Issue by DEvil0000** [edenhill/librdkafka#233]
I am producing messages to UA using the partitioner callback.
I was trying to print some values from the message object when dr_cb is called.
* partition: was -1, expected the real partition used by partitioner callback.
* offset: was kind of random(not set/initialized), expected the offset of the message written (if not possible -1 or the last known offset)
Maybe it would be a nice enhancement setting some values when producing.

**Comment by edenhill** [comment]
* Partition in rkmessage: will fix.
* You need to enable offset reporting by setting the `produce.offset.report` topic configuration property to `true`. This is a non-default property since it has a tiny tiny performance impact.

**Comment by edenhill** [comment]
->partition should be fixed now.
