### ISSUE TITLE
Producer to consumer latency measurement

### ISSUE THREAD

**Issue by jleducq** [edenhill/librdkafka#2330]
Hi,

I am measuring the latency of my applications communicating via Kafka. The producer and consumer are C++ applications using librdkafka.
There are few things I am still not clear on how to correctly measure the latency:

- **Producer to Consumer latency**: In my consumer I use the `timestamp()` function of the `RdKafka::Message` class, and subtract to the current time to get the elapsed time between producing and consuming. My understanding is that the producer will create the timestamp in the header of the message, but I don't know when exactly. Is the timestamp created right after the `produce` function is called? Is it created before the message is being batched by the producer? Or is it created when the message is sent to the network? And if yes, is there a way to calculate the latency between the `produce` call to the `consume` call?

- **Produce to delivery report latency**: Similarly I use the `message.latency()` function in the delivery report callback to log the latency between the `produce` and the delivery report callback. Does this latency includes the wait/batch time in the producer queue? Or is it just the network latency? 

Thanks

**Comment by edenhill** [comment]
Message timestamps are set at produce() time.

See [latency measurements](https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#low-latency) for a complete breakdown of latencies.

**Comment by jleducq** [comment]
Thanks.
Just to confirm the `latency()` method doc of the `RdKafka::Message` class states: 

> The latency in microseconds for a produced message measured from the produce() call

We are speaking about the latency between the `produce()` and the delivery report callback call? Not the latency between the `produce()` and the reception of the message by the Kafka broker?

**Comment by edenhill** [comment]
It is the number of microseconds since the produce() call to now.
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_msg.c#L1044
