### ISSUE TITLE
Poll blocks forever if Unsubscribe/Close is called concurrently

### ISSUE THREAD

**Issue by agis** [edenhill/librdkafka#2333]
Description
===========
_Note: Not sure if this is an actual issue or just us using librdkafka in a wrong way._

In [rafka](https://github.com/skroutz/rafka) (a Kafka proxy), it's common that we use a consumer from multiple goroutines. For example, a rafka client might call `Poll()` while a rafka admin might at the same time shuts down the server.

This means that the [consumer termination code](https://github.com/skroutz/rafka/blob/master/consumer.go#L69-L99) (i.e. `Unsubscribe`, `Poll`, `Close`) might be called _concurrently_ with a [consumer Poll()](https://github.com/skroutz/rafka/blob/master/consumer.go#L103-L106).

We noticed that if the termination process is called right after a `Poll()` happens (but before it returns), then that `Poll()` hangs up forever, with no additional logs by librdkafka.

This happens in 0.11.6 and 1.0.0. The process used to work fine with 0.11.4 and 0.11.5. I've attached logs from 0.11.5 and 0.11.6 for comparison.

That said, I'm not sure if we're supposed to do this concurrent usage (calling `Poll()` and `Unsubscribe()` or `Close()` from multiple goroutines).

How to reproduce
================
If further investigation is needed, I'll try to prepare a reproduction script.

Checklist
=========
 - [x] librdkafka version: 0.11.6 and 1.0.0
 - [x] Apache Kafka version: 1.1.1
 - [x] librdkafka client configuration: `api.version.request:true auto.commit.interval.ms:10000 auto.offset.reset:latest bootstrap.servers:foo.example.com enable.auto.commit:true enable.auto.offset.store:false enable.partition.eof:false go.application.rebalance.enable:false go.events.channel.enable:false log.connection.close:false session.timeout.ms:6000] map[api.version.request:true bootstrap.servers:foo.example.com go
.delivery.reports:true go.events.channel.size:1000 go.produce.channel.size:0 log.connection.close:false session.timeout.ms:6000`
 - [x] Operating system: Debian Stretch
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

### librdkafka logs
- working: [11_5.txt](https://github.com/edenhill/librdkafka/files/3206404/11_5.txt)
- non-working: [11_6.txt](https://github.com/edenhill/librdkafka/files/3206405/11_6.txt)

**Comment by edenhill** [comment]
This is not a supported use-case, you must not call poll(), or any other method short of destroy(), on the consumer object while or after you've called close().
Consider it a destructor of sorts.

**Comment by agis** [comment]
Makes sense. Though I'm not sure this is what happens in our use case. It's more like "calling Close in-between a Poll`. But anyway, I guess the same holds true as well. Thanks.
