### ISSUE TITLE
Know that RdKafka::Producer::create initially connects

### ISSUE THREAD

**Issue by vsakharuk** [edenhill/librdkafka#2334]
Description
===========

I am trying to figure out how I can block "main" application until initial connect to Kafka server made. For example if someone provide wrong broker then error will happen but after the reconnect time out. This is handy after the initial success but not on first attempt. On first attempt I would like to treat those as "fatal".

Is there any appropriate solution?

How to reproduce
================
RdKafka::Conf conf;
string errstr;
conf.set("metadata.broker.list", "127.0.0.1:12345", errstr);
RdKafka::Producer::create(&conf, errstr));
wait_and_hope(); // obviously will fail socket.max.fails times.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Irrelevant.

**Comment by edenhill** [comment]
As a workaround you could call `clusterid()` with a timeout, if you get an empty string back it means the client was not able to connect, else it will provide a non-empty string of the cluster as retrieved from the first broker it connects to.

**Comment by vsakharuk** [comment]
Thank you very much.
