### ISSUE TITLE
Kafka @ Azure Event Hubs?

### ISSUE THREAD

**Issue by robert-schmidt** [edenhill/librdkafka#2336]
Really sorry for breaking the rules here, but I feel like losing it. Trying to connect & consume from an Azure Event Hub with no luck so far. I don't know what SSL certificate to use for the SASL_SSL mechanism that Azure requires. From their guidelines, it doesn't seem necessary to specify a SSL certificate path, but the authentication fails without it ( Failed to verify broker certificate: unable to get local issuer certificate). If I specify a self generated .crt file path, it doesn't really help either, it fails on consuming brokers. 

Has anyone managed to consume/produce from php to Azure Event Hubs? HOW did you do it?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please fill out the checklist.

**Comment by rolandyoung** [comment]
This sounds more like a question about Azure, SASL. SSL or Kafka than about librdkafka. Have you tried connecting using the Kafka command line Java client? If that doesn't work, you may need to try another forum.

If you can connect with the command line client, the command line and any config files it references would be useful information here, as well as details of your librdkafka client configuration.

Bear in mind that that third party broker is unlikely to trust a certificate that isn't signed by an authority they trust. But you don't normally need them to trust your certificate: you need to let your client trust the broker's certificate by configure its CA certificate file as `ssl.ca.location`.

**Comment by totuni** [comment]
I am currently trying to connect to event hubs using this.  If you got something to work.  I sure would like to see the config parms.

**Comment by robert-schmidt** [comment]
@totuni please see my last reply here: https://github.com/Azure/azure-event-hubs-for-kafka/issues/51

Hope it helps.

**Comment by anantmaks** [comment]
@robert-schmidt 
As per your commented solution on [https://github.com/Azure/azure-event-hubs-for-kafka/issues/51](https://github.com/Azure/azure-event-hubs-for-kafka/issues/51), I tried to use and consume a topic but it came out with no luck. Can you please have a look at the code and guide what needs to be done? 

I have installed the rdkafka.so on my ubuntu system as per [PHP Manual](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/index.html) and then used this piece of code :

`$conf = new RdKafka\Conf();`
`$conf->set('group.id', '$Default');`
`$conf->set('metadata.broker.list', 'syndigo-wk.servicebus.windows.net:9093');`
`$conf->set('security.protocol', 'SASL_SSL');`
`$conf->set('sasl.mechanisms', 'PLAIN');`
`$conf->set('sasl.username', '$ConnectionString');`
`$conf->set('sasl.password', 'const connectionString = "Endpoint=sb://syndigo-wk.servicebus.windows.net/;SharedAccessKeyName=syn-wk;SharedAccessKey=7K3RFuz6OEVXejb99PpyRRkmn8xXV9/8sncpnY4TosE=;EntityPath=webkul-syndigo"');`
`$conf->set('api.version.request', 'false');`
`$conf->set('log_level', (string) LOG_DEBUG);`
`$conf->set('debug', 'all');`

`$rk = new RdKafka\Consumer($conf);`
`$topicConf = new RdKafka\TopicConf();`
`$topicConf->set('auto.commit.interval.ms', 100);`
`$topicConf->set('offset.store.method', 'broker');`
`$topicConf->set('auto.offset.reset', 'earliest');`
`$topic = $rk->newTopic("test", $topicConf);`

`while (true) {`
`    $message = $topic->consume(0, 120*10000);`
`    switch ($message->err) {`
`        case RD_KAFKA_RESP_ERR_NO_ERROR:`
`            var_dump($message);`
`            break;`
`        case RD_KAFKA_RESP_ERR__PARTITION_EOF:`
`            echo "No more messages; will wait for more\n";`
`            break;`
`        case RD_KAFKA_RESP_ERR__TIMED_OUT:`
`            echo "Timed out\n";`
`            break;`
`        default:`
`            throw new \Exception($message->errstr(), $message->err);`
`            break;`
`    }`
`}`

My connection string already has produced events in it that I can confirm by [azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/eventhub/event-hubs/samples/v5/javascript), using JS SDK I am able to produce and consume events.
When I try to read the `$message` from `$topic` it returns as `null`

PS: I am currently using the pricing tier as 'Standard' on the azure event hub and it has Kafka Surface 'enabled'
