### ISSUE TITLE
Kerberos authentication fails on Alpine container

### ISSUE THREAD

**Issue by PanagiotisFytas** [edenhill/librdkafka#2342]
Description
===========
I am trying to use a python consumer to read from a secure kafka (with kerberos) from a within an alpine docker container. However, I receive the  following messages when calling calling `consume(1)`:

%2|1559044535.520|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://sn07.ops.domain.gr:9093/bootstrap]: sasl_ssl://sn07.ops.domain.gr:9093/bootstrap: GSSAPI Error:  Miscellaneous failure (see text) (Matching credential (kafka/sn07.ops.domain.gr@OPS.DOMAIN.GR) not found)
%3|1559044535.520|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://sn07.ops.domain.gr:9093/bootstrap]: sasl_ssl://sn07.ops.domain.gr:9093/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text) (Matching credential (kafka/sn07.ops.domain.gr@OPS.DOMAIN.GR) not found) (after 35043ms in state AUTH)
%3|1559044535.520|ERROR|rdkafka#consumer-1| [thrd:sasl_ssl://sn07.ops.domain.gr:9093/bootstrap]: sasl_ssl://sn07.ops.domain.gr:9093/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text) (Matching credential (kafka/sn07.ops.domain.gr@OPS.DOMAIN.GR) not found) (after 35043ms in state AUTH)
%2|1559044536.519|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://sn04.ops.domain.gr:9093/bootstrap]: sasl_ssl://sn04.ops.domain.gr:9093/bootstrap: GSSAPI Error:  Miscellaneous failure (see text) (Matching credential (kafka/sn04.ops.domain.gr@OPS.DOMAIN.GR) not found)
%3|1559044536.519|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://sn04.ops.domain.gr:9093/bootstrap]: sasl_ssl://sn04.ops.domain.gr:9093/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text) (Matching credential (kafka/sn04.ops.domain.gr@OPS.DOMAIN.GR) not found) (after 35041ms in state AUTH)
%3|1559044536.519|ERROR|rdkafka#consumer-1| [thrd:sasl_ssl://sn04.ops.domain.gr:9093/bootstrap]: sasl_ssl://sn04.ops.domain.gr:9093/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text) (Matching credential (kafka/sn04.ops.domain.gr@OPS.DOMAIN.GR) not found) (after 35041ms in state AUTH)

Kinit appears to be working, since this is the content of my kerberos cache:

Ticket cache: FILE:/tmp/krb5cc_0
Default principal: principal@DOMAIN.GR

Valid starting     Expires            Service principal
05/28/19 11:56:16  05/28/19 21:56:16  kafka/sn09.ops.domain.gr@DOMAIN.GR
	renew until 06/04/19 11:56:16

It appears to be an issue with my alpine container, since I am able to consume messages using librdkafka and the python library from the host machine without an issue. My /etc/hosts and /etc/krb5.conf files on the container seem to be configured properly (they are the same as the host machine), since I am able to consume messages using a pyspark consumer from within my docker container. 

Please let me know if you want me to attach specific librdkafka debug messages.

How to reproduce
================

My docker images has the following format:
```
FROM alpine:3.8

RUN apk add --no-cache git alpine-sdk python-dev py-cffi linux-headers musl-dev python3-dev g++ 
RUN apk add --no-cache krb5-pkinit krb5-dev krb5 cyrus-sasl-gssapi
RUN git clone https://github.com/edenhill/librdkafka.git \
    && apk add --no-cache cyrus-sasl-dev openssl-dev  bsd-compat-headers cyrus-sasl openssl \
    && cd /librdkafka/ \
    && git checkout v1.0.0 \
    && ./configure --install-deps \
    && make \
    && make install
RUN pip3.6 install --upgrade pip \
    && pip install --no-binary :all: confluent-kafka==0.11.5
```
I run this python 3.6 script, which starts printing (continuously) those messages when the consume() method is called.

```
import confluent_kafka

c = confluent_kafka.Consumer({
    'bootstrap.servers': ','.join(['sn01.ops.domain.gr:9093',
                        'sn02.ops.domain.gr:9093',
                        'sn03.ops.domain.gr:9093',
                        'sn04.ops.domain.gr:9093',
                        'sn05.ops.domain.gr:9093',
                        'sn06.ops.domain.gr:9093',
                        'sn07.ops.domain.gr:9093',
                        'sn08.ops.domain.gr:9093',
                        'sn09.ops.domain.gr:9093',
                        'sn10.ops.domain.gr:9093',
                        'sn11.ops.domain.gr:9093',]),
   'group.id': ...,
   'sasl.kerberos.keytab': ...,
   'sasl.kerberos.principal': 'principal@DOMAIN.GR',
   'sasl.kerberos.service.name': 'kafka',
   'sasl.mechanisms': 'GSSAPI',
   'security.protocol': 'sasl_ssl',
   'ssl.certificate.location': ...,
   'ssl.ca.location': ...,
})

c.assign([confluent_kafka.TopicPartition('dev-1', 0, 0)])
m = c.consume(1)
print(m)

```

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `release: v1.0.0`
 - [x] Apache Kafka version: `0.11`
 - [x] librdkafka client configuration: `<'bootstrap.servers': '...',
   'group.id': '...',
   'sasl.kerberos.keytab': '...',
   'sasl.kerberos.principal': '...',
   'sasl.kerberos.service.name': 'kafka',
   'sasl.mechanisms': 'GSSAPI',
   'security.protocol': 'sasl_ssl',
   'ssl.certificate.location': '...',
   'ssl.ca.location': '...'.>`
 - [x] Operating system: `Alpine linux`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you try librdkafka master branch instead of v1.0.0, we recently merged some Kerberos-related fixes?

**Comment by edenhill** [comment]
That's great news, thanks!

You can use master for development and testing, but not for production use.
We're planning the release for within a month.

**Comment by PanagiotisFytas** [comment]
Ok thanks, I will wait for the release
