### ISSUE TITLE
SSL_new runtime issue with Integration to another application

### ISSUE THREAD

**Issue by ChandraDuddukuri** [edenhill/librdkafka#2343]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
librdkafka is built on my environment and created a static library
this static library is used while building my application which internally has its own SSL implementation.

During runtime, the kafka method is trying to use the SSL_new method from other library and failing. 

How to avoid this??

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I think you should dynamically link librdkafka, your app, and that other library to openssl.

**Comment by ChandraDuddukuri** [comment]
i have constraints in my project and i should go for static linking 

the initial static library is not having the dependencies in librdkafka.a (commands used to create lib : ./configure;make)

When trying to use the ./configure --enable-static;make
**Error in Suse 11:**
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libz.a(crc32.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libz.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

**Error in Suse 12:**
usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lssl
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lcrypto
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status

**From where can i download these lib's for Suse Linux  libssl(.so;a), libcrypto(.so;a) & libz(.so;a)**

**Comment by edenhill** [comment]
Try `./configure --enable-static --install-deps --source-deps-only`

**Comment by ChandraDuddukuri** [comment]
**The below information will be usefull for persons looking for the fix:**
by using the --install-deps, it tried to download the deps, but it failed and no log information

upon investigation, came to know, the openssl & zstd are the required dependencies for me. The below mentioned files have the information about the URL to download & version of the dependencies
<librdkafka_source_code>/mklove/modules/configure.libssl
<librdkafka_source_code>/mklove/modules/configure.zstd
I copied the dependency code to 
<librdkafka_source_code>/mklove/deps/src/libcrypto
<librdkafka_source_code>/mklove/deps/src/zstd

./configure --enable-static --install-deps --source-deps-only
make

the librdkafka got build successfully.
