### ISSUE TITLE
Could not determine kind of name for C.RD_KAFKA_EVENT_OAUTHBEARER_TOKEN_REFRESH

### ISSUE THREAD

**Issue by ssridharan27** [edenhill/librdkafka#2344]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
When I try to install librdkafka followed by the go client library for kafka I get the following error:
go/src/github.com/confluentinc/confluent-kafka-go/kafka/adminapi.go:930:82: could not determine kind of name for C.RD_KAFKA_EVENT_OAUTHBEARER_TOKEN_REFRESH

How to reproduce
================
Install the latest version of librdkafka which is 1.0.1 and then run
go get github.com/confluentinc/confluent-kafka-go/kafka

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.0.1`
 - [x] Apache Kafka version: `2.2.0`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `Mojave 10.14.4`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Pin the Golang client to v1, otherwise you'll get the master branch which may reference unreleased librdkafka functionality, such as in this case.

So, change your import to:
`"gopkg.in/confluentinc/confluent-kafka-go.v1/kafka"`

**Comment by ssridharan27** [comment]
@edenhill  For some reason gopkg.in wasn't working but instead using go mod along with @ for versioning helped get the right version for the client library which works perfectly. Thanks a lot for the help.

**Comment by ssubhaadip** [comment]
@ssridharan27 Can you please provide the solution that resolved your issue?
I am also facing the exact same issue.

**Comment by ssridharan27** [comment]
@ssubhaadip I basically used go mod to pin a specific version of the client library that I needed which works with the version of librdkafka. 
Follow this link to understand go module: https://blog.golang.org/using-go-modules

You need to have an entry inside your go.mod file after you initialize
something like this:
require github.com/confluentinc/confluent-kafka-go v1.0.0

**Comment by ssubhaadip** [comment]
@ssridharan27 Thanks for your reply.
I have already used go modules and my module looks like below
module xxxx
go 1.12
require (
	github.com/confluentinc/confluent-kafka-go v1.0.0
        ....
)
Do you see any issue with this?
