### ISSUE TITLE
librdkafak.so.1 not found

### ISSUE THREAD

**Issue by liur20** [edenhill/librdkafka#2345]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hello Eden, 
I followed you guide here https://github.com/KxSystems/kafka and git clone, make, and make installed the librdkafak. However, I am not able to find the librdkafka.so.1 file. This results me not able to proceed the tutorial. Can you help me explain this problem? Thank you

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [x] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rolandyoung** [comment]
The KxSystems/Kafka project does not belong to Magnus Edenhill, the owner of this project.
You should raise questions about their tutorial here: https://github.com/KxSystems/kafka/issues .

When raising an issue against any project, you MUST provide steps to reproduce your problem (say exactly what you did) and provide information about the version of the software you downloaded and the operating system you were using. (See the two IMPORTANT notes above.)
