### ISSUE TITLE
Fastest way of consuming a lot of data

### ISSUE THREAD

**Issue by roblos** [edenhill/librdkafka#2346]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have an producer and consumer written in C. The producer sometimes has to writes 4600000 entries, and this is done within 6 seconds. That's fine by me. The consumer is taking about 2 minutes to consume those entries. Can this be done faster or do I have reached the limit ?
Producer and consumer both use partition 0.

How to reproduce
================
I use the following consuming method:

```
int Nbatch=150000;
ssize_t ret;
struct mykafkadata packet;
rd_kafka_message_t **rkmessages = NULL;
rkmessages = (rd_kafka_message_t**)malloc(sizeof(*rkmessages) * Nbatch);
while(true) {
      ret = rd_kafka_consume_batch_queue(rkqu,5000,rkmessages,Nbatch);
      if (ret > 0)
      {
        for (i = 0 ; i < ret ; i++)
        {
          if(rkmessages[i]->len != sizeof(packet))
          {
            printf("\n\n**** invalied packet '%s'\n\n\n",(char*)rkmessages[i]->payload);
            continue;
          }
          memcpy(&packet, (struct mykafkadata*)rkmessages[i]->payload, rkmessages[i]->len);
          // ... do stuff with consumed data ...
          rd_kafka_message_destroy(rkmessages[i]);
        }
        printf("Consumed : %d\n",ret);
      }
      else
      {
         printf("\n\n**** rd_kafka_consume_batch: failed ret=%d\n\n\n",ret);
      }
}

kafka config settings:
debug=security
auto.offset.reset=earliest
bootstrap.servers=test.alliander.local:9094
group.id=spectrum
batch.num.messages=5000
queue.buffering.max.ms=1000
queue.buffering.max.messages=4000000
queued.min.messages=1000000
security.protocol=SASL_SSL
sasl.mechanism=GSSAPI
sasl.username=test@ALLIANDER.LOCAL
sasl.kerberos.service.name=kafka
sasl.kerberos.keytab=/etc/krb5/test.keytab
sasl.kerberos.principal=test@ALLIANDER.LOCAL
ssl.ca.location=/etc/krb5/keystore-it.pem
```

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag):  v0.11.6
 - [ ] Operating system: solaris 10

**Comment by edenhill** [comment]
Try the following:
 * comment out your per-message processing and memcpy so that you only measure the performance of the consumer and not your application.
 * don't use consume_batch(), or use an Nbatch of 1

**Comment by roblos** [comment]
I comment out the per message processing but that didn't influence.
Nbatch=1 made it slower. What do you mean with don't use consume_batch() ? What method do you recommend ?

**Comment by edenhill** [comment]
You can try `rd_kafka_consume_queue()`, but there's probably no difference.

Consumption should generally be a lot faster than producing.
Can you try the examples/rdkafka_performance tool in consumer -C mode to see what message rate it gets?

**Comment by roblos** [comment]
Problem solved. Difference between test and accp environment. accp environment uses mirror maker to sync between 2 kafka envs. That resulted in a slow communication. Thanks for the support.
