### ISSUE TITLE
Producer and consumer use same partition on the same host/pod

### ISSUE THREAD

**Issue by sneerin** [edenhill/librdkafka#2351]
Description
===========
I'm running producer and consumer on the same host, I want message returns to the same host. For that, I need to get consumers current partition for the topic. If it's become rebalanced I also need to update that. What is the best option to do that?

How to reproduce
================
Run producer and consumer on the same host producer a message. It will be sent back with a random consistency result. I need to achieve a request-reply model with rdkafka which is a very generic use case

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `0.11.6`
 - [x] Apache Kafka version: `2.0.0`

**Comment by edenhill** [comment]
Set a rebalance_cb() and you will get callbacks when your consumer receives a new partition assignment (and when it is revoked).
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1575
