### ISSUE TITLE
How to implement self-defined partition assignment strategy when consumer group rebalance happens?

### ISSUE THREAD

**Issue by op-hunter** [edenhill/librdkafka#2354]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
As far as I can see, when consumer group rebalance happens, the new partition assignment strategy is performed by group leader. I want to know whether librdkafka provides related API to set user-defined partition assignment strategy.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by C4ptainCrunch** [comment]
@op-hunter: it looks like it's not possible at the moment (see feature request #2284: _Feature request: Support pluggable partition assignment algorithms for consumer_)
