### ISSUE TITLE
Failed to create new producer: `ssl.ca.location`, and memory-based set_ssl_cert(CERT_CA) are mutually exclusive

### ISSUE THREAD

**Issue by mmanoj** [edenhill/librdkafka#2355]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I was upgraded the latest librdkafka lib and getting below error while run the example code with my old kafka server (Version -kafka_2.11-0.10.0.0)

Failed to create new producer: `ssl.ca.location`, and memory-based set_ssl_cert(CERT_CA) are mutually exclusive

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [x ] Apache Kafka version: `kafka_2.11-0.10.0.0`
 - [ x] librdkafka client configuration: `N/A`
 - [ x] Operating system: `Ubuntu 16.04 LTS`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
What example code are you running and what arguments are you passing?

**Comment by mmanoj** [comment]
/**
 * Simple Apache Kafka producer
 * using the Kafka driver from librdkafka
 * (https://github.com/edenhill/librdkafka)
 */

#include <stdio.h>
#include <signal.h>
#include <string.h>


/* Typical include path would be <librdkafka/rdkafka.h>, but this program
 * is builtin from within the librdkafka source tree and thus differs. */
#include "rdkafka.h"

/*
 * https://github.com/edenhill/librdkafka/issues/853
 * 
 * So you changed the example code to not persist the producer instance but create a new one for each message. I said in an earlier comment that is not the way to do it, you should persist the producer instance and reuse it for each message you send.
 * 
 * The application you changed, rdkafka_example.c, is the example.
Just make sure to only create rd_kafka_t (producer) once and then reuse it for each time you call produce().
 *
 */

static int run = 1;
static rd_kafka_t *rk;

//------------------
rd_kafka_topic_t *rkt;
	 const char *brokers = "localhost:9092,localhost:9093,localhost:9094";
	char mode = 'P';
	 const char *topic = NULL;
	int partition = RD_KAFKA_PARTITION_UA;
	int opt;
	rd_kafka_conf_t *conf;
	rd_kafka_topic_conf_t *topic_conf;
	char errstr[512];
	int64_t start_offset = 0;
        int report_offsets = 0;
	int do_conf_dump = 0;
	char tmp[16];
        int64_t seek_offset = 0;
        int64_t tmp_offset = 0;
	int get_wmarks = 0;

//-----------------

/**
 * @brief Signal termination of program
 */
static void stop (int sig) {
        run = 0;
        fclose(stdin); /* abort fgets() */
}


/**
 * @brief Message delivery report callback.
 *
 * This callback is called exactly once per message, indicating if
 * the message was succesfully delivered
 * (rkmessage->err == RD_KAFKA_RESP_ERR_NO_ERROR) or permanently
 * failed delivery (rkmessage->err != RD_KAFKA_RESP_ERR_NO_ERROR).
 *
 * The callback is triggered from rd_kafka_poll() and executes on
 * the application's thread.
 */
static void dr_msg_cb (rd_kafka_t *rk,
                       const rd_kafka_message_t *rkmessage, void *opaque) {
        if (rkmessage->err)
                fprintf(stderr, "%% Message delivery failed: %s\n",
                        rd_kafka_err2str(rkmessage->err));
        else
                fprintf(stderr,
                        "%% Message delivered (%zd bytes, "
                        "partition %"PRId32")\n",
                        rkmessage->len, rkmessage->partition);

        /* The rkmessage is destroyed automatically by librdkafka */
}



//int main (int argc, char **argv) {
int InitsendMSG(void){
    
   //     rd_kafka_t *rk;         /* Producer instance handle */
   //     rd_kafka_topic_t *rkt;  /* Topic object */
  //      rd_kafka_conf_t *conf;  /* Temporary configuration object */
  //      char errstr[512];       /* librdkafka API error reporting buffer */
        char buf[512];          /* Message value temporary buffer */
    //    const char *brokers;    /* Argument: broker list */
    //    const char *topic;      /* Argument: topic to produce to */

        /*
         * Argument validation
         */
     //   if (argc != 3) {
       //         fprintf(stderr, "%% Usage: %s <broker> <topic>\n", argv[0]);
      //          return 1;
     //   }

    //    brokers = argv[1];
    //    topic   = argv[2];


     
        
        /*
         * Create Kafka client configuration place-holder
         */
        printf("----Before create config---\n");
        conf = rd_kafka_conf_new();
        printf("---After create config-----\n");
        
        /* Tune params for PCRF */
       /* Minimize wait-for-larger-batch delay (since there will be no batching) */
       // rd_kafka_conf_set(conf, "queue.buffering.max.ms", "10", NULL, 0); // 1 sec
        /* Minimize wait-for-socket delay (otherwise you will lose 100ms per message instead just the RTT) */
       // rd_kafka_conf_set(conf, "socket.blocking.max.ms", "1", NULL, 0);
    //    rd_kafka_conf_set(conf, "batch.num.messages", "100000", NULL, 0);
    //    rd_kafka_conf_set(conf, "request.required.acks", "-1", NULL, 0);
    //    rd_kafka_conf_set(conf, "compression.codec", "snappy", NULL, 0);

        /* Set bootstrap broker(s) as a comma-separated list of
         * host or host:port (default port 9092).
         * librdkafka will use the bootstrap brokers to acquire the full
         * set of brokers from the cluster. */
        if (rd_kafka_conf_set(conf, "bootstrap.servers", brokers,
                              errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK) {
                fprintf(stderr, "%s\n", errstr);
                return 1;
        }

        /* Set the delivery report callback.
         * This callback will be called once per message to inform
         * the application if delivery succeeded or failed.
         * See dr_msg_cb() above. */
        rd_kafka_conf_set_dr_msg_cb(conf, dr_msg_cb);

 }//InitsendMSG
 
 static rd_kafka_t *getProducer(void){
        /*
         * Create producer instance.
         *
         * NOTE: rd_kafka_new() takes ownership of the conf object
         *       and the application must not reference it again after
         *       this call.
         */
        rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf, errstr, sizeof(errstr));
        if (!rk) {
                fprintf(stderr,
                        "%% Failed to create new producer: %s\n", errstr);
                return rk;
        }
 }//getProducer
 
 
 void sendMSG1(const char* channel, char *data, rd_kafka_t *rk){//global method call by others

        /* Create topic object that will be reused for each message
         * produced.
         *
         * Both the producer instance (rd_kafka_t) and topic objects (topic_t)
         * are long-lived objects that should be reused as much as possible.
         * 
         */
        topic = channel;//"TEST"; // creating publishing manoj
        rkt = rd_kafka_topic_new(rk, topic, NULL);
        if (!rkt) {
                printf(stderr, "%% Failed to create topic object: %s\n",
                        rd_kafka_err2str(rd_kafka_last_error()));
                rd_kafka_destroy(rk);
               // return 1;
        }

        /* Signal handler for clean shutdown */
        signal(SIGINT, stop);

        fprintf(stderr,
                "%% Type some text and hit enter to produce message\n"
                "%% Or just hit enter to only serve delivery reports\n"
                "%% Press Ctrl-C or Ctrl-D to exit\n");

       // while (run && fgets(buf, sizeof(buf), stdin)) {
                size_t len = strlen(data);

                if (data[len-1] == '\n') /* Remove newline */
                        data[--len] = '\0';

                if (len == 0) {
                        /* Empty line: only serve delivery reports */
                        rd_kafka_poll(rk, 0/*non-blocking */);
                        //continue;
                }

                /*
                 * Send/Produce message.
                 * This is an asynchronous call, on success it will only
                 * enqueue the message on the internal producer queue.
                 * The actual delivery attempts to the broker are handled
                 * by background threads.
                 * The previously registered delivery report callback
                 * (dr_msg_cb) is used to signal back to the application
                 * when the message has been delivered (or failed).
                 */
      //  retry:
                if (rd_kafka_produce(
                            /* Topic object */
                            rkt,
                            /* Use builtin partitioner to select partition*/
                            RD_KAFKA_PARTITION_UA,
                            /* Make a copy of the payload. */
                            RD_KAFKA_MSG_F_COPY,
                            /* Message payload (value) and length */
                            data, len,
                            /* Optional key and its length */
                            NULL, 0,
                            /* Message opaque, provided in
                             * delivery report callback as
                             * msg_opaque. */
                            NULL) == -1) {
                        /**
                         * Failed to *enqueue* message for producing.
                         */
                        fprintf(stderr,
                                "%% Failed to produce to topic %s: %s\n",
                                rd_kafka_topic_name(rkt),
                                rd_kafka_err2str(rd_kafka_last_error()));

                        /* Poll to handle delivery reports */
                        if (rd_kafka_last_error() ==
                            RD_KAFKA_RESP_ERR__QUEUE_FULL) {
                                /* If the internal queue is full, wait for
                                 * messages to be delivered and then retry.
                                 * The internal queue represents both
                                 * messages to be sent and messages that have
                                 * been sent or failed, awaiting their
                                 * delivery report callback to be called.
                                 *
                                 * The internal queue is limited by the
                                 * configuration property
                                 * queue.buffering.max.messages */
                                rd_kafka_poll(rk, 1000/*block for max 1000ms*/);
                               // goto retry;
                        }
                } else {
                        fprintf(stderr, "%% Enqueued message (%zd bytes) "
                                "for topic %s\n",
                                len, rd_kafka_topic_name(rkt));
                }


                /* A producer application should continually serve
                 * the delivery report queue by calling rd_kafka_poll()
                 * at frequent intervals.
                 * Either put the poll call in your main loop, or in a
                 * dedicated thread, or call it after every
                 * rd_kafka_produce() call.
                 * Just make sure that rd_kafka_poll() is still called
                 * during periods where you are not producing any messages
                 * to make sure previously produced messages have their
                 * delivery report callback served (and any other callbacks
                 * you register). */
                rd_kafka_poll(rk, 0/*non-blocking*/);
        


        /* Wait for final messages to be delivered or fail.
         * rd_kafka_flush() is an abstraction over rd_kafka_poll() which
         * waits for all messages to be delivered. */
        fprintf(stderr, "%% Flushing final messages..\n");
        rd_kafka_flush(rk, 10*1000 /* wait for max 10 seconds */);

        /* Destroy topic object */
        rd_kafka_topic_destroy(rkt);
 }

 void kafkaDistroy(rd_kafka_t *rk){
        /* Destroy the producer instance */
        rd_kafka_destroy(rk);

 }

 // This is the main function to test standalone--Manoj
int main()
{
printf("Inside New Main...\n");
InitsendMSG();
sendMSG1("PCRF-DPI","tstMSG",getProducer()); 
kafkaDistroy(getProducer());
    
}

**Comment by mmanoj** [comment]
It's a little modified version from rdkafka_simple_producer.c

**Comment by edenhill** [comment]
you are calling getProducer() multiple times, each one creating a new instance of the producer, but you are only setting up the conf_t object once, and it can't be reused.

**Comment by mmanoj** [comment]
Thanks for the quick advice, I will check to change the code to make one producer and re-use. I will update you the progress.
