### ISSUE TITLE
"consume_cb" configuration property doesn't take effect

### ISSUE THREAD

**Issue by TinkerBell-xdd** [edenhill/librdkafka#2367]
Description
===========
It seems the "consume_cb" configuration doesn't take effect any more in the latest version of librdkafka. And the code example for KafkaConsumer demonstrating the usage of "consume_cb" has been removed.

Is there any solid reason for the incompatible API interface change?

Thanks for your attention.

**Comment by edenhill** [comment]
The consume callback is deprecated and will be removed in the next API version, and it has never worked with the KafkaConsumer afaik.
