### ISSUE TITLE
Message timestamp type is incorrect for produced message

### ISSUE THREAD

**Issue by TinkerBell-xdd** [edenhill/librdkafka#2368]
Description
===========
For topic configured with message.timestamp.type=LogAppendTime, the message timestamp type of produced message is 8, which should be 2.

I noticed there is a potential buggy assignment code in function: rd_kafka_handle_Produce

`rkm->rkm_tstype = RD_KAFKA_MSG_ATTR_LOG_APPEND_TIME;`

It seem the value assigned should be RD_KAFKA_TIMESTAMP_LOG_APPEND_TIME, instead of RD_KAFKA_MSG_ATTR_LOG_APPEND_TIME.

Could you help confirm my suspicion?

Thanks

**Comment by edenhill** [comment]
You are right!
Want to submit a PR?

**Comment by jediMunees** [comment]
Hi @edenhill , Please find the pull request https://github.com/edenhill/librdkafka/pull/2664 for the changes proposed by TinkerBell-xdd.
