### ISSUE TITLE
Fetching last message problem with polling

### ISSUE THREAD

**Issue by nilsocket** [edenhill/librdkafka#2369]
Description
===========
I have created a Consumer, to fetch last message.
But it seems I need to poll two times to get the last message.

Is there any possible reason for this, or am I doing something wrong?

How to reproduce
================
https://gist.github.com/nilsocket/f7cbcacb51eeab3e88d72c1aff2a8b7c.js

minimal consumer (for testing), I wasn't able to receive message, only on second call to `rd_kafka_consumer_poll()`, I was able to fetch the message. 

 - [x] librdkafka version (release number or git tag): `3cf68480d326`
 - [x] Apache Kafka version: `2.2`
 - [x] Operating system: `Ubuntu 18.04`

Thank you.

**Comment by edenhill** [comment]
Maybe it takes more than 1s to connect and start consuming.
Try increasing the poll timeout.

**Comment by nilsocket** [comment]
Yeah, you were right.
Thanks a lot.

**Comment by nilsocket** [comment]
Can I poll in loop, by keeping poll time to be 1s(sometime it's taking more than 2 seconds to respond).
Or am I doing something wrong.
```c
int times = 4;
while(times > 0){
    if (( rkmessage = rd_kafka_consumer_poll(rk, 1000) )){
        break;
    }
times--;
}
```

Thank you.
