### ISSUE TITLE
Provide a Conan Package Recipe

### ISSUE THREAD

**Issue by KepptnKool** [edenhill/librdkafka#2375]
Description
===========
In our project we try retrieve all dependencies as Conan packages. Libraries that are not natively provided as Conan packages are packaged by ourselves.

For LibRdKafka this is not as easy to do. As you can see in this project: https://github.com/ess-dmsc/conan-librdkafka
Some features can not be supported as the build infrastructure is not so easily tricked to use dependencies that are not present in the operating system.

Checklist
=========

Please provide the following information:

 - [x]  v0.11.6
 - [x] Apache Kafka version: does not apply
 - [x] librdkafka client configuration: does not apply
 - [x] Operating system: ubuntu 18.04, conan 1.16.1
 - [x] Provide logs : none
 - [x] Provide broker log excerpts : none
 - [x] Critical issue: no

**Comment by edenhill** [comment]
You might want to try out `./configure --install-deps --source-deps-only` to have librdkafka bootstrap its dependencies.

There are no plans for us to provide conan packages.

**Comment by KepptnKool** [comment]
Thank you for replying.

Actually that ./configure script only does what conan would do if you would pull your dependencies with it :-(. In our case it doesn't really ease the packaging because those libraries are not tracked as transitive conan dependencies.

I suggest to look into that stuff in the future.
