### ISSUE TITLE
[Question] Refresh SASL key refresh failed: Failed to execute kinit

### ISSUE THREAD

**Issue by roygao2017** [edenhill/librdkafka#2381]
i can't confirm it is a permission issue or librdkafka issue, appreciate if you can give some advice. thanks.

My program use SASL_SSL protocol to connect kafka, it prints the following ERR when start
SASL key refresh failed: Failed to execute kinit -S "kafka/dal01s-gen-kaf-brk001.com" -k -t "constgops.keytab" constgops@XXX.COM".

i can execute the command success manually and some messages can feed to kafka success.
Beside that, i add some code to call system(cmd) in rd_kafka_sasl_cyrus_kinit_refresh(), find it failed too, even i call system("pwd"). but it's sucess when i call same cmd in rd_kafka_new().

i try to add and remove -R in sasl.kerberos.kinit.cmd, it always print the ERROR.

also, i add debug=security in client configuration, the log is:
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Broker SSL certificate verified
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Auth in state APIVERSION_QUERY (handshake supported)
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Broker supported SASL mechanisms: PLAIN,GSSAPI
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Auth in state AUTH_HANDSHAKE (handshake supported)
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Initializing SASL client: service name kafka, hostname dal01s-gen-kaf-brk001.XXX.com, mechanisms GSSAPI, provider Cyrus
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Refreshing SASL keys with command: kinit -S "kafka/dal01s-gen-kaf-brk001.XXX.com" -k -t "constgops.keytab" constgops@XXX.COM
Thu Jun 20 01:44:26 2019 thread 22284 ERRO KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: SASL key refresh failed: Failed to execute kinit -S "kafka/dal01s-gen-kaf-brk001.XXX.com" -k -t "constgops.keytab" constgops@XXX.COM
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: My supported SASL mechanisms: ANONYMOUS PLAIN GSSAPI LOGIN EXTERNAL
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Send SASL frame to broker (1834 bytes)
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Received SASL frame from broker (112 bytes)
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: CB_CANON: flags 0x3, "constgops@XXX.COM" @ "(null)": returning "constgops@XXX.COM"
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Send SASL frame to broker (0 bytes)
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Received SASL frame from broker (36 bytes)
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Send SASL frame to broker (32 bytes)
Thu Jun 20 01:44:26 2019 thread 22284 DEBG KAFKA KAFKA ra_kafka_producer.c-217-ra_kafka_db_sync_log : ra_kafka_db_sync_log: rdkafka#producer-1: [thrd:sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/boots]: sasl_ssl://dal01s-gen-kaf-brk001.XXX.com:9093/bootstrap: Authenticated as constgops@XXX.COM using GSSAPI (gssapiv2)

client configration:
compression.codec = snappy
queue.buffering.max.messages = 100000
queue.buffering.max.ms = 5000
batch.num.messages = 10000
message.send.max.retries = 2
log.connection.close = false
debug=security

#security.protocol = ssl
ssl.certificate.location = TrustedRoot.crt
#ssl.ca.location = TrustedRoot.crt

ssl.key.password = changeit
ssl.keystore.password = changeit

security.protocol=SASL_SSL
acks=all
sasl.kerberos.keytab=constgops.keytab
sasl.kerberos.principal=constgops@XXX.COM
sasl.kerberos.service.name=kafka
sasl.mechanism=GSSAPI
#sasl.kerberos.min.time.before.relogin = 86400000
#sasl.kerberos.min.time.before.relogin = 0
#sasl.kerberos.kinit.cmd=/usr/bin/kinit -S %{sasl.kerberos.service.name}/%{broker.name} -t %{sasl.kerberos.keytab} -k %{sasl.kerberos.principal}

How to reproduce
================
1. compile my program use the latest released.
2. set configuration as above, and set correct broker port 9093.
3. start my c program.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v1.01>`
 - [x] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `<compression.codec = nappy,queue.buffering.max.messages = 100000,queue.buffering.max.ms = 5000,batch.num.messages = 10000,message.send.max.retries = 2,log.connection.close = false,debug=security,ssl.certificate.location = TrustedRoot.crt,ssl.key.password = changeit,ssl.keystore.password = changeit,security.protocol=SASL_SSL,acks=all,sasl.kerberos.keytab=constgops.keytab,sasl.kerberos.principal=constgops@XXX.COM,sasl.kerberos.service.name=kafka,sasl.mechanism=GSSAPI,
#sasl.kerberos.kinit.cmd=/usr/bin/kinit -S %{sasl.kerberos.service.name}/%{broker.name} -t %{sasl.kerberos.keytab} -k %{sasl.kerberos.principal}>`
 - [x] Operating system: `<Linux 2.6.32-431.1.2.el6.x86_64>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts
 - [ ] Critical issue

**Comment by roygao2017** [comment]
there are five brokers on kafka cluster, one producer on client side, and there are 10 topics.
i find the client try to connect another broker in broker list even if configure only one broker in my app configuration.
i use klist, there is only one broker in service principal.
Ticket cache: FILE:/tmp/krb5cc_28040
Default principal: constgops@XXX.COM
Valid starting     Expires            Service principal
06/25/19 21:40:53  06/26/19 07:40:53  kafka/dal01s-gen-kaf-brk003.xxx.com@XXX.COM

as i said before, there are five brokers, and my app connect more of them when init topic even if i configure one broker only.  but only one broker in kerberos cache file.

i think it cause SASL key refresh fail. 
how can i fix it? thanks.
i replace some information with XXX, i can make sure they are correct.

**Comment by roygao2017** [comment]
i checked it, find the system(cmd) retrun -1 with "errno=10(No child processes)". so i want to know
does the librdkafka change the default process for signal "SIGCHLD" in internal function, since i can call system(cmd) success in public function of librdkafka.

**Comment by edenhill** [comment]
I'm not really sure what is going on here, haven't seen any issues with calling system() from librdkafka threads.
The internal librdkafka threads do block all signals though.

**Comment by roygao2017** [comment]
i find it was changed by another process in my app, it's OK when i disable it. thanks.

**Comment by hannip** [comment]
For those running into this same issue you may be interesting in this pull request.
https://github.com/edenhill/librdkafka/pull/2421
