### ISSUE TITLE
assert fail in 

### ISSUE THREAD

**Issue by jcalcote** [edenhill/librdkafka#2384]
Hi Magnus,

We're seeing this assert failure in version librdkafka 0.11.4 (-1.el7 - CentOS 7.6). It happens intermittently and we don't know how to reproduce it. Can you please help us figure out why it's happening and what it means? Perhaps we're doing something to cause it so any information you can provide that will help us understand what CAN cause it would be helpful.

Thanks!
John

Description
===========
```
Program terminated with signal 6, Aborted.
#0  0x00007f7d9e64b207 in raise () from /lib64/libc.so.6
#0  0x00007f7d9e64b207 in raise () from /lib64/libc.so.6
#1  0x00007f7d9e64c8f8 in abort () from /lib64/libc.so.6
#2  0x00007f7d9e644026 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f7d9e6440d2 in __assert_fail () from /lib64/libc.so.6
#4  0x00007f7d9c7a1b12 in rd_kafka_topic_destroy_final () from /lib64/librdkafka.so.1
#5  0x00007f7d9c79ef70 in rd_kafka_msg_destroy () from /lib64/librdkafka.so.1
#6  0x00007f7d9c7890d4 in rd_kafka_poll_cb () from /lib64/librdkafka.so.1
#7  0x00007f7d9c7b4c93 in rd_kafka_q_serve () from /lib64/librdkafka.so.1
```

How to reproduce
================
intermittent - unknown reproduction steps

Checklist
=========
 - [x] librdkafka version: librdkafka-0.11.4-1.el7.x86_64
 - [x] Apache Kafka version: kafka-0.11.0.1-12.el7.noarch
 - [x] librdkafka client configuration: 
	rd_kafka_conf_set(conf, "queue.buffering.max.messages", "500000", NULL, 0);
	rd_kafka_conf_set(conf, "message.send.max.retries", "3", NULL, 0);
	rd_kafka_conf_set(conf, "retry.backoff.ms", "500", NULL, 0);
	rd_kafka_conf_set(conf, "api.version.request", "false", NULL, 0);
	rd_kafka_conf_set(conf, "broker.version.fallback", vstr, NULL, 0);
	rd_kafka_conf_set(conf, "security.protocol", get_kafka_security_protocol(), NULL, 0);
	rd_kafka_conf_set(conf, "ssl.ca.location", get_kafka_broker_cert_path(), NULL, 0);
	rd_kafka_conf_set(conf, "ssl.certificate.location", get_kafka_client_cert_path(), NULL, 0);
	rd_kafka_conf_set(conf, "ssl.key.location", get_kafka_client_key_path(), NULL, 0);
	rd_kafka_conf_set(conf, "ssl.key.password", get_kafka_key_password(), NULL, 0);
	rd_kafka_conf_set_log_cb(conf, pd_kafka_logger);
 - [x] Operating system: CentOS Linux release 7.6.1810 (Core)
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Could be a reference counting issue, is anything printed on the console/stderr when this happens, preferably an assert message?

0.11.4 is old, I suggest upgrading to the latest release, v1.1.0.
