### ISSUE TITLE
Question: High Level Consumer, queue per topic

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#2387]
Hello Magnus!

Hopefully easy one for you. It is my understanding that the high level consumer does not provide an interface to poll a given topic?

My scenario that i want to achieve is:
1.Single Consumer instance per process. Has to be High Level so that things like rebalances are handled for me.
2.The process subscribes to 2 topics, one partition each.
3.Each thread polls its own topic, so that message from one topic does not block the other one.
4.Aim is to only retrieve messages from the brokers as the processing thread’s rate.

Am i right that in order to satisfy all of the above, i need the low level consumer?

**Comment by MaximGurschi** [comment]
Ok i found this interface: 

1. rd_kafka_queue_new
2.rd_kafka_consume_start_queue
3.rd_kafka_consume_queue

, can i use this with the high level consumer?

**Comment by MaximGurschi** [comment]
Does anyone know, are those methods just for the Legacy Consumer?

**Comment by edenhill** [comment]
You'll want to do this:

In your rebalance callback when you get a new assignment, for each assigned partition, you get that partition's queue (which is by default forwarded to the main consumer_poll() queue): `rd_kafka_queue_get_partition()`.
For each such queue, remove the forwarding (to the main queue): `rd_kafka_queue_forward(part_queue, NULL)`.
Then pass this queue to consumption thread for that partition.

You will still need to call consumer_poll() in your main thread to serve rebalance events, etc, but it will not have any messages any more.

**Comment by MaximGurschi** [comment]
Thank you Magnus! That makes sense.

Couple of detail questions:
1. If one of these queues i create get filled up, and i do not consume from it, will that prevent other message queues or the main queue from moving along?
2. When should i call rd_kafka_queue_destroy for the reference i get back? Immediately before i destroy the consumer handle? Basically what is the correct order to release this reference?

**Comment by edenhill** [comment]
1. No, when the queues are separated (no longer forwarded) the queue threshold configs are enforced per queue rather than for the consumer as a whole.
 2. When you no longer need it, but no later than just prior to rd_kafka_destroy().

**Comment by MaximGurschi** [comment]
Thanks Magnus!
