### ISSUE TITLE
Flushing pending commits without consuming more messages

### ISSUE THREAD

**Issue by ajwootto** [edenhill/librdkafka#2388]
Hello,

I'm trying to implement a consumer which manages offset commits manually. When the consumer is rebalanced or is about to shut down, I attempt to cleanly flush all the messages that are in the buffer. I do this by tracking the offsets that I've received so far, and waiting for the commit_cb to be called with those offsets after I process & commit them. I also stop calling consume() in order to avoid receiving new messages while a flush is on-going. However, it seems the only way to get a commit request to actually be sent to the broker is to call consume(). In this scenario, how can I ensure that my commit requests get sent without having to consume more messages in the middle of a rebalance or shutdown? Is it safe to consume messages with the consume() call and then just throw them away? What's the right approach for this? Any help is appreciated.

Thanks!

**Comment by edenhill** [comment]
Upon rebalance the fetchers will stop and the pre-fetched messages in local queue will be purged, so you don't need to do anything special, you should not see any new messages from consume() until you get a new assignment.
As for the commit, it will be done in the background, but you need to call poll() to trigger the commit_cb.

The typical approach when using custom offset commits is something like:

```c
void my_rebalance_cb (...) {

    if (err == .. __ASSIGN_PARTITIONS) {
        rd_kafka_assign(assignment);
    } else if (err == .._REVOKE_PARTITIONS) {
       rd_kafka_commit(rk, NULL, 0/*sync*/); // synchronous commit
   }
```
