### ISSUE TITLE
 GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found (filename: /tmp/krb5cc_xxx))))

### ISSUE THREAD

**Issue by mtk0104** [edenhill/librdkafka#2391]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi Eden
I have a consumer application written in librdkafka. It shows the following error when I try to connect to the topic.

I enabled debug= “security” and got the logs below. 

_%7|1561639951.626|SASL|rdkafka#consumer-1| [thrd:app]: Selected provider Cyrus for SASL mechanism GSSAPI
%7|1561639951.627|SSL|rdkafka#consumer-1| [thrd:app]: Loading CA certificate(s) from file /./././xyz.cer
Subscribed to abcdefgh, waiting for assignment and messages...
Press Ctrl-C to exit.
%7|1561639970.634|SSLVERIFY|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/bootstrap: Broker SSL certificate verified
%7|1561639970.634|AUTH|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/bootstrap: Auth in state CONNECT (handshake not supported)
%7|1561639970.634|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/bootstrap: Initializing SASL client: service name kafka, hostname xxx.com, mechanisms GSSAPI, provider Cyrus
%7|1561639970.634|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/bootstrap: Refreshing SASL keys with command: kinit -S "kafka/xxx.com" -k -t "/home/pkn0app0/kn00/myketab.keytab" mydev@xyz.com
%7|1561639970.636|SSLVERIFY|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: Broker SSL certificate verified
%7|1561639970.636|AUTH|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: Auth in state CONNECT (handshake not supported)
%7|1561639970.636|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: Initializing SASL client: service name kafka, hostname yyy.com, mechanisms GSSAPI, provider Cyrus
%7|1561639970.636|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: Refreshing SASL keys with command: kinit -S "kafka/yyy.com" -k -t "/home/pkn0app0/kn00/myketab.keytab" mydev@xyz.com
%7|1561639970.637|SSLVERIFY|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: Broker SSL certificate verified
%7|1561639970.637|AUTH|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: Auth in state CONNECT (handshake not supported)
%7|1561639970.637|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: Initializing SASL client: service name kafka, hostname zzz.com, mechanisms GSSAPI, provider Cyrus
%7|1561639970.637|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: Refreshing SASL keys with command: kinit -S "kafka/zzz.com" -k -t "/home/pkn0app0/kn00/myketab.keytab" mydev@xyz.com
%7|1561639970.649|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/bootstrap: SASL key refreshed
%7|1561639970.650|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/bootstrap: My supported SASL mechanisms: GSS-SPNEGO GSSAPI EXTERNAL ANONYMOUS
%7|1561639970.680|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: SASL key refreshed
%7|1561639970.680|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: My supported SASL mechanisms: GSS-SPNEGO GSSAPI EXTERNAL ANONYMOUS
%7|1561639970.683|SSLVERIFY|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: Broker SSL certificate verified
%7|1561639970.683|AUTH|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: Auth in state CONNECT (handshake not supported)
%7|1561639970.683|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: Initializing SASL client: service name kafka, hostname www.com, mechanisms GSSAPI, provider Cyrus
%7|1561639970.683|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: Refreshing SASL keys with command: kinit -S "kafka/www.com" -k -t "/home/pkn0app0/kn00/myketab.keytab" mydev@xyz.com
%7|1561639970.684|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: Send SASL frame to broker (1380 bytes)
%2|1561639970.684|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found (filename: /tmp/krb5cc_334201027))
%3|1561639970.684|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found (filename: /tmp/krb5cc_334201027))
%3|1561639970.684|ERROR|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Matching credential not found (filename: /tmp/krb5cc_334201027))
%7|1561639970.696|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: SASL key refreshed
%7|1561639970.696|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: My supported SASL mechanisms: GSS-SPNEGO GSSAPI EXTERNAL ANONYMOUS
%7|1561639970.699|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: Send SASL frame to broker (1412 bytes)
%7|1561639970.711|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: SASL key refreshed
%7|1561639970.711|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: My supported SASL mechanisms: GSS-SPNEGO GSSAPI EXTERNAL ANONYMOUS
%7|1561639970.713|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: Send SASL frame to broker (1380 bytes)
%7|1561639970.725|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: Received SASL frame from broker (108 bytes)
%7|1561639970.727|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: CB_CANON: flags 0x3, "mydev@xyz.com" @ "(null)": returning "mydev@xyz.com"
%7|1561639970.727|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: Send SASL frame to broker (0 bytes)
%7|1561639970.727|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: Received SASL frame from broker (54 bytes)
%7|1561639970.728|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: Send SASL frame to broker (50 bytes)
%7|1561639970.728|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://yyy.com:9092/bootstrap]: sasl_ssl://yyy.com:9092/bootstrap: Authenticated as mydev@xyz.com using GSSAPI (gssapiv2)
%7|1561639970.740|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: Received SASL frame from broker (107 bytes)
%7|1561639970.742|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: CB_CANON: flags 0x3, "mydev@xyz.com" @ "(null)": returning "mydev@xyz.com"
%7|1561639970.742|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: Send SASL frame to broker (0 bytes)
%7|1561639970.743|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: Received SASL frame from broker (54 bytes)
%7|1561639970.743|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: Send SASL frame to broker (50 bytes)
%7|1561639970.743|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://zzz.com:9092/bootstrap]: sasl_ssl://zzz.com:9092/bootstrap: Authenticated as mydev@xyz.com using GSSAPI (gssapiv2)
%7|1561639970.755|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: Received SASL frame from broker (108 bytes)
%7|1561639970.757|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: CB_CANON: flags 0x3, "mydev@xyz.com" @ "(null)": returning "mydev@xyz.com"
%7|1561639970.757|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: Send SASL frame to broker (0 bytes)
%7|1561639970.758|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: Received SASL frame from broker (54 bytes)
%7|1561639970.758|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: Send SASL frame to broker (50 bytes)
%7|1561639970.758|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://www.com:9092/bootstrap]: sasl_ssl://www.com:9092/bootstrap: Authenticated as mydev@xyz.com using GSSAPI (gssapiv2)
%7|1561639971.716|SSLVERIFY|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: Broker SSL certificate verified
%7|1561639971.716|AUTH|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: Auth in state CONNECT (handshake not supported)
%7|1561639971.716|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: Initializing SASL client: service name kafka, hostname xxx.com, mechanisms GSSAPI, provider Cyrus
%7|1561639971.716|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: Refreshing SASL keys with command: kinit -S "kafka/xxx.com" -k -t "/home/pkn0app0/kn00/myketab.keytab" mydev@xyz.com
%7|1561639971.739|SASLREFRESH|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: SASL key refreshed
%7|1561639971.739|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: My supported SASL mechanisms: GSS-SPNEGO GSSAPI EXTERNAL ANONYMOUS
%7|1561639971.741|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: Send SASL frame to broker (1380 bytes)
%7|1561639971.782|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: Received SASL frame from broker (108 bytes)
%7|1561639971.784|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: CB_CANON: flags 0x3, "mydev@xyz.com" @ "(null)": returning "mydev@xyz.com"
%7|1561639971.784|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: Send SASL frame to broker (0 bytes)
%7|1561639971.784|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: Received SASL frame from broker (54 bytes)
%7|1561639971.784|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: Send SASL frame to broker (50 bytes)
%7|1561639971.785|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://xxx.com:9092/bootstrap]: sasl_ssl://xxx.com:9092/4: Authenticated as mydev@xyz.com using GSSAPI (gssapiv2)_

I have noticed that if I do a kinit a tmp/krbcc_xx gets created . But my code is trying to access a different tmp/krbcc_xx file. 

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [x] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by mtk0104** [comment]
**librdkafka consumer configurations:**
char * brokers = "www.com:9092,xxx.com:9092,yyy.com:9092,zzz.com:9092";
rd_kafka_conf_set(Kafka_conf, "group.id", consumer_group, NULL, 0);
rd_kafka_conf_set(Kafka_conf, "auto.offset.reset", "latest", NULL, 0);
rd_kafka_conf_set(Kafka_conf, "enable.partition.eof", "false", NULL, 0);
rd_kafka_conf_set(Kafka_conf, "sasl.kerberos.principal", " mydev@xyz.com", NULL, 0);
rd_kafka_conf_set(Kafka_conf, "sasl.kerberos.keytab", "/./././mykeytab.keytab", NULL, 0);
rd_kafka_conf_set(Kafka_conf, "bootstrap.servers", brokers, NULL, 0);
rd_kafka_conf_set(Kafka_conf, "security.protocol", "sasl_ssl", NULL, 0);// "sasl_ssl"SASL_PLAINTEXT
rd_kafka_conf_set(Kafka_conf, "sasl.kerberos.service.name", "kafka", NULL, 0);
rd_kafka_conf_set(Kafka_conf, "ssl.ca.location", "/./././xyz.cer", NULL, 0);
**Operating system** : Red Hat Linux

**Comment by edenhill** [comment]
Please fill out the checklist.

**Comment by mtk0104** [comment]
**librdkafka version**:0.11.4
**kafka version** : 2.0.1
**librdkafka consumer configurations:**
char * brokers = "www.com:9092,xxx.com:9092,yyy.com:9092,zzz.com:9092";
rd_kafka_conf_set(Kafka_conf, "group.id", consumer_group, NULL, 0);
rd_kafka_conf_set(Kafka_conf, "auto.offset.reset", "latest", NULL, 0);
rd_kafka_conf_set(Kafka_conf, "enable.partition.eof", "false", NULL, 0);
rd_kafka_conf_set(Kafka_conf, "sasl.kerberos.principal", " mydev@xyz.com", NULL, 0);
rd_kafka_conf_set(Kafka_conf, "sasl.kerberos.keytab", "/./././mykeytab.keytab", NULL, 0);
rd_kafka_conf_set(Kafka_conf, "bootstrap.servers", brokers, NULL, 0);
rd_kafka_conf_set(Kafka_conf, "security.protocol", "sasl_ssl", NULL, 0);
rd_kafka_conf_set(Kafka_conf, "sasl.kerberos.service.name", "kafka", NULL, 0);
rd_kafka_conf_set(Kafka_conf, "ssl.ca.location", "/./././xyz.cer", NULL, 0);
**Operating system** : RHEL

**Comment by edenhill** [comment]
There's been fixes around TKT acquisition and refresh in librdkafka v1.1.0, I suggest upgrading

**Comment by jvarugh** [comment]
Any update on a resolution to this? I am getting the exact same error. 

librdkafka: v1.2.2 

kinit will success and create the cache file (/tmp/krb5cc_[uid]) but then immediately throws this error. 

Thanks,
