### ISSUE TITLE
KafkaConsumer does not receive ERR__PARTITION_EOF

### ISSUE THREAD

**Issue by ngrande** [edenhill/librdkafka#2397]
Description
===========
Consuming with the `KafkaConsumer` class misses the `ERR__PARTITION_EOF` error status, one does not know when the end of the topic / partition is reached.
I did not check the whole `KafkaConsumer` C code yet but so far all references i have seen with `ERR__PARTITION_EOF` were in the context of the `simple consumer`. How is a `KafkaConsumer` expected to know the end of the topic?

I also tried the `consume_cb` approach (here i have to call `poll(ms)` on the `KafkaConsumer` instead of `consume(ms)` - documentation says this must not be done, just fiddling around right now...). I am able to consume messages but never receive the EOF `err()`.

Consuming the same topic with kafkacat brings up the expected EOF in the `consume_cb` function, but unfortunately i am unable to recreate this with my own code. May i miss here something?

How to reproduce
================
start consuming a topic with a `KafkaConsumer` object and wait till you reach the end (either you know what your latest log entry is or you will see it by not receiving new messages...)

Checklist
=========

 - [x] librdkafka version (release number or git tag): `1.1.0`
 - [x] Apache Kafka version: `1.1.1`
 - [x] librdkafka client configuration: `defaults`
 - [x] Operating system: `arch-linux`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
PARTITION_EOF is disabled by default since v1.0.0, see `enable.partition.eof`

**Comment by ngrande** [comment]
thanks for clarifying. May i ask why this is off by default?

**Comment by edenhill** [comment]
It simplifies the common consumer case that don't care about partition eofs.
