### ISSUE TITLE
Question: can we know the Producer's local message queue size?

### ISSUE THREAD

**Issue by ossberyl** [edenhill/librdkafka#2400]
Hi all,

In our application, we want to have logic as: before producing to Kafka, check if the current local message queue size has exceeds certain size limit(smaller than **queue.buffering.max.kbytes**), if yes, we will slow down producing speed.

We only produce to one certain Topic per Producer, and might not use the **RK_MSG_BLOCK** flag to block the thread when local message queue is full as we don't want to block the thread.

Is it possible to check the message queue size(either for all Topics or certain Topic is good) for a Producer?

Thanks in advance!

**Comment by edenhill** [comment]
Extract `msg_cnt` from statistics (or the per-partition counterpart)
https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

**Comment by ossberyl** [comment]
Thanks for reply.

But there would be gap between last statistic result and real current message queue size, and it costs to extract both **msg_size**(mightbe this one for our case) frequently from a long statistic string.

Btw, if the number of messages has exceeds "queue.buffering.max.messages", and even though the queue size is still smaller than "queue.buffering.max.kbytes", will producer still report "Queue Full" error?

And is that possible to expose the apis to get message queue size and get number of messages in queue?

**Comment by edenhill** [comment]
You can also use `outq_len()` to get the number of messages in-queue/in-flight.
Do note that this len also includes outstanding events on the poll queue.
