### ISSUE TITLE
Any possibility consumers in one consumer group consume the same partition?

### ISSUE THREAD

**Issue by lxyscls** [edenhill/librdkafka#2402]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have a topic which has been devided into 40 partitions, and have a consumer group about 20 consumers. The consumer processes are running in docker swarm.
I found that two consumers in this group share one partition's message nearly at the same time.

How to reproduce
================
Because this is in the customer's envrionment, we can't do any reproduce work.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.3
 - [x] Apache Kafka version: 0.10.2.1
 - [x] librdkafka client configuration: enable.auto.offset.store:0
 - [x] Operating system: CentOS in docker swarm
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

Is there any way to find the consumer groups of one topic? I only find the commands to list all consumer groups and describe one consumer group.  

We are sure that those two processes consumed the same partition in the log of "consume callback“, and we don't find any rebalance information between the consumption interval.

**Comment by edenhill** [comment]
Try setting `debug=consumer` to see what and when assignments are changed.

**Comment by lxyscls** [comment]
> 
> 
> Try setting `debug=consumer` to see what and when assignments are changed.

ok, we will try it.

Btw, from the docker logs, it seems that two consumers consumed the same partition at the same time.

> 2019-07-09T05:55:32.273852281Z [ CMA_DATA ] Read msg at partition 19 offset 639157
> 2019-07-09T05:55:32.275912048Z [ CMA_DATA ] Read msg at partition 19 offset 639157

So I think there is no assignment change.

One more question, is there any command to show all consumer group of one topic? I doubted that those two conumsers used two group names. So I need some means to check.

**Comment by lxyscls** [comment]
@edenhill 
Because the cluster is in customer's envrionment, so it is hard to add some debug flag.
Btw, we have done some packet captures, and found that there were two consumers sent offsetcommit request for two same partitions.
![图片](https://user-images.githubusercontent.com/4469678/61100560-33f29c00-a499-11e9-9b09-4fc6b9e91172.png)
![图片](https://user-images.githubusercontent.com/4469678/61100587-4bca2000-a499-11e9-8e9b-825a14b0e687.png)

Would you please give us more suggestions about how to check the captures? Thank you very much.

**Comment by edenhill** [comment]
The packet captures does not show you why there are two consumers committing the same partition, you will need to use debug=cgrp for that.
We also highly recommend that you upgrade the client, v0.11.3 is old and unsupported.
