### ISSUE TITLE
Is there any workaround about such connectedness issue?

### ISSUE THREAD

**Issue by lxyscls** [edenhill/librdkafka#2404]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have a Kafka cluster behind the NAT. Today, one host misses an iptables rule. So there are something wrong between them.
My producer continued to send message to this host(forwarded by NAT) and failed. But from the meta info, it knows that this host is still alive.

So, is there any workaround?

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.3
 - [x] Apache Kafka version: 0.10.2.1
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue: Cluster behind NAT

**Comment by edenhill** [comment]
1. upgrade librdkafka, v0.11.3 is really old. Use latest version v1.1.0
2. provide logs
3. see `socket.keepalive.enable` configuration option  and http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html

socket.keepalive.enable
--
