### ISSUE TITLE
Broker: Message format on broker does not support request

### ISSUE THREAD

**Issue by harshadvichare** [edenhill/librdkafka#2408]
**Error: Broker: Message format on broker does not support request**

Description
===========
Once we have updated librdkafka to 1.0.0 versions accordingly step mentioned in document. While producing message we are getting the following error message.

Broker: Message format on broker does not support request

Configuration
============
retries = 3
acks = all
retry.backoff.ms = 100
max.in.flight.requests.per.connection = 1
enable.idempotence = true
broker version = 0.11.0.0

Kafka Logs
================
2019-07-11T10:29:50,989 [myid:] - ERROR [kafka-request-handler-6:Logging$class@105] - [Replica Manager on Broker 1]: Error processing append operation on partition sem-test-topic-1
org.apache.kafka.common.errors.UnsupportedForMessageFormatException: Idempotent records cannot be used with magic version 1
2019-07-11T10:29:51,001 [myid:] - ERROR [kafka-request-handler-1:Logging$class@105] - [Replica Manager on Broker 1]: Error processing append operation on partition sem-test-topic-4
org.apache.kafka.common.errors.UnsupportedForMessageFormatException: Idempotent records cannot be used with magic version 1
2019-07-11T10:30:43,935 [myid:] - ERROR [kafka-request-handler-7:Logging$class@105] - [Replica Manager on Broker 1]: Error processing append operation on partition sem-test-topic-1
org.apache.kafka.common.errors.UnsupportedForMessageFormatException: Idempotent records cannot be used with magic version 1
2019-07-11T10:30:43,944 [myid:] - ERROR [kafka-request-handler-5:Logging$class@105] - [Replica Manager on Broker 1]: Error processing append operation on partition sem-test-topic-4
org.apache.kafka.common.errors.UnsupportedForMessageFormatException: Idempotent records cannot be used with magic version 1

Checklist
=========

Please provide the following information:

 - [x] librdkafka version :1.0.0
 - [x] kafka client : 0.11.0.0
 - [x] Os version: Centos 7.xx

**Comment by edenhill** [comment]
What is your broker version?

**Comment by edenhill** [comment]
And please reproduce with `debug=protocol,msg,feature` and provide the logs from when this happens.

**Comment by harshadvichare** [comment]
For this do I need to change anything in kafka configuration and restart it

**Comment by harshadvichare** [comment]
@edenhill  Any update on this

**Comment by edenhill** [comment]
Do you see anything interesting in the broker logs when you get this error on the client?
I'm guessing there is a message downgrade problem.

**Comment by polomarcus** [comment]
hi @harshadvichare ,

If you want to use idempotence, your topics' config for `message.format.version` should be => 0.11

> If the message format of the destination topic is not upgraded to 0.11.0.0, idempotent and transactional produce requests will fail with an UnsupportedForMessageFormatException error. If this is encountered during a transaction, it is possible to abort and continue. But note that future sends to the same topic will continue receiving the same exception until the topic is upgraded. 

source: https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/producer/KafkaProducer.html


cheers
