### ISSUE TITLE
Consumer terminates sproadicly

### ISSUE THREAD

**Issue by neural-wetware** [edenhill/librdkafka#2410]
Description
===========
We run our consumer for some time and it seems to terminate. I can't figure out why this is happening. See snipped below.

I'm not sure if this is a bug or just my ignorance on the proper configuration for kafka clients. Sorry in advance if it is the later.

Its a PHP script using https://github.com/arnaud-lb/php-rdkafka with below config. It's run in docker container (debian 9.4) inside AWS VPC. it connects to an AWS Confluent service. let it run for a while and it terminates sporadically.

```
...
%7|1562752739.499|STATE|rdkafka#consumer-1| [thrd:sasl_ssl://cp69.ap-southeast-2.aws.confluent.cloud:9092/bootstr]: sasl_ssl://cp69.ap-southeast-2.aws.confluent.cloud:9092/bootstrap: Broker changed state DOWN -> INIT
%7|1562752739.499|BROADCAST|rdkafka#consumer-1| [thrd:sasl_ssl://cp69.ap-southeast-2.aws.confluent.cloud:9092/bootstr]: Broadcasting state change
%7|1562752739.499|SEND|rdkafka#consumer-1| [thrd:sasl_ssl://b7-cp69.ap-southeast-2.aws.confluent.cloud:9092/7]: sasl_ssl://b7-cp69.ap-southeast-2.aws.confluent.cloud:9092/7: Sent MetadataRequest (v2, 38 bytes @ 0, CorrId 75098)
%7|1562752739.499|CGRPCOORD|rdkafka#consumer-1| [thrd:main]: sasl_ssl://cp69.ap-southeast-2.aws.confluent.cloud:9092/bootstrap: Group "fb1nodegroup" GroupCoordinator response error: Local: Broker transport failure
%7|1562752739.499|CLOSE|rdkafka#consumer-1| [thrd:app]: Closing consumer
%7|1562752739.499|CLOSE|rdkafka#consumer-1| [thrd:app]: Waiting for close events
%7|1562752739.499|CGRPSTATE|rdkafka#consumer-1| [thrd:main]: Group "fb1nodegroup" changed state up -> query-coord (v4, join-state started)
%7|1562752739.500|BROADCAST|rdkafka#consumer-1| [thrd:main]: Broadcasting state change
%7|1562752739.500|CGRPOP|rdkafka#consumer-1| [thrd:main]: Group "fb1nodegroup" received op TERMINATE (v0) in state query-coord (join state started, v4 vs 0)
%7|1562752739.500|CGRPTERM|rdkafka#consumer-1| [thrd:main]: Terminating group "fb1nodegroup" in state query-coord with 12 partition(s)
%7|1562752739.500|UNSUBSCRIBE|rdkafka#consumer-1| [thrd:main]: Group "fb1nodegroup": unsubscribe from current subscription of 1 topics (leave group=yes, join state started, v4)
%7|1562752739.500|SUBSCRIPTION|rdkafka#consumer-1| [thrd:main]: Group "fb1nodegroup": clearing subscribed topics list (1)
%7|1562752739.500|SUBSCRIPTION|rdkafka#consumer-1| [thrd:main]: Group "fb1nodegroup": effective subscription list changed from 1 to 0 topic(s):
%7|1562752739.500|GRPLEADER|rdkafka#consumer-1| [thrd:main]: Group "fb1nodegroup": resetting group leader info: unsubscribe
%7|1562752739.500|REBALANCE|rdkafka#consumer-1| [thrd:main]: Group "fb1nodegroup" is rebalancing in state query-coord (join-state started) with assignment: unsubscribe
%7|1562752739.500|PAUSE|rdkafka#consumer-1| [thrd:main]: Library pausing 12 partition(s)
...
```

The `response error: Local: Broker transport failure` seem suspect, but this happens a few times as the process is running, including the first minutes of execution.

How to reproduce
================

This happens when running our container inside AWS VPC, but oddly seems to run indefinitely from my workstation (though maybe I didn't' wait long enough; 4 hours). In either case I'm connecting to our AWS Confluent broker.

No messages are produced to the topic.

After some time, minutes or hours, it terminates.

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.1.0
 - [x] Apache Kafka version: 2.?
 - [x] librdkafka client configuration:
```php
$conf->set('group.id', 'fb1nodegroup');
$conf->set('metadata.broker.list', getenv('KAFKA_BROKERS'));
$conf->set('api.version.request', 'true');
$conf->set('sasl.username', $user);
$conf->set('sasl.password', $pass);
$conf->set('security.protocol', 'SASL_SSL');
$conf->set('sasl.mechanisms', 'PLAIN');
$conf->set('ssl.ca.location', '/etc/ssl/certs/ca-certificates.crt');

$topicConf->set('auto.offset.reset', 'smallest');
$topicConf->set('offset.store.method', 'broker');
$topicConf->set('auto.commit.enable', 'false');
```

 - [x] Operating system: debian:9.4
 - [x] Provide logs  
  Log file is 1.2G with `debug=all` and a couple of hours of up-time. Here is the last 1000 line. It kind of repeats the top few 100 lines for a long time before shutting down.  
[kafka_log_last1000.log.gz](https://github.com/edenhill/librdkafka/files/3384649/kafka_log_last1000.log.gz)

 - [ ] Provide broker log excerpts  
  Can't get broker logs from Confluent, apparently?

 - [ ] Critical issue

**Comment by edenhill** [comment]
The consumer will not terminate itself, so this is either your application or the PHP garbage collector kicking in.
