### ISSUE TITLE
The bottleneck of kafka

### ISSUE THREAD

**Issue by eelyaj** [edenhill/librdkafka#2412]
I am running a high throughput test of my message collecting system.
There are 10 vms which can send message as much as it can.
The message length is about 300 bytes, and one vm could send 1 million messages per second.

I found that the whole system could only handle about 5 million messages per second.
I've increased producer number, kafka broker number, partition number, and nothing helped.

I thought the rtt might be something to do with the throughput.  When I set 'acks=all‘, the total throughput decrease to 2 million messages per second.  but when I set 'acks=0', the total throughput is still 5 million messages per second. It seems 'acks=0' and 'ack=1' are the same :(

I found change 'replication_factor=1' will increase the throughput up to 10 million messages per second, but I don't want to sacrifice reliability.

What can I do to find the bottleneck? Thanks.

API
rd_kafka_produce_batch

Cluster
10 vms for producer, each one has 8 vcpu 32G RAM
20 vms for kafka, each one has 8 vcpu 32G RAM 1.2T HDD
network bandwidth is 10Gbits/s. It can reach 8Gbits/s, based on iperf test.
IOPS is around 2500.

Producer parameters:
            "queue.buffering.max.ms": "1000",
            "queue.buffering.max.messages": "1000000",
            "queue.buffering.max.kbytes": "2048000",
            "batch.num.messages": "100000",
            "compression.codec": "lz4",
            "socket.send.buffer.bytes": "100000000",
            "socket.receive.buffer.bytes": "100000000",
            "message.max.bytes": "209715200"
            "request.required.acks": "1",
            "request.timeout.ms": "30000"
            "partition_num": 200,
             "replication_factor": 2,
             "retention_ms": 3600000,

Version:
librdkafka 0.11.6
Kafka 1.1.1
I have tried librdkafka 1.1.0  and kafka 2.1.0, no difference.

Kafka broker config:
broker.id.generation.enable=true
reserved.broker.max.id=15000000

listeners=PLAINTEXT://180.10.10.100:9092

host.name=180.10.10.100

advertised.host.name=180.10.10.100
advertised.port=9092

num.network.threads=9

num.io.threads=16

socket.send.buffer.bytes=102400

socket.receive.buffer.bytes=102400

socket.request.max.bytes=104857600

log.dirs=/opt/data/kafka/data_log

auto.create.topics.enable=false

num.recovery.threads.per.data.dir=8

offsets.topic.replication.factor=2
transaction.state.log.replication.factor=2
transaction.state.log.min.isr=2

log.flush.interval.messages=100000

log.flush.interval.ms=7000

log.retention.hours=1
log.roll.hours=8
log.roll.jitter.hours=4

log.segment.bytes=1073741824

log.retention.check.interval.ms=300000

replica.lag.time.max.ms=10000

log.cleaner.enable=true
message.max.bytes=209715200

replica.fetch.max.bytes=210000000
replica.fetch.min.bytes=1048576
default.replication.factor=2
min.insync.replicas=1
delete.topic.enable=true

num.replica.fetchers=8
log.flush.scheduler.interval.ms=7000
replica.fetch.wait.max.ms=500
group.initial.rebalance.delay.ms=0
controlled.shutdown.max.retries=10
controlled.shutdown.retry.backoff.ms=10000

log.message.timestamp.type=LogAppendTime

**Comment by sarkanyi** [comment]
For high rate producing we found that counter-intuitively "queue.buffering.max.ms":"0.5" worked best. But our goal is to use as few CPU cores as possible, as it's the most limited resources. As for speed, after my malloc patch we could hit about 15 Gbps into 3 brokers (the brokers can't go over 5 Gbps each yet)

**Comment by eelyaj** [comment]
> For high rate producing we found that counter-intuitively "queue.buffering.max.ms":"0.5" worked best. But our goal is to use as few CPU cores as possible, as it's the most limited resources. As for speed, after my malloc patch we could hit about 15 Gbps into 3 brokers (the brokers can't go over 5 Gbps each yet)

What is malloc patch?

**Comment by sarkanyi** [comment]
Malloc has a contention issue when trying to scale librdkafka, I've made a PR for using a custom allocator if needed. Ofc you can simply try by LD_PRELOAD -ing a different allocator like jemalloc or tcmalloc, but that's not always an option because it replaces all malloc/free calls

**Comment by write2jaydeep** [comment]
@sarkanyi when would be this patch available? I would like to discover more about the improvement of producer on my platform

**Comment by sarkanyi** [comment]
The easiest test would be just to LD_PRELOAD jemalloc or tcmalloc. In our case that's not possible as it might throw off other things, but maybe in your case it's workable. As for a custom allocator, there are 2 PRs pending: https://github.com/edenhill/librdkafka/pull/2409 and https://github.com/edenhill/librdkafka/pull/2405
