### ISSUE TITLE
How to limit the network bandwidth consumption

### ISSUE THREAD

**Issue by fesun** [edenhill/librdkafka#2414]
I have one kafka topic, each message size is about 1MB. One producer sends about 2GB data to kafka each minute, the data arrival is not even, the producer sends all data during the first 10 seconds, and send nothing during the remaining 50 seconds. One online consumer reads from kafka constantly. Librdkafka works like this: reads from brokers at full speed during the first 10ms to fill the queue, and do nothing during the next 10ms, the problem is that using up network bandwidth for tens of ms makes the online server latency unstable, and it's acceptable for latency sensitive service.
Is it possible to limit the bandwidth consumption?

**Comment by edenhill** [comment]
That is not possible with librdkafka.
I suggest either rate limiting your produce() calls, or rate-limiting on the network level with e.g., `iptables`.

**Comment by fesun** [comment]
If we or other people have the effort, is it ok to add it to librdkafka? Usually producers and consumers are managed by different teams or the producer is distribution job, and it's not easy to set the producing rate correctly. I am not familiar with iptables but I think iptables needs complex configuration and much additional effort to maintain it, say if we change the broker list, we need to update the iptable rules.

**Comment by edenhill** [comment]
For such a use-case you probably want client quotas on the broker:
https://docs.confluent.io/current/kafka/post-deployment.html#enforcing-client-quotas

**Comment by fesun** [comment]
The quota is designed to protect brokers and it's per-broker configuration. If we want to set out per-consumer bandwidth limitation, we need to take consumer number and broker number into consideration, it's not that straightforward as those two numbers may change anything, thought we may have some workaround like monitor and change dynamically, still needs quite lots of effort.
Thanks for your reply, for now I used iptables to achieve this limitation as current cluster size is small, I will fork and edit in the future if I really need this limitation.
