### ISSUE TITLE
ssl.endpoint.identification.algorithm failing when openssl version >= 1.1

### ISSUE THREAD

**Issue by hunterjackson** [edenhill/librdkafka#2419]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We are using the [confluent-kafka python library](https://github.com/confluentinc/confluent-kafka-python/tree/v1.1.0). We were attempting to enable `ssl.endpoint.identification.algorithm=https` and we were receiving the error `KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}`. After spending some time validating our endpoint was indeed correct we poked around and found what appears to be a bug when the OpenSSL version is >= what I believe is 1.1. In [rdkafka_ssl](https://github.com/edenhill/librdkafka/blob/v1.1.0/src/rdkafka_ssl.c#L430), `rktrans->rktrans_rkb->rkb_nodename` should be `name` because `rkb_nodename` appears to include the port.  

Attached is a patch that we applied when building that remedied the problem for us. Let me know if you need anymore information. 

[rdkafka_ssl.patch](https://github.com/edenhill/librdkafka/files/3407753/rdkafka_ssl.txt)

How to reproduce
================
As we were using a python library I don't have direct reproduction steps, however if needed I'm happy to run more tests. 

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.1.0`
 - [x] Apache Kafka version: `2.1`
 - [x] librdkafka client configuration: `sasl.username=..., sasl.password=..., ssl.endpoint.identification.algorithm=https, sasl.mechanisms=SCRAM-SHA-256, security.protocol=SASL_SSL, ssl.ca.location=/etc/ssl/certs`
 - [x] Operating system: `Linux factorytx 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 GNU/Linux`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Good find!

Would you like to submit a PR?

**Comment by hunterjackson** [comment]
Here's a PR with only the patch listed applied https://github.com/edenhill/librdkafka/pull/2420

**Comment by edenhill** [comment]
Thanks!
