### ISSUE TITLE
How do I configure different topics separately with KafkaConsumer?

### ISSUE THREAD

**Issue by ronalabraham** [edenhill/librdkafka#2422]
Description
===========
I want to set "auto.offset.reset" to different values for different topics using the same `RdKafka::KafkaConsumer` instance. The [FAQ](https://github.com/edenhill/librdkafka/wiki/FAQ#how-do-i-set-topic-configuration-properties-with-the-kafkaconsumer) says: 

> If you need special configuration for a sub-set of your topics you will need to create them prior to calling subscribe() or assign() and pass their explicit configuration objects at topic creation time.

I understand how to set the topic configuration when creating an `RdKafka::Topic`, but how do I tell my `RdKafka::KafkaConsumer` instance to use the created `RdKafka::Topic` object? I don't see any relationship between `RdKafka::KafkaConsumer` and `RdKafka::Topic`, at least from the interface (rdkafkacpp.h).

**Comment by edenhill** [comment]
Topic objects are reused internally, so just make sure to create your Topic object (with custom config) prior to referencing the same topic names in subscribe() or assign().

**Comment by ronalabraham** [comment]
Ah! Thank you, this was an obvious question. I missed the fact that `Handle` is passed into `static Topic * create (Handle *base, const std::string &topic_str, Conf *conf, std::string &errstr)`.
