### ISSUE TITLE
rdkafka_example code error, rdkafka_example_cpp -L to list metadata can't assign topic

### ISSUE THREAD

**Issue by njzcx** [edenhill/librdkafka#2425]
https://github.com/edenhill/librdkafka/blob/0b98c7b27fe166fae9e40b0bd3860e997a09fb6e/examples/rdkafka_example.cpp#L661

I test example with two cases, but the result is the same
`./rdkafka_example_cpp -L -b 172.17.0.2:9092 -t test_topic`
`./rdkafka_example_cpp -L -b 172.17.0.2:9092`

The reason that found the problem is `topic!=NULL` should be `!topic` in 661 line

**Comment by njzcx** [comment]
ps: My OS is Ubuntu 18

**Comment by edenhill** [comment]
You are right, care to submit a PR to fix this?

**Comment by njzcx** [comment]
ok, i will do

发自我的 iPhone
