### ISSUE TITLE
rd_kafka_oauthbearer_set_token_failure: symbol not found

### ISSUE THREAD

**Issue by Rahul7794** [edenhill/librdkafka#2429]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I am running confluent-go-kakfa in docker with alpine and I am able to build my docker image but when I run my docker image it throws error:

Error relocating /opt/gddb-consumer/bin/gddb-consumer: rd_kafka_oauthbearer_set_token_failure: symbol not found
Error relocating /opt/gddb-consumer/bin/gddb-consumer: rd_kafka_event_config_string: symbol not found
Error relocating /opt/gddb-consumer/bin/gddb-consumer: rd_kafka_oauthbearer_set_token: symbol not found

How to reproduce
================
my dockerfile is something like this:
FROM golang:alpine3.10 AS build-stage

LABEL app="abcr"

# Because of https://github.com/docker/docker/issues/14914
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin
# required by go get
RUN apk add --update --no-cache alpine-sdk bash python ca-certificates \
      libressl \
      tar \
      git openssh openssl yajl-dev zlib-dev cyrus-sasl-dev openssl-dev build-base coreutils

WORKDIR /root
RUN git clone https://github.com/edenhill/librdkafka.git
WORKDIR /root/librdkafka
RUN /root/librdkafka/configure --install-deps
RUN make
RUN make install

WORKDIR /src/abc

ARG COMMIT
ARG BUILD_DATE
COPY . .
# build the application
RUN go build -ldflags "-X abc/version/version.GitCommit=${COMMIT} -X abc/version/version.BuildDate=${BUILD_DATE}"

# Final Stage
FROM alpine:3.10

# because of https://github.com/docker/docker/issues/14914
ENV PATH=$PATH:/opt/abc/bin

WORKDIR /opt/abc/bin

COPY --from=build-stage /src/abc/abc .
RUN apk add --no-cache librdkafka
ENTRYPOINT ["/opt/abc/bin/abc"]

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://github.com/confluentinc/confluent-kafka-go/#getting-started

The Go client requires the latest version of librdkafka, v1.1.0
