### ISSUE TITLE
RdKafka::Headers::Header operator= memory leak

### ISSUE THREAD

**Issue by vsakharuk** [edenhill/librdkafka#2431]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Kafka assignment operator does not delete previous buffer.
//memory leak
          auto h = headers->get_last("AAA");
          h = headers->get_last("BBB");
//does not.
          auto a = headers->get_last("AAA");
          auto b  = headers->get_last("BBB");

Cause:

previous allocation was not freed.
need line 
      free (value_);
in:

   Header& operator=(const Header &other)
    {
      if (&other == this) {
	return *this;
      }

      key_ = other.key_;
      err_ = other.err_;
      value_size_ = other.value_size_;
      **free (value_);**
      value_ = copy_value(other.value_, value_size_);

      return *this;
    }

How to reproduce
================
         auto headers =   RdKafka::Headers::create();
        headers->add("AAA", "aaa");
        headers->add("BBB", "bbb");
          auto h = headers->get_last("AAA");
          h = headers->get_last("BBB");

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by vsakharuk** [comment]
There one more issue.
get_last will random core.

     auto headers =   RdKafka::Headers::create();
    headers->add("AAA", "aaa");
     h = headers->get_last("BBB");

====
rd_kafka_header_get_last() will set  (const void **valuep, size_t *sizep)
only if this exist.

So value and size
in get_last() will not be set.
   const void *value;
    size_t size;
    rd_kafka_resp_err_t err;
    err = rd_kafka_header_get_last(headers_, key.c_str(), &value, &size);
    return Headers::Header(key, value, size,
                           static_cast<RdKafka::ErrorCode>(err));
as a result
 Headers::Header(key, value, size,
                           static_cast<RdKafka::ErrorCode>(err));
will call 
 value_ = copy_value(value, value_size);
where both value and value_size uninitalize.

======
Patch:
   const void *value=nullptr;
    size_t size=0;

**Comment by edenhill** [comment]
The value of value and size are supposed to be undefined if get_last() returns an error, the caller should not dereference those pointers on error.

As for the memory leak, would you like to submit a PR with a fix?

**Comment by vsakharuk** [comment]
I will try.

"The value of value and size are supposed to be undefined if get_last() returns an error, the caller should not dereference those pointers on error."  -> this access happens inside the API, not outside so caller has no control.
those 2 lines:

err = rd_kafka_header_get_last(headers_, key.c_str(), &value, &size);
return Headers::Header(key, value, size,
static_castRdKafka::ErrorCode(err));

**Comment by edenhill** [comment]
You're right! That should definitely be fixed in rdkafkacpp_int.h
Please include that fix in your PR too
