### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by subcon42** [edenhill/librdkafka#2434]
Description
===========
It is worth pointing out that the instructions on ...

 * https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka

... should mention that (for CentOS 7+ users), one must also install:

```
cyrus-sasl-devel
```

... in addition to the other mentioned `cyrus-sasl` package(s).

Until I did this, I was unable to get `./configure` to declare `sasl2` as **ok**.

A documentation update to the aforementioned link may be a good idea.

Thanks!

Jesse 💜

**Comment by edenhill** [comment]
Thank you, fixed!
