### ISSUE TITLE
rd_kafka_poll works sometimes

### ISSUE THREAD

**Issue by MockingJayWong** [edenhill/librdkafka#2435]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>
i found it rd_kafka_poll(rk, 0) works in someway but not always work. 
for example:
case it works:

* send msg in another thread(for loop limited + usleep)
* * when uncomment usleep function，rd_kafka_poll not works。

```C
void send_msg_func(rd_kafka_t* rk, rd_kafka_topic_t* m_topic) {
    rd_kafka_produce(m_topic, 0, RD_KAFKA_MSG_F_COPY, "string", 7, NULL, 0, NULL);
    rd_kafka_poll(rk, 0);
    return;
}

void* poll_fun(void* opaque) {
    thread_param_t* param = (thread_param_t*)opaque;
    printf("start thread, %d\n", state);
    for (int i = 0; i < 100; i++) {
        send_msg_func(param->rk, param->topic);
        usleep(100* 1000);           // ----uncomment this line
    }
    printf("after send and poll %d\n", rd_kafka_outq_len(param->rk));
    printf("ending func\n");
    return NULL;
}
```

* send it in another thread(for loop unlimited)

```C
void* poll_fun(void* opaque) {
    thread_param_t* param = (thread_param_t*)opaque;
    printf("start thread, %d\n", state);
    for (;;) {
        send_msg_func(param->rk, param->topic);
    }
    printf("after send and poll %d\n", rd_kafka_outq_len(param->rk));
    printf("ending func\n");
    return NULL;
}
```

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>
in two case above, i can get delivery callback work。but if we using poll_fun in main thread or dont use usleep when for loop limited, it cant work at all. 
so i want to know what influences `rd_kafka_poll`. 

with producer instance configs: 
    rd_kafka_conf_set(conf, "queue.buffering.max.messages", "10000000", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "linger.ms", "0", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "compression.codec", "none", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "socket.keepalive.enable", "true", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "enable.idempotence", "true", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "message.timeout.ms", "500", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "acks", "all", errstr, sizeof(errstr));

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [x] Apache Kafka version: `kafka_2.12-2.2.0`
 - [x] librdkafka client configuration: `"queue.buffering.max.messages"="10000000"
"linger.ms"= "0"
"compression.codec"="none"
"socket.keepalive.enable"= "true"
"enable.idempotence"="true"
"message.timeout.ms"="1000" "ack"="all"`
 - [x] Operating system: `Ubuntu 18.04.1 LTS`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by MockingJayWong** [comment]
with full code
```C
#include <stdio.h>
#include <signal.h>
#include <string.h>
#include <stdlib.h>
/* Typical include path would be <librdkafka/rdkafka.h>, but this program
 * is builtin from within the librdkafka source tree and thus differs. */
#include "rdkafka.h"
#include <time.h>
#include <poll.h>
#include <unistd.h>
#include <pthread.h>

volatile int run = 1;
static pthread_t poll_thread_id;
static volatile int state = 0;

typedef struct thread_param_s {

    rd_kafka_t *rk;

    rd_kafka_topic_t *topic;

} thread_param_t;

static void mq_connection_deliverlog(rd_kafka_t* kafka, const rd_kafka_message_t* message, 
        void* opaque)
{
    if (!message)
    {
        printf("param message is null\n");
        return;
    }

    if (RD_KAFKA_RESP_ERR_NO_ERROR == message->err)
    {
        printf("send message\n");
        return;
    }

    printf("failed to deliver message,len:%lu,offset:%"PRId64",topic:%s,err:%s\n", message->len,
            message->offset, rd_kafka_topic_name(message->rkt), rd_kafka_err2str(message->err));
    return;
}

void send_msg_func(rd_kafka_t* rk, rd_kafka_topic_t* m_topic) {
    rd_kafka_produce(m_topic, 0, RD_KAFKA_MSG_F_COPY, "string", 7, NULL, 0, NULL);
    rd_kafka_poll(rk, 0);
    //rd_kafka_poll(rk, 100);
    return;
}

void* poll_fun(void* opaque) {
    thread_param_t* param = (thread_param_t*)opaque;
    printf("start thread, %d\n", state);
    for (;state != 0;) {
        send_msg_func(param->rk, param->topic);
        usleep(100* 1000);
    }
    printf("after send and poll %d\n", rd_kafka_outq_len(param->rk));
    printf("ending func\n");
    // printf("after poll %d\n", rd_kafka_outq_len(rk));
    return NULL;
}

int main (int argc, char **argv) {
    rd_kafka_t *rk;         /* Producer instance handle */
    rd_kafka_conf_t *conf;  /* Temporary configuration object */
    char errstr[512];       /* librdkafka API error reporting buffer */
    char sigio_str[16] = {0,};
    memset(sigio_str, 0, sizeof(sigio_str));
    snprintf(sigio_str, sizeof(sigio_str), "%d", SIGIO);
    sigio_str[sizeof(sigio_str) - 1] = '\0';

    const char *brokers = "vm1:9092,vm2:9092,vm3:9092";
    const char *topic   = "wa_test_1";
    
    conf = rd_kafka_conf_new();
    rd_kafka_conf_set(conf, "queue.buffering.max.messages", "10000000", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "linger.ms", "0", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "compression.codec", "none", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "socket.keepalive.enable", "true", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "enable.idempotence", "true", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "message.timeout.ms", "500", errstr, sizeof(errstr));
    rd_kafka_conf_set(conf, "acks", "all", errstr, sizeof(errstr));
    
    rd_kafka_conf_set_dr_msg_cb(conf, mq_connection_deliverlog);
    
    if (RD_KAFKA_CONF_OK != rd_kafka_conf_set(conf, "internal.termination.signal", sigio_str, errstr,
                sizeof(errstr))) {
            fprintf(stderr, "%s\n", errstr);
            return 1;
    }
    
    rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf, errstr, sizeof(errstr));
    if (!rk) {
            fprintf(stderr,
                    "%% Failed to create new producer: %s\n", errstr);
            return -1;
    }
    if (!rd_kafka_brokers_add(rk, brokers))
    {
        printf("failed to add brokers to kafka client\n");
        rd_kafka_destroy(rk);
        rk = NULL;
        return -1;
    }
    
    rd_kafka_topic_conf_t* topic_conf = NULL;
    char err_str[512] = {0, };
    memset(err_str, 0, sizeof(err_str));
    topic_conf = rd_kafka_topic_conf_new();

    rd_kafka_topic_t* m_topic = NULL;
    printf("begin to obtain topic\n");
    m_topic = rd_kafka_topic_new(rk, topic, topic_conf);
    printf("topic %s\n", rd_kafka_topic_name(m_topic));
    
    thread_param_t param;
    param.rk = rk;
    param.topic = m_topic;

    state = 1;
    //poll_fun((void*)&param);
    //send_msg_func(rk, topic);
    pthread_create(&poll_thread_id, NULL, poll_fun, (void*)&param);

    usleep(5000*1000);
    state = 0;
    pthread_join(poll_thread_id, NULL);

    rd_kafka_topic_destroy(m_topic);
    rd_kafka_destroy(rk);
    return 0;
}
```

**Comment by edenhill** [comment]
produce() is asynchronous, the message is delivered to the broker in a background thread without blocking on produce().
This means that if you call produce() and directly call poll(0) there is no, or little, chance that the message has been delivered.
This is okay though, because that poll() call might trigger the delivery report callback for a previously produced message.

If you know that you will have a steady stream of messages to produce you can do a produce() + poll(0) loop.
If the rate of messages is unknown it is better to put the poll() call in a separate loop (in another thread) and call it with a timeout.

**Comment by MockingJayWong** [comment]
___got it! thx for your reply!!___ 
i made a mistake that i thought loop unlimited or limited must affect rd_kafka_poll. 
In fact, poll have no matter with it. when i using loop limited, why poll get nothing, just because of produce in asynchronous way, and doesnt send it out when last poll trigger.

**Comment by MockingJayWong** [comment]
I think some guys like me are willing to get this instruction to use poll correctly, maybe we can put this somewhere like FAQ or other places
* `If you know that you will have a steady stream of messages to produce you can do a produce() + poll(0) loop.`
* `If the rate of messages is unknown it is better to put the poll() call in a separate loop (in another thread) and call it with a timeout.`

**Comment by edenhill** [comment]
Done, thanks
https://github.com/edenhill/librdkafka/wiki/FAQ#when-and-how-should-i-call-rd_kafka_poll
