### ISSUE TITLE
Problem with visual studio

### ISSUE THREAD

**Issue by tompeled** [edenhill/librdkafka#2436]
Description
===========
Hello, 
I have an error, trying to compile and this is what i got:

`1>------ Build started: Project: WindowsProject4, Configuration: Debug Win32 ------
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::err2str(enum RdKafka::ErrorCode)" (__imp_?err2str@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ErrorCode@1@@Z) referenced in function _main
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall RdKafka::DeliveryReportCb::~DeliveryReportCb(void)" (__imp_??1DeliveryReportCb@RdKafka@@UAE@XZ) referenced in function "public: virtual __thiscall ExampleDeliveryReportCb::~ExampleDeliveryReportCb(void)" (??1ExampleDeliveryReportCb@@UAE@XZ)
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall RdKafka::DeliveryReportCb::DeliveryReportCb(void)" (__imp_??0DeliveryReportCb@RdKafka@@QAE@XZ) referenced in function "public: __thiscall ExampleDeliveryReportCb::ExampleDeliveryReportCb(void)" (??0ExampleDeliveryReportCb@@QAE@XZ)
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Conf * __cdecl RdKafka::Conf::create(enum RdKafka::Conf::ConfType)" (__imp_?create@Conf@RdKafka@@SAPAV12@W4ConfType@12@@Z) referenced in function _main
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Topic * __cdecl RdKafka::Topic::create(class RdKafka::Handle *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class RdKafka::Conf *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (__imp_?create@Topic@RdKafka@@SAPAV12@PAVHandle@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAVConf@2@AAV45@@Z) referenced in function _main
1>KafkaProducer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Producer * __cdecl RdKafka::Producer::create(class RdKafka::Conf *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (__imp_?create@Producer@RdKafka@@SAPAV12@PAVConf@2@AAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function _main
1>KafkaProducer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int const RdKafka::Topic::PARTITION_UA" (__imp_?PARTITION_UA@Topic@RdKafka@@2HB)
1>MSVCRTD.lib(exe_winmain.obj) : error LNK2019: unresolved external symbol _WinMain@16 referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
1>C:\Users\inbal\source\repos\WindowsProject4\Debug\WindowsProject4.exe : fatal error LNK1120: 8 unresolved externals
1>Done building project "WindowsProject4.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

i installed the librdkafka with NUGET 
I saw on which page I should set LIBRDKAFKA_STATICLIB, but i can't using CMAKE and NUGET together, so how i can do this?

can you help me please? 

Thanks!

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Make sure you are linking your application to librdkafkacpp.lib and librdkafka.lib.

**Comment by sushmukund26** [comment]
I am facing the same issue where after referencing librdkafka.redist NuGet package in the  Visual Studio project, the following is happening:

- Able to successfully include <librdkafka/rdkafkacpp.h>

- Able to successfully create a dummy object, for instance, RdKafka::Conf *conf;

- Unable to instantiate it as follows: RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);

- The following error occurs: **Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Conf * __cdecl RdKafka::Conf::create(enum RdKafka::Conf::ConfType)" (__imp_?create@Conf@RdKafka@@SAPEAV12@W4ConfType@12@@Z)	EmoRecVidSVM_Adult	C:\EmotionDetection\expression_recognition_video_SVM_adult\exe\FaceLandmarkVid\EmoRecVidSVM_Adult.obj	1**	

- The project does not compile when I try to include both librdkafka/rdkafka.h and librdkafka/rdkafkacpp.h.

Do let me know if I am missing something. Thanks in advance!

**Comment by mnewman-iress** [comment]
@sushmukund26, I faced the same issue and found that the librdkafka Nuget package targets include librdkafka.lib, but not librdkafkacpp.lib. Below is taken from librdkafka.redist.targets:
```
...
      <AdditionalDependencies Condition="'$(Platform)' == 'x64'">$(MSBuildThisFileDirectory)lib\win\x64\win-x64-Release\v120\librdkafka.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalDependencies Condition="'$(Platform)' != 'x64'">$(MSBuildThisFileDirectory)lib\win\x86\win-x86-Release\v120\librdkafka.lib;%(AdditionalDependencies)</AdditionalDependencies>
...
```

This means a consuming project will not link to librdkafkacpp.lib by default.

Adding librdkafkacpp.lib as an Additional Dependency for the Linker fixed the issue for me:
```
    <Link>      <AdditionalDependencies>$(MSBuildThisFileDirectory)packages\librdkafka.redist.1.3.0\build\native\lib\win\x86\win-x86-Release\v120\librdkafkacpp.lib;$(ConanSystemDeps)%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
```

**Comment by sushmukund26** [comment]
@mnewman-iress, thank you so much!! Adding librdkafkacpp.lib as an additional dependency fixed the issue for me!

**Comment by rogerlee24** [comment]
@mnewman-iress 
<AdditionalDependencies>$(MSBuildThisFileDirectory)packages\librdkafka.redist.1.8.2\build\native\lib\win\x86\win-x86-Release\v140\librdkafkacpp.lib;%(AdditionalDependencies)</AdditionalDependencies>
![image](https://user-images.githubusercontent.com/57137841/147359869-fdd3421b-6663-4d59-bb04-ad296139aeee.png)

After adding librdkafkacpp.lib as an Additional Dependency for the Linker, i encounter  an error.
![image](https://user-images.githubusercontent.com/57137841/147359855-e9787844-dcbe-4f05-9bf3-802da14eb812.png)
can you help me? thanks!

**Comment by mnewman-iress** [comment]
Sorry @rogerlee24, I haven't used the Nuget package since original post. It may be worth opening a new issue.

MS [docs](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1104?view=msvc-170) for the error may help (e.g. has the directory path potentially changed in newer version of librdkafka Nuget package, is it even still in the package).

FYI I ended up building librdkafka using a Conan recipe similar to this [one](https://conan.io/center/librdkafka?os=&tab=recipe). The big advantage with this approach is that I could specify all the options (and only those) that I needed (e.g. SSL, ZLIB).
