### ISSUE TITLE
Please update debian distribution

### ISSUE THREAD

**Issue by apoggi-carecloud** [edenhill/librdkafka#2438]
Debian distribution is quite out of date and incompatible with https://github.com/confluentinc/confluent-kafka-go

**Comment by edenhill** [comment]
Can you be more specific?

**Comment by digizeph** [comment]
On this topic: do you keep the `changelog` file or more generally the `debian` directory updated in somewhere else? seems like the `changelog` files in master branch and 1.0.x branch is quite old.

**Comment by daniellavoie** [comment]
Using debien stretch and buster I get the following error when trying to install librdkafka-dev.

```
wget -qO - https://packages.confluent.io/deb/5.3/archive.key | apt-key add - && \
  apt-get update && \
  apt-get install -y apt-transport-https software-properties-common && \
  add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.3 stable main" && \
  apt-get update && \
  apt-get install -y librdkafka-dev

**Comment by daniellavoie** [comment]
I have a dependency error when trying to install on stretch and buster. Got to the same by switching to confluent 5.3 repository. I'll try ubuntu for now.

```
wget -qO - https://packages.confluent.io/deb/5.2/archive.key | apt-key add - && \
  apt-get update && \
  apt-get install -y apt-transport-https software-properties-common && \
  add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.2 stable main" && \
  apt-get update && \
  apt-get install -y librdkafka-dev
```

Output : 

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 librdkafka-dev : Depends: librdkafka1 (= 1.0.0~1confluent5.2.2-1) but it is not going to be installed
                  Depends: librdkafka++1 (= 1.0.0~1confluent5.2.2-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by kerenor23** [comment]
@edenhill , being more specific-

The debian packages listed here: [https://docs.confluent.io/current/installation/available_packages.html#librdkafka](https://docs.confluent.io/current/installation/available_packages.html#librdkafka) (got to that documentation from this repo's [installation instruction](https://github.com/edenhill/librdkafka#installing-prebuilt-packages)) all seem to be out of date with this git repo. 

More alarming, it lists [https://github.com/confluentinc/librdkafka](https://github.com/confluentinc/librdkafka) as the doc, and that repo seems extremely out of date.

output of `apt-cache policy librdkafka-dev librdkafka1` (I haven't installed yet)
```
librdkafka-dev:
  Installed: (none)
  Candidate: 0.11.3-1build1
  Version table:
     0.11.3-1build1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
librdkafka1:
  Installed: (none)
  Candidate: 0.11.3-1build1
  Version table:
     0.11.3-1build1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

0.11.3-build1? Isn't current release 1.1.0?

**Comment by edenhill** [comment]
Those packages are from Ubuntu bionic, the confluent packages are at 1.1.0, make sure to add the confluent apt repository to your apt sources and update.

As for the doc link, that's just a mistake, it should point to edenhill/librdkafka.

**Comment by kerenor23** [comment]
Thanks!
