### ISSUE TITLE
Error with key store contains ca chain

### ISSUE THREAD

**Issue by zhengbli** [edenhill/librdkafka#2439]
Description
===========
I'm trying to use libkafka with a keystore file (.jks) containing a ca chain when it gives the following error:
```
% Reading configuration from file kafkacat.config
% ERROR: Failed to create producer: Error reading PKCS#12 file: crypto/asn1/asn1_lib.c:101: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:
```
My kafkacat config file looks like this:
```
security.protocol=ssl
ssl.key.location=key
ssl.keystore.location=jp2.jks
ssl.keystore.password=abc123
```
where the `jp2.jks` is the keystore file.

It is worth mentioning that I successfully connected to the broker via `kafka-console-consumer.sh` using the same file:
```
kafka-console-consumer.sh --bootstrap-server [BROKER LIST] -topic [TOPIC] --consumer.config client.properties --from-beginning
```
Where the client.properties are:
```
security.protocol=SSL
ssl.truststore.location=./kafka.client.truststore.jks
ssl.keystore.location=./jp2.jks
ssl.keystore.password=abc123
ssl.key.password=abc123
```
**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.1.0-1`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
JKS files are is a java-specific format, they're not supported by librdkafka.
Convert your JKS files to PKCS#12 or PEM, which are standard formats.
