### ISSUE TITLE
Any API to list all available topics and partitions?

### ISSUE THREAD

**Issue by michema** [edenhill/librdkafka#244]
Hi, Magnus:

Is there any consumer API to list all available topics and partitions?

Thanks,

Michelle

**Comment by edenhill** [comment]
Hi Michelle,

yes, the `rd_kafka_metadata()` API does just that.
It is currently only available in the C API but a C++ pull-request has been submitted.

Hope that helps,
Magnus

**Comment by michema** [comment]
Thanks. It helps a lot.
