### ISSUE TITLE
CRITICAL ERROR within `rd_kafka_timer_cmp`, which  would completely stuck the timer (if with any long `timeout` configuration)

### ISSUE THREAD

**Issue by kenneth-jia** [edenhill/librdkafka#2443]
The function `rd_kafka_timer_cmp` uses `(int)(a->rtmr_next - b->rtmr_next)` for comparing.
However, this is quite a wrong way with `(int) cast`, since the result of `(a->rtmr_next - b->rtmr_next)` is `int64`, and it could be truncated (`int` is `int32` in our case) thus the highest bit of the left part would be the `sign bit`.
E.g, if `a->rtmr_next` = `0x00000000 80000000`, and `b->rtmr_next` = `0x00000000 00000000`, then result of `rd_kafka_timer_cmp` could be `0x80000000`, which is negative, but in fact the first value is larger! 

We found the problem while our consumer failed to auto-commit offsets after some timepoint. Once a really big `rtmr_next` is sorted to be the first one in the list, then the `rd_kafka_timers_run` would always skip the left ones.

There're some configurations could be with large `timeout` and thus trigger the problem, -- e.g, `sasl.kerberos.min.time.before.relogin` , `auto.commit.interval.ms`, `offset.store.sync.interval.ms`, `api.version.fallback.ms`, `statistics.interval.ms`, `broker.address.ttl`. The maximum value for them is `86400 seconds`. In fact, any timer longer than `2147,483` ms could cause the problem.

The solution might be simple, replace `(int)(a->rtmr_next - b->rtmr_next)` with `a->rtmr_next < b->rtmr_next ? -1 : (a->rtmr_next > b->rtmr_next ? 1 : 0)`.

**Comment by edenhill** [comment]
Thank you!
I'll push a PR that fixes all such comparators.

**Comment by edenhill** [comment]
Please try out the cmp_ovflow branch which contains the fix.

**Comment by kenneth-jia** [comment]
Thank you for your quick response.
We'll try with the branch. It surely would work, -- even just fixing the `rd_kafka_timer_cmp` would solve our problem.
Cheers :-)
