### ISSUE TITLE
undefined reference to `crc32' while building binary

### ISSUE THREAD

**Issue by meirelop** [edenhill/librdkafka#2449]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

I was able to use librdkafka and build Golang binaries with command:
 **go build -tags static -ldflags "${ldflags}" -o bin/**
Then I installed library "zlib" for decompression.
And now same command gives following error. 

`/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/lib/librdkafka.a(rdkafka_broker.o): In function 'rd_crc32_update':
/home/meirkhan/Go/librdkafka/src/rdcrc32.h:102: undefined reference to 'crc32'
/home/meirkhan/Go/librdkafka/src/rdcrc32.h:102: undefined reference to 'crc32'
/home/meirkhan/Go/librdkafka/src/rdcrc32.h:102: undefined reference to 'crc32'
/home/meirkhan/Go/librdkafka/src/rdcrc32.h:102: undefined reference to 'crc32'
/home/meirkhan/Go/librdkafka/src/rdcrc32.h:102: undefined reference to 'crc32'
/usr/lib/librdkafka.a(rdkafka_broker.o):/home/meirkhan/Go/librdkafka/src/rdcrc32.h:102: more undefined references to 'crc32' follow
/usr/lib/librdkafka.a(rdkafka_msgset_writer.o): In function 'rd_kafka_msgset_writer_compress_gzip':
/home/meirkhan/Go/librdkafka/src/rdkafka_msgset_writer.c:950: undefined reference to 'deflateInit2_'
/home/meirkhan/Go/librdkafka/src/rdkafka_msgset_writer.c:969: undefined reference to 'deflateBound'
/home/meirkhan/Go/librdkafka/src/rdkafka_msgset_writer.c:982: undefined reference to 'deflate'
/home/meirkhan/Go/librdkafka/src/rdkafka_msgset_writer.c:1002: undefined reference to 'deflate'
/home/meirkhan/Go/librdkafka/src/rdkafka_msgset_writer.c:1021: undefined reference to 'deflateEnd'
/home/meirkhan/Go/librdkafka/src/rdkafka_msgset_writer.c:993: undefined reference to 'deflateEnd'
/home/meirkhan/Go/librdkafka/src/rdkafka_msgset_writer.c:1013: undefined reference to 'deflateEnd'
/usr/lib/librdkafka.a(rdbuf.o): In function 'rd_crc32_init':
/home/meirkhan/Go/librdkafka/src/rdcrc32.h:74: undefined reference to 'crc32'
/usr/lib/librdkafka.a(rdbuf.o): In function 'rd_crc32_update':
/home/meirkhan/Go/librdkafka/src/rdcrc32.h:102: undefined reference to 'crc32'
/usr/lib/librdkafka.a(rdbuf.o): In function 'rd_crc32_init':
/home/meirkhan/Go/librdkafka/src/rdcrc32.h:74: undefined reference to 'crc32'
/usr/lib/librdkafka.a(rdbuf.o): In function 'rd_crc32_update':
/home/meirkhan/Go/librdkafka/src/rdcrc32.h:102: undefined reference to 'crc32'
/home/meirkhan/Go/librdkafka/src/rdcrc32.h:102: undefined reference to 'crc32'
/usr/lib/librdkafka.a(rdbuf.o):/home/meirkhan/Go/librdkafka/src/rdcrc32.h:74: more undefined references to 'crc32' follow
/usr/lib/librdkafka.a(rdgz.o): In function 'rd_gz_decompress':
/home/meirkhan/Go/librdkafka/src/rdgz.c:59: undefined reference to 'inflateInit2_'
/home/meirkhan/Go/librdkafka/src/rdgz.c:65: undefined reference to 'inflateGetHeader'
/home/meirkhan/Go/librdkafka/src/rdgz.c:84: undefined reference to 'inflate'
/home/meirkhan/Go/librdkafka/src/rdgz.c:115: undefined reference to 'inflateEnd'
/home/meirkhan/Go/librdkafka/src/rdgz.c:90: undefined reference to 'inflateEnd'
/home/meirkhan/Go/librdkafka/src/rdgz.c:115: undefined reference to 'inflateEnd'
/home/meirkhan/Go/librdkafka/src/rdgz.c:106: undefined reference to 'inflateEnd'
collect2: error: ld returned 1 exit status
`

How to reproduce
================
Install zlib: sudo apt install zlib1g-dev
./configure
make 
sudo make install 
go build -tags static -ldflags "${ldflags}" -o bin/

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [ ] librdkafka version (release number or git tag): `<couldn't find, but year 2018>`
 - [ ] Apache Kafka version: `<2.2.0>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [  ] Operating system: `<Linux ubuntu18 x86_64>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It looks like the linker flags are incomplete, your application needs to be linked with zlib.

The current state of static linking with the Go client is not good, but we're looking to improve it by providing prebuilt static bundles of librdkafka with the Go client itself.
Please try it out by changing your import to `confluent-kafka-go-dev`, e.g:
https://github.com/confluentinc/confluent-kafka-go-example/blob/master/main.go#L23

This is still experimental, but with enough positive feedback we'll move it to confluent-kafka-go, voiding the need for a separate librdkafka install.

**Comment by meirelop** [comment]
Thanks for response.
Yes, I will try that and will leave response later.
But for now, for poruction use, how can I link it to zlib?

**Comment by edenhill** [comment]
add `-lz` to ldflags

**Comment by meirelop** [comment]
> 
> 
> It looks like the linker flags are incomplete, your application needs to be linked with zlib.
> 
> The current state of static linking with the Go client is not good, but we're looking to improve it by providing prebuilt static bundles of librdkafka with the Go client itself.
> Please try it out by changing your import to `confluent-kafka-go-dev`, e.g:
> https://github.com/confluentinc/confluent-kafka-go-example/blob/master/main.go#L23
> 
> This is still experimental, but with enough positive feedback we'll move it to confluent-kafka-go, voiding the need for a separate librdkafka install.

Thank you.
confluent-kafka-go-dev seems to work. Is there any approximate date  when you will push it to master or it only depends on feedbacks?

**Comment by edenhill** [comment]
We're doing public beta now (confluent-kafka-go-dev) and with enough positive feedback we're looking to merge this into a release in a month or so.

**Comment by oswee** [comment]
Confirm. This one builds well in my setup. And it even works! :D

**Comment by wushuang5112** [comment]
Yes，can't find zlib link, I use Visual Stdio 2017 to link the lib,but not fount suit package 'zlib.**v141**.windesktop.msvcstl.dyn.rt-dyn', so how can I do it.
I am browser the source web site  http://todorepositorylocation.com/, but it can't open, may it hasn't maintain.

Can we should change the zlib sourse?
