### ISSUE TITLE
Does any C++ API invoke rd_kafka_consume_callback

### ISSUE THREAD

**Issue by michema** [edenhill/librdkafka#245]
Hi, Magnus:

The current C++ API consume invokes rd_kafka_consume(). Is there any plan to integrate rd_kafka_consume_callback() for C++ API?

Thanks,

Michelle

**Comment by edenhill** [comment]
The plan is to support all relevant C APIs in the C++ API, and this is an ongoing effort.
Requesting specific APIs, like you do here, speeds that up :)
So is this a request for consume_callback in C++?

**Comment by michema** [comment]
Yes, because it has a better performance.

**Comment by kodekarl** [comment]
I made a draft of this (in the context of #168) some time ago. I'll rebase it, fix it up a little, and let you have a look. Hang on.

**Comment by edenhill** [comment]
Now fixed, by kodekarl, in PR #250
