### ISSUE TITLE
[Question] Is there any way to sync with results of async operations?

### ISSUE THREAD

**Issue by abyss7** [edenhill/librdkafka#2455]
The operations of interest are:
- pause/resume
- subscribe/unsubscribe

The related calls to `rd_kafka_resume_partitions()`, `rd_kafka_pause_partitions()`, `rd_kafka_subscribe()`, etc. just put a task into some queue which is processed by another thread async. I can't find any high-level mechanism (like future-promise) to sync with a result of these operations, and can't figure out how to check if operation is completed within a couple lines of code.

The basic scenario:
1. Check if consumer is subscribed to anything.
2. If not, then pause all consumption - to not accidentally read any messages while polling for subscription messages. Wait for pause to apply.
3. Subscribe and poll with timeout until anything gets assigned.
4. Resume and wait for it - especially if subscription gone wrong and failed.

**Comment by abyss7** [comment]
The better description of high-level scenario.

If consumer is not subscribed (or assigned) to anything, then subscribe it in sync way, make sure it's resumed, and make sure that next call to `poll()` will return new messages if there are any on broker-side.

**Comment by edenhill** [comment]
pause/resume..() are currently asynchronous, as you say, but it is probably a good idea to make them synchronous.

**Comment by edenhill** [comment]
Fixed
