### ISSUE TITLE
kafka Transaction support

### ISSUE THREAD

**Issue by nleeuskadi** [edenhill/librdkafka#2458]
Description
===========
Does librdkafka support transactional producer which allows transactional consume-transform-produce pattern?
I can't find any example of it with librdkafka.

How to reproduce
================
check the git repo 

Checklist
=========
 - [x] librdkafka version : V1.1.0
 - [x ] Apache Kafka version: V2.2.1

**Comment by rolandyoung** [comment]
Not yet.
Please see issue #1308

**Comment by pinsker88** [comment]
any progress?

**Comment by edenhill** [comment]
Transaction support was released in v1.4.0.
