### ISSUE TITLE
kafka_2.11-2.1.0 producer use transaction mode, if abort transaction, consumer error_callback() will report  “Message size too large”?

### ISSUE THREAD

**Issue by JiangXiao2019** [edenhill/librdkafka#2460]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by JiangXiao2019** [comment]
kafka server version 2.11-2.1.0
producer uses transaction mode.
consumer uses librdkafka 1.0 RC7, pull message mode.
if producer aborts a transaction, then kafka server will post a "transaction control message" to consumer? librdkafka can process it?  there are many "message with error: Broker: Message size too large" error in my log, but as I know, each message size is very small and the max message size paramters are big enough.

**Comment by edenhill** [comment]
@JiangXiao2019 Upgrade to a proper version, such as v1.1.0.

**Comment by JiangXiao2019** [comment]
Could you tell me v1.1.0 reolved which issue?  compatible with kafka 2.11-2.1.0 or resolved "Message size too large" error?  Further more,  whether v1.1.0 support kafka transaction?

**Comment by edenhill** [comment]
The control messages should be properly handled by v1.1.0.

The next version of librdkafka, v1.2.0, will support transactions on the consumer - filtering out non-committed messages.

**Comment by JiangXiao2019** [comment]
@edenhill Thanks for your answer.  I will be waiting v1.2.0.
