### ISSUE TITLE
Consumer: Local: Unknown partition - store offset

### ISSUE THREAD

**Issue by Mohamed-Mosaad** [edenhill/librdkafka#2462]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
My consumer is getting "Local: Unknown partition" when trying to store offset after processing the msg.
My understanding was that it means this partition is no longer assigned to this instance of the consumer and it has been reassigned to another consumer in the same consumer group, so it's not an issue.

However looking at the documentation here: https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L195

It says "/** Permanent: Partition does not exist in cluster. */
	ERR__UNKNOWN_PARTITION = -190,"
Partition does not exist in cluster looks worrying, Now I am not sure whether this is an issue or not.

How to reproduce
================
 I didn't particularly  reproduce it , however I have 10 consumers in the same group polling frequently from a topic with 4 partitions(so 6 are idle) and I get "Local: Unknown partition" couple of times a day.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [0.11.5] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [enableAutoOffsetStore=False, rest is default ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [Linux ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
offsets_store()/offset_store() will return ERR__UNKNOWN_PARTITION if a given partition is not known internally/locally, which typically means the partition does not exist on the cluster or that the topic is not consumed (subscription or assignment changed).

**Comment by Mohamed-Mosaad** [comment]
thanks.
