### ISSUE TITLE
So, ERR__ASSIGN_PARTITIONS is not an error?

### ISSUE THREAD

**Issue by yushizhao** [edenhill/librdkafka#2463]
Every time when subscribe to a broker, a consumer get ERR__ASSIGN_PARTITIONS. This is actually normal right?

**Comment by edenhill** [comment]
Correct, that's a non-error event (despite the ERR__ prefix) indicating that a new consumer assignment has been received, there is also a REVOKE_PARTITIONS when the assignment has been revoked.
