### ISSUE TITLE
Question: rd_kafka_set_log_queue

### ISSUE THREAD

**Issue by nick-zh** [edenhill/librdkafka#2467]
Dear Magnus
I have the following configs set:
```
log_level = 7
debug= all
log.queue = true
```
I am not sure if i am using this correctly:
```
log_queue = rd_kafka_queue_new(rk);
rd_kafka_set_log_queue(rk, log_queue);
rd_kafka_conf_set_log_cb(conf, kafka_conf_log_cb);
```
My assumption is, that this would be enough to get my `kafka_conf_log_cb`
called when i am calling `rd_kafka_consumer_poll(rk, timeout_ms);`
during message consumption.
Am i missing something, because somehow my callback is not executed.
Thanks in advance for the help!

Cheers,
Nick

**Comment by edenhill** [comment]
When you redirect logs to a custom queue you will need to poll that queue explicitly to get log events, see rd_kafka_queue_poll() for returning the log as an event, or rd_kafka_queue_poll_callback() for triggering event callbacks.
