### ISSUE TITLE
Suppress 'Failed to finish gzip compression' logs

### ISSUE THREAD

**Issue by clusby** [edenhill/librdkafka#2472]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
On the same topic, I'm producing mostly large messages and also infrequent small messages.

I need to use gzip compression on the topic for the large payloads, but this leads to warnings being logged:

eg:
"%3|1528528646.620|GZIP|rdkafka#producer-1| [thrd:109.XXX.XX.XX:9092/bootstrap]: 109.XX.XX.XX:9092/1: Failed to finish gzip compression  of 23 bytes for topic Test [2]:  (0): sending uncompressed"

Example someone else has reported using Python:
https://github.com/confluentinc/confluent-kafka-python/issues/398

Clients should be able to suppress these warnings - everything is still working as expected from a client perspective.

How to reproduce
================
See: https://github.com/confluentinc/confluent-kafka-python/issues/398

I'm using Python 2.7.8, confluent-kafka==0.11.5

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.5 (python confluent-kafka==0.11.5)
 - [x] Apache Kafka version: 0.11
 - [x] librdkafka client configuration: compression.codec = gzip
 - [x] Operating system: Centos 7
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I don't really understand why gzip fails here, can you try to reproduce this on librdkafka v1.1.0?

**Comment by clusby** [comment]
I'm using your rdkafka indirectly via python (confluent-kafka lib), so this will be tricky for me.

I think it would still exhibit in v1.1.0 though
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_msgset_writer.c#L1004

It's just on very small messages (eg < 50 bytes). So the behavior of sending uncompressed is fine iin this case.

The zlib docs do suggest to retry the deflate() again if Z_OK or Z_BUF_ERROR is returned: https://www.zlib.net/manual.html
> If the parameter flush is set to Z_FINISH, pending input is processed, pending output is flushed and deflate returns with Z_STREAM_END if there was enough output space. If deflate returns with Z_OK or Z_BUF_ERROR, this function must be called again with Z_FINISH and more output space (updated avail_out) but no more input data, until it returns with Z_STREAM_END or an error. After deflate has returned Z_STREAM_END, the only possible operations on the stream are deflateReset or deflateEnd.

Although unclear what it is actually returning.

**Comment by edenhill** [comment]
Thanks for looking up the details, much appreciated!

If deflate() requires more output space it means deflateBound() returned an insufficient size (which it may do since we call deflateBound() for the entire buffer chain size, but pass each buffer to deflate()).
We could of course grow the buffer, but that's a costly operation and since this only seems to happen for very small input sizes I think we might actually be better off skipping compression altogether if the input size is smaller than some per-compression-type minimum threshold, saving precious CPU cycles on the producer, broker and consumers.

*note: librdkafka already throws away the compressed buffer if compression succeeds but the compressed data is larger than the uncompressed data.*

Some googling suggests a threshold around 100 bytes:
https://stackoverflow.com/questions/5737189/minimal-data-size-for-zlib-compression

So maybe we should start out at a conservative 75 byte threshold.

**Comment by clusby** [comment]
After a quick test, it might not actually be as straight forward as just setting a minimum compression threshold.

Using data that may be for zlib to compress:
```
from confluent_kafka import Producer
producer = Producer( {'compression.type':'gzip', ...})
...
value = "123456789abcdefghijklmnopqrstuvwxyz!@#$%^&*()-=_+/?<>:\";'[]{}ABCDEFGHIKJKLMNOPQRSTUVXYZ982347654321zhdkfjuruwpqoekdkxlkcv,msadf340965LKSDIE!@)(*(*$%(*&$[]SDFOKJEadslfkjwelrkj)(@#$(*$(*2139483498"
producer.produce("test.topic", key=None, value=value)
```

So it fails 203 bytes...
```
%3|1565918423.599|GZIP|rdkafka#producer-2| [thrd:X.X.X.X:X/X]: X.X.X.X:X/X: Failed to finish gzip compression  of 203 bytes for topic test.topic [0]:  (0): sending uncompressed
```

And if gzip has a better chance at compression (17 bytes):
```
    results_kafka_producer.send_items([ (None, "1111111111") ])

> %3|1565918802.716|GZIP|rdkafka#producer-2| [thrd:10.166.137.52:7051/4]: 10.166.137.52:7051/4: Failed to finish gzip compression  of 17 bytes for topic lusby-uat.pt.us_gas.position.v8 [0]:  (0): sending uncompressed
```

But then add just one more '1' it then compresses ok - I get no 'sending uncompressed' error:
```
    results_kafka_producer.send_items([ (None, "11111111111") ])
```

Probably needs some more testing with the underlying zlib library.

**Comment by edenhill** [comment]
Thanks for the thorough exploration!

I think the proper way to fix this is compress to a buffer chain, so that new buffer space can be added if there is not enough space, rather than reallocating the whole chunk (which is costly).

Will look into this after the 1.2 release.

**Comment by edenhill** [comment]
Fixed
