### ISSUE TITLE
'Broker: Message size too large' not always a broker error

### ISSUE THREAD

**Issue by 65278** [edenhill/librdkafka#2474]
Description
===========
rd_kafka_msg_new() can fail with RD_KAFKA_RESP_ERR_MSG_SIZE_TOO_LARGE, which is described as "Broker: Message size too large" in rd_kafka_err_descs[].
This here is not a broker- but a local failure, which is highly misleading.
Kafkas own producer handles this edge case by overwriting the message string in the constructor of its exception handler and thus avoids wild goose chases. I believe a similar feature would be useful here.

How to reproduce
================
I'll leave reproduction as an exercise to the reader. It involves producing a message larger than message.max.bytes (where the naming convention has sufficiently diverged from Kafkas max.request.bytes and message.max.bytes to cause further confusion).

Checklist
=========
 - [x] librdkafka version v1.1.0 and all before that

**Comment by edenhill** [comment]
While it might have been a lapse to reuse the broker-side error code for this error, even though it should be relevant given that broker and client configuration is in sync, we can't change it now without breaking the API.

The produce() error codes are documented [here](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L3664).

**Comment by 65278** [comment]
This is a valid issue, breaking the API is not grounds for closing it.
A low cost fix could even be just changing the error string to 'Local/Broker', I'd expect people don't considering error strings part of a stable api.

**Comment by edenhill** [comment]
The error codes specified in the kafka protocol (positive integers) are prefixed with "Broker: " while the librdkafka-specific error (negative integers) are prefixed with "Local: ".

If your produce() call fails with RD_KAFKA_RESP_ERR_MSG_SIZE_TOO_LARGE it means your message size exceeds the client's configured message size.
If your delivery callback fails with RD_KAFKA_RESP_ERR_MSG_SIZE_TOO_LARGE it means your message size exceeds the broker's configured message size.
