### ISSUE TITLE
Is group.instance.id implemented?

### ISSUE THREAD

**Issue by adrian-vlad** [edenhill/librdkafka#2475]
Description
===========
Is group.instance.id missing from librdkafka?

I'm having some issues with consumers taking too much time before starting to receive messages (6 seconds) and I tried to avoid consumer rebalances by using this setting, but it seems it's not implemented.

How to reproduce
================

Checklist
=========

Please provide the following information:

 - [ ] librdkafka version (release number or git tag): I'm using it with confluent_kafka_python 1.1.0
 - [x] Apache Kafka version: `2.3.0`
 - [ ] librdkafka client configuration:
 - [x] Operating system: `Debian 9`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rnpridgeon** [comment]
It's missing in that librdkafka does not yet support static group membership as defined in KIP-345. This is something we are currently working on though so it should be available in the near future.

**Comment by adrian-vlad** [comment]
That would be really helpful. Thank you!

**Comment by chrisdone** [comment]
Is this still unsupported? I'm seeing `No such configuration property: \"group.instance.id\"` when attempting to use it, but could find no other reference than this issue about it.

**Comment by edenhill** [comment]
It will be available in the upcoming v1.4.0 release, scheduled for release end of march.

**Comment by chrisdone** [comment]
Thanks @edenhill.

**Comment by Maatary** [comment]
Hi all / @edenhill , i have kafka stream 2.4.1 but i can't find the configuration enum, is it supported yet ?

**Comment by edenhill** [comment]
Yes, group.instance.id was added to librdkafka v1.4.0
