### ISSUE TITLE
Couldn't find zstd file while creating cmake build

### ISSUE THREAD

**Issue by Detril** [edenhill/librdkafka#2486]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I'm trying to create the cmake build as instructed in the /packaging/cmake/README.md file.
I have zstd v1.3.1 installed.
I have encountered the following error:

```
/home/user/rdkafka/librdkafka-1.1.0/src/rdkafka_zstd.c:38:25: fatal error: zstd_errors.h: No such file or directory
compilation terminated.
src/CMakeFiles/rdkafka.dir/build.make:855: recipe for target 'src/CMakeFiles/rdkafka.dir/rdkafka_zstd.c.o' failed
make[2]: *** [src/CMakeFiles/rdkafka.dir/rdkafka_zstd.c.o] Error 1
CMakeFiles/Makefile2:102: recipe for target 'src/CMakeFiles/rdkafka.dir/all' failed
make[1]: *** [src/CMakeFiles/rdkafka.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

In case it might be useful, here is the results of the command I ran before encountering such error:
```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pow in m
-- Looking for pow in m - found
-- Found ZSTD: /usr/lib/x86_64-linux-gnu/libzstd.so  
-- Found Zstd: /usr/lib/x86_64-linux-gnu/libzstd.so
-- Checking for module 'libsasl2'
--   Found libsasl2, version 2.1.26
-- Found LZ4: /usr/lib/x86_64-linux-gnu/liblz4.so (found version "1.7.1") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found ZSTD: /usr/lib/x86_64-linux-gnu/libzstd.so
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/rdkafka/librdkafka-1.1.0/_cmake_build
```
Thanks in advance for any help!

How to reproduce
================
From top-level librdkafka directory, run the following commands:

```
$ cmake -H. -B_cmake_build
$ cmake --build _cmake_build
```

Checklist
=========
 - [x] librdkafka version (release number or git tag): v1.1.0 release
 - [x] Apache Kafka version: 2.3.0
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `Ubuntu 16.04.6 LTS`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Looks like:
 cmake is not checking that zstd_errors.h is available
and
 your libzstd-dev package is too old and does not contain zstd_errors.h.
 I recommend upgrading libzstd-dev.

**Comment by Detril** [comment]
My libzstd-dev is the latest version (0.5.1-1), but I have installed it with 'sudo apt install libzstd-dev'. Is it possible that I have to manually build it?

**Comment by Detril** [comment]
I have purged the libzstd-dev and reinstalled it again. I ran:
```
./configure --install-deps --source-deps-only
sudo make
sudo make install
```

And it worked this time!

I don't understand why ZSTD was causing problems, but it seems to have fixed itself. Thank you for your support.

**Comment by zheolong** [comment]
Fix dependency problems: 

```
pip install grpcio; pip install --user grpcio-tools;
sudo yum install cyrus-sasl-devel cyrus-sasl-lib libzstd-devel
```
