### ISSUE TITLE
[question] Is there a way to install latest version of librdkafka in Ubuntu 16.04?

### ISSUE THREAD

**Issue by kolinko-ant** [edenhill/librdkafka#2488]
In ubuntu 16.04 the 0.8.6 version of librdkafka is installed. This one is quite outdated. Can I somehow get the latest version in ubuntu 16.04?

**Comment by edenhill** [comment]
Use Confluent packages, they're always up to date:
https://docs.confluent.io/current/installation/installing_cp/deb-ubuntu.html#systemd-ubuntu-debian-install
