### ISSUE TITLE
librdkafka execute thread question

### ISSUE THREAD

**Issue by lvfuchao** [edenhill/librdkafka#2489]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

#### I coding C++ sdk package based on librdkafka for direct use by business and Start a separate thread to consume the message as follow:

```
bool KafkaConsumeImp::start_consumer() {

    // begin consume thread
    thread_ = std::make_unique<std::thread>([this] {
       this->start();
    }); }

bool KafkaConsumeImp::start() {
   /*Consume messages*/
    if(started_) {
        return -1;
    }
    if(!kafka_consumer_) {
        return -2;
    }
    this->started_ = true;
    try {
        while (EDU_SP_KAFKA::run) {
            //2000毫秒未订阅到消息会触发：RdKafka::ERR__TIMED_OUT=-185(not really error)
            RdKafka::Message *msg = kafka_consumer_->consume(2000);

            //消费完消息之后会触发：RdKafka::ERR__PARTITION_EOF=-191(not really error)
            consumer_cb(msg, nullptr);
            delete msg;
        }
    } catch (std::exception &e) {
        std::cout << "Rdkafka Execption: consumer_ start failure: " << e.what() << " !!!"<< std::endl;
        YY_LOG(LOG_ERR, "Rdkafka Execption: consumer_ start failure: %s !!!", e.what());
        return -4;
    }
    return true;
}
```
#### top:
```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                       
17652 lvfuchao  20   0  539464  91324   4488 S 18.7  0.6   0:14.35 kafka-consumer_                                                               
17645 lvfuchao  20   0  539464  91324   4488 S  0.0  0.6   0:00.00 kafka-consumer_                                                               
17646 lvfuchao  20   0  539464  91324   4488 S  0.0  0.6   0:00.00 rdk:broker-1                                                                  
17647 lvfuchao  20   0  539464  91324   4488 S  0.0  0.6   0:00.09 rdk:main                                                                      
17648 lvfuchao  20   0  539464  91324   4488 S  0.0  0.6   0:00.00 rdk:broker-1                                                                  
17649 lvfuchao  20   0  539464  91324   4488 S  0.0  0.6   0:00.00 rdk:broker1                                                                   
17650 lvfuchao  20   0  539464  91324   4488 S  0.0  0.6   0:00.00 rdk:broker2                                                                   
17651 lvfuchao  20   0  539464  91324   4488 S  0.0  0.6   0:00.42 rdk:broker3 
```
my understanding is:
（1) broke1、broker2、broker3：Used to interact with three kafka clusters

  (2) 17652、17645 < kafka-consumer_..>: I don`t know 

  (3)  17646 、17648 <rdk:broker-1 >: I don`t know

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v1.1.0>`
 - [x] Apache Kafka version: `<2.12-2.3.0>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `<Linux ubuntu x86_64 16.04>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-internal-threads

rdk:brokerX == internal per-broker threads
rdk:main == internal main thread
kafka-consumer_ == your application threads

**Comment by agis** [comment]
@edenhill what about the `rdk:broker-1` thread though? According to the FAQ you linked, there should be N broker threads (N=number of brokers).

In a scenario with 4 brokers, I see:

1. `rdk:broker1`
2. `rdk:broker2`
3. `rdk:broker3`
4. `rdk:broker4`
5. `rdk:broker-1`

1-4 I can understand, it's (5) that stands out to me. What is this about? By stracing it I only see calls to `futex`.

**Comment by abhimanyuseth-alation** [comment]
@edenhill 
I have the same question about broker-1. I see 24 of these threads!
```
(env) PROD [alationadmin@alationfc-0 bin]$  top -bn1 -o +%MEM -w512 -H -p 12532 | grep broker-1$ | wc -l
24
```
