### ISSUE TITLE
Missing msgs from compacting topic

### ISSUE THREAD

**Issue by shanson7** [edenhill/librdkafka#2492]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

We are seeing an issue with compacting topics. We have a consumer that on start up reads from the beginning of a topic and occasional new messages come in. It looks like after a while, on restart not all messages are consumed back from the topic. I can't get the messages from the topic using a standalone librdkafka based consumer either. However, the missing messages do show up using kafka-console-consumer.  This tells me that the messages do exist in kafka.  

I have a *ton* of logs but I'm not sure what would relevant to this issue. I can try out whatever suggestions you might have.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): consumer/producer 0.11.5 and also tried consumer w/ version 1.1.0 
 - [x] Apache Kafka version: `1.1.0`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `rhel7`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
As a start run librdkafka with `debug=fetch,msg,protocol` and see if there's anything funny-looking in the logs around the offsets that are missing from the librdkafka consumer but seen in the Java consumer.
Things to look for are parse errors, skipped offset intervals between Fetch requests, etc.

**Comment by edenhill** [comment]
I wonder if this is a manifestation of https://github.com/edenhill/librdkafka/commit/9aed3142bc35085553b28f4b56615c0bd80f872c

Could you try latest master?

**Comment by shanson7** [comment]
Seems to be fixed on master
