### ISSUE TITLE
Add support for boost asio

### ISSUE THREAD

**Issue by progovoy** [edenhill/librdkafka#2493]
Add support for boost asio
===========
Hi,

I would like to add a boost asio binding to your library. I would like to hear your opinion on this one and if such a feature would be interesting for you.

Thanks.

**Comment by edenhill** [comment]
What is it you are trying to achieve?
If you want to integrate librdkafka's poll functions with asio you can use the io events:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2944

As for using Boost from librdkafka itself; that's a no, we don't want that dependency (and the IO parts are in C anyway)

**Comment by alexhultman** [comment]
@edenhill I need to integrate with asio: https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/reference/posix__basic_descriptor/async_wait.html

Do you have some pointers for where to start? What types of async operations are needed? Socket fds, timers, anything more? Does anything like this exist? Is there any preferred architecture for adding asio event-loop support? You mentioned io events - any docs on this?

**Comment by edenhill** [comment]
Look at rd_kafka_queue_io_event_enable() and rd_kafka_queue_queue_event_enable() that provide two different methods for your dispatcher to get notified when there's a new event (e.g., a message) on a queue.

**Comment by alexhultman** [comment]
So with rd_kafka_queue_io_event_enable I can create a unix pipe (https://man7.org/linux/man-pages/man2/pipe.2.html), give librdkafka one fd and use asio to poll for the other one, then use that to read from the queue?

**Comment by edenhill** [comment]
Yep, that's the idea.

For the producer you would enable io_event on the main queue (rd_kafka_queue_get_main()), and on the consumer the consumer queue (rd_kafka_queue_get_consumer()).

**Comment by alexhultman** [comment]
I can't find anything on rd_kafka_queue_queue_event_enable - google is empty for that one, is rd_kafka_queue_io_event_enable the only thing I need to use?

**Comment by edenhill** [comment]
Sorry, that should be `rd_kafka_queue_cb_event_enable()` which triggers a callback instead of writing on the fd. Choose the one that's most practical for your use-case.

**Comment by alexhultman** [comment]
Wow rd_kafka_queue_cb_event_enable is super useful - I assume it is called from some background thread so all you really need to "integrate" with asio is call boost::asio::io_context::post (https://www.boost.org/doc/libs/1_77_0/doc/html/boost_asio/reference/io_context/post.html) to end up on the event-loop's thread. That's like 5 lines of code!
