### ISSUE TITLE
Invalid value for configuration property "compression.codec"

### ISSUE THREAD

**Issue by lvfuchao** [edenhill/librdkafka#2496]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Hello edenhill,

Unable to create configuration for Kafka "compression.codec". as follow:
% Invalid value "gzip" for configuration property "compression.codec"
% Invalid value "zstd" for configuration property "compression.codec"

but use snappy and lz4 is ok。

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v1.1.0>`
 - [x] Apache Kafka version: `<2.12-2.3.0>>`
 - [x] librdkafka client configuration: `<compression.codec [none, gzip, snappy, lz4, zstd]>`
 - [x] Operating system: `<Linux ubuntu x86_64>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Your librdkafka library was built without support for gzip (requires zlib1g-dev) and zstd (requires libzstd-dev).

**Comment by lvfuchao** [comment]
ok I Know thanks

**Comment by mateusjunges** [comment]
@edenhill which library is required to build with support for snappy? I'm getting the same message but with snappy compression.

**Comment by edenhill** [comment]
snappy is always builtin. What version of librdkafka are you using?

**Comment by edenhill** [comment]
Check how librdkafka is built. With the standard configure & make it will always include snappy support.

**Comment by vutien071294** [comment]
Hello edenhill,
i use php 7.4 and i installed zlib1g-dev, but error :
Invalid value "gzip" for configuration property "compression.codec"
still happens.
![image](https://user-images.githubusercontent.com/24518398/175820828-2588090c-3bf3-4f19-9c44-953daaef8c48.png)
can you help me
