### ISSUE TITLE
qst: log rotation

### ISSUE THREAD

**Issue by GeorgeShagov** [edenhill/librdkafka#2497]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ
done

Description
===========
Is it possible to output logs to rotatable file?

How to reproduce
================
NA

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version 1.0.0
 - [ ] Apache Kafka version: `0.10.2.3`
 - [x] Operating system: `Ubuntu 18.04`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There is no builtin file logger in librdkafka, but it does provide a syslog logger and syslog will do rotation, or write your own log callback that does rotation.

`rd_kafka_conf_set_log_cb(conf, rd_kafka_log_syslog);`
