### ISSUE TITLE
the "request.required.acks" config question

### ISSUE THREAD

**Issue by lvfuchao** [edenhill/librdkafka#2499]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Hello edenhill,

## there is an question when I use "request.required.acks"

1. when I not set  "request.required.acks" config , it used default (-1) ,when I produce 100,000 messages, 600 bytes per message There will be a loss of message。
2. when I set acks = 1, There Will not lose the message

According to the cluster configuration "buffer.memory", the default 32M, because the production speed is too fast, so that the buffer is full of blocking), but when acks=1, I did not appear to lose the message when testing (I don`t understand, because The production speed is about the same. Can it be said that kafka will only send a message after receiving the ack? If it does not receive the ack, it will rewrite the current message to the buffer and try again. If it is received, the message will be cleared. and Send next batch message 

so I don`t know "request.required.acks"  Impact on the producer, can you explain it to me in detail?

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<<v1.1.0>`
 - [x] Apache Kafka version: `<2.12-2.3.0>`
 - [x] librdkafka client configuration: `<"request.required.acks" [-1, 1, 0]>`
 - [x] Operating system: `<Linux ubuntu x86_64>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Messages will not be lost.

If your produce() call fails, check the error code and take action accordingly.
If your produce() call succeeds you will eventually get a delivery report callback for the message, if the delivery report has an error it means the message failed to produce.

Which case are you seeing? And what is the error code you get?

**Comment by lvfuchao** [comment]
## 1. the code as follow:
```
    while ( isRunning ) {
        if (times > 100000)
            break;
    RdKafka::ErrorCode resp = kafka_producer_->produce(kafka_topic_.get(),
                                                       partition_,
                                                       ProducerConfig::Instance()->getProducerConfigMsgflags(),
                                                       data,
                                                       data_len,
                                                       (key.empty())?nullptr:&key,
                                                       nullptr);

        printf("%% %d messages (%lu bytes) producer success !!!",
               (times*1), (times*jsonStr.size()));
        times ++;
    }
```

## 2. the err event is:
```
101637 LOG-5-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out ProduceRequest in flight (after 60712ms, timeout #0)
101638 % "LOG": event is a log message: LOG-5-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out ProduceRequest in fli       ght (after 60712ms, timeout #0)
101639 LOG-5-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out ProduceRequest in flight (after 60712ms, timeout #1)
101640 % "LOG": event is a log message: LOG-5-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out ProduceRequest in fli       ght (after 60712ms, timeout #1)
101641 LOG-5-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out ProduceRequest in flight (after 60712ms, timeout #2)
101642 % "LOG": event is a log message: LOG-5-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out ProduceRequest in fli       ght (after 60712ms, timeout #2)
101643 LOG-5-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out ProduceRequest in flight (after 60712ms, timeout #3)
101644 % "LOG": event is a log message: LOG-5-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out ProduceRequest in fli       ght (after 60712ms, timeout #3)
101645 LOG-5-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out ProduceRequest in flight (after 60712ms, timeout #4)
101646 % "LOG": event is a log message: LOG-5-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out ProduceRequest in fli       ght (after 60712ms, timeout #4)
101647 LOG-4-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out 1429 in-flight, 0 retry-queued, 0 out-queue, 0 partial       ly-sent requests
101648 % "LOG": event is a log message: LOG-4-REQTMOUT: [thrd:183.36.117.51:9292/bootstrap]: 183.36.117.51:9292/2: Timed out 1429 in-flight, 0 ret       ry-queued, 0 out-queue, 0 partially-sent requests
```

**Comment by edenhill** [comment]
1. You're not checking the return value from produce. If the produce() call fails you will not know about it. There will be no delivery report for messages who are not accepted by produce()
You specifically need to handle ERR__QUEUE_FULL , by calling poll(100) and then retrying the produce() call.

2. Looks like your network or broker can't keep up. You can increase thruput by increasing the producer batch buffering time, set linger.ms=50. See https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#high-throughput

**Comment by edenhill** [comment]
This is what your produce loop should look like:
https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_simple_producer.c#L209

**Comment by lvfuchao** [comment]
but when I set acks = 1, the same code ,  linger.ms = default = 0.5 there is no message lost。
so I really don`t know the acks Ack an influence on producers

**Comment by lvfuchao** [comment]
and the same producer code , why acks=-1 the queue is full but acks = 1 the queue is nou full

**Comment by lvfuchao** [comment]
My understanding as follow:
When the producer push a message and receives a ack from the broker, it will delete this message. If it does not receive the ack, it will re-join the buffer and wait for resend.

Acks = -1 Because all the broker's acks are received very slow,  so the old messages  in the buffer can't be cleared, then buffer blocked, and the latter messages are lost.

**Comment by lvfuchao** [comment]
I Set linger.ms = 500 、debug = msg  、acks = 1 

there is no

**Comment by lvfuchao** [comment]
I Set linger.ms = 500 、debug = msg 、acks = 1、message.max.bytes = 1000000（default）、batch.num.messages = 10000（default）

there is no another err msg，and message not lost，but occurred follow problem , I don`t Know what happened

`191862 LOG-7-PRODUCE: [thrdserver1:9292/bootstrap]: server1:9292/3: test_sdk7 [1]: No more space in current MessageSet (1634 messag       e(s), 999553 bytes)`
