### ISSUE TITLE
While testing with `ut_handle_ProduceResponse`, `idempotence`  doesn't work if `max.in.flight > 1`

### ISSUE THREAD

**Issue by kenneth-jia** [edenhill/librdkafka#2501]
Description
===========
We're trying to test with `idempotence` feature and glad to see that there's a `ut_handle_ProduceResponse` stub.
However, there seems some problem while `max.in.flight>1`. It shows not `idempotence` in that case.

Librdkafka version:
================
1.1.0

How to reproduce
================
1. Define a callback function for `ut_handle_ProduceResponse`, which would always response `RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE` for a certain `seq_id`. E.g., always response failure for `seq_id: 5`.
2. Start a producer with configuration: "acks"="all", "batch.num.messages"="1", "enable.idempotence"="true", "max.in.flight"="2", and with the previously defined `ut_handle_ProduceResponse`.
3. Let the producer send 10 messages. The seq_id would be 1, 2, ...10.  Note: we always response `seq_id:5` with `RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE` failure.
4. We check in the delivery callback, each of these 10 messages (i.e,[1,2,3,4,5,6,7,8,9,10]) would be delivered successfully, (not only [1,2,3,4]), even including `seq.id: 5`!

So, how could it be possible? Is it a problem within the ut stub, or within `idenpontence` implementation? The brokers never response success to a certain message, but with `max.in.flight>1' configured, all these message would be reported as `delivered successfully`?

**Comment by edenhill** [comment]
The unit test functions, ut_.., are for internal librdkafka use only and their use are not supported.
