### ISSUE TITLE
rd_kafka_produce produce success of topic even though the topic doesn't exist

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#2502]
Description
===========
I am using simple producer from example dir.
I have implemented SYNC mode. I am testing a few negative things. Sometimes  rd_kafka_produce() gets success on the topic which doesn't exist on the broker.

it should fail as follow:
> Failed to produce to topic xyz_test: Local: Unknown topic

yes, if it produced success and enqueued message,  later I get a response from dr_msg_cb()
> % Message delivery failed: Broker: Unknown topic or partition

Can you think, why these happened? 

How to reproduce
================
Modify rdkafka_simple_producer.c in Sync mode and produce multiple messages frequently.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.1.0`
 - [x] Apache Kafka version: `1.1.1`
 - [ ] librdkafka client configuration: `queue.buffering.max.ms = 1`
 - [ ] Operating system: `Ubuntu Linux`
 - [x] Critical issue

**Comment by edenhill** [comment]
The producer is asynchronous, it will accept messages, without blocking, before it has managed to connect to the cluster.
Any messages produce()d prior to the metadata of the topic being known (which happens after connecting to the cluster) will fail as soon as the metadata is known.
Any messages produce()d to a non-existent topic after the metadata is known will fail the produce() call immediately.
