### ISSUE TITLE
supply allocator. 

### ISSUE THREAD

**Issue by OrenHadaya** [edenhill/librdkafka#2505]
i would like to use the cpp KafkaConsumer class, but in the example it looks like the lib allocate and free each message buffer. My question is, is there a way to avois all this memory allocations by using my allocator ? and still use the cpp high level API ? 

Thanks 
Oren

**Comment by edenhill** [comment]
There is currently no support for pluggable allocators, but there's a PR for it.

**Comment by umashankartm** [comment]
Hi,

Any plans for adding this feature? I am working on a project that requires having a custom allocator. 

~tmu

**Comment by edenhill** [comment]
If possible, try to overload malloc, calloc, free, realloc, strdup and strndup, perhaps with LD_PRELOAD.

Making the allocator pluggable is a big change and there is very little demand for it, so there are no plans to do it.
