### ISSUE TITLE
Can one consumer application consume messages from multiple partitions?

### ISSUE THREAD

**Issue by longli97** [edenhill/librdkafka#251]
Hi, Magnus:

From the document, it looks like that one consumer application can only consume messages from one specified partition (the partition number is required). Is there a way to make one consumer application consume messages from multiple or all partitions from the same topic? 

Also, is there a plan to support consumer group?

Thanks

**Comment by edenhill** [comment]
You can call `consume_start()` on multiple partitions, but you will have to know which partitions are available first, and for this you can use the `rd_kafka_metadata()` API.
To avoid having to call `rd_kafka_consume()` on each partition separately, a shared queue can be set up that routes each partitions messages  to a single queue that can be consumed in just one call (`rd_kafka_queue_new()` and `rd_kafka_consume_queue()`).

kafkacat does this (when no `-p <part>` argument is given), see here:
https://github.com/edenhill/kafkacat/blob/master/kafkacat.c#L369

And this is a primer on the queue usage:
https://github.com/edenhill/librdkafka/wiki/Consuming-from-multiple-topics-partitions-from-a-single-thread


Broker based consumer groups will be supported by the time Apache Kafka 0.9 is released.
The current zookeeper based consumer groups probably will not be available.

**Comment by longli97** [comment]
So if I have four partitions, does the code like this:

/*start partition*/
int i=0;
for(i=0;i<4;i++){
   rd_kafka_consume_start (i);  // start partition i   (or rd_kafka_consume_start_queue(i) ?)
}

/*consume messages*/
rd_kafka_consume_queue();

/*stop consumer*/
for(i=0;i<4;i++){
   rd_kafka_consume_stop (i);  // stop partition i
}

Do you have any example about it?

Thanks

**Comment by edenhill** [comment]
Yep, thats the general idea.

See kafkacat for an example:
https://github.com/edenhill/kafkacat/blob/master/kafkacat.c#L369
