### ISSUE TITLE
Java JAAS configuration is not supported

### ISSUE THREAD

**Issue by notobject** [edenhill/librdkafka#2510]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>

int main() {
    std::string topicName = "TestTopic";
    std::string errstr;
    int throughput = 0;
    int32_t partition = RdKafka::Topic::PARTITION_UA;

    std::cerr << now() << ": librdkafka version "
              << RdKafka::version_str()
              << "(" << RdKafka::version() << ")"
              << std::endl;

    RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);

    if (conf->set("bootstrap.servers", "[XXXXXXXXX]:9092", errstr) != RdKafka::Conf::CONF_OK) {
        std::cerr << now() << ": " << errstr << std::endl;
        exit(1);
    }
    if (conf->set("security.protocol", "SASL_PLAINTEXT", errstr) != RdKafka::Conf::CONF_OK) {
        std::cerr << now() << ": " << errstr << std::endl;
        exit(1);
    }
    if (conf->set("sasl.mechanism", "PLAIN", errstr) != RdKafka::Conf::CONF_OK) {
        std::cerr << now() << ": " << errstr << std::endl;
        exit(1);
    }
    char auth_str[512];

    sprintf(auth_str, "%s username=\"%s\" password=\"%s\";",
            "org.apache.kafka.common.security.plain.PlainLoginModule required",
            "yarn",
            "l2LKQe290Vs9vO9qG8lM511SM67eNYLSzY8ENU4OX3dscyCJIhE0qmEylKCtYVCiqMMOuTFWVTO+j66GsFfQ4v7G3BU43QCJYvXUh9dNJHchntsl4wgryTl8XoNkbqVFtgPQcs9P8fVp60gw4kR2vYW1Z0zWYEzXHBbO6J3Ej4Q="
    );

    if (conf->set("sasl.jaas.config", auth_str, errstr) != RdKafka::Conf::CONF_OK) {
        std::cerr << now() << ": " << errstr << std::endl;
        exit(1);
    }

    ExampleDeliveryReportCb ex_dr_cb;
    conf->set("dr_cb", &ex_dr_cb, errstr);

    RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);
    if (!producer) {
        std::cerr << now() << ": Failed to create producer: " << errstr << std::endl;
        exit(1);
    }

    RdKafka::Topic *topic = RdKafka::Topic::create(producer, topicName, NULL, errstr);
    if (!topic) {
        std::cerr << now() << ": Failed to create topic: " << errstr << std::endl;
        exit(1);
    }
    static const int delay_us = throughput ? 1000000 / throughput : 10;
    std::string msg = "Test...";
    for (int i = 0; i < 1; i++) {
        RdKafka::ErrorCode resp;
        producer->poll(delay_us / 1000);
        resp = producer->produce(topic, partition,
                                 RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
                                 const_cast<char *>(msg.c_str()),
                                 msg.size(), NULL, NULL);
        if (resp == RdKafka::ERR__QUEUE_FULL) {
            producer->poll(100);
            continue;
        } else if (resp != RdKafka::ERR_NO_ERROR) {
            errorString("producer_send_error", RdKafka::err2str(resp), topic->name(), NULL, msg);
        } else {

        }
        std::cerr << now() << ": " << resp << std::endl;
        usleep(1000);
    }

    delete topic;
    delete producer;

    RdKafka::wait_destroyed(5000);
    std::cerr << now() << ": EXITING WITH RETURN VALUE 0" << std::endl;
    return 0;
}

[root@longduping src]# g++ -c main.cpp && g++ -o demo main.cpp -lrdkafka++ && ./demo
20:16:52.338: librdkafka version 1.1.0(16843007)
20:16:52.338: Java JAAS configuration is not supported, see https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka for more information.

Why i got this error message? 
I was installed cyrus-sasl cyrus-sasl-devel cyrus-sasl-gssapi, before compile librdkafka.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.1.0`
 - [x] Operating system: `Centos 7`

**Comment by edenhill** [comment]
Jaas is a java-specific construct.
Librdkafka is written in C. 

Follow the link in the error message for how to configure sasl.

**Comment by notobject** [comment]
> Jaas is a java-specific construct.
> Librdkafka is written in C.
> 
> Follow the link in the error message for how to configure sasl.

oh~~so i should set `sasl.username`=xxx and `sasl.password`=xxx to conf

**Comment by edenhill** [comment]
Yes, and security.protocol=SASL_SSL (or SASL_PLAINTEXT for non-SSL) and sasl.mechanisms=PLAIN

**Comment by notobject** [comment]
Thanks so mush!
