### ISSUE TITLE
help needed: sync producer implementation

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#2512]
Description
===========
We have special requirement for SYNC producer, so I went through instruction given in link https://github.com/edenhill/librdkafka/wiki/Sync-producer

**This is the scenario:**
We do have implemented threading environment on top of librdkafka. In the application, we have 5 worker threads and single thread to poll message delivery using rd_kafka_poll()

SYNC wrapper looks like as follow:

> if (rd_kafka_produce(                                      
>                             /* Topic object */
>                             rkt,                                                                  
>                             /* Use builtin partitioner to select partition*/       
>                             0,                                              
>                             /* Make a copy of the payload. */
>                             RD_KAFKA_MSG_F_COPY,                                                                              
>                             /* Message payload (value) and length */
>                             msg_buf, msg_len,                                                         
>                             /* Optional key and its length */
>                             msg_key, strlen(msg_key),                                     
>                             /* Message opaque, provided in   
>                              * delivery report callback as        
>                              * msg_opaque. */                                                                    
>                              (struct MSG_CALL_BACK_INFO *)msg_call_back_info) == -1)
=======some lines of code here=====

> 					if(SYNC_MODE)
> 						rd_kafka_poll(rk, -1/*blocking*/);

here **msg_call_back_info** is structure pointer contains info which required while delivery call back occurs. 

**problem:**
here in the worker thread rd_kafka_poll() in blocking mode is waiting for a delivery call back.
sometimes, delivery call back entertains by a separate thread which we are running for a delivery call back, so these worker threads remain in a deadlock condition. certainly all the worker threads get blocked.

is there any solution to recover this kind of situations? 

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.0.0`
 - [x] Apache Kafka version: `1.1.1`
 - [x] librdkafka client configuration: `default`
 - [x] Operating system: `ubuntu LINUX`

**Comment by edenhill** [comment]
Run poll in a dedicated thread, and use a conditional variable that you block on in the produce thread.
From the delivery report in the dedicated thread signal the condition variable for wake up.
Pseudo code:
```
struct sync_prod {
   cnd_t cnd;
   mtx_t lock;
   rd_kafka_resp_err_t dr_err;
};

//  in producer thread:
  struct sync_prod sync_prod;
    init cnd and mtx..;
   lock(sync_prod.lock);
   sync_prod.dr_err = -12345;
   produce(.., &sync_prod); <--sync_prod on-stack instance as the msg_opaque
   while (sync_prod.dr_err != -12345)
     cnd_wait(&sync_prod.cnd, &sync_prod.lock);


// in poll thread:
   void dr_msg_cb (..err, ..) {
        struct sync_prod *sync_prod = rkmessage._private;
        sync_prod.err = err;
        cnd_signal(&sync_prod.cnd);
  }
..
   while (run)
      rd_kafka_poll(rk, -1);
```

But you shouldn't really do sync processing, see https://github.com/edenhill/librdkafka/wiki/FAQ#why-is-there-no-sync-produce-interface


hint: use three backticks \`\`\` to make a code area, not >

**Comment by write2jaydeep** [comment]
@edenhill Thank you very much for your help. It works well.
Sorry for wrong code area quote. I will take care of it next time.

Thanks
JD

**Comment by prehistoric-penguin** [comment]
The document is out-dated, I have already modified it:
https://github.com/edenhill/librdkafka/wiki/Sync-producer

I'd like to implement a sync interface for c++11 interface, via the `std::future` mechanism, do you like this future?

@edenhill

**Comment by edenhill** [comment]
@prehistoric-penguin The example is in C, not C++. But a C++ example with std::future would be a nice addition. Create a gist which I can review before you update the wiki page.
