### ISSUE TITLE
Can a consumer application retrieve some metadata information from brokers

### ISSUE THREAD

**Issue by michema** [edenhill/librdkafka#252]
Hi,

To get some metadata (e.g. topics and partitions), I need to provide the address of zookeeper. Is there a way to achieve this by only providing the address of brokers?

Thanks,

**Comment by edenhill** [comment]
Zookeeper is not needed, all the required information is readily available from the broker itself.
So all you need to do is a create an librdkafka CONSUMER or PRODUCER with at least one broker configured `metadata.broker.list` and then call `rd_kafka_metadata()`.

**Comment by michema** [comment]
Thanks.
