### ISSUE TITLE
Consume return null msg when downgrade from v1.0.0 to v0.11.3.

### ISSUE THREAD

**Issue by lxyscls** [edenhill/librdkafka#2521]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We deploy the consumers in docker. When we downgrade the rdkafka's version from v1.0.0 to v0.11.3, the application crashed because the consumer return null msg and the msg_consume in example did not handle this situation.

It's odd, any suggestion?

How to reproduce
================

1. use consumer with v0.11.3
2. upgrade consumer with v1.0.0
3. downgrade consumer with v0.11.3

The consumer's code keeps the same.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v1.0.0 -> v0.11.3
 - [x] Apache Kafka version: 0.10.2.1
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: CentOS Linux release 7.4.1708
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue: docker CE swarm

**Comment by edenhill** [comment]
Both versions will return NULL on timeout.

What example did not handle NULL?

**Comment by lxyscls** [comment]
The msg_consume in rdkafka_example.cpp. Our consumer use the framework of this function.
```
void msg_consume(RdKafka::Message* message, void* opaque) {
  const RdKafka::Headers *headers;

  switch (message->err()) {
    case RdKafka::ERR__TIMED_OUT:
      break;

    case RdKafka::ERR_NO_ERROR:
      /* Real message */
      std::cout << "Read msg at offset " << message->offset() << std::endl;
      if (message->key()) {
        std::cout << "Key: " << *message->key() << std::endl;
      }
      headers = message->headers();
      if (headers) {
        std::vector<RdKafka::Headers::Header> hdrs = headers->get_all();
        for (size_t i = 0 ; i < hdrs.size() ; i++) {
          const RdKafka::Headers::Header hdr = hdrs[i];

          if (hdr.value() != NULL)
            printf(" Header: %s = \"%.*s\"\n",
                   hdr.key().c_str(),
                   (int)hdr.value_size(), (const char *)hdr.value());
          else
            printf(" Header:  %s = NULL\n", hdr.key().c_str());
        }
      }
      printf("%.*s\n",
        static_cast<int>(message->len()),
        static_cast<const char *>(message->payload()));
      break;

    case RdKafka::ERR__PARTITION_EOF:
      /* Last message */
      if (exit_eof) {
        run = false;
      }
      break;

    case RdKafka::ERR__UNKNOWN_TOPIC:
    case RdKafka::ERR__UNKNOWN_PARTITION:
      std::cerr << "Consume failed: " << message->errstr() << std::endl;
      run = false;
      break;

    default:
      /* Errors */
      std::cerr << "Consume failed: " << message->errstr() << std::endl;
      run = false;
  }
}
```

And according to the code, i can't get that there will be msg == NULL.

```
RdKafka::Message *RdKafka::KafkaConsumerImpl::consume (int timeout_ms) {
  rd_kafka_message_t *rkmessage;

  rkmessage = rd_kafka_consumer_poll(this->rk_, timeout_ms);

  if (!rkmessage)
    return new RdKafka::MessageImpl(NULL, RdKafka::ERR__TIMED_OUT);

  return new RdKafka::MessageImpl(rkmessage);

}
```

**Comment by mohakhan** [comment]
with what solution this thread was closed ?

**Comment by edenhill** [comment]
@mohakhan What problem are you seeing? Afaict consume() can't return NULL.
