### ISSUE TITLE
rdkafka_performance shows decreasing throughput

### ISSUE THREAD

**Issue by benp20** [edenhill/librdkafka#2522]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I am running  rdkafka_performance to identify message through put to my broker. I notice that the throughput keeps progressively decreasing as the test runs (logs shown below) starting from 46k msg/sec to down to 28k msg/sec over a couple of minutes. Any inputs on something fundamental in how kafka brokers  or the rdkafka performance test work that may be causing this?

How to reproduce
================
rdkafka_performance -P -l -t test-topic -b <broker url>  -c 10000000 -s 1000

**Output:**

% 1346537 messages produced (1346537000 bytes), 846537 delivered (offset 8549879, 0 failed) in 18086ms: 46803 msgs/s and 46.80 MB/s, 2709 produce failures, 500000 in queue, no compression
% 1387109 messages produced (1387109000 bytes), 887141 delivered (offset 8553551, 0 failed) in 19087ms: 46477 msgs/s and 46.48 MB/s, 2986 produce failures, 499968 in queue, no compression
% 1424362 messages produced (1424362000 bytes), 924368 delivered (offset 15509481, 0 failed) in 20089ms: 46012 msgs/s and 46.01 MB/s, 3303 produce failures, 499994 in queue, no compression
% 1456100 messages produced (1456100000 bytes), 957067 delivered (offset 13132069, 0 failed) in 21090ms: 45379 msgs/s and 45.38 MB/s, 3658 produce failures, 499033 in queue, no compression
% 1483308 messages produced (1483308000 bytes), 983338 delivered (offset 15512447, 0 failed) in 22094ms: 44506 msgs/s and 44.51 MB/s, 4035 produce failures, 499970 in queue, no compression
% 1511831 messages produced (1511831000 bytes), 1011835 delivered (offset 8566566, 0 failed) in 23096ms: 43809 msgs/s and 43.81 MB/s, 4367 produce failures, 499996 in queue, no compression
% 1538091 messages produced (1538091000 bytes), 1038091 delivered (offset 12930270, 0 failed) in 24105ms: 43065 msgs/s and 43.07 MB/s, 4732 produce failures, 500000 in queue, no compression
% 1560884 messages produced (1560884000 bytes), 1060911 delivered (offset 15515621, 0 failed) in 25107ms: 42253 msgs/s and 42.25 MB/s, 5024 produce failures, 499973 in queue, no compression
% 1582523 messages produced (1582523000 bytes), 1082523 delivered (offset 12932193, 0 failed) in 26114ms: 41453 msgs/s and 41.45 MB/s, 5363 produce failures, 500000 in queue, no compression
% 1607064 messages produced (1607064000 bytes), 1107084 delivered (offset 8574833, 0 failed) in 27114ms: 40829 msgs/s and 40.83 MB/s, 5653 produce failures, 499980 in queue, no compression
% 1653234 messages produced (1653234000 bytes), 1153237 delivered (offset 12934345, 0 failed) in 28116ms: 41015 msgs/s and 41.02 MB/s, 5838 produce failures, 499997 in queue, no compression
% 1693397 messages produced (1693397000 bytes), 1193437 delivered (offset 8593095, 0 failed) in 29117ms: 40986 msgs/s and 40.99 MB/s, 6066 produce failures, 499960 in queue, no compression
% 1735773 messages produced (1735773000 bytes), 1235774 delivered (offset 12937009, 0 failed) in 30123ms: 41022 msgs/s and 41.02 MB/s, 6425 produce failures, 499999 in queue, no compression
% 1773789 messages produced (1773789000 bytes), 1273796 delivered (offset 8601267, 0 failed) in 31126ms: 40923 msgs/s and 40.92 MB/s, 6696 produce failures, 499993 in queue, no compression

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Are you monitoring the broker load at the same time? Does it increase proportionally?
