### ISSUE TITLE
Avro support in librdkafka

### ISSUE THREAD

**Issue by pratikbatua** [edenhill/librdkafka#2523]
Description
===========
Is there a way in librdkafka where a user can provide a Avro schema and librdkafka publishes Avro message to broker ?

In our project we have a mandate to publish Avro to kafka, I know there a separate C++ lib which can be used to create Avro messages.

I am checking if there is anything within librdkafka which abstracts Avro from end user.

**Comment by edenhill** [comment]
Use [libserdes](https://github.com/confluentinc/libserdes/) on top of librdkafka, see [libserdes examples](https://github.com/confluentinc/libserdes/tree/master/examples).
