### ISSUE TITLE
Confluent-Kafka-Python script not working with SASL_SSL

### ISSUE THREAD

**Issue by karthikkgc** [edenhill/librdkafka#2526]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Below are the server.properties configuration

```
zookeeper.connect=XX.XXX.XX.XX:2181

listeners=SASL_SSL://:9093
advertised.listeners=SASL_SSL://kafka1:9093
#listener.security.protocol.map=SASL_SSL:SASL_SSL
#security.protocol=SSL
#ssl.endpoint.identification.algorithm=
security.inter.broker.protocol=SASL_SSL
sasl.mechanism.inter.broker.protocol=PLAIN
sasl.enabled.mechanisms=PLAIN


ssl.keystore.location=/opt/ssl2/keystore.jks
ssl.keystore.password=abc#1
ssl.key.password=abc#1
ssl.keystore.type=JKS
ssl.truststore.location=/opt/ssl2/truststore.jks
ssl.truststore.password=abc#1
ssl.truststore.type=JKS
authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
#allow.everyone.if.no.acl.found=false
super.users=User:admin
ssl.client.auth=required
#ssl.enabled.protocols=TLSv1.2,TLSv1.1,TLSv1
```

How to reproduce
================
using the below python script to connect Apache broker with SASL_SSL implemeted.
```
import confluent_kafka
import sys
import config
from confluent_kafka.admin import AdminClient, NewTopic, NewPartitions, ConfigResource, ConfigSource 
from confluent_kafka import Consumer, KafkaException, KafkaError

librdkafka_conf = {
    'bootstrap.servers': 'kafka1:9093',
    'security.protocol': 'SASL_SSL',
    'sasl.mechanisms': 'PLAIN',
    'sasl.username': 'dfghjks',
    'sasl.password': 'ghttkk#dpfw',
    'ssl.ca.location': '/opt/ssl2/ca-cert'
}
ac = AdminClient(librdkafka_conf)
md = ac.list_topics()
md.topics
```

Throwing below error

> 2019-09-13T18:11:42.7130887Z %3|1568398302.711|SSL|rdkafka#producer-1| [thrd:app]: bss_file.c:413: error:02001002:system library:fopen:No such file or directory: fopen('/opt/ssl2/ca-cert','r')
> 2019-09-13T18:11:42.7131693Z %3|1568398302.711|SSL|rdkafka#producer-1| [thrd:app]: bss_file.c:415: error:20074002:BIO routines:FILE_CTRL:system lib: 
> 2019-09-13T18:11:42.7136295Z Traceback (most recent call last):
> 2019-09-13T18:11:42.7136761Z     ac = AdminClient(librdkafka_conf)
> 2019-09-13T18:11:42.7137987Z   File "/usr/local/lib/python2.7/dist-packages/confluent_kafka/admin/__init__.py", line 216, in __init__
> 2019-09-13T18:11:42.7138210Z     super(AdminClient, self).__init__(conf)
> 2019-09-13T18:11:42.7138914Z cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="Failed to create admin client: ssl.ca.location failed: ssl_rsa.c:701: error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib: "}

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `current`
 - [ ] Apache Kafka version: `2.1`
 - [ ] librdkafka client configuration: `'bootstrap.servers': 'kafka1:9093',
    'security.protocol': 'SASL_SSL',
    'sasl.mechanisms': 'PLAIN',
    'sasl.username': 'dfghjk',
    'sasl.password': 'ghttkk#dpfw',
    'ssl.ca.location': '/opt/ssl2/ca-cert'`
 - [ ] Operating system: `Oracle Linux Server 7.5`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
> `2019-09-13T18:11:42.7130887Z %3|1568398302.711|SSL|rdkafka#producer-1| [thrd:app]: bss_file.c:413: error:02001002:system library:fopen:No such file or directory: fopen('/opt/ssl2/ca-cert','r')`
