### ISSUE TITLE
Producer and Consumer for Flatbuffer

### ISSUE THREAD

**Issue by ankitgkurup** [edenhill/librdkafka#2527]
**Scenario**
I am getting data from the source system as flatbuffer object. I want to send this flatbuffer object to a Kafka topic using librdkafka Kafka producer. Later from the same topic I will consume this data and process further.
**Questions**
1) Is it possible to send Flatbuffer object to Kafka topic as it is using librdkafka producer (in C++)?
2) How I can consume the flatbuffer object from a Kafka topic using librdkafka consumer (in C++)?

I am new in C++, if somebody can share sample code it will be really helpful.
Regards
Ankit

**Comment by Ximik** [comment]
@ankitgkurup Your flatbuffer objects are just arrays of bytes. You can just send them to Kafka topic as is. Once you consume the object from the topic, you should deserialize it from received bytes with Flatbuffer lib.

If you are not familiar with C++, I'd advice you to use one of the bindings for librdkafka (there are at least for golang and python, which are both supported by flatbuffers).

**Comment by ankitgkurup** [comment]
Thank you Alex.

**Comment by edwardnguyen1705** [comment]
@Ximik 
Did you try to produce and consume flatbuffer objects?

**Comment by Ximik** [comment]
@edwardnguyen1705
No, but I have used it with my custom serializer, which works the same way as flatbuffer.
