### ISSUE TITLE
comsume one topic with two clusters brokers given, the program stuck occasionally

### ISSUE THREAD

**Issue by yunyajiao1** [edenhill/librdkafka#2529]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
When I want to comuse a topic from cluster one, I filled rd_kafka_brokers_add() with multi brokers together with cluster one and cluster two.  I know it is a wrong usege. But the reslut is 
 stuck occasionally. And when i want to execute rd_kafka_destroy(), the program Fall into an infinite loop, and rkb->rkb_state = RD_KAFKA_BROKER_STATE_UP rkb->rkb_refcnt->v =2. Please explain it to me when you are convenient. Thank you vary much!<your issue description goes here>

**Comment by edenhill** [comment]
A kafka client may only be connected to one single cluster at the time.
