### ISSUE TITLE
Delivery Report callback not providing the original value of the opaque pointer used on the call to produce

### ISSUE THREAD

**Issue by wcn00** [edenhill/librdkafka#2530]
Description
===========

Using libdrkafka 1.0
Running the simple producer sample.
I added a string to the opaque parm of the rd_kafka_produce call.

However the opaque parm of the callback is null.  Interestingly in the callback the rk_message.private field contains my opaque object's address.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.0.0`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x ] Operating system: `Ubuntu 19`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The dr_msg_cb opaque value is the rd_kafka_t opaque, not the message opaque. The message opaque is in `rkmessage->_private`:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1568
