### ISSUE TITLE
Installing librdkafka on Debian 9 from Confluent repository?

### ISSUE THREAD

**Issue by kurtostfeld** [edenhill/librdkafka#2532]
Description
===========

Now, that Confluent 5.3.x officially supports Debian 9, I wanted to use the Confluent Debian repo to install a recent, version 1.0.0 or later version of librdkafka on Debian 9. It doesn't work due to a libssl incompatibility.

The Debian repos, both stretch backports and buster have an older version of librdkafka 0.11.x
https://packages.debian.org/source/librdkafka. That is too old for my needs.

How to reproduce
================

```bash
docker pull debian:9
docker run --rm -it debian:9

apt-get update
apt-get install -y wget gnupg2 software-properties-common libssl1.0.2

wget -qO - http://packages.confluent.io/deb/5.3/archive.key | apt-key add -
add-apt-repository "deb [arch=amd64] http://packages.confluent.io/deb/5.3 stable main"
apt-get install librdkafka1

...

The following packages have unmet dependencies:
 librdkafka1 : Depends: libssl1.0.0 (>= 1.0.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Checklist
=========

Please provide the following information:

 - [x] librdkafka version v1.1.0.
 - [x] Apache Kafka version: 2.3.0
 - [x] librdkafka client configuration: n/a
 - [x] Operating system: Debian 9.11
 - [x] Provide logs
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by kurtostfeld** [comment]
fyi, this works fine in Debian 8. Just bumping to Debian 9 breaks this:

```
docker run --rm -it debian:8
apt-get update
apt-get install -y wget gnupg2 software-properties-common

wget -qO - http://packages.confluent.io/deb/5.3/archive.key | apt-key add -
add-apt-repository "deb [arch=amd64] http://packages.confluent.io/deb/5.3 stable main"
apt-get update
apt-get install -y librdkafka1
```

FYI, often staying on Debian 8 is often not an option. Often, upgrading is required for new projects. For example, the official Golang Docker images, they support the two recent Debian releases, with golang:1.13-stretch and golang:1.13-buster but they don't support jessie.

**Comment by edenhill** [comment]
We're aware of this issue and will look into it during Q2.

**Comment by anirudh-chhangani** [comment]
we are looking to move to debian buster, is there any workaround to get this running under buster?

**Comment by edenhill** [comment]
You have three options for now:
 1. build librdkafka from source
 2. build your own debian packages (using the librdkafka debian/ dir)
 3. Use the official Debian packages (which are likely to lag behind)

**Comment by RoboBuffalo** [comment]
Hi there,
Is there any progress on this issue?
I have same issue with Debian 10

**Comment by andrewthad** [comment]
I'm trying to go the "build your own debian packages" route, but there is no documentation on how to actually use the file in the `debian/` directory to build a deb file. I've tried this:

```
amartin@myhost:~/Development/librdkafka-1.5.2$ ./debian/rules
# Use dependency installation for missing dependencies, zstd in particular.
# These will be statically linked.
dh_auto_configure -- --install-deps
        ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --install-deps
using cache file config.cache
checking for OS or distribution... ok (ubuntu)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
...
Now type 'make' to build
```

But then after running `make`, there is not a deb file anywhere. Also, it's confusing that there is a `debian/` at the root of the project, and then there is also a `packaging/debian/`, and both have similar files. If someone is able to explain how this is supposed to work, I can document it in the project itself.

**Comment by edenhill** [comment]
See https://github.com/edenhill/librdkafka/blob/master/packaging/tools/distro-build.sh#L17
