### ISSUE TITLE
latency increase when run multiple topics on one kafka instance

### ISSUE THREAD

**Issue by MockingJayWong** [edenhill/librdkafka#2533]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have tested with 500 topics, 
and use one rd_kafka_t instance first to send msg on these 10, 100, 500 topics, found that latency becomes larger when I increase topics nums. 
 ___int_latency,rtt___ becomes larger, and then I try ___10 rd_kafka_t___ instance instead,
but not improve better on ___int_latency,rtt___. 
Is there a suitable way for this scenerio? And is there a way to measure delay ? Appreciated!

How to reproduce
================
I have put timestamp inside message payload and use a consumer to calculate end-to-end delay. Beside, I use tcpdump to catch info on the producer side, found that with more topic, delay between  timestamp i make inside msg and producerRequest sending-out becomes larger. In fact, most time-cost happens here!

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.1.0`
 - [x] Apache Kafka version: `2.12-2.2.0`
 - [x] librdkafka client configuration: 
`socket.nagle.disable=true`,
`queue.buffering.max.messages=10000000`,
`acks=all`,
`linger.ms=1`,
`compression.codec=lz4`,
`socket.keepalive.enable=true`,
`enable.idempotence=true`,
`message.timeout.ms=300000`
 - [x] Operating system: ` Centos 7 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka will currently only send one partitioner per ProduceRequest, and each request is handled in order by the broker, so the more partitions you produce to the longer wait time will be due to head of line blocking in the broker.
We are looking to optimize this in future versions but there is no current date set.

**Comment by MockingJayWong** [comment]
thanks for reply. I use more rd_kafka_t to set up more broker threads to send ProducerRequest, but it seems not works well in latency. Theoretically, is it better to have more rd_kafka_t when topic grows more ？

**Comment by edenhill** [comment]
If you are producing to a lot of partitions on a small number of brokers there will be higher latency, the only workaround at this point is using multiple rd_kafka_t instances.

**Comment by MockingJayWong** [comment]
thanks! waiting for optimizing `rd_kafka_ProduceRequest`
