### ISSUE TITLE
Typo in FAQ on configuration variable name

### ISSUE THREAD

**Issue by SnugglyCoder** [edenhill/librdkafka#2534]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
There is a typo in the FAQ on a configuration name. In the "How are partitions fetched?" section, there is the line "the same queue has less than queued.max.message.kbytes enqueued"

queued.max.message.kbytes should be queued.max.message**s**.kbytes

https://github.com/edenhill/librdkafka/wiki/FAQ#how-are-partitions-fetched

**Comment by edenhill** [comment]
Thank you, fixed!
