### ISSUE TITLE
Adding ACLs on Kafka topic

### ISSUE THREAD

**Issue by karthikkgc** [edenhill/librdkafka#2538]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I didn't find any documentation related to add ACL on topics. 

Something like https://github.com/dpkp/kafka-python/commit/23c712350c1372a08e7e638ecbcf3f5f31e13016#diff-d25dfc6dcf074a098d579d711ad43630

If it is not supported, is there any workaround to add ACLs?

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): "current"
 - [ ] Apache Kafka version:  '0.10.2.1`
 - [ ] librdkafka client configuration: `security.protocol='SASL_SSL`
 - [ ] Operating system: `Linux 7.5`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The librdkafka Admin API currently does not support the ACL functionality, but it is on our backlog (no committed date yet).
Your interest in this feature has been noted

**Comment by saheemg** [comment]
I'm very much interested in this feature as well

**Comment by emasab** [comment]
I've added a PR for this: https://github.com/edenhill/librdkafka/pull/2676

**Comment by edenhill** [comment]
Will be available in 1.9
