### ISSUE TITLE
ALL_BROKERS_DOWN doesn't really mean anything to librdkafka ..

### ISSUE THREAD

**Issue by plachor** [edenhill/librdkafka#2543]
...

Also, ALL_BROKERS_DOWN doesn't really mean anything to librdkafka, it is just a friendly indication to the application that **currently** there are no brokers to communicate with. But librdkafka will continue to try to reconnect indefinately, and it will attempt to re-send messages until message.timeout.ms or message.max.retries are exceeded

...

_Originally posted by @edenhill in https://github.com/edenhill/librdkafka/issues/1072#issuecomment-281997806_

Hi @edenhill. I am using dotnet-wrapper over Librd Kafka from https://github.com/confluentinc/confluent-kafka-dotnet. 

I'm troubled with lots of false positives involving idle connection reaper and this log entry `ALL_BROKERS_DOWN`. Since you log this with *Error* severity level it does not feel as a friendly indication at all. Should it be *Warning* than?

Additionally in my situation this log indicates that connection was lost to all 3 brokers at once. Is Librd keeping active connection to all brokers or only to one that it has active assignment from?

I've already suppressed errors regarding connection being closed with `log.connection.close=false` but this does not affect `ALL_BROKERS_DOWN`.  So that would indicate that my client should keep active connection to all brokers in cluster ? If so maybe there is a jitter configuration that I have not set and loose connection to all brokers at once?

**Comment by sebwills** [comment]
The discussion and fix done following #2466 may be of interest to you. I think the enhancement #2476 went into 1.2.0.

**Comment by plachor** [comment]
Thnx @sebwills for input, so if that is correct than I should see no errors soon as default values should cover connection reaper timeout.

**Comment by plachor** [comment]
Seems to work indeed 👍
