### ISSUE TITLE
Topic authorization failed can be transient

### ISSUE THREAD

**Issue by sebwills** [edenhill/librdkafka#2544]
Description
===========
Currently a broker TOPIC_AUTHORIZATION_FAILED error when producing a message is treated by librdkafka as 'Permanent', which means the message is not retried.

I have experienced a Kafka cluster which temporarily returns topic authorization errors, e.g. due to a related security service being restarted. Currently when this happens my messages are dropped, whereas had they been kept in librdkafka's queue and retried until the message timeout, they would have been accepted by the broker after a few minutes.

Is it possible to make TOPIC_AUTHORIZATION_FAILED be treated as a potentially transient condition, i.e. not 'Permanent'?

Relevant log line:
```
MessageSet with 1 message(s) (MsgId 0, BaseSeq -1) encountered error: Broker: Topic authorization failed (actions Permanent,MsgNotPersisted)
```

Checklist
=========

 - [x] librdkafka version (release number or git tag): `1.1.0`
 - [x] Apache Kafka version: `2.12-2.3.0`
 - [x] librdkafka client configuration: `default`
 - [x] Operating system: `Windows`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I hear what you are saying but I'm not sure this is a good idea.
Having these random auth failures sounds to me like a problem that needs to be fixed at the source.

Are other users having this problem as well?

Having said that, a solution in librdkafka would be to have something like a list of error codes or types of errors that should be retriable.

**Comment by sebwills** [comment]
@edenhill Any chance you could reconsider this? I get this error transiently if the security daemon SSSD is restarted; it would be great if librdkafka could retry when this happens.

I take the point that usually users want immediate, fail-fast feedback for configuration errors rather than retry behaviour, but perhaps there is some way this could be make configurable, or have a category of error that is logged immediately as a warning but also retried?

**Comment by edenhill** [comment]
This ultimately sounds like an issue with your security provider and not with the clients, not sure it is a good idea to work around this on the client side.
Perhaps it would be better if the topic became leader-less when the security daemon is unavailable.

**Comment by sebwills** [comment]
@edenhill This issue is still causing me problems in production. Can I put forward a few arguments why I think it should be addressed in librdkafka, and propose a way forward?

We agree that ultimately the fault is that a security provider somewhere is not 100% reliable. However, in a complex environment, it's perhaps not unexpected that a transient auth issue can filter down to the consuming system as a failsafe 'unauthorized' rather than the more accurate 'error'. Realistically, returning 'not authorized' is a likely failure mode for a security system involving potentially many linked subsystems. Retries are a pragmatic way to deal with this.

You suggested 

> Perhaps it would be better if the topic became leader-less when the security daemon is unavailable.

but (a) that assumes Kafka can tell that the security provider is unavailable, rather than transiently returning 'unauthorised', and (b) I don't think the Kafka maintainers would accept this change. 

Furthermore, librdkafka already treats 'topic authorization failed' as retryable _if it occurs when first fetching metadata for the topic_. So making it retry when this error occurs when producing messages, as requested by this issue, is in fact making librdkafka more consistent.

> Having said that, a solution in librdkafka would be to have something like a list of error codes or types of errors that should be retriable.

My colleague has drafted a PR along these lines. I'll ask him to link it here; if you're able to consider it that would be great.
