### ISSUE TITLE
Broker Transport Failure while using “SASL_PLAINTEXT” OR “PLAINTEXT” protocol

### ISSUE THREAD

**Issue by rajjagani021** [edenhill/librdkafka#2545]
I am trying to connect the confluent Kafka broker using "SASL_PLAINTEXT" or "PLAINTEXT" security protocol but I am getting this error **broker transport failure**. However, it's working fine with the "SASL_SSL" protocol but not working with any other security protocol.

How to reproduce
================
```
const consumer = new Kafka.KafkaConsumer({
    'group.id':'gsuite_consumer',
    'metadata.broker.list': *******,
    'sasl.mechanisms': 'PLAIN',
    'sasl.username': *********,
    'sasl.password': ******,
    'security.protocol': 'PLAINTEXT'
}, {});

// Connect the consumer.
consumer.connect({timeout: "1000ms"}, (err) => {
    if (err) {
        console.log(`Error connecting to Kafka broker: ${err}`);
        process.exit(-1);
    }

    console.log("Connected to Kafka broker");
});
```
Please provide the following information:

 - [x] librdkafka version : `1.1.0`
 - [ ] Apache Kafka version: `2.7.1-2`
 - [ ] Operating system: `macOS mojave 10.14.4`

**Comment by edenhill** [comment]
If it works with SASL_SSL it means the broker is using an SSL endpoint, not a PLAINTEXT, and you will need to configure your client accordingly (security.protocol=SASL_SSL)
