### ISSUE TITLE
Question about KafkaConsumer and opaque topic data

### ISSUE THREAD

**Issue by sirzooro** [edenhill/librdkafka#2547]
Description
===========
My code uses `KafkaConsumer` class and reads messages by repeatedly calling `consume()` method. I would like to assign some opaque pointer to topic, and then extract it from received `Message`. FAQ contains entry "How do I set topic configuration properties with the KafkaConsumer?", but it contains following unclear advice:

> If you need special configuration for a sub-set of your topics you will need to create them prior to calling subscribe() or assign() and pass their explicit configuration objects at topic creation time.

I checked `KafkaConsumer` but did not found any method which accepts `Topic` object. The same for `TopicPartition`, it also does not allow this.

I also do not know how to get this opaque pointer from Message object - both `Message` and `Topic` classes does not have methods which returns `Conf` object for topic.

Could you give me some hints how to do this? An alternative is to map topic names to pointers in my code, what will add some performance overhead.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Unfortunately there is no opaque object available on the C++ topic object, the underlying C topic opaque is used in the C++ wrapper to map the C topic to the C++ Topic object.

We could add `set_opaque()` & `opaque()` methods to the Topic object to allow an application to set up its own on demand.

**Comment by sirzooro** [comment]
This would be nice, please add this feature. Make sure to modify 

What about setting config for topic added to KafkaConsumer? Current API allows to pass topic name only.

**Comment by edenhill** [comment]
What per-topic configuration do you want to make with the KafkaConsumer?

**Comment by sirzooro** [comment]
At this moment I do not need to configure anything extra for individual topics. I am simply curious if there is some way to do this.

**Comment by edenhill** [comment]
As KafkaConsumer inherits from Handle you can create a new Topic by passing the consumer to Topic::create(), but for the passed configuration to take effect you will need to do this before the topic (name) is referenced (through assign(), subscribe(), etc).

**Comment by sirzooro** [comment]
Thanks.
