### ISSUE TITLE
Not  opening  solution file  in Vs2010

### ISSUE THREAD

**Issue by nitinpatharia** [edenhill/librdkafka#2550]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi edenhill,
I am try  to build  using vs 2010  when  i try  to  open  The Visual Studio solution file  win32/librdkafka.sln in vs2010 ,  i am  getting error  like  the  sln  was  developed  in  higher  version  and  its  not  opening  the  file .
 do  we  support vs2010  for  building . if  yes  how  can  i build  using vs2010.
i am  using code  from master.
Appreciate your  help .

Thanks

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>
trying to  open  win32/librdkafka.sln in vs2010 but  sln  is  not  opening .

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
You will probably need VS 2015 or later.

But instead of building librdkafka yourself you should probably use the librdkafka.redist nuget package: https://www.nuget.org/packages/librdkafka.redist/

**Comment by nitinpatharia** [comment]
Thanks for  response. Using https://www.nuget.org/packages/librdkafka.redist/ how can I create producer and consumer from my vs2010

**Comment by nitinpatharia** [comment]
I have already added https://www.nuget.org/packages/librdkafka.redist/ in my vs2010. Using nuget.
Please help me as how can I create topic, producer and consumer by using this line. 
Appreciate your help
