### ISSUE TITLE
Error  while using  the  rdakafka lib  as per  example  in Vs2010

### ISSUE THREAD

**Issue by nitinpatharia** [edenhill/librdkafka#2552]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
i  am  using   librdkafka-master\examples\rdkafka_example.cpp in   my  application . i am  using rdkafka_example.cpp  as  its  is,  no  changes  made.
while  building  rdkafka_example.cpp i am  facing  linking  error  as  

Error	33	error LNK2001: unresolved external symbol "__declspec(dllimport) public: static __int64 const RdKafka::Topic::OFFSET_BEGINNING" (__imp_?OFFSET_BEGINNING@Topic@RdKafka@@2_JB)	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	29	error LNK2001: unresolved external symbol "__declspec(dllimport) public: static __int64 const RdKafka::Topic::OFFSET_END" (__imp_?OFFSET_END@Topic@RdKafka@@2_JB)	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	28	error LNK2001: unresolved external symbol "__declspec(dllimport) public: static __int64 const RdKafka::Topic::OFFSET_STORED" (__imp_?OFFSET_STORED@Topic@RdKafka@@2_JB)	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	34	error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int const RdKafka::Topic::PARTITION_UA" (__imp_?PARTITION_UA@Topic@RdKafka@@2HB)	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	30	error LNK2001: unresolved external symbol _optarg	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	27	error LNK2001: unresolved external symbol _optind	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	21	error LNK2019: unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::err2str(enum RdKafka::ErrorCode)" (__imp_?err2str@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ErrorCode@1@@Z) referenced in function _main	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	26	error LNK2019: unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::get_debug_contexts(void)" (__imp_?get_debug_contexts@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function _main	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	24	error LNK2019: unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::version_str(void)" (__imp_?version_str@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function _main	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	25	error LNK2019: unresolved external symbol "__declspec(dllimport) int __cdecl RdKafka::version(void)" (__imp_?version@RdKafka@@YAHXZ) referenced in function _main	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	18	error LNK2019: unresolved external symbol "__declspec(dllimport) int __cdecl RdKafka::wait_destroyed(int)" (__imp_?wait_destroyed@RdKafka@@YAHH@Z) referenced in function _main	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	41	error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall RdKafka::ConsumeCb::ConsumeCb(void)" (__imp_??0ConsumeCb@RdKafka@@QAE@XZ) referenced in function "public: __thiscall ExampleConsumeCb::ExampleConsumeCb(void)" (??0ExampleConsumeCb@@QAE@XZ)	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	39	error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall RdKafka::DeliveryReportCb::DeliveryReportCb(void)" (__imp_??0DeliveryReportCb@RdKafka@@QAE@XZ) referenced in function "public: __thiscall ExampleDeliveryReportCb::ExampleDeliveryReportCb(void)" (??0ExampleDeliveryReportCb@@QAE@XZ)	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	37	error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall RdKafka::EventCb::EventCb(void)" (__imp_??0EventCb@RdKafka@@QAE@XZ) referenced in function "public: __thiscall ExampleEventCb::ExampleEventCb(void)" (??0ExampleEventCb@@QAE@XZ)	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	35	error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall RdKafka::PartitionerCb::PartitionerCb(void)" (__imp_??0PartitionerCb@RdKafka@@QAE@XZ) referenced in function "public: __thiscall MyHashPartitionerCb::MyHashPartitionerCb(void)" (??0MyHashPartitionerCb@@QAE@XZ)	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	32	error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Conf * __cdecl RdKafka::Conf::create(enum RdKafka::Conf::ConfType)" (__imp_?create@Conf@RdKafka@@SAPAV12@W4ConfType@12@@Z) referenced in function _main	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	20	error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Consumer * __cdecl RdKafka::Consumer::create(class RdKafka::Conf *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (__imp_?create@Consumer@RdKafka@@SAPAV12@PAVConf@2@AAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function _main	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	22	error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Headers * __cdecl RdKafka::Headers::create(void)" (__imp_?create@Headers@RdKafka@@SAPAV12@XZ) referenced in function _main	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka

i  have  downloaded  these  as  nuget  i my  vs2010  application 
librdkafka.redist.1.2.0
zlib-msvc-x64.1.2.11.8900
boost.1.70.0.0

I have  included  the  path  explicitly  as  well  in  my solution .
not  sure  what  is  causing the issue or  i am missing  something .
i want  to  use  kafa  in my application . Any  help as  what  i am doing  wrong .

Appreciate  your  help .

Thanks

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by nitinpatharia** [comment]
@edenhill   any  help  on this ?

**Comment by edenhill** [comment]
Looks like you are not linking to librdkafkacpp.lib

**Comment by nitinpatharia** [comment]
@edenhill Thanks    for  reply ......i am  able  to  resolve  some  of  error.
these  are  few  error  i have  now 
Error	21	error LNK1120: 3 unresolved externals	c:\project\testingkafka\Debug\testingkafka.exe	1	1	testingkafka
Error	19	error LNK2001: unresolved external symbol _optarg	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	18	error LNK2001: unresolved external symbol _optind	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	20	error LNK2019: unresolved external symbol _getopt referenced in function _main	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka

Am  i am  missing  some  other  lib  or  .....?

Thanks

**Comment by nitinpatharia** [comment]
@edenhill  hi  eden  any  help , i need  to  use  this  in my  application  please  help  about  the  error  seen above .

Thanks

**Comment by sushmukund26** [comment]
> @edenhill Thanks for reply ......i am able to resolve some of error.
> these are few error i have now
> Error 21 error LNK1120: 3 unresolved externals c:\project\testingkafka\Debug\testingkafka.exe 1 1 testingkafka
> Error 19 error LNK2001: unresolved external symbol _optarg c:\project\testingkafka\testingkafka\testingkafka.obj testingkafka
> Error 18 error LNK2001: unresolved external symbol _optind c:\project\testingkafka\testingkafka\testingkafka.obj testingkafka
> Error 20 error LNK2019: unresolved external symbol _getopt referenced in function _main c:\project\testingkafka\testingkafka\testingkafka.obj testingkafka
> 
> Am i am missing some other lib or .....?
> 
> Thanks

Hi, I am facing a similar issue and wanted to understand how you were able to link to librdkafkacpp.lib. I am facing the same issue where after referencing librdkafka.redist NuGet package in the Visual Studio project, the following is happening:

Able to successfully include <librdkafka/rdkafkacpp.h>

Able to successfully create a dummy object, for instance, RdKafka::Conf *conf;

Unable to instantiate it as follows: RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);

The following error occurs: Severity Code Description Project File Line Suppression State
Error LNK2001 unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Conf * __cdecl RdKafka::Conf::create(enum RdKafka::Conf::ConfType)" (_imp?create@Conf@RdKafka@@SAPEAV12@W4ConfType@12@@z) EmoRecVidSVM_Adult C:\EmotionDetection\expression_recognition_video_SVM_adult\exe\FaceLandmarkVid\EmoRecVidSVM_Adult.obj 1
