### ISSUE TITLE
Error while  using any  example  for  cpp 

### ISSUE THREAD

**Issue by nitinpatharia** [edenhill/librdkafka#2554]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ
I am  facing  these  error  while  using  any  example  in my application  i have  used  rdkafka_consumer_example.cpp and  rdkafka_example.cpp  in both   i am  facing  below  error 

Error	1	error LNK2001: unresolved external symbol _getopt	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	2	error LNK2001: unresolved external symbol _optarg	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	3	error LNK2001: unresolved external symbol _optind	c:\project\testingkafka\testingkafka\testingkafka.obj	testingkafka
Error	4	error LNK1120: 3 unresolved externals	c:\project\testingkafka\Release\testingkafka.exe	testingkafka

Please  help  if  any  idea  as  what  is  missing .

Thanks 

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by MockingJayWong** [comment]
it seems that getopt not include in ur windows library, maybe u should check _MSC_VER works in ur code. Or this may help #1428

**Comment by nitinpatharia** [comment]
@MockingJayWong @edenhill 
Hi  Thanks  for  reply . I  am  already  using  _MSC_VER  and    in code  its  shows  value  1600.
i am  using  vs 2010.  
in  my application  i have  used  like 
#ifdef _MSC_VER
#include "C:/Users/Nitin/Desktop/kafka/librdkafka-master/win32/wingetopt.h"

i have given   fulll path  of  wingetopt.h.  Not  sure  as  what  i am  missing  any  clue  or  help  to  overcome  with  these  linking errors

Error 1 error LNK2001: unresolved external symbol _getopt c:\project\testingkafka\testingkafka\testingkafka.obj testingkafka
Error 2 error LNK2001: unresolved external symbol _optarg c:\project\testingkafka\testingkafka\testingkafka.obj testingkafka
Error 3 error LNK2001: unresolved external symbol _optind c:\project\testingkafka\testingkafka\testingkafka.obj testingkafka
Error 4 error LNK1120: 3 unresolved externals c:\project\testingkafka\Release\testingkafka.exe testingkafka


Thanks

**Comment by edenhill** [comment]
You will also need to add wingetopt.c to your build.

**Comment by nitinpatharia** [comment]
@edenhill  i have  added file   wingetopt.c  now  i am  facing these  error  . Try  some  option available  on internet but  still  facing  this  error 
Error	1	error LNK1181: cannot open input file 'C:\Users\Nitin\Desktop\kafka\librdkafka-master\win32.obj'	c:\project\testingkafka\testingkafka\LINK	testingkafka


any  idea  as  how  can  fix  this ....?
Thanks
Nitin

**Comment by nitinpatharia** [comment]
i have added file wingetopt.c now i am facing these error . Try some option available on internet but still facing this error
Error 1 error LNK1181: cannot open input file 'C:\Users\Nitin\Desktop\kafka\librdkafka-master\win32.obj' c:\project\testingkafka\testingkafka\LINK testingkafka

any idea as how can fix this ....?
Thanks
Nitin

**Comment by edenhill** [comment]
I dont know what win32.obj is, I don't think it is an object that librdkafka provides.

**Comment by nitinpatharia** [comment]
i have  fixed   win32.ob    Now  i am  getting error  

LINK : fatal error LNK1181: cannot open input file 'C:\Users\Nitin\Desktop\kafka\librdkafka-master.obj'

any  idea ?

**Comment by edenhill** [comment]
You should reference the librdkafka.redist nuget package, see what kafkacat does:
https://github.com/edenhill/kafkacat/tree/master/win32
