### ISSUE TITLE
kafka monitor

### ISSUE THREAD

**Issue by SouthStar** [edenhill/librdkafka#256]
I use KafkaOffsetMonitor to monitor the status of consumer, but the KafkaOffsetMonitor can not achieve the information of consumer, I set the "group.id" and "client.id", it dosen't work still, can you give advise to me about monitor?

**Comment by edenhill** [comment]
It looks like KafkaOffsetMonitor only supports zookeeper-based offsets (e.g., pre 0.8.2).
librdkafka does not support zookeeper-based offsets (they are on the way out),
instead it supports broker-based offsets (for broker 0.8.0) and proper support for broker based consumer group offset management (broker 0.8.2) is soon available.
This work is tracked by issue #225

**Comment by SouthStar** [comment]
How long can librdkafka support zookeeper? Do you have a plan for zookeeper?

**Comment by edenhill** [comment]
Since Zookeeper-based consumer groups will be replaced by broker-based consumer groups in Kafka 0.9 I'm not sure there will ever be zookeeper-based consumer group support in librdkafka.
Unless, of course, someone is willing to sponsor it.

**Comment by SouthStar** [comment]
ok, thank you
