### ISSUE TITLE
Unable to consume messages from Kafka

### ISSUE THREAD

**Issue by rameshmaruthi80** [edenhill/librdkafka#2561]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

%7|1570649288.363|SSL|rdkafka#consumer-1| [thrd:app]: Loading CA certificate(s) from file ca-path.pem
%7|1570649288.364|BROKER|rdkafka#consumer-1| [thrd:app]: GroupCoordinator: Added new broker with NodeId -1
%7|1570649288.364|BRKMAIN|rdkafka#consumer-1| [thrd:GroupCoordinator]: GroupCoordinator: Enter main broker thread
%7|1570649288.365|BRKMAIN|rdkafka#consumer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1570649288.366|BROKER|rdkafka#consumer-1| [thrd:app]: sasl_ssl://edge03-uat.dl.internal.abc.com:6767/bootstrap: Added new broker with NodeId -1
%7|1570649288.366|BRKMAIN|rdkafka#consumer-1| [thrd:sasl_ssl://edge03-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge03-uat.dl.internal.abc.com:6767/bootstrap: Enter main broker thread
%7|1570649288.367|BROKER|rdkafka#consumer-1| [thrd:app]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Added new broker with NodeId -1
%7|1570649288.371|BRKMAIN|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Enter main broker thread
%7|1570649288.371|INIT|rdkafka#consumer-1| [thrd:app]: librdkafka v1.2.1 (0x10201ff) rdkafka#consumer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, SSL ZLIB SNAPPY SASL_SCRAM PLUGINS HDRHISTOGRAM, debug 0x282)
%7|1570649289.369|CONNECT|rdkafka#consumer-1| [thrd:main]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Selected for cluster connection: coordinator query (broker has 0 connection attempt(s))
%7|1570649289.369|CONNECT|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Received CONNECT op
%7|1570649289.369|CONNECT|rdkafka#consumer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection
%7|1570649289.373|STATE|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1570649289.375|CONNECT|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: broker in state TRY_CONNECT connecting
%7|1570649289.376|STATE|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1570649289.398|CONNECT|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Connecting to ipv4#162.13.63.134:6767 (sasl_ssl) with socket 2596
%7|1570649289.415|CONNECT|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Connected to ipv4#162.13.63.134:6767
%7|1570649289.456|SSLVERIFY|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Broker SSL certificate verified
%7|1570649289.456|CONNECTED|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Connected (#1)
%7|1570649289.457|FEATURE|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1570649289.459|STATE|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1570649289.460|SEND|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Sent ApiVersionRequest (v0, 25 bytes @ 0, CorrId 1)
%7|1570649289.477|RECV|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Received ApiVersionResponse (v0, 264 bytes, CorrId 1, rtt 16.92ms)
%7|1570649289.477|FEATURE|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,UnitTest
%7|1570649289.478|AUTH|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Auth in state APIVERSION_QUERY (handshake supported)
%7|1570649289.480|STATE|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Broker changed state APIVERSION_QUERY -> AUTH_HANDSHAKE
%7|1570649289.481|SEND|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Sent SaslHandshakeRequest (v1, 29 bytes @ 0, CorrId 2)
%7|1570649289.497|RECV|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Received SaslHandshakeResponse (v1, 14 bytes, CorrId 2, rtt 15.83ms)
%7|1570649289.498|SASLMECHS|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Broker supported SASL mechanisms: GSSAPI
%7|1570649289.503|AUTH|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Auth in state AUTH_HANDSHAKE (handshake supported)
%7|1570649289.505|STATE|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Broker changed state AUTH_HANDSHAKE -> AUTH_REQ
%7|1570649289.506|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Initializing SASL client: service name kafka, hostname edge04-uat.dl.internal.abc.com, mechanisms GSSAPI, provider Win32 SSPI
%7|1570649289.507|SASL|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Acquired Kerberos credentials handle (expiry in 2147483413.1317339135s)
%7|1570649289.611|BROKERFAIL|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: failed: err: Local: Authentication failure: (errno: Invalid argument)
%3|1570649289.611|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap]: sasl_ssl://edge04-uat.dl.internal.abc.com:6767/bootstrap: Failed to initialize SASL authentication: InitializeSecurityContext failed: (no string representation) (0x80090342) (after 104ms in state AUTH_REQ)

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">` current
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>` 1.1.1
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>` windows
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka - in description
 - [ ] Provide broker log excerpts
 - [ ] Critical issue - yes

**Comment by edenhill** [comment]
Please fill out the checklist.
