### ISSUE TITLE
Can we decode the C/C++ encoded Kafka message using Java?

### ISSUE THREAD

**Issue by bhoopal-tech** [edenhill/librdkafka#2564]
Description
===========
I have used the avro tool to encode/ decode the message.which is working fine.But when i tried to decode the message which was encoded by the librdkafka C/C++ client. I facing issue citing invalid length. But the same i can decode using librdkafka consume. Can only C consume can be used to decode the message or we can use java as well.

Please suggest.

**Comment by edenhill** [comment]
What deserializer are you using in the Java consumer?
Is it expecting the schema-registry framing? If so, you should use libserdes with your librdkafka client to perform schema-registry framing on the producer.

**Comment by bhoopal-tech** [comment]
Thanks for your reply. queried the same with the producer. Will get back to you.

**Comment by bhoopal-tech** [comment]
Schema inAvroSchemaFile = new Schema.Parser().parse(new File("avroschema.avsc"));
	Schema outAvroSchemaFile = new Schema.Parser().parse(new File("avroschema.avsc"));
	GenericDatumReader<GenericRecord> inRreader = new GenericDatumReader<GenericRecord>(inAvroSchemaFile);
	DatumWriter<GenericRecord> outputDatumWriter=new GenericDatumWriter<>(outAvroSchemaFile);
	ByteArrayInputStream in = new ByteArrayInputStream(message.getBytes(Charsets.UTF_8));
    DatumReader<GenericRecord> datumReader = new GenericDatumReader<>();
    DataFileStream<GenericRecord> dataFileReader = new DataFileStream<GenericRecord>(in, datumReader);
    GenericRecord rec = null;
    while (dataFileReader.hasNext()) {
        rec = dataFileReader.next(rec);
        if(rec==null) System.out.println("\n===============  NULL record");
    }
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    BinaryEncoder encoder = EncoderFactory.get().binaryEncoder(baos, null);
    outputDatumWriter.write(rec, encoder);
    encoder.flush();

I used above code to do desrialize the data. It fails while constructing the DataFileStream(like below). woth exception as Illegal ArgumentException. 

 DataFileStream<GenericRecord> dataFileReader = new DataFileStream<GenericRecord>(in, datumReader);

The above error only throws when i try to deserialize the avro message from String.But fails by doing the same from file.

Am i miss anything

**Comment by edenhill** [comment]
If the message is produced by a schema-registry supporting avro serializer producer then the data is prefixed with the schema-registry header and you will need to either strip it (5 bytes) or, preferably, use libserdes.
https://github.com/confluentinc/libserdes/tree/master/examples

**Comment by bhoopal-tech** [comment]
Message does not support schema-registry.Could you please share the java example than C

**Comment by bhoopal-tech** [comment]
Is this the only way to decode the message by reading from file.because only docode message by reading file works. decoding the message alone does not work.

Note: the serialization was done by C

**Comment by edenhill** [comment]
Kafka, nor librdkafka, does not know anything about the format of the message, it is all just a binary blob.

If you  have issues using the Avro C++ API I recommend reading up on the [official Avro docs](http://avro.apache.org/docs/current/api/cpp/html/index.html) and if that does not help you should create an issue on Avro project or send an email to their mailing list.
