### ISSUE TITLE
dyld: lazy symbol binding failed

### ISSUE THREAD

**Issue by Aashna-Agrawal** [edenhill/librdkafka#2570]
Description
===========
After successfully installing librdkafka, I compiled my application successfully (go build main.go). When I ran the same, binding was unsuccessfull.

**Error:**
xdyld: lazy symbol binding faileddyld: lazy symbol binding faileddyld: lazy symbol binding faileddyld: lazy symbol binding faileddyld: lazy symbol binding failed: Symbol not found: _timespec_ge: Symbol not found: _timespec_ge: Symbol not found: _timespec_ge: Symbol not found: _timespec_get
  Referenced from: /usr/local/t
  Referenced from: /usr/local/dyld: lazy symbol binding failedt
  Referenced from: /usr/local/opt/librdkafka/lib/librdkafka.1.t
  Referenced from: /usr/local/opt/librdkafka/lib/librdkafka.1.: Symbol not found: _timespec_gedylib
  Expected in: /usr/lib/liopt/librdkafka/lib/librdkafka.1.t
  Referenced from: /usr/local/dylib
  Expected in: /usr/lib/lidyld: lazy symbol binding faileddylib
  Expected in: /usr/lib/li: Symbol not found: _timespec_geopt/librdkafka/lib/librdkafka.1.bSystem.B.dylib

: Symbol not found: _timespec_gebSystem.B.dylib

opt/librdkafka/lib/librdkafka.1.dylib
  Expected in: /usr/lib/lit
  Referenced from: /usr/local/t
  Referenced from: /usr/local/bSystem.B.dylib

dylib
  Expected in: /usr/lib/liopt/librdkafka/lib/librdkafka.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _timespedyld: Symbol not found: _timespec_get
  Referenced from: /usr/loc_get
  Referenced from: /usr/local/opt/librdkafka/lib/librdkafkcal/opt/librdkafka/lib/librdkafka.1.dylib
  Expected in: /usr/lidyld: Symbol not found: _timespea.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

bSystem.B.dylib

opt/librdkafka/lib/librdkafka.1.dyld: lazy symbol binding failedb/libSystem.B.dylib

dyld: lazy symbol binding failedc_get
  Referenced from: /usr/lodyld: lazy symbol binding faileddylib
  Expected in: /usr/lib/li: Symbol not found: _timespec_gedyld: lazy symbol binding failed: Symbol not found: _timespec_gecal/opt/librdkafka/lib/librdkafk: Symbol not found: _timespec_gedyld: Symbol not found: _timespea.1.dylib
  Expected in: /usr/lit
  Referenced from: /usr/local/c_get
  Referenced from: /usr/lot
  Referenced from: /usr/local/opt/librdkafka/lib/librdkafka.1.b/libSystem.B.dylib

cal/opt/librdkafka/lib/librdkafk: Symbol not found: _timespec_gea.1.dylib
  Expected in: /usr/lit
  Referenced from: /usr/local/dyld: lazy symbol binding faileddylib
  Expected in: /usr/lib/lidyld: lazy symbol binding failedopt/librdkafka/lib/librdkafka.1.: Symbol not found: _timespec_geb/libSystem.B.dylib

dylib
  Expected in: /usr/lib/lit
  Referenced from: /usr/local/bSystem.B.dylib

bSystem.B.dylib

dyld: lazy symbol binding failedbSystem.B.dylib

opt/librdkafka/lib/librdkafka.1.t
  Referenced from: /usr/local/: Symbol not found: _timespec_geopt/librdkafka/lib/librdkafka.1.: Symbol not found: _timespec_geopt/librdkafka/lib/librdkafka.1.dylib
  Expected in: /usr/lib/lidylib
  Expected in: /usr/lib/lidyld: Symbol not found: _timespedylib
  Expected in: /usr/lib/lit
  Referenced from: /usr/local/bSystem.B.dylib

c_get
  Referenced from: /usr/lobSystem.B.dylib

bSystem.B.dylib

opt/librdkafka/lib/librdkafka.1.cal/opt/librdkafka/lib/librdkafkt
  Referenced from: /usr/local/dylib
  Expected in: /usr/lib/lidyld: Symbol not found: _timespedyld: Symbol not found: _timespec_get
  Referenced from: /usr/lobSystem.B.dylib

opt/librdkafka/lib/librdkafka.1.bSystem.B.dylib

dyld: lazy symbol binding faileddyld: Symbol not found: _timespedylib
  Expected in: /usr/lib/lical/opt/librdkafka/lib/librdkafkdyld: Symbol not found: _timespec_get
  Referenced from: /usr/lodyld: lazy symbol binding faileda.1.dylib
  Expected in: /usr/libSystem.B.dylib

: Symbol not found: _timespec_gecal/opt/librdkafka/lib/librdkafkt
  Referenced from: /usr/local/a.1.dylib
  Expected in: /usr/liopt/librdkafka/lib/librdkafka.1.c_get
  Referenced from: /usr/lob/libSystem.B.dylib

dylib
  Expected in: /usr/lib/lical/opt/librdkafka/lib/librdkafkc_get
  Referenced from: /usr/lob/libSystem.B.dylib

dyld: Symbol not found: _timespea.1.dylib
  Expected in: /usr/libSystem.B.dylib

cal/opt/librdkafka/lib/librdkafkc_get
  Referenced from: /usr/lodyld: Symbol not found: _timespeb/libSystem.B.dylib

a.1.dylib
  Expected in: /usr/lical/opt/librdkafka/lib/librdkafkc_get
  Referenced from: /usr/lodyld: Symbol not found: _timespea.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

c_get
  Referenced from: /usr/local/opt/librdkafka/lib/librdkafka.1.dylib
  Expected in: /usr/li: Symbol not found: _timespec_gedyld: Symbol not found: _timespea.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _timespesignal: abort trap

**Versions I used:**
 - [ ] librdkafka version 1.2.1
 - [ ] Operating system: macos 10.14.5
 - [ ]Go- go1.10.4 darwin/amd64 

**Linking**:
 librdkafka++.1.dylib -> ../Cellar/librdkafka/1.2.1/lib/librdkafka++.1.dylib
 librdkafka++.a -> ../Cellar/librdkafka/1.2.1/lib/librdkafka++.a
 librdkafka++.dylib -> ../Cellar/librdkafka/1.2.1/lib/librdkafka++.dylib
 librdkafka.1.dylib -> ../Cellar/librdkafka/1.2.1/lib/librdkafka.1.dylib
 librdkafka.a -> ../Cellar/librdkafka/1.2.1/lib/librdkafka.a
 librdkafka.dylib -> ../Cellar/librdkafka/1.2.1/lib/librdkafka.dylib

**Comment by maparent** [comment]
As you no doubt noticed, this is solved by https://github.com/edenhill/librdkafka/pull/2569

**Comment by Aashna-Agrawal** [comment]
@edenhill The issue still persists.
