### ISSUE TITLE
rd_kafka_consume_callback behavior change

### ISSUE THREAD

**Issue by harishankar1998** [edenhill/librdkafka#2578]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
rd_kafka_consume_callback used to call the callback function when there is no message in the topic partition.
It used to pass a message containing error "RD_KAFKA_RESP_ERR__PARTITION_EOF" to the callback
function.
The new library just return with message count 0.
It doesn't make a call to the callback function.
Is there any change of behavior for rd_kafka_consume_callback()?

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Since v1.0.0 you will need to set `enable.partition.eof=true` to get EOF events

**Comment by harishankar1998** [comment]
Thanks
