### ISSUE TITLE
Consume failed: Local: Broker transport failure, after upgraded from v0.11.3 to v1.0.0.

### ISSUE THREAD

**Issue by lxyscls** [edenhill/librdkafka#2581]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have several dockers running as Kafka's clients. And after I upgraded rdkafka from v0.11.3 to v1.0.0, some dockers exited due to the "Consume failed: Local: Broker transport failure". Around 10 times in a day.
Btw, the code logic and Kafka keep the same.

How to reproduce
================
Around 10 times a day.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): upgrade from v0.11.3 to v1.0.0
 - [x] Apache Kafka version: 0.10.2.1
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: CentOS Linux release 7.4.1708
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Generally you should not exit your client when an error is raised since all errors are automatically retried by the client.

As for the error itself, can you print the error message? (`rd_kafka_message_errstr()`)

**Comment by lxyscls** [comment]
@edenhill Thanks a lot for your suggestion. And I will add those detail error message.

**Comment by lxyscls** [comment]
@edenhill The detail is "GroupCoordinator response error: Local: Broker transport failure". Any suggestion? Kafka run on 5 hosts and dockers run the same hosts.

**Comment by lxyscls** [comment]
> [2019-10-24 02:05:12,653] INFO [GroupCoordinator 5]: Preparing to restabilize group _QOE_06ccb6f62fc9_7 with old generation 1 (kafka.coordinator.GroupCoordinator)
> [2019-10-24 02:05:12,653] INFO [GroupCoordinator 5]: Group _QOE_06ccb6f62fc9_7 with generation 2 is now empty (kafka.coordinator.GroupCoordinator)

According to our syslog, I found some logs in the server log. I don't know why broker needs to restabilize? Because the docker will exit on the error, so it will "empty".

**Comment by NeoyeElf** [comment]
I have probably run into the same error after I have upgrade from v0.11.6 to v1.2.2. The error message is:
`'Local: Broker transport failure',\n  code: -195,\n  errno: -195,\n  origin: 'kafka'`

1. I want to know what does the error message mean? 
2. What's the difference between `code:-1` and `code:-195`? and should I ignore it or do something?

[the detail I have write in the issue for node-rdkafka](https://github.com/Blizzard/node-rdkafka/issues/738)
