### ISSUE TITLE
Is it safe to mutate the payload returned by rd_kafka_consume?

### ISSUE THREAD

**Issue by benesch** [edenhill/librdkafka#2589]
Propagating a question from rust-rdkafka: https://github.com/fede1024/rust-rdkafka/issues/95

Basically, is it safe to mutate `payload` in the `rd_kafka_message_t` returned by `rd_kafka_consume`? Without changing its length, of course. The docs don't seem to say much on the point. INTRODUCTION.md says the memory is still owned by librdkafka and needs to be returned to librdkafka via `rd_kafka_message_destroy`, but it seems like the application has ownership over the message in the meantime, and so it seems like it might be ok to mutate the payload before handing it back to rdkafka.

**Comment by edenhill** [comment]
There are currently no constraints to modifying the per-message key/payload as long as honouring the key/payload lengths, but this should be considered and implementation detail and there are no formal guarantees that this will continue to be the case in future versions.

In practice I don't see a reason why this would ever change though.

**Comment by benesch** [comment]
Great, thanks, @edenhill! Sounds like we can expose this upstream as long as we caveat it properly.
