### ISSUE TITLE
Misleading description in rdkafkacpp.h header (line 1738 and 1756)

### ISSUE THREAD

**Issue by naszta** [edenhill/librdkafka#2592]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Time duration in `MessageTimestamp` is microsecond and not millisecond. Could we fix the descriptions in the code?

How to reproduce
================
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1756

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The Kafka message timestamp is in milliseconds, not microseconds.
