### ISSUE TITLE
duplicate message consumption when resuming active partition

### ISSUE THREAD

**Issue by gridaphobe** [edenhill/librdkafka#2593]
Description
===========
There appears to be a race condition in `RdKafka::Handle::resume` that can result in duplicate message consumption if you `resume` a partition that is already active. The docs don't make it clear whether it's valid to call `resume` on an active partition, or if you should only call `resume` on a paused partition.

How to reproduce
================
I have a [sample client](https://gist.github.com/gridaphobe/c75f8f0d4953a65a39388f180d73ae78) that demonstrates the issue. The duplicate message consumption happens on multiple Linux distros and macOS (it's very reliable on Linux but less so on macOS), and on librdkafka `v1.1.0` and `v1.2.2-RC1`. The [debug logs](https://gist.github.com/gridaphobe/15442abde75f04d246bc7737528ad06c) (with `debug=fetch,consumer,topic` show librdkafka consuming partition 0, offset 0, and then resuming at partition 0, offset 0.

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.2.2-RC1`
 - [X] Apache Kafka version: `2.3.0`
 - [X] Operating system: `ubuntu-18.04, rhel7, macos-10.14.6`
 - [X] Provide logs (with `debug=fetch,consumer,topic` as necessary) from librdkafka

**Comment by edenhill** [comment]
I think this might be a problem with seek(),pause(),resume() being asynchronous and returning before a new version barrier has been set for the partition fetch state. This was however fixed in v1.6.0.
