### ISSUE TITLE
Uneven consumption rate across partitions

### ISSUE THREAD

**Issue by sebwills** [edenhill/librdkafka#2597]
Description
===========

I have a single high-level librdkafka consumer consuming from a topic with 50 partitions. In a situation where the offset of all partitions is a long way from the last message (i.e. all partitions have plenty of messages to be read), the rate of consumption across the 50 partitions is consistently uneven. I observe that the consumer has a fairly steady rate for each partition, maintained over a period of hours, yet the rate for the fastest-consuming partition is 2.5 messages/sec as opposed to more like 0.5 messages/sec for the lowest partition.

Please can you comment on why this might be and what determines the relative consumption rates across assigned partitions in a situation where all partitions have plenty of new messages available?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.1.0`
 - [x] Apache Kafka version: `2.3.0`
 - [x] librdkafka client configuration: `nothing relevant`
 - [x] Operating system: `linux`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#what-are-partition-queues-and-why-are-some-partitions-slower-than-others
