### ISSUE TITLE
PKCS 11 support

### ISSUE THREAD

**Issue by benp20** [edenhill/librdkafka#2599]
Description
===========
I read through the SSL guide for rdkafka.
I’m wondering if the library enabled use of PKCS 11 interface for interacting with private keys stored in a hardware module (HSM).

Thanks 

 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Yes, you can pass a PKCS11/PFX store to `ssl.keystore.location`, or if it resides in memory use the methods defined here: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2033

**Comment by benp20** [comment]
Thanks @edenhill.
In my use case, we want the rdkafka based application to not access the private keys directly but instead go through the HSM. To that extent, using rd_kafka_conf_set_ssl_cert is not desirable nor is giving application access to the keystore.

My hope was to have rdkafka use something like  pkcs-11 along with the associated cryptoki API (https://docs.oracle.com/cd/E23823_01/html/816-4863/chapter2-10.html) to have the underlying HSM perform the cryptographic operations such as message decryption and signing during session creation and messaging. This way, the application itself does not need access to the private key.

The question is whether something like this is supported in rdkafka. If not I'd appreciate some guidance on how to go about adding this functionality and estimated complexity/ level of effort.

Thanks!

**Comment by sirzooro** [comment]
You probably will need fix for #2601 to make it work.
