### ISSUE TITLE
The consumer's throughput degrades seriously after enabling the statistics info

### ISSUE THREAD

**Issue by kenneth-jia** [edenhill/librdkafka#2604]
Description
===========
Problem: 
    We're doing the throughput test with kafka consumers, and see what's the best result.
After enabling the statistics info (with `statistics.interval.ms=1000`), we see the throughput was seriously impacted! 1500 MB/s (with `statistics.interval.ms=0`) -> 850 MB/s (with `statistics.interval.ms=1000`), 

Question:
    1. Could the function `rd_kafka_stats_emit_all` be more efficient?
    2. Beside being triggered by timer, could the statistics info also be emitted on demand? 

How to reproduce
================
1. librdkafka release: v1.2.1
2. Topics configuration: partitions=5, replication_factor=3
2. Try with a consumer (configured with the statistics callback), polling (previously published) messages, with `statistics.interval.ms=1000`, and see the result.
3. Try with `statistics.interval.ms=0` later, and we'll see the throughput would be much better!

I will also attach a graph to show the result.

**Comment by kenneth-jia** [comment]
![statistics_interval_impact](https://user-images.githubusercontent.com/48558845/68105960-044c2180-fed8-11e9-8564-ed7d74eda911.png)

**Comment by edenhill** [comment]
Interesting.
Do you get different throughput if you increase statistics.interval.ms even further, let's say 10s? or 0.5s?

The per-interval statistics histogram rollovers are quite expensive.

**Comment by kenneth-jia** [comment]
I didn't try with other intervals, -- I could try it later anyway.
I noticed many lock operations involved (towards `rkt`), could this part be improved?
BTW, interesting thing is, during our test, the `statistics.interval.ms=1000` configuration would not impact a producer's throughput, -- which is quite strange!

**Comment by edenhill** [comment]
Please do try that.

side question: is that Megabyte or Megabit per second?

**Comment by kenneth-jia** [comment]
It's Megabyte per second.
I'll try with different intervals, thanks. :-)

**Comment by kenneth-jia** [comment]
![more_stats](https://user-images.githubusercontent.com/48558845/68219758-76a72980-ffde-11e9-978b-4c96f874e2c5.png)
(consumer's throughput with statistics.intervals [0, 0.5s, 1s, 2s, 5s] )

**Comment by edenhill** [comment]
Perfect, thank you.
So that shows there is a direct inverse correlation between the interval and the throughput.

What hardware and OS are you running this on?
Are you making use of the histograms in the stats?

**Comment by kenneth-jia** [comment]
![more_stats2](https://user-images.githubusercontent.com/48558845/68289849-ce956d00-007e-11ea-854b-55b1ce896e41.png)
Here's another graph (the performance impact seems more obvious)

**Comment by kenneth-jia** [comment]
We're running kafka clusters in 3 dedicated servers, -- with Xeon E5-2650, DELL PERC 730P Mini SCSI disk, RHEL 6.1. 
We need these statistics info to show the on-time perf histograms in future. For now, I'm working on the `C++ Wrapper` for librdkafka, and considering how to expose an interface for stats info, -- the degraded throughput gave me a shock.
BTW, our `C++ Wrapper` currently is used (and keeps being improved) within Firm, -- it would be open-sourced in some later time. :-)

**Comment by edenhill** [comment]
From what I can gather the E5-2650 is not very powerful, and the hdr histogram rollovers with average calculations are quite CPU intensive, that is probably why you are seeing the drop in throughput as the statistics interval is decreased.

To verify this run your program with a profiler (e.g., `valgrind --tool=callgrind ..` and then `kcachegrind ..`) to see where CPU cycles are being spent, my guess is in the histogram rollover.


Looking forward to your C++ wrapper!

**Comment by kenneth-jia** [comment]
Sorry, I misunderstood your question (about hdr histogram) -- in fact, we did not enable `WITH_HDRHISTOGRAM` macro.
Anyway, I'll try the profiler later, thanks!

**Comment by edenhill** [comment]
The HdrHistograms are enabled by default, but they do come at a cost since they are CPU-intensive to average on.
So my thinking was that if you don't need the histograms we could make it configurable to turn just the histograms off.

**Comment by kenneth-jia** [comment]
Yes, after profiling, we found the histograms were enabled, then we could benefit from disabling the MACRO. Thanks! :-)

**Comment by edenhill** [comment]
Could you remove "WITH_HDRHISTOGRAM" from co

Could you comment out this block: https://github.com/edenhill/librdkafka/blob/master/configure.self#L105-L108

Then do:
```
$ ./configure --clean
$ ./configure
$ make -j
$ sudo make install
```

and then run your profiler again to see if the situation is better?

**Comment by kenneth-jia** [comment]
Sorry for the late response.
I had a try, with `WITH_HDRHISTOGRAM` disabled, while seems no difference.
Here's the perf graph,
![with-no-histgram-stats](https://user-images.githubusercontent.com/48558845/69613747-02cece80-102a-11ea-9363-241d6a3257f5.png)

**Comment by edenhill** [comment]
If you enable debugging the client will print a log line like this at startup, verify that HDRHISTOGRAM is not in there:
`%7|1574713103.833|INIT|0030_offset_commit#consumer-14| [thrd:app]: librdkafka v1.3.0-RC1-2-g471ec7 (0x10300ff) 0030_offset_commit#consumer-14 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, GCC GXX PKGCONFIG INSTALL GNULD LDS LIBDL PLUGINS ZLIB SSL SASL_CYRUS ZSTD HDRHISTOGRAM LZ4_EXT RAPIDJSON SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x100)`

**Comment by kennethjia** [comment]
No, `HDRHISTOGRAM` was not enabled. As below,
`FEATURE | [thrd:GroupCoordinator]: GroupCoordinator/2: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD,UnitTest`

**Comment by edenhill** [comment]
That is the wrong debug log, you will want to look for "INIT ... initialized" line as shown above

**Comment by kennethjia** [comment]
Sorry, here is the right one,
`2019-11-26 06:16:14.068498]DEBUG Consumer[perf-consumer-139790787327744] INIT | [thrd:app]: librdkafka v1.2.1 (0x10201ff) perf-consumer-139790787327744#consumer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,sasl_oauthbearer, CC CXX PKGCONFIG INSTALL GNULD LD
S LIBDL PLUGINS ZLIB SSL SASL_CYRUS SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0xffff)`

**Comment by edenhill** [comment]
Thanks.

So if you run profiling on this build, where does it spend its time?

**Comment by kenneth-jia** [comment]
Here's the profile result, 
1) With statistics info disabled,
![profile-with-no-stats](https://user-images.githubusercontent.com/48558845/69720865-814f6d00-110b-11ea-93a5-e74e6041f009.png)
2) With statistics info enabled (per second),
![profile-with-per-1s-stats](https://user-images.githubusercontent.com/48558845/69720891-8f9d8900-110b-11ea-98d4-6eea9245bca2.png)

It seems the  statistics info emitting would cost `rd_kafka_q_serve_rkmessages` more time.

**Comment by edenhill** [comment]
Hey @kenneth-jia, is this still an issue?

**Comment by kenneth-jia** [comment]
> Hey @kenneth-jia, is this still an issue?

Hi, @edenhill I didn't try with newer librdkafka releases, -- these test result was from our internal test env within Firm, thus it was not that "convenience" to share with more details. Good news is, `modern-cpp-kafka` is opensourced now, -- maybe at some later time, I'd work out a simple benchmark tool and try again. So let's close it for now (and re-open it in future if the problem still exists). Thanks! 😀
