### ISSUE TITLE
error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib:

### ISSUE THREAD

**Issue by i-enchev** [edenhill/librdkafka#2606]
Description
===========
I have a new Kafka project and use again librdkafka. This time I get an error:
Failed to create new producer, reason code: ssl.ca.location failed: .\crypto\x509\by_file.c:254: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib: 

Do you know what is wrong?

Best regards,
ie

Checklist
=========

 - [x] librdkafka version RD_KAFKA_VERSION  0x010202ff
 - [x] Apache Kafka version: `2.2.1`
 - [x] librdkafka client configuration: `12-07-2019 10:48:08.932 request.required.acks = -1
12-07-2019 10:48:08.933 request.timeout.ms = 5000
12-07-2019 10:48:08.934 message.timeout.ms = 300000
12-07-2019 10:48:08.939 queuing.strategy = fifo
12-07-2019 10:48:08.940 produce.offset.report = false
12-07-2019 10:48:08.941 partitioner = consistent_random
12-07-2019 10:48:08.942 compression.codec = inherit
12-07-2019 10:48:08.944 compression.level = -1
12-07-2019 10:48:08.945 auto.commit.enable = true
12-07-2019 10:48:08.947 auto.commit.interval.ms = 60000
12-07-2019 10:48:08.948 auto.offset.reset = largest
12-07-2019 10:48:08.949 offset.store.path = .
12-07-2019 10:48:08.950 offset.store.sync.interval.ms = -1
12-07-2019 10:48:08.951 offset.store.method = broker
12-07-2019 10:48:08.955 consume.callback.max.messages = 0
 - [x] Operating system: `Win 32>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Are you sure you are not specifying ssl.ca.location in your configuration?

The error indicates that you specified a file for ssl.ca.location but the file format is not in x509 format.

Side note: "auto.commit.enable" is deprecated and only for use with the legacy consumer, use "enable.auto.commit" instead.

**Comment by i-enchev** [comment]
Thank you very much. The format was not x509.

**Comment by Pilipets** [comment]
Getting the same error after generating ca-cert and other keys with https://github.com/confluentinc/librdkafka/wiki/Using-SSL-with-librdkafka for Red Hat.

`The error indicates that you specified a file for ssl.ca.location but the file format is not in x509 format.`
How to convert to x509 format then?

```
Create a CA certificate
If you dont have a proper CA certificate you can generate your own for testing.

gen-ssl-certs.sh ca ca-cert <the_ca_CN>
```
That's what I did
