### ISSUE TITLE
RdKafka::OAuthBearerTokenRefreshCb interface needs an RdKafka::Handle to call oauthbearer_set_token()

### ISSUE THREAD

**Issue by chrisbeard** [edenhill/librdkafka#2607]
Description
===========
According to the [`RdKafka::OAuthBearerTokenRefreshCb`](https://github.com/edenhill/librdkafka/blob/v1.2.1/src-cpp/rdkafkacpp.h#L548-L583) docs, a class implementing this interface should call [`RdKafka::oauthbearer_set_token()`](https://github.com/edenhill/librdkafka/blob/v1.2.1/src-cpp/rdkafkacpp.h#L1519-L1562), in the callback.

Since `oauthbearer_set_token()` is a member function of `RdKafka::Handle`, the `RdKafka::OAuthBearerTokenRefreshCb` implementation needs access to the `RdKafka::Handle` which triggered the callback. However, this `RdKafka::Handle` object can't exist when the `OAuthBearerTokenRefreshCb` object is used to configure `RdKafka::Conf`, since the Producer/Consumer is created from this `RdKafka::Conf`, and no `RdKafka::Handle` is provided as an argument to `oauthbearer_token_refresh_cb`.

This leads to code like the following:

```c++
RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
std::string errstr;
...
conf->set("sasl.mechanisms", "OAUTHBEARER", errstr);

// Provide our OAuthBearerTokenRefreshCb implementation. We can't bind the RdKafka::Handle* to our callback
// because the RdKafka::Handle which will trigger the token refresh has not been created yet.
MyOAuthBearerTokenRefreshCb cb;
conf->set("oauthbearer_token_refresh_cb", &cb, errstr);

// Create the RdKafka::Handle which will be using OAUTHBEARER
RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);

// Store the RdKafka::Handle* which will be used in our implementation of oauthbearer_token_refresh_cb() to call oauthbearer_set_token().
cb.setHandle(producer);

// Trigger the token refresh
producer->poll(1000);
```

This seems really clunky, especially if a task is creating multiple producers and consumers.

In comparison, the [C API](https://github.com/edenhill/librdkafka/blob/v1.2.1/src/rdkafka.h#L1816-L1856) provides a `rd_kafka_t` as a callback parameter.

It looks like [`RdKafka::oauthbearer_token_refresh_cb_trampoline`](https://github.com/edenhill/librdkafka/blob/v1.2.1/src-cpp/HandleImpl.cpp#L135-L144) could have provide the necessary arg to the callback.
Can the C++ API be aligned with the C API in this respect? In particular, can `oauthbearer_token_refresh_cb()` receive a `RdKafka:Handle*` as a second parameter?

Also, should the [docs](https://github.com/edenhill/librdkafka/blob/v1.2.1/src-cpp/rdkafkacpp.h#L548-L574) be updated to replace `RdKafka::oauthbearer_set_token()` with `RdKafka::Handle::oauthbearer_set_token()`, and similarly for `oauthbearer_set_token_failure()`?

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.2.1`
 - [x] Apache Kafka version: `2.2.0`
 - [X] librdkafka client configuration: `sasl.mechanisms=OAUTHBEARER, oauthbearer_token_refresh_cb`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
@rondagostino Comments?

**Comment by rondagostino** [comment]
Yes, this makes a lot of sense.  It would be a breaking change, though -- but it does seem like it would be significantly better s proposed.  I'm currently away from my development environment and unable to code the change, but I can probably take a look next week -- unless @chrisbeard you wish to submit a P/R before then?  I agree it is a great bug report -- thanks!
