### ISSUE TITLE
librdkafka installed but not working and searching

### ISSUE THREAD

**Issue by flik** [edenhill/librdkafka#2608]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
```

[root@9bxxx /]# php -i | grep kafka
[root@9bxxx /]# yum install librdkafka-devel
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.umd.edu
 * epel: iad.mirror.rackspace.com
 * extras: mirror.umd.edu
 * remi-php71: mirror.team-cymru.com
 * remi-safe: mirror.team-cymru.com
 * updates: mirror.cs.vt.edu
Package librdkafka-devel-0.11.5-1.el7.x86_64 already installed and latest version
Nothing to do
```

How to reproduce
================
```

[root@9bxxx /]# php -i | grep kafka
[root@9bxxx /]# yum install librdkafka-devel
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.umd.edu
 * epel: iad.mirror.rackspace.com
 * extras: mirror.umd.edu
 * remi-php71: mirror.team-cymru.com
 * remi-safe: mirror.team-cymru.com
 * updates: mirror.cs.vt.edu
Package librdkafka-devel-0.11.5-1.el7.x86_64 already installed and latest version
Nothing to do
```

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `librdkafka-devel-0.11.5-1.el7.x86_64`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x ] Operating system: ` Centos 7 (x64) `
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You're not providing any error output, I'm guessing from php-rdkafka?

You should also consider installing the latest version of librdkafka from the Confluent RPM repository, librdkafka v0.11.5 is really old.

https://docs.confluent.io/current/installation/installing_cp/rhel-centos.html#systemd-rhel-centos-install
