### ISSUE TITLE
librdkafka auto offset store potential data loss

### ISSUE THREAD

**Issue by zelong430** [edenhill/librdkafka#2609]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

This is more of a question rather than an issue. I read the FAQ and offset management. 
I'm trying to understand the potential data loss in case of consumer failure with auto.offset.commit and auto.offset.store enabled.

In the configuration description of auto.offset.store it says "Automatically store offset of last message provided to application."

What does "last message provided to application." means? Does this mean the last message I got from Kafka_Consumer->consume() call? 

If this is the case, does this means if my consumer dies after an auto.offset.commit happens but before the processing of a message finish. Then, I could potentially lose AT MOST 1 message because the consume() call gives me 1 message at a time and auto.offset.store will only store last message provided to application.

I may re-process more messages under this setting, but data loss will be limited to at most 1 message. Is may understanding correct?

If this is also the case, than one benefit of Kafka_Consumer_Consume providing only 1 message compare with Java's consumer.poll which giving you multiple messages to process is that you may loss more data in Java than librdkafka?

This is one of the question that has been confused me for quite a while and I can't find answer else where. Thanks for the help.

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by nick-zh** [comment]
@zelong430 your assumption is correct, if you have enabled to automatically commit offsets, you might lose the message if due to you setting the offset was commited, but your application dies before processing it. This is why, depending on your usecase, you might want to commit manually and disable auto commit. Depending on how your application works, this might mean though, that potentially you might read a message more than once if you die while commiting.

**Comment by edenhill** [comment]
Related:
https://github.com/edenhill/librdkafka/issues/2610#issuecomment-598205565
