### ISSUE TITLE
What does commitSync provides commitAsync

### ISSUE THREAD

**Issue by zelong430** [edenhill/librdkafka#2610]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

In the issue 826, edenhill mentioned that each call to commitAsync will add a OffsetCommitRequest to be added to a local queue. The requests in the queue will then being sent to the consumer group coordinate one by one. The consume will wait for response for each of them. And if the commitAsync is called for each message, this queue could build up and results in a lot of OffsetCommitRequest to be timeout. 

I can't find my question in that issue so I just asked it in a new issue in case other people run into same confusion as me.

1) If there is a local queue for the OffsetCommitRequest, then how the commitSync works? Does it also put a request in that queue? Does it wait until the OffsetCommitRequest get a response from the coordinate? What does it actually blocking for? And what is the max waiting time.

2) With the commitSync, and am willing to pay for performance, could it avoids duplicate process message and message loss in case of consumer failure?

3) If in the 826 case, where I just have one consumer and stack up too many OffsetCommitRequest in the queue or in flight, what will be cost by a lot of OffsetCommitRequest timeout? Will too many of this kind of timeout close the connection and let broker think the consumer is dead? Will these timeouts block the consumer's fetching data request and thus stop consumption? Or it just block some consumption but still keep the consumer alive because of dedicated heartbeat thread?

Thank you so much!

**Comment by nick-zh** [comment]
i think i can answer question 1:
commitSync works the same as async with the difference, that a queue for the response will be created and it will be polled indefinitely until you get a result.

**Comment by zelong430** [comment]
> i think i can answer question 1:
> commitSync works the same as async with the difference, that a queue for the response will be created and it will be polled indefinitely until you get a result.

Then how long does the sync call block for? until your commit request get response?
Or it just put in the queue and indefinitely pulling that queue to send out offsetCommitRequest but not actually WAITING for response.

**Comment by nick-zh** [comment]
From what I see, it blocks until you get the response, this is why you lose a bit of performance doing this.

**Comment by zelong430** [comment]
> From what I see, it blocks until you get the response, this is why you lose a bit of performance doing this.

Oh, ok, That could be potentially quite expensive wait. In case of the __comsumer_offsets topic going under-replication, it could wait for up to "offsetCommitRequest timeout". Alright, should be very cautious about this.

**Comment by edenhill** [comment]
1. As @nick-zh says, All offset commits share the same queue and broker connection (the GroupCoordinator logical broker connection).
2. If you commitSync prior to message processing you guarantee at-most-once processing, if you comit after processing you guarantee at-least-once processing. For exactly-once-processing you will need the transactional producer API, see the example here: https://github.com/edenhill/librdkafka/blob/txnexample/examples/transactions.c
3. Heartbeats, group operations and commits are sharing the same group coordinator connection, while Fetch is done on other connections. So if your group coordinator connection fills up with slow OffsetCommitRequests you risk Heartbeats arriving too late which will eventually time out the member from the group.
