### ISSUE TITLE
Question: rd_kafka_consume_callback and manual commit

### ISSUE THREAD

**Issue by nick-zh** [edenhill/librdkafka#2617]
Dear Magnus

What is the proper way to handle committing offsets manually with `rd_kafka_consume_callback`?
Is it ok to use `rd_kafka_consume_callback_queue` for a high level consumer (on the main queue)?
Thanks in advance for your help!

Cheers,
Nick

**Comment by nick-zh** [comment]
silly me, i think for high level i should of course use `rd_kafka_conf_set_consume_cb` the question on how to handle manual commits best for both still remains though.

**Comment by nick-zh** [comment]
@edenhill any insight on what best practice is for manual commits using the callbacks? Thanks in advance for helping me out!

**Comment by edenhill** [comment]
The consumer callbacks are generally not supported for the new high-level consumer and will be removed in the next version of the API.

As for commit_queue(), et.al, those are fine to use.
