### ISSUE TITLE
Long timeout in state CONNECT

### ISSUE THREAD

**Issue by jwheels** [edenhill/librdkafka#2622]
Description
===========
I'm trying to reduce the amount of time taken to get a connection time out error/log-message from librdkafka.

I have configured "message.timeout.ms", "socket.timeout.ms", "metadata.request.timeout.ms" to be 5 seconds.

When all brokers are unreachable e.g. due to firewall rules, it takes almost two minutes before I see any connection timeout errors:
REDACTED:9092/bootstrap: Connect to ipv4#REDACTED:9092 failed: Operation timed out (after 127260ms in state CONNECT)

Is there any way to control this particular timeout?

How to reproduce
================
* Configure a producer with low timeouts for "message.timeout.ms" "socket.timeout.ms" and "metadata.request.timeout.ms"
* Create firewall rules to drop packets between the producer and broker(s)
* Observe how long it takes to get connection timeouts

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.1.0`
 - [x] Apache Kafka version: `2.3`
 - [x] librdkafka client configuration: `message.timeout.ms=5000,socket.timeout.ms=5000,metadta.request.timeout.ms=5000,debug=broker`
 - [x] Operating system: `alpine linux`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka

 - [x] Provide broker log excerpts N/A
 - [x] Critical issue No

**Comment by edenhill** [comment]
librdkafka does not provide a means to control the connect timeout, but relies on the TCP stack to do so.

We could add a `connect.timeout.ms` and an internal timer that aborts the connect if it hasn't succeeded within the threshold.

**Comment by jwheels** [comment]
Thanks @edenhill. I will try to work around the issue for now.

I had forgotten that the connect syscall provides no means of specifying a timeout (other than using non-blocking sockets, and polling to check connection status). I haven't looked through the librdkafka code enough to see if that approach is already being used, but it sounds like a headache if not.

**Comment by edenhill** [comment]
We're doing asynchronous connections (non-blocking connect()), but we're not enforcing a timeout.

The quick fix for you might be to simply add a `setsockopt(.., SNDTIMEO, ..)` prior to connect and reset it after the connection is established.
