### ISSUE TITLE
Run make error

### ISSUE THREAD

**Issue by SteveAIS** [edenhill/librdkafka#2623]
Description
===========
I am getting this error now when running make. It was working fine yesterday. I saw some recent code changes in this file. 

rdkafka_mock.c: In function 'rd_kafka_mock_push_request_errors':
rdkafka_mock.c:1363:9: warning: implicit declaration of function 'va_start'; did you mean 'assert'? [-Wimplicit-function-declaration]
         va_start(ap, cnt);
         ^~~~~~~~
         assert
rdkafka_mock.c:1366:25: warning: implicit declaration of function 'va_arg'; did you mean 'ualarm'? [-Wimplicit-function-declaration]
                         va_arg(ap, rd_kafka_resp_err_t);
                         ^~~~~~
                         ualarm
rdkafka_mock.c:1366:36: error: expected expression before 'rd_kafka_resp_err_t'
                         va_arg(ap, rd_kafka_resp_err_t);
                                    ^~~~~~~~~~~~~~~~~~~
rdkafka_mock.c:1367:9: warning: implicit declaration of function 'va_end'; did you mean 'rand'? [-Wimplicit-function-declaration]
         va_end(ap);
         ^~~~~~
         rand
make[1]: *** [../mklove/Makefile.base:79: rdkafka_mock.o] Error 1
make[1]: Leaving directory '/app/librdkafka/src'
make: *** [Makefile:24: libs] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2

How to reproduce
================
git clone

run make

Checklist
=========

Step 8/17 : RUN git clone https://github.com/edenhill/librdkafka.git
Step 9/17 : WORKDIR /app/librdkafka
Step 10/17 : RUN ./configure --prefix /usr
Step 11/17 : RUN make

[error is here]

**Comment by edenhill** [comment]
What OS and compiler is this on?

**Comment by edenhill** [comment]
This is now fixed on master branch.
