### ISSUE TITLE
Manual offset commit won't work

### ISSUE THREAD

**Issue by davideberra** [edenhill/librdkafka#2628]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Cannot make manual offset commit to work.
I've written a client (C language) connecting as consumer to a Kafka cluster.
Everything works normally if i set auto.commit.enable to true (and avoid to call rd_kafka_offset_store), but if i set it to false, the client, everytime is restarted, starts to pop data from offset zero like if no offset is ever commited to broker.

This is the main cycle of the app:

```
    rkmessage =  rd_kafka_consumer_poll(rk, timeout);

    // do things with msg ....

    // when done, i want to commit offset
   if (rkmessage->err == RD_KAFKA_RESP_ERR_NO_ERROR) 
         rd_kafka_offset_store(rkmessage->rkt, rkmessage->partition, rkmessage->offset));
```

I tried also to leave auto.commit.enable to true and enable.auto.offset.store to false... no luck.

What is the exact sequence of function to be called if we want manual offset commit?

How to reproduce
================
Set parameters like below 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.2.2`
 - [x] Apache Kafka version: `2.0.0`
 - [x] librdkafka client configuration: `
offset.store.method=broker
auto.commit.enable=false
auto.commit.interval.ms=1000
enable.auto.offset.store=true
auto.offset.reset=smallest
log.connection.close=false`
 - [x] Operating system: `CentOS 6.9`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You should not use `auto.commit.enable`, it is for the legacy consumer API.
Use `enable.auto.commit` instead.
