### ISSUE TITLE
[Question] Is Kafka TopicCreation supported?

### ISSUE THREAD

**Issue by vasakris** [edenhill/librdkafka#2632]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Is Kafka TopicCreation supported?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.0.0`
 - [ ] Apache Kafka version: `2.1.0`
 - [ ] Operating system: `linux`

**Comment by edenhill** [comment]
See rd_kafka_CreateTopics():
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L5451

**Comment by vasakris** [comment]
Hi edenhill

Thanks. But i am not getting how to use this function.
I saw admin test - https://github.com/edenhill/librdkafka/blob/master/tests/0081-admin.c
But it has many things.

To create topic, should i need to just call rd_kafka_NewTopic_new function? Or i need to initialize somethings before calling this function?

**Comment by edenhill** [comment]
Specify what topics to create by calling NewTopic_new(), then pass an array of those objects to CreateTopics()
