### ISSUE TITLE
Feature Request/Questions

### ISSUE THREAD

**Issue by Buttered** [edenhill/librdkafka#2633]
1. Schema Registry
2. Pluggable Partition Assignment for Consumer(s)
3. Exactly One Semantics

As of right now it looks like these 3 features are not available through librdkafka. Is there any plan to add these features to the client so that they are available for wrapper clients such as confluent's GoLang library?  These are extremely important features and make it difficult to migrate from Java to GoLang. Would be awesome if these were added!

**Comment by edenhill** [comment]
1. Schema registry support for C/C++ is provided in [libserdes](https://github.com/confluentinc/libserdes/)
2. Custom Partition assignment strategies: TBD
3. Full EOS lands in late Q4 or early Q1, we're currently finalizing Producer transactions which is the last missing piece.
