### ISSUE TITLE
1 (of 3) brokers failed with SSL expired certificate

### ISSUE THREAD

**Issue by roblos** [edenhill/librdkafka#2637]
Description
===========
My consumer uses SASL/SSL. There are 3 brokers (lets say lp0084, lp0085 and lp0086), to 2 of them the authentication (SSL/SASL) is working and 1 fails, with : Failed to verify broker certificate: certificate has expired (after 13ms in state CONNECT)
I have updated the correct certificate.

What do I miss or doing wrong ?

The message is:
%7|1574778033.961|CONNECT|rdkafka#consumer-1| [thrd:sasl_ssl://lp0086.alliander.local:9094/bootstrap]: sasl_ssl://lp0086.alliander.local:9094/26: Connecting to ipv4#10.88.72.50:9094 (sasl_ssl) with socket 20
%7|1574778033.962|STATE|rdkafka#consumer-1| [thrd:sasl_ssl://lp0086.alliander.local:9094/bootstrap]: sasl_ssl://lp0086.alliander.local:9094/26: Broker changed state DOWN -> CONNECT
%7|1574778033.962|CONNECT|rdkafka#consumer-1| [thrd:sasl_ssl://lp0086.alliander.local:9094/bootstrap]: sasl_ssl://lp0086.alliander.local:9094/26: Connected to ipv4#10.88.72.50:9094
%7|1574778033.976|BROKERFAIL|rdkafka#consumer-1| [thrd:sasl_ssl://lp0086.alliander.local:9094/bootstrap]: sasl_ssl://lp0086.alliander.local:9094/26: failed: err: Local: SSL error: (errno: Error 0)
%3|1574778033.976|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://lp0086.alliander.local:9094/bootstrap]: sasl_ssl://lp0086.alliander.local:9094/26: Failed to verify broker certificate: certificate has expired (after 14ms in state CONNECT)
%3|1574778033.976|ERROR|rdkafka#consumer-1| [thrd:sasl_ssl://lp0086.alliander.local:9094/bootstrap]: sasl_ssl://lp0086.alliander.local:9094/26: Failed to verify broker certificate: certificate has expired (after 14ms in state CONNECT)
%7|1574778033.976|STATE|rdkafka#consumer-1| [thrd:sasl_ssl://lp0086.alliander.local:9094/bootstrap]: sasl_ssl://lp0086.alliander.local:9094/26: Broker changed state CONNECT -> DOWN
%7|1574778034.975|CONNECT|rdkafka#consumer-1| [thrd:sasl_ssl://lp0086.alliander.local:9094/bootstrap]: sasl_ssl://lp0086.alliander.local:9094/26: broker in state DOWN connecting
%7|1574778034.975|CONNECT|rdkafka#consumer-1| [thrd:sasl_ssl://lp0086.alliander.local:9094/bootstrap]: sasl_ssl://lp0086.alliander.local:9094/26: Connecting to ipv4#10.88.72.50:9094 (sasl_ssl) with socket 20

I also uses openssl to check the certificate on lp0086 (and lp0084).
openssl s_client -connect <host>:9094
This gives no further clues why it failed with 

How to reproduce
================
Just starting the consumer.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] 0.11.6
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: 
bootstrap.servers=lp0084.alliander.local:9094,lp0085.alliander.local:9094,lp0086.alliander.local:9094
group.id=spectrum
debug=security,broker
batch.num.messages=5000
queue.buffering.max.ms=1000
queue.buffering.max.messages=4000000
security.protocol=SASL_SSL
sasl.username=svc_kfk_spect_p@ALLIANDER.LOCAL
sasl.kerberos.service.name=kafka
sasl.kerberos.keytab=/etc/krb5/svc_kfk_spect_p.keytab
sasl.kerberos.principal=svc_kfk_spect_p@ALLIANDER.LOCAL
sasl.kerberos.kinit.cmd=kinit -k -t %{sasl.kerberos.keytab} %{sasl.kerberos.principal}
sasl.kerberos.min.time.before.relogin=3600000
ssl.ca.location=/etc/krb5/keystore-it.pem

 - [ ] Sun solaris 10 (x64(
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please reproduce on latest release, v1.3.0.
