### ISSUE TITLE
rd_kafka_consume_batch () returns an empty message but the topic doesn't have any message

### ISSUE THREAD

**Issue by michema** [edenhill/librdkafka#264]
Hi,

I create a topic (1 partition) without any message.

When I use rd_kafka_consume_batch (), it returns an empty message which I think it should not.

        int numOfMessages = rd_kafka_consume_batch(topicHandler, partition,
                    1000, rkmessages, batchSize);

In this case, the value of "numOfMessages" is one.

**Comment by edenhill** [comment]
Did you check `rkmessage[..]->err` for errors? If the partition is empty you should typically get a `RD_KAFKA_RESP_ERR__PARTITION_EOF` error (which is not really an error, but a way for indicating that the **current** (temporal) end of partition has been reached).
