### ISSUE TITLE
Parsing of member metadata in group membership API?

### ISSUE THREAD

**Issue by benesch** [edenhill/librdkafka#2643]
We recently received [a rust-rdkafka PR](https://github.com/fede1024/rust-rdkafka/pull/184/files) that adds support for parsing the `member_metadata` and the `member_assignment` fields of the `rd_kafka_group_member_info` struct returned by the `rd_kafka_list_groups` API. 

It seems to me that this is something that should be handled by librdkafka itself, and not by every downstream dependency. Is this intuition right, @edenhill? Or is there some specific reason you chose to leave the data in its binary-encoded form?

**Comment by edenhill** [comment]
The group member metadata format is not really part of the Kafka protocol itself, but specified by the group protocol, which in this case is the high-level consumer group protocol, but there's also one or two for connect, etc.

While librdkafka could provide a decoder for the consumer group protocol it would be yet another API with types that needs to be future proof and maintained, for little gain - most applications don't need it.

We therefore suggest that you keep the decoder in rust-rdkafka for the time being.
