### ISSUE TITLE
Reading a topic from multiple threads in C++ (one thread per partition)

### ISSUE THREAD

**Issue by naszta** [edenhill/librdkafka#2644]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
How should it be done? Should I create as many `KafkaConsumer` instances as many threads I use and execute `consume` in each thread one-by-one (based on kafka docs it makes sense here)? Or is a single client enough smart and it could handle the multiple threads when I call `consume` from multiple threads?

How to reproduce
================
It's a question.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You'll want to use the Queue API to redirect partitions to specific queues that you can poll separately.
Look at this test case for how to do it:
https://github.com/edenhill/librdkafka/blob/master/tests/0056-balanced_group_mt.c

The test is written in C but the C++ API is similar.

**Comment by naszta** [comment]
I see. So it's the old school API in C++ with `Consumer` and `Queue`.

**Comment by edenhill** [comment]
No, you should use the high-level KafkaConsumer.

**Comment by naszta** [comment]
Fix myself: simply over re-balance callback.

**Comment by naszta** [comment]
+1 question: Could I register different `RdKafka::RebalanceCb` for each client? I guess yes, but it's better to ask.

**Comment by edenhill** [comment]
Yes

**Comment by naszta** [comment]
So what I did do finally: I have a vector of `KafkaConsumer`. Each has an own thread where `consume` is called. I added the same `RebalanceCb` for each and in the callback I assign a `TopicPartition` to a `KafkaConsumer` based on its `partition` (practically the thread index in the vector is the same as the partition number). As I understand, it's enough to subscribe to just one of the clients (practically to index 0), all other stuffs come for free based on the `RebalanceCb`.

**Comment by edenhill** [comment]
I don't think you should spin up multiple KafkaConsumers, instead use a single one and from the rebalanceCb on ASSIGN you set up a Queue and a thread for each partition, and on REVERT you join the threads and kill the Queues.

**Comment by naszta** [comment]
Oh, I see. I have a try. (When I finish, I create a wiki on it so it could go to FAQ.)

**Comment by naszta** [comment]
`Queue::forward` is the big trick here.

**Comment by aaron-gu** [comment]
Hi @edenhill , when using multiple threads to read from a partition's Queue, what is the commit strategy used? Is it at-least-once message processing semantics?

**Comment by edenhill** [comment]
librdkafka's auto-commit will only register increasing offsets to commit, so you need to take extra care to only store the low watermark of offsets you've processed.

**Comment by aaron-gu** [comment]
Another question with using Queues in threads, it seems like my custom rebalance_cb is not being called when a Queue/thread shuts down, which causes the rest of the messages in the partition to go unprocessed. How do you trigger a rebalance when the number of running Queues changes like this?

**Comment by edenhill** [comment]
With queue-per-partition you still need to poll the main consumer queue for rebalance callbacks, and you should never destroy this queue (until termination).
