### ISSUE TITLE
Does SSL with librd kafka requires ssl.key.password to be set always ?

### ISSUE THREAD

**Issue by NaikPrats** [edenhill/librdkafka#2647]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
If ssl.key.password is not set in config then I am not able to send message from producer. Can someone confirm if thats requirement ? Can my producer still produce messege without requiring ssl.key.password ?

**Comment by edenhill** [comment]
They key password is only required if your client's private key (`ssl.key.location` ) is password protected.

**Comment by NaikPrats** [comment]
Thanks for clarification
