### ISSUE TITLE
rdkafka_performance tool does not consume any messages

### ISSUE THREAD

**Issue by nleeuskadi** [edenhill/librdkafka#2649]
Description
===========
The example program rdkafka_performance does not work when it is executed as a consumer: It does not consume any messages being sent to the topic to be read.
the rdkafka_performance logs these messages:

> % 0 messages (0 bytes) consumed in 0ms: 0 msgs/s (0.00 MB/s)
> % 0 messages (0 bytes) consumed in 0ms: 0 msgs/s (0.00 MB/s)
> % 0 messages (0 bytes) consumed in 0ms: 0 msgs/s (0.00 MB/s)
> ...

How to reproduce
================

1. create a topic
`./kafka-topics.sh --bootstrap-server myserver:9092 --create --replication-factor 3 --partitions 1 --topic test_perf_librdkafka`

2. Start the rdkafka_performance as a consumer to read data - also use `-l` parameter to compute latency
`./rdkafka_performance -C -t test_perf_librdkafka -c 10000000 -l `

3. The rdkafka_performance consumer starts logging these messages:
> % 0 messages (0 bytes) consumed in 0ms: 0 msgs/s (0.00 MB/s)
> % 0 messages (0 bytes) consumed in 0ms: 0 msgs/s (0.00 MB/s)
> ...

2. Run another instance of rdkafka_performance as a producer to publish 10M messages - also use `-l` parameter to compute latency
`rdkafka_performance -P -s 1200 -t test_perf_librdkafka -c 10000000 -l`

3. The rdkafka_performance producer starts logging these messages:
> % Sending 10000000 messages of size 1200 bytes
> % 528910 messages produced (634692000 bytes), 28910 delivered (offset 162721, 0 failed) in 1000ms: 28891 msgs/s and 34.67 MB/s, 10 produce failures, 500000 in queue, no compression
> % 555342 messages produced (666410400 bytes), 55342 delivered (offset 189153, 0 failed) in 2001ms: 27653 msgs/s and 33.18 MB/s, 123 produce failures, 500000 in queue, no compression
> ....

4. While the rdkafka_performance producer is  publishing messages into the topic, the rdkafka_performance consumer desperately still not consume any messages and logs these traces:
> % 0 messages (0 bytes) consumed in 0ms: 0 msgs/s (0.00 MB/s)
> % 0 messages (0 bytes) consumed in 0ms: 0 msgs/s (0.00 MB/s)
> ...

5. If you run a basic kafka-console-consumer tool it reads the messages sent by the rdkafka_performance producer.

Checklist
=========
 - [x] librdkafka version (release number or git tag): 1.3.0
 - [x] Apache Kafka version: 2.3.1
 - [x] librdkafka client configuration:  default values. No overwritten configurations
 - [x] Operating system:  centos 3.10.0-957.el7.x86_64
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Either pass a specific partition to consume, with -p 3, or use the consumer group mode with -G mygroup.

**Comment by nleeuskadi** [comment]
Hi, thank you for your help

Only using "-G myConsumerGrp" parameter does not work neither.
But it works fine with "-p partitionID" parameter. 
is it possible to pass more than one partition to -p parameter ?

**Comment by edenhill** [comment]
You will need to use -G to consume all partitions, just make sure that you specify a unique group-id and allow some time for the initial rebalance to happen.
