### ISSUE TITLE
Pushing messages to consumer(s)

### ISSUE THREAD

**Issue by petermpham** [edenhill/librdkafka#265]
It appears that a consumer can only poll for message availability from Kafka. However, polling could be expensive in term of network traffic. Are there any way we can do something like pushing messages to consumer(s) or some sort of mechanism for notification of message availability so consumer goes out to pull messages home? I ran across discussion on consume_callback() mechanism, not sure if this is some sort of notification of message availability? Please advise.

**Comment by edenhill** [comment]
You are right that the Kafka protocol currently only supports poll based message fetching, which might lead to some performance concerns, especially if the broker RTT is high.
To alleviate this each fetch request may pull a large amount of messages (`fetch.message.max.bytes` defaults to 1 Meg, see https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md).

librdkafka improves this even further by continually fetching messages as fast as it can until the internal fetch queue reaches a certain threshold (`queued.max.messages.kbytes` defaults to 1 Gig).

Depending on the network and broker (disk) speed, this allows a application consume rate of million of messages per second, and the best choice of consume function for high performance use is the callback based one (`rd_kafka_consume_callback()` or its C++ counterpart `consume_callback()`

**Comment by petermpham** [comment]
Can you help to explain how the consume_callback was implemented? Is it right rdkafka transparently polls the broker for available data and fetch them if avail and then executes the callback?

**Comment by edenhill** [comment]
Each broker thread fetches messages from the broker which is leader for those topic+partitions that `consume_start()`has been called for.
The fetched messages are stored in an internal queue (the fetch queue) which is limited in size by `queued.max.message.kbytes`.
When the application calls one of the `consume..()` functions, all it does is pop messages of that internal fetch queue.
