### ISSUE TITLE
rd_kafka_committed high memory usage

### ISSUE THREAD

**Issue by rileyberton** [edenhill/librdkafka#2653]
Description
===========
rd_kafka_committed appearing on jemalloc heap profile report as consuming 90+% of application RAM.  Have tried suggestions in FAQ for limiting RAM but this seems related to offset fetching.

How to reproduce
================
Configured consumer like:

```  
  rd_kafka_conf_t *conf = rd_kafka_conf_new();

  rd_kafka_conf_set_log_cb(conf, tm_kafka_logger);
  rd_kafka_conf_set_dr_msg_cb(conf, msg_delivered);

  snprintf(tmp, sizeof(tmp), "%i", SIGIO);
	rd_kafka_conf_set(conf, "internal.termination.signal", tmp, NULL, 0);
  rd_kafka_conf_set(conf, "enable.auto.commit", "true",
                    NULL, 0);
  rd_kafka_conf_set(conf, "auto.commit.interval.ms", "1000",
                    NULL, 0);
  rd_kafka_conf_set(conf, "enable.auto.offset.store", "true",
                    NULL, 0);
  rd_kafka_conf_set(conf, "queue.buffering.max.ms", "1000",
                    NULL, 0);
  rd_kafka_conf_set(conf, "queue.buffering.max.kbytes", "10000",
                    NULL, 0);
  rd_kafka_conf_set(conf, "request.required.acks", "1",
                    NULL, 0);
  rd_kafka_conf_set(conf, "produce.offset.report", "true",
                    NULL, 0);
  rd_kafka_conf_set(conf, "compression.codec", "lz4",
                    NULL, 0);
  rd_kafka_conf_set(conf, "queued.min.messages", "1000", NULL, 0);
  rd_kafka_conf_set(conf, "fetch.message.max.bytes", "25000", NULL, 0);
  rd_kafka_conf_set(conf, "queued.max.message.kbytes", "10000", NULL, 0);

  rd_kafka_conf_set(conf, "statistics.interval.ms", "2000",
                    NULL, 0);
  rd_kafka_conf_set(conf, "group.id", group_id,
                    NULL, 0);
```

Consuming messages like:

```  
  uint64_t offset = 0;
  rd_kafka_message_t **rkmessages = (rd_kafka_message_t **)calloc(sizeof(rd_kafka_message_t), 1000);
  ssize_t r = rd_kafka_consume_batch(ts->topic->rkt, ts->topic->partition,
                                     100,
                                     rkmessages,
                                     1000);
  if (r != -1) {
    for (int i = 0 ; i < r ; i++) {
      if (tm_kafka_process_message(rkmessages[i], ts) && offset < rkmessages[i]->offset) {
        offset = rkmessages[i]->offset;
      }
      rd_kafka_message_destroy(rkmessages[i]);
    }
  }
  free(rkmessages);
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version: `librdkafka-0.11.5-1.el7.x86_64`
 - [x] Apache Kafka version: `confluent-kafka-2.11-2.1.1cp3-1.noarch`
 - [x] librdkafka client configuration: `see above`
 - [x] Operating system: `Centos 7(x86_64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rileyberton** [comment]
[leak.pdf](https://github.com/edenhill/librdkafka/files/3946551/leak.pdf)

**Comment by edenhill** [comment]
`  rd_kafka_message_t **rkmessages = (rd_kafka_message_t **)calloc(sizeof(rd_kafka_message_t), 1000);`

that should be `sizeof(rd_kafka_message_t *)` or preferably `sizeof(*rkmessages*)`

As for the pdf graph, I don't think the symbols name are correct, those are not proper call chains.

Also make sure to use the latest version of librdkafka (v1.3.0), or at least something fairly recent (>= v1.1.0), v0.11.5 is very old.

**Comment by rileyberton** [comment]
Was missing an `rk_kafka_poll` on the separate producer connection which cleared up this issue.
