### ISSUE TITLE
Is there some config property similar with "num.consumer.fetchers"

### ISSUE THREAD

**Issue by michema** [edenhill/librdkafka#266]
Hi,

For java API, there is a property called "num.consumer.fetchers" to decide the number fetcher threads used to fetch data. Is this property supported in librdkafka? If not, how many fetch threads are used?

Thanks,

**Comment by edenhill** [comment]
Nope, librdkafka runs one thread per broker, so if partitions are load balanced over multiple brokers there will be the corresponding number of threads on the librdkafka side.

**Comment by michema** [comment]
Hi,

I am studying the performance with different consumer properties. I have one broker with one partition. Do you have any suggestion about which property may impact the performance?

Thanks

**Comment by petermpham** [comment]
"librdkafka runs one thread per broker" ... does it also mean one connection per broker? and is this "librdkafka runs one thread per broker" also applied to Producer?

**Comment by edenhill** [comment]
@michema The default librdkafka configuration is aimed at performance (throughput), so you typically should not need to change anything.  What performance numbers are you seeing?
The `rdkafka_performance` tool is a good way to measure performance, it resides in the `examples/` directory.
Typical usage:
`./rdkafka_performance -P -t <my_topic> -p <partition> -c <number_of_messages, e.g., 1000000>  -s <msg_size.e_g._1000>`

**Comment by edenhill** [comment]
@petermpham Yes, one connection per broker, each broker connection handled by its own thread.
This is true for both Consumer and Producer.
