### ISSUE TITLE
Question: Which Kafka version is needed to use the library?

### ISSUE THREAD

**Issue by LiorBanai** [edenhill/librdkafka#2662]
Hi,
I did not get which version of Kafka is needed to install from https://kafka.apache.org/downloads hen using latest release.

Is there a mapping for each version of librdkafka and the Kafka/zoo keeper to install?

**Comment by rnpridgeon** [comment]
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#broker-version-compatibility
