### ISSUE TITLE
Simple visual 2017 console project crashes while trying to cout librdkafka version.

### ISSUE THREAD

**Issue by FabienCarmagnac** [edenhill/librdkafka#2665]
![Capture](https://user-images.githubusercontent.com/6823543/71549333-128c5a80-29bc-11ea-9eee-ddf9f70a3c0d.PNG)
Description
===========
Simple win x64 project under visual 2017 crashes while trying to cout librdkafka version.

How to reproduce
================
1-create visual studio c++ console project, set platform=x64, configuration=Debug
2-add librdkafka 1.3.0 as nugget
3-create a main.cpp with code :
    #include <iostream>
    #include <librdkafka/rdkafkacpp.h>
    #pragma comment(lib,"librdkafkacpp.lib")
    int main()
    {
           std::cout << RdKafka::version_str() << "\n"; 
           return 0;
     }
![Capture](https://user-images.githubusercontent.com/6823543/71549296-c3dec080-29bb-11ea-8d76-525022e8fbaa.PNG)

compile, link, execute. 

Checklist
=========

 - [x] librdkafka version 1.3.0, nugget, x64 win  
 - [ ] Apache Kafka version: NA
 - [ ] librdkafka NA 
 - [ ] Operating system: win10 x64 
 - [ ] Provide logs NA (crashes at first call)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by FabienCarmagnac** [comment]
Got last 1.3.0 source code, builded with visual 2017 => working.
The v120 build toolset is not compatible with v141...
May be you can close this issue ?

**Comment by baocean** [comment]
Hello FabienCarmagnac

Can I ask you to explain me how you managed to build with msvc 2017 (v141) ?
I have number of errors
Error	MSB8020	The build tools for v141 (Platform Toolset = 'v141') cannot be found. 
The missing file is packages\zlib.v141.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\zlib.v141.windesktop.msvcstl.dyn.rt-dyn.targets.

**Comment by FabienCarmagnac** [comment]
I invoked cmake as [described](https://github.com/edenhill/librdkafka/tree/master/packaging/cmake), but forced x64 platform and visual version because cmake uses x86 as default platform even on x64 arch, as you can read [here](https://cmake.org/cmake/help/git-stage/generator/Visual%20Studio%2015%202017.html#toolset-selection). 

For visual 2017 :
> $ cmake -H. -B_cmake_build -A x64   -G "Visual Studio 15 2017" -A x64

For visual 2019 :
> $ cmake -H. -B_cmake_build -A x64   -G "Visual Studio 16 2019" -A x64

**Comment by baocean** [comment]
FabienCarmagnac

Thank you very much.
It worked!
Previously I was trying to compile solution in librdkafka-1.3.0\win32\librdkafka.sln from visual studio.
