### ISSUE TITLE
rd_kafka_conf_set_dr_msg_cb not available.

### ISSUE THREAD

**Issue by chenghaojun** [edenhill/librdkafka#2668]
Description
===========
I want to handle error messages when produce to kafka server. make sure the message will not lost when the server is not available. after read librdkafka documentation, I want to use rd_kafka_conf_set_dr_msg_cb to register a function and hold the failed messages.

I am using librdkafka-1.2.2 and kafka_2.11-1.0.0.2.6.5.0-292, and I compiled producer.c in librdkafka/example as below: 
`
gcc -o producer-c producer.c -I/usr/local/include/librdkafka -L/usr/local/lib -lrdkafka && ./producer-c master0.hdp.dky.com:16667 nilg
`
the broker is invalid 'master0.hdp.dky.com:16667' also as topic 'nilg'. 

How to reproduce
================
1. just install librdkafka-1.2.2
2. and then compile librdkafka/producer.c using gcc.
3. using invalid broker and topic parameters.
4. the `dr_msg_cb` register by `rd_kafka_conf_set_dr_msg_cb` never been called as expected.

Checklist
=========
 - [x] librdkafka version : 1.2.2 release 
 - [ x] Apache Kafka version: kafka_2.11-1.0.0.2.6.5.0-292
 - [ x] librdkafka client configuration: the same as librdkafka/example/producer.c
 - [ x] Operating system: CentOS Linux release 7.5.1804 (Core) 

Logs
=========
```
% Type some text and hit enter to produce message
% Or just hit enter to only serve delivery reports
% Press Ctrl-C or Ctrl-D to exit
%3|1577776229.941|FAIL|rdkafka#producer-1| [thrd:master0.hdp.dky.com:16667/bootstrap]: master0.hdp.dky.com:16667/bootstrap: Connect to ipv4#172.18.72.71:16667 failed: Connection refused
%3|1577776229.941|ERROR|rdkafka#producer-1| [thrd:master0.hdp.dky.com:16667/bootstrap]: master0.hdp.dky.com:16667/bootstrap: Connect to ipv4#172.18.72.71:16667 failed: Connection refused
%3|1577776229.941|ERROR|rdkafka#producer-1| [thrd:master0.hdp.dky.com:16667/bootstrap]: 1/1 brokers are down
adsf
% Enqueued message (4 bytes) for topic nilg
as
% Enqueued message (2 bytes) for topic nilg
dfa
% Enqueued message (3 bytes) for topic nilg
sdf
% Enqueued message (3 bytes) for topic nilg
asdf
% Enqueued message (4 bytes) for topic nilg
^C% Flushing final messages..
% 5 message(s) were not delivered
```

**Comment by edenhill** [comment]
For temporary errors (such as broker down), messages will remain in queue until `message.timeout.ms` has elapsed.
flush() simply waits for messages to be delivered/failed, but does not force them to time out.
If you want to force messages to fail, use rd_kafka_purge().
