### ISSUE TITLE
how to cross compile librdkafka for mips platform?

### ISSUE THREAD

**Issue by george-liang** [edenhill/librdkafka#267]
Hi,
I am not sure if librdkafka is now supporting mips or not. I downloaded the master branch, I want to cross compile it to mips in a X86_64 ubuntu platform.

**Comment by edenhill** [comment]
librdkafka successfully builds under MIPS.
See the debian build logs for example:
https://buildd.debian.org/status/package.php?p=librdkafka&suite=unstable

**Comment by george-liang** [comment]
Cool! But how? I ran following commands
./configure --host=mipsel-linux-uclibc --prefix=my_local_folder --cc=mipsel-linux-uclibc-gcc
make
Several errors accorded, for example:
mipsel-linux-uclibc-gcc -MD -MP -g -O2 -fPIC -Wall -Wfloat-equal -Wpointer-arith  -c rdkafka.c -o rdkafka.o
In file included from rdkafka_int.h:42,
                 from rdkafka.c:39:
rdtime.h: In function `rd_ctime':
rdtime.h:81: error: thread-local storage not supported for this target

the mipsel gcc version is 3.4.2

Is there something missing in ./configure command?

**Comment by edenhill** [comment]
Your toolchain is more than 10 years old, TLS (thread-local storage) support was added to GCC in 2005 from what I understand.
Could you try upgrading your toolchain just a few years? ;)
