### ISSUE TITLE
[Documentation] How to set username and password for plaintext protocol (no SASL) in Conf object ?

### ISSUE THREAD

**Issue by FabienCarmagnac** [edenhill/librdkafka#2671]
Description
===========
Cant figure out though the documentation how to set login/passwd to auth a producer/consumer when security.protocol=plaintext. I tried :
key=user_dev1, value=dev1_ => ERR : No such configuration property: ...

key=username, value=dev1 
key=password, value=dev1_ => ERR : No such configuration property: ...

key=sasl.username, value=dev1  => worked during config, but of course , at runtime ==> ERR :  LOG-4-CONFWARN: [thrd:app]: Configuration property `sasl.username` only applies when `sasl.mechanism` is set to PLAIN or SCRAM-SHA-.

How to reproduce
================
NA (how to problem, not a runtime problem)

Checklist
=========

 - [x] librdkafka version : build with visual 2019 from src 1.3.0, compiled with WITH_SSL=0
 - [x] Apache Kafka version:  2.3.1, running with :

listeners=PLAINTEXT://:9091
security.inter.broker.protocol=PLAINTEXT
listener.security.protocol.map=PLAINTEXT:PLAINTEXT
auto.create.topics.enable=true
auto.leader.rebalance.enable=true

jaas.conf file :

KafkaServer {
	org.apache.kafka.common.security.plain.PlainLoginModule required
	serviceName="kafka"
	username="admin"
	password="admin_pass"
	user_admin="admin__pass"
	user_fabien="fabien_pass"
	user_tepp="tepp_pass"
	user_dev1="dev1_pass"
	user_dev2="dev2_pass"
	user_dev3="dev3_pass"
	user_broker="broker-secret";
};

Jaas file transmitted via :

"%~dp0kafka-run-class.bat" -Djava.security.auth.login.config=jaas.conf kafka.Kafka %*

 - [x] librdkafka client configuration: THIS IS WHAT I AM LOOKING FOR !
security.protocol=plaintext
debug=all
metadata.broker.list=ip:port

 - [x] Operating system: win10 (producer) , win server 2012 (kafka server)
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka NA
 - [ ] Provide broker log excerpts : NA
 - [ ] Critical issue :

**Comment by rnpridgeon** [comment]
JAAS is specific to Java. Please find the following wiki which should help. 

https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka

Let us know if you need further assistance.
