### ISSUE TITLE
Local: Invalid compressed data

### ISSUE THREAD

**Issue by EvgeniyZviryaka** [edenhill/librdkafka#2672]
**Description**
From time to time Kafka Consumer writes error "Local: Invalid compressed data" but I can't find any info in the documentation what this error means and how we can avoid it in production. Am I right that consumer skip message with such error and potentially we can miss some updates? I'm sure that message has correct data as we have a few consumers that read the same topic and error randomly appears on some of them.

**How to reproduce**
The error appears randomly in production don't have any idea how to reproduce it in a controlled environment

Checklist
=========
 - [x] librdkafka version (release number or git tag): 1.3.0
 - [x] .Net Client Confluent Kafka: 1.3.0
 - [ ] librdkafka client configuration: 
            {
                {"group.id", UniqueId},
                {"enable.auto.commit", "true"},
                {"auto.commit.interval.ms", "1000"},
                {"statistics.interval.ms", "1000"},
                {"fetch.wait.max.ms", "50"},
                {"enable.partition.eof", "true"},
                {"api.version.request", "true"},
                {"bootstrap.servers", bootstrapServers},
                {"auto.offset.reset", "earliest"},
                {"request.required.acks", "1"},
            };
 - [x ] Operating system: windows
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Sorry for the slow response.

That error message means the consumer failed to decompress a compressed MessageSet.

What compression codec/type is used for these messages?
What is producing the messages, platform, language and client?
What other consumer is successfully reading those messages? Platform, language and client?

**Comment by zhuboshuai** [comment]
when I produce messages using librdkafka with conf compression.codec = zstd ,  I try to consumer messages using librdkafka , the log always print as below:
"% Consume error for topic "xxx" [14] offset 626: Decompression (codec 0x4) of message at 626 of 495 bytes failed: Local: Invalid compressed data"
what should I do to recorrect it?
the librdkafka version is v1.5.0

**Comment by champtar** [comment]
Sounds like #2951 #2943

**Comment by zhuboshuai** [comment]
> Sounds like #2951 #2943
thanks, I  will pay attention to progress of [facebook/zstd#2222](https://github.com/facebook/zstd/issues/2222)

**Comment by benesch** [comment]
There are now several zstd releases (v1.4.7, v1.4.8) that don't have this bug, so probably safe to close this!

**Comment by mausch** [comment]
I'm getting this after upgrading https://www.nuget.org/packages/Confluent.Kafka/ from 1.6.3 to 1.7.0 (and therefore librdkafka 1.7.0), any ideas?

**Comment by taspeotis** [comment]
If I download the NuGet package and extract `libzstd.dll` its implementation of `ZSTD_versionString` returns `1.3.8`. 

https://github.com/facebook/zstd/issues/2222 is fixed in zstd 1.4.7 or newer.

The NuGet package needs to ship a newer version of zstd by the looks of things, or statically link to a newer version?
