### ISSUE TITLE
Non Blocking Socket

### ISSUE THREAD

**Issue by syedtoah** [edenhill/librdkafka#268]
Hello Edenhill,

I wanted to know if librdkafka support the Non-blocking socket? From what I understood the socket that is created to connect to the broker is a blocking one from the code. Help me if I am wrong. Is there a roadmap for adding non-blocking socket to the lib?

I understand librdkafka handles huge messges/sec, but what if the core is heavily loaded.

Thank you for your reply.

**Comment by edenhill** [comment]
Hi,

librdkafka uses non-blocking sockets for the initial connect() phase of the broker connection, after that it uses polled IO and non-blocking recv/sends.
Each broker has its own thread so the initial blocking connect() does not affect any other part of the library and consumes no CPU resources while waiting for connection.

Are you seeing a specific problem with this, or just curious?

**Comment by syedtoah** [comment]
I was just curious, I saw the following API and didnt see the non blocking flag ""rd_kafka_broker_connect""
