### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by liyongxin** [edenhill/librdkafka#2685]
recently I used fluentd to send logs to kafka, using the rdkafka2 type in fluent-plugin-kafka. Rdkafka2 will use rdkafka-ruby as the client, and rdkafka-ruby will call librdkafka as the actual worker.
I did some tests for performance, but the results were very unsatisfactory.

Description
===========
The producer and kafka server are on the same network, so there is no network delay,
The test loads 400,000 pieces of data from a file, each piece of data is about 500 bytes, the average transmission time of the test results is 35s, and only more than 10,000 pieces of data are processed per second, and I found from the trace log print that most of the time is used for data After processing, it will take very little time to send to Kafka after packaging into a MessageSet. Does anyone have experience in this area, please help

How to reproduce
================
Requires a complete fluentd environment

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<1.2.0 >`
 - [x]  Apache Kafka version: `<2.0.0>`
 - [x] librdkafka client configuration:
 `<"batch.num.messages": 1000000,
"queue.buffering.max.ms": 15000,
"request.required.acks": 1,
"queue.buffering.max.messages":10000000,
"queue.buffering.max.kbytes": 4000000,
"socket.keepalive.enable": true,
"socket.send.buffer.bytes": 0,
"socket.blocking.max.ms": 2,
"message.max.bytes": 1000000000>`
 - [x] Operating system: `<Alpine Linux v3.9>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
https://user-images.githubusercontent.com/7601142/72117955-7d5d6e80-338a-11ea-9bf1-58dc47d64737.png
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by liyongxin** [comment]
This is the log of librdkafka when generating the local message queue. About 10,000 pieces of data are generated every second. My configuration "queue.buffering.max.ms": 15000, so about 144544 pieces of data in 15 seconds. , So I want to know why the data processing takes so long, and the real problem lies
![Uploading 72117955-7d5d6e80-338a-11ea-9bf1-58dc47d64737.png…]()

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#low-latency

**Comment by liyongxin** [comment]
> https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#low-latency
thanks，I have read the description of throughput and low latency, but the current problem is that the data is slow to load into the local queue. From the logs I have screenshots, it is only about 10,000 per second, and the deliverd speed is okay. What are the possible reasons for the speed of data processing?

**Comment by edenhill** [comment]
Time each part of your program separately:
 * how much time is spent reading records from file
 * how much time is spent processing the records
 * how much time is spent in produce()
 * how much time is spent between produce() and the delivery report (see rd_kafka_message_latency() in the delivery report)

You could do this by adding timing calculations to your code, or using a profiler.
