### ISSUE TITLE
How to get the offset of the produced message in a synchronous way?

### ISSUE THREAD

**Issue by nleeuskadi** [edenhill/librdkafka#2689]
Description
===========
For business use-case reason I need to get the offset of a produced message before continuing produce next message : while producing messages asynchronously, regularly I need to keep the offset of a specific produced message. This offset is then put in header of the next following produced messages.

With Java API , I can do it using the synchronous call of producer.send" API. This API returns a Future<RecordMetadata> on which I can call blocking get() method.
Example:
Future<RecordMetadata> result = producer.send(mySpecificMessage);
long synchrooffset =result.get().offset();  //blocking call. Wait for getting the offset (or error in case of failure).
///... then continue to send next messages asynchronously, each containing an header with the offset read above.

How can I implement the same type of mechanism with librdkafka C++ Producer API?

How to reproduce
================
Indeed the API provides the delivery report callback mechanism, but the producer::;produce APi is asynchronous and I can't see how to make the call synchronous with the callback report?

Checklist
=========
 - [x] librdkafka version  : `v1.3.0`
 - [x] Apache Kafka version: `2.3.0`
 - [ ] librdkafka client configuration: No specific configuration
 - [x] Operating system: `Centos 7 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Here's an example how to make synchronous produce calls:
https://github.com/edenhill/librdkafka/wiki/Sync-producer

But make sure to read this:
https://github.com/edenhill/librdkafka/wiki/FAQ#why-is-there-no-sync-produce-interface
