### ISSUE TITLE
How to configure Producer with 'security.protocol'='SASL_SSL' but without a CA

### ISSUE THREAD

**Issue by DrStrangepork** [edenhill/librdkafka#2691]
Description
===========
I am running a Python Producer service in AWS Lambda using the `confluent-kafka` library which makes use of librdkafka, connecting to a kafka service that requires SSL. I have found that the only way I can authenticate to kafka is to include a physical CA PEM file in the 'ssl.ca.location' setting. This is deemed as a security risk, because I'd have to store the PEM file in my repo in order to deploy it with my Lambda code. This feels like I'm missing a better alternative, but in my searches through the documentation, I haven't seen one. Is there a better way to do this?

Checklist
=========
 - [x] librdkafka version (release number or git tag): `confluent-kafka 1.3.0`
 - [x] Apache Kafka version: Confluent 5.1
 - [x] librdkafka client configuration: `acks=1,bootstrap.servers=KAFKA_BROKER,security.protocol=SASL_SSL,sasl.mechanism=SCRAM-SHA-256,sasl.username=SASL_USERNAME,sasl.password=SASL_PASSWORD,ssl.ca.location=<path to CA pem>`
 - [x] Operating system: `Python 3.6`
 - [x] Provide logs: There are no logs; without the CA, `producer.list_topics()` and `producer.flush()` just hang until timeout
 - [x] Provide broker log excerpts: No logs
 - [x] Critical issue: No

**Comment by rolandyoung** [comment]
You only need the public key of the Kafka service's CA at ssl.ca.location. This is not a security risk. However, if the Kafka service in question is using a self-signed CA key as its broker certificate (which **is** a security risk), then you will need to use that PEM file in your deployment. In that case, you will need a separate deployment step to put the file in place.
