### ISSUE TITLE
`make` leaves git tree dirty

### ISSUE THREAD

**Issue by sylr** [edenhill/librdkafka#2692]
Description
===========

Doing a make leaves git tree in dirty state.

I'm using librdkafka as a git submodule and if one submodule is in a dirty state the parent git repo is also considered dirty.

How to reproduce
================

```shell
$ git describe --tags --dirty                                                                                                        
v1.3.0-13-g43b214c7
$ ./configure
...
$ git describe --tags --dirty                                                                                                        
v1.3.0-13-g43b214c7
$ make
...
$ git describe --tags --dirty                                                                                                        
v1.3.0-13-g43b214c7-dirty
$ git status
HEAD detached at 43b214c7
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   CONFIGURATION.md

no changes added to commit (use "git add" and/or "git commit -a")
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Yeah, this is a bit of an annoyance.
We're going to make the CONFIGURATION.md generation unconditional, meaning it will produce the same results regardless of configure/build options.

**Comment by edenhill** [comment]
As a workaround, change your build script to `make && git checkout CONFIGURATION.md`

**Comment by edenhill** [comment]
CONFIGURATION.md now contains all config options, regardless of build options.
