### ISSUE TITLE
Kafka client bind on source interface ip address

### ISSUE THREAD

**Issue by babuveld** [edenhill/librdkafka#2694]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Does Kafka client support for bind on the ip address similar to telnet? This is to have the producer traffic go on a particular source interface. Please let me know.

[e.g] telnet 10.82.227.160 50001 -s 10.1.1.1

https://linux.die.net/man/1/telnet

**Comment by edenhill** [comment]
Not builtin, but you may do so yourself by adding a connect_cb:
https://docs.confluent.io/current/clients/librdkafka/rdkafka_8h.html#a53dd1b77019324170d0168617fdaf040

and calling the relevant setsockopt() on the socket before calling connect()
