### ISSUE TITLE
rdkafka consumer not getting message after some time while message is getting produced and getting in console consumer

### ISSUE THREAD

**Issue by pramodyadav130** [edenhill/librdkafka#2699]
Hello All Genius,

I am new to kafka consumer .

I have  written kakfka consumer code and getting consumed message but after some time not getting messages but when i m checking in apache kafka console consumer message is getting there..I am not getting what I did wrong in  below code....

```javascript
exp.createKafkaConsumerStream = function (topicName, phase, instance, offsetPeriod) {
    console.log("broker:" + conf.get("kafkaBroker"));
    const consumer = new kafka.KafkaConsumer({
        //'debug': 'all',
        'metadata.broker.list': conf.get("kafkaBroker"),
        'client.id': phase + "." + instance,
        'group.id': phase + '.grp',
        'enable.auto.commit': true
    }, {
        'auto.offset.reset': 'latest'
    });

    consumer.on('ready', function (arg) {
        log.info('consumer ready.' + JSON.stringify(arg));
        consumer.subscribe([topicName]);
        console.log("final topic name:" + topicName);
        //start consuming messages
        consumer.consume();
    });


    consumer.on('disconnected', function (arg) {
        log.info('consumer disconnected. ' + JSON.stringify(arg));
    });

    //logging all errors
    consumer.on('event.error', function (err) {
        log.error('Error from consumer', err, 'code: ', err.code);
    });
    //starting the consumer
    consumer.connect();

    consumerReady = new Promise((resolve, reject) => {
        consumer.on('ready', () => {
            log.info('consumer ready');
            resolve(consumer);
        });
    });

    var marks;

    const calcOffsets = (cons) => {
        return new Promise((resolve, reject) => {
            cons.queryWatermarkOffsets(topicName, 0, 10000, function (err, offsets) {
                if (err) {
                    log.error(err);
                }
                resolve(offsets);
            });
        });
    };

    const watermarks = () => {
        return consumerReady.then(calcOffsets);
    };

    var obj = {};
    obj['consumer'] = consumer;
    obj['offsets'] = watermarks;
    return obj;
};
```

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
You seem to be missing an `..on('data', ..)` for actually receiving the consumed messages.
