### ISSUE TITLE
Change in SSL config (key/CA cert) for librdkafka producer

### ISSUE THREAD

**Issue by NaikPrats** [edenhill/librdkafka#2702]
Description
===========
I am using SSL for connecting to kafka client. I am using kafka conf_set APIs to provide ca-cert and keys location and then initializing the producer to start streaming data.

My question is - 
If my CA-cert or keys change , do I have to re instantiate rd_kafka object with these new files ? Or I can use some APIs on my current rd_kafka handle and start using new SSL files?

**Comment by edenhill** [comment]
You will need to create a new rd_kafka_t object, the certs and keys are only loaded on startup.

**Comment by NaikPrats** [comment]
For Kafka SSL, each broker in a cluster will have its own certificate.
 
So on the client side(telemetry) we set following 4 SSL fields using rd_kafka_conf_set() and eventually call rd_kafka_new() API with the list of brokers.
 
Query => We are passing only one CA certificate from telemetry. So will it be validated for all brokers in the broker list by the server? Am not getting this part. Can you please clarify?

**Comment by edenhill** [comment]
The SSL cert/key configuration is per cluster, not per broker.
All broker certificates will need to be verifiable with ssl.ca... and the client cert and key must be accepted by all brokers.
