### ISSUE TITLE
Question on consumer pause and resume: is there any way to find out the current state of the consumer, if it's paused ?

### ISSUE THREAD

**Issue by ajayb0507** [edenhill/librdkafka#2703]
Question on consumer pause and resume: is there any way to find out the current state of the consumer, if it's paused ? We want to avoid unnecessary pause/resume call (and also the assignment() call), if it's already done.

Please provide the following information:

 - [v1.3.0] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There is no way to check the pause state of a partition, so you will need to track this yourself when calling pause() and resume().

Also note that pause() will empty the pre-fetchq (up to 1 GB) of the given partition(s), thus if you do pause/resume repeatedly there will be a lot of extra pre-fetching of messages (if there are messages available in the topic) as they are thrown away.

**Comment by ajayb0507** [comment]
Thanks for your quick response. We basically want to avoid consumer disconnecting after exceeding the max.poll.interval.ms. Alternative to using pause/resume, Is there any downside of having a very high value for this configuration. We are using enable.auto.offset.store=false.

**Comment by edenhill** [comment]
`max.poll.interval.ms` defines how long a consumer  application owns an assigned partition, and its data.
This has two consequences:
 1. it is the upper time bound on per-message processing.
 2. it is the upper time bound for how long a consumer group rebalance might stall.

In other words, long processing times will also lead to long recovery times.
