### ISSUE TITLE
node:lts and node:lts-buster libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ceastman-ibm** [edenhill/librdkafka#2704]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
trying to use node-rdkafka but when starting the node js microservice i get the following:

Error: libssl.so.1.0.0: cannot open shared object file: No such file or directory

I also logged an issue with node-rdkafka but they said it was more a librdkafka issue: https://github.com/Blizzard/node-rdkafka/issues/750

these are the only libssl.so files in the image:
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
/usr/lib/x86_64-linux-gnu/libssl.so.1.1

How to reproduce
================
using a docker image based up node:lts-buster
npm install node-rdkafka@2.7.4 and other dependencies. zip up the node_modules and the source code.

Deploy to a docker image based upon node:lts-buster and start the node app

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version librdkafka-dev is already the newest version (0.11.6-1.1).
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [X] Operating system: `node:lts-buster (debian)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ceastman-ibm** [comment]
the zipped up node modules and deployment has this for ldd:
root@d03c6d82d611:~# ldd /home/node/app/node_modules/node-rdkafka/build/deps/librdkafka.so
	linux-vdso.so.1 (0x00007ffcea4f6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f365bc45000)
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => not found
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f365ba27000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f365ba22000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f365ba01000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f365b9f5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f365b834000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f365c112000)

a fresh install has:
	linux-vdso.so.1 (0x00007ffe7bde9000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1775449000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f17753b7000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f17750ce000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1774eb0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1774eab000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1774e8a000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1774e7e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1774cbd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1775718000)

**Comment by ceastman-ibm** [comment]
I believe i found the issue, zip is not zipping up the softlinks. i found this by switching to gzip:
gzip: ./node_modules/node-rdkafka/build/deps/librdkafka.so: Too many levels of symbolic links

**Comment by monil-panchal** [comment]
@ceastman-ibm thank you for posting this question. I'm facing a similar problem but I'm afraid I couldn't understand the solution. Can you please elaborate on how it was fixed?
