### ISSUE TITLE
Feature request: remove kinit requirement

### ISSUE THREAD

**Issue by mckenzig** [edenhill/librdkafka#2709]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi

this page explains the configuration options for kinit/keytab use with Kerberos.

https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

there are occasions where the Kerberos tickets are initialized and maintained by some external process however and it is not necessary for the library to manage this. It would be good to have the ability to disable the kinit behavior in the library and pickup tickets that are prepared externally.

Thanks! 

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Isn't it sufficient to set the kinit cmd to a no-op command like "true"?

**Comment by mckenzig** [comment]
That seems to work thanks
