### ISSUE TITLE
librdkafka win-x64 deleted as malware by Bitdefender

### ISSUE THREAD

**Issue by jblagorce** [edenhill/librdkafka#2712]
Description
===========

Since this morning Bitdefender deletes librdkafka.dll 1.3.0 win-x64, considering it a malware.
I spent some time today trying to resolve the issue. I first thought it was a nuget or Visual studio issue, until I finally figured it out when unzipping the package in a test folder and saw the lib magically disappear.

Translation of the bitdefender message is :
"Analysis has detected a threat. The file has been deleted"
"...\librdkafka.dll is a malware of type Gen:Variant.Ursu.757318"

I also downloaded the 1.3.0 package from the nuget site to ensure that my package source was not corrupted, and encountered the same issue.

This does not affect the 1.3.0 win-x86 dll, nor 1.4.0-RC1 dlls

Bitdefender version is 6.6.16.218
Bitdefender Engine version is 7.83783

================
Checklist
=========

 - [x] librdkafka version 1.3.0
 - [ ] Apache Kafka version: `not relevant`
 - [ ] librdkafka client configuration: `not relevant`
 - [x] Operating system: `win 10 x64`
 - [x] Provide logs see capture (in french, sorry)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

![image](https://user-images.githubusercontent.com/3418504/74442295-89e55300-4e71-11ea-9180-6641399acfa8.png)

**Comment by edenhill** [comment]
I'm not sure what to do with this, suggestions?

**Comment by jblagorce** [comment]
As I am checking today if the problem still persists, it seems to have gone away with the latest updates of Bitdefender.

Thanks for your time.
