### ISSUE TITLE
Please build C code

### ISSUE THREAD

**Issue by drewwells** [edenhill/librdkafka#2715]
It's possible to build C code with packages written in Go. This package should be packaging librbkafka to ensure compatibility and reliability of tools built on top of it like `prometheus-kafka-adapter`. For an example, check out sqlite https://github.com/mattn/go-sqlite3. This package is widely used because it works out of the box. This project requires importing special confluent only libraries which makes it hard to use.

Description
===========
```
-> % go get github.com/Telefonica/prometheus-kafka-adapter                                                                         dev-6
go: downloading github.com/konsorten/go-windows-terminal-sequences v0.0.0-20180402223658-b729f2633dfe
go: finding github.com/json-iterator/go v1.1.9
go: downloading github.com/json-iterator/go v1.1.9
go: extracting github.com/json-iterator/go v1.1.9
go: extracting github.com/konsorten/go-windows-terminal-sequences v0.0.0-20180402223658-b729f2633dfe
go: downloading github.com/modern-go/reflect2 v0.0.0-20180701023420-4b7aa43c6742
go: downloading github.com/modern-go/concurrent v0.0.0-20180228061459-e0a39a4cb421
go: extracting github.com/modern-go/concurrent v0.0.0-20180228061459-e0a39a4cb421
go: extracting github.com/modern-go/reflect2 v0.0.0-20180701023420-4b7aa43c6742
# pkg-config --cflags  -- rdkafka
Package rdkafka was not found in the pkg-config search path.
Perhaps you should add the directory containing `rdkafka.pc'
to the PKG_CONFIG_PATH environment variable
No package 'rdkafka' found
pkg-config: exit status 1
```

How to reproduce
================
Build any package dependent on this one.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `master`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `should not be a requirement`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I'm not really sure what the question is here, but I'm guessing the external dependency on librdkafka.
We're going to include librdkafka pre-built with the confluent-kafka-go client end of Q1, early Q2 this year.
