### ISSUE TITLE
question: logger and opaque data type

### ISSUE THREAD

**Issue by edsiper** [edenhill/librdkafka#2717]
Description
===========

I need to pass an opaque data type to the logger callback function ```rd_kafka_conf_set_log_cb()```, pretty much as is supported by ```rd_kafka_conf_set_dr_msg_cb```. Is there any option ?

The context I want to pass is unique for the rdkafka main context.

what would be the suggestion?

**Comment by edsiper** [comment]
cc: @edenhill

**Comment by edenhill** [comment]
You can retrieve the rd_kafka_t's opaque value with `rd_kafka_opaque(rk)` in the log_cb.

**Comment by edsiper** [comment]
thanks
