### ISSUE TITLE
documentation issue for `broker.version.fallback` property

### ISSUE THREAD

**Issue by Eliyahu-Machluf** [edenhill/librdkafka#2719]
The default value of `broker.version.fallback`
at the page https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#broker-version-compatibility
it is `0.9.0.0`
while at configuration.md  https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
it is `0.10.0`
Please fix one of the pages to the correct default.
Thanks.
Eliyahu

**Comment by edenhill** [comment]
Thank you, will fix 👍
