### ISSUE TITLE
Unable to find an entry point named 'rd_kafka_producev' in shared library 'librdkafka'

### ISSUE THREAD

**Issue by chalcrow** [edenhill/librdkafka#2720]
Description
===========
I'm working on a .NET Core application that uses the Nuget package - Confluent.Kafka, Version 0.11.3

I'm using it to instantiate a `Producer`, then calling the `myProducer.ProduceAsync` method. I get an error in the application logs stating - `Unable to find an entry point named 'rd_kafka_producev' in shared library 'librdkafka'`.

The docker container that's my .NET Core app runs in has `librdkafka1 - v0.9.3-1` installed. I needed to manually install it in the container as part of the Docker image, using:

`RUN apt-get update -y`
`RUN apt-get install -y librdkafka-dev`

I don't understand why I needed to install it manually anyway - this was to fix an error where the library wasn't being found at all. Shouldn't it already exist on the image? I'm using the standard `wurstmeister/kafka` Docker  image.

Everything is working on a different server, where the exact same Confluent.Kafka package version is being used, and the exact same `librdkafka1` is installed. Any ideas on how to fix this?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<librdkafka1 - 0.9.3-1>`
 - [x] Apache Kafka version: `Confluent.Kafka, Version 0.11.3`
 - [x] librdkafka client configuration: `(bootstrap.servers = brokerList, retries = 2)`
 - [x] Operating system: `Debian v9`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by chalcrow** [comment]
0


I removed this from the Docker file:

RUN apt-get update -y RUN apt-get install -y librdkafka-dev

Then, deleted librdkafka1 from the Debian container running my application. Redeployed my application to the container and now it works - I don't get any error that `librdkafka` isn't found. The strange thing is, librdkafka1 now doesn't exist as a package on the container, so I'm unclear as to whether librdkafka1 even needs to be installed as an explicit dependency or whether the nuget package somehow encompasses it.

**Comment by edenhill** [comment]
confluent-kafka-dotnet depends on the librdkafka.redist nuget package which contains librdkafka, so you typically don't have to manually install librdkafka on the system (there are some cases where you might, such as when using GSSAPI).
