### ISSUE TITLE
Does librdkafka supports TLS v1_2 ?

### ISSUE THREAD

**Issue by ajayb0507** [edenhill/librdkafka#2723]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We have setup SASL_SSL on one of the kafka server. When we run the following command, it works fine only for tls1_2.

openssl s_client -connect 10.0.0.103:9094 -tls1
openssl s_client -connect 10.0.0.103:9094 -tls1_1
openssl s_client -connect 10.0.0.103:9094 -tls1_2

Librdkafka however reports SSL handshake failure. 

"sasl_ssl://ckafka:9094/bootstrap: SSL handshake failed: s3_clnt.c:1264: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:  (after 8ms in state CONNECT)"

So does librdkafka support v1_2, or is there any configuration to turn on to ensure it uses tls1_2. Below are the configuration we are using. We know that we are not passing any ca, but it seems to work fine on another machine which supports all TLS v1/1_1/1_2. Probably ca isn't required for sasl_ssl PLAIN ?

security.protocol : sasl_ssl
sasl.mechanism : PLAIN
sasl.username  : XXXXXX
sasl.password  : XXXXXX

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [X] librdkafka version (release number or git tag): `1.3.0
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by deejgregor** [comment]
See https://github.com/edenhill/librdkafka/issues/1680#issuecomment-364921002 and lines 1050-1060 here: https://github.com/edenhill/librdkafka/blob/869186bf997ab29689557cf74fdc4ec4862479b9/src/rdkafka_ssl.c#L1050

It looks like the only thing that is done is disabling SSLv3, and there is no configurability for other TLS protocol versions. The flags that can be passed to disable various protocol versions is in https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_new.html -- search for SSL_OP_NO_.

**Comment by edenhill** [comment]
I believe you can control which TLS version is used by setting ssl.cipher.suites accordingly, see https://www.openssl.org/docs/man1.1.0/man1/ciphers.html

**Comment by edenhill** [comment]
A CA cert to verify the broker's certificate is required by default, you can disable broker cert verification by setting `enable.ssl.certificate.verification=false`, but this should only be done for troubleshooting, not in production.

**Comment by ajayb0507** [comment]
That's very strange. We have a Confluent managed Kafka, and they say they have sasl_ssl enabled. In-fact we are using librdkafka to connect to the server using the configuration mentioned in initial description, no certificate. How is that possible ? Is there any similar configuration on the server end which may relax the client from sending the ca-cert, or any other plugin perhaps.
We are trying to setup a similar server as Confluent (to compare NFR), not getting a lot of help in this regard from them.

**Comment by edenhill** [comment]
The client will use the system's ca-certs by default.
