### ISSUE TITLE
Init producer throws segmentation fault while connection to ssl  on node-rdkafka wrapper

### ISSUE THREAD

**Issue by Denusdv** [edenhill/librdkafka#2726]
Description
===========
We have the following setup

MSK on AWK with TLS enabled connectivity
OpenSSL 1.0.2k-fips  26 Jan 2017
Node v12.13.1
node-rdkafka:2.7.4

Here is the Kafka.Producer init code

     ```
        this.kproducer = new Kafka.Producer({
                    'metadata.broker.list': this.producers.toString(),
                    'message.send.max.retries': 10,
                    'debug': 'broker,security',
                    'security.protocol': 'ssl',
                    'ssl.key.location': 'kafka_ssl/ssl.key',
                    'ssl.ca.location': 'kafka_ssl/ssl.ca',
                    'ssl.certificate.location': 'kafka_ssl/ssl.cert',
                    'socket.keepalive.enable': true,
                    'dr_cb': true,
                    'event_cb': true
                });
      ```

To setup the client

1 .the ssl.cert I got from 
openssl s_client -debug -connect .....amazonaws.com:9094

2. the ssl.key I got from 
openssl s_client -connect .....amazonaws.com:9094 | openssl x509 -pubkey -noout

The ssl.ca is the root Amazon CA was downloaded from the official AWS trust repository 

here is my logs including segfault-handler logs.

info: Kafka.features gzip,snappy,**ssl**,sasl,regex,lz4,sasl_plain,sasl_scram,plugins,sasl_oauthbearer

info: connecting to {"metadata.broker.list":"b-2.airlytics-dev1.6beykp.c4.kafka.eu-west-1.amazonaws.com:9094,b-1.airlytics-dev1.6beykp.c4.kafka.eu-west-1.amazonaws.com:9094","message.send.max.retries":10,"debug":"broker,security","security.protocol":"ssl","ssl.key.location":"kafka_ssl/server.key","ssl.ca.location":"kafka_ssl/ssl.ca","ssl.certificate.location":"kafka_ssl/server.cert","socket.keepalive.enable":true}
PID 24987 received SIGSEGV for address: 0x0
/home/ec2-user/stable/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x2ba0)[0x7f79c6388ba0]
/lib64/libpthread.so.0(+0x117e0)[0x7f79dd9337e0]
/lib64/libssl.so.10(ssl_cert_set0_chain+0x8)[0x7f79d42905a8]
/lib64/libssl.so.10(ssl3_ctx_ctrl+0x3cb)[0x7f79d427273b]
node(SSL_CTX_use_certificate_chain_file+0x12e)[0x142fe4e]
/home/ec2-user/stable/node_modules/node-rdkafka/build/Release/../deps/librdkafka.so.1(+0xb843e)[0x7f79d457243e]
/home/ec2-user/stable/node_modules/node-rdkafka/build/Release/../deps/librdkafka.so.1(rd_kafka_new+0x92a)[0x7f79d44d2dfa]
/home/ec2-user/stable/node_modules/node-rdkafka/build/Release/../deps/librdkafka++.so.1(_ZN7RdKafka8Producer6createEPNS_4ConfERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xda)[0x7f79dc11bcea]
/home/ec2-user/stable/node_modules/node-rdkafka/build/Release/node-librdkafka.node(_ZN9NodeKafka8Producer7ConnectEv+0x5e)[0x7f79dc35b61e]
/home/ec2-user/stable/node_modules/node-rdkafka/build/Release/node-librdkafka.node(_ZN9NodeKafka7Workers15ProducerConnect7ExecuteEv+0x27)[0x7f79dc360957]
/home/ec2-user/stable/node_modules/node-rdkafka/build/Release/node-librdkafka.node(_ZN3Nan12AsyncExecuteEP9uv_work_s+0x2d)[0x7f79dc34f9cd]
node[0x12d1c0e]
/lib64/libpthread.so.0(+0x740b)[0x7f79dd92940b]
/lib64/libc.so.6(clone+0x3f)[0x7f79dd663e7f]
Segmentation fault

Since I don't see any debug in the stdout, that's the only thing I get. not clear if that's env or parameters problem, pls assist to figure it out.

Thanks

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.2.2`
 - [x] Apache Kafka version: `MSK on AWS`
 - [x] librdkafka client configuration: ` 'metadata.broker.list': thisproducers.toString(),
                    'message.send.max.retries': 10,
                    'debug': 'broker,security',
                    'security.protocol': 'ssl',
                    'ssl.key.location': 'kafka_ssl/server.key',
                    'ssl.ca.location': 'kafka_ssl/ssl.ca',
                    'ssl.certificate.location': 'kafka_ssl/server.cert',
                    'socket.keepalive.enable': true,
                    'dr_cb': true,
                    'event_cb': true`
 - [x] Operating system: `centos rhel fedora`
 - [x] Provide logs (with `debug=..` as necessary) don't see any debug although 'debug': 'broker,security', is set

**Comment by edenhill** [comment]
This might due to ABI incompatibilities in different versions or builds of openssl/libssl, i.e., if you are building your application on one machine and then running it on another it is imperative that the openssl versions are identical.
