### ISSUE TITLE
Producer ACK offset order

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#2729]
Hi Magnus, tell me please is there a guarantee that the delivery reports all have the partition offsets in strict consecutive order?

What i mean by this:
1. Producer sends messages to the same partition. Assume only one process ever writes.
2. Say 5 messages are sent and arrive at the broker in some unknown order. I do not care what order they arrive in.
3. When polling for acks, will the partition offset in the delivery report for the messages be (assume sends started at offset 99):
   100,101,102,103,104 in that exact consecutive order? Or is it possible for the application to first detect that a message was written at offset 102 and after that that some other message was written at offset 100?

**Comment by edenhill** [comment]
Delivery reports are enqueued in the same order as the ProduceResponses from the broker, so they should be in monotonic offset order, but I'm not sure I would rely on that fact going forward, it is not a semantic that neither the broker or client guarantees, thus might change.

**Comment by MaximGurschi** [comment]
Understood, thank you!
