### ISSUE TITLE
segmentation fault calling KafkaConsumer->query_watermark_offsets()

### ISSUE THREAD

**Issue by jdye64** [edenhill/librdkafka#2730]
Description
===========
I am receiving segmentation faults when invoking `query_watermark_offsets()` on a `KafkaConsumer` object instance. GDB is showing me this occurring when an attempt is made to set ```*low = state.offsets[0];``` in rdkafka.c#3182. However GDB also shows me that ```state.offsets[0]``` has a valid value of 0 so this confuses me?

How to reproduce
================
I have validated my issue exists in the latest librdkafka 1.3.0 release. I am creating a "KafkaConsumer" object with a global configuration (configs dump provided below). After creation I am assigning the KafkaConsumer with a Partition and start offset of 0. I am sure those values exist. I then attempt to get the watermark offsets and the segmentation fault occurs. Below is a snippet of that code.

```
// consumer_ is the KafkaConsumer object instance.

int64_t *low;
int64_t *high;
std::vector<RdKafka::TopicPartition *> topic_parts;

err_ = consumer_->assignment(topic_parts);
if (err_ != RdKafka::ErrorCode::ERR_NO_ERROR) {
  printf("Error: '%s'\n", err2str(err_).c_str());
}
// prints 1, this is a single topic and single partition
printf("# Consumer Partition(s) -> '%lu'\n", topic_parts.size()); 
printf("Topic: '%s' Partition: '%d'\n", topic_parts[0]->topic().c_str(), topic_parts[0]->partition());

// Segmentation fault is occurring here
err_ = consumer_->query_watermark_offsets(topic_parts[0]->topic().c_str(), topic_parts[0]->partition(), low, high, 10000);
```

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.3.0
 - [x] Apache Kafka version: 2.3.0
 - [x] librdkafka client configuration: 
'builtin.features' = 'gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer'
'client.id' = 'rdkafka'
'metadata.broker.list' = 'localhost:9092'
'message.max.bytes' = '1000000'
'message.copy.max.bytes' = '65535'
'receive.message.max.bytes' = '100000000'
'max.in.flight.requests.per.connection' = '1000000'
'metadata.request.timeout.ms' = '60000'
'topic.metadata.refresh.interval.ms' = '300000'
'metadata.max.age.ms' = '900000'
'topic.metadata.refresh.fast.interval.ms' = '250'
'topic.metadata.refresh.fast.cnt' = '10'
'topic.metadata.refresh.sparse' = 'true'
'debug' = ''
'socket.timeout.ms' = '60000'
'socket.blocking.max.ms' = '1000'
'socket.send.buffer.bytes' = '0'
'socket.receive.buffer.bytes' = '0'
'socket.keepalive.enable' = 'false'
'socket.nagle.disable' = 'false'
'socket.max.fails' = '1'
'broker.address.ttl' = '1000'
'broker.address.family' = 'any'
'enable.sparse.connections' = 'true'
'reconnect.backoff.jitter.ms' = '0'
'reconnect.backoff.ms' = '100'
'reconnect.backoff.max.ms' = '10000'
'statistics.interval.ms' = '0'
'enabled_events' = '0'
'error_cb' = '0x7ffff738f590'
'throttle_cb' = '0x7ffff738f180'
'stats_cb' = '0x7ffff738f2d0'
'log_cb' = '0x7ffff738f8b0'
'log_level' = '6'
'log.queue' = 'false'
'log.thread.name' = 'true'
'log.connection.close' = 'true'
'socket_cb' = '0x7ffff6a30670'
'open_cb' = '0x7ffff6a4d330'
'opaque' = '0x5555557f2888'
'default_topic_conf' = '0x5555557f2660'
'internal.termination.signal' = '0'
'api.version.request' = 'true'
'api.version.request.timeout.ms' = '10000'
'api.version.fallback.ms' = '0'
'broker.version.fallback' = '0.10.0'
'security.protocol' = 'plaintext'
'enable.ssl.certificate.verification' = 'true'
'ssl.endpoint.identification.algorithm' = 'none'
'sasl.mechanisms' = 'GSSAPI'
'sasl.kerberos.service.name' = 'kafka'
'sasl.kerberos.principal' = 'kafkaclient'
'sasl.kerberos.kinit.cmd' = 'kinit -R -t "%{sasl.kerberos.keytab}" -k %{sasl.kerberos.principal} || kinit -t "%{sasl.kerberos.keytab}" -k %{sasl.kerberos.principal}'
'sasl.kerberos.min.time.before.relogin' = '60000'
'enable.sasl.oauthbearer.unsecure.jwt' = 'false'
'test.mock.num.brokers' = '0'
'group.id' = 'test_group_id'
'partition.assignment.strategy' = 'range,roundrobin'
'session.timeout.ms' = '10000'
'heartbeat.interval.ms' = '3000'
'group.protocol.type' = 'consumer'
'coordinator.query.interval.ms' = '600000'
'max.poll.interval.ms' = '300000'
'enable.auto.commit' = 'true'
'auto.commit.interval.ms' = '5000'
'enable.auto.offset.store' = 'true'
'queued.min.messages' = '100000'
'queued.max.messages.kbytes' = '1048576'
'fetch.wait.max.ms' = '100'
'fetch.message.max.bytes' = '1048576'
'fetch.max.bytes' = '52428800'
'fetch.min.bytes' = '1'
'fetch.error.backoff.ms' = '500'
'offset.store.method' = 'broker'
'isolation.level' = 'read_committed'
'rebalance_cb' = '0x7ffff73901a0'
'enable.partition.eof' = 'true'
'check.crcs' = 'false'
'client.rack' = ''
'enable.idempotence' = 'false'
'enable.gapless.guarantee' = 'false'
'queue.buffering.max.messages' = '100000'
'queue.buffering.max.kbytes' = '1048576'
'queue.buffering.max.ms' = '0.5'
'message.send.max.retries' = '2'
'retry.backoff.ms' = '100'
'queue.buffering.backpressure.threshold' = '1'
'compression.codec' = 'none'
'batch.num.messages' = '10000'
'delivery.report.only.error' = 'false'
 - [x] Operating system: Ubuntu 18.04
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jdye64** [comment]
Any advice on this would be greatly appreciated.

**Comment by rolandyoung** [comment]
It appears that you are passing uninitialised pointers in `low` and `high`. 
Instead of 
```
int64_t *low;
int64_t *high;
/* ... */
err_ = consumer_->query_watermark_offsets(topic_parts[0]->topic().c_str(), topic_parts[0]->partition(), low, high, 10000);
```
I think you need to write
```
int64_t low;
int64_t high;
/* ... */
err_ = consumer_->query_watermark_offsets(topic_parts[0]->topic().c_str(), topic_parts[0]->partition(), &low, &high, 10000);
```

**Comment by jdye64** [comment]
@rolandyoung thank you. I knew better than this. I couldn't see the forest for the trees as they say. Thanks again for the extra set of eyes!
