### ISSUE TITLE
missing nuget package for v141 toolset in VS 2017

### ISSUE THREAD

**Issue by lolotp** [edenhill/librdkafka#2731]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
https://github.com/edenhill/librdkafka/wiki/FAQ
This is essentially the same issue [here](https://github.com/edenhill/librdkafka/issues/2112). When  building with Visual Studio, even after we've downloaded and installed the nuget packages configured in `win32/packages.config`, we'd still fail to build the project because it's looking for zlib.v141.* which is not available. As for where the v141 comes from, the configuration in the *.vcxproj file indicate that the zlib package whould be `zlib.$(PlatformToolset)` which expands into 141 in this case (presumably this is tied to the version of Visual Studio being used). It looks like the best fix for this would somehow publishing a new zlib nuget built with this toolset?

How to reproduce
================
Open the solution file in visual studio 2017 and tries to build it (see related issues for details: https://github.com/edenhill/librdkafka/issues/2112).

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `c8fd8e682bb79e756920176b34051f18e7c8c006`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `Windows 10 64-bit`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by VadimShtukan** [comment]
In VS2019 $(PlatformToolset)=142, which still missing in nuget.
_error : This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\zlib.**v142**.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\zlib.**v142**.windesktop.msvcstl.dyn.rt-dyn.targets._

**Comment by fquinsol** [comment]
Indeed the Nuget package for Toolset v142 is not available. However I consider the main issue to be that common.vcxproj ties the Toolset to the version of VisualStudio. It is quite common to keep moving  to the latest version of the IDE while keeping older toolsets.

**Comment by edenhill** [comment]
We're now using vcpkg for dependencies instead of nuget, so this is no longer an issue.
