### ISSUE TITLE
Question: query_watermark_offsets visibility

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#2734]
Hello Magnus,

Hopefully another trivial question.
Assume some toppar that is never truncated. I use the broker round trip API to get query_watermark_offsets:

1. If at time T one process sees the value X from querying "query_watermark_offsets" (for some toppar), can i assume that any other process will also see X if they query after T?

2. And in a more advanced scenario:
If at time T a producer gets ack for offset X, can i assume that any other process will also see X if they query query_watermark_offsets  after T?

3. Similar to 2, if a consumer consumed offset X at time T, can i assume that any other process will also see X if they query query_watermark_offsets  after T?

**Comment by MaximGurschi** [comment]
Sorry Magnus, are you able to comment?

I'm building a system relying on certain "visibility" aspects of query_watermark_offsets.
It is important to know the guarantees of this function. Are you able to comment on the above questions?

**Comment by MaximGurschi** [comment]
Closing as have not heard feedback.

**Comment by edenhill** [comment]
Sorry for missing this one.

To answer your questions:
 1 and 3: Since query_watermark_offsets() queries the current partition leader for the watermark offsets it should give the same result on two different clients, given that no new messages are produced to the partition.
 2. Unless you are using transactions on the topic, yes. (see `isolation.level`)

**Comment by MaximGurschi** [comment]
Thanks Magnus,

For 1, 3 i think there is a race condition possible, where the node that thinks it is the leader is not the leader in fact. Is there a very small fraction of time where this is possible? I looked at the Kafka's scala code and it aligns with what you say - the leader is queried. But i was not 100% sure if there is a race condition where the node thinks wrongly that it is the leader.
