### ISSUE TITLE
If the client is created with empty string/null brokers, librdkafka gets stuck silently, reporting "Cluster connection already in progress" 

### ISSUE THREAD

**Issue by sershe-ms** [edenhill/librdkafka#2737]
Description
===========
The synopsis is that 1.2.2 librdkafka reports "already connecting" when there's no indication connection was ever attempted, and gets forever stuck in consume. Logs are below.

The longer version is that we use librdkafka/C# Confluent.Kafka; we just create a config, then create a thread that calls Subscribe and Consume. Recently after moving some code around (as far as I can tell so far, all the calls into Confluent.Kafka, consumer config, etc. are the same), librdkafka gets stuck and never connects to a broker. The issue is easy to repro by just replacing one of our dlls to before/after, but strangely this works fine for other services using the same dll, so I'm not sure how to provide a repro.
One thing that definitely changed is the order/timing of class creation (like configs and where producers/consumers are created) so I wonder if library loading somehow affects this. I'm trying to narrow it down now, however given that I see subscribe and consume calls in both cases this seems like some init bug. 

The logs have a difference in that I can see "broker:port/bootstrap" lines before refactoring, but not after. Then, in before it tries to connect:

```
[thrd:app]: Group "CG": updating member id "(not-set)" -> "",MEMBERID"
[thrd:app]: GroupCoordinator: Enabled low-latency ops queue wake-ups,WAKEUPFD"
[thrd:app]: GroupCoordinator: Added new broker with NodeId -1,BROKER"
[thrd:GroupCoordinator]: GroupCoordinator: Enter main broker thread,BRKMAIN"
[thrd::0/internal]: :0/internal: Enter main broker thread,BRKMAIN"
[thrd:app]: broker:port/bootstrap: Enabled low-latency ops queue wake-ups,WAKEUPFD"
[thrd:app]: broker:port/bootstrap: Added new broker with NodeId -1,BROKER"
[thrd:app]: librdkafka v1.2.2 (0x10202ff) ...#consumer-2 initialized (builtin.features gzip.snappy.ssl.sasl.regex.lz4.sasl_gssapi.sasl_plain.sasl_scram.plugins.zstd.sasl_oauthbearer. SSL ZLIB SNAPPY SASL_SCRAM PLUGINS HDRHISTOGRAM. debug 0xffff),INIT"
[thrd:broker:port/bootstrap]: broker:port/bootstrap: Enter main broker thread,BRKMAIN"
Before calling Subsribe
[thrd:main]: Group "CG" received op SUBSCRIBE (v0) in state init (join state init. v1 vs 0),CGRPOP"
[thrd:main]: Group "CG": subscribe to new subscription of 1 topics (join state init),SUBSCRIBE"
[thrd:main]: Group "CG": unsubscribe from current unset subscription of 0 topics (leave group=no. join state init. v1),UNSUBSCRIBE"
[thrd:main]: Group "CG": resetting group leader info: unsubscribe,GRPLEADER"
[thrd:main]: Group "CG" is rebalancing in state init (join-state init) without assignment: unsubscribe,REBALANCE"
[thrd:main]: Group "CG" changed join state init -> wait-unassign (v1. state init),CGRPJOINSTATE"
[thrd:main]: Group "CG": unassign done in state init (join state wait-unassign): without new assignment: unassign (no previous assignment),UNASSIGN"
[thrd:main]: Group "CG" changed join state wait-unassign -> init (v1. state init),CGRPJOINSTATE"
[thrd:main]: Group "CG" changed state init -> query-coord (v1. join-state init),CGRPSTATE"
[thrd:main]: Broadcasting state change,BROADCAST"
[thrd:main]: broker:port/bootstrap: Selected for cluster connection: coordinator query (broker has 0 connection attempt(s)),CONNECT"
[thrd:main]: Group "CG": no broker available for coordinator query: intervaled in state query-coord,CGRPQUERY"
[thrd:broker:port/bootstrap]: broker:port/bootstrap: Received CONNECT op,CONNECT"
```
Proceeds fine after this.

After:
```
[thrd:app]: Group "CG": updating member id "(not-set)" -> "",MEMBERID"
[thrd:app]: GroupCoordinator: Enabled low-latency ops queue wake-ups,WAKEUPFD"
[thrd:app]: GroupCoordinator: Added new broker with NodeId -1,BROKER"
[thrd:GroupCoordinator]: GroupCoordinator: Enter main broker thread,BRKMAIN"
[thrd:app]: librdkafka v1.2.2 (0x10202ff) ...#consumer-2 initialized (builtin.features gzip.snappy.ssl.sasl.regex.lz4.sasl_gssapi.sasl_plain.sasl_scram.plugins.zstd.sasl_oauthbearer. SSL ZLIB SNAPPY SASL_SCRAM PLUGINS HDRHISTOGRAM. debug 0xffff),INIT"
[thrd::0/internal]: :0/internal: Enter main broker thread,BRKMAIN"
Before calling Subsribe
[thrd:main]: Group "CG" received op SUBSCRIBE (v0) in state init (join state init. v1 vs 0),CGRPOP"
[thrd:main]: Group "CG": subscribe to new subscription of 1 topics (join state init),SUBSCRIBE"
[thrd:main]: Group "CG": unsubscribe from current unset subscription of 0 topics (leave group=no. join state init. v1),UNSUBSCRIBE"
[thrd:main]: Group "CG": resetting group leader info: unsubscribe,GRPLEADER"
[thrd:main]: Group "CG" is rebalancing in state init (join-state init) without assignment: unsubscribe,REBALANCE"
[thrd:main]: Group "CG" changed join state init -> wait-unassign (v1. state init),CGRPJOINSTATE"
[thrd:main]: Group "CG": unassign done in state init (join state wait-unassign): without new assignment: unassign (no previous assignment),UNASSIGN"
[thrd:main]: Group "CG" changed join state wait-unassign -> init (v1. state init),CGRPJOINSTATE"
[thrd:main]: Group "CG" changed state init -> query-coord (v1. join-state init),CGRPSTATE"
[thrd:main]: Broadcasting state change,BROADCAST"
[thrd:main]: Cluster connection already in progress: coordinator query,CONNECT"
[thrd:main]: Group "CG": no broker available for coordinator query: intervaled in state query-coord,CGRPQUERY"
Subscribe call returned
[thrd:main]: Group "CG" received op GET_ASSIGNMENT (v0) in state query-coord (join state init. v1 vs 0),CGRPOP"
[thrd:main]: Group "CG" received op GET_ASSIGNMENT (v0) in state query-coord (join state init. v1 vs 0),CGRPOP"
[thrd:main]: Cluster connection already in progress: coordinator query,CONNECT"
[thrd:main]: Group "CG": no broker available for coordinator query: intervaled in state query-coord,CGRPQUERY"
[thrd:main]: Not selecting any broker for cluster connection: still suppressed for 34ms: no cluster connection,CONNECT"
```
These messages are repeated infinitely after that.
Note that it says "Cluster connection already in progress:" even though there's no indication of a connection of any kind.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.2.2
 - [x] Apache Kafka version: 2.3
 - [x] librdkafka client configuration (Confluent.Kafka): 
                bootstrap servers, group id, client id. 
                EnableAutoOffsetStore = false, 
                EnableAutoCommit = false,
                AutoOffsetReset = Earliest
                Debug = all
 - [x] Operating system: Windows sever
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by sershe-ms** [comment]
Turns out the changes combined how some library users init config caused brokers list to not be read correctly, and an empty list was passed at some point. It's surprising that this is not checked though and instead results in the above symptoms.

**Comment by edenhill** [comment]
The reason `bootstrap.servers` is not required is that brokers may be added manually after creating the client instance by calling `rd_kafka_brokers_add()`, we need to maintain this for backwards compatibility with existing applications.

But we should emit a warning log if no brokers are configured.

**Comment by sershe-ms** [comment]
"Cluster connection already in progress" also seems like a wrong long message to emit, since it's not. I am not sure if it's just the message, or actually means library is in the bad state. I guess one could say the connection to 0 brokers is in progress waiting for broker addition :)

**Comment by edenhill** [comment]
The client now logs if there are no bootstrap.servers configured (to the dismay of the few brokers_add() users):
```
$ ../examples/producer "" test
%5|1588765418.398|CONFWARN|rdkafka#producer-1| [thrd:app]: No `bootstrap.servers` configured: client will not be able to connect to Kafka cluster
```
