### ISSUE TITLE
why don't support special path for SASL and GSSAPI lib?

### ISSUE THREAD

**Issue by beyond-wyc** [edenhill/librdkafka#2738]
only support /usr/lib64 path of SASL and GSSAPI now.

https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka

**Comment by edenhill** [comment]
The library linking path is dependent on your build configuration  (through pkg-config, etc) and target system, it is not something librdkafka dictates.

You can troubleshoot this further by `ldd librdkafka.so.1` and `LD_LIBRARY_PATH=/alternate/path/to/libs ./yourprogram`
