### ISSUE TITLE
Specifying custom library paths for linux build

### ISSUE THREAD

**Issue by JSoet** [edenhill/librdkafka#2740]
Description
===========
I'm trying to build librdkafka on linux - I would only like to build the static library, and I would like to use my own downloaded versions of some of the libraries instead of the system libraries (specifically zstd and openssl)... 

I tried to configure the build using `LIBS="/path/to/libs" CFLAGS="/path/to/includes" ./configure` but it seems that this didn't work:
- first off, the CFLAGS argument didn't get written to the `Makefile.config` file (I also tried with `./configure CFLAGS=...` but that also didn't work). 
- second, the LIBS were just concatenated to the end of the existing LIBS argument, so it complained about symbols being declared twice. 

Anyway, I was able to fix the issues by just manually editing the `Makefile.config` file before running `make` but I had a couple questions based on that:

- Is there a supported way to replace the LIBS and CFLAGS other than just doing what I did and editing the `Makefile.config`?
- Is it possible to only build the static library? (This isn't really important, but then I wouldn't have to worry about updating the LIBS parameter, so I was just curious)

Checklist
=========

 - [x] librdkafka version (release number or git tag): `v1.3.0`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `RHEL 7`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
1. 
`CFLAGS=.. ./configure` and `./configure --CFLAGS=..` (note, not `./configure CFLAGS..`) works for me:
```bash
$ CFLAGS="-Wno-common" ./configure | grep no-common ; grep -H no-common Makefile.config
  CFLAGS                   -Wno-common      
Makefile.config:CFLAGS+=	-Wno-common      
```

2. re LIBS=, seems to work as expected, it appends the specified libs to the end of the linker list, I'm not seeing any duplicates unless the linked libraries are picked up by configure, but in that case you should use LDFLAGS to instruct configure to find your libs elsewhere.   LIBS=.. is for adding additional libraries that configure does not find.
