### ISSUE TITLE
Install generated `rdkafka.pc`

### ISSUE THREAD

**Issue by alexott** [edenhill/librdkafka#275]
Right now, the `rdkafka.pc` file for `pkg-config` is generated, but not installed by default.  Installing it can make use of the `librdkafka` easier for developers

**Comment by remicollet** [comment]
+1

**Comment by edenhill** [comment]
Good idea.
The question is where? In a portable manner

**Comment by remicollet** [comment]
I dont know how the "configure" was created, bu autotool use "pkgconfig_DATA" 

$(libdir)/pkgconfig seems portable (used in some other project)

**Comment by alexott** [comment]
pkg-config's documentation mentions that it by default searches in `/usr/lib/pkgconfig` and `/usr/share/pkgconfig`, so we can explicitly specify `$(libdir)/pkgconfig`.  But if automake supports `pkg-config` directly via `pkgconfig_DATA`, then it's better to use it...

**Comment by edenhill** [comment]
This is fixed in master.
Two separate .pc files are generated, one for the C library and one for the C++ library.
They are installed to $(libdir)/pkgconfig as suggested above.

**Comment by PetrusJPrinsloo** [comment]
This does not seem to be working in Fedora 26. I am now trying to get the `rdkafka.pc` file that is generated and can't find it.

**Comment by edenhill** [comment]
@PetrusJPrinsloo Check where rdkafka.pc is being installed and make sure that matches the path where pkg-config is looking (look for the default PKG_CONFIG_PATH in `man pkg-config`)

**Comment by PetrusJPrinsloo** [comment]
Hi edenhill, thanks for the response!
There doesn't seem to be a `rdkafka.pc` in `/usr/share/pkgconfig` where fedora looks for them. Is there a way I can generate the file and add it there? I found an older version of the file for 0.8 and put it in that directory then I get a different error:

error while loading shared libraries: librdkafka.so.1: cannot open shared object file: No such file or directory

I'm assuming I need to add some directories to this file manually or regenerate the file somehow.

**Comment by remicollet** [comment]
@PetrusJPrinsloo perhaps you should try the package available in my [repository](https://rpms.remirepo.net/)

```
$ rpm -ql librdkafka-devel  | grep pc
/usr/lib64/pkgconfig/rdkafka++.pc
/usr/lib64/pkgconfig/rdkafka.pc
```

**Comment by PetrusJPrinsloo** [comment]
hi @remicollet, I downloaded and ran the version for fedora 26. My output for `rpm -ql librdkafka-devel  | grep pc` is blank. Those files aren't in that directory though.

    $ ls /usr/lib64/pkgconfig/
    fontutil.pc  libelf.pc  zlib.pc

**Comment by remicollet** [comment]
> I downloaded and ran the version for fedora 26.

Which package have you download ?  Should be there, perhaps you pull the i686 package instead of the x86_64 one ?

**Comment by PetrusJPrinsloo** [comment]
I downloaded this one: https://rpms.remirepo.net/fedora/remi-release-26.rpm

**Comment by remicollet** [comment]
This is the repository configuration package.... then you obviously need to 
`dnf install --enablerepo=remi install librdkafka-devel`

**Comment by PetrusJPrinsloo** [comment]
Oh, my bad! I'm new to Fedora coming from the Debian side of things. Will try that and see. Thanks.

**Comment by PetrusJPrinsloo** [comment]
That worked! Thanks a lot!
