### ISSUE TITLE
librdkafka hostname ip address change connection

### ISSUE THREAD

**Issue by babuveld** [edenhill/librdkafka#2751]
Description
===========
Does the librdkafka takes care of case where broker list is configured with hostnames and the ip address of a hostname changes. For this case, does librdkafka internally handles reconnecting with new ip address [or] the API user need to disconnect and reconnect with the hostname?

**Comment by edenhill** [comment]
librdkafka will re-resolve the broker hostname on each connection attemption (but no more often than `broker.address.ttl` (default 1s)), but it will not actively disconnect from a broker because its DNS entry changed.
