### ISSUE TITLE
Statistics - Event Hubs - Duplicate partition keys under a single topic

### ISSUE THREAD

**Issue by Progdom** [edenhill/librdkafka#2755]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We are experiencing an issue where we are getting duplicate partition keys in our statistics. We are using the `rd_kafka_conf_set_stats_cb` config callback. Are partition keys supposed to be unique or should we be handling this case? Our deserializers are not happy with JSON objects having duplicate keys and are blowing up.

The duplicates are 2,10,21,28,20 :

`
"topics":{
"requests":{
"topic":"requests",
"metadata_age":288587,
"batchsize":{
"min":885,
"max":885,
"avg":885,
"sum":885,
"stddev":0,
"p50":887,
"p75":887,
"p90":887,
"p95":887,
"p99":887,
"p99_99":887,
"outofrange":0,
"hdrsize":14448,
"cnt":1
},
"batchcnt":{
"min":1,
"max":1,
"avg":1,
"sum":1,
"stddev":0,
"p50":1,
"p75":1,
"p90":1,
"p95":1,
"p99":1,
"p99_99":1,
"outofrange":0,
"hdrsize":8304,
"cnt":1
},
"partitions":{
"0":{
"partition":0,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"1":{
"partition":1,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"2":{
"partition":2,
"leader":0,
"desired":true,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"active",
"query_offset":-1,
"next_offset":1491,
"app_offset":1491,
"stored_offset":1491,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":1490,
"lo_offset":0,
"hi_offset":1490,
"consumer_lag":0,
"txmsgs":0,
"txbytes":0,
"rxmsgs":1486,
"rxbytes":1324988,
"msgs":1486,
"rx_ver_drops":2,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"3":{
"partition":3,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"4":{
"partition":4,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"5":{
"partition":5,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"6":{
"partition":6,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"7":{
"partition":7,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"8":{
"partition":8,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"9":{
"partition":9,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":1,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"10":{
"partition":10,
"leader":0,
"desired":true,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"active",
"query_offset":-1001,
"next_offset":1364,
"app_offset":1364,
"stored_offset":1364,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":1363,
"lo_offset":1,
"hi_offset":1363,
"consumer_lag":0,
"txmsgs":0,
"txbytes":0,
"rxmsgs":1357,
"rxbytes":1210608,
"msgs":1357,
"rx_ver_drops":2,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"11":{
"partition":11,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":1,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"12":{
"partition":12,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"13":{
"partition":13,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"14":{
"partition":14,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":1,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"15":{
"partition":15,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"16":{
"partition":16,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"17":{
"partition":17,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"18":{
"partition":18,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"19":{
"partition":19,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"20":{
"partition":20,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":1,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"21":{
"partition":21,
"leader":0,
"desired":true,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"active",
"query_offset":-1001,
"next_offset":1409,
"app_offset":1409,
"stored_offset":1409,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":1408,
"lo_offset":0,
"hi_offset":1408,
"consumer_lag":0,
"txmsgs":0,
"txbytes":0,
"rxmsgs":1400,
"rxbytes":1249950,
"msgs":1400,
"rx_ver_drops":2,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"22":{
"partition":22,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"23":{
"partition":23,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"24":{
"partition":24,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":1,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"25":{
"partition":25,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"26":{
"partition":26,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":0,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"27":{
"partition":27,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":1,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"28":{
"partition":28,
"leader":0,
"desired":true,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"active",
"query_offset":-1001,
"next_offset":1511,
"app_offset":1511,
"stored_offset":1511,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":1510,
"lo_offset":1,
"hi_offset":1510,
"consumer_lag":0,
"txmsgs":0,
"txbytes":0,
"rxmsgs":1503,
"rxbytes":1340451,
"msgs":1503,
"rx_ver_drops":2,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"29":{
"partition":29,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":1,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"30":{
"partition":30,
"leader":0,
"desired":true,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"active",
"query_offset":-1,
"next_offset":1486,
"app_offset":1486,
"stored_offset":1486,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":1485,
"lo_offset":0,
"hi_offset":1485,
"consumer_lag":0,
"txmsgs":0,
"txbytes":0,
"rxmsgs":1486,
"rxbytes":1324475,
"msgs":1486,
"rx_ver_drops":2,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"31":{
"partition":31,
"leader":0,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":1,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"2":{
"partition":2,
"leader":0,
"desired":true,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"active",
"query_offset":-1,
"next_offset":1491,
"app_offset":1491,
"stored_offset":1491,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":1490,
"lo_offset":0,
"hi_offset":1490,
"consumer_lag":0,
"txmsgs":0,
"txbytes":0,
"rxmsgs":1486,
"rxbytes":1324988,
"msgs":1486,
"rx_ver_drops":2,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"10":{
"partition":10,
"leader":0,
"desired":true,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"active",
"query_offset":-1001,
"next_offset":1364,
"app_offset":1364,
"stored_offset":1364,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":1363,
"lo_offset":1,
"hi_offset":1363,
"consumer_lag":0,
"txmsgs":0,
"txbytes":0,
"rxmsgs":1357,
"rxbytes":1210608,
"msgs":1357,
"rx_ver_drops":2,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"21":{
"partition":21,
"leader":0,
"desired":true,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"active",
"query_offset":-1001,
"next_offset":1409,
"app_offset":1409,
"stored_offset":1409,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":1408,
"lo_offset":0,
"hi_offset":1408,
"consumer_lag":0,
"txmsgs":0,
"txbytes":0,
"rxmsgs":1400,
"rxbytes":1249950,
"msgs":1400,
"rx_ver_drops":2,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"28":{
"partition":28,
"leader":0,
"desired":true,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"active",
"query_offset":-1001,
"next_offset":1511,
"app_offset":1511,
"stored_offset":1511,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":1510,
"lo_offset":1,
"hi_offset":1510,
"consumer_lag":0,
"txmsgs":0,
"txbytes":0,
"rxmsgs":1503,
"rxbytes":1340451,
"msgs":1503,
"rx_ver_drops":2,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"30":{
"partition":30,
"leader":0,
"desired":true,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"active",
"query_offset":-1,
"next_offset":1486,
"app_offset":1486,
"stored_offset":1486,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":1485,
"lo_offset":0,
"hi_offset":1485,
"consumer_lag":0,
"txmsgs":0,
"txbytes":0,
"rxmsgs":1486,
"rxbytes":1324475,
"msgs":1486,
"rx_ver_drops":2,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
},
"-1":{
"partition":-1,
"leader":-1,
"desired":false,
"unknown":false,
"msgq_cnt":0,
"msgq_bytes":0,
"xmit_msgq_cnt":0,
"xmit_msgq_bytes":0,
"fetchq_cnt":0,
"fetchq_size":0,
"fetch_state":"none",
"query_offset":-1001,
"next_offset":0,
"app_offset":-1001,
"stored_offset":-1001,
"commited_offset":-1001,
"committed_offset":-1001,
"eof_offset":-1001,
"lo_offset":-1001,
"hi_offset":-1001,
"consumer_lag":-1,
"txmsgs":0,
"txbytes":0,
"rxmsgs":0,
"rxbytes":0,
"msgs":0,
"rx_ver_drops":0,
"msgs_inflight":0,
"next_ack_seq":0,
"next_err_seq":0,
"acked_msgid":0
}
`

How to reproduce
================
This is a bit difficult to repro as it requires .NET wrapper that calls out to the librdkafka.dll which connects to an azure event hub.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.1.0
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration: 
 - [x] Operating system: windows 10
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Interesting, never seen this before.

Did the number of partitions change for this topic during the runtime of the client?

**Comment by Progdom** [comment]
Actually, we figured this out and it's not on librdkafka. We were incorrectly setting partitions when partitions changed around (Forgetting to remove the old ones). You can consider this closed.

**Comment by Progdom** [comment]
I'm curious if librdkafka should protect against duplicate json keys in this situation. What do you think @edenhill ?

**Comment by edenhill** [comment]
Can you elaborate on how you were incorrectly setting partitions?
librdkafka shouldn't add duplicate partitions in the internal partition cache.
