### ISSUE TITLE
Error SSL Handshake Failed - certificate verify failed

### ISSUE THREAD

**Issue by JSoet** [edenhill/librdkafka#2758]
Just writing this down for later users, because google seems quite good at bringing up these issues when searching, so I figured it's a good resource for someone else who runs into the same issue.

I was running librdkafka with the ssl setting, and it was working for me when following the instructions at https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

But I was trying to build these settings into my application, and found that if I didn't set the `ssl.ca.location` then it would fail to connect with the message:
```
%3|1583954693.318|ERROR|rdkafka#producer-2| [thrd:ssl://localhost:9092/bootstrap]: ssl://localhost:9092/bootstrap: SSL handshake failed: ssl\statem\statem_clnt.c:1915: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:  (after 6ms in state CONNECT)
```

However I thought that it should be possible to connect without verifying the certificate, and eventually I noticed the setting `enable.ssl.certificate.verification` which by default is set to `true`. When setting it to `false` then it's possible to leave the `ssl.ca.location` setting unset and not receive the above message.

I will also just mention here in the hope that it might be useful to someone, that the instructions laid out in the [using ssl with librdkafka](https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka) document are instructions for doing ***[authentication](https://docs.confluent.io/current/kafka/authentication_ssl.html)*** in addition to ***[encryption](https://docs.confluent.io/current/kafka/encryption.html#kafka-ssl-encryption)***. If you just want to do encryption (and the `ssl.client.auth` setting is set to `none` on the broker) then it's possible to not specify the key and certificate, and only set the `security.protocol` setting to `ssl` in order to use ssl encryption over the wire.

**Comment by edenhill** [comment]
Thanks for sharing your knowledge with the community! 💯 

Just want to point out that disabling broker certificate verification (enable.ssl.certificate.verification=false) is a dangerous thing since it allows for man-in-the-middle attacks, broker impersonations, etc. This should only be done in completely trusted development environments.

**Comment by JSoet** [comment]
Yes, thanks for pointing that out, that's a good point, but in our app it is already an existing setting for other connections that we have, so is expected for the kafka interface as well, and that's why I was testing that that worked... but obviously as you mentioned it should not generally be used...

**Comment by rogeralsing** [comment]
I'm at complete loss over this one.
We are using the .NET Confluence driver for Kafka, which uses librdkafka internally.

Now to my confusion. 
When I run this in Linux, it works fine, I don't have to install any certs or anything, it just works.
Anyone else on the team, can run this on Mac, it just works, nothing special installed.
When I run on Mac, I get this above error.

I can disable ssl verification, then it works.

But for us devs that are not literate in the world of certificates, what would be the cause of this?
Why is is that it works out of the box for most cases?

**Comment by edenhill** [comment]
OSX keeps its certs in a certificate/key store, which librdkafka (through OpenSSL) does not access.
librdkafka needs the certificates on disk (or provided with set_ssl_cert() as memory blobs).

If you install OpenSSL through homebrew I think it typically extracts the CA certs into file, so maybe that's what your colleagues have done.
Alternatively you can grab the CA certs from curl (https://curl.haxx.se/docs/caextract.html) and use `SslCaLocation` to pioint the client to where they reside.
