### ISSUE TITLE
connection with broker not using FQDN when running with SSL

### ISSUE THREAD

**Issue by benp20** [edenhill/librdkafka#2759]
Description
===========
I am trying to run connect and send messages to a kafka broker using rd_kafka_simple_producer with SSL enabled.
The application is failing because after successful initial handshake, it is connecting to the just the hostname part of the broker instead of the full FQDN. This causes host resolution to fail.
Wondering if this is an issue with librdkafka library whereby seems to use only the hostname for resolution and not the FQDN,

Alternatively, is the name of the "new" broker the application is to connect to after the SSL handshake being returned by kafka broker side wherein what is being returned is not the FQDN?
I tried to research if there is a configuration setting that lists the addresses of brokers being returned by the kafka broker side. But I did not find anything relevant (I am using confluent kafka).

Any guidance is appreciated!

How to reproduce
================
Run rdkafka_simple_producer with SSL enabled and connect to a broker using FQDN.
Eg:
**rdkafka_simple_producer dhcp-172-17-170-60.mydomain.com test1**

Relevant logs:
===========
## Initial connection establishment is succesful including SSL handshake:
%7|1583993798.511|STATE|rdkafka#producer-1| [thrd:ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap]: ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1583993798.513|CONNECT|rdkafka#producer-1| [thrd:ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap]: ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap: Connecting to ipv4#172.17.170.60:9093 (ssl) with socket 9
%7|1583993798.513|CONNECT|rdkafka#producer-1| [thrd:ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap]: ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap: Connected to ipv4#172.17.170.60:9093
%7|1583993798.536|SSLVERIFY|rdkafka#producer-1| [thrd:ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap]: ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap: Broker SSL certificate verified

## New broker added:
%7|1583993798.537|FEATURE|rdkafka#producer-1| [thrd:ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap]: ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD,UnitTest
%7|1583993798.537|STATE|rdkafka#producer-1| [thrd:ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap]: ssl://dhcp-172-17-170-60.mydomain.com:9093/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1583993798.538|BROKER|rdkafka#producer-1| [thrd:main]: ssl://dhcp-172-17-170-60:9093/0: Added new broker with NodeId 0

Note that the new broker added is not in FQDN format, but just the host name.

## Connection to new broker fails since host resolution fails
% Enqueued message (3 bytes) for topic test1
%7|1583993864.853|TOPPAR|rdkafka#producer-1| [thrd:ssl://dhcp-172-17-170-60:9093/0]: ssl://dhcp-172-17-170-60:9093/0: test1 [0] 1 message(s) queued but broker not up
%7|1583993864.853|STATE|rdkafka#producer-1| [thrd:ssl://dhcp-172-17-170-60:9093/0]: ssl://dhcp-172-17-170-60:9093/0: Broker changed state INIT -> TRY_CONNECT
%7|1583993864.853|CONNECT|rdkafka#producer-1| [thrd:ssl://dhcp-172-17-170-60:9093/0]: ssl://dhcp-172-17-170-60:9093/0: broker in state TRY_CONNECT connecting
%7|1583993864.853|STATE|rdkafka#producer-1| [thrd:ssl://dhcp-172-17-170-60:9093/0]: ssl://dhcp-172-17-170-60:9093/0: Broker changed state TRY_CONNECT -> CONNECT
%7|1583993864.855|BROKERFAIL|rdkafka#producer-1| [thrd:ssl://dhcp-172-17-170-60:9093/0]: ssl://dhcp-172-17-170-60:9093/0: failed: err: Local: Host resolution failure: (errno: Bad address)

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): bd71c96b3d8eb7c5f7e85f94fe33f75302167b80
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: 
security.protocol=ssl;ssl.ca.location=/home/temp/certs/ca-cert;ssl.certificate.location=/home/temp/certs/cert.pem;ssl.key.location=/home/temp/certs/private_key.pem
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>: Ubuntu
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Sounds like your broker's `advertised.listener` configuration is incorrect, these are the hosts/addresses that the client will connect to after having connected to the bootstrap servers.

You can see the advertised addresses by `examples/rdkafka_example -b A.Bootstrap.Server -L` ( or `kafkacat -b A.Bootstrap.Server -L`)
