### ISSUE TITLE
multiple threads consumer AND cpp logger examples required

### ISSUE THREAD

**Issue by FantasyJXF** [edenhill/librdkafka#2760]
Description
===========

Hope to release example codes for multiple threads consumer AND cpp logger

Thanks

=========

 - [x] librdkafka version (1.3.0)
 - [ ] Apache Kafka version: 0.8.2
 - [ ] librdkafka client configuration: default
 - [ ] Operating system: CentOS 7.6
 - [ ] Provide logs (with `debug=""` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
See https://github.com/edenhill/librdkafka/blob/master/tests/0056-balanced_group_mt.c for how to use consumer queues to direct partitions to separate threads. It is in C but the C++ API is similar.

As for logging, see https://github.com/edenhill/librdkafka/blob/master/tests/0058-log.cpp

**Comment by FantasyJXF** [comment]
Thanks for the rapid reply
