### ISSUE TITLE
Question: Producer Usage in multiple Threads

### ISSUE THREAD

**Issue by KevDi** [edenhill/librdkafka#2764]
Description
===========
I'm using multiple Threads in my application and all of them should send data to one Kafka Topic.
Now my Question is should they all share one Producer or should every thread hold it's own Producer? Are there any recommendations for that?

Checklist
=========

 - [x] librdkafka version (release number or git tag): `v1.3.0`
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The recommendation is to reuse a single producer.
The producer is thread safe.
