### ISSUE TITLE
librdkafka prefers libc regex over bundled regex, breaking lookaheads

### ISSUE THREAD

**Issue by jrgp** [edenhill/librdkafka#2769]
Description
========

I'd like to be able to use negative lookaheads within the topic blacklist regex.

I looked into the librdkafka source, and it seems the header-only regex library that is bundled (from https://github.com/ccxvii/minilibs ) supports negative lookaheads (see [0]) , but during the build process, librdkafka first checks if libc's regex support exists and uses that instead of the built-in regex engine if it does.

This is unfortunate as the minilibs regex library has many more features than the GNU libc regex library (as it strives to emulate Javascript's regex), and it'd be great if there was a ./configure flag or similar to explicitly choose one regex implementation over the other. 

How to reproduce
=============

When using a pattern that contains a negative lookahead, the regex parser fails with: `Invalid preceding regular expression` which looks to be bubbled up from gnu libc [1]

I've verified the regex I'm using successfully works with more modern regex engines like the one that comes with python:

```
'^service-(?!name-actioner|.+broker|.+federator)'
```

[0] https://github.com/edenhill/librdkafka/blob/master/src/regexp.c#L106
[1] https://github.com/coreutils/gnulib/blob/master/lib/regcomp.c#L174

Checklist
=======

 - [x] librdkafka version 1.0.0 by way of confluent-kafka-go version 1.0.0
 - [x] Operating system: RHEL 7
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I don't have strong confidence in the bundled regexp implementation (not that there is anything wrong with it, but it is a small personal side projects (80 stars) and not really battle tested afaik), it is a fallback for platforms (windows) where there is no builtin regexp engine.

We could make a build-option to use the builtin regex, e.g., `--disable-libc-regex`, but you would have to build your own librdkafka for that since we don't want to make it the defult.

Another alternative would perhaps be to support pcre, but that adds yet another optional dependency, and would be an opt-in.

**Comment by jrgp** [comment]
Hey, thanks for getting back to me. An opt-in option at librdkafka's build time to disable libc's regex would work great for my use case, as I'm already building librdkafka from source.

**Comment by ret394** [comment]
>  projects (80 stars)

if you didn't check the source code,  Matthew Effect is a social phenomenon to blame.

I only trust projects that have promising source code. Or it could be to "star projects quickly then forget about them" gang. Trusting the majority could be riskier than trusting a 

https://github.com/ccxvii/minilibs/issues/3 is good to start.

**Comment by Iaraaa** [comment]
@Louaneee_ok instagram😂❤

**Comment by talmachani** [comment]
Hey, 
this use case can also be viable for me 
was wondering if there is any progress with this?

If this requires changes in the build, specifically with CMake perhaps I can contribute, I have some experience with CMake.

Thanks!

**Comment by edenhill** [comment]
There's now a `./configure --disable-regex-ext` flag to use the internal regex engine.
