### ISSUE TITLE
build error with gcc 5

### ISSUE THREAD

**Issue by remicollet** [edenhill/librdkafka#277]
rdlog.c: In function 'rd_hexdump':
     rdlog.c:39:6: error: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Werror=strict-overflow]
      void rd_hexdump (FILE *fp, const char *name, const void *ptr, size_t len) {
           ^
     cc1: all warnings being treated as errors

**Comment by edenhill** [comment]
Thanks for reporting this, should be fixed now.
