### ISSUE TITLE
Producer does not Queue the messages in case of brokers not connected.

### ISSUE THREAD

**Issue by syedtoah** [edenhill/librdkafka#2770]
Description
===========
Hello Edenhill,

My prod system takes time to connect to the broker/cluster and in the mean time there are other processes that are already generating data. And during this time (I have pasted the logs with debug set to all and debug level set to 7). 
I cannot see anywhere in the documentation if we have to set a property for the library to start saving the messages in case of the broker connection is not active or is there any?
Can you take a look at it and let me know what am I missing here.

Thanks

How to reproduce
================
delay the connection from the broker to the producer on the first connect. 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.11.6
 - [x] Apache Kafka version: 2.11.5
 - [x] librdkafka client configuration: `statistics.interval.ms = 0
queue.buffering.max.messages = 600000
queue.buffering.max.ms = 5
socket.timeout.ms = 10000
socket.max.fails = 0
socket.send.buffer.bytes = 20971520
message.send.max.retries = 500
retry.backoff.ms = 500
debug = all

produce.offset.report = true
message.timeout.ms=310000`
 - [x] Operating system: `ubuntu`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
```
Msg recvt from client
Producer logs:
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic v_Events partition count is zero: should refresh metadata.
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic S_Report partition count is zero: should refresh metadata.
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic v_MessageStream partition count is zero: should refresh metadata.
Level:7 - METADATA - rdkafka#producer-1: [thrd:main]: Skipping metadata refresh of 3 topic(s): no usable brokers.
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic v_Events partition count is zero: should refresh metadata.
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic S_Report partition count is zero: should refresh metadata.
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic v_MessageStream partition count is zero: should refresh metadata.
Level:7 - METADATA - rdkafka#producer-1: [thrd:main]: Skipping metadata refresh of 3 topic(s): no usable brokers.
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic v_Events partition count is zero: should refresh metadata.
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic S_Report partition count is zero: should refresh metadata.
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic v_MessageStream partition count is zero: should refresh metadata.
Level:7 - METADATA - rdkafka#producer-1: [thrd:main]: Skipping metadata refresh of 3 topic(s): no usable brokers.
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic v_Events partition count is zero: should refresh metadata.
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic S_Report partition count is zero: should refresh metadata.
Level:7 - NOINFO - rdkafka#producer-1: [thrd:main]: Topic v_MessageStream partition count is zero: should refresh metadata.

Once the connection is established I get this

Level:7 - TOPPAR - rdkafka#producer-1: [thrd:10.0.8.57:9092/bootstrap]: 10.0.8.57:9092/1: v_Events [0] 2 message(s) in xmit queue (2 added 
Level:7 - TOPPAR - rdkafka#producer-1: [thrd:10.0.8.57:9092/bootstrap]: 10.0.8.57:9092/1: v_Events [0] 2 message(s) in xmit queue (0 added 
Level:7 - TOPPAR - rdkafka#producer-1: [thrd:10.0.8.57:9092/bootstrap]: 10.0.8.57:9092/1: v_Events [0] 2 message(s) in xmit queue (0 added 
Level:7 - PRODUCE - rdkafka#producer-1: [thrd:10.0.8.57:9092/bootstrap]: 10.0.8.57:9092/1: v_Events [0]: Produce MessageSet with 2 message(s) 
Level:7 - SEND - rdkafka#producer-1: [thrd:10.0.8.57:9092/bootstrap]: 10.0.8.57:9092/1: Sent ProduceRequest (v2, 314 bytes @ 0, CorrId 89).

```
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That is not correct, the producer will queue messages on the Unassigned partition queue until the partition count is known, at which point it will partition the messages to the available partitions.

**Comment by syedtoah** [comment]
From the logs though, I am trying to write to 3 different topics and the messages are not being queued. Anything I am missing?

**Comment by edenhill** [comment]
Are you specifying the partition when you produce or relying on the partitioner?

**Comment by syedtoah** [comment]
RD_KAFKA_PARTITION_UA is the partition I am using.

```
if (rd_kafka_produce(rkt, partition, RD_KAFKA_MSG_F_COPY, buf, len, mac, macLen, 0) == -1)
{
}
else
{
}

```

**Comment by edenhill** [comment]
UA is the unassigned partition which means the partitioner will be used, and the partitioner can't run until the partition count is known, so until the client manages to connect the messages are enqueued on the UA partition queue, when a connection is made and the partition count is known the messages will be partitioned across the available partitions.

**Comment by syedtoah** [comment]
So there is no way that the librdkafka will Queue the messages when the partition count is not known?
Is the onus on the calling APP to save those messages?

**Comment by syedtoah** [comment]
Edenhill,

I tried with partition count 1 too, coz that is the one we are using in our testing. The result is the same.
Do you have any suggestions?

**Comment by edenhill** [comment]
To be clear, unless produce() returns an error, the message will be enqueued for (later) transmission when the leader broker is available.

If you are saying that this is not the case, what are you basing this on?
Your log excerpt shows two messages being sent to the broker.

**Comment by syedtoah** [comment]
There were some issues on my code base that I have solved, but I will have to dig deep into this with the idempotent producer attributes. We are on a rather old kafka and librdkafka builds. I will close this for now and will revert back with more information. Thanks for your time.
