### ISSUE TITLE
Client aborted due to "msetw->msetw_ApiVersion >= min_ApiVersion".

### ISSUE THREAD

**Issue by lxyscls** [edenhill/librdkafka#2772]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have upgraded librdkafka to v1.0.0 on a MIPS environment. Then my clients can't work due to abort. The dump stack is as below.

```
(gdb) bt
#0  0x2b2e7ba0 in *__GI_raise (sig=30018) at ../nptl/sysdeps/unix/sysv/linux/raise.c:46
#1  0x2b2e9558 in *__GI_abort () at lowlevellock.h:129
#2  0x2b2df658 in *__GI___assert_fail (assertion=0x101b92c8 "msetw->msetw_ApiVersion >= min_ApiVersion", 
    file=0x101b8e80 "rdkafka_msgset_writer.c", line=201, function=0x101b9480 "rd_kafka_msgset_writer_select_MsgVersion")
    at assert.c:69
#3  0x10149584 in rd_kafka_msgset_create_ProduceRequest (rkb=0x316f3708, rktp=0x38f010c0, rkmq=0x38f01150, pid=
      {id = -1, epoch = -1}, MessageSetSizep=0x356fcb50) at rdkafka_msgset_writer.c:201
#4  0x10113fb8 in rd_kafka_ProduceRequest (rkb=0x7507, rktp=0x38f01150, pid={id = -1, epoch = -1}) at rdkafka_request.c:2718
#5  0x100ee1d4 in rd_kafka_broker_serve (rkb=0x316f3708, timeout_ms=<value optimized out>) at rdkafka_broker.c:3397
#6  0x100ef628 in rd_kafka_broker_thread_main (arg=<value optimized out>) at rdkafka_broker.c:4386
#7  0x2b413d38 in start_thread (arg=<value optimized out>) at pthread_create.c:263
```

The **msetw->msetw_ApiVersion == -1**.

Btw, v0.11.3 and v0.11.6 work well on such environment.

How to reproduce
================
Everytime.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v1.0.0
 - [x] Apache Kafka version: 0.10.2.1
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That's been fixed.
Upgrade to 1.3.0
