### ISSUE TITLE
Consume hangs with Kafka Broker 2.4

### ISSUE THREAD

**Issue by devgig** [edenhill/librdkafka#2774]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I am doing the basic Consume with both version of 1.3 and 1.4 RC using the  Confluent Wrapper of your library.  This is the basic Consume example.   

How to reproduce
================
Run the basic consume example from Confluent. 

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [x] Apache Kafka version: 2.4`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: 
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
We use AK 2.4 for our integration tests and weve seen no such problems.

You need to provide more information, e.g., by setting `debug` to `broker,consumer` and provide debug logs.
