### ISSUE TITLE
librdkafka 0.11.5 on centos 7 producer creation fails when ssl enabled

### ISSUE THREAD

**Issue by srikarn** [edenhill/librdkafka#2776]
Description
===========
Kafka client producer creation fails with error message 
SSLv23_client_method() failed: ssl/ssl_lib.c:2592: error:140A90A1:SSL routines:SSL_CTX_new:library has no ciphers
SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1383:

openssl version: OpenSSL 1.0.2k-fips  26 Jan 2017

The broker supports TLS 1.2.

How to reproduce
================
centos 7 docker image, with librdkafka-devel installed, create producer

 - librdkafka version 0.11.5
 - librdkafka client configuration: security.protocol=SSL
 - Operating system: Cent OS 7 docker image

**Comment by edenhill** [comment]
My guess would be that your build of OpenSSL lacks support of the ciphers used by the broker.

`SSL routines:SSL_CTX_set_cipher_list:no cipher match:ssl_lib.c:1383:`

You can use `openssl s_client ..` to troubleshoot this by letting it connect to the broker.

**Comment by srikarn** [comment]
The ciphers are present, the openssl s_client ssl handshake is successful.

**Comment by srikarn** [comment]
@edenhill, I feel that this is a mismatched dependency issue, the ssl works fine with

openssl s_client -connect <URL> -tls1_2

the broker supports tls 1.2

**Comment by edenhill** [comment]
Verify that librdkafka and openssl are using the same libssl by comparing:
`ldd opensl | grep ssl` to `ldd path/to/librdkafka.so.1 | grep ssl`
