### ISSUE TITLE
rd_kafka_produce behaviour

### ISSUE THREAD

**Issue by silviucpp** [edenhill/librdkafka#2777]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

Hello,

I'm using librdkafka in combination with a local queue where I push messages in case the kafka is down for a long time and the librdkafka in memory queue get full.

Code looks like:

```
if (rd_kafka_produce(topic_, RD_KAFKA_PARTITION_UA, RD_KAFKA_MSG_F_COPY, (void*)value.data(), value.size(), key.data(), key.size(), NULL) != 0)
{
    auto last_error = rd_kafka_last_error();

    if(last_error != RD_KAFKA_RESP_ERR__QUEUE_FULL)
    {
        LOG(SWITCH_LOG_ERROR, "KafkaProducer::produce -> failed with: %s\n", rd_kafka_err2str(last_error));
        return false;
    }

    return local_storage_->push(key, value);
}
```

Time to time I'm checking the local storage to see if any message there and send them back to kafka and remove from local storage if response it's not a failure.

1. It's my assumption correct that once `rd_kafka_produce` doesn't return an error the message is queued and sent to the broker once comes online even if this takes hours?

2. In case I receive a delivery report callback for a message which indicates that delivery failed this implicitly means that the message was removed from librdkafka queue because delivery failed ? Or the message will still there and will be retried till will be successfully delivered ?

For example last time on the delivery report when during a load test all kafka brokers were out of space I received "Message delivery failed Local: Message timed out"

Kind regards,
Silviu

Checklist
=========

Please provide the following information:

 - [8681f884020e880a4c6cda3cfc672f0669e1f38e] librdkafka version
 - [ 1.1.1] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [Ubuntu ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by silviucpp** [comment]
I found myself the answer

**Comment by firefeifei** [comment]
> I found myself the answer

Hello, how did you solve it？
