### ISSUE TITLE
Question: Is it possible to send the same messages to two different KAFKA broker?

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#2779]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Hello friends,
   Can you please answer my query?

Description
===========
There are completely two different setups of Kafka brokers. Here zookeepers and topics are also different.
Is it possible to send the same messages to both brokers(with separate zookeepers) using the same producer?
please note that we are using only a single **rd_kafka_t** handle.

Please suggest an alternate solution if possible.

Thanks
JD

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.1.1`
 - [X] Apache Kafka version: `1.1.1`
 - [X] Operating system: `Linux Os`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That is not possible, a single `rd_kafka_t` instance must only communicate with a single cluster at the time.

Communicating with multiple clusters will not be supported.
