### ISSUE TITLE
topic isn't set in the rkmessage in delivery report callbacks

### ISSUE THREAD

**Issue by lehenbauer** [edenhill/librdkafka#278]
In librdkafka if you register for a delivery report callback using *rd_kafka_conf_set_dr_msg_cb()*, the callback gets called with an *rd_kafka_message_t *rkmessage*, but within that message structure the *rd_kafka_topic_t *rkt* topic pointer is NULL and the key is NULL even if a key was specified.

The partition, payload, payload length, and offset are all there.

Since the delivery report callback is set against the *rd_kafka_conf_t* configuration then if someone is producing to multiple topics then in the callback I believe they will be unable to distinguish which topic the callback is about unless they can figure it out from the payload, which is kind of problematic.

In our case we want to produce to a topic and occasionally produce a clock-and-offset message to an index topic.  We need the callback to determine the relationship between a clock and its offset.  It would also be helpful for us if the key was also in the rkmessage passed to the callback.

If it's too heavyweight to include/reference an entire *rd_kafka_topic_t* in the rkmessage, a *char ** of the topic name would be fine.

**Comment by lehenbauer** [comment]
I have since realized I can get what I need using the opaque pointer.

**Comment by edenhill** [comment]
There is already a FIXME in the code setting rkmessage->rkt, it will just take some refactoring of the broker transmission loop, I'll see to it.

For dr_msg_cb, rkmessage->_private  is the message opaque (as given to the produce..() call).

**Comment by dharesign** [comment]
Somewhat off-topic to this particular discussion, but I was wondering why the message opaque shows up as `...->_private`, rather than something like `...->opaque`. It makes it sound like something that shouldn't be used.

**Comment by edenhill** [comment]
@dharesign API design is hard, especially when you need to be infinitely API and ABI safe.

message_t started off as a consumer data type where _private pointed back to the internal storage,
but then out of convenience (and naming) it was reused for the producer side as well and then
_private was reused as opaque to maintain binary compatbility.

In hind sight I should have made rd_kafka_message_t a private type with accessor methods instead.

**Comment by edenhill** [comment]
Fixed on master
