### ISSUE TITLE
Lightweight Kafka C/C++ Producer

### ISSUE THREAD

**Issue by davihar** [edenhill/librdkafka#2780]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
How do I reduce the memory footprint of a Producer?  I have a memory budget of 100k for code and memory used.  Is there another lightweight client I should use?  Thanks.

**Comment by edenhill** [comment]
Super lightweight is not a design goal of librdkafka.

You might want to look into using the [kafka-rest proxy](https://docs.confluent.io/current/kafka-rest/index.html) and having a simple http client.
