### ISSUE TITLE
Confluent Kafka C# 1.3.0 - Local: Maximum application poll interval (max.poll.interval.ms) exceeded

### ISSUE THREAD

**Issue by Abby86** [edenhill/librdkafka#2785]
Hi

We are regularly receiving the below error in our Kafka consumer. We are unable to fix this.

Local: Maximum application poll interval (max.poll.interval.ms) exceeded

Can you please help us in resolving this. Consumer config

BootstrapServers = xxxx,
GroupId = xxxxx,
EnableAutoCommit = false,
StatisticsIntervalMs = 5000,
SessionTimeoutMs = 6000,
MaxPollIntervalMs = 30000,
AutoOffsetReset = AutoOffsetReset.Earliest,
EnablePartitionEof = true

Code Snippet

using (var consumer = new ConsumerBuilder<Ignore, string>(KafkaConfig).SetErrorHandler(ErrorHandler)
.Build())
{
consumer.Subscribe(KafkaTopic);

Please help

Thanks
Abhay

**Comment by edenhill** [comment]
Dup of https://github.com/confluentinc/confluent-kafka-dotnet/issues/1228
