### ISSUE TITLE
dr_msg_cb() always get a NULL opaque data type

### ISSUE THREAD

**Issue by edsiper** [edenhill/librdkafka#2789]
Description
===========

As a recent improvement from our application, we are using an opaque data type to handle better logging from our side. For some reason, the opaque data set when calling the producer, is never returned in the delivery message callback, it always gets NULL.

Workflow through GDB breakpoints (refer to msg_opaque address):

```
Thread 1 "fluent-bit" hit Breakpoint 2, rd_kafka_produce (rkt=0x555555bc6e10, partition=-1, msgflags=2, payload=0x555555bcff50, len=367, key=0x0, keylen=0, msg_opaque=0x555555bc6c00)
    at /home/edsiper/coding/fluent-bit/plugins/out_kafka/librdkafka-1.3.0/src/rdkafka_msg.c:470
470	        return rd_kafka_msg_new(rd_kafka_topic_a2i(rkt), partition,
(gdb) c
Continuing.

Thread 1 "fluent-bit" hit Breakpoint 1, cb_kafka_msg (rk=0x555555bc8a10, rkmessage=0x555555bd0190, opaque=0x0) at /home/edsiper/coding/fluent-bit/plugins/out_kafka/kafka.c:38
38	    if (rkmessage->err) {

```

As you can see, our producer set an opaque with address ```0x555555bc6c00```, but our callback called ```cb_kafka_msg``` is getting a ```opaque=0x0```.

Our expectation is that the opaque reference gets available in the callback.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v1.3.0
 - [x] Critical issue

**Comment by edenhill** [comment]
The opaque parameter to produce() shows up as `rkmessage._private` in dr_msg_cb, while the opaque argument to dr_msg_cb is the `rd_kafka_t` opaque value (rd_kafka_conf_set_opaque()).

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1668
