### ISSUE TITLE
librdkafka and broker compatibility

### ISSUE THREAD

**Issue by lathakris** [edenhill/librdkafka#2790]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
librdkafka and broker compatibility. Just wanted to find out if librdkafka version 1.3.0 is compatible with broker version - 2.4.1. thank you for your response.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [ ] librdkafka version (release number or git tag): `1.0.1
 - [ ] Apache Kafka version: `2.4.1`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `Ubuntu (x64))>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rolandyoung** [comment]
From the manual page (which is linked from the FAQ): 

> librdkafka supports all released Apache Kafka broker versions since 0.8.0.0.0, but not all features may be available on all broker versions since some features rely on newer broker functionality.

After reading this: https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#broker-version-compatibility, do you have any specific question about feature support?

**Comment by lathakris** [comment]
thank you very much for your prompt response. I just wanted to make sure since this looked like a generic statement, Thanks once again.
