### ISSUE TITLE
Bump bundled openssl to 1.1.1 LTS

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#2793]
1.0.2 went EOL december 2019.

**Comment by dannypaz** [comment]
@edenhill do you have a high-level idea of what work would need to go in to make this change? +1 for this feature

**Comment by edenhill** [comment]
It is straight-forward on Linux and OSX, but the Windows build needs some work.

**Comment by edenhill** [comment]
https://ci.appveyor.com/project/edenhill/librdkafka/builds/32736810/job/m613xb5vjjcg2lbu

**Comment by edenhill** [comment]
They're all 1.1.1 now
