### ISSUE TITLE
Question about producer delivery report callback function

### ISSUE THREAD

**Issue by atari83** [edenhill/librdkafka#2794]
Hello there,
Based on this sample: https://github.com/edenhill/librdkafka/blob/master/examples/producer.c

I just wanted to make sure if i get it right,
So, lets say I'm producing messages with rd_kafka_producev and also retry on RD_KAFKA_RESP_ERR__QUEUE_FULL error. Just wanted to know in such occurrence (internal queue gets full), Do i still receive error on delivery report callback function ? or because i'm handling that error locally it doesnt pop anything on that callback function ?

Thanks

**Comment by edenhill** [comment]
You will only get delivery reports for messages accepted by produce(), i.e., where produce does not return an error.
When produce() returns an error the message is not handled, queued or kept by librdkafka.

**Comment by atari83** [comment]
Thank you Magnus :)
