### ISSUE TITLE
Kafka consumer not work if I set too large offset

### ISSUE THREAD

**Issue by DinoStray** [edenhill/librdkafka#2796]
Description
===========
If there are only 10 message in kafka, but I set the offset to 200
 
int64_t offset= 200
rd_kafka_consume_start(topic_, partition_, RD_KAFKA_OFFSET_TAIL(offset)) 

then the consumer never get any message from kafka , yes , never , even if I called rd_kafka_consume() for more than 200 times  
If I set offset= 3, then everything is ok

Checklist
=========
 - librdkafka version 1.3.0
 - Apache Kafka version:  kafka_2.12-2.2.0
 - librdkafka client configuration: "fetch.wait.max.ms" = "5"
 - ubuntu 18.04

**Comment by DinoStray** [comment]
"auto.offset.reset" = "earliest"  
then everything is OK

**Comment by edenhill** [comment]
If you pass a non-existent offset it will use the auto.offset.reset policy, which defaults to latest.
