### ISSUE TITLE
New Consumer API

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#280]
Some thoughts on the new consumer API when broker based consumer balancing is available (0.9).

This should strive to mimick the org.apache.kafka.clients.consumer API as closely as possible (when relevant).

Consumer instances are created as they are today:
````
    rd_kafka_conf_t *conf = ..;
    consumer = rd_kafka_new(RD_KAFKA_CONSUMER, conf..);
````

To join a consumer group for a topic:
````
    rd_kafka_topic_conf_t *tconf = ...;
    rd_kafka_topic_t *rkt = rd_kafka_topic_new("mytopic", tconf,..);
    rd_kafka_queue_t *rkqueue = ...;  /* optional routing queue */
    /* Add topic subscription */
    rd_kafka_subscription_t *sub;

    sub = rd_kafka_topic_subscribe(rkt, rkqueue);
````

To part a consumer group:
````
   rd_kafka_topic_unsubscribe(sub);
   // or: ?
   rd_kafka_topic_unsubscribe(rkt, rkqueue);
````

The same interface could be used for the current simple consumer with an added partition argument:
````
   /* Join consumer group */
    rd_kafka_topic_subscribe(rkt, RD_KAFKA_PARTITION_UA, rkqueue);

   /* Consume single partition (simple consumer) */
   rd_kafka_topic_subscribe(rkt, my_partition, rkqueue);
````

Messages are consumed as usual on the queue.

Thoughts and comments are welcome.

**Comment by fsaintjacques** [comment]
I'm more interested in failure scenarios, if consumer X fails without calling `rd_kafka_topic_unsubscribe()`, what's the behaviour?

**Comment by edenhill** [comment]
Any client that does not send a HeartbeatRequest within `session.timeout.ms` will be purged from the group and cause a group rebalance.

**Comment by edenhill** [comment]
Fixed on master
