### ISSUE TITLE
Error LNK2019	unresolved external symbol "__declspec(dllimport)

### ISSUE THREAD

**Issue by ChinigamiHunter** [edenhill/librdkafka#2802]
hello,
i am new to c++ and apache kafka and i'm trying to create a producer that send json file.
produucer code using is:

// Kafka.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <iostream>
#include <string>
#include <fstream>

#include "librdkafka/rdkafkacpp.h"

int static producer_1()
{
	std::string brokers = "127.0.0.1";
	std::string errstr;
	std::string topic_str = "linli";
	std::string mode;
	std::string debug;
	int32_t partition = RdKafka::Topic::PARTITION_UA;
	int64_t start_offset = RdKafka::Topic::OFFSET_BEGINNING;
	bool do_conf_dump = false;
	int opt;
	// MyHashPartitionerCb hash_partitioner;
	int use_ccb = 0;

	/*
	* Create configuration objects
	*/
	RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
	RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

	conf->set("metadata.broker.list", brokers, errstr);

	RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);
	if (!producer) {
		std::cerr << "Failed to create producer: " << errstr << std::endl;
		exit(1);
	}

	std::cout << "% Created producer " << producer->name() << std::endl;

	/*
	* Create topic handle.
	*/
	RdKafka::Topic *topic = NULL;
	if (!topic_str.empty()) {
		topic = RdKafka::Topic::create(producer, topic_str, tconf, errstr);
		if (!topic) {
			std::cerr << "Failed to create topic: " << errstr << std::endl;
			exit(1);
		}
	}

	RdKafka::ErrorCode resp = producer->produce(topic, partition,
		RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
		const_cast<char *>("hello worlf"), 11,
		NULL, NULL);

	delete topic;
	delete producer;
	return 0;
}

int static producer_2()
{
	std::string brokers = "127.0.0.1";
	std::string errstr;
	std::string topic_str = "linli";
	std::string mode;
	std::string debug;
	int32_t partition = RdKafka::Topic::PARTITION_UA;
	int64_t start_offset = RdKafka::Topic::OFFSET_BEGINNING;
	bool do_conf_dump = false;
	int opt;
	// MyHashPartitionerCb hash_partitioner;
	int use_ccb = 0;

	RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
	RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

	conf->set("metadata.broker.list", brokers, errstr);

	RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);
	if (!producer) {
		std::cerr << "Failed to create producer: " << errstr << std::endl;
		exit(1);
	}

	std::cout << "% Created producer " << producer->name() << std::endl;

	RdKafka::ErrorCode resp = producer->produce(topic_str, partition,
		RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
		(void *)"hi", 2,
		NULL, 0, 0, NULL);

	std::string errs(RdKafka::err2str(resp));
	std::cout << errs << std::endl;
	//producer->poll(0);

	delete producer;

	return 0;
}

int main()
{

	producer_2();

	return 0;
}

the error code is:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::err2str(enum RdKafka::ErrorCode)" (__imp_?err2str@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ErrorCode@1@@Z) referenced in function _main	Kafka	C:\Users\HP\documents\visual studio 2015\Projects\Kafka\Kafka\Kafka.obj	1

**Comment by edenhill** [comment]
Are you linking to librdkafkacpp.lib?

**Comment by Damour2** [comment]
how ?

**Comment by legend-k** [comment]
@ChinigamiHunter Did you solve this error?

**Comment by SaiManasaS** [comment]
I started the zookeeper server and Kafka server on my local machine and then executed the below application code.

I am getting a similar error: "Exception thrown at 0x00007FFC93A4C3F9 (msvcr120.dll) in KafkaSecond.exe: 0xC0000005: Access violation reading location 0x0000003904D00000." (librdkafkacpp.lib is included in the Linker options).

Below is the program I tried out on Visual Studio 2019.
-----------------------------------------------------------------------------------------------------
#pragma once 

#include <iostream>
#include "kafkaConsumer.h"
#include "librdkafka/rdkafkacpp.h"

using namespace std;

void main()
{
	int32_t partition = RdKafka::Topic::PARTITION_UA;
	int64_t start_offset = RdKafka::Topic::OFFSET_BEGINNING;

	/*
     * Create configuration objects
     */
	RdKafka::Conf* conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
	RdKafka::Conf* tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

	cout << "conf: " << conf << endl;
	cout << "tconf: " << tconf << endl;

	RdKafka::Conf::ConfResult confRes;
	std::string features;
	std::string errstr, optarg;
	string brokers = "localhost";

	/*
     * Set configuration properties
     */

	if (conf)
	{
		conf->set("client.id", "MyClient", errstr);
		//conf->set("client.id", "MyClient", errstr);
		conf->set("group.id", "MyGroup", errstr);
		
		conf->set("bootstrap.servers", brokers, errstr);
	}

	/*
     * Create consumer using accumulated global configuration.
     */

	cout << "Creating a consumer" << endl;

	RdKafka::Consumer* consumer = RdKafka::Consumer::create(conf, errstr);

	cout << "Checking for a consumer" << endl;
	if (!consumer) 
	{
		std::cerr << "Failed to create consumer: " << errstr << std::endl;
		exit(1);
	}

	//confRes = conf->get("builtin.features", features);
	confRes = conf->get("compression.codec", features);

	cout << "confRes: " << confRes << endl;
	cout << "features: " << features.c_str() << endl;

	cout << "features: " << features.c_str() << endl;

//	conf->set(

	while (1);
}

**Comment by edenhill** [comment]
@SaiManasaS Please don't reuse an unrelated issue, find a matching issue or create a new issue instead and provide more info, e.g., on what line does it crash? Crash dump? Backtraces? Logs?

**Comment by SaiManasaS** [comment]
@edenhill: Sure, I'll do that.
