### ISSUE TITLE
librdkafkacpp.dll

### ISSUE THREAD

**Issue by Damour2** [edenhill/librdkafka#2807]
hello,
i get this error when i try running my app in visual studio 2015 c++.

Exception thrown at 0x50021F39 (librdkafkacpp.dll) in ProjectKafka.exe: 0xC0000005: Access violation writing location 0x5002B9EF.

If there is a handler for this exception, the program may be safely continued.

error line in : 
std::string err_string;
	if (topic_conf->set("partitioner_cb", &hash_partitioner, err_string) != RdKafka::Conf::CONF_OK) {
		printf("set partitioner_cb error: %s\n", err_string.c_str());
		return 0;
	}
	global_conf->set("metadata.broker.list", broker_list, err_string);
	global_conf->set("event_cb", &event_cb, err_string);
	global_conf->set("dr_cb", &delivery_cb, err_string);
	global_conf->set("debug", "all", err_string);

**Comment by Damour2** [comment]
error line is here : std::cout << "% Created producer " << producer->name() << std::endl;

	RdKafka::ErrorCode resp = producer->produce(topic_str, partition,
		RdKafka::Producer::RK_MSG_COPY /* Copy payload */,
		(void *)"hi", 2,
		NULL, 0, 0, NULL);

**Comment by edenhill** [comment]
Issue template not respected.

**Comment by Damour2** [comment]
gow can i fix the problem !

**Comment by edenhill** [comment]
Open a new issue where you fill out the issue template with the requested information.

Also provide the backtrace from the crash (using the visual studio debugger, for instance).

Make sure that your callback class instances are either static or allocated on the heap so they don't go out of scope, they need to outlive the Kafka client instance.
