### ISSUE TITLE
Documentation on confluent website merges 2 message statuses

### ISSUE THREAD

**Issue by JSoet** [edenhill/librdkafka#2808]
Description
===========
I noticed that the message status on the confluent website seems to merge the 'not persisted' and the 'possibly persisted' statuses, and then the one listed for 'persisted' shows up under 'possibly persisted':
![image](https://user-images.githubusercontent.com/4523613/78836227-8a4c2700-79a6-11ea-9a6f-02600fb890bb.png)

vs the current master:
![image](https://user-images.githubusercontent.com/4523613/78836260-9cc66080-79a6-11ea-89b5-1867ad123984.png)

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v 1.4.0` codebase

**Comment by edenhill** [comment]
Thank you for report this, will fix!

**Comment by rnpridgeon** [comment]
![image](https://user-images.githubusercontent.com/5313961/79467724-1aecbd80-7fcc-11ea-8751-a5648fcf9300.png)
:+1:

**Comment by edenhill** [comment]
The Confluent docs will be updated soon.
