### ISSUE TITLE
Any plan to use CMake as the only build tool?

### ISSUE THREAD

**Issue by prehistoric-penguin** [edenhill/librdkafka#2809]
Currently, we have configure/mklove for Linux building, Visual Studio/Nuget for Windows building. Any plan to use CMake as the only build tool?

Reasons:

- Today CMake is the most widely used building tool for c/c++ projects, it's highly recommended
- CMake combine with VCPKG is great, it makes 3rdparty library management easier
- The Visual Studio/Nuget configuration is buggy (When I want to remove the linkage of openssl/zlib/sasl it won't' working, Nuget is not designed for c++ libraries, it have many drawbacks) and hard to use (Openssl must be installed at C:\OpenSSL64 which is a struggle for our 3rdparty library management)

If you agree with me, I can make contributions.

**Comment by rolandyoung** [comment]
As I understand it, there is already a CMakeList provided and maintained by external contributors. It might be helpful if you indicate what further steps you are proposing, maybe some or all of the following (numbered for reference, not priority):

1. Magnus to keep the CMakeList up to date as he merges changes that would affect it
2. CI tasks to verify CMake builds on Windows and key Linux platforms
3. Build documentation to prefer CMake over other build tools
4. Drop other build tools

Clearly if @edenhill isn't happy with the first, or the project budget won't run to the second, the rest are moot, but I think it's worth being clear what this would involve.

**Comment by prehistoric-penguin** [comment]
@rolandyoung 

Thanks for the reply, I have tried the existed CMakeLists on Linux and it works. But for Windows, there are problems with 3rdparty library finding and function switch.

**Comment by edenhill** [comment]
@rolandyoung is completely right.

There are no plans to replace the current official build alternatives with CMake, but we're happy to provide CMake as an alternative given that the community maintains it, but we will not.


We have CI builds that use CMake to verify that PRs do not miss or break the CMake builds, that should be sufficient for now.
