### ISSUE TITLE
rd_kafka_test_fatal_error() call reports failure when it succeeds

### ISSUE THREAD

**Issue by ckb42** [edenhill/librdkafka#2811]
Description
===========

I believe the logic is flipped on the return value for rd_kafka_test_fatal_error.  This routine calls set_fatal_error, which returns 0 on failure (error pending) and 1 on success.

Below this is inverted, where the in_progress error is returned when set returns 1:

rd_kafka_resp_err_t
rd_kafka_test_fatal_error (rd_kafka_t *rk, rd_kafka_resp_err_t err,
                           const char *reason) {
        if (rd_kafka_set_fatal_error(rk, err, "test_fatal_error: %s", reason))
                return RD_KAFKA_RESP_ERR__PREV_IN_PROGRESS;
        else
                return RD_KAFKA_RESP_ERR_NO_ERROR;
}

Maybe I am confused.  Who knows.

How to reproduce
================

1. Write code that actually checks the return value of test_fatal_error.
2. Every call to test_fatal_error that should succeed returns the IN_PROGRESS error.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<rdkafka.c https://github.com/edenhill/librdkafka/commit/d564269c436446bf214206f7f8d9be865f34562f>`
 - [x] Apache Kafka version: `<NA>`
 - [x] librdkafka client configuration: `<NA>`
 - [x] Operating system: `<N/A but Linux Ubuntu 14.04>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You are right!
Care to file a single-character PR? :)

**Comment by ckb42** [comment]
Thanks for confirming. 
I will do it solely for the story I can tell afterwards and being able to put "librdkafka contributor" on my resume.  :-)

    On Thursday, April 9, 2020, 03:55:47 PM EDT, Magnus Edenhill <notifications@github.com> wrote:  
 
 


You are right!
Care to file a single-character PR? :)

**Comment by edenhill** [comment]
Merged, thank you :)
