### ISSUE TITLE
DLQ

### ISSUE THREAD

**Issue by renatocosta** [edenhill/librdkafka#2813]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Does lib support Dead letter queue? Is possible in case of reaching out max attempts and then move the message to another topic?

**Comment by edenhill** [comment]
No, that logic is up to the application, but it can be easily done by producing to the secondary topic in the dr_msg_cb upon failure.

**Comment by renatocosta** [comment]
I got it. Thank you for me help me.

**Comment by renatocosta** [comment]
Thank you for your all attentions
