### ISSUE TITLE
[question]: consumer API query

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#2814]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

> /**
>  * @name Simple Consumer API (legacy): Queue consumers
>  * @{
>  *
>  * The following `..._queue()` functions are analogue to the functions above
>  * but reads messages from the provided queue \p rkqu instead.
>  * \p rkqu must have been previously created with `rd_kafka_queue_new()`
>  * and the topic consumer must have been started with
>  * `rd_kafka_consume_start_queue()` utilising the the same queue.
>  */

while using rd_kafka_consume_queue() API, I came across comments in list. Do I must  call `rd_kafka_consume_start_queue()` if I have used consume_queue() API?

I am using multiple threads per partition logic as per your test program [here](https://github.com/edenhill/librdkafka/blob/master/tests/0056-balanced_group_mt.c)
I didn't see `consume_start()` API in this test code. Is there any specific reason?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.4.0`
 - [x] Apache Kafka version: `1.1.1`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `Ubuntu Linux`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by write2jaydeep** [comment]
@edenhill another question:
As mentioned above I am polling the partition queue using `rd_kafka_consume_queue()`
to get an internal error(error_cb) and statistics (stat_cb), do we need to poll 'rd_kafka_consumer_poll()' in separately?

**Comment by edenhill** [comment]
Missed this one, sorry.

1. Don't use the legacy consumer. You can use the new consumer with assign() and forward queues individually per partition  as you see fit.
2. Yes, you will need to call consumer_poll() separately if you have redirected partition queues to separate queues.
3. That works fine
