### ISSUE TITLE
This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\zlib.v142.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\zlib.v142.windesktop.msvcstl.dyn.rt-dyn.targets.

### ISSUE THREAD

**Issue by yadav26** [edenhill/librdkafka#2816]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Project migration to VS2019 and pointed to latest sdk that is default 10.0 and nuget manager started errorin

How to reproduce
================
No brainer just open the solution in VS2019 16.0 update(latest to 10.04.2020), point the DLL of projects to sdk version 10.0

 - [x] librdkafka version (release number or git tag): "current">`
 - [ ] Apache Kafka version: `doesnt matter it's about compilation failure`
 - [ ] librdkafka client configuration: `same as above`
 - [ ] Operating system: `Win10x64`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\zlib.v142.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\zlib.v142.windesktop.msvcstl.dyn.rt-dyn.targets.	\librdkafka\win32\librdkafka.vcxproj	257	

 - [ ] Provide broker log excerpts -- NA
 - [ ] Critical issue

![image](https://user-images.githubusercontent.com/25176775/78961380-9b2aa300-7b34-11ea-8266-0c101c163f41.png)

**Comment by yadav26** [comment]
Though nugets are downloaded in package folder on build.

**Comment by yadav26** [comment]
Able to fix the issue with modifications in vcxproj and linking directories and openssl libs updated to available at https://www.npcglib.org/~stathis/downloads/openssl-1.1.0f-vs2017.7z
I could only able to build when removed libeay*and ssleay*.lib , and link the correct MD or MTD lib.

**Comment by edenhill** [comment]
zlib is now included in librdkafka.redist
