### ISSUE TITLE
How Can I use librdkafka in windows with Qt and mingw ?

### ISSUE THREAD

**Issue by Ryan-Lew** [edenhill/librdkafka#2817]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

How Can I use librdkafka in windows with Qt/mingw?

How to reproduce
================
I have compiled the librdkafka 64 bit dlls with virtualstudio2015 as document saying.
but failed to use the DLLs with qt/mingw32. The error message is : File format not recognized.
Meanwhile, I use qt/msvc 64 , also got the message : Unresolved external symbols.
I did anything wrong? I`m almost creazy now.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I'm sorry but I have no experience with MinGW, we only support MSVC builds through the librdkafka.redist NuGet packages.

Maybe other community members can help?

**Comment by edenhill** [comment]
MinGW64 build options were recently merged, see https://github.com/edenhill/librdkafka/pull/2553

These builds are unsupported and need to be maintained by the open source community.

**Comment by neptoess** [comment]
@Ryan-Lew ,
As @edenhill mentioned, MinGW builds have been added to master. I would recommend building the librdkafka with MinGW. Once v1.5.0 releases, I'm hoping to get a package added to msys2 to streamline using the MinGW build.

However, you can also use the files from the librdkafka.redist NuGet package, but it's a little more involved. I've detailed this on a confluent-kafka-go issue
https://github.com/confluentinc/confluent-kafka-go/issues/128

For v1.4.2, high-level:
1. Copy rdkafka.h into include/librdkafka
2. Generate a librdkafka.a and copy it to lib
3. Copy the DLLs from the redist to System32 (or copy them to your app's bin directory)
