### ISSUE TITLE
Is there any way to figure out when a message was actually being sent through the network? Besides, how could we get the local queue buffering pressure?

### ISSUE THREAD

**Issue by kenneth-jia** [edenhill/librdkafka#2818]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
While using a Kafka producer to send messages, we could know when a message was produced (generated), when the record was persisted (logAppended) , but we have no idea when the message was actually being sent through the network!

E.g, if we're trying to benchmark the Kafka network with some fixed throughput, we might see a large end-to-end latency (could be a few seconds), while in fact, during most of the time, these messages were just pending in the local queue (i.e, queue.buffering.max.messges/queue.buffering.max.kbytes). 

So is there any way to figure out how the real networking latency (i.e, get when the message actually been sent through the network) is? Besides, how could we get the local queue buffering pressure?

Thanks!

**Comment by edenhill** [comment]
Aggregate latencies are available in the statistics json object, see https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#latency-measurement

**Comment by kenneth-jia** [comment]
@edenhill Thank you, Magnus! It definitely would help.
