### ISSUE TITLE
Could not tell the error is network timeout or eof

### ISSUE THREAD

**Issue by haosdent** [edenhill/librdkafka#282]
Hi, sorry to disturb you. For current rdkafka consume api. https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L520-L525
```
* Errors (in Message->err()):
   *   ERR__TIMED_OUT - 'timeout_ms' was reached with no new messages fetched.
   *   ERR__PARTITION_EOF - End of partition reached, not an error.
```
If reach eof, would return ERR__TIMED_OUT. Is it normal?

**Comment by edenhill** [comment]
When your consumer reaches the current end of the partition your app will get a ERR__PARTITION_EOF error, if no new messages are produced to the partition your next consume() call will time out, and subsequent calls will too until new messages are available.
Neither PARTITION_EOF or TIMED_OUT are really errors, just indications that there are no more messages available (which is a temporary state).

**Comment by haosdent** [comment]
Oh, so if a error indicate the network error?

**Comment by edenhill** [comment]
No, these do not indicate network errors, and network errors are not propagated on the consumer interface, only through the error_cb on poll() with error code ERR__TRANSPORT.
The application typically shouldn't care about network errors though, those are also mostly temporary failures and it is better for librdkafka to handle that graceful by retrying connections, etc.

**Comment by haosdent** [comment]
Thank you very much for your reply. Let me try other ways to skip it.
