### ISSUE TITLE
Can a partition's fetch_state != 'none' for multiple consumers?

### ISSUE THREAD

**Issue by jpdstan** [edenhill/librdkafka#2821]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We're trying to build a realtime view of a topic's stats per partition to get better visibility into each partition's offsets and such. Originally, we intended to have a partition to have its stats reported by a consumer _only if_ the `fetch_state == 'active'`. These stats would be upserted to some central datastore, essentially replacing the old values every time a new statistics event is received.

However, we realize that there are many more states (`stopping, stopped, offset-query, offset-wait`) that we wouldn't be collecting offset stats for, and thus considered changing the above check to be `fetch_state != 'none'`. 

But with this we are worried that this check might be too permissive and may result in consumers overriding each others' values. We didn't have to worry about this with the `fetch_state == 'active'` since I believe we're guaranteed this would be true for only one partition at any given time. Is this true for the other states, as well? E.g. is it possible for a partition to be `stopped` for one consumer but `offset-wait` for another? Or any combination of these states?

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.2.2`
 - [x] Apache Kafka version: `2.2.1`
 - [x] librdkafka client configuration:
```
  'enable.auto.offset.store': false,
  'enable.auto.commit': true,
  'auto.commit.interval.ms': 1000,
  'security.protocol': 'ssl',
```
 - [x] Operating system: `Alpine Linux 3.10`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The non-active|none states are transitory between either none or active, where stopping and stopped are for when the assignment is lost, and offset* is for a new assignment where the committed offsets are fetched.
I think you should only see stopping, offset* and active from a single consumer at the time.
