### ISSUE TITLE
rd_kafka_message_errstr not available as it is inlined

### ISSUE THREAD

**Issue by andre2007** [edenhill/librdkafka#2822]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
The example `consumer.c` is using functon `rd_kafka_message_errstr`. This function is not available if you develop not in C/C++ but from another language and you have only the DLL/SO and the header file definitions.
The counter part for producers `rd_kafka_err2str` is not inlined and therefore available. Is it possible to remove the inline attribute for `rd_kafka_message_errstr`?

How to reproduce
================
Not relevant

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v.1.4.0`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `Windows x64>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Good point, we'll see if we can do this without breaking ABI.
