### ISSUE TITLE
Installing librdkafka updated version

### ISSUE THREAD

**Issue by parveenbadoni** [edenhill/librdkafka#2823]
Hi,

I am trying to install librdkafka on ubuntu 18.04.1. I used following commands :
sudo apt-get install librdkafka-dev
sudo apt-get install librdkafka1
sudp apt-get install librdkafka++1

librdkafka got installed, but version 0.11.3. How can i install updated version of librdkafka. For my requirement, i need version 0.11.4 or above. Can someone please help?

**Comment by edenhill** [comment]
Use the Confluent APT repos as instructed in the README:
https://github.com/edenhill/librdkafka#installation
