### ISSUE TITLE
Is it possible to use only the necessary .so files from redist?

### ISSUE THREAD

**Issue by sungam3r** [edenhill/librdkafka#2824]
Hi. I found these files in the output publish folder after publish self-contained .NET Core app for with `<RuntimeIdentifier>linux-musl-x64</RuntimeIdentifier>`:
![image](https://user-images.githubusercontent.com/21261007/79220097-11dcde80-7e5c-11ea-9b86-b05482e3c312.png)

I understand that these files are in the distribution package in the native dependency section. My question is, are they all necessary for my application to work? I use [microsoft/dotnet/core/runtime-deps:3.1](https://hub.docker.com/_/microsoft-dotnet-core-runtime-deps/) base image.

First, I wanted to manually delete some files (debian9-librdkafka.so and centos7-librdkafka.so) and run the application to see if t works. But I got such an error:
```
An assembly specified in the application dependencies manifest (MyApp.deps.json) was not found:
    package: 'librdkafka.redist', version: '1.0.1'
    path: 'runtimes/linux-x64/native/centos7-librdkafka.so'
```

Looking at the app manifest I found these lines there:
```json
"librdkafka.redist/1.0.1": {
        "native": {
          "runtimes/linux-x64/native/alpine-librdkafka.so": {
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-x64/native/centos7-librdkafka.so": {
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-x64/native/debian9-librdkafka.so": {
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-x64/native/librdkafka.so": {
            "fileVersion": "0.0.0.0"
          }
        }
      },
```

On this I decided that the problem is deeper and will not be solved simply by deleting files. I don’t want to manually edit the application manifest, although I assume this might help. My goal is to have only the files actually used by the application in the docker container. As you can see, native libraries take up a lot of space. I suppose that I actually only need `alpine-librdkafka.so` saving 32 MB removing other `.so` redist native files. Could you say I'm thinking in the right direction? And if so, how can you get rid of unnecessary files without resorting to low-level editing of the manifest?

  - [x] librdkafka version (release number or git tag): `1.3.0`

The information below is not relevant to the issue.

 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by sungam3r** [comment]
@edenhill @mhowlett Could you help please?

**Comment by mhowlett** [comment]
On startup, the .NET Client tries to load each of the .so's in librdkafka.redist until it finds one that works and then uses that. There isn't currently a nice way of reducing librdkafka.redist dependency size. Instead of editing the nuget manifest, you could maybe overwrite the .so's (and .dll and .dylib) you don't need with a 0 size file which the .net client will fail to load, and so will ignore. I think this will also keep nuget happy. This would be easier to automate than editing the manifest and I think would work. Any ideas for a better solution, please feel free to suggest. I suspect size is going to come more into the spotlight with .net 5 and single file apps where people are going to be more explicitly noticing this (also, there's the question of whether the current setup is even going to work... but we'll cross that bridge when we get to it).

**Comment by sungam3r** [comment]
> until it finds one that works 

Thanks for the answer, it’s pretty clear. I am just curious how this condition determined - _that works_?

**Comment by mhowlett** [comment]
it's not sophisticated. it just tries to use a method, and if it works, assumes it's loaded.

**Comment by sungam3r** [comment]
Ok. I ended up using this
```
<PropertyGroup>
    <LibrdkafkaDirectoriesToRemove>$(PublishDir)/runtimes/osx-x64;$(PublishDir)/runtimes/win;$(PublishDir)/runtimes/win-x64;$(PublishDir)/runtimes/win-x86;</LibrdkafkaDirectoriesToRemove>
    <LibrdkafkaFilesToTruncate>$(PublishDir)/runtimes/linux-x64/native/librdkafka.so;$(PublishDir)/runtimes/linux-x64/native/centos7-librdkafka.so;$(PublishDir)/runtimes/linux-x64/native/alpine-librdkafka.so</LibrdkafkaFilesToTruncate>
  </PropertyGroup>

  <!-- https://github.com/edenhill/librdkafka/issues/2824 -->
  <!-- https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2019 -->
  <UsingTask TaskName="TruncateFile" TaskFactory="RoslynCodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >
    <ParameterGroup>
      <Files ParameterType="Microsoft.Build.Framework.ITaskItem[]" Required="true" />
    </ParameterGroup>
    <Task>
      <Using Namespace="System.IO"/>
      <Code Type="Fragment" Language="cs">
        <![CDATA[
      if (Files.Length > 0)
      {
        for (int i = 0; i < Files.Length; i++)
        {
          string path = Files[i].ItemSpec;
          if (File.Exists(path))
          {
            using (var stream = new FileStream(path, FileMode.Open, FileAccess.ReadWrite))
              stream.SetLength(0);
          }
        }
      }
]]>
      </Code>
    </Task>
  </UsingTask>
  
  <Target Name="RemoveDirectories" AfterTargets="Publish">
    <RemoveDir Directories="$(LibrdkafkaDirectoriesToRemove)" />
    <TruncateFile Files="$(LibrdkafkaFilesToTruncate)" />
  </Target>
```

Before:

Total 80 MB in 157 files

After:

Total 35 MB in 142 files

**Comment by sungam3r** [comment]
@mhowlett Thank you for the hint.

**Comment by ThomasTosik** [comment]
Glad we are not the only ones that got this urge to cleanup and shrink ;). But the workaround seems a little bit "heavy" for my taste.

When i look into my deps.json i see the following:
```
     "librdkafka.redist/1.4.4": {
        "runtimeTargets": {
          "runtimes/linux-x64/native/alpine-librdkafka.so": {
            "rid": "linux-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-x64/native/centos7-librdkafka.so": {
            "rid": "linux-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-x64/native/debian9-librdkafka.so": {
            "rid": "linux-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/linux-x64/native/librdkafka.so": {
            "rid": "linux-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          },
          "runtimes/osx-x64/native/librdkafka.dylib": {
            "rid": "osx-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
          }
.....
        }
      }
```

The docs (https://docs.microsoft.com/de-de/dotnet/core/rid-catalog) states that there is a appropriate RID for Alpine "linux-musl-x64". Shouldnt it be enough to explicitly set the rid for alpine to musl? Do i miss something conceptually? Backwards compatibility?

**Comment by sungam3r** [comment]
I think the whole point of this issue is that all distribution files are always copied regardless of the RID.

**Comment by ThomasTosik** [comment]
I cant confirm that. When using dotnet publish with the runtime information (-r) :
```
dotnet publish -c Release -o /app -r linux-musl-x64 --self-contained false --no-restore
```

I am getting no windows or mac libs. But sadly debian etc, even though i am running alpine.
```
-rwxr--r--    1 root     root      18912480 Jun 29 07:09 alpine-librdkafka.so
-rwxr--r--    1 root     root       2057096 Jun 29 07:09 centos7-librdkafka.so
-rwxr--r--    1 root     root      23597168 Jun 29 07:09 debian9-librdkafka.so
-rwxr--r--    1 root     root      13733429 Jun 29 07:09 librdkafka.so
```

BTW: I am in docker context...

**Comment by sungam3r** [comment]
Well, you see that you still have to delete more files.

**Comment by stylianosnicoletti** [comment]
Any updates on that?
What if I only need debian9-librdkafka.so and no alpine, centos etc
