### ISSUE TITLE
Redirecting logs (from stderr / stdout)

### ISSUE THREAD

**Issue by atari83** [edenhill/librdkafka#2825]
Hello there,

So, I'm trying to redirect all errors or warnings to my logger code, such as this log:

%3|1586866844.848|FAIL|rdkafka#consumer-2| [thrd:192.168.1.107:9092/bootstrap]: 192.168.1.107:9092/bootstrap: Connect to ipv4#192.168.1.107:9092 failed: Operation timed out (after 75002ms in state CONNECT)

Correct me if i'm wring, i think the way to go is to implement a callback for "rd_kafka_conf_set_log_cb" (?).

Although as i checked i cannot pass an external object (opaque) to the callback function .. So, what could be the workaround for my case ?

Checklist
=========

 - [x] librdkafka version : librdkafka-1.3.0
 - [x] Apache Kafka version: 2.4.1
 - [x] librdkafka client configuration: auto.reset.offset=earliest
 - [x] Operating system: FreeBSD 12.1 amd64

Thanks,

**Comment by rolandyoung** [comment]
You will need to fill out the checklist that you deleted when you raised this issue.

Have you checked the code example here: https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.c ?

**Comment by atari83** [comment]
> You will need to fill out the checklist that you deleted when you raised this issue.
> 
> Have you checked the code example here: https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.c ?

Thank you Roland, I'll update my post and add the checklist to it.
The example doesnt address my problem, because the callback function doesnt define how to ingest an external object to the function. (like what we could do with rd_kafka_conf_set_dr_msg_cb)

**Comment by rolandyoung** [comment]
For the opaque, use `rd_kafka_opaque(rk)` where `rk` is the first parameter passed to the logger callback. This allows you to access the opaque value you specified with  rd_kafka_conf_set_opaque when craeting the global config object you passed to rd_kafka_new.

**Comment by atari83** [comment]
Thank you Ronald, it worked :)
