### ISSUE TITLE
Python not found by build script on Ubuntu 20.04

### ISSUE THREAD

**Issue by umanwizard** [edenhill/librdkafka#2829]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
In Ubuntu 20.04, there is no binary on the path called `python`. There is, however, `python3`, `python2.7`, and `python2`. Thus, the build script is not able to find python.

How to reproduce
================
```
~/c/librdkafka ❯❯❯ ./configure | grep python
checking for python (by command)... failed (disable)
disabling linker-script since python is not available
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): ` git 3c8cc41103cfcbff3f2d782d9fc97293bf5bc13c
 - [X] Apache Kafka version: N/A
 - [X] librdkafka client configuration: N/A
 - [X] Operating system: Ubuntu 20.04
 - [X] Provide logs (with `debug=..` as necessary) from librdkafka: N/A
 - [X] Provide broker log excerpts: N/A
 - [ ] Critical issue

**Comment by edenhill** [comment]
Will be fixed in v1.5.0

Thank you for reporting this
