### ISSUE TITLE
Question about admin API

### ISSUE THREAD

**Issue by accelerated** [edenhill/librdkafka#2838]
Hi @edenhill, I've been looking at the Admin API and I wonder if there's a way to query the positions or committed offsets of all consumer groups or even a specific one. I know it's possible to do so for the consumer itself, but imagine a task which needs to know the positions of all consumer groups in the system. 
Thanks

**Comment by edenhill** [comment]
Hi, there are no admin APIs for this, but you can do the same thing through the consumer API by calling list_groups(), then creating a new consumer instance for each group.id and calling rd_kafka_metadata() to get the partitions for a topic and then committed() to get the committed offsets for that group and partitions.

**Comment by accelerated** [comment]
Ok, I see. But if the consumer groups have dynamic assignment, won't creating a new consumer instance cause a rebalance?

**Comment by accelerated** [comment]
Or do you mean to create the consumer w/o subscribing?

**Comment by edenhill** [comment]
Right, there will only be a rebalance if you call subscribe().

**Comment by accelerated** [comment]
Sure but don't you need to associate the group name with a topic somehow? How would you do that w/o calling subscribe or assign partitions? Multiple topics can have groups with the same name, so you have to make the distinction. The group name is only unique within a topic. Unless maybe I'm missing something.

**Comment by plachor** [comment]
@accelerated vote for https://github.com/edenhill/librdkafka/issues/2173 :)
