### ISSUE TITLE
How long must a topic name passed to rd_kafka_producev remain in memory

### ISSUE THREAD

**Issue by andrewthad** [edenhill/librdkafka#2843]
If I produce a messages with `rd_kafka_produce` and set `msgflags` to 0, no copying and no `free(3)`ing is done by kafka, so as the user, I must reclaim the payload through whatever means are appropriate in the message delivery callback. This makes perfect sense. What is not clear to me is if the same restriction applies to the topic name passed in through `rd_kafka_producev`. May I reclaim the memory after `rd_kafka_producev` returns, or do I need to reclaim that memory in the callback?

Whatever the case, I would like to see this documented, and I'm happy to PR that documentation if there's a clear answer to this.

**Comment by edenhill** [comment]
For everything but the message value/payload the lifetime of the passed object only needs to outlive the produce*() call itself, as soon as produce*() returns the memory is no longer referenced.

I'd be happy to accept a PR that clarifies this :+1:

**Comment by andrewthad** [comment]
Excellent, thanks for the quick reply. I've [PRed some documentation about this](https://github.com/edenhill/librdkafka/pull/2852).
