### ISSUE TITLE
Small naming error in the transaction explanation in the rdkafka.h

### ISSUE THREAD

**Issue by faladu** [edenhill/librdkafka#2846]
In the comment explaining the transactional producer on line 6637 it states
* least one of the following operations within \c transactional.timeout.ms to

However that parameter doesn't exist.
The correct one is transaction.timeout.ms which is listed in the configuration.md (https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)

Would be great if that could be adjusted, but not that important.

**Comment by edenhill** [comment]
Thank you! Will fix

**Comment by edenhill** [comment]
Will be fixed in v1.5.0
