### ISSUE TITLE
[Question] Diffrent subscriptions within same consumer group instances

### ISSUE THREAD

**Issue by plachor** [edenhill/librdkafka#2847]
Hi, I have been looking for answer to my question but have no luck finding any. 

In my scenario I have multiple instances of same process sharing same consumer group. Within this single consumer group I would like to divide instances further in to subgroups with dedicated list of topics to subscribe.

So for example:
a) 10 instance subscribing (`topicA`, `topicB`)
b) 2 instances subscribing (`topicC`, `topicD`)
c) 3 instances subscribing (`topicB`, `topicC`) 

Is it safe to assume following:
* those 10 instance from subgroup `a)` will only receive partitions form `topicA` and `topicB` and that some of partitions from `topicB` will assigned 3 instances from subgroup `c)`
* that partitions from topic `topicD` will be divided among those to 2 instance from subgroup `b)`

So to formalize the question: will subscription honor specific requirement (list of topics) or will eventually after some time treat all 15 instances as whole group and divide all those topics among this group evenly.

I've tried this out and it seems that consumer instance will only receive assignment from range of topics asked during subscription but would not like to fall in too a pitfall after some time once i start relaying on this fact.

**Comment by plachor** [comment]
Any hint if I'm heading right direction?

**Comment by edenhill** [comment]
The partition assignor respects each member's topic subscription list, so if instance-1 subscribes to topic A and B it might get assigned partitions from topic A and B (depending on number of consumers) but definitely not from C or D.

**Comment by plachor** [comment]
Thank you for clarification.
