### ISSUE TITLE
librdkafkacpp: undefined refrence

### ISSUE THREAD

**Issue by patidar12** [edenhill/librdkafka#2848]
Hi,
I just installed **librdkafka** using **apt install librdkafka-dev** on ubuntu.

I created a program in **CPP** for a producer to produce data.

But When I am going to execute it, its Giving errors:

/tmp/ccptqKZQ.o: In function `main':
Producer.cpp:(.text+0x2e0): undefined reference to `RdKafka::Producer::create(RdKafka::Conf*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
Producer.cpp:(.text+0x541): undefined reference to `RdKafka::err2str[abi:cxx11](RdKafka::ErrorCode)'
collect2: error: ld returned 1 exit status

Description
===========
Actually I am not using this git-hub project examples. I am using my code. I don't want to use make.
Can it be possible to resolve the issue?
Please reply fast.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rolandyoung** [comment]
Please provide all the information requested in the **IMPORTANT** notes above. In particular, fill out the checklist. Please also confirm that you down loaded the latest version of librdkafka as explained at https://docs.confluent.io/current/installation/installing_cp/deb-ubuntu.html#get-the-software.

You should also confirm that your installation is valid by following the GitHub project examples; the output of the supported build system will show you the compiler and linker options you need to use.

Finally, if you have a different approach that you want to follow, you will need to show exactly what compiler and linker options you used and provide the the full text of any error messages.

**Comment by Charana123** [comment]
I'm have this same issue.
After installing version 1.4.0 on debian with `apt install librdkafka-dev`
Compiling with `g++ producer.cpp $(pkg-config --cflags --libs rdkafka++)` gives
```
/tmp/cc1HP1q1.o: In function `main':
producer.cpp:(.text+0x2ce): undefined reference to `RdKafka::Producer::create(RdKafka::Conf*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
producer.cpp:(.text+0x4e9): undefined reference to `RdKafka::err2str[abi:cxx11](RdKafka::ErrorCode)'
collect2: error: ld returned 1 exit status
```

**Comment by edenhill** [comment]
Provide the output from `pkg-config --cflags --libs rdkafka++`

**Comment by Charana123** [comment]
Its just `-lrdkafka++` even though the pkg-config file is
```
prefix=/usr
libdir=/usr/lib/x86_64-linux-gnu
includedir=/usr/include

Name: librdkafka++
Description: The Apache Kafka C/C++ library
Version: 1.4.0
Cflags: -I${includedir}
Libs: -L${libdir} -lrdkafka++
Libs.private: -L../src -lrdkafka -lstdc++
```
The same error appears during compilation if I expand the pkg-config options as intended like 
`g++ --std=c++17 producer.cpp -I/usr/include -L/usr/lib/x86_64-linux-gnu -lrdkafka++`

**Comment by edenhill** [comment]
Try:
`g++ producer.cpp -I/usr/include -L/usr/lib/x86_64-linux-gnu -lrdkafka++ -lrdkafka`

**Comment by Charana123** [comment]
@edenhill doesn't help unfortunately, same error. I does work however if I `make && make install` and run my original command.
