### ISSUE TITLE
librdkafka build for UWP apps

### ISSUE THREAD

**Issue by dimtsiakm** [edenhill/librdkafka#2850]
Description
===========

I am developing an application for UWPbased applications (HoloLens) and I need the Kafka-Client. So, I need to build the librdkafka.dll from source for this architecture but I'm stuck. I am using Visual Studio 2017 and when I try to build the project I get some errors. I fixed a bunch of errors but new problems are coming.  

The current problem is the following.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol ___iob_func	librdkafka	
C:\..\librdkafka-1.4.0\win32\ssleay32MT.lib(t1_enc.obj)	1

and 

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol ___iob_func referenced in function _OPENSSL_stderr	librdkafka	C:\..\librdkafka-1.4.0\win32\libeay32MT.lib(cryptlib.obj)	1	

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.4.0`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `Windows 10 x64 SDK 18362`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
try to remove `\static`  from these two lines:
https://github.com/edenhill/librdkafka/blob/master/win32/librdkafka.vcxproj#L16
https://github.com/edenhill/librdkafka/blob/master/win32/librdkafka.vcxproj#L20

**Comment by dimtsiakm** [comment]
Dear Magnus,

Thank you for your reply. 

That's worked. Also, another problem in my case was that the files from OpenSSL installation. When you install in windows system you must choose to copy OpenSSL DLLs to OpenSSL binaries (/bin) directory (the second one).

Kind regards,
Dimitris
