### ISSUE TITLE
failed: err: Local: Broker handle destroyed

### ISSUE THREAD

**Issue by bjlvfei** [edenhill/librdkafka#2854]
Hi Team,
There one issue when client produce message to kafka cluster base of k8s. 

The value.yaml 
external:
  type: LoadBalancer
  dns:
    useInternal: false
    useExternal: false
    distinct: false
  enabled: true
  servicePort: 19092
  firstListenerPort: 31090
  domain: ***-dia-****.us-south.containers.appdomain.cloud
  loadBalancerIP:
    - 169.60.39.*
    - 10.209.242.*
    - 169.63.7.*
    - 10.74.190.*
    - 10.93.128.*
    - 169.62.134.*

configurationOverrides:
  "offsets.topic.replication.factor": "3"
  # "default.replication.factor": 3
  # "min.insync.replicas": 2
  # "auto.create.topics.enable": false
  #"auto.leader.rebalance.enable": true

  ## Options required for external access via NodePort
  ## ref:
  ## - http://kafka.apache.org/documentation/#security_configbroker
  ## - https://cwiki.apache.org/confluence/display/KAFKA/KIP-103%3A+Separation+of+Internal+and+External+traffic
  ##
  ## Advertised listeners will use the firstListenerPort value as it's default unless overridden here.
  ## Setting "advertised.listeners" here appends to "PLAINTEXT://${POD_IP}:9092,"
  "listener.security.protocol.map": PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
  #"listeners": PLAINTEXT://:19092,EXTERNAL://:31090
  #"inter.broker.listener.name": "PLAINTEXT"
  "advertised.listeners": 'EXTERNAL://${LOAD_BALANCER_IP}:31090'

I'm also add above private ip to client /etc/hosts
10.74.190.* dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka
10.93.128.* dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafka
10.209.242.* dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafka

kafkacat debug info
[root@CentOS1 ~]# docker run 168d762741a0 kafkacat -b kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092 -L -d broker
%7|1588124139.502|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1588124139.502|BROKER|rdkafka#producer-1| [thrd:app]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Added new broker with NodeId -1
%7|1588124139.502|CONNECT|rdkafka#producer-1| [thrd:app]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Selected for cluster connection: bootstrap servers added (broker has 0 connection attempt(s))
%7|1588124139.503|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v1.4.0 (0x10400ff) rdkafka#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,sasl_oauthbearer, GCC GXX INSTALL GNULD LDS LIBDL PLUGINS ZLIB SSL SASL_CYRUS HDRHISTOGRAM SYSLOG SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x2)
%7|1588124139.503|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
%7|1588124139.503|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
%7|1588124139.503|BRKMAIN|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Enter main broker thread
%7|1588124139.503|CONNECT|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Received CONNECT op
%7|1588124139.503|STATE|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1588124139.503|CONNECT|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: broker in state TRY_CONNECT connecting
%7|1588124139.503|STATE|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1588124139.505|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 47ms: application metadata request
%7|1588124139.505|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 47ms: application metadata request
%7|1588124139.642|CONNECT|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Connecting to ipv4#169.60.39.246:19092 (plaintext) with socket 7
%7|1588124139.691|CONNECT|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Connected to ipv4#169.60.39.246:19092
%7|1588124139.691|CONNECTED|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Connected (#1)
%7|1588124139.691|FEATURE|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1588124139.691|STATE|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1588124139.691|CONNECT|rdkafka#producer-1| [thrd:app]: Cluster connection already in progress: application metadata request
%7|1588124139.691|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
%7|1588124139.746|PROTOERR|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Protocol parse failure for ApiVersion v3 at 3/6 (rd_kafka_handle_ApiVersion:1909) (incorrect broker.version.fallback?)
%7|1588124139.746|PROTOERR|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: ApiArrayCnt -1 out of range
%7|1588124139.746|APIVERSION|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: ApiVersionRequest v3 failed due to UNSUPPORTED_VERSION: retrying with v0
%7|1588124139.798|FEATURE|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD,SaslAuthReq
%7|1588124139.798|STATE|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1588124139.852|BROKER|rdkafka#producer-1| [thrd:main]: dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092/0: Added new broker with NodeId 0
%7|1588124139.852|BRKMAIN|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092/0: Enter main broker thread
%7|1588124139.853|BROKER|rdkafka#producer-1| [thrd:main]: dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafka:9092/2: Added new broker with NodeId 2
%7|1588124139.853|BRKMAIN|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafka:9092/2: Enter main broker thread
%7|1588124139.853|BROKER|rdkafka#producer-1| [thrd:main]: dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafka:9092/1: Added new broker with NodeId 1
%7|1588124139.853|CLUSTERID|rdkafka#producer-1| [thrd:main]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: ClusterId update "" -> "srQPzd_1TTmwMu3Anzm9bw"
%7|1588124139.853|CONTROLLERID|rdkafka#producer-1| [thrd:main]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: ControllerId update -1 -> 0
%7|1588124139.853|BRKMAIN|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafka:9092/1: Enter main broker thread
%7|1588124139.904|DESTROY|rdkafka#producer-1| [thrd:app]: Terminating instance (destroy flags none (0x0))
%7|1588124139.904|DESTROY|rdkafka#producer-1| [thrd:main]: Destroy internal
%7|1588124139.905|DESTROY|rdkafka#producer-1| [thrd:main]: Removing all topics
%7|1588124139.905|DESTROY|rdkafka#producer-1| [thrd:main]: Sending TERMINATE to dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafka:9092/1
%7|1588124139.905|DESTROY|rdkafka#producer-1| [thrd:main]: Sending TERMINATE to dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafka:9092/2
%7|1588124139.905|DESTROY|rdkafka#producer-1| [thrd:main]: Sending TERMINATE to dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092/0
%7|1588124139.905|DESTROY|rdkafka#producer-1| [thrd:main]: Sending TERMINATE to kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap
%7|1588124139.905|TERM|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Received TERMINATE op in state UP: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1588124139.905|BROKERFAIL|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
%7|1588124139.905|FAIL|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Client is terminating (after 107ms in state UP)
%7|1588124139.905|STATE|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Broker changed state UP -> DOWN
%7|1588124139.905|TERMINATE|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: Handle is terminating in state DOWN: 1 refcnts (0x560d807f2460), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1588124139.905|BROKERFAIL|rdkafka#producer-1| [thrd:kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.clo]: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
%7|1588124139.906|TERM|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Received TERMINATE op in state INIT: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1588124139.906|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1588124139.906|FAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Client is terminating (after 403ms in state INIT)
%7|1588124139.906|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> DOWN
%7|1588124139.906|TERMINATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Handle is terminating in state DOWN: 1 refcnts (0x560d807f16b0), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1588124139.906|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1588124139.906|TERM|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafka:9092/1: Received TERMINATE op in state INIT: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1588124139.906|BROKERFAIL|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafka:9092/1: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1588124139.906|FAIL|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafka:9092/1: Client is terminating (after 53ms in state INIT)
%7|1588124139.906|STATE|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafka:9092/1: Broker changed state INIT -> DOWN
%7|1588124139.906|TERMINATE|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafka:9092/1: Handle is terminating in state DOWN: 1 refcnts (0x7fefe0002e30), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1588124139.906|BROKERFAIL|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafka:9092/1: failed: err: Local: Broker handle destroyed: (errno: Success)
Metadata for all topics (from broker -1: kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092/bootstrap):
 3 brokers:
  broker 0 at dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092
  broker 2 at dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafka:9092
  broker 1 at dswgraylog-cp-kafka-1.dswgraylog-cp-kafka-headless.graylog-kafka:9092
 6 topics:
  topic "est" with 1 partitions:
    partition 0, leader 2, replicas: 2, isrs: 2
  topic "test" with 1 partitions:
    partition 0, leader 0, replicas: 0, isrs: 0
  topic "esbuat.sl.bluecloud.ibm.com-broker" with 1 partitions:
    partition 0, leader 0, replicas: 0, isrs: 0
  topic "__consumer_offsets" with 50 partitions:
    partition 0, leader 2, replicas: 2,0,1, isrs: 0,2,1
    partition 1, leader 0, replicas: 0,1,2, isrs: 0,2,1
    partition 2, leader 1, replicas: 1,2,0, isrs: 0,2,1
    partition 3, leader 2, replicas: 2,1,0, isrs: 0,2,1
    partition 4, leader 0, replicas: 0,2,1, isrs: 0,2,1
    partition 5, leader 1, replicas: 1,0,2, isrs: 0,2,1
    partition 6, leader 2, replicas: 2,0,1, isrs: 0,2,1
    partition 7, leader 0, replicas: 0,1,2, isrs: 0,2,1
    partition 8, leader 1, replicas: 1,2,0, isrs: 0,2,1
    partition 9, leader 2, replicas: 2,1,0, isrs: 0,2,1
    partition 10, leader 0, replicas: 0,2,1, isrs: 0,2,1
    partition 11, leader 1, replicas: 1,0,2, isrs: 0,2,1
    partition 12, leader 2, replicas: 2,0,1, isrs: 0,2,1
    partition 13, leader 0, replicas: 0,1,2, isrs: 0,2,1
    partition 14, leader 1, replicas: 1,2,0, isrs: 0,2,1
    partition 15, leader 2, replicas: 2,1,0, isrs: 0,2,1
    partition 16, leader 0, replicas: 0,2,1, isrs: 0,2,1
    partition 17, leader 1, replicas: 1,0,2, isrs: 0,2,1
    partition 18, leader 2, replicas: 2,0,1, isrs: 0,2,1
    partition 19, leader 0, replicas: 0,1,2, isrs: 0,2,1
    partition 20, leader 1, replicas: 1,2,0, isrs: 0,2,1
    partition 21, leader 2, replicas: 2,1,0, isrs: 0,2,1
    partition 22, leader 0, replicas: 0,2,1, isrs: 0,2,1
    partition 23, leader 1, replicas: 1,0,2, isrs: 0,2,1
    partition 24, leader 2, replicas: 2,0,1, isrs: 0,2,1
    partition 25, leader 0, replicas: 0,1,2, isrs: 0,2,1
    partition 26, leader 1, replicas: 1,2,0, isrs: 0,2,1
    partition 27, leader 2, replicas: 2,1,0, isrs: 0,2,1
    partition 28, leader 0, replicas: 0,2,1, isrs: 0,2,1
    partition 29, leader 1, replicas: 1,0,2, isrs: 0,2,1
    partition 30, leader 2, replicas: 2,0,1, isrs: 0,2,1
    partition 31, leader 0, replicas: 0,1,2, isrs: 0,2,1
    partition 32, leader 1, replicas: 1,2,0, isrs: 0,2,1
    partition 33, leader 2, replicas: 2,1,0, isrs: 0,2,1
    partition 34, leader 0, replicas: 0,2,1, isrs: 0,2,1
    partition 35, leader 1, replicas: 1,0,2, isrs: 0,2,1
    partition 36, leader 2, replicas: 2,0,1, isrs: 0,2,1
    partition 37, leader 0, replicas: 0,1,2, isrs: 0,2,1
    partition 38, leader 1, replicas: 1,2,0, isrs: 0,2,1
    partition 39, leader 2, replicas: 2,1,0, isrs: 0,2,1
    partition 40, leader 0, replicas: 0,2,1, isrs: 0,2,1
    partition 41, leader 1, replicas: 1,0,2, isrs: 0,2,1
    partition 42, leader 2, replicas: 2,0,1, isrs: 0,2,1
    partition 43, leader 0, replicas: 0,1,2, isrs: 0,2,1
    partition 44, leader 1, replicas: 1,2,0, isrs: 0,2,1
    partition 45, leader 2, replicas: 2,1,0, isrs: 0,2,1
    partition 46, leader 0, replicas: 0,2,1, isrs: 0,2,1
    partition 47, leader 1, replicas: 1,0,2, isrs: 0,2,1
    partition 48, leader 2, replicas: 2,0,1, isrs: 0,2,1
    partition 49, leader 0, replicas: 0,1,2, isrs: 0,2,1
  topic "_confluent-metrics" with 12 partitions:
    partition 0, leader 1, replicas: 1,0,2, isrs: 0,2,1
    partition 1, leader 0, replicas: 0,2,1, isrs: 0,2,1
    partition 2, leader 2, replicas: 2,1,0, isrs: 0,2,1
    partition 3, leader 1, replicas: 1,2,0, isrs: 0,2,1
    partition 4, leader 0, replicas: 0,1,2, isrs: 0,2,1
    partition 5, leader 2, replicas: 2,0,1, isrs: 0,2,1
    partition 6, leader 1, replicas: 1,0,2, isrs: 0,2,1
    partition 7, leader 0, replicas: 0,2,1, isrs: 0,2,1
    partition 8, leader 2, replicas%7|1588124139.912|TERM|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092/0: Received TERMINATE op in state INIT: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1588124139.912|BROKERFAIL|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092/0: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1588124139.912|FAIL|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092/0: Client is terminating (after 61ms in state INIT)
%7|1588124139.912|STATE|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092/0: Broker changed state INIT -> DOWN
%7|1588124139.912|TERMINATE|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092/0: Handle is terminating in state DOWN: 1 refcnts (0x7fefe0001080), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1588124139.912|BROKERFAIL|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092/0: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1588124139.913|TERM|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafka:9092/2: Received TERMINATE op in state INIT: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1588124139.913|BROKERFAIL|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafka:9092/2: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1588124139.913|FAIL|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafka:9092/2: Client is terminating (after 60ms in state INIT)
%7|1588124139.913|STATE|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafka:9092/2: Broker changed state INIT -> DOWN
%7|1588124139.913|TERMINATE|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafka:9092/2: Handle is terminating in state DOWN: 1 refcnts (0x7fefe0001fb0), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1588124139.913|BROKERFAIL|rdkafka#producer-1| [thrd:dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafk]: dswgraylog-cp-kafka-2.dswgraylog-cp-kafka-headless.graylog-kafka:9092/2: failed: err: Local: Broker handle destroyed: (errno: Success)
: 2,1,0, isrs: 0,2,1
    partition 9, leader 1, replicas: 1,2,0, isrs: 0,2,1
    partition 10, leader 0, replicas: 0,1,2, isrs: 0,2,1
    partition 11, leader 2, replicas: 2,0,1, isrs: 0,2,1
  topic "__confluent.support.metrics" with 1 partitions:
    partition 0, leader 0, replicas: 0, isrs: 0

Any idea or suggestion? Thanks In Advance!!
Levi

**Comment by edenhill** [comment]
What is the actual problem you are seeing?
You seem to be getting the cluster metadata successfully.

`Local: Broker handle destroyed: ` is a debug log that is emitted when the client is being terminated, nothing to worry about.

**Comment by bjlvfei** [comment]
Hi @edenhill 

there one issue when I'm producer or consumer test message from test topic as below
kafkacat -b kafka.dsw-dia-dataflow-877236.us-south.containers.appdomain.cloud:19092 -L  -t test -C
% ERROR: Local: Host resolution failure: dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092/0: Failed to resolve 'dswgraylog-cp-kafka-0.dswgraylog-cp-kafka-headless.graylog-kafka:9092': nodename nor servname provided, or not known (after 177ms in state CONNECT)

I'm not sure why the nodename nor servername was not know.

Levi
Thanks!

**Comment by edenhill** [comment]
That is probably an advertised.listener as reported by the broker itself, see https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by bjlvfei** [comment]
I will check this article. Thank you
