### ISSUE TITLE
producer's qps decrease when topic's partitions increase or decrease from default num.partitions

### ISSUE THREAD

**Issue by h-zh-cn** [edenhill/librdkafka#2855]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>
producer's qps decrease when topic's partitions increase or decrease from default num.partitions

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>
kafka server.properties: num.partitions=6
![image](https://user-images.githubusercontent.com/46153728/80560388-4da6a500-8a13-11ea-951e-652bc424c1d4.png)

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [v1.3.0] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [0.11.0] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ default] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ Ubuntu 16.04.2 LTS] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
What is the record size?
How many brokers are the partitions on?
What hardware/instance type are you running the client on? How many cores/vcpus?

**Comment by h-zh-cn** [comment]
I have some errors in my operation, partitions=3 is new topic，that is the reasons why partitions = 3 is slower than 6 and 12;

I create three new topic with partitions 3、6、12，the results show that More Partitions May Increase End-to-end Latency, just as 'https://github.com/edenhill/librdkafka/commit/14000812c06195fbefcb6ba9b983a762c611df4a#diff-ab78e771fd78692a15ed791e0269a2db' said.

And, I find the reason why produce speed so low is that  'Change producer default to acks=all',
'https://github.com/edenhill/librdkafka/commit/14000812c06195fbefcb6ba9b983a762c611df4a'

I no longer have any questions, thanks
