### ISSUE TITLE
How to solve data duplication

### ISSUE THREAD

**Issue by ZhangchengHu0923** [edenhill/librdkafka#2857]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

As far as I know, when the two data primary keys are the same, ClickHouse may retain them for a period of time. When Kafka auto commit is used, if Kafka consumer restarts, data may be duplicated. So ClickHouse Kafka Engine Table should also have this problem, how should this problem be treated?

Description
===========

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I think this is more of a question for the ClickHouse community.

**Comment by ZhangchengHu0923** [comment]
ok,thx




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Magnus Edenhill"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月29日(星期三) 下午4:03
收件人:&nbsp;"edenhill/librdkafka"<librdkafka@noreply.github.com&gt;;
抄送:&nbsp;"唐"<2410753379@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [edenhill/librdkafka] How to solve data duplication (#2857)





 
I think this is more of a question for the ClickHouse community.
