### ISSUE TITLE
How does client (producer) determine it can send the messages out in the internal queue?

### ISSUE THREAD

**Issue by yhsiung** [edenhill/librdkafka#2863]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I saw so many -192 local msg_timed_out errors from the message delivery callback. You mentioned in other threads, this might be caused due to leader is not available or the connection to the brokers were broken. I have some questions which need your clarification as below.

1. Who (producer or broker) decides number of partitions for the topic? If it is configurable parameter, which API should be used? What is the default value?

2. What conditions (e.g., connection, leader availability, batch count, linger ms etc.) that client code will be based on to determine the messages in the internal queue can be sent to brokers?

3. What conditions (e.g., message.timeout.ms, missing ACK from broker etc.) that client code will remove the messages from internal queue and call the message delivery callback?

4. Does the local msg_timed_out (-192) always mean that the messages never been sent by client? Is it possible that the messages have been sent but eventually got the msg_timed_out due to no ACK received from brokers?

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.6
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
1. The number of partitions for a topic is defined at topic creation time, which may be auto-created (in which case the broker's default num.partitions is used) or manually created with the AdminAPI CreateTopics() in which case the partition count is manually set.
 Partitions may also be added a later time with the AdminAPI CreatePartitions call.
 2. Queued messages will be sent when the leader for a partition is known and the connection to the leader broker is up.
 3. Message timeout, permanent broker error, topic being removed.
 4. It depends, and there is a message_status() API to check the persistance status of a message.

More info in the manual:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-reliability
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-persistence-status
