### ISSUE TITLE
feedback on the erland binding for librdkafka

### ISSUE THREAD

**Issue by silviucpp** [edenhill/librdkafka#2866]
Hello,

I'm the author of https://github.com/silviucpp/erlkaf and I want to improve the design of my erlang binding for librdkafka and I need your expertise to clarify some of my concerns.

On consumer side right now I have a design as follow:

- Each topic and partition it's handled by an erlang process. In background each erlang process works with the native queue from `rd_kafka_queue_get_partition`. Of course I'm also calling `rd_kafka_queue_forward` to remove the queue forwarding on the main queue.
- The erlang processs calls `rd_kafka_queue_poll` on a regular basis on it's partition queue that owns. In case no events are returned it waits 100 ms before calling it again. So far I don't see any problem with this.

My problem is that each consumer group also creates a native thread where I'm calling `rd_kafka_consumer_poll` time to time for getting rebalance events and whatever else might be in the main queue.

I want to switch to a single thread that calls `rd_kafka_consumer_poll` for all the consumers groups inside the driver. 

My plan is to integrate `rd_kafka_queue_io_event_enable` and when a main queue is signaled to call `rd_kafka_consumer_poll` on that queue.

My questions are :

**A**. When a read event is signaled on a queue, and I'm calling `rd_kafka_consumer_poll` on that queue, I can safely assume that all events in the queue were processed and queue is empty and next poll on the file descriptor will be triggered again when queue has events ?

My concern is related to the fact that `rd_kafka_queue_io_event_enable` will notify only when a queue is going from 0 to N events. So if `rd_kafka_consumer_poll` won't consume all pending events, a notification won't be triggered again.

**B**. Also documentation says `rd_kafka_consumer_poll` should be called at least once per max.poll.interval.ms . In my case where queues are individually polled using `rd_kafka_queue_poll` (and are not forwarded to the main queue) I still need to call `rd_kafka_consumer_poll` at least once in that interval ?

Silviu

**Comment by edenhill** [comment]
Good work on the Erlang bindings!

Switching to a single consume queue sounds like a good option since this is more in line with the standard use and less likely to hit corner cases.

 A. Yes, unless you call rd_kafka_yield().
 B. queue_poll() will also reset the max.poll timeout, so it should be fine.

**Comment by silviucpp** [comment]
Thanks a lot for the feedback ! I also tested and saw what you are confirming now. 

Silviu
