### ISSUE TITLE
what is the indication with partition -1

### ISSUE THREAD

**Issue by yhsiung** [edenhill/librdkafka#2875]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I saw lots of "sent xx bytes to topic xxxx partition -1" followed by "Message delivery failed: Local: Message timed out". What is the indication of partition -1? Why it caused the Local message timed out?

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag):  latest librdkafka.
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
If you produce to partition -1 (PARTITION_UA / unassigned) the producer will use the configured partitioner to select partition fort he message.
For the partitioner to run it needs to know the number of partitions in the topic, which it retrieves as soon as a cluster connection is made.

A Message timeout typically indicates the cluster is not available or the client is erroneously configured so it can't connect.
You can troubleshoot this further by setting the `debug` config property to `broker,topic,msg`

**Comment by yhsiung** [comment]
Please clarify the following client behavior:
1. By default, the client will randomly pick up one of to partitions based on the metadata response for sending each batch of messages.
2. The messages will be queued in the xmit queue.
3. The messages will be added to the randomly selected partition queue when the leader of the partition is in UP state, and send the messages to the partition leader.
4. If the partition leader's state is not UP, the messages will continue staying in the xmit queue until the message.timeout.ms expired. (assume the leader state is not changed to UP)

**Comment by edenhill** [comment]
1. If produce() is called with partition set to -1 (or RD_KAFKA_PARTITION_UA) the default or configured `partitioner` will select a partition based on the message key.
 2. As soon as a message is assigned a partition, and that partition has a leader broker, the message will be enqueued for batching and transmission
 3. Yep.
 4 Yep.

**Comment by yhsiung** [comment]
In case the randomly selected partition whose leader is not in "UP" state, is there a good reason why client code does not re-select another partition, which associates "UP" leader? Otherwise, all these messages eventually will be timed out. because the partition leader will be never "UP" due to some firewall issue along with the network path. Note: metadata contains all good information.

**Comment by edenhill** [comment]
A message will never change partition once a partition has been assigned, since this would jeopardise ordering.

The partitioners will attempt to select an available partition though.

**Comment by yhsiung** [comment]
One more question: what may trigger the RD_KAFKA_RESP_ERR__TRANSPORT error?

**Comment by edenhill** [comment]
The broker transport, namely the TCP connection, failed or is not available. This is an aggregate error for things like disconnects, connection refused, connection timed out, etc.
