### ISSUE TITLE
Please remove -lstdc++ flag from Makefiles and link using CXX

### ISSUE THREAD

**Issue by ryandesign** [edenhill/librdkafka#2878]
Description
===========
The flag `-lstdc++` appears in several places in the Makefiles. It should be removed. Not all systems use libstdc++. Some use libc++ instead.

OS X 10.9 and later use libc++ by default. OS X 10.8 and earlier use libstdc++ by default. In MacPorts, we've switched to using libc++ on Mac OS X 10.6-10.8. [Here is a build failure from 10.7](https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/23119/steps/install-port/logs/stdio). Note that we're correctly compiling the objects with clang++ and `-stdlib=libc++` (MacPorts adds this flag):

```
/usr/bin/clang++ -MD -MP -I/opt/local/include -gstrict-dwarf -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -pipe -Os -stdlib=libc++ -arch x86_64 -Wno-non-virtual-dtor -c RdKafka.cpp -o RdKafka.o
```

but that linking fails because it is linking with clang (not clang++) and it is specifying `-lstdc++` (this comes from your Makefiles):

```
/usr/bin/clang -Wl,-headerpad_max_install_names -L../src -L/opt/local/lib -arch x86_64 -shared -dynamiclib -Wl,-install_name,/opt/local/lib/librdkafka++.1.dylib RdKafka.o ConfImpl.o HandleImpl.o ConsumerImpl.o ProducerImpl.o KafkaConsumerImpl.o TopicImpl.o TopicPartitionImpl.o MessageImpl.o HeadersImpl.o QueueImpl.o MetadataImpl.o -o librdkafka++.1.dylib -L../src -lrdkafka -lstdc++
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare(char const*) const", referenced from:
      RdKafka::ConfImpl::set(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, RdKafka::DeliveryReportCb*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in ConfImpl.o
      RdKafka::ConfImpl::set(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, RdKafka::OAuthBearerTokenRefreshCb*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in ConfImpl.o
```

To fix this, link with `$(CXX)` (not `$(CC)`) and don't attempt to link with a C++ standard library (let the C++ compiler do it for you, influenced by the `-stdlib` flag that MacPorts puts in CXXFLAGS and can optionally put in LDFLAGS if you don't use CXXFLAGS when linking).

How to reproduce
================
On Mac OS X 10.7 with MacPorts, `sudo port install librdkafka`

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.4.2`
 - [ ] Apache Kafka version: `n/a`
 - [ ] librdkafka client configuration: `n/a`
 - [X] Operating system: `Mac OS X 10.7`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks for the great report, will address this in the upcoming v1.5.0 release

**Comment by edenhill** [comment]
Please review #2882
