### ISSUE TITLE
How to set producer configuration dynamically

### ISSUE THREAD

**Issue by sreeni89** [edenhill/librdkafka#2883]
Description
===========

How to set producer configuration (both global & topic)  dynamically  ?

 kafkaGLobalConf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
 kafkaTopicConf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

**Comment by edenhill** [comment]
What do you mean dynamically?

**Comment by sreeni89** [comment]
I have initialized "batch.num.messages" value to 1 and passed it to producer create API.

kafkaGLobalConf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);

confResult = kafkaGLobalConf->set("batch.num.messages", 1, errstr);

producer = RdKafka::Producer::create(kafkaGLobalConf, errstr);

After producer is created I am trying to change "batch.num.messages" to '10' but not found the way to modify the value.

**Comment by edenhill** [comment]
There is no way to modify a client instance's configuration after construction.

**Comment by sreeni89** [comment]
ok, thanks for the clarification.
