### ISSUE TITLE
`rdkafka_mock.h` does not check for c++ compiler

### ISSUE THREAD

**Issue by mpribble** [edenhill/librdkafka#2885]
Description
===========
`rdkafka_mock.h` does not check if it is being compiled with a c++ compiler.

How to reproduce
================
Include `rdkafka_mock.h` in a c++ program. In the program, use one or more the mock functions (in my case, `rd_kafka_handle_mock_cluster()` and `rd_kafka_mock_cluster_bootstraps()`). Compile the program using a c++ compiler (I used clang), linking against `librdkafka`

This will result in undefined reference link errors. This is because the c++ compiler mangles the names of the symbols it included from `rdkafka_mock.h`, but the c compiler that built `librdkafka` does not.

A workaround (which I am using), is to  wrap the include of `rdkafka_mock.h` in `extern "C" {...}`. I.e.,

`extern "C" {  #include "rdkafka_mock.h" }`

This works of course, but I think it would be better if `rdkafka_mock.h` does this conditionally based on compiler in the same way `rdkafka.h` does.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.4.2`
 - [x] Apache Kafka version: N/A
 - [x] librdkafka client configuration: N/A
 - [x] Operating system: N/A
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka N/A
 - [x] Provide broker log excerpts N/A
 - [ ] Critical issue: No - this is low priority

**Comment by edenhill** [comment]
Aight, care to file a PR that copies what rdkafka.h does?

**Comment by mpribble** [comment]
yeah sure, shouldn't be a problem.

**Comment by mpribble** [comment]
Well, that was actually my first ever PR on github. Hopefully I did it right.

**Comment by edenhill** [comment]
:tada: you did!
