### ISSUE TITLE
Incremental Rebalance Roadmap?

### ISSUE THREAD

**Issue by codeburke** [edenhill/librdkafka#2886]
I've been catching up on the latest Kafka improvements and the KIP-429 (Incremental Rebalance Protocol) seems to be a major improvement for people who have frequent changes to their consumer group. I was wondering if there was any roadmap to supporting KIP-429 in librdkafka?

Keep up the good work!

**Comment by mhowlett** [comment]
yep, it's underway: https://github.com/edenhill/librdkafka/pull/2884 

you can follow progress on the `incrreb` branch.
