### ISSUE TITLE
CPU 100% for librdkafka-1.2.2

### ISSUE THREAD

**Issue by rola-zhang** [edenhill/librdkafka#2889]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
CPU 100%

stack:
![image](https://user-images.githubusercontent.com/65419195/82086817-f277e200-96a3-11ea-9a4c-e62fdb1f317e.png)

How to reproduce
================
I don't clear due to run at production.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<1.2.2>`
 - [ ] Apache Kafka version: `<don't clear>`
 - [x] librdkafka client configuration: `<security.protocol=sasl_ssl, sasl.mechanism=PLAIN, others use default>`
 - [x] Operating system: `<centos 7.5>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Would need some sort of profiling to understand where it is spending time, a single gdb backtrace might not be representative of the hot spots.

Please also provide information on your produce-rate, number of partitions, brokers, etc.

**Comment by rola-zhang** [comment]
I only used it as a light-weight producer. When launching it, it seems all are OK. You can see the screenshot, the connection was broken when the issue happened. produce-rate is lower that 200K bytes/s. I use RD_KAFKA_PARTITION_UA as partition parameter. There are two brokers. I don't understand number of vcores. 

Now I keep one issue machine. If you want more stack info, I will copy it here. Thanks

**Comment by edenhill** [comment]
My guess is `linger.ms` is left at its default 0.5ms value which results in small batches, large overhead, and increased CPU usage.
Try setting `linger.ms` to your maximum allowed producer latency, e.g, 50-100ms, and see if it helps?

**Comment by rola-zhang** [comment]
Thank you. I will try it and feedback here.

**Comment by edenhill** [comment]
Most likely the SSL handshake CPU busy loop fixed in #3363
