### ISSUE TITLE
Doubt- simulating m producers X n consumers

### ISSUE THREAD

**Issue by prabcs** [edenhill/librdkafka#289]
Hi,

While evaluating Kafka using librdkafka, I've felt the need of benchmarking it using m producers vs n consumers
Please pour in your thoughts on it
Can the performance binary be used somehow?

**Comment by prabcs** [comment]
Hi,

Please share your thoughts on this

**Comment by edenhill** [comment]
rdkafka_performance would be a suitable tool for that, just fire up any number of instances.
It might be useful to the use the `-r <rate_msgs/s>` switch on the producers.
While the rate limiting is a bit coarse it allows some control of the message rate.

One thing to note about performance measurements on Kafka is that produce performance is typically pretty steady over time, with the occassional dip when file system caches are written do disk.

The way consumption is implemented in Kafka brokers is that it maps the incoming logical partition Offset to a byte offset in one of the spool files and then sendfile(2) is used to transfer spool file contents to the TCP connection. This is zero-copy and very fast, but the latency and throughput of such a request will vary greatly depending on if the requested portion of the spool file is in the disk cache (very fast) or if it needs to read from disk (disk access and read speed times (also SSD vs HDD)).
Keep this in mind when you do consumer performance testing, there will be differences depending on your producer behaviour -> are requested data in disk caches or not?
