### ISSUE TITLE
Memory usage grows when nothing is done after rd_kafka_t object is created

### ISSUE THREAD

**Issue by davideberra** [edenhill/librdkafka#2890]
Description
===========
It seems like memory usage of the library keeps growing if nothing is done after connection creation.

How to reproduce
================
* create rd_kafka_conf_new object and fill it with parameters listed below 
* creates new rd_kafka_t object as PRODUCER 
* stay forever in a loop like this:

`while (1) sleep(10);`

* observe process RSS slowly growing forever

Checklist
=========

 - [x] librdkafka: `1.4.2`
 - [x] Apache Kafka version: `2.0.0`
 - [x] librdkafka client configuration: `enable.idempotence=true; retry.backoff.ms=100; max.in.flight.requests.per.connection=1; api.version.request=false; broker.version.fallback=2.1.1; linger.ms=0; batch.num.messages=10000; queue.buffering.max.messages=; message.max.bytes=10000; statistics.interval.ms=60; debug=all;`
 - [x] Operating system: `CentOS 7 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You need to call poll() to serve the event queue, your high frequency stats are accumulating on the queue now.
