### ISSUE TITLE
build error with Visual Studio 2019

### ISSUE THREAD

**Issue by mikeyqin** [edenhill/librdkafka#2896]
Description
===========
including header rd.h causes build error on Windows using Visual Studio 2019. The compiler complains the following line:
https://github.com/edenhill/librdkafka/blob/master/src/rd.h#L148
char *n = malloc(len + 1);
C2440 'initializing': cannot convert from 'void *' to 'char *' 

This happens in branch 1.4.2 as well.

**Comment by edenhill** [comment]
Thank you, fix soon merged to master.

Can you change that line to `char *n = (char *)malloc(len + 1);` and see if you get any other compile errors that we can fix at the same time?

**Comment by mikeyqin** [comment]
That works. No more build errors. Thanks!
