### ISSUE TITLE
hang on sequential termination of 2 consumers with NoConsumerClose

### ISSUE THREAD

**Issue by filimonov** [edenhill/librdkafka#2898]
Description
===========
librdkafka hangs on sequential termination of 2 consumers.
Both consumers consumer the same topic. Rebalance happen (between them) just before destroy. 

Hangs with that message:
```
 terminating: broker still has 2 refcnt(s), 0 buffer(s), 0 partition(s)
```

How to reproduce
================
The sequence is like follow

consumer1 subcribe ( topic1 )
consumer1 rd_kafka_consume_batch_queue  ()
consumer1 subcribe ( topic1  )

consumer2 subcribe ( topic1 )
consumer2 rd_kafka_consume_batch_queue ()
consumer2 subcribe ( topic1  )

consumer1 close 
consumer1 destoy ( with NoConsumerClose) 

consumer2 close 
consumer1 destoy ( with NoConsumerClose) 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.4.2
 - [x] Apache Kafka version: 5.2.0
 - [x] librdkafka client configuration: 
```
    conf.set("metadata.broker.list", brokers);
    conf.set("group.id", group);
    conf.set("client.id", VERSION_FULL);
    conf.set("auto.offset.reset", "smallest");
    conf.set("enable.auto.commit", "false");
    conf.set("enable.auto.offset.store", "false");
    conf.set("enable.partition.eof", "false");
```
 - [x] Operating system: Ubuntu 18 in docker
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
See https://gist.github.com/filimonov/ccf587c8edeb5e3e69599261f55bc023
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Are you sure that you have destroyed all other objects, such as Messages and Topics, prior to calling close()?

**Comment by filimonov** [comment]
I'm sure.

**Comment by gridaphobe** [comment]
I've recently run into what appears to be the same issue (in v1.4.2 and v1.5.0). I have two consumers in the same group, shut them down sequentially, and sometimes the second consumer hangs inside `rd_kafka_destroy()` while the broker threads (sometimes one, sometimes multiple) spew the following log:

```
Handle is terminating in state INIT: 3 refcnts (0x2265850), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
```

(the number of remaining refcnts is also nondeterministic)

I've never been able to trigger the issue while running a single consumer, so it does seem relevant that there are multiple consumers involved.

I observed this in the context of an internal wrapper library we have, I'll try to put together a repro against vanilla librdkafka.

**Comment by edenhill** [comment]
I think we sorted out a bunch of these with the consumer rewrite in v1.6.0

Reopen if you're still seeing this on modern releases.
