### ISSUE TITLE
the configure script does not work correctly when configuration is like "--LDFLAGS='-Wl,--build-id=none'"

### ISSUE THREAD

**Issue by sky92zwq** [edenhill/librdkafka#2900]
Description
===========
`./configure --LDFLAGS='-Wl,--build-id=none'`

there are two '=' in a configuration, then ` name="${opt%=*}"` will Intercept `LDFLAGS=-Wl,--build-id` as `name`. 

so ` name="${opt%%=*}"`may be a good choice to Intercept LDFLAGS out.

How to reproduce
================
some configurations within `--LDFLAGS='-Wl,--build-id=none` can reproduce.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.3.0 v1.1.0`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thank you!
