### ISSUE TITLE
Whether librdkafka can be compiled with Visual Studio 2010？

### ISSUE THREAD

**Issue by lnsycmy** [edenhill/librdkafka#2906]
Hi,
Is it possible to use the librdkafka library in VS2010, and if so, what is the method of build?

* I want to use `librdkafka` dynamic link library in VS2010，but cannot open `librdkafka.sln` in VS2010 to compiled.
* I try to open `librdkafka.sln` in VS2015 and changed platform toolset from `Visual Studio 2015 (v140)` to `Visual Studio 2010 (v100)`, although the build can be completed, it cannot be run in the VS2010 project.

- [x] librdkafka version: v1.4.0.

**Comment by edenhill** [comment]
I don't have any experience with VS2010. I use VS2015 for librdkafka development.
Since VS2010 is over 10 years old we will not put any effort into supporting it.
