### ISSUE TITLE
Release tag 1.4.2 commit history diverged from master branch

### ISSUE THREAD

**Issue by iradul** [edenhill/librdkafka#2910]
The current release tag [1.4.2](https://github.com/edenhill/librdkafka/releases/tag/v1.4.2) has commit hash `b0d91bd` which is nowhere to be found on the master branch. It seems like a good chunk of the latest commit history doesn't match master branch at all. I'm wondering what's the reason for this and will this become a new norm?

**Comment by edenhill** [comment]
We try to avoid maintaining multiple release branches, but we needed to release a couple of hot-fix releases for 1.4.x so we created a 1.4.x branch that these are based off, with commits cherry-picked from master.

**Comment by iradul** [comment]
Thanks!
