### ISSUE TITLE
Got "Broker: Offset out of range" when producing message

### ISSUE THREAD

**Issue by davideberra** [edenhill/librdkafka#2918]
Description
===========
Scenario:
I have one producer that sets up a persistent connection with kafka brokers.
It may work correctly for days, then, it happens to receive an RD_KAFKA_RESP_ERR_OFFSET_OUT_OF_RANGE when calling rd_kafka_produce.

From that moment onward, calling rd_kafka_produce returns always RD_KAFKA_RESP_ERR_OFFSET_OUT_OF_RANGE.

Destroy and recreate rd_kafka_topic_t wont help.

The weird thing is that offset should be a consumer thing AFAIK. Maybe is something tied to idempotence in case of producer?

Update: When the process has been terminated, rd_kafka_flush made the produce callback get called with rd_kafka_resp_err_t field set to RD_KAFKA_RESP_ERR_UNKNOWN_PRODUCER_ID

Don't know if useful but i also have a lot of log like this:

`PID has changed: must drain requests for all partitions before resuming reset of PID`

How to reproduce
================
- i would like to know if you have idea about how to reproduce it. Unfortunally it happened just twice and i don't know why

Checklist
=========

 - [x] librdkafka-1.2.2
 - [x] Apache Kafka version: 2.0.0
 - [x] librdkafka client configuration: `enable.idempotence=true; retry.backoff.ms=100; max.in.flight.requests.per.connection=1; api.version.request=false; broker.version.fallback=2.1.1; linger.ms=0; batch.num.messages=10000; queue.buffering.max.messages=; message.max.bytes=10000; statistics.interval.ms=60; debug=all; `
 - [x] Operating system: `CentOS 7 x64`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Interesting, I see you have debug enabled, is there a log file you can share?

**Comment by davideberra** [comment]
[librdkafka.zip](https://github.com/edenhill/librdkafka/files/4735320/librdkafka.zip)

Log attached. It's the last day of the process involved.

Another info that might be useful to you: No data was pushed to involved topics for weeks and probably (certainly?) they had 100% data deleted due to retention policies (default brokers retention is set to 7 days).

**Comment by edenhill** [comment]
> No data was pushed to involved topics for weeks

So this error occurred when the producer tried producing data again after a long idle period?

**Comment by davideberra** [comment]
> > No data was pushed to involved topics for weeks
> 
> So this error occurred when the producer tried producing data again after a long idle period?

Yes, exactly

**Comment by edenhill** [comment]
It also looks like TOPICNAME_ONE had been deleted and was re-created (by auto create) at 12:08:23, does that seem likely?

**Comment by edenhill** [comment]
Scratch that, TOPICNAME_ONE seems to be stuck in a partition and leader-less state:
`debug Jun  3 11:28:23 hostname producer_process[5278]: (Ctype) RDKAFKA - 7-METADATA: rdkafka#producer-1: [thrd:main]: kafka3.domain:9092/3:   Topic #2/3: TOPICNAME_ONE with 0 partitions: Broker: Leader not available`

Do you know why that might be?

**Comment by davideberra** [comment]
> Scratch that, TOPICNAME_ONE seems to be stuck in a partition and leader-less state:
> `debug Jun 3 11:28:23 hostname producer_process[5278]: (Ctype) RDKAFKA - 7-METADATA: rdkafka#producer-1: [thrd:main]: kafka3.domain:9092/3: Topic #2/3: TOPICNAME_ONE with 0 partitions: Broker: Leader not available`
> 
> Do you know why that might be?

TOPICNAME_ONE might be deleted by an automated process. Anyway, the produce fails are tied to TOPICNAME_THREE. If you search for lines starting with "err " you can get exactly where last attempts were made.

**Comment by davideberra** [comment]
Further infos: 

in case of **RD_KAFKA_RESP_ERR_OFFSET_OUT_OF_RANGE**, `rd_kafka_produce` returned -1 and the error was retrieved with `rd_kafka_resp_err_t resp_err = rd_kafka_last_error();`

**Comment by edenhill** [comment]
That OFFSET_OF_RANGE last_error is weird, it should not be reported by the producer.
Are you using a consumer in the same thread?

**Comment by davideberra** [comment]
No consumer is running on the same thread. No consumer is running at all on the server.
Just to be sure, here's the snippet of the rd_kafka_produce call:

    produce:

    if (rd_kafka_produce(
                         k->topic,
                         0,
                         RD_KAFKA_MSG_F_COPY,
                         buf, sz,
                         key, key_sz,
                         &err) == -1) {

        rd_kafka_resp_err_t resp_err = rd_kafka_last_error();

        if (resp_err == RD_KAFKA_RESP_ERR__QUEUE_FULL) {
            rd_kafka_poll(conn, 1000);
            goto produce;
        } else {
            log_write(LOG_ERR, "Error returned by rd_kafka_produce: %s",
                               rd_kafka_err2str(resp_err));
            return 1;
        }
    }

**Comment by edenhill** [comment]
This is a bug which was fixed in librdkafka v1.4.0: https://github.com/edenhill/librdkafka/commit/18882875af641dcf22ea58ddfabfd76007769533#diff-1057ff10d16a12ea9d5ef68e83274e13L645
