### ISSUE TITLE
librdkafka and dynamic libraries missing

### ISSUE THREAD

**Issue by jedzme** [edenhill/librdkafka#2919]
Hi,

Im trying to build librdkafka to support sasl_ssl connection.
I used confluent-kafka-go v0.11.6 since I have a problem with the latest version.
We're trying to deploy our application on AWS lambda, and it somehow wont allow us from installing dependencies via apt-get, so the only way that I could think of is upload whatever dependency needed together with the project executable file.

So these are my steps: (Note: I am building locally the librdkafka)
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

1. I installed the libsasl2-dev dependencies on my local: I followed the instructions here: https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka
through running this command: sudo apt-get install libsasl2-modules-gssapi-mit libsasl2-dev

2. Build librdkafka on my local: I followed the instructions here: https://github.com/edenhill/librdkafka

3. The ./configure showed me this log
using cache file config.cache
checking for OS or distribution... ok (ubuntu)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking executable libtool... failed (disable)
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x01050001'... ok (1.5.0)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for c11threads (by pkg-config)... failed
checking for c11threads (by compile)... failed (disable)
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok
checking for zlib (by pkg-config)... failed
checking for zlib (by compile)... failed (disable)
checking for libcrypto (by pkg-config)... ok
checking for libssl (by pkg-config)... ok
checking for libsasl2 (by pkg-config)... ok
checking for libzstd (by pkg-config)... failed
checking for libzstd (by compile)... failed (disable)
checking for libm (by pkg-config)... failed
checking for libm (by compile)... ok
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for syslog (by compile)... ok
checking for rapidjson (by compile)... failed (disable)
checking for crc32chw (by compile)... ok
checking for regex (by compile)... ok
checking for strndup (by compile)... ok
checking for strlcpy (by compile)... failed (disable)
checking for strerror_r (by compile)... ok
checking for pthread_setname_gnu (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for python3 (by command)... ok
checking for getrusage (by compile)... ok
Generated Makefile.config
Generated config.h

4. I compressed/zipped the librdkafka.so.1 library together with the libcrypto.so.1.1 and libc.so.6, aand the executable deployment file then uploaded it to AWS lambda.

I bumped into this error:
 **/usr/lib64/libsasl2.so.2: no version information available (required by /var/task/librdkafka.so.1)
/lib64/libc.so.6: version `GLIBC_2.25' not found (required by /var/task/libcrypto.so.1.1)**

I think when deploying to lambda environment, it uploads the binaries to the /var/task folder of the environment. librdkafka and libcrypto are looking for  these two files the libsasl2.so.2 and libc.so.6.

I can't install these depencies via apt-get command, so I would like to upload them together with my librdkafka and libcrypto on the same folder.
Is it possible to change the location where they lookup these files on run time, if yes then how? which file should I modify before I re-compile my librdkafka.

**Comment by edenhill** [comment]
Your build system (ubuntu) and AWS Lambda do not have compatible libraries.
The easiest option is to build librdkafka in a docker container that is as close as possible to what the AWS Lambda linux container looks like, such as this:
https://hub.docker.com/r/lambci/lambda/

Also note that you only need libsasl2 if you're  using GSSAPI/Kerberos authentication.
The other SASL mechasnisms (PLAIN, SCRAM, OAUTHBEARER) are built-in with librdkafka, in which case you should remove libsasl2-dev from your build machine.
