### ISSUE TITLE
Doubt/Bug - '-B' option in rdkafka_performance

### ISSUE THREAD

**Issue by prabcs** [edenhill/librdkafka#292]
Hi,

I've noticed that using the following command, no matter what batch size (ranging from 1 to 300) I select using the -B option, the throughput does not vary much and the writes complete in around the same time. This is the command I've used:-

time ./rdkafka_performance -P -t temp4 -s <variable> -c 1048576  -b x.x.x.x:9092,y.y.y.y:9092,z.z.z.z:9092 -u -i 100 -B <variable>

I've tried running the same command with various values of -s ranging from 200 to 10240 and -c from 1048576 to 10485760 and -B from 1 to 300. But, I dont get much of a throughput variance with changes in -B option.
This observation is quite different from the results in the section 'producer throughput as a function of batch size' mentioned in http://kafka.apache.org/07/performance.html

Please provide some explanation on this observation.

**Comment by prabcs** [comment]
Hi,

Request you to share your thoughts on this

**Comment by edenhill** [comment]
First, in rdkafka_performance `-B ..` is a consumer property, not producer. 

Secondly, producer batching (e.g., sending multiple messages in the same ProduceRequest to the broker) is automatically performed under the hood in librdkafka. The `rd_kafka_produce_batch()` API does **NOT** correlate to those batches but are only a convenient high level API that allows enqueueing multiple messages in one API call (less locking & lookup overhead).

**Comment by prabcs** [comment]
Great. Thanks for the answer
