### ISSUE TITLE
Question: Querying Current offsets for other consumers through python API

### ISSUE THREAD

**Issue by JohnRGMorgan** [edenhill/librdkafka#2920]
Hello @edenhill, 

I'm currently using confluent_kafka python api and I'm wondering if there's a way to query the offsets of a partition without being the consumer that is consuming that partition.

Specifically I'm wondering if it's possible to bring up a consumer in the same topic and consumer group and query the offsets of specific/all partitions in that group.

This is a similar question to https://github.com/edenhill/librdkafka/issues/2838, however i'm using the python API and I couldn't find any method that could provide TopicPartitions to be used for the committed() method (There's no rd_kafka_metadata() for python).

Here is what I've looked into, I created a mimic consumer in the same consumer group but I do not subscribe as I don't want to re balance or consume messages:

- I have tried obtaining the ClusterMetadata from list_topics() and going down to the PartitionMetadata but I don't believe I can obtain offsets from it
- it seems if I create a TopicPartition with offset -1000 to get the current stored that doesn't give me the actual current stored offset from calling committed() with it
- Using assignment() also doesn't yield anything meaningful if I don't subscribe

From what I understand, I believe I'm looking for the TopicPartition to pass to committed() that stores the actual current offset, but i'm unsure where I can obtain that from.

Cheers

**Comment by edenhill** [comment]
Wrote up an example how to get committed offsets here:
https://github.com/confluentinc/confluent-kafka-python/pull/909/files#diff-9658f4d776ed9e51eb0d8d8720e4f35e
