### ISSUE TITLE
rd_kafka_conf_set() API question

### ISSUE THREAD

**Issue by adamkotwasinski** [edenhill/librdkafka#2922]
Do `rd_kafka_conf_set()` / `Conf::set(const std::string &name, const std::string &value, std::string &errstr)` copy values of (string) properties passed to them, or should they be kept alive as long as the configuration object exists?

**Comment by edenhill** [comment]
They are copied, will improve docs.

**Comment by adamkotwasinski** [comment]
Thank you!
