### ISSUE TITLE
Questions w.r.t rebalance_cb in librd kafka

### ISSUE THREAD

**Issue by dshivashankar1994** [edenhill/librdkafka#2923]
I have a high level consumer. I am planning to enhance this with the below things.

1. I'm planning to subscribe the topics. The topics may or may not be created. But once the topic is created, I'd like the consumer to receive the messages.
2. I need to make sure only one consumer per consumer group id. This is because, all the topics that are in use have only one partition. So if more than one consumer gets created, it has to get a fatal error and fail rather than waiting idle
3. If the user has specified 'beginning', I wanted to create a snapshot from the starting offset to the current offset and send it to the user in one go and then send the messages that are periodically published.
I thought I could use the rebalance_cb and implement all the above things. Please correct me if I am wrong.

If correct, I'd like to know few things, 
1. For the case 2, in what all cases is the rebalance_cb is called ? Will it be called multiple times in a single subscribe itself ? 
2. Reg 3, when exactly is the rebalance cb called ? If this is called only during poll, my code might not work correctly for non-existent topic.

**Comment by edenhill** [comment]
1. That will work today, a newly created topic will be detected within `topic.metadata.refresh.interval.ms`.
 2. You could create a rebalance_cb() that asserts if you get an empty assignment (meaning some other consumer got the single partition available).

**Comment by dshivashankar1994** [comment]
```
 LOG_INFORMATION(myLogger, "Rebalance callback called with " << partitions.size() << " partition(s).");
    if (err == RdKafka::ERR__ASSIGN_PARTITIONS) {
        if (partitions.size() == 0) {
            throw KafkaException("Partitions not assigned to consumer");
        }
        for (auto& partition : partitions) {
            LOG_INFORMATION(myLogger, "Rebalance callback called with topic" << partition->topic());
            if (offsetSeeked.count(partition->topic()) == 0) {
                LOG_INFORMATION(myLogger, "Rebalance callback called with topic 12" << partition->topic());
                switch (myOffsetPosition) {
                case OffsetPosition::beginning:
                    partition->set_offset(RdKafka::Topic::OFFSET_BEGINNING);
                    break;
                case OffsetPosition::end:
                    partition->set_offset(RdKafka::Topic::OFFSET_END);
                    break;
                case OffsetPosition::stored:
                default:
                    partition->set_offset(RdKafka::Topic::OFFSET_STORED);
                    break;
                }
                offsetSeeked.insert(partition->topic());
            }
        }
        consumer->assign(partitions);
    }
    else if (err == RdKafka::ERR__REVOKE_PARTITIONS) {
        consumer->unassign();
    }
    else {
        LOG_ERROR(myLogger, "Rebalancing error: " << RdKafka::err2str(err));
    }
}
```
I have the above rebalance cb implemented. I am using a single consumer and all the topics are with single partition. The problem is, when i subscribe to existing + non-existing topics (a, b) with the offset as "beginning", the topic a receives all the messages in topic "a". Now when b gets created and the producer has produced 10 messages after which the meta-data-refresh happened. Now rebalance cb is called and the producer has produced 10 more messages in topic "b". The consumer receives only those messages that were published after the rebalance cb ie, last 10 messages.

**Comment by dshivashankar1994** [comment]
Thanks for your answer
