### ISSUE TITLE
Schema registry support question

### ISSUE THREAD

**Issue by SleepyBearDad** [edenhill/librdkafka#2927]
Hi,

Jumped to this great repo from confluent site.
In the feature set it says that the C++ implementation supports schema registry, but I could not find any mention of avro/protobuf/json schema in the code, nor any mention of schema registry (except to get statistics).

Am I missing the location in the code? Is it going to be suported?

Thanks,
Shahar

**Comment by edenhill** [comment]
librdkafka itself does not provide serialization or schema-registry support, this is provided by Confluent's [libserdes](https://github.com/confluentinc/libserdes) which can be used in combination with librdkafka to serialize/deserialize Avro with schemas registered in the Schema-registry.

**Comment by SleepyBearDad** [comment]
Thanks!
