### ISSUE TITLE
event_cb option missing from documentation/types

### ISSUE THREAD

**Issue by eurostar-fennec-cooper** [edenhill/librdkafka#2931]
Description
===========
The event_cb option is missing from both Configuration.md and from config.d.ts.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `f665358d503284f1e0192df09d1cd5b2515bb8b7`

**Comment by rkahv** [comment]
Hi, I just noticed the same thing. 
Did you find an answer why event_cb is not listed in the Configuration.md, but used in a lot of the example code?
