### ISSUE TITLE
librdkafka logs are displayed on the serial console

### ISSUE THREAD

**Issue by yhsiung** [edenhill/librdkafka#2935]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>
We saw a lots of error messages generated from librdkafka repeatably on the serial console, which blocked the console usage. How do we redirect these errors to a file instead of displaying on the serial console without modifying the librdkafka code.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.11.6
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka logs to stderr by default, you can redirect logs elsewhere by implementing a log_cb and setting it with `rd_kafka_conf_set_log_cb()`.

Apart from the stderr logger there is also a builtin syslog logger you can use:
rd_kafka_log_syslog

**Comment by yhsiung** [comment]
Hi Magnus,

I have a question with "ssl.ca.location" config at the producer side? I
believe this is the path for the trust store where all the CA certificates
reside, and Kafka producer uses it to verify Kafka broker's certificate,
right?
I saw most of the examples configure it with a particular CA cert (e.g.,
/etc/ssl/certs/ca-cert.crt) rather than an entire trust store directory
(e.g., /etc/ssl/certs). Please advise.

Regards,
Yang

**Comment by edenhill** [comment]
Both are fine.

**Comment by yhsiung** [comment]
Hi Magnus,

I was told that when the certificate rotation happens, Librdkafka will hit
a case where it will try to reconnect using the old/expired cert and that
will result in SSL handshake failure. Is it still the case or has it been
resolved? Any workarounds? Thanks.

Regards,
Yang

**Comment by yhsiung** [comment]
Hi Magnus,

I configured "message.max.bytes" with "2000000" (2M) because sometimes I
need to push 1.4MB with single message to brokers. However, I still get the
"Message size too large" error from my callback as below. Please advise how
to resolve this issue. Thank you.

Regards,
Yang

Level: ERROR Time: 2021-04-19 23:09:14.947660 Thread: 0xb6fb3010 Process:
873 Unknown error -1: ocskafka_producer: Message delivery failed: Broker:
Message size too large,

**Comment by edenhill** [comment]
Please don't hijack issues for other purposes, this issue is about logs being displayed on the serial console.
Your question is suitable for the discussions forum here: https://github.com/edenhill/librdkafka/discussions
