### ISSUE TITLE
Application terminates by the following lbrdkafka exception 0xc0000005

### ISSUE THREAD

**Issue by fruttyh** [edenhill/librdkafka#2936]
Description
===========
While trying to consume a kafka topic using 6 threads (equal to the amount of partitions) I get the following error in the windows event viewer:
```
Faulting application name: XXXXXXX, version: 1.0.0.0, time stamp: 0xce2fff25
Faulting module name: librdkafka.dll, version: 0.0.0.0, time stamp: 0x5eb2aca9
Exception code: 0xc0000005
Fault offset: 0x00165f9a
Faulting process id: 0xb18
Faulting application start time: 0x01d63e27134c4f61
Faulting application path: XXXXXXX
Faulting module path: XXXXXXX\librdkafka\x86\librdkafka.dll
Report Id: d623c2ea-f84b-4be2-a3c4-27d3c51b608c
Faulting package full name: 
Faulting package-relative application ID: 

XXXXXXX
  1.0.0.0 
  ce2fff25 
  librdkafka.dll 
  0.0.0.0 
  5eb2aca9 
  c0000005 
  00165f9a 
  b18 
  01d63e27134c4f61 
  XXXXXXX.exe 
  XXXXXXX\librdkafka\x86\librdkafka.dll 
  d623c2ea-f84b-4be2-a3c4-27d3c51b608c 
```
This issue occurs every time I try to do an initial load of the topic, ie. run from the very beggining of the topic. The error occurs every time, but the error can occur after 5 minutes, 10 minutes, 15 minutes or more. It's very random.

I have monitored the CPU / RAM of the server and nothing suspicious there.
There is plenty of application log in the application and all code blocks are encapsulated in try / catch but nothing it catched. (I have removed these in the provided example)

I have registered an event handler for: 
UnhandledException in program.cs

Also in my try catch blocks when consuming from kafka I have added a catch block for:
RuntimeWrappedException

I haven't hade the opportunity to look at the kafka logs since I dont have acces to them.

Environment: C#, .NET Framework (v4.7.2), TopShelf Windows Service
Confluent.Kafka Version: 1.4.3
librdkafka.redist Version: 1.4.2
Estimated number of records on the topic: ~ 6,000,000
Kafka Partitions: 6

How to reproduce
================
Start an application with 6 threads (same amount as the number of partitions) running the method "ConsumeMessagesEof" in the provided code.

```
public async void ConsumeMessagesEof (CancellationToken cancellationToken, MessageReceivedCallback messageReceivedCallback) {
  var kafkaConsumer = GetKafkaConsumer();
  using (kafkaConsumer) {
    kafkaConsumer.Subscribe (_kafkaConsumerConfigFactory.GetTopic());
    while (!cancellationToken.IsCancellationRequested) {
      var consumptionResult = kafkaConsumer.Consume (cancellationToken);
      if (consumptionResult.IsPartitionEOF) break;

      var msg = consumptionResult?.Message.Value;
      if (msg == null) continue;

      if (string.IsNullOrEmpty(msg)) continue;

      var incomingMessageModel = JsonConvert.DeserializeObject<T> (msg);
      await messageReceivedCallback(incomingMessageModel, consumptionResult);
    }
    kafkaConsumer.Close ();
  }
}

private IConsumer<string, string> GetKafkaConsumer() {
  return new ConsumerBuilder<string, string> (_kafkaConsumerConfigFactory.GetConfig())
    .SetErrorHandler((consumer, error) => {
      _logger.Error(MessageTemplates.ServiceMessage, "Kafka error.", new { error.Code, error.Reason });
    }).SetLogHandler((consumer, message) => {
      _logger.Debug(MessageTemplates.ServiceMessage, "Kafka log.", new { message.Message });
    }).Build();
}

public ConsumerConfig GetConfig() {
  return new ConsumerConfig {
      BootstrapServers = "bootstrapServers",
      SecurityProtocol = "sslKeystorePassword",
      SslCaLocation = "kafkaSslKeystoreLocation",
      SslCertificateLocation ="kafkaSslKeystoreLocation",
      SslKeyLocation = "kafkaSslKeystoreLocation",
      SslKeyPassword = "sslKeystorePassword",
      GroupId = "groupId",
      AutoOffsetReset = AutoOffsetReset.Earliest,
      MessageMaxBytes = 2097152,
      Debug = false,
      AutoCommitIntervalMs = 3000,
      StatisticsIntervalMs = 0,
      EnablePartitionEof = true
  };
}
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<latest>`
 - [ ] Apache Kafka version: `<Confluent Kafka>`
 - [x] librdkafka client configuration: `<bootstrapServers = "xxxx", securityProtocol = "xxxx", sslCaLoaction = "xxxx", sslCertificateLocation = "xxxx", sslKeyLocation = "xxxx", 
sslKeyPassword = "xxxx", groupId = "xxxx", auto.offset.reset = earliest, messageMaxBytes = 2097152, debug = false, autoCommitIntervalMs = 3000, statisticsIntervalMs = 0, enablePartitionEof = true>`
 - [x] Operating system: `<Windows Server 2016>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
@mhowlett ring a bell?

**Comment by fruttyh** [comment]
Any updates on this @edenhill & @mhowlett ?
Is there anything else I can provide to you that would help?

**Comment by edenhill** [comment]
We haven't seen similar reports and there is not much to go on.

 * Is it possible that your process runs out of memory? (track its memory usage up until crash)
 * Does it crash every time?
 * Is the topic compressed, if so, with what compression codec?
 * Can you try to reproduce with Debug set to `all` and provide us the logs?

**Comment by edenhill** [comment]
Are you subscribing to wildcard topics?

**Comment by mhowlett** [comment]
- `Debug=false` won't compile right?
- Re: possible OOM, it might be worth setting `queued.max.messages.kbytes` to a (much) lower value and see if that helps.
- It might be worth `Wait()` ing rather than `await` ing `messageReceivedCallback` to ensure main loop execution is always on the same thread - but there shouldn't be an issue, i'm clutching at straws there.

**Comment by fruttyh** [comment]
@edenhill @mhowlett Thanks a lot for the quick replies, really appreciated!

I just started the service trying the following:

- Debug set to all (will provide logs shortly, forgot to change log level on my serilog logger, doh!)
- Also reduced queued.max.messages.kbytes to 20971 instead

This didn't help unfortunately..
Same exception as before. 

**Is it possible that your process runs out of memory? (track its memory usage up until crash)** It does not run out of memory. Plenty of head room.

**Does it crash every time?** Yes it does, not allways at the same amount of time though.

**Is the topic compressed, if so, with what compression codec?** By compressed, do you mean log compacted or something else?

**It might be worth Wait() ing rather than await ing messageReceivedCallback to ensure main loop execution is always on the same thread - but there shouldn't be an issue, i'm clutching at straws there.** I agree! I'll see if these modifications will help otherwise I'll start chaning the code. The service is running in production so the less code changes the better!

**Are you subscribing to wildcard topics?** No.

**Debug=false won't compile right?** We have that as an parameter in our release so it will be null most of the times. I just edited it to indicate that we aren't using it. Sorry for being unclear.

The service should crash any minute now, will get back with the logs when I have them!

**Comment by fruttyh** [comment]
[kafka_log_2020-06-30.txt](https://github.com/edenhill/librdkafka/files/4849784/kafka_log_2020-06-30.txt)

Here are the logs.

**Comment by edenhill** [comment]
Thank you, the logs look fine.

Could you try an older release, say v1.2.2 or v1.1.0?

**Comment by edenhill** [comment]
> Is the topic compressed, if so, with what compression codec? By compressed, do you mean log compacted or something else?

Compressed as in lz4, zstd, snappy, or gzip.

**Comment by fruttyh** [comment]
> > Is the topic compressed, if so, with what compression codec? By compressed, do you mean log compacted or something else?
> 
> Compressed as in lz4, zstd, snappy, or gzip.

I tired running with both 1.4.4 and 1.2.2 but still the same issue.
Want me to try with 1.1.0 aswell?

And no, the topic should not be compressed (not that I am aware of).

**Comment by fruttyh** [comment]
Trying again with v1.1.0 since I din't know what else to try.
Will report the result as soon as I got them.

**Comment by fruttyh** [comment]
> Trying again with v1.1.0 since I din't know what else to try.
> Will report the result as soon as I got them.

Same issue with v1.1.0...

**Comment by edenhill** [comment]
Thank you for testing the older versions as well.

Since your use-case is standard my assumption is that there is something in your environment that triggers this crash, but I have no idea what that is.
We would probably need you to reproduce this in some sort of debugger (visual studio perhaps), but the specifics of doing that for a .NET app is outside my knowledge.

**Comment by fruttyh** [comment]
@edenhill No worries, I really appreciate that you are taking your time to investigate this as well.
I've asked for the logs from the broker, hopefully I can provide those as well.

The problem is that I wont be able to reproduce this with a debugger attached.
Since this issue only occurs in our production environment.

But like you are saying, that should indicate that something is wrong in our environment.
I'll post the broker logs as soon as I get them (if I get them).

Thanks again!

**Comment by edenhill** [comment]
Assuming that `Fault offset: 0x00165f9a` is the relative location (without
the load address) of the code
that triggers the segmentation fault (due to NULL reference) I've explored
the DLLs provided by librdkafka.redist
to try to find the function that crashes.

Only librdkafka.dll is large enough to have fit that offset, but using
dumpbin /disasm together with the pdb
all I get is unsymboled garbage. It does seem to be in the statically
linked OpenSSL section of the code though,
but nothing more detailed than that.

Would it be possible for you to reproduce this without using SSL?


Den tis 30 juni 2020 kl 12:55 skrev fruttyh <notifications@github.com>:

**Comment by fruttyh** [comment]
@edenhill Sorry for the late response, didn't work thursday/friday last week.

Interesting that you might have located the issue.
Unfortunately I can't run the application without SSL against the same topic/data.
The wierd part is that I have tried the same code in 2 other environments that use SSL, and there are no issues there.

The only thing that is different is the size of the topic between the environments.
Could that cause the issue?

**Comment by edenhill** [comment]
I understand.

If you think topic size could be the issue it would point in the direction of memory usage in the application, so what we could try to do is minimize the pre-fetch queue to scale down memory usage and see if it helps.
Could you set to `queued.max.message.kbytes` to `64000` and see if you still see the crashes?

**Comment by fruttyh** [comment]
@edenhill Like I wrote in a previous comment I did try to run with queued.max.message.kbytes = 20971 and that still caused the issue. Anything else I could try?

**Comment by edenhill** [comment]
Ah, sorry for missing that.

Could you try running just one consumer thread?

**Comment by fruttyh** [comment]
@edenhill I have experimented with fewer threads, I remember trying running 3 threads instead of 6 but that still caused the same problem. At the moment we are in the middle of a release so I can't cancel it at the moment.

I can try it as soon as the release is done!

**Comment by edenhill** [comment]
It seems that Userdump can be used to get a process dump/core file from a crashing application, is this something you could try and then supply us with the process dump file for further inspection?
https://support.microsoft.com/en-gb/help/241215/how-to-use-the-userdump-exe-tool-to-create-a-dump-file

**Comment by fruttyh** [comment]
@edenhill Unfortunately we don't have that one installed (the guide you linked seems to be for Windows Server 2003 aswell).
I'm also not authorized to install new programs from an .exe on our production server. 

I was however able to create a dump file but that resulted in a 3gb file which I couldn't transfer from the server to my developer PC.... Doh!

I'll try to get that dump file to my PC but my worry is that it won't show anything since I have to create the dump from a running instance, ie. before it crashes.

**Comment by fruttyh** [comment]
@edenhill Short update. I got a chance to try to run our application with 3 threads instead of 6 and then it ran for about 1 hour without crashing and also finishing the initial load of the topic.

Previously it ran for about ~5 minutes before crashing so that a huge improvement.
Really strange though that this didn't work before? It could be a coincidence so I need to try this again by doing another initial load with 3 threads in order to know.

**Comment by edenhill** [comment]
So it didnt crash at all with a reduced number of threads?

This would indicate that the process runs out of memory with the increased thread count, or that that the increased thread count surfaces a race condition (due to more context switches and slower overall execution) or a concurrency issue either within librdkafka or some other part of the stack.

We use both helgrind and tsan to verify concurrency correctness,  and there are no known outstanding such issues.

**Comment by fruttyh** [comment]
@edenhill Exactly it kept running for about 60 minutes until reaching end of file.
I've watched the memory on the server when the application is crashing and that isn't the issue atleast.
We shouldn't have any race condition on our side that causes this either, that's the strange part.

I guess we can close this issue for now. I will run more tests with 6 threads when I get the opportunity but I can't do that now since our production environment is relying on the data that we get from the kafka topic.

But I really appreciate the quick feedback / help and sorry for this late response! :) 
Have a great summer!

**Comment by edenhill** [comment]
Are things still stable with the reduced thread count?

**Comment by fruttyh** [comment]
@edenhill Sorry for the really late response. Had late vacation this year so I just missed your response.

However, we haven't had the chance to try this anymore. 
At the moment the service is running with 1 thread since we don't have that high load no that we have done our initial load from the topic.

We will however have the chance to try "the same" code on a even larger kafka topic here the coming weeks.

I can report back once we have tested that? :-)

**Comment by edenhill** [comment]
Please do :+1:
