### ISSUE TITLE
Error: Invalid value "sasl_ssl" for configuration property "security.protocol"

### ISSUE THREAD

**Issue by Davenporten** [edenhill/librdkafka#2937]
Description
===========
I'm getting the error
```
Error: Invalid value "sasl_ssl" for configuration property "security.protocol"
```
I've used both `sasl_ssl` and `SASL_SSL`, but with the same result. I'm making the request from [graphql-kafka-subscriptions](https://www.npmjs.com/package/graphql-kafka-subscriptions) and the configs that are pass in in totaly are
```
        'security.protocol': 'sasl_ssl',
        'sasl.kerberos.keytab': <path_to_keytab>,
        'sasl.kerberos.principal': <principal>,
```
I don't know if I need to send something else along in order for the sasl_ssl to go through, but the error is generated by `librdkafka`. I've been combing through the code and it seems like while maybe there are some other missing configs `sasl_ssl` or `SASL_SSL` should at least be valid input for `security.protocol`.

How to reproduce
================
Use similar configs as the ones above.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.4.2`
 - [ ] Apache Kafka version: `Unsure, using Hortonworks bundle, don't have much control`
 - [x] librdkafka client configuration: `see above`
 - [x] Operating system: `Centos 5 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Your build of librdkafka lacks SASL support.
If you built librdkafka from source, make sure required dependencies are installed and look at the ./configure output for hints on what is missing.

**Comment by Davenporten** [comment]
So do I have to make sure all of these are `ok` in order to get things to work as expected? No problem if so, just want to know.
```
checking for OS or distribution... ok (centos)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking executable libtool... failed (disable)
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x010402ff'... ok (1.4.2)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for c11threads (by pkg-config)... failed
checking for c11threads (by compile)... failed (disable)
checking for libdl (by pkg-config)... failed
checking for libdl (by compile)... ok
checking for zlib (by pkg-config)... failed
checking for zlib (by compile)... failed (disable)
checking for libcrypto (by pkg-config)... failed
checking for libcrypto (by compile)... failed (disable)
checking for libsasl2 (by pkg-config)... ok
checking for libzstd (by pkg-config)... failed
checking for libzstd (by compile)... failed (disable)
checking for libm (by pkg-config)... failed
checking for libm (by compile)... ok
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for syslog (by compile)... ok
checking for rapidjson (by compile)... failed (disable)
checking for crc32chw (by compile)... ok
checking for regex (by compile)... ok
checking for strndup (by compile)... ok
checking for strlcpy (by compile)... failed (disable)
checking for strerror_r (by compile)... ok
checking for pthread_setname_gnu (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for python3 (by command)... ok
checking for getrusage (by compile)... ok
```

**Comment by edenhill** [comment]
You're missing OpenSSL

**Comment by Davenporten** [comment]
Ok gotcha, I thought I neede `libsasl2` OR `openssl`. Thanks!

**Comment by Davenporten** [comment]
@edenhill What made you say OpenSSL was missing? I actually already had it installed. Is there something in the avoid that is telling you ssl might not be totally enabled?

**Comment by Davenporten** [comment]
@edenhill Thanks for all the help, it's working. Closing this issue.
