### ISSUE TITLE
performance of a traditional queue

### ISSUE THREAD

**Issue by prabcs** [edenhill/librdkafka#294]
Hi,

Kafka can work as a traditional queue, allowing c consumers in one consumer group to consume from p partitions, where c<=p.
Can the same be achieved for perf testing Kafka using librdkafka_performance?

**Comment by edenhill** [comment]
Not automatically, librdkafka does not currently support automatically balanced consumer groups, you will need to start up an rdkafka_performance consumer per partition.

Broker based consumer group balancing will be released with Apache Kafka 0.9, and librdkafka will support it.

**Comment by prabcs** [comment]
Hi,

I was going through Kafka 0.8 documentation and architecture, where they've
explained how consumers in 1 consumer group and consume from multiple
partitions.
I was wondering how that can be done via rdkaka_performance

Thanks

On Mon, Jun 1, 2015 at 1:50 PM, Magnus Edenhill <notifications@github.com>
wrote:

> Not automatically, librdkafka does not currently support automatically
> balanced consumer groups, you will need to start up an rdkafka_performance
> consumer per partition.
>
> Broker based consumer group balancing will be released with Apache Kafka
> 0.9, and librdkafka will support it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edenhill/librdkafka/issues/294#issuecomment-107357260>
> .
>



-- 
---------------------------------------------------------
"There are only 10 types of people in the world: Those who understand
binary, and those who don't"

**Comment by edenhill** [comment]
That's automatically balanced consumer groups, which are not currently supported by librdkafka (see previous comment)

**Comment by prabcs** [comment]
All right. 
I understand now that 1 librdkafka consumer can not consume from more than 1 partitions.
But, then, in production use cases, if 1 consumer goes down, how can I make sure that the data written on the partition is consumed so there is no producer backlog ?
In my use case, the data needs to be processed within a certain SLA, so consumer going down should not affect. Can librdkafka be of help in such a use case ?

**Comment by edenhill** [comment]
One librdkafka consumer can consume from any number of topics and partitions, just call `rd_kafka_consume_start[_queue]()` for each one.

For the failover parts: librdkafka currently does not support automatic consumer group balancing, but it will as soon as the new broker support is available in 0.9 (during fall 2015 most likely).

In the meantime you could probably conceive the consumer balancing yourself with some zookeeper integration.

**Comment by prabcs** [comment]
Let me try and explain my understanding of your answer:-
Consumer 1 - consumes from partition 1 and 2
Consumer 2 - consumes from partition 1 and 2

So, the above 2 consumers are not part of the same consumer group, which means both of these consumers will be getting the same data.
Is my understanding correct ?

**Comment by edenhill** [comment]
Yes, correct
Den 2 jun 2015 09:44 skrev "prabcs" <notifications@github.com>:

**Comment by prabcs** [comment]
Thanks for all your help. Closing the issue now.
