### ISSUE TITLE
how to get consumer offset in producer

### ISSUE THREAD

**Issue by zqian4321** [edenhill/librdkafka#2940]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description

I know that query_watermark_offsets can be used to get producer offset. I wonder how to get consumer offset in producer.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): librdkafka1.0.5
 - [x] Apache Kafka version: kafka2.5.0
 - [x] librdkafka client configuration: default
 - [x] Operating system:ubuntu14.04
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by zqian4321** [comment]
can i get consumer offset of Topic+Partition without using consumer instance?

**Comment by zqian4321** [comment]
It seems that i can do this with Rdkafka::KafkaComsumer::committed.

**Comment by edenhill** [comment]
You will need to instantiate a KafkaConsumer and use committed().
