### ISSUE TITLE
admin operations in c++

### ISSUE THREAD

**Issue by SleepyBearDad** [edenhill/librdkafka#2941]
Hi,

I saw that KAFKA topics may be created using the admin API which has a C implementation.
I looked at the C++ but couldn't find it.

Am I missing something? Are there plans for implementation?

**Comment by edenhill** [comment]
There are no plans to add the Admin API to the C++ API at this point, the API surface area is vast and the return of investment is low.

Instead use the C API on your RdKafka::Handle's `c_ptr()`.
