### ISSUE TITLE
ZSTD 1.4.5: Unable to begin ZSTD decompression (out buffer is 11022 bytes): Corrupted block detected

### ISSUE THREAD

**Issue by champtar** [edenhill/librdkafka#2943]
The problem is likely in ZSTD, but I'm reporting it here to help/warn people
You can close it right away if you think there is nothing to do for you

Description
===========
Using libzstd-1.4.5-3.el7.x86_64.rpm with librdkafka 1.0.1 or 1.4.4, I'm getting the following error on the consumer:
```
Unable to begin ZSTD decompression (out buffer is 10020 bytes): Corrupted block detected
```

Reverting to zstd 1.4.4 (https://dl.fedoraproject.org/pub/archive/epel/7/x86_64/Packages/l/libzstd-1.4.4-1.el7.x86_64.rpm) and rereading the same data (--reset-offsets --to-earliest), it works

Data was produce by librdkafka 1.0.1 / libzstd 1.4.5

How to reproduce
================
To be done (might not have time before next week)

Producer:
kafkacat -P -E -X compression.codec=zstd -X queue.buffering.max.ms=100 -X broker.version.fallback=2.2.0 -X security.protocol=sasl_plaintext -X sasl.mechanisms=PLAIN -X sasl.username=kafkacat -X sasl.password='ABCD' -b 10.30.71.37 -t vme1

Consumer: librdkafka

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.4.4` (at first was `1.0.1`)
 - [x] Apache Kafka version: `2.2.1`
 - [x] librdkafka client configuration: `api.version.fallback.ms=0, broker.version.fallback=0.11.0`
 - [x] Operating system: `CentOS 7`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
```
Unable to begin ZSTD decompression (out buffer is 10020 bytes): Corrupted block detected
```
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Might want to file an upstream issue on https://github.com/facebook/zstd/issues, but could be an issue with how librdkafka interacts with zstd.
Relevant librdkafka code: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_zstd.c

**Comment by champtar** [comment]
@edenhill this a regression in zstd, see https://github.com/facebook/zstd/issues/2222

small note from my investigation, it would be nice to have a debug level that dump the buffer on error
(depending on how long your retention is, by the time you rebuild everything it might be too late)
```
diff --git a/src/rdkafka_zstd.c b/src/rdkafka_zstd.c
index 052cb7c..f819090 100644
--- a/src/rdkafka_zstd.c
+++ b/src/rdkafka_zstd.c
@@ -94,13 +94,22 @@ rd_kafka_zstd_decompress (rd_kafka_broker_t *rkb,
                         out_bufsize += RD_MAX(out_bufsize * 2, 4000);
 
                         rd_atomic64_add(&rkb->rkb_c.zbuf_grow, 1);
+                        rd_rkb_dbg(rkb, MSG, "ZSTD", "Growing buffer %llu bytes\n", out_bufsize);
 
                 } else {
                         /* Fail on any other error */
                         rd_rkb_dbg(rkb, MSG, "ZSTD",
                                    "Unable to begin ZSTD decompression "
-                                   "(out buffer is %llu bytes): %s",
-                                   out_bufsize, ZSTD_getErrorName(ret));
+                                   "(in buffer is %zu bytes, out buffer is %llu bytes): %s",
+                                   inlen, out_bufsize, ZSTD_getErrorName(ret));
+                        rd_rkb_dbg(rkb, MSG, "ZSTD", "Bad buffer start");
+                        size_t i;
+                        fprintf(stderr, "==========\n");
+                        for (i = 0; i < inlen; i++)
+                            fprintf(stderr, "%#x,", (unsigned char)inbuf[i]);
+                        fprintf(stderr, "\n==========\n");
+                        rd_rkb_dbg(rkb, MSG, "ZSTD", "Bad buffer end");
+
                         return RD_KAFKA_RESP_ERR__BAD_COMPRESSION;
                 }
         }
```
