### ISSUE TITLE
it seems not to work well when “auto.create.topics.enable=false” is set.

### ISSUE THREAD

**Issue by zqian4321** [edenhill/librdkafka#2945]
Description
===========
    
when “auto.create.topics.enable=false” is set in server.properties, i create topic instance and producer instance successfully(in the same process or different process). But neither can i get offsets using query_watermark_offsets  nor comsune message after producing message.
    Can i set “auto.create.topics.enable=false" when using librdkafka? What should i do about config? 

How to reproduce
================
“auto.create.topics.enable=false” in server.properties. So do in RdKafka::Conf. Then Create producer and topic. 
After producing message, can neither get offsets using query_watermark_offsets  nor comsune message.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.10.5
 - [x] Apache Kafka version: kafka_2.13_2.5.0
 - [x] librdkafka client configuration: auto.create.topics.enable=false
 - [x] Operating system: ubuntu14.04
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by zqian4321** [comment]
It seems that topic create failed(topic can not be found by kafka-topics.sh), but RdKafka::Topic::create return a ptr not null.

**Comment by edenhill** [comment]
librdkafka 0.10.5 is not a valid librdkafka version.


RdKafka::Topic::create() simply creates a local topic object, and if auto topic creation is enabled on the cluster it might (asynchronously) trigger the topic to be created on the cluster.  

If you are creating topics through the Admin API it might take some time for the newly created topic to propagate in the cluster and becoming fully functional.

**Comment by zqian4321** [comment]
> librdkafka 0.10.5 is not a valid librdkafka version.
> 
> RdKafka::Topic::create() simply creates a local topic object, and if auto topic creation is enabled on the cluster it might (asynchronously) trigger the topic to be created on the cluster.
> 
> If you are creating topics through the Admin API it might take some time for the newly created topic to propagate in the cluster and becoming fully functional.



> librdkafka 0.10.5 is not a valid librdkafka version.
> 
> RdKafka::Topic::create() simply creates a local topic object, and if auto topic creation is enabled on the cluster it might (asynchronously) trigger the topic to be created on the cluster.
> 
> If you are creating topics through the Admin API it might take some time for the newly created topic to propagate in the cluster and becoming fully functional.         


The version is    "#define RD_KAFKA_VERSION 0x01050001". Is it librdkafka 1.05.1?
So what if i disable auto topic creation when using librdkafka?

**Comment by edenhill** [comment]
That should work, how much time passes between creating the topic before trying to produce to it?

Do note that you are using the librdkafka master branch which is being actively developed and should not be used for production use (use the latest tagged release for that), but Im interested to know what is happening in your scenario.

**Comment by zqian4321** [comment]
> That should work, how much time passes between creating the topic before trying to produce to it?
> Just several seconds. But even for several minutes, i still fail to produce to it.  And i cannot query that topic using  kafka-topics.sh

> Do note that you are using the librdkafka master branch which is being actively developed and should not be used for production use (use the latest tagged release for that), but Im interested to know what is happening in your scenario.
> Ok,thanks.

**Comment by edenhill** [comment]
How are you creating the topics?

**Comment by zqian4321** [comment]
> How are you creating the topics?

RdKafka::Conf* conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
RdKafka::Conf* t_conf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);
std::string errstr;
conf->set("bootstrap.servers", "localhost:9092", errstr);
conf->set("allow.auto.create.topic", "0", errstr);
RdKafka::Producer* producer = RdKafka::Producer::create(conf, errstr);
RdKafka::Topic* topic = RdKafka::Topic::create(producer, "testTopic", t_conf, errstr);

Everything is ok on creating and setting, but no topic is created.

auto.create.topics.enable=false

**Comment by edenhill** [comment]
Topic::create() only creates a local topic object in the client which will only trigger topic auto creation (on the broker) if auto creation is enabled in the broker config.

You will need to create the topic with kafka-topics.sh or the Admin API : https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L5820

**Comment by zqian4321** [comment]
> Topic::create() only creates a local topic object in the client which will only trigger topic auto creation (on the broker) if auto creation is enabled in the broker config.
> 
> You will need to create the topic with kafka-topics.sh or the Admin API : https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L5820

OK, thanks.
