### ISSUE TITLE
Align producer config options to the new java producer released in Kafka 0.8.2

### ISSUE THREAD

**Issue by cleaton** [edenhill/librdkafka#295]
Kafka 0.8.2 release brought a new Java producer which support callbacks (finally!) and some new configuration options. Most of the new functionality has always been in librdkafka but it would be nice to update librdkafka options to match the new producer.

https://kafka.apache.org/082/configuration.html

In particular the new api sets batch.size in bytes instead of batch.num.messages which can help prevent producers hitting brokers max.message.bytes.

**Comment by edenhill** [comment]
I agree! (issue #157)
