### ISSUE TITLE
Zstd compression

### ISSUE THREAD

**Issue by migue** [edenhill/librdkafka#2951]
Description
===========
First of all, I would like to thank you all for the nice library you have built; it's been extremely useful for me (not just using it on my projects but learning from the source code as well).

I've been experiencing a weird (at least to me :D) problem and I would like to share it with you folks because I am probably missing something

When I enable the `zstd` compression in my producers I start getting errors like the following one: `Consumer error: Decompression (codec 0x4) of message at 76266 of 1605 bytes failed: Local: Invalid compressed data` on the consumer side, but only when the __topic__ has __more than 1 partition__.

I am using the library from a Go program but I have set up a way to reproduce it using the consumer and producer provided in this repo (the ones in the example folder). In the next section, I provide a step by step guide trying to explain it

How to reproduce
================

1. Create a topic with more than one partition: `/opt/kafka2/bin/kafka-topics.sh --zookeeper zookeeper:2181 --create --topic native-three-partitions --partitions 3 --replication-factor 2`
1. Generate the input data: `./metrics-generator metrics-json.data json 5` This program creates JSON elements in the file metrics-json.data for 5 minutes. The program is able to generate data in `msgpack` or `proto` encodings (at the beginning I thought it was something related to the encoding of my messages).
1. Use the producer provided in this repo (and linked against the zstd v1.4.5) to generate data in the topic previously created: `./producer localhost:9092 native-three-partitions`.
1. Start the consumer on the previous topic: `./consumer localhost:9092 native-three-partitions-group native-three-partitions`.

For a while the consumer reads the data:

```
Message on native-three-partitions [2] at offset 76258:
 Value: {"timestamp":1593516633014273057,"values":{"duration":6252484413710253229},"properties":{"az":"az-1","rack":"rack-1","server":"server-1"},"metricSetType":"latency","namespace":"myns","recordDate":1593516633014274923}
Message on native-three-partitions [2] at offset 76259:
 Value: {"timestamp":1593516633014281207,"values":{"duration":7533849970615038329},"properties":{"az":"az-1","rack":"rack-1","server":"server-1"},"metricSetType":"latency","namespace":"myns","recordDate":1593516633014283183}
Message on native-three-partitions [2] at offset 76260:
```

But it suddenly starts to continuously report the following errors:

```
% Subscribed to 1 topic(s), waiting for rebalance and messages...
% Consumer error: Decompression (codec 0x4) of message at 10285 of 1108 bytes failed: Local: Invalid compressed data
% Consumer error: Decompression (codec 0x4) of message at 23860 of 1179 bytes failed: Local: Invalid compressed data
% Consumer error: Decompression (codec 0x4) of message at 76266 of 1605 bytes failed: Local: Invalid compressed data
% Consumer error: Decompression (codec 0x4) of message at 10285 of 1108 bytes failed: Local: Invalid compressed data
% Consumer error: Decompression (codec 0x4) of message at 23860 of 1179 bytes failed: Local: Invalid compressed data
% Consumer error: Decompression (codec 0x4) of message at 76266 of 1605 bytes failed: Local: Invalid compressed data
% Consumer error: Decompression (codec 0x4) of message at 10285 of 1108 bytes failed: Local: Invalid compressed data
% Consumer error: Decompression (codec 0x4) of message at 23860 of 1179 bytes failed: Local: Invalid compressed data
% Consumer error: Decompression (codec 0x4) of message at 76266 of 1605 bytes failed: Local: Invalid compressed data
% Consumer error: Decompression (codec 0x4) of message at 10285 of 1108 bytes failed: Local: Invalid compressed data
```

If I check the segments using a command like: `KAFKA_OPTS="-Djava.io.tmpdir=/home/ec2-user" /opt/kafka2/bin/kafka-run-class.sh kafka.tools.DumpLogSegments --files /var/lib/kafka2/data/native-three-partitions-0/00000000000000000000.log --print-data-log`I cannot find anything obviously wrong (to me, of course :D )

And the consumer starts lagging

```
GROUP                         TOPIC                   PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
native-three-partitions-group native-three-partitions 0          23860           1000777         976917          rdkafka-373ab497-a0d4-4d3d-97d3-b60bd6e626e2 /IP   rdkafka
native-three-partitions-group native-three-partitions 1          10285           998478          988193          rdkafka-373ab497-a0d4-4d3d-97d3-b60bd6e626e2 /IP   rdkafka
native-three-partitions-group native-three-partitions 2          76266           1000745         924479          rdkafka-373ab497-a0d4-4d3d-97d3-b60bd6e626e2 /IP   rdkafka
```

In addition to the previous tests, I have compressed and decompressed the previous file using a standalone program (simple and streaming) compiled using the `1.4.5` Zstd version (these examples are provided in the Zstd repo as well).

Just to provide more context, with the same setup but using `lz4` as the `compression.codec` I have not been able to reproduce the issue described before.

So, before I get going down the rabbit hole I have decided to share this with you folks in case this is something completely obvious I am missing or this is something you have already experienced (I couldn't find anything similar looking at the existing issues).

Again, thanks a lot for your hard work.

Migue

PS: The little program used to generate the input data can be found here: https://drive.google.com/file/d/1iAysyrXz6KUKLmgZepGUi0PfXHhn_e0a/view?usp=sharing

Checklist
=========

Please provide the following information:

 - [x] librdkafka version: v1.4.4
 - [x] Apache Kafka version: `2.5.0 (Commit:66563e712b0b9f84)`
 - [x] librdkafka client (producer) configuration: `compression.codec:"zstd"`
 - [x] Operating system: `4.14.146-120.181.amzn2.x86_64`
 - [] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks for the encouragement!

This sounds very much like https://github.com/edenhill/librdkafka/issues/2943 which is a regression in zstd.

**Comment by edenhill** [comment]
Great bug report, btw!
