### ISSUE TITLE
Get broker information in the message delivery report callback

### ISSUE THREAD

**Issue by geo-matheou** [edenhill/librdkafka#2952]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
It would be nice to get broker information in the message delivery report callback using either rd_kafka_t or rd_kafka_message_t structs. This can be helpful in situations where we get timeout issues and we would like to know which broker is responsible for these issues. 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v1.4.4
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Is the broker id sufficient?

**Comment by geo-matheou** [comment]
If the broker id contains the ip addreess / url of the broker would be great!

**Comment by edenhill** [comment]
The broker id is the unique integer id for each broker, it is what identifies a single broker.

We don't want to store the connection address on each message object, it will either increase memory pressure or complexity, or both.

**Comment by geo-matheou** [comment]
ok then it will be fine. 

Thank you for the update.
