### ISSUE TITLE
KIP-389: Introduce a configurable consumer group size limit

### ISSUE THREAD

**Issue by blaketastic2** [edenhill/librdkafka#2956]
Description
===========
Looking at the enabled KIPs(https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#supported-kips), "KIP-389: Introduce a configurable consumer group size limit" seems to be supported, but I do not see that the configuration of "group.max.size" is in the documentation, nor do I see any reference to the property in the source code. Is this property supported? I'm using `confluent-kafka-go`.

How to reproduce
================
Adding "group.max.size" to my kafka.ConfigMap and starting my consumer

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.4.2`
 - [x] Apache Kafka version: `2.5.0`
 - [x] librdkafka client configuration: `"group.max.size": 1, "auto.offset.reset": "earliest", "enable.auto.commit": "false", "sasl.mechanisms": "PLAIN"`
 - [x] Operating system: `Amazon Linux`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
`group.max.size` is a broker-side config property.
