### ISSUE TITLE
SASL Authentication failure messages, even though messages are coming through.

### ISSUE THREAD

**Issue by itkovian** [edenhill/librdkafka#2959]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
omkafka shows errors despite being able to produce messages to kafka over SASL_SSL.

I'm seeing a lot of `Local: Authentication failure` errors, stopping and resuming omkafka. Those error strings come from librdkafka afaik.

Note that SSL without SASL does work correctly.
Note also that changing the password to something incorrect for the SASL part does result in _no_ messages coming through and the connection being broken.

Pipeline is:

rsyslog -> kafka -> logstash -> elasticsearch and I can see the log messages in the kibana search. So all messages do seem to come through, even the ones of the form

`omkafka: action will suspended due to kafka error -169: Local: Authentication failure [v8.2006.0 try https://www.rsyslog.com/e/2422 ]`

How to reproduce
================
- build rsyslog 8.2006.0 with librdkafka-1.4.0-devel
- configure the JAAS file on the Kafka side to have an `rsyslog` user with the `rsyslog-secret` password
- configure rsyslog to talk to kafka over SSL and authenticate using SASL

Checklist
=========

Please provide the following information:

 - [x] librdkafka version 1.4.0 (used to build omkafka, rpm from https://packages.confluent.io/rpm/5.5/7/)
 - [x] Apache Kafka version: 2.5.0
 - [x] librdkafka client configuration: 

~~~~
"security.protocol=SASL_SSL", "ssl.ca.location=/etc/ipa/ca.crt", "ssl.certificate.location=/etc/ipa/quattor/certs/host.pem", "ssl.key.location=/etc/ipa/quattor/keys/host.key", "sasl.mechanisms=PLAIN", "sasl.username=rsyslog", "sasl.password=rsyslog-secret", "debug=broker,security"
~~~~

 - [x] Operating system: CentOS 7.8
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka

debug=broker,security but I do not see anything appear in any logs, so I guess I am doing something wrong here.
https://gist.github.com/itkovian/6d752e5ca3bf88d9025821ff8941d7df

 - [x] Provide broker log excerpts: 

There's nothing to see in the broker that suggests an error. 

 - [ ] Critical issue

**Comment by edenhill** [comment]
With debug=broker,security you should be seeing quite a lot of debugging, so try to find out where it is emitted and then provide the logs to us. Thanks

**Comment by itkovian** [comment]
I think I may have found the culprit, although I am not sure this is the reason for the syslog lines I am seeing. Seems like there's the following issue: `Topics not in preferred replica for broker`. I tried to fix this, but no luck so far. I'll update this issue as I make progress.

**Comment by itkovian** [comment]
Output from kafkacat states:

~~~~
ERROR: Local: Authentication failure: sasl_ssl://kafka21.banette.os:9093/21: SASL PLAIN mechanism handshake failed: Broker: Request not valid in current SASL state: broker's supported mechanisms:  (after 0ms in state AUTH_HANDSHAKE)
~~~~

**Comment by itkovian** [comment]
@edenhill,

Here are the logs from kafkacat connecting to the same broker: https://gist.github.com/itkovian/6d752e5ca3bf88d9025821ff8941d7df

It is able to get consume messages: stuff I produce is consumed (all the lines that mention vsc40075).

Does the above help you or should I provide other/more data?

**Comment by edenhill** [comment]
It seems to be an issue with broker 21 not being configured with a proper SASL PLAIN listener, compare:
`%7|1594737497.004|SASLMECHS|rdkafka#consumer-1| [thrd:sasl_ssl://kafka21.banette.os:9093/21]: sasl_ssl://kafka21.banette.os:9093/21: Broker supported SASL mechanisms: `
to broker 22 which works:
`%7|1594737497.006|SASLMECHS|rdkafka#consumer-1| [thrd:sasl_ssl://kafka22.banette.os:9093/22]: sasl_ssl://kafka22.banette.os:9093/22: Broker supported SASL mechanisms: PLAIN`

**Comment by itkovian** [comment]
Thanks! I'll check our cfgmgmt :/

**Comment by thotapallin** [comment]
@itkovian - Were you able to fix the problem? We are also facing the same error.
