### ISSUE TITLE
Question: Could RdKafka::KafkaConsumer set the parameter RdKafka::Topic::OFFSET_BEGINNING, how do it?

### ISSUE THREAD

**Issue by zoust2018** [edenhill/librdkafka#2960]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>

how i can consumer msg from RdKafka::Topic::OFFSET_BEGINNING when using RdKafka::KafkaConsumer ?
(note: i kown how do it by using the api RdKafka::Consumer, but  RdKafka::KafkaConsumer ?)

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

my code:
        RdKafka::KafkaConsumer *consumer = RdKafka::KafkaConsumer::create(pshared_conf.get(), errstr);
	if (!consumer) {
		std::cerr << "Failed to create consumer: " << errstr << std::endl;
		exit(1);
	}

	pShared_kafka_consumer.reset(consumer);

	RdKafka::ErrorCode err = consumer->subscribe(m_vectTopics);
	if (err) {
		std::cerr << "Failed to subscribe to " << m_vectTopics.size() << " topics: "
			<< RdKafka::err2str(err) << std::endl;
		exit(1);
	}
	else
	{
	//	cout << "111 no err" << endl;
	}

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
If you want to use the committed offset if available, else start from the beginning, then simply set `auto.offset.reset` config property to `earliest`.

If you always want to start from the beginning but still want to use balanced consumer groups (subscribe()) then you will need register a RebalanceCb and set the start offset of each assigned partition to OFFSET_BEGINNING prior to calling assign() (from within the rebalance callback).
