### ISSUE TITLE
How to revive a partition when it fails with offset out of range and auto.offset.reset is set to error?

### ISSUE THREAD

**Issue by iolazarc** [edenhill/librdkafka#2961]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
As mentioned in the title, I set auto.offset.reset to error and in addition use custom offset management.
The simple example of the issue is starting a new consumer for a topic: when partition is assigned, I specify offset 0 to start fetching from and that would usually be out of range for topics that have been around for a while. 
So the intent is to find another suitable offset to fetch from, but calls to Seek after an out of range error is encountered fail with ERR__STATE because the partition is in the none fetch state.
I don't want to have re-initialize the whole assignment of the consumer just because one partition has issues (due to not being able to indicate a "don't change alter fetch offset" value for partitions that are already fetching fine).
Why is it an error to seek a partition if fetching failed previously due to offset out of range before?

How to reproduce
================
Create a new consumer for a topic where offset 0 has been expired. Set assignment for the consumer to start fetching at offset 0 and make sure auto.offset.reset=error. Try to seek the partition after ERR_OFFSET_OUT_OF_RANGE is received.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.4.2
 - [x] Apache Kafka version: 2.3
 - [x] librdkafka client configuration: auto.offset.reset=error
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You will unfortunately need to call assign() again.
With the work on incremental rebalancing we will be providing an incremental_assign() that allows you to update a single partition, this is scheduled for Q3.

**Comment by iolazarc** [comment]
Thanks for the answer. Any chance to allow partition seek to resume fetching for a previously assigned partition in fetch state None?

**Comment by edenhill** [comment]
Yeah we'll revise this error logic. :+1:

**Comment by edenhill** [comment]
auto.offset.reset=error errors are now raised with RD_KAFKA_RESP_ERR__AUTO_OFFSET_RESET, and the application should call one of the assign*() methods to decide what to do next.
