### ISSUE TITLE
I cannot create topics through the Admin API.

### ISSUE THREAD

**Issue by zqian4321** [edenhill/librdkafka#2962]
Description
===========
I cannot create topics through the Admin API in kafka0.10.0.1, but i do create topics successfully  through the Admin API in kafka2.5.0. 

How to reproduce
================
Topics are created successfully using kafka-topics.sh, but failed through the Admin API.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.4.4
 - [x] Apache Kafka version: 0.10.0.1
 - [x] librdkafka client configuration: auto.create.topics.enable=false
 - [x] Operating system: ubuntu14.04
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by zqian4321** [comment]
Topics are created successfully with kafka-topics.sh(kafka2.5.0, kafka0.10.0.1) or the Admin API(kafka2.5.0).

**Comment by edenhill** [comment]
Please provide your code and debug logs with debug=admin,broker enabled. There is nothing to go on.

**Comment by zqian4321** [comment]
> Please provide your code and debug logs with debug=admin,broker enabled. There is nothing to go on.

code:
rd_kafka_conf_t* conf = rd_kafka_conf_new();
rd_kafka_conf_set(conf, "bootstrap.servers", "localhost:9092", errstr, sizeof(errstr));
rd_kafka_t* rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf, errstr, sizeof(errstr));
rd_kafka_NewTopic_t* topic[1];
topic[0] = rd_kafka_NewTopic_new("test", 6, 1, nullptr, 0);
rd_kafka_queue_t* rkqu = rd_kafka_queue_new(rk);
rd_kafka_CreateTopics(rk, topic, 1, nullptr, rkqu);

How to generate debug logs with debug=admin,broker enabled?  I use kafka_2.10-0.10.0.1 binary with default configs expect setting num.partitions=6 and auto.create.topic.enable=false

**Comment by edenhill** [comment]
CreateTopics is an asynchronous operation which signals completion on the provided queue.
You are not waiting for the results of CreateTopics.
See https://github.com/edenhill/librdkafka/blob/master/tests/test.c#L4026 for an example usage.

**Comment by zqian4321** [comment]
> CreateTopics is an asynchronous operation which signals completion on the provided queue.
> You are not waiting for the results of CreateTopics.
> See https://github.com/edenhill/librdkafka/blob/master/tests/test.c#L4026 for an example usage.

OK ,thanks. 
rd_kafka_event_error_string(rkev) = Topic Admin API (KIP-4) not supported by broker, requires broker version >= 0.10.2.0.
