### ISSUE TITLE
Is there a convenient way to disable SASL?

### ISSUE THREAD

**Issue by shfnet** [edenhill/librdkafka#2966]
Is there a convenient way to disable SASL?
Something in the spirit of `./configure --disable-sasl`, or a configuration somewhere would be perfect

Many thanks!

**Comment by edenhill** [comment]
By SASL I'm assuming you mean SASL GSSAPI/Kerberos and the sasl2 dependency?
On master you should be able to do `./configure --disable-sasl` to accomplish this.

**Comment by shfnet** [comment]
Fixed. Strange that I didn't see it myself.. 
anyway, thanks again!
