### ISSUE TITLE
The consumer does not consume all partitions fairly

### ISSUE THREAD

**Issue by syahiaoui** [edenhill/librdkafka#2969]
Description
===========
I use `node-rdkafka`  non-following mode consumer and each batch contains 2000 records, all consumer runs on hosts with  (8 cores).
The consumer consumes messages well, but as we can see in the picture below, each Kafka broker is the leader of two partitions and the consumer consumes only 1 partition:
![image](https://user-images.githubusercontent.com/12759390/86621198-0eba4000-bfbe-11ea-9799-7151d8c1e929.png)
Initially, the consumer commit messages manually, I changed it to auto-commit and I saw a marked improvement.

by activating the logs I see that the consumer fetch the messages which are already committed, is that normal?

![Consumer](https://user-images.githubusercontent.com/12759390/86621727-fe569500-bfbe-11ea-92cd-7c8d02a1a63b.PNG)
[node-rdkafka.log](https://github.com/edenhill/librdkafka/files/4880399/node-rdkafka.log)

Checklist
=========
 - librdkafka version (release number or git tag): `(v1.4.2)`
 - Apache Kafka version: `2.2.1`
 - node: v14.3.0 (same as 12.0.0) 
 -  librdkafka client configuration: 

```json
{
   "bootstrap.servers":[
      "10.121.0.1:9092",
      "10.121.0.2:9092"
   ],
   "socket.keepalive.enable":true,
   "enable.auto.commit":true,
   "group.id":"frg",
   "client.id":"rdo-stkqty-77",
   "enable.auto.offset.store":true,
   "max.poll.interval.ms":"200000",
   "partition.assignment.strategy":"roundrobin",
   "heartbeat.interval.ms":3000,
   "session.timeout.ms":10000,
   "fetch.message.max.bytes":548576,
   "queued.max.messages.kbytes":548576,
   "queued.min.messages":50000,
   "message.max.bytes":1000000,
   "fetch.wait.max.ms":0,
   "fetch.error.backoff.ms":100,
   "security.protocol":"SASL_PLAINTEXT",
   "sasl.mechanisms":"SCRAM-SHA-512",
   "sasl.username":"user",
   "sasl.password":"pwd-secret"
} ,  {"auto.offset.reset":"earliest"}
```
 - Operating system: `CentOS 7`
 - Provide logs ( `debug=consumer,cgrp,topic,fetch` ) from librdkafka

**Comment by champtar** [comment]
An old but similar issue: #1395

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#what-are-partition-queues-and-why-are-some-partitions-slower-than-others
