### ISSUE TITLE
question about "max.poll.interval.ms" config 

### ISSUE THREAD

**Issue by FantasyJXF** [edenhill/librdkafka#2971]
Description
===========
The default  value of `max.poll.interval.ms` is `300000ms`, which is `5 minutes`, when it costs more than `5 minutes` to consume one message, the machine would be kicked out of consumer group, which was not what I want.

Error message is as following:
```
EVENT_LOG-4-MAXPOLL: [thrd:main]: Application maximum poll interval (300000ms) exceeded by 12ms (adjust max.poll.interval.ms for long-running message processing): leaving group
```

How Can I pass the long runing message and keep my consumer alive? Since it might be bugs which make it so long 

How to reproduce
================
Once it met with a very time consuming message

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.3.0`
 - [ ] Apache Kafka version: `Not sure`
 - [ ] librdkafka client configuration: `default`
 - [ ] Operating system: `Centos 7(x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
As instructed by the log message you need to adjust max.poll.interval.ms to your maximum allowed processing time.

**Comment by FantasyJXF** [comment]
In my case, regular message usually takes less than 30 seconds, so the default '5 minutes' poll interval is enough for me.

When a message takes more than '5 minutes', I'd like to jump to the next message  but not abandon the consumer, so I think there might be a better way to solve my problem without change 'max.poll.interval.ms'. 😀

**Comment by FantasyJXF** [comment]
Maybe I shoulu realize the `throttle_cb`?

**Comment by edenhill** [comment]
`max.poll.interval.ms` works like a watchdog between the consumer and the application, the application needs to call poll() at least this often or the consumer will deem the application malfunctional and then leave the group.
`max.poll.interval.ms` should be set to the maximum allowed per-message processing time. If your processing can get stuck you need some other mechanism to unstuck the application so that poll() is called in due time.

throttle_cb is just for propagating information on when the *broker* throttles the client's connection.

**Comment by FantasyJXF** [comment]
Thanks, maybe the most simple way for me is to set a timeout during consuming a message.

**Comment by zhangxueyii** [comment]
I'm doing some research about this config and notice in this thread multiple messages mentions it's for the longest time for processing **one** message. it's misleading.

It's not for one message, it's for the max interval between two poll calls which means it's the total processing time for a set of messages that are polled at a time. (max.poll.records decides the number of messages, 500 by default.)
