### ISSUE TITLE
rd_kafka_poll() API question

### ISSUE THREAD

**Issue by adamkotwasinski** [edenhill/librdkafka#2972]
Is there any recommended way of interrupting (Producer) `rd_kafka_poll` / `Producer::poll` invocations?
(Effectively that would be something similar to Java client's `org.apache.kafka.clients.consumer.KafkaConsumer.wakeup()` that's capable of interrupting long-running polls).

The scenario where I'd find it useful is when we have poll-s done in separate thread (pseudocode):
```
while (running) {
  producer->poll(timeout)
}
```
This is not a problem as we can pick timeout e.g. = 1000, but for applications where we create multiple producers then it'd take some time unless we parallelize the shutdowns (what might not be viable for everyone).

**Comment by edenhill** [comment]
There's currently no means of interrupting a blocking rd_kafka_poll() call, but it is on our list of things to add.

**Comment by adamkotwasinski** [comment]
Thanks! 👍
