### ISSUE TITLE
Error after invoking consumer->poll(0)

### ISSUE THREAD

**Issue by bowu** [edenhill/librdkafka#2973]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
After seeking to position 0, consuming a message, a poll(0) always causes the following error:

*** rdkafka_queue.c:500:rd_kafka_q_serve: assert: res != RD_KAFKA_OP_RES_PASS ***

What could be the possible reasons?

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<d4360a57>`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you show relevant parts of your code, such as the poll loop and how you set up the consumer?

**Comment by bowu** [comment]
I just noticed that some comment says poll should never be used with KafkaConsumer. After removing poll, my code works fine.

**Comment by nikolaydimitrov** [comment]
> I just noticed that some comment says poll should never be used with KafkaConsumer. After removing poll, my code works fine.

Thanks, that helped. I converted my Consumer to KafkaConsumer and got the same error.
