### ISSUE TITLE
(Clarification) Consumer rd_kafka_message_destroy, order of calls

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#2977]
Hello Magnus,

A clarifying question. When the consumer retrieves a message after calling poll, is there any protection i need to make when the destroying that message? Some scenarios that i am thinking:

1. It is clear every message should be destroyed and only once.
2. Is it safe to call destroy from an arbitrary thread? (I believe this is yes.)
3. Is it safe to call rd_kafka_message_destroy, some arbitrary time later? (I believe this is yes.)
4. Most interesting for me, is it safe to call rd_kafka_message_destroy after the consumer handle has been freed? (Probably not).

**Comment by edenhill** [comment]
1. Yes
2. Yes
3. Yes, but this may have memory consequences, see https://github.com/edenhill/librdkafka/wiki/FAQ#explain-the-consumers-memory-usage-to-me .  TLDR: a single message_t may hold on to a larger receive buffer.
4. No, the consumer handle must be the last object destroyed.

**Comment by MaximGurschi** [comment]
Thank you as always!
