### ISSUE TITLE
messages from idempotent producer getting delayed 

### ISSUE THREAD

**Issue by sanjay24** [edenhill/librdkafka#2978]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
- I have an idempotent producer with the following configuration:
"linger.ms": "100"
"compression.codec": "snappy"
"enable.idempotence": "true"
"statistics.interval.ms": "5000"
"batch.num.messages": "100000"
"message.timeout.ms": "300000"
"queue.buffering.max.messages": "10000000"
- I'm calling rd_kafka_poll() after calling rd_kafka_produce

Problem: With the above configurations set,  messages produced from by the producer are getting delayed by ~5 minutes.
Same producer binary was connected to same Kafka cluster nodes (3 brokers), but, issue was observed on two of the binaries. 
I saw few message delivery failure errors, unfortunately, I don't have the exact errors from the delivery report. 

I have few questions will really appreciate any help/hints:

1. Do you think not calling rd_kafka_poll() periodically should result in such a scenario? though I do have a consistently steady stream of messages?
2. During the period when rd_kafka_poll() is not called, I see that a call to rd_kafka_outq_len() always gives an incremental value? is that expected?
3. A consistent delay of 5 mins is suggestive of "message.timeout.ms" coming into play. If the delivery report callback reports an error is it a guaranteed failure of the message or just means that message is being retried by rdkafka? 
4. Though i don't have the exact error reported by dr_callback, it appears that the message was retried internally and waited upto 5 min. Could you suggest some error scenario that might have lead to this issue (I know it will be too wide a guess) around? Could it be related to enable.idempotence property? There were no issues around the network or broker's health

How to reproduce
================
could not reproduce this later.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version v1.4.2
 - [ ] Apache Kafka version: 2.1.3
 - [x] librdkafka client configuration:
 - [x] Operating system:  Centos 7.7
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
1. librdkafka will only allow queue.buffering.max.messages to be handled at once, this includes both messages to be sent as well as delivery reports. so you will need to call poll() frequently to serve the delivery reports and make room for new messages.
2. Yes, see the API docs: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L4473
3. librdkafka will retry the message (if the error allows retrying), so when the delivery report is finally received by the application there is typically little the application can do to mitigate the issue, there is no point in trying to reproduce the message (and it will cause out of order messaging). Also see rd_kafka_message_status().
4. Sounds like connectivity issues, is there anything in the logs emitted by librdkafka? If you don't see anything, enable `debug=broker` in the producer config.

You should also check what the error is in the delivery report callback, in this case it is probably ERR__MSG_TIMED_OUT which abstracts connectivity issues, etc.

**Comment by sanjay24** [comment]
Thanks @edenhill for the response. I did further testing with debug=broker enabled.  Below is the error that I saw

```
[anonymous] [7] [BROKERFAIL] [thrd:host1045:9092/2]: host1045:9092/2: failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
[anonymous] [7] [FAIL] [thrd:host1045:9092/2]: host1045:9092/2: Disconnected (after 1199232ms in state UP)
[anonymous] [7] [STATE] [thrd:host1045:9092/2]: host1045:9092/2: Broker changed state UP -> DOWN
[anonymous] [7] [STATE] [thrd:host1045:9092/2]: host1045:9092/2: Broker changed state DOWN -> INIT
```

The broker's idle connection timeout is set to its default value. Not sure, if this is due to connection being idle, (though the uptime in the log shows close to 20min, as against 10 mins of idle timeout).

What do you think could be the reasons for this behavior?

**Comment by sanjay24** [comment]
@edenhill could you comment on the above please?

**Comment by edenhill** [comment]
Idle connection reaper seems plausible, could be that the last request was sent 10 minutes ago on that connection.
librdkafka v1.5.0 improves on this by reusing the least idle connection.

**Comment by sanjay24** [comment]
what's the best way to deal with connection reset by idle connection reaper?
Couple of solutions I could think of:
- setting  ``socket.timeout.ms``, ``message.timeout.ms`` to low value (I'm thinking of 500ms, that's ~4x the WAN rtt I have) and 
``reconnect.backoff.ms=0`` should ensure that any disconnection (either timeout or connection reset by peer) comes back up immediately? The application I'm working with has sporadic in-frequent message bursts (there's high likelihood of having multiple idle windows > 10 minutes). Would it insure that connection to broker(s) is restored immediately? 
- I assume setting ``socket.keepalive.enable`` doesn't impact idle connections?!
- Could you suggest other configuration/way without increasing the ``connections.max.idle.ms`` on broker to ensure that the connection to broker is kept alive?

**Comment by edenhill** [comment]
Why do you need to handle them? An idle connection being closed shouldn't have any effect on the operations since the connection wasn't used anyway.

Strongly advise against changing socket.timeout.ms.
message.timeout.ms should typically not be set below 10-30s to allow for temporary network issues.
socket.keepalive.enable will not help with idle connections.

**Comment by sanjay24** [comment]
My application works like a proxy to broker like below: 
data producer ----> myproxy ----> Kafka cluster
Problem with connections going idle (and closed) is that when "data producer" sends the data after idle connection reaping. The message delivery to Kafka cluster gets delayed heavily (close to 5 mins). These messages expect low latency guarantees, that's why I want someway to ensure that connects is kept alive OR is restored quickly in case it is reset.

**Comment by edenhill** [comment]
librdkafka will reconnect automatically if needed, it should definitely not take 5 minutes, that indicates something else is wrong.

I think we would need logs with `debug=broker,msg,topic,eos`  set to understand what is going on.
