### ISSUE TITLE
Dynamic changes to config file 

### ISSUE THREAD

**Issue by chkoilot** [edenhill/librdkafka#2983]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

We want to dynamically change the debug property of the config file in order to turn on and off debugging. Is there any guides on how to do this ?

How to reproduce
================

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.4.4`
 - [ x] Apache Kafka version: `2.5.0`
 - [ x] librdkafka client configuration: ``
 - [x ] Operating system: `Windows`
 - [x ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is currently not supported, configuration objects are immutable after client construction.
