### ISSUE TITLE
(Question) Stale messages arriving at broker

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#2984]
Related to #2734

Hi Magnus,

Is such a scenario possible?:
1. Producer sends 2 messages. M1 arrives and is committed at broker at partition offset 10. M2's status is unknown.
2. Client detects that M2 status is unknown.
3. Client queries the partition of the tail offset and it happens to be 10.
4.Client assumes M2 never made it to the broker.
5.BOOM! M2 arrives at broker and is committed.

I tried to trace the scala logic in the Kafka broker, and it seems that the query for the watermark does not reflect the most up to date commit. Is that your understanding as well, is it possible to arrive at step 5 where M2 gets committed after the offset is retrieved?

**Comment by edenhill** [comment]
If M1 and M2 are sent in different ProduceRequests it is very much possible for the watermark query (ListOffsetsRequest) to be sent between ProduceRequest 1 and 2.

**Comment by MaximGurschi** [comment]
Thanks Magnus, In my scenario the timelines are:
T1 - producer sends M1
T2 - producer "knows" M1 made it and is stored at offset 10
T3 - producer sends M2
T4 - producer "thinks" M2 might have not made it to the broker
T5 - producer queries ListOffsetsRequest
T6 - producer sees that the tail offset of the partition is 10, producer **assumes** that M2 must have been lost

The question is if it is safe to make the **assumption** at time T6? Can it be wrong and M2 getting committed at broker at some time after T6?

**Comment by edenhill** [comment]
If you use acks=all and have a replication factor of 3 you can be sure that a message for which you've seen a successful delivery report will have been successfully written to the partition log.
Querying for offsets seems error prone and slow.

**Comment by MaximGurschi** [comment]
Thank you, however the brokers send acks before data is fsynched. In any case this is unrelated to the scenario i describe.

In other words i was trying to establish the data consistency of querying watermarks. I believe the returned results from watermark querying can be stale. That is the issue i am concerned with.
