### ISSUE TITLE
How to count the success and failure of kafka sending messages

### ISSUE THREAD

**Issue by hyhtemple** [edenhill/librdkafka#2987]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
As mentioned above, I want to accurately count the success and failure of messages sent to kafka. At present, I use dr_cb callback function to make statistics. During the test, I found that some messages did not enter the callback function, resulting in inaccurate statistical information. What should I do to get correct statistical results

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `librdkafka-1.2.1`
 - [ ] Apache Kafka version: `kafka_2.11-1.0.0`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: ` CentOS Linux release 7.2.1511 (Core)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by hyhtemple** [comment]
this is my code, does it is correct ?
	void dr_cb (RdKafka::Message &message) 
	{
		//TODO use message.msg_opaque() to access user data
		string key = message.key() ? (*message.key()) : "";
		GLOGEX_D(("Message delivered! res=%s, len=%u, key=%s, topic=%s", message.errstr().c_str(), message.len(), key.c_str(), message.topic_name().c_str()));

		CpssKafkaProducer* pPtr = GetKafkaProducerPtr();
		if (pPtr)
		{
			CpssKafkaMsgCache* pMsgCache = pPtr->GetKafkaMsgCachePtr();

			if (message.err() == RdKafka::ERR_NO_ERROR)
			{
		              //do nothing
			}
			else
			{
				ProtectCountor::GetInstance()->DecreaseWorkThreadSuccess(KAFKA_MODULE_TYPE);
				CpssCountor::GetInstance()->DecreaseKafkaSuccess(message.topic_name());

				ProtectCountor::GetInstance()->IncreaseWorkThreadFailed(KAFKA_MODULE_TYPE);
				CpssCountor::GetInstance()->IncreaseKafkaFailed(message.topic_name());
		
		 }
	}





    //==========================================================================
	RdKafka::ErrorCode resp = mProducer->produce(strTopics,
												 m_nPartitionNum/*RdKafka::Topic::PARTITION_UA*/, 
												 RdKafka::Producer::RK_MSG_COPY,
												 const_cast<char *>(msg), 
												 len, 
												 index.c_str(), 
												 index.size(), 
												 0,
												 NULL);


	if (resp != RdKafka::ERR_NO_ERROR)
	{
		err = RdKafka::err2str(resp);
		GLOGEX_E(("Produce failed! topic=%s, resp=%u, err=%s, len=%u, msg=%s.", strTopics.c_str(), resp, err.c_str(), len, msg));

		ProtectCountor::GetInstance()->IncreaseWorkThreadFailed(KAFKA_MODULE_TYPE);
		CpssCountor::GetInstance()->IncreaseKafkaFailed(strTopics);

		mProducer->poll(CpssKafkaTimeToWait);

		return CPSS_KAFKA_ERROR;
	}

	ProtectCountor::GetInstance()->IncreaseWorkThreadSuccess(KAFKA_MODULE_TYPE);
	CpssCountor::GetInstance()->IncreaseKafkaSuccess(strTopics);
//==========================================================================

**Comment by edenhill** [comment]
All messages will get exactly one delivery report, but you need to call poll() at regular intervals to serve the delivery reports.
