### ISSUE TITLE
call to consume repeatedly failing with error "Replica not available"

### ISSUE THREAD

**Issue by adinigam** [edenhill/librdkafka#2988]
Description
===========
Librdkafka consumer->consume(250ms) call fails with "Replica not available"

How to reproduce
================
1) set configs : 
enable.auto.commit=false,
auto.offset.reset=beginning,
enable.partition.eof=true,
fetch.wait.max.ms=10,
fetch.error.backoff.ms=10,
statistics.interval.ms=600000
log_level=7,
debug=consumer,broker,topic,fetch
2) create consumer
and call consumer->consume(250ms) in while loop.
3) call consumer->query_watermark_offsets(...) repeatedly in background thread.

Note: we had been using librdkafka 1.2 and recently switched to librdkafka 1.4.2. This is when we started seeing above error.
Our thinking was client should refresh its metadata if leader changes occur, but many times it takes multiple hours to resume consuming.

[clientlogs.txt](https://github.com/edenhill/librdkafka/files/4917491/clientlogs.txt)
[brokerlogs.txt](https://github.com/edenhill/librdkafka/files/4917530/brokerlogs.txt)
[controllerlogs.txt](https://github.com/edenhill/librdkafka/files/4917544/controllerlogs.txt)

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.4.2`
 - [x] Apache Kafka version: `2.4`
 - [x] librdkafka client configuration: `enable.auto.commit=false,
auto.offset.reset=beginning,
enable.partition.eof=true,
fetch.wait.max.ms=10,
fetch.error.backoff.ms=10,
statistics.interval.ms=600000`
 - [x] Operating system: `windows`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Thanks for providing all necessary information!

This is a broker issue which is being fixed in Kafka v2.7: https://issues.apache.org/jira/projects/KAFKA/issues/KAFKA-10223?filter=allopenissues

But we're providing a work-around in librdkafka  v1.5.0 which will be released soon.

**Comment by adinigam** [comment]
@edenhill Thanks a lot for the information. This really helps.

Can you let me know if the workaround is already checked in and if we just take the workaround in librdkafka will it fix the problem for us with 1.4.2 ?
Reason i am asking is this is sort of critical for us and I am evaluating is we should wait for 1.5 OR revert to 1.2

**Comment by edenhill** [comment]
This patch should do it:
```patch
diff --git a/src/rdkafka_broker.c b/src/rdkafka_broker.c
index eaedb925..42126f50 100644
--- a/src/rdkafka_broker.c
+++ b/src/rdkafka_broker.c
@@ -4361,6 +4361,9 @@ rd_kafka_fetch_reply_handle (rd_kafka_broker_t *rkb,
                                case RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE:
                                case RD_KAFKA_RESP_ERR_NOT_LEADER_FOR_PARTITION:
                                case RD_KAFKA_RESP_ERR_BROKER_NOT_AVAILABLE:
+                                case RD_KAFKA_RESP_ERR_REPLICA_NOT_AVAILABLE:
+                                case RD_KAFKA_RESP_ERR_KAFKA_STORAGE_ERROR:
+                                case RD_KAFKA_RESP_ERR_FENCED_LEADER_EPOCH:
                                         /* Request metadata information update*/
                                         rd_kafka_toppar_leader_unavailable(
                                                 rktp, "fetch", hdr.ErrorCode);
```

Part of 6d13bb6f8d89038e6939fe1e7d0747e62407fab1

**Comment by adinigam** [comment]
thanks a lot!!
let me try the fix.

**Comment by adinigam** [comment]
fixes mentioned above so far seems to work for us.
