### ISSUE TITLE
++ Kafka producer does not support ignoration of "\0" character in Protocol Buffers (google flat buffers)

### ISSUE THREAD

**Issue by kohouja** [edenhill/librdkafka#2989]
C++ Kafka producer does not support ignoration of "\0" character in Protocol Buffers (google flat buffers)

Library version: 1.2.1, 1.4.1
Kafka server: https://github.com/confluentinc/cp-docker-images

Description
===========
I have got a problem with sending data which came from MQTT broker to Kafka topic without any loss, because if there is "0" value of some parameter in the message payload, Kafka producer indicates that as "\0" character which means end of byte array and payload in message is not delivered full into Kafka topic which is on server. 

I have tried:
1. Check the payload length which came from MQTT consumer and it is correct as full recieved message which is pushed into Kafka producer
2. I have tried to serve original payload length to kafka producer (problem still occurs)
3. "Google" some configuration on server side if there is not any mistake in config file, I have not found any parameter which is responsible for ignoring special characters
4. I have analyzed logs in server side and there is no error, at least as well in callback message from broker (message was delivered without any error, but it is just shorter, because it is cut with a first occurence of "\0" char)
5. reinstall the librdkafka ubuntu stable version 1.2.1, and built and installed latest 1.4.1 (problem still occured)

Is there any possibility to solve this problem?

Does librdkafka c++ support Protocol Buffers, Google flat buffers somehow?

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.2.1, 1.4.1`
 - [x] Apache Kafka version: `2.0.0`
 - [x] librdkafka client configuration: `auto.reset.offset=end`
 - [x] Operating system: `Ubuntu Server 2.0`
 - [x] Provide logs: NO exception, warning, error logs
 - [x] Provide broker log excerpts: NO exception, warning, error logs
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka never interpretes the produced or consumed data, it is treated as a binary blob with length specified separately.
Make sure your application treats the message data as binary (with length) rather than nul-terminated string.
