### ISSUE TITLE
For the c++ interface, is there a way to close the consumer connection cleanly without committing offsets?

### ISSUE THREAD

**Issue by witanswer** [edenhill/librdkafka#2992]
If my application has an issue while running, I may want to close the consumer connection without committing offset(s). I can't see a way to do that currently using the c++ api.
The Close() call automatically commits offsets. Am I missing something?

Thanks

librdkafka version:latest

**Comment by edenhill** [comment]
If you delete the KafkaConsumer object it will shut down without committing final offsets.

**Comment by witanswer** [comment]
sounds good thanks
