### ISSUE TITLE
dr_cb is never invoked if producer never connects broker.

### ISSUE THREAD

**Issue by prashankmehta** [edenhill/librdkafka#2997]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
dr_cb is never invoked if producer is not able to connect broker (due to bad broker url or network policy, in both case it will never connect).
The things become interesting, if an application manages payload lifetime (say by storing on heap) and sends payload by not RK_MSG_COPY or  RK_MSG_FREE, application expects to free the payload on dr_cb.
If producer never succeeds to connect broker, it invokes event_cb once with error 'ERR__ALL_BROKERS_DOWN' but never returns original payload ptr for application to delete.

My concern is, that message never times out or never runs out of retries so dr_cb never get's invoked on polling thread. This results in memory leak in my application.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x]  librdkafka version (release number or git tag): RD_KAFKA_VERSION  0x010404ff -> 1.4.4 ?
 - [x] Apache Kafka version: 2.5.0
 - [x] librdkafka client configuration: Issue is replicable with any configs
For simplicity and faster error out:
queue.buffering.max.messages = 10
queue.buffering.max.ms = 100
message.timeout.ms = 200
message.send.max.retries=1
log.connection.close=false
"metadata.broker.list", "randomabcd:9091"

 - [x] Operating system: RHEL
 - [x] Critical issue

**Comment by edenhill** [comment]
If there is no connection to produce the messages the messages will time out after `message.timeout.ms` (roughly).

Are you seeing `message.timeout.ms` on the global `rd_kafka_conf_t` object or on the `rd_kafka_topic_conf_t` topic config object?
If the former (which is preferable), make sure that you don't specify a default_topic_config, nor any config objects passed to topic_new(), since both of those approaches will overwrite the topic-level properties set on the global conf_t object.

**Comment by prashankmehta** [comment]
I am using C++ API and observing  'message.timeout.ms' in topic configuration. i.e. via RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC).

Yes, I was passing the default topic config and as you mentioned, it was overriding the default topic config.

After modification, I set  message.timeout.ms to topic configuration and it behaves as expected.
Thank you for your response.
