### ISSUE TITLE
can you build linux arm64 package 

### ISSUE THREAD

**Issue by CrazyJson** [edenhill/librdkafka#3000]
This package is currently required for Linux ARM64.There is no official version of this package, and I tried to compile it myself, but failed.Can you help compile a Linux ARM64 package

**Comment by edenhill** [comment]
Suggest you build librdkafka from source on ARM64 and install it on the target system, the .NET client should be able to discover it automatically.

**Comment by CrazyJson** [comment]
Hello, I manually compiled librdKafka ARM64 version of so file, the program boot times the following exception

Unhandled exception. System.InvalidOperationException: No such configuration property: "client.software.name" at Confluent.Kafka.Impl.SafeConfigHandle.Set(String name, String value) in E:\xx\CANetLibvip\Confluent.Kafka\Impl\SafeConfigHandle.cs:line 116 at Confluent.Kafka.Producer2.<>c__DisplayClass51_0.<.ctor>b__4(KeyValuePair2 kvp) in E:\xx\CANetLibvip\Confluent.Kafka\Producer.cs:line 620 at System.Collections.Generic.List1.ForEach(Action1 action) at Confluent.Kafka.Producer2..ctor(ProducerBuilder2 builder) in E:\xx\CANetLibvip\Confluent.Kafka\Producer.cs:line 617 at Confluent.Kafka.ProducerBuilder2.Build() in E:\xx\CANetLibvip\Confluent.Kafka\ProducerBui`

Trying to reference the source code comment NameAndVersionConfig configuration, a new exception appears
internal static List<KeyValuePair<string, string>> NameAndVersionConfig { get { return new List<KeyValuePair<string, string>> { new KeyValuePair<string, string>( "client.software.name", "confluent-kafka-dotnet"), new KeyValuePair<string, string>( "client.software.version", VersionString ) }; } }

[root@arm-253 kafkatest]# dotnet KafakTest.dll bootstrap.servers---192.168.10.10:21005,192.168.10.11:21005,192.168.10.12:21005 %3|1595321326.325|FAIL|rdkafka#producer-1| [thrd:192.168.10.11:21005/bootstrap]: 192.168.10.11:21005/bootstrap: Connect to ipv4#192.168.10.11:21005 failed: Connection refused %3|1595321326.325|ERROR|rdkafka#producer-1| [thrd:192.168.10.11:21005/bootstrap]: 192.168.10.11:21005/bootstrap: Connect to ipv4#192.168.10.11:21005 failed: Connection refused

**Comment by CrazyJson** [comment]
The same code runs on a Linux X64 server without any problems

[root@elk197 kafkatest]# dotnet KafakTest.dll Delivered 'test' to 'test-topic [[0]] @1'

**Comment by edenhill** [comment]
What version of librdkafka did you build?

**Comment by CrazyJson** [comment]
Is there any heat to arm64 so library compilation

**Comment by edenhill** [comment]
As for the connection errors, that is outside the client's control. Check your docker/emulator/network settings.

**Comment by CrazyJson** [comment]
Network setup should be fine, Linux X64 running normally server IP 192.168.0.197 Linux ARM64 connection denied IP :192.168.0.253

**Comment by CrazyJson** [comment]
I was able to connect by testing Telnet
![image](https://user-images.githubusercontent.com/8163485/88037064-042fa700-cb77-11ea-875d-4dfa224f95ac.png)

**Comment by CrazyJson** [comment]
[root@arm-253 kafkatest]# dotnet KafakTest.dll
bootstrap.servers---192.168.10.10:21005,192.168.10.11:21005,192.168.10.12:21005
%3|1595323439.435|FAIL|rdkafka#producer-1| [thrd:192.168.10.11:21005/bootstrap]: 192.168.10.11:21005/bootstrap: Connect to ipv4#192.168.10.11:21005 failed: Connection refused
%3|1595323439.435|ERROR|rdkafka#producer-1| [thrd:192.168.10.11:21005/bootstrap]: 192.168.10.11:21005/bootstrap: Connect to ipv4#192.168.10.11:21005 failed: Connection refused
^C
[root@arm-253 kafkatest]# telnet 192.168.10.10 21005
Trying 192.168.10.10...
Connected to 192.168.10.10.
Escape character is '^]'.

**Comment by edenhill** [comment]
The client can't connect to 192.168.10.11, not 192.168.10.10.

**Comment by CrazyJson** [comment]
I rebuilt a single node Kafka, Telnet working.No response after starting the test program, librdkafka1.4.4 1.5.0 has been tried

**Comment by CrazyJson** [comment]
![image](https://user-images.githubusercontent.com/8163485/88242723-a7d89e80-ccc0-11ea-92b5-52ee8b093398.png)

**Comment by CrazyJson** [comment]
![image](https://user-images.githubusercontent.com/8163485/88242748-bcb53200-ccc0-11ea-81bf-9cfd2cccddc1.png)

**Comment by CrazyJson** [comment]
![image](https://user-images.githubusercontent.com/8163485/88242757-c5a60380-ccc0-11ea-8dba-c625bf82eac1.png)

**Comment by CrazyJson** [comment]
Could you please help me to see what the problem is? I can provide an ARM64 server for you to test

**Comment by edenhill** [comment]
The logs state that 192.168.10.11:21005 can't be connected to, but you're telnetting to another address.

**Comment by CrazyJson** [comment]
Thank you, I have compiled successfully

**Comment by avivgold098** [comment]
@CrazyJson 
Can you share how you done it please? What is the required setup?

**Comment by MarkPare** [comment]
@CrazyJson also interested in what the fix was for you.
