### ISSUE TITLE
[SASL_SSL] Truststore SSL_CTX_use_certificate:passed a null parameter

### ISSUE THREAD

**Issue by Freerider689** [edenhill/librdkafka#3002]
Description
===========
When trying to connect to our Kafka Broker with SASL_SSL we run into the problem that the following error is thrown:

```
./rdkafka_example -C \
                   -t test-topic \
                   -p 1 \ 
                   -b ***:443 \
                   -X receive.message.max.bytes=1213486160 -X security.protocol=sasl_ssl \
                   -X ssl.keystore.location=/**/truststore.p12 \
                   -X ssl.keystore.password=**\
                   -X sasl.mechanisms=SCRAM-SHA-512 \
                   -X sasl.username=test-user \ 
                   -X sasl.password=** \
                   -X ssl.endpoint.identification.algorithm=https \
                   -d all 

>> 1595258986.997 RDKAFKA-7-SASL: rdkafka#consumer-1: [thrd:app]: Selected provider SCRAM (builtin) for SASL mechanism SCRAM-SHA-512
>> 1595258986.997 RDKAFKA-7-OPENSSL: rdkafka#consumer-1: [thrd:app]: Using OpenSSL version OpenSSL 1.1.1 11 Sep 2018 (0x1010100f, librdkafka built with 0x1010100f)
>> 1595258986.999 RDKAFKA-7-SSL: rdkafka#consumer-1: [thrd:app]: Loading client's keystore file from /**/truststore.p12 % 
>> Failed to create new consumer: Failed to use ssl.keystore.location certificate: ../ssl/ssl_rsa.c:305: error:140AB043:SSL routines:SSL_CTX_use_certificate:passed a null parameter
``` 

How to reproduce
================

1. Create truststore with root CA and child certs for Kafka 
2. Create consumer with truststore

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.5.0-RC2`
 - [x] Apache Kafka version: `2.3.1`
 - [x] librdkafka client configuration: `see command`
 - [x] Operating system: `Ubuntu 15 (x64)`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts (not accessible)
 - [x] Critical issue

**Comment by edenhill** [comment]
That error seems to indicate that the PKCS does not contain a certificate for the key, use `openssl pkcs12 -info -infile your_pkcs_file` to verify the contents.

**Comment by Freerider689** [comment]
Problem was solved, thx very much ^^
