### ISSUE TITLE
Topics which are created during a rebalancing won't trigger a new rebalancing

### ISSUE THREAD

**Issue by ArneSchulze** [edenhill/librdkafka#3008]
Hi, 
my team and I are using the Node.js library [`node-rdkafka`](<https://github.com/Blizzard/node-rdkafka>) and encountered an issue during rebalancing which I believe is a bug in `librdkafka`. Because we are using the bindings it's not that easy for me to check whether the issue is already resolved on the latest master.

Description
===========
A topic that is created during a rebalancing (while the consumer is executing the rebalancing callback) will not trigger a new rebalancing when using the subscribe-via-regex feature. In our custom rebalancing process we have to initialize/clean-up some state before we can assing/unassign partitions which may take a few seconds. If a topic is created while we are initializing state, it will not trigger a rebalancing. Subsequent topic creations, after the rebalancing finished, will however trigger a rebalancing which will then also include the previously created topic.

How to reproduce
================
1. Create a consumer using the subscribe-via-regex feature
2. Create a topic while the consumer is doing a rebalancing

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.4.2`
 - [x] Apache Kafka version: `2.12-2.4.0`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `macOS 10.15.5`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
New topics will be discovered, and trigger a rebalance, within `topic.metadata.refresh.interval.ms`.
