### ISSUE TITLE
Additional brokers listed in statistics in a dns alias setup

### ISSUE THREAD

**Issue by Boskovits** [edenhill/librdkafka#3010]
Description
===========
I am working with librdkafka in a kerberized environment with dns aliases. In the statistics json I see that the aliases are listen in a state: INIT, and the real fqdns as UP. It this behavior expected?

Checklist
=========

 - [x] librdkafka version (release number or git tag): 1.4.0
 - [x] Apache Kafka version: 2.7.0
 - [x] librdkafka client configuration: [bootstrap.servers=alias1,alias2,alias3|client.id=kafka_1|compression.codec=zstd|debug=all|enable.idempotence=true|enable.partition.eof=false|linger.ms=1|log_level=6|message.timeout.ms=300000|partitioner=murmur2_random|queue.buffering.max.messages=1000000|kerberos parameters|statistics.interval.ms=1000]
 - [x] Operating system: RHEL6, brokers on RHEL7

**Comment by edenhill** [comment]
Each specified bootstrap broker will have its own stats entry.

**Comment by Boskovits** [comment]
Yes, the bootstrap brokers are listed, but they are listed twice. When we have three brokers configured, than we get entries for six. Three with the dns aliases, and another three with the real fqnds.

**Comment by edenhill** [comment]
Brokers are solely identified by their hostname:port, if you add bootstrap.servers with non-matching names to what is reported from the broker's advertisted.listeners, then there will be "duplicates".

https://github.com/edenhill/librdkafka/wiki/FAQ#number-of-broker-tcp-connections
