### ISSUE TITLE
Setting up SASL/OAUTHBEARER for kafka client

### ISSUE THREAD

**Issue by magel20** [edenhill/librdkafka#3017]
Description
===========
I am trying to consume message from a server which requires SASL/OAUTHBEARER for authentication. I assume that this should be possible with this lib since this https://github.com/edenhill/librdkafka/pull/2189. The problem I currently have is that with the code documentation and the configuration description I can not fully figure out how to use. And besides that I only found explanations on how to set up sasl with kerberos. Are there other explanations or examples available which I did not find?

In my case I get the access_token, the refresh_token and the corresponding expiration dates via an rest_interface of the server and not from kafka. Does this somehow effect what I need to do within my client? My current understanding is that I have to implement an oauthbearer_token_refresh_cb function which takes care about getting the access_token. But what happens if the access_token expires, how do I recognize that?

Also I am not sure for what the oauthbearer config is usually used and whether I need it in my case. In the description some keys are mentioned (e.g. principalClaimName, principal) which I don not know how to use or whether I do not need them at all.

How to reproduce
================

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `43b8bc17986a23ad2ad45cebeef61ca3689d2f81`
 - [x] Apache Kafka version: `2.5`
 - [x] librdkafka client configuration: ` security.protocol: sasl_plaintext, sasl.mechanism: OAUTHBEARER`
 - [x] Operating system: `Windows 10 (x64)`
 - [-] Provide logs (with `debug=..` as necessary) from librdkafka 
 - [-] Provide broker log excerpts
 - [-] Critical issue

**Comment by magel20** [comment]
I have solved some issues in the meantime, so a short update also with some new questions.

> In my case I get the access_token, the refresh_token and the corresponding expiration dates via an rest_interface of the server and not from kafka. Does this somehow effect what I need to do within my client? My current understanding is that I have to implement an oauthbearer_token_refresh_cb function which takes care about getting the access_token. But what happens if the access_token expires, how do I recognize that?
>
> Also I am not sure for what the oauthbearer config is usually used and whether I need it in my case. In the description some keys are mentioned (e.g. principalClaimName, principal) which I don not know how to use or whether I do not need them at all.

This is working now. oauthbearer_token_refresh_cb(...) gets called automatically once the access token expires. For this to work you need to pass the  correct token_value and md_lifetime_ms to oauthbearer_set_token(...). I did not use the oathbearer config at all so it seems to be possible to use it without the config.

But I still have one question. I have to pass a md_principal_name to oauthbearer_set_token(...), but I do not know what this should be. First I just passed the current username and this worked. But if I pass a wrong username or just some random string it also works. So the question for me is what is the actual use of this parameter?

Also I have one question regarding this comment in the code:
>The refresh operation is eventable and may be received when an event
 callback handler is set with an event type of
 \c RdKafka::Event::EVENT_OAUTHBEARER_TOKEN_REFRESH.

I tried to handle this event with my existing event callback, but I cannot find the  'RdKafka::Event::EVENT_OAUTHBEARER_TOKEN_REFRESH' event. If I search the code I only find this event: 'RD_KAFKA_EVENT_OAUTHBEARER_TOKEN_REFRESH' .

And also I am not sure if it is really necessary to handle this event because at least to me it seems like the lib is already handling it because the oauthbearer_token_refresh_cb(...) function is getting called correctly once the token expires. So do I need to handle this event on my own or not?

**Comment by edenhill** [comment]
>  I have to pass a md_principal_name to oauthbearer_set_token(...), but I do not know what this should be.

I believe that's up to the broker-side oauthbearer authenticator to decide how it is used.

> I tried to handle this event with my existing event callback

It is only available as a callback in C++, not as en Event.
