### ISSUE TITLE
SSL Handshake failure regardless of passed configs

### ISSUE THREAD

**Issue by Arkh1** [edenhill/librdkafka#3018]
Description
===========
> [2020-07-29 14:17:52,630] INFO [SocketServer brokerId=0] Failed authentication with /127.0.0.1 (SSL handshake failed) (org.apache.kafka.common.network.Selector)

We are getting an SSL handshake failure in our ssl environment when using librdkafka. The non-ssl environments are working as expected.  We have connected to this cert using other node -> kafka solutions, but we would like to use librdkafka (via node-rdkafka).  We know the path and password for the keystore are correct since they work with other libraries.

Let me know if I can provide any other information to help debug. Any assistance would be greatly appreciated.

Thanks in advance!

Checklist
=========
 - [x] librdkafka version (release number or git tag): `1.4.2`
 - [x] Apache Kafka version: `2.5.0`
 - [x] librdkafka client configuration:
``` javascript
'client.id': 'clientId',
'metadata.broker.list': 'brokerList',
'request.timeout.ms': 3000,
'message.send.max.retries': 3,
'debug': 'all'
'security.protocol': 'ssl',
'ssl.cipher.suites': 'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256',
'ssl.keystore.location': '/path/to/keystore.p12',
'ssl.keystore.password': 'keystorePassword'
```
 - [x] Operating system: `MacOS Catalina`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

 - [x] Node Version: 12.14.1
 - [x] NPM Version: 6.13.4

**Comment by edenhill** [comment]
Can you try using the `openssl s_client` cli with your keystore to see if it manages to connect to the broker, if not it should provide more information on what is going on?

**Comment by Arkh1** [comment]
We were able to connect via the openssl s_client.  We have narrowed it down to a version mismatch issue related to using Node 12 + openssl 1.0.2.  We are getting a segfault error due to the version mismatch.  Currently trying to get all of our environments, build machines, etc on openssl 1.1.1d.

**Comment by Arkh1** [comment]
After getting our build environment, runtime environment & Node openssl versions on 1.1.1 we were able to get it to work.
