### ISSUE TITLE
Losing data somewhere after ->produce()

### ISSUE THREAD

**Issue by skandragon** [edenhill/librdkafka#302]
For my fun and exciting problem of the week...  :)

I have a producer which is committing around 1.4 million < 16k messages to a topic.

If I use 1 partition, I get only 38% of the messages actually in the topic.
If I use 2, I get 66%.
If I use 3, I get 96%.
If I use 4, I get 99.99%.

This is not linear.

Test machines:  2 machines, set up as a 2 broker cluster.  24 cores each, raid 10 setup that isn't really being pushed hard.  10 GE connections.

I plan on writing a simple test case, but thought I'd open the ticket first in case someone has wisdom.

I do have a delivery report callback, but it's not reporting any errors.

**Comment by edenhill** [comment]
To debug this I suggest you add a stats_cb and collect the stats somewhere for later review,
this will help figuring out where messages are going.

It might also be useful to add the occassional call to `rd_kafka_dump()` to dump the internal state of all topics and partitions, which also shows message counters.

**Comment by skandragon** [comment]
I have a capture of the stats, but didn't see anything immediately obvious.  However, our logger truncates the message.  I'll modify this to dump to a file soon.

Note this only happens on the "big iron" boxes.  It works perfectly on my laptop, where it's easy to debug... of course.

**Comment by skandragon** [comment]
Here is a typical stats line:

**Comment by edenhill** [comment]
Short and concise, bordering on overly frugal.

**Comment by skandragon** [comment]
I think we found the root cause.  "queue full".

We've started a "rdkafka best practices" internal doc, which shows how to handle this.  I'll close, as it was misuse on our end.  :)

**Comment by edenhill** [comment]
That's good news!

If you find the documentation (rdkafka.h, rdkafkacpp.h and INTRODUCTION.md) lacking, please feel free to improve it :)
