### ISSUE TITLE
Confusing comment regarding offset when pausing consumption

### ISSUE THREAD

**Issue by jerrylzy** [edenhill/librdkafka#3023]
The comment I refer to is here: https://github.com/edenhill/librdkafka/blob/5203235a974fcbc74725e962973e622f7b16c02d/src/rdkafka_partition.c#L1809
https://github.com/edenhill/librdkafka/blob/5203235a974fcbc74725e962973e622f7b16c02d/src/rdkafka_partition.c#L1810

It seems to contradict @edenhill 's reply to an issue in the confluent-kafka-dotnet repo: https://github.com/confluentinc/confluent-kafka-dotnet/issues/672#issuecomment-438605215

    Pause() will store the offset of the last message Consume()d by the application as the next offset to fetch when Resume() is called.

So let's say we consumed at partition 0 offset 1 and then called `Pause()` on partition 0.

Will the next `Consume()` call after `Resume()` return the same message we just consumed at offset 1 or a new message at offset 2? What is `rktp->rktp_app_offset` referring to in the code?
https://github.com/edenhill/librdkafka/blob/5203235a974fcbc74725e962973e622f7b16c02d/src/rdkafka_partition.c#L1812

Thank you very much.

**Comment by mhowlett** [comment]
librdkafka shouldn't give you a message you're already consumed before pause after resume. I just quickly updated the .net integration tests to check for this, as i didn't see an existing integration test covering it. https://github.com/confluentinc/confluent-kafka-dotnet/pull/1379

**Comment by jerrylzy** [comment]
> librdkafka shouldn't give you a message you're already consumed before pause after resume. I just quickly updated the .net integration tests to check for this, as i didn't see an existing integration test covering it. [confluentinc/confluent-kafka-dotnet#1379](https://github.com/confluentinc/confluent-kafka-dotnet/pull/1379)

Thanks for the integration test. Now, I understand that `Consume` will return a new message at offset 2 in my example.

If we use auto-commit, then a new call to `Consume()` will commit the offset of the last `Consume()` call. Does this apply as well when the consumer is paused? Let's say a Kafka consumer
1. Consumes message A at offset 0
2. Consumes message B at offset 1 and commits offset 0
3. Gets paused
4. `Consume()` is called again
5. Gets resumed
6. `Consume()` is called again and returns a new message C.

When will offset 1 be committed? Is it in step 4 or step 6? Thanks.

**Comment by FTQ03008** [comment]
> librdkafka shouldn't give you a message you're already consumed before pause after resume. I just quickly updated the .net integration tests to check for this, as i didn't see an existing integration test covering it. [confluentinc/confluent-kafka-dotnet#1379](https://github.com/confluentinc/confluent-kafka-dotnet/pull/1379)

Does this applicable to auto.commit enabled? or disabled? or both?

**Comment by edenhill** [comment]
Offsets are stored for the next  auto commit just prior to passing the message to the application.
See `enable.auto.offset.store=false` to get more fine-grained control of this
