### ISSUE TITLE
Crash on: rdkafka_roundrobin_assignor.c:97

### ISSUE THREAD

**Issue by plachor** [edenhill/librdkafka#3024]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Our application is based on dotnet 3.1. Until now we used `Confluent.Kafka` library `1.4.2` without issues.

After upgrade to `1.5.0` we found on our CI that our integration tests in docker-based environment are broken. Tests fail with log entry:

> The active test run was aborted. Reason: Test host process crashed : dotnet: rdkafka_roundrobin_assignor.c:97: rd_kafka_roundrobin_assignor_assign_cb: Assertion `next < rd_list_cnt(&eligible_topic-> members)' failed.

Same tests run OK when started from Windows host directly from visual studio.
Same test run OK also when running them locally on Windows using `dotnet test` command (same runner used in docker)

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.5.0` (through `Confluent.Kafka`)
 - [x] Apache Kafka version: `2.1.0`
 - [x] librdkafka client configuration: `partition.assignment.strategy=RoundRobin, api.version.request=true`
 - [x] Operating system: `docker-image based on: mcr.microsoft.com/dotnet/core/sdk:3.1.201`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by plachor** [comment]
this was already reported on https://github.com/confluentinc/confluent-kafka-dotnet/issues/1369

**Comment by TheFireCookie** [comment]
Nice work!
When is it forecast to release a new version with this fix?
Thanks,
Matthias.

**Comment by edenhill** [comment]
Mid october.
