### ISSUE TITLE
librdkafka does not read the Intermediate Certificate Store on Windows

### ISSUE THREAD

**Issue by saherahwal** [edenhill/librdkafka#3025]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
On Windows with EnableSSLVerification set to true, only the Root store certificates are accessed. The intermediate cert store is not accessed. 

In my use case, we have 2 certs, one in the Root store and another one issued by the former one to be found in the Intermediate certificate authorities store. 
When I import that 2nd certificate into the Root store, everything works. However, one the certificate remains in the Intermediate Store (where it should be as Intermediate cert), it doesn't work.

I looked at the latest code and it looks like the Root store is only opened and we never read from other stores.

```
/**
 * @brief Attempt load CA certificates from the Windows Certificate Root store.
 */
static int rd_kafka_ssl_win_load_root_certs (rd_kafka_t *rk, SSL_CTX *ctx) {
        HCERTSTORE w_store;
        PCCERT_CONTEXT w_cctx = NULL;
        X509_STORE *store;
        int fail_cnt = 0, cnt = 0;
        char errstr[256];

        w_store = CertOpenStore(CERT_STORE_PROV_SYSTEM,
                                0,
                                0,
                                CERT_SYSTEM_STORE_CURRENT_USER,
                                L"Root");
```

How to reproduce
================
If you have 2 certificates part of chain where one is root and the other is intermediate. SSL handshake will fail when enabling SSL verification at the client side. 

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Would it help if the store name was configurable, or would it need to scan both "Intermediate" and "Root" by default (and is that safe?)?

**Comment by edenhill** [comment]
Cert stores are now configurable.

**Comment by saherahwal** [comment]
I believe it needs to scan both in our case. 
With what confluent version is this fix associated ?

**Comment by edenhill** [comment]
Try configuring ssl.windows.certificate.store=Intermediate,Root

**Comment by saherahwal** [comment]
Thanks @edenhill 
what setting this corresponds to in the Confluent https://github.com/confluentinc/confluent-kafka-dotnet/search?q=Certificate library ?

Many Thanks
Saher

**Comment by teoring** [comment]
I am wonder if it is possible to use Intermediate CA on Linux.
