### ISSUE TITLE
Documentation does not clarify if timeout is treated consistently in all functions

### ISSUE THREAD

**Issue by andrewthad** [edenhill/librdkafka#3027]
The documentation for `rd_kafka_poll` makes it clear that a timeout of -1 is a special value that means to wait forever:

> To wait indefinately [sic] for an event, provide -1.

However, other functions that take at timeout argument like `rd_kafka_consumer_poll` and `rd_kafka_flush` make no such mention. I'll put up a PR clarifying this in the documentation if someone can tell me what the expected behavior here is.

**Comment by edenhill** [comment]
Right, -1 means infinite, 0 means immediate, >0 means specific timeout.

**Comment by edenhill** [comment]
And yes, it works like that in pretty much all the APIs that take a timeout_ms
