### ISSUE TITLE
Invalid value "none" for configuration property "auto.offset.reset"

### ISSUE THREAD

**Issue by natemurthy** [edenhill/librdkafka#3028]
Description
===========
I recently deployed a service using the `auto.offset.reset = none` setting per the Kafka consumer documentation on this config property (http://kafka.apache.org/documentation/#auto.offset.reset) and discovered that this is an invalid value upon seeing the error log:
```
Invalid value "none" for configuration property "auto.offset.reset"
```
I'm looking for an equivalent albeit differently named setting. Is `error` in librdkafka equivalent to the `none` value in the Java library for this config property?

How to reproduce
================
Easy: just create a consumer with this config property set to what's described above and try connecting to a Kafka broker.

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.4.0`
 - [x] Apache Kafka version: `2.1.0`
 - [x] librdkafka client configuration: 
```
{"auto.offset.reset":"none","bootstrap.servers":"REDACTED","enable.auto.commit":true,"go.events.channel.enable":true,"go.events.channel.size":0,"group.id":"REDACTED","log_level":0,"message.max.bytes":4194304,"ssl.ca.location":"/etc/ca/ca.pem","ssl.certificate.location":"/etc/certs/tls.crt","ssl.key.location":"/etc/certs/tls.key"}
```
 - [x] Operating system: `debian:stretch-slim`
 - [x] Provide logs (see above)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rolandyoung** [comment]
According to the respective docs, yes, librdkafka `error` is the equivalent of Apache Kafka `none` for `auto.offset.reset`

Kafka docs:
> * none: throw exception to the consumer if no previous offset is found for the consumer's group

libdrkafka docs (https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md or https://docs.confluent.io/current/clients/librdkafka/md_CONFIGURATION.html):
>  'error' - trigger an error which is retrieved by consuming messages and checking 'message->err'.

**Comment by natemurthy** [comment]
@rolandyoung that is how I am interpreting it. Would love to get an authoritative response on this from @edenhill or any of the other core maintainers as well.

**Comment by edenhill** [comment]
@rolandyoung is right, use `error` and check the message's error field. There's unfortunately no specific error code for offset resets, so an application can't really know that the consumer error is because of an offset reset (yes, this will be improved).
