### ISSUE TITLE
dr_cb in C++ doesn't seem to work

### ISSUE THREAD

**Issue by skandragon** [edenhill/librdkafka#303]
I am setting the dr_cb using:

```
    if (conf->set("dr_cb", &dr_callback_, error) != RdKafka::Conf::CONF_OK)
```
(with proper error checking, which verifies an error was not indicated)

However, this callback is never called.  I am not setting delivery.report.only.error, so the default false should keep this from being called only on errors.

I have added a printf() inside both dr_msg_cb_trampoline() and Producer::create() to verify it is being set, and called.  Only the setting printf triggers:

```
    if (confimpl->dr_cb_) {
      printf("dr_cb set\n");
      rd_kafka_conf_set_dr_msg_cb(rk_conf, dr_msg_cb_trampoline);
      rkp->dr_cb_ = confimpl->dr_cb_;
    }
```

```
static void dr_msg_cb_trampoline (rd_kafka_t *rk,
                                  const rd_kafka_message_t *
                                  rkmessage,
                                  void *opaque) {
printf("Got here!\n");
  RdKafka::HandleImpl *handle = static_cast<RdKafka::HandleImpl *>(opaque);
  RdKafka::MessageImpl message(NULL, rkmessage);
  handle->dr_cb_->dr_cb(message);
}
```

**Comment by skandragon** [comment]
Same bug as "if all brokers are down, dr_msg_cb isn't called"

**Comment by edenhill** [comment]
If all brokers are down the message is propbably waiting for time out, which by default (`message.timeout.ms`) is 300 seconds.
