### ISSUE TITLE
Cannot produce messages

### ISSUE THREAD

**Issue by jzb1006** [edenhill/librdkafka#3033]
Below is my log

version:0.11.6

%7|1597657596.017|SASL|rdkafka#producer-1| [thrd:app]: Selected provider PLAIN (builtin) for SASL mechanism PLAIN
%7|1597657596.017|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v0.11.6 (0xb06ff) rdkafka#producer-1 initialized (builtin.features 0xffff, debug 0xffff)
%7|1597657596.017|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1597657596.017|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1597657596.017|BROADCAST|rdkafka#producer-1| [thrd::0/internal]: Broadcasting state change
%7|1597657596.017|WAKEUPFD|rdkafka#producer-1| [thrd:app]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Enabled low-latency partition queue wake-ups
%7|1597657596.017|WAKEUPFD|rdkafka#producer-1| [thrd:app]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Enabled low-latency ops queue wake-ups
%7|1597657596.018|BROKER|rdkafka#producer-1| [thrd:app]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Added new broker with NodeId -1
%7|1597657596.018|TOPIC|rdkafka#producer-1| [thrd:app]: New local topic: ChatLog
%7|1597657596.018|BRKMAIN|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Enter main broker thread
%7|1597657596.018|CONNECT|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: broker in state INIT connecting
%7|1597657596.018|TOPPARNEW|rdkafka#producer-1| [thrd:app]: NEW ChatLog [-1] 0x55b6def9ecd0 (at rd_kafka_topic_new0:362)
%7|1597657596.018|METADATA|rdkafka#producer-1| [thrd:app]: Skipping metadata refresh of 1 topic(s): no usable brokers
%7|1597657596.018|DESTROY|rdkafka#producer-1| [thrd:app]: Terminating instance (destroy flags none (0x0))
%7|1597657596.018|TERMINATE|rdkafka#producer-1| [thrd:app]: Interrupting timers
%7|1597657596.019|TERMINATE|rdkafka#producer-1| [thrd:app]: Sending TERMINATE to internal main thread
%7|1597657596.019|TERMINATE|rdkafka#producer-1| [thrd:app]: Joining internal main thread
%7|1597657596.019|TERMINATE|rdkafka#producer-1| [thrd:main]: Internal main thread terminating
%7|1597657596.019|DESTROY|rdkafka#producer-1| [thrd:main]: Destroy internal
%7|1597657596.019|BROADCAST|rdkafka#producer-1| [thrd:main]: Broadcasting state change
%7|1597657596.019|DESTROY|rdkafka#producer-1| [thrd:main]: Removing all topics
%7|1597657596.019|TOPPARREMOVE|rdkafka#producer-1| [thrd:main]: Removing toppar ChatLog [-1] 0x55b6def9ecd0
%7|1597657596.019|DESTROY|rdkafka#producer-1| [thrd:main]: ChatLog [-1]: 0x55b6def9ecd0 DESTROY_FINAL
%7|1597657596.019|TERMINATE|rdkafka#producer-1| [thrd:main]: Purging reply queue
%7|1597657596.019|TERMINATE|rdkafka#producer-1| [thrd:main]: Decommissioning internal broker
%7|1597657596.019|TERMINATE|rdkafka#producer-1| [thrd:main]: Join 2 broker thread(s)
%7|1597657596.020|TERM|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Received TERMINATE op in state UP: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1597657596.020|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1597657596.020|FAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Client is terminating (after 2ms in state UP)
%7|1597657596.020|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state UP -> DOWN
%7|1597657596.020|BROADCAST|rdkafka#producer-1| [thrd::0/internal]: Broadcasting state change
%7|1597657596.020|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Purging bufq with 0 buffers
%7|1597657596.020|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Purging bufq with 0 buffers
%7|1597657596.020|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Updating 0 buffers on connection reset
%7|1597657596.020|TERMINATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Handle is terminating in state DOWN: 1 refcnts (0x55b6def9d710), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1597657596.020|BROKERFAIL|rdkafka#producer-1| [thrd::0/internal]: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
%7|1597657596.020|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Purging bufq with 0 buffers
%7|1597657596.020|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Purging bufq with 0 buffers
%7|1597657596.020|BUFQ|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Updating 0 buffers on connection reset
%7|1597657596.045|CONNECT|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Connecting to ipv4#118.25.170.130:9092 (sasl_plaintext) with socket 6
%7|1597657596.046|STATE|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Broker changed state INIT -> CONNECT
%7|1597657596.046|BROADCAST|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: Broadcasting state change
%7|1597657596.046|TERMINATE|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Handle is terminating in state CONNECT: 1 refcnts (0x55b6def9e270), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1597657596.046|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Operation now in progress)
%7|1597657596.046|STATE|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Broker changed state CONNECT -> DOWN
%7|1597657596.046|BROADCAST|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: Broadcasting state change
%7|1597657596.046|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Purging bufq with 0 buffers
%7|1597657596.046|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Purging bufq with 0 buffers
%7|1597657596.046|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Updating 0 buffers on connection reset
%7|1597657596.046|TERM|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Received TERMINATE op in state DOWN: 1 refcnts, 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs
%7|1597657596.046|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Operation now in progress)
%7|1597657596.046|FAIL|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Client is terminating (after 0ms in state DOWN)
%7|1597657596.046|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Purging bufq with 0 buffers
%7|1597657596.046|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Purging bufq with 0 buffers
%7|1597657596.046|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentclou]: sasl_plaintext://ckafka-epk0cfr4.ap-shanghai.ckafka.tencentcloudmq.com:9092/bootstrap: Updating 0 buffers on connection reset
%7|1597657596.046|TERMINATE|rdkafka#producer-1| [thrd:main]: Internal main thread termination done
%7|1597657596.046|TERMINATE|rdkafka#producer-1| [thrd:app]: Destroying op queues
%7|1597657596.046|TERMINATE|rdkafka#producer-1| [thrd:app]: Termination done: freeing resources

**Comment by edenhill** [comment]
Looks like you are terminating the producer one millisecond after creating it.
produce() is asynchronous, you will need to use flush() or poll() to wait for the delivery before closing down the producer.
