### ISSUE TITLE
Document restrictions on timeout values

### ISSUE THREAD

**Issue by andrewthad** [edenhill/librdkafka#3034]
If a call `rd_kafka_flush` and try to get it to wait for an hour by setting the timeout to 3600000, it immediately fails with `RD_KAFKA_RESP_ERR__TIMED_OUT`. I've not looked through the source code, but I have a suspicion that an overflow is happening. If milliseconds is being converting to nanoseconds somewhere, then that would suggest that on platform with a 32-bit C `int`, timeouts a little greater than 2 seconds should not work. If that were the case though, I suspect this would have already been noticed. What is the maximum support milliseconds that is allowed as a timeout?

**Comment by edenhill** [comment]
You are right, I believe it is this line that overflows the int:
https://github.com/edenhill/librdkafka/blob/master/src/rdtime.h#L182

Which limits timeouts to 1.5 days.

Casting timeout_ms to rd_ts_t (int64_t) should do the trick.
