### ISSUE TITLE
Question: which debug flag should I use in production environment

### ISSUE THREAD

**Issue by eelyaj** [edenhill/librdkafka#3037]
Description
===========

I set log_cb and error_cb callback function in my kafka producer and consumer application.

Which of the following debug config should I set in production environment to observe librdkafka.
generic, broker, topic, metadata, feature, queue, msg, protocol, cgrp, security, fetch, interceptor, plugin, consumer, admin, eos, mock, all

I don't want to set it to 'all'. because there are too many logs.

Please provide the following information:

 - [x] librdkafka version 1.1.0
 - [x] Apache Kafka version: 2.2.1
 - [ ] librdkafka client configuration: 
 - [x] Operating system: centos 7
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You typically don't need to enable any debugging unless you're having problems with your Kafka client.

See the 'Suggested debugging contexts' in the manual:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#debug-contexts
