### ISSUE TITLE
Question: consuming from 10k topics with optional wildcards

### ISSUE THREAD

**Issue by robambalu** [edenhill/librdkafka#3040]
Hi.  Im just getting started with kafka and I'm trying to add it to our internal framework in a generic way so other users can leverage it.  I've read through the docs and looked through the code but I'm still having a hard time figuring this out.
Say I have many topics, 1 per stock, so lets say roughly 10k topics.  
A user applications may arbitrarily subscribe to some or all topics.  Some applications may want to subscribe to all symbols as a wildcard.
Im trying to understand the best way to map topics to consumers properly.  As far as I can see the pattern is to create 1 thread per consumer.  Given that limitation, I clearly cant create 1 consumer per topic since that would require too many threads.
So it seems I would have to create N consumers ( based on how many threads I want to use for processing msgs ), and round robin topic subscriptions  to each.  Then each thread would have to poll for new messages, check the topic that the message is for and then route it to the correct subscriber in my code.
This already sounds cumbersome and a burden on the developer, but ok its not the end of the world, keep a mapping of topic -> my internal subscribers and I'm good.
Now throw in the wrench of wildcard topics.  If I want to subscribe to 4k topics and 10 wildcard topics, for example, now what?  When I get a message I would have to scan through all my wildcard subscriptions and regex match to see who matches?
This doesn't sound right to me, especially since the kafka consumer is already doing this regex filtering it seems odd that I would have to do it on my end as well ( and I hope that I can match the regex matching logic used by kafka ).  If the message mentioned which subscription topic it was for ( so the rgex, not the actual topic ) that would be ok too.
It feels like I might be missing something here.

Thanks in advance
- Rob

**Comment by edenhill** [comment]
Having a separate topic per user/ticker/someotheridentity is an anti-pattern. You should be using a topic per type of data, and the use key-based partitioning for multiplexing.
