### ISSUE TITLE
is there a way to generate Broker: Unknown topic or partition error code forcefully?

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#3043]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I would like to simulate one issue in my application, so is there any way to generate "Broker: Unknown topic or partition" error code forcefully?

**Comment by edenhill** [comment]
Which API do you want to return that error from?

**Comment by write2jaydeep** [comment]
in producer API, dr_msg_cb() I wanted to simulate the error_code 3

**Comment by edenhill** [comment]
You could use the mock cluster and inject the error code for the ProduceRequest, see here for inspiration:
https://github.com/edenhill/librdkafka/blob/master/tests/0105-transactions_mock.c#L152
