### ISSUE TITLE
Question: high CPU usage on idle consumers, help needed to profile!

### ISSUE THREAD

**Issue by archetec** [edenhill/librdkafka#3047]
So we have a high CPU usage problem on Windows when our Kafka cluster becomes unstable.  Our consumers are using Confluent's client and librdkafka 1.5.  I profiled the program in VS2019 and the CPU utilization is located in a "native" module so I suspect librdkafka.dll but can't confirm.  Since I don't have a pdb, I can't load symbols for that module.

This problem only occurs when the cluster is unstable and consumers are trying to reconnect.  At some point, each instance of consumer starts using between 20-40% of a CPU, sometimes even more.  On our server farms with many of these instances the usage is sometimes so high that our admins can't login into remote admin consoles.

I don't have enough data to submit a bug but I would like to do so. I tried to recompile my own librdkafka and succeeded, but only with dynamic links to openssl libs and I suspect this doesn't work because when I replace the dlls in my solution with the ones I built, it fails to load (pretty sure there's a dependency missing).

Is there a quick guide on how to do this? It would be so easy if symbols would be provided with the Nuget package!

Thanks for the help and best regards.

**Comment by edenhill** [comment]
You could try grabbing the pdbs from the AppVeyor build:
https://ci.appveyor.com/project/edenhill/librdkafka/builds/34195443/job/8cmr2seitto6n5xx/artifacts

**Comment by archetec** [comment]
Hello Magnus.  Thanks, it worked, partially.  I can load symbols in debug in VS2019, but looks like I can't get them to load in the profiler.  I don't know why.  Maybe it's a limitation of the profiler with dynamically linked native dlls or something. I'm trying to find a solution...
