### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by orenIsabella** [edenhill/librdkafka#3051]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I recieve multiple errors that i cant fix:
$ npm install node-rdkafkah
npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/node-rdkafkah - Not found
npm ERR! 404 
npm ERR! 404  'node-rdkafkah@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/isabella/.npm/_logs/2020-08-28T11_00_38_935Z-debug.log

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<1.2.1-1ubuntu1">`
 - [x] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `<ERR! 404  'node-rdkafkah@latest' is not in the npm registry>`
 - [x] Operating system: `<ubuntu (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rolandyoung** [comment]
This is not the right place to report a bug with the [Node.js wrapper for Kafka](https://github.com/blizzard/node-rdkafka)

But your problem is a typo in the npm command. It should be `npm install node-rdkafka` (no trailing 'h')
