### ISSUE TITLE
Question regarding rdkafka_broker.h

### ISSUE THREAD

**Issue by accelerated** [edenhill/librdkafka#3052]
Hi @edenhill, I just wanted to know if rdkafka_broker.h is meant to be used publicly? I would like to get broker status events for the application, currently this is available only by logging with `debug:broker` option, but is there a way to use any of the callbacks in the rdkafka_broker.h file?

Thanks!

**Comment by edenhill** [comment]
@accelerated No, only rdkafka.h (and rdkafka_mock.h) are public in the C interface and you should not integrate with the internal API.
What you can do is enable statistics to extract the broker states, but read this https://github.com/edenhill/librdkafka/wiki/FAQ#i-want-to-get-an-event-when-brokers-come-up-and-down

**Comment by accelerated** [comment]
@edenhill Thank you!
