### ISSUE TITLE
No `bootstrap.servers` configured: client will not be able to connect to Kafka cluster

### ISSUE THREAD

**Issue by DinoStray** [edenhill/librdkafka#3054]
I upgrade librdkafka from 1.4.2 to 1.5.0, then got the following error:
```
[kafka]-5-CONFWARN: rdkafka#producer-1[thrd:app]: No `bootstrap.servers` configured: client will not be able to connect to Kafka cluster
[kafka]-7-PROTOERR: rdkafka#producer-1[thrd:172.16.138.114:9092/bootstrap]: 172.16.138.114:9092/bootstrap: Protocol parse failure for ApiVersion v3 at 3/6 (rd_kafka_handle_ApiVersion:1945) (incorrect broker.version.fallback?)
[kafka]-7-PROTOERR: rdkafka#producer-1[thrd:172.16.138.114:9092/bootstrap]: 172.16.138.114:9092/bootstrap: ApiArrayCnt -1 out of range
```
My kafka version: 2.2.0

**Comment by DinoStray** [comment]
I use rd_kafka_conf_set after rd_kafka_brokers_add, then the first error removed:
```
[kafka]-5-CONFWARN: rdkafka#producer-1[thrd:app]: No `bootstrap.servers` configured: client will not be able to connect to Kafka cluster
```
But others still there

**Comment by DinoStray** [comment]
I have to set "bootstrap.servers" again, then everything is OK. Although I had called rd_kafka_brokers_add()

**Comment by DinoStray** [comment]
Finally, I confirm that, I do not need update kafka.

**Comment by edenhill** [comment]
Right, this warning is emitted if no bootstrap.servers are configured, this was added because new users sometimes miss to configure it and wonder why nothing happens.
brokers_add() is a legacy API that should typically not be used, but it is still fine to use but you will see this warning.

**Comment by studiawan** [comment]
> 
> 
> Finally, I confirm that, I do not need update kafka.
> The only thing I need to do is just set "bootstrap.servers" , and not call rd_kafka_brokers_add()

Hi @DinoStray how can we set "bootstrap.servers"? Is there any config file we should set?
Thanks.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/blob/master/examples/producer.c#L108

**Comment by studiawan** [comment]
Thank you.
