### ISSUE TITLE
C++ queues that contain both messages and non-messages

### ISSUE THREAD

**Issue by t3nsor** [edenhill/librdkafka#3056]
This is a feature request (I think).

The C++ API has the Queue class, but it seems that it doesn't support queues that contain a mixture of messages and events such as delivery callbacks. If I were to construct such a queue, I would not be allowed to call `poll`, since the comment says that `poll` may not be used on queues that contain messages. If I call `consume`, I won't get any delivery callbacks.

I think that in the C API, the equivalent functionality already exists: one can set up the queue and then call `rd_kafka_queue_poll` which would return a `rd_kafka_event_t*` which could refer to EITHER a fetch event or a delivery event (or some other event types). But the C++ API doesn't have an equivalent function. So if one has a `Producer` and a `KafkaConsumer` I think the only way to do it is to call `c_ptr()` and then use the C API, but there's no guarantee that this works properly when mixed with usage of the C++ API.

**Comment by edenhill** [comment]
Since that's an advanced use-case the recommendation is to use the C API directly for this, and not mix in C++.
