### ISSUE TITLE
Protocol parse failure for ApiVersion v3 at 3/6 (rd_kafka_handle_ApiVersion:1945) (incorrect broker.version.fallback?)

### ISSUE THREAD

**Issue by DinoStray** [edenhill/librdkafka#3057]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
If I use librdkafka `1.5.0` connet to kafka `2.1.1`, then the log show errors as below.  
But produce message or consume message is OK.  
And if I use kafka `2.6.0`, there is no error.

Checklist
=========

 - [x] librdkafka version: `1.5.0`
 - [ ] Apache Kafka version: `2.1.1`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `ubuntu 18.04`
 - [ ] Provide logs
```
[kafka]-7-PROTOERR: rdkafka#producer-2[thrd:172.16.138.118:9092/bootstrap]: 172.16.138.118:9092/bootstrap: Protocol parse failure for ApiVersion v3 at 3/6 (rd_kafka_handle_ApiVersion:1945) (incorrect broker.version.fallback?)
[kafka]-7-PROTOERR: rdkafka#producer-2[thrd:172.16.138.118:9092/bootstrap]: 172.16.138.118:9092/bootstrap: ApiArrayCnt -1 out of range
```
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That's a debug message (level 7) which is only shown if you have debugging enabled, it can be safely ignored.

**Comment by DinoStray** [comment]
@edenhill Where can I get All the log level info?
https://github.com/edenhill/librdkafka/wiki/FAQ

**Comment by edenhill** [comment]
They are the standard syslog severity levels, see https://en.wikipedia.org/wiki/Syslog
