### ISSUE TITLE
rdkafka:: Kafka consumer:: create  memory leaks

### ISSUE THREAD

**Issue by dada0708** [edenhill/librdkafka#3061]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>
Rdkafka:: kafaconsumer * consumer = rdkafka:: Kafka consumer:: create (CONF, errstr); memory leaks will appear in the above line after close and delete. I used Valgrind test in centos7 and found that:

==15546== 9,526 bytes in 8 blocks are still reachable in loss record 664 of 665
==15546==    at 0x4C2C089: calloc (vg_replace_malloc.c:762)
==15546==    by 0x400B1EE: _dl_new_object (in /usr/lib64/ld-2.17.so)
==15546==    by 0x4006013: _dl_map_object_from_fd (in /usr/lib64/ld-2.17.so)
==15546==    by 0x4008659: _dl_map_object (in /usr/lib64/ld-2.17.so)
==15546==    by 0x4014293: dl_open_worker (in /usr/lib64/ld-2.17.so)
==15546==    by 0x400F7C3: _dl_catch_error (in /usr/lib64/ld-2.17.so)
==15546==    by 0x4013B7A: _dl_open (in /usr/lib64/ld-2.17.so)
==15546==    by 0x6CB8FAA: dlopen_doit (in /usr/lib64/libdl-2.17.so)
==15546==    by 0x400F7C3: _dl_catch_error (in /usr/lib64/ld-2.17.so)
==15546==    by 0x6CB95AC: _dlerror_run (in /usr/lib64/libdl-2.17.so)
==15546==    by 0x6CB9040: dlopen@@GLIBC_2.2.5 (in /usr/lib64/libdl-2.17.so)
==15546==    by 0x6AAF503: _sasl_get_plugin (in /usr/lib64/libsasl2.so.3.0.0)
==15546== 
==15546== 16,384 bytes in 1 blocks are still reachable in loss record 665 of 665
==15546==    at 0x4C2C291: realloc (vg_replace_malloc.c:836)
==15546==    by 0x648A6A8: CRYPTO_realloc (in /usr/lib64/libcrypto.so.1.0.2k)
==15546==    by 0x6542770: lh_insert (in /usr/lib64/libcrypto.so.1.0.2k)
==15546==    by 0x6545209: ??? (in /usr/lib64/libcrypto.so.1.0.2k)
==15546==    by 0x6544BCA: ??? (in /usr/lib64/libcrypto.so.1.0.2k)
==15546==    by 0x6546839: ERR_load_crypto_strings (in /usr/lib64/libcrypto.so.1.0.2k)
==15546==    by 0x61F08C8: SSL_load_error_strings (in /usr/lib64/libssl.so.1.0.2k)
==15546==    by 0x511E7C5: rd_kafka_transport_ssl_init (in /root/c-workspace/kafka/consumer-cpp/lib/librdkafka.so)
==15546==    by 0x5098FBF: rd_kafka_global_cnt_incr (in /root/c-workspace/kafka/consumer-cpp/lib/librdkafka.so)
==15546==    by 0x509CEEB: rd_kafka_new (in /root/c-workspace/kafka/consumer-cpp/lib/librdkafka.so)
==15546==    by 0x4E5AFF4: RdKafka::KafkaConsumer::create(RdKafka::Conf*, std::string&) (in /root/c-workspace/kafka/consumer-cpp/lib/librdkafka++.so)
==15546==    by 0x402C43: KafkaConsumer::consumer() (kafkaconsumer.cpp:187)
==15546== 
==15546== LEAK SUMMARY:
==15546==    definitely lost: 0 bytes in 0 blocks
==15546==    indirectly lost: 0 bytes in 0 blocks
==15546==      possibly lost: 0 bytes in 0 blocks
==15546==    still reachable: 119,220 bytes in 3,451 blocks
==15546==         suppressed: 0 bytes in 0 blocks

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Those are one-time initializations of global data in OpenSSL and Cyrus-sasl, there is no safe way to decommission these at librdkafka object destruction and it is not a problem since these allocations will only be done once per runtime.

**Comment by edenhill** [comment]
There is a suppressions file you can use to silence these:
https://github.com/edenhill/librdkafka/blob/master/tests/librdkafka.suppressions

**Comment by dada0708** [comment]
> There is a suppressions file you can use to silence these:

Well, thank you very much.

**Comment by dada0708** [comment]
@edenhill Well, thank you very much.
