### ISSUE TITLE
kafka session /  heartbeat timeout problem

### ISSUE THREAD

**Issue by sofire** [edenhill/librdkafka#3064]
Recently, my kafka client had session timeout problems:
2020-09-09 10:10:55 SESSTMOUT, [thrd:main]: Consumer group session timed out (in join-state started) after 10008 ms without a successful response from the group coordinator (broker 1, last error was Success): revoking assignment and rejoining group (level: 4)

I used tcpdump on broker server, and found the reason: broker's response took long time (over 10s).

10:10:46.963744	— client request
10:10:57.064160	— broker response

I want to know why and how to resolve this problem.
Can I change this config:
session.timeout.ms 10s -> 30s

In librdkafka, client send one heartbeat request, and wait for response,  not send every 3s.
Can I change it to sending heartbeat every 3s?

thanks.

kafka version: 2.4.1
librdkafka: 1.4.2
php-rdkafka: 4.0.3

**Comment by edenhill** [comment]
librdkafka will just have one outstanding Heartbeat at the time, but you are free to increase the session.timeout.ms property.

**Comment by sofire** [comment]
Thanks for replying.

Increasing the session.timeout.ms dos not resolved the problem.
I stopped one broker and seem ok now.

Btw:
I think this code is wrong:  
errcnt ? offsets->cnt : errcnt, offsets->cnt,

should be:
errcnt ? errcnt : offsets->cnt, offsets->cnt,

rdkafka_cgrp.c rd_kafka_cgrp_op_handle_OffsetCommit function
`
rd_kafka_log(rkcg->rkcg_rk, LOG_WARNING, "COMMITFAIL",
                             "Offset commit (%s) failed "
                             "for %d/%d partition(s): "
                             "%s%s%s",
                             rko_orig->rko_u.offset_commit.reason,
                             errcnt ? offsets->cnt : errcnt, offsets->cnt,
                             errcnt ? rd_kafka_err2str(err) : "",
                             errcnt ? ": " : "",
                             tmp)
`

**Comment by edenhill** [comment]
> I think this code is wrong:

Thank you, will fix.

**Comment by edenhill** [comment]
Sounds like you have a faulty broker.
