### ISSUE TITLE
ConsumeException: Broker: Unknown topic or partition

### ISSUE THREAD

**Issue by czd890** [edenhill/librdkafka#3065]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

[trace.kafka.log](https://github.com/edenhill/librdkafka/files/5192705/trace.kafka.log)

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
1.5.1
 - [x] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
``shell
'bootstrap.servers' = 'broker0.kafka.org:9092,broker1.kafka.org:9092,broker2.kafka.org:9092'.
'auto.offset.reset' = 'earliest'.
'enable.auto.commit' = 'false'.
'group.id' = 'xCurrency.SummarizeTick'.
'debug' = 'cgrp,fetch,topic,broker,protocol'
```
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka

**Comment by edenhill** [comment]
Because the topic `MyTopicName` does not seem to exist in the cluster.
This is a new feature in v1.5.0, see the release notes Upgrade considerations:
https://github.com/edenhill/librdkafka/releases/tag/v1.5.0
