### ISSUE TITLE
Feature request: broker rack information in BrokerMetadata

### ISSUE THREAD

**Issue by koushikchitta** [edenhill/librdkafka#3070]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
BrokerMetadata currently supports id, host, port properties, it would be helpful to support broker rack information as well.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.4.*`
 - [x] Apache Kafka version: `2.4`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Dup of #1158
