### ISSUE TITLE
Question - Create a topic with r replicas and p partitions

### ISSUE THREAD

**Issue by prabcs** [edenhill/librdkafka#308]
Hi,

I'm using librdkafka to create topics and send messages to kafka
Could you please give some pointers to minimalistic code to create a topic with r replicas and p partitions?

Thanks

**Comment by edenhill** [comment]
There is currently no way to create partitions with specific configuration values through the Kafka protocol, you'll need to use the kafka-topic.sh tool bundled with Kafka.

For future reference see this KIP:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations

**Comment by prabcs** [comment]
so, my question was: while creating a topic through Topic::Create, can I specify how many partitions I want in the topic, instead of creating the topics offline through kafka-topic.sh ?

**Comment by edenhill** [comment]
Sorry, thats not possible, there is no such functionality in the Kafka protocol at this point.
