### ISSUE TITLE
Question: Unable to receive information from kafka(v0.8.2.2)

### ISSUE THREAD

**Issue by Leo-Lin20** [edenhill/librdkafka#3081]
@edenhill 
I cannot receive data from Kafka(v0.8.2.2), I use the librdkafka(v1.5)

I have completed the version configuration, like:
```cpp
rd_kafka_conf_set(conf, "api.version.request", "false", errstr, sizeof(errstr));
rd_kafka_conf_set(conf, "broker.version.fallback", "0.8.2.2", errstr, sizeof(errstr));
```

You said [here](https://github.com/edenhill/librdkafka/issues/751) before

> You can still access kafka 0.8.1 broker with latest librdkafka (See here: https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility) but consumer groups requires broker 0.9 or later

But if I don’t configure "group.id", the program will report an error：Failed to subscribe to 1 topics: Local: Unknown group

So what should I do, look forward to your answer

Thank you so much!

**Comment by edenhill** [comment]
subscribe() requires consumer group support on the broker, which was added in 0.9.
