### ISSUE TITLE
Request: Async metadata API

### ISSUE THREAD

**Issue by vojtechkral** [edenhill/librdkafka#3085]
Description
===========

The function `rd_kafka_metadata()` is synchronous. I haven't found a way to obtain metadata asynchronously. I am using librdkafka from Rust with Tokio and the `rd_kafka_metadata()` being synchronous complicates things... It shouldn't be called from an async context (so as not to block a thread executing async tasks), it could be called from an external thread, but then one has to synchronize ownership of the client between the async context and the external thread... I expect the client shouldn't be destroyed while another thread blocks in the metadata call, right?

All other features of the library seem to fit in very nicely with async Rust, especially thanks to the `rd_kafka_queue_cb_event_enable()` which can be used to notify async tasks to be scheduled. It works really well. The Metadata API is the only problem as far as I know...

How to reproduce
================
Try to use `rd_kafka_metadata()` from an async environment...

Checklist
=========

 - [x] librdkafka version (release number or git tag): 1.3.0 to current master (4af2ca0)
 - [x] Apache Kafka version: Any
 - [x] librdkafka client configuration: N/A
 - [x] Operating system: N/A
 - [x] Critical issue: No

**Comment by vojtechkral** [comment]
So far my workaround is to move the client entirely into the blocking thread and then move it back after completion or error.

**Comment by edenhill** [comment]
Let's get this into #1158
