### ISSUE TITLE
get_watermark offsets timeout not firing

### ISSUE THREAD

**Issue by jdye64** [edenhill/librdkafka#3089]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
==========
When using the C++ api I am unable to successfully make the get_watermark offsets time-out Fire? I’m wondering if I missing a configuration, callback, or?? That might be causing this?

How to reproduce
================
- create c++ class with KafkaConsumer
- call get_watermark_offsets with timeouts of 10s
- call hangs and never returns

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Fixed on master

**Comment by chinmaychandak** [comment]
That's great, thank you so much, @edenhill. Could you please point me to the PR that fixed it? Curious about the issue & fix in the code base.

**Comment by edenhill** [comment]
5514d2de87d41a6283b92fab32b964908dedae02 rewrote some of the leader query handling.

v1.6.0 is scheduled in circa 2 weeks.

**Comment by chinmaychandak** [comment]
I see 1.6.0 has been release on PyPI. :) Any ETA for a conda release?

**Comment by chinmaychandak** [comment]
My bad - I meant to ask about the ETA for Confluent Kafka's 1.6.0 Conda release, and not librdkafka. I'll create an issue there, if that's okay.
