### ISSUE TITLE
Clarify how to use batching with balanced consumer groups

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [edenhill/librdkafka#3093]
Description
===========

I'm writing an OCaml binding to librdkafka and I want it to use the modern APIs. The FAQ states that balanced consumers are created via `rd_kafka_subscribe`, which is exactly the behaviour I want. But I also want each of the consumers to consume batches, which leaves me in a weird spot because the batching APIs seem to be part of the simple consumer.

To understand how this is in other bindings I checked how out Python code does that and arrived at this piece of code: https://github.com/confluentinc/confluent-kafka-python/blob/5aa6439df081ead048932ee395085236ef0bca9d/confluent_kafka/src/Consumer.c#L939-L941

What I see there is that it uses `rd_kafka_consume_batch_queue`. When I consult with the FAQ I see that it distinguishes between balanced consumer groups and legacy simple consumers. Since I want to use balanced consumer groups I want the former, but checking the API documentation of `rd_kafka_consume_batch_queue` redirects me to `rd_kafka_consume_batch` which states:

`rd_kafka_consume_batch() provides higher throughput performance than rd_kafka_consume().

Checking from here `rd_kafka_consume` states the following:

`Consumer must have been previously started with rd_kafka_consume_start().`

Which according to the FAQ is part of the legacy simple consumer API. Therefore I don't understand, is this part of both APIs? Do the Python bindings do something wrong (since they seemingly support consumer groups and batching)?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.5.0
 - [X] Apache Kafka version: 2.3.0
 - [X] librdkafka client configuration: `group.id=mygroup`
 - [X] Operating system: Any
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

(Sorry, lots of that information I can't provide because it is a documentation issue)

**Comment by edenhill** [comment]
Your best option is to make your own batching wrapper function:
 * First set `enable.auto.offset.store` to `false`. This makes sure no message is marked as handled (by the app) when consumer_poll() returns.
 * Loop over consumer_poll() until your timeout or message count is reached.
 * If a rebalance happens while accumulating a batch, throw away the accumulated messages and start over from scratch.
 * Have the application call store_offsets() when it is done processing the batch (or per message). The stored offset is what will be auto-committed by the consumer, so it is important that a stored offset is not set before the application has a chance to process a message, and it should preferably be set after the message has been processed (at-least-once delivery, as opposed to at-most-once delivery if stored prior to processing).
