### ISSUE TITLE
Getting error while running producer to Kafka broker endpoint: ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by amit1barthwal** [edenhill/librdkafka#3094]
Description
===========
Getting below error when running producer application

%3|1601544943.909|FAIL|rdkafka#producer-1| [thrd:ssl://KAFKA_ENDPOINT:443/bootstrap]: ssl://KAFKA_ENDPOINT:443/bootstrap: SSL handshake failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (after 457ms in state CONNECT)
%3|1601553211.429|FAIL|rdkafka#producer-1| [thrd:ssl://KAFKA_ENDPOINT:443/bootstrap]: ssl://KAFKA_ENDPOINT:443/bootstrap: SSL handshake failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (after 493ms in state CONNECT, 31 identical error(s) suppressed)
%3|1601553241.478|FAIL|rdkafka#producer-1| [thrd:ssl://KAFKA_ENDPOINT:443/bootstrap]: ssl://KAFKA_ENDPOINT:443/bootstrap: SSL handshake failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (after 540ms in state CONNECT, 30 identical error(s) suppressed)

How to reproduce
================
**Installation**
apt install librdkafka-dev
./configure --install-deps
make
sudo make install

**Producer code is edited for SSL.**

char *p="XXXXXBroker endpointXXXX";
	
rd_kafka_conf_set(conf, "metadata.broker.list", p,
	NULL, 0);
rd_kafka_conf_set(conf, "security.protocol", "ssl",
	NULL, 0);
rd_kafka_conf_set(conf, "ssl.ca.location",
			"/home/CARoot.pem",
			NULL, 0);
rd_kafka_conf_set(conf, "ssl.certificate.location",
			"/home/certificate.pem",
			NULL, 0);
rd_kafka_conf_set(conf, "ssl.key.location",
			"/home/key.pem",
			NULL, 0);
rd_kafka_conf_set(conf, "ssl.key.password", "clientpass",
	NULL, 0);

if (rd_kafka_conf_set(conf, "bootstrap.servers", brokers, errstr,
			sizeof(errstr)) != RD_KAFKA_CONF_OK)
	{
		fprintf(stderr, "%s\n", errstr);
		return 1;
	}

Run the application

./producer KAFKA_ENDPOINT:443 videojet-telemetry

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v1.5.2
 - [x ] Apache Kafka version: 2.4.1
 - [x ] Operating system: Any

**Comment by edenhill** [comment]
This is typically caused by the client and broker not being able to negotiate the same TLS version or that you are connecting to a non-SSL listener on the broker.

**Comment by amit1barthwal** [comment]
Hi @edenhill, 
I have been using the example producer application to connect to the kafka broker endpoints using SSL certs. By using same certs i am able to connect to the kafka endpoint with apache kafka batch scripts. 
Could you please share if any way to resolve this issue ?

Using Rasbian OS
openssl version 1.1.0f

**Comment by edenhill** [comment]
If you run `openssl s_client ..` to connect to the broker, do you get the same error?

**Comment by edenhill** [comment]
You might need to select another ssl.cipher.suite (see `man ciphers`) to use TLS v1.2

**Comment by amit1barthwal** [comment]
I have tried to connect to kafka endpoint using openssl s_client. Below results achieved..

**Openssl s_client response**

I am getting attached response when using **-cipher TLSv1.2.**
command - openssl s_client -connect KAFKA_ENDPOINT:443 -cipher TLSv1.2

[openss with Cipher TLSv1.2.txt](https://github.com/edenhill/librdkafka/files/5314090/openss.with.Cipher.TLSv1.2.txt)


Without using -cipher i am getting same error.
1995609760:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:252:


I tried to configure the same cipher in producer application , but getting same error when running application as below.

**Code changes in producer.**
rd_kafka_conf_set(conf, "ssl.cipher.suite", "TLSv1.2",
		NULL, 0);

%3|1601576523.847|ERROR|rdkafka#producer-1| [thrd:app]: rdkafka#producer-1: ssl://kafka_broker:443/bootstrap: SSL handshake failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (after 454ms in state CONNECT)

**Comment by amit1barthwal** [comment]
Hey @edenhill ,

I think i got this. There was a mistake in  "ssl.cipher.suite" which is "ssl.cipher.suites".

**Code changes in producer.**
rd_kafka_conf_set(conf, "ssl.cipher.suites", "TLSv1.2",
NULL, 0);

This is working now. 

Thanks you so much for immediate help..!!

**Comment by amit1barthwal** [comment]
Hi @edenhill,

I am trying to connect the application from different system, facing the error below.

%3|1601881068.577|FAIL|rdkafka#producer-1| [thrd:ssl://kafkaENDpoint:443/bootstrap]: ssl://kafkaENDpoint:443/bootstrap: SSL handshake failed: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small (after 456ms in state CONNECT) 

System configuration

OS- Ubuntu 20.04
openssl - 1.1.1f

Same response i received when tried the openssl s_client command.

**Comment by edenhill** [comment]
That's an OpenSSL error code that is easily googlable:
https://www.google.com/search?q=tls_process_ske_dhe%3Adh+key+too+small

**Comment by amit1barthwal** [comment]
Thanks @edenhill .. Got this resolved.. Openssl issue in Ubunutu 20.04.
