### ISSUE TITLE
topic consumption performance

### ISSUE THREAD

**Issue by robambalu** [edenhill/librdkafka#3098]
This is a question not an issue.
I'm trying kafka for the first time and in my test app im subscribing to ~ 8,000 topics ( 1 topic per US stock ticker )
I'm seeing extremely poor performance if I only have 1, or a handful of consumers, because from what I can see the topic lookup call is linear:
rd_kafka_topic_find0_fl 

[https://urldefense.com/v3/__https:/github.com/edenhill/librdkafka/blob/master/src/rdkafka_topic.c*L167__;Iw!!K_TC0FI_KA!4S4SJP011NoWOvcQ4n4jZjMmUuYhMFVevGDwNer7Jy2cBuMr8wIeKthA_DpUTuBB7FM$](url)

why would topic lookups do a linear scan instead of rely on a hash table?
On the flip side, if I try to create many consumers ( say 100 ), then I need to run 100 threads to poll them, and now pthread_mutex_lock/unlock is the biggest cost.

Am I just doing something completely off-base here?

Help appreciated

Thanks
- Rob

**Comment by edenhill** [comment]
That is a lot of topics for one consumer, not very typical usage, thus the non-optimized lookups, but that could be surely be improved as needed.

I think it might be better to use the ticker as key and let it be partitioned on to a smaller set of partitions on a single topic instead.

Why did you close the issue though?

**Comment by robambalu** [comment]
sorry for some reason when I created the ticket something on github timed out, so I created a new one ( 3099 )
https://github.com/edenhill/librdkafka/issues/3099

I'll paste your message there and respond
