### ISSUE TITLE
performance issues when consuming many topics

### ISSUE THREAD

**Issue by robambalu** [edenhill/librdkafka#3099]
This is a question not an issue.
I'm trying kafka for the first time and in my test app im subscribing to ~ 8,000 topics ( 1 topic per US stock ticker )
I'm seeing extremely poor performance if I only have 1, or a handful of consumers, because from what I can see the topic lookup call is linear:
rd_kafka_topic_find0_fl 
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_topic.c#L167

why would topic lookups do a linear scan instead of rely on a hash table?
On the flip side, if I try to create many consumers ( say 100 ), then I need to run 100 threads to poll them, and now pthread_mutex_lock/unlock is the biggest cost.

Am I just doing something completely off-base here?

Help appreciated

Thanks
- Rob

**Comment by robambalu** [comment]
Pasting edenhill's comment from 3098:

> That is a lot of topics for one consumer, not very typical usage, thus the non-optimized lookups, but that could be surely be improved as needed.
> I think it might be better to use the ticker as key and let it be partitioned on to a smaller set of partitions on a single topic instead.

I wouldn't say its atypical usage in a financial setting.  You will typically find one or many ticker plants that publish market data by ticker, and then N consumers consuming some subset ( or all ) tickers.  The reason its split out this way is to avoid subscribing to all tickers in client applications if only 1 or a handful of tickers are actually needed.  

I am completely new to kafka and just trying it out, can you elaborate a bit on key /partition based setup, or point me at a wiki?
The main goal here is to be able to subscribe to a subset of the tickers without consuming all the ticker data in the client application.

All this aside, my original comment still stands, why not store topics in a hashmap?

**Comment by edenhill** [comment]
Topic per entity (user, object, ticker, etc) is not recommended, it is more suitable with topic per data type, and then use a higher number of partitions to share the load of consumers over that topic.
