### ISSUE TITLE
Question - Get a list of all topics created in kafka cluster

### ISSUE THREAD

**Issue by prabcs** [edenhill/librdkafka#310]
Hi,

Using this library, it is possible to enlist all the topics created in kafka ?

Thanks,
prabcs

**Comment by edenhill** [comment]
Use `rd_kafka_metadata()` without a topic argument (NULL).

**Comment by DEvil0000** [comment]
is there a c++ way to do this?

**Comment by edenhill** [comment]
Almost, there is a pull request for it here: https://github.com/edenhill/librdkafka/pull/221
But it is not fully done yet.
