### ISSUE TITLE
Question: how to determine supported Apache Kafka protocol versions by librdkafka release?

### ISSUE THREAD

**Issue by kfdx87** [edenhill/librdkafka#3103]
Hi dear all! Please take a look at my question regarding Apache Kafka protocol versions, supported by various versions of librdkafka. I read FAQ, wiki, etc., but didn't find a clear answer.

Does **librdkafka v1.0.0-RC7** support [Apache Kafka protocol from release 1.1.1](https://archive.apache.org/dist/kafka/1.1.1/RELEASE_NOTES.html)?
Or does it support only [Apache Kafka protocol from release 1.0.0](https://archive.apache.org/dist/kafka/1.0.0/RELEASE_NOTES.html)?
How do I determine supported protocol versions by the library release?

My practical problem:

- broker **1.0.0**
- various producers: **v1.0.0-RC7-librdkafka-based**, **v1.2.2-librdkafka-based** and one non-librdkafka based (supports protocol versions up to **2.4.0**)
- various consumers: **v1.0.0-RC7-librdkafka-based**, and two non-librdkafka based (one supports protocol versions up to **2.4.0** and another supports protocol versions up to **2.5.0**)

I'm thinking about broker upgrade from **1.0.0** to **1.1.1**. But I heard that if broker and some producer will use newer protocol version and some consumer will use older protocol version, then broker may experience significant performance issue. For example, producer posts messages in new format, broker keeps them in the data log and then has to convert/downgrade each message for "old" consumer. So I'm trying to understand which exact protocol versions (in terms of Apache Kafka releases) are supported by **v1.0.0-RC7** and **v1.2.2** to make a decision about upgrade.

Please provide the following information:

 - [x] librdkafka version v1.0.0-RC7 and v1.2.2
 - [x] Apache Kafka version: 1.0.0
 - [ ] librdkafka client configuration:
 - [x] Operating system: CentOS 7.7
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka supports a mix of protocol versions, depending on what is needed in librdkafka itself.
The supported per-protocol versions are specified in the manual:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#supported-protocol-versions

**Comment by edenhill** [comment]
librdkafka supports all broker versions >= 0.8.
