### ISSUE TITLE
librdkafka producer consuming cpu even after on messages are not being produced

### ISSUE THREAD

**Issue by adinigam** [edenhill/librdkafka#3104]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
as per our recent findings we saw librdkafka producer consuming cpu even after on messages are not being produced.
Below are the flow of events
1) application initiated producer with only broker list on plaintext channel. but connection was never made because of broker unreachable. all request kept timeing out. Rate of messages produce was around 450 messages per minute. and message size is 250 bytes. Here CPU consumption by librdkafka was petty high upto 60% cpu as shown in windows taskmgr

2) we stopped production of messages in application without restarting the application. even now we see around 30% cpu consumption.

Is this expected or can there me a reason why it happened ?
Thing to note is this is not a happy day scenario and brokers were never reachable.
unfortunately we do not have debug logs at the moment.

How to reproduce
================
1) Start an application with all default config values with invalid broker, i.e. linger.ms=.5.
2) Produce at 450 messages per minute. we should all produce requests timming out on plaintext. we should also see some cpu consumption. (we saw 60% in our case)
3) stop produce of messages without restarting the application. we should still see significant cpu usage. (in our case it was 30%)

after we saw this we changed linger.ms to 200ms. we did not see high cpu neither with valid broker list OR invalid broker list.
Is this expected ?

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [x] Apache Kafka version: `2.4`
 - [ ] librdkafka client configuration: `metadata.broker.list`
 - [x] Operating system: `windows`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
What librdkafka version is this? Is it reproducible on the latest release?

**Comment by adinigam** [comment]
@edenhill This is on librdkafka 1.4.2.
We have not tried on 1.5 yet.
