### ISSUE TITLE
Unknown event type in the event channel/delivery report loop

### ISSUE THREAD

**Issue by mavogel** [edenhill/librdkafka#3105]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
We observe a lot of `Unknown event types` and even `Nil event types` as seen below in the code and we were wondering
1. if we can cast to other types than `*kafkalib.Message`? 
2. if there is another possibility to get failure messages from kafka other than we determine via the `isKafkaFailureEventType` method as shown below in the code?

How to reproduce
================
This is the way we currently do the deliver report loop:

```go
func (k *KafkaProducer) startDeliveryReport() {
	eventsC := k.producer.Events()

	for {
		select {
		case <-k.quit:
			return
		case e := <-eventsC:
			switch ev := e.(type) {
			case *kafkalib.Message:
				if ev.TopicPartition.Error != nil {
					k.logger.Error("Delivery failed", zap.String("topic", ev.TopicPartition.String()))
					k.errorC <- ev.TopicPartition.Error
					continue
				}

				k.logger.Debug("Delivered message to",
					zap.String("topic", ev.TopicPartition.String()),
					zap.ByteString("message", ev.Value),
				)
			default:
				if k.isKafkaFailureEventType(e) {
					k.logger.Warn("kafka failure event type", zap.String("type", e.String()))
					k.errorC <- fmt.Errorf("kafka failure event type: %v", e)
					return
				}

				if e == nil {
					k.logger.Info("Nil event type")
				} else {
					k.logger.Warn("Unknown event type", zap.String("type", e.String()))
				}
			}
		}
	}
}

// isKafkaFailureEventType determines if an event indicates
// a failure of kafkalib. Currently we ignore 'Connection refused'
// because it occurs in the test setup.
func (k KafkaProducer) isKafkaFailureEventType(e kafkalib.Event) bool {
	if e == nil {
		return false
	}

	return strings.Contains(strings.ToLower(e.String()), "failed") &&
		!strings.Contains(e.String(), "Connection refused")
}
```

### Regarding the `Unknown event type`:
We see this message in the log as follows. This occurs ~1s after we connect to Kafka although the config for `"socket.timeout.ms":       120000` as shown below in the config section:
```console
{"level":"warn","timestamp":"xx","caller":"kafka_producer.go:111","msg":"Unknown event type","type":"kafka:9092/bootstrap: Disconnected (after 59912ms in state UP)"}
```
What does `Disconnected (after xxx ms in state UP)` mean exactly? We also see that messages are produced successfully to kafka.

### Regarding the `Nil event type`:
We see this message when we shut down, aka we first `flush` the messages to kafka and then close the producer.

```go
func (k KafkaProducer) Shutdown(ctx context.Context) {
	k.flush(ctx)

	if k.producer != nil {
		k.producer.Close()
	}

	close(k.quit)
	k.wg.Wait()
}

/// more code
func (k KafkaProducer) flush(ctx context.Context) {
    go func() {
		for {
			numOfUndeliveredMsgs := k.producer.Flush(15000) // 15s
			if numOfUndeliveredMsgs == 0 {
				// we quit the flushing if all message were delivered
				close(quitFlushingC)
				return
			}
    }
}
/// more code
```

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version: `1.4.2`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration:
```
"bootstrap.servers":       kafka:9092,
"socket.timeout.ms":       120000,
"acks":                    -1, // = all
"retries":                 10000000,
"retry.backoff.ms":        100,
"delivery.timeout.ms":     2147483647,
"compression.type":        "lz4",
"go.produce.channel.size": 100,
"go.events.channel.size":  100,
```
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You're probably seeing kafka.Error events, which are *informational* errors (can be considered logs).

The disconnects are typically due to idle connections, see https://github.com/edenhill/librdkafka/wiki/FAQ#why-am-i-seeing-receive-failed-disconnected

**Comment by mavogel** [comment]
Alright, so a `case *kafkalib.Error:` would make sense and only if the `ev.IsFatal()` is true then it's a real error, right? AFAIK as I understand the code and the link you posted.

**Comment by edenhill** [comment]
Spot on!

**Comment by mavogel** [comment]
Thanks, so an updated [example](https://github.com/confluentinc/confluent-kafka-go/blob/master/examples/producer_channel_example/producer_channel_example.go#L62) would be great :) Because all events other than `*kafka.Message` are ignored. Also the _real_ errors. I'll file a PR

**Comment by edenhill** [comment]
Awesome, thank you!

**Comment by mavogel** [comment]
You're welcome: https://github.com/confluentinc/confluent-kafka-go/pull/569
