### ISSUE TITLE
Memory Leak while kafka producer security.protocol = SASL_SSL

### ISSUE THREAD

**Issue by DinoStray** [edenhill/librdkafka#3106]
Description
===========
My rdkafka config:
```
options["security.protocol"] = "SASL_SSL";
options["sasl.mechanism"] = "PLAIN";
options["sasl.username"] = "xxx";
options["sasl.password"] = "xxx"
```
There is no memory leak while running, but if I stop the server, there always 16 blocks definitely lost in loss record.

eg.
```
==16787== 12 bytes in 1 blocks are definitely lost in loss record 1 of 16
==16787==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==16787==    by 0x57D48CD: CRYPTO_zalloc (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==16787==    by 0x57D0A05: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==16787==    by 0x57B093F: ERR_get_state (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==16787==    by 0x57B0A9C: ERR_clear_error (in /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)
==16787==    by 0x5116F7B: rd_kafka_transport_ssl_clear_error (rdkafka_ssl.c:83)
==16787==    by 0x5116F7B: rd_kafka_transport_ssl_connect (rdkafka_ssl.c:507)
==16787==    by 0x50D2D01: rd_kafka_transport_connected (rdkafka_transport.c:617)
==16787==    by 0x50D2D01: rd_kafka_transport_io_event (rdkafka_transport.c:704)
==16787==    by 0x50D380B: rd_kafka_transport_io_serve (rdkafka_transport.c:801)
==16787==    by 0x5061719: rd_kafka_broker_ops_io_serve (rdkafka_broker.c:3338)
==16787==    by 0x50630A6: rd_kafka_broker_producer_serve (rdkafka_broker.c:3930)
==16787==    by 0x50630A6: rd_kafka_broker_serve (rdkafka_broker.c:4981)
==16787==    by 0x50639D4: rd_kafka_broker_thread_main (rdkafka_broker.c:5035)
==16787==    by 0x519C6D9: start_thread (pthread_create.c:474)
```
full log: [valigrind.txt](https://github.com/edenhill/librdkafka/files/5369932/valigrind.txt)

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.5.0`
 - [ ] Apache Kafka version: `2.6.0`
 - [ ] librdkafka client configuration: `security.protocol=SASL_SSL,sasl.mechanism=PLAIN`
 - [ ] Operating system: `Ubuntu 20.04`

**Comment by edenhill** [comment]
This is most likely a one-time internal malloc in libcrypto/OpenSSL which can be ignored.

**Comment by edenhill** [comment]
There is a tests/librdkafka.suppressions file you can use to suppress some known valgrind warnings.

**Comment by DinoStray** [comment]
> There is a tests/librdkafka.suppressions file you can use to suppress some known valgrind warnings.

I use the file by  --suppressions=/work/librdkafka.suppressions, but the memory leak report still there

**Comment by edenhill** [comment]
The callstacks are different between OpenSSL versions, you might need to generate a new suppression for that one.

**Comment by DinoStray** [comment]
maybe we can call some function for quit gracefully
