### ISSUE TITLE
Network_Exception is taken as permanent failure whereas according to Apache Kafka doc it is retiable.

### ISSUE THREAD

**Issue by serkantkaraca** [edenhill/librdkafka#3108]
Description
===========
Network_Exception is a retriable error according to Apache Kafka documentation. https://kafka.apache.org/protocol

![image](https://user-images.githubusercontent.com/16924470/96019860-ff8b2f80-0e01-11eb-9682-a561e0dd4110.png)

Current implementation doesn't retry on Network_Exception even when the message is still in its retry and timeout limits.

How to reproduce
================
This requires server to send Network_Exception error code so no controllable repro possible.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.5.0
 - [x] Apache Kafka version: kafka_2.13-2.5.0
 - [x] librdkafka client configuration: 
log.connection.close : false
queue.buffering.max.kbytes : 256000
queue.buffering.max.messages : 1000000
request.required.acks : 1
message.max.bytes : 1000000
linger.ms : 10000
socket.timeout.ms : 60000
batch.num.messages : 10000
retries : 10000
message.timeout.ms : 3000000
retry.backoff.ms : 3000
request.timeout.ms : 90000
max.in.flight.requests.per.connection : 50
metadata.request.timeout.ms : 3000000
 - [x] Operating system: Windows 10 Enterprise - Build 19042.572
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There is no Network_Exception in librdkafka, where are you seeing this?
