### ISSUE TITLE
LZ4 compression

### ISSUE THREAD

**Issue by prabcs** [edenhill/librdkafka#311]
Hi,

I'm producing LZ4 compressed data (as string) to kafka and consuming it on the other side and decompressing it.

I'm seeing some garbage data  on the consumer side. I'm wondering if this is a known issue.
Any pointers in some direction will help

Thanks

**Comment by edenhill** [comment]
Are you doing the compression yourself before producing the payload or is the producer doing it for you internally? 
What producer and consumer are you using?

**Comment by prabcs** [comment]
Yes, I'm doing the compression and decompression myself.
Compressed data is a std::string .
I'm using the C++ producer and C consumer using rkqu (i.e. multiple partitions of the same topic)

**Comment by prabcs** [comment]
or a general question - If I'm writing binary data (i.e. a std::string data) to kafka, why is it that I'm getting some more garbage data after the actual data ?

**Comment by edenhill** [comment]
Could you write a small program that reproduces this issue?

**Comment by prabcs** [comment]
I could write that as well. 
But, on consume side, I am consuming like this:-

string received_msg ((char*)rkmessage->payload, int(rkmessage->len));

Is this the correct way of doing it ?

**Comment by prabcs** [comment]
Also, the rkmessage is got from 
rkmessage = rd_kafka_consume_queue(rkqu, 1000);

**Comment by edenhill** [comment]
Yes, just make sure to check rkmessage->err first.

**Comment by prabcs** [comment]
Doing this in a loop:-

rkmessage = rd_kafka_consume_queue(rkqu, 1000);
                if ((!rkmessage) || ((int)rkmessage->len == 0)){/* timeout */
                        continue;}
                std::cerr<<"message received : " << (int)rkmessage->len << std::endl;
                if (rkmessage->err) {
                        if (rkmessage->err == RD_KAFKA_RESP_ERR__PARTITION_EOF) {
            

                        continue;
                        }   
                }   

string received_msg ((char*)rkmessage->payload, int(rkmessage->len));

**Comment by edenhill** [comment]
I think you want to check err before len, but it probably doesn't matter with your issue.  
It'd be great if you could provide some sample code to reproduce the data corruption issue. 

What does your produce code look like? Are you sure the provided produce payload doesn't go out of scope? E.g use F_COPY or F_FREE

**Comment by edenhill** [comment]
Is this still an issue? If so reopen

**Comment by agboom** [comment]
```

**Comment by agboom** [comment]
I'm having a similar problem with kafkacat:
```
 Fatal error at consume_cb:406:
% ERROR: Topic *** [0] error: Unsupported compression codec 0x3
```
