### ISSUE TITLE
Producer failing to get partition information

### ISSUE THREAD

**Issue by sreeni89** [edenhill/librdkafka#3110]
librdkafka version used : librdkafka-0.11.5-1.el7.x86_64

Description
===========
For my application requirement I am trying to write custom partition selection logic for the producer which looks something like this
1. Retrieve all the partitions configured under a given/selected topic.
2. Calculate offsets of each partition and find the partition which is free or which can accommodate the data which producer can produce (let say my producer produce 1GB data).
(Here trying to address the case where to avoid override of partition data when consumers are down and can't read data from the cluster for a certain period)
  
For the second point I tried below ways to get the partition offsets but not succeeded. 
Case 1:

int64_t *low = 0, *high = 0;
int32_t partition = 1
RdKafka::ErrorCode resp = producer->query_watermark_offsets(topicName, partition, low, high, 1);
if (resp != RdKafka::ERR_NO_ERROR)
{
  auto err = RdKafka::err2str(resp);
  std::cout << err << std::endl;
}

==> This always failing with error : "Broker: Leader not available"
Note: Consumer's were assigned and reading data properly.

Case 2:
In the event_stats which coming from producer event_cb, only message produced information is coming no offset fields are updated.

"0": {"partition": 0,"leader": 0,"desired": false,"unknown": false,"msgq_cnt": 0,"msgq_bytes": 0,"xmit_msgq_cnt": 0,"xmit_msgq_bytes": 0,"fetchq_cnt": 0,"fetchq_size": 0,fetch_state": "none","query_offset": -1001,"next_offset": 0,"app_offset": -1001,"stored_offset": -1001,"commited_offset": -1001,"committed_offset": -1001,"eof_offset": -1001,"lo_offset": -1001,"hi_offset": -1001,"consumer_lag": -1,"txmsgs": 2,"txbytes": 1000,"rxmsgs": 0,"rxbytes": 0,"msgs": 2,rx_ver_drops": 0}

Your inputs to get the partition details from the producer is well appreciated.

**Comment by edenhill** [comment]
v0.11.5 is two years old. Reproduce on latest version (v1.5.0)
