### ISSUE TITLE
Undefined reference 'va_start ...' on librdkafka/src/rdkafka_cgrp.c  (gcc 4.8.2) miss stdarg.h?

### ISSUE THREAD

**Issue by amichelotti** [edenhill/librdkafka#3115]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Linking of librdka.a (static) fails (gcc 4.8.2) : undefined reference va_start ... on librdkafka/src/rdkafka_cgrp.c .
Looking at the source it misses #include <stdarg.h>.
The problem arosed  after : https://github.com/edenhill/librdkafka/commit/74749d475d0a156c3df274b104d9ec47a56dacc8#diff-f4be68d9a41906eb18b50bc6e4b96aa7fb94eb8e01c480718b2181bd913328ab

No problem with higher releases of gcc. 
No idea why the commit of yesterday broke my pipeline. However I would include stdarg.h into the sources that use va_start .. 

How to reproduce
================
Compile static and link with gcc 4.8.2 (commit 74749d475d0a156c3df274b104d9ec47a56dacc8). 

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by amichelotti** [comment]
A dump of my pipeline:
/usr/local/chaos/chaos-distrib/lib/librdkafka.a(rdkafka_cgrp.c.o): In function `rd_kafka_cgrp_assignment_clear_lost':
rdkafka_cgrp.c:(.text+0x1fd): undefined reference to `va_start'
rdkafka_cgrp.c:(.text+0x224): undefined reference to `va_end'
/usr/local/chaos/chaos-distrib/lib/librdkafka.a(rdkafka_cgrp.c.o): In function `rd_kafka_cgrp_assign':
rdkafka_cgrp.c:(.text+0x54c0): undefined reference to `va_start'
rdkafka_cgrp.c:(.text+0x54e4): undefined reference to `va_end'
/usr/local/chaos/chaos-distrib/lib/librdkafka.a(rdkafka_cgrp.c.o): In function `rd_kafka_cgrp_unassign':
rdkafka_cgrp.c:(.text+0x5630): undefined reference to `va_start'
rdkafka_cgrp.c:(.text+0x5654): undefined reference to `va_end'
/usr/local/chaos/chaos-distrib/lib/librdkafka.a(rdkafka_cgrp.c.o): In function `rd_kafka_cgrp_rejoin':
rdkafka_cgrp.c:(.text+0x573d): undefined reference to `va_start'
rdkafka_cgrp.c:(.text+0x5764): undefined reference to `va_end'
/usr/local/chaos/chaos-distrib/lib/librdkafka.a(rdkafka_cgrp.c.o): In function `rd_kafka_cgrp_incremental_assign.part.23':
rdkafka_cgrp.c:(.text+0x62d0): undefined reference to `va_start'
rdkafka_cgrp.c:(.text+0x62f4): undefined reference to `va_end'
/usr/local/chaos/chaos-distrib/lib/librdkafka.a(rdkafka_cgrp.c.o): In function `rd_kafka_cgrp_incremental_unassign.part.24':
rdkafka_cgrp.c:(.text+0x6450): undefined reference to `va_start'
rdkafka_cgrp.c:(.text+0x6474): undefined reference to `va_end'
/usr/local/chaos/chaos-distrib/lib/librdkafka.a(rdkafka_cgrp.c.o): In function `rd_kafka_cgrp_revoke_all_rejoin':
rdkafka_cgrp.c:(.text+0x7e0c): undefined reference to `va_start'
rdkafka_cgrp.c:(.text+0x7e38): undefined reference to `va_end'
rdkafka_cgrp.c:(.text+0x7ede): undefined reference to `va_start'
rdkafka_cgrp.c:(.text+0x7f0a): undefined reference to `va_end'
/usr/local/chaos/chaos-distrib/lib/librdkafka.a(rdkafka_cgrp.c.o): In function `rd_kafka_cgrp_metadata_update_check':
rdkafka_cgrp.c:(.text+0xeb4c): undefined reference to `va_start'
rdkafka_cgrp.c:(.text+0xeb70): undefined reference to `va_end'

**Comment by edenhill** [comment]
Fixed on master, thank you!
