### ISSUE TITLE
cmake: inttypes.h doesn't exist

### ISSUE THREAD

**Issue by jalegido** [edenhill/librdkafka#3117]
Description
===========
I would like **cmake** detects if inttypes.h exists or not. 
I'm compiling with **Visual Studio 2010** and CMAKE and this compiler hasn't inttypes.h file.

How to reproduce
================
`cmake .. -G "Visual Studio 10 2010 Win64"`
doesn't show the problem until we start the compilation

Checklist
=========
I would like add this code in **CMakeLists.txt**

```
include(CheckIncludeFile)
CHECK_INCLUDE_FILE("inttypes.h" HAVE_INTTYPES_H)
if(NOT HAVE_INTTYPES_H)
	message( FATAL_ERROR "inttypes.h Not Found" )
endif()

```
to check if file exists or not.

**Comment by edenhill** [comment]
You will need to get stdint.h from elsewhere, this is a common problem with outdated VS releases, see Google for solutions.
