### ISSUE TITLE
Reading header before message

### ISSUE THREAD

**Issue by lugospod** [edenhill/librdkafka#3120]
Hi,

Is there a way for a consumer to read kafka message headers without retrieving the message/payload?

Idea is to avoid transmitting the payload all the way to my Consumer in case I plan to discard that message (information in headers provide me with info to decide if the message is of interest to my app.). Currently the payload is not a small message, it goes up to a MB. So if we have a lot of messages, there is a lot of network traffic going on...

Tnx!

**Comment by edenhill** [comment]
That's not possible with Kafka.
