### ISSUE TITLE
Is librdkafka IPv6 capable?

### ISSUE THREAD

**Issue by yhsiung** [edenhill/librdkafka#3121]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Should I do anything special in the Kafka producer application to configure IPv6 other than the broker's bootstrapping IPv6 address?

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v. 0.11.6`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Yes

**Comment by yhsiung** [comment]
How do I enable it other than configure broker with IPv6 address?

**Comment by edenhill** [comment]
It is enabled by default. Just pass an IPv6 address or a hostname that resolves to IPv6 to `bootstrap.servers`.
