### ISSUE TITLE
Statically link zstd in nuget package

### ISSUE THREAD

**Issue by braca** [edenhill/librdkafka#3122]
This issue was originally opened on confluent-kafka-dotnet (https://github.com/confluentinc/confluent-kafka-dotnet/issues/1416) but I was told to open it here, asking to statically link zstd in nuget package.

Description
===========
It seems that there is a conflict between `Confluent.Kafka` and `MongoDB.Driver`.

If I publish my app as self-contained for windows (`dotnet publish -r win-x86`), the app crashes at startup because `Confluent.Kafka` won't be able to load `librdkafka`, this only happens if I have `MongoDB.Driver` package installed as well.

I've been looking into this, and I believe that the culprit is the `libzstd.dll` that both projects use, but I'm not sure how I can fix this.

**Details:**
- Confluent.Kafka version: 1.5.1
- MongoDB.Driver version: 2.11.2
- .netcore 2.1/3.1
- Apache Kafka version: Not relevant (it crashes before establishing any connection to kafka)
- Operating System: Windows 10 / Windows Server 2016

**Exception:**
```
System.DllNotFoundException: Failed to load the librdkafka native library.
   at Confluent.Kafka.Impl.Librdkafka.Initialize(String userSpecifiedPath)
   at Confluent.Kafka.Consumer`2..ctor(ConsumerBuilder`2 builder)
   at Confluent.Kafka.ConsumerBuilder`2.Build()
   at kafka_mongo_issue.Startup.StartKafkaConsumer() in D:\Dev\kafka-mongo-issue\Startup.cs:line 61
```

How to reproduce
================
```
git clone https://github.com/braca/kafka-mongo-issue
cd kafka-mongo-issue
dotnet publish -r win-x86 -c Release -o output
cd output
kafka-mongo-issue.exe
```
Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: ``
 - [ ] librdkafka client configuration: ``
 - [x] Operating system: `Windows 10 / Windows Server 2016`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by naughtyGitCat** [comment]
does this fixed?

**Comment by naughtyGitCat** [comment]
my applicaiton failed with this problem in a production environment

**Comment by edenhill** [comment]
Have you tried the 1.8.2 release which uses vcpkg instead of nuget for dependencies? Might have fixed the issue
