### ISSUE TITLE
invalid use of memcpy in regexp.c

### ISSUE THREAD

**Issue by briot** [edenhill/librdkafka#3128]
We just upgraded from 1.3.2 to 1.5.2, reusing some configuration files (we should have regenerated them...). As a result, it did not have HAVE_REGEXP set to true, and thus was trying to compile regexp.c.

We end up with a legitimate warning from gcc:

```
src/regexp.c: In function 're_regcomp':
src/regexp.c:851:9: warning: 'memcpy' accessing 4 bytes at offsets 1 and 0 overlaps 3 bytes at offset 1 [-Wrestrict]
         memcpy(((char *)prog)+1, prog, 4);
```

Sources haven't changed in master, the incorrect source is still there. Likely not important for most people, since the systems generally do provide a regexp library. But still worth fixing.

Thanks
Emmanuel

**Comment by edenhill** [comment]
That's a very weird memcpy, not really sure what the idea was and I don't see what good it would do. Will remove it.

Thanks for reporting this!
