### ISSUE TITLE
Unexpected warning on missing bootstrap.servers

### ISSUE THREAD

**Issue by briot** [edenhill/librdkafka#3132]
We are moving from 1.3.2 to 1.5.2, and are now seeing the following warning in the log files:
```
log 5 CONFWARN : [thrd:app]: No `bootstrap.servers` configured: client will not be able to connect to Kafka cluster
```

This was apparently added in commit 43a5a3e2979fdc47af4191123a9666fdcfee4096

Our code is basically doing what the examples do (we are programming in Ada, so here I will simply copy-paste from the example rdkafka_example.c:
```
		/* Create Kafka handle */
		if (!(rk = rd_kafka_new(RD_KAFKA_CONSUMER, conf,
					errstr, sizeof(errstr)))) {
			fprintf(stderr,
				"%% Failed to create new consumer: %s\n",
				errstr);
			exit(1);
		}

		/* Add brokers */
		if (rd_kafka_brokers_add(rk, brokers) == 0) {
			fprintf(stderr, "%% No valid brokers specified\n");
			exit(1);
		}
```

In our code, the conf has no bootstrap.servers set yet, so the call to `rd_kafka_new()` results in the above warning. But we add servers immediately afterwards with `rd_kafka_brokers_add`.

May I suggest one of the following changes:
   - either the warning occurs too early (not giving a chance for call to rd_kafka_brokers_add`
   - or update the example (and documentation for bootstrap.servers) to show that users really should be modifying the configuration before calling `rd_kafka_new`

Thanks !

Emmanuel

**Comment by edenhill** [comment]
brokers_add() is a legacy API and should not be used unless needed.
I'll update the examples.

Thanks
