### ISSUE TITLE
[Question] Please confirm/clarify producer queue understanding

### ISSUE THREAD

**Issue by Kamil-Zakiev** [edenhill/librdkafka#3134]
Hi!

I've been investigating Kafka API and the concept of producer queue is revealing from time to time but it still not clear for me.

As far as I understand, producer queue is a **local** queue in a process which produces messages. 

On the other hand, "queue.buffering.max.messages" configuration mentions that "This queue is **shared** by all topics and partitions." and it really confuses me. It sounds like the queue resides on a broker.

Am I understanding correctly that a producer has a single queue for all messages to be sent to a broker but still this queue is **on a producer side** and not on a broker?

**Comment by edenhill** [comment]
There'll be a blog post about the producer queues in a bit, stay tuned.

But yes, the queues refer to local queues in the producer, not on the broker.

**Comment by scanterog** [comment]
Where can I find this blog post (if it ever was published)?
