### ISSUE TITLE
High CPU usage when the local socket used to wake the broker thread for produce is disconnected

### ISSUE THREAD

**Issue by ajbarb** [edenhill/librdkafka#3139]
Description
===========
I was investigating a High CPU usage on the client running on windows. I found out that WSAPoll was returning immediately and the broker threads were continuously spinning. On looking at a heap dump I found out that the second socket on the fd list of rktrans_pfd has revents set to 3.

0:098> dx rktrans->rktrans_pfd[1]
rktrans->rktrans_pfd[1]                 [Type: pollfd]
    [+0x000] fd               : 0xbe0 [Type: unsigned __int64]
    [+0x008] events           : 768 [Type: short]
    [+0x00a] revents          : 3 [Type: short]

For some reason it seems like the local socket used for event based thread wake went bad. This causes WSAPoll to return immediately and the broker thread spins.

How to reproduce
================
1. Run the librdkafka_example project
2. Observe that CPU usage is low.
3. Use currports to kill the local tcp sockets.
4. CPU usage jumps.
![image](https://user-images.githubusercontent.com/1256612/98723487-4dcf1800-2347-11eb-8f24-ff2f46c4448a.png)

5. Before killing the connection, WSAPoll seems to be working fine but after killing the connection, WSAPoll return immediately.

Checklist
=========

Please provide the following information:

 - [x] librdkafka version: v1.4.4 (Tried it with the latest version too and hit the same issue)
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `queue.buffering.backpressure.threshold=1000000, queue.buffering.max.ms=1000, linger.ms=1000
 - [x] Operating system: Windows 10.0.19042.572
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
revents 0x3 is POLLIN|RDNORM on Windows, which would be raised if the socket was closed, but we're assuming the internal queue sockets are not closed.

Does this happen spontaneously or only when you forcefully kill these connections?

**Comment by ajbarb** [comment]
This happens spontaneously in our deployments. I was able to capture a dump of this in action and then tried to reproduce this locally. I was able to get the same effect after forcefully killing the internal queue socket in my local repro.

**Comment by edenhill** [comment]
Guess my Intellisense lied to me.  HUP|ERR does make more sense in this case.


Do you have any idea why the localhost TCP connections are killed? Is there some firewall software in play?

**Comment by ajbarb** [comment]
Haven't been able to figure out yet why the localhost TCP connection got disconnected. I will keep digging.

**Comment by edenhill** [comment]
The internal loopback connections are gone now.
