### ISSUE TITLE
For the new high-level KafkaConsumer, how to read always latest messages

### ISSUE THREAD

**Issue by madanmch** [edenhill/librdkafka#3141]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
My Kafka Producer produces always more messages, but for my consumer I need only latest messages. Tried to found example code, but couldn't found it.

How to reproduce
================
A simple producer and consumer scenario, where producer always produces more messages where consumer need latest messages only.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by madanmch** [comment]
I was going through other closed  [here](https://github.com/edenhill/librdkafka/issues/2783), and found below code
` std::vector<RdKafka::TopicPartition*> partitions;
  partitions.push_back(RdKafka::TopicPartition::create(topic_name, 0, -1));
  partitions.push_back(RdKafka::TopicPartition::create(topic_name, 1, 0));
  partitions.push_back(RdKafka::TopicPartition::create(topic_name, 2, 0));

  err = consumer->assign(partitions);
  if (err) {
      std::cerr << "Failed to assign to " << partitions.size() << " topics: "
                << RdKafka::err2str(err) << std::endl;
      exit(1);
  }`

I tried by using above code, but I couldn't able to access latest message every time. And I have 35 partitions in Kafka broker. I am not sure which partition uses my subscribed topic. Is there any way to access the latest message every time I get message from Kafka?

**Comment by madanmch** [comment]
@edenhill can you answer my issue?

**Comment by edenhill** [comment]
Set enable.auto.commit=false and auto.offset.reset=latest

**Comment by madanmch** [comment]
Thank you @edenhill, this configuration is working for me
