### ISSUE TITLE
enable.partition.eof parameter meaning

### ISSUE THREAD

**Issue by nleeuskadi** [edenhill/librdkafka#3145]
Description
===========
I am trying to understand how this parameter works behind the scene to validate its usage for our use-case.
Could you give me deeper details about the way this parameter is used by librdkafka, and what first use-cases is it intended for ?

For example, what is happening if the consumer is reaching the end of partition while new messages are coming in but are not commited yet neither replicated with the required replication factor and/or min in-sync ?

Perhaps I am wrong but I guess that when there is no more message to be read in the partition, the call to `consumer->consume(topic, partition, 1000);` may return no message? if it is true I can't see the added value of the enable.partiton.eof parameter?

Thank you in advance for you help.
 
Checklist
=========
 - [x] librdkafka version (release number or git tag): `v1.5.2`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
If enable.partition.eof is true, each time the consumer fetcher reaches the end of the partition and there are no new messages it will emit an ERR__PARTITION_EOF on the consumer queue.
This allows use-cases like 'read until there are no more messages and then exit', such as kafkacat's `-e` option.

You can't really use the consume timeout for this purpose since the consume could be stalled for other reasons: rebalance, broker unavailable, etc.

**Comment by nleeuskadi** [comment]
Hi, thank you for your explanation.
If i understood well, it will emit an ERR__PARTITION_EO each time the consumer fetcher reaches the end of the partition (i.e. it reaches the high watermark offset) regardless there is unreplicated messages after this offset that may be available to be read later?

**Comment by edenhill** [comment]
Yes, and depending on the client's isolation.level (i.e., committed or uncommitted transactions).

**Comment by nleeuskadi** [comment]
thanks a lot for your clarifications, every thing is clear now on my side.
