### ISSUE TITLE
using python to connect to kafka with kerberos - Ticket expired

### ISSUE THREAD

**Issue by sstevens303** [edenhill/librdkafka#3149]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I have the python code to connect to kafka, it initially does the kinit successfully. Then after this appears in the log:
Broker changed state AUTH_HANDSHAKE -> AUTH_REQ
I get this error:
GSSAPI Error:  Miscellaneous failure (see text (Ticket expired)
Although my colleague can run the exact same code and it is working fine.

How to reproduce
================
each run it fails

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):
confluent-kafka-1.5.0 , librdkafka 1.5.2
 - [x] Apache Kafka broker version:
Confluent 5.5.1
 - [x] Client configuration: `{...}`
conf = {
    'bootstrap.servers': ‘xxx-kafkaxx:1234',
     'group.id': 'gcp-xxxx.test',
    'default.topic.config': {'auto.offset.reset': 'earliest'},
    'enable.auto.offset.store': False,
    'security.protocol': 'SASL_SSL',
      'sasl.mechanisms': 'GSSAPI',
    'sasl.kerberos.principal': 'svc_xxx_test@xxx.xxx.xxx’,
    'sasl.kerberos.keytab': ‘/xxx/xxx/svc_xxx_test.keytab',
    'sasl.kerberos.kinit.cmd': 'kinit -k -t "%{sasl.kerberos.keytab}" %{sasl.kerberos.principal}',
    'ssl.ca.location': '/Users/xxx/xxxs/cert.pem'
}

 - [x] Operating system:  Mac OS

 - [x] Provide client logs (with `'debug': '..'` as necessary)
[debugall.log](https://github.com/edenhill/librdkafka/files/5550203/debugall.log)

 - [ ] Provide broker log excerpts
 - [ ] Critical issue
development

**Comment by edenhill** [comment]
librdkafka simply calls into libsasl2/cyrus-sasl to handle Kerberos, suggest you start looking there.
