### ISSUE TITLE
Offset managment - Can I use store offset commit on broker?

### ISSUE THREAD

**Issue by MaksVal** [edenhill/librdkafka#315]
Hi!

Thanks, for your library!
I want to use commit store on broker. But I get a misstake: 
 `` %7|1435060983.739|OFFSET|rdkafka#consumer-0| dev-scheduler-event [0]: offset reset (at offset -1001) to -1: waiting for broker offset: Broker: Leader not available ``

This is duplicate the issue https://github.com/edenhill/librdkafka/issues/192

How I can use store commit offset on broker?

Thanks!

**Comment by DEvil0000** [comment]
you can't - (as far as I know) it was never working (at least with this lib)

**Comment by edenhill** [comment]
Broker based offset storage worked with broker 0.8.1, but then it all changed for 0.8.2 and librdkafka does not yet support that, though it is in the works.
