### ISSUE TITLE
rdkafka not found on ubuntu 20.04

### ISSUE THREAD

**Issue by AldoCF96** [edenhill/librdkafka#3152]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
<your issue description goes here>

Error while installing and building the examples for librdkafka. 

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>
 the steps goes here after pulling the latest version from the github repository 

./configure
make 

and then: 

![image](https://user-images.githubusercontent.com/50414883/99618063-aad56880-29ee-11eb-8c7b-dfbd3a8d3bbc.png)

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<master>`
 - [ ] Apache Kafka version: `<>`
 - [ ] librdkafka client configuration: `<>`
 - [x] Operating system: `<ubuntu 20.04>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Try building with `./configure` and `make`.  The cmake build is not officially supported.

**Comment by AldoCF96** [comment]
Yes, I tried that, same error. Not solution found.

**Comment by edenhill** [comment]
Please do:

```bash
$ ./configure --clean
$ ./configure
$ make
```

And if that fails, please provide the full output.
