### ISSUE TITLE
Question. Message visibility time

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#3155]
Hi,

This is a question about producer message visibility in Kafka.

-----------------------T0--------------------T1----------------> (time)
1. T0 - producer application sends message M0 to topic.
2. T1 - the message M0, sent at T0, is visible to a consumer.

The question is - what is the longest time possible between T0 and T1, ie |T1-T0| = commit_time?

Considering all things that can go wrong:
1. The producer application retrying for up to "message.timeout.ms"
2. Kafka brokers restarting and resynching. A leader having local messages not yet replicated but eventually replicated...
3. Various network level latencies
3. Any other delays in the system i did not mention

Is there a formula based on some variables to establish the maximum value of commit_time? The reason i am asking is the following:

1. I have a process that produces messages (it does not use transactions). The same process consumes these messages.
2. This process detects that a message it produced does not appear in the topic when it consumes it.
3. The process needs to answer the question: "Did the message make it to the topic?"
4. How long should it wait for before concluding that the message did not end up in the topic?

I believe that if the value of commit_time can be established then if the process does not see that message for that time, it can conclude that it did not (and won't) make it to the topic.

**Comment by edenhill** [comment]
Given that M0 was actually accepted by the leader broker the longest commit_time, with isolation.level=read_committed, would be the maximum transaction.max.timeout.ms (broker property, defaults to 15 minutes).

If also taking producer-side retries into question then it would be message.timeout.ms + transaction.max.timeout.ms.

If transactions are not used, replace it with replica.lag.time.max.ms (30 s).

**Comment by edenhill** [comment]
But you don't need to use that kind of logic, simply make sure that your producer is using acks=all and that your topics are properly replicated by at least 3 brokers and Kafka will provide those guarantees for you.

**Comment by MaximGurschi** [comment]
Thank you @edenhill !

1. I am not using transaction - does that mean that the answer is?:
    commit_time = message.timeout.ms + replica.lag.time.max.ms
2. I cannot rely on acks=all. This is because acks can be returned before the data is fsynched to disk. However, as i have read, consumers receive only those messages that have been fsynched.
    I do use 3 brokers, full replication and min in sync replica set 2, but that is not sufficient given the fsync problem.

**Comment by edenhill** [comment]
> consumers receive only those messages that have been fsynched

I don't think that's correct.

**Comment by MaximGurschi** [comment]
@edenhill This is how i interpret this:
http://notes.stephenholiday.com/Kafka.pdf

" A message is only exposed to the consumers after it is flushed."

**Comment by edenhill** [comment]
Yeah I'm not sure that's correct for modern Kafka, but I don't really know, sorry.

**Comment by MaximGurschi** [comment]
Fair enough. Can you please just confirm this bit:

For non transactional producer?
commit_time ~= message.timeout.ms + replica.lag.time.max.ms

**Comment by edenhill** [comment]
Yep :+1:

**Comment by MaximGurschi** [comment]
Thank you.
