### ISSUE TITLE
Incompatible type for the Crc field in msg structs.

### ISSUE THREAD

**Issue by rohitvkumar** [edenhill/librdkafka#316]
Hi,

This may be an issue:

In rdkafka_broker.c (rd_kafka_messageset_handle:2753) 

struct {
			int64_t Offset;
			int32_t MessageSize;
			int32_t Crc;
			int8_t  MagicByte;
			int8_t  Attributes;
		} RD_PACKED *hdr;

the CRC value is stored in an int32_t field whereas the return value for the crc32(...) function is an uLong. This field is being populated by the crc32(..) function at locations 2101, 2106, 2120 etc. in rdkafka_broker.c

Same thing in (rd_kafka_broker_produce_toppar:1989)

struct {
		struct {
			int64_t Offset;
			int32_t MessageSize;
			int32_t Crc;
			int8_t  MagicByte;
			int8_t  Attributes;
		} __attribute__((packed)) part3;
		struct {
			int32_t Value_len;
		} __attribute__((packed)) part4;
	} *msghdr;

I noticed this in my testing that for random lengths of messages the broker fails to validate and responds with an Invalid Message error code. When I switched the type for the 'Crc' field in the structs to uint32_t the broker did not complain on any of the messages.

What is interesting is that this issue only manifests when I link the librdkafka library in our code base. Building the test app independent of our code base does not cause the failure.

**Comment by DEvil0000** [comment]
the problem is not exactly the type even if it is not so readable.
storing a on a 32Bit system long equals int - but it is a int there ;)
int and uint have the same size - just the interpretation is slightly different.
if you don't cast it at storing it is still valid and correct.
you just have to be careful later with every compare and cast.

to reduce error potential it is a good idea to use the more correct type there.

**Comment by DEvil0000** [comment]
please ignore the three auto connected messages before - I screwed up doing stuff in the wrong branch. And paying to less attention ;)
will commit the correct one again in a second.

**Comment by rohitvkumar** [comment]
Hi,

Thanks for the quick turnaround. 

Do you have an estimate of how soon the pull request will be accepted and merged into the main branch?

Thanks,
Rohit

**Comment by edenhill** [comment]
Now!
