### ISSUE TITLE
Consumer cannot consume messages during rehydration

### ISSUE THREAD

**Issue by ruishenmicrosoft** [edenhill/librdkafka#3162]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Our consumer is not able to consume messages during rehydration, we set it up to consume from 1500 offset from tail, but it is reset to LEO instead of tail offset, and we couldn't get the 1500 messages from tail. After that, we are able to consume 15 messages per minute (that's how many we produce), so the consume issue only exists during rehydration. By taking a closer look to the client log, we saw "Offset out of range" and invalid offset issue in it (for example: "updating to version 2 (was 2) at offset 2749330 (was -1001)"), please refer to the following sections for more details.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<1.4.2>`
 - [x] Apache Kafka version: `<2.4.1>`
 - [x] librdkafka client configuration: `<enable.auto.commit = false, auto.offset.reset = beginning, enable.partition.eof = true, fetch.wait.max.ms = 10, fetch.error.backoff.ms = 10, statistics.interval.ms = 600000>`
 - [x] Operating system: `<Windows 10 (x64)  Windows Server 2019 Datacenter, version 1809  OSBuild 17763.1518>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
[ProcessId: 93856] Level: Debug, Message: Consumer.RebalanceCallback: Mode: Assign, Count: 17 [Topic: ClusterHealth, Partition: 0, Offset: Invalid]

[ProcessId: 93856] Level: Debug, Message: [thrd:main]: OffsetReply for topic ClusterHealth [0]: offset 2749330: adjusting for OFFSET_TAIL(1500): effective offset 2747830

 

[ProcessId: 93856] Level: Debug, Message: [thrd:ssl://{IP}:{Port}/bootstrap]: ssl://{IP}:{Port}/2: ClusterHealth[0]: Fetch backoff for 10ms: Broker: Offset out of range

 

[ProcessId: 93856] Level: Debug, Message: [thrd:main]: ClusterHealth [0]: offset reset (at offset 2747830) to END: Broker: Offset out of range: Broker: Offset out of range

 

[ProcessId: 93856] Level: Debug, Message: [thrd:ssl://{IP}:{Port}/bootstrap]: Topic ClusterHealth [0]: fetch decide: updating to version 2 (was 2) at offset 2749330 (was -1001)
 - [x] Provide broker log excerpts
Timestamp	Level	Message	ClassName
2020-11-30 16:13:44.0060000	INFO	[ReplicaFetcher replicaId=1, leaderId=0, fetcherId=19] Node 0 was unable to process the fetch request with (sessionId=625402220, epoch=INITIAL): OFFSET_OUT_OF_RANGE.	org.apache.kafka.clients.FetchSessionHandler

 - [x] Critical issue: Yes

**Comment by edenhill** [comment]
Is it possible that the partition contains less than 1500 messages and TAIL thus referring to a message that no longer exists?
