### ISSUE TITLE
Query of creating 2 broker servers using librdkafka library in C++ Visual Studio 2019 application

### ISSUE THREAD

**Issue by SaiManasaS** [edenhill/librdkafka#3167]
Description
===========
I'm fairly new to Kafka. Following the tutorials and sample code I have put together a program to create 2 Kafka consumers, each subscribing to a different topic in C++ (using Visual Studio 2019). I created a Kafka environment on my local machine, following the steps in https://kafka.apache.org/quickstart.

My program can be available in https://github.com/SaiManasaS/BasicKafkaConsumer
main.cpp has 3 functions:
-> configKafkaConsumer()
-> subscribeToKafkaTopics(rd_kafka_t * rk, rd_kafka_topic_partition_list_t * topics) 
-> pollForMsgs(rd_kafka_t * rk1, rd_kafka_t * rk2)

Leaving all the configuration settings for the consumer, producer, server and zookeeper as they were when installed, I created a single broker in the code by setting the property 'bootstrap.servers', to my local host "localhost:9092".

So, I understand there is just a single broker, with 2 topics, each on a single partition (as defined in default configuration file).

**Steps for testing the application:**
1) I started zookeeper followed by the server on my local machine. 
2) I created 2 topics on my Windows terminal using the .bat files. (topic names: firsttopic1, secondtopic1)
3) Then I created 2 producers publishing to the above 2 topics created.
4) Next I started my application (ran the exe after building it in Visual Studio 2019)
5) I sent sample messages on each of my producers and was able to see them appear on my application (exe window).

The test was a success.

Now, I want to extend the functionality to connect to 2 broker servers.
I modified my program to state the CSV string to state 2 brokers

, I supplied the string: "localhost:9092,52.111.222.217:9092" in the bootstrap-servers property of my application.

After making this change in my application, I again followed the above 'Steps for testing the application'. This time, I was NOT able to receive any message from either of the local host producers. 

My assumption was, that even though I created 2 brokers, one being my local machine as a broker, at least messages from my broker were supposed to show up, irrespective of the second broker (52.111.222.217:9092, which is sitting else where), messages showing up. 

However, I couldn't see any message showing up in my application's console.

Will highly appreciate any guidance in configuring my application to work with 2 broker servers.

How to reproduce
================
Run a local Kafka server by:
1) Starting a zookeeper followed by the server on my local machine. (zookeeper-server-start.bat, kafka-server-start.bat)
2) Creating 2 topics on my Windows terminal using the .bat files. (topic names: firsttopic1, secondtopic1) (kafka-topics.bat)
3) Creating 2 producers publishing to the above 2 topics created. (kafka-console-producer.bat)
4) Starting my application (ran the exe after building it in Visual Studio 2019)
5) Send sample messages on each of my producers and was able to see them appear on my application (exe window).

Checklist
=========
Please find the following information:

 - [x] librdkafka version: 1.5.2 
 - [x] Apache Kafka version: kafka_2.13-2.6.0
 - [ ] librdkafka client configuration: all defaults
 - [x] Operating system: Windows 10 Home (x64)
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

Attached are the properties files used for creating Kafka local environment:
[connect-distributed_properties.txt](https://github.com/edenhill/librdkafka/files/5642886/connect-distributed_properties.txt)
[consumer_properties.txt](https://github.com/edenhill/librdkafka/files/5642887/consumer_properties.txt)
[producer_properties.txt](https://github.com/edenhill/librdkafka/files/5642888/producer_properties.txt)
[server_properties.txt](https://github.com/edenhill/librdkafka/files/5642889/server_properties.txt)
[zookeeper_properties.txt](https://github.com/edenhill/librdkafka/files/5642891/zookeeper_properties.txt)

**Comment by edenhill** [comment]
Are the two brokers part of the same cluster?
Enable `debug=consumer` to see what is going on in the client (or `debug=broker,cgrp` for more detail).

**Comment by rolandyoung** [comment]
To set debug in your C++ program, you use `rd_kafka_conf_set(config, "debug", "consumer")` The log4j properties you refer to apply to Java programs.
Unless your local broker is connecting to the same Zookeeper cluster as the broker at 52.111.222.217:9092, it is **not** in the same cluster. You probably need to test your proposed Kafka setup using the Java command line tools before trying to debug your C++ program. For example, try to use the command line consumer to subscribe to the same broker and topics that you want your program to use.
One additional hint (based on looking at your source code): you can subscribe to multiple topics using a single consumer handle (rd_kafka_t). You would not usually use multiple handles unless you are running independent threads of execution or if you need to both consume and produce messages.

**Comment by SaiManasaS** [comment]
@rolandyoung: Sure, Thank you for your inputs, let me try them out. I see much documentation regarding Kafka implementation with Java, as compared to C++, thanking you for your inputs!

**Comment by SaiManasaS** [comment]
@rolandyoung & @edenhill: I was able to create a Kafka cluster on my local machine following the below steps and was able to get the application running. Thank you for your inputs!
1) Created 2 Kafka folders (after downloaded from apache.org)

2) In server.properties, broker.id=1, broker.id=2 in each of the folders
listeners=PLAINTEXT://localhost:9092 listeners=PLAINTEXT://localhost:9091
log.dirs=C:/Kafka/kafka_2.13-2.6.0_2/logs & log.dirs=C:/Kafka/kafka_2.13-2.6.0_1/logs
zookeeper.connect=localhost:2181, zookeeper.connect=localhost:2181 in each one
This is the local zookeeper IP and port.

Also modified zookeeper.properties in each of the folders:
dataDir=C:\Kafka\kafka_2.13-2.6.0_1\data
dataDir=C:\Kafka\kafka_2.13-2.6.0_2\data

3) Started zookeeper from one of the above Kafka folders: bin\windows\zookeeper-server-start.bat config\zookeeper.properties

Started 2 Kafka servers from each of the above Kafka folders:
bin\windows\kafka-server-start.bat config\server.properties

4) Created 2 Kafka producers and created and published to topics
5) Created 2 Kafka consumers and subscribed to and listened to the topics

**Comment by SaiManasaS** [comment]
@rolandyoung & @edenhill: I was able to create a Kafka cluster on my local machine following the below steps and was able to get the application running. Thank you for your inputs!
1) Created 2 Kafka folders (after downloaded from apache.org)

2) In server.properties, broker.id=1, broker.id=2 in each of the folders
listeners=PLAINTEXT://localhost:9092 listeners=PLAINTEXT://localhost:9091
log.dirs=C:/Kafka/kafka_2.13-2.6.0_2/logs & log.dirs=C:/Kafka/kafka_2.13-2.6.0_1/logs
zookeeper.connect=localhost:2181, zookeeper.connect=localhost:2181 in each one
This is the local zookeeper IP and port.

Also modified zookeeper.properties in each of the folders:
dataDir=C:\Kafka\kafka_2.13-2.6.0_1\data
dataDir=C:\Kafka\kafka_2.13-2.6.0_2\data

3) Started zookeeper from one of the above Kafka folders: bin\windows\zookeeper-server-start.bat config\zookeeper.properties
