### ISSUE TITLE
Topic name not applicable

### ISSUE THREAD

**Issue by karentsarukyan** [edenhill/librdkafka#3168]
Hi,

I have wrote a consumer application using librdkafka. I am using RdKafka::KafkaConsumer::consume method to process messages.
The problem is topic_name() returns an empty string under Windows. In the documentation I see the following comment:
"returns Topic name (if applicable, else empty string)"
But I am having trouble to find further details about when it is not applicable.
In fact under Linux I do receive the expected topic name.
Could you please provide more info? Is there a way to always get the topic name with each message?

**Comment by edenhill** [comment]
Check Message->err() to see if the Message is actually an error event, if not then topic_name() should be defined.

**Comment by karentsarukyan** [comment]
Thanks a lot for a quick response.
That is exactly what I am doing. First checking Message->err(), which is ERR_NO_ERROR, then querying the data. Everything else is as expected, key, paylpoad, etc ... but the topic name is an empty string.

**Comment by karentsarukyan** [comment]
Thanks a lot! Solved.
