### ISSUE TITLE
Need access to offset of control messages in consumer

### ISSUE THREAD

**Issue by pf-qiu** [edenhill/librdkafka#3171]
Currently librdkafka hides control messages from application. Normally client application shouldn't care about control messages as long as librdkafka handles it transparently.
There's one edge case where client wants to know the offset of last control message.
1. Producer produces message using transaction, and stop. So no more incoming messages.
2. Client application consume messages until EOF. Client records the offset of last valid message, say 100. But actually there's one more hidden control message in the topic with offset 101.
3. After client stops, retention period expires and all messages in the topic are discarded.
4. Producer starts again, from offset 102.
5. Client application starts consume from the last offset it recorded. But it will detect that message at offset 101 is missing. At this point consumer can't tell whether it's error or just normal transaction message.

I would like to propose a configuration switch just like "enable_partition_eof", for example "enable_control_message". When enabled librdkafka will emit a special message including information for control message.

**Comment by edenhill** [comment]
You shouldn't make any assumptions on offset sequences, or "missing offsets", messages may be removed due to compaction or whatever future reasons.

**Comment by pf-qiu** [comment]
> You shouldn't make any assumptions on offset sequences, or "missing offsets", messages may be removed due to compaction or whatever future reasons.
We don't care about what kind of control message it is, just the fact that the message at every offset is correctly handled before it's removed.
Our use case requires us to record offset every message we process, and report fatal error if any offset is missing. Then user intervention is required. This is another layer of exactly once guarantee we are trying to implement.
In step 2 of above example, actually the control message at 101 is already processed by librdkafka, but client application doesn't know and records 100 as last offset incorrectly. If we have access to control messages then we could correctly record 101 as the last message and start at 102 without any problem the next time.
librdkafka already records offset of control messages internally, we just want to replicate that behavior to external storage.

**Comment by edenhill** [comment]
Kafka does not provide any guarantees that a consumer will get a range of offsets without any gaps, so you shouldn't rely on that in your application.
