### ISSUE TITLE
Building latest release (1.5.2) on linux add debug information to the created object files and static library

### ISSUE THREAD

**Issue by Eliyahu-Machluf** [edenhill/librdkafka#3172]
Description: 
===========
When building librdkafka on Linux, I see it has debug information (gcc -g flag), and the artifact is much larger than before. i.e. librdkafka.a size is ~12MB, while before it was ~1.3MB.
I know I can run a strip command and remove this debug information, however, I think it is better be handled by the configure script.

How to reproduce
================
download librdkafka-1.5.2.tar.gz
extract it and run the command ./configure.
you'll see at output result:
**CPPFLAGS                 -g**  ....
now run make, for each gcc command you'll see this '-g' flag. 
gcc -MD -MP **-g** -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align  -c rdkafka.c -o rdkafka.o
The size of the output static library librdkafka.a is about 12MB.

Checklist
=========
 - [x] librdkafka version (release number or git tag): `1.5.2`
 - [x] Apache Kafka version: `not relevant`
 - [x] librdkafka client configuration: `not relevant`
 - [x] Operating system: `RedHat 6.2`

**Comment by massada** [comment]
Seems to affect a few dists.

![Screenshot 2020-12-19 at 02 21 40](https://user-images.githubusercontent.com/8666702/102678739-469af580-41a2-11eb-84e9-565c143b893f.png)

**Comment by edenhill** [comment]
What was the previous release were you saw smaller image sizes?

**Comment by Eliyahu-Machluf** [comment]
1.3.0

**Comment by edenhill** [comment]
Libraries are now stripped on install

**Comment by Eliyahu-Machluf** [comment]
Thanks.
