### ISSUE TITLE
How to use librdkafka to change retention time for the running kafka topic?

### ISSUE THREAD

**Issue by xiangPoolin** [edenhill/librdkafka#3175]
We can use the following command in kafka machine to update the retention time for the running kafka topic:

`    bin/kafka-topics.sh --zookeeper <kafka_ip> --alter --topic <target_topic> --config retention.ms=86400000`

But I don't want to login to the kafka machine and run the command.
I just want to use C or C++ to change kafka retention time for the running kafka topic in the remote producer machine.

**Question is: Can we use api in librdkafka to update the retention time for the running kafka topic?** 

note: Now we can produce and consume kafka data with C/C++.

**Comment by edenhill** [comment]
`rd_kafka_AlterConfigs()`

**Comment by horchi** [comment]
is there also a way to set the retention time by the C++ API?
If not:
- how I can get the rd_kafka_t* from the RdKafka::Topic to pass it to rd_kafka_AlterConfigs()?
- is there a example for rd_kafka_AlterConfigs()?

**Comment by edenhill** [comment]
use c_ptr() on your RdKafka::Handle (Producer or Consumer) to get rd_kafka_t* pointer.
https://github.com/edenhill/librdkafka/blob/master/tests/0081-admin.c#L731

**Comment by horchi** [comment]
Thx ist works :+1: 
Is planned to put this in the C++ API?

**Comment by edenhill** [comment]
There will not be an Admin API in C++, the surface area is too big and the C Admin API is usable from C++.
