### ISSUE TITLE
suggesting test improvement: test preconditions

### ISSUE THREAD

**Issue by DEvil0000** [edenhill/librdkafka#318]
some of the tests require some special conditions.
* only one partition
* two partitions
* three brokers (& replication factor?)
the tests should read the metadata and fail if the preconditions are not fulfilled.

**Comment by edenhill** [comment]
Yeah, test precond tests would be good.
Sooner or later the tests will move to some kind of virtualization environment where the proper number of brokers are spawned with appropriate config, but until then this is good.

**Comment by DEvil0000** [comment]
even later it is a good thing - in case someone would like to run the tests on his/her machine.

**Comment by edenhill** [comment]
This is handled now by the trivup-based test clusters.
