### ISSUE TITLE
Can I delete the conf pointer after the producer pointer is created?

### ISSUE THREAD

**Issue by prehistoric-penguin** [edenhill/librdkafka#3181]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Thanks for this great project!
I have a question about the conf object lifetime.

Description
===========
Take this code snippet for example:

```
RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);

ExampleDeliveryReportCb ex_dr_cb; 
conf->set("dr_cb", &ex_dr_cb, errstr);

ExampleEventCb ex_evt_cb; 
conf->set("event_cb", &ex_evt_cb, errstr);
RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);

delete conf;

// Then store producer as class data member and use it through all the process lifetime

while (running) {
  generate_data();
  producer->produce(...);
}

delete producer;
```
Is it safe to use?
If it's safe, then seems that the `ExampleDeliveryReportCb` object needs to be ensured to live since the pointer has been stored someplace in the producer, is this right?
Is `ExampleEventCb` dealt the same with  `ExampleDeliveryReportCb`?

How to reproduce
================
N/A

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

Not necessary, it's a common question.

**Comment by edenhill** [comment]
The `conf` object may be deleted after `Producer::create()`, but the callback class instances must not go out of scope, in your case make sure `ex_dr_cb` stays valid for the duration of the Producer lifetime.

**Comment by prehistoric-penguin** [comment]
Thanks so much!
