### ISSUE TITLE
Pending messages

### ISSUE THREAD

**Issue by horchi** [edenhill/librdkafka#3183]
I'm wondering how I can query the count of pending messages on a topic related to the actual position consumer.
I don't know if this is a feature request or already supported.

Thx and regards, Jörg

**Comment by edenhill** [comment]
You can calculate the consumer lag by comparing the partition high watermark with the current consume position.
See rd_kafka_query_watermark_offsets() and rd_kafka_position() (or rd_kafka_committed()).
There's also a `consumer_lag` metric maintained in the statistics https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

**Comment by horchi** [comment]
that's what I'm looking for. Thanks!
