### ISSUE TITLE
Local: Host resolution failure

### ISSUE THREAD

**Issue by dinohrascanec** [edenhill/librdkafka#3184]
**Problem**
We're having a problem connecting to a remote broker from local environment. We're using arnaud-lb/php-rdkafka library for this. There is a remote producer that created a topic and put some content in it. We created a consumer and added previously mentioned IP and topic. However, we get error "Local: Host resolution failure". 

**Info**
 * PHP version: 7.1
 * librdkafka version: latest
 * php-rdkafka version: latest
 * kafka version: latest

**Code**
```
<?php
$conf = new RdKafka\Conf();
$conf->set('log_level', (string) LOG_DEBUG);
$conf->set('debug', 'all');
$rk = new RdKafka\Consumer($conf);
$rk->addBrokers("XX.XX.XX.XX:9092");
$topic = $rk->newTopic("test-topic-1");

$topic->consumeStart(0, RD_KAFKA_OFFSET_BEGINNING);
while (true) {
    $msg = $topic->consume(0, 1000);
    if (null === $msg || $msg->err === RD_KAFKA_RESP_ERR__PARTITION_EOF) {
        continue;
    } elseif ($msg->err) {
        var_dump($msg);
        echo $msg->errstr(), "\n";
        break;
    } else {
        echo $msg->payload, "\n";
        exit;
    }
}

```

**Error:**
```
object(RdKafka\Message)[4]
   'err' => int -193
   'topic_name' => string 'test-topic-1' (length=12)
   'timestamp' => null
   'partition' => int 0
   'payload' => null
   'len' => null
   'key' => null
   'offset' => int -1
   'headers' => null
Local: Host resolution failure
```

**Comment by edenhill** [comment]
There's probably a log line saying what it tried to resolve, something like:
`Failed to resolve '....': ...`
