### ISSUE TITLE
Notification / trigger on new messages

### ISSUE THREAD

**Issue by horchi** [edenhill/librdkafka#3185]
Is there a kind of notification interface like a callback which is triggered (without getting the message itself) every time a new message appear to a topic? Or is the only way calling the consume method?

**Comment by edenhill** [comment]
No such thing, no.

**Comment by horchi** [comment]
does it is possible regarding the kafka protocol and may be a feature in future releases of the librdkafka?

**Comment by edenhill** [comment]
What's the use-case?

**Comment by horchi** [comment]
the process is doing a lot oft stuff and has a central point for notifications like a message hock and all stuff is triggered there. 
To do so even for the kafka messages I have a thread which consume a message, trigger the process and wait until the process has fetched the message from the thread. A pure notification thread will fir better into this framemework, after such a trigger the process can conmule the message by itself and continue consuming until all pending messages are consumed.

**Comment by edenhill** [comment]
You could use IO triggering to see when there are messages (or events) on the consumer queue:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L3253
