### ISSUE TITLE
offsetsForTimes() and assign()

### ISSUE THREAD

**Issue by YarinLowe** [edenhill/librdkafka#3186]
Description
===========
I use `offsetsForTimes()` in order to get the earliest offset of messages produced at or after a given timestamp.
Then, I use `assign()` to start consuming from the resulted offset.
I noticed that when the partition is empty, or there are no messages at or after the given timestamp, `offsetsForTimes()` returns (-1) as the offset for the partition (which is not documented anywhere, as far as I could find).
Also, I noticed that using this offset (-1) in the `assign()` function actually works as assigning the end of the partition (thus, consuming new messages only).
I would be glad to get some formal information or a referral to relevant documentation, that this behavior is indeed on purpose and well-defined (about both getting (-1) by `offsetsForTimes()` and using `assign()` with offset -1).

Thanks!

Checklist
=========
 - [x] librdkafka version (release number or git tag): `v1.5.2`
 - [x] Apache Kafka version: `2.6.0`
 - [x] librdkafka client configuration: `default`
 - [ ] Operating system: `Ubuntu 16.04 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The brokers returned from the broker is passed as-is to the application, -1 probably meaning invalid, you should check the per-partition .err field before using the offset.

**Comment by YarinLowe** [comment]
I checked the per-partition .err field, but it says NO_ERROR.
What about using `assign()` with offset of `-1`? Is it a defined behavior to assign the latest offset?

**Comment by edenhill** [comment]
-1 is RD_KAFKA_OFFSET_END; start reading from end of partition. So that will work, but may not be what you wish.
Best choice is to convert -1 to RD_KAFKA_OFFSET_INVALID and then let the consumer rely on `auto.offset.reset` to decide what to do on unknown offsets.
