### ISSUE TITLE
Can't recover when message delivery error "Local: Message timed out"

### ISSUE THREAD

**Issue by wangyg193** [edenhill/librdkafka#3189]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
When the Kafka broker is re-elected, during the election process, the Kafka producer will report Local: Message timed out. After the election, the vast majority of Kafka producers will return to normal and write Kafka successfully, but a few instances still report Error: Local time out. For example, when 160 containers appeared in a certain time, 157 recovered, and 3 still reported errors.

How to reproduce
================
The current version of librdkafka is 0.11.0. Since it is only a production system that has been running for two years, librdkafka has not been updated to the latest version.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [0.11.0] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [2.0 ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [message.timeout.ms=30000 ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [RedHat 7.2 ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
0.11.0 is really old, there's been a vast number of fixes and enhancements
since then.
Highly recommend upgrading to the latest version.

Den fre 25 dec. 2020 10:19wangyg <notifications@github.com> skrev:

**Comment by wangyg193** [comment]
I will upgrade to the latest version，thank you very much！
