### ISSUE TITLE
Win64 & VC++ 2019 & PVS-Studio report

### ISSUE THREAD

**Issue by pavel-pimenov** [edenhill/librdkafka#3190]
http://oracle.fly-server.ru/pvs-studio/librdkafka/
Date:	12/26/20 22:31:55
PVS-Studio Version:	7.11.44142.2691
Total Warnings (GA):	1288
Total Warnings (OP):	169
Total Warnings (64):	70

**Comment by pavel-pimenov** [comment]
update http://oracle.fly-server.ru/pvs-studio/librdkafka/

**Comment by edenhill** [comment]
Thank you. Went through the High severity ones in src/ and src-cpp/, but none of them were real problems.

**Comment by edenhill** [comment]
Not entirely true, it did find one real issue: flush() timeout was not respected in DR_EVENT_MODE

**Comment by pavel-pimenov** [comment]
update http://dc.fly-server.ru/pvs-studio/librdkafka/
PVS Studio version - 7.29.79138.387
