### ISSUE TITLE
Adding a produce() flag to free msg_opaque (like RD_KAFKA_MSG_F_FREE)

### ISSUE THREAD

**Issue by arnaud-lb** [edenhill/librdkafka#3192]
Description
===========

In bindings for memory managed languages, freeing a `msg_opaque` is tricky.

Adding a flag to `rd_kafka_produce()` that allows librdkafka to free the `msg_opaque`, as `RD_KAFKA_MSG_F_FREE` does for the payload, would be very helpful.

The flag could be named `RD_KAFKA_MSG_OPAQUE_F_FREE`, and passing it to `rd_kafka_produce()` and variants would cause `rd_kafka_msg_destroy()` to free `->rkm_opaque`.

Would you accept a PR with this change?

Checklist
=========

 - [x] librdkafka version: `e116a873bbe395b78d3b40171afa9c68dc93da78`
 - [x] Feature request

**Comment by edenhill** [comment]
Why can't you free it in the delivery report callback?

**Comment by arnaud-lb** [comment]
We could, but will it be called in all cases, including when the `rd_kafka_t` is destroyed while a message is still queued ?

**Comment by arnaud-lb** [comment]
Actually I could handle this by keeping track of inflight `msg_opaques` and free them after `rd_kafka_destroy()`

**Comment by edenhill** [comment]
You can call purge() to force delivery callbacks for queued messages.

Den mån 28 dec. 2020 17:42Arnaud Le Blanc <notifications@github.com> skrev:

**Comment by arnaud-lb** [comment]
Oh, this is perfect! Thanks :)
