### ISSUE TITLE
rdkafkacpp_int.h:974: bad call to free ?

### ISSUE THREAD

**Issue by dcb314** [edenhill/librdkafka#3194]
rdkafkacpp_int.h: In member function 'virtual RdKafka::ErrorCode RdKafka::HandleImpl::oauthbearer_set_token(const string&, int64_t, const string&, const std::__cxx11::list<std::__cxx11::basic_string<char> >&, std::string&)':
rdkafkacpp_int.h:974:15: warning: 'void free(void*)' called on pointer returned from a mismatched allocation function [-Wmismatched-new-delete]
  974 |           free(extensions_copy);
      |           ~~~~^~~~~~~~~~~~~~~~~
rdkafkacpp_int.h:961:76: note: returned from 'void* operator new [](std::size_t)'
  961 |           const char **extensions_copy = new const char *[extensions.size()];
      |                                                                            ^

**Comment by edenhill** [comment]
Yes, that should be a `delete ..`, will fix. Thank you.
