### ISSUE TITLE
Local: Message timed out error while producing continuous image frames to Kafka brokers list of 3 - Python Language (confluent_kafka==1.5.0)

### ISSUE THREAD

**Issue by Udayaprasad** [edenhill/librdkafka#3195]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

I am facing a "Local: Message timed out" error while producing continuous image frames to Kafka brokers list of 3.

There are 10 cameras, each camera sending a video feed to one specific topic (10 cameras... 10 topics) having 2 partitions each.

The producer is running for sometime smoothly, but after a certain time, it is throwing the following error. 

```
2021-01-01 20:13:05,067 default      ERROR    Failed to deliver message: b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x
```

I am using the following kafka docker images.
```
confluentinc/cp-kafka:5.5.3
zookeeper:3.4.9
```

Producer config:
```
"bootstrap.servers": "host1:port1,host2:port2,host3:port3",
"enable.idempotence": true,
"acks": "all",
"retries": 5,
"max.in.flight": 1,
"debug":"protocol,broker,msg,queue",
"max.in.flight.requests.per.connection": 5,
"linger.ms": 0,
"batch.num.messages": 32
```

Thanks,
Uday

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by Udayaprasad** [comment]
[error_logs.log](https://github.com/edenhill/librdkafka/files/5759246/error_logs.log)

**Comment by edenhill** [comment]
max.in.flight=1 ruins your throughput (and you are setting it to both 1 and 5..)
I highly recommend removing all non-essential configuration, the defaults are suitable for most use-cases.
Also, to increase thruput, increase linger.ms.

Recommend this config for you:
```
"bootstrap.servers": "host1:port1,host2:port2,host3:port3",
"enable.idempotence": true,
"linger.ms": 5,
```

**Comment by Udayaprasad** [comment]
@edenhill 
Thank you for your response. The issue got resolved not. I increased following parameters while spinning up the containers.

`KAFKA_LOG_SEGMENT_BYTES: 16777216
      KAFKA_LOG_RETENTION_BYTES: 134217728
      KAFKA_MESSAGE_MAX_BYTES: 30000036
      KAFKA_NUM_IO_THREADS: 16
      KAFKA_NUM_NETWORK_THREADS: 6
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_NUM_REPLICA_FETCHERS: 3
      KAFKA_REPLICA_FETCH_MAX_BYTES: 30000036`
      
      increasing `linger.ms` will put more latency
`This setting defaults to 0 (i.e. no delay). Setting linger.ms=5, for example, would have the effect of reducing the number of requests sent but would add up to 5ms of latency to records sent in the absence of load.`

**Comment by edenhill** [comment]
You will need to find the right balance between throughput (higher linger.ms) and latency (lower linger.ms).
