### ISSUE TITLE
How to check librdkafka version in Linux?

### ISSUE THREAD

**Issue by BinZhiZhu** [edenhill/librdkafka#3198]
We compiled and installed manually ，how to check version ?

**Comment by rolandyoung** [comment]
You could
1. `grep RD_KAFKA_VERSION rdkafka.h`, or
2. Write a program that calls rd_kafka_version_str()

However, if you have simply cloned github.com:edenhill/librdkafka.git and built the latest commit, you probably have the current bleeding-edge version. This is not the best version to use if you want to ask for support.

You might want to rebuild the current supported release instead:

1. git checkout v1.5.3 (or whatever is the current release at the time you read this)
2. build and install as before

**Comment by BinZhiZhu** [comment]
I got it,so great ~ thank u for ur help
