### ISSUE TITLE
Segmentation fault when using SSL security protocol

### ISSUE THREAD

**Issue by jpnorenam** [edenhill/librdkafka#3200]
Description
===========
Memory leakage when using `SSL` or `SASL_SSL` as `security.protocol` in [`rd_kafka_ssl_ctx_init`](https://github.com/edenhill/librdkafka/blob/e9f34032d15668946bd0b889fb0765949d0e9920/src/rdkafka_ssl.c#L1323-L1324). The `errstr` variable assignation leads into a `SIGSEGV`.

I had to comment the [lines](https://github.com/edenhill/librdkafka/blob/e9f34032d15668946bd0b889fb0765949d0e9920/src/rdkafka_ssl.c#L1323-L1324) to make it work for me.

Checklist
=========

 - [x] librdkafka version: `v1.6.0`
 - [x] Apache Kafka version: `v5.5.0`
 - [x] librdkafka client configuration: `security.protocol=SASL_SSL, ssl.ca.location=path/to/ca.pem, sasl.mechanisms=SCRAM-SHA-512`
 - [x] Operating system: `debian buster (10)`
 - [ ] Provide logs
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That probably means you are calling rd_kafka_new() with invalid errstr/errstr_size parameters.
