### ISSUE TITLE
Exception: Access violation when trying to access conf->set() using RdKafka::Conf::create() in rdkafkacpp.h

### ISSUE THREAD

**Issue by SaiManasaS** [edenhill/librdkafka#3205]
Description
===========
I am trying to create a simple Kafka consumer application using the functions in rdkafkacpp.h

Steps followed in code include:
1) Created an RdKafka::Conf* conf object & RdKafka::Conf* tconf
2) Set configuration properties such as 'client.id', 'group.id', 'bootstrap.servers' 
3) Create a Kafka consumer using RdKafka::Consumer::create()

My code is available at https://github.com/SaiManasaS/KafkaCPPExample/blob/main/main.cpp

However, after creating an RdKafka::Conf* conf object in step1, when I was trying to set configuration properties in step 2, during execution, the function was throwing a runtime 'access violation exception'. A snapshot of the error is attached as an image.
<img width="717" alt="KafkaSecond_Exception" src="https://user-images.githubusercontent.com/42083395/104022282-1913fb80-51e6-11eb-9492-dcf1cad5cc07.PNG">

How to reproduce
================
1) Build an application with main.cpp (from Github: https://github.com/SaiManasaS/KafkaCPPExample/blob/main/main.cpp)
2) Execute the application.

Checklist
=========
Please find the following information:

 - [x] librdkafka version: 1.5.2
 - [x] Apache Kafka version: kafka_2.13-2.6.0
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: Windows 10 Home (x64)
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
How are you installing librdkafka? Through nuget?

**Comment by SaiManasaS** [comment]
@edenhill: Yes, that's right, I'm using the Nuget Manager to install librdkafka.

**Comment by edenhill** [comment]
The code looks good so I'm guessing this is a linking problem, you'll really need to run this in a debugger to figure out what is going on.
