### ISSUE TITLE
exception is: 'cimpl.Message' object has no attribute 'get' with latest version of librdkafka and even with 1.4.0

### ISSUE THREAD

**Issue by bezawada27** [edenhill/librdkafka#3207]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
My application is running on confluent-kafka 0.11.5 and librdkafka that is below 1.0.0. I cannot use enable.idempotence with the current version. So i update confluent-kafka to use 1.5.0 and librdkafka to latest version. When i run application Producer is throwing an error "exception is: 'cimpl.Message' object has no attribute 'get'

Any suggestions on how we can solve this?

How to reproduce
================
Application runs in docker container and we follow below steps to create image
Only change is the the version of confluent-kafka and librdkafka.

Producer Object configurations i use
p = Producer({'bootstrap.servers': ,
                          'queue.buffering.max.messages': 
                          'queue.buffering.max.ms': 
                          'batch.num.messages': ,
                          'group.id': ,
                          'enable.idempotence': 'true',
                          'message.send.max.retries': ,
                          'security.protocol': 'SASL_SSL',
                          'sasl.mechanisms': 'GSSAPI',
                          'sasl.kerberos.service.name': ,
                          'sasl.kerberos.principal': 
                          'sasl.kerberos.keytab': ,
                          'ssl.ca.location': ,
                          'default.topic.config': {'acks': 'all'}
                          })

and
producerObj.produce(topic=topic_name, key=partition_key, value=message,
                                         callback=self.delivery_callback)
producerObj.poll(0)

This is happening randomly on few messages. But not occuring when i use old version of kafka,librdkafka and with out enable.idempotence

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.4.0 and also used latest 1.5.3`
 - [x] Apache Kafka version: `Using confluent-kafka 1.5.0 version`
 - [x] librdkafka client configuration: `mostly default`
 - [x] Operating system: `rhel7`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by bezawada27** [comment]
this is happening randomly on few messages. How to enable debug logging for these issues?

**Comment by edenhill** [comment]
Can you show me the Python source code line that raises this error?=

**Comment by bezawada27** [comment]
> Can you show me the Python source code line that raises this error?=

        try:
            self.producerObj.produce(topic=topic_name, key=partition_key, value=message,
                                     callback=self.delivery_callback)
            self.producerObj.poll(0)
        except (KafkaError, IndexError, AttributeError, KafkaException, BufferError) as e:
            if self.logger.isEnabledFor(logging.ERROR):
                self.logger.error('Exception is: ' + str(e))
        except Exception as e:
            if self.logger.isEnabledFor(logging.ERROR):
                self.logger.error('Other Exception: ' + str(e))

    def delivery_callback(self, err, msg):
        if err:
            if self.logger.isEnabledFor(logging.ERROR):
                self.logger.error('Message delivery failed:' + str(err) + ' to a topic: '
                                  + str(msg.topic()) + ' on partition: ' + str(msg.partition())
                                  + ' at offset : ' + str(msg.offset()) + ' + message: ' + msg.get())
        else:
            if self.logger.isEnabledFor(logging.DEBUG):
                self.logger.debug('Message delivered to a topic: ' + str(msg.topic()) + ' on partition: ' +
                                  str(msg.partition()) + ' at offset : ' + str(msg.offset()))
So i get into exception block and and exception says exception is: 'cimpl.Message' object has no attribute 'get'
Some messages go through and some don't

**Comment by edenhill** [comment]
You have a `msg.get()` in the delivery_callback, but there is no `get()` method on Message type.
You probably want `msg.value()`

**Comment by bezawada27** [comment]
> You have a `msg.get()` in the delivery_callback, but there is no `get()` method on Message type.
> You probably want `msg.value()`

Right! My bad
I will remove that.
If it is coming to delivery_callback  err block. Will the message delivery be retried automatically?

**Comment by edenhill** [comment]
The delivery report callback will be called once per message, indicating success or permanent failure (after all retries exhausted).
The application should not attempt retry.
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#message-reliability
