### ISSUE TITLE
Add by default librdkafkacpp.lib in the link dependencies

### ISSUE THREAD

**Issue by mariomastrodicasa** [edenhill/librdkafka#3208]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
On NuGet package, whitin _librdkafka.redist.targets_, it is missing the reference to **librdkafkacpp.lib**. _librdkafka.redist.targets_ links only to C version and to use C++ version it is mandatory to link against **librdkafkacpp**. Every time I need to update the local _librdkafka.redist.targets_ with this snippet:

```
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <Link>
      <AdditionalDependencies Condition="'$(Platform)' == 'x64'">$(MSBuildThisFileDirectory)lib\win\x64\win-x64-Release\v120\librdkafka.lib;$(MSBuildThisFileDirectory)lib\win\x64\win-x64-Release\v120\librdkafkacpp.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalDependencies Condition="'$(Platform)' != 'x64'">$(MSBuildThisFileDirectory)lib\win\x86\win-x86-Release\v120\librdkafka.lib;$(MSBuildThisFileDirectory)lib\win\x86\win-x86-Release\v120\librdkafkacpp.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalLibraryDirectories Condition="'$(Platform)' == 'x64'">$(MSBuildThisFileDirectory)lib\win\x64\win-x64-Release\v120;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalLibraryDirectories Condition="'$(Platform)' != 'x64'">$(MSBuildThisFileDirectory)lib\win\x86\win-x86-Release\v120;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
    <ClCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory)include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup Condition="'$(Platform)' == 'x64'">
    <ReferenceCopyLocalPaths Include="$(MSBuildThisFileDirectory)..\..\runtimes\win-x64\native\*.dll" />
  </ItemGroup>
  <ItemGroup Condition="'$(Platform)' != 'x64'">
    <ReferenceCopyLocalPaths Include="$(MSBuildThisFileDirectory)..\..\runtimes\win-x86\native\*.dll" />
  </ItemGroup>
</Project>
```

How to reproduce
================
Use any NuGet package from C++ API.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): all versions
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration: 
 - [ ] Operating system: 
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
We don't want to link non-C++ applications with the C++ library though.

**Comment by mariomastrodicasa** [comment]
The answer seems right for non-C++ applications, even if all DLLs (**librdkafkacpp.dll** too) are copied to the target folder. Now the question is how to link against C++ API without change _librdkafka.redist.targets_.
