### ISSUE TITLE
consumer group----can  rdkafka library support  consumer  group

### ISSUE THREAD

**Issue by beitiandijun** [edenhill/librdkafka#321]
can rdkafka library support  consumergroup？
if not support， why and when to support

**Comment by DEvil0000** [comment]
kind of.
you can use a different offset for each group.
but there is no consumer balancing or such. this needs ZK and librdkafka has no ZK integrated.

**Comment by edenhill** [comment]
Proper broker based consumer balancing will be available when Apache Kafka 0.9 is released.
For the time being you will need to conceive something on your own with libzookeeper and librdkafka

**Comment by edenhill** [comment]
Tracking issue is #152
