### ISSUE TITLE
ALL_BROKERS_DOWN won't be received on an 'idle' producer

### ISSUE THREAD

**Issue by YarinLowe** [edenhill/librdkafka#3210]
Description
===========
Hi,
I have 2 producer instances with similar configuration (more or less the default one).
With one of them, I periodically produce messages and polling for DRs.
With the second, I'm not producing any messages, just periodically polling for DRs (on another thread, apart from the first producer).
Both producers registered an event callback.

Then, I kill the whole cluster (3 brokers) and expecting to receive ALL_BROKERS_DOWN error event on both producers.
The first producer (which produces messages) gets the error event, but the second one won't get anything.

Is there anything I miss here? Shouldn't I get the error event on both producers?

Thanks!

Checklist
=========
 - [x] librdkafka version (release number or git tag): `v1.5.2`
 - [x] Apache Kafka version: `2.7.0`
 - [x] librdkafka client configuration: `default`
 - [x] Operating system: `Ubuntu 16.04 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It could be that the second producer doesn't have any active connections to the cluster if it has been idling for some time.

**Comment by YarinLowe** [comment]
@edenhill Thanks for your very-quick response.

Is there is any way to hold an active connection to the cluster?
I will explain my aim in the first place - the second producer is a singleton instance which aims to "monitor" the cluster status:
If ALL_BROKERS_DOWN received -> Periodically call metadata() and check if there's any available broker
Otherwise, just wait for ALL_BROKERS_DOWN to be received

If there is any other possible way of implementing this 'monitoring' logic, I will be more than happy to hear it :)

**Comment by edenhill** [comment]
I think that if you reference a topic, by creating a topic object with rd_kafka_topic_new(), the producer will keep a connection open to refresh topic metadata every topic.metadata.refresh.interval.ms

**Comment by YarinLowe** [comment]
@edenhill Seems like it worked.
Thank you so much!
