### ISSUE TITLE
Want to suppress "GSSAPI client step" messages in log

### ISSUE THREAD

**Issue by szalapski** [edenhill/librdkafka#3213]
Description
===========
I am using librdkafka to use the .NET Kafka client to connect to Kafka using SASL.

When it is working well, I get lots of log messages in my console that look like the following.  **How can I suppress these** useless informational log messages?  (I believe it uses Cyrus SASL underneath, right?  Shouldn't librdkafka expose a way to tell cyrus-sasl to turn down its verbosity?  Because there's no way for any consumer of librdkafka to do so.)

```
%5|1610494965.948|LIBSASL|my-service-67c5d5d998-2trdv#consumer-8| [thrd:sasl_ssl://xkafkad13.mydomain.com:9094/3]: sasl_ssl://xkafkad13.mydomain.com:9094/3: GSSAPI client step 2
%5|1610494965.948|LIBSASL|my-service-67c5d5d998-2trdv#consumer-6| [thrd:sasl_ssl://xkafkad13.mydomain.com:9094/3]: sasl_ssl://xkafkad13.mydomain.com:9094/3: GSSAPI client step 1
%5|1610494965.949|LIBSASL|my-service-67c5d5d998-2trdv#consumer-6| [thrd:sasl_ssl://xkafkad13.mydomain.com:9094/3]: sasl_ssl://xkafkad13.mydomain.com:9094/3: GSSAPI client step 2
%5|1610494966.030|LIBSASL|my-service-67c5d5d998-2trdv#consumer-8| [thrd:sasl_ssl://xkafkad11.mydomain.com:9094/1]: sasl_ssl://xkafkad11.mydomain.com:9094/1: GSSAPI client step 1
```

How to reproduce
================
Normal use of the library when consuming via a .NET client using SASL.

Checklist
=========
 - [x] librdkafka version (release number or git tag): `1.5.0`
 - [x] Apache Kafka version: `2.6.0`
 - [x] librdkafka client configuration: see below
 - [x] Operating system: client running on Alpine Linux via docker: `FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka -- see above
 - [x] Provide broker log excerpts - NA, client issue only
 - [x] Critical issue - no

librdkafka is configured via the .NET client as follows:
```c#
            var consumerSettings = new ConsumerConfig()
            {
                BootstrapServers = configuration["Kafka:BrokerList"],
                ClientId = System.Environment.MachineName,
                GroupId = configuration["Kafka:ConsumerGroup"],
                EnableAutoCommit = true,
                EnableAutoOffsetStore = false,
                AutoOffsetReset = AutoOffsetReset.Earliest,
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SaslMechanism = SaslMechanism.Gssapi,
                SaslKerberosServiceName = "Kafka",
                SslCaLocation = "MyCert.pem",
                SaslKerberosKeytab = "/etc/secrets/MID.ktf",
                SaslKerberosPrincipal = kerberosPrincipal
            }
```

**Comment by edenhill** [comment]
There is no option in librdkafka to do that, short of changing the code (see rdkafka_sasl_cyrus.c), I'm not sure why libsasl sometimes emits these things and sometimes don't.

**Comment by szalapski** [comment]
Yes, I'd like to request a code change to allow for suppressing spurious output lines.

**Comment by edenhill** [comment]
You could register a Log delegate and filter out those messages yourself for the time being

**Comment by szalapski** [comment]
Oh, great.  How can I do that from .NET code?

**Comment by edenhill** [comment]
SetLogHandler

**Comment by edenhill** [comment]
These client step messages are now only emitted when debugging is enabled.
