### ISSUE TITLE
Any api in the library to make sure  produce_batch(msgs) sent in just once request in order that msgs are all success or failed.

### ISSUE THREAD

**Issue by lvhuat** [edenhill/librdkafka#3214]
As descripted in title, Have we an api that send wrapped batch msgs in just one request to make sure msg are ether all succeed or all failed,just like implement in kafka-go.

https://github.com/segmentio/kafka-go/blob/64959510dd0326d5b14e53a2eea7d1efc65b321d/conn.go#L1051

I have to do logic for eventsouring output, message produced without lost and I can bear the message re-sent,  and of course, take performace into consideration:

```
msg_list;
msg_len;
while(true) {
    err = produce_batch(msg_list) // fsend(sock,batch_msg_frame(msg_list))
    if (err == -1) {
       for(int i = 0;i < msg_len;i++){
              ( (user_define_struct*)msg->value)->is_retry_msg = 1;
       }
       continue;
    }
   break;
}
```

what i expect(produce without queue):

first time: msg1 msg2 msg3 <- all failed or all success 
retry: msg1' msg2' msg3' <- all failed or all success 

and below is also fine:
first time: msg1(ok) msg2(ok) msg3(fail)  <- no gaps
retry: msg1'(ok) msg2'(ok) msg3'(ok) 

and below is critical:
msg1(ok) msg2(fail) msg3(ok)  msg1'(ok) msg2'(ok) msg3'(ok) 
msg1(unkown) msg2(unkown) msg3(unkown)  msg1'(fail) msg2'(ok) msg3'(ok) 

Please help me.

**Comment by edenhill** [comment]
No, there are no such guarantees.

If you atomic writes you should use the idempotent producer or transactions, the idempotent producer is probably sufficient for your needs and only requires a config setting (enable.idempotence=true).
See https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#idempotent-producer
