### ISSUE TITLE
Question about CentOS EOL

### ISSUE THREAD

**Issue by sungam3r** [edenhill/librdkafka#3216]
Reading https://github.com/edenhill/librdkafka/releases/tag/v1.5.3:

> CentOS 6 is now EOL and is no longer included in binary librdkafka packages,
such as NuGet.

I downloaded librdkafka.redist v1.5.3 nuget package and I still see `centos7-librdkafka.so` file under `runtimes/linux-x64/native`. I don't understand.

**Comment by edenhill** [comment]
CentOS **6** is EOL, we still provide centos**7** builds.

**Comment by sungam3r** [comment]
OK
