### ISSUE TITLE
Multile threads shared one producer

### ISSUE THREAD

**Issue by hchhbbcxl** [edenhill/librdkafka#3222]
multiple threads share one producer ,and the producer bind one topic,
I use the producer in multiple threads like this :
producer.produce(topicA,...)
the other thread :
producer.produce(topicA,...)

is it work fine ?

**Comment by edenhill** [comment]
Yes, that's fine.

**Comment by hchhbbcxl** [comment]
> Yes, that's fine.

multiple threads share one producer,i use the producer like this:
A:
producer.produce(topicA,...)
producer.poll(0)
B:
producer.produce(topicA,...)
producer.poll(0)

they producer different byte message;
kafka will receive some invalid data and some partially modified data.(according to the log before produce,data is OK)

but it is fine to use one thread to produce;
why?

**Comment by hchhbbcxl** [comment]
I know what is wrong, I use share buffer in multiple threads.
