### ISSUE TITLE
What is "assert: rkbuf->rkbuf_rkb"?

### ISSUE THREAD

**Issue by arpitgarg101** [edenhill/librdkafka#3223]
Description
===========
I have got the following message from the consumer I am using.
`*** rdkafka_cgrp.c:882:rd_kafka_group_MemberMetadata_consumer_read: assert: rkbuf->rkbuf_rkb ***`

**This is observed intermittently.**
Sometimes, as soon as the application is started, right after the log line above, the application crashes. And sometimes it is also observed that it is crashing in the middle of the running application with the same error log.

**What is the problem of this failure?**

Error occurs at: (stack trace)
[rdkafka_cgrp.c](https://clickhouse.tech/codebrowser/html_report/ClickHouse/contrib/librdkafka/src/rdkafka_cgrp.c.html#882): Line 882 it calls: 
`rd_kafka_buf_read_str(rkbuf, &Topic);`

[rdkafka_buf.h](https://clickhouse.tech/codebrowser/html_report/ClickHouse/contrib/librdkafka/src/rdkafka_buf.h.html#365):  `rd_kafka_buf_read_str(rkbuf, kstr)` it calls `rd_kafka_buf_read_i16a(rkbuf, (kstr)->len)` at line 367, which internally calls 

[rdkafka_buf.h](https://clickhouse.tech/codebrowser/html_report/ClickHouse/contrib/librdkafka/src/rdkafka_buf.h.html#318): `rd_kafka_buf_read_i16a(rkbuf, dst)` it calls `rd_kafka_buf_read(rkbuf, &_v, 2)` at line 320, which internally calls 

[rdkafka_buf.h](https://clickhouse.tech/codebrowser/html_report/ClickHouse/contrib/librdkafka/src/rdkafka_buf.h.html#256): `rd_kafka_buf_read(rkbuf,dstptr,len)` it calls `rd_kafka_buf_check_len(rkbuf, __len2)` at line 259, which internally calls 

[rdkafka_buf.h](https://clickhouse.tech/codebrowser/html_report/ClickHouse/contrib/librdkafka/src/rdkafka_buf.h.html#223): `rd_kafka_buf_check_len(rkbuf,len)` it calls `rd_kafka_buf_underflow_fail(rkbuf, __len0)` at line 226, which internally calls 

[rdkafka_buf.h](https://clickhouse.tech/codebrowser/html_report/ClickHouse/contrib/librdkafka/src/rdkafka_buf.h.html#186): `rd_kafka_buf_underflow_fail(rkbuf,wantedlen,...)` it calls `rd_kafka_assert(NULL, rkbuf->rkb)` at line 188(This function fails when buffer reading fails due to buffer underflow), which internally calls

[rdkafka_int.h](https://clickhouse.tech/codebrowser/html_report/ClickHouse/contrib/librdkafka/src/rdkafka_int.h.html#61): `rd_kafka_assert(rk, cond)` it calls `rd_kafka_crash(__FILE__,__LINE__, __FUNCTION__, (rk) , "assert: " # cond)` at line 63 (This function asserts the condition if the condition is true it crashes the kafka), which internally calls

[rdkafka.c](https://clickhouse.tech/codebrowser/html_report/ClickHouse/contrib/librdkafka/src/rdkafka.c.html#rd_kafka_crash): `rd_kafka_crash` it logs the error "rdkafka_cgrp.c:882:rd_kafka_group_MemberMetadata_consumer_read: assert: rkbuf->rkbuf_rkb "

![image](https://user-images.githubusercontent.com/26571334/105027015-4168e900-5a75-11eb-9bd9-e8830c95f2dd.png)

Similar GitHub issue:
https://github.com/edenhill/librdkafka/issues/1070

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.5.2`
 - [x] Apache Kafka version: `Azure Event Hubs for Apache Kafka Ecosystems supports Apache Kafka version 1.0 and later.` 
 - [x] librdkafka client configuration: `{
    "auto.commit.interval.ms": 30000,
    "auto.offset.reset": "latest",
    "bootstrap.servers": "CI-cdrin-KAR262269.servicebus.windows.net:9093",
    "enable.auto.commit": true,
    "fetch.message.max.bytes": 20480,
    "fetch.wait.max.ms": 100,
    "group.id": "cdr",
    "heartbeat.interval.ms": 3000,
    "max.poll.interval.ms": 60000,
    "metadata.max.age.ms": 900000,
    "metadata.request.timeout.ms": 30000,
    "queued.max.messages.kbytes": 20480,
    "sasl.mechanisms": "PLAIN",
    "security.protocol": "SASL_SSL",
    "session.timeout.ms": 30000,
    "socket.keepalive.enable": true,
    "socket.timeout.ms": 10000,
    "topic.metadata.refresh.interval.ms": 120000
}`
 - [x] Operating system: Linux with container image alpine:3.11.6
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka: Debug log not available 
 - [ ] Provide broker log excerpts: Since, it is running on Azure cloud, broker logs not available.
 - [x] Critical issue: No

**Comment by edenhill** [comment]
Please fill out the checklist.

**Comment by arpitgarg101** [comment]
> Please fill out the checklist.

Checklist filled.

**Comment by edenhill** [comment]
Thank you, can you reproduce this with `debug=cgrp,protocol`  and provide the logs?

**Comment by deankarn** [comment]
There seems to be a reproducible example found [here](https://github.com/confluentinc/confluent-kafka-go/issues/650#issuecomment-856661159) using two Go clients.

**Comment by alan-delrio** [comment]
This issue is still present for us on linux and windows builds and happens most of the time. We can't simply consume messages few times we have been able to connect
> go1.17.6
> github.com/confluentinc/confluent-kafka-go v1.8.2

**Comment by edenhill** [comment]
This is fixed on master.
We'll release v1.9.0 in a couple of weeks, which includes this fix.
