### ISSUE TITLE
Problem with Kerberos Authentication (Topic not authorized - because a non set principal is used)

### ISSUE THREAD

**Issue by faladu** [edenhill/librdkafka#3224]
I read the FAQ but didn't find this covered.

My problem is that I have an application that writes data to librdkafka using Kerberos.
Authentication is done using a keytab for the kinit command.

The application runs twice using a different keytab each time.
The application reads messages from a database log and applies them to a kafka installation.
As there are two seperate kafka installations each instance of the application writes it to one of them using a keytab for authentication. 

A problem occurs when no messages where sent for a while and then a message is sent again to both.
This leads to one of the application instances using the principal that's in the keytab for the other instance.
This leads to a topic authorization error which makes sense as the prinicipal written in the debug messages isn't authorized as its the principal of the other instance writing to the other kafka.

As that principal was in no data at all used by this instance the suspicion is that the ticket cache is somehow overwritten when this happens and both instances of the application would then try to use the same ticket.

Is there anything I can do to avoid this behaviour?
I tried to find an option to configure where the ticket cache is located and put it into different places for each instance but couldn't find an option like that. (Or an option to use an in memory ticket cache which I didn't see either)

 - [x] librdkafka version (release number or git tag):v1.6.0-RC1

**Comment by faladu** [comment]
I just wanted to add some debug trace:

18.07.24.813250B9628700 Kafka Log Event. Severity: 7 , Buffer :SASL ,fac: [thrd:sasl_plaintext://xxx:9092/boot]: sasl_plaintext://xxx:9092/106: Send SASL Kafka frame to broker (636 bytes)
18.07.24.813312B9628700 Kafka Log Event. Severity: 7 , Buffer :TOPPAR ,fac: [thrd:sasl_plaintext://xxx:9092/boot]: sasl_plaintext://xxx:9092/106: <topicname> [0] 1 message(s) queued but broker not up
18.07.24.813783B9628700 Kafka Log Event. Severity: 7 , Buffer :SASL ,fac: [thrd:sasl_plaintext://xxx:9092/boot]: sasl_plaintext://xxx:9092/106: Received SASL frame from broker (104 bytes)
18.07.24.829493B9628700 Kafka Log Event. Severity: 7 , Buffer :LIBSASL ,fac: [thrd:sasl_plaintext://xxx:9092/boot]: sasl_plaintext://xxx:9092/106: CB_CANON: flags 0x3, "princ@REALM" @ "(null)": returning "princ2"

When it works the 

18.07.24.829493B9628700 Kafka Log Event. Severity: 7 , Buffer :LIBSASL ,fac: [thrd:sasl_plaintext://xxx:9092/boot]: sasl_plaintext://xxx:9092/106: CB_CANON: flags 0x3, "princ2@REALM" @ "(null)": returning "princ"

is

18.07.24.829493B9628700 Kafka Log Event. Severity: 7 , Buffer :LIBSASL ,fac: [thrd:sasl_plaintext://xxx:9092/boot]: sasl_plaintext://xxx:9092/106: CB_CANON: flags 0x3, "princ@REALM" @ "(null)": returning "princ"

so the principal named after the 'returning' is the correct one and the one handed to the librdkafka.
The principal in the princ@REALM is the wrong one from time to time (princ2 is the principal of the other instance of the application that is running)

I hope this helps to clarify the problem.
Is there anything i can do to prevent librdkafka from using princ2@realm instead of princ@realm in these instances?

**Comment by edenhill** [comment]
librdkafka simply uses the principal configured with `sasl.kerberos.principal`

**Comment by faladu** [comment]
The problem is that it doesn't in this log, the configured principal is princ@realm but it is using prin2@realm according to the debug log printed by librdkafka.
princ2@realm would be the principal set to be used in the other instance of the program that is running but in this one princ2 is not set anywhere, the set principal is princ which is used for the first 4 occurances of this exchange in the kafka debug trace but in the 5th it prints using the wrong one in the debug log and as it also fails the topic authorization it seems it also used the wrong one.

**Comment by edenhill** [comment]
Sounds like you might be reusing the `conf` object for multiple instances, can you double check?

**Comment by faladu** [comment]
I only ever create the conf at the very start of the program to create the kafka producer and never touch it after that so that should not be possible.

With the two instances I mean that the program writing to kafka is started 2 times (one time for each kafka cluster it writes to)
The conf is created newly inside the program and the parameters are filled then, so it is also not loaded from a file where it might be mixed up.

The reason for starting the program multiple times instead of doing multiple producers in one start is that if one program has troubles and needs to be restarted it doesn't affect the other programs writing to the other kafka clusters (I sadly can't adjust this otherwise I would have tried doing multiple producers and then the mutex locks etc should protect stuff from being overwritten at the wrong time if my suspicion is correct)

**Comment by dearchap** [comment]
@edenhill Is it possible to use librdkafka with different principals for different producers/consumers to different streams?

**Comment by dearchap** [comment]
@faladu I ran into the same problem. Basically the kerberos cache is being overwritten when the second application starts up and so when application 1 goes to read the cache it has principle 2's ticket and thats why it is failing

**Comment by faladu** [comment]
The thing is that it's a client having this problem.
When I try to replicate it in my test enviroment everything works well and it writes using the two different tickets without much of an issue.
So far I was not able to pin point the difference between the enviroments.
And even in their enviroment it works for maybe ~2hours and then after some time it mixes up the tickets.

My hope was to solve it by moving the tickets to an in memory cache but I found no way to do that so I am trying to recreate the problem reliably and then see what I can do to solve it, but I am still not having much luck reproducing it.

**Comment by dearchap** [comment]
@faladu what is the sasl.kerberos.min.time.before.relogin set ? My guess is that once that timer expires and cache is refreshed and sometime when the session is reinitialized the problem happens ?

@edenhill is it possible to pass in krb5 ccache name to the sasl_client somehow ?

**Comment by faladu** [comment]
I idn't change it so it was the default 60000ms and i exceeded one minute multiple times.
I tried between 5 seconds and 1hour time period between the message to recreate the problem.
The customer had it after ~20 min breaks in the messages.

**Comment by edenhill** [comment]
Kerberos is outside my expertise, you will need to play around with krb5 and libsasl2/cyrus-sasl to find a solution.

**Comment by gnlabrie** [comment]
I know the issue is closed. 
However, we had the same problem and we fixed the issue by setting the KRB5CCNAME=FILE:/tmp/krbcc_<appname> for each application before launching the application. In our case, in the systemd service file.
Each instance will then use a different cache file for Kerberos credentials.
Hope it helps.
