### ISSUE TITLE
rd_kafka_message_t offset is off by 1 when publishing?

### ISSUE THREAD

**Issue by winbatch** [edenhill/librdkafka#323]
This number seems to be 1 higher than the actual offset in Kafka. By design?

**Comment by edenhill** [comment]
Are you referring to the produced offset when `produce.offset.report` is enabled?

**Comment by winbatch** [comment]
Yes

**Comment by edenhill** [comment]
Seems to work okay for me:
````
$ echo "Message#1" | ./kafkacat -vvvv -b 0 -P -test -p 0 -X topic.produce.offset.report=true 
% Message delivered to partition 0 (offset 6)

$ echo "Message#2" | ./kafkacat -vvvv -b 0 -P -test -p 0 -X topic.produce.offset.report=true 
% Message delivered to partition 0 (offset 7)


$ ./kafkacat -vvvv -b 0 -P -test -p 0 -X topic.produce.offset.report=true -C -f '%o: %s\n' -c 1 -o 6
6: Message#1

$ ./kafkacat -vvvv -b 0 -P -test -p 0 -X topic.produce.offset.report=true -C -f '%o: %s\n' -c 1 -o 7
7: Message#2

````

**Comment by winbatch** [comment]
Ok. I'll do some more digging.

**Comment by DEvil0000** [comment]
#227 I am pretty sure we see the same bug (or at least one of some)

**Comment by edenhill** [comment]
@DEvil0000 thats a consumer bug though, produce.offset.report is for the producer

**Comment by DEvil0000** [comment]
if it is using the same code for offset handling it might be the same bug - but I don't really know

**Comment by edenhill** [comment]
This could be related to issue #335 which turned out to be a broker bug:
https://issues.apache.org/jira/browse/KAFKA-1255

**Comment by rathdeep** [comment]
Sorry to comment on this. winbatch  did you notice this bug on 0.8.2.1 kafka version. what was the version you were testing against.
