### ISSUE TITLE
rd_kafka_stats_emit_all timer, Topic partition msgs & broker tx no accumulation

### ISSUE THREAD

**Issue by okman1214** [edenhill/librdkafka#324]
Or Where these two parameters be reset

Thank u

**Comment by edenhill** [comment]
Hi,
Im not sure what you mean. Do you want to reset counters to 0? That is not currently possible but you can do delta comparison in your application

**Comment by okman1214** [comment]
The code file rdkafka.c ,function “rd_kafka_stats_emit_all”
this is the statistics timer function
Read the code, i think this counter  "rkb->rkb_c.tx" must be incremental,but this is not the case.
So,i want to know where this counter to be reset.
also the function "rd_kafka_stats_emit_toppar"  the counter "rktp->rktp_c.msgs"

**Comment by edenhill** [comment]
`rkb_c.tx` are the number of buffers transmitted to the broker.
`rktp_c.msgs` are the number of messages consumed for a specific topic+partition.

Neither of these counters are reset to zero. Are you seeing them being reset to zero?

**Comment by okman1214** [comment]
i think rkb_c.tx is the number of transmitted to the broker. it isn't the buffers counter?

I found those counter are not cumulative that every time the statistic timer 's results, in fact, as image

![image](https://cloud.githubusercontent.com/assets/7188300/8514442/3da8893c-23c2-11e5-8a98-d174181241da.png)

thx for your help

**Comment by okman1214** [comment]
I wonder whether values of rkb_c.tx and rktp_c.msgs are temporary and where to be reset.
I set timer interval of monitor to 5 minutes (statistics.interval.ms) and in each result the two values do not aggregate.
thx u for help

**Comment by edenhill** [comment]
`rkb_c.tx` is a true accumulative counter of the number of buffers sent to the broker.
`rktp_c.msgs` is also such a counter of the number of messages either produced or consumed for that partition.

Is it possible that your graphing tool translates the COUNTER to a rate?

**Comment by okman1214** [comment]
yes it's the bug of our tool ,thank you very much!
