### ISSUE TITLE
"Group authorization failed" error not occurring when re-subscribed

### ISSUE THREAD

**Issue by dshivashankar1994** [edenhill/librdkafka#3244]
Description
===========
When subscribed to a set of topics and if the group authorization fails, the error is thrown. If I use the same kafka_consumer to unsubscribe and subscribe to the same set of topics with same conf, the error is not observed.

Rather we get an unauthorized error during the topic metadata refresh

How to reproduce
================
Did the below change with the rdkafka example code
```
diff --git a/examples/rdkafka_complex_consumer_example.cpp b/examples/rdkafka_complex_consumer_example.cpp
index 220f3d91..1dc309cb 100644
--- a/examples/rdkafka_complex_consumer_example.cpp
+++ b/examples/rdkafka_complex_consumer_example.cpp
@@ -466,6 +466,31 @@ int main (int argc, char **argv) {
     delete msg;
   }
 
+  /*
+   * Subscribe to topics
+   */
+  std::cerr << "UnSubscribing\n";
+
+  err = consumer->unsubscribe();
+
+  /*
+   * Subscribe to topics
+   */
+  std::cerr << "Subscribing";
+
+  err = consumer->subscribe(topics);
+  run = 1;
+
+  /*
+   * Consume messages
+   */
+  while (run) {
+    RdKafka::Message *msg = consumer->consume(1000);
+    msg_consume(msg, NULL);
+    delete msg;
+  }
+
+
 #ifndef _WIN32
   alarm(10);
 #endif
```

Output:
```
examples/rdkafka_complex_consumer_example_cpp -b kafka.bootstrap.servers=mwkafka-prod-01.nyc.firm.com:9092,mwkafka-prod-02.nyc.firm.com:9092,mwkafka-prod-01.dr.firm.com:9092,mwkafka-prod-02.dr.firm.com:9092,mwkafka-prod-01.tbd.firm.com:9092,mwkafka-prod-02.tbd.firm.com:9092 -g aaafps.new_cons_gp -X security.protocol=SASL_PLAINTEXT -X sasl.kerberos.service.name=kafka -X sasl.mechanism=GSSAPI -X sasl.kerberos.kinit.cmd='skinit --force' -X client.id=aaafps.cppcon  aaafps.dhamodha.test-n-9
dhamodha acquired ticket: client dhamodha/hostbased@UNIX.firm.COM, server krbtgt/UNIX.firm.COM@UNIX.firm.COM
% Created consumer aaafps.cppcon#consumer-1
Consume failed: FindCoordinator response error: Group authorization failed.
UnSubscribing
Subscribingdhamodha acquired ticket: client dhamodha/hostbased@UNIX.DESfirmAW.COM, server krbtgt/UNIX.firm.COM@UNIX.firm.COM
dhamodha acquired ticket: client dhamodha/hostbased@UNIX.firm.COM, server krbtgt/UNIX.firm.COM@UNIX.firm.COM
dhamodha acquired ticket: client dhamodha/hostbased@UNIX.firm.COM, server krbtgt/UNIX.firm.COM@UNIX.firm.COM
dhamodha acquired ticket: client dhamodha/hostbased@UNIX.firm.COM, server krbtgt/UNIX.firm.COM@UNIX.firm.COM
Consume failed: Subscribed topic not available: aaafps.dhamodha.test-n-9: Broker: Topic authorization failed
% Consumed 0 messages (0 bytes)
```

- Tried with latest version and still the same behavior

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [x] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by dshivashankar1994** [comment]
Any update here ?

**Comment by dshivashankar1994** [comment]
Any updates here ?

**Comment by edenhill** [comment]
The FindCoordinator request is issued on client instantiation and that's the Group auth .. error you are seeing, it is unrelated to subscribe(), so re-subscribing() does not really re-trigger that error.

Your application should probably treat the group auth error as a fatal error and terminate.

**Comment by dshivashankar1994** [comment]
That explains, Thanks!
