### ISSUE TITLE
kafka consumer session timeout

### ISSUE THREAD

**Issue by vasundhara785** [edenhill/librdkafka#3253]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
The issue is occurring transiently with the error 

%4|1612579319.971|SESSTMOUT|rdkafka#consumer-1| [thrd:main]: Consumer group session timed out (in join-state started) after 30089 ms without a successful response from the group coordinator (broker 0, last error was **Local: Broker transport failure**): revoking assignment and rejoining group.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
librdkafka go-client :1.5.2
consumer config:
			"auto.offset.reset": "latest",
			"enable.auto.offset.store": "true",
			"enable.auto.commit": true,
			"socket.keepalive.enable": "true",
			"metadata.max.age.ms": "900000",
			"metadata.request.timeout.ms": "30000",
			"topic.metadata.refresh.interval.ms": "120000",
			"socket.timeout.ms": "10000",
			"session.timeout.ms": "30000",
			"max.poll.interval.ms": "60000",
			"queued.max.messages.kbytes": "20480",
			"fetch.message.max.bytes": "20480",
			"fetch.wait.max.ms": "100",
			"heartbeat.interval.ms": "3000"

**Comment by edenhill** [comment]
Try to reproduce with `"debug": "cgrp,protocol"`
