### ISSUE TITLE
Topic gets deleted and re-created missing some messages

### ISSUE THREAD

**Issue by dshivashankar1994** [edenhill/librdkafka#3255]
This is a continuation of https://github.com/edenhill/librdkafka/issues/2963. 

When the consumer is subscribed to a topic and the topic gets deleted and re-created while the consumer is subscribed then it misses few messages if the producer continuously produces messages onto the topic

How to reproduce
================
Reproducible with version 1.6.0

- Start consumer with topic T subscribed
- Delete T while Producer continuously produces messages
- Consumer will not receive all the messages

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by dshivashankar1994** [comment]
Any updates here ?

**Comment by dshivashankar1994** [comment]
Any updates here ?

**Comment by edenhill** [comment]
There's currently no way for a consumer to reliable detect that a topic is re-created.
I believe there's a KIP to improve this by using unique topic ids under the hood.

**Comment by dshivashankar1994** [comment]
Hi, could you point me the KIP for reference

**Comment by dshivashankar1994** [comment]
Hi, please provide the KIP for my reference. We should be good to suspend this issue

**Comment by edenhill** [comment]
https://cwiki.apache.org/confluence/display/KAFKA/KIP-516%3A+Topic+Identifiers

**Comment by dshivashankar1994** [comment]
Thanks
