### ISSUE TITLE
Can't complete test 0105_transactions_mock

### ISSUE THREAD

**Issue by AlexeiBaranov** [edenhill/librdkafka#3262]
Description
===========
When testing changes by my pull request, travis often raises an error in the test 0105_transactions_mock. The same issue can be observed in tests for other pull requests:
```
### Test "0105_transactions_mock (do_test_txn_endtxn_errors:406)" failed at 0105-transactions_mock.c:529:do_test_txn_endtxn_errors() at Wed Feb 10 21:38:46 2021: ###

Test assertion failed: "scenario[i].exp_err == rd_kafka_error_code(error)": Scenario #7: expected _FENCED, not _TIMED_OUT
```
It looks like this is a common problem for all pull requests based on the current master. Sometimes this test passes without errors, or fails on a different travis configuration(s). 

How to reproduce
================
For examples, please have a look at:
https://travis-ci.org/github/edenhill/librdkafka/jobs/758398587
https://travis-ci.org/github/edenhill/librdkafka/jobs/758809876
https://travis-ci.org/github/edenhill/librdkafka/jobs/756747315
etc

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.6.0`
 - [х] Apache Kafka version: `2.4.0.0`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [х] Provide logs (with `debug=..` as necessary) from librdkafka - see links above
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please try on latest master and reopen if still an isssue.
