### ISSUE TITLE
Persist pending retries to disk to avoid loosing them after a restart

### ISSUE THREAD

**Issue by Pierre48** [edenhill/librdkafka#3266]
Hi!
I'm using librd kafka since few month, mainly with the dotnet implementation. Thanks for the jobs, It's perfect.

I have just a question about retries. I have understood that it is stored in an internal partition queue. 
I guess this queue is only in memory ? to be clear, if my service is restarted while  reties are pending, unsend event are all lost ?
Sad news ... I tried and it seems yes .

Is there a start of discussion to persist retries on disk : 
  - Avoid to loose message when retries are pending
  - Retries at startup where events was not send

Thanks in advance.

**Comment by edenhill** [comment]
You are correct in that the message queues are in volatile memory only.

What you can do is write the message to a disk spool before calling produce() and later removing the message from the spool on successful delivery.

**Comment by Pierre48** [comment]
Thanks endenhill. I will do that for this use case.
