### ISSUE TITLE
PROTOERR message from librdkafka current version

### ISSUE THREAD

**Issue by murugesan70** [edenhill/librdkafka#3268]
Description
===========
We are using librdkafka 1.6.0, kafka broker version: 1.1.0 and we are seeing this PROTOERR. Is this actually harmful from librdkafka perspective or is it benign on the usage?

==========
Logs from librdkafka:
librdkafka - librdkafka: PROTOERR [thrd:ip:9092/3]: ip:9092/3: Protocol parse failure for ApiVersion v3(flex) at 3/6 (rd_kafka_handle_ApiVersion:2118) (incorrect broker.version.fallback?)
librdkafka - librdkafka: PROTOERR [thrd:broker:9092/2]: broker:9092/2: ApiArrayCnt -1 out of range

Please provide the following information:
 - [x] librdkafka version (release number or git tag): `v1.6.0`
 - [x] Apache Kafka version: `1.1.0`
 - [x] librdkafka client configuration: `api.version.request= true, enable.partition.eof=false,session.timeout.ms=6000,enable.auto.commit=true,auto.commit.interval.ms=5000,enable.auto.offset.store=false`
 - [x] Operating system: `Ubuntu 18.04`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka `debug=consumer`
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I belive that's a debug log that can be ignored, do you have any debugging enabled?

**Comment by murugesan70** [comment]
we had debug=consumer enabled, but I will close this as not an issue
