### ISSUE TITLE
 Produce failed: Local: Unknown partition

### ISSUE THREAD

**Issue by Eric-918** [edenhill/librdkafka#327]
Hi,Magnus
when I use C++ API to do a test about producer and consumer,if i set 
partition = RdKafka::Topic::PARTITION_UA;

producer works well ,and I run 
./bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic testTopic1 --from-beginning 
 consumer works well too.
my own consumer ( code split from rdkafka_example.cpp ) can get nothing (partition = RdKafka::Topic::PARTITION_UA;).
I want to know why should put an arg in consumer->start(topic, partition, start_offset),how can i know which partition the topic is in .

but when I set
partition = 1;
in producer ,the error appears .

% Created producer 123#producer-0
create topic :testTopic2
safl;g
% Produce failed: Local: Unknown partition
sdl;sfdjglk;fs
% Produce failed: Local: Unknown partition
^C

long for your answer. 
Thx

**Comment by DEvil0000** [comment]
does your topic only have one partition? check Kafka and increase the partition count for this topic to at least 2. otherwise your test makes not much sense.

`PARTITION_UA` means auto assign to a partition based on partitioner algorithm and the given key.
trying to consume from `PARTITION_UA` makes no sense - I am not sure if it is even valid.

**Comment by Eric-918** [comment]
yes ,I tried set partition 2 or 4 ,the problem still exists.console log like this:
[eric@localhost build]$ ./kafkaExample -P -t test -p 4 -b localhost:9092
% Type stuff and hit enter to send
1
% Failed to produce to topic test partition 4: Local: Unknown partition
2
% Failed to produce to topic test partition 4: Local: Unknown partition
3
% Failed to produce to topic test partition 4: Local: Unknown partition
4
% Failed to produce to topic test partition 4: Local: Unknown partition
5
% Failed to produce to topic test partition 4: Local: Unknown partition
^C[eric@localhost build]$ ./kafkaExample -P -t test -b localhost:9092
% Type stuff and hit enter to send
1
% Sent 1 bytes to topic test partition -1
2
% Sent 1 bytes to topic test partition -1
% Message delivered (1 bytes)
3
% Sent 1 bytes to topic test partition -1
45^H
% Sent 3 bytes to topic test partition -1
% Message delivered (1 bytes)
% Message delivered (1 bytes)
6
% Sent 1 bytes to topic test partition -1
% Message delivered (3 bytes)
7
% Sent 1 bytes to topic test partition -1
8
% Sent 1 bytes to topic test partition -1
% Message delivered (1 bytes)
% Message delivered (1 bytes)
^C% Message delivered (1 bytes)




And I want to know ,why a consumer need to know a partition num when it start.and how can I know the partition if producer use PARTITION_UA ?

**Comment by Eric-918** [comment]
who can tell me ,why the unknown partition error occurs when partition is set any value except  PARTITION_UA .
crazy !

**Comment by edenhill** [comment]
If you create a topic with 4 partitions then those partitions are numbered 0..3,
you seem to try to consume partition 4 which is indeed an Unknown partition.

You can verify the partition numbers by fetching metadata, e.g.:
`rdkafka_example -L -b mybroker -t mytopic`

librdkafka does not directly support consuming from all partitions of a topic automatically,
you will need to call consume_start() on each partition you wish to consume.
To find out the number of available partitions you use the `rd_kafka_metadata()` API.
kafkacat is an example how to achieve this:

https://github.com/edenhill/kafkacat/blob/master/kafkacat.c#L439
https://github.com/edenhill/kafkacat/blob/master/kafkacat.c#L473

**Comment by Eric-918** [comment]
a lot of thanks, Magnus. I know how to get partition number for consumer.
but the first question , in producer mode ,why I set partition a fixed number (2 ,4,6 ) ,it shows that Unknown partition. did I miss something important ? is the producer who decide how many partitions a topic has ? 

unknown partition error as follow.
[eric@localhost build]$ ./rkExample -P -t test -p 2 -b localhost:9092
% Created producer rdkafka#producer-0
ks
% Produce failed: Local: Unknown partition
kjg
% Produce failed: Local: Unknown partition
kd
% Produce failed: Local: Unknown partition
kd
% Produce failed: Local: Unknown partition

**Comment by edenhill** [comment]
Can you provide the output of `rdkafka_example -L -t test -b localhost:9092` ?

**Comment by Eric-918** [comment]
./kafkaExample -L -t test -b localhost:9092
Metadata for test (from broker -1: localhost:9092/bootstrap):
 1 brokers:
  broker 0 at localhost:9092
 1 topics:
  topic "test" with 1 partitions:
    partition 0, leader 0, replicas: 0, isrs: 0

**Comment by edenhill** [comment]
That means topic `test`only has 1 partition: 0.

If you want to produce to that partition you can either specify it explicitly (e.g `.. -p 0`)
or let the partitioner select it automatically (since there is only one partition all messages will go to that partition).

If you want to consume the topic you will need to specify the partition id too (`.. -p 0`)

**Comment by Eric-918** [comment]
get it ,thanks a lot.

**Comment by DEvil0000** [comment]
you have to configure/create and manage your partitions in kafka not rdkafka.
there are command line tools for this - see kafka docu.
also take a look at kafka config
