### ISSUE TITLE
Kafka Requests Timeout 

### ISSUE THREAD

**Issue by vyjayanthi-sys** [edenhill/librdkafka#3270]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Observing huge latency in producing the messages , when there is a sudden spike in traffic .Below are the errors.

%3|1613536501.674|FAIL|rdkafka#producer-3| [thrd:sasl_ssl://SI-egress-Tel-AIR700071.servicebus.windows.net:9093/]: sasl_ssl://SI-egress-Tel-AIR700071.servicebus.windows.net:9093/0: 1 request(s) timed out: disconnect (after 42161139ms in state UP, 1 identical error(s) suppressed) 

%5|1613536501.674|REQTMOUT|rdkafka#producer-3| [thrd:sasl_ssl://SI-egress-Tel-AIR700071.servicebus.windows.net:9093/]: sasl_ssl://SI-egress-Tel-AIR700071.servicebus.windows.net:9093/0: Timed out ProduceRequest in flight (after 435ms, timeout #0) e

![image](https://user-images.githubusercontent.com/78948015/108311814-ad0cb600-71db-11eb-8764-7ca67703d9ed.png)

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<librdkafka go-client :1.5.2">`
 - [ ] librdkafka producer configuration: `< "go.events.channel.size": 400,
    "go.produce.channel.size": 400,
    "socket.keepalive.enable": true,
    "metadata.max.age.ms": "900000",
    "metadata.request.timeout.ms": "30000",
    "topic.metadata.refresh.interval.ms": "120000",
    "retries": "1000000",
    "message.timeout.ms": "300000",
    "socket.timeout.ms": "10000",
    "max.in.flight.requests.per.connection": "5",
    "enable.idempotence": true
>`

**Comment by edenhill** [comment]
There's an upcoming 1.9.0 release with a bunch of producer queue improvements, try it out and reopen if this is still an issue.
