### ISSUE TITLE
librdkafka does not compile cleanly on AIX (using gcc/g++)

### ISSUE THREAD

**Issue by shalstea** [edenhill/librdkafka#328]
I have patches for this but am waiting for fixes to the dev branch.  On the dev branch the current code does not compile cleanly with older versions of gcc / the linux OS.

**Comment by edenhill** [comment]
Which is issue #319

**Comment by shalstea** [comment]
I am struggling to figure out the best way to do this.  I have made code changes to port the library to AIX (in the dev branch) however the mklove build tool needs work for both AIX and Solaris and I have had to hack around this for now.  The solaris build crashes in the tests and I haven't tried to even build/link on AIX since the solaris executables don't work.

would you be open to me:
1. Submit the current changes for AIX - which are modest... knowing that it isn't complete
2. Providing a list of suggested compiler/linker options to mklove that you would need to integrate

-- when you have done #1 and #2 above I would clone the dev branch and try building testing again

**Comment by edenhill** [comment]
Absolutely, that sounds like a good plan.
Go ahead and submit some PRs for your work.

Big thanks for your effort!

**Comment by edenhill** [comment]
@shalstea What's the status on this?

**Comment by shalstea** [comment]
It now compiles cleanly (in dev branch).  You can close this.

**Comment by edenhill** [comment]
awesome, thanks
