### ISSUE TITLE
Expose connections.max.idle.ms as Consumer and Producer Configuration

### ISSUE THREAD

**Issue by cdemi** [edenhill/librdkafka#3280]
Hi all,

According to the [Confluent Consumer Configuration Docs](https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#consumerconfigs_connections.max.idle.ms), `connections.max.idle.ms` should be available as a consumer and producer configuration.

As far as I can find in the source code and in the librdkafka's CONFIGURATION.md, this library does not expose `connections.max.idle.ms` for producer and consumers. I know that this configuration can also be set on the broker, however it is not always possible to set this on the broker.

For example, let's say that a Kafka Broker is setup on-premises with a `connections.max.idle.ms` of 45 minutes. A third-party client which we have no control over is on Azure so the Azure Firewall is considering the connection idle after 4 minutes. In essence, unless all Kafka consumers and producers live in a network that is under your control, there is no way to have a common value on the broker, or otherwise the `connections.max.idle.ms` would be set to a really low value to accomodate all posible client configurations.

In order to solve this, I think `connections.max.idle.ms` should be exposed for producers and consumers. This way, clients can specify what they consider their ideal idle timeout if it is lower from the broker, thus it would be on a per-connection basis. 

In turn, I would like to include this in confluentinc/confluent-kafka-dotnet#1544 for use in our applications. 

What are your thoughts?

**Comment by edenhill** [comment]
Yeah I think it makes sense to add `connections.max.idle.ms`, but I'm a bit avert to having it enabled by default (especially with the 9 minute Java default) since that will affect existing users in stable environments with long time idle connections.

**Comment by cdemi** [comment]
I agree it shouldn't break backwards compatibility. I wonder, though, if, without this setting they are having adverse affects. As far as I know, by default, Firewalls have relatively short idle timeouts

**Comment by edenhill** [comment]
On-prem installations may not have firewalls or load balancers and their networks are at least in theory more reliable than the cloud counterparts - these are the users I'm mostly concerned with when it comes to changing this default.

**Comment by edenhill** [comment]
Done
