### ISSUE TITLE
rd_kafka_consume_start（）   can't  not work when called  multiple times？

### ISSUE THREAD

**Issue by beitiandijun** [edenhill/librdkafka#329]
in  rdkafka.h：
 * `rd_kafka_consume_start()` must not be called multiple times for the same
 * topic and partition without stopping consumption first with
 * `rd_kafka_consume_stop()`.

so can I call rd_kafka_consume_start()  multiple times for the same topic partition  after rd_kafka_consume_stop()

call rd_kafka_consume_start()   for the same topic and partition like this：
rd_kafka_consume_start();       // 1st time start
...other codes                            //   can work
rd_kafka_consume_stop();       // 1st time stop
rd_kafka_consume_start();       //  2nd time start
..other codes                             // but consume not from the 2nd start offset 

why?

**Comment by edenhill** [comment]
Restarting a consumer too quickly may lead to these problems, that is a known issue which is soon fixed.
See issue #227
