### ISSUE TITLE
why RdKafka::Consumer cannot get EVENT_STATS

### ISSUE THREAD

**Issue by linus-lc** [edenhill/librdkafka#3291]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
i try to register event_cb by follow code

     if (conf->set("event_cb", mEventCb, errMsg) != RdKafka::Conf::CONF_OK)
      {
            std::cerr << errMsg << std::endl;
            exit(1);
        }

        if (conf->set("statistics.interval.ms", ToString(mReportIntervalMs), errMsg) != RdKafka::Conf::CONF_OK)
        {
            std::cerr << errMsg << std::endl;
            exit(1);
        }
        
       RdKafka::Consumer* consumer = RdKafka::Consumer::create(conf, errMsg);

but i cannot recive EVENT_STATS. if i use this conf to create RdKafka::Producer, it can get EVENT_STATS successful.

**Comment by edenhill** [comment]
How are you consuming messages/polling?

**Comment by linus-lc** [comment]
> How are you consuming messages/polling?

i tried both  consume_callback  and consume，it cann't work.

**Comment by linus-lc** [comment]
Is it supported by RdKafka::KafkaConsumer, but not supported by RdKafka::Consumer ？

**Comment by edenhill** [comment]
The legacy RdKafka::Consumer has one queue per partition by default, which you poll with consume(), but the stats events are emitted on the main queue that you need to poll separately with poll().
Recommend instead that you use the KafkaConsumer that combines all partition queues and the main queue in a single consume()
