### ISSUE TITLE
ERROR: "Local: Broker transport failure"

### ISSUE THREAD

**Issue by tolgaakkapulu** [edenhill/librdkafka#3292]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi @edenhill

3 Kafka brokers communicate over SSL. When trying to connect to brokers with librdkafka via .NET Client, the following error is received. When the opened records regarding this were checked, no solution was obtained.

**_ERROR: "Local: Broker transport failure"_**

Do you have any solution suggestions for this issue?

Kafka Brokers can communicate with each other properly and with Kafka Tool, a seamless connection is provided over SSL. 

**Kafka Configs**
```
listeners = SSL://localhost: {port}
port = {port}
security.inter.broker.protocol = SSL
ssl.client.auth = none
ssl.key.password = {PASSWORD}
ssl.keystore.location = /etc/kafka/certs/kafka.server.keystore.jks
ssl.keystore.password = {PASSWORD}
ssl.truststore.location = /etc/kafka/certs/kafka.server.truststore.jks
ssl.truststore.password = {PASSWORD}
```

**.NET Client Config**
```
var mutualAuthConfig = new Dictionary <string, object>
{
    {"bootstrap.servers", "{server_hostnames}: {port}"},
    {"security.protocol", "SSL"},
    {"ssl.ca.location", "/path/to/caroot/file/ca-cert"}
};
```

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.3.0
 - [x] Apache Kafka version: 1.0.0.3.1
 - [x] librdkafka client configuration: ' bootstrap.servers="{server_hostnames}:{port}", security.protocol="SSL", ssl.ca.location="/path/to/caroot/file/ca-cert" '
 - [x] Operating system: Ubuntu 18.04
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
That seems to be only part of the error message, in fact only the error code itself, there should also be a more verbose error string or log message saying what is wrong.

But typically when this happens it is because you are connecting to the incorrect listener/port on the broker, one which does not match the security.protocol.

Troubleshoot further with `Debug: "secury,broker"` on the client.

**Comment by tolgaakkapulu** [comment]
Problem solved. Thank you for your return.

**Comment by MelanieGravel** [comment]
@tolgaakkapulu Can you share your solution?

**Comment by tolgaakkapulu** [comment]
**Hi Melanie,**

The error in my environment was that the compiled **librdkafka** packages were compiled as a result of their incomplete **dependencies**.

For this reason, you can check the compiled **librdkafka** packages for an erroneous output with the command below.

**Sample output is as follows:** 

_**ldd /usr/lib/librdkafka***_
```
/usr/lib/librdkafka++.a:
	not a dynamic executable
/usr/lib/librdkafka.a:
	not a dynamic executable
/usr/lib/librdkafka++.so:
	linux-vdso.so.1 (0x00007fff5e10c000)
	librdkafka.so.1 => /usr/lib/librdkafka.so.1 (0x00007f68e43ea000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f68e4061000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f68e4046000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f68e3e54000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f68e3e31000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f68e3e26000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f68e3e1e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f68e48f1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f68e3ccf000)
/usr/lib/librdkafka.so:
	linux-vdso.so.1 (0x00007ffdd63ef000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd60276e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd602763000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd60275d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd60256b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd602a79000)
/usr/lib/librdkafka++.so.1:
	linux-vdso.so.1 (0x00007ffd7a3e7000)
	librdkafka.so.1 => /usr/lib/librdkafka.so.1 (0x00007f575edbc000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f575ea33000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f575ea18000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f575e826000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f575e803000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f575e7f8000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f575e7f0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f575f2c3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f575e6a1000)
/usr/lib/librdkafka.so.1:
	linux-vdso.so.1 (0x00007ffd5a5c5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f652c21f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f652c214000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f652c20e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f652c01c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f652c52a000)

```
