### ISSUE TITLE
offsetsForTimes fails with 'Local: Unknown partition'

### ISSUE THREAD

**Issue by YarinLowe** [edenhill/librdkafka#3295]
Description
===========
Hi,
I've recently upgraded librdkafka from v1.5.2 to v1.6.1.
The upgrade caused a certain system-test which starts consuming a topic from a certain timestamp (using `offsetsForTimes()`) to fail.
**The failure is deterministic on v1.6.1 (always happens) and does NOT occur on v1.5.2.**

Unfortunately, I won't be able to attach logs because of technical limitations, but I will try to summarize it.
When calling offsetsForTimes, the following lines are logged:
```
Sent FindCoordinatorRequest (v2, CorrId 3)
Received MetadataResponse (v4, CorrId 2)
=== Received Metadata (for 1 requested topics): connected ===
ClusterId: ... ControllerId: 1
3 brokers, 1 topics'. INT: 0
Broker #0/3: ... INT: 0
Broker #1/3: ... INT: 0
Broker #2/3: ... INT: 0
Topics #0/1: CORRECT_AND_EXACT_TOPIC_NAME with 1 partitions'. INT: 0
1/1 requested topic(s) seen in metadata'. INT: 0
```

How to reproduce
================
1. Create a topic with a single partition and produce messages to it.
2. Configure a consumer
3. Convert a timestamp of between the messages into an offset using `offsetsForTimes` (using the correct and exact topic name + partition 0)
4. `offsetsForTimes` fails and returns an error code of 'Local: Unknown partition'

Checklist
=========
 - [x] librdkafka version (release number or git tag): `v1.6.1`
 - [x] Apache Kafka version: `2.13-2.7.0`
 - [x] Operating system: `linux (Ubuntu 16.04)`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Critical issue
 - [ ] Provide broker log excerpts
 - [ ] librdkafka client configuration: ``

**Comment by edenhill** [comment]
This is fixed and will be available in the upcoming 1.7.0 release (a month or so away).
https://github.com/edenhill/librdkafka/pull/3287
