### ISSUE TITLE
Transaction timeout can lead to non-recoverable INVALID_TXN_STATE error

### ISSUE THREAD

**Issue by tgnm** [edenhill/librdkafka#3297]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
After loss of connectivity, a transactional producer may reconnect and try to commit a transaction that has timed out.
If a message failed to deliver with `Failed to produce message Local: Message timed out` and we try to commit, an `AbortableError` occurs. However, aborting the transaction leads to an `INVALID_TXN_STATE` error since the transaction isn't open any longer (transaction state goes from `Ongoing`->timeout leads to `CompleteAbort`->`Empty` once producer sends InitProducerId request)

The `AbortableError` is misleading which leads to a non-recoverable/fatal error `INVALID_TXN_STATE`.

We also experienced a variant of this case which happens when a message is successfully delivered but the transaction times out because the producer doesn't commit the transaction in time. This results in a producer fenced error, which is expected but being improved in KIP-588: https://cwiki.apache.org/confluence/display/KAFKA/KIP-588%3A+Allow+producers+to+recover+gracefully+from+transaction+timeouts

How to reproduce
================

1) Have a transaction producer sending messages in a loop, each loop opening and committing a transaction. If an `AbortableError` occurs, try to abort the transaction.
2) Connect through `socat` or similar to occasionally interrupt the connection for a duration longer than `transaction.timeout.ms`
3) See producer trying to handle `AbortableError` by aborting the transaction and failing with `INVALID_TXN_STATE`

librdkafka logs and broker logs here:
https://gist.github.com/tgnm/ce9c50895558898f20cb9725fe3fed2f

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.6.1`
 - [x] Apache Kafka version: `2.7.0`
 - [x] librdkafka client configuration: `transaction.timeout.ms=10000, max.in.flight=5, retries=MAX`
 - [x] Operating system: `Windows`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts

**Comment by edenhill** [comment]
Thank you for a thorough bug report.
This was fixed in #3331 and will be available in the upcoming 1.7.0 release.
