### ISSUE TITLE
Localhost connection refused and Message delivery timeout

### ISSUE THREAD

**Issue by ivoras** [edenhill/librdkafka#3302]
Description
===========

I'm creating a producer, and I'm connecting to Kafka like this:

```
         kafkaProd, err = kafka.NewProducer(&kafka.ConfigMap{
                 "metadata.broker.list": *kafkaServer,
         })
```

I've also tried using the `boostrap.servers` config with same results.

When messages are produced, I'm getting these errors:

```
%3|1616061417.954|FAIL|rdkafka#producer-1| [thrd:localhost:9092/1]: localhost:9092/1: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 8 identical error(s) suppressed)
```

followed by these, for each message produced:

```
2021/03/18 10:01:33 Delivery failed: mytopic[0]@unset(Local: Message timed out)
```

Which surprises me since there's no `localhost` involved. Kafka is running on a remote server, and I can connect to it on port 9092. 

Could it be that Kafka is misconfigured in some way? Why is my code trying to connect to 127.0.0.1:9092 ?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `librdkafka from confluent-kafka-go@v1.5.2`
 - [x] Apache Kafka version: `2.7.0`
 - [x] librdkafka client configuration: `metadata.broker.list=<hostname>`
 - [x] Operating system: `Ubuntu 18.04.4`

**Comment by edenhill** [comment]
https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by ivoras** [comment]
Thanks!
