### ISSUE TITLE
the producer does not work properly.

### ISSUE THREAD

**Issue by wuweikang** [edenhill/librdkafka#3314]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I worked with the producer in c++ project , after I call the produce method, and poll(0), the callback class method is not called and the message is not sent, any idea on this ?  appreciate your quick reply. Thanks

**Comment by edenhill** [comment]
If you call poll() with a timeout of 0 right after produce() there is very little chance the background threads will have been able to produce the message and receive an ack from the broker yet.

Suggest you use an infinite (-1) timeout or look at the producer examples:
https://github.com/edenhill/librdkafka/blob/master/examples/producer.cpp
