### ISSUE TITLE
How to enable statistics in producer

### ISSUE THREAD

**Issue by laurafbec** [edenhill/librdkafka#3316]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi everyone . I'm starting to use librdkafka to send some logs messages to kafka. To this purpose I've use the example https://github.com/edenhill/librdkafka/blob/master/examples/producer.cpp but I would like to get the librdkafka statistics. I've already added the statistics.interval.ms param in this way

if (conf->set("statistics.interval.ms", "500", errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }

but I don't know what else should I do. Is there any simple example?
Thanks in advance

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You will need to set up an event_cb:
https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.cpp#L453

and handle the EVENT_STATS in that callback:
https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.cpp#L168

**Comment by laurafbec** [comment]
Thanks for the quick solution!!

**Comment by buskuzi** [comment]
@edenhill Hi! is it possible to sample producer statistics for a short session "on the fly" without restarting the producer?
Thinking loud, correct me if im wrong, I understand that I cannot modify _rd_kafka_t_ producer object dynamically in order to turn on and off the stats op, however, using 2 producers with identical settings except what I want to toggle ON & OFF (statistics.interval.ms) would do the job? any potential side effects in mind? 
Thanks!
