### ISSUE TITLE
Enable SSL/TLS in rdkafka producer

### ISSUE THREAD

**Issue by laurafbec** [edenhill/librdkafka#3317]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi everyone, I'm using the producer.cpp example to send a log output to Kafka. I've followed the guide https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka and the next configuration to enable TLS but, since I have done that, no message is delivered, getting the error : "% Failed to produce to topic testTopic2: Local: Queue full". Can anyone help me? Thanks in advance!

 /* Set bootstrap broker(s) as a comma-separated list of host or host:port (default port 9092). */
  if (conf->set("bootstrap.servers", brokers, errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }

 /* Set the Delay in milliseconds to wait for messages in the producer queue to accumulate before constructing message batches (MessageSets) to transmit to brokers.*/
 if (conf->set("linger.ms", "500", errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }

  /* Maximum number of messages allowed on the producer queue. This queue is shared by all topics and partitions. */
 if (conf->set("queue.buffering.max.messages", "500", errstr) != RdKafka::Conf::CONF_OK) {
  //if (conf->set("batch.num.messages", "1000", errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }

 /* Maximum number of messages allowed on the producer queue. This queue is shared by all topics and partitions. */
  if (conf->set("statistics.interval.ms", "500", errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }

/* Set  broker(s) as a comma-separated list of host or host:port (default port 9092). */
  if (conf->set("metadata.broker.list", brokers, errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }

  if (conf->set("security.protocol", "ssl", errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);

if (conf->set("ssl.ca.location", "ca-cert", errstr) != RdKafka::Conf::CONF_OK) {
    std::cerr << errstr << std::endl;
    exit(1);
  }

 if (conf->set("ssl.certificate.location", "client_laura-VirtualBox_client.pem", errstr) != RdKafka::Conf::CONF_OK){
    std::cerr << errstr << std::endl;
    exit(1);
  }

if (conf->set("ssl.key.location", "client_laura-VirtualBox_client.key", errstr) != RdKafka::Conf::CONF_OK){
    std::cerr << errstr << std::endl;
    exit(1);
  }

if (conf->set("ssl.key.password", "abcdefgh", errstr) != RdKafka::Conf::CONF_OK){
    std::cerr << errstr << std::endl;
    exit(1);
  }

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.6.1`
 - [x] Apache Kafka version: `2.7.0`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `Ubuntu 16.04`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Recommend you set `"debug"` config property to `"broker,security"` to get some insight into what is happening under the hood.

Also please fill out the checklist, in particular the librdkafka version.

**Comment by edenhill** [comment]
You should be seeing debug logs on stderr (your EVENT_LOG handler)

**Comment by laurafbec** [comment]
@edenhill I didn't see them because an infinite loop produce by the configuration properties I posted before, but now I get them. I've comment the values related to linger.ms, batch.num.messages and statistics.interval.ms and it seems to be working now, what I dont really understand is why, because I had these properties configured before enabling ssl ¿? Thanks again for you help!!

**Comment by laurafbec** [comment]
Thanks @edenhill !! the problem was related to queue.buffering.max.messages property. Solved!
