### ISSUE TITLE
Consumer fails to commit offset with cooperative-sticky assignment strategy

### ISSUE THREAD

**Issue by dvachaiev** [edenhill/librdkafka#3337]
Description
===========
Consumer fails with the error:
```
failed to commit offset: Broker: Group rebalance in progress
%4|1617810820.630|ASSIGN|rdkafka#consumer-1| [thrd:main]: Group "processor": application *assign() call failed: Changes to the current assignment must be made using incremental_assign() or incremental_unassign() when rebalance protocol type is COOPERATIVE
```

How to reproduce
================
1. Start consumer that explicitly commits offset after receiving each message
2. During active consuming by first consumer start another one in the same consumer group

Checklist
=========
 - [x] librdkafka version (release number or git tag): `1.6.1`
 - [x] Apache Kafka version: `2.12-2.2.0`
 - [x] librdkafka client configuration: `partition.assignment.strategy: cooperative-sticky`
 - [x] Operating system: `MacOS`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Are you using incremental_*assign()? You can't use the atomic *assign() methods with cooperative-sticky

**Comment by dvachaiev** [comment]
My code directly calls neither any *assign() nor incremental_*assign() methods.
It successfully works with the default assignment strategy and fails with provided error with cooperative-sticky strategy. Should it be somehow updated to support this strategy?

**Comment by dvachaiev** [comment]
Moreover, I was able to reproduce the same error with `go.application.rebalance.enable: true` and explicit calls of Consumer.IncrementalAssign and Consumer.IncrementalUnassign methods.

**Comment by dvachaiev** [comment]
My bad, this issue is related to confluent-kafka-go. Created a [new issue](https://github.com/confluentinc/confluent-kafka-go/issues/633) into the right repo.

**Comment by hpk** [comment]
I don't actually believe this is an issue with confluent-kafka-go; it appears to affect confluent-kafka-python as well and is probably a behavior of librdkafka.

I'm testing `confluent-kafka-python==1.7.0` with `cooperative-sticky` and am seeing this issue as well when the consumer attempts to commit offsets during a rebalance.

My understanding of KIP-429 is that if the consumer receives this error, it should try to sync its partition assignment and retry committing offsets for the partitions that are still assigned. With librdkafka and the wrapper libraries, It's not clear if that is left up to the end user or is handled by the libraries.
