### ISSUE TITLE
Nuget package for librdkafka.redis does not contain a debug version. Makes it impossible to use C++ wrappers.

### ISSUE THREAD

**Issue by fquinsol** [edenhill/librdkafka#3338]
Description
===========
Code like the one below fails in DEBUG
The actual value returned by the api is CONF_UNKNOWN
I suspect the issue is because there is no DEBUG version of the librdkafka.redis so we are passing an std::string from a debug heap to a module using a release heap. 

How to reproduce
================
Run the given code from a console app or test project. The assertion will hit.

    std::string error;
    auto config = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
    auto res = config->set("group.id", "foobar", error);
    assert(res == RdKafka::Conf::CONF_OK);

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.61`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `Windows`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Should librdkafka.redist contain debug builds, or should there be a separate librdkafka.redist.debug package? I'd prefer the latter to keep dependent project sizes down.

**Comment by fquinsol** [comment]
The C interface doesn't have the same problem, so this is only necessary on the c++ interface.
On the other hand a header only library for C++ could have been enough, assuming it is only a think wrapper over the c interface.
That is what I will personally do for myself to work around the problem.
BTW I'm truly new to this library so these are only my first off-the-cuff remarks.

**Comment by edenhill** [comment]
Your input is valuable, I don't do development on Windows and am not overly familiar with these types of best practices.

**Comment by edenhill** [comment]
Suggest using the vcpkg of librdkafka instead.
