### ISSUE TITLE
found memory leak.when i set statistics.interval.ms with cpp api

### ISSUE THREAD

**Issue by cryingzl** [edenhill/librdkafka#3341]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
when i set statistics.interval.ms , i found menory leak in func rd_kafka_stats_emit_toppar.
and i found "rko->rko_u.stats.json = NULL; //Application wanted json ptr" in func rd_kafka_poll_cb,
but RdKafka::stats_cb_trampoline didn't call rd_free to release stats.json.

How to reproduce
================
`
conf->set("statistics.interval.ms", "1000", errstr);`
`m_pConsumer = RdKafka::KafkaConsumer::create(conf, errstr);`
`...`
`while(TRUE)`
`{`
`    RdKafka::Message *msg = m_pConsumer->consume(100);`
`    ...`
`    SAFE_DEL(msg);`
`}
`
set statistics.interval.ms and wait

Checklist
=========

 - [x] librdkafka version 1.5.0
 - [x] Apache Kafka version: 1.1.1
 - [x] librdkafka client configuration: "statistics.interval.ms", "1000"

**Comment by edenhill** [comment]
stats_cb_trampoline() returns 0 which leaves rko_u.stats.json intact and it will be freed by op_destroy(), so there shouldn't be a leak there.

**Comment by cryingzl** [comment]
> stats_cb_trampoline() returns 0 which leaves rko_u.stats.json intact and it will be freed by op_destroy(), so there shouldn't be a leak there.
i got it. but my app memory still leak somewhere.
i use pporf to find memory leak. it show me this.
![微信截图_20210408203520](https://user-images.githubusercontent.com/10082367/114027731-45551c00-98aa-11eb-82b6-e79753693372.png)
87% memory is used by rd_kafka_stats_emit_toppar. any idea?

**Comment by edenhill** [comment]
Did you register an EventCb handler? You need to do so to handle the stats anyways.

**Comment by cryingzl** [comment]
> Did you register an EventCb handler? You need to do so to handle the stats anyways.

Yes I did. There have serveral producer and one consumer in my app, I have registed eventcb handler for each of them.
It seems that I may have made some low-level mistakes.But I can't find it.
I'll keep on it and report the result.

**Comment by cryingzl** [comment]
My colleague call my producer class with out register timer to poll eventcb...
(╯‵□′)╯︵┻━┻

**Comment by bababababamu** [comment]
I had the same problem

librdkafka version 2.3.0
Apache Kafka version: 1.1.1
librdkafka client configuration: "statistics.interval.ms", "1000"

> Did you register an EventCb handler? You need to do so to handle the stats anyways.
