### ISSUE TITLE
use `rd_kafka_queue_io_event_enable` to notify consume, got poll interval timeout

### ISSUE THREAD

**Issue by changrui0608** [edenhill/librdkafka#3344]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

I'm trying to use `rd_kafka_queue_io_event_enable` as a notifier to my epoll-based dispatcher, like:
```cpp
  int pipe_fd[2];
  pipe(pipe_fd);

  RdKafka::KafkaConsumer* consumer_ = RdKafka::KafkaConsumer::create(...);
  rd_kafka_t* rk = consumer_->c_ptr();
  rd_kafka_queue_t* queue = rd_kafka_queue_get_consumer(rk);
  rd_kafka_queue_io_event_enable(queue, pipe_fd[1], "\0", 1);
  epoll_ctl(epoll_fd_, op, pipe_fd[0], &ev);
```
then in my app, `KafkaConsumer::consume()` will be called only if there is a message arrived (epoll polled).
If there isn't any messages for like 5 minutes, I get:
```
%4|1618317069.623|MAXPOLL|test_kafka_client_id#consumer-1| [thrd:main]: Application maximum poll interval (300000ms) exceeded by 428ms (adjust max.poll.interval.ms for long-running message processing): leaving group
%4|1618317069.826|COMMITFAIL|test_kafka_client_id#consumer-1| [thrd:main]: Offset commit (unassigned partitions) failed for 2/3 partition(s) in join-state wait-unassign-to-complete: Broker: Unknown member: test[0]@254(Broker: Unknown member), test[1]@194(Broker: Unknown member)
%4|1618317369.831|MAXPOLL|test_kafka_client_id#consumer-1| [thrd:main]: Application maximum poll interval (300000ms) exceeded by 207ms (adjust max.poll.interval.ms for long-running message processing): leaving group
```

The consumer functionalities are working fine before & after these logs.
Should I just set `max.poll.interval.ms` to maximum, or maybe I missed something else?

BTW it will be good to have a C++ version of `rd_kafka_queue_get_consumer`.

How to reproduce
================

-

=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.6.1`
 - [ ] Apache Kafka version: 
 - [x] librdkafka client configuration: almost default
 - [x] Operating system: `Centos 7 (x64)`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Your application still needs to call poll() at least every <max.poll.interval.ms to indicate to the consumer that it is still alive.

**Comment by changrui0608** [comment]
Got it, I will add an extra timer task in my app.
Thanks.

**Comment by elizajeanwong** [comment]
@edenhill Is there some kind of keep-alive functionality we can have so that we don't have to have a timer that periodically calls rd_consumer_poll()?
