### ISSUE TITLE
metadata.request.timeout.ms unused

### ISSUE THREAD

**Issue by dimpavloff** [edenhill/librdkafka#3346]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

Hi, maybe I'm missing some magic but `metadata.request.timeout.ms` is not documented as deprecated and yet searching through the code for usage of `metadata_request_timeout_ms` shows no usage. Experimentally, setting it to 10ms also doesn't seem to make a difference. 

I'd like to know whether this is intentionally the case and if so, what value controls the timeouts for metadata requests. Thanks

How to reproduce
================
 https://github.com/edenhill/librdkafka/search?q=metadata_request_timeout_ms&type=code 

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<b31363fe4362c5c42c6afd551af0cfaa3f69aa86 also 1.6.1>`
 - [ ] Apache Kafka version: `N/A`
 - [ ] librdkafka client configuration: `N/A`
 - [ ] Operating system: `N/A`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks! Turns out this property was never implemented, will hide and mark as deprecated.

**Comment by dimpavloff** [comment]
Thanks for the quick response! In this case, could you please clarify what controls the timeouts on metadata requests? `socket.timeout.ms` or something else?

**Comment by edenhill** [comment]
Yep, socket.timeout.ms.

**Comment by dimpavloff** [comment]
Thanks!
