### ISSUE TITLE
Kafka stucks when try to `SendOffsetsToTransaction`

### ISSUE THREAD

**Issue by stgleb** [edenhill/librdkafka#3348]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

When call to `SendOffsetsToTransaction` is sent librdkafka does not proceed without error and with following internal
log error:

```
%3|1618430548.637|TXNERR|rdkafka#producer-2| [thrd:main]: Current transaction failed: Transactional API operation (commit_transaction (begin)) timed out (_TIMED_OUT)
```

Algorithm:

```
1. consumer reads messages
2. begin tx
3. SendOffsetsToTransaction with consumer current position
4. commit tx or abort in case of failure
```

 - [x] librdkafka version (release number or git tag): `v1.6.1`
 - [x] Apache Kafka version: `12.9.5`
 - [x] Operating system: `k8s`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka

**Comment by edenhill** [comment]
Please reproduce with `debug=eos,broker` and provide the logs.
Also see if you can reproduce this on latest master, we've made additional bug fixes for the txn producer since 1.6.1.

**Comment by stgleb** [comment]
@edenhill Can you explain me please what is eos? I've run producer with log_level 7 and get only the one line from library.

**Comment by rolandyoung** [comment]
Please see here https://github.com/edenhill/librdkafka/wiki/FAQ#logging-and-logs . "with debug=eos,broker" means set the "debug" configuration property to "eos,broker". ("eos" stands for "exactly once semantics".)

**Comment by stgleb** [comment]
I've found a root cause:

```
	err = p.Producer.Produce(msg, deliveryChan)
	if err != nil {
		logging.Warnf("produce error %v", err)
	}
```

This was cause by passing delivery chan and not using it.
