### ISSUE TITLE
Unable to replicate that acks works for given range -1..1000. Producer only working for -1(all), 0 and 1.

### ISSUE THREAD

**Issue by tasneem-hyder** [edenhill/librdkafka#3361]
**Issue:**
Unable to replicate that `acks` works for given range -1..1000. Producer only working for -1(all), 0 and 1

https://github.com/edenhill/librdkafka/blob/f18e273d20b3a25f74a7f178a6a515dd8518c8ed/src/rdkafka_conf.c#L1439-L1455

**Question:**
What are the conditions for setting acks more than 1 ?

**Error:** 
`
KafkaError{code=INVALID_REQUIRED_ACKS,val=21,str="Broker: Invalid required acks value"}
`

**Dependency & config**
Docker image: confluentinc/cp-kafka:5.2.0
Python: confluent-kafka==1.6.1

```
root@broker2:/# kafka-topics --bootstrap-server broker1:19092 --describe --topic hello-producer
Topic:hello-producer    PartitionCount:3        ReplicationFactor:3     Configs:min.insync.replicas=2
        Topic: hello-producer   Partition: 0    Leader: 3       Replicas: 3,1,2 Isr: 3,1,2
        Topic: hello-producer   Partition: 1    Leader: 1       Replicas: 1,2,3 Isr: 1,2,3
        Topic: hello-producer   Partition: 2    Leader: 2       Replicas: 2,3,1 Isr: 2,3,1
```

```python
    producer_config = {'client.id': socket.gethostname(),
                       'bootstrap.servers': 'localhost:9092',
                       'acks': '2'}
```

**Comment by edenhill** [comment]
0, 1 and -1 are the only ones that matter, the remaining range is legacy.

**Comment by tasneem-hyder** [comment]
Thanks for the update.

The librdkafka configuration documentation confused me and I did multiple things to proof that but couldn’t achieve. Are we looking to update it?
