### ISSUE TITLE
Raspbian: System.DllNotFoundException: Failed to load the librdkafka native library

### ISSUE THREAD

**Issue by bgarcia78** [edenhill/librdkafka#3365]
Description
===========

I want to be able to write a message as a producer from a raspberry with the .net core client.

I receive the following error message.

The libraries from librdkafka.redist are not compatible with armhf.

System.DllNotFoundException: Failed to load the librdkafka native library

How to reproduce
================
           var config = new ProducerConfig { BootstrapServers = "192.168.1.36:9092" };

            // If serializers are not specified, default serializers from
            // `Confluent.Kafka.Serializers` will be automatically used where
            // available. Note: by default strings are encoded as UTF8.
            using( var p = new ProducerBuilder<Null, string>( config ).Build( ) )
            {
                try
                {
                    var dr = await p.ProduceAsync( "test", new Message<Null, string> { Value = "test 3" } );
                    Console.WriteLine( $"Delivered '{dr.Value}' to '{dr.TopicPartitionOffset}'" );
                }
                catch( ProduceException<Null, string> exception )
                {
                    Console.WriteLine( $"Delivery failed: {exception.Error.Reason}" );
                }
            }
Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.6.3
 - [ ] Apache Kafka version: 2.8
 - [ ] librdkafka client configuration: 
 - [ ] Operating system: rasbian
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
We don't provide armhf builds of librdkafka at this point, so you will need to install librdkafka through other means, just make sure the librdkafka version is equal or higher than the dotnet client version (e.g., don't attempt to run confluent-kafka-dotnet v1.6.1 with librdkafka v1.5.0).
Building from source might be the easiest alternative unless the Raspbian librdkafka package is up to date, and then install librdkafka with `make install`.

After that the dotnet client should be able to automatically pick up the system-installed librdkafka.
