### ISSUE TITLE
GSSAPI Error:  Miscellaneous failure (AUTH_REQ)

### ISSUE THREAD

**Issue by kan1-git** [edenhill/librdkafka#3371]
Hi, 

confluent-kafka-go v1.6.1

Description
===========

We are trying to connect to Kafka Topics (using Kerberos auth). Sometimes maybe because of machine being idle for long time or VPN reconnecting we are not able to connect to the topics and the Producer/Consumer start throwing these errors : 

 (krbtgt/***) unknown while looking up 'kafka/secured-kafka*****' (cached result, timeout in 920 sec) (negative cache))
********Read message Consumer error: 3/3 brokers are down (<nil>)
%2|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://secured-kafka02*******/bootstrap]: sasl_ssl://secured-kafka02******/bootstrap: GSSAPI Error:  Miscellaneous failure (see text (Server (krbtgt/******) unknown while looking up 'kafka/secured-kafka02.******' (cached result, timeout in 920 sec) (negative cache))
********Read message Consumer error: 3/3 brokers are down (<nil>)
%2|LIBSASL|rdkafka#consumer-1| [thrd:sasl_ssl://secured-kafka01.******/bootstrap]: sasl_ssl://secured-kafka01.******/bootstrap: GSSAPI Error:  Miscellaneous failure (see text (Server (krbtgt/******) unknown while looking up 'kafka/secured-kafka01.******' (cached result, timeout in 920 sec) (negative cache))

How to reproduce
================
This happens sometimes and very intermittent, maybe if the client loses connection and comes back up or stays idle for long time. Something to do with the krbtgt - Kerberos Ticket expiry and not able to renew. Using kdestroy command - it sometimes works after restarting the clients.

Debug logs for Producer : 

ed (start (-1)): SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (Server (krbtgt/xxxxxxxx@US.CORP) unknown while looking up 'kafka/secured-kafka02.xxxxxxxx@xxxxxxxx' (cached result, timeout in 1199 sec)) (after 7ms in state AUTH_REQ) (_AUTHENTICATION)
%3|1619635691.037|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka02.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka02.xxxxxxxx/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (Server (krbtgt/xxxxxxxx@US.CORP) unknown while looking up 'kafka/secured-kafka02.xxxxxxxx@xxxxxxxx' (cached result, timeout in 1199 sec)) (after 7ms in state AUTH_REQ)
%7|1619635691.037|STATE|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka02.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka02.xxxxxxxx/bootstrap: Broker changed state AUTH_REQ -> DOWN
%7|1619635691.037|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka02.xxxxxxxx/bootstrap]: Cluster connection already in progress: broker down
%7|1619635691.037|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (Server (krbtgt/xxxxxxxx@US.CORP) unknown while looking up 'kafka/secured-kafka03.xxxxxxxx@xxxxxxxx' (cached result, timeout in 1199 sec)) (after 5ms in state AUTH_REQ) (_AUTHENTICATION)
%7|1619635691.037|STATE|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka02.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka02.xxxxxxxx/bootstrap: Broker changed state DOWN -> INIT
%7|1619635691.038|STATE|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka02.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka02.xxxxxxxx/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1619635691.038|RECONNECT|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka02.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka02.xxxxxxxx/bootstrap: Delaying next reconnect by 1089ms
%3|1619635691.038|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error:  Miscellaneous failure (see text (Server (krbtgt/xxxxxxxx@US.CORP) unknown while looking up 'kafka/secured-kafka03.xxxxxxxx@xxxxxxxx' (cached result, timeout in 1199 sec)) (after 5ms in state AUTH_REQ)
%7|1619635691.038|STATE|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap: Broker changed state AUTH_REQ -> DOWN
%7|1619635691.038|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap]: Not selecting any broker for cluster connection: still suppressed for 48ms: broker down
%7|1619635691.038|STATE|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap: Broker changed state DOWN -> INIT
%7|1619635691.039|STATE|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1619635691.039|RECONNECT|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka03.xxxxxxxx/bootstrap: Delaying next reconnect by 1020ms
%7|1619635691.080|NOINFO|rdkafka#producer-1| [thrd:main]: Topic development.internal.rewards.benefitsintegration metadata information unknown
%7|1619635691.080|NOINFO|rdkafka#producer-1| [thrd:main]: Topic development.internal.rewards.benefitsintegration partition count is zero: should refresh metadata
%7|1619635691.080|CONNECT|rdkafka#producer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 7ms: refresh unavailable topics
%7|1619635691.080|CONNECT|rdkafka#producer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 7ms: no cluster connection
%7|1619635691.302|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka01.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka01.xxxxxxxx/bootstrap: broker in state TRY_CONNECT connecting
%7|1619635691.302|STATE|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka01.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka01.xxxxxxxx/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1619635691.303|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka01.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka01.xxxxxxxx/bootstrap: Connecting to ipv4#xxxxxxxx (sasl_ssl) with socket 16
%7|1619635691.399|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://secured-kafka01.xxxxxxxx/bootstrap]: sasl_ssl://secured-kafka01.xxxxxxxx/bootstrap: Connected to ipv4#xxxxxxxx

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `librdkafka: stable 1.5.3`
 - [x] Apache Kafka version: `2.7`
 - [x] librdkafka client configuration: `"bootstrap.servers": bootstrapServers,"security.protocol": securityProtocol,"sasl.kerberos.service.name": serviceName,"sasl.kerberos.keytab": keytabFile,"sasl.kerberos.principal": principalName,"ssl.ca.location": certificateLocation`
 - [x] Operating system: `Mac OS x64`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Looks like a Kerberos issue.
