### ISSUE TITLE
Golang Dockerfile with Kerberos error

### ISSUE THREAD

**Issue by kan1-git** [edenhill/librdkafka#3373]
Description
===========
I tried multiple options to have a working Dockerfile with Golang and librdkafka support. 

I am getting following error : 
#13 0.493    44 | #error "confluent-kafka-go requires librdkafka v1.6.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
#

I am not able to find 1.6.0 version for alpine containers. The latest ones are librdkafka=1.5.3-r1 librdkafka-dev=1.5.3-r1

How to reproduce
================

Docker file : 

FROM golang:1.14-alpine AS base
WORKDIR /go/src/test
COPY . .

USER root

RUN apk update && apk --no-cache --update add build-base
RUN apk add librdkafka=1.5.3-r1 librdkafka-dev=1.5.3-r1 pkgconf
RUN go build -tags dynamic -ldflags '-linkmode=external'

FROM alpine:3.7
WORKDIR /usr/bin
COPY --from=base /go/src/test/client .
CMD ["./client"]

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Latest is available in edge:
https://pkgs.alpinelinux.org/package/edge/community/x86/librdkafka-dev

**Comment by Lavjeetk** [comment]
Hey any help from who could successfully built a docker along with GSSAPI/Kerberos support ?

**Comment by kan1-git** [comment]
Hey any help from anyone who could successfully built a docker along with GSSAPI/Kerberos support ?

**Comment by kan1-git** [comment]
@edenhill : 

I have this file now : 

```
FROM alpine:3.8 as builder

USER root

ENV LIBRD_KAFKA_VER=master
RUN apk add --update bash krb5-pkinit krb5-dev krb5 cyrus-sasl-gssapi g++ openssl make curl unzip && rm -rf /var/cache/apk/*
COPY ./librdkafka-${LIBRD_KAFKA_VER}.zip ./librdkafka.zip
RUN unzip librdkafka.zip && \
cd librdkafka-${LIBRD_KAFKA_VER} && ./configure --install-deps && make && make install

RUN apk add --no-cache git make musl-dev go
ENV GOFLAGS -mod=vendor

WORKDIR /go/src/test
COPY . .

USER root
RUN go build -tags dynamic -ldflags '-linkmode=external'

CMD ["./client"]

```

Earlier when I was using LIBRD_KAFKA_VER=1.6.0 I was facing problem : 
```
#11 6.338 # github.com/confluentinc/confluent-kafka-go/kafka
#11 6.338 /usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_txnmgr.o): in function `rd_kafka_txn_set_fatal_error':
#11 6.338 (.text+0x149): undefined reference to `__strdup'
#11 6.338 /usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: vendor/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor/librdkafka_glibc_linux.a(rdkafka_txnmgr.o): in function `rd_kafka_txn_set_abortable_error':
#

```

I changed the Librdkafka to have the latest master. Now I am facing this issue : 
`standard_init_linux.go:219: exec user process caused: exec format error`

I am not sure why this is an issue, my earlier working Dockerfile had same Architecture as the recent one : 
 "Architecture": "amd64"

**Comment by kan1-git** [comment]
@edenhill do you have any inputs ?

**Comment by edenhill** [comment]
Looks like `-tags dynamic` doesn't work.
This is a go issue though, not librdkafka.
