### ISSUE TITLE
support about consumer group

### ISSUE THREAD

**Issue by Eric-918** [edenhill/librdkafka#338]
Hi ,Magnus ,me again.
I want to know do you have plan to support consumer group in librdkafka?

thx.

**Comment by Eric-918** [comment]
why did not librdkafka sent topic and consumer data to zookeeper like quick start of kafka.apache.org does?
http://kafka.apache.org/documentation.html#quickstart

**Comment by edenhill** [comment]
Zookeeper based consumer groups are on the way out in favour of the new broker based consumer groups that will be available with Apache Kafka 0.9.
librdkafka will support the new broker based consumer groups.
If an application needs to support the older zookeeper based consumer groups it can implement that on top of librdkafka and libzookeeper.

**Comment by Eric-918** [comment]
get it ,thx
