### ISSUE TITLE
Docker librdkafka issue

### ISSUE THREAD

**Issue by JJCodeTry** [edenhill/librdkafka#3380]
Description
===========
Trying to use librdkafka along with alpine Docker. It does not work. Followed the steps mentioned here : https://github.com/confluentinc/confluent-kafka-go

How to reproduce
================
Use the following Dockerfile : 

`
FROM amd64/alpine:3.8 as builder
USER root

RUN apk add --no-cache git make go
RUN apk add --no-cache autoconf
RUN apk add --no-cache bash
RUN apk add --no-cache g++
RUN git clone https://github.com/edenhill/librdkafka.git
RUN cd librdkafka && ./configure && make && make install

ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH
ENV GOFLAGS -mod=vendor
ENV GOARCH=amd64 GOOS=linux

WORKDIR /go/src/test
COPY . .
RUN go build -tags dynamic -ldflags '-linkmode=external'

CMD ["./run_test"]`

The error is : "standard_init_linux.go:219: exec user process caused: exec format error"
I have MacOS and architecture of Docker image is same as what I have as host.

Checklist
=========

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by kgns** [comment]
Even though you haven't provided any useful information, you probably have an M1 MacBook which is not based on amd64 but on arm64 instead
