### ISSUE TITLE
Process timeout vs session timeout

### ISSUE THREAD

**Issue by plachor** [edenhill/librdkafka#3381]
Hi, I've just wanted to confirm that heartbeats keeping consumer session alive are send from a dedicated thread not paired in any way with consume/poll. I want to allow maximal `max.poll.interval.ms` and wonder if it can affect in any way heartbeats, or consumer being thrown out of group before he ends processing by client itself. 

I can also imagine that there can be other reasons like rebalance or temporal network partition between consumer and broker. Is there any callback exposed that I could use to notify my long running process and cancel it as it want be able to commit that message anyway and most probably some other instance is already processing it.

Checklist
=========

 - [x] librdkafka version (release number or git tag): `v1.6.1`

**Comment by edenhill** [comment]
Yes, heartbeats are sent in one of librdkafka's background threads as long as the application calls consume/poll() at least every max.poll.interval.ms.

Register a rebalance_cb to be notified of rebalance assign/revokes.

**Comment by plachor** [comment]
Thanks for quick response and clarification.
