### ISSUE TITLE
missing Findlibrdkafka.cmake

### ISSUE THREAD

**Issue by alejandro-colomar** [edenhill/librdkafka#3387]
Description
===========

Can't consume librdkafka from project using `cmake` with `find_package()`.

```
CMake Error at src/xxx/CMakeLists.txt:96 (find_package):
  By not providing "Findlibrdkafka.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "librdkafka", but CMake did not find one.

  Could not find a package configuration file provided by "librdkafka"
  (requested version 1.6.0) with any of the following names:

    librdkafkaConfig.cmake
    librdkafka-config.cmake

  Add the installation prefix of "librdkafka" to CMAKE_PREFIX_PATH or set
  "librdkafka_DIR" to a directory containing one of the above files.  If
  "librdkafka" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

How to reproduce
================
Write in a `CMakeLists.txt` the following line:

```
find_package(librdkafka 1.6.0 REQUIRED)
```

I used version 1.6.0, because it's the latest one provided by conan-center.

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.6.0`
 - [x] Apache Kafka version: `I don't know`
 - [x] librdkafka client configuration: `shared=False, ssl=False`
 - [x] Operating system: `Debian Sid (but the important part here is that I used conan to get it, I guess)`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka `I don't have logs from librdkafka`
 - [x] Provide broker log excerpts `Don't have of these either`
 - [x] Critical issue `It depends on what you consider critical`

**Comment by sadeepwdon** [comment]
I think you need to change `librdkafka` to `RdKafka`

**Comment by alejandro-colomar** [comment]
It works with `RdKafka` but not with `rdkafka` :)

Thank you!

Now I don't know how I didn't see that myself.
