### ISSUE TITLE
Issue while buliding librdkafka in Solaris 11

### ISSUE THREAD

**Issue by chandarkumar7385** [edenhill/librdkafka#3388]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Issue while buliding librdkafka in Solaris 11
Kindly help us in resolving the issue

How to reproduce
================
1. Download the librdkafka
2. Give comment ./configure --install-deps

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `https://github.com/edenhill/librdkafka
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

-------------------------------------------

root@SOL1:~/librdkafka# ./configure --install-deps
using cache file config.cache
checking for OS or distribution... ok (sunos)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... failed (disable)
checking executable strip... ok
checking executable libtool... failed (disable)
checking executable ranlib... ok
checking for pkgconfig (by command)... failed
checking for GNU install... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... failed
checking for Solaris linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x010700ff'... ok (1.7.0)
checking for librt (by compile)... ok
checking for libpthread (by compile)... ok
checking for c11threads (by compile)... ok
checking for libdl (by compile)... ok
checking for zlib (by compile)... ok
checking for libcrypto (by compile)... ok
checking for libssl (by compile)... ok
checking for libsasl2 (by compile)... ok
checking for libzstd (by compile)... failed
building dependency libzstd... failed (disable)
libzstd source build failed, see /root/librdkafka/mklove/deps/src/libzstd/_mkl_install.log for details. Last 50 lines:
### Installing libzstd 1.3.8 from source to /root/librdkafka/mklove/deps/dest/libzstd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   623  100   623    0     0   1393      0 --:--:-- --:--:-- --:--:--  1393
100 1819k  100 1819k    0     0  1336k      0  0:00:01  0:00:01 --:--:-- 6494k
make: Warning: Ignoring DistributedMake -j option
make: Fatal error: Don't know how to make target `install'

real    0m0.392s
user    0m0.005s
sys     0m0.014s
checking for libm (by compile)... ok
checking for liblz4 (by compile)... failed (disable)
checking for syslog (by compile)... ok
checking for rapidjson (by compile)... failed (disable)
checking for crc32chw (by compile)... failed (disable)
checking for regex (by compile)... ok
checking for rand_r (by compile)... ok
checking for strndup (by compile)... ok
checking for strlcpy (by compile)... ok
checking for strerror_r (by compile)... ok
checking for strcasestr (by compile)... ok
checking for pthread_setname_gnu (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for python3 (by command)... ok
checking for getrusage (by compile)... failed (disable)
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  MKL_DISTRO               sunos
  SOLIB_EXT                .so
  ARCH                     i86pc
  CPU                      generic
  GEN_PKG_CONFIG           y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  STRIP                    strip
  RANLIB                   ranlib
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -D__EXTENSIONS__
  PKG_CONFIG               pkg-config
  INSTALL                  ginstall
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,-M
  RDKAFKA_VERSION_STR      1.7.0
  MKL_APP_VERSION          1.7.0
  LIBS                     -lm -lsasl2 -lssl -lcrypto -lcrypto -lz -ldl -lpthread -lrt -lpthread -lrt
  MKL_PKGCONFIG_LIBS_PRIVATE -lm -lsasl2 -lssl -lcrypto -lcrypto -lz -ldl -lpthread -lrt -lpthread -lrt
  CXXFLAGS                 -Wno-non-virtual-dtor
  CFLAGS                   -std=c99
  SYMDUMPER                $(NM) -D
  MKL_DYNAMIC_LIBS         -lm -lsasl2 -lssl -lcrypto -lcrypto -lz -ldl -lpthread -lrt -lpthread -lrt
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  runstatedir              /usr/local/var/run
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
  BUILT_WITH               GCC GXX INSTALL GNULD LDS C11THREADS LIBDL PLUGINS ZLIB SSL SASL_CYRUS HDRHISTOGRAM SYSLOG SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER
Generated config.cache

Now type 'make' to build
root@SOL1:~/librdkafka# make
make: Fatal error in reader: mklove/Makefile.base, line 15: Unexpected end of line seen
root@SOL1:~/librdkafka#

**Comment by edenhill** [comment]
Could be that [this](https://github.com/edenhill/librdkafka/blob/master/mklove/modules/configure.libzstd#L53) needs to use `gmake` (gnu make) instead of `make` (possibly SunStudio or whatever).
Try changing it and see if it helps
