### ISSUE TITLE
Selected provider Cyrus for SASL mechanism GSSAPI failed to create producer

### ISSUE THREAD

**Issue by smadurange** [edenhill/librdkafka#3393]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I'm trying to configure a client to use ssl together with username and password authentication. I'm configuring the client (a producer) as below

```
rd_kafka_conf_t *cfg = rd_kafka_conf_new();

if (rd_kafka_conf_set(cfg, "bootstrap.servers", brokers, err, sizeof(err) != RD_KAFKA_CONF_OK)) {
    fprintf(stderr, "failed to set brokers: %s\n", err);
    exit(EXIT_FAILURE);
}

if (rd_kafka_conf_set(cfg, "security.protocol", "sasl_ssl", err, sizeof(err) != RD_KAFKA_CONF_OK)) {
    fprintf(stderr, "failed to set security protocol: %s\n", err);
    exit(EXIT_FAILURE);
}

if (rd_kafka_conf_set(cfg, "sasl.username", username, err, sizeof(err) != RD_KAFKA_CONF_OK)) {
    fprintf(stderr, "failed to set sasl username: %s\n", err);
    exit(EXIT_FAILURE);
}
  
if (rd_kafka_conf_set(cfg, "sasl.password", pwd, err, sizeof(err) != RD_KAFKA_CONF_OK)) {
    fprintf(stderr, "failed to set sasl password: %s\n", err);
    exit(EXIT_FAILURE);
}

if (rd_kafka_conf_set(cfg, "ssl.ca.location", "ca.cert", err, sizeof(err) != RD_KAFKA_CONF_OK)) {
    fprintf(stderr, "failed to set ca certificate location: %s\n", err);
    exit(EXIT_FAILURE);
}

rd_kafka_t *producer;
if (!(producer = rd_kafka_new(RD_KAFKA_PRODUCER, cfg, err, sizeof(err)))) {
    fprintf(stderr, "failed to create producer: %s\n", err);
    exit(EXIT_FAILURE);
}
```
When I start the client, I see the error:

```
%7|1621160000.863|SASL|rdkafka#producer-1| [thrd:app]: Selected provider Cyrus for SASL mechanism GSSAPI
failed to create producer: Invalid sasl.kerberos.kinit.cmd value: Property not available: "sasl.kerberos.keytab"
```
Alternatively, I have a "kafka.client.truststore.pfx", not sure if I can use this instead. What I want to accomplish is just connecting to a broker that requires authentication and with ssl.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.70.0-1`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [x] librdkafka client configuration: `bootstrap.servers=broker1,broker2,broker3, security.protocol=sasl_ssl, sasl.username=my_username, sasl.password=my_pwd, ssl.ca.location"=my_ca.cert_file`
 - [x] Operating system: `Arch Linux (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You need to set `sasl.kerberos.keytab` in your config.

**Comment by smadurange** [comment]
@edenhill I don't have a keytab file. I checked with the broker side and they say that they are not using kerberos authentication. I'm probably missing something here. I don't have access to the broker clusters. All I got is just the username and password.

**Comment by rolandyoung** [comment]
The SASL mechanism defaults to GSSAPI (that is, Kerberos). Try adding this setting: `sasl.mechanism=PLAIN`

In your case:
```
if (rd_kafka_conf_set(cfg, "sasl.mechanism", "PLAIN", err, sizeof(err)) != RD_KAFKA_CONF_OK)
```
Do please notice that you have a right parenthesis in the wrong place in every one of your calls to rd_kafka_conf_set - you are passing the fourth argument as `sizeof(err) != RD_KAFKA_CONF_OK`, which is a boolean expression, so that you are passing 1 or 0 as the size of the `err` buffer.

**Comment by smadurange** [comment]
@rolandyoung Thanks so much for your help! `PLAIN` didn't work for me, but your explanation put me on the right track. When I changed it to  `PLAIN` the broker started spitting out errors like

```
SASL GSSAPI mechanism handshake failed: Broker: Unsupported SASL mechanism: broker's supported mechanisms: SCRAM-SHA-256 
```

And I changed the mechanism to `SCRAM-SHA-256` and it's all good now :)
