### ISSUE TITLE
Issue in accessing librdkafka.so in Solaris OS 11

### ISSUE THREAD

**Issue by kumarch7385** [edenhill/librdkafka#3394]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
While compiling using shared library(librdkafka.so) librdkafka getting below undefined reference error.
Kindly help me to resolve the below issue.

CC      -DSIXTY_FOUR_BIT_LONGS  -m64  -mt -D_RWCONFIG_12s -DRW_MULTI_THREAD   -DRWDB_ORACLE10X  -D_RWSTD_MULTI_THREAD -D_REENTRANT -DIT_USE_STD_IOSTREAM -DWANT_ORBIX_FDS -DSYNCHRONIZATION_REQUIRED  -I. -O -I/opt/csw/include/librdkafka  -c sampleClient.C -o sampleClient.o

CC      -m64 -mt sampleClient.o   -o ../bin/sampleClient  -L/opt/csw/lib/64 -lrdkafka
Undefined                       first referenced
 symbol                             in file
rd_ut_coverage_check                /opt/csw/lib/64/librdkafka.so

How to reproduce
================
**1.  Install the pacakge using below command**  https://www.opencsw.org/packages/CSWlibrdkafka-dev/
     /opt/csw/bin/pkgutil -y -i librdkafka_dev 

**2. Write sample code**
File : sampleClient.C
#include <fstream.h>
#include <rdkafka.h> 

int main( int iArgc, char** iArgv )
{
   
   rd_kafka_conf_t *conf;
   conf = rd_kafka_conf_new(); 
   
   return 0;
}

**3. Makefile**

LOCALCFLAGS=    -I. -O -I/opt/csw/include/librdkafka
LOCALLDFLAGS=	-L/opt/csw/lib/64 -lrdkafka
SYNCHRONIZATION_REQUIRED = -DSYNCHRONIZATION_REQUIRED 
export SYNCHRONIZATION_REQUIRED
OBJS=sampleClient.o 
SERVER= ../bin/sampleClient
TEMPLATES_OBJS= SunWS_cache/*/*.o
all: all_dirs depend
	rm -f sampleClient.o
	$(MAKE) $(MKFLAGS) $(SERVER)${PURESUF}

clean::	clean_dirs

include ../../../../config/makefile_${OSTYPE}.mk
#------------------------------------

**4. Give make**
CC      -DSIXTY_FOUR_BIT_LONGS  -m64  -mt -D_RWCONFIG_12s -DRW_MULTI_THREAD   -DRWDB_ORACLE10X  -D_RWSTD_MULTI_THREAD -D_REENTRANT -DIT_USE_STD_IOSTREAM -DWANT_ORBIX_FDS -DSYNCHRONIZATION_REQUIRED  -I. -O -I/opt/csw/include/librdkafka  -c sampleClient.C -o sampleClient.o

CC      -m64 -mt sampleClient.o   -o ../bin/sampleClient  -L/opt/csw/lib/64 -lrdkafka
Undefined                       first referenced
 symbol                             in file
rd_ut_coverage_check                /opt/csw/lib/64/librdkafka.so
ld: fatal: symbol referencing errors
make[1]: *** [../bin/sampleClient] Error 2

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag):    https://www.opencsw.org/packages/CSWlibrdkafka-dev/ 
                                                                                    /opt/csw/bin/pkgutil -y -i librdkafka_dev 
 - [ ] Apache Kafka version: `NA
 - [ ] librdkafka client configuration: `NA
 - [x] Operating system: Solaris 11 Sparc
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by kumarch7385** [comment]
Any clue ?

**Comment by edenhill** [comment]
No idea, that symbol is only referenced from the test suite.
I don't have any up to date experience with solaris, et.al.

**Comment by kumarch7385** [comment]
Thanks for you response @edenhill 

We have installed the package from https://www.opencsw.org/packages/CSWlibrdkafka-dev/
Where the version is mentioned as  Version | 1.5.3,REV=2020.12.29.

Is this latest ? if not can I get the latest for Solaris. ?

**Comment by edenhill** [comment]
We don't package for Solaris, you will need to talk to the people that do (OpenCSW folks?)
