### ISSUE TITLE
rd_kafka_consumer_poll() returns null most of the times

### ISSUE THREAD

**Issue by reddybhargava** [edenhill/librdkafka#3397]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I'm using the consumer.c from https://github.com/edenhill/librdkafka/blob/master/examples/consumer.c without any changes and executing it as ./consumer broker groupid topicname and rd_kafka_consumer_poll returns null most of the times (except for certain groupid values) even though there is data present in the kafka cluster. I'd understand if some number of calls return null but I don't understand why it is always null.

I have tried increasing the poll timeout from 100ms to 1000ms, it still doesn't make any difference and returns null all the time. But at certain random groupid values, it does fetch all the data from the cluster. On repeated runs, I've to keep increasing the groupid value to random values for the consumer to fetch data.

Is this the expected behavior of rd_kafka_consumer_poll ? Or is there something I've to change in the implementation

How to reproduce
================
- By using the consumer.c from https://github.com/edenhill/librdkafka/blob/master/examples/consumer.c without any changes.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.6.1`
 - [x] Apache Kafka version: `not sure`
 - [x] librdkafka client configuration: `auto.reset.offset=earliest`
 - [x] Operating system: `Linux 3.10.0`

**Comment by edenhill** [comment]
If you use a group.id that has committed offsets for the given topic(s) it will resume from those offsets. If they are the end of the partition there will be no messages returned from poll().

Using a new group.id without committed offsets, and having auto.reset.offset=earliest, will read from the beginning.

**Comment by reddybhargava** [comment]
Hi,
Yes I knew that. But didn't realize by default the offsets were getting committed. Got it to work now.
Thanks.
