### ISSUE TITLE
[Feature Request] Add support for AWS_MSK_IAM SASL mechanism to librdkafka.

### ISSUE THREAD

**Issue by sayantacC** [edenhill/librdkafka#3402]
Description
===========
AWS recently [introduced](https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html) a SASL mechanism for AWS_MSK_IAM that allows Kafka clients to handle authentication and authorization with [MSK](https://aws.amazon.com/msk/) clusters through [AWS IAM](https://aws.amazon.com/iam/). AWS launched a java based plugin [aws-msk-iam-auth](https://github.com/aws/aws-msk-iam-auth) for integrating AWS_MSK_IAM as a SASL mechanism for JVM based clients. We (from AWS) would like to work with you to add support for AWS_MSK_IAM as a SASL mechanism in librdkafka. This issue was filed as a follow up from the [discussion thread](https://github.com/edenhill/librdkafka/discussions/3385).

Based on initial exploration, we have identified two possible approaches:
* Write a librdkafka plugin to implement and register an additional SASL provider. However, as far as I could tell, librdkafka's plugin architecture will have to be extended to allow a plugin to implement and set the sasl provider based on the configured mechanism.
* Implement AWS_MSK_IAM as another sasl mechanism within librdkafka.

We would love to learn if there are other possible approaches and your thoughts on which one to take. Also, any suggestions on next steps would be great.

How to reproduce
================
Not filling this in as it is a feature request.

Checklist
=========

Please provide the following information:

 - [ ] librdkafka version (release number or git tag): NA since it is a feature request.
 - [x] Apache Kafka version: `> 2.4`
 - [ ] librdkafka client configuration: 
 - [ ] Operating system: 
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by gokul2411s** [comment]
Bumping up. As of now, there are 23 +1's on this. Any thoughts on this from the maintainers of librdkafka?

**Comment by edenhill** [comment]
If you need to add a new SASL mechanism to Kafka clients you should follow the Apache Kafka KIP process by writing up a proposal and get buy-in from the open source Kafka community.
See [Kafka Improvement Proposals](https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals) for more details.

There would also need to be the corresponding broker support for this mechanism to be usable by the community, and testable by client maintainers.

When the KIP has been accepted you're welcome to contribute a PR to add support to librdkafka.

**Comment by garrett528** [comment]
would you be open to allow librdkafka to have some way to plug in a custom mechanism like what was suggested as option 1? 

the standard Java clients already support this type of behavior via JAAS and the client callback handler in the [SaslConfigs class](https://github.com/apache/kafka/blob/e8754ba7a01f33ba503ef79de66a5f644cc2ced8/clients/src/main/java/org/apache/kafka/common/config/SaslConfigs.java). for Java, AWS provided the JAAS config file and the callback handler. that is sufficient for the Java client to work properly. seems like a similar mechanism for librdkafka and those libraries that bind to it would be helpful for this use case as well as other SASL implementations that the community may need.

**Comment by garrett528** [comment]
@sayantacC @gokul2411s we forked this library so we could provide built-in IAM SASL auth for our downstream clients that rely on librdkafka. That fork can be found [here](https://github.com/UrbanCompass/librdkafka).

@edenhill we'd love to work with you to get this integrated back into master at some point. if you'd be willing, we can modify this fork to better fit your vision for the library and refactor anything that you recommend (i tried to keep it close to how you implemented other SASL mechanisms)

**Comment by arunvasudevan** [comment]
@edenhill Any path forward on merging the fork @garrett528 created above to provide IAM support for kafka?

**Comment by arunvasudevan** [comment]
Just noticed this comment - https://github.com/edenhill/librdkafka/pull/3496#issuecomment-901183346
This makes it clear on what to expect

**Comment by ScheerMT** [comment]
@sayantacC - I went looking to see if there is an open KIP for this yet. Will this be pursued further?

**Comment by rcollette** [comment]
Doesn't [KIP-86](https://cwiki.apache.org/confluence/display/kafka/kip-86%3a+configurable+sasl+callback+handlers) already cover the scenario of pluggable authorization providers via login and callback methods and it's just that the maintainers have chosen not to implement it?  That's why it's so easy to do with the Java client.

**Comment by niemyjski** [comment]
> Doesn't [KIP-86](https://cwiki.apache.org/confluence/display/kafka/kip-86%3a+configurable+sasl+callback+handlers) already cover the scenario of pluggable authorization providers via login and callback methods and it's just that the maintainers have chosen not to implement it? That's why it's so easy to do with the Java client.

@edenhill ^^

**Comment by VineetSa** [comment]
> @sayantacC @gokul2411s we forked this library so we could provide built-in IAM SASL auth for our downstream clients that rely on librdkafka. That fork can be found [here](https://github.com/UrbanCompass/librdkafka).
> 
> @edenhill we'd love to work with you to get this integrated back into master at some point. if you'd be willing, we can modify this fork to better fit your vision for the library and refactor anything that you recommend (i tried to keep it close to how you implemented other SASL mechanisms)

@garrett528  -> can you also help with the the right documentation on how to get this running using python, with the configurations as example. This will be great help.

**Comment by judilsteve** [comment]
@garrett528 I've been trying to get your fork built using docker today but not having much luck. I think I'm missing some AWS-IAM-specific header files but not sure which. Would you please be able to point me in the right direction?

**Comment by bcarranza** [comment]
Hi comunity 
Here Also trying to connect to MSK Kafka by IAM whit the next configuration
```

# Sets up TLS for encryption and SASL for authN.
security.protocol = SASL_SSL

# Identifies the SASL mechanism to use.
sasl.mechanism = AWS_MSK_IAM

# Binds SASL client implementation.
sasl.jaas.config = software.amazon.msk.auth.iam.IAMLoginModule required;

# Encapsulates constructing a SigV4 signature based on extracted credentials.
# The SASL client bound by "sasl.jaas.config" invokes this class.
sasl.client.callback.handler.class = software.amazon.msk.auth.iam.IAMClientCallbackHandler
```

Has anyone had success along the way?

**Comment by drennerpfc6** [comment]
Does [KIP-86](https://cwiki.apache.org/confluence/display/kafka/kip-86%3a+configurable+sasl+callback+handlers) only apply to the Java implementation?

Would there be any benefit/movement in opening a new issue requesting [KIP-86](https://cwiki.apache.org/confluence/display/kafka/kip-86%3a+configurable+sasl+callback+handlers) to be implemented? With that in place @sayantacC can provide a Python equivalent to [aws-msk-iam-auth](https://github.com/aws/aws-msk-iam-auth).

**Comment by ivanbishop** [comment]
Asking is tehre has been any futrtehr effort/success implemen ting IAM support for librdkafka per https://cwiki.apache.org/confluence/display/kafka/kip-86%3a+configurable+sasl+callback+handlers
