### ISSUE TITLE
Missing library in Visual Studio nuget

### ISSUE THREAD

**Issue by MPeli** [edenhill/librdkafka#3405]
Description
===========
I cannot build a project using https://www.nuget.org/packages/librdkafka.redist/ However, when I add librdkafkacpp.lib to the local copy of [librdkafka.redist.targets](https://github.com/edenhill/librdkafka/blob/master/packaging/nuget/templates/librdkafka.redist.targets), the build succeeded.

How to reproduce
================
Create a C++ project in Visual Studio, add librdkafka.redist v1.7.0. 

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.7.8`
 - [N/A] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [N/A] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `Windows`
 - [N/A] Provide logs (with `debug=..` as necessary) from librdkafka
 - [N/A] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Add librdkafkacpp.lib to your application instead
