### ISSUE TITLE
crash when rd_kafka_msg_partitioner_consistent is called with a partition count of 0

### ISSUE THREAD

**Issue by lehenbauer** [edenhill/librdkafka#341]
Apparently when a topic is first being created, the metadata for the topic can return a partition count of zero.  If rd_kafka_msg_partitioner_consistent is invoked with a zero parttion count, it does a divide-by-zero (modulo-by-zero) at rdkafka_msg.c:330:
```c
 return rd_crc32(key, keylen) % partition_cnt;
```
I propose rd_kafka_msg_partitioner_consistent is called with a partition count of 0 that it return -1.

**Comment by DEvil0000** [comment]
I would say invoking the partitioner with a partition count of 0 is illegal. You can not produce if there is no partition. I would handle it before calling partitioner.

**Comment by edenhill** [comment]
Thanks Karl, good find. 
I agree with devil's solution, will fix it.

**Comment by edenhill** [comment]
@lehenbauer What librdkafka version are you using? There is code to protect from this scenario here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_msg.c#L371

Do you still have a core file from this event so we can have a look at the call chain?

**Comment by edenhill** [comment]
ping @lehenbauer ?
