### ISSUE TITLE
LibrdKafka Giving undefined symbol: _ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE

### ISSUE THREAD

**Issue by ankush2394** [edenhill/librdkafka#3419]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
i have been trying LibrdKafka library for my node application running on Debian with node:erbium image, i have used the following in docker file.

RUN apt-get update -y
RUN apt-get install build-essential musl-dev -y
RUN ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1

RUN git clone https://github.com/edenhill/librdkafka.git
WORKDIR /srv/chat-service/librdkafka
RUN /srv/chat-service/librdkafka/configure --prefix /usr
RUN make
RUN make install

How to reproduce
================
As soon as i deploy ,i used a node package "node-rdkafka": "2.10.0" in package.json and require it in consumer, but i am getting this error '/node_modules/node-rdkafka/build/Release/node-librdkafka.node: undefined symbol: _ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE' everytime i start my application due to which my consumers PM2 log: App [consumer-xyz:6] exited with code [0] via signal [SIGINT] this happpens

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

librdkafka version: '1.7.0'
Apache Kafka version: '0.11.0.3'
ibrdkafka client configuration: 'default'
Operating system: 'Debian'
Logs: '/node_modules/node-rdkafka/build/Release/node-librdkafka.node: undefined symbol: _ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE' ,PM2 log: App [consumer-xyz:6] exited with code [0] via signal [SIGINT]
Critical issue: true

**Comment by edenhill** [comment]
EscapableHandleScope is a nodeJs-symbol, not librdkafka, so this issue is not related to librdkafka.
File an issue with node-rdkafka.
