### ISSUE TITLE
Is there any proposal to add a condition wait on the internal librdkafka consumer message queue for data availability.

### ISSUE THREAD

**Issue by rathdeep** [edenhill/librdkafka#342]
Today, we continuously poll for the messages by calling msg_consume method as Kafka provides  pull mechanism.
E.g. in rdkafka_example.c
                while (run) {
                        rd_kafka_message_t *rkmessage;

                        /* Consume single message.
                         * See rdkafka_performance.c for high speed
                         * consuming of messages. */
                        rkmessage = rd_kafka_consume(rkt, partition, 1000);
                        if (!rkmessage) /* timeout */
                                continue;

                        msg_consume(rkmessage, NULL);

                        /* Return message to rdkafka */
                        rd_kafka_message_destroy(rkmessage);
                }

This takes lot of CPU even when there is no data in queue. We can add a sleep in above while loop to reduce the CPU consumption but that will delay message consumption.
If consumer thread waits on a condition and is woken up when data on internal queue is available, that will solve these problems.

Any thoughts or alternative to reduce CPU consumption without compromising on time.

Thanks.

**Comment by yungchin** [comment]
On 3 August 2015 at 13:53, rathdeep <notifications@github.com> wrote:

> Any thoughts or alternative to reduce CPU consumption without compromising
> on time.
>
Would `rd_kafka_consume(rkt, partition, -1)` - ie wait forever - do for
this purpose?

**Comment by rathdeep** [comment]
here the CPU consumption is due to continuously calling rd_kafka_consume() in a while loop without any sleep.

**Comment by rathdeep** [comment]
rdkafka_performance.c:
			} else {
				/* Callback mode */
				r = rd_kafka_consume_callback(rkt, partition,
							      1000/*timeout*/, ==> changed this to -1, but it does not wait 
                                                                                               _____________________________
							      msg_consume,
							      NULL);
			}

**Comment by yungchin** [comment]
No, but that's in callback mode? Also I don't see why that would give you
high cpu load if nothing new arrives? Your msg_consume should never run.

**Comment by rathdeep** [comment]
you are correct.that will solve the problem of high CPU.  Thanks.
I am using rd_kafka_consume_callback in my application... Looking at the API rd_kafka_consume_callback, -1 should work, but not working if i modify the rdkafka_performance.c example

**Comment by rathdeep** [comment]
Edenhill, Any comments on timeout argument of rd_kafka_consume_callback. Shouldn't -1 block  until data is available?

Thanks.

**Comment by edenhill** [comment]
I don't see why -1 wouldn't work? It should block indefinitely until a new message is available, thus no CPU will we utilized during the waiting idle periods.

**Comment by rathdeep** [comment]
To test  that, I just modified rdkafka_performance.c as below. 
1172                                 }
1173                         } else {
1174                                 /* Callback mode */
1175                                 r = rd_kafka_consume_callback(rkt, partition,
1176                                                               -1/*timeout*/,
1177                                                               msg_consume,
1178                                                               NULL);
1179                                 printf ("CALLING rd_kafka_consume_callback\n");
1180                         }

And ran ./rdkafka_performance -C -b broker -t topic -p 0
which prints the statement “CALLING rd_kafka_consume_callback” continuously. Am I missing anything.

**Comment by edenhill** [comment]
I cannot reproduce this behaviour but I recall something similar occuring on some systems due to an unblockable thread synchronization signal being issued:
https://github.com/edenhill/librdkafka/issues/272

But it should only occur with pthread_cancel() and seteuid(), which rdkafka_performance does none of.

Could you compile librdkafka with profiling enabled and then rerun rdkafka_performance followed by gprof and then paste the output of gprof to this issue?

````
./configure --enable-profiling
make clean all

examples/rdkafka_performance -C -b broker -t topic -p 0
gprof examples/rdkafka_performance gmon.out
`````

**Comment by rathdeep** [comment]
sure.. when i tried debugging earlier, i saw call to pthread_cond_timedwait_ms and not pthread_cond_wait inside  rd_kafka_q_serve method.

**Comment by rathdeep** [comment]
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name
 24.69      0.20     0.20 13551499     0.00     0.00  rd_kafka_consume_callback
 24.69      0.40     0.20                             main
 20.37      0.57     0.17 27103083     0.00     0.00  rd_kafka_q_serve
 17.29      0.71     0.14 13551485     0.00     0.00  print_stats
  8.64      0.78     0.07 13551563     0.00     0.00  rd_kafka_toppar_get
  1.23      0.79     0.01 13551503     0.00     0.00  rd_kafka_poll
  1.23      0.80     0.01   273623     0.00     0.00  rd_kafka_toppar_desired_get
  1.23      0.81     0.01        4     2.50     2.50  stats_cb
  0.62      0.81     0.01       15     0.33     0.33  rd_kafka_op_destroy
  0.00      0.81     0.00      718     0.00     0.00  rd_kafka_topic_find
  0.00      0.81     0.00      662     0.00     0.00  rd_kafka_topic_metadata_update
  0.00      0.81     0.00      261     0.00     0.01  rd_kafka_recv
  0.00      0.81     0.00      162     0.00     0.00  rd_kafka_msghdr_rebuild
  0.00      0.81     0.00      155     0.00     0.00  rd_kafka_buf_push
  0.00      0.81     0.00      143     0.00     0.02  rd_kafka_broker_io_serve
  0.00      0.81     0.00      136     0.00     0.00  rd_kafka_buf_new
  0.00      0.81     0.00      134     0.00     0.00  rd_kafka_broker_waitresp_timeout_scan
  0.00      0.81     0.00      134     0.00     0.00  rd_kafka_buf_destroy
  0.00      0.81     0.00       77     0.00     0.00  rd_kafka_bufq_deq
  0.00      0.81     0.00       69     0.00     0.00  pthread_cond_timedwait_ms
…………………
……………



granularity: each sample hit covers 2 byte(s) for 1.23% of 0.81 seconds

index % time    self  children    called     name
                                                 <spontaneous>
[1]     99.5    0.20    0.61                 main [1]
                0.20    0.17 13551499/13551499     rd_kafka_consume_callback [2]
                0.14    0.00 13551485/13551485     print_stats [4]
                0.08    0.01 13551566/27103083     rd_kafka_q_serve [3]
                0.01    0.00 13551503/13551503     rd_kafka_poll [6]
                0.00    0.00       1/1           rd_kafka_destroy [23]
                0.00    0.00       1/1           rd_kafka_consume_stop [26]
                0.00    0.00       1/59          rd_kafka_topic_destroy0 <cycle 1> [48]
                0.00    0.00       1/59          rd_kafka_destroy0 <cycle 1> [58]
                0.00    0.00       1/1           rd_kafka_consume_start0 [32]
                0.00    0.00       6/6           rd_kafka_anyconf_set [60]
                0.00    0.00       6/6           rd_kafka_conf_set [62]
                0.00    0.00       2/2           rd_clock [82]
                0.00    0.00       1/1           rd_kafka_conf_new [89]
                0.00    0.00       1/1           rd_kafka_conf_set_dr_msg_cb [90]
                0.00    0.00       1/1           rd_kafka_conf_set_error_cb [91]
                0.00    0.00       1/1           rd_kafka_topic_conf_new [101]
                0.00    0.00       1/1           rd_kafka_conf_set_stats_cb [92]
                0.00    0.00       1/1           rd_kafka_wait_destroyed [108]
                0.00    0.00       1/1           rd_kafka_new [95]
                0.00    0.00       1/1           rd_kafka_brokers_add [88]
                0.00    0.00       1/1           rd_kafka_topic_new [105]
                0.00    0.00       1/1           rd_kafka_consume_start [94]
                0.00    0.00       1/1           rd_kafka_topic_destroy [102]
-----------------------------------------------
                0.20    0.17 13551499/13551499     main [1]
[2]     45.4    0.20    0.17 13551499         rd_kafka_consume_callback [2]
                0.08    0.01 13551517/27103083     rd_kafka_q_serve [3]
                0.07    0.00 13551514/13551563     rd_kafka_toppar_get [5]
                0.01    0.00  273620/273623      rd_kafka_toppar_desired_get [7]
-----------------------------------------------
                0.08    0.01 13551517/27103083     rd_kafka_consume_callback [2]
                0.08    0.01 13551566/27103083     main [1]
[3]     21.7    0.17    0.01 27103083         rd_kafka_q_serve [3]
                0.00    0.01       1/1           rd_kafka_poll_cb [9]
                0.00    0.00       5/59          rd_kafka_op_destroy <cycle 1> [11]
                0.00    0.00       1/1           msg_consume [86]
                0.00    0.00       1/1           rd_kafka_consume_cb [93]
-----------------------------------------------
                0.14    0.00 13551485/13551485     main [1]
[4]     17.3    0.14    0.00 13551485         print_stats [4]
-----------------------------------------------
                0.00    0.00       1/13551563     rd_kafka_consume_stop [26]
                0.00    0.00       1/13551563     rd_kafka_toppar_desired_add [33]
                0.00    0.00       1/13551563     rd_kafka_topic_assign_uas [34]
                0.00    0.00       1/13551563     rd_kafka_topic_partition_cnt_update [28]
                0.00    0.00       3/13551563     rd_kafka_topic_partitions_remove [24]
                0.00    0.00       8/13551563     rd_kafka_topic_metadata_update [19]
                0.00    0.00      11/13551563     rd_kafka_topic_scan_all [31]
                0.00    0.00      23/13551563     rd_kafka_toppar_get2 [16]
                0.07    0.00 13551514/13551563     rd_kafka_consume_callback [2]
[5]      8.6    0.07    0.00 13551563         rd_kafka_toppar_get [5]
-----------------------------------------------
                0.01    0.00 13551503/13551503     main [1]
[6]      1.2    0.01    0.00 13551503         rd_kafka_poll [6]
-----------------------------------------------
                0.00    0.00       1/273623      rd_kafka_toppar_desired_add [33]
                0.00    0.00       2/273623      rd_kafka_topic_partition_cnt_update [28]
                0.01    0.00  273620/273623      rd_kafka_consume_callback [2]
[7]      1.2    0.01    0.00  273623         rd_kafka_toppar_desired_get [7]
-----------------------------------------------
                0.01    0.00       4/4           rd_kafka_poll_cb [9]
[8]      1.2    0.01    0.00       4         stats_cb [8]
                0.00    0.00       4/4           json_parse_stats [66]
-----------------------------------------------
                0.00    0.01       1/1           rd_kafka_q_serve [3]
[9]      1.2    0.00    0.01       1         rd_kafka_poll_cb [9]
                0.01    0.00       4/4           stats_cb [8]
-----------------------------------------------
[10]     0.6    0.01    0.00      59+9       <cycle 1 as a whole> [10]
                0.01    0.00      15             rd_kafka_op_destroy <cycle 1> [11]
                0.00    0.00      33             rd_kafka_topic_destroy0 <cycle 1> [48]
                0.00    0.00      13             rd_kafka_q_purge <cycle 1> [52]
                0.00    0.00       7             rd_kafka_destroy0 <cycle 1> [58]
-----------------------------------------------
                                   6             rd_kafka_q_purge <cycle 1> [52]
                0.00    0.00       4/59          rd_kafka_broker_metadata_reply [17]
                0.00    0.00       5/59          rd_kafka_q_serve [3]
[11]     0.6    0.01    0.00      15         rd_kafka_op_destroy <cycle 1> [11]
                                   1             rd_kafka_topic_destroy0 <cycle 1> [48]
-----------------------------------------------
                                                 <spontaneous>
[12]     0.5    0.00    0.00                 rd_kafka_broker_thread_main [12]
                0.00    0.00     143/143         rd_kafka_broker_io_serve [14]
                0.00    0.00       3/3           rd_kafka_broker_fail [20]
                0.00    0.00       2/20          rd_kafka_broker_destroy [18]
                0.00    0.00     134/134         rd_kafka_broker_waitresp_timeout_scan [39]
                0.00    0.00     111/155         rd_kafka_buf_push [37]
                0.00    0.00      74/136         rd_kafka_buf_new [38]
                0.00    0.00      46/134         rd_kafka_buf_destroy [40]
                0.00    0.00      37/41          rd_kafka_broker_buf_enq1 [44]
                0.00    0.00       4/4           rd_kafka_socket_cb_linux [70]
                0.00    0.00       4/6           rd_kafka_broker_set_state [61]
                0.00    0.00       4/4           rd_kafka_broker_metadata_req_op [68]
                0.00    0.00       4/4           rd_kafka_broker_metadata_req [67]
                0.00    0.00       3/3           rd_getaddrinfo [75]
-----------------------------------------------
                0.00    0.00     261/261         rd_kafka_broker_io_serve [14]
[13]     0.4    0.00    0.00     261         rd_kafka_recv [13]
                0.00    0.00      21/22          rd_kafka_broker_fetch_reply [15]
                0.00    0.00       3/3           rd_kafka_broker_metadata_reply [17]
                0.00    0.00     162/162         rd_kafka_msghdr_rebuild [36]
                0.00    0.00      41/136         rd_kafka_buf_new [38]
                0.00    0.00      34/77          rd_kafka_bufq_deq [41]
                0.00    0.00      17/17          rd_kafka_toppar_offset_reply [51]
-----------------------------------------------
                0.00    0.00     143/143         rd_kafka_broker_thread_main [12]
[14]     0.4    0.00    0.00     143         rd_kafka_broker_io_serve [14]
                0.00    0.00     261/261         rd_kafka_recv [13]
                0.00    0.00      62/62          rd_kafka_send [43]
-----------------------------------------------
                0.00    0.00       1/22          rd_kafka_broker_fail [20]
                0.00    0.00      21/22          rd_kafka_recv [13]
[15]     0.2    0.00    0.00      22         rd_kafka_broker_fetch_reply [15]
                0.00    0.00      22/22          rd_kafka_toppar_get2 [16]
                0.00    0.00      43/134         rd_kafka_buf_destroy [40]
                0.00    0.00       3/7           rd_clock [57]
                0.00    0.00       1/10          rd_kafka_op_new [54]
                0.00    0.00       1/1           rd_kafka_q_enq [98]
                0.00    0.00       1/1           rd_kafka_offset_reset [96]
-----------------------------------------------
                0.00    0.00      22/22          rd_kafka_broker_fetch_reply [15]
[16]     0.2    0.00    0.00      22         rd_kafka_toppar_get2 [16]
                0.00    0.00      21/59          rd_kafka_topic_destroy0 <cycle 1> [48]
                0.00    0.00      23/13551563     rd_kafka_toppar_get [5]
                0.00    0.00      22/22          rd_kafka_topic_find0 [49]
-----------------------------------------------
                0.00    0.00       3/3           rd_kafka_recv [13]
[17]     0.2    0.00    0.00       3         rd_kafka_broker_metadata_reply [17]
                0.00    0.00     662/662         rd_kafka_topic_metadata_update [19]
                0.00    0.00       9/20          rd_kafka_broker_destroy [18]
                0.00    0.00       4/59          rd_kafka_op_destroy <cycle 1> [11]
                0.00    0.00      11/17          rd_kafka_broker_find_by_nodeid [50]
                0.00    0.00       8/134         rd_kafka_buf_destroy [40]
                0.00    0.00       2/3           rd_kafka_broker_add [76]
-----------------------------------------------
                0.00    0.00       1/20          rd_kafka_toppar_broker_delegate [27]
                0.00    0.00       2/20          rd_kafka_broker_thread_main [12]
                0.00    0.00       8/20          rd_kafka_topic_metadata_update [19]
                0.00    0.00       9/20          rd_kafka_broker_metadata_reply [17]
[18]     0.1    0.00    0.00      20         rd_kafka_broker_destroy [18]
                0.00    0.00       4/4           rd_kafka_q_destroy [22]
                0.00    0.00       4/59          rd_kafka_q_purge <cycle 1> [52]
                0.00    0.00       4/59          rd_kafka_destroy0 <cycle 1> [58]
                0.00    0.00       3/3           rd_sockaddr_list_destroy [81]
-----------------------------------------------
                0.00    0.00     662/662         rd_kafka_broker_metadata_reply [17]
[19]     0.1    0.00    0.00     662         rd_kafka_topic_metadata_update [19]
                0.00    0.00       8/20          rd_kafka_broker_destroy [18]
                0.00    0.00       4/59          rd_kafka_topic_destroy0 <cycle 1> [48]
                0.00    0.00       2/4           rd_kafka_toppar_broker_delegate [27]
                0.00    0.00       4/4           rd_kafka_topic_partition_cnt_update [28]
                0.00    0.00       8/13551563     rd_kafka_toppar_get [5]
                0.00    0.00       1/1           rd_kafka_topic_assign_uas [34]
                0.00    0.00     717/718         rd_kafka_topic_find [35]
                0.00    0.00       6/17          rd_kafka_broker_find_by_nodeid [50]
                0.00    0.00       4/4           rd_kafka_topic_set_state [72]
-----------------------------------------------
                0.00    0.00       3/3           rd_kafka_broker_thread_main [12]
[20]     0.1    0.00    0.00       3         rd_kafka_broker_fail [20]
                0.00    0.00       2/3           rd_kafka_toppar_destroy0 [21]
                0.00    0.00       2/59          rd_kafka_topic_destroy0 <cycle 1> [48]
                0.00    0.00       1/22          rd_kafka_broker_fetch_reply [15]
                0.00    0.00       2/4           rd_kafka_toppar_broker_delegate [27]
                0.00    0.00       4/134         rd_kafka_buf_destroy [40]
                0.00    0.00       4/4           rd_kafka_bufq_concat [69]
                0.00    0.00       2/6           rd_kafka_broker_set_state [61]
-----------------------------------------------
                0.00    0.00       1/3           rd_kafka_topic_partitions_remove [24]
                0.00    0.00       2/3           rd_kafka_broker_fail [20]
[21]     0.1    0.00    0.00       3         rd_kafka_toppar_destroy0 [21]
                0.00    0.00       3/59          rd_kafka_topic_destroy0 <cycle 1> [48]
                0.00    0.00       3/59          rd_kafka_q_purge <cycle 1> [52]
                0.00    0.00       6/6           rd_kafka_op_reply2 [63]
                0.00    0.00       5/5           rd_kafka_dr_msgq [64]
-----------------------------------------------
                0.00    0.00       4/4           rd_kafka_broker_destroy [18]
[22]     0.0    0.00    0.00       4         rd_kafka_q_destroy [22]
                0.00    0.00       4/59          rd_kafka_q_purge <cycle 1> [52]
-----------------------------------------------
                0.00    0.00       1/1           main [1]
[23]     0.0    0.00    0.00       1         rd_kafka_destroy [23]
                0.00    0.00       1/1           rd_kafka_topic_partitions_remove [24]
                0.00    0.00       1/59          rd_kafka_topic_destroy0 <cycle 1> [48]
                0.00    0.00       1/1           rd_kafka_timers_interrupt [100]
-----------------------------------------------
                0.00    0.00       1/1           rd_kafka_destroy [23]
[24]     0.0    0.00    0.00       1         rd_kafka_topic_partitions_remove [24]
                0.00    0.00       1/3           rd_kafka_toppar_destroy0 [21]
                0.00    0.00       3/13551563     rd_kafka_toppar_get [5]
-----------------------------------------------
                                                 <spontaneous>
[25]     0.0    0.00    0.00                 rd_kafka_thread_main [25]
                0.00    0.00       1/59          rd_kafka_destroy0 <cycle 1> [58]
                0.00    0.00       5/5           rd_kafka_timers_run [29]
                0.00    0.00       3/3           rd_kafka_timer_start [79]
-----------------------------------------------
                0.00    0.00       1/1           main [1]
[26]     0.0    0.00    0.00       1         rd_kafka_consume_stop [26]
                0.00    0.00       1/59          rd_kafka_q_purge <cycle 1> [52]
                0.00    0.00       1/13551563     rd_kafka_toppar_get [5]
                0.00    0.00       1/1           rd_kafka_toppar_desired_del [106]
                0.00    0.00       1/1           rd_kafka_offset_store_term [97]
                0.00    0.00       1/1           rd_kafka_q_fwd_set [99]
-----------------------------------------------
                0.00    0.00       2/4           rd_kafka_broker_fail [20]
                0.00    0.00       2/4           rd_kafka_topic_metadata_update [19]
[27]     0.0    0.00    0.00       4         rd_kafka_toppar_broker_delegate [27]
                0.00    0.00       1/20          rd_kafka_broker_destroy [18]
-----------------------------------------------
                0.00    0.00       4/4           rd_kafka_topic_metadata_update [19]
[28]     0.0    0.00    0.00       4         rd_kafka_topic_partition_cnt_update [28]
                0.00    0.00       2/273623      rd_kafka_toppar_desired_get [7]
                0.00    0.00       1/13551563     rd_kafka_toppar_get [5]
                0.00    0.00       1/3           rd_kafka_toppar_new [80]
-----------------------------------------------
                0.00    0.00       5/5           rd_kafka_thread_main [25]
[29]     0.0    0.00    0.00       5         rd_kafka_timers_run [29]
                0.00    0.00       4/4           rd_kafka_topic_scan_tmr_cb [30]
                0.00    0.00      69/69          pthread_cond_timedwait_ms [42]
                0.00    0.00       6/9           rd_kafka_timer_schedule [56]
                0.00    0.00       4/4           rd_kafka_stats_emit_tmr_cb [71]
-----------------------------------------------
                0.00    0.00       4/4           rd_kafka_timers_run [29]
[30]     0.0    0.00    0.00       4         rd_kafka_topic_scan_tmr_cb [30]
                0.00    0.00       2/2           rd_kafka_topic_scan_all [31]
-----------------------------------------------
                0.00    0.00       2/2           rd_kafka_topic_scan_tmr_cb [30]
[31]     0.0    0.00    0.00       2         rd_kafka_topic_scan_all [31]
                0.00    0.00      11/13551563     rd_kafka_toppar_get [5]
                0.00    0.00      12/12          rd_kafka_msgq_age_scan [53]
-----------------------------------------------
                0.00    0.00       1/1           main [1]
[32]     0.0    0.00    0.00       1         rd_kafka_consume_start0 [32]
                0.00    0.00       1/1           rd_kafka_toppar_desired_add [33]
-----------------------------------------------
                0.00    0.00       1/1           rd_kafka_consume_start0 [32]
[33]     0.0    0.00    0.00       1         rd_kafka_toppar_desired_add [33]
                0.00    0.00       1/273623      rd_kafka_toppar_desired_get [7]
                0.00    0.00       1/13551563     rd_kafka_toppar_get [5]
                0.00    0.00       1/3           rd_kafka_toppar_new [80]
-----------------------------------------------
                0.00    0.00       1/1           rd_kafka_topic_metadata_update [19]
[34]     0.0    0.00    0.00       1         rd_kafka_topic_assign_uas [34]
                0.00    0.00       1/13551563     rd_kafka_toppar_get [5]
-----------------------------------------------
                0.00    0.00       1/718         rd_kafka_topic_new [105]
                0.00    0.00     717/718         rd_kafka_topic_metadata_update [19]
[35]     0.0    0.00    0.00     718         rd_kafka_topic_find [35]
-----------------------------------------------
                0.00    0.00     162/162         rd_kafka_recv [13]
[36]     0.0    0.00    0.00     162         rd_kafka_msghdr_rebuild [36]
-----------------------------------------------
                0.00    0.00       3/155         rd_kafka_broker_metadata_req_op [68]
                0.00    0.00      41/155         rd_kafka_broker_buf_enq1 [44]
                0.00    0.00     111/155         rd_kafka_broker_thread_main [12]
[37]     0.0    0.00    0.00     155         rd_kafka_buf_push [37]
-----------------------------------------------
                0.00    0.00       4/136         rd_kafka_broker_metadata_req_op [68]
                0.00    0.00      17/136         rd_kafka_broker_buf_enq1 [44]
                0.00    0.00      41/136         rd_kafka_recv [13]
                0.00    0.00      74/136         rd_kafka_broker_thread_main [12]
[38]     0.0    0.00    0.00     136         rd_kafka_buf_new [38]
-----------------------------------------------
…………….
……………..

Index by function name

  [66] json_parse_stats (rdkafka_performance.c) [90] rd_kafka_conf_set_dr_msg_cb [79] rd_kafka_timer_start
   [1] main                   [91] rd_kafka_conf_set_error_cb [100] rd_kafka_timers_interrupt
  [86] msg_consume (rdkafka_performance.c) [92] rd_kafka_conf_set_stats_cb [29] rd_kafka_timers_run
   [4] print_stats (rdkafka_performance.c) [2] rd_kafka_consume_callback [34] rd_kafka_topic_assign_uas (rdkafka_topic.c)
  [42] pthread_cond_timedwait_ms [93] rd_kafka_consume_cb (rdkafka.c) [101] rd_kafka_topic_conf_new
  [73] rd_addrinfo_prepare    [94] rd_kafka_consume_start [102] rd_kafka_topic_destroy
  [74] rd_array_shuffle       [32] rd_kafka_consume_start0 (rdkafka.c) [48] rd_kafka_topic_destroy0
  [82] rd_clock (rdtime.h)    [26] rd_kafka_consume_stop  [35] rd_kafka_topic_find
  [57] rd_clock (rdtime.h)    [84] rd_kafka_defaultconf_set (rdkafka_defaultconf.c) [49] rd_kafka_topic_find0
  [75] rd_getaddrinfo         [23] rd_kafka_destroy      [103] rd_kafka_topic_leader_query0
  [83] rd_kafka_anyconf_destroy [58] rd_kafka_destroy0    [19] rd_kafka_topic_metadata_update
  [60] rd_kafka_anyconf_set (rdkafka_defaultconf.c) [64] rd_kafka_dr_msgq [104] rd_kafka_topic_name
  [47] rd_kafka_anyconf_set_prop0 (rdkafka_defaultconf.c) [36] rd_kafka_msghdr_rebuild (rdkafka_broker.c) [105] rd_kafka_topic_new
  [76] rd_kafka_broker_add (rdkafka_broker.c) [53] rd_kafka_msgq_age_scan [28] rd_kafka_topic_partition_cnt_update (rdkafka_topic.c)
  [87] rd_kafka_broker_any    [95] rd_kafka_new           [24] rd_kafka_topic_partitions_remove
  [45] rd_kafka_broker_buf_enq0 (rdkafka_broker.c) [96] rd_kafka_offset_reset [31] rd_kafka_topic_scan_all
  [44] rd_kafka_broker_buf_enq1 (rdkafka_broker.c) [97] rd_kafka_offset_store_term [30] rd_kafka_topic_scan_tmr_cb (rdkafka.c)
  [18] rd_kafka_broker_destroy [11] rd_kafka_op_destroy   [72] rd_kafka_topic_set_state (rdkafka_topic.c)
  [20] rd_kafka_broker_fail (rdkafka_broker.c) [54] rd_kafka_op_new [27] rd_kafka_toppar_broker_delegate
  [15] rd_kafka_broker_fetch_reply (rdkafka_broker.c) [77] rd_kafka_op_reply [33] rd_kafka_toppar_desired_add
  [50] rd_kafka_broker_find_by_nodeid [78] rd_kafka_op_reply0 [106] rd_kafka_toppar_desired_del
  [14] rd_kafka_broker_io_serve (rdkafka_broker.c) [63] rd_kafka_op_reply2 [7] rd_kafka_toppar_desired_get
  [17] rd_kafka_broker_metadata_reply (rdkafka_broker.c) [6] rd_kafka_poll [21] rd_kafka_toppar_destroy0
  [67] rd_kafka_broker_metadata_req [9] rd_kafka_poll_cb (rdkafka.c) [5] rd_kafka_toppar_get
  [68] rd_kafka_broker_metadata_req_op (rdkafka_broker.c) [22] rd_kafka_q_destroy [16] rd_kafka_toppar_get2
  [61] rd_kafka_broker_set_state (rdkafka_broker.c) [98] rd_kafka_q_enq (rdkafka_int.h) [65] rd_kafka_toppar_hi_offset_handle (rdkafka_broker.c)
  [39] rd_kafka_broker_waitresp_timeout_scan (rdkafka_broker.c) [99] rd_kafka_q_fwd_set [55] rd_kafka_toppar_lo_offset_handle (rdkafka_broker.c)
  [88] rd_kafka_brokers_add   [59] rd_kafka_q_init        [80] rd_kafka_toppar_new (rdkafka_topic.c)
  [40] rd_kafka_buf_destroy   [52] rd_kafka_q_purge      [107] rd_kafka_toppar_next_offset_handle (rdkafka_broker.c)
  [38] rd_kafka_buf_new (rdkafka_broker.c) [3] rd_kafka_q_serve (rdkafka.c) [51] rd_kafka_toppar_offset_reply (rdkafka_broker.c)
  [37] rd_kafka_buf_push (rdkafka_broker.c) [13] rd_kafka_recv (rdkafka_broker.c) [108] rd_kafka_wait_destroyed
  [69] rd_kafka_bufq_concat (rdkafka_broker.c) [43] rd_kafka_send (rdkafka_broker.c) [81] rd_sockaddr_list_destroy
  [41] rd_kafka_bufq_deq (rdkafka_broker.c) [70] rd_kafka_socket_cb_linux [8] stats_cb (rdkafka_performance.c)
  [46] rd_kafka_bufq_enq (rdkafka_broker.c) [71] rd_kafka_stats_emit_tmr_cb (rdkafka.c) [10] <cycle 1>
  [89] rd_kafka_conf_new      [85] rd_kafka_thread_cnt
  [62] rd_kafka_conf_set      [56] rd_kafka_timer_schedule (rdkafka_timer.c)

**Comment by edenhill** [comment]
Thanks.
Could you check the return value of `pthread_cond_wait()` and print it along with errno here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L452

e.g.:
````
 int r = pthread_cond_wait(&....);
 printf("cond_wait ret %d, %s\n", r, strerror(errno));
````

**Comment by rathdeep** [comment]
in my local copy (downloaded early Jun)... i see following code which is different from the master code ( it has max_cnt-- criteria). Was there any bug fix.
static int rd_kafka_q_serve (rd_kafka_q_t *rkq, int timeout_ms,
                             int max_cnt,
                             void (*callback) (rd_kafka_op_t *rko,
                                               void *opaque),
.....{

        while (!(rko = TAILQ_FIRST(&rkq->rkq_q)) && timeout_ms != 0 &&
               max_cnt-- > 0) {
                if (timeout_ms != RD_POLL_INFINITE) {
                        if (pthread_cond_timedwait_ms(&rkq->rkq_cond,
                                                      &rkq->rkq_lock,
                                                      timeout_ms) ==
                            ETIMEDOUT)
                                break;

                        timeout_ms = 0;

                } else
                        pthread_cond_wait(&rkq->rkq_cond,
                                          &rkq->rkq_lock);
        }

**Comment by rathdeep** [comment]
Works fine with master code. Thanks.

**Comment by edenhill** [comment]
That's excellent news.
