### ISSUE TITLE
StoreOffset on consumer with Assign() no longer auto committed in 1.7.0

### ISSUE THREAD

**Issue by ulbodk** [edenhill/librdkafka#3420]
Description
===========
We are using librdkafka via the Confluent .NET Api. Up until 1.6.3 (with librdkafka 1.6.1) we have successfully been using `StoreOffset` on consumers with `Assign(topicPartition)` (and not `Subscribe()`). With 1.7.0 the stored offsets are no longer committed in the background. If we add an explicit call to `Commit()` after `StoreOffset` then they get committed.

Note, *problem is not* with the `SetOffsetsCommittedHandler`, we have verified that no commit are made on our Kafka cluster with 1.7.0.

How to reproduce
================
The following test code works with 1.6.1 but not 1.7.0:

```csharp
ConsumerConfig cfg = // default values
cfg.EnableAutoCommit = true;
cfg.AutoCommitIntervalMs = 1000;

AutoResetEvent committed = new AutoResetEvent(false);
var builder = new ConsumerBuilder<string, byte[]>(cfg)
	.SetOffsetsCommittedHandler((c, o) => committed.Set());

using (IConsumer<string, byte[]> con = builder.Build())
{
	// IMPORTANT: problem only when using Assign, not when using Subscribe()
	con.Assign(new Confluent.Kafka.TopicPartition(topic, 0));

	ConsumeResult<string, byte[]> msg = con.Consume(5000);
	Assert.NotNull(msg);

	con.StoreOffset(msg);

	for (int i=0; i<100; i++)
	{
		if (committed.WaitOne(100))
			return;
		con.Consume(1000);
	}

	throw new Exception("No commit!");
}
```

**Comment by edenhill** [comment]
Interesting, can you reproduce this with `Debug: "cgrp,topic"` and provide the logs?

**Comment by ulbodk** [comment]
Yes, please see attached log.

[librdkafka_log.txt](https://github.com/edenhill/librdkafka/files/6647926/librdkafka_log.txt)

**Comment by ulbodk** [comment]
Yes, please see attached file:

[librdkafka_log.txt](https://github.com/edenhill/librdkafka/files/6648009/librdkafka_log.txt)

**Comment by hallfox** [comment]
We can also replicate this issue with 1.7.0 using just the C API.

**Comment by hallfox** [comment]
From messing around with a debugger we're able to see that the commit gets stopped because the `rkcg_join_state` is always `RD_KAFKA_CGRP_JOIN_STATE_INIT` from [this commit](https://github.com/edenhill/librdkafka/commit/fee6b90c6c6568a9a65a8f39311f646060edb933#diff-f4be68d9a41906eb18b50bc6e4b96aa7fb94eb8e01c480718b2181bd913328abR3048). Working on producing a minimal reproducible example.

**Comment by edenhill** [comment]
The upcoming v1.9.0 release has a number of fixes for offset store, see https://github.com/edenhill/librdkafka/blob/master/CHANGELOG.md#upgrade-considerations
