### ISSUE TITLE
query_watermark call is not transaction-aware

### ISSUE THREAD

**Issue by charles-cooper** [edenhill/librdkafka#3423]
Description
===========
When using `rd_kafka_query_watermark_offsets` with a read_committed consumer I noticed that it was returning high watermark offsets which are too high in the presence of aborted transactions. This results in not being able to find out when a consumer has reached the Last Stable Offset. I assume this is due to the usage of OffsetRequest v1 at the protocol level (https://kafka.apache.org/protocol#The_Messages_ListOffsets) here:
https://github.com/edenhill/librdkafka/blob/c28fbbb45dd14be57e577c05515d1a4af8ac70ff/src/rdkafka_request.c#L566-L573

read_committed awareness was introduced for this request in v2. Meanwhile, v4 of the protocol introduced the last_stable_offset field into the response, so the client could be informed of both the high watermark and the last stable offset at the same time.

I am not sure what the compatibility requirements of this project are, so I'm not sure if it's feasible to upgrade protocol versions. But it seems pretty important to be able to have transaction-aware watermarks when using a transaction-aware client, and this issue could be fixed by simply upgrading the protocol version for this call.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v1.7.0
 - [x] Apache Kafka version: `2.7`
 - [x] librdkafka client configuration: `isolation.level: read_committed`
 - [x] Operating system: all

**Comment by edenhill** [comment]
Good find! Will fix.
