### ISSUE TITLE
example producer.c compile error

### ISSUE THREAD

**Issue by dhgokul** [edenhill/librdkafka#3424]
installed librdkafak by:
apt install librdkafka-dev

used example producer. c to produce a message

got an error on comiplation:

root@kafka-ssd5:/home/ubuntu# gcc producer.c
/tmp/ccuMxFiT.o: In function `dr_msg_cb':
kap.c:(.text+0x4e): undefined reference to `rd_kafka_err2str'
/tmp/ccuMxFiT.o: In function `main':
kap.c:(.text+0x123): undefined reference to `rd_kafka_conf_new'
kap.c:(.text+0x154): undefined reference to `rd_kafka_conf_set'
kap.c:(.text+0x19a): undefined reference to `rd_kafka_conf_set_dr_msg_cb'
kap.c:(.text+0x1ba): undefined reference to `rd_kafka_new'
kap.c:(.text+0x28f): undefined reference to `rd_kafka_poll'
kap.c:(.text+0x2e7): undefined reference to `rd_kafka_producev'
kap.c:(.text+0x307): undefined reference to `rd_kafka_err2str'
kap.c:(.text+0x34c): undefined reference to `rd_kafka_poll'
kap.c:(.text+0x38e): undefined reference to `rd_kafka_poll'
kap.c:(.text+0x3eb): undefined reference to `rd_kafka_flush'
kap.c:(.text+0x3fa): undefined reference to `rd_kafka_outq_len'
kap.c:(.text+0x40d): undefined reference to `rd_kafka_outq_len'
kap.c:(.text+0x439): undefined reference to `rd_kafka_destroy'
collect2: error: ld returned 1 exit status

**Comment by rolandyoung** [comment]
You need to tell gcc to link with the rdkafka library.
