### ISSUE TITLE
Observing Huge Consumer Lag 

### ISSUE THREAD

**Issue by vasundhara785** [edenhill/librdkafka#3427]
Description
===========
We are observing huge consumer lag on multiple partitions. Only an application restart helps. After restart, all queued messages are successfully received from the broker. Unfortunately we have this issue on production...!

After looking into the logs it seems that the request to get the message fails.

%5|1622789456.701|REQTMOUT|rdkafka#consumer-1| [thrd:sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/]: sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/0: Timed out FetchRequest in flight (after 11007ms, timeout #0)
%4|1622789456.701|REQTMOUT|rdkafka#consumer-1| [thrd:sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/]: sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1622789456.701|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/]: sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/0: 1 request(s) timed out: disconnect (average rtt 34.435ms) (after 11008ms in state UP)
{"level":"error","ts":1622789456.7015622,"msg":"Kafka error while Consuming ","error":"sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/0: 1 request(s) timed out: disconnect (average rtt 34.435ms) (after 11008ms in state UP)"}

{"level":"info","ts":1622804444.5437155,"msg":"CONSUMER STATISTICS LOG:  {\"TopLevel\":{\"msg_cnt\":0,\"msg_max\":0,\"rebalance_age\":95158557,\"rebalance_cnt\":163,\"rebalance_reason\":\"group is rebalancing\"},\"Brokers\":{\"sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/0\":{\"broker\":\"CI-egress-Tel-VOD192315.servicebus.windows.net:9093\"}},\"Topics\":{\"egress-3-26\":{\"Statistics\":{\"topic\":\"egress-3-26\"},\"Partitions\":{\"11\":{\"committed_offset\":428003,\"consumer_lag\":45544,\"partition\":\"11\"},\"12\":{\"committed_offset\":427457,\"consumer_lag\":45439,\"partition\":\"12\"},\"13\":{\"committed_offset\":427116,\"consumer_lag\":45796,\"partition\":\"13\"},\"14\":{\"committed_offset\":427399,\"consumer_lag\":45829,\"partition\":\"14\"},\"15\":{\"committed_offset\":427823,\"consumer_lag\":45386,\"partition\":\"15\"},\"16\":{\"committed_offset\":426903,\"consumer_lag\":45370,\"partition\":\"16\"},\"17\":{\"committed_offset\":427468,\"consumer_lag\":45763,\"partition\":\"17\"},\"18\":{\"committed_offset\":426586,\"consumer_lag\":46153,\"partition\":\"18\"},\"19\":{\"committed_offset\":425982,\"consumer_lag\":44840,\"partition\":\"19\"},\"20\":{\"committed_offset\":426724,\"consumer_lag\":45537,\"partition\":\"20\"},\"21\":{\"committed_offset\":427422,\"consumer_lag\":45866,\"partition\":\"21\"}}}}}"}

Above logs are continously occuring  until the application restart.

We have 32 partitions for the topic used and there are three applications consuming from same topic.

How to reproduce
================
I was not able to reliably reproduce the issue. We are using Microsoft Azure's event hub service and the consumer application is also hosted in azure. It is occurring intermittently.

Checklist
=========

 - [x] librdkafka go-client version (release number or git tag): `<1.5.2>`
 - [x] librdkafka client consumer configuration: `<    "queued.max.messages.kbytes.int": "1000000",
    "fetch.message.max.bytes.int": "1048576",
    "receive.message.max.bytes.int": "100000000",
    "max.partition.fetch.bytes.int": "1048576",
    "auto.offset.reset.string": "latest",
    "enable.auto.commit.boolean": "true",
    "auto.commit.interval.ms.int": "5000",
    "socket.keepalive.enable.boolean": "true",
    "metadata.max.age.ms.int": "900000",
    "session.timeout.ms.int": "30000",
    "heartbeat.interval.ms.int": "3000",
    "max.poll.interval.ms.int": "60000",
    "metadata.request.timeout.ms.int": "30000",
    "topic.metadata.refresh.interval.ms.int": "120000",
    "socket.timeout.ms.int": "10000",
    "fetch.wait.max.ms.int": "100",
    "statistics.interval.ms.int": "25000">`
 - [x] Operating system: `<Ubuntu 10.2 (x64)>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
   [kafka logs.txt](https://github.com/edenhill/librdkafka/files/6653432/kafka.logs.txt)
 - [x] Critical issue

**Comment by edenhill** [comment]
Recommend upgrading and reproducing on the latest version (v1.7.0).

I'd also avoid changing socket.timeout.ms, leave it at its default value.

**Comment by vasundhara785** [comment]
Even after upgrading the latest version still ale to observe consumer lag.


%5|1631956926.678|REQTMOUT|rdkafka#consumer-1| [thrd:sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/]: sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/0: Timed out FetchRequest in flight (after 10892ms, timeout #0)
%4|1631956926.678|REQTMOUT|rdkafka#consumer-1| [thrd:sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/]: sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1631956926.678|FAIL|rdkafka#consumer-1| [thrd:sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/]: sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/0: 1 request(s) timed out: disconnect (average rtt 20.955ms) (after 10893ms in state UP)
{"level":"error","ts":1631956926.678528,"msg":"Kafka error while Consuming ","error":"sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/0: 1 request(s) timed out: disconnect (average rtt 20.955ms) (after 10893ms in state UP)"}
{"level":"error","ts":1631956931.5893533,"msg":"CONSUMER STATISTICS LOG:  {\"TopLevel\":{\"msg_cnt\":0,\"msg_max\":0,\"rebalance_age\":94287897,\"rebalance_cnt\":49,\"rebalance_reason\":\"Consumer group session timed out (in join-state steady) after 30479 ms without a successful response from the group coordinator (broker 0, last error was Local: Timed out)\"},\"Brokers\":{\"sasl_ssl://CI-egress-Tel-VOD192315.servicebus.windows.net:9093/0\":{\"broker\":\"CI-egress-Tel-VOD192315.servicebus.windows.net:9093\"}},\"Topics\":{\"egress-3-28\":{\"Statistics\":{\"topic\":\"egress-3-28\"},\"Partitions\":{\"0\":{\"committed_offset\":2254291,\"consumer_lag\":4130,\"partition\":\"0\"},\"1\":{\"committed_offset\":2257145,\"consumer_lag\":4044,\"partition\":\"1\"},\"10\":{\"committed_offset\":2254458,\"consumer_lag\":3805,\"partition\":\"10\"},\"11\":{\"committed_offset\":2257218,\"consumer_lag\":4191,\"partition\":\"11\"},\"12\":{\"committed_offset\":2255254,\"consumer_lag\":3768,\"partition\":\"12\"},\"13\":{\"committed_offset\":2256639,\"consumer_lag\":4177,\"partition\":\"13\"},\"14\":{\"committed_offset\":2252983,\"consumer_lag\":3837,\"partition\":\"14\"},\"15\":{\"committed_offset\":2253947,\"consumer_lag\":4593,\"partition\":\"15\"},\"16\":{\"committed_offset\":2256075,\"consumer_lag\":3827,\"partition\":\"16\"},\"17\":{\"committed_offset\":2258205,\"consumer_lag\":4386,\"partition\":\"17\"},\"18\":{\"committed_offset\":2255376,\"consumer_lag\":4283,\"partition\":\"18\"},\"19\":{\"committed_offset\":2255694,\"consumer_lag\":4195,\"partition\":\"19\"},\"2\":{\"committed_offset\":2254594,\"consumer_lag\":4269,\"partition\":\"2\"},\"20\":{\"committed_offset\":2256541,\"consumer_lag\":4132,\"partition\":\"20\"},\"21\":{\"committed_offset\":2254236,\"consumer_lag\":4036,\"partition\":\"21\"},\"22\":{\"committed_offset\":2255765,\"consumer_lag\":4587,\"partition\":\"22\"},\"23\":{\"committed_offset\":2253521,\"consumer_lag\":4435,\"partition\":\"23\"},\"24\":{\"committed_offset\":2258441,\"consumer_lag\":4331,\"partition\":\"24\"},\"25\":{\"committed_offset\":2256665,\"consumer_lag\":4345,\"partition\":\"25\"},\"26\":{\"committed_offset\":2258217,\"consumer_lag\":3958,\"partition\":\"26\"},\"27\":{\"committed_offset\":2257786,\"consumer_lag\":4174,\"partition\":\"27\"},\"28\":{\"committed_offset\":2252741,\"consumer_lag\":3835,\"partition\":\"28\"},\"29\":{\"committed_offset\":2256738,\"consumer_lag\":4095,\"partition\":\"29\"},\"3\":{\"committed_offset\":2256448,\"consumer_lag\":3919,\"partition\":\"3\"},\"30\":{\"committed_offset\":2257122,\"consumer_lag\":4204,\"partition\":\"30\"},\"31\":{\"committed_offset\":2255810,\"consumer_lag\":4185,\"partition\":\"31\"},\"4\":{\"committed_offset\":2255468,\"consumer_lag\":3721,\"partition\":\"4\"},\"5\":{\"committed_offset\":2258385,\"consumer_lag\":4232,\"partition\":\"5\"},\"6\":{\"committed_offset\":2255247,\"consumer_lag\":3819,\"partition\":\"6\"},\"7\":{\"committed_offset\":2256253,\"consumer_lag\":4144,\"partition\":\"7\"},\"8\":{\"committed_offset\":2252765,\"consumer_lag\":4118,\"partition\":\"8\"},\"9\":{\"committed_offset\":2258981,\"consumer_lag\":4099,\"partition\":\"9\"}}}}}"}

Please suggest.

**Comment by edenhill** [comment]
The timeouts suggest that you seem to have connectivity issues, might be worthwhile to look into.
