### ISSUE TITLE
How can i change mini-batch size when i using tfio.experimental.streaming.KafkaBatchIODataset api?

### ISSUE THREAD

**Issue by TTian-vivo** [edenhill/librdkafka#3429]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

How can i change mini-batch size when i using tfio.experimental.streaming.KafkaBatchIODataset api? I increase the configuration params  tenfold  (batch.size、batch.num.messages、message.max.bytes)  simultaneously,but the mini batch size is still 1024.

**Comment by edenhill** [comment]
This might be more of a question for the TensorFlow community, and I'm not sure what you mean by mini batch size.

**Comment by TTian-vivo** [comment]
Oh, thanks for your reply, I pushed the issue in a wrong place!
