### ISSUE TITLE
rdkafka doesn't honor the same broker ID when moved to new host

### ISSUE THREAD

**Issue by liljenback** [edenhill/librdkafka#343]
If migrating an existing broker to a new host and re-using its broker ID (from the host that is decommissioned) rdkafka still remember the old host name broker ID combination even when it is no longer available (brought offline). The client does not start using the new host. This results in messages being lost for partitions that are reassigned to the new host. The Kafka documentation seems to hint that the clients should be able to start using the new host with the same ID without having to be restarted.

**Comment by edenhill** [comment]
By messages lost you mean they are succesfully produced to the old broker, right?

**Comment by liljenback** [comment]
Right, the messages will be produced to the old broker but in this case it's offline.

**Comment by edenhill** [comment]
Should be fixed now.

**Comment by edenhill** [comment]
If possible please try verifying on your end
