### ISSUE TITLE
Migrating to travis-ci.com

### ISSUE THREAD

**Issue by shahidhs-ibm** [edenhill/librdkafka#3432]
The travis-ci.org site will not run any new builds after June 15th, 2021. 
Do we have any plans to migrate the repository to travis-ci.com? This is important for architectures like s390x which have CI support through Travis only.

**Comment by shahidhs-ibm** [comment]
Any update? 
As per a statement in [this](https://blog.travis-ci.com/oss-announcement) blog, travis-ci.com is totally free for opensource projects.

**Comment by edenhill** [comment]
librdkafka is now migrated to travis-ci.com.  Thanks!

**Comment by shahidhs-ibm** [comment]
@edenhill Thank you
