### ISSUE TITLE
getaddrinf memory leak

### ISSUE THREAD

**Issue by qwcbeyond** [edenhill/librdkafka#3433]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
version:librdkafka 1.7.0
glibc version:2.12  in redhat 6.7
I found some memory leak where I set the  conf "bootstrap.servers" to some bad IP, to test the "QUEUE_FULL" scence.
I use valgrind-massif tool to compare the memory increase,found the memory always increasing by  this position:

rd_gfetaddrinfo (rdaddr.c line 187) .
 --getaddrinf(getaddrinfo.c:2385)
    ---gaih_inet(getaddrinfo.c:1213)
      ---malloc(malloc.c:3655)
        --arena_get2(arena.c:910)
           ---new_heap(arena.c:725)

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>
1.set bad "bootstrap.servers"
2.send msg
3.lib.so.6 version 2.12
4.redhat 6.7

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I've seen it to but I think it is part of the resolver cache, and not a leak per say.
