### ISSUE TITLE
Linking rdkafka leads to EINVAL when creating Pthread with stack size 16384

### ISSUE THREAD

**Issue by jigkoshti** [edenhill/librdkafka#3434]
Description
===========
I have an application that creates threads (Pthreads) with stack size 16384. As soon as I link rdkafka into my application, thread creation starts failing with code 22 (EINVAL).

**One thing to note here is that this happens as soon as I link rdkafka library into my application, EVEN IF I dont use any code from rdkafka in my application.**

How to reproduce
================
I have written a simple 30-lines code which can easily reproduce this issue. All this piece of code does is create a pthread with stack size 16384. The code is pasted below - 

**testThread.c ->**
```
#include <stdio.h> 
#include <stdlib.h> 
#include <pthread.h> 
  
void *myThreadFunc(void *vargp) 
{ 
    sleep(1); 
	return NULL; 
} 
   
int main() 
{ 
	int new_stacksize = 16384;
	
	pthread_t thrd; 
	pthread_attr_t attrs;
	pthread_attr_init(&attrs);
	pthread_attr_setstacksize(&attrs, new_stacksize);
	
	printf("\ncreating new thread with stacksize - %zd\n", new_stacksize); 
	int ret = pthread_create(&thrd, &attrs, myThreadFunc, NULL); 
	
	printf("pthread_create return code - %d\n", ret);
	
	if (ret == 0) {
		pthread_join(thrd, NULL); 
		printf("done \n"); 
	} else {
		printf("could not create new thread \n"); 
	}
	exit(0); 
}
```

### This works -
**Compile -** 
gcc testThread.c -o testThread -L. -lpthread

**Run -**
./testThread.c 

**Output -** 

> creating new thread with stacksize - 16384
> pthread_create return code - 0
> done

### This does NOT work -
**Compile - (this time linking with rdkafka)**
gcc testThread.c -o testThread -L. -lpthread **-lrdkafka**

**Run -** 
./testThread.c 

**Output -** 

> creating new thread with stacksize - 16384
> pthread_create return code - 22
> could not create new thread

Checklist
=========
 - [x] librdkafka version (release number or git tag): 1.7.0
 - [x] Apache Kafka version: Not applicable, since the issue occurs with mere linking with rdkafka
 - [x] librdkafka client configuration: Not applicable, since the issue occurs with mere linking with rdkafka
 - [x] Operating system: CentOS Linux release 7.3.1611
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: Not applicable, since the issue occurs with mere linking with rdkafka
 - [x] Provide broker log excerpts: Not applicable, since the issue occurs with mere linking with rdkafka
 - [x] Critical issue - Yes

**Comment by rolandyoung** [comment]
Have you tried reproducing this with the current release version (1.7.0) ?
Version 0.11.5 is very old.

**Comment by j4873** [comment]
Hi @rolandyoung, checked with latest version 1.7.0, same issue exists in the latest version too..

**Comment by edenhill** [comment]
Can't reproduce.
