### ISSUE TITLE
callback function can't work for cplusplus?

### ISSUE THREAD

**Issue by xiongdaofu** [edenhill/librdkafka#344]
i called the function  mpConsumer->consume_callback(mpTopic, miPartition, 1000, &_PlatConsumeCb, &miUseccb); and  _PlatConsumeCb is a member variable ，
this is definition.
````
PlatConsumeCb _PlatConsumeCb ; 
class PlatConsumeCb: public RdKafka::ConsumeCb
{
// 
}
````

but the callback function can't be work?

**Comment by edenhill** [comment]
Have a look at the example code to see how to construct a callback class:
https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.cpp#L150

**Comment by xiongdaofu** [comment]
i run the example exe "./rdkafka_example_cpp -P -" as a producer, and top the process, and the memory is increasing when no data is produced.
is there some memory lost ?

**Comment by edenhill** [comment]
Could you please provide your full command line?

**Comment by kodekarl** [comment]
Uhm, the issue mentions both "consumer callback" and running as a producer.
How much memory is the producer using, and how quickly does it rise? Does it level out after "some time", or keep rising?
I'm pretty confident that Valgrind is correct when it says that no blocks are lost - so everything is freed eventually. However, the process _might_ be holding on to "something" for longer than it needs to?

**Comment by edenhill** [comment]
ping @xiongdaofu : any updates on this?

**Comment by edenhill** [comment]
Reopen if still a problem.
