### ISSUE TITLE
Loopback connections

### ISSUE THREAD

**Issue by avsevolodov** [edenhill/librdkafka#3443]
I use confluent kafka dot net client version 1.6.3, with librdkafka.redist  version 1.6.1. 
I create producer,  after execution function "rd_kafka_new" librdkafka opens several loopback connections (ports 4xxxx) :
![image](https://user-images.githubusercontent.com/10231712/123764671-ac90d400-d8cd-11eb-87a8-e9b7f58c2206.png)

I need more information about this connections.

**Comment by edenhill** [comment]
These loopback connections are used on Windows to wake up broker threads that are currently blocking on IO so that they can wake up and read from a queue.
On Linux/Unix we use a pipe.

**Comment by avsevolodov** [comment]
Oh, thank you. 
1. Is there upper limit number of this connections? 
2. One connection per broker-partition? 
3. Are there any configuration parameters for this feature?
4.  I have a cluster with 3 nodes, 16 partitions per topic and my producer creates (after few days) a lot of loopback connections (about 100), why so much?

**Comment by ajbarb** [comment]
There are two loopback sockets used per broker object. In your case with one producer and 3 nodes you should see a maximum of 6 loopback ports.. How many client instances are running?

@edenhill, what's the reason behind using sockets for windows vs events?

**Comment by edenhill** [comment]
@ajbarb 
> what's the reason behind using sockets for windows vs events?

The IO dispatcher is fd-based, but it really should be Events-based on Windows. This is an outstanding task.

**Comment by edenhill** [comment]
The loopback connections are now gone.
