### ISSUE TITLE
Unable to read message with \n \n (New Lines) as one Message

### ISSUE THREAD

**Issue by ankush2394** [edenhill/librdkafka#3445]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description

Unable to read message with \n \n (New Lines) as one Message
We have an xml message with \n  in body tag , on reading the message via consumer, its getting truncated automatically

How to reproduce

INPUT to consumer is->

```
<message xml:lang='en' to='123' from='34' type='' id='' xmlns='jabber:client'><version xmlns='urn:xmpp:version' value='v3_14.29.002'/><markable xmlns='urn:xmpp:chat-markers:0'/><extras xmlns='urn:xmpp:extras' custom_reply='false' appkey='panamera' callRequested='false' countryId='' senderType='seller' categoryId='85' itemId='' dealerType=''/><text xmlns='urn:xmpp:type'/><body>9686468411
call time 9am to 7pm</body></message>
```

Reading Code in Consumer ->

```
const { value: msgValue, topic, offset, partition, } = msg;
Buffer.from(msgValue.data).toString('utf8');
```

OUTPUT is truncated to  ->

```
call time 9am to 7pm</body></message>
```
Expecting the complete xml stanza (original message)

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version 1.7.0
 - [x] Apache Kafka version: 0.11.0.2
 - [x] Operating system: Debian 9.0(stretch)
 - [x] Provide logs -> Truncates the original message from new line
 - [x] Critical Issue -> Yes

**Comment by edenhill** [comment]
librdkafka treats all message value/payload and keys as binary and does not inteprete or truncate them in any way based on their contents.
Make sure you pass the correct size to produce().
