### ISSUE TITLE
How can I check if advertised.listeners is defined in Kafka / zookeeper config ?

### ISSUE THREAD

**Issue by smichaut** [edenhill/librdkafka#3447]
Hi,
I have a C client which interacts with Kafka using librdkafka. When starting I perform a few check such as calling rd_kafka_metadata (that calls rd_kafka_broker_any_usable which checks that the given broker in my config are up)... 
When running in docker if I 'forget' to set the advertised listener variable (KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://<broker>:<port>) everything works well and I am able to catch the error.
But with Kubernetes, making a deployment (with image: lensesio/fast-data-dev) if I don't set KAFKA_ADVERTISED_HOST_NAME, I have no error, but the client hangs when trying to read data from Kafka without any errors... So the problem is hard to diagnose.

My goal is to be able to detect there is something missing in the configuration (i.e; since the advertised listener or host name variable hasn't been set, I assume something is missing in Kakfa/Zookeeper config) that will prevent to consume topic in a K8S environment. So my guess is to check if the advertised.listener properties (or any other property) is correctly set... How can I do this with librdkafka (or any other mean) ? 

Thanks for any suggestion/help

**Comment by edenhill** [comment]
You could try connecting with a client.
