### ISSUE TITLE
Producer with consistent_random and no key is never blacklisting under min isr partitions 

### ISSUE THREAD

**Issue by HerveRiviere** [edenhill/librdkafka#3452]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Producer emitting records in a random way (no key, consistent_random partitioner) is never blacklisting partitions that are under-min-isr and so it generates 

- potentially timed-out records
- potentially an important load on leader of such partition and a risk of full cluster down due to snowball effect in case of numerous clients and aggressive retry config.
Leaders of under min isr partitions can be quickly saturated of invalid produce request of librd kafka (as min.isr is not satisfied) -> broker starts to lag for it replica partitions  due to network io saturated -> more under min isr partitions on other leaders  -> more retries by clients -> the full cluster may eventually collapse (_this scenario happen in one of our production cluster and we need to stop biggest producer to be able to recover_)

Do you think, as under min isr partitions can stay dozen of minutes to many hours (typically a production outage), under min isr partitions can fall as "Waiting for active partition leader" ([https://github.com/edenhill/librdkafka/wiki/Producer-message-reliability](https://github.com/edenhill/librdkafka/wiki/Producer-message-reliability)) which seems to be a more reasonable way to treat such errors instead of just retrying ?

Or do you have configuration settings or patterns to reduce data loss and retries in such situation? I searched about it with no success.

NB : In the how to reproduce I experimented with under min isr and offline partitions to show the difference.

How to reproduce
================
Modify examples/producer.c to produce 6 round of 2 000 messages with a sleep of 1 sec between each round

Producer config 
`ack=-1, 
batch.num.messages=100,
partitioner=consistent_random,
message.timeout.ms=3000,
sticky.partitioning.linger.ms=10`

Cluster configuration, three brokers 1, 2, 3  **and broker 2 down**
```
Topic:min_isr_topic 	PartitionCount:3	ReplicationFactor:2	Configs:min.insync.replicas=2
	Topic: min_isr_topic	Partition: 0	Leader: 3	Replicas: 3,2	Isr: 3
	Topic: min_isr_topic	Partition: 1	Leader: 1	Replicas: 2,1	Isr: 2
	Topic: min_isr_topic	Partition: 2	Leader: 1	Replicas: 1,3	Isr: 1,3

Topic:offline_topic 	PartitionCount:3	ReplicationFactor:1	Configs:min.insync.replicas=1
	Topic: offline_topic	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
	Topic: offline_topic	Partition: 1	Leader: none	Replicas: 2	Isr: 
	Topic: offline_topic	Partition: 2	Leader: none	Replicas: 2	Isr: 
```

```
examples/producer kafka:9092 min_isr_topic | grep delivered | wc -l
# On 3 run 4000 / 6000 or 8000 messages delivered on a total of 12 000 

examples/producer kafka:9092 offline_topic | grep delivered | wc -l
# On 3 runs 11 996 / 11 995 / 11991 messages delivered 
```

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
 - [x] librdkafka version :`v1.7.0`
 - [x] Apache Kafka version: `2.3.1`
 - [x] librdkafka client configuration: `ack=-1, batch.num.messages=100, partitioner=consistent_random, message.timeout.ms=3000, sticky.partitioning.linger.ms=10`
 - [x] Operating system: `MacOs BigSur`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It is not the producer's responsibility to enforce min.isr, that's the brokers.
