### ISSUE TITLE
statistics.interval.ms documentation clarification

### ISSUE THREAD

**Issue by elindsey** [edenhill/librdkafka#3453]
Hello! The[ configuration documentation](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) for statistics.interval.ms reads:

> librdkafka statistics emit interval. The application also needs to register a stats callback using rd_kafka_conf_set_stats_cb(). The granularity is 1000ms. A value of 0 disables statistics. 

I'm having trouble understanding what "the granularity is 1000ms" means in this context. Looking at the code this appears to have 1ms/1000us granularity in triggering the emit stats callback:
https://github.com/edenhill/librdkafka/blob/77a013b7a2611f7bdc091afa1e56b1a46d1c52f5/src/rdkafka.c#L2033

And it appears to have had that granularity since introduction ~8 years ago (https://github.com/edenhill/librdkafka/commit/ce7b6838a19265712a2eda42c6a5a18ae2da1dcf).

Am I misunderstanding what granularity it's referring to?

**Comment by edenhill** [comment]
Your understanding is correct, and I'm not really sure why that granularity thing is in the docs, but it does give us some wiggle room for future changes, so let's just assume that the granularity is actually a thing.
