### ISSUE TITLE
librdkafka fails to do TLS hostname validation

### ISSUE THREAD

**Issue by kurtostfeld** [edenhill/librdkafka#3462]
Description
===========
librdkafka fails to do TLS hostname validation. I have a Kafka Cluster that was incorrectly configured with X.509 certificates that don't match the hostnames. The main security protection of TLS is hostname validation. A TLS client should detect the problem and fail.

JVM based clients including the kafka-console-consumer.sh that comes with the Apache Kafka download correctly fail the hostname validation and produce the desired error.

librdkafka based clients including kafkacat incorrectly bypass hostname validation, bypass the security provided by TLS, and work anyway, possibly with servers that aren't who they claim to be.

How to reproduce
================

(redacted employer details)

This fails to do hostname validation and (incorrectly) shows messages. Golang applications based on librdkafka exhibit similar behavior.

```bash
kafkacat -b kafka-bootstrap.company.com:443 -X security.protocol=SSL -C -t my-topic -o beginning -c 3
```

JVM clients correctly detect the TLS problem and exhibit desired behavior of erroring out. Here I'm using the shell script that comes with the Apache Kafka binary download, but any JVM based client exhibits similar behavior:

```bash
bin/kafka-console-consumer.sh \
    --bootstrap-server kafka-bootstrap.company.com:443 \
    --topic my-topic \
    --consumer-property security.protocol=SSL \
    --max-messages 3

(snip)
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching kafka-broker-2.company.com found.
```

We can also confirm the TLS hostname problem with curl, even though Kafka brokers aren't http based:

This validates:

```bash
curl -v https://kafka-bootstrap.company.com
(snip)
*  SSL certificate verify ok.
```

This fails SSL/TLS validation:

```bash
curl -v https://kafka-broker-0.company.com
(snip)
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Checklist
=========

Please provide the following information:

 - [x] librdkafka version: 1.6.0 + 1.7.0
 - [x] Apache Kafka version: 2.8.0
 - [x] librdkafka client configuration: (shown above)
 - [x] Operating system: client MacOS and/or Linux. Server Linux
 - [x] Provide logs (shown above)
 - [x] Provide broker log excerpts (N/A)
 - [x] Critical issue

**Comment by edenhill** [comment]
You need to set ssl.endpoint.identification.algorithm=https
