### ISSUE TITLE
Upgrade zstd in NuGet package

### ISSUE THREAD

**Issue by mausch** [edenhill/librdkafka#3463]
Description
===========
I'm getting "invalid compressed data" errors reading from a Kafka topic with https://www.nuget.org/packages/Confluent.Kafka/1.7.0 for some messages produced https://www.nuget.org/packages/Confluent.Kafka/1.6.3 .

According to https://github.com/edenhill/librdkafka/issues/2672 this is because of an issue in zstd.

And according to https://github.com/edenhill/librdkafka/issues/2672#issuecomment-882219508 the version of zstd used in https://www.nuget.org/packages/librdkafka.redist/1.7.0 is rather old.

So this should probably be updated?

How to reproduce
================
Honestly I've not been able to figure out what data exactly causes this error :confused: 
Some messages are read fine, some others crash with this error...

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.7.0
 - [ ] Apache Kafka version: I don't think it matters here?
 - [ ] librdkafka client configuration: I don't think it matters here?
 - [ ] Operating system: I don't think it matters here?
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by taspeotis** [comment]
Hi, thanks for taking a look at this. Having a very quick look through the repo version 1.3.8 is defined in two places: [`configure.libzstd`](https://github.com/edenhill/librdkafka/blob/889b4d779c35e2cd60b8af3aa87ee88b9159b3e0/mklove/modules/configure.libzstd#L45) for *nix and the `vcxproj` (sorry I have lost the link) for Windows.

**Comment by edenhill** [comment]
We're now using vcpkgs, so this should be fine now.
