### ISSUE TITLE
fcntl called incorrectly for setting FD_CLOEXEC

### ISSUE THREAD

**Issue by rittneje** [edenhill/librdkafka#3467]
https://github.com/edenhill/librdkafka/blob/55ad6101ac80a9ba09b802eab1c4dbf484245004/src/rdkafka_broker.c#L1969-L1983

`fcntl` only takes three parameters, not four. (Since `fcntl` was defined as variadic, the compiler doesn't warn about this and the extra parameter is ignored.) Also, this is technically unsafe, since if another FD flag gets added in the future, this would clobber it.

This is the correct way to set `FD_CLOEXEC`.
```c
int flags = fcntl(fd, F_GETFD);
if (flags < 0) {
    return -1;
}
return fcntl(fd, F_SETFD, flags | FD_CLOEXEC)
```

See https://man7.org/linux/man-pages/man2/fcntl.2.html.

To be clear, the current code works, but only by chance.

**Comment by rittneje** [comment]
ping @edenhill

**Comment by edenhill** [comment]
Thanks for identifying this issue!
