### ISSUE TITLE
DeleteRecords can crash on empty partial response

### ISSUE THREAD

**Issue by chrisbeard** [edenhill/librdkafka#3476]
Description
===========
It appears that DeleteRecords can crash when a broker shuts down mid-request.

We only observe this happening as of `v1.7.0` with an rdkafka client that tunnels connections to the Kafka cluster through an HTTP proxy. The rdkafka client tunnels through an HTTP proxy using the [CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) method via the connect callback. When brokers turn without the proxy, we see no issue. We'd previously been using `v1.6.0` and `v1.6.1` with no issue.

I fully admit, this setup is strange and may very well be to blame, or at least may be causing things to fail in a strange way that librdkafka would otherwise handle gracefully (without the HTTP proxy in the picture).

Here's the walkback from our coredump:
```
#0  rd_kafka_DeleteRecords_response_merge (rko_fanout=0x7fd528006ca0,  
    rko_partial=<optimized out>) at rdkafka_admin.c:3267 
#1  0x0000000000882b01 in rd_kafka_admin_fanout_worker (rk=0x7fd52800fd80,  
    rkq=<optimized out>, rko=0x7fd468009290) at rdkafka_admin.c:1268 
#2  0x0000000000814f44 in rd_kafka_op_call (rk=<optimized out>,  
    rkq=<optimized out>, rko=0x7fd468009290) at rdkafka_op.c:689 
#3  0x0000000000816268 in rd_kafka_op_handle (rk=0x7fd52800fd80,  
    rkq=0x7fd543ffb210, rko=0x7fd468009290, cb_type=RD_KAFKA_Q_CB_CALLBACK,  
    opaque=0x7fd52800fd80, callback=0x7d7110 <rd_kafka_poll_cb>) 
    at rdkafka_op.c:859 
#4  0x000000000080b455 in rd_kafka_q_serve (rkq=0x7fd528006830,  
    timeout_ms=<optimized out>, max_cnt=max_cnt@entry=0,  
    cb_type=cb_type@entry=RD_KAFKA_Q_CB_CALLBACK,  
    callback=callback@entry=0x0, opaque=opaque@entry=0x0) 
    at rdkafka_queue.c:507 
#5  0x00000000007d6884 in rd_kafka_thread_main (arg=arg@entry=0x7fd52800fd80) 
    at rdkafka.c:2079 
#6  0x0000000000860fb7 in _thrd_wrapper_function (aArg=<optimized out>) 
    at tinycthread.c:576 
#7  0x00007fd56fa11dd5 in start_thread () from /usr/lib64/libpthread.so.0 
#8  0x00007fd56ef1c02d in clone () from /usr/lib64/libc.so.6 
```
`rdkafka_admin.c:3267` points [here](https://github.com/edenhill/librdkafka/blob/v1.7.0/src/rdkafka_admin.c#L3267). This segfaults because `partitions` is null.

After noticing the WARN/ERROR logs, I added a few additional logs (I don't have full debug logs right now). I've reproduced this using sasl_plaintext as noted below, but nothing I've seen suggests sasl is related or to blame, it's just the config I tested with.
```
21JUL2021_21:42:14.592 139789711705856 INFO  calling DeleteRecords topic=test-topic partitions=[0,1,2,3]
21JUL2021_21:42:14.598 139789184476928 INFO  connectCallback()
21JUL2021_21:42:14.598 139789184476928 INFO  Connecting via broker proxy.myproxy.com:1234
21JUL2021_21:42:14.618 139789184476928 INFO  connectCallback()
21JUL2021_21:42:14.618 139789184476928 INFO  Connecting via broker proxy.myproxy.com:1234
21JUL2021_21:42:14.625 139788279600896 INFO  connectCallback()
21JUL2021_21:42:14.625 139788279600896 INFO  Connecting via broker proxy.myproxy.com:1234
21JUL2021_21:42:14.625 139788290090752 INFO  connectCallback()
21JUL2021_21:42:14.625 139788290090752 INFO  Connecting via broker proxy.myproxy.com:1234
21JUL2021_21:42:14.630 139789205456640 INFO  RDKAFKA[rdkafka#producer-64 :: DELETERECORDS] [thrd:main]: DeleteRecords partial response has valid results
21JUL2021_21:42:14.630 139789205456640 INFO  RDKAFKA[rdkafka#producer-64 :: DELETERECORDS] [thrd:main]: DeleteRecords response contains  [1] elements
21JUL2021_21:43:14.679 139788279600896 WARN  RDKAFKA[rdkafka#producer-64 :: REQTMOUT] [thrd:sasl_plaintext://kafka-box:9093/1]: sasl_plaintext://kafka-box:9093/1: Timed out DeleteRecordsRequest in flight (after 60049ms, timeout #0)
21JUL2021_21:43:14.679 139788279600896 WARN  RDKAFKA[rdkafka#producer-64 :: REQTMOUT] [thrd:sasl_plaintext://kafka-box:9093/1]: sasl_plaintext://kafka-box:9093/1: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
21JUL2021_21:43:14.679 139789205456640 INFO  RDKAFKA[rdkafka#producer-64 :: DELETERECORDS] [thrd:main]: DeleteRecords partial response has an error
21JUL2021_21:43:14.679 139788279600896 ERROR RDKAFKA[rdkafka#producer-64 :: FAIL] [thrd:sasl_plaintext://kafka-box:9093/1]: sasl_plaintext://kafka-box:9093/1: 1 request(s) timed out: disconnect (after 60050ms in state UP)
```
This ~60s timeout corresponds to the default for `socket.timeout.ms`, which serves as the default timeout for admin network requests according to `CONFIGURATION.md`.

It looks like when the connection times out (because broker shutdown has severed the proxy -> broker connection), `rd_kafka_DeleteRecords_response_merge` doesn't gracefully handle the error. This is made clearer when the logic is compared to `rd_kafka_DeleteGroups_response_merge`, which checks if the given `rko_partial` has an error [[source](https://github.com/edenhill/librdkafka/blob/v1.7.0/src/rdkafka_admin.c#L3662-L3686)].

At minimum, a patch like the following seems reasonable to at least prevent a segfault: https://github.com/chrisbeard/librdkafka/commit/ca94570aa1cea9b05aa309a5b2e09c774332c963

I'm happy to send this patch over if what I've outlined above is reasonable.

How to reproduce
================
I'll outline the high-level of what I've done to reproduce, but don't have a code sample that's sharable. I don't expect anyone to actually attempt to reproduce this, but the steps might be helpful regardless.
1. Start a Kafka broker, create a topic
2. Start an HTTP proxy
3. In a tight loop, call delete records on one or more partitions in the topic, tunneling all requests through the http proxy
4. Kill brokers leading the partitions from (3)
5. At some point, a request will hang and you'll see trace like shown above

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.7.0`
 - [x] Apache Kafka version: `2.5.1`
 - [x] librdkafka client configuration: all defaults (& sasl configs, though I don't think that's relevant)
 - [x] Operating system: `RHEL 7.6`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ZMZ91** [comment]
Hi there, I've met similar crashes as in the coredump. I saw the pr is about ready. So is there a timeline when to merge the fix? Thank you.

**Comment by edenhill** [comment]
Great analysis, Chris!
