### ISSUE TITLE
librdkafka version 0.11.4 compatible with Kafka Broker version

### ISSUE THREAD

**Issue by karthikeyanajendran1984** [edenhill/librdkafka#3479]
Hi Experts,

We have started our development of Producer and Consumer using librdkafa 0.11.4 and we used Kafka Broker version 0.11.00.

Now customer starts upgrading Kafka Broker version from 0.11.00 to 2.5 and to 2.7. We have still used the librdkafka version 0.11.4.

I would like to know is there any documentation I can find like 
1) what are the features and configuration options supported in librdkafka 0.11.4 
2) How this features and configuration options compatible with latest Kafka broker version ?
3) Is it recommended to upgrade librdkafka version to latest Kafka broker version ?

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (librdkafka 0.11.4)
 - [x] Apache Kafka version:  0.11.00, 2.5, 2.7
 - [ ] librdkafka client configuration: 
 - [x] Operating system: Linux x86_64
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka - Not applicable
 - [ ] Provide broker log excerpts - Not applicable
 - [ ] Critical issue - Not applicable

Regards,
Karthikeyan Rajendran.

**Comment by karthikeyanajendran1984** [comment]
Hi Experts / @edenhill,
Could you please guide on this ? 

Regards,
Karthikeyan Rajendran.

**Comment by rolandyoung** [comment]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ, especially https://github.com/edenhill/librdkafka/wiki/FAQ#what-version-should-i-use
 
In short: you should use the current version (1.7) of librdkafka if you require free support.
