### ISSUE TITLE
No errors or warnings when a topic does not exist and auto-create is off

### ISSUE THREAD

**Issue by skandragon** [edenhill/librdkafka#348]
```
./rdkafka_example -b "broker-01:9092" -t flarg -p 0
```

My application also behaves the same way.  Ideally, an error should be presented in some way to indicate this configuration is bogus.

**Comment by edenhill** [comment]
Good point.
This will be propagated asynchronously, meaning:
 * consumer: returns rkmessage->err with UNKNOWN_TOPIC
 * producer: if produce() is called before internal metadata fetch is complete: dr_cb with err==UNKNOWN_TOPIC
 * producer: if produce() is called after internal metadata fetch is complete: will fail immediately and return err==UNKNOWN_TOPIC

**Comment by skandragon** [comment]
Is that how it happens now, or how it will happen with a fix?

**Comment by edenhill** [comment]
This is how it will happen very soon.

**Comment by edenhill** [comment]
Or well, the producer behaviour is already like this, only the consumer needs adjusting.

**Comment by edenhill** [comment]
There, that should do it. Please verify on your end too.
