### ISSUE TITLE
When is a consumer expected to be successfully subscribed to the topics ?

### ISSUE THREAD

**Issue by dshivashankar1994** [edenhill/librdkafka#3480]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
I need to send a notification to a system from consumer saying that it has been successfully subscribed to the set of topics. I wanted to use the latest offset.

I don't think subscribe is a synchronous call and it would simply return control back and tries to subscribe internally. I also don't think I can override the RebalanceCb too as the assign call also tries to actually assign the partitions asynchronous manner internally.

Is there a way I can be sure that my consumer is successfully subscribed so that it will receive all the messages that are created after that instace ?

**Comment by dshivashankar1994** [comment]
Hi, Any updates here ?

**Comment by dshivashankar1994** [comment]
Hi @edenhill , Any updates here ?

**Comment by edenhill** [comment]
You will need to provide your own Rebalance callback to be notified of when partitions are assigned (or revoked).
All you need to do in the callback itself is call assign() according to the event type (assign or revoke). See the examples directory

**Comment by dshivashankar1994** [comment]
Hi, I am having my custom RebalanceCallback and the assign call passes the logical offset - LATEST. But even the assign call doesn't seem to be synchronous. I added a print statement after assign call in RebalanceCb. The statement got printed and only after that I could see that the actual latest offset is fetched and then the proper assigning take place. So I cannot consider that by the end of  execution of assign the topics will be subscribed.

All I want is a deterministic time at which the topics are subscribed and post that I can be sure that the messages published after this time will be received by my consumer.

**Comment by dshivashankar1994** [comment]
Ping for above

**Comment by dshivashankar1994** [comment]
Ping for above

**Comment by edenhill** [comment]
assign() is indeed asynchronous as it will need to look up leaders, logical offsets, etc, before it can start fetching, and we wouldn't want to block until all partitions have started fetching, since that could be a long time (if ever) if some leaders are down.

**Comment by edenhill** [comment]
What you can do is set enable.partition.eof=true, keep track of which partitions you have assign()ed, and then flag each partition as "done" when you have received at least one message, a PARTITION_EOF, or an error, for the given partition.

**Comment by dshivashankar1994** [comment]
Ping for above

**Comment by edenhill** [comment]
I think waiting for a message or PARTITION_EOF is your best bet. A callback would be pretty much the same thing.
