### ISSUE TITLE
Segmentation fault in rd_kafka_transport_ssl_connect() when try to consume data

### ISSUE THREAD

**Issue by wonderdong** [edenhill/librdkafka#3483]
Description
===========
I developed an application in C++ to consume data from Kafka cluster based on Librdkafka, it got segmentation fault. But kafkacat can consume fine.

How to reproduce
================
1. the C++ application is similar as example in "librdkafka/examples/rdkafka_example.cpp"
2. built and link the application with archive from kafkacat's compile output "./tmp-bootstrap/librdkafka/src/librdkafka.a, ./tmp-bootstrap/librdkafka/src-cpp/librdkafka++.a"
3. run the application with config like:
   "kafka_config":{
       "security.protocol": "SASL_SSL",
       "ssl.ca.location":"/path/to/kerberos_kafka/ca-root.crt",
       "sasl.kerberos.service.name":"kafka",
       "sasl.kerberos.principal": "kafka-producer@ABC.COM",
       "sasl.kerberos.keytab": "/path/to/kerberos_kafka/kafka-producer.keytab"
   }
4. run the application get segmentation fault:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff117fa700 (LWP 93093)]
0x0000000001b53265 in bssl::ssl_cert_dup(bssl::CERT*) ()
(gdb) bt
#0  0x0000000001b53265 in bssl::ssl_cert_dup(bssl::CERT*) ()
#1  0x0000000001b0bc24 in SSL_new ()
#2  0x00000000017f4589 in rd_kafka_transport_ssl_connect (rkb=rkb@entry=0x312ba70, rktrans=rktrans@entry=0x7ffefc000a70, errstr=errstr@entry=0x7fff117f3560 "",
    errstr_size=errstr_size@entry=512) at rdkafka_ssl.c:502
#3  0x000000000172664b in rd_kafka_transport_connected (rktrans=0x7ffefc000a70) at rdkafka_transport.c:622
#4  rd_kafka_transport_io_event (rktrans=rktrans@entry=0x7ffefc000a70, events=events@entry=4) at rdkafka_transport.c:700
#5  0x0000000001727133 in rd_kafka_transport_io_serve (rktrans=0x7ffefc000a70, timeout_ms=1000) at rdkafka_transport.c:818
#6  0x000000000170f451 in rd_kafka_broker_ops_io_serve (rkb=rkb@entry=0x312ba70, abs_timeout=<optimized out>) at rdkafka_broker.c:3425
#7  0x000000000170f8b0 in rd_kafka_broker_consumer_serve (rkb=rkb@entry=0x312ba70, abs_timeout=abs_timeout@entry=14594077736) at rdkafka_broker.c:5023
#8  0x0000000001710f7b in rd_kafka_broker_serve (rkb=rkb@entry=0x312ba70, timeout_ms=<optimized out>, timeout_ms@entry=1000) at rdkafka_broker.c:5166
#9  0x000000000171139d in rd_kafka_broker_thread_main (arg=arg@entry=0x312ba70) at rdkafka_broker.c:5313
#10 0x0000000001786577 in _thrd_wrapper_function (aArg=<optimized out>) at tinycthread.c:576
#11 0x00007ffff2a42ea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007ffff1b3f9fd in clone () from /lib64/libc.so.6
(gdb)
```

NOTE:
The kafkacat built with the same librdkafka (1.7.0) works fine, as:
```
kafkacat -C -b kafka-0.abc.com:9092 -X security.protocol=SASL_SSL \
             -X sasl.kerberos.keytab=kafka-producer.keytab \
             -X sasl.kerberos.principal=kafka-producer@ABC.COM \
             -X ssl.ca.location=ca-root.crt -t kafka-test
```

Question:
Why the kafkacat can consume data, while the application built with same archive librdkafka.a and librdkafka++.a (which are built by kafkacat/bootstrap.sh) got segmenation fault?

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.7.0`
 - [x] Apache Kafka version: `kafka_2.11-2.1.1`
 - [x] librdkafka client configuration: `       "security.protocol": "SASL_SSL",
       "ssl.ca.location":"/path/to/kerberos_kafka/ca-root.crt",
       "sasl.kerberos.service.name":"kafka",
       "sasl.kerberos.principal": "kafka-producer@ABC.COM",
       "sasl.kerberos.keytab": "/path/to/kerberos_kafka/kafka-producer.keytab"`
 - [x] Operating system: `Centos 7.9 (x64)`
 - [x] Openssl version: `1.0.2k`

**Comment by edenhill** [comment]
Seems like you are using BoringSSL, so I'd start looking there.
While BoringSSL may work, it is not a setup we support.

**Comment by rolandyoung** [comment]
If you link your code against BoringSSL and build librdkafka with openSSL, you will get all kinds of problems, because they define the same symbols in the global namespace. For example, it is quite likely that at most one will be initialised correctly. If you try to build librdkafka against BoringSSL, you may or may not succeed, but, as Magnus says, that is not supported here.
