### ISSUE TITLE
rd_kafka_consume_batch() returns 0 on timeout?

### ISSUE THREAD

**Issue by donatello** [edenhill/librdkafka#349]
Though the [header file's comments](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L787) say that -1 is returned on error, it does not seem to be the case looking at the implementation [here](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L1503) and [here](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L523-L579) - when there are no available messages, it appears that this function returns 0. Is this correct?

I believe this may be related to an issue in the [Haskell binding for Kafka](https://github.com/cosbynator/haskakafka/issues/12) - thus the question. Thanks in advance!

**Comment by edenhill** [comment]
Ah yes, you're correct, the documentation is a bit unclear. Timeouts are not considered hard errors and are thus not reported as such.
For consume() this means the returned rkmessage object has .err set to TIMED_OUT while for consume_batch() it simply returns 0 - i.e., no messages were put in message array.

**Comment by edenhill** [comment]
Alleviated here: d75ff4639e07346b0a6d8332c5fcde2910511caf

**Comment by donatello** [comment]
Thank you for the quick response!
