### ISSUE TITLE
How to set the kafka consumer to limit consuming certain records per second ?

### ISSUE THREAD

**Issue by neha2007** [edenhill/librdkafka#3495]
Description
===========
I have implemented kafkaConsumer in my application. When this application is down, the other appication which is producing the data will keep on writing the data to Kafka. So when the application with consumer is UP again, it will start consuming at a very high rate, but this application can not handle such high traffic. So is there any way we can limit the consumer to consume the data at lower rate?

How to reproduce
================
Not an issue, just a query

**Comment by neha2007** [comment]
@edenhill

**Comment by edenhill** [comment]
Your application decides what rate it wants new messages by how often it calls consumer_poll().
If messages can be fetched from the broker faster than the application reads them then eventually the internal fetchq fills up and fetching stops until the threshold is no longer exceeded - this is all abstracted and not something the application needs to worry about.

You can configure the pre-fetch queue sizes with `queued.max.messages.kbytes` which defaults to 64 MB.

**Comment by neha2007** [comment]
Thanks @edenhill 

Could you please also let me know if it is possible to configure below kafka parameters using librdkafka?

- replica.high.watermark.checkpoint.interval.ms 
- num.replica.fetchers
- num.io.threads

**Comment by edenhill** [comment]
Those are broker-side config properties, so you would need to use the rd_kafka_AlterConfigs() API.
