### ISSUE TITLE
Observing Session Timeouts 

### ISSUE THREAD

**Issue by vasundhara785** [edenhill/librdkafka#3500]
Description
===========
We are observing continuous SESSTMOUTs. 

After looking into the logs it seems that the request is getting timedout.

How to reproduce
================
I was not able to reliably reproduce the issue. We are using Microsoft Azure's event hub service and the consumer application is also hosted in azure. It is occurring intermittently.

Checklist
=========

 - [x] librdkafka go-client version (release number or git tag): `<1.5.2>`
 - [x] librdkafka client consumer configuration: `<    "queued.max.messages.kbytes.int": "1000000",
    "fetch.message.max.bytes.int": "1048576",
    "receive.message.max.bytes.int": "100000000",
    "max.partition.fetch.bytes.int": "1048576",
    "auto.offset.reset.string": "latest",
    "enable.auto.commit.boolean": "true",
    "auto.commit.interval.ms.int": "5000",
    "socket.keepalive.enable.boolean": "true",
    "metadata.max.age.ms.int": "900000",
    "session.timeout.ms.int": "30000",
    "heartbeat.interval.ms.int": "3000",
    "max.poll.interval.ms.int": "60000",
    "metadata.request.timeout.ms.int": "30000",
    "topic.metadata.refresh.interval.ms.int": "120000",
    "socket.timeout.ms.int": "10000",
    "fetch.wait.max.ms.int": "100",
    "statistics.interval.ms.int": "25000">`
 - [x] Operating system: `<Ubuntu 10.2 (x64)>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
[query_data (2).csv](https://github.com/edenhill/librdkafka/files/6982103/query_data.2.csv)

 - [x] Critical issue

**Comment by edenhill** [comment]
Try reproducing on the latest version, v.1.7.0. There's been several improvements to the consumer since v1.5.2

**Comment by vasundhara785** [comment]
Thanks @edenhill will update the version and try to reproduce.
