### ISSUE TITLE
No offset stored

### ISSUE THREAD

**Issue by leileileileilei1** [edenhill/librdkafka#3504]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
hi edenhill:
we have a question for you.
The C++ client version is 1.0.0, and the Kafka version on the server is kafka_2.11-2.2.1. When the data volume exceeds 3 million, the client reports the error rd_kafka_commit Local: No offset stored.
Have similar problems been resolved in the latest librdkafka.a client version?
If the client version is upgraded to 1.7.0, are there any requirements on the server version?
thanks

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>
The C++ client version is 1.0.0, and the Kafka version on the server is kafka_2.11-2.2.1. When the data volume exceeds 3 million

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [1.0.0] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [kafka_2.11-2.2.1 ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Both the broker and clients are backwards and forwards compatible, so there is no issue upgrading to 1.7.0

**Comment by leileileileilei1** [comment]
Have the following problems been fixed?

When the data volume exceeds 3 million, the client reports the error rd_kafka_commit Local: No offset stored

**Comment by leileileileilei1** [comment]
Have the following problems been fixed?

When the data volume exceeds 3 million, the client reports the error rd_kafka_commit Local: No offset stored

**Comment by edenhill** [comment]
That just means there has been no update to the stored offset and that stored offset >= committed offset.
