### ISSUE TITLE
Question: Insights into producer batching?

### ISSUE THREAD

**Issue by HenningRoigaard** [edenhill/librdkafka#3509]
Is it possible to get insights into how effective batching is when producing? 

We would like to know how many messages are in a record batch, and if possible, how effective compression is.
Is there any way to get this kind of information?

It would be a plus if we could inspect the messages and their headers. This could be as simple as dumping the serialized record batch or getting access to the producer’s buffers.

This is purely for use during development/testing, so setting debug flags and performance hits etc. is acceptable.

We use the C# client, but I expect that if this is possible, it must come from librdkafka.

**Comment by edenhill** [comment]
librdkafka statistics have some metrics on batch sizes, the `batchsize` and `batchcnt` topic metrics:
https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md#topics
`batchsize` is a histogram of the number of bytes per batch, and `batchcnt` is a histogram of the number of messages per batch.

We're also working on streaming compression which will vastly improve the compression ratio and increase the number of messages in a batch, it will come with a compression ratio metric.
You can try it out on the [streamingcompr](https://github.com/edenhill/librdkafka/tree/streamingcompr) branch.

**Comment by HenningRoigaard** [comment]
This looks exactly like what I am looking for, and it it usable from the C# client.
