### ISSUE TITLE
Look up the offsets for the given partitions by timestamp

### ISSUE THREAD

**Issue by zhiming0228** [edenhill/librdkafka#3511]
Description
===========
Can we consume from some given timestamp in C++ librdkafka?  I know we can use offsetsForTimes () to get offset and
there is a create() function in the TopicPartition  class (TopicPartition *create (const std::string &topic, int partition,int64_t offset);).
But how can we input the specified timestamp? use offsets as timestamp? If it is, I want to know why; if not, I want to know how to specify a timestamp to consume,Thank you!

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [ ] librdkafka version (release number or git tag): v1.7.0
 - [ ] Apache Kafka version: 0.10.0

**Comment by edenhill** [comment]
Call OffsetsForTimes() where the .offset field represents the timestamp (milliseconds epoch) on input and the earliest offset for the given timestamp on output.
Then call assign() to start consuming the given partitions at those offsets.

**Comment by zhiming0228** [comment]
> Call OffsetsForTimes() where the .offset field represents the timestamp (milliseconds epoch) on input and the earliest offset for the given timestamp on output.
> Then call assign() to start consuming the given partitions at those offsets.

Yes, I succeeded according to what you said, thank you very much

**Comment by zhiming0228** [comment]
> Call OffsetsForTimes() where the .offset field represents the timestamp (milliseconds epoch) on input and the earliest offset for the given timestamp on output.
> Then call assign() to start consuming the given partitions at those offsets.

**Comment by tigerinus** [comment]
> Call OffsetsForTimes() where the .offset field represents the timestamp (milliseconds epoch) on input and the earliest offset for the given timestamp on output.

Could it be possible that an offset happens to look like a epoch timestamp?
