### ISSUE TITLE
Compile librdkafka for android with sasl support

### ISSUE THREAD

**Issue by manang** [edenhill/librdkafka#3515]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========

Hi, I'm trying to use librdkafka on Android and I obtain this error:
(kafka::LogBuffer<1024>) $0 = (_wptr = "No provider for SASL mechanism SCRAM-SHA-256: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN", _buf = "No provider for SASL mechanism SCRAM-SHA-256: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN")

how can I solve this problem?
I'm trying to compile libsasl for android, but it is not so simple
I appreciate your help

Thank you very much
Angelo

**Comment by edenhill** [comment]
Android is not a supported platform, you'll need to sort this out yourself (PRs welcome!)

**Comment by manang** [comment]
it works with android, tested.
So if you want to add the details in the repo, let me know.
Angelo

**Comment by marcos-marimon** [comment]
Hi there,
have you been able to compile a full version of librdkafka for Android? And for iOS? If so, please, let me know how to achieve it.
Thanks in advance!!!!

**Comment by Dardev12** [comment]
> Hi there, have you been able to compile a full version of librdkafka for Android? And for iOS? If so, please, let me know how to achieve it. Thanks in advance!!!!

Any news about that ? i am stuck on this too for my MAUI Project when i try to run for iOS and Android
