### ISSUE TITLE
fbsd  12 pkg librdkafka-1.7.0 contains fbsd 13 symbols

### ISSUE THREAD

**Issue by Cescante** [edenhill/librdkafka#3525]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
pkg [librdkafka-1.7.0](https://freebsd.pkgs.org/12/freebsd-amd64/librdkafka-1.7.0.txz.html)  for freedsb 12 contains symbols to FBSD_1.6

How to reproduce
================
download/pkg install librdkafka-1.7.0 on freebsd 12.1, then

- On freebsd 12.1, invoke any kafka client 1.7.0 to consume/produce, get
` Undefined symbol "pthread_setname_np@FBSD_1.6"`
- alternatively:
`objdump -TC /usr/local/lib/librdkafka.so.1 | grep pthread_setname_np `
will give pthread_setname_np@FBSD_1.6

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I'm sorry but the FreeBSD packages are not maintained by the librdkafka project. You will need to reach out to the FreeBSD pkg maintainers.
