### ISSUE TITLE
offsetsForTimes failed with Local: All broker connections are down

### ISSUE THREAD

**Issue by LeungKent** [edenhill/librdkafka#3528]
Hi All / Edenhill, 

I'm new to Kafka and GitHub so please bear with me.

I would like to use the 'offsetsForTimes()' to get an offset from a given timestamp, but the call always failed with RD_KAFKA_RESP_ERR__ALL_BROKERS_DOWN error code. May I know, how should I fix this issue?

We need to subscribe to 5 topics and the broker only has one partition per topic, so the consumer program will create 5 comm threads for each topic, each comm thread will have a consumer with a different groupID.

Below is the complete initialize codes (removes some of the error printing blocks), mostly the setting is 'defaulted' based on the sample SDK provided by the broker:-
`BOOL CKafkaCommThread::Initialize()
{
  CString sStr;
  std::string brokers = "some-broker.com:9094";
  std::string errstr;
  std::string mode;
  std::string debug;
  std::vector<std::string> topics;

  NCDSOAuthBearerTokenRefreshCb token_cb;

  int64_t start_offset = RdKafka::Topic::OFFSET_BEGINNING;

  RdKafka::Conf* conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
  RdKafka::Conf* tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

  conf->set("debug", "all", errstr);
  conf->set("metadata.broker.list", brokers, errstr);
  conf->set("security.protocol", "SASL_SSL", errstr);
  conf->set("ssl.ca.location", (LPCTSTR)m_sCertPath, errstr);

  //to fix the certificate error during SSL_HANDSHAKE, during testing
  conf->set("enable.ssl.certificate.verification", "false", errstr);

  conf->set("sasl.mechanism", "OAUTHBEARER", errstr);
  conf->set("sasl.oauthbearer.config", "dummy", errstr);
  conf->set("check.crcs", "true", errstr);
  conf->set("isolation_level", "read_uncommitted", errstr);
  
  // brokers recommend settings
  conf->set("max.poll.records", "5000", errstr);
  conf->set("retry.backoff.ms", "500", errstr);
  conf->set("request.timeout.ms", "20000", errstr);
  conf->set("fetch.max.bytes", "209715200", errstr);
  conf->set("max.partition.fetch.bytes", "5242880", errstr);

  // ---------------- statistics ---------------------
  conf->set("statistics.interval.ms", "1000", errstr);
  // -------------------------------------------------
  conf->set("oauthbearer_token_refresh_cb", &token_cb, errstr);

  CString sGroupId;
  sGroupId.Format("GroupID_Topic%d", m_iGroupID);
  conf->set("group.id", (LPCTSTR)sGroupId, errstr);

  if (m_bStartBeginning)
    conf->set("auto.offset.reset", "earliest", errstr);// always start from midnight (12:00:00 AM ET)
  else
    conf->set("auto.offset.reset", "latest", errstr);// start consume from last stop / fail

  conf->set("default_topic_conf", tconf, errstr);

  rd_kafka_conf_set_stats_cb(conf->c_ptr_global(), stats_cb);

  std::list<std::string>* config_dump = conf->dump();

  m_pkc = RdKafka::KafkaConsumer::create(conf, errstr);
  if (!m_pkc)
  {
    sStr.Format("Failed to create consumer: %s", errstr.c_str());
    GetConsoleApp()->WriteToLog(sStr);
    return FALSE;
  }

  errstr = "";

  topics.push_back((LPCTSTR)m_sTopic);

  RdKafka::ErrorCode err;
  if (m_i64TopicStartTime)
  {
    RdKafka::TopicPartition* topicPartition = RdKafka::TopicPartition::create((LPCTSTR)m_sTopic, 0);
    std::vector<RdKafka::TopicPartition*> toppars{ topicPartition };

    RdKafka::TopicPartition* offsetTopicPartition = RdKafka::TopicPartition::create((LPCTSTR)m_sTopic, 0, m_i64TopicStartTime);
    std::vector<RdKafka::TopicPartition*> offsettoppars{ offsetTopicPartition };

    err = m_pkc->assign(toppars);
    if (err)
    {
      sStr.Format("Failed to assign to toppars, err = %s", RdKafka::err2str(err).c_str());
      GetConsoleApp()->WriteToLog(sStr);
      return FALSE;
    }

    err = m_pkc->offsetsForTimes(offsettoppars, m_dwOffsetTimeout);
    if (err)
    {
      sStr.Format("Failed to offsetsForTimes, err = %s, offset = %I64d, iGroupId = %d",
        RdKafka::err2str(err).c_str(), offsetTopicPartition->offset(), m_iGroupID);
      GetConsoleApp()->WriteToLog(sStr);
      return FALSE;
    }

    err = m_pkc->seek(*offsettoppars[0], m_dwOffsetTimeout);
    if (err)
    {
      sStr.Format("Failed to seek, err = %s", RdKafka::err2str(err).c_str());
      GetConsoleApp()->WriteToLog(sStr);
      return FALSE;
    }
  }
  else
    err = m_pkc->subscribe(topics);

  if (err)
  {
    sStr.Format("Failed to subscribe to %d topics: %s with timestamp = %I64d", topics.size(), RdKafka::err2str(err).c_str(), m_i64TopicStartTime);
    GetConsoleApp()->WriteToLog(sStr);
    return FALSE;
  }

  sStr.Format("****Subscribed");
  GetConsoleApp()->WriteToLog(sStr);

  RdKafka::Message *msg = m_pkc->consume(1000);
  msg_consume(msg, NULL);

  //sStr.Format("RdKafka Version = %d", RdKafka::version());
  //GetConsoleApp()->WriteToLog(sStr);

  delete conf;
  delete tconf;
  return TRUE;
}

I have tried few things below:-
1) If I were to comment on the "IF clause" block statement and direct using the consume->subscribe, the consumer is able to connect and consume data.
2) Increase the timeout parameter to 30000ms or 60000ms still returning the same error.

Some additional info:-
1) The broker is unable to provide the broker log excerpts.
2) The consumer is built as a 32bit application (due to some issue compiling some of the libraries needed to x64 build).

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<v1.7.0>`
 - [x] Apache Kafka version: `<2.6>`
 - [x] librdkafka client configuration: `<auto.reset.offset=earliest>`
 - [x] Operating system: `<Windows 10 - x64>`
 - [x] Provide logs (with `debug=all`) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by rolandyoung** [comment]
That error indicates that librdkafka is unable to connect to the brokers. It is not specific to offsetsForTimes.

It appears from the log that SASL authorisation is failing.  You should check that you can connect to your brokers using kafkacat with the same authorisation parameters.

**Comment by LeungKent** [comment]
Hi Roland,

Well, if I were to comment on that "IF statement" and just using "err = m_pkc->subscribe(topics);", I'm able to consume the message from brokers. The problem I'm having is to subscribe/lookup the offset based on timestamp.

**Comment by rolandyoung** [comment]
It might be that the timeout you are using is too short. Looking at the code for rd_kafka_topic_partition_list_query_leaders (which is one of a very few places that can return the RD_KAFKA_RESP_ERR__ALL_BROKERS_DOWN error code), it seems that, when the timeout expires, if no broker connections have been established yet, it will return the "brokers down" code instead of RD_KAFKA_RESP_ERR__TIMED_OUT.
When you comment out the if statement, do you start getting messages within 1000ms of subscribing? If so, we need to wait for Magnus to comment; if not, try increasing the timeout parameter to offsetForTimes

**Comment by LeungKent** [comment]
Hi Roland,

Thanks, I'll try your suggestion later.

Cheers.

**Comment by LeungKent** [comment]
Hi Roland,

Update, I'm still getting the RD_KAFKA_RESP_ERR__ALL_BROKERS_DOWN error code even with 30000ms or 60000ms timeout. I checked the log when I directly use the "m_pkc->subscribe(topics);", it takes less than 1m as shown below:-

```
22:19:47:688 [49e0][L:I] set token callback: Success : 
22:20:00:433 [3a70][L:I] Timestamp: create time 1631024399711 
```
Is the step that I'm using is correct? Or is there any specific config I need to turn ON for it to work?

Thanks.

**Comment by rolandyoung** [comment]
Hi Leung, 
I can't see anything obviously wrong with what you are doing. We will have to wait for Magnus @edenhill or one of the other maintainers to comment.

Meanwhile, it would probably help if you could fill in the checklist item that asks for the Apache Kafka version of the brokers you are connecting to. Also, from the logs you attached, it looks as you may have quite a lot of non-default configuration settings, and that you are setting a number of producer config settings although yours is a consumer app. You might want to check these and you definitely should list all the configuration settings you are using, as requested in the checklist.

**Comment by LeungKent** [comment]
Hi Roland,

Thanks for the advice. I'll ask my broker regarding the Apache Kafka version and that broker log excerpts. 

However, how can I get the debug log? The program is set with "conf->set("debug", "all", errstr);", but I can't find any file that logs the connection unless I copied it directly from the console app itself. I'll edit and fill up the rest of the task.

Thanks.

**Comment by rolandyoung** [comment]
Logs will go to the console unless you provide a logging callback. See https://github.com/edenhill/librdkafka/wiki/FAQ#logging-and-logs

**Comment by LeungKent** [comment]
Hi Roland,

Thanks for the help, so far I've added the librdkafka log and the Apache Kafka version that the broker is using.

However, they're unable to provide me with the broker excerpts log. Meanwhile, I tried to build the consumer as an x64 bit app, not sure it helps though.

I guess we will have to wait for Magnus @edenhill or one of the other maintainers to help.

**Comment by LeungKent** [comment]
Hi All,

Just to update, I did not test back with librdkafka ver 1.7.0, but using the latest librdkafka ver 1.8.0 and add a call to a dummy poll, for the offsetsForTimes() to work.

Thanks.
