### ISSUE TITLE
KafkaConsumer consume stuck on start up

### ISSUE THREAD

**Issue by emmettwu** [edenhill/librdkafka#3529]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
KafkaConsumer consume stuck on start up
* log
```
MAXPOLL|rdkafka#consumer-1| [thrd:main]: Application maximum poll interval (300000ms) exceeded by 255ms (adjust max.poll.interval.ms for long-running message processing): leaving group
```
![kafka_no_more_message](https://user-images.githubusercontent.com/6754834/132126731-729f0042-b205-41d0-b55f-0a76e307d68c.png)
![kafka_no_more_message_2](https://user-images.githubusercontent.com/6754834/132126734-7077008b-d385-42e0-8aa2-6523ab59c9fa.png)

* pstack
[kafka_init_block_tmp.log](https://github.com/edenhill/librdkafka/files/7111525/kafka_init_block_tmp.log)

* simplified code:
```
std::string err_str;
        #define CHECK_KAFKA_CONF(conf_result) \
            if (RdKafka::Conf::CONF_OK != conf_result) { \
                throw std::invalid_argument("Fail to set kafka config, err=" + err_str); \
            } \

        CHECK_KAFKA_CONF(conf_->set("bootstrap.servers", kafka_config_.brokers(), err_str));
        // default only read newest msg
        CHECK_KAFKA_CONF(conf_->set("auto.offset.reset", "latest", err_str));
        CHECK_KAFKA_CONF(conf_->set("event_cb", &kafka_log_event_cb_, err_str));
        CHECK_KAFKA_CONF(conf_->set("enable.partition.eof", "true", err_str));
        if (!kafka_config_.group_name().empty()) {
            CHECK_KAFKA_CONF(conf_->set("group.id", kafka_config_.group_name(), err_str));
            CHECK_KAFKA_CONF(conf_->set("sasl.username", kafka_config_.user_name(), err_str));
            CHECK_KAFKA_CONF(conf_->set("sasl.password", kafka_config_.pwd(), err_str));
            CHECK_KAFKA_CONF(conf_->set("sasl.mechanisms", kafka_config_.scram(), err_str));
            CHECK_KAFKA_CONF(conf_->set("security.protocol", "SASL_PLAINTEXT", err_str));
        } else {
            CHECK_KAFKA_CONF(conf_->set("group.id", kafka_group_id_, err_str));
        }
        consumer_.reset(RdKafka::KafkaConsumer::create(conf_.get(), err_str));
        if (!consumer_) {
            LOG(ERROR) << "Fail to create consumer. err=" << err_str
                       << " conf=" << kafka_config_.ShortDebugString();
            return false;
        }

// init partition
    consumer_partitions_.clear();
    int32_t partition_count = GetPartitionCount();
    if (partition_count < 1) {
        LOG(ERROR) << "Fail to init consumer with timestamp, "
                   << "invalid partition_count=" << partition_count;
        return false;
    }
    for (int i = 0; i < partition_count; i++) {
        if (i % FLAGS_num_groups == FLAGS_group_id) {
            consumer_partitions_.insert(i);
        }
    }

    butil::Timer tm;
    tm.start();
    std::vector<RdKafka::TopicPartition*> partition_vec;
    for (auto partition_id : consumer_partitions_) {
        RdKafka::TopicPartition* tp =
            RdKafka::TopicPartition::create(kafka_config_.topic_name(), partition_id, timestamp);
        partition_vec.push_back(tp);
    }
    LOG(INFO) << "Consumer partition_size=" << partition_vec.size();

    RdKafka::ErrorCode err = consumer_->offsetsForTimes(partition_vec, FLAGS_kafka_fetch_offset_timeout_ms);
    if (RdKafka::ERR_NO_ERROR != err) {
        LOG(ERROR) << "Fail to get offset, timestamp=" << timestamp << " error=" << err;
        return false;
    }
    LOG(INFO) << "Succeed to get offset of kafka";

    for (auto& pt : partition_vec) {
        LOG(INFO) << "Kafka offset info, part_id=" << pt->partition()
                  << " offset=" << pt->offset();
    }

    err = consumer_->assign(partition_vec);
    if (RdKafka::ERR_NO_ERROR != err) {
        LOG(ERROR) << "Fail to assign offset for timestamp=" << timestamp << " error=" << err;
        return false;
    }

 while (running_) {
        auto msg = consumer_.consume(2000);
        if (msg == nullptr) {
            LOG(ERROR) << "null msg from consume";
            continue;
        }
        Process(*msg);  // user callback
        delete msg;
    }

void Process(const RdKafka::Message& msg) {
    switch (msg.err()) {
        case RdKafka::ERR_NO_ERROR: {
            int64_t msg_ts = msg.timestamp().timestamp;
            processor_(std::string(static_cast<const char*>(msg.payload()), msg.len()), msg_ts);
        } break;
        case RdKafka::ERR__PARTITION_EOF:
            LOG_EVERY_N(INFO, 1000) << "Fail to consume, err=" << msg.err() << " errstr=" << msg.errstr();
            break;
        case RdKafka::ERR__TIMED_OUT:
            LOG(WARNING) << "Fail to consume, err=" << msg.err() << " errstr=" << msg.errstr();
            break;
        case RdKafka::ERR__UNKNOWN_TOPIC:
        case RdKafka::ERR__UNKNOWN_PARTITION:
        default:
            LOG(ERROR) << "Fail to consume, err=" << msg.err() << " errstr=" << msg.errstr();
            return;
    }
}

```
How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">` v1.0.0
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`  in the above code 
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>` Centos7 x64
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka 
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by emmettwu** [comment]
I have tried to patch this `[commit](https://github.com/edenhill/librdkafka/commit/80e9b1ee0c0e477c02f18b130c4302240711a88d`    
the problem still exists.

**Comment by edenhill** [comment]
What version of librdkafka are you using?

Are you sure you are not calling subscribe() at some point?

**Comment by emmettwu** [comment]
librdkafka v1.0.0

**Comment by edenhill** [comment]
Please upgrade to the latest version (1.7.0) and try to reproduce

**Comment by emmettwu** [comment]
our broker is based on open source broker v1.1.0 and add some internal feature in protocol and change the api version which may cause some incompatibility issue when client upgrade to librdkafka v1.7.
which version of librdkafka has critical fix that may related to this issue? I am trying to upgrade to a little newer version and test the compatibility with broker and this issue.

**Comment by emmettwu** [comment]
In my application, there are two kafka consumer. these two consumers call KafkaConsumer::consume in single thread. thread 621 is running. thread 624 is blocked on application start up. two consumer's throughputs capacity is much bigger than producer side.

**Comment by edenhill** [comment]
Both clients and brokers are backwards compatible, so there is no issue running a newer client with an older broker and vice versa.

We only provide free support of the latest librdkafka version.
