### ISSUE TITLE
consumer query about partition size

### ISSUE THREAD

**Issue by pbertoni** [edenhill/librdkafka#354]
Let's say I don't have access to the set of producers that commits on the partition of interest, but just have control over a bunch of C++ consumers. 
Since I'm running benchmarks over a complex program, I'd like to know the spread between the offset my consumers are fetching and the total offset stored in the partition.

*e.g.*, `>> reading message #1234 of 5678 total in partition 0 of topic foo`

I misunderstood the purpose of `RdKafka::Consumer->outq_len()` and `RdKafka::Topic->OFFSET_END`, because they *seem* always equal to `0` and `-1`, respectively.

How can I acquire the `5678` value of my example?

P.S. this may be more fitting for StackOverflow (and ready to replicate it once, hopefully, answered)

**Comment by edenhill** [comment]
You need to subscribe to librdkafka's statistics to get an updated view of your consumer's lag.
Register an Event callback class and regularily call poll() on your handle, check for EVENT_STATS and then parse the corresponding JSON message and look for `lo_offset`, `hi_offset` and `consumer_lag`
