### ISSUE TITLE
Query: Integration of librdkafka client with conluence interceptor

### ISSUE THREAD

**Issue by divya-4062** [edenhill/librdkafka#3542]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
@edenhill 
is there a cpp API available to configure confluence interceptor for librdkafka client?
If you have please share the example for reference.

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The confluent monitoring-interceptor is configured by setting `plugin.library.paths=monitoring-interceptor`, see
https://docs.confluent.io/platform/current/control-center/installation/clients.html#add-ic-librdkafka

**Comment by neha2007** [comment]
@edenhill is this how we can set it with C++ ? Apart from setting this configuration anything else is required?

Using C++ API
==============

RdKafka::Conf* kafkaGlobalConf; 
std::string kafkaConfErr;
RdKafka::Producer* producer;

kafkaGlobalConf->set("metadata.broker.list", "kafka1", kafkaConfErr);
kafkaTopicConf->set("plugin.library.paths", "monitoring-interceptor", kafkaConfErr); 

producer = RdKafka::Producer::create(kafkaGlobalConf, kafkaConfErr);

**Comment by edenhill** [comment]
Yep, that should be sufficient.

**Comment by neha2007** [comment]
okay thanks
