### ISSUE TITLE
Producer fails with message timeout when a broker which is a partition leader is down.

### ISSUE THREAD

**Issue by neha2007** [edenhill/librdkafka#3545]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
@edenhill  

When one broker is down, our application producer is trying to send the msgs to the partitions whose leader is down and those msgs are getting timed out. We are using PARTITION_UA while producing the msgs. How can this be handled from producer so that it produces the msg to the partition whose leader is UP?

Topic replication factor - 1
Number of brokers - 3

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The partitioner will switch to an up broker (if possible), but only for new messages. Already partitioned messages will remain on whatever partition they were partitioned to and sent as soon as a leader for that partition comes up. With a replication factor of 1 you have limited the available brokers to just one, so there's no redundancy.
Recommend a replication factor of 3.

**Comment by neha2007** [comment]
@edenhill is there anyway the produce API does not try to send the msgs to the partitions whose leader is not available. And only produce the msgs to the partitions which has an active leader.

**Comment by edenhill** [comment]
The produce() API selects the partition at the time of produce() and will try to pick a broker that is up. If the broker goes down after produce() then those messages will already have been partitioned and will need a proper leader for that partition.

Increase your replication-factor to 3.
