### ISSUE TITLE
Chances of getting duplicate messages 

### ISSUE THREAD

**Issue by etavene** [edenhill/librdkafka#3549]
Description
===========
May be this a duplicate question. Let's say I have 1-100 messages and getting processed in seperate go routines. All messages got manually commited except four messages 55,56,57,58 due to some processsing issues, and the last commited offset is 100. I restarted the machine which includes both consumer and kafka broker. When consumer is started, I am receiving messages again from 55 onwards. When this will happen? My expection is, always to receive last commited message + 1. In that case it will be  messages above 100.

autoOffsetReset = earliest, num.partitions = 1, number of consumers = 1, auto commit= off

Please provide the following information:

 - [x] librdkafka -1.1.0
 - [x] Apache Kafka version: `2.6.0`

**Comment by edenhill** [comment]
Please try to reproduce on the latest version (1.7.0)

**Comment by etavene** [comment]
@edenhill 
I am not able to reproduce this  either with 1.1.0 or 1.8.0.  Will the above be a possiblity in any scenario ?

**Comment by edenhill** [comment]
Does not sound plausible.
