### ISSUE TITLE
Call log_cb from rd_kafka_poll()

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#355]
This allows an application to control when and from what threads the log_cb is called.
Currently it can be called from any thread at any time, with this enhancement
it'd be possible to configure rdkafka to enqueue log messages on the internal op queue
which is served by the application's call to `rd_kafka_poll()`.

**Comment by yungchin** [comment]
@edenhill if this would purely be for pykafka's benefit, I wonder if I shouldn't rather disable log_cb and bind to error_cb instead? That means a lot less info out of librdkafka I guess, but for development purposes I could still enable and route logging to stderr.

**Comment by edenhill** [comment]
The log callbacks as they stand today are a problem, from the application's perspective it gets a callback on some unknown librdkafka-internal thread, from librdkafka's perspective it calls an application callback from deep within the rdkafka code with a plethora of locks being held.
It is a recipe for disaster if the application really, so having a way to push logs on to a safe queue for later polling is a good approach for both parties.

There are plans to add an automatic rd_kafka_poll() thread provided by rdkafka for applications who dont want to bother with a poll loop, this would fit nicely with log_cb as well.

**Comment by yungchin** [comment]
Thanks, well in that case, this sounds super.
As for https://github.com/Parsely/pykafka/issues/176 what I'll do is I'll switch to using error_cb with a polling thread for the time being - which lets me get rid of the crazy amount of global-intepreter-lock handling that that has now - and then we can move it onto using log_cb once that runs onder rd_kafka_poll.

Thanks!

**Comment by edenhill** [comment]
More specifically:
 * allow logs to be forwarded to any queue_t
 * create poll_queue() API to serve a queue_t

This allows applications to create a separate thread just polling the log queue for in-time log delivery.
