### ISSUE TITLE
programe segment fault

### ISSUE THREAD

**Issue by jarwin123** [edenhill/librdkafka#3551]
hi @edenhill :
       my programe have segment fault cause by librdkafka.
![图片](https://user-images.githubusercontent.com/8475971/133958466-5dbc11fc-58d1-4ef3-a6d5-6329e8e842ea.png)

librdkafka version   v1.6.1
kafka version is kafka_2.11-2.2.0
 librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 
![图片](https://user-images.githubusercontent.com/8475971/133958853-5c3a1e4a-b446-4820-a743-70a0e07b81d2.png)
Operating system
 
![图片](https://user-images.githubusercontent.com/8475971/133958707-17cfcf89-6dfd-4dab-9de4-6b5423bd4fdd.png)

**Comment by edenhill** [comment]
Try running it with valgrind to get some more insight into what's wrong:
`valgrind ./your-program ..`

**Comment by jarwin123** [comment]
sorry, because my programe have a part of dpdk, valgrind didnot support dpdk's programe

**Comment by jarwin123** [comment]
@edenhill , if the topic is not exist, the librdkafka's program produce many data， can be segment fault cause by topic did not exist？
