### ISSUE TITLE
Is retriable exceptions guaranteed to not occur continuously ? 

### ISSUE THREAD

**Issue by dshivashankar1994** [edenhill/librdkafka#3552]
I'm planning to ignore all the exceptions that are ignorable while making the consume call from the kafkaConsumer.

I just wanted to check if all the re-triable exceptions thrown by the consumer are not guaranteed to occur continuously. I was thinking about adding a check that if a re-triable exception pops continuously for several times (say 100) then to raise the exception explicitly. 

Does this kind of feature already exist or would it be better to have on in place ?

Checklist
=========
**IMPORTANT**: We will close issues where the checklist has not been completed.
Please provide the following information:
 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka does not throw any exceptions.

**Comment by dshivashankar1994** [comment]
I was actually mentioning about the ErrorCode. Currently I am checking the errorcode. If no-error, process the message otherwise fail in most of the cases.

I'm planning to check if the error is re-tryable, simple ignore and consume again. I was thinking about adding a check that if a re-triable exception pops continuously for several times (say 100) then to raise the exception explicitly.

Does this kind of feature already exist or would it be better to have on in place ?

**Comment by edenhill** [comment]
Ah, sorry. The error code API unfortunately does not provide any means of indicating retriable or not. The new `rd_kafka_error_t` does though, but it is only used in new APIs.
The long term plan is to migrate everything to the richer error type.
A shorter term plan is to provide something like:
```c
rd_kafka_error_t *rd_kafka_error_from_legacy (rd_kafka_resp_err_t err, void *api_ptr);

// So you could do:
rd_kafka_err_resp_t err = rd_kafka_produce(...);
if (err) {
  rd_kafka_error_t *error = rd_kafka_error_from_legacy(err, rd_kafka_produce);
  if (rd_kafka_error_is_retriable(error))
   ...
}
```

In the meantime you will need to maintain your own list of retriable error types per API.

**Comment by dshivashankar1994** [comment]
I saw that the Error object does - (https://docs.confluent.io/platform/current/clients/librdkafka/html/classRdKafka_1_1Error.html).

If I can get the Error Object using the code, then I should be able to use it right ? Is there a way to get the error object  ?

**Comment by dshivashankar1994** [comment]
Also, I saw this in code
```
case RD_KAFKA_RESP_ERR_COORDINATOR_LOAD_IN_PROGRESS:                       
case RD_KAFKA_RESP_ERR_UNKNOWN_TOPIC_OR_PART:
--
  | p_actions \|= RD_KAFKA_ERR_ACTION_RETRY;
  | err = ErrorCode;
  | request_error = rd_true;
  | break;
```

I believe this is to mark the errors as re-triable. Am I right ? If I could make use of them, it would be nice.

**Comment by dshivashankar1994** [comment]
Hi, Ping for above.

**Comment by dshivashankar1994** [comment]
Hi, Ping for above.

**Comment by dshivashankar1994** [comment]
Hi, Ping for above.

**Comment by edenhill** [comment]
Only rd_kafka_error_t exposes an is_retriable().
