### ISSUE TITLE
librdkafka may raise OpenSSL error 'no OPENSSL_Applink()' on Windows due to use of 'd2i_PKCS12_fp' in rdkafka_ssl.c

### ISSUE THREAD

**Issue by OliverH-SDOS** [edenhill/librdkafka#3554]
Description
===========
librdkafka raises error 'no OPENSSL_Applink()' on Windows if the application executable using the library does not use

#include <openssl/applink.c>

which is not always possible, i.e. for DLLs or if the calling executable is not written in C/C++.  

The problem is caused by using any of the OpenSSL '*_fp()' functions, i.e. in 'rdkafka_ssl.c' the line

p12 = d2i_PKCS12_fp(fp, NULL);

This can easily be resolved by using the OpenSSL BIO functions, please check attached patch:

PKCS12 *p12 = NULL;
[...]
BIO *bio = BIO_new(BIO_s_file());
if (bio) {
    if (BIO_read_filename(bio, (char*)rk->rk_conf.ssl.keystore_location) > 0) {
        p12 = d2i_PKCS12_bio(bio, NULL);
        BIO_free(bio);
    }
    else {
        rd_snprintf(errstr, errstr_size,
            "Failed to open ssl.keystore.location: "
            "%s: %s",
            rk->rk_conf.ssl.keystore_location,
            rd_strerror(errno));
        BIO_free(bio);
        return -1;
    }
}

[0001-OpenSSL-BIO-for-FP.zip](https://github.com/edenhill/librdkafka/files/7196224/0001-OpenSSL-BIO-for-FP.zip)

How to reproduce
======
On Windows OS, set config 'ssl.ca.location' and do not include 'openssl/applink.c' in the C/C++ executable

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.7.0`
 - [x] Apache Kafka version: `2.13-2.8.0`
 - [x] librdkafka client configuration: `ssl.ca.location=<ca_pem>`
 - [x] Operating system: `Windows 10 Pro, Version 21H2, Build 19043`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: `process terminates with 'OPENSSL_Uplink() - no OPENSSL_Applnk()`

**Comment by edenhill** [comment]
Interesting, we've never seen this being reported before.

@mhowlett Can you try to reproduce with the dotnet client on 1.8.0 by setting `SslCaLocation: "/some/cacert.pem"` ?

**Comment by OliverH-SDOS** [comment]
To further explain: 

I’m using a wrapper library implementing an ‘easy’ interface for librdkafka which is used from a C++ and a Delphi executable. While I could include ‘openssl/applink.c’ in my C++ executable this is not possible in Delphi.

The OpenSSL ‘*_fp()’ functions are special on Windows as ‘fopen’, ‘open’, … are provide by the MS VC runtime library for which you have 4 variants (shared DLL or static, each release and debug). As a result all OpenSSL ‘*_fp()’ functions are required to use the same implementation, even if OpenSSL itself is linked to a different MS VC runtime. To allow this they use ‘OPENSSL_Applink’ which gives OpenSSL a table containing the required function pointers. I think that there is a define for the OpenSSL build process to disable this mechanism, but especially the ‘vcpkg’ OpenSSL port I’m using on Windows has this enabled.

I think such a mess should be avoided, especially as the BIO functions offer ‘BIO_file()’ to do so.

**Comment by edenhill** [comment]
Addressed in https://github.com/edenhill/librdkafka/pull/3602

Thanks for a great report, and the patch :+1:
