### ISSUE TITLE
ProduceRequest failed: Local: Timed out in queue: explicit actions Retry,MsgNotPersisted

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#3564]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi @edenhill 
In our production, we have two different machines sending messages to the same Kafka cluster. One of them working fine.
Another one is having a problem and the Produce request is being failed with error **"ProduceRequest failed: Local: Timed out in queue: explicit actions Retry,MsgNotPersisted"**

what could be the probable cause?

do you think **socket.nagle.disable=true** or **queue.buffering.max.ms=1** can create trouble?

**Note: we have a high traffic of 2k msgs/second in peak hour**

Thank you!

LOG
========
G 180130 -0-KAFKA-INT: 1632416490.525 ARI-RDKAFKA-7-REQERR: elavon_eu_axis_dub02 #producer-1: [thrd:sasl_plaintext://kygfsa69901e8
                       7.us.bank-dns.com:9092/1002]: sasl_plaintext://kygfsa69901e86.us.bank-dns.com:9092/1003: ProduceRequ
                       est failed: Local: Timed out in queue: explicit actions Retry,MsgNotPersisted
G 180130 -0-KAFKA-INT: 1632416490.525 ARI-RDKAFKA-4-REQTMOUT: elavon_eu_axis_dub02 #producer-1: [thrd:sasl_plaintext://kygfsa69901
                       e87.us.bank-dns.com:9092/1002]: sasl_plaintext://kygfsa69901e86.us.bank-dns.com:9092/1003: Timed out
                        0 in-flight, 0 retry-queued, 1 out-queue, 1 partially-sent requests
G 180130 -0-KAFKA-INT: 1632416490.527 ARI-RDKAFKA-7-FAIL: elavon_eu_axis_dub02 #producer-1: [thrd:sasl_plaintext://kygfsa69901e87.
                       us.bank-dns.com:9092/1002]: sasl_plaintext://kygfsa69901e86.us.bank-dns.com:9092/1003: 1 request(s)
                       timed out: disconnect (after 787099ms in state UP) (_TIMED_OUT)
G 180130 -0-KAFKA-INT: 1632416490.528 ARI-RDKAFKA-3-FAIL: elavon_eu_axis_dub02 #producer-1: [thrd:sasl_plaintext://kygfsa69901e87.
                       us.bank-dns.com:9092/1002]: sasl_plaintext://kygfsa69901e86.us.bank-dns.com:9092/1003: 1 request(s)
                       timed out: disconnect (after 787099ms in state UP)
G 180130 -0-KAFKA-INT: 1632416490.528 ARI-RDKAFKA-7-STATE: elavon_eu_axis_dub02 #producer-1: [thrd:sasl_plaintext://kygfsa69901e87
                       .us.bank-dns.com:9092/1002]: sasl_plaintext://kygfsa69901e86.us.bank-dns.com:9092/1003: Broker chang
                       ed state UP -> DOWN                                          
G 180130 -0-KAFKA-INT: 1632416490.528 ARI-RDKAFKA-7-STATE: elavon_eu_axis_dub02 #producer-1: [thrd:sasl_plaintext://kygfsa69901e87
                       .us.bank-dns.com:9092/1002]: sasl_plaintext://kygfsa69901e86.us.bank-dns.com:9092/1003: Broker chang       
                       ed state DOWN -> INIT                                                                              
G 180130 -0-KAFKA-INT: 1632416490.528 ARI-RDKAFKA-7-STATE: elavon_eu_axis_dub02 #producer-1: [thrd:sasl_plaintext://kygfsa69901e87
                       .us.bank-dns.com:9092/1002]: sasl_plaintext://kygfsa69901e86.us.bank-dns.com:9092/1003: Broker chang       
                       ed state INIT -> TRY_CONNECT

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.5.0`
 - [x] Apache Kafka version: `0.10.1`
 - [x] librdkafka client configuration: `security.protocol=sasl_plaintext
 - builtin.features=sasl_gssapi 
 - queue.buffering.max.ms=1
 - socket.nagle.disable=true`
 - [ ] Operating system: `Linux`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by write2jaydeep** [comment]
Hi @edenhill 
I can understand it could be a burden for you guys to reply to all problems.
This problem is on high priority for me, anybody please guide me? I request you to please help me

Thanks
Jaydeep

**Comment by rolandyoung** [comment]
It looks as rdkafka is reporting that the broker failed to respond in time to a request and then the broker actually went down. I doubt that any configuration on the client side will fix this. If you have a reproducible error, you should try to reproduce it using the current release of librdkafka. You might also want to use a more up-to-date version of the broker software.

**Comment by write2jaydeep** [comment]
Thanks a lot @rolandyoung 
We have another machine with the same version 1.5.0 sending to the same broker and topic, it works very well.
What parameter do I need to tune on the client-side or broker side if it is problem with network connections?

**Comment by rolandyoung** [comment]
If you have two clients running the same software connecting to the same broker and one works fine but the other fails badly, with symptoms of network issues, then you do not need to tune the client, you need to fix the network.
(I am sorry, but you will not receive free support from an open source project for an out-of-date release.)

**Comment by write2jaydeep** [comment]
Thank you @rolandyoung I really appreciate your valuable time.
I will see possibilities to upgrade librdkafka to the latest release.

Thanks once again.
