### ISSUE TITLE
request for enhancement: add support for kafka through an HTTP proxy tunnel (HTTP CONNECT)

### ISSUE THREAD

**Issue by funkiestj** [edenhill/librdkafka#3568]
Description
===========
 I have a kafka producer written in Go using the confluent-kafka-go bindings.

I want my kafka producer to establish a connection to a kafka broker that is behind an HTTP proxy that supports HTTP CONNECT tunneling.

It looks like this is not currently supported.  

https://stackoverflow.com/questions/69398962/does-librdkafka-and-confluent-kafka-go-support-connecting-to-a-kafka-broker-via

I have an urgent need for this feature and am interested in contracting with a librdkafka develop (edenhill or other) to implement this.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version v1.8.0

**Comment by OneCricketeer** [comment]
As answered on Stackoverflow, Kafka or its clients don't use HTTP or header negotiation
