### ISSUE TITLE
Transactional producer inadvertently creates new transaction on OUT_OF_ORDER_SEQUENCE error

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#3575]
Description
===========
Upon receiving OUT_OF_ORDER_SEQUENCE the transactional producer will ask the transaction coordinator to bump its Epoch so it can reset its message sequences and attempt retries, but this inadvertently creates a new clean transaction on the broker without the client knowing. Any messages successfully produced to the transaction prior to this will be lost (in an uncommitted and later implicitly aborted transaction) while the new transaction's transaction_commit() will return success.

How to reproduce
================

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 1.6.1
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by Leveled986** [comment]
63723209301a9aa59767118f76e11d5b40144014
