### ISSUE TITLE
consumer suspend fetching message from brokers in some condition， and it resumes in several minutes  automatically.

### ISSUE THREAD

**Issue by JiangXiao2019** [edenhill/librdkafka#3578]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
@edenhill
Hi, this issue became more serious, my customer complained.  Do you have some advice for me?
In recent 1 month, I noticed the log output some information as:
     Timed out FetchRequest in flight  (after 61080ms, timeout #0)
     Timed out 1 in-flight, 0 retry-queued, 0 out queue, 0 partially-sent requests
When the program output this message, the consumer can't get message, maybe blocked in calling rd_kafka_consume_batch().
It happens on some consumers,  and other cosumers works on other topics works well.
It can resume consume after 2-20 minutes, but some times will need 1 hour.
If I jump some offsets consume from offset=-1, it can consume 2-3 batches of messages, and then suspend.
The kafka server works normally, there is "ERROR" or "WARNING" in log.

I upgraded librdkafka from 1.2.0RC3 to 1.8.0 last week, the issue is still exist. and, the error information became:
2021-10-15 08:26:40.193 <err_cb> topic:babj_hadb_surf_wea_chn_pre_min_tab: error:Local: Timed out: reason:xx.xx.xx.xx:9092/3: 1 request(s) timed out: disconnect (after 61043ms in state UP, 1 identical error(s) suppressed)
2021-10-15 08:41:30.100 <err_cb> topic:babj_hadb_surf_wea_chn_mul_min_tab: error:Local: Timed out: reason:xx.xx.xx.xx:9092/3: 1 request(s) timed out: disconnect (after 61257ms in state UP)
2021-10-15 08:49:36.025 <err_cb> topic:babj_hadb_surf_wea_chn_mul_min_tab: error:Local: Timed out: reason:xx.xx.xx.xx:9092/3: 1 request(s) timed out: disconnect (after 113080ms in state UP, 1 identical error(s) suppressed)

It seems there have some relations with this code:
/* If this was a partially sent request that timed out, or the
                 * number of timed out requests have reached the
                 * socket.max.fails threshold, we need to take down the
                 * connection. */
                if (partial_cnt > 0 ||
                    (**rkb->rkb_rk->rk_conf.socket_max_fails** &&
                     **rkb->rkb_req_timeouts** >=
                     rkb->rkb_rk->rk_conf.**socket_max_fails** &&
                     rkb->**rkb_state >= RD_KAFKA_BROKER_STATE_UP**)) {
                        char rttinfo[32];
                        /* Print average RTT (if avail) to help diagnose. */
                        rd_avg_calc(&rkb->rkb_avg_rtt, now);
                        if (rkb->rkb_avg_rtt.ra_v.avg)
                                rd_snprintf(rttinfo, sizeof(rttinfo),
                                            " (average rtt %.3fms)",
                                            (float)(rkb->rkb_avg_rtt.ra_v.avg/
                                                    1000.0f));
                        else
                                rttinfo[0] = 0;
                        **rd_kafka_broker_fail(rkb, LOG_ERR,
                                             RD_KAFKA_RESP_ERR__TIMED_OUT,
                                             "%i request(s) timed out: "
                                             "disconnect%s",
                                             rkb->rkb_req_timeouts, rttinfo);**
                }

How to reproduce
================
I don't know how to reproduce, my program had been working over 1 year, it happened recently.

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<1.8.0>`
 - [ ] Apache Kafka version: `<2.10-2.1.0>`
 - [ ] librdkafka client configuration: `<>`
 - [ ] Operating system: `<Centos 7 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please provide your consumer configs.

This does look like a networking or cluster problem though, requests taking too long.

**Comment by edenhill** [comment]
Check your broker metrics for request handling times, have they increased lately?

**Comment by JiangXiao2019** [comment]
comment: This issue was due to network transport. If we set fetch.max.bytes and fetch.message.max.bytes to lower, consumer worked normally but with low transport speed. When network restored, we adjusted these two parameters back. Thank you edenhill, you lead me to consider network issue.

**Comment by pranavrth** [comment]
Closing this issue as confirmed.
