### ISSUE TITLE
Seems some libraries are missing when configured the client with SASL

### ISSUE THREAD

**Issue by michellewen1516** [edenhill/librdkafka#3583]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Got these logs when start a producer:
looking for plugins in '/usr/lib/x86_64-linux-gnu/sasl2', failed to open directory, error: No such file or directory
 looking for plugins in '/usr/lib/sasl2', failed to open directory, error: No such file or directory

But could find the /usr/lib64/sasl2/ folder, not sure what's going wrong or config issue.

**Comment by edenhill** [comment]
That's a cyrus-sasl2 issue.
