### ISSUE TITLE
Question: Does librdkafka support mTLS authentication?

### ISSUE THREAD

**Issue by write2jaydeep** [edenhill/librdkafka#3588]
Hi @edenhill 

Description
===========
Does librdkafka support mTLS authentication?

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.8.0`
 - [x] Apache Kafka version: `2.7`
 - [x] Operating system: `Linux`

**Comment by write2jaydeep** [comment]
What about RBAC?

**Comment by write2jaydeep** [comment]
Anyone can reply to my question, please?? 
I really appreciate your valuable time.
Thanks
JD

**Comment by orent** [comment]
IIUC, mTLS  or "mutual TLS" is just a fancy name for TLS with client certificates. The answer is yes:

https://github.com/confluentinc/librdkafka/wiki/Using-SSL-with-librdkafka#configure-librdkafka-client
