### ISSUE TITLE
Can't install it on CentOS 7 ... output of ./configure  

### ISSUE THREAD

**Issue by monukhamba** [edenhill/librdkafka#359]
checking for OS or distribution... ok (CentOS)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok (cached)
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok (cached)
checking executable ld... ok (cached)
checking executable nm... ok (cached)
checking executable objdump... ok (cached)
checking executable strip... ok (cached)
checking for pkgconfig (by command)... ok (cached)
checking for install (by command)... ok (cached)
checking for PIC (by compile)... ok (cached)
checking for GNU-compatible linker options... ok (cached)
checking for GNU linker-script ld flag... ok (cached)
checking for __atomic_32 (by compile)... failed
checking for __atomic_32_lib (by compile)... failed
checking for __sync_32 (by compile)... ok (cached)
checking for __atomic_64 (by compile)... failed
checking for __atomic_64_lib (by compile)... failed
checking for __sync_64 (by compile)... ok (cached)
checking for socket (by compile)... ok (cached)
parsing version '0x00080600'... ok (0.8.6)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for perl (by command)... ok (cached)
Generated rdkafka.pc
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  ARCH                     x86_64
  CPU                      generic
  CPPFLAGS                 -m64 -g -O2 -fPIC -Wall -Wfloat-equal -Wpointer-arith
  LDFLAGS                  -m64
  MKL_DISTRO               CentOS
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.8.6
  LIBS                     -lpthread -lz   -lrt
  CFLAGS                    
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
Generated config.cache

**Comment by edenhill** [comment]
Can you provide the output of `make all` and `sudo make install` after configure?

**Comment by monukhamba** [comment]
[root@mesos2 librdkafka]# make all
make[1]: Entering directory `/opt/librdkafka/src'
Checking librdkafka integrity
librdkafka.so.1                OK
librdkafka.a                   OK
Symbol visibility              OK
make[1]: Leaving directory `/opt/librdkafka/src'
make[1]: Entering directory `/opt/librdkafka/src-cpp'
Checking librdkafka++ integrity
librdkafka++.so.1              OK
librdkafka++.a                 OK
make[1]: Leaving directory `/opt/librdkafka/src-cpp'
make -C examples
make[1]: Entering directory `/opt/librdkafka/examples'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/opt/librdkafka/examples'
Updating
Checking  integrity
CONFIGURATION.md               OK
examples/rdkafka_example       OK
examples/rdkafka_performance   OK
examples/rdkafka_example_cpp   OK
make[1]: Entering directory `/opt/librdkafka/src'
Checking librdkafka integrity
librdkafka.so.1                OK
librdkafka.a                   OK
Symbol visibility              OK
make[1]: Leaving directory `/opt/librdkafka/src'
make[1]: Entering directory `/opt/librdkafka/src-cpp'
Checking librdkafka++ integrity
librdkafka++.so.1              OK
librdkafka++.a                 OK
make[1]: Leaving directory `/opt/librdkafka/src-cpp'
[root@mesos2 librdkafka]# sudo make install
make[1]: Entering directory `/opt/librdkafka/src'
Install librdkafka to /usr/local
install -d $DESTDIR/usr/local/include/librdkafka ; \
	install -d $DESTDIR/usr/local/lib ; \
	install rdkafka.h $DESTDIR/usr/local/include/librdkafka ; \
	install librdkafka.a $DESTDIR/usr/local/lib ; \
	install librdkafka.so.1 $DESTDIR/usr/local/lib ; \
	(cd $DESTDIR/usr/local/lib && ln -sf librdkafka.so.1 librdkafka.so)
make[1]: Leaving directory `/opt/librdkafka/src'
make[1]: Entering directory `/opt/librdkafka/src-cpp'
Install librdkafka++ to /usr/local
install -d $DESTDIR/usr/local/include/librdkafka ; \
	install -d $DESTDIR/usr/local/lib ; \
	install rdkafkacpp.h $DESTDIR/usr/local/include/librdkafka ; \
	install librdkafka++.a $DESTDIR/usr/local/lib ; \
	install librdkafka++.so.1 $DESTDIR/usr/local/lib ; \
	(cd $DESTDIR/usr/local/lib && ln -sf librdkafka++.so.1 librdkafka++.so)
make[1]: Leaving directory `/opt/librdkafka/src-cpp'

**Comment by edenhill** [comment]
Ì dont see any errors. Whats the problem?

**Comment by monukhamba** [comment]
I am trying to use it with kafkacat for  https://github.com/mesos/kafka


and when I run this ..

[root@mesos2 opt]# echo "test"|kafkacat -P -b "mesos1.xxxx.com:31000" -t testTopic -p 0
kafkacat: error while loading shared libraries: librdkafka.so.1: cannot open shared object file: No such file or directory

**Comment by edenhill** [comment]
That probably means you dont have /usr/local/lib in you LD_LIBRARY_PATH or /etc/ld.so.conf
Try this:
`LD_LIBRARY_PATH=/usr/local/lib  echo test | kafkacat -P .....`

See answer number two here for a proper fix:
http://serverfault.com/questions/372987/centos-usr-local-lib-system-wide-ld-library-path

**Comment by monukhamba** [comment]
Thanks!
