### ISSUE TITLE
Kafka producer publishes messages to one partition out of 4 only

### ISSUE THREAD

**Issue by aliabidzaidi** [edenhill/librdkafka#3603]
I have a producer that publishes messages to kafka, 
I have 2 brokers with 4 partitions by default, my problem is the producer sends all messages to one partition. 
But if I run the same producer code on another VM it runs fine and divides it into partitions, even if I use the console-producer it gets divided.
The problem is weird and its on this Virtual Machine, here is a screenshot of stats from kafdrop

![image](https://user-images.githubusercontent.com/32914990/139854749-f2474ac6-f459-4a53-9dc3-c4168b8798d9.png)

I have copied snippets from production find complete code here: https://gist.github.com/aliabidzaidi/5ab0a313d282d3ebb8cb4a63589e53b8

Its hard to reproduce this, since it works fine if we run the producer on other Virtual Machines.

 - [x] librdkafka version `librdkafka-dev 1.2.1-1` (Also tried it on latest librdkafka release of 1.7)
 - [x] Apache Kafka version: `kafka_2.13-2.7.0-`
 - [x] librdkafka client configuration: 
        - broker_list=10.120.1.134:9092,10.120.1.135:9092
        - batch_size=2147483647
        - linger_ms=1000
        - message_send_max_retries=1
        - queued_min_messages=10000000
        - queue_buffering_max_kbytes=2147483647
        - queue_buffering_max_messages=2000000
 - [x] Operating system: `Ubuntu 20.04`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please repro with debug="topic,msg,broker" and provide the logs.
