### ISSUE TITLE
About rebalance

### ISSUE THREAD

**Issue by Z-J-X** [edenhill/librdkafka#3615]
When I use the consumer program to consume data, I use rebalance. I subscribe to three topics. At this time, none of the three topics are created. When the consumer program starts, an error will be reported, and then when I create one of the topics, rebalance_cb will be triggered immediately. At this time, this topic can be consumed normally, but when I create the remaining topics, It will take about 2 to 3 minutes to trigger rebalance_cb. Can the trigger time be dynamically configured? I want to achieve this effect: when the topic is created, the rebalance_cb is triggered immediately.

**Comment by edenhill** [comment]
Try decreasing `topic.metadata.refresh.interval.ms`
