### ISSUE TITLE
Default `topic.metadata.refresh.interval.ms` is very aggressive

### ISSUE THREAD

**Issue by eapache** [edenhill/librdkafka#363]
@edenhill it defaults to 10 seconds, which is extremely aggressive. The default value in Sarama and in the JVM client is 10 minutes, which seems much more reasonable.

cc @kvs

**Comment by eapache** [comment]
For context: we deployed some instances of librdkafka without noticing this default, and nearly DDOSed our cluster under metadata refreshes.

**Comment by edenhill** [comment]
Thanks Evan, sorry about your cluster.. ;)
