### ISSUE TITLE
consumer

### ISSUE THREAD

**Issue by CXW0504** [edenhill/librdkafka#3643]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
<your issue description goes here>
my error log:

ytes, CorrId 1, rtt 41.64ms)
%7|1638883762.584|PROTOERR|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test24.bj:9092/bootstrap]: ali-f-inf-kafka-test24.bj:9092/2: Protocol parse failure for ApiVersion v3(flex) at 3/6 (rd_kafka_handle_ApiVersion:2046) (incorrect broker.version.fallback?)
%7|1638883762.584|PROTOERR|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test24.bj:9092/bootstrap]: ali-f-inf-kafka-test24.bj:9092/2: ApiArrayCnt -1 out of range
%7|1638883762.584|APIVERSION|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test24.bj:9092/bootstrap]: ali-f-inf-kafka-test24.bj:9092/2: ApiVersionRequest v3 failed due to UNSUPPORTED_VERSION: retrying with v0
%7|1638883762.584|SEND|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test24.bj:9092/bootstrap]: ali-f-inf-kafka-test24.bj:9092/2: Sent ApiVersionRequest (v0, 21 bytes @ 0, CorrId 2)
%7|1638883762.584|RECV|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test27.bj:9092/bootstrap]: ali-f-inf-kafka-test27.bj:9092/5: Received ApiVersionResponse (v3, 6 bytes, CorrId 1, rtt 41.65ms)
%7|1638883762.584|PROTOERR|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test27.bj:9092/bootstrap]: ali-f-inf-kafka-test27.bj:9092/5: Protocol parse failure for ApiVersion v3(flex) at 3/6 (rd_kafka_handle_ApiVersion:2046) (incorrect broker.version.fallback?)
%7|1638883762.584|PROTOERR|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test27.bj:9092/bootstrap]: ali-f-inf-kafka-test27.bj:9092/5: ApiArrayCnt -1 out of range
%7|1638883762.584|APIVERSION|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test27.bj:9092/bootstrap]: ali-f-inf-kafka-test27.bj:9092/5: ApiVersionRequest v3 failed due to UNSUPPORTED_VERSION: retrying with v0
%7|1638883762.584|SEND|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test27.bj:9092/bootstrap]: ali-f-inf-kafka-test27.bj:9092/5: Sent ApiVersionRequest (v0, 21 bytes @ 0, CorrId 2)
%7|1638883762.593|RECV|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test25.bj:9092/bootstrap]: ali-f-inf-kafka-test25.bj:9092/3: Received ApiVersionResponse (v3, 6 bytes, CorrId 1, rtt 48.25ms)
%7|1638883762.593|PROTOERR|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test25.bj:9092/bootstrap]: ali-f-inf-kafka-test25.bj:9092/3: Protocol parse failure for ApiVersion v3(flex) at 3/6 (rd_kafka_handle_ApiVersion:2046) (incorrect broker.version.fallback?)
%7|1638883762.593|PROTOERR|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test25.bj:9092/bootstrap]: ali-f-inf-kafka-test25.bj:9092/3: ApiArrayCnt -1 out of range
%7|1638883762.593|APIVERSION|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test25.bj:9092/bootstrap]: ali-f-inf-kafka-test25.bj:9092/3: ApiVersionRequest v3 failed due to UNSUPPORTED_VERSION: retrying with v0
%7|1638883762.593|SEND|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test25.bj:9092/bootstrap]: ali-f-inf-kafka-test25.bj:9092/3: Sent ApiVersionRequest (v0, 21 bytes @ 0, CorrId 2)
%7|1638883762.593|RECV|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test23.bj:9092/bootstrap]: ali-f-inf-kafka-test23.bj:9092/1: Received ApiVersionResponse (v3, 6 bytes, CorrId 1, rtt 43.85ms)
%7|1638883762.593|PROTOERR|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test23.bj:9092/bootstrap]: ali-f-inf-kafka-test23.bj:9092/1: Protocol parse failure for ApiVersion v3(flex) at 3/6 (rd_kafka_handle_ApiVersion:2046) (incorrect broker.version.fallback?)
%7|1638883762.593|PROTOERR|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test23.bj:9092/bootstrap]: ali-f-inf-kafka-test23.bj:9092/1: ApiArrayCnt -1 out of range
%7|1638883762.593|APIVERSION|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test23.bj:9092/bootstrap]: ali-f-inf-kafka-test23.bj:9092/1: ApiVersionRequest v3 failed due to UNSUPPORTED_VERSION: retrying with v0
%7|1638883762.593|SEND|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test23.bj:9092/bootstrap]: ali-f-inf-kafka-test23.bj:9092/1: Sent ApiVersionRequest (v0, 21 bytes @ 0, CorrId 2)
%7|1638883762.626|RECV|rdkafka#consumer-1| [thrd:ali-f-inf-kafka-test27.bj:9092/bootstrap]: ali-f-inf-kafka-test27.bj:9092/5: Received ApiVersionResponse (v0, 234 bytes, CorrId 2, rtt 41.86ms)

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There are no errors in that log, it is all debug logs (level %7).
