### ISSUE TITLE
coredump in producer::poll

### ISSUE THREAD

**Issue by acoredump** [edenhill/librdkafka#3647]
have a crash in librdkafka ,and the heap-stack info is :
==================================================================
Core was generated by `./dns_defend'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f1302b90ad7 in dr_msg_cb_trampoline(rd_kafka_s*, rd_kafka_message_s const*, void*) () from ../lib/libkafka/librdkafka++.so.1
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-21.el7.x86_64 glibc-2.17-307.el7.1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libdb-5.3.21-25.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libselinux-2.5-11.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 nss-softokn-freebl-3.28.3-6.el7.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) where
#0  0x00007f1302b90ad7 in dr_msg_cb_trampoline(rd_kafka_s*, rd_kafka_message_s const*, void*) () from ../lib/libkafka/librdkafka++.so.1
#1  0x00007f13028c20c9 in rd_kafka_poll_cb () from ../lib/libkafka/librdkafka.so.1
#2  0x00007f13028edc93 in rd_kafka_q_serve () from ../lib/libkafka/librdkafka.so.1
#3  0x00000000004487df in def_output_kafka (
    buff=0x7f1241596240 "1|124.64.19.212|tls-amap.dingtalk.com|0|0|10904|2021-12-15 18:25:16|39.98.22.123;59.82.29.233||0\n1|124.64.18.53|pull-tsl-l3.douyincdn.com|0|0|10904|2021-12-15 18:25:16|125.35.234.180;125.35.234.182;12"..., topic="forwardmsgtopic", index=1) at dc_dispatch_search.cpp:265
#4  0x00000000004493ae in file_writer (arg=0x17de270) at dc_dispatch_search.cpp:558
#5  0x00007f1301e76ea5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f1301b9f8dd in clone () from /lib64/libc.so.6
==================================================================
the way that use the libkafka is :
void def_output_kafka(char *buff, std::string &topic, int index)
{
    if(producer_mgr[index] == NULL)
        return ;
    int error_code = producer_mgr[index]->produce(
        topic,
        RdKafka::Topic::PARTITION_UA,
        RdKafka::Producer::RK_MSG_COPY,
        const_cast<char*>(buff), strlen(buff),
        NULL, 0, 0, NULL);
    
    if (error_code != RdKafka::ERR_NO_ERROR)
    {
        printf("error in kafka produce, and code is %d\n", error_code);
        if (error_code == RdKafka::ERR__QUEUE_FULL)
        {
            error_code = producer_mgr[index]->poll(-1);
            error_code = producer_mgr[index]->produce(
                    topic,
                    RdKafka::Topic::PARTITION_UA,
                    RdKafka::Producer::RK_MSG_COPY,
                    const_cast<char*>(buff), strlen(buff),
                    NULL, 0, 0, NULL);
            return ;
        }
            
    }
    producer_mgr[index]->poll(-1);
    return ;
}
==================================================================
function def_output_kafka running in a while (true) {  }  thread，can any one help me ????

**Comment by edenhill** [comment]
Don't delete the issue template, fill it out instead.

But your issue is probably that your delivery report callback class has gone out of scope (stack allocated?).

**Comment by acoredump** [comment]
> Don't delete the issue template, fill it out instead.
> 
> But your issue is probably that your delivery report callback class has gone out of scope (stack allocated?).

thank you , that is a very low-level bug！
