### ISSUE TITLE
cpp consumer of the example seems doesn't work

### ISSUE THREAD

**Issue by cleo-yin** [edenhill/librdkafka#366]
$ ./rdkafka_example_cpp -P -t "Position" -p 1
% Created producer rdkafka#producer-0
LOG-5-TOPICBRK: Topic Position [0] migrated to unknown broker 1: requesting metadata update
LOG-5-TOPICBRK: Topic Position [1] migrated to unknown broker 1: requesting metadata update
LOG-5-TOPICBRK: Topic Position [2] migrated to unknown broker 1: requesting metadata update
test
% Produced message (4 bytes)
test!!
% Produced message (6 bytes)
Message delivery for (4 bytes): Success

cpp consumer didn't got any messages, and after a while, it got timeout:
$ ./rdkafka_example_cpp -C -t "Position" -p 1
% Created consumer rdkafka#consumer-0
LOG-5-TOPICBRK: Topic Position [0] migrated to unknown broker 1: requesting metadata update
LOG-5-TOPICBRK: Topic Position [1] migrated to unknown broker 1: requesting metadata update
LOG-5-TOPICBRK: Topic Position [2] migrated to unknown broker 1: requesting metadata update
Consume failed: Local: Message timed out

but with c consumer, it received the messages:
$ ./rdkafka_example -C -t "Position" -p 1
% Message (offset 54, 4 bytes):
Message Payload hexdump (4 bytes):
00000000: 74 65 73 74                                      test            
% Consumer reached end of Position [1] message queue at offset 55
% Message (offset 55, 6 bytes):
Message Payload hexdump (6 bytes):
00000000: 74 65 73 74 21 21                                test!!          
% Consumer reached end of Position [1] message queue at offset 56

**Comment by edenhill** [comment]
That works for me on current master:
````
$ ./rdkafka_example_cpp -P -t "Position" -p 1
% Created producer rdkafka#producer-0
test
% Produced message (4 bytes)
test!!
% Produced message (6 bytes)
Message delivery for (4 bytes): Success
Waiting for 1
Message delivery for (6 bytes): Success
$ 


$ ./rdkafka_example_cpp -C -t "Position" -p 1
% Created consumer rdkafka#consumer-0
Read msg at offset 0
test
Read msg at offset 1
test!!
^C
$ 
`````

**Comment by cleo-yin** [comment]
hi edenhill, thanks for your quick response. I just cloned the master branch, and it's the same as before. I just modified the brokers from "localhost" to another server, it's no problem with C version consumer/producer and C++ producer, but the C++ consumer still didn't work, is there anything special for C++ client to be configured on the server side?

**Comment by edenhill** [comment]
The C++ interface is just a thin layer on top of the C library, so there shouldn't be any operational differences.

Try specifying the offset with `-o beginning` and see if that helps.
If that doesn't work please run rdkafka_example_cpp with `-d topic,msg` and paste the log output here.

Thanks

**Comment by cleo-yin** [comment]
Hi edenhill, I just upgraded the kafka server to 0.8.2.1, it worked well now,before it's 0.8.0, sorry for the mistake, I will close this issue now, thanks.
