### ISSUE TITLE
error appears when sending messages

### ISSUE THREAD

**Issue by rogerlee24** [edenhill/librdkafka#3661]
when the producer sends a message, the following error appears, can you help me? 

![image](https://user-images.githubusercontent.com/57137841/147733574-8dbc261d-18e0-46c4-9b73-2e4f6576f79a.png)
I believe the error occurred during the execution of this function .
![image](https://user-images.githubusercontent.com/57137841/148178620-640ac3bc-189c-4d05-a0a7-b12f3a079986.png)

![image](https://user-images.githubusercontent.com/57137841/147733844-ca1eec9d-1a39-4466-a329-c9a6f55a7d62.png)

thanks.

**Comment by rogerlee24** [comment]
@NZKoz @ctrochalakis @thijsc @janmejay can you help me ? thanks!

**Comment by edenhill** [comment]
You will need to use a debugger to understand what is going on. Try to reduce the program to a minimum reproducible test case, then use the debugger and single step to find the cause.
