### ISSUE TITLE
Error: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.

### ISSUE THREAD

**Issue by radhaagr** [edenhill/librdkafka#3688]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by radhaagr** [comment]
I am not sure what I am doing wrong. I keep getting below error with the following command -
/serdes-kafka-avro-client -P -b "127.0.0.1:9092" -t "topic-name" -p 0  -r "127.0.0.1:8081" -s "1"
% Using schema (null) with id 1
FATAL: % Failed to create producer: Failed to create thread: Success (0)
serdes-kafka-avro-client: tpp.c:82: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed

**Comment by edenhill** [comment]
That's an issue with libserdes that's being fixed in this PR: 
https://github.com/confluentinc/libserdes/pull/44/commits/913eaa293313a719263c650f63347c0764f92de1

**Comment by radhaagr** [comment]
Thanks for the lead.

**Comment by yuvalif** [comment]
@edenhill which librdkafka release has this fix?
