### ISSUE TITLE
Size of producer batch queues not updating correctly

### ISSUE THREAD

**Issue by kcnguyen** [edenhill/librdkafka#369]
Referencing issue #368, which was closed and I cannot reopen it so I'm opening a new issue.

I'm still noticing that the size of the queue of messages waiting to be delivered is not updating correctly. I can see the message delivered in kafka, yet the size of the queue is not decreasing. I am calling the function rd_kafka_outq_len (rd_kafka_t *rk) to get the size of the queue. I think there is a bug here.

**Comment by edenhill** [comment]
rd_kafka_outq_len() correlates to the number of messages in different internal librdkafka queues.

Is it possible that you are not calling rd_kafka_poll() to handle delivery reports?

**Comment by kcnguyen** [comment]
I do not call rd_kafka_poll(). I call rd_kafka_outq_len (rd_kafka_t *rk) to check the length of the queue after each time I call rd_kafka_produce_batch. Sounds like I need to call rd_kafka_poll for rd_kafka_outq_len to work correctly?

**Comment by edenhill** [comment]
You typically dont need to call outq_len() at all except for when you are waiting for librdkafka to shut down when you are exiting your application.

What you need to do continually though is serve the delivery report queue by calling `rd_kafka_poll()` frequently.

Either you do something like:
````
  ...
  r = rd_kafka_produce();
  if (r == -1) // error handling
  // Serve delivery report and error queue. This call will not block and will not call the delivery callback
  // for the message that was just produced, but rathre for previous messages that have now been acked by the broker.  
  rd_kafka_poll(rk, 0);
````

Alternatively you run poll from a separate thread, e.g.:
````
  while (run)
    rd_kafka_poll(rk, 1000);
````

It really depends on your application design.
