### ISSUE TITLE
Metadata leader query timer backoff never applied

### ISSUE THREAD

**Issue by larry-cdn77** [edenhill/librdkafka#3690]
Further to #3237, `timers_run` [unschedules](https://github.com/ajbarb/librdkafka/blob/efcdcee986d8998116e024e7de3541e41abfd530/src/rdkafka_timer.c#L281) the leader query timer before invoking its callback, `rd_kafka_metadata_leader_query_tmr_cb`. The callback's attempt to back-off then always fails on the [scheduled condition](https://github.com/ajbarb/librdkafka/blob/efcdcee986d8998116e024e7de3541e41abfd530/src/rdkafka_timer.c#L176).

```
        if (rd_kafka_timer_scheduled(rtmr)) {
                rtmr->rtmr_interval *= 2;
                rd_kafka_timer_unschedule(rkts, rtmr);
        }
```

To be sure of the above analysis I printed backoff attempts using version 1.8.2 and the backoff function would indeed always come in with an unscheduled timer, and actually not do the backoff.

**Comment by edenhill** [comment]
I think you're right.
The rtmr_interval should be doubled regardless of scheduled(), and it should not be passed as extra_us to schedule().
Do you agree?
Would you like to submit a PR?

**Comment by larry-cdn77** [comment]
Disregarding the timer's scheduled status sounds fine. The exponential back-off function is currently only called from a timer callback, in which case doubling unconditionally should not cause a problem.

I will submit a pull request separately

**Comment by larry-cdn77** [comment]
Now tracked under pull request #3820
