### ISSUE TITLE
Problem about install librdkafka

### ISSUE THREAD

**Issue by siyuanmami** [edenhill/librdkafka#370]
Hi edenhill,
During installing librdkafka on my ubuntu 14.04 system, I came across this error when executing ./configure command:

root@ip-10-0-0-18:~/kafka_client/librdkafka-0.8.6# ./configure
using cache file config.cache
checking for OS or distribution... ok (Ubuntu)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok (cached)
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok (cached)
checking executable ld... ok (cached)
checking executable nm... ok (cached)
checking executable objdump... ok (cached)
checking executable strip... ok (cached)
checking for pkgconfig (by command)... ok (cached)
checking for install (by command)... ok (cached)
checking for PIC (by compile)... ok (cached)
checking for GNU-compatible linker options... ok (cached)
checking for GNU linker-script ld flag... ok (cached)
checking for __atomic_32 (by compile)... ok (cached)
checking for __atomic_64 (by compile)... ok (cached)
checking for socket (by compile)... ok (cached)
parsing version '0x00080600'... ok (0.8.6)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for perl (by command)... ok (cached)
Generated rdkafka.pc
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  ARCH                     x86_64
  CPU                      generic
  MKL_DISTRO               Ubuntu
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -g -O2 -fPIC -Wall -Werror -Wfloat-equal -Wpointer-arith
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.8.6
  LIBS                     -lpthread -lz   -lrt
  CFLAGS
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
Generated config.cache

Now type 'make' to build

for those failed items, do I need to fix them before executing make command? 
I am not familiar with shell script, could you help to tell me if I miss anything? c complier, c++ complier, or something like that ?
I tried executing make command yesterday, but looked the installation failed ( I can not use librdkafka ) although there was no error prompt during the installation.

Thanks!

**Comment by DEvil0000** [comment]
`cached` may not be a good thing - try without cached configure..
you will need to provide some more input to get a helpful answer. (make output etc..)

**Comment by edenhill** [comment]
The "failed" configure tests are not typically critical, they only try to find different alternatives, or to enable/disable certain futures.
If a required test fails it will be very evident by a large error printout at the end of ./configure execution.

As @DEvil0000 mentions you will need to provide the output of `make` and `sudo make install`.
Also make sure that your own application has /usr/local/lib in its library path (e.g., /etc/ld.so.conf or LD_LIBRARY_PATH).

I see that you are running on Ubuntu so you could try `sudo apt-get install librdkafka1`

**Comment by siyuanmami** [comment]
@DEvil0000 Thank you for you advice. I tried to install it again, and it worked now.

**Comment by siyuanmami** [comment]
@edenhill 
OK. Thank you for your explanation. I have installed it successfully now even with those "failed" items. 
So actually, I can install it by sudo apt-get install librdkafka1 instead, right ?

**Comment by edenhill** [comment]
Installing the debian/ubuntu package is easier but might give you an older version (which is usually okay), For the latest stuff you'll need to build your own and use steps given above.

**Comment by siyuanmami** [comment]
@edenhill 
Hi edenhill,
I am installing librdkafka on centos 6.5, and after executing ./configure, I found the check for these items failed:
checking for __atomic_32 (by compile)... failed
checking for __atomic_32_lib (by compile)... failed
checking for __sync_32 (by compile)... ok
checking for __atomic_64 (by compile)... failed
checking for __atomic_64_lib (by compile)... failed

Could you help to tell me if there is anything necessary I miss to install ? 
Thanks!

**Comment by edenhill** [comment]
librdkafka requires 64-bit atomics but it seems like your arch or toolchain does not provide it.
You can provide the full output of `./configure`, and `uname -a` and `gcc --version`

Thanks

**Comment by siyuanmami** [comment]
@edenhill 
Thanks for you help.
1.  The full output of ./configure is as follows:
checking for OS or distribution... ok (CentOS)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... failed
checking for __atomic_32_lib (by compile)... failed
checking for __sync_32 (by compile)... ok
checking for __atomic_64 (by compile)... failed
checking for __atomic_64_lib (by compile)... failed
checking for __sync_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x00080600'... ok (0.8.6)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for perl (by command)... ok
Generated rdkafka.pc
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  ARCH                     x86_64
  CPU                      generic
  MKL_DISTRO               CentOS
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -g -O2 -fPIC -Wall -Werror -Wfloat-equal -Wpointer-arith
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.8.6
  LIBS                     -lpthread -lz   -lrt
  CFLAGS
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
Generated config.cache

Now type 'make' to build

2. The output of uname -a is:
Linux iZ94d7vqlolZ 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

3. The output of gcc --version is:
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Thanks!

**Comment by edenhill** [comment]
There is no error, you have all you need to build and install the library.

**Comment by siyuanmami** [comment]
@edenhill 

Thanks, edenhill.
But not sure why after I install this php extension which is based on librdkafka, it tells me:
PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/kafka.so' - librdkafka.so.1: cannot open shared object file: No such file or directory in Unknown on line 0
https://github.com/EVODelavega/phpkafka

**Comment by edenhill** [comment]
You probably need to add /usr/local/lib to your library search path, since that's where librdkafka is installed by default.

So you could try doing `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib` before running your PHP script, or update /etc/ld.so.conf to include /usr/local/lib

**Comment by edenhill** [comment]
https://github.com/EVODelavega/phpkafka#requirements

**Comment by siyuanmami** [comment]
@edenhill 
Thanks for you great help.
I've tried export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib, it still does not work.
The same error.

**Comment by siyuanmami** [comment]
@edenhill 
By the way, I uninstalled librdkafka by executing 'make clean', and installed it again, is this alright ? 

Thanks!

**Comment by edenhill** [comment]
Try this:
`./configure --prefix=/usr`
`sudo make install`

**Comment by siyuanmami** [comment]
@edenhill 
Do you mean ./configure --prefix=/usr for installing librdkafka ?

**Comment by edenhill** [comment]
Yes
Den 16 okt 2015 11:15 skrev "siyuanmami" <notifications@github.com>:

**Comment by siyuanmami** [comment]
@edenhill 
Then librdkafka will be installed under /usr, right ?

**Comment by edenhill** [comment]
Yes
Den 16 okt 2015 11:16 skrev "siyuanmami" <notifications@github.com>:

**Comment by siyuanmami** [comment]
@edenhill 
Do I need to "make clean" the previous one before "./configure --prefix=/usr" ? 
Then I need to export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr, right ?

Thanks!

**Comment by edenhill** [comment]
Nope, just reconfigure and install
Den 16 okt 2015 11:34 skrev "siyuanmami" <notifications@github.com>:

**Comment by siyuanmami** [comment]
@edenhill 
OK.
May I know the reason of doing so ?
Thanks!

**Comment by edenhill** [comment]
/usr is already in the default library search path.
Den 16 okt 2015 11:37 skrev "siyuanmami" <notifications@github.com>:

**Comment by edenhill** [comment]
Did this make it work?

**Comment by siyuanmami** [comment]
@edenhill 
Thanks you so much for you patience!
I am so glad that I installed that php extension successfully after I updated /etc/ld.so.conf to include /usr/local/lib !
I really appreciate your help and have learned a lot from you!
^_^

**Comment by edenhill** [comment]
Perfect!

**Comment by sp-suresh** [comment]
I faced the same. Below is the errors which says `not ok`
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.13.0-45-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/local/ZEBPAY/suresh.prajapati/projects/tradesync/node_modules/int64-native
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! int64-native@0.4.0 install: `node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the int64-native@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by edenhill** [comment]
@sp-suresh The actual build error is probably above the pasted output

**Comment by edenhill** [comment]
Those errors look like v8 version errors:
```
../src/Int64.cc:85:43: error: no matching function for call to ‘v8::Value::ToNumber()’
         obj = new Int64(info[0]->ToNumber());
```

and are not related to librdkafka in any way.
File the issue on node-rdkafka instead.

**Comment by amikar** [comment]
sudo apt-get install build-essential 

Worked for me

**Comment by chandarkumar7385** [comment]
Trying to configure librdkafak in solaris 11

root@SOL1:~/librdkafka# ./configure --install-deps
using cache file config.cache
checking for OS or distribution... ok (sunos)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... failed (disable)
checking executable strip... ok
checking executable libtool... failed (disable)
checking executable ranlib... ok
checking for pkgconfig (by command)... failed
checking for GNU install... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... failed
checking for Solaris linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x010700ff'... ok (1.7.0)
checking for librt (by compile)... ok
checking for libpthread (by compile)... ok
checking for c11threads (by compile)... ok
checking for libdl (by compile)... ok
checking for zlib (by compile)... ok
checking for libcrypto (by compile)... ok
checking for libssl (by compile)... ok
checking for libsasl2 (by compile)... ok
checking for libzstd (by compile)... failed
building dependency libzstd... failed (disable)
libzstd source build failed, see /root/librdkafka/mklove/deps/src/libzstd/_mkl_install.log for details. Last 50 lines:
### Installing libzstd 1.3.8 from source to /root/librdkafka/mklove/deps/dest/libzstd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   623  100   623    0     0   1393      0 --:--:-- --:--:-- --:--:--  1393
100 1819k  100 1819k    0     0  1336k      0  0:00:01  0:00:01 --:--:-- 6494k
make: Warning: Ignoring DistributedMake -j option
make: Fatal error: Don't know how to make target `install'

real    0m0.392s
user    0m0.005s
sys     0m0.014s
checking for libm (by compile)... ok
checking for liblz4 (by compile)... failed (disable)
checking for syslog (by compile)... ok
checking for rapidjson (by compile)... failed (disable)
checking for crc32chw (by compile)... failed (disable)
checking for regex (by compile)... ok
checking for rand_r (by compile)... ok
checking for strndup (by compile)... ok
checking for strlcpy (by compile)... ok
checking for strerror_r (by compile)... ok
checking for strcasestr (by compile)... ok
checking for pthread_setname_gnu (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for python3 (by command)... ok
checking for getrusage (by compile)... failed (disable)
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr/local
  MKL_DISTRO               sunos
  SOLIB_EXT                .so
  ARCH                     i86pc
  CPU                      generic
  GEN_PKG_CONFIG           y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  STRIP                    strip
  RANLIB                   ranlib
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -D__EXTENSIONS__
  PKG_CONFIG               pkg-config
  INSTALL                  ginstall
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,-M
  RDKAFKA_VERSION_STR      1.7.0
  MKL_APP_VERSION          1.7.0
  LIBS                     -lm -lsasl2 -lssl -lcrypto -lcrypto -lz -ldl -lpthread -lrt -lpthread -lrt
  MKL_PKGCONFIG_LIBS_PRIVATE -lm -lsasl2 -lssl -lcrypto -lcrypto -lz -ldl -lpthread -lrt -lpthread -lrt
  CXXFLAGS                 -Wno-non-virtual-dtor
  CFLAGS                   -std=c99
  SYMDUMPER                $(NM) -D
  MKL_DYNAMIC_LIBS         -lm -lsasl2 -lssl -lcrypto -lcrypto -lz -ldl -lpthread -lrt -lpthread -lrt
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  runstatedir              /usr/local/var/run
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
  BUILT_WITH               GCC GXX INSTALL GNULD LDS C11THREADS LIBDL PLUGINS ZLIB SSL SASL_CYRUS HDRHISTOGRAM SYSLOG SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER
Generated config.cache

Now type 'make' to build


root@SOL1:~/librdkafka# make
make: Fatal error in reader: mklove/Makefile.base, line 15: Unexpected end of line seen
root@SOL1:~/librdkafka#

**Comment by Avi29n** [comment]
In Redhat7.8
 getting below error when i am doing make or make install.
Please suggest.

###############################

checking for C compiler from CC env... failed
checking for C++ compiler from CXX env... failed
checking for librt (by pkg-config)... failed
checking for libpthread (by pkg-config)... failed
checking for c11threads (by pkg-config)... failed
checking for c11threads (by compile)... failed (disable)
checking for libdl (by pkg-config)... failed
checking for zlib (by pkg-config)... failed
checking for zlib (by compile)... failed
checking for libcrypto (by pkg-config)... failed
checking for libcrypto (by compile)... failed
installing dependencies (yum install -y openssl-devel) libcrypto... using yum
checking for libzstd (by pkg-config)... failed
checking for libzstd (by compile)... failed
checking for libcurl (by pkg-config)... failed
checking for libcurl (by compile)... failed
checking for libcrypto (by pkg-config)... failed
checking for libcrypto (by compile)... failed
installing dependencies (yum install -y openssl-devel) libcrypto... using yum
checking for libzstd (by pkg-config)... failed
checking for libzstd (by compile)... failed
checking for libcurl (by pkg-config)... failed
checking for libcurl (by compile)... failed
------------------------

gcc  -shared -Wl,-soname,librdkafka.so.1 -Wl,--version-script=librdkafka.lds rdkafka.o rdkafka_broker.o rdkafka_msg.o rdkafka_topic.o rdkafka_conf.o rdkafka_timer.o rdkafka_offset.o rdkafka_transport.o rdkafka_buf.o rdkafka_queue.o rdkafka_op.o rdkafka_request.o rdkafka_cgrp.o rdkafka_pattern.o rdkafka_partition.o rdkafka_subscription.o rdkafka_assignment.o rdkafka_assignor.o rdkafka_range_assignor.o rdkafka_roundrobin_assignor.o rdkafka_sticky_assignor.o rdkafka_feature.o rdcrc32.o crc32c.o rdmurmur2.o rdfnv1a.o cJSON.o rdaddr.o rdrand.o rdlist.o tinycthread.o tinycthread_extra.o rdlog.o rdstring.o rdkafka_event.o rdkafka_metadata.o rdregex.o rdports.o rdkafka_metadata_cache.o rdavl.o rdkafka_sasl.o rdkafka_sasl_plain.o rdkafka_interceptor.o rdkafka_msgset_writer.o rdkafka_msgset_reader.o rdkafka_header.o rdkafka_admin.o rdkafka_aux.o rdkafka_background.o rdkafka_idempotence.o rdkafka_cert.o rdkafka_txnmgr.o rdkafka_coord.o rdvarint.o rdbuf.o rdmap.o rdunittest.o rdkafka_mock.o rdkafka_mock_handlers.o rdkafka_mock_cgrp.o rdkafka_error.o rdkafka_sasl_cyrus.o rdkafka_sasl_scram.o rdkafka_sasl_oauthbearer.o snappy.o rdgz.o rdkafka_zstd.o rdhdrhistogram.o rdkafka_ssl.o rdhttp.o rdkafka_sasl_oauthbearer_oidc.o rdkafka_lz4.o rdxxhash.o lz4.o lz4frame.o lz4hc.o rddl.o rdkafka_plugin.o -o librdkafka.so.1 -lm -pthread -L/usr/local/lib -lcurl -lssl -lgssapi_krb5 -lkrb5 -lcom_err -lk5crypto -lcrypto -ldl -lzstd -lz   /home/c08752/librdkafka/mklove/deps/dest/usr/lib/libzstd.a -lsasl2   -lssl -lcrypto   -lcrypto   -lz   -ldl -lpthread -lrt
/bin/ld: cannot find -lcurl
/bin/ld: cannot find -lzstd
collect2: error: ld returned 1 exit status
make[1]: *** [librdkafka.so.1] Error 1
make[1]: Leaving directory `/home/XYZMNP/librdkafka/src'
make: *** [libs] Error 2

**Comment by edenhill** [comment]
@Avi29n please provide the full configure and make output.
