### ISSUE TITLE
Pick the latest stable version of librdkafka + RD_KAFKA_MSG_F_COPY

### ISSUE THREAD

**Issue by rathdeep** [edenhill/librdkafka#371]
For production, how  do we usually pick or from where we download the latest stable librdkafka library version.

One basic question:
 RD_KAFKA_MSG_F_COPY: Kafka will create a copy and "DELETE IT WHEN IT IS DONE" ( cannot find this comment, just reconfirming)

**Comment by edenhill** [comment]
The latest release on github is the latest stable release, so at this moment that is 0.8.6:
https://github.com/edenhill/librdkafka/releases/tag/0.8.6

Yes, your assumption about MSG_F_COPY is correct:
The produce() call will instantly copy the payload instead of using it without copy.

**Comment by rathdeep** [comment]
And the copy will be deleted after it is used.

**Comment by edenhill** [comment]
The copy is automatically deleted after use (when the delivery report callback returns), yes.

**Comment by rathdeep** [comment]
Thanks. 0.8.6 was released on March and will not have bug fixes after that. When is the plan to release  next version.

**Comment by edenhill** [comment]
There will be a large feature release in about a month.
If there are any critical bugs found before that a maintenance release will be shipped first.

Is there anything in particular (fix or feature) you are waiting for?

**Comment by rathdeep** [comment]
I was looking for https://github.com/edenhill/librdkafka/issues/342. But I just downloaded 0.8.6 source code and see the correct file in there. So not an issue. Thanks.

**Comment by rathdeep** [comment]
Actually found a RD_KAFKA_MSG_F_FREE bug which is fixed and not present in 0.8.6. 
https://github.com/rthalley/librdkafka/commit/bff4beddbc4208d3e631c46972b821d06d39a2c0

Surely interested in this.
