### ISSUE TITLE
Expose HighwaterMarkOffset to subscribers

### ISSUE THREAD

**Issue by bnham** [edenhill/librdkafka#372]
It appears that librdkafka does parse out HighwaterMarkOffset from reply headers to detect EOF conditions:

```
	_READ_REF(hdr, sizeof(*hdr));
	hdr->Partition = ntohl(hdr->Partition);
	hdr->ErrorCode = ntohs(hdr->ErrorCode);
	hdr->HighwaterMarkOffset = be64toh(hdr->
					   HighwaterMarkOffset);
	hdr->MessageSetSize = ntohl(hdr->MessageSetSize);

	// ...

	/* If this is the last message of the queue,
	 * signal EOF back to the application. */
	if (hdr->HighwaterMarkOffset == rktp->rktp_next_offset
	    &&
	    rktp->rktp_eof_offset != rktp->rktp_next_offset) {
		hdr->ErrorCode =
			RD_KAFKA_RESP_ERR__PARTITION_EOF;
		rktp->rktp_eof_offset = rktp->rktp_next_offset;
	}
```

However, it looks like this information isn't passed along to subscribers in (for instance) `rd_kafka_message_t`. This is useful info for consumers since it helps estimate how far behind a consumer is without performing additional requests to find the latest offset for a partition.

**Comment by edenhill** [comment]
The consumer lag (how far behind a consumer is from the tail offset) is  constantly monitored by librdkafka and returned with the stats for each topic+partition as `consumer_lag`. Unit is number of messages.

Hope that helps

**Comment by edenhill** [comment]
The current implementation polls the high watermark every `statistics.interval.ms` which means the `consumer_lag` field in the stats may be outdated by that long.

The new implementation which will be available in a couple of weeks uses the high watermark directly from the Fetch response instead, so it is always up to date.

**Comment by bnham** [comment]
I see, good to know. Using the consumer_lag field is a good workaround until the high watermark is exposed.

**Comment by edenhill** [comment]
The high watermark is already exposed as "hi_offset' in the stats, but with the current implementation it might be a bit outdated.
