### ISSUE TITLE
What is the proper way to replace deprecated rd_kafka_set_logger ?

### ISSUE THREAD

**Issue by remicollet** [edenhill/librdkafka#3724]
rd_kafka_set_logger is deprecated, so what is the proper way to set it

Immediate idea was 

```
-    rd_kafka_set_logger(rk, logger);
+    rd_kafka_conf_set_log_cb(rd_kafka_conf(rk), logger);
```

But rd_kafka_conf return a const pointer, while rd_kafka_conf_set_log_cb expect a non const one.

Shouldn't the "const" be dropped?
Or is there a better way ?

**Comment by rolandyoung** [comment]
I set up the config before constructing the rk handle - something like this
```
rd_kafka_conf_t* globalConfig = rd_kafka_conf_new();
/* other settings... */
rd_kafka_conf_set_log_cb(globalConfig, logger);
rd_kafka_t* producer = rd_kafka_new(RD_KAFKA_PRODUCER, rd_kafka_conf_dup(globalConfig), errstr, ERRSTR_SIZE);
```
I'm pretty sure I followed the style of the example code when I wrote this. I'm using `rd_kafka_conf_dup` because the same global config settings are used for more than one rdkafka client.

**Comment by remicollet** [comment]
ok at construct time... but if you want to change the logger later, this means you have to keep the conf address, while `rd_kafka_conf` is designed to retrieve it.

**Comment by edenhill** [comment]
The `rd_kafka_conf_t` object is consumed and destroyed by a successful `rd_kafka_new()` call, thus not supporting any configuration changes after the client instance has been created.
If you need to change the log callback after instance creation I recommend solving that on the application side, i.e., have a fixed log_cb and have an application-level log callback called from it.

**Comment by remicollet** [comment]
ok, will continue to use the old `rd_kafka_set_logger` call.

(too much refactoring for me trying to help @arnaud-lb on https://github.com/arnaud-lb/php-rdkafka)
