### ISSUE TITLE
MSK not working locally with public access on

### ISSUE THREAD

**Issue by Coldplayer1995** [edenhill/librdkafka#3728]
Description
===========
 ```c# var config = new ConsumerConfig
            {
                BootstrapServers = aws_bootstrap_servers,
                GroupId = _groupId,
                AutoOffsetReset = _autoOffsetReset,
                SslCertificateLocation = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "certificates/signed-certificate-from-acm.crt"),
                SslKeyLocation = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "certificates/client.key"),
                SecurityProtocol = SecurityProtocol.Ssl,
            };
```

ERROR: Application Crashed: ssl.key.location failed: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>
Setup MSK in AWS, enable public access with TLS, create private CA in AWS and sign the Certificate request with it using aws-cli

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `Confluent.Kafka 1.8.2`
 - [x ] Apache Kafka version: `2.6.2`
 - [ x] librdkafka client configuration: `
 auto.create.topics.enable = true
zookeeper.connection.timeout.ms = 1000
log.roll.ms = 604800000
allow.everyone.if.no.acl.found = false
 - `
 - [x] Operating system: `windows 10`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This sounds like an MSK issue.

**Comment by Coldplayer1995** [comment]
@edenhill  managed to solve that one, it might be useful to have it with CA authority as hosted in AWS :)
` var config = new ConsumerConfig
            {
                BootstrapServers = _bootstrapServers,
                GroupId = _groupId,
                AutoOffsetReset = _autoOffsetReset,
                SslCertificateLocation = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "certificates/danton-certificate.pem"),
                SslKeyLocation = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "certificates/danton-key.pem"),
                SecurityProtocol = SecurityProtocol.Ssl,
            };`

we are referring the pem formats with CSR being signed in private CA in AWS. and working great.
