### ISSUE TITLE
C++ bindings missing RD_KAFKA_OFFSET_TAIL() equivalent

### ISSUE THREAD

**Issue by bwelling** [edenhill/librdkafka#374]
With the C bindings, callers can consume starting at an offset from the end, using RD_KAFKA_OFFSET_TAIL(), but there doesn't appear to be anything similar defined in the C++ API.  A caller could include both the C and C++ headers, and call RD_KAFKA_OFFSET_TAIL() (and that seems to work), but I believe the C++ API should include way to do this directly.  Simply copying the macro would work, but there might be a better way.

**Comment by edenhill** [comment]
I guess it would be more idiomatic to implement it as a method to avoid using macros, e.g., RdKafka::Consumer::OffsetTail(..) or similar.
Would you mind whipping up a pull request?

**Comment by edenhill** [comment]
Fixed
