### ISSUE TITLE
How to add a new partition?

### ISSUE THREAD

**Issue by kcnguyen** [edenhill/librdkafka#375]
Is there a way in librdkafka to add a new partition to a topic in kafka?

**Comment by edenhill** [comment]
You mean to extend a 4-partition topic to have 5 topics?
librdkafka can't do that (there is no admin protocol API to kafka yet), you need to use the kafka-topics.sh tool that resides in the official Kafka distribution's bin/ directory.

E.g.:
`bin/kafka-topics.sh --zookeeper localhost --alter --topic mytopic --partitions 5`
