### ISSUE TITLE
Confluent.Kafka.ConsumeException: Unknown broker error

### ISSUE THREAD

**Issue by Atallah-Hammad** [edenhill/librdkafka#3768]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
I'm using [azure-event-hubs-for-kafka], and sometimes getting this error when consume=>
Confluent.Kafka.ConsumeException: Unknown broker error
at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)

How to reproduce
================
Using .NET 5 class library with Confluent.Kafka 1.8.2, and this error occurs also when using 1.6.2.

Is BrokerVersionFallback config property can help here?

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.8.2`
 - [x] Apache Kafka version: `azure-event-hubs-for-kafka`
 - [x] librdkafka client configuration: `ConsumerConfig
            {
                BootstrapServers = KafkaCredentials.BrokerList,
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SocketTimeoutMs = 60000,
                SessionTimeoutMs = 30000,
                SaslMechanism = SaslMechanism.Plain,
                SaslUsername = "$ConnectionString",
                SaslPassword = KafkaCredentials.ConnectionString,
                GroupId = consumerGroup,
                AutoOffsetReset = AutoOffsetReset.Latest
            }`
 - [x] Operating system: ``
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Please enable debugging by setting `Debug = "all"` in your ConsumerConfig and provide the full log output.

**Comment by edenhill** [comment]
Closing in favour of discussion thread https://github.com/edenhill/librdkafka/discussions/3769
