### ISSUE TITLE
Transaction blocked during a cluster roll

### ISSUE THREAD

**Issue by LGouellec** [edenhill/librdkafka#3779]
Description
===========

I'm trying to reproduce a client's problem (a transaction blocked during cluster maintenance), we found a behavior very strange on librdkafka-based client side.

Use-case :
 " if a cluster roll happens during a transaction, and if the broker down was the transaction coordinator of this transaction, what happens ?"

After a lot of tests, often the librdkafka-based client doesn't complete the AbortTransaction operation. Client will be disposed of 10 minutes after trying to abort the transaction. There is a bug in librdkafka-based's client ? or broker side ?

Seems transaction timeout (10 seconds in my example) is not considered ever. Because my application is blocked in the AbortTransaction method for 10 minutes, before crashing and throwing a KafkaException.

``` csharp
producer.AbortTransaction(TIMEOUT_KAFKA_OPS)
```

I created this issue on librdkafka project, even I use `confluent-kafka-dotnet` package, it's just a binding on  [`abort_transaction(IntPtr rk, IntPtr timeout)`](
https://github.com/confluentinc/confluent-kafka-dotnet/blob/9baf1875d70dd9128ca87972637432f37f8a19dc/src/Confluent.Kafka/Impl/SafeKafkaHandle.cs#L536). 
But doesn't matter, I can create one issue `confluent-kafka-dotnet`  too if you want.

How to reproduce
================

I created a repository where you can reproduce the problem easily (just run start.sh, and check producer logs container)
https://github.com/LGouellec/transaction-roll-dotnet

You can find complete example logs where the abort transaction doesn't work and the application crashes 10 minutes after opening the transaction (L3324 to L5460 - Abort operation doesn't work, block 10 minutes, before crashing my producer).
https://github.com/LGouellec/transaction-roll-dotnet/blob/master/issue_debug_all.log

You have an another log file with less debug context [here](https://github.com/LGouellec/transaction-roll-dotnet/blob/master/issue.log). 

README.md is completed with more informations and schemas.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.8.2`
 - [X] Apache Kafka version: `3.0.0`
 - [ ] librdkafka client configuration: `enable.idempotence=true, max.in.flight = 5, use transaction API in producer`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [X] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [X] Critical issue

**Comment by edenhill** [comment]
Thanks for a great report 💯 !

Your docker-based reproducer worked great to reproduce the issue on 1.8.2.
There are two issues at play here:
 1. confluent-kafka-dotnet's Flush() method stalls for a long time while waiting for the AddPartitionsToTxnRequests to the downed coordinator to time out. Standard librdkafka does not do this.  This is what causes the long stall, but is not a big problem in itself.
 2. librdkafka v1.9.0 (not yet released, so effectively master branch) has improved error handling and correctly handles the errors returned during cluster roll.
