### ISSUE TITLE
Endless Metadata Refresh when all brokers share the same host and port

### ISSUE THREAD

**Issue by rmb938** [edenhill/librdkafka#3784]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========

I am creating a Kafka proxy to federate multiple Kafka clusters behind one endpoint. I have noticed that librdkafka behaves differently than the native Java, Python and Golang clients.

When a metadata request is made and the response contains multiple brokers that all have the same host and port librdkafka endlessly makes metadata requests over and over.

Example logs in this gist https://gist.github.com/rmb938/4d4f30ac9126b1f7fb2044b3e05069f2

The native language clients for Java, Python and Golang don't seem to do this, they don't seem to care that the hosts and ports are the same for every broker and act as normal.

How to reproduce
================

I'm able to reproduce it using the confluent kafka Python and Golang libraries. To be able to reproduce it yourself though you will need to run my Kafka Proxy as it can't be replicated on a normal Kafka cluster.

I can walk though the steps needed to do this if desired. Code is here: https://github.com/rmb938/krouter

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v1.8.2`
 - [x] Apache Kafka version: `3.1.0`
 - [x] librdkafka client configuration: `bootstrap.servers=localhost:29092,debug=all`
 - [x] Operating system: `Fedora 34`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts - N/A
 - [ ] Critical issue

**Comment by edenhill** [comment]
Brokers are identified/mapped by their addr:port -> broker_id, 1:1. Having the same addr:port map to multiple broker ids breaks that mapping, your proxy is thus out of specification.
