### ISSUE TITLE
Fair Fetch scheduling

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#379]
Currently the list of partitions to fetch from a single broker are always in the same order which means that if an earlier partition in the list fills up the entire response message (fetch.message.max.bytes) the later partitions will not be served at all. This isn't fair!

A simple round-robin of the list head is probably sufficient to solve this issue.

**Comment by chengchengpei** [comment]
This is one feature I want http://stackoverflow.com/questions/33550872/how-kafka-consumer-prefetch-messages and http://stackoverflow.com/questions/33508365/can-flume-spark-storm-read-from-kafka-in-round-robin-way.

**Comment by edenhill** [comment]
The next version of librdkafka (due in a month or so) will have a round-robin fetch scheduler to promote fairness.

**Comment by fsaintjacques** [comment]
How about making it configurable, potential I see:

* random
* round-robin
* static (current behaviour)

**Comment by edenhill** [comment]
@fsaintjacques I dont really see the point, librdkafka already uses prefetching with backpressure so any partition that has reached the upper local queue threshold will be removed from the fetcher list and added back when it falls below the threshold again.

**Comment by edenhill** [comment]
Fixed on master
