### ISSUE TITLE
Consumer hangs in rd_kafka_destroy after using rd_kafka_offsets_store

### ISSUE THREAD

**Issue by jorendorff** [edenhill/librdkafka#3796]
Description
===========

The following API usage pattern causes a hang:

1. Create a topic partition list.
2. Create a new rd_kafka with `enable.auto.offset.store` set to `false`.
3. Do normal consumer stuff, using `rd_kafka_offsets_store`.
4. Destroy the rd_kafka.
5. Destroy the topic partition list.

The call to `rd_kafka_destroy()` in step 4 never returns. The broker thread gets stuck in an infinite loop, with debug output like:

```
%7|1649091085.898|TERMINATE|rdkafka#consumer-1| [thrd:localhost:29094/bootstrap]: localhost:29094/1: Handle is terminating in state INIT: 2 refcnts (0x61f000002020), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1649091085.899|TERMINATE|rdkafka#consumer-1| [thrd:localhost:29094/bootstrap]: localhost:29094/1: Handle is terminating in state INIT: 2 refcnts (0x61f000002020), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1649091085.900|TERMINATE|rdkafka#consumer-1| [thrd:localhost:29094/bootstrap]: localhost:29094/1: Handle is terminating in state INIT: 2 refcnts (0x61f000002020), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
...
```

I don't know if this is the same issue as #3143.

How to reproduce
================

It's super easy! Here's a test program that always reproduces the hang:

https://github.com/jorendorff/librdkafka-hang/tree/main/#setup

The test program is using `rd_kafka_offsets_store`. This calls `rd_kafka_topic_partition_get_toppar` which calls `rd_kafka_topic_partition_ensure_toppar` which stashes a reference to an `rd_kafka_toppar_t` in a private field of an `rd_kafka_topic_partition_t`. I think this extra reference causes the hang.

If you switch the order of teardown function calls so that the topic partition list is destroyed first, then there's no hang.

I have run this against the current `master` librdkafka.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): 88173384e9cdeea09a610d4a0cb575a5f04707f
 - [x] Apache Kafka version: Great question. 2.6, I think. I'm new to both Kafka and docker-compose, so I just did

     ```
     ❯ docker-compose exec -T kafka kafka-topics --version
    6.0.4-ccs (Commit:cc9e8c610c3903bb)
    ```

    [https://docs.confluent.io/platform/current/installation/versions-interoperability.html](This apparently maps to Kafka 2.6.x?)

 - [x] librdkafka client configuration:
    ```
    group.id=test
    bootstrap.servers=localhost:29094
    enable.partition.eof=false
    enable.auto.offset.store=false
    enable.auto.commit=true
    debug=consumer,cgrp,topic,fetch,broker
    ```
 - [x] Operating system: macOS 11.4
 - [x] Provide [logs (with `debug=..` as necessary) from librdkafka](https://gist.github.com/jorendorff/43c4015bc7ce71fdee4f6e51707e7f5a)
 - [ ] Provide broker log excerpts - Sorry, I don't know what this is.
 - [ ] Critical issue

**Comment by edenhill** [comment]
This is a great report, thank you! Others: take note!

But, I think the problem here is the termination sequence:
all objects that have been used with a specific rd_kafka_t instance must be destroyed prior to destroying that rd_kafka_t instance.

In this case the `tpl` list is destroyed after the `rd_kafka_t` instance, and as you say, the tpl holds a reference to a partition object:
https://github.com/jorendorff/librdkafka-hang/blob/main/rdkafka-hang.c#L132-L136

**Comment by jorendorff** [comment]
Ah, yes, the manual is very clear about this ([here](https://docs.confluent.io/platform/current/clients/librdkafka/html/md_INTRODUCTION.html) under Usage > Termination).

Thanks for the instant turnaround!
