### ISSUE TITLE
Producer not timing out on messages in the queue

### ISSUE THREAD

**Issue by sanbhidu** [edenhill/librdkafka#382]
I wrote a kafka producer using this lib and set the message.timeout.ms equal to 1000.
While trying to simulate the broker shutdown, I came across an issue wherein some of the messages in the queue just wont time out.

Basically I run my producer and midway take down the broker and then this happens.

Here are the config options I am using:
Global:
queue.buffering.max.messages=1000
delivery.report.only.error=true
message.send.max.retries=1
topic.metadata.refresh.interval.ms=100
socket.timeout.ms=10000
socket.keepalive.enable=true
broker.address.ttl=1000
topic.metadata.refresh.fast.cnt=10
socket.max.fails=1
Topic:
message.timeout.ms=1000
request.required.acks=0

**Comment by edenhill** [comment]
The problem might be with `request,required.acks=0`:
Not requiring any acks to ProduceRequests means librdkafka will send/produce messages as quickly as the network allows and assume all messages that were accepted by the kernel's sendmsg() to have succeeded.
You are also using `delivery.report.only.error=true` which means you wont get any delivery report callbacks for succesfully sent messages.
So my guess is that the lost messages are in transit to the broker when the broker is taken down, but from librdkafka's point of view with `request.reqiured.acks=0` it thinks all messages were succesfully delivered.

Thats my theory, but, you are saying that "some of the messages in the queue just wont time out".
What queue are you referring to?  rd_kafka_outq_len()?

**Comment by sanbhidu** [comment]
Yeah that queue.
So before exiting the program I check if the queue lenght is zero and then exit.
As this is not happening, my program gets stuck at that point.
I tried this without the request.required.acks=0 option too.
The behaviour is the same.
Most of them timeout, but a few would stay in the queue forever.

I do something exactly like this 
while (run && rd_kafka_outq_len(rk) > 0)
			rd_kafka_poll(rk, 100);

But the len stays above 0.

**Comment by edenhill** [comment]
Okay, just reproduced this with rdkafka_performance:
````
$ examples/rdkafka_performance -b 0:9091 -t test -p 0 -r 1000 -s 10 -c 10000 -P -v -X topic.message.timeout.ms=1000
......
......
<kill broker after a couple of seconds>
.....
% 10000 messages produced (100000 bytes), 932 delivered (offset 0, 9041 failed) in 12001ms: 77 msgs/s and 0.00 Mb/s, 0 produce failures, 27 in queue, no compression
````

Finally ends up with 27 messages in the queue that are not timed out.
Will look in to to this.

Thanks for your detailed bug report.

**Comment by edenhill** [comment]
This should be fixed now with this commit on master:
https://github.com/edenhill/librdkafka/commit/a11bf887f1384bbb8f92469ebd84d5fdb9735b2a

**Comment by sanbhidu** [comment]
Thank you
