### ISSUE TITLE
C++ Api consume messages from multiple topics and partitions 

### ISSUE THREAD

**Issue by bitxel** [edenhill/librdkafka#383]
Hi, all:
Is there any C++ api that can consume messages from multiple topics and partitions simultaneously in a thread, just like the C api `rd_kafka_consume_start_queue()`.
Or what's the best approach to consume multiple partitions in a thread?
Thanks.

**Comment by edenhill** [comment]
Hi,

@macisamuele is working on a C++ queue interface, you can follow his work on gitter:
https://gitter.im/edenhill/librdkafka

**Comment by edenhill** [comment]
Fixed
