### ISSUE TITLE
socket.connection.setup.timeout.ms

### ISSUE THREAD

**Issue by dndhypothesis** [edenhill/librdkafka#3858]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "socket.connection.setup.timeout.ms""}

How to reproduce
================
....
self.cfg = {
        "socket.keepalive.enable": True,
        "socket.connection.setup.timeout.ms": 3000,
        "socket.max.fails": 0,
        "socket.timeout.ms":  10000,
        "reconnect.backoff.ms": 1000,
....

self._producer = kafkaProducer(self.cfg)
....

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `with confluent-kafka`
 - [x] Apache Kafka version: ` python confluent-kafka 1.8.2`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `ubuntu 20.10`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
It hasn't been released yet
