### ISSUE TITLE
static link rdkafka error

### ISSUE THREAD

**Issue by gaoj414** [edenhill/librdkafka#386]
Hi,

   I have a project to connect kafka server with rdkafka. I have 2 version of this project static link version and dynamic link version. The dynamic link version works good but the static link version can't send or receive any message from kafka server. Please tell me how to fix it. I really need static link for my project.

**Comment by edenhill** [comment]
There shouldn't be any operational differences between static and dynamic linking.

Could you think of anything else that is different? Is the static version forking for some reason? (make sure to fork before initializing librdkafka!).

Use gdb and set breakpoints to figure out what is happening.
