### ISSUE TITLE
Could not install confluent-kafka 1.9.0 with librdkafka 1.9.0

### ISSUE THREAD

**Issue by vcalmic** [edenhill/librdkafka#3879]
Description
===========
I am trying to install the new release of the library 1.9.0 together with confluent-kafka for Python and I am receiving the following errors:

[error.txt](https://github.com/edenhill/librdkafka/files/8927104/error.txt)

How to reproduce
================
Install librdkafka@1.9.0 and confluent-kafka@1.9.0

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.9.0`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [x] Operating system: `macOS 12.4`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ronaldpetty** [comment]
Hack that worked for me, unfortunately using prior version (on 22.04).

```
wget -qO - https://packages.confluent.io/deb/6.1/archive.key | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/6.1 stable main"
sudo apt-get install librdkafka-dev
pip3 install confluent_kafka==1.8.2
```

Not for production, but got me going for now.

**Comment by edenhill** [comment]
@vcalmic You need to install the latest version of librdkafka, v1.9.0. Either thru homebrew or source.

@ronaldpetty The latest librdkafka version is available at:
`sudo add-apt-repository "deb https://packages.confluent.io/clients/deb $(lsb_release -cs) main"`

**Comment by vcalmic** [comment]
@edenhill Thank you for your response.
I am using the latest version of librdkafka, which is v1.9.0 (as stated in the issue description)

**Comment by edenhill** [comment]
@vcalmic 
This error indicates that it is finding an older version of librdkafka:
```
        #error "confluent-kafka-python requires librdkafka v1.9.0 or later. Install the latest version of librdkafka from Homebrew by running `brew install librdkafka` or `brew upgrade librdkafka`"

```

**Comment by edenhill** [comment]
We don’t yet provide Python 3.10 wheels which means it will use your
locally installed librdkafka instead, and that needs to be v1.9.0 too.


fre 17 juni 2022 kl. 14:45 skrev Vitalie Calmîc ***@***.***>:
