### ISSUE TITLE
The nuget package of version 1.9.0 does not work in visual studio

### ISSUE THREAD

**Issue by mariomastrodicasa** [edenhill/librdkafka#3881]
Description
===========
The **librdkafka.redist.targets** file, within the nuget package, contains a wrong path: it point to lib\win\x64\win-x64-Release\ **v140** while the package contains lib\win\x64\win-x64-Release\ **v142**

How to reproduce
================
- Upgrade to latest version (1.9.0)
- Recompile the project

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.9.0`
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration: 
 - [ ] Operating system: 
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks for reporting this, fix is on the way.

**Comment by edenhill** [comment]
Could you try out the librdkafka.redist 1.9.0-POST1 package and see if it works?

**Comment by mariomastrodicasa** [comment]
Yes, it works. When it is scheduled a new official release?

**Comment by edenhill** [comment]
Thank you.  A new fixed version is now uploaded as 1.9.0.1.
