### ISSUE TITLE
Registered Rebalance callback gets called only after producing first message from the producer

### ISSUE THREAD

**Issue by pratikthakkar24** [edenhill/librdkafka#3885]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
<I have a single topic, 3 partitions and 2 consumers.
I am using "rebalance_cb" to register my rebalance callback in both the consumers. 
My producer and consumers do get started and then wait for some time before producing some messages on the topic.
Even if my consumer has started and has successfully called "subscribe()" with the topic set and "consume()", my registered rebalance callback doesn't get called / triggered after the call of subscribe.
The rebalance callback gets called / triggered only after producing the first message from the producer on that topic.

Is this the default behavior of kafka ? or there is a need to tweak some config to get the rebalance callback called on consume() call.>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [1.9.0.1] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [2.8] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [Windows Server 2012 R2] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The only reason I can think of is if the topic doesn't exist at consumer startup, in which case it will not join the group, and then the topic is created by the producer (topic auto create) - which in turn triggers the consumer to join the group now when the topic is available.

**Comment by pratikthakkar24** [comment]
Got my answer and solution...thanks a lot @edenhill
