### ISSUE TITLE
rd_kafka_consume_start0() locking order race?

### ISSUE THREAD

**Issue by rthalley** [edenhill/librdkafka#389]
In rd_kafka_consume_start0, the code does

	rd_kafka_toppar_unlock(rktp);

	if (rkq)
		rd_kafka_q_fwd_set(&rktp->rktp_fetchq, rkq);

It seems to me like the toppar lock should be held while rd_kafka_q_fwd_set() is called, as otherwise there's seems race between letting go of the toppar and forwarding anything it might receive.

In the stop case, the toppar lock is held when forwarding is stopped.

**Comment by edenhill** [comment]
I dont think it really matters since the queue has a lock as well which is locked on each enq() or pop() access, as well as fwd_set().

Are you seeing problems that suggest otherwise?

**Comment by rthalley** [comment]
I'm not seeing any problems; I discovered this while reading code.  The issue is not whether the queue has a lock or not, but "between the time when we release the toppar lock, without setting up forwarding, and the time we set up forwarding, can a message arrive and be queued instead of forwarded (and thus lost)?"

**Comment by edenhill** [comment]
Enqueuing messages on rktp_fetchq actually does not touch the toppar_lock, so there is no race condition between the unlock and the q_fwd_set(). And even if they were q_fwd_set() makes sure to move any messages in the original queue to the forward queue. So we're double safe! (famous last words)

**Comment by rthalley** [comment]
awesome, thanks!
