### ISSUE TITLE
how can i deal with lost message.

### ISSUE THREAD

**Issue by Eric-918** [edenhill/librdkafka#392]
If message time out ,rdkafka would remove it from the queue without a delivery report , how can i know which message is dumped, and which is sent correctly ? I do not see something like message ID .

**Comment by edenhill** [comment]
The delivery report is called for each message, either on succesful delivery or on permanent failure, including timeouts.
You can use the msg_opaque (as provided to produce()) to pass your own data structure/identifier with each message.

**Comment by Eric-918** [comment]
THX ,Edenhill
