### ISSUE TITLE
Why rd_kafka_consume_queue can't get message?

### ISSUE THREAD

**Issue by w3hacker** [edenhill/librdkafka#393]
When I run rd_kafka_consume_queue in a forked process, rd_kafka_consume_queue can't receive message

**Comment by edenhill** [comment]
librdkafka creates internal threads (on rd_kafka_new() and later).
Threads will not survive a fork().
This means you need to fork() between initializing librdkafka.

**Comment by w3hacker** [comment]
@edenhill Thanks.
