### ISSUE TITLE
Docker Build Issue

### ISSUE THREAD

**Issue by ykishorereddy** [edenhill/librdkafka#3939]
Description
===========
 /tmp/pip-install-3zn71rtb/confluent-kafka_1577fda28d2f4a1fbbfe78cceec3959f/src/confluent_kafka/src/confluent_kafka.c: In function ‘oauth_cb’:
    /tmp/pip-install-3zn71rtb/confluent-kafka_1577fda28d2f4a1fbbfe78cceec3959f/src/confluent_kafka/src/confluent_kafka.c:1633:17: error: ‘for’ loop initial declarations are only allowed in C99 mode
                     for(int i = 0; i < rd_extensions_size; i++) {
                     ^
    /tmp/pip-install-3zn71rtb/confluent-kafka_1577fda28d2f4a1fbbfe78cceec3959f/src/confluent_kafka/src/confluent_kafka.c:1633:17: note: use option -std=c99 or -std=gnu99 to compile your code
    error: command 'gcc' failed with exit status 1

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
That source file is from confluent-kafka-python, not librdkafka.
