### ISSUE TITLE
About librdkafka-0.7 some questions

### ISSUE THREAD

**Issue by wangfakang** [edenhill/librdkafka#395]
hi @bmilekic 
       may be it's a old questions at librdkafka-0.7 and source code example:
```c    
static void rd_kafka_wait_op (rd_kafka_t *rk) {
	
	while (!rk->rk_terminate && rk->rk_state == RD_KAFKA_STATE_UP) {
		rd_kafka_op_t *rko =
			rd_kafka_q_pop(&rk->rk_op, RD_POLL_INFINITE);
		
		rd_kafka_produce_send(rk, rko);

                rd_kafka_op_destroy(rk, rko);
	}
}		
```    
at the code, if rd_kafka_produce_send is call fail(may be net ) and next call function  rd_kafka_op_destroy free topic lose log ? may be it's not a questions thx.

**Comment by edenhill** [comment]
Yes, if produce_send() fails the rko message will be lost. This is only a problem with the old 0.7 implementation.
