### ISSUE TITLE
Failed to add offsets to transaction on broker TxnCoordinator

### ISSUE THREAD

**Issue by brucewang2022** [edenhill/librdkafka#3958]
librdkafka version: librdkafka-1.7.0
errormessage:
ucer-3-retry: 0#producer-1: [rdkafka_buf.c:395]: [thrd:main]: TxnCoordinator/2: rkbuf: 0x7fd5bc0fea10, has msg: 0, retry: 1790, max retry: 1,lasterrcode=0[45776_]
^KafkaProducer.cpp:209^kafka_producer_logger|producer-3-ADDOFFSETS: 0#producer-1: [rdkafka_txnmgr.c:1922]: [thrd:main]: TxnCoordinator/2: Failed to add offsets to transaction on broker TxnCoordinator/2: Broker: Not coordinator,lasterrcode=0[45776_]
KafkaProducer.cpp:1552^sendOffsetsToTransaction|sendOffsetToTransaction must be retry ,transID:52001_100086_31,err is Failed to add offsets to transaction on broker TxnCoordinator/2: Broker: Not coordinator (after 0ms),errcode=16[45776_WorkTask#8-10 

how to deal this ,except reboot the client.

**Comment by fad16papa** [comment]
Hi @brucewang2022 Have you already solved this? I also encountered this  Thank you

**Comment by edenhill** [comment]
Please upgrade to the latest librdkafka version, there's been important transaction fixes since v1.7.0.
