### ISSUE TITLE
No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN

### ISSUE THREAD

**Issue by paritosh-96** [edenhill/librdkafka#3963]
I have a project connecting to Confluent Kafka and SARAMA kafka both. The connection fails for Confluent kafka only with the below error:
Failed to create Producer: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN

I see this was faced by people earlier as well, and I have gone through those issues but could not resolve this.

I am trying to setup things in an Ubuntu system. Here is what my docker file looks like:

WORKDIR /opt
RUN apt-get update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y install krb5-user libpam-krb5
ENV DEBIAN_FRONTEND=interactive
RUN apt-get -y install libsasl2-dev
RUN apt-get -y install libsasl2-modules-gssapi-mit
RUN \
    git clone https://github.com/edenhill/librdkafka.git && \
    cd librdkafka  && \
    ./configure --prefix /usr  && \
    make clean && \
    make && \
    make install && \
    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig/

After this I build my project with the -tags dynamic tag. I am using go 1.18.3. This seems to be working for other projects on 1.16 go version. 

Please help on this

_Originally posted by @paritosh-96 in https://github.com/edenhill/librdkafka/discussions/3962_

**Comment by paritosh-96** [comment]
@edenhill

**Comment by OneCricketeer** [comment]
Does this help?

> Make sure the openssl and libssl-dev packages are installed.

> Reconfigure and rebuild librdkafka (`./configure --reconfigure && make`). Verify that `WITH_SSL` is set to 1 in `config.h`

https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

**Comment by edenhill** [comment]
If you are on Ubuntu you can add the Confluent clients APT repository and use those packages directly, which feature GSSAPI support.

See instructions here and make sure you add the clients repository:
https://docs.confluent.io/platform/current/installation/installing_cp/deb-ubuntu.html#configure-cp

**Comment by SAMUEL-KETECHIE** [comment]
facing similar issue here

were you able to resolve it? @paritosh-96

**Comment by taabrcr** [comment]
Hi!
What have work for me was to follow this: https://github.com/confluentinc/confluent-kafka-python/blob/master/INSTALL.md?plain=1.
