### ISSUE TITLE
C++ Topic::name() constness

### ISSUE THREAD

**Issue by incessantier** [edenhill/librdkafka#398]
In the C++ API, a "const Topic*" pointer is passed around (e.g. partitioner callbacks), but Topic::name() is not a const method.  In order to get the topic name in a callback, you need to cast away the constness of the pointer.  Does Topic::name() really make internal mods, or could it be const?

**Comment by edenhill** [comment]
You are right, it should be const. same for partition_available().
Care to file a PR?

**Comment by incessantier** [comment]
Not at all, I'll get it going in the next couple days.
