### ISSUE TITLE
How to config "buffer.memory" and "max.request.size" of producer?

### ISSUE THREAD

**Issue by nemesis-blue** [edenhill/librdkafka#3980]
I got an error of  "no such configuration property" when I set conf of producer with properties of "buffer.memory" and "max.request.size"  .My code:
-----------------------------------------------------------------------------------------------
     string errstr = "";
    /*
     * Create configuration objects
     */
    RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
    RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

    /*Set configuration properties,broker list*/
    if (conf->set("metadata.broker.list", m_strBroker, errstr) != RdKafka::Conf::CONF_OK){
        std::cerr << "RdKafka conf set brokerlist failed :" << errstr.c_str() << endl;
    }
    /* Set delivery report callback */
    conf->set("dr_cb", &m_producerDeliveryReportCallBack, errstr);
    conf->set("event_cb", &m_producerEventCallBack, errstr);

    if (conf->set("batch.size", "524288", errstr) != RdKafka::Conf::CONF_OK) {
        std::cerr << "RdKafka conf set batch.size failed :" << errstr.c_str() << endl;
    }

    if (conf->set("compression.type", "lz4", errstr) != RdKafka::Conf::CONF_OK) {
        std::cerr << "RdKafka conf set compression.type failed :" << errstr.c_str() << endl;
    }

    if (conf->set("acks", "1", errstr) != RdKafka::Conf::CONF_OK) {
        std::cerr << "RdKafka conf set acks failed :" << errstr.c_str() << endl;
    }

    if (conf->set("max.request.size", "5242880", errstr) != RdKafka::Conf::CONF_OK) {
        std::cerr << "RdKafka conf set max.request.size failed :" << errstr.c_str() << endl;
    }

    if (conf->set("buffer.memory", "268435456", errstr) != RdKafka::Conf::CONF_OK) {
        std::cerr << "RdKafka conf set buffer.memory failed :" << errstr.c_str() << endl;
    }

    /*
     * Create producer using accumulated global configuration.
    */
    m_pProducer = RdKafka::Producer::create(conf, errstr);
    if (!m_pProducer) {
        std::cerr << "Failed to create producer: " << errstr << std::endl;
        return false;
    }
    std::cout << "% Created producer " << m_pProducer->name() << std::endl;
-----------------------------------------------------------------------------------------------
After I read the source code, I can't find "buffer.memory" or"max.request.size" properties in the file "rdkafka_conf.c".
How can I set the properties by api not by the config file "producer.properties"?

**Comment by edenhill** [comment]
Those are Java producer config properties.

librdkafka has its own set of properties as seen here:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

Also read this:
https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#performance


The default settings are well tuned and battle tested, we thus highly recommend sticking with the default settings unless there's a clear/proven benefit of alternate settings.
The defaults are

**Comment by Sam-sad-Sajid** [comment]
Hey @edenhill, I am a bit confused about the `max.request.size` and `message.max.bytes`. I saw your comment [here](https://github.com/confluentinc/librdkafka/issues/3246#issuecomment-774001962) that
> Part of the problem is that librdkafka predates the Java producer, but what we can do is add an alias max.request.size -> message.max.bytes.

Is it safe to assume that `message.max.bytes` in librdkafka is equivalent to the `max.request.size` from the Java world?
