### ISSUE TITLE
SSL setup does not work when using keystore.p12 in windows

### ISSUE THREAD

**Issue by Protheon** [edenhill/librdkafka#3992]
Description
===========

Hi. on attempting to load a keystore the same way mentioned here https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka
ssl.keystore.location=C:\pathtokeystore\keystore.p12
ssl.keystore.password=XXXXX

i run into the error Error reading ssl.keystore.location PKCS#12 file: C:\pathtokeystore\keystore.p12: error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data

this suggests that the file is missing or somehow is not found. i can confirm that the file is there and works as i have loaded it properly using another loader and also can open it using openssl for windows and export the certificate as pem through openssl.

if i extract the keys and certificates and load directly, this works:
"ssl.ca.location" = ".../chain.pem"
"ssl.certificate.location" = ".../client_cert"
"ssl.key.location" = ".../client_key"

This however poses a security risk by exposing the pkey in a file and cannot be used on a production environment.

Do you know what could be going wrong when loading PKCS#12 keystores or if this library is not compatible for windows?

I'm using
OS: Windows 10 ver 20H2
Framework: .net6.0

How to reproduce
================
Run a .net core 6.0 application in windows using confluentinc/confluent-kafka-dotnet.

Checklist
=========

 - [x] librdkafka version (release number or git tag): `librdkafka.redist 1.9.2`
 - [ ] Apache Kafka version: `N\A`
 - [ ] librdkafka client configuration: `N\A`
 - [x] Operating system: ` Windows 10 ver 20H2`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka `N\A`
 - [ ] Provide broker log excerpts  `N\A`
 - [x] Critical issue

**Comment by emasab** [comment]
I'm testing this [fix](https://github.com/edenhill/librdkafka/pull/3999). In the meantime this is the workaround that I've tested. Exporting the p12 keystore to a PEM key and certificate and using those.

```
export KEYSTORE_PASSWORD=fill_in \
KEY_PASSWORD=fill_in \
KEYSTORE=client.keystore.p12 \
CERTIFICATE=client.certificate.pem \
KEY=client.key && \
openssl pkcs12 -in "$KEYSTORE" -out "$CERTIFICATE" -nodes -passin "pass:$KEYSTORE_PASSWORD" && \
openssl pkcs12 -in "$KEYSTORE" -out "$KEY" -nocerts -passin "pass:$KEYSTORE_PASSWORD" -passout "pass:$KEY_PASSWORD"
```

With this configuration:
```
config.SslCaLocation = "client.truststore.pem";
config.SslCertificateLocation = "client.certificate.pem";
config.SslKeyLocation = "client.key";
config.SslKeyPassword = "fill_in";
```

**Comment by tuyenlq** [comment]
I also have the same problem with fule .p12

**Comment by emasab** [comment]
@tuyenlq the workaround and fix are the same for Python too.

**Comment by sebeyruv** [comment]
short question about config.SslCaLocation = "client.truststore.pem"; => if you have the truststore only in .jks format, how would you convert?

**Comment by Protheon** [comment]
you can use java's sdk to convert jks formats to pem. you can then use openssl that comes with git to convert p12 to pem or vice versa (i think)

**Comment by ashishakolkar** [comment]
Hi I am having the same issue on windows could you please  help me to understand fix and  workaround mentioned above.

would like to know what configuration we need i have pfx file on windows with password.

**Comment by Protheon** [comment]
hi @ashishakolkar  what does your setup look like? The workaround is explained and is as follows:

extract the keys and certificates from your keystore.p12. when creating the config, load the files directly using the config values:
"ssl.ca.location" = "<path to your CA>/ca.pem"
"ssl.certificate.location" = "<path to your certificate public key>/client_cert.pem"
"ssl.key.location" = "<path to your certificate private key>/client_key.key"
if you encrypt your private key file, you can also configure the key path:
"ssl.KeyPassword" = "your encrypted private key file"

These property names may vary according to the client you are using. for .net Confluent.Kafka Check ProducerConfig and ConsumerConfig

If it doesnt work , please clarify the reason

**Comment by ashishakolkar** [comment]
@Protheon Ok thank you for reply. I have .pfx keystore exported with password  from Certificate manager of windows. It includes certificate,key.pem and ca certificate Which is working prefectly for Schema registery but not for producer config.

I also tried to use SSL certificate as you mentioned above but then Produce.ProduceAsync does not return and end with thread is aborted error.

**Comment by Protheon** [comment]
hi @ashishakolkar There could be many reasons for a thread abort. Could be that it's not related to this specific issue. Are you using Confluent.Kafka for .netcore ? If so, you can also raise an incident here https://github.com/confluentinc/confluent-kafka-dotnet/issues
