### ISSUE TITLE
ZooKeeper integration

### ISSUE THREAD

**Issue by preillyme** [edenhill/librdkafka#4]
When is ZooKeeper integration planned?

— Patrick

**Comment by edenhill** [comment]
Kafka is moving away from ZooKeeper reliance on clients, so closing this as **wontfix**

**Comment by vchampion** [comment]
> Kafka is moving away from ZooKeeper reliance on clients
Please explain - where that information about feature of kafka was published? I red manual and don't find such information.

**Comment by edenhill** [comment]
The new Producer and KafkaConsumer java clients dont make use of zookeeper, they only rely on broker functionality.

**Comment by vchampion** [comment]
mb I [found](http://www.confluent.io/blog/apache-kafka-0.9-is-released)

> This new consumer is implemented using a powerful new server-side facility that makes group management a first-class part of Kafka's protocols. This has several advantages. First it allows for a much more scalable group facility, which allows the consumer clients to be much simpler and thinner and allows for larger groups with far faster rebalancing. This facility is available to all clients; work is already nearing completion to use it in the C client, librdkafka. This same facility turns out to be broadly useful for managing distributed producing and consuming of data in Kafka; it is the basis for Kafka Connect as well as several upcoming projects. Finally this completes a series of projects done in the last few years to fully decouple Kafka clients from Zookeeper, thus entirely removing the consumer client’s dependency on ZooKeeper. Zookeeper is still used by Kafka, but it is an implementation detail of the broker--clients that use this new facility have no need to connect to Zookeeper at all. This has a number of operational benefits since clients are now always working through the security and quota mechanisms the broker provides. This significantly simplifies the consumer and opens the door for first-class non-Java implementations of the consumer API to emerge over time.

[and](http://www.confluent.io/blog/tutorial-getting-started-with-the-new-apache-kafka-0.9-consumer-client)

> This new consumer also adds a set ohttp://www.confluent.io/blog/apache-kafka-0.9-is-releasedf protocols for managing fault-tolerant groups of consumer processes. Previously this functionality was implemented with a thick Java client (that interacted heavily with Zookeeper). The complexity of this logic made it hard to build fully featured consumers in other languages. With the introduction of this new protocol, this has now become far far easier. In fact we’ve moved the C client over to this protocol already.

**Comment by vchampion** [comment]
> The new Producer and KafkaConsumer java clients dont make use of zookeeper, they only rely on broker functionality.

Good, it's cool, so zookeeper mb needed only for Kafka fault tolerance and configuration? And for producers and consumers it's not need as well?

**Comment by edenhill** [comment]
Correct, Kafka brokers still use ZK, but clients dont.

**Comment by edenhill** [comment]
As of Kafka v0.9
