### ISSUE TITLE
kafka broker down or network disconnection,program will  throw exception and stop

### ISSUE THREAD

**Issue by z772458549** [edenhill/librdkafka#401]
How can I catch the exception and Make the program continues to run and try reconnect in seconds.
  Thank you very much!

**Comment by edenhill** [comment]
librdkafka does not throw any exceptions, and it will automatically reconnect whenever a broker connection is disconnected.

**Comment by z772458549** [comment]
oh,sorry!,I kill kakfa server then I test my program,no cores,no exceptions.
I beg you and  ask a question.
when I start kafka produce,show some logs.
"RDKAFKA-3-FAIL: rdkafka#producer-0:10.2.28.60:9092/bootstrap:Failed to connect to broker at ...1/1 brokers are down" 

if log like this,kafka produce will reconnect with rd_kafka_thread_main function  or program  is down?
Can you tell us your powerfull librdkafka implementation ideas?

**Comment by edenhill** [comment]
That means it can't connect to your broker.
Did you give it the right address and port?
Check connectivity with the broker, e.g.:  "telnet <broker-address> <broker-port>" should give you a connection.

**Comment by z772458549** [comment]
Kafka produce server has dual ethernet(Internal network and external network),Kafka produce data and poll data to Internal network through haproxy server to  external network. When haproxy is down,log  will show.How can I deal with this situation.

**Comment by edenhill** [comment]
librdkafka needs to be able to connect with TCP to the brokers and it usually will not work with a proxy inbetween.

**Comment by z772458549** [comment]
Oh,thank you very much
