### ISSUE TITLE
Offset autocommit does not work if consumer starts from non-STORED offset

### ISSUE THREAD

**Issue by mutability** [edenhill/librdkafka#402]
If auto.commit.enabled = true, but the consumer starts consuming at an offset other than RD_KAFKA_OFFSET_STORED, then rd_kafka_offset_store_init is never called, the autocommit timer is never started, and subsequent consumption of messages is not recorded.

**Comment by edenhill** [comment]
That's according to design. OFFSET_STORED as the initial offset is how you enable offset storage.

For the cases where there is no previous offset stored you can set the starting offset with ` auto.offset.reset=..`.
If you want to start at a specific offset and still use the offset store for committing offsets you need to use the seek() API which is not yet available in master (will be in about 3 weeks, along with the new consumer).

**Comment by mutability** [comment]
Ah, it's not documented to do that.

Assume you have a longlived consumer that usually starts from STORED and uses autocommit. When you restart it, it picks up where it left off. There are a couple of use cases where starting at non-STORED but wanting autocommit make sense:

1) You find a bug and need to reprocess the last N messages, so you want to restart from a specific offset, catch up to the topic end, then continue running with autocommit happening.

2) The consumer goes down for a while and the messages are time-sensitive, so you would rather skip to the current end of topic and start processing there with autocommit happening, rather than spending time trying to catch up from the stored offset.

How can I do that with the current code?

**Comment by mutability** [comment]
(it is a bit unfortunate that currently auto.commit.enabled is silently ignored in these cases - I only discovered this behaviour on the _next_ restart when the consumer suddenly decided to go back 12 hours because autocommit hadn't been recording anything)

**Comment by edenhill** [comment]
I'm sorry to hear that, the docs should be clarified indeed.

It sounds like the seek API is what you need

**Comment by mutability** [comment]
With the seek API, what's the correct sequence of calls to resume from non-STORED?

rd_kafka_consume_start(..., RD_KAFKA_OFFSET_STORED) then rd_kafka_seek() does not look right, at a glance, since you might consume some messages at STORED before the seek kicks in.

**Comment by edenhill** [comment]
librdkafka uses internal op-versioning to flush any messages that were received in between two different operations.
In this case  consume_start() starts consuming with op-version 1, any messages that are fetched will be tagged with that version.
When you do seek() it will bump the op-version to 2, any messages with version 1 in the queues will be purged and you will only see messages starting with the seek.

Obviously this is only true as long as you dont perform any consume() calls between the start and the seek.

**Comment by mutability** [comment]
Whether consume is called or not is somewhat out of my control, since there's a tcl layer between the app code and rdkafka which might run the event loop (which calls rd_kafka_consume_callback()) at somewhat unpredictable times.

So, feature request I guess, an atomic start+seek operation that works with autocommit please.

**Comment by edenhill** [comment]
Okay, I hear you, I'll see what I can do.

**Comment by mutability** [comment]
Thanks :)

**Comment by edenhill** [comment]
This is now available through the new rd_kafka_assign() API.
Create a rd_kafka_topic_partition_list_t with the list of topics+partitions you want to consume and optionally also the starting offset for each partition.

**Comment by resuna** [comment]
What version was rd_kafka_assign() added in, can you say?
