### ISSUE TITLE
Zlib tar.gz packages moved

### ISSUE THREAD

**Issue by Michal-lolo** [edenhill/librdkafka#4024]
Description
===========
Zlib tar.gz packages were moved to https://zlib.net/fossils/ (https://github.com/madler/zlib/issues/649), therefore mklove/modules/configure.zlib#install_source url should be updated.

How to reproduce
================
Try to fetch any zlib tar.gz packge from https://zlib.net/ location

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `1.9.2`
 - [x] Apache Kafka version: `N/A`
 - [x] librdkafka client configuration: `N/A`
 - [x] Operating system: `N/A`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: N/A
 - [x] Provide broker log excerpts: N/A
 - [x] Critical issue: No

**Comment by pranavrth** [comment]
Upgraded zlib version - https://github.com/edenhill/librdkafka/blob/master/mklove/modules/configure.zlib

**Comment by Michal-lolo** [comment]
Hi @pranavrth,
Issue reported by me was about url where all zlib packages are stored, not zlib version 🙂

**Comment by edenhill** [comment]
Good point, we should probably use the fossils/ URL to avoid breaking future builds.
@pranavrth Can you make a new PR?

**Comment by pranavrth** [comment]
Sure. Will do that. 

Just FYI - Latest version is still downloadable from old location - https://zlib.net/zlib-1.2.13.tar.gz
