### ISSUE TITLE
Allow random jitter on broker reconnects

### ISSUE THREAD

**Issue by mutability** [edenhill/librdkafka#403]
Currently when a broker goes down rdkafka immediately tries to reconnect.

This can cause a huge spike in load and outgoing connection rate if there are a lot of consumers on the same machine (we have ~1500), as they all wake up at the same time and try to reconnect.

Obviously you can't avoid the timing of the disconnect being seen, but it would be nice to be able to configure a random delay before reconnecting so that all the consumers don't try to do it at the same time.

**Comment by edenhill** [comment]
Good idea, will add.it for the next release.
