### ISSUE TITLE
The ./configure --enable-static does not create statically linked executable

### ISSUE THREAD

**Issue by habdank** [edenhill/librdkafka#4032]
Description
===========
I would like to get kcat statically linked, to run it on all our servers RHEL 7 regardless on installed libs.

./configure --enable-static
as well as
./configure --disable-shared

does not produce statically linked binary.

In the later build logs I see:

gcc -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -L/.../kafkacat/librdkafka/lib/ -L/.../kafkacat/librdkafka/lib/ kcat.o format.o tools.o input.o -o kcat /.../librdkafka/build-deployables/lib/librdkafka.a -L/.../librdkafka/build-deployables/lib -lm -ldl -lpthread -lrt -lz -lssl -lzstd -llz4 -lcrypto

What means, that only librdkafka is statically linked and all others not.

Can you provide configuration options to make it possible?

How to reproduce
================

./configure --enable-static # or --disable-shared
make
make install
ldd kcat

Please provide the following information:

 - [x] librdkafka version 1.8.0
 - [x] Apache Kafka version: 3.2.1
 - [x] librdkafka client configuration: `N/A`
 - [x] Operating system: `RHEL 7`

**Comment by edenhill** [comment]
This is a kcat issue, not librdkafka.
