### ISSUE TITLE
linking librdkafka in python shared library and TLS issue

### ISSUE THREAD

**Issue by davidebenato** [edenhill/librdkafka#4047]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========

We are building librdkafka with `fpic` and we link is statically into a `lib.so` that uses `pybind11` for python bindings.
We build the library using `conan` and we also use it in conjunction with `cppkafka:0.4.0`
https://conan.io/center/cppkafka

Once we load our library from python we see the following error:

```
>>> import libcustom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/dabe/libcustom.so: cannot allocate memory in static TLS block
```

This was working fine prior to introducing librdkafka.
Interesingly this hack we found masks the problem:

```
LD_PRELOAD=/home/dabe/libcustom.so python3
>>> import libcustom
```

Is librdkafka using a lot of TLS memory? 
Any pointer could be helpful. 
We use the same library in our statically linked binary executables and we don't see this issue.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version 1.9.2
 - [x] Operating system: `Debian bullseye`

**Comment by edenhill** [comment]
librdkafka does indeed use quite some thread-local-storage: https://github.com/edenhill/librdkafka/search?q=RD_TLS&type=code

Haven't previously seen that this is a problem though.

**Comment by davidebenato** [comment]
interesting. We had a similar problem a while ago when we were linking `libstdc++.so` statically into the shared library version. 
I checked and I don't think `libstdc++.so` is embedded into librdkafka, so probably another problem.

**Comment by davidebenato** [comment]
we found a workaround to not link the library in our shared lib. 
Closing
