### ISSUE TITLE
undefine

### ISSUE THREAD

**Issue by laoola** [edenhill/librdkafka#4066]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
<your issue description goes here>

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

Configuration summary:
  prefix                   /usr/local
  MKL_DISTRO               kylin
  SOLIB_EXT                .so
  ARCH                     aarch64
  CPU                      generic
  GEN_PKG_CONFIG           y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  RANLIB                   ranlib
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
  PKG_CONFIG               pkg-config
  INSTALL                  /usr/bin/install
  HAS_GNU_AR               y
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      1.9.2
  MKL_APP_VERSION          1.9.2
  LIBS                     -lm -lssl   -lcrypto   -lz   -ldl -lpthread -lrt
  MKL_PKGCONFIG_LIBS_PRIVATE -lm -ldl -lpthread -lrt
  MKL_PKGCONFIG_REQUIRES_PRIVATE zlib libcrypto libssl
  CFLAGS                        
  MKL_PKGCONFIG_REQUIRES   zlib libcrypto libssl
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  MKL_DYNAMIC_LIBS         -lm -lssl -lcrypto -lz -ldl -lpthread -lrt
  exec_prefix              /usr/local
  bindir                   /usr/local/bin
  sbindir                  /usr/local/sbin
  libexecdir               /usr/local/libexec
  datadir                  /usr/local/share
  sysconfdir               /usr/local/etc
  sharedstatedir           /usr/local/com
  localstatedir            /usr/local/var
  runstatedir              /usr/local/var/run
  libdir                   /usr/local/lib
  includedir               /usr/local/include
  infodir                  /usr/local/info
  mandir                   /usr/local/man
  BUILT_WITH               GCC GXX PKGCONFIG INSTALL GNULD LDS LIBDL PLUGINS ZLIB SSL HDRHISTOGRAM SYSLOG SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER
Generated config.cache

Now type 'make' to build

1.9.2.verison build, this is Latest version，not solve this progrom;

but
undefined symbol: _ZN7RdKafka5Topic6createEPNS_6HandleERKSsPKNS_4ConfERSs       (./libDataReport.so)
undefined symbol: _ZN7RdKafka7err2strENS_9ErrorCodeE    (./libDataReport.so)
undefined symbol: _ZN7RdKafka8Producer6createEPKNS_4ConfERSs    (./libDataReport.so)

pc:
Linux user-GW-001M1A-FTF 4.4.131-20200710.kylin.desktop-generic #kylin SMP Fri Jul 10 13:46:24 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
每个核的线程数：1
每个座的核数：  4
Socket(s):             1
Model name:            Phytium,FT-1500A
BogoMIPS:              3600.00
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<REPLACE with e.g., v0.10.5 or a git sha. NOT "latest" or "current">`
 - [ ] Apache Kafka version: `<REPLACE with e.g., 0.10.2.3>`
 - [ ] librdkafka client configuration: `<REPLACE with e.g., message.timeout.ms=123, auto.reset.offset=earliest, ..>`
 - [ ] Operating system: `<REPLACE with e.g., Centos 5 (x64)>`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You're probably not linking to `-lrdkafkac++`
