### ISSUE TITLE
How we give a  argument about timestamp  to rd_kafka_offsets_for_times function? 

### ISSUE THREAD

**Issue by caojun97** [edenhill/librdkafka#4074]
Description
===========
<your issue description goes here>
I know a function that rd_kafka_offsets_for_times, it can return a offset by timestamp.

but you see, there is  not a argument that is timestamp :
*  `rd_kafka_offsets_for_times(rd_kafka_t *rk, rd_kafka_topic_partition_list_t *offsets, int timeout_ms);`
*  ` rd_kafka_topic_partition_list_t`
```c
typedef struct rd_kafka_topic_partition_list_s {
        int cnt;                           /**< Current number of elements */
        int size;                          /**< Current allocated size */
        rd_kafka_topic_partition_t *elems; /**< Element array[] */
} rd_kafka_topic_partition_list_t;
```
*  `rd_kafka_topic_partition_t `
```c
typedef struct rd_kafka_topic_partition_s {
        char *topic;             /**< Topic name */
        int32_t partition;       /**< Partition */
        int64_t offset;          /**< Offset */
        void *metadata;          /**< Metadata */
        size_t metadata_size;    /**< Metadata size */
        void *opaque;            /**< Opaque value for application use */
        rd_kafka_resp_err_t err; /**< Error code, depending on use. */
        void *_private;          /**< INTERNAL USE ONLY,
                                  *   INITIALIZE TO ZERO, DO NOT TOUCH */
} rd_kafka_topic_partition_t;
```

**Comment by edenhill** [comment]
The rd_kafka_offsets_for_times() documentation says to put the timestamp (milliseconds since epoch utc) in the .offset field of each requested partition.
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L3208
