### ISSUE TITLE
Dont use OpenSSL on OSX

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#408]
Apple has deprecated their bundled OpenSSL / libcrypto on OSX 10.7.
See here:
http://rentzsch.tumblr.com/post/33696323211/wherein-i-write-apples-technote-about-openssl-on

We should be using CommonCrypto on OSX, or some 3rd party SSL library.

**Comment by edoardocomar** [comment]
I used the brew version
`brew install openssl`
and then run configure with the settings:
```
CPPFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib ./configure
```

**Comment by joekarl** [comment]
Just ran into this, big thanks to @edoardocomar for the hint on compiling against a local openssl.

For me this was manifesting itself as:
`ERROR|rdkafka#consumer-1| ssl://kafka-1:9092/bootstrap: SSL handshake failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/ssl/s23_clnt.c:618: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol: `

Linking with the brew installed openssl helped solve the problem for the near term, but definitely was a pain to track this down and makes building tooling around librdkafka a pain.

**Comment by joekarl** [comment]
Curious how kafkacat is setup, is the version installed via homebrew statically compiled with openssl or something?

**Comment by edenhill** [comment]
Brew OpenSSL works fine, closing this issue.
