### ISSUE TITLE
Failed to create consumer: Unsupported value "SASL_SSL" for configuration property "security.protocol": OpenSSL not available at build timed

### ISSUE THREAD

**Issue by pforpramit** [edenhill/librdkafka#4087]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Do NOT create issues for questions, use the discussion forum: https://github.com/edenhill/librdkafka/discussions

Description
===========
Getting below error message upon running a go-alpine image of Kafka consumer GO application that uses GSSAPI as the sasl mechanism and security.protocol as SASL_SSL -

Failed to create consumer: Unsupported value "SASL_SSL" for configuration property "security.protocol": OpenSSL not available at build timed

I am using confluent-kafka-go library having version 1.9.2

How to reproduce
================
Here is my dockerfile content -

FROM golang:1.19-alpine as c-bindings

RUN apk update && apk upgrade && apk add pkgconf git bash build-base sudo

FROM c-bindings as app-builder

WORKDIR /go/app

COPY . .

RUN go mod download
RUN go mod verify

RUN git clone https://github.com/edenhill/librdkafka.git
RUN cd librdkafka && ./configure && make && sudo make install

RUN apk add libressl-dev

RUN go build -race -tags dynamic --ldflags "-extldflags -static -s -w" -o main ./main.go

FROM scratch AS app-runner

WORKDIR /go/app/

COPY --from=app-builder /go/app/main ./main

CMD ["/go/app/main"]

**Comment by edenhill** [comment]
As the error message hints, openssl was not available when building librdkafka.
Try changing your ./configure line to:
`./configure --install-deps`

**Comment by pforpramit** [comment]
Hello, tried that - however, the docker build fails this time. Attached error log.
[docker_build_failure.txt](https://github.com/edenhill/librdkafka/files/10133514/docker_build_failure.txt)

**Comment by edenhill** [comment]
drop the ldflags

**Comment by pforpramit** [comment]
Tried that as well. Dockerfile gets built successfully. However, it fails to run the container with this error message - 

standard_init_linux.go:228: exec user process caused: no such file or directory

**Comment by edenhill** [comment]
I would guess that your subsequent `FROM scratch` clears the image of the dependencies.

But this has turned into a docker support issue, so closing.
