### ISSUE TITLE
Windows...

### ISSUE THREAD

**Issue by incessantier** [edenhill/librdkafka#409]
I hate to even have to ask this question, but alas...does librdkafka compile on windows with msvc?

**Comment by edenhill** [comment]
It does! And I'm currently finalizing the win32 porting work, so it is not available in master yet (will be in about a month's time).
Please feel free to try out the `oct15` branch.

**Comment by incessantier** [comment]
oooh neat-o.  That may make some on our team very happy...

**Comment by incessantier** [comment]
Is there any chance I can talk you into merging [the const PR](https://github.com/edenhill/librdkafka/pull/404) into the oct15 branch?

**Comment by edenhill** [comment]
Yep, I'll merge master into oct15 soon.

**Comment by incessantier** [comment]
:+1:

**Comment by edenhill** [comment]
Windows development is pretty new to me so any feedback on the windows stuff is very much welcomed.

**Comment by incessantier** [comment]
Sorry to jump back on an old issue, but a related question - any thought on using cmake instead of the manual make/solution files?

**Comment by edenhill** [comment]
Not really, never liked cmake, too convoluted, too much in your face.
(ignorance is bliss)

**Comment by edenhill** [comment]
Why do you ask?

**Comment by incessantier** [comment]
Not a hugea deal, just selfish reasons.  We have a pretty large code-base comprised of both internally-developed and imported libraries in support of multiple platforms (different linux flavors, windows, solaris...)  Our build system is based on cmake so we don't need to maintain different make/build systems individually...we don't need to manage different project files for each platform/compiler, just the single cmake.  It would simply make it easier for us to integrate directly into our build process rather than install on every developer's machine.

**Comment by fsaintjacques** [comment]
@edenhill, here's an example [1] of a good C library project template based on cmake.

[1] https://github.com/redjack/c-template

**Comment by edenhill** [comment]
Thanks for the explanation. Everyone has different needs and I'm not sure it is worth the cost maintaining multiple build systems.
