### ISSUE TITLE
./configure fails upon pulling https://github.com/edenhill/librdkafka.git

### ISSUE THREAD

**Issue by pforpramit** [edenhill/librdkafka#4090]
Description
===========
I am trying to pull https://github.com/edenhill/librdkafka.git and trigger ./configure as I was trying the same in my dockerfile in parallel. 

How to reproduce
Git close: https://github.com/edenhill/librdkafka.git
Trigger ./configure

Getting below -

$ ./configure
checking for OS or distribution... ok (mingw64_nt-10.0-19042)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking executable libtool... failed (disable)
checking executable ranlib... ok
checking for pkgconfig (by command)... failed
checking for install (by command)... ok
checking for GNU ar... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... failed
checking for socket_nsl (by compile)... failed (fail)
parsing version '0x020000ff'... ok (2.0.0)
checking for librt (by compile)... failed
checking for libpthread (by compile)... ok
checking for c11threads (by compile)... failed (disable)
checking for libdl (by compile)... failed (disable)
checking for zlib (by compile)... failed (disable)
checking for libcrypto (by compile)... failed (disable)
checking for libsasl2 (by compile)... failed (disable)
checking for libsasl (by compile)... failed (disable)
checking for libzstd (by compile)... failed (disable)
checking for libcurl (by compile)... failed (disable)
checking for libm (by compile)... ok
checking for liblz4 (by compile)... failed (disable)
checking for syslog (by compile)... failed (disable)
checking for rapidjson (by compile)... failed (disable)
checking for crc32chw (by compile)... ok
checking for regex (by compile)... failed (disable)
checking for rand_r (by compile)... failed (disable)
checking for strndup (by compile)... failed (disable)
checking for strlcpy (by compile)... failed (disable)
checking for strerror_r (by compile)... failed (disable)
checking for strcasestr (by compile)... failed (disable)
checking for pthread_setname_gnu (by compile)... ok
checking for nm (by env NM)... ok (cached)
checking for python3 (by command)... failed (disable)
disabling linker-script since python3 is not available
checking for getrusage (by compile)... failed (disable)

###########################################################
###########################################################
###########################################################
socket_nsl ()
    module: socket
    action: fail
    reason:
compile check failed:
CC: CC
flags:
gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmp6wmRgB.c -o _mkltmp6wmRgB.c.o -lsocket -lnsl   :
_mkltmp6wmRgB.c:3:10: fatal error: sys/socket.h: No such file or directory
    3 | #include <sys/socket.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

**Comment by edenhill** [comment]
Look at this file for inspiration:
https://github.com/edenhill/librdkafka/blob/cd955b13eabb29f8c4dbbb01a3943b17da909f25/packaging/alpine/build-alpine.sh#L12
