### ISSUE TITLE
one or more broker down, messages lost.

### ISSUE THREAD

**Issue by Eric-918** [edenhill/librdkafka#410]
edenhill, if one or more broker down , message would not be sent, and stay timeout. 
how can i fix that ? monitoring broker node on zookeeper ?

**Comment by edenhill** [comment]
librdkafka will automatically reconnect to a down broker when it comes up again and will retransmit any waiting messages that havent yet timed out.

**Comment by Eric-918** [comment]
but ,if the broker is dead forever, how librd deal with this situation?

**Comment by edenhill** [comment]
The messages will timeout after `message.timeout.ms` milliseconds.

**Comment by edenhill** [comment]
If you've registered a delivery report callback you will get a callback with error code ERR__TIMED_OUT when the message times out.

**Comment by Eric-918** [comment]
yes ,I got timeout error in delivery report , it means that, if one broker dead ,all the broker down ?
it is a little unreasonable. support of zookeeper would solve this problem ?

**Comment by edenhill** [comment]
If you only configure one bootstrap broker ( `.._brokers_add()` or `metadata.broker.list`) and that broker is down, then naturally librdkafka will not be able to communicate with the cluster.

The solution is to provide more bootstrap brokers addresses or alternatively use a roundrobin CNAME for all your clusters, something like:
kafka-bootstrap  IN  CNAME   broker1, broker2, broker3, broker4,

Then librdkafka will roundrobin over all the addresses until it manages to connect to one of them.

**Comment by edenhill** [comment]
Getting the broker list from zookeeper is another alternative, yes, but there is no support for that in librdkafka so you will have to code that yourself.

**Comment by Eric-918** [comment]
I get broker list from zookeeper and set the brokers (3 brokers ) to librdkafka, but if one broker down ,librd didn't send delivery report , and I did not see it send delivery report  again , how long would librd take to connect to one of another broker ?

but , I find another way : set watcher on broker nodes on zookeeper ,and if broker nodes change , I update broker list to librd . This solver my problem.

**Comment by edenhill** [comment]
If the broker going down is the leader for the partition you are producing to and no other broker takes over (reassignment) then this is expected.
You should check why the other brokers arent reassigned for the partition.

You dont need to use zookeeper for this as long as librdkafka is still connected to other brokers that have reassigned the partition.

**Comment by sanbhidu** [comment]
Why does librdkafka send messages only to the leader broker?

**Comment by sanbhidu** [comment]
Why cant it round robin through all the brokers provided?

**Comment by edenhill** [comment]
Kafka will only allow producing and consuming from the leader broker.

**Comment by kanchanagarwal3** [comment]
Hi,I am trying to enable kerberos authentication using librdkafka library 0.9.1 in RHEM...
To do so:
I have set WITH_SASL =Y
installed libsasl2
set sasl parameters
but still unable to connect to kerberos enable broker..moreover there is no error log i receive for sasl..
do i need to make some changed in code level(in rdkafka_sasl.c)?pls suggest..what i sthe appropriate procedure

**Comment by kanchanagarwal3** [comment]
Hi,Actually i am not getting link to create new issue..Could you please suggest.

The links you mentioned above above are for apache kafka

I am using gnu library to set sasl emchanism in librdkafka library

**Comment by kanchanagarwal3** [comment]
ok i got it ...just on th etop right corner i saw new issu button
