### ISSUE TITLE
After update rd_kafka_consume_queue can't consume message

### ISSUE THREAD

**Issue by w3hacker** [edenhill/librdkafka#412]
rkmessage = rd_kafka_consume_queue(db->rkqu, 100);

rkmssage.err  Broker: No more messages
rkmessage->payload is null

**Comment by w3hacker** [comment]
Previous version works fine.

**Comment by edenhill** [comment]
What git sha's exactly are the previous working and the new non-working versions?

**Comment by edenhill** [comment]
Ping?
