### ISSUE TITLE
About multi-thread

### ISSUE THREAD

**Issue by oyld** [edenhill/librdkafka#413]
Hi.
Now I have to consume many partitions. Considering performance, should I create many thread and each thread call rd_kafka_consume_start? Or call rd_kafka_consume_start many times in one thread?

**Comment by edenhill** [comment]
When you want to consume multiple partitions from the same code I suggest you use the queue interface to direct each partition to the same queue, and then you consume off that queue.

See here:
https://github.com/edenhill/librdkafka/wiki/Consuming-from-multiple-topics-partitions-from-a-single-thread

**Comment by oyld** [comment]
Nice! Thanks.
