### ISSUE TITLE
I meet the core ,use librdkafka-0.8.6.zip and Linux version 2.6.32, gcc version 4.8.2 

### ISSUE THREAD

**Issue by yangkai04** [edenhill/librdkafka#414]
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004c61d9 in RdKafka::log_cb_trampoline (rk=<optimized out>, level=3, fac=<optimized out>, 
    buf=0x7ff58f39a620 "nmg01-crm-hina59.nmg01.baidu.com:8092/59: Receive failed: Receive error: Connection timed out") at HandleImpl.cpp:55
55        handle->event_cb_->event_cb(event);
(gdb) bt
#0  0x00000000004c61d9 in RdKafka::log_cb_trampoline (rk=<optimized out>, level=3, fac=<optimized out>, 
    buf=0x7ff58f39a620 "nmg01-crm-hina59.nmg01.baidu.com:8092/59: Receive failed: Receive error: Connection timed out") at HandleImpl.cpp:55
#1  0x00000000004c7f69 in rd_kafka_log0 (rk=0x22be000, extra=extra@entry=0x0, level=level@entry=3, fac=fac@entry=0x6950ac "FAIL", fmt=fmt@entry=0x6951d5 "%s")
    at rdkafka.c:141
#2  0x00000000004d58ce in rd_kafka_broker_fail (rkb=rkb@entry=0x2391800, err=RD_KAFKA_RESP_ERR__TRANSPORT, fmt=fmt@entry=0x69511d "Receive failed: %s")
    at rdkafka_broker.c:398
#3  0x00000000004d5fe7 in rd_kafka_recv (rkb=rkb@entry=0x2391800) at rdkafka_broker.c:1519
#4  0x00000000004d6888 in rd_kafka_broker_io_serve (rkb=rkb@entry=0x2391800) at rdkafka_broker.c:2452
#5  0x00000000004d7103 in rd_kafka_broker_consumer_serve (rkb=0x2391800) at rdkafka_broker.c:4105
#6  rd_kafka_broker_thread_main (arg=<optimized out>) at rdkafka_broker.c:4154
#7  0x00007ff5a07b71c3 in ?? ()
#8  0x0000000000000000 in ?? ()

**Comment by edenhill** [comment]
Dup #415
