### ISSUE TITLE
Unfair partition fetching

### ISSUE THREAD

**Issue by oyld** [edenhill/librdkafka#417]
I hava two partitions, each partition is very large. I use rd_kafka_consume_start_queue to comsume these partitions from 0 offset. But it only print one partition data, never print another.

**Comment by edenhill** [comment]
This is currently a known issue, the fetcher is not fair.
It is fixed on the oct15 branch, but that branch is not production ready.

In the meantime you could probably decrease queued.max.messages.kbytes, which is the per-partition fetch queue.

**Comment by edenhill** [comment]
Fixed on master
