### ISSUE TITLE
Connection State

### ISSUE THREAD

**Issue by twaters** [edenhill/librdkafka#418]
The event callback can tell me when the connection to the broker has failed.  But is there a way to know when the connection is re-established?  The only thing I can see at the moment is a debug log.

**Comment by edenhill** [comment]
Nope, not currently.

What this usually boils down to is some event mechanism for monitoring availability of the leader brokers for your desired partitions, eg #137 

I guess that's what you are after?

**Comment by incessantier** [comment]
Yep, something like that is exactly what I'm looking for.

**Comment by edenhill** [comment]
We probably want these events:
 * `BROKER_ADDED`
 * `[BROKER_REMOVED (brokers are currently not removed from librdkafka)]`
 * `BROKER_UP`
 * `BROKER_DOWN`
 * `ALL_BROKERS_DOWN`
 * `PARTITION_LEADER_UP`
 * `PARTITION_LEADER_DOWN`
 * `GROUP_COORDINATOR_UP`
 * `GROUP_COORDINATOR_DOWN`

**Comment by briot** [comment]
I like the proposal with the various kinds of events.

The scenario I currently have is the following: I have two brokers, and a topic with multiple partitions, but replication_factory=1 (the problem can be generalized with more brokers and higher replication factory).

When one of the two brokers goes down, I am getting a msg_timeout error (as expected) for my high-level consumer. But the error callback does not provide any information as to which broker is down. So my program must assume they are all down, and let listeners know they will not be getting new messages for the time being. Would be nice to have more detailed information, and the proposed PARTITION_LEADER_DOWN error would be useful !

Thanks
