### ISSUE TITLE
last core reason

### ISSUE THREAD

**Issue by yangkai04** [edenhill/librdkafka#422]
hi，edenhill
I am sorry that I was so busy to forget the question I ask. Today, that core repeat, I found the event_cb  I set a LOCAL variable in a _init function. So，when meet error, the event_cb called, the core appeard.

And I have a new question, if the consummer need restart?when and how?

Thank you~!

**Comment by edenhill** [comment]
I dont really understand your question. What do you mean by consumer restart?

**Comment by yangkai04** [comment]
sorry,my english is poor....      I mean when meet the net error or some other error, if the consumer need to restart? for example, the connection need to reconnect.

**Comment by edenhill** [comment]
librdkafka will handle reconnects automatically, the application does not need to bother.

**Comment by yangkai04** [comment]
thank you very much~!
