### ISSUE TITLE
rd_kafka_poll

### ISSUE THREAD

**Issue by hitljs** [edenhill/librdkafka#424]
hi，i'm using the async produce function，consider there are 4 messages in the queue，and 3 messages got ok in async_produce_dr_cb function， wheather calling the rd_kafka_poll again， may send the lost message or all 4 messages？

**Comment by edenhill** [comment]
The delivery report callback will only be called once per message.  You may call rd_kafka_poll() as many times as you wish, if there are waiting callbacks it will call them, otherwise sleep.
