### ISSUE TITLE
Plan for supporting 0.9 consumer

### ISSUE THREAD

**Issue by banks** [edenhill/librdkafka#425]
I realise this is a little early but Kafka 0.9 is due to be released imminently  [ref](https://twitter.com/mr_paul_banks/status/666338953776246784) and features redesigned high-level consumer which is powered entirely by kafka brokers with no need for client to talk to ZK nor to implement rebalancing logic etc.

Just wondered if there are already plans to support this in librdkafka (or an experimental attempt)? It's a huge win in that the complexity of implementing correct distributed consumer is largely taken into the broker and the consumer protocol itself is not a lot more complex than the old low level consumer. Details (such as they are so far) are here: https://cwiki.apache.org/confluence/display/KAFKA/Kafka+0.9+consumer+protocol

If no one else is working on it already, it //might// be something I or a colleague could contribute as we will probably want to consume from kafka from C/C++ pretty soon and it makes no sense to write a consumer from scratch.

Thanks

**Comment by banks** [comment]
Just found https://github.com/edenhill/librdkafka/wiki/Roadmap

Would still be interested to know when you anticipate working on that assuming 0.9 is released before the end of the month? Would having contributors help or hinder?

**Comment by edenhill** [comment]
It is not too early, in fact it is quite a timely question!

Work is currently being done to make librdkafka support Kafka 0.9, this includes:
 * a high-level KafkaConsumer with 0.9-based broker based consumer groups and client-side assignment strategies. The API is modelled after the official Java o.a.k new KafkaConsumer.
 * SSL support
 * SASL support
 * Broker-based quota support
 * Native Win32 support
 * Broker based offset storage
 * A fair consumer fetcher scheduler
 * and a load of bugfixes

I'm aiming to have the API stabilized within a week and a formal 0.9.0 release of librdkafka in december.

If you'd like to try it out see the `oct15` branch, I'd be real grateful to get some additional alpha testing on it.

Here is an example high-level consumer in C++:
https://github.com/edenhill/librdkafka/blob/oct15/examples/rdkafka_consumer_example.cpp#L387

Contributions are always welcome, at this stage the primary concern is with testing, so please do feel free to try it out.

**Comment by ah-** [comment]
With the new consumer, how would I best guarantee at least once processing of messages?

I think auto.commit.enable still commits before passing the messages to the consumer, so I'd have to use rd_kafka_offset_store manually?

**Comment by edenhill** [comment]
For exactly once you should disable auto commits and call commitSync() (WIP, available soon) as soon as you get the Message/rd_kafka_message_t.

**Comment by panarchus** [comment]
Will the old consumer API still be supported in the new version? More broadly: will I be able to consume from Kafka 0.8.x instances (obviously cannot use any new features) with the same librdkafka binaries as when consuming from 0.9? Will the old consumer API still work against 0.9?

**Comment by edenhill** [comment]
@panarchus Yes, the legacy simple consumer interface will still be supported and 0.8 is also supported.

**Comment by edenhill** [comment]
The legacy consumer will work for 0.9 as well, the protocol is backwards compatible.

**Comment by panarchus** [comment]
Awesome, thanks for the quick response.

**Comment by edenhill** [comment]
Fixed on master
