### ISSUE TITLE
Consumers in different threads performance bottleneck

### ISSUE THREAD

**Issue by haosdent** [edenhill/librdkafka#427]
In a same process, I use RdKafka::Consumer::create to create multi consumers in different threads to consume different topics. Do they share anything? Because I found the sum of all consumers speed have a limit. No matter how many consumers I start in same process.
When I use different processes, the sum of consumers speed impove processes number times.

**Comment by edenhill** [comment]
Different consumers will not share anything.
What differences in speed are you seeing?

**Comment by haosdent** [comment]
For example, I create 1 consumers in 1 threads. And the sum of speed is 20K per second. When I create 10 consumers in 10 threads, the sum of speed is still 20K per second. But when I start two processes, every processes have 20K per second, so I got the sum of speed 40K per second.

**Comment by edenhill** [comment]
Okay, well that does sound weird.
I dont see why there should be such a large discrepancy between the two.

Can you try running the two scenarios with profiling enabled? (--enable-profiling and then do  gprof ./your-program gmon.out)

**Comment by haosdent** [comment]
Sure, thank you very much for your reply. Let me try this.

**Comment by edenhill** [comment]
dont forget to add -pg to your own program's CFLAGS

**Comment by haosdent** [comment]
Hmm, thank you very much for your help. Let me try and feedback to you.

On Thu, Nov 19, 2015 at 2:17 AM, Magnus Edenhill <notifications@github.com>
wrote:

> dont forget to add -pg to your own program's CFLAGS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edenhill/librdkafka/issues/427#issuecomment-157807716>
> .
>



-- 
Best Regards,
Haosdent Huang

**Comment by haosdent** [comment]
Thank you for @edenhill helps, the limit is we use log4cxx. And this log library have bottleneck when have too much logs per seconds.

**Comment by edenhill** [comment]
Good to know and happy you found it!

**Comment by haosdent** [comment]
Yes, I am amazing the single consumer for librdkafka could handle 80 k records per second and increase linearly according to the number of threads. Thank you very much for your great work! :+1:

**Comment by edenhill** [comment]
Thanks :)

I've been able to top out the consumer just above 3 million messages / second.
(depends on message size of course, think that was 100 bytes/msg)

**Comment by haosdent** [comment]
LoL. Sounds great!
