### ISSUE TITLE
A question about  "How to decrease message latency" 

### ISSUE THREAD

**Issue by jimmy1911** [edenhill/librdkafka#428]
hi, edenhill 
    I read the wiki https://github.com/edenhill/librdkafka/wiki/How-to-decrease-message-latency and try to do some test. In my test senario, there is a producer with following config : 
    "queue.buffering.max.messages", "500000"
    "queue.buffering.max.ms", "1"
    "batch.num.messages", "1" 
    "message.send.max.retries", "3"
    "retry.backoff.ms", "500"
and a consumer with  following config : 
    "queued.min.messages", "1000000"
   "fetch.wait.max.ms", "10"
    "fetch.error.backoff.ms", "5"
    "event_cb", &ex_event_cb
Step1:
    start consumer to consume a new topic which have no message(consume timeout is set 50ms).
Step2:
    start producer to produce 1000 message(size 2000bytes) with a timestamp.
Step3:
    consumer  starts to consume message, and calculate the latency with  timestamp in message.
Before the 91st message, the avg latency is 13ms.After that there occured 20 consume TIME_OUT which makes 1000ms more latency.So the 92nd message's latency is about 1024ms. No mater how to set the consume timeout, the latency will be more than 1000ms.
    How to config producer and consumer to decrease the latency in this case?

**Comment by edenhill** [comment]
The sudden latency spike could be caused by the broker writing log to disk (syncing).
Look at broker config `log.flush.interval.messages` with friends, here:
http://kafka.apache.org/documentation.html#brokerconfigs

**Comment by jimmy1911** [comment]
I set log.flush.interval.messages=20000 and log.flush.interval.ms=10000. But the  latency is also more than 1000ms.

**Comment by haosdent** [comment]
Do these options work for you?
queue.buffering.max.ms - set to 1 (0 is an illegal value here).
fetch.wait.max.ms - set to your allowed maximum latency, e.g. 10 (ms).

**Comment by jimmy1911** [comment]
yes， I have set "queue.buffering.max.ms"="1"  in producer and set "fetch.wait.max.ms"="10" in consumer.
@haosdent, what is your latency after optimizing queue.buffering.max.ms and fetch.wait.max.ms?

**Comment by haosdent** [comment]
My global config is 
```
	// Set fetch.wait.max.ms to reduce fetch time in server.
	_globalConf->set("fetch.wait.max.ms", "10", errStr);
	// Set fetch.error.backoff.ms to reduce retry interval when fetch error in librdkafka.
	_globalConf->set("fetch.error.backoff.ms", "0", errStr);
	// Set queue.buffering.max.ms to reduce poll timeout in librdkafka.
	// This option should use the same value of "fetch.wait.max.ms" above.
	_globalConf->set("queue.buffering.max.ms", "10", errStr);
```

**Comment by jimmy1911** [comment]
my producer config:
    rd_kafka_conf_set(m_conf, "queue.buffering.max.messages", "500000",NULL, 0); 
    rd_kafka_conf_set(m_conf, "queue.buffering.max.ms", "1",NULL, 0);
    rd_kafka_conf_set(m_conf, "batch.num.messages", "1",NULL, 0); 
    rd_kafka_conf_set(m_conf, "debug", "all",NULL, 0); 
my consumer config:
    consumer_conf->set("metadata.broker.list", brokers, errstr);
    consumer_conf->set("queued.min.messages", "100000", errstr);
    consumer_conf->set("fetch.wait.max.ms", "10", errstr);
    consumer_conf->set("fetch.error.backoff.ms", "0", errstr);
    consumer_conf->set("debug", "all", errstr);
consumer,producer and kafka all run on the same node.
    In my test, consumer start to consume a clean topic, then producer starts to produce 1000 message.
At the beginning, the delay is about 13ms, after that consumer will get nothing from the broker and timeout(consume timeout is 50ms) for about 20 times.So, the latency is more than 1000ms.
    Can you tell me the latency in you case ?

**Comment by haosdent** [comment]
Less then 100ms, most are 10ms.

On Thu, Nov 19, 2015 at 3:28 PM, jimmy1911 <notifications@github.com> wrote:

> my producer config:
> rd_kafka_conf_set(m_conf, "queue.buffering.max.messages", "500000",NULL,
> 0);
> rd_kafka_conf_set(m_conf, "queue.buffering.max.ms", "1",NULL, 0);
> rd_kafka_conf_set(m_conf, "batch.num.messages", "1",NULL, 0);
> rd_kafka_conf_set(m_conf, "debug", "all",NULL, 0);
> my consumer config:
> consumer_conf->set("metadata.broker.list", brokers, errstr);
> consumer_conf->set("queued.min.messages", "100000", errstr);
> consumer_conf->set("fetch.wait.max.ms", "10", errstr);
> consumer_conf->set("fetch.error.backoff.ms", "0", errstr);
> consumer_conf->set("debug", "all", errstr);
> consumer,producer and kafka all run on the same node.
> In my test, consumer start to consume a clean topic, then producer starts
> to produce 1000 message.
> At the beginning, the delay is about 13ms, after that consumer will get
> nothing from the broker and timeout(consume timeout is 50ms) for about 20
> times.So, the latency is more than 1000ms.
> Can you tell me the latency in you case ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edenhill/librdkafka/issues/428#issuecomment-157975838>
> .
>



-- 
Best Regards,
Haosdent Huang

**Comment by jimmy1911** [comment]
@haosdent  can you supply your latency-test program?

**Comment by jimmy1911** [comment]
@edenhill,I opened debug and I found consumer was fetching offset 5 for about 20 times. Does this mean the latency is caused by producer?

LOG-7-FETCH: 10.10.38.70:9503/3: Fetch topic rt_memcache [0] at offset 5
LOG-7-CONSUME: 10.10.38.70:9503/3: consume from 1 toppar(s)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 1 toppars, fetching=1, backoff=18446744073708579ms
LOG-7-SEND: 10.10.38.70:9503/3: Sent FetchRequest (70 bytes, CorrId 1739)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 0 toppars, fetching=1, backoff=18446744073708579ms
LOG-7-RECV: 10.10.38.70:9503/3: Received FetchResponse (39 bytes, CorrId 1739, rtt 10.46ms)
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] MessageSet size 0, error "Success", MaxOffset 5
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch reply: Success
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] fetch queue 0 (0kb) >= queued.min.messages 100000 (queued.max.messages.kbytes 1000000)?
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch topic rt_memcache [0] at offset 5
LOG-7-CONSUME: 10.10.38.70:9503/3: consume from 1 toppar(s)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 1 toppars, fetching=1, backoff=18446744073708569ms
LOG-7-SEND: 10.10.38.70:9503/3: Sent FetchRequest (70 bytes, CorrId 1740)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 0 toppars, fetching=1, backoff=18446744073708569ms
LOG-7-RECV: 10.10.38.70:9503/3: Received FetchResponse (39 bytes, CorrId 1740, rtt 10.45ms)
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] MessageSet size 0, error "Success", MaxOffset 5
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch reply: Success
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] fetch queue 0 (0kb) >= queued.min.messages 100000 (queued.max.messages.kbytes 1000000)?
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch topic rt_memcache [0] at offset 5
LOG-7-CONSUME: 10.10.38.70:9503/3: consume from 1 toppar(s)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 1 toppars, fetching=1, backoff=18446744073708558ms
LOG-7-SEND: 10.10.38.70:9503/3: Sent FetchRequest (70 bytes, CorrId 1741)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 0 toppars, fetching=1, backoff=18446744073708558ms
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 0 toppars, fetching=1, backoff=18446744073708551ms
LOG-7-RECV: 10.10.38.70:9503/3: Received FetchResponse (530399 bytes, CorrId 1741, rtt 8.15ms)
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] MessageSet size 530360, error "Success", MaxOffset 257
LOG-7-CONSUME: 10.10.38.70:9503/3: Enqueue 252 messages on rt_memcache [0] fetch queue (0)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch reply: Success
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch topic rt_memcache [0] at offset 257
LOG-7-CONSUME: 10.10.38.70:9503/3: consume from 1 toppar(s)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 1 toppars, fetching=1, backoff=18446744073708549ms
LOG-7-SEND: 10.10.38.70:9503/3: Sent FetchRequest (70 bytes, CorrId 1742)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 0 toppars, fetching=1, backoff=18446744073708549ms
LOG-7-RECV: 10.10.38.70:9503/3: Received FetchResponse (530499 bytes, CorrId 1742, rtt 7.13ms)
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] MessageSet size 530460, error "Success", MaxOffset 509
LOG-7-CONSUME: 10.10.38.70:9503/3: Enqueue 252 messages on rt_memcache [0] fetch queue (199)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch reply: Success
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] fetch queue 451 (915kb) >= queued.min.messages 100000 (queued.max.messages.kbytes 1000000)?
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch topic rt_memcache [0] at offset 509
LOG-7-CONSUME: 10.10.38.70:9503/3: consume from 1 toppar(s)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 1 toppars, fetching=1, backoff=18446744073708542ms
LOG-7-SEND: 10.10.38.70:9503/3: Sent FetchRequest (70 bytes, CorrId 1743)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 0 toppars, fetching=1, backoff=18446744073708541ms
LOG-7-RECV: 10.10.38.70:9503/3: Received FetchResponse (530499 bytes, CorrId 1743, rtt 5.49ms)
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] MessageSet size 530460, error "Success", MaxOffset 761
LOG-7-CONSUME: 10.10.38.70:9503/3: Enqueue 252 messages on rt_memcache [0] fetch queue (432)LOG-7-FETCH: 10.10.38.70:9503/3: Fetch reply: Success
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] fetch queue 684 (1388kb) >= queued.min.messages 100000 (queued.max.messages.kbytes 1000000)?
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch topic rt_memcache [0] at offset 761
LOG-7-CONSUME: 10.10.38.70:9503/3: consume from 1 toppar(s)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 1 toppars, fetching=1, backoff=18446744073708536ms
LOG-7-SEND: 10.10.38.70:9503/3: Sent FetchRequest (70 bytes, CorrId 1744)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 0 toppars, fetching=1, backoff=18446744073708535ms
LOG-7-RECV: 10.10.38.70:9503/3: Received FetchResponse (503134 bytes, CorrId 1744, rtt 1.75ms)
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] MessageSet size 503095, error "Success", MaxOffset 1000
LOG-7-CONSUME: 10.10.38.70:9503/3: Enqueue 239 messages on rt_memcache [0] fetch queue (669)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch reply: Success
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] fetch queue 908 (1843kb) >= queued.min.messages 100000 (queued.max.messages.kbytes 1000000)?
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch topic rt_memcache [0] at offset 1000
LOG-7-CONSUME: 10.10.38.70:9503/3: consume from 1 toppar(s)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 1 toppars, fetching=1, backoff=18446744073708534ms
LOG-7-SEND: 10.10.38.70:9503/3: Sent FetchRequest (70 bytes, CorrId 1745)
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch for 0 toppars, fetching=1, backoff=18446744073708534ms
LOG-7-RECV: 10.10.38.70:9503/3: Received FetchResponse (39 bytes, CorrId 1745, rtt 10.24ms)
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] MessageSet size 0, error "Success", MaxOffset 1000
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch reply: Success
LOG-7-FETCH: 10.10.38.70:9503/3: Topic rt_memcache [0] fetch queue 728 (1476kb) >= queued.min.messages 100000 (queued.max.messages.kbytes 1000000)?
LOG-7-FETCH: 10.10.38.70:9503/3: Fetch topic rt_memcache [0] at offset 1000
LOG-7-CONSUME: 10.10.38.70:9503/3: consume from 1 toppar(s)

**Comment by edenhill** [comment]
What is your request.required.acks setting?
The higher replication the higher latency. E.g, compare 1 (just leader) to -1  (all ISR)

**Comment by jimmy1911** [comment]
I didn't set request.required.acks, the default value is 1.In my case, topic was created with --replication-factor 1 --partitions 1.

**Comment by jimmy1911** [comment]
I will new/destroy a rd_kafka_topic_conf_t to produce every message. Will this increase the latency.

**Comment by edenhill** [comment]
If you are using the same rd_kafka_t handle then an additional topic_new() will not affect performance (much), the topic object is cached internally so after your first topic_new("topic") any later topic_new("topic") will return the cached object. This also means it will only use the configuration passed to the first call to topic_new()

**Comment by jimmy1911** [comment]
OK. 
Can you give me some suggestions to find the reason of high latency?

**Comment by edenhill** [comment]
Well:
* Register a stats_cb and look at the broker rtt (round-trip-times).
* Use debug=protocol, it will give you a rtt measurement for each request. Look for Produce and Fetch (consumer). That is the amount of time spent on network (minimal) + broker handling

**Comment by jimmy1911** [comment]
OK, I will do both.Can a sync-producer decrease the latency.

**Comment by edenhill** [comment]
Highly unlikely

**Comment by edenhill** [comment]
rdkafka_performance has a end-to-end latency measurement mode, try it out.

# Consumer:
`rdkafka_performance -C -t test -p 0 -o end -l -u`
(also see the -A option)

# Producer:
`rdkafka_performance -P -t test -p 0 -s 1000 -l -u`

**Comment by jimmy1911** [comment]
Thanks for this suggestion.
The result of the latency measurement  is as follow:
Producer:
 ../rdkafka_performance -P -t test -p 0 -s 2000 -l -u -b 10.10.38.70:9501,10.10.38.70:9502,10.10.38.70:9503
% Sending messages of size 30 bytes
|    elapsed |       msgs |      bytes |        rtt |         dr |     dr_m/s |    dr_MB/s |     dr_err |     tx_err |       outq 
|          0 |          1 |         30 |          0 |          0 |          0 |       0.00 |          0 |          0 |          1 
%5|1447934260.230|TOPICBRK|rdkafka#producer-0| Topic test [0] migrated to unknown broker 2: requesting metadata update
%5|1447934260.231|TOPICBRK|rdkafka#producer-0| Topic test [0] migrated to unknown broker 2: requesting metadata update
|       1000 |     530990 |   15929700 |         51 |     199938 |     199936 |       6.00 |          0 |          0 |     331052 
|       2002 |     859098 |   25772940 |        395 |     359350 |     179421 |       5.38 |          0 |        378 |     499748 
|       3006 |    1003858 |   30115740 |        358 |     516850 |     171928 |       5.16 |          0 |        472 |     487008 
|       4006 |    1111550 |   33346500 |        315 |     617398 |     154091 |       4.62 |          0 |        532 |     494152 
|       5013 |    1300494 |   39014820 |        275 |     800494 |     159679 |       4.79 |          0 |        636 |     500000 
|       6013 |    1500666 |   45019980 |        354 |    1000666 |     166411 |       4.99 |          0 |        725 |     500000 
|       7015 |    1731069 |   51932070 |        355 |    1255269 |     178930 |       5.37 |          0 |        868 |     475800 
|       8021 |    2001382 |   60041460 |        195 |    1601140 |     199597 |       5.99 |          0 |        897 |     400242 
|       9021 |    2136998 |   64109940 |        328 |    1801355 |     199666 |       5.99 |          0 |        976 |     335643 
|      10025 |    2501381 |   75041430 |        339 |    2001381 |     199637 |       5.99 |          0 |       1029 |     500000 
|      11025 |    2701464 |   81043920 |        292 |    2201464 |     199675 |       5.99 |          0 |       1129 |     500000 
|      12025 |    3101768 |   93053040 |        213 |    2601768 |     216358 |       6.49 |          0 |       1175 |     500000 
|      13025 |    3301794 |   99053820 |        332 |    2801794 |     215103 |       6.45 |          0 |       1294 |     500000 
|      14039 |    3501895 |  105056850 |        250 |    3001895 |     213823 |       6.41 |          0 |       1394 |     500000 
|      15039 |    3869296 |  116078880 |        281 |    3402068 |     226214 |       6.79 |          0 |       1524 |     467228 
^C|      16045 |    4102226 |  123066780 |        332 |    3602226 |     224497 |       6.73 |          0 |       1629 |     500000 
% 1629 backpressures for 4102227 produce calls: 0.040% backpressure rate
|      16060 |    3602227 |  108066810 |        332 |    3602226 |     224291 |       6.73 |          0 |       1629 |     371159 

Consumer:
./rdkafka_performance -C -t test -p 0 -o end -l -u -b 10.10.38.70:9501,10.10.38.70:9502,10.10.38.70:9503 -A consume.out 
%5|1447934257.512|TOPICBRK|rdkafka#consumer-0| Topic test [0] migrated to unknown broker 2: requesting metadata update
%5|1447934257.512|TOPICBRK|rdkafka#consumer-0| Topic test [0] migrated to unknown broker 2: requesting metadata update
%5|1447934257.513|TOPICBRK|rdkafka#consumer-0| Topic test [0] migrated to unknown broker 2: requesting metadata update
%5|1447934257.517|TOPICBRK|rdkafka#consumer-0| Topic test [0] migrated to unknown broker 2: requesting metadata update
|    elapsed |       msgs |      bytes |        rtt |        m/s |       MB/s |     rx_err |     offset |   lat_curr |    lat_avg |     lat_lo |     lat_hi 
|        130 |          0 |          0 |          0 |          0 |       0.00 |          0 |          0 |       0.00 |       0.00 |       0.00 |       0.00 
|       1131 |          0 |          0 |          0 |          0 |       0.00 |          0 |          0 |       0.00 |       0.00 |       0.00 |       0.00 
|       2131 |          0 |          0 |         11 |          0 |       0.00 |          0 |          0 |       0.00 |       0.00 |       0.00 |       0.00 
|       3854 |        252 |       7560 |         40 |         65 |       0.00 |          0 |        252 |      38.98 |      39.03 |      38.98 |      39.39 
|       5128 |     199938 |    5998140 |          1 |      38986 |       1.17 |          0 |     199938 |     834.39 |    1010.40 |      38.98 |    1157.50 
|       6151 |     600262 |   18007860 |          1 |      97580 |       2.93 |          0 |     600262 |    2331.93 |    1654.08 |      38.98 |    2332.57 
|       7151 |     600262 |   18007860 |          1 |      83934 |       2.52 |          0 |     600262 |    2331.93 |    1654.08 |      38.98 |    2332.57 
|       8372 |     800494 |   24014820 |          4 |      95608 |       2.87 |          0 |     800494 |    2811.88 |    2029.77 |      38.98 |    3440.63 
|       9587 |    1000666 |   30019980 |          8 |     104375 |       3.13 |          0 |    1000666 |    2858.83 |    2301.51 |      38.98 |    3844.30 
|      11336 |    1419700 |   42591000 |          6 |     125228 |       3.76 |          0 |    1419699 |    3076.85 |    2540.38 |      38.98 |    3897.96 
|      12924 |    1820079 |   54602370 |          6 |     140821 |       4.22 |          0 |    1820078 |    2820.40 |    2563.02 |      38.98 |    3897.96 
|      14098 |    2020105 |   60603150 |          0 |     143286 |       4.30 |          0 |    2020104 |    3344.50 |    2573.14 |      38.98 |    3897.96 
|      15407 |    2420375 |   72611250 |         99 |     157087 |       4.71 |          0 |    2420374 |    2804.71 |    2565.60 |      38.98 |    3897.96 
|      16763 |    2820518 |   84615540 |          5 |     168257 |       5.05 |          0 |    2820517 |    2760.80 |    2527.32 |      38.98 |    3897.96 
|      17911 |    3001895 |   90056850 |          6 |     167598 |       5.03 |          0 |    3001895 |    2267.46 |    2526.73 |      38.98 |    3897.96 
|      19696 |    3602730 |  108081900 |          5 |     182912 |       5.49 |          0 |    3602729 |    2600.17 |    2541.92 |      38.98 |    3897.96 
|      20796 |    3602730 |  108081900 |         10 |     173236 |       5.20 |          0 |    3602730 |    2600.17 |    2541.92 |      38.98 |    3897.96 
|      21796 |    3602730 |  108081900 |         28 |     165286 |       4.96 |          0 |    3602730 |    2600.17 |    2541.92 |      38.98 |    3897.96 
^C|      22797 |    3602730 |  108081900 |         37 |     158034 |       4.74 |          0 |    3602730 |    2600.17 |    2541.92 |      38.98 |    3897.96 
|      22797 |    3602730 |  108081900 |         84 |     158034 |       4.74 |          0 |    3602730 |    2600.17 |    2541.92 |      38.98 |    3897.96 
% Average application fetch latency: 6us

And the consumer -A output  file content is like this:
first 20 lines;
1 39389
      2 39084
      3 39080
      4 39079
      5 39075
      6 39075
      7 39075
      8 39074
      9 39074
     10 39074
     11 39073
     12 39074
     13 39074
     14 39073
     15 39073
     16 39073
     17 39072
     18 39072
     19 39072
     20 39071

last 20 lines:
3602711 2600163
3602712 2600164
3602713 2600164
3602714 2600164
3602715 2600164
3602716 2600164
3602717 2600165
3602718 2600165
3602719 2600165
3602720 2600165
3602721 2600165
3602722 2600166
3602723 2600166
3602724 2600167
3602725 2600166
3602726 2600166
3602727 2600166
3602728 2600167
3602729 2600167
3602730 2600168

2600168 means 2600168us?

**Comment by edenhill** [comment]
@jimmy1911 Were you able to reduce latency?
