### ISSUE TITLE
High CPU usage due to short poll timeouts

### ISSUE THREAD

**Issue by vincentbernat** [edenhill/librdkafka#429]
Hey!

I am observing a high CPU usage from librdkafka without much activity (network-wise, one small batch every 5 seconds). Here is some output from strace:

```
   3263 [pid  5945] poll([{fd=15, events=POLLIN}], 1, 1 <unfinished ...>
   3264 [pid  5943] poll([{fd=16, events=POLLIN}], 1, 1 <unfinished ...>
   3264 [pid  5944] poll([{fd=13, events=POLLIN}], 1, 1 <unfinished ...>
   3264 [pid  5946] poll([{fd=18, events=POLLIN}], 1, 1 <unfinished ...>
   3264 [pid  5947] poll([{fd=17, events=POLLIN}], 1, 1 <unfinished ...>
   3264 [pid  5948] poll([{fd=19, events=POLLIN}], 1, 1 <unfinished ...>
```

All the FD are connected to a Kafka broker.

The first figure is the number of time the event was detected. strace was running for only a few seconds. If I build a flame graph, I also see that most of the time (85%) is spent in polling. I am calling `rd_kafka_poll` with a timeout of 5000 ms. So, I don't know where the 1ms timeout comes from.

The code is available here:
 https://github.com/balabit/syslog-ng-incubator/blob/master/modules/kafka/kafka.c#L378

I have the problem with both librdkafka 0.8.5 and 0.8.6.

**Comment by edenhill** [comment]
The internal poll() in 0.8.6 uses "queue.buffering.max.ms" as timeout.
Are you setting that value to 1 perhaps?

**Comment by vincentbernat** [comment]
Yes, it is set to 1. The description is misleading: "Maximum time for buffering data on the producer queue". I set it to 1 to ensure that if there is data to send, it is sent right away. I didn't expect to have an active loop when no data is present.

However, I now understand its meaning: if we want to send a message as fast as possible, we have to not wait for the network too long to be able to check the message queue as soon as possible. Isn't possible to use a file descriptor to signal a new message in the message queue?

**Comment by vincentbernat** [comment]
Setting the value to 1000 fixes my problem. This is a fine value for me. Thanks!

**Comment by vincentbernat** [comment]
Now, I remember why I put 1 in the first place. I am using the following code: https://github.com/balabit/syslog-ng-incubator/blob/master/modules/kafka/kafka.c#L374-L396

If I set `queue.buffering.max.ms` to 1000, I'll have to wait 1000 ms each time I want to acknowledge one message. It's easier for me to acknowledge messages synchronously one at a time instead of acknowledging a whole batch asynchronously (syslog-ng API is easier this way). So, how could I retrieve acks without pausing while not using a lot of CPU for other operations?

**Comment by edenhill** [comment]
If you are okay with async delivery (always the way to go, always!) I would suggest either using a separate thread that does just rd_kafka_poll(), or plugging the poll in to your program/library's main loop (if such exists).

If you are stuck with sync delivery (never the way to go, never!) then you will need to minimize the queue.buffering.max.ms config, with the inherit problems of that (such as poll() busy looping).

Your previous suggestion with using an fd to "wake up" the poll when needed is good but it will not be implemented for the next release, so earliest is probably in January.
