### ISSUE TITLE
Consume to EOF ends subscription

### ISSUE THREAD

**Issue by incessantier** [edenhill/librdkafka#430]
I seem to occasionally receive the ERR__PARTITION_EOF prematurely during consumption (I know there is still data on the partition).  When this occurs, is the subscription stopped?  The only way I have found to continue consuming from the partition is to restart the subscription.

**Comment by edenhill** [comment]
You will receive PARTITION_EOF as soon as your consumer catches up with the end of the partition (which is a moving target), but it shouldn't stop consuming that partition. What it will do is back off for a short while (`fetch.error.backoff.ms=500`) before doing the next fetch to avoid busy-looping on the partition tail.

Is this on the oct15 branch?

**Comment by incessantier** [comment]
No, this was on master.

**Comment by incessantier** [comment]
I do not appear to be having any problems with it on the oct15 branch.  I've seen an issue mentioned resolved in oct15 about receiving the incorrect offsets...it's possible my root problem is related to that.  What is your ETA on merging oct15 into master?

**Comment by edenhill** [comment]
Do you stop()+start() your consumer? That is not very well handled in the master branch and is subject to race conditions which can give these sort of errors.

My plan is to have it merged within a month and hopefully a release short after that.

**Comment by incessantier** [comment]
yes, exactly.  I am doing a lot of stop+start calls.  Thanks.

**Comment by edenhill** [comment]
Ah, that's a no go currently.
Are you doing it because of flow control or because you want to seek?

**Comment by incessantier** [comment]
yes :)  Our system design has a very dynamic processing setup....the nodes handling processing come up/down pretty regularly depending on the type of processing that is needed.

In order to track where a a dataset for processing resides, we use a separate topic with some processing "meta-data".  This meta-data includes the topic/partition/offset/number of messages for a processing set.  We then have a consumer subscribing to the meta-data topic, which then farms out processing tasks to the individual nodes.  I admit that it is not how kafka intends processing to be done (a consumer for each partition), but it allows us some flexibility in resource management and load balancing.

The Oct15 branch has been working quite well, so we are switching to that until it is merged into master (we are still very-much in development...nothing production).

**Comment by edenhill** [comment]
Thanks for the explanation, It sounds like you wont have any need for consumer group balancing, right?
What are you using for offset storage?

**Comment by incessantier** [comment]
No, we aren't using the consumer group balancing.  I don't have offset storage built-in yet.  But the only offset storage we will need to handle is on the "meta-data" topic.  The difficulty is that we will have several consumers of that meta-data...not distributed consumers, but several consumers that will need all the data.  I'll probably end up using zookeeper so that each consumer can store their offset individually.

**Comment by edenhill** [comment]
You could use a compacted topic for storing offsets where the key is the consumer type.

**Comment by incessantier** [comment]
I haven't played with log compaction at all, but an initial read makes that intriguing, thanks.  How does a consumer know what offset to start from in the event of a failure?  Is there a way to just consume the last message for a given key?
