### ISSUE TITLE
rd_kafka_message_destroy cause memory leak

### ISSUE THREAD

**Issue by hitljs** [edenhill/librdkafka#431]
Hi，i am using the c consume function when i call the rd_kafka_message_destroy(rkmessage); and return and found the memory leak problem。 like this
                if (rkmessage->len <= sizeof(pack_header_t)) {
                    LOG(COMLOG_WARNING, "message len[%d] too small", rkmessage->len);
                    rd_kafka_message_destroy(rkmessage);
                } else 
                    rd_kafka_message_destroy(rkmessage);
                    return RECV_SUCC;  //this will cause memory leak
                } 

how can i fix this，thank you。

**Comment by edenhill** [comment]
Please run your program with `valgrind --leak-check=full ./your-program and args...` to find the root of the memory leak.
Thanks

**Comment by edenhill** [comment]
Any luck?
