### ISSUE TITLE
Num Partitions

### ISSUE THREAD

**Issue by incessantier** [edenhill/librdkafka#433]
Is there a way to get the number of partitions on a topic via the C++ API?  It doesn't seem like the metadata is readily available in the C++ realm.

**Comment by edenhill** [comment]
The metadata() API is missing from the C++ API, there is a semi-done PR here:
https://github.com/edenhill/librdkafka/pull/221

If someone wants to finish it I'd be happy to merge it.
It should generally following Google's C++ coding standards.

**Comment by incessantier** [comment]
I might take a stab at it.  What held it back last year?

**Comment by edenhill** [comment]
Not really sure anymore, I will have a look but it'll be a week or two.
Can you give it the once over and see if it looks good?

**Comment by incessantier** [comment]
Just a quick glance and it looked like it was done.  You had asked @eugpermar to fix a few style things which look resolved.  I merged master up to it and issued a PR #434.

**Comment by eugpermar** [comment]
Hi @incessantier , nice to meet you.

In theory, the only think that left to do in the PR was regression tests, that I left out because all test base was in C, not C++. If you or @edenhill need it, I could make them.

**Comment by incessantier** [comment]
you too, @eugpermar.  Thanks for already having that wrapped and ready for me when I needed it! ;)  I'll defer to @edenhill on how he wants to handling testing...I am curious on how you unit test things that may require various broker setups, though.

**Comment by edenhill** [comment]
@incessantier There are no unit tests, but a bunch of functional tests in `tests/` (currently only C, will need some C++ test helper wrappers). These tests require a >=three broker cluster.

The long term plan is to use virtualization (vagrant or docker) to provide a known good test environment.
