### ISSUE TITLE
Sorry for interrupting you,How can I make some proceducer in one program

### ISSUE THREAD

**Issue by z772458549** [edenhill/librdkafka#435]
rd_kafka_t *rk[];
rd_kafka_conf_t *conf[];
if two proceducer will work,more core,

**Comment by edenhill** [comment]
Did you have a look at the example programs?
https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.c

It should give you good starting point to create your own client.

**Comment by z772458549** [comment]
I seem,but example is single producer,rdkafka c api can support double or more producer

**Comment by edenhill** [comment]
You can produce to multiple topics using one rd_kafka_t handle.

You only need multiple rd_kafka_t handles if you want to produce to different kafka clusters, or using different configuration depending on handle.

**Comment by z772458549** [comment]
Oh,thank you very much! I will try it
