### ISSUE TITLE
Cannot send messages with rd_kafka_produce

### ISSUE THREAD

**Issue by maiduy** [edenhill/librdkafka#439]
I want to push message with flexible topic to Kafka cluster by zookeeper, I create kafka handle with rd_kafka_new, then I add brokers with rd_kafka_brokers_add, and waiting for data poured in from other systems, corresponding to each kind of data, I create topic with rd_kafka_topic_new, and then I called rd_kafka_produce, but cannot send messages to kafka cluster although it is not an error.

**Comment by edenhill** [comment]
Have you registered a delivery report callback (..conf_set_dr_cb or conf_set_dr_msg_cb (preferred))?
You dont have to, but it lets you know the send status of each message, if it was produced succesfully or failed and for what reason.

**Comment by maiduy** [comment]
I register delivery report callback with rd_kafka_conf_set_dr_cb, when i try call rd_kafka_metadata(rk, rkt?0:1, rkt,&metadata, 5000), it return "Failed to acquire metadata: Time out", before call rd_kafka_produce.

**Comment by edenhill** [comment]
Sounds like you have connectivity issues, try enabling "debug=broker" (conf_set..) to see what's up.
