### ISSUE TITLE
process can not exit when Ctrl + C

### ISSUE THREAD

**Issue by oyld** [edenhill/librdkafka#441]
In oct15 branch rdkafka_consumer_example.
I have 3 brokers and one broker down.
When I enter Ctrl + C, process can not exit.
It looks like one broker thread sleep in poll() so main thread sleep in pthread_join().

(gdb) info threads
  Id   Target Id         Frame 
  5    Thread 0x7ffff5df2700 (LWP 10264) "rdkafka_consume" 0x00007ffff76e1b7d in poll () at ../sysdeps/unix/syscall-template.S:81
  2    Thread 0x7ffff75f5700 (LWP 10261) "rdkafka_consume" 0x00007ffff7bc7f27 in pthread_join (threadid=140737318430464, thread_return=thread_return@entry=0x7ffff75f41c8)
    at pthread_join.c:92
* 1    Thread 0x7ffff7fe42c0 (LWP 10260) "rdkafka_consume" 0x00007ffff7bc7f27 in pthread_join (threadid=threadid@entry=140737343608576, 
    thread_return=thread_return@entry=0x7fffffffe128) at pthread_join.c:92

**Comment by edenhill** [comment]
Please use the 0.9.0 branch now, this should be fixed
Den 3 dec 2015 08:21 skrev "oyld" <notifications@github.com>:
