### ISSUE TITLE
rdkafka_example application can't connect the kafka on the remote server

### ISSUE THREAD

**Issue by yanchaomars** [edenhill/librdkafka#442]
I used librdkafka version 0.8.6 (0x00080600) version, the rdkafka_example can work well to connect localhost kafka, but when I changed the broker address with a remote server, and test the kafka server  remote , the rdkafka_example will report connect refused, and the broker still use localhost, logs as followed:

[root@localhost examples]# ./rdkafka_example -P -t test -p 0 -b 192.168.44.98:9092
% Type stuff and hit enter to send
1449192392.132 RDKAFKA-3-FAIL: rdkafka#producer-0: localhost:9092/0: Failed to connect to broker at localhost:9092: Connection refused
1449192392.132 RDKAFKA-3-ERROR: rdkafka#producer-0: localhost:9092/0: Failed to connect to broker at localhost:9092: Connection refused

Is anyone have the same issue?

**Comment by yanchaomars** [comment]
Figured out!
The remote kafka server need set the value of "advertised.host.name" , as , if not set, the kafka will use the "host.name" value which is setted as "localhost" . The configure file is under kafka_2.9.1-0.8.2.2/config/server.properties

**Comment by karthikeyanajendran1984** [comment]
Hi @edenhill,

I am new to kafka and currently working in a project which we are using librdkafka API, can you please guide me if Connection refused happened after the call broker add API, in what way we can handle this error in application side? as you have mentioned to use call back function. Can you please tell me which call back function need to be use for this function and do i need to use it after the broker add API ?

**Comment by edenhill** [comment]
@karthikeyanajendran1984 You can register an error_cb to get notified of various generic errors, such as when unable to connect to broker (in which case the error code will be `RD_KAFKA_RESP_ERR__TRANSPORT`)

**Comment by karthikeyanajendran1984** [comment]
Hi @edenhill ,
Thanks you very much for reply. Just tried with error_cb (rd_kafka_conf_set_error_cb(lcommsConfig->kafkaConfig, err_cb); and our err_cb just contains "%% ERROR CALLBACK: %s:  %s\n", rd_kafka_name(rk),  reason. but still not printing the error code in stdin where we are running our binary. 
Can you please advice whether i m using a correct  callback function and why it is not printing ?
Also i have attached code block which i m using currently. Can you please assist ?

[comms_kafka.zip](https://github.com/edenhill/librdkafka/files/1180104/comms_kafka.zip)

**Comment by karthikeyanajendran1984** [comment]
Hi @edenhill ,
Sorry to bother you, your suggestion worked by using error_cb call back function. 
Broker Count 1 Topic Succssfully Subscribed% ERROR CALLBACK: rdkafka#consumer-1: error: -187 1/1 brokers are down

Once again thanks very much for reply.
