### ISSUE TITLE
High level consumer

### ISSUE THREAD

**Issue by oyld** [edenhill/librdkafka#443]
A new group looks like consume from the largest offset, why not begin from smallest offset?
And how can I customize offset?

**Comment by edenhill** [comment]
Set `auto.offset.reset=earliest` on the default topic config object, something like:
````
rd_kafka_conf_t *conf = rd_kafka_conf_new();
rd_kafka_topic_conf_t *tconf = rd_kafka_topic_conf_new();
rd_kafka_topic_conf_set(tconf, "auto.offset.reset", "earliest", NULL, 0);

rd_kafka_conf_set_default_topic_conf(conf, tconf)
````
