### ISSUE TITLE
Use v0.9.0 lib consumer offset stored broker , when restart consumer reset the offset to the largest offset

### ISSUE THREAD

**Issue by nmred** [edenhill/librdkafka#444]
Error Log:

RDKAFKA-7-OFFSET:rdkafka#consumer-0:test [4]: offset reset (at offset ERROR) to END: no previously committed offset available: Local: No offset stored

**Comment by nmred** [comment]
My kafka broker version is V0.9.0.0.

**Comment by edenhill** [comment]
How are you shutting down your consumer?

**Comment by nmred** [comment]
Ctl + C

**Comment by nmred** [comment]
I test rdkafka_consumer_example script seem error report

1449648058.492 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic test [0]: setting default offset -1001
1449648058.492 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic test [1]: setting default offset -1001
1449648058.492 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic test [2]: setting default offset -1001
1449648058.492 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic test [3]: setting default offset -1001
1449648058.492 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic test [4]: setting default offset -1001
1449648058.492 RDKAFKA-7-CGRPOP: rdkafka#consumer-0: Group "tes" received op REPLY:OFFSET_FETCH in state up (join state assigned)
1449648058.492 RDKAFKA-7-FETCHSTART: rdkafka#consumer-0: Group "tes": starting fetchers for 5 assigned partition(s)
1449648058.492 RDKAFKA-7-CONSUMER: rdkafka#consumer-0: Start consuming test [0] at offset ERROR
1449648058.492 RDKAFKA-7-CONSUMER: rdkafka#consumer-0: Start consuming test [1] at offset ERROR
1449648058.492 RDKAFKA-7-CONSUMER: rdkafka#consumer-0: Start consuming test [2] at offset ERROR
1449648058.492 RDKAFKA-7-OP: rdkafka#consumer-0: test [0] received op FETCH_START (v2) in fetch-state none
1449648058.492 RDKAFKA-7-FETCH: rdkafka#consumer-0: Start fetch for test [0] in state none at offset ERROR (v2)
1449648058.492 RDKAFKA-7-CONSUMER: rdkafka#consumer-0: Start consuming test [3] at offset ERROR
1449648058.492 RDKAFKA-7-PARTSTATE: rdkafka#consumer-0: Partition test [0] changed fetch state none -> offset-query
1449648058.492 RDKAFKA-7-CONSUMER: rdkafka#consumer-0: Start consuming test [4] at offset ERROR
1449648058.492 RDKAFKA-7-OFFSET: rdkafka#consumer-0: test [0]: offset reset (at offset ERROR) to END: no previously committed offset available: Local: No offset stored
1449648058.492 RDKAFKA-7-OFFSET: rdkafka#consumer-0: test [0]: no current leader for partition, starting offset query timer for offset END

**Comment by edenhill** [comment]
Is this your own client or are you using one of the examples?

**Comment by nmred** [comment]
Yes, I use rdkafka_consumer_example test

**Comment by edenhill** [comment]
Okay, if you run with `-d cgrp,topic,protocol` you should be seeing something like this when you shut it down:
````
1449650025.328 RDKAFKA-7-CGRPJOINSTATE: rdkafka#consumer-0: Group "g11" changed join state assigned -> wait-unassign
1449650025.328 RDKAFKA-7-COMMIT: rdkafka#consumer-0: Group "g11": committing offsets for 4 partition(s)
1449650025.328 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic small [0]: committing stored offset 1000
1449650025.328 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic small [1]: committing stored offset 1000
1449650025.328 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic small [2]: committing stored offset -1
1449650025.328 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic small [3]: committing stored offset -1
1449650025.328 RDKAFKA-7-OFFSET: rdkafka#consumer-0: eden:9093/3: OffsetCommitRequest(v1, 4 partition(s)))
````

And on restart you should be seeing this:
````
1449650038.205 RDKAFKA-7-CGRPOP: rdkafka#consumer-0: Group "g11" received op REPLY:OFFSET_FETCH in state up (join state assigned)
1449650038.205 RDKAFKA-7-FETCHSTART: rdkafka#consumer-0: Group "g11": starting fetchers for 4 assigned partition(s)
1449650038.205 RDKAFKA-7-CONSUMER: rdkafka#consumer-0: Start consuming small [0] at offset 1000
1449650038.205 RDKAFKA-7-CONSUMER: rdkafka#consumer-0: Start consuming small [1] at offset 1000
1449650038.205 RDKAFKA-7-CONSUMER: rdkafka#consumer-0: Start consuming small [2] at offset ERROR
1449650038.205 RDKAFKA-7-CONSUMER: rdkafka#consumer-0: Start consuming small [3] at offset ERROR
````

**Comment by nmred** [comment]
I use `-d cgrp,topic,protocol` debug level log is:

```
1449650595.219 RDKAFKA-7-COMMIT: rdkafka#consumer-0: Group "gtest": committing offsets for 5 partition(s)
1449650595.219 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic test [0]: committing stored offset -1
1449650595.219 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic test [1]: committing stored offset -1
1449650595.219 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic test [2]: committing stored offset -1
1449650595.219 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic test [3]: committing stored offset -1
1449650595.219 RDKAFKA-7-OFFSET: rdkafka#consumer-0: Topic test [4]: committing stored offset -1
1449650595.219 RDKAFKA-7-COMMIT: rdkafka#consumer-0: Group "gtest": no valid offsets to commit
```

offset commit fail when stop consumer.

**Comment by nmred** [comment]
Sorry!

Example script not problem,  Thanks!
