### ISSUE TITLE
How to set topic configuration properties in a configuration file?

### ISSUE THREAD

**Issue by microwish** [edenhill/librdkafka#446]
When I try setting topic configurations in consumer.properties, e.g. offset.store.path, "No such configuration property" error occurs.
What to do to set topic configuration properties?

**Comment by edenhill** [comment]
`offset.store.path` is topic configuration property so you will need to set that on your `rd_kafka_topic_conf_t` (or RdKafka::Conf of type CONF_TOPIC in  C++).

With regards to configuration files, what I usually do is something like:
````
foreach line in file {
   // Split "name=val" into separate variables.
  split(line, &name, &val);

   // Try topic config first
   r = rd_kafka_topic_conf_set(topic_conf, name, val, errstr, ..);
   if (r == RD_KAFKA_CONF_OK)
    continue;
   else if (r == RD_KAFKA_CONF_INVALID)
     fail(errstr);  // property name exists but value is malformed, fail.

  // Was not a topic config, now try global kafka config
  r = rd_kafka_conf_set(conf, name, val, errstr, ..);
  if (r == RD_KAFKA_CONF_OK)
    continue;
  else if (r == RD_KAFKA_CONF_INVALID)
    fail(errstr);

  // Now an rdkafka topic/global config property, pass the config along to the application.
  my_app_conf_set(name, val);
}
````

**Comment by microwish** [comment]
Got it. Scopes of properties in a configuration file should be check while the file is parsed.
Thanks.
