### ISSUE TITLE
message less than message.timeout.ms also be callback timeout

### ISSUE THREAD

**Issue by laxpio** [edenhill/librdkafka#450]
i use lib 0.8.6 and kafka 0.8.2.1
when the message input produce buffer,i will set a curr time,and when get the message callback,try to compare with callback_time,and find the sub_time(818) is less then message.timeout.ms(30000),and there some timeout callback in a second,the first message is out of timeout.

**Comment by edenhill** [comment]
Can you reproduce this with just one single message and with `debug=broker,msg,queue` enabled?

**Comment by laxpio** [comment]
it more log,e.g: "36 request(s) timed out: disconnect"

**Comment by edenhill** [comment]
That sounds like you have issues with the broker. Either connection problems or the broker is malfunctioning. Have you checked the broker logs?

**Comment by laxpio** [comment]
the log in broker:
Closing socket for /host because of error
it likes the produce close the connect

**Comment by laxpio** [comment]
MSGSET log:
MessageSet with 1 message(s) not delivered
failed: err: Local: Message timed out: (errno: Connection
 timed out)

**Comment by edenhill** [comment]
...:
* Which broker version?
* Does it work with the scala/java client?
* Try increasing logging on the broker
* Do you have packet loss between broker and client? (ping ..)
* How large are your messages?

**Comment by laxpio** [comment]
1. broker: 0.8.2.1
2. java client sync is ok
4. ping times 2ms
5. msg size : 1000 ~ n*100,000

and i set message.timeout.ms(30000),message.send.max.retries=1,and req timeout only 5s,why the message will keep 30s+,is it send block?

**Comment by edenhill** [comment]
Can you reproduce this on `master` branch with just one single message and with `debug=broker,msg,queue` enabled?
If so, please upload the log.

**Comment by laxpio** [comment]
strange, it is work ok now,and i does not do any modify...

**Comment by laxpio** [comment]
add the log about (rkbuf->rkbuf_ts_enq - rkbuf->rkbuf_ts_sent),the time interval will larger than 4000ms,it does produce too fast?

**Comment by laxpio** [comment]
0.9 would be disabled  SSL explicitly?

**Comment by edenhill** [comment]
I dont really understand what you mean by produce too fast, please try to be more elaborate, thanks.

There is currently no way to explicitly disable building with SSL support if ./configure finds the needed SSL libraries, but it will not use SSL runtime unless you configure security.protocol=ssl

**Comment by laxpio** [comment]
rkbuf_ts_enq is rkbuf put in rkb_outbufs.rkbq_bufs, rkbuf_ts_sent is rkbuf send by socket,and them interval larger than 4000ms,so i guess maybe produce to fast and deal message delay, or broker io server block.

**Comment by laxpio** [comment]
add log in the method rd_kafka_send
if (!(rkbuf->rkbuf_flags & RD_KAFKA_OP_F_NO_RESPONSE)){
			rd_kafka_bufq_enq(&rkb->rkb_waitresps, rkbuf);
			//add debug
			if( (rkbuf->rkbuf_ts_sent - rkbuf->rkbuf_ts_enq) > 3*1000*1000 )
				rd_rkb_dbg(rkb, MSG, "PUTWAITBUF", "put wait buf,sent time = %"PRIu64
						"|rkbuf_ts_enq time = %"PRIu64"|speed times = %"PRIu64"|msg size = %i |CorrId %"PRId32,
						rkbuf->rkbuf_ts_sent,rkbuf->rkbuf_ts_enq,rkbuf->rkbuf_ts_sent-rkbuf->rkbuf_ts_enq,
						rkbuf->rkbuf_msgq.rkmq_msg_cnt,rkbuf->rkbuf_corrid);
		}

will get some log,the speed times larger 4000ms,and ack = -1,replicas=3

**Comment by edenhill** [comment]
Ah, okay, so it seems the request is queued on the xmit for 4000 ms before being sent?
That is a long time.
Can you print the request type? `rd_kafka_ApiKey2str(rkbuf->rkbuf_reqhdr.ApiKey)`

Also try running with `debug=protocol`, it will show you round-trip-times (rtt) per request.

**Comment by laxpio** [comment]
rtt time 300+ms - 1000+ms

**Comment by laxpio** [comment]
request type Unknown-768?，this type is?

**Comment by edenhill** [comment]
Ah, that is in big endian, so the request type is 3 aka MetadataRequest.
It should typically not take 4 seconds to complete.

**Comment by edenhill** [comment]
Do you have any idea why you get such slow response times? How is your broker health?
What is the network connectivity?

**Comment by laxpio** [comment]
the ping time just 0.3-2ms,the net in io 600Mb+ pre broker,and kafka metrics 99.9% deal per req speed 50ms.
at the same time, java producer can write 800Mb/s with ack=1.

**Comment by laxpio** [comment]
c producer ack=-1 and replicas=3

**Comment by edenhill** [comment]
@laxpio What's the status on this, did you find the cause of the slow broker response times?
