### ISSUE TITLE
keeps producing to down broker

### ISSUE THREAD

**Issue by hitljs** [edenhill/librdkafka#451]
HI, i am using the rd_kafka_produce, while one computer shut down which in the broker list, and the  information removed from zookeeper list，i wonder why the produce function still send message to the broken machine with the following message [rdkafka error 10.26.90.17:9092/22: Fai
led to connect to broker at tc-fc-kafka22.tc.baidu.com:9092: Connection timed out]

**Comment by edenhill** [comment]
Can you reproduce this with `debug=topic,broker`?
