### ISSUE TITLE
Subscribe to topic using regex/wildcard

### ISSUE THREAD

**Issue by coberty** [edenhill/librdkafka#452]
Hello,
Let's say I have some topics: test_1, test_2, test_3, ...

In rdkafkacpp.h I've found:
```Regex pattern matching automatically performed for topics prefixed with \c \"^\" (e.g. \c \"^myPfx[0-9]_.*\"```

So I'm trying to subscribe to them using patterns ```^test_.```, ```^test_.*```, ```^test_*```, even ```^test_2```. None of them are working - I haven't received any message. What am I doing wrong?
```test_2``` (w/o caret symbol) works fine but it's not a pattern.

I'm working on rdkafka_consumer_example.cpp tailored to win32 environment.

cob

**Comment by edenhill** [comment]
Huhm, yeah, that does seem a bit flaky.
It works for me with one regex for some topics.

Thanks for reporting this

**Comment by edenhill** [comment]
Turns out the trex regex implementation is buggy and Ive ripped it out,
until I can find a portable alternative I'll use the standard libc regex functionality.
This means, however, that there will be no native Win32 support for this feature.

The plan is probably to use pcre (which is available as NuGet package)

**Comment by kparadkar** [comment]
Can rd_kafka_subscribe call mix of regular topics and regex in the topic list ?
can I pass topic1, topic2, ^_t* ^p* to the rd_kafka_subscribe call?

is it mutually exclusive subscription? either topics or regex not both?

**Comment by edenhill** [comment]
@kparadkar Yes, you can mix as you wish.

**Comment by kparadkar** [comment]
@edenhill Does librdkafka perform complete pattern match or partial? 
If I have topics ta1, tb1, a1, b1 and if I have regex ^a.* and ^b.*, I should get only a1 and b1 topics right (as per /bin/kafka-topic.sh util)?

**Comment by edenhill** [comment]
Not sure what you mean by complete or partial, but the prefixing '^' token is actually part of the regex itself which means regexps are anchored, and thus your example is correct, it will only match a1 and b1.

**Comment by kparadkar** [comment]
Thanks @edenhill , Sorry for posting qn in incorrect thread.
