### ISSUE TITLE
0.8.6 build does not properly specify librdkafka.so as a linker dependency for librdkafka++

### ISSUE THREAD

**Issue by petergaultney** [edenhill/librdkafka#456]
This may apply to other builds - this is simply the only one I have tested.

I have encountered runtime linking errors when running an executable that specifies a dependency on the C++ librdkafka++, but does not explicitly specify a dependency on the C librdkafka library. The executable in question does not have a direct dependency on any methods inside librdkafka.so, and so linking it with the flag --as-needed results in a build that does not include librdkafka.so as an explicit dependency. 

However, loading librdkafka++ at runtime immediately attempts to resolve various librdkafka.so methods, resulting in a linker error something like this:

/usr/bin/xxxxx: symbol lookup error: /usr/lib/librdkafka++.so.1: undefined symbol: rd_kafka_conf_new

Running ldd against /usr/local/lib/librdkafka++.so.1 lists the following dependencies:

	linux-vdso.so.1 (0x00007ffc2bc4a000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f7221968000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/libstdc++.so.6 (0x00007f7221660000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/libgcc_s.so.1 (0x00007f7221448000)
	libc.so.6 => /lib/libc.so.6 (0x00007f72210a0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7221db0000)
	libm.so.6 => /lib/libm.so.6 (0x00007f7220da8000)

However, I believe librdkakfa++.so.1 should also be listed.

**Comment by edenhill** [comment]
Thanks for pointing this out, it is now fixed on master. Can you give it a try?
