### ISSUE TITLE
Free function for rd_kafka_memberid

### ISSUE THREAD

**Issue by ah-** [edenhill/librdkafka#459]
It would be very useful to have a corresponding free() function exported by librdkafka, so one can safely clean up the memory allocated by rd_kafka_memberid.

This is an issue if e.g. the host application uses a different allocator than the one used by librdkafka, and so the applications free() doesn't match the malloc() used by rd_strdup().

**Comment by edenhill** [comment]
Sure, will fix.

**Comment by edenhill** [comment]
Fixed on master, see rd_kafka_mem_free()

**Comment by ah-** [comment]
Wonderful, thanks!
