### ISSUE TITLE
KafkaConsumer is consuming only messages from the first topic of the given list

### ISSUE THREAD

**Issue by coberty** [edenhill/librdkafka#463]
Hi,
you can observe this running ```rdkafka_consumer_example``` with arguments ```-X group.id=test test_2 test_3```. ```consume()``` is returning only messages from topic ```test_2```.

Am I doing something wrong or is it a bug?

cob

**Comment by ah-** [comment]
I tried reproducing this, but it works for me:

```
./rdkafka_consumer_example -g test test test2 
% Consumer group rebalanced: assigned:
 test2 [0], test [0]
% Consumer reached end of test2 [0] message queue at offset 0
% Consumer reached end of test [0] message queue at offset 1
% Message (topic test2 [0], offset 0, 5 bytes):
Message Payload hexdump (5 bytes):
00000000: 74 65 73 74 32                                   test2           
% Consumer reached end of test2 [0] message queue at offset 1
% Message (topic test [0], offset 1, 4 bytes):
Message Payload hexdump (4 bytes):
00000000: 74 65 73 74                                      test            
% Consumer reached end of test [0] message queue at offset 2
```

Do you have a complete example of it not working?

**Comment by edenhill** [comment]
`auto.offset.reset` defaults to `largest` which means that if there was no previous offset stored for this consumer group + topic + partition it will start fetching at the end of the partition.
If there are no active producers there will be no new messages and thus nothing will be consumed.

I also suggest that you use rdkafka_consumer_example_cpp at this point, I think rdkafka_consumer_example might be lagging behind somewhat.

Try this:
`rdkafka_consumer_example_cpp -g test -X topic.auto.offset.reset=smallest test test_2`

Also make sure to use latest master

**Comment by coberty** [comment]
I've pulled recent sources and it's working now.
Sorry for disturbing you...
