### ISSUE TITLE
Error while loading shared libraries: librdkafka.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kaustavha** [edenhill/librdkafka#466]
Was getting aforementioned error attempting to run kafkacat, a tool which depends on this library after compiling both from scratch.
i.e:  
```
root@kostco-kafka:~/kafkacat# kafkacat
kafkacat: error while loading shared libraries: librdkafka.so.1: cannot open shared object file: No such file or directory
root@kostco-kafka:~/kafkacat# ldd kafkacat
	linux-vdso.so.1 =>  (0x00007ffef8197000)
	librdkafka.so.1 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f131eb18000)
	libyajl.so.2 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f131e753000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f131ed36000)
```
Solution from https://github.com/salebab/phpkafka/issues/6#issuecomment-66611059 worked for me:
i.e.:  
```
root@kostco-kafka:~/kafkacat#  LD_LIBRARY_PATH=/usr/local/lib
root@kostco-kafka:~/kafkacat# export LD_LIBRARY_PATH
root@kostco-kafka:~/kafkacat# ldd kafkacat
	linux-vdso.so.1 =>  (0x00007ffc6b460000)
	librdkafka.so.1 => /usr/local/lib/librdkafka.so.1 (0x00007f3a8f0da000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3a8eebc000)
	libyajl.so.2 => /usr/local/lib/libyajl.so.2 (0x00007f3a8ecb2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3a8e8ed000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f3a8e6d4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3a8e4cc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3a8f331000)
```
OS is:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```

Creating this issue in the hopes it may help someone in the future.

**Comment by edenhill** [comment]
Either that or add /usr/local/lib to /etc/ld.so.conf  (and run `ldconfig` afterwards to update)

**Comment by FreCap** [comment]
is there a solution that doesn't require sudo access?

**Comment by rolandyoung** [comment]
You do not need sudo to set LD_LIBRARY_PATH. Be aware that, if you built librdkafka and kafkacat from scratch without root access, you must have installed the libraries somewhere outside of /usr/local/lib, so the example above will need adapting to your case.
If you have not built librdkafka and kafkacat from scratch, this issue does not apply to you: in that case, you should ask a new question in the Discussions section.
