### ISSUE TITLE
producing too fast, turn out overflow

### ISSUE THREAD

**Issue by bournex** [edenhill/librdkafka#471]
we are sending messages very fast, like 100 per second....the memory grows quite fast, and soon grows to 2.8GB,,,,,finally turns out Segmentfault..

we tried to slow down to 10 per/s,,, the memory will not explode...

so i think, if there's no memory for new messages, maybe produce should return an error...instead of crash

**Comment by edenhill** [comment]
You can limit the number of messages librdkafka will queue internally for sending with `queue.buffering.max.messages`
