### ISSUE TITLE
How to prevent from commiting on consumer->close()?

### ISSUE THREAD

**Issue by coberty** [edenhill/librdkafka#472]
I use this setting for ```rdkafka_consumer_example_cpp```:

```tconf->set("auto.offset.reset", "smallest", errstr);```
```tconf->set("auto.commit.enable", "false", errstr);```
```tconf->set("offset.store.method", "broker", errstr);```
```conf->set("default_topic_conf", tconf, errstr);```

So, as you can see auto commit is set to false but it's committing on ```consumer->close()``` anyway.
Is this expected behavior? I'd like to commit only manualy.

**Comment by edenhill** [comment]
That's a bug, thanks for reporting it.
Will investigate

**Comment by edenhill** [comment]
When using the High-Level consumer you should use the global `enable.auto.commit` setting instead of the topic `auto.commit.enable` (yes, the naming inconsistency sucks but librdkafka tries to use the same names as the Java upstream client..)

**Comment by coberty** [comment]
It works as you said. Thanks.

**Comment by edenhill** [comment]
:+1:
