### ISSUE TITLE
ssl.certificate.location (documentation)

### ISSUE THREAD

**Issue by ozac** [edenhill/librdkafka#473]
Documentation for **ssl.certificate.location** says: "Path to certificate file for verifying the broker's key."
Actually, it is used for client authentication, pointing to client's public key file.
Maybe change it to:  "Path to client's public key (PEM) used for authentication."

I didn't set this property at the beginning. It took me some time to troubleshoot why authentication was not working :-)

**Comment by edenhill** [comment]
Thanks, fixed!

Did you see SSL tutorial here
https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

or were you able to figure it out yourself?

**Comment by ozac** [comment]
Thanks for the quick fix and for the SSL tutorial.
I was looking at the properties table in CONFIGURATION.md.

**Comment by pabloaguerre** [comment]
Can it be a .crt file or it must always be a PEM file for Clients?
