### ISSUE TITLE
Confusion on message delivery error "Local: Message timed out"

### ISSUE THREAD

**Issue by microwish** [edenhill/librdkafka#474]
I got some errors by rd_kafka_conf_set_dr_msg_cb() saying "Local: Message timed out".

The Kafka messages were originally born at 11:23:52, and I tried to produce them at 11:23:53 by rd_kafka_produce(), and I got the errors at 11:26:02.

I set message.timeout.ms=360000, i.e. 6 minutes.

So my question is that why I got errors reported by dr_msg_cb in much less than 6 minutes (actually less than 3 minutes).

What's more, I got around 20,000 errors reported by dr_msg_cb while only 3 errors reported by err_cb. All are producing related.
Do errors reported by dr_msg_cb indicate final failure? I.e. messages related with those errors wouldn't be retried any more, right?

Thanks.

**Comment by edenhill** [comment]
The premature message timeouts are weird, do you have any idea how to reproduce this?

dr_msg_cb is called once for each message either when the message has been succesfully produced or on final error (after retries) trying to produce (such as time out).

The err_cb are for more general and global errors in librdkafka and is not per-message.

**Comment by microwish** [comment]
More symptom:

1) this error (reported by dr_msg_cb) lasted around a minute, and then everything went well
2) this error occured after the producers had run 10 minutes or so (not all producers encountered this error)
3) sometimes Kafka brokers had corresponding network error saying "reset by peer", but no logs showed the producer stopped or shutdown connection (I've logged as much as possible for the behavior of producer)

**Comment by microwish** [comment]
Hi Magnus,
Do you have any idea on this issue?
Thanks.

**Comment by microwish** [comment]
It seems that I am unable to solve that only by configuration, I have to do some workaround to try to send timed-out messages, e.g. using an extra queue outside librdkafka.

**Comment by edenhill** [comment]
Are you still seeing these problems?
Are they reproducible? If so, can you reproduce with `debug=topic,broker,protocol,msg,queue` enabled and send me the logs (will be a lot)?

**Comment by microwish** [comment]
Hi Magnus,
I've sent an email titled 'About librdkafka issue 474: Confusion on message delivery error "Local: Message timed out"' and attached related log files.

**Comment by edenhill** [comment]
From reading the log files I conclude that after the initial connection is set up to broker 192.168.145.209:9092 it fails to reply to any of the client's ProduceRequests.
When these requests remain unanswered for `message.timeout.ms` (which you have configured to 360 seconds) the requests will fail locally and be retried.

For each timed out message set the rkb_req_timeouts counter is increased and when that counter reaches `socket.max.fails` (defaults to 3) the broker connection is torn down (and re-established) and the timed out messages are failed permanently with ERR__MSG_TIMED_OUT.

So that is **what** is happening, now the question is **why** it is happening?
Why is the broker failing to respond to ProduceRequests for more than 360 seconds?
Is it always the same broker failing?
Is there something in the broker logs?

**Comment by microwish** [comment]
Related brokers (a cluster of 10 brokers) are random.
Take the broker 145.209 as an example.

In app.log, the producer (on 152.121) related error (i.e. Local messages timed out) first occurred at 15:39:00 and at almost the same time, broker (145.209) log (server.log) showed the following:

[2016-01-02 15:38:01,964] ERROR Closing socket for /192.168.152.121 because of error (kafka.network.Processor)
java.io.IOException: Connection reset by peer 
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:218)
        at sun.nio.ch.IOUtil.read(IOUtil.java:191)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:359)
        at kafka.utils.Utils$.read(Utils.scala:380)
        at kafka.network.BoundedByteBufferReceive.readFrom(BoundedByteBufferReceive.scala:54)
        at kafka.network.Processor.read(SocketServer.scala:444)
        at kafka.network.Processor.run(SocketServer.scala:340)
        at java.lang.Thread.run(Thread.java:722)

What's weird is that no producer logs (including app.log and stdout_stderr.log) showed anything on shutting down connection proactively.

**Comment by microwish** [comment]
What's more, this kind of errors usually occurs only once in a producer's lifetime, occurring 5~10 minutes after a producer started.

**Comment by edenhill** [comment]
That broker exception is most likely from when the producer closes the connection due to the timeouts.


What OS are the producers on?

**Comment by microwish** [comment]
-bash-4.1$ uname -a
Linux dsp152121 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
-bash-4.1$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.4 (Final)
Release:	6.4
Codename:	Final
-bash-4.1$ getconf LONG_BIT
64

**Comment by microwish** [comment]
Might it be caused by too large amount of messages to be produced?

And I am unable to figure out why this kind of error almost occurs only once in a producer's lifetime and  why it always occurs after 5~10 minutes when a producer started.

**Comment by edenhill** [comment]
Can you try reproducing this by only providing one broker on the initial bootstrap broker list?
I'm thinking it might have something to do with the migration of a bootstrap broker to a proper broker.

**Comment by microwish** [comment]
I provided a single broker on the initial bootstrap broker list and then started the producing application about 45 minutes ago. And so far that kind of error hasn't occurred yet.

**Comment by edenhill** [comment]
Interesting!
Can you restart it and let it run for 20 minutes, a couple of times, to verify that this is the most likely cause?

**Comment by microwish** [comment]
Sure, I'm doing it.
Any principle or suggestion on choosing the solo bootstrap broker? Does the selected broker bear more burden than those non-selected?

**Comment by edenhill** [comment]
I think it is simply some kind of race condition where it transitions from a bootstrap to a real broker.
If this turns out to be true we can quite simply disable that transitioning functionality and revert back to how it used to be where it had separate brokers for bootstrap and real brokers.

**Comment by microwish** [comment]
After I provided only one broker on the initial bootstrap broker list, this error never occurred again.
So I think we can try disabling that transitioning functionality and reverting back to where brokers for bootstrap and real brokers separated.
Is that okay?

**Comment by microwish** [comment]
Hi Magnu,
Hope you had a great holiday.
Do you have any plan to disable the transitioning functionality and revert back to where brokers for bootstrap and real brokers are separated?
Thanks.

**Comment by edenhill** [comment]
I managed to reproduce this and a fix is on the way.

**Comment by edenhill** [comment]
Please verify on your end as well.

**Comment by microwish** [comment]
So I can provide a list of many bootstrap brokers now, can't I?

**Comment by edenhill** [comment]
Yep!
Den 15 jan 2016 08:13 skrev "microwish" <notifications@github.com>:
