### ISSUE TITLE
Java client can't decode null group metadata

### ISSUE THREAD

**Issue by DavidLiuXh** [edenhill/librdkafka#479]
1. Use rdkafka_consumer_example to consume a topic, 
<pre><code> ./examples/rdkafka_consumer_example -b localhost:9192,localhost:9193,localhost:9194 -g rd_kafka_12 -X partition.assignment.strategy=roundrobin -A t_p_6:0 t_p
_6:1 t_p_6:2 </code></pre>

2. I got an exception when use kafka-consumer-groups.sh in the kafka/bin folder
    Exception: *Error while executing consumer group command Error reading field 'user_data': java.lang.IllegalArgumentException*
<pre><code>./kafka-consumer-groups.sh --new-consumer --bootstrap-server localhost:9192,localhost:9193,localhost:9194 --describe --group rd_kafka_12</code></pre>

3. I try to replace "size = RD_KAFKAP_BYTES_LEN_NULL" whit "size = 0"  in the rd_kafka_buf_write_bytes function in the rdkafka_buf.h file to solve this problem， But 
I'm not sure this is a good way. Please help me. Thanks.

**Comment by edenhill** [comment]
I remember something about the Java client not being able to properly decode NULL Bytes (-1), I thought that was fixed but maybe it wasn't. If so this is an upstream bug, but I'll try to verify that first.

**Comment by DavidLiuXh** [comment]
Thanks for @edenhill. 
I want to know why  use  NULL Bytes encode.

**Comment by DavidLiuXh** [comment]
I found bug from https://issues.apache.org/jira/browse/KAFKA-2695

**Comment by edenhill** [comment]
This is supposedly fixed in upstream Kafka now :+1:
