### ISSUE TITLE
Hang on shutdown on Windows

### ISSUE THREAD

**Issue by snardone** [edenhill/librdkafka#485]
We are experimenting with this library on Windows (64 bit build) and are running into what might be a race condition on shut down. This is against master pulled earlier today.

Our test program has two threads, a producer and a consumer, and the main thread waiting for them to finish. Each of thread calls rd_kafka_destroy() when finished, passing in the value returned from their call to rk_kafka_new().

About half the time the application shuts down cleanly. The other half it just hangs. The last call to rd_kafka_destroy is waiting for the thread with rd_kafka_broker_consumer_serve() loop to exit (calls to rd_kafka_broker_terminating() in that loop do not return true because rkb->rkb_refcnt > 0).

This doesn't seem to happen on Linux. Any thoughts on this?

**Comment by edenhill** [comment]
I've seen the occassional shut down deadlock too on Linux and I'm working to sort it out.
It seems there is an op enqueued on some queue that keeps the broker refcount from decreasing to the termination level.

**Comment by edenhill** [comment]
Should be fixed now, please verify on your end as well. Thanks

**Comment by snardone** [comment]
Thanks, that's great news! We have some unit tests that recreate the
problem, I'll test this week and let you know.
