### ISSUE TITLE
Need visual studio 2008 project of librdkafka

### ISSUE THREAD

**Issue by tommylei** [edenhill/librdkafka#486]
Hi Edenhill,could you please support Visual studio 2008 project for building?I tried to add all .h and .c files to an 2008 project for building,but lots of errors occured.Thank you very much!

**Comment by edenhill** [comment]
Hi,

native Windows support was just added to librdkafka using recent versions of Visual Studio (2013).
It is unfortunately rather unlikely that a backport to older IDE versions, such as VS 2008, will be done any time soon.

But I'd be happy to accept a pull request for it.

**Comment by tommylei** [comment]
Hi Edenhill,just a comment,there are some .h file not supported by vs2008,such as <inttypes.h>,so maybe there are some code change work.
Thank you!I'm waiting for your great work!!!

**Comment by ozac** [comment]
tommylei,

Try this workaround:
1. Download header files from https://code.google.com/p/msinttypes/downloads/list
2. Use `#include <stdint.h>`
3. In rdkafka.h comment out `#include <inttypes.h>`

**Comment by edenhill** [comment]
Thanks @ozac
