### ISSUE TITLE
about customized tinycthread

### ISSUE THREAD

**Issue by gnr163** [edenhill/librdkafka#487]
Hi,when I want to include tinycthread.h in my own cpp-project ,I find is not work yet.
Is this right at the end of tinycthread.h ?

#endif
#ifdef __cplusplus
}
#endif
ifdef __cplusplus
}
#endif

Thanks!

**Comment by edenhill** [comment]
I only use tinycthread from the C part of my library (the C++ librdkafka library is a thin wrapper on top of the C librdkafka library), so I have no experience in getting tinycthread to compile on C++.

Have a look at the upstream and see if they've fixed anything for this:
https://github.com/tinycthread/tinycthread
