### ISSUE TITLE
Large message fails the following messages as well?

### ISSUE THREAD

**Issue by ozac** [edenhill/librdkafka#488]
I'm testing a scenario where a message too large is sent:

I configured Kafka broker with a maximum message size of 2,000 bytes (`message.max.bytes=2000`).
I produce a message larger than 2,000 bytes, immediately followed by smaller messages.
Results: **all** messages failed with error **"Broker: Message size too large"**.

I then added a delay between message producing.
This worked fine: the too large message failed, other messages succeeded.

Is this the expected behavior? 

Thanks

**Comment by edenhill** [comment]
Messages are batched together in the producer before being sent to the broker, so in this case the batch probably contains first the large message and then the small. But the entire batch is too big for the broker so it throws them both away and thus both messages fail.

Adding a delay will put the messages in two different batches. (`queue.buffering.max.ms`)

**Comment by ozac** [comment]
So the options are to use delay (bad performance) or have short messages to fail because of previous long message?

What if I use 'message.max.bytes' on librdkafka client - will this fail only the long message or the entire batch?

**Comment by edenhill** [comment]
It is highly recommended to sync `message.max.bytes` across producers, consumers and brokers.

If you try to produce a message larger than `message.max.bytes` the produce() call will fail immediately for just that message, see here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1803
