### ISSUE TITLE
Getting errno from DLL

### ISSUE THREAD

**Issue by ozac** [edenhill/librdkafka#489]
I'm building librdkafka as a DLL that contains static version of the run-time library (/MT).
The problem is that calling application can no longer get errno, since it's different run-time.

Is it possible to add new function to expose errno?
e.g. 
   `int rd_errno() { return errno; }`

Thanks.

**Comment by edenhill** [comment]
Okay, that makes sense.

It was a mistake to use errnos in the  API at all and all the new APIs have proper rd_kafka_resp_err_t return codes, but the legacy APIs still need to be supported ..
