### ISSUE TITLE
Consumer cann't receive message from kafka if set offset

### ISSUE THREAD

**Issue by tommylei** [edenhill/librdkafka#491]
hi ,i built by vs2013,and use rdkafka_example.exe to test,but sometimes can not receive message,the command is "rdkafka_example -C -t test -p 0 -o 18 -b 172.16.131.21:9192",the command windows show:
D:\!S2文档\!GII\开发工具\librdkafka-master\win32\Release>rdkafka_example -C -t test -p 0 -o 18 -b 172.16.131.21:9192
% Created consumer rdkafka#consumer-0

**Comment by gnr163** [comment]
英语比较捉急，所以就用中文回答下...如果18这个offset点在kafka上已经没有数据了(被kafka定期清理了)，是不会被消费的。 你可以试下earliest time 消费的第一条的offset是不是大于18来check一下。thanks！

**Comment by tommylei** [comment]
Feedback to gnr163:I confirmed again,offset 18 exist in test topic.Is there any log files can anaylize?

**Comment by edenhill** [comment]
@gnr163 Please use english on github issues to let all users take part of the discussion. Thanks

**Comment by edenhill** [comment]
@tommylei Enable debugging by providing the `-d topic,fetch` command line option
