### ISSUE TITLE
run ./rdkafka_example_cpp use stored was "Failed to create consumer" on librdkafka 0.9

### ISSUE THREAD

**Issue by coolulu** [edenhill/librdkafka#496]
hi Edenhill,
I run "./rdkafka_example -C -t TEST -b 192.168.18.76:9092 -p 0 -o stored"  on librdkafka 0.8 was good running.
but run same command line on librdkafka 0.9, print
[lilu@localhost examples]$ ./rdkafka_example -C -t TEST -b 192.168.18.76:9092 -p 0 -o stored
% Failed to start consuming: Local: Invalid argument or configuration

**Comment by edenhill** [comment]
The broker based offset storage now requires a group.id to be configured, e.g. add ` -X group.id=foo`
