### ISSUE TITLE
Broken build on RHEL/CentOS 5

### ISSUE THREAD

**Issue by remicollet** [edenhill/librdkafka#505]
Mostly for information, or if you have spare time to spend on this.

EL-5 is ~9 years old and will be EOL on 31 March, 2017 (soon)

Compile:

    snappy.c: In function 'emit_copy_less_than64':
    snappy.c:652: warning: implicit declaration of function 'htole16'
    snappy.c: In function 'decompress_all_tags':
    snappy.c:1208: warning: implicit declaration of function 'le32toh'

And of course, link:

     /builddir/build/BUILD/librdkafka-0c15023708302c41a36e95f9650d69c453dfabba/src/snappy.c:1234: undefined reference to `le32toh'
     /builddir/build/BUILD/librdkafka-0c15023708302c41a36e95f9650d69c453dfabba/src/snappy.c:652: undefined reference to `htole16'

**Comment by edenhill** [comment]
Fixed now (verified on CentOS 5.11)

**Comment by remicollet** [comment]
I confirm, fix ok.

Built on Fedora 20-23 and RHEL 5-7 (i686, x86_64).

Thanks.
