### ISSUE TITLE
Can I retrieve messages from the internal producer queue?

### ISSUE THREAD

**Issue by 72mailbu** [edenhill/librdkafka#508]
There are times when my Kafka producer process must be restarted, for example to apply recent configuration changes that have been made. During shutdown I'd like to grab what is in the internal queue and save the messages off somewhere, on disk for example, then load them back in immediately after the restart and produce them before producing any new events.

If its not possible, I may need to keep the queue size very small, but this seems counter to the librdkafka design, and it still won't prevent a few messages from being lost each time a restart happens. I expect to be restarting the process on average at least once a day.

Thank you for your time.

**Comment by edenhill** [comment]
That makes sense.
Out of curiousity, how will you store these messages while restarting the app?

So if you decide to shut down your application and there are messages in-flight to the broker waiting to be acked, what do you want to happen with them?
 * wait for ack from broker, may take up to `socket.timeout.ms`
 * consider the in-flight messages as non-delivered and return them to the app (may cause duplicates)
 * consider the in-flight messages delivered and dont return them to the app (may cause message loss)

**Comment by 72mailbu** [comment]
I like Option 2 the best because duplicates are not a problem and they are preferable to message loss.

I'm hesitant to wait for ACKs on account of delaying the restart. I suppose I could lower the default 60 second socket timeout to something like 5 seconds but offhand that doesn't seem like a good idea.

I'm thinking of storing the messages either on the filesystem (/tmp) or in a local memcached (which is already installed on the server for other purposes). I may tweak the queue size downwards, it really depends on how long it takes to flush the messages. I'm looking for the best balance between a short lasting message flush operation and a large enough queue that gives at least a few minutes of buffer.

**Comment by edenhill** [comment]
Okay, what interface would you favor:
 * "fail" all messages in the queue through the standard delivery report callback, with a special error code (RD_KAFKA_RESP_ERR__PERSIST or similar).
 * retrieve the full list of messages in an `rd_kafka_message_t *` array?

**Comment by 72mailbu** [comment]
Offhand I think I like getting the full list of messages in the array, .e.g. kafka_producer->queue(). But what do you think is best?

**Comment by edenhill** [comment]
I dont have a preference at this point, the latter is probably cleaner.

Would it be okay if the function required you to specify topic?
E.g.,
flush_queue(topic_handle, &rkmessage_array, &rkmessage_array_size);

**Comment by 72mailbu** [comment]
Yes that's fine since I create the handle to the topic. Am I correct in assuming that I can pass in the size of the array using the results from outq_len()?

**Comment by edenhill** [comment]
Either that or librdkafka allocates the array for you

**Comment by 72mailbu** [comment]
OK I like that. Thanks much!

**Comment by edenhill** [comment]
Join with duplicate #426
