### ISSUE TITLE
Consumer segfault @ rd_kafka_broker_metadata_req_op

### ISSUE THREAD

**Issue by microwish** [edenhill/librdkafka#518]
Simple debug information is following:

Program terminated with signal 11, Segmentation fault.
#0  rd_kafka_broker_metadata_req_op (rkb=0x0, rko=0x7f10a8378ed0) at rdkafka_broker.c:616
616		rd_rkb_dbg(rkb, METADATA, "METADATA",
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-gssapi-2.1.23-13.el6_3.1.x86_64 cyrus-sasl-lib-2.1.23-13.el6_3.1.x86_64 cyrus-sasl-md5-2.1.23-13.el6_3.1.x86_64 cyrus-sasl-plain-2.1.23-13.el6_3.1.x86_64 db4-4.7.25-17.el6.x86_64 glibc-2.12-1.166.el6_7.3.x86_64 hadoop-2.4.0.2.1.4.0-632.el6.x86_64 keyutils-libs-1.4-4.el6.x86_64 krb5-libs-1.10.3-10.el6.x86_64 libcom_err-1.41.12-14.el6.x86_64 libgcc-4.4.7-3.el6.x86_64 libselinux-2.0.94-5.8.el6.x86_64 libstdc++-4.4.7-3.el6.x86_64 nss-softokn-freebl-3.12.9-11.el6.x86_64 openssl-1.0.1e-42.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  rd_kafka_broker_metadata_req_op (rkb=0x0, rko=0x7f10a8378ed0) at rdkafka_broker.c:616
#1  0x00007f10e51776a7 in rd_kafka_handle_Offset (rkb=0x21b4880, err=<value optimized out>, rkbuf=<value optimized out>, 
    request=0x7f1090005120, rktp=0x7f10a4002810, Offsetp=0x7f10bd7fb1c8) at rdkafka_request.c:174
#2  0x00007f10e517d888 in rd_kafka_toppar_handle_Offset (rkb=0x21b4880, err=<value optimized out>, rkbuf=<value optimized out>, 
    request=<value optimized out>, opaque=<value optimized out>) at rdkafka_request.c:209
#3  0x00007f10e5172661 in rd_kafka_buf_callback (rkb=0x21b4880, err=RD_KAFKA_RESP_ERR_NO_ERROR, response=0x7f10a8378fa0, 
    request=0x7f1090005120) at rdkafka_buf.c:471
#4  0x00007f10e5164c29 in rd_kafka_req_response (rkb=0x21b4880) at rdkafka_broker.c:888
#5  rd_kafka_recv (rkb=0x21b4880) at rdkafka_broker.c:1059
#6  0x00007f10e5170988 in rd_kafka_transport_io_event (rktrans=0x7f10a8378d90, events=1) at rdkafka_transport.c:1007
#7  0x00007f10e5165c94 in rd_kafka_broker_serve (rkb=0x21b4880, timeout_ms=<value optimized out>) at rdkafka_broker.c:2117
#8  0x00007f10e51661cb in rd_kafka_broker_consumer_serve (rkb=0x21b4880) at rdkafka_broker.c:3228
#9  0x00007f10e5168777 in rd_kafka_broker_thread_main (arg=0x21b4880) at rdkafka_broker.c:3336
#10 0x00007f10e518e0ff in _thrd_wrapper_function (aArg=<value optimized out>) at tinycthread.c:596
#11 0x0000003edee07a51 in start_thread () from /lib64/libpthread.so.0
#12 0x0000003ede6e893d in clone () from /lib64/libc.so.6

**Comment by edenhill** [comment]
This should be fixed now, thanks for your report.
