### ISSUE TITLE
lds-gen.py assumes python version

### ISSUE THREAD

**Issue by agboom** [edenhill/librdkafka#520]
My `/usr/bin/python` points to version 3.5, while `lds-gen.py` can only be executed by Python 2 (because of the way `print` is used). This results in de following error:

```
Generating linker script librdkafka.lds from rdkafka.h
  File "../lds-gen.py", line 27
    print '# Automatically generated by lds-gen.py - DO NOT EDIT'
                                                                ^
SyntaxError: Missing parentheses in call to 'print'
Makefile:51: recipe for target 'librdkafka.lds' failed
make[1]: *** [librdkafka.lds] Error 1
make[1]: Leaving directory '/home/adriaan/repositories/librdkafka/src'
Makefile:20: recipe for target 'libs' failed
make: *** [libs] Error 2
```

A solution would be to specify the Python version in the script, but I'm not sure how to do that. `#!/usr/bin/env python2` doesn't work.

**Comment by agboom** [comment]
Changing the following line in `{src|src-cpp}/Makefile` fixes the issue, but I'm not sure if it's a sensible cross-platform solution:

```
cat ../src/rdkafka.h | ../lds-gen.py > $@)
```
to:
```
cat ../src/rdkafka.h | /usr/bin/python2 ../lds-gen.py > $@)
```

**Comment by edenhill** [comment]
Isn't the proper fix just to change `print 'foo'` to `print('foo')`? Seems to work both for 2.7 and 3.4

**Comment by agboom** [comment]
Haven't tried, but that makes sense

**Comment by edenhill** [comment]
Fixed now, please verify on your end.

**Comment by agboom** [comment]
Works like a charm
