### ISSUE TITLE
Default `auto.reset.offset = largest` for consumer is dangerous

### ISSUE THREAD

**Issue by fsaintjacques** [edenhill/librdkafka#521]
We were just bitten by this, where we started consuming at given offset `k` that doesn't exists anymore. I would expect the consumer to fail hard when a requested absolute offset isn't available. This is highly non-intuitive with the UNIX mentality.

**Comment by edenhill** [comment]
Use `auto.offset.reset=error` to raise an error instead.

**Comment by fsaintjacques** [comment]
I am aware, I'm just stating that the default is non-intuitive.

**Comment by edenhill** [comment]
The default is the same as in the official Kafka clients and I think the underlying idea is that it is more important to keep the data stream going than to miss a bunch of messages.
