### ISSUE TITLE
librdkafka does not reconnect to brokers on Windows

### ISSUE THREAD

**Issue by sneves** [edenhill/librdkafka#525]
As the title says, under Windows 8 and above librdkafka does not reconnect to the brokers once a failed connection attempt happens. This is due to [this WSAPoll bug](https://daniel.haxx.se/blog/2012/10/10/wsapoll-is-broken/), which Microsoft shows no intention to fix.

I have been able to work around this by replacing `WSAPoll` with a `select`-based `poll` emulator, but it's certainly not optimal, and I'm not sure whether this subtly breaks something else in the library.

**Comment by edenhill** [comment]
Do you think enabling SO_KEEPALIVE mitigates this issue?
Can you give it a shot by enabling `socket.keepalive.enable=true`?

**Comment by sneves** [comment]
I suppose keepalives prevent disconnections from happening as often, but it doesn't really solve the problem (I just checked with `socket.keepalive.enable=true`). Once you get disconnected for real (say, by a network outrage or something) the connections won't come back up, because `WSAPoll` doesn't get notified of connection failures generated by non-blocking `connect`---only successes---and it just sits there polling forever.

A non-`select` solution that would prevent this would be to set a deadline for connection attempts, instead of expecting `poll` to signal this, and cancel the connection attempt once some amount of time has passed. But this would involve more mastery of librdkafka internals than I have.

**Comment by edenhill** [comment]
Thanks for trying that one.

Just to clarify; the core issue is that poll() will not return any event when the corresponding connection closes, and this is true both for connected sockets and for connecting sockets?

**Comment by sneves** [comment]
No, the scope is smaller than that. Disconnections from connected sockets are detected and properly handled; the only event that is missing is `connect` -> `WSAPoll` in connecting sockets. `WSAPoll` simply returns 0 when the connection attempt fails. The expectation would be that it would return 1 and give out `POLLOUT` or `POLLERR` in the respective event.

**Comment by edenhill** [comment]
Okay, so what do you think about a workaround that retrieves the socket error (SO_ERROR) after each WSApoll() == 0 call when in state==CONNECT?

**Comment by sneves** [comment]
That seems like a good idea, I think that works!

**Comment by edenhill** [comment]
Okay, I'll push a fix that I currently can't verify on win32, can you do it?

**Comment by sneves** [comment]
Yes, I can verify whether it works.

**Comment by sneves** [comment]
FYI, I changed `rd_kafka_transport_poll` to (excluding non-Win32 code):

```
  int r;

  r = WSAPoll(&rktrans->rktrans_pfd, 1, tmout);
  if (r == 0) {
    const rd_kafka_broker_t *rkb = rktrans->rktrans_rkb;
    if (rkb->rkb_state == RD_KAFKA_BROKER_STATE_CONNECT) {
      socklen_t intlen = sizeof(r);
      if (getsockopt(rktrans->rktrans_s, SOL_SOCKET, SO_ERROR, (void *)&r, &intlen) != 0) {
        return -1;
      } else {
        return r != 0 ? POLLERR : 0;
      }
    }
    return 0;
  }
  else if (r == SOCKET_ERROR)
    return -1;
  return rktrans->rktrans_pfd.revents;
```

and it appears to be working, that is, connection failures are now being detected.

**Comment by edenhill** [comment]
There, that fixes it. Can you verify on your end?

Thanks for your effort!

**Comment by sneves** [comment]
Things appear to be working. Thank you very much for the quick fix!

**Comment by edenhill** [comment]
Awesome, thanks!
