### ISSUE TITLE
Async Commit Hit an Error 

### ISSUE THREAD

**Issue by funglee2k** [edenhill/librdkafka#526]
hey, 

When I tried to use the Consumer Async Commit API, I hit an error.  Do you happen to have a sample code to show me how to use the consumer async commit API ? 

The code is pretty same as the one on http://docs.confluent.io/2.0.0/clients/consumer.html#asynchronous-commits 

  if (commit_async) {
           rd_kafka_commit(rk, NULL, 1); //set up callback during initialize. 
  } else {
           rd_kafka_commit_message(rk, rkmessage , 0);
  }
 
I don't have any problem with sync-commit. But when I enable the async commit, I hit the error.

Do I miss any thing here ? 

Thanks.

Yours
Feng 

*** rdkafka_cgrp.c:789:rd_kafka_cgrp_handle_OffsetCommit: assert: rkcg->rkcg_flags & RD_KAFKA_CGRP_F_WAIT_COMMIT ***
rd_kafka_op_cnt: 1
rd_kafka_t 0x18ab2f0: rdkafka#consumer-1
 producer.msg_cnt 0
 rk_rep reply queue: 0 ops
 brokers:
 rd_kafka_broker_t 0x18ab9b0: :0/internal NodeId -1 in state UP (for 20.442s)
  refcnt 2
  outbuf_cnt: 0 waitresp_cnt: 0
  0 messages sent, 0 bytes, 0 errors, 0 timeouts
  0 messages received, 0 bytes, 0 errors
  0 messageset transmissions were retried
  0 toppars:
 rd_kafka_broker_t 0x18ac660: localhost:9092/bootstrap NodeId -1 in state UP (for 20.431s)
  refcnt 2
  outbuf_cnt: 0 waitresp_cnt: 0
  3 messages sent, 91 bytes, 0 errors, 0 timeouts
  3 messages received, 1509 bytes, 0 errors
  0 messageset transmissions were retried
  0 toppars:
 rd_kafka_broker_t 0x7f1324001f00: lif-ThinkPad-T440:9092/0 NodeId 0 in state UP (for 20.381s)
  refcnt 4
  outbuf_cnt: 0 waitresp_cnt: 0
  194 messages sent, 13345 bytes, 0 errors, 0 timeouts
  194 messages received, 9323 bytes, 0 errors
  0 messageset transmissions were retried
  1 toppars:
   mytopic1 [0] leader lif-ThinkPad-T440:9092/0
    refcnt 5
    msgq:      0 messages
    xmit_msgq: 0 messages
    total:     0 messages, 0 bytes
 cgrp:
  lif-test in state up, flags 0x10
   coord_id 0, managing broker lif-ThinkPad-T440:9092/0
  toppars:
   mytopic1 [0] in state active
 topics:
  mytopic1 with 1 partitions, state exists, refcnt 2
   mytopic1 [-1] leader none
    refcnt 1
    msgq:      0 messages
    xmit_msgq: 0 messages
    total:     0 messages, 0 bytes
   desired partitions:
Aborted

**Comment by edenhill** [comment]
Did you set `enable.auto.commit=false` in the consumer config? It defaults to true and should not be used in conjunction with the manual commits.

**Comment by funglee2k** [comment]
Hey Thanks.

I did set "enable.auto.commit" as false.

I attached my changes (patch and raw file) with this email. It was based on
rdkafka_consumer_example.c

Thanks.

Yours
Feng LI

**Comment by edenhill** [comment]
@funglee2k I dont see an attachment, not sure you can do that with issues. Maybe create a gist at gist.github.com and link to?

**Comment by funglee2k** [comment]
Oops.

Could you see the patch
https://gist.github.com/funglee2k/9037d43328aaf87cfe7f

Thanks Magnus.

**Comment by edenhill** [comment]
Are you using the latest master?

**Comment by edenhill** [comment]
Fixed on latest master, please verify.

**Comment by funglee2k** [comment]
Thanks. edenhill :) It works now. :+1:
