### ISSUE TITLE
How to get minimum and maximum offsets of a topic?

### ISSUE THREAD

**Issue by harishmk** [edenhill/librdkafka#530]
I would need to get the lowest and largest offset available on a topic. How do I go about doing this? Python library has `get_partition_offsets` API. Is there something similar in cpp library?

**Comment by edenhill** [comment]
This is continously updated by the consumer and available through the statistics callback (stats_cb or EVENT_STATS) as `lo_offset` and `hi_offset` (per partition).

**Comment by harishmk** [comment]
I am trying to to port a python app to c++.
this app queries the low and high offsets of a topic on startup and does a binary search based on these offsets:
```
while lo < hi:
   mid = (lo+hi)/2
    read msg at msg
    if msg.time > input_time:
        lo = mid
    else
        hi = mid
```

basically the stream contains messages sorted by time(application provided). so we can search for any point in time and then play back from there.

my issues:
1. How to get lo and hi offsets? waiting for stats_cb does not look like a good idea.
2. KafkaConsumer, how to set the offsets of a topic? With Consumer I an use start(...)
3. Consumer, does not have a close method?
4. delete on Consumer hangs.

**Comment by edenhill** [comment]
Thanks for clarifying your use-case:
 1. I agree, waiting for stats is not an optimal solution. A proper get_offset API is needed, there is an existing issue to track that, see issue #503 
 2. I'm a bit hesitant on which interface is best for what sounds like a highly seek-intensive use, let me get back to you on that.
 3. The legacy Consumer does not have a close method, you should call stop() instead.
 4. Consumer or KafkaConsumer?

**Comment by harishmk** [comment]
4 . Legacy `Consumer`. Delete hangs if done right after `RdKafka::Consumer::create`. But If I put a `start` and `stop` in between, there is no issue.

**Comment by edenhill** [comment]
Added a test case for nr 4 but couldn't reproduce, maybe the bug has been fixed or the test case is bad, can you have a look here FIXME-WAIT-PUSH to verify?

**Comment by edenhill** [comment]
This is now in master, rd_kafka_get_offsets() / RdKafka::get_offsets()
Please take it for a spin.

**Comment by ah-** [comment]
Works nicely, thanks!
