### ISSUE TITLE
How to build on Windows with php_rdkafka

### ISSUE THREAD

**Issue by vchampion** [edenhill/librdkafka#531]
I need compile librdkafka together with php_rdkafka php extension. It can be obviously that sources of librdkafka should be placed near sources of php_rdkafka extension and all should work, but it's not.. 

When I try nmake in console appears message that it's needed librdkafka/rdkafka.h, when I downloaded it and placed in the folder with php-rdkafka extension in console appears error that reached 100 count of errors compilation stopped.. (fatal error c1003)

How I can build it together? I found that in librdkafka exists Visual Studio project.. Should I use it somehow?

**Comment by edenhill** [comment]
librdkafka builds on both Cygwin and with Visual Studio (preferred), but I dont know about the php-rdkafka bindings, you'll need to ask @EVODelavega about that.

**Comment by EVODelavega** [comment]
@vchampion The sources needn't be anywhere near the sources of the PHP extension. The PHP extension uses librdkafka as a shared library, just make sure your paths are set up correctly (running `sudo make install` should be enough on most systems)

**Comment by vchampion** [comment]
@EVODelavega thank you for response, but in Windows while compiling php extension it's required librdkafka sources, because in windows, libraries is dll and kafka php extension doesn't linked with that dll.
