### ISSUE TITLE
improvement for returned metadata structure

### ISSUE THREAD

**Issue by DEvil0000** [edenhill/librdkafka#532]
Talking about the C++ API.
At the moment the metadata is structured in vectors (as it is in the plain protocol) like:
`typedef std::vector<const TopicMetadata*> TopicMetadataVector;`
`typedef std::vector<const PartitionMetadata*> PartitionMetadataVector;`
This makes it annoying to access.
Every time you have to find the correct element and in topics and then in partitions vector. This means looping over all elements with O(n). And you get some more code for it then you really need.

I think in the most cases you know what data you are interested in (you know the KEY). e.g. topic_name, partition_id or broker_id.
I mean the data should be structured in maps. This way the access would be O(log n) and the usability in the application code is much better.

`map<topic_name, TopicInfo>`
`inside TopicInfo: map<partition_ID, PartitionInfo>`

This also applies for broker metadata.

**Comment by edenhill** [comment]
I hear what you are saying but there is no one format that fits everyone, so instead of providing yet another format in librdkafka I will leave this up to the applications to mange for the time being.
If the community can agree on what they need I'll be happy to accept a PR
