### ISSUE TITLE
Consumer does not connect back after broker restart or broker down during init

### ISSUE THREAD

**Issue by mylarchetan** [edenhill/librdkafka#536]
I am working on a setup with single broker to test out my application.
When I try with the test program rdkafka_consumer_example I am facing problem with 2 scenarios:
Scenario 1:
a. All brokers down.
b. Start consumer.
c. Start kafka broker.
d. Start a producer and publish messages.
e. rdkafka consumer is not able to establish connection and get messages without any errors seen on console.

Scenario 2:
a. Start kafka broker, Start producer, Start rdkafka consumer.
b. Publish message and is received in rdkafka consumer.
c. Restart kafka broker.
d. Publish message.
e. rdkafka consumer fails to get the message.

Please let me know if I am missing anything here. I am testing this on Win10 with VS2013.

**Comment by edenhill** [comment]
Are you using the latest master?
A bug was fixed last week that caused failing connections to never re-establish:
https://github.com/edenhill/librdkafka/issues/525

**Comment by mylarchetan** [comment]
Not the latest one. Let me try with the latest master and revert.
Thanks.

**Comment by mylarchetan** [comment]
It works with the latest master. The event cb is being invoked on kafka broker down or restart case.
Thanks a lot.

**Comment by edenhill** [comment]
:+1:

**Comment by mylarchetan** [comment]
What will be your suggestion to handle the kafka down/restart situation? I mean when the event call back is invoked should the client application monitor/poll the availability of kafka broker and then recreate the consumer object? or do we have a better approach or solution within rdkafka lib?

**Comment by edenhill** [comment]
librdkafka will automatically reconnect as soon as the broker comes back so an application typically shouldn't do anything when the broker goes down.

**Comment by mylarchetan** [comment]
Ok. Thanks for the confirmation. I will work on my application accordingly.

**Comment by Parthi-J** [comment]
It's connecting only to the last leader broker. If I scale up the other broker consumer not connecting
