### ISSUE TITLE
`rd_kafka_subscribe` with offset

### ISSUE THREAD

**Issue by barock19** [edenhill/librdkafka#537]
Is it possible to set specific offset to use this `balanced consumer group` ?

**Comment by edenhill** [comment]
subscribe() only takes a list of topics, not partitions, and offsets is a partition property so what you are asking is not possible.
You may provide a starting offset in rd_kafka_assign(), to use it in conjunction with the high-level consumer you register a rebalance_cb.
See examples/rdkafka_consumer_example.c for an example.

**Comment by barock19** [comment]
@edenhill woww .. now it's works like a charm, thanks man.

**Comment by edenhill** [comment]
Great!
