### ISSUE TITLE
Multiple consumers in the same process

### ISSUE THREAD

**Issue by harishmk** [edenhill/librdkafka#540]
Inside a process I am creating two consumers , they both connect to the same broker but uses separate topics. This does not work correctly if I read from the two consumers at the same time.

Are there any shared resources or singletons here?

**Comment by edenhill** [comment]
Client instances are completely separated so they should not interfere.
What consumer are you using, legacy or high-level KafkaConsumer?
If the latter; are you sure both of them are not in the same group?

**Comment by harishmk** [comment]
false alarm, issue was with the code.
