### ISSUE TITLE
question on rdkafka_consumer_example 

### ISSUE THREAD

**Issue by funglee2k** [edenhill/librdkafka#542]
Hey, 

I am kind of new to Kafka world.  When I play with rdkafka_consumer_example, I had unexpected group consumer behavior.  

Basically, I changed nothing. I have started two rdkafka_consumer_example instances with same parameters but in different terminals.  

rdkafka_consumer_example -g lif-test -b localhost:9092 mytopic2:0

I expected only one instance would receive the changes b/c they are in the same consumer group. However, I noticed both of them received the new message. 

If I start the sample program with the following parameters: (do not specify the partition), everything looks good to me: only one of the instances have the new message. 

rdkafka_consumer_example -g lif-test -b localhost:9092 mytopic2 

is that expected behavior ?  

I am running the test code from master branch, and I believe I have the latest changes.

**Comment by edenhill** [comment]
Hi, 

When specifying the partition it actually sets a static partition assignment and circumvents the high level balanced consumer group functionality. 
It was added as a feature to the example program to show case both the high level and simple consumer with the same program.

**Comment by funglee2k** [comment]
Thanks for clarifying this. Edenhill.

Two small problems with rdkafka_consumer_example.cpp (CPP) 
1) the program does not take "-X list" as command line parameter, which is different from the help page.   (it actually takes -X dump).
  -X <prop=name>  Set arbitrary librdkafka configuration property
                  Properties prefixed with "topic." will be set on topic object.
                  Use '-X list' to see the full list
                  of supported properties.

2) Is there any sample code for KafkaConsumer::Position() ? I could not get the CPP version of API working.  

Thanks.

**Comment by edenhill** [comment]
....:

 1. To retrieve the list of available config options either look at CONFIGURATION.md or use `rdkafka_example -X list`. Standard `-X [topic.]property=value` should work though.
 2. There is currently no sample code for position(), how are you calling it and what do you get back?
   Remember that you need to configure the KafkaConsumer handle with the appropriate group that you wish to query the stored offsets (positions) for, and you need to specify both topic and partition in the std::vector.

**Comment by funglee2k** [comment]
Hey, edenhill,

https://gist.github.com/funglee2k/a163b834c828b7aab04e 
here is my sample code I used. I just added a new cmdline parameter as -O 

If you have time, please help me review it. (I had some code to try the asyncommit in that file too).

Thanks .

**Comment by edenhill** [comment]
It looks good, what is the result you are getting from ::position() ?

**Comment by funglee2k** [comment]
I run the program with -d ALL option.  Based on the file, OFFSETOffsetFetchRequest: skipping it.  

I updated the https://gist.github.com/funglee2k/a163b834c828b7aab04e and added the logs.

Thanks.
Yours
Feng LI 

2016-02-15 16:31:13.018: LOG-7-CGRPOP: Group "lif-test" received op OFFSET_FETCH in state up (join state init)

**2016-02-15 16:31:13.018: LOG-7-OFFSETOffsetFetchRequest: skipping %s [%d] with valid offset %s: lif-ThinkPad-T440:9092/0: mytopic1
**
2016-02-15 16:31:13.019: LOG-7-OFFSET: lif-ThinkPad-T440:9092/0: OffsetFetchRequest(v1) for 0/1 partition(s)
DEBUG: try to fetch offsets for 2016-02-15 16:31:13.019: LOG-7-CGRPQUERY: lif-ThinkPad-T440:9092/0: Group "lif-test": querying for coordinator: intervaled in state up
1 partitions,  KafkaConsumer::position() returns Success
2016-02-15 16:31:13.118: LOG-7-SEND: lif-ThinkPad-T440:9092/0: Sent GroupCoordinatorRequest (v0, 31 bytes, CorrId 2)
2016-02-15 16:31:13.119: LOG-7-CGRPOP: Group "lif-test" received op TERMINATE in state up (join state init)
2016-02-15 16:31:13.119: LOG-7-CGRPTERM: Terminating group "lif-test" in state up with 0 partition(s)

**Comment by edenhill** [comment]
@funglee2k The issue you were seeing with position() should now be fixed, please update to latest master and verify on your end.
Thanks

**Comment by funglee2k** [comment]
thanks. It is fixed.
