### ISSUE TITLE
New consumer how to get stat info when stop call rd_kafka_consumer_poll function 

### ISSUE THREAD

**Issue by nmred** [edenhill/librdkafka#549]
I use v0.8.x api can call `rd_kafka_poll` get stat info, but call new consumer `rd_kafka_consumer_poll` will return message and call stat callback , I want stop consumer data only callback stat func, how to ?

V.0.8.x

```
rkmessage = rd_kafka_consume_queue(_kqueue.get(), _consumeTimeout);
while(!_messageCallback(_topic, rkmessage->partition, rkmessage->offset, std::string(tmp))) {
     // callback stat 
     rd_kafka_poll(_kt.get(), _consumeTimeout);
}
```

V0.9.x New Consumer Api

```
rkmessage = rd_kafka_consumer_poll(_kt.get(), _consumeTimeout);
while(!_messageCallback(_topic, rkmessage->partition, rkmessage->offset, std::string(tmp))) {
    //rd_kafka_poll(_kt.get(), _consumeTimeout);
    // call this function will *** rdkafka_queue.c:388:rd_kafka_q_serve: assert: handled == cnt ***
}
```

**Comment by edenhill** [comment]
The global ops queue that is usually served by rd_kafka_poll() is forwarded to the consumer queue when using the high-level consumer (and calling rd_kafka_poll_set_consumer() explicitly). In this case you are not allowed to call rd_kafka_poll(), only rd_kafka_consumer_poll().
If you dont want messages you can pause the current fetchers by calling rd_kafka_partitions_pause(), after this consumer_poll() should not give you more messages, just callbacks, etc.

**Comment by nmred** [comment]
call rd_kafka_pause_partitions is not pause fetcher and not callback stat function

**Comment by edenhill** [comment]
It doesnt? It should, see https://github.com/edenhill/librdkafka/blob/master/tests/0026-consume_pause.c

**Comment by nmred** [comment]
It works! Thanks
