### ISSUE TITLE
CPP API missing statistic call back ?

### ISSUE THREAD

**Issue by funglee2k** [edenhill/librdkafka#551]
Hey, edenhill,

Is there any way to register statistics call back for CPP API ? If possible I  want to have something similar to  the C API, rd_kafka_conf_set_stats_cb().  or I missed something in CPP API ? 

Thanks.

Yours
Feng LI

**Comment by edenhill** [comment]
Register an EventCb and look for EVENT_STATS:
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L431
