### ISSUE TITLE
win32: regex support

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#552]
Since the bundled trex turned out to be buggy there is currently no builtin regex support on Win32.

Proper fix is probably to depend on pcre (which is available through NuGet)

**Comment by ffbin** [comment]
hi, edenhill.
I am using rdkafka consumer api and now i have a problem that after kafka server Rolled new log segment, my rdkafka consumer can not get message from kafka any more. Can you give me some help? Thank you very much.
My code is like this:
{
    rd_kafka_conf_t       *pstConf;
    rd_kafka_topic_conf_t *pstTopicConf;
    pstTopicConf = rd_kafka_topic_conf_new();
    if (NULL == pstTopicConf)
    {
        return -1;
    }

    pstConf = rd_kafka_conf_new();
    if (NULL == pstConf)
    {
        rd_kafka_topic_conf_destroy(pstTopicConf);
        return -1;
    }

    char acErr[1024];
    rd_kafka_t *pstKHander = rd_kafka_new(RD_KAFKA_CONSUMER, pstConf, acErr, sizeof(acErr));
    if (NULL == pstKHander)
    {
        rd_kafka_topic_conf_destroy(pstTopicConf);
        return -1;
    }

       std::string strBrokers = "127.0.0.1:4001";
    if (0 == rd_kafka_brokers_add(pstKHander, strBrokers.c_str()))
    {
        rd_kafka_topic_conf_destroy(pstTopicConf);
        return -1;
    }

       std::string strTopic = "Test";
    rd_kafka_topic_t *pstKTopic = rd_kafka_topic_new(pstKHander, strTopic.c_str(), pstTopicConf);
    if (SPS_NULL_PTR == pstKTopic)
    {
              return -1;
    }

       if (-1 == rd_kafka_consume_start(pstKTopic, i32Idx, RD_KAFKA_OFFSET_END))
       {
              return -1;
       }
       
       rd_kafka_message_t *astMsgs[1024];
       rd_kafka_message_t *pMsg;
       int i32ConsumeNum;
       char *pcData;
       int i32Len;
       while (1)
       {
              i32ConsumeNum = rd_kafka_consume_batch(pstKTopic, 0,
            500, astMsgs, 1024);
              if (0 == i32ConsumeNum
            && 0 == rd_kafka_topic_partition_available(pstKTopic, 0)
              {
                     continue;
              }
              else if (i32ConsumeNum > 0)
              {
                  for (int i32MsgIdx = 0; i32MsgIdx < i32ConsumeNum; ++i32MsgIdx)
                     {
                            pMsg    = astMsgs[i32MsgIdx];
                            pcData = (char*)pMsg->payload;
                            i32Len  = (int)pMsg->len;

                            if (i32Len != 0)
                            {
                                   //do something
                            }

                            rd_kafka_message_destroy(pMsg);
                     }
              }
       }
}

**Comment by edenhill** [comment]
@ffbin Please create a new issue, this has nothing to do with regex support on windows

**Comment by ffbin** [comment]
@edenhill Thanks.

**Comment by edenhill** [comment]
Or this: https://github.com/ccxvii/minilibs
