### ISSUE TITLE
question of RdKafka::Consumer use group id

### ISSUE THREAD

**Issue by simon-rock** [edenhill/librdkafka#554]
Hi, edenhill
my environment is kafka 0.9.
In my case
1. start a producer
/rdkafka_example_cpp -P -t TEST_B -b 10.21.48.74:9092  -p 0
2. start two consumer with group id
./rdkafka_consumer_example_cpp -g group-0001 -b 10.21.48.74:9092 TEST_A
3. send msgs from producer and only one consumer of them can get the msg. The msgs cann't rebalance in two consumers.
It works as design?
Thanks.

**Comment by edenhill** [comment]
That is exactly what balanced consumer groups are meant to do; make sure a given message reaches exactly one consumer in a group.
If you want every consumer to receive every message you need to put them in different groups

**Comment by simon-rock** [comment]
sorry. I didn't say clearly.
I means there are two consumers A and B.
When I send msgs, only A can get the msg every time and B get nothing.
If I kill the A and B can get msg.
it like this
         P send 10 msgs ,   
         A  get 10 , B get 0
we want that A 5, B 5 or 6:4
we need make some setttings?
thanks.

**Comment by edenhill** [comment]
That is how balanced consumer groups work, only one consumer will consume a partition at any given time. If you need multiple consumers to read the same partition simultaneously you need to put these consumers in different groups (and the point of balanced groups are somewhat mute for this use case).

Read more here:

http://kafka.apache.org/documentation.html#intro_consumers

> This is achieved by assigning the partitions in the topic to the consumers in the consumer group so that each partition is consumed by exactly one consumer in the group. By doing this we ensure that the consumer is the only reader of that partition and consumes the data in order.

**Comment by simon-rock** [comment]
Thanks for reply.
I thinks I find the reason, the topic I created have two partitions.
so consumer A for partitions 0
     consumer B for partitions 1
thanks
