### ISSUE TITLE
configure with "--enable-{sasl,ssl}" should fail when sasl/ssl isn't available

### ISSUE THREAD

**Issue by Whissi** [edenhill/librdkafka#556]
Commit 8d141ef30a18df3d953a052e3fd1b1a47298feb3 and 92ec079c58bff7928ec5e3c4684bb487478a4173 added support for disabling sasl/ssl, however if you have enabled sasl but sasl wasn't found configure doesn't fail.

I expect the same for ssl but haven't verified.

**Comment by edenhill** [comment]
--enable-sasl is the default and it was actually added to avoid installing sasl/ssl by specifying --disable-xxx

But I hear you, it would need to be a tri-state:  defaulty, y, n, and fail if 'y' && notfound.

**Comment by edenhill** [comment]
added trivup issue
