### ISSUE TITLE
Error from producer sync API "Broker: Request timed out"

### ISSUE THREAD

**Issue by ankurjohri** [edenhill/librdkafka#557]
Hi Eden,

There is a producer which uses librdkafka to send messages over a Kafka infrastructure. There is an error which occurred from sync API call. It gives error message "Broker: Request timed out". Can you please provide description of this error message?

Earlier we got another error message "Local: Message timed out" which was there due to unavailability of leader broker and it was understandable.

Please provide details of this error message. There is not much in broker config files. Thanks for your help.

Thanks,
Ankur

**Comment by edenhill** [comment]
Both these error codes indicate a problem with broker connectivity or the broker itself.
librdkafka will attempt to Produce messages for `message.timeout.ms` and `message.send.max.retries`.

If the message timeout is reached then "Local: Message timed out" will be returned, this usually indicates a problem with network connectivity to the broker or there is no leader broker for the given topic+partition.

"Broker: Request timed out" is an error returned by the broker (thus the "Broker: " prefix), you will need to look at the broker logs to see the reason for it.

**Comment by ankurjohri** [comment]
Hi Eden,

Thanks for your response. I don't see any relevant error message in broker debug logs. Is there any specific error message I should look for?
In this case, message.timeout.ms is 200 and message.send.max.retries is 2, so ideally it should attempt for 600 ms for sending a message. But  it was very inconsistent for different message. For one message it was around 127 ms, for another message it was 209 ms, for third message it was 325 ms and so forth. Ideally, it should attempt for 600 ms for each message.
Any information related to the issue would be helpful.

Thanks,
Ankur

**Comment by ankurjohri** [comment]
Hi Eden,

Can you please explain me the difference between the following error codes?
-192: Local: Message timed out
7: Broker: Request timed out
8: Broker: Broker not available
9: Broker: Replica not available

Thanks,
Ankur

**Comment by edenhill** [comment]
librdkafka errors have double underscore prefix (RD_KAFKA_RESP_ERR__TIMED_OUT) and prints with a "Local: " prefix:
 * `-192: Local: Message timed out`: Local timeout inside librdkafka, typically due to broker not being available or too slow.

Errors reported by the brokers have a single underscore prefix (RD_KAFKA_RESP_ERR_BROKER_NOT_AVAILABLE). See here for an explanation of the broker errors:
https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-ErrorCodes

**Comment by edenhill** [comment]
What broker version is this?
Are you sure broker 2 is leader for the partition before bringing down broker 1?
Does the problem occur when you bring broker 1 down or when you bring it back up?

**Comment by ankurjohri** [comment]
The issue was resolved. Actually, the required.acks was set to -1 (all brokers) instead of 1 (only leader broker) by mistake. This was making to wait for acks from all brokers (2 in this case) including ack from broker which was going down. That ack was not coming, so it was timing out. Thanks for your help.
