### ISSUE TITLE
Change in auto-offset-reset behaviour just before/after 0.9.0?

### ISSUE THREAD

**Issue by yungchin** [edenhill/librdkafka#559]
I'm trying to understand a test failure in pykafka when upgrading our dependency from librdkafka 0.8.6 to 0.9.0 - specifically, our tests fail [here][0] - and hoping this might ring a bell here? What the test does is basically this:

1. fetch the latest partition offsets (not using librdkafka for this)
2. set one of the consumer partitions to an offset that is 5 beyond the latest available offset (ie an invalid offset)
3. start a new librdkafka consumer with a new queue, passing it these offsets as starting points, with the invalid offset included, and with `auto.offset.reset="earliest"` in the configuration
4. consume a message, and expect that message to be at the earliest offset for the partition we chose

This test passed fine with 0.8.6, and after jumping around commits I can confirm it passes fine all the way up to 3ff4705d419779180c6f9bfabfacc57cbffc472d - so just before 0.9.0. I can unfortunately not pin down the change to an exact commit, because the next commit (9c5aee8ba4bb7888d64a15c165c5bd5342bf5b9a) fails to build, and the next ~40 commits seem to segfault. The first commit that doesn't is 10f6ea380ddacc82de74198d033dc172d9f9881b - where the test finishes, but no longer passes: instead of returning the earliest message, it just times out.

That is: the change would have been introduced somewhere between 3ff4705d419779180c6f9bfabfacc57cbffc472d and 10f6ea380ddacc82de74198d033dc172d9f9881b. I've also tested current master (915f11c199e8f154277361f7fe7e9cb4a95612c1) and the test still fails there.

[0]: https://github.com/Parsely/pykafka/blob/f35297a8e6c9f75c8694a670046a37264609f7ac/tests/pykafka/test_simpleconsumer.py#L154-L160

**Comment by edenhill** [comment]
Will look into this!

**Comment by edenhill** [comment]
Thanks for reporting this, it should now be fixed on master. Can you verify on your end?

**Comment by yungchin** [comment]
Works like a charm, thanks!
