### ISSUE TITLE
What does 'product failures' mean in the context of rdkafka_performance?

### ISSUE THREAD

**Issue by winbatch** [edenhill/librdkafka#563]
Hey there, long time no speak :)

What does the 32716 produce failures mean in the line below.  Are those actually lost messages or ones that had to be retried?

10512756 messages produced (10765062144 bytes), 9570393 delivered (offset 0, 442363 failed) in 336123ms: 28472 msgs/s and 29.16 Mb/s, 32716 produce failures, 500000 in queue, no compression

from:
./rdkafka_performance   -P -t performance_test -b host -s 1024 -a 1

**Comment by winbatch** [comment]
btw, should this work?
 ./rdkafka_performance   -P -t performance_test -b host -s 1024 -a 1 -X request.timeout.ms=10000
% No such configuration property: "request.timeout.ms"

**Comment by edenhill** [comment]
Hey!

The produce failures are typically due to the producer queue being full and you should see a "backpressure" value somewhere too that represents this. The failed message will be re-produce()d so there is no message loss.

For other errors rdkafka_performance exits immediately.

**Comment by edenhill** [comment]
Topic configuration properties must be prefixed with `topic.` with the example tools, e.g., `topic.request.timeout.ms`
