### ISSUE TITLE
Question of RebalanceCb::rebalance_cb

### ISSUE THREAD

**Issue by coolulu** [edenhill/librdkafka#564]
hi Edenhill, I use consumer group,
Q1. sometimes wait for call RebalanceCb::rebalance_cb get topic+partition with a long time.

Q2.I run two rdkafka_consumer_example_cpp.
program 1 topics is 'AA' and 'BB', 
program 2 topics is 'BB', 'CC', 'DD'. but topic 'DD' can not appearence;
```
program 1
[lilu@localhost examples]$ ./rdkafka_consumer_example_cpp -g GGG -b 192.168.18.76:9092 AA BB
% Created consumer rdkafka#consumer-1
RebalanceCb: Local: Assign partitions: BB[0], AA[0], AA[1], 
RebalanceCb: Local: Revoke partitions: BB[0], AA[0], AA[1], 
RebalanceCb: Local: Assign partitions: BB[0], 

program 2
[lilu@localhost examples]$  ./rdkafka_consumer_example_cpp -g GGG -b 192.168.18.76:9092 BB CC DD
% Created consumer rdkafka#consumer-1
RebalanceCb: Local: Assign partitions: BB[1], CC[1], 
RebalanceCb: Local: Revoke partitions: BB[1], CC[1], 
RebalanceCb: Local: Assign partitions: BB[1], CC[0], CC[1], 
```

**Comment by edenhill** [comment]
Q1: Long waiting times on group rebalancing are usually due to `session.timeout.ms`. Lower that value if you need faster rebalancings.

Q2: I fixed some assignment issues three weeks ago, are you using the latest master? And are you sure there is a DD topic with partitions?

**Comment by edenhill** [comment]
Q2 could be related to issue #553
