### ISSUE TITLE
Running rdkafka_example with sasl gives a bad kinit option on debian

### ISSUE THREAD

**Issue by winbatch** [edenhill/librdkafka#567]
./rdkafka_example -C -t non_encrypt_with_auth -b host:9094 -p 0 -X security.protocol=sasl_plaintext
kinit: invalid option -- 'i'
Usage: kinit [-V] [-l lifetime] [-s start_time]
        [-r renewable_life] [-f | -F] [-p | -P] -n [-a | -A] [-C]
        [-E]
        [-v] [-R] [-k [-t keytab_file]] [-c cachename]
        [-S service_name] [-T ticket_armor_cache]
        [-X <attribute>[=<value>]] [principal]

    options:    -V verbose
        -l lifetime
        -s start time
        -r renewable lifetime
        -f forwardable
        -F not forwardable
        -p proxiable
        -P not proxiable
        -n anonymous
        -a include addresses
        -A do not include addresses
        -v validate
        -R renew
        -C canonicalize
        -E client is enterprise principal name
        -k use keytab
        -t filename of keytab to use
        -c Kerberos 5 cache name
        -S service
        -T armor credential cache
        -X <attribute>[=<value>]
1456435115.957 RDKAFKA-3-SASLREFRESH: rdkafka#consumer-1: SASL key refresh failed: kinit -S "kafka/host" -k -i kafkaclient: exited with code 2
kinit: invalid option -- 'i'

**Comment by winbatch** [comment]
And looks like -X sasl.kerberos.kinit.cmd is only to specify the path to kinit rather than the cmd itself.

**Comment by edenhill** [comment]
Should probably change sasl.kerberos.kinit.cmd to take a token string.

**Comment by edenhill** [comment]
For now you'll need to create a wrapper script or specify the keytab path with sasl.kerberos.keytab=..

**Comment by edenhill** [comment]
The kinit.cmd is now completely formattable
