### ISSUE TITLE
Producer can't send msg when restart kafka broker

### ISSUE THREAD

**Issue by DavidLiuXh** [edenhill/librdkafka#569]
1. Startup kafka 0.9 broker A, B, C; 
2. Startup producer D, it is work;
3. Restart borker A;
4. Failed to produce msg for produce D and the error msg: Local: Unknown topic;
5. Startup producer E and the E is work;
6. The producer D can send msg about 5 minutes later.

Librdkafka log:
<pre><code>
Mon Feb 29 10:35:04 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Receive failed: Disconnected
Mon Feb 29 10:35:04 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Receive failed: Disconnected
Mon Feb 29 10:35:04 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:04 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:05 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:05 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:06 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:06 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:07 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:07 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:08 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:08 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:09 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:09 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:10 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:10 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:11 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:11 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:12 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:12 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:13 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:13 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:14 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:14 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:15 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:15 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:16 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:16 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:17 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:17 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:18 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:18 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:19 2016
 | RD_KAFKA_LOG | level: 3 | fac: FAIL | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
Mon Feb 29 10:35:19 2016
 | RD_KAFKA_LOG | level: 3 | fac: ERROR | msg: 10.139.220.16:9092/0: Connect to ipv4#10.139.220.16:9092 failed: Connection refused
</code></pre>

**Comment by DavidLiuXh** [comment]
@edenhill Please see this issue. Thanks

**Comment by edenhill** [comment]
If you could reproduce this with debug=broker,topic enabled that would be great.

**Comment by oyld** [comment]
[rdkafka.txt](https://github.com/edenhill/librdkafka/files/175266/rdkafka.txt)

**Comment by edenhill** [comment]
Thanks, where is this log from, producer D or E?
At what timestamp does it stop working and at what timestamp does it start working again?

**Comment by DavidLiuXh** [comment]
@edenhill 
I set topic.metadata.refresh.interval.ms=30000 and message.timeout.ms=3000, This D can quickly resume work when the broker A restart.

**Comment by edenhill** [comment]
Is this still an issue with latest master?

**Comment by DavidLiuXh** [comment]
It is work.

**Comment by edenhill** [comment]
great!
