### ISSUE TITLE
snappy is no longer included by default in configure.librdkafka

### ISSUE THREAD

**Issue by TimEvens** [edenhill/librdkafka#570]
Was it intentional in commit eb961035c979e60c55d0b5546dd71f756a48c974 to remove "**mkl\_allvar\_set mkl\_allvar\_set** WITH_SNAPPY WITH_SNAPPY y" from **configure.librdkafka**? 

Previously snappy was included by default, now it's not.  I didn't see this change mentioned in the commit log.

**Comment by rthalley** [comment]
Yeah, this just bit me too.  Looks like an accident!

**Comment by edenhill** [comment]
Ouch, you are right, that is an accident. Will fix.
