### ISSUE TITLE
ENOENT when producing more than queue.buffering.max.messages messages on Windows

### ISSUE THREAD

**Issue by ah-** [edenhill/librdkafka#571]
Hi,

I'm sending a lot of messages, enough to fill the outward buffer up. I'm trying to handle the buffer being full by just backing off for a short while and then retrying.

It seems that on Windows the failing produce call doesn't return EBUSY (QUEUE_FULL) in that situation but ENOENT (UNKNOWN_TOPIC), which is rather surprising and prevents me from handling this situation.

Do you have any idea what might be going on there?

**Comment by edenhill** [comment]
Sounds weird, could this be a problem with errno leakage in .NET?

**Comment by ah-** [comment]
Possibly, although .net has a special attribute to prevent that and I'm reasonably certain I used that. I'll try to build a test case.

**Comment by edenhill** [comment]
Try writing a simple test-case in tests/ that tries producing to an unknown topic, unknown partition and exceeding the queue limit (set it low).

That way the test will be reusable for future regressions.

**Comment by ah-** [comment]
Just had a closer look, the issue is that Windows has both errno and Set/GetLastError, and they're two distinct things. C# only supports reliably reading GetLastError, to get errno I'd have to manually call the c function and it wouldn't be guaranteed that nothing else has changed it since librdkafka set it.
On linux this just wasn't an issue since there's only one errno and the linux .net runtime implements GetLastError by returning errno.

I'm not quite sure how to solve this best. I can see a couple of possible ways, but don't particularly like any of them:
1. Ignore that errno could be overwritten and use it anyways. This will just lead to obscure and hard to debug issues.
2. Change librdkafka to also store its errors with SetLastError. Would work, but there would be two locations for the errors and it'd require updating all current usages of "errno = something" to a "SET_ERROR(something)" macro as SetLastError is a function.
3. Change librdkafka to also store its errors using its own internal errno that won't get changed by any other c lib calls.
4. Change librdkafka to just not use errno. Would break compatibility or require duplication of a bunch of functions, so not really an option.
5. Write my own wrapper implementing 4. Really don't want to do that.

I'm leaning towards solution 2, do you have any better ideas?

**Comment by edenhill** [comment]
I'm thinking we should do something closer to 3) to get rid of needing to use errno without breaking the API contract. Add a:
`   rd_kafka_resp_err_t rd_kafka_last_error(rd_kafka_t *rk)`
that returns the last error code returned by an API in the current thread.

So for produce you would do something like:
`````
  if (rd_kafka_produce(...) == -1) {
     err = rd_kafka_last_error(rk);
     switch (err) {
         case RD_KAFKA_RESP_ERR__QUEUE_FULL:
        ...
     ..
`````

This is quite common in other well known C libraries, maybe for the same reason.

What do you think?

**Comment by ah-** [comment]
Sounds good, I like that it also directly returns the rd_kafka_resp_err_t.

**Comment by edenhill** [comment]
Give it a spin and see if it fixes your problem.

**Comment by ah-** [comment]
Cool, works perfectly!
