### ISSUE TITLE
group.id  for consumer group support at present??

### ISSUE THREAD

**Issue by chenzhanyiczy** [edenhill/librdkafka#573]
i find consumer group still can't work which version is already latest. and kafka-server version is  kafka_2.10-0.9.0.0.tgz.

**Comment by edenhill** [comment]
librdkafka now supports 0.9-based consumer groups with the new rd_kafka_subscribe() (KafkaConsumer::subscribe()) APIs.
See [here](https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_consumer_example.cpp) for an example

**Comment by chenzhanyiczy** [comment]
i try,thanks
