### ISSUE TITLE
if timeout set a long time,will with large memory

### ISSUE THREAD

**Issue by laxpio** [edenhill/librdkafka#574]
i set a long timeout,when the kafka cluster busy,the process will use a large memory.
i find the rkb->rkb_waitresps no limit, could limit rkb->rkb_waitresps to keep the memory not too large?

**Comment by edenhill** [comment]
I'm guessing this is when using the Producer?
If so the  `queue.buffering.max.messages` should be used to control the maximum number of messages enqueued (there is also a yet unmerged PR to limit on bytes rather than messages).

**Comment by laxpio** [comment]
queue.buffering.max.messages just control the message add to toppar,when ack=-1,the message will add to rkb->rkb_waitresps after do send,if response later, we can not control the rkb->rkb_waitresps expand.
it will control do send message when response later?

**Comment by edenhill** [comment]
But you will not have more rkb_waitresps than queue.buffering.max.messages, so there is no need for an additional limit, right?

**Comment by laxpio** [comment]
it means the message buffer size keep less than queue.buffering.max.messages until the message do poll_cb?
and when timeout times > socket_max_fails,the message buffer is free right away?
i find the memory will increase when disconnect kafka(timeout times > socket_max_fails).

**Comment by edenhill** [comment]
If you think there is a memory leak please run your program with valgrind to find it.
Reopen if you find anything in librdkafka. Thanks
