### ISSUE TITLE
Change offset with rd_kafka_consume_start cause reading twice some messages

### ISSUE THREAD

**Issue by dgiordan88** [edenhill/librdkafka#575]
Hello,
For my C project I need to allow the consumer to change the offset and the partition to read from. For this purpose I start a connection with rd_kafka_consume_start to partition 0 and offset 0, then when I know in which  partition and offset I need to read I use rd_kafka_consume_start again to specify the correct information.

However, now I am facing a weird problem. By using the rd_kafka_consume_start to set the correct offset and partition, and then reading the log I read twice the first 100k messages of the 600k existing. 

How may I solve this issue? Is there any other better solution to change the offset and partition? 

Thanks, bye

**Comment by edenhill** [comment]
You need to call rd_kafka_consume_stop() before calling rd_kafka_consume_start() again.
But there is a simpler solution, namely to call rd_kafka_seek() instead that allows you to more quickly update the fetch position.
