### ISSUE TITLE
wild card in topic names

### ISSUE THREAD

**Issue by lathakris** [edenhill/librdkafka#576]
Hi Eden,
Does the C library support wild cards in topic names ? like test.*. Please clarify. I am using version 0.8.

Thanks,

**Comment by edenhill** [comment]
Wildcard topic names are generally not supported by librdkafka, but the new high-level KafkaConsumer supports regex subscriptions (rd_kafka_subscribe() and KafkaConsumer::subscribe())

**Comment by edenhill** [comment]
Beware though that no other Kafka clients supports regex subscriptions so if you plan of using different client implementations in the same consumer group the regexes will not work. As long as all clients in a consumer group are using librdkafka you will be fine though.

**Comment by lathakris** [comment]
Hi Eden,

Thanks for your prompt reply. I think this high-level kafkaConsumer support is present starting from 0.9 and not in 0.8 right ?

Also, I see that the Java client (0.9) does support regex topic names ? We have multiple different clients implementations in the same consumer group - Java, C and Python.

**Comment by edenhill** [comment]
Yeah, high-level KafkaConsumer is a 0.9 thing.

I dont think the Java KafkaConsumer has regex support yet.

**Comment by lathakris** [comment]
this is the Java client link which points to a pattern support in the topic names.

https://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#subscribe(java.util.regex.Pattern,%20org.apache.kafka.clients.consumer.ConsumerRebalanceListener)

**Comment by edenhill** [comment]
Ah, you are right, the approach is a bit different in the two clients:
 * Java: Each member of a group periodically matches its regex list to the available topics and updates its subscription set accordingly.
 * librdkafka: The regexps are forwarded to the single group assignor and it performs the regex matching.

I will discuss with the Java devs which of these two methods are the best and adjust the respective client accordingly.

**Comment by lathakris** [comment]
Thank you Eden.

**Comment by edenhill** [comment]
This issue is now fixed on master, please try to verify the fix in your environment.
Thank you.

**Comment by jeffwidman** [comment]
> Ah, you are right, the approach is a bit different in the two clients:
>
>    Java: Each member of a group periodically matches its regex list to the available topics and updates its subscription set accordingly.
    librdkafka: The regexps are forwarded to the single group assignor and it performs the regex matching.
>
> I will discuss with the Java devs which of these two methods are the best and adjust the respective client accordingly.

I'm curious, what was the outcome of this? How does this actually work under the covers now in `librdkafka`?

**Comment by edenhill** [comment]
@jeffwidman 
For better or worse, but more importantly for compatibility: librdkafka now does what the Java client does.
Each client in the group is responsible for monitoring and updating its subscribed topic set by polling metadata from the cluster and applying its regexp to it.
This isn't optimal from a scalability or robustness perspective, but it'll do for now.

**Comment by jeffwidman** [comment]
Thanks!
I'd deleted my comment because I read through the source. I'm glad you're already thinking about the scalability downsides of this approach.
