### ISSUE TITLE
RD_KAFKA_RESP_ERR_END name

### ISSUE THREAD

**Issue by AlexeyRaga** [edenhill/librdkafka#578]
I am trying to use a new `librdkafka` from Haskell and there is a little problem here:

The `rd_kafka_resp_err_t` now contains both `RD_KAFKA_RESP_ERR_END` and `RD_KAFKA_RESP_ERR__END`. 

In Haskell we use `c2hs` processor that can automatically generate Haskell data types from enums and it is typically used with `underscoreToCase` strategy which transforms names like `RD_KAFKA_RESP_ERR_END` to canonical Haskell's `RdKafkaRespErrEnd`.

The problem is that it doesn't seem to care about multiple underscores in line and tries to create two type constructors with the same name `RdKafkaRespErrEnd`, which is illegal in Haskell.

Is it possible to rename enum members in a way that their difference is not only in underscores?

**Comment by edenhill** [comment]
Renamed _END to _END_ALL.
Good enough?
