### ISSUE TITLE
Getting "Local: Broker transport failure" by reducing metadata refresh rate and sparse

### ISSUE THREAD

**Issue by rathdeep** [edenhill/librdkafka#581]
Changing following properties to:
topic.metadata.refresh.interval.ms	*	300000
topic.metadata.refresh.sparse	*	true

Randomly throws error "Local: Broker transport failure", although broker is always up.

Default value for 0.8.6 librdkafka library is
topic.metadata.refresh.interval.ms	*	10000
topic.metadata.refresh.sparse	*	false

Do we need to do anything else.

Thanks,

**Comment by edenhill** [comment]
Where are you seeing that error? Can you provide the full log line?
Thanks

**Comment by rathdeep** [comment]
On both consumer and producer applications.

Following gets logged on console from library
FAIL|rdkafka#producer-0| hostname:5757/2: Receive failed: Disconnected

And following in the  error callback.
Error for kafka instance [rdkafka#producer-0], Error [Local: Broker transport failure]: [hostname:5757/8: Receive failed: Disconnected]

Kafka cluster has 10 brokers.

**Comment by edenhill** [comment]
This is the broker closing the connection, is there anything in the broker logs?

Could be the 0.9 idle connection reaper kicking in, I think it defaults to 10 minutes.

**Comment by rathdeep** [comment]
There is nothing in broker logs. I tried changing topic.metadata.refresh.interval.ms to 5 mins, 15 mins, 30 mins. Always get this error . Broker version is 0.8.2

**Comment by edenhill** [comment]
Do you get the disconnects at some regular interval? If so, which?

**Comment by rathdeep** [comment]
around 10 mins interval.. 6 - 7 times after startup, then it stops.

**Comment by edenhill** [comment]
Something else than librdkafka is closing the connection, it could be:
 * broker
 * firewall/nat/..

For whatever reason:
 * idle timeout (broker, tcp, nat session, ..)
 * network issues

**Comment by kanppa** [comment]
The broker has this log set to TRACE level, so if you don't change the config of log level, it won't show that the broker indeed close the connection. In my case topic.metadata.refresh.interval.ms is default, and my broker still close connection if idle 10mins. Not sure why.

**Comment by edenhill** [comment]
@kanppa Metadata refreshes are typically performed using a single random broker connection, so it can't be used as a means to fight the idle connection reaper.

**Comment by kanppa** [comment]
Guess i will have to produce some msg every 10mins

**Comment by spritezhong** [comment]
I met a consumer error: Broker transport failure: GroupCoordinator response error
