### ISSUE TITLE
RdKafka::Consumer hang on destroy

### ISSUE THREAD

**Issue by incessantier** [edenhill/librdkafka#582]
Have you seen the destruction of RdKafka::Consumer hang?  In my specific case I've passed in an incorrect broker address (e.g. from user input), and the consumer hangs when I try to destroy and re-create with the correct broker address.

**Comment by edenhill** [comment]
Can this be reproduced with rdkafka_consumer_example_cpp?
What is wrong with the address? Unresolvable? Connection refused? Connection time out? Not a broker?

**Comment by incessantier** [comment]
It's unresolvable (e.g. a broker of asdfasdf).  And no, it doesn't look like the consumer example has the same issue.

At least, a ctrl-c killed it without issue.

Looks like I should maybe update to using the new consumer...does it work for kafka 8.2 or do I need to upgrade to 9?

**Comment by edenhill** [comment]
The KafkaConsumer only works with 0.9, for 0.8 you'll need to use the legacy consume_start() interface.

**Comment by edenhill** [comment]
Anything else I can do here?

**Comment by incessantier** [comment]
Unfortunately we won't be able to upgrade to 0.9.  I haven't looked into it further yet, though.

**Comment by edenhill** [comment]
Sorry, consumer_example is 0.9, can you reproduce with rdkafka_example?
