### ISSUE TITLE
Trouble with rd_kafka_position

### ISSUE THREAD

**Issue by FDePourcq** [edenhill/librdkafka#583]
Hi Magnus,

I need your help. 

The product I am working on needs to be able to recover after a crash. At recovery there are 2 important offsets: First the offset from which we want to start reading a partition, secondly the offset that marks the highest offset processed at the previous (crashed) run.

At recovery we calculate the offset from which we want to start. To get kafka to effectively start from that offset rd_kafka_seek seems to work. (setting the offset in the topars given to the rd_kafka_assign during a rebalancecallback does not always work, forcing the stored offset to the startoffset with rd_kafka_commit during the rebalancecallback and starting from there was also unreliable). 
Issue 1: is rd_kafka_seek the correct way to specify from where to start?
Issue 2: It is not entirely clear when exactly to call the seek because directly before or after the rd_kafka_assign it results in a "communication failure with broker".  (For now i do the seeks at the first 
received message... which is not very clean.)

The committed/stored partitionoffset is the one that should indicate how far we got, the offset that indicates when to stop the recovery. 
Issue 3: I do not know how to read/inspect/get the absolute value from this value (the value set by rd_kafka_commit by another consumer). rd_kafka_position seems to be the way to go but when I give it a list of toppars for the partitions that interest me ... it does not modify the offsets. It does not return an errorcode and the rd_kafka_topic_partition_t.err values remain 0. Alternatively, the offsets in the toppars from the rebalancecallback (during assignment) also remain negative. And in another alternative, the metadata from rd_kafka_metadata does not seem to contain any offsets.

If I do not get this to work quickly I will rearrange the design to store the highest ever processed offset on some external storage and to advance the committed/stored partitionoffset conservatively to the offset from where I would want to start a recovery if ever needed. (In that case I would never need to seek.) 

Greetings from a troubled mind,

Frederic De Pourcq

**Comment by edenhill** [comment]
Hey Frederic,

rd_kafka_seek() should only be called when there is an active consumer for a partition (i.e., following an assign() or .._start()).

However it is advisable to use the partitions in rebalanceCb + assign() to dictate the starting offset, if these dont work then that's a bug.


Are you using the latest master version?

**Comment by FDePourcq** [comment]
My last pull of librdkafka was Thu Mar 3 15:43:32 2016, 
Well ... I had the impression that when I used the rebalanceCb + topar.offset = desired_offset + assign(topars) ... that often the first message delivered was from a farther offset: at the committed/stored kafkapartitionoffset. I could do another pull+merge (i added another assignor) in case some bug got fixed in the meantime?

**Comment by edenhill** [comment]
I'm not really following you on this: 
> rebalanceCb + topar.offset = desired_offset + assign(topars)

Can you elaborate?

**Comment by FDePourcq** [comment]
Shortened from my code, I ask startoffsets  and tried to give them to the assign:
`void rebalanceCallback(rd_kafka_t *rk, rd_kafka_resp_err_t err, rd_kafka_topic_partition_list_t *partitions)
{

	switch(err)
	{
	case RD_KAFKA_RESP_ERR__ASSIGN_PARTITIONS:
	{

		std::set < int32_t > new_partitions;
		for(int i = 0; i < partitions->cnt; ++i)
		{
			new_partitions.insert(partitions->elems[i].partition);
		}
		startoffsets = rebalanceCallback(new_partitions);

		for(int i = 0; i < partitions->cnt; ++i)
		{
			auto j = startoffsets.find(partitions->elems[i].partition);
			if(j != startoffsets.end())
			{
				partitions->elems[i].offset = j->second;
			}

		}
		rd_kafka_assign(rk, partitions);
	}
		break;

	case RD_KAFKA_RESP_ERR__REVOKE_PARTITIONS:
	{
		rd_kafka_assign(rk, NULL);
	}
		break;
	default:
		break;
	}
}
`

**Comment by edenhill** [comment]
Not sure what is what in that example, but are you sure the offsets you assign are valid offsets? Otherwise auto.offset.reset will kick in (which btw was fixed after your last pull!).

**Comment by FDePourcq** [comment]
i believe I gave valid offsets, i checked it by letting kafkacat output all the offsets within those partitions. The kafkaserver still had the data that I wanted.

**Comment by edenhill** [comment]
Okay, can reproduce this with debug=topic,fetch and provide the logs?

**Comment by FDePourcq** [comment]
I added this code in the rebalance callback:

```
            for(int i = 0; i < partitions->cnt; ++i){
            	std::cerr << "partition " << partitions->elems[i].partition << " is asked to started at " << partitions->elems[i].offset << std::endl;
            }

            rd_kafka_assign(rk, partitions);
```

```
partition 0 is asked to started at 11438
...
partition 0 is empty. (offset 16902)
...
!!! Recovery asked to start partition 0 at offset 11438 BUT first thing mentioned by kafka is offset 16902 !!!
```

And kafkacat -C -t theinput32v36  -b 192.168.99.100:9092 -f "%o\n" -p 0 -e 
gives me a list from 0 to 16901  of 16902 lines...

[wrongstartoffset.txt](https://github.com/edenhill/librdkafka/files/182379/wrongstartoffset.txt)

**Comment by FDePourcq** [comment]
After some more grepping for the right data:
[filteredlog4magnus.txt](https://github.com/edenhill/librdkafka/files/182422/filteredlog4magnus.txt)

**Comment by edenhill** [comment]
Thanks, will investigate.

**Comment by FDePourcq** [comment]
The above is with the latest git version btw,
And the code that creates the consumer is attached, maybe it can help...

[consumerconfig.txt](https://github.com/edenhill/librdkafka/files/182665/consumerconfig.txt)

**Comment by edenhill** [comment]
Can you give latest master a try, it should have fixed this issue

**Comment by FDePourcq** [comment]
The startoffsets seem to be good now, the assert is not triggered anymore, at least not in the handfull of runs i just did. Great! Thanks! ( Got to say I messed up before with the update, I was always running a rdkafka compiled shortly before the migration to visual studio 2014.)

Issue 3 still stands though. Is  rd_kafka_position supposed to work correctly before during the rebalancecallback before the assign? The offsets and err's of the given topars remains unchanged. I would expect to see at least one of the 2 error mechanisms kicking into action there.

**Comment by edenhill** [comment]
The VS toolchains are a mess, I'm sorry about that, not really sure what is the best solution. I think I reverted back to toolchain v120 (VS2013).


I can't reproduce your issues with rd_kafka_position(), it returns proper offsets both from within rebalance_cb (ASSIGN) and when called directly after creating the consumer.
I used the rdkafka_consumer_example.c  to test this.

**Comment by FDePourcq** [comment]
i will hunt for this today, is there logging that can help here? a value for "debug" ?

**Comment by edenhill** [comment]
debug=cgrp,topic,protocol

**Comment by FDePourcq** [comment]
Ok, it works, but i propose 2 modifications to rd_kafka_position:
- overwrite the offset-values from the topars before reading them... at the moment the initial value of the offset affects the outcome of the getter. If i initialise those offsets to eg -42 then i will still have -42 after the call with error 0.

- for empty never-used partitions ... internally the offsetfetchrequest returns -1. In that case the returned offset is not set at all, it remains -1001.  And error remains 0. A troubled user could try to figure out what that means by for example ... setting the inputoffset to -42 to see if that value gets overwritten ... and falls into pit number 2. 

Great! all fixed :) :+1:

**Comment by edenhill** [comment]
Good point, the passed offsets are now overwritten with RD_KAFKA_OFFSET_INVALID.
It will also retain the INVALID value for your second case, where the broker does not have stored offset for a partition.

For unknown topic and partitions the .err field will be set (by the broker).

**Comment by edenhill** [comment]
That should do it.
Thanks for reporting this issue and providing all the good info, it really helps in fixing.
