### ISSUE TITLE
Chicken and egg-problem

### ISSUE THREAD

**Issue by FDePourcq** [edenhill/librdkafka#585]
Hi Magnus,

There are some constraints on buffersizes in the configuration for a producer. If wrong something might blow up at runtime when least expected.
I don't know all of them, but I got a line like this one:
`std::size_t receivemessagemaxbytes = fetchmessagemaxbytes * numpartitions + 200000;`

See how I use the number of partitions there. It is hardcoded because to inspect the broker for metadata i need the producer first. 

So 
Issue 1: a exhaustive list of these caveats somewhere would be nice. right now i don't even know what options i should make configurable to operations.
Issue 2: is it possible to change config like "message.max.bytes" after the producer has been constructed? (So that it can be used first to get info from the broker to calculate the configuration?)

Looks like kafka could use some layer on top of the current configurationoptions to simplify things. Some kind of autoconfig.

**Comment by edenhill** [comment]
answers:
1. librdkafka has a fair round-robin fetcher. This means that a single fetch must not be able to fetch messages from all partitions, it'll fetch from the ones that didnt fit in on the next round (which is immediately, typically). Are you seeing actual problems with this?

2. No sorry, config is immutable after creating the instance. I've had some thoughts on making it mutable but there is too much work and performance penalty, and there is no really clear use-case either.


Ideally librdkafka should be able to figure out proper values itself.

**Comment by FDePourcq** [comment]
Because of the (obscenely) large outputmessage-sizes i did encounter problems, i had to fiddle with the broker-config and had to hardcode that line.
Ah well, lets just make it all configurable :)
