### ISSUE TITLE
Another startoffset failed

### ISSUE THREAD

**Issue by FDePourcq** [edenhill/librdkafka#586]
Hi Magnus,

My consumer specified in the rebalancecallback to start partition 0 at offset 0...
A bit later kafka throws me at the end of the partition, offset 25910.
The data is still there (I do have another bug where entire partitions simply disappear, but that is kafka.)
I havent updated rdkafka the past 24 hours, you might have fixed it ? 

> %7|1458743467.125|FETCH|rdkafka#consumer-2| 192.168.99.100:9092/0: Topic theinput32v36 [0] at offset 0 (107253/100000 msgs, 26634/1000000 kb queued) is not fetchable: queued.min.messages exceeded

The filtered log attached
[4magnus.txt](https://github.com/edenhill/librdkafka/files/186253/4magnus.txt)

Greetings, 

Frederic De Pourcq

**Comment by edenhill** [comment]
Looking at the log it seems to start fetching at 0 and then work its way up to 25910, you are seeing you dont see any of the first 25909 messages at all?

Is 25910 a proper message (err==0) or PARTITION_EOF?

I'm guessing that log is an excerpt, can you send me the whole log file?
The versions look suspicious, bumping between v7 and v14.

**Comment by FDePourcq** [comment]
- that  "partition 0 is empty. (offset 25910)" is my first line after 
`if(rkmessage->err == RD_KAFKA_RESP_ERR__PARTITION_EOF) `

[mysterycrash_filtered2.txt](https://github.com/edenhill/librdkafka/files/186300/mysterycrash_filtered2.txt)

(this is still somewhat filtered but I can not show more)

**Comment by FDePourcq** [comment]
and the startoffsetcheck really is the very first thing that gets done with a message, (skipping happens but later)

**Comment by FDePourcq** [comment]
Its as if that verson v14 leaked from partitons 16 or 24 to partitions 0 and 8  ...  but not for all datastructures from partitions 0 and 8 :)

**Comment by FDePourcq** [comment]
hypothesis: that consumer has duplicate datastructures for partition 0. 
- the fetch decide updated modified one of them
- the duplicate got introduced during previous take/give-back rebalancing. (I was causing them.)

**Comment by edenhill** [comment]
Could you join on gitter to discuss this?
https://gitter.im/edenhill/librdkafka

**Comment by FDePourcq** [comment]
So yesterday I figured that for every consumerxpartition there is a version-number kept internally in rktp->rktp_fetch_version,
outgoing data for a specific broker for all relevant partitions is bundled in rd_kafka_buf_t request->rkbuf_op_version ....    which seems wrong by design, it should be a rktp_fetch_version-value per message or per partition within  rd_kafka_buf_t ...
The effect is that sometimes data from one partition with a low version number gets skipped when it is in company of a partition with a high version number...  `if(request->rkbuf_op_version < rktp->rktp_fetch_version)`
which might lead to all kinds of curiosities later like eg wrong startoffsets.

**Comment by FDePourcq** [comment]
quick hack
[versioning_issue.diff.txt](https://github.com/edenhill/librdkafka/files/193104/versioning_issue.diff.txt)

**Comment by edenhill** [comment]
Merged to master
