### ISSUE TITLE
Failed to consume from newly created topic

### ISSUE THREAD

**Issue by szmcdull** [edenhill/librdkafka#587]
I'm using kafka_2.11-0.9.0.1 and librdkafka-0.9.0.99. I created the topic with the following command:

bin/kafka-topics.sh --zookeeper localhost --topic newtest --create --replication-factor 2 --partition 3 --config retention.bytes=100000000

With 3 brokers:
0: Linux virtual machine IP 192.168.1.77, this is also where zookeeper is on
1: Linux virtual machine IP 192.168.1.67
2: Windows host

I made a test program with librdkafka as both the producer and the consumer. The producer send 1 sync messages per second. The consumer consume the sync message and then signals the producer to stop syncing and start to send the test payloads.

When I run the test, the consumer can never receive the sync messages (always gets a timeout), no matter how many sync messages the producer produces. I can see the sync messages really got sent to the broker using the kafka-console-consumer.sh command. But the program just cannot consume them.

After some searching, I add debug=topic,metadata,queue config, then I see repeated logs complaining invalid / out-of-range offset:

%7|1458807452.924|OP|rdkafka#consumer-1| newtest [0] received op CALLBACK (v0) in fetch-state active
%7|1458807452.924|PARTSTATE|rdkafka#consumer-1| Partition newtest [0] changed fetch state active -> offset-query
%7|1458807452.926|OFFSET|rdkafka#consumer-1| newtest [0]: offset reset (at offset INVALID) to END: Fetch response: Broker: Offset out of range
%7|1458807452.928|OFFREQ|rdkafka#consumer-1| 192.168.1.67:9092/1: Partition newtest [0]: querying for logical offset END (opv 2)
%7|1458807452.931|OFFSET|rdkafka#consumer-1| 192.168.1.67:9092/1: OffsetRequest (-1) for topic newtest [0]
%7|1458807452.933|PARTSTATE|rdkafka#consumer-1| Partition newtest [0] changed fetch state offset-query -> offset-wait
%7|1458807452.969|FETCHADD|rdkafka#consumer-1| 192.168.1.77:9092/0: Removed newtest [2] from fetch list (0 entries, opv 2)
%7|1458807452.977|FETCHADD|rdkafka#consumer-1| 192.168.2.59:9092/2: Added newtest [1] to fetch list (1 entries, opv 2)
%7|1458807452.978|FETCH|rdkafka#consumer-1| 192.168.2.59:9092/2: Fetch for 1 toppars, fetching=1, backoff=-194ms
%7|1458807452.981|OP|rdkafka#consumer-1| newtest [1] received op CALLBACK (v0) in fetch-state active
%7|1458807452.982|PARTSTATE|rdkafka#consumer-1| Partition newtest [1] changed fetch state active -> offset-query
%7|1458807452.983|OFFSET|rdkafka#consumer-1| newtest [1]: offset reset (at offset INVALID) to END: Fetch response: Broker: Offset out of range
%7|1458807452.985|OFFREQ|rdkafka#consumer-1| 192.168.2.59:9092/2: Partition newt...

For the code please look at the attachment
[ConsoleApplication1.zip](https://github.com/edenhill/librdkafka/files/187461/ConsoleApplication1.zip)

**Comment by edenhill** [comment]
Can you provide some more logging, I see the client sending OffsetRequest for partition 0 but there is no reply (yet), so some more log would be helpful.

**Comment by edenhill** [comment]
Also make sure to use latest master.

**Comment by szmcdull** [comment]
Thank you for quick reply. I'm using the latest release, as suggested by your main page. Should I switch to latest master?
[log.txt](https://github.com/edenhill/librdkafka/files/187474/log.txt)

**Comment by edenhill** [comment]
Yes, please do switch to master, the 0.9.0.99 release is not a proper release.

**Comment by szmcdull** [comment]
Thanks a lot edenhill. After I switch to master, the issue run away. I can confirm by deleting and recreating the topic :)

Should I use master for product quality? If not, when would you like to make new release version?

By the way, the 'queue.buffering.max.ms', 'fetch.error.backoff.ms' and 'fetch.wait.max.ms' config don't make a big change in my program, I mean the latency is always larger than 1 sec. It is only when I add a 100ms sleep between every 4k produce(), the latency can be lowered to 100-200 ms. Am I doing anything wrong? Would it be that I am running all the 3 brokers virtually on the same physical machine? I can see CPU and disk usage go really high when producing 100k messages.

**Comment by edenhill** [comment]
I'm looking to release a proper version within the next 14 days.
