### ISSUE TITLE
Producer with bootstrap.servers not set should fail to produce

### ISSUE THREAD

**Issue by szmcdull** [edenhill/librdkafka#588]
Producer::produce returns ERR_NO_ERROR even if I have not set the bootstrap.servers config.

**Comment by edenhill** [comment]
Not failing immediately when there are no bootstrap servers is a valid use-case for applications that add brokers through some other method (e.g., ZK) and later calling rd_kafka_brokers_add().

**Comment by szmcdull** [comment]
Would the produced messages be buffered and send to the brokers added later?

**Comment by edenhill** [comment]
Yes, they'll remain in the producer queue for message.timeout.ms (5 minutes default) and get sent whenever a leader broker becomes available.

**Comment by szmcdull** [comment]
Is there a sync-ed produce? I want to make sure the message really delivered or I have to save them to disk first.

**Comment by edenhill** [comment]
It is usually not advisable to use sync producing since it will kill performance (max message rate is bound by broker RTT, e.g., 2ms to produce a message = max 500 messages/s), but if you still want this have a look at: https://github.com/edenhill/librdkafka/wiki/Sync-producer
