### ISSUE TITLE
Not support AIX6.1?

### ISSUE THREAD

**Issue by salmanchan** [edenhill/librdkafka#589]
When I execute this command , there are many errors.
operating system AIX 6.1

abmhost02:[/app/librdkafka-mastern]#./configure
checking for OS or distribution... ok (AIX)
checking for C compiler from CC env... failed
checking for gcc (by command)... failed
checking for clang (by command)... failed
checking for cc (by command)... failed (fail)
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... failed
checking for C++ compiler (clang++)... failed
checking for C++ compiler (c++)... failed (fail)
checking executable ld... ok
checking executable nm... ok
checking executable objdump... failed (disable)
checking executable strip... ok
checking for pkgconfig (by command)... failed
checking for install (by command)... failed
checking for PIC (by compile)...mklove/modules/configure.base: line 905: mktemp: command not found
mv: cannot rename  to .c: 
No such file or directory
 failed (disable)
...

**Comment by edenhill** [comment]
I'm sorry but I dont have access to an AIX machine so I have no idea if librdkafka works there or not.

**Comment by edenhill** [comment]
If I was given access to an AIX machine I could make the porting effort.
