### ISSUE TITLE
how to repare this compile warning?

### ISSUE THREAD

**Issue by merlin82** [edenhill/librdkafka#590]
warning: 'class RdKafka::DeliveryReportCb' has virtual functions and accessible non-virtual destructor

**Comment by edenhill** [comment]
What compiler (and its version) are you using?

**Comment by merlin82** [comment]
@edenhill  use g++,  the version is:
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.6 20110731 (Red Hat 4.4.6-4) (GCC)

**Comment by merlin82** [comment]
@edenhill ok, i know it ,  add this in rdkafkacpp.h can ignore warning. thanks.
#pragma GCC diagnostic ignored "-Wnon-virtual-dtor"

**Comment by edenhill** [comment]
I think this is fixed on master now, please verify.
