### ISSUE TITLE
Negative lag returned by kafka if using java producer and librdkafka consumer

### ISSUE THREAD

**Issue by zwaheed-rms** [edenhill/librdkafka#596]
Kafka Server Version: 0.9
librdkafka version: 0.9.99.0 (RDKAFKA_VERSION_STR  0.9.1 from configure script)
Kakka official Java Client: 0.9.0.0

We have a setup where the producer is java based and consumer is using C++ librdkafka to consume the messages. But quite often we run into an issue where the librdkafka consumer will stop receiving messages and when we run the following command:

/bin/kafka-consumer-offset-checker.sh --group some_group --topic some_topic --zookeeper xxx:9092

then it return the following output:

Group           Topic                          Pid Offset          logSize         Lag             Owner
some_group some_topic           0   10              1               -9              none
some_group some_topic           1   11              0               -11             none
some_group some_topic           2   9               0               -9              none
some_group some_topic           3   7               1               -6              none

The lag is a negative number which does not make sense. The workaround we are using right now is to send some dummy messages to the topic and bring the lag to 0. After that the librdkafka client starts receiving messages.

Any ideas on what could be going on or how to debug this. Both drivers should be using broker based offset by default according to the documentation.

**Comment by edenhill** [comment]
The 0.9.0.99 tag was never intended for public use but only for package testing, I recently moved that tag to another commit too. Sorry about that.
Since the tag was moved it is not clear what exact version you are on, can you tell me the sha1 version of your librdkafka version? (e.g. `git log | head -1`)

**Comment by zwaheed-rms** [comment]
Actually I downloaded the zip from release tab https://github.com/edenhill/librdkafka/releases. And droped it in my thirdparty folder and later I compile it from there.

So I don't have the .git folder for librdkafka so can't run git log | head -1.

I downloaded it around 25th Feb, maybe that helps. But I can upgrade my copy of librdkafka if that would help. Can you point me to the librdkafka release that works with Kafka 0.9?

**Comment by edenhill** [comment]
Latest master can be found here: https://github.com/edenhill/librdkafka/archive/master.zip

**Comment by zwaheed-rms** [comment]
Should I use master or is there a release that has Kafka 0.9 support.

**Comment by edenhill** [comment]
Please use master until 0.9.1 is released.

**Comment by edenhill** [comment]
Let me know if latest master solved your issues

**Comment by zwaheed-rms** [comment]
Sure I will observe it and let you know in a couple of days.

**Comment by zwaheed-rms** [comment]
We did not notice the negative lag issue after upgrading. However we now see a different issue. On application shutdown the call to RdKafka::KafkaConsumer::Close just hangs and never returns. I will close this issue and will open a separate issue for the hang.
