### ISSUE TITLE
Enable heartbeat during rebalance_cb

### ISSUE THREAD

**Issue by FDePourcq** [edenhill/librdkafka#598]
When usercode takes arbritrary long times during the rebalance_cb (to eg figure out the desired offsets and to recover where it has left of... or simply because the user loves to put a Sleep(60) in there) ... the rebalance will be triggered again soon after the first one ended.
I assume this is caused by the server not seeing a heartbeat for that consumer for longer than session.timeout.ms and consequently deciding to forget the consumer.

Solution as proposed by @edenhill & observed to be working by me:
rdkafka_cgrp.c:1632 and move that case RD_KAFKA_CGRP_JOIN_STATE_WAIT_REBALANCE_CB: just before JOIN_STATE_ASSIGNED: and remove the break; inbetween.

**Comment by edenhill** [comment]
Even with this fix in place there is still a problem if the group rebalances while the app is still in its rebalance_cb, thus stacking up rebalance callbacks to be called.
There is no easy way around that though.

**Comment by FDePourcq** [comment]
In my particular case it should not be a problem to have a bunch of rebalance callbacks in quick succession because of A. sticky partitionining (so i should get the same partitions over ander over) and B. code that detects when the same partitions are taken and handed back so no recovery is needed.

**Comment by edenhill** [comment]
Merged to master. Please verify.
