### ISSUE TITLE
RdKafka::KafkaConsumer vs RdKafka::Consumer

### ISSUE THREAD

**Issue by senior7515** [edenhill/librdkafka#600]
on the old kafka consumer one can do 

````
consumer->start ( topic, partition, offset ) 
````
However, on the new consumer you can't really do that, there is no start() method. 

How does one reset the the consumer to read from the beginning, aka 

```
  static const int64_t OFFSET_BEGINNING = -2; /**< Consume from beginning */
  static const int64_t OFFSET_END       = -1; /**< Consume from end */
  static const int64_t OFFSET_STORED    = -1000; /**< Use offset storage */

```

I tried setting it on the TopicParition* on the rebalance_cb, but looking at the code, it just sets the offset to a local variable. 

Thanks!

**Comment by senior7515** [comment]
I'm using the 0.9.0 driver

**Comment by edenhill** [comment]
Using latest master you can indeed set the initial offset for each partition in the TopicPartition list you pass to assign() (from rebalanceCb or standalone).

**Comment by senior7515** [comment]
@edenhill thanks for the fast response. 

I'm pretty sure I'm doing that 

This is the hash of the branch - tag 0.9.0. Will try 

50ee2ea30e798258e934f26c830c91b31fb0dca6

This is how I was implementing it. 

https://gist.github.com/senior7515/bb67dd60539c26363b58b3aef6b401d5

**Comment by edenhill** [comment]
You should be using latest master (which will soon be 0.9.1), 0.9.0 was never a formal release had some issues.

**Comment by senior7515** [comment]
@edenhill THANK YOU!  ... testing now.

**Comment by senior7515** [comment]
Looking good. It started consuming from the begining. Will report progress when I change the offsets. 

Somehow after commiting the offset via

consumer->commitSync() -> and seeing offsets being committed, on the `RdKafka::RebalanceCb` i see the stored offset on the TopicParitions* to be -1001 --> invalid offset, my guess is that it hasn't started reading the offsets yet, so it doesn't know. 

Thanks! so much.

**Comment by edenhill** [comment]
The partitions in the TopicPartitions list in RebalanceCb will always be INVALID since no offset fetching from the broker has taken place yet.
Passing a partition with offset=INVALID to assign() tells it to retrieve the stored offset from the broker, or if that is not available revert to auto.offset.reset setting.

**Comment by senior7515** [comment]
Great, btw, the 0.9.1-pre0 branch works w/ setting the TopicParition->set_offset(). 

Last question, what is the difference between OFFSET_STORED and OFFSET_INVALID then ? 

```
  static const int64_t OFFSET_BEGINNING = -2; /**< Consume from beginning */
  static const int64_t OFFSET_END       = -1; /**< Consume from end */
  static const int64_t OFFSET_STORED    = -1000; /**< Use offset storage */
  static const int64_t OFFSET_INVALID   = -1001; /**< Invalid offset */
```

I imagine, that OFFSET_INVALID is just the default value, but in practice they mean the same. 

it's probably just a way to denote that the user hasn't set the value yet?

Thanks! for the help!

**Comment by edenhill** [comment]
Thats good to hear!

Yes you are right, INVALID is just the default value.
