### ISSUE TITLE
Consumer group support

### ISSUE THREAD

**Issue by vdeters** [edenhill/librdkafka#601]
Hello, your introduction states that there is no consumer group support, but I want to verify what that means in my context. We have a requirement to run redundant Kafka consumers that consume an identical stream of messages in identical order. For this reason we plan to have these consumers consume from the same topic partition and identify themselves as unique consumer groups. Can I do this using librdkafka? Thanks,
Vince

**Comment by edenhill** [comment]
Ooh, means I need to update the introduction because there is in fact support for (broker >=0.9) consumer groups!

I dont see any problems with the use-case your are describing.

I will release 0.9.1 shortly, until then I strongly suggest that you use latest master branch.

**Comment by vdeters** [comment]
Excellent, thanks for your quick response. Follow up question:
These consumers are part of a failover group and need to be aware of each other's presence. I suppose I could use Zookeeper for this purpose, but is there anything already in the protocol that provides awareness of consumer (or producer) groups attached to a specific topic or partition?
Thanks.

**Comment by edenhill** [comment]
Awareness is only available within a consumer group, not across them.

**Comment by vdeters** [comment]
Ok, one more question: for the scenario described in my initial message above, should I use a RdKafka::KafkaConsumer or a RdKafka::Consumer? It doesn't complain if I set "group.id" in a config used by a RdKafka::Consumer, but it's not obvious to me whether the group id is actually sent to the broke in this case. Thanks.

**Comment by edenhill** [comment]
You should use the KafkaConsumer, it can function both as a balanced consumer group (if you use subscribe()), or as a standalone consumer (if you use assign()).

**Comment by jose9r** [comment]
Hello, im trying to use KafkaConsumer with one group and with debug options 
%7|1460117663.901|TOPIC|rdkafka#consumer-1| New local topic: queue
%7|1460117663.901|DESP|rdkafka#consumer-1| Adding desired topic queue [0]
%7|1460117663.901|FETCHSTART|rdkafka#consumer-1| List with 1 partition(s):
%7|1460117663.901|FETCHSTART|rdkafka#consumer-1|  queue [0] offset INVALID
%7|1460117663.901|OFFSET|rdkafka#consumer-1| 10.0.0.203:9092/1: OffsetFetchRequest(v1) for 1/1 partition(s)
%7|1460117663.999|OFFSET|rdkafka#consumer-1| Topic queue [0]: setting default offset INVALID
%7|1460117663.999|OFFSETFETCH|rdkafka#consumer-1| 10.0.0.203:9092/1: OffsetFetchResponse: queue [0] offset -1
%7|1460117663.999|OFFFETCH|rdkafka#consumer-1| 10.0.0.203:9092/1: OffsetFetch for 1/1 partition(s) returned Success
%7|1460117663.999|FETCHSTART|rdkafka#consumer-1| List with 1 partition(s):
%7|1460117663.999|FETCHSTART|rdkafka#consumer-1|  queue [0] offset INVALID
%7|1460117663.999|FETCH|rdkafka#consumer-1| Start fetch for queue [0] in state none at offset INVALID (v2)
%7|1460117663.999|PARTSTATE|rdkafka#consumer-1| Partition queue [0] changed fetch state none -> offset-query
%7|1460117663.999|OFFSET|rdkafka#consumer-1| queue [0]: offset reset (at offset INVALID) to END: no previously committed offset available: Local: No offset stored
%7|1460117663.999|OFFSET|rdkafka#consumer-1| queue [0]: no current leader for partition, starting offset query timer for offset END

and i cant read messages, because the offset is setted to the end. When will you probably have available new version with group support??

**Comment by jose9r** [comment]
Im using kafka_2.11-0.9.0.1 and php-rdkafka from arnaud-lb repository https://github.com/arnaud-lb/php-rdkafka/

**Comment by edenhill** [comment]
When starting a new consumer group there will be no offsets stored so it will choose the starting offset based on the topic config property `auto.offset.reset` which defaults to `latest` (END)

**Comment by jose9r** [comment]
I set auto.offset.reset to smallest, but it isnt valid to Conf() from KafkaConsumer config.

**Comment by edenhill** [comment]
That is a topic config property.

Create a topic config object and set `auto.offset.reset`, then assign the object as the default topic config to your global config object.

**Comment by edenhill** [comment]
@arnaud-lb Ping ^ not sure if you are exposing the default topic config for high-level consumer users?

**Comment by edenhill** [comment]
Added to FAQ: https://github.com/edenhill/librdkafka/wiki/FAQ

**Comment by arnaud-lb** [comment]
@edenhill @jose9r [RdKafka\Conf::setDefaultTopicConf()](https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka-conf.setdefaulttopicconf.html) allows to set the default topic config :)

**Comment by jose9r** [comment]
ok thank you so much!!!

**Comment by vdeters** [comment]
Can you please provide a cpp KafkaConsumer example that uses assign() instead of subscribe()? rdkafkacpp.h only shows assign() called in the context of a rebalance callback but it's not clear that I even need to implement that callback when I have one consumer per group. It's also not clear to me how the topic is set if subscribe() is not called. Thanks,
Vince

**Comment by edenhill** [comment]
=Balanced high-level consumer
subscribe() takes a absolute list of topics and joins the consumer group configured with `group.id` with those topics as its subscription. One of the group members will be elected leader and it performs the partition assignment (according `partition.assignment.strategy`) for all topics subscribed by members of the group.

The rebalance callback is called when a member receives or looses its partition assignment (ASSIGN / REVOKE) and allows an application to perform auxilliery tasks, such as special handling of offset storage. An application must call assign() from within the rebalance to atomically update its partition assignment based on the ASSIGN or REVOKE.

If no rebalance callback is registered librdkafka does the assign() call automatically and no further actions are needed by the application.


=Simple consumer
The assign() call may also be used directly with no previous subscribe() call, in this case the consumer will not join any consumer group but immediately start consuming the partitions provided to assign().
To stop consuming simply provide an empty list to assign().


Does that help?

**Comment by vdeters** [comment]
Thanks that helps somewhat...I thought I could implement multiple simple consumers and call assign() directly but since they don't implement a consumer group they won't be allowed to consume an identical stream from a single partition correct? If so, I need to use balanced high level consumers even though each consumer will be the lone consumer in a unique consumer group, and the rebalance callback is still required. Hope I have that right.

**Comment by edenhill** [comment]
You should only use the high-level balanced consumer if you want a set of consumers to NOT share messages, i.e., each partition is assigned to only one consumer.
This is what the high-level balanced consumer is all about.

You are saying that you want multiple consumers to consume the same set of partitions, but you also say you want a consumer group. These two statements contradicts since a consumer group will make sure no two consumers share the same partition.

It sounds like you should use assign() directly, and no subscribe().

**Comment by vdeters** [comment]
If I use assign() directly and assign the same partition to multiple simple consumers, will each consumer receive their own copy of every message in the partition in the same order?

**Comment by edenhill** [comment]
Yes.

**Comment by vdeters** [comment]
Ok, so do I even need to set group.id in this case? (I thought consumers needed to identify themselves as unique consumer groups to consume an identical stream from a single partition)

**Comment by edenhill** [comment]
group.id is needed to find the proper coordinator broker so that offsets can be committed. I suggest you use one group per application.

**Comment by vdeters** [comment]
(...by single partition, I mean the same partition...)

**Comment by jose9r** [comment]
so the default option for auto.offset.reset (largest) isnt working for me. Its a general issue or bad configuration? Because when i suscribed to a queue with many messages, i dont want to reprocess old messages.

**Comment by edenhill** [comment]
@arnaud-lb Will @jose9r need to do anything special with the default config after setting `auto.offset.reset`? E.g., apply it to the main config or so?

**Comment by arnaud-lb** [comment]
Yes, the property has to be set before calling setDefaultTopicConf():

```
$topicConf = new RdKafka\TopicConf();
$topicConf->set('auto.offset.reset', 'largest');

$conf->setDefaultTopicConf($topicConf);

$consumer = new RdKafka\KafkaConsumer($conf);
```

**Comment by jose9r** [comment]
i have the same config, but when i try to consume always new messages dont appear, and offset is set to end.

**Comment by edenhill** [comment]
@jose9r Please create a new issue for this problem, and provide output from a run with "debug=topic,fetch" configured.

**Comment by vdeters** [comment]
So I have 2 simple consumers consuming from the same topic and partition, setting the same group.id, and both setting "auto.offset.reset" = "smallest". They both call assign(). The topic has no messages. When my producer writes to that topic and partition, both consumers get copies of all messages. I assume that's working as designed but if so, I'm a bit confused because it sounds like this case from the kafka doc:

If all the consumer instances have the same consumer group, then this works just like a traditional queue balancing load over the consumers.

...what am I missing? Thanks,
Vince

**Comment by edenhill** [comment]
The balancing behaviour is only enabled if you use subscribe().
Den 14 apr 2016 15:37 skrev "vdeters" <notifications@github.com>:

**Comment by vdeters** [comment]
Ok. What are the implications of the consumers using identical vs different group.id values in this case?

**Comment by vdeters** [comment]
By "this case" I mean the scenario I describe above that uses assign().

**Comment by edenhill** [comment]
The offset is only commited once (last commit) per topic+partition+groupid, so if you have two consumers in the same group and restart one of them it will restart from the latest commit of any of them, which might not be desirable.

**Comment by vdeters** [comment]
Ok, understood. But I may want to use identical group ids for another reason, which is the ability of a consumer to detect the presence (and be notified of the disappearance) of other consumers in the group. But this may not be possible using simple consumers - is it even possible using balanced high level consumers?

**Comment by edenhill** [comment]
You cant really do that with the high level consumer either because only one of the group members are elected group leaders and only the leader will receive the full list of members, the non-leader members will not know about the other members.
