### ISSUE TITLE
rdkafka_consumer_example: subscrie topics error

### ISSUE THREAD

**Issue by havenni** [edenhill/librdkafka#604]
my kafka version: 0.8.2.2
when I use rdkafka_consumer_example for test:
./rdkafka_consumer_example test

1460102946.757 RDKAFKA-3-FAIL: rdkafka#consumer-1: SWEBMYVMM000955:9092/0: Receive failed: Disconnected
1460102946.757 RDKAFKA-3-ERROR: rdkafka#consumer-1: SWEBMYVMM000955:9092/0: Receive failed: Disconnected
1460102946.868 RDKAFKA-3-FAIL: rdkafka#consumer-1: SWEBMYVMM000955:9092/0: Receive failed: Disconnected

**Comment by edenhill** [comment]
rdkafka_consumer_example is using the new high-level KafkaConsumer which requires broker version >0.9.
Older brokers simply disconnect when they see a protocol request they dont recognize.
There is unfortunately no way in <0.10.0 for the client to know if a broker supports an API or not, so this is good as these error messages go at this time.

**Comment by havenni** [comment]
thanks for your quick response,  Can I use   rebalance_cb  when  my kafka version is  0.8.2.2 ?

**Comment by edenhill** [comment]
No, the entire KafkaConsumer API depends on broker 0.9 or later.
That includes: subscribe, assign, rebalance_cb, etc.

For 0.8 you will need to use the legacy Consumer (C++) or consume_start() (C)
