### ISSUE TITLE
commit a message from legacy queue failed with RD_KAFKA_RESP_ERR__WAIT_COORD

### ISSUE THREAD

**Issue by szmcdull** [edenhill/librdkafka#609]
Logs:

%7|1460517613.657|MEMBERID|rdkafka#consumer-1| Group "client1": updating member id "(not-set)" -> ""
%7|1460517613.658|BRKREASSIGN|rdkafka#consumer-1| Group "client1" management reassigned from broker (none) to :0/internal
%7|1460517613.658|CGRPSTATE|rdkafka#consumer-1| Group "client1" changed state init -> wait-broker
%7|1460517613.658|BRKASSIGN|rdkafka#consumer-1| Group "client1" management assigned to broker :0/internal
%7|1460517613.660|CGRPOP|rdkafka#consumer-1| Group "client1" received op PARTITION_JOIN in state wait-broker (join state init) for test [0]
consuming...
%7|1460517613.660|PARTADD|rdkafka#consumer-1| Group "client1": add test [0]
%7|1460517613.661|CGRPQUERY|rdkafka#consumer-1| :0/internal: Group "client1": querying for coordinator: intervaled in state wait-broker
%7|1460517613.671|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/bootstrap: Request metadata for locally known topics: connected
%7|1460517613.671|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/bootstrap: Request metadata for locally known topics: connected
%7|1460517613.691|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/bootstrap: ===== Received metadata =====
%7|1460517613.691|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/bootstrap: 1 brokers, 1 topics
%7|1460517613.691|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/bootstrap:   Broker #0/1: 192.168.0.157:9092 NodeId 0
%7|1460517613.692|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/bootstrap:   Topic #0/1: test with 1 partitions
%7|1460517613.692|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/0: Request metadata for locally known topics: leader query
%7|1460517613.692|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/0:   Topic test partition 0 Leader 0
%7|1460517613.692|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/0: Request metadata for locally known topics: leader query
%7|1460517613.693|BRKREASSIGN|rdkafka#consumer-1| Group "client1" management reassigned from broker :0/internal to 192.168.0.157:9092/0
%7|1460517613.696|BRKUNASSIGN|rdkafka#consumer-1| Group "client1" management unassigned from broker handle :0/internal
%7|1460517613.697|BRKASSIGN|rdkafka#consumer-1| Group "client1" management assigned to broker 192.168.0.157:9092/0
%7|1460517613.744|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/0: ===== Received metadata =====
%7|1460517613.744|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/0: 1 brokers, 1 topics
%7|1460517613.745|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/0:   Broker #0/1: 192.168.0.157:9092 NodeId 0
%7|1460517613.745|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/0:   Topic #0/1: test with 1 partitions
%7|1460517613.746|METADATA|rdkafka#consumer-1| 192.168.0.157:9092/0:   Topic test partition 0 Leader 0
Message received - Hello World at offset 10
%7|1460517613.747|CGRPQUERY|rdkafka#consumer-1| 192.168.0.157:9092/0: Group "client1": querying for coordinator: intervaled in state wait-broker
%7|1460517614.759|CGRPOP|rdkafka#consumer-1| Group "client1" received op OFFSET_COMMIT in state wait-broker (join state init)
%7|1460517614.759|CGRPQUERY|rdkafka#consumer-1| 192.168.0.157:9092/0: Group "client1": querying for coordinator: OffsetCommitRequest failed
%7|1460517614.759|CGRPCOORD|rdkafka#consumer-1| 192.168.0.157:9092/0: Group "client1" coordinator is 192.168.0.157:9092 id 0
%7|1460517614.760|CGRPCOORD|rdkafka#consumer-1| Group "client1" changing coordinator -1 -> 0
%7|1460517614.760|CGRPSTATE|rdkafka#consumer-1| Group "client1" changed state wait-broker -> wait-broker-transport
%7|1460517614.763|CGRPSTATE|rdkafka#consumer-1| Group "client1" changed state wait-broker-transport -> up
%7|1460517614.764|CGRPOP|rdkafka#consumer-1| Group "client1" received op PARTITION_LEAVE in state up (join state init) for test [0]
%7|1460517614.766|PARTDEL|rdkafka#consumer-1| Group "client1": delete test [0]
%7|1460517614.764|DESTROY|rdkafka#consumer-1| Terminating instance
%7|1460517614.867|CGRPCOORD|rdkafka#consumer-1| 192.168.0.157:9092/0: Group "client1" coordinator is 192.168.0.157:9092 id 0
%7|1460517614.867|DESTROY|rdkafka#consumer-1| Destroy internal
%7|1460517614.868|CGRPTERM|rdkafka#consumer-1| Terminating group "client1" in state up with 0 partition(s)
%7|1460517614.869|UNASSIGN|rdkafka#consumer-1| Group "client1": unassign done in state up (join state init): without new assignment
%7|1460517614.871|CGRPSTATE|rdkafka#consumer-1| Group "client1" changed state up -> term
%7|1460517614.874|BRKUNASSIGN|rdkafka#consumer-1| Group "client1" management unassigned from broker handle 192.168.0.157:9092/0
%7|1460517614.875|DESTROY|rdkafka#consumer-1| Remove all topics
%7|1460517614.879|MEMBERID|rdkafka#consumer-1| Group "client1": updating member id "" -> "(not-set)"

**Comment by edenhill** [comment]
From the logs it seems that the client has not yet found out which coordinator to use for committing offsets, that's why the offset commit fails.

To verify this can you add a delay in your program between starting to consume and committingn the first offset, like 2 seconds?

This should be handled better in librdkafka.

**Comment by edenhill** [comment]
I believe this is handled better now, offset commits are queued until the coordinator is available.
Please have a try with the latest master.
