### ISSUE TITLE
about, metadata request fialed ?why ?how to fix?

### ISSUE THREAD

**Issue by wangyanshun** [edenhill/librdkafka#610]
I have get the follow log info:

KAFKA-4-METADATA: rdkafka#producer-181 host_address:9092/11: Metadata request failed: Local: Message timed out

I don't know what's the meaning .

What should I do  to fix it.

TKS.

**Comment by edenhill** [comment]
This means the MetadataRequest to the broker timed out, there is no typical reason for this so I suggest you look at the broker logs to see what is up

**Comment by wangyanshun** [comment]
The broker logs is "IOException " and BrokenPipe exception.

two questions:

1.  When the MetadataRequest to the broker timed out, whether the data is lost?
2. What is the MetadataRequest  ?

TKS

**Comment by edenhill** [comment]
The MetadataRequest is used to get information about available brokers and topics, it does not cause any data to be lost if it fails but the failures are an indication that something is wrong, either with your network or the broker health.
