### ISSUE TITLE
synchronous producer Interface Needed

### ISSUE THREAD

**Issue by Eric-918** [edenhill/librdkafka#611]
Hi , Magnus.
Will librdkafka offer synchronous produce interface ?

**Comment by edenhill** [comment]
Hi, please see this entry in the FAQ:
https://github.com/edenhill/librdkafka/wiki/FAQ#why-is-there-no-sync-produce-interface

**Comment by Eric-918** [comment]
If message timeout ,can i get the delivery call back?

**Comment by edenhill** [comment]
Yes, the delivery callback will be called once for each message accepted by produce(), either to indicate success or error (includingn timeout)
