### ISSUE TITLE
poll wake?

### ISSUE THREAD

**Issue by rthalley** [edenhill/librdkafka#614]
We have a mode called RD_POLL_INFINITE_WAKEABLE that lets a producer do an infinite sleep in rk_kafka_poll() and yet allows any threads using that mode to be woken up with rd_kafka_poll_wake().

The advantage here is that you can do an indefinite sleep, thus not costing any effort when there is nothing to do, yet still be able to cause a timely program exit.  Prior to this change we had to have a short timeout in the poll so the thread could check if it needed to exit or not.

Interested?

**Comment by edenhill** [comment]
Interesting. How did you wake up the polling thread?

**Comment by rthalley** [comment]
We call cnd_broadcast(&rkq->rkq_cond).  The poll waiting code was modified to break out of the loop and return if the condition variable wait ended and we were in the RD_POLL_INFINITE_WAKEABLE mode.

**Comment by edenhill** [comment]
Okay, there may be spurious wakeups on condvars though in which case the poll will not restart with INFINITE_WAKEABLE.

What  do you think of enqueueing an op on the queue instead letting the poller know it should bail out?

**Comment by rthalley** [comment]
I wasn't worried about spurious wakeups since the caller has the poll wrapped in a loop, but I'm ok with an enqueue-an-op solution too.

**Comment by edenhill** [comment]
This is usable in the language bindings as well.

**Comment by edenhill** [comment]
I think the most useful approach is to provide this api on queue_t's, I'm not sure about the name but something like: `void rd_kafka_queue_cancel(rd_kafka_queue_t *rkqu);`

 * cancel
 * yield (might be confused with rd_kafka_yield())
 * wakeup
 * wake

**Comment by Quuxplusone** [comment]
@edenhill: I see you closed this as "completed" on 2022-04-07, but can you put something here about _how_ it was completed? I'm just coming around to the conclusion that `rd_kafka_yield` does _not_ do what I want (in fact, some documentation claims it should never be called unless from within a callback handler!), which means either I need to revive #3114, or I need to use the feature you claim to have added in April. Can you elaborate on that feature, please?
