### ISSUE TITLE
active/standby producer

### ISSUE THREAD

**Issue by vdeters** [edenhill/librdkafka#616]
Hi, looking for suggestions on having a standby producer take over for a failed producer based on the last successfully produced message to a fixed topic and partition. When taking over the new producer needs access to the actual last msg (as opposed to the offset or some other correlation id). I plan on using Zookeeper for notification of a failed producer, but no other producer-producer messaging. I could have a standby producer implement a consumer that (when taking over) does a one-time pull of the message at the current offset, but I don't want to overlook something that may already be built in to the protocol. Thanks.

**Comment by vdeters** [comment]
Hi, what is the most efficient way for a RdKafka::Producer to get the current offset for a specific partition in an RdKafka::Topic that another producer has been producing on? Thanks.

**Comment by edenhill** [comment]
The current offset (from a Producer's perspective) is the highest I assume? In that case you should use [query|get]_watermark_offsets()

**Comment by vdeters** [comment]
Ok thanks, that's working. Unrelated question: is there some 10 minute timeout on something? I consistently see this log event about 10 min after connecting my client:

3-FAIL: localhost:9092/bootstrap: Receive failed: Disconnected

followed by this error event:

(Local: Broker transport failure): localhost:9092/bootstrap: Receive failed: Disconnected

**Comment by edenhill** [comment]
That's the 0.9 broker's fancy new idle connection reaper that hits at 10 minute intervals, see here:
https://github.com/edenhill/librdkafka/issues/437#issuecomment-171733277

**Comment by vdeters** [comment]
Ok, how about this message:

3-GRPSYNC: Group "espmeta": synchronization failed: Broker: Group rebalance in progress

I see this show up occasionally when I have multiple RdKafka::KafkaConsumer instances sharing a group id. I suppose a rebalance is normal as these consumers come and go, bit it seems that a new consumer to the group (after another consumer died) may not begin consuming until this rebalance occurs, which seems to take 10s of seconds. Is there a related timeout that can be modified? Thanks.

**Comment by edenhill** [comment]
`session.timeout.ms` is primarily what controls the rebalancing delay.

**Comment by edenhill** [comment]
That log message is now a debug log instead (so you wont see it) and there are some other improvements to the rebalancing code.
