### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by hackerwin7** [edenhill/librdkafka#618]
when I use lua to require the so file, it says :
`
nginx: [error] failed to run init_by_lua*: /export/servers/openresty/lualib/resty/mercury.lua:38: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by /usr/local/lib/librdkafka.so.1)
`
my system is centos 6.4
I google the centos 6.4 with glibc 2.14, but it says that is discouraged.

https://www.centos.org/forums/viewtopic.php?t=6702
https://www.centos.org/forums/viewtopic.php?t=6745

anyway to resolve this ?? thx

**Comment by edenhill** [comment]
Looks like you are using a binary librdkafka package built for another platform.
Instead try compiling and installing librdkafka directly on your target platform.

**Comment by hackerwin7** [comment]
Got it!
I solve it with your ans.
thanks!
