### ISSUE TITLE
Are there any differences in implementation between C/C++ client vs. Java Client?

### ISSUE THREAD

**Issue by seongyun-ko** [edenhill/librdkafka#619]
Hi,

while I am running a simple test program directly using /examples/rdkafka_performance.c.

I found the backpressure mechanism which works with asynchronous request handling mechanism.
There is a configuration parameter called, queue.buffering.max.messages, which, I guess, is the size of the queue in the producer client where the messages from the application threads are enqueued.

When I take a look at Kafka's New Java Producer client, I don't see such a configuration parameter.
Does it mean that C/C++ client and Java client has different asynchronous mechanisms?

thanks,

**Comment by edenhill** [comment]
Your assumptions regarding librdkafka are correct, it is fully asynchronous by design and maintains internal queues both for producing and consuming messages.

I'm not really well versed with the Java producer so I can't say how it behaves.

**Comment by seongyun-ko** [comment]
Thanks, I understood, I will take a look at the Java code again.
Let me ask a brief question. If I set "batch.size = 1" in producer performance test, will the underlying network thread sends a message once at a time even though there are huge amounts of messages in the queue related with 'queue.buffering.max.messages'.
