### ISSUE TITLE
Protocol parse failure at rd_kafka_fetch_reply_handle:3042

### ISSUE THREAD

**Issue by microwish** [edenhill/librdkafka#620]
Hi Magnus,

When I tried using the latest master branch, the error below kept occurring. While I used codes you committed on March 31 after we had talked about an issue over emails, everything was okay.

%4|1461123726.554|PROTOERR|kafka2hdfs0#consumer-1| 192.168.145.202:9092/145202: Protocol parse failure at rd_kafka_fetch_reply_handle:3042
%4|1461123726.554|PROTOERR|kafka2hdfs0#consumer-1| 192.168.145.202:9092/145202: expected 5545025 bytes > 1048599 remaining bytes

**Comment by edenhill** [comment]
What is your client config and broker version?

**Comment by microwish** [comment]
client related config:

client.id=kafka2hdfs0
metadata.broker.list=192.168.145.201:9092,192.168.145.202:9092,192.168.145.203:9092,192.168.145.204:9092,192.168.145.205:9092,192.168.145.206:9092,192.168.145.207:9092,192.168.145.208:9092,192.168.145.209:9092,192.168.145.210:9092
#auto.commit.enable=true
offset.store.method=file
offset.store.path=/data/users/data-infra/kafka2hdfs/offset
#auto.offset.reset=smallest
group.id=kafka2hdfs
queued.min.messages=120000
queued.max.messages.kbytes=1100000


broker version: 0.8.2.2

**Comment by edenhill** [comment]
Try setting broker.version=0.8.2.2 and see if that helps

**Comment by GeoffreyOnRails** [comment]
Hello, I just encountered the same issue with the 13 Apr-master version, I downgraded librdkafka to the previous version that I knew was working (i.e 9 Feb-master version) and everything works fine now.

**Comment by microwish** [comment]
@edenhill 
Hi Magnus, I set broker.version=0.8.2.2 explicitly and the same error kept occurring when I used the latest master:

%4|1462526163.326|PROTOERR|kafka2hdfs0#consumer-1| 192.168.145.206:9092/145206: Protocol parse failure at rd_kafka_fetch_reply_handle:3044
%4|1462526163.326|PROTOERR|kafka2hdfs0#consumer-1| 192.168.145.206:9092/145206: expected 8943550 bytes > 25 remaining bytes
%4|1462526163.332|PROTOERR|kafka2hdfs0#consumer-1| 192.168.145.208:9092/145208: Protocol parse failure at rd_kafka_fetch_reply_handle:3044
%4|1462526163.332|PROTOERR|kafka2hdfs0#consumer-1| 192.168.145.208:9092/145208: expected 8943550 bytes > 25 remaining bytes

**Comment by edenhill** [comment]
Interesting, thanks for the info.

**Comment by edenhill** [comment]
Ive made some protocol compatibility fixes on master, please update to latest one and try again. Make sure to set broker.version.fallback=  appropriately.

**Comment by edenhill** [comment]
@microwish can you try this on latest master?

**Comment by hw-pega** [comment]
@edenhill 

I encountered same issue, and this solution:  set broker.version.fallback= "0.8.8.2",  works for me.

**Comment by edenhill** [comment]
@hw-pega That's absolutely right! (even though you probably mean 0.8.2.2)

More info here:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by hw-pega** [comment]
Oh, sorry for typo, I mean 0.8.2.2

**Comment by dsouzamanish** [comment]
I encountered same issue. Is setting 0 broker.version.fallback= "0.8.2.2"  is the only solution to this problem.? OR do i have to make any other changes to the Producer or Broker?
Following is the error which is recorded in server error log
%4|1467777482.818|PROTOERR|rdkafka#producer-2| 172.16.xx.xx:xxxx/3: Protocol parse failure at rd_kafka_produce_reply_handle:1622
%4|1467777482.819|PROTOERR|rdkafka#producer-2| 172.16.xx.xx:xxxx/3: expected 4 bytes > 0 remaining bytes

Plz help

**Comment by edenhill** [comment]
Yes, set broker.version.fallback to your broker version.

**Comment by dsouzamanish** [comment]
No such configuration property: "broker.version.fallback" I M getting this error after adding broker.version.fallback
Following is the code i have writtened

try{
            $conf = new RdKafka\Conf();
            $conf->setErrorCb(function ($kafka, $err, $reason) {
               $this->callBackWrite($kafka, $err, $reason);
            });
            $conf->set('broker.version.fallback', '0.8.2.2');

            my_var_dump($conf, "Manish KAfka Config");
            $this->producer = new RdKafka\Producer($conf);

            my_var_dump($this->producer, "Kafka Producer Manish");
        }
        catch(Exception $e)
        {
            $this->logKafkaException($e->getMessage());
        }

**Comment by edenhill** [comment]
What is your librdkafka version? `broker.version.fallback` was added in librdkafka 0.9.1

**Comment by dsouzamanish** [comment]
Hey have i done mistake in specifying the value.
  Is it

$conf->set('broker.version.fallback', 0.8.2.2);
Instead of
$conf->set('broker.version.fallback', '0.8.2.2');

**Comment by dsouzamanish** [comment]
The version of librdkafka is 0.9.1.0

**Comment by edenhill** [comment]
So you are still getting the protocol parse failures when setting broker.version.fallback=YourBrokerVersion ?

**Comment by shbhsngh** [comment]
Hi @edenhill,
I encountered same issue.
`kafkacat  -b 10.99.199.230:9092 -C -t DRIVERS`
results:
```
%4|1527337137.816|PROTOERR|rdkafka#consumer-0| GDC-DineshK-LPT:9092/0: Protocol parse failure at rd_kafka_fetch_reply_handle:3155
%4|1527337137.816|PROTOERR|rdkafka#consumer-0| GDC-DineshK-LPT:9092/0: Remaining data after message set parse: 335 bytes
```
I am using noderdkafka which uses librdkafka and trying to access remote kafka broker (which is hosted on kubentes service) from another microservice (which is also hosted on different kubernetes service and same clluster)
Here are config detail of producer client:
```
{
  'client.id': 'kafka',
  'metadata.broker.list': '10.99.199.230:9092',
  'compression.codec': 'none',
  'retry.backoff.ms': 200,
  'message.send.max.retries': 10,
  'socket.keepalive.enable': true,
  'queue.buffering.max.messages': 100000,
  'queue.buffering.max.ms': 1000,
  'batch.num.messages': 1000000,
  'dr_cb': true,
  'api.version.request':true,
  'debug':'all',
  'broker.version.fallback':'0.8.2.2'
 }
```
Could please check what is wrong here?

**Comment by edenhill** [comment]
What librdkafka version is that?

**Comment by shbhsngh** [comment]
0.11.4
