### ISSUE TITLE
How to find total available brokers using librdkafka metadata API

### ISSUE THREAD

**Issue by mazharshaikh86** [edenhill/librdkafka#621]
Hi Magnus,

Using librdkafka metadata API, how can i find the total number of brokers available.

Suppose I have configured 6 brokers in a cluster with zero topic configured.
Then metadata in librdkafka returns 0 brokers instead of 6.

 <SX4 SYS_CTRLI0> root@sysctrl1:/opt/wbee/log# /home/vuser/metadataQuery
In Main
Metadata for all topics (from broker 4294967295 : sysctrl1.vsepx.broker.com:9092/bootstrap):
 0 brokers:
 0 topics:

Incase , if i create a topic, then the metadata returns correct broker list.

 <SX4 SYS_CTRLI0> root@sysctrl1:/opt/wbee/log# /home/vuser/metadataQuery
In Main
Metadata for all topics (from broker 4294967295 : sysctrl1.vsepx.broker.com:9092/bootstrap):
 6 brokers:
  broker 0 at CARD6:9092
  broker 5 at CARD4:9092
  broker 1 at CARD2:9092
  broker 2 at CARD3:9092
  broker 3 at CARD4:9092
  broker 4 at CARD5:9092
 1 topics:
  topic "topic1" with 6 partitions:

//Fetch metadata
    const struct rd_kafka_metadata *metadata;
    err = rd_kafka_metadata(rk, (rkt ? 0 : 1), rkt,&metadata, 5000);

**Comment by edenhill** [comment]
Which librdkafka version are you using, is this on latest master?

**Comment by edenhill** [comment]
It works for me on a cluster without topics:
```
tests$ ../examples/rdkafka_example -b $BROKERS -L
Metadata for all topics (from broker -1: localhost:37133/bootstrap):
 3 brokers:
  broker 2 at localhost:37133
  broker 4 at localhost:48350
  broker 3 at localhost:51774
 0 topics:
```
