### ISSUE TITLE
Default "produce.offset.report" to "true"?

### ISSUE THREAD

**Issue by ah-** [edenhill/librdkafka#622]
In rdkafka-dotnet I'm always returning reports on deliveries, and when "produce.offset.report" is "false" it just silently returns wrong information in the report.

I don't really want my users to have to deal with this setting, so currently I have some logic in place that just sets it to "true" no matter what.
However I think that logic might be broken in some edge cases (https://github.com/ah-/rdkafka-dotnet/issues/19#issuecomment-212640075).

What do you think about just defaulting it to "true"?

**Comment by edenhill** [comment]
The reason for not having this on by default is to avoid a O(N) loop for assigning the proper offset of each  produced message, this might seem like a micro optimization but not many applications care about the produced offset so I dont think it warrants a default change.

I suggest you keep the current logic in your code to overwrite the value.
