### ISSUE TITLE
dr_msg_cb err!=0 how to get message payload

### ISSUE THREAD

**Issue by hackerwin7** [edenhill/librdkafka#626]
hi edenhill,
I want to know, in the dr_msg_cb, if err != 0 , how can i get the msg payload however the payload is err string (err != 0).
in the original dr_cb, if err != 0 I can get the msg payload, but in the dr_msg_cb, the rd_kafka_message_t do not provide the message payload when err != 0.
so how can i get the message payload when err != 0 in the dr_msg_cb.

**Comment by edenhill** [comment]
That piece of the documentation only relates to the consumer, for the producer delivery report callbacks `payload`  is always the original message payload.
I will update the docs, thanks

**Comment by hackerwin7** [comment]
got it, thx very much
