### ISSUE TITLE
Assignment offset is always invalid

### ISSUE THREAD

**Issue by lethalman** [edenhill/librdkafka#627]
I'm using php-rdkafka commit 6ad5fea and rdkafka 0.8.6-1 compiled from librdkafka-confluent-debian-0.9.0.99 release, php 5.6.19+dfsg-0+deb8u1.

I'm not sure it's a php-rdkafka issue or rdkafka issue, but the php-rdkafka code seems quite forward.

I subscribe to a topic and receive some messages correctly, then I want to see the assignments with `$consumer->getAssignment()`. The offset however is `-1001` always and for every partition.

That said, offsets are correctly committed to the broker.

Do you have any hints on how to debug this issue?

**Comment by edenhill** [comment]
getAssignment()/assignment() will actually not return the current offsets (neither the last consumed or last committed), the offset should be ignored for that API, it just happens to reuse the TopicPartition data type for convenience.
If you want the last consumed offset use position() or for the last committed (queries the broker) use committed()

**Comment by lethalman** [comment]
Thanks. It seems php-rdkafka is not exposing those methods. Feel free to close the issue.
