### ISSUE TITLE
Does fac=TOPPAR indicate broker is contactable?

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#634]
I am looking for a way to detect that any one broker from the cluster is available - basically check that it is "probably ok" to produce.

Now the error callback will indicate "RD_KAFKA_RESP_ERR__ALL_BROKERS_DOWN" but is there a way to be told "some brokers are back"?

Is the correct way to check the log callback for fac == "TOPPAR"? Does this achieve the above?

**Comment by edenhill** [comment]
The TOPPAR facility is used for various topic-partition debug messages and cant really be relied upon for this matter.

I would like to add a proper event interface for cluster, broker, topic, partition and group availability, but Im not quite sure what that would look like. The easiest would be to just add new error codes and trigger the error_cb, but that means that existing apps will see these new "errors" that arent really errors and they might act negatively upon them, treating them like terminal errors or such.

**Comment by MaximGurschi** [comment]
I see. Good to know that there is no standard way to achieve that. Will close this question then. Thank you.

Off topic: I am tracking how much network traffic is generated by a consumer connected to a 3 node cluster (all local machines). The number I see (29kb/sec) makes me want to lower the frequency of the messages being sent by consumer's underlying logic (FetchRequest/HeartbeatRequest,etc.). What are the settings i have to modify? I tried a number of them i found in "CONFIGURATION.md" but i do not see any reduction in kb/sec. Note the consumer is idle in the sense that i do not produce any messages. I just start up the consumer and track kb/sec (via Microsoft Network Monitor).

**Comment by edenhill** [comment]
You can set the heartbeat interval with heartbeat.interval.ms (default 1s).

To slow down the fetch rate you may increase fetch.wait.max.ms and fetch.min.bytes.

See here for more info:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by MaximGurschi** [comment]
That "fetch.wait.max.ms" and "heartbeat.interval.ms" is it. By setting both to 10seconds, i've reduced the traffic to an acceptable level (under 1kb/sec). Thank you!

**Comment by edenhill** [comment]
Just make sure that the heartbeat interval is at least a third of the session timeout.
(The heartbeat request is minimal)

**Comment by MaximGurschi** [comment]
Will do that, thanks!
