### ISSUE TITLE
many test failed on kafka_2.10-0.8.1.1.tgz

### ISSUE THREAD

**Issue by dean-chen** [edenhill/librdkafka#636]
OS: ArchLinux
Compiler: c++ -> clang++ 3.7.1
librdkafka: newest in master branch
Test report
TEST 20160430060309 (bare) SUMMARY
#==================================================================#
| <MAIN>                                   |     FAILED |  62.243s |
| 0001_multiobj                            |     PASSED |   5.564s |
| 0002_unkpart                             |     PASSED |   2.109s |
| 0003_msgmaxsize                          |     FAILED |  54.241s |
| 0004_conf                                |     PASSED |   0.205s |
| 0005_order                               |     FAILED |  51.241s |
| 0006_symbols                             |     PASSED |   0.000s |
| 0007_autotopic                           |     FAILED |  47.201s |
| 0008_reqacks                             |     FAILED |  45.201s |
| 0011_produce_batch                       |     FAILED |  43.201s |
| 0012_produce_consume                     |     FAILED |  40.068s |
| 0013_null_msgs                           |     FAILED |  38.012s |
| 0014_reconsume_191                       |     FAILED |  36.012s |
| 0015_offsets_seek                        |     FAILED |  34.007s |
| 0017_compression                         |     FAILED |  32.007s |
| 0018_cgrp_term                           |     FAILED |  30.006s |
| 0019_list_groups                         |     FAILED |  28.006s |
| 0020_destroy_hang                        |     FAILED |  16.004s |
| 0021_rkt_destroy                         |     FAILED |  14.004s |
| 0022_consume_batch                       |     FAILED |  12.003s |
| 0025_timers                              |     FAILED |  10.003s |
| 0026_consume_pause                       |     FAILED |   9.003s |
| 0028_long_topicnames                     |     FAILED |   8.002s | <-- known issue: https://github.com/edenhill/librdkafka/issues/529
| 0029_assign_offset                       |     FAILED |   7.002s |
| 0030_offset_commit                       |     FAILED |   6.002s |
| 0031_get_offsets                         |     FAILED |   5.002s |
| 0033_regex_subscribe                     |     FAILED |   4.001s |
| 0034_offset_reset                        |     FAILED |   3.001s |
| 0035_api_version                         |     FAILED |   2.001s |
#==================================================================#
###
###
Makefile:24: recipe for target 'run_seq' failed
make: *** [run_seq] Error 1
[log.txt](https://github.com/edenhill/librdkafka/files/243480/log.txt)

**Comment by edenhill** [comment]
This is a known issue with the tests; some of those tests need Kafka 0.9.0.
I have a fix on the way.

**Comment by edenhill** [comment]
Fixed on master
