### ISSUE TITLE
wrong request type 10 when using rdkafka_consumer_example_cpp with kafka 0.8.1

### ISSUE THREAD

**Issue by dean-chen** [edenhill/librdkafka#637]
Hi,
  I have to use kafka 0.8.1 in my project, when using newest master branch of librdkafka, the following example binary failed:
```
[dean@dell_xps_13 examples]$ ./rdkafka_consumer_example_cpp -g consumer -b localhost:9092 test
% Created consumer rdkafka#consumer-1
2016-04-30 15:01:56.686: LOG-3-FAIL: localhost.localdomain:9092/0: Receive failed: Disconnected
2016-04-30 15:01:56.686: ERROR (Local: Broker transport failure): localhost.localdomain:9092/0: Receive failed: Disconnected
2016-04-30 15:01:57.188: LOG-3-FAIL: localhost.localdomain:9092/0: Receive failed: Disconnected
2016-04-30 15:01:57.188: ERROR (Local: Broker transport failure): localhost.localdomain:9092/0: Receive failed: Disconnected
2016-04-30 15:01:57.743: LOG-3-FAIL: localhost:9092/bootstrap: Receive failed: Disconnected
2016-04-30 15:01:57.743: ERROR (Local: Broker transport failure): localhost:9092/bootstrap: Receive failed: Disconnected
2016-04-30 15:01:57.743: ERROR (Local: All broker connections are down): 2/2 brokers are down
2016-04-30 15:01:57.966: LOG-3-FAIL: localhost.localdomain:9092/0: Receive failed: Disconnected
2016-04-30 15:01:57.966: ERROR (Local: Broker transport failure): localhost.localdomain:9092/0: Receive failed: Disconnected
Consume failed: Local: Broker transport failure
Alarm clock
```

The log in kafka log/server.log show there is a wrong request type 10. Do not know hot  to fix it.

> [2016-04-30 15:01:33,002] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
> kafka.common.KafkaException: Wrong request type 10
> 	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:57)
> 	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
> 	at kafka.network.Processor.read(SocketServer.scala:353)
> 	at kafka.network.Processor.run(SocketServer.scala:245)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-04-30 15:01:33,506] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
> kafka.common.KafkaException: Wrong request type 10
> 	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:57)
> 	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
> 	at kafka.network.Processor.read(SocketServer.scala:353)
> 	at kafka.network.Processor.run(SocketServer.scala:245)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-04-30 15:01:34,050] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
> kafka.common.KafkaException: Wrong request type 10
> 	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:57)
> 	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
> 	at kafka.network.Processor.read(SocketServer.scala:353)
> 	at kafka.network.Processor.run(SocketServer.scala:245)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-04-30 15:01:34,287] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
> kafka.common.KafkaException: Wrong request type 10
> 	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:57)
> 	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
> 	at kafka.network.Processor.read(SocketServer.scala:353)
> 	at kafka.network.Processor.run(SocketServer.scala:245)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-04-30 15:01:44,324] INFO Closing socket connection to /127.0.0.1. (kafka.network.Processor)
> [2016-04-30 15:01:56,685] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
> kafka.common.KafkaException: Wrong request type 10
> 	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:57)
> 	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
> 	at kafka.network.Processor.read(SocketServer.scala:353)
> 	at kafka.network.Processor.run(SocketServer.scala:245)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-04-30 15:01:57,188] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
> kafka.common.KafkaException: Wrong request type 10
> 	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:57)
> 	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
> 	at kafka.network.Processor.read(SocketServer.scala:353)
> 	at kafka.network.Processor.run(SocketServer.scala:245)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-04-30 15:01:57,733] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
> kafka.common.KafkaException: Wrong request type 10
> 	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:57)
> 	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
> 	at kafka.network.Processor.read(SocketServer.scala:353)
> 	at kafka.network.Processor.run(SocketServer.scala:245)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-04-30 15:01:57,966] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
> kafka.common.KafkaException: Wrong request type 10
> 	at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:57)
> 	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
> 	at kafka.network.Processor.read(SocketServer.scala:353)
> 	at kafka.network.Processor.run(SocketServer.scala:245)
> 	at java.lang.Thread.run(Thread.java:745)
> [2016-04-30 15:02:08,006] INFO Closing socket connection to /127.0.0.1. (kafka.network.Processor)

**Comment by edenhill** [comment]
rdkafka_consumer_example* are using the new high-level KafkaConsumer API which requires broker version >= 0.9.

For 0.8 you will need to use the simple legacy consumer interface (rdkafka_example) or a static partition assignment (assign())
