### ISSUE TITLE
Meaning of 'Batch size' in rdkafka_performance tool

### ISSUE THREAD

**Issue by seongyun-ko** [edenhill/librdkafka#638]
Hi, I am testing performance of Kafka consumer (c client)

If I set 'batch.size = 1' and 'queue.min.messages = 1000', will the kafka client receives a single message at a time from broker, or will it get 1000 messages in batch and show it to application layer once at a time?

How about the producer client? will it batch up to 'queue.buffering.max.messages'?

**Comment by edenhill** [comment]
`batch.size` is not a librdkafka property.

The librdkafka consumer will maintain a local queue of fetched messages from the broker, this increases performance and reduces latency. This local queue size is limited by >= `queued.min.messages` and <= `queued.max.message.kbytes`.

As for the the producer it will wait up to `queue.buffering.max.ms` or `batch.num.messages` (whichever is reached first) to create a batch that is then sent to the broker.

**Comment by fritzblue** [comment]
@edenhill But, but, if message sizes are heterogenous, number of messages is a poor and unpredictable way of measuring batch sizes. Why not just use byte sizes like the official Java producer/consumer?

**Comment by edenhill** [comment]
librdkafka predates the Java producer, `batch.num.messages` was found in the original Scala producer and librdkafka followed suite.
I agree that an additional `batch.size` property would make sense (but I think the Java producer default of 16K is too low, should probably be same as maximum message size by default - i.e., try to create as large batches as possible while honouring the latency (linger.ms) config)

**Comment by fritzblue** [comment]
Really appreciate the background and willingness to consider an additional `batch.size` property!

I agree with your proposed defaults.

**Comment by edenhill** [comment]
`batch.size` is now available on master

**Comment by fritzblue** [comment]
Awesome! 🙌Love the quick feedback cycle!
