### ISSUE TITLE
Consumer groups

### ISSUE THREAD

**Issue by oryahud** [edenhill/librdkafka#639]
Hi,

I created a consumer and set a group id named "bla" like this:

/* Set configuration properties. */
confRes = mConf->set("group.id", "bla", errString);

/* Validity check */
if (confRes != Conf::CONF_OK)
	return HANDLER_STATUS_INIT_ERROR;

/* Create consumer using accumulated global configuration. */
mConsumer = Consumer::create(mConf, errString);

/* Validity check */
if (mConsumer == nullptr)
	return HANDLER_STATUS_NULL_ERROR;

The problem is that when I try to get the consumer group from code or the group list from command line I found nothing,
I tried:
"mConsumer->memberid()" from code -> retruns empty string.
and
./kafka-consumer-groups.sh --zookeeper 127.0.0.1:2181 --describe --group bla
 -> returns "No topic available for consumer group provided"

Thanks for help !!!
Or.

**Comment by edenhill** [comment]
The consumer (group) is only registered (and created) when you issue subscribe() and the memberid() will only return after a succesful rebalance (e.g., rebalance_cb with err == PARTITIONS_ASSIGNED)

**Comment by oryahud** [comment]
Thanks for the quick replay ! 

Unfortunately my consumer doesn't have subscribe() method.

Can you please guide me how should I subscribe ?

Thanks a lot !

**Comment by edenhill** [comment]
For the legacy consumer (Consumer class) you start consuming with start(), this works with all broker versions.

For broker version >= 0.9 you should use the high-level KafkaConsumer class which has the subscribe() and assign() calls.

**Comment by oryahud** [comment]
I used legacy consume, after the code above I did run:

ErrorCode resp = mConsumer->start(mTopic, mPartition, startOffset);

/* Validity check */
if (resp != ERR_NO_ERROR)
	return HANDLER_STATUS_INIT_ERROR;

But I see no groups.

Thanks.

**Comment by edenhill** [comment]
The legacy/simple consumer does not use groups, you will need to use the high-level KafkaConsumer for that, which requires broker >=0.9

**Comment by oryahud** [comment]
Great, it's working !

Last thing, how can I monitor my active consumers from code ?

Thanks.

**Comment by edenhill** [comment]
What do you mean by monitor?

**Comment by oryahud** [comment]
After I startrd all my consumers I want to make sure that they are running.

**Comment by edenhill** [comment]
You generally dont need to monitor the consumer instance itself, you should be able to rely on it continuing to function. For actual application monitoring that is outside the scope of librdkafka, but librdkafka provides a statistics API that gives you stats and feedback on the internal state of librdkafka. See here:
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L441
and here:
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L413

**Comment by oryahud** [comment]
Thanks again for you amazing help !
