### ISSUE TITLE
enum keyed message

### ISSUE THREAD

**Issue by itayB** [edenhill/librdkafka#640]
Just wonder if the key_pointer capability is librdkafka extension or kafka officially supported.

I'm using librdkafka in my C++ for consume&produce keyed messages - where my keys are enum (for efficiency purpose).
Recently, I've added node.js producer (using [kafka-node](https://www.npmjs.com/package/kafka-node)) and I didn't see option to send there keyed message which is not string.
for more info: http://stackoverflow.com/questions/36979586/kafka-node-send-enum-key-message-instead-of-string-key

**Comment by edenhill** [comment]
The Kafka protocol specifies the message key as arbitrary opaque binary bytes, thus it can contain any kind of data and there is no defined format for it, that is up to the application to define.

**Comment by itayB** [comment]
OK. Great, thanks for the quick answer!
