### ISSUE TITLE
error of Local: Bad message format

### ISSUE THREAD

**Issue by microwish** [edenhill/librdkafka#641]
In dr_msg_cb, rd_kafka_message_t.err is not zero. The error is "Local: Bad message format".

I used the latest master branch and set broker.version=0.8.2.2 explicitly in the conf file for producer.

**Comment by edenhill** [comment]
Have you checked the broker logs for some error indication?

**Comment by edenhill** [comment]
Also, are there any logs from librdkafka?

**Comment by microwish** [comment]
I made a test that everything worked quite well when I used an old version of librdkafka.

**Comment by microwish** [comment]
And In my test, I didn't set broker.version.

**Comment by edenhill** [comment]
Please provide more details:
 * Is there anything in the broker logs?
 * Enable `debug=broker,msg,queue` in the producer, are there any related logs in there?
 * What is your client configuration?

**Comment by microwish** [comment]
Okay, I'll take a test.

**Comment by edenhill** [comment]
Please try with the latest master, Ive made some fixes around protocol compatibility.
Make sure to set broker.version.fallback= properly.

**Comment by microwish** [comment]
It works well now.
I remember that the property name was broker.version before.
