### ISSUE TITLE
Failed to connect to broker at locakhost

### ISSUE THREAD

**Issue by AnandhamK** [edenhill/librdkafka#642]
After installing librdkafka, phpkafka i am getting this error:

%3|1462365636.982|FAIL|rdkafka#consumer-1| localhost:9092/bootstrap: Failed to connect to broker at localhost:9092: Permission denied

**Comment by edenhill** [comment]
The connect(2) man page on Linux says:
>        EACCES, EPERM
>              The user tried to connect to a broadcast address without  having
>              the  socket  broadcast  flag  enabled  or the connection request
>              failed because of a local firewall rule.

**Comment by AnandhamK** [comment]
Thanks..
Now working fine.
