### ISSUE TITLE
Feature Request: Replace existing c snappy port with officially supported snappy c bindings by Google.

### ISSUE THREAD

**Issue by webmakersteve** [edenhill/librdkafka#645]
We're currently experiencing a difficult to trace error. When librdkafka sends a batch of messages to our kafka server, certain messages cause the batch to not be decompressable. After looking into it, I saw that the version of snappy being used is 1.1.0 which is a few years old.

Is porting over the snappy implementation to the new snappy bindings something you're interested in / working on, or would take a PR for?

Thanks for the great library.

**Comment by edenhill** [comment]
That sounds serious.
Do you have a test case that triggers this issue? I would like to reproduce it.

The reason for using Andy's snappy-c is that the official Snappy C library lacked a streaming or iovec based interface which means it requires an extra level of allocation and copying.
The underlying C++ library seems to support it through the use of Sinks and Sources, but this is not reflected in the C API unfortunately.

**Comment by webmakersteve** [comment]
I'm in the process of making a test case for this. It's a little complicated because there are a lot of factors. We're only seeing this on our system when the Replica Sets try to decompress the message and when the batches get to a certain size with certain formatted messages. I'm going to try to make a docker environment that can simulate the conditions and see if I can isolate the test.

**Comment by edenhill** [comment]
Which broker version is this?

**Comment by webmakersteve** [comment]
0.9.2. We were able to reproduce the error using kafkacat with these messages (the ones specifically in the *-metrics.topic file)

[messages.zip](https://github.com/edenhill/librdkafka/files/255889/messages.zip)

Here is the command

```sh
for n in {0..100000}; do cat telemetry-v1-client-general-metric.topic; done | \
   kafkacat -P -z snappy \
   -X batch.num.messages=1000000 -X queue.buffering.max.messages=1000000 \
   -X queue.buffering.max.ms=30000 -X socket.send.buffer.bytes=1048576 \
   -b localhost:9092 -t vmstat 
```

This is on a 3 node cluster with a topic that has 3 partitions and a replication factor of 3.

**Comment by webmakersteve** [comment]
Just to add some information here, it appears to work fine using GZIP instead of snappy.

**Comment by edenhill** [comment]
Have tried to reproduce this using the provided data set to no avail.

**Comment by edenhill** [comment]
Reproduced!

**Comment by webmakersteve** [comment]
Awesome! Happy to hear it. Let me know any other way I can help.

**Comment by edenhill** [comment]
This is uncannily similar:
https://issues.apache.org/jira/browse/KAFKA-3764

**Comment by edenhill** [comment]
This is most likely a regression in Kafka 0.10.0.0 / trunk, see KAFKA-3764.

Have not been able to reproduce on 0.9.0.1

**Comment by edenhill** [comment]
upstream issue: https://github.com/xerial/snappy-java/issues/142
