### ISSUE TITLE
Setting session.timeout.ms to another value crashes the consumer

### ISSUE THREAD

**Issue by deepseer** [edenhill/librdkafka#646]
Description
===========
When this parameter is set to a value other than its default value (30000 ms), it makes rdkafka_consumer_example_cpp spin up before the first RebalanceCB, which should be called  when initializing the consumer.

How to reproduce
================
I tried to set it with `conf->set("session.timeout.ms", std::string(buffer), errstr)` in my own program, but it failed to work. Later I found that the problem had already occurred in the examples.

ubuntu 14.04 x64
librdkafka-master (April 30, after the patch that fixed the unassign() bug)
kafka 0.9.0.1, default settings, created topic "cl" with "--partitions 3 --replication-factor 1"
zookeeper 3.4.6, default settings

./rdkafka_consumer_example_cpp -g mygroup -b localhost:9092 -X session.timeout.ms=30000 cl
It worked as expected.
> % Created consumer rdkafka#consumer-1
> RebalanceCb: Local: Assign partitions: cl[0], cl[1], cl[2], 
> a
> d
> b
> e
> c
> ..........

./rdkafka_consumer_example_cpp -g mygroup -b localhost:9092 -X session.timeout.ms=25000 cl
It was stuck here, and received no messages from the producer:
> % Created consumer rdkafka#consumer-1

When Ctrl+C was pressed, nothing happened. Only kill -9 can terminate it.

**Comment by edenhill** [comment]
I can't reproduce this on trunk nor 0.9.0.1.

I start the first consumer with session timeout 30s, wait for it to get an assignment, then start the 25s consumer and the group is evenly balanced pretty quickly.

**Comment by deepseer** [comment]
I mean, start only the 25s consumer and see whether it works. BTW, what OS did you use?

**Comment by edenhill** [comment]
Can't reproduce, everything works as expected:
```
[TRIVUP:librdkafkaInteractiveBrokerVersionTests@0.9.0.1] maglun@uddub:/var/maglun/src/librdkafka/tests$ ../examples/rdkafka_consumer_example_cpp -g mygroup -b $BROKERS -X session.timeout.ms=25000 test
% Created consumer rdkafka#consumer-1
RebalanceCb: Local: Assign partitions: test[0], test[1], test[2], test[3], 
^CRebalanceCb: Local: Revoke partitions: test[0], test[1], test[2], test[3], 
% Consumed 0 messages (0 bytes)
```

**Comment by deepseer** [comment]
Strange... After rebuilding with the newest master branch today, this problem disappeared.
I'll close this issue.
