### ISSUE TITLE
Is there API to determine whether KAFKA is running ?

### ISSUE THREAD

**Issue by oryahud** [edenhill/librdkafka#648]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information (if applicable):

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Not specifically, but you can use the metadata() API to query the cluster, it doesnt have side effects.

**Comment by oryahud** [comment]
Thank! It's working.
