### ISSUE TITLE
Can i use producer and consumer in one process at the same time?

### ISSUE THREAD

**Issue by shawn246** [edenhill/librdkafka#649]
Apache Kafka version: 0.8.2

Hi,
I create one c++ producer and one c++ consumer on same topic separately(in different threads, with different RdKafka::Conf) in same process. While running both at the same time, i get core dump from calling poll with producer. But it is ok to run producer or consumer independently. I have no idea whether there is any global stuff in library shared by all the modules or do i need to modify the configuration to support this?

**Comment by edenhill** [comment]
That should be okay, in fact the librdkafka regression test suite runs in parallel.

Please try with latest librdkafka master and provide output from gdb of the crash.

**Comment by shawn246** [comment]
After using the latest librdkafka.a without any code being modified, the consumer can not work at all. The following is the error information printed by the library. And the same error information appeared when i forgot to set the correct kafka version into global RdKafka::Conf at the first time. I think it's the protocol issue.

%4|1462785622.283|PROTOERR|rdkafka#producer-2| 10.10.252.77:9092/3: Protocol parse failure at rd_kafka_produce_reply_handle:1779
%4|1462785622.284|PROTOERR|rdkafka#producer-2| 10.10.252.77:9092/3: expected 4 bytes > 0 remaining bytes
%4|1462785622.485|PROTOERR|rdkafka#producer-2| 10.10.252.77:9092/3: Protocol parse failure at rd_kafka_produce_reply_handle:1779
%4|1462785622.485|PROTOERR|rdkafka#producer-2| 10.10.252.77:9092/3: expected 4 bytes > 0 remaining bytes
%4|1462785622.589|PROTOERR|rdkafka#producer-2| 10.10.252.77:9092/3: Protocol parse failure at rd_kafka_produce_reply_handle:1779
%4|1462785622.589|PROTOERR|rdkafka#producer-2| 10.10.252.77:9092/3: expected 4 bytes > 0 remaining bytes

PS: I do not describe the way i use consumer clearly. I use RdKafka::Consumer and RdKafka::Queue to consume messages from several partitions of one topic.

**Comment by edenhill** [comment]
You will need to set broker.version.fallback= according to your broker version, so i your case it looks like broker.version.fallback=0.8.2.2.

See here for more info:

https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by shawn246** [comment]
It works. Thanks a lot!

**Comment by shawn246** [comment]
One more question, is the "produce" function thread-safe, There are multiple threads producing messages.

**Comment by edenhill** [comment]
Yes, it is.
