### ISSUE TITLE
Backward Offset

### ISSUE THREAD

**Issue by incessantier** [edenhill/librdkafka#651]
Edenhill!  

We are using the "old" C++ Consumer, and are trying to consume "n" messages from the end of a partition.  Our current idea is to consume the last message, get the offset, and look backward from that offset to start a second subscription.  But then we saw the "OffsetTail" call in Consumer and said "yipee!"  But how does that call work?  it does not ask for a specific topic/partition, so how does it know what the current end of the partition is?

**Comment by edenhill** [comment]
OffsetTail() simply converts the given relative offset to an internal notation of the same, so you pass the return value of OffsetTail() as you would pass an absolute or logical (BEGINNING, END) offset to start().

e.g.:

consumer->start(topic, partition, consumer->OffsetTail(1000));


This is maybe the most clear in the C code:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1626
