### ISSUE TITLE
what time to support Consumer group and Consumer offset?

### ISSUE THREAD

**Issue by hzhxxx** [edenhill/librdkafka#653]
### Description
===========

rt

### How to reproduce
================

Checklist
=========
Please provide the following information (if applicable):

 - [ ] librdkafka version (release number or git tag):
 - [x] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by hzhxxx** [comment]
./rdkafka_example -X list|grep "group.id"
./rdkafka_example -P -b localhost:9092 -t bbb -p 2 -X group.id=test-consumer-group
./rdkafka_example -P -b localhost:9092 -t bbb -p 2 -X group.id=test-consumer-group
but property group.id,offset.store.method and offset.store.path is not invalid

**Comment by hzhxxx** [comment]
# ./rdkafka_example -C -b localhost:9092 -t bbb -p 0 -X group.id=bbb -s stored -X offset.store.method=local
% Invalid value for configuration property "offset.store.method"

**Comment by edenhill** [comment]
Kafka consumer groups (broker version 0.9 or later) is available in librdkafka.
See examples/rdkafka_consumer_example.c (or .cpp)

**Comment by hzhxxx** [comment]
./rdkafka_example -P -b localhost:9092,localhost:9093 -t bbb -p 0  -X group.id=bbb

consumer group
./rdkafka_consumer_example -b localhost:9092,localhost:9093 bbb:0 -g bbb
./rdkafka_consumer_example -b localhost:9092,localhost:9093  bbb:0 -g bbb

run two process,the two process recieve the same message

**Comment by edenhill** [comment]
What librdkafka version are you using?

**Comment by zjunwang** [comment]
hello, edenhill
I has a problem about this,
1、broker version 0.9 or later is available in librdkafka, which version of librdkafka? 0.9.1 or later?
2、how can i know which librdkafka version should be compatible to broker? example broker 0.8.2.1
3、I see your code, in librdkafka 0.8.6 can support consumer group, which version of broker should to choose?
thanks very much.

**Comment by edenhill** [comment]
@zjunwang Please see this wiki page:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by zjunwang** [comment]
hello， edenhill
thanks for your answer, another question:
if older version not support consumer group, I setup two client, consume same topic and same partition, suppose has 80 messages, in this case, client 1 can consume 80 messages or about 40 messages? thanks

**Comment by zjunwang** [comment]
I think client1 and client2 will received the same message

**Comment by edenhill** [comment]
Balanced consumer (e.g., only one consumer will see a single message) requires broker version 0.9 or later.

**Comment by zjunwang** [comment]
thank you , I Known

**Comment by zjunwang** [comment]
hello edenhill : 
thanks for your answer, still has 2 problems:
1、if we choose RD_KAFKA_OFFSET_METHOD_FILE and offset.store.path is not exist, in this case, we consume message from where? beginning or end?
2、if offset.store.path not configured, you will use file topic-partition.offset or topic-partition-groupid.offset, but in first running a program, these offset file is not exists, so consume from which offset, begining or end?
thanks

**Comment by zjunwang** [comment]
https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management 
I See this wiki, but I don't know if offset file not exist, librdkafka will do what, consume message from begin or end?

**Comment by edenhill** [comment]
See the topic config property `auto.offset.reset`

**Comment by zjunwang** [comment]
thanks edenhill

**Comment by zjunwang** [comment]
hello, @edenhill
how can I get offset from broker by given a message time, thanks

**Comment by edenhill** [comment]
That is not currently implemented, but you can open a new issue to file an enhancement request for it.
