### ISSUE TITLE
Test: connect to multiple clusters

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#654]
It is not a supported use case but it  happens from time to time, so we need to make sure that we dont spin out of control completely. Actional operation is undefined though.

Use trivup.

**Comment by MaximGurschi** [comment]
Can you clarify this, please? I use the RD-kafka .net wrapper and create multiple producer instances per cluster. Is that something that is not supported? Or is it a single producer instance given addresses of brokers from different clusters that is not supported?

**Comment by edenhill** [comment]
@MaximGurschi This is the latter case where a single rdkafka instance is wrongfully configured to connect to brokers from different clusters, this is a configuration error and completely unsupported, but this issue is here to track that it should be somewhat gracefully handled.

With different rdkafka instances you are free to connect to the same or other clusters as you wish, they are completely separated.

**Comment by MaximGurschi** [comment]
Thanks for the confirmation!
