### ISSUE TITLE
the consumers group problem

### ISSUE THREAD

**Issue by hzhxxx** [edenhill/librdkafka#655]
Description
===========

the only Producer by rdkafka_example to put message to topic "bbb"  partition 0
run two consumer in the same group "bbb" and topic "bbb" partition 0 
two consumers(same group) receive the same message. "11111","22222","33333"

How to reproduce
================

# ./rdkafka_example -P -b localhost:9092,localhost:9093,six.dev3:9092 -t bbb -p 0
% Type stuff and hit enter to send
11111
% Sent 5 bytes to topic bbb partition 0
22222
% Sent 5 bytes to topic bbb partition 0
% Message delivered (5 bytes): 11111
33333
% Sent 5 bytes to topic bbb partition 0
% Message delivered (5 bytes): 22222

% Sent 0 bytes to topic bbb partition 0
% Message delivered (5 bytes): 33333
^C% Message delivered (0 bytes):

# ./rdkafka_consumer_example -b localhost:9092,localhost:9093,six.dev3:9092 bbb:0 -g bbb
% Assigning 1 partitions
% Consumer reached end of bbb [0] message queue at offset 1823
% Message (topic bbb [0], offset 1823, 5 bytes):
Message Payload hexdump (5 bytes):
00000000: 31 31 31 31 31                                   11111           
% Consumer reached end of bbb [0] message queue at offset 1824
% Message (topic bbb [0], offset 1824, 5 bytes):
Message Payload hexdump (5 bytes):
00000000: 32 32 32 32 32                                   22222           
% Consumer reached end of bbb [0] message queue at offset 1825
% Message (topic bbb [0], offset 1825, 5 bytes):
Message Payload hexdump (5 bytes):
00000000: 33 33 33 33 33                                   33333           
% Consumer reached end of bbb [0] message queue at offset 1826
% Message (topic bbb [0], offset 1826, 0 bytes):
Message Payload hexdump (0 bytes):
% Consumer reached end of bbb [0] message queue at offset 1827
^C% Consumer closed

# ./rdkafka_consumer_example -b localhost:9092,localhost:9093,six.dev3:9092 bbb:0
% Assigning 1 partitions
% Consumer reached end of bbb [0] message queue at offset 1823
% Message (topic bbb [0], offset 1823, 5 bytes):
Message Payload hexdump (5 bytes):
00000000: 31 31 31 31 31                                   11111           
% Consumer reached end of bbb [0] message queue at offset 1824
% Message (topic bbb [0], offset 1824, 5 bytes):
Message Payload hexdump (5 bytes):
00000000: 32 32 32 32 32                                   22222           
% Consumer reached end of bbb [0] message queue at offset 1825
% Message (topic bbb [0], offset 1825, 5 bytes):
Message Payload hexdump (5 bytes):
00000000: 33 33 33 33 33                                   33333           
% Consumer reached end of bbb [0] message queue at offset 1826
% Message (topic bbb [0], offset 1826, 0 bytes):
Message Payload hexdump (0 bytes):

Checklist
=========
Please provide the following information (if applicable):

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You are specifying both topic and partition to your consumers which means it just runs assign() directly and does not do subscribe() to join a consumer group.

So change `bbb:0` to just `bbb` in your consumer examples and you should be fine.
