### ISSUE TITLE
About Producer PARTITION_UA and partitioner_cb property

### ISSUE THREAD

**Issue by jerves** [edenhill/librdkafka#656]
Hello everyone!
Here is my question:
    If I never set partitioner_cb when I created a producer and produce  messages with PARTITION_UA , whether or not  the messages will be delivering randomly to partitions?

**Comment by edenhill** [comment]
librdkafka master uses the consistent_random as the default partitioner, see here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1293

**Comment by jerves** [comment]
Got it! Thanks @edenhill

**Comment by helloworldagain** [comment]
when I created a producer with "PARTITION_UA",it works well and I can push my message into server. And then when I use a Consumer use PARTITION_UA for a partition value，it tells “Failed to start consumer: Local: Unknown partition” . How can I know the partition value when the producer start with "PARTITION_UA" which is not specific partition value.

**Comment by treziac** [comment]
You can't use PARTITION_UA for consumer. Either assign a specific partition, or in your case I assume all partitions, either use subscription  with a specific groupid so you will automatically get assigned to all partitions.

**Comment by horchi** [comment]
where I can find a documentation about how to consume all messages of a specific topic whose produced with PARTITION_UA?
Or in other words how the partition for RdKafka::KafkaConsumer::assign has to be specified to consume all messages of one topic and ALL it's partitions?

**Comment by horchi** [comment]
it seams that a RdKafka::KafkaConsumer::subscribe is working without specifying a partition, but I use assign since I like to start at a specific offset.

**Comment by edenhill** [comment]
assign() requires you to specify the partitions manually and then starts consuming them immedidately.
subscribe() makes the consumer join a balanced consumer group, wait for an assignment, and then start consuming - in this case you can register a rebalance callback to intercept the assigned partitions and update their offsets to your liking and then calling assign().

**Comment by horchi** [comment]
okay thx! And the easy way by subscribe is only possible if I don't have to specify an start offset?

**Comment by edenhill** [comment]
if you subscribe without a rebalance callback it will start consuming at the last committed offset or if that is not available the `auto.offset.reset` config policy.

With a rebalance callback you must call assign() yourself and can thus set the starting offsets.

**Comment by horchi** [comment]
Okay understood. 
And the required 'initial' offset has to be passed to the callback until I have to call assign there? 

Sorry about so many questions I'm quite new to the hole kafka stuff

**Comment by edenhill** [comment]
It is optional to modify the offsets of the assigned partitions in your rebalance callback, if not it will used committed offsets or auto.offset.reset.

**Comment by horchi** [comment]
yes I understood this point, but unfortunately there are situations where I need the offset.
In the situations the offset is needed I have to pass it in some way to the callback and use it there for the first initial assign call. But hat is on the next call of the callback and subsequent assign calls (other partition), is the offset than handled automatically and continue consuming on the current position? 

For example:
- all messages are already processed by this consumer
- a user decide to start processing the messages of the last two hours again and therefore restart the consumer with an offset of now - 2 hours (e.g. 200 messages)
- on the first rebalance callback the offset is calculated and set by calling assign
- then consuming starts at the correct offset and processes and commit the messages again
- now e.g. the fist 100 of the 200 messages are processed and the rebalance callback appears again and assign is called  did I have to specify an offset again or is the actual position persistent and the consume continue with the 101th message? Specially against the background that the messages of this last 2 hours still committed before the reprocessing was started.

**Comment by edenhill** [comment]
The offset is reset on each rebalance, and if you don't do anything it will use the committed offset.
