### ISSUE TITLE
Publisher does not get all offset of published messages, just the last one

### ISSUE THREAD

**Issue by danny794** [edenhill/librdkafka#658]
Description
===========

Hey! I have a Kafka server running on a machine and I want to publish messages to it and then check the offsets of the messages. However, if I publish a batch of 10 messages (this number is irrelevant, I tried with others and the behaviour is the same) I get only the last message's offset the other ones are 0. If I use the Kafka java consumer client I can see that all my messages are published, but I don't understand why am I missing the offsets. 

How to reproduce
================
include < librdkafka/rdkafkacpp.h >

#include < atomic >
#include < chrono >
#include < cstdlib >
#include < cstring >
#include < cinttypes >
#include < string >
#include < thread >

std::atomic_bool run(true);

class KafkaDeliveyCb : public RdKafka::DeliveryReportCb {
 public:
  void dr_cb(RdKafka::Message &msg) override {
    run = false;
    printf("Message was delivered! %" PRId64 "\n", msg.offset());
  }
};

class KafkaEventCb : public RdKafka::EventCb {
 public:
  void event_cb(RdKafka::Event &event) override {
    printf("Event was triggered!\n");
  }
};

int main (int argc, char **argv) {
  std::string errorMessage;
  std::string topicName("88");
  int partition = 2;
  RdKafka::Conf *conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);
  RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);
  RdKafka::DeliveryReportCb *deliveryCb = new KafkaDeliveyCb();
  RdKafka::EventCb *eventCb = new KafkaEventCb();
  conf->set("metadata.broker.list",
            "cloud-vm-47-43:9092",
            errorMessage);
  conf->set("dr_cb", deliveryCb, errorMessage);
  conf->set("event_cb", eventCb, errorMessage);

  RdKafka::Producer *producer =
    RdKafka::Producer::create(conf, errorMessage);
  RdKafka::Topic *topic = RdKafka::Topic::create(
    producer,
    topicName,
    tconf,
    errorMessage);

  int size = 10;
  char * message = new char[size];
  memset(message, '\0', size);
  message[0] = 'T';
  message[1] = 'E';
  message[2] = 'S';
  message[3] = 'T';

  for (int i = 0; i < 10; i++) {
    RdKafka::ErrorCode err = producer->produce(
      topic,
      partition,
      RdKafka::Producer::RK_MSG_COPY,
      message,
      size,
      nullptr,
      0,
      (void*) message);
  }
  while (run) {
    printf("Spinnin'\n");
    std::this_thread::sleep_for(std::chrono::seconds(5));
    producer->poll(0);
  }
  delete topic;
  delete producer;
  delete conf;
  delete deliveryCb;
  delete message;
  return 0;
}

Output:
Spinnin'
Message was delivered! 0
Message was delivered! 0
Message was delivered! 0
Message was delivered! 0
Message was delivered! 0
Message was delivered! 0
Message was delivered! 0
Message was delivered! 0
Message was delivered! 0
Message was delivered! 20

Checklist
=========
Please provide the following information:
Using git commit: b1e88ae78c271d4c6caf12762d463ef4ea1bcbec
Apache Kafka version: 0.9.0.1
OS: Ubuntu 14.04.3 LTS

**Comment by edenhill** [comment]
This is an optimization in the producer code.
To enable producer per-message offset reports set the topic config property `produce.offset.report` to `true`.

**Comment by danny794** [comment]
I checked now and it works! Thanks! 😃 Is it a big penalty if I use this option set to true?

**Comment by edenhill** [comment]
Nope, the penalty is minimal, you should be fine.
