### ISSUE TITLE
Producer throws warnings. [PROTOERR]

### ISSUE THREAD

**Issue by keajer** [edenhill/librdkafka#661]
Description
===========
When sending some protobuf messages to brokers, getting following warning messages:
```
WARNING:pykafka.rdkafka._rd_kafka:pykafka.rdkafka#producer-1 [PROTOERR] **.**.**.**:9092/1: Protocol parse failure at rd_kafka_produce_reply_handle:1779
WARNING:pykafka.rdkafka._rd_kafka:pykafka.rdkafka#producer-1 [PROTOERR] **.**.**.**:9092/1: expected 4 bytes > 0 remaining bytes
```
seems serious, but message does send successfully.
Can someone please explain?
Thanks

**Comment by edenhill** [comment]
What is your broker version and librdkafka version?

(the issue template includes these questions at the bottom..)

**Comment by keajer** [comment]
kafka: 0.8.2.2
librdkafka: librdkafka-0.9.0.100

**Comment by edenhill** [comment]
See this:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility
