### ISSUE TITLE
Symbol referencing errors when linking against librdkafka on Solaris 10

### ISSUE THREAD

**Issue by jocoda** [edenhill/librdkafka#662]
Hi Magnus,

 - librdkafka version (release number or git tag): latest master 18/05/2016
 - System Information: SunOS 5.10 Generic_141444-09 sun4u sparc SUNW,Sun-Fire-V240
 - gcc version 4.9.0

I get the following build error when linking my application with librdkafka on Solaris 10.

Undefined                       first referenced
 symbol                             in file
rd_kafka_message_errstr             /usr/local/lib/librdkafka.so
ld: fatal: Symbol referencing errors. No output written to kp_tester
collect2: ld returned 1 exit status

Changing line to last_line on line 20 of lds-gen.py seems to resolve the issue by ensuring rd_kafka_message_errstr is omitted from src/librdkafka.lds (was written previously) but not sure whether this is the best solution here? 

Could you  advise?
Thanks.

**Comment by edenhill** [comment]
That's weird, `./lds-gen.py < src/rdkafka.h | grep errstr` includes that symbol when it matches on `line`, but not with your `last_line` modification.
Are you saying you get the opposite behaviour?

**Comment by jocoda** [comment]
Aargh!  Sorry my description is wrong.  I see the same behaviour as you re lds-gen.py script.
 
My application builds when rd_kafka_message_errstr is **omitted** from src/librdkafka.lds.

**Comment by edenhill** [comment]
ah, yeah, you are right, static functions should not be in the symbol file, so your fix is correct.

**Comment by jocoda** [comment]
Have updated the original issue comment to reflect the actual behaviour.

**Comment by edenhill** [comment]
give master a try now

**Comment by jocoda** [comment]
Yes fixed now.  Thanks.
