### ISSUE TITLE
no func to set queue.buffering.max.messages

### ISSUE THREAD

**Issue by lmxhappy** [edenhill/librdkafka#663]
Description
===========
There is no function to set the producer parameter  in the master trunk and Latest release 0.8.6. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):0.8.6
 - [ ] Apache Kafka version: kafka_2.9.2-0.8.1.1
 - [ ] librdkafka client configuration:
 - [ ] Operating system: centos5.7
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Use `rd_kafka_conf_set(conf, "queue.buffering.max.messages", "yourvalue", errstr, sizeof(errstr))` or the corresponding C++ function `conf->set()`

**Comment by lmxhappy** [comment]
rd_kafka_conf_res_t rd_kafka_conf_set (rd_kafka_conf_t *conf,
				       const char *name,
				       const char *value,
				       char *errstr, size_t errstr_size) {
	return rd_kafka_anyconf_set(_RK_GLOBAL, conf, name, value,
				    errstr, errstr_size);
}

the 1st parameter is defaultly _RK_GLOBAL instead of _RK_GLOBAL |_RK_PRODUCER that is right.

**Comment by edenhill** [comment]
Yes, that is right, the instance type isnt known at the time conf_t is being set up.

What issues are you encountering?

**Comment by lmxhappy** [comment]
The setting of the parameter "queue.buffering.max.messages" is in rd_kafka_properties[] with _RK_GLOBAL |_RK_PRODUCER, so if it is to be changed it should be to call  rd_kafka_anyconf_set(_RK_GLOBAL|_RK_PRODUCER, conf, name, value,
errstr, errstr_size).

However, there is no func that rd_kafka_anyconf_set by passing the parameter _RK_GLOBAL|_RK_PRODUCER. That is to say, if to set the parameter "queue.buffering.max.messages", a self-defined function is needed.

**Comment by edenhill** [comment]
I'm not really sure what you are trying to do.
The code works as intended as far as I know and so does "queue.buffering.max.messages".
What is it that you are trying to achieve?

**Comment by lmxhappy** [comment]
rd_kafka_topic_conf_set(topic_conf,   "produce.offset.report",   "1000000", errstr, sizeof(errstr)); can set  "produce.offset.report" successfully? I try and it does work.

**Comment by edenhill** [comment]
Please see CONFIGURATION.md for expected values, that property takes a bool
