### ISSUE TITLE
KafkaConsumer bottleneck in process with single thread consumer - what is best implementation strategy for multiple threads for multiple consumers ?

### ISSUE THREAD

**Issue by jlewis111** [edenhill/librdkafka#666]
I’m using the High-Level C++ API [v 0.9.1].

I have a test Producer and a test Consumer with a single Partition and a single Kafka Broker with no replication of partitions. I can send messages on a single Topic at a rate of around 160MB/s, but the consumer can only manage to consume at around 35 MB/s.

All of the processes are on the same box.

In order to try and increase the overall consumption rate, I am considering moving to having multiple consumer threads in the test Consumer.

I am considering the following scenarios:

1) Keeping just 1 partition, have the same single KafkaConsumer object consuming on 5 separate threads

2) Keeping just 1 partition, having 5 KafkaConsumer objects each consuming the same partition on their own thread (1 object per thread, 5 threads in total)

3) Having 5 partitions , having 5 KafkaConsumer objects each consuming on their own partition and their own thread (1 object per thread, 5 partitions, 5 threads in total). The producer sends to each partition in round-robin.

Are each of the above scenarios valid ?

What approximate overall total consumption rate is expected for each scenario ?

**I tried an initial test of case two to 2 threads and 2 KafkaConsumer objects and 1 partition but noticed that 99.9% of the messages were being consumed on on eof the two threads.** 

I was calling KafkaConsumer:: consume(1000) in loops in each of the two threads.

Is this the expected behaviour or is there a more appropriate way of consume from multiple threads to get the fastest consumption rate within a single process? What is the best way of implementing this ?
- [x] librdkafka version (release number or git tag): 0.9.1
- [ ] Apache Kafka version: 0.9.0.1
- [ ] librdkafka client configuration: [optimised for throughput rather than latency]
- [ ] Operating system: RHAT 5.x

**Comment by edenhill** [comment]
What's your average message size?
Have you tried consuming the same topic and partition using `examples/rdkafka_performance -b yourbroker -t yourtopic -p onepartition -C -o beginning -e`? What rate is it saying?
When consuming, is there CPU load? If so, on broker or client or both?

**Comment by jlewis111** [comment]
Thanks for the prompt response.
The message size is fixed at 100 bytes.
I will get back with answers on your other questions.

**Comment by jlewis111** [comment]
OK, I've run the rdkafka_performance and tried out various combinations of settings.

I confirm the following:

- If I run with a Producer without a Consumer, I can send at 125 MB/s.
- If I run with a Consumer without a Producer, I can receive at 150 MB/s.
- If I run with a Producer and Consumer, I can send at 120 MB/s and receive at 115 MB/s.

In the last case, it takes about 6 seconds for the Consumer to reach the rate of 115 MB/s and it appears to increase from 0 MB/s to 115 MB/s in a linear-like fashion over that time.

The 6 seconds corresponds to the amount fo time the Producer is sending the messages - 12m messages at 2m a second.

In my original test case, my test app runs both the Producer and Consumer for about of the order of 10 milliseconds (a small batch of 10,000 messages), so if there were some initial overhead in getting up to top speed (as was subsequently observed with rdkafka_performance) then this would account for the behaviour I was seeing.

So I think the issue I had appears to be resolved - thanks for your support.


I would still be very interested in finding out the best way to run multiple Consumer threads to get even better consume perfomance, as per the 3 original scenarios listed above.

Would you be able to confirm what your expectations would be and offer some guidance and/or application notes on the best way of approaching and implementing this scenario ?

Thanks,

John

**Comment by edenhill** [comment]
Sorry for missing your final question on this.

Generally speaking the consumer should be able to see disk read speeds (or higher when the disk cache is hot), and is mostly affected by broker load more than anything else - that is why you are seeing a decrease in performance when the producer is producing messages simultaneously.

But I guess you've sorted all this out by now. Do you have a successful (or not) story to share?
