### ISSUE TITLE
mklove/modules/configure.base: line 1104: c++: command not found

### ISSUE THREAD

**Issue by yxw2014** [edenhill/librdkafka#667]
Description
===========

###########################################################
###########################################################
###########################################################
 cxx (WITH_CXX) C++ compiler (c++)
    module: cc
    action: fail
    reason:
command 'c++ --version' failed:
mklove/modules/configure.base: line 1104: c++: command not found

[root@ librdkafka]# cat /etc/issue
CentOS release 6.7 (Final)
Kernel \r on an \m

[root@librdkafka]# uname -a
Linux yizhibo-test-51 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

How to reproduce
================

./configure

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version: git master branch

**Comment by edenhill** [comment]
You need to install a C++ compiler, e.g. g++

**Comment by gylgylgyl123** [comment]
> You need to install a C++ compiler, e.g. g++

but I do "yum install g++"?still the same error.ths
