### ISSUE TITLE
shipped tests fail

### ISSUE THREAD

**Issue by szmcdull** [edenhill/librdkafka#668]
Description
===========
shipped tests fail

```
TEST 20160524145756 (bare) SUMMARY
#==================================================================#
| <MAIN>                                   |     FAILED |  63.026s |
| 0001_multiobj                            |     PASSED |   5.232s |
| 0002_unkpart                             |     PASSED |   3.635s |
| 0003_msgmaxsize                          |     PASSED |   1.901s |
| 0004_conf                                |     PASSED |   1.543s |
| 0005_order                               |     PASSED |   1.872s |
| 0006_symbols                             |     PASSED |   0.000s |
| 0007_autotopic                           |     PASSED |   1.396s |
| 0008_reqacks                             |     PASSED |   1.390s |
| 0011_produce_batch                       |     PASSED |   1.232s |
| 0012_produce_consume                     |     FAILED |  60.018s |
| 0013_null_msgs                           |     PASSED |   1.929s |
| 0014_reconsume_191                       |     PASSED |   9.346s |
| 0015_offsets_seek                        |     PASSED |   3.691s |
| 0017_compression                         |     PASSED |   3.895s |
| 0018_cgrp_term                           |     FAILED |  58.023s |
| 0019_list_groups                         |     PASSED |   2.307s |
| 0020_destroy_hang                        |     PASSED |  13.454s |
| 0021_rkt_destroy                         |     PASSED |   0.374s |
| 0022_consume_batch                       |     FAILED |  55.022s |
| 0025_timers                              |     PASSED |   6.107s |
| 0026_consume_pause                       |     PASSED |  35.876s |
| 0028_long_topicnames                     |    SKIPPED |   0.000s |
| 0029_assign_offset                       |     FAILED |  53.021s |
| 0030_offset_commit                       |     PASSED |  49.301s |
| 0031_get_offsets                         |     PASSED |   1.871s |
| 0033_regex_subscribe                     |     PASSED |  46.692s |
| 0034_offset_reset                        |     PASSED |   3.570s |
| 0035_api_version                         |     PASSED |   0.043s |
| 0036_partial_fetch                       |     PASSED |   2.122s |
| 0037_destroy_hang_local                  |     PASSED |   1.113s |
| 0038_performance                         |     PASSED |  20.915s |
#==================================================================#
[<MAIN>                      / 64.026s] # Test report written to test_report_20160524145756.json
### Test "<MAIN>" failed at test.c:1093:main(): ###
1 test(s) failed, see previous errors
### Test random seed was 59788700 ###
```

How to reproduce
================
make the shipped tests

Checklist
=========
Please provide the following information:

 - [confluent-debian-0.9.1] librdkafka version (release number or git tag):
 - [0.9.0.1] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [CentOS 6.7] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Could you provide the test failure logs for the failing tests?
Should say something like: `Test "..." failed at ..`

**Comment by szmcdull** [comment]
### Test "0012_produce_consume" failed at 0012-produce_consume.c:54:dr_cb(): ###
Message delivery failed: Local: Unknown partition

### Test random seed was 59788700 ###

...

### Test "0018_cgrp_term" failed at test.c:1266:test_produce_msgs_nowait(): ###
Failed to produce message 1000 to partition 1: Local: Unknown partition
### Test random seed was 59788700 ###

...

### Test "0022_consume_batch" failed at test.c:1114:test_dr_cb(): ###
Message delivery failed: Local: Unknown partition

### Test random seed was 59788700 ###

...

### Test "0029_assign_offset" failed at test.c:1266:test_produce_msgs_nowait(): ###
Failed to produce message 0 to partition 1: Local: Unknown partition
### Test random seed was 59788700 ###



Also there is an error complaining git not found, and a note `This test requires at least 3 brokers!`

**Comment by edenhill** [comment]
Are you using an existing cluster to test this?
If so, what is your `num.partitions` config? It needs to be 3 for librdkafka tests.

But a better approach is to use the trivup-based test scripts that sets up a test cluster automatically, try: 
```
  cd tests
 ./broker_version_tests.py 0.9.0.1
```
You will need to install trivup first from https://github.com/edenhill/trivup
