### ISSUE TITLE
Producer keeps reporting protocol parse failure

### ISSUE THREAD

**Issue by nxgyzxw** [edenhill/librdkafka#669]
Description
===========
When producing one message to Kafka(0.8.2.1), the client reports 3 sets of log as below :

%4|1464145856.607|PROTOERR|rdkafka#producer-1| 10.43.149.109:9092/136168: Protocol parse failure at rd_kafka_produce_reply_handle:1622
%4|1464145856.607|PROTOERR|rdkafka#producer-1| 10.43.149.109:9092/136168: expected 4 bytes > 0 remaining bytes
%4|1464145856.767|PROTOERR|rdkafka#producer-1| 10.43.149.109:9092/136168: Protocol parse failure at rd_kafka_produce_reply_handle:1622
%4|1464145856.767|PROTOERR|rdkafka#producer-1| 10.43.149.109:9092/136168: expected 4 bytes > 0 remaining bytes
%4|1464145856.898|PROTOERR|rdkafka#producer-1| 10.43.149.109:9092/136168: Protocol parse failure at rd_kafka_produce_reply_handle:1622
%4|1464145856.898|PROTOERR|rdkafka#producer-1| 10.43.149.109:9092/136168: expected 4 bytes > 0 remaining bytes

The producer client resides in the **different network segment** from the Broker. And the Broker received this message, but  tripled to three messages.

The producer client **works well** when it's in the same network segment with the Broker, for example, on the same machine.

Checklist
=========
Please provide the following information:

 - [0.9.1 release ] librdkafka version (release number or git tag):
 - [ 0.8.2.1] Apache Kafka version: 
 - [ default] librdkafka client configuration:
 - [ Linux RedHat 6.4] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by nxgyzxw** [comment]
Sorry, find someone have already post this issue.

**Comment by nxgyzxw** [comment]
I configured **broker.version.fallback** to 0.8.2, but nothing changes, still the same error reported. Please help me, thks.

**Comment by edenhill** [comment]
You should set broker.version.fallback to your broker version  which was 0.8.1.2, right?

**Comment by nxgyzxw** [comment]
sorry, typo, it's 0.8.2.1. 
I've tried both 0.8.2 and 0.8.2.1.
 But nothing works。

**Comment by edenhill** [comment]
Try enabling debug=protocol and provide logs. Thanks

**Comment by nxgyzxw** [comment]
Sorry, my fault again. Careless. Needless space in "broker.version.fallback ". ( >﹏<)
Thank you.
