### ISSUE TITLE
I can receive many ack messages from kafka but the producer don't any message to kafka

### ISSUE THREAD

**Issue by andrewrong** [edenhill/librdkafka#670]
# Description

The producer receives many ack messages from kafka, but the producer don't send any messasges to kafka;  The message is below

`
10:14:22.374958 IP 10.19.11.31.XmlIpcRegSvc > 10.11.11.13.58202: Flags [.], seq 181001:182449, ack 25, win 14480, options [nop,nop,TS val 1640230738 ecr 3370824366], length 1448
E...M.@.>...
...
# ..Z;....d.l..8........

a..R....de_refund_error_log.........................r.......r.............r.......r...p.......p...r.....................q.......q.............q.......q...o.......o...q..."magic_access_spulinkfirstaudit_log.............p.......p...r.......p...r.....................p.......p.............o.......o...q.......o...q.....................o.......o........order_detail_process................................................................................................................................................mage_jump_trace_log.............q.......q...........q.............o.......o...r.......o...r.........p.......p...........p.........................q.......q........boshen_boxing_debug_log.............p.......p...q.......p...q.....................o...........o.........o.......o...p.......o...p......................................uni_donquixote_error_log................................................................................................................................................doimgrouphistory_log.............r.......r...o.......o...r.........p.......p...........p.............q.......q...........q.............o.......o...r.......o...r....innerapi_sign_exception_log.........................q.......q.............q.......q...o.......o...q.........r.......r...p.......p...r.   .......p.......p.......p....mtalk_action_log.............r.......r...o.......o...r.........p.......p...........p.............q.......q...........q
10:14:22.375393 IP 10.11.11.13.58202 > 10.19.11.31.XmlIpcRegSvc: Flags [.], ack 228785, win 65535, options [nop,nop,TS val 3370824367 ecr 1640230738], length 0
E..4..@.@..b
..
....Z#..d.l;..R.....    .....
....a..R
`

My producer receive message speed is 401kb/s, the speed is too large;
# How to reproduce

I'm very sorry, the phenomenon is accidental，I met three times; 
# Checklist

Please provide the following information:
- [ ] librdkafka version (release number or git tag): 0.9.0.99
- [ ] Apache Kafka version: 0.8.2.2
- [ ] librdkafka client configuration:

`
batch.num.message:1000
queue.buffering.max.ms:100
queue.buffering.max.messages:100000
metadata.broker.list: three hosts
message.max.bytes:1024 * 1024
request.required.acks：1
`
- [ ] Operating system: centos 6.5
- [ ] Using the legacy Consumer
- [ ] Using the high-level KafkaConsumer
- [ ] Provide logs (with `debug=..` as necessary) from librdkafka
- [ ] Provide broker log excerpts
- [ ] Critical issue

**Comment by edenhill** [comment]
I'm not really sure what problem is:
* are you unable to produce messages?
* or are messages not produced fast enough?
* something else?


To troubleshoot issues with librdkafka you can try setting the config property `debug` to `topic,broker,protocol`

> My producer receive message speed is 401kb/s, the speed is too large;

What do you mean by "speed is too large"?

**Comment by andrewrong** [comment]
My problem is 

the producer  send no messages to kafka. so it should not receive any ack message from kafka; But I find that kafka send many ack message to this producer;

Yeah, i can set the config property `debug` to `topic, broker, protocol`, how ?

> My producer receive message speed is 401kb/s, the speed is too large;

I use `dstat`, the item of recv is 400~600 kb/s, the phenomenon is unnormal；the item of recv should be 1k; because the producer do nothing;
