### ISSUE TITLE
Current Metadata

### ISSUE THREAD

**Issue by incessantier** [edenhill/librdkafka#674]
Currently Handle->metadata(...) adds another request to the queue, but as it is done automatically periodically, is there a way to just retrieve the current metadata?

**Comment by edenhill** [comment]
What about returning the last cached metadata if it is not older than the provided negative timeout, e.g.:
`...metadata(, -30000);` -> returned cached metadata if not older than 30s.

**Comment by edenhill** [comment]
Does the situation improve if you decrease metadata.request.timeout.ms?

**Comment by incessantier** [comment]
Time delay time improves, but I still had one rouge reference count preventing the shutdown.

**Comment by edenhill** [comment]
Okay, what is the easiest way to reproduce? (using rdkafka_example -L  for example)

**Comment by incessantier** [comment]
standby...

**Comment by incessantier** [comment]
1) I stand corrected, eventually it does exit out...dependent on metadata.request.timeout.ms.
2) I modified the rdkafka_example.cpp ...changing the -L mode.  It keeps requesting metadata in the loop, and then explicitly calls delete on the producer on a ctrl+c

    /* Metadata mode */

    /*
     * Create producer using accumulated global configuration.
     */
    RdKafka::Producer *producer = RdKafka::Producer::create(conf, errstr);
    if (!producer) {
      std::cerr << "Failed to create producer: " << errstr << std::endl;
      exit(1);
    }

    std::cout << "% Created producer " << producer->name() << std::endl;

    /*
     * Create topic handle.
     */
    RdKafka::Topic *topic = NULL;
    if(!topic_str.empty()) {
      topic = RdKafka::Topic::create(producer, topic_str, tconf, errstr);
      if (!topic) {
        std::cerr << "Failed to create topic: " << errstr << std::endl;
        exit(1);
      }
    }

    while (run) {
      class RdKafka::Metadata *metadata(NULL);

      /* Fetch metadata */
      RdKafka::ErrorCode err = producer->metadata(topic!=NULL, topic,
                                                  &metadata, 5000);
      if (err != RdKafka::ERR_NO_ERROR) {
        std::cerr << "%% Failed to acquire metadata: "
                  << RdKafka::err2str(err) << std::endl;
      }

      if (metadata) {
        delete metadata;
        metadata_print(topic_str, metadata);
      }
    }

    delete producer;

**Comment by incessantier** [comment]
just run with -L without a local broker started, and do a ctrl+c a couple seconds after starting.  takes ~30 seconds to shutdown.

**Comment by incessantier** [comment]
@edenhill how do you feel about me tackling the metadata enhancement?  I have a pretty good start on it I think.  The only thing that I can't track down is the time of the metadata message to store.  Any thoughts on how that should be grabbed? (system time?)

**Comment by incessantier** [comment]
@edenhill I have a deadlock issue that I'm looking into, but here is a start:
https://github.com/distributePro/librdkafka/commit/c0216aa9c22e8026046e5b48b33a09aeb56017d7

**Comment by incessantier** [comment]
@edenhill The metadata caching and a solution for the long shut-down time is in pull request #683

**Comment by edenhill** [comment]
@incessantier Is this feature still of interest?
