### ISSUE TITLE
master->kafka 0.8.2

### ISSUE THREAD

**Issue by incessantier** [edenhill/librdkafka#676]
Description
===========

Is master still intended to support 0.8.2?  Or should I go back to a different branch?  I am seeing parsing errors after updating to master.  E.g.:

LOG-4-PROTOERR: localhost:9092/0: Protocol parse failure at rd_kafka_fetch_reply_handle:3218
LOG-4-PROTOERR: localhost:9092/0: expected 20219350 bytes > 32 remaining bytes
EVENT 3 (Success): localhost:9092

How to reproduce
================
```examples/rdkafka_example_cpp -C -t <topoic> -p 0```

Checklist
=========
Please provide the following information:

 - [master] librdkafka version (release number or git tag):
 - [0.8.2 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [linux mint] Operating system:
 - [x] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka now defaults to broker protocol version 0.9.0, see this:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by incessantier** [comment]
perfect, thank you @edenhill.
