### ISSUE TITLE
broke_stat() had been removed?

### ISSUE THREAD

**Issue by foggy32** [edenhill/librdkafka#677]
Description
===========

I download the latest version of libkafka, found that function broke_stat() had been removed?
when and why?

I previously used it to judge broker's state, like:  if(RD_KAFKA_BROKER_STATE_UP == pProducer->broke_stat()).

grateful for your reply. ^ ^

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
To my knowledge there has never been a public API for returning the broker state, so I dont where you got broke_stat() from.

**Comment by foggy32** [comment]
In file: rdkafkacpp_int.h
class HandleImpl : virtual public Handle {
     int broker_stat () { return rd_kafka_broke_stat(rk_); };
}
version 0.8.6

**Comment by edenhill** [comment]
I think those are your fork's modifications, see official upstream here, no sign of broker_stat (regardless of spelling..)
https://github.com/edenhill/librdkafka/blob/0.8.6/src-cpp/rdkafkacpp_int.h

**Comment by foggy32** [comment]
thank you! 
another question:
   I run example to produce msg, and run bin/kafka-console-consumer.sh to consume.
Strangely,  I send one ,but receive three!
Here's some details,
Produce succ
outq_len  is [1]
%4|1464780370.643|PROTOERR|rdkafka#producer-1| 10.187.18.125:9092/2: Protocol parse failure at rd_kafka_produce_reply_handle:1795
%4|1464780370.643|PROTOERR|rdkafka#producer-1| 10.187.18.125:9092/2: expected 4 bytes > 0 remaining bytes

%4|1464780370.844|PROTOERR|rdkafka#producer-1| 10.187.18.125:9092/2: Protocol parse failure at rd_kafka_produce_reply_handle:1795
%4|1464780370.845|PROTOERR|rdkafka#producer-1| 10.187.18.125:9092/2: expected 4 bytes > 0 remaining bytes

%4|1464780370.946|PROTOERR|rdkafka#producer-1| 10.187.18.125:9092/2: Protocol parse failure at rd_kafka_produce_reply_handle:1795
%4|1464780370.946|PROTOERR|rdkafka#producer-1| 10.187.18.125:9092/2: expected 4 bytes > 0 remaining bytes

**Comment by edenhill** [comment]
You need to configure `broker.version.fallback` according to your broker version, see here:
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by foggy32** [comment]
Ah, exactly! it works. thx a lot!
