### ISSUE TITLE
phpKafka Consumer not working 

### ISSUE THREAD

**Issue by aarush091** [edenhill/librdkafka#680]
My code:-
error_reporting(E_ALL | E_STRICT);
ini_set('display_errors',1);

$kafka = new Kafka("localhost:9092");
$kafka->produce("aman", "aarush11111");
$partitions = $kafka->getPartitionsForTopic('aman');
$kafka->setPartition($partitions[0]);

echo "Consumer Start";
$kafkaConsumer = new Kafka("localhost:2181");
try{
    $msg = $kafkaConsumer->consume("aman",'beginning', 10);
}  catch (Exception $e){
    print_r($e);
}
var_dump($msg);

Output :-

Consumer Startarray(0) {
}
%3|1464786196.371|FAIL|rdkafka#consumer-1| localhost:2181/bootstrap: Receive failed: Disconnected
%5|1464786196.371|FAIL|rdkafka#consumer-1| localhost:2181/bootstrap: Connection closed

I am not able to consume through PHP while i am able to only produce through PHP.

**Comment by edenhill** [comment]
You should file this issue on the PHP kafka project's github issues page.
