### ISSUE TITLE
too many threads in librdkafka

### ISSUE THREAD

**Issue by hzhxxx** [edenhill/librdkafka#681]
Description
===========
[root@six examples]# ./rdkafka_consumer_example -b six.dev2:9092,six.dev2:9093,six.dev3:9092,six.dev4:9092 bbb
% Subscribing to 1 topics
% Consumer group rebalanced: assigned:
 bbb [0] offset -1001, bbb [1] offset -1001, bbb [2] offset -1001, bbb [3] offset -1001
% Consumer reached end of bbb [2] message queue at offset 51657489,0
% Consumer reached end of bbb [1] message queue at offset 53108608,0
% Consumer reached end of bbb [3] message queue at offset 50385058,0
% Consumer reached end of bbb [0] message queue at offset 69880977,0

[root@six examples]# ps -ef|grep "rdkafka_consumer_example"
root      8760  3527  0 09:08 pts/3    00:00:00 ./rdkafka_consumer_example -b six.dev2:9092,six.dev2:9093,six.dev3:9092,six.dev4:9092 bbb
[root@six examples]# gdb -p 8760
(gdb) info threads 
  7 Thread 0x7f9f49544700 (LWP 8761)  0x00007f9f4b6f6a5e in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  6 Thread 0x7f9f48b43700 (LWP 8762)  0x00007f9f4b6f6a5e in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  5 Thread 0x7f9f48142700 (LWP 8763)  0x00007f9f4a9c9113 in poll ()
   from /lib64/libc.so.6
  4 Thread 0x7f9f47741700 (LWP 8764)  0x00007f9f4a9c9113 in poll ()
   from /lib64/libc.so.6
  3 Thread 0x7f9f46d40700 (LWP 8765)  0x00007f9f4a9c9113 in poll ()
   from /lib64/libc.so.6
  2 Thread 0x7f9f4633f700 (LWP 8766)  0x00007f9f4a9c9113 in poll ()
   from /lib64/libc.so.6
* 1 Thread 0x7f9f4bb147c0 (LWP 8760)  0x00007f9f4b6f6a5e in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by hzhxxx** [comment]
the process both consumer and Producer,then need more 10 threads。

**Comment by edenhill** [comment]
added to #825
