### ISSUE TITLE
Publish to more topics reduces throughput significantly

### ISSUE THREAD

**Issue by danny794** [edenhill/librdkafka#684]
Hi,

I am working on an app that has one component X that is responsible with storing messages to Kafka. When I am publishing messages from a client to X for one topic, I get  a throughput around 90k msgs/second. However, if I change the number of topics to 16, for example, the throughput goes down to ~1,5k msgs/second.

In component X, I am using one RdKafka::Producer and create a new RdKafka::Topic for each topic that I want. Then use that Producer to publish messages for each Topic. I also tried to have one producer for each topic, but the result was the same. Moreover, when I check the CPU usage is almost 0.  I am doing something wrong?

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 236c09a9d257f84557cabdbf02116e3b17eb5916
 - [ ] Apache Kafka version: 0.9
 - [ ] librdkafka client configuration:
 - [ ] Operating system: Ubuntu 14.04 LTS
 - [ ] Using the legacy Consumer: No
 - [ ] Using the high-level KafkaConsumer: No
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Interesting.

What is your average message size and latency (either check stats_cb or debug=protocol and look for ProduceResponse rtt printouts)

**Comment by danny794** [comment]
* message size: 136 bytes (all messages have identical size)
* average latency: 1000ms.

These are measurements that I take in the client. The client does not talk directly to Kafka (it sends to component X, then component X talks to Kafka, then I get in component X the response from Kafka, then the client gets its acknowledgement). On the other hand, when I was publishing to  only a single topic I had the latency around 100ms.

I will try your checking as well.

**Comment by danny794** [comment]
This is an output sample from your suggestions:

[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 20459 bytes @ 0, CorrId 450)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 19487 bytes @ 0, CorrId 451)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 19933 bytes @ 0, CorrId 452)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 18677 bytes @ 0, CorrId 453)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 20945 bytes @ 0, CorrId 454)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 19811 bytes @ 0, CorrId 455)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 20585 bytes @ 0, CorrId 456)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 22079 bytes @ 0, CorrId 457)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 18140 bytes @ 0, CorrId 458)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 19281 bytes @ 0, CorrId 459)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 17162 bytes @ 0, CorrId 460)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 17381 bytes @ 0, CorrId 461)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 16247 bytes @ 0, CorrId 462)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 20422 bytes @ 0, CorrId 463)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 21269 bytes @ 0, CorrId 464)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 17488 bytes @ 0, CorrId 465)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 450, rtt 3.52ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 451, rtt 3.41ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 452, rtt 3.28ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 453, rtt 3.21ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 454, rtt 3.67ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 455, rtt 4.38ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 456, rtt 4.84ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 457, rtt 5.63ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 458, rtt 5.99ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 459, rtt 6.39ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 460, rtt 6.80ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 461, rtt 7.29ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 462, rtt 7.54ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 463, rtt 7.91ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 464, rtt 8.31ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 465, rtt 8.74ms)

**Comment by danny794** [comment]
This is for 1 topic (but the writing on the screen is much faster than the one for 16 topics)

[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 41195 bytes @ 0, CorrId 514)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 41195 bytes @ 0, CorrId 515)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 41195 bytes @ 0, CorrId 516)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 41195 bytes @ 0, CorrId 517)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 41195 bytes @ 0, CorrId 518)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 41195 bytes @ 0, CorrId 519)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 41195 bytes @ 0, CorrId 520)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 41195 bytes @ 0, CorrId 521)
[LOG]SEND|cloud-vm-47-43:9092/0: Sent ProduceRequest (v1, 11063 bytes @ 0, CorrId 522)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 514, rtt 2.75ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 515, rtt 3.43ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 516, rtt 4.27ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 517, rtt 5.20ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 518, rtt 6.18ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 519, rtt 6.93ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 520, rtt 7.73ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 521, rtt 8.68ms)
[LOG]RECV|cloud-vm-47-43:9092/0: Received ProduceResponse (v1, 30 bytes, CorrId 522, rtt 9.31ms)

**Comment by edenhill** [comment]
rtts looks very good, so thats not it then.

**Comment by danny794** [comment]
But do you have any advice how to manage publishing to multiple topics from the same component?

I tried now to create 16 topics and publish to only one of them and the throughput was high. Only when I am publishing to all 16 it goes down like that. I will continue to debug.

**Comment by edenhill** [comment]
What is the distribution of those topics among your brokers, is it the same broker that is leader for all of them? (or your Kafka proxy)

**Comment by edenhill** [comment]
Try debug=queue and look for something along the lines of "<yourtopic> [<partition>] N+M msgs", please provide a log of at least one line per topic and partition you are producing to when it seems slow.

**Comment by danny794** [comment]
When I noticed the problem I started using only 1 broker. Will run now with debug = queue and provide the logs, as requested.

**Comment by danny794** [comment]
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 21 [2] 0+113 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 21 [5] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 21 [4] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 21 [7] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 21 [1] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 21 [9] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 21 [3] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 21 [6] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 21 [0] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 52 [8] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 52 [2] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 52 [5] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 52 [4] 0+113 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 52 [7] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 52 [1] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 52 [9] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 52 [3] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 52 [6] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 52 [0] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 49 [8] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 49 [2] 0+90 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 49 [5] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 49 [4] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 49 [7] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 49 [1] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 49 [9] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 49 [3] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 49 [6] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 49 [0] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 14 [8] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 14 [2] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 14 [5] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 14 [4] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 14 [7] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 14 [1] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 14 [9] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 14 [3] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 14 [6] 0+0 msgs
[LOG]TOPPAR|cloud-vm-47-43:9092/0: 14 [0] 0+114 msgs

**Comment by danny794** [comment]
Can a message set contain messages from more topics?

**Comment by edenhill** [comment]
Those topics and partition queues look very empty.

Try setting  socket.blocking.max.ms=1 and queue.buffering.max.ms=1  and see if that improves anything

**Comment by danny794** [comment]
This works! I will increase a bit those values, as it makes the system fluctuate too much. It also decreased the latency to 20ms ⏩ 

Thank you very for all your time! I am really grateful! 😃
