### ISSUE TITLE
Consumer returns time out in non callback mode

### ISSUE THREAD

**Issue by DungBeetle0001** [edenhill/librdkafka#685]
# Description

I used librdkafka client consumer in non callback mode
I will get ERR_TIMED_OUT from message-err() after about 1~2 million messages from current offset, 
but if I start the consumer from the time out offset , it can continue to consume, that is to say,
I still have more message can be consumed in kafka when I receive the time out message.

I used the sample code, it is still the same.
# How to reproduce

1、add the "message time out" output in msg_consume() function in examples/rdkafka_example.cpp

switch (message->err()) {
    case RdKafka::ERR__TIMED_OUT:
      std::cout << "message time out\n";
      break;

2、make sure there are more than 2 million messages can be consumed.

3、compile and run the program,

4、the "message time out "  output will appear, at about the 1~2 million message from current offset. 
# Checklist

Please provide the following information:
- [ ] librdkafka version (release number or git tag): e5646cc6167b7dcbec1b268fea5255c066ede15a
- [ ] Apache Kafka version: 0.8.2.2
- [ ] librdkafka client configuration: ./rdkafka_example_cpp -C -t test_hzg -p 0 -b __1:9092,__2:9092,*_3:9092
- [ ] Operating system: centos 6.3
- [ ] Using the legacy Consumer
- [ ] Using the high-level KafkaConsumer
- [ ] Provide logs (with `debug=..` as necessary) from librdkafka
- [ ] Provide broker log excerpts
- [ ] Critical issue

**Comment by edenhill** [comment]
Is this still an issue?
