### ISSUE TITLE
librdkafka window System version requirements

### ISSUE THREAD

**Issue by Thomsonchen1206** [edenhill/librdkafka#686]
Hello , I would like to ask librdkafka minimum system version requirements . Because I'm running window xp and window server2003 unsuccessful , we look forward to your reply, thank you !

Note: I downloaded the latest version of librdkafka.

**Comment by edenhill** [comment]
The older Windows versions lack fundamental concurrency primitives, such as conditional variables, etc, so it isn't trivial to support them from the threading-heavy librdkafka.

Pull requests are welcome.

**Comment by Thomsonchen1206** [comment]
Tests found that run on Windows Vista, Windows Server 2008 is good.
