### ISSUE TITLE
Unneeded param on kinit?

### ISSUE THREAD

**Issue by tqshay** [edenhill/librdkafka#688]
Description
===========

When using this library, my code is failing when it attempts to refresh the SASL keys with a kinit.  It gives me the error "Server not found in Kerberos database while getting initial credentials".  Is there a way to turn off the server parameter?  If I perform a kinit manually without '-S "***"', it works just fine.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You can specify the exact command to execute by configuration `sasl.kerberos.kinit.cmd`, see https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md for more info

**Comment by tqshay** [comment]
Wow... I am not sure how I missed that.  I will give it a shot. Thanks for the amazing response time!

**Comment by tqshay** [comment]
I seem to be misunderstanding or missing something still...
My config has been setup with:
topic_conf = rd_kafka_topic_conf_new();
rd_kafka_conf_set(conf, "debug", "all", errstr, sizeof(errstr));
rd_kafka_conf_set(conf, "security.protocol", "SASL_PLAINTEXT", errstr, sizeof(errstr));
rd_kafka_conf_set(conf, "sasl.kerberos.kinit.cmd", "<MYKINIT>", errstr, sizeof(errstr));
rd_kafka_conf_set_dr_cb(conf, msg_delivered);

I am seeing the following behavior:
%3|1465483055.268|SASLREFRESH|rdkafka#producer-1| SASL key refresh failed: <MYKINIT> -S "kafka/*****" -k -i kafkaclient: exited with code 1

Any suggestions on how to avoid extra params from being appended to my kinit command?

**Comment by edenhill** [comment]
What librdkafka version are you using? The semantics of sasl.kerberos.kinit.cmd changed in 0.9.1 allowing full flexibility of the constructed command line, in 0.9.0 it was just a single executable path.
From your logs it looks like you are using 0.9.0, and in this case you should upgrade.

Also, specifying an empty string for sasl.kerberos.kinit.cmd is invalid config (and in fact crashes on 0.9.1! - will fix that)

**Comment by tqshay** [comment]
Aha!  We were running 0.9.0.  I now have 0.9.1 running on my local machine and getting through Kerberos properly.
Now, we just have to get it to compile nicely on our Solaris box using KornShell!
Thanks for the help!
