### ISSUE TITLE
Producer `max.block.ms`

### ISSUE THREAD

**Issue by jarreds** [edenhill/librdkafka#689]
What is the equivalent of `max.block.ms` in the librdkafka configuration settings?

**Comment by edenhill** [comment]
queue.buffering.max.ms

**Comment by jarreds** [comment]
Thank you!

**Comment by jarreds** [comment]
Actually, it appears there may not be an equivalent:

```
The producer config block.on.buffer.full has been deprecated and will
be removed in future release. Currently its default value has been
changed to false. The KafkaProducer will no longer throw
BufferExhaustedException but instead will use max.block.ms value to
block, after which it will throw a TimeoutException. If
block.on.buffer.full property is set to true explicitly, it will set
the max.block.ms to Long.MAX_VALUE and metadata.fetch.timeout.ms will
not be honoured
```

In the case of librdkafka, we get an `ENOBUFS` instead of a blocking produce. This allows us to put back-pressure instead of blocking.

Does that sound correct?

**Comment by edenhill** [comment]
Yes, you are right, librdkafka will currently not block when the buffer is full (it might in the future as an option).
