### ISSUE TITLE
Unknown topic error after bringing down node in cluster and bringing it back

### ISSUE THREAD

**Issue by winbatch** [edenhill/librdkafka#69]
Not sure if this is a kafka issue or a librdkafka issue.  We were doing some tests with our 3 node cluster.  We brought down one of the nodes and continued to operate.  (librdkafka gave the callback about the transport failure to the one node as expected, but continued on).  We found that when we brought back the 3rd node online, things continued to operate successfully while it was syncing back up/catching up.  As soon as the 3rd node was fully online, we got an error in several of our librdkafka clients that the topic wasn't found.  Some of the clients did not get this error.  

Can you think of a reason why this might happen?  I can ignore the error 'X' number of times/retry but wanted to make sure whether this was expected or considered a bug somewhere.

**Comment by winbatch** [comment]
Hi - been seeing this again.  Do you think if i receive an UNKNOWN_TOPIC any time after at least an initial successful send that I should just reconnect/restart?

**Comment by edenhill** [comment]
Did it happen during the same circumstances, e.g., by the time a bouncing broker gets back in sync?


If you in your app know that a topic really should exist (and anything else is an error), then I suggest that you yield for a short while and then try again. One alternative would perhaps be to trigger a metadata refresh by calling `rd_kafka_metadata(the_topic);`
Would that work for you?

**Comment by winbatch** [comment]
I'm happy to try it if you think it will help. The Kafka team was doing
a rolling restart when it occurred.  Do you have an idea why it's
happening?  Why would it no longer think the topic exists?

**Comment by winbatch** [comment]
I don't call rd_kafka_metadata anywhere else in the code since I am not
using any metadata directly.  Not sure what to pass it since I am not using
a metadata object.  How do I tell librdkafka to update its internal
metadata that I use for publishing?

**Comment by edenhill** [comment]
Since bugs in librdkafka itself is unthinkable my theory on this is that one of the brokers returns invalid/outdated information the topic metadata reply during the rolling upgrade.
A `rd_kafka_metadata(rk, NULL, 1000);` call would force a new metadata request and hopefully receive valid information back.

**Comment by winbatch** [comment]
Unthinkable :)
