### ISSUE TITLE
Error during configure of package

### ISSUE THREAD

**Issue by bvrygud** [edenhill/librdkafka#693]
Description
===========

I tried to do ./configure inside librdkafka folder.  I am getting the following error. 

checking for OS or distribution... ok (CentOS)
checking for C compiler from CC env... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... ok
checking for install (by command)... ok
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... ok
checking for GNU linker-script ld flag... ok
checking for __atomic_32 (by compile)... failed
checking for __atomic_32_lib (by compile)... failed
**checking for __sync_32 (by compile)... failed (fail)**
checking for __atomic_64 (by compile)... failed
checking for __atomic_64_lib (by compile)... failed
**checking for __sync_64 (by compile)... failed (fail)**
checking for socket (by compile)... ok
parsing version '0x00090100'... ok (0.9.1)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for libcrypto (by pkg-config)... ok
checking for libssl (by pkg-config)... ok
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... ok
checking for regex (by compile)... ok
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for strndup (by compile)... failed (disable)
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok

###########################################################
###########################################################
###########################################################
 **__sync_32 (HAVE_ATOMICS_32)**
    module: atomics
    action: disable
    reason:
compile check failed:
CC: CC
flags:
/usr/bin/gcc  -g -O2 -fPIC -Wall -Werror  _mkltmp19307.c -o _mkltmp19307.c.o  :
/tmp/cc0P5nn2.o: In function `foo':
/work/librdkafka/_mkltmp19307.c:4: undefined reference to `__sync_add_and_fetch_4'
collect2: ld returned 1 exit status
source:
#include <inttypes.h>
int32_t foo (int32_t i) {
  return __sync_add_and_fetch(&i, 1);
}

 **__sync_64 (HAVE_ATOMICS_64)**
    module: atomics
    action: disable
    reason:
compile check failed:
CC: CC
flags:
/usr/bin/gcc  -g -O2 -fPIC -Wall -Werror  _mkltmp19348.c -o _mkltmp19348.c.o  :
/tmp/ccem6DRB.o: In function `foo':
work/librdkafka/_mkltmp19348.c:4: undefined reference to `__sync_add_and_fetch_8'
collect2: ld returned 1 exit status
source:
#include <inttypes.h>
int64_t foo (int64_t i) {
  return __sync_add_and_fetch(&i, 1);
}

My gcc version: 

**file /usr/bin/gcc**
/usr/bin/gcc: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), for GNU/Linux 2.6.9, dynamically linked (uses shared libs), stripped

**gcc -v**
Using built-in specs.
Target: i386-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-libgcj-multifile --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --disable-plugin --with-java-home=/usr/lib/jvm/java-1.4.2-gcj-1.4.2.0/jre --with-cpu=generic --host=i386-redhat-linux
Thread model: posix
gcc version 4.1.2 20080704 (Red Hat 4.1.2-55)

**cat /etc/redhat-release**
CentOS release 5.11 (Final)

Can you please let me know how to resolve this issue.

**Comment by edenhill** [comment]
librdkafka requires 64-bit atomics, you'll need a newer GNU / gcc toolchain to get support for that.

**Comment by bvrygud** [comment]
This library needs to be added as a dependency for 32 bit server. So you are suggesting me to build it with 64 bit  gcc. In this case my 32bit server will throw an error with incompatible architecture.

**Comment by edenhill** [comment]
Newer 32-bit gcc toolchains have libatomic that provides 64-bit atomics on 32-bit platforms, as I understand it.
Your toolchain is very old, almost 8 years.

**Comment by bvrygud** [comment]
Thanks for the update. 

But for my case I have no option rather than sticking with the older toolchain as there is way too many dependencies.

**Comment by edenhill** [comment]
librdkafka now falls back to standard mutexes when atomic ops are not available.
Could you give latest master branch a try?
I verified this on CentOS 5.6 (32bit)
