### ISSUE TITLE
How can i create a topic with specify partition count

### ISSUE THREAD

**Issue by 7zkeeper** [edenhill/librdkafka#697]
Description
===========
I see the tests example，and I dont find a way to create a topic with specify partition conut.
Most producer example produce message to broker with partition,but not mention about how create
a topic with mutil partition

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):newest
 - [ ] Apache Kafka version: 0.9.1
 - [ ] librdkafka client configuration:
 - [ ] Operating system:centos 7
 - [ ] Using the legacy Consumer 
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There are two ways, for manually created topics use the kafka-topics.sh script included in the Kafka distribution: http://kafka.apache.org/documentation.html#basic_ops_add_topic
For automatically created topics you will need to configure the broker with auto.create.topics.enable=true,  num.partitions=N, etc.

**Comment by 7zkeeper** [comment]
thank you and it means it is not way to create multi partition for topic with librdkafka api

**Comment by edenhill** [comment]
That's right.

**Comment by neha2007** [comment]
Can we create new partitions from client using below API on Kafka?? I tried to use it but getting segmentation fault.

 rd_kafka_CreatePartitions (rd_kafka_t *rk,
                           rd_kafka_NewPartitions_t **new_parts,
                           size_t new_parts_cnt,
                           const rd_kafka_AdminOptions_t *options,
                           rd_kafka_queue_t *rkqu);

**Comment by edenhill** [comment]
See an example here:
https://github.com/edenhill/librdkafka/blob/master/tests/test.c#L5666

**Comment by neha2007** [comment]
> See an example here:
> https://github.com/edenhill/librdkafka/blob/master/tests/test.c#L5666

Thank you. Could you please point me to the c++ example code for this if possible, to create topic with number of partitions specified?

**Comment by agbogdan** [comment]
Hi, is it possible to specify the number of replicas and their assignment when creating a topic from librdkafka?

**Comment by edenhill** [comment]
See NewTopic() and NewTopic_set_replica_assignment():
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L6563
