### ISSUE TITLE
Is there a seek in the c++ legacy consumer?

### ISSUE THREAD

**Issue by nasava** [edenhill/librdkafka#699]
Description
===========

I could not find the possibility in the C++ legacy Consumer API to do a seek, only the C function rd_kafka_seek.  This can not be used easily, as it needs an  rd_kafka_topic_t TopicImpl carries an instance around in its rkt_ field, but I think I should not code against it.

Is there a better way?

Checklist
=========
Please provide the following information:

 - [X] librdkafka version (release number or git tag): 0.9.1

**Comment by edenhill** [comment]
This issue is now fixed on master, please try to verify the fix in your environment.
Thank you.
