### ISSUE TITLE
Query Watermark Offsets returns Incorrect Offsets

### ISSUE THREAD

**Issue by dharesign** [edenhill/librdkafka#700]
The `rd_kafka_query_watermark_offsets` API doesn't return the correct offsets.  This was observed by the return value for `low` differing from the the offset retrieved when consuming a single message from the beginning and inspecting the offset.

Having inspected the code, it seems likely that this is related to the request built up in `rd_kafka_OffsetRequest`.  Here, the `MaxNumberOfOffsets` is set to `offset_cnt`, which is `2`.  Having read [this article][1], it seems that in the case of `timestamp` = `-1`, if `MaxNumberOfOffsets` is greater than `1`, you get back multiple offsets if you have multiple log segments on disk.

As a result, to reproduce you will need to ensure that the Kafka broker you connect to has multiple log segments.  In that case, you can try to use the `rdkafka_example` program to query the watermarks, and consume the first message, and observe that the offsets for the start differ.

~~I'm guessing that the required fix would be to hard code `1` [here][2], rather than `offset_cnt`.~~

[1]: http://cfchou.github.io/blog/2015/04/23/a-closer-look-at-kafka-offsetrequest/
[2]: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_request.c#L279

**Comment by dharesign** [comment]
Hard coding `1` didn't help.  The Kafka broker was just returning a single offset for a single partition.

**Comment by dharesign** [comment]
To determine the reason for that, I started digging in the Kafka code.

Here's the code for handling an Offset Request: https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/server/KafkaApis.scala#L508

And here's the OffsetRequest type in Kafka: https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/api/OffsetRequest.scala#L29

It looks like it reads the request from the wire format, and builds up a map keyed on `TopicAndPartition`.  In your case, both offsets being requested have the same topic and partition, so whilst you're requesting two offsets, the Kafka broker only handles and returns the response for a single one.

**Comment by dharesign** [comment]
This is true for both Kafka 0.8.2 and Kafka trunk, and probably worth of a bug report / feature request from Kafka itself.

In the mean time, I think the only way to implement your API is to send two requests to the broker.

**Comment by dharesign** [comment]
Looks like: https://issues.apache.org/jira/browse/KAFKA-1588

**Comment by edenhill** [comment]
Thanks for your awesome bug report, and solution!
Will fix for the next release.

(sorry for not tending to this earlier)

**Comment by edenhill** [comment]
Please give latest master a try.

**Comment by ajige** [comment]
does 0.9.2 solve this bug? 
what about the master?

**Comment by edenhill** [comment]
Yes, it is fixed in 0.9.2 (and master)
