### ISSUE TITLE
install: Unable to get "librdkafka.a" file status (stat): No such file or directory

### ISSUE THREAD

**Issue by bencen** [edenhill/librdkafka#701]
HI,Edenhill,please help me,thank you

using cache file config.cache
checking for OS or distribution... ok (Linux)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok (cached)
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok (cached)
checking executable ld... ok (cached)
checking executable nm... ok (cached)
checking executable objdump... ok (cached)
checking executable strip... ok (cached)
checking for pkgconfig (by command)... ok (cached)
checking for install (by command)... ok (cached)
checking for PIC (by compile)... ok (cached)
checking for GNU-compatible linker options... ok (cached)
checking for GNU linker-script ld flag... ok (cached)
checking for __atomic_32 (by compile)... failed
checking for __atomic_32_lib (by compile)... failed
checking for __sync_32 (by compile)... ok (cached)
checking for __atomic_64 (by compile)... failed
checking for __atomic_64_lib (by compile)... failed
checking for __sync_64 (by compile)... ok (cached)
checking for socket (by compile)... ok (cached)
parsing version '0x000901ff'... ok (0.9.1)
checking for libpthread (by pkg-config)... failed
checking for libpthread (by compile)... ok
checking for zlib (by pkg-config)... ok
checking for libcrypto (by pkg-config)... ok
checking for liblz4 (by pkg-config)... failed
checking for liblz4 (by compile)... failed (disable)
checking for libssl (by pkg-config)... ok
checking for libsasl2 (by pkg-config)... failed
checking for libsasl2 (by compile)... ok
checking for regex (by compile)... ok (cached)
checking for librt (by pkg-config)... failed
checking for librt (by compile)... ok
checking for strndup (by compile)... ok (cached)
checking for nm (by env NM)... ok (cached)
checking for python (by command)... ok (cached)
Generated Makefile.config
Generated config.h

Configuration summary:
  prefix                   /usr
  ARCH                     x86_64
  CPU                      generic
  GEN_PKG_CONFIG           y
  ENABLE_DEVEL             n
  ENABLE_VALGRIND          n
  ENABLE_REFCNT_DEBUG      n
  ENABLE_SHAREDPTR_DEBUG   n
  ENABLE_SSL               y
  ENABLE_SASL              y
  MKL_APP_NAME             librdkafka
  MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
  MKL_DISTRO               Linux
  CC                       gcc
  CXX                      g++
  LD                       ld
  NM                       nm
  OBJDUMP                  objdump
  STRIP                    strip
  CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith
  PKG_CONFIG               pkg-config
  INSTALL                  install
  LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
  LDFLAG_LINKERSCRIPT      -Wl,--version-script=
  RDKAFKA_VERSION_STR      0.9.1
  MKL_APP_VERSION          0.9.1
  LIBS                     -lpthread -lz   -lcrypto   -lssl -lcrypto   -lsasl2 -lrt
  CFLAGS                        
  CXXFLAGS                 -Wno-non-virtual-dtor
  SYMDUMPER                $(NM) -D
  exec_prefix              /usr
  bindir                   /usr/bin
  sbindir                  /usr/sbin
  libexecdir               /usr/libexec
  datadir                  /usr/share
  sysconfdir               /usr/etc
  sharedstatedir           /usr/com
  localstatedir            /usr/var
  libdir                   /usr/lib
  includedir               /usr/include
  infodir                  /usr/info
  mandir                   /usr/man
Generated config.cache

Now type 'make' to build

=================

make[1]: Entering directory `/root/librdkafka-master/src'
Install librdkafka to /usr
install -d $DESTDIR/usr/include/librdkafka ; \
	install -d $DESTDIR/usr/lib ; \
	install rdkafka.h $DESTDIR/usr/include/librdkafka ; \
	install librdkafka.a $DESTDIR/usr/lib ; \
	install librdkafka.so.1 $DESTDIR/usr/lib ; \
	[ -f "rdkafka.pc" ] && ( \
		install -d $DESTDIR/usr/lib/pkgconfig ; \
		install -m 0644 rdkafka.pc $DESTDIR/usr/lib/pkgconfig \
	) ; \
	(cd $DESTDIR/usr/lib && ln -sf librdkafka.so.1 librdkafka.so)
install: Unable to get "librdkafka.a" file status (stat): No such file or directory
install: Unable to get "librdkafka.so.1" file status (stat): No such file or directory
make[1]: Leaving directory `/root/librdkafka-master/src'
make[1]: Entering directory `/root/librdkafka-master/src-cpp'
Install librdkafka++ to /usr
install -d $DESTDIR/usr/include/librdkafka ; \
	install -d $DESTDIR/usr/lib ; \
	install rdkafkacpp.h $DESTDIR/usr/include/librdkafka ; \
	install librdkafka++.a $DESTDIR/usr/lib ; \
	install librdkafka++.so.1 $DESTDIR/usr/lib ; \
	[ -f "rdkafka++.pc" ] && ( \
		install -d $DESTDIR/usr/lib/pkgconfig ; \
		install -m 0644 rdkafka++.pc $DESTDIR/usr/lib/pkgconfig \
	) ; \
	(cd $DESTDIR/usr/lib && ln -sf librdkafka++.so.1 librdkafka++.so)
install: Unable to get "librdkafka++.a" file status (stat): No such file or directory
install: Unable to get "librdkafka.so.1" file status (stat): No such file or directory
make[1]: Leaving directory `/root/librdkafka-master/src-cpp'
=============================

**Comment by bencen** [comment]
ibrdkafka++.a,librdkafka.so.1,why no such,what do I need to do

**Comment by nasava** [comment]
The output you sent looks like that of make install. Did you run simple make without parameters before it? Without running make I could reproduce your error message.

**Comment by bencen** [comment]
1. ./configure --prefix=/usr
Display the contents of the first floor
2.make install
too

**Comment by bencen** [comment]
Linux by4.picnic-bag.com 2.6.32-573.el6.x86_64 #1 SMP Thu Jul 23 15:44:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
Copyright © 2010 Free Software Foundation, Inc.

**Comment by bencen** [comment]
soｉinstall https://github.com/arnaud-lb/php-rdkafka
#./configure --prefix=/usr

checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local/php
checking for PHP includes... -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php/lib/php/extensions/no-debug-non-zts-20121212
checking for PHP installed headers prefix... /usr/local/php/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... gawk
checking for rdkafka support... yes, shared
checking for librdkafka/rdkafka.h" in default path... found in /usr/local
found in /usr
checking for rd_kafka_new in -lrdkafka... no
configure: error: wrong rdkafka lib version or lib not found



install fails

I think it should be librakafak install fails

**Comment by nasava** [comment]
I do not know for the php variant, but for rdkafka lib itself building goes like this:

```
./configure
make
make install
```

the second command will create the files which the error messages say are missing. The last one has to be run as root, if you use prefix /usr. Then make install copies the libs created by make into the path into your root file system, hopefully where the php wrapper looks for it.

**Comment by bencen** [comment]
thank you very mach ,i lose the second command.

**Comment by edenhill** [comment]
Thanks for helping out, @nasava
