### ISSUE TITLE
get all topics in rdfkafka_

### ISSUE THREAD

**Issue by danyalxahid** [edenhill/librdkafka#702]
Description
===========
How can i get all the topics present in the kafka cluster in rdkafka_exapmle.cpp.
i just need to get all the present topics.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Use the metadata() API

**Comment by danyalxahid** [comment]
i dont fully understand. Could you elaborate a little.

**Comment by edenhill** [comment]
Here is an example how to call the C++ metadata() API:
https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_example.cpp#L588

**Comment by danyalxahid** [comment]
what Topic::Create does is creates a topic, i just need to get all the topic registered in the form of string vector or something.

**Comment by danyalxahid** [comment]
or it just handles the errors f there are any

**Comment by nasava** [comment]
I used something like this: 
``` cpp   
//... initiate a consumer ...

typedef RdKafka::Metadata::TopicMetadataIterator TopicIterator;
typedef RdKafka::TopicMetadata::PartitionMetadataIterator PartitionIterator;

RdKafka::Metadata* metadata;
consumer->metadata(true, 0, &metadata, timeout_ms);

for(TopicIterator it = metadata->topics()->begin(); it != metadata->topics()->end(); ++it)
{
    std::cout<< "Availiable topic: " << (*it)->topic() << std::endl;    
    for(PartitionIterator partIt = (*it)->partitions()->begin(); partIt != (*it)->partitions()->end(); ++partIt)
    {
        std::cout<< "    Availiable partition: " << (*partIt)->id() << std::endl;
    }
}

delete metadata;
```
A remark: I did not test it exactly in this form, I had to replace my wrappings, but the original worked for me.

**Comment by danyalxahid** [comment]
Just figured out a more simpler version to do this. 
Just call the function metadata_print(topic_str, metadata) and make changes to it where necessary.
