### ISSUE TITLE
The type initializer for 'RdKafka.Internal.LibRdKafka' threw an exception.

### ISSUE THREAD

**Issue by gargvicky** [edenhill/librdkafka#703]
Description
===========
After uploading on server getting The type initializer for 'RdKafka.Internal.LibRdKafka' threw an exception.message.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ah-** [comment]
Which version of RdKafka are you using?

How does the directory structure on the server look like, is there a librdkafka.dll? From where are you running your executable?

**Comment by ah-** [comment]
Also do you have vcredist 2013 installed?
https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by gargvicky** [comment]
I have already added librdkafka.dll and zlib.dll but still same issue. This issue resolved earlier using vcredist 2013 installed but under container facing same issue.

**Comment by gargvicky** [comment]
I am using below commands to add vcredist 2013 on container

ADD https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe /vc_redist_x64.exe

ADD https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe /vc_redist_x86.exe

RUN C:\vc_redist_x64.exe /quiet /install

RUN C:\vc_redist_x86.exe /quiet /install
