### ISSUE TITLE
rd_kafka_commit does not notify of non-existing topic

### ISSUE THREAD

**Issue by edoardocomar** [edenhill/librdkafka#704]
Description
===========

rd_kafka_commit (rd_kafka_t *rk, const rd_kafka_topic_partition_list_t *offsets, int async)

invoked with async =0 
and a list that contains a topic that does not exist on the broker. 
always returns error code 0, 

i.e. the caller is not notified that the request is for a non-existing topic.

This is a notable difference with the Java client which instead throws
[2016-06-27 16:17:09,341] Exception in thread "main" org.apache.kafka.common.KafkaException: Unexpected error in commit: This server does not host this topic-partition. at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler.handle(ConsumerCoordinator.java:556)

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.9.1 ] librdkafka version (release number or git tag):
 - [0.9] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ mac & ubuntu] Operating system:
 - [ ] Using the legacy Consumer
 - [X ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka

rdkafka: 7 RECV sasl_ssl://kafka05-stage1.messagehub.services.us-south.bluemix.net:9093/4: Received OffsetCommitResponse (v1, 19 bytes, CorrId 38, rtt 134.30ms)
rdkafka: 7 RECV sasl_ssl://kafka05-stage1.messagehub.services.us-south.bluemix.net:9093/4: Received OffsetCommitResponse (v1, 19 bytes, CorrId 39, rtt 134.72ms)
rdkafka: 7 RECV sasl_ssl://kafka05-stage1.messagehub.services.us-south.bluemix.net:9093/4: Received OffsetCommitResponse (v1, 19 bytes, CorrId 40, rtt 134.73ms)
rdkafka: 7 OFFSET OffsetCommit failed for foo [1] at offset 82072: Broker: Unknown topic or partition
rdkafka: 7 OFFSET OffsetCommit failed for foo [1] at offset 82082: Broker: Unknown topic or partition

 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edoardocomar** [comment]
Here's attached a sample program (modified rdkafka_consumer_example.c) that shows this issue

start a localhost zk and kafka brokers (I tested this against 0.10) and create a topic, e.g. `mytopic1`
on one terminal, run a console producer, e.g.
```$ bin/kafka-console-producer.sh --broker-list localhost:9092 --topic mytopic1 ```

on another terminal launch the sample
```$ ./rdkafka_consumer_example_issue704  -g mygrp mytopic1```

the sample will do a SYNC commit the offset+1 of each message consumed first
and then will do another SYNC commit, this time of a non-existent topic.
both will succeed while I'd expect the latter to fail.

```$ ./rdkafka_consumer_example_issue704  -g mygrp mytopic1
 set enable.auto.commit = false 
 set group.id = mygrp 
% Subscribing to 1 topics
% Consumer group rebalanced: assigned:
 mytopic1 [0] offset -1001
% Consumer reached end of mytopic1 [0] message queue at offset 8
% Message (topic mytopic1 [0], offset 8, 3 bytes):
Key: key
topic=mytopic1 offset=8 len=3 key=key payload=msg
COMMITTED: topic-partition=mytopic1-0 offset=9
COMMITTED: topic-partition=foobartopic-0 offset=9
% Consumer reached end of mytopic1 [0] message queue at offset 9
```

[rdkafka_consumer_example_issue704.c.zip](https://github.com/edenhill/librdkafka/files/337223/rdkafka_consumer_example_issue704.c.zip)

**Comment by edenhill** [comment]
You'll need to register an offset_commit_cb to get per-topic-partition-offset status/error-reporting of an offset commit.

**Comment by edoardocomar** [comment]
from gitter conversation:

so even in the case of SYNC commits I can't know if there was an error until rd_kafka_consumer_poll() is called again and the offset_commit_cb is invoked ?

> correct, which kind of sucks. I'm going to add per-commit callbacks soon which will also make it to the sync interface and update the provided offset errors accordingly

is there a way to find out if an error occurred before invoking poll() again ?
> and no, no way of knowing that beforehand

**Comment by edoardocomar** [comment]
Updated attachment example with callback showing the error

**Comment by edenhill** [comment]
This issue is now fixed on master, please try to verify the fix in your environment.
Thank you.

You can use the new rd_kafka_commit_queue() API which allows you to specify a temporary callback (and NULL queue for sync behaviour). See this for an example:
https://github.com/edenhill/librdkafka/blob/master/tests/0030-offset_commit.c#L471

**Comment by edoardocomar** [comment]
Thanks @edenhill works for us
```
% Message (topic testtopic [0], offset 7, 4 bytes):
topic=testtopic offset=7 len=4 key=(null) payload=msg8
COMMITTED (GOOD TOPIC): topic-partition=testtopic-0 offset=8
COMMITTED (UNKNOWN TOPIC): topic-partition=foobartopic-0 offset=1000
% Consumer reached end of testtopic [0] message queue at offset 8
CALLBACK : offset_commit_cb : offsets->cnt=1, err=0 
CALLBACK : testtopic-0 offs=8 err=0 Success
CALLBACK : offset_commit_cb : offsets->cnt=1, err=0 
CALLBACK : foobartopic-0 offs=1000 err=3 Broker: Unknown topic or partition
```

**Comment by kparadkar** [comment]
What is the behavior for rd_kafka_commit to the topics you have not subscribed/assigned to ? I tried committing to a topic which exists but consumer has not subscribed to , and I do not get error (even via rd_kafka_offset_commit_cb) Is this a valid test?

**Comment by edenhill** [comment]
afaik it is okay to commit offsets for groups that dont have any active joined members.
