### ISSUE TITLE
Question about message timestamp

### ISSUE THREAD

**Issue by BDeus** [edenhill/librdkafka#707]
Hi Eden,
Is it possible to pass the timestamp as a parameter of the produce message with a 0.10 broker and 0.9.1 librdkafka ?
It seems that we can only have the utc now date in this field.

**Comment by edenhill** [comment]
This is currently not possible, unfortunately.

**Comment by edenhill** [comment]
The new rd_kafka_producev() API supports setting the timestamp.

**Comment by dharesign** [comment]
It looks like this didn't make 0.9.3.  When can I expect it?

**Comment by edenhill** [comment]
@dharesign 0.9.4 will be released in a month or so.
