### ISSUE TITLE
Cross compiling 

### ISSUE THREAD

**Issue by CHNEG8805** [edenhill/librdkafka#708]
# Description

I want run rdkafka_example on my arm platform. I use the librdkafka-0.8.2(C),and change the Makefile 
LIBNAME=librdkafka
LIBVER=0

DESTDIR?=/usr/local

CC=arm-none-linux-gnueabi-gcc
LD=arm-none-linux-gnueabi-ld
AR=arm-none-linux-gnueabi-ar
NM=arm-none-linux-gnueabi-nm

SRCS=   rdkafka.c rdkafka_broker.c rdkafka_msg.c rdkafka_topic.c \
    rdkafka_defaultconf.c rdkafka_timer.c rdkafka_offset.c
SRCS+=  rdcrc32.c rdgz.c rdaddr.c rdrand.c rdthread.c rdqueue.c rdlog.c
# SRCS+= snappy.c

HDRS=   rdkafka.h

OBJS=   $(SRCS:.c=.o)
DEPS=   ${OBJS:%.o=%.d}

CFLAGS+=-O2 -fPIC -I.
CFLAGS+=-g
# Clang warnings to ignore
# CFLAGS+=-Wno-gnu-designator
# Enable iovecs in snappy
# CFLAGS+=-DSG
# Profiling
# CFLAGS+=-O0
# CFLAGS += -pg
# LDFLAGS += -pg
# LDFLAGS+=-g -fPIC

LDFLAGS+= -shared -g -fPIC 
.PHONY:

all: libs
# libs: $(LIBNAME).so.$(LIBVER) $(LIBNAME).a CONFIGURATION.md

libs: $(LIBNAME).so.$(LIBVER) $(LIBNAME).a

%.o: %.c
    $(CC) -MD -MP $(CFLAGS) -c $<
# $(LIBNAME).so.$(LIBVER): $(OBJS)
# @(if [ "`uname -s`" = "Linux" ]; then \
# $(CC) $(LDFLAGS) \
# -shared -Wl,-soname,$@ \
# -Wl,--version-script=librdkafka.lds \
# $(OBJS) -o $@ -lpthread -lrt -lz -lc ; \
# elif [ "`uname -s`" = "Darwin" ]; then \
# $(CC) $(LDFLAGS) \
# $(OBJS) -dynamiclib -o $@ -lpthread -lz -lc ; \
# fi)

$(LIBNAME).so.$(LIBVER):$(OBJS)
# $(LD) -shared -Wl,$(LIBNAME).so.$(LIBVER) \
# $(LDFLAGS) $(OBJS) -o $@
# ln -fs $(LIBNAME).so $(LIBNAME).so.$(LIBVER)

$(LIBNAME).a:   $(OBJS)
    $(AR) rcs $@ $(OBJS)
# CONFIGURATION.md: rdkafka.h examples
# examples/rdkafka_performance -X list > CONFIGURATION.md.tmp
# cmp CONFIGURATION.md CONFIGURATION.md.tmp || \
# mv CONFIGURATION.md.tmp CONFIGURATION.md
# rm -f CONFIGURATION.md.tmp
# examples: .PHONY
# make -C $@

install:
    if [ "$(DESTDIR)" != "/usr/local" ]; then \
        DESTDIR="$(DESTDIR)/usr"; \
    else \
        DESTDIR="$(DESTDIR)" ; \
    fi ; \
    install -d $$DESTDIR/include/librdkafka $$DESTDIR/lib ; \
    install -t $$DESTDIR/include/$(LIBNAME) $(HDRS) ; \
    install -t $$DESTDIR/lib $(LIBNAME).a ; \
    install -t $$DESTDIR/lib $(LIBNAME).so.$(LIBVER) ; \
    (cd $$DESTDIR/lib && ln -sf $(LIBNAME).so.$(LIBVER) $(LIBNAME).so)
# tests: .PHONY
# make -C tests

clean:
    rm -f $(OBJS) $(DEPS) \
        $(LIBNAME)_.a $(LIBNAME)_.so $(LIBNAME)*.so.$(LIBVER)
    make -C tests clean

-include $(DEPS)

i success make the librdkafka.a  but rum the rdkafka_example on my arm platform it message:
A newer kernel is required to run this binary. (__kernel_cmpxchg64 helper)
Aborted
i can not run the bin......
# How to reproduce
# Checklist

Please provide the following information:
- [ ] librdkafka version (release number or git tag):
- [ ] Apache Kafka version: 
- [ ] librdkafka client configuration:
- [ ] Operating system:
- [ ] Using the legacy Consumer
- [ ] Using the high-level KafkaConsumer
- [ ] Provide logs (with `debug=..` as necessary) from librdkafka
- [ ] Provide broker log excerpts
- [ ] Critical issue

**Comment by edenhill** [comment]
Please try latest librdkafka master, it has support for platforms that lack 64-bit (and 32-bit) atomics

**Comment by CHNEG8805** [comment]
Thanks .I have cross compiling the libatomics on my platform and link to librdkafka .I will try latest librdkafka master soon。thanks again.



astonish1@126.com
 
From: Magnus Edenhill
Date: 2016-06-30 14:02
To: edenhill/librdkafka
CC: CHNEG8805; Author
Subject: Re: [edenhill/librdkafka] Cross compiling (#708)
Please try latest librdkafka master, it has support for platforms that lack 64-bit (and 32-bit) atomics

**Comment by bekritsk** [comment]
I am trying to cross-compile librdkafka for arm, but it isn't clear which switches to use in the ./configure command to have it use the arm-none-linux-gnueabi toolchain as it seems that the ./configure ignores the --host switch. (--host=HOST                          Configure to build programs to run on HOST (no-op))
What is the preferred way update the makefile (without updating it as above) using autoconfig?

**Comment by bekritsk** [comment]
I've worked through some of the issues, but still get the following errors when making the library: 

arm-none-linux-gnueabi-gcc -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith  -c rdkafka.c -o rdkafka.o
In file included from rdposix.h:97,
                 from rd.h:68,
                 from rdkafka_int.h:44,
                 from rdkafka.c:38:
rdatomic.h: In function 'rd_atomic32_add':
rdatomic.h:41: warning: implicit declaration of function 'ATOMIC_OP'
rdatomic.h:41: error: 'add' undeclared (first use in this function)
rdatomic.h:41: error: (Each undeclared identifier is reported only once
rdatomic.h:41: error: for each function it appears in.)
rdatomic.h:41: error: 'fetch' undeclared (first use in this function)
rdatomic.h: In function 'rd_atomic32_sub':
rdatomic.h:58: error: 'sub' undeclared (first use in this function)
rdatomic.h:58: error: 'fetch' undeclared (first use in this function)
rdatomic.h: In function 'rd_atomic32_get':
rdatomic.h:72: error: 'fetch' undeclared (first use in this function)
rdatomic.h:72: error: 'add' undeclared (first use in this function)
make[1]: *** [rdkafka.o] Error 1
make[1]: Leaving directory `/home/benjyb/librdkafka-master/src'
make: *** [libs] Error 2

The configuration shows that only atomic "sync32" works:
hecking for __atomic_32 (by compile)... failed
checking for __atomic_32_lib (by compile)... failed
checking for __sync_32 (by compile)... ok
checking for __atomic_64 (by compile)... failed
checking for __atomic_64_lib (by compile)... failed
checking for __sync_64 (by compile)... failed (disable)

**Comment by ifding** [comment]
Hey, @edenhill  @CHNEG8805 @bekritsk
I am trying to cross-compile librdkafka 0.9.1 for OpenWrt, I mostly succeeded. 

```
Creating static library librdkafka++.a
mipsel-openwrt-linux-musl-ar rcs librdkafka++.a RdKafka.o ConfImpl.o HandleImpl.o ConsumerImpl.o ProducerImpl.o KafkaConsumerImpl.o TopicImpl.o TopicPartitionImpl.o MessageImpl.o QueueImpl.o MetadataImpl.o
Creating librdkafka++.so symlink
rm -f "librdkafka++.so" && ln -s "librdkafka++.so.1" "librdkafka++.so"
Generating pkg-config file rdkafka++.pc
Checking librdkafka++ integrity
librdkafka++.so.1              OK
librdkafka++.a                 OK
```

but finally, it tells me:

```
../src/librdkafka.a(rdkafka.o): In function `rd_atomic64_get':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:63: undefined reference to `__atomic_fetch_add_8'
../src/librdkafka.a(rdkafka_msg.o): In function `rd_atomic64_add':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:47: undefined reference to `__atomic_fetch_add_8'
../src/librdkafka.a(rdkafka_msg.o): In function `rd_atomic64_get':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:63: undefined reference to `__atomic_fetch_add_8'
../src/librdkafka.a(rdkafka_msg.o): In function `rd_atomic64_sub':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:55: undefined reference to `__atomic_fetch_sub_8'
../src/librdkafka.a(rdkafka_msg.o): In function `rd_atomic64_add':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:47: undefined reference to `__atomic_fetch_add_8'
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:47: undefined reference to `__atomic_fetch_add_8'
../src/librdkafka.a(rdkafka_topic.o): In function `rd_atomic64_add':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:47: undefined reference to `__atomic_fetch_add_8'
../src/librdkafka.a(rdkafka_topic.o): In function `rd_atomic64_get':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:63: undefined reference to `__atomic_fetch_add_8'
../src/librdkafka.a(rdkafka_partition.o): In function `rd_atomic64_get':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:63: undefined reference to `__atomic_fetch_add_8'
../src/librdkafka.a(rdkafka_partition.o):/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:47: more undefined references to `__atomic_fetch_add_8' follow
../src/librdkafka.a(rdkafka_partition.o): In function `rd_atomic64_sub':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:55: undefined reference to `__atomic_fetch_sub_8'
../src/librdkafka.a(rdkafka_broker.o): In function `rd_atomic64_add':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:45: undefined reference to `__atomic_fetch_add_8'
../src/librdkafka.a(rdkafka_broker.o): In function `rd_atomic64_get':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:63: undefined reference to `__atomic_fetch_add_8'
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:63: undefined reference to `__atomic_fetch_add_8'
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:63: undefined reference to `__atomic_fetch_add_8'
../src/librdkafka.a(rdkafka_broker.o): In function `rd_atomic64_sub':
/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/src/rdatomic.h:55: undefined reference to `__atomic_fetch_sub_8'
collect2: error: ld returned 1 exit status
make[5]: *** [rdkafka_example] Error 1
make[5]: Leaving directory `/home/ubuntu/Downloads/openwrt/build_dir/target-mipsel_24kec+dsp_musl-1.1.16/librdkafka-0.9.1/examples'
make[4]: *** [examples] Error 2
```

Any suggestion about this? Thanks so much!

**Comment by edenhill** [comment]
librdkafka v0.9.2 added support for falling back on mutexes when atomics are not available.
I suggest upgrading to librdkafka v0.9.5 (latest)

**Comment by ifding** [comment]
@edenhill Thanks so much! I will try to upgrade to the latest librdkafka later
