### ISSUE TITLE
about consuming the last message

### ISSUE THREAD

**Issue by zdftju** [edenhill/librdkafka#709]
Description
===========
hi!
I found a problem when I consumed the last message of a topic. The last message  always end with some messy code , but the others are  normal.

How to reproduce
================

Checklist
=========
Please provide the following information:
librdkafka version 0.9.1
apache kafka version 0.8.2.1

**Comment by edenhill** [comment]
What do you mean by messy code exactly?
Do you have an example?

**Comment by zdftju** [comment]
I produced 3 messages ,then consumed them  and print out
example:
    produce print :hello world1!
                           hello world2!
                           hello world3!

    consume print:hello world1!
                           hello world2!
                           hello world3! 姝ゅ閰嶇
                           %%consumer reached end of topic1 partition 0
(the messy code like this '姝ゅ閰嶇' ,it not belong to the message,but it always appeared the end of the last message)

**Comment by zdftju** [comment]
@edenhill 
I produced 3 messages ,then consumed them and print out
example:
produce print :hello world1!
                       hello world2!
                       hello world3!

consume print:hello world1!
                       hello world2!
                       hello world3! 姝ゅ閰嶇
                       %%consumer reached end of topic1 partition 0

(the messy code likes this '姝ゅ閰嶇' ,it not belongs to the message,but it always appeared the end of the last message)

**Comment by edenhill** [comment]
can you show the code that prints the message?

**Comment by zdftju** [comment]
@edenhill 
it's ok now,but I don't know why! I just  create a new topic and use it  and I will show you the code later .
it's really strange

**Comment by edenhill** [comment]
Do note that the message payloads are not null-terminated, so if you want to print them you must limit the print to the message length.
E.g.:
   printf("Message: %.*s\n", (int)rkmessage.len, rkmessage.payload)

**Comment by zdftju** [comment]
@edenhill
yes! it works ! Thank you very much! But why it always  occurs in consuming the last one?  and the others is ok.

**Comment by edenhill** [comment]
The Kafka framing probably causes an accidental nul termination between messages, but thats just pure luck, dont rely on it.
