### ISSUE TITLE
Mixed up error message when creating thread fails

### ISSUE THREAD

**Issue by ah-** [edenhill/librdkafka#712]
Rather minor, but stumbled upon this via https://github.com/ah-/rdkafka-dotnet/issues/45.

In https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.c#L1167 the return value of thrd_create is interpreted as a normal errno, which is wrong. 0 errno means no error, while a 0 return value of thrd_create means thrd_error.

This results in the somewhat confusing error message "Failed to create thread: No error (0)" if thread creation fails.

**Comment by Nagendra82** [comment]
Yes you are right.
Failed to create thread: No error (0)
