### ISSUE TITLE
 error while loading shared libraries: librdkafka++.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by generalibm** [edenhill/librdkafka#713]
Description
===========
I got this error message:

./a.out: error while loading shared libraries: librdkafka++.so.1: cannot open shared object file: No such file or directory

when I compiled file rdkafka_example.cpp and rdkafkacpp.h (thoes were just copied from XX/librdkafka/src-cpp/) and run ./a.out.

My command is:

g++ rdkafka_example.cpp -lpthread -lrdkafka++ -lz -lrt

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):v0.9.0
 - [ ] Apache Kafka version: 2.11-0.10.0.0
 - [ ] librdkafka client configuration:
 - [ ] Operating system:centos 6.5
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Did you do 'make install' and is the install path in your ld.so.conf? 

Also, you should upgrade to librdkafka 0.9.1

**Comment by generalibm** [comment]
yes, I have "make install"

but what "the install path" means , I just "git clone git@github.com:edenhill/librdkafka.git"  "home/XXX"

and how can I get upgrade?

Regards

**Comment by generalibm** [comment]
Thanks a lot , I had build successfuly!
