### ISSUE TITLE
./configure requirements

### ISSUE THREAD

**Issue by generalibm** [edenhill/librdkafka#717]
Description
===========

when I installed  librdkafka with
./configue

I got so many failed labels , such as 
checking for C compiler from CC env... failed

checking for liblz4 ... failed 

checking for libsasl2 failed 

....

is that mean I need to intall all the failed libs that is required?

because you I have posted this:

Requirements

The GNU toolchain
GNU make
pthreads
zlib (optional, for gzip compression support)
libssl-dev (optional, for SSL support)
libsasl2-dev (optional, for SASL support)

**Comment by edenhill** [comment]
If configure completes succesfully (telling you to run make) then you are fine, the missing libraries are optional.
