### ISSUE TITLE
Is there any way to return from the producer client when Kafka crashes while sending message to it?

### ISSUE THREAD

**Issue by nxgyzxw** [edenhill/librdkafka#719]
Description
===========
Dear Magnus,
When firstly sending messages to Kafka(only 1 broker), everything works fine. But during the transmission, the Kafka server somehow breaks down, and the producer client just hangs there so I can't start the next round transmission.

In the destructor function, I ues:
	if (producerHandle)
	{
		    while(producerHandle->outq_len() > 0)
    		{
    			    continue;
		    }
    		delete producerHandle;
	}

Perhaps it's because outq_len() is always greater than 0 ?  So this is a endless loop?
In the CONFIGURATION.md, I found some TimeOut Settings, and I think messages buffered in the local que should timed out somehow?

Please point out a solution to me, thank you .

Checklist
=========
Please provide the following information:

 - [ 0.9.0.1] librdkafka version (release number or git tag):
 - [ 0.8.2.1] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ RedHat] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by nxgyzxw** [comment]
I found some Info in #426 . Still this is the solution ?

**Comment by edenhill** [comment]
You are right, messages will remain in the internal producer queue up to message.timeout.ms.

There is currently no way to purge this queue manually, but if you register a delivery report callback you can keep track of which messages have been acked by the broker, and simply call rd_kafka_destroy() to destroy the producer instance along with any mesages currently queued.

**Comment by nxgyzxw** [comment]
Thank you.
