### ISSUE TITLE
Keep getting % Message delivery failed: Broker: Invalid message 

### ISSUE THREAD

**Issue by sububack** [edenhill/librdkafka#722]
Description
===========
I am keep getting "% Message delivery failed: Broker: Invalid message ". 

How to reproduce
================

Just create a producer and topic later. Then start producing message.
I am consistently hitting this issue, no idea why this occurs. Searching for documentation on when this could occur also.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): commit c51b83d9646e4ed030a47b975cd3caf908273f21
 - [ ] Apache Kafka version: 0.9
 - [ ] Operating system: Yocto 6
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide broker log excerpts

**Comment by edenhill** [comment]
Is there anything in the broker logs?

Try enabling   debug=protocol in librdkafka

**Comment by sububack** [comment]
LNX_CON0:Jul  8 03:38:56.144 : procA[379]: SUBU: Broker list: localhost.localdomain:4455.
LNX_CON0:Jul  8 03:38:56.157 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.157|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: Using (configuration fallback) 0.9.0 protocol features 
LNX_CON0:Jul  8 03:38:56.157 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.157|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature MsgVer1: Produce (2..2) NOT supported by broker 
LNX_CON0:Jul  8 03:38:56.157 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.157|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature MsgVer1: Fetch (2..2) NOT supported by broker 
LNX_CON0:Jul  8 03:38:56.158 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.157|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: Disabling feature MsgVer1 
LNX_CON0:Jul  8 03:38:56.158 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.158|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature ApiVersion: ApiVersion (0..0) NOT supported by broker 
LNX_CON0:Jul  8 03:38:56.158 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.158|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: Disabling feature ApiVersion 
LNX_CON0:Jul  8 03:38:56.158 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.158|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature BrokerBalancedConsumer: GroupCoordinator (0..0) supported by broker 
LNX_CON0:Jul  8 03:38:56.158 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.158|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature BrokerBalancedConsumer: OffsetCommit (1..2) supported by broker 
LNX_CON0:Jul  8 03:38:56.158 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.158|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature BrokerBalancedConsumer: OffsetFetch (1..1) supported by broker 
LNX_CON0:Jul  8 03:38:56.158 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.158|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature BrokerBalancedConsumer: JoinGroup (0..0) supported by broker 
LNX_CON0:Jul  8 03:38:56.158 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.158|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature BrokerBalancedConsumer: SyncGroup (0..0) supported by broker 
LNX_CON0:Jul  8 03:38:56.159 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.158|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature BrokerBalancedConsumer: Heartbeat (0..0) supported by broker 
LNX_CON0:Jul  8 03:38:56.159 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.159|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature BrokerBalancedConsumer: LeaveGroup (0..0) supported by broker 
LNX_CON0:Jul  8 03:38:56.159 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.159|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: Enabling feature BrokerBalancedConsumer 
LNX_CON0:Jul  8 03:38:56.159 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.159|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature ThrottleTime: Produce (1..2) supported by broker 
LNX_CON0:Jul  8 03:38:56.159 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.159|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap:  Feature ThrottleTime: Fetch (1..2) supported by broker 
LNX_CON0:Jul  8 03:38:56.159 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.159|APIVERSION|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: Enabling feature ThrottleTime 
LNX_CON0:Jul  8 03:38:56.170 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.169|SEND|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: Sent MetadataRequest (v0, 37 bytes, CorrId 1) 
LNX_CON0:Jul  8 03:38:56.304 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.304|RECV|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: Received MetadataResponse (v0, 57 bytes, CorrId 1, rtt 134.69ms) 
LNX_CON0:Jul  8 03:38:56.315 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.315|SEND|rdkafka#producer-1| localhost.localdomain:4455/0: Sent MetadataRequest (v0, 37 bytes, CorrId 2) 
LNX_CON0:Jul  8 03:38:56.324 : syslog_dev[115]: procA[379] PID-19432: %7|1467949136.324|RECV|rdkafka#producer-1| localhost.localdomain:4455/0: Received MetadataResponse (v0, 57 bytes, CorrId 2, rtt 8.04ms) 
LNX_CON0:Jul  8 03:38:57.227 : syslog_dev[115]: procA[379] PID-19432: %7|1467949137.227|SEND|rdkafka#producer-1| localhost.localdomain:4455/0: Sent MetadataRequest (v0, 37 bytes, CorrId 3) 
LNX_CON0:Jul  8 03:38:57.255 : syslog_dev[115]: procA[379] PID-19432: %7|1467949137.255|RECV|rdkafka#producer-1| localhost.localdomain:4455/0: Received MetadataResponse (v0, 83 bytes, CorrId 3, rtt 27.88ms) 
LNX_CON0:Jul  8 03:39:01.163 : syslog_dev[115]: procA[379] PID-19432: %7|1467949141.163|SEND|rdkafka#producer-1| localhost.localdomain:4455/0: Sent ProduceRequest (v1, 96 bytes, CorrId 4) 
LNX_CON0:Jul  8 03:39:01.276 : syslog_dev[115]: procA[379] PID-19432: %7|1467949141.275|RECV|rdkafka#producer-1| localhost.localdomain:4455/0: Received ProduceResponse (v1, 38 bytes, CorrId 4, rtt 111.61ms) 
LNX_CON0:Jul  8 03:39:01.376 : syslog_dev[115]: procA[379] PID-19432: %7|1467949141.376|RETRY|rdkafka#producer-1| localhost.localdomain:4455/0: Retrying ProduceRequest (v1, 96 bytes, retry 1/2) 
LNX_CON0:Jul  8 03:39:01.476 : syslog_dev[115]: procA[379] PID-19432: %7|1467949141.476|SEND|rdkafka#producer-1| localhost.localdomain:4455/0: Sent ProduceRequest (v1, 96 bytes, CorrId 5) 
LNX_CON0:Jul  8 03:39:01.484 : syslog_dev[115]: procA[379] PID-19432: %7|1467949141.484|RECV|rdkafka#producer-1| localhost.localdomain:4455/0: Received ProduceResponse (v1, 38 bytes, CorrId 5, rtt 7.58ms) 
LNX_CON0:Jul  8 03:39:01.484 : syslog_dev[115]: procA[379] PID-19432: %7|1467949141.484|RETRY|rdkafka#producer-1| localhost.localdomain:4455/0: Retrying ProduceRequest (v1, 96 bytes, retry 2/2) 
LNX_CON0:Jul  8 03:39:01.585 : syslog_dev[115]: procA[379] PID-19432: %7|1467949141.585|SEND|rdkafka#producer-1| localhost.localdomain:4455/0: Sent ProduceRequest (v1, 96 bytes, CorrId 6) 
LNX_CON0:Jul  8 03:39:01.594 : syslog_dev[115]: procA[379] PID-19432: %7|1467949141.594|RECV|rdkafka#producer-1| localhost.localdomain:4455/0: Received ProduceResponse (v1, 38 bytes, CorrId 6, rtt 8.40ms) 
LNX_CON0:Jul  8 03:39:06.146 : procA[379]: % Message delivery failed: Broker: Invalid message

**Comment by edenhill** [comment]
Okay, there should be an exception in the broker logs, can you paste that?

**Comment by sububack** [comment]
Hi, 
Where do I look for broker logs? /tmp/kafka-logs/<topic>-0/ had 000.log and it was empty. New to this let me know where to get broker logs from.

Meanwhile I have enabled most of the debugs and below are those logs


LNX_CON0:Jul  8 04:07:39.175 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.175|FEATURE|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: Updated enabled protocol features to BrokerBalancedConsumer,ThrottleTime 
LNX_CON0:Jul  8 04:07:39.176 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.176|STATE|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: Broker changed state CONNECT -> UP 
LNX_CON0:Jul  8 04:07:39.186 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.186|SEND|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: Sent MetadataRequest (v0, 37 bytes, CorrId 1) 
LNX_CON0:Jul  8 04:07:39.197 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.197|RECV|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: Received MetadataResponse (v0, 83 bytes, CorrId 1, rtt 10.21ms) 
LNX_CON0:Jul  8 04:07:39.198 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.198|STATE|rdkafka#producer-1| Topic procA changed state unknown -> exists 
LNX_CON0:Jul  8 04:07:39.198 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.198|PARTCNT|rdkafka#producer-1| Topic procA partition count changed from 0 to 1 
LNX_CON0:Jul  8 04:07:39.198 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.198|BRKDELGT|rdkafka#producer-1| Broker :0/internal is now leader for topic procA [0] with 0 messages (0 bytes) queued 
LNX_CON0:Jul  8 04:07:39.199 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.199|BRKMIGR|rdkafka#producer-1| Migrating topic procA [0] from (none) to :0/internal 
LNX_CON0:Jul  8 04:07:39.199 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.199|PARTCNT|rdkafka#producer-1| Partitioning 0 unassigned messages in topic procA to 1 partitions 
LNX_CON0:Jul  8 04:07:39.199 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.198|UPDATE|rdkafka#producer-1| localhost.localdomain:4455/bootstrap: NodeId changed from -1 to 0 
LNX_CON0:Jul  8 04:07:39.199 : syslog_dev[115]: procA[379] PID-22944: %7|1467950859.199|TOPBRK|rdkafka#producer-1| :0/internal: Topic procA [0]: joining broker 
LNX_CON0:Jul  8 04:07:39.200 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.199|UAS|rdkafka#producer-1| 0/0 messages were partitioned in topic procA 
LNX_CON0:Jul  8 04:07:39.200 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.199|UPDATE|rdkafka#producer-1| localhost.localdomain:4455/0: Name changed from localhost.localdomain:4455/bootstrap to localhost.localdomain:4455/0 
LNX_CON0:Jul  8 04:07:39.200 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.200|STATE|rdkafka#producer-1| localhost.localdomain:4455/0: Broker changed state UP -> UPDATE 
LNX_CON0:Jul  8 04:07:39.210 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.210|SEND|rdkafka#producer-1| localhost.localdomain:4455/0: Sent MetadataRequest (v0, 37 bytes, CorrId 2) 
LNX_CON0:Jul  8 04:07:39.210 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.210|STATE|rdkafka#producer-1| localhost.localdomain:4455/0: Broker changed state UPDATE -> UP 
LNX_CON0:Jul  8 04:07:39.214 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.213|RECV|rdkafka#producer-1| localhost.localdomain:4455/0: Received MetadataResponse (v0, 83 bytes, CorrId 2, rtt 3.18ms) 
LNX_CON0:Jul  8 04:07:39.214 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.214|TOPICUPD|rdkafka#producer-1| Topic procA [0] migrated from broker -1 to 0 
LNX_CON0:Jul  8 04:07:39.214 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.214|BRKDELGT|rdkafka#producer-1| Broker :0/internal no longer leader for topic procA [0] 
LNX_CON0:Jul  8 04:07:39.214 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.214|BRKDELGT|rdkafka#producer-1| Broker localhost.localdomain:4455/0 is now leader for topic procA [0] with 0 messages (0 bytes) queued 
LNX_CON0:Jul  8 04:07:39.214 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.214|BRKMIGR|rdkafka#producer-1| Migrating topic procA [0] from :0/internal to localhost.localdomain:4455/0 
LNX_CON0:Jul  8 04:07:39.214 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.214|PARTCNT|rdkafka#producer-1| Partitioning 0 unassigned messages in topic procA to 1 partitions 
LNX_CON0:Jul  8 04:07:39.215 : syslog_dev[115]: procA[379] PID-22943: %7|1467950859.214|UAS|rdkafka#producer-1| 0/0 messages were partitioned in topic procA 
LNX_CON0:Jul  8 04:07:39.215 : syslog_dev[115]: procA[379] PID-22944: %7|1467950859.215|TOPBRK|rdkafka#producer-1| :0/internal: Topic procA [0]: leaving broker (next leader localhost.localdomain:4455/0) 
LNX_CON0:Jul  8 04:07:39.314 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.314|TOPBRK|rdkafka#producer-1| localhost.localdomain:4455/0: Topic procA [0]: joining broker 
LNX_CON0:Jul  8 04:07:39.415 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.415|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:39.515 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.515|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:39.616 : syslog_dev[115]: procA[379] PID-22945: %7|1467950859.616|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.141 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.141|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.242 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.242|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 1+0 msgs 
LNX_CON0:Jul  8 04:07:44.242 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.242|PRODUCE|rdkafka#producer-1| localhost.localdomain:4455/0: produce messageset with 1 messages (41 bytes) 
LNX_CON0:Jul  8 04:07:44.242 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.242|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.243 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.242|SEND|rdkafka#producer-1| localhost.localdomain:4455/0: Sent ProduceRequest (v1, 96 bytes, CorrId 3) 
LNX_CON0:Jul  8 04:07:44.243 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.243|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.251 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.251|RECV|rdkafka#producer-1| localhost.localdomain:4455/0: Received ProduceResponse (v1, 38 bytes, CorrId 3, rtt 8.31ms) 
LNX_CON0:Jul  8 04:07:44.251 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.251|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.252 : syslog_dev[115]: procA[379] PID-22943: %7|1467950864.251|MSGSET|rdkafka#producer-1| localhost.localdomain:4455/0: MessageSet with 1 message(s) delivered 
LNX_CON0:Jul  8 04:07:44.252 : syslog_dev[115]: procA[379] PID-22943: %7|1467950864.252|MSGSET|rdkafka#producer-1| localhost.localdomain:4455/0: MessageSet with 1 message(s) encountered error: Broker: Invalid message 
LNX_CON0:Jul  8 04:07:44.352 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.352|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.352 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.352|RETRY|rdkafka#producer-1| localhost.localdomain:4455/0: Retrying ProduceRequest (v1, 96 bytes, retry 1/2) 
LNX_CON0:Jul  8 04:07:44.453 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.453|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.453 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.453|SEND|rdkafka#producer-1| localhost.localdomain:4455/0: Sent ProduceRequest (v1, 96 bytes, CorrId 4) 
LNX_CON0:Jul  8 04:07:44.453 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.453|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.461 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.461|RECV|rdkafka#producer-1| localhost.localdomain:4455/0: Received ProduceResponse (v1, 38 bytes, CorrId 4, rtt 7.56ms) 
LNX_CON0:Jul  8 04:07:44.461 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.461|MSGSET|rdkafka#producer-1| localhost.localdomain:4455/0: MessageSet with 1 message(s) delivered 
LNX_CON0:Jul  8 04:07:44.461 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.461|MSGSET|rdkafka#producer-1| localhost.localdomain:4455/0: MessageSet with 1 message(s) encountered error: Broker: Invalid message 
LNX_CON0:Jul  8 04:07:44.462 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.462|RETRY|rdkafka#producer-1| localhost.localdomain:4455/0: Retrying ProduceRequest (v1, 96 bytes, retry 2/2) 
LNX_CON0:Jul  8 04:07:44.462 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.462|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.563 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.562|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.563 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.563|SEND|rdkafka#producer-1| localhost.localdomain:4455/0: Sent ProduceRequest (v1, 96 bytes, CorrId 5) 
LNX_CON0:Jul  8 04:07:44.563 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.563|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.570 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.570|RECV|rdkafka#producer-1| localhost.localdomain:4455/0: Received ProduceResponse (v1, 38 bytes, CorrId 5, rtt 6.80ms) 
LNX_CON0:Jul  8 04:07:44.570 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.570|MSGSET|rdkafka#producer-1| localhost.localdomain:4455/0: MessageSet with 1 message(s) delivered 
LNX_CON0:Jul  8 04:07:44.570 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.570|MSGSET|rdkafka#producer-1| localhost.localdomain:4455/0: MessageSet with 1 message(s) encountered error: Broker: Invalid message 
LNX_CON0:Jul  8 04:07:44.570 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.570|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs 
LNX_CON0:Jul  8 04:07:44.671 : syslog_dev[115]: procA[379] PID-22945: %7|1467950864.671|TOPPAR|rdkafka#producer-1| localhost.localdomain:4455/0: procA [0] 0+0 msgs

**Comment by sububack** [comment]
Little more info:
I tried running with no-compression, still same issue. When I compiled my code in standalone gcc-4.7 it worked fine. When I compiled same code in gcc-4.2.1 I am hitting this Message is corrupt error.

The message is same until it left rd_kafka_msg_new0(). Not sure where the problem is, still trying to understand.

**Comment by edenhill** [comment]
The `"Hello, World"` string is just 12 bytes (13 with nul term), but you are indicating 15.
Now I dont think that matters for this test because it should reside in some ro data region, but correct that to at least put that out of the equation.
