### ISSUE TITLE
About pre-release

### ISSUE THREAD

**Issue by gabriel-ibarra** [edenhill/librdkafka#723]
Hi, I was working with the release 0.9.0.99, as long as I understand this is a pre-release version, is this assumption ok? So, do you recommend strongly an updating?
Also, is there any way to know the changelog between 0.9.0.99 and the final release 0.9.1?

Thanks

**Comment by edenhill** [comment]
The 0.9.0.99 tag was just used internally and was never meant for external use, to make matters worse I believe it was moved.
To get a changelog you can do:
```
  git fetch --all
  git log --onelinen 0.9.0.99..0.9.1
```

Anyway, 0.9.1 has alot of improvements and I strongly suggest upgrading.

**Comment by gabriel-ibarra** [comment]
ok, It is very helpful for me, thank you.
