### ISSUE TITLE
How long can a topic or handle (producer) destroy take?

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#725]
Hello, I ask this question in the context of an RdKafka observation i made. In RdKafka i notice that if i do not explicitly destroy the topic and producer then the application can crash at exit. This is the stack trace (Unhandled exception at 0x7724E843 (ntdll.dll) in WERFB97.tmp.mdmp: 0xC0000374: A heap has been corrupted (parameters: 0x77284270).):

![image](https://cloud.githubusercontent.com/assets/18578793/16690975/752ca19a-4522-11e6-97cc-e61810ab0bf8.png)

In .NET, finalizers have 2 seconds to complete. How long do you think a destroy of either topic or producer can take? Can it be more than 2 seconds? I wonder if one of the destroys takes more than 2 seconds and .NET stops it and moves to the next finalizer, thus breaking the correct destruction chain.

[https://github.com/ah-/rdkafka-dotnet/issues/50](url)

**Comment by edenhill** [comment]
topic_destroy() doesnt really free the underlying memory, the object is refcount based and the the last refcount for topics are decremented upon rd_kafka_destroy().

What I suggest you do is keep track of the allocated topic_t's in rdkafka-dotnet and destroy from the main handle's dispose function just prior to calling rd_kafka_destroy().

E.g.:
```
   dispose_the_producer_thing (..) {
        foreach cached topic {
             rd_kafka_topic_destroy(topic);
        }
        rd_kafka_destroy(rk); // blocks until fully destroyed
  }
```

**Comment by MaximGurschi** [comment]
Thank you. In case there is any confusion about what i am describing...
If i explicitly clean up topic handles and producer handles then all looks ok. If i leave it to .NET (i.e. do not dispose and just let the finalizers do their job) then sometimes it crashes.

What you describe in the above prototype is kinda what Andreas is doing.

**Comment by edenhill** [comment]
Okay, librdkafka requires topic_t objects to be symmetrically destroyed prior to the rd_kafka_t handle.

By symmetric I mean that each rd_kafka_topic_new() must have a corresponding rd_kafka_topic_t.


It is also prohibited to call any other librdkafka API simultaneously ot calling rd_kafka_destroy()

**Comment by MaximGurschi** [comment]
I'm not sure how to map those types to the .NET, but if you are saying that before destroying the producer all topics must be destroyed, then that is what i see Andreas has implemented.

**Comment by MaximGurschi** [comment]
What would happen if during a destroy there would still be a pending poll? By pending, i mean a poll that has yet to return?

**Comment by edenhill** [comment]
That's not allowed.

**Comment by MaximGurschi** [comment]
Ok, say the poll was given a timeout of 15 seconds. Say it is taking 5. On the 6th second i call destroy. That is not allowed? If that is true then it explains what is see in .NET.

**Comment by edenhill** [comment]
Correct.

**Comment by MaximGurschi** [comment]
Ok. Thank you very much! Will close once/if Andreas confirms.
