### ISSUE TITLE
Build librdkafka in VS 2013

### ISSUE THREAD

**Issue by TonysGit2015** [edenhill/librdkafka#728]
Description
===========
Many link errors: error LNK2019: Un recognized identifier _CRYPTO_num_locks, _CRYPTO_set_id_callback, _SSL_CTX_get_cert_store etc, so many SSL functions.
I downloaded OpenSSL_64bit binary version from  https://slproweb.com/products/Win32OpenSSL.html  and installed, and include the header files and libraries in to the project, still link errors.
Can anyone help to figure out which lib I missed?

How to reproduce
================
Just download librdkafka and OpenSSL_64 bit, link error will occur. I am using win7 PE 64-bit
Not sure which lib I missed cased the link error

Checklist
=========
Please provide the following information:
N/A
 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka's VS solution has the OpenSSL path hardcoded to C:\OpenSSL-Win32\

Make sure you either install it in the same location or change the IncludePath and LibraryPath settings of the solution accordingly.
