### ISSUE TITLE
rdkafka_performance.c type wrong unit

### ISSUE THREAD

**Issue by lmxhappy** [edenhill/librdkafka#733]
Description
===========
in print_stats(), in the if sentence  where otype & _OTYPE_SUMMARY is true in the producer mode, a variable's unit should be MB/s instead of Mb/s in the printf sentence. 
The variable  is   (float)((cnt.bytes_dr_ok) / (float)t_total).

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Could you submit a PR?
