### ISSUE TITLE
gzip or snappy compression both lead high CPU used

### ISSUE THREAD

**Issue by wangyinsheng** [edenhill/librdkafka#734]
Description
===========
hi there
  I am using librdkafka to produce data to kafka,while before set the compression code option the CPU only used 34%,when i set the compression as gzip the CPU used 95%,and change to snappy the CPU used 94%. It's too high. What may be the reason. What I can do to fix it.Thank you for any suggestion.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by wangyinsheng** [comment]
librdkafka version :0.8.6
Apache Kafka version:2.10-0.8.2.1
librdkafka client configuration:
`char errstr[512];
    rd_kafka_conf_set(conf, "compression.codec", "snappy", errstr, sizeof(errstr));`
Operating system:CentOs 6.6

**Comment by edenhill** [comment]
I believe this is expected, compression is a CPU intensive operation.

What average message rates and sizes do you have? Have you tried lz4 compression? (requires latest librdkafka master and liblz4)

**Comment by wangyinsheng** [comment]
sorry, I found the reason, I write too much logs while the request is too much 
I am using librdkafka with version 0.8.6, it not support lz4
