### ISSUE TITLE
A lot of "Receive failed: Disconnected" error messages in logs

### ISSUE THREAD

**Issue by zwaheed-rms** [edenhill/librdkafka#736]
Description
===========
I See a lot of error messages for producers and consumers in the kafka log messages. The messages are of the form:

%3|1469185516.707|ERROR|rdkafka#producer-1| some-server-1:9092/bootstrap: Receive failed: Disconnected
%3|1469185516.707|ERROR|rdkafka#producer-1| some-server-2:9092/bootstrap: Receive failed: Disconnected
%3|1469185516.707|ERROR|rdkafka#producer-1| some-server-3:9092/bootstrap: Receive failed: Disconnected

And for consumers it looks like:

%3|1469185216.195|FAIL|rdkafka#consumer-2| some-server-1:9092/bootstrap: Receive failed: Disconnected
%3|1469185216.195|FAIL|rdkafka#consumer-2| some-server-2:9092/bootstrap: Receive failed: Disconnected
%3|1469185216.195|FAIL|rdkafka#consumer-2| some-server-3:9092/bootstrap: Receive failed: Disconnected

I was ignoring them for the most part because the producers and consumers were able to send and receive messages fine despite these intermittent log messages. But now I am trying to debug some issue where the consumer is not getting messages for extended period of time.

Could these intermittent issues be the cause of this. What do these messages mean and what could be causing this error?

Also these messages appear to show up almost every 5 minutes once they start to appear, Is librdkafka trying to reconnect every 5 minutes?

How to reproduce
================
Happens intermittently on our testing/dev environments.

Checklist
=========
Please provide the following information:

 - [0.9.1] librdkafka version (release number or git tag):
 - [0.9.0] Apache Kafka version: 
 - [] librdkafka client configuration:
 - [Ubuntu 14] Operating system:
 - [No] Using the legacy Consumer
 - [Yes ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [Probably] Critical issue

**Comment by edenhill** [comment]
Could this be the broker's idle connection reaper? See issue #437

**Comment by zhangmoon** [comment]
i met this problem too. however my connection is not idle

**Comment by baiwfg2** [comment]
So did I. Often see such log, although producer still send ok.
