### ISSUE TITLE
is it possible to force a call of the rebalance callback?

### ISSUE THREAD

**Issue by abrugh** [edenhill/librdkafka#738]
Description
===========
During development and occasionally in the wild, it would be nice to kick a running process and have it jump back to the oldest offset (beginning) and start processing. A command line argument can achieve this but for something like a running daemon (where I normally want it to pick up where it left off if it does restart) I don't want to have to edit init scripts to add the flag, restart the service, then revert the script (or config file or what have you). I'd really like it if i could just send my process SIGUSR1 or something and be able to get it to reset the offset on the fly.

The process of figuring out how to change an offset lead me to a discussion in another issue where you suggest doing it in the rebalance_cb (there's a test case that actually shows how to do this for anyone else wondering) but I can't seem to find any way, correct or otherwise, to invoke the rebalance_cb myself as a lot of the machinery surrounding it seems private. Maybe what I'm trying to do is a bad idea in general?

Thanks!

**Comment by edenhill** [comment]
You cant (and shouldnt) trigger a rebalance_cb, but you are free to call assign() at any time to change the  current partition assignment and their offsets.

If you just like to change the offset of a partition after having started consumption you can call seek()

**Comment by abrugh** [comment]
Even with KafkaConsumer (new style, not legacy)?

**Comment by edenhill** [comment]
Yes, only culprit is that seek() must be called after consumtion for the given partition has started, which isnt really known to the application, but if it fails you can just try again in a little while.

**Comment by pachacutec** [comment]
I am trying to set offset, but I got  /** Wrong state */    RD_KAFKA_RESP_ERR__STATE = -172, I have to calle >3 times within  consume_poll calls. Is this OK? if I make this call without poll, I have to make >30 times. Is this the expected behavior? o I am missing some step o config

I am doing:
create a Config
create a topic_list
create kafka handler (consume)
assign the consumer with topic_list
consume_poll
  iter [ seek(consumer, offset) ]

**Comment by edenhill** [comment]
Yeah, that's the problem with seek(), it requires the internal fetcher to have started for the partition.

Did you try calling assign() instead?

**Comment by pachacutec** [comment]
You mean add offset to topic_list an the call assign? I just tried and it work ok!!!
I use rd_kafka_topic_partition_list_set_offset( (rd_kafka_topic_partition_list_t*) topic_part_list,
                                                                       topic_and_tenant_group, partition, offset);
prior to assign or subscribe
Thanks

**Comment by edenhill** [comment]
Yep, great!
