### ISSUE TITLE
Possible bug in rd_kafka_topic_partition_list_del_by_idx

### ISSUE THREAD

**Issue by diazdiego86** [edenhill/librdkafka#739]
Description
===========
When the memmove is called, the size argument shouldn't be 
`(rktparlist->cnt - idx) * sizeof(rd_kafka_topic_partition_t)`
?

Also, if we apply the previous change, I think the "@remark" in the following function, maybe, could not apply.
`/**
 * @brief Delete partition from list.
 *
 * @param rktparlist List to modify
 * @param topic      Topic name to match
 * @param partition  Partition to match
 *
 * @returns 1 if partition was found (and removed), else 0.
 *
 * @remark Any held indices to elems[] are unusable after this call returns 1.
 */

RD_EXPORT
int
rd_kafka_topic_partition_list_del (rd_kafka_topic_partition_list_t *rktparlist,
                    const char *topic, int32_t partition);`

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.1
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Ah yes. you are right, good catch!
