### ISSUE TITLE
Easily reproducible message timeouts

### ISSUE THREAD

**Issue by winbatch** [edenhill/librdkafka#74]
Hi - not sure if this is an rdkafka issue or an actual kafka issue.  (Not sure which one I want..)

I'm finding that when I send a lot of small messages, I frequently get message timeouts.  I see this in both using the api as well as using the sample programs.

Example:

./rdkafka_performance -P -t TENSECONDLOGS  -b masked.com:5757 -s 2 -a 2  -z gzip -p 1 -c  1000000 -X queue.buffering.max.messages=1000000

Message delivered: 471000 remain^M
Message delivered: 470000 remain^M
Message delivered: 469000 remain^M
Message delivered: 468000 remain^M
Message delivered: 467000 remain^M
Message delivered: 466000 remain^M
Message delivered: 465000 remain^M
Message delivered: 464000 remain^M
Message delivered: 463000 remain^M
Message delivered: 462000 remain^M
Message delivered: 461000 remain^M
Message delivered: 460000 remain^M

(sits and hangs here for a long time...and then:)
%4|1391743416.628|METADATA|rdkafka#producer-0| d146537-021.masked.com:5757/1052189105: Metadata request failed: Local: Message timed out^M
%4|1391743416.628|METADATA|rdkafka#producer-0| d146537-021.masked.com:5757/1052189105: Metadata request failed: Local: Message timed out^M
%4|1391743416.628|METADATA|rdkafka#producer-0| d146537-021.masked.com:5757/1052189105: Metadata request failed: Local: Message timed out^M
%4|1391743416.628|METADATA|rdkafka#producer-0| d146537-021.masked.com:5757/1052189105: Metadata request failed: Local: Message timed out^M
%4|1391743416.628|METADATA|rdkafka#producer-0| d146537-021.masked.com:5757/1052189105: Metadata request failed: Local: Message timed out^M
%4|1391743416.628|METADATA|rdkafka#producer-0| d146537-021.masked.com:5757/1052189105: Metadata request failed: Local: Message timed out^M
%4|1391743417.429|METADATA|rdkafka#producer-0| d146537-021.masked.com:5757/1052189105: Metadata request failed: Local: Message timed out^M
%4|1391743417.429|METADATA|rdkafka#producer-0| d146537-021.masked.com:5757/1052189105: Metadata request failed: Local: Message timed out^M
%4|1391743417.429|METADATA|rdkafka#producer-0| d146537-021.masked.com:5757/1052189105: Metadata request failed: Local: Message timed out^M
%4|1391743417.429|METADATA|rdkafka#producer-0| d146537-021.masked.com:5757/1052189105: Metadata request failed: Local: Message timed out^M

if I strace while its hanging, I see:

futex(0x1374160, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x137418c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 7175, {1391707106, 253292000}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x1374160, FUTEX_WAKE_PRIVATE, 1) = 0

I sometimes see this on the cluster (but definitely not always):

[2014-02-06 22:02:54,585] INFO Client session timed out, have not heard from server in 4815ms for sessionid 0x343c4f6383400a7, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2014-02-06 22:02:54,689] INFO zookeeper state changed (Disconnected) (org.I0Itec.zkclient.ZkClient)
[2014-02-06 22:02:55,201] INFO Opening socket connection to server zookeeperlog1.masked.com/10.52.189.106:5700 (org.apache.zookeeper.ClientCnxn)
[2014-02-06 22:02:55,202] INFO Socket connection established to zookeeperlog1.masked.com/10.52.189.106:5700, initiating session (org.apache.zookeeper.ClientCnxn)
[2014-02-06 22:02:55,207] INFO Session establishment complete on server zookeeperlog1.masked.com/10.52.189.106:5700, sessionid = 0x343c4f6383400a7, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2014-02-06 22:02:55,208] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)

do you think I should simply increase the zookeeper timeout?  (note it's running on the same host as the cluster node).   Have you seen this before?

**Comment by mikesparr** [comment]
@edenhill could this be cause of what I'm seeing in logs? should I explicitly add `topic.message.timeout.ms` to my confluent-kakfa-python producer class?

~~~
2016-09-16 08:56:01,425 - INFO - extractor_rets.py - Sleeping for 5 minutes (300 seconds)
2016-09-16 09:01:08,140 - INFO - extractor_rets.py - Processed 0 rows
2016-09-16 09:01:08,141 - INFO - extractor_rets.py - Sleeping for 5 minutes (300 seconds)
%4|1474038111.837|METADATA|app2#producer-1| queue4:9092/4: Metadata request failed: Local: Timed out
%3|1474038111.837|FAIL|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%3|1474038111.837|ERROR|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%4|1474038174.946|METADATA|app2#producer-1| queue4:9092/4: Metadata request failed: Local: Timed out
%3|1474038174.946|FAIL|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%3|1474038174.946|ERROR|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%4|1474038238.055|METADATA|app2#producer-1| queue4:9092/4: Metadata request failed: Local: Timed out
%3|1474038238.055|FAIL|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%3|1474038238.055|ERROR|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%3|1474038252.485|FAIL|app2#producer-1| queue4:9092/4: Receive failed: Connection reset by peer
%3|1474038252.485|ERROR|app2#producer-1| queue4:9092/4: Receive failed: Connection reset by peer
%4|1474038300.358|METADATA|app2#producer-1| queue4:9092/4: Metadata request failed: Local: Timed out
%3|1474038314.380|FAIL|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%3|1474038314.380|ERROR|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%4|1474038316.394|METADATA|app2#producer-1| queue4:9092/4: Metadata request failed: Local: Timed out
2016-09-16 09:06:13,052 - INFO - extractor_rets.py - Processed 0 rows
2016-09-16 09:06:13,053 - INFO - extractor_rets.py - Sleeping for 5 minutes (300 seconds)
%3|1474038375.488|FAIL|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%3|1474038375.488|ERROR|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%4|1474038377.501|METADATA|app2#producer-1| queue4:9092/4: Metadata request failed: Local: Timed out
%3|1474038436.593|FAIL|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%3|1474038436.593|ERROR|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%4|1474038438.607|METADATA|app2#producer-1| queue4:9092/4: Metadata request failed: Local: Timed out
%3|1474038497.699|FAIL|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%3|1474038497.699|ERROR|app2#producer-1| queue4:9092/4: 3 request(s) timed out: disconnect
%4|1474038499.713|METADATA|app2#producer-1| queue4:9092/4: Metadata request failed: Local: Timed out
~~~

**Comment by edenhill** [comment]
The Metadata timeouts are an indication of some problem with the broker(s) or network, they should typically not time out. Check your broker logs.

**Comment by mikesparr** [comment]
I tried setting that in Producer client configuration and see this error:

~~~
2016-09-16 10:14:00,476 - ERROR - stream_producer.pyc - Error [KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "message.timeout.ms""}] publishing data at topic [rets.rayac.Office]:[None]-[rayac:1347]
~~~

But in your docs I see it, and configured same as other settings?

<img width="1173" alt="screen shot 2016-09-16 at 10 18 21 am" src="https://cloud.githubusercontent.com/assets/5553105/18593124/3a9c1a40-7bf7-11e6-9c96-421d47de3c81.png">

Configured...

![screen shot 2016-09-16 at 10 17 38 am](https://cloud.githubusercontent.com/assets/5553105/18593137/45534be8-7bf7-11e6-95bc-7718f3cdeec1.png)

**Comment by mikesparr** [comment]
I'll try request.timeout.ms instead since not "local" setting from python client. Still trying to figure out broker issue. I'm curious if perhaps the buffer size being 1 million could be impacting the Open file limits on server? Is a file created for each buffered message and perhaps that explains why after they all get running we hit that ceiling and crash brokers? Sorry to hijack thread but his errors seem all too similar to what I'm experiencing.

**Comment by edenhill** [comment]
`message.timeout.ms` is a topic-level config property so you will need to set it in the `"default.topic.config"` sub-dict.

Messages are written to log segments, when a log segment reaches a certain configured sized it is rolled over and a new log segment is created.
So yes, the message size * message count does affect the number of open log segments.
Please see broker properties `log.segment.bytes` and `log.roll.*` here:
http://kafka.apache.org/documentation.html#brokerconfigs

**Comment by mikesparr** [comment]
Thanks for clarification. Crazy thing happened. On a whim I updated my Ansible playbooks and reduced 4-node cluster to 3-node for Zookeeper/Kafka and Cassandra I removed 4th node too. Restarted everything and ETL running fine; no issues whatsoever.

Is it possible issues caused by having an even number of servers vs. and odd number? I did read that Zookeeper should be Odd number but very surprised if that would actually cause all these issues. Now everything is working 100% moving from 4 node to 3 node.

**Comment by AKR2015** [comment]
Could any please help on this below issue..

I am using Kafka 9.0.1
rdkafka :9.0.1
librdkafka: 9.0.1

thank you for your help.

3|2016-10-21 10:26:33.546|rdkafka#producer-37|FAIL| usiadansetl04:9092/2: 3 request(s) timed out: disconnect
3|2016-10-21 10:26:33.546|rdkafka#producer-37|ERROR| usiadansetl04:9092/2: 3 request(s) timed out: disconnect

3|2016-10-21 10:26:35.733|rdkafka#producer-37|FAIL| usiadansetl04:9092/2: 3 request(s) timed out: disconnect
3|2016-10-21 10:26:35.733|rdkafka#producer-37|ERROR| usiadansetl04:9092/2: 3 request(s) timed out: disconnect
5|2016-10-21 10:26:37.093|rdkafka#producer-37|FAIL| usiadansetl04:9092/2: Connection closed
3|2016-10-21 10:26:37.093|rdkafka#producer-37|ERROR| usiadansetl04:9092/2: Connection closed
4|2016-10-21 10:26:41.186|rdkafka#producer-41|METADATA| usiadansetl03:9092/1: Metadata request failed: Local: Timed out
rdkafka#consumer-64|FAIL| 10.61.19.88:9092/bootstrap: Connection closed
rdkafka#consumer-64|ERROR| 10.61.19.88:9092/bootstrap: Connection closed
rdkafka#consumer-62|FAIL| 10.61.19.88:9092/bootstrap: Connection closed
rdkafka#consumer-62|ERROR| 10.61.19.88:9092/bootstrap: Connection closed
rdkafka#producer-61|FAIL| 10.61.19.88:9092/bootstrap: Connection closed

if i increase the ****batch.num.messages****,  the error i get in broker log is similar to below

org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:91)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:71)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:153)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:134)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:286)
        at kafka.network.Processor.run(SocketServer.scala:413)
        at java.lang.Thread.run(Thread.java:745)
[2016-10-06 22:17:42,001] WARN Unexpected error from /10.61.48.28; closing connection (org.apache.kafka.common.network.Selector)
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1969447758 larger than 104857600)
        at
