### ISSUE TITLE
Lack of RdKafka::KafkaConsumer::consume_callback

### ISSUE THREAD

**Issue by lambdaknight** [edenhill/librdkafka#740]
On RdKafka::Consumer, there is the handy consume_callback method, but it is nowhere to be found on RdKafka::KafkaConsumer. Is there a technical reason for this or just an oversight?

**Comment by cedarwu** [comment]
Same question.
I want to use high level RdKafka::KafkaConsumer in C++, but why no consume_callback in KafkaConsumer.

**Comment by edenhill** [comment]
fixed on master
