### ISSUE TITLE
librdkafka windows library and Unicode compatibility.

### ISSUE THREAD

**Issue by aczire** [edenhill/librdkafka#750]
Description
===========
From the first look it seems like librdkafka uses non-unicode compatible datatypes for example 'char' instead of 'wchar'. 
Any idea whether the librdkafka is compatible with Windows Unicode environment. For example, if the input is unicode characters (let's assume my Windows Locale is French or German), how well the librdkafka adjusts to it?

btw, the query is specific to Windows library.

**Comment by edenhill** [comment]
Are you talking about configuration properties or message payload/keys?
For the latter case librdkafka does not care about encoding, it produces the bytes exactly as passed by the app, and provides the same raw binary payload in the consume interfaces.

For configuration properties I guess that path names could be subject to unicode strings, but path names are only used by the outdated legacy consumer file based offset storages so not a problem.

**Comment by aczire** [comment]
Cool. Thanks for the clarification. btw, i'm worried only about the message/payload. Good to see it is the same byte array at the consume interface as well.
