### ISSUE TITLE
how to read 400 partitions from kafka 0.8.1 cluster

### ISSUE THREAD

**Issue by dean-chen** [edenhill/librdkafka#751]
Description
===========
I am using librdkafka 0.8 branch to read 400 partitions data from kafka 0.8.1 cluster. I create 20 threads, each thread reads data from 20 partitions. But it works slowly, some messages are delayed 4-7 hours.
Each thread reads 10 messages from one partition then read 10 messages from next partitions. I am using consume and poll functions to do this.
All messages read from partitions are written to local log file via boost log,
no mutex or queue between threads are used.
My Questions:
1. I need a better way to improve the performance, or if my way is not correct, please tell me.
2. No consumer group means lost data? 
One friend said if I am not using consumer group, this will cause my app uses default group, if other apps are using default group, my app cannot read messages consumed by other apps.
3. My app can process part of partitions. 
I can deploy my app on 4 computers, each app can handle 100 partitions. Does this way improve performance?

How to reproduce
================
```
		/*
		 * read 10 messages from each patition, then process another partition
		 */
		while (true) {
			for (auto info: partition_infos) {
				BOOST_LOG_SEV(lg, trace) << "for loop, partition index: " << info->partition_idx;
				int timeout = 1000;
				for (int i = 0; i < 10; ++i) {
					std::unique_ptr<RdKafka::Message> msg(info->consumer->consume(info->topic, info->partition_idx, timeout));
					try {
						if (MyConsumer::Process(msg.get())) {
							info->consumer->poll(0);
							time_t timer;
							time(&timer);
							BOOST_LOG_SEV(lg, trace) << "time after read:" << std::this_thread::get_id() << ", " << TimeHelper::GetLocalTimeString(timer);
						} else {
							std::this_thread::sleep_for (std::chrono::seconds(10));
							time_t timer;
							time(&timer);
							BOOST_LOG_SEV(lg, trace) << "time after pause:" << std::this_thread::get_id() << ", " << TimeHelper::GetLocalTimeString(timer);
							info->consumer->poll(0);
						}
					} catch (KafkaError const& ex) {
						BOOST_LOG_SEV(lg, error) << "catch exception when processing kafka message, quit now: "  <<  ex.what();
						break;
					}
				}
			}
		}
```

Checklist
=========
Please provide the following information:

 - [ 0.8 branch ] librdkafka version (release number or git tag):
 - [ 0.8.1 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ CentOS 6.4 ] Operating system:
 - [ Yes ] Using the legacy Consumer
 - [ I do not know ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ performance ] Critical issue

**Comment by edenhill** [comment]
I think the low performance is inherent to your loop, not librdkafka.
You are looping over 400 partitions, calling consume 10 times for each partition, each call with a max timeout of 1000ms (e.g., if thee partition you consume lack new messages the consume() call will block for 1 second).

Is it important to your application to read exactly 10 messages, for each partition, in order? Or would you be fine with getting messages from any partition?

In the latter case I suggest you upgrade to latest librdkafka and use the new high-level KafkaConsumer interface and assign() to assign the partitions to consume.
With this newer interface you consume from all assigned partitions with a single consume() call.

**Comment by dean-chen** [comment]
Hi, edenhill:
  My thread is looping over 20 partitions, (400 partitions / 20 threads).
I can let it read one message using consume function for one partition instead of reading 10 messages. And try tomorrow to see if it improved.
  I need my app can be deployed on a few computers to scale out because data in kafka cluster is so huge. I need each process on one computer can read part of partitions. For example, a, b, c and d are running on four computers. a consume data from [0, 100) partitions, b for [100, 200), c for [200, 300), d for [300, 400). Is there any better way than my current solution?
  If I upgrade to latest librdkafka, can I still access kafka 0.8.1 cluster, can I use consume group?

**Comment by edenhill** [comment]
You can still access kafka 0.8.1 broker with latest librdkafka (See here: https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility)  but consumer groups requires broker 0.9 or later

**Comment by dean-chen** [comment]
If I cannot use consumer group for kafka 0.8.1 cluster limit, does this cause message lost?

**Comment by edenhill** [comment]
There will not be message loss, but it is up to your application to decide which partitions to consume.

**Comment by dean-chen** [comment]
Thanks for quick response. About scale out requirement. Any suggestion? Is my current way right or wrong?

> I need my app can be deployed on a few computers to scale out because data in kafka cluster is too huge. I need each process on one computer can read part of partitions. For example, a, b, c and d are running on four computers. a consumes data from [0, 100) partitions, b for [100, 200), c for [200, 300), d for [300, 400). Is there any better way than my current solution?

**Comment by edenhill** [comment]
Yes, that is the typical scale out strategy, assign a bunch of partitions to each consumer and let it operate independently.
This is also exactly what the balanced consumer groups in >= 0.9 does  (and in Scala 0.8 clients)
