### ISSUE TITLE
Failed to build librdkafka on Solaris 10(Sparc)

### ISSUE THREAD

**Issue by jvdvjvdv** [edenhill/librdkafka#752]
Description
===========
Failed to build librdkafka on Solaris 10.  

Questions 1:
Is it ok for gmake to invoke  "/usr/ccs/bin/as" instead of "/usr/sfw/libexec/gcc/sparc-sun-solaris2.10/3.4.3/as" which I also found on the Solaris box?

Question 2:
I want to consume/call librdkafka from an application that is compiled with the Sun Studio compilers.   Will a binary created via Sun tool chain be able to use a sharedlibrary(librdkafka) created with GNU tool chain? 

How to reproduce
================
./configure
gmake
gmake[1]: Entering directory `/export/home/nevapp/librdkafka/librdkafka-master/src'
gcc -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -D__EXTENSIONS__  -c rdkafka.c -o rdkafka.o
rdkafka.c:59: warning: missing braces around initializer
rdkafka.c:59: warning: (near initialization for `rd_kafka_global_init_once.__pthread_once_pad')
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 50928: error: statement syntax
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 50928: error: statement syntax
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 50928: error: statement syntax
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 51686: error: statement syntax
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 51686: error: statement syntax
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 51686: error: statement syntax
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 60707: error: statement syntax
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 60707: error: statement syntax
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 60707: error: statement syntax
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 60726: error: statement syntax
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 60726: error: statement syntax
/usr/ccs/bin/as: "/var/tmp//ccJyP4et.s", line 60726: error: statement syntax
gmake[1]: *** [rdkafka.o] Error 1
gmake[1]: Leaving directory `/export/home/nevapp/librdkafka/librdkafka-master/src'
gmake: *** [libs] Error 2

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
Current Master
/librdkafka-master> grep -i ver Makefile.config
RDKAFKA_VERSION_STR=    0.9.1
MKL_APP_VERSION=        0.9.1

 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 uname -a
SunOS nevdisdev 5.10 Generic_150400-30 sun4v sparc SUNW,SPARC-Enterprise-T5120

gcc -v
Reading specs from /usr/sfw/lib/gcc/sparc-sun-solaris2.10/3.4.3/specs
Configured with: /sfw10/builds/build/sfw10-patch/usr/src/cmd/gcc/gcc-3.4.3/configure --prefix=/usr/sfw --with-as=/usr/ccs/bin/as --without-gnu-as --with-ld=/usr/ccs/bin/ld --without-gnu-ld --enable-languages=c,c++ --enable-shared
Thread model: posix
gcc version 3.4.3 (csl-sol210-3_4-branch+sol_rpath)

 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Hi,

**Question 1:**
librdkafka requires a complete GNU toolchain (gcc) to build.

**Question 2:**
I dont know whether it works to link GNU built libraries with SunStudio built apps, you'll need to consult corresponding system and toolchain documentation to find out.

**Comment by jvdvjvdv** [comment]
Installed a GNU tool chain rdkafka,c compiled but rdkafka_broker.c failed.
I used gcc version 5.2.0 (GCC)
Will try to install version gcc version 4.x and see if that helps. Googling seems to indicate that it might be related too differences between VER 4 and VER 5.
Might be related/caused by #define _XOPEN_SOURCE

/export/home/jvdv/librdkafka-master> gmake
gmake[1]: Entering directory '/export/home/jvdv/librdkafka-master/src'
gcc -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -D__EXTENSIONS__  -c rdkafka_broker.c -o rdkafka_broker.o
In file included from /usr/include/signal.h:18:0,
                 from rdkafka_broker.c:37:
/opt/csw/lib/gcc/sparc-sun-solaris2.10/5.2.0/include-fixed/sys/feature_tests.h:346:2: error: #error "Compiler or options invalid for pre-UNIX 03 X/Open applications     and pre-2001 POSIX applications"
 #error "Compiler or options invalid for pre-UNIX 03 X/Open applications \
  ^
rdkafka_broker.c: In function 'rd_kafka_compress_MessageSet_buf':
rdkafka_broker.c:2396:22: warning: unused variable 'err' [-Wunused-variable]
  rd_kafka_resp_err_t err;
                      ^
rdkafka_broker.c: In function 'rd_kafka_messageset_handle':
rdkafka_broker.c:3395:37: warning: variable 'err' set but not used [-Wunused-but-set-variable]
                 rd_kafka_resp_err_t err = RD_KAFKA_RESP_ERR_NO_ERROR;
                                     ^
../mklove/Makefile.base:77: recipe for target 'rdkafka_broker.o' failed
gmake[1]: *** [rdkafka_broker.o] Error 1
gmake[1]: Leaving directory '/export/home/jvdv/librdkafka-master/src'
Makefile:20: recipe for target 'libs' failed
gmake: *** [libs] Error 2

**Comment by edenhill** [comment]
If you are willing to work out the needed changes I'd be happy to accept a PR.

**Comment by jvdvjvdv** [comment]
Looks like it is compiling with version 4.9.2
gcc -v
Reading specs from /opt/csw/lib/gcc/sparc-sun-solaris2.10/4.9.2/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/csw/libexec/gcc/sparc-sun-solaris2.10/4.9.2/lto-wrapper
Target: sparc-sun-solaris2.10
Configured with: /home/dam/mgar/pkg/gcc4/trunk/work/solaris10-sparc/build-isa-sparcv8plus/gcc-4.9.2/configure --prefix=/opt/csw --exec_prefix=/opt/csw --bindir=/opt/csw/bin --sbindir=/opt/csw/sbin --libexecdir=/opt/csw/libexec --datadir=/opt/csw/share --sysconfdir=/etc/opt/csw --sharedstatedir=/opt/csw/share --localstatedir=/var/opt/csw --libdir=/opt/csw/lib --infodir=/opt/csw/share/info --includedir=/opt/csw/include --mandir=/opt/csw/share/man --enable-cloog-backend=isl --enable-java-awt=xlib --enable-languages=ada,c,c++,fortran,go,java,objc --enable-libada --enable-libssp --enable-nls --enable-objc-gc --enable-threads=posix --program-suffix=-4.9 --with-cloog=/opt/csw --with-gmp=/opt/csw --with-included-gettext --with-ld=/usr/ccs/bin/ld --without-gnu-ld --with-libiconv-prefix=/opt/csw --with-mpfr=/opt/csw --with-ppl=/opt/csw --with-system-zlib=/opt/csw --with-as=/usr/ccs/bin/as --without-gnu-as
Thread model: posix
gcc version 4.9.2 (GCC)

Checking  integrity
CONFIGURATION.md               OK
examples/rdkafka_example       OK
examples/rdkafka_performance   OK
examples/rdkafka_example_cpp   OK
gmake[1]: Entering directory '/export/home/jvdv/librdkafka-master/src'
Checking librdkafka integrity
librdkafka.so.1                OK
librdkafka.a                   OK
Symbol visibility              OK
gmake[1]: Leaving directory '/export/home/jvdv/librdkafka-master/src'
gmake[1]: Entering directory '/export/home/jvdv/librdkafka-master/src-cpp'
Checking librdkafka++ integrity
librdkafka++.so.1              OK
librdkafka++.a                 OK
gmake[1]: Leaving directory '/export/home/jvdv/librdkafka-master/src-cpp'

find . -name "*so*"
./src-cpp/librdkafka++.so.1
./src-cpp/librdkafka++.so
./mklove/modules/configure.socket
./src/librdkafka.so.1
./src/librdkafka.so
./packaging/debian/source
