### ISSUE TITLE
Getting crashes with producer and RK_MSG_FREE flag

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#754]
Description
===========
I am currently using RK_MSG_COPY in my producer->produce() call
my code sums up to :
```
RdKafka::Message *msg = consumer->consume(timeout_ms);
if(msg->err() == RdKafka::ERR_NO_ERROR) {

producer->produce(topic,RdKafka::Topic::PARTITION_UA, RdKafka::Producer::RK_MSG_COPY,
		  msg->payload(), msg->len(), msg->key(), NULL);
}
delete (msg);

```

so I have tried to change the code with **RK_MSG_FREE** instead of **RK_MSG_COPY**
and removed the **delete(msg)**

but then I get a crash with error 
> : munmap_chunk(): invalid pointer: 0x00007ffa88002818 ***

not long after having called produce().

call stack :

> 1  __GI_raise                              raise.c                   54   0x7ffff69cd418 
> 2  __GI_abort                              abort.c                   89   0x7ffff69cf01a 
> 3  __libc_message                          libc_fatal.c              175  0x7ffff6a0f72a 
> 4  malloc_printerr                         malloc.c                  5007 0x7ffff6a1bc18 
> 5  munmap_chunk                            malloc.c                  2843 0x7ffff6a1bc18 
> 6  __GI___libc_free                        malloc.c                  2964 0x7ffff6a1bc18 
> 7  rd_free                                 rd.h                      99   0x7ffff5b6ffee 
> 8  rd_kafka_msg_destroy                    rdkafka_msg.c             46   0x7ffff5b6ffee 
> 9  rd_kafka_poll_cb                        rdkafka.c                 2122 0x7ffff5b5bf7e 
> 10 rd_kafka_q_serve                        rdkafka_queue.c           373  0x7ffff5b7e19a 
> 

has anyone seen any bug related to RK_MSG_FREE lately ?
Thank you.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [c577bcf3aa82f1cbe3b8cc28db5ce0b8887f6abd ] librdkafka version (release number or git tag):
 - [0.10 ] Apache Kafka version: 
 - [ 0.10.0.0] librdkafka client configuration:
 - [ Ubuntu16.04 ] Operating system:
 - [ no] Using the legacy Consumer
 - [ yes but problem is on producer] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Remeber that produce() is an asynchronous call, it will enqueue the message in an internal librdkafka queue and then return, so the payload you pass to it must either persist or be copied (_MSG_F_COPY).

In your example you pass it the payload of a consumed message which you then delete just after the produce() call.
 

Additionally, when using MSG_F_FREE you must pass a malloc():ed pointer, but you are passing msg->payload() which you do not have control over (it might be allocated, or might be inside a larger allocation), either way it is not safe to assume it is a straight up malloc() and thus you must not use _MSG_F_FREE with msg->payload()

**Comment by edenhill** [comment]
If you want to avoid copying the data you could register a delivery report callback (dr_msg_cb) and pass the 'msg' as the msg_opaque value to produce(neither COPY or FREE), then in the dr_msg_cb() you would delete the 'msg'.

**Comment by vin-d** [comment]
Thank you, that's what I've missed about the the flag on the produce() call.
It's exactly what I wanted. I have mistakenly assumed that either RK_MSG_FREE and RK_MSG_COPY was a required arg but you can pass value 0 instead;

Now that I read the doc again it all makes sense : 
> msgflags is **zero** or more of the following flags OR:ed together

And now that you outline it I also understand, wha't wrong with my example which mixes  RdKafka::Message constructor from inside the consume and free() from the produce() process.
