### ISSUE TITLE
How do I reduce log level when using Python client for librdkafka?

### ISSUE THREAD

**Issue by mikesparr** [edenhill/librdkafka#755]
Description
===========
I am using Python client wrapper for librdkafka and see very verbose output for connection and heartbeat in logs. It's not clear how to set the log level to INFO level so not so verbose.  It would be nice if the documentation were a little more descriptive instead of numerical values 1-8 (default 6) as it's not clear which direction to go without trial/error.

How to reproduce
================
Start app and view logs with a lot of output like this:

~~~
%7|1471039430.968|FETCH|rdkafka#consumer-1| queue1:9092/1: Fetch for 2 toppars, fetching=1, backoff=-111378ms
%7|1471039430.968|FETCH|rdkafka#consumer-1| queue2:9092/2: Topic rets.gacar.OpenHouse [0] MessageSet size 0, error "Success", MaxOffset 563, Ver 3/3
%7|1471039430.968|FETCH|rdkafka#consumer-1| queue2:9092/2: Topic rets.gacar.Media [0] MessageSet size 0, error "Success", MaxOffset 0, Ver 3/3
%7|1471039430.968|FETCH|rdkafka#consumer-1| queue2:9092/2: Fetch reply: Success
%7|1471039430.968|FETCH|rdkafka#consumer-1| queue2:9092/2: Fetch topic rets.gacar.OpenHouse [0] at offset 563 (v3)
%7|1471039430.968|FETCH|rdkafka#consumer-1| queue2:9092/2: Fetch topic rets.gacar.Media [0] at offset 0 (v3)
%7|1471039430.968|FETCH|rdkafka#consumer-1| queue2:9092/2: Fetch 2/2/2 toppar(s)
%7|1471039430.968|FETCH|rdkafka#consumer-1| queue2:9092/2: Fetch for 2 toppars, fetching=1, backoff=-111378ms
%7|1471039430.968|SEND|rdkafka#consumer-1| queue1:9092/1: Sent FetchRequest (v1, 114 bytes @ 0, CorrId 121)
%7|1471039430.968|SEND|rdkafka#consumer-1| queue2:9092/2: Sent FetchRequest (v1, 117 bytes @ 0, CorrId 116)
%7|1471039430.993|SEND|rdkafka#consumer-1| queue4:9092/4: Sent HeartbeatRequest (v0, 84 bytes @ 0, CorrId 200)
%7|1471039430.993|RECV|rdkafka#consumer-1| queue4:9092/4: Received HeartbeatResponse (v0, 2 bytes, CorrId 200, rtt 0.34ms)
~~~

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 0.10
 - [ ] librdkafka client configuration:
 - [ ] Operating system: Ubuntu 14.04.5 LTS
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The log levels relate to the standard syslog log levels, where 0 is EMERGENCY and 7 is DEBUG.
See "Severity levels" here: https://en.wikipedia.org/wiki/Syslog

The log excerpt you provided are debug logs - debugging must be explicitly enabled through the `debug` config setting and they should generally be left turned off unless you are actively troubleshooting an issue. So please make sure you are not setting the "debug" property.

**Comment by mikesparr** [comment]
Thanks!
