### ISSUE TITLE
Failed to create thread: Success(0)

### ISSUE THREAD

**Issue by anakjh** [edenhill/librdkafka#757]
Description
===========
Im trying to create some producers(about 90) in a thread,then the following ERROR occurred.
"Failed to create thread: Success(0)" or "Unable to create broker thread: Success (0)"
.....failed ,but errno is 0. Does anybody have met the similar  problem?
Share your experiences would be great; Ty very much!

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [Linux hp181 ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Why are you creating 90 producers?
You would typically only need to do that if you are to connect to 90 different Kafka clusters.

Any way, librdkafka creates a number of threads per instance internally and with your number of instances you are hitting the thread / proc limit.
See here:
http://stackoverflow.com/questions/344203/maximum-number-of-threads-per-process-in-linux

**Comment by anakjh** [comment]
OMG, that's  the author !!!!awesome! 
I need to analyze and classify some data ,then send them to diffrent topic( about 30kind of topic). so at least i need 30 producers.  but  in test, i have a problem, there are  almost 300,000 msgs be wrote to each  producer'queue per second,  I think that's to much ,so "	ERR__QUEUE_FULL = -184," occurred.  THEN i try to increase the number of producer in order to reduce the amount of each producer 'queue. 
Could u give me some advises about my problem? ty very much.
by the way ,i made a test about  the " thread / proc limit", creating 1000 thread is ok. 
My English is terrible. - -! forgive me!!

**Comment by anakjh** [comment]
By the way ,I  have notice that " An `rd_kafka_topic_t` object may only be used with the `rd_kafka_t`
	object it was created from.", but coud diffrent`rd_kafka_topic_t` object be created from same producer? @edenhill

**Comment by edenhill** [comment]
Yes, you can (and should) have multiple topic objects for each kafka_t instance.

One rd_kafka_t per Kafka cluster
One rd_kafka_topic_t per topic you  need to produce to.

So in your case you would have on rd_kafka_t and 90 rd_kafka_topic_t.

rd_kafka_topic_t objects may not be shared among multiple rd_kafka_t objects.
