### ISSUE TITLE
mktemp (non-GNU) and older no longer supported?

### ISSUE THREAD

**Issue by anilm23** [edenhill/librdkafka#759]
Description
===========
Using master branch.  Seems like a regression issue.
I get a failure during .configure with mktemp (using mktemp 1.7, not GNU mktemp).

This issue was previously reported in issue #176, that ticket has a patch and was closed.

FIX/Workaround:
Created a patch on my own that looks very similar to the code in that closed ticket.  Use the legacy (no suffix, more 6 Xs) mktemp behavior, then move the file to the extension;  no sense uploading my patch or committing it, since the code is there in 176.

How to reproduce
================
run ./configure on an older version of mktemp or on mktemp 1.7 (mktemp.org)

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): master
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:  Wind River Linux 6.0.0.27 
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You are saying current master does not work with non-GNU mktemp despite 6 X-es and no suffix?

That's weird.
