### ISSUE TITLE
Compiling librdkafka on Windows

### ISSUE THREAD

**Issue by CPS86** [edenhill/librdkafka#760]
# Description

Hello

I have a problem with compiling librdkafka on Windows. This is what I tried so far:
- Compiled on VS2013 - I had to do some minor changes in the code because I was receiving the errors during compilation. Basically, I moved the some variable declarations at the beginning of the methods and it worked.... However,  I was not able to run the executable - the example app crashed immediately. When I executed the app with the Administrative permissions enabled I got no error, however, I didn't receive any output at all - application just stopped without any errors or warnings. I thought that my changes caused this, so I tried to compile this in different compiler like DEVC++ or VISUAL STUDIO 2015. But, I received the same error after compiling - app crashes immediately with 0xc0000076 error.
  My next idea was that the problem was connected with the VS C++ libraries, but I have them.
  Any other ideas? 
# Checklist

Please provide the following information:
- [ ] librdkafka version (release number or git tag): 
  0.91
  - [ ] Operating system:
    Windows 7 x64

**Comment by edenhill** [comment]
librdkafka succesfully builds and runs with MSVC 2013 and 2015, see AppVeyor here:
https://ci.appveyor.com/project/edenhill/librdkafka
