### ISSUE TITLE
Fix space/tab consistency

### ISSUE THREAD

**Issue by dbeacham** [edenhill/librdkafka#762]
Not a critical issue by any means but I've browsing the source over the last few days and noticed there's inconsistency in the indenting style in some places - switching between tabs and 8 spaces - which makes everything look a bit weird when I've got tabs set to 4 spaces.

e.g. rd_kafka_conf.c -> rd_kafka_anyconf_dump

Happy to help clear some of this up - Is there a coding style that should be adhered to?

**Comment by edenhill** [comment]
Yeah, the split emacs / visual studio development messed it up.

It is on my TODO but since it will make `git blame` et.al useless I'm a bit reluctant to do it.

**Comment by benjaminbillet** [comment]
Hi,

Maybe I can do this for you: I'm currently reading the code of librdkafka and I will reformat it for my own understanding.

Which coding style would you like to enforce? And would you take a pull request for this?

**Comment by edenhill** [comment]
Thank you @benjaminbillet, I'm actually working on a proper style checker (and fixer) that will be part of the CI builds to make sure the code style is maintained.

**Comment by edenhill** [comment]
The current C code style is similar to the Linux kernel style guide, while the C++ code is following the Google C++ style guide.

**Comment by edenhill** [comment]
We now clang-format
