### ISSUE TITLE
Crash while trying to use rd_kafka_conf_set_log_cb

### ISSUE THREAD

**Issue by fishelson** [edenhill/librdkafka#763]
Description
===========
On trying to set rd_kafka_conf_set_log_cb(conf, logger) in custom program, observed 

%3|1471772712.470|FAIL|rdkafka#consumer-151| :0/internal: Failed to resolve ':0': Name or service not known
%3|1471772712.470|ERROR|rdkafka#consumer-151| :0/internal: Failed to resolve ':0': Name or service not known
%3|1471772712.470|ERROR|rdkafka#consumer-151| 1/1 brokers are down
Segmentation fault (core dumped)

How to reproduce
================
Working on a proprietary project, so cannot provide full details, but following is the crash analysis

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `XXXXX'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  rd_kafka_message_destroy (rkmessage=0x0) at rdkafka_queue.c:402
402		if (likely((rko = (rd_kafka_op_t *)rkmessage->_private) != NULL))
[Current thread is 1 (Thread 0x7f29639f4700 (LWP 124862))]

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
commit c577bcf3aa82f1cbe3b8cc28db5ce0b8887f6abd
Author: Magnus Edenhill <magnus@edenhill.se>
Date:   Thu Jul 14 16:45:08 2016 +0200

    Correct win32 README

 - [x] Apache Kafka version: 
kafka_2.11-0.10.0.0
 - [ ] librdkafka client configuration:
 - [x] Operating system:
Ubuntu
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
Using the one in rdkafka_example
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
See above
 - [ ] Provide broker log excerpts
 - [ ] Critical issue
I don't see the issue with deprecated rd_kafka_set_logger API, so workaround exists

**Comment by edenhill** [comment]
Do you  have a full backtrace from gdb?
Thanks

**Comment by gomuap** [comment]
1>  Generating Code...
1>     Creating library D:\Spark\librdkafka-master\librdkafka-master\win32\Debug\librdkafka.lib and object D:\Spark\librdkafka-master\librdkafka-master\win32\Debug\librdkafka.exp
1>rdkafka_transport.obj : error LNK2019: unresolved external symbol _OPENSSL_init_crypto referenced in function _rd_kafka_transport_ssl_init
1>rdkafka_transport.obj : error LNK2019: unresolved external symbol _SSL_CTX_set_options referenced in function _rd_kafka_transport_ssl_ctx_init
1>rdkafka_transport.obj : error LNK2019: unresolved external symbol _TLS_client_method referenced in function _rd_kafka_transport_ssl_ctx_init
1>rdkafka_transport.obj : error LNK2019: unresolved external symbol _OPENSSL_init_ssl referenced in function _rd_kafka_transport_ssl_init
1>D:\Spark\librdkafka-master\librdkafka-master\win32\Debug\librdkafka.dll : fatal error LNK1120: 4 unresolved externals
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========


Am getting this error while running on visual studio 2015.. How should run my client win32 with ubuntu

**Comment by edenhill** [comment]
You seem to be missing the Win OpenSSL32 library. Look at the README.win32 for more info
