### ISSUE TITLE
Producer termination order

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#765]
Hello Eden,

Hopefully an easy yes/no for you!

I am aware of the proper termination sequence you suggest but the RdKafka implementation of the termination of the producer can lead to this sequence:

1.rd_kafka_topic_destroy(rkt);
2.while (rd_kafka_outq_len(**rk**) > 0) rd_kafka_poll(**rk**, 50);
3.rd_kafka_destroy(**rk**);
 
Does the destroy of all the topics need to happen strictly after the poll loop?
So are the only correct orders: 2,1,3 or 2,3,1?

**Comment by edenhill** [comment]
The order of 1 and 2 dont matter much, librdkafka will hold on to topics until all references (external and internal) are lost.
But 3 must always be the last API called for an rk.

**Comment by MaximGurschi** [comment]
Cheers!
