### ISSUE TITLE
Produce Topic variable destroy time, use PHP rdkafka

### ISSUE THREAD

**Issue by shaunxq** [edenhill/librdkafka#766]
Hello,

a simple produce example cost me at least 150ms.
message is quickly send to broker, but the program is ended about 150ms after.
i tried to 

unset($rk);
unset($topic);

 the time cost in that
could you tell me the point in this case.
(sorry about my terrible english)

$rk = new RdKafka\Producer();
$rk->addBrokers("127.0.0.1:9092");
$topic = $rk->newTopic('test_topic');
$topic->produce(RD_KAFKA_PARTITION_UA, 0, 'test');

**Comment by fabienduval** [comment]
Hi shaunxq,

from php-rdkafka's readme, you can set set a lower value for "socket.blocking.max.ms".
The lower the value, the faster it will be to close the program (this is usefull for http requests).

Hope this help

**Comment by edenhill** [comment]
What @fabienduval said.

You can also allow librdkafka to terminate more quickly by setting `internal.termination.signal` to some unused signal such as 29 (SIGIO)
