### ISSUE TITLE
groud.id requite to be set allways

### ISSUE THREAD

**Issue by pachacutec** [edenhill/librdkafka#767]
Description
===========
I am developing a consumer but it seem I require to set the `group.id` always. But at the kafka doc seem to be optional please check [http://kafka.apache.org/documentation.html](http://kafka.apache.org/documentation.html)

Following the code at rdkafka.c line: 1121, is checking 
 `if (RD_KAFKAP_STR_LEN(rk->rk_conf.group_id) > 0)
                rk->rk_cgrp = rd_kafka_cgrp_new(rk,
                                                rk->rk_conf.group_id,
                                                rk->rk_conf.client_id);`

but at rdkafka_cgrp.c line 150:
 `if (RD_KAFKAP_STR_IS_NULL(group_id)) {
                /* No group configured: Operate in legacy/SimpleConsumer mode */
                rd_kafka_simple_consumer_add(rk);
                /* no need look up group coordinator (no queries) */
                rd_interval_disable(&rkcg->rkcg_coord_query_intvl);
        }`

Do you see an issue remove the checking at line 1121?

How to reproduce
================
Try to consume without:
"group.id" config set-  

Checklist
=========
Please provide the following information:

 - [master] librdkafka version (release number or git tag):
 - [0.10 ] Apache Kafka version: 
 - [X] librdkafka client configuration:
 - [LINUX ] Operating system:
 - [ ] Using the legacy Consumer
 - [X ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The group.id is required to start the internal consumer group machinery which takes care of high level balanced consumer groups (broker >=0.9) and broker offset commits.

If you dont need any of that you can use the legacy consumer API  (C++: Consumer class, C: consume_start() et.al)

**Comment by pachacutec** [comment]
Are any issue if we use the same group.id with assignation?

**Comment by pachacutec** [comment]
I think issue response my question
