### ISSUE TITLE
0.9 rdkafka tests on kafka 0.8.1 broker still failed

### ISSUE THREAD

**Issue by dean-chen** [edenhill/librdkafka#772]
Description
===========
According to the following issue response, set environment TEST_KAFKA_VERSION to
0.8.1.1 can avoid test failures.
https://github.com/edenhill/librdkafka/issues/636
But still get a few errors when running 'make'.

How to reproduce
================
Launch one kafka broker and run 'make' command will get following error.

### Test "0002_unkpart" failed at 0002-unkpart.c:107:main_0002_unkpart(): ###
Failed to acquire metadata: Local: Broker transport failure

Checklist
=========
Please provide the following information:

 - [ 0.9 in master branch] librdkafka version (release number or git tag):
 - [0.8.1 ] Apache Kafka version: 
 - [tests folder, default ] librdkafka client configuration:
 - [ArchLinux ] Operating system:
 - [ ] Using the legacy Consumer
 - [] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by dean-chen** [comment]
I think you might add some info for new people to teach them how to use your test. Following are my experience:
1. launch at least three kafka brokers, also specify different ports number and broker ids for them in server.properties, also add some configurations:

> auto.create.topics.enable=true
> default.replication.factor=3
> advertised.host.name=localhost//optional

2. set environment variable like this
`export TEST_KAFKA_VERSION=0.8.1.1`
3. copy test.conf.example file to test.conf, edit the file, add them

> metadata.broker.list=localhost:9093,localhost:9094,localhost:9095
> broker.version.fallback=0.8.1.1

After that, when re-run make command, many errors disappeared.
#==================================================================#
| <MAIN>                                   |     PASSED |  32.006s |
| 0001_multiobj                            |     PASSED |   1.732s |
| 0002_unkpart                             |     PASSED |   2.113s |
| 0003_msgmaxsize                          |     PASSED |   0.167s |
| 0004_conf                                |     PASSED |   0.110s |
| 0005_order                               |     PASSED |   0.183s |
| 0006_symbols                             |     PASSED |   0.000s |
| 0007_autotopic                           |     PASSED |   1.273s |
| 0008_reqacks                             |     PASSED |   0.463s |
| 0011_produce_batch                       |     PASSED |   1.385s |
| 0012_produce_consume                     |     PASSED |   3.670s |
| 0013_null_msgs                           |     PASSED |   1.938s |
| 0014_reconsume_191                       |     PASSED |   3.311s |
| 0015_offsets_seek                        |     PASSED |   4.707s |
| 0017_compression                         |     PASSED |   5.065s |
| 0018_cgrp_term                           |    SKIPPED |   0.000s |
| 0019_list_groups                         |    SKIPPED |   0.000s |
| 0020_destroy_hang                        |    SKIPPED |   0.000s |
| 0021_rkt_destroy                         |     PASSED |   0.285s |
| 0022_consume_batch                       |     PASSED |   4.129s |
| 0025_timers                              |     PASSED |   6.117s |
| 0026_consume_pause                       |    SKIPPED |   0.000s |
| 0028_long_topicnames                     |    SKIPPED |   0.000s |
| 0029_assign_offset                       |     FAILED |  25.004s |
| 0030_offset_commit                       |    SKIPPED |   0.000s |
| 0031_get_offsets                         |     PASSED |   1.729s |
| 0033_regex_subscribe                     |    SKIPPED |   0.000s |
| 0034_offset_reset                        |     PASSED |   3.248s |
| 0035_api_version                         |     PASSED |   0.077s |
| 0036_partial_fetch                       |     PASSED |   1.963s |
| 0037_destroy_hang_local                  |     PASSED |   1.116s |
| 0038_performance                         |    RUNNING |  21.004s |
| 0039_event                               |     PASSED |   0.483s |
| 0040_io_event                            |     FAILED |  20.003s |
| 0041_fetch_max_bytes                     |     PASSED |  12.315s |
#==================================================================#

Now, I have a few questions:
1. cannot see 0027 test case in above table
2. 0029 and 0040 failed
3. 0038 is running, why?
4. Actually I only know my kafka broker version is 0.8.1, but you need to specify 0.8.1.X, I have to use 1 for X, get 0.8.1.1. Is the last number important?

**Comment by tutucute5678** [comment]
I met the same problems with you in kafka version 0.8.2.1.
But i found test 0029 can be passed by simply modifying line 42 in "0029-assign_offset.c", changing "static const int partitions = 4" to "static const int partitions = 3". Because this test topic was created with 3 partitions (the default partition number in my cluster is set to 3, seems this "partitions" variable was not used in creating test topic), but the test script tried to access 4 partitions later, so it failed.

**Comment by edenhill** [comment]
tests/README outlines how to run the tests using trivup (which automatically creates a cluster)
