### ISSUE TITLE
Hung with GROUP.id set in Producer Handler at destroy

### ISSUE THREAD

**Issue by pachacutec** [edenhill/librdkafka#773]
Description
===========
if you have set the groud.id to rd_kafka_conf_t and use this configuration for create  rd_kafka_t producer type. When you try to rd_kafka_destroy that handler. The app hung, reporting

`#0  0x00007ffff651165b in pthread_join (threadid=threadid@entry=140737319380736, thread_return=thread_return@entry=0x7fffffffd7c8) at pthread_join.c:92
#1  0x00007ffff6bb9fe2 in thrd_join (thr=thr@entry=140737319380736, res=res@entry=0x0) at tinycthread.c:732
#2  0x00007ffff6b80588 in rd_kafka_destroy_app (blocking=1, rk=0x607970) at rdkafka.c:504
#3  rd_kafka_destroy (rk=0x607970) at rdkafka.c:512
#4  0x00007ffff70e883d in _databus_producer_tear_down (producer=0x607410) at /home/tinacho/development/databus-libdatabus/src/producer/databus_producer.c:78
#5  0x00007ffff70e886e in _databus_producer_free_mem (producer=0x607410) at /home/tinacho/development/databus-libdatabus/src/producer/databus_producer.c:90
#6  0x00007ffff70e8b58 in databus_producer_destroy (producer=0x607410) at /home/tinacho/development/databus-libdatabus/src/producer/databus_producer.c:202
#7  0x00007ffff7bd6468 in Databus::DatabusProducerImpl::~DatabusProducerImpl (this=0x608ee0, __in_chrg=<optimized out>) at /home/tinacho/development/databus-libdatabus/src-cpp/producer/databusProducer.cpp:59
#8  0x00007ffff7bd64c0 in Databus::DatabusProducerImpl::~DatabusProducerImpl (this=0x608ee0, __in_chrg=<optimized out>) at /home/tinacho/development/databus-libdatabus/src-cpp/producer/databusProducer.cpp:62
#9  0x0000000000403566 in std::default_delete<Databus::DatabusProducer>::operator()(Databus::DatabusProducer*) const ()
#10 0x0000000000402c1b in std::unique_ptr<Databus::DatabusProducer, std::default_delete<Databus::DatabusProducer> >::~unique_ptr() ()
`

How to reproduce
================
rd_kafka_conf_set(conf, "client_id_str", "dxdsad", NULL, 0);
rd_kafka_conf_set(conf, "brokers", brokers, NULL, 0);
set a group.id to conf using the rd_kafka_conf_set(conf, "group.id", "xxxxxx");
create producer with this conf
rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf, errstr, sizeof(errstr));
rd_kafka_produce(rkt, PARTITION, sendflags, message, cnt.msg_size, NULL, 0, NULL);
 rd_kafka_destroy(rk);

Checklist
=========
Please provide the following information:

 - [ 0.9.1] librdkafka version (release number or git tag):
 - [ 0.10] Apache Kafka version: 
 - [ X] librdkafka client configuration:
 - [ LINUX] Operating system:
 - [ ] Using the legacy Consumer
 - [ X] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Dup of #691, fixed on master
