### ISSUE TITLE
Delete bootstrap broker

### ISSUE THREAD

**Issue by lixiaoqing6052** [edenhill/librdkafka#774]
# Description

Kafka cluster : kafka broker A and kafka broker B。
I use rd_kafka_brokers_add() set broker A、B，and create consumer。consumer success。
when broker B leaves cluster，how delete broker B from librdkafka。
please help me，thank you~
# How to reproduce
# Checklist

Please provide the following information:
- [0.9 ] librdkafka version (release number or git tag):
- [2.11-0.10 ] Apache Kafka version: 
- [ ] librdkafka client configuration:
- [ ] Operating system:
- [ ] Using the legacy Consumer
- [ ] Using the high-level KafkaConsumer
- [ ] Provide logs (with `debug=..` as necessary) from librdkafka
- [ ] Provide broker log excerpts
- [ ] Critical issue

**Comment by edenhill** [comment]
That is not currently possible.
When support for cluster.id is added we could automatically purge brokers that changes cluster.id
https://cwiki.apache.org/confluence/display/KAFKA/KIP-78%3A+Cluster+Id
