### ISSUE TITLE
CONFIGURATION.md syntax error

### ISSUE THREAD

**Issue by eugpermar** [edenhill/librdkafka#782]
Description
===========
Global configuration properties table is bad formatted in the most important file of internet, CONFIGURATION.md

How to reproduce
================
See https://github.com/edenhill/librdkafka/blob/8ff3f890eb213d26157713475f1d74e493fa3b5a/CONFIGURATION.md, and go to the end of the table.

How to solve
==========
Remove last newline in that property:
```diff
diff --git i/src/rdkafka_conf.c w/src/rdkafka_conf.c
index 2e6501c..faa2fd6 100644
--- i/src/rdkafka_conf.c
+++ w/src/rdkafka_conf.c
@@ -605,7 +605,7 @@ static const struct rd_kafka_property rd_kafka_properties[] = {
        { _RK_GLOBAL|_RK_PRODUCER, "batch.num.messages", _RK_C_INT,
          _RK(batch_num_messages),
          "Maximum number of messages batched in one MessageSet. "
-         "The total MessageSet size is also limited by message.max.bytes.\n",
+         "The total MessageSet size is also limited by message.max.bytes.",
          1, 1000000, 10000 },
        { _RK_GLOBAL|_RK_PRODUCER, "delivery.report.only.error", _RK_C_BOOL,
          _RK(dr_err_only),
```

I can send a PR if you say that that newline has no special use.

Checklist
=========
Please provide the following information:

 - [X] librdkafka version (release number or git tag):
8ff3f890eb213d26157713475f1d74e493fa3b5a
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks ;)

**Comment by eugpermar** [comment]
As efficient as always :) Thanks to you!
