### ISSUE TITLE
Setting producer configs using Python client confluent-kafka-python

### ISSUE THREAD

**Issue by matthayes** [edenhill/librdkafka#784]
Description
===========
I tried providing `request.required.acks` and several other props to `confluent_kafka.Producer` and get an `_INVALID_ARG` error: No such configuration property: "request.required.acks"

I looked through the librdkafka code to try to understand why this is happening.  I noticed that `"request.required.acks"` uses `_RK_TOPIC|_RK_PRODUCER`, however I can't find any place where `_RK_PRODUCER` is set.  I'm not familiar with this code or confluent-kafka-python, so it isn't clear to me where the problem is (or if it's my own problem).

How to reproduce
================

```
from confluent_kafka import Producer
p = Producer({
    'bootstrap.servers': 'localhost:9092',
    'request.required.acks': -1
})
p.produce('test', "hey there".encode('utf-8'))
```

Checklist
=========
Please provide the following information:

 - [0.9.1] librdkafka version (release number or git tag):
 - [0.10.0.1-cp1] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [OSX 10.11.6] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Hey,

the _RK_TOPIC properties (https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md#topic-configuration-properties)  need to be set on a topic configuration object.
The python client does not currently expose per-topic configuration, but supports a "default.topic.config" sub-dict where you can set these properties.
Example:
https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/consumer.py#L37

So in your case you would do:
```
from confluent_kafka import Producer
p = Producer({
    'bootstrap.servers': 'localhost:9092',
    'default.topic.config': { 'request.required.acks': 'all' }
})
p.produce('test', "hey there".encode('utf-8'))
```

**Comment by matthayes** [comment]
Okay thanks for the explanation.  When I set `default.topic.config` as you suggest I don't see an error.
