### ISSUE TITLE
KafkaConsumer : how to poll without consuming ?

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#786]
Description
===========
Hi, I have a question on the usage of librdkafka (c++ wrapper) related to high level consumers.
Documentation says that poll should not be called on a high level consumer.
but how should I poll for callback without consuming msgs then ?

In my program I consume messages that I process asynchronously.
as I don't want to buffer too many messages if the processing part is slow I put limiter and stop consuming if the number of buffered messages is above a limit.

Then because I've stopped to consume how do I get callbacks like rebalancing  ones ?
should I then consume, not process the message and reposition the topic partition offset to decrement its position ?    

Thanks for the help.

Checklist
=========
Please provide the following information:

 - [ e36cd1e06bd5dcb8d86a17f3169b61d4c77b5ae7] librdkafka version (release number or git tag):
 - [0.10 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ubuntu 16.04 ] Operating system:
 - [ no ] Using the legacy Consumer
 - [ yes ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You can use the pause() API to stop consuming while maintaining active group membership state.
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L869
