### ISSUE TITLE
Starting Learning Kafka , but have few doubts

### ISSUE THREAD

**Issue by abhit011** [edenhill/librdkafka#787]
Description
===========
I am fairly new to Kafka, you can say few hours of just reading kafka related material on internet.
So please forgive me if I ask any foolish question in Kafka.

First I will give brief why I choose Kafka. You gurus can correct me more if I am going in wrong direction.

I have written a scalable TCP server (C/C++) , where I am maintaining concurrent connections close to hundred thousands clients. Now with humble threadpool of few threads I am serving so many clients, now if I use any direct DB insert call in those threads, it would have blocked the thread and there could be possibility that rest of the clients will get delayed for serving.  

I initially did some study on RabitMQ, thought of using it but major flaw was all API were SYNC API , that too can lead to blocking sometimes. that why dropped the idea of choosing RabitMQ, then I saw Kafka, and may be I was looking for something like that , where insert is just async.  

Then I decided something like from TCP threads , I will write the client msg into Kafka topics and at the other end there would be those message topic consumer which will keep on consuming the data from queues and injecting into DB.. 

something like 

   TCP Server threads 

~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ Producer 
 |   |   |   |   |   |   |  |   |   |   |   |  | 

--------------------------------
|	KAFKA with 3 Brokers      |
--------------------------------

|   |   |   |   |   |   |  |   |   |   |   |  |    Consumer Threads on diff process	
                  DB
I am thinking of creating close to 3 brokers and 10 topics like 00,01,02,03,04,05 till 09 why this because the client had id so i will just do something like client id % 10 , so what ever will the remainder . I will be dumping that client MSG into relevant topic.

So what I did like creating the 10 topics manually by calling 

C:\kafka_2.11-0.10.0.1\bin\windows>kafka-topics.bat --create --zookeeper localhost:2181 --replication-factor 2 --partitions 10 --topic 00

C:\kafka_2.11-0.10.0.1\bin\windows>kafka-topics.bat --create --zookeeper localhost:2181 --replication-factor 2 --partitions 10 --topic 01

C:\kafka_2.11-0.10.0.1\bin\windows>kafka-topics.bat --create --zookeeper localhost:2181 --replication-factor 2 --partitions 10 --topic 02

C:\kafka_2.11-0.10.0.1\bin\windows>kafka-topics.bat --create --zookeeper localhost:2181 --replication-factor 2 --partitions 10 --topic 03

C:\kafka_2.11-0.10.0.1\bin\windows>kafka-topics.bat --create --zookeeper localhost:2181 --replication-factor 2 --partitions 10 --topic 04

C:\kafka_2.11-0.10.0.1\bin\windows>kafka-topics.bat --create --zookeeper localhost:2181 --replication-factor 2 --partitions 10 --topic 05

etc....

Now Questions.
1. During initial boot up of my server, I will be init the KafkaRelated stuffs, now how many instances of 
RdKafka::Producer *m_kafkaProducer , I need to create  ?Depending upon no of my threads in threadpool ?

2. how many topic handler , i need to create , something like 10 , because there are 10 topics ?
e.g RdKafka::Topic	  *m_kafkaTopic[10] ? or something else.

3. how I am going to decide under which partation i need to dump ? if i give -1 it gives error , I just ran those on sample programs. 

Please do share your views

Abhi

**Comment by abhit011** [comment]
So after spent some time on learning kafka, thats how i designed 
kafka cluster with minimum 3 brokers, with partition 3, and replication factor 3.

From my application
I mean in my main thread, I have created kafka handle like  **RdKafka::Producer::create**
, all topic handles like **RdKafka::Topic::create** where I have array of toppic handles. 

I have created a thread pool in my application, where I have dedicated one thread for doing this
void run(){

		while (!CThread::currentThread().isInterrupted()) {
			m_Ptr->getKafkaProducerInstance()->poll(time );
		}
	};

**Question:** What time i should menton in poll ?

Now other threads of threadpool, it keeps on dumping the objects data to Kafka using 
m_kafkaProducer->produce() API, // remember that kafkaProducer  is just one, and all threads have the same handle ? **Question: It won't lead to any issues?** 
edenhill
Please do share your views.  @ edenhill ?

Abhi

**Comment by abhit011** [comment]
can you please reply edenhill

**Comment by edenhill** [comment]
The poll time is up to you: it specifies the maximum amount of time the poll() call will block waiting for new events. As soon as it has handled any new events (callbacks) it will return, even if it has not reached the timeout.

Your current design with producing from multiple threads and polling from one is good, it promotes high performance.

**Comment by edenhill** [comment]
And you typically only need to create one producer (or consumer) per Kafka cluster you are connecting to.

If you specify PARTITION_UA as partition when you produce it will use the configured (or default) partitioner to select a partition.

**Comment by abhit011** [comment]
edenill thanks for the response.... 
Another doubt ,
1. when dr_cb gets called at times, why I am getting offset like
log below
[2016-09-12 19:36:41.060]  AxKafkaCB    KAFKA Bytes : 96[Offset:0]
[2016-09-12 19:36:41.091]  AxKafkaCB    KAFKA Bytes : 96[Offset:0]
[2016-09-12 19:36:41.093]  AxKafkaCB    KAFKA Bytes : 96[Offset:0]
[2016-09-12 19:36:41.095]  AxKafkaCB    KAFKA Bytes : 96[Offset:64]
[2016-09-12 19:36:41.098]  AxKafkaCB    KAFKA Bytes : 96[Offset:0]
[2016-09-12 19:36:41.099]  AxKafkaCB    KAFKA Bytes : 96[Offset:0]
[2016-09-12 19:36:41.100]  AxKafkaCB    KAFKA Bytes : 96[Offset:0]
[2016-09-12 19:36:41.102]  AxKafkaCB    KAFKA Bytes : 96[Offset:0]
[2016-09-12 19:36:41.103]  AxKafkaCB    KAFKA Bytes : 96[Offset:0]
[2016-09-12 19:36:41.104]  AxKafkaCB    KAFKA Bytes : 96[Offset:104]
[2016-09-12 19:36:41.106]  AxKafkaCB    KAFKA Bytes : 96[Offset:0]
[2016-09-12 19:36:41.107]  AxKafkaCB    KAFKA Bytes : 96[Offset:36]

Why Offsets are coming like this. ?

2. Currently I have not written consumer part yet, but a small demo for consumer like if i mention 
PARTITION as -1 on a particular topic , it gives error unknown PARTITION? How to resolve that ?

3. Will consumer take care of picking up all the messages from all the partition of topics ? How to do that ? 

4. How to check how many messages are dumped to a particular topic ? (any command line will do)

 Abhi

**Comment by edenhill** [comment]
To get per-message delivery report offsets you need to set the topic config property: `produce.offset.report=true`

1. The legacy / simple consumer (Consumer class in C++, consume_start() in C) requires you to specify the exact partition to consume (0..N). If you use broker version 0.9 or later I suggest you use balanced consumer groups (KafkaConsumer, subscribe()).

2. see 1

3. register a stats_cb and look for the consumer_lag. Alternatively use get_watermark_offsets()
