### ISSUE TITLE
Detect if the message was delivered to kafka.

### ISSUE THREAD

**Issue by pachacutec** [edenhill/librdkafka#790]
Description
==========
At the new delivery callback we do not have the msg_opaque available, just the global opaque, the question how can i know that a message x was delivered? Since, i do not have a "id" to check . 

```
RD_EXPORT
int rd_kafka_produce(rd_kafka_topic_t *rkt, int32_t partition,
		      int msgflags,
		      void *payload, size_t len,
		      const void *key, size_t keylen,
		      void *msg_opaque);
```
```
**
 * @brief \b Producer: Set delivery report callback in provided \p conf object.
 *
 * The delivery report callback will be called once for each message
 * accepted by rd_kafka_produce() (et.al) with \p err set to indicate
 * the result of the produce request.
 * 
 * The callback is called when a message is succesfully produced or
 * if librdkafka encountered a permanent failure, or the retry counter for
 * temporary errors has been exhausted.
 *
 * An application must call rd_kafka_poll() at regular intervals to
 * serve queued delivery report callbacks.
 */
RD_EXPORT
void rd_kafka_conf_set_dr_msg_cb(rd_kafka_conf_t *conf,
                                  void (*dr_msg_cb) (rd_kafka_t *rk,
                                                     const rd_kafka_message_t *
                                                     rkmessage,
                                                     void *opaque));
```

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [X] librdkafka version (release number or git tag): 0.9.1
 - [X ] Apache Kafka version:  0.10
 - [ ] librdkafka client configuration:
 - [x ] Operating system: Linyx 
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ X] Critical issue

**Comment by edenhill** [comment]
The msg_opaque is avalable as `rkmessage->_private`

See here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L690

**Comment by pachacutec** [comment]
thanks, I din't see the params.
