### ISSUE TITLE
Measuring the latency time of producer/consumer individually?

### ISSUE THREAD

**Issue by seongyun-ko** [edenhill/librdkafka#791]
Description
===========

I am performing a benchmark of Kafka using the rdkafka_performance tool in rdkafka.
There is a latency mode that shows the latency time of each message from producer to consumer.

How can I measure the latency time of the individual producers/consumers?
; from the time of produce/consume function call to the time of the message acknowledged.

// btw, If the client also supports blocking produce/consume mode, I would be able to write the code for it easily. Do you also have a blocking-call APIs for producer/consumer (even as an internal API?)

Checklist
=========
(I didn't fill in the checklist because it's not about any bug..)

**Comment by edenhill** [comment]
You can look at the rtt (round-trip-time) in statistics (register a stats_cb, or pass -G .. to rdkafka_performance).

Sync producing is generally a bad idea since it has poor performance (bound by rtt), but here's a way to do it:
https://github.com/edenhill/librdkafka/wiki/Sync-producer

I'm not sure what a synchronous consumer is.

See some hints here:
https://github.com/edenhill/librdkafka/wiki/How-to-decrease-message-latency

**Comment by seongyun-ko** [comment]
the rtt-count in metrics is larger than the count of messages published.
What does it mean? When does the producer perform round-trip communication not for achtual message publishing?

**Comment by edenhill** [comment]
rtt is the round-trip-time in milliseconds.
Each protocol ProduceRequest (which takes one or more messages) is acked by the broker (if config property `acks!=0`). The rtt is the time it takes from sending the request to receiving the response.

**Comment by seongyun-ko** [comment]
That means the rtt measurement count must be equal to or smaller than the number of messages produced. 

i.e.

msg_cnt = 0, but rrt cnt is 4.
'ack' is 1 (default)

{ ... **"msg_cnt":0**, ... "rtt": { "min":42876, "max":71061, "avg":53414, "sum":213656, **"cnt":4** }, ...}

**Comment by edenhill** [comment]
Not really, there are other protocol message being sent as well (MetadataRequest, for example).
You can also enable `debug=protocol` to see per-request rtt

**Comment by seongyun-ko** [comment]
Thank you, I will try that option.

**Comment by seongyun-ko** [comment]
Can I make librdkafka not count the other protocol message (i.e. MetadataRequest) for measuring rtt?

**Comment by edenhill** [comment]
Not out of the box, but you can easily modify the code in rd_kafka_waitresp_find in rdkafka_broker.c
