### ISSUE TITLE
Triggering an assert after blocking /unblocking connection to broker

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#792]
Description
===========
hi have the following assert that fails : `rd_kafka_assert(NULL, rkbuf->rkbuf_of == 0);`

here is my stack : 
http://pix.toile-libre.org/upload/original/1473700025.jpg
Is my usage of the lib wrong or would that be a bug ?

Thank you.

Checklist
=========
Please provide the following information:

 - [ e36cd1e06bd5dcb8d86a17f3169b61d4c77b5ae7] librdkafka version (release number or git tag):
 - [0.10 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ubuntu 16.04 ] Operating system:
 - [ no ] Using the legacy Consumer
 - [ yes ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Very interesting, do you have any idea what happened prior to the crash?
Do you have any logs?

**Comment by edenhill** [comment]
Probably dup of #756
