### ISSUE TITLE
Balanced high-level consumer support  batched messages?

### ISSUE THREAD

**Issue by greatt1n** [edenhill/librdkafka#793]
Hi,for the simple consumer ,consume batched messages can work,but i would like to consume batched messages using consumer group,do support?

**Comment by edenhill** [comment]
You should be able to use `rd_kafka_consume_batch_queue()` and use the queue returned by `rd_kafka_queue_get_consumer()`.
I havent tried this myself but it should work.

**Comment by abhit011** [comment]
@edenhill  does it exist in  KafkaConsumer class  too ?

**Comment by edenhill** [comment]
That API is not currently implemented in C++.
What is your use case for consuming batches of messages?

**Comment by edenhill** [comment]
Okay, this is currently not supported but you should be able to replicate the behaviour in your application by consuming the number of messages you want into a temporary list or queue and then process that as a batch.
From librdkafka's perspective there is no difference between that and a batched interface, i.e., there is no semantic meaning of batches on the consumer.

**Comment by greatt1n** [comment]
I did this follow your suggestion and it works,thans for your help.
