### ISSUE TITLE
Regarding KafkaConsumer

### ISSUE THREAD

**Issue by abhit011** [edenhill/librdkafka#794]
Description
===========

@edenhill 

I have queries with respect to KafkaConsumer since I am producing from multiple threads into 
(3 Kafka Brokers with 10 topics ,  3 partitions and replication factor of 3) 

1. Now I am coding the Consumer part, a little confused, in my main thread i am creating the KafkaConsumerHandler, registering callbacks, and subscribing to all the 10 topics.  Should I create 
N Consume threads to consume messages ? or Just one thread to consume message from those 10 topics ? 
e.g 
thread code for consuming 
while (!CThread::currentThread().isInterrupted()){
			RdKafka::Message *msg = m_Ptr->getKafkaConsumerInstance()->consume(1000);
			kafkaMsgConsume(msg, NULL);
			passItToDatabase(msg); // I am doing the deallocation of msg in this passItToDB  //after    succcesful dump into DB
                       }   

2. Trust me I could not able to understand what rebalancing callback does and why its required too ?

3. Whats the maximum size of kafka logs directory for each broker?

4. Is it possible that messages from producer and after successful reading each message from Kafka Consumer, those messages should be deleted from the logs ?

Abhi

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ X] Apache Kafka version:kafka_2.11-0.10.0.1 
 - [ ] librdkafka client configuration:
 - [X ] Operating system: Windows 10
 - [ ] Using the legacy Consumer
 - [X] Using the high-level KafkaConsumer: yes intended to use that only
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Answers:
 
 1. You should typically only call consume() from one thread, but it is okay to call from multiple threads (which might be good if your processing time per message is long).
 2. The rebalance_cb allows an application to find out what partitions were assigned to it (or revoked) when a consumer group rebalances (assigns partitions to group members). It is optional but do read the rules of its use (such as needing to call assign()).
 3. consult Kafka broker documentation.
 4. Kafka is state-less, it does not have functionality for deleting messages based on if they've been consumed or not. But do read up on log compaction and see if it is for you.

**Comment by abhit011** [comment]
@edenhill 

Please correct me if I am wrong . 

**As per kafka documentation**
The Kafka cluster retains all published messages—whether or not they have been consumed—for a configurable period of time. For example if the log retention is set to two days, then for the two days after a message is published it is available for consumption, after which it will be discarded to free up space. **Kafka's performance is effectively constant with respect to data size so retaining lots of data is not a problem.**
In fact the only metadata retained on a per-consumer basis is the position of the consumer in  the log, called the "offset". This offset is controlled by the consumer: normally a consumer will advance its offset linearly as it reads messages, but in fact the position is controlled by the consumer and it can consume messages in any order it likes. For example a consumer can reset to an older offset to reprocess.

e.g something like this t_KafkaConf->set("auto.offset.reset", "smallest", errstr); will always start from the beginning ? 

Now there is confusion like 

Last offset read by Consumer for topic **00** was 52, topic **01** was 70, topic **02** was 10. and now I shut down the Consumer and lets say producer is keep on dumping the data into Kafka logs and current offset of topic **00** is 68, topic **01** is 100, topic **02** is 59 etc.. 

Now when i restart the consumer, from where the consumer will start consuming the data, e.g from where it let its last/ topic offset or like start from 0 ? 

Abhi

**Comment by edenhill** [comment]
If previously committed offsets are available (which they will be if you leave the enable.auto.commit=true to its true default) then they will start off at their last position. In your case offsets 52+2, 70+1 and 10+1

**Comment by abhit011** [comment]
Why + 2 for 52 ??? or its a typo ?

**Comment by edenhill** [comment]
typo

**Comment by abhit011** [comment]
:+1:  Though  I did not touch the enable.auto.commit property at all . 
So i assume that Kafka takes care of auto saving the offset by itself, once the msgconsume() gets called with case case RdKafka::ERR_NO_ERROR: ?

**Comment by edenhill** [comment]
yes, more info here:
http://docs.confluent.io/3.0.1/clients/consumer.html#concepts

**Comment by abhit011** [comment]
Thanks for the URI.. Also why my event_cb :( not getting called :(

**Comment by abhit011** [comment]
I am wondering since I started knowing more and more about Kafka, all messages produced are saved into FILE logs, and there are heavy File operations, then why there is no latency in that ?

**Comment by abhit011** [comment]
Another thing per cluster how many consumer groups should be there ? 
So I i create one instance of kafka consumer, then in that case i can just bind one consumer group it that kaka consumer right ?

**Comment by abhit011** [comment]
![new_consumer_figure_1](https://cloud.githubusercontent.com/assets/10906885/18585657/d7b123e6-7c35-11e6-8936-c64d37bce268.png)

Regarding the cosumer1, consumer2.. and on.. Are these individual consumer threads which are calling 
something like this ?
while (!CThread::currentThread().isInterrupted()){
RdKafka::Message *msg = m_Ptr->getKafkaConsumerInstance()->consume(1000);
kafkaMsgConsume(msg, NULL);
passItToDatabase(msg); 
}

**Comment by edenhill** [comment]
You typically only run one consumer instance for a group per application+host.
It doesnt really make sense to have multiple consumer instances for the same group in the same application.

**Comment by abhit011** [comment]
@edenhill 

What benefits storm/spark will add , in a way they are nothing but just doing the job of a kafka consumer only ? Or I am missing something else. 
Also aren't there any library for kafka connect in C++, where i can connect to Database ?

Abhi

**Comment by abhit011** [comment]
@edenhill  
?

**Comment by edenhill** [comment]
Kafka Connect is currently only available for Java, I dont think it is likely that we'll  see a C++ library for it.
