### ISSUE TITLE
Consumer Group

### ISSUE THREAD

**Issue by abhisharma** [edenhill/librdkafka#795]
Description
===========
I'm having following issues with using high-level consumer API (C based):

1. After successful call to rd_kafka_subscribe() with partition supplied equal to -1, I expect an available partition to be assigned when I call rd_kafka_subscription() subsequently to lookup subscription, but I still get -1.
2. I call describe_groups() from example source code(https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_consumer_example.c) to get information about consumer groups, but I get nothing although I had set group.id and client.id on the kafka configuration.
3. rd_kafka_consumer_poll() does not retrieve any message although I'm listening to same topic and partition to which producer is publishing. I tried rd_kafka_assign() as well but no group information is retrieved and no messages get pulled. I made sure that while instantiating client configuration, that I'm using RD_KAFKA_CONSUMER mode.

If I use legacy API, I can successfully retrieve messages but my understanding is that consumer group support is not present with legacy API. Any help will be greatly appreciated.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): librdkafka-0.9.1
 - [ ] Apache Kafka version: kafka_2.10-0.10.0.0
 - [ ] librdkafka client configuration:
 - [ ] Operating system: Solaris
 - [ ] Using the legacy Consumer yes
 - [ ] Using the high-level KafkaConsumer yes
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue yes

**Comment by edenhill** [comment]
1. subscribe() sets the topic(s) to subscribe, the partition is not used. subscription() returns the subscribed topics, the partitions are not used. After rebalancing finishes you can see what partitions were assigned with the assignment() API.
2. describe_groups() only returns relevant information for active groups that have offsets committed
3. use `debug=cgrp` config property to see what partitions were assigned to you after rebalance. If the topic is not actively produced to it might be that the consumer starts at the end (default) and thus wont see any new messages. See `auto.offset.reset` topic conf property.

**Comment by abhisharma** [comment]
Thanks for the explanation. Rebalancing callback never gets triggered. Is there anything I need to do make sure it gets trigerred. I had my auto.offset.reset set to smallest and there are messages in topic partitions.

**Comment by abhisharma** [comment]
I notice rebalance should happen on any consumer joining or leaving the group but apparently that is not happening for me.

**Comment by abhisharma** [comment]
cgrp:
  mytopic in state up, flags 0x10
   coord_id 1, managing broker machineName:9092/1
  toppars:
 topics:
  mytopic with 2 partitions, state exists, refcnt 4
   mytopic [-1] leader none
    refcnt 1
    msgq:      0 messages
    xmit_msgq: 0 messages
    total:     0 messages, 0 bytes
   desired partitions:

**Comment by abhisharma** [comment]
It was session.timeout issue.
