### ISSUE TITLE
struct not defined?

### ISSUE THREAD

**Issue by lidaili** [edenhill/librdkafka#798]
Description
===========

in src/rdkafka.h  line 182: typedef struct rd_kafka_topic_s rd_kafka_topic_t;

could not find the definition of  rd_kafka_topic_s, should it be  rd_kafka_itopic_s ??

How to reproduce
================

source code problem? 

Checklist
=========
Please provide the following information:

 - [ master ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The librdkafka API is implemented using private structs that are not visible to the application, this is to ensure ABI safety across versions.

**Comment by jeffin-ntx** [comment]
@edenhill ,Thanks -  the private structs are exposed so that we don't temper with the members and the changes doesn't requires the client to recompile, But I would still like to know the struct definition of `struct rd_kafka_topic_s` or what is exactly the type

**Comment by edenhill** [comment]
It maps to the underlying topic implementation, see here
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_topic.h#L38

**Comment by jeffin-ntx** [comment]
Thanks @edenhill for taking the time out and pointing out the lines :)

Also Thanks for all the hard work done with `librdkafka` ❤️

**Comment by edenhill** [comment]
Thank you :+1:
