### ISSUE TITLE
legacy consumer coredump on 0.8.6

### ISSUE THREAD

**Issue by longtong** [edenhill/librdkafka#801]
# Description

`Cannot access memory at address 0x7fc7f2532810
(gdb) bt
#0  0x00000000004f1d27 in rd_kafka_waitresp_find (rkb=0x6cfaf001) at thirdparty/librdkafka-0.8.6/src/rdkafka_broker.c:1274
#1  rd_kafka_req_response (rkb=0x6cfaf001) at thirdparty/librdkafka-0.8.6/src/rdkafka_broker.c:1301
#2  rd_kafka_recv (rkb=0x6cfaf001) at thirdparty/librdkafka-0.8.6/src/rdkafka_broker.c:1513
#3  0x00000000004f4b6c in rd_kafka_broker_fetch_toppars (arg=0x7fc7d5bd09e8) at thirdparty/librdkafka-0.8.6/src/rdkafka_broker.c:4011
#4  rd_kafka_broker_consumer_serve (arg=0x7fc7d5bd09e8) at thirdparty/librdkafka-0.8.6/src/rdkafka_broker.c:4089
#5  rd_kafka_broker_thread_main (arg=0x7fc7d5bd09e8) at thirdparty/librdkafka-0.8.6/src/rdkafka_broker.c:4154
#6  0x00000000004f5e37 in rd_kafka_q_enq (rkb=0x1, err=32711, reply=0x5448420, request=0x8d2d1b5, opaque=0x0) at thirdparty/librdkafka-0.8.6/src/rdkafka_int.h:846
#7  rd_kafka_q_enq (rkb=0x1, err=32711, reply=0x5448420, request=0x8d2d1b5, opaque=0x0) at thirdparty/librdkafka-0.8.6/src/rdkafka_int.h:851
#8  rd_kafka_broker_metadata_reply (rkb=0x1, err=32711, reply=0x5448420, request=0x8d2d1b5, opaque=0x0) at thirdparty/librdkafka-0.8.6/src/rdkafka_broker.c:1045
#9  0x00000000004f67e0 in rd_kafka_metadata_handle (rkb=0x257fb80, err=0, reply=0x4f4910, request=0x7fff2a936952, opaque=0x4efef2) at thirdparty/librdkafka-0.8.6/src/rdkafka_broker.c:865
#10 rd_kafka_broker_metadata_reply (rkb=0x257fb80, err=0, reply=0x4f4910, request=0x7fff2a936952, opaque=0x4efef2) at thirdparty/librdkafka-0.8.6/src/rdkafka_broker.c:1027
#11 0x00000000004f82ee in sink_peek (env=0x0, iov_in=0x257fb80, iov_in_len=2189, input_length=<value optimized out>, iov_out=0x7fc7d5bd1440, iov_out_len=0x7fc7d5bd145c,

```
compressed_length=0x7fc7d5bd2700) at thirdparty/librdkafka-0.8.6/src/snappy.c:297
```
#12 compress (env=0x0, iov_in=0x257fb80, iov_in_len=2189, input_length=<value optimized out>, iov_out=0x7fc7d5bd1440, iov_out_len=0x7fc7d5bd145c, compressed_length=0x7fc7d5bd2700)

```
at thirdparty/librdkafka-0.8.6/src/snappy.c:1356
```
#13 snappy_compress_iov (env=0x0, iov_in=0x257fb80, iov_in_len=2189, input_length=<value optimized out>, iov_out=0x7fc7d5bd1440, iov_out_len=0x7fc7d5bd145c, compressed_length=0x7fc7d5bd2700)

```
at thirdparty/librdkafka-0.8.6/src/snappy.c:1398
```
#14 0x00007fc7f27829d1 in ?? ()
#15 0x00007fc7d5bd2700 in ?? ()
#16 0x0000000000000000 in ?? ()

(gdb) quit
`
# How to reproduce

I create a kakfa-topic with 15 paritions, and start 15 consumer threads for consuming each parition, but sometimes the app cores, how could i fix this ? help~

rdkakfa version:  0.8.6
# Checklist

Please provide the following information:
- [ ] librdkafka version (release number or git tag):
- [ ] Apache Kafka version: 
- [ ] librdkafka client configuration:
- [ ] Operating system:
- [ ] Using the legacy Consumer
- [ ] Using the high-level KafkaConsumer
- [ ] Provide logs (with `debug=..` as necessary) from librdkafka
- [ ] Provide broker log excerpts
- [ ] Critical issue

**Comment by edenhill** [comment]
Can you try the same on librdkafka version 0.9.1?
