### ISSUE TITLE
rd_kafka_consumer_example does not consume from Kafka when topic is created later

### ISSUE THREAD

**Issue by fishelson** [edenhill/librdkafka#802]
Description
===========

If a topic is created after consumption has already started 
./rdkafka_consumer_example topic_new, does not consume any messages. Interestingly, if we use ./rdkafka_consumer_example topic_new:0, the consumption works

How to reproduce
================

Start ./rdkafka_consumer_example random_topic
Create topic in another tab
Send messages to random_topic
No message is received
Start ./rdkafka_consumer_example random_topic_2:0
Create topic in another tab
Send messages to random_topic_2
Messages appear

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.1
 - [ ] Apache Kafka version: 2.10-0.9.0
 - [ ] librdkafka client configuration: NA
 - [ ] Operating system: Linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by fishelson** [comment]
Is this expected behavior ?

**Comment by fishelson** [comment]
I notice that when just topic is mentioned rd_kafka_subscribe is used but rd_kafka_assign is used when topic and partition both are used

**Comment by edenhill** [comment]
Yes, a fix is on the way for this.

**Comment by edenhill** [comment]
This issue is now fixed on master, please try to verify the fix in your environment.
Thank you.
