### ISSUE TITLE
consumer crash

### ISSUE THREAD

**Issue by sashabel** [edenhill/librdkafka#803]
Hello ,
following the issue #800 , I took current master and noticed the following :

Description
===========
I perform a unit test thst:
1.creates produces
2. creates consumer
3. consumes all messages (if any)
4. produces 500 messeages
5. test that I consume 500 messages

First run of the application is OK. The second exits on assert in rd_kafka_topic_partition_list_copy() saying 
src = NULL.

The interesting thing is that if the group.id is set to different values between the executions everything is OK.
when I run with debug=cgrp I receive (before the crash):
LOG-7-CGRPOP: Group "my_grp" received op OFFSET_COMMIT (v0) in state up (join state wait-join, v1)
LOG-7-COMMIT: OffsetCommit internal error: Local: No offset stored

How to reproduce
================
Re-run the described scenario with the same group.id

Checklist
=========
Please provide the following information:

 - [@] librdkafka version (release number or git tag): 67b0f8c1a53c891f3b5b64877b21711563e0505a
 - [@] Apache Kafka version: kafak_2.11-0.9.0.0
 - [ ] librdkafka client configuration:
 - [@] Operating system: win7/ubuntu
 - [ ] Using the legacy Consumer
 - [@] Using the high-level KafkaConsumer : YES
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you provide the full backtrace? (e.g. `bt full` from gdb)

**Comment by sashabel** [comment]
Prefer get logs on windows, the linux machine I only got Segmentation fault (I'm still new to linux)

**Comment by edenhill** [comment]
A full stacktrace of the asserthing threads from Windows works equally great, thanks

**Comment by sashabel** [comment]
librdkafka.dll!rd_kafka_topic_partition_list_copy() - rdkafka_partition.c -Line 2253
librdkafka.dll!rd_kafka_cgrp_op_handle_OffsetCommit()-rdkafka_cgrp.c- Line 1005

**Comment by edenhill** [comment]
Is this this your own consumer application or one of the examples?
Are you using auto offset commits or manual ones?
If manual commits; how are you calling the commit APIs?

**Comment by sashabel** [comment]
This is my own conusmer app. based on  RdKafka::KafkaConsumer. I am using the defaults (auto.offset.commit = true, auto.commit.enable=true)
After each consume I call commitSync()

**Comment by edenhill** [comment]
You shouldnt typically use auto commit and manual  commit, select one or the other.

**Comment by sashabel** [comment]
I use the defaults as specified in configuration.md

* For topic:
**auto.commit.enable**                       |  C  | true, false     |          true | If true, periodically commit offset of the last message handed to the application. This committed offset will be used when the process restarts to pick up where it left off. If false, the application will have to call `rd_kafka_offset_store()` to store an offset (optional). **NOTE:** This property should only be used with the simple legacy consumer, when using the high-level KafkaConsumer the global `auto.commit.enable` property must be used instead. **NOTE:** There is currently no zookeeper integration, offsets will be written to broker or local file according to offset.store.method. <br>*Type: boolean*

* For Consumer
**enable.auto.commit**                       |  C  | true, false     |          true | Automatically and periodically commit offsets in the background. <br>*Type: boolean*

**Comment by sashabel** [comment]
By the way the same code with your latest released version doesn't crash (however, it doesn't exit properly, there is some kind of deadlock in the destructor of the consumer , that's why I've tried current master stream as you've recommended in issue #800 )

**Comment by edenhill** [comment]
If you do manual commits through the commit*() APIs you should set auto.commit.enable=false.

So it doesnt crash  on latest master, but it hangs? Is that correct?

**Comment by sashabel** [comment]
Yes this is correct.
Is there any risk to call commit manually in addition to periodic commits that are performed by auto.commit.enable=true ?

**Comment by edenhill** [comment]
There should not be a problem doing that, it is just unecessary if you already commit every message.

**Comment by edenhill** [comment]
There's a fix for this that will be pushed to master soon.

**Comment by edenhill** [comment]
This issue is now fixed on master, please try to verify the fix in your environment.
Thank you.
