### ISSUE TITLE
Temporary failure in name resolution and Cannot assign requested address in rdkafka client

### ISSUE THREAD

**Issue by sa35t** [edenhill/librdkafka#804]
<?php

$rk = new RdKafka\Producer();
$rk->setLogLevel(LOG_DEBUG);
$rk->addBrokers("172.31.18.232,172.31.18.233,172.31.18.234");
$topic = $rk->newTopic("test");
$error = $topic->produce(RD_KAFKA_PARTITION_UA, 0, "Message payload");

I am using above code for connecting to kafka server, while it works fine for initial period but after some time it gives me following errors

`%3|1474886718.162|ERROR|rdkafka#producer-537| ip-172-31-18-233.ap-southeast-1.compute.internal:9092/3: Failed to resolve 'ip-172-31-18-233.ap-southeast-1.compute.internal:9092': Temporary failure in name resolution
%3|1474886745.535|FAIL|rdkafka#producer-537| ip-172-31-18-233.ap-southeast-1.compute.internal:9092/3: Failed to connect to broker at <unsupported:inet>: Cannot assign requested address
%3|1474886745.535|ERROR|rdkafka#producer-537| ip-172-31-18-233.ap-southeast-1.compute.internal:9092/3: Failed to connect to broker at <unsupported:inet>: Cannot assign requested address
%3|1474886751.773|FAIL|rdkafka#producer-538| ip-172-31-18-234.ap-southeast-1.compute.internal:9092/5: Failed to connect to broker at ip-172-31-18-234.ap-southeast-1.compute.internal:9092: Cannot assign requested address
%3|1474886751.773|ERROR|rdkafka#producer-538| ip-172-31-18-234.ap-southeast-1.compute.internal:9092/5: Failed to connect to broker at ip-172-31-18-234.ap-southeast-1.compute.internal:9092: Cannot assign requested address
%3|1474886762.789|FAIL|rdkafka#producer-538| ip-172-31-18-234.ap-southeast-1.compute.internal:9092/5: Failed to resolve 'ip-172-31-18-234.ap-southeast-1.compute.internal:9092': Temporary failure in name resolution
%3|1474886762.789|ERROR|rdkafka#producer-538| ip-172-31-18-234.ap-southeast-1.compute.internal:9092/5: Failed to resolve 'ip-172-31-18-234.ap-southeast-1.compute.internal:9092': Temporary failure in name resolution
%3|1474886796.488|FAIL|rdkafka#producer-538| ip-172-31-18-234.ap-southeast-1.compute.internal:9092/5: Failed to connect to broker at ip-172-31-18-234.ap-southeast-1.compute.internal:9092: Cannot assign requested address
%3|1474886796.488|ERROR|rdkafka#producer-538| ip-172-31-18-234.ap-southeast-1.compute.internal:9092/5: Failed to connect to broker at ip-172-31-18-234.ap-southeast-1.compute.internal:9092: Cannot assign requested address
%3|1474886826.071|FAIL|rdkafka#producer-541| 172.31.18.234:9092/bootstrap: Failed to connect to broker at ip-172-31-18-234.ap-southeast-1.compute.internal:9092: Cannot assign requested address
%3|1474886826.071|ERROR|rdkafka#producer-541| 172.31.18.234:9092/bootstrap: Failed to connect to broker at ip-172-31-18-234.ap-southeast-1.compute.internal:9092: Cannot assign requested address
%3|1474886931.777|FAIL|rdkafka#producer-552| 172.31.18.233:9092/bootstrap: Failed to connect to broker at ip-172-31-18-233.ap-southeast-1.compute.internal:9092: Cannot assign requested address
%3|1474886931.777|ERROR|rdkafka#producer-552| 172.31.18.233:9092/bootstrap: Failed to connect to broker at ip-172-31-18-233.ap-southeast-1.compute.internal:9092: Cannot assign requested address
%3|1474886932.778|FAIL|rdkafka#producer-552| 172.31.18.232:9092/bootstrap: Failed to connect to broker at ip-172-31-18-232.ap-southeast-1.compute.internal:9lution
%3|1474886774.525|ERROR|rdkafka#producer-33| ip-172-31-18-234.ap-southeast-1.compute.internal:9092/5: Failed to resolve 'ip-172-31-18-234.ap-southeast-1.compute.internal:9092': Temporary failure in name resolution
%3|1474886774.525|FAIL|rdkafka#producer-33| ip-172-31-18-232.ap-southeast-1.compute.internal:9092/1: Failed to resolve 'ip-172-31-18-232.ap-southeast-1.compute.internal:9092': Temporary failure in name resolution
%3|1474886774.525|ERROR|rdkafka#producer-33| ip-172-31-18-232.ap-southeast-1.compute.internal:9092/1: Failed to resolve 'ip-172-31-18-232.ap-southeast-1.compute.internal:9092': Temporary failure in name resolution
%3|1474886781.017|FAIL|rdkafka#producer-33| ip-172-31-18-232.ap-southeast-1.compute.internal:9092/1: Failed to connect to broker at ip-172-31-18-232.ap-southeast-1.compute.internal:9092: Cannot assign requested address
%3|1474886781.017|ERROR|rdkafka#producer-33| ip-172-31-18-232.ap-southeast-1.compute.internal:9092/1: Failed to connect to broker at ip-172-31-18-232.ap-southeast-1.compute.internal:9092: Cannot assign requested address
%3|1474886791.041|FAIL|rdkafka#producer-33| ip-172-31-18-234.ap-southeast-1.compute.internal:9092/5: Failed to connect to broker at <unsupported:inet>: Cannot assign requested address`

can some one help me resolve this issue.

Iam using php 5.3.3

Thanks.

**Comment by edenhill** [comment]
Can you resolve ip-172-31-18-234.ap-southeast-1.compute.internal from a shell?
E.g.: `ping ip-172-31-18-234.ap-southeast-1.compute.internal`
