### ISSUE TITLE
[throttling] Protocol parse failure when consuming from a topic

### ISSUE THREAD

**Issue by mfontanini** [edenhill/librdkafka#805]
Description
===========
I just created a consumer and while trying to consume from some topic where there are a lot of messages queued, I get this error constantly and can't seem to consume a single one of them:

```$ ./test
%4|1474940031.346|PROTOERR|rdkafka#consumer-1| kafka2.local/l:6667/2: Protocol parse failure at rd_kafka_fetch_reply_handle:3829 (incorrect broker.version.fallback?)
%4|1474940031.346|PROTOERR|rdkafka#consumer-1| kafka2.local:6667/2: expected 39944975 bytes > 44 remaining bytes```

I read some other issues where this was happening and I can confirm that:

* We're using kafka brokers version 0.9.0.1.
* I tried playing around with `broker.version.fallback` but the behavior is the same.
* This does not happen on other topics where there's less messages.
* I tried assigning a single partition rather than subscribing and still get the same error.
* I tried playing around with message sizes. I changed `message.max.bytes` and `fetch.message.max.bytes` always to the same value, increasing them to up to 80MB. Also increasing `receive.message.max.bytes`. I moved it to up to 500MB while consuming from a single partition and this still happens.
* This happens on both the latest `rdkafka` release and the latest master commit both on GNU/Linux and OSX.

Now, something somehow interesting is that another process which was running on a different server, consuming from a different topic and had been running steadily for weeks started getting the same issue right after I started this consumer for the first time. So this somehow escaped this consumer and affected other ones on unrelated topics.

How to reproduce
================
The consumer is really simple. I even wrote a separate dummy consumer that just processes the messages from the beginning of the topic and this still happens 100% of the times. Note that we have some other consumers written in Java consuming from these same topics and they're having no issues.

If you need any extra information, please let me know. I can't seem to find anything relevant in the broker's logs. I'll keep looking into this tomorrow to see if I can narrow it down a bit.

Checklist
=========
Please provide the following information:

 - [X] librdkafka version (release number or git tag): latest release and latest master have the same issue.
 - [X] Apache Kafka version: 0.9.0.1
 - [X] librdkafka client configuration: Nothing special just `auto.offset.reset: smallest`, plus `group.id`.
 - [X] Operating system: GNU/Linux and OSX
 - [X] Using the high-level KafkaConsumer
 - [X] Provide logs (with `debug=..` as necessary) from librdkafka: https://gist.github.com/mfontanini/eba767c09bbb9dba816d8548bfbb25e5

**Comment by edenhill** [comment]
What are the message sizes on those topics and partitions?

**Comment by mfontanini** [comment]
The `message.max.bytes` is the default, which seems to be 1Mb, so the messages should definitely fit, especially after I increased the client max bytes size to 40MB.

**Comment by mfontanini** [comment]
So apparently if I only increase `receive.message.max.bytes` to something like (1024 * 1024 * 100), I don't see the issue anymore on this consumer. Still, this triggers the issue on the other, unrelated consumer that is polling messages from a different topic, which is still bugging me.

I do see a bunch of messages like:

```kafka2.local:6667/2: 3 request(s) timed out: disconnect````

On both my consumer and the unrelated one once I start this one. Note that I checked the value of `TopicArrayCnt` after it's read on `rd_kafka_fetch_reply_handle` and when this issue is triggered, I see the value `1597799`, which doesn't seem to be fine (note that there's 20 partitions here).

**Comment by mfontanini** [comment]
Okay, I found something. So, I printed the `Throttle_Time` after reading it [here](https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L3818) and it's always `1` when the bug happens. I commented that `if` statement out and now it works fine. So it somehow seems like the condition for which the throttle time is read is wrong and it's reading the `TopicArrayCnt` instead.

**Comment by mfontanini** [comment]
Erased my previous comment as it didn't make much sense. So basically I'm seeing that every time the throttle time on the fetch reply is 0, I actually get to consume some messages from the consumer. Whenever it's 1, the topic count is broken and contains the value `1597799` every single time. 

Right now, I'm getting basically:

```
(fetch reply having throttle time 0) -> consume 4k+ messages
(fetch reply having throttle time 1) -> topic array count 1597799
(fetch reply having throttle time 1) -> topic array count 1597799
(fetch reply having throttle time 1) -> topic array count 1597799
(fetch reply having throttle time 0) -> consume 1 message
```

**Comment by mfontanini** [comment]
One more update. I'm currently printing the read buffer on `rd_kafka_fetch_reply_handle` (this is, print `rkbuf->rkbuf_rbuf[rkbuf->rkbuf_of+i]` for i in `(0, rd_kafka_buf_remain(rkbuf)`) and whenever this error happens, I get buffers that look like this:

```python
['\x00', '\x00', '\x00', '\x01', '\x00', '\x18', 'S', 'O', 'M', 'E', '_', 'T', 'O', 'P', 'I', 'C', '_',
 'N', 'A', 'M', 'E', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', '\x00', '\x00', '\x00', '\x07',
 '\x00', '\x00', '\x00', '\n', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', 
'\xff', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x01', '\xff', '\xff', '\xff',
 '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\x00', '\x00', '\x00', '\x00', '\x00', 
'\x00', '\x00', '\r', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff',
'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x07', '\xff', '\xff', '\xff', '\xff',
 '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', 
'\x00', '\x10', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\x00', 
'\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x13', '\xff', '\xff', '\xff', '\xff', '\xff', 
'\xff', '\xff', '\xff', '\xff', '\xff', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', '\x00', 
'\x04', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\xff', '\x00', '\x00', 
'\x00', '\x00']
```

This doesn't really look like any data that should come out of that topic and it makes sense why it's incorrectly being parsed, as the first 4 bytes for the throttle time are missing (note that I do see those first 4 bytes on fetch responses that do contain data).

**Comment by edenhill** [comment]
Interesting! So if I read this correctly it only happens when throttling is enabled and kicks in?
If so; what's your throttling config on the broker?

**Comment by mfontanini** [comment]
That really seems to be the issue. I can actually not reproduce this on my laptop but I can on any server inside the data center. Which makes it look even more like some throttling issue, as I obviously have less throughput on my laptop. Also, there's a ton of data in this topic, so I could be consuming for a long time before I reached EOF. 

This is the configuration we're using (let me know if you need any other value):

```
quota.consumer.default=5242880
quota.producer.default=5242880
```

**Comment by mfontanini** [comment]
Okay, this is definitely related to throttling. I wasn't explicitly setting the `client.id`, so all my consumers were using `rdkafka` as it. The quota is applied per client id, so that's why spawning one consumer would cause the same issue on other topics' consumers. Now I'm using different client ids and this issue doesn't take down the rest.

**Comment by mfontanini** [comment]
For now I'm setting `max.in.flight.requests.per.connection=100` as a workaround, which seems to be enough to not trigger the issue.

**Comment by edenhill** [comment]
I think you might be hitting issue #756 which is now fixed on partition_changes branch:
https://github.com/edenhill/librdkafka/commit/9db322b525685daad40d5c779d68fb0c37225769

**Comment by mfontanini** [comment]
Thanks! I'll test this in a few hours and will get back to you. Is there an estimated date for when that branch makes it into a release?

**Comment by edenhill** [comment]
This will be merged to master today and there'll be a formal 0.9.2 release within a couple of weeks.

**Comment by mfontanini** [comment]
The fix seems to be working fine! Thank you so much for the quick response.
