### ISSUE TITLE
Consumers indicate RD_KAFKA_RESP_ERR__PARTITION_EOF, meanwhile they suffer big lags and partitions are written continuously

### ISSUE THREAD

**Issue by microwish** [edenhill/librdkafka#807]
# Description

I have more than ten topics in Kafka. "topicA" is one of the topics having fewest data and it has 11 partitions with replica factor 3.
However, consumers of topicA always indicate RD_KAFKA_RESP_ERR__PARTITION_EOF and meanwhile those consumers suffer big lags.
Consumers of all the other topics, including those of topics with much much more data, work quite well.

Do you have any idea on why consumers of topicA work badly?
# How to reproduce
# Checklist

Please provide the following information:
- [x] librdkafka version (release number or git tag): 0.9.1
- [x] Apache Kafka version: kafka_2.10-0.8.2.2
- [ ] librdkafka client configuration:
- [x] Operating system: CentOS 6.4
- [ ] Using the legacy Consumer
- [ ] Using the high-level KafkaConsumer
- [ ] Provide logs (with `debug=..` as necessary) from librdkafka
- [ ] Provide broker log excerpts
- [ ] Critical issue

**Comment by edenhill** [comment]
Are you using the legacy consumer (consume_start()) or the high-level one? (subscribe()¸, assign())?
How are you calculating the lag?
Does it consume any message at all?

**Comment by microwish** [comment]
I'm using the legacy consumer.
Lag calculation: the largest offset of partition - the offset a consumer submits every time
Yes, it consumes messages but often encounters RD_KAFKA_RESP_ERR__PARTITION_EOF.

**Comment by edenhill** [comment]
It will emit an EOF event whenever it reaches the end of the partition, since the end will move for each produced message you might see this  event often.
Seeing the EOF is also an indication that the consumer is keeping up and not lagging.

**Comment by microwish** [comment]
I had been thinking so. However, the fact is the offsets of every partitions the consumers submit by the default interval are behind the latest offsets very much. So I feel the problem quite weird.

**Comment by edenhill** [comment]
Are you doing manual or auto commits?
What are you using to check the committed offsets for lag?
Are you sure you look at the same partitions in both cases (EOF and committed offsets)?

**Comment by microwish** [comment]
I'm doing auto commits.
I use two ways to check offsets and lags. One is Kafka manager, the other is offset records committed automatically and largest offsets of segment files on brokers.
Yes, I'm sure.

**Comment by edenhill** [comment]
Can you provide some debug logging that shows the problem in action?
debug=cgrp,topic  should do it

**Comment by microwish** [comment]
Hi Magnus,

I've just sent the logs with "debug=cgrp,topic" turned on to your email magnus@edenhill.se.
The subject of the email is "About issue #807".

Thanks.

**Comment by microwish** [comment]
Hi Magnus,

Have you received my email?

Thanks.

**Comment by edenhill** [comment]
You seem to be using offset.store.method=file which means offsets are committed to a local file rather than the broker. (you should typically offset.store.method=broker)
I can only imagine Kafka manager using the broker based offset commits to figure out lag.

In the log you sent me it seems that there is no printout from your programming telling what offset it has consumed, there's also no indication what the offset should be, so it is hard to draw any conclusions from it.

**Comment by microwish** [comment]
Yes, I'm using offset.store.method=file instead of broker. When calculating lag, I get the largest offset from Kafka manager or check it directly on brokers (segment files). And then from the local files recording consumed offset, I can calculate the lag.

I've turned on "debug=cgrp,topic". What config should be turned on in order to print out more information?

Thanks.

**Comment by edenhill** [comment]
To be able to correlate what the application is actually seeing to what the library does you need to modify your application to print the topic+partition+offset of messages it is handling every 1 second or so.

Also enable `debug=cgrp,topic,fetch`

**Comment by edenhill** [comment]
Please also provide the highwater offsets reported by Kafka Manager in a meaningful manner along with the log.

E.g.: "at time X Kafka manager reported hi offset Y for partition Z"

**Comment by microwish** [comment]
Good news, but still confusing.

As per the log enabling "debug=cgrp,topic,fetch", we decreased the value of queued.min.messages, the problem went away. However, the application had always been working well with the original queued.min.messages.

Thanks.
