### ISSUE TITLE
Memory usage while consuming

### ISSUE THREAD

**Issue by winbatch** [edenhill/librdkafka#81]
Have you ever seen a case where when consuming, if the consumer can't keep up (let's say he is writing each message to slow disk), that the amount of memory explodes?  I'm seeing that.  I've run valgrind and don't see any leaks, etc. thinking librdkafka is caching msgs but I haven't changed any of the defaults in terms of fetch.message.max.bytes, etc.

**Comment by kant111** [comment]
@winbatch Going through this discussion I am wondering why you ran out of memory ? The default value for `queued.min.messages` is `100,000` and say your message size 20KB(which is a lot but whatever) then 100K * 20KB = 2GB. so what is your message size and the memory you have?

**Comment by winbatch** [comment]
@kant111  - This was more than 2 1/2 years ago and I'm sure many versions of kafka and librdkafka ago.

**Comment by kant111** [comment]
@winbatch I am sorry I did not understand your latter part of the sentence.
