### ISSUE TITLE
Does librdKafka Producer gurantees FIFO ?

### ISSUE THREAD

**Issue by abhit011** [edenhill/librdkafka#811]
Description
===========
Does librdkafka c++ produce() API guarantee that the order in which messages  gets inserted to a topic, at consumer end consume() API the messages gets consumed in exactly FIFO Order ? 
Because for me the order really matters a lot 

Abhi

**Comment by abhit011** [comment]
I assume that with same kafka producer , if i send the messages , it should picked in exactly in the same order (FIFO) at consumer end

**Comment by edenhill** [comment]
Message ordering only makes sense on a partition level, not topic level.
And to guarantee strict ordering you will need to disable retries by setting `message.send.max.retries=0`.

Generally though it is recommended to allow for message reordering in your application,.
