### ISSUE TITLE
OpenSSL global destructor fix

### ISSUE THREAD

**Issue by edenhill** [edenhill/librdkafka#815]
Issue seen in https://github.com/arnaud-lb/php-rdkafka/issues/59 where both librdkafka and curl use OpenSSL. When libraries are unloaded from memory on PHP termination the global callbacks will reference unmapped memory causing a crash.

PostgreSQL's fix for the same is here:
https://www.postgresql.org/message-id/20081203200427.0A23B7545A4@cvs.postgresql.org

**Comment by dzuelke** [comment]
This was my dumb attempt, but it doesn't seem to be working: https://github.com/edenhill/librdkafka/compare/master...dzuelke:unset_ssl_callbacks

**Comment by edenhill** [comment]
rd_kafka_transport_term() is never called :)
I just left it in there as documentation as why it shouldnt be used..

**Comment by edenhill** [comment]
I have a fix on the way though

**Comment by dzuelke** [comment]
Oh I see now. My bad =)

**Comment by dzuelke** [comment]
I can test right away once you got a fix ready!

**Comment by edenhill** [comment]
Awesome, it will be on the partition_changes branch in a few minutes, just need it to pass the SSL and SASL tests.

**Comment by edenhill** [comment]
There, go crazy!

**Comment by dzuelke** [comment]
No more crash! Good stuff @edenhill :)

**Comment by edenhill** [comment]
wohoo! Thanks for all the fantastic work on this!
The partition_changes branch will end up in master in a week or two.

**Comment by edenhill** [comment]
Do you need it cherry-picked in master sooner than that?

**Comment by dzuelke** [comment]
Nah I think I'll wait for 0.9.2. If I want to ship PHP+Kafka support on Heroku earlier I can always use that branch, but I won't be able to do that next week anyway, so the week after sounds mighty fine :)

**Comment by dzuelke** [comment]
Also general 👊🏼 for your A++ responsiveness to issues. Remind me to buy you a drink if we ever run into each other; I got the memory of a goldfish so I'll certainly forget.

**Comment by edenhill** [comment]
I clearly remember you saying 2 drinks

**Comment by edenhill** [comment]
This issue is now fixed on master, please try to verify the fix in your environment.
Thank you.

**Comment by dzuelke** [comment]
Still works with master! Thanks!
