### ISSUE TITLE
How many consume threads gets spwaned by a librdkafka ?

### ISSUE THREAD

**Issue by abhit011** [edenhill/librdkafka#817]
Description
===========
@edenhill  , does there exist any logic /science , like how many threads gets spwaned by librdkakfa ? 
I mean if I have 3 brokers, with 3 partations and replication factor of 2 , and total 10 topics. Does there exists any such logic? How many threads gets spwaned by librdkafka to handle msgconsume() ?

Abhi

**Comment by edenhill** [comment]
librdkafka creates 1+B+N threads per instance, where B is the number of bootstrap brokers and N is the number of brokers in the cluster.
If the bootstrap brokers are named exactly as reported by the broker metadata (advertised.host.name..) then it is 1+N
