### ISSUE TITLE
Producer performance when a single broker vs. multi brokers

### ISSUE THREAD

**Issue by seongyun-ko** [edenhill/librdkafka#818]
# Description

When a producer publishes to a single broker (a single partition), its transfer rate is about ~30 MB/sec.
However, when it dose to two brokers (the topic has two partitions on each broker), its transfer rate drops significantly down to 4 Mb/sec.

Is it related with batching/buffering the messages? (I am using "queue.buffering.max.messages" = 20, "batch.num.messages" = 2. ) For example, the messages to the different brokers cannot be batched together, which can decrease the overall batching efficiency.
The application program is performing batch and strictly handling the buffering policies so I make queueing/batch in Kafka side as small as possible.

**This issue is not a problem to me, but I just want to know what can be possible causes for this issue** 💃   Could you give me an idea?
# How to reproduce
- 1:  a producer <----> a broker
- 2: a producer <----> two brokers
# Checklist

Please provide the following information:
- [ ] librdkafka version (release number or git tag): 
- [ ] Apache Kafka version: 0.9.1
- [ ] librdkafka client configuration:
  Producer: "queue.buffering.max.messages" = 20, "batch.num.messages" = 2
- [ ] Operating system:
  CentOS 7
- [ ] Using the legacy Consumer
- [ ] Using the high-level KafkaConsumer
- [ ] Provide logs (with `debug=..` as necessary) from librdkafka
- [ ] Provide broker log excerpts
- [ ] Critical issue

**Comment by edenhill** [comment]
Monitor rtt (latency) metrics in statistics (https://github.com/edenhill/librdkafka/wiki/Statistics) or use `debug=protocol` to see the rtt of Produce requests.
