### ISSUE TITLE
Can we do KafkaConsumer and KafkaProducer in same process ?

### ISSUE THREAD

**Issue by abhit011** [edenhill/librdkafka#819]
Description
===========
Just want to know , can we do KafkaProduce and KafkaConsume in a single process / applicaiton.

The use case is like that , e.g if my kafkaconsumer is consuming messages and it does analytics, and after that it does batch save in Data Base. 
Lets say the Database stops responding for some time, so I push those failed messages again into a new Kafka Topic  named as "FailedOnes", (I have already created a Kafka Producer instance, and passed the reference of that instance to each DB Batch Write thread ). Hence in future if I want to see how many failed messages exists , i can see it . Or does there exist any other better method than this ?

My Kafka Consumer looks like this

```
int CLASSKAFKA::doWarmUpTheKafkaConsumer(void){
		
		if (NULL == m_KafkaConf)
			return -1; 

		if (NULL == t_KafkaConf)
			return -1; 
		
		t_KafkaConf->set("auto.offset.reset", "smallest", errstr);
		m_KafkaConf->set("rebalance_cb", m_ex_rebalance_cb, errstr);
		
		m_KafkaConf->set("metadata.broker.list", m_brokersAddress, errstr);
		
		if (m_KafkaConf->set("group.id", "axGroud1", errstr) != RdKafka::Conf::CONF_OK)
		{
			return -1;
		}

		if (m_ex_event_cb == NULL)
			return -1; 

		m_KafkaConf->set("event_cb", m_ex_event_cb, errstr);		
		m_KafkaConf->set("default_topic_conf", t_KafkaConf, errstr);

		delete t_KafkaConf; 

		topicsList.push_back(std::string("00"));
		topicsList.push_back(std::string("01"));
		topicsList.push_back(std::string("02"));
		topicsList.push_back(std::string("03"));
		topicsList.push_back(std::string("04"));
		topicsList.push_back(std::string("05"));
		topicsList.push_back(std::string("06"));
		topicsList.push_back(std::string("07"));
		topicsList.push_back(std::string("08"));
		topicsList.push_back(std::string("09"));

		RdKafka::KafkaConsumer *consumer = RdKafka::KafkaConsumer::create(m_KafkaConf, errstr);
		
		this->m_kafkaConsumer = consumer; 
		if (!consumer) {
			return -1; 
		}

		delete m_KafkaConf; 

		RdKafka::ErrorCode err = m_kafkaConsumer->subscribe(topicsList);
		return 0;
	}
```

and my KafkaProducer in same process looks like this
```
int KafkaProducer::doWarmUpTheKafkaProducer(void){
		
		if (NULL == m_KafkaConf)
			return -1; 

		if (NULL == t_KafkaConf)
			return -1; 

		if (NULL == ex_dr_cb)
			return -1; 

		m_KafkaConf->set("metadata.broker.list", m_brokersAddress, errstr);			
		m_KafkaConf->set("dr_cb", ex_dr_cb, errstr);
		t_KafkaConf->set("produce.offset.report", "true", errstr);
		
		m_KafkaConf->set("event_cb", m_ex_event_cb, errstr);

		m_kafkaProducer = RdKafka::Producer::create(m_KafkaConf, errstr);
		if (!m_kafkaProducer) {
			kafka_logger1->critic() << "Failed to create Kafka Producer";
			return -1; 
		}

		m_kafkaTopic[0] = RdKafka::Topic::create(m_kafkaProducer, "FailedOnes", t_KafkaConf, errstr);
		if (!m_kafkaTopic[0]) {
			kafka_logger1->critic() << "Failed to create m_kafkaTopic00";
			return -1;
		}

		return 0;
	}
```

Abhi

**Comment by edenhill** [comment]
Yes, you can run multiple RdKafka instances in the same process.

Just make sure not to share any objects (e.g., Topic, Message, etc) between them.

**Comment by abhit011** [comment]
Because I am really getting unwanted results.

1. When i created the kafka topics, i mentioned kafka-topics.bat --alter --zookeeper 127.0.0.1:2181 --topic 00 --config retention.ms=120000

2. I have already consumed close to 600000 before I added  KafkaProducer piece of code for failed ones in the same process.. To my utter astonishment, it again started consuming the data from start . Hows that possible ? Or what hasn't retention.ms not taken place or what ? 

Abhi

**Comment by edenhill** [comment]
retention.ms controls standard topics.
Consumer group offsets are stored in a special topic controlled through `offsets.retention.minutes` (et.al) which defaults to 24 hours. Sound reasonable?

**Comment by abhit011** [comment]
But when I have already consumed all the offsets of each topic thats 00,01,02 till 09 , then why it again started consuming ?

**Comment by edenhill** [comment]
If a stored offset cannot be retrieved (because there is none, or it was removed due to offsets.retention.*) the configuration `auto.offset.reset` kicks in and it will start reading from the beginning instead (with your "smallest" config)

**Comment by edenhill** [comment]
Did you wait longer than 24 hours between your last consumer run and the next?

**Comment by abhit011** [comment]
Last time i ran the tests around 18-19 hrs ago..

**Comment by edenhill** [comment]
Is it reproducible if you run it now? Will it start from the beginning each time you start your program?
