### ISSUE TITLE
RebalanceCB is not getting called 

### ISSUE THREAD

**Issue by abhit011** [edenhill/librdkafka#820]
Description
===========
My Kafka set up
Zookeper + 4 Kafka Broker Nodes: on one server: **IP: x.x.x.100** and here I am also running my **KafkaConsumer instance**
Another server **IP: X.X.X.105 , in this I am running the KafkaProducer.**

Both my KafkaProducer, KafkaConusmer broker addresses points to ip: x.x.x.100 and all its all kafka broker node's port. 
e.g m_brokersAddress = kafkaBrokerBaseIP + ":9093," +
						   kafkaBrokerBaseIP + ":9094," +
						   kafkaBrokerBaseIP + ":9095," +
						   kafkaBrokerBaseIP + ":9096" ;

Now KafkaProducer is able to dump the messages at  x.x.x.100, but there is strange thing happening at
my KafkaConsumer thats running on ip:x.x.x.100 machine, ReblanceCB does not get called that's why consumer can't consume.

Now if I run the kafkaConsumer from my machine using server  x.x.x.100 ip address, it started consuming :( Am i missing something ?

Abhi

**Comment by edenhill** [comment]
Add conf property `debug=cgrp,broker` to KafkaConsumer to find out what is going on

**Comment by abhit011** [comment]
my bad, it was a small ***up from my end 🗡 . I should be killed for that ;)

**Comment by edenhill** [comment]
That might be a bit drastic

**Comment by abhit011** [comment]
;)
