### ISSUE TITLE
rd_kafka_topic_new is return NULL ptr

### ISSUE THREAD

**Issue by pachacutec** [edenhill/librdkafka#821]
Description
===========
I am getting topic_t*  NULL. Before to send data,  I call rd_kafka_topic_new api to get the rd_kafka_topic_t* to use in the rd_kafka_produce, but when I call several time this api, this api return a NULL ptr.

Checking the code seem to be found the topic but 
`rdkafka_topic.c line: ~253 return rkt->rkt_app_rkt;`
`is NULL
Configuration

    "queue.buffering.max.messages", "5000000"
    "client.id", "databus_producer_performance"
    "produce.offset.report", "true"
    "batch.num.messages", "1000"
    "queue.buffering.max.ms", "1000"
     "message.max.bytes", "1000000"
    // End

How to reproduce
================
int send_data(handle, topic, kafka_payload, payload_len) 
{
```
 rd_kafka_topic_t* rkt = rd_kafka_topic_new(handle, topic, kafka_topic_conf);
 databus_resp_err_t err = rd_kafka_produce(rkt, record->partition, RD_KAFKA_MSG_F_FREE,
                             // Payload and length.
                             kafka_payload, payload_len,
                             // Sharding key.
                             NULL,
                             // Sharding key length.
                             0,
                             // Represents unequivocally the current message to send.
                             // This will be consulted in the dr_cb from the rkmessage->_private value.
                             NULL);
```
}
logs for reference-count
 DEBUG: &(s_rkt)->rkt_refcnt                1537 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1536 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1535 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1534 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1533 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1532 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1531 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1530 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1529 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1528 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1527 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1526 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1525 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1524 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1523 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1522 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1521 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1520 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1519 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1518 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1517 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1516 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1515 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1514 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1513 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1512 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1511 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(rkb)->rkb_refcnt                  7 +1:         0x6ae358: rd_kafka_recv:1302
REFCNT DEBUG: &(request)->rkbuf_refcnt            1 +1:   0x7f51341017d8: rd_kafka_buf_callback:524
REFCNT DEBUG: &(request)->rkbuf_refcnt            2 -1:   0x7f51341017d8: rd_kafka_buf_callback:531
REFCNT DEBUG: &(rkb)->rkb_refcnt                  8 +1:         0x6ae358: rd_kafka_recv:1302
REFCNT DEBUG: &(request)->rkbuf_refcnt            1 +1:   0x7f5134201788: rd_kafka_buf_callback:524
REFCNT DEBUG: &(request)->rkbuf_refcnt            2 -1:   0x7f5134201788: rd_kafka_buf_callback:531
fail - f
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1510 -1:         0x6ad080: rd_kafka_topic_destroy:87
databus_producer_performance: /home/ammarch/src/pure/databus-libdatabus/src/producer/databus_producer.c:224: databus_producer_send: Assertion `rkt != NULL' failed.
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1509 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1508 -1:         0x6ad080: rd_kafka_topic_destroy:87
REFCNT DEBUG: &(s_rkt)->rkt_refcnt                1507 -1:         0x6ad080: rd_kafka_topic_destroy:87

Checklist
=========
Please provide the following information:

 - [x ] librdkafka version (release number or git tag): lastest trunk
 - [x] Apache Kafka version: 0.10.0.1
 - [X ] librdkafka client configuration:
 - [x ] Operating system: Linux Debian/Ubuntu
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x ] Critical issue

**Comment by edenhill** [comment]
You should typically only call topic_new() once per topic and hold on to the returned object for future produce() calls

**Comment by pachacutec** [comment]
Ok, I will make this changes and let you know. just to mention in 0.9.1 version is working,

**Comment by pachacutec** [comment]
Yeap, it is working, if it is not called all the time

**Comment by edenhill** [comment]
I'll look into the regression

**Comment by edenhill** [comment]
This issue is now fixed on master, please try to verify the fix in your environment.
Thank you.
