### ISSUE TITLE
Support for Native compilers

### ISSUE THREAD

**Issue by abhisharma** [edenhill/librdkafka#828]
Description
===========
I'm trying to build librdkafka(0.9.1) on Sun and IBM. Using GCC/G++, I'm able to build on both platforms and I'm also able to pass all tests except one test(compression test). But I need to make it work with native compilers. 

I started with Sun and tried with following compilers:
Sun C 5.12 SunOS_sparc Patch , Sun C++ 5.12 SunOS_sparc Patch 

I have 300+ errors related to following categories:
1. Typecasting needed errors
2. Enums inside structs not visible
3. "#pragma once" not being recognized and resulting in multiple definitions errors
4. Conversion issues between enums and ints
5. Designated initializers for arrays not being recognized
........and list goes on ......

Question:
Do you have any idea on level of effort needed for this support? Could you please provide any help or insight?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
This pops up every now and then (but it is becoming rarer, thank god!).

The librdkafka code is a mix of C89 and C99, these native compilers usually comply with C89 if you are lucky.

What needs to be done is simply(..) fixing all those errors without affecting existing platforms, and without making too big changes to the code, which is not a small task.

And I'm not really sure it is worth the effort, it might be better to try to use a modern toolchain instead.
