### ISSUE TITLE
consumer group can not be listed on the kafka brokers by command-line tools

### ISSUE THREAD

**Issue by castlewang** [edenhill/librdkafka#829]
Description
===========
When I run two consumers(rdkafka_consumer_example) built from the example source code(librdkafka-0.9.1/examples/rdkafka_consumer_example.c) using the same group name and command line parameters, or run two consumers with the same group name built from my code, it seems that the consumer group has been created and worked successfully. But when I use the kafka command-line tool, kafka-consumer-groups.sh, my consumer group is not show up.

why can not i find my consumer group on the brokers?

How to reproduce
================
Directly run the rdkafka_consumer_example program twice, with the same command line parameters, like this

`./rdkafka_consumer_example -g rdkafka_consumer_example_test -b 10.58.118.79:9092,10.58.118.82:9092,10.194.2.193:9092 -d cgrp -A cfm_game_weapon_stat`

and then login the brokers, and use the kafka-consumer-groups.sh like this:

` sh  kafka-consumer-groups.sh --zookeeper 10.58.118.79:2183,10.58.118.82:2183,10.194.2.193:2183 --list`

rdkafka_consumer_example_test is not listed.

here 10.58.118.79:9092,10.58.118.82:9092,10.194.2.193:9092 is the broker list, while the 10.58.118.79:2183,10.58.118.82:2183,10.194.2.193:2183 is the zk list which the brokers are
registered.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):0.9.1
 - [ ] Apache Kafka version: 0.9.0
 - [ ] librdkafka client configuration:
 - [x] Operating system: Linux 2.6.32.43
 - [x] Using the legacy Consumer no
 - [x] Using the high-level KafkaConsumer yes
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You are querying the old legacy consumer groups (in ZK), librdkafka only supports the new broker based consumer groups, try this instead:

`kafka-consumer-groups.sh --bootstrap-server 10.58.118.89:9092 --new-consumer --list`

**Comment by shengbinxu** [comment]
@edenhill  very good!
