### ISSUE TITLE
Producer message order

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#831]
Hello Eden,

Can you please indicate the necessary settings for the producer that preserve message order.
The scenario is:
1.I have an application that calls produce (in different threads).
2.Messages are produced in bursts. So there might be no messages for 1 minute but 10000 in one second.
3.I assume the message order to be the order the messages end up in the producer queue.

How do i make sure that the producer preserves the order of the messages stored on the broker to be the same as they are in the producer queue? Preserve under **any** circumstances (broker failure, etc.).
1.Must i set "**max.in.flight.requests.per.connection**" to 1 (the default is 1000000)? Is this sufficient or must i do point 2?
2.Must i set "**retries**" to 0? Or can this stay the default (2) ?
3.Importantly how do i not compromise the throughput (as measured as messages/sec) with the settings? I am happy to accept some performance degradation but believe it must be kept minimal if messages are produced in bursts.
Also I am not concerned about duplicate messages.

**Comment by edenhill** [comment]
Look for "Message ordering" here:
http://docs.confluent.io/3.0.1/clients/producer.html

**Comment by MaximGurschi** [comment]
Thank you Eden for pointing me to that great page!
It confirms my suspicion.

One last point. If I use:
max.in.flight.requests.per.connection=1
retries>0

, to guarantee no gaps but still have the retry mechanism work, must i set retries to the maximum value (10000000)?

**Comment by edenhill** [comment]
Yes, you will need to set retries (and message.timeout.ms) silly high.

**Comment by edenhill** [comment]
Do note though that max.in.flight..=1 is a performance killer since the throughput rate will be directly limited by the broker round-trip-time.

**Comment by MaximGurschi** [comment]
Thanks. I think max.in.flight can run at 20% of the unconstrained use case.
Am afraid i have no choice since the order is critical.
