### ISSUE TITLE
ssl.certificate.location (Documentation - QUESTION) - Is it only PEM file format supported for "C" Clients?

### ISSUE THREAD

**Issue by pabloaguerre** [edenhill/librdkafka#834]
Question linked to SSL Documentation issue: https://github.com/edenhill/librdkafka/issues/473

**Comment by pabloaguerre** [comment]
Can I user .crt format instead of PEM?

**Comment by edenhill** [comment]
The OpenSSL documentation says this:
> SSL_CTX_use_certificate_chain_file() loads a certificate chain from file into ctx. The certificates must be in PEM format and must be sorted starting with the subject's certificate (actual client or server certificate), followed by intermediate CA certificates if applicable, and ending at the highest level (root) CA. SSL_use_certificate_chain_file() is similar except it loads the certificate chain into ssl.

For SSL_CTX_use_certificate_chain_file() which ssl.certificate.location maps to

https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_use_certificate.html
