### ISSUE TITLE
librdkafka snappy conflict with google snappy lib

### ISSUE THREAD

**Issue by hustlijian** [edenhill/librdkafka#835]
Description
===========
snappy conflict with [google snappy](https://github.com/google/snappy);
because they have same function name and different params,
eg:
[google snappy](https://github.com/google/snappy/blob/master/snappy-c.h#L71)
`snappy_status snappy_compress(const char* input,  
                              size_t input_length,  
                              char* compressed,  
                              size_t* compressed_length);`

[librdkafka](https://github.com/edenhill/librdkafka/blob/master/src/snappy.h#L21)
`int snappy_compress(struct snappy_env *env,  
		    const char *input,  
		    size_t input_length,  
		    char *compressed,  
		    size_t *compressed_length);`

How to reproduce
================
comiple google snappy with librdkafka.

Suguestion
===========
my solution: 
use function header : 
`sed -i 's/snappy_init_env/rdkafka_snappy_init_env/g' snappy.h  snappy.c rdkafka_broker.c  
sed -i 's/snappy_free_env/rdkafka_snappy_free_env/g' rdkafka_broker.c snappy.h snappy.c  
sed -i 's/snappy_uncompress/rdkafka_snappy_uncompress/g' rdkafka_broker.c snappy.h snappy.c  
sed -i 's/snappy_compress/rdkafka_snappy_compress/g' rdkafka_broker.c snappy.h snappy.c  
sed -i 's/snappy_max_compressed_length/rdkafka_snappy_max_compressed_length/g' rdkafka_broker.c snappy.h snappy.c`

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you submit a PR? Thanks

**Comment by hustlijian** [comment]
OK, I've  submitted: [add snappy function header to be compatible with google snappy#840](https://github.com/edenhill/librdkafka/pull/840)
