### ISSUE TITLE
Clean up pointers

### ISSUE THREAD

**Issue by jupiterh** [edenhill/librdkafka#838]
Description
===========
In rdkafka_example.cpp, both  RdKafka::Conf *conf = (RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL) and RdKafka::Conf *tconf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC) are created, but never deleted. Should both be deleted when the program is ended? Will it cause memory leak if don't clean up those points?

Also, in the consume callback class, it passes a message reference to the consume_cb, I guess the RdKafka::ConsumeCb will clean up the message buffer, the user does not need to worry about cleaning up the message buffer after reading the message, right?

Thank you.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
The C and C++ interfaces differ when it comes to their respective config objects:
 * in C the new() APIs takes ownership of the provided conf and the application must not destroy them
 * in C++ the application remains owner of the Conf objects and need to delete them explicitly.

Re ConsumeCb: your assumption is correct, the library will free the message.
The opposite is true for the APIs that return a Message (consume())

**Comment by kparadkar** [comment]
Regarding your last comment, about ConsumeCb, is same valid for Consume_cb in C? 
i.e with High level consumer, if consume_cb is configured, rd_kafka_message_destroy should not be called on consumed message, is this statement right?

**Comment by edenhill** [comment]
That's right, see here:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L2035

**Comment by kparadkar** [comment]
Can 'rd_kafka_consume_callback' be used for High level consumers?

**Comment by edenhill** [comment]
Nope, the high-level consumer does not feature consume_cb callbacks at this point.
