### ISSUE TITLE
0.9.2RC1 tag name and directory name differ

### ISSUE THREAD

**Issue by dzuelke** [edenhill/librdkafka#845]
The latest tag is `v0.9.2-RC1`, but the tarball contains a folder named `librdkafka-0.9.2-RC1`, without the "v".

Looking through previous tags, it appears like their naming has been inconsistent, sometimes with a "v", sometimes not.

This is a problem for automated build scripts etc, since they need adjusting each time.

My recommendation would be to not use the "v" in tag names, and to also append postfixes for beta, RC etc without a dash, so "0.9.2RC1", and to have the archives consistently use `reponame-tagname` as the top level folder.

**Comment by edenhill** [comment]
:(

**Comment by edenhill** [comment]
The switch to v-prefix was decided on to be consistent with other Confluent packages.

Sorry for the inconvenience.

Regarding archive directory prefixes; I dont think github gives me any control over that.

**Comment by dzuelke** [comment]
That's cool; as long as it's consistent :)
