### ISSUE TITLE
When I produce data, I get a "full Queue" error, which is caused by no call "rd_kafka_poll"?

### ISSUE THREAD

**Issue by DavidLiuXh** [edenhill/librdkafka#848]
Description
===========
When I produce data, I get a "Queue full" error, which is caused by no call "rd_kafka_poll"?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Typically yes (or that you are producing faster than the broker can handle).

If you've registered a delivery report callback you will need to call rd_kafka_poll() regularily to serve the callback queue.

**Comment by DavidLiuXh** [comment]
@edenhill Thanks. I added "rd_kafka_poll", can't reproude "Queue full" error.

**Comment by edenhill** [comment]
Great!
