### ISSUE TITLE
rdkafka-master/rdkafka.c:54: error: redefinition of typedef ‘kafka_object’

### ISSUE THREAD

**Issue by goldlife1981** [edenhill/librdkafka#849]
Description
===========
when i make  librdkafka  .  I get   a "rdkafka-master/rdkafka.c:54: error: redefinition of typedef ‘kafka_object’"  error

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There is no `kafka_object` in librdkafka.
Maybe you are referring to the PHP client? If so, open an issue there:
https://github.com/arnaud-lb/php-rdkafka
