### ISSUE TITLE
How to minimize the latency involved in kafka messaging  while high load

### ISSUE THREAD

**Issue by mmanoj** [edenhill/librdkafka#853]
Description
===========
we refer your guide and modify rdkafka_example.c to producer, however i single machine we still observed nearly 1 min delay to retrieval of the messages to consumer. we observe this once the load increase around 2000 msg / sec pumping to kafka

        /* Minimize wait-for-larger-batch delay (since there will be no batching) */
        rd_kafka_conf_set(conf, "queue.buffering.max.ms", "1", NULL, 0);
        /* Minimize wait-for-socket delay (otherwise you will lose 100ms per message instead just the RTT) */
        rd_kafka_conf_set(conf, "socket.blocking.max.ms", "1", NULL, 0);
----------------------------------------------------------------------------------------
if (report_offsets) {
                        rd_kafka_topic_conf_set(topic_conf,
                                                "produce.offset.report",
                                                "true", errstr, sizeof(errstr));
                        
                         /* Minimize wait-for-larger-batch delay (since there will be no batching) */
        rd_kafka_conf_set(topic_conf, "queue.buffering.max.ms", "1", errstr, sizeof(errstr));
        /* Minimize wait-for-socket delay (otherwise you will lose 100ms per message instead just the RTT) */
        rd_kafka_conf_set(topic_conf, "socket.blocking.max.ms", "1", errstr, sizeof(errstr));

Seeking your advice to reduce the latency:

My kafka version -8.0
librd kafka version- latest from git
OS -Ubuntu -Ubuntu 16.04.1 LTS 4.4.0-38-generic

 

How to reproduce
================
Please share the email I will send my code.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by mmanoj** [comment]
main idea is we need to get the notifications from kafka to consumer real time max delay 5 sec.

**Comment by edenhill** [comment]
There are tricks to decrease the internal latency of librdkafka, but that is usually only required when you want to bring it down from the typical latency of 100ms to a handful of the same.

A 1 minute delay is an indication that something else is strange.
If you register a stats_cb you can monitor the statistics for 'rtt' (broker round trip time) to figure out if that's where the time is spent. Alternatively you can use `debug=protocol` and look for `ProduceResponse .. rtt ..` printouts.

**Comment by mmanoj** [comment]
Hi, 

Thanks for the feedback, Can you elaborate more details. I'm using librdkafka_example.c program. So I can modify and test. Above settings I was done is fine ? any changes required.

**Comment by edenhill** [comment]
How are you measuring latency?
You can enable protocol debugging with rdkafka_example by appending the `-d protocol` command line argument.

**Comment by mmanoj** [comment]
I was embedded to my another program which generate traffic. My program calling producer code as external function. Is there another way I can enable debugging in code level. 
Basically we are measuring latency by looking at local application data processing via log and kafka command line consumer regarding kafka publish. So we notice local processing and kafka consumer output having delay.

**Comment by edenhill** [comment]
The message should show up at the consumer within milliseconds after it has been succesfully produced.
You should try to slim down your test scenario and separate things so you know what takes time.

**Comment by mmanoj** [comment]
/* Minimize wait-for-larger-batch delay (since there will be no batching) */
        rd_kafka_conf_set(conf, "queue.buffering.max.ms", "1", NULL, 0);
        /* Minimize wait-for-socket delay (otherwise you will lose 100ms per message instead just the RTT) */
        rd_kafka_conf_set(conf, "socket.blocking.max.ms", "1", NULL, 0);

**Comment by mmanoj** [comment]
this is  my config

**Comment by edenhill** [comment]
As I commented on earlier, those settings are for drecreasing latency from 100ms to a handful of ms.
Since you have latencies around 600 times larger than that I would say something else is wrong.
Please try a standalone producer and a consumer and measure the time from produce to consume.

**Comment by mmanoj** [comment]
you mean default example program having latency from 100ms ?

**Comment by edenhill** [comment]
librdkafka producer's have a default latency of about 100ms, so yes, if you use rdkafka_example -P  that should be your latency (plus network + broker latency)

**Comment by mmanoj** [comment]
what is the linger.ms  in default example ? are we need to set any thing?

**Comment by edenhill** [comment]
As Ive been trying to say in previous comments: if you are seeing end-to-end latencies of 1 minute (or even above a couple of seconds) it means something else is wrong, not the client library itself.
So please follow the aforementioned steps to systematically track down what part of the produce->broker->consume pipeline is adding that large latency.

**Comment by mmanoj** [comment]
ok,will check and update you.

**Comment by mmanoj** [comment]
thanks for quick support. will keep you posted.

**Comment by mmanoj** [comment]
Hi,
I'm calling renamed main method from outside program, is this can cause delay, as every time broker connection creating ? Basically I need to call producer as API call with parameters to send message from external program. Please advice how to achieve it.

Thank you,

**Comment by edenhill** [comment]
Client instances are meant to be long lived. You should not create a new one for each message, but reuse the producer instance for all your messages.

**Comment by mmanoj** [comment]
any example reference implementation can you guide.

**Comment by mmanoj** [comment]
/*
 * librdkafka - Apache Kafka C library
 *
 * Copyright (c) 2012, Magnus Edenhill
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met: 
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer. 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution. 
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * Apache Kafka consumer & producer example programs
 * using the Kafka driver from librdkafka
 * (https://github.com/edenhill/librdkafka)
 */

#include <ctype.h>
#include <signal.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <syslog.h>
#include <time.h>
#include <sys/time.h>

/* Typical include path would be <librdkafka/rdkafka.h>, but this program
 * is builtin from within the librdkafka source tree and thus differs. */
#include "rdkafka.h"  /* for Kafka driver */


static int run = 1;
static rd_kafka_t *rk;
static int exit_eof = 0;
static int quiet = 0;
static 	enum {
	OUTPUT_HEXDUMP,
	OUTPUT_RAW,
} output = OUTPUT_HEXDUMP;

//------------------
rd_kafka_topic_t *rkt;
	char *brokers = "localhost:9092,localhost:9093,localhost:9094";
	char mode = 'P';
	char *topic = NULL;
	int partition = RD_KAFKA_PARTITION_UA;
	int opt;
	rd_kafka_conf_t *conf;
	rd_kafka_topic_conf_t *topic_conf;
	char errstr[512];
	int64_t start_offset = 0;
        int report_offsets = 0;
	int do_conf_dump = 0;
	char tmp[16];
        int64_t seek_offset = 0;
        int64_t tmp_offset = 0;
	int get_wmarks = 0;

//-----------------

static void stop (int sig) {
	run = 0;
	fclose(stdin); /* abort fgets() */
}


static void hexdump (FILE *fp, const char *name, const void *ptr, size_t len) {
	const char *p = (const char *)ptr;
	size_t of = 0;


	if (name)
		fprintf(fp, "%s hexdump (%zd bytes):\n", name, len);

	for (of = 0 ; of < len ; of += 16) {
		char hexen[16*3+1];
		char charen[16+1];
		int hof = 0;

		int cof = 0;
		int i;

		for (i = of ; i < (int)of + 16 && i < (int)len ; i++) {
			hof += sprintf(hexen+hof, "%02x ", p[i] & 0xff);
			cof += sprintf(charen+cof, "%c",
				       isprint((int)p[i]) ? p[i] : '.');
		}
		fprintf(fp, "%08zx: %-48s %-16s\n",
			of, hexen, charen);
	}
}

/**
 * Kafka logger callback (optional)
 */
static void logger (const rd_kafka_t *rk, int level,
		    const char *fac, const char *buf) {
	struct timeval tv;
	gettimeofday(&tv, NULL);
	fprintf(stderr, "%u.%03u RDKAFKA-%i-%s: %s: %s\n",
		(int)tv.tv_sec, (int)(tv.tv_usec / 1000),
		level, fac, rk ? rd_kafka_name(rk) : NULL, buf);
        printf("%u.%03u RDKAFKA-%i-%s: %s: %s\n",
		(int)tv.tv_sec, (int)(tv.tv_usec / 1000),
		level, fac, rk ? rd_kafka_name(rk) : NULL, buf);
}

/**
 * Message delivery report callback.
 * Called once for each message.
 * See rdkafka.h for more information.
 */
static void msg_delivered (rd_kafka_t *rk,
			   void *payload, size_t len,
			   int error_code,
			   void *opaque, void *msg_opaque) {
    printf("---Inside msg_delivered ()----\n");

	if (error_code){
		fprintf(stderr, "%% Message delivery failed: %s\n",
			rd_kafka_err2str(error_code));
                printf("%% Message delivery failed: %s\n",
			rd_kafka_err2str(error_code));
                
        }else if (!quiet){
		fprintf(stderr, "%% Message delivered (%zd bytes): %.*s\n", len,
			(int)len, (const char *)payload);
                
        }
        printf("%% Message delivered (%zd bytes): %.*s\n", len,
			(int)len, (const char *)payload);
              
}

/**
 * Message delivery report callback using the richer rd_kafka_message_t object.
 */
static void msg_delivered2 (rd_kafka_t *rk,
                            const rd_kafka_message_t *rkmessage, void *opaque) {
    printf("-----Inside msg_delivered2 ()-------\n");
	printf("del: %s: offset %"PRId64"\n",
	       rd_kafka_err2str(rkmessage->err), rkmessage->offset);
        if (rkmessage->err){
		fprintf(stderr, "%% Message delivery failed: %s\n",
                        rd_kafka_message_errstr(rkmessage));
                printf("%% Message delivery failed: %s\n",
                        rd_kafka_message_errstr(rkmessage));
                
        }else if (!quiet) {
		fprintf(stderr,
                        "%% Message delivered (%zd bytes, offset %"PRId64", "
                        "partition %"PRId32"): %.*s\n",
                        rkmessage->len, rkmessage->offset,
			rkmessage->partition,
			(int)rkmessage->len, (const char *)rkmessage->payload);
                printf( "%% Message delivered (%zd bytes, offset %"PRId64", "
                        "partition %"PRId32"): %.*s\n",
                        rkmessage->len, rkmessage->offset,
			rkmessage->partition,
			(int)rkmessage->len, (const char *)rkmessage->payload);
        }
}


static void msg_consume (rd_kafka_message_t *rkmessage,
			 void *opaque) {
	if (rkmessage->err) {
		if (rkmessage->err == RD_KAFKA_RESP_ERR__PARTITION_EOF) {
			fprintf(stderr,
				"%% Consumer reached end of %s [%"PRId32"] "
			       "message queue at offset %"PRId64"\n",
			       rd_kafka_topic_name(rkmessage->rkt),
			       rkmessage->partition, rkmessage->offset);

			if (exit_eof)
				run = 0;

			return;
		}

		fprintf(stderr, "%% Consume error for topic \"%s\" [%"PRId32"] "
		       "offset %"PRId64": %s\n",
		       rd_kafka_topic_name(rkmessage->rkt),
		       rkmessage->partition,
		       rkmessage->offset,
		       rd_kafka_message_errstr(rkmessage));

                if (rkmessage->err == RD_KAFKA_RESP_ERR__UNKNOWN_PARTITION ||
                    rkmessage->err == RD_KAFKA_RESP_ERR__UNKNOWN_TOPIC)
                        run = 0;
		return;
	}

	if (!quiet) {
		rd_kafka_timestamp_type_t tstype;
		int64_t timestamp;
		fprintf(stdout, "%% Message (offset %"PRId64", %zd bytes):\n",
			rkmessage->offset, rkmessage->len);

		timestamp = rd_kafka_message_timestamp(rkmessage, &tstype);
		if (tstype != RD_KAFKA_TIMESTAMP_NOT_AVAILABLE) {
			const char *tsname = "?";
			if (tstype == RD_KAFKA_TIMESTAMP_CREATE_TIME)
				tsname = "create time";
			else if (tstype == RD_KAFKA_TIMESTAMP_LOG_APPEND_TIME)
				tsname = "log append time";

			fprintf(stdout, "%% Message timestamp: %s %"PRId64
				" (%ds ago)\n",
				tsname, timestamp,
				!timestamp ? 0 :
				(int)time(NULL) - (int)(timestamp/1000));
		}
	}

	if (rkmessage->key_len) {
		if (output == OUTPUT_HEXDUMP)
			hexdump(stdout, "Message Key",
				rkmessage->key, rkmessage->key_len);
		else
			printf("Key: %.*s\n",
			       (int)rkmessage->key_len, (char *)rkmessage->key);
	}

	if (output == OUTPUT_HEXDUMP)
		hexdump(stdout, "Message Payload",
			rkmessage->payload, rkmessage->len);
	else
		printf("%.*s\n",
		       (int)rkmessage->len, (char *)rkmessage->payload);
}


static void metadata_print (const char *topic,
                            const struct rd_kafka_metadata *metadata) {
        int i, j, k;

        printf("Metadata for %s (from broker %"PRId32": %s):\n",
               topic ? : "all topics",
               metadata->orig_broker_id,
               metadata->orig_broker_name);


        /* Iterate brokers */
        printf(" %i brokers:\n", metadata->broker_cnt);
        for (i = 0 ; i < metadata->broker_cnt ; i++)
                printf("  broker %"PRId32" at %s:%i\n",
                       metadata->brokers[i].id,
                       metadata->brokers[i].host,
                       metadata->brokers[i].port);

        /* Iterate topics */
        printf(" %i topics:\n", metadata->topic_cnt);
        for (i = 0 ; i < metadata->topic_cnt ; i++) {
                const struct rd_kafka_metadata_topic *t = &metadata->topics[i];
                printf("  topic \"%s\" with %i partitions:",
                       t->topic,
                       t->partition_cnt);
                if (t->err) {
                        printf(" %s", rd_kafka_err2str(t->err));
                        if (t->err == RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE)
                                printf(" (try again)");
                }
                printf("\n");

                /* Iterate topic's partitions */
                for (j = 0 ; j < t->partition_cnt ; j++) {
                        const struct rd_kafka_metadata_partition *p;
                        p = &t->partitions[j];
                        printf("    partition %"PRId32", "
                               "leader %"PRId32", replicas: ",
                               p->id, p->leader);

                        /* Iterate partition's replicas */
                        for (k = 0 ; k < p->replica_cnt ; k++)
                                printf("%s%"PRId32,
                                       k > 0 ? ",":"", p->replicas[k]);

                        /* Iterate partition's ISRs */
                        printf(", isrs: ");
                        for (k = 0 ; k < p->isr_cnt ; k++)
                                printf("%s%"PRId32,
                                       k > 0 ? ",":"", p->isrs[k]);
                        if (p->err)
                                printf(", %s\n", rd_kafka_err2str(p->err));
                        else
                                printf("\n");
                }
        }
}


static void sig_usr1 (int sig) {
	rd_kafka_dump(stdout, rk);
}

//int main (int argc, char **argv) {
 void InitsendMSG(){
	/*
     rd_kafka_topic_t *rkt;
	char *brokers = "localhost:9092,localhost:9093,localhost:9094";
	char mode = 'P';
	char *topic = NULL;
	int partition = RD_KAFKA_PARTITION_UA;
	int opt;
	rd_kafka_conf_t *conf;
	rd_kafka_topic_conf_t *topic_conf;
	char errstr[512];
	int64_t start_offset = 0;
        int report_offsets = 0;
	int do_conf_dump = 0;
	char tmp[16];
        int64_t seek_offset = 0;
        int64_t tmp_offset = 0;
	int get_wmarks = 0;
        */
        
        printf("----Before create config---\n");
	/* Kafka configuration */
	conf = rd_kafka_conf_new();
        printf("---After create config-----\n");

        /* Set logger */
        rd_kafka_conf_set_log_cb(conf, logger);

	/* Quick termination */
	snprintf(tmp, sizeof(tmp), "%i", SIGIO);
	rd_kafka_conf_set(conf, "internal.termination.signal", tmp, NULL, 0);
        
        /* Tune params for PCRF */
       /* Minimize wait-for-larger-batch delay (since there will be no batching) */
        rd_kafka_conf_set(conf, "queue.buffering.max.ms", "1000", NULL, 0); // 1 sec
        /* Minimize wait-for-socket delay (otherwise you will lose 100ms per message instead just the RTT) */
        rd_kafka_conf_set(conf, "socket.blocking.max.ms", "1", NULL, 0);
        rd_kafka_conf_set(conf, "batch.num.messages", "100000", NULL, 0);
        rd_kafka_conf_set(conf, "request.required.acks", "-1", NULL, 0);
        rd_kafka_conf_set(conf, "compression.codec", "snappy", NULL, 0);
        

	/* Topic configuration */
	topic_conf = rd_kafka_topic_conf_new();

   
	if (do_conf_dump) {
		const char **arr;
		size_t cnt;
		int pass;

		for (pass = 0 ; pass < 2 ; pass++) {
			int i;

			if (pass == 0) {
				arr = rd_kafka_conf_dump(conf, &cnt);
				printf("# Global config\n");
			} else {
				printf("# Topic config\n");
				arr = rd_kafka_topic_conf_dump(topic_conf,
							       &cnt);
			}

			for (i = 0 ; i < (int)cnt ; i += 2)
				printf("%s = %s\n",
				       arr[i], arr[i+1]);

			printf("\n");

			rd_kafka_conf_dump_free(arr, cnt);
		}

		exit(0);
	}


	if ((mode == 'C' && !isatty(STDIN_FILENO)) ||
	    (mode != 'C' && !isatty(STDOUT_FILENO)))
		quiet = 1;


	signal(SIGINT, stop);
	signal(SIGUSR1, sig_usr1);
 }//init
        //------------------------------------------------------------------------------------------------------------------------------
void sendMSG1(const char* channel, char *data){
	if (mode == 'P') {
		/*
		 * Producer
		 */
                printf("Inside Producer--\n");
		char buf[2048];
		int sendcnt = 0;

		/* Set up a message delivery report callback.
		 * It will be called once for each message, either on successful
		 * delivery to broker, or upon failure to deliver to broker. */

                /* If offset reporting (-o report) is enabled, use the
                 * richer dr_msg_cb instead. */
                if (report_offsets) {
                        rd_kafka_topic_conf_set(topic_conf,
                                                "produce.offset.report",
                                                "true", errstr, sizeof(errstr));
                        
                         /* Minimize wait-for-larger-batch delay (since there will be no batching) */
        rd_kafka_conf_set(topic_conf, "queue.buffering.max.ms", "1000", errstr, sizeof(errstr));
        /* Minimize wait-for-socket delay (otherwise you will lose 100ms per message instead just the RTT) */
        rd_kafka_conf_set(topic_conf, "socket.blocking.max.ms", "1", errstr, sizeof(errstr));
        
                        rd_kafka_conf_set_dr_msg_cb(conf, msg_delivered2);
                } else
                        rd_kafka_conf_set_dr_cb(conf, msg_delivered);

		/* Create Kafka handle */
		if (!(rk = rd_kafka_new(RD_KAFKA_PRODUCER, conf,
					errstr, sizeof(errstr)))) {
			fprintf(stderr,
				"%% Failed to create new producer: %s\n",
				errstr);
                        printf("%% Failed to create new producer: %s\n",
				errstr);
			exit(1);
		}

		rd_kafka_set_log_level(rk, LOG_DEBUG);

		/* Add brokers */
		if (rd_kafka_brokers_add(rk, brokers) == 0) {
			fprintf(stderr, "%% No valid brokers specified\n");
                        printf("---%% No valid brokers specified\n");
			exit(1);
		}

		/* Create topic */
                topic = channel;//"TEST"; // creating publishing manoj
                
		rkt = rd_kafka_topic_new(rk, topic, topic_conf);
                topic_conf = NULL; /* Now owned by topic */

		//if (!quiet)
			//fprintf(stderr,
				//"%% Type stuff and hit enter to send\n");
				//by Manoj 05/june/2016
				//memset(buf, '\0', sizeof(buf));
                                //strcpy(buf, "This is tutorialspoint.com");
                              //  strncpy(buf,data,sizeof(buf));data = NULL;
                                //buf =data;//assign pcrf msg to buf
     

		//while (run && fgets(buf, sizeof(buf), stdin)) { // user input via command line -- manoj buff is the string buffer of message
                        //while (run) {
			size_t len = strlen(data);
			if (data[len-1] == '\n')
				data[--len] = '\0';

			/* Send/Produce message. */
			if (rd_kafka_produce(rkt, partition,
					     RD_KAFKA_MSG_F_COPY,
					     /* Payload and length */
					     data, len,
					     /* Optional key and its length */
					     NULL, 0,
					     /* Message opaque, provided in
					      * delivery report callback as
					      * msg_opaque. */
					     NULL) == -1) {
				fprintf(stderr,
					"%% Failed to produce to topic %s "
					"partition %i: %s\n",
					rd_kafka_topic_name(rkt), partition,
					rd_kafka_err2str(rd_kafka_last_error()));
                                printf("%% Failed to produce to topic %s "
					"partition %i: %s\n",
					rd_kafka_topic_name(rkt), partition,
					rd_kafka_err2str(rd_kafka_last_error()));
				/* Poll to handle delivery reports */
				rd_kafka_poll(rk, 0);
				//continue;
			}

			if (!quiet)
				fprintf(stderr, "%% Sent %zd bytes to topic "
					"%s partition %i\n",
				len, rd_kafka_topic_name(rkt), partition);
                        
                        fprintf(stdout, "%% Sent %zd bytes to topic "
					"%s partition %i\n  PCRF-Message %s\n",
				len, rd_kafka_topic_name(rkt), partition,data);
                        
			sendcnt++;
			/* Poll to handle delivery reports */
			rd_kafka_poll(rk, 0);
		//} //while

		/* Poll to handle delivery reports */
		rd_kafka_poll(rk, 0);

		/* Wait for messages to be delivered */
		while (run && rd_kafka_outq_len(rk) > 0)
			rd_kafka_poll(rk, 100);

		/* Destroy topic */
		rd_kafka_topic_destroy(rkt);

		/* Destroy the handle */
		rd_kafka_destroy(rk);

	}//producer 


        if (topic_conf)
                rd_kafka_topic_conf_destroy(topic_conf);

	/* Let background threads clean up and terminate cleanly. */
	run = 5;
	while (run-- > 0 && rd_kafka_wait_destroyed(1000) == -1)
		printf("Waiting for librdkafka to decommission\n");
	if (run <= 0)
		rd_kafka_dump(stdout, rk);

	//return 0;
}//send MSG

// This is the main function to test standalone--Manoj
//int main()
//{
//printf("Inside New Main...\n");
//InitsendMSG();
 //  sendMSG("PCRF","tstMSG"); 
//}

**Comment by mmanoj** [comment]
This is my modification as producer. Any comments and suggestions welcome. I take out below functions out as global and it can call from other program.
InitsendMSG();
sendMSG("PCRF","tstMSG");

**Comment by edenhill** [comment]
So you changed the example code to not persist the producer instance but create a new one for each message. I said in an earlier comment that is not the way to do it, you should persist the producer instance and reuse it for each message you send.

**Comment by edenhill** [comment]
The application you changed, rdkafka_example.c, is the example.
Just make sure to only create rd_kafka_t (producer) once and then reuse it for each time you call produce().

**Comment by mmanoj** [comment]
Ok, Thanks for the extensive support. I will try this method and update. Thanks again for guidelines.
