### ISSUE TITLE
Memory Leak while using librdkafka C api consumer

### ISSUE THREAD

**Issue by amit-majumdar** [edenhill/librdkafka#860]
# Description

While running the consumer using C api of librdkafka producing huge memory leak, even though rd_kafka_message_destroy is called after each message consumption.

Below is the valgrind output.

==00:04:00:26.325 29596== 1,000,528,110 bytes in 1,281 blocks are still reachable in loss record 8,814 of 8,814
==00:04:00:26.325 29596==    at 0x4C27A2E: malloc (vg_replace_malloc.c:270)
==00:04:00:26.325 29596==    by 0x34FB97AF: rd_kafka_buf_alloc_recvbuf (rd.h:87)
==00:04:00:26.325 29596==    by 0x34FA954B: rd_kafka_recv (rdkafka_broker.c:1290)
==00:04:00:26.325 29596==    by 0x34FB8728: rd_kafka_transport_io_event (rdkafka_transport.c:1025)
==00:04:00:26.325 29596==    by 0x34FAD5EF: rd_kafka_broker_serve (rdkafka_broker.c:3174)
==00:04:00:26.325 29596==    by 0x34FADB52: rd_kafka_broker_consumer_serve (rdkafka_broker.c:4436)
==00:04:00:26.325 29596==    by 0x34FAEED7: rd_kafka_broker_thread_main (rdkafka_broker.c:4548)
==00:04:00:26.325 29596==    by 0x34FD9FEE: _thrd_wrapper_function (tinycthread.c:613)
==00:04:00:26.325 29596==    by 0x6694AA0: start_thread (in /lib64/libpthread-2.12.so)
==00:04:00:26.325 29596==    by 0x63E1AAC: clone (in /lib64/libc-2.12.so)
==00:04:00:26.325 29596==
==00:04:00:26.325 29596== LEAK SUMMARY:
==00:04:00:26.325 29596==    definitely lost: 328 bytes in 37 blocks
==00:04:00:26.325 29596==    indirectly lost: 2,400 bytes in 50 blocks
==00:04:00:26.325 29596==      possibly lost: 1,716,857 bytes in 659 blocks
==00:04:00:26.325 29596==    still reachable: 1,137,575,291 bytes in 1,930,986 blocks
==00:04:00:26.325 29596==         suppressed: 0 bytes in 0 blocks
# How to reproduce
# Checklist

Please provide the following information:
- [ ] librdkafka version (release number or git tag): 0.9 and master 
- [ ] Apache Kafka version: 0.10.0.0
- [ ] librdkafka client configuration:
- [ ] Operating system: Cent OS 6.5
- [ ] Using the legacy Consumer
- [ ] Using the high-level KafkaConsumer
- [ ] Provide logs (with `debug=..` as necessary) from librdkafka
- [ ] Provide broker log excerpts
- [ ] Critical issue

**Comment by edenhill** [comment]
What's your consumer config?
Is this reproducible using one of the example/ tools?
