### ISSUE TITLE
Producer to broker connection status (C++ interface)

### ISSUE THREAD

**Issue by SkyToGround** [edenhill/librdkafka#864]
I use the C++ interface to librdkafka in order to connect to a producer. It turns out that for some network errors (e.g. broker network is available but broker is down), it can take a long time to determine that this is the case. In many of the tests I did, with an event callback registered, no error event was produced for over 70 seconds after having initialized the library.

Is there a way to get the connection status in a similar way to what is available to the C version of the library (as mentioned in #211)? I have tried to find such functionality in the documentation without success.

**Comment by edenhill** [comment]
The stats api mentioned in that issue is available in C++ too as EVENT_STATS.

**Comment by SkyToGround** [comment]
Ah, so it is. Thank you.
Well the next guy encountering this problem will now have an easier time finding the solution. A very simplified version of the code I ended up using is the following:

    //Connect an event call back class instance
    cRes = conf->set("event_cb", &evt_cb, errstr);
    //Set the number of milliseconds between status events
    conf->set("statistics.interval.ms", "2000", errstr);

And then in the `event_cb()` member function of the event call back class I parse the data:

    ...
    switch (event.type()) {
        case RdKafka::Event::EVENT_STATS:
            ParseStatMsg(event.str());
            break;
        ...
    }
    ...
