### ISSUE TITLE
Unexpected jmx.kafka.BrokerTopicMetrics.BytesOutPerSec.gauge.Count

### ISSUE THREAD

**Issue by jquinn47** [edenhill/librdkafka#866]
# Description

We recently upgraded our kafka brokers to 0.10.  Our broker config:

We then began a roll out of our consumers, using librdkafka 0.9.1 (we use the high level consumer). The only new setting we turned on was `api.version.request = true`.  When we bounced in the new consumers, we saw a significant increase in the BytesOutPerSecond metric reported by the brokers via JMX.

Our write rate didn't change during the time:

![screen shot 2016-10-26 at 5 47 43 pm](https://cloud.githubusercontent.com/assets/5684681/19746403/5d33fed4-9ba4-11e6-9d20-1baf866223d8.png)

But after we bounced the consumers, we saw a significant increase in the bytes out metric:

![screen shot 2016-10-26 at 5 49 23 pm](https://cloud.githubusercontent.com/assets/5684681/19746472/98250600-9ba4-11e6-9734-a5d7de79cabb.png)

As a side effect, GC times spiked, (first young, then old), then the brokers ran out of memory while trying to keep up with our heavy write rate. This then caused the partitions to shuffle around, and problems get worse from there.

Our consumers were reporting this error message frequently: 

```
Local: Bad message format: broker3:9092/3: Receive failed: Invalid message size 106347363 (0..100000000): increase receive.message.max.bytes
```

Operation System:
RHEL 7, for both brokers and consumers

Broker Configuration

```
$> cat /etc/kafka/kafka.properties
broker.id=1
port=9092
num.partitions=8
num.network.threads=4
num.io.threads=12
log.dirs=/data/kafka/logs
log.retention.hours=24
log.segment.bytes=536870912
log.cleanup.interval.mins=1
zookeeper.connection.timeout.ms=1000000
socket.send.buffer.bytes=1048576
socket.receive.buffer.bytes=1048576
socket.request.max.bytes=104857600
kafka.metrics.polling.interval.secs=5
kafka.metrics.reporters=kafka.metrics.KafkaCSVMetricsReporter
kafka.csv.metrics.dir=/data/kafka/metrics
kafka.csv.metrics.reporter.enabled=false
replica.lag.max.messages=10000000
zookeeper.connect=(our hosts):2181/kafka
auto.create.topics.enable=false
advertised.host.name=(our public host)
num.recovery.threads.per.data.dir=10
inter.broker.protocol.version=0.10.0.0
log.message.format.version=0.10.0.0
auto.leader.rebalance.enable=true
```

librdkafka configuration:

```
metadata.broker.list = (our brokers)
group.id = (our group id)
compression.codec = snappy
batchTimeoutMs= 2000
statistics.interval.ms = 15000
queued.min.messages= 15000
api.version.request = true 
```
# How to reproduce

If we start our consumer without setting the 'api.version.request=true' parameter in librdkafka, we see the significant increase in our BytesOut rate, as reported by kafka brokers.

As I work with sensitive data, I'd rather not attach logs straight away, but if there is anything specific I can help with in answering a log question, I could attach relevant snippets.

**Comment by shanson7** [comment]
The particular message was `Local: Bad message format: broker3:9092/3: Receive failed: Invalid message size 106347363 (0..100000000): increase receive.message.max.bytes`.

**Comment by edenhill** [comment]
Did increasing receive.massage.max.bytes fix the issue?

**Comment by shanson7** [comment]
We didn't try that, as we thought it might be a red herring. We saw values as large 1GB for the purported "message size". We knew that the only thing we had changed was adding that `api.version.request = true` config item, so we undid that and it was all better. 

We were afraid that if the message format was bad (as the log line indicated) that we may not be getting the correct message size from the message itself. We wanted to avoid reading in 4 random bytes and trying to malloc the space.

**Comment by edenhill** [comment]
Which broker 0.10 release did you upgrade to?

**Comment by shanson7** [comment]
0.10.0.1

**Comment by edenhill** [comment]
How many partitions are you consuming?

**Comment by shanson7** [comment]
~350 across 6 instances

**Comment by edenhill** [comment]
whoop!

This is the doc for `receive.message.max.bytes`:
> Maximum receive message size. This is a safety precaution to avoid memory exhaustion in case of protocol hickups. The value should be at least fetch.message.max.bytes * number of partitions consumed from + messaging overhead (e.g. 200000 bytes). 
Default value: ~100Mb.

`fetch.message.max.bytes` defaults to 1M.

So if one of your consumers is assigned more than 100 partitions then the total fetch response size may exceed receive.message.max.bytes.

**Comment by shanson7** [comment]
Yep, we read that. We verified that number of partitions assigned to a single instance was below 100, and furthermore, we say reported "message sizes" as high as 2094351488 (about 2GB) so I don't think that this was as simple as mis-weighted partition assignment.

**Comment by edenhill** [comment]
Can you enable `debug=protocol,fetch`.
I want to know how many partitions are being fetched and what the returned FetchResponse size are.

**Comment by jquinn47** [comment]
I'll work on that now. Be back with results in a bit 👍

**Comment by jquinn47** [comment]
Sorry that took a bit longer. I had to mess around with our staging cluster a bit to get these tests ready to go. 

For some context, the task that I'm experimenting with is a kafka consumer meant to pull from multiple topics, translate payloads into a splunk protocol, then ship the contents over to a splunk HTTP endpoint for downstream ingestion. 

`normal.log` is created running our consumers with `api.version.request = false`. `problem.log` is with `api.version.request = true`.  

[kafka-tests.tar.gz](https://github.com/edenhill/librdkafka/files/556853/kafka-tests.tar.gz)

The staging cluster has a orders of magnitude less data, but it still exhibited the same spike in the bytes out rate as reported by kafka.

![screen shot 2016-10-27 at 3 53 11 pm](https://cloud.githubusercontent.com/assets/5684681/19782813/7fb23e9e-9c5d-11e6-8275-4666c96fa9f8.png)

The first little blip was when i bounced in with the api version request set to false. The huge spike was true.

**Comment by jquinn47** [comment]
Just wanted to ping this one. We only have conjecture on our end still, but our current guess is that as a side effect of api.version.request being enabled, a feature got turned on that caused the brokers to miscommunicate with the subscribers.

The brokers then send larger messages than the consumers are expecting, the consumers reject the message due to the size limits baked into the api, then immediately ask for more message they won't be able to read.

**Comment by edenhill** [comment]
I've looked at the logs and I regret to tell you that I'll need you to enable one more debug flag so that it prints the actual MesageSetSize of the received fetch.
Can you reproduce this with  `debug=protocol,topic,fetch,msg` ?

Thanks

**Comment by jquinn47** [comment]
No problem. Log file is quite a bit bigger. Had to cut it off for githubs upload limits, but the problems that start repeating towards the end of the file go on for another 400k lines. 


[problems.tar.gz](https://github.com/edenhill/librdkafka/files/567080/problems.tar.gz)

**Comment by edenhill** [comment]
Thanks!

What is the typical message size for the `logs` topic?

**Comment by edenhill** [comment]
And what's your `fetch.message.max.bytes` property set to?

**Comment by jquinn47** [comment]
Taking a snapshot, our average message size for `logs` is 12.5kB, (min 2kB, max 900kB). Max message size that the brokers will accept is 1MB.

Looks like we're using the defaults for `fetch.message.max.bytes property`.

**Comment by edenhill** [comment]
Let's look at log [78] which gets stuck at offset 23254370:
```
Fetch topic logs [78] at offset 23254370 (v2)
Topic logs [78] MessageSet size 174727, error "Success", MaxOffset 23254396, Ver 2/2
Enqueue 0 messages on logs [78] fetch queue (qlen 0, v2)
Topic logs [78]: Increasing max fetch bytes to 2097152
Fetch topic logs [78] at offset 23254370 (v2)
Topic logs [78] MessageSet size 174727, error "Success", MaxOffset 23254396, Ver 2/2
Enqueue 0 messages on logs [78] fetch queue (qlen 0, v2)
Topic logs [78]: Increasing max fetch bytes to 4194304
...
.. continues increasing to..
Topic logs [78]: Increasing max fetch bytes to 1073741824
... but still unable to continue
```

Logically, this would indicate that the message (or messageset batch) at that offset is larger than 1 gig, now practically that is most likely not the case.
Could you fire up kafkacat and try consuming that offset and print some info about it:
`kafkacat -b <broker> -C -t log -p 78 -o 23254370 -f '%t [%p] @ %o: %S 0 %K\n'` -c 100

**Comment by edenhill** [comment]
Oh right, you need to run kafkacat twice, once with -X api.version.request=true  and one without

**Comment by shanson7** [comment]
I built kafkacat with the 0.9.1 release branch of librdkafka and when setting `api.version.request=true` it exhibited problematic behavior (it did nothing). We noticed that the broker handling partition 78 immediately started sending 4x more "bytes out" than before. When running with `api.version.request=false` data flowed through kafkacat and our brokers hardly registered the extra load (only a single partition ingested).

```
C02R2018G8WP:kafkacat shanson7$ ./kafkacat -b broker:9092 -C -t logs -p 78 -o 23297000  -f '%t [%p] @ %o: %S + %K\n'  -X statistics.interval.ms=10000 -X api.version.request=true -X queued.min.messages=15000
<15 second pause without data>
^C
C02R2018G8WP:kafkacat shanson7$ ./kafkacat -b broker:9092 -C -t logs -p 78 -o 23297000  -f '%t [%p] @ %o: %S + %K\n'  -X statistics.interval.ms=10000 -X queued.min.messages=15000
logs [78] @ 23297000: 863 + -1
logs [78] @ 23297001: 1429 + -1
logs [78] @ 23297002: 1664 + -1
logs [78] @ 23297003: 757 + -1
logs [78] @ 23297004: 21953 + -1
logs [78] @ 23297005: 145543 + -1
logs [78] @ 23297006: 20855 + -1
logs [78] @ 23297007: 21905 + -1
logs [78] @ 23297008: 18272 + -1
```

Worth noting, kafkacat using the master branch of librdkafka worked fine with or without `api.version.request=true`.

**Comment by shanson7** [comment]
Might be fixed on master, but there are a lot of commits between 0.9.1 and current master.

**Comment by jquinn47** [comment]
We added a few extra options to the kafkacat test to remove any variables between our usage of the API and kafkacat's :)

**Comment by jquinn47** [comment]
Sorry for the accidental close.

**Comment by edenhill** [comment]
I thought you already tested this with master (the "Increasing max fetch bytes .. " printout was not available in 0.9.1).
Which master sha1 did you try this out on when you got the failures?

**Comment by jquinn47** [comment]
Git tag 0.9.1, 2213fb29f98a7a73f22da21ef85e0783f6fd67c4

**Comment by jquinn47** [comment]
Which was the most recent kafka

**Comment by jquinn47** [comment]
Damn it... those buttons are too close.

Just an addendum here, that was for the kafkacat tests. I'll check on our task's librdkafka versions now.

**Comment by jquinn47** [comment]
```$ git rev-parse HEAD
26448824be13f184555e653a967caad9328ca2be
```

**Comment by jquinn47** [comment]
I'd wager the issue is gone. Following up might useful, but only in the academic sense. My current plan is to build master, rebuild our task, and try to reproduce the problem. If its fixed I'd close this issue (for real this time).

**Comment by jquinn47** [comment]
Closing this for real this time. Rebuilding our task with the current master (39ba864f9d649e3888ec0c9ae4ef3fd73bae5ddb) fixes our problem. I'm not sure what the cause was.

Is there an official suggestion on if we should be able to pull from master regularly, or should we always wait for releases?

**Comment by edenhill** [comment]
So to summarize:
librdkafka 0.9.1 did not automatically increase the receive buffer size when it encountered a message too large to receive.
This in turn lead to requesting the same offset over and over again, the broker would respond, but the client wouldnt make any progress - this most likely explains the broker tx rate peaks.
master solves this by increasing the receive buffer (by doubling it for each attempt) up to about 1 gig.

It is not clear why you saw this issue on your outdated master (26448824be13f184555e653a967caad9328ca2be) but which had that fix in place, I've scanned the commit logs and I dont find anything relevant being changed after that commit.


Re what version to use:
you shouldy typically only use proper releases in production, the master branch is actively developed and it is hard to guarantee any sort of quality for a master snapshot.
The next formal release will be in about a week: 0.9.2, which includes this fix.

**Comment by jquinn47** [comment]
Excellent! We'll keep our eyes peeled for the release. Thanks for all of your help
