### ISSUE TITLE
rdkafka PHP consume cannot read

### ISSUE THREAD

**Issue by jogucc** [edenhill/librdkafka#879]
Description
===========
kafka version I use is kafka_2.10-0.9.0.1,
The producer code like this:
            $kafka = new RdKafka\Producer();
            $kafka->setLogLevel(LOG_DEBUG);
            $rst = $kafka->addBrokers("xxxx.xxxx.xxxx.xxxx:9092/testkafka");

            $topic = $kafka->newTopic("test_topic");
            $rst = $topic->produce(RD_KAFKA_PARTITION_UA, 0, "jo test11");

but the consumer can not get msg:

             $rk = new RdKafka\Consumer();
             $rk->addBrokers("xxxx.xxxx.xxxx.xxxx:9092/testkafka");
             $topic = $rk->newTopic("test_topic");
             $topic->consumeStart(0, RD_KAFKA_OFFSET_BEGINNING);

while (true) {
    $msg = $topic->consume(0,1000);
    var_dump($msg);
}

The $msg return is NULL. anybody know WHY?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you consume messages with another client? (such as kafkacat or kafka-console-consumer.sh)
Can your consumer consume messagse produced with another producer? (such as kafkacat or kafka-consule-producer.sh)

**Comment by abeelenj** [comment]
I've got the same issue. I am able to consume via kafka-console-consumer.sh. Messages produced by kafka-consule-producer.sh wont be consumed by my php code, but are being consumed by kafka-console-consumer.sh.

`$rk = new RdKafka\Consumer();
  $rk->setLogLevel(LOG_DEBUG);
  $rk->addBrokers("127.0.0.1");

  $topic = $rk->newTopic("test");
  $topic->consumeStart(0, RD_KAFKA_OFFSET_BEGINNING);

  while (true) {
      $msg = $topic->consume(0, 10);
      if($msg==NULL){
        continue;
      }
      if ($msg->err) {
          echo $msg->errstr(), "\n";
          break;
      } else {
          return json_encode(['handled' => $msg->payload]);
          break;
      }
  }`

**Comment by edenhill** [comment]
Enable `fetch,topic` debugging (set `debug` config property to `fetch,topic`) to figure out what is going on.

**Comment by abeelenj** [comment]
```
%7|1510918663.069|TOPIC|testkafkaubes#consumer-1| [thrd:app]: New local topic: test
%7|1510918663.069|TOPPARNEW|testkafkaubes#consumer-1| [thrd:app]: NEW test [-1] 0x56104b0fac50 (at rd_kafka_topic_new0:282)
%7|1510918663.069|START|testkafkaubes#consumer-1| [thrd:app]: Start consuming partition 0
%7|1510918663.069|TOPPARNEW|testkafkaubes#consumer-1| [thrd:app]: NEW test [0] 0x56104aef3660 (at rd_kafka_toppar_desired_add:566)
%7|1510918663.069|DESIRED|testkafkaubes#consumer-1| [thrd:app]: test [0]: adding to DESIRED list
%7|1510918663.069|DESP|testkafkaubes#consumer-1| [thrd:app]: Adding desired topic test [0]
%7|1510918663.069|BARRIER|testkafkaubes#consumer-1| [thrd:app]: test [0]: rd_kafka_toppar_op_fetch_start:2056: new version barrier v2
%7|1510918663.069|CONSUMER|testkafkaubes#consumer-1| [thrd:app]: Start consuming test [0] at offset BEGINNING (v2)
%7|1510918663.069|OP|testkafkaubes#consumer-1| [thrd:main]: test [0] received op FETCH_START (v2) in fetch-state none (opv1)
%7|1510918663.069|FETCH|testkafkaubes#consumer-1| [thrd:main]: Start fetch for test [0] in state none at offset BEGINNING (v2)
%7|1510918663.069|PARTSTATE|testkafkaubes#consumer-1| [thrd:main]: Partition test [0] changed fetch state none -> offset-query
%7|1510918663.069|OFFSET|testkafkaubes#consumer-1| [thrd:main]: test [0]: offset reset (at offset BEGINNING) to BEGINNING: update: Success
%7|1510918663.069|OFFSET|testkafkaubes#consumer-1| [thrd:main]: test [0]: no current leader for partition, starting offset query timer for offset BEGINNING
%7|1510918663.569|OFFSET|testkafkaubes#consumer-1| [thrd:main]: Topic test [0]: timed offset query for BEGINNING in state offset-query
%7|1510918663.569|OFFSET|testkafkaubes#consumer-1| [thrd:main]: test [0]: no current leader for partition, starting offset query timer for offset BEGINNING
%7|1510918664.069|NOINFO|testkafkaubes#consumer-1| [thrd:main]: Topic test partition count is zero: should refresh metadata
%7|1510918664.069|OFFSET|testkafkaubes#consumer-1| [thrd:main]: Topic test [0]: timed offset query for BEGINNING in state offset-query
%7|1510918664.069|OFFSET|testkafkaubes#consumer-1| [thrd:main]: test [0]: no current leader for partition, starting offset query timer for offset BEGINNING
%3|1510918664.072|FAIL|testkafkaubes#consumer-1| [thrd:127.0.0.1:2181/bootstrap]: 127.0.0.1:2181/bootstrap: Receive failed: Disconnected
%3|1510918664.072|ERROR|testkafkaubes#consumer-1| [thrd:127.0.0.1:2181/bootstrap]: 127.0.0.1:2181/bootstrap: Receive failed: Disconnected
%7|1510918664.074|STATE|testkafkaubes#consumer-1| [thrd:main]: Topic test changed state unknown -> exists
%7|1510918664.074|PARTCNT|testkafkaubes#consumer-1| [thrd:main]: Topic test partition count changed from 0 to 1
%7|1510918664.074|METADATA|testkafkaubes#consumer-1| [thrd:main]:   Topic test partition 0 Leader 0
%7|1510918664.074|BRKDELGT|testkafkaubes#consumer-1| [thrd:main]: test [0]: delegate to broker api.localhost:9092/0 (rktp 0x56104aef3660, term 0, ref 2, remove 0)
%7|1510918664.074|BRKDELGT|testkafkaubes#consumer-1| [thrd:main]: test [0]: broker api.localhost:9092/0 is now leader for partition with 0 messages (0 bytes) queued
%7|1510918664.074|BRKMIGR|testkafkaubes#consumer-1| [thrd:main]: Migrating topic test [0] 0x56104aef3660 from (none) to api.localhost:9092/0 (sending PARTITION_JOIN to api.localhost:9092/0)
%7|1510918664.074|METADATA|testkafkaubes#consumer-1| [thrd:main]: localhost:9092/bootstrap: 1/1 requested topic(s) seen in metadata
%7|1510918664.075|TOPBRK|testkafkaubes#consumer-1| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Topic test [0]: joining broker (rktp 0x56104aef3660)
%7|1510918664.076|METADATA|testkafkaubes#consumer-1| [thrd:main]:   Topic test partition 0 Leader 0
%7|1510918664.076|METADATA|testkafkaubes#consumer-1| [thrd:main]: localhost:9092/bootstrap: 1/1 requested topic(s) seen in metadata
%7|1510918664.089|DESP|testkafkaubes#consumer-1| [thrd:app]: Removing (un)desired topic test [0]
```

**Comment by edenhill** [comment]
Set api.version.request to false on the client config

**Comment by abeelenj** [comment]
Thanks for your quick response :) It gets me one step further, still $msg=NULL

Log shows (many more lines like these):
```
%7|1510920786.174|FETCH|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch topic test [0] at offset 0 (v2)
%7|1510920786.174|FETCH|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch 1/1/1 toppar(s)
%3|1510920786.174|PROTOERR|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Protocol parse failure at 8/1993 (rd_kafka_fetch_reply_handle:2513) (incorrect broker.version.fallback?)
%3|1510920786.174|PROTOERR|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: expected 7298525 bytes > 1985 remaining bytes
%7|1510920786.174|BACKOFF|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch backoff for 500ms: Local: Bad message format
%7|1510920786.174|FETCH|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch topic test [0] at offset 0 (v2)
%7|1510920786.174|FETCH|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch 1/1/1 toppar(s)
%3|1510920786.174|PROTOERR|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Protocol parse failure at 8/1993 (rd_kafka_fetch_reply_handle:2513) (incorrect broker.version.fallback?)
%3|1510920786.174|PROTOERR|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: expected 7298525 bytes > 1985 remaining bytes
%7|1510920786.174|BACKOFF|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch backoff for 500ms: Local: Bad message format
%7|1510920786.174|FETCH|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch topic test [0] at offset 0 (v2)
%7|1510920786.174|FETCH|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch 1/1/1 toppar(s)
%3|1510920786.177|PROTOERR|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Protocol parse failure at 8/1993 (rd_kafka_fetch_reply_handle:2513) (incorrect broker.version.fallback?)
%3|1510920786.177|PROTOERR|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: expected 7298525 bytes > 1985 remaining bytes
%7|1510920786.177|BACKOFF|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch backoff for 500ms: Local: Bad message format
%7|1510920786.177|FETCH|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch topic test [0] at offset 0 (v2)
%7|1510920786.177|FETCH|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch 1/1/1 toppar(s)
%3|1510920786.178|PROTOERR|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Protocol parse failure at 8/1993 (rd_kafka_fetch_reply_handle:2513) (incorrect broker.version.fallback?)
%3|1510920786.178|PROTOERR|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: expected 7298525 bytes > 1985 remaining bytes
%7|1510920786.178|BACKOFF|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch backoff for 500ms: Local: Bad message format
%7|1510920786.178|FETCH|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch topic test [0] at offset 0 (v2)
%7|1510920786.178|FETCH|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch 1/1/1 toppar(s)
%3|1510920786.178|PROTOERR|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Protocol parse failure at 8/1993 (rd_kafka_fetch_reply_handle:2513) (incorrect broker.version.fallback?)
%3|1510920786.178|PROTOERR|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: expected 7298525 bytes > 1985 remaining bytes
%7|1510920786.178|BACKOFF|tkubes111#consumer-6| [thrd:api.localhost:9092/0]: api.localhost:9092/0: Fetch backoff for 500ms: Local: Bad message format

```

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by abeelenj** [comment]
Thanks, that helped a bunch!

**Comment by cobak78** [comment]
@abeelenj how do you find broker version? it's the same of kafka?

**Comment by edenhill** [comment]
@cobak78 yes

**Comment by dhanashreeshetty19** [comment]
Hi I have a Kafka on another server and PHP consumer on another server. Producer code is written in Python while consumer in PHP. But when I try to extract Message Payload (i.e. Consume) from any topic then  system keeps executing..i.e. more than 20 minutes. Then I forcefully stopped the execution. Please find the code below:

                                $conf = new \RdKafka\Conf();

                                // Set the group id. This is required when storing offsets on the broker
                                $conf->set('group.id', 'tbfc_alarms_staging');

                                $rk = new \RdKafka\Consumer($conf);

                                $rk->addBrokers("10.136.104.192");

                                 $topicConf = new \RdKafka\TopicConf();
                                $topicConf->set('auto.commit.interval.ms', 100);
                                $topicConf->set('auto.offset.reset', 'latest'); // earliest
                                $topic = $rk->newTopic("TBFC_ALARMS_STAGING", $topicConf);
                                $topic->consumeStart(0, RD_KAFKA_OFFSET_STORED);

                                while (true) {

                                                $message = $topic->consume(0, 120*10000);

                                                if (null === $message) {

                                                                continue;

                                                } elseif ($message->err) {

                                                    // echo 'Error: ';
                                                    // echo $message->errstr(), "\n";
                                                                break;
                                                } else {
                                                    $trapDetails = $message->payload;
                                                    print_r($trapDetails);
                                                    $topologyGenericTicketsObj->processGenericTicket($trapDetails);
                                                    echo 'Done';
                                                }
                                }

Please can any one help as when same topic is used by another developer in another code. Then they receive the output.

**Comment by edenhill** [comment]
Set the `debug` config property to `cgrp,fetch` to see what is going on.

**Comment by dhanashreeshetty19** [comment]
Thanks edenhill. 

As I'm new to Kafka with PHP, can you please help me how to set debug property. Are you asking me to do it at library or at coding level.

**Comment by edenhill** [comment]
Yep, that looks correct
