### ISSUE TITLE
want : avro message without schema

### ISSUE THREAD

**Issue by elhindu** [edenhill/librdkafka#881]
Description
===========
Trying to create an avro message without the schema in the header to reduce the network traffic.

How to reproduce
================
I have been using the sample app that is provided to create a record with a simple schema.  It all results in the schema being streamed out to a kafka server.  How can I create it so that when I serialize it, the schema doesn't get attached?

Checklist
=========
Please provide the following information:

 - [ ] librdkafka latest pulled from github under edenhill/librdkafka 
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system: ubuntu 14/16
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka has no notion of schema, all payload is considered opaque and you may send whatever you want without any alteration by librdkafka.

If you want to send avro with librdkafka without attaching the schema we made libserdes that integrates with Confluent's schema-registry and let's you do just that.
See here:
https://github.com/confluentinc/libserdes

Example how to integrate with librdkafka:
https://github.com/confluentinc/libserdes/blob/master/examples/kafka-serdes-avro-console-producer.cpp
