### ISSUE TITLE
minor bug in RdKafka::Conf::get() string update of parameter value

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#882]
Description
===========
RdKafka::Conf::get() bug
When I use **get()** on my **conf** to get back my consumer group name (with "group.id" the std::string object I get back is my consumer group name appended by the '\000' char
si size of the string is also false because it is increased by 1.

I guess this issue happens because in 
```
Conf::ConfResult get(const std::string &name, std::string &value) const
```
the code does a
``value.resize(size);``
then passes the string internal buffer (value.c_str() ) to be updated in line 403
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp_int.h#L403

On this debugger window you see kfkConsumerGroup that I use to set my conf "group.ip". Its size is 20
then I do a conf.get with consGroup and its size is 21.
<a href='http://pix.toile-libre.org/?img=1478082868.jpg'><img src='http://pix.toile-libre.org/upload/img/1478082868.jpg' /></a>

consGroup.c_str()[20] is then displayed on stdout and my logfiles causing logfile to open with a weird asian char encoding if open with gedit : 
<a href='http://pix.toile-libre.org/?img=1478083616.jpg'><img src='http://pix.toile-libre.org/upload/img/1478083616.jpg' /></a>

viewed with nano : 
<a href='http://pix.toile-libre.org/?img=1478083513.jpg'><img src='http://pix.toile-libre.org/upload/img/1478083513.jpg' /></a>

How to reproduce
================

create a Conf : do a set(), then do a get()

Checklist
=========
Please provide the following information:

 - [48099dbc24929c195dbeb6cfe75cdbe00b4c3941 ] librdkafka version (release number or git tag):
 - [ 0.10] Apache Kafka version: 
 - [ cpp version] librdkafka client configuration:
 - [ Ubuntu 16.04] Operating system:
 - [ ] Using the legacy Consumer
 - [ x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Thanks.
Can you file a PR to fix the issue?

**Comment by vin-d** [comment]
#884

**Comment by vin-d** [comment]
# #885
