### ISSUE TITLE
FreeBSD: undefined reference to `WIFSIGNALED'

### ISSUE THREAD

**Issue by eserte** [edenhill/librdkafka#886]
Description
===========

Linking on a FreeBSD 10.1 system fails. After doing `./configure && gmake`:
```
clang -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -I/usr/local/include   -I/usr/local/include   -I/usr/local/include   -I../src rdkafka_example.c -o rdkafka_example  \
        ../src/librdkafka.a -lpthread -lz   -L/usr/local/lib -lcrypto   -L/usr/local/lib -lssl   -L/usr/local/lib -lsasl2   -lrt
../src/librdkafka.a(rdkafka_sasl.o): In function `rd_kafka_sasl_kinit_refresh':
/tmp/librdkafka/src/rdkafka_sasl.c:296: undefined reference to `WIFSIGNALED'
/tmp/librdkafka/src/rdkafka_sasl.c:297: undefined reference to `WTERMSIG'
/tmp/librdkafka/src/rdkafka_sasl.c:302: undefined reference to `WIFEXITED'
/tmp/librdkafka/src/rdkafka_sasl.c:302: undefined reference to `WEXITSTATUS'
/tmp/librdkafka/src/rdkafka_sasl.c:303: undefined reference to `WEXITSTATUS'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Adding `#include <sys/wait.h>` to src/rdkafka_sasl.c and tests/test.c helps to finish the compilation.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 39ba864f9d649e3888ec0c9ae4ef3fd73bae5ddb
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system: FreeBSD 10.1
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
now on master
