### ISSUE TITLE
_UNKNOWN_TOPIC on produce during broker restart

### ISSUE THREAD

**Issue by MaximGurschi** [edenhill/librdkafka#889]
Hi Eden,

I have a 3 broker cluster. My restart policy for the machines is 1+2. Basically if i need to apply updates to the host i first apply changes and restart Broker1 and then Broker2 and Broker3 together.

Now obviously to do it properly i need to cycle the hosts one by one.

In any case, is it expected to get an error with "_UNKNOWN_TOPIC" when i call produce while the machines are restarted?

**Comment by edenhill** [comment]
Is your topic properly replicated between the two brokers?
What broker version?
What librdkafka version?

**Comment by MaximGurschi** [comment]
I've setup replication factor 3.
The broker version is: 0.9.0.1.
librdkafka version: 0.9.1.

**Comment by MaximGurschi** [comment]
This is the error on the broker:
ERROR [KafkaApi-1] error when handling request Name: TopicMetadataRequest; Version: 0; CorrelationId: 12590; ClientId: rdkafka; Topics: some_topic (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 2
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:77)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:236)
	at kafka.server.KafkaApis$$anonfun$20.apply(KafkaApis.scala:572)
	at kafka.server.KafkaApis$$anonfun$20.apply(KafkaApis.scala:555)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Set$Set4.foreach(Set.scala:181)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:555)
	at kafka.server.KafkaApis.handleTopicMetadataRequest(KafkaApis.scala:624)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:71)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Unknown Source)

**Comment by edenhill** [comment]
> kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 2

This should probably be treated as a temporary error in librdkafka and make it accept messages and retry them for `retries` and `message.timeout.ms` until the topic becomes available.


If this is easily reproducible it would be nice to get a reproduction log with debug=metadata,topic enabled.

**Comment by MaximGurschi** [comment]
I think this is the same issue from this SO post.
http://stackoverflow.com/questions/31547644/all-messages-in-out-queue-failed-to-be-delivered-to-broker-when-kafka-brokers-re

Will try to reproduce. In the meantime - if i detect this error, should i just produce the same message again?

**Comment by edenhill** [comment]
Yeah, that seems like a reasonable workaround.

**Comment by MaximGurschi** [comment]
Oh, i found the place in the code where this error is treated as terminal. If you decide to alter the behaviour on this error do you think this will be in the next release (0.9.2)?

**Comment by edenhill** [comment]
It will not make 0.9.2 unfortunately.

**Comment by MaximGurschi** [comment]
For the **message.timeout.ms** setting - is that an upper bound on how long the message can linger in the internal produce queue?

Say **retries** is 2 and it takes 5 seconds for librdkafka to detect that the message cannot be delivered, does that then mean that any value of **message.timeout.ms** greater than 10 (2*5) seconds useless?

**Comment by edenhill** [comment]
Yes, that is the upper bound.

librdkafka will only attempt a retry if there is an active leader broker for a partition, in your case where the partition is offline due to insufficient replicas there will not be a leader and no retries will take place.
So in this case the timeout is bound by message.timeout.ms rather than retries.

**Comment by MaximGurschi** [comment]
Ok makes sense, thanks Eden.

So if i wrap the produce retry loop into my own code, must i query metadata to know that it makes sense to retry or is it better to just sleep and retry?

Sketch of code:
1.Produce fails with _UNKNOWN_TOPIC.
2.Query topic metadata until there are enough replicas. (Or just sleep 1 minute).
3.Try produce again.

**Comment by edenhill** [comment]
I suggest you just sleep and retry, and you could do so rather aggressively.

**Comment by MaximGurschi** [comment]
Cool thank you. Would be great if you will actually make it part of librdkafka eventually.

I had no time today to look at Kerberos but plan to first thing tomorrow.
