### ISSUE TITLE
Message failed, callback function didn't called, just blocked 

### ISSUE THREAD

**Issue by chrislee87** [edenhill/librdkafka#892]
Description
===========
When failed to connect to kafka, i want the producer write data into file. So i register the callback,
`rd_kafka_conf_set_dr_msg_cb(m_conf, msgDelivered2);`
In msgDelivered2, messages failed would write to file. Then i kill the kafka cluster.
I found for any connection, the last 16 messages will not be writen to file, other messages successfully write to file.
Is the producer queue buffering the last buffered messages for ever?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
If the broker goes down the queued messages will linger for `message.timeout.ms` (default 5 minutes).
Are you waiting that long?

What is your producer config?

What does your librdkafka termination code look like?
See this:
https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence

**Comment by chrislee87** [comment]
I use global and topic configurations as below:
`compression.codec = snappy
message.send.max.retries = 2
batch.num.messages = 1000
queue.buffering.max.messages = 500000
queue.buffering.max.ms = 1000

produce.offset.report = false
message.timeout.ms = 15000
request.required.acks = 1`

For each connection, i create a rd_kafka_topic_t, functions called as bellow:
`rd_kafka_topic_new(...)
rd_kafka_produce_batch(...)
rd_kafka_poll(m_rk, 0)
rd_kafka_topic_destroy(rkt)`
rkt is the rd_kafka_topic_t for each connection, m_rk is the global rd_kafka_t.

I have a client which send one message per second, i use it to send 60 messages(the kafka cluester is killed), the 1st message output to disk after 15 seconds(as message.timeout.ms), then the 2ed till the 44th, after that i waiting for several minitues, the remaining 16 messages didn't output. 
I opened the client again for 1 minute, the remaining 16 messages output at the same time imidiately, and 44 new messages, however the last 16 messages won't output for ever unless i start client and new messages come in.  
So it seams the last 16 messages buffered in the queue for ever and callback function never called, unless new messages come in.
