### ISSUE TITLE
flow excepition 

### ISSUE THREAD

**Issue by wangyanshun** [edenhill/librdkafka#893]
Description
===========
When I add a new broker into the kafka cluster, the kafka cluster will send some data to client,  about   increasing 200MB per operation.

How to reproduce
================

Add a new broker into kafka cluster.

Checklist
=========
Please provide the following information:

 - [0.8 ] librdkafka version (release number or git tag):
 - [ 0.8.2 and 0.10.0] Apache Kafka version: 
 - [default ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Not much to go on.

What kind of client?
How do you measure the data?
What is an operation?
etc..

**Comment by wangyanshun** [comment]
My server plays the client role, which is developed used librdkafka, only use producer function.

The operation is that to add a new host into the kafka cluster.

My company has a monitor system, I found the phenomenon (about increasing 200MB per operation) by it.

The kafka cluster has 48 hosts.
Every client will create 755 connections with the kafka cluster, I have 26 client hosts.

enough ?

**Comment by edenhill** [comment]
If you add a new broker to your cluster could the increase in bandwidth be explained by the broker being added to the replica set for a given set of topics?

**Comment by wangyanshun** [comment]
In fact ，I catch the package during the librdkafka and the kafka cluster server, I found the package's details are the metadata.
If like you said, I think it will be cost some small time and finally disappear, but it the phenomenon is keeping.

Another question, I found max topic count is 10000 and now I already create more than 9000 topics.

**Comment by edenhill** [comment]
Yes, you can increase the limit, it is just an arbitrary picked limit since librdkafka internals were not designed for that number of topics (e.g., linear searches).
There'll probably be improvements to this area soon.
