### ISSUE TITLE
How to detect if kafka is alive

### ISSUE THREAD

**Issue by chrislee87** [edenhill/librdkafka#894]
Description
===========
Producer writes messages to kafka, when kafka is down, those mssages write to files.
Another thread load data from files and try to send them to kafka again.
Is there any way to detect whether kafka is alive or down? I can only detect messages send fail from callbacks? Right now, the code load file, send to kafka fail and write to file again and again. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There is currently no "I'm Up again" notification available, but this issue tracks that feature request: #137

**Comment by asharma339** [comment]
You may call `rd_kafka_metadata()`,which returns RD_KAFKA_RESP_ERR__TRANSPORT if broker is down. Is there anything wrong with that approach?
