### ISSUE TITLE
0.9.2 reports as 0.9.2-RC1

### ISSUE THREAD

**Issue by remicollet** [edenhill/librdkafka#895]
Because of

#define RD_KAFKA_VERSION  0x000902c9

Which sould be 0x000902ff

**Comment by edenhill** [comment]
erghf, I wonder if I could fix that and move the tag. Would I get away with that?

**Comment by remicollet** [comment]
Moving the tag... is... a bad practice... (but could be acceptable when done "very shortly" after the initial tag).

Best practice is to bump the version to 0.9.3

**Comment by edenhill** [comment]
The release hasn't been made formally public yet, so I'll cheat this time and move the tag, dont tell anyone.

**Comment by edenhill** [comment]
Fixed in 25f44213ddf91f3c0413837b2a815097a1f34521 and tag moved
