### ISSUE TITLE
No such configuration property: security.protocol

### ISSUE THREAD

**Issue by llinsky** [edenhill/librdkafka#896]
Description
===========

"No such configuration property" issue with librdkafka C++:
```
    // kafka global configuration
    string err;
    rd_conf = RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL);

    // create handle to topic
    rd_topic_conf = RdKafka::Conf::create(RdKafka::Conf::CONF_TOPIC);

    // apply the user-defined settings to kafka
    map<string,string>::iterator i;
    for (i = kafka_conf.begin(); i != kafka_conf.end(); ++i) {
        string key = i->first;
        string val = i->second;

       printf("Attempting to set '%s'='%s'", key.c_str(), val.c_str());

        // apply setting to kafka
        if (RdKafka::Conf::CONF_OK == rd_topic_conf->set(key, val, err)) {
            continue;
        }
        else if (RdKafka::Conf::CONF_OK != rd_conf->set(key, val, err))
        {
          printf("error: Failed to set conf or topic conf '%s'='%s': %s", key.c_str(), \
            val.c_str(), err.c_str());
          return false;
        }
    }
```

My kafka_conf settings, pre-loaded:
	"metadata.broker.list" = "localhost:9092",
        "security.protocol" = "ssl",
        "ssl.certificate.location" = "/var/private/ssl/cert-signed",

Output:
Attempting to set 'metadata.broker.list'='localhost:9092'    <<no error>>
Attempting to set 'security.protocol'='ssl'
error: Failed to set conf or topic conf 'security.protocol'='ssl': No such configuration property: "security.protocol"

ENABLE_SSL=1 in my config.h.
Regardless, in the code source (rdkafka_conf.c), security.protocol should be defined as a global property regardless of build settings.

How to reproduce
================

Take the above code. I thought this was a rd_conf vs rd_topic_conf issue, but I think my above code should be checking both. I would expect this output error string to be impossible: `No such configuration property: "security.protocol"`

Let me know if there is something I'm doing wrong

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): Git tag: 686c404
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [x] Operating system:  Centos 6 (Linux 2.6.32)
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Is it possible that your application picks up an older librdkafka library from somewhere?
You can try printing RdKafka::version_str()

**Comment by llinsky** [comment]
Output of printf("Version: %s",RdKafka::version_str().c_str()):

Version: 0.8.6

**Comment by edenhill** [comment]
There you go, that's a really old library. It should report 0.9.xx.. something for the git sha you specified.

I'm guessing you have a library installed in /usr/lib (through RPM).
Either remove the RPM, or set LD_LIBRARY_PATH=new/path/lib

**Comment by llinsky** [comment]
I will try that, thank you for the info.

**Comment by cmtholm** [comment]
Clarifying on this, so versions before 0.9.xx will not have security.protocol as a config property?

**Comment by edenhill** [comment]
Right, OpenSSL and SASL support was introduced in 0.9 which was released almost 2 years ago.
The latest release is 0.11.0.
