### ISSUE TITLE
rdkafka_example_cpp can not comsue msg from kafka servers

### ISSUE THREAD

**Issue by robertbee** [edenhill/librdkafka#897]
Description
===========
rdkafka_example_cpp can not comsue msg from kafka servers

How to reproduce
================
create kakfa topic as:
cd /opt/kafka/bin
./kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 3 --partitions 1 --topic bee

I download maxwell maxwell-1.3.0.tar.gz at site
http://maxwells-daemon.io/

run it as:
SZX1000014463:/opt/maxwell # ./bin/maxwell --user='root' --password='Changeme_123' --host='10.64.126.175' --init_position=mysql-bin.000003:1638 --producer=kafka --kafka.bootstrap.servers=10.93.166.152:9092 --kafka_topic=bee

I generated a kafka msg by using sql:
insert into t_vertex (id1,type1,name1,C1,C2,C3,C4) values (1, 1, '1','1','1',1,1);

also can check it as:
SZX1000058402:/opt/kafka/bin # ./kafka-console-consumer.sh --zookeeper 10.93.166.152:2181 --from-beginning --topic bee
........
{"database":"bee","table":"t_vertex","type":"insert","ts":1478675127,"xid":466,"commit":true,"data":{"id1":1,"type1":1,"name1":"1","C1":"1","C2":"1","C3":1,"C4":1}}

run rdkafka_example_cpp got error. the details are:
SZX1000058401:/opt/bee/kafka/librdkafka-master/examples # ./rdkafka_example_cpp -C -t bee -p 0 -b 10.93.166.152:9092 -d all
LOG-7-BROKER: 10.93.166.152:9092/bootstrap: Added new broker with NodeId -1
LOG-7-BRKMAIN: :0/internal: Enter main broker thread
% Created consumer rdkafka#consumer-1
LOG-7-STATE: :0/internal: Broker changed state INIT -> UP
LOG-7-BROADCAST: Broadcasting state change
LOG-7-BRKMAIN: 10.93.166.152:9092/bootstrap: Enter main broker thread
LOG-7-TOPIC: New local topic: bee
LOG-7-CONNECT: 10.93.166.152:9092/bootstrap: broker in state INIT connecting
LOG-7-START: Start consuming partition 0
LOG-7-DESP: Adding desired topic bee [0]
LOG-7-BARRIER: bee [0]: rd_kafka_toppar_op_fetch_start:1860: new version barrier v2
LOG-7-CONSUMER: Start consuming bee [0] at offset BEGINNING (v2)
LOG-7-CONNECT: 10.93.166.152:9092/bootstrap: Connecting to ipv4#10.93.166.152:9092 (plaintext) with socket 3
LOG-7-OP: bee [0] received op FETCH_START (v2) in fetch-state none
LOG-7-FETCH: Start fetch for bee [0] in state none at offset BEGINNING (v2)
LOG-7-PARTSTATE: Partition bee [0] changed fetch state none -> offset-query
LOG-7-OFFSET: bee [0]: offset reset (at offset BEGINNING) to BEGINNING: update: Success
LOG-7-OFFSET: bee [0]: no current leader for partition, starting offset query timer for offset BEGINNING
LOG-7-STATE: 10.93.166.152:9092/bootstrap: Broker changed state INIT -> CONNECT
LOG-7-BROADCAST: Broadcasting state change
LOG-7-CONNECT: 10.93.166.152:9092/bootstrap: Connected to ipv4#10.93.166.152:9092
LOG-7-CONNECTED: 10.93.166.152:9092/bootstrap: Connected (#1)
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap: Using (configuration fallback) 0.9.0 protocol features
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature MsgVer1: Produce (2..2) NOT supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature MsgVer1: Fetch (2..2) NOT supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap: Disabling feature MsgVer1
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature ApiVersion: ApiVersion (0..0) NOT supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap: Disabling feature ApiVersion
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature BrokerGroupCoordinator: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap: Enabling feature BrokerGroupCoordinator
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature BrokerBalancedConsumer: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature BrokerBalancedConsumer: OffsetCommit (1..2) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature BrokerBalancedConsumer: OffsetFetch (1..1) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature BrokerBalancedConsumer: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature BrokerBalancedConsumer: SyncGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature BrokerBalancedConsumer: Heartbeat (0..0) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature BrokerBalancedConsumer: LeaveGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap: Enabling feature BrokerBalancedConsumer
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature ThrottleTime: Produce (1..2) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature ThrottleTime: Fetch (1..2) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap: Enabling feature ThrottleTime
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature Sasl: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap: Enabling feature Sasl
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature SaslHandshake: SaslHandshake (0..0) NOT supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap: Disabling feature SaslHandshake
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap:  Feature LZ4: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: 10.93.166.152:9092/bootstrap: Enabling feature LZ4
LOG-7-FEATURE: 10.93.166.152:9092/bootstrap: Updated enabled protocol features to BrokerBalancedConsumer,ThrottleTime,Sasl,BrokerGroupCoordinator,LZ4
LOG-7-STATE: 10.93.166.152:9092/bootstrap: Broker changed state CONNECT -> UP
LOG-7-BROADCAST: Broadcasting state change
LOG-7-METADATA: 10.93.166.152:9092/bootstrap: Request metadata for locally known topics: connected
LOG-7-METADATA: 10.93.166.152:9092/bootstrap: Request metadata for locally known topics: connected
LOG-7-SEND: 10.93.166.152:9092/bootstrap: Sent MetadataRequest (v0, 30 bytes @ 0, CorrId 1)
LOG-7-RECV: 10.93.166.152:9092/bootstrap: Received MetadataResponse (v0, 130 bytes, CorrId 1, rtt 10.14ms)
LOG-7-METADATA: 10.93.166.152:9092/bootstrap: ===== Received metadata =====
LOG-7-METADATA: 10.93.166.152:9092/bootstrap: 3 brokers, 1 topics
LOG-7-METADATA: 10.93.166.152:9092/bootstrap:   Broker #0/3: 10.93.159.109:9092 NodeId 2
LOG-7-BROKER: 10.93.159.109:9092/2: Added new broker with NodeId 2
LOG-7-METADATA: 10.93.166.152:9092/bootstrap:   Broker #1/3: 10.93.190.155:9092 NodeId 1
LOG-7-BRKMAIN: 10.93.159.109:9092/2: Enter main broker thread
LOG-7-CONNECT: 10.93.159.109:9092/2: broker in state INIT connecting
LOG-7-BROKER: 10.93.190.155:9092/1: Added new broker with NodeId 1
LOG-7-METADATA: 10.93.166.152:9092/bootstrap:   Broker #2/3: 10.93.166.152:9092 NodeId 0
LOG-7-METADATA: 10.93.166.152:9092/bootstrap:   Topic #0/1: bee with 1 partitions
LOG-7-STATE: Topic bee changed state unknown -> exists
LOG-7-BRKMAIN: 10.93.190.155:9092/1: Enter main broker thread
LOG-7-CONNECT: 10.93.190.155:9092/1: broker in state INIT connecting
LOG-7-UPDATE: 10.93.166.152:9092/bootstrap: NodeId changed from -1 to 0
LOG-7-UPDATE: 10.93.166.152:9092/0: Name changed from 10.93.166.152:9092/bootstrap to 10.93.166.152:9092/0
LOG-7-METADATA: 10.93.166.152:9092/0: Request metadata for locally known topics: leader query
LOG-7-METADATA: 10.93.166.152:9092/0: Request metadata for locally known topics: leader query
LOG-7-STATE: 10.93.166.152:9092/0: Broker changed state UP -> UPDATE
LOG-7-BROADCAST: Broadcasting state change
LOG-7-CONNECT: 10.93.190.155:9092/1: Connecting to ipv4#10.93.190.155:9092 (plaintext) with socket 5
LOG-7-CONNECT: 10.93.159.109:9092/2: Connecting to ipv4#10.93.159.109:9092 (plaintext) with socket 4
LOG-7-STATE: 10.93.190.155:9092/1: Broker changed state INIT -> CONNECT
LOG-7-BROADCAST: Broadcasting state change
LOG-7-PARTCNT: Topic bee partition count changed from 0 to 1
LOG-7-STATE: 10.93.159.109:9092/2: Broker changed state INIT -> CONNECT
LOG-7-BROADCAST: Broadcasting state change
LOG-7-METADATA: 10.93.166.152:9092/0:   Topic bee partition 0 Leader 0
LOG-7-BRKDELGT: Broker :0/internal is now leader for topic bee [0] with 0 messages (0 bytes) queued
LOG-7-BRKMIGR: Migrating topic bee [0] from (none) to :0/internal
LOG-7-TOPBRK: :0/internal: Topic bee [0]: joining broker
LOG-7-BROADCAST: Broadcasting state change
LOG-7-SEND: 10.93.166.152:9092/0: Sent MetadataRequest (v0, 30 bytes @ 0, CorrId 2)
LOG-7-STATE: 10.93.166.152:9092/0: Broker changed state UPDATE -> UP
LOG-7-BROADCAST: Broadcasting state change
LOG-7-CONNECT: 10.93.159.109:9092/2: Connected to ipv4#10.93.159.109:9092
LOG-7-CONNECTED: 10.93.159.109:9092/2: Connected (#1)
LOG-7-APIVERSION: 10.93.159.109:9092/2: Using (configuration fallback) 0.9.0 protocol features
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature MsgVer1: Produce (2..2) NOT supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature MsgVer1: Fetch (2..2) NOT supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2: Disabling feature MsgVer1
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature ApiVersion: ApiVersion (0..0) NOT supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2: Disabling feature ApiVersion
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature BrokerGroupCoordinator: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2: Enabling feature BrokerGroupCoordinator
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature BrokerBalancedConsumer: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature BrokerBalancedConsumer: OffsetCommit (1..2) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature BrokerBalancedConsumer: OffsetFetch (1..1) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature BrokerBalancedConsumer: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature BrokerBalancedConsumer: SyncGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature BrokerBalancedConsumer: Heartbeat (0..0) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature BrokerBalancedConsumer: LeaveGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2: Enabling feature BrokerBalancedConsumer
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature ThrottleTime: Produce (1..2) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature ThrottleTime: Fetch (1..2) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2: Enabling feature ThrottleTime
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature Sasl: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2: Enabling feature Sasl
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature SaslHandshake: SaslHandshake (0..0) NOT supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2: Disabling feature SaslHandshake
LOG-7-APIVERSION: 10.93.159.109:9092/2:  Feature LZ4: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: 10.93.159.109:9092/2: Enabling feature LZ4
LOG-7-FEATURE: 10.93.159.109:9092/2: Updated enabled protocol features to BrokerBalancedConsumer,ThrottleTime,Sasl,BrokerGroupCoordinator,LZ4
LOG-7-STATE: 10.93.159.109:9092/2: Broker changed state CONNECT -> UP
LOG-7-BROADCAST: Broadcasting state change
LOG-7-METADATA: 10.93.159.109:9092/2: Request metadata for locally known topics: connected
LOG-7-METADATA: 10.93.159.109:9092/2: Request metadata for locally known topics: connected
LOG-7-CONNECT: 10.93.190.155:9092/1: Connected to ipv4#10.93.190.155:9092
LOG-7-CONNECTED: 10.93.190.155:9092/1: Connected (#1)
LOG-7-APIVERSION: 10.93.190.155:9092/1: Using (configuration fallback) 0.9.0 protocol features
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature MsgVer1: Produce (2..2) NOT supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature MsgVer1: Fetch (2..2) NOT supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1: Disabling feature MsgVer1
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature ApiVersion: ApiVersion (0..0) NOT supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1: Disabling feature ApiVersion
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature BrokerGroupCoordinator: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1: Enabling feature BrokerGroupCoordinator
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature BrokerBalancedConsumer: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature BrokerBalancedConsumer: OffsetCommit (1..2) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature BrokerBalancedConsumer: OffsetFetch (1..1) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature BrokerBalancedConsumer: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature BrokerBalancedConsumer: SyncGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature BrokerBalancedConsumer: Heartbeat (0..0) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature BrokerBalancedConsumer: LeaveGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1: Enabling feature BrokerBalancedConsumer
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature ThrottleTime: Produce (1..2) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature ThrottleTime: Fetch (1..2) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1: Enabling feature ThrottleTime
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature Sasl: JoinGroup (0..0) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1: Enabling feature Sasl
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature SaslHandshake: SaslHandshake (0..0) NOT supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1: Disabling feature SaslHandshake
LOG-7-APIVERSION: 10.93.190.155:9092/1:  Feature LZ4: GroupCoordinator (0..0) supported by broker
LOG-7-APIVERSION: 10.93.190.155:9092/1: Enabling feature LZ4
LOG-7-RECV: 10.93.166.152:9092/0: Received MetadataResponse (v0, 130 bytes, CorrId 2, rtt 0.42ms)
LOG-7-SEND: 10.93.159.109:9092/2: Sent MetadataRequest (v0, 30 bytes @ 0, CorrId 1)
LOG-7-FEATURE: 10.93.190.155:9092/1: Updated enabled protocol features to BrokerBalancedConsumer,ThrottleTime,Sasl,BrokerGroupCoordinator,LZ4
LOG-7-STATE: 10.93.190.155:9092/1: Broker changed state CONNECT -> UP
LOG-7-BROADCAST: Broadcasting state change
LOG-7-METADATA: 10.93.190.155:9092/1: Request metadata for locally known topics: connected
LOG-7-METADATA: 10.93.190.155:9092/1: Request metadata for locally known topics: connected
LOG-7-METADATA: 10.93.166.152:9092/0: ===== Received metadata =====
LOG-7-METADATA: 10.93.166.152:9092/0: 3 brokers, 1 topics
LOG-7-METADATA: 10.93.166.152:9092/0:   Broker #0/3: 10.93.159.109:9092 NodeId 2
LOG-7-METADATA: 10.93.166.152:9092/0:   Broker #1/3: 10.93.190.155:9092 NodeId 1
LOG-7-METADATA: 10.93.166.152:9092/0:   Broker #2/3: 10.93.166.152:9092 NodeId 0
LOG-7-METADATA: 10.93.166.152:9092/0:   Topic #0/1: bee with 1 partitions
LOG-7-METADATA: 10.93.166.152:9092/0:   Topic bee partition 0 Leader 0
LOG-7-TOPICUPD: Topic bee [0] migrated from broker -1 to 0
LOG-7-BRKDELGT: Broker :0/internal no longer leader for topic bee [0]
LOG-7-BRKDELGT: Broker 10.93.166.152:9092/0 is now leader for topic bee [0] with 0 messages (0 bytes) queued
LOG-7-BRKMIGR: Migrating topic bee [0] from :0/internal to 10.93.166.152:9092/0
LOG-7-SEND: 10.93.190.155:9092/1: Sent MetadataRequest (v0, 30 bytes @ 0, CorrId 1)
LOG-7-TOPBRK: :0/internal: Topic bee [0]: leaving broker (next leader 10.93.166.152:9092/0)
LOG-7-BROADCAST: Broadcasting state change
LOG-7-RECV: 10.93.190.155:9092/1: Received MetadataResponse (v0, 130 bytes, CorrId 1, rtt 1.27ms)
LOG-7-METADATA: 10.93.190.155:9092/1: ===== Received metadata =====
LOG-7-METADATA: 10.93.190.155:9092/1: 3 brokers, 1 topics
LOG-7-METADATA: 10.93.190.155:9092/1:   Broker #0/3: 10.93.159.109:9092 NodeId 2
LOG-7-METADATA: 10.93.190.155:9092/1:   Broker #1/3: 10.93.190.155:9092 NodeId 1
LOG-7-METADATA: 10.93.190.155:9092/1:   Broker #2/3: 10.93.166.152:9092 NodeId 0
LOG-7-METADATA: 10.93.190.155:9092/1:   Topic #0/1: bee with 1 partitions
LOG-7-METADATA: 10.93.190.155:9092/1:   Topic bee partition 0 Leader 0
LOG-7-BRKDELGT: Broker 10.93.166.152:9092/0 is now leader for topic bee [0] with 0 messages (0 bytes) queued
LOG-7-RECV: 10.93.159.109:9092/2: Received MetadataResponse (v0, 130 bytes, CorrId 1, rtt 2.73ms)
LOG-7-METADATA: 10.93.159.109:9092/2: ===== Received metadata =====
LOG-7-METADATA: 10.93.159.109:9092/2: 3 brokers, 1 topics
LOG-7-METADATA: 10.93.159.109:9092/2:   Broker #0/3: 10.93.159.109:9092 NodeId 2
LOG-7-METADATA: 10.93.159.109:9092/2:   Broker #1/3: 10.93.190.155:9092 NodeId 1
LOG-7-METADATA: 10.93.159.109:9092/2:   Broker #2/3: 10.93.166.152:9092 NodeId 0
LOG-7-METADATA: 10.93.159.109:9092/2:   Topic #0/1: bee with 1 partitions
LOG-7-METADATA: 10.93.159.109:9092/2:   Topic bee partition 0 Leader 0
LOG-7-BRKDELGT: Broker 10.93.166.152:9092/0 is now leader for topic bee [0] with 0 messages (0 bytes) queued
LOG-7-TOPBRK: 10.93.166.152:9092/0: Topic bee [0]: joining broker
LOG-7-BROADCAST: Broadcasting state change
LOG-7-OFFSET: Topic bee [0]: timed offset query for BEGINNING in state offset-query
LOG-7-OFFREQ: 10.93.166.152:9092/0: Partition bee [0]: querying for logical offset BEGINNING (opv 2)
LOG-7-OFFSET: 10.93.166.152:9092/0: OffsetRequest (1 offsets) for topic bee [0] (v0)
LOG-7-PARTSTATE: Partition bee [0] changed fetch state offset-query -> offset-wait
LOG-7-SEND: 10.93.166.152:9092/0: Sent OffsetRequest (v0, 54 bytes @ 0, CorrId 3)
LOG-7-RECV: 10.93.166.152:9092/0: Received OffsetResponse (v0, 31 bytes, CorrId 3, rtt 0.68ms)
LOG-7-OFFSET: 10.93.166.152:9092/0: Offset reply for topic bee [0] (v2 vs v2)
LOG-7-OFFSET: Offset BEGINNING request for bee [0] returned offset 48 (48)
LOG-7-PARTSTATE: Partition bee [0] changed fetch state offset-wait -> active
LOG-7-FETCHDEC: Topic bee [0]: fetch decide: updating to version 2 (was 0) at offset 48 (was 0)
LOG-7-FETCH: 10.93.166.152:9092/0: Topic bee [0] at offset 48 (0/100000 msgs, 0/1000000 kb queued, opv 2) is fetchable: 
LOG-7-FETCHADD: 10.93.166.152:9092/0: Added bee [0] to fetch list (1 entries, opv 2)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch topic bee [0] at offset 48 (v2)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch 1/1/1 toppar(s)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch for 1 toppars, fetching=1, backoff=0ms
LOG-7-SEND: 10.93.166.152:9092/0: Sent FetchRequest (v1, 62 bytes @ 0, CorrId 4)
LOG-7-RECV: 10.93.166.152:9092/0: Received FetchResponse (v1, 574 bytes, CorrId 4, rtt 0.69ms)
LOG-7-FETCH: 10.93.166.152:9092/0: Topic bee [0] MessageSet size 539, error "Success", MaxOffset 57, Ver 2/2
LOG-7-CONSUME: 10.93.166.152:9092/0: Enqueue 8 messages on bee [0] fetch queue (qlen 0, v2)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch reply: Success
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch topic bee [0] at offset 56 (v2)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch 1/1/1 toppar(s)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch for 1 toppars, fetching=1, backoff=0ms
Read msg at offset 48
*****
Read msg at offset 49
LOG-7-SEND: 10.93.166.152:9092/0: Sent FetchRequest (v1, 62 bytes @ 0, CorrId 5)
*****
Read msg at offset 50
*****
Read msg at offset 51
*****
Read msg at offset 52
*****
Read msg at offset 53
*****
Read msg at offset 54
*****
Read msg at offset 55
*****
LOG-7-RECV: 10.93.166.152:9092/0: Received FetchResponse (v1, 256 bytes, CorrId 5, rtt 0.59ms)
LOG-7-FETCH: 10.93.166.152:9092/0: Topic bee [0] MessageSet size 221, error "Success", MaxOffset 57, Ver 2/2
LOG-7-CODEC: 10.93.166.152:9092/0: bee [0]: Message at offset 56 with unsupported compression codec 0x1: message ignored
LOG-7-CONSUME: 10.93.166.152:9092/0: Enqueue 1 messages on bee [0] fetch queue (qlen 0, v2)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch reply: Success
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch topic bee [0] at offset 56 (v2)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch 1/1/1 toppar(s)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch for 1 toppars, fetching=1, backoff=0ms
Consume failed: Local: Not implemented
LOG-7-DESP: Removing (un)desired topic bee [0]
LOG-7-BARRIER: bee [0]: rd_kafka_toppar_op_fetch_stop:1887: new version barrier v3
LOG-7-CONSUMER: Stop consuming bee [0] (v3)
LOG-7-OP: bee [0] received op FETCH_STOP (v3) in fetch-state active
LOG-7-FETCH: Stopping fetch for bee [0] in state active (v3)
LOG-7-PARTSTATE: Partition bee [0] changed fetch state active -> stopping
LOG-7-PARTSTATE: Partition bee [0] changed fetch state stopping -> stopped
LOG-7-SEND: 10.93.166.152:9092/0: Sent FetchRequest (v1, 62 bytes @ 0, CorrId 6)
LOG-7-FETCH: 10.93.166.152:9092/0: Topic bee [0] at offset 48 (0/100000 msgs, 0/1000000 kb queued, opv 2) is not fetchable: not in active fetch state
LOG-7-FETCHADD: 10.93.166.152:9092/0: Removed bee [0] from fetch list (0 entries, opv 2)
LOG-7-RECV: 10.93.166.152:9092/0: Received FetchResponse (v1, 256 bytes, CorrId 6, rtt 0.38ms)
LOG-7-FETCH: 10.93.166.152:9092/0: Topic bee [0] MessageSet size 221, error "Success", MaxOffset 57, Ver 2/2
LOG-7-CODEC: 10.93.166.152:9092/0: bee [0]: Message at offset 56 with unsupported compression codec 0x1: message ignored
LOG-7-CONSUME: 10.93.166.152:9092/0: Enqueue 1 messages on bee [0] fetch queue (qlen 0, v2)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch reply: Success
LOG-7-DESTROY: Terminating instance
LOG-7-BROADCAST: Broadcasting state change
LOG-7-DESTROY: Destroy internal
LOG-7-DESTROY: Remove all topics
LOG-7-PARTCNT: Topic bee partition count changed from 1 to 0
LOG-7-BRKDELGT: Broker 10.93.166.152:9092/0 no longer leader for topic bee [0]
LOG-7-BRKDELGT: No broker is leader for topic bee [0]
LOG-7-BRKMIGR: Migrating topic bee [0] from 10.93.166.152:9092/0 to (none)
LOG-7-TOPPARREMOVE: Removing toppar bee [-1]
LOG-7-TOPBRK: 10.93.166.152:9092/0: Topic bee [0]: leaving broker (next leader (none))
LOG-7-BROADCAST: Broadcasting state change
LOG-7-TOPPARREMOVE: Removing toppar bee [0]
LOG-7-TERMINATE: 10.93.190.155:9092/1: Handle is terminating: failed 0 request(s) in retry+outbuf
LOG-7-BROKERFAIL: 10.93.190.155:9092/1: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
LOG-7-STATE: 10.93.190.155:9092/1: Broker changed state UP -> DOWN
LOG-7-BROADCAST: Broadcasting state change
LOG-7-BUFQ: 10.93.190.155:9092/1: Purging bufq with 0 buffers
LOG-7-BUFQ: 10.93.190.155:9092/1: Purging connection-setup requests from bufq with 0 buffers
LOG-7-TERMINATE: 10.93.159.109:9092/2: Handle is terminating: failed 0 request(s) in retry+outbuf
LOG-7-BROKERFAIL: 10.93.159.109:9092/2: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
LOG-7-STATE: 10.93.159.109:9092/2: Broker changed state UP -> DOWN
LOG-7-BROADCAST: Broadcasting state change
LOG-7-BUFQ: 10.93.159.109:9092/2: Purging bufq with 0 buffers
LOG-7-BUFQ: 10.93.159.109:9092/2: Purging connection-setup requests from bufq with 0 buffers
LOG-7-TERMINATE: 10.93.166.152:9092/0: Handle is terminating: failed 0 request(s) in retry+outbuf
LOG-7-BROKERFAIL: 10.93.166.152:9092/0: failed: err: Local: Broker handle destroyed: (errno: Resource temporarily unavailable)
LOG-7-STATE: 10.93.166.152:9092/0: Broker changed state UP -> DOWN
LOG-7-BROADCAST: Broadcasting state change
LOG-7-BUFQ: 10.93.166.152:9092/0: Purging bufq with 0 buffers
LOG-7-BUFQ: 10.93.166.152:9092/0: Purging connection-setup requests from bufq with 0 buffers
LOG-7-TERMINATE: :0/internal: Handle is terminating: failed 0 request(s) in retry+outbuf
LOG-7-BROKERFAIL: :0/internal: failed: err: Local: Broker handle destroyed: (errno: Success)
LOG-7-STATE: :0/internal: Broker changed state UP -> DOWN
LOG-7-BROADCAST: Broadcasting state change
LOG-7-BUFQ: :0/internal: Purging bufq with 0 buffers
LOG-7-BUFQ: :0/internal: Purging connection-setup requests from bufq with 0 buffers

I notice the msg:
LOG-7-RECV: 10.93.166.152:9092/0: Received FetchResponse (v1, 256 bytes, CorrId 5, rtt 0.59ms)
LOG-7-FETCH: 10.93.166.152:9092/0: Topic bee [0] MessageSet size 221, error "Success", MaxOffset 57, Ver 2/2
LOG-7-CODEC: 10.93.166.152:9092/0: bee [0]: Message at offset 56 with unsupported compression codec 0x1: message ignored
LOG-7-CONSUME: 10.93.166.152:9092/0: Enqueue 1 messages on bee [0] fetch queue (qlen 0, v2)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch reply: Success
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch topic bee [0] at offset 56 (v2)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch 1/1/1 toppar(s)
LOG-7-FETCH: 10.93.166.152:9092/0: Fetch for 1 toppars, fetching=1, backoff=0ms
Consume failed: Local: Not implemented

version:librdkafka-master 20160912 downloaded
with unsupported compression codec 0x1, I think it's not this way, any suggestions?
thanks a lot.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:   suse linux 11 sp3
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It seems like librdkafka was built without gzip compression support, you can verify this by doing:
`rdkafka_example -X list | grep builtin.features`: is gzip listed?

If not you will need to to install the zlib-devel package and then reconfigure and rebuild librdkafka:
```
$ sudo yum install zlib-devel
$ ./configure --reconfigure
grep WITH_ZLIB config.h # should say WITH_ZLIB 1
$ make
$ sudo make install
```

**Comment by robertbee** [comment]
great thanks, that's really i miss the zlib.

**Comment by shukla-praveen** [comment]
Thanks @edenhill worked for me as well 👍 
sudo apt-get install zlib1g-dev (For ubuntu instead of zlib-devel)

**Comment by arpanshah29** [comment]
@achilles42 after apt-get installing zlib-devel, did you have to rebuild librdkafka?

**Comment by brennovich** [comment]
@arpanshah29 yes, you need to recompile it.

It's `zlib-dev` for **alpine**.
