### ISSUE TITLE
When does payload copied because of RD_KAFKA_MSG_F_COPY being true get freed?

### ISSUE THREAD

**Issue by kparadkar** [edenhill/librdkafka#899]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
If you've registered a delivery report callback: when your dr callback returns.
If not: when the message has been acked by broker, or failed delivery (after retries)
