### ISSUE TITLE
RDKafka producer publishes messages but doesn't reflect in message count

### ISSUE THREAD

**Issue by sampather** [edenhill/librdkafka#900]
Hi Team,

Am using rdkafka version 0.9.1 with .net core.
When i deploy it on ubuntu server 14.X OS the publisher posts message and can be seen with the increase in message.
The same project is being deployed on windows server 2012 R2 standard, in this publisher doesn't error out it says the publish was successful but doesn't reflect the same in message counts.
But when deployed on windows 7 sp1 the publish is success and reflects in message count.

Can anyone tell whats the problem here. am i missing anything.

I do have a strange problem with ubuntu, when i try and load test with like 1000 messages , the cpu consumption raises , it's just that publisher.Dispose() doesn't respond at all and causes the system to crash

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [x] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I think this issue should be filed on https://github.com/ah-/rdkafka-dotnet

**Comment by sampather** [comment]
Thanks
