### ISSUE TITLE
broker 0.10 with rdkafka 0.8.6

### ISSUE THREAD

**Issue by rathdeep** [edenhill/librdkafka#904]
Hi,

I went through broker version compatibility document as we plan to migrate our brokers to 0.10.
https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

We don't plan to upgrade librdkafka version 0.8.6 (does not support api version property) for now.

Do we need to be worry about these issues?

Thanks

**Comment by edenhill** [comment]
You should be fine, the broker is backwards compatible with older clients. 
So note though that running older clients with a >=0.10 broker forces the broker to translate old msg formats internally. This isn't a problem in itself but will increase the broker CPU and memory consumption.

**Comment by jeffwidman** [comment]
> So note though that running older clients with a >=0.10 broker forces the broker to translate old msg formats internally. 

My understanding was this is only true once `log.message.format.version` was bumped to the newer broker version? If it matches the old broker version, then I thought this wasn't an issue.
