### ISSUE TITLE
Invalid value for configuration property "compression.codec" for LZ4 compression type

### ISSUE THREAD

**Issue by AKR2015** [edenhill/librdkafka#909]
Description
===========
Hello edenhill,

I trying to use the 0.9.2 with broker version 0.9.1 with LZ4 compression. when i try to set the 
config["compression.codec"] = "lz4";
i get below this error "Invalid value for configuration property "compression.codec""

when i try to see the builtin.features, i get the below result.
config["builtin.features"]
"gzip,snappy,ssl,regex"

while as per latest release(0.9.2 on 11/09/2016), it does support the lz4 compression. 

How to reproduce
================
I am using in .net version of Rdkafka-dotnet
config["compression.codec"] = "lz4";

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):0.9.2
 - [ ] Apache Kafka version: 0.9.1
 - [ ] librdkafka client configuration:0.9.2
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [X ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You need liblz4-dev package installed prior to ./configure

**Comment by AKR2015** [comment]
@edenhill 
thanks for quick response.
Is there way to build this on windows using visual studio...i see the below instruction and find LZ4 support mentioned as missing ..
NOTE: See README.win32 for instructions how to build on Windows with Microsoft Visual Studio.

any help will be really appreciated.

**Comment by edenhill** [comment]
I havent tried it, but if you manage to install liblz4 with its headers on Windows and set up VS to find them, all you need to do is `#define WITH_LZ4 1` in src/win32_config.h

**Comment by edenhill** [comment]
lz4 is now enabled by default on Win32 (master branch)
