### ISSUE TITLE
Issue producing 10,000 messages in quick sequence with 0.9.2

### ISSUE THREAD

**Issue by webmakersteve** [edenhill/librdkafka#910]
Description
===========
When producing over 100 messages in a for loop in the node.js library, it does not emit any delivery report events. I have put logging in the c++ callback to ensure it isn't just an issue with the transmission of the event from c++ to v8. 

When doing 100, each message gets an individual delivery report. When doing more, no delivery reports are emitted. Poll is being called on a 200ms interval.

How to reproduce
================
Unfortunately it's hard to tell if it's a library problem or something in the communication between node and librdkafka.

Can be reliably reproduced using `node-rdkafka` when running the producer unit tests when producing over

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.2
 - [ ] Apache Kafka version: 0.9.2
 - [ ] librdkafka client configuration: All defaults, except debug set to all. (Or not. Reproduces in both cases)
 - [ ] Operating system: Arch Linux
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
These logs keep getting logged up until the test times out after 3 seconds. 
```
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
{ severity: 7, fac: 'SEND' } '127.0.0.1:9092/1001: Sent partial ProduceRequest (v1, 0+0/36980 bytes, CorrId 2)'
```

This is not a critical issue, but does stop me from upgrading the library underneath until I can resolve it.

https://github.com/Blizzard/node-rdkafka/blob/lib-update/e2e/producer.spec.js#L133

**Comment by edenhill** [comment]
What's your producer config?
What's the message sizes?

Are you running in a constrained environment, such as slow network or similar?
Those partial requests are typically an indication of network backpressure but this should only be seen when you transmit a lot of data.

**Comment by webmakersteve** [comment]
The producer config is all the defaults, except:
`client.id` is `kafka-test`
`metadata.broker.list` is `localhost:9092`
`dr_cb` is set, and handled by the library.
`debug` is set to all

The message size is 9-10 bytes for all of the messages.

I am using a docker kafka and zookeeper container for the CI tests, and running that same situation on my local machine to reproduce it.

The issue only happens in the `librdkafka` 0.9.2. It seems to pass CI in 0.9.1

When running it on the bigger kafka cluster we have I am getting a similar result. 

```
{ severity: 7, fac: 'SEND' } 'dev6-kafka-broker02.battle.net:9092/24: Sent partial ProduceRequest (v1, 0+0/42939 bytes, CorrId 3)'
{ severity: 7, fac: 'TOPPAR' } 'dev6-kafka-broker02.battle.net:9092/24: librdtesting-01 [2] 0+0 msgs'
{ severity: 7, fac: 'TOPPAR' } 'dev6-kafka-broker02.battle.net:9092/24: librdtesting-01 [5] 0+0 msgs'
{ severity: 7, fac: 'SEND' } 'dev6-kafka-broker01.battle.net:9092/23: Sent partial ProduceRequest (v1, 0+0/43850 bytes, CorrId 4)'
{ severity: 7, fac: 'TOPPAR' } 'dev6-kafka-broker01.battle.net:9092/23: librdtesting-01 [4] 0+0 msgs'
{ severity: 7, fac: 'TOPPAR' } 'dev6-kafka-broker01.battle.net:9092/23: librdtesting-01 [1] 0+0 msgs'
{ severity: 7, fac: 'SEND' } 'dev6-kafka-broker02.battle.net:9092/24: Sent partial ProduceRequest (v1, 0+0/42939 bytes, CorrId 3)'
{ severity: 7, fac: 'TOPPAR' } 'dev6-kafka-broker02.battle.net:9092/24: librdtesting-01 [2] 0+0 msgs'^CTerminated
```

**Comment by edenhill** [comment]
What's the broker verison? 0.9.0.1?

**Comment by webmakersteve** [comment]
Yes. Broker version is 0.9.0.1

**Comment by edenhill** [comment]
Is it reproducible with rdkafka_performance, or similar?

**Comment by webmakersteve** [comment]
```
% Sending messages of size 31 bytes
% 1065913 messages produced (33043303 bytes), 565913 delivered (offset 0, 0 failed) in 1000ms: 565873 msgs/s and 17.54 Mb/s, 32 produce failures, 500000 in queue, no compression
% 1683688 messages produced (52194328 bytes), 1193688 delivered (offset 0, 0 failed) in 2005ms: 595194 msgs/s and 18.45 Mb/s, 122 produce failures, 490000 in queue, no compression
% 2221740 messages produced (68873940 bytes), 2116627 delivered (offset 0, 0 failed) in 3005ms: 704240 msgs/s and 21.83 Mb/s, 175 produce failures, 105113 in queue, no compression
% 3545842 messages produced (109921102 bytes), 3405416 delivered (offset 0, 0 failed) in 4005ms: 850175 msgs/s and 26.36 Mb/s, 175 produce failures, 140426 in queue, no compression
% 4579139 messages produced (141953309 bytes), 4542126 delivered (offset 0, 0 failed) in 5006ms: 907301 msgs/s and 28.13 Mb/s, 175 produce failures, 37013 in queue, no compression
% 5865441 messages produced (181828671 bytes), 5807313 delivered (offset 0, 0 failed) in 6006ms: 966887 msgs/s and 29.97 Mb/s, 175 produce failures, 58128 in queue, no compression
% 6925131 messages produced (214679061 bytes), 6700847 delivered (offset 0, 0 failed) in 7007ms: 956236 msgs/s and 29.64 Mb/s, 175 produce failures, 224284 in queue, no compression
% 8214469 messages produced (254648539 bytes), 8028293 delivered (offset 0, 0 failed) in 8029ms: 999788 msgs/s and 30.99 Mb/s, 175 produce failures, 186176 in queue, no compression
```

It looks like it got a few produce failures on that run but it doesn't reproduce reliably. Most of the runs had 0 errors

**Comment by edenhill** [comment]
the produce failures probably just backpressure (produce() returns QUEUE_FULL so rdkafka_performance waits and tries again, an alternative would be to use RD_KAFKA_MSG_F_BLOCK).
You can verify this by hitting ctrl-c, it should say % Backpressure <somethingsomething-not-zero>

Anyway, from the look of this it looks alright.
Back to the node.js client, you are sure this doesn't happen with 0.9.1, just with 0.9.2?
