### ISSUE TITLE
Local Queue Full

### ISSUE THREAD

**Issue by revrunner** [edenhill/librdkafka#911]
Description
===========
What kind of settings on the topic_conf should I use for my kafka producer if I'm sending 100k messages/s? I keep getting a queue full issue and have tried adjusting the poll time, but now the process upload to kafka is taking up the majority of the runtime. I tried to adjust the batching and queue.buffering.messages.max and queue.buffering.messages.ms but then i didn't see anything on consumer side until i tried to breakdown the connection to kafka and it was dumping all of the data at once.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
100k msgs/s shouldnt be a problem, but it depends on the message size, what is it?

Are you calling poll() frequently enough?

**Comment by revrunner** [comment]
~180 kbs a msg. i call rd_kafka_poll() every message. and have default settings for the topic_conf right now. each message is an avrocpp encoded byte array

**Comment by edenhill** [comment]
Are you sure about those numbers?
100k msgs/s at 180 kb per message is about 18 Gb/s, I dont see how any broker can keep up with that rate.

**Comment by revrunner** [comment]
sry, 180bytes. not kb.

**Comment by revrunner** [comment]
i re cloned the repo and ran it, and ran into the queue full issue again, but your code cleared the queue and didn't have that problem afterwards. Mine seems to run in the queue full issue also, but its not actually pushing up to kafka, cause i can't see the output on consumer side. And it doesn't seem to be clearing the queue like yours. I split the main you wrote in rdkafka_example.c into four parts. One to handle breakdown of connection, one for pushing messages to kafka server, one for polling, and one to create the topic handle. Hopefully this helps to understand my issue.
[cProducer.txt](https://github.com/edenhill/librdkafka/files/596244/cProducer.txt)

**Comment by edenhill** [comment]
The code has the relevant parts but you didnt include the code that actually makes use of those functions, so it is hard to say if you are using it correctly.

**Comment by revrunner** [comment]
[cparser.txt](https://github.com/edenhill/librdkafka/files/607200/cparser.txt)
 sorry about that.

**Comment by edenhill** [comment]
The code that calls the Kafka stuff is commented out, so I dont think this code does much.
Anyway, if you get QUEUE_FULL you should typically back off producing and call poll() to wait for delivery reports, then you can try again.
