### ISSUE TITLE
is there a way to know the total message count of a partition ? 

### ISSUE THREAD

**Issue by yourNameIsGood** [edenhill/librdkafka#912]
Description
===========

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (0.9.2):
 - [x] Apache Kafka version: 0.8
 - [ ] librdkafka client configuration:
 - [ ] Operating system: Ubuntu
 - [x] Using the legacy Consumer : yes, Rdkafka\Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Have a look at query_watermark_offsets
