### ISSUE TITLE
conf error: No such configuration property: "fetch.max.wait.ms"

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#916]
Description
===========

How to reproduce
================
using cpp version of librdkafka

Configuration
fetch.min.bytes=10000000 
fetch.max.wait.ms=5000

happens when I do the  conf->set()

Checklist
=========
Please provide the following information:

 - [git deaea3d ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [Ubuntu 16.04 ] Operating system:
 - [ ] Using the legacy Consumer
 - [x ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
fetch.wait.max.ms

**Comment by imba-tjd** [comment]
Why?
I used https://web.archive.org. It turns out in 2016 the kafka doc had used `fetch.max.wait.ms`. Why librdkafka uses `fetch.wait.max.ms`?
And how about adding an alias?
