### ISSUE TITLE
Producer offset report 

### ISSUE THREAD

**Issue by zkaiwen** [edenhill/librdkafka#917]
Description
===========
I'm trying to track the offset of the messages written into kafka. I have a delivery report callback that i'm using to check the offsets that are coming out. However, it seems like the offset returned is for the last message in the batch that is sent, and not for each message. The messages are queued up locally and is held up by the network so I'm assuming that it's batching the messages. Sample output of the message output from the callback is shown below. The remaining output is when checking to see if the local queue is empty. It shows the remaining messages in the queue to be sent out
    
    ...
    Message delivery for (1036830 bytes): Success, Index: 2636, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2637, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2639, Offset: 31010
    Remaining: 142
    Message delivery for (1036830 bytes): Success, Index: 2641, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2642, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2645, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2646, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2647, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2648, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2649, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2652, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2657, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2658, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2659, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2660, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2661, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2662, Offset: 0
    Message delivery for (1036830 bytes): Success, Index: 2663, Offset: 31025
    Remaining: 127
    ...

I'm not sure if this is the expected behavior, but I would like that whenever the dr_cb is called, to keep track of the offset for each message. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
0.9.1
 - [x] Apache Kafka version: 
0.10.0
 - [ ] librdkafka client configuration:
 - [x] Operating system:
centos 7
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by zkaiwen** [comment]
I am currently overriding the dr_cb function in the DeliveryReportCb. However, according to configuration.md, the produce.offset.report needs dr_msg_cb to be used. But when looking through the docs, there is no dr_msg_cb under DeliveryReportCb.

**Comment by ah-** [comment]
Don't remember the exact name but there's a config option for just that.

**Comment by edenhill** [comment]
DeliveryReportCb (C++) provides the same functionality as dr_msg_cb (C), so setting `produce.offset.report` to true and reading msg.offset() should be sufficient.

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/FAQ#how-do-i-get-the-offset-of-a-produced-message
