### ISSUE TITLE
Question / wishlist : modifying an existing RdKafka::Message

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#919]
Description
===========
My problem is the following :
I get a message from a kafka topic using 
```
RdKafka::Message *myMsg = myConsumer->consume()
```
then I process my message how I want and I forward the message to a new kafka cluster/topic doing :
```
myProducer->produce(topic,RdKafka::Topic::PARTITION_UA, RdKafka::Producer::RK_MSG_COPY,
		      myMsg->payload(), myMsg->len(), myMsg->key(),offset_mapkey);
delete (myMsg)
```
Problem : this is inefficient because I tell librdKafka to copy the payload and then I delete the payload which is in the myMessage object ;
which results in a useless copy of 1 GB of data to process 1 GB of incoming data.

if RdKafka::Message had the 2 new methods setPayload(void*) and setLen(size_t)
(or just setPayload(void*, size_t) )
I would be able to use RK_MSG_FREE and just write :
```
RdKafka::Message *myMsg = myConsumer->consume()
//myFooBarProcessing(myMsg);
myProducer->produce(topic,RdKafka::Topic::PARTITION_UA, RdKafka::Producer::RK_MSG_FREE,
		      myMsg->payload(), myMsg->len(), myMsg->key(),offset_mapkey);
myMsg->setPayload(NULL);
myMsg->setLen(0);
delete (myMsg);
```

Are you OK to enrich the cpp interface of RdKafka::Message for such use ?
Thank you. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ cpp interface ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I see your pain, unfortunately it is not that easy because all messages received in the same batch share the same underlying memory (zero copying).

What you can do though is simply hang on on the consumer's Message until the producer deliveryReport callback is done.

E.g.:
```
 msg = c->consume();
 p->produce(..., msg->payload, msg->size, .. 0/*msgflags*, msg/*msg_opaque*/);

...
dr_cb (.., void *msg_opaque) {
  Message *m = msg_opaque;
  ..
  delete m;
}
````

**Comment by edenhill** [comment]
Just make sure to monitor memory usage

**Comment by vin-d** [comment]
Good idea, thank you.
