### ISSUE TITLE
ask for documentation precision around Handle::resume and KafkaConsumer::assignement

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#922]
Hi, I'd like to get a bit of precision to some KafkaConsumer calls.

Description
===========
I base my use of the library on 
librdkafka/staging-docs/html/classRdKafka_1_1KafkaConsumer.html

I see that by calling resume on a KafkaConsumer, it (in addition to the "play/pause" feature it gives) repositions its "position" at the offset set in the TopicPartitions given by parameter.

A) Is that an intended use ? because it's not documented in the interface documentation.
B) I note that position() can retrieve the currents offsets of the KafkaConsumer (without touching committed offsets) but there is no setPosition() call. Can I then legally consider that resume() provides such capability.
C) what is the definition of the offset value returned in TopicPartitions when a KafkaConsumer calls assign().

D) ::edit::
there is no question D) --> in fact I had a logic bug in my software.
 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.9.2 ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
A) The offset of the TopicPartition is ignored in resume(). resume() will resume consuming at the app_offset saved by pause(). The app_offset is the offset of the last message passed to the application

B) You can either use assign() to set the offsets to consume, or seek().
  assign() replaces the current assignment so it might be a bit heavy, while seek() just updates the next offset to fetch (and purging the queue of fetched messages). Do note however that seek() requires that consumtion has already started for the partition.

C) assign() sets the starting offset for each assigned partition to the offset provided in the TopicPartition. If that offset is unset (INVALID) it will default to STORED and thus retrieve offsets from committed storage, and if that fails employ auto.offset.reset

D) So you are saying that you do something like this:
````
   rebalancecb (parts) {
      if (ASSIGN_PARTITIONS) {
          assign(parts);
          pause(parts);
      } else {
        unassign();
     }
   }
....
...
   while (run) {
       m = consumer->consume();
       ..
    }
```

And if you do that you still get the first message (just one? not more?) after a rebalance even though you havent called resume() yet?

**Comment by vin-d** [comment]
I just edited my initial post as for D) it's a logic error from my side  :-x

**Comment by vin-d** [comment]
Thanks for the answers but correct me if I'm wrong : 
seek() is a Consumer Method.
not a KafkaConsumer one nor a Handle one so I can't use it.
is there a reason ?

Anyway, it's not a problem for me as I'm satisfied with assign().

**Comment by edenhill** [comment]
Right, seek() is not currently available in the C++ KafkaConsumer
