### ISSUE TITLE
SASL Handshake not supported by broker  - Error connecting to 0.10.0.1 broker using sasl/plain

### ISSUE THREAD

**Issue by edoardocomar** [edenhill/librdkafka#927]
Description
===========
with librdkafka at current master level
https://github.com/edenhill/librdkafka/commit/4a58dd60b132432b4bcaeae52c22b892bf8d01e3
running the librdkafka_example example against Message Hub (broker 0.10.0.1 with sasl plain)
I cannot successfully handshake :

`SASL authentication: SASL Handshake not supported by broker`

```1480435084.230 RDKAFKA-3-ERROR: rdkafka#producer-1: sasl_ssl://kafka02-devtest01.messagehub.services.eu-gb.bluemix.net:9093/bootstrap: Failed to initialize SASL authentication: SASL Handshake not supported by broker (required by mechanism PLAIN)
1480435084.256 RDKAFKA-3-FAIL: rdkafka#producer-1: sasl_ssl://kafka04-devtest01.messagehub.services.eu-gb.bluemix.net:9093/bootstrap: Failed to initialize SASL authentication: SASL Handshake not supported by broker (required by mechanism PLAIN)
1480435084.256 RDKAFKA-3-ERROR: rdkafka#producer-1: sasl_ssl://kafka04-devtest01.messagehub.services.eu-gb.bluemix.net:9093/bootstrap: Failed to initialize SASL authentication: SASL Handshake not supported by broker (required by mechanism PLAIN)
% Failed to acquire metadata: Local: Broker transport failure
```

0.9.2 and 0.9.1 both work fine

How to reproduce
================

checkout master, configure and make and run the example
```
./rdkafka_example -b "kafka01-prod01.messagehub.services.us-south.bluemix.net:9093,kafka02-prod01.messagehub.services.us-south.bluemix.net:9093,kafka03-prod01.messagehub.services.us-south.bluemix.net:9093,kafka04-prod01.messagehub.services.us-south.bluemix.net:9093,kafka05-prod01.messagehub.services.us-south.bluemix.net:9093" -X "security.protocol=sasl_ssl" -X "ssl.ca.location=/etc/ssl/certs/SystemRootsCertificates.pem" -X "sasl.mechanisms=PLAIN" -X "sasl.username=<my cred>" -X "sasl.password=<my cred>" $@
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
4a58dd60b132432b4bcaeae52c22b892bf8d01e3
 - [x] Apache Kafka version: 0.10.0.1
 - [ ] librdkafka client configuration:
 - [x] Operating system: macOS sierra
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You need to enable the new protocol features needed by SASL auth handshake which was added in 0.10.
Either by api.version.request=true (preferred)  or broker.version.fallback=0.10.the.version

**Comment by edenhill** [comment]
Did that fix it?

**Comment by edoardocomar** [comment]
Thanks @edenhill both options work !
