### ISSUE TITLE
Batch polling for High-level KafkaConsumer C API ?

### ISSUE THREAD

**Issue by recao** [edenhill/librdkafka#928]
Description
===========
Hi, I'm new to librdkafka and trying to implement a C# wrapper of it. 

Seems that for the High-level KafkaConsumer C API, there is only one message-polling function called "rd_kafka_consumer_poll", which returns only **one** message object if succeed. 

Is there a function for polling **a batch of** messages for High-level KafkaConsumer? If not, is there a recommended way to implement such function? Thanks.

**Comment by edenhill** [comment]
What you can (probably) do is extract the consumer queue with `rd_kafka_queue_get_consumer()` (make sure to call `rd_kafka_poll_set_consumer()` first), and then consume that queue using `rd_kafka_consume_batch_queue()`.

I haven't verified this myself, but in theory it should work :)

Why do you need to read messages in batches?

**Comment by recao** [comment]
I'm trying to implement a scenario where High-level consumer must stop consuming when: 
1) it has consumed 6,000 messages since last commit
2) it has been consuming over 1 second since last commit (suppose it cosumed X msg before timeout)

,**whichever of 6000 or 1-sec comes first**, the consumer must stop consuming, then hand over this 6,000 or X msg as a whole batch for processsing. 

So I was wondering whether librdkafka already has similar batch polling functions with parameter size & timeout, etc. Otherwise, I would need to use a loop to consume messages one by one, along with a timer. 

Now I could try function rd_kafka_consume_batch_queue() you mentioned, thanks :)
