### ISSUE TITLE
Question: When is a partition unavailable ?

### ISSUE THREAD

**Issue by Wramberg** [edenhill/librdkafka#929]
Hey,

I'm using librdkafka in a larger component. I have implemented my own partitoner which is supposed to avoid using partitions which are unavailable.

I have written a simple C++ Broker Stub to respond to metadata and produce requests which i use for unittests. I am trying to test my partitioner but whatever I do librdkafka insists that the partition is available.

So far I have tried:
Simulating a setup with two brokers: Broker 0 and Broker 1. In this setup we act as if Broker 0 is down. Using rd_kafka_brokers_add() I give the following addresses to rdkafka:

> 127.0.0.1:16 <- connection refused
> 127.0.0.1:x

where x is the port of the broker stub that is actually responding. When responding to metadata requests the broker stub states that there are two partitions - one at each broker. Despite being unable to reach broker 0 it still saids its partition is up.

**Comment by edenhill** [comment]
..available() will return true if the partition exists and has a leader broker assigned (but not necessarily a connection to that leader).

**Comment by Wramberg** [comment]
Ah ok I see. So theres no way to avoid brokers that aren't up ? Maybe I'm misunderstanding what the kafka cluster does in this scenario. If a broker is down for a longer period of time maybe its supposed to be removed from metadata responses ?

**Comment by edenhill** [comment]
Since the nature of connections are fragile an application should typically not bother with connectivity details, librdkafka abstracts all that handling.
What it typically boils down to instead is: how long am I willing to spend producing a message before I give up? And that's controlled by the topic property `message.timeout.ms` (default 5 minutes).

**Comment by Wramberg** [comment]
Makes sense - thanks for the quick replies and clearing everything up :-)
