### ISSUE TITLE
why consumer poll after stop 

### ISSUE THREAD

**Issue by ajige** [edenhill/librdkafka#930]
Description
===========
in source code: example/rdkafka_example.cpp, 
line 614: 
614     consumer->stop(topic, partition);
615
616     consumer->poll(1000);
1. why call poll after stop?  Is it necessary?
2. What does stop do?  After stop, if an event happens, like disconnect from broker, process will segment, since hanle->event_cb_ is empty.  Why and how to handle this??

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.9.1 ] librdkafka version (release number or git tag):

**Comment by edenhill** [comment]
Stop in the legacy consumer will stop consumtion for that partition and purge its message queue.
The following poll() is as you say, for handling other types of callbacks, such as error_cb.

The applicaiton should not segfault when you do this, is this reproducible with rdkafka_example?

**Comment by ajige** [comment]
Yes, it is reproducible.  Donot know why handle->event_cb_ become empty.

**Comment by ajige** [comment]
one more question:  here why poll 1000ms, how long should be long enough? what if consumer->poll(0) ?
616 consumer->poll(1000);

**Comment by edenhill** [comment]
How do you reproduce this with rdkafka_example_cpp?

**Comment by edenhill** [comment]
You dont really need to poll() after stopping your consumer if you dont want to, so the timeout is just arbitrary in the example.
