### ISSUE TITLE
Valgrind reports assignor leak during termination (librdkafka 0.9.0)

### ISSUE THREAD

**Issue by Wramberg** [edenhill/librdkafka#931]
Description
===========
I am using the v0.9.0 C api from within a C++ class to produce messages. I get the following leak from valgrind:

> ==26236== 128 (72 direct, 56 indirect) bytes in 1 blocks are definitely lost in loss record 6 of 6
> ==26236==    at 0x4C2B974: calloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==26236==    by 0x46D1BD: rd_calloc (rd.h:77)
> ==26236==    by 0x46EA84: rd_kafka_assignor_add (rdkafka_assignor.c:450)
> ==26236==    by 0x46EBDA: rd_kafka_assignors_init (rdkafka_assignor.c:489)
> ==26236==    by 0x458455: rd_kafka_new (rdkafka.c:1033)
> rd_kafka_new(RD_KAFKA_PRODUCER, m_kafkaConf, errstr, sizeof(errstr)) is called here...

My code
======
I initialize in the following way:
```
char errstr[512];
m_kafkaConf = rd_kafka_conf_new();
if (!m_kafkaConf)
{
   // Log here
   return false;
}

rd_kafka_conf_set_opaque(m_kafkaConf, this);
rd_kafka_conf_set_error_cb(m_kafkaConf, errorCallback);
rd_kafka_conf_set_throttle_cb(m_kafkaConf, throttleCallback);
rd_kafka_conf_set_dr_msg_cb(m_kafkaConf, messageDeliveredExtCallback);
rd_kafka_conf_set_dr_cb(m_kafkaConf, messageDeliveredCallback);
rd_kafka_conf_set_log_cb(m_kafkaConf, logCallback);

if (rd_kafka_conf_set(m_kafkaConf, "queue.buffering.max.messages", "1000000", errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK)
{
   // Log here
}

if (rd_kafka_conf_set(m_kafkaConf, "batch.num.messages", "10000", errstr, sizeof(errstr)) != RD_KAFKA_CONF_OK)
{
   // Log here
}

m_topicConf = rd_kafka_topic_conf_new();
if (!m_topicConf)
{
   // Log here
   return false;
}

rd_kafka_topic_conf_set_partitioner_cb(m_topicConf, &partitioner);

m_kafka = rd_kafka_new(RD_KAFKA_PRODUCER, m_kafkaConf, errstr, sizeof(errstr));
if (!m_kafka)
{
   // Log here
   return false;
}

m_brokerList = GetBrokerListAsString();
if (rd_kafka_brokers_add(m_kafka, m_brokerList.c_str()) == 0)
{
   // Log here
   return false;
}

m_topic = rd_kafka_topic_new(m_kafka, m_outputTopicname.c_str(), m_topicConf);
if (!m_topic)
{
   ESPLOG(m_logger, CRITICAL, "Failed to create new topic: " << errstr);
   return false;
}

```
During operation the callbacks are used but they dont really anything except some logging and status conunters. Besides this only the produce function is called. During destruction I call

```

if (m_kafka)
{
   printf("1\n"); // We get here
   while (rd_kafka_outq_len(m_kafka) > 0)
   {
      printf("2\n"); // We do NOT get here
      rd_kafka_poll(m_kafka, 100);
   }
}

if (m_topic)
{
   printf("3\n"); // We get here
   rd_kafka_topic_destroy(m_topic);
}

if (m_kafka)
{
   printf("4\n"); // We get here
   rd_kafka_destroy(m_kafka);
}

if (rd_kafka_wait_destroyed(5000) == -1)
{
   printf("5\n"); // We do NOT get here
}
else
{
   printf("6\n"); // We get here
}

```

The only "special" thing im doing is that I am using my own kafka broker stub and not a real kafka broker. But if this is the issue I'm having a hard time seeing why (I can provide hex dumps of all messages going back and forth - in my simple test its only 2 metadata request and 2 responses). I know that librdkafka accepts the responses since I can produce to the topics afterwards and my stub receives the data as expected. Also I dont get any errors or other logging from librdkafka.

My first guess would be that maybe i forgot something during termination ? I just cant figure out what it is (i read the wiki).

I am running Centos 7 with g++:

> g++ (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
> Copyright (C) 2013 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Let me know if I can provide any more information that can help.

**Comment by edenhill** [comment]
I believe this was fixed in 0.9.2

**Comment by edenhill** [comment]
Can you try 0.9.2 or master? (0.9.0 is old..)

**Comment by Wramberg** [comment]
I'll give 0.9.2 a try - thanks.
