### ISSUE TITLE
Failed to produce message (Error _TIMED_OUT_QUEUE - Local: Timed out in queue) + also memory not releasing 

### ISSUE THREAD

**Issue by AKR2015** [edenhill/librdkafka#935]
Description
===========
Getting **"Failed to produce message (Error _TIMED_OUT_QUEUE - Local: Timed out in queue)"**
error while producing message. I am using v 0.9.2-ci-179. Broker version is 0.9.1

How to reproduce
================
1. Producing the contentious message to topic. Seen this message starts only after 10-12 minutes after the producer starts.  After getting this error message, i noticed my application still consume and produce the messages as usual... wondering if the message will be missing due to this error.

2. **Memory is not releasing** even if there is no message to consume and produce. That is causing memory exhausts. My application is running on windows machine with 32 GB RAM with 8 cores. 

3. Only 8 consumer and producer threads is running at this machine.

4. No unusual error or messages seen in broker logs.

Checklist
=========
Please provide the following information:

 - [X ] librdkafka version (release number or git tag): **0.9.2-ci-28**
 - [ X] Apache Kafka version: **0.9.1**
 - [ X] librdkafka client configuration: **defaults**
 - [ ] Operating system: 
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer **YES**
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka 
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
1. If you produce messages to a partition that exists but isnt available (no leader broker, insufficient isr, or the leader broker is down) then the messages will remain in internal librdkafka queues until the leader is back up or the messages time out (topic property message.timeout.ms which defaults to 5m). Failure to produce will lead to message loss.

 2. If messages cant be produced, but are queued internally, their memory wont be released until message is delivered or timed out.  Also make sure that you properly destroy messages returned by the consumer. You can also run your program with valgrind (use tests/librdkafka.suppressions) to find memory leaks.

**Comment by AKR2015** [comment]
Hello @edenhill,

thank you for quick reply.  Here is the info i see about broker, isr
Topic:Queue1    PartitionCount:12       ReplicationFactor:1     Configs:
        Topic: Queue1   Partition: 0    Leader: 7       Replicas: 7     Isr: 7
        Topic: Queue1   Partition: 1    Leader: 1       Replicas: 1     Isr: 1
        Topic: Queue1   Partition: 2    Leader: 4       Replicas: 4     Isr: 4
        Topic: Queue1   Partition: 3    Leader: 7       Replicas: 7     Isr: 7
        Topic: Queue1   Partition: 4    Leader: 1       Replicas: 1     Isr: 1
        Topic: Queue1   Partition: 5    Leader: 4       Replicas: 4     Isr: 4
        Topic: Queue1   Partition: 6    Leader: 7       Replicas: 7     Isr: 7
        Topic: Queue1   Partition: 7    Leader: 1       Replicas: 1     Isr: 1
        Topic: Queue1   Partition: 8    Leader: 4       Replicas: 4     Isr: 4
        Topic: Queue1   Partition: 9    Leader: 7       Replicas: 7     Isr: 7
        Topic: Queue1   Partition: 10   Leader: 1       Replicas: 1     Isr: 1
        Topic: Queue1   Partition: 11   Leader: 4       Replicas: 4     Isr: 4

The time is default, so wondering if the message is timeout or not delivered, it should free the memory.
I do see the memory utilization goes down here and there during process.  but slowly memory utilization get accumulated and dont get freed.

**Comment by edenhill** [comment]
You can use `debug=msg,topic` in librdkafka to see what is going on.

**Comment by AKR2015** [comment]
Thank your for your help, Memory leak issue was in my code.  After enabling the debug options, it did not help much.

Question, if the default msg time out is 5 min, i tried increasing the msg time out, but did not help that too.
to just test, i set 0(A time of 0 is infinite. )... but did not help.

**Comment by AKR2015** [comment]
resolved by increasing the msg timeout
