### ISSUE TITLE
high level consumer can not fetch data when "session.timeout.ms" set a larger value

### ISSUE THREAD

**Issue by greatt1n** [edenhill/librdkafka#938]
Hi Edenhill,
  I use high level consumer in my application,when revoke event happens the application should complete processing current data  , so I put unassign() in my main process after processing business data. 
  another , I use batch fecth method,a batch data(10000 messages) need  at least 60s to deal，so unluckly, rdkafka may assign a same partition to different consumers.
  So I set "session.timeout.ms" 300s  (default 30s) ,then my application works. but when I set this property 600s,all my application(the same group) do not work ,cant not fetch any data.

below my consumer property
partition.assignment.strategy=roundrobin
session.timeout.ms=600000
enable.auto.commit=false
auto.offset.reset=smallest
socket.keepalive.enable=true
log.connection.close=false
socket.max.fails=0

**Comment by edenhill** [comment]
The contract is for the application to call unassign() from within the rebalance callback.
When you get a rebalance callback (revoke) you should probably cancel your current dataset and throw it away.

**Comment by greatt1n** [comment]
I know I should call unassign() within the rebalance callback.but in this way , my application needs to do much rollback work,my application has much commit step(e.g. commit to database, produce messages to kafka).
and I call unassign()  outside the rebalance callback is inadvisable?at present ,it works when I set "session.timeout.ms" 300s

**Comment by edenhill** [comment]
It should be okay, yeah.

**Comment by edenhill** [comment]
Can you reproduce this with debug=cgrp,protocol,broker   and provide logs from the rebalance to the error.

**Comment by greatt1n** [comment]
I set request.timeout.ms=600000 in server.properties , and it works well.
