### ISSUE TITLE
kafkaConsumer consumes from partition but does not own it - consumer group stuck on one of two consumers

### ISSUE THREAD

**Issue by DEvil0000** [edenhill/librdkafka#939]
Description
===========
My setup:
2 brokers
2 consumers in one group
topics with replication count 2 and 2 partitions

Sometimes I had a situation where a consumer was not owning a partition anymore and the other owns both partitions (broker group status). The consumer owning both partitions worked as expected but the other consumer was still owning/consuming a partition (process states). So one of them got in a state where it was not in the consumer group anymore (based on broker information) but the internal state of the process was not changed and it was still acting like it would be in the consumer group.

How to reproduce
================
I have not found a way to reproduce this till now. I just know that both consumer processes have been in a group and worked correctly at the beginning. Then after some restarts of one of the consumer processes it seams to happen (sometimes).
Because it only happens sometimes and after some group rebalances a race condition in group handling could be the issue.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
master (39ba864f9d649e3888ec0c9ae4ef3fd73bae5ddb)
 - [x] Operating system:
ubuntu 14.04
- [x] Apache Kafka version: 
0.9.0.1
 - [ ] librdkafka client configuration:
  - [x] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue

**Comment by edenhill** [comment]
Are you doing anything special or something that takes a lot of time from your rebalance callback prior to calling un/assign()?

**Comment by DEvil0000** [comment]
I iterate over partitions and push the info to my logger queue (mutex protected). So it should be quite fast but it is not exactly predictable due to the mutex. Anyway this should be save right? Otherwise the callback would be quite useless.

**Comment by edenhill** [comment]
That should be safe, yeah.

**Comment by DEvil0000** [comment]
I was looking at #952 - I think it could be related even if I do not call any offset methods.

**Comment by edenhill** [comment]
@DEvil0000 is this still an issue?

**Comment by DEvil0000** [comment]
have not faced it again since using 7bf0bd230ad87f67d4e30c6488db24fc0f79e82b
Thu Feb 23 09:25:09 2017
but I am not sure if it is gone

**Comment by edenhill** [comment]
reopen if reseen
