### ISSUE TITLE
Question: Testing Status for Apache Kafka 0.8 & 0.9 & 0.10

### ISSUE THREAD

**Issue by javierholguera** [edenhill/librdkafka#941]
The README states that the status for Apache Kafka 0.8 & 0.9 & 0.10 support is "testing". Is that the case, or can we safely use the library for production?

Thanks.

**Comment by edenhill** [comment]
Ooh, that's a mistake, it is stable for use with any Kafka version >= 0.8

**Comment by javierholguera** [comment]
Cool thanks for the quick answer!
