### ISSUE TITLE
Is partition auto creation supported by librdkafka?

### ISSUE THREAD

**Issue by jinzh** [edenhill/librdkafka#942]
Hey,
I want to create multiple partitions when creating a topic by librdkafka,
Try setting the following, but fail.
//
iRet = conf->set("num.partitions", "3", errstr);
if (iRet != RdKafka::Conf::CONF_OK)
{
	printf("tconf->set error:%d\n", iRet);
}
//

Does librdkafka support the automatic creation of partitions?

**Comment by edenhill** [comment]
Nope, not yet.
Work is being done on the broker to support this, in KIP-4

**Comment by jinzh** [comment]
Thanks!

**Comment by hzhxxx** [comment]
[root@six test]# cd /usr/local/kafka_2.11-0.10.0.1/
[root@six kafka_2.11-0.10.0.1]# ls
bin  config  libs  LICENSE  logs  NOTICE  site-docs
[root@six kafka_2.11-0.10.0.1]# cd bin/
[root@six bin]# pwd
/usr/local/kafka_2.11-0.10.0.1/bin
[root@six bin]# ls
connect-distributed.sh               kafka-replica-verification.sh
connect-standalone.sh                kafka-run-class.sh
kafka-acls.sh                        kafka-server-start.sh
kafka-configs.sh                     kafka-server-stop.sh
kafka-console-consumer.sh            kafka-simple-consumer-shell.sh
kafka-console-producer.sh            kafka-streams-application-reset.sh
kafka-consumer-groups.sh             kafka-topics.sh
kafka-consumer-offset-checker.sh     kafka-verifiable-consumer.sh
kafka-consumer-perf-test.sh          kafka-verifiable-producer.sh
kafka-mirror-maker.sh                windows
kafka-preferred-replica-election.sh  zookeeper-security-migration.sh
kafka-producer-perf-test.sh          zookeeper-server-start.sh
kafka-reassign-partitions.sh         zookeeper-server-stop.sh
kafka-replay-log-producer.sh         zookeeper-shell.sh

kafka server have best tools.

**Comment by edenhill** [comment]
Yeah, use `bin/kafka-topics.sh --zookeeper $ZK_ADDR --create --topic $TOPIC --replication-factor 3 --partitions 3 ..`
