### ISSUE TITLE
about librdkafka HA(High Availability)

### ISSUE THREAD

**Issue by hzhxxx** [edenhill/librdkafka#943]
Description
===========

we use three brokers ,but kill one of broker and down ,librdkafka do not  automatic exclude  the down brokers,finish failover。the process with librdkafka entry  endless loop.
use librdkafka version 0.92(C langage)

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [x] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Can you elaborate on:
 - a: what do you expect to happen, in detial
 - b: what behaviour you are seeing
 - c: how you detect the difference between a and b

**Comment by hzhxxx** [comment]
a.  librdkafka can automatic exclude the down brokers beause kafka server has selected a leader to manager partitions
b. the process with librdkafka entry endless loop.
see step:
1. create a producer
 ./rdkafka_example -P -t librdkafka -b six.dev3:9092,six.dev4:9092,Slave01.Hadoop:9092,Slave02.Hadoop:9092

2.  create a consumer
./rdkafka_example -C -t librdkafka -b six.dev3:9092,six.dev4:9092,Slave01.Hadoop:9092,Slave02.Hadoop:9092 -p 0,1,2,3

3. start consume and produce
% Sent 2 bytes to topic librdkafka partition -1
% Message delivered (2 bytes): 66
88
% Sent 2 bytes to topic librdkafka partition -1
% Message delivered (2 bytes): 77
99
% Sent 2 bytes to topic librdkafka partition -1
% Message delivered (2 bytes): 88

00000000: 37 37                                            77              
% Consumer reached end of librdkafka [0] message queue at offset 5
% Message (offset 5, 2 bytes):
Message Payload hexdump (2 bytes):
00000000: 38 38                                            88              
% Consumer reached end of librdkafka [0] message queue at offset 6

4.  kill one of kafka brokers
[root@six bin]# jps
20723 Kafka
[root@six bin]# kill -9 20723

5.  the producer entry endless loop
1481245058.803 RDKAFKA-3-FAIL: rdkafka#producer-1: six.dev4:9092/3: Receive failed: Disconnected
1481245058.803 RDKAFKA-3-ERROR: rdkafka#producer-1: six.dev4:9092/3: Receive failed: Disconnected
1481245058.913 RDKAFKA-3-FAIL: rdkafka#producer-1: six.dev4:9092/3: Connect to ipv4#192.168.71.15:9092 failed: Connection refused
1481245058.913 RDKAFKA-3-ERROR: rdkafka#producer-1: six.dev4:9092/3: Connect to ipv4#192.168.71.15:9092 failed: Connection refused
1481245059.930 RDKAFKA-3-FAIL: rdkafka#producer-1: six.dev4:9092/3: Connect to ipv4#192.168.71.15:9092 failed: Connection refused
1481245059.930 RDKAFKA-3-ERROR: rdkafka#producer-1: six.dev4:9092/3: Connect to ipv4#192.168.71.15:9092 failed: Connection refused
1481245060.941 RDKAFKA-3-FAIL: rdkafka#producer-1: six.dev4:9092/3: Connect to ipv4#192.168.71.15:9092 failed: Connection refused

**Comment by hzhxxx** [comment]
a broker down is normal in kafka cluster ,currently the librdkafka can automatic reconnect the brokers,but the down broker is invalid  for a long time ,then entry endless loop. the librdkafka should automatic exclude the down brokers,finish failover.

**Comment by edenhill** [comment]
as soon as a new leader is elected for the consumed partitions librdkafka will switch to the new leader and consume from it.
You can verify when this happens with `-X debug=topic`.

The repeated "Connection refused" logs are just informatory.

**Comment by edenhill** [comment]
You can use `rdkafka_example -b brokers.. -L -t librdkafka` to see what the current leader for a partition is.
It is possible, if you have replication-factor=1, that there is no backup leader for your partition

**Comment by hzhxxx** [comment]
[root@six bin]# ./kafka-topics.sh --describe --topic librdkafka --zookeeper six.dev1:2181,six.dev3:2181,six.dev4:2181
Topic:librdkafka        PartitionCount:4        ReplicationFactor:2     Configs:
        Topic: librdkafka       Partition: 0    Leader: 5       Replicas: 5,3   Isr: 5
        Topic: librdkafka       Partition: 1    Leader: 2       Replicas: 2,4   Isr: 4,2
        Topic: librdkafka       Partition: 2    Leader: 5       Replicas: 3,5   Isr: 5
        Topic: librdkafka       Partition: 3    Leader: 4       Replicas: 4,2   Isr: 4,2

**Comment by hzhxxx** [comment]
currently, not the consumer  but the producer entry endless loop

**Comment by hzhxxx** [comment]
currently, both the consumer and the producer entry endless loop,always reconnect the down broker.
all business messages dot not send and receive

**Comment by edenhill** [comment]
It will attempt to reconnect to the down broker forever, but this will not effect operation, if there is a new leader for the partition it will continue to consume or produce.

**Comment by hzhxxx** [comment]
ok.thanks,we continue to test.

**Comment by hzhxxx** [comment]
1. ./rdkafka_performance -P -t librdkafka -b six.dev3:9092,six.dev4:9092,Slave01.Hadoop:9092,Slave02.Hadoop:9092
2.  kill broker
[root@six bin]# jps
17467 Kafka
[root@six bin]# kill -9 17467
3. show status
[root@six examples]# ps -ef|grep "24359"
root       529 26871  0 09:01 pts/3    00:00:00 grep --color=auto 24359
root     24359  2158 91 08:54 pts/1    00:06:23 ./rdkafka_performance -P -t librdkafka -b six.dev3:9092,six.dev4:9092,Slave01.Hadoop:9092,Slave02.Hadoop:9092
[root@six examples]# top -H -p 24359
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND        
**_24359 root      20   0  484064 125556   2180 S 66.3  0.4   5:06.12 rdkafka_perfo+ 
24365 root      20   0  484064 125556   2180 S 10.3  0.4   0:44.28 rdkafka_perfo+_** 
24362 root      20   0  484064 125556   2180 S  5.3  0.4   0:24.37 rdkafka_perfo+ 
24364 root      20   0  484064 125556   2180 S  5.0  0.4   0:24.00 rdkafka_perfo+ 
24360 root      20   0  484064 125556   2180 S  0.7  0.4   0:03.02 rdkafka_perfo+ 
24361 root      20   0  484064 125556   2180 S  0.0  0.4   0:00.44 rdkafka_perfo+ 
24363 root      20   0  484064 125556   2180 S  0.0  0.4   0:02.59 rdkafka_perfo+

the  rdkafka_performance entry endless loop

**Comment by edenhill** [comment]
rdkafka_performance will continue to operate using remaining brokers if one goes down.
