### ISSUE TITLE
[question] cannot install on official PHP Docker image

### ISSUE THREAD

**Issue by miglanc** [edenhill/librdkafka#944]
Thanks in advance with any help!

Description
===========

I have problem with installing librdkafka on the latest official PHP docker image.

The last lines of the console output when building an image are the following:

```
/usr/bin/ld: rdkafka.o: relocation R_X86_64_TPOFF32 against `rd_kafka_last_error_code' can not be used when making a shared object; recompile with -fPIC
rdkafka.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
../mklove/Makefile.base:86: recipe for target 'librdkafka.so.1' failed
make[1]: *** [librdkafka.so.1] Error 1
make[1]: Leaving directory '/usr/src/librdkafka/src'
Makefile:20: recipe for target 'libs' failed
make: *** [libs] Error 2
```

I am attaching full output here: [output.txt](https://github.com/edenhill/librdkafka/files/639604/output.txt)

I didn't have any problems with building this image about 2 weeks ago on the same machine but using some older image.

How to reproduce
================

My Dockerfile contents is following:

```Dockerfile
FROM php:7.1.0-cli

ENV LIBRDKAFKA_VERSION v0.9.2

RUN apt-get clean && apt-get update && \
    mkdir -p /usr/src/librdkafka && \
    curl -L --silent https://github.com/edenhill/librdkafka/archive/debian/${LIBRDKAFKA_VERSION}.tar.gz | tar -xz --strip=1 -C /usr/src/librdkafka && \
    apt-get -y install \
    build-essential \
    libc6-dev \
    python-dev \
    zlib1g-dev \
    && cd /usr/src/librdkafka && ./configure && make && sudo make install
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): v0.9.2
 - [x] Apache Kafka version: does not matter
 - [x] librdkafka client configuration:
 - [x] Operating system: [official PHP Docker image (Debian Jessie)](https://github.com/docker-library/php/blob/173945670390f6595da8f93ae46b442167ff05be/7.1/Dockerfile)
 - [x] Using the legacy Consumer no, does not matter
 - [x] Using the high-level KafkaConsumer no, does not matter
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka, does not matter, I think
 - [x] Provide broker log excerpts, does not matter
 - [x] Critical issue, does not matter

I assume it does not matter but I have the same problem both on:

(1) My laptop running Lubuntu - Linux 4.4.0-47-generic #68-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux.
(2) An VPS in OVH Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-100-generic x86_64).

Both my laptop and VPS have the same docker version:

Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 OS/Arch:      linux/amd64

**Comment by edenhill** [comment]
There are a couple of CPPFLAGS/CFLAGS that arent set by librdkafka but must be from your build system or something:
`-fstack-protector-strong -fpic -fpie`

librdkafka later adds `-fPIC`

My guess is that  `-fpic ` and `-fPIC` dont play nice together, I suggest removing the external C*FLAGS (-fstack-pr.. -fpic etc)

**Comment by miglanc** [comment]
> I suggest removing the external C*FLAGS (-fstack-pr.. -fpic etc)

What is that mean? What should I do exactly? I mean, how can I remove these?

**Comment by edenhill** [comment]
I'm sorry but I don't know where they come from.

**Comment by EvgenyOrekhov** [comment]
@miglanc Put this right above the `RUN` command:

```dockerfile
ENV CFLAGS ""
ENV CPPFLAGS ""
ENV LDFLAGS ""
```

**Comment by edenhill** [comment]
The problem is mixing -fpic and -fPIC, so I guess librdkafka's configure could skip its -fPIC if -fpic has already been specified.
Either by compiling and linking to check if -fPIC works, or simply string-matching if -fpic has been specified.
Neither are great.

**Comment by miglanc** [comment]
@EvgenyOrekhov Thanks, that is exactly what I have done as a workaround and it works. 

@edenhill An issue within PHP official docker image has beed opened here https://github.com/docker-library/php/issues/347#issuecomment-266224972 so I think this issue can be closed.

Thanks for help guys!
