### ISSUE TITLE
can't set message.timeout.ms config param

### ISSUE THREAD

**Issue by johnrgregg3** [edenhill/librdkafka#946]
Description
===========

Using 0.9.1, with the confluent python wrapper. In python, if I do the following:

conf = {'bootstrap.servers': '1.2.3.4',
        'message.timeout.ms': 8000,
        'session.timeout.ms': 3000}

kafka_producer = Producer(**conf)

I get this Exception:

Traceback (most recent call last):
  File "fred.py", line 26, in <module>
    kafka_producer = Producer(**conf)
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "message.timeout.ms""}

Even though message.timeout.ms appears in CONFIGURATION.md and rdkafka_conf.c.

The problem, I think, is this. The variable message.timeout.ms certainly does appear in rdkafka_conf.c, but its scope is _RK_TOPIC|_RK_PRODUCER. Since I am creating a Producer, this should work, right? But a quick grep through the code shows that no one ever sets the _RK_PRODUCER flag in the scope argument to rd_kafka_anyconf_set(). So we are guaranteed never to see a config parameter whose scope was set to _RK_PRODUCER. For that matter, it looks like no one ever calls rd_kafka_topic_conf_set(), the only place that calls rd_kafka_anyconf_set(_RK_TOPIC,...) so it looks like _RK_TOPIC is never used either.

Although I happen to be using the confluent python wrapper, I think this is a problem with the underlying librdkafka, and would show up anytime someone tried to set message.timeout.ms.

How to reproduce
================

see above.

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):0.9.1
 - [ ] Apache Kafka version: N/A, I never get as far as connecting with a broker
 - [ ] librdkafka client configuration: see above
 - [ ] Operating system: Ubuntu 14.04
 - [ ] Using the legacy Consumer N/A, Producer side only.
 - [ ] Using the high-level KafkaConsumer N/A, Producer side only.
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka see above
 - [ ] Provide broker log excerpts N/A, I never get as far as connecting with a broker
 - [ ] Critical issue: not sure yet. Maybe there is a workaround?

**Comment by edenhill** [comment]
That's a topic property so you'll need to set in the "default.topic.config” sub-dict of your conf dict.

**Comment by johnrgregg3** [comment]
OK, that worked:

        'default.topic.config': {'message.timeout.ms': 8000},

But I can't see how. I don't see 'default.topic.config' in CONFIGURATION.md or in rdkafka_conf.c. Are there other parameters that are only set in this subdict?

I do see, however, in confluent_kafka.c in the confluent code where it calls rd_kafka_topic_conf_set(), so I was wrong above when I said no one ever calls it. I also see where the confluent code explicitly looks for default.topic.config inline in the code:

                if (!strcmp(k, "default.topic.config")) {
                        if (populate_topic_conf(tconf, k, vo) == -1) {

So is this a confluent-only (sub)section of config, not directly supported by the underlying librdkafka library?

**Comment by edenhill** [comment]
"default.topic.config" is a python client thing to abstract the need for a topic-specific topic configuration object (as in librdkafka).
What it does under the hood is set up a topic config object and then applying that as the default topic config object in librdkafka.

**Comment by edenhill** [comment]
This isn't directly straight forward and many people struggle with these topic properties, so I'm thinking we might just want to allow for fallthru: try setting a property on the topic conf first, if that fails try the global conf, if that fails return an error. (This is what tools like kafkacat do)
