### ISSUE TITLE
Question around Broker version compatibility and api.version.request=true

### ISSUE THREAD

**Issue by vin-d** [edenhill/librdkafka#949]
Description
===========
I read on this wiki page [NOTE: As more users move to broker version >= 0.10.0.0 the default value of api.version.request will be changed to true in librdkafka. Please read future release notes to know when this happens since it will affect users of <0.10.0 brokers.
](https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility)

I have also read the [Feature-discovery](https://github.com/edenhill/librdkafka/blob/4a58dd60b132432b4bcaeae52c22b892bf8d01e3/INTRODUCTION.md#feature-discovery) section
but still cannot get to know if the api.version.request=true must be input by myself in the configuration of my consumers and producers or if this is done by the library automatically.

I'm using the last librdkafka and 10.0.0 and 10.0.1 brokers

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ 7f12b7f0c93609acbd4b2119766a99a865fea6dd] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
For now you need to specify api.version.request=true yourself since it defaults to false.
This will change in later versions of librdkafka.

**Comment by vin-d** [comment]
Thank you.
