### ISSUE TITLE
dynamic linking doesn't work

### ISSUE THREAD

**Issue by ghost** [edenhill/librdkafka#95]
Hello,

If I try to use dynamic link I always get undefined references.

I installed the libraries in /usr/local/lib ane try to compile rdkafka_example.c using

gcc -I/usr/local/include/librdkafka -L/usr/local/lib -lrdkafka rdkafka_example.c

But I get link errors

/tmp/cczYMsjA.o: In function `rd_kafka_message_errstr':
rdkafka_example.c:(.text+0x31): undefined reference to`rd_kafka_err2str'
/tmp/cczYMsjA.o: In function `logger':
rdkafka_example.c:(.text+0x1f0): undefined reference to`rd_kafka_name'
/tmp/cczYMsjA.o: In function `msg_delivered':
rdkafka_example.c:(.text+0x263): undefined reference to`rd_kafka_err2str'
/tmp/cczYMsjA.o: In function `msg_consume':
rdkafka_example.c:(.text+0x2e7): undefined reference to`rd_kafka_topic_name'
rdkafka_example.c:(.text+0x357): undefined reference to `rd_kafka_topic_name'
/tmp/cczYMsjA.o: In function`metadata_print':
rdkafka_example.c:(.text+0x5ba): undefined reference to `rd_kafka_err2str'
rdkafka_example.c:(.text+0x6fc): undefined reference to`rd_kafka_err2str'
/tmp/cczYMsjA.o: In function `sig_usr1':
rdkafka_example.c:(.text+0x765): undefined reference to`rd_kafka_dump'
/tmp/cczYMsjA.o: In function `main':
rdkafka_example.c:(.text+0x7ea): undefined reference to`rd_kafka_conf_new'
rdkafka_example.c:(.text+0x7f3): undefined reference to `rd_kafka_topic_conf_new'
rdkafka_example.c:(.text+0x887): undefined reference to`rd_kafka_conf_set'
.....

**Comment by bhanushrestha** [comment]
I am still getting same compilation as above while trying to build with gcc compiler the librdkafka cpp example code.

./Librdkafkaexample.o: In function `metadata_print':
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:91: undefined reference to `RdKafka::err2str(RdKafka::ErrorCode)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:121: undefined reference to `RdKafka::err2str(RdKafka::ErrorCode)'
./Librdkafkaexample.o: In function `main':
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:258: undefined reference to `RdKafka::Conf::create(RdKafka::Conf::ConfType)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:259: undefined reference to `RdKafka::Conf::create(RdKafka::Conf::ConfType)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:411: undefined reference to `RdKafka::get_debug_contexts()'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:411: undefined reference to `RdKafka::version()'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:411: undefined reference to `RdKafka::version_str()'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:476: undefined reference to `RdKafka::Producer::create(RdKafka::Conf*, std::string&)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:488: undefined reference to `RdKafka::Topic::create(RdKafka::Handle*, std::string const&, RdKafka::Conf*, std::string&)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:513: undefined reference to `RdKafka::err2str(RdKafka::ErrorCode)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:542: undefined reference to `RdKafka::Consumer::create(RdKafka::Conf*, std::string&)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:554: undefined reference to `RdKafka::Topic::create(RdKafka::Handle*, std::string const&, RdKafka::Conf*, std::string&)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:566: undefined reference to `RdKafka::err2str(RdKafka::ErrorCode)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:602: undefined reference to `RdKafka::Producer::create(RdKafka::Conf*, std::string&)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:615: undefined reference to `RdKafka::Topic::create(RdKafka::Handle*, std::string const&, RdKafka::Conf*, std::string&)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:630: undefined reference to `RdKafka::err2str(RdKafka::ErrorCode)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:651: undefined reference to `RdKafka::wait_destroyed(int)'
./Librdkafkaexample.o: In function `ExampleEventCb::event_cb(RdKafka::Event&)':
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:153: undefined reference to `RdKafka::err2str(RdKafka::ErrorCode)'
/home/lenovo/cpp-workspace/LibrdKafkaTest/Debug/../Librdkafkaexample.cpp:170: undefined reference to `RdKafka::err2str(RdKafka::ErrorCode)'


Even though all the libraries are included and the linkers as given in documentation i get this error. Can anyone help?

**Comment by edenhill** [comment]
Please provide your linking command line.

**Comment by bhanushrestha** [comment]
@edenhill  I used Eclipse IDE that generated this command on console:
g++  -o "LibrdKafkaTest"  ./Librdkafkaexample.o   -lrdkafka -lpthread -lrt

I set the linker to have -lz as well as per your documentation in the github project but that gave error as :

_/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status_

**Comment by edenhill** [comment]
You dont seem to be linking with the C++ library, try: -lrdkafka++

**Comment by bhanushrestha** [comment]
Thanks a ton @edenhill . It worked and now the project is building. Thanks again for the quick response.

**Comment by foreign** [comment]
Hello,
I run the commands below but gcc gives error: rdkafka.h: No such file or directory
Please help.

./configure --prefix=/home/gateway/kafkalib
 make
 make install

I created kafka.conf under ld.so.conf.d folder. (content: /home/gateway/kafkalib) 
echo $LD_LIBRARY_PATH
/usr/local/lib:/home/gateway/kafkalib/lib

gcc -O3 Wall -lrdkafka -lz -lpthread -lrt kafkaexample.c

**Comment by edenhill** [comment]
You need to put the libraries at the end of the command line:
`gcc -O3 -Wall kafkaexample.c -lrdkafka -lz -lpthread -lrt `

**Comment by foreign** [comment]
The same error occurs again.

**Comment by edenhill** [comment]
Would you mind pasting the actual error message?

**Comment by foreign** [comment]
Line 11: #include "rdkafka.h"

Error : 
kafkaexample.c:11:21: error: rdkafka.h: No such file or directory

**Comment by edenhill** [comment]
If you've installed librdkafka to a non-standard location you'll also need to provide the include path to the compiler, e.g.:

`gcc -O3 -Wall -I/home/gateway/kafkalib/include/librdkafka kafkaexample.c -lrdkafka -lz -lpthread -lrt`

**Comment by foreign** [comment]
Error :
/usr/bin/ld: cannot find -lrdkafka
collect2: ld returned 1 exit status

**Comment by edenhill** [comment]
These are pretty basic C compilation/building concepts and are outside the scope of librdkafka open source support.

`gcc -O3 -Wall -I/home/gateway/kafkalib/include/librdkafka kafkaexample.c -L/home/gateway/kafkalib/lib -lrdkafka -lz -lpthread -lrt`

**Comment by foreign** [comment]
Final code is like below and it worked successfully.
Thanks for your help and quick response.

gcc -O3 -Wall  -L/home/gateway/kafkalib/lib -lrdkafka -lz -lpthread -lrt -I/home/gateway/kafkalib/include/librdkafka kafkaexample.c

**Comment by edenhill** [comment]
You have an incorrect include path: `-I/usr/local/include/librdkafka`, it should be without the librdkafka part, so: `-I/usr/local/include`

**Comment by singhgurpreetcs** [comment]
Hi Team, 
I am getting below error while compiling producer code using C kafka library.

[root@EC2AMAZ-ROPJ2S kafka2]# gcc -Wall -o producer  producer.c -I/usr/bin/include  -lrdkafka -lz -lpthread -lrt
producer.c: In function ‘main’:
producer.c:83:35: warning: implicit declaration of function ‘rd_kafka_message_new’; did you mean ‘rd_kafka_queue_new’? [-Wimplicit-function-declaration]
   rd_kafka_message_t *rkmessage = rd_kafka_message_new();
                                   ^~~~~~~~~~~~~~~~~~~~
                                   rd_kafka_queue_new
producer.c:83:35: warning: initialization of ‘rd_kafka_message_t *’ {aka ‘struct rd_kafka_message_s *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
producer.c:85:3: warning: implicit declaration of function ‘rd_kafka_message_set_topic’; did you mean ‘rd_kafka_message_status’? [-Wimplicit-function-declaration]
   rd_kafka_message_set_topic(rkmessage, topic);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
   rd_kafka_message_status
producer.c:87:3: warning: implicit declaration of function ‘rd_kafka_message_set_payload’; did you mean ‘rd_kafka_message_set_headers’? [-Wimplicit-function-declaration]
   rd_kafka_message_set_payload(rkmessage, (void *) messages[i], message_lens[i]);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
   rd_kafka_message_set_headers
/tmp/cckqSz4V.o: In function `main':
producer.c:(.text+0x21a): undefined reference to `rd_kafka_message_new'
producer.c:(.text+0x238): undefined reference to `rd_kafka_message_set_topic'
producer.c:(.text+0x266): undefined reference to `rd_kafka_message_set_payload'
