### ISSUE TITLE
Is RD_KAFKA_RESP_ERR__AUTHENTICATION error signaled through error_cb?

### ISSUE THREAD

**Issue by kparadkar** [edenhill/librdkafka#950]
While going through [Issue 64]((https://github.com/edenhill/librdkafka/issues/64)) I found the list of error codes signaled through error_cb and noticed that RD_KAFKA_RESP_ERR__AUTHENTICATION was not under it. If error_cb doesn't signal it then how does this error get propagated to application?

I am basically trying to find the error reporting mechanism when I try to write to a topic I dont have permission for .. and where to look for errors if any?

**Comment by edenhill** [comment]
Connection/broker-level authentication failures are triggered with ERR__AUTHENTICATION through error_cb.
But producing to a topic you dont have access to will be signalled through the delivery report cb (dr_msg_cb/dr_cb) with an error code set by the broker, probably RD_KAFKA_RESP_ERR_TOPIC_AUTHORIZATION_FAILED

**Comment by archanapujar** [comment]
If a consumer does not have permission on a topic, how is it notified and what is the expected error code?
