### ISSUE TITLE
[KafkaApi-35] error when handling request Name: TopicMetadataRequest

### ISSUE THREAD

**Issue by wking1986** [edenhill/librdkafka#951]
Description
===========
Hello edenhill ：
We use the librdkafka to get kafka metadata However, due to a number of illegal mixed topic, which appeared ERROR TopicMetaData, Will this time libkafka will throw out the abnormal or return to other legitimate topic Lead = -1? 

![image](https://cloud.githubusercontent.com/assets/4937857/21144284/0b0be084-c185-11e6-8e3a-74c6d4ee2690.png)

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [0.9.2] librdkafka version (release number or git tag):
 - [0.10.0] Apache Kafka version: 0.10.0
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by wking1986** [comment]
@edenhill，Thank you for your reply，
Other legitimate topic will return topic partition leader = -1?

**Comment by edenhill** [comment]
Or a valid leader, if there is one.
