### ISSUE TITLE
Before produce msg to  kafka, how to quickly determine which partition is valid?

### ISSUE THREAD

**Issue by DavidLiuXh** [edenhill/librdkafka#954]
Description
===========

Before produce msg to  kafka, how to quickly determine which partition is valid?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There is the `rd_kafka_topic_partition_available()` that does that, but it must only be called from within a partitioner callback, not from the main code.

Otherwise you'll have to call rd_kafka_metadata() for your topic and extract the topic.partition_cnt

**Comment by DavidLiuXh** [comment]
Thanks for @edenhill .
