### ISSUE TITLE
Debian Package build target

### ISSUE THREAD

**Issue by alfechner** [edenhill/librdkafka#958]
I'd like to install `librdkafka` from a Debian package. Packages in Debian/Ubuntu repository are slightly outdated. So I'd like to build them myself. While there is a target for building `rpm` packages there is non for Debian.

I also cannot find any information about the Debian package building process though there seem to be some branches dedicated for this task.

So is there a easy way to build a Debian package from this source?

**Comment by edenhill** [comment]
Confluent provides up-to-date Debian packages, see here for the 0.9.2 release:
http://docs.confluent.io/3.1.1/installation.html#installation-apt

If you want to do it manually you should check out the debian branch and use git-buildpackage or similar.

**Comment by alfechner** [comment]
Thank you for your quick response.

I found the current version in the confluent repository you mentioned.

Did I miss this information somewhere in the README? If so adding this hint would be quite useful.
