### ISSUE TITLE
Use key to select partition

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#959]
Description
===========
I would like the partitioner to select a consistent partition using the key I provide when producing a message as in:

rd_kafka_produce(topic_handle,
                  RD_KAFKA_PARTITION_KEY, <----- partitioning using the key
                  RD_KAFKA_MSG_F_FREE,
                  (void*) messageBuffer, msgLen,
                  &key,   <---- Use the key to choose partition
                 sizeof(key),
                  &produceError);

This allows me to publish to a consist partition which in turn preserves the order in which messages are produced and then received by the consumer.

How might I do this?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Hi,
this is what the partitioner is for, it takes a key and the partition count and returns an output partition.
There are a couple of builtin ones and a consistent random partitioner happens to be the default:
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1480

The partitioner is only employed if you specify `RD_KAFKA_PARTITION_UA` (unassigned) as partition to te produce() call.

**Comment by blandings** [comment]
Thanks for your reply.

For clarity, do you mean that if I use RD_KAFKA_PARTITION_UA, *and* supply the key, then that key is used for consistent mapping of message to specific partition?

I don't need to specifically call  rd_kafka_topic_conf_set_partitioner_cb and setup the producer to rd_kafka_msg_partitioner_consistent_random?

**Comment by edenhill** [comment]
Yes, that's right. RD_KAFKA_PARTITION_UA causes the producer to call the configured partitioner for each message (regardless of key - you can map a null key as you wish).

And yes, if you are happy with the default partitioner (consistent random) you dont need to change it.

**Comment by blandings** [comment]
Thank you!
