### ISSUE TITLE
Dynamic Link Doesn't Work

### ISSUE THREAD

**Issue by studdykid** [edenhill/librdkafka#960]
Description
===========

I have tried many times to compile this consumer_example and it doesn't work.

$ g++ -lz -lpthread -lrt rdkafka_consumer_example.cpp -lrdkafka++
/data/opt/lib/../lib64/librdkafka++.so: undefined reference to `rd_kafka_get_offsets'
/data/opt/lib/../lib64/librdkafka++.so: undefined reference to `rd_kafka_position'
/data/opt/lib/../lib64/librdkafka++.so: undefined reference to `rd_kafka_mem_free'
/data/opt/lib/../lib64/librdkafka++.so: undefined reference to `rd_kafka_resume_partitions'
/data/opt/lib/../lib64/librdkafka++.so: undefined reference to `rd_kafka_pause_partitions'
collect2: error: ld returned 1 exit status

Really hope you can help! Thank you so much!!!

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ 0.9.0 ] librdkafka version (release number or git tag):
 - [ kafka_2.10-0.10.1.0 ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ linux ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ x ] Critical issue

**Comment by edenhill** [comment]
Your librdkafka version is too old, upgrade to 0.9.2

**Comment by studdykid** [comment]
Thanks Eden, I've changed (git checkout to) to 0.9.2.x, but the exactly same error occurred.

**Comment by edenhill** [comment]
I'm guessing you have an old version of librdkafka installed that the compiler&linker picks up.

**Comment by studdykid** [comment]
Thank you again, Eden. Then I successfully installed (make install) as instructed. And now it turned with 1 last error:
g++ -lz -lpthread -lrt rdkafka_consumer_example.cpp -lrdkafka++             
/data/opt/lib/../lib64/librdkafka++.so: undefined reference to `rd_kafka_get_offsets'
collect2: error: ld returned 1 exit status

**Comment by edenhill** [comment]
rd_kafka_get_offsets() was added in librdkafka 0.9.1, so I still think you are linking the wrong library somehow.
Try to locate all existing librdkafka.so.1 and librdkafkacpp.so.1 files on the system and check their file dates to figure out what needs to be removed.

**Comment by studdykid** [comment]
Hi Eden, Thank you so much for your response! It works well with your instructions. : )
