### ISSUE TITLE
Undefined reference to static const int RdKafka::Producer::RK_MSG_FREE

### ISSUE THREAD

**Issue by bbfgelman1** [edenhill/librdkafka#961]
Description
===========
It is not possible to pass by const reference any of the `static const int` values declared in the C++ classes. Doing so generates an undefined reference error at link time.

How to reproduce
================

```c++
# include "rdkafkacpp.h"
void foo(const int&) {}

int main(int, char**) {
  foo(RdKafka::Producer::RK_MSG_FREE);
  return 0;
}
```
```sh
g++ -g -O0 -lrdkafka++ -lrdkafka main.cpp
In function `...':
main.cpp: undefined reference to `RdKafka::Producer::RK_MSG_COPY'
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 6c7c8644c01c159c8a164fa0ed0493741b54cdc7
 - [ ] Apache Kafka version: N/A
 - [ ] librdkafka client configuration: N/A
 - [ ] Operating system: N/A
 - [ ] Using the legacy Consumer: N/A
 - [ ] Using the high-level KafkaConsumer: N/A
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka: N/A
 - [ ] Provide broker log excerpts: N/A
 - [ ] Critical issue: N/A

**Comment by bbfgelman1** [comment]
https://github.com/edenhill/librdkafka/pull/962

**Comment by edenhill** [comment]
I can't reproduce this, what GCC version?

**Comment by bbfgelman1** [comment]
I'm using GCC 4.8.2. The problem only happens with `-O0`.

**Comment by edenhill** [comment]
Okay. Why would you need a reference to these constants anyway?

**Comment by bbfgelman1** [comment]
To pass them to generated and/or template code that takes things by const reference. I ran into this when trying to use variadic templates and perfect forwarding to forward these constants to an RdKafka method.
