### ISSUE TITLE
destroy producer will be  blocked more than 10 minutes

### ISSUE THREAD

**Issue by byd913** [edenhill/librdkafka#963]
Description
===========
When I destroy producer, the thread will be blocked more than 10 minutes.
I create producer and topic like this.
`producer_.reset(RdKafka::Producer::create(gconf_.get(), errstr));
topic_.reset(RdKafka::Topic::create(producer_.get(), topic_name_, tconf_.get(), errstr));`

I destroy producer and topic like this.
`  topic_.reset();
    CINFO_LOG("reset topic_ ok");
    producer_.reset();                                                                                                                                                      
    CINFO_LOG("reset producer_ ok");
    gconf_.reset();
    CINFO_LOG("reset gconf_ ok");
    tconf_.reset();
    CINFO_LOG("reset tconf_ ok");
`

destroy log.
`
2016-12-21 08:17:09 reset topic_ ok
2016-12-21 08:28:21 reset producer_ ok
`

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.1
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
It is not clear what your .reset() logic does, Im guessing it deletes the objects?

If there are outstanding messages waiting to be produced in internal librdkafka queues or in-flight to the broker, then librdkafka will wait for those messages to either get succesfully produced, or fail permanently after retries/timeouts. The default message timeout is 5 minutes.

**Comment by byd913** [comment]
Yes, .reset() means delete the objects.

Is there any params can change the default message timeout?

I use librdkafka to produce data to kafka servers, but sometimes it can not write any message to kafka server(log shows `queue is full`). I log event_cb and dr_cb callback, nothing useful information can be found.
When this error happens, I use `netstat` to check the connections with kafka server, but the connections  still exist.

I can not find why this happen. So I want reinitialize kafka when this error happens, but when I delete producer objects, It blocks long time.

**Comment by edenhill** [comment]
You can change the message timeout with the topic property `message.timeout.ms`, either set it on a per-topic config object, or use the default_topic_conf to make it apply on all your topics.

Reinitializing librdkafka when the queue gets full really doesn't solve any problems, it just requires you to resend everything and possibly loosing or duplication messages.
If you enable a stats_cb you can see where messages are held up by looking at the various queue points inside library - search the JSON output for "q_cnt" to find the queues with large counts.
