### ISSUE TITLE
consuming ability comes to lower

### ISSUE THREAD

**Issue by zdftju** [edenhill/librdkafka#964]
Description
===========

hello edenhill,i met a serious problem these days, the consuming ability becomes too low suddenly,and the java API is normal, i doubt that if i do something wrong when i used c API ,how can this happened? i hope to get some advice ,thank you!

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by zdftju** [comment]
kafka version 0.8.2.1

**Comment by edenhill** [comment]
Please fill out the Checklist above (use the edit pencil).

You also need to provide some more information, there is nothing to go on.

**Comment by edenhill** [comment]
Please provide the following information (and no less):
 * librdkafka version
 * librdkafka configuration
 * operating system and version
 * your consumer source code (relevant parts that make use of the librdkafka API
