### ISSUE TITLE
How to set offset in KafkaConsumer

### ISSUE THREAD

**Issue by smartcat2010** [edenhill/librdkafka#965]
In legacy code, RdKafka::Consumer::start could specify start_offset such as RdKafka::Topic::OFFSET_BEGINNING or RdKafka::Topic::OFFSET_END, ... 
However, in RdKafka::KafkaConsumer, it seems not provide interface to set the starting offset. Is there any way to set this offset?

**Comment by edenhill** [comment]
On my phone now so will keep it short. 

If you register a rebalance callback you can specify the start offset for each partition in the vector you pass to assign()

**Comment by smartcat2010** [comment]
@edenhill Thanks a lot! It works! I found this offset is 0, 1, 2, ...N. It is not the kafka "offset" which is the "byte" offset. Does libkafka use some logic to hide the original "byte" offset?

**Comment by edenhill** [comment]
Kafka moved from byte offsets in 0.7 to logical message offsets in 0.8. All offsets are now logical offsets starting at 0 and increasing by one for each message written to the partition log.
