### ISSUE TITLE
I need help, I set Configuration Type  dll to lib I have some error

### ISSUE THREAD

**Issue by molele2** [edenhill/librdkafka#967]
Description
===========

>trade_kafka_producer.obj : error LNK2001: unresolved external symbol _optind
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Topic * __cdecl RdKafka::Topic::create(class RdKafka::Handle *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class RdKafka::Conf *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (__imp_?create@Topic@RdKafka@@SAPAV12@PAVHandle@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAVConf@2@AAV45@@Z)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) int __cdecl RdKafka::wait_destroyed(int)" (__imp_?wait_destroyed@RdKafka@@YAHH@Z)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::version_str(void)" (__imp_?version_str@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) int __cdecl RdKafka::version(void)" (__imp_?version@RdKafka@@YAHXZ)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::get_debug_contexts(void)" (__imp_?get_debug_contexts@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Conf * __cdecl RdKafka::Conf::create(enum RdKafka::Conf::ConfType)" (__imp_?create@Conf@RdKafka@@SAPAV12@W4ConfType@12@@Z)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class RdKafka::Producer * __cdecl RdKafka::Producer::create(class RdKafka::Conf *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (__imp_?create@Producer@RdKafka@@SAPAV12@PAVConf@2@AAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl RdKafka::err2str(enum RdKafka::ErrorCode)" (__imp_?err2str@RdKafka@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4ErrorCode@1@@Z)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) const RdKafka::EventCb::`vftable'" (__imp_??_7EventCb@RdKafka@@6B@)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol _optarg
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) const RdKafka::PartitionerCb::`vftable'" (__imp_??_7PartitionerCb@RdKafka@@6B@)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol _getopt
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) const RdKafka::DeliveryReportCb::`vftable'" (__imp_??_7DeliveryReportCb@RdKafka@@6B@)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall RdKafka::DeliveryReportCb::DeliveryReportCb(void)" (__imp_??0DeliveryReportCb@RdKafka@@QAE@XZ)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall RdKafka::EventCb::EventCb(void)" (__imp_??0EventCb@RdKafka@@QAE@XZ)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall RdKafka::PartitionerCb::PartitionerCb(void)" (__imp_??0PartitionerCb@RdKafka@@QAE@XZ)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall RdKafka::EventCb::~EventCb(void)" (__imp_??1EventCb@RdKafka@@UAE@XZ)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall RdKafka::PartitionerCb::~PartitionerCb(void)" (__imp_??1PartitionerCb@RdKafka@@UAE@XZ)
1>trade_kafka_producer.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall Rd

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Please fill out the Checklist above.

Also specify what toolchain you are using and your full commandline.
