### ISSUE TITLE
How to consume multiple partitions in a single consumer?

### ISSUE THREAD

**Issue by smartcat2010** [edenhill/librdkafka#970]
Our kafka version is 0.8.2.1, the master branch librdkafka reports error when connecting it(I've already specified "broker.version.fallback" as "0.8.2.1"). Then I use librdkafka version 0.8, then it works.
 
Now the question is, I found Consumer::start could only specify a single partition. If our kafka partitions are not equal with(usually multiple times more than) the number of consumers, then how could we achieve good load-balance?  The ideal way may be using some API to get total partition number in the topic, then allocate them evenly among all consumers in this group.

**Comment by edenhill** [comment]
I suggest using the new KafkaConsumer and creating an absolute partition set you wish to consume (TopicPartition vector) which you pass to assign().

**Comment by smartcat2010** [comment]
Our company's kafka version is 0.8.2.1. The latest master version and 0.9 version rdkafka can't connect to it even I specify "conf->set("broker.version.fallback", "0.8.2.1", errstr)" in my code. If I use rdkafka version 0.8, it could successfully connect to kafka but the KafkaConsumer class is not supported. 
The only way for me, is to install kafka 0.10? But that needs heavy data transport for us.

**Comment by edenhill** [comment]
The KafkaConsumer should work with older brokers if you use the assign() API rather than subscribe().
Can you provide some librdkafka and broker logs to clarify what "can't connect" means.

Thanks

**Comment by mtrienis** [comment]
@edenhill 

> The KafkaConsumer should work with older brokers if you use the assign() API rather than subscribe().

Does this mean that the rdkafka_consumer_example.cpp will not work with 0.8.2.x until we modify it to use assign() instead subscribe()?

I'm running rdkafka_consumer_example.cpp againt against kafka 0.8.2.2 and the output can be found below. 

https://gist.github.com/mtrienis/5486395bd568c5eded446778f1c7d885

**Comment by edenhill** [comment]
assign() should work with 0.8.2 brokers but you are using the subscription interface (just the topic name) rather than the assign interface (topic:partition)

**Comment by mtrienis** [comment]
Thanks!
