### ISSUE TITLE
 What would rdkafka do when Kafka  server close the idle connection?

### ISSUE THREAD

**Issue by DavidLiuXh** [edenhill/librdkafka#971]
Description
===========
If no new messages are generated for a long time, kafka  server will close the idle connection, so how does rakafka handle for producer and consumer?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
librdkafka will reconnect to the broker when the connection goes down.
