### ISSUE TITLE
Unable to set the security.protocol to sasl_plaintext

### ISSUE THREAD

**Issue by lustgraaf** [edenhill/librdkafka#972]
Description
===========
I'm trying to connect to my Kafka cluster with kerberos enabled using the rdkafka_exmple. Just for testing to see if I can consume and produce messages before I start writing my Python code around it.

Return message: `% Invalid value for configuration property "security.protocol"`

When I remove the security protocol it ends with an error: `1482931184.842 RDKAFKA-7-BROKERFAIL: rdkafka#producer-1: broker-fqdn:6667/bootstrap: failed: err: Local: Broker transport failure: (errno: Resource temporarily unavailable)`

What am I missing here?

How to reproduce
================
sudo examples/rdkafka_example -P -d protocol,security,broker -t test -b broker-fqdn:6667 -X api.version.request=true -X broker.version.fallback=0.10.0 -X security.protocol=sasl_plaintext

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): clone from master on 28-12-2016
 - [x] Apache Kafka version: 0.10.0 (Hortonworks)
 - [x] librdkafka client configuration: Not changed
 - [x] Operating system: Ubuntu 12.04
 - [x] Using the legacy Consumer: No, just testing the Producer for now.
 - [x] Using the high-level KafkaConsumer: No, just testing the Producer for now
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [x] Critical issue: Unable to use sasl_plaintext

**Comment by edenhill** [comment]
Config Option syntax is -X key=val with no spaces around the equal sign

**Comment by lustgraaf** [comment]
Just fixed that mistake, and edit the initial post.

`-X security.protocol=sasl_plaintext` results in `% Invalid value for configuration property "security.protocol"`

**Comment by edenhill** [comment]
It seems your librdkafka was not compiled with SASL support (you can check the builtin.features property for sasl)

**Comment by edenhill** [comment]
Run this command to see what features your librdkafka was built with:
```
$ examples/rdkafka_example -X builtin.features
builtin.features = gzip,snappy,ssl,sasl,regex,lz4
```
