### ISSUE TITLE
Can Consumer get new message in queue every 10 minutes

### ISSUE THREAD

**Issue by vungoctho** [edenhill/librdkafka#973]
Description
===========
Hi,
Can we configure the consumer will get the messages every 10 minutes? 
As I know, we can use the configure _fetch.wait.max.ms_, is that correct and is there any else configuration to do that?

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag): 0.9.1
 - [ ] Apache Kafka version: kafka_2.11-0.10.0.0
 - [ ] librdkafka client configuration:
 - [ ] Operating system: Windows 10
 - [ ] Using the legacy Consumer
 - [ X] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by vungoctho** [comment]
#https://github.com/ah-/rdkafka-dotnet/issues/102

**Comment by edenhill** [comment]
`fetch.wait.max.ms` restricts the *maximum* wait time, not the minimum one which you seem to be after.

I suggest you look into the pause/resume APIs which lets you pause and resume consumtion at your own discretion.

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1672

**Comment by vungoctho** [comment]
Thanks for your suggestion.
