### ISSUE TITLE
Consumer consume method returns a NULL message

### ISSUE THREAD

**Issue by zkaiwen** [edenhill/librdkafka#975]
Description
===========
When using the Consumer object to consume from the queue, it returns a message pointing to NULL. What would be the reason for this case instead of returning a message object that has an error flag set. I have a KafkaConsumer consuming from the same topic and it's consuming all the messages correctly. The reason why I'm also using the Consumer object  is because I need to start consuming at specific offsets in the queue to reprocess certain pieces of data. Using the Consumer object I can set the offset using the start method to start consuming from a desired location in the queue. I have double checked the offset and partition and topic I am consuming from. 

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 9.2
 - [x] Apache Kafka version: 0.10
 - [ ] librdkafka client configuration:
 - [x] Operating system: Centos7
 - [x] Using the legacy Consumer Yes
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
See this:
https://github.com/edenhill/librdkafka/wiki/Manually-setting-the-consumer-start-offset

**Comment by halafawy** [comment]
Any update about this, i check the above link, and this what i'm implementing, but Consume API return null message although when increase timeout it works and get a message but not always, I tried timeout of 5000 milliseconds and also with this timeout some calls to Consume API return null message as well.

I'm Using .Net client

**Comment by edenhill** [comment]
Make sure to allow for at least session.timeout.ms to elapse before expecting a message, if you are unlucky to trigger a full rebalance.
