### ISSUE TITLE
TopicPartition create function does not have offset argument

### ISSUE THREAD

**Issue by zkaiwen** [edenhill/librdkafka#978]
Description
===========
Following the wiki to manually set the offset using KafkaConsumer, the C++ Direct assign() with no subscription example creates a TopicPartition object with three arguments. The API only lists two arguments (the offset is not listed as an argument). Furthermore, when updating the code to the current branch and compiling, there is a compile error stating that two arguments is expected instead of three. Just wondering if I'm am missing something here. Thanks

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
v0.9.2-126-g0b0ccec
 - [x] Apache Kafka version: 
0.10
 - [ ] librdkafka client configuration:
 - [x] Operating system:
centos7
 - [ ] Using the legacy Consumer
 - [x] Using the high-level KafkaConsumer
yes
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
You are right, the offset-supporting create() hasn't been pushed yet.
I suggest you use set_offset() (which is available on master) for now.

**Comment by edenhill** [comment]
Merged to master now

**Comment by yayuntian** [comment]
Can you give an example? No interface for set_offset () was found, thank you very much

**Comment by edenhill** [comment]
@yayuntian The new set_offset() API was pushed to master yesterday:
https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1072

There are some examples here:
https://github.com/edenhill/librdkafka/wiki/Manually-setting-the-consumer-start-offset#c-example-1

**Comment by yayuntian** [comment]
@edenhill 
Thank you, find the usage, in fact, the  C example should use "rd_kafka_topic_partition_list_find" in rdkafka.h   not "rd_kafka_topic_partition_find"
