### ISSUE TITLE
when enable stats module, producer maybe memleak

### ISSUE THREAD

**Issue by HeChuanXUPT** [edenhill/librdkafka#980]
Description
===========
after my program  enable stats, it has memleak problem.
when I comment the code below, the memory recovered.

How to reproduce
================
produce mode
enable stats
```
static int stats_cb (rd_kafka_t *rk, char *json, size_t json_len, void *opaque)
{
    // do nothing
    return 0;
}

rd_kafka_conf_set_stats_cb(conf, stats_cb);
rd_kafka_conf_set(conf, "statistics.interval.ms", "10000",errstr, sizeof(errstr))
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):0.9.2
 - [x] Apache Kafka version: 0.10.0.1
 - [x] librdkafka client configuration:
1.  broker.version.fallback=0.8.2
2. statistics.interval.ms=10000
3. rd_kafka_conf_set_log_cb(conf, logger);
 - [x] Operating system: linux
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
Is the stats_cb being called?
Which part are you commenting out to stop the leak?

**Comment by HeChuanXUPT** [comment]
yes, stats_cb has being called. I tried to print something.
when only comment 2 lines, the leak stop
```
// rd_kafka_conf_set_stats_cb(conf, stats_cb);
// rd_kafka_conf_set(conf, "statistics.interval.ms", "10000",errstr, sizeof(errstr))

```

**Comment by edenhill** [comment]
Okay, can you try running your program with valgrind to find the source of the leak?
`valgrind --suppressions=librdkafka/tests/librdkafka.suppressions ./your-program ..`

**Comment by HeChuanXUPT** [comment]
got error when use vargrind
#valgrind --suppressions=librdkafka.suppressions ./test

> ==18795== Memcheck, a memory error detector
> ==18795== Copyright (C) 2002-2010, and GNU GPL'd, by Julian Seward et al.
> ==18795== Using Valgrind-3.6.0 and LibVEX; rerun with -h for copyright info
> ==18795== Command: ./test
> ==18795== 
> location should be "...", or should start with "fun:" or "obj:"
> ==18795== FATAL: in suppressions file "librdkafka.suppressions" near line 131:
> ==18795==    location should be "...", or should start with "fun:" or "obj:"
> ==18795== exiting now.

I have a question,
As a producer :
1. has nothing to produce in a while
2. enable stats
3. not call rd_kafka_poll(rk, 0) in a while
does the producer will still collect stat data, and not free them ?

**Comment by edenhill** [comment]
Stats events will be enqueued every statistics  interval but only trigger the stats_cb callback when you call poll(). If you dont call poll() it will seem as if memory is leaking but it is only building up awaiting your call.

**Comment by edenhill** [comment]
This thread design is deliberate.
Spontaneously calling application callbacks from internal librdkafka threads might seem practical, but it forces the application developer to understand, implement and maintain proper locking, etc, which many people will get wrong.
Having the callback called in one of the application's threads by explicitly calling poll() avoids this problem, and if the developer is well-versed enough in thread programming it should be fairly simple to add its own polling thread to the application.
