### ISSUE TITLE
segfault with php-rdkafka

### ISSUE THREAD

**Issue by allyraza** [edenhill/librdkafka#981]
Description
===========

I am running librdkafaka with php-rdkafka, I copied one of the simple producer example and it throws a segfault.

How to reproduce
================

I installed php70, php70-librdkafka, php70-rdkafka with homebrew and copied the code snippet and throws an error.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 0.9.3
 - [x] Apache Kafka version: 0.10
 - [ ] librdkafka client configuration:
 - [x] Operating system: OSX El Capitan ]
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

Program received signal SIGSEGV, Segmentation fault.
0x000000010455bc87 in rd_kafka_new ()
   from /usr/local/opt/librdkafka/lib/librdkafka.1.dylib

**Comment by edenhill** [comment]
php-rdkafka client issues should typically be filed with that project.

Can you paste your PHP code?

**Comment by allyraza** [comment]
```php
$k = new Producer;
$k->setLogLevel(LOG_DEBUG);
$k->addBrokers('localhost');
$topic = $k->newTopic("events");
$topic->produce(0, 0, "Message data");
```

**Comment by edenhill** [comment]
That seems okay to me, so Im out of ideas.
Please file an issue with php-rdkafka.
