### ISSUE TITLE
Please how latency < 1ms

### ISSUE THREAD

**Issue by rudolfvavra** [edenhill/librdkafka#984]
Description
===========
Hi please could you help us how we can do latency smaller than 1ms? We have latency 500-2ms;

Producer
    # 'batch.num.messages': 1000,
    # 'queue.buffering.max.ms': 5,
    # 'queued.min.messages': 1000,
    #  'request.timeout.ms': 10,
  confProducer = {
   'api.version.request': api_version_request,
   'batch.num.messages': 100,
   'bootstrap.servers': args.brokers,
   'error_cb': error_cb,
   'message.max.bytes': 100000,
   'fetch.wait.max.ms': 1,
   'fetch.error.backoff.ms': 1,
   'queue.buffering.max.ms': 1,
   'socket.blocking.max.ms': 1,
   'default.topic.config': {
     'request.required.acks': 0,
     'produce.offset.report': True,
     'offset.store.sync.interval.ms': 0,
     'auto.offset.reset': 'earliest'
   }
  }

Consumer
    #  'auto.commit.interval.ms': 50,
    #  'socket.timeout.ms': 100,
    #  'statistics.interval.ms': 5,
    #  'fetch.wait.max.ms' : 5,
    #  'enable.auto.commit': True,
    # 'auto.commit.interval.ms': 5,
    #  'socket.blocking.max.ms': 1,
    conf = {
      'api.version.request': api_version_request,
      'bootstrap.servers': brokers,
      'error_cb': error_cb,
      'fetch.wait.max.ms': 5,
      'group.id': group,
      'on_commit': print_commit_result,
      'session.timeout.ms': 6000,
      'default.topic.config': {
        'request.required.acks': 0,
        'offset.store.sync.interval.ms': 0,
        'auto.offset.reset': 'earliest'
      }
    }

Checklist
=========
Please provide the following information:
   kafka/libs/kafka_2.11-0.10.1.0-test.jar.asc
   librdkafka-0.9.2-RC1
   Linux 2.6.32-642.4.2.el6.x86_64 #1  x86_64 x86_64 x86_64 GNU/Linux
   latest confluent-kafka-python

Log
=========
INFO: Committed offsets for: [TopicPartition{topic=topic-1-16,partition=0,offset=118606773,error=None}]
1483628162.64
1483628162.63
        INFO: Latency samples: 14.6501064301, 14.6598815918, 14.6799087524, 14.6999359131, 14.3401622772, 4.54020500183 
        INFO: Topic:    topic-1-16
                partition:      [0]
                current offset:         118649320
                published at:           1483628162.63457
                consumed at:          1483628162.63911
                last latency:             4.54020500183
        INFO: End of partion event: % topic-1-16 [0] reached end at offset 118685616

Thank you

**Comment by edenhill** [comment]
Please try latest master, I've made good latency improvements there since 0.9.2-RC1

**Comment by rudolfvavra** [comment]
Thank you
