### ISSUE TITLE
KIP-4: implement Topic admin APIs

### ISSUE THREAD

**Issue by jeffwidman** [edenhill/librdkafka#986]
CreateTopic api landed in Kafka 0.10.1.x

It'd be useful to have this supported by librdkafka

**Comment by InKolev** [comment]
Is there an option to specify the number of partitions to create with the topic, as it is in the Java client?

Thanks in advance.

**Comment by edenhill** [comment]
This feature is not yet implement, but when it is it will allow the partition count, etc, to be specified.

**Comment by InKolev** [comment]
@edenhill Thanks for the quick response.

**Comment by Summerxwu** [comment]
Is there any way to specify the replication factor of the topic which need to be created ?

**Comment by edenhill** [comment]
@Summerxwu when this API has been implemented: yes

**Comment by MrDHat** [comment]
Since this is kind of a blocker for anyone exploring languages other than Java (Node in our case) for Kafka, do we see this somewhere in the roadmap?

**Comment by hjespers** [comment]
@MrDHat the other option is to add AdminClient API support in Confluent REST Proxy and that would expose it to all languages but that is also a roadmap item at the moment and is independent of the librdkafka effort to support these capabilities.

**Comment by llamahunter** [comment]
What's the schedule to support the admin api interfaces added to the kafka protocol?

**Comment by edenhill** [comment]
Scheduled for Q1

**Comment by jpscaduto** [comment]
Do we have a line of sight into when KIP-4 may be released?

**Comment by edenhill** [comment]
Target is mid Q2
