### ISSUE TITLE
Poor producer performance on Windows

### ISSUE THREAD

**Issue by evildiamond** [edenhill/librdkafka#987]
Description
===========
I'm sorry I meet 2 questions and i can't fix it, cause my English is poor. Please help me , thanks a lot.
1. I run the rdkafka_example.exe, one for producer and one for consumer.When i use producer send a message , the consumer print timestamp not avaliable. Both two and broker run on the same machine( win 7).
2. When i use rdkafka_performance.c to test performance on my  machine, it seems that 16Mb/sec  is the upper bound with consumer. Can I promote it?  And when i use  kafka-consumer-perf-test.bat to test, it can up to 90Mb/sec which use 10 threads. Does one thread is the same with one consumer? (borker on redhat 6.0, producer and consumer on win 7) 

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):  0x00090301
 - [x] Apache Kafka version:  kafka_2.10-0.10.1.0
 - [x] librdkafka client configuration: default
 - [x] Operating system: win7
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer  
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
1. For timestamps to work you'll need to enable protocol feature detection by setting the `api.version.request` config property to true. E.g.: `rdkafka_example -X api.version.request=true -b yourbroker ...`

2. That does sound low. What message sizes do you have? Any compression? The number of threads should not matter since no processing is done per message.

**Comment by edenhill** [comment]
2. What toolchain are you using to build librdkafka on Win32?

**Comment by evildiamond** [comment]
Thanks for your answer.
Now I solved the first problem with your guide. 
And the second problem i got a error which 16Mb/s should be 16MB/s. The message size I used was 100 bytes, but when i changed message size, it was always this number. I am using  the MSVC to bulid librdkafka.

**Comment by evildiamond** [comment]
By the way, no compression, thanks. @edenhill

**Comment by edenhill** [comment]
rdkafka_performance wont compile on MSVC, did you fix that? :)

Ive noted that the consumer performance is very poor on Windows, trying to establish why that is.

**Comment by arnath** [comment]
Is there any update on this issue?

**Comment by edenhill** [comment]
It would be interesting to see what numbers you are getting on librdkafka v0.11.1 using `linger.ms=50` (or higher)
