### ISSUE TITLE
dlsym for rd_kafka_conf_set_dr_cb, seg fault

### ISSUE THREAD

**Issue by blandings** [edenhill/librdkafka#988]
Description
===========
I want to load librdkafka dynamically. When I call rd_kafka_conf_set_dr_cb, I get a segmentation fault. I haven't been able to find a good solution on other places. How  might I fix this? I need a synchronous producer, so there is no way around this issue.

Here is the backtrace:

Program terminated with signal 11, Segmentation fault.
#0  rd_kafka_conf_set_dr_cb (conf=0x7f379a2fcbe0 <rd_kafka_conf_new>, 
    dr_cb=0x4006d0 <syncProduceDrCb(rd_kafka_s*, void*, unsigned long, rd_kafka_resp_err_t, void*, void*)>)
    at rdkafka_conf.c:1383
1383		conf->dr_cb = dr_cb;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-105.el7.x86_64
(gdb) bt
#0  rd_kafka_conf_set_dr_cb (conf=0x7f379a2fcbe0 <rd_kafka_conf_new>, 
    dr_cb=0x4006d0 <syncProduceDrCb(rd_kafka_s*, void*, unsigned long, rd_kafka_resp_err_t, void*, void*)>)
    at rdkafka_conf.c:1383
#1  0x0000000000400830 in main () at producer.C:84

How to reproduce
================
Here is my code:

#include <stdio.h>
#include <stdlib.h>
#include <dlfcn.h>

#include <librdkafka/rdkafka.h>
#define MAX_SYMBOL_NAME 80

/* Producer Callback */
void syncProduceDrCb (
  rd_kafka_t*         rk,
  void*               payload,
  size_t              len,
  rd_kafka_resp_err_t err,
  void*               opaque,
  void*               msg_opaque)
{
  rd_kafka_resp_err_t *errp = (rd_kafka_resp_err_t *)msg_opaque;
  *errp = err;
}

int main() {
  const char* brokers = "localhost:9092";
  const char* topic = "fs0";

  char* dlerr;
  char symbolName[MAX_SYMBOL_NAME];

  /* Library Handle */
  void* libHandleP;

  /* Function pointers */
  rd_kafka_conf_t* (*ldKafka_conf_new)(); // rd_kafka_conf_new
  void (*ldKafka_set_dr_cb)(rd_kafka_conf_t*,
                            void (*)(rd_kafka_t*, void*, size_t, rd_kafka_resp_err_t, void*, void*));

  /* Object pointers */
  rd_kafka_conf_t* ldKafka_conf_t;

  dlerror();
  libHandleP = dlopen("librdkafka.so", RTLD_NOW | RTLD_GLOBAL);
  if (libHandleP == NULL)
  {
    dlerr = dlerror();
    printf("LWE_KAFKA: Failed to load librdkafka library %s: (dlopen)", dlerr);
    return -1;
  }

  *(void **)(&ldKafka_conf_new) = dlsym(libHandleP, "rd_kafka_conf_new");
  if ((dlerr = dlerror()) != NULL)
  {
    printf("Could not load symbol for rd_kafka_conf_new %s: (dlsym)\n", dlerr);
    return -1;
  }

  ldKafka_conf_t = (rd_kafka_conf_t *) (*ldKafka_conf_new);
  if (ldKafka_conf_t == NULL)
  {
    printf("Could not create a new kafka configuration");
    return -1;
  }

  *(void **)(&ldKafka_set_dr_cb) = dlsym(libHandleP, "rd_kafka_conf_set_dr_cb");
  if ((dlerr = dlerror()) != NULL)
  {
    printf("Could not load symbol for rd_kafka_conf_set_dr_cb: (dlsym)\n", dlerr);
    return -1;
  }

  ldKafka_set_dr_cb(ldKafka_conf_t, syncProduceDrCb);

  return 0;
}

Checklist
=========
Please provide the following information:

 - [ ] librdkafka version (release number or git tag):
 - [ ] Apache Kafka version: 
 - [ ] librdkafka client configuration:
 - [ ] Operating system:
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
I'm not sure but I think you want to make the function pointers as pointers, e.g.:
`rd_kafka_conf_t (*ldKafka_conf_new)(); `
and then use accordingly.

**Comment by blandings** [comment]
It looks like the copy/paste omitted the *. Here is an attachment of my code.

Also, rd_kafka_conf_new returns a pointer to rd_kakfka_conf_t. Hence, the correct function pointer is defined as

rd_kafka_conf_t *(*ldKafka_conf_new())(); or

rd_kafka_conf_t (*(*ldKafka_conf_new())());


[producer.C.txt](https://github.com/edenhill/librdkafka/files/691552/producer.C.txt)

**Comment by edenhill** [comment]
You are not calling conf_new(), just return its pointer here:
`  ldKafka_conf_t = (rd_kafka_conf_t *) (*ldKafka_conf_new);`
If you loose the explicit cast you'll get the proper error.
