### ISSUE TITLE
Quotas (max around 10-11 mbps)

### ISSUE THREAD

**Issue by AKR2015** [edenhill/librdkafka#989]
Description
===========
Hello,
I am using 0.9.2 librdkafka version with 0.9.0 version of kafka brokers. Its 3 node kafka cluster on redhat.

I am running single producer on windows machine where i am not able to see more then 10-11mbps of throughput.  If i start another producer from different window machine, i see the throughput reduced to around 5mbps. Both of these producers are producing the message on different topic.

In any situation, i dont get more then 10 mbps throughput while producing to the queue.
Not sure if this is due to default quota that is getting shared acros clients. In my case both both of the producer has the same client.id="rdkafka"

https://cwiki.apache.org/confluence/display/KAFKA/KIP-13+-+Quotas

I configure this in broker server.properties, but did not see any change.
**quota.producer.default = 52428800
quota.consumer.default = 52428800**

tried to override this to client level using below command, but no help.
**bin/kafka-configs.sh  --zookeeper localhost:2181 --alter --add-config 'producer_byte_rate=52428800,consumer_byte_rate=52428800' --entity-name rdkafka --entity-type clients**

these two are in server.props too.
quota.window.size.seconds = 1
quota.window.num = 11

Any help will be really appreciated.

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ 0.9.2] librdkafka version (release number or git tag):
 - [0.9.1 ] Apache Kafka version: 
 - [ 0.9.2] librdkafka client configuration:
 - [ X] Operating system:
 - [ ] Using the legacy Consumer
 - [ X] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment]
There seems to be some pretty significant performance degradation running on Windows.
In my test environment the Producer flats out at ~24MB/s (megabyte) and the Consumer consuming one partition at ~8MB/s which is incredibly slow.
Early analysis suggests the Windows LFH allocator might be the reason.

**Comment by edenhill** [comment]
Performance on Windows is issue #987

**Comment by abhit011** [comment]
@edenhill 

Is this the same issue ?  https://github.com/edenhill/librdkafka/issues/1067

Abhi

**Comment by edenhill** [comment]
@abhit011 Most likely yeah.

I'll spend some time the coming couple of weeks to look into this.

**Comment by abhit011** [comment]
Fine @edenhill
