### ISSUE TITLE
Some undefined symbols when linking to librdkafka++ under MacOSX

### ISSUE THREAD

**Issue by SkyToGround** [edenhill/librdkafka#994]
Description
===========
As one of my unit tests failed due to a bug where the timeout in flush() was ignored (thanks for fixing that bug btw), I downloaded, compiled and installed the latest version of librdkafka from the repository. When re-compiling my unit tests I got the following linker error:

```
Undefined symbols for architecture x86_64:
  "RdKafka::Topic::create(RdKafka::Handle*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, RdKafka::Conf*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)", referenced from:
      KafkaProducer::SetTopic(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in KafkaProducer.o
      KafkaProducer::MakeConnection() in KafkaProducer.o
  "RdKafka::Producer::create(RdKafka::Conf*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)", referenced from:
      KafkaProducer::MakeConnection() in KafkaProducer.o
ld: symbol(s) not found for architecture x86_64
```

The operating system used is MacOSX 10.11.6 (El Capitan) with the latest developer tools installed. My application is developed using Xcode but when compiling the project using CMake (and make) the compile fails with identical error messages.

When taking a look at the symbols in ```librdkafka++.dylib``` using ```nm```, ```Producer::create``` and ```Topic::Create``` is available. I.E. ```nm librdkafka++.dylib``` produces (amongst others) these two lines:

```
__ZN7RdKafka5Topic6createEPNS_6HandleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_4ConfERS8_
__ZN7RdKafka8Producer6createEPNS_4ConfERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

which can be translated using ```c++filt``` into

```
RdKafka::Topic::create(RdKafka::Handle*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RdKafka::Conf*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
RdKafka::Producer::create(RdKafka::Conf*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
```

The library is actually a x86_64 binary as illustrated by ```file```:

```
jonas@Muspelheim /u/l/lib> file librdkafka++.dylib 
librdkafka++.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```
Curiously, the calls to ```RdKafka::Conf::create()``` does not cause any linking error messages.

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag):
Commit: bbee686594d009a078758cba7070dbb3964f771c
 - [ ] Apache Kafka version: *Not applicable*
 - [ ] librdkafka client configuration: *Not applicable*
 - [x] Operating system: MacOSX 10.11.6
 - [ ] Using the legacy Consumer
 - [ ] Using the high-level KafkaConsumer
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by SkyToGround** [comment]
When writing about this issue I had already figured out the problem (and the solution) but I decided to create this issue anyway for posterity.

After a few hours I was finally able to determine that while CMake and Xcode uses clang for compilation, the configure-script provided with librdkafka prefers the gcc compiler if available. Last time I compiled librdkafka (a few months ago), gcc was not available and thus that version of librdkafka++ was compiled with clang. Since then, MacPorts had for some reason installed gcc 6 on my development machine and when again compiling librdkafka this compiler was used instead of clang. Due to small differences between the two compilers in how std::string is handled, only some of the member functions caused *undefined symbols* errors.

The solution to the problem was to force librdkafka to use clang by configuring the build process with the following command:

```
./configure --cc=clang --cxx=clang++
```

As I am not familiar with the build system used by librdkafka (except for how to invoke it), and thus I can not tell if there is an easy way to have it prefer clang when building on a computer running MacOSX. Even if is easy, I am not sure that it should be done. Either way, feel free to close this issue after having read my description Magnus.

**Comment by edenhill** [comment]
With standard xcode installed I believe 'gcc' is actually a 'clang' wrapper on OSX, but if you explicitly install the true gcc after that then they'll differ, yeah.

In your case where some of librdkafka had already been compiled with an older C++ compiler and then new bits compiled with a new one: I don't think there is any trivial way around that, you will need to reconfigure or at least 'make clean'.
